/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.player.sui.slotmachinebox;

import engine.lua.LuaObject;
import server.zone.objects.scene.SceneObject;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.creature.CreatureObject;
import system.io.StringTokenizer;
import engine.service.proto.BaseMessage;
import server.zone.objects.player.sui.SuiBox;
import server.zone.objects.player.sui.listbox.SuiListBox;
import system.lang.String;

include server.zone.packets.ui.SuiCreatePageMessage;

class SuiSlotMachineBox extends SuiListBox {

	protected unsigned int payoutBoxID;
	
	public SuiSlotMachineBox(CreatureObject player, unsigned int windowType, unsigned int payoutBox, unsigned int listBoxType = 0) {
		super(player, windowType, listBoxType);
		payoutBoxID = payoutBox;
	}
	
	public unsigned int getPayoutBoxID() {
		return payoutBoxID;
	}
	
}
