/*
Copyright (C) 2007 <SWGEmu>
 
This File is part of Core3.
 
This program is free software; you can redistribute 
it and/or modify it under the terms of the GNU Lesser 
General Public License as published by the Free Software
Foundation; either version 2 of the License, 
or (at your option) any later version.
 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
See the GNU Lesser General Public License for
more details.
 
You should have received a copy of the GNU Lesser General 
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 
Linking Engine3 statically or dynamically with other modules 
is making a combined work based on Engine3. 
Thus, the terms and conditions of the GNU Lesser General Public License 
cover the whole combination.
 
In addition, as a special exception, the copyright holders of Engine3 
give you permission to combine Engine3 program with free software 
programs or libraries that are released under the GNU LGPL and with 
code included in the standard release of Core3 under the GNU LGPL 
license (or modified versions of such code, with unchanged license). 
You may copy and distribute such a system following the terms of the 
GNU LGPL for Engine3 and the licenses of the other code concerned, 
provided that you include the source code of that other code when 
and as the GNU LGPL requires distribution of source code.
 
Note that people who make modified versions of Engine3 are not obligated 
to grant this special exception for their modified versions; 
it is their choice whether to do so. The GNU Lesser General Public License 
gives permission to release a modified version without this exception; 
this exception also makes it possible to release a modified version 
which carries forward this exception.
*/

package server.zone;

import engine.service.proto.BaseClientProxy;
import engine.service.proto.BasePacket;
import engine.core.ManagedObject;
import system.lang.ref.Reference;
import system.net.SocketAddress;
import system.net.Socket;

import server.login.account.Account;
import server.zone.objects.scene.SceneObject;
import server.zone.ZoneServer;

import engine.service.proto.events.BaseClientNetStatusCheckupEvent;
import engine.service.proto.events.BaseClientCleanupEvent;
import engine.service.proto.events.BaseClientNetStatusRequestEvent;
import engine.service.proto.events.BaseClientEvent;

import engine.log.Logger;

//@nonTransactional
class ZoneClientSession extends ManagedObject {
	transient protected BaseClientProxy session;
	
	@weakReference
	protected SceneObject player;

	protected unsigned int sessionID;
	
	protected Account account;
	
	protected unsigned int accountID;
	
	boolean disconnecting;
	
	public native ZoneClientSession(BaseClientProxy session);
			
	public native void disconnect();
	public native void disconnect(boolean doLock);
	
	public native void sendMessage(BasePacket msg);

	public native void balancePacketCheckupTime();
	
	public native void resetPacketCheckupTime();
	
	public native void closeConnection(boolean lockPlayer, boolean doLock = true);

	public native void info(final string msg, boolean force = false);
	
	public native void error(final string msg);

	public native string getAddress();
	
	// setters and getters
	public void setPlayer(SceneObject playerCreature) {
		if (playerCreature != player) {
			if (playerCreature == null && player != null) {
				// TODO: find a proper way to acqure zone server
				ZoneServer zoneServer = player.getZoneServer();
				
				if (zoneServer != null)
					zoneServer.decreaseOnlinePlayers();
			} else if (playerCreature != player) {
				// TODO: find a proper way to acqure zone server
				ZoneServer zoneServer = playerCreature.getZoneServer();
				
				if (zoneServer != null)
					zoneServer.increaseOnlinePlayers();
			}
		}
		
		player = playerCreature;
	}

	public void setSessionID(unsigned int id) {
		sessionID = id;
	}
	
	public void setAccount(Account acc) {
		account = acc;
	}
	
	public void setAccountID(unsigned int acc) {
		accountID = acc;
	}
	 

	@local
	public native BaseClientProxy getSession();
	
	public SceneObject getPlayer() {
		return player;
	}

	public unsigned int getSessionID() {
		return sessionID;
	}
	
	public unsigned int getAccountID() {
		return accountID;;
	}
	
	public native Account getAccount() {
		return account;
	}
}
