/*
Copyright (C) 2007 <SWGEmu>
 
This File is part of Core3.
 
This program is free software; you can redistribute 
it and/or modify it under the terms of the GNU Lesser 
General Public License as published by the Free Software
Foundation; either version 2 of the License, 
or (at your option) any later version.
 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
See the GNU Lesser General Public License for
more details.
 
You should have received a copy of the GNU Lesser General 
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 
Linking Engine3 statically or dynamically with other modules 
is making a combined work based on Engine3. 
Thus, the terms and conditions of the GNU Lesser General Public License 
cover the whole combination.
 
In addition, as a special exception, the copyright holders of Engine3 
give you permission to combine Engine3 program with free software 
programs or libraries that are released under the GNU LGPL and with 
code included in the standard release of Core3 under the GNU LGPL 
license (or modified versions of such code, with unchanged license). 
You may copy and distribute such a system following the terms of the 
GNU LGPL for Engine3 and the licenses of the other code concerned, 
provided that you include the source code of that other code when 
and as the GNU LGPL requires distribution of source code.
 
Note that people who make modified versions of Engine3 are not obligated 
to grant this special exception for their modified versions; 
it is their choice whether to do so. The GNU Lesser General Public License 
gives permission to release a modified version without this exception; 
this exception also makes it possible to release a modified version 
which carries forward this exception.
*/

/*import "objects/ObjectMap";*/

import "objects/scene/SceneObject";

import "managers/user/UserManager";
import "managers/guild/GuildManager";
import "managers/player/PlayerManager";
import "managers/crafting/CraftingManager";
import "managers/item/ItemManager";
import "managers/item/ItemConfigManager";
import "managers/resource/ResourceManager";
import "managers/loot/LootTableManager";
import "managers/bazaar/BazaarManager";
import "managers/bank/BankManager";
import "managers/mission/MissionManager";
import "managers/creature/CreatureManager";

import "../chat/ChatManager";

import "Zone";

include "../db/ServerDatabase";

interface ZoneServer {
	ZoneServer(int threadcount) {
		super(threadcount);
	}

	void start(int port, int conn);

	void stop();

	void startManagers();

	// object methods	
	void addObject(SceneObject obj, boolean doLock = true);

	SceneObject getObject(unsigned long oid, boolean doLock = true);

	SceneObject removeObject(unsigned long oid, boolean doLock = true);
	SceneObject removeObject(SceneObject obj, boolean doLock = true);

	boolean destroyObject(SceneObject obj, boolean doLock = true);

	SceneObject getCachedObject(unsigned long oid, boolean doLock = true);

	SceneObject removeCachedObject(unsigned long oid, boolean doLock = true);
	SceneObject removeCachedObject(SceneObject obj, boolean doLock = true);

	// administration methods
	boolean banUser(String name, String admin);
	
	boolean kickUser(String name, String admin);

	void changeUserCap(int amount = 50);

	void addTotalSentPacket(int count);
	void addTotalResentPacket(int count);

	void lock();
	void unlock();
	
	void increaseTotalDeletedPlayers();

	void printInfo();
	
	void fixScheduler();

	void changeMessageoftheDay(const String newMOTD);
	void loadMessageoftheDay();

	// getters
	ChatManager getChatManager();
	GuildManager getGuildManager();
	PlayerManager getPlayerManager();
	UserManager getUserManager();
	CraftingManager getCraftingManager();
	ItemManager getItemManager();
	ItemConfigManager getItemConfigManager();
	ResourceManager getResourceManager();
	LootTableManager getLootTableManager();
	BazaarManager getBazaarManager();
	BankManager getBankManager();
	MissionManager getMissionManager();
	CreatureManager getCreatureManager(int zone);
	
	Zone getZone(int index);
	
	String getServerName();
	
	boolean isServerLocked();
	boolean isServerOnline();
	boolean isServerOffline();
	boolean isServerLoading();
	int getServerState();
	
	int getConnectionCount();
	int getTotalPlayers();
	int getMaxPlayers();
	int getDeletedPlayers();

	unsigned long getStartTimestamp();
	
	unsigned long getNextCreatureID(boolean doLock = true);
	unsigned long getNextID(boolean doLock = true);
	unsigned long getNextCellID(boolean doLock = true);

	String& getMessageoftheDay();
	
	// setters
	void setServerState(int state);
	void setServerStateLocked();
	void setServerStateOnline();
}
