/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone;

import engine.service.proto.BaseClientProxy;
import engine.service.proto.BasePacket;
import engine.core.ManagedObject;
import system.lang.ref.Reference;
import system.net.SocketAddress;
import system.net.Socket;

import server.zone.objects.scene.SceneObject;
import server.zone.ZoneServer;

import engine.service.proto.events.BaseClientNetStatusCheckupEvent;
import engine.service.proto.events.BaseClientCleanupEvent;
import engine.service.proto.events.BaseClientNetStatusRequestEvent;
import engine.service.proto.events.BaseClientEvent;

import system.lang.Time;
import system.util.HashSet;
import system.util.HashTable;
import system.util.VectorMap;
import engine.log.Logger;

//@nonTransactional
class ZoneClientSession extends ManagedObject {
	transient protected BaseClientProxy session;
	
	@dereferenced
	protected VectorMap<unsigned int, unsigned long> characters;
	
	@dereferenced
	protected VectorMap<unsigned int, unsigned long> bannedCharacters;
	
	@weakReference
	protected SceneObject player;

	protected unsigned int sessionID;

	protected unsigned int accountID;
	
	boolean disconnecting;
	
	@dereferenced
	protected Time commandSpamCooldown;
	
	protected int commandCount;
	
	public native ZoneClientSession(BaseClientProxy session);
			
	public native void disconnect();
	public native void disconnect(boolean doLock);
	
	@dirty
	public native void sendMessage(BasePacket msg);

	public native void balancePacketCheckupTime();
	
	public native void resetPacketCheckupTime();
	
	public native void closeConnection(boolean lockPlayer, boolean doLock = true);

	public native void info(final string msg, boolean force = false);
	
	public native void error(final string msg);

	public native string getAddress();
	
	// setters and getters
	public native void setPlayer(SceneObject playerCreature);

	public void setSessionID(unsigned int id) {
		sessionID = id;
	}

	public void setAccountID(unsigned int acc) {
		accountID = acc;
	}
	
	public int getCommandCount() {
		return commandCount;
	}
	 
	public void increaseCommandCount() {
		commandCount = commandCount + 1;
	}
	
	public void resetCommandCount() {
		commandCount = 0;
	}
	
	@local
	public Time getCommandSpamCooldown() {
		return commandSpamCooldown;
	}

	@local
	public native BaseClientProxy getSession();
	
	@weakReference
	public SceneObject getPlayer() {
		return player;
	}

	public unsigned int getSessionID() {
		return sessionID;
	}
	
	public unsigned int getAccountID() {
		return accountID;
	}

	public native boolean hasCharacter(unsigned long cid, unsigned int galaxyId);

	public void addCharacter(unsigned long cid, unsigned int galaxyId) {
		characters.put(galaxyId, cid);	
	}
	
	public void addBannedCharacter(unsigned long cid, unsigned int galaxyId) {
		bannedCharacters.put(galaxyId, cid);
	}
	
	public int getCharacterCount() {
		return characters.size() + bannedCharacters.size();
	}
	
	public native int getCharacterCount(int galaxyId);
	
	public void resetCharacters() {
		characters.removeAll();
		bannedCharacters.removeAll();
	}
}
