/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.player.sui.messagebox;

import engine.lua.LuaObject;
import server.zone.objects.scene.SceneObject;
import server.zone.objects.creature.CreatureObject;
import engine.service.proto.BaseMessage;
import server.zone.objects.player.sui.SuiBox;
include server.zone.packets.ui.SuiCreatePageMessage;
import server.zone.objects.creature.CreatureObject;

class SuiMessageBox extends SuiBox {
	
	
	public SuiMessageBox(CreatureObject player, unsigned int windowType) {
		super(player, windowType, SuiBox.MESSAGEBOX);
		;
	}
	
	public native BaseMessage generateMessage();
	
	public boolean isMessageBox() {
		return true;
	}
	
}