/*
 *	server/zone/objects/creature/aigroup/LairGroup.cpp generated by engine3 IDL compiler 0.60
 */

#include "LairGroup.h"

#include "server/zone/objects/tangible/lair/LairObject.h"


// Imported class dependencies

#include "server/zone/objects/cell/CellObject.h"

#include "server/zone/objects/creature/PatrolPoint.h"

#include "server/zone/objects/manufactureschematic/craftingvalues/CraftingValues.h"

#include "server/zone/objects/creature/events/AiThinkEvent.h"

#include "server/zone/ZonePacketHandler.h"

#include "engine/service/DatagramServiceThread.h"

#include "server/zone/templates/tangible/LairObjectTemplate.h"

#include "server/zone/objects/creature/events/AiAwarenessEvent.h"

#include "engine/util/u3d/Coordinate.h"

#include "engine/util/Facade.h"

#include "server/zone/objects/creature/PatrolPointsVector.h"

#include "server/zone/objects/player/events/PlayerRecoveryEvent.h"

#include "server/zone/objects/creature/events/DespawnCreatureOnPlayerDissappear.h"

#include "engine/util/u3d/Quaternion.h"

#include "server/zone/managers/radial/RadialManager.h"

#include "server/zone/objects/draftschematic/DraftSchematic.h"

#include "server/zone/managers/creature/CreatureManager.h"

#include "server/zone/objects/creature/events/AiWaitEvent.h"

#include "server/zone/objects/building/BuildingObject.h"

#include "server/zone/objects/tangible/lair/HealLairEvent.h"

#include "server/zone/objects/tangible/sign/SignObject.h"

#include "server/zone/managers/planet/MapLocationTable.h"

#include "server/zone/managers/resource/ResourceManager.h"

#include "server/zone/managers/creature/StaticSpawnGroup.h"

#include "engine/util/u3d/QuadTreeNode.h"

#include "server/zone/objects/manufactureschematic/IngredientSlots.h"

#include "engine/core/Task.h"

#include "server/zone/managers/city/CityManager.h"

#include "server/zone/objects/player/badges/Badges.h"

#include "server/zone/templates/SharedObjectTemplate.h"

#include "server/zone/objects/tangible/DamageMap.h"

#include "server/zone/objects/manufactureschematic/ManufactureSchematic.h"

#include "engine/service/proto/BasePacketHandler.h"

#include "server/zone/ZoneProcessServer.h"

#include "server/zone/objects/tangible/weapon/WeaponObject.h"

#include "server/zone/objects/tangible/tool/SurveyTool.h"

#include "engine/util/u3d/QuadTreeEntry.h"

#include "server/zone/objects/scene/variables/PendingTasksMap.h"

#include "server/zone/managers/vendor/VendorManager.h"

#include "system/net/Packet.h"

#include "server/zone/objects/player/events/PlayerDisconnectEvent.h"

#include "server/zone/templates/tangible/SharedWeaponObjectTemplate.h"

#include "server/zone/objects/scene/variables/DeltaVector.h"

#include "server/zone/objects/tangible/tool/CraftingTool.h"

#include "system/util/SortedVector.h"

#include "server/zone/managers/name/NameManager.h"

#include "server/zone/managers/planet/PlanetManager.h"

#include "server/zone/objects/scene/variables/CustomizationVariables.h"

#include "server/zone/objects/creature/aigroup/AiGroupObserver.h"

#include "server/zone/managers/sui/SuiManager.h"

#include "server/zone/managers/crafting/CraftingManager.h"

#include "server/zone/packets/object/ObjectMenuResponse.h"

#include "server/zone/objects/player/sui/SuiBox.h"

#include "engine/service/proto/BaseClientProxy.h"

#include "server/zone/objects/tangible/TangibleObject.h"

#include "system/net/Socket.h"

#include "system/util/Vector.h"

#include "server/zone/objects/scene/WorldCoordinates.h"

#include "engine/service/proto/BasePacket.h"

#include "server/zone/managers/object/ObjectManager.h"

#include "server/zone/managers/creature/DynamicSpawnGroup.h"

#include "server/zone/objects/creature/AiAgent.h"

#include "system/io/ObjectOutputStream.h"

#include "server/zone/managers/planet/HeightMap.h"

#include "server/zone/managers/mission/MissionManager.h"

#include "server/zone/objects/creature/AiObserver.h"

#include "server/zone/managers/player/PlayerManager.h"

#include "system/thread/atomic/AtomicInteger.h"

#include "server/chat/room/ChatRoom.h"

#include "server/zone/managers/object/ObjectMap.h"

#include "engine/util/Observable.h"

#include "engine/service/Message.h"

#include "server/login/account/Account.h"

#include "server/zone/managers/minigames/ForageManager.h"

#include "server/chat/ChatManager.h"

#include "server/zone/objects/scene/SceneObject.h"

#include "system/io/ObjectInputStream.h"

#include "engine/util/ObserverEventMap.h"

#include "server/zone/managers/objectcontroller/ObjectController.h"

#include "server/zone/managers/guild/GuildManager.h"

#include "server/zone/objects/creature/CreatureObject.h"

#include "engine/core/ObjectUpdateToDatabaseTask.h"

#include "engine/util/Observer.h"

#include "server/zone/objects/area/ActiveArea.h"

#include "server/zone/ZoneHandler.h"

#include "server/zone/Zone.h"

#include "engine/core/ManagedObject.h"

#include "server/zone/managers/creature/CreatureTemplate.h"

#include "server/zone/objects/player/PlayerCreature.h"

#include "server/zone/managers/minigames/GamblingManager.h"

#include "server/zone/managers/creature/CreatureTemplateManager.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

#include "server/zone/managers/minigames/FishingManager.h"

#include "system/lang/Exception.h"

#include "server/zone/objects/player/ValidatedPosition.h"

#include "server/zone/ZoneClientSession.h"

#include "system/lang/Time.h"

#include "engine/util/u3d/QuadTree.h"

#include "engine/stm/TransactionalReference.h"

#include "server/zone/objects/player/TradeContainer.h"

#include "system/net/SocketAddress.h"

#include "server/zone/managers/holocron/HolocronManager.h"

#include "server/zone/managers/auction/AuctionManager.h"

#include "server/zone/managers/loot/LootManager.h"

#include "server/zone/ZoneServer.h"

#include "server/zone/managers/professions/ProfessionManager.h"

#include "server/zone/objects/creature/aigroup/AiGroup.h"

#include "system/util/VectorMap.h"

#include "server/zone/objects/scene/variables/StringId.h"

#include "server/zone/managers/stringid/StringIdManager.h"

#include "server/zone/objects/creature/events/AiMoveEvent.h"

/*
 *	LairGroupStub
 */

enum {RPC_ISLAIRGROUP__ = 6};

LairGroup::LairGroup() : AiGroup(DummyConstructorParameter::instance()) {
	LairGroupImplementation* _implementation = new LairGroupImplementation();
	ManagedObject::_setImplementation(_implementation);
	_implementation->_setStub(this);
}

LairGroup::LairGroup(DummyConstructorParameter* param) : AiGroup(param) {
}

LairGroup::~LairGroup() {
}


bool LairGroup::isLairGroup() {
	LairGroupImplementation* _implementation = (LairGroupImplementation*) _getImplementation();
	if (_implementation == NULL) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISLAIRGROUP__);

		return method.executeWithBooleanReturn();
	} else
		return _implementation->isLairGroup();
}

DistributedObjectServant* LairGroup::_getImplementation() {

	_updated = true;
	return dynamic_cast<DistributedObjectServant*>(getForUpdate());}

void LairGroup::_setImplementation(DistributedObjectServant* servant) {
	setObject(dynamic_cast<LairGroupImplementation*>(servant));
}

/*
 *	LairGroupImplementation
 */

LairGroupImplementation::LairGroupImplementation(DummyConstructorParameter* param) : AiGroupImplementation(param) {
	_initializeImplementation();
}


LairGroupImplementation::~LairGroupImplementation() {
}


void LairGroupImplementation::finalize() {
}

void LairGroupImplementation::_initializeImplementation() {
	_setClassHelper(LairGroupHelper::instance());

	_serializationHelperMethod();
	_serializationHelperMethod();
}

void LairGroupImplementation::_setStub(DistributedObjectStub* stub) {
	_this = (LairGroup*) stub;
	AiGroupImplementation::_setStub(stub);
}

DistributedObjectStub* LairGroupImplementation::_getStub() {
	return _this;
}

LairGroupImplementation::operator const LairGroup*() {
	return _this;
}

Object* LairGroupImplementation::clone() {
	return dynamic_cast<Object*>(new LairGroupImplementation(*this));
}


void LairGroupImplementation::lock(bool doLock) {
}

void LairGroupImplementation::lock(ManagedObject* obj) {
}

void LairGroupImplementation::rlock(bool doLock) {
}

void LairGroupImplementation::wlock(bool doLock) {
}

void LairGroupImplementation::wlock(ManagedObject* obj) {
}

void LairGroupImplementation::unlock(bool doLock) {
}

void LairGroupImplementation::runlock(bool doLock) {
}

void LairGroupImplementation::_serializationHelperMethod() {
	AiGroupImplementation::_serializationHelperMethod();

	_setClassName("LairGroup");

}

void LairGroupImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		String _name;
		_name.parseFromBinaryStream(stream);

		uint16 _varSize = stream->readShort();

		int _currentOffset = stream->getOffset();

		if(LairGroupImplementation::readObjectMember(stream, _name)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool LairGroupImplementation::readObjectMember(ObjectInputStream* stream, const String& _name) {
	if (AiGroupImplementation::readObjectMember(stream, _name))
		return true;

	if (_name == "lair") {
		TypeInfo<ManagedReference<LairObject* > >::parseFromBinaryStream(&lair, stream);
		return true;
	}


	return false;
}

void LairGroupImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = LairGroupImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int LairGroupImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	String _name;
	int _offset;
	uint16 _totalSize;
	_name = "lair";
	_name.toBinaryStream(stream);
	_offset = stream->getOffset();
	stream->writeShort(0);
	TypeInfo<ManagedReference<LairObject* > >::toBinaryStream(&lair, stream);
	_totalSize = (uint16) (stream->getOffset() - (_offset + 2));
	stream->writeShort(_offset, _totalSize);


	return 1 + AiGroupImplementation::writeObjectMembers(stream);
}

LairGroupImplementation::LairGroupImplementation() : AiGroupImplementation() {
	_initializeImplementation();
}

bool LairGroupImplementation::isLairGroup() {
	// server/zone/objects/creature/aigroup/LairGroup.idl():  		return true;
	return true;
}

/*
 *	LairGroupAdapter
 */

LairGroupAdapter::LairGroupAdapter(LairGroupImplementation* obj) : AiGroupAdapter(obj) {
}

Packet* LairGroupAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	Packet* resp = new MethodReturnMessage(0);

	switch (methid) {
	case RPC_ISLAIRGROUP__:
		resp->insertBoolean(isLairGroup());
		break;
	default:
		return NULL;
	}

	return resp;
}

bool LairGroupAdapter::isLairGroup() {
	return ((LairGroupImplementation*) impl)->isLairGroup();
}

/*
 *	LairGroupHelper
 */

LairGroupHelper* LairGroupHelper::staticInitializer = LairGroupHelper::instance();

LairGroupHelper::LairGroupHelper() {
	className = "LairGroup";

	Core::getObjectBroker()->registerClass(className, this);
}

void LairGroupHelper::finalizeHelper() {
	LairGroupHelper::finalize();
}

DistributedObject* LairGroupHelper::instantiateObject() {
	return new LairGroup(DummyConstructorParameter::instance());
}

DistributedObjectServant* LairGroupHelper::instantiateServant() {
	return new LairGroupImplementation(DummyConstructorParameter::instance());
}

DistributedObjectAdapter* LairGroupHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new LairGroupAdapter((LairGroupImplementation*) obj->_getImplementation());

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

