/*
Copyright (C) 2007 <SWGEmu>
 
This File is part of Core3.
 
This program is free software; you can redistribute 
it and/or modify it under the terms of the GNU Lesser 
General Public License as published by the Free Software
Foundation; either version 2 of the License, 
or (at your option) any later version.
 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
See the GNU Lesser General Public License for
more details.
 
You should have received a copy of the GNU Lesser General 
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 
Linking Engine3 statically or dynamically with other modules 
is making a combined work based on Engine3. 
Thus, the terms and conditions of the GNU Lesser General Public License 
cover the whole combination.
 
In addition, as a special exception, the copyright holders of Engine3 
give you permission to combine Engine3 program with free software 
programs or libraries that are released under the GNU LGPL and with 
code included in the standard release of Core3 under the GNU LGPL 
license (or modified versions of such code, with unchanged license). 
You may copy and distribute such a system following the terms of the 
GNU LGPL for Engine3 and the licenses of the other code concerned, 
provided that you include the source code of that other code when 
and as the GNU LGPL requires distribution of source code.
 
Note that people who make modified versions of Engine3 are not obligated 
to grant this special exception for their modified versions; 
it is their choice whether to do so. The GNU Lesser General Public License 
gives permission to release a modified version without this exception; 
this exception also makes it possible to release a modified version 
which carries forward this exception.
*/

import "../../objects/guild/Guild";
import "../../objects/player/Player";

import "server/zone/ZoneServer";

import "GuildMap";

interface GuildManager {
	GuildManager(ZoneServer server) {
		super(server);
	}
	
	void lock(boolean doLock = true);
	void unlock(boolean doLock = true);
	
	void load();

	boolean createGuild(Player player, string tag, string name);

	Guild getGuild(string tag, boolean doLock = true);
	Guild getGuild(unsigned int gid, boolean doLock = true);
	
	boolean removeGuild(int gid); 
	
	void removePlayersFromGuild(int gid);
	
	GuildMap getGuildMap();
	
	void handleGuildTag(unsigned int boxID, Player player, unsigned int  cancel, string returnString);
	void handleGuildName(unsigned int boxID, Player player, unsigned int cancel, string returnString);
	void handleGuildCreationName(Player player);

	void handleGuildSponsor(unsigned int boxID, Player player, unsigned int cancel, string returnString);

	void handleVerifyBoxSponsorTargetforGuildMembership(unsigned int boxID, Player otherPlayer, unsigned int cancel);
	void VerifyBoxSponsorTargetforGuildMembership(Player otherPlayer, string inviter, string guildname);
	
	void handleSponsoredGuildMembersBox(unsigned int boxID, Player player, unsigned int cancel, int index);
	void handleSponsoredGuildMembersAcceptBox(unsigned int boxID, Player player, unsigned int cancel, int index);
	
	void removeFromGuild(Player player, Player removePlayer);
	void execRemoveFromGuild(unsigned int boxID, Player player, unsigned int cancel);
	
	void handleGuildDisbandBox(unsigned int boxID, Player player, unsigned int cancel, string returnString);
	void handleGuildNameChange(unsigned int boxID, Player player, unsigned int cancel, string returnString);
	void handleGuildNameChangeName(unsigned int boxID, Player player, unsigned int cancel, string returnString);
	
	void handleGuildInformationMembers(Player player);
	void handleGuildInformationMembersBox(unsigned int boxID, Player player, unsigned int cancel, int index);
	
	void handleGuildMemberOptions(unsigned int boxID, Player player, unsigned int cancel, int index);
	
	void handleRemoveFromGuild(Player player, string kickee);
	
	void callGuildPermissions(Player player, string proband);
	void handleGuildPermissionSelection(unsigned int boxID, Player player, unsigned int cancel, int index);
	
	void declineSponsoring(string declinee,unsigned int inviteGuild, Player inviter);
	
	void handleGuildInfo(Player player);
	
	void handleGuildSponsoring(Player player);
	
	void handleGuildRenaming(Player player);
	
	void handleGuildTransferLeader(Player player);
	void handleGuildTransferLeaderBox(unsigned int boxID, Player player, unsigned int cancel, string returnString);	
	void handleGuildTransferLeaderVerifyBox(unsigned int boxID, Player player, unsigned int cancel);
}
