package server.zone.objects.events;

import server.zone.objects.scene.SceneObject;

import server.zone.objects.events.StreamEvent;

@graph(edge, label = "player_command")
class PlayerCommandEvent extends StreamEvent {
    protected SceneObject source;
    protected SceneObject target;

    @graph(type = "String")
    protected string command;

    @graph(type = "String")
    protected unicode arguments;

	public PlayerCommandEvent(SceneObject source, SceneObject target, final string command, final unicode arguments) {
	    this.source = source;
	    this.target = target;
	    this.command = command;
	    this.arguments = arguments;
	}
}


