package server.zone.objects.waypoint;

import engine.lua.LuaObject;
import engine.core.ManagedReference;
import server.zone.objects.intangible.IntangibleObject;
import engine.service.proto.BaseMessage;
import server.zone.Zone;
import server.zone.templates.SharedObjectTemplate;
include system.lang.String;

class WaypointObject extends IntangibleObject {
	protected unsigned int cellID; //?

	protected unsigned long unknown;//? cell object id maybe
	protected unsigned int planetCRC;
	
	protected string detailedDescription;

	protected byte color;
	protected byte active;

	protected int specialTypeID;
	
	public static final byte COLOR_WHITE = 0x00;
	public static final byte COLOR_BLUE = 0x01;
	public static final byte COLOR_GREEN = 0x02;
	public static final byte COLOR_ORANGE = 0x03;
	public static final byte COLOR_YELLOW = 0x04;
	public static final byte COLOR_PURPLE = 0x05;

	public static final int SPECIALTYPE_FIND = 1;
	public static final int SPECIALTYPE_FINDFRIEND = 2;
	public static final int SPECIALTYPE_FINDPLAYER = 3;
	public static final int SPECIALTYPE_FINDMYTRAINER = 4;
	public static final int SPECIALTYPE_FINDOBJECT = 5;
	public static final int SPECIALTYPE_RESOURCE = 6;
	public static final int SPECIALTYPE_THEMEPARK = 7;
	public static final int SPECIALTYPE_RACETRACK = 8;
	public static final int SPECIALTYPE_NEARESTMISSIONFORGROUP = 9;
	public static final int SPECIALTYPE_TREASUREMAP = 10;
	
	public WaypointObject() {
		Logger.setLoggingName("WaypointObject");
	}
	
	@local
	public native void loadTemplateData(SharedObjectTemplate templateData);
	
	@local
	public native void insertToMessage(BaseMessage msg);
	
	public void setCellID(unsigned int id) {
		cellID = id;
	}
	
	public void setPlanetCRC(unsigned int crc) {
		planetCRC = crc;
	}
	
	@dirty
	public unsigned int getPlanetCRC() {
		return planetCRC;
	}
		
	public void setColor(byte newColor) {
		color = newColor;
	}
	
	public void setActive(byte newStatus) {
		active = newStatus;
	}
	
	public void setUnknown(unsigned long id) {
		unknown = id;
	}

	public void setSpecialTypeID(int id) {
		specialTypeID = id;
	}

	@dirty
	public int getSpecialTypeID() {
		return specialTypeID;
	}
	
	public void toggleStatus() {
		active = !active;
	}
	
	@dirty
	public boolean isActive() {
		return active;
	}
	
	@dirty
	public byte getColor() {
		return color;
	}
	
	@dirty
	public native string getDetailedDescription();
	
	public void setDetailedDescription(final string desc) {
		detailedDescription = desc;
	}
	
}
