/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.tangible.terminal;

import server.zone.objects.tangible.TangibleObject;
import server.zone.objects.scene.SceneObject;

class Terminal extends TangibleObject {
	//@weakReference
	protected SceneObject controlledObject;
	
	public Terminal() {		
		Logger.setLoggingName("Terminal");
		
		controlledObject = null;
	}
	
	public native void initializeTransientMembers();

	@dirty
	public boolean isTerminal() {
		return true;
	}
	
	@dirty
	public abstract boolean isGuildTerminal() {
		return false;
	}
	
	public void setControlledObject(SceneObject obj) {
		controlledObject = obj;
	}
	
	@dirty
	public SceneObject getControlledObject() {
		return controlledObject;
	}
	
	@dirty
	public abstract boolean isElevatorTerminal() {
		return false;
	}

	@dirty
	public abstract boolean isVendorTerminal() {
		return false;
	}

	@dirty
	public abstract boolean isBazaarTerminal() {
		return false;
	}
	
	public void initializeChildObject(SceneObject controllerObject) {
		setControlledObject(controllerObject);
	}
}
