/*
Copyright <SWGEmu>
See file COPYING for copying conditions.
*/

package server.zone.objects.ship.components;

import server.zone.objects.ship.components.ShipComponent;
import server.zone.objects.ship.ShipObject;
include server.zone.objects.manufactureschematic.craftingvalues.CraftingValues;
include server.zone.packets.scene.AttributeListMessage;
import server.zone.objects.creature.CreatureObject;
include templates.SharedObjectTemplate;

class ShipArmorComponent extends ShipComponent {

	public ShipArmorComponent() {
		super();
	}

	@local
	public native void loadTemplateData(SharedObjectTemplate templateData);

	@local
	@dirty
	public native void fillAttributeList(AttributeListMessage msg, CreatureObject object);

	@local
	public abstract native void install(CreatureObject owner, ShipObject component, int slot, boolean notifyClient);

	@local
	public abstract native void uninstall(CreatureObject owner, ShipObject component, int slot, boolean notifyClient);
}
