/*
Copyright <SWGEmu>
See file COPYING for copying conditions.
*/

package server.zone.objects.ship.components;

import server.zone.objects.ship.components.ShipComponent;
import server.zone.objects.ship.ShipObject;
include server.zone.objects.manufactureschematic.craftingvalues.CraftingValues;
include server.zone.packets.scene.AttributeListMessage;
import server.zone.objects.creature.CreatureObject;
include templates.SharedObjectTemplate;

class ShipBoosterComponent extends ShipComponent {
	protected float boosterConsumptionRate;
	protected float boosterAcceleration;
	protected float boosterEnergy;
	protected float boosterRechargeRate;
	protected float boosterSpeed;

	public ShipBoosterComponent() {
		super();

		boosterConsumptionRate = 0.f;
		boosterAcceleration = 0.f;
		boosterEnergy = 0.f;
		boosterRechargeRate = 0.f;
		boosterSpeed = 0.f;
	}

	public float getBoosterAcceleration() {
		return boosterAcceleration;
	}

	public float getBoosterEnergyConsumptionRate() {
		return boosterConsumptionRate;
	}

	public float getBoosterEnergy() {
		return boosterEnergy;
	}

	public float getBoosterRechargeRate() {
		return boosterRechargeRate;
	}

	public float getBoosterSpeed() {
		return boosterSpeed;
	}

	@local
	public void setBoosterAcceleration(float accel) {
		boosterAcceleration = accel;
	}

	@local
	public void setBoosterEnergyConsumptionRate(float rate) {
		boosterConsumptionRate = rate;
	}

	@local
	public void setBoosterEnergy(float energy) {
		boosterEnergy = energy;
	}

	@local
	public void setBoosterRechargeRate(float rate) {
		boosterRechargeRate = rate;
	}

	@local
	public void setBoosterSpeed(float speed) {
		boosterSpeed = speed;
	}

	@local
	public native void loadTemplateData(SharedObjectTemplate templateData);

	@local
	public abstract native void updateCraftingValues(CraftingValues values, boolean firstUpdate);

	@local
	@dirty
	public native void fillAttributeList(AttributeListMessage msg, CreatureObject object);

	@local
	public abstract native void install(CreatureObject owner, ShipObject component, int slot, boolean notifyClient);

	@local
	public abstract native void uninstall(CreatureObject owner, ShipObject component, int slot, boolean notifyClient);
}
