/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions. */

package server.zone.objects.intangible;

include engine.core.ManagedObject;

import engine.util.Observer;
import engine.util.Observable;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.intangible.PetControlDevice;
include templates.params.ObserverEventType;


class PetControlObserver extends Observer {
	
	@weakReference
	PetControlDevice petControlDevice;
	
	public PetControlObserver(PetControlDevice device) {
		petControlDevice = device;
	}

	@dirty
	public int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2) {
		if (eventType != ObserverEventType.STARTCOMBAT) {
			return 0;
		}
		
		PetControlDevice strongRef = petControlDevice;
		
		if (strongRef != null) {
			CreatureObject creature = (CreatureObject) observable;
			strongRef.cancelSpawnObject(creature);
		}
		
		return 1;
	}

}
