/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.objects.intangible;

import server.zone.objects.intangible.ControlDevice;
import server.zone.objects.creature.CreatureObject;
import server.zone.packets.object.ObjectMenuResponse;
include server.zone.managers.radial.RadialOptions;
import server.zone.objects.scene.SceneObject;
import server.zone.objects.ship.ShipObject;

@json
class ShipControlDevice extends ControlDevice {
	public ShipControlDevice() {
		Logger.setLoggingName("ShipControlDevice");
	}

	@preLocked
	@arg1preLocked
	public native void storeShip(CreatureObject player, ShipObject ship);

	@preLocked
	@arg1preLocked
	public native void generateObject(CreatureObject player);

	@preLocked
	@arg1preLocked
	public native int handleObjectMenuSelect(CreatureObject player, byte selectedID);

	/**
	 * Fills the radial options, needs to be overriden
	 * @pre { this object is locked }
	 * @post { this object is locked, menuResponse is complete}
	 * @param menuResponse ObjectMenuResponse that will be sent to the client
	 */
	@local
	@dirty
	public native void fillObjectMenuResponse(ObjectMenuResponse menuResponse, CreatureObject player);

	@dirty
	public native boolean canBeTradedTo(CreatureObject player, CreatureObject receiver, int numberInTrade);

	@dirty
	public boolean isShipControlDevice() {
		return true;
	}
}
