import "../DeedObject";
import "../../../installation/harvester/HarvesterObject";
import "../../TangibleObject";
import "../../../../packets";
import "../../../player/Player";
import "../../../creature/CreatureObject";

interface HarvesterDeed implements DeedObject {
	HarvesterDeed(CreatureObject creature, int tempCRC, const UnicodeString n, const String tempn) {
		super(creature, tempCRC, n, tempn, int tp);
	}
	
	HarvesterDeed(unsigned long oid, int tempCRC, const UnicodeString n, const String tempn) {
		super(oid, tempCRC, n, tempn, int tp);
	}
	
	HarvesterDeed(CreatureObject creature, HarvesterObject hino) {
		super(unsigned long oid, int tp);
	}

	void parseItemAttributes();
	
	void setSurplusMaintenance(int maint);
	void setMaintenanceRate(float rate);
	void setSurplusPower(int pow);
	void setPowerRate(float rate);
	void setExtractionRate(float rate);
	void setHopperSize(float size);
	void setLotSize(int size);
	
	int getSurplusMaintenance();
	float getMaintenanceRate();
	int getSurplusPower();
	float getPowerRate();
	float getExtractionRate();
	float getHopperSize();
	int getLotSize();

	int getSize();
}

