/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

package server.zone.managers.auction;

import engine.core.ManagedObject;
import system.util.VectorMap;
import server.zone.objects.auction.AuctionItem;
import server.zone.objects.creature.CreatureObject;
include server.zone.managers.auction.AuctionTerminalMap;
include server.zone.managers.auction.TerminalListVector;

class AuctionsMap extends ManagedObject {
	
	@dereferenced
	protected transient AuctionTerminalMap vendorItemsForSale;
	
	@dereferenced
	protected transient AuctionTerminalMap bazaarItemsForSale;

	@dereferenced
	protected transient VectorMap<unsigned long, AuctionItem> allItems;
	
	@dereferenced
	protected transient VectorMap<unsigned long, int> bazaarCount;
	
	@dereferenced
	protected transient Logger logger;
	
	public AuctionsMap() {
		allItems.setNullValue(null);
		allItems.setNoDuplicateInsertPlan();
		
		bazaarCount.setAllowOverwriteInsertPlan();
		bazaarCount.setNullValue(0);
		
		logger.setLoggingName("AuctionsMap");
		logger.setGlobalLogging(true);
		logger.setLogging(true);
	}

	public native int addItem(CreatureObject player, SceneObject vendor, AuctionItem item);
	private native int addVendorItem(CreatureObject player, final string planet, final string region, SceneObject vendor, AuctionItem item);
	private native int addBazaarItem(CreatureObject player, final string planet, final string region, SceneObject vendor, AuctionItem item);

	public native int removeItem(SceneObject vendor, AuctionItem item);
	private native int removeVendorItem(SceneObject vendor, AuctionItem item);
	private native int removeBazaarItem(SceneObject vendor, AuctionItem item);

	
	public synchronized AuctionItem getItem(unsigned long id) {
		return allItems.get(id);
	}
	
	public synchronized boolean containsItem(unsigned long id) {
		return allItems.contains(id);
	}

	@local
	@dereferenced
	public native TerminalListVector getVendorTerminalData(final string planet, final string region, SceneObject vendor);
	
	@local
	@dereferenced
	public native TerminalListVector getBazaarTerminalData(final string planet, final string region, SceneObject vendor);
	
	private native void sendVendorUpdateMail(SceneObject vendor, boolean isEmpty);

	public native int getVendorItemCount(SceneObject vendor);
	
	public native void deleteTerminalItems(SceneObject vendor);
	
	public int getBazaarItemCount(CreatureObject player) {
		return bazaarCount.get(player.getObjectID());
	}
	
	public native void updateUID(SceneObject vendor, final string oldUID, final string newUID);

	public native void updateVendorSearch(SceneObject vendor, boolean enabled);

	public int getBazaarCount() {
		return bazaarItemsForSale.size();
	}
	
	public int getVendorCount() {
		return vendorItemsForSale.size();
	}
	
	public int getTotalItemCount() {
		return allItems.size();
	}
}
