/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.area;

include server.zone.objects.scene.SceneObject;
include server.zone.objects.area.areashapes.AreaShape;
include system.util.Vector;


import server.zone.Zone;
import server.zone.objects.pathfinding.NavArea;
import server.zone.objects.region.Region;

@mock
@json
class ActiveArea extends SceneObject {
	protected unsigned long cellObjectID;

	protected boolean pvpArea;

	protected boolean overtOnlyArea;

	protected boolean rebelOnlyArea;

	protected boolean imperialOnlyArea;

	protected boolean noCombatArea;

	protected boolean noPetArea;

	protected boolean lockedArea;

	protected AreaShape areaShape;

	@dereferenced
	protected transient Vector<SceneObject> attachedScenery;

	protected unsigned int areaFlags;

	protected string areaName;

	public static final int UNDEFINEDAREA = 0x000000;
	public static final int SPAWNAREA = 0x000001;
	public static final int NOSPAWNAREA = 0x000002;
	public static final int WORLDSPAWNAREA = 0x000004;
	public static final int NOWORLDSPAWNAREA = 0x000008;
	public static final int NOBUILDZONEAREA = 0x000010;
	public static final int CAMPINGAREA = 0x000020;
	public static final int CITY = 0x000040;
	public static final int NAVAREA = 0x000080;
	public static final int NAMEDREGION = 0x000100;

	public static final int CIRCLE = 1;
	public static final int RECTANGLE = 2;
	public static final int RING = 3;

	public ActiveArea() {
		cellObjectID = 0;

		pvpArea = false;

		overtOnlyArea = false;

		rebelOnlyArea = false;

		imperialOnlyArea = false;

		noCombatArea = false;

		noPetArea = false;

		lockedArea = false;

		areaShape = null;

		areaName = "";

		areaFlags = 0;

		Logger.setLoggingName("ActiveArea");
	}

	/**
	 * Sends the necessary messages to player in order to create this object
	 * @pre { this object is locked }
	 * @post { this object is locked, player received this object }
	 * @param player SceneObject that will receive the messages
	 * @param doClose if true a SceneObjectCloseMessage is sent to finish the object
	 */
	@dirty
	public native void sendTo(SceneObject player, boolean doClose, boolean forceLoadContainer = true) {
	}

	@mock
	@dirty
	public native abstract void enqueueEnterEvent(SceneObject obj);

	@mock
	@dirty
	public native abstract void enqueueExitEvent(SceneObject obj);

	@dirty
	public native abstract void notifyEnter(SceneObject object);

	@dirty
	public native abstract void notifyExit(SceneObject object);

	public native void sendDebugMessage(SceneObject creature, boolean entry);

	public native void setZone(Zone zone);

	@read
	public native boolean containsPoint(float x, float y, unsigned long cellid);

	@read
	public abstract native boolean containsPoint(float x, float y);

	@read
	public native boolean intersectsWith(ActiveArea area);

	@dirty
	@local
	public abstract NavArea asNavArea() {
		return null;
	}

	@dirty
	@local
	public abstract Region asRegion() {
		return null;
	}

	@preLocked
	public native void setRegionFlags(unsigned int flags) {
		areaFlags = flags;
	}

	@preLocked
	public void setAreaName(final string name) {
		areaName = name;
	}

	@dirty
	public boolean isActiveArea() {
		return true;
	}

	@dirty
	public abstract boolean isRegion() {
		return false;
	}

	@read
	public abstract boolean isNavArea() {
		return false;
	}

	@dirty
	public abstract boolean isCampArea() {
		return false;
	}

	@read
	public boolean isUndefinedRegion() {
		return areaFlags & UNDEFINEDAREA;
	}

	@read
	public boolean isCityRegion() {
		return  areaFlags & CITY;
	}

	@read
	public boolean isSpawnArea() {
		return areaFlags & SPAWNAREA;
	}

	@read
	public boolean isNoSpawnArea() {
		return areaFlags & NOSPAWNAREA;
	}

	@read
	public boolean isWorldSpawnArea() {
		return areaFlags & WORLDSPAWNAREA;
	}

	@read
	public boolean isNoWorldSpawnArea() {
		return areaFlags & NOWORLDSPAWNAREA;
	}

	@read
	public boolean isNoBuildZone() {
		return areaFlags & NOBUILDZONEAREA;
	}

	@read
	public boolean isCampingArea() {
		return areaFlags & CAMPINGAREA;
	}

	@read
	public boolean shouldBuildNavmesh() {
		return areaFlags & NAVAREA;
	}

	@read
	public boolean isNamedRegion() {
		return areaFlags & NAMEDREGION;
	}

	@read
	public boolean isPvpArea() {
		return pvpArea;
	}

	@read
	public boolean isOvertOnlyArea() {
		return overtOnlyArea;
	}

	@read
	public boolean isRebelOnlyArea() {
		return rebelOnlyArea;
	}

	@read
	public boolean isImperialOnlyArea() {
		return imperialOnlyArea;
	}

	@read
	public boolean isNoCombatArea() {
		return noCombatArea;
	}

	@read
	public boolean isNoPetArea() {
		return noPetArea;
	}

	@read
	public boolean isLockedArea() {
		return lockedArea;
	}

	@read
	public boolean isRectangularAreaShape() {
		return areaShape && areaShape.isRectangularAreaShape();
	}

	@preLocked
	public native void addAreaFlag(unsigned int flag);

	@preLocked
	public native void removeAreaFlag(unsigned int flag);

	@preLocked
	public void setRadius(float r) {
		if (areaShape && r < areaShape.getRadius()) {
			r = areaShape.getRadius();
		}

		super.setRadius(r);
	}

	@preLocked
	public void setPvpArea(boolean val) {
		pvpArea = val;
	}


	@preLocked
	public void setOvertOnlyArea(boolean val) {
		overtOnlyArea = val;
	}

	@preLocked
	public void setRebelOnlyArea(boolean val) {
		rebelOnlyArea = val;
	}


	@preLocked
	public void setImperialOnlyArea(boolean val) {
		imperialOnlyArea = val;
	}

	@preLocked
	public void setNoCombatArea(boolean val) {
		noCombatArea = val;
	}

	@preLocked
	public void setNoPetArea(boolean val) {
		noPetArea = val;
	}

	@preLocked
	public void setLockedArea(boolean val) {
		lockedArea = val;
	}

	@preLocked
	public void setCellObjectID(unsigned long celloid) {
		cellObjectID = celloid;
	}

	@preLocked
	public void setAreaShape(AreaShape area) {
		areaShape = area;

		if (areaShape) {
			setRadius(areaShape.getRadius());
		}
	}

	@read
	public int getAreaFlags() {
		return areaFlags;
	}

	@read
	public float getRadius2() {
		float radius = getRadius();

		return radius * radius;
	}

	@read
	public float getRadius() {
		if (areaShape) {
			return areaShape.getRadius();
		} else {
			return super.getRadius();
		}
	}

	@read
	public unsigned long getCellObjectID() {
		return cellObjectID;
	}

	@read
	public AreaShape getAreaShape() {
		return areaShape;
	}

	@read
	public string getAreaName() {
		return areaName;
	}

	@preLocked
	public void attachScenery(SceneObject scene) {
		attachedScenery.add(scene);
	}

	public native void initializeChildObject(SceneObject controllerObject);
}
