import "../player/Player";

import "ActiveArea";

import "../tangible/campkit/campsite/CampSite";

interface CampActiveArea implements ActiveArea {
	CampActiveArea(float x, float y, float z, float radius, CampSite camp) {
		super(x,y, z,radius);
	}

	void onEnter(Player player);
	
	void onExit(Player player);
}
