/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.area;

import server.zone.objects.scene.SceneObject;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.area.ActiveArea;


class GarageArea extends ActiveArea {
	public GarageArea() {
		Logger.setLoggingName("GarageArea");
	}

	@dirty
	public void notifyEnter(SceneObject player) {
		if (player.isPlayerCreature()) {
			CreatureObject playerCreature = (CreatureObject) player;
			
			SceneObject rootParent = playerCreature.getRootParent();
			
			if (rootParent == null || !rootParent.isVehicleObject())
				return;
			
			playerCreature.sendSystemMessage("@pet/pet_menu:garage_proximity"); //You have entered into the proximity of a vehicle garage.
		}
	}
}

