/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.objects.area;

import engine.core.ManagedObject;
import server.zone.objects.scene.SceneObject;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.area.ActiveArea;

class SarlaccArea extends ActiveArea {

	@dereferenced
	protected Time lastErupt;

	public SarlaccArea() {
		super();
	}

	public void updateEruptTime() {
		lastErupt.updateToCurrentTime();
	}
	
	@dirty
	public native void notifyEnter(SceneObject player);
}
