/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.area;

import engine.util.Observer;
import engine.util.Observable;
include server.zone.objects.area.SpawnArea;
import server.zone.objects.scene.SceneObject;

class SpawnAreaObserver extends Observer implements Logger {
	@weakReference
	protected SpawnArea spawnArea;
	
	public SpawnAreaObserver(SpawnArea area) {
		spawnArea = area;
		
		Logger.setLoggingName("SpawnAreaObserver");
	}
	
	@dirty
	public abstract int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2) {
		if (spawnArea == null)
			return 1;
		else
			return spawnArea.notifyObserverEvent(eventType, observable, arg1, arg2);
	}
}
