/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

package server.zone.objects.tangible.pharmaceutical;

import server.zone.objects.tangible.TangibleObject;
import server.zone.objects.scene.SceneObject;
import server.zone.Zone;
import engine.lua.LuaObject;
import server.zone.packets.scene.AttributeListMessage;
import server.zone.packets.object.ObjectMenuResponse;
import server.zone.objects.creature.CreatureObject;
import server.zone.ZoneServer;
import server.zone.objects.tangible.pharmaceutical.PharmaceuticalObject;
include server.zone.objects.creature.CreatureState;
include server.zone.objects.creature.CreatureAttribute;
import server.zone.objects.manufactureschematic.ManufactureSchematic;
include server.zone.objects.manufactureschematic.craftingvalues.CraftingValues;
include server.zone.templates.tangible.DotPackTemplate;

class DotPack extends PharmaceuticalObject {
	protected float effectiveness;
	protected float range;
	protected float area;
	protected float rangeMod;
	protected float potency;
	protected string commandToExecute;

	protected unsigned int duration;
	protected unsigned int pool;
	protected unsigned int dotType;
	
	public DotPack() {
		area = 0;
		range = 0;
		rangeMod = 0;
		potency = 0;
		duration = 0;
		pool = 0;
		dotType = 0;
		effectiveness = 0;
		
		setLoggingName("DotPack");
	}
	
	@local
	public void updateCraftingValues(CraftingValues values, boolean firstUpdate) {
		effectiveness = values.getCurrentValue("power");
		super.medicineUseRequired = values.getCurrentValue("skillmodmin");
		setUseCount(values.getCurrentValue("charges"));
		
		range = values.getCurrentValue("range");
		area = values.getCurrentValue("area");
		potency = values.getCurrentValue("potency");
		duration = values.getCurrentValue("duration");
	}
	
	/**
	 * Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
	 * @pre { templateData is a valid pointer }
	 * @post { TangibleObject members are initialized }
	 * @param templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
	 */
	@local
	public void loadTemplateData(SharedObjectTemplate templateData) {
		super.loadTemplateData(templateData);
		
		if (!templateData.isDotPackTemplate())
			return;
		
		DotPackTemplate stimPackTemplate = (DotPackTemplate) templateData;
		
		effectiveness = stimPackTemplate.getEffectiveness();
		super.medicineUseRequired = stimPackTemplate.getMedicineUse();
		duration = stimPackTemplate.getDuration();
		area = stimPackTemplate.getArea();
		range = stimPackTemplate.getRange();
		rangeMod = stimPackTemplate.getRangeMod();
		pool = stimPackTemplate.getPool();
		dotType = stimPackTemplate.getDotType();
		potency = stimPackTemplate.getPotency();
		commandToExecute = stimPackTemplate.getCommandToExecute();
	}
	
	/**
	 * Fills the attribute list message options that are sent to player creature
	 * @pre { }
	 * @post { }
	 * @param msg attribute list message with the attributes
	 * @param object player creature to which the message is sent
	 */
	@local
	public void fillAttributeList(AttributeListMessage msg, CreatureObject object) {
		super.fillAttributeList(msg, object);
		
		msg.insertAttribute("examine_dot_attribute", CreatureAttribute.getName(pool, true));

		msg.insertAttribute("examine_dot_apply_power", Math.getPrecision(effectiveness, 0));

		if (isPoisonDeliveryUnit()) {
			msg.insertAttribute("examine_dot_apply", "Poison");
		} else {
			msg.insertAttribute("examine_dot_apply", "Diseased");
		}
		
		msg.insertAttribute("examine_dot_potency", Math.getPrecision(potency, 0));

		msg.insertAttribute("examine_heal_range", Math.getPrecision(range, 0));

		if (isArea()) {
			msg.insertAttribute("examine_heal_area", Math.getPrecision(area, 0));

			msg.insertAttribute("duration", Math.getPrecision(duration, 0));

			msg.insertAttribute("combat_healing_ability", super.getMedicineUseRequired());
		} else {

			msg.insertAttribute("duration", Math.getPrecision(duration, 0));

			msg.insertAttribute("combat_healing_ability", super.getMedicineUseRequired());
		}
	}
	
	/**
	 * Handles the radial selection sent by the client, must be overriden by inherited objects
	 * @pre { this object is locked, player is locked }
	 * @post { this object is locked, player is locked }
	 * @param player CreatureObject that selected the option
	 * @param selectedID selected menu id
	 * @returns 0 if successfull
	 */
	public int handleObjectMenuSelect(CreatureObject player, byte selectedID) {
		if (selectedID != 20)
			return 1;

		if (player.getSkillMod("combat_healing_ability") < super.medicineUseRequired) {
			player.sendSystemMessage("@error_message:insufficient_skill"); //You lack the skill to use this item.
			
			return 0;
		} else {
			string command = commandToExecute + " ";
			command = command + String.valueOf(super.getObjectID());
			
			player.sendExecuteConsoleCommand(command);
			
			return 0;
		}

	}
	
	public int calculatePower(CreatureObject creature) {
		float modSkill = (float) creature.getSkillMod("combat_medic_effectiveness");
		return ((100 + modSkill) / 100 * effectiveness);
	}

	public boolean isPoisonDeliveryUnit() {
		return dotType == CreatureState.POISONED;
	}
	
	public boolean isDiseaseDeliveryUnit() {
		return dotType == CreatureState.DISEASED;
	}
	
	public float getEffectiveness() {
		return effectiveness;
	}
	
	public float getRange() {
		return range;
	}
	
	public float getArea() {
		return area;
	}
	
	public float getRangeMod() {
		return rangeMod;
	}
	
	public float getPotency() {
		return potency;
	}
	
	public unsigned int getDuration() {
		return duration;
	}
	
	public boolean isArea() {
		return area != 0;
	}
	
	public unsigned int getPool() {
		return pool;
	}
	
	public unsigned int getDotType() {
		return dotType;
	}
}
