import "../../scene/SceneObject";

import "../../creature/CreatureObject";

import "../../player/Player";

import "../TangibleObject";

import "Pharmaceutical";

interface StimPack implements Pharmaceutical {
	
	StimPack(unsigned long oid, unsigned int tempCRC, const UnicodeString n, const String tempn) {
		super(oid, tempCRC, n, tempn, int mptype);
	}
	
	StimPack(CreatureObject creature, unsigned int tempCRC, const UnicodeString n, const String tempn) {
		super(creature, tempCRC, n, tempn, int mptype);
	}
	
	void generateAttributes(SceneObject obj);
	
	unsigned int calculatePower(CreatureObject healer, CreatureObject patient, boolean applyBattleFatigue = true);
	
	void setEffectiveness(float eff);
	float getEffectiveness();
}
