/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.player.sui.messagebox;

import server.zone.objects.creature.CreatureObject;
import engine.service.proto.BaseMessage;
import server.zone.objects.player.sui.SuiBox;

class SuiInputBox extends SuiBox {
	protected int maxInputSize;
	protected string defaultInput;

	protected int inputType;

	public final static int DEFAULT = 0;
	public final static int FILTER = 1;

	public SuiInputBox(CreatureObject player, unsigned int windowType = 0, int inputtype = 0) {
		super(player, windowType, SuiBox.INPUTBOX);
		
		maxInputSize = 25;

		inputType = inputtype;
	}

	@local
	public native BaseMessage generateMessage();

	public void setMaxInputSize(int size) {
		maxInputSize = size;
	}

	public void setDefaultInput(final string text) {
		defaultInput = text;
	}

	public boolean isFilterBox() {
		return inputType == FILTER;
	}
	
	public boolean isInputBox() {
		return true;
	}
}
