import "../DeedObject";
import "../../TangibleObject";
import "../../../../packets";
import "../../../player/Player";
import "../../../creature/CreatureObject";

interface HarvesterDeed implements DeedObject {
	HarvesterDeed(CreatureObject creature, int tempCRC, const unicode n, const string tempn) {
		super(creature, tempCRC, n, tempn, int tp);
	}
	
	HarvesterDeed(unsigned long oid, int tempCRC, const unicode n, const string tempn) {
		super(oid, tempCRC, n, tempn, int tp);
	}
}

