/*
Copyright (C) 2007 <SWGEmu>
 
This File is part of Core3.
 
This program is free software; you can redistribute 
it and/or modify it under the terms of the GNU Lesser 
General Public License as published by the Free Software
Foundation; either version 2 of the License, 
or (at your option) any later version.
 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
See the GNU Lesser General Public License for
more details.
 
You should have received a copy of the GNU Lesser General 
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 
Linking Engine3 statically or dynamically with other modules 
is making a combined work based on Engine3. 
Thus, the terms and conditions of the GNU Lesser General Public License 
cover the whole combination.
 
In addition, as a special exception, the copyright holders of Engine3 
give you permission to combine Engine3 program with free software 
programs or libraries that are released under the GNU LGPL and with 
code included in the standard release of Core3 under the GNU LGPL 
license (or modified versions of such code, with unchanged license). 
You may copy and distribute such a system following the terms of the 
GNU LGPL for Engine3 and the licenses of the other code concerned, 
provided that you include the source code of that other code when 
and as the GNU LGPL requires distribution of source code.
 
Note that people who make modified versions of Engine3 are not obligated 
to grant this special exception for their modified versions; 
it is their choice whether to do so. The GNU Lesser General Public License 
gives permission to release a modified version without this exception; 
this exception also makes it possible to release a modified version 
which carries forward this exception.
*/

#ifndef ANIMATIONS_H_
#define ANIMATIONS_H_

#include "engine/engine.h"

const static char* anims[] = {
	"fire_single",
	"fire_burst",
	"fire_suppression",
	"ranged_coup_de_grace",
	"unarmed_coup_de_grace",
	"melee_coup_de_grace",
	"fire_acrobatic",
	"tumble_facing",
	"tumble",
	"warcry",
	"force_throw_1_arc_particle_level_1_light",
	"force_throw_1_arc_particle_level_1_medium",
	"force_throw_1_particle_level_1_light",
	"force_throw_1_particle_level_1_medium",
	"force_mind_blast_1_arc_particle_level_1_light",
	"force_mind_blast_1_arc_particle_level_1_medium",
	"force_mind_blast_1_particle_level_1_light",
	"force_mind_blast_1_particle_level_1_medium",
	"force_knockdown_1_particle_level_1",
	"force_knockdown_1_arc_particle_level_1",
	"force_intimidate",
	"force_intimidate_chain",
	"force_weaken_1_arc_particle_level_1_light",
	"force_weaken_1_arc_particle_level_1_medium",
	"force_weaken_1_particle_level_1_light",
	"force_weaken_1_particle_level_1_medium",
	"force_healing_1",
	"force_drain_1",
	"force_transfer_1",
	"mind_trick_1",
	"force_lightning_1_particle_level_1_light",
	"force_lightning_1_particle_level_1_medium",
	"force_lightning_1_particle_level_2_light",
	"force_lightning_1_particle_level_2_medium",
	"force_lightning_1_particle_level_3_light",
	"force_lightning_1_particle_level_3_medium",
	"force_lightning_1_particle_level_4_light",
	"force_lightning_1_particle_level_4_medium",
	"force_lightning_1_particle_level_5_light",
	"force_lightning_1_particle_level_5_medium",
	"force_lightning_1_arc_particle_level_1_light",
	"force_lightning_1_arc_particle_level_1_medium",
	"force_lightning_1_arc_particle_level_2_light",
	"force_lightning_1_arc_particle_level_2_medium",
	"force_lightning_1_arc_particle_level_3_light",
	"force_lightning_1_arc_particle_level_3_medium",
	"force_lightning_1_arc_particle_level_4_light",
	"force_lightning_1_arc_particle_level_4_medium",
	"force_lightning_1_arc_particle_level_5_light",
	"force_lightning_1_arc_particle_level_5_medium",
	"force_choke_1_arc_particle_level_1_light",
	"force_choke_1_arc_particle_level_1_medium",
	"force_choke_1_particle_level_1_light",
	"force_choke_1_particle_level_1_medium",
	"force_channel_2_particles_light",
	"force_channel_2_particles_medium",
	"force_channel_1_particle_light",
	"force_channel_1_particle_medium",
	"force_blast_2_particles_light",
	"force_blast_2_particles_medium",
	"force_blast_1_particle_light",
	"force_blast_1_particle_medium",
	"force_absorb_2_particles_light",
	"force_absorb_2_particles_medium",
	"force_absorb_1_particle_light",
	"force_absorb_1_particle_medium",
	"point_and_laugh",
	"intimidate",
	"rescue",
	"fire_defender_posture_change_up",
	"fire_defender_posture_change_down",
	"fire_area_light",
	"fire_area_medium",
	"fire_area_no_trails_light",
	"fire_area_no_trails_medium",
	"fire_5_single_medium",
	"fire_5_single_light",
	"fire_5_single_medium_face",
	"fire_5_single_light_face",
	"fire_7_single_medium",
	"fire_7_single_light",
	"fire_7_single_medium_face",
	"fire_7_single_light_face",
	"fire_9_single_medium",
	"fire_9_single_light",
	"fire_9_single_medium_face",
	"fire_9_single_light_face",
	"fire_5_special_single_light",
	"fire_5_special_single_medium",
	"fire_5_special_single_light_face",
	"fire_5_special_single_medium_face",
	"fire_3_single_light",
	"fire_3_single_medium",
	"fire_3_single_light_face",
	"fire_3_single_medium_face",
	"fire_3_special_single_light",
	"fire_3_special_single_medium",
	"fire_3_special_single_light_face",
	"fire_3_special_single_medium_face",
	"fire_1_single_light",
	"fire_1_single_medium",
	"fire_1_single_light_face",
	"fire_1_single_medium_face",
	"fire_1_special_single_light",
	"fire_1_special_single_medium",
	"fire_1_special_single_light_face",
	"fire_1_special_single_medium_face",
	"test_swoosh",
	"test_homing",
	"test_heavy_weapon",
	"test_heavy_weapon_particle_system",
	"test_sword_ricochet",
	"test_sword_throw",
	"test_flamethrower_arc",
	"test_lightning_1",
	"test_lightning_2",
	"test_lightning_passive_actors",
	"fire_flame_thrower_cone_1_light",
	"fire_flame_thrower_cone_1_medium",
	"fire_flame_thrower_cone_2_light",
	"fire_flame_thrower_cone_2_medium",
	"fire_flame_thrower_single_1_light",
	"fire_flame_thrower_single_1_medium",
	"fire_flame_thrower_single_2_light",
	"fire_flame_thrower_single_2_medium",
	"fire_lightning_rifle_single_1_light",
	"fire_lightning_rifle_single_1_medium",
	"fire_lightning_rifle_single_2_light",
	"fire_lightning_rifle_single_2_medium",
	"fire_acid_rifle_single_1_light",
	"fire_acid_rifle_single_1_medium",
	"fire_acid_rifle_single_2_light",
	"fire_acid_rifle_single_2_medium",
	"test_flamethrower",
	"saberthrow_posture_change",
	"saberthrow_light",
	"saberthrow_medium",
	"fire_heavy_rocket_launcher_light",
	"fire_heavy_rocket_launcher_medium",
	"fire_heavy_particle_beam_light",
	"fire_heavy_particle_beam_medium",
	"fire_heavy_lightning_beam_light",
	"fire_heavy_lightning_beam_medium",
	"fire_heavy_acid_beam_light",
	"fire_heavy_acid_beam_medium",
	"change_posture",
	"posture_scramble",
	"dodge",
	"go_incapacitated",
	"get_hit_light",
	"get_hit_medium",
	"attack_high_left_light_0",
	"attack_high_center_light_0",
	"attack_high_right_light_0",
	"attack_mid_left_light_0",
	"attack_mid_center_light_0",
	"attack_mid_right_light_0",
	"attack_low_left_light_0",
	"attack_low_center_light_0",
	"attack_low_right_light_0",
	"attack_high_left_medium_0",
	"attack_high_center_medium_0",
	"attack_high_right_medium_0",
	"attack_mid_left_medium_0",
	"attack_mid_center_medium_0",
	"attack_mid_right_medium_0",
	"attack_low_left_medium_0",
	"attack_low_center_medium_0",
	"attack_low_right_medium_0",
	"attack_high_left_light_1",
	"attack_high_center_light_1",
	"attack_high_right_light_1",
	"attack_mid_left_light_1",
	"attack_mid_center_light_1",
	"attack_mid_right_light_1",
	"attack_low_left_light_1",
	"attack_low_center_light_1",
	"attack_low_right_light_1",
	"attack_high_left_medium_1",
	"attack_high_center_medium_1",
	"attack_high_right_medium_1",
	"attack_mid_left_medium_1",
	"attack_mid_center_medium_1",
	"attack_mid_right_medium_1",
	"attack_low_left_medium_1",
	"attack_low_center_medium_1",
	"attack_low_right_medium_1",
	"attack_high_left_light_2",
	"attack_high_center_light_2",
	"attack_high_right_light_2",
	"attack_mid_left_light_2",
	"attack_mid_center_light_2",
	"attack_mid_right_light_2",
	"attack_low_left_light_2",
	"attack_low_center_light_2",
	"attack_low_right_light_2",
	"attack_high_left_medium_2",
	"attack_high_center_medium_2",
	"attack_high_right_medium_2",
	"attack_mid_left_medium_2",
	"attack_mid_center_medium_2",
	"attack_mid_right_medium_2",
	"attack_low_left_medium_2",
	"attack_low_center_medium_2",
	"attack_low_right_medium_2",
	"attack_high_left_light_3",
	"attack_high_center_light_3",
	"attack_high_right_light_3",
	"attack_mid_left_light_3",
	"attack_mid_center_light_3",
	"attack_mid_right_light_3",
	"attack_low_left_light_3",
	"attack_low_center_light_3",
	"attack_low_right_light_3",
	"attack_high_left_medium_3",
	"attack_high_center_medium_3",
	"attack_high_right_medium_3",
	"attack_mid_left_medium_3",
	"attack_mid_center_medium_3",
	"attack_mid_right_medium_3",
	"attack_low_left_medium_3",
	"attack_low_center_medium_3",
	"attack_low_right_medium_3",
	"counter_high_left_light",
	"counter_high_center_light",
	"counter_high_right_light",
	"counter_mid_left_light",
	"counter_mid_center_light",
	"counter_mid_right_light",
	"counter_low_left_light",
	"counter_low_center_light",
	"counter_low_right_light",
	"counter_high_left_medium",
	"counter_high_center_medium",
	"counter_high_right_medium",
	"counter_mid_left_medium",
	"counter_mid_center_medium",
	"counter_mid_right_medium",
	"counter_low_left_medium",
	"counter_low_center_medium",
	"counter_low_right_medium",
	"charge",
	"attack_high_right_2_punch_roundhouse_medium",
	"attack_special_foot_stomp_medium",
	"attack_special_shoulder_bash_medium",
	"attack_special_wookiee_slap_medium",
	"attack_special_headbutt_medium",
	"attack_special_knee_strike_medium",
	"attack_special_elbow_throw_medium",
	"attack_special_hammerfist_medium",
	"attack_high_right_0_rear_handhook_medium",	
	"attack_high_right_1_lead_arckick_medium",
	"attack_high_right_2_rear_roundhouse_kick_medium",	
	"attack_high_center_1_jab_double_medium",
	"combo_2a_medium",
	"combo_2b_medium",
	"combo_2c_medium",
	"combo_2d_medium",
	"combo_2e_medium",
	"attack_high_righ_2_punch_roundhouse_light",	
	"attack_special_foot_stomp_light",
	"attack_special_shoulder_bash_light",	
	"attack_special_wookiee_slap_light",
	"attack_special_headbutt_light",
	"attack_special_knee_strike_light",	
	"attack_special_elbow_throw_light",
	"attack_special_hammerfist_light",
	"attack_high_right_0_rear_handhook_light",	
	"attack_high_right_1_lead_arckick_light",
	"attack_high_right_2_rear_roundhouse_kick_light",
	"attack_high_center_1_jab_double_light",
   	"combo_2a_light",
  	"combo_2b_light",
   	"combo_2c_light",
   	"combo_2d_light",
   	"combo_2e_light",
   	"combo_3a_light",	
   	"combo_3a_medium",	
   	"combo_3b_light",	
  	"combo_3b_medium",	
   	"combo_3c_light",	
   	"combo_3c_medium",	
   	"combo_3d_light",	
   	"combo_3d_medium",	
   	"combo_3e_light",	
   	"combo_3e_medium",	
   	"combo_4a_light",	
   	"combo_4a_medium",	
   	"combo_4b_light",	
   	"combo_4b_medium",	
   	"combo_4c_light",	
   	"combo_4c_medium",	
   	"combo_4d_light",	
   	"combo_4d_medium",	
   	"combo_4e_light",	
   	"combo_4e_medium",	
   	"combo_5a_light",	
   	"combo_5a_medium",	
   	"combo_5b_light",	
   	"combo_5b_medium",	
   	"showoff_1_light",	
   	"showoff_1_medium",	
   	"showoff_2_light",	
   	"showoff_2_medium",	
   	"showoff_3_light",	
   	"showoff_3_medium",	
   	"showoff_4_light",	
   	"showoff_4_medium",	
	"combo_jedi_1_light",	
	"combo_jedi_1_medium",	
	"combo_jedi_2_light",	
	"combo_jedi_2_medium",	
	"combo_jedi_3_light",	
	"combo_jedi_3_medium",	
	"combo_jedi_4_light",	
	"combo_jedi_4_medium",	
   	"lower_posture_polearm_1",	
   	"lower_posture_unarmed_1",	
   	"lower_posture_2hmelee_1",	
   	"lower_posture_2hmelee_2",	
   	"lower_posture_2hmelee_3",	
   	"lower_posture_2hmelee_4",	
   	"lower_posture_2hmelee_5",	
   	"lower_posture_2hmelee_6",	
   	"lower_posture_1hmelee_1",	
   	"lower_posture_polearm_2",	
   	"knockdown_polearm_1",	
   	"knockdown_polearm_2",	
   	"knockdown_polearm_3",	
   	"knockdown_1hmelee_1",	
   	"knockdown_2hmelee_1",	
   	"knockdown_unarmed_1",	
   	"knockdown_unarmed_2",	
   	"knockdown_unarmed_3",	
   	"ranged_melee_light",	
   	"ranged_melee_medium"
   	"throw_grenade",
   	"throw_grenade_near_cryoban",	
   	"throw_grenade_medium_cryoban",	
   	"throw_grenade_far_cryoban",
   	"throw_grenade_near_bug_bomb",	
   	"throw_grenade_medium_bug_bomb",	
   	"throw_grenade_far_bug_bomb",	
   	"throw_grenade_near_healing",	
   	"throw_grenade_medium_healing",	
   	"throw_grenade_far_healing",	
   	"throw_grenade_near_healing_longrange",	
   	"throw_grenade_medium_healing_longrange",	
   	"throw_grenade_far_healing_longrange",
   	"throw_grenade_near_poison",	
   	"throw_grenade_medium_poison",	
   	"throw_grenade_far_poison",	
   	"throw_grenade_near_area_poison",	
   	"throw_grenade_medium_area_poison",	
   	"throw_grenade_far_area_poison",	
   	"throw_grenade_near_disease",	
   	"throw_grenade_medium_disease",
   	"throw_grenade_far_disease",	
   	"throw_grenade_near_area_disease",	
   	"throw_grenade_medium_area_disease",	
   	"throw_grenade_far_area_disease",
   	"throw_grenade_near_fragmentation",	
   	"throw_grenade_medium_fragmentation",	
   	"throw_grenade_far_fragmentation",	
   	"throw_grenade_near_glop",	
   	"throw_grenade_medium_glop",	
   	"throw_grenade_far_glop",	
   	"throw_grenade_near_imperial_detonator",	
   	"throw_grenade_medium_imperial_detonator",	
   	"throw_grenade_far_imperial_detonator",	
   	"throw_grenade_near_proton",	
   	"throw_grenade_medium_proton",
   	"throw_grenade_far_proton",	
   	"throw_grenade_near_thermal_detonator",	
   	"throw_grenade_medium_thermal_detonator",	
   	"throw_grenade_far_thermal_detonator",
   	"get_hit_grenade_near_light",
   	"get_hit_grenade_medium_light",	
	"get_hit_grenade_far_light",	
	"get_hit_grenade_near_medium",	
	"get_hit_grenade_medium_medium",	
	"get_hit_grenade_far_medium",
	"throw_trap_enraging_spur",
	"throw_trap_flash_bomb",	
	"throw_trap_noise_maker",	
	"throw_trap_sonic_pulse",	
	"throw_trap_tranq_dart",	
	"throw_trap_drowsy_dart",	
	"throw_trap_webber",	
	"throw_trap_melee_def_1",	
	"throw_trap_melee_ranged_def_1",	
	"throw_trap_ranged_def_1",	
	"throw_trap_state_def_1",	
	"creature_attack_light",	
   	"creature_attack_special_1_medium",	
   	"creature_attack_special_1_light",	
   	"creature_attack_special_2_medium",	
   	"creature_attack_special_2_light",
   	"creature_attack_medium",	
   	"creature_attack_ranged_light",	
   	"creature_attack_ranged_medium",
   	"droid_attack_light",
   	"droid_attack_medium",
	"fire_turret_light",	
	"fire_turret_medium",
	"fire_turret"
};
	
class Animations {
public:
	inline const static char* getRandomAnimation() {
		return anims[System::random(279)];
	}
	
};

#endif /*ANIMATIONS_H_*/
