/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

include "engine/util/Coordinate";

import "server/zone/Zone";
include "server/zone/ZoneProcessServerImplementation";

import "../../objects/creature/Creature";
import "../../objects/creature/CreatureObject";
import "../../objects/creature/CreatureGroup";
import "../../objects/tangible/lair/LairObject";

import "../../objects/creature/trainer/TrainerCreature";
import "../../objects/creature/recruiter/RecruiterCreature";
import "../../objects/creature/shuttle/ShuttleCreature";

interface CreatureManager {
	CreatureManager(Zone zone, ZoneProcessServerImplementation processor) {
		super(zone, processor);
	}

	void init();

	void loadCreatures();

	void start();

	void stop();

	// creature loading methods
	void loadTrainers();
	void loadRecruiters();
	void loadBlueFrogs();

	void load(Creature creature);
	void unloadCreature(Creature creature);

	// creation methods

	//Creature spawnCreature(String objname, unsigned long cellid, float x, float y, int bitmask = 0, boolean baby = false, boolean doLock = true, float height = 1);
	boolean verifyCreatureSpawn(String name);

	Creature spawnCreature(unsigned int objcrc, unsigned long cellid, float x, float y, int bitmask = 0, boolean baby = false, boolean doLock = true, float height = 1);

	TrainerCreature spawnTrainer(const String profession, const String stfname, const String name, int objCrc, unsigned long cell, float x, float y, float z, float oy, float ow, boolean doLock = true);
	ShuttleCreature spawnShuttle(const String Planet, const String City, Coordinate playerSpawnPoint, unsigned long cellid, float x, float y, float z, int tax = 0, boolean starport = false, boolean doLock = true);
	RecruiterCreature spawnRecruiter(float x, float y, float oY, float oW, unsigned char type = 1, unsigned long cellid = 0, boolean doLock = true);

	LairObject spawnLair(const String type, float x, float y, float z, boolean doLock = true);

	unsigned int getCreatureCrc(String name);
	boolean hotLoadCreature(String name);

	void registerFunctions();
	void registerGlobals();

	void loadCreatureFile();

	//void queueActivity(Creature creature, unsigned int time = 1000);

	// setters and getters
	Creature getCreature(unsigned long oid);
	void addCreature(Creature creature);

	void setGlobalNPCRegen(float value);
	float getGlobalNPCRegen();
}
