/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.managers.creature;

import server.zone.objects.creature.ai.AiAgent;
import engine.core.ManagedObject;
import engine.util.Observable;
import server.zone.managers.creature.SpawnObserver;
import server.zone.objects.tangible.LairObject;
import system.lang.Time;

include server.zone.objects.tangible.TangibleObject;
include system.thread.atomic.AtomicInteger;

class LairObserver extends SpawnObserver {
	public static final int BABY_SPAWN_CHANCE = 500;

	public static final int WILD_LAIR_PASSIVE_MAX = 10;

	public static final int SPAWN_TIME_MIN = 1; // In seconds
	public static final int SPAWN_TIME_MAX = 10; // In seconds

	public static final int RESPAWN_TIME_MIN = 120; // In seconds
	public static final int RESPAWN_TIME_MAX = 240; // In seconds

	public static final int PASSIVE_SPAWN_TIME_MIN = 15; // In seconds
	public static final int PASSIVE_SPAWN_TIME_MAX = 20; // In seconds

	public static final int HEAL_CHECK_INTERVAL = 15; // In seconds
	public static final int AGGRO_CHECK_INTERVAL = 30; // In seconds
	public static final int AGGRO_TASK_DELAY = 4; // In seconds

	public static final int SCOUT_SPAWN_CHANCE = 10; // Chance out of 100 to spawn scout

	@dereferenced
	protected AtomicInteger spawnNumber;

	@dereferenced
	protected AtomicInteger bossesSpawned;

	@dereferenced
	protected transient Time lastHealTime;

	@dereferenced
	protected transient Time lastAggroTime;

	@weakReference
	protected unsigned long scoutCreatureId;

	public LairObserver() {
		super();

		Logger.setLoggingName("LairObserver");
		spawnNumber.set(0);
		bossesSpawned.set(0);

		scoutCreatureId = 0;
	}

	// Observer Events
	public native int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);
	public native void notifyDestruction(TangibleObject lair, TangibleObject attacker, int condition);

	// Healing
	public abstract native void checkForHeal(TangibleObject lair, boolean forceNewUpdate = false);

	// Spawning
	@arg1preLocked
	public abstract native boolean checkForNewSpawns(TangibleObject lair, TangibleObject attacker, boolean forceSpawn = false);

	@arg1preLocked
	public native void checkForBossSpawn(TangibleObject lair, TangibleObject attacker);

	@arg1preLocked
	public native void checkRespawn(LairObject lair, TangibleObject attacker);

	@arg1preLocked
	public abstract native void spawnLairMobile(LairObject lair, int spawnNumber, final string templateToSpawn, boolean spawnPassive = true);

	// Aggro
	public native void doAggro(TangibleObject lair, TangibleObject attacker, boolean allAttack = false);

	// Lair Milking
	public native void repopulateLair(TangibleObject lair);

	public boolean isLairObserver() {
		return true;
	}

	public native int getLivingCreatureCount();

	public int getMobType() {
		return super.lairTemplate.getMobType();
	}

	public int getSpawnNumber() {
		return spawnNumber.get();
	}
}
