/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.installation.shuttle;

import server.zone.objects.installation.InstallationObject;
import engine.lua.LuaObject;
import system.util.SortedVector;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.creature.CreatureObject;
import server.zone.packets.object.ObjectMenuResponse;
import server.zone.packets.scene.AttributeListMessage;
import server.zone.packets.object.ObjectMenuResponse;
import engine.service.proto.BasePacket;
import system.lang.ref.Reference;
import server.zone.Zone;
import server.zone.templates.SharedObjectTemplate;
import system.util.VectorMap;
import server.zone.objects.tangible.terminal.ticketcollector.TicketCollector;
import server.zone.objects.tangible.terminal.travel.TravelTerminal;

class ShuttleInstallation extends InstallationObject {
	
	public ShuttleInstallation() {
		setLoggingName("ShuttleInstallation");
	}
	
	public native boolean checkRequisitesForPlacement(CreatureObject player);
	
		
	public boolean isShuttleInstallation(){
		return true;
	}
}
