/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.managers.gcw;
import engine.core.ManagedObject;
import engine.util.Observer;
import engine.util.Observable;
include engine.log.Logger;

class GCWBaseShutdownObserver extends Observer implements Logger {

	public GCWBaseShutdownObserver() {
		Logger.setLoggingName("GCWBaseShutdownObserver");
	}

	public native int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);
}
