/*
 *	server/zone/objects/tangible/gambling/LugjackMachine.cpp generated by engine3 IDL compiler 0.55
 */

#include "LugjackMachine.h"

#include "LugjackMachineImplementation.h"

#include "../../player/Player.h"

#include "../TangibleObject.h"

/*
 *	LugjackMachineStub
 */

LugjackMachine::LugjackMachine(unsigned long long objid, float x, float z, float y) : TangibleObject(DummyConstructorParameter::instance()) {
	_impl = new LugjackMachineImplementation(objid, x, z, y);
	_impl->_setStub(this);
}

LugjackMachine::LugjackMachine(DummyConstructorParameter* param) : TangibleObject(param) {
}

LugjackMachine::~LugjackMachine() {
}

int LugjackMachine::useObject(Player* player) {
	if (_impl == NULL) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, 6);
		method.addObjectParameter(player);

		return method.executeWithSignedIntReturn();
	} else
		return ((LugjackMachineImplementation*) _impl)->useObject(player);
}

/*
 *	LugjackMachineAdapter
 */

LugjackMachineAdapter::LugjackMachineAdapter(LugjackMachineImplementation* obj) : TangibleObjectAdapter(obj) {
}

Packet* LugjackMachineAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	Packet* resp = new MethodReturnMessage(0);

	switch (methid) {
	case 6:
		resp->insertSignedInt(useObject((Player*) inv->getObjectParameter()));
		break;
	default:
		return NULL;
	}

	return resp;
}

int LugjackMachineAdapter::useObject(Player* player) {
	return ((LugjackMachineImplementation*) impl)->useObject(player);
}

/*
 *	LugjackMachineHelper
 */

LugjackMachineHelper* LugjackMachineHelper::staticInitializer = LugjackMachineHelper::instance();

LugjackMachineHelper::LugjackMachineHelper() {
	className = "LugjackMachine";

	DistributedObjectBroker::instance()->registerClass(className, this);
}

void LugjackMachineHelper::finalizeHelper() {
	LugjackMachineHelper::finalize();
}

DistributedObject* LugjackMachineHelper::instantiateObject() {
	return new LugjackMachine(DummyConstructorParameter::instance());
}

DistributedObjectAdapter* LugjackMachineHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new LugjackMachineAdapter((LugjackMachineImplementation*) obj->_getImplementation());

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	LugjackMachineServant
 */

LugjackMachineServant::LugjackMachineServant(unsigned long long objid, unsigned int tempCRC, const UnicodeString& n, const String& tname, int tp) : TangibleObjectImplementation(objid, tempCRC, n, tname, tp) {
	_classHelper = LugjackMachineHelper::instance();
}

LugjackMachineServant::~LugjackMachineServant() {
}

void LugjackMachineServant::_setStub(DistributedObjectStub* stub) {
	_this = (LugjackMachine*) stub;
	TangibleObjectServant::_setStub(stub);
}

DistributedObjectStub* LugjackMachineServant::_getStub() {
	return _this;
}

