/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.chat;

import engine.core.ManagedObject;
import system.lang.System;
import system.util.Vector;
include server.chat.ChatParameter;
include server.chat.StringIdChatParameterVector;
include server.chat.WaypointChatParameter;
include server.chat.WaypointChatParameterVector;
include server.chat.StringIdChatParameter;
import server.zone.objects.creature.CreatureObject;

class ChatMessage extends ManagedObject {
	protected string message;
	
	public ChatMessage() {
		message = "";
	}
	
	public void setString(final string msg) {
		message = msg;
	}
	
	public string toString() {
		return message;
	}
}