/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.chat;

import engine.core.ManagedObject;

class ChatMessage extends ManagedObject {
	protected string message;
	
	public ChatMessage() {
		message = "";
	}
	
	public void setString(final string msg) {
		message = msg;
	}
	
	public string toString() {
		return message;
	}
}
