/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

include "engine/service/Message";
include "../zone/packets/object/StfParameter";

import "room/ChatRoom";

import "../zone/objects/player/Player";

import "../zone/objects/creature/CreatureObject";

import "server/zone/ZoneServer";

interface ChatManager {
	ChatManager(ZoneServer server, int initPlayers) {
		super(server, initPlayers);
	}

	void lock(boolean doLock = true);
	void unlock(boolean doLock = true);

	void addPlayer(Player player);
	Player getPlayer(string name);
	Player removePlayer(string name);

	void sendMail(const string sendername, unicode header, unicode body, const string name);
	void sendMailBody(Player receiver, unsigned int mailid);
	void listMail(Player ply);
	void deleteMail(unsigned int mailid);

	void handleTellMessage(Player player, Message pack);

	void handleMessage(Player player, Message pack);
	void handleEmote(Player player, Message pack);
	void handleMood(Player player, Message pack);

	void sendSystemMessage(Player player, unicode message);
	void sendSystemMessage(Player player, const string file, const string str, StfParameter param);

	void broadcastMessage(CreatureObject player, unicode message, unsigned long target = 0, unsigned int moodid = 0, unsigned int mood2 = 0);
	void broadcastMessage(CreatureObject player, const string file, const string str, StfParameter param, unsigned long target = 0, unsigned int moodid = 0, unsigned int mood2 = 0);
	void broadcastMessage(const string message);
	void broadcastMessageRange(Player player, const string message, float range);

	void handleGameCommand(Player player, const string command);

	// ChatRooms
	void initiateRooms();

	void handleChatRoomMessage(Player player, Message pack);
	void handleGroupChat(Player player, Message pack);
	void handleGuildChat(Player player, Message pack);
	void handleCreateRoom(Player player, Message pack);
	void handleChatEnterRoomById(Player player, Message pack);
	void handleChatDestroyRoom(Player player, Message pack);
	void handleChatRemoveAvatarFromRoom(Player player, Message pack);

	ChatRoom getChatRoom(unsigned int id);

	void addRoom(ChatRoom channel);
	void removeRoom(ChatRoom channel);

	void sendRoomList(Player player);
	ChatRoom createGroupRoom(unsigned int groupID, Player creator);

	void sendGuildChat(Player player);

	ChatRoom createRoomByFullPath(const string path);

	void destroyRoom(ChatRoom room);

	void printRoomTree(ChatRoom channel);

	ChatRoom getChatRoomByFullPath(const string path);
	ChatRoom getGameRoom(const string game);
	ChatRoom getChatRoomByGamePath(ChatRoom game, const string path);

	unsigned int getNextRoomID();

	int getPlayerCount();

	boolean isMute();

	void setMute(boolean isMuted);
}
