/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.building.recreation;

import server.zone.objects.building.BuildingObject;
import engine.lua.LuaObject;
import server.zone.Zone;
import server.zone.objects.cell.CellObject;
include server.zone.templates.tangible.RecreationBuildingObjectTemplate;
include server.zone.managers.skill.SkillModManager;


class RecreationBuildingObject extends BuildingObject {

	public RecreationBuildingObject() {		
		Logger.setLoggingName("RecreationBuildingObject");
	}
	
	@read	
	public boolean isRecreationalBuildingObject() {
		return true;
	}
}