/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

package server.zone.objects.region;

import system.util.VectorMap;
import engine.core.ManagedObject;
import server.zone.objects.tangible.terminal.bazaar.BazaarTerminal;
import server.zone.objects.area.ActiveArea;
import server.zone.objects.player.PlayerCreature;
import server.zone.objects.creature.shuttle.ShuttleCreature;
import server.zone.objects.building.city.CityHallObject;
import server.zone.objects.creature.CreatureObject;
include server.zone.objects.scene.variables.StringId;
include server.zone.objects.region.RegionCenterPoint;
include server.zone.objects.region.RegionCenterPointList;
import server.zone.objects.installation.shuttle.ShuttleInstallation;
import server.zone.Zone;

class Region extends ActiveArea {	
	@dereferenced
	protected VectorMap<unsigned long, BazaarTerminal> bazaars;
	
//	@weakReference
	protected ShuttleInstallation shuttleInstallation;
	
//	@weakReference
	protected CityHallObject cityHall;
	
	public Region() {
		super();
		
		bazaars.setNoDuplicateInsertPlan();
		bazaars.setNullValue(null);
	}
	
	public void notifyEnter(SceneObject object) {
		if (object.isBazaarTerminal()) {
			bazaars.put(object.getObjectID(), (BazaarTerminal)object);
		}
		
		if (object.isPlayerCreature()) {
			sendGreetingMessage((PlayerCreature) object);
		}
		
		if (object.isShuttleInstallation()) {
			shuttleInstallation = (ShuttleInstallation) object;
		}
	}
	
	public native void sendGreetingMessage(PlayerCreature player);
	public native void sendDepartingMessage(PlayerCreature player);
	
	public void notifyExit(SceneObject object) {
		if (object.isBazaarTerminal()) {
			bazaars.drop(object.getObjectID());
		}
		
		if (object.isPlayerCreature()) {
			sendDepartingMessage((PlayerCreature) object);
		}
		
		if (object == shuttleInstallation) {
			shuttleInstallation = null;
		}
	}
	
	/**
	 * Inserts this object into zone
	 * @pre { this object is locked }
	 * @post { this object is locked and inserted into zone }
	 * @param zone Zone object where this object will be inserted
	 */
	public native void insertToZone(Zone zone);
	
	public void removeFromZone() {
		despawnCityObjects();
			
		super.removeFromZone();
		
		updateToDatabaseWithoutChildren();
	}
	
	public native void despawnCityObjects();

	public void addBazaar(BazaarTerminal ter) {
		bazaars.put(ter.getObjectID(), ter);
	}

	public BazaarTerminal getBazaar(int idx) {
		return bazaars.get(idx);
	}
	
	public ShuttleInstallation getShuttle() {
		return shuttleInstallation;
	}

	public int getBazaarCount() {
		return bazaars.size();
	}
	
	public boolean isRegion() {
		return true;
	}
	
	public CityHallObject getCityHall() {
		return cityHall;
	}
	
	public void setCityHall(CityHallObject hall) {
		cityHall = hall;
	}
}

