/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.objects.ship;

import server.zone.objects.ship.ShipObject;

class FighterShipObject extends ShipObject {
	public FighterShipObject() {
		Logger.setLoggingName("FighterShipObject");
	}
}
