/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.objects.ship;

import engine.log.Logger;
import server.zone.objects.scene.SceneObject;

include server.zone.objects.ship.FighterShipObject;
include templates.SharedObjectTemplate;
include engine.util.u3d.Vector3;
include server.zone.objects.ship.PlayerLaunchPoints;
include server.zone.objects.ship.DamageSparkLocations;

class PobShipObject extends FighterShipObject {

	@dereferenced
	protected DamageSparkLocations sparkLocations;

	@dereferenced
	protected PlayerLaunchPoints launchPoints;

	public PobShipObject() {
		Logger.setLoggingName("PobShipObject");
	}

	@local
	public native void loadTemplateData(SharedObjectTemplate templateData);

	@dirty
	@nativeStub
	@local
	public native PobShipObject asPobShipObject();

	@dirty
	@local
	@nativeStub
	public native boolean isPobShipObject();

	@local
	@dereferenced
	@dirty
	public native string getRandomLaunchCell();

	@local
	@dereferenced
	@dirty
	public native Vector3 getLaunchPointInCell(final string cellName);
}
