/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.objects.ship;

import system.lang.Time;
import server.zone.objects.tangible.TangibleObject;
import server.zone.objects.ship.components.ShipComponent;
import server.zone.objects.ship.events.ShipRecoveryEvent;
import server.zone.Zone;
import engine.service.proto.BaseMessage;
import server.zone.objects.ship.ai.ShipAiAgent;
import system.util.SortedVector;
import system.lang.String;

include server.zone.TreeEntry;
include server.zone.objects.scene.SceneObject;
include server.zone.objects.creature.CreatureObject;
include server.zone.CloseObjectsVector;
include engine.log.Logger;
include system.lang.UnicodeString;
include server.zone.packets.DeltaMessage;
include server.zone.objects.scene.variables.DeltaAutoVariable;
include server.zone.objects.scene.variables.DeltaAutoMap;
include server.zone.objects.scene.variables.DeltaAutoPackedMap;
include server.zone.objects.scene.variables.DeltaVectorMap;
include server.zone.objects.scene.variables.DeltaBitArray;
include server.zone.objects.manufactureschematic.craftingvalues.CraftingValues;
include templates.SharedObjectTemplate;
include templates.tangible.ship.SharedShipObjectTemplate;
include system.util.VectorMap;
include system.lang.ref.Reference;
include server.zone.objects.ship.ShipDeltaVector;
include server.zone.objects.ship.ShipTargetVector;
include engine.util.u3d.Quaternion;
include engine.util.u3d.Matrix4;
include server.zone.objects.player.variables.SpaceLaunchPoint;
include system.util.Vector;
include engine.util.u3d.Vector3;


class ShipObject extends TangibleObject {
	public static final int HYPERSPACE_DELAY = 40;
	public static final int NAVIGATOR_DELAY = 20;

	public static final int COMM_MAX_DISTANCE = 500;
	public static final int SPACESTATION_COMM_MAX_DISTANCE = 1000;
	public static final int CONVO_DELAY = 60;

	public static final int WEAPON_COMPONENT_START = 12;

	protected transient boolean hyperspacing;

	public unsigned long controlDeviceID;

	@dereferenced
	protected transient Reference<ShipRecoveryEvent> shipRecoveryEvent;

	@dereferenced
	protected transient Reference<ShipDeltaVector> shipDeltaVector;

	@dereferenced
	protected transient Reference<ShipTargetVector> shipTargetVector;

	protected int totalCellNumber;

	@weakReference
	protected CreatureObject owner;

	unsigned long ownerID;

	@dereferenced
	protected SpaceLaunchPoint launchPoint;

	@weakReference
	protected SceneObject pilotChair;

	@weakReference
	protected SceneObject operationsChair;

	@weakReference
	protected SceneObject turretLadder;

	@dereferenced
	protected VectorMap<unsigned int, ShipComponent> components;

	@dereferenced
	protected Time boostTimer;

	@dereferenced
	protected Time hyperspaceTime;

	@dereferenced
	protected transient Time lastDamageReceived;

	protected boolean hasWings;

	@dereferenced
	protected string chassisDataName;

	@dereferenced
	protected string shipName;

	@dereferenced
	protected string chassisCategory;

	protected int chassisLevel;

	protected float boundingRadius;

	protected float currentSpeed;

	protected float speedRotationFactorMax;

	protected float speedRotationFactorMin;

	protected float speedRotationFactorOptimal;

	@dereferenced
	protected Matrix4 rotationMatrix;

	@dereferenced
	protected Matrix4 conjugateMatrix;

	protected transient float staffModifiedSpeed;

	protected unsigned int shipFaction;

	// DeltaAutoVariable template <class K, class V, int BaselineName, uint8 DeltaType, int DeltaIndex>

	@rawTemplate(value = "float, 'SHIP', 1, 17")
	@dereferenced
	protected DeltaAutoVariable chassisMaxMass;

	@rawTemplate(value = "float, 'SHIP', 1, 18")
	@dereferenced
	protected DeltaAutoVariable shieldRechargeRate;

	@rawTemplate(value = "float, 'SHIP', 1, 19")
	@dereferenced
	protected DeltaAutoVariable capacitorMaxEnergy;

	@rawTemplate(value = "float, 'SHIP', 1, 20")
	@dereferenced
	protected DeltaAutoVariable capacitorRechargeRate;

	@rawTemplate(value = "float, 'SHIP', 1, 21")
	@dereferenced
	protected DeltaAutoVariable engineAccelerationRate;

	@rawTemplate(value = "float, 'SHIP', 1, 22")
	@dereferenced
	protected DeltaAutoVariable engineDecelerationRate;

	@rawTemplate(value = "float, 'SHIP', 1, 23")
	@dereferenced
	protected DeltaAutoVariable enginePitchAccelerationRate;

	@rawTemplate(value = "float, 'SHIP', 1, 24")
	@dereferenced
	protected DeltaAutoVariable engineYawAccelerationRate;

	@rawTemplate(value = "float, 'SHIP', 1, 25")
	@dereferenced
	protected DeltaAutoVariable engineRollAccelerationRate;

	@rawTemplate(value = "float, 'SHIP', 1, 26")
	@dereferenced
	protected DeltaAutoVariable enginePitchRate;

	@rawTemplate(value = "float, 'SHIP', 1, 27")
	@dereferenced
	protected DeltaAutoVariable engineYawRate;

	@rawTemplate(value = "float, 'SHIP', 1, 28")
	@dereferenced
	protected DeltaAutoVariable engineRollRate;

	@rawTemplate(value = "float, 'SHIP', 1, 29")
	@dereferenced
	protected DeltaAutoVariable engineMaxSpeed;

	@rawTemplate(value = "float, 'SHIP', 1, 30")
	@dereferenced
	protected DeltaAutoVariable reactorGenerationRate;

	@rawTemplate(value = "float, 'SHIP', 1, 31")
	@dereferenced
	protected DeltaAutoVariable boosterMaxEnergy;

	@rawTemplate(value = "float, 'SHIP', 1, 32")
	@dereferenced
	protected DeltaAutoVariable boosterRechargeRate;

	@rawTemplate(value = "float, 'SHIP', 1, 33")
	@dereferenced
	protected DeltaAutoVariable boosterConsumptionRate;

	@rawTemplate(value = "float, 'SHIP', 1, 34")
	@dereferenced
	protected DeltaAutoVariable boosterAcceleration;

	@rawTemplate(value = "float, 'SHIP', 1, 35")
	@dereferenced
	protected DeltaAutoVariable boosterMaxSpeed;

	@rawTemplate(value = "float, 'SHIP', 1, 36")
	@dereferenced
	protected DeltaAutoVariable droidCommandSpeed;

	@rawTemplate(value = "uint64, 'SHIP', 1, 37")
	@dereferenced
	protected DeltaAutoVariable shipDroidID;

	@rawTemplate(value = "float, 'SHIP', 3, 11")
	@dereferenced
	protected DeltaAutoVariable slip;

	@rawTemplate(value = "float, 'SHIP', 3, 12")
	@dereferenced
	protected DeltaAutoVariable chassisCurrentHealth;

	@rawTemplate(value = "float, 'SHIP', 3, 13")
	@dereferenced
	protected DeltaAutoVariable chassisMaxHealth;

	@rawTemplate(value = "uint32, 'SHIP', 3, 14")
	@dereferenced
	protected DeltaAutoVariable shipNameCRC;

	@rawTemplate(value = "float, 'SHIP', 3, 20")
	@dereferenced
	protected DeltaAutoVariable frontShieldMax;

	@rawTemplate(value = "float, 'SHIP', 3, 21")
	@dereferenced
	protected DeltaAutoVariable rearShieldMax;

	@rawTemplate(value = "float, 'SHIP', 4, 0")
	@dereferenced
	protected DeltaAutoVariable chassisMass;

	@rawTemplate(value = "float, 'SHIP', 4, 1")
	@dereferenced
	protected DeltaAutoVariable chassisSpeed;

	@rawTemplate(value = "float, 'SHIP', 4, 2")
	@dereferenced
	protected DeltaAutoVariable capacitorEnergy;

	@rawTemplate(value = "float, 'SHIP', 4, 3")
	@dereferenced
	protected DeltaAutoVariable boosterEnergy;

	@rawTemplate(value = "uint16, 'SHIP', 6, 2")
	@dereferenced
	protected DeltaAutoVariable uniqueID;

	@rawTemplate(value = "float, 'SHIP', 6, 3")
	@dereferenced
	protected DeltaAutoVariable actualAccelerationRate;

	@rawTemplate(value = "float, 'SHIP', 6, 4")
	@dereferenced
	protected DeltaAutoVariable actualDecelerationRate;

	@rawTemplate(value = "float, 'SHIP', 6, 5")
	@dereferenced
	protected DeltaAutoVariable actualPitchAccelerationRate;

	@rawTemplate(value = "float, 'SHIP', 6, 6")
	@dereferenced
	protected DeltaAutoVariable actualYawAccelerationRate;

	@rawTemplate(value = "float, 'SHIP', 6, 7")
	@dereferenced
	protected DeltaAutoVariable actualRollAccelerationRate;

	@rawTemplate(value = "float, 'SHIP', 6, 8")
	@dereferenced
	protected DeltaAutoVariable actualPitchRate;

	@rawTemplate(value = "float, 'SHIP', 6, 9")
	@dereferenced
	protected DeltaAutoVariable actualYawRate;

	@rawTemplate(value = "float, 'SHIP', 6, 10")
	@dereferenced
	protected DeltaAutoVariable actualRollRate;

	@rawTemplate(value = "float, 'SHIP', 6, 11")
	@dereferenced
	protected DeltaAutoVariable actualMaxSpeed;

	@rawTemplate(value = "uint64, 'SHIP', 6, 12")
	@dereferenced
	protected DeltaAutoVariable shipTargetID;

	@rawTemplate(value = "uint32, 'SHIP', 6, 13")
	@dereferenced
	protected DeltaAutoVariable shipTargetSlot;

	@rawTemplate(value = "String, 'SHIP', 6, 17")
	@dereferenced
	protected DeltaAutoVariable shipType;

	@rawTemplate(value = "String, 'SHIP', 6, 18")
	@dereferenced
	protected DeltaAutoVariable shipDifficulty;

	@rawTemplate(value = "String, 'SHIP', 6, 19")
	@dereferenced
	protected DeltaAutoVariable shipFactionString;

	@rawTemplate(value = "float, 'SHIP', 6, 20")
	@dereferenced
	protected DeltaAutoVariable frontShield;

	@rawTemplate(value = "float, 'SHIP', 6, 21")
	@dereferenced
	protected DeltaAutoVariable rearShield;

	@rawTemplate(value = "uint32, 'SHIP', 6, 22")
	@dereferenced
	protected DeltaAutoVariable shipGuildID;

	// DeltaAutoMap template <class K, class V, int BaselineName, uint8 Type, int DeltaID>

	@rawTemplate(value = "uint32, float, 'SHIP', 1, 2")
	@dereferenced
	protected DeltaAutoPackedMap componentEfficiency;

	@rawTemplate(value = "uint32, float, 'SHIP', 1, 3")
	@dereferenced
	protected DeltaAutoPackedMap componentEnergyEfficiency;

	@rawTemplate(value = "uint32, float, 'SHIP', 1, 4")
	@dereferenced
	protected DeltaAutoPackedMap componentEnergyCost;

	@rawTemplate(value = "uint32, float, 'SHIP', 1, 5")
	@dereferenced
	protected DeltaAutoPackedMap componentMass;

	@rawTemplate(value = "uint32, UnicodeString, 'SHIP', 1, 6")
	@dereferenced
	protected DeltaAutoPackedMap componentNames;

	@rawTemplate(value = "uint32, uint64, 'SHIP', 1, 7")
	@dereferenced
	protected DeltaAutoPackedMap componentCreator;

	@rawTemplate(value = "uint32, float, 'SHIP', 1, 8")
	@dereferenced
	protected DeltaAutoPackedMap componentMaxDamage;

	@rawTemplate(value = "uint32, float, 'SHIP', 1, 9")
	@dereferenced
	protected DeltaAutoPackedMap componentMinDamage;

	@rawTemplate(value = "uint32, float, 'SHIP', 1, 10")
	@dereferenced
	protected DeltaAutoPackedMap componentShieldEffectiveness;

	@rawTemplate(value = "uint32, float, 'SHIP', 1, 11")
	@dereferenced
	protected DeltaAutoPackedMap componentArmorEffectiveness;

	@rawTemplate(value = "uint32, float, 'SHIP', 1, 12")
	@dereferenced
	protected DeltaAutoPackedMap componentEnergyPerShot;

	@rawTemplate(value = "uint32, float, 'SHIP', 1, 13")
	@dereferenced
	protected DeltaAutoPackedMap componentRefire;

	@rawTemplate(value = "uint32, int, 'SHIP', 1, 14")
	@dereferenced
	protected DeltaAutoPackedMap componentAmmoCurrent;

	@rawTemplate(value = "uint32, int, 'SHIP', 1, 15")
	@dereferenced
	protected DeltaAutoPackedMap componentAmmoMax;

	@rawTemplate(value = "uint32, uint32, 'SHIP', 1, 16")
	@dereferenced
	protected DeltaAutoPackedMap componentAmmoClass;

	@rawTemplate(value = "uint32, float, 'SHIP', 3, 15")
	@dereferenced
	protected DeltaAutoPackedMap componentMaxArmor;

	@rawTemplate(value = "uint32, float, 'SHIP', 3, 16")
	@dereferenced
	protected DeltaAutoPackedMap componentCurrentArmor;

	@rawTemplate(value = "uint32, float, 'SHIP', 3, 17")
	@dereferenced
	protected DeltaAutoPackedMap componentCurrentHitpoints;

	@rawTemplate(value = "uint32, float, 'SHIP', 3, 18")
	@dereferenced
	protected DeltaAutoPackedMap componentMaxHitpoints;

	@rawTemplate(value = "uint32, uint32, 'SHIP', 3, 19")
	@dereferenced
	protected DeltaAutoPackedMap componentOptions;

	@rawTemplate(value = "uint32, float, 'SHIP', 4, 4")
	@dereferenced
	protected DeltaAutoPackedMap componentRefireEfficiency;

	// 6:14
	@dereferenced
	DeltaBitArray componentTargetableBitfield;

	@rawTemplate(value = "uint32, uint32, 'SHIP', 6, 15")
	@dereferenced
	protected DeltaAutoMap componentCRCs;

	@dereferenced
	protected Vector<unsigned long> playersOnBoard;

	protected string certificationRequired;

	float wingsOpenSpeed;

	public ShipObject() {
		Logger.setLoggingName("ShipObject");

		super.objectVisible = 1;

		ownerID = 0;

		super.closeobjects = new CloseObjectsVector();
		super.closeobjects.setNoDuplicateInsertPlan();

		controlDeviceID = 0;
		hyperspacing = false;
		hasWings = false;

		chassisLevel = 0;
		totalCellNumber = 0;

		boundingRadius = 1.f;
		currentSpeed = 0.f;
		staffModifiedSpeed = 0.f;
		speedRotationFactorMax = 1.f;
		speedRotationFactorMin = 1.f;
		speedRotationFactorOptimal = 0.5f;

		chassisSpeed.set(1.f);

		certificationRequired = "";
	}

	public native void notifyLoadFromDatabase();

	@dirty
	public native abstract void sendSlottedObjectsTo(SceneObject player);

	public native void initializeTransientMembers();

	@preLocked
	public native void doRecovery(int latency);

	@preLocked
	public native float getTotalShipDamage();

	@preLocked
	public native void repairShip(float repairAmount, boolean decay = true);

	@preLocked
	public native void scheduleRecovery();

	@preLocked
	public native void cancelRecovery();

	@dirty
	@nativeStub
	@local
	public native ShipObject asShipObject();

	public native abstract void sendTo(SceneObject player, boolean doClose, boolean forceLoadContainer = true);
	public native void sendBaselinesTo(SceneObject player);

	public native void notifyObjectInsertedToZone(SceneObject object);

	@dirty
	public native abstract int notifyObjectInserted(SceneObject object);

	@local
	public native abstract void notifyInsert(TreeEntry obj);

	@local
	public abstract native void notifyDissapear(TreeEntry obj);

	@preLocked
	public abstract native void notifyDespawn(Zone zone);

	@dirty
	public native void sendDestroyTo(SceneObject player);

	public native void notifyInsertToZone(Zone zone);

	@local
	public native abstract void updateZone(boolean lightUpdate, boolean sendPackets = true);

	public abstract native void updatePlayersInShip(boolean lightUpdate, boolean sendPackets = true);

	/*

		Mutators

	*/

	// DeltaVariable Mutators

	// 1:17
	@local
	public void setChassisMaxMass(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		chassisMaxMass.update(value, notifyClient, this, delta, vector);
	}

	// 1:18
	@local
	public void setShieldRechargeRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		shieldRechargeRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:19
	@local
	public void setCapacitorMaxEnergy(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		capacitorMaxEnergy.update(value, notifyClient, this, delta, vector);
	}

	// 1:20
	@local
	public void setCapacitorRechargeRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		capacitorRechargeRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:21
	@local
	public void setEngineAccelerationRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		engineAccelerationRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:22
	@local
	public void setEngineDecelerationRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		engineDecelerationRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:23
	@local
	public void setEnginePitchAccelerationRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		enginePitchAccelerationRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:24
	@local
	public void setEngineYawAccelerationRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		engineYawAccelerationRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:25
	@local
	public void setEngineRollAccelerationRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		engineRollAccelerationRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:26
	@local
	public void setEnginePitchRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		enginePitchRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:27
	@local
	public void setEngineYawRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		engineYawRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:28
	@local
	public void setEngineRollRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		engineRollRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:29
	@local
	public void setEngineMaxSpeed(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		engineMaxSpeed.update(value, notifyClient, this, delta, vector);
	}

	// 1:30
	@local
	public void setReactorGenerationRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		reactorGenerationRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:31
	@local
	public void setBoosterMaxEnergy(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		boosterMaxEnergy.update(value, notifyClient, this, delta, vector);
	}

	// 1:32
	@local
	public void setBoosterRechargeRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		boosterRechargeRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:33
	@local
	public void setBoosterEnergyConsumptionRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		boosterConsumptionRate.update(value, notifyClient, this, delta, vector);
	}

	// 1:34
	@local
	public void setBoosterAcceleration(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		boosterAcceleration.update(value, notifyClient, this, delta, vector);
	}

	// 1:35
	@local
	public void setBoosterMaxSpeed(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		boosterMaxSpeed.update(value, notifyClient, this, delta, vector);
	}

	// 1:36
	@local
	public void setDroidCommandSpeed(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		droidCommandSpeed.update(value, notifyClient, this, delta, vector);
	}

	// 1:37
	@local
	public void setShipDroidID(unsigned long value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		shipDroidID.update(value, notifyClient, this, delta, vector);
	}

	// 3:11
	@local
	public void setSlipRate(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		slip.update(value, notifyClient, this, delta, vector);
	}

	// 3:12
	@local
	public void setCurrentChassisHealth(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		chassisCurrentHealth.update(value, notifyClient, this, delta, vector);
	}

	// 3:13
	@local
	public void setChassisMaxHealth(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		chassisMaxHealth.update(value, notifyClient, this, delta, vector);
	}

	// 3:13
	@local
	public void setShipNameCRC(unsigned int value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		shipNameCRC.update(value, notifyClient, this, delta, vector);
	}

	// 3:20
	@local
	public void setFrontShieldMax(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		frontShieldMax.update(value, notifyClient, this, delta, vector);
	}

	// 3:21
	@local
	public void setRearShieldMax(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		rearShieldMax.update(value, notifyClient, this, delta, vector);
	}

	// 4:0
	@local
	public void setChassisMass(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		chassisMass.update(value, notifyClient, this, delta, vector);
	}

	// 4:1
	@local
	public void setChassisSpeed(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		chassisSpeed.update(value, notifyClient, this, delta, vector);
	}

	// 4:2
	@local
	public void setCapacitorEnergy(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		capacitorEnergy.update(value, notifyClient, this, delta, vector);
	}

	// 4:3
	@local
	public void setBoosterEnergy(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		boosterEnergy.update(value, notifyClient, this, delta, vector);
	}

	// 6:2
	@local
	public void setUniqueID(unsigned short value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		uniqueID.update(value, notifyClient, this, delta, vector);
	}

	// 6:3
	@local
	public void setActualAccelerationRate(float radians, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		actualAccelerationRate.update(radians, notifyClient, this, delta, vector);
	}

	// 6:4
	@local
	public void setActualDecelerationRate(float radians, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		actualDecelerationRate.update(radians, notifyClient, this, delta, vector);
	}

	// 6:5
	@local
	public void setActualPitchAccelerationRate(float scale, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		actualPitchAccelerationRate.update(scale, notifyClient, this, delta, vector);
	}

	// 6:6
	@local
	public void setActualYawAccelerationRate(float scale, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		actualYawAccelerationRate.update(scale, notifyClient, this, delta, vector);
	}

	// 6:7
	@local
	public void setActualRollAccelerationRate(float scale, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		actualRollAccelerationRate.update(scale, notifyClient, this, delta, vector);
	}

	// 6:8
	@local
	public void setActualPitchRate(float radians, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		actualPitchRate.update(radians, notifyClient, this, delta, vector);
	}

	// 6:9
	@local
	public void setActualYawRate(float radians, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		actualYawRate.update(radians, notifyClient, this, delta, vector);
	}

	// 6:10
	@local
	public void setActualRollRate(float radians, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		actualRollRate.update(radians, notifyClient, this, delta, vector);
	}

	// 6:11
	@local
	public void setActualMaxSpeed(float speed, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		actualMaxSpeed.update(speed, notifyClient, this, delta, vector);
	}

	// 6:12
	@local
	public void setShipTargetID(unsigned long value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		shipTargetID.update(value, notifyClient, this, delta, vector);
	}

	// 6:13
	@local
	public void setShipTargetSlot(int value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		shipTargetSlot.update(value, notifyClient, this, delta, vector);
	}

	// 6:17
	@local
	public void setShipType(@dereferenced final string value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		shipType.update(value, notifyClient, this, delta, vector);
	}

	// 6:18
	@local
	public void setShipDifficulty(@dereferenced final string value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		shipDifficulty.update(value, notifyClient, this, delta, vector);
	}

	// 6:19
	@local
	public void setShipFactionString(@dereferenced final string factionString, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		if (factionString == "rebel") {
			super.setFaction(String.hashCode(factionString));
		} else if (factionString == "imperial") {
			super.setFaction(String.hashCode(factionString));
		} else {
			super.setFaction(0);
		}

		shipFactionString.update(factionString, notifyClient, this, delta, vector);
		setShipFaction(String.hashCode(factionString));
	}

	public void setShipFaction(unsigned int value) {
		shipFaction = value;
	}

	// 6:20
	@local
	public void setFrontShield(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		frontShield.update(value, notifyClient, this, delta, vector);
	}

	// 6:21
	@local
	public void setRearShield(float value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		rearShield.update(value, notifyClient, this, delta, vector);
	}

	// 6:22
	@local
	public void setShipGuildID(unsigned int value, boolean notifyClient = true, DeltaMessage delta = null, ShipDeltaVector vector = null) {
		shipGuildID.update(value, notifyClient, this, delta, vector);
	}

	// DeltaVector mutator

	// 1:2
	@local
	public void setEfficiency(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentEfficiency.update(slot, value, message, command, vector);
	}

	// 1:3
	@local
	public void setEnergyEfficiency(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentEnergyEfficiency.update(slot, value, message, command, vector);
	}

	// 1:4
	@local
	public void setEnergyCost(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentEnergyCost.update(slot, value, message, command, vector);
	}

	// 1:5
	@local
	public void setComponentMass(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentMass.update(slot, value, message, command, vector);
	}

	// 1:6
	@local
	public void setComponentName(int slot, @dereferenced final unicode value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentNames.update(slot, value, message, command, vector);
	}

	// 1:7
	@local
	public void setComponentCreator(int slot, unsigned long value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentCreator.update(slot, value, message, command, vector);
	}

	// 1:8
	@local
	public void setMaxDamage(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentMaxDamage.update(slot, value, message, command, vector);
	}

	// 1:9
	@local
	public void setMinDamage(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentMinDamage.update(slot, value, message, command, vector);
	}

	// 1:10
	@local
	public void setShieldEffectiveness(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentShieldEffectiveness.update(slot, value, message, command, vector);
	}

	// 1:11
	@local
	public void setArmorEffectiveness(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentArmorEffectiveness.update(slot, value, message, command, vector);
	}

	// 1:12
	@local
	public void setEnergyPerShot(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentEnergyPerShot.update(slot, value, message, command, vector);
	}

	// 1:13
	@local
	public void setRefireRate(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentRefire.update(slot, value, message, command, vector);
	}

	// 1:14
	@local
	public void setCurrentAmmo(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentAmmoCurrent.update(slot, value, message, command, vector);
	}

	// 1:15
	@local
	public void setMaxAmmo(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentAmmoMax.update(slot, value, message, command, vector);
	}

	// 1:16
	@local
	public void setAmmoClass(int slot, unsigned int value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentAmmoClass.update(slot, value, message, command, vector);
	}

	// 3:15
	@local
	public void setComponentMaxArmor(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentMaxArmor.update(slot, value, message, command, vector);
	}

	// 3:16
	@local
	public void setComponentArmor(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentCurrentArmor.update(slot, value, message, command, vector);
	}

	// 3:17
	@local
	public void setComponentHitpoints(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentCurrentHitpoints.update(slot, value, message, command, vector);
	}

	// 3:18
	@local
	public void setComponentMaxHitpoints(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentMaxHitpoints.update(slot, value, message, command, vector);
	}

	// 3:19
	@local
	public void setComponentOptions(int slot, unsigned int value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentOptions.update(slot, value, message, command, vector);
	}

	// 4:4
	@local
	public void setRefireEfficiency(int slot, float value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentRefireEfficiency.update(slot, value, message, command, vector);
	}

	// 6:15
	@local
	public void setComponentCRC(int slot, unsigned int value, DeltaMessage message = null, byte command = 0, ShipDeltaVector vector = null) {
		componentCRCs.update(slot, value, message, command, vector);
	}

	// End DeltaVector Mutators

	public void setOwner(CreatureObject object) {
		owner = object;
		ownerID = object.getObjectID();
	}

	public void setPilotChair(SceneObject object) {
		pilotChair = object;
	}

	public void setOperationsChair(SceneObject object) {
		operationsChair = object;
	}

	public void setTurretLadder(SceneObject object) {
		turretLadder = object;
	}

	public void setComponentTargetable(int slot, boolean targetable) {
		componentTargetableBitfield.setBit(slot, targetable);
	}

	@preLocked
	public void setHyperspacing(boolean value) {
		hyperspacing = value;

		if (hyperspacing) {
			setHyperspaceDelay();
		}
	}

	@preLocked
	public native void setHyperspaceDelay();

	@local
	public void setHasWings(boolean value) {
		hasWings = value;
	}

	public native void setShipName(@dereferenced final string name, boolean notifyClient = true);


	@local
	public void setChassisCategory(@dereferenced final string value) {
		chassisCategory = value;
	}

	@local
	public void setChassisLevel(int value) {
		chassisLevel = value;
	}

	@preLocked
	public void setControlDeviceID(unsigned long oid) {
		controlDeviceID = oid;
	}

	@local
	public native void setRotationMatrix(@dereferenced final Quaternion value);

	public void setBoundingRadius(float value) {
		boundingRadius = value;
	}

	public void setCurrentSpeed(float value) {
		currentSpeed = value;
	}

	public void setSpeedRotationFactorMax(float value) {
		speedRotationFactorMax = value;
	}

	public void setSpeedRotationFactorMin(float value) {
		speedRotationFactorMin = value;
	}

	public void setSpeedRotationFactorOptimal(float value) {
		speedRotationFactorOptimal = value;
	}

	@preLocked
	public void setStaffShipSpeed(float speed) {
		staffModifiedSpeed = speed;
	}

	@preLocked
	public native void updateLastDamageReceived();

	@preLocked
	public native void addPlayerOnBoard(CreatureObject player);

	@preLocked
	public native void removePlayerOnBoard(CreatureObject player);

	@preLocked
	public native void clearPlayersOnBoard();

	/*

		Accesors

	*/

	// DeltaVector get

	// 1:2
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getComponentEfficiencyMap() {
		return componentEfficiency;
	}

	// 1:3
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getComponentEnergyEfficiencyMap() {
		return componentEnergyEfficiency;
	}

	// 1:4
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getComponentEnergyCostMap() {
		return componentEnergyCost;
	}

	// 1:5
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getComponentMassMap() {
		return componentMass;
	}

	// 1:6
	@local
	@read
	public final DeltaVectorMap<unsigned int, unicode> getComponentNameMap() {
		return componentNames;
	}

	// 1:7
	@local
	@read
	public final DeltaVectorMap<unsigned int, unsigned long> getComponentCreatorMap() {
		return componentCreator;
	}

	// 1:8
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getComponentMaxDamageMap() {
		return componentMaxDamage;
	}

	// 1:9
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getComponentMinDamageMap() {
		return componentMinDamage;
	}

	// 1:10
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getShieldEffectivenessMap() {
		return componentShieldEffectiveness;
	}

	// 1:11
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getArmorEffectivenessMap() {
		return componentArmorEffectiveness;
	}

	// 1:12
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getEnergyPerShotMap() {
		return componentEnergyPerShot;
	}

	// 1:13
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getComponentRefireRate() {
		return componentRefire;
	}

	// 1:14
	@local
	@read
	public final DeltaVectorMap<unsigned int, int> getCurrentAmmoMap() {
		return componentAmmoCurrent;
	}

	// 1:15
	@local
	@read
	public final DeltaVectorMap<unsigned int, int> getMaxAmmoMap() {
		return componentAmmoMax;
	}

	// 1:16
	@local
	@read
	public final DeltaVectorMap<unsigned int, unsigned int> getAmmoClassMap() {
		return componentAmmoClass;
	}

	// 3:15
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getMaxArmorMap() {
		return componentMaxArmor;
	}

	// 3:16
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getCurrentArmorMap() {
		return componentCurrentArmor;
	}

	// 3:17
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getCurrentHitpointsMap() {
		return componentCurrentHitpoints;
	}

	//  3:18
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getMaxHitpointsMap() {
		return componentMaxHitpoints;
	}

	// 3:19
	@local
	@read
	public final DeltaVectorMap<unsigned int, unsigned int> getComponentOptionsMap() {
		return componentOptions;
	}

	// 4:4
	@local
	@read
	public final DeltaVectorMap<unsigned int, float> getComponentRefireEfficiency() {
		return componentRefireEfficiency;
	}

	// 6:14
	@local
	@read
	public final DeltaBitArray getTargetableBitfield() {
		return componentTargetableBitfield;
	}

	// 6:15
	@local
	@read
	public final DeltaVectorMap<unsigned int, unsigned int> getShipComponentMap() {
		return componentCRCs;
	}

	// delta variable get

	// 1:17
	public float getChassisMaxMass() {
		return chassisMaxMass.get();
	}

	// 1:18
	public float getShieldRechargeRate() {
		return shieldRechargeRate.get();
	}

	// 1:19
	public float getCapacitorMaxEnergy() {
		return capacitorMaxEnergy.get();
	}

	// 1:20
	public float getCapacitorRechargeRate() {
		return capacitorRechargeRate.get();
	}

	// 1:21
	public float getEngineAccelerationRate() {
		return engineAccelerationRate.get();
	}

	// 1:22
	public float getEngineDecelerationRate() {
		return engineDecelerationRate.get();
	}

	// 1:23
	public float getEnginePitchAccelerationRate() {
		return enginePitchAccelerationRate.get();
	}

	// 1:24
	public float getEngineYawAccelerationRate() {
		return engineYawAccelerationRate.get();
	}

	// 1:25
	public float getEngineRollAccelerationRate() {
		return engineRollAccelerationRate.get();
	}

	// 1:26
	public float getEnginePitchRate() {
		return enginePitchRate.get();
	}

	// 1:27
	public float getEngineYawRate() {
		return engineYawRate.get();
	}

	// 1:28
	public float getEngineRollRate() {
		return engineRollRate.get();
	}

	// 1:29
	public float getEngineMaxSpeed() {
		return engineMaxSpeed.get();
	}

	// 1:30
	public float getReactorGenerationRate() {
		return reactorGenerationRate.get();
	}

	// 1:31
	public float getBoosterMaxEnergy() {
		return boosterMaxEnergy.get();
	}

	// 1:32
	public float getBoosterRechargeRate() {
		return boosterRechargeRate.get();
	}

	// 1:33
	public float getBoosterConsumptionRate() {
		return boosterConsumptionRate.get();
	}

	// 1:34
	public float getBoosterAcceleration() {
		return boosterAcceleration.get();
	}

	// 1:35
	public float getBoosterMaxSpeed() {
		return boosterMaxSpeed.get();
	}

	// 1:36
	public float getDroidCommandSpeed() {
		return droidCommandSpeed.get();
	}

	// 1:37
	public unsigned long getShipDroidID() {
		return shipDroidID.get();
	}

	// 3:11
	public float getSlip() {
		return slip.get();
	}

	// 3:12
	public float getChassisCurrentHealth() {
		return chassisCurrentHealth.get();
	}

	// 3:13
	public float getChassisMaxHealth() {
		return chassisMaxHealth.get();
	}

	// 3:14
	public unsigned int getShipNameCRC() {
		return shipNameCRC.get();
	}

	// 3:20
	public float getMaxFrontShield() {
		return frontShieldMax.get();
	}

	// 3:21
	public float getMaxRearShield() {
		return rearShieldMax.get();
	}

	// 4:0
	public float getChassisMass() {
		return chassisMass.get();
	}

	// 4:1
	public float getChassisSpeed() {
		return chassisSpeed.get();
	}

	// 4:2
	public float getCapacitorEnergy() {
		return capacitorEnergy.get();
	}

	// 4:3
	public float getBoosterEnergy() {
		return boosterEnergy.get();
	}

	// 6:2
	public unsigned short getUniqueID() {
		return uniqueID.get();
	}

	// 6:3
	public float getActualAccelerationRate() {
		return actualAccelerationRate.get();
	}

	// 6:4
	public float getActualDecelerationRate() {
		return actualDecelerationRate.get();
	}

	// 6:5
	public float getActualPitchAccelerationRate() {
		return actualPitchAccelerationRate.get();
	}

	// 6:6
	public float getActualYawAccelerationRate() {
		return actualYawAccelerationRate.get();
	}

	// 6:7
	public float getActualRollAccelerationRate() {
		return actualRollAccelerationRate.get();
	}

	// 6:8
	public float getActualPitchRate() {
		return actualPitchRate.get();
	}

	// 6:9
	public float getActualYawRate() {
		return actualYawRate.get();
	}

	// 6:10
	public float getActualRollRate() {
		return actualRollRate.get();
	}

	// 6:11
	public float getActualMaxSpeed() {
		return actualMaxSpeed.get();
	}

	// 6:12
	public unsigned long getShipTargetID() {
		return shipTargetID.get();
	}

	// 6:13
	public int getShipTargetSlot() {
		return shipTargetSlot.get();
	}

	// 6:17
	@read
	@dereferenced
	public string getShipType() {
		return shipType.get();
	}

	// 6:18
	@read
	@dereferenced
	public string getShipDifficulty() {
		return shipDifficulty.get();
	}

	// 6:19
	@read
	@dereferenced
	public string getShipFactionString() {
		return shipFactionString.get();
	}

	// 6:20
	public float getFrontShield() {
		return frontShield.get();
	}

	// 6:21
	public float getRearShield() {
		return rearShield.get();
	}

	// 6:22
	public unsigned int getShipGuildID() {
		return shipGuildID.get();
	}

	// deltas end

	@local
	public DeltaBitArray getTargetableBitfield() {
		return componentTargetableBitfield;
	}

	public string getShipChassisName() {
		return chassisDataName;
	}

	public native string getShipName();

	public native string getShipLaunchedName();

	public float getComponentEnergyEfficiency(int slot) {
		return componentEnergyEfficiency.get(slot);
	}

	public float getComponentEfficiency(int slot) {
		return componentEfficiency.get(slot);
	}

	@weakReference
	public CreatureObject getOwner() {
		return owner;
	}

	public unsigned long getOwnerID() {
		return ownerID;
	}

	@weakReference
	public SceneObject getPilotChair() {
		return pilotChair;
	}

	@weakReference
	public SceneObject getOperationsChair() {
		return operationsChair;
	}

	@weakReference
	public SceneObject getTurretLadder() {
		return turretLadder;
	}

	@dirty
	public unsigned int getShipFaction() {
		return shipFaction;
	}

	@preLocked
	public native void installAmmo(CreatureObject owner, SceneObject component, int slot, boolean notifyClient = false);

	@preLocked
	public native void uninstallAmmo(CreatureObject owner, int slot, boolean notifyClient = false);

	@preLocked
	public native void install(CreatureObject owner, SceneObject component, int slot, boolean notifyClient = false);

	@preLocked
	public native void uninstall(CreatureObject owner, int slot, boolean notifyClient);

	@local
	public abstract native void updateCraftingValues(CraftingValues values, boolean firstUpdate);

	@local
	public native abstract void loadTemplateData(SharedObjectTemplate templateData);

	@dirty
	@local
	@nativeStub
	public native boolean isShipObject();

	@dirty
	public boolean isHyperspacing() {
		return hyperspacing;
	}

	@dirty
	public boolean hasShipWings() {
		return hasWings;
	}

	@dirty
	public boolean isBoosterActive() {
		return hasComponentFlag(7,4);
	}

	public final string getChassisCategory() {
		return chassisCategory;
	}

	public int getChassisLevel() {
		return chassisLevel;
	}

	@dirty
	@local
	public native boolean checkInConversationRange(SceneObject object);

	public native int getHyperspaceDelay();

	public unsigned long getControlDeviceID() {
		return controlDeviceID;
	}

	@dirty
	public ShipComponent getComponentObject(unsigned int slot) {
		return components.get(slot);
	}

	@dirty
	public boolean isReadyToBoost() {
		return boostTimer.isPast();
	}

	public native boolean hasComponentFlag(unsigned int slot, unsigned int flag);

	@preLocked
	@local
	public native void addComponentFlag(unsigned int slot, unsigned int flag, boolean notify = true, ShipDeltaVector vector = null);

	@preLocked
	@local
	public native void removeComponentFlag(unsigned int slot, unsigned int flag, boolean notify = true, ShipDeltaVector vector = null);

	@preLocked
	@local
	public native void resetComponentFlag(unsigned int slot, boolean notify = true, ShipDeltaVector vector = null);

	@preLocked
	@local
	public native void setComponentDemolished(unsigned int slot, boolean notify = true, ShipDeltaVector vector = null);

	public native void restartBooster();

	public native float calculateCurrentMass();

	public native float calculateCurrentEnergyCost();

	@dirty
	@local
	public native void sendPvpStatusTo(CreatureObject player);

	@preLocked
	@local
	public native ShipDeltaVector getDeltaVector();

	@preLocked
	@local
	public native ShipTargetVector getTargetVector();

	@preLocked
	public abstract native void destroyObjectFromDatabase(boolean destroyContainedObjects = false);

	public native CreatureObject getPilot();

	public native CreatureObject getShipOperator();

	public native CreatureObject getTurretOperatorTop();

	public native CreatureObject getTurretOperatorBottom();

	/**
	 * Evaluates if this can be attacked by object
	 * @pre { }
	 * @post { }
	 * @return returns true if object can attack this
	 */
	@dirty
	public native abstract boolean isAttackableBy(TangibleObject object);

	@dirty
	public native boolean isAttackableBy(CreatureObject object);

	@dirty
	public native abstract boolean isAggressiveTo(TangibleObject object);

	@local
	public final Matrix4 getRotationMatrix() {
		return rotationMatrix;
	}

	@local
	public final Matrix4 getConjugateMatrix() {
		return conjugateMatrix;
	}

	public float getBoundingRadius() {
		return boundingRadius;
	}

	public float getCurrentSpeed() {
		return currentSpeed;
	}

	public float getSpeedRotationFactorMax() {
		return speedRotationFactorMax;
	}

	public float getSpeedRotationFactorMin() {
		return speedRotationFactorMin;
	}

	public float getSpeedRotationFactorOptimal() {
		return speedRotationFactorOptimal;
	}

	public native unsigned long getLastDamageReceivedMili();

	public native float getComponentCondition(unsigned int slot);

	public native int getTotalPlayersOnBoard();

	public native CreatureObject getPlayerOnBoard(int index);

	@local
	@dereferenced
	public native Vector<unsigned long> getPlayersOnBoard();

	public native void sendShipMembersMessage(final string message);

	public native void sendShipMembersMusicMessage(final string message);

	public native void sendMembersHyperspaceBeginMessage(final string zoneName, @dereferenced final Vector3 location);

	public native void sendMembersHyperspaceOrientMessage(final string zoneName, @dereferenced final Vector3 location);

	@dirty
	@local
	public native void sendMembersBaseMessage(BaseMessage message, boolean sendSelf = true);

	@preLocked
	@arg1preLocked
	public abstract native void awardLootItems(ShipAiAgent destructedShip, int payout);

	public native boolean isShipLaunched();

	@read
	public native int getReceiverFlags();

	public native boolean isComponentInstalled(unsigned int slot);

	public native boolean isComponentFunctional(unsigned int slot);

	public native float calculateActualComponentEfficiency(unsigned int slot);

	public native float calculateSpeedRotationFactor();

	public native float calculateActualAccelerationRate();

	public native float calculateActualDecelerationRate();

	public native float calculateActualMaxSpeed();

	@dirty
	public native abstract float getOutOfRangeDistance(unsigned long specialRangeObjectID = 0);

	@preLocked
	@local
	public native void updateSpeedRotationValues(boolean notifyClient = true, ShipDeltaVector vector = null);

	@preLocked
	@local
	public native void updateActualEngineValues(boolean notifyClient = true, ShipDeltaVector vector = null);

	@preLocked
	@local
	public native void updateComponentFlags(boolean notifyClient = true, ShipDeltaVector vector = null);

	public native void initializeUniqueID(boolean notifyClient = true);

	public native boolean canBePilotedBy(CreatureObject player);

	public native boolean hasComponentsInstalled();

	public native boolean isStarterShip();

	public native boolean isSorosuubSpaceYacht();

	public void setSpaceLaunchZone(string zoneName) {
		launchPoint.setGroundZoneName(zoneName);
	}

	public void setSpaceLaunchCityName(string cityName) {
		launchPoint.setCityName(cityName);
	}

	public void setSpaceLaunchLocation(@dereferenced Vector3 location) {
		launchPoint.setLocation(location.getX(), location.getZ(), location.getY());
	}

	@dereferenced
	public string getSpaceLaunchZone() {
		return launchPoint.getGoundZoneName();
	}

	@dereferenced
	public string getSpaceLaunchCityName() {
		return launchPoint.getCityName();
	}

	@local
	@dereferenced
	public Vector3 getSpaceLaunchLocation() {
		return launchPoint.getLocation();
	}

	@read
	public string getCertificationRequired() {
		return certificationRequired;
	}

	public void setCertificationRequired(final string cert) {
		certificationRequired = cert;
	}
}
