/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.objects.ship;

import engine.log.Logger;
import server.zone.objects.ship.ShipObject;
import server.zone.objects.scene.SceneObject;

class SpaceStationObject extends ShipObject {

	public SpaceStationObject() {
		Logger.setLoggingName("SpaceStationObject");
	}

	@dirty
	@local
	@nativeStub
	public native boolean isSpaceStationObject();

	@dirty
	@preLocked
	public native boolean sendConversationStartTo(SceneObject player);
}