/*
 *	server/zone/objects/creature/conversation/TrainerConversationObserver.cpp generated by engine3 IDL compiler 0.60
 */

#include "TrainerConversationObserver.h"

/*
 *	TrainerConversationObserverStub
 */

TrainerConversationObserver::TrainerConversationObserver(ConversationTemplate* conversationTemplate) : ConversationObserver(DummyConstructorParameter::instance()) {
	TrainerConversationObserverImplementation* _implementation = new TrainerConversationObserverImplementation(conversationTemplate);
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("TrainerConversationObserver");
}

TrainerConversationObserver::TrainerConversationObserver(DummyConstructorParameter* param) : ConversationObserver(param) {
	_setClassName("TrainerConversationObserver");
}

TrainerConversationObserver::~TrainerConversationObserver() {
}



DistributedObjectServant* TrainerConversationObserver::_getImplementation() {

	_updated = true;
	return _impl;
}

void TrainerConversationObserver::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	TrainerConversationObserverImplementation
 */

TrainerConversationObserverImplementation::TrainerConversationObserverImplementation(DummyConstructorParameter* param) : ConversationObserverImplementation(param) {
	_initializeImplementation();
}


TrainerConversationObserverImplementation::~TrainerConversationObserverImplementation() {
}


void TrainerConversationObserverImplementation::finalize() {
}

void TrainerConversationObserverImplementation::_initializeImplementation() {
	_setClassHelper(TrainerConversationObserverHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void TrainerConversationObserverImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<TrainerConversationObserver*>(stub);
	ConversationObserverImplementation::_setStub(stub);
}

DistributedObjectStub* TrainerConversationObserverImplementation::_getStub() {
	return _this.get();
}

TrainerConversationObserverImplementation::operator const TrainerConversationObserver*() {
	return _this.get();
}

void TrainerConversationObserverImplementation::lock(bool doLock) {
	_this.get()->lock(doLock);
}

void TrainerConversationObserverImplementation::lock(ManagedObject* obj) {
	_this.get()->lock(obj);
}

void TrainerConversationObserverImplementation::rlock(bool doLock) {
	_this.get()->rlock(doLock);
}

void TrainerConversationObserverImplementation::wlock(bool doLock) {
	_this.get()->wlock(doLock);
}

void TrainerConversationObserverImplementation::wlock(ManagedObject* obj) {
	_this.get()->wlock(obj);
}

void TrainerConversationObserverImplementation::unlock(bool doLock) {
	_this.get()->unlock(doLock);
}

void TrainerConversationObserverImplementation::runlock(bool doLock) {
	_this.get()->runlock(doLock);
}

void TrainerConversationObserverImplementation::_serializationHelperMethod() {
	ConversationObserverImplementation::_serializationHelperMethod();

	_setClassName("TrainerConversationObserver");

}

void TrainerConversationObserverImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		String _name;
		_name.parseFromBinaryStream(stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(TrainerConversationObserverImplementation::readObjectMember(stream, _name)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool TrainerConversationObserverImplementation::readObjectMember(ObjectInputStream* stream, const String& _name) {
	if (ConversationObserverImplementation::readObjectMember(stream, _name))
		return true;

	if (_name == "TrainerConversationObserver.trainerScreenHandlers") {
		TypeInfo<TrainerScreenHandlers >::parseFromBinaryStream(&trainerScreenHandlers, stream);
		return true;
	}


	return false;
}

void TrainerConversationObserverImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = TrainerConversationObserverImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int TrainerConversationObserverImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ConversationObserverImplementation::writeObjectMembers(stream);

	String _name;
	int _offset;
	uint32 _totalSize;
	_name = "TrainerConversationObserver.trainerScreenHandlers";
	_name.toBinaryStream(stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<TrainerScreenHandlers >::toBinaryStream(&trainerScreenHandlers, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);


	return _count + 1;
}

/*
 *	TrainerConversationObserverAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


TrainerConversationObserverAdapter::TrainerConversationObserverAdapter(TrainerConversationObserver* obj) : ConversationObserverAdapter(obj) {
}

void TrainerConversationObserverAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		throw Exception("Method does not exists");
	}
}

/*
 *	TrainerConversationObserverHelper
 */

TrainerConversationObserverHelper* TrainerConversationObserverHelper::staticInitializer = TrainerConversationObserverHelper::instance();

TrainerConversationObserverHelper::TrainerConversationObserverHelper() {
	className = "TrainerConversationObserver";

	Core::getObjectBroker()->registerClass(className, this);
}

void TrainerConversationObserverHelper::finalizeHelper() {
	TrainerConversationObserverHelper::finalize();
}

DistributedObject* TrainerConversationObserverHelper::instantiateObject() {
	return new TrainerConversationObserver(DummyConstructorParameter::instance());
}

DistributedObjectServant* TrainerConversationObserverHelper::instantiateServant() {
	return new TrainerConversationObserverImplementation(DummyConstructorParameter::instance());
}

DistributedObjectAdapter* TrainerConversationObserverHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new TrainerConversationObserverAdapter(static_cast<TrainerConversationObserver*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

