/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.tangible.terminal.guild;

import server.zone.objects.tangible.terminal.Terminal;
import server.zone.objects.scene.SceneObject;
import engine.lua.LuaObject;
import server.zone.objects.guild.GuildObject;
import server.zone.objects.creature.CreatureObject;
import server.zone.packets.object.ObjectMenuResponse;
import server.zone.Zone;

class GuildTerminal extends Terminal {

	public GuildTerminal() {
		Logger.setLoggingName("GuildTerminal");
	}

	public void initializeTransientMembers() {
		super.initializeTransientMembers();
		
		Logger.setLoggingName("GuildTerminal");
	}

	@dirty
	public native void fillObjectMenuResponse(ObjectMenuResponse menuResponse, CreatureObject player);

	public native int handleObjectMenuSelect(CreatureObject player, byte selectedID);

	@dirty
	public boolean isGuildTerminal() {
		return true;
	}
}
