package server.zone.objects.installation;

import server.zone.objects.installation.InstallationObject;

class HarvesterObject extends InstallationObject {
	public HarvesterObject() {
		Logger.setLoggingName("HarvesterObject");
	}
}