import "../../tangible/TangibleObject";
import "../../creature/CreatureObject";
import "../../player/Player";
import "../../tangible/deed/DeedObject";
import "../../tangible/deed/harvesterdeed/HarvesterDeed";
import "../InstallationObject";

import "../../../Zone";

include "engine/service/Message";

interface HarvesterObject implements InstallationObject {

	HarvesterObject(unsigned long oid) {
		super (oid);
	}
	
	HarvesterObject(unsigned long oid, HarvesterDeed theDeed) {
		super (oid, theDeed);
	}

	int getHarvesterType();
	void changeActiveResourceID(unsigned long oid);
	void updateOperatorsAddBlankActiveRescource();
}
