/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.managers.space;

import server.zone.managers.planet.PlanetManager;
import server.zone.ZoneProcessServer;
import server.zone.Zone;
include engine.log.Logger;

class SpaceManager extends PlanetManager {
	public SpaceManager(Zone planet, ZoneProcessServer srv) {
		super(planet, srv);
		
		Logger.setLoggingName("SpaceManager " + planet.getZoneName());
		Logger.setLogging(false);
		Logger.setGlobalLogging(true);
	}

	public void initialize() {
		Logger.info("loading space manager " + super.zone.getZoneName());
	}
}
