/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

/*
 *	server/zone/objects/intangible/IntangibleObject.cpp generated by Engine3 IDL compiler 0.51
 */

#include "../scene/SceneObject.h"

#include "../player/Player.h"

#include "IntangibleObject.h"

#include "IntangibleObjectImplementation.h"

/*
 *	IntangibleObjectStub
 */

IntangibleObject::IntangibleObject() : SceneObject(NULL) {
}

IntangibleObject::IntangibleObject(ORBObjectServant* obj) : SceneObject(obj) {
}

IntangibleObject::IntangibleObject(IntangibleObject& ref) : SceneObject(ref) {
}

IntangibleObject::~IntangibleObject() {
}

IntangibleObject* IntangibleObject::clone() {
	return new IntangibleObject(*this);
}


void IntangibleObject::sendTo(Player* player, bool doClose) {
	 if (!deployed)
		throw ObjectNotDeployedException(this);

	if (_impl == NULL) {
		ORBMethodInvocation invocation(this, 6);
		invocation.addObjectParameter(player);
		invocation.addBooleanParameter(doClose);

		invocation.executeWithVoidReturn();
	} else
		((IntangibleObjectImplementation*) _impl)->sendTo(player, doClose);
}

void IntangibleObject::sendDestroyTo(Player* player) {
	 if (!deployed)
		throw ObjectNotDeployedException(this);

	if (_impl == NULL) {
		ORBMethodInvocation invocation(this, 7);
		invocation.addObjectParameter(player);

		invocation.executeWithVoidReturn();
	} else
		((IntangibleObjectImplementation*) _impl)->sendDestroyTo(player);
}

void IntangibleObject::setName(const string& name) {
	 if (!deployed)
		throw ObjectNotDeployedException(this);

	if (_impl == NULL) {
		ORBMethodInvocation invocation(this, 8);
		invocation.addAsciiParameter(name);

		invocation.executeWithVoidReturn();
	} else
		((IntangibleObjectImplementation*) _impl)->setName(name);
}

void IntangibleObject::setDetailName(const string& detail) {
	 if (!deployed)
		throw ObjectNotDeployedException(this);

	if (_impl == NULL) {
		ORBMethodInvocation invocation(this, 9);
		invocation.addAsciiParameter(detail);

		invocation.executeWithVoidReturn();
	} else
		((IntangibleObjectImplementation*) _impl)->setDetailName(detail);
}

void IntangibleObject::setWorldObject(SceneObject* obj) {
	 if (!deployed)
		throw ObjectNotDeployedException(this);

	if (_impl == NULL) {
		ORBMethodInvocation invocation(this, 10);
		invocation.addObjectParameter(obj);

		invocation.executeWithVoidReturn();
	} else
		((IntangibleObjectImplementation*) _impl)->setWorldObject(obj);
}

void IntangibleObject::updateStatus(unsigned int stat) {
	 if (!deployed)
		throw ObjectNotDeployedException(this);

	if (_impl == NULL) {
		ORBMethodInvocation invocation(this, 11);
		invocation.addUnsignedIntParameter(stat);

		invocation.executeWithVoidReturn();
	} else
		((IntangibleObjectImplementation*) _impl)->updateStatus(stat);
}

string& IntangibleObject::getName() {
	 if (!deployed)
		throw ObjectNotDeployedException(this);

	if (_impl == NULL) {
		ORBMethodInvocation invocation(this, 12);

		invocation.executeWithAsciiReturn(_return_getName);
		return _return_getName;
	} else
		return ((IntangibleObjectImplementation*) _impl)->getName();
}

string& IntangibleObject::getDetailName() {
	 if (!deployed)
		throw ObjectNotDeployedException(this);

	if (_impl == NULL) {
		ORBMethodInvocation invocation(this, 13);

		invocation.executeWithAsciiReturn(_return_getDetailName);
		return _return_getDetailName;
	} else
		return ((IntangibleObjectImplementation*) _impl)->getDetailName();
}

SceneObject* IntangibleObject::getWorldObject() {
	 if (!deployed)
		throw ObjectNotDeployedException(this);

	if (_impl == NULL) {
		ORBMethodInvocation invocation(this, 14);

		return (SceneObject*) invocation.executeWithObjectReturn();
	} else
		return ((IntangibleObjectImplementation*) _impl)->getWorldObject();
}

unsigned int IntangibleObject::getStatus() {
	 if (!deployed)
		throw ObjectNotDeployedException(this);

	if (_impl == NULL) {
		ORBMethodInvocation invocation(this, 15);

		return invocation.executeWithUnsignedIntReturn();
	} else
		return ((IntangibleObjectImplementation*) _impl)->getStatus();
}

/*
 *	IntangibleObjectAdapter
 */

IntangibleObjectAdapter::IntangibleObjectAdapter(IntangibleObjectImplementation* obj) : SceneObjectAdapter(obj) {
}

Packet* IntangibleObjectAdapter::invokeMethod(uint32 methid, ORBMethodInvocation* inv) {
	Packet* resp = new MethodReturnMessage(0);

	switch (methid) {
	case 6:
		sendTo((Player*) inv->getObjectParameter(), inv->getBooleanParameter());
		break;
	case 7:
		sendDestroyTo((Player*) inv->getObjectParameter());
		break;
	case 8:
		setName(inv->getAsciiParameter(_param0_setName__string_));
		break;
	case 9:
		setDetailName(inv->getAsciiParameter(_param0_setDetailName__string_));
		break;
	case 10:
		setWorldObject((SceneObject*) inv->getObjectParameter());
		break;
	case 11:
		updateStatus(inv->getUnsignedIntParameter());
		break;
	case 12:
		resp->insertAscii(getName());
		break;
	case 13:
		resp->insertAscii(getDetailName());
		break;
	case 14:
		resp->insertLong(getWorldObject()->_getORBObjectID());
		break;
	case 15:
		resp->insertInt(getStatus());
		break;
	default:
		return NULL;
	}

	return resp;
}

void IntangibleObjectAdapter::sendTo(Player* player, bool doClose) {
	return ((IntangibleObjectImplementation*) impl)->sendTo(player, doClose);
}

void IntangibleObjectAdapter::sendDestroyTo(Player* player) {
	return ((IntangibleObjectImplementation*) impl)->sendDestroyTo(player);
}

void IntangibleObjectAdapter::setName(const string& name) {
	return ((IntangibleObjectImplementation*) impl)->setName(name);
}

void IntangibleObjectAdapter::setDetailName(const string& detail) {
	return ((IntangibleObjectImplementation*) impl)->setDetailName(detail);
}

void IntangibleObjectAdapter::setWorldObject(SceneObject* obj) {
	return ((IntangibleObjectImplementation*) impl)->setWorldObject(obj);
}

void IntangibleObjectAdapter::updateStatus(unsigned int stat) {
	return ((IntangibleObjectImplementation*) impl)->updateStatus(stat);
}

string& IntangibleObjectAdapter::getName() {
	return ((IntangibleObjectImplementation*) impl)->getName();
}

string& IntangibleObjectAdapter::getDetailName() {
	return ((IntangibleObjectImplementation*) impl)->getDetailName();
}

SceneObject* IntangibleObjectAdapter::getWorldObject() {
	return ((IntangibleObjectImplementation*) impl)->getWorldObject();
}

unsigned int IntangibleObjectAdapter::getStatus() {
	return ((IntangibleObjectImplementation*) impl)->getStatus();
}

/*
 *	IntangibleObjectHelper
 */

IntangibleObjectHelper::IntangibleObjectHelper() {
	className = "IntangibleObject";

	ObjectRequestBroker::instance()->registerClass(className, this);
}

void IntangibleObjectHelper::finalizeHelper() {
	IntangibleObjectHelper::finalize();
}

ORBObject* IntangibleObjectHelper::instantiateObject() {
	return new IntangibleObject();
}

ORBObjectAdapter* IntangibleObjectHelper::createAdapter(ORBObjectServant* obj) {
	ORBObjectAdapter* adapter = new IntangibleObjectAdapter((IntangibleObjectImplementation*) obj);

	ORBObjectStub* stub = new IntangibleObject(obj);
	stub->_setORBClassName(className);
	stub->_setClassHelper(this);

	adapter->setStub(stub);

	obj->_setStub(stub);

	return adapter;
}

/*
 *	IntangibleObjectServant
 */

IntangibleObjectServant::IntangibleObjectServant(unsigned long long oid) : SceneObjectImplementation(oid) {
	_classHelper = IntangibleObjectHelper::instance();
}

IntangibleObjectServant::~IntangibleObjectServant() {
}

void IntangibleObjectServant::_setStub(ORBObjectStub* stub) {
	_this = (IntangibleObject*) stub;
	SceneObjectServant::_setStub(stub);
}

ORBObjectStub* IntangibleObjectServant::_getStub() {
	return _this;
}

