/*
 *	server/zone/objects/tangible/terminal/city/CityTerminal.cpp generated by engine3 IDL compiler 0.60
 */

#include "CityTerminal.h"

#include "server/zone/objects/scene/SceneObject.h"

#include "server/zone/objects/player/PlayerCreature.h"

#include "server/zone/packets/object/ObjectMenuResponse.h"

#include "server/zone/Zone.h"

#include "server/zone/objects/building/city/CityHallObject.h"


// Imported class dependencies

#include "engine/core/ManagedObject.h"

#include "engine/core/ObjectUpdateToDatabaseTask.h"

#include "engine/core/Task.h"

#include "engine/service/proto/BaseClientProxy.h"

#include "engine/service/proto/BaseMessage.h"

#include "engine/service/proto/BasePacket.h"

#include "engine/stm/TransactionalReference.h"

#include "engine/util/Facade.h"

#include "engine/util/Observable.h"

#include "engine/util/Observer.h"

#include "engine/util/ObserverEventMap.h"

#include "engine/util/u3d/Coordinate.h"

#include "engine/util/u3d/QuadTree.h"

#include "engine/util/u3d/QuadTreeEntry.h"

#include "engine/util/u3d/QuadTreeNode.h"

#include "engine/util/u3d/Quaternion.h"

#include "server/chat/StringIdChatParameter.h"

#include "server/chat/room/ChatRoom.h"

#include "server/login/account/Account.h"

#include "server/login/account/AccountManager.h"

#include "server/zone/Zone.h"

#include "server/zone/ZoneClientSession.h"

#include "server/zone/ZonePacketHandler.h"

#include "server/zone/ZoneProcessServer.h"

#include "server/zone/ZoneServer.h"

#include "server/zone/managers/city/CityManager.h"

#include "server/zone/managers/creature/CreatureManager.h"

#include "server/zone/managers/holocron/HolocronManager.h"

#include "server/zone/managers/name/NameManager.h"

#include "server/zone/managers/object/ObjectMap.h"

#include "server/zone/managers/objectcontroller/ObjectController.h"

#include "server/zone/managers/planet/HeightMap.h"

#include "server/zone/managers/planet/MapLocationTable.h"

#include "server/zone/managers/planet/PlanetManager.h"

#include "server/zone/managers/professions/ProfessionManager.h"

#include "server/zone/managers/sui/SuiManager.h"

#include "server/zone/managers/vendor/VendorManager.h"

#include "server/zone/objects/area/ActiveArea.h"

#include "server/zone/objects/building/BuildingObject.h"

#include "server/zone/objects/building/city/CityHallObject.h"

#include "server/zone/objects/cell/CellObject.h"

#include "server/zone/objects/creature/CreatureObject.h"

#include "server/zone/objects/creature/SpeedMultiplierModChanges.h"

#include "server/zone/objects/creature/buffs/Buff.h"

#include "server/zone/objects/creature/buffs/BuffList.h"

#include "server/zone/objects/creature/damageovertime/DamageOverTimeList.h"

#include "server/zone/objects/creature/professions/SkillBox.h"

#include "server/zone/objects/creature/variables/CommandQueueAction.h"

#include "server/zone/objects/creature/variables/CooldownTimerMap.h"

#include "server/zone/objects/creature/variables/SkillBoxList.h"

#include "server/zone/objects/draftschematic/DraftSchematic.h"

#include "server/zone/objects/group/GroupList.h"

#include "server/zone/objects/group/GroupObject.h"

#include "server/zone/objects/guild/GuildObject.h"

#include "server/zone/objects/installation/shuttle/ShuttleInstallation.h"

#include "server/zone/objects/intangible/ControlDevice.h"

#include "server/zone/objects/manufactureschematic/IngredientSlots.h"

#include "server/zone/objects/manufactureschematic/ManufactureSchematic.h"

#include "server/zone/objects/manufactureschematic/craftingvalues/CraftingValues.h"

#include "server/zone/objects/player/PlayerCreature.h"

#include "server/zone/objects/player/TradeContainer.h"

#include "server/zone/objects/player/ValidatedPosition.h"

#include "server/zone/objects/player/badges/Badges.h"

#include "server/zone/objects/player/events/PlayerDisconnectEvent.h"

#include "server/zone/objects/player/events/PlayerRecoveryEvent.h"

#include "server/zone/objects/player/sui/SuiBox.h"

#include "server/zone/objects/region/Region.h"

#include "server/zone/objects/scene/SceneObject.h"

#include "server/zone/objects/scene/variables/CustomizationVariables.h"

#include "server/zone/objects/scene/variables/DeltaVector.h"

#include "server/zone/objects/scene/variables/DeltaVectorMap.h"

#include "server/zone/objects/scene/variables/PendingTasksMap.h"

#include "server/zone/objects/scene/variables/StringId.h"

#include "server/zone/objects/tangible/TangibleObject.h"

#include "server/zone/objects/tangible/sign/SignObject.h"

#include "server/zone/objects/tangible/terminal/city/CityTerminal.h"

#include "server/zone/objects/tangible/terminal/city/CityVoteTerminal.h"

#include "server/zone/objects/tangible/terminal/vendor/bazaar/BazaarTerminal.h"

#include "server/zone/objects/tangible/tool/CraftingTool.h"

#include "server/zone/objects/tangible/tool/SurveyTool.h"

#include "server/zone/objects/tangible/weapon/WeaponObject.h"

#include "server/zone/packets/object/ObjectMenuResponse.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

#include "server/zone/templates/SharedObjectTemplate.h"

#include "system/io/ObjectInputStream.h"

#include "system/io/ObjectOutputStream.h"

#include "system/lang/Time.h"

#include "system/util/SortedVector.h"

#include "system/util/Vector.h"

#include "system/util/VectorMap.h"

/*
 *	CityTerminalStub
 */

enum {RPC_INITIALIZETRANSIENTMEMBERS__ = 6,RPC_FILLOBJECTMENURESPONSE__OBJECTMENURESPONSE_PLAYERCREATURE_,RPC_HANDLEOBJECTMENUSELECT__PLAYERCREATURE_BYTE_,RPC_ISCITYTERMINAL__};

CityTerminal::CityTerminal() : Terminal(DummyConstructorParameter::instance()) {
	CityTerminalImplementation* _implementation = new CityTerminalImplementation();
	ManagedObject::_setImplementation(_implementation);
	_implementation->_setStub(this);
}

CityTerminal::CityTerminal(DummyConstructorParameter* param) : Terminal(param) {
}

CityTerminal::~CityTerminal() {
}


void CityTerminal::initializeTransientMembers() {
	CityTerminalImplementation* _implementation = (CityTerminalImplementation*) _getImplementation();
	if (_implementation == NULL) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_INITIALIZETRANSIENTMEMBERS__);

		method.executeWithVoidReturn();
	} else
		_implementation->initializeTransientMembers();
}

void CityTerminal::fillObjectMenuResponse(ObjectMenuResponse* menuResponse, PlayerCreature* player) {
	CityTerminalImplementation* _implementation = (CityTerminalImplementation*) _getImplementation();
	if (_implementation == NULL) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_FILLOBJECTMENURESPONSE__OBJECTMENURESPONSE_PLAYERCREATURE_);
		method.addObjectParameter(menuResponse);
		method.addObjectParameter(player);

		method.executeWithVoidReturn();
	} else
		_implementation->fillObjectMenuResponse(menuResponse, player);
}

int CityTerminal::handleObjectMenuSelect(PlayerCreature* player, byte selectedID) {
	CityTerminalImplementation* _implementation = (CityTerminalImplementation*) _getImplementation();
	if (_implementation == NULL) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_HANDLEOBJECTMENUSELECT__PLAYERCREATURE_BYTE_);
		method.addObjectParameter(player);
		method.addByteParameter(selectedID);

		return method.executeWithSignedIntReturn();
	} else
		return _implementation->handleObjectMenuSelect(player, selectedID);
}

bool CityTerminal::isCityTerminal() {
	CityTerminalImplementation* _implementation = (CityTerminalImplementation*) _getImplementation();
	if (_implementation == NULL) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISCITYTERMINAL__);

		return method.executeWithBooleanReturn();
	} else
		return _implementation->isCityTerminal();
}

DistributedObjectServant* CityTerminal::_getImplementation() {

	_updated = true;
	return dynamic_cast<DistributedObjectServant*>(getForUpdate());}

void CityTerminal::_setImplementation(DistributedObjectServant* servant) {
	setObject(dynamic_cast<CityTerminalImplementation*>(servant));
}

/*
 *	CityTerminalImplementation
 */

CityTerminalImplementation::CityTerminalImplementation(DummyConstructorParameter* param) : TerminalImplementation(param) {
	_initializeImplementation();
}


CityTerminalImplementation::~CityTerminalImplementation() {
}


void CityTerminalImplementation::finalize() {
}

void CityTerminalImplementation::_initializeImplementation() {
	_setClassHelper(CityTerminalHelper::instance());

	_serializationHelperMethod();
	_serializationHelperMethod();
}

void CityTerminalImplementation::_setStub(DistributedObjectStub* stub) {
	_this = (CityTerminal*) stub;
	TerminalImplementation::_setStub(stub);
}

DistributedObjectStub* CityTerminalImplementation::_getStub() {
	return _this;
}

CityTerminalImplementation::operator const CityTerminal*() {
	return _this;
}

Object* CityTerminalImplementation::clone() {
	return dynamic_cast<Object*>(new CityTerminalImplementation(*this));
}


void CityTerminalImplementation::lock(bool doLock) {
}

void CityTerminalImplementation::lock(ManagedObject* obj) {
}

void CityTerminalImplementation::rlock(bool doLock) {
}

void CityTerminalImplementation::wlock(bool doLock) {
}

void CityTerminalImplementation::wlock(ManagedObject* obj) {
}

void CityTerminalImplementation::unlock(bool doLock) {
}

void CityTerminalImplementation::runlock(bool doLock) {
}

void CityTerminalImplementation::_serializationHelperMethod() {
	TerminalImplementation::_serializationHelperMethod();

	_setClassName("CityTerminal");

}

void CityTerminalImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		String _name;
		_name.parseFromBinaryStream(stream);

		uint16 _varSize = stream->readShort();

		int _currentOffset = stream->getOffset();

		if(CityTerminalImplementation::readObjectMember(stream, _name)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool CityTerminalImplementation::readObjectMember(ObjectInputStream* stream, const String& _name) {
	if (TerminalImplementation::readObjectMember(stream, _name))
		return true;


	return false;
}

void CityTerminalImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = CityTerminalImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int CityTerminalImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	String _name;
	int _offset;
	uint16 _totalSize;

	return 0 + TerminalImplementation::writeObjectMembers(stream);
}

CityTerminalImplementation::CityTerminalImplementation() {
	_initializeImplementation();
	// server/zone/objects/tangible/terminal/city/CityTerminal.idl():  		Logger.setLoggingName("CityTerminal");
	Logger::setLoggingName("CityTerminal");
}

void CityTerminalImplementation::initializeTransientMembers() {
	// server/zone/objects/tangible/terminal/city/CityTerminal.idl():  		super.initializeTransientMembers();
	TerminalImplementation::initializeTransientMembers();
	// server/zone/objects/tangible/terminal/city/CityTerminal.idl():  		Logger.setLoggingName("CityTerminal");
	Logger::setLoggingName("CityTerminal");
}

bool CityTerminalImplementation::isCityTerminal() {
	// server/zone/objects/tangible/terminal/city/CityTerminal.idl():  		return true;
	return true;
}

/*
 *	CityTerminalAdapter
 */

CityTerminalAdapter::CityTerminalAdapter(CityTerminalImplementation* obj) : TerminalAdapter(obj) {
}

Packet* CityTerminalAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	Packet* resp = new MethodReturnMessage(0);

	switch (methid) {
	case RPC_INITIALIZETRANSIENTMEMBERS__:
		initializeTransientMembers();
		break;
	case RPC_FILLOBJECTMENURESPONSE__OBJECTMENURESPONSE_PLAYERCREATURE_:
		fillObjectMenuResponse((ObjectMenuResponse*) inv->getObjectParameter(), (PlayerCreature*) inv->getObjectParameter());
		break;
	case RPC_HANDLEOBJECTMENUSELECT__PLAYERCREATURE_BYTE_:
		resp->insertSignedInt(handleObjectMenuSelect((PlayerCreature*) inv->getObjectParameter(), inv->getByteParameter()));
		break;
	case RPC_ISCITYTERMINAL__:
		resp->insertBoolean(isCityTerminal());
		break;
	default:
		return NULL;
	}

	return resp;
}

void CityTerminalAdapter::initializeTransientMembers() {
	((CityTerminalImplementation*) impl)->initializeTransientMembers();
}

void CityTerminalAdapter::fillObjectMenuResponse(ObjectMenuResponse* menuResponse, PlayerCreature* player) {
	((CityTerminalImplementation*) impl)->fillObjectMenuResponse(menuResponse, player);
}

int CityTerminalAdapter::handleObjectMenuSelect(PlayerCreature* player, byte selectedID) {
	return ((CityTerminalImplementation*) impl)->handleObjectMenuSelect(player, selectedID);
}

bool CityTerminalAdapter::isCityTerminal() {
	return ((CityTerminalImplementation*) impl)->isCityTerminal();
}

/*
 *	CityTerminalHelper
 */

CityTerminalHelper* CityTerminalHelper::staticInitializer = CityTerminalHelper::instance();

CityTerminalHelper::CityTerminalHelper() {
	className = "CityTerminal";

	Core::getObjectBroker()->registerClass(className, this);
}

void CityTerminalHelper::finalizeHelper() {
	CityTerminalHelper::finalize();
}

DistributedObject* CityTerminalHelper::instantiateObject() {
	return new CityTerminal(DummyConstructorParameter::instance());
}

DistributedObjectServant* CityTerminalHelper::instantiateServant() {
	return new CityTerminalImplementation(DummyConstructorParameter::instance());
}

DistributedObjectAdapter* CityTerminalHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new CityTerminalAdapter((CityTerminalImplementation*) obj->_getImplementation());

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

