/*
Copyright (C) 2007 <SWGEmu>
 
This File is part of Core3.
 
This program is free software; you can redistribute 
it and/or modify it under the terms of the GNU Lesser 
General Public License as published by the Free Software
Foundation; either version 2 of the License, 
or (at your option) any later version.
 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
See the GNU Lesser General Public License for
more details.
 
You should have received a copy of the GNU Lesser General 
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 
Linking Engine3 statically or dynamically with other modules 
is making a combined work based on Engine3. 
Thus, the terms and conditions of the GNU Lesser General Public License 
cover the whole combination.
 
In addition, as a special exception, the copyright holders of Engine3 
give you permission to combine Engine3 program with free software 
programs or libraries that are released under the GNU LGPL and with 
code included in the standard release of Core3 under the GNU LGPL 
license (or modified versions of such code, with unchanged license). 
You may copy and distribute such a system following the terms of the 
GNU LGPL for Engine3 and the licenses of the other code concerned, 
provided that you include the source code of that other code when 
and as the GNU LGPL requires distribution of source code.
 
Note that people who make modified versions of Engine3 are not obligated 
to grant this special exception for their modified versions; 
it is their choice whether to do so. The GNU Lesser General Public License 
gives permission to release a modified version without this exception; 
this exception also makes it possible to release a modified version 
which carries forward this exception.
*/

package server.zone.objects.building;

import server.zone.objects.tangible.TangibleObject;
import engine.lua.LuaObject;
import engine.util.QuadTree;
import engine.util.QuadTreeEntry;
import server.zone.objects.cell.CellObject;
import system.util.SortedVector;
import system.util.Vector;
import server.zone.objects.scene.SceneObject;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.player.PlayerCreature;
import server.zone.objects.tangible.sign.SignObject;
import server.zone.objects.tangible.terminal.structure.StructureTerminal;
import server.zone.ZoneServer;
import server.zone.Zone;
import server.zone.templates.SharedObjectTemplate;
include server.zone.objects.building.StructurePermissionList;

class BuildingObject extends TangibleObject implements QuadTree {
	@dereferenced
	protected Vector<CellObject> cells;
	
	@dereferenced
	protected StructurePermissionList structurePermissionList;
	
	protected StructureTerminal structureTerminal;

	protected unsigned long ownerObjectID;
	
	protected int totalCellNumber;
	
	protected SignObject signObject;
	
	protected int lotSize;
	
	protected unsigned long deedObjectID;
	
	protected int baseMaintenanceRate;
	protected unsigned int surplusMaintenance;
	
	protected int accessFee;
	
	protected boolean publicStructure;
	
	//TODO: This should probably be handled differently...
	protected boolean declaredResidency;
	
	public BuildingObject() {
		Logger.setLoggingName("BuildingObject");

		QuadTree.setSize(-1024, -1024, 1024, 1024);

		super.staticObject = false;
		
		super.containerVolumeLimit = 0xFFFFFFFF;

		super.containerType = 2;
		
		totalCellNumber = 0;
		
		lotSize = 0;
		
		baseMaintenanceRate = 0;
		
		surplusMaintenance = 0;
		
		deedObjectID = 0;
		
		accessFee = 0;
		
		publicStructure = false;
		
		declaredResidency = false;
	}
	
	public native void createChildObjects();
	
	public void createCellObjects() {
		for (int i = 0; i < totalCellNumber; ++i) {
			SceneObject newCell = getZoneServer().createObject(2906855187, 2);

			addCell((CellObject)newCell);
		}
		
		updateToDatabase();
	}
	
	@local
	public native void loadTemplateData(SharedObjectTemplate templateData);
		
	public native void initializeTransientMembers();
	
	/**
	 * Sends the contained non slotted objects to the specified player
	 * @pre { this object is locked }
	 * @post { this object is locked, player received the container objects }
	 * @param player SceneObject that will receive the objects 
	 */
	public native void sendContainerObjectsTo(SceneObject player);
	
	public native void handleStructureStatus(PlayerCreature player);
	public native void handleStructureDestroyRequest(PlayerCreature player);
	public native void handleStructureDestroyConfirm(PlayerCreature player, boolean confirm);
	public native void handlePayMaintenance(PlayerCreature player);
	public native void handlePrivacyChange(PlayerCreature player);
	public native void handleDeclareResidency(PlayerCreature player);
	public native void handleSetObjectName(PlayerCreature player);
	
	/**
	 * Gets called when the structure has been created;
	 */
	public abstract int notifyStructurePlaced(PlayerCreature player) {
		return 0;
	}
	
	public abstract boolean checkRequisitesForPlacement(PlayerCreature player) {
		return true;
	}
	
	public native void removeFromZone();/* {
		for (int i = 0; i < cells.size(); ++i) {
			CellObject cell = cells.get(i);
			
			while (cell.getContainerObjectsSize() > 0) {
				SceneObject obj = cell.getContainerObject(0);
				
				obj.removeFromZone();
				
			}
		}
		
		super.removeFromZone();
	}*/
	
	@local
	public native void notifyInsert(QuadTreeEntry obj);
	
	@local
	public native void notifyDissapear(QuadTreeEntry obj);

	public native void notifyInsertToZone(SceneObject object);
	
	@local
	public native void insert(QuadTreeEntry obj);
	
	@local
	public native void remove(QuadTreeEntry obj);
	
	@local
	public native void update(QuadTreeEntry obj);
	
	@local
	public native void inRange(QuadTreeEntry obj, float range);
	
	public native void sendTo(SceneObject player, boolean doClose);
	public native void sendBaselinesTo(SceneObject player);
	public native void sendDestroyTo(SceneObject player);
	
	public native void addCell(CellObject cell);
	
	public boolean isStaticBuilding() {
		return super.staticObject;
	}
	
	public CellObject getCell(int idx) {
		return cells.get(idx);
	}
	
	public int getTotalCellNumber() {
		return totalCellNumber;
	}
	
	public void setLotSize(int lotsize) {
		lotSize = lotsize;
	}
	
	public int getLotSize() {
		return lotSize;
	}
	
	public void setStaticBuilding(boolean value) {
		super.staticObject = value;
	}
	
	/**
	 * Abstract function that is triggered when a player enters a building.
	 * This function should only be called from PlayerCreature::insertToBuilding.
	 * Overloaded functions must meet the post conditions for this function.
	 * @pre { player is locked, zone is locked }
	 * @post { player is locked, zone is locked }
	 * @param player PlayerCreature that entered the building
	 */
	public abstract void onEnter(PlayerCreature player) { 

	}
	
	/**
	 * Abstract function that is triggered when a player exits a building.
	 * This function should only be called from PlayerCreature::removeFromBuilding.
	 * Overloaded functions must meet the post conditions for this function.
	 * @pre { player is locked, zone is locked }
	 * @post { player is locked, zone is locked }
	 * @param player PlayerCreature that exited the building
	 */
	public abstract void onExit(PlayerCreature player) {
		
	}
	
	public boolean isBuildingObject() {
		return true;
	}
	
	public abstract boolean isMedicalBuildingObject() {
		return false;
	}
	
	public void setDeedObjectID(unsigned long deedid) {
		deedObjectID = deedid;
	}
	
	public unsigned long getDeedObjectID() {
		return deedObjectID;
	}
	
	public void setOwnerObjectID(unsigned long ownerID) {
		ownerObjectID = ownerID;
		structurePermissionList.grantPermission(ownerID, StructurePermissionList.OWNER);
	}
	
	public unsigned long getOwnerObjectID() {
		return ownerObjectID;
	}
	
	public void setSignObject(SignObject sign) {
		signObject = sign;
	}
	
	public SignObject getSignObject() {
		return signObject;
	}
	
	public void setSurplusMaintenance (unsigned int maintenance) {
		surplusMaintenance = maintenance;
	}
	
	public unsigned int getSurplusMaintenance() {
		return surplusMaintenance;
	}
	
	/**
	 * Sets the base maintenance rate for this building. This is the rate before any bonuses are applied.
	 * @param maintenanceRate The new maintenance rate to set for this building.
	 */
	public void setBaseMaintenanceRate(int maintenanceRate) {
		baseMaintenanceRate = maintenanceRate;
	}
	
	/**
	 * Returns the base maintenance rate for the building.
	 * This value is the rate before any bonuses from the merchant skills are added.
	 * @return The base maintenance rate for the building.
	 */
	public int getBaseMaintenanceRate() {
		return baseMaintenanceRate;
	}
	
	/**
	 * Returns the cost to redeed this building. The redeed cost is 50 times the hourly maintenance rate.
	 * @return The cost to redeed this building.
	 */
	public int getRedeedCost() {
		return baseMaintenanceRate * 50;
	}
	
	public abstract boolean isCityHallBuilding() {
		return false;
	}
	
	/**
	 * Returns if the creature is on the admin list or not for this structure.
	 * @param creature The creature to check for admin permissions on.
	 * @return boolean True if the creature is on the admin list.
	 */
	public boolean isOnAdminList(CreatureObject creature) {
		return structurePermissionList.isOnAdminList(creature.getObjectID());
	}
	
	public void sendPermissionListTo(PlayerCreature player, final string listName) {
		structurePermissionList.sendTo(player, listName);
	}
	
	public boolean isPublicStructure() {
		return publicStructure;
	}
	
	public void setPublicStructure(boolean value) {
		publicStructure = value;
	}
	
	public boolean isDeclaredResidency() {
		return declaredResidency;
	}
	
	public void setDeclaredResidency(boolean value) {
		declaredResidency = value;
	}
}