/*
Copyright (C) 2007 <SWGEmu>
 
This File is part of Core3.
 
This program is free software; you can redistribute 
it and/or modify it under the terms of the GNU Lesser 
General Public License as published by the Free Software
Foundation; either version 2 of the License, 
or (at your option) any later version.
 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
See the GNU Lesser General Public License for
more details.
 
You should have received a copy of the GNU Lesser General 
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 
Linking Engine3 statically or dynamically with other modules 
is making a combined work based on Engine3. 
Thus, the terms and conditions of the GNU Lesser General Public License 
cover the whole combination.
 
In addition, as a special exception, the copyright holders of Engine3 
give you permission to combine Engine3 program with free software 
programs or libraries that are released under the GNU LGPL and with 
code included in the standard release of Core3 under the GNU LGPL 
license (or modified versions of such code, with unchanged license). 
You may copy and distribute such a system following the terms of the 
GNU LGPL for Engine3 and the licenses of the other code concerned, 
provided that you include the source code of that other code when 
and as the GNU LGPL requires distribution of source code.
 
Note that people who make modified versions of Engine3 are not obligated 
to grant this special exception for their modified versions; 
it is their choice whether to do so. The GNU Lesser General Public License 
gives permission to release a modified version without this exception; 
this exception also makes it possible to release a modified version 
which carries forward this exception.
*/

import "../../objects/player/Player";
import "../../objects/mission/MissionObject";
import "../../objects/tangible/TangibleObject";
import "../../objects/creature/action/ActionCreature";
import "../../objects/creature/action/Action";

import "server/zone/ZoneServer";
include "server/zone/ZoneProcessServerImplementation";

interface MissionManager {
	MissionManager(ZoneServer zs, ZoneProcessServerImplementation ps) {
		super(zs, ps);
	}
	
	void init();
	void unloadManager();
	void removeMissions();
	
	// creation methods
	MissionObject poolMission(string dbKey, int termMask, const string typeStr, unsigned int descKey, unsigned int titleKey, unsigned int diffLv, float destX, 
			float destY, unsigned int destPlanetCrc, const string creatorName, unsigned int rewardAmount, float targetX, float targetY, unsigned int targetPlanetCrc, 
			unsigned int depictedObjCrc, const string descriptionStf, const string titleStf, unsigned int typeCrc, TangibleObject deliverItem = NULL, boolean doLock = true);
	
	//Test
	void setupHardcodeMissions();
	
	//data setup
	void sendTerminalData(Player player, int termBitmask, boolean doLock = true);
	void sendMission(Player player, string tKey, boolean doLock = true);
	
	//events
	void doMissionAccept(Player player, unsigned long oid, boolean doLock = true);
	void doMissionComplete(Player player, string tKey, boolean doLock = true);
	void doMissionAbort(Player player, unsigned long oid, boolean doLock = true);
	void doMissionAbort(Player player, string tKey, boolean doLock = true);
	
	
	//Completely remove the mission from the server:
	void removeMisoFromPool(MissionObject miso, boolean doLock = true);
	
	unsigned int getMissionItemCrc(string tKey, boolean doLock = true);

	//script methods
	void loadMissionScripts();
	void registerFunctions();
	void registerGlobals();
}
