/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.tangible.deed.pet;

import server.zone.objects.tangible.deed.Deed;
import server.zone.packets.object.ObjectMenuResponse;
include server.zone.objects.manufactureschematic.craftingvalues.CraftingValues;
include server.zone.packets.scene.AttributeListMessage;
import server.zone.objects.creature.CreatureObject;
include server.zone.objects.creature.ai.variables.CreatureAttackMap;
include templates.SharedObjectTemplate;

@json
class PetDeed extends Deed {
	// dna qulity
	protected int quality;
	// Pet Level
	protected int level;
	// Crafted pets have their own attack speed and chance to hit
	protected float chanceHit;
	protected float attackSpeed;
	// Damage min/mac for the pet
	protected int damageMin;
	protected int damageMax;
	// Armor value of the pet
	protected int armor;
	// resists of the pet
	protected float kinResist;
	protected float energyResist;
	protected float blastResist;
	protected float coldResist;
	protected float heatResist;
	protected float elecResist;
	protected float acidResist;
	protected float stunResist;
	protected float saberResist;
	// ham of the pet
	protected int health;
	protected int action;
	protected int mind;
	protected int regen;
	// specials
	protected string special1;
	protected string special2;
	protected boolean ranged;

	protected string controlDeviceObjectTemplate;
	protected string mobileTemplate;

	protected int cleverness;
	protected int endurance;
	protected int fierceness;
	protected int power;
	protected int intelligence;
	protected int courage;
	protected int dependency;
	protected int dexterity;
	protected int fortitude;
	protected int hardiness;
	// sampling
	protected int sampleCount;
	protected int specialResists;

	@dereferenced
	protected CreatureAttackMap attacks;

	public PetDeed() {
		Logger.setLoggingName("PetDeed");
		damageMin = 20;
		damageMax = 20;
		armor = 0;
		kinResist = 0;
		blastResist = 0;
		coldResist = 0;
		heatResist = 0;
		elecResist = 0;
		acidResist = 0;
		stunResist = 0;
		saberResist = -1;
		health = 10;
		action = 10;
		mind = 10;
		special1 = "none";
		special2 = "none";
		ranged = false;
		chanceHit = 0;
		attackSpeed = 0;
		level = 1;
		// Source DNA of a pet deed
		cleverness = 0;
		endurance = 0;
		fierceness = 0;
		power = 0;
		intelligence = 0;
		courage = 0;
		dependency = 0;
		dexterity = 0;
		fortitude = 0;
		hardiness = 0;
		quality = 7;
		sampleCount = 0;
		specialResists = 0;
		regen = 1;
	}
	@dirty
	public native void setSpecialResist(int type);

	@read
	public native boolean isSpecialResist(int type);

	@read
	public int getSampleCount() {
		return sampleCount;
	}

	public void incrementSampleCount() {
		sampleCount += 1;
	}

	public native void initializeTransientMembers();

	@read
	@local
	public native final CreatureAttackMap getAttacks();

	@read
	public int getQuality() {
		return quality;
	}

	@read
	public int getLevel() {
		return level;
	}

	@read
	public float getAttackSpeed() {
		return attackSpeed;
	}

	@read
	public float getHitChance() {
		return chanceHit;
	}

	@read
	public int getHealth() {
		return health;
	}

	@read
	public int getAction() {
		return action;
	}

	@read
	public int getMind() {
		return mind;
	}

	@read
	public int getMinDamage() {
		return damageMin;
	}

	@read
	public int getMaxDamage() {
		return damageMax;
	}

	@read
	public float getKinetic() {
		return kinResist;
	}

	@read
	public float getEnergy() {
		return energyResist;
	}

	@read
	public float getBlast() {
		return blastResist;
	}

	@read
	public float getCold() {
		return coldResist;
	}

	@read
	public float getHeat() {
		return heatResist;
	}

	@read
	public float getElectric() {
		return elecResist;
	}

	@read
	public float getAcid() {
		return acidResist;
	}

	@read
	public float getStun() {
		return stunResist;
	}

	@read
	public float getSaber() {
		return saberResist;
	}

	@read
	public boolean getRanged() {
		return ranged;
	}

	@read
	public int getArmor() {
		return armor;
	}

	/**
	 * Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
	 * @pre { templateData is a valid pointer }
	 * @post { TangibleObject members are initialized }
	 * @param templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
	 */
	@local
	public native void loadTemplateData(SharedObjectTemplate templateData);

	@local
	@dirty
	public native void fillAttributeList(AttributeListMessage alm, CreatureObject object);

	@local
	@dirty
	public native void fillObjectMenuResponse(ObjectMenuResponse menuResponse, CreatureObject player);

	/**
	 * Handles the radial selection sent by the client
	 * @pre { this object is locked, player is locked }
	 * @post { this object is locked, player is locked }
	 * @returns 0 if successfull
	 */
	@preLocked
	@arg1preLocked
	public native int handleObjectMenuSelect(CreatureObject player, byte selectedID);

	@local
	public native void updateCraftingValues(CraftingValues values, boolean firstUpdate);

	@dirty
	public boolean isPetDeedObject() {
		return true;
	}

	@read
	public string getSpecial1() {
		return special1;
	}

	@read
	public string getSpecial2() {
		return special2;
	}

	@read
	public int getCleverness() {
		return cleverness;
	}

	@read
	public int getEndurance() {
		return endurance;
	}

	@read
	public int getFierceness() {
		return fierceness;
	}

	@read
	public int getPower() {
		return power;
	}

	@read
	public int getIntelligence() {
		return intelligence;
	}

	@read
	public int getCourage() {
		return courage;
	}

	@read
	public int getDependency() {
		return dependency;
	}

	@read
	public int getDexterity() {
		return dexterity;
	}

	@read
	public int getFortitude() {
		return fortitude;
	}

	@read
	public int getHardiness() {
		return hardiness;
	}

	@read
	@local
	public native string getTemplateName();

	/**
	 * Setup attack map during initialize
	 */
	@local
	public native void setupAttacks();

	@local
	public native int calculatePetLevel();

	@local
	public native void adjustPetLevel(CreatureObject player, CreatureObject pet);
	@local
	public native boolean adjustPetStats(CreatureObject player, CreatureObject pet);
}
