/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.tangible.misc;

import server.zone.objects.tangible.TangibleObject;
import server.zone.objects.scene.SceneObject;
import server.zone.Zone;
import engine.lua.LuaObject;
import server.zone.packets.scene.AttributeListMessage;
import server.zone.objects.creature.CreatureObject;
import server.zone.ZoneServer;

@lua
class CustomIngredient extends TangibleObject {
	@dereferenced
	protected VectorMap<string, int> objectAttributes;

	public CustomIngredient() {
		objectAttributes.setAllowOverwriteInsertPlan();
		setLoggingName("CustomIngredient");
	}
	
	/**
	 * Fills the attribute list message options that are sent to player creature
	 * @pre { }
	 * @post { }
	 * @param msg attribute list message with the attributes
	 * @param object player creature to which the message is sent
	 */
	@local
	@dirty
	public native void fillAttributeList(AttributeListMessage msg, CreatureObject object);

	@preLocked
	public native void addAttribute(final string attribute, int value);

	@local
	@dirty
	public native int getAttributeAndValue(string attribute, int index);

	@dirty
	public int getAttributeValue(int index) {
		return objectAttributes.get(index);
	}

	@dirty
	public native int getValueOf(int index);

	@dirty
	public native int getValueOf(final string attribute);

	@dirty
	public boolean isCustomIngredient() {
		return true;
	}
}
