/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.tangible.fspuzzlepack;

import server.zone.objects.tangible.TangibleObject;
import server.zone.packets.scene.AttributeListMessage;
import server.zone.objects.creature.CreatureObject;
import system.lang.String;
include server.zone.objects.manufactureschematic.craftingvalues.CraftingValues;

@lua
class FsPuzzlePack extends TangibleObject {
	protected int cureSymptomOne;
	protected int cureSymptomTwo;
	protected int giveSymptomOne;

	public FsPuzzlePack() {
		setLoggingName("FsPuzzlePack");
		
		cureSymptomOne = -1;
		cureSymptomTwo = -1;
		giveSymptomOne = -1;
	}
	
	@local
	public void updateCraftingValues(CraftingValues values, boolean firstUpdate) {
		cureSymptomOne = (int)values.getCurrentValue("curesymptomone");
		cureSymptomTwo = (int)values.getCurrentValue("curesymptomtwo");
		giveSymptomOne = (int)values.getCurrentValue("givesymptomone");

		if (cureSymptomOne == cureSymptomTwo)
			cureSymptomTwo = -1;

		if (giveSymptomOne == cureSymptomOne || giveSymptomOne == cureSymptomTwo)
			giveSymptomOne = -1;
	}
	
	/**
	 * Fills the attribute list message options that are sent to player creature
	 * @pre { }
	 * @post { }
	 * @param msg attribute list message with the attributes
	 * @param object player creature to which the message is sent
	 */
	@local
	@dirty
	public void fillAttributeList(AttributeListMessage msg, CreatureObject object) {
		super.fillAttributeList(msg, object);

		msg.insertAttribute("fs_medic_pack_cure_one", "@quest/force_sensitive/fs_medic:symptom" + String.valueOf(cureSymptomOne));

		if (cureSymptomTwo >= 0)
			msg.insertAttribute("fs_medic_pack_cure_two", "@quest/force_sensitive/fs_medic:symptom" + String.valueOf(cureSymptomTwo));
		
		if (giveSymptomOne >= 0)
			msg.insertAttribute("fs_medic_pack_symptom_one", "@quest/force_sensitive/fs_medic:symptom" + String.valueOf(giveSymptomOne));
	}
	
	/**
	 * Handles the radial selection sent by the client, must be overriden by inherited objects
	 * @pre { this object is locked, player is locked }
	 * @post { this object is locked, player is locked }
	 * @param player CreatureObject that selected the option
	 * @param selectedID selected menu id
	 * @returns 0 if successfull
	 */
	public int handleObjectMenuSelect(CreatureObject player, byte selectedID) {
		if (!isASubChildOf(player))
			return 0;
		
		return 1;
	}

	@dirty
	public int getCureSymptomOne() {
		return cureSymptomOne;
	}

	@dirty
	public int getCureSymptomTwo() {
		return cureSymptomTwo;
	}

	@dirty
	public int getGiveSymptomOne() {
		return giveSymptomOne;
	}

	@dirty
	public boolean isFsPuzzlePack() {
		return true;
	}
}
