/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.tangible.misc;

import server.zone.objects.tangible.TangibleObject;
import server.zone.objects.scene.SceneObject;
import server.zone.Zone;
import server.zone.packets.scene.AttributeListMessage;
import server.zone.ZoneServer;
include templates.SharedObjectTemplate;

import server.zone.objects.creature.CreatureObject;

@lua
@json
class SchematicFragment extends TangibleObject {
	protected unsigned int targetSchematic;
	protected int totalFragments;
	protected unsigned int fragmentBitmask;

	public SchematicFragment() {
		setLoggingName("SchematicFragment");

		initializeMembers();
	}

	@dirty
	public void initializeMembers() {
		targetSchematic = 0;
		totalFragments = 0;
		fragmentBitmask = 0;
	}

	/**
	 * Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
	 * @pre { templateData is a valid pointer }
	 * @post { TangibleObject members are initialized }
	 * @param templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
	 */
	@local
	@dirty
	public native void loadTemplateData(SharedObjectTemplate templateData);

	@read
	@local
	public native int getTotalFragments() {
		return totalFragments;
	}

	@read
	@local
	public native unsigned int getFragmentBitmask() {
		return fragmentBitmask;
	}

	@dirty
	public native unsigned int getTargetSchematic() {
		return targetSchematic;
	}

	@dirty
	public boolean isSchematicFragmentObject() {
		return true;
	}
}
