/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.player.sui.transferbox;

import engine.lua.LuaObject;
import server.zone.objects.scene.SceneObject;
import server.zone.objects.creature.CreatureObject;
import engine.service.proto.BaseMessage;
import server.zone.objects.player.sui.SuiBox;
import server.zone.objects.player.sui.transferbox.SuiTransferBox;
include server.zone.packets.ui.SuiCreatePageMessage;
import server.zone.objects.creature.CreatureObject;

class SuiFireworkDelayBox extends SuiTransferBox {

	protected unsigned int fireworkIndex;

	public SuiFireworkDelayBox(CreatureObject player, unsigned int windowType, unsigned int index) {
		super(player, windowType);
		fireworkIndex = index;
	}

	public unsigned int getFireworkIndex() {
		return fireworkIndex;
	}

	public boolean isFireworkDelayBox() {
		return true;
	}
}
