/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.objects.ship.ai;

import server.zone.objects.ship.ShipObject;
import server.zone.objects.ship.ai.ShipAiAgent;
import server.zone.objects.scene.SceneObject;
import engine.log.Logger;

@json
class CapitalShipObject extends ShipAiAgent {

	public CapitalShipObject() {
		Logger.setLoggingName("CapitalShipObject");
		Logger.setLogging(false);
		Logger.setGlobalLogging(true);
	}

	@dirty
	public native abstract float getOutOfRangeDistance(unsigned long specialRangeObjectID = 0);
}
