/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions. */

package server.zone.objects.installation;

import engine.util.Observer;
import engine.util.Observable;
import engine.log.Logger;
import engine.core.ManagedObject;

include engine.log.Logger;

class TurretObserver extends Observer implements Logger {
	
	public TurretObserver() {
		Logger.setLoggingName("TurretObserver");
	}

	public abstract native int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);
	
}
