/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions. */

package server.zone.objects.player;

include engine.core.ManagedObject;
import engine.util.Observer;
import engine.util.Observable;
import server.zone.objects.creature.CreatureObject;
include templates.params.ObserverEventType;

class EntertainingObserver extends Observer {
	
	public EntertainingObserver() {
		;
	}

	@dirty
	public int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2) {
		if (eventType != ObserverEventType.POSTURECHANGED) {
			return 0;
		}
		
		CreatureObject creature = (CreatureObject) observable;
		creature.stopEntertaining();
		
		return 1;
	}

}
