/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.player.sui.characterbuilderbox;

import server.zone.objects.creature.CreatureObject;
import server.zone.objects.player.sui.listbox.SuiListBox;

include server.zone.objects.tangible.terminal.characterbuilder.CharacterBuilderMenuNode;
import server.zone.objects.creature.CreatureObject;

class SuiCharacterBuilderBox extends SuiListBox {
	protected transient CharacterBuilderMenuNode rootNode;
	protected transient CharacterBuilderMenuNode currentNode;
	
	public SuiCharacterBuilderBox(CreatureObject player, CharacterBuilderMenuNode root) {
		super(player, SuiWindowType.CHARACTER_BUILDER_LIST, SuiListBox.HANDLETHREEBUTTON);
		
		Logger.setLoggingName("SuiCharacterBuilderBox");
		
		setPromptTitle("Character Builder");
		
		setPromptText("Provided below are items which the developers feel are necessary to complete the current testing objectives. Please select only the items which you require.");
		
		rootNode = root;
		
		currentNode = root;
	}
	
	public native BaseMessage generateMessage();
	
	@local
	public native CharacterBuilderMenuNode getCurrentNode();
	
	@local
	public native void setCurrentNode(CharacterBuilderMenuNode node);
	
	public boolean isCharacterBuilderBox() {
		return true;
	}
}
