/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.mission;

import server.zone.objects.mission.DeliverMissionObjective;
import server.zone.objects.mission.MissionObject;
import server.zone.objects.creature.CreatureObject;

class CraftingMissionObjective extends DeliverMissionObjective {
	public CraftingMissionObjective(MissionObject mission) {
		super(mission);
		
		Logger.setLoggingName("CraftingMissionObjective");
	}
	
	public native void finalize() {
		//Logger.info("deleting from memory", true);
	}
	
	public void initializeTransientMembers() {
		super.initializeTransientMembers();
		
		Logger.setLoggingName("CraftingMissionObjective");
	}
	
	public abstract native void updateMissionStatus(CreatureObject player);
	public abstract native void abort();
}
