/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.mission;

import engine.util.Observer;
import engine.util.Observable;
import server.zone.objects.mission.MissionObject;
import server.zone.objects.mission.MissionObjective;
import server.zone.objects.mission.MissionObserver;
import server.zone.objects.scene.SceneObject;
include server.zone.templates.TemplateReference;
import server.zone.templates.SharedObjectTemplate;
import server.zone.objects.area.MissionSpawnActiveArea;
import server.zone.templates.mobile.LairTemplate;
import server.zone.objects.tangible.LairObject;
import server.zone.Zone;

class DestroyMissionObjective extends MissionObjective {
	@dereferenced
	protected string lairTemplate;
	
	protected MissionSpawnActiveArea spawnActiveArea;
	
	protected LairObject lairObject;

	int difficultyLevel;
	int difficulty;
	
	public DestroyMissionObjective(MissionObject mission) {
		super(mission);

		difficultyLevel = 0;
		difficulty = 2;

		Logger.setLoggingName("DestroyMissionObjective");
	}
	
	public native void finalize() {
		//Logger.info("deleting from memory", true);
	}
	
	public void initializeTransientMembers() {
		super.initializeTransientMembers();
		
		Logger.setLoggingName("DestroyMissionObjective");
	}
	
	public native void activate();
	public native void abort();
	public native void complete();
	
	public native void spawnLair();
	
	/**
	 * Destroys this object from database
	 * @pre { this is locked }
	 * @post { this is locked }
	 */
	public native void destroyObjectFromDatabase();
	
	@local
	@dereferenced
	@dirty
	public native Vector3 findValidSpawnPosition(Zone zone);
	
	public native int notifyObserverEvent(MissionObserver observer, unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);
	
	@local
	public native void setLairTemplateToSpawn(final string sp);

	public void setDifficultyLevel(int diff) {
		difficultyLevel = diff;
	}

	public void setDifficulty(int diff) {
		difficulty = diff;
	}

	@dereferenced
	@local
	@dirty
	public native Vector3 getEndPosition();
}
