/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.mission;

import engine.util.Observer;
import engine.util.Observable;
import server.zone.objects.mission.MissionObjective;
import engine.log.Logger;

import engine.core.ManagedObject;
include engine.log.Logger;
include engine.util.u3d.Vector3;

class MissionObserver extends Observer implements Logger {
	@weakReference
	protected MissionObjective missionObjective;

	public MissionObserver(MissionObjective objective) {
		missionObjective = objective;

		Logger.setLoggingName("MissionObserver");
	}

	public abstract native int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);

	/**
	 * Destroys this object from database
	 * @pre { this is locked }
	 * @post { this is locked }
	 */
	@preLocked
	public abstract native void destroyObjectFromDatabase();
}
