/*
Copyright (C) 2007 <SWGEmu>
 
This File is part of Core3.
 
This program is free software; you can redistribute 
it and/or modify it under the terms of the GNU Lesser 
General Public License as published by the Free Software
Foundation; either version 2 of the License, 
or (at your option) any later version.
 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
See the GNU Lesser General Public License for
more details.
 
You should have received a copy of the GNU Lesser General 
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 
Linking Engine3 statically or dynamically with other modules 
is making a combined work based on Engine3. 
Thus, the terms and conditions of the GNU Lesser General Public License 
cover the whole combination.
 
In addition, as a special exception, the copyright holders of Engine3 
give you permission to combine Engine3 program with free software 
programs or libraries that are released under the GNU LGPL and with 
code included in the standard release of Core3 under the GNU LGPL 
license (or modified versions of such code, with unchanged license). 
You may copy and distribute such a system following the terms of the 
GNU LGPL for Engine3 and the licenses of the other code concerned, 
provided that you include the source code of that other code when 
and as the GNU LGPL requires distribution of source code.
 
Note that people who make modified versions of Engine3 are not obligated 
to grant this special exception for their modified versions; 
it is their choice whether to do so. The GNU Lesser General Public License 
gives permission to release a modified version without this exception; 
this exception also makes it possible to release a modified version 
which carries forward this exception.
*/

package server.zone.objects.mission;

import engine.util.Observer;
import engine.util.Observable;
import server.zone.objects.mission.MissionObject;
import server.zone.objects.mission.MissionObserver;
import server.zone.objects.scene.SceneObject;
import system.util.SortedVector;
import server.zone.objects.creature.CreatureObject;
import engine.log.Logger;
import engine.core.ManagedObject;
import server.zone.objects.mission.events.FailMissionAfterCertainTimeTask;
import engine.util.u3d.Vector3;

class MissionObjective extends ManagedObject implements Logger {
	@dereferenced
	private SortedVector<MissionObserver> observers;
	
	@weakReference
	protected MissionObject mission;
	
	protected unsigned int objectiveType;
	
	@dereferenced
	protected Time missionStartTime;
	
	protected FailMissionAfterCertainTimeTask failTask;
	
	protected unsigned long timeRemaining;

	public MissionObjective(MissionObject parent) {
		mission = parent;
		
		Logger.setLoggingName("MissionObjective");
		
		//Default time remaining 2 days.
		timeRemaining = 48 * 60 * 60 * 1000;
		
		missionStartTime.updateToCurrentTime();
	}
	
	/**
	 * Destroys this object from database
	 * @pre { this is locked }
	 * @post { this is locked }
	 */
	public abstract native void destroyObjectFromDatabase();
	
	public abstract int notifyObserverEvent(MissionObserver observer, unsigned int eventType, Observable observable, ManagedObject arg1, long arg2) {
		return 1;
	}
	
	public native void addObserver(MissionObserver observer, boolean makePersistent);
	
	public void dropObserver(MissionObserver observer, boolean removeFromDatabase) {
		if (removeFromDatabase)
			observer.destroyObjectFromDatabase();
		
		observers.drop(observer);
	}
	
	public int getObserverCount() {
		return observers.size();
	}
	
	public void removeAllObservers() {
		observers.removeAll();
	}
	
	public MissionObserver getObserver(int index) {
		return observers.get(index);
	}
	
	public boolean hasObservers() {
		return observers.size() != 0;
	}
	
	public native abstract void activate();
	
	public native abstract void abort();

	public native abstract void complete();
	public native abstract void fail();
	
	@weakReference
	public MissionObject getMissionObject() {
		return mission;
	}
	
	public unsigned int getObjectiveType() {
		return objectiveType;
	}
	
	@weakReference
	public native CreatureObject getPlayerOwner();
	
	public native void awardFactionPoints();
	
	public native void removeMissionFromPlayer();
	
	public native void awardReward();
	
	@dereferenced
	@local
	public abstract native Vector3 getEndPosition();
}
