/*
 * SessionFacadeTypes.h
 *
 *  Created on: 22/09/2010
 *      Author: victor
 */

#ifndef SESSIONFACADETYPE_H_
#define SESSIONFACADETYPE_H_

class SessionFacadeType {
public:

	enum {
		ENTERTAINING = 1,
		MIGRATESTATS = 2,
		IMAGEDESIGN = 3,
		SLICING = 4,
		CREATEVENDOR = 5,
		PLACESTRUCTURE = 6,
		DESTROYSTRUCTURE = 7,
		FIND = 8,
		CONVERSATION = 9,
		CITYSPEC = 10,
		CITYWITHDRAW = 11,
		CITYMILITIA = 12,
		FISHING = 13,
		TRADE = 14,
		PLAYERTEACH = 15,
		CRAFTING = 16,
		PLAYERMANAGEMENT = 17,
		SURVEY = 18,
		SETSTRUCTUREACCESSFEE = 19,
		VENDORADBARKING = 20,
		PROPOSEUNITY = 21,
		VETERANREWARD = 22,
		INTERPLANETARYSURVEYDROID = 23,
		DROIDMAINTENANCERUN = 24,
		LOOTLOTTERY = 25,
		CONTRABANDSCAN = 26,
	};

};

#endif /* SESSIONFACADETYPES_H_ */
