/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.building.tutorial;

import server.zone.objects.building.BuildingObject;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.building.tutorial.events.UnloadBuildingTask;

class TutorialBuildingObject extends BuildingObject {

	protected transient UnloadBuildingTask unloadTask;

	public TutorialBuildingObject() {
		unloadTask = null;

		Logger.setLoggingName("TutorialBuildingObject");
	}

	public native void notifyRemoveFromZone();

	public void initializeTransientMembers() {
		super.initializeTransientMembers();

		unloadTask = null;

		Logger.setLoggingName("TutorialBuildingObject");
	}

	public void onEnter(CreatureObject player) {
		if (player.isPlayerCreature())
			dequeueUnloadEvent();
	}

	public void onExit(CreatureObject player) {
		if (player.isPlayerCreature())
			enqueueUnloadEvent();
	}

	@preLocked
	public void clearUnloadEvent() {
		unloadTask = null;
	}

	protected void dequeueUnloadEvent() {
		if (unloadTask) {
			unloadTask.cancel();
			clearUnloadEvent();
		}
	}

	protected native void enqueueUnloadEvent();
}
