/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.creature.buffs;

import engine.core.ManagedObject;
import system.util.VectorMap;
import system.lang.ref.Reference;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.creature.CreatureObject;
import system.lang.Time;

include server.zone.ZoneProcessServer;
import server.zone.objects.creature.buffs.ChannelForceBuffDurationEvent;
import server.zone.objects.creature.buffs.Buff;
include server.zone.objects.creature.buffs.BuffType;
include server.zone.objects.creature.buffs.BuffCRC;
include server.chat.StringIdChatParameter;


class ChannelForceBuff extends Buff {
	
	protected transient ChannelForceBuffDurationEvent cfBuffEvent;

	protected int cfBonus;
	protected int cfTick;
	protected int amountOfTicks;
	protected int currentTick;
	protected int time;
	protected int hamBuffAmount;
	
	@dereferenced
	protected Time nextTickTime; 
	
	public ChannelForceBuff(CreatureObject creo, final string name, unsigned int buffCRC, int value, int duration) {
		super(creo, buffCRC, duration, BuffType.SKILL);
		
		super.buffName = name;
		cfBonus = value;
		amountOfTicks = 10;
		currentTick = 0;
		cfTick = value/amountOfTicks;
		time = duration * 1000;
		hamBuffAmount=0;
	}
	
	public native void initializeTransientMembers();

	public native void activate(boolean applyModifiers);
	
	public native void deactivate();

	public native void doHamTick();

	public native void clearBuffEvent();
}