/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

package server.zone.objects.creature.buffs;

import engine.core.ManagedObject;
import system.util.VectorMap;
import system.lang.ref.Reference;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.creature.CreatureObject;
import system.lang.Time;

include server.zone.ZoneProcessServer;
import server.zone.objects.creature.buffs.BuffDurationEvent;
import server.zone.objects.creature.buffs.Buff;
include server.zone.objects.creature.buffs.BuffType;
include server.zone.managers.object.ObjectManager;
include server.chat.StringIdChatParameter;
import server.zone.objects.tangible.consumable.DelayedBuffObserver;

class DelayedBuff extends Buff {
	protected int usesRemaining;
	protected CreatureObject player;
	protected DelayedBuffObserver observer;
	
	@dereferenced
	protected Vector<int> eventTypes;
	
	public DelayedBuff(CreatureObject creo, unsigned int buffcrc, int effectCount) {
		super(creo, buffcrc, 1380, BuffType.FOOD);
		
		usesRemaining = effectCount;
		player = creo;

	}
	
	@local
	public void init(Vector<int> events) {
		observer = new DelayedBuffObserver(this);
		ObjectManager.instance().persistObject(observer, 1, "buffs");
		
		for(int i = 0; i < events.size(); ++i) {
			eventTypes.add(events.get(i));
		}
	}
	
	//Duration buffs don't apply the modifiers to the creature. They are referenced when used.
	public void activate() {
		super.activate(false);
		addObservers();
	}
	
	public void deactivate() {
		super.deactivate(false);
		dropObservers();
	}
	
	public void useCharge() {
		usesRemaining = usesRemaining - 1;
		
		player.sendAttributeListTo(player);
		
		if (usesRemaining < 1) {
			player.removeBuff(this);
		}
	}

	public void setUsesRemaining(int uses) {
		usesRemaining = uses;
		
		player.sendAttributeListTo(player);
		
		if (usesRemaining < 1) {
			player.removeBuff(this);
		}
	}
	
	private void addObservers() {
		for(int i = 0; i < eventTypes.size(); ++i) {
			player.registerObserver(eventTypes.get(i), observer);
		}
	}
	
	private void dropObservers() {
		for(int i = 0; i < eventTypes.size(); ++i) {
			player.dropObserver(eventTypes.get(i), observer);
		}
	}
}
