/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.creature.buffs;

import engine.core.ManagedObject;
import server.zone.objects.creature.buffs.PlayerVehicleBuff;
import server.zone.objects.creature.CreatureObject;
include server.zone.objects.creature.buffs.BuffType;


class GallopBuff extends PlayerVehicleBuff {
	public GallopBuff(CreatureObject creo, unsigned int buffcrc, float duration) {
		super(creo, buffcrc, duration, BuffType.SKILL);
	}

	public void activate(boolean applyModifiers) {
		super.activate(true);

		CreatureObject rider = super.creature.getSlottedObject("rider").asCreatureObject();
		if(rider != null)
			rider.removeMountedCombatSlow();
	}

	public void deactivate(boolean applyModifiers) {
		super.deactivate(true);

		CreatureObject rider = super.creature.getSlottedObject("rider").asCreatureObject();
		if(rider != null)
			rider.addMountedCombatSlow();
	}

}
