/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.creature.buffs;

import server.zone.objects.creature.buffs.PlayerVehicleBuff;
import server.zone.objects.creature.CreatureObject;
include server.zone.objects.creature.buffs.BuffType;
import server.zone.objects.scene.SceneObject;

class GallopBuff extends PlayerVehicleBuff {
	public GallopBuff(CreatureObject creo, unsigned int buffcrc, float duration) {
		super(creo, buffcrc, duration, BuffType.SKILL);
	}

	public void activate(boolean applyModifiers) {
		super.activate(true);
	
		SceneObject rider = super.creature.getSlottedObject("rider");
		if(rider == null)
			return;
	
		CreatureObject creo = rider.asCreatureObject();
		if(creo != null)
			creo.removeMountedCombatSlow();
	}

	public void deactivate(boolean applyModifiers) {
		super.deactivate(true);

		SceneObject rider = super.creature.getSlottedObject("rider");
		if(rider == null)
			return;
	
		CreatureObject creo = rider.asCreatureObject();
		if(creo != null)
			creo.addMountedCombatSlow();
	}
}
