/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.creature.buffs;

import server.zone.objects.creature.CreatureObject;
import server.zone.objects.creature.buffs.Buff;
include server.zone.objects.creature.buffs.BuffType;

class PerformanceBuff extends Buff {
	protected float strength;
	protected int type;

	public PerformanceBuff(CreatureObject creo, unsigned int buffCRC, float value, int duration, int typeOfBuff) {
		super(creo, buffCRC, duration, BuffType.PERFORMANCE);
		strength = value;
		type = typeOfBuff;
	}

	public native void activate(boolean applyModifiers);

	@read
	public float getBuffStrength() {
		return strength;
	}

	public native void deactivate(boolean removeModifiers);
}
