/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.creature.buffs;

import server.zone.objects.creature.CreatureObject;
import system.lang.Time;

import server.zone.objects.creature.buffs.PowerBoostBuffDurationEvent;
import server.zone.objects.creature.buffs.Buff;
include server.zone.objects.creature.buffs.BuffType;


class PowerBoostBuff extends Buff {
	protected transient PowerBoostBuffDurationEvent pbBuffEvent;

	protected int pbBonus;
	protected int pbTick;
	protected int time;
	protected int counter;
	protected int haBuffAmount;
	protected int mindBuffAmount;
	
	@dereferenced
	protected Time nextTickTime; 
	
	public PowerBoostBuff(CreatureObject creo, final string name, unsigned int buffCRC, int value, int duration) {
		super(creo, buffCRC, duration, BuffType.SKILL);
		
		super.buffName = name;
		pbBonus = value;
		pbTick = value/20;
		time = duration * 1000;
		counter = 0;
		haBuffAmount=0;
		mindBuffAmount=0;
	}
	
	public native void initializeTransientMembers();

	public native void activate(boolean applyModifiers);
	
	public native void deactivate(boolean removeModifiers);

	public native void doHealthAndActionTick(boolean up);

	public native void doMindTick(boolean up);

	public native void clearBuffEvent();

}

