/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.creature.buffs;

import server.zone.objects.creature.buffs.Buff;
import server.zone.objects.creature.CreatureObject;

// A private buff will only be appropriate if it only contains private_ skillmods and does not need
// to be sent (or can't be sent) to the player.
class PrivateBuff extends Buff {
	public PrivateBuff(CreatureObject creo, unsigned int buffcrc, float duration, int bufftype) {
		super(creo, buffcrc, duration, bufftype);
	}

	@preLocked
	public void activate(boolean applyModifiers) {
		if (applyModifiers) {
			applyAttributeModifiers();
			applySkillModifiers();
			applyStates();
		}

		scheduleBuffEvent();
	}

	@preLocked
	public void deactivate(boolean removeModifiers) {
		if (removeModifiers) {
			removeAttributeModifiers();
			removeSkillModifiers();
			removeStates();
		}

		clearBuffEvent();
	}
}
