/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions. */

package server.zone.objects.creature.buffs;

include engine.core.ManagedObject;

import engine.util.Observer;
import engine.util.Observable;
import server.zone.objects.creature.buffs.SingleUseBuff;

class SingleUseBuffObserver extends Observer {
	@weakReference
	protected SingleUseBuff buff;
	
	public SingleUseBuffObserver(SingleUseBuff b) {
		buff = b;
	}

	public native int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);
	
}
