/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.objects.creature.buffs;

import server.zone.objects.creature.buffs.Buff;
import system.lang.Long;
include server.zone.objects.creature.buffs.BuffType;
import server.zone.objects.creature.CreatureObject;

class StateBuff extends Buff {
	protected unsigned long stateApplied;

	public StateBuff(CreatureObject creo, unsigned long buffState, int duration, unsigned long secondaryCRC = 0) {
		super(creo, Long.hashCode(buffState), duration, BuffType.STATE, secondaryCRC);

		stateApplied = buffState;
	}

	@preLocked
	public void activate(boolean applyModifiers) {
		super.activate(applyModifiers);

		super.creature.setState(stateApplied);
	}

	@preLocked
	public void deactivate(boolean removeModifiers) {
		super.deactivate(removeModifiers);

		super.creature.clearState(stateApplied);
	}
}
