/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

package server.zone.objects.creature.trainer;

import engine.core.ManagedObject;
import engine.lua.LuaObject;
import system.util.Vector;
import system.lang.Time;
import server.zone.Zone;
import system.util.SortedVector;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.scene.SceneObject;

include server.zone.objects.creature.professions.Profession;
include server.zone.objects.creature.professions.ProfessionReference;

class TrainerCreature extends CreatureObject {
	@dereferenced
	protected ProfessionReference profession;

	protected int trainerID;
	protected string location;

	public TrainerCreature() {
		Logger.setLoggingName("TrainerCreature");

		profession.setProfession(null);
		trainerID = 0;
	}
	
	@local
	public void loadTemplateData(SharedObjectTemplate templateData) {
		super.loadTemplateData(templateData);
		
		super.optionsBitmask = 0x108;
		super.pvpStatusBitmask = 0;
	}
	
	public void activateRecovery() {
		
	}

	/**
	 * Sends the initial trainer NPC blurb.
	 * \param player The player to send the conversation to.
	 */
	public native void sendInitialMessage(CreatureObject player);
	/**
	 * Sends the initial trainer NPC options.
	 * \param player The player to send the conversation to.
	 */
	public native void sendInitialChoices(CreatureObject player);
	/**
	 * Sends the intial message to start the
	 * training conversation. Checks for
	 * qualificactions.
	 * \param player The player to send the conversation to (in SceneObject form).
	 */
	public native void sendConversationStartTo(SceneObject obj);
	
	/**
	 * Sends skill box options for player for training,
	 * and as such can check experience.
	 * \param player The player to send the conversation to.
	 * \param chackXp Whether or not to check experience to determine if each skillbox should be listed.
	 */
	public native void sendSkillBoxes(CreatureObject player, boolean checkXp);
	/**
	 * Sends skill boxes that the particular trainer
	 * can train, regardless of intentionor ability
	 * to learn.
	 * \param player The player to send the conversation to.
	 * \param checkLearned Whether or not you want to check if the box has been learned already.
	 */
	public native void sendSkillBoxList(CreatureObject player, boolean checkLearned);
	/**
	 * Sends the Yes/No options to the player to
	 * confirm their choice in skill acquisition.
	 * \param player The player to send the conversation to.
	 */
	public native void sendConfirmation(CreatureObject player);

	/**
	 * Handles the options that the player has selected
	 * and sets the last conversation strings to be used
	 * to determine how to parse the option selected.
	 * \param option The numerical selection the player has made (0indexed).
	 * \param obj The player to send the conversation to (in SceneObject form).
	 */
	public native void selectConversationOption(int option, SceneObject obj);

	public void setTrainerID(int id) {
		trainerID = id;
	}
	
	@local
	public void setProfession(Profession prof) {
		profession.setProfession(prof);
	}

	public int getTrainerID() {
		return trainerID;
	}

	public string getLocation() {
		return location;
	}

	public void setLocation(final string loc) {
		location = loc;
	}
	
	public boolean isTrainerCreature() {
		return true;
	}
	
	public boolean isAttackableBy(CreatureObject object) {
		return false;
	}
}
