/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.managers.gcw.observers;

import engine.core.ManagedObject;
import engine.util.Observer;
import engine.util.Observable;

include engine.log.Logger;

class ImperialChatObserver extends Observer implements Logger {

	public ImperialChatObserver() {
		super();

		Logger.setLoggingName("ImperialChatObserver");
	}

	@local
	public native int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);
}