/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.managers.gcw.observers;

import engine.core.ManagedObject;
import engine.util.Observer;
import engine.util.Observable;

include engine.log.Logger;
include server.zone.managers.gcw.tasks.ContainmentTeam;
include system.util.Vector;
include system.lang.ref.WeakReference;

class LambdaTrooperObserver extends Observer implements Logger {

	@local
	protected ContainmentTeam containmentTeam;

	public LambdaTrooperObserver() {
		super();

		Logger.setLoggingName("LambdaTrooperObserver");
	}

	public native int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);

	public boolean isLambdaTrooperObserver() {
		return true;
	}

	@local
	public void setContainmentTeam(ContainmentTeam team) {
		containmentTeam = team;
	}
}