/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.managers.gcw.observers;

import server.zone.objects.creature.ai.AiAgent;
import server.zone.objects.scene.SceneObject;
import server.zone.objects.tangible.TangibleObject;
import engine.core.ManagedObject;
import engine.util.Observer;
import engine.util.Observable;
import system.thread.Mutex;

include engine.log.Logger;
include system.util.Vector;
include engine.util.u3d.Vector3;

class SquadObserver extends Observer implements Logger {
	@local
	@dereferenced
	protected Vector<AiAgent> teamMembers;

	@dereferenced
	protected transient Mutex squadLock;

	public SquadObserver() {
		super();

		Logger.setLoggingName("SquadObserver");
	}

	@local
	@read
	public int size() {
		return teamMembers.size();
	}

	@local
	@preLocked
	public native void removeMember(int index) {
		teamMembers.remove(index);
	}

	@local
	public native void addMember(AiAgent member);

	@local
	public native AiAgent getMember(int teamMemberIndex);

	@local
	public native void despawnSquad();

	@local
	public native boolean despawnMembersCloseToLambdaShuttle(@dereferenced final Vector3 landingPosition, boolean forcedCleanup);
}