import "../../tangible/TangibleObject";
import "../../creature/CreatureObject";
import "../../player/Player";
import "../../tangible/deed/DeedObject";
import "../../tangible/deed/generatordeed/GeneratorDeed";
import "../InstallationObject";

import "../../../Zone";

include "engine/service/Message";

interface GeneratorObject implements InstallationObject {

	GeneratorObject(unsigned long oid) {
		super (oid);
	}
	
	GeneratorObject(unsigned long oid, GeneratorDeed theDeed) {
		super (oid, theDeed);
	}
}
