/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

package server.zone.objects.scene;

import engine.core.ManagedObject;
import engine.log.Logger;
import engine.core.ManagedReference;
import engine.util.Coordinate;
import engine.util.QuadTreeEntry;
import system.io.Serializable;
import engine.lua.Lua;
import engine.lua.LuaObject;
import system.util.VectorMap;
import system.util.Quaternion;

import server.zone.ZoneProcessServerImplementation;

include server.zone.ZoneClientSession;

import server.zone.objects.scene.variables.StringId;
import server.zone.objects.scene.variables.CustomizationVariables;;

import server.zone.objects.scene.variables.SceneObjectReference;
import engine.core.ManagedReference;


class SceneObject extends ManagedObject, native QuadTreeEntry, native Logger, native Serializable {
	protected ZoneProcessServerImplementation server;
	
	protected native unsigned long objectID;
	
	protected SceneObject parent;
	
	protected VectorMap<string, SceneObject> children;
	
	protected unsigned int objectCRC;
	
	protected Quaternion direction;
	
	protected native float positionX;
	protected native float positionZ;
	protected native float positionY;
	
	protected string arrangementDescriptor;
	
	protected StringId objectName;
	protected StringId detailedDescription;
	protected unsigned int containerType;
	protected unsigned int containerVolumeLimit;
	protected unsigned int gameObjectType; 
	
	public static boolean registered;
	
	public static final int ARMOR = 0x100;
	public static final int BODYARMOR = 0x101;
	public static final int HEADARMOR = 0x102;
	public static final int MISCARMOR = 0x103;
	public static final int LEGARMOR = 0x104;
	public static final int ARMARMOR = 0x105;
	public static final int HANDARMOR = 0x106;
	public static final int FOOTARMOR = 0x107;
	public static final int SHIELDGENERATOR = 0x108;

	public static final int BUILDING = 0x200;
	public static final int MUNICIPALBUILDING = 0x201;
	public static final int FACTIONPERKBUILDING = 0x203;

	public static final int CREATURE = 0x400;
	public static final int NPCCREATURE = 0x401;
	public static final int DROIDCREATURE = 0x402;
	public static final int PROBOTCREATURE = 0x403;

	public static final int INTANGIBLE = 0x800;
	public static final int DRAFTSCHEMATIC = 0x801;
	public static final int MANUFACTURINGSCHEMATIC = 0x802;
	public static final int MISSIONOBJECT = 0x803;
	public static final int TOKEN = 0x804;
	public static final int WAYPOINT = 0x805;
	public static final int DATA2 = 0x806;
	public static final int PETCONTROLDEVICE = 0x807;
	public static final int VEHICLECONTROLDEVICE = 0x808;
	public static final int SHIPCONTROLDEVICE = 0x80A;
	public static final int DROIDCONTROLDEVICE = 0x80B;

	public static final int INSTALLATION = 0x1000;
	public static final int FACTORY = 0x1001;
	public static final int GENERATOR = 0x1002;
	public static final int HARVESTER = 0x1003;
	public static final int TURRET = 0x1004;
	public static final int MINEFIELD = 0x1005;

	public static final int TANGIBLE = 0x2000;
	public static final int AMMUNITION = 0x2001;
	public static final int CHEMICAL = 0x2002;
	public static final int CONTAINER = 0x2005;
	public static final int CRAFTINGSTATION = 0x2006;
	public static final int ELECTRONICS = 0x2008;
	public static final int FLORA = 0x2009;
	public static final int FOOD = 0x200A;
	public static final int FURNITURE = 0x200B;
	public static final int INSTRUMENT = 0x200C;
	public static final int PHARMACEUTICAL = 0x200D;
	public static final int SIGN = 0x200F;
	public static final int COUNTER = 0x2010;
	public static final int FACTORYCRATE = 0x2011;
	public static final int TRAVELTICKET = 0x2012;
	public static final int GENERICITEM = 0x2013;
	public static final int TRAP = 0x2014;
	public static final int WEARABLECONTAINER = 0x2015;
	public static final int FISHINGPOLE = 0x2016;
	public static final int FISHINGBAIT = 0x2017;
	public static final int DRINK = 0x2018;
	public static final int FIREWORK = 0x2019;
	public static final int ITEM = 0x201A;
	public static final int PETMEDECINE = 0x201B;
	public static final int FIREWORKSHOW = 0x201C;
	public static final int CLOTHINGATTACHMENT = 0x201D;
	public static final int LIVESAMPLE = 0x201E;
	public static final int ARMORATTACHMENT = 0x201F;
	public static final int COMMUNITYCRAFTINGPROJECT = 0x2020;
	public static final int CRYSTAL = 0x2021;
	public static final int DROIDPROGRAMMINGCHIP = 0x2022;
	public static final int ASTEROID = 0x2023;
	public static final int PILOTCHAIR = 0x2024;
	public static final int OPERATIONSCHAIR = 0x2025;
	public static final int TURRETACCESSLADDER = 0x2026;
	public static final int CONTAINER2 = 0x2027;
	public static final int CAMOKIT = 0x2028;

	public static final int TERMINAL = 0x4000;
	public static final int BANK = 0x4001;
	public static final int BAZAAR = 0x4002;
	public static final int CLONING = 0x4003;
	public static final int INSURANCE = 0x4004;
	public static final int MISSIONTERMINAL = 0x4006;
	public static final int PLAYERTERMINALSTRUCTURE = 0x4008;
	public static final int SHIPPINGTERMINAL = 0x4009;
	public static final int SPACETERMINAL = 0x400B;
	public static final int INTERACTIVETERMINAL = 0x400C;

	public static final int TOOL = 0x8000;
	public static final int CRAFTINGTOOL = 0x8001;
	public static final int SURVEYTOOL = 0x8002;
	public static final int REPAIRTOOL = 0x8003;
	public static final int CAMPKIT = 0x8004;
	public static final int SHIPCOMPONENTREPAIRITEM = 0x8005;

	public static final int VEHICLE = 0x10000;
	public static final int HOVERVEHICLE = 0x10001;

	public static final int WEAPON = 0x20000;
	public static final int MELEEWEAPON = 0x20001;
	public static final int RANGEDWEAPON = 0x20002;
	public static final int THROWNWEAPON = 0x20003;
	public static final int HEAVYWEAPON = 0x20004;
	public static final int MINE = 0x20005;
	public static final int SPECIALHEAVYWEAPON = 0x20006;
	public static final int ONEHANDMELEEWEAPON = 0x20007;
	public static final int TWOHANDMELEEWEAPON = 0x20008;
	public static final int POLEARM = 0x20009;
	public static final int PISTOL = 0x2000A;
	public static final int CARBINE = 0x2000B;
	public static final int RIFLE = 0x2000C;
	public static final int GRENADE = 0x2000E;

	public static final int COMPONENT = 0x40000;
	public static final int ARMORCOMPONENT = 0x40001;
	public static final int CHEMISTRYCOMPONENT = 0x40002;
	public static final int CLOTHINGCOMPONENT = 0x40003;
	public static final int COMMUNITYCRAFTINGCOMPONENT = 0x40004;
	public static final int DROIDCOMPONENT = 0x40005;
	public static final int ELECTRONICSCOMPONENT = 0x40006;
	public static final int GENETICCOMPONENT = 0x40007;
	public static final int LIGHTSABERCRYSTAL = 0x40008;
	public static final int MELEEWEAPONCOMPONENT = 0x40009;
	public static final int MUNITIONCOMPONENT = 0x4000A;
	public static final int RANGEDWEAPONCOMPONENT = 0x4000B;
	public static final int STRUVTURECOMPONENT = 0x4000C;
	public static final int TISSUECOMPONENT = 0x4000D;

	public static final int WEAPONPOWERUP = 0x80000;
	public static final int MELEEWEAPONPOWERUP = 0x80001;
	public static final int RANGEDWEAPONPOWERUP = 0x80002;
	public static final int THROWNWEAPONPOWERUP = 0x80003;
	public static final int HEAVYWEAPONPOWERUP = 0x80004;
	public static final int MINEPOWERUP = 0x80005;
	public static final int SPECIALHEAVYWEAPONPOWERUP = 0x80006;

	public static final int WEARABLE = 0x200000;
	public static final int RING = 0x200001;
	public static final int BRACELET = 0x200002;
	public static final int NECKLACE = 0x200003;
	public static final int EARRING = 0x200004;

	public static final int RESOURCECONTAINER = 0x400000;
	public static final int ENERGYGAS = 0x400001;
	public static final int ENERGYLIQUID = 0x400002;
	public static final int ENERGYRADIOACTIVE = 0x400003;
	public static final int ENERGYSOLID = 0x400004;
	public static final int INORGANICCHEMICAL = 0x400005;
	public static final int INORGANICGAS = 0x400006;
	public static final int INORGANICMINERAL = 0x400007;
	public static final int WATER = 0x400008;
	public static final int ORGANICFOOD = 0x400009;
	public static final int ORGANICHIDE = 0x40000A;
	public static final int ORGANICSTRUCTURAL = 0x40000B;
	public static final int QUESTREOURCE = 0x40000C;

	public static final int DEED = 0x800000;
	public static final int BUILDINGDEED = 0x800001;
	public static final int INSTALLATIONDEED = 0x800002;
	public static final int PETDEED = 0x800003;
	public static final int DROIDDEED = 0x800004;
	public static final int VEHICLEDEED = 0x800005;
	public static final int RESOURCEDEED = 0x800006;

	public static final int CLOTHING = 0x1000000;
	public static final int BANDOLIER = 0x1000001;
	public static final int BELT = 0x1000002;
	public static final int BODYSUIT = 0x1000003;
	public static final int CAPE = 0x1000004;
	public static final int CLOAK = 0x1000005;
	public static final int FOOTWEAR = 0x1000006;
	public static final int DRESS = 0x1000007;
	public static final int HANDWEAR = 0x1000008;
	public static final int EYEWEAR = 0x1000009;
	public static final int HEADWEAR = 0x100000A;
	public static final int JACKET = 0x100000B;
	public static final int PANTS = 0x100000C;
	public static final int ROBE = 0x100000D;
	public static final int SHIRT = 0x100000E;
	public static final int VEST = 0x100000F;
	public static final int WOOKIEGARB = 0x1000010;
	public static final int MISCCLOTHING = 0x1000011;
	public static final int SKIRT = 0x1000012;
	public static final int ITHOGARB = 0x1000013;

	public SceneObject(LuaObject templateData, SceneObject parent = NULL);
	
	public void addSerializableVariables();
	
	public void serialize(string data);
	
	public void deSerialize(final string data);
	
	public void redeploy() {
	}

	public void scheduleUndeploy() {
	}

	public void undeploy() {
	}

	public void removeUndeploymentEvent() {
	}
	
	public boolean isPlayer() {
		return true;
	}
	
	public abstract boolean addObject(string slot, SceneObject object) {
		/*if (children.contains(slot)) {
			removeObject(slot);
		}
		
		children.put(slot, object);
		
		//object.setParent(this);*/
		
		return true;
	}
	
	public abstract boolean removeObject(string slot) {
		return children.drop(slot);
	}
	
	public void create(ZoneClientSession client);
	
	public void destroy(ZoneClientSession client);
	
	public abstract void sendTo(SceneObject player, boolean doClose = true) {
	}
	
	public unsigned long getObjectID() {
		return QuadTreeEntry.objectID;
	}
	
	public float getPositionX() {
		return QuadTreeEntry.getPositionX();
	}

	public float getPositionZ() {
		return QuadTreeEntry.getPositionZ();
	}

	public float getPositionY() {
		return QuadTreeEntry.getPositionY();
	}
	
	public float getDirectionX() {
		return direction.getX();
	}

	public float getDirectionZ() {
		return direction.getZ();
	}

	public float getDirectionY() {
		return direction.getY();
	}

	public float getDirectionW() {
		return direction.getW();
	}
	
	public unsigned int getObjectCRC() {
		return this.objectCRC;
	}
	
	/*public StringId getObjectName() {
		return this.objectName;
	}*/
	
	public unsigned int getGameObjectType() {
		return this.gameObjectType;
	}
	
	public void setPosition(float x, float z, float y) {
		QuadTreeEntry.setPosition(x, z, y);
	}
	
	public void setGameObjectType(unsigned int type) {
		this.gameObjectType = type;
	}
	
	public void setObjectCRC(unsigned int objCRC) {
		this.objectCRC = objCRC;
	}
	
	public void setParent(SceneObject parent) {
		this.parent = parent;
	}

}

