/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.building.travel;

import server.zone.objects.building.BuildingObject;

class TravelBuildingObject extends BuildingObject {

	public TravelBuildingObject() {
		Logger.setLoggingName("TravelBuildingObject");
	}
}
