update skills set skill_commands = "cert_grenade_proton,throwgrenadeproton,flameCone2,fireAcidCone2,ranged_damage_mitigation_3" where skill_name = "combat_commando_master" ;
update skills set skill_commands = "cert_rocket_launcher,cert_pistol_launcher,cert_rifle_flame_thrower,cert_rifle_acid_beam,cert_grenade_fragmentation,throwgrenadefragmentation" where skill_name = "combat_commando_novice" ;
update skills set skill_commands = "cert_grenade_cryoban,throwgrenadecryoban,ranged_damage_mitigation_1" where skill_name = "combat_commando_heavyweapon_accuracy_01" ;
update skills set skill_commands = "cert_grenade_glop,throwgrenadeglop" where skill_name = "combat_commando_heavyweapon_accuracy_02" ;
update skills set skill_commands = "cert_grenade_imperial_detonator,throwimperialdetonator,ranged_damage_mitigation_2" where skill_name = "combat_commando_heavyweapon_accuracy_03" ;
update skills set skill_commands = "cert_grenade_thermal_detonator,throwthermaldetonator" where skill_name = "combat_commando_heavyweapon_accuracy_04" ;

update skills set skill_commands = "cert_knife_stone,cert_knife_survival,cert_lance_staff_wood_s1,cert_axe_heavy_duty,cert_rifle_cdef,cert_pistol_cdef,cert_carbine_cdef,cert_grenade_fragmentation_light,throwgrenade" where skill_name = "species_bothan" ;
update skills set skill_commands = "cert_knife_stone,cert_knife_survival,cert_lance_staff_wood_s1,cert_axe_heavy_duty,cert_rifle_cdef,cert_pistol_cdef,cert_carbine_cdef,cert_grenade_fragmentation_light,throwgrenade" where skill_name = "species_human" ;
update skills set skill_commands = "cert_knife_stone,cert_knife_survival,cert_lance_staff_wood_s1,cert_axe_heavy_duty,cert_rifle_cdef,cert_pistol_cdef,cert_carbine_cdef,cert_grenade_fragmentation_light,throwgrenade" where skill_name = "species_moncal" ;
update skills set skill_commands = "regeneration,cert_knife_stone,cert_knife_survival,cert_lance_staff_wood_s1,cert_axe_heavy_duty,cert_rifle_cdef,cert_pistol_cdef,cert_carbine_cdef,cert_grenade_fragmentation_light,throwgrenade" where skill_name = "species_trandoshan" ;
update skills set skill_commands = "cert_knife_stone,cert_knife_survival,cert_lance_staff_wood_s1,cert_axe_heavy_duty,cert_rifle_cdef,cert_pistol_cdef,cert_carbine_cdef,cert_grenade_fragmentation_light,throwgrenade" where skill_name = "species_twilek" ;
update skills set skill_commands = "cert_knife_stone,cert_knife_survival,cert_lance_staff_wood_s1,cert_axe_heavy_duty,cert_rifle_cdef,cert_pistol_cdef,cert_carbine_cdef,cert_grenade_fragmentation_light,throwgrenade" where skill_name = "species_rodian" ;
update skills set skill_commands = "wookieeRoar,cert_rifle_bowcaster,cert_knife_stone,cert_knife_survival,cert_lance_staff_wood_s1,cert_axe_heavy_duty,cert_rifle_cdef,cert_pistol_cdef,cert_carbine_cdef,cert_grenade_fragmentation_light,throwgrenade" where skill_name = "species_wookiee" ;
update skills set skill_commands = "vitalize,equilibrium,cert_knife_stone,cert_knife_survival,cert_lance_staff_wood_s1,cert_axe_heavy_duty,cert_rifle_cdef,cert_pistol_cdef,cert_carbine_cdef,cert_grenade_fragmentation_light,throwgrenade" where skill_name = "species_zabrak" ;
update skills set skill_commands = "cert_knife_stone,cert_knife_survival,cert_lance_staff_wood_s1,cert_axe_heavy_duty,cert_rifle_cdef,cert_pistol_cdef,cert_carbine_cdef,cert_grenade_fragmentation_light,throwgrenade" where skill_name = "species_ithorian" ;
update skills set skill_commands = "space_navigator,cert_knife_stone,cert_knife_survival,cert_lance_staff_wood_s1,cert_axe_heavy_duty,cert_rifle_cdef,cert_pistol_cdef,cert_carbine_cdef,cert_grenade_fragmentation_light,throwgrenade" where skill_name = "species_sullustan" ;
