SET FOREIGN_KEY_CHECKS=0;

--
-- Definition of table `swgemu`.`characters`
--

DROP TABLE IF EXISTS `swgemu`.`characters`;
CREATE TABLE  `swgemu`.`characters` (
  `character_id` mediumint(8) unsigned NOT NULL auto_increment,
  `account_id` mediumint(8) unsigned NOT NULL default '0',
  `galaxy_id` int(5) unsigned NOT NULL default '0',
  `firstname` varchar(15) NOT NULL default '',
  `surname` varchar(20) default NULL,
  `appearance` mediumtext NOT NULL,
  `professions` varbinary(110) NOT NULL,
  `race` tinyint(2) NOT NULL default '0',
  `gender` tinyint(1) NOT NULL default '0',
  `lots` int(2) NOT NULL default '10',
  `credits_inv` int(11) unsigned default '10000',
  `credits_bank` int(11) unsigned default '0',
  `guild` smallint(5) NOT NULL,
  `x` float(10,6) default NULL,
  `y` float(10,6) default NULL,
  `z` float(10,6) default NULL,
  `zoneid` int(10) default NULL,
  `planet_id` int(2) default NULL,
  `lfg` tinyint(1) default '0',
  `helper` tinyint(1) default '0',
  `roleplayer` tinyint(1) default '0',
  `faction_id` int(4) unsigned default NULL,
  `archived` tinyint(1) default '0',
  `scale` float(4,2) default '1.00',
  `biography` text NOT NULL,
  `appearancelen` int(11) NOT NULL default '0',
  `infofield` text NOT NULL,
  `hair` text NOT NULL,
  `hairData` text NOT NULL,
  `hairDataLen` int(8) NOT NULL default '0',
  `playermodel` text NOT NULL,
  `CRC` bigint(20) NOT NULL default '0',
  `Title` tinytext NOT NULL,
  `parentid` bigint(20) NOT NULL default '0',
  `itemShift` int(11) NOT NULL default '100',
  `Health` mediumint(8) unsigned NOT NULL default '900',
  `Strength` mediumint(8) unsigned NOT NULL default '450',
  `Constitution` mediumint(8) unsigned NOT NULL default '450',
  `Action` mediumint(8) unsigned NOT NULL default '900',
  `Quickness` mediumint(8) unsigned NOT NULL default '450',
  `Stamina` mediumint(8) unsigned NOT NULL default '450',
  `Mind` mediumint(8) unsigned NOT NULL default '900',
  `Focus` mediumint(8) unsigned NOT NULL default '450',
  `Willpower` mediumint(8) unsigned NOT NULL default '450',
  `HealthWounds` mediumint(8) unsigned NOT NULL default '0',
  `StrengthWounds` mediumint(8) unsigned NOT NULL default '0',
  `ConstitutionWounds` mediumint(8) unsigned NOT NULL default '0',
  `ActionWounds` mediumint(8) unsigned NOT NULL default '0',
  `QuicknessWounds` mediumint(8) unsigned NOT NULL default '0',
  `StaminaWounds` mediumint(8) unsigned NOT NULL default '0',
  `MindWounds` mediumint(8) unsigned NOT NULL default '0',
  `FocusWounds` mediumint(8) unsigned NOT NULL default '0',
  `WillpowerWounds` mediumint(8) unsigned NOT NULL default '0',
  `BattleFatigue` mediumint(8) unsigned NOT NULL default '0',
  `PvpRating` smallint(5) unsigned NOT NULL default '1200',
  `adminLevel` tinyint(1) unsigned NOT NULL default '4',
  `guildpermission` tinyint(3) unsigned NOT NULL default '0',
  `public` tinyint(1) unsigned NOT NULL default '0',
  `factionStatus` tinyint(1) unsigned NOT NULL default '0',
  `factionRank` tinyint(1) unsigned NOT NULL default '0',
  `experience` text NOT NULL,
  PRIMARY KEY  (`character_id`)
) ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;


