Core3: server::zone::objects::scene::SceneObjectImplementation Class Reference
server::zone::objects::scene::SceneObjectImplementation Class Reference
#include <SceneObject.h>
Public Member Functions
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void loadTemplateData (SharedObjectTemplate *templateData)
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendTo (SceneObject *player, bool doClose)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendBaselinesTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
virtual void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
virtual void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
virtual int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isTangibleObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
virtual void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< SceneObject * > _this
Protected Member Functions
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Friends
class SceneObject
Detailed Description
Definition at line 1244 of file SceneObject.h.
Constructor & Destructor Documentation
SceneObjectImplementation::SceneObjectImplementation ()
Definition at line 4149 of file SceneObject.cpp.
References _initializeImplementation(), and initializePrivateData().
SceneObjectImplementation::SceneObjectImplementation (DummyConstructorParameter * param)
Definition at line 3773 of file SceneObject.cpp.
References _initializeImplementation().
SceneObjectImplementation::~SceneObjectImplementation () protected virtual
Definition at line 3778 of file SceneObject.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * SceneObjectImplementation::_getStub ()
Definition at line 3796 of file SceneObject.cpp.
References _this.
void SceneObjectImplementation::_initializeImplementation () protected
Definition at line 3783 of file SceneObject.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SceneObjectImplementation().
void SceneObjectImplementation::_serializationHelperMethod () protected
Definition at line 3832 of file SceneObject.cpp.
Referenced by _initializeImplementation().
void SceneObjectImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 3791 of file SceneObject.cpp.
References _this.
Referenced by server::zone::objects::scene::SceneObject::SceneObject().
void SceneObjectImplementation::addActiveArea (ActiveArea * area)
Definition at line 1609 of file SceneObjectImplementation.cpp.
References activeAreas.
Referenced by server::zone::objects::scene::SceneObject::addActiveArea().
void SceneObjectImplementation::addActiveSession (unsigned int type, Facade * session)
Definition at line 4328 of file SceneObject.cpp.
References objectActiveSessions.
Referenced by server::zone::objects::scene::SceneObject::addActiveSession().
void SceneObjectImplementation::addPendingTask (const String & name, Task * task, int miliseconds)
Adds a pending task of this SceneObject
Precondition
{ this locked }
Postcondition
{ this locked}
Parameters
name Name of the task
task Task to add
Definition at line 4255 of file SceneObject.cpp.
References containerLock, and getPendingTasks().
Referenced by server::zone::objects::scene::SceneObject::addPendingTask(), server::zone::objects::creature::CreatureObjectImplementation::queueDizzyFallEvent(), server::zone::objects::creature::CreatureImplementation::scheduleDespawn(), server::zone::objects::creature::AiAgentImplementation::scheduleDespawn(), server::zone::objects::installation::factory::FactoryObjectImplementation::startFactory(), and server::zone::objects::building::BuildingObjectImplementation::updatePaidAccessList().
void SceneObjectImplementation::broadcastDestroy (SceneObject * object, bool sendSelf)
Broadcasts an object to the in range objects
Precondition
{this object is locked, object is not null }
Postcondition
{this object is locked, in range objects received the object }
Parameters
object SceneObject that will be sent to the in range objects
sendSelf if true the owner of this object receives the object too
Definition at line 759 of file SceneObjectImplementation.cpp.
References _this, and broadcastDestroyPrivate().
Referenced by server::zone::objects::scene::SceneObject::broadcastDestroy(), and server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild().
void SceneObjectImplementation::broadcastDestroyPrivate (SceneObject * object, SceneObject * selfObject)
Definition at line 690 of file SceneObjectImplementation.cpp.
References server::zone::objects::scene::SceneObject::getClient(), getRootParent(), getZoneServer(), server::zone::ZoneServer::isServerLoading(), server::zone::objects::scene::SceneObject::isVehicleObject(), and zone.
Referenced by broadcastDestroy(), and server::zone::objects::scene::SceneObject::broadcastDestroyPrivate().
void SceneObjectImplementation::broadcastMessage (BasePacket * message, bool sendSelf, bool lockZone = true)
Broadcasts the message to the in range objects
Precondition
{this object is locked, message is not null }
Postcondition
{this object is locked, in range objects received a copy of the message, message is deleted }
Parameters
sendSelf if true the owner if this object receives the message too
Definition at line 880 of file SceneObjectImplementation.cpp.
References _this, and broadcastMessagePrivate().
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::addDefender(), server::zone::objects::creature::CreatureObjectImplementation::addWearableObject(), server::zone::objects::scene::SceneObject::broadcastMessage(), server::zone::objects::creature::AiAgentImplementation::broadcastNextPositionUpdate(), server::zone::objects::player::PlayerObjectImplementation::clearCharacterBit(), server::zone::objects::creature::CreatureObjectImplementation::clearCombatState(), server::zone::objects::creature::CreatureObjectImplementation::clearState(), server::zone::objects::creature::CreatureObjectImplementation::doAnimation(), server::zone::objects::creature::CreatureObjectImplementation::doCombatAnimation(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), server::zone::objects::creature::CreatureObjectImplementation::playEffect(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefender(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefenders(), server::zone::objects::creature::CreatureObjectImplementation::removeWearableObject(), server::zone::objects::creature::CreatureObjectImplementation::setBaseHAM(), server::zone::objects::player::PlayerObjectImplementation::setCharacterBit(), server::zone::objects::creature::CreatureObjectImplementation::setCombatState(), server::zone::objects::tangible::TangibleObjectImplementation::setConditionDamage(), server::zone::objects::tangible::TangibleObjectImplementation::setCountdownTimer(), server::zone::objects::creature::CreatureObjectImplementation::setCreatureLink(), server::zone::objects::tangible::TangibleObjectImplementation::setCustomObjectName(), server::zone::objects::tangible::TangibleObjectImplementation::setDefender(), server::zone::objects::creature::CreatureObjectImplementation::setEncumbrance(), server::zone::objects::creature::CreatureObjectImplementation::setFactionRank(), server::zone::objects::creature::CreatureObjectImplementation::setHAM(), server::zone::objects::creature::CreatureObjectImplementation::setHeight(), server::zone::objects::creature::CreatureObjectImplementation::setInstrumentID(), server::zone::objects::creature::CreatureObjectImplementation::setLevel(), server::zone::objects::tangible::TangibleObjectImplementation::setMaxCondition(), server::zone::objects::creature::CreatureObjectImplementation::setMaxHAM(), server::zone::objects::creature::CreatureObjectImplementation::setMood(), server::zone::objects::creature::CreatureObjectImplementation::setMoodString(), server::zone::objects::tangible::TangibleObjectImplementation::setOptionsBitmask(), server::zone::objects::creature::CreatureObjectImplementation::setPerformanceAnimation(), server::zone::objects::creature::CreatureObjectImplementation::setPerformanceCounter(), server::zone::objects::resource::ResourceContainerImplementation::setQuantity(), server::zone::objects::creature::CreatureObjectImplementation::setShockWounds(), server::zone::objects::creature::CreatureObjectImplementation::setState(), server::zone::objects::creature::CreatureObjectImplementation::setTargetID(), server::zone::objects::player::PlayerObjectImplementation::setTitle(), server::zone::objects::factorycrate::FactoryCrateImplementation::setUseCount(), server::zone::objects::creature::CreatureObjectImplementation::setWeapon(), server::zone::objects::creature::CreatureObjectImplementation::setWounds(), showFlyText(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::updateCharges(), updateDirection(), server::zone::objects::creature::CreatureObjectImplementation::updateGroup(), and server::zone::objects::creature::CreatureObjectImplementation::updateGroupInviterID().
void SceneObjectImplementation::broadcastMessagePrivate (BasePacket * message, SceneObject * selfObject, bool lockZone)
Definition at line 764 of file SceneObjectImplementation.cpp.
References server::zone::objects::scene::SceneObject::getClient(), getRootParent(), getZoneServer(), server::zone::ZoneServer::isServerLoading(), server::zone::ZoneClientSession::sendMessage(), and zone.
Referenced by broadcastMessage(), and server::zone::objects::scene::SceneObject::broadcastMessagePrivate().
void SceneObjectImplementation::broadcastMessages (Vector< BasePacket * > * messages, bool sendSelf)
Broadcasts a vector of messages to the in range objects
Precondition
{this object is locked }
Postcondition
{ this object is locked, in range objects received the messages, messages are deleted and removed from the vector }
Parameters
messages a vector containing the messages to be sent, it will be emptied when messages get sent
sendSelf if true the owner of this object receives the messages too
Definition at line 973 of file SceneObjectImplementation.cpp.
References _this, and broadcastMessagesPrivate().
Referenced by server::zone::objects::scene::SceneObject::broadcastMessages(), server::zone::objects::installation::InstallationObjectImplementation::setOperating(), and server::zone::objects::creature::CreatureObjectImplementation::setPosture().
void SceneObjectImplementation::broadcastMessagesPrivate (Vector< BasePacket * > * messages, SceneObject * selfObject)
Definition at line 886 of file SceneObjectImplementation.cpp.
References server::zone::objects::scene::SceneObject::getClient(), getRootParent(), getZoneServer(), server::zone::ZoneServer::isServerLoading(), server::zone::objects::scene::SceneObject::isVehicleObject(), server::zone::objects::scene::SceneObject::sendMessage(), and zone.
Referenced by broadcastMessages(), and server::zone::objects::scene::SceneObject::broadcastMessagesPrivate().
void SceneObjectImplementation::broadcastObject (SceneObject * object, bool sendSelf)
Broadcasts an object to the in range objects
Precondition
{this object is locked, object is not null }
Postcondition
{this object is locked, in range objects received the object }
Parameters
object SceneObject that will be sent to the in range objects
sendSelf if true the owner of this object receives the object too
Definition at line 685 of file SceneObjectImplementation.cpp.
References _this, and broadcastObjectPrivate().
Referenced by server::zone::objects::scene::SceneObject::broadcastObject(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), and server::zone::objects::creature::AiAgentImplementation::selectWeapon().
void SceneObjectImplementation::broadcastObjectPrivate (SceneObject * object, SceneObject * selfObject)
Definition at line 615 of file SceneObjectImplementation.cpp.
References server::zone::objects::scene::SceneObject::getClient(), getRootParent(), getZoneServer(), server::zone::ZoneServer::isServerLoading(), server::zone::objects::scene::SceneObject::isVehicleObject(), and zone.
Referenced by broadcastObject(), and server::zone::objects::scene::SceneObject::broadcastObjectPrivate().
int SceneObjectImplementation::canAddObject (SceneObject * object, int containmentType, String & errorDescription) virtual
Evaluates if this object has the necessary free slots to be able to add the specified SceneObject
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be checked
error error string that the player will receive on error
Returns
returns 0 on success, or error code
Reimplemented in server::zone::objects::tangible::fishing::FishingPoleObjectImplementation, server::zone::objects::cell::CellObjectImplementation, server::zone::objects::tangible::ContainerImplementation, and server::zone::objects::tangible::loot::LootkitObjectImplementation.
Definition at line 1121 of file SceneObjectImplementation.cpp.
References _this, containerComponent, and containmentType.
Referenced by server::zone::objects::tangible::loot::LootkitObjectImplementation::canAddObject(), server::zone::objects::tangible::ContainerImplementation::canAddObject(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::canAddObject(), server::zone::objects::scene::SceneObject::canAddObject(), and server::zone::objects::factorycrate::FactoryCrateImplementation::extractObjectToParent().
int SceneObjectImplementation::canBeDestroyed (CreatureObject * player) virtual
Checks if the object can be destroyed
Precondition
{ player is locked }
Postcondition
{ player is locked }
Parameters
player Player that attempts to destroy this object
Returns
0 on succes, != 0 on error
Reimplemented in server::zone::objects::intangible::VehicleControlDeviceImplementation.
Definition at line 4193 of file SceneObject.cpp.
Referenced by server::zone::objects::intangible::VehicleControlDeviceImplementation::canBeDestroyed(), and server::zone::objects::scene::SceneObject::canBeDestroyed().
byte SceneObjectImplementation::checkContainerPermission (CreatureObject * player, unsigned short permission) virtual
Definition at line 4212 of file SceneObject.cpp.
References _this, and containerComponent.
Referenced by server::zone::objects::scene::SceneObject::checkContainerPermission(), server::zone::objects::tangible::ContainerImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::ContainerImplementation::handleObjectMenuSelect(), server::zone::objects::building::BuildingObjectImplementation::isAllowedEntry(), server::zone::objects::building::BuildingObjectImplementation::onEnter(), and server::zone::objects::cell::CellObjectImplementation::sendPermissionsTo().
void SceneObjectImplementation::clearContainerDefaultAllowPermission (unsigned short perm)
Definition at line 5100 of file SceneObject.cpp.
References containerPermissions.
Referenced by server::zone::objects::scene::SceneObject::clearContainerDefaultAllowPermission().
void SceneObjectImplementation::clearContainerDefaultDenyPermission (unsigned short perm)
Definition at line 5110 of file SceneObject.cpp.
References containerPermissions.
Referenced by server::zone::objects::scene::SceneObject::clearContainerDefaultDenyPermission().
void SceneObjectImplementation::close (SceneObject * client) protected
Sends a SceneObjectCloseMessage of this object to client
Precondition
{ this object is locked }
Postcondition
{ this object is locked, client received the close message }
Parameters
client ZoneClientSession that will receive the message
Definition at line 238 of file SceneObjectImplementation.cpp.
References _this, and server::zone::objects::scene::SceneObject::sendMessage().
Referenced by sendTo(), sendWithoutContainerObjectsTo(), and sendWithoutParentTo().
void SceneObjectImplementation::closeContainerTo (CreatureObject * player, bool notify = true) virtual
Closes the container of a player
Definition at line 1140 of file SceneObjectImplementation.cpp.
References _this, and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::objects::scene::SceneObject::closeContainerTo().
int SceneObjectImplementation::compareTo (SceneObject * obj)
Compares object ids of this object with obj
Precondition
{ this object is locked, obj is not null }
Postcondition
{this object is locked }
Parameters
obj SceneObject that will be compared to
Returns
returns 1 if this < obj, -1 if this > obj and 0 if this == obj
Definition at line 4227 of file SceneObject.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), and getObjectID().
Referenced by server::zone::objects::scene::SceneObject::compareTo().
bool SceneObjectImplementation::containsActiveSession (unsigned int type)
Definition at line 4333 of file SceneObject.cpp.
References objectActiveSessions.
Referenced by server::zone::objects::scene::SceneObject::containsActiveSession().
bool SceneObjectImplementation::containsChildObject (SceneObject * obj)
Definition at line 5283 of file SceneObject.cpp.
References childObjects.
Referenced by server::zone::objects::scene::SceneObject::containsChildObject(), server::zone::objects::cell::CellObjectImplementation::destroyAllPlayerItems(), and server::zone::objects::cell::CellObjectImplementation::getCurrentNumberOfPlayerItems().
bool SceneObjectImplementation::containsPendingTask (const String & name)
Definition at line 4311 of file SceneObject.cpp.
References containerLock, and pendingTasks.
Referenced by server::zone::objects::scene::SceneObject::containsPendingTask().
void SceneObjectImplementation::createChildObjects () virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::installation::InstallationObjectImplementation, server::zone::objects::structure::StructureObjectImplementation, server::zone::objects::installation::factory::FactoryObjectImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, and server::zone::objects::installation::garage::GarageInstallationImplementation.
Definition at line 1370 of file SceneObjectImplementation.cpp.
References _this, childObjects, server::zone::ZoneServer::createObject(), direction, error(), server::zone::objects::building::BuildingObject::getCell(), ChildObject::getCellId(), ChildObject::getContainmentType(), ChildObject::getDirection(), getObjectID(), ChildObject::getPosition(), ChildObject::getTemplateFile(), server::zone::objects::building::BuildingObject::getTotalCellNumber(), getZone(), server::zone::Zone::getZoneServer(), isBuildingObject(), server::zone::objects::scene::variables::ContainerPermissions::setDefaultDenyPermission(), server::zone::objects::scene::variables::ContainerPermissions::setDenyPermission(), server::zone::objects::scene::variables::ContainerPermissions::setInheritPermissionsFromParent(), server::zone::objects::scene::variables::ContainerPermissions::setOwner(), templateObject, server::zone::objects::cell::CellObject::transferObject(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::objects::scene::SceneObject::createChildObjects().
void SceneObjectImplementation::createComponents () virtual
Definition at line 209 of file SceneObjectImplementation.cpp.
References attributeListComponent, createContainerComponent(), error(), info(), objectMenuComponent, templateObject, and zoneComponent.
Referenced by server::zone::objects::scene::SceneObject::createComponents().
void SceneObjectImplementation::createContainerComponent () virtual
Reimplemented in server::zone::objects::building::BuildingObjectImplementation, and server::zone::ZoneImplementation.
Definition at line 201 of file SceneObjectImplementation.cpp.
References containerComponent, and templateObject.
Referenced by createComponents(), and server::zone::objects::scene::SceneObject::createContainerComponent().
void SceneObjectImplementation::destroyObjectFromDatabase (bool destroyContainedObjects = false) virtual
Destroys this object from database
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
destroyContainedObjects if true, will destroy from database all its contained objects
Reimplemented in server::zone::objects::player::PlayerObjectImplementation, server::zone::objects::mission::MissionObjectImplementation, server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::installation::InstallationObjectImplementation, server::zone::objects::intangible::VehicleControlDeviceImplementation, server::zone::objects::resource::ResourceContainerImplementation, and server::zone::objects::installation::garage::GarageInstallationImplementation.
Definition at line 340 of file SceneObjectImplementation.cpp.
References _this, childObjects, dataObjectComponent, server::zone::ZoneServer::destroyObjectFromDatabase(), getContainerObject(), getContainerObjectsSize(), getObjectID(), getSlottedObject(), getSlottedObjectsSize(), getZoneServer(), isPlayerCreature(), and server.
Referenced by server::zone::objects::tangible::firework::FireworkObjectImplementation::completeLaunch(), server::zone::objects::tangible::loot::LootkitObjectImplementation::createItem(), server::zone::objects::area::CampSiteActiveAreaImplementation::despawnCamp(), server::zone::objects::creature::ai::AiActorImplementation::destroyActor(), server::zone::objects::tangible::deed::ResourceDeedImplementation::destroyDeed(), server::zone::objects::intangible::VehicleControlDeviceImplementation::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObject::destroyObjectFromDatabase(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::factorycrate::FactoryCrateImplementation::setUseCount(), and server::zone::objects::tangible::TangibleObjectImplementation::setUseCount().
void SceneObjectImplementation::destroyObjectFromWorld (bool sendSelfDestroy) virtual
Destroys the object from the world
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, and server::zone::objects::creature::AiAgentImplementation.
Definition at line 4168 of file SceneObject.cpp.
References _this, and zoneComponent.
Referenced by server::zone::objects::tangible::firework::FireworkObjectImplementation::completeLaunch(), server::zone::objects::tangible::loot::LootkitObjectImplementation::createItem(), server::zone::objects::area::CampSiteActiveAreaImplementation::despawnCamp(), server::zone::objects::creature::ai::AiActorImplementation::destroyActor(), server::zone::objects::tangible::deed::ResourceDeedImplementation::destroyDeed(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::area::MissionSpawnActiveAreaImplementation::notifyEnter(), server::zone::objects::area::MissionReconActiveAreaImplementation::notifyEnter(), server::zone::objects::area::MissionReconActiveAreaImplementation::notifyExit(), server::zone::objects::resource::ResourceContainerImplementation::setQuantity(), server::zone::objects::factorycrate::FactoryCrateImplementation::setUseCount(), and server::zone::objects::tangible::TangibleObjectImplementation::setUseCount().
void SceneObjectImplementation::destroyPlayerCreatureFromDatabase (bool destroyContainedObjects = false) virtual
Destroys a PlayerCreature from the database. If this object is not a PlayerCreature then the method will return without doing anything.
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
destroyContainedObjects if true, will destroy from database all its contained objects
Definition at line 295 of file SceneObjectImplementation.cpp.
References _this, childObjects, dataObjectComponent, server::zone::ZoneServer::destroyObjectFromDatabase(), getContainerObject(), getContainerObjectsSize(), getObjectID(), getSlottedObject(), getSlottedObjectsSize(), getZoneServer(), isPlayerCreature(), and server.
Referenced by server::zone::objects::scene::SceneObject::destroyPlayerCreatureFromDatabase().
bool SceneObjectImplementation::doSendToClient ()
Definition at line 5298 of file SceneObject.cpp.
References sendToClient.
Referenced by server::zone::objects::scene::SceneObject::doSendToClient().
void SceneObjectImplementation::dropActiveArea (ActiveArea * area)
Definition at line 4363 of file SceneObject.cpp.
References activeAreas, and containerLock.
Referenced by server::zone::objects::scene::SceneObject::dropActiveArea().
bool SceneObjectImplementation::dropActiveSession (unsigned int type)
Definition at line 4338 of file SceneObject.cpp.
References objectActiveSessions.
Referenced by server::zone::objects::scene::SceneObject::dropActiveSession().
void SceneObjectImplementation::dropSlottedObject (const String & arrengementDescriptor)
Definition at line 1530 of file SceneObjectImplementation.cpp.
References containerLock, and slottedObjects.
Referenced by server::zone::objects::scene::SceneObject::dropSlottedObject().
void SceneObjectImplementation::error (const String & msg)
Logs an error message
Precondition
{}
Postcondition
{error message has been printed to console and file }
Parameters
msg error message to print
Definition at line 4163 of file SceneObject.cpp.
Referenced by server::zone::objects::installation::InstallationObjectImplementation::activateUiSync(), server::zone::objects::creature::CreatureObjectImplementation::addEncumbrance(), server::zone::objects::creature::CreatureObjectImplementation::addMaxHAM(), server::zone::objects::creature::CreatureObjectImplementation::addSkill(), server::zone::objects::creature::CreatureObjectImplementation::addWounds(), server::zone::objects::tangible::TangibleObjectImplementation::canRepair(), server::zone::objects::installation::InstallationObjectImplementation::changeActiveResourceID(), server::zone::objects::installation::factory::FactoryObjectImplementation::collectMatchesInInputHopper(), server::zone::objects::building::BuildingObjectImplementation::createCellObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), createChildObjects(), createComponents(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::createFactoryBlueprint(), server::zone::objects::draftschematic::DraftSchematicImplementation::createManufactureSchematic(), server::zone::objects::resource::ResourceSpawnImplementation::createResource(), server::zone::objects::area::CampSiteActiveAreaImplementation::despawnCamp(), server::zone::objects::scene::SceneObject::error(), server::zone::objects::factorycrate::FactoryCrateImplementation::extractObject(), server::zone::objects::factorycrate::FactoryCrateImplementation::extractObjectToParent(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::fillAttributeList(), server::zone::objects::tangible::tool::recycle::RecycleToolImplementation::fillObjectMenuResponse(), server::zone::objects::factorycrate::FactoryCrateImplementation::getCraftersName(), server::zone::objects::factorycrate::FactoryCrateImplementation::getPrototype(), server::zone::objects::factorycrate::FactoryCrateImplementation::getSerialNumber(), server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::SurveyToolImplementation::handleObjectMenuSelect(), server::zone::objects::installation::InstallationObjectImplementation::handleStructureAddEnergy(), server::zone::objects::creature::CreatureObjectImplementation::healDamage(), server::zone::objects::creature::CreatureObjectImplementation::healWound(), server::zone::objects::creature::CreatureObjectImplementation::inflictDamage(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::initializeIngredientSlots(), server::zone::objects::guild::GuildObjectImplementation::isInWaringGuild(), isInWater(), server::zone::objects::tangible::firework::FireworkObjectImplementation::loadTemplateData(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::loadTemplateData(), server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), server::zone::objects::player::PlayerObjectImplementation::logout(), server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), server::zone::objects::building::BuildingObjectImplementation::payAccessFee(), server::zone::objects::installation::factory::FactoryObjectImplementation::populateSchematicBlueprint(), server::zone::objects::creature::CreatureObjectImplementation::removeSkill(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), sendAttributeListTo(), server::zone::objects::draftschematic::DraftSchematicImplementation::sendBaselinesTo(), server::zone::objects::creature::ai::AiActorImplementation::sendConversationStartTo(), server::zone::objects::creature::AiAgentImplementation::sendConversationStartTo(), setContainerComponent(), setObjectMenuComponent(), server::zone::objects::building::BuildingObjectImplementation::spawnChildCreaturesFromTemplate(), server::zone::objects::resource::ResourceContainerImplementation::split(), server::zone::objects::factorycrate::FactoryCrateImplementation::split(), server::zone::objects::creature::AiAgentImplementation::tryRetreat(), server::zone::objects::area::LairSpawnAreaImplementation::trySpawnLair(), server::zone::ZoneImplementation::updateActiveAreas(), and server::zone::objects::tangible::deed::DeedImplementation::updateCraftingValues().
void SceneObjectImplementation::faceObject (SceneObject * obj)
Sets this objects direction so that the object is facing the specified object.
Parameters
obj The object to face.
Definition at line 1446 of file SceneObjectImplementation.cpp.
References direction.
Referenced by server::zone::objects::creature::AiAgentImplementation::checkNewAngle(), server::zone::objects::scene::SceneObject::faceObject(), and server::zone::objects::creature::AiAgentImplementation::sendConversationStartTo().
void SceneObjectImplementation::fillAttributeList (AttributeListMessage * msg, CreatureObject * object) virtual
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::creature::AiAgentImplementation, server::zone::objects::tangible::TangibleObjectImplementation, server::zone::objects::creature::ai::AiActorImplementation, server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::installation::InstallationObjectImplementation, server::zone::objects::tangible::component::dna::DnaComponentImplementation, server::zone::objects::manufactureschematic::ManufactureSchematicImplementation, server::zone::objects::tangible::consumable::ConsumableImplementation, server::zone::objects::tangible::tool::CraftingToolImplementation, server::zone::objects::creature::VehicleObjectImplementation, server::zone::objects::resource::ResourceSpawnImplementation, server::zone::objects::tangible::component::genetic::GeneticComponentImplementation, server::zone::objects::tangible::wearables::ArmorObjectImplementation, server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation, server::zone::objects::tangible::pharmaceutical::DotPackImplementation, server::zone::objects::creature::CreatureImplementation, server::zone::objects::draftschematic::DraftSchematicImplementation, server::zone::objects::intangible::VehicleControlDeviceImplementation, server::zone::objects::tangible::pharmaceutical::WoundPackImplementation, server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation, server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation, server::zone::objects::tangible::pharmaceutical::StimPackImplementation, server::zone::objects::tangible::pharmaceutical::CurePackImplementation, server::zone::objects::tangible::pharmaceutical::StatePackImplementation, server::zone::objects::installation::factory::FactoryObjectImplementation, server::zone::objects::tangible::pharmaceutical::RevivePackImplementation, server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation, server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation, server::zone::objects::factorycrate::FactoryCrateImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, server::zone::objects::tangible::attachement::AttachmentImplementation, server::zone::objects::tangible::fishing::FishingPoleObjectImplementation, server::zone::objects::tangible::fishing::FishObjectImplementation, server::zone::objects::tangible::component::ComponentImplementation, server::zone::objects::resource::ResourceContainerImplementation, server::zone::objects::tangible::ticket::TicketObjectImplementation, server::zone::objects::tangible::tool::repair::RepairToolImplementation, server::zone::objects::tangible::deed::pet::PetDeedImplementation, server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation, server::zone::objects::tangible::loot::LootkitObjectImplementation, server::zone::objects::tangible::wearables::WearableObjectImplementation, server::zone::objects::tangible::deed::DeedImplementation, server::zone::objects::tangible::deed::structure::StructureDeedImplementation, server::zone::objects::tangible::fishing::FishingBaitObjectImplementation, server::zone::objects::tangible::powerup::PowerupObjectImplementation, server::zone::objects::tangible::wearables::WearableContainerObjectImplementation, and server::zone::objects::tangible::wearables::PsgArmorObjectImplementation.
Definition at line 4204 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::fillAttributeList().
void SceneObjectImplementation::fillObjectMenuResponse (ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented in server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation, server::zone::objects::tangible::tool::CraftingToolImplementation, server::zone::objects::creature::VehicleObjectImplementation, server::zone::objects::tangible::tool::recycle::RecycleToolImplementation, server::zone::objects::tangible::InstrumentImplementation, server::zone::objects::creature::CreatureImplementation, server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation, server::zone::objects::factorycrate::FactoryCrateImplementation, server::zone::objects::tangible::tool::SurveyToolImplementation, server::zone::objects::tangible::component::ComponentImplementation, server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, server::zone::objects::tangible::fishing::FishObjectImplementation, server::zone::objects::tangible::fishing::FishingPoleObjectImplementation, server::zone::objects::tangible::deed::pet::PetDeedImplementation, server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation, server::zone::objects::tangible::ContainerImplementation, server::zone::objects::tangible::deed::ResourceDeedImplementation, server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation, server::zone::objects::installation::harvester::HarvesterObjectImplementation, server::zone::objects::installation::GeneratorObjectImplementation, and server::zone::objects::intangible::ShipControlDeviceImplementation.
Definition at line 1266 of file SceneObjectImplementation.cpp.
References _this, and objectMenuComponent.
Referenced by server::zone::objects::installation::GeneratorObjectImplementation::fillObjectMenuResponse(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::deed::ResourceDeedImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::ContainerImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::deed::pet::PetDeedImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::fishing::FishObjectImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::tool::CraftingStationImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::component::ComponentImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::tool::SurveyToolImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::InstrumentImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::tool::CraftingToolImplementation::fillObjectMenuResponse(), and server::zone::objects::scene::SceneObject::fillObjectMenuResponse().
void SceneObjectImplementation::finalize ()
Definition at line 4155 of file SceneObject.cpp.
Referenced by ~SceneObjectImplementation().
Vector< ManagedReference< ActiveArea * > > * SceneObjectImplementation::getActiveAreas ()
Definition at line 4403 of file SceneObject.cpp.
References activeAreas.
Referenced by server::zone::objects::scene::SceneObject::getActiveAreas().
int SceneObjectImplementation::getActiveAreasSize ()
Definition at line 4408 of file SceneObject.cpp.
References activeAreas.
Referenced by server::zone::objects::scene::SceneObject::getActiveAreasSize().
Reference< ActiveArea * > SceneObjectImplementation::getActiveRegion ()
Definition at line 4413 of file SceneObject.cpp.
References activeAreas, and containerLock.
Referenced by server::zone::objects::scene::SceneObject::getActiveRegion(), and server::zone::objects::creature::VehicleObjectImplementation::repairVehicle().
Reference< Facade * > SceneObjectImplementation::getActiveSession (unsigned int type)
Returns a Facade session
Definition at line 4323 of file SceneObject.cpp.
References objectActiveSessions.
Referenced by server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::creature::CreatureObjectImplementation::isDancing(), server::zone::objects::creature::CreatureObjectImplementation::isPlayingMusic(), and server::zone::objects::creature::CreatureObjectImplementation::stopEntertaining().
int SceneObjectImplementation::getActiveSessionsCount ()
Definition at line 4343 of file SceneObject.cpp.
References objectActiveSessions.
Referenced by server::zone::objects::scene::SceneObject::getActiveSessionsCount().
String SceneObjectImplementation::getArrangementDescriptor (int idx)
Definition at line 4541 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::scene::SceneObject::getArrangementDescriptor().
int SceneObjectImplementation::getArrangementDescriptorSize ()
Definition at line 4533 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::tangible::ContainerImplementation::canAddObject(), and server::zone::objects::scene::SceneObject::getArrangementDescriptorSize().
SortedVector< ManagedReference< SceneObject * > > * SceneObjectImplementation::getChildObjects ()
Definition at line 5278 of file SceneObject.cpp.
References childObjects.
Referenced by server::zone::objects::scene::SceneObject::getChildObjects().
ManagedWeakReference< CityRegion * > SceneObjectImplementation::getCityRegion () virtual
Reimplemented in server::zone::objects::region::RegionImplementation.
Definition at line 4435 of file SceneObject.cpp.
References cityRegion.
Referenced by server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::building::BuildingObjectImplementation::isCityBanned(), server::zone::objects::creature::VehicleObjectImplementation::sendRepairConfirmTo(), and server::zone::objects::structure::StructureObjectImplementation::updateStructureStatus().
ZoneClientSession * SceneObjectImplementation::getClient () virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 4681 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::getClient().
unsigned int SceneObjectImplementation::getClientGameObjectType ()
Definition at line 4691 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::scene::SceneObject::getClientGameObjectType().
unsigned int SceneObjectImplementation::getClientObjectCRC ()
Definition at line 4493 of file SceneObject.cpp.
References clientObjectCRC.
Referenced by server::zone::objects::scene::SceneObject::getClientObjectCRC().
int SceneObjectImplementation::getContainedObjectsRecursive ()
Definition at line 1632 of file SceneObjectImplementation.cpp.
References containerLock, containerObjects, server::zone::objects::scene::ContainerObjectsMap::get(), and server::zone::objects::scene::ContainerObjectsMap::size().
Referenced by server::zone::objects::scene::SceneObject::getContainedObjectsRecursive().
ReadWriteLock * SceneObjectImplementation::getContainerLock ()
Definition at line 4725 of file SceneObject.cpp.
References containerLock.
Referenced by server::zone::objects::scene::SceneObject::getContainerLock().
Reference< SceneObject * > SceneObjectImplementation::getContainerObject (int idx)
Definition at line 4603 of file SceneObject.cpp.
References containerObjects.
Referenced by server::zone::objects::installation::factory::FactoryObjectImplementation::createNewObject(), server::zone::objects::cell::CellObjectImplementation::destroyAllPlayerItems(), destroyObjectFromDatabase(), destroyPlayerCreatureFromDatabase(), server::zone::objects::tangible::tool::CraftingToolImplementation::disperseItems(), server::zone::objects::tangible::fishing::FishObjectImplementation::filet(), server::zone::objects::installation::factory::FactoryObjectImplementation::fillAttributeList(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::cell::CellObjectImplementation::getCurrentNumberOfPlayerItems(), server::zone::objects::tangible::firework::FireworkObjectImplementation::getDisplayedUseCount(), server::zone::objects::factorycrate::FactoryCrateImplementation::getPrototype(), server::zone::objects::tangible::tool::CraftingToolImplementation::getPrototype(), server::zone::objects::tangible::tool::CraftingToolImplementation::handleObjectMenuSelect(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleOperateToggle(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleRemoveFactorySchem(), server::zone::objects::cell::CellObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendIngredientsNeededSui(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendInsertManuSui(), and server::zone::objects::installation::factory::FactoryObjectImplementation::startFactory().
Reference< SceneObject * > SceneObjectImplementation::getContainerObject (unsigned long long objectID)
Definition at line 4646 of file SceneObject.cpp.
References containerObjects.
Reference< SceneObject * > SceneObjectImplementation::getContainerObjectRecursive (unsigned long long oid)
Definition at line 1654 of file SceneObjectImplementation.cpp.
References containerLock, containerObjects, server::zone::objects::scene::ContainerObjectsMap::get(), and server::zone::objects::scene::ContainerObjectsMap::size().
Referenced by server::zone::objects::scene::SceneObject::getContainerObjectRecursive().
void server::zone::objects::scene::SceneObjectImplementation::getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > & objects)
Referenced by server::zone::objects::scene::SceneObject::getContainerObjects().
VectorMap< unsigned long long, ManagedReference< SceneObject * > > * SceneObjectImplementation::getContainerObjects ()
Definition at line 4608 of file SceneObject.cpp.
References containerObjects.
Referenced by sendContainerObjectsTo().
int SceneObjectImplementation::getContainerObjectsSize ()
Definition at line 4583 of file SceneObject.cpp.
References containerObjects.
Referenced by server::zone::objects::installation::factory::FactoryObjectImplementation::createNewObject(), server::zone::objects::cell::CellObjectImplementation::destroyAllPlayerItems(), destroyObjectFromDatabase(), destroyPlayerCreatureFromDatabase(), server::zone::objects::tangible::tool::CraftingToolImplementation::disperseItems(), server::zone::objects::tangible::fishing::FishObjectImplementation::filet(), server::zone::objects::tangible::fishing::FishObjectImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::tool::CraftingToolImplementation::fillObjectMenuResponse(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::cell::CellObjectImplementation::getCurrentNumberOfPlayerItems(), server::zone::objects::tangible::firework::FireworkObjectImplementation::getDisplayedUseCount(), server::zone::objects::factorycrate::FactoryCrateImplementation::getPrototype(), server::zone::objects::tangible::tool::CraftingToolImplementation::getPrototype(), server::zone::objects::installation::factory::FactoryObjectImplementation::getRedeedMessage(), server::zone::objects::tangible::fishing::FishObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::CraftingToolImplementation::handleObjectMenuSelect(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleOperateToggle(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleRemoveFactorySchem(), server::zone::objects::tangible::tool::CraftingToolImplementation::initializeTransientMembers(), server::zone::objects::cell::CellObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendIngredientsNeededSui(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendInsertManuSui(), and server::zone::objects::installation::factory::FactoryObjectImplementation::startFactory().
ContainerPermissions * SceneObjectImplementation::getContainerPermissions ()
Definition at line 5090 of file SceneObject.cpp.
References containerPermissions.
Referenced by server::zone::objects::intangible::ControlDeviceImplementation::ControlDeviceImplementation(), and server::zone::objects::scene::SceneObject::getContainerPermissions().
unsigned int SceneObjectImplementation::getContainerType ()
Definition at line 4676 of file SceneObject.cpp.
References containerType.
Referenced by server::zone::objects::tangible::ContainerImplementation::canAddObject(), and server::zone::objects::scene::SceneObject::getContainerType().
unsigned int SceneObjectImplementation::getContainerVolumeLimit ()
Definition at line 4598 of file SceneObject.cpp.
References containerVolumeLimit.
Referenced by server::zone::objects::tangible::ContainerImplementation::canAddObject(), and server::zone::objects::scene::SceneObject::getContainerVolumeLimit().
unsigned int SceneObjectImplementation::getContainmentType ()
Definition at line 4696 of file SceneObject.cpp.
References containmentType.
Referenced by server::zone::objects::scene::SceneObject::getContainmentType().
Vector3 SceneObjectImplementation::getCoordinate (float distance, float angleDegrees)
Definition at line 1299 of file SceneObjectImplementation.cpp.
References direction, server::zone::Zone::getHeight(), and getZone().
Referenced by server::zone::objects::scene::SceneObject::getCoordinate().
int SceneObjectImplementation::getCountableObjectsRecursive () virtual
Reimplemented in server::zone::objects::factorycrate::FactoryCrateImplementation.
Definition at line 1616 of file SceneObjectImplementation.cpp.
References containerLock, containerObjects, server::zone::objects::scene::ContainerObjectsMap::get(), and server::zone::objects::scene::ContainerObjectsMap::size().
Referenced by server::zone::objects::tangible::ContainerImplementation::canAddObject(), and server::zone::objects::scene::SceneObject::getCountableObjectsRecursive().
UnicodeString SceneObjectImplementation::getCustomObjectName ()
Definition at line 4730 of file SceneObject.cpp.
References customName.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::createFactoryCrate(), server::zone::objects::creature::CreatureObjectImplementation::getCreatureName(), server::zone::objects::scene::SceneObject::getCustomObjectName(), server::zone::objects::creature::CreatureObjectImplementation::getFirstName(), server::zone::objects::creature::CreatureObjectImplementation::getLastName(), server::zone::objects::tangible::ContainerImplementation::handleObjectMenuSelect(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendInsertManuSui(), server::zone::objects::factorycrate::FactoryCrateImplementation::split(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::updateCraftingValues().
DataObjectComponentReference * SceneObjectImplementation::getDataObjectComponent ()
Definition at line 4790 of file SceneObject.cpp.
References dataObjectComponent.
Referenced by server::zone::objects::scene::SceneObject::getDataObjectComponent().
String SceneObjectImplementation::getDetailedDescription () virtual
Reimplemented in server::zone::objects::waypoint::WaypointObjectImplementation.
Definition at line 4523 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::scene::SceneObject::getDetailedDescription().
Quaternion * SceneObjectImplementation::getDirection ()
Definition at line 1253 of file SceneObjectImplementation.cpp.
References direction.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::scene::SceneObject::getDirection(), and server::zone::objects::building::BuildingObjectImplementation::spawnChildCreaturesFromTemplate().
float SceneObjectImplementation::getDirectionAngle ()
Definition at line 4701 of file SceneObject.cpp.
References direction.
Referenced by server::zone::objects::scene::SceneObject::getDirectionAngle().
float SceneObjectImplementation::getDirectionW ()
Definition at line 4488 of file SceneObject.cpp.
References direction.
Referenced by server::zone::objects::scene::SceneObject::getDirectionW().
float SceneObjectImplementation::getDirectionX ()
Definition at line 4473 of file SceneObject.cpp.
References direction.
Referenced by server::zone::objects::scene::SceneObject::getDirectionX().
float SceneObjectImplementation::getDirectionY ()
Definition at line 4483 of file SceneObject.cpp.
References direction.
Referenced by server::zone::objects::scene::SceneObject::getDirectionY().
float SceneObjectImplementation::getDirectionZ ()
Definition at line 4478 of file SceneObject.cpp.
References direction.
Referenced by server::zone::objects::scene::SceneObject::getDirectionZ().
String SceneObjectImplementation::getDisplayedName ()
Definition at line 1598 of file SceneObjectImplementation.cpp.
References customName, server::zone::objects::scene::variables::StringId::getFullPath(), and objectName.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::createFactoryBlueprint(), server::zone::objects::installation::factory::FactoryObjectImplementation::createNewFactoryCrate(), server::zone::objects::installation::factory::FactoryObjectImplementation::createNewObject(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::decreasePowerupUses(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleOperateToggle(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), server::zone::objects::creature::VehicleObjectImplementation::sendRepairConfirmTo(), server::zone::objects::tangible::sign::SignObjectImplementation::sendSignNameTo(), and server::zone::objects::installation::factory::FactoryObjectImplementation::stopFactory().
float SceneObjectImplementation::getDistanceTo (SceneObject * object)
Definition at line 1231 of file SceneObjectImplementation.cpp.
References server::zone::objects::scene::SceneObject::getWorldPositionX(), getWorldPositionX(), server::zone::objects::scene::SceneObject::getWorldPositionY(), and getWorldPositionY().
Referenced by server::zone::objects::scene::SceneObject::getDistanceTo(), and server::zone::objects::creature::AiAgentImplementation::selectWeapon().
float SceneObjectImplementation::getDistanceTo (Coordinate * coordinate)
Definition at line 1242 of file SceneObjectImplementation.cpp.
References getWorldPositionX(), and getWorldPositionY().
unsigned int SceneObjectImplementation::getGameObjectType ()
Definition at line 4686 of file SceneObject.cpp.
References gameObjectType.
Referenced by server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::calculateSuccessRate(), server::zone::objects::tangible::TangibleObjectImplementation::canRepair(), server::zone::objects::tangible::TangibleObjectImplementation::createFactoryCrate(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::fillAttributeList(), server::zone::objects::scene::SceneObject::getGameObjectType(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getWeaponType(), and server::zone::objects::tangible::TangibleObjectImplementation::repair().
Zone * SceneObjectImplementation::getLocalZone ()
Definition at line 4468 of file SceneObject.cpp.
References zone.
Referenced by server::zone::objects::scene::SceneObject::getLocalZone().
String SceneObjectImplementation::getLoggingName ()
Definition at line 4735 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::getLoggingName(), server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData(), and server::zone::objects::creature::AiAgentImplementation::loadTemplateData().
unsigned int SceneObjectImplementation::getMovementCounter ()
Definition at line 4711 of file SceneObject.cpp.
References movementCounter.
Referenced by server::zone::objects::scene::SceneObject::getMovementCounter().
VectorMap< unsigned int, ManagedReference< Facade * > > * SceneObjectImplementation::getObjectActiveSessions ()
Definition at line 4348 of file SceneObject.cpp.
References objectActiveSessions.
Referenced by server::zone::objects::scene::SceneObject::getObjectActiveSessions().
uint64 SceneObjectImplementation::getObjectID ()
Definition at line 388 of file SceneObjectImplementation.cpp.
References _this.
Referenced by server::zone::objects::building::BuildingObjectImplementation::addCell(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::checkJoin(), compareTo(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), createChildObjects(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::createSellJunkLootSelection(), destroyObjectFromDatabase(), destroyPlayerCreatureFromDatabase(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::ship::ShipObjectImplementation::getUniqueID(), server::zone::objects::installation::GeneratorObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::deed::structure::StructureDeedImplementation::handleObjectMenuSelect(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::ticket::TicketObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::InstrumentImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::objects::creature::AiAgentImplementation::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObjectImplementation::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObjectImplementation::initializeTransientMembers(), server::zone::objects::waypoint::WaypointObjectImplementation::insertToMessage(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::selectConversationOption(), server::zone::objects::cell::CellObjectImplementation::sendBaselinesTo(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendBaselinesTo(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationStartTo(), server::zone::objects::creature::AiAgentImplementation::sendConversationStartTo(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationTerminate(), server::zone::objects::cell::CellObjectImplementation::sendPermissionsTo(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendTo(), server::zone::objects::group::GroupObjectImplementation::startChatRoom(), and server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::updateCharges().
ObjectMenuComponent * SceneObjectImplementation::getObjectMenuComponent ()
Definition at line 4785 of file SceneObject.cpp.
References objectMenuComponent.
Referenced by server::zone::objects::scene::SceneObject::getObjectMenuComponent().
StringId * SceneObjectImplementation::getObjectName ()
Definition at line 4508 of file SceneObject.cpp.
References objectName.
Referenced by server::zone::objects::scene::SceneObject::getObjectName().
String SceneObjectImplementation::getObjectNameStringIdFile ()
Definition at line 4513 of file SceneObject.cpp.
References objectName.
Referenced by server::zone::objects::scene::SceneObject::getObjectNameStringIdFile().
String SceneObjectImplementation::getObjectNameStringIdName ()
Definition at line 4518 of file SceneObject.cpp.
References objectName.
Referenced by server::zone::objects::building::BuildingObjectImplementation::addCell(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::draftschematic::DraftSchematicImplementation::createManufactureSchematic(), server::zone::objects::scene::SceneObject::getObjectNameStringIdName(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::selectConversationOption(), and server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationStartTo().
SharedObjectTemplate * SceneObjectImplementation::getObjectTemplate ()
Definition at line 5288 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::installation::InstallationObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::structure::StructureObjectImplementation::getBaseMaintenanceRate(), server::zone::objects::structure::StructureObjectImplementation::getBasePowerRate(), server::zone::objects::installation::InstallationObjectImplementation::getHitChance(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::building::BuildingObjectImplementation::hasTemplateChildCreatures(), server::zone::objects::building::BuildingObjectImplementation::initializeTransientMembers(), server::zone::objects::creature::VehicleObjectImplementation::notifyInsertToZone(), and server::zone::objects::building::BuildingObjectImplementation::spawnChildCreaturesFromTemplate().
SortedVector< ManagedReference< Observer * > > SceneObjectImplementation::getObservers (unsigned int eventType)
The returning value points directly to the internal vector, do not delete it or store it
Definition at line 1578 of file SceneObjectImplementation.cpp.
Referenced by server::zone::objects::scene::SceneObject::getObservers(), server::zone::objects::creature::CreatureObjectImplementation::notifyPostureChange(), and server::zone::objects::creature::AiAgentImplementation::sendConversationStartTo().
ManagedWeakReference< SceneObject * > SceneObjectImplementation::getParent ()
Definition at line 1565 of file SceneObjectImplementation.cpp.
References _this, and parentLock.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addFriend(), server::zone::objects::player::PlayerObjectImplementation::addIgnore(), server::zone::objects::player::PlayerObjectImplementation::addPermissionGroup(), server::zone::objects::tangible::ContainerImplementation::canAddObject(), server::zone::objects::cell::CellObjectImplementation::canAddObject(), server::zone::objects::tangible::InstrumentImplementation::canDropInstrument(), server::zone::objects::creature::AiAgentImplementation::checkNewAngle(), server::zone::objects::cell::CellObjectImplementation::destroyAllPlayerItems(), server::zone::objects::tangible::tool::CraftingToolImplementation::disperseItems(), server::zone::objects::creature::AiAgentImplementation::doMovement(), server::zone::objects::factorycrate::FactoryCrateImplementation::extractObject(), server::zone::objects::factorycrate::FactoryCrateImplementation::extractObjectToParent(), server::zone::objects::tangible::tool::CraftingToolImplementation::fillAttributeList(), server::zone::objects::tangible::ContainerImplementation::fillObjectMenuResponse(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), server::zone::objects::cell::CellObjectImplementation::getCurrentNumberOfPlayerItems(), server::zone::objects::scene::SceneObject::getParent(), getParentRecursively(), getRootParent(), getZone(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::ContainerImplementation::handleObjectMenuSelect(), isASubChildOf(), server::zone::objects::tangible::wearables::WearableContainerObjectImplementation::isEquipped(), server::zone::objects::tangible::wearables::WearableObjectImplementation::isEquipped(), server::zone::objects::player::PlayerObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::player::PlayerObjectImplementation::notifyOnline(), server::zone::objects::player::PlayerObjectImplementation::removeFriend(), server::zone::objects::player::PlayerObjectImplementation::removeIgnore(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::removeObject(), server::zone::objects::player::PlayerObjectImplementation::removePermissionGroup(), server::zone::objects::creature::CreatureImplementation::runAway(), server::zone::objects::player::PlayerObjectImplementation::sendBadgesResponseTo(), server::zone::objects::cell::CellObjectImplementation::sendBaselinesTo(), server::zone::objects::creature::AiAgentImplementation::sendConversationStartTo(), server::zone::objects::player::PlayerObjectImplementation::sendFriendLists(), server::zone::objects::player::PlayerObjectImplementation::sendMessage(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendTo(), server::zone::objects::player::PlayerObjectImplementation::setDrinkFilling(), server::zone::objects::player::PlayerObjectImplementation::setFactionStatus(), server::zone::objects::player::PlayerObjectImplementation::setFoodFilling(), server::zone::objects::player::PlayerObjectImplementation::setLanguageID(), server::zone::objects::creature::aigroup::AiGroupImplementation::setPatrolPoint(), server::zone::objects::resource::ResourceContainerImplementation::setQuantity(), server::zone::objects::creature::CreatureObjectImplementation::setState(), server::zone::objects::factorycrate::FactoryCrateImplementation::split(), server::zone::objects::player::PlayerObjectImplementation::unloadSpawnedChildren(), server::zone::objects::player::PlayerObjectImplementation::updateBountyPvpStatus(), server::zone::objects::intangible::IntangibleObjectImplementation::updateStatus(), and updateVehiclePosition().
unsigned long long SceneObjectImplementation::getParentID ()
Returns the object id of the parent of this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns 0 if this object doesnt have a parent, otherwise returns its object id
Definition at line 4240 of file SceneObject.cpp.
References parentLock.
Referenced by server::zone::objects::scene::SceneObject::getParentID().
ManagedWeakReference< SceneObject * > SceneObjectImplementation::getParentRecursively (unsigned int gameObjectType)
Returns the parent of object type in the tree
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
Returns the parent of object type in the tree
Definition at line 1175 of file SceneObjectImplementation.cpp.
References _this, gameObjectType, and getParent().
Referenced by server::zone::objects::tangible::ContainerImplementation::canAddObject(), server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation::fillObjectMenuResponse(), server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::tangible::loot::LootkitObjectImplementation::getPlayer(), server::zone::objects::player::PlayerObjectImplementation::removeSchematics(), server::zone::objects::mission::MissionObjectImplementation::setCreatorName(), server::zone::objects::mission::MissionObjectImplementation::setEndPosition(), server::zone::objects::mission::MissionObjectImplementation::setMissionDescription(), server::zone::objects::mission::MissionObjectImplementation::setMissionDifficulty(), server::zone::objects::mission::MissionObjectImplementation::setMissionTargetName(), server::zone::objects::mission::MissionObjectImplementation::setMissionTitle(), server::zone::objects::mission::MissionObjectImplementation::setRefreshCounter(), server::zone::objects::mission::MissionObjectImplementation::setRewardCredits(), server::zone::objects::mission::MissionObjectImplementation::setStartPosition(), server::zone::objects::mission::MissionObjectImplementation::setTargetTemplate(), server::zone::objects::mission::MissionObjectImplementation::setTypeCRC(), and server::zone::objects::mission::MissionObjectImplementation::updateMissionLocation().
Reference< Task * > SceneObjectImplementation::getPendingTask (const String & name)
Looks up a specific pending tasks by the name
Precondition
{ this locked }
Postcondition
{ this locked }
Parameters
name Name of the task to lookup
Definition at line 4299 of file SceneObject.cpp.
References containerLock, and pendingTasks.
Referenced by server::zone::objects::installation::factory::FactoryObjectImplementation::createNewObject(), server::zone::objects::scene::SceneObject::getPendingTask(), server::zone::objects::creature::CreatureObjectImplementation::queueDizzyFallEvent(), server::zone::objects::creature::CreatureImplementation::scheduleDespawn(), server::zone::objects::creature::AiAgentImplementation::scheduleDespawn(), server::zone::objects::creature::CreatureObjectImplementation::setCombatState(), server::zone::objects::installation::factory::FactoryObjectImplementation::stopFactory(), and server::zone::objects::building::BuildingObjectImplementation::updatePaidAccessList().
PendingTasksMap * SceneObjectImplementation::getPendingTasks ()
Definition at line 4278 of file SceneObject.cpp.
References containerLock, and pendingTasks.
Referenced by addPendingTask(), and server::zone::objects::scene::SceneObject::getPendingTasks().
uint32 SceneObjectImplementation::getPlanetCRC () virtual
Reimplemented in server::zone::objects::resource::ResourceSpawnImplementation, and server::zone::objects::waypoint::WaypointObjectImplementation.
Definition at line 1363 of file SceneObjectImplementation.cpp.
References getZone(), and server::zone::Zone::getZoneCRC().
Referenced by server::zone::objects::scene::SceneObject::getPlanetCRC().
PlanetMapCategory * SceneObjectImplementation::getPlanetMapCategory ()
Definition at line 5264 of file SceneObject.cpp.
References TemplateManager::getPlanetMapCategoryByCrc(), and planetMapCategory.
Referenced by server::zone::objects::scene::SceneObject::getPlanetMapCategory().
int SceneObjectImplementation::getPlanetMapCategoryCRC ()
Definition at line 5240 of file SceneObject.cpp.
References planetMapCategory.
Referenced by server::zone::objects::scene::SceneObject::getPlanetMapCategoryCRC().
PlanetMapCategory * SceneObjectImplementation::getPlanetMapSubCategory ()
Definition at line 5271 of file SceneObject.cpp.
References TemplateManager::getPlanetMapCategoryByCrc(), and planetMapSubCategory.
Referenced by server::zone::objects::scene::SceneObject::getPlanetMapSubCategory().
int SceneObjectImplementation::getPlanetMapSubCategoryCRC ()
Definition at line 5245 of file SceneObject.cpp.
References planetMapSubCategory.
Referenced by server::zone::objects::scene::SceneObject::getPlanetMapSubCategoryCRC().
ManagedWeakReference< SceneObject * > SceneObjectImplementation::getRootParent ()
Returns the parent of all children in the object tree
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns the parent of all children in the object tree
Definition at line 1148 of file SceneObjectImplementation.cpp.
References _this, and getParent().
Referenced by broadcastDestroyPrivate(), broadcastMessagePrivate(), broadcastMessagesPrivate(), broadcastObjectPrivate(), server::zone::objects::tangible::ContainerImplementation::canAddObject(), server::zone::objects::scene::SceneObject::getRootParent(), getWorldPosition(), getZone(), server::zone::objects::ship::ShipObjectImplementation::sendBaselinesTo(), and server::zone::objects::creature::CreatureObjectImplementation::sendToOwner().
unsigned int SceneObjectImplementation::getServerObjectCRC ()
Definition at line 4498 of file SceneObject.cpp.
References serverObjectCRC.
Referenced by server::zone::objects::scene::SceneObject::getServerObjectCRC(), and server::zone::objects::factorycrate::FactoryCrateImplementation::split().
String SceneObjectImplementation::getSlotDescriptor (int idx)
Definition at line 4546 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::scene::SceneObject::getSlotDescriptor(), and hasSlotDescriptor().
int SceneObjectImplementation::getSlotDescriptorSize ()
Definition at line 4575 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::scene::SceneObject::getSlotDescriptorSize(), and hasSlotDescriptor().
Reference< SceneObject * > SceneObjectImplementation::getSlottedObject (const String & slot)
Definition at line 1489 of file SceneObjectImplementation.cpp.
References containerLock, and slottedObjects.
Referenced by server::zone::objects::creature::CreatureImplementation::canHarvestMe(), server::zone::objects::installation::factory::FactoryObjectImplementation::closeHopper(), server::zone::objects::installation::factory::FactoryObjectImplementation::createNewFactoryCrate(), destroyObjectFromDatabase(), destroyPlayerCreatureFromDatabase(), server::zone::objects::tangible::tool::CraftingToolImplementation::disperseItems(), server::zone::objects::installation::factory::FactoryObjectImplementation::fillAttributeList(), server::zone::objects::creature::CreatureObjectImplementation::getActorObject(), server::zone::objects::tangible::tool::CraftingToolImplementation::getManufactureSchematic(), server::zone::objects::creature::CreatureObjectImplementation::getPlayerObject(), server::zone::objects::installation::factory::FactoryObjectImplementation::getRedeedMessage(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::creature::AiAgentImplementation::hasLoot(), server::zone::objects::installation::factory::FactoryObjectImplementation::initializeTransientMembers(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), server::zone::objects::installation::factory::FactoryObjectImplementation::locateCrateInOutputHopper(), server::zone::objects::creature::AiAgentImplementation::notifyDespawn(), server::zone::objects::installation::factory::FactoryObjectImplementation::openHopper(), server::zone::objects::installation::factory::FactoryObjectImplementation::populateSchematicBlueprint(), server::zone::objects::creature::AiAgentImplementation::selectWeapon(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::sendContainerTo(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendIngredientHopper(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendOutputHopper(), server::zone::objects::creature::CreatureObjectImplementation::sendSlottedObjectsTo(), and server::zone::objects::creature::AiAgentImplementation::setLevel().
Reference< SceneObject * > SceneObjectImplementation::getSlottedObject (int idx)
Definition at line 1510 of file SceneObjectImplementation.cpp.
References containerLock, and slottedObjects.
void SceneObjectImplementation::getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > & objects)
Fills the specified vector with the containment objects of this object
Precondition
{ this obejct is locked }
Postcondition
{ this object is locked, objects is a vector map with the contained objects and their occupied slots }
Parameters
objects the vector map that will contain the objects and their occupied slots
Definition at line 1467 of file SceneObjectImplementation.cpp.
References containerLock, lock(), and slottedObjects.
Referenced by server::zone::objects::scene::SceneObject::getSlottedObjects().
VectorMap< String, ManagedReference< SceneObject * > > * SceneObjectImplementation::getSlottedObjects ()
Definition at line 4570 of file SceneObject.cpp.
References slottedObjects.
Referenced by sendSlottedObjectsTo().
int SceneObjectImplementation::getSlottedObjectsSize ()
Definition at line 4588 of file SceneObject.cpp.
References slottedObjects.
Referenced by destroyObjectFromDatabase(), destroyPlayerCreatureFromDatabase(), server::zone::objects::scene::SceneObject::getSlottedObjectsSize(), and server::zone::objects::creature::CreatureObjectImplementation::sendSlottedObjectsTo().
float SceneObjectImplementation::getSpecialDirectionAngle ()
Definition at line 4706 of file SceneObject.cpp.
References direction.
Referenced by server::zone::objects::scene::SceneObject::getSpecialDirectionAngle().
Matrix4 * SceneObjectImplementation::getTransformForCollisionMatrix ()
Definition at line 5293 of file SceneObject.cpp.
References transformForCollisionMatrix.
Referenced by server::zone::objects::scene::SceneObject::getTransformForCollisionMatrix().
Vector3 SceneObjectImplementation::getWorldCoordinate (float distance, float angleDegrees)
Definition at line 1310 of file SceneObjectImplementation.cpp.
References direction, server::zone::Zone::getHeight(), getWorldPositionX(), getWorldPositionY(), and getZone().
Referenced by server::zone::objects::scene::SceneObject::getWorldCoordinate().
Vector3 SceneObjectImplementation::getWorldPosition () virtual
Definition at line 1278 of file SceneObjectImplementation.cpp.
References getRootParent().
Referenced by server::zone::objects::building::BuildingObjectImplementation::addCell(), server::zone::objects::creature::AiAgentImplementation::doMovement(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), server::zone::objects::building::BuildingObjectImplementation::getEjectionPoint(), server::zone::objects::scene::SceneObject::getWorldPosition(), and isInRange().
float SceneObjectImplementation::getWorldPositionX () virtual
Definition at line 1321 of file SceneObjectImplementation.cpp.
Referenced by getDistanceTo(), getWorldCoordinate(), server::zone::objects::scene::SceneObject::getWorldPositionX(), and server::zone::objects::creature::CreatureObjectImplementation::setState().
float SceneObjectImplementation::getWorldPositionY () virtual
Definition at line 1336 of file SceneObjectImplementation.cpp.
Referenced by getDistanceTo(), getWorldCoordinate(), server::zone::objects::scene::SceneObject::getWorldPositionY(), and server::zone::objects::creature::CreatureObjectImplementation::setState().
float SceneObjectImplementation::getWorldPositionZ () virtual
Definition at line 1351 of file SceneObjectImplementation.cpp.
Referenced by server::zone::objects::scene::SceneObject::getWorldPositionZ().
Zone * SceneObjectImplementation::getZone ()
Definition at line 4445 of file SceneObject.cpp.
References getParent(), getRootParent(), and zone.
Referenced by server::zone::objects::creature::AiAgentImplementation::activateMovementEvent(), server::zone::objects::creature::AiAgentImplementation::activateWaitEvent(), server::zone::objects::installation::InstallationObjectImplementation::broadcastMessage(), server::zone::objects::tangible::TangibleObjectImplementation::broadcastPvpStatusBitmask(), server::zone::objects::installation::garage::GarageInstallationImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), createChildObjects(), server::zone::objects::intangible::VehicleControlDeviceImplementation::destroyObjectFromDatabase(), server::zone::objects::creature::CreatureObjectImplementation::destroyObjectFromWorld(), server::zone::objects::creature::AiAgentImplementation::doMovement(), server::zone::objects::creature::AiAgentImplementation::doRecovery(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), getCoordinate(), getPlanetCRC(), server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation::getPlanetTravelPoint(), server::zone::objects::area::SpawnAreaImplementation::getRandomPosition(), getWorldCoordinate(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::InstrumentImplementation::handleObjectMenuSelect(), inRangeObjects(), server::zone::objects::creature::VehicleObjectImplementation::isAttackableBy(), server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy(), isInWater(), server::zone::objects::area::FsVillageAreaImplementation::notifyEnter(), server::zone::objects::creature::AiAgentImplementation::notifyObjectDestructionObservers(), server::zone::objects::creature::CreatureObjectImplementation::notifyObjectDestructionObservers(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToZone(), server::zone::objects::creature::CreatureObjectImplementation::notifySelfPositionUpdate(), server::zone::objects::building::BuildingObjectImplementation::onEnter(), server::zone::objects::building::BuildingObjectImplementation::onExit(), server::zone::objects::creature::AiAgentImplementation::respawn(), server::zone::objects::creature::CreatureImplementation::runAway(), server::zone::objects::creature::CreatureObjectImplementation::sendBaselinesTo(), server::zone::objects::installation::InstallationObjectImplementation::setActiveResource(), server::zone::objects::installation::InstallationObjectImplementation::setOperating(), server::zone::objects::creature::aigroup::AiGroupImplementation::setPatrolPoint(), server::zone::objects::creature::CreatureObjectImplementation::setState(), server::zone::objects::creature::aigroup::AiGroupImplementation::setup(), server::zone::objects::area::DynamicSpawnAreaImplementation::spawnCreature(), server::zone::objects::area::StaticSpawnAreaImplementation::spawnCreatures(), server::zone::objects::installation::GeneratorObjectImplementation::synchronizedUIListen(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::synchronizedUIListen(), server::zone::objects::cell::CellObjectImplementation::transferObject(), server::zone::objects::area::LairSpawnAreaImplementation::trySpawnLair(), server::zone::objects::creature::AiAgentImplementation::updateCurrentPosition(), and server::zone::objects::installation::InstallationObjectImplementation::updateHopper().
ZoneComponent * SceneObjectImplementation::getZoneComponent ()
Definition at line 4780 of file SceneObject.cpp.
References zoneComponent.
Referenced by server::zone::objects::scene::SceneObject::getZoneComponent(), and server::zone::objects::structure::StructureObjectImplementation::isCityHall().
ZoneProcessServer * SceneObjectImplementation::getZoneProcessServer ()
Definition at line 5155 of file SceneObject.cpp.
References server.
Referenced by server::zone::objects::scene::SceneObject::getZoneProcessServer(), and server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData().
ZoneServer * SceneObjectImplementation::getZoneServer ()
Definition at line 4716 of file SceneObject.cpp.
References server.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::activateImmediateAction(), server::zone::objects::creature::CreatureObjectImplementation::activateQueueAction(), server::zone::objects::player::PlayerObjectImplementation::addWaypoint(), server::zone::objects::player::PlayerObjectImplementation::awardBadge(), broadcastDestroyPrivate(), broadcastMessagePrivate(), broadcastMessagesPrivate(), broadcastObjectPrivate(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::calculatePower(), server::zone::objects::installation::InstallationObjectImplementation::changeActiveResourceID(), server::zone::objects::building::BuildingObjectImplementation::createCellObjects(), server::zone::objects::installation::InstallationObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::tangible::TangibleObjectImplementation::createFactoryCrate(), server::zone::objects::draftschematic::DraftSchematicImplementation::createManufactureSchematic(), server::zone::objects::resource::ResourceSpawnImplementation::createResource(), server::zone::objects::mission::MissionObjectImplementation::createWaypoint(), server::zone::objects::installation::InstallationObjectImplementation::destroyObjectFromDatabase(), server::zone::objects::building::BuildingObjectImplementation::destroyObjectFromDatabase(), destroyObjectFromDatabase(), server::zone::objects::player::PlayerObjectImplementation::destroyObjectFromDatabase(), destroyPlayerCreatureFromDatabase(), server::zone::objects::player::PlayerObjectImplementation::doRecovery(), server::zone::objects::creature::CreatureObjectImplementation::enqueueCommand(), server::zone::objects::creature::CreatureObjectImplementation::executeObjectControllerAction(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), server::zone::objects::intangible::ShipControlDeviceImplementation::generateObject(), server::zone::objects::player::PlayerObjectImplementation::getLotsRemaining(), server::zone::objects::structure::StructureObjectImplementation::getOwnerCreatureObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::AiAgentImplementation::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObjectImplementation::handleObjectMenuSelect(), server::zone::objects::installation::InstallationObjectImplementation::handleStructureAddEnergy(), server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::creature::CreatureObjectImplementation::notifyObjectDestructionObservers(), server::zone::objects::player::PlayerObjectImplementation::notifySceneReady(), server::zone::objects::building::BuildingObjectImplementation::spawnChildSceneObject(), server::zone::objects::intangible::VehicleControlDeviceImplementation::spawnObject(), and server::zone::objects::player::PlayerObjectImplementation::unload().
int SceneObjectImplementation::handleObjectMenuSelect (CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player CreatureObject that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::creature::AiAgentImplementation, server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation, server::zone::objects::creature::VehicleObjectImplementation, server::zone::objects::tangible::tool::CraftingToolImplementation, server::zone::objects::tangible::consumable::ConsumableImplementation, server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation, server::zone::objects::tangible::wearables::ArmorObjectImplementation, server::zone::objects::tangible::tool::recycle::RecycleToolImplementation, server::zone::objects::tangible::InstrumentImplementation, server::zone::objects::tangible::pharmaceutical::DotPackImplementation, server::zone::objects::creature::CreatureImplementation, server::zone::objects::tangible::pharmaceutical::WoundPackImplementation, server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation, server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation, server::zone::objects::factorycrate::FactoryCrateImplementation, server::zone::objects::tangible::pharmaceutical::RevivePackImplementation, server::zone::objects::tangible::pharmaceutical::StimPackImplementation, server::zone::objects::intangible::VehicleControlDeviceImplementation, server::zone::objects::tangible::pharmaceutical::CurePackImplementation, server::zone::objects::tangible::pharmaceutical::StatePackImplementation, server::zone::objects::tangible::tool::SurveyToolImplementation, server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation, server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, server::zone::objects::tangible::fishing::FishObjectImplementation, server::zone::objects::tangible::fishing::FishingPoleObjectImplementation, server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation, server::zone::objects::tangible::ticket::TicketObjectImplementation, server::zone::objects::tangible::ContainerImplementation, server::zone::objects::tangible::deed::pet::PetDeedImplementation, server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation, server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation, server::zone::objects::tangible::deed::ResourceDeedImplementation, server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation, server::zone::objects::installation::harvester::HarvesterObjectImplementation, server::zone::objects::tangible::deed::structure::StructureDeedImplementation, server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation, server::zone::objects::tangible::terminal::ticketcollector::TicketCollectorImplementation, server::zone::objects::installation::GeneratorObjectImplementation, server::zone::objects::tangible::terminal::startinglocation::StartingLocationTerminalImplementation, server::zone::objects::tangible::sign::SignObjectImplementation, server::zone::objects::intangible::ShipControlDeviceImplementation, and server::zone::objects::tangible::terminal::spaceship::SpaceshipTerminalImplementation.
Definition at line 1270 of file SceneObjectImplementation.cpp.
References _this, and objectMenuComponent.
Referenced by server::zone::objects::tangible::sign::SignObjectImplementation::handleObjectMenuSelect(), server::zone::objects::installation::GeneratorObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::ContainerImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::SurveyToolImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::recycle::RecycleToolImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::CraftingToolImplementation::handleObjectMenuSelect(), and server::zone::objects::scene::SceneObject::handleObjectMenuSelect().
bool SceneObjectImplementation::hasActiveArea (ActiveArea * area)
Definition at line 4372 of file SceneObject.cpp.
References activeAreas, and containerLock.
Referenced by server::zone::objects::scene::SceneObject::hasActiveArea().
bool SceneObjectImplementation::hasActiveArea (unsigned long long objectid)
Definition at line 4381 of file SceneObject.cpp.
References activeAreas, and containerLock.
bool SceneObjectImplementation::hasArrangementDescriptor (const String & descr)
Definition at line 4565 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::scene::SceneObject::hasArrangementDescriptor(), and server::zone::objects::tangible::wearables::ArmorObjectImplementation::loadTemplateData().
bool SceneObjectImplementation::hasFullContainerObjects ()
Definition at line 4593 of file SceneObject.cpp.
References containerObjects, and containerVolumeLimit.
Referenced by server::zone::objects::scene::SceneObject::hasFullContainerObjects().
bool SceneObjectImplementation::hasObjectInContainer (unsigned long long objectID)
Definition at line 4613 of file SceneObject.cpp.
References containerObjects.
Referenced by server::zone::objects::tangible::loot::LootkitObjectImplementation::addToKit(), and server::zone::objects::scene::SceneObject::hasObjectInContainer().
bool SceneObjectImplementation::hasObjectInSlottedContainer (SceneObject * object)
Definition at line 4618 of file SceneObject.cpp.
References containerLock, server::zone::objects::scene::SceneObject::getArrangementDescriptor(), and slottedObjects.
Referenced by server::zone::objects::scene::SceneObject::hasObjectInSlottedContainer().
bool SceneObjectImplementation::hasSlotDescriptor (const String & descr)
Definition at line 4551 of file SceneObject.cpp.
References getSlotDescriptor(), and getSlotDescriptorSize().
Referenced by server::zone::objects::scene::SceneObject::hasSlotDescriptor().
void SceneObjectImplementation::incrementMovementCounter ()
Definition at line 5175 of file SceneObject.cpp.
References movementCounter.
Referenced by server::zone::objects::scene::SceneObject::incrementMovementCounter().
void SceneObjectImplementation::info (const String & msg, bool forced = false)
Logs an info message
Precondition
{}
Postcondition
{ message has been printed to console or file }
Parameters
msg message to print
forced if true, always prints the message to console
Definition at line 4158 of file SceneObject.cpp.
Referenced by server::zone::objects::creature::AiAgentImplementation::activateAwarenessEvent(), server::zone::objects::building::BuildingObjectImplementation::addCell(), server::zone::objects::installation::InstallationObjectImplementation::changeActiveResourceID(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::checkJoin(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), createComponents(), server::zone::objects::player::PlayerObjectImplementation::disconnect(), server::zone::objects::player::PlayerObjectImplementation::doRecovery(), server::zone::objects::tangible::terminal::startinglocation::StartingLocationTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::scene::SceneObject::info(), server::zone::objects::player::PlayerObjectImplementation::logout(), server::zone::objects::resource::ResourceSpawnImplementation::print(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefender(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::selectConversationOption(), server::zone::objects::intangible::IntangibleObjectImplementation::sendBaselinesTo(), server::zone::objects::resource::ResourceContainerImplementation::sendBaselinesTo(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::sendBaselinesTo(), server::zone::objects::tangible::TangibleObjectImplementation::sendBaselinesTo(), server::zone::objects::player::PlayerObjectImplementation::sendBaselinesTo(), server::zone::objects::building::BuildingObjectImplementation::sendDestroyTo(), server::zone::objects::player::PlayerObjectImplementation::sendFriendLists(), setContainerComponent(), setObjectMenuComponent(), server::zone::objects::player::PlayerObjectImplementation::unload(), and server::zone::ZoneImplementation::updateCityRegions().
void SceneObjectImplementation::initializeChildObject (SceneObject * controllerObject) virtual
This method initializes "this" object as if it were a "childObject" of the controller object that is passed as an argument to the method. NOTE: The controllerObject is not necessarily the "parent" of the child object. The childObject just happens to be specified in the controllerObject's childObjects vector.
Parameters
controllerObject The object that has this object specified as a "childObject".
Reimplemented in server::zone::objects::tangible::terminal::TerminalImplementation, and server::zone::objects::tangible::sign::SignObjectImplementation.
Definition at line 1556 of file SceneObjectImplementation.cpp.
Referenced by server::zone::objects::scene::SceneObject::initializeChildObject().
void SceneObjectImplementation::initializePrivateData ()
Definition at line 133 of file SceneObjectImplementation.cpp.
References childObjects, clientObjectCRC, containmentType, gameObjectType, movementCounter, objectActiveSessions, pendingTasks, planetMapCategory, planetMapSubCategory, sendToClient, server, serverObjectCRC, setLoggingName(), staticObject, templateObject, and zone.
Referenced by server::zone::objects::scene::SceneObject::initializePrivateData(), and SceneObjectImplementation().
void SceneObjectImplementation::initializeTransientMembers ()
Initializes the transient members of SceneObject, must call the inherited object method first.
Precondition
{transient members are not initialized }
Postcondition
{ transient members are initialized }
Definition at line 97 of file SceneObjectImplementation.cpp.
References _this, containerComponent, dataObjectComponent, movementCounter, objectMenuComponent, server, serverObjectCRC, setLoggingName(), templateObject, and zoneComponent.
Referenced by server::zone::objects::scene::SceneObject::initializeTransientMembers(), server::zone::objects::creature::aigroup::PackGroupImplementation::readObject(), server::zone::objects::creature::aigroup::HerdGroupImplementation::readObject(), server::zone::objects::creature::aigroup::LairGroupImplementation::readObject(), server::zone::objects::area::GarageAreaImplementation::readObject(), server::zone::objects::area::FsVillageAreaImplementation::readObject(), server::zone::objects::staticobject::StaticObjectImplementation::readObject(), server::zone::objects::area::BadgeActiveAreaImplementation::readObject(), server::zone::objects::area::MissionSpawnActiveAreaImplementation::readObject(), server::zone::objects::area::MissionReconActiveAreaImplementation::readObject(), server::zone::objects::area::StaticSpawnAreaImplementation::readObject(), server::zone::objects::area::SpawnAreaImplementation::readObject(), server::zone::objects::region::RegionImplementation::readObject(), server::zone::objects::area::LairSpawnAreaImplementation::readObject(), server::zone::objects::creature::aigroup::AiGroupImplementation::readObject(), server::zone::objects::area::DynamicSpawnAreaImplementation::readObject(), server::zone::objects::area::ActiveAreaImplementation::readObject(), server::zone::objects::group::GroupObjectImplementation::readObject(), server::zone::objects::guild::GuildObjectImplementation::readObject(), and readObject().
int SceneObjectImplementation::inRangeObjects (unsigned int gameObjectType, float range)
Returns number of specified game objects in range
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
number of objects in range
Definition at line 979 of file SceneObjectImplementation.cpp.
References _this, gameObjectType, getZone(), and zone.
Referenced by server::zone::objects::scene::SceneObject::inRangeObjects().
bool SceneObjectImplementation::isActiveArea () virtual
Reimplemented in server::zone::objects::area::ActiveAreaImplementation.
Definition at line 4815 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isActiveArea().
bool SceneObjectImplementation::isActorObject () virtual
Reimplemented in server::zone::objects::creature::ai::AiActorImplementation.
Definition at line 5235 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isActorObject().
bool SceneObjectImplementation::isAiAgent () virtual
Reimplemented in server::zone::objects::creature::AiAgentImplementation.
Definition at line 4830 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isAiAgent(), and server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy().
bool SceneObjectImplementation::isArmorObject () virtual
Reimplemented in server::zone::objects::tangible::wearables::ArmorObjectImplementation.
Definition at line 4880 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isArmorObject(), and server::zone::objects::tangible::TangibleObjectImplementation::isSliceable().
bool SceneObjectImplementation::isASubChildOf (SceneObject * object)
Evaluates if this object is a child of the specified SceneObject
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns true if this object is a child of object
Definition at line 1198 of file SceneObjectImplementation.cpp.
References getParent().
Referenced by server::zone::objects::tangible::wearables::WearableObjectImplementation::applyAttachment(), server::zone::objects::tangible::TangibleObjectImplementation::canRepair(), server::zone::objects::tangible::deed::pet::PetDeedImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::fillObjectMenuResponse(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), server::zone::objects::tangible::deed::structure::StructureDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::deed::pet::PetDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::ticket::TicketObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::SurveyToolImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::recycle::RecycleToolImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::CraftingToolImplementation::handleObjectMenuSelect(), server::zone::objects::scene::SceneObject::isASubChildOf(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), server::zone::objects::intangible::VehicleControlDeviceImplementation::spawnObject(), and server::zone::objects::tangible::deed::ResourceDeedImplementation::useObject().
bool SceneObjectImplementation::isAttachment () virtual
Reimplemented in server::zone::objects::tangible::attachement::AttachmentImplementation.
Definition at line 5060 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isAttachment().
bool SceneObjectImplementation::isAuctionObject () virtual
Definition at line 5035 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isAuctionObject().
bool SceneObjectImplementation::isBazaarTerminal ()
Definition at line 4940 of file SceneObject.cpp.
References SceneObjectType::BAZAAR, and gameObjectType.
Referenced by server::zone::objects::scene::SceneObject::isBazaarTerminal().
bool SceneObjectImplementation::isBuildingDeed () virtual
Definition at line 5000 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isBuildingDeed().
bool SceneObjectImplementation::isBuildingObject () virtual
Reimplemented in server::zone::objects::building::BuildingObjectImplementation.
Definition at line 4850 of file SceneObject.cpp.
Referenced by server::zone::objects::cell::CellObjectImplementation::canAddObject(), createChildObjects(), server::zone::objects::scene::SceneObject::isBuildingObject(), and server::zone::objects::structure::StructureObjectImplementation::updateStructureStatus().
bool SceneObjectImplementation::isCamoKit ()
Definition at line 5055 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::scene::SceneObject::isCamoKit().
bool SceneObjectImplementation::isCampKit ()
Definition at line 5075 of file SceneObject.cpp.
References SceneObjectType::CAMPKIT, and gameObjectType.
Referenced by server::zone::objects::scene::SceneObject::isCampKit().
bool SceneObjectImplementation::isCampStructure () virtual
Reimplemented in server::zone::objects::structure::StructureObjectImplementation.
Definition at line 5080 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isCampStructure().
bool SceneObjectImplementation::isCellObject () virtual
Reimplemented in server::zone::objects::cell::CellObjectImplementation.
Definition at line 4905 of file SceneObject.cpp.
Referenced by server::zone::objects::creature::AiAgentImplementation::checkNewAngle(), and server::zone::objects::scene::SceneObject::isCellObject().
bool SceneObjectImplementation::isCityTerminal () virtual
Definition at line 4965 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isCityTerminal().
bool SceneObjectImplementation::isCityVoteTerminal () virtual
Definition at line 4970 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isCityVoteTerminal().
bool SceneObjectImplementation::isCloningBuildingObject () virtual
Definition at line 4855 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isCloningBuildingObject().
bool SceneObjectImplementation::isComponent () virtual
Reimplemented in server::zone::objects::tangible::component::ComponentImplementation.
Definition at line 4925 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isComponent().
bool SceneObjectImplementation::isContainerFull ()
Definition at line 4800 of file SceneObject.cpp.
References containerObjects, and containerVolumeLimit.
Referenced by server::zone::objects::scene::SceneObject::isContainerFull().
bool SceneObjectImplementation::isContainerObject () virtual
Reimplemented in server::zone::objects::tangible::ContainerImplementation.
Definition at line 5200 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isContainerObject(), and server::zone::objects::tangible::TangibleObjectImplementation::isSliceable().
bool SceneObjectImplementation::isControlDevice () virtual
Reimplemented in server::zone::objects::intangible::ControlDeviceImplementation.
Definition at line 5220 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isControlDevice().
bool SceneObjectImplementation::isCraftingStation () virtual
Reimplemented in server::zone::objects::tangible::tool::CraftingStationImplementation.
Definition at line 5020 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isCraftingStation().
bool SceneObjectImplementation::isCraftingTool () virtual
Reimplemented in server::zone::objects::tangible::tool::CraftingToolImplementation.
Definition at line 5015 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isCraftingTool().
bool SceneObjectImplementation::isCreatureHabitat ()
Definition at line 5070 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::scene::SceneObject::isCreatureHabitat().
bool SceneObjectImplementation::isCreatureObject () virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 4825 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isCreatureObject(), and server::zone::objects::tangible::TangibleObjectImplementation::setUseCount().
bool SceneObjectImplementation::isDecoration ()
Definition at line 1648 of file SceneObjectImplementation.cpp.
References templateObject.
Referenced by server::zone::objects::scene::SceneObject::isDecoration().
bool SceneObjectImplementation::isDeedObject () virtual
Reimplemented in server::zone::objects::tangible::deed::DeedImplementation.
Definition at line 4990 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isDeedObject().
bool SceneObjectImplementation::isDetector ()
Definition at line 4765 of file SceneObject.cpp.
References dataObjectComponent.
Referenced by server::zone::objects::scene::SceneObject::isDetector().
bool SceneObjectImplementation::isDiceObject ()
Definition at line 5065 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::scene::SceneObject::isDiceObject().
bool SceneObjectImplementation::isFactory () virtual
Reimplemented in server::zone::objects::installation::factory::FactoryObjectImplementation.
Definition at line 4975 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isFactory().
bool SceneObjectImplementation::isFactoryCrate () virtual
Reimplemented in server::zone::objects::factorycrate::FactoryCrateImplementation.
Definition at line 4980 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isFactoryCrate().
bool SceneObjectImplementation::isFireworkObject () virtual
Reimplemented in server::zone::objects::tangible::firework::FireworkObjectImplementation.
Definition at line 4895 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isFireworkObject().
bool SceneObjectImplementation::isFishingBait ()
Definition at line 5040 of file SceneObject.cpp.
References SceneObjectType::FISHINGBAIT, and gameObjectType.
Referenced by server::zone::objects::scene::SceneObject::isFishingBait().
bool SceneObjectImplementation::isFishingPoleObject ()
Definition at line 4985 of file SceneObject.cpp.
References SceneObjectType::FISHINGPOLE, and gameObjectType.
Referenced by server::zone::objects::scene::SceneObject::isFishingPoleObject().
bool SceneObjectImplementation::isGarage ()
Definition at line 4860 of file SceneObject.cpp.
References gameObjectType, SceneObjectType::GARAGEBUILDING, and SceneObjectType::GARAGEINSTALLATION.
Referenced by server::zone::objects::scene::SceneObject::isGarage().
bool SceneObjectImplementation::isGCWBase ()
Definition at line 4750 of file SceneObject.cpp.
References dataObjectComponent.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::initializeTransientMembers(), server::zone::objects::building::BuildingObjectImplementation::isAllowedEntry(), server::zone::objects::scene::SceneObject::isGCWBase(), and server::zone::objects::building::BuildingObjectImplementation::onEnter().
bool SceneObjectImplementation::isGeneratorObject () virtual
Reimplemented in server::zone::objects::installation::InstallationObjectImplementation, and server::zone::objects::installation::GeneratorObjectImplementation.
Definition at line 4960 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isGeneratorObject().
bool SceneObjectImplementation::isGroupObject () virtual
Reimplemented in server::zone::objects::group::GroupObjectImplementation.
Definition at line 5210 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isGroupObject().
bool SceneObjectImplementation::isGuildObject () virtual
Reimplemented in server::zone::objects::guild::GuildObjectImplementation.
Definition at line 5215 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isGuildObject().
bool SceneObjectImplementation::isHarvesterObject () virtual
Reimplemented in server::zone::objects::installation::InstallationObjectImplementation, and server::zone::objects::installation::harvester::HarvesterObjectImplementation.
Definition at line 4955 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isHarvesterObject().
bool SceneObjectImplementation::isInRange (SceneObject * obj, float range)
Evaluates if the object is in range
Precondition
{ this object is locked, obj is locked}
Postcondition
{ thisobject is locked, obj is locked }
Parameters
obj object that will be checked against
range range to check
Returns
returns true if this object is in range with obj
Definition at line 1219 of file SceneObjectImplementation.cpp.
References getWorldPosition().
Referenced by server::zone::objects::scene::SceneObject::isInRange().
bool SceneObjectImplementation::isInstallationDeed () virtual
Definition at line 5010 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isInstallationDeed().
bool SceneObjectImplementation::isInstallationObject () virtual
Reimplemented in server::zone::objects::installation::InstallationObjectImplementation.
Definition at line 4950 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isInstallationObject().
bool SceneObjectImplementation::isInstrument ()
Definition at line 4935 of file SceneObject.cpp.
References gameObjectType, and SceneObjectType::INSTRUMENT.
Referenced by server::zone::objects::scene::SceneObject::isInstrument().
bool SceneObjectImplementation::isIntangibleObject () virtual
Reimplemented in server::zone::objects::intangible::IntangibleObjectImplementation.
Definition at line 4930 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isIntangibleObject().
bool SceneObjectImplementation::isInWater ()
Definition at line 1582 of file SceneObjectImplementation.cpp.
References error(), server::zone::Zone::getPlanetManager(), and getZone().
Referenced by server::zone::objects::scene::SceneObject::isInWater().
bool SceneObjectImplementation::isJunkDealer () virtual
Reimplemented in server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation.
Definition at line 4835 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isJunkDealer().
bool SceneObjectImplementation::isLightsaberCrystalObject () virtual
Reimplemented in server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation.
Definition at line 4890 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isLightsaberCrystalObject().
bool SceneObjectImplementation::isLiveSample ()
Definition at line 4945 of file SceneObject.cpp.
References gameObjectType, and SceneObjectType::LIVESAMPLE.
Referenced by server::zone::objects::scene::SceneObject::isLiveSample().
bool SceneObjectImplementation::isManufactureSchematic () virtual
Reimplemented in server::zone::objects::manufactureschematic::ManufactureSchematicImplementation.
Definition at line 5025 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isManufactureSchematic().
bool SceneObjectImplementation::isMinefield ()
Definition at line 4760 of file SceneObject.cpp.
References dataObjectComponent.
Referenced by server::zone::objects::installation::InstallationObjectImplementation::createChildObjects(), server::zone::objects::scene::SceneObject::isMinefield(), server::zone::objects::structure::StructureObjectImplementation::notifyInsertToZone(), and server::zone::objects::installation::InstallationObjectImplementation::sendBaselinesTo().
bool SceneObjectImplementation::isMissionObject () virtual
Reimplemented in server::zone::objects::mission::MissionObjectImplementation.
Definition at line 5230 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isMissionObject().
bool SceneObjectImplementation::isMissionTerminal () virtual
Reimplemented in server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation.
Definition at line 5225 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isMissionTerminal(), and server::zone::objects::tangible::TangibleObjectImplementation::isSliceable().
bool SceneObjectImplementation::isNoTrade ()
Definition at line 4795 of file SceneObject.cpp.
References templateObject.
Referenced by server::zone::objects::scene::SceneObject::isNoTrade().
bool SceneObjectImplementation::isPlayerCreature () virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 4740 of file SceneObject.cpp.
Referenced by server::zone::objects::group::GroupObjectImplementation::addGroupModifiers(), destroyObjectFromDatabase(), destroyPlayerCreatureFromDatabase(), server::zone::objects::group::GroupObjectImplementation::hasSquadLeader(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::building::BuildingObjectImplementation::payAccessFee(), and server::zone::objects::group::GroupObjectImplementation::removeGroupModifiers().
bool SceneObjectImplementation::isPlayerObject ()
Definition at line 4810 of file SceneObject.cpp.
References gameObjectType, and SceneObjectType::PLAYEROBJECT.
Referenced by server::zone::objects::scene::SceneObject::isPlayerObject().
bool SceneObjectImplementation::isPsgArmorObject ()
Definition at line 4900 of file SceneObject.cpp.
References gameObjectType, and SceneObjectType::SHIELDGENERATOR.
Referenced by server::zone::objects::scene::SceneObject::isPsgArmorObject().
bool SceneObjectImplementation::isRecycleToolObject () virtual
Definition at line 5085 of file SceneObject.cpp.
References gameObjectType, and SceneObjectType::RECYCLETOOL.
Referenced by server::zone::objects::scene::SceneObject::isRecycleToolObject().
bool SceneObjectImplementation::isRegion () virtual
Reimplemented in server::zone::objects::area::ActiveAreaImplementation, and server::zone::objects::region::RegionImplementation.
Definition at line 4820 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isRegion().
bool SceneObjectImplementation::isRepairTool ()
Definition at line 5050 of file SceneObject.cpp.
References gameObjectType, and SceneObjectType::REPAIRTOOL.
Referenced by server::zone::objects::scene::SceneObject::isRepairTool().
bool SceneObjectImplementation::isResourceContainer () virtual
Reimplemented in server::zone::objects::resource::ResourceContainerImplementation.
Definition at line 4915 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isResourceContainer().
bool SceneObjectImplementation::isResourceSpawn () virtual
Reimplemented in server::zone::objects::resource::ResourceSpawnImplementation.
Definition at line 4920 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isResourceSpawn().
bool SceneObjectImplementation::isRobeObject () virtual
Reimplemented in server::zone::objects::tangible::wearables::RobeObjectImplementation.
Definition at line 4885 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isRobeObject().
bool SceneObjectImplementation::isSecurityTerminal ()
Definition at line 4770 of file SceneObject.cpp.
References dataObjectComponent.
Referenced by server::zone::objects::scene::SceneObject::isSecurityTerminal(), and server::zone::objects::tangible::TangibleObjectImplementation::isSliceable().
bool SceneObjectImplementation::isShipObject () virtual
Reimplemented in server::zone::objects::ship::ShipObjectImplementation.
Definition at line 4840 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isShipObject().
bool SceneObjectImplementation::isShuttleInstallation ()
Definition at line 4805 of file SceneObject.cpp.
References gameObjectType, and SceneObjectType::SHUTTLEINSTALLATION.
Referenced by server::zone::objects::scene::SceneObject::isShuttleInstallation().
bool SceneObjectImplementation::isSignObject () virtual
Reimplemented in server::zone::objects::tangible::sign::SignObjectImplementation.
Definition at line 5005 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isSignObject().
bool SceneObjectImplementation::isStaticObject ()
Definition at line 5195 of file SceneObject.cpp.
References staticObject.
Referenced by server::zone::objects::scene::SceneObject::isStaticObject(), server::zone::objects::building::BuildingObjectImplementation::onEnter(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendTo(), sendTo(), and sendWithoutContainerObjectsTo().
bool SceneObjectImplementation::isStructureObject () virtual
Reimplemented in server::zone::objects::structure::StructureObjectImplementation.
Definition at line 5030 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isStructureObject().
bool SceneObjectImplementation::isTangibleObject () virtual
Reimplemented in server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 4910 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isTangibleObject().
bool SceneObjectImplementation::isTerminal () virtual
Reimplemented in server::zone::objects::tangible::terminal::TerminalImplementation.
Definition at line 5205 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isTerminal().
bool SceneObjectImplementation::isTrapObject ()
Definition at line 5045 of file SceneObject.cpp.
References gameObjectType, and SceneObjectType::TRAP.
Referenced by server::zone::objects::scene::SceneObject::isTrapObject().
bool SceneObjectImplementation::isTurret ()
Definition at line 4755 of file SceneObject.cpp.
References dataObjectComponent.
Referenced by server::zone::objects::installation::InstallationObjectImplementation::createChildObjects(), server::zone::objects::installation::InstallationObjectImplementation::fillAttributeList(), server::zone::objects::scene::SceneObject::isTurret(), server::zone::objects::structure::StructureObjectImplementation::notifyInsertToZone(), and server::zone::objects::installation::InstallationObjectImplementation::sendBaselinesTo().
bool SceneObjectImplementation::isTurretControlTerminal ()
Definition at line 4775 of file SceneObject.cpp.
References dataObjectComponent.
Referenced by server::zone::objects::scene::SceneObject::isTurretControlTerminal().
bool SceneObjectImplementation::isVehicleDeedObject () virtual
Reimplemented in server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation.
Definition at line 4995 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isVehicleDeedObject().
bool SceneObjectImplementation::isVehicleObject () virtual
Reimplemented in server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 4845 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isVehicleObject().
bool SceneObjectImplementation::isVendor ()
Definition at line 4745 of file SceneObject.cpp.
References dataObjectComponent.
Referenced by server::zone::objects::scene::SceneObject::isVendor().
bool SceneObjectImplementation::isWaypointObject ()
Definition at line 4503 of file SceneObject.cpp.
References gameObjectType, and SceneObjectType::WAYPOINT.
Referenced by server::zone::objects::scene::SceneObject::isWaypointObject().
bool SceneObjectImplementation::isWeaponObject () virtual
Reimplemented in server::zone::objects::tangible::weapon::WeaponObjectImplementation.
Definition at line 4865 of file SceneObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::isSliceable(), and server::zone::objects::scene::SceneObject::isWeaponObject().
bool SceneObjectImplementation::isWearableContainerObject () virtual
Reimplemented in server::zone::objects::tangible::wearables::WearableContainerObjectImplementation.
Definition at line 4875 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isWearableContainerObject().
bool SceneObjectImplementation::isWearableObject () virtual
Reimplemented in server::zone::objects::tangible::wearables::WearableObjectImplementation.
Definition at line 4870 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::isWearableObject().
void server::zone::objects::scene::SceneObjectImplementation::link (SceneObject * client, unsigned int containmentType = 4) protected
Sends an UpdateContainmentMessage to client that adds/links this object to its parent object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, client received the link message }
Parameters
client ZoneClientSession that will receive the message
containmentType arrangement type?
Referenced by server::zone::objects::scene::SceneObject::link(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendTo(), sendTo(), and sendWithoutContainerObjectsTo().
BaseMessage* server::zone::objects::scene::SceneObjectImplementation::link (unsigned long long objectID, unsigned int containmentType = 4)
Creates a new UpdateContainmentMessage that adds/links this object to the specified objectID
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
objectID object id of object to link
containmentType arrangement type?
Returns
returns a new valid UpdateContainmentMessage
void SceneObjectImplementation::loadTemplateData (SharedObjectTemplate * templateData) virtual
Reads and sets the template data from a SharedObjectTemplate LuaObject
Precondition
{ templateData is a valid pointer }
Postcondition
{ SceneObject members are initialized }
Parameters
templateData templateData points to the LuaObject that is used to initialize SceneObejct members
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::player::PlayerObjectImplementation, server::zone::objects::creature::AiAgentImplementation, server::zone::objects::tangible::TangibleObjectImplementation, server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation, server::zone::objects::structure::StructureObjectImplementation, server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::installation::InstallationObjectImplementation, server::zone::objects::tangible::consumable::ConsumableImplementation, server::zone::objects::tangible::tool::CraftingToolImplementation, server::zone::objects::creature::VehicleObjectImplementation, server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation, server::zone::objects::tangible::tool::recycle::RecycleToolImplementation, server::zone::objects::tangible::wearables::ArmorObjectImplementation, server::zone::objects::tangible::InstrumentImplementation, server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation, server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation, server::zone::objects::tangible::pharmaceutical::DotPackImplementation, server::zone::objects::draftschematic::DraftSchematicImplementation, server::zone::objects::tangible::pharmaceutical::WoundPackImplementation, server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation, server::zone::objects::tangible::pharmaceutical::StimPackImplementation, server::zone::objects::tangible::pharmaceutical::CurePackImplementation, server::zone::objects::tangible::pharmaceutical::StatePackImplementation, server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation, server::zone::objects::installation::factory::FactoryObjectImplementation, server::zone::objects::factorycrate::FactoryCrateImplementation, server::zone::objects::tangible::tool::SurveyToolImplementation, server::zone::objects::tangible::attachement::AttachmentImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, server::zone::objects::tangible::firework::FireworkObjectImplementation, server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation, server::zone::objects::waypoint::WaypointObjectImplementation, server::zone::objects::tangible::tool::repair::RepairToolImplementation, server::zone::objects::tangible::deed::pet::PetDeedImplementation, server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation, server::zone::objects::tangible::loot::LootkitObjectImplementation, server::zone::objects::cell::CellObjectImplementation, server::zone::objects::tangible::ContainerImplementation, server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation, server::zone::objects::tangible::deed::DeedImplementation, server::zone::objects::installation::harvester::HarvesterObjectImplementation, server::zone::objects::intangible::IntangibleObjectImplementation, server::zone::objects::tangible::wearables::RobeObjectImplementation, and server::zone::objects::staticobject::StaticObjectImplementation.
Definition at line 175 of file SceneObjectImplementation.cpp.
References clientObjectCRC, containerType, containerVolumeLimit, dataObjectComponent, gameObjectType, server::zone::templates::SharedObjectTemplate::getAppearanceTemplate(), server::zone::templates::SharedObjectTemplate::getClientObjectCRC(), server::zone::templates::SharedObjectTemplate::getCollisionActionBlockFlags(), server::zone::templates::SharedObjectTemplate::getContainerType(), server::zone::templates::SharedObjectTemplate::getContainerVolumeLimit(), PlanetMapCategory::getCrc(), server::zone::templates::SharedObjectTemplate::getDataObjectComponent(), server::zone::templates::SharedObjectTemplate::getGameObjectType(), server::zone::templates::SharedObjectTemplate::getObjectName(), server::zone::templates::SharedObjectTemplate::getPlanetMapCategory(), server::zone::templates::SharedObjectTemplate::getPlanetMapSubCategory(), server::zone::templates::SharedObjectTemplate::getPortalLayout(), objectName, planetMapCategory, planetMapSubCategory, server::zone::objects::scene::variables::StringId::setStringId(), and templateObject.
Referenced by server::zone::objects::scene::SceneObject::loadTemplateData().
void SceneObjectImplementation::lock (bool doLock = true) protected
Definition at line 3804 of file SceneObject.cpp.
References _this.
Referenced by getSlottedObjects().
void SceneObjectImplementation::lock (ManagedObject * obj) protected
Definition at line 3808 of file SceneObject.cpp.
References _this.
void SceneObjectImplementation::notifyCloseContainer (CreatureObject * player) virtual
Parameters
player player that closed the container
Definition at line 1055 of file SceneObjectImplementation.cpp.
References ObserverEventType::CLOSECONTAINER.
Referenced by server::zone::objects::scene::SceneObject::notifyCloseContainer().
void SceneObjectImplementation::notifyDissapear (QuadTreeEntry * entry)
Definition at line 4222 of file SceneObject.cpp.
References _this, and zoneComponent.
Referenced by server::zone::objects::scene::SceneObject::notifyDissapear().
void SceneObjectImplementation::notifyInsert (QuadTreeEntry * entry)
Definition at line 4217 of file SceneObject.cpp.
References _this, and zoneComponent.
Referenced by server::zone::objects::scene::SceneObject::notifyInsert(), sendContainerObjectsTo(), sendSlottedObjectsTo(), and server::zone::objects::creature::CreatureObjectImplementation::sendToOwner().
void SceneObjectImplementation::notifyInsertToZone (Zone * zone) virtual
Inserts this object into zone
Precondition
{ this object is locked }
Postcondition
{ this object is locked and inserted into zone }
Parameters
zone Zone object where this object will be inserted
Reimplemented in server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::structure::StructureObjectImplementation, server::zone::objects::creature::VehicleObjectImplementation, and server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation.
Definition at line 1077 of file SceneObjectImplementation.cpp.
References _this, and zoneComponent.
Referenced by server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation::notifyInsertToZone(), and server::zone::objects::scene::SceneObject::notifyInsertToZone().
void SceneObjectImplementation::notifyLoadFromDatabase ()
Gets called when this objects is loaded from database
Precondition
{ this locked }
Postcondition
{ this locked }
Definition at line 454 of file SceneObjectImplementation.cpp.
References _this, activeAreas, containerObjects, server::zone::objects::scene::ContainerObjectsMap::get(), server::zone::objects::scene::ContainerObjectsMap::hasDelayedLoadOperationMode(), server::zone::objects::scene::ContainerObjectsMap::size(), slottedObjects, and zone.
Referenced by server::zone::objects::installation::harvester::HarvesterObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::installation::factory::FactoryObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::tangible::InstrumentImplementation::notifyLoadFromDatabase(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::notifyLoadFromDatabase(), and server::zone::objects::scene::SceneObject::notifyLoadFromDatabase().
int SceneObjectImplementation::notifyObjectInserted (SceneObject * object) virtual
Is called when this object has been inserted with an object
Parameters
object object that has been inserted
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, and server::zone::objects::tangible::loot::LootkitObjectImplementation.
Definition at line 4353 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::notifyObjectInserted().
int SceneObjectImplementation::notifyObjectInsertedToChild (SceneObject * object, SceneObject * child, SceneObject * oldParent) virtual
Reimplemented in server::zone::objects::building::BuildingObjectImplementation.
Definition at line 4173 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::notifyObjectInsertedToChild().
int SceneObjectImplementation::notifyObjectRemoved (SceneObject * object) virtual
Is called when an object was removed
Parameters
object object that has been inserted
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 4358 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::notifyObjectRemoved().
int SceneObjectImplementation::notifyObjectRemovedFromChild (SceneObject * object, SceneObject * child) virtual
Reimplemented in server::zone::objects::building::BuildingObjectImplementation.
Definition at line 4178 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::notifyObjectRemovedFromChild().
void SceneObjectImplementation::notifyPositionUpdate (QuadTreeEntry * entry)
Definition at line 1059 of file SceneObjectImplementation.cpp.
References _this, ObserverEventType::OBJECTINRANGEMOVED, and zoneComponent.
Referenced by server::zone::objects::creature::AiAgentImplementation::notifyPositionUpdate(), and server::zone::objects::scene::SceneObject::notifyPositionUpdate().
void SceneObjectImplementation::notifyRemoveFromZone () virtual
Reimplemented in server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation, and server::zone::objects::installation::garage::GarageInstallationImplementation.
Definition at line 1117 of file SceneObjectImplementation.cpp.
References _this, and zoneComponent.
Referenced by server::zone::objects::installation::garage::GarageInstallationImplementation::notifyRemoveFromZone(), and server::zone::objects::scene::SceneObject::notifyRemoveFromZone().
void SceneObjectImplementation::notifySelfPositionUpdate () virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 1051 of file SceneObjectImplementation.cpp.
References ObserverEventType::POSITIONCHANGED.
Referenced by server::zone::objects::scene::SceneObject::notifySelfPositionUpdate().
void SceneObjectImplementation::openContainerTo (CreatureObject * player) virtual
Opens container contents to player
Precondition
{ }
Postcondition
{ }
Parameters
player CreatureObject to open the container to
Definition at line 1133 of file SceneObjectImplementation.cpp.
References _this, sendContainerObjectsTo(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::objects::scene::SceneObject::openContainerTo().
SceneObjectImplementation::operator const SceneObject * ()
Definition at line 3800 of file SceneObject.cpp.
void SceneObjectImplementation::putInContainer (SceneObject * obj, unsigned long long key)
Definition at line 4656 of file SceneObject.cpp.
References containerObjects.
Referenced by server::zone::objects::cell::CellObjectImplementation::notifyLoadFromDatabase(), and server::zone::objects::scene::SceneObject::putInContainer().
void SceneObjectImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::player::PlayerObjectImplementation, server::zone::objects::creature::AiAgentImplementation, server::zone::objects::tangible::TangibleObjectImplementation, server::zone::objects::creature::ai::AiActorImplementation, server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::structure::StructureObjectImplementation, server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation, server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::mission::MissionObjectImplementation, server::zone::objects::installation::InstallationObjectImplementation, server::zone::objects::manufactureschematic::ManufactureSchematicImplementation, server::zone::ZoneImplementation, server::zone::objects::creature::VehicleObjectImplementation, server::zone::objects::resource::ResourceSpawnImplementation, server::zone::objects::tangible::component::dna::DnaComponentImplementation, server::zone::objects::guild::GuildObjectImplementation, server::zone::objects::tangible::wearables::ArmorObjectImplementation, server::zone::objects::tangible::tool::CraftingToolImplementation, server::zone::objects::draftschematic::DraftSchematicImplementation, server::zone::objects::tangible::consumable::ConsumableImplementation, server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation, server::zone::objects::creature::CreatureImplementation, server::zone::objects::tangible::pharmaceutical::DotPackImplementation, server::zone::objects::area::CampSiteActiveAreaImplementation, server::zone::objects::tangible::InstrumentImplementation, server::zone::objects::tangible::tool::recycle::RecycleToolImplementation, server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation, server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation, server::zone::objects::installation::factory::FactoryObjectImplementation, server::zone::objects::tangible::component::genetic::GeneticComponentImplementation, server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation, server::zone::objects::tangible::pharmaceutical::WoundPackImplementation, server::zone::objects::factorycrate::FactoryCrateImplementation, server::zone::objects::intangible::VehicleControlDeviceImplementation, server::zone::objects::tangible::pharmaceutical::CurePackImplementation, server::zone::objects::tangible::pharmaceutical::RevivePackImplementation, server::zone::objects::tangible::pharmaceutical::StimPackImplementation, server::zone::objects::tangible::tool::SurveyToolImplementation, server::zone::objects::tangible::pharmaceutical::StatePackImplementation, server::zone::objects::group::GroupObjectImplementation, server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation, server::zone::objects::tangible::component::ComponentImplementation, server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation, server::zone::objects::area::ActiveAreaImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, server::zone::objects::area::DynamicSpawnAreaImplementation, server::zone::objects::cell::CellObjectImplementation, server::zone::objects::resource::ResourceContainerImplementation, server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation, server::zone::objects::tangible::attachement::AttachmentImplementation, server::zone::objects::tangible::ticket::TicketObjectImplementation, server::zone::objects::waypoint::WaypointObjectImplementation, server::zone::objects::tangible::fishing::FishingPoleObjectImplementation, server::zone::objects::tangible::fishing::FishObjectImplementation, server::zone::objects::installation::shuttle::ShuttleInstallationImplementation, server::zone::objects::creature::aigroup::AiGroupImplementation, server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation, server::zone::objects::tangible::ContainerImplementation, server::zone::objects::tangible::wearables::WearableObjectImplementation, server::zone::objects::tangible::firework::FireworkObjectImplementation, server::zone::objects::tangible::deed::pet::PetDeedImplementation, server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation, server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation, server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation, server::zone::objects::intangible::ControlDeviceImplementation, server::zone::objects::tangible::tool::repair::RepairToolImplementation, server::zone::objects::tangible::deed::ResourceDeedImplementation, server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation, server::zone::objects::installation::harvester::HarvesterObjectImplementation, server::zone::objects::tangible::deed::structure::StructureDeedImplementation, server::zone::objects::area::LairSpawnAreaImplementation, server::zone::objects::tangible::deed::DeedImplementation, server::zone::objects::tangible::loot::LootkitObjectImplementation, server::zone::objects::tangible::component::armor::ArmorComponentImplementation, server::zone::objects::region::RegionImplementation, server::zone::objects::area::SpawnAreaImplementation, server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation, server::zone::objects::installation::GeneratorObjectImplementation, server::zone::objects::tangible::terminal::ticketcollector::TicketCollectorImplementation, server::zone::objects::tangible::powerup::PowerupObjectImplementation, server::zone::objects::tangible::fishing::FishingBaitObjectImplementation, server::zone::objects::tangible::wearables::WearableContainerObjectImplementation, server::zone::objects::area::StaticSpawnAreaImplementation, server::zone::objects::tangible::terminal::startinglocation::StartingLocationTerminalImplementation, server::zone::objects::area::MissionReconActiveAreaImplementation, server::zone::objects::tangible::terminal::TerminalImplementation, server::zone::objects::intangible::IntangibleObjectImplementation, server::zone::objects::area::MissionSpawnActiveAreaImplementation, server::zone::objects::intangible::ShipControlDeviceImplementation, server::zone::objects::tangible::sign::SignObjectImplementation, server::zone::objects::area::BadgeActiveAreaImplementation, server::zone::objects::creature::NonPlayerCreatureObjectImplementation, server::zone::objects::tangible::wearables::RobeObjectImplementation, server::zone::objects::tangible::wearables::PsgArmorObjectImplementation, server::zone::objects::staticobject::StaticObjectImplementation, server::zone::objects::tangible::wearables::ClothingObjectImplementation, server::zone::objects::building::hospital::HospitalBuildingObjectImplementation, server::zone::objects::building::recreation::RecreationBuildingObjectImplementation, server::zone::objects::tangible::consumable::DrinkImplementation, server::zone::objects::tangible::consumable::FoodImplementation, server::zone::objects::area::FsVillageAreaImplementation, server::zone::objects::ship::ShipObjectImplementation, server::zone::objects::tangible::tool::ToolTangibleObjectImplementation, server::zone::objects::area::GarageAreaImplementation, server::zone::objects::installation::garage::GarageInstallationImplementation, server::zone::objects::building::travel::TravelBuildingObjectImplementation, server::zone::objects::tangible::terminal::spaceship::SpaceshipTerminalImplementation, server::zone::objects::creature::aigroup::HerdGroupImplementation, server::zone::objects::creature::aigroup::LairGroupImplementation, server::zone::objects::creature::aigroup::PackGroupImplementation, server::zone::objects::ship::FighterShipObjectImplementation, and server::zone::objects::ship::SpaceStationObjectImplementation.
Definition at line 3839 of file SceneObject.cpp.
References initializeTransientMembers(), and readObjectMember().
bool SceneObjectImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 3858 of file SceneObject.cpp.
References activeAreas, childObjects, clientObjectCRC, containerObjects, containerPermissions, containerType, containerVolumeLimit, containmentType, customName, dataObjectComponent, direction, gameObjectType, movementCounter, objectActiveSessions, objectName, planetMapCategory, planetMapSubCategory, sendToClient, serverObjectCRC, slottedObjects, staticObject, and zone.
Referenced by readObject().
void SceneObjectImplementation::removeAllContainerObjects ()
Definition at line 4651 of file SceneObject.cpp.
References containerObjects.
Referenced by server::zone::objects::scene::SceneObject::removeAllContainerObjects().
void SceneObjectImplementation::removeFromContainerObjects (int index)
Definition at line 4661 of file SceneObject.cpp.
References containerObjects.
Referenced by server::zone::objects::scene::SceneObject::removeFromContainerObjects().
bool SceneObjectImplementation::removeObject (SceneObject * object, SceneObject * destination, bool notifyClient = false) virtual
Tries to remove/unlink object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be removed from the current object
destination SceneObject that will be the new destination of the object.
notifyClient not used currently
Returns
returns true if the object has been successfully removed
Reimplemented in server::zone::objects::tangible::fishing::FishingPoleObjectImplementation.
Definition at line 1129 of file SceneObjectImplementation.cpp.
References _this, and containerComponent.
Referenced by server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::removeObject(), and server::zone::objects::scene::SceneObject::removeObject().
void SceneObjectImplementation::removePendingTask (const String & name)
Removes a pending task from this SceneObject
Precondition
{ this locked }
Postcondition
{ this locked }
Parameters
name Name of the task to drop
Definition at line 4266 of file SceneObject.cpp.
References containerLock, and pendingTasks.
Referenced by server::zone::objects::scene::SceneObject::removePendingTask(), server::zone::objects::installation::factory::FactoryObjectImplementation::stopFactory(), and server::zone::objects::building::BuildingObjectImplementation::updatePaidAccessList().
void SceneObjectImplementation::removeSlottedObject (int index)
Definition at line 1536 of file SceneObjectImplementation.cpp.
References containerLock, and slottedObjects.
Referenced by server::zone::objects::scene::SceneObject::removeSlottedObject().
void SceneObjectImplementation::rlock (bool doLock = true) protected
Definition at line 3812 of file SceneObject.cpp.
References _this.
void SceneObjectImplementation::rotate (int degrees)
Rotates an object by a specified number of degrees.
Parameters
degrees How many degrees to rotate the object with 0 being North. TODO:
notifyClient
Definition at line 1261 of file SceneObjectImplementation.cpp.
References direction.
Referenced by server::zone::objects::scene::SceneObject::rotate().
void SceneObjectImplementation::runlock (bool doLock = true) protected
Definition at line 3828 of file SceneObject.cpp.
References _this.
void SceneObjectImplementation::sendAttributeListTo (CreatureObject * object) virtual
Sends an AttributeListMessage to specified object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, object received the attribute list message }
Parameters
object SceneObject that will receive the message
Definition at line 590 of file SceneObjectImplementation.cpp.
References _this, attributeListComponent, and error().
Referenced by server::zone::objects::tangible::weapon::WeaponObjectImplementation::applyPowerup(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::decreasePowerupUses(), and server::zone::objects::scene::SceneObject::sendAttributeListTo().
void SceneObjectImplementation::sendBaselinesTo (SceneObject * player) virtual
Sends the baseline messages of this object to the specified player, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the baseline messages }
Parameters
player SceneObject that will receive the baselines
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::player::PlayerObjectImplementation, server::zone::objects::creature::AiAgentImplementation, server::zone::objects::tangible::TangibleObjectImplementation, server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::installation::InstallationObjectImplementation, server::zone::objects::mission::MissionObjectImplementation, server::zone::objects::manufactureschematic::ManufactureSchematicImplementation, server::zone::objects::guild::GuildObjectImplementation, server::zone::objects::draftschematic::DraftSchematicImplementation, server::zone::objects::cell::CellObjectImplementation, server::zone::objects::factorycrate::FactoryCrateImplementation, server::zone::objects::resource::ResourceContainerImplementation, server::zone::objects::group::GroupObjectImplementation, server::zone::objects::intangible::IntangibleObjectImplementation, server::zone::objects::staticobject::StaticObjectImplementation, and server::zone::objects::ship::ShipObjectImplementation.
Definition at line 4198 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::sendBaselinesTo(), sendTo(), sendWithoutContainerObjectsTo(), and sendWithoutParentTo().
void SceneObjectImplementation::sendContainerObjectsTo (SceneObject * player) virtual
Sends the contained non slotted objects to the specified player
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the container objects }
Parameters
player SceneObject that will receive the objects
Reimplemented in server::zone::objects::building::BuildingObjectImplementation, and server::zone::objects::cell::CellObjectImplementation.
Definition at line 559 of file SceneObjectImplementation.cpp.
References getContainerObjects(), notifyInsert(), and server::zone::objects::scene::SceneObject::sendTo().
Referenced by openContainerTo(), server::zone::objects::scene::SceneObject::sendContainerObjectsTo(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendTo(), sendTo(), and sendWithoutParentTo().
void SceneObjectImplementation::sendDestroyTo (SceneObject * player) virtual
Sends a SceneObjectDestroyMessage of this object to client
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the destroy message }
Parameters
plaer SceneObject that will receive the message
Reimplemented in server::zone::objects::building::BuildingObjectImplementation.
Definition at line 578 of file SceneObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObject::sendMessage(), and staticObject.
Referenced by server::zone::objects::group::GroupObjectImplementation::disband(), server::zone::objects::scene::SceneObject::sendDestroyTo(), and server::zone::objects::creature::CreatureObjectImplementation::setState().
void SceneObjectImplementation::sendMessage (BasePacket * msg) virtual
Sends BasePacket msg to the owner of this object, needs to be overriden
Precondition
{ }
Postcondition
{owner of this object received message, message is deleted }
Parameters
msg BasePacket to be sent
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::player::PlayerObjectImplementation, and server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 1012 of file SceneObjectImplementation.cpp.
Referenced by server::zone::objects::scene::SceneObject::sendMessage().
void SceneObjectImplementation::sendSlottedObjectsTo (SceneObject * player) virtual
Sends the contained slotted objects to the specified player
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the slotted objects }
Parameters
player SceneObject that will receive the objects
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 538 of file SceneObjectImplementation.cpp.
References getSlottedObjects(), and notifyInsert().
Referenced by server::zone::objects::scene::SceneObject::sendSlottedObjectsTo(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendTo(), sendTo(), and sendWithoutParentTo().
void SceneObjectImplementation::sendTo (SceneObject * player, bool doClose) virtual
Sends the necessary messages to player in order to create this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received this object }
Parameters
player SceneObject that will receive the messages
doClose if true a SceneObjectCloseMessage is sent to finish the object
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::manufactureschematic::ManufactureSchematicImplementation, server::zone::objects::area::ActiveAreaImplementation, and server::zone::objects::ship::ShipObjectImplementation.
Definition at line 407 of file SceneObjectImplementation.cpp.
References _this, close(), server::zone::objects::scene::SceneObject::getClient(), isStaticObject(), link(), sendBaselinesTo(), sendContainerObjectsTo(), server::zone::objects::scene::SceneObject::sendMessage(), sendSlottedObjectsTo(), and sendToClient.
Referenced by server::zone::objects::group::GroupObjectImplementation::addMember(), server::zone::objects::structure::StructureObjectImplementation::sendPermissionListTo(), and server::zone::objects::scene::SceneObject::sendTo().
void SceneObjectImplementation::sendToOwner (bool doClose = true) virtual
Sends the necessary messages to owner client, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, owner received its own scene object }
Parameters
doClose if true a SceneObjectCloseMessage is sent to finish the object
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 4201 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::sendToOwner().
void SceneObjectImplementation::sendWithoutContainerObjectsTo (SceneObject * player) virtual
Definition at line 439 of file SceneObjectImplementation.cpp.
References _this, close(), isStaticObject(), link(), sendBaselinesTo(), server::zone::objects::scene::SceneObject::sendMessage(), and sendToClient.
Referenced by server::zone::objects::scene::SceneObject::sendWithoutContainerObjectsTo().
void SceneObjectImplementation::sendWithoutParentTo (SceneObject * player) virtual
Sends the object without linking to its actual parent and without sending its children (f.e trade)
Definition at line 392 of file SceneObjectImplementation.cpp.
References _this, close(), sendBaselinesTo(), sendContainerObjectsTo(), server::zone::objects::scene::SceneObject::sendMessage(), and sendSlottedObjectsTo().
Referenced by server::zone::objects::scene::SceneObject::sendWithoutParentTo().
void SceneObjectImplementation::setCityRegion (CityRegion * region)
Definition at line 4440 of file SceneObject.cpp.
References cityRegion.
Referenced by server::zone::objects::scene::SceneObject::setCityRegion().
void SceneObjectImplementation::setClientObject (bool val)
Definition at line 5190 of file SceneObject.cpp.
References staticObject.
Referenced by server::zone::objects::scene::SceneObject::setClientObject().
void SceneObjectImplementation::setClientObjectCRC (unsigned int objCRC)
Definition at line 5140 of file SceneObject.cpp.
References clientObjectCRC.
Referenced by server::zone::objects::scene::SceneObject::setClientObjectCRC().
void SceneObjectImplementation::setContainerAllowPermission (const String & group, unsigned short perm)
Definition at line 5125 of file SceneObject.cpp.
References containerPermissions.
Referenced by server::zone::objects::scene::SceneObject::setContainerAllowPermission().
void SceneObjectImplementation::setContainerComponent (const String & name)
Definition at line 519 of file SceneObjectImplementation.cpp.
References containerComponent, error(), info(), and templateObject.
Referenced by server::zone::objects::scene::SceneObject::setContainerComponent().
void SceneObjectImplementation::setContainerDefaultAllowPermission (unsigned short perm)
Definition at line 5095 of file SceneObject.cpp.
References containerPermissions.
Referenced by server::zone::objects::installation::InstallationObjectImplementation::createChildObjects(), and server::zone::objects::scene::SceneObject::setContainerDefaultAllowPermission().
void SceneObjectImplementation::setContainerDefaultDenyPermission (unsigned short perm)
Definition at line 5105 of file SceneObject.cpp.
References containerPermissions.
Referenced by server::zone::objects::tangible::tool::CraftingToolImplementation::CraftingToolImplementation(), server::zone::objects::installation::InstallationObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::initializeMembers(), and server::zone::objects::scene::SceneObject::setContainerDefaultDenyPermission().
void SceneObjectImplementation::setContainerDenyPermission (const String & group, unsigned short perm)
Definition at line 5130 of file SceneObject.cpp.
References containerPermissions.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::initializeMembers(), and server::zone::objects::scene::SceneObject::setContainerDenyPermission().
void SceneObjectImplementation::setContainerInheritPermissionsFromParent (bool val)
Definition at line 5115 of file SceneObject.cpp.
References containerPermissions.
Referenced by server::zone::objects::tangible::tool::CraftingToolImplementation::CraftingToolImplementation(), server::zone::objects::creature::CreatureObjectImplementation::initializeMembers(), and server::zone::objects::scene::SceneObject::setContainerInheritPermissionsFromParent().
void SceneObjectImplementation::setContainerOwnerID (unsigned long long id)
Definition at line 5120 of file SceneObject.cpp.
References containerPermissions.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::initializeTransientMembers(), and server::zone::objects::scene::SceneObject::setContainerOwnerID().
void SceneObjectImplementation::setContainerType (int type)
Definition at line 4671 of file SceneObject.cpp.
References containerType.
Referenced by server::zone::objects::scene::SceneObject::setContainerType().
void SceneObjectImplementation::setContainerVolumeLimit (int lim)
Definition at line 4666 of file SceneObject.cpp.
References containerVolumeLimit.
Referenced by server::zone::objects::scene::SceneObject::setContainerVolumeLimit().
void SceneObjectImplementation::setContainmentType (unsigned int type)
Definition at line 5180 of file SceneObject.cpp.
References containmentType.
Referenced by server::zone::objects::scene::SceneObject::setContainmentType().
void SceneObjectImplementation::setCustomObjectName (const UnicodeString & name, bool notifyClient) virtual
Updates the custom name of the object
Precondition
{ this locked }
Postcondition
{ this locked }
Reimplemented in server::zone::objects::tangible::TangibleObjectImplementation, and server::zone::objects::building::BuildingObjectImplementation.
Definition at line 4207 of file SceneObject.cpp.
References customName.
Referenced by server::zone::objects::scene::SceneObject::setCustomObjectName().
void SceneObjectImplementation::setDetailedDescription (const String & detail) virtual
Reimplemented in server::zone::objects::waypoint::WaypointObjectImplementation.
Definition at line 4528 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::setDetailedDescription().
void SceneObjectImplementation::setDirection (float fw, float fx, float fy, float fz)
Definition at line 5160 of file SceneObject.cpp.
References direction.
Referenced by server::zone::objects::creature::AiAgentImplementation::doMovement(), server::zone::objects::scene::SceneObject::setDirection(), and updateDirection().
void SceneObjectImplementation::setDirection (float headingAngleRadians)
Definition at line 5165 of file SceneObject.cpp.
References direction.
void SceneObjectImplementation::setDirection (const Quaternion & dir)
Definition at line 1257 of file SceneObjectImplementation.cpp.
References direction.
void SceneObjectImplementation::setGameObjectType (unsigned int type)
Definition at line 5135 of file SceneObject.cpp.
References gameObjectType.
Referenced by server::zone::objects::scene::SceneObject::setGameObjectType().
void SceneObjectImplementation::setLoggingName (const String & name)
Definition at line 5185 of file SceneObject.cpp.
Referenced by server::zone::objects::tangible::consumable::ConsumableImplementation::ConsumableImplementation(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::CurePackImplementation(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::DotPackImplementation(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::EnhancePackImplementation(), server::zone::objects::installation::garage::GarageInstallationImplementation::GarageInstallationImplementation(), initializePrivateData(), server::zone::objects::tangible::wearables::PsgArmorObjectImplementation::initializeTransientMembers(), server::zone::objects::intangible::IntangibleObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::terminal::TerminalImplementation::initializeTransientMembers(), server::zone::objects::tangible::wearables::WearableContainerObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::terminal::startinglocation::StartingLocationTerminalImplementation::initializeTransientMembers(), server::zone::objects::tangible::deed::DeedImplementation::initializeTransientMembers(), server::zone::objects::tangible::deed::structure::StructureDeedImplementation::initializeTransientMembers(), server::zone::objects::tangible::deed::ResourceDeedImplementation::initializeTransientMembers(), server::zone::objects::tangible::wearables::WearableObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation::initializeTransientMembers(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::initializeTransientMembers(), server::zone::objects::tangible::deed::pet::PetDeedImplementation::initializeTransientMembers(), server::zone::objects::tangible::ContainerImplementation::initializeTransientMembers(), server::zone::objects::tangible::attachement::AttachmentImplementation::initializeTransientMembers(), server::zone::objects::cell::CellObjectImplementation::initializeTransientMembers(), server::zone::objects::factorycrate::FactoryCrateImplementation::initializeTransientMembers(), server::zone::objects::installation::factory::FactoryObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::initializeTransientMembers(), server::zone::objects::draftschematic::DraftSchematicImplementation::initializeTransientMembers(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::tool::recycle::RecycleToolImplementation::initializeTransientMembers(), server::zone::objects::building::BuildingObjectImplementation::initializeTransientMembers(), server::zone::objects::mission::MissionObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::TangibleObjectImplementation::initializeTransientMembers(), server::zone::objects::player::PlayerObjectImplementation::initializeTransientMembers(), initializeTransientMembers(), server::zone::objects::creature::CreatureObjectImplementation::initializeTransientMembers(), server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::PharmaceuticalObjectImplementation(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::PrecisionLaserKnifeImplementation(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::RangedStimPackImplementation(), server::zone::objects::tangible::tool::repair::RepairToolImplementation::RepairToolImplementation(), server::zone::objects::resource::ResourceContainerImplementation::ResourceContainerImplementation(), server::zone::objects::resource::ResourceSpawnImplementation::ResourceSpawnImplementation(), server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::RevivePackImplementation(), server::zone::objects::scene::SceneObject::setLoggingName(), server::zone::objects::installation::shuttle::ShuttleInstallationImplementation::ShuttleInstallationImplementation(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::SlicingToolImplementation(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::StatePackImplementation(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::StimPackImplementation(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::WoundPackImplementation(), and server::zone::ZoneImplementation::ZoneImplementation().
void SceneObjectImplementation::setMovementCounter (unsigned int count)
Definition at line 5170 of file SceneObject.cpp.
References movementCounter.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::sendToOwner(), and server::zone::objects::scene::SceneObject::setMovementCounter().
void SceneObjectImplementation::setObjectMenuComponent (const String & name)
Definition at line 500 of file SceneObjectImplementation.cpp.
References error(), info(), objectMenuComponent, and templateObject.
Referenced by server::zone::objects::scene::SceneObject::setObjectMenuComponent().
void SceneObjectImplementation::setObjectName (StringId & stringID)
Definition at line 1274 of file SceneObjectImplementation.cpp.
References objectName.
Referenced by server::zone::objects::scene::SceneObject::setObjectName().
void SceneObjectImplementation::setParent (QuadTreeEntry * entry)
Definition at line 1559 of file SceneObjectImplementation.cpp.
References parentLock.
Referenced by server::zone::objects::scene::SceneObject::setParent().
void SceneObjectImplementation::setPlanetMapCategory (PlanetMapCategory * pmc)
Definition at line 5250 of file SceneObject.cpp.
References PlanetMapCategory::getCrc(), and planetMapCategory.
Referenced by server::zone::objects::scene::SceneObject::setPlanetMapCategory().
void SceneObjectImplementation::setPlanetMapSubCategory (PlanetMapCategory * pmc)
Definition at line 5259 of file SceneObject.cpp.
References PlanetMapCategory::getCrc(), and planetMapSubCategory.
Referenced by server::zone::objects::scene::SceneObject::setPlanetMapSubCategory().
void SceneObjectImplementation::setSendToClient (bool val)
Definition at line 5303 of file SceneObject.cpp.
References sendToClient.
Referenced by server::zone::objects::scene::SceneObject::setSendToClient().
void SceneObjectImplementation::setServerObjectCRC (unsigned int objCRC)
Definition at line 5145 of file SceneObject.cpp.
References serverObjectCRC.
Referenced by server::zone::objects::scene::SceneObject::setServerObjectCRC().
bool SceneObjectImplementation::setTransformForCollisionMatrixIfNull (Matrix4 * mat)
Definition at line 1605 of file SceneObjectImplementation.cpp.
References transformForCollisionMatrix.
Referenced by server::zone::objects::scene::SceneObject::setTransformForCollisionMatrixIfNull().
void SceneObjectImplementation::setZone (Zone * zone)
Definition at line 1542 of file SceneObjectImplementation.cpp.
References zone.
Referenced by server::zone::objects::scene::SceneObject::setZone().
void SceneObjectImplementation::setZoneComponent (const String & name)
Definition at line 205 of file SceneObjectImplementation.cpp.
References zoneComponent.
Referenced by server::zone::objects::scene::SceneObject::setZoneComponent().
void SceneObjectImplementation::setZoneProcessServer (ZoneProcessServer * srv)
Definition at line 5150 of file SceneObject.cpp.
References server.
Referenced by server::zone::objects::scene::SceneObject::setZoneProcessServer().
void SceneObjectImplementation::showFlyText (const String & file, const String & uax, byte red, byte green, byte blue)
Definition at line 1546 of file SceneObjectImplementation.cpp.
References _this, and broadcastMessage().
Referenced by server::zone::objects::creature::AiAgentImplementation::addDefender(), server::zone::objects::creature::CreatureObjectImplementation::clearState(), server::zone::objects::creature::CreatureImplementation::runAway(), server::zone::objects::creature::CreatureObjectImplementation::setNextAttackDelay(), server::zone::objects::creature::CreatureObjectImplementation::setState(), and server::zone::objects::scene::SceneObject::showFlyText().
void SceneObjectImplementation::switchZone (const String & newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID = 0) virtual
Switches zone and position of this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, is in the new zone and in the new position }
Parameters
newTerrainName Name of the new terrain where the player will be inserted.
newPositionX new position X
newPositionZ new position Z
newPositionY new position Y
Definition at line 1085 of file SceneObjectImplementation.cpp.
References _this, and zoneComponent.
Referenced by server::zone::objects::scene::SceneObject::switchZone().
void SceneObjectImplementation::synchronizedUIListen (SceneObject * player, int value) virtual
Calls the appropriate UI Listener Function
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
player CreatureObject using the item
value value from packet
Reimplemented in server::zone::objects::tangible::TangibleObjectImplementation, server::zone::objects::manufactureschematic::ManufactureSchematicImplementation, server::zone::objects::installation::harvester::HarvesterObjectImplementation, and server::zone::objects::installation::GeneratorObjectImplementation.
Definition at line 4183 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::synchronizedUIListen().
void SceneObjectImplementation::synchronizedUIStopListen (SceneObject * player, int value) virtual
Calls the appropriate UI Stop Listener Function
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
player CreatureObject using the item
value value from packet
Reimplemented in server::zone::objects::tangible::TangibleObjectImplementation, server::zone::objects::manufactureschematic::ManufactureSchematicImplementation, server::zone::objects::installation::harvester::HarvesterObjectImplementation, and server::zone::objects::installation::GeneratorObjectImplementation.
Definition at line 4188 of file SceneObject.cpp.
Referenced by server::zone::objects::scene::SceneObject::synchronizedUIStopListen().
void SceneObjectImplementation::teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID = 0) virtual
Definition at line 1081 of file SceneObjectImplementation.cpp.
References _this, and zoneComponent.
Referenced by server::zone::objects::scene::SceneObject::teleport().
bool SceneObjectImplementation::transferObject (SceneObject * object, int containmentType, bool notifyClient = false, bool allowOverflow = false) virtual
Tries to add/link object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be added to the current object
containmentType arrangement type that will be used to add the object
notifyClient if true in range objects will be updated with the change
Returns
returns true if the object has been successfully added
Reimplemented in server::zone::objects::building::BuildingObjectImplementation, and server::zone::objects::cell::CellObjectImplementation.
Definition at line 1125 of file SceneObjectImplementation.cpp.
References _this, containerComponent, and containmentType.
Referenced by server::zone::objects::installation::factory::FactoryObjectImplementation::createChildObjects(), server::zone::objects::installation::InstallationObjectImplementation::createChildObjects(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleInsertFactorySchem(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), server::zone::objects::creature::AiAgentImplementation::selectWeapon(), server::zone::objects::factorycrate::FactoryCrateImplementation::split(), server::zone::objects::intangible::ShipControlDeviceImplementation::storeObject(), and server::zone::objects::scene::SceneObject::transferObject().
void SceneObjectImplementation::unlock (bool doLock = true) protected
Definition at line 3824 of file SceneObject.cpp.
References _this.
void SceneObjectImplementation::updateDirection (float fw, float fx, float fy, float fz)
Updates the direction of this object, and braodcasts DataTransform with the update
Definition at line 1089 of file SceneObjectImplementation.cpp.
References _this, broadcastMessage(), movementCounter, and setDirection().
Referenced by server::zone::objects::scene::SceneObject::updateDirection().
void SceneObjectImplementation::updateDirection (float angleHeadingRadians)
Definition at line 1103 of file SceneObjectImplementation.cpp.
References _this, broadcastMessage(), movementCounter, and setDirection().
void SceneObjectImplementation::updateToDatabase ()
Updates this object to database (calls updatesToDatabaseAllObjects())
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
startTask if true, queues a new update task
Definition at line 253 of file SceneObjectImplementation.cpp.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createCellObjects(), server::zone::objects::player::PlayerObjectImplementation::unload(), and server::zone::objects::scene::SceneObject::updateToDatabase().
void SceneObjectImplementation::updateToDatabaseAllObjects (bool startTask)
Updates this object and childre objects to database
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
startTask if true, queues a new update task
Definition at line 262 of file SceneObjectImplementation.cpp.
Referenced by server::zone::objects::intangible::ControlDeviceImplementation::updateToDatabaseAllObjects(), and server::zone::objects::scene::SceneObject::updateToDatabaseAllObjects().
void SceneObjectImplementation::updateToDatabaseWithoutChildren ()
Updates only this object to database without updating children WARNING use only when necessary
Definition at line 257 of file SceneObjectImplementation.cpp.
Referenced by server::zone::objects::scene::SceneObject::updateToDatabaseWithoutChildren().
void SceneObjectImplementation::updateVehiclePosition (bool sendPackets)
Definition at line 1031 of file SceneObjectImplementation.cpp.
References direction, and getParent().
Referenced by server::zone::objects::scene::SceneObject::updateVehiclePosition().
void SceneObjectImplementation::updateZone (bool lightUpdate, bool sendPackets = true) virtual
Updates position of this object to the rest of in range objects
Precondition
{ this object is locked}
Postcondition
{ this object is locked, in range objects are updated with the new position }
Parameters
lightUpdate if true a standalone message is sent to the in range objects
Definition at line 1047 of file SceneObjectImplementation.cpp.
References _this, and zoneComponent.
Referenced by server::zone::objects::creature::AiAgentImplementation::checkNewAngle(), server::zone::objects::creature::AiAgentImplementation::updateCurrentPosition(), and server::zone::objects::scene::SceneObject::updateZone().
void SceneObjectImplementation::updateZoneWithParent (SceneObject * newParent, bool lightUpdate, bool sendPackets = true) virtual
Updates position and/or parent of this object and to the rest of in range objects
Precondition
{ this object is locked, newParent is a CellObject }
Postcondition
{this object is locked, in range objects are updated of the new position and parent }
Parameters
newParent cellObject where this object is
lightUpdate if true a standalone message is sent to the in range objects
Definition at line 1073 of file SceneObjectImplementation.cpp.
References _this, and zoneComponent.
Referenced by server::zone::objects::creature::AiAgentImplementation::checkNewAngle(), server::zone::objects::creature::AiAgentImplementation::updateCurrentPosition(), and server::zone::objects::scene::SceneObject::updateZoneWithParent().
void SceneObjectImplementation::wlock (bool doLock = true) protected
Definition at line 3816 of file SceneObject.cpp.
References _this.
void SceneObjectImplementation::wlock (ManagedObject * obj) protected
Definition at line 3820 of file SceneObject.cpp.
References _this.
void SceneObjectImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::player::PlayerObjectImplementation, server::zone::objects::creature::AiAgentImplementation, server::zone::objects::tangible::TangibleObjectImplementation, server::zone::objects::creature::ai::AiActorImplementation, server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::structure::StructureObjectImplementation, server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation, server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::mission::MissionObjectImplementation, server::zone::objects::installation::InstallationObjectImplementation, server::zone::objects::manufactureschematic::ManufactureSchematicImplementation, server::zone::ZoneImplementation, server::zone::objects::creature::VehicleObjectImplementation, server::zone::objects::resource::ResourceSpawnImplementation, server::zone::objects::tangible::component::dna::DnaComponentImplementation, server::zone::objects::guild::GuildObjectImplementation, server::zone::objects::tangible::wearables::ArmorObjectImplementation, server::zone::objects::tangible::tool::CraftingToolImplementation, server::zone::objects::draftschematic::DraftSchematicImplementation, server::zone::objects::tangible::consumable::ConsumableImplementation, server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation, server::zone::objects::creature::CreatureImplementation, server::zone::objects::tangible::pharmaceutical::DotPackImplementation, server::zone::objects::area::CampSiteActiveAreaImplementation, server::zone::objects::tangible::InstrumentImplementation, server::zone::objects::tangible::tool::recycle::RecycleToolImplementation, server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation, server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation, server::zone::objects::installation::factory::FactoryObjectImplementation, server::zone::objects::tangible::component::genetic::GeneticComponentImplementation, server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation, server::zone::objects::tangible::pharmaceutical::WoundPackImplementation, server::zone::objects::factorycrate::FactoryCrateImplementation, server::zone::objects::intangible::VehicleControlDeviceImplementation, server::zone::objects::tangible::pharmaceutical::CurePackImplementation, server::zone::objects::tangible::pharmaceutical::RevivePackImplementation, server::zone::objects::tangible::pharmaceutical::StimPackImplementation, server::zone::objects::tangible::tool::SurveyToolImplementation, server::zone::objects::tangible::pharmaceutical::StatePackImplementation, server::zone::objects::group::GroupObjectImplementation, server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation, server::zone::objects::tangible::component::ComponentImplementation, server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation, server::zone::objects::area::ActiveAreaImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, server::zone::objects::area::DynamicSpawnAreaImplementation, server::zone::objects::cell::CellObjectImplementation, server::zone::objects::resource::ResourceContainerImplementation, server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation, server::zone::objects::tangible::attachement::AttachmentImplementation, server::zone::objects::tangible::ticket::TicketObjectImplementation, server::zone::objects::waypoint::WaypointObjectImplementation, server::zone::objects::tangible::fishing::FishingPoleObjectImplementation, server::zone::objects::tangible::fishing::FishObjectImplementation, server::zone::objects::installation::shuttle::ShuttleInstallationImplementation, server::zone::objects::creature::aigroup::AiGroupImplementation, server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation, server::zone::objects::tangible::ContainerImplementation, server::zone::objects::tangible::wearables::WearableObjectImplementation, server::zone::objects::tangible::firework::FireworkObjectImplementation, server::zone::objects::tangible::deed::pet::PetDeedImplementation, server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation, server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation, server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation, server::zone::objects::intangible::ControlDeviceImplementation, server::zone::objects::tangible::tool::repair::RepairToolImplementation, server::zone::objects::tangible::deed::ResourceDeedImplementation, server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation, server::zone::objects::installation::harvester::HarvesterObjectImplementation, server::zone::objects::tangible::deed::structure::StructureDeedImplementation, server::zone::objects::area::LairSpawnAreaImplementation, server::zone::objects::tangible::deed::DeedImplementation, server::zone::objects::tangible::loot::LootkitObjectImplementation, server::zone::objects::tangible::component::armor::ArmorComponentImplementation, server::zone::objects::region::RegionImplementation, server::zone::objects::area::SpawnAreaImplementation, server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation, server::zone::objects::installation::GeneratorObjectImplementation, server::zone::objects::tangible::terminal::ticketcollector::TicketCollectorImplementation, server::zone::objects::tangible::powerup::PowerupObjectImplementation, server::zone::objects::tangible::fishing::FishingBaitObjectImplementation, server::zone::objects::tangible::wearables::WearableContainerObjectImplementation, server::zone::objects::area::StaticSpawnAreaImplementation, server::zone::objects::tangible::terminal::startinglocation::StartingLocationTerminalImplementation, server::zone::objects::area::MissionReconActiveAreaImplementation, server::zone::objects::tangible::terminal::TerminalImplementation, server::zone::objects::intangible::IntangibleObjectImplementation, server::zone::objects::area::MissionSpawnActiveAreaImplementation, server::zone::objects::intangible::ShipControlDeviceImplementation, server::zone::objects::tangible::sign::SignObjectImplementation, server::zone::objects::area::BadgeActiveAreaImplementation, server::zone::objects::creature::NonPlayerCreatureObjectImplementation, server::zone::objects::tangible::wearables::RobeObjectImplementation, server::zone::objects::tangible::wearables::PsgArmorObjectImplementation, server::zone::objects::staticobject::StaticObjectImplementation, server::zone::objects::tangible::wearables::ClothingObjectImplementation, server::zone::objects::building::hospital::HospitalBuildingObjectImplementation, server::zone::objects::building::recreation::RecreationBuildingObjectImplementation, server::zone::objects::tangible::consumable::DrinkImplementation, server::zone::objects::tangible::consumable::FoodImplementation, server::zone::objects::area::FsVillageAreaImplementation, server::zone::objects::ship::ShipObjectImplementation, server::zone::objects::tangible::tool::ToolTangibleObjectImplementation, server::zone::objects::area::GarageAreaImplementation, server::zone::objects::installation::garage::GarageInstallationImplementation, server::zone::objects::building::travel::TravelBuildingObjectImplementation, server::zone::objects::tangible::terminal::spaceship::SpaceshipTerminalImplementation, server::zone::objects::creature::aigroup::HerdGroupImplementation, server::zone::objects::creature::aigroup::LairGroupImplementation, server::zone::objects::creature::aigroup::PackGroupImplementation, server::zone::objects::ship::FighterShipObjectImplementation, and server::zone::objects::ship::SpaceStationObjectImplementation.
Definition at line 3956 of file SceneObject.cpp.
References writeObjectMembers().
int SceneObjectImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 3963 of file SceneObject.cpp.
References activeAreas, childObjects, clientObjectCRC, containerObjects, containerPermissions, containerType, containerVolumeLimit, containmentType, customName, dataObjectComponent, direction, gameObjectType, movementCounter, objectActiveSessions, objectName, planetMapCategory, planetMapSubCategory, sendToClient, serverObjectCRC, slottedObjects, staticObject, and zone.
Referenced by writeObject().
Friends And Related Function Documentation
friend class SceneObject friend
Definition at line 2312 of file SceneObject.h.
Member Data Documentation
WeakReference<SceneObject*> server::zone::objects::scene::SceneObjectImplementation::_this
Definition at line 2280 of file SceneObject.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), broadcastDestroy(), broadcastMessage(), broadcastMessages(), broadcastObject(), canAddObject(), checkContainerPermission(), close(), closeContainerTo(), createChildObjects(), destroyObjectFromDatabase(), destroyObjectFromWorld(), destroyPlayerCreatureFromDatabase(), fillObjectMenuResponse(), getObjectID(), getParent(), getParentRecursively(), getRootParent(), handleObjectMenuSelect(), initializeTransientMembers(), inRangeObjects(), lock(), notifyDissapear(), notifyInsert(), notifyInsertToZone(), notifyLoadFromDatabase(), notifyPositionUpdate(), notifyRemoveFromZone(), openContainerTo(), removeObject(), rlock(), runlock(), sendAttributeListTo(), sendDestroyTo(), sendTo(), sendWithoutContainerObjectsTo(), sendWithoutParentTo(), showFlyText(), switchZone(), teleport(), transferObject(), unlock(), updateDirection(), updateZone(), updateZoneWithParent(), and wlock().
SortedVector<ManagedReference<ActiveArea* > > server::zone::objects::scene::SceneObjectImplementation::activeAreas protected
Definition at line 1300 of file SceneObject.h.
Referenced by addActiveArea(), dropActiveArea(), getActiveAreas(), getActiveAreasSize(), getActiveRegion(), server::zone::objects::creature::CreatureObjectImplementation::getCurrentCamp(), hasActiveArea(), notifyLoadFromDatabase(), readObjectMember(), server::zone::objects::area::LairSpawnAreaImplementation::trySpawnLair(), and writeObjectMembers().
Reference<AttributeListComponent* > server::zone::objects::scene::SceneObjectImplementation::attributeListComponent protected
Definition at line 1252 of file SceneObject.h.
Referenced by createComponents(), and sendAttributeListTo().
SortedVector<ManagedReference<SceneObject* > > server::zone::objects::scene::SceneObjectImplementation::childObjects protected
Definition at line 1302 of file SceneObject.h.
Referenced by containsChildObject(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::destroyChildObjects(), destroyObjectFromDatabase(), destroyPlayerCreatureFromDatabase(), getChildObjects(), initializePrivateData(), readObjectMember(), server::zone::objects::building::BuildingObjectImplementation::spawnChildSceneObject(), and writeObjectMembers().
ManagedWeakReference<CityRegion* > server::zone::objects::scene::SceneObjectImplementation::cityRegion protected
Definition at line 1298 of file SceneObject.h.
Referenced by getCityRegion(), and setCityRegion().
unsigned int server::zone::objects::scene::SceneObjectImplementation::clientObjectCRC protected
Definition at line 1274 of file SceneObject.h.
Referenced by getClientObjectCRC(), initializePrivateData(), loadTemplateData(), readObjectMember(), server::zone::objects::draftschematic::DraftSchematicImplementation::sendDraftSlotsTo(), server::zone::objects::draftschematic::DraftSchematicImplementation::sendResourceWeightsTo(), setClientObjectCRC(), and writeObjectMembers().
Reference<ContainerComponent* > server::zone::objects::scene::SceneObjectImplementation::containerComponent protected
Definition at line 1254 of file SceneObject.h.
Referenced by canAddObject(), checkContainerPermission(), server::zone::ZoneImplementation::createContainerComponent(), createContainerComponent(), initializeTransientMembers(), removeObject(), setContainerComponent(), and transferObject().
ReadWriteLock server::zone::objects::scene::SceneObjectImplementation::containerLock protected
Definition at line 1306 of file SceneObject.h.
Referenced by addPendingTask(), containsPendingTask(), dropActiveArea(), dropSlottedObject(), getActiveRegion(), getContainedObjectsRecursive(), getContainerLock(), getContainerObjectRecursive(), getCountableObjectsRecursive(), getPendingTask(), getPendingTasks(), getSlottedObject(), getSlottedObjects(), hasActiveArea(), hasObjectInSlottedContainer(), removePendingTask(), and removeSlottedObject().
ContainerObjectsMap server::zone::objects::scene::SceneObjectImplementation::containerObjects protected
Definition at line 1310 of file SceneObject.h.
Referenced by getContainedObjectsRecursive(), getContainerObject(), getContainerObjectRecursive(), getContainerObjects(), getContainerObjectsSize(), getCountableObjectsRecursive(), hasFullContainerObjects(), hasObjectInContainer(), isContainerFull(), server::zone::objects::tangible::ContainerImplementation::loadTemplateData(), server::zone::objects::cell::CellObjectImplementation::notifyLoadFromDatabase(), notifyLoadFromDatabase(), putInContainer(), readObjectMember(), removeAllContainerObjects(), removeFromContainerObjects(), and writeObjectMembers().
ContainerPermissions server::zone::objects::scene::SceneObjectImplementation::containerPermissions protected
Definition at line 1270 of file SceneObject.h.
Referenced by clearContainerDefaultAllowPermission(), clearContainerDefaultDenyPermission(), getContainerPermissions(), readObjectMember(), server::zone::objects::cell::CellObjectImplementation::sendPermissionsTo(), setContainerAllowPermission(), setContainerDefaultAllowPermission(), setContainerDefaultDenyPermission(), setContainerDenyPermission(), setContainerInheritPermissionsFromParent(), setContainerOwnerID(), and writeObjectMembers().
unsigned int server::zone::objects::scene::SceneObjectImplementation::containerType protected
Definition at line 1266 of file SceneObject.h.
Referenced by getContainerType(), server::zone::objects::building::BuildingObjectImplementation::loadTemplateData(), loadTemplateData(), readObjectMember(), setContainerType(), and writeObjectMembers().
unsigned int server::zone::objects::scene::SceneObjectImplementation::containerVolumeLimit protected
Definition at line 1268 of file SceneObject.h.
Referenced by getContainerVolumeLimit(), hasFullContainerObjects(), isContainerFull(), server::zone::objects::building::BuildingObjectImplementation::loadTemplateData(), loadTemplateData(), readObjectMember(), setContainerVolumeLimit(), and writeObjectMembers().
unsigned int server::zone::objects::scene::SceneObjectImplementation::containmentType protected
Definition at line 1290 of file SceneObject.h.
Referenced by canAddObject(), getContainmentType(), initializePrivateData(), readObjectMember(), setContainmentType(), transferObject(), and writeObjectMembers().
UnicodeString server::zone::objects::scene::SceneObjectImplementation::customName protected
Definition at line 1296 of file SceneObject.h.
Referenced by getCustomObjectName(), getDisplayedName(), server::zone::objects::waypoint::WaypointObjectImplementation::insertToMessage(), readObjectMember(), server::zone::objects::tangible::TangibleObjectImplementation::setCustomObjectName(), setCustomObjectName(), and writeObjectMembers().
DataObjectComponentReference server::zone::objects::scene::SceneObjectImplementation::dataObjectComponent protected
Definition at line 1262 of file SceneObject.h.
Referenced by server::zone::objects::installation::InstallationObjectImplementation::createChildObjects(), destroyObjectFromDatabase(), destroyPlayerCreatureFromDatabase(), server::zone::objects::installation::InstallationObjectImplementation::fillAttributeList(), getDataObjectComponent(), initializeTransientMembers(), isDetector(), isGCWBase(), isMinefield(), isSecurityTerminal(), isTurret(), isTurretControlTerminal(), isVendor(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
Quaternion server::zone::objects::scene::SceneObjectImplementation::direction protected
Definition at line 1276 of file SceneObject.h.
Referenced by createChildObjects(), server::zone::objects::creature::AiAgentImplementation::doMovement(), faceObject(), getCoordinate(), getDirection(), getDirectionAngle(), getDirectionW(), getDirectionX(), getDirectionY(), getDirectionZ(), getSpecialDirectionAngle(), getWorldCoordinate(), readObjectMember(), rotate(), setDirection(), updateVehiclePosition(), and writeObjectMembers().
unsigned int server::zone::objects::scene::SceneObjectImplementation::gameObjectType protected
Definition at line 1288 of file SceneObject.h.
Referenced by server::zone::objects::tangible::ContainerImplementation::canAddObject(), getGameObjectType(), getParentRecursively(), server::zone::objects::tangible::attachement::AttachmentImplementation::initializeMembers(), initializePrivateData(), inRangeObjects(), server::zone::objects::tangible::attachement::AttachmentImplementation::isArmorAttachment(), isBazaarTerminal(), isCampKit(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isCarbineWeapon(), server::zone::objects::tangible::attachement::AttachmentImplementation::isClothingAttachment(), isFishingBait(), isFishingPoleObject(), isGarage(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isHeavyWeapon(), isInstrument(), isLiveSample(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isMineWeapon(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isOneHandMeleeWeapon(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isPistolWeapon(), isPlayerObject(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isPolearmWeaponObject(), isPsgArmorObject(), isRecycleToolObject(), isRepairTool(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isRifleWeapon(), isShuttleInstallation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isSpecialHeavyWeapon(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isThrownWeapon(), isTrapObject(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isTwoHandMeleeWeapon(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isUnarmedWeapon(), isWaypointObject(), loadTemplateData(), readObjectMember(), setGameObjectType(), server::zone::objects::tangible::attachement::AttachmentImplementation::updateCraftingValues(), and writeObjectMembers().
unsigned int server::zone::objects::scene::SceneObjectImplementation::movementCounter protected
Definition at line 1278 of file SceneObject.h.
Referenced by server::zone::objects::creature::AiAgentImplementation::broadcastNextPositionUpdate(), server::zone::objects::creature::AiAgentImplementation::checkNewAngle(), getMovementCounter(), incrementMovementCounter(), initializePrivateData(), initializeTransientMembers(), readObjectMember(), setMovementCounter(), updateDirection(), and writeObjectMembers().
VectorMap<unsigned int, ManagedReference<Facade* > > server::zone::objects::scene::SceneObjectImplementation::objectActiveSessions protected
Definition at line 1286 of file SceneObject.h.
Referenced by addActiveSession(), containsActiveSession(), dropActiveSession(), getActiveSession(), getActiveSessionsCount(), getObjectActiveSessions(), initializePrivateData(), readObjectMember(), and writeObjectMembers().
Reference<ObjectMenuComponent* > server::zone::objects::scene::SceneObjectImplementation::objectMenuComponent protected
Definition at line 1250 of file SceneObject.h.
Referenced by createComponents(), fillObjectMenuResponse(), getObjectMenuComponent(), handleObjectMenuSelect(), initializeTransientMembers(), and setObjectMenuComponent().
StringId server::zone::objects::scene::SceneObjectImplementation::objectName protected
Definition at line 1280 of file SceneObject.h.
Referenced by getDisplayedName(), getObjectName(), getObjectNameStringIdFile(), getObjectNameStringIdName(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), loadTemplateData(), readObjectMember(), setObjectName(), and writeObjectMembers().
Mutex server::zone::objects::scene::SceneObjectImplementation::parentLock protected
Definition at line 1308 of file SceneObject.h.
Referenced by getParent(), getParentID(), and setParent().
Reference<PendingTasksMap* > server::zone::objects::scene::SceneObjectImplementation::pendingTasks protected
Definition at line 1282 of file SceneObject.h.
Referenced by containsPendingTask(), getPendingTask(), getPendingTasks(), initializePrivateData(), and removePendingTask().
int server::zone::objects::scene::SceneObjectImplementation::planetMapCategory protected
Definition at line 1292 of file SceneObject.h.
Referenced by getPlanetMapCategory(), getPlanetMapCategoryCRC(), initializePrivateData(), loadTemplateData(), readObjectMember(), setPlanetMapCategory(), and writeObjectMembers().
int server::zone::objects::scene::SceneObjectImplementation::planetMapSubCategory protected
Definition at line 1294 of file SceneObject.h.
Referenced by getPlanetMapSubCategory(), getPlanetMapSubCategoryCRC(), initializePrivateData(), loadTemplateData(), readObjectMember(), setPlanetMapSubCategory(), and writeObjectMembers().
bool server::zone::objects::scene::SceneObjectImplementation::sendToClient protected
Definition at line 1258 of file SceneObject.h.
Referenced by doSendToClient(), initializePrivateData(), readObjectMember(), sendTo(), sendWithoutContainerObjectsTo(), setSendToClient(), and writeObjectMembers().
ManagedReference<ZoneProcessServer* > server::zone::objects::scene::SceneObjectImplementation::server protected
Definition at line 1246 of file SceneObject.h.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addFriend(), server::zone::objects::creature::CreatureObjectImplementation::addSkill(), server::zone::objects::tangible::firework::FireworkObjectImplementation::completeLaunch(), server::zone::objects::installation::garage::GarageInstallationImplementation::createChildObjects(), server::zone::objects::installation::factory::FactoryObjectImplementation::createChildObjects(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), server::zone::objects::tangible::loot::LootkitObjectImplementation::createItem(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::createSellJunkLootSelection(), server::zone::objects::resource::ResourceSpawnImplementation::createSpawnMaps(), server::zone::objects::group::GroupObjectImplementation::destroyChatRoom(), destroyObjectFromDatabase(), destroyPlayerCreatureFromDatabase(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::doFishing(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), server::zone::objects::resource::ResourceSpawnImplementation::getPlanetCRC(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::getText(), getZoneProcessServer(), getZoneServer(), server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation::giveLanguages(), server::zone::objects::tangible::terminal::startinglocation::StartingLocationTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::SurveyToolImplementation::handleObjectMenuSelect(), server::zone::objects::installation::InstallationObjectImplementation::handleStructureAddEnergy(), initializePrivateData(), initializeTransientMembers(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::joinTerminal(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::leaveTerminal(), server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::player::PlayerObjectImplementation::notifyOffline(), server::zone::objects::player::PlayerObjectImplementation::notifyOnline(), server::zone::objects::creature::CreatureObjectImplementation::notifyPostureChange(), server::zone::objects::player::PlayerObjectImplementation::notifySceneReady(), server::zone::objects::building::BuildingObjectImplementation::promptPayAccessFee(), server::zone::objects::player::PlayerObjectImplementation::removeFriend(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::removeObject(), server::zone::objects::player::PlayerObjectImplementation::removeSchematics(), server::zone::objects::creature::CreatureObjectImplementation::removeSkill(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::selectConversationOption(), server::zone::objects::player::PlayerObjectImplementation::sendFriendLists(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendInsertManuSui(), server::zone::objects::tangible::tool::SurveyToolImplementation::sendRadioactiveWarning(), server::zone::objects::tangible::tool::SurveyToolImplementation::sendRangeSui(), server::zone::objects::creature::VehicleObjectImplementation::sendRepairConfirmTo(), server::zone::objects::creature::CreatureObjectImplementation::sendToOwner(), setZoneProcessServer(), server::zone::objects::intangible::VehicleControlDeviceImplementation::spawnObject(), server::zone::objects::factorycrate::FactoryCrateImplementation::split(), server::zone::objects::group::GroupObjectImplementation::startChatRoom(), server::zone::objects::installation::factory::FactoryObjectImplementation::stopFactory(), server::zone::objects::tangible::attachement::AttachmentImplementation::updateCraftingValues(), server::zone::objects::building::BuildingObjectImplementation::updatePaidAccessList(), and server::zone::objects::tangible::deed::ResourceDeedImplementation::useObject().
unsigned int server::zone::objects::scene::SceneObjectImplementation::serverObjectCRC protected
Definition at line 1272 of file SceneObject.h.
Referenced by getServerObjectCRC(), initializePrivateData(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::initializeTransientMembers(), initializeTransientMembers(), readObjectMember(), setServerObjectCRC(), server::zone::objects::tangible::InstrumentImplementation::spawnInForeignCell(), server::zone::objects::tangible::InstrumentImplementation::spawnOutside(), and writeObjectMembers().
VectorMap<String, ManagedReference<SceneObject* > > server::zone::objects::scene::SceneObjectImplementation::slottedObjects protected
Definition at line 1304 of file SceneObject.h.
Referenced by dropSlottedObject(), getSlottedObject(), getSlottedObjects(), getSlottedObjectsSize(), hasObjectInSlottedContainer(), notifyLoadFromDatabase(), readObjectMember(), removeSlottedObject(), and writeObjectMembers().
bool server::zone::objects::scene::SceneObjectImplementation::staticObject protected
Definition at line 1284 of file SceneObject.h.
Referenced by initializePrivateData(), isStaticObject(), server::zone::objects::structure::StructureObjectImplementation::notifyInsertToZone(), readObjectMember(), sendDestroyTo(), setClientObject(), and writeObjectMembers().
Reference<SharedObjectTemplate* > server::zone::objects::scene::SceneObjectImplementation::templateObject protected
Definition at line 1256 of file SceneObject.h.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::addTemplateSkillMods(), server::zone::objects::structure::StructureObjectImplementation::addTemplateSkillMods(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), createChildObjects(), createComponents(), createContainerComponent(), server::zone::objects::tangible::TangibleObjectImplementation::createFactoryCrate(), server::zone::objects::structure::StructureObjectImplementation::getAABBTree(), getArrangementDescriptor(), getArrangementDescriptorSize(), getClientGameObjectType(), getDetailedDescription(), server::zone::objects::structure::StructureObjectImplementation::getLotSize(), server::zone::objects::building::BuildingObjectImplementation::getMaximumNumberOfPlayerItems(), getObjectTemplate(), getSlotDescriptor(), getSlotDescriptorSize(), server::zone::objects::building::BuildingObjectImplementation::getTemplateEjectionPoint(), server::zone::objects::tangible::TangibleObjectImplementation::getTemplateSkillMods(), hasArrangementDescriptor(), server::zone::objects::building::BuildingObjectImplementation::hasTemplateEjectionPoint(), initializePrivateData(), server::zone::objects::tangible::deed::structure::StructureDeedImplementation::initializeTransientMembers(), initializeTransientMembers(), isCamoKit(), server::zone::objects::structure::StructureObjectImplementation::isCampStructure(), server::zone::objects::structure::StructureObjectImplementation::isCivicStructure(), server::zone::objects::structure::StructureObjectImplementation::isCommercialStructure(), isCreatureHabitat(), isDecoration(), isDiceObject(), isNoTrade(), loadTemplateData(), server::zone::objects::creature::AiAgentImplementation::notifyDespawn(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::tangible::TangibleObjectImplementation::removeTemplateSkillMods(), server::zone::objects::structure::StructureObjectImplementation::removeTemplateSkillMods(), setContainerComponent(), setObjectMenuComponent(), server::zone::objects::mission::MissionObjectImplementation::setTargetTemplate(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::updateCraftingValues().
Reference<Matrix4* > server::zone::objects::scene::SceneObjectImplementation::transformForCollisionMatrix protected
Definition at line 1264 of file SceneObject.h.
Referenced by getTransformForCollisionMatrix(), and setTransformForCollisionMatrixIfNull().
ZoneReference server::zone::objects::scene::SceneObjectImplementation::zone protected
Definition at line 1260 of file SceneObject.h.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addPermissionGroup(), server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership(), broadcastDestroyPrivate(), broadcastMessagePrivate(), broadcastMessagesPrivate(), broadcastObjectPrivate(), server::zone::objects::tangible::TangibleObjectImplementation::broadcastPvpStatusBitmask(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::resource::ResourceSpawnImplementation::createSpawnMaps(), server::zone::objects::intangible::VehicleControlDeviceImplementation::destroyObjectFromDatabase(), server::zone::objects::building::BuildingObjectImplementation::destroyObjectFromDatabase(), server::zone::objects::player::PlayerObjectImplementation::destroyObjectFromDatabase(), server::zone::objects::building::BuildingObjectImplementation::ejectObject(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), server::zone::objects::building::BuildingObjectImplementation::getEjectionPoint(), getLocalZone(), server::zone::objects::resource::ResourceSpawnImplementation::getPlanetCRC(), getZone(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::handleObjectMenuSelect(), initializePrivateData(), inRangeObjects(), server::zone::objects::creature::ai::AiActorImplementation::notifyDespawn(), server::zone::objects::creature::AiAgentImplementation::notifyDespawn(), server::zone::objects::building::BuildingObjectImplementation::notifyLoadFromDatabase(), notifyLoadFromDatabase(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), server::zone::objects::area::LairSpawnAreaImplementation::notifyObserverEvent(), server::zone::objects::player::PlayerObjectImplementation::notifySceneReady(), readObjectMember(), server::zone::objects::player::PlayerObjectImplementation::removePermissionGroup(), server::zone::objects::creature::CreatureObjectImplementation::sendBaselinesTo(), server::zone::objects::player::PlayerObjectImplementation::setFactionStatus(), setZone(), server::zone::objects::building::BuildingObjectImplementation::spawnChildCreature(), server::zone::objects::building::BuildingObjectImplementation::spawnChildCreaturesFromTemplate(), server::zone::objects::building::BuildingObjectImplementation::spawnChildSceneObject(), server::zone::objects::intangible::VehicleControlDeviceImplementation::spawnObject(), server::zone::objects::intangible::ShipControlDeviceImplementation::storeObject(), server::zone::objects::cell::CellObjectImplementation::transferObject(), server::zone::objects::area::LairSpawnAreaImplementation::trySpawnLair(), and writeObjectMembers().
Reference<ZoneComponent* > server::zone::objects::scene::SceneObjectImplementation::zoneComponent protected
Definition at line 1248 of file SceneObject.h.
Referenced by createComponents(), destroyObjectFromWorld(), getZoneComponent(), initializeTransientMembers(), notifyDissapear(), notifyInsert(), notifyInsertToZone(), notifyPositionUpdate(), notifyRemoveFromZone(), setZoneComponent(), switchZone(), teleport(), updateZone(), and updateZoneWithParent().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/SceneObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/SceneObject.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/SceneObjectImplementation.cpp