Core3: ChatPersistentMessageToClient Class Reference
ChatPersistentMessageToClient Class Reference
#include <ChatPersistentMessageToClient.h>
Public Member Functions
ChatPersistentMessageToClient (const String &sender, uint32 mailid, uint8 type, const UnicodeString &subject, const UnicodeString &body, uint32 timestamp=0, char status= 'N')
ChatPersistentMessageToClient (const String &sender, uint32 mailid, uint8 type, const UnicodeString &subject, StringIdChatParameter &body, uint32 timestamp=0, char status= 'N')
ChatPersistentMessageToClient (PersistentMessage *mail, bool sendBody)
Private Member Functions
void insertParameters (PersistentMessage *mail)
Detailed Description
Definition at line 55 of file ChatPersistentMessageToClient.h.
Constructor & Destructor Documentation
ChatPersistentMessageToClient::ChatPersistentMessageToClient (const String & sender, uint32 mailid, uint8 type, const UnicodeString & subject, const UnicodeString & body, uint32 timestamp = 0, char status = 'N') inline
Definition at line 87 of file ChatPersistentMessageToClient.h.
ChatPersistentMessageToClient::ChatPersistentMessageToClient (const String & sender, uint32 mailid, uint8 type, const UnicodeString & subject, StringIdChatParameter & body, uint32 timestamp = 0, char status = 'N') inline
Definition at line 122 of file ChatPersistentMessageToClient.h.
References server::chat::ChatParameter::insertToMessage().
ChatPersistentMessageToClient::ChatPersistentMessageToClient (PersistentMessage * mail, bool sendBody) inline
Definition at line 156 of file ChatPersistentMessageToClient.h.
References server::chat::PersistentMessage::getBody(), server::chat::PersistentMessage::getMailID(), server::chat::PersistentMessage::getSenderName(), server::chat::PersistentMessage::getStatus(), server::chat::PersistentMessage::getSubject(), server::chat::PersistentMessage::getTimeStamp(), and insertParameters().
Member Function Documentation
void ChatPersistentMessageToClient::insertParameters (PersistentMessage * mail) inline private
Definition at line 56 of file ChatPersistentMessageToClient.h.
References server::chat::PersistentMessage::getStringIdParameters(), server::chat::PersistentMessage::getWaypointParameters(), and server::chat::ChatParameter::insertToMessage().
Referenced by ChatPersistentMessageToClient().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/chat/ChatPersistentMessageToClient.h