Core3: server::zone::objects::player::sessions::vendor::CreateVendorSession Class Reference
server::zone::objects::player::sessions::vendor::CreateVendorSession Class Reference
#include <CreateVendorSession.h>
Public Member Functions
CreateVendorSession (CreatureObject *play)
int initializeSession ()
int cancelSession ()
int clearSession ()
void handleVendorSelection (byte menuID)
void createVendor (String &name)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
CreateVendorSession (DummyConstructorParameter *param)
virtual ~CreateVendorSession ()
Friends
class CreateVendorSessionHelper
Detailed Description
Definition at line 95 of file CreateVendorSession.h.
Constructor & Destructor Documentation
CreateVendorSession::CreateVendorSession (CreatureObject * play)
Definition at line 21 of file CreateVendorSession.cpp.
References server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::_setStub().
CreateVendorSession::CreateVendorSession (DummyConstructorParameter * param) protected
Definition at line 28 of file CreateVendorSession.cpp.
CreateVendorSession::~CreateVendorSession () protected virtual
Definition at line 32 of file CreateVendorSession.cpp.
Member Function Documentation
DistributedObjectServant * CreateVendorSession::_getImplementation ()
Definition at line 104 of file CreateVendorSession.cpp.
Referenced by cancelSession(), clearSession(), createVendor(), handleVendorSelection(), and initializeSession().
DistributedObjectServant * CreateVendorSession::_getImplementationForRead ()
Definition at line 110 of file CreateVendorSession.cpp.
void CreateVendorSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 114 of file CreateVendorSession.cpp.
int CreateVendorSession::cancelSession ()
Definition at line 50 of file CreateVendorSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
Referenced by CreateVendorSuiCallback::run(), and NameVendorSuiCallback::run().
int CreateVendorSession::clearSession ()
Definition at line 63 of file CreateVendorSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
void CreateVendorSession::createVendor (String & name)
Definition at line 90 of file CreateVendorSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::createVendor(), and RPC_CREATEVENDOR__STRING_.
void CreateVendorSession::handleVendorSelection (byte menuID)
Definition at line 76 of file CreateVendorSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::handleVendorSelection(), and RPC_HANDLEVENDORSELECTION__BYTE_.
int CreateVendorSession::initializeSession ()
Definition at line 37 of file CreateVendorSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
Friends And Related Function Documentation
friend class CreateVendorSessionHelper friend
Definition at line 119 of file CreateVendorSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/CreateVendorSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/CreateVendorSession.cpp