Core3: server::zone::objects::player::sessions::DestroyStructureSession Class Reference
server::zone::objects::player::sessions::DestroyStructureSession Class Reference
#include <DestroyStructureSession.h>
Public Member Functions
DestroyStructureSession (CreatureObject *creature, StructureObject *structure)
bool isDestroyCode (unsigned int code)
int initializeSession ()
int sendDestroyCode ()
int destroyStructure ()
int cancelSession ()
int clearSession ()
StructureObject * getStructureObject ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
DestroyStructureSession (DummyConstructorParameter *param)
virtual ~DestroyStructureSession ()
Friends
class DestroyStructureSessionHelper
Detailed Description
Definition at line 66 of file DestroyStructureSession.h.
Constructor & Destructor Documentation
DestroyStructureSession::DestroyStructureSession (CreatureObject * creature, StructureObject * structure)
Definition at line 19 of file DestroyStructureSession.cpp.
References server::zone::objects::player::sessions::DestroyStructureSessionImplementation::_setStub().
DestroyStructureSession::DestroyStructureSession (DummyConstructorParameter * param) protected
Definition at line 26 of file DestroyStructureSession.cpp.
DestroyStructureSession::~DestroyStructureSession () protected virtual
Definition at line 30 of file DestroyStructureSession.cpp.
Member Function Documentation
DistributedObjectServant * DestroyStructureSession::_getImplementation ()
Definition at line 127 of file DestroyStructureSession.cpp.
Referenced by cancelSession(), clearSession(), destroyStructure(), getStructureObject(), initializeSession(), isDestroyCode(), and sendDestroyCode().
DistributedObjectServant * DestroyStructureSession::_getImplementationForRead ()
Definition at line 133 of file DestroyStructureSession.cpp.
void DestroyStructureSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 137 of file DestroyStructureSession.cpp.
int DestroyStructureSession::cancelSession ()
Definition at line 88 of file DestroyStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::DestroyStructureSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
Referenced by DestroyStructureRequestSuiCallback::run(), and DestroyStructureCodeSuiCallback::run().
int DestroyStructureSession::clearSession ()
Definition at line 101 of file DestroyStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::DestroyStructureSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
int DestroyStructureSession::destroyStructure ()
Definition at line 75 of file DestroyStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::DestroyStructureSessionImplementation::destroyStructure(), and RPC_DESTROYSTRUCTURE__.
StructureObject * DestroyStructureSession::getStructureObject ()
Definition at line 114 of file DestroyStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::DestroyStructureSessionImplementation::getStructureObject(), and RPC_GETSTRUCTUREOBJECT__.
Referenced by StructureManager::redeedStructure().
int DestroyStructureSession::initializeSession ()
Definition at line 49 of file DestroyStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::DestroyStructureSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
bool DestroyStructureSession::isDestroyCode (unsigned int code)
Definition at line 35 of file DestroyStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::DestroyStructureSessionImplementation::isDestroyCode(), and RPC_ISDESTROYCODE__INT_.
int DestroyStructureSession::sendDestroyCode ()
Definition at line 62 of file DestroyStructureSession.cpp.
References _getImplementation(), RPC_SENDDESTROYCODE__, and server::zone::objects::player::sessions::DestroyStructureSessionImplementation::sendDestroyCode().
Friends And Related Function Documentation
friend class DestroyStructureSessionHelper friend
Definition at line 94 of file DestroyStructureSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/DestroyStructureSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/DestroyStructureSession.cpp