Core3: StatusServer Class Reference
StatusServer Class Reference
#include <StatusServer.h>
Public Member Functions
StatusServer (ConfigManager *conf, ZoneServer *server)
~StatusServer ()
void init ()
void run ()
void shutdown ()
ServiceClient * createConnection (Socket *sock, SocketAddress &addr)
Packet * getStatusXMLPacket ()
bool testZone ()
Private Attributes
ZoneServer * zoneServer
StatusHandler * statusHandler
ConfigManager * configManager
unsigned int statusInterval
Time timestamp
bool lastStatus
uint64 oid
Detailed Description
Definition at line 58 of file StatusServer.h.
Constructor & Destructor Documentation
StatusServer::StatusServer (ConfigManager * conf, ZoneServer * server)
Definition at line 49 of file StatusServer.cpp.
References configManager, server::conf::ConfigManager::getStatusInterval(), statusHandler, statusInterval, and zoneServer.
StatusServer::~StatusServer ()
Definition at line 62 of file StatusServer.cpp.
Member Function Documentation
ServiceClient * StatusServer::createConnection (Socket * sock, SocketAddress & addr)
Definition at line 89 of file StatusServer.cpp.
References getStatusXMLPacket().
Referenced by StatusHandler::createConnection().
Packet * StatusServer::getStatusXMLPacket ()
Definition at line 107 of file StatusServer.cpp.
References server::zone::ZoneServer::getConnectionCount(), server::zone::ZoneServer::getDeletedPlayers(), server::zone::ZoneServer::getGalaxyName(), server::zone::ZoneServer::getMaxPlayers(), server::zone::ZoneServer::getServerCap(), server::zone::ZoneServer::getStartTimestamp(), server::zone::ZoneServer::getTotalPlayers(), lastStatus, testZone(), timestamp, and zoneServer.
Referenced by createConnection().
void StatusServer::init ()
Definition at line 66 of file StatusServer.cpp.
References lastStatus, statusHandler, timestamp, and zoneServer.
void StatusServer::run ()
Definition at line 80 of file StatusServer.cpp.
References shutdown().
void StatusServer::shutdown ()
Definition at line 86 of file StatusServer.cpp.
Referenced by run().
bool StatusServer::testZone ()
Definition at line 139 of file StatusServer.cpp.
References lastStatus, statusInterval, timestamp, and zoneServer.
Referenced by getStatusXMLPacket().
Member Data Documentation
ConfigManager* StatusServer::configManager private
Definition at line 62 of file StatusServer.h.
Referenced by StatusServer().
bool StatusServer::lastStatus private
Definition at line 67 of file StatusServer.h.
Referenced by getStatusXMLPacket(), init(), and testZone().
uint64 StatusServer::oid private
Definition at line 70 of file StatusServer.h.
StatusHandler* StatusServer::statusHandler private
Definition at line 60 of file StatusServer.h.
Referenced by init(), and StatusServer().
unsigned int StatusServer::statusInterval private
Definition at line 64 of file StatusServer.h.
Referenced by StatusServer(), and testZone().
Time StatusServer::timestamp private
Definition at line 66 of file StatusServer.h.
Referenced by getStatusXMLPacket(), init(), and testZone().
ZoneServer* StatusServer::zoneServer private
Definition at line 59 of file StatusServer.h.
Referenced by getStatusXMLPacket(), init(), StatusServer(), and testZone().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/status/StatusServer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/status/StatusServer.cpp