Core3: TotalHealOtherCommand Class Reference
TotalHealOtherCommand Class Reference
#include <TotalHealOtherCommand.h>
Public Member Functions
TotalHealOtherCommand (const String &name, ZoneProcessServer *server)
void doAnimations (CreatureObject *creature, CreatureObject *creatureTarget)
bool checkTarget (CreatureObject *creature, CreatureObject *creatureTarget)
void sendWoundMessage (CreatureObject *object, CreatureObject *target, int healthWound, int actionWound, int mindWound, int strengthWound, int constitutionWound, int quicknessWound, int staminaWound, int focusWound, int willpowerWound)
void sendHealMessage (CreatureObject *object, CreatureObject *target, int healthDamage, int actionDamage, int mindDamage)
bool canPerformSkill (CreatureObject *creature, CreatureObject *creatureTarget)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Public Member Functions inherited from server::zone::objects::creature::commands::QueueCommand
QueueCommand (const String &skillname, ZoneProcessServer *serv)
virtual ~QueueCommand ()
bool checkInvalidLocomotions (CreatureObject *creature)
void onStateFail (CreatureObject *creature, uint32 actioncntr)
void onLocomotionFail (CreatureObject *creature, uint32 actioncntr)
virtual String getSyntax () const
virtual void onFail (uint32 actioncntr, CreatureObject *creature, uint32 errorNumber)
virtual void onComplete (uint32 actioncntr, CreatureObject *creature, float commandDuration)
void setInvalidLocomotions (const String &lStr)
void addInvalidLocomotion (int l)
bool checkStateMask (CreatureObject *creature)
virtual float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
void setStateMask (uint64 mask)
void setDefaultTime (float time)
void setTargetType (int num)
void setDisabled (bool state)
void setDisabled (int state)
void setAddToCombatQueue (bool state)
void setAddToCombatQueue (int state)
void setCommandGroup (int val)
void setMaxRange (float r)
void setCharacterAbility (const String &ability)
void setDefaultPriority (const String &priority)
void setDefaultPriority (const int priority)
uint64 getStateMask ()
bool requiresAdmin ()
int getTargetType ()
uint32 getNameCRC ()
float getMaxRange ()
String & getQueueCommandName ()
String & getCharacterAbility ()
float getDefaultTime ()
int getDefaultPriority ()
bool isDisabled ()
bool addToCombatQueue ()
virtual bool isCombatCommand ()
int getSkillModSize ()
int getSkillMod (int index, String &skillMod)
int getCommandGroup ()
void addSkillMod (const String &skillMod, const int value)
bool isWearingArmor (CreatureObject *creo)
virtual void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Protected Attributes
int forceCost
int heal
int healthHealed
int actionHealed
int mindHealed
int healthWoundHealed
int strengthWoundHealed
int constitutionWoundHealed
int actionWoundHealed
int quicknessWoundHealed
int staminaWoundHealed
int mindWoundHealed
int focusWoundHealed
int willpowerWoundHealed
float speed
float range
String effectName
Protected Attributes inherited from server::zone::objects::creature::commands::QueueCommand
ZoneProcessServer * server
String name
uint32 nameCRC
uint64 stateMask
Vector< int > invalidLocomotion
int targetType
int maxRangeToTarget
bool disabled
bool addToQueue
bool admin
uint32 cooldown
float defaultTime
String characterAbility
int defaultPriority
VectorMap< String, int > skillMods
int commandGroup
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::creature::commands::QueueCommand
static const int IMMEDIATE = 0
static const int FRONT = 1
static const int NORMAL = 2
static const int SUCCESS = 0
static const int GENERALERROR = 1
static const int INVALIDLOCOMOTION = 2
static const int INVALIDSTATE = 3
static const int INVALIDTARGET = 4
static const int INVALIDWEAPON = 5
static const int TOOFAR = 6
static const int INSUFFICIENTHAM = 7
static const int INVALIDPARAMETERS = 8
static const int NOPRONE = 9
static const int NOKNEELING = 10
static const int INSUFFICIENTPERMISSION = 11
static const int NOJEDIARMOR = 12
static const int INVALIDSYNTAX = 13
Detailed Description
Definition at line 58 of file TotalHealOtherCommand.h.
Constructor & Destructor Documentation
TotalHealOtherCommand::TotalHealOtherCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 85 of file TotalHealOtherCommand.h.
References actionHealed, actionWoundHealed, constitutionWoundHealed, focusWoundHealed, forceCost, heal, healthHealed, healthWoundHealed, mindHealed, mindWoundHealed, quicknessWoundHealed, speed, staminaWoundHealed, strengthWoundHealed, and willpowerWoundHealed.
Member Function Documentation
bool TotalHealOtherCommand::canPerformSkill (CreatureObject * creature, CreatureObject * creatureTarget) inline
Definition at line 294 of file TotalHealOtherCommand.h.
References CreatureAttribute::ACTION, CreatureState::BLINDED, CollisionManager::checkLineOfSight(), CreatureAttribute::CONSTITUTION, CreatureState::DIZZY, CreatureAttribute::FOCUS, server::zone::ZoneProcessServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getWounds(), server::zone::objects::creature::CreatureObject::hasDamage(), server::zone::objects::creature::CreatureObject::hasState(), CreatureAttribute::HEALTH, CreatureState::INTIMIDATED, server::zone::objects::creature::CreatureObject::isBleeding(), server::zone::objects::creature::CreatureObject::isDiseased(), server::zone::objects::creature::CreatureObject::isPoisoned(), server::zone::objects::creature::CreatureObject::isProne(), CreatureAttribute::MIND, CreatureAttribute::QUICKNESS, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::commands::QueueCommand::server, CreatureAttribute::STAMINA, CreatureAttribute::STRENGTH, CreatureState::STUNNED, and CreatureAttribute::WILLPOWER.
Referenced by doQueueCommand().
bool TotalHealOtherCommand::checkTarget (CreatureObject * creature, CreatureObject * creatureTarget) inline
Definition at line 118 of file TotalHealOtherCommand.h.
References CreatureAttribute::ACTION, CreatureState::BLINDED, CollisionManager::checkLineOfSight(), CreatureAttribute::CONSTITUTION, CreatureState::DIZZY, CreatureAttribute::FOCUS, server::zone::ZoneProcessServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getWounds(), server::zone::objects::creature::CreatureObject::hasDamage(), server::zone::objects::creature::CreatureObject::hasState(), CreatureAttribute::HEALTH, CreatureState::INTIMIDATED, server::zone::objects::creature::CreatureObject::isBleeding(), server::zone::objects::creature::CreatureObject::isDiseased(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isPoisoned(), CreatureAttribute::MIND, CreatureAttribute::QUICKNESS, server::zone::objects::creature::commands::QueueCommand::server, CreatureAttribute::STAMINA, CreatureAttribute::STRENGTH, CreatureState::STUNNED, and CreatureAttribute::WILLPOWER.
void TotalHealOtherCommand::doAnimations (CreatureObject * creature, CreatureObject * creatureTarget) inline
Definition at line 111 of file TotalHealOtherCommand.h.
References server::zone::objects::creature::CreatureObject::doCombatAnimation(), and server::zone::objects::creature::CreatureObject::playEffect().
Referenced by doQueueCommand().
int TotalHealOtherCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline virtual
Reimplemented from server::zone::objects::creature::commands::QueueCommand.
Definition at line 314 of file TotalHealOtherCommand.h.
References CreatureAttribute::ACTION, server::zone::objects::creature::CreatureObject::addShockWounds(), CreatureState::BLEEDING, CreatureState::BLINDED, canPerformSkill(), server::zone::objects::creature::commands::QueueCommand::checkInvalidLocomotions(), server::zone::objects::creature::commands::QueueCommand::checkStateMask(), CreatureAttribute::CONSTITUTION, CreatureState::DISEASED, CreatureState::DIZZY, doAnimations(), CreatureAttribute::FOCUS, forceCost, server::zone::objects::creature::commands::QueueCommand::GENERALERROR, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::player::PlayerObject::getFactionStatus(), server::zone::ZoneServer::getObject(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::ZoneProcessServer::getZoneServer(), heal, server::zone::objects::creature::CreatureObject::healDamage(), server::zone::objects::creature::CreatureObject::healDot(), CreatureAttribute::HEALTH, server::zone::objects::creature::CreatureObject::healWound(), CreatureState::INTIMIDATED, server::zone::objects::creature::commands::QueueCommand::INVALIDLOCOMOTION, server::zone::objects::creature::commands::QueueCommand::INVALIDSTATE, server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::tangible::TangibleObject::isAttackableBy(), server::zone::objects::creature::CreatureObject::isAttackableBy(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isHealableBy(), server::zone::objects::creature::CreatureObject::isMounted(), server::zone::objects::creature::CreatureObject::isRidingCreature(), server::zone::objects::creature::commands::QueueCommand::isWearingArmor(), CreatureAttribute::MIND, server::zone::objects::creature::commands::QueueCommand::NOJEDIARMOR, FactionStatus::ONLEAVE, CreatureState::POISONED, CreatureAttribute::QUICKNESS, server::zone::objects::creature::CreatureObject::removeStateBuff(), sendHealMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), sendWoundMessage(), server::zone::objects::creature::commands::QueueCommand::server, CreatureAttribute::STAMINA, CreatureAttribute::STRENGTH, CreatureState::STUNNED, server::zone::objects::creature::commands::QueueCommand::SUCCESS, and CreatureAttribute::WILLPOWER.
void TotalHealOtherCommand::sendHealMessage (CreatureObject * object, CreatureObject * target, int healthDamage, int actionDamage, int mindDamage) inline
Definition at line 257 of file TotalHealOtherCommand.h.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::chat::StringIdChatParameter::setTT().
Referenced by doQueueCommand().
void TotalHealOtherCommand::sendWoundMessage (CreatureObject * object, CreatureObject * target, int healthWound, int actionWound, int mindWound, int strengthWound, int constitutionWound, int quicknessWound, int staminaWound, int focusWound, int willpowerWound) inline
Definition at line 210 of file TotalHealOtherCommand.h.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
Member Data Documentation
int TotalHealOtherCommand::actionHealed protected
Definition at line 65 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
int TotalHealOtherCommand::actionWoundHealed protected
Definition at line 72 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
int TotalHealOtherCommand::constitutionWoundHealed protected
Definition at line 70 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
String TotalHealOtherCommand::effectName protected
Definition at line 82 of file TotalHealOtherCommand.h.
int TotalHealOtherCommand::focusWoundHealed protected
Definition at line 77 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
int TotalHealOtherCommand::forceCost protected
Definition at line 61 of file TotalHealOtherCommand.h.
Referenced by doQueueCommand(), and TotalHealOtherCommand().
int TotalHealOtherCommand::heal protected
Definition at line 62 of file TotalHealOtherCommand.h.
Referenced by doQueueCommand(), and TotalHealOtherCommand().
int TotalHealOtherCommand::healthHealed protected
Definition at line 64 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
int TotalHealOtherCommand::healthWoundHealed protected
Definition at line 68 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
int TotalHealOtherCommand::mindHealed protected
Definition at line 66 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
int TotalHealOtherCommand::mindWoundHealed protected
Definition at line 76 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
int TotalHealOtherCommand::quicknessWoundHealed protected
Definition at line 73 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
float TotalHealOtherCommand::range protected
Definition at line 81 of file TotalHealOtherCommand.h.
float TotalHealOtherCommand::speed protected
Definition at line 80 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
int TotalHealOtherCommand::staminaWoundHealed protected
Definition at line 74 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
int TotalHealOtherCommand::strengthWoundHealed protected
Definition at line 69 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
int TotalHealOtherCommand::willpowerWoundHealed protected
Definition at line 78 of file TotalHealOtherCommand.h.
Referenced by TotalHealOtherCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/TotalHealOtherCommand.h