Core3: server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBox Class Reference
server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBox Class Reference
#include <SuiCharacterBuilderBox.h>
Public Member Functions
SuiCharacterBuilderBox (CreatureObject *player, CharacterBuilderMenuNode *root)
BaseMessage * generateMessage ()
CharacterBuilderMenuNode * getCurrentNode ()
void setCurrentNode (CharacterBuilderMenuNode *node)
bool isCharacterBuilderBox ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::player::sui::listbox::SuiListBox
SuiListBox (CreatureObject *player, unsigned int windowType=0, unsigned int listBoxType=0)
void init ()
void addMenuItem (const String &name, unsigned long long objectID=0)
String getMenuItemName (int index)
void removeAllMenuItems ()
unsigned long long getMenuObjectID (unsigned int idx)
int getMenuSize ()
BaseMessage * generateMessage ()
void setNextBox (unsigned int boxID)
void setPreviousBox (unsigned int boxID)
unsigned long long getNextBox ()
unsigned long long getPreviousBox ()
bool isListBox ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::player::sui::SuiBox
SuiBox (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
void initialize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateMessage ()
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
bool isInputBox ()
bool isListBox ()
bool isMessageBox ()
bool isTransferBox ()
bool isBankTransferBox ()
bool isSlicingBox ()
bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
SuiCharacterBuilderBox (DummyConstructorParameter *param)
virtual ~SuiCharacterBuilderBox ()
Protected Member Functions inherited from server::zone::objects::player::sui::listbox::SuiListBox
SuiListBox (DummyConstructorParameter *param)
virtual ~SuiListBox ()
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBox
SuiBox (DummyConstructorParameter *param)
virtual ~SuiBox ()
Friends
class SuiCharacterBuilderBoxHelper
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::player::sui::listbox::SuiListBox
static const int MSGSELECTED = 0
static const int HANDLESINGLEBUTTON = 1
static const int HANDLETWOBUTTON = 2
static const int HANDLETHREEBUTTON = 3
Detailed Description
Definition at line 53 of file SuiCharacterBuilderBox.h.
Constructor & Destructor Documentation
SuiCharacterBuilderBox::SuiCharacterBuilderBox (CreatureObject * player, CharacterBuilderMenuNode * root)
Definition at line 17 of file SuiCharacterBuilderBox.cpp.
References server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::_setStub().
SuiCharacterBuilderBox::SuiCharacterBuilderBox (DummyConstructorParameter * param) protected
Definition at line 24 of file SuiCharacterBuilderBox.cpp.
SuiCharacterBuilderBox::~SuiCharacterBuilderBox () protected virtual
Definition at line 28 of file SuiCharacterBuilderBox.cpp.
Member Function Documentation
DistributedObjectServant * SuiCharacterBuilderBox::_getImplementation ()
Definition at line 77 of file SuiCharacterBuilderBox.cpp.
Referenced by generateMessage(), getCurrentNode(), isCharacterBuilderBox(), and setCurrentNode().
DistributedObjectServant * SuiCharacterBuilderBox::_getImplementationForRead ()
Definition at line 83 of file SuiCharacterBuilderBox.cpp.
void SuiCharacterBuilderBox::_setImplementation (DistributedObjectServant * servant)
Definition at line 87 of file SuiCharacterBuilderBox.cpp.
BaseMessage * SuiCharacterBuilderBox::generateMessage ()
Definition at line 33 of file SuiCharacterBuilderBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), and RPC_GENERATEMESSAGE__.
CharacterBuilderMenuNode * SuiCharacterBuilderBox::getCurrentNode ()
Definition at line 46 of file SuiCharacterBuilderBox.cpp.
References _getImplementation(), and server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::getCurrentNode().
bool SuiCharacterBuilderBox::isCharacterBuilderBox ()
Definition at line 64 of file SuiCharacterBuilderBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::isCharacterBuilderBox(), and RPC_ISCHARACTERBUILDERBOX__.
void SuiCharacterBuilderBox::setCurrentNode (CharacterBuilderMenuNode * node)
Definition at line 55 of file SuiCharacterBuilderBox.cpp.
References _getImplementation(), and server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::setCurrentNode().
Friends And Related Function Documentation
friend class SuiCharacterBuilderBoxHelper friend
Definition at line 75 of file SuiCharacterBuilderBox.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/characterbuilderbox/SuiCharacterBuilderBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/characterbuilderbox/SuiCharacterBuilderBox.cpp