Core3: ContainerComponent Class Reference
ContainerComponent Class Reference
#include <ContainerComponent.h>
Public Member Functions
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
virtual int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
virtual bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
virtual int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Detailed Description
Definition at line 31 of file ContainerComponent.h.
Member Function Documentation
int ContainerComponent::canAddObject (SceneObject * sceneObject, SceneObject * object, int containmentType, String & errorDescription) virtual
Evaluates if this object has the necessary free slots to be able to add the specified SceneObject
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be checked
error error string that the player will receive on error
Returns
returns 0 on success, or error code
Reimplemented in LuaContainerComponent, FireworkShowContainerComponent, SaberInventoryContainerComponent, RecycleToolContainerComponent, MinefieldContainerComponent, PlayerContainerComponent, LootContainerComponent, and PlaceableLootContainerComponent.
Definition at line 50 of file ContainerComponent.cpp.
References TransferErrorCode::CANTADDTOITSELF, TransferErrorCode::CONTAINERFULL, server::zone::objects::scene::SceneObject::error(), server::zone::objects::scene::SceneObject::getContainerLock(), server::zone::objects::scene::SceneObject::getContainerObjects(), server::zone::objects::scene::SceneObject::getContainerVolumeLimit(), server::zone::objects::scene::SceneObject::getSlottedObjects(), TransferErrorCode::SLOTOCCUPIED, and TransferErrorCode::UNKNOWNCONTAIMENTTYPE.
Referenced by PlayerContainerComponent::canAddObject(), RecycleToolContainerComponent::canAddObject(), FireworkShowContainerComponent::canAddObject(), and LuaContainerComponent::canAddObject().
bool ContainerComponent::checkContainerPermission (SceneObject * sceneObject, CreatureObject * creature, uint16 permission) virtual
Reimplemented in GCWBaseContainerComponent, MinefieldContainerComponent, LootContainerComponent, StructureContainerComponent, ContainerObjectComponent, VendorContainerComponent, and PlaceableLootContainerComponent.
Definition at line 93 of file ContainerComponent.cpp.
References server::zone::objects::scene::variables::ContainerPermissions::getAllowPermissions(), server::zone::objects::scene::SceneObject::getContainerPermissions(), server::zone::objects::scene::variables::ContainerPermissions::getDenyPermissions(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::variables::ContainerPermissions::getOwnerID(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::player::PlayerObject::getPermissionGroups(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::variables::ContainerPermissions::hasInheritPermissionsFromParent(), server::zone::objects::scene::variables::ContainerPermissions::hasOwnerPermission(), and server::zone::objects::scene::SceneObject::isStaticObject().
Referenced by StructureContainerComponent::checkContainerPermission(), ContainerObjectComponent::checkContainerPermission(), and MinefieldContainerComponent::checkContainerPermission().
int ContainerComponent::notifyObjectInserted (SceneObject * sceneObject, SceneObject * object) virtual
Is called when this object has been inserted with an object
Parameters
object object that has been inserted
Reimplemented in LuaContainerComponent, FireworkShowContainerComponent, SaberInventoryContainerComponent, MinefieldContainerComponent, PlayerContainerComponent, and RecycleToolContainerComponent.
Definition at line 326 of file ContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::notifyObjectInserted().
Referenced by RecycleToolContainerComponent::notifyObjectInserted(), PlayerContainerComponent::notifyObjectInserted(), MinefieldContainerComponent::notifyObjectInserted(), LuaContainerComponent::notifyObjectInserted(), and transferObject().
int ContainerComponent::notifyObjectRemoved (SceneObject * sceneObject, SceneObject * object, SceneObject * destination) virtual
Is called when an object was removed
Parameters
object object that has been inserted
Reimplemented in LuaContainerComponent, FireworkShowContainerComponent, SaberInventoryContainerComponent, MinefieldContainerComponent, PlayerContainerComponent, and LootContainerComponent.
Definition at line 334 of file ContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::notifyObjectRemoved().
Referenced by PlayerContainerComponent::notifyObjectRemoved(), MinefieldContainerComponent::notifyObjectRemoved(), LuaContainerComponent::notifyObjectRemoved(), and removeObject().
bool ContainerComponent::removeObject (SceneObject * sceneObject, SceneObject * object, SceneObject * destination, bool notifyClient) virtual
Tries to remove/unlink object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be removed from the current object
notifyClient not used currently
Returns
returns true if the object has been successfully removed
Reimplemented in LuaContainerComponent, ZoneContainerComponent, and RecycleToolContainerComponent.
Definition at line 224 of file ContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), server::zone::objects::scene::SceneObject::error(), server::zone::objects::scene::SceneObject::getArrangementDescriptor(), server::zone::objects::scene::SceneObject::getContainerLock(), server::zone::objects::scene::SceneObject::getContainerObjects(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getRootParent(), server::zone::objects::scene::SceneObject::getSlottedObjects(), server::zone::objects::scene::SceneObject::link(), notifyObjectRemoved(), server::zone::objects::scene::SceneObject::notifyObjectRemovedFromChild(), and server::zone::objects::scene::SceneObject::updateToDatabase().
Referenced by RecycleToolContainerComponent::removeObject(), and LuaContainerComponent::removeObject().
bool ContainerComponent::transferObject (SceneObject * sceneObject, SceneObject * object, int containmentType, bool notifyClient = false, bool allowOverflow = false) virtual
Tries to add/link object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be added to the current object
containmentType arrangement type that will be used to add the object
notifyClient if true in range objects will be updated with the change
allowOverflow if true will bypass the containerVolumeLimit check
Returns
returns true if the object has been successfully added
Reimplemented in RecycleToolContainerComponent, LuaContainerComponent, FireworkShowContainerComponent, and ZoneContainerComponent.
Definition at line 132 of file ContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), server::zone::objects::scene::SceneObject::broadcastObject(), server::zone::objects::scene::SceneObject::error(), server::zone::objects::scene::SceneObject::getArrangementDescriptor(), server::zone::objects::scene::SceneObject::getContainerLock(), server::zone::objects::scene::SceneObject::getContainerObjects(), server::zone::objects::scene::SceneObject::getContainerVolumeLimit(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getSlottedObjects(), server::zone::objects::scene::SceneObject::link(), notifyObjectInserted(), and server::zone::objects::scene::SceneObject::updateToDatabase().
Referenced by FireworkShowContainerComponent::transferObject(), LuaContainerComponent::transferObject(), and RecycleToolContainerComponent::transferObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/components/ContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/components/ContainerComponent.cpp