Core3: ResourceAttribute Class Reference
ResourceAttribute Class Reference
#include <ResourceAttribute.h>
Public Member Functions
ResourceAttribute (const String &n, const int min, const int max)
~ResourceAttribute ()
void setIndex (String name)
String getName ()
int getMinimum ()
int getMaximum ()
int getIndex ()
Private Attributes
String name
int minimum
int maximum
int index
Detailed Description
The resource attribute class stores the name of a resource attribute and the min / max value
Definition at line 60 of file ResourceAttribute.h.
Constructor & Destructor Documentation
ResourceAttribute::ResourceAttribute (const String & n, const int min, const int max) inline
Constructor
Parameters
n Name of the Attribute
min Minimum Value
max Maximum Value
Definition at line 74 of file ResourceAttribute.h.
References index, maximum, minimum, name, and setIndex().
ResourceAttribute::~ResourceAttribute () inline
Destructor
Definition at line 86 of file ResourceAttribute.h.
Member Function Documentation
int ResourceAttribute::getIndex () inline
Definition at line 135 of file ResourceAttribute.h.
References index.
Referenced by ResourceSpawner::createResourceSpawn().
int ResourceAttribute::getMaximum () inline
Returns the maximum value of the Attribute
Definition at line 131 of file ResourceAttribute.h.
References maximum.
Referenced by ResourceSpawner::createResourceSpawn().
int ResourceAttribute::getMinimum () inline
Returns the minimum value of the Attribute
Definition at line 124 of file ResourceAttribute.h.
References minimum.
Referenced by ResourceSpawner::createResourceSpawn().
String ResourceAttribute::getName () inline
Returns the name of the Attribute
Definition at line 117 of file ResourceAttribute.h.
References name.
Referenced by ResourceTreeEntry::addAttribute(), ResourceSpawner::createRecycledResourceSpawn(), and ResourceSpawner::createResourceSpawn().
void ResourceAttribute::setIndex (String name) inline
Definition at line 90 of file ResourceAttribute.h.
References index.
Referenced by ResourceAttribute().
Member Data Documentation
int ResourceAttribute::index private
Definition at line 65 of file ResourceAttribute.h.
Referenced by getIndex(), ResourceAttribute(), and setIndex().
int ResourceAttribute::maximum private
Definition at line 64 of file ResourceAttribute.h.
Referenced by getMaximum(), and ResourceAttribute().
int ResourceAttribute::minimum private
Definition at line 63 of file ResourceAttribute.h.
Referenced by getMinimum(), and ResourceAttribute().
String ResourceAttribute::name private
Definition at line 62 of file ResourceAttribute.h.
Referenced by getName(), and ResourceAttribute().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcetree/ResourceAttribute.h