Core3: SceneObjectCreateMessage Class Reference
SceneObjectCreateMessage Class Reference
#include <SceneObjectCreateMessage.h>
Public Member Functions
SceneObjectCreateMessage (SceneObject *scno)
SceneObjectCreateMessage (uint64 oid, uint32 objCrc)
Static Public Member Functions
static void parseMessage (Message *pack, SceneObject *scno)
Detailed Description
Definition at line 52 of file SceneObjectCreateMessage.h.
Constructor & Destructor Documentation
SceneObjectCreateMessage::SceneObjectCreateMessage (SceneObject * scno) inline
Definition at line 54 of file SceneObjectCreateMessage.h.
References server::zone::objects::scene::SceneObject::getClientObjectCRC(), server::zone::objects::scene::SceneObject::getDirectionW(), server::zone::objects::scene::SceneObject::getDirectionX(), server::zone::objects::scene::SceneObject::getDirectionY(), server::zone::objects::scene::SceneObject::getDirectionZ(), and server::zone::objects::scene::SceneObject::getObjectID().
SceneObjectCreateMessage::SceneObjectCreateMessage (uint64 oid, uint32 objCrc) inline
Definition at line 72 of file SceneObjectCreateMessage.h.
Member Function Documentation
static void SceneObjectCreateMessage::parseMessage (Message * pack, SceneObject * scno) inline static
Definition at line 89 of file SceneObjectCreateMessage.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/scene/SceneObjectCreateMessage.h