Core3: server::zone::objects::creature::buffs::SingleUseBuffObserverImplementation Class Reference
server::zone::objects::creature::buffs::SingleUseBuffObserverImplementation Class Reference
#include <SingleUseBuffObserver.h>
Public Member Functions
SingleUseBuffObserverImplementation (SingleUseBuff *b)
SingleUseBuffObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const SingleUseBuffObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< SingleUseBuffObserver * > _this
Protected Member Functions
virtual ~SingleUseBuffObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< SingleUseBuff * > buff
Friends
class SingleUseBuffObserver
Detailed Description
Definition at line 99 of file SingleUseBuffObserver.h.
Constructor & Destructor Documentation
SingleUseBuffObserverImplementation::SingleUseBuffObserverImplementation (SingleUseBuff * b)
Definition at line 194 of file SingleUseBuffObserver.cpp.
References _initializeImplementation(), and buff.
SingleUseBuffObserverImplementation::SingleUseBuffObserverImplementation (DummyConstructorParameter * param)
Definition at line 68 of file SingleUseBuffObserver.cpp.
References _initializeImplementation().
SingleUseBuffObserverImplementation::~SingleUseBuffObserverImplementation () protected virtual
Definition at line 73 of file SingleUseBuffObserver.cpp.
Member Function Documentation
DistributedObjectStub * SingleUseBuffObserverImplementation::_getStub ()
Definition at line 93 of file SingleUseBuffObserver.cpp.
References _this.
void SingleUseBuffObserverImplementation::_initializeImplementation () protected
Definition at line 80 of file SingleUseBuffObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SingleUseBuffObserverImplementation().
void SingleUseBuffObserverImplementation::_serializationHelperMethod () protected
Definition at line 129 of file SingleUseBuffObserver.cpp.
Referenced by _initializeImplementation().
void SingleUseBuffObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 88 of file SingleUseBuffObserver.cpp.
References _this.
Referenced by server::zone::objects::creature::buffs::SingleUseBuffObserver::SingleUseBuffObserver().
void SingleUseBuffObserverImplementation::finalize () protected
Definition at line 77 of file SingleUseBuffObserver.cpp.
void SingleUseBuffObserverImplementation::lock (bool doLock = true) protected
Definition at line 101 of file SingleUseBuffObserver.cpp.
References _this.
void SingleUseBuffObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 105 of file SingleUseBuffObserver.cpp.
References _this.
int SingleUseBuffObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 17 of file SingleUseBuffObserverImplementation.cpp.
References buff, and server::zone::objects::creature::commands::QueueCommand::handleBuff().
Referenced by server::zone::objects::creature::buffs::SingleUseBuffObserver::notifyObserverEvent().
SingleUseBuffObserverImplementation::operator const SingleUseBuffObserver * ()
Definition at line 97 of file SingleUseBuffObserver.cpp.
void SingleUseBuffObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 136 of file SingleUseBuffObserver.cpp.
References readObjectMember().
bool SingleUseBuffObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 155 of file SingleUseBuffObserver.cpp.
References buff.
Referenced by readObject().
void SingleUseBuffObserverImplementation::rlock (bool doLock = true) protected
Definition at line 109 of file SingleUseBuffObserver.cpp.
References _this.
void SingleUseBuffObserverImplementation::runlock (bool doLock = true) protected
Definition at line 125 of file SingleUseBuffObserver.cpp.
References _this.
void SingleUseBuffObserverImplementation::unlock (bool doLock = true) protected
Definition at line 121 of file SingleUseBuffObserver.cpp.
References _this.
void SingleUseBuffObserverImplementation::wlock (bool doLock = true) protected
Definition at line 113 of file SingleUseBuffObserver.cpp.
References _this.
void SingleUseBuffObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 117 of file SingleUseBuffObserver.cpp.
References _this.
void SingleUseBuffObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 169 of file SingleUseBuffObserver.cpp.
References writeObjectMembers().
int SingleUseBuffObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 176 of file SingleUseBuffObserver.cpp.
References buff.
Referenced by writeObject().
Friends And Related Function Documentation
friend class SingleUseBuffObserver friend
Definition at line 144 of file SingleUseBuffObserver.h.
Member Data Documentation
WeakReference<SingleUseBuffObserver*> server::zone::objects::creature::buffs::SingleUseBuffObserverImplementation::_this
Definition at line 110 of file SingleUseBuffObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<SingleUseBuff* > server::zone::objects::creature::buffs::SingleUseBuffObserverImplementation::buff protected
Definition at line 101 of file SingleUseBuffObserver.h.
Referenced by notifyObserverEvent(), readObjectMember(), SingleUseBuffObserverImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SingleUseBuffObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SingleUseBuffObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SingleUseBuffObserverImplementation.cpp