Core3: server::zone::objects::building::tutorial::TutorialBuildingObject Class Reference
server::zone::objects::building::tutorial::TutorialBuildingObject Class Reference
#include <TutorialBuildingObject.h>
Public Member Functions
TutorialBuildingObject ()
void notifyRemoveFromZone ()
void initializeTransientMembers ()
void onEnter (CreatureObject *player)
void onExit (CreatureObject *player)
void clearUnloadEvent ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::building::BuildingObject
BuildingObject ()
void createCellObjects ()
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void createContainerComponent ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void updateSignName (bool notifyClient)
void sendContainerObjectsTo (SceneObject *player)
void updateCellPermissionsTo (CreatureObject *creature)
void broadcastCellPermissions ()
void broadcastCellPermissions (unsigned long long objectid)
bool isAllowedEntry (CreatureObject *player)
bool isCityBanned (CreatureObject *player)
int notifyStructurePlaced (CreatureObject *player)
bool hasTemplateEjectionPoint ()
Vector3 getTemplateEjectionPoint ()
Vector3 getEjectionPoint ()
void ejectObject (CreatureObject *creature)
void notifyRemoveFromZone ()
void notifyLoadFromDatabase ()
void notifyInsert (QuadTreeEntry *obj)
void notifyInsertToZone (Zone *zone)
void notifyDissapear (QuadTreeEntry *obj)
void notifyObjectInsertedToZone (SceneObject *object)
void insert (QuadTreeEntry *obj)
void remove (QuadTreeEntry *obj)
void update (QuadTreeEntry *obj)
void inRange (QuadTreeEntry *obj, float range)
void sendTo (SceneObject *player, bool doClose)
void sendBaselinesTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void addCell (CellObject *cell, unsigned int cellNumber)
bool isStaticBuilding ()
CellObject * getCell (unsigned int idx)
int getTotalCellNumber ()
bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
int getCurrentNumberOfPlayerItems ()
void destroyAllPlayerItems ()
void onEnter (CreatureObject *player)
void onExit (CreatureObject *player, unsigned long long parentid)
bool isBuildingObject ()
void setSignObject (SignObject *sign)
SignObject * getSignObject ()
bool isPublicStructure ()
bool isPrivateStructure ()
void setPublicStructure (bool privacy)
bool isCondemned ()
int getMapCellSize ()
bool togglePrivacy ()
unsigned int getMaximumNumberOfPlayerItems ()
String getRedeedMessage ()
bool hasAccessFee ()
int getAccessFee ()
bool canChangeAccessFee ()
void setAccessFee (int fee, int duration)
void removeAccessFee ()
int getAccessFeeDelay ()
void payAccessFee (CreatureObject *player)
void updatePaidAccessList ()
void createChildObjects ()
void spawnChildSceneObject (String &templatePath, float x, float z, float y, unsigned long long cellID, float dw, float dx, float dy, float dz)
void spawnChildCreaturesFromTemplate ()
void spawnChildCreature (String &mobile, int respawnTimer, float x, float z, float y, float heading, unsigned long long cellID)
bool hasTemplateChildCreatures ()
void destroyChildObjects ()
bool isResidence ()
void setResidence (bool isResidence)
int getFactionBaseType ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::structure::StructureObject
StructureObject ()
void initializeTransientMembers ()
void loadTemplateData (SharedObjectTemplate *templateData)
void notifyInsertToZone (Zone *zone)
void createChildObjects ()
int notifyStructurePlaced (CreatureObject *creature)
bool checkRequisitesForPlacement (CreatureObject *player)
String getTimeString (unsigned int timestamp)
void scheduleMaintenanceExpirationEvent ()
void scheduleMaintenanceTask (int timeFromNow)
void updateStructureStatus ()
bool isOnAdminList (CreatureObject *player)
bool isOnAdminList (const String &firstName, bool caseSensitive=false)
bool isOnEntryList (CreatureObject *player)
bool isOnBanList (CreatureObject *player)
bool isOnBanList (const String &firstName, bool caseSensitive=false)
bool isOnHopperList (CreatureObject *player)
bool isOnPermissionList (const String &listName, CreatureObject *player)
bool isOnPermissionList (const String &listName, const String &firstName, bool caseSensitive=false)
bool isOwnerOf (SceneObject *obj)
bool isOwnerOf (unsigned long long oid)
bool isOnAccessList (SceneObject *obj)
bool isOnAccessList (unsigned long long oid)
void sendPermissionListTo (CreatureObject *creature, const String &listName)
bool hasPermissionList (const String &listName)
bool isPermissionListFull (const String &listName)
int togglePermission (const String &listName, const String &targetName, bool caseSensitive=false)
int grantPermission (const String &listName, const String &targetName, bool caseSensitive=false)
int revokePermission (const String &listName, const String &targetName, bool caseSensitive=false)
int revokeAllPermissions (const String &targetName, bool caseSensitive=false)
void setOwnerName (const String &ownerName)
int getRedeedCost ()
CreatureObject * getOwnerCreatureObject ()
unsigned long long getOwnerObjectID ()
unsigned long long getDeedObjectID ()
int getLotSize ()
void setMaintenanceReduced (bool value)
float getMaintenanceRate ()
String getMaintenanceMods ()
int getBaseMaintenanceRate ()
int getBasePowerRate ()
int getSurplusMaintenance ()
int getSurplusPower ()
bool isPublicStructure ()
bool isPrivateStructure ()
void setOwnerObjectID (unsigned long long objectID)
void setDeedObjectID (unsigned long long deedID)
void setBaseMaintenanceRate (int rate)
void setBasePowerRate (int rate)
void setSurplusMaintenance (int surplus)
void addMaintenance (float add)
void payMaintenance (int maintenance, CreatureObject *payer, bool cashFirst)
void setSurplusPower (int surplus)
void addPower (float add)
bool isDecaying ()
bool isDecayed ()
int getDecayPercentage ()
bool isCondemned ()
void setPublicStructure (bool privacy)
bool isStructureObject ()
bool isCampStructure ()
bool isRedeedable ()
AABBTree * getAABBTree ()
void addTemplateSkillMods (TangibleObject *targetObject)
void removeTemplateSkillMods (TangibleObject *tangibleObject)
String getRedeedMessage ()
bool isCivicStructure ()
bool isCityHall ()
bool isCommercialStructure ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::tangible::TangibleObject
TangibleObject ()
void initializeMembers ()
void addTemplateSkillMods (TangibleObject *targetObject)
void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
void removeSkillModsFrom (CreatureObject *creature)
void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
void removeAllSkillModsOfType (const int skillType, bool notifyClient=true)
void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void sendBaselinesTo (SceneObject *player)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
void removeDefenders ()
void setCombatState ()
void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void clearCombatState (bool clearDefenders=true)
bool hasDefender (SceneObject *defender)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
bool isHealableBy (CreatureObject *object)
void sendPvpStatusTo (CreatureObject *player)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
void updateCraftingValues (CraftingValues *values, bool firstUpdate)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
bool isKiller ()
bool isTicketCollector ()
bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
int getUseCount ()
int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
int getJunkDealerNeeded ()
void setJunkValue (int jValue)
int getJunkValue ()
void setSerialNumber (const String &serial)
void setLevel (int lev)
String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
String repairAttempt (int repairChance)
bool isBroken ()
float getHitChance ()
void broadcastPvpStatusBitmask ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject ()
void initializePrivateData ()
void loadTemplateData (SharedObjectTemplate *templateData)
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendAttributeListTo (CreatureObject *object)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
void openContainerTo (CreatureObject *player)
byte checkContainerPermission (CreatureObject *player, unsigned short permission)
void closeContainerTo (CreatureObject *player, bool notify=true)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets=true)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
String getDetailedDescription ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
TutorialBuildingObject (DummyConstructorParameter *param)
virtual ~TutorialBuildingObject ()
Protected Member Functions inherited from server::zone::objects::building::BuildingObject
BuildingObject (DummyConstructorParameter *param)
virtual ~BuildingObject ()
Protected Member Functions inherited from server::zone::objects::structure::StructureObject
StructureObject (DummyConstructorParameter *param)
virtual ~StructureObject ()
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObject
TangibleObject (DummyConstructorParameter *param)
virtual ~TangibleObject ()
Protected Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject (DummyConstructorParameter *param)
virtual ~SceneObject ()
Friends
class TutorialBuildingObjectHelper
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::building::BuildingObject
static const int MAXPLAYERITEMS = 400
Detailed Description
Definition at line 112 of file TutorialBuildingObject.h.
Constructor & Destructor Documentation
TutorialBuildingObject::TutorialBuildingObject ()
Definition at line 25 of file TutorialBuildingObject.cpp.
References server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation::_setStub().
TutorialBuildingObject::TutorialBuildingObject (DummyConstructorParameter * param) protected
Definition at line 32 of file TutorialBuildingObject.cpp.
TutorialBuildingObject::~TutorialBuildingObject () protected virtual
Definition at line 36 of file TutorialBuildingObject.cpp.
Member Function Documentation
DistributedObjectServant * TutorialBuildingObject::_getImplementation ()
Definition at line 108 of file TutorialBuildingObject.cpp.
Referenced by clearUnloadEvent(), initializeTransientMembers(), notifyRemoveFromZone(), onEnter(), and onExit().
DistributedObjectServant * TutorialBuildingObject::_getImplementationForRead ()
Definition at line 114 of file TutorialBuildingObject.cpp.
void TutorialBuildingObject::_setImplementation (DistributedObjectServant * servant)
Definition at line 118 of file TutorialBuildingObject.cpp.
void TutorialBuildingObject::clearUnloadEvent ()
Definition at line 95 of file TutorialBuildingObject.cpp.
References _getImplementation(), server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation::clearUnloadEvent(), and RPC_CLEARUNLOADEVENT__.
void TutorialBuildingObject::initializeTransientMembers ()
Definition at line 54 of file TutorialBuildingObject.cpp.
References _getImplementation(), server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
void TutorialBuildingObject::notifyRemoveFromZone ()
Definition at line 41 of file TutorialBuildingObject.cpp.
References _getImplementation(), server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation::notifyRemoveFromZone(), and RPC_NOTIFYREMOVEFROMZONE__.
void TutorialBuildingObject::onEnter (CreatureObject * player)
Definition at line 67 of file TutorialBuildingObject.cpp.
References _getImplementation(), server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation::onEnter(), and RPC_ONENTER__CREATUREOBJECT_.
void TutorialBuildingObject::onExit (CreatureObject * player)
Definition at line 81 of file TutorialBuildingObject.cpp.
References _getImplementation(), server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation::onExit(), and RPC_ONEXIT__CREATUREOBJECT_.
Friends And Related Function Documentation
friend class TutorialBuildingObjectHelper friend
Definition at line 136 of file TutorialBuildingObject.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/building/tutorial/TutorialBuildingObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/building/tutorial/TutorialBuildingObject.cpp