Core3: server::zone::objects::player::sessions::ImageDesignPositionObserver Class Reference
server::zone::objects::player::sessions::ImageDesignPositionObserver Class Reference
#include <ImageDesignPositionObserver.h>
Public Member Functions
ImageDesignPositionObserver (ImageDesignSession *designSession)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ImageDesignPositionObserver (DummyConstructorParameter *param)
virtual ~ImageDesignPositionObserver ()
Friends
class ImageDesignPositionObserverHelper
Detailed Description
Definition at line 44 of file ImageDesignPositionObserver.h.
Constructor & Destructor Documentation
ImageDesignPositionObserver::ImageDesignPositionObserver (ImageDesignSession * designSession)
Definition at line 15 of file ImageDesignPositionObserver.cpp.
References server::zone::objects::player::sessions::ImageDesignPositionObserverImplementation::_setStub().
ImageDesignPositionObserver::ImageDesignPositionObserver (DummyConstructorParameter * param) protected
Definition at line 22 of file ImageDesignPositionObserver.cpp.
ImageDesignPositionObserver::~ImageDesignPositionObserver () protected virtual
Definition at line 26 of file ImageDesignPositionObserver.cpp.
Member Function Documentation
DistributedObjectServant * ImageDesignPositionObserver::_getImplementation ()
Definition at line 48 of file ImageDesignPositionObserver.cpp.
Referenced by notifyObserverEvent().
DistributedObjectServant * ImageDesignPositionObserver::_getImplementationForRead ()
Definition at line 54 of file ImageDesignPositionObserver.cpp.
void ImageDesignPositionObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 58 of file ImageDesignPositionObserver.cpp.
int ImageDesignPositionObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 31 of file ImageDesignPositionObserver.cpp.
References _getImplementation(), server::zone::objects::player::sessions::ImageDesignPositionObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class ImageDesignPositionObserverHelper friend
Definition at line 60 of file ImageDesignPositionObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignPositionObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignPositionObserver.cpp