Core3: server::zone::objects::player::PlayerObject Class Reference
server::zone::objects::player::PlayerObject Class Reference
#include <PlayerObject.h>
Public Member Functions
PlayerObject ()
void notifyLoadFromDatabase ()
void unload ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void sendBaselinesTo (SceneObject *player)
void sendMessage (BasePacket *msg)
void addOwnedStructure (StructureObject *obj)
void removeOwnedStructure (StructureObject *obj)
int getTotalOwnedStructureCount ()
bool isOwnedStructure (StructureObject *obj)
unsigned long long getOwnedStructure (int i)
int getLotsRemaining ()
bool hasLotsRemaining (int lots)
void notifySceneReady ()
int addExperience (const String &xpType, int xp, bool notifyClient=true)
void removeExperience (const String &xpType, bool notifyClient=true)
bool hasCappedExperience (const String &xpType)
void addWaypoint (WaypointObject *waypoint, bool checkName, bool notifyClient=true)
void setWaypoint (WaypointObject *waypoint, bool notifyClient=true)
WaypointObject * addWaypoint (const String &planet, float positionX, float positionY, bool notifyClient=true)
void removeWaypoint (unsigned long long waypointID, bool notifyClient=true)
void addAbilities (Vector< Ability * > &abilities, bool notifyClient=true)
void addAbility (Ability *ability, bool notifyClient=true)
void removeAbilities (Vector< Ability * > &abilities, bool notifyClient=true)
void removeAbility (Ability *ability, bool notifyClient=true)
bool addSchematics (Vector< ManagedReference< DraftSchematic * > > &schematics, bool notifyClient=true)
void removeSchematics (Vector< ManagedReference< DraftSchematic * > > &schematics, bool notifyClient=true)
bool addRewardedSchematic (DraftSchematic *schematic, short type, int quantity=1, bool notifyClient=true)
void removeRewardedSchematic (DraftSchematic *schematic, bool notifyClient=true)
void decreaseSchematicUseCount (DraftSchematic *schematic)
void setLanguageID (byte language, bool notifyClient=true)
void addFriend (const String &name, bool notifyClient=true)
void removeFriend (const String &name, bool notifyClient=true)
void addIgnore (const String &name, bool notifyClient=true)
void removeIgnore (const String &name, bool notifyClient=true)
void setTitle (const String &characterTitle, bool notifyClient=true)
void setFoodFilling (int newValue, bool notifyClient=true)
void setDrinkFilling (int newValue, bool notifyClient=true)
void increaseFactionStanding (const String &factionName, float amount)
void decreaseFactionStanding (const String &factionName, float amount)
float getFactionStanding (const String &factionName)
WaypointObject * getSurveyWaypoint ()
void setScreenPlayData (const String &screenPlay, const String &variable, const String &data)
String getScreenPlayData (const String &screenPlay, const String &variable)
void clearScreenPlayData (const String &screenPlay)
void activateRecovery ()
void doRecovery ()
void disconnect (bool closeClient, bool doLock)
void reload (ZoneClientSession *client)
void setOffline ()
void setLinkDead ()
void setOnline ()
void setLoggingOut ()
void sendBadgesResponseTo (CreatureObject *player)
void logout (bool doLock)
void setJediState (int state, bool notifyClient=true)
FactionStandingList * getFactionStandingList ()
void setLastNpcConvStr (const String &conv)
void setLastNpcConvMessStr (const String &mess)
String getLastNpcConvStr ()
String getLastNpcConvMessStr ()
String getLastNpcConvOption (int idx)
void addLastNpcConvOptions (const String &option)
int countLastNpcConvOptions ()
void clearLastNpcConvOptions ()
void setConversatingCreature (CreatureObject *creature)
unsigned long long getConversatingCreature ()
void setTrainerCoordinates (const Vector3 &trainer)
Vector3 getTrainerCoordinates ()
void setTrainerZoneName (String &zoneName)
String getTrainerZoneName ()
SortedVector< unsigned long
long > * getPersistentMessages ()
void addPersistentMessage (unsigned long long id)
void dropPersistentMessage (unsigned long long id)
void unloadSpawnedChildren ()
void addToConsentList (const String &name)
bool hasInConsentList (const String &name)
void removeFromConsentList (const String &name)
String getConsentName (int i)
int getConsentListSize ()
String getFactionRank ()
void setFactionRank (const String &rank)
void setCommandMessageString (unsigned int actionCRC, String &message)
void removeCommandMessageString (unsigned int actionCRC)
unsigned long long getDeclaredResidence ()
void setDeclaredResidence (BuildingObject *residence)
void setCloningFacility (BuildingObject *cloningfac)
unsigned long long getCloningFacility ()
void notifyOnline ()
void doDigest (int fillingReduction)
bool isDigesting ()
String getSavedTerrainName ()
void setSavedParentID (unsigned long long id)
void setSavedTerrainName (const String &name)
void setForcePower (int fp, bool notifyClient=true)
void setForcePowerMax (int newValue, bool notifyClient=true)
void activateForceRegen ()
void setForcePowerRegen (int val)
int getForcePowerRegen ()
unsigned long long getSavedParentID ()
unsigned int getNewSuiBoxID (unsigned int type)
bool hasSuiBox (unsigned int boxID)
SuiBox * getSuiBox (unsigned int boxID)
void removeSuiBox (unsigned int boxID, bool closeWindowToClient=false)
void removeSuiBoxType (unsigned int windowType)
bool hasSuiBoxWindowType (unsigned int windowType)
void closeSuiWindowType (unsigned int windowType)
SuiBox * getSuiBoxFromWindowType (unsigned int windowType)
void addSuiBox (SuiBox *sui)
void addPermissionGroup (const String &group, bool updateInRangeBuildingPermissions=false)
void removePermissionGroup (const String &group, bool updateInRangeBuildingPermissions=false)
bool hasPermissionGroup (const String &group)
SortedVector< String > * getPermissionGroups ()
bool isFirstIncapacitationExpired ()
void resetIncapacitationCounter ()
void resetFirstIncapacitationTime ()
void updateIncapacitationCounter ()
bool isFirstIncapacitation ()
byte getIncapacitationCounter ()
void addToDuelList (CreatureObject *targetPlayer)
void removeFromDuelList (CreatureObject *targetPlayer)
CreatureObject * getDuelListObject (int index)
bool requestedDuelTo (CreatureObject *targetPlayer)
bool isDuelListEmpty ()
int getDuelListSize ()
UnicodeString getBiography ()
void notifyOffline ()
void setBadge (unsigned int badge)
void awardBadge (unsigned int badge)
void setTeleporting (bool val)
int getNumBadges ()
int getBadgeTypeCount (byte type)
bool hasFriend (const String &name)
bool isIgnoring (const String &name)
void addReverseFriend (const String &name)
void removeReverseFriend (const String &name)
void sendFriendLists ()
bool hasWaypoint (unsigned long long objectID)
bool hasAbility (const String &ability)
bool hasCommandMessageString (unsigned int actionCRC)
unsigned int getCharacterBitmask ()
String getTitle ()
unsigned int getAdminLevel ()
void setAdminLevel (unsigned int adminlvl)
void setBiography (const UnicodeString &bio)
bool isDeveloper ()
bool isCSR ()
bool isPrivileged ()
void setCharacterBitmask (unsigned int bitmask)
bool setCharacterBit (unsigned int bit, bool notifyClient=false)
bool clearCharacterBit (unsigned int bit, bool notifyClient=false)
void toggleCharacterBit (unsigned int bit)
bool isAFK ()
VectorMap< String, int > * getXpTypeCapList ()
DeltaVectorMap< String, int > * getExperienceList ()
int getForcePower ()
int getForcePowerMax ()
WaypointList * getWaypointList ()
AbilityList * getAbilityList ()
SchematicList * getSchematics ()
DraftSchematic * getSchematic (int i)
Vector< ManagedReference
< DraftSchematic * > > filterSchematicList (CreatureObject *player, Vector< unsigned int > *enabledTabs, int complexityLevel)
int getFoodFilling ()
int getFoodFillingMax ()
int getDrinkFilling ()
int getDrinkFillingMax ()
int getJediState ()
byte getLanguageID ()
DeltaVector< String > * getFriendList ()
bool isTeleporting ()
void addChatRoom (ChatRoom *room)
void removeChatRoom (ChatRoom *room)
void setBankLocation (const String &location)
String getBankLocation ()
DeltaVector< String > * getIgnoreList ()
int getExperience (const String &xp)
void maximizeExperience ()
void activateMissions ()
String getCommandMessageString (unsigned int actionCRC)
bool hasBadge (unsigned int badge)
void clearDisconnectEvent ()
void clearRecoveryEvent ()
bool isOnline ()
bool isOffline ()
bool isLoading ()
bool isLinkDead ()
bool isLoggingIn ()
bool isLoggingOut ()
void setSkillPoints (int points)
void addSkillPoints (int points)
int getSkillPoints ()
ValidatedPosition * getLastValidatedPosition ()
void updateLastValidatedPosition ()
void setSpawnedBlueFrog ()
bool hasSpawnedBlueFrog ()
unsigned int getAccountID ()
unsigned long long getServerMovementTimeDelta ()
Time * getServerMovementTimeStamp ()
void setClientLastMovementStamp (unsigned int stamp)
void updateServerLastMovementStamp ()
void setAccountID (unsigned int id)
int getFactionStatus ()
void setFactionStatus (int status)
unsigned int getClientLastMovementStamp ()
void addHologrindProfession (byte prof)
Vector< byte > * getHologrindProfessions ()
byte getRaceID ()
void setRaceID (byte race)
void setMaximumLots (byte lots)
byte getMaximumLots ()
String getStarterProfession ()
void setStarterProfession (String &profession)
void addToBountyLockList (unsigned long long playerId)
bool isInBountyLockList (unsigned long long playerId)
void removeFromBountyLockList (unsigned long long playerId, bool immediately)
void removeFromBountyLockListDirectly (unsigned long long playerId)
bool isBountyLocked ()
unsigned long long getPerformanceBuffTarget ()
void setPerformanceBuffTarget (unsigned long long target)
void setDebug (bool value)
bool getDebug ()
float getVisibility ()
void setVisibility (float value)
Time getLastVisibilityUpdateTimestamp ()
void addVendor (SceneObject *vendor)
void removeVendor (SceneObject *vendor)
int getVendorCount ()
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
bool isJedi ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::intangible::IntangibleObject
IntangibleObject ()
void initializeTransientMembers ()
void loadTemplateData (SharedObjectTemplate *templateData)
bool isIntangibleObject ()
void sendBaselinesTo (SceneObject *player)
void updateStatus (int newStatus, bool notifyClient=true)
unsigned int getStatus ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject ()
void initializePrivateData ()
void loadTemplateData (SharedObjectTemplate *templateData)
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendAttributeListTo (CreatureObject *object)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
void openContainerTo (CreatureObject *player)
byte checkContainerPermission (CreatureObject *player, unsigned short permission)
void closeContainerTo (CreatureObject *player, bool notify=true)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets=true)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
String getDetailedDescription ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int LFG = 1
static const int NEWBIEHELPER = 2
static const int ROLEPLAYER = 4
static const int AFK = 0x80
static const int LD = 0x100
static const int FACTIONRANK = 0x200
static const int ANONYMOUS = 0x80000000
static const int NORMALPLAYER = 0
static const int CSR = 1
static const int DEV = 2
static const int ONLINE = 1
static const int OFFLINE = 2
static const int LINKDEAD = 3
static const int LOGGINGIN = 4
static const int LOGGINGOUT = 5
static const int LOADING = 6
Protected Member Functions
PlayerObject (DummyConstructorParameter *param)
virtual ~PlayerObject ()
Protected Member Functions inherited from server::zone::objects::intangible::IntangibleObject
IntangibleObject (DummyConstructorParameter *param)
virtual ~IntangibleObject ()
Protected Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject (DummyConstructorParameter *param)
virtual ~SceneObject ()
Friends
class PlayerObjectHelper
Detailed Description
Definition at line 275 of file PlayerObject.h.
Constructor & Destructor Documentation
PlayerObject::PlayerObject ()
Definition at line 43 of file PlayerObject.cpp.
References server::zone::objects::player::PlayerObjectImplementation::_setStub().
PlayerObject::PlayerObject (DummyConstructorParameter * param) protected
Definition at line 50 of file PlayerObject.cpp.
PlayerObject::~PlayerObject () protected virtual
Definition at line 54 of file PlayerObject.cpp.
Member Function Documentation
DistributedObjectServant * PlayerObject::_getImplementation ()
Definition at line 3079 of file PlayerObject.cpp.
Referenced by activateForceRegen(), activateMissions(), activateRecovery(), addAbilities(), addAbility(), addChatRoom(), addExperience(), addFriend(), addHologrindProfession(), addIgnore(), addLastNpcConvOptions(), addOwnedStructure(), addPermissionGroup(), addPersistentMessage(), addReverseFriend(), addRewardedSchematic(), addSchematics(), addSkillPoints(), addSuiBox(), addToBountyLockList(), addToConsentList(), addToDuelList(), addVendor(), addWaypoint(), awardBadge(), clearCharacterBit(), clearDisconnectEvent(), clearLastNpcConvOptions(), clearRecoveryEvent(), clearScreenPlayData(), closeSuiWindowType(), countLastNpcConvOptions(), decreaseFactionStanding(), decreaseSchematicUseCount(), destroyObjectFromDatabase(), disconnect(), doDigest(), doRecovery(), dropPersistentMessage(), filterSchematicList(), getAbilityList(), getAccountID(), getAdminLevel(), getBadgeTypeCount(), getBankLocation(), getBiography(), getCharacterBitmask(), getClientLastMovementStamp(), getCloningFacility(), getCommandMessageString(), getConsentListSize(), getConsentName(), getConversatingCreature(), getDebug(), getDeclaredResidence(), getDrinkFilling(), getDrinkFillingMax(), getDuelListObject(), getDuelListSize(), getExperience(), getExperienceList(), getFactionRank(), getFactionStanding(), getFactionStandingList(), getFactionStatus(), getFoodFilling(), getFoodFillingMax(), getForcePower(), getForcePowerMax(), getForcePowerRegen(), getFriendList(), getHologrindProfessions(), getIgnoreList(), getIncapacitationCounter(), getJediState(), getLanguageID(), getLastNpcConvMessStr(), getLastNpcConvOption(), getLastNpcConvStr(), getLastValidatedPosition(), getLastVisibilityUpdateTimestamp(), getLotsRemaining(), getMaximumLots(), getNewSuiBoxID(), getNumBadges(), getOwnedStructure(), getPerformanceBuffTarget(), getPermissionGroups(), getPersistentMessages(), getRaceID(), getSavedParentID(), getSavedTerrainName(), getSchematic(), getSchematics(), getScreenPlayData(), getServerMovementTimeDelta(), getServerMovementTimeStamp(), getSkillPoints(), getStarterProfession(), getSuiBox(), getSuiBoxFromWindowType(), getSurveyWaypoint(), getTitle(), getTotalOwnedStructureCount(), getTrainerCoordinates(), getTrainerZoneName(), getVendorCount(), getVisibility(), getWaypointList(), getXpTypeCapList(), hasAbility(), hasBadge(), hasCappedExperience(), hasCommandMessageString(), hasFriend(), hasInConsentList(), hasLotsRemaining(), hasPermissionGroup(), hasSpawnedBlueFrog(), hasSuiBox(), hasSuiBoxWindowType(), hasWaypoint(), increaseFactionStanding(), initializeTransientMembers(), isAFK(), isBountyLocked(), isCSR(), isDeveloper(), isDigesting(), isDuelListEmpty(), isFirstIncapacitation(), isFirstIncapacitationExpired(), isIgnoring(), isInBountyLockList(), isJedi(), isLinkDead(), isLoading(), isLoggingIn(), isLoggingOut(), isOffline(), isOnline(), isOwnedStructure(), isPrivileged(), isTeleporting(), loadTemplateData(), logout(), maximizeExperience(), notifyLoadFromDatabase(), notifyOffline(), notifyOnline(), notifySceneReady(), reload(), removeAbilities(), removeAbility(), removeChatRoom(), removeCommandMessageString(), removeExperience(), removeFriend(), removeFromBountyLockList(), removeFromBountyLockListDirectly(), removeFromConsentList(), removeFromDuelList(), removeIgnore(), removeOwnedStructure(), removePermissionGroup(), removeReverseFriend(), removeRewardedSchematic(), removeSchematics(), removeSuiBox(), removeSuiBoxType(), removeVendor(), removeWaypoint(), requestedDuelTo(), resetFirstIncapacitationTime(), resetIncapacitationCounter(), sendBadgesResponseTo(), sendBaselinesTo(), sendFriendLists(), sendMessage(), setAccountID(), setAdminLevel(), setBadge(), setBankLocation(), setBiography(), setCharacterBit(), setCharacterBitmask(), setClientLastMovementStamp(), setCloningFacility(), setCommandMessageString(), setConversatingCreature(), setDebug(), setDeclaredResidence(), setDrinkFilling(), setFactionRank(), setFactionStatus(), setFoodFilling(), setForcePower(), setForcePowerMax(), setForcePowerRegen(), setJediState(), setLanguageID(), setLastNpcConvMessStr(), setLastNpcConvStr(), setLinkDead(), setLoggingOut(), setMaximumLots(), setOffline(), setOnline(), setPerformanceBuffTarget(), setRaceID(), setSavedParentID(), setSavedTerrainName(), setScreenPlayData(), setSkillPoints(), setSpawnedBlueFrog(), setStarterProfession(), setTeleporting(), setTitle(), setTrainerCoordinates(), setTrainerZoneName(), setVisibility(), setWaypoint(), toggleCharacterBit(), unload(), unloadSpawnedChildren(), updateIncapacitationCounter(), updateLastValidatedPosition(), and updateServerLastMovementStamp().
DistributedObjectServant * PlayerObject::_getImplementationForRead ()
Definition at line 3085 of file PlayerObject.cpp.
void PlayerObject::_setImplementation (DistributedObjectServant * servant)
Definition at line 3089 of file PlayerObject.cpp.
void PlayerObject::activateForceRegen ()
Definition at line 1331 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::activateForceRegen(), and RPC_ACTIVATEFORCEREGEN__.
void PlayerObject::activateMissions ()
Definition at line 2393 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::activateMissions(), and RPC_ACTIVATEMISSIONS__.
void PlayerObject::activateRecovery ()
Definition at line 649 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::activateRecovery(), and RPC_ACTIVATERECOVERY__.
void PlayerObject::addAbilities (Vector< Ability * > & abilities, bool notifyClient = true)
Adds new abilities commands to player
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
abilities Vector of abilities to add
notifyClient determines whether to update the client with the changes
Definition at line 344 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::addAbilities().
Referenced by server::zone::managers::skill::SkillManager::addAbilities().
void PlayerObject::addAbility (Ability * ability, bool notifyClient = true)
Definition at line 353 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::addAbility().
Referenced by server::zone::managers::skill::SkillManager::addAbility().
void PlayerObject::addChatRoom (ChatRoom * room)
Definition at line 2300 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addChatRoom(), and RPC_ADDCHATROOM__CHATROOM_.
Referenced by server::chat::room::ChatRoomImplementation::addPlayer().
int PlayerObject::addExperience (const String & xpType, int xp, bool notifyClient = true)
Adds experience of a type to the player's experience pool.
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
xpType The string value for the type of experience to add.
xp The value of experience to add.
notifyClient Boolean to determing whether the client should receive a delta packet for the experience gain.
Returns
returns total experience awarded
Definition at line 244 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addExperience(), and RPC_ADDEXPERIENCE__STRING_INT_BOOL_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::awardExperience(), server::zone::managers::city::CityManagerImplementation::processCityUpdate(), server::zone::managers::city::CityManagerImplementation::updateCityVoting(), and server::zone::managers::skill::SkillManager::updateXpLimits().
void PlayerObject::addFriend (const String & name, bool notifyClient = true)
Adds a friend to the friend list
Precondition
{ this is locked}
Postcondition
{ this is locked }
Parameters
name friends name
notifyClient determines whether to update the client with the changes
Definition at line 440 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addFriend(), and RPC_ADDFRIEND__STRING_BOOL_.
void PlayerObject::addHologrindProfession (byte prof)
Definition at line 2745 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addHologrindProfession(), and RPC_ADDHOLOGRINDPROFESSION__BYTE_.
void PlayerObject::addIgnore (const String & name, bool notifyClient = true)
Adds a player to the ignore list
Precondition
{ this is locked}
Postcondition
{ this is locked }
Parameters
name player name
notifyClient determines whether to update the client with the changes
Definition at line 470 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addIgnore(), and RPC_ADDIGNORE__STRING_BOOL_.
void PlayerObject::addLastNpcConvOptions (const String & option)
Definition at line 882 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addLastNpcConvOptions(), and RPC_ADDLASTNPCCONVOPTIONS__STRING_.
void PlayerObject::addOwnedStructure (StructureObject * obj)
Definition at line 135 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addOwnedStructure(), and RPC_ADDOWNEDSTRUCTURE__STRUCTUREOBJECT_.
Referenced by server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership().
void PlayerObject::addPermissionGroup (const String & group, bool updateInRangeBuildingPermissions = false)
Definition at line 1511 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addPermissionGroup(), and RPC_ADDPERMISSIONGROUP__STRING_BOOL_.
void PlayerObject::addPersistentMessage (unsigned long long id)
Definition at line 1005 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addPersistentMessage(), and RPC_ADDPERSISTENTMESSAGE__LONG_.
Referenced by SendMailTask::run().
void PlayerObject::addReverseFriend (const String & name)
Definition at line 1849 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addReverseFriend(), and RPC_ADDREVERSEFRIEND__STRING_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addFriend().
bool PlayerObject::addRewardedSchematic (DraftSchematic * schematic, short type, int quantity = 1, bool notifyClient = true)
Definition at line 398 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::addRewardedSchematic().
bool PlayerObject::addSchematics (Vector< ManagedReference< DraftSchematic * > > & schematics, bool notifyClient = true)
Definition at line 380 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::addSchematics().
Referenced by SchematicList::addRewardedSchematics(), and SchematicMap::addSchematics().
void PlayerObject::addSkillPoints (int points)
Definition at line 2554 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addSkillPoints(), and RPC_ADDSKILLPOINTS__INT_.
void PlayerObject::addSuiBox (SuiBox * sui)
Definition at line 1497 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addSuiBox(), and RPC_ADDSUIBOX__SUIBOX_.
Referenced by DiagnoseCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), ServerInfoCommand::executeCommand(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation::initializeSession(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::initializeSession(), server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::initializeSession(), PlaceCityHallComponent::placeStructure(), server::zone::managers::city::CityManagerImplementation::promptAddMilitiaMember(), server::zone::managers::city::CityManagerImplementation::promptDepositCityTreasury(), server::zone::objects::building::BuildingObjectImplementation::promptPayAccessFee(), server::zone::managers::city::CityManagerImplementation::promptRegisterCity(), server::zone::managers::city::CityManagerImplementation::promptUnregisterCity(), server::zone::managers::player::PlayerManagerImplementation::sendActivateCloneRequest(), StartDanceCommand::sendAvailableDances(), StartMusicCommand::sendAvailableSongs(), server::zone::managers::city::CityManagerImplementation::sendChangeCityName(), server::zone::managers::city::CityManagerImplementation::sendCitizenshipReport(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::sendConfirmationBox(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport(), server::zone::managers::city::CityManagerImplementation::sendManageMilitia(), server::zone::managers::city::CityManagerImplementation::sendStructureReport(), and server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::sendTransferBox().
void PlayerObject::addToBountyLockList (unsigned long long playerId)
Definition at line 2851 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addToBountyLockList(), and RPC_ADDTOBOUNTYLOCKLIST__LONG_.
void PlayerObject::addToConsentList (const String & name)
Definition at line 1046 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addToConsentList(), and RPC_ADDTOCONSENTLIST__STRING_.
Referenced by ConsentCommand::consent().
void PlayerObject::addToDuelList (CreatureObject * targetPlayer)
Definition at line 1642 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addToDuelList(), and RPC_ADDTODUELLIST__CREATUREOBJECT_.
Referenced by CombatManager::requestDuel().
void PlayerObject::addVendor (SceneObject * vendor)
Definition at line 3011 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addVendor(), and RPC_ADDVENDOR__SCENEOBJECT_.
void PlayerObject::addWaypoint (WaypointObject * waypoint, bool checkName, bool notifyClient = true)
Adds waypoint object to waypointList
Precondition
{ this is locked }
Postcondition
{ this is locked, waypoint object is in the list }
Parameters
waypoint waypoint object to add
checkName determines whether to remove existing Waypoint with equal customName
notifyClient determines whether to update the client with the changes
Definition at line 289 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::addWaypoint(), and RPC_ADDWAYPOINT__WAYPOINTOBJECT_BOOL_BOOL_.
Referenced by server::zone::objects::player::sessions::FindSessionImplementation::addWaypoint(), and server::zone::objects::player::sessions::survey::SurveySessionImplementation::surveyCnodeMinigame().
WaypointObject * PlayerObject::addWaypoint (const String & planet, float positionX, float positionY, bool notifyClient = true)
Adds a new waypoint with the specified coordinates
Precondition
{ this is locked }
Postcondition
{ this is locked, waypoint object is in the list }
Parameters
planet planet where waypoint will be created
positionX waypoint position X
positionY waypoint position Y
notifyClient determines whether to update the client with the changes
Definition at line 320 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::addWaypoint().
void PlayerObject::awardBadge (unsigned int badge)
Definition at line 1766 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::awardBadge(), and RPC_AWARDBADGE__INT_.
bool PlayerObject::clearCharacterBit (unsigned int bit, bool notifyClient = false)
Definition at line 2064 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::clearCharacterBit(), and RPC_CLEARCHARACTERBIT__INT_BOOL_.
Referenced by GroupManager::createGroup(), and GroupManager::joinGroup().
void PlayerObject::clearDisconnectEvent ()
Definition at line 2436 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::clearDisconnectEvent(), and RPC_CLEARDISCONNECTEVENT__.
void PlayerObject::clearLastNpcConvOptions ()
Definition at line 909 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::clearLastNpcConvOptions(), and RPC_CLEARLASTNPCCONVOPTIONS__.
void PlayerObject::clearRecoveryEvent ()
Definition at line 2449 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::clearRecoveryEvent(), and RPC_CLEARRECOVERYEVENT__.
void PlayerObject::clearScreenPlayData (const String & screenPlay)
Definition at line 635 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::clearScreenPlayData(), and RPC_CLEARSCREENPLAYDATA__STRING_.
Referenced by server::zone::managers::director::DirectorManager::clearScreenPlayData().
void PlayerObject::closeSuiWindowType (unsigned int windowType)
Definition at line 1469 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::closeSuiWindowType(), and RPC_CLOSESUIWINDOWTYPE__INT_.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::canUseTurret(), TurretFireTask::checkTurretController(), TurretFireTask::closeControls(), DiagnoseCommand::doQueueCommand(), and server::zone::managers::gcw::GCWManagerImplementation::sendTurretAttackListTo().
int PlayerObject::countLastNpcConvOptions ()
Definition at line 896 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::countLastNpcConvOptions(), and RPC_COUNTLASTNPCCONVOPTIONS__.
void PlayerObject::decreaseFactionStanding (const String & factionName, float amount)
Definition at line 560 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::decreaseFactionStanding(), and RPC_DECREASEFACTIONSTANDING__STRING_FLOAT_.
Referenced by DelegateFactionPointsCommand::doDelegate().
void PlayerObject::decreaseSchematicUseCount (DraftSchematic * schematic)
Definition at line 416 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::decreaseSchematicUseCount().
void PlayerObject::destroyObjectFromDatabase (bool destroyContainedObjects = false)
Definition at line 3052 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::destroyObjectFromDatabase(), and RPC_DESTROYOBJECTFROMDATABASE__BOOL_.
void PlayerObject::disconnect (bool closeClient, bool doLock)
Definition at line 675 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::disconnect(), and RPC_DISCONNECT__BOOL_BOOL_.
Referenced by DisconnectClientEvent::run().
void PlayerObject::doDigest (int fillingReduction)
Definition at line 1231 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::doDigest(), and RPC_DODIGEST__INT_.
void PlayerObject::doRecovery ()
Definition at line 662 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::doRecovery(), and RPC_DORECOVERY__.
void PlayerObject::dropPersistentMessage (unsigned long long id)
Definition at line 1019 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::dropPersistentMessage(), and RPC_DROPPERSISTENTMESSAGE__LONG_.
Vector< ManagedReference< DraftSchematic * > > PlayerObject::filterSchematicList (CreatureObject * player, Vector< unsigned int > * enabledTabs, int complexityLevel)
Definition at line 2191 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::filterSchematicList().
AbilityList * PlayerObject::getAbilityList ()
Definition at line 2159 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getAbilityList().
Referenced by PlayerInfoCommand::executeCommand(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::initializeSession(), StartDanceCommand::sendAvailableDances(), and StartMusicCommand::sendAvailableSongs().
unsigned int PlayerObject::getAccountID ()
Definition at line 2629 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getAccountID(), and RPC_GETACCOUNTID__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::banAccount(), server::zone::managers::player::PlayerManagerImplementation::banCharacter(), and server::zone::managers::player::PlayerManagerImplementation::banFromGalaxy().
unsigned int PlayerObject::getAdminLevel ()
Definition at line 1955 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getAdminLevel(), and RPC_GETADMINLEVEL__.
Referenced by PlayerObjectMessage6::PlayerObjectMessage6().
int PlayerObject::getBadgeTypeCount (byte type)
Definition at line 1807 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getBadgeTypeCount(), and RPC_GETBADGETYPECOUNT__BYTE_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::awardBadge().
String PlayerObject::getBankLocation ()
Definition at line 2342 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getBankLocation(), and RPC_GETBANKLOCATION__.
UnicodeString PlayerObject::getBiography ()
Definition at line 1724 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getBiography(), and RPC_GETBIOGRAPHY__.
unsigned int PlayerObject::getCharacterBitmask ()
Definition at line 1927 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getCharacterBitmask(), and RPC_GETCHARACTERBITMASK__.
Referenced by PlayerObjectMessage3::PlayerObjectMessage3().
unsigned int PlayerObject::getClientLastMovementStamp ()
Definition at line 2732 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getClientLastMovementStamp(), and RPC_GETCLIENTLASTMOVEMENTSTAMP__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackSecondTest().
unsigned long long PlayerObject::getCloningFacility ()
Definition at line 1205 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getCloningFacility(), and RPC_GETCLONINGFACILITY__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::sendActivateCloneRequest(), and server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner().
String PlayerObject::getCommandMessageString (unsigned int actionCRC)
Definition at line 2406 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getCommandMessageString(), and RPC_GETCOMMANDMESSAGESTRING__INT_.
int PlayerObject::getConsentListSize ()
Definition at line 1104 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getConsentListSize(), and RPC_GETCONSENTLISTSIZE__.
String PlayerObject::getConsentName (int i)
Definition at line 1088 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getConsentName(), and RPC_GETCONSENTNAME__INT_.
unsigned long long PlayerObject::getConversatingCreature ()
Definition at line 936 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getConversatingCreature(), and RPC_GETCONVERSATINGCREATURE__.
bool PlayerObject::getDebug ()
Definition at line 2962 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getDebug(), and RPC_GETDEBUG__.
unsigned long long PlayerObject::getDeclaredResidence ()
Definition at line 1164 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getDeclaredResidence(), and RPC_GETDECLAREDRESIDENCE__.
Referenced by StructureManager::declareResidence(), PlaceCityHallComponent::placeStructure(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), and server::zone::objects::region::CityRegionImplementation::transferCivicStructuresToMayor().
int PlayerObject::getDrinkFilling ()
Definition at line 2226 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getDrinkFilling(), and RPC_GETDRINKFILLING__.
Referenced by server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), and PlayerObjectDeltaMessage9::updateStomachFilling().
int PlayerObject::getDrinkFillingMax ()
Definition at line 2239 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getDrinkFillingMax(), and RPC_GETDRINKFILLINGMAX__.
Referenced by server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), and PlayerObjectDeltaMessage9::updateStomachFilling().
CreatureObject * PlayerObject::getDuelListObject (int index)
Definition at line 1670 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getDuelListObject(), and RPC_GETDUELLISTOBJECT__INT_.
Referenced by CombatManager::freeDuelList().
int PlayerObject::getDuelListSize ()
Definition at line 1711 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getDuelListSize(), and RPC_GETDUELLISTSIZE__.
Referenced by CombatManager::freeDuelList().
int PlayerObject::getExperience (const String & xp)
Definition at line 2366 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getExperience(), and RPC_GETEXPERIENCE__STRING_.
DeltaVectorMap< String, int > * PlayerObject::getExperienceList ()
Definition at line 2115 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getExperienceList().
Referenced by server::zone::managers::skill::SkillManager::updateXpLimits().
String PlayerObject::getFactionRank ()
Definition at line 1117 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getFactionRank().
float PlayerObject::getFactionStanding (const String & factionName)
Definition at line 575 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getFactionStanding(), and RPC_GETFACTIONSTANDING__STRING_.
Referenced by DelegateFactionPointsCommand::doDelegate(), and DelegateFactionPointsCommand::doQueueCommand().
FactionStandingList * PlayerObject::getFactionStandingList ()
Gets the faction point list.
Definition at line 799 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getFactionStandingList().
int PlayerObject::getFactionStatus ()
Definition at line 2705 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getFactionStatus(), and RPC_GETFACTIONSTATUS__.
Referenced by MinefieldContainerComponent::checkContainerPermission(), GCWBaseContainerComponent::checkPVEPermission(), HealStatesOtherCommand::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), server::zone::objects::creature::ai::AiActorImplementation::isAggressiveTo(), server::zone::objects::creature::AiAgentImplementation::isAggressiveTo(), server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy(), server::zone::objects::creature::CreatureObjectImplementation::isHealableBy(), and server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner().
int PlayerObject::getFoodFilling ()
Definition at line 2200 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getFoodFilling(), and RPC_GETFOODFILLING__.
Referenced by server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), and PlayerObjectDeltaMessage9::updateStomachFilling().
int PlayerObject::getFoodFillingMax ()
Definition at line 2213 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getFoodFillingMax(), and RPC_GETFOODFILLINGMAX__.
Referenced by server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), and PlayerObjectDeltaMessage9::updateStomachFilling().
int PlayerObject::getForcePower ()
Definition at line 2124 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getForcePower(), and RPC_GETFORCEPOWER__.
int PlayerObject::getForcePowerMax ()
Definition at line 2137 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getForcePowerMax(), and RPC_GETFORCEPOWERMAX__.
int PlayerObject::getForcePowerRegen ()
Definition at line 1358 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getForcePowerRegen(), and RPC_GETFORCEPOWERREGEN__.
DeltaVector< String > * PlayerObject::getFriendList ()
Definition at line 2278 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getFriendList().
Referenced by FriendsListMessage::FriendsListMessage().
Vector< byte > * PlayerObject::getHologrindProfessions ()
Definition at line 2759 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getHologrindProfessions().
Referenced by PlayerInfoCommand::executeCommand().
DeltaVector< String > * PlayerObject::getIgnoreList ()
Definition at line 2357 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getIgnoreList().
Referenced by IgnoreListMessage::IgnoreListMessage().
byte PlayerObject::getIncapacitationCounter ()
Definition at line 1629 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getIncapacitationCounter(), and RPC_GETINCAPACITATIONCOUNTER__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::notifyDestruction().
int PlayerObject::getJediState ()
Definition at line 2252 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getJediState(), and RPC_GETJEDISTATE__.
Referenced by server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::fillAttributeList(), and server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner().
byte PlayerObject::getLanguageID ()
Definition at line 2265 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getLanguageID(), and RPC_GETLANGUAGEID__.
String PlayerObject::getLastNpcConvMessStr ()
Definition at line 851 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getLastNpcConvMessStr(), and RPC_GETLASTNPCCONVMESSSTR__.
String PlayerObject::getLastNpcConvOption (int idx)
Definition at line 866 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getLastNpcConvOption(), and RPC_GETLASTNPCCONVOPTION__INT_.
String PlayerObject::getLastNpcConvStr ()
Definition at line 836 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getLastNpcConvStr(), and RPC_GETLASTNPCCONVSTR__.
ValidatedPosition * PlayerObject::getLastValidatedPosition ()
Definition at line 2581 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getLastValidatedPosition().
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackSecondTest(), and ShipUpdateTransformCallback::run().
Time PlayerObject::getLastVisibilityUpdateTimestamp ()
Definition at line 3002 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getLastVisibilityUpdateTimestamp().
int PlayerObject::getLotsRemaining ()
Definition at line 204 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getLotsRemaining(), and RPC_GETLOTSREMAINING__.
byte PlayerObject::getMaximumLots ()
Definition at line 2809 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getMaximumLots(), and RPC_GETMAXIMUMLOTS__.
unsigned int PlayerObject::getNewSuiBoxID (unsigned int type)
Definition at line 1384 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getNewSuiBoxID(), and RPC_GETNEWSUIBOXID__INT_.
int PlayerObject::getNumBadges ()
Definition at line 1794 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getNumBadges(), and RPC_GETNUMBADGES__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::awardBadge().
unsigned long long PlayerObject::getOwnedStructure (int i)
Definition at line 190 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getOwnedStructure(), and RPC_GETOWNEDSTRUCTURE__INT_.
Referenced by server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership(), and server::zone::managers::gcw::GCWManagerImplementation::canPlaceMoreBases().
unsigned long long PlayerObject::getPerformanceBuffTarget ()
Definition at line 2921 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getPerformanceBuffTarget(), and RPC_GETPERFORMANCEBUFFTARGET__.
SortedVector< String > * PlayerObject::getPermissionGroups ()
Definition at line 1555 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getPermissionGroups().
Referenced by ContainerComponent::checkContainerPermission().
SortedVector< unsigned long long > * PlayerObject::getPersistentMessages ()
Definition at line 996 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getPersistentMessages().
Referenced by server::chat::ChatManagerImplementation::deletePersistentMessage(), server::chat::ChatManagerImplementation::handleRequestPersistentMsg(), and server::chat::ChatManagerImplementation::loadMail().
byte PlayerObject::getRaceID ()
Definition at line 2768 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getRaceID(), and RPC_GETRACEID__.
unsigned long long PlayerObject::getSavedParentID ()
Definition at line 1371 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getSavedParentID(), and RPC_GETSAVEDPARENTID__.
String PlayerObject::getSavedTerrainName ()
Definition at line 1258 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getSavedTerrainName(), and RPC_GETSAVEDTERRAINNAME__.
DraftSchematic * PlayerObject::getSchematic (int i)
Definition at line 2177 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getSchematic(), and RPC_GETSCHEMATIC__INT_.
SchematicList * PlayerObject::getSchematics ()
Definition at line 2168 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getSchematics().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase().
String PlayerObject::getScreenPlayData (const String & screenPlay, const String & variable)
Definition at line 618 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getScreenPlayData(), and RPC_GETSCREENPLAYDATA__STRING_STRING_.
unsigned long long PlayerObject::getServerMovementTimeDelta ()
Definition at line 2642 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getServerMovementTimeDelta(), and RPC_GETSERVERMOVEMENTTIMEDELTA__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackSecondTest().
Time * PlayerObject::getServerMovementTimeStamp ()
Definition at line 2655 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getServerMovementTimeStamp().
int PlayerObject::getSkillPoints ()
Definition at line 2568 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getSkillPoints(), and RPC_GETSKILLPOINTS__.
Referenced by PlayerInfoCommand::executeCommand(), and server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase().
String PlayerObject::getStarterProfession ()
Definition at line 2822 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getStarterProfession(), and RPC_GETSTARTERPROFESSION__.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addStartingItemsInto(), and server::zone::managers::player::creation::PlayerCreationManager::addStartingWeaponsInto().
SuiBox * PlayerObject::getSuiBox (unsigned int boxID)
Definition at line 1412 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getSuiBox(), and RPC_GETSUIBOX__INT_.
Referenced by server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::closeMenu().
SuiBox * PlayerObject::getSuiBoxFromWindowType (unsigned int windowType)
Definition at line 1483 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getSuiBoxFromWindowType(), and RPC_GETSUIBOXFROMWINDOWTYPE__INT_.
WaypointObject * PlayerObject::getSurveyWaypoint ()
Returns the active SurveyWaypoint
Definition at line 589 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getSurveyWaypoint(), and RPC_GETSURVEYWAYPOINT__.
Referenced by server::zone::objects::player::sessions::survey::SurveySessionImplementation::surveyCnodeMinigame().
String PlayerObject::getTitle ()
Definition at line 1940 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getTitle(), and RPC_GETTITLE__.
Referenced by PlayerObjectMessage3::PlayerObjectMessage3().
int PlayerObject::getTotalOwnedStructureCount ()
Definition at line 163 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getTotalOwnedStructureCount(), and RPC_GETTOTALOWNEDSTRUCTURECOUNT__.
Referenced by server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership(), and server::zone::managers::gcw::GCWManagerImplementation::canPlaceMoreBases().
Vector3 PlayerObject::getTrainerCoordinates ()
Definition at line 958 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getTrainerCoordinates().
String PlayerObject::getTrainerZoneName ()
Definition at line 981 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getTrainerZoneName(), and RPC_GETTRAINERZONENAME__.
int PlayerObject::getVendorCount ()
Definition at line 3039 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getVendorCount(), and RPC_GETVENDORCOUNT__.
float PlayerObject::getVisibility ()
Definition at line 2975 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::getVisibility(), and RPC_GETVISIBILITY__.
WaypointList * PlayerObject::getWaypointList ()
Definition at line 2150 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getWaypointList().
Referenced by server::zone::objects::player::sessions::FindSessionImplementation::clearWaypoint(), and FindCommand::doQueueCommand().
VectorMap< String, int > * PlayerObject::getXpTypeCapList ()
Definition at line 2106 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::getXpTypeCapList().
Referenced by server::zone::managers::skill::SkillManager::updateXpLimits().
bool PlayerObject::hasAbility (const String & ability)
Checks to see if this player object has the specified ability.
Parameters
ability The ability to search for.
Returns
True if the player has the ability.
Definition at line 1904 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::hasAbility().
Referenced by server::zone::managers::skill::SkillManager::addAbilities(), CombatManager::calculateDamageRange(), ProneCommand::doQueueCommand(), server::zone::objects::tangible::tool::SurveyToolImplementation::handleObjectMenuSelect(), StructureManager::payMaintenance(), server::zone::managers::city::CityManagerImplementation::promptRegisterCity(), server::zone::managers::skill::SkillManager::removeAbilities(), and server::zone::managers::city::CityManagerImplementation::sendManageMilitia().
bool PlayerObject::hasBadge (unsigned int badge)
Definition at line 2422 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::hasBadge(), and RPC_HASBADGE__INT_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::awardBadge().
bool PlayerObject::hasCappedExperience (const String & xpType)
Checks if the player has capped the experience type.
Parameters
xpType The string value for the type of experience to check.
Returns
true if experience is capped, false otherwise.
Definition at line 275 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::hasCappedExperience(), and RPC_HASCAPPEDEXPERIENCE__STRING_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::awardExperience().
bool PlayerObject::hasCommandMessageString (unsigned int actionCRC)
Definition at line 1913 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::hasCommandMessageString(), and RPC_HASCOMMANDMESSAGESTRING__INT_.
bool PlayerObject::hasFriend (const String & name)
Definition at line 1821 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::hasFriend(), and RPC_HASFRIEND__STRING_.
Referenced by FindFriendCommand::doQueueCommand().
bool PlayerObject::hasInConsentList (const String & name)
Definition at line 1060 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::hasInConsentList(), and RPC_HASINCONSENTLIST__STRING_.
bool PlayerObject::hasLotsRemaining (int lots)
Definition at line 217 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::hasLotsRemaining(), and RPC_HASLOTSREMAINING__INT_.
bool PlayerObject::hasPermissionGroup (const String & group)
Definition at line 1541 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::hasPermissionGroup(), and RPC_HASPERMISSIONGROUP__STRING_.
bool PlayerObject::hasSpawnedBlueFrog ()
Definition at line 2616 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::hasSpawnedBlueFrog(), and RPC_HASSPAWNEDBLUEFROG__.
bool PlayerObject::hasSuiBox (unsigned int boxID)
Definition at line 1398 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::hasSuiBox(), and RPC_HASSUIBOX__INT_.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::canUseTurret(), and server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::closeMenu().
bool PlayerObject::hasSuiBoxWindowType (unsigned int windowType)
Definition at line 1455 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::hasSuiBoxWindowType(), and RPC_HASSUIBOXWINDOWTYPE__INT_.
Referenced by server::zone::objects::building::BuildingObjectImplementation::promptPayAccessFee(), server::zone::managers::city::CityManagerImplementation::sendChangeCityName(), server::zone::managers::city::CityManagerImplementation::sendCitizenshipReport(), and server::zone::managers::gcw::GCWManagerImplementation::sendTurretAttackListTo().
bool PlayerObject::hasWaypoint (unsigned long long objectID)
Definition at line 1890 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::hasWaypoint(), and RPC_HASWAYPOINT__LONG_.
void PlayerObject::increaseFactionStanding (const String & factionName, float amount)
Adds the amount of faction points to the faction point list.
Precondition
{ this locked }
Postcondition
{ this locked }
Parameters
factionName The string key for the faction the faction points are to be added.
amount The float amount of faction points to add.
Definition at line 545 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::increaseFactionStanding(), and RPC_INCREASEFACTIONSTANDING__STRING_FLOAT_.
Referenced by DelegateFactionPointsCommand::doDelegate().
void PlayerObject::initializeTransientMembers ()
Definition at line 94 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
bool PlayerObject::isAFK ()
is the player AFK
Definition at line 2093 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isAFK(), and RPC_ISAFK__.
bool PlayerObject::isBountyLocked ()
Definition at line 2908 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isBountyLocked(), and RPC_ISBOUNTYLOCKED__.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::isHealableBy().
bool PlayerObject::isCSR ()
Definition at line 2009 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isCSR(), and RPC_ISCSR__.
bool PlayerObject::isDeveloper ()
Definition at line 1996 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isDeveloper(), and RPC_ISDEVELOPER__.
bool PlayerObject::isDigesting ()
Definition at line 1245 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isDigesting(), and RPC_ISDIGESTING__.
bool PlayerObject::isDuelListEmpty ()
Definition at line 1698 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isDuelListEmpty(), and RPC_ISDUELLISTEMPTY__.
Referenced by CombatManager::freeDuelList().
bool PlayerObject::isFirstIncapacitation ()
Definition at line 1616 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isFirstIncapacitation(), and RPC_ISFIRSTINCAPACITATION__.
bool PlayerObject::isFirstIncapacitationExpired ()
Definition at line 1564 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isFirstIncapacitationExpired(), and RPC_ISFIRSTINCAPACITATIONEXPIRED__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::notifyDestruction().
bool PlayerObject::isIgnoring (const String & name)
Definition at line 1835 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isIgnoring(), and RPC_ISIGNORING__STRING_.
bool PlayerObject::isInBountyLockList (unsigned long long playerId)
Definition at line 2865 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isInBountyLockList(), and RPC_ISINBOUNTYLOCKLIST__LONG_.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::isAggressiveTo(), and server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy().
bool PlayerObject::isJedi ()
Definition at line 3066 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isJedi(), and RPC_ISJEDI__.
Referenced by PlayerContainerComponent::notifyObjectInserted().
bool PlayerObject::isLinkDead ()
Definition at line 2501 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isLinkDead(), and RPC_ISLINKDEAD__.
bool PlayerObject::isLoading ()
Definition at line 2488 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isLoading(), and RPC_ISLOADING__.
bool PlayerObject::isLoggingIn ()
Definition at line 2514 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isLoggingIn(), and RPC_ISLOGGINGIN__.
bool PlayerObject::isLoggingOut ()
Definition at line 2527 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isLoggingOut(), and RPC_ISLOGGINGOUT__.
Referenced by InvisibleDelayEvent::run().
bool PlayerObject::isOffline ()
Definition at line 2475 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isOffline(), and RPC_ISOFFLINE__.
bool PlayerObject::isOnline ()
Definition at line 2462 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isOnline(), and RPC_ISONLINE__.
bool PlayerObject::isOwnedStructure (StructureObject * obj)
Definition at line 176 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isOwnedStructure(), and RPC_ISOWNEDSTRUCTURE__STRUCTUREOBJECT_.
bool PlayerObject::isPrivileged ()
Definition at line 2022 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isPrivileged(), and RPC_ISPRIVILEGED__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::banAccount(), server::zone::managers::player::PlayerManagerImplementation::banCharacter(), server::zone::managers::player::PlayerManagerImplementation::banFromGalaxy(), StructureManager::declareResidence(), server::zone::objects::building::BuildingObjectImplementation::ejectObject(), server::zone::managers::city::CityManagerImplementation::sendChangeCityName(), server::zone::managers::player::PlayerManagerImplementation::unbanAccount(), server::zone::managers::player::PlayerManagerImplementation::unbanCharacter(), server::zone::managers::player::PlayerManagerImplementation::unbanFromGalaxy(), DataTransformCallback::updatePosition(), and DataTransformWithParentCallback::updatePosition().
bool PlayerObject::isTeleporting ()
Definition at line 2287 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::isTeleporting(), and RPC_ISTELEPORTING__.
Referenced by server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage(), ShipUpdateTransformCallback::run(), DataTransformCallback::updatePosition(), and DataTransformWithParentCallback::updatePosition().
void PlayerObject::loadTemplateData (SharedObjectTemplate * templateData)
Definition at line 85 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::loadTemplateData().
void PlayerObject::logout (bool doLock)
Definition at line 770 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::logout(), and RPC_LOGOUT__BOOL_.
Referenced by DisconnectClientEvent::run().
void PlayerObject::maximizeExperience ()
Maximizes all types of experience for the player.
Definition at line 2380 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::maximizeExperience(), and RPC_MAXIMIZEEXPERIENCE__.
Referenced by server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem().
void PlayerObject::notifyLoadFromDatabase ()
Gets called when this objects is loaded from database
Precondition
{ this locked }
Postcondition
{ this locked }
Definition at line 59 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::notifyLoadFromDatabase(), and RPC_NOTIFYLOADFROMDATABASE__.
void PlayerObject::notifyOffline ()
Notifies all reverse friends offline status
Precondition
{ }
Postcondition
{ }
Definition at line 1739 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::notifyOffline(), and RPC_NOTIFYOFFLINE__.
void PlayerObject::notifyOnline ()
Notifies all reverse friends online status
Precondition
{ }
Postcondition
{ }
Definition at line 1218 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::notifyOnline(), and RPC_NOTIFYONLINE__.
void PlayerObject::notifySceneReady ()
Definition at line 231 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::notifySceneReady(), and RPC_NOTIFYSCENEREADY__.
void PlayerObject::reload (ZoneClientSession * client)
Definition at line 690 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::reload(), and RPC_RELOAD__ZONECLIENTSESSION_.
void PlayerObject::removeAbilities (Vector< Ability * > & abilities, bool notifyClient = true)
Removes certifications from player
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
skills Vector of skills to add
notifyClient determines whether to update the client with the changes
Definition at line 362 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::removeAbilities().
Referenced by server::zone::managers::skill::SkillManager::removeAbilities().
void PlayerObject::removeAbility (Ability * ability, bool notifyClient = true)
Definition at line 371 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::removeAbility().
Referenced by server::zone::managers::skill::SkillManager::removeAbility().
void PlayerObject::removeChatRoom (ChatRoom * room)
Definition at line 2314 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeChatRoom(), and RPC_REMOVECHATROOM__CHATROOM_.
Referenced by server::chat::room::ChatRoomImplementation::removeAllPlayers(), and server::chat::room::ChatRoomImplementation::removePlayer().
void PlayerObject::removeCommandMessageString (unsigned int actionCRC)
Definition at line 1150 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeCommandMessageString(), and RPC_REMOVECOMMANDMESSAGESTRING__INT_.
void PlayerObject::removeExperience (const String & xpType, bool notifyClient = true)
Removes experience of a type from the player's experience pool.
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
xpType The string value for the type of experience to remove.
notifyClient Boolean to determing whether the client should receive a delta packet for the experience loss.
Definition at line 260 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeExperience(), and RPC_REMOVEEXPERIENCE__STRING_BOOL_.
void PlayerObject::removeFriend (const String & name, bool notifyClient = true)
Removes the specified friend from the friend list
Precondition
{ this is locked }
Postcondition
{ this is locked}
Parameters
name friend name to remove
notifyClient determines whether to update the client with the changes
Definition at line 455 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeFriend(), and RPC_REMOVEFRIEND__STRING_BOOL_.
void PlayerObject::removeFromBountyLockList (unsigned long long playerId, bool immediately)
Definition at line 2879 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeFromBountyLockList(), and RPC_REMOVEFROMBOUNTYLOCKLIST__LONG_BOOL_.
void PlayerObject::removeFromBountyLockListDirectly (unsigned long long playerId)
Definition at line 2894 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeFromBountyLockListDirectly(), and RPC_REMOVEFROMBOUNTYLOCKLISTDIRECTLY__LONG_.
void PlayerObject::removeFromConsentList (const String & name)
Definition at line 1074 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeFromConsentList(), and RPC_REMOVEFROMCONSENTLIST__STRING_.
Referenced by UnconsentCommand::unconscent().
void PlayerObject::removeFromDuelList (CreatureObject * targetPlayer)
Definition at line 1656 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeFromDuelList(), and RPC_REMOVEFROMDUELLIST__CREATUREOBJECT_.
Referenced by CombatManager::declineDuel(), CombatManager::freeDuelList(), and CombatManager::requestEndDuel().
void PlayerObject::removeIgnore (const String & name, bool notifyClient = true)
Removes the specified player from the ignore list
Precondition
{ this is locked }
Postcondition
{ this is locked}
Parameters
name player name to remove
notifyClient determines whether to update the client with the changes
Definition at line 485 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeIgnore(), and RPC_REMOVEIGNORE__STRING_BOOL_.
void PlayerObject::removeOwnedStructure (StructureObject * obj)
Definition at line 149 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeOwnedStructure(), and RPC_REMOVEOWNEDSTRUCTURE__STRUCTUREOBJECT_.
Referenced by server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership(), and DestroyStructureTask::run().
void PlayerObject::removePermissionGroup (const String & group, bool updateInRangeBuildingPermissions = false)
Definition at line 1526 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removePermissionGroup(), and RPC_REMOVEPERMISSIONGROUP__STRING_BOOL_.
void PlayerObject::removeReverseFriend (const String & name)
Definition at line 1863 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeReverseFriend(), and RPC_REMOVEREVERSEFRIEND__STRING_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::removeFriend().
void PlayerObject::removeRewardedSchematic (DraftSchematic * schematic, bool notifyClient = true)
Definition at line 407 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::removeRewardedSchematic().
void PlayerObject::removeSchematics (Vector< ManagedReference< DraftSchematic * > > & schematics, bool notifyClient = true)
Definition at line 389 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::removeSchematics().
Referenced by SchematicMap::removeSchematics().
void PlayerObject::removeSuiBox (unsigned int boxID, bool closeWindowToClient = false)
Removes the specified box id and optionally closes the client sui
Definition at line 1426 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeSuiBox(), and RPC_REMOVESUIBOX__INT_BOOL_.
Referenced by server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::closeMenu().
void PlayerObject::removeSuiBoxType (unsigned int windowType)
Definition at line 1441 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeSuiBoxType(), and RPC_REMOVESUIBOXTYPE__INT_.
Referenced by server::zone::managers::minigames::FishingManagerImplementation::closeMenu(), and server::zone::managers::player::PlayerManagerImplementation::sendActivateCloneRequest().
void PlayerObject::removeVendor (SceneObject * vendor)
Definition at line 3025 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeVendor(), and RPC_REMOVEVENDOR__SCENEOBJECT_.
Referenced by DestroyStructureTask::run().
void PlayerObject::removeWaypoint (unsigned long long waypointID, bool notifyClient = true)
Removes a waypoint from this player
Precondition
{ this is locked }
Postcondition
{ this is locked, waypoint list doesnt contain the specified waypoint }
Parameters
waypointID waypoint object id to remove
notifyClient determines whether to update the client with the changes
Definition at line 329 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::removeWaypoint(), and RPC_REMOVEWAYPOINT__LONG_BOOL_.
Referenced by server::zone::objects::player::sessions::FindSessionImplementation::clearWaypoint(), ServerDestroyObjectCommand::doQueueCommand(), FindCommand::doQueueCommand(), and server::zone::objects::player::sessions::survey::SurveySessionImplementation::surveyCnodeMinigame().
bool PlayerObject::requestedDuelTo (CreatureObject * targetPlayer)
Definition at line 1684 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::requestedDuelTo(), and RPC_REQUESTEDDUELTO__CREATUREOBJECT_.
Referenced by CombatManager::declineDuel(), CombatManager::freeDuelList(), server::zone::objects::creature::CreatureObjectImplementation::isAggressiveTo(), server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy(), server::zone::managers::player::PlayerManagerImplementation::killPlayer(), CombatManager::requestDuel(), and CombatManager::requestEndDuel().
void PlayerObject::resetFirstIncapacitationTime ()
Definition at line 1590 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::resetFirstIncapacitationTime(), and RPC_RESETFIRSTINCAPACITATIONTIME__.
void PlayerObject::resetIncapacitationCounter ()
Definition at line 1577 of file PlayerObject.cpp.
References _getImplementation(), server::zone::objects::player::PlayerObjectImplementation::resetIncapacitationCounter(), and RPC_RESETINCAPACITATIONCOUNTER__.
void PlayerObject::sendBadgesResponseTo (CreatureObject * player)
Sends a badges response message
Precondition
{ }
Postcondition
{ }
Parameters
player CreatureObject to receive badges response message
Definition at line 756 of file PlayerObject.cpp.
References _getImplementation(), RPC_SENDBADGESRESPONSETO__CREATUREOBJECT_, and server::zone::objects::player::PlayerObjectImplementation::sendBadgesResponseTo().
void PlayerObject::sendBaselinesTo (SceneObject * player)
Definition at line 107 of file PlayerObject.cpp.
References _getImplementation(), RPC_SENDBASELINESTO__SCENEOBJECT_, and server::zone::objects::player::PlayerObjectImplementation::sendBaselinesTo().
void PlayerObject::sendFriendLists ()
Definition at line 1877 of file PlayerObject.cpp.
References _getImplementation(), RPC_SENDFRIENDLISTS__, and server::zone::objects::player::PlayerObjectImplementation::sendFriendLists().
void PlayerObject::sendMessage (BasePacket * msg)
Definition at line 121 of file PlayerObject.cpp.
References _getImplementation(), RPC_SENDMESSAGE__BASEPACKET_, and server::zone::objects::player::PlayerObjectImplementation::sendMessage().
void PlayerObject::setAccountID (unsigned int id)
Definition at line 2691 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETACCOUNTID__INT_, and server::zone::objects::player::PlayerObjectImplementation::setAccountID().
void PlayerObject::setAdminLevel (unsigned int adminlvl)
Definition at line 1968 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETADMINLEVEL__INT_, and server::zone::objects::player::PlayerObjectImplementation::setAdminLevel().
void PlayerObject::setBadge (unsigned int badge)
Definition at line 1752 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETBADGE__INT_, and server::zone::objects::player::PlayerObjectImplementation::setBadge().
Referenced by server::zone::managers::player::PlayerManagerImplementation::awardBadge().
void PlayerObject::setBankLocation (const String & location)
Definition at line 2328 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETBANKLOCATION__STRING_, and server::zone::objects::player::PlayerObjectImplementation::setBankLocation().
void PlayerObject::setBiography (const UnicodeString & bio)
Definition at line 1982 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETBIOGRAPHY__UNICODESTRING_, and server::zone::objects::player::PlayerObjectImplementation::setBiography().
bool PlayerObject::setCharacterBit (unsigned int bit, bool notifyClient = false)
Definition at line 2049 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETCHARACTERBIT__INT_BOOL_, and server::zone::objects::player::PlayerObjectImplementation::setCharacterBit().
void PlayerObject::setCharacterBitmask (unsigned int bitmask)
Definition at line 2035 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETCHARACTERBITMASK__INT_, and server::zone::objects::player::PlayerObjectImplementation::setCharacterBitmask().
void PlayerObject::setClientLastMovementStamp (unsigned int stamp)
Definition at line 2664 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETCLIENTLASTMOVEMENTSTAMP__INT_, and server::zone::objects::player::PlayerObjectImplementation::setClientLastMovementStamp().
Referenced by PlayerZoneComponent::teleport(), DataTransformCallback::updatePosition(), and DataTransformWithParentCallback::updatePosition().
void PlayerObject::setCloningFacility (BuildingObject * cloningfac)
Definition at line 1191 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETCLONINGFACILITY__BUILDINGOBJECT_, and server::zone::objects::player::PlayerObjectImplementation::setCloningFacility().
Referenced by server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner().
void PlayerObject::setCommandMessageString (unsigned int actionCRC, String & message)
Definition at line 1135 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETCOMMANDMESSAGESTRING__INT_STRING_, and server::zone::objects::player::PlayerObjectImplementation::setCommandMessageString().
void PlayerObject::setConversatingCreature (CreatureObject * creature)
Definition at line 922 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETCONVERSATINGCREATURE__CREATUREOBJECT_, and server::zone::objects::player::PlayerObjectImplementation::setConversatingCreature().
void PlayerObject::setDebug (bool value)
Definition at line 2948 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETDEBUG__BOOL_, and server::zone::objects::player::PlayerObjectImplementation::setDebug().
void PlayerObject::setDeclaredResidence (BuildingObject * residence)
Definition at line 1177 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETDECLAREDRESIDENCE__BUILDINGOBJECT_, and server::zone::objects::player::PlayerObjectImplementation::setDeclaredResidence().
Referenced by StructureManager::declareResidence(), and server::zone::objects::region::CityRegionImplementation::transferCivicStructuresToMayor().
void PlayerObject::setDrinkFilling (int newValue, bool notifyClient = true)
Definition at line 530 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETDRINKFILLING__INT_BOOL_, and server::zone::objects::player::PlayerObjectImplementation::setDrinkFilling().
Referenced by server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect().
void PlayerObject::setFactionRank (const String & rank)
Definition at line 1126 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::setFactionRank().
void PlayerObject::setFactionStatus (int status)
Definition at line 2718 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETFACTIONSTATUS__INT_, and server::zone::objects::player::PlayerObjectImplementation::setFactionStatus().
Referenced by server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner().
void PlayerObject::setFoodFilling (int newValue, bool notifyClient = true)
Definition at line 515 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETFOODFILLING__INT_BOOL_, and server::zone::objects::player::PlayerObjectImplementation::setFoodFilling().
Referenced by server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect().
void PlayerObject::setForcePower (int fp, bool notifyClient = true)
Definition at line 1301 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETFORCEPOWER__INT_BOOL_, and server::zone::objects::player::PlayerObjectImplementation::setForcePower().
void PlayerObject::setForcePowerMax (int newValue, bool notifyClient = true)
Definition at line 1316 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETFORCEPOWERMAX__INT_BOOL_, and server::zone::objects::player::PlayerObjectImplementation::setForcePowerMax().
void PlayerObject::setForcePowerRegen (int val)
Definition at line 1344 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETFORCEPOWERREGEN__INT_, and server::zone::objects::player::PlayerObjectImplementation::setForcePowerRegen().
void PlayerObject::setJediState (int state, bool notifyClient = true)
Definition at line 784 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETJEDISTATE__INT_BOOL_, and server::zone::objects::player::PlayerObjectImplementation::setJediState().
void PlayerObject::setLanguageID (byte language, bool notifyClient = true)
Sets the specified language id
Precondition
{ }
Postcondition
{ }
Parameters
language language id to set
notifyClient determines whether to update the client with the changes
Definition at line 425 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETLANGUAGEID__BYTE_BOOL_, and server::zone::objects::player::PlayerObjectImplementation::setLanguageID().
void PlayerObject::setLastNpcConvMessStr (const String & mess)
Definition at line 822 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETLASTNPCCONVMESSSTR__STRING_, and server::zone::objects::player::PlayerObjectImplementation::setLastNpcConvMessStr().
Referenced by server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationStartTo(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendInitialChoices(), and server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendInitialMessage().
void PlayerObject::setLastNpcConvStr (const String & conv)
Definition at line 808 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETLASTNPCCONVSTR__STRING_, and server::zone::objects::player::PlayerObjectImplementation::setLastNpcConvStr().
Referenced by server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationStartTo().
void PlayerObject::setLinkDead ()
Definition at line 717 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETLINKDEAD__, and server::zone::objects::player::PlayerObjectImplementation::setLinkDead().
Referenced by DisconnectClientEvent::run().
void PlayerObject::setLoggingOut ()
Definition at line 743 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETLOGGINGOUT__, and server::zone::objects::player::PlayerObjectImplementation::setLoggingOut().
Referenced by server::zone::managers::player::PlayerManagerImplementation::kickUser().
void PlayerObject::setMaximumLots (byte lots)
Definition at line 2795 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETMAXIMUMLOTS__BYTE_, and server::zone::objects::player::PlayerObjectImplementation::setMaximumLots().
void PlayerObject::setOffline ()
Definition at line 704 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETOFFLINE__, and server::zone::objects::player::PlayerObjectImplementation::setOffline().
void PlayerObject::setOnline ()
Definition at line 730 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETONLINE__, and server::zone::objects::player::PlayerObjectImplementation::setOnline().
void PlayerObject::setPerformanceBuffTarget (unsigned long long target)
Definition at line 2934 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETPERFORMANCEBUFFTARGET__LONG_, and server::zone::objects::player::PlayerObjectImplementation::setPerformanceBuffTarget().
void PlayerObject::setRaceID (byte race)
Definition at line 2781 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETRACEID__BYTE_, and server::zone::objects::player::PlayerObjectImplementation::setRaceID().
void PlayerObject::setSavedParentID (unsigned long long id)
Definition at line 1273 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETSAVEDPARENTID__LONG_, and server::zone::objects::player::PlayerObjectImplementation::setSavedParentID().
Referenced by server::zone::managers::player::PlayerManagerImplementation::createSkippedTutorialBuilding(), and server::zone::managers::player::PlayerManagerImplementation::createTutorialBuilding().
void PlayerObject::setSavedTerrainName (const String & name)
Definition at line 1287 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETSAVEDTERRAINNAME__STRING_, and server::zone::objects::player::PlayerObjectImplementation::setSavedTerrainName().
Referenced by server::zone::managers::player::PlayerManagerImplementation::createSkippedTutorialBuilding(), server::zone::managers::player::PlayerManagerImplementation::createTutorialBuilding(), and PlayerZoneComponent::notifyInsertToZone().
void PlayerObject::setScreenPlayData (const String & screenPlay, const String & variable, const String & data)
Definition at line 602 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETSCREENPLAYDATA__STRING_STRING_STRING_, and server::zone::objects::player::PlayerObjectImplementation::setScreenPlayData().
Referenced by server::zone::managers::director::DirectorManager::writeScreenPlayData().
void PlayerObject::setSkillPoints (int points)
Definition at line 2540 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETSKILLPOINTS__INT_, and server::zone::objects::player::PlayerObjectImplementation::setSkillPoints().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase().
void PlayerObject::setSpawnedBlueFrog ()
Definition at line 2603 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETSPAWNEDBLUEFROG__, and server::zone::objects::player::PlayerObjectImplementation::setSpawnedBlueFrog().
void PlayerObject::setStarterProfession (String & profession)
Definition at line 2837 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETSTARTERPROFESSION__STRING_, and server::zone::objects::player::PlayerObjectImplementation::setStarterProfession().
void PlayerObject::setTeleporting (bool val)
Definition at line 1780 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETTELEPORTING__BOOL_, and server::zone::objects::player::PlayerObjectImplementation::setTeleporting().
Referenced by server::zone::objects::intangible::ShipControlDeviceImplementation::generateObject(), InsertedAsPilotCallback::run(), and PlayerZoneComponent::teleport().
void PlayerObject::setTitle (const String & characterTitle, bool notifyClient = true)
Definition at line 500 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETTITLE__STRING_BOOL_, and server::zone::objects::player::PlayerObjectImplementation::setTitle().
void PlayerObject::setTrainerCoordinates (const Vector3 & trainer)
Definition at line 949 of file PlayerObject.cpp.
References _getImplementation(), and server::zone::objects::player::PlayerObjectImplementation::setTrainerCoordinates().
void PlayerObject::setTrainerZoneName (String & zoneName)
Definition at line 967 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETTRAINERZONENAME__STRING_, and server::zone::objects::player::PlayerObjectImplementation::setTrainerZoneName().
void PlayerObject::setVisibility (float value)
Definition at line 2988 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETVISIBILITY__FLOAT_, and server::zone::objects::player::PlayerObjectImplementation::setVisibility().
void PlayerObject::setWaypoint (WaypointObject * waypoint, bool notifyClient = true)
Definition at line 305 of file PlayerObject.cpp.
References _getImplementation(), RPC_SETWAYPOINT__WAYPOINTOBJECT_BOOL_, and server::zone::objects::player::PlayerObjectImplementation::setWaypoint().
void PlayerObject::toggleCharacterBit (unsigned int bit)
Definition at line 2079 of file PlayerObject.cpp.
References _getImplementation(), RPC_TOGGLECHARACTERBIT__INT_, and server::zone::objects::player::PlayerObjectImplementation::toggleCharacterBit().
Referenced by AnonCommand::doQueueCommand(), ToggleDisplayingFactionRankCommand::doQueueCommand(), ToggleAwayFromKeyBoardCommand::doQueueCommand(), LfgCommand::doQueueCommand(), NewbiehelperCommand::doQueueCommand(), and RolePlayCommand::doQueueCommand().
void PlayerObject::unload ()
Definition at line 72 of file PlayerObject.cpp.
References _getImplementation(), RPC_UNLOAD__, and server::zone::objects::player::PlayerObjectImplementation::unload().
void PlayerObject::unloadSpawnedChildren ()
Unloads all the spawned creatures from the datapad control devices
Definition at line 1033 of file PlayerObject.cpp.
References _getImplementation(), RPC_UNLOADSPAWNEDCHILDREN__, and server::zone::objects::player::PlayerObjectImplementation::unloadSpawnedChildren().
void PlayerObject::updateIncapacitationCounter ()
Definition at line 1603 of file PlayerObject.cpp.
References _getImplementation(), RPC_UPDATEINCAPACITATIONCOUNTER__, and server::zone::objects::player::PlayerObjectImplementation::updateIncapacitationCounter().
Referenced by server::zone::managers::player::PlayerManagerImplementation::notifyDestruction().
void PlayerObject::updateLastValidatedPosition ()
Definition at line 2590 of file PlayerObject.cpp.
References _getImplementation(), RPC_UPDATELASTVALIDATEDPOSITION__, and server::zone::objects::player::PlayerObjectImplementation::updateLastValidatedPosition().
Referenced by PlayerZoneComponent::teleport().
void PlayerObject::updateServerLastMovementStamp ()
Definition at line 2678 of file PlayerObject.cpp.
References _getImplementation(), RPC_UPDATESERVERLASTMOVEMENTSTAMP__, and server::zone::objects::player::PlayerObjectImplementation::updateServerLastMovementStamp().
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackSecondTest(), and ShipUpdateTransformCallback::run().
Friends And Related Function Documentation
friend class PlayerObjectHelper friend
Definition at line 924 of file PlayerObject.h.
Member Data Documentation
const int server::zone::objects::player::PlayerObject::AFK = 0x80 static
Definition at line 283 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::ANONYMOUS = 0x80000000 static
Definition at line 289 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::CSR = 1 static
Definition at line 293 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::DEV = 2 static
Definition at line 295 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::FACTIONRANK = 0x200 static
Definition at line 287 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::LD = 0x100 static
Definition at line 285 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::LFG = 1 static
Definition at line 277 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::LINKDEAD = 3 static
Definition at line 301 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::LOADING = 6 static
Definition at line 307 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::LOGGINGIN = 4 static
Definition at line 303 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::LOGGINGOUT = 5 static
Definition at line 305 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::NEWBIEHELPER = 2 static
Definition at line 279 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::NORMALPLAYER = 0 static
Definition at line 291 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::OFFLINE = 2 static
Definition at line 299 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::ONLINE = 1 static
Definition at line 297 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObject::ROLEPLAYER = 4 static
Definition at line 281 of file PlayerObject.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/PlayerObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/PlayerObject.cpp