Core3: server::zone::objects::player::sessions::TradeSessionImplementation Class Reference
server::zone::objects::player::sessions::TradeSessionImplementation Class Reference
#include <TradeSession.h>
Public Member Functions
TradeSessionImplementation ()
TradeSessionImplementation (DummyConstructorParameter *param)
bool getAcceptedTrade ()
void addTradeItem (SceneObject *object)
SortedVector< ManagedReference
< SceneObject * > > * getItemsToTrade ()
SceneObject * getTradeItem (int index)
int getTradeSize ()
int getMoneyToTrade ()
unsigned long long getTradeTargetPlayer ()
bool isTryingToTrade ()
bool hasVerifiedTrade ()
void setAcceptedTrade (bool val)
void setMoneyToTrade (int val)
void setTradeTargetPlayer (unsigned long long val)
void setVerifiedTrade (bool val)
operator const TradeSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< TradeSession * > _this
Protected Member Functions
virtual ~TradeSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
unsigned long long tradeTargetPlayer
SortedVector< ManagedReference
< SceneObject * > > itemsToTrade
bool verifiedTrade
bool acceptedTrade
int moneyToTrade
Friends
class TradeSession
Detailed Description
Definition at line 111 of file TradeSession.h.
Constructor & Destructor Documentation
TradeSessionImplementation::TradeSessionImplementation ()
Definition at line 396 of file TradeSession.cpp.
References _initializeImplementation(), acceptedTrade, itemsToTrade, moneyToTrade, tradeTargetPlayer, and verifiedTrade.
TradeSessionImplementation::TradeSessionImplementation (DummyConstructorParameter * param)
Definition at line 222 of file TradeSession.cpp.
References _initializeImplementation().
TradeSessionImplementation::~TradeSessionImplementation () protected virtual
Definition at line 227 of file TradeSession.cpp.
Member Function Documentation
DistributedObjectStub * TradeSessionImplementation::_getStub ()
Definition at line 247 of file TradeSession.cpp.
References _this.
void TradeSessionImplementation::_initializeImplementation () protected
Definition at line 234 of file TradeSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by TradeSessionImplementation().
void TradeSessionImplementation::_serializationHelperMethod () protected
Definition at line 283 of file TradeSession.cpp.
Referenced by _initializeImplementation().
void TradeSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 242 of file TradeSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::TradeSession::TradeSession().
void TradeSessionImplementation::addTradeItem (SceneObject * object)
Definition at line 415 of file TradeSession.cpp.
References itemsToTrade.
Referenced by server::zone::objects::player::sessions::TradeSession::addTradeItem().
void TradeSessionImplementation::finalize () protected
Definition at line 231 of file TradeSession.cpp.
bool TradeSessionImplementation::getAcceptedTrade ()
Definition at line 410 of file TradeSession.cpp.
References acceptedTrade.
Referenced by server::zone::objects::player::sessions::TradeSession::getAcceptedTrade().
SortedVector< ManagedReference< SceneObject * > > * TradeSessionImplementation::getItemsToTrade ()
Definition at line 420 of file TradeSession.cpp.
References itemsToTrade.
Referenced by server::zone::objects::player::sessions::TradeSession::getItemsToTrade().
int TradeSessionImplementation::getMoneyToTrade ()
Definition at line 435 of file TradeSession.cpp.
References moneyToTrade.
Referenced by server::zone::objects::player::sessions::TradeSession::getMoneyToTrade().
SceneObject * TradeSessionImplementation::getTradeItem (int index)
Definition at line 425 of file TradeSession.cpp.
References itemsToTrade.
Referenced by server::zone::objects::player::sessions::TradeSession::getTradeItem().
int TradeSessionImplementation::getTradeSize ()
Definition at line 430 of file TradeSession.cpp.
References itemsToTrade.
Referenced by server::zone::objects::player::sessions::TradeSession::getTradeSize().
unsigned long long TradeSessionImplementation::getTradeTargetPlayer ()
Definition at line 440 of file TradeSession.cpp.
References tradeTargetPlayer.
Referenced by server::zone::objects::player::sessions::TradeSession::getTradeTargetPlayer().
bool TradeSessionImplementation::hasVerifiedTrade ()
Definition at line 450 of file TradeSession.cpp.
References verifiedTrade.
Referenced by server::zone::objects::player::sessions::TradeSession::hasVerifiedTrade().
bool TradeSessionImplementation::isTryingToTrade ()
Definition at line 445 of file TradeSession.cpp.
References tradeTargetPlayer.
Referenced by server::zone::objects::player::sessions::TradeSession::isTryingToTrade().
void TradeSessionImplementation::lock (bool doLock = true) protected
Definition at line 255 of file TradeSession.cpp.
References _this.
void TradeSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 259 of file TradeSession.cpp.
References _this.
TradeSessionImplementation::operator const TradeSession * ()
Definition at line 251 of file TradeSession.cpp.
void TradeSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 290 of file TradeSession.cpp.
References readObjectMember().
bool TradeSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 309 of file TradeSession.cpp.
References acceptedTrade, itemsToTrade, moneyToTrade, tradeTargetPlayer, and verifiedTrade.
Referenced by readObject().
void TradeSessionImplementation::rlock (bool doLock = true) protected
Definition at line 263 of file TradeSession.cpp.
References _this.
void TradeSessionImplementation::runlock (bool doLock = true) protected
Definition at line 279 of file TradeSession.cpp.
References _this.
void TradeSessionImplementation::setAcceptedTrade (bool val)
Definition at line 455 of file TradeSession.cpp.
References acceptedTrade.
Referenced by server::zone::objects::player::sessions::TradeSession::setAcceptedTrade().
void TradeSessionImplementation::setMoneyToTrade (int val)
Definition at line 460 of file TradeSession.cpp.
References moneyToTrade.
Referenced by server::zone::objects::player::sessions::TradeSession::setMoneyToTrade().
void TradeSessionImplementation::setTradeTargetPlayer (unsigned long long val)
Definition at line 465 of file TradeSession.cpp.
References tradeTargetPlayer.
Referenced by server::zone::objects::player::sessions::TradeSession::setTradeTargetPlayer().
void TradeSessionImplementation::setVerifiedTrade (bool val)
Definition at line 470 of file TradeSession.cpp.
References verifiedTrade.
Referenced by server::zone::objects::player::sessions::TradeSession::setVerifiedTrade().
void TradeSessionImplementation::unlock (bool doLock = true) protected
Definition at line 275 of file TradeSession.cpp.
References _this.
void TradeSessionImplementation::wlock (bool doLock = true) protected
Definition at line 267 of file TradeSession.cpp.
References _this.
void TradeSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 271 of file TradeSession.cpp.
References _this.
void TradeSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 339 of file TradeSession.cpp.
References writeObjectMembers().
int TradeSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 346 of file TradeSession.cpp.
References acceptedTrade, itemsToTrade, moneyToTrade, tradeTargetPlayer, and verifiedTrade.
Referenced by writeObject().
Friends And Related Function Documentation
friend class TradeSession friend
Definition at line 188 of file TradeSession.h.
Member Data Documentation
WeakReference<TradeSession*> server::zone::objects::player::sessions::TradeSessionImplementation::_this
Definition at line 154 of file TradeSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
bool server::zone::objects::player::sessions::TradeSessionImplementation::acceptedTrade protected
Definition at line 119 of file TradeSession.h.
Referenced by getAcceptedTrade(), readObjectMember(), setAcceptedTrade(), TradeSessionImplementation(), and writeObjectMembers().
SortedVector<ManagedReference<SceneObject* > > server::zone::objects::player::sessions::TradeSessionImplementation::itemsToTrade protected
Definition at line 115 of file TradeSession.h.
Referenced by addTradeItem(), getItemsToTrade(), getTradeItem(), getTradeSize(), readObjectMember(), TradeSessionImplementation(), and writeObjectMembers().
int server::zone::objects::player::sessions::TradeSessionImplementation::moneyToTrade protected
Definition at line 121 of file TradeSession.h.
Referenced by getMoneyToTrade(), readObjectMember(), setMoneyToTrade(), TradeSessionImplementation(), and writeObjectMembers().
unsigned long long server::zone::objects::player::sessions::TradeSessionImplementation::tradeTargetPlayer protected
Definition at line 113 of file TradeSession.h.
Referenced by getTradeTargetPlayer(), isTryingToTrade(), readObjectMember(), setTradeTargetPlayer(), TradeSessionImplementation(), and writeObjectMembers().
bool server::zone::objects::player::sessions::TradeSessionImplementation::verifiedTrade protected
Definition at line 117 of file TradeSession.h.
Referenced by hasVerifiedTrade(), readObjectMember(), setVerifiedTrade(), TradeSessionImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TradeSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TradeSession.cpp