Core3: DetectorZoneComponent Class Reference
DetectorZoneComponent Class Reference
#include <DetectorZoneComponent.h>
Public Member Functions
void notifyPositionUpdate (SceneObject *sceneObject, QuadTreeEntry *entry)
Public Member Functions inherited from ZoneComponent
virtual void notifyInsertToZone (SceneObject *sceneObject, Zone *zone)
virtual void switchZone (SceneObject *sceneObject, const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, uint64 parentID=0)
virtual void teleport (SceneObject *sceneObject, float newPositionX, float newPositionZ, float newPositionY, uint64 parentID=0)
virtual void notifyRemoveFromZone (SceneObject *sceneObject)
virtual void updateZone (SceneObject *sceneObject, bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *sceneObject, SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
virtual void notifySelfPositionUpdate (SceneObject *sceneObject)
virtual void notifyInsert (SceneObject *sceneObject, QuadTreeEntry *entry)
virtual void notifyDissapear (SceneObject *sceneObject, QuadTreeEntry *entry)
void updateInRangeObjectsOnMount (SceneObject *sceneObject)
virtual void destroyObjectFromWorld (SceneObject *sceneObject, bool sendSelfDestroy)
Additional Inherited Members
Protected Member Functions inherited from ZoneComponent
void insertChildObjectsToZone (SceneObject *sceneObject, Zone *zone)
Detailed Description
Definition at line 17 of file DetectorZoneComponent.h.
Member Function Documentation
void DetectorZoneComponent::notifyPositionUpdate (SceneObject * sceneObject, QuadTreeEntry * entry) virtual
Reimplemented from ZoneComponent.
Definition at line 20 of file DetectorZoneComponent.cpp.
References DetectorDataComponent::canScan(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::isDetector(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::scene::SceneObject::isTangibleObject(), and DetectorDataComponent::updateCooldown().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/DetectorZoneComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/DetectorZoneComponent.cpp