Core3: server::zone::objects::area::areashapes::CircularAreaShapeAdapter Class Reference
server::zone::objects::area::areashapes::CircularAreaShapeAdapter Class Reference
#include <CircularAreaShape.h>
Public Member Functions
CircularAreaShapeAdapter (CircularAreaShape *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setRadius (float r)
float getRadius ()
float getRadius2 ()
bool containsPoint (float x, float y)
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
Public Member Functions inherited from server::zone::objects::area::areashapes::AreaShapeAdapter
AreaShapeAdapter (AreaShape *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setAreaCenter (float x, float y)
bool containsPoint (float x, float y)
float getRadius ()
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
Detailed Description
Definition at line 269 of file CircularAreaShape.h.
Constructor & Destructor Documentation
CircularAreaShapeAdapter::CircularAreaShapeAdapter (CircularAreaShape * impl)
Definition at line 381 of file CircularAreaShape.cpp.
Member Function Documentation
bool CircularAreaShapeAdapter::containsPoint (float x, float y)
Definition at line 450 of file CircularAreaShape.cpp.
Referenced by invokeMethod().
float CircularAreaShapeAdapter::getArea ()
Definition at line 470 of file CircularAreaShape.cpp.
Referenced by invokeMethod().
float CircularAreaShapeAdapter::getRadius ()
Definition at line 442 of file CircularAreaShape.cpp.
Referenced by invokeMethod().
float CircularAreaShapeAdapter::getRadius2 ()
Definition at line 446 of file CircularAreaShape.cpp.
Referenced by invokeMethod().
bool CircularAreaShapeAdapter::intersectsWith (AreaShape * areaShape)
Definition at line 466 of file CircularAreaShape.cpp.
Referenced by invokeMethod().
void CircularAreaShapeAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 384 of file CircularAreaShape.cpp.
References containsPoint(), getArea(), getRadius(), getRadius2(), intersectsWith(), isCircularAreaShape(), isRectangularAreaShape(), isRingAreaShape(), RPC_CONTAINSPOINT__FLOAT_FLOAT_, RPC_GETAREA__, RPC_GETRADIUS2__, RPC_GETRADIUS__, RPC_INTERSECTSWITH__AREASHAPE_, RPC_ISCIRCULARAREASHAPE__, RPC_ISRECTANGULARAREASHAPE__, RPC_ISRINGAREASHAPE__, RPC_SETRADIUS__FLOAT_, and setRadius().
bool CircularAreaShapeAdapter::isCircularAreaShape ()
Definition at line 454 of file CircularAreaShape.cpp.
Referenced by invokeMethod().
bool CircularAreaShapeAdapter::isRectangularAreaShape ()
Definition at line 458 of file CircularAreaShape.cpp.
Referenced by invokeMethod().
bool CircularAreaShapeAdapter::isRingAreaShape ()
Definition at line 462 of file CircularAreaShape.cpp.
Referenced by invokeMethod().
void CircularAreaShapeAdapter::setRadius (float r)
Definition at line 438 of file CircularAreaShape.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/CircularAreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/CircularAreaShape.cpp