Core3: LuaConversationScreen Class Reference
LuaConversationScreen Class Reference
#include <LuaConversationScreen.h>
Public Member Functions
LuaConversationScreen (lua_State *L)
~LuaConversationScreen ()
int _setObject (lua_State *L)
int getOptionText (lua_State *L)
int getOptionLink (lua_State *L)
int getOptionCount (lua_State *L)
int sendTo (lua_State *L)
int getScreenID (lua_State *L)
int cloneScreen (lua_State *L)
int addOption (lua_State *L)
int removeAllOptions (lua_State *L)
int setDialogTextStringId (lua_State *L)
int setDialogTextTT (lua_State *L)
int setDialogTextTO (lua_State *L)
int setDialogTextTU (lua_State *L)
int setDialogTextDF (lua_State *L)
int setDialogTextDI (lua_State *L)
int setCustomDialogText (lua_State *L)
Static Public Attributes
static const char className [] = "LuaConversationScreen"
static Luna
< LuaConversationScreen >
::RegType Register []
Static Private Member Functions
static void setDialogText (StringIdParameter *param, lua_State *L)
Private Attributes
ConversationScreen * realObject
Detailed Description
Definition at line 15 of file LuaConversationScreen.h.
Constructor & Destructor Documentation
LuaConversationScreen::LuaConversationScreen (lua_State * L)
Definition at line 32 of file LuaConversationScreen.cpp.
References realObject.
LuaConversationScreen::~LuaConversationScreen ()
Definition at line 36 of file LuaConversationScreen.cpp.
Member Function Documentation
int LuaConversationScreen::_setObject (lua_State * L)
Definition at line 39 of file LuaConversationScreen.cpp.
References realObject.
int LuaConversationScreen::addOption (lua_State * L)
Definition at line 117 of file LuaConversationScreen.cpp.
References server::zone::templates::mobile::ConversationScreen::addOption(), and realObject.
int LuaConversationScreen::cloneScreen (lua_State * L)
Definition at line 111 of file LuaConversationScreen.cpp.
References server::zone::templates::mobile::ConversationScreen::cloneScreen(), and realObject.
int LuaConversationScreen::getOptionCount (lua_State * L)
Definition at line 79 of file LuaConversationScreen.cpp.
References server::zone::templates::mobile::ConversationScreen::getOptionCount(), and realObject.
int LuaConversationScreen::getOptionLink (lua_State * L)
Definition at line 62 of file LuaConversationScreen.cpp.
References server::zone::templates::mobile::ConversationScreen::getOptionLink(), and realObject.
int LuaConversationScreen::getOptionText (lua_State * L)
Definition at line 45 of file LuaConversationScreen.cpp.
References server::zone::templates::mobile::ConversationScreen::getOptionText(), and realObject.
int LuaConversationScreen::getScreenID (lua_State * L)
Definition at line 98 of file LuaConversationScreen.cpp.
References server::zone::templates::mobile::ConversationScreen::getScreenID(), and realObject.
int LuaConversationScreen::removeAllOptions (lua_State * L)
Definition at line 128 of file LuaConversationScreen.cpp.
References realObject, and server::zone::templates::mobile::ConversationScreen::removeAllOptions().
int LuaConversationScreen::sendTo (lua_State * L)
Definition at line 87 of file LuaConversationScreen.cpp.
References realObject, and server::zone::templates::mobile::ConversationScreen::sendTo().
int LuaConversationScreen::setCustomDialogText (lua_State * L)
Definition at line 203 of file LuaConversationScreen.cpp.
References realObject, and server::zone::templates::mobile::ConversationScreen::setCustomDialogText().
void LuaConversationScreen::setDialogText (StringIdParameter * param, lua_State * L) static private
Definition at line 146 of file LuaConversationScreen.cpp.
References server::zone::objects::scene::variables::StringIdParameter::set().
Referenced by setDialogTextTO(), setDialogTextTT(), and setDialogTextTU().
int LuaConversationScreen::setDialogTextDF (lua_State * L)
Definition at line 195 of file LuaConversationScreen.cpp.
References realObject, and server::zone::templates::mobile::ConversationScreen::setDialogTextDF().
int LuaConversationScreen::setDialogTextDI (lua_State * L)
Definition at line 211 of file LuaConversationScreen.cpp.
References realObject, and server::zone::templates::mobile::ConversationScreen::setDialogTextDI().
int LuaConversationScreen::setDialogTextStringId (lua_State * L)
Definition at line 136 of file LuaConversationScreen.cpp.
References realObject, and server::zone::templates::mobile::ConversationScreen::setDialogText().
int LuaConversationScreen::setDialogTextTO (lua_State * L)
Definition at line 179 of file LuaConversationScreen.cpp.
References server::zone::templates::mobile::ConversationScreen::getDialogText(), server::chat::StringIdChatParameter::getTO(), realObject, and setDialogText().
int LuaConversationScreen::setDialogTextTT (lua_State * L)
Definition at line 171 of file LuaConversationScreen.cpp.
References server::zone::templates::mobile::ConversationScreen::getDialogText(), server::chat::StringIdChatParameter::getTT(), realObject, and setDialogText().
int LuaConversationScreen::setDialogTextTU (lua_State * L)
Definition at line 187 of file LuaConversationScreen.cpp.
References server::zone::templates::mobile::ConversationScreen::getDialogText(), server::chat::StringIdChatParameter::getTU(), realObject, and setDialogText().
Member Data Documentation
const char LuaConversationScreen::className = "LuaConversationScreen" static
Definition at line 18 of file LuaConversationScreen.h.
ConversationScreen* LuaConversationScreen::realObject private
Definition at line 45 of file LuaConversationScreen.h.
Referenced by _setObject(), addOption(), cloneScreen(), getOptionCount(), getOptionLink(), getOptionText(), getScreenID(), LuaConversationScreen(), removeAllOptions(), sendTo(), setCustomDialogText(), setDialogTextDF(), setDialogTextDI(), setDialogTextStringId(), setDialogTextTO(), setDialogTextTT(), and setDialogTextTU().
Luna< LuaConversationScreen >::RegType LuaConversationScreen::Register static
Initial value:
= {
                { "_setObject", &LuaConversationScreen::_setObject },
                { "getOptionText", &LuaConversationScreen::getOptionText},
                { "getOptionLink", &LuaConversationScreen::getOptionLink},
                { "getOptionCount", &LuaConversationScreen::getOptionCount},
                { "sendTo", &LuaConversationScreen::sendTo},
                { "getScreenID", &LuaConversationScreen::getScreenID},
                { "cloneScreen", &LuaConversationScreen::cloneScreen},
                { "addOption", &LuaConversationScreen::addOption},
                { "removeAllOptions", &LuaConversationScreen::removeAllOptions},
                { "setDialogTextStringId", &LuaConversationScreen::setDialogTextStringId},
                { "setDialogTextTT", &LuaConversationScreen::setDialogTextTT},
                { "setDialogTextTO", &LuaConversationScreen::setDialogTextTO},
                { "setDialogTextTU", &LuaConversationScreen::setDialogTextTU},
                { "setDialogTextDF", &LuaConversationScreen::setDialogTextDF},
                { "setDialogTextDI", &LuaConversationScreen::setDialogTextDI},
                { "setCustomDialogText", &LuaConversationScreen::setCustomDialogText},
                { 0, 0 }
}
Definition at line 19 of file LuaConversationScreen.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/mobile/LuaConversationScreen.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/mobile/LuaConversationScreen.cpp