Core3: server::zone::managers::crafting::CraftingManager Class Reference
server::zone::managers::crafting::CraftingManager Class Reference
#include <CraftingManager.h>
Public Member Functions
CraftingManager ()
void initialize ()
void awardSchematicGroup (PlayerObject *playerObject, Vector< String > &schematicgroups, bool updateClient=false)
void removeSchematicGroup (PlayerObject *playerObject, Vector< String > &schematicgroups, bool updateClient=false)
DraftSchematic * getSchematic (unsigned int schematicID)
void sendDraftSlotsTo (CreatureObject *player, unsigned int schematicID)
void sendResourceWeightsTo (CreatureObject *player, unsigned int schematicID)
int calculateAssemblySuccess (CreatureObject *player, DraftSchematic *draftSchematic, float effectiveness)
void experimentRow (ManufactureSchematic *schematic, CraftingValues *craftingValues, int rowEffected, int pointsAttempted, float failure, int experimentationResult)
int calculateExperimentationFailureRate (CreatureObject *player, ManufactureSchematic *manufactureSchematic, int pointsUsed)
int calculateExperimentationSuccess (CreatureObject *player, DraftSchematic *draftSchematic, float effectiveness)
String generateSerial ()
String checkBioSkillMods (const String &property)
void setInitialCraftingValues (TangibleObject *prototype, ManufactureSchematic *manufactureSchematic, int assemblySuccess)
bool allowManufactureSchematic (ManufactureSchematic *manufactureSchematic)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::manager::ZoneManager
ZoneManager (const String &name)
void setZoneProcessor (ZoneProcessServer *server)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const short RESOURCECOMBINE = 0x00
static const short LINEARCOMBINE = 0x01
static const short PERCENTAGECOMBINE = 0x02
static const short BITSETCOMBINE = 0x03
static const short OVERRIDECOMBINE = 0x04
static const short CR = 1
static const short CD = 2
static const short DR = 3
static const short HR = 4
static const short FL = 5
static const short MA = 6
static const short PE = 7
static const short OQ = 8
static const short SR = 9
static const short UT = 10
static const short AMAZINGSUCCESS = 0
static const short GREATSUCCESS = 1
static const short GOODSUCCESS = 2
static const short MODERATESUCCESS = 3
static const short SUCCESS = 4
static const short MARGINALSUCCESS = 5
static const short OK = 6
static const short BARELYSUCCESSFUL = 7
static const short CRITICALFAILURE = 8
static const int RESOURCE_LAB = 0x00
static const int GENETIC_LAB = 0x01
Protected Member Functions
CraftingManager (DummyConstructorParameter *param)
virtual ~CraftingManager ()
Protected Member Functions inherited from server::zone::manager::ZoneManager
ZoneManager (DummyConstructorParameter *param)
virtual ~ZoneManager ()
Friends
class CraftingManagerHelper
Detailed Description
Definition at line 117 of file CraftingManager.h.
Constructor & Destructor Documentation
CraftingManager::CraftingManager ()
Definition at line 25 of file CraftingManager.cpp.
References server::zone::managers::crafting::CraftingManagerImplementation::_setStub().
CraftingManager::CraftingManager (DummyConstructorParameter * param) protected
Definition at line 32 of file CraftingManager.cpp.
CraftingManager::~CraftingManager () protected virtual
Definition at line 36 of file CraftingManager.cpp.
Member Function Documentation
DistributedObjectServant * CraftingManager::_getImplementation ()
Definition at line 230 of file CraftingManager.cpp.
Referenced by allowManufactureSchematic(), awardSchematicGroup(), calculateAssemblySuccess(), calculateExperimentationFailureRate(), calculateExperimentationSuccess(), checkBioSkillMods(), experimentRow(), generateSerial(), getSchematic(), initialize(), removeSchematicGroup(), sendDraftSlotsTo(), sendResourceWeightsTo(), and setInitialCraftingValues().
DistributedObjectServant * CraftingManager::_getImplementationForRead ()
Definition at line 236 of file CraftingManager.cpp.
void CraftingManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 240 of file CraftingManager.cpp.
bool CraftingManager::allowManufactureSchematic (ManufactureSchematic * manufactureSchematic)
Definition at line 216 of file CraftingManager.cpp.
References _getImplementation(), server::zone::managers::crafting::CraftingManagerImplementation::allowManufactureSchematic(), and RPC_ALLOWMANUFACTURESCHEMATIC__MANUFACTURESCHEMATIC_.
void CraftingManager::awardSchematicGroup (PlayerObject * playerObject, Vector< String > & schematicgroups, bool updateClient = false)
Definition at line 50 of file CraftingManager.cpp.
References _getImplementation(), and server::zone::managers::crafting::CraftingManagerImplementation::awardSchematicGroup().
int CraftingManager::calculateAssemblySuccess (CreatureObject * player, DraftSchematic * draftSchematic, float effectiveness)
Definition at line 112 of file CraftingManager.cpp.
References _getImplementation(), server::zone::managers::crafting::CraftingManagerImplementation::calculateAssemblySuccess(), and RPC_CALCULATEASSEMBLYSUCCESS__CREATUREOBJECT_DRAFTSCHEMATIC_FLOAT_.
int CraftingManager::calculateExperimentationFailureRate (CreatureObject * player, ManufactureSchematic * manufactureSchematic, int pointsUsed)
Definition at line 137 of file CraftingManager.cpp.
References _getImplementation(), server::zone::managers::crafting::CraftingManagerImplementation::calculateExperimentationFailureRate(), and RPC_CALCULATEEXPERIMENTATIONFAILURERATE__CREATUREOBJECT_MANUFACTURESCHEMATIC_INT_.
int CraftingManager::calculateExperimentationSuccess (CreatureObject * player, DraftSchematic * draftSchematic, float effectiveness)
Definition at line 153 of file CraftingManager.cpp.
References _getImplementation(), server::zone::managers::crafting::CraftingManagerImplementation::calculateExperimentationSuccess(), and RPC_CALCULATEEXPERIMENTATIONSUCCESS__CREATUREOBJECT_DRAFTSCHEMATIC_FLOAT_.
String CraftingManager::checkBioSkillMods (const String & property)
Definition at line 184 of file CraftingManager.cpp.
References _getImplementation(), server::zone::managers::crafting::CraftingManagerImplementation::checkBioSkillMods(), and RPC_CHECKBIOSKILLMODS__STRING_.
void CraftingManager::experimentRow (ManufactureSchematic * schematic, CraftingValues * craftingValues, int rowEffected, int pointsAttempted, float failure, int experimentationResult)
Definition at line 128 of file CraftingManager.cpp.
References _getImplementation(), and server::zone::managers::crafting::CraftingManagerImplementation::experimentRow().
String CraftingManager::generateSerial ()
Definition at line 169 of file CraftingManager.cpp.
References _getImplementation(), server::zone::managers::crafting::CraftingManagerImplementation::generateSerial(), and RPC_GENERATESERIAL__.
Referenced by server::zone::managers::creature::DnaManager::generateSample().
DraftSchematic * CraftingManager::getSchematic (unsigned int schematicID)
Definition at line 68 of file CraftingManager.cpp.
References _getImplementation(), server::zone::managers::crafting::CraftingManagerImplementation::getSchematic(), and RPC_GETSCHEMATIC__INT_.
void CraftingManager::initialize ()
Definition at line 41 of file CraftingManager.cpp.
References _getImplementation(), and server::zone::managers::crafting::CraftingManagerImplementation::initialize().
void CraftingManager::removeSchematicGroup (PlayerObject * playerObject, Vector< String > & schematicgroups, bool updateClient = false)
Definition at line 59 of file CraftingManager.cpp.
References _getImplementation(), and server::zone::managers::crafting::CraftingManagerImplementation::removeSchematicGroup().
void CraftingManager::sendDraftSlotsTo (CreatureObject * player, unsigned int schematicID)
Definition at line 82 of file CraftingManager.cpp.
References _getImplementation(), RPC_SENDDRAFTSLOTSTO__CREATUREOBJECT_INT_, and server::zone::managers::crafting::CraftingManagerImplementation::sendDraftSlotsTo().
void CraftingManager::sendResourceWeightsTo (CreatureObject * player, unsigned int schematicID)
Definition at line 97 of file CraftingManager.cpp.
References _getImplementation(), RPC_SENDRESOURCEWEIGHTSTO__CREATUREOBJECT_INT_, and server::zone::managers::crafting::CraftingManagerImplementation::sendResourceWeightsTo().
void CraftingManager::setInitialCraftingValues (TangibleObject * prototype, ManufactureSchematic * manufactureSchematic, int assemblySuccess)
Definition at line 200 of file CraftingManager.cpp.
References _getImplementation(), RPC_SETINITIALCRAFTINGVALUES__TANGIBLEOBJECT_MANUFACTURESCHEMATIC_INT_, and server::zone::managers::crafting::CraftingManagerImplementation::setInitialCraftingValues().
Friends And Related Function Documentation
friend class CraftingManagerHelper friend
Definition at line 211 of file CraftingManager.h.
Member Data Documentation
const short server::zone::managers::crafting::CraftingManager::AMAZINGSUCCESS = 0 static
Definition at line 149 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::SharedLabratory::calculateAssemblyValueModifier(), and server::zone::managers::crafting::labratories::SharedLabratory::calculateExperimentationValueModifier().
const short server::zone::managers::crafting::CraftingManager::BARELYSUCCESSFUL = 7 static
Definition at line 163 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::SharedLabratory::calculateExperimentationValueModifier().
const short server::zone::managers::crafting::CraftingManager::BITSETCOMBINE = 0x03 static
Definition at line 125 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats().
const short server::zone::managers::crafting::CraftingManager::CD = 2 static
Definition at line 131 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManager::CR = 1 static
Definition at line 129 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManager::CRITICALFAILURE = 8 static
Definition at line 165 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::SharedLabratory::calculateExperimentationValueModifier().
const short server::zone::managers::crafting::CraftingManager::DR = 3 static
Definition at line 133 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManager::FL = 5 static
Definition at line 137 of file CraftingManager.h.
const int server::zone::managers::crafting::CraftingManager::GENETIC_LAB = 0x01 static
Definition at line 169 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManager::GOODSUCCESS = 2 static
Definition at line 153 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::SharedLabratory::calculateExperimentationValueModifier().
const short server::zone::managers::crafting::CraftingManager::GREATSUCCESS = 1 static
Definition at line 151 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::SharedLabratory::calculateExperimentationValueModifier().
const short server::zone::managers::crafting::CraftingManager::HR = 4 static
Definition at line 135 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManager::LINEARCOMBINE = 0x01 static
Definition at line 121 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), and server::zone::managers::crafting::labratories::GeneticLabratory::setInitialCraftingValues().
const short server::zone::managers::crafting::CraftingManager::MA = 6 static
Definition at line 139 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManager::MARGINALSUCCESS = 5 static
Definition at line 159 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::SharedLabratory::calculateExperimentationValueModifier().
const short server::zone::managers::crafting::CraftingManager::MODERATESUCCESS = 3 static
Definition at line 155 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::SharedLabratory::calculateExperimentationValueModifier().
const short server::zone::managers::crafting::CraftingManager::OK = 6 static
Definition at line 161 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::SharedLabratory::calculateExperimentationValueModifier().
const short server::zone::managers::crafting::CraftingManager::OQ = 8 static
Definition at line 143 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManager::OVERRIDECOMBINE = 0x04 static
Definition at line 127 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), server::zone::managers::crafting::labratories::ResourceLabratory::setInitialCraftingValues(), and server::zone::managers::crafting::labratories::GeneticLabratory::setInitialCraftingValues().
const short server::zone::managers::crafting::CraftingManager::PE = 7 static
Definition at line 141 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManager::PERCENTAGECOMBINE = 0x02 static
Definition at line 123 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats().
const int server::zone::managers::crafting::CraftingManager::RESOURCE_LAB = 0x00 static
Definition at line 167 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManager::RESOURCECOMBINE = 0x00 static
Definition at line 119 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManager::SR = 9 static
Definition at line 145 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManager::SUCCESS = 4 static
Definition at line 157 of file CraftingManager.h.
Referenced by server::zone::managers::crafting::labratories::SharedLabratory::calculateExperimentationValueModifier().
const short server::zone::managers::crafting::CraftingManager::UT = 10 static
Definition at line 147 of file CraftingManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/CraftingManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/CraftingManager.cpp