Core3: server::zone::managers::radial::RadialManagerAdapter Class Reference
server::zone::managers::radial::RadialManagerAdapter Class Reference
#include <RadialManager.h>
Public Member Functions
RadialManagerAdapter (RadialManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void handleObjectMenuSelect (CreatureObject *player, byte selectID, unsigned long long objectID)
void handleObjectMenuRequest (CreatureObject *player, ObjectMenuResponse *defaultMenuResponse, unsigned long long objectID)
Detailed Description
Definition at line 157 of file RadialManager.h.
Constructor & Destructor Documentation
RadialManagerAdapter::RadialManagerAdapter (RadialManager * impl)
Definition at line 221 of file RadialManager.cpp.
Member Function Documentation
void RadialManagerAdapter::handleObjectMenuRequest (CreatureObject * player, ObjectMenuResponse * defaultMenuResponse, unsigned long long objectID)
Definition at line 247 of file RadialManager.cpp.
Referenced by invokeMethod().
void RadialManagerAdapter::handleObjectMenuSelect (CreatureObject * player, byte selectID, unsigned long long objectID)
Definition at line 243 of file RadialManager.cpp.
Referenced by invokeMethod().
void RadialManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 224 of file RadialManager.cpp.
References handleObjectMenuRequest(), handleObjectMenuSelect(), RPC_HANDLEOBJECTMENUREQUEST__CREATUREOBJECT_OBJECTMENURESPONSE_LONG_, and RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_LONG_.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/radial/RadialManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/radial/RadialManager.cpp