Core3: ObjectController Class Reference
ObjectController Class Reference
#include <ObjectController.h>
Public Member Functions
ObjectController (Zone *zn)
void handleObjectController (SceneObject *object, uint32 header1, uint32 header2, Message *pack)
void handleSpatialChat (SceneObject *object, Message *pack)
bool doCommand (uint32 crc, const UnicodeString &arguments)
void doSayCommand (const UnicodeString &msg)
void doEnqueueCommand (uint32 command, const UnicodeString &arguments)
void setZone (Zone *zon)
Private Attributes
Zone * zone
Detailed Description
Definition at line 16 of file ObjectController.h.
Constructor & Destructor Documentation
ObjectController::ObjectController (Zone * zn)
Definition at line 15 of file ObjectController.cpp.
References zone.
Member Function Documentation
bool ObjectController::doCommand (uint32 crc, const UnicodeString & arguments)
Definition at line 44 of file ObjectController.cpp.
References doEnqueueCommand(), and doSayCommand().
Referenced by Zone::doCommand().
void ObjectController::doEnqueueCommand (uint32 command, const UnicodeString & arguments)
Definition at line 59 of file ObjectController.cpp.
References CreatureObject::getNewActionCount(), SceneObject::getObjectID(), Zone::getSelfPlayer(), and zone.
Referenced by doCommand().
void ObjectController::doSayCommand (const UnicodeString & msg)
Definition at line 74 of file ObjectController.cpp.
References CreatureObject::getNewActionCount(), SceneObject::getObjectID(), Zone::getSelfPlayer(), and zone.
Referenced by doCommand().
void ObjectController::handleObjectController (SceneObject * object, uint32 header1, uint32 header2, Message * pack)
Definition at line 20 of file ObjectController.cpp.
References handleSpatialChat().
Referenced by ZonePacketHandler::handleObjectControllerMessage().
void ObjectController::handleSpatialChat (SceneObject * object, Message * pack)
Definition at line 31 of file ObjectController.cpp.
References Zone::getObject(), and zone.
Referenced by handleObjectController().
void ObjectController::setZone (Zone * zon) inline
Definition at line 30 of file ObjectController.h.
References zone.
Member Data Documentation
Zone* ObjectController::zone private
Definition at line 17 of file ObjectController.h.
Referenced by doEnqueueCommand(), doSayCommand(), handleSpatialChat(), ObjectController(), and setZone().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/zone/managers/objectcontroller/ObjectController.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/zone/managers/objectcontroller/ObjectController.cpp