Core3: server::zone::managers::minigames::FishingManager Class Reference
server::zone::managers::minigames::FishingManager Class Reference
#include <FishingManager.h>
Public Member Functions
FishingManager ()
void initializeBaitStatus ()
void initializeProperty ()
void initializeAction ()
void initializeState ()
void initializeFishType ()
void initializeFishLength ()
void initializeLoot ()
void initializeColor ()
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void checkFishingOnPositionUpdate (CreatureObject *player)
int notifyCloseContainer (CreatureObject *player, SceneObject *container)
int checkLocation (CreatureObject *player, int quality, float &x, float &y, float &z)
int startFishing (CreatureObject *player)
void stopFishing (CreatureObject *player, unsigned int boxID, bool rem)
void fishingStep (CreatureObject *player)
void success (CreatureObject *player, int fish, SceneObject *marker, unsigned int boxID)
String getTime ()
void sendReward (CreatureObject *player, SceneObject *marker, SceneObject *loot)
unsigned int createWindow (CreatureObject *player, unsigned int boxID)
void closeMenu (CreatureObject *player, unsigned int boxID)
int vegetation (SceneObject *marker)
int density (SceneObject *marker)
int getFish (CreatureObject *player)
int getNextAction (CreatureObject *player)
void setNextAction (CreatureObject *player, int next)
FishingPoleObject * getPole (CreatureObject *player)
FishingBaitObject * getBait (CreatureObject *player)
unsigned int getFishBoxID (CreatureObject *player)
void setFishBoxID (CreatureObject *player, unsigned int boxID)
int getFishingState (CreatureObject *player)
void setFishingState (CreatureObject *player, int state)
SceneObject * getFishMarker (CreatureObject *player)
void setFishMarker (CreatureObject *player, SceneObject *marker)
void freeBait (CreatureObject *player)
void fishingProceed (CreatureObject *player, int nextAction, SceneObject *marker, int fish, unsigned int boxID, int newstate, bool notifyClient, String &moodString)
void mishapEvent (const String &text, CreatureObject *player, unsigned int boxID, bool losebait, String &moodString)
bool loseBait (CreatureObject *player)
void animate (CreatureObject *player, int nextAction)
SceneObject * createMarker (float x, float y, float z, Zone *zone)
void createSplash (float x, float y, float z, Zone *zone, CreatureObject *player)
bool checkUpdateMarker (CreatureObject *player, float &x, float &y, float &z)
bool isPlaying (CreatureObject *player)
SceneObject * updateMarker (CreatureObject *player, SceneObject *marker, bool notifyPlayer)
void removeMarker (CreatureObject *player, SceneObject *container)
void removeSplash (SceneObject *splash)
void createFishingSplashEvent (CreatureObject *player, SceneObject *splash)
void createFishingSession (CreatureObject *player, FishingEvent *event, SceneObject *marker, int nextAction, int fish, unsigned int boxID, int fishingState, String &mood)
FishingEvent * createFishingEvent (CreatureObject *player, int state)
void stopFishingEvent (CreatureObject *player)
FishingEvent * getFishingEvent (CreatureObject *player)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int NOTFISHING = 0
static const int WAITING = 1
static const int SNAGGED = 2
static const int NIBBLE = 3
static const int BITE = 4
static const int CATCH = 5
static const int REELING = 6
static const int REELGAME = 7
static const int BLACKFISH = 0
static const int BLOWFISH = 1
static const int BLUEFISH = 2
static const int FAA = 3
static const int LAA = 4
static const int RAY = 5
static const int STRIPED = 6
static const int FRESH = 0
static const int SOGGY = 6
static const int MUSH = 10
static const int DONOTHING = 0
static const int TUGUP = 1
static const int TUGRIGHT = 2
static const int TUGLEFT = 3
static const int REEL = 4
static const int STOPFISHING = 5
static const int NOEVENT = 0
static const int PROCEED = 17
static const int MISHAP = 45
Protected Member Functions
FishingManager (DummyConstructorParameter *param)
virtual ~FishingManager ()
Friends
class FishingManagerHelper
Detailed Description
Definition at line 159 of file FishingManager.h.
Constructor & Destructor Documentation
FishingManager::FishingManager ()
Definition at line 31 of file FishingManager.cpp.
References server::zone::managers::minigames::FishingManagerImplementation::_setStub().
FishingManager::FishingManager (DummyConstructorParameter * param) protected
Definition at line 38 of file FishingManager.cpp.
FishingManager::~FishingManager () protected virtual
Definition at line 42 of file FishingManager.cpp.
Member Function Documentation
DistributedObjectServant * FishingManager::_getImplementation ()
Definition at line 755 of file FishingManager.cpp.
Referenced by animate(), checkFishingOnPositionUpdate(), checkLocation(), checkUpdateMarker(), closeMenu(), createFishingEvent(), createFishingSession(), createFishingSplashEvent(), createMarker(), createSplash(), createWindow(), density(), fishingProceed(), fishingStep(), freeBait(), getBait(), getFish(), getFishBoxID(), getFishingEvent(), getFishingState(), getFishMarker(), getNextAction(), getPole(), getTime(), initializeAction(), initializeBaitStatus(), initializeColor(), initializeFishLength(), initializeFishType(), initializeLoot(), initializeProperty(), initializeState(), isPlaying(), loseBait(), mishapEvent(), notifyCloseContainer(), notifyObserverEvent(), removeMarker(), removeSplash(), sendReward(), setFishBoxID(), setFishingState(), setFishMarker(), setNextAction(), startFishing(), stopFishing(), stopFishingEvent(), success(), updateMarker(), and vegetation().
DistributedObjectServant * FishingManager::_getImplementationForRead ()
Definition at line 761 of file FishingManager.cpp.
void FishingManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 765 of file FishingManager.cpp.
void FishingManager::animate (CreatureObject * player, int nextAction)
Does Player Animations for different fishing actions animate switches through nextAction and calls appropriate Animations
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to doAnimation()
nextAction index used to decide which animation to play
Definition at line 581 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::animate(), and RPC_ANIMATE__CREATUREOBJECT_INT_.
void FishingManager::checkFishingOnPositionUpdate (CreatureObject * player)
Checks for Player movement checkFishingOnPositionUpdate is called from notify(SceneObject) by the observer pattern The method locks the manager since it is a new entry point into the manager Based on the Fishing State and the position change, fishing might be stopped if the Player goes in too deep (starts swimming) or moves too far from the marker for the line or if the Player moves within 2.0 distance of the marker, attempts to reel in either succeeding or stopping fishing because no fish was caught yet.
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject to check movement for
Definition at line 168 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::checkFishingOnPositionUpdate(), and RPC_CHECKFISHINGONPOSITIONUPDATE__CREATUREOBJECT_.
int FishingManager::checkLocation (CreatureObject * player, int quality, float & x, float & y, float & z)
check location of Player and return the marker position checkLocation gets the PositionX/Y/Z from Player computing new coordinates based on quality of the fishing pole
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject used for coordinate calculation
quality Crafted Quality of the Fishing Pole
x x-Coordinate to be filled with marker position
y y-Coordinate to be filled with marker position
z z-Coordinate to be filled with marker position
Returns
{ 0: everything worked, 1: Exception case, 3: No Water, 4: Water under terrain } { once actually craftable the line range calculation probably needs to be adjusted to affect the outcome less }
Definition at line 197 of file FishingManager.cpp.
References _getImplementation(), and server::zone::managers::minigames::FishingManagerImplementation::checkLocation().
bool FishingManager::checkUpdateMarker (CreatureObject * player, float & x, float & y, float & z)
Checks whether the fish has beached checkUpdateMarker is called by updateMarker to see if the new position is in Water
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to check
x X-Coordinate of the splash
y Y-Coordinate of the splash
z Z-Coordinate of the splash
Returns
{ true if beached, false if water }
Definition at line 631 of file FishingManager.cpp.
References _getImplementation(), and server::zone::managers::minigames::FishingManagerImplementation::checkUpdateMarker().
void FishingManager::closeMenu (CreatureObject * player, unsigned int boxID)
Closes the FishingMenu closeMenu checks for valid boxID and Player and sends the close message, removing the sui box from the player
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to close window
boxID Fishing window being closed
Definition at line 313 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::closeMenu(), and RPC_CLOSEMENU__CREATUREOBJECT_INT_.
FishingEvent * FishingManager::createFishingEvent (CreatureObject * player, int state)
Creates a Fishing Event schedule 7000 createFishingEvent creates a new Fishing Event given the State
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to create Fishing Event
zoneServer ZoneServer used
state FishingState the player is in
Definition at line 723 of file FishingManager.cpp.
References _getImplementation(), and server::zone::managers::minigames::FishingManagerImplementation::createFishingEvent().
void FishingManager::createFishingSession (CreatureObject * player, FishingEvent * event, SceneObject * marker, int nextAction, int fish, unsigned int boxID, int fishingState, String & mood)
Creates a FishingSession createFishingSession creates a new FishingSession given the player, event, nextAction, the marker, the FishType as sum, the fishing window, the State and the mood and puts it into VectorMap sessions
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to create FishingSession
event Current FishingEvent
nextAction Action to be executed
marker The fish marker being used
sum Integer indicating fish
boxID Fishing window to later close
state FishingState the player is in
moodString String taken from player before fishing to return to after fishing
Definition at line 714 of file FishingManager.cpp.
References _getImplementation(), and server::zone::managers::minigames::FishingManagerImplementation::createFishingSession().
void FishingManager::createFishingSplashEvent (CreatureObject * player, SceneObject * splash)
Creates a Splash Event schedule 1000 createFishingSplashEvent creates a new FishingSplashEvent for the given SceneObject and schedules it to 1000 so the Splash is removed after 1 second
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to create Splash Event
zoneServer ZoneServer used
splash SceneObject to remove later
Definition at line 699 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::createFishingSplashEvent(), and RPC_CREATEFISHINGSPLASHEVENT__CREATUREOBJECT_SCENEOBJECT_.
SceneObject * FishingManager::createMarker (float x, float y, float z, Zone * zone)
Creates a marker object at the given coordinates createMarker creates a SceneObject for tango/fishing/shared_marker.iff and inserts it at given coordinates
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
x X-Coordinate of new marker
y Y-Coordinate of new marker
z Z-Coordinate of new marker
zone Zone used to create the marker in
Returns
{ SceneObject of new marker }
Definition at line 596 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::createMarker(), and RPC_CREATEMARKER__FLOAT_FLOAT_FLOAT_ZONE_.
void FishingManager::createSplash (float x, float y, float z, Zone * zone, CreatureObject * player)
Creates a small Splash at the given coordinates createSplash creates a SceneObject for tango/fishing/shared_splash.iff and inserts it at given coordinates a FishingSplashEvent is created so that the splash is removed in due time
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
x X-Coordinate of the splash
y Y-Coordinate of the splash
z Z-Coordinate of the splash
zone Zone used to create the splash in
player CreatureObject for which to create fishing splash event
Definition at line 613 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::createSplash(), and RPC_CREATESPLASH__FLOAT_FLOAT_FLOAT_ZONE_CREATUREOBJECT_.
unsigned int FishingManager::createWindow (CreatureObject * player, unsigned int boxID)
Creates a Fishing Window createWindow closes the old menu and creates a new one based on vegetation, density, freshness etc
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to open a new window
boxID Old fishing window to close
Returns
{ -1: problem, otherwise uint32 boxID of new window }
Definition at line 298 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::createWindow(), and RPC_CREATEWINDOW__CREATUREOBJECT_INT_.
int FishingManager::density (SceneObject * marker)
Calculates density based on current Position density returns a value 0-5 based on abs(PositionY/100) rounded up { Actually make density a property of a body of water }
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
marker Fishing marker to get coordinates of to calculate the fish density
Returns
{ 0-5 }
Definition at line 342 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::density(), and RPC_DENSITY__SCENEOBJECT_.
void FishingManager::fishingProceed (CreatureObject * player, int nextAction, SceneObject * marker, int fish, unsigned int boxID, int newstate, bool notifyClient, String & moodString)
fishingProceed notifies the Player and create the new Event fishingProceed is called from FishingStep unless fishing has ended It will notify the Player through fly text and system messages of what is going on
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to proceed fishing
nextAction action taken by player
marker Fish marker used to create splash at
fish Integer carried along to know what fish is currently biting
boxID window to close when creating new window
newstate The new state for the player to know from where and where to the transition is taking place
notifyClient If true the marker was updated and the player will be informed that the fish was brought closer
moodString String taken from player before fishing to return to after fishing
Definition at line 528 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::fishingProceed(), and RPC_FISHINGPROCEED__CREATUREOBJECT_INT_SCENEOBJECT_INT_INT_INT_BOOL_STRING_.
void FishingManager::fishingStep (CreatureObject * player)
fishingStep gets called from FishingEvent::run() fishingStep closes the menu, gets the current state and computes two random numbers If the player hasnt reached CATCH state yet and the bait is MUSH, it will be tossed and fishing ends
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject which is currently fishing
Definition at line 236 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::fishingStep(), and RPC_FISHINGSTEP__CREATUREOBJECT_.
void FishingManager::freeBait (CreatureObject * player)
Hands out free Bait freeBait is used for debugging: in case the Pole is empty, a bait will be created and added to the pole { Remove this and it's call at FishCommand when testing is complete }
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to put free bait into the fishing pole
Definition at line 514 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::freeBait(), and RPC_FREEBAIT__CREATUREOBJECT_.
FishingBaitObject * FishingManager::getBait (CreatureObject * player)
Gets Bait from Pole getBait gets the pole from the Player, looks into the Container and if there's an object in it returns it
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get fishing bait
Returns
{ FishingBaitObject or NULL }
Definition at line 413 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::getBait(), and RPC_GETBAIT__CREATUREOBJECT_.
int FishingManager::getFish (CreatureObject * player)
Calculates Fish biting getFish calculates a random number 0-99 and, if it's a fish (<94) calculates what kind of fish based on pole quality, vegetation penalty, fish density bonus, bait status, and a random number
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to randomize fish
Returns
{ 0-6: Fish, 94-99: Misc Item }
Definition at line 356 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::getFish(), and RPC_GETFISH__CREATUREOBJECT_.
unsigned int FishingManager::getFishBoxID (CreatureObject * player)
Gets Fishing Window ID from Event getFishBoxID gets the Event linked to a player and returns the fishBoxID from it
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get fishing event's fishBoxID
Returns
{ boxID or -1 }
Definition at line 427 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::getFishBoxID(), and RPC_GETFISHBOXID__CREATUREOBJECT_.
FishingEvent * FishingManager::getFishingEvent (CreatureObject * player)
FishingEvent getter getFishingEvent is a readonly method that gets the FishingEvent from the events VectorMap and returns it
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to get fishing event
Definition at line 746 of file FishingManager.cpp.
References _getImplementation(), and server::zone::managers::minigames::FishingManagerImplementation::getFishingEvent().
int FishingManager::getFishingState (CreatureObject * player)
Gets fishing state from Event getFishingState gets the Event linked to the player and returns the FishingState, NOTFISHING if there is no event
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get the fishing event's fishing state
Returns
{ 0-6 }
Definition at line 456 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::getFishingState(), and RPC_GETFISHINGSTATE__CREATUREOBJECT_.
SceneObject * FishingManager::getFishMarker (CreatureObject * player)
Gets Fish Marker in Event getFishMarker gets the Event linked to the player and returns the Marker of the Event, even if it is NULL
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get the event's fish marker
Returns
{ NULL: player is NULL, player: no fishing event, FishMarker otherwise }
Definition at line 485 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::getFishMarker(), and RPC_GETFISHMARKER__CREATUREOBJECT_.
int FishingManager::getNextAction (CreatureObject * player)
Gets Next Action from Event getNextAction gets the Event linked to the Player and returns the next action, if the player or the event are NULL the value DONOTHING(=0) is returned
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get the fishing event's nextAction member
Returns
{ 0-5: Next Action }
Definition at line 370 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::getNextAction(), and RPC_GETNEXTACTION__CREATUREOBJECT_.
FishingPoleObject * FishingManager::getPole (CreatureObject * player)
Gets Pole from Player getPole gets the SceneObject in the Players right hand and, unless it is NULL, checks whether it is a fishing pole and returns it
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get fishing pole
Returns
{ FishingPoleObject or NULL }
Definition at line 399 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::getPole(), and RPC_GETPOLE__CREATUREOBJECT_.
String FishingManager::getTime ()
Returns timestamp as string Takes current time and returns formatted String
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
{ String of time }
Definition at line 267 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::getTime(), and RPC_GETTIME__.
void FishingManager::initializeAction ()
Definition at line 73 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::initializeAction(), and RPC_INITIALIZEACTION__.
void FishingManager::initializeBaitStatus ()
Definition at line 47 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::initializeBaitStatus(), and RPC_INITIALIZEBAITSTATUS__.
void FishingManager::initializeColor ()
Definition at line 138 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::initializeColor(), and RPC_INITIALIZECOLOR__.
void FishingManager::initializeFishLength ()
Definition at line 112 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::initializeFishLength(), and RPC_INITIALIZEFISHLENGTH__.
void FishingManager::initializeFishType ()
Definition at line 99 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::initializeFishType(), and RPC_INITIALIZEFISHTYPE__.
void FishingManager::initializeLoot ()
Definition at line 125 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::initializeLoot(), and RPC_INITIALIZELOOT__.
void FishingManager::initializeProperty ()
Definition at line 60 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::initializeProperty(), and RPC_INITIALIZEPROPERTY__.
void FishingManager::initializeState ()
Definition at line 86 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::initializeState(), and RPC_INITIALIZESTATE__.
bool FishingManager::isPlaying (CreatureObject * player)
Definition at line 640 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::isPlaying(), and RPC_ISPLAYING__CREATUREOBJECT_.
bool FishingManager::loseBait (CreatureObject * player)
Lose the Bait in the Container loseBait gets the pole and removes the object from that container { For stacks (more than 1 of the bait) remove just one of it }
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to remove bait from pole
Returns
{ true if bait was removed }
Definition at line 567 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::loseBait(), and RPC_LOSEBAIT__CREATUREOBJECT_.
void FishingManager::mishapEvent (const String & text, CreatureObject * player, unsigned int boxID, bool losebait, String & moodString)
mishapEvent stops Fishing out of bad luck, possibly losing bait in the process mishapEvent uses the argument string and sends it to the Player, stops Fishing and if losebait is true, calls loseBait
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
text String to send to Player
player CreatureObject to which send message
boxID fishing window to close when calling stopFishing()
losebait If true the bait in the pole will be removed as an outcome of what happened
moodString String taken from player before fishing to return to after fishing
Definition at line 549 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::mishapEvent(), and RPC_MISHAPEVENT__STRING_CREATUREOBJECT_INT_BOOL_STRING_.
int FishingManager::notifyCloseContainer (CreatureObject * player, SceneObject * container)
Removes the Marker notifyCloseContainer is called when the registered Marker is closed.
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject to remove Marker from
Definition at line 182 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::notifyCloseContainer(), and RPC_NOTIFYCLOSECONTAINER__CREATUREOBJECT_SCENEOBJECT_.
int FishingManager::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 151 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
void FishingManager::removeMarker (CreatureObject * player, SceneObject * container)
Removes the fishing marker removeMarker sets the Marker in the Event to NULL and removes the marker from Zone it is only called where it is set to a new marker, or the event is stopped, so the NULL won't cause problems
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject to get Event to remove marker from
container Container to remove
Definition at line 670 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::removeMarker(), and RPC_REMOVEMARKER__CREATUREOBJECT_SCENEOBJECT_.
void FishingManager::removeSplash (SceneObject * splash)
Removes the Splash removeSplash is called from FishingSplashEvent, the splash is simply removed from zone
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
splash SceneObject to remove from Zone
Definition at line 685 of file FishingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingManagerImplementation::removeSplash(), and RPC_REMOVESPLASH__SCENEOBJECT_.
void FishingManager::sendReward (CreatureObject * player, SceneObject * marker, SceneObject * loot)
Sends loot to Player sendReward receives Player, the Marker and the created Object, adds the object to the marker, opens the Container to the Player and sends appropriate SystemMessage
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject receiving item
marker Container for item
loot Item to send to Player
Definition at line 282 of file FishingManager.cpp.
References _getImplementation(), RPC_SENDREWARD__CREATUREOBJECT_SCENEOBJECT_SCENEOBJECT_, and server::zone::managers::minigames::FishingManagerImplementation::sendReward().
void FishingManager::setFishBoxID (CreatureObject * player, unsigned int boxID)
Sets Window BoxID in Event setFishBoxID gets the event linked to the player and sets the fishBoxID to the argument given boxID
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to modify the fishing event
boxID fishing window to point to
Definition at line 441 of file FishingManager.cpp.
References _getImplementation(), RPC_SETFISHBOXID__CREATUREOBJECT_INT_, and server::zone::managers::minigames::FishingManagerImplementation::setFishBoxID().
void FishingManager::setFishingState (CreatureObject * player, int state)
Sets fishing state in Event setFishingState gets the Event linked to the player and sets the FishingState to the argument-given state unless it's NULL
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to set the fishing event's fishing state
state Integer value sent to event
Definition at line 470 of file FishingManager.cpp.
References _getImplementation(), RPC_SETFISHINGSTATE__CREATUREOBJECT_INT_, and server::zone::managers::minigames::FishingManagerImplementation::setFishingState().
void FishingManager::setFishMarker (CreatureObject * player, SceneObject * marker)
Sets Fish Marker in Event setFishMarker gets the Event linked to the player and sets it's marker to the argument-given marker there is an intended call that sets the marker in the event to NULL
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to set the event's fish marker
marker Marker sent to event
Definition at line 499 of file FishingManager.cpp.
References _getImplementation(), RPC_SETFISHMARKER__CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::minigames::FishingManagerImplementation::setFishMarker().
void FishingManager::setNextAction (CreatureObject * player, int next)
Sets Next Action on Fishing Event setNextAction gets the Fishing Event linked to the Player and sets it's Action to the argument unless it is out of acceptable bounds
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to modify the fishing event
next Integer index of Action selected by Player
Definition at line 384 of file FishingManager.cpp.
References _getImplementation(), RPC_SETNEXTACTION__CREATUREOBJECT_INT_, and server::zone::managers::minigames::FishingManagerImplementation::setNextAction().
int FishingManager::startFishing (CreatureObject * player)
Starts Fishing Game startFishing checks for Fishing Pole, Fishing Bait and Water at the position of the bobber, creates the bobber and opens the window for Fishing.
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject which wants to start fishing
Returns
{ 0: everything worked, 1: No Pole, 2: No Bait, 3: No Water, 4: Water under terrain, 5: Player Swimming, 6: Exception case }
Definition at line 206 of file FishingManager.cpp.
References _getImplementation(), RPC_STARTFISHING__CREATUREOBJECT_, and server::zone::managers::minigames::FishingManagerImplementation::startFishing().
void FishingManager::stopFishing (CreatureObject * player, unsigned int boxID, bool rem)
Stops Fishing Game stopFishing sets fishing state to NOTFISHING, creates a new splash (marker disappearing), closes the menu, removes the marker and stops the event
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject which wants to stop fishing
boxID Fishing window to close
rem if true removes Marker, false when called by successful catch so the container won't disappear
Definition at line 220 of file FishingManager.cpp.
References _getImplementation(), RPC_STOPFISHING__CREATUREOBJECT_INT_BOOL_, and server::zone::managers::minigames::FishingManagerImplementation::stopFishing().
void FishingManager::stopFishingEvent (CreatureObject * player)
Stops Fishing Event stopFishingEvent gets the FishingEvent for a player, drops it from the VectorMap and cancels it
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to stop the fishing event
Definition at line 732 of file FishingManager.cpp.
References _getImplementation(), RPC_STOPFISHINGEVENT__CREATUREOBJECT_, and server::zone::managers::minigames::FishingManagerImplementation::stopFishingEvent().
void FishingManager::success (CreatureObject * player, int fish, SceneObject * marker, unsigned int boxID)
success is called to give the Player his reward success uses the given fish to decide whether the player receives a misc item or a fish The values for chances (>93 for item, >94 on another roll for rare item) are based on a SWG Dev comment: "As for the drop rates of Fish Tank Items/Treasure maps/Junk Loot (not including collection fish) when fishing, each time you catch something, there is a 6% chance it will be one of the above mentioned items." -Millbarge - SWG Developer So there is a 6% chance of an item, and another 5% change for a rare item => 0.3% chance for a rare item Also, if you are unlucky (5% chance) the fish was too small and it is being tossed
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject that receives the reward
marker Fishing Marker that is used as Container
boxID Fishing window being closed
Definition at line 250 of file FishingManager.cpp.
References _getImplementation(), RPC_SUCCESS__CREATUREOBJECT_INT_SCENEOBJECT_INT_, and server::zone::managers::minigames::FishingManagerImplementation::success().
SceneObject * FishingManager::updateMarker (CreatureObject * player, SceneObject * marker, bool notifyPlayer)
Updates the fishing Marker updateMarker takes the player position and the marker position and halfes that distance creating a new marker at that position and returning the marker
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to update the fishing event's marker
marker Object sent to event as new marker
Returns
{ SceneObject of new Marker }
Definition at line 654 of file FishingManager.cpp.
References _getImplementation(), RPC_UPDATEMARKER__CREATUREOBJECT_SCENEOBJECT_BOOL_, and server::zone::managers::minigames::FishingManagerImplementation::updateMarker().
int FishingManager::vegetation (SceneObject * marker)
Calculates vegetation based on current Position vegetation returns a value 0-5 based on abs(PositionX/100) rounded up { Actually make vegetation a property of a body of water }
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
marker Fishing marker to get coordinates of to calculate the vegetation
Returns
{ 0-5 }
Definition at line 328 of file FishingManager.cpp.
References _getImplementation(), RPC_VEGETATION__SCENEOBJECT_, and server::zone::managers::minigames::FishingManagerImplementation::vegetation().
Friends And Related Function Documentation
friend class FishingManagerHelper friend
Definition at line 710 of file FishingManager.h.
Member Data Documentation
const int server::zone::managers::minigames::FishingManager::BITE = 4 static
Definition at line 169 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::BLACKFISH = 0 static
Definition at line 177 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::BLOWFISH = 1 static
Definition at line 179 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::BLUEFISH = 2 static
Definition at line 181 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::CATCH = 5 static
Definition at line 171 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::DONOTHING = 0 static
Definition at line 197 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::FAA = 3 static
Definition at line 183 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::FRESH = 0 static
Definition at line 191 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::LAA = 4 static
Definition at line 185 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::MISHAP = 45 static
Definition at line 213 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::MUSH = 10 static
Definition at line 195 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::NIBBLE = 3 static
Definition at line 167 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::NOEVENT = 0 static
Definition at line 209 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::NOTFISHING = 0 static
Definition at line 161 of file FishingManager.h.
Referenced by server::zone::managers::minigames::FishingManagerImplementation::checkFishingOnPositionUpdate().
const int server::zone::managers::minigames::FishingManager::PROCEED = 17 static
Definition at line 211 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::RAY = 5 static
Definition at line 187 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::REEL = 4 static
Definition at line 205 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::REELGAME = 7 static
Definition at line 175 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::REELING = 6 static
Definition at line 173 of file FishingManager.h.
Referenced by server::zone::managers::minigames::FishingManagerImplementation::checkFishingOnPositionUpdate().
const int server::zone::managers::minigames::FishingManager::SNAGGED = 2 static
Definition at line 165 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::SOGGY = 6 static
Definition at line 193 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::STOPFISHING = 5 static
Definition at line 207 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::STRIPED = 6 static
Definition at line 189 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::TUGLEFT = 3 static
Definition at line 203 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::TUGRIGHT = 2 static
Definition at line 201 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::TUGUP = 1 static
Definition at line 199 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManager::WAITING = 1 static
Definition at line 163 of file FishingManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingManager.cpp