Core3: server::zone::objects::creature::aigroup::AiGroupObserverImplementation Class Reference
server::zone::objects::creature::aigroup::AiGroupObserverImplementation Class Reference
#include <AiGroupObserver.h>
Public Member Functions
AiGroupObserverImplementation (AiGroup *group)
AiGroupObserverImplementation (DummyConstructorParameter *param)
virtual int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const AiGroupObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< AiGroupObserver * > _this
Protected Member Functions
virtual ~AiGroupObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference< AiGroup * > aiGroup
Friends
class AiGroupObserver
Detailed Description
Definition at line 87 of file AiGroupObserver.h.
Constructor & Destructor Documentation
AiGroupObserverImplementation::AiGroupObserverImplementation (AiGroup * group)
Definition at line 194 of file AiGroupObserver.cpp.
References _initializeImplementation(), and aiGroup.
AiGroupObserverImplementation::AiGroupObserverImplementation (DummyConstructorParameter * param)
Definition at line 68 of file AiGroupObserver.cpp.
References _initializeImplementation().
AiGroupObserverImplementation::~AiGroupObserverImplementation () protected virtual
Definition at line 73 of file AiGroupObserver.cpp.
Member Function Documentation
DistributedObjectStub * AiGroupObserverImplementation::_getStub ()
Definition at line 93 of file AiGroupObserver.cpp.
References _this.
void AiGroupObserverImplementation::_initializeImplementation () protected
Definition at line 80 of file AiGroupObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by AiGroupObserverImplementation().
void AiGroupObserverImplementation::_serializationHelperMethod () protected
Definition at line 129 of file AiGroupObserver.cpp.
Referenced by _initializeImplementation().
void AiGroupObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 88 of file AiGroupObserver.cpp.
References _this.
Referenced by server::zone::objects::creature::aigroup::AiGroupObserver::AiGroupObserver().
void AiGroupObserverImplementation::finalize () protected
Definition at line 77 of file AiGroupObserver.cpp.
void AiGroupObserverImplementation::lock (bool doLock = true) protected
Definition at line 101 of file AiGroupObserver.cpp.
References _this.
void AiGroupObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 105 of file AiGroupObserver.cpp.
References _this.
int AiGroupObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2) virtual
Definition at line 202 of file AiGroupObserver.cpp.
References aiGroup.
Referenced by server::zone::objects::creature::aigroup::AiGroupObserver::notifyObserverEvent().
AiGroupObserverImplementation::operator const AiGroupObserver * ()
Definition at line 97 of file AiGroupObserver.cpp.
void AiGroupObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 136 of file AiGroupObserver.cpp.
References readObjectMember().
bool AiGroupObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 155 of file AiGroupObserver.cpp.
References aiGroup.
Referenced by readObject().
void AiGroupObserverImplementation::rlock (bool doLock = true) protected
Definition at line 109 of file AiGroupObserver.cpp.
References _this.
void AiGroupObserverImplementation::runlock (bool doLock = true) protected
Definition at line 125 of file AiGroupObserver.cpp.
References _this.
void AiGroupObserverImplementation::unlock (bool doLock = true) protected
Definition at line 121 of file AiGroupObserver.cpp.
References _this.
void AiGroupObserverImplementation::wlock (bool doLock = true) protected
Definition at line 113 of file AiGroupObserver.cpp.
References _this.
void AiGroupObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 117 of file AiGroupObserver.cpp.
References _this.
void AiGroupObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 169 of file AiGroupObserver.cpp.
References writeObjectMembers().
int AiGroupObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 176 of file AiGroupObserver.cpp.
References aiGroup.
Referenced by writeObject().
Friends And Related Function Documentation
friend class AiGroupObserver friend
Definition at line 132 of file AiGroupObserver.h.
Member Data Documentation
WeakReference<AiGroupObserver*> server::zone::objects::creature::aigroup::AiGroupObserverImplementation::_this
Definition at line 98 of file AiGroupObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedReference<AiGroup* > server::zone::objects::creature::aigroup::AiGroupObserverImplementation::aiGroup protected
Definition at line 89 of file AiGroupObserver.h.
Referenced by AiGroupObserverImplementation(), notifyObserverEvent(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/aigroup/AiGroupObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/aigroup/AiGroupObserver.cpp