Core3: LayersGroup Class Reference
LayersGroup Class Reference
#include <LayersGroup.h>
Public Member Functions
LayersGroup ()
~LayersGroup ()
void parseFromIffStream (engine::util::IffStream *iffStream)
void parseFromIffStream (engine::util::IffStream *iffStream, Version<'0000'>)
Vector< Layer * > * getLayers ()
Public Member Functions inherited from TemplateVariable<'LYRS'>
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Private Attributes
Vector< Layer * > layers
Detailed Description
Definition at line 14 of file LayersGroup.h.
Constructor & Destructor Documentation
LayersGroup::LayersGroup () inline
Definition at line 18 of file LayersGroup.h.
LayersGroup::~LayersGroup () inline
Definition at line 22 of file LayersGroup.h.
References layers.
Member Function Documentation
Vector<Layer*>* LayersGroup::getLayers () inline
Definition at line 46 of file LayersGroup.h.
References layers.
Referenced by TerrainGenerator::addLayer(), ProceduralTerrainAppearance::addTerrainModification(), ProceduralTerrainAppearance::getEnvironmentID(), ProceduralTerrainAppearance::getHeight(), ProceduralTerrainAppearance::getLayer(), TerrainGenerator::parseFromIffStream(), TerrainGenerator::processLayers(), and TerrainGenerator::removeLayer().
void LayersGroup::parseFromIffStream (engine::util::IffStream * iffStream) inline virtual
Reimplemented from TemplateVariable<'LYRS'>.
Definition at line 29 of file LayersGroup.h.
void LayersGroup::parseFromIffStream (engine::util::IffStream * iffStream, Version<'0000'>) inline
Definition at line 35 of file LayersGroup.h.
References layers, and TemplateVariable< formType >::readObject().
Member Data Documentation
Vector<Layer*> LayersGroup::layers private
Definition at line 15 of file LayersGroup.h.
Referenced by getLayers(), parseFromIffStream(), and ~LayersGroup().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/LayersGroup.h