Core3: CreatureObjectDeltaMessage4 Class Reference
CreatureObjectDeltaMessage4 Class Reference
#include <CreatureObjectDeltaMessage4.h>
Public Member Functions
CreatureObjectDeltaMessage4 (CreatureObject *cr)
void updateAccelerationMultiplierBase ()
void updateAccelerationMultiplierMod ()
void updateSpeedMultiplierBase ()
void updateSpeedMultiplierMod ()
void updateRunSpeed ()
void updateEntertainerValue (uint32 value)
void updateListenToID (uint64 objectid)
void updateTerrainNegotiation ()
void updateTurnScale ()
Public Member Functions inherited from DeltaMessage
DeltaMessage (uint64 oid, uint32 name, uint8 type)
uint32 generateRandomObjectCRC ()
void startUpdate (uint16 type)
void addByteUpdate (uint16 type, uint8 value)
void addShortUpdate (uint16 type, uint16 value)
void addIntUpdate (uint16 type, uint32 value)
void addLongUpdate (uint16 type, uint64 value)
void addFloatUpdate (uint16 type, float value)
void addAsciiUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const UnicodeString &val)
void startList (uint32 cnt, uint32 updcnt)
void addListIntElement (uint16 index, uint32 value)
void addListFloatElement (uint16 index, float value)
void addListLongElement (uint16 index, uint64 value)
void addListAsciiElement (const String &value)
void removeListIntElement (uint16 index, uint32 value)
void removeListFloatElement (uint16 index, float value)
void removeListLongElement (uint16 index, uint64 value)
void removeListLongElement (uint16 index)
void removeListAsciiElement (const String &value)
void close ()
Private Attributes
CreatureObject * creo
Detailed Description
Definition at line 50 of file CreatureObjectDeltaMessage4.h.
Constructor & Destructor Documentation
CreatureObjectDeltaMessage4::CreatureObjectDeltaMessage4 (CreatureObject * cr) inline
Definition at line 54 of file CreatureObjectDeltaMessage4.h.
References creo.
Member Function Documentation
void CreatureObjectDeltaMessage4::updateAccelerationMultiplierBase () inline
Definition at line 59 of file CreatureObjectDeltaMessage4.h.
References DeltaMessage::addFloatUpdate(), and creo.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::creature::CreatureObjectImplementation::setAccelerationMultiplierBase(), and server::zone::managers::skill::SkillManager::surrenderSkill().
void CreatureObjectDeltaMessage4::updateAccelerationMultiplierMod () inline
Definition at line 63 of file CreatureObjectDeltaMessage4.h.
References DeltaMessage::addFloatUpdate(), and creo.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::creature::CreatureObjectImplementation::setAccelerationMultiplierMod(), and server::zone::managers::skill::SkillManager::surrenderSkill().
void CreatureObjectDeltaMessage4::updateEntertainerValue (uint32 value) inline
Definition at line 79 of file CreatureObjectDeltaMessage4.h.
References DeltaMessage::startUpdate().
void CreatureObjectDeltaMessage4::updateListenToID (uint64 objectid) inline
Definition at line 84 of file CreatureObjectDeltaMessage4.h.
References DeltaMessage::startUpdate().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::setListenToID().
void CreatureObjectDeltaMessage4::updateRunSpeed () inline
Definition at line 75 of file CreatureObjectDeltaMessage4.h.
References DeltaMessage::addFloatUpdate(), and creo.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::creature::CreatureObjectImplementation::setRunSpeed(), and server::zone::managers::skill::SkillManager::surrenderSkill().
void CreatureObjectDeltaMessage4::updateSpeedMultiplierBase () inline
Definition at line 67 of file CreatureObjectDeltaMessage4.h.
References DeltaMessage::addFloatUpdate(), and creo.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::creature::CreatureObjectImplementation::setSpeedMultiplierBase(), and server::zone::managers::skill::SkillManager::surrenderSkill().
void CreatureObjectDeltaMessage4::updateSpeedMultiplierMod () inline
Definition at line 71 of file CreatureObjectDeltaMessage4.h.
References DeltaMessage::addFloatUpdate(), and creo.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::creature::CreatureObjectImplementation::setSpeedMultiplierMod(), and server::zone::managers::skill::SkillManager::surrenderSkill().
void CreatureObjectDeltaMessage4::updateTerrainNegotiation () inline
Definition at line 90 of file CreatureObjectDeltaMessage4.h.
References DeltaMessage::addFloatUpdate(), and creo.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::creature::CreatureObjectImplementation::setTerrainNegotiation(), and server::zone::managers::skill::SkillManager::surrenderSkill().
void CreatureObjectDeltaMessage4::updateTurnScale () inline
Definition at line 94 of file CreatureObjectDeltaMessage4.h.
References DeltaMessage::addFloatUpdate(), and creo.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::setTurnScale().
Member Data Documentation
CreatureObject* CreatureObjectDeltaMessage4::creo private
Definition at line 51 of file CreatureObjectDeltaMessage4.h.
Referenced by CreatureObjectDeltaMessage4(), updateAccelerationMultiplierBase(), updateAccelerationMultiplierMod(), updateRunSpeed(), updateSpeedMultiplierBase(), updateSpeedMultiplierMod(), updateTerrainNegotiation(), and updateTurnScale().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/creature/CreatureObjectDeltaMessage4.h