Core3: ArmorObjectMenuComponent Class Reference
ArmorObjectMenuComponent Class Reference
#include <ArmorObjectMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 14 of file ArmorObjectMenuComponent.h.
Member Function Documentation
void ArmorObjectMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from WearableObjectMenuComponent.
Definition at line 23 of file ArmorObjectMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), WearableObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::scene::SceneObject::getParent(), and server::zone::objects::scene::SceneObject::isWearableObject().
int ArmorObjectMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from WearableObjectMenuComponent.
Definition at line 47 of file ArmorObjectMenuComponent.cpp.
References SuiWindowType::COLOR_ARMOR, server::zone::templates::SharedObjectTemplate::getAppearanceFilename(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), WearableObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObject::sendMessage(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/ArmorObjectMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/ArmorObjectMenuComponent.cpp