Core3: StructureContainerComponent Class Reference
StructureContainerComponent Class Reference
#include <StructureContainerComponent.h>
Public Member Functions
bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
Public Member Functions inherited from ContainerComponent
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
virtual int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Detailed Description
Definition at line 13 of file StructureContainerComponent.h.
Member Function Documentation
bool StructureContainerComponent::checkContainerPermission (SceneObject * sceneObject, CreatureObject * creature, uint16 permission) virtual
Reimplemented from ContainerComponent.
Definition at line 13 of file StructureContainerComponent.cpp.
References ContainerComponent::checkContainerPermission(), server::zone::objects::building::BuildingObject::isAllowedEntry(), server::zone::objects::scene::SceneObject::isBuildingObject(), server::zone::objects::structure::StructureObject::isOnAdminList(), server::zone::objects::structure::StructureObject::isOnPermissionList(), server::zone::objects::structure::StructureObject::isOwnerOf(), server::zone::objects::structure::StructureObject::isPrivateStructure(), server::zone::objects::structure::StructureObject::isPublicStructure(), server::zone::objects::scene::SceneObject::isStaticObject(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by GCWBaseContainerComponent::checkContainerPermission().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/structure/components/StructureContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/structure/components/StructureContainerComponent.cpp