Core3: MinefieldDataComponent Class Reference
MinefieldDataComponent Class Reference
#include <MinefieldDataComponent.h>
Public Member Functions
MinefieldDataComponent ()
~MinefieldDataComponent ()
void initializeTransientMembers ()
bool isMinefieldData ()
bool canExplode ()
int getCapacity ()
void updateCooldown (int cooldown)
void addMine (WeaponObject *weapon)
WeaponObject * getMine (int indx)
WeaponObject * removeMine (int indx)
int getMineCapacity ()
int getMineCount ()
void setMaxRange (int val)
int getMaxRange ()
Public Member Functions inherited from DataObjectComponent
DataObjectComponent ()
~DataObjectComponent ()
virtual void notifyObjectDestroyingFromDatabase ()
void setParent (SceneObject *object)
SceneObject * getParent ()
virtual bool isDiceData ()
virtual bool isVendorData ()
virtual bool isAuctionTerminalData ()
virtual bool isCreatureHabitatData ()
virtual bool isBuildingData ()
virtual bool isDestructibleBuildingData ()
virtual bool isTurretData ()
virtual bool isDetectorData ()
virtual bool isGCWBaseData ()
virtual bool isSecurityTerminalData ()
virtual bool isTurretControlTerminalData ()
virtual bool isDecoration ()
Protected Attributes
uint64 nextExplodeTime
int attackSpeed
Vector< WeaponObject * > mines
SharedInstallationObjectTemplate * templateData
int maxRange
Protected Attributes inherited from DataObjectComponent
ManagedWeakReference
< SceneObject * > parent
Static Protected Attributes
static const int CAPACITY = 20
Private Member Functions
void addSerializableVariables ()
Detailed Description
Definition at line 15 of file MinefieldDataComponent.h.
Constructor & Destructor Documentation
MinefieldDataComponent::MinefieldDataComponent () inline
Definition at line 24 of file MinefieldDataComponent.h.
References addSerializableVariables(), attackSpeed, maxRange, nextExplodeTime, and templateData.
MinefieldDataComponent::~MinefieldDataComponent () inline
Definition at line 33 of file MinefieldDataComponent.h.
Member Function Documentation
void MinefieldDataComponent::addMine (WeaponObject * weapon) inline
Definition at line 64 of file MinefieldDataComponent.h.
References mines.
void MinefieldDataComponent::addSerializableVariables () inline private
Definition at line 97 of file MinefieldDataComponent.h.
References mines.
Referenced by MinefieldDataComponent().
bool MinefieldDataComponent::canExplode () inline
Definition at line 50 of file MinefieldDataComponent.h.
References nextExplodeTime.
Referenced by MinefieldZoneComponent::notifyPositionUpdate(), and MinefieldAttackTask::run().
int MinefieldDataComponent::getCapacity () inline
Definition at line 54 of file MinefieldDataComponent.h.
References CAPACITY.
int MinefieldDataComponent::getMaxRange () inline
Definition at line 88 of file MinefieldDataComponent.h.
References maxRange.
Referenced by MinefieldZoneComponent::notifyPositionUpdate().
WeaponObject* MinefieldDataComponent::getMine (int indx) inline
Definition at line 68 of file MinefieldDataComponent.h.
References mines.
int MinefieldDataComponent::getMineCapacity () inline
Definition at line 76 of file MinefieldDataComponent.h.
References CAPACITY.
int MinefieldDataComponent::getMineCount () inline
Definition at line 80 of file MinefieldDataComponent.h.
References mines.
void MinefieldDataComponent::initializeTransientMembers () inline virtual
Reimplemented from DataObjectComponent.
Definition at line 37 of file MinefieldDataComponent.h.
References attackSpeed, server::zone::objects::scene::SceneObject::getObjectTemplate(), DataObjectComponent::getParent(), and templateData.
bool MinefieldDataComponent::isMinefieldData () inline virtual
Reimplemented from DataObjectComponent.
Definition at line 46 of file MinefieldDataComponent.h.
WeaponObject* MinefieldDataComponent::removeMine (int indx) inline
Definition at line 72 of file MinefieldDataComponent.h.
References mines.
void MinefieldDataComponent::setMaxRange (int val) inline
Definition at line 84 of file MinefieldDataComponent.h.
References maxRange.
Referenced by MinefieldAttackTask::run().
void MinefieldDataComponent::updateCooldown (int cooldown) inline
Definition at line 58 of file MinefieldDataComponent.h.
References nextExplodeTime.
Referenced by MinefieldAttackTask::run().
Member Data Documentation
int MinefieldDataComponent::attackSpeed protected
Definition at line 18 of file MinefieldDataComponent.h.
Referenced by initializeTransientMembers(), and MinefieldDataComponent().
const int MinefieldDataComponent::CAPACITY = 20 static protected
Definition at line 19 of file MinefieldDataComponent.h.
Referenced by getCapacity(), and getMineCapacity().
int MinefieldDataComponent::maxRange protected
Definition at line 22 of file MinefieldDataComponent.h.
Referenced by getMaxRange(), MinefieldDataComponent(), and setMaxRange().
Vector<WeaponObject*> MinefieldDataComponent::mines protected
Definition at line 20 of file MinefieldDataComponent.h.
Referenced by addMine(), addSerializableVariables(), getMine(), getMineCount(), and removeMine().
uint64 MinefieldDataComponent::nextExplodeTime protected
Definition at line 17 of file MinefieldDataComponent.h.
Referenced by canExplode(), MinefieldDataComponent(), and updateCooldown().
SharedInstallationObjectTemplate* MinefieldDataComponent::templateData protected
Definition at line 21 of file MinefieldDataComponent.h.
Referenced by initializeTransientMembers(), and MinefieldDataComponent().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/MinefieldDataComponent.h