Core3: server::zone::objects::player::sui::listbox::SuiListBoxImplementation Class Reference
server::zone::objects::player::sui::listbox::SuiListBoxImplementation Class Reference
#include <SuiListBox.h>
Public Member Functions
SuiListBoxImplementation (CreatureObject *player, unsigned int windowType=0, unsigned int listBoxType=0)
SuiListBoxImplementation (DummyConstructorParameter *param)
void init ()
void addMenuItem (const String &name, unsigned long long objectID=0)
String getMenuItemName (int index)
void removeAllMenuItems ()
unsigned long long getMenuObjectID (unsigned int idx)
int getMenuSize ()
BaseMessage * generateMessage ()
void setNextBox (unsigned int boxID)
void setPreviousBox (unsigned int boxID)
unsigned long long getNextBox ()
unsigned long long getPreviousBox ()
bool isListBox ()
operator const SuiListBox * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
SuiBoxImplementation (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
SuiBoxImplementation (DummyConstructorParameter *param)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
virtual bool isInputBox ()
virtual bool isMessageBox ()
virtual bool isTransferBox ()
virtual bool isBankTransferBox ()
virtual bool isSlicingBox ()
virtual bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
operator const SuiBox * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< SuiListBox * > _this
Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
WeakReference< SuiBox * > _this
Static Public Attributes
static const int MSGSELECTED = 0
static const int HANDLESINGLEBUTTON = 1
static const int HANDLETWOBUTTON = 2
static const int HANDLETHREEBUTTON = 3
Static Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Protected Member Functions
virtual ~SuiListBoxImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
virtual ~SuiBoxImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
Vector< ManagedReference
< SuiListBoxMenuItem * > > menuItems
int type
Protected Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
ManagedWeakReference
< CreatureObject * > player
Reference< SuiCallback * > suiCallback
unsigned int boxID
ManagedWeakReference
< SceneObject * > usingObject
String handlerStr
String cancelButtonText
bool cancelButton
String okButtonText
bool okButton
String otherButtonText
bool otherButton
String promptTitle
String promptText
int boxType
unsigned int windowType
float forceCloseDistance
Vector< String > headerSets
Vector< String > optionSets
int hdrOptCount
bool hasGenerated
Private Attributes
unsigned long long next
unsigned long long previous
Friends
class SuiListBox
Detailed Description
Definition at line 145 of file SuiListBox.h.
Constructor & Destructor Documentation
SuiListBoxImplementation::SuiListBoxImplementation (CreatureObject * player, unsigned int windowType = 0, unsigned int listBoxType = 0)
Definition at line 379 of file SuiListBox.cpp.
References _initializeImplementation(), init(), and type.
SuiListBoxImplementation::SuiListBoxImplementation (DummyConstructorParameter * param)
Definition at line 217 of file SuiListBox.cpp.
References _initializeImplementation().
SuiListBoxImplementation::~SuiListBoxImplementation () protected virtual
Definition at line 222 of file SuiListBox.cpp.
Member Function Documentation
DistributedObjectStub * SuiListBoxImplementation::_getStub ()
Definition at line 242 of file SuiListBox.cpp.
References _this.
void SuiListBoxImplementation::_initializeImplementation () protected
Definition at line 229 of file SuiListBox.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SuiListBoxImplementation().
void SuiListBoxImplementation::_serializationHelperMethod () protected
Definition at line 278 of file SuiListBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void SuiListBoxImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 237 of file SuiListBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_setStub(), and _this.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::SuiListBox().
void SuiListBoxImplementation::addMenuItem (const String & name, unsigned long long objectID = 0)
Use to add Menu Item to the ListBox Sui class. List will be looped through in generateBody
Definition at line 102 of file SuiListBoxImplementation.cpp.
References menuItems.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::addMenuItem().
void SuiListBoxImplementation::finalize () protected
Definition at line 226 of file SuiListBox.cpp.
BaseMessage * SuiListBoxImplementation::generateMessage () virtual
This crashes the client, but is what makes the third button Report info
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 14 of file SuiListBoxImplementation.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::addHeader(), server::zone::objects::player::sui::SuiBoxImplementation::addSetting(), server::zone::objects::player::sui::SuiBoxImplementation::boxID, server::zone::objects::player::sui::SuiBoxImplementation::cancelButton, server::zone::objects::player::sui::SuiBoxImplementation::cancelButtonText, server::zone::objects::player::sui::SuiBoxImplementation::generateBody(), server::zone::objects::player::sui::SuiBoxImplementation::generateFooter(), server::zone::objects::player::sui::SuiBoxImplementation::generateHeader(), getMenuSize(), server::zone::objects::player::sui::SuiBoxImplementation::hasGenerated, menuItems, server::zone::objects::player::sui::SuiBoxImplementation::okButton, server::zone::objects::player::sui::SuiBoxImplementation::okButtonText, server::zone::objects::player::sui::SuiBoxImplementation::otherButton, server::zone::objects::player::sui::SuiBoxImplementation::otherButtonText, server::zone::objects::player::sui::SuiBoxImplementation::promptText, and server::zone::objects::player::sui::SuiBoxImplementation::promptTitle.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::generateMessage().
String SuiListBoxImplementation::getMenuItemName (int index)
Definition at line 394 of file SuiListBox.cpp.
References menuItems.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::getMenuItemName().
unsigned long long SuiListBoxImplementation::getMenuObjectID (unsigned int idx)
Definition at line 406 of file SuiListBox.cpp.
References menuItems.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::getMenuObjectID().
int SuiListBoxImplementation::getMenuSize ()
Definition at line 419 of file SuiListBox.cpp.
References menuItems.
Referenced by generateMessage(), and server::zone::objects::player::sui::listbox::SuiListBox::getMenuSize().
unsigned long long SuiListBoxImplementation::getNextBox ()
Definition at line 434 of file SuiListBox.cpp.
References next.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::getNextBox().
unsigned long long SuiListBoxImplementation::getPreviousBox ()
Definition at line 439 of file SuiListBox.cpp.
References previous.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::getPreviousBox().
void SuiListBoxImplementation::init ()
Definition at line 387 of file SuiListBox.cpp.
References next, and previous.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::init(), and SuiListBoxImplementation().
bool SuiListBoxImplementation::isListBox () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 444 of file SuiListBox.cpp.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::isListBox().
void SuiListBoxImplementation::lock (bool doLock = true) protected
Definition at line 250 of file SuiListBox.cpp.
References _this.
void SuiListBoxImplementation::lock (ManagedObject * obj) protected
Definition at line 254 of file SuiListBox.cpp.
References _this.
SuiListBoxImplementation::operator const SuiListBox * ()
Definition at line 246 of file SuiListBox.cpp.
void SuiListBoxImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Reimplemented in server::zone::objects::player::sui::slotmachinebox::SuiSlotMachineBoxImplementation, and server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation.
Definition at line 285 of file SuiListBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::initializeTransientMembers(), and readObjectMember().
bool SuiListBoxImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 304 of file SuiListBox.cpp.
References menuItems, next, previous, server::zone::objects::player::sui::SuiBoxImplementation::readObjectMember(), and type.
Referenced by readObject().
void SuiListBoxImplementation::removeAllMenuItems ()
Clears all Menu Items from the list box
Warning
If you are going to reuse the SuiBox object and call this method, you most likely need to call clearOptions() in SuiBoxImplementation
Definition at line 401 of file SuiListBox.cpp.
References menuItems.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::removeAllMenuItems().
void SuiListBoxImplementation::rlock (bool doLock = true) protected
Definition at line 258 of file SuiListBox.cpp.
References _this.
void SuiListBoxImplementation::runlock (bool doLock = true) protected
Definition at line 274 of file SuiListBox.cpp.
References _this.
void SuiListBoxImplementation::setNextBox (unsigned int boxID)
Definition at line 424 of file SuiListBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::boxID, and next.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::setNextBox().
void SuiListBoxImplementation::setPreviousBox (unsigned int boxID)
Definition at line 429 of file SuiListBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::boxID, and previous.
Referenced by server::zone::objects::player::sui::listbox::SuiListBox::setPreviousBox().
void SuiListBoxImplementation::unlock (bool doLock = true) protected
Definition at line 270 of file SuiListBox.cpp.
References _this.
void SuiListBoxImplementation::wlock (bool doLock = true) protected
Definition at line 262 of file SuiListBox.cpp.
References _this.
void SuiListBoxImplementation::wlock (ManagedObject * obj) protected
Definition at line 266 of file SuiListBox.cpp.
References _this.
void SuiListBoxImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Reimplemented in server::zone::objects::player::sui::slotmachinebox::SuiSlotMachineBoxImplementation, and server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation.
Definition at line 330 of file SuiListBox.cpp.
References writeObjectMembers().
int SuiListBoxImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 337 of file SuiListBox.cpp.
References menuItems, next, previous, type, and server::zone::objects::player::sui::SuiBoxImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class SuiListBox friend
Definition at line 234 of file SuiListBox.h.
Member Data Documentation
WeakReference<SuiListBox*> server::zone::objects::player::sui::listbox::SuiListBoxImplementation::_this
Definition at line 200 of file SuiListBox.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
const int server::zone::objects::player::sui::listbox::SuiListBoxImplementation::HANDLESINGLEBUTTON = 1 static
Definition at line 159 of file SuiListBox.h.
const int server::zone::objects::player::sui::listbox::SuiListBoxImplementation::HANDLETHREEBUTTON = 3 static
Definition at line 163 of file SuiListBox.h.
const int server::zone::objects::player::sui::listbox::SuiListBoxImplementation::HANDLETWOBUTTON = 2 static
Definition at line 161 of file SuiListBox.h.
Vector<ManagedReference<SuiListBoxMenuItem* > > server::zone::objects::player::sui::listbox::SuiListBoxImplementation::menuItems protected
Definition at line 147 of file SuiListBox.h.
Referenced by addMenuItem(), generateMessage(), getMenuItemName(), getMenuObjectID(), getMenuSize(), readObjectMember(), removeAllMenuItems(), and writeObjectMembers().
const int server::zone::objects::player::sui::listbox::SuiListBoxImplementation::MSGSELECTED = 0 static
Definition at line 157 of file SuiListBox.h.
unsigned long long server::zone::objects::player::sui::listbox::SuiListBoxImplementation::next private
Definition at line 152 of file SuiListBox.h.
Referenced by getNextBox(), init(), readObjectMember(), setNextBox(), and writeObjectMembers().
unsigned long long server::zone::objects::player::sui::listbox::SuiListBoxImplementation::previous private
Definition at line 154 of file SuiListBox.h.
Referenced by getPreviousBox(), init(), readObjectMember(), setPreviousBox(), and writeObjectMembers().
int server::zone::objects::player::sui::listbox::SuiListBoxImplementation::type protected
Definition at line 149 of file SuiListBox.h.
Referenced by readObjectMember(), SuiListBoxImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/listbox/SuiListBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/listbox/SuiListBox.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/listbox/SuiListBoxImplementation.cpp