Core3: server::zone::objects::mission::MissionObjective Class Reference
server::zone::objects::mission::MissionObjective Class Reference
#include <MissionObjective.h>
Public Member Functions
MissionObjective (MissionObject *parent)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
MissionObjective (DummyConstructorParameter *param)
virtual ~MissionObjective ()
Friends
class MissionObjectiveHelper
Detailed Description
Definition at line 103 of file MissionObjective.h.
Constructor & Destructor Documentation
MissionObjective::MissionObjective (MissionObject * parent)
Definition at line 23 of file MissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_setStub().
MissionObjective::MissionObjective (DummyConstructorParameter * param) protected
Definition at line 30 of file MissionObjective.cpp.
MissionObjective::~MissionObjective () protected virtual
Definition at line 34 of file MissionObjective.cpp.
Member Function Documentation
DistributedObjectServant * MissionObjective::_getImplementation ()
Definition at line 318 of file MissionObjective.cpp.
Referenced by abort(), activate(), addObserver(), awardFactionPoints(), awardReward(), complete(), deactivate(), destroyObjectFromDatabase(), dropObserver(), fail(), getEndPosition(), getMissionObject(), getObjectiveType(), getObserver(), getObserverCount(), getPlayerOwner(), hasObservers(), initializeTransientMembers(), notifyObserverEvent(), removeAllObservers(), and removeMissionFromPlayer().
DistributedObjectServant * MissionObjective::_getImplementationForRead ()
Definition at line 324 of file MissionObjective.cpp.
void MissionObjective::_setImplementation (DistributedObjectServant * servant)
Definition at line 328 of file MissionObjective.cpp.
void MissionObjective::abort ()
Definition at line 192 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::abort(), and RPC_ABORT__.
void MissionObjective::activate ()
Definition at line 166 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::activate(), and RPC_ACTIVATE__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::activateMissions().
void MissionObjective::addObserver (MissionObserver * observer, bool makePersistent)
Definition at line 83 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::addObserver(), and RPC_ADDOBSERVER__MISSIONOBSERVER_BOOL_.
void MissionObjective::awardFactionPoints ()
Definition at line 270 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::awardFactionPoints(), and RPC_AWARDFACTIONPOINTS__.
void MissionObjective::awardReward ()
Definition at line 296 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::awardReward(), and RPC_AWARDREWARD__.
void MissionObjective::complete ()
Definition at line 205 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::complete(), and RPC_COMPLETE__.
void MissionObjective::deactivate ()
Definition at line 179 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::deactivate(), and RPC_DEACTIVATE__.
Referenced by server::zone::managers::mission::MissionManagerImplementation::deactivateMissions().
void MissionObjective::destroyObjectFromDatabase ()
Destroys this object from database
Precondition
{ this is locked }
Postcondition
{ this is locked }
Definition at line 52 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::destroyObjectFromDatabase(), and RPC_DESTROYOBJECTFROMDATABASE__.
void MissionObjective::dropObserver (MissionObserver * observer, bool removeFromDatabase)
Definition at line 98 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::dropObserver(), and RPC_DROPOBSERVER__MISSIONOBSERVER_BOOL_.
void MissionObjective::fail ()
Definition at line 218 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::fail(), and RPC_FAIL__.
Vector3 MissionObjective::getEndPosition ()
Definition at line 309 of file MissionObjective.cpp.
References _getImplementation(), and server::zone::objects::mission::MissionObjectiveImplementation::getEndPosition().
ManagedWeakReference< MissionObject * > MissionObjective::getMissionObject ()
Definition at line 231 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::getMissionObject(), and RPC_GETMISSIONOBJECT__.
Referenced by server::zone::objects::mission::bountyhunter::events::FindTargetTask::getTargetLevel().
unsigned int MissionObjective::getObjectiveType ()
Definition at line 244 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::getObjectiveType(), and RPC_GETOBJECTIVETYPE__.
MissionObserver * MissionObjective::getObserver (int index)
Definition at line 139 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::getObserver(), and RPC_GETOBSERVER__INT_.
int MissionObjective::getObserverCount ()
Definition at line 113 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::getObserverCount(), and RPC_GETOBSERVERCOUNT__.
ManagedWeakReference< CreatureObject * > MissionObjective::getPlayerOwner ()
Definition at line 257 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), and RPC_GETPLAYEROWNER__.
Referenced by server::zone::objects::mission::bountyhunter::events::FindTargetTask::findAndTrackSuccess().
bool MissionObjective::hasObservers ()
Definition at line 153 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::hasObservers(), and RPC_HASOBSERVERS__.
void MissionObjective::initializeTransientMembers ()
Definition at line 39 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
int MissionObjective::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 65 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
void MissionObjective::removeAllObservers ()
Definition at line 126 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::removeAllObservers(), and RPC_REMOVEALLOBSERVERS__.
void MissionObjective::removeMissionFromPlayer ()
Definition at line 283 of file MissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectiveImplementation::removeMissionFromPlayer(), and RPC_REMOVEMISSIONFROMPLAYER__.
Friends And Related Function Documentation
friend class MissionObjectiveHelper friend
Definition at line 164 of file MissionObjective.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObjective.cpp