Core3: DataTransformWithParentCallback Class Reference
DataTransformWithParentCallback Class Reference
#include <DataTransformWithParent.h>
Public Member Functions
DataTransformWithParentCallback (ObjectControllerMessageCallback *objectControllerCallback)
void parse (Message *message)
void bounceBack (SceneObject *object, ValidatedPosition &pos)
void run ()
void updatePosition (CreatureObject *object)
Public Member Functions inherited from server::zone::packets::MessageCallback
MessageCallback (ZoneClientSession *client, ZoneProcessServer *server)
virtual ~MessageCallback ()
int getTaskQueue ()
bool parseMessage (Message *packet)
ZoneClientSession * getClient ()
ZoneProcessServer * getServer ()
Private Attributes
uint32 movementStamp
uint32 movementCounter
uint64 parent
float directionX
float directionY
float directionZ
float directionW
float positionX
float positionZ
float positionY
float parsedSpeed
ObjectControllerMessageCallback * objectControllerMain
Additional Inherited Members
Protected Attributes inherited from server::zone::packets::MessageCallback
Reference< ZoneClientSession * > client
ManagedReference
< ZoneProcessServer * > server
int taskqueue
Detailed Description
Definition at line 83 of file DataTransformWithParent.h.
Constructor & Destructor Documentation
DataTransformWithParentCallback::DataTransformWithParentCallback (ObjectControllerMessageCallback * objectControllerCallback) inline
Definition at line 96 of file DataTransformWithParent.h.
References server::zone::packets::MessageCallback::client, server::zone::objects::scene::SceneObject::getLocalZone(), server::zone::Zone::getZoneName(), objectControllerMain, and server::zone::packets::MessageCallback::taskqueue.
Member Function Documentation
void DataTransformWithParentCallback::bounceBack (SceneObject * object, ValidatedPosition & pos) inline
Definition at line 143 of file DataTransformWithParent.h.
References ValidatedPosition::getParent(), and ValidatedPosition::getPosition().
Referenced by updatePosition().
void DataTransformWithParentCallback::parse (Message * message) inline virtual
Implements server::zone::packets::MessageCallback.
Definition at line 123 of file DataTransformWithParent.h.
References directionW, directionX, directionY, directionZ, movementCounter, movementStamp, parent, parsedSpeed, positionX, positionY, and positionZ.
void DataTransformWithParentCallback::run () inline
Definition at line 150 of file DataTransformWithParent.h.
References server::zone::packets::MessageCallback::client, CreaturePosture::DRIVINGVEHICLE, CreaturePosture::PRONE, CreaturePosture::RIDINGCREATURE, CreaturePosture::SKILLANIMATING, updatePosition(), and CreaturePosture::UPRIGHT.
void DataTransformWithParentCallback::updatePosition (CreatureObject * object) inline
Definition at line 169 of file DataTransformWithParent.h.
References server::zone::managers::objectcontroller::ObjectController::activateCommand(), bounceBack(), directionW, directionX, directionY, directionZ, CollisionManager::getCellFloorCollision(), server::zone::objects::scene::SceneObject::getContainerVolumeLimit(), server::zone::objects::scene::SceneObject::getCountableObjectsRecursive(), server::zone::ZoneServer::getObjectController(), server::zone::objects::scene::SceneObject::getParent(), ObjectControllerMessageCallback::getPriority(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::variables::ContainerPermissions::hasInheritPermissionsFromParent(), server::zone::objects::creature::CreatureObject::isFrozen(), server::zone::objects::player::PlayerObject::isPrivileged(), server::zone::objects::creature::CreatureObject::isRidingMount(), server::zone::objects::player::PlayerObject::isTeleporting(), movementCounter, movementStamp, objectControllerMain, parent, parsedSpeed, positionX, positionY, positionZ, server::zone::packets::MessageCallback::server, server::zone::objects::player::PlayerObject::setClientLastMovementStamp(), ValidatedPosition::update(), and server::zone::objects::scene::SceneObject::updateZoneWithParent().
Referenced by run().
Member Data Documentation
float DataTransformWithParentCallback::directionW private
Definition at line 88 of file DataTransformWithParent.h.
Referenced by parse(), and updatePosition().
float DataTransformWithParentCallback::directionX private
Definition at line 88 of file DataTransformWithParent.h.
Referenced by parse(), and updatePosition().
float DataTransformWithParentCallback::directionY private
Definition at line 88 of file DataTransformWithParent.h.
Referenced by parse(), and updatePosition().
float DataTransformWithParentCallback::directionZ private
Definition at line 88 of file DataTransformWithParent.h.
Referenced by parse(), and updatePosition().
uint32 DataTransformWithParentCallback::movementCounter private
Definition at line 85 of file DataTransformWithParent.h.
Referenced by parse(), and updatePosition().
uint32 DataTransformWithParentCallback::movementStamp private
Definition at line 84 of file DataTransformWithParent.h.
Referenced by parse(), and updatePosition().
ObjectControllerMessageCallback* DataTransformWithParentCallback::objectControllerMain private
Definition at line 92 of file DataTransformWithParent.h.
Referenced by DataTransformWithParentCallback(), and updatePosition().
uint64 DataTransformWithParentCallback::parent private
Definition at line 86 of file DataTransformWithParent.h.
Referenced by parse(), and updatePosition().
float DataTransformWithParentCallback::parsedSpeed private
Definition at line 90 of file DataTransformWithParent.h.
Referenced by parse(), and updatePosition().
float DataTransformWithParentCallback::positionX private
Definition at line 89 of file DataTransformWithParent.h.
Referenced by parse(), and updatePosition().
float DataTransformWithParentCallback::positionY private
Definition at line 89 of file DataTransformWithParent.h.
Referenced by parse(), and updatePosition().
float DataTransformWithParentCallback::positionZ private
Definition at line 89 of file DataTransformWithParent.h.
Referenced by parse(), and updatePosition().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/object/DataTransformWithParent.h