Core3: Skill Class Reference
Skill Class Reference
#include <Skill.h>
Public Member Functions
Skill ()
~Skill ()
int compareTo (const Skill &s)
int compareTo (Skill *s)
void parseDataTableRow (DataTableRow *row)
void parseLuaObject (LuaObject *templateData)
String & getSkillName ()
bool isGodOnly ()
bool isTitle ()
bool isSkill ()
bool isHidden ()
bool isSearchable ()
Skill * getParent ()
int getTotalChildren ()
Skill * getChildNode (int idx)
bool containsChildNode (Skill *skill)
String & getParentName ()
void addChild (Skill *skill)
Vector< String > * getAbilities ()
Vector< String > * getSchematicsGranted ()
VectorMap< String, int > * getSkillModifiers ()
Vector< String > * getSkillsRequired ()
bool isRequiredSkillOf (Skill *skill)
String getXpType ()
int getXpCap ()
int getXpCost ()
int getMoneyRequired ()
int getSkillPointsRequired ()
Vector< String > * getSpeciesRequired ()
Protected Attributes
Reference< Skill * > parentNode
Vector< Reference< Skill * > > childNodes
String skillName
String parentName
int graphType
bool godOnly
bool title
bool profession
bool hidden
bool searchable
int moneyRequired
int pointsRequired
int skillsRequiredCount
Vector< String > skillsRequired
Vector< String > preclusionSkills
String xpType
int xpCost
int xpCap
Vector< String > missionsRequired
int apprenticeshipsRequired
Vector< String > statsRequired
Vector< String > speciesRequired
int jediStateRequired
Vector< String > skillAbility
Vector< String > commands
VectorMap< String, int > skillModifiers
Vector< String > schematicsGranted
Vector< String > schematicsRevoked
Private Member Functions
void setParentNode (Skill *skill)
void parseSkillMods (const String &modstring)
Friends
class server::zone::managers::skill::SkillManager
Detailed Description
Definition at line 19 of file Skill.h.
Constructor & Destructor Documentation
Skill::Skill () inline
Definition at line 62 of file Skill.h.
Skill::~Skill () inline
Definition at line 81 of file Skill.h.
Member Function Documentation
void Skill::addChild (Skill * skill) inline
Definition at line 260 of file Skill.h.
References setParentNode().
Referenced by server::zone::managers::skill::SkillManager::loadClientData(), and server::zone::managers::skill::SkillManager::loadSkill().
int Skill::compareTo (const Skill & s) inline
Definition at line 84 of file Skill.h.
References skillName.
int Skill::compareTo (Skill * s) inline
Definition at line 88 of file Skill.h.
References skillName.
bool Skill::containsChildNode (Skill * skill) inline
Definition at line 252 of file Skill.h.
Vector<String>* Skill::getAbilities () inline
Definition at line 265 of file Skill.h.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::skill::SkillManager::surrenderAllSkills(), and server::zone::managers::skill::SkillManager::surrenderSkill().
Skill* Skill::getChildNode (int idx) inline
Definition at line 248 of file Skill.h.
int Skill::getMoneyRequired () inline
Returns the credits required for training the skill at a trainer.
Returns
the credits required for training the skill at a trainer.
Definition at line 305 of file Skill.h.
Referenced by server::zone::objects::creature::conversation::screenhandlers::TrainerCanLearnSkillScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainSkillScreenHandler::handleScreen(), and server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughCreditsScreenHandler::handleScreen().
Skill* Skill::getParent () inline
Definition at line 240 of file Skill.h.
String& Skill::getParentName () inline
Definition at line 256 of file Skill.h.
Vector<String>* Skill::getSchematicsGranted () inline
Definition at line 269 of file Skill.h.
Referenced by server::zone::managers::skill::SkillManager::awardDraftSchematics(), server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::skill::SkillManager::surrenderAllSkills(), and server::zone::managers::skill::SkillManager::surrenderSkill().
VectorMap<String, int>* Skill::getSkillModifiers () inline
Definition at line 273 of file Skill.h.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::skill::SkillManager::surrenderAllSkills(), and server::zone::managers::skill::SkillManager::surrenderSkill().
String& Skill::getSkillName () inline
Definition at line 216 of file Skill.h.
Referenced by server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer(), SkillList::add(), server::zone::managers::skill::SkillManager::awardSkill(), ResetJediCommand::doQueueCommand(), PlayerInfoCommand::executeCommand(), server::zone::objects::creature::conversation::screenhandlers::TrainerNextSkillsScreenHandler::getNextSkillsList(), server::zone::managers::player::PlayerManagerImplementation::getTeachableSkills(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainableSkillsScreenHandler::getTrainableSkillsList(), server::zone::objects::creature::conversation::screenhandlers::TrainerCanLearnSkillScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainSkillScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughCreditsScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughSkillPointsScreenHandler::handleScreen(), isRequiredSkillOf(), server::zone::managers::player::PlayerManagerImplementation::offerTeaching(), and server::zone::managers::skill::SkillManager::surrenderSkill().
int Skill::getSkillPointsRequired () inline
Returns the number of skill points required for the skill.
Returns
the number of skill points required for the skill.
Definition at line 313 of file Skill.h.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::skill::SkillManager::canLearnSkill(), PlayerInfoCommand::executeCommand(), server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughSkillPointsScreenHandler::handleScreen(), server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), server::zone::managers::skill::SkillManager::surrenderAllSkills(), and server::zone::managers::skill::SkillManager::surrenderSkill().
Vector<String>* Skill::getSkillsRequired () inline
Definition at line 277 of file Skill.h.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::skill::SkillManager::fullfillsSkillPrerequisites(), server::zone::objects::creature::conversation::screenhandlers::TrainerNextSkillsScreenHandler::getNextSkillsList(), and server::zone::objects::creature::conversation::screenhandlers::TrainerTrainableSkillsScreenHandler::getTrainableSkillsList().
Vector<String>* Skill::getSpeciesRequired () inline
Returns the species required for the skill.
Returns
the species required for the skill.
Definition at line 321 of file Skill.h.
Referenced by server::zone::managers::skill::SkillManager::fullfillsSkillPrerequisites().
int Skill::getTotalChildren () inline
Definition at line 244 of file Skill.h.
Referenced by server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer().
int Skill::getXpCap () inline
Definition at line 289 of file Skill.h.
Referenced by server::zone::managers::skill::SkillManager::updateXpLimits().
int Skill::getXpCost () inline
Returns the XP cost for the skill.
Returns
XP cost for the skill.
Definition at line 297 of file Skill.h.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::skill::SkillManager::canLearnSkill(), server::zone::managers::skill::SkillManager::fullfillsSkillPrerequisitesAndXp(), and server::zone::managers::player::PlayerManagerImplementation::offerTeaching().
String Skill::getXpType () inline
Definition at line 285 of file Skill.h.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::skill::SkillManager::canLearnSkill(), server::zone::managers::skill::SkillManager::fullfillsSkillPrerequisitesAndXp(), server::zone::managers::player::PlayerManagerImplementation::offerTeaching(), and server::zone::managers::skill::SkillManager::updateXpLimits().
bool Skill::isGodOnly () inline
Definition at line 220 of file Skill.h.
Referenced by server::zone::managers::skill::SkillManager::awardSkill().
bool Skill::isHidden () inline
Definition at line 232 of file Skill.h.
bool Skill::isRequiredSkillOf (Skill * skill) inline
Definition at line 281 of file Skill.h.
References getSkillName().
Referenced by server::zone::managers::skill::SkillManager::surrenderSkill().
bool Skill::isSearchable () inline
Definition at line 236 of file Skill.h.
bool Skill::isSkill () inline
Definition at line 228 of file Skill.h.
bool Skill::isTitle () inline
Definition at line 224 of file Skill.h.
void Skill::parseDataTableRow (DataTableRow * row) inline
Definition at line 92 of file Skill.h.
References DataTableRow::getValue().
void Skill::parseLuaObject (LuaObject * templateData) inline
Definition at line 125 of file Skill.h.
void Skill::parseSkillMods (const String & modstring) inline private
Definition at line 330 of file Skill.h.
void Skill::setParentNode (Skill * skill) inline private
Definition at line 326 of file Skill.h.
Referenced by addChild().
Friends And Related Function Documentation
friend class server::zone::managers::skill::SkillManager friend
Definition at line 350 of file Skill.h.
Member Data Documentation
int Skill::apprenticeshipsRequired protected
Definition at line 48 of file Skill.h.
Vector<Reference<Skill*> > Skill::childNodes protected
Definition at line 22 of file Skill.h.
Vector<String> Skill::commands protected
Definition at line 56 of file Skill.h.
bool Skill::godOnly protected
Definition at line 28 of file Skill.h.
int Skill::graphType protected
Definition at line 26 of file Skill.h.
bool Skill::hidden protected
Definition at line 31 of file Skill.h.
int Skill::jediStateRequired protected
Definition at line 53 of file Skill.h.
Vector<String> Skill::missionsRequired protected
Definition at line 46 of file Skill.h.
int Skill::moneyRequired protected
Definition at line 34 of file Skill.h.
String Skill::parentName protected
Definition at line 25 of file Skill.h.
Reference<Skill*> Skill::parentNode protected
Definition at line 21 of file Skill.h.
int Skill::pointsRequired protected
Definition at line 35 of file Skill.h.
Vector<String> Skill::preclusionSkills protected
Definition at line 39 of file Skill.h.
bool Skill::profession protected
Definition at line 30 of file Skill.h.
Vector<String> Skill::schematicsGranted protected
Definition at line 58 of file Skill.h.
Vector<String> Skill::schematicsRevoked protected
Definition at line 59 of file Skill.h.
bool Skill::searchable protected
Definition at line 32 of file Skill.h.
Vector<String> Skill::skillAbility protected
Definition at line 55 of file Skill.h.
VectorMap<String, int> Skill::skillModifiers protected
Definition at line 57 of file Skill.h.
String Skill::skillName protected
Definition at line 24 of file Skill.h.
Referenced by compareTo().
Vector<String> Skill::skillsRequired protected
Definition at line 38 of file Skill.h.
int Skill::skillsRequiredCount protected
Definition at line 36 of file Skill.h.
Vector<String> Skill::speciesRequired protected
Definition at line 51 of file Skill.h.
Vector<String> Skill::statsRequired protected
Definition at line 50 of file Skill.h.
bool Skill::title protected
Definition at line 29 of file Skill.h.
int Skill::xpCap protected
Definition at line 44 of file Skill.h.
int Skill::xpCost protected
Definition at line 43 of file Skill.h.
String Skill::xpType protected
Definition at line 41 of file Skill.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/variables/Skill.h