Core3: server::zone::objects::area::areashapes::CircularAreaShapeImplementation Class Reference
server::zone::objects::area::areashapes::CircularAreaShapeImplementation Class Reference
#include <CircularAreaShape.h>
Public Member Functions
CircularAreaShapeImplementation ()
CircularAreaShapeImplementation (DummyConstructorParameter *param)
void setRadius (float r)
virtual float getRadius ()
float getRadius2 ()
virtual bool containsPoint (float x, float y)
virtual bool containsPoint (const Vector3 &point)
virtual Vector3 getRandomPosition ()
virtual Vector3 getRandomPosition (const Vector3 &origin, float minDistance, float maxDistance)
virtual bool isCircularAreaShape ()
virtual bool isRectangularAreaShape ()
virtual bool isRingAreaShape ()
virtual bool intersectsWith (AreaShape *areaShape)
virtual float getArea ()
operator const CircularAreaShape * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
AreaShapeImplementation ()
AreaShapeImplementation (DummyConstructorParameter *param)
void setAreaCenter (float x, float y)
Vector3 getAreaCenter ()
operator const AreaShape * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< CircularAreaShape * > _this
Public Attributes inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
WeakReference< AreaShape * > _this
Protected Member Functions
virtual ~CircularAreaShapeImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
virtual ~AreaShapeImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
float radius
float radius2
Protected Attributes inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
Vector3 areaCenter
Private Member Functions
bool intersectsWithCircle (CircularAreaShape *circle)
Friends
class CircularAreaShape
Detailed Description
Definition at line 133 of file CircularAreaShape.h.
Constructor & Destructor Documentation
CircularAreaShapeImplementation::CircularAreaShapeImplementation ()
Definition at line 333 of file CircularAreaShape.cpp.
References _initializeImplementation(), radius, and radius2.
CircularAreaShapeImplementation::CircularAreaShapeImplementation (DummyConstructorParameter * param)
Definition at line 195 of file CircularAreaShape.cpp.
References _initializeImplementation().
CircularAreaShapeImplementation::~CircularAreaShapeImplementation () protected virtual
Definition at line 200 of file CircularAreaShape.cpp.
Member Function Documentation
DistributedObjectStub * CircularAreaShapeImplementation::_getStub ()
Definition at line 220 of file CircularAreaShape.cpp.
References _this.
void CircularAreaShapeImplementation::_initializeImplementation () protected
Definition at line 207 of file CircularAreaShape.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CircularAreaShapeImplementation().
void CircularAreaShapeImplementation::_serializationHelperMethod () protected
Definition at line 256 of file CircularAreaShape.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void CircularAreaShapeImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 215 of file CircularAreaShape.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::_setStub(), and _this.
Referenced by server::zone::objects::area::areashapes::CircularAreaShape::CircularAreaShape().
bool CircularAreaShapeImplementation::containsPoint (float x, float y) virtual
Check if the coordinate is within the area shape.
Parameters
x the x coordinate.
y the y coordinate.
Returns
true if the coordinate is within the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 12 of file CircularAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, and radius2.
Referenced by server::zone::objects::area::areashapes::CircularAreaShape::containsPoint().
bool CircularAreaShapeImplementation::containsPoint (const Vector3 & point) virtual
Check if the coordinate is within the area shape.
Parameters
point the point to check if it is within the area shape.
Returns
true if the coordinate is within the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 19 of file CircularAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, and radius2.
void CircularAreaShapeImplementation::finalize () protected
Definition at line 204 of file CircularAreaShape.cpp.
float CircularAreaShapeImplementation::getArea () virtual
Get the area of the areaShape.
Returns
the area of the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 69 of file CircularAreaShapeImplementation.cpp.
References radius2.
Referenced by server::zone::objects::area::areashapes::CircularAreaShape::getArea().
float CircularAreaShapeImplementation::getRadius () virtual
Get the radius of the circle.
Returns
radius of the circle
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 348 of file CircularAreaShape.cpp.
References radius.
Referenced by server::zone::objects::area::areashapes::CircularAreaShape::getRadius().
float CircularAreaShapeImplementation::getRadius2 ()
Get the squared radius of the circle.
Returns
squared radius of the circle
Definition at line 353 of file CircularAreaShape.cpp.
References radius2.
Referenced by server::zone::objects::area::areashapes::CircularAreaShape::getRadius2().
Vector3 CircularAreaShapeImplementation::getRandomPosition () virtual
Generate a random position within the area.
Returns
a random position within the area.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 23 of file CircularAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, and radius.
Referenced by server::zone::objects::area::areashapes::CircularAreaShape::getRandomPosition().
Vector3 CircularAreaShapeImplementation::getRandomPosition (const Vector3 & origin, float minDistance, float maxDistance) virtual
Generate a random position within the area with the supplied origin and radius as limits.
Parameters
origin the origin coordinate to generate the random position from.
minDistance the minimum distance from the origin.
maxDistance the maximum distance from the origin.
Returns
a random position within the area.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 33 of file CircularAreaShapeImplementation.cpp.
bool CircularAreaShapeImplementation::intersectsWith (AreaShape * areaShape) virtual
Check if this area shape intersects with the supplied area shape.
Parameters
areaShape the area shape to check for intersections with.s
Returns
true if the area shapes intersects each other.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 43 of file CircularAreaShapeImplementation.cpp.
References _this, intersectsWithCircle(), server::zone::objects::area::areashapes::AreaShape::isCircularAreaShape(), server::zone::objects::area::areashapes::AreaShape::isRectangularAreaShape(), and server::zone::objects::area::areashapes::AreaShape::isRingAreaShape().
Referenced by server::zone::objects::area::areashapes::CircularAreaShape::intersectsWith().
bool CircularAreaShapeImplementation::intersectsWithCircle (CircularAreaShape * circle) private
Check if this area shape intersects with the supplied circular area shape.
Parameters
circle the circular area shape to check for intersections with.
Returns
true if the circles intersect with each other.
Definition at line 62 of file CircularAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, server::zone::objects::area::areashapes::AreaShape::getAreaCenter(), server::zone::objects::area::areashapes::CircularAreaShape::getRadius2(), and radius2.
Referenced by intersectsWith().
bool CircularAreaShapeImplementation::isCircularAreaShape () virtual
Check if this is a circular area shape.
Returns
true if it is a circular area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 358 of file CircularAreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::CircularAreaShape::isCircularAreaShape().
bool CircularAreaShapeImplementation::isRectangularAreaShape () virtual
Check if this is a rectangular area shape.
Returns
true if it is a rectangular area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 363 of file CircularAreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::CircularAreaShape::isRectangularAreaShape().
bool CircularAreaShapeImplementation::isRingAreaShape () virtual
Check if this is a ring area shape.
Returns
true if it is a ring area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 368 of file CircularAreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::CircularAreaShape::isRingAreaShape().
void CircularAreaShapeImplementation::lock (bool doLock = true) protected
Definition at line 228 of file CircularAreaShape.cpp.
References _this.
void CircularAreaShapeImplementation::lock (ManagedObject * obj) protected
Definition at line 232 of file CircularAreaShape.cpp.
References _this.
CircularAreaShapeImplementation::operator const CircularAreaShape * ()
Definition at line 224 of file CircularAreaShape.cpp.
void CircularAreaShapeImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 263 of file CircularAreaShape.cpp.
References readObjectMember().
bool CircularAreaShapeImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 282 of file CircularAreaShape.cpp.
References radius, radius2, and server::zone::objects::area::areashapes::AreaShapeImplementation::readObjectMember().
Referenced by readObject().
void CircularAreaShapeImplementation::rlock (bool doLock = true) protected
Definition at line 236 of file CircularAreaShape.cpp.
References _this.
void CircularAreaShapeImplementation::runlock (bool doLock = true) protected
Definition at line 252 of file CircularAreaShape.cpp.
References _this.
void CircularAreaShapeImplementation::setRadius (float r)
Set the radius of the cirle.
Parameters
r the new radius of the circle.
Definition at line 341 of file CircularAreaShape.cpp.
References radius, and radius2.
Referenced by server::zone::objects::area::areashapes::CircularAreaShape::setRadius().
void CircularAreaShapeImplementation::unlock (bool doLock = true) protected
Definition at line 248 of file CircularAreaShape.cpp.
References _this.
void CircularAreaShapeImplementation::wlock (bool doLock = true) protected
Definition at line 240 of file CircularAreaShape.cpp.
References _this.
void CircularAreaShapeImplementation::wlock (ManagedObject * obj) protected
Definition at line 244 of file CircularAreaShape.cpp.
References _this.
void CircularAreaShapeImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 300 of file CircularAreaShape.cpp.
References writeObjectMembers().
int CircularAreaShapeImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 307 of file CircularAreaShape.cpp.
References radius, radius2, and server::zone::objects::area::areashapes::AreaShapeImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class CircularAreaShape friend
Definition at line 266 of file CircularAreaShape.h.
Member Data Documentation
WeakReference<CircularAreaShape*> server::zone::objects::area::areashapes::CircularAreaShapeImplementation::_this
Definition at line 232 of file CircularAreaShape.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), intersectsWith(), lock(), rlock(), runlock(), unlock(), and wlock().
float server::zone::objects::area::areashapes::CircularAreaShapeImplementation::radius protected
Definition at line 135 of file CircularAreaShape.h.
Referenced by CircularAreaShapeImplementation(), getRadius(), getRandomPosition(), readObjectMember(), setRadius(), and writeObjectMembers().
float server::zone::objects::area::areashapes::CircularAreaShapeImplementation::radius2 protected
Definition at line 137 of file CircularAreaShape.h.
Referenced by CircularAreaShapeImplementation(), containsPoint(), getArea(), getRadius2(), intersectsWithCircle(), readObjectMember(), setRadius(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/CircularAreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/CircularAreaShape.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/CircularAreaShapeImplementation.cpp