Core3: FireworkShowContainerComponent Class Reference
FireworkShowContainerComponent Class Reference
#include <FireworkShowContainerComponent.h>
Public Member Functions
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Public Member Functions inherited from ContainerComponent
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
virtual bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
Detailed Description
Definition at line 33 of file FireworkShowContainerComponent.h.
Member Function Documentation
int FireworkShowContainerComponent::canAddObject (SceneObject * sceneObject, SceneObject * object, int containmentType, String & errorDescription) virtual
Evaluates if this object has the necessary free slots to be able to add the specified SceneObject
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be checked
error error string that the player will receive on error
Returns
returns 0 on success, or error code
Reimplemented from ContainerComponent.
Definition at line 50 of file FireworkShowContainerComponent.cpp.
References ContainerComponent::canAddObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), TransferErrorCode::INVALIDTYPE, and server::zone::objects::scene::SceneObject::isFireworkObject().
int FireworkShowContainerComponent::notifyObjectInserted (SceneObject * sceneObject, SceneObject * object) virtual
Is called when this object has been inserted with an object
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 92 of file FireworkShowContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::notifyObjectInserted().
int FireworkShowContainerComponent::notifyObjectRemoved (SceneObject * sceneObject, SceneObject * object, SceneObject * destination) virtual
Is called when an object was removed
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 100 of file FireworkShowContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::notifyObjectRemoved().
bool FireworkShowContainerComponent::transferObject (SceneObject * sceneObject, SceneObject * object, int containmentType, bool notifyClient = false, bool allowOverflow = false) virtual
Tries to add/link object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be added to the current object
containmentType arrangement type that will be used to add the object
notifyClient if true in range objects will be updated with the change
Returns
returns true if the object has been successfully added
Reimplemented from ContainerComponent.
Definition at line 60 of file FireworkShowContainerComponent.cpp.
References server::zone::managers::object::ObjectManager::cloneObject(), server::zone::objects::tangible::TangibleObject::decreaseUseCount(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::tangible::TangibleObject::getUseCount(), server::zone::objects::scene::SceneObject::isFireworkObject(), and ContainerComponent::transferObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/firework/components/FireworkShowContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/firework/components/FireworkShowContainerComponent.cpp