Core3: server::zone::objects::creature::buffs::SingleUseBuffImplementation Class Reference
server::zone::objects::creature::buffs::SingleUseBuffImplementation Class Reference
#include <SingleUseBuff.h>
Public Member Functions
SingleUseBuffImplementation (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype, unsigned int comCRC)
SingleUseBuffImplementation (DummyConstructorParameter *param)
void init (Vector< unsigned int > *events)
unsigned int getCommandCRC ()
CreatureObject * getPlayer ()
void activate ()
void deactivate ()
operator const SingleUseBuff * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
BuffImplementation (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype)
BuffImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
virtual void sendTo (CreatureObject *player)
virtual void sendDestroyTo (CreatureObject *player)
virtual void activate (bool applyModifiers)
virtual void deactivate (bool removeModifiers)
VectorMap< String, int > * getSkillModifiers ()
virtual void applyAttributeModifiers ()
virtual void applySkillModifiers ()
virtual void applyStates ()
virtual void removeAttributeModifiers ()
virtual void removeSkillModifiers ()
virtual void removeStates ()
virtual void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
virtual void parseAttributeModifierString (const String &modifierstring)
virtual void parseSkillModifierString (const String &modifierstring)
virtual String getAttributeModifierString ()
virtual String getSkillModifierString ()
virtual float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
VectorMap< byte, int > * getAttributeModifiers ()
virtual int getAttributeModifierValue (byte attribute)
virtual int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartMessage (StringIdChatParameter &start)
void setEndMessage (StringIdChatParameter &end)
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
operator const Buff * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< SingleUseBuff * > _this
Public Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
WeakReference< Buff * > _this
Protected Member Functions
virtual ~SingleUseBuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
virtual ~BuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference
< SingleUseBuffObserver * > observer
ManagedReference
< CreatureObject * > player
unsigned int commandCRC
Vector< unsigned int > eventTypes
Protected Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
ManagedWeakReference
< CreatureObject * > creature
Reference< BuffDurationEvent * > buffEvent
VectorMap< byte, int > attributeModifiers
VectorMap< String, int > skillModifiers
Vector< unsigned long long > states
String buffName
float buffDuration
unsigned int buffCRC
int buffType
bool fillAttributesOnBuff
StringIdChatParameter startMessage
StringIdChatParameter endMessage
String startFlyFile
String startFlyAux
byte startFlyRed
byte startFlyGreen
byte startFlyBlue
String endFlyFile
String endFlyAux
byte endFlyRed
byte endFlyGreen
byte endFlyBlue
Time nextExecutionTime
Private Member Functions
void addObservers ()
void dropObservers ()
Friends
class SingleUseBuff
Detailed Description
Definition at line 121 of file SingleUseBuff.h.
Constructor & Destructor Documentation
SingleUseBuffImplementation::SingleUseBuffImplementation (CreatureObject * creo, unsigned int buffcrc, float duration, int bufftype, unsigned int comCRC)
Definition at line 276 of file SingleUseBuff.cpp.
References _initializeImplementation(), commandCRC, and player.
SingleUseBuffImplementation::SingleUseBuffImplementation (DummyConstructorParameter * param)
Definition at line 114 of file SingleUseBuff.cpp.
References _initializeImplementation().
SingleUseBuffImplementation::~SingleUseBuffImplementation () protected virtual
Definition at line 119 of file SingleUseBuff.cpp.
Member Function Documentation
DistributedObjectStub * SingleUseBuffImplementation::_getStub ()
Definition at line 139 of file SingleUseBuff.cpp.
References _this.
void SingleUseBuffImplementation::_initializeImplementation () protected
Definition at line 126 of file SingleUseBuff.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SingleUseBuffImplementation().
void SingleUseBuffImplementation::_serializationHelperMethod () protected
Definition at line 175 of file SingleUseBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void SingleUseBuffImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 134 of file SingleUseBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::buffs::SingleUseBuff::SingleUseBuff().
void SingleUseBuffImplementation::activate () virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 310 of file SingleUseBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::activate(), and addObservers().
Referenced by server::zone::objects::creature::buffs::SingleUseBuff::activate().
void SingleUseBuffImplementation::addObservers () private
Definition at line 324 of file SingleUseBuff.cpp.
References eventTypes, observer, and player.
Referenced by activate().
void SingleUseBuffImplementation::deactivate () virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 317 of file SingleUseBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::deactivate(), and dropObservers().
Referenced by server::zone::objects::creature::buffs::SingleUseBuff::deactivate().
void SingleUseBuffImplementation::dropObservers () private
Definition at line 335 of file SingleUseBuff.cpp.
References eventTypes, observer, and player.
Referenced by deactivate().
void SingleUseBuffImplementation::finalize () protected
Definition at line 123 of file SingleUseBuff.cpp.
unsigned int SingleUseBuffImplementation::getCommandCRC ()
Definition at line 300 of file SingleUseBuff.cpp.
References commandCRC.
Referenced by server::zone::objects::creature::buffs::SingleUseBuff::getCommandCRC().
CreatureObject * SingleUseBuffImplementation::getPlayer ()
Definition at line 305 of file SingleUseBuff.cpp.
References player.
Referenced by server::zone::objects::creature::buffs::SingleUseBuff::getPlayer().
void SingleUseBuffImplementation::init (Vector< unsigned int > * events)
Definition at line 284 of file SingleUseBuff.cpp.
References _this, eventTypes, and observer.
Referenced by server::zone::objects::creature::buffs::SingleUseBuff::init().
void SingleUseBuffImplementation::lock (bool doLock = true) protected
Definition at line 147 of file SingleUseBuff.cpp.
References _this.
void SingleUseBuffImplementation::lock (ManagedObject * obj) protected
Definition at line 151 of file SingleUseBuff.cpp.
References _this.
SingleUseBuffImplementation::operator const SingleUseBuff * ()
Definition at line 143 of file SingleUseBuff.cpp.
void SingleUseBuffImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 182 of file SingleUseBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::initializeTransientMembers(), and readObjectMember().
bool SingleUseBuffImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 201 of file SingleUseBuff.cpp.
References commandCRC, eventTypes, observer, player, and server::zone::objects::creature::buffs::BuffImplementation::readObjectMember().
Referenced by readObject().
void SingleUseBuffImplementation::rlock (bool doLock = true) protected
Definition at line 155 of file SingleUseBuff.cpp.
References _this.
void SingleUseBuffImplementation::runlock (bool doLock = true) protected
Definition at line 171 of file SingleUseBuff.cpp.
References _this.
void SingleUseBuffImplementation::unlock (bool doLock = true) protected
Definition at line 167 of file SingleUseBuff.cpp.
References _this.
void SingleUseBuffImplementation::wlock (bool doLock = true) protected
Definition at line 159 of file SingleUseBuff.cpp.
References _this.
void SingleUseBuffImplementation::wlock (ManagedObject * obj) protected
Definition at line 163 of file SingleUseBuff.cpp.
References _this.
void SingleUseBuffImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 227 of file SingleUseBuff.cpp.
References writeObjectMembers().
int SingleUseBuffImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 234 of file SingleUseBuff.cpp.
References commandCRC, eventTypes, observer, player, and server::zone::objects::creature::buffs::BuffImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class SingleUseBuff friend
Definition at line 186 of file SingleUseBuff.h.
Member Data Documentation
WeakReference<SingleUseBuff*> server::zone::objects::creature::buffs::SingleUseBuffImplementation::_this
Definition at line 152 of file SingleUseBuff.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), init(), lock(), rlock(), runlock(), unlock(), and wlock().
unsigned int server::zone::objects::creature::buffs::SingleUseBuffImplementation::commandCRC protected
Definition at line 127 of file SingleUseBuff.h.
Referenced by getCommandCRC(), readObjectMember(), SingleUseBuffImplementation(), and writeObjectMembers().
Vector<unsigned int> server::zone::objects::creature::buffs::SingleUseBuffImplementation::eventTypes protected
Definition at line 129 of file SingleUseBuff.h.
Referenced by addObservers(), dropObservers(), init(), readObjectMember(), and writeObjectMembers().
ManagedReference<SingleUseBuffObserver* > server::zone::objects::creature::buffs::SingleUseBuffImplementation::observer protected
Definition at line 123 of file SingleUseBuff.h.
Referenced by addObservers(), dropObservers(), init(), readObjectMember(), and writeObjectMembers().
ManagedReference<CreatureObject* > server::zone::objects::creature::buffs::SingleUseBuffImplementation::player protected
Definition at line 125 of file SingleUseBuff.h.
Referenced by addObservers(), dropObservers(), getPlayer(), readObjectMember(), SingleUseBuffImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SingleUseBuff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SingleUseBuff.cpp