Core3: server::zone::objects::mission::MissionObserverImplementation Class Reference
server::zone::objects::mission::MissionObserverImplementation Class Reference
#include <MissionObserver.h>
Public Member Functions
MissionObserverImplementation (MissionObjective *objective)
MissionObserverImplementation (DummyConstructorParameter *param)
virtual int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
virtual void destroyObjectFromDatabase ()
operator const MissionObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< MissionObserver * > _this
Protected Member Functions
virtual ~MissionObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< MissionObjective * > missionObjective
Friends
class MissionObserver
Detailed Description
Definition at line 105 of file MissionObserver.h.
Constructor & Destructor Documentation
MissionObserverImplementation::MissionObserverImplementation (MissionObjective * objective)
Definition at line 209 of file MissionObserver.cpp.
References _initializeImplementation(), and missionObjective.
MissionObserverImplementation::MissionObserverImplementation (DummyConstructorParameter * param)
Definition at line 83 of file MissionObserver.cpp.
References _initializeImplementation().
MissionObserverImplementation::~MissionObserverImplementation () protected virtual
Definition at line 88 of file MissionObserver.cpp.
Member Function Documentation
DistributedObjectStub * MissionObserverImplementation::_getStub ()
Definition at line 108 of file MissionObserver.cpp.
References _this.
void MissionObserverImplementation::_initializeImplementation () protected
Definition at line 95 of file MissionObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by MissionObserverImplementation().
void MissionObserverImplementation::_serializationHelperMethod () protected
Definition at line 144 of file MissionObserver.cpp.
Referenced by _initializeImplementation().
void MissionObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 103 of file MissionObserver.cpp.
References _this.
Referenced by server::zone::objects::mission::MissionObserver::MissionObserver().
void MissionObserverImplementation::destroyObjectFromDatabase () virtual
Destroys this object from database
Precondition
{ this is locked }
Postcondition
{ this is locked }
Definition at line 22 of file MissionObserverImplementation.cpp.
References _this.
Referenced by server::zone::objects::mission::MissionObserver::destroyObjectFromDatabase().
void MissionObserverImplementation::finalize () protected
Definition at line 92 of file MissionObserver.cpp.
void MissionObserverImplementation::lock (bool doLock = true) protected
Definition at line 116 of file MissionObserver.cpp.
References _this.
void MissionObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 120 of file MissionObserver.cpp.
References _this.
int MissionObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2) virtual
Definition at line 13 of file MissionObserverImplementation.cpp.
References _this, and missionObjective.
Referenced by server::zone::objects::mission::MissionObserver::notifyObserverEvent().
MissionObserverImplementation::operator const MissionObserver * ()
Definition at line 112 of file MissionObserver.cpp.
void MissionObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 151 of file MissionObserver.cpp.
References readObjectMember().
bool MissionObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 170 of file MissionObserver.cpp.
References missionObjective.
Referenced by readObject().
void MissionObserverImplementation::rlock (bool doLock = true) protected
Definition at line 124 of file MissionObserver.cpp.
References _this.
void MissionObserverImplementation::runlock (bool doLock = true) protected
Definition at line 140 of file MissionObserver.cpp.
References _this.
void MissionObserverImplementation::unlock (bool doLock = true) protected
Definition at line 136 of file MissionObserver.cpp.
References _this.
void MissionObserverImplementation::wlock (bool doLock = true) protected
Definition at line 128 of file MissionObserver.cpp.
References _this.
void MissionObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 132 of file MissionObserver.cpp.
References _this.
void MissionObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 184 of file MissionObserver.cpp.
References writeObjectMembers().
int MissionObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 191 of file MissionObserver.cpp.
References missionObjective.
Referenced by writeObject().
Friends And Related Function Documentation
friend class MissionObserver friend
Definition at line 157 of file MissionObserver.h.
Member Data Documentation
WeakReference<MissionObserver*> server::zone::objects::mission::MissionObserverImplementation::_this
Definition at line 123 of file MissionObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), destroyObjectFromDatabase(), lock(), notifyObserverEvent(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<MissionObjective* > server::zone::objects::mission::MissionObserverImplementation::missionObjective protected
Definition at line 107 of file MissionObserver.h.
Referenced by MissionObserverImplementation(), notifyObserverEvent(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObserverImplementation.cpp