Core3: UpdatePVPStatusMessage Class Reference
UpdatePVPStatusMessage Class Reference
#include <UpdatePVPStatusMessage.h>
Public Member Functions
UpdatePVPStatusMessage (TangibleObject *tano)
UpdatePVPStatusMessage (TangibleObject *tano, uint32 pvpStatusBitmask)
Detailed Description
Definition at line 52 of file UpdatePVPStatusMessage.h.
Constructor & Destructor Documentation
UpdatePVPStatusMessage::UpdatePVPStatusMessage (TangibleObject * tano) inline
Definition at line 54 of file UpdatePVPStatusMessage.h.
References server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::scene::SceneObject::getObjectID(), and server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask().
UpdatePVPStatusMessage::UpdatePVPStatusMessage (TangibleObject * tano, uint32 pvpStatusBitmask) inline
Definition at line 62 of file UpdatePVPStatusMessage.h.
References server::zone::objects::tangible::TangibleObject::getFaction(), and server::zone::objects::scene::SceneObject::getObjectID().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/tangible/UpdatePVPStatusMessage.h