Core3: HarvesterObjectMessage7 Class Reference
HarvesterObjectMessage7 Class Reference
#include <HarvesterObjectMessage7.h>
Public Member Functions
HarvesterObjectMessage7 (InstallationObject *hino)
void insertHopperSpawnObjects (Vector< ManagedReference< ResourceSpawn * > > *resourceList, InstallationObject *hino)
void insertResourceIDList (Vector< ManagedReference< ResourceSpawn * > > *hino)
void insertResourceNameList (Vector< ManagedReference< ResourceSpawn * > > *hino)
void insertResourceTypeList (Vector< ManagedReference< ResourceSpawn * > > *hino)
void insertHopperItems (InstallationObject *hino)
Public Member Functions inherited from BaseLineMessage
BaseLineMessage (uint64 oid, uint32 name, uint8 type, uint16 opcnt)
uint32 generateRandomObjectCRC ()
void setSize ()
void insertStringId (StringId *id)
void insertCustomName (const UnicodeString &name)
Detailed Description
Definition at line 11 of file HarvesterObjectMessage7.h.
Constructor & Destructor Documentation
HarvesterObjectMessage7::HarvesterObjectMessage7 (InstallationObject * hino) inline
Definition at line 13 of file HarvesterObjectMessage7.h.
References server::zone::objects::installation::InstallationObject::getActiveResourceSpawnID(), server::zone::objects::installation::InstallationObject::getActualRate(), server::zone::objects::installation::InstallationObject::getExtractionRate(), server::zone::objects::installation::InstallationObject::getHopperSize(), server::zone::objects::installation::InstallationObject::getHopperSizeMax(), server::zone::objects::installation::InstallationObject::getInstallationType(), server::zone::managers::resource::ResourceManager::getResourceListByType(), server::zone::ZoneServer::getResourceManager(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::scene::SceneObject::getZoneServer(), insertHopperItems(), insertHopperSpawnObjects(), insertResourceIDList(), insertResourceNameList(), insertResourceTypeList(), server::zone::objects::installation::InstallationObject::isOperating(), and BaseLineMessage::setSize().
Member Function Documentation
void HarvesterObjectMessage7::insertHopperItems (InstallationObject * hino) inline
Definition at line 95 of file HarvesterObjectMessage7.h.
References server::zone::objects::installation::InstallationObject::getHopperList(), HopperList::insertToMessage(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
Referenced by HarvesterObjectMessage7().
void HarvesterObjectMessage7::insertHopperSpawnObjects (Vector< ManagedReference< ResourceSpawn * > > * resourceList, InstallationObject * hino) inline
Definition at line 57 of file HarvesterObjectMessage7.h.
References server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::installation::InstallationObject::getHopperList(), server::zone::objects::resource::ResourceSpawn::inShift(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
Referenced by HarvesterObjectMessage7().
void HarvesterObjectMessage7::insertResourceIDList (Vector< ManagedReference< ResourceSpawn * > > * hino) inline
Definition at line 69 of file HarvesterObjectMessage7.h.
Referenced by HarvesterObjectMessage7().
void HarvesterObjectMessage7::insertResourceNameList (Vector< ManagedReference< ResourceSpawn * > > * hino) inline
Definition at line 79 of file HarvesterObjectMessage7.h.
Referenced by HarvesterObjectMessage7().
void HarvesterObjectMessage7::insertResourceTypeList (Vector< ManagedReference< ResourceSpawn * > > * hino) inline
Definition at line 87 of file HarvesterObjectMessage7.h.
Referenced by HarvesterObjectMessage7().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/harvester/HarvesterObjectMessage7.h