Core3: Servlet Class Reference
Servlet Class Reference abstract
#include <Servlet.h>
Public Member Functions
Servlet (String context)
virtual ~Servlet ()
virtual void handleGet (HttpRequest *request, HttpResponse *response)=0
virtual void handlePost (HttpRequest *request, HttpResponse *response)=0
void handleRequest (struct mg_connection *conn, HttpRequest *request, HttpResponse *response)
void setZoneServer (ZoneServer *serv)
String getContext ()
Protected Attributes
ManagedReference< ZoneServer * > server
Private Member Functions
void outputResponse (struct mg_connection *conn, HttpResponse *response)
Private Attributes
String context
Detailed Description
Definition at line 16 of file Servlet.h.
Constructor & Destructor Documentation
Servlet::Servlet (String context)
Definition at line 12 of file Servlet.cpp.
References context.
Servlet::~Servlet () virtual
Definition at line 20 of file Servlet.cpp.
Member Function Documentation
String Servlet::getContext () inline
Definition at line 36 of file Servlet.h.
References context.
Referenced by server::web::WebServer::handleRequest().
virtual void Servlet::handleGet (HttpRequest * request, HttpResponse * response) pure virtual
Implemented in AccountServlet, AdminServlet, CharacterServlet, LoginServlet, LogsServlet, MainServlet, and PermissionsServlet.
Referenced by server::web::WebServer::dispatch(), and handleRequest().
virtual void Servlet::handlePost (HttpRequest * request, HttpResponse * response) pure virtual
Implemented in AccountServlet, AdminServlet, CharacterServlet, LoginServlet, LogsServlet, MainServlet, and PermissionsServlet.
Referenced by handleRequest().
void Servlet::handleRequest (struct mg_connection * conn, HttpRequest * request, HttpResponse * response)
Definition at line 24 of file Servlet.cpp.
References server::web::HttpRequest::getRequestMethod(), handleGet(), handlePost(), outputResponse(), and server::web::HttpResponse::println().
Referenced by server::web::WebServer::handleRequest().
void Servlet::outputResponse (struct mg_connection * conn, HttpResponse * response) private
Definition at line 48 of file Servlet.cpp.
References server::web::HttpResponse::generatePage(), and mg_printf().
Referenced by handleRequest().
void Servlet::setZoneServer (ZoneServer * serv) inline
Definition at line 32 of file Servlet.h.
References server.
Referenced by server::web::WebServer::addContext().
Member Data Documentation
String Servlet::context private
Definition at line 18 of file Servlet.h.
Referenced by getContext(), and Servlet().
ManagedReference<ZoneServer*> Servlet::server protected
Definition at line 20 of file Servlet.h.
Referenced by PermissionsServlet::handlePost(), and setZoneServer().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/servlets/Servlet.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/servlets/Servlet.cpp