Core3: InsuranceTerminalMenuComponent Class Reference
InsuranceTerminalMenuComponent Class Reference
#include <InsuranceTerminalMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file InsuranceTerminalMenuComponent.h.
Member Function Documentation
void InsuranceTerminalMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from TangibleObjectMenuComponent.
Definition at line 18 of file InsuranceTerminalMenuComponent.cpp.
References TangibleObjectMenuComponent::fillObjectMenuResponse().
int InsuranceTerminalMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from TangibleObjectMenuComponent.
Definition at line 23 of file InsuranceTerminalMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::managers::player::PlayerManager::getInsurableItems(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), TangibleObjectMenuComponent::handleObjectMenuSelect(), SuiWindowType::INSURANCE_MENU, server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::objects::creature::CreatureObject::sendMessage(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/InsuranceTerminalMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/InsuranceTerminalMenuComponent.cpp