Core3: server::zone::managers::auction::AuctionManagerAdapter Class Reference
server::zone::managers::auction::AuctionManagerAdapter Class Reference
#include <AuctionManager.h>
Public Member Functions
AuctionManagerAdapter (AuctionManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initialize ()
void getItemAttributes (CreatureObject *player, unsigned long long objectid)
void getData (CreatureObject *player, int extent, unsigned long long vendorObjectID, int screen, unsigned int category, int count, int offset)
void retrieveItem (CreatureObject *player, unsigned long long objectid, unsigned long long vendorID)
void buyItem (CreatureObject *player, unsigned long long objectid, int price1, int price2)
void doAuctionBid (CreatureObject *player, AuctionItem *item, int price1, int price2)
void doInstantBuy (CreatureObject *player, AuctionItem *item)
int checkBidAuction (CreatureObject *player, AuctionItem *item, int price1, int price2)
void cancelItem (CreatureObject *player, unsigned long long objectID)
AuctionsMap * getAuctionMap ()
void checkVendorItems ()
void checkAuctions ()
String getVendorUID (SceneObject *vendor)
void updateVendorUID (SceneObject *vendor, const String &oldUID, const String &newUID)
void updateVendorSearch (SceneObject *vendor, bool enabled)
void expireSale (AuctionItem *item)
void expireBidAuction (AuctionItem *item)
void expireAuction (AuctionItem *item)
void deleteExpiredSale (AuctionItem *item)
bool isMarketEnabled ()
void setMarketEnabled (bool value)
void displayInfo (CreatureObject *player)
void updateAuctionOwner (AuctionItem *item, CreatureObject *player)
Detailed Description
Definition at line 380 of file AuctionManager.h.
Constructor & Destructor Documentation
AuctionManagerAdapter::AuctionManagerAdapter (AuctionManager * impl)
Definition at line 709 of file AuctionManager.cpp.
Member Function Documentation
void AuctionManagerAdapter::buyItem (CreatureObject * player, unsigned long long objectid, int price1, int price2)
Definition at line 853 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::cancelItem (CreatureObject * player, unsigned long long objectID)
Definition at line 869 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::checkAuctions ()
Definition at line 881 of file AuctionManager.cpp.
Referenced by invokeMethod().
int AuctionManagerAdapter::checkBidAuction (CreatureObject * player, AuctionItem * item, int price1, int price2)
Definition at line 865 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::checkVendorItems ()
Definition at line 877 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::deleteExpiredSale (AuctionItem * item)
Definition at line 909 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::displayInfo (CreatureObject * player)
Definition at line 921 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::doAuctionBid (CreatureObject * player, AuctionItem * item, int price1, int price2)
Definition at line 857 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::doInstantBuy (CreatureObject * player, AuctionItem * item)
Definition at line 861 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::expireAuction (AuctionItem * item)
Definition at line 905 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::expireBidAuction (AuctionItem * item)
Definition at line 901 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::expireSale (AuctionItem * item)
Definition at line 897 of file AuctionManager.cpp.
Referenced by invokeMethod().
AuctionsMap * AuctionManagerAdapter::getAuctionMap ()
Definition at line 873 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::getData (CreatureObject * player, int extent, unsigned long long vendorObjectID, int screen, unsigned int category, int count, int offset)
Definition at line 845 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::getItemAttributes (CreatureObject * player, unsigned long long objectid)
Definition at line 841 of file AuctionManager.cpp.
Referenced by invokeMethod().
String AuctionManagerAdapter::getVendorUID (SceneObject * vendor)
Definition at line 885 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::initialize ()
Definition at line 837 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 712 of file AuctionManager.cpp.
References buyItem(), cancelItem(), checkAuctions(), checkBidAuction(), checkVendorItems(), deleteExpiredSale(), displayInfo(), doAuctionBid(), doInstantBuy(), expireAuction(), expireBidAuction(), expireSale(), getAuctionMap(), getData(), getItemAttributes(), getVendorUID(), initialize(), isMarketEnabled(), retrieveItem(), RPC_BUYITEM__CREATUREOBJECT_LONG_INT_INT_, RPC_CANCELITEM__CREATUREOBJECT_LONG_, RPC_CHECKAUCTIONS__, RPC_CHECKBIDAUCTION__CREATUREOBJECT_AUCTIONITEM_INT_INT_, RPC_CHECKVENDORITEMS__, RPC_DELETEEXPIREDSALE__AUCTIONITEM_, RPC_DISPLAYINFO__CREATUREOBJECT_, RPC_DOAUCTIONBID__CREATUREOBJECT_AUCTIONITEM_INT_INT_, RPC_DOINSTANTBUY__CREATUREOBJECT_AUCTIONITEM_, RPC_EXPIREAUCTION__AUCTIONITEM_, RPC_EXPIREBIDAUCTION__AUCTIONITEM_, RPC_EXPIRESALE__AUCTIONITEM_, RPC_GETAUCTIONMAP__, RPC_GETDATA__CREATUREOBJECT_INT_LONG_INT_INT_INT_INT_, RPC_GETITEMATTRIBUTES__CREATUREOBJECT_LONG_, RPC_GETVENDORUID__SCENEOBJECT_, RPC_INITIALIZE__, RPC_ISMARKETENABLED__, RPC_RETRIEVEITEM__CREATUREOBJECT_LONG_LONG_, RPC_SETMARKETENABLED__BOOL_, RPC_UPDATEAUCTIONOWNER__AUCTIONITEM_CREATUREOBJECT_, RPC_UPDATEVENDORSEARCH__SCENEOBJECT_BOOL_, RPC_UPDATEVENDORUID__SCENEOBJECT_STRING_STRING_, setMarketEnabled(), updateAuctionOwner(), updateVendorSearch(), and updateVendorUID().
bool AuctionManagerAdapter::isMarketEnabled ()
Definition at line 913 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::retrieveItem (CreatureObject * player, unsigned long long objectid, unsigned long long vendorID)
Definition at line 849 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::setMarketEnabled (bool value)
Definition at line 917 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::updateAuctionOwner (AuctionItem * item, CreatureObject * player)
Definition at line 925 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::updateVendorSearch (SceneObject * vendor, bool enabled)
Definition at line 893 of file AuctionManager.cpp.
Referenced by invokeMethod().
void AuctionManagerAdapter::updateVendorUID (SceneObject * vendor, const String & oldUID, const String & newUID)
Definition at line 889 of file AuctionManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionManager.cpp