Core3: HealMindWoundSelf1Command Class Reference
HealMindWoundSelf1Command Class Reference
#include <HealMindWoundSelf1Command.h>
Public Member Functions
HealMindWoundSelf1Command (const String &name, ZoneProcessServer *server)
bool canPerformSkill (CreatureObject *creature)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file HealMindWoundSelf1Command.h.
Constructor & Destructor Documentation
HealMindWoundSelf1Command::HealMindWoundSelf1Command (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file HealMindWoundSelf1Command.h.
Member Function Documentation
bool HealMindWoundSelf1Command::canPerformSkill (CreatureObject * creature) inline
Definition at line 58 of file HealMindWoundSelf1Command.h.
References CreatureAttribute::FOCUS, server::zone::objects::creature::CreatureObject::getWounds(), CreatureAttribute::MIND, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and CreatureAttribute::WILLPOWER.
Referenced by doQueueCommand().
int HealMindWoundSelf1Command::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 67 of file HealMindWoundSelf1Command.h.
References canPerformSkill(), CreatureAttribute::FOCUS, server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::healWound(), CreatureAttribute::MIND, server::zone::objects::creature::CreatureObject::playEffect(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and CreatureAttribute::WILLPOWER.
float HealMindWoundSelf1Command::getCommandDuration (CreatureObject * object, const UnicodeString & arguments) inline
Definition at line 145 of file HealMindWoundSelf1Command.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/HealMindWoundSelf1Command.h