Core3: DestructibleBuildingDataComponent Class Reference
DestructibleBuildingDataComponent Class Reference
#include <DestructibleBuildingDataComponent.h>
Public Member Functions
DestructibleBuildingDataComponent ()
virtual ~DestructibleBuildingDataComponent ()
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
bool isVulnerable ()
bool isDestructibleBuildingData ()
int getState ()
Time getLastVulnerableTime ()
Time getNextVulnerableTime ()
Time getVulnerabilityEndTime ()
Time getPlacmenetTime ()
Time getLastResetTime ()
Time getSliceRepairTime ()
int getUplinkBand ()
int getSampleMatches ()
void incrementSampleMatches ()
int isTerminalBeingRepaired ()
bool isTerminalDamanged ()
void setState (int state)
void setLastVulnerableTime (Time time)
void setNextVulnerableTime (Time time)
void setVulnerabilityEndTime (Time time)
void setPlacementTime (Time time)
void setLastResetTime (Time time)
void setUplinkBand (int band)
void setSliceRepairTime (Time time)
void setTerminalBeingRepaired (bool val)
void setTerminalDamaged (bool val)
void setSampleMatches (int val)
void setActiveTurret (int indx, uint64 turretOID)
void setActiveMinefield (int indx, uint64 minefieldOID)
void modifySampleAt (int indx, String val)
void initializeTransientMembers ()
void addDNAProfile (int indx, String val)
void setSystemDNAString (String val)
String getSystemDNAString ()
String getDNAProfile (int id)
bool getPowerPosition (int indx)
void clearDNAProfiles ()
bool isDNAInitialized ()
void turnSwitchOff (int indx)
void turnSwitchOn (int indx)
int getOnSwitchCount ()
void turnAllSwitchesOn ()
int getTotalTurretCount ()
int getTotalMinefieldCount ()
int getTotalScannerCount ()
bool isTurretSlotOccupied (int indx)
bool isMinefieldSlotOccupied (int indx)
uint64 getTurretID (int indx)
uint64 getMinefieldOID (int indx)
bool hasTurret (uint64 turretID)
bool hasMinefield (uint64 minefieldOID)
int getIndexOfTurret (uint64 turretID)
int getIndexOfMinefield (uint64 minefieldOID)
void setTurretID (int indx, uint64 turretOID)
void addScanner (int indx, uint64 scannerOID)
void addTurret (int indx, uint64 turretOID)
void setScannerID (int indx, uint64 scannerOID)
void setMinefieldID (int indx, uint64 minefieldOID)
void addMinefield (int indx, uint64 minefieldOID)
bool isGCWBaseData ()
bool hasDefense ()
void setDefense (bool value)
void setRebootFinishTime (Time val)
Time getRebootFinishTime ()
Public Member Functions inherited from BuildingDataComponent
BuildingDataComponent ()
virtual ~BuildingDataComponent ()
bool isBuildingData ()
Public Member Functions inherited from DataObjectComponent
DataObjectComponent ()
~DataObjectComponent ()
virtual void notifyObjectDestroyingFromDatabase ()
void setParent (SceneObject *object)
SceneObject * getParent ()
virtual bool isDiceData ()
virtual bool isVendorData ()
virtual bool isAuctionTerminalData ()
virtual bool isCreatureHabitatData ()
virtual bool isTurretData ()
virtual bool isDetectorData ()
virtual bool isSecurityTerminalData ()
virtual bool isMinefieldData ()
virtual bool isTurretControlTerminalData ()
virtual bool isDecoration ()
Static Public Attributes
static const int INVULNERABLE = 0
static const int VULNERABLE = 1
static const int BAND = 2
static const int JAMMED = 3
static const int SLICED = 4
static const int DNA = 5
static const int OVERLOADED = 6
static const int ALIGNED = 7
static const int SHUTDOWNSEQUENCE = 8
static const int POWERSWITCHCOUNT = 8
Private Member Functions
int writeObjectMembers (ObjectOutputStream *stream)
bool readObjectMember (ObjectInputStream *stream, const String &name)
Private Attributes
HashTable< int, String > dnaProfiles
String lastDNAString
int intCurrentState
bool terminalDamaged
bool inRepair
int sampleMatches
int switchesTurnedOn
Vector< bool > powerSwitchesTester
Vector< uint64 > turretSlots
Vector< uint64 > minefieldSlots
Vector< uint64 > scannerSlots
Time lastVulnerableTime
Time nextVulnerableTime
Time vulnerabilityEndTime
Time placementTime
Time lastResetTime
Time repairTime
Time rebootFinishTime
int uplinkBand
bool activeDefenses
bool exposed
Additional Inherited Members
Protected Attributes inherited from DataObjectComponent
ManagedWeakReference
< SceneObject * > parent
Detailed Description
Definition at line 17 of file DestructibleBuildingDataComponent.h.
Constructor & Destructor Documentation
DestructibleBuildingDataComponent::DestructibleBuildingDataComponent () inline
Definition at line 58 of file DestructibleBuildingDataComponent.h.
References activeDefenses, dnaProfiles, exposed, inRepair, intCurrentState, INVULNERABLE, lastDNAString, POWERSWITCHCOUNT, powerSwitchesTester, rebootFinishTime, repairTime, sampleMatches, switchesTurnedOn, terminalDamaged, and uplinkBand.
virtual DestructibleBuildingDataComponent::~DestructibleBuildingDataComponent () inline virtual
Definition at line 85 of file DestructibleBuildingDataComponent.h.
Member Function Documentation
void DestructibleBuildingDataComponent::addDNAProfile (int indx, String val) inline
Definition at line 207 of file DestructibleBuildingDataComponent.h.
References dnaProfiles.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::sendDNASampleMenu().
void DestructibleBuildingDataComponent::addMinefield (int indx, uint64 minefieldOID) inline
Definition at line 338 of file DestructibleBuildingDataComponent.h.
References minefieldSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addMinefield().
void DestructibleBuildingDataComponent::addScanner (int indx, uint64 scannerOID) inline
Definition at line 324 of file DestructibleBuildingDataComponent.h.
References scannerSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addScanner().
void DestructibleBuildingDataComponent::addTurret (int indx, uint64 turretOID) inline
Definition at line 327 of file DestructibleBuildingDataComponent.h.
References turretSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addTurret().
void DestructibleBuildingDataComponent::clearDNAProfiles () inline
Definition at line 230 of file DestructibleBuildingDataComponent.h.
References dnaProfiles.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::endVulnerability().
String DestructibleBuildingDataComponent::getDNAProfile (int id) inline
Definition at line 217 of file DestructibleBuildingDataComponent.h.
References dnaProfiles.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::processDNASample(), and server::zone::managers::gcw::GCWManagerImplementation::sendDNASampleMenu().
int DestructibleBuildingDataComponent::getIndexOfMinefield (uint64 minefieldOID) inline
Definition at line 311 of file DestructibleBuildingDataComponent.h.
References minefieldSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::notifyMinefieldDestruction().
int DestructibleBuildingDataComponent::getIndexOfTurret (uint64 turretID) inline
Definition at line 302 of file DestructibleBuildingDataComponent.h.
References turretSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::notifyTurretDestruction().
Time DestructibleBuildingDataComponent::getLastResetTime () inline
Definition at line 121 of file DestructibleBuildingDataComponent.h.
References lastResetTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::resetVulnerability().
Time DestructibleBuildingDataComponent::getLastVulnerableTime () inline
Definition at line 105 of file DestructibleBuildingDataComponent.h.
References lastVulnerableTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::endVulnerability(), and server::zone::managers::gcw::GCWManagerImplementation::refreshExpiredVulnerability().
uint64 DestructibleBuildingDataComponent::getMinefieldOID (int indx) inline
Definition at line 290 of file DestructibleBuildingDataComponent.h.
References minefieldSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::notifyMinefieldDestruction(), and server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield().
Time DestructibleBuildingDataComponent::getNextVulnerableTime () inline
Definition at line 109 of file DestructibleBuildingDataComponent.h.
References nextVulnerableTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::checkVulnerabilityData(), server::zone::managers::gcw::GCWManagerImplementation::endVulnerability(), server::zone::managers::gcw::GCWManagerImplementation::scheduleVulnerabilityStart(), server::zone::managers::gcw::GCWManagerImplementation::sendStatus(), and server::zone::managers::gcw::GCWManagerImplementation::startVulnerability().
int DestructibleBuildingDataComponent::getOnSwitchCount () inline
Definition at line 253 of file DestructibleBuildingDataComponent.h.
References switchesTurnedOn.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::handlePowerRegulatorSwitch().
Time DestructibleBuildingDataComponent::getPlacmenetTime () inline
Definition at line 117 of file DestructibleBuildingDataComponent.h.
References placementTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::initializeBaseTimers().
bool DestructibleBuildingDataComponent::getPowerPosition (int indx) inline
Definition at line 221 of file DestructibleBuildingDataComponent.h.
References powerSwitchesTester.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::handlePowerRegulatorSwitch(), and server::zone::managers::gcw::GCWManagerImplementation::sendPowerRegulatorControls().
Time DestructibleBuildingDataComponent::getRebootFinishTime () inline
Definition at line 358 of file DestructibleBuildingDataComponent.h.
References rebootFinishTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::scheduleBaseDestruction().
int DestructibleBuildingDataComponent::getSampleMatches () inline
Definition at line 134 of file DestructibleBuildingDataComponent.h.
References sampleMatches.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::processDNASample(), and server::zone::managers::gcw::GCWManagerImplementation::sendDNASampleMenu().
Time DestructibleBuildingDataComponent::getSliceRepairTime () inline
Definition at line 125 of file DestructibleBuildingDataComponent.h.
References repairTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::isTerminalDamaged(), and server::zone::managers::gcw::GCWManagerImplementation::repairTerminal().
int DestructibleBuildingDataComponent::getState () inline
Definition at line 101 of file DestructibleBuildingDataComponent.h.
References intCurrentState.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::checkVulnerabilityData(), server::zone::managers::gcw::GCWManagerImplementation::isBandIdentified(), server::zone::managers::gcw::GCWManagerImplementation::isBaseVulnerable(), server::zone::managers::gcw::GCWManagerImplementation::isDNASampled(), server::zone::managers::gcw::GCWManagerImplementation::isPowerOverloaded(), server::zone::managers::gcw::GCWManagerImplementation::isSecurityTermSliced(), server::zone::managers::gcw::GCWManagerImplementation::isShutdownSequenceStarted(), and server::zone::managers::gcw::GCWManagerImplementation::isUplinkJammed().
String DestructibleBuildingDataComponent::getSystemDNAString () inline
Definition at line 214 of file DestructibleBuildingDataComponent.h.
References lastDNAString.
int DestructibleBuildingDataComponent::getTotalMinefieldCount () inline
Definition at line 271 of file DestructibleBuildingDataComponent.h.
References minefieldSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addMinefield(), server::zone::managers::gcw::GCWManagerImplementation::notifyMinefieldDestruction(), and server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield().
int DestructibleBuildingDataComponent::getTotalScannerCount () inline
Definition at line 275 of file DestructibleBuildingDataComponent.h.
References scannerSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addScanner().
int DestructibleBuildingDataComponent::getTotalTurretCount () inline
Definition at line 267 of file DestructibleBuildingDataComponent.h.
References turretSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addTurret(), server::zone::managers::gcw::GCWManagerImplementation::notifyTurretDestruction(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield(), server::zone::managers::gcw::GCWManagerImplementation::performDonateTurret(), server::zone::managers::gcw::GCWManagerImplementation::sendBaseDefenseStatus(), and server::zone::managers::gcw::GCWManagerImplementation::verifyTurrets().
uint64 DestructibleBuildingDataComponent::getTurretID (int indx) inline
Definition at line 286 of file DestructibleBuildingDataComponent.h.
References turretSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::notifyTurretDestruction(), server::zone::managers::gcw::GCWManagerImplementation::performDonateTurret(), server::zone::managers::gcw::GCWManagerImplementation::sendBaseDefenseStatus(), server::zone::managers::gcw::GCWManagerImplementation::sendTurretAttackListTo(), and server::zone::managers::gcw::GCWManagerImplementation::verifyTurrets().
int DestructibleBuildingDataComponent::getUplinkBand () inline
Definition at line 130 of file DestructibleBuildingDataComponent.h.
References uplinkBand.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::verifyUplinkBand().
Time DestructibleBuildingDataComponent::getVulnerabilityEndTime () inline
Definition at line 113 of file DestructibleBuildingDataComponent.h.
References vulnerabilityEndTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::checkVulnerabilityData(), server::zone::managers::gcw::GCWManagerImplementation::failSecuritySlice(), server::zone::managers::gcw::GCWManagerImplementation::refreshExpiredVulnerability(), server::zone::managers::gcw::GCWManagerImplementation::scheduleVulnerabilityEnd(), and server::zone::managers::gcw::GCWManagerImplementation::sendStatus().
bool DestructibleBuildingDataComponent::hasDefense () inline
Definition at line 346 of file DestructibleBuildingDataComponent.h.
References activeDefenses.
Referenced by GCWBaseContainerComponent::checkPVEPermission(), and GCWBaseContainerComponent::checkPVPPermission().
bool DestructibleBuildingDataComponent::hasMinefield (uint64 minefieldOID) inline
Definition at line 298 of file DestructibleBuildingDataComponent.h.
References minefieldSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::notifyInstallationDestruction().
bool DestructibleBuildingDataComponent::hasTurret (uint64 turretID) inline
Definition at line 294 of file DestructibleBuildingDataComponent.h.
References turretSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::notifyInstallationDestruction().
void DestructibleBuildingDataComponent::incrementSampleMatches () inline
Definition at line 138 of file DestructibleBuildingDataComponent.h.
References sampleMatches.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::processDNASample().
void DestructibleBuildingDataComponent::initializeTransientMembers () virtual
Reimplemented from DataObjectComponent.
Definition at line 16 of file DestructibleBuildingDataComponent.cpp.
References uplinkBand.
bool DestructibleBuildingDataComponent::isDestructibleBuildingData () inline virtual
Reimplemented from DataObjectComponent.
Definition at line 97 of file DestructibleBuildingDataComponent.h.
bool DestructibleBuildingDataComponent::isDNAInitialized () inline
Definition at line 234 of file DestructibleBuildingDataComponent.h.
References dnaProfiles.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::sendDNASampleMenu().
bool DestructibleBuildingDataComponent::isGCWBaseData () inline virtual
Reimplemented from BuildingDataComponent.
Definition at line 342 of file DestructibleBuildingDataComponent.h.
bool DestructibleBuildingDataComponent::isMinefieldSlotOccupied (int indx) inline
Definition at line 282 of file DestructibleBuildingDataComponent.h.
References minefieldSlots.
int DestructibleBuildingDataComponent::isTerminalBeingRepaired () inline
Definition at line 142 of file DestructibleBuildingDataComponent.h.
References inRepair.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::repairTerminal().
bool DestructibleBuildingDataComponent::isTerminalDamanged () inline
Definition at line 146 of file DestructibleBuildingDataComponent.h.
References terminalDamaged.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::isTerminalDamaged(), and server::zone::managers::gcw::GCWManagerImplementation::repairTerminal().
bool DestructibleBuildingDataComponent::isTurretSlotOccupied (int indx) inline
Definition at line 278 of file DestructibleBuildingDataComponent.h.
References turretSlots.
bool DestructibleBuildingDataComponent::isVulnerable () inline
Definition at line 93 of file DestructibleBuildingDataComponent.h.
References intCurrentState, and VULNERABLE.
Referenced by GCWBaseContainerComponent::checkPVPPermission().
void DestructibleBuildingDataComponent::modifySampleAt (int indx, String val) inline
Definition at line 199 of file DestructibleBuildingDataComponent.h.
References dnaProfiles.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::processDNASample().
bool DestructibleBuildingDataComponent::parseFromBinaryStream (ObjectInputStream * stream)
Definition at line 20 of file DestructibleBuildingDataComponent.cpp.
References readObjectMember().
Referenced by readObjectMember().
bool DestructibleBuildingDataComponent::readObjectMember (ObjectInputStream * stream, const String & name) private
Definition at line 205 of file DestructibleBuildingDataComponent.cpp.
References activeDefenses, exposed, inRepair, intCurrentState, lastResetTime, lastVulnerableTime, minefieldSlots, nextVulnerableTime, parseFromBinaryStream(), placementTime, powerSwitchesTester, rebootFinishTime, repairTime, sampleMatches, scannerSlots, switchesTurnedOn, terminalDamaged, turretSlots, and vulnerabilityEndTime.
Referenced by parseFromBinaryStream().
void DestructibleBuildingDataComponent::setActiveMinefield (int indx, uint64 minefieldOID) inline
Definition at line 195 of file DestructibleBuildingDataComponent.h.
References minefieldSlots.
void DestructibleBuildingDataComponent::setActiveTurret (int indx, uint64 turretOID) inline
Definition at line 191 of file DestructibleBuildingDataComponent.h.
References turretSlots.
void DestructibleBuildingDataComponent::setDefense (bool value) inline
Definition at line 350 of file DestructibleBuildingDataComponent.h.
References activeDefenses.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::notifyTurretDestruction(), and server::zone::managers::gcw::GCWManagerImplementation::verifyTurrets().
void DestructibleBuildingDataComponent::setLastResetTime (Time time) inline
Definition at line 167 of file DestructibleBuildingDataComponent.h.
References lastResetTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::initializeBaseTimers(), and server::zone::managers::gcw::GCWManagerImplementation::resetVulnerability().
void DestructibleBuildingDataComponent::setLastVulnerableTime (Time time) inline
Definition at line 151 of file DestructibleBuildingDataComponent.h.
References lastVulnerableTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::endVulnerability(), server::zone::managers::gcw::GCWManagerImplementation::initializeBaseTimers(), server::zone::managers::gcw::GCWManagerImplementation::refreshExpiredVulnerability(), server::zone::managers::gcw::GCWManagerImplementation::resetVulnerability(), and server::zone::managers::gcw::GCWManagerImplementation::startVulnerability().
void DestructibleBuildingDataComponent::setMinefieldID (int indx, uint64 minefieldOID) inline
Definition at line 334 of file DestructibleBuildingDataComponent.h.
References minefieldSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::notifyMinefieldDestruction(), and server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield().
void DestructibleBuildingDataComponent::setNextVulnerableTime (Time time) inline
Definition at line 155 of file DestructibleBuildingDataComponent.h.
References nextVulnerableTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::endVulnerability(), server::zone::managers::gcw::GCWManagerImplementation::initializeBaseTimers(), server::zone::managers::gcw::GCWManagerImplementation::refreshExpiredVulnerability(), and server::zone::managers::gcw::GCWManagerImplementation::resetVulnerability().
void DestructibleBuildingDataComponent::setPlacementTime (Time time) inline
Definition at line 163 of file DestructibleBuildingDataComponent.h.
References placementTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::initializeBaseTimers().
void DestructibleBuildingDataComponent::setRebootFinishTime (Time val) inline
Definition at line 354 of file DestructibleBuildingDataComponent.h.
References rebootFinishTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::abortShutdownSequence(), and server::zone::managers::gcw::GCWManagerImplementation::initializeNewVulnerability().
void DestructibleBuildingDataComponent::setSampleMatches (int val) inline
Definition at line 187 of file DestructibleBuildingDataComponent.h.
References sampleMatches.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::initializeNewVulnerability().
void DestructibleBuildingDataComponent::setScannerID (int indx, uint64 scannerOID) inline
Definition at line 331 of file DestructibleBuildingDataComponent.h.
References scannerSlots.
void DestructibleBuildingDataComponent::setSliceRepairTime (Time time) inline
Definition at line 175 of file DestructibleBuildingDataComponent.h.
References repairTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::failSecuritySlice(), server::zone::managers::gcw::GCWManagerImplementation::initializeBaseTimers(), server::zone::managers::gcw::GCWManagerImplementation::initializeNewVulnerability(), and server::zone::managers::gcw::GCWManagerImplementation::repairTerminal().
void DestructibleBuildingDataComponent::setState (int state)
Definition at line 10 of file DestructibleBuildingDataComponent.cpp.
References intCurrentState, INVULNERABLE, and SHUTDOWNSEQUENCE.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::abortShutdownSequence(), server::zone::managers::gcw::GCWManagerImplementation::completeSecuritySlice(), server::zone::managers::gcw::GCWManagerImplementation::endVulnerability(), server::zone::managers::gcw::GCWManagerImplementation::handlePowerRegulatorSwitch(), server::zone::managers::gcw::GCWManagerImplementation::initializeNewVulnerability(), server::zone::managers::gcw::GCWManagerImplementation::processDNASample(), server::zone::managers::gcw::GCWManagerImplementation::refreshExpiredVulnerability(), server::zone::managers::gcw::GCWManagerImplementation::scheduleBaseDestruction(), and server::zone::managers::gcw::GCWManagerImplementation::verifyUplinkBand().
void DestructibleBuildingDataComponent::setSystemDNAString (String val) inline
Definition at line 211 of file DestructibleBuildingDataComponent.h.
References lastDNAString.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::initializeNewVulnerability(), and server::zone::managers::gcw::GCWManagerImplementation::refreshDNA().
void DestructibleBuildingDataComponent::setTerminalBeingRepaired (bool val) inline
Definition at line 179 of file DestructibleBuildingDataComponent.h.
References inRepair.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::failSecuritySlice(), server::zone::managers::gcw::GCWManagerImplementation::isTerminalDamaged(), and server::zone::managers::gcw::GCWManagerImplementation::repairTerminal().
void DestructibleBuildingDataComponent::setTerminalDamaged (bool val) inline
Definition at line 183 of file DestructibleBuildingDataComponent.h.
References terminalDamaged.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::failSecuritySlice(), server::zone::managers::gcw::GCWManagerImplementation::initializeBaseTimers(), server::zone::managers::gcw::GCWManagerImplementation::initializeNewVulnerability(), and server::zone::managers::gcw::GCWManagerImplementation::isTerminalDamaged().
void DestructibleBuildingDataComponent::setTurretID (int indx, uint64 turretOID) inline
Definition at line 320 of file DestructibleBuildingDataComponent.h.
References turretSlots.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::notifyTurretDestruction(), and server::zone::managers::gcw::GCWManagerImplementation::performDonateTurret().
void DestructibleBuildingDataComponent::setUplinkBand (int band) inline
Definition at line 171 of file DestructibleBuildingDataComponent.h.
References uplinkBand.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::renewUplinkBand().
void DestructibleBuildingDataComponent::setVulnerabilityEndTime (Time time) inline
Definition at line 159 of file DestructibleBuildingDataComponent.h.
References vulnerabilityEndTime.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::endVulnerability(), server::zone::managers::gcw::GCWManagerImplementation::initializeBaseTimers(), server::zone::managers::gcw::GCWManagerImplementation::refreshExpiredVulnerability(), and server::zone::managers::gcw::GCWManagerImplementation::resetVulnerability().
bool DestructibleBuildingDataComponent::toBinaryStream (ObjectOutputStream * stream)
Definition at line 40 of file DestructibleBuildingDataComponent.cpp.
References writeObjectMembers().
Referenced by writeObjectMembers().
void DestructibleBuildingDataComponent::turnAllSwitchesOn () inline
Definition at line 257 of file DestructibleBuildingDataComponent.h.
References POWERSWITCHCOUNT, powerSwitchesTester, and switchesTurnedOn.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::initializeNewVulnerability().
void DestructibleBuildingDataComponent::turnSwitchOff (int indx) inline
Definition at line 238 of file DestructibleBuildingDataComponent.h.
References powerSwitchesTester, and switchesTurnedOn.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::handlePowerRegulatorSwitch().
void DestructibleBuildingDataComponent::turnSwitchOn (int indx) inline
Definition at line 246 of file DestructibleBuildingDataComponent.h.
References powerSwitchesTester, and switchesTurnedOn.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::handlePowerRegulatorSwitch().
int DestructibleBuildingDataComponent::writeObjectMembers (ObjectOutputStream * stream) private
Definition at line 50 of file DestructibleBuildingDataComponent.cpp.
References activeDefenses, inRepair, intCurrentState, lastResetTime, lastVulnerableTime, minefieldSlots, nextVulnerableTime, placementTime, powerSwitchesTester, rebootFinishTime, repairTime, sampleMatches, scannerSlots, switchesTurnedOn, terminalDamaged, toBinaryStream(), turretSlots, and vulnerabilityEndTime.
Referenced by toBinaryStream().
Member Data Documentation
bool DestructibleBuildingDataComponent::activeDefenses private
Definition at line 42 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), hasDefense(), readObjectMember(), setDefense(), and writeObjectMembers().
const int DestructibleBuildingDataComponent::ALIGNED = 7 static
Definition at line 53 of file DestructibleBuildingDataComponent.h.
const int DestructibleBuildingDataComponent::BAND = 2 static
Definition at line 48 of file DestructibleBuildingDataComponent.h.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::isBandIdentified(), and server::zone::managers::gcw::GCWManagerImplementation::verifyUplinkBand().
const int DestructibleBuildingDataComponent::DNA = 5 static
Definition at line 51 of file DestructibleBuildingDataComponent.h.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::isDNASampled(), and server::zone::managers::gcw::GCWManagerImplementation::processDNASample().
HashTable<int, String> DestructibleBuildingDataComponent::dnaProfiles private
Definition at line 20 of file DestructibleBuildingDataComponent.h.
Referenced by addDNAProfile(), clearDNAProfiles(), DestructibleBuildingDataComponent(), getDNAProfile(), isDNAInitialized(), and modifySampleAt().
bool DestructibleBuildingDataComponent::exposed private
Definition at line 43 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), and readObjectMember().
bool DestructibleBuildingDataComponent::inRepair private
Definition at line 26 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), isTerminalBeingRepaired(), readObjectMember(), setTerminalBeingRepaired(), and writeObjectMembers().
int DestructibleBuildingDataComponent::intCurrentState private
Definition at line 24 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), getState(), isVulnerable(), readObjectMember(), setState(), and writeObjectMembers().
const int DestructibleBuildingDataComponent::INVULNERABLE = 0 static
Definition at line 46 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), server::zone::managers::gcw::GCWManagerImplementation::endVulnerability(), server::zone::managers::gcw::GCWManagerImplementation::isBaseVulnerable(), server::zone::managers::gcw::GCWManagerImplementation::refreshExpiredVulnerability(), and setState().
const int DestructibleBuildingDataComponent::JAMMED = 3 static
Definition at line 49 of file DestructibleBuildingDataComponent.h.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::isUplinkJammed(), and server::zone::managers::gcw::GCWManagerImplementation::verifyUplinkBand().
String DestructibleBuildingDataComponent::lastDNAString private
Definition at line 22 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), getSystemDNAString(), and setSystemDNAString().
Time DestructibleBuildingDataComponent::lastResetTime private
Definition at line 38 of file DestructibleBuildingDataComponent.h.
Referenced by getLastResetTime(), readObjectMember(), setLastResetTime(), and writeObjectMembers().
Time DestructibleBuildingDataComponent::lastVulnerableTime private
Definition at line 34 of file DestructibleBuildingDataComponent.h.
Referenced by getLastVulnerableTime(), readObjectMember(), setLastVulnerableTime(), and writeObjectMembers().
Vector<uint64> DestructibleBuildingDataComponent::minefieldSlots private
Definition at line 31 of file DestructibleBuildingDataComponent.h.
Referenced by addMinefield(), getIndexOfMinefield(), getMinefieldOID(), getTotalMinefieldCount(), hasMinefield(), isMinefieldSlotOccupied(), readObjectMember(), setActiveMinefield(), setMinefieldID(), and writeObjectMembers().
Time DestructibleBuildingDataComponent::nextVulnerableTime private
Definition at line 35 of file DestructibleBuildingDataComponent.h.
Referenced by getNextVulnerableTime(), readObjectMember(), setNextVulnerableTime(), and writeObjectMembers().
const int DestructibleBuildingDataComponent::OVERLOADED = 6 static
Definition at line 52 of file DestructibleBuildingDataComponent.h.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::abortShutdownSequence(), server::zone::managers::gcw::GCWManagerImplementation::handlePowerRegulatorSwitch(), and server::zone::managers::gcw::GCWManagerImplementation::isPowerOverloaded().
Time DestructibleBuildingDataComponent::placementTime private
Definition at line 37 of file DestructibleBuildingDataComponent.h.
Referenced by getPlacmenetTime(), readObjectMember(), setPlacementTime(), and writeObjectMembers().
const int DestructibleBuildingDataComponent::POWERSWITCHCOUNT = 8 static
Definition at line 56 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), and turnAllSwitchesOn().
Vector<bool> DestructibleBuildingDataComponent::powerSwitchesTester private
Definition at line 29 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), getPowerPosition(), readObjectMember(), turnAllSwitchesOn(), turnSwitchOff(), turnSwitchOn(), and writeObjectMembers().
Time DestructibleBuildingDataComponent::rebootFinishTime private
Definition at line 40 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), getRebootFinishTime(), readObjectMember(), setRebootFinishTime(), and writeObjectMembers().
Time DestructibleBuildingDataComponent::repairTime private
Definition at line 39 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), getSliceRepairTime(), readObjectMember(), setSliceRepairTime(), and writeObjectMembers().
int DestructibleBuildingDataComponent::sampleMatches private
Definition at line 27 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), getSampleMatches(), incrementSampleMatches(), readObjectMember(), setSampleMatches(), and writeObjectMembers().
Vector<uint64> DestructibleBuildingDataComponent::scannerSlots private
Definition at line 32 of file DestructibleBuildingDataComponent.h.
Referenced by addScanner(), getTotalScannerCount(), readObjectMember(), setScannerID(), and writeObjectMembers().
const int DestructibleBuildingDataComponent::SHUTDOWNSEQUENCE = 8 static
Definition at line 54 of file DestructibleBuildingDataComponent.h.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::checkVulnerabilityData(), server::zone::managers::gcw::GCWManagerImplementation::isShutdownSequenceStarted(), server::zone::managers::gcw::GCWManagerImplementation::scheduleBaseDestruction(), and setState().
const int DestructibleBuildingDataComponent::SLICED = 4 static
Definition at line 50 of file DestructibleBuildingDataComponent.h.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::completeSecuritySlice(), and server::zone::managers::gcw::GCWManagerImplementation::isSecurityTermSliced().
int DestructibleBuildingDataComponent::switchesTurnedOn private
Definition at line 28 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), getOnSwitchCount(), readObjectMember(), turnAllSwitchesOn(), turnSwitchOff(), turnSwitchOn(), and writeObjectMembers().
bool DestructibleBuildingDataComponent::terminalDamaged private
Definition at line 25 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), isTerminalDamanged(), readObjectMember(), setTerminalDamaged(), and writeObjectMembers().
Vector<uint64> DestructibleBuildingDataComponent::turretSlots private
Definition at line 30 of file DestructibleBuildingDataComponent.h.
Referenced by addTurret(), getIndexOfTurret(), getTotalTurretCount(), getTurretID(), hasTurret(), isTurretSlotOccupied(), readObjectMember(), setActiveTurret(), setTurretID(), and writeObjectMembers().
int DestructibleBuildingDataComponent::uplinkBand private
Definition at line 41 of file DestructibleBuildingDataComponent.h.
Referenced by DestructibleBuildingDataComponent(), getUplinkBand(), initializeTransientMembers(), and setUplinkBand().
Time DestructibleBuildingDataComponent::vulnerabilityEndTime private
Definition at line 36 of file DestructibleBuildingDataComponent.h.
Referenced by getVulnerabilityEndTime(), readObjectMember(), setVulnerabilityEndTime(), and writeObjectMembers().
const int DestructibleBuildingDataComponent::VULNERABLE = 1 static
Definition at line 47 of file DestructibleBuildingDataComponent.h.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::initializeNewVulnerability(), and isVulnerable().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/building/components/DestructibleBuildingDataComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/building/components/DestructibleBuildingDataComponent.cpp