Core3: server::zone::managers::minigames::FishingSessionImplementation Class Reference
server::zone::managers::minigames::FishingSessionImplementation Class Reference
#include <FishingSession.h>
Public Member Functions
FishingSessionImplementation (CreatureObject *player, FishingEvent *event, SceneObject *marker, int nextAction, int fish, unsigned int boxID, int fishingState, const String &mood)
FishingSessionImplementation (DummyConstructorParameter *param)
void setEvent (FishingEvent *ev)
void setMood (const String &m)
FishingEvent * getEvent ()
void setNextAction (int action)
int getNextAction ()
void setFishBoxID (unsigned int box)
unsigned int getFishBoxID ()
SceneObject * getMarker ()
void setMarker (SceneObject *mar)
int getFish ()
void setFish (int fi)
int getFishingState ()
void setFishingState (int state)
void setPlayer (CreatureObject *pl)
void update (int nextAction, SceneObject *marker, int fish, unsigned int boxID, int fishingState)
String getMoodString ()
operator const FishingSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< FishingSession * > _this
Protected Member Functions
virtual ~FishingSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > player
Reference< FishingEvent * > event
ManagedReference< SceneObject * > marker
int nextAction
int fish
unsigned int boxID
int fishingState
String mood
Friends
class FishingSession
Detailed Description
Definition at line 136 of file FishingSession.h.
Constructor & Destructor Documentation
FishingSessionImplementation::FishingSessionImplementation (CreatureObject * player, FishingEvent * event, SceneObject * marker, int nextAction, int fish, unsigned int boxID, int fishingState, const String & mood)
Definition at line 465 of file FishingSession.cpp.
References _initializeImplementation(), setEvent(), setFish(), setFishBoxID(), setFishingState(), setMarker(), setMood(), setNextAction(), and setPlayer().
FishingSessionImplementation::FishingSessionImplementation (DummyConstructorParameter * param)
Definition at line 267 of file FishingSession.cpp.
References _initializeImplementation().
FishingSessionImplementation::~FishingSessionImplementation () protected virtual
Definition at line 272 of file FishingSession.cpp.
Member Function Documentation
DistributedObjectStub * FishingSessionImplementation::_getStub ()
Definition at line 292 of file FishingSession.cpp.
References _this.
void FishingSessionImplementation::_initializeImplementation () protected
Definition at line 279 of file FishingSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by FishingSessionImplementation().
void FishingSessionImplementation::_serializationHelperMethod () protected
Definition at line 328 of file FishingSession.cpp.
Referenced by _initializeImplementation().
void FishingSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 287 of file FishingSession.cpp.
References _this.
Referenced by server::zone::managers::minigames::FishingSession::FishingSession().
void FishingSessionImplementation::finalize () protected
Definition at line 276 of file FishingSession.cpp.
FishingEvent * FishingSessionImplementation::getEvent ()
Definition at line 495 of file FishingSession.cpp.
References event.
Referenced by server::zone::managers::minigames::FishingSession::getEvent().
int FishingSessionImplementation::getFish ()
Definition at line 530 of file FishingSession.cpp.
References fish.
Referenced by server::zone::managers::minigames::FishingSession::getFish().
unsigned int FishingSessionImplementation::getFishBoxID ()
Definition at line 515 of file FishingSession.cpp.
References boxID.
Referenced by server::zone::managers::minigames::FishingSession::getFishBoxID().
int FishingSessionImplementation::getFishingState ()
Definition at line 540 of file FishingSession.cpp.
References fishingState.
Referenced by server::zone::managers::minigames::FishingSession::getFishingState().
SceneObject * FishingSessionImplementation::getMarker ()
Definition at line 520 of file FishingSession.cpp.
References marker.
Referenced by server::zone::managers::minigames::FishingSession::getMarker().
String FishingSessionImplementation::getMoodString ()
Definition at line 568 of file FishingSession.cpp.
References mood.
Referenced by server::zone::managers::minigames::FishingSession::getMoodString().
int FishingSessionImplementation::getNextAction ()
Definition at line 505 of file FishingSession.cpp.
References nextAction.
Referenced by server::zone::managers::minigames::FishingSession::getNextAction().
void FishingSessionImplementation::lock (bool doLock = true) protected
Definition at line 300 of file FishingSession.cpp.
References _this.
void FishingSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 304 of file FishingSession.cpp.
References _this.
FishingSessionImplementation::operator const FishingSession * ()
Definition at line 296 of file FishingSession.cpp.
void FishingSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 335 of file FishingSession.cpp.
References readObjectMember().
bool FishingSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 354 of file FishingSession.cpp.
References boxID, fish, fishingState, marker, mood, nextAction, and player.
Referenced by readObject().
void FishingSessionImplementation::rlock (bool doLock = true) protected
Definition at line 308 of file FishingSession.cpp.
References _this.
void FishingSessionImplementation::runlock (bool doLock = true) protected
Definition at line 324 of file FishingSession.cpp.
References _this.
void FishingSessionImplementation::setEvent (FishingEvent * ev)
Definition at line 485 of file FishingSession.cpp.
Referenced by FishingSessionImplementation(), and server::zone::managers::minigames::FishingSession::setEvent().
void FishingSessionImplementation::setFish (int fi)
Definition at line 535 of file FishingSession.cpp.
References fish.
Referenced by FishingSessionImplementation(), server::zone::managers::minigames::FishingSession::setFish(), and update().
void FishingSessionImplementation::setFishBoxID (unsigned int box)
Definition at line 510 of file FishingSession.cpp.
References boxID.
Referenced by FishingSessionImplementation(), server::zone::managers::minigames::FishingSession::setFishBoxID(), and update().
void FishingSessionImplementation::setFishingState (int state)
Definition at line 545 of file FishingSession.cpp.
References fishingState.
Referenced by FishingSessionImplementation(), server::zone::managers::minigames::FishingSession::setFishingState(), and update().
void FishingSessionImplementation::setMarker (SceneObject * mar)
Definition at line 525 of file FishingSession.cpp.
References marker.
Referenced by FishingSessionImplementation(), server::zone::managers::minigames::FishingSession::setMarker(), and update().
void FishingSessionImplementation::setMood (const String & m)
Definition at line 490 of file FishingSession.cpp.
References mood.
Referenced by FishingSessionImplementation(), and server::zone::managers::minigames::FishingSession::setMood().
void FishingSessionImplementation::setNextAction (int action)
Definition at line 500 of file FishingSession.cpp.
References nextAction.
Referenced by FishingSessionImplementation(), server::zone::managers::minigames::FishingSession::setNextAction(), and update().
void FishingSessionImplementation::setPlayer (CreatureObject * pl)
Definition at line 550 of file FishingSession.cpp.
References player.
Referenced by FishingSessionImplementation(), and server::zone::managers::minigames::FishingSession::setPlayer().
void FishingSessionImplementation::unlock (bool doLock = true) protected
Definition at line 320 of file FishingSession.cpp.
References _this.
void FishingSessionImplementation::update (int nextAction, SceneObject * marker, int fish, unsigned int boxID, int fishingState)
Definition at line 555 of file FishingSession.cpp.
References setFish(), setFishBoxID(), setFishingState(), setMarker(), and setNextAction().
Referenced by server::zone::managers::minigames::FishingSession::update().
void FishingSessionImplementation::wlock (bool doLock = true) protected
Definition at line 312 of file FishingSession.cpp.
References _this.
void FishingSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 316 of file FishingSession.cpp.
References _this.
void FishingSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 392 of file FishingSession.cpp.
References writeObjectMembers().
int FishingSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 399 of file FishingSession.cpp.
References boxID, fish, fishingState, marker, mood, nextAction, and player.
Referenced by writeObject().
Friends And Related Function Documentation
friend class FishingSession friend
Definition at line 225 of file FishingSession.h.
Member Data Documentation
WeakReference<FishingSession*> server::zone::managers::minigames::FishingSessionImplementation::_this
Definition at line 191 of file FishingSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
unsigned int server::zone::managers::minigames::FishingSessionImplementation::boxID protected
Definition at line 148 of file FishingSession.h.
Referenced by getFishBoxID(), readObjectMember(), setFishBoxID(), and writeObjectMembers().
Reference<FishingEvent* > server::zone::managers::minigames::FishingSessionImplementation::event protected
Definition at line 140 of file FishingSession.h.
Referenced by getEvent().
int server::zone::managers::minigames::FishingSessionImplementation::fish protected
Definition at line 146 of file FishingSession.h.
Referenced by getFish(), readObjectMember(), setFish(), and writeObjectMembers().
int server::zone::managers::minigames::FishingSessionImplementation::fishingState protected
Definition at line 150 of file FishingSession.h.
Referenced by getFishingState(), readObjectMember(), setFishingState(), and writeObjectMembers().
ManagedReference<SceneObject* > server::zone::managers::minigames::FishingSessionImplementation::marker protected
Definition at line 142 of file FishingSession.h.
Referenced by getMarker(), readObjectMember(), setMarker(), and writeObjectMembers().
String server::zone::managers::minigames::FishingSessionImplementation::mood protected
Definition at line 152 of file FishingSession.h.
Referenced by getMoodString(), readObjectMember(), setMood(), and writeObjectMembers().
int server::zone::managers::minigames::FishingSessionImplementation::nextAction protected
Definition at line 144 of file FishingSession.h.
Referenced by getNextAction(), readObjectMember(), setNextAction(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::managers::minigames::FishingSessionImplementation::player protected
Definition at line 138 of file FishingSession.h.
Referenced by readObjectMember(), setPlayer(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingSession.cpp