Core3: server::zone::objects::player::sessions::TradeSessionAdapter Class Reference
server::zone::objects::player::sessions::TradeSessionAdapter Class Reference
#include <TradeSession.h>
Public Member Functions
TradeSessionAdapter (TradeSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
bool getAcceptedTrade ()
void addTradeItem (SceneObject *object)
SceneObject * getTradeItem (int index)
int getTradeSize ()
int getMoneyToTrade ()
unsigned long long getTradeTargetPlayer ()
bool isTryingToTrade ()
bool hasVerifiedTrade ()
void setAcceptedTrade (bool val)
void setMoneyToTrade (int val)
void setTradeTargetPlayer (unsigned long long val)
void setVerifiedTrade (bool val)
Detailed Description
Definition at line 191 of file TradeSession.h.
Constructor & Destructor Documentation
TradeSessionAdapter::TradeSessionAdapter (TradeSession * impl)
Definition at line 483 of file TradeSession.cpp.
Member Function Documentation
void TradeSessionAdapter::addTradeItem (SceneObject * object)
Definition at line 559 of file TradeSession.cpp.
Referenced by invokeMethod().
bool TradeSessionAdapter::getAcceptedTrade ()
Definition at line 555 of file TradeSession.cpp.
Referenced by invokeMethod().
int TradeSessionAdapter::getMoneyToTrade ()
Definition at line 571 of file TradeSession.cpp.
Referenced by invokeMethod().
SceneObject * TradeSessionAdapter::getTradeItem (int index)
Definition at line 563 of file TradeSession.cpp.
Referenced by invokeMethod().
int TradeSessionAdapter::getTradeSize ()
Definition at line 567 of file TradeSession.cpp.
Referenced by invokeMethod().
unsigned long long TradeSessionAdapter::getTradeTargetPlayer ()
Definition at line 575 of file TradeSession.cpp.
Referenced by invokeMethod().
bool TradeSessionAdapter::hasVerifiedTrade ()
Definition at line 583 of file TradeSession.cpp.
Referenced by invokeMethod().
void TradeSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 486 of file TradeSession.cpp.
References addTradeItem(), getAcceptedTrade(), getMoneyToTrade(), getTradeItem(), getTradeSize(), getTradeTargetPlayer(), hasVerifiedTrade(), isTryingToTrade(), RPC_ADDTRADEITEM__SCENEOBJECT_, RPC_GETACCEPTEDTRADE__, RPC_GETMONEYTOTRADE__, RPC_GETTRADEITEM__INT_, RPC_GETTRADESIZE__, RPC_GETTRADETARGETPLAYER__, RPC_HASVERIFIEDTRADE__, RPC_ISTRYINGTOTRADE__, RPC_SETACCEPTEDTRADE__BOOL_, RPC_SETMONEYTOTRADE__INT_, RPC_SETTRADETARGETPLAYER__LONG_, RPC_SETVERIFIEDTRADE__BOOL_, setAcceptedTrade(), setMoneyToTrade(), setTradeTargetPlayer(), and setVerifiedTrade().
bool TradeSessionAdapter::isTryingToTrade ()
Definition at line 579 of file TradeSession.cpp.
Referenced by invokeMethod().
void TradeSessionAdapter::setAcceptedTrade (bool val)
Definition at line 587 of file TradeSession.cpp.
Referenced by invokeMethod().
void TradeSessionAdapter::setMoneyToTrade (int val)
Definition at line 591 of file TradeSession.cpp.
Referenced by invokeMethod().
void TradeSessionAdapter::setTradeTargetPlayer (unsigned long long val)
Definition at line 595 of file TradeSession.cpp.
Referenced by invokeMethod().
void TradeSessionAdapter::setVerifiedTrade (bool val)
Definition at line 599 of file TradeSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TradeSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TradeSession.cpp