Core3: LuaContainerComponent Class Reference
LuaContainerComponent Class Reference
#include <LuaContainerComponent.h>
Public Member Functions
LuaContainerComponent (String className)
~LuaContainerComponent ()
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
virtual int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Public Member Functions inherited from ContainerComponent
virtual bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
Public Attributes
String luaClassName
Detailed Description
Definition at line 33 of file LuaContainerComponent.h.
Constructor & Destructor Documentation
LuaContainerComponent::LuaContainerComponent (String className)
Definition at line 13 of file LuaContainerComponent.cpp.
References luaClassName.
LuaContainerComponent::~LuaContainerComponent ()
Definition at line 17 of file LuaContainerComponent.cpp.
Member Function Documentation
int LuaContainerComponent::canAddObject (SceneObject * sceneObject, SceneObject * object, int containmentType, String & errorDescription) virtual
Evaluates if this object has the necessary free slots to be able to add the specified SceneObject
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be checked
error error string that the player will receive on error
Returns
returns 0 on success, or error code
Reimplemented from ContainerComponent.
Definition at line 20 of file LuaContainerComponent.cpp.
References ContainerComponent::canAddObject(), TransferErrorCode::CANTADDTOITSELF, and luaClassName.
int LuaContainerComponent::notifyObjectInserted (SceneObject * sceneObject, SceneObject * object) virtual
Is called when this object has been inserted with an object
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 96 of file LuaContainerComponent.cpp.
References ContainerComponent::notifyObjectInserted().
int LuaContainerComponent::notifyObjectRemoved (SceneObject * sceneObject, SceneObject * object, SceneObject * destination) virtual
Is called when an object was removed
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 104 of file LuaContainerComponent.cpp.
References ContainerComponent::notifyObjectRemoved().
bool LuaContainerComponent::removeObject (SceneObject * sceneObject, SceneObject * object, SceneObject * destination, bool notifyClient) virtual
Tries to remove/unlink object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be removed from the current object
notifyClient not used currently
Returns
returns true if the object has been successfully removed
Reimplemented from ContainerComponent.
Definition at line 69 of file LuaContainerComponent.cpp.
References luaClassName, and ContainerComponent::removeObject().
bool LuaContainerComponent::transferObject (SceneObject * sceneObject, SceneObject * object, int containmentType, bool notifyClient = false, bool allowOverflow = false) virtual
Tries to add/link object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be added to the current object
containmentType arrangement type that will be used to add the object
notifyClient if true in range objects will be updated with the change
Returns
returns true if the object has been successfully added
Reimplemented from ContainerComponent.
Definition at line 46 of file LuaContainerComponent.cpp.
References luaClassName, and ContainerComponent::transferObject().
Member Data Documentation
String LuaContainerComponent::luaClassName
Definition at line 36 of file LuaContainerComponent.h.
Referenced by canAddObject(), LuaContainerComponent(), removeObject(), and transferObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/components/LuaContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/components/LuaContainerComponent.cpp