Core3: server::zone::objects::creature::CreatureObjectImplementation Class Reference
server::zone::objects::creature::CreatureObjectImplementation Class Reference
#include <CreatureObject.h>
Public Member Functions
CreatureObjectImplementation ()
CreatureObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
void finalize ()
void createChildObjects ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void clearQueueAction (unsigned int actioncntr, float timer=0, unsigned int tab1=0, unsigned int tab2=0)
void sendBaselinesTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendTo (SceneObject *player, bool doClose)
void sendSystemMessage (const String &message)
void playMusicMessage (const String &file)
void sendNewbieTutorialRequest (const String &request)
void sendNewbieTutorialEnableHudElement (const String &ui, bool enable=true)
void sendOpenHolocronToPageMessage ()
void sendSystemMessage (UnicodeString &message)
void sendSystemMessage (StringIdChatParameter &stringid)
void sendSlottedObjectsTo (SceneObject *player)
void setCombatState ()
void clearCombatState (bool clearDefenders=true)
virtual void setPosture (int newPosture, bool notifyClient=true)
float calculateSpeed ()
virtual void updateLocomotion ()
void setHeight (float heigh, bool notifyClient=true)
void setAccelerationMultiplierBase (float newMultiplierBase, bool notifyClient=true)
void setAccelerationMultiplierMod (float newMultiplierMod, bool notifyClient=true)
void setSpeedMultiplierBase (float newMultiplierBase, bool notifyClient=true)
virtual void setSpeedMultiplierMod (float newMultiplierMod, bool notifyClient=true)
virtual void setTurnScale (float newMultiplierMod, bool notifyClient=true)
void setRunSpeed (float newSpeed, bool notifyClient=true)
void setCurrentSpeed (float newSpeed)
void setHAM (int type, int value, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
bool hasDamage (int attribute)
int healDamage (TangibleObject *healer, int damageType, int damage, bool notifyClient=true, bool notifyObservers=true)
int healWound (TangibleObject *healer, int damageType, int damage, bool notifyClient=true, bool notifyObservers=true)
void setBaseHAM (int type, int value, bool notifyClient=true)
void setWounds (int type, int value, bool notifyClient=true)
int addWounds (int type, int value, bool notifyClient=true)
void setMaxHAM (int type, int value, bool notifyClient=true)
void addMaxHAM (int type, int value, bool notifyClient=true)
void setEncumbrance (int type, int value, bool notifyClient=true)
void addEncumbrance (int type, int value, bool notifyClient=true)
void setWeapon (WeaponObject *weao, bool notifyClient=false)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void setInstrumentID (int instrumentid, bool notifyClient=true)
void setListenToID (unsigned long long id, bool notifyClient=true)
void setPerformanceCounter (int counter, bool notifyClient=true)
void setPerformanceAnimation (const String &animation, bool notifyClient=true)
void setShockWounds (int newShock, bool notifyClient=true)
void addShockWounds (int shockToAdd, bool notiyClient=true)
void setTargetID (unsigned long long targetID, bool notifyClient=true)
void setBankCredits (int credits, bool notifyClient=true)
void addBuff (Buff *buff)
bool removeBuff (unsigned int buffcrc)
void removeBuff (Buff *buff)
bool removeStateBuff (unsigned long long state)
void clearBuffs (bool updateclient)
void addWearableObject (TangibleObject *object, bool notifyClient=true)
void removeWearableObject (TangibleObject *object, bool notifyClient=true)
WearablesDeltaVector * getWearablesDeltaVector ()
void sendBuffsTo (CreatureObject *creature)
BuffList * getBuffList ()
Buff * getBuff (unsigned int buffcrc)
long long getSkillModFromBuffs (const String &skillMod)
int addDotState (unsigned long long dotType, unsigned long long objectID, unsigned int strength, byte type, unsigned int duration, float potency, unsigned int defense, int secondaryStrength=0)
bool healDot (unsigned long long dotType, int reduction)
void clearDots ()
DamageOverTimeList * getDamageOverTimeList ()
bool hasBuff (unsigned int buffcrc)
void notifySelfPositionUpdate ()
void notifyPostureChange (int newPosture)
void setLevel (int level)
void updateToDatabaseAllObjects (bool startTask)
bool isResuscitable ()
void addBankCredits (int credits, bool notifyClient=true)
void addCashCredits (int credits, bool notifyClient=true)
void subtractBankCredits (int credits)
void subtractCashCredits (int credits)
bool verifyCashCredits (int credits)
bool verifyBankCredits (int credits)
bool isDancing ()
bool isPlayingMusic ()
void stopEntertaining ()
bool isEntertaining ()
void setCashCredits (int credits, bool notifyClient=true)
void setTerrainNegotiation (float value, bool notifyClient=true)
void addSkill (Skill *skill, bool notifyClient=true)
void addSkill (const String &skill, bool notifyClient=true)
void removeSkill (Skill *skill, bool notifyClient=true)
void removeSkill (const String &skill, bool notifyClient=true)
void addSkillMod (const int modType, const String &skillMod, int value, bool notifyClient=true)
void removeSkillMod (const int modType, const String &skillMod, int value, bool notifyClient=true)
void removeAllSkillModsOfType (const int modType, bool notifyClient=true)
void updateGroupInviterID (unsigned long long id, bool notifyClient=true)
void updateGroup (GroupObject *group, bool notifyClient=true)
void enqueueCommand (unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString &arguments, int priority=-1)
void setMood (byte moodID, bool notifyClient=true)
void setMoodString (const String &animation, bool notifyClient=true)
void deleteQueueAction (unsigned int actionCount)
bool setState (unsigned long long state, bool notifyClient=true)
bool clearState (unsigned long long state, bool notifyClient=true)
void setControlDevice (ControlDevice *device)
void setCreatureLink (CreatureObject *object, bool notifyClient=true)
void executeObjectControllerAction (unsigned int actionCRC)
void executeObjectControllerAction (unsigned int actionCRC, unsigned long long targetID, const UnicodeString &args)
bool isAttackableBy (CreatureObject *object)
bool isAttackableBy (TangibleObject *attacker)
bool isHealableBy (CreatureObject *object)
bool isInBountyMission (CreatureObject *bountyHunter, CreatureObject *target)
virtual void sendConversationStartTo (SceneObject *player)
virtual void selectConversationOption (int option, SceneObject *obj)
void sendMessage (BasePacket *msg)
void sendExecuteConsoleCommand (const String &command)
bool isAggressiveTo (CreatureObject *object)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
int notifyObjectKillObservers (TangibleObject *killer)
void notifyLoadFromDatabase ()
void setFactionRank (int rank, bool notifyClient=true)
String getFirstName ()
String getLastName ()
bool isOnline ()
bool canTreatInjuries ()
bool canTreatStates ()
bool canTreatWounds ()
bool canTreatConditions ()
Reference< PlayerObject * > getPlayerObject ()
AiActor * getActorObject ()
bool isListening ()
bool isWatching ()
void setClient (ZoneClientSession *cli)
void dismount ()
float calculateBFRatio ()
void setDizziedState (int durationSeconds=5)
void setRalliedState (int durationSeconds=5)
void setAimingState (int durationSeconds=5)
void setCoverState (int durationSeconds=40)
void setBerserkedState (unsigned int duration)
void setStunnedState (int durationSeconds=5)
void setBlindedState (int durationSeconds=5)
void setIntimidatedState (unsigned int mod, int durationSeconds=15)
void setSnaredState (int durationSeconds=20)
void setRootedState (int durationSeconds=20)
bool setNextAttackDelay (unsigned int mod, int del)
void setMeditateState ()
virtual void activateHAMRegeneration ()
virtual void activatePassiveWoundRegeneration ()
virtual void activateStateRecovery ()
void updateTimeOfDeath ()
bool hasAttackDelay ()
void removeAttackDelay ()
CooldownTimerMap * getCooldownTimerMap ()
bool hasSpice ()
void updateLastSuccessfulCombatAction ()
void updateKnockdownRecovery ()
virtual void queueDizzyFallEvent ()
void updateLastKnockdown ()
bool checkKnockdownRecovery ()
bool checkLastKnockdown ()
void updatePostureDownRecovery ()
void updatePostureUpRecovery ()
bool checkPostureDownRecovery ()
unsigned long long getScreenPlayState (const String &screenPlay)
void setScreenPlayState (const String &screenPlay, unsigned long long state)
bool checkPostureUpRecovery ()
void updateCooldownTimer (const String &coooldownTimer, unsigned int miliSecondsToAdd=0)
bool checkCooldownRecovery (const String &cooldown)
Time * getCooldownTime (const String &cooldown)
void addCooldown (const String &name, unsigned int miliseconds)
void doAnimation (const String &animation)
void doCombatAnimation (CreatureObject *defender, unsigned int animationCRC, byte hit, byte trails)
void playEffect (const String &file, const String &aux)
void playEffect (const String &file)
void activateQueueAction ()
void activateImmediateAction ()
UnicodeString getCreatureName ()
bool isGrouped ()
int getBankCredits ()
int getCashCredits ()
int getBaseHAM (int idx)
int getWounds (int idx)
DeltaVector< int > * getWounds ()
int getHAM (int idx)
DeltaVector< int > * getHAM ()
int getMaxHAM (int idx)
DeltaVector< int > * getMaxHAM ()
int getEncumbrance (int idx)
DeltaVector< int > * getEncumbrances ()
byte getPosture ()
byte getLocomotion ()
byte getFactionRank ()
ManagedWeakReference
< CreatureObject * > getLinkedCreature ()
unsigned long long getCreatureLinkID ()
float getShockWounds ()
unsigned long long getWatchToID ()
unsigned long long getStateBitmask ()
bool hasState (unsigned long long state)
bool hasStates ()
unsigned long long getListenID ()
float getAccelerationMultiplierBase ()
float getAccelerationMultiplierMod ()
float getSpeedMultiplierBase ()
float getSpeedMultiplierMod ()
float getCurrentSpeed ()
SpeedMultiplierModChanges * getSpeedMultiplierModChanges ()
CommandQueueActionVector * getCommandQueue ()
float getRunSpeed ()
float getWalkSpeed ()
float getTurnScale ()
float getTerrainNegotiation ()
float getRunAcceleration ()
float getWalkAcceleration ()
String getPerformanceAnimation ()
String getMoodString ()
unsigned long long getWeaponID ()
Reference< WeaponObject * > getWeapon ()
Reference< GuildObject * > getGuildObject ()
int getGuildID ()
bool isInGuild ()
void setGuildObject (GuildObject *guildobj)
unsigned long long getGroupID ()
unsigned long long getGroupInviterID ()
GroupObject * getGroup ()
unsigned long long getGroupInviteCounter ()
unsigned long long getTargetID ()
byte getMoodID ()
float getSlopeModPercent ()
int getPerformanceCounter ()
int getInstrumentID ()
byte getFrozen ()
float getHeight ()
int getSpecies ()
String getSpeciesName ()
int getGender ()
DeltaVector< int > * getBaseHAM ()
SkillList * getSkillList ()
int getSkillMod (const String &skillmod)
bool hasSkill (const String &skill)
SkillModList * getSkillModList ()
void setWatchToID (unsigned long long id)
bool isCreatureObject ()
bool isNextActionPast ()
virtual bool isTrainerCreature ()
bool isSwimming ()
ZoneClientSession * getClient ()
bool isRidingMount ()
ManagedWeakReference
< ControlDevice * > getControlDevice ()
float getSwimHeight ()
bool isIncapacitated ()
bool isDead ()
bool isKnockedDown ()
bool isKneeling ()
bool isProne ()
bool isStanding ()
bool isSitting ()
bool isSkillAnimating ()
bool isRallied ()
bool isInCombat ()
bool isDizzied ()
bool isBerserked ()
bool isStunned ()
bool isBlinded ()
bool isIntimidated ()
bool isSnared ()
bool isImmobilized ()
bool isRooted ()
bool isFrozen ()
bool isDiseased ()
bool isPoisoned ()
bool isBleeding ()
bool isOnFire ()
bool isMounted ()
bool isRidingCreature ()
bool isPeaced ()
bool isMeditating ()
bool isAiming ()
bool isInCover ()
bool isRunning ()
virtual bool isNonPlayerCreatureObject ()
virtual bool isCreature ()
bool isPlayerCreature ()
bool isAiActor ()
virtual bool isInformantCreature ()
CampSiteActiveArea * getCurrentCamp ()
byte getCurrentWeather ()
void setCurrentWeather (byte value)
byte getCurrentWind ()
void setCurrentWind (byte value)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void destroyObjectFromWorld (bool sendSelfDestroy)
bool isInvisible ()
void setInvisible (bool invis)
Mutex * getSkillModMutex ()
float calculateCostAdjustment (byte stat, float baseCost)
void updateSpeedAndAccelerationMods ()
operator const CreatureObject * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
TangibleObjectImplementation ()
TangibleObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
virtual void addTemplateSkillMods (TangibleObject *targetObject)
virtual void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
virtual void removeSkillModsFrom (CreatureObject *creature)
virtual void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
virtual void setDefender (SceneObject *defender)
virtual void addDefender (SceneObject *defender)
virtual void removeDefender (SceneObject *defender)
virtual void removeDefenders ()
virtual void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
bool hasDefender (SceneObject *defender)
virtual void sendPvpStatusTo (CreatureObject *player)
virtual int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
virtual void updateCraftingValues (CraftingValues *values, bool firstUpdate)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
virtual bool isKiller ()
virtual bool isTicketCollector ()
virtual bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
virtual int getUseCount ()
virtual int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
virtual bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
virtual String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
virtual int getJunkDealerNeeded ()
void setJunkValue (int jValue)
virtual int getJunkValue ()
void setSerialNumber (const String &serial)
virtual String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
virtual String repairAttempt (int repairChance)
bool isBroken ()
virtual float getHitChance ()
void broadcastPvpStatusBitmask ()
operator const TangibleObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< CreatureObject * > _this
Public Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
WeakReference< TangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Static Public Attributes
static const int HUMAN = 0
static const int RODIAN = 1
static const int TRANDOSHAN = 2
static const int MONCAL = 3
static const int WOOKIE = 4
static const int BOTHAN = 5
static const int TWILEK = 6
static const int ZABRAK = 7
static const int ITHORIAN = 0x21
static const int SULLUSTAN = 0x31
static const int MALE = 0
static const int FEMALE = 1
static float DEFAULTRUNSPEED = 5.376
static unsigned const long long DEAD_TOO_LONG = 1800000
Protected Member Functions
virtual ~CreatureObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
float getConditionReduction (float value)
virtual ~TangibleObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference
< ZoneClientSession * > owner
int bankCredits
int cashCredits
int gender
int species
DeltaVector< int > baseHAM
byte posture
byte locomotion
byte factionRank
bool invisible
ManagedWeakReference
< CreatureObject * > linkedCreature
ManagedWeakReference
< ControlDevice * > controlDevice
float shockWounds
DeltaVector< int > wounds
unsigned long long stateBitmask
DeltaVector< int > encumbrances
WearablesDeltaVector wearablesVector
float accelerationMultiplierBase
float accelerationMultiplierMod
float speedMultiplierBase
SpeedMultiplierModChanges speedMultiplierModChanges
float speedMultiplierMod
float turnScale
float runSpeed
float walkSpeed
float currentSpeed
float terrainNegotiation
float runAcceleration
float walkAcceleration
float height
float swimHeight
float slopeModPercent
float slopeModAngle
unsigned long long listenToID
unsigned long long watchToID
String performanceAnimation
String moodString
ManagedReference< WeaponObject * > weapon
ManagedReference< GroupObject * > group
unsigned long long groupInviterID
unsigned long long groupInviteCounter
ManagedReference< GuildObject * > guild
unsigned long long targetID
byte moodID
int performanceCounter
int instrumentID
DeltaVector< int > hamList
DeltaVector< int > maxHamList
byte frozen
String templateString
SkillList skillList
SkillModList skillModList
Mutex skillModMutex
Reference
< CommandQueueActionVector * > commandQueue
Reference
< CommandQueueActionVector * > immediateQueue
Time nextAction
Reference< CooldownTimerMap * > cooldownTimerMap
BuffList creatureBuffs
DamageOverTimeList damageOverTimeList
Time lastSuccessfulCombatAction
Time timeOfDeath
VectorMap< String, unsigned
long long > screenPlayStates
byte healthWoundHeal
byte actionWoundHeal
byte mindWoundHeal
byte currentWeather
byte currentWind
Time lastCombatActionTime
Vector3 lastCombatPosition
Protected Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
bool targetable
float complexity
int volume
unsigned int faction
CustomizationVariables customizationVariables
float conditionDamage
int maxCondition
int useCount
short level
unsigned int optionsBitmask
unsigned int pvpStatusBitmask
byte unknownByte
String craftersName
int junkDealerNeeded
int junkValue
String objectSerial
Reference< ThreatMap * > threatMap
DeltaVector< ManagedReference
< SceneObject * > > defenderList
bool sliceable
bool sliced
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Friends
class CreatureObject
Detailed Description
Definition at line 1419 of file CreatureObject.h.
Constructor & Destructor Documentation
CreatureObjectImplementation::CreatureObjectImplementation ()
Definition at line 4917 of file CreatureObject.cpp.
References _initializeImplementation(), and initializeMembers().
CreatureObjectImplementation::CreatureObjectImplementation (DummyConstructorParameter * param)
Definition at line 4109 of file CreatureObject.cpp.
References _initializeImplementation().
CreatureObjectImplementation::~CreatureObjectImplementation () protected virtual
Definition at line 4114 of file CreatureObject.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * CreatureObjectImplementation::_getStub ()
Definition at line 4132 of file CreatureObject.cpp.
References _this.
void CreatureObjectImplementation::_initializeImplementation () protected
Definition at line 4119 of file CreatureObject.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CreatureObjectImplementation().
void CreatureObjectImplementation::_serializationHelperMethod () protected
Definition at line 4168 of file CreatureObject.cpp.
Referenced by _initializeImplementation(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::_serializationHelperMethod(), server::zone::objects::creature::VehicleObjectImplementation::_serializationHelperMethod(), and server::zone::objects::creature::AiAgentImplementation::_serializationHelperMethod().
void CreatureObjectImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 4127 of file CreatureObject.cpp.
References _this.
Referenced by server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::_setStub(), server::zone::objects::creature::VehicleObjectImplementation::_setStub(), server::zone::objects::creature::AiAgentImplementation::_setStub(), and server::zone::objects::creature::CreatureObject::CreatureObject().
void CreatureObjectImplementation::activateHAMRegeneration () virtual
Definition at line 2217 of file CreatureObjectImplementation.cpp.
References _this, CreatureAttribute::ACTION, activatePassiveWoundRegeneration(), CreatureAttribute::CONSTITUTION, getHAM(), healDamage(), CreatureAttribute::HEALTH, isDead(), isIncapacitated(), isKneeling(), isPlayerCreature(), isSitting(), CreatureAttribute::MIND, CreatureAttribute::STAMINA, and CreatureAttribute::WILLPOWER.
Referenced by server::zone::objects::creature::CreatureObject::activateHAMRegeneration(), and server::zone::objects::creature::AiAgentImplementation::doRecovery().
void CreatureObjectImplementation::activateImmediateAction ()
Definition at line 1706 of file CreatureObjectImplementation.cpp.
References _this, server::zone::managers::objectcontroller::ObjectController::activateCommand(), server::zone::ZoneServer::getObjectController(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), CommandQueueActionEvent::IMMEDIATE, and immediateQueue.
Referenced by server::zone::objects::creature::CreatureObject::activateImmediateAction().
void CreatureObjectImplementation::activatePassiveWoundRegeneration () virtual
Health wound regen
Action wound regen
Mind wound regen
Definition at line 2288 of file CreatureObjectImplementation.cpp.
References _this, CreatureAttribute::ACTION, actionWoundHeal, CreatureAttribute::CONSTITUTION, CreatureAttribute::FOCUS, getSkillMod(), CreatureAttribute::HEALTH, healthWoundHeal, healWound(), CreatureAttribute::MIND, mindWoundHeal, CreatureAttribute::QUICKNESS, CreatureAttribute::STAMINA, CreatureAttribute::STRENGTH, and CreatureAttribute::WILLPOWER.
Referenced by activateHAMRegeneration(), and server::zone::objects::creature::CreatureObject::activatePassiveWoundRegeneration().
void CreatureObjectImplementation::activateQueueAction ()
Definition at line 1728 of file CreatureObjectImplementation.cpp.
References _this, server::zone::managers::objectcontroller::ObjectController::activateCommand(), commandQueue, server::zone::ZoneServer::getObjectController(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), and nextAction.
Referenced by server::zone::objects::creature::CreatureObject::activateQueueAction(), and enqueueCommand().
void CreatureObjectImplementation::activateStateRecovery () virtual
Definition at line 2139 of file CreatureObjectImplementation.cpp.
References _this, DamageOverTimeList::activateDots(), damageOverTimeList, DamageOverTimeList::hasDot(), and DamageOverTimeList::isNextTickPast().
Referenced by server::zone::objects::creature::CreatureObject::activateStateRecovery(), and server::zone::objects::creature::AiAgentImplementation::doRecovery().
void CreatureObjectImplementation::addBankCredits (int credits, bool notifyClient = true)
Definition at line 4993 of file CreatureObject.cpp.
References bankCredits, and setBankCredits().
Referenced by server::zone::objects::creature::CreatureObject::addBankCredits().
void CreatureObjectImplementation::addBuff (Buff * buff)
Adds the buff to the creature, activating it and sending packets if it is a player. Buffs should never be added to the list without sending of packets.
Parameters
buff The Buff object to add the creature.
Definition at line 2157 of file CreatureObjectImplementation.cpp.
References BuffList::addBuff(), creatureBuffs, and server::zone::objects::creature::buffs::Buff::getBuffCRC().
Referenced by server::zone::objects::creature::CreatureObject::addBuff(), setAimingState(), setBerserkedState(), setBlindedState(), setCoverState(), setDizziedState(), setIntimidatedState(), setRalliedState(), setRootedState(), setSnaredState(), and setStunnedState().
void CreatureObjectImplementation::addCashCredits (int credits, bool notifyClient = true)
Definition at line 5000 of file CreatureObject.cpp.
References cashCredits, and setCashCredits().
Referenced by server::zone::objects::creature::CreatureObject::addCashCredits().
void CreatureObjectImplementation::addCooldown (const String & name, unsigned int miliseconds)
Definition at line 5196 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::addCooldown().
int CreatureObjectImplementation::addDotState (unsigned long long dotType, unsigned long long objectID, unsigned int strength, byte type, unsigned int duration, float potency, unsigned int defense, int secondaryStrength = 0)
Definition at line 4968 of file CreatureObject.cpp.
References _this, and damageOverTimeList.
Referenced by server::zone::objects::creature::CreatureObject::addDotState().
void CreatureObjectImplementation::addEncumbrance (int type, int value, bool notifyClient = true)
Definition at line 1110 of file CreatureObjectImplementation.cpp.
References encumbrances, server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::objects::scene::variables::DeltaVector< E >::get(), setEncumbrance(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
Referenced by server::zone::objects::creature::CreatureObject::addEncumbrance().
void CreatureObjectImplementation::addMaxHAM (int type, int value, bool notifyClient = true)
Definition at line 1097 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::objects::scene::variables::DeltaVector< E >::get(), maxHamList, setMaxHAM(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
Referenced by server::zone::objects::creature::CreatureObject::addMaxHAM().
void CreatureObjectImplementation::addShockWounds (int shockToAdd, bool notiyClient = true)
Definition at line 580 of file CreatureObjectImplementation.cpp.
References setShockWounds(), and shockWounds.
Referenced by server::zone::objects::creature::CreatureObject::addShockWounds().
void CreatureObjectImplementation::addSkill (Skill * skill, bool notifyClient = true)
Adds the specified skillbox to this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified skillbox in the delta vector
Parameters
skillbox skillbox to add
notifyClient if set true the client will be updated with the changes
Definition at line 1157 of file CreatureObjectImplementation.cpp.
References SkillList::add(), DeltaMessage::close(), server::zone::objects::scene::variables::DeltaVector< E >::contains(), sendMessage(), skillList, and DeltaMessage::startUpdate().
Referenced by server::zone::objects::creature::CreatureObject::addSkill(), and addSkill().
void CreatureObjectImplementation::addSkill (const String & skill, bool notifyClient = true)
Adds the specified skillbox to this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified skillbox in the delta vector
Parameters
skillbox skillbox name to add
notifyClient if set true the client will be updated with the changes
Definition at line 1266 of file CreatureObjectImplementation.cpp.
References addSkill(), server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::managers::skill::SkillManager::getSkill(), and server::zone::objects::scene::SceneObjectImplementation::server.
void CreatureObjectImplementation::addSkillMod (const int modType, const String & skillMod, int value, bool notifyClient = true) virtual
Adds new value to the specified skillmod (add a negative number to subtract)
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
skillMod skill mod to change
value value to add/subtract
notifyClient if set true the client will be updated with the changes
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 1205 of file CreatureObjectImplementation.cpp.
References _this, SkillModList::add(), DeltaMessage::close(), DeltaVectorMap< K, V >::contains(), DeltaVectorMap< K, V >::drop(), DeltaVectorMap< K, V >::get(), SkillModEntry::getTotalSkill(), SkillModList::getVisibleSkillMod(), sendMessage(), DeltaVectorMap< K, V >::set(), skillModList, skillModMutex, and DeltaMessage::startUpdate().
Referenced by server::zone::objects::creature::CreatureObject::addSkillMod(), and removeSkillMod().
void CreatureObjectImplementation::addWearableObject (TangibleObject * object, bool notifyClient = true)
Definition at line 2670 of file CreatureObjectImplementation.cpp.
References _this, WearablesDeltaVector::add(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), server::zone::objects::scene::variables::DeltaVector< E >::contains(), DeltaMessage::startUpdate(), and wearablesVector.
Referenced by server::zone::objects::creature::CreatureObject::addWearableObject().
int CreatureObjectImplementation::addWounds (int type, int value, bool notifyClient = true)
Returns
returns wounds added
Definition at line 1029 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::objects::scene::variables::DeltaVector< E >::get(), setWounds(), server::zone::objects::scene::variables::DeltaVector< E >::size(), and wounds.
Referenced by server::zone::objects::creature::CreatureObject::addWounds().
float CreatureObjectImplementation::calculateBFRatio ()
Definition at line 1947 of file CreatureObjectImplementation.cpp.
References shockWounds.
Referenced by server::zone::objects::creature::CreatureObject::calculateBFRatio().
float CreatureObjectImplementation::calculateCostAdjustment (byte stat, float baseCost)
Definition at line 2732 of file CreatureObjectImplementation.cpp.
References getHAM().
Referenced by server::zone::objects::creature::CreatureObject::calculateCostAdjustment().
float CreatureObjectImplementation::calculateSpeed ()
checks locomotion and sets a new one if appropriate
Precondition
{ this object is locked }
Postcondition
{this object is locked, this object has the new locomotion set, if appropriate }
Definition at line 1341 of file CreatureObjectImplementation.cpp.
References lastCombatActionTime, and lastCombatPosition.
Referenced by server::zone::objects::creature::CreatureObject::calculateSpeed().
bool CreatureObjectImplementation::canTreatConditions ()
Definition at line 5073 of file CreatureObject.cpp.
Referenced by server::zone::objects::creature::CreatureObject::canTreatConditions().
bool CreatureObjectImplementation::canTreatInjuries ()
Definition at line 5058 of file CreatureObject.cpp.
Referenced by server::zone::objects::creature::CreatureObject::canTreatInjuries().
bool CreatureObjectImplementation::canTreatStates ()
Definition at line 5063 of file CreatureObject.cpp.
Referenced by server::zone::objects::creature::CreatureObject::canTreatStates().
bool CreatureObjectImplementation::canTreatWounds ()
Definition at line 5068 of file CreatureObject.cpp.
Referenced by server::zone::objects::creature::CreatureObject::canTreatWounds().
bool CreatureObjectImplementation::checkCooldownRecovery (const String & cooldown)
Definition at line 5186 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::checkCooldownRecovery().
bool CreatureObjectImplementation::checkKnockdownRecovery ()
Definition at line 5133 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::checkKnockdownRecovery().
bool CreatureObjectImplementation::checkLastKnockdown ()
Definition at line 5138 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::checkLastKnockdown().
bool CreatureObjectImplementation::checkPostureDownRecovery ()
Definition at line 5153 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::checkPostureDownRecovery().
bool CreatureObjectImplementation::checkPostureUpRecovery ()
Definition at line 5168 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::checkPostureUpRecovery().
void CreatureObjectImplementation::clearBuffs (bool updateclient)
Removes all buffs from the creature, deactivating any currently active buffs.
Parameters
updateclient Should packets be sent to the player?
Definition at line 2181 of file CreatureObjectImplementation.cpp.
References BuffList::clearBuffs(), and creatureBuffs.
Referenced by server::zone::objects::creature::CreatureObject::clearBuffs().
void CreatureObjectImplementation::clearCombatState (bool clearDefenders = true) virtual
Cleares the combat state
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object is not in a combat state }
Parameters
clearDefenders if true the defender vector willl be emptied
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 634 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), CreatureState::COMBAT, getActorObject(), isAiActor(), server::zone::objects::creature::ai::AiActor::next(), CreatureState::PEACE, server::zone::objects::tangible::TangibleObjectImplementation::removeDefenders(), stateBitmask, and CreatureObjectDeltaMessage3::updateState().
Referenced by server::zone::objects::creature::CreatureObject::clearCombatState(), and server::zone::objects::creature::AiAgentImplementation::clearCombatState().
void CreatureObjectImplementation::clearDots ()
Definition at line 4978 of file CreatureObject.cpp.
References _this, and damageOverTimeList.
Referenced by server::zone::objects::creature::CreatureObject::clearDots().
void CreatureObjectImplementation::clearQueueAction (unsigned int actioncntr, float timer = 0, unsigned int tab1 = 0, unsigned int tab2 = 0)
Sends a CommandQueueRemove ObjectControllerMessage to the owner client of this object
Precondition
{ }
Postcondition
{ client received the CommandQueueRemove message }
Parameters
actioncntr action id that will be cleared from clients queue
timer how many seconds will the action take to execute
tab1 message 1
tab2 message 2
Definition at line 475 of file CreatureObjectImplementation.cpp.
References _this, isPlayerCreature(), and sendMessage().
Referenced by server::zone::objects::creature::CreatureObject::clearQueueAction(), and enqueueCommand().
bool CreatureObjectImplementation::clearState (unsigned long long state, bool notifyClient = true)
Cleares a state from the state bitmask
Precondition
{ this object is locked }
Postcondition
{ this object is locked, stateBitmask doesnt have the specified state }
Parameters
state state to clear
Definition at line 764 of file CreatureObjectImplementation.cpp.
References _this, CreatureState::AIMING, CreatureState::BERSERK, CreatureState::BLEEDING, CreatureState::BLINDED, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), CreatureState::COVER, CreatureState::DISEASED, CreatureState::DIZZY, CreatureState::FROZEN, hasBuff(), CreatureState::IMMOBILIZED, CreatureState::INTIMIDATED, CreatureState::ONFIRE, CreatureState::POISONED, CreatureState::RALLIED, removeBuff(), sendSystemMessage(), server::zone::objects::scene::SceneObjectImplementation::showFlyText(), stateBitmask, CreatureState::STUNNED, and CreatureObjectDeltaMessage3::updateState().
Referenced by server::zone::objects::creature::CreatureObject::clearState(), notifyLoadFromDatabase(), and setPosture().
void CreatureObjectImplementation::createChildObjects () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 2641 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::childObjects, server::zone::ZoneServer::createObject(), ChildObject::getContainmentType(), server::zone::objects::scene::SceneObjectImplementation::getObjectID(), ChildObject::getTemplateFile(), server::zone::objects::scene::SceneObjectImplementation::server, server::zone::objects::scene::variables::ContainerPermissions::setDefaultDenyPermission(), server::zone::objects::scene::variables::ContainerPermissions::setDenyPermission(), server::zone::objects::scene::variables::ContainerPermissions::setInheritPermissionsFromParent(), server::zone::objects::scene::variables::ContainerPermissions::setOwner(), server::zone::objects::scene::SceneObjectImplementation::templateObject, and server::zone::objects::scene::SceneObjectImplementation::transferObject().
Referenced by server::zone::objects::creature::CreatureObject::createChildObjects().
void CreatureObjectImplementation::deleteQueueAction (unsigned int actionCount)
Removes a command from queue
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
actionCount the action count to remove
Definition at line 1769 of file CreatureObjectImplementation.cpp.
References commandQueue, and CommandQueueAction::getActionCounter().
Referenced by server::zone::objects::creature::CreatureObject::deleteQueueAction().
void CreatureObjectImplementation::destroyObjectFromWorld (bool sendSelfDestroy) virtual
Destroys the object from the world
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 5811 of file CreatureObject.cpp.
References getActorObject(), server::zone::objects::scene::SceneObjectImplementation::getZone(), isAiActor(), and server::zone::objects::creature::ai::AiActor::notifyDespawn().
Referenced by server::zone::objects::creature::AiAgentImplementation::destroyObjectFromWorld(), and server::zone::objects::creature::CreatureObject::destroyObjectFromWorld().
void CreatureObjectImplementation::dismount ()
Definition at line 1943 of file CreatureObjectImplementation.cpp.
References executeObjectControllerAction().
Referenced by server::zone::objects::creature::CreatureObject::dismount().
void CreatureObjectImplementation::doAnimation (const String & animation)
Definition at line 1929 of file CreatureObjectImplementation.cpp.
References _this, and server::zone::objects::scene::SceneObjectImplementation::broadcastMessage().
Referenced by server::zone::objects::creature::CreatureObject::doAnimation().
void CreatureObjectImplementation::doCombatAnimation (CreatureObject * defender, unsigned int animationCRC, byte hit, byte trails)
Definition at line 1922 of file CreatureObjectImplementation.cpp.
References _this, and server::zone::objects::scene::SceneObjectImplementation::broadcastMessage().
Referenced by server::zone::objects::creature::CreatureObject::doCombatAnimation().
void CreatureObjectImplementation::enqueueCommand (unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString & arguments, int priority = -1)
Enqueues a command action
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
actionCRC queue command crc
actionCount command count
targetID target
arguments arguments
priority command priority
Definition at line 1633 of file CreatureObjectImplementation.cpp.
References _this, activateQueueAction(), clearQueueAction(), commandQueue, server::zone::objects::creature::commands::QueueCommand::getDefaultPriority(), server::zone::ZoneServer::getObjectController(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), CommandQueueActionEvent::IMMEDIATE, immediateQueue, nextAction, and targetID.
Referenced by server::zone::objects::creature::AiAgentImplementation::doAttack(), and server::zone::objects::creature::CreatureObject::enqueueCommand().
void CreatureObjectImplementation::executeObjectControllerAction (unsigned int actionCRC)
Executes an object controller command
Definition at line 1906 of file CreatureObjectImplementation.cpp.
References _this, server::zone::managers::objectcontroller::ObjectController::activateCommand(), server::zone::ZoneServer::getObjectController(), and server::zone::objects::scene::SceneObjectImplementation::getZoneServer().
Referenced by server::zone::objects::creature::AiAgentImplementation::activatePostureRecovery(), dismount(), and server::zone::objects::creature::CreatureObject::executeObjectControllerAction().
void server::zone::objects::creature::CreatureObjectImplementation::executeObjectControllerAction (unsigned int actionCRC, unsigned long long targetID, const UnicodeString & args)
void CreatureObjectImplementation::fillAttributeList (AttributeListMessage * msg, CreatureObject * object) virtual
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 5803 of file CreatureObject.cpp.
References server::zone::objects::creature::ai::AiActor::fillAttributeList(), getActorObject(), and isAiActor().
Referenced by server::zone::objects::creature::CreatureObject::fillAttributeList().
void CreatureObjectImplementation::finalize ()
Definition at line 279 of file CreatureObjectImplementation.cpp.
Referenced by ~CreatureObjectImplementation().
float CreatureObjectImplementation::getAccelerationMultiplierBase ()
Definition at line 5327 of file CreatureObject.cpp.
References accelerationMultiplierBase.
Referenced by server::zone::objects::creature::CreatureObject::getAccelerationMultiplierBase().
float CreatureObjectImplementation::getAccelerationMultiplierMod ()
Definition at line 5332 of file CreatureObject.cpp.
References accelerationMultiplierMod.
Referenced by server::zone::objects::creature::CreatureObject::getAccelerationMultiplierMod().
AiActor * CreatureObjectImplementation::getActorObject ()
Definition at line 2430 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::getSlottedObject().
Referenced by clearCombatState(), destroyObjectFromWorld(), fillAttributeList(), server::zone::objects::creature::CreatureObject::getActorObject(), inflictDamage(), isAiActor(), notifyObjectDestructionObservers(), and sendConversationStartTo().
int CreatureObjectImplementation::getBankCredits ()
Definition at line 5211 of file CreatureObject.cpp.
References bankCredits.
Referenced by server::zone::objects::creature::CreatureObject::getBankCredits().
int CreatureObjectImplementation::getBaseHAM (int idx)
Definition at line 5221 of file CreatureObject.cpp.
References baseHAM, and server::zone::objects::scene::variables::DeltaVector< E >::get().
Referenced by server::zone::objects::creature::CreatureObject::getBaseHAM().
DeltaVector< int > * CreatureObjectImplementation::getBaseHAM ()
Definition at line 5543 of file CreatureObject.cpp.
References baseHAM.
Buff * CreatureObjectImplementation::getBuff (unsigned int buffcrc)
Definition at line 4955 of file CreatureObject.cpp.
References creatureBuffs, and hasBuff().
Referenced by server::zone::objects::creature::CreatureObject::getBuff().
BuffList * CreatureObjectImplementation::getBuffList ()
Definition at line 4950 of file CreatureObject.cpp.
References creatureBuffs.
Referenced by server::zone::objects::creature::CreatureObject::getBuffList().
int CreatureObjectImplementation::getCashCredits ()
Definition at line 5216 of file CreatureObject.cpp.
References cashCredits.
Referenced by server::zone::objects::creature::CreatureObject::getCashCredits().
ZoneClientSession * CreatureObjectImplementation::getClient () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 5588 of file CreatureObject.cpp.
References owner.
Referenced by server::zone::objects::creature::CreatureObject::getClient().
CommandQueueActionVector * CreatureObjectImplementation::getCommandQueue ()
Definition at line 5357 of file CreatureObject.cpp.
References commandQueue.
Referenced by server::zone::objects::creature::CreatureObject::getCommandQueue().
ManagedWeakReference< ControlDevice * > CreatureObjectImplementation::getControlDevice ()
Definition at line 5598 of file CreatureObject.cpp.
References controlDevice.
Referenced by server::zone::objects::creature::CreatureObject::getControlDevice().
Time * CreatureObjectImplementation::getCooldownTime (const String & cooldown)
Definition at line 5191 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::getCooldownTime().
CooldownTimerMap * CreatureObjectImplementation::getCooldownTimerMap ()
Definition at line 5108 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::getCooldownTimerMap().
unsigned long long CreatureObjectImplementation::getCreatureLinkID ()
Definition at line 5286 of file CreatureObject.cpp.
References linkedCreature.
Referenced by server::zone::objects::creature::CreatureObject::getCreatureLinkID().
UnicodeString CreatureObjectImplementation::getCreatureName ()
Definition at line 1370 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::getCustomObjectName().
Referenced by server::zone::objects::creature::CreatureObject::getCreatureName().
CampSiteActiveArea * CreatureObjectImplementation::getCurrentCamp ()
Definition at line 2706 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::activeAreas.
Referenced by server::zone::objects::creature::CreatureObject::getCurrentCamp().
float CreatureObjectImplementation::getCurrentSpeed ()
Definition at line 5347 of file CreatureObject.cpp.
References currentSpeed.
Referenced by server::zone::objects::creature::CreatureObject::getCurrentSpeed().
byte CreatureObjectImplementation::getCurrentWeather ()
Definition at line 5783 of file CreatureObject.cpp.
References currentWeather.
Referenced by server::zone::objects::creature::CreatureObject::getCurrentWeather().
byte CreatureObjectImplementation::getCurrentWind ()
Definition at line 5793 of file CreatureObject.cpp.
References currentWind.
Referenced by server::zone::objects::creature::CreatureObject::getCurrentWind().
DamageOverTimeList * CreatureObjectImplementation::getDamageOverTimeList ()
Definition at line 4983 of file CreatureObject.cpp.
References damageOverTimeList.
Referenced by server::zone::objects::creature::CreatureObject::getDamageOverTimeList().
int CreatureObjectImplementation::getEncumbrance (int idx)
Definition at line 5256 of file CreatureObject.cpp.
References encumbrances.
Referenced by server::zone::objects::creature::CreatureObject::getEncumbrance().
DeltaVector< int > * CreatureObjectImplementation::getEncumbrances ()
Definition at line 5261 of file CreatureObject.cpp.
References encumbrances.
Referenced by server::zone::objects::creature::CreatureObject::getEncumbrances().
byte CreatureObjectImplementation::getFactionRank ()
Definition at line 5276 of file CreatureObject.cpp.
References factionRank.
Referenced by server::zone::objects::creature::CreatureObject::getFactionRank().
String CreatureObjectImplementation::getFirstName ()
Definition at line 2393 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::getCustomObjectName().
Referenced by server::zone::objects::creature::CreatureObject::getFirstName().
byte CreatureObjectImplementation::getFrozen ()
Definition at line 5478 of file CreatureObject.cpp.
References frozen.
Referenced by server::zone::objects::creature::CreatureObject::getFrozen().
int CreatureObjectImplementation::getGender ()
Definition at line 5538 of file CreatureObject.cpp.
References gender.
Referenced by server::zone::objects::creature::CreatureObject::getGender().
GroupObject * CreatureObjectImplementation::getGroup ()
Definition at line 5443 of file CreatureObject.cpp.
References group.
Referenced by server::zone::objects::creature::CreatureObject::getGroup().
unsigned long long CreatureObjectImplementation::getGroupID ()
Definition at line 5429 of file CreatureObject.cpp.
References group.
Referenced by server::zone::objects::creature::CreatureObject::getGroupID().
unsigned long long CreatureObjectImplementation::getGroupInviteCounter ()
Definition at line 5448 of file CreatureObject.cpp.
References groupInviteCounter.
Referenced by server::zone::objects::creature::CreatureObject::getGroupInviteCounter().
unsigned long long CreatureObjectImplementation::getGroupInviterID ()
Definition at line 5438 of file CreatureObject.cpp.
References groupInviterID.
Referenced by server::zone::objects::creature::CreatureObject::getGroupInviterID().
int CreatureObjectImplementation::getGuildID ()
Definition at line 5411 of file CreatureObject.cpp.
References guild.
Referenced by server::zone::objects::creature::CreatureObject::getGuildID().
Reference< GuildObject * > CreatureObjectImplementation::getGuildObject ()
Definition at line 5406 of file CreatureObject.cpp.
References guild.
Referenced by server::zone::objects::creature::CreatureObject::getGuildObject().
int CreatureObjectImplementation::getHAM (int idx)
Definition at line 5236 of file CreatureObject.cpp.
References server::zone::objects::scene::variables::DeltaVector< E >::get(), and hamList.
Referenced by server::zone::objects::creature::CreatureObject::getHAM().
DeltaVector< int > * CreatureObjectImplementation::getHAM ()
Definition at line 5241 of file CreatureObject.cpp.
References hamList.
Referenced by activateHAMRegeneration(), calculateCostAdjustment(), notifyLoadFromDatabase(), and setWounds().
float CreatureObjectImplementation::getHeight ()
Definition at line 5483 of file CreatureObject.cpp.
References height.
Referenced by server::zone::objects::creature::AiAgentImplementation::findNextPosition(), and server::zone::objects::creature::CreatureObject::getHeight().
int CreatureObjectImplementation::getInstrumentID ()
Definition at line 5473 of file CreatureObject.cpp.
References instrumentID.
Referenced by server::zone::objects::creature::CreatureObject::getInstrumentID().
String CreatureObjectImplementation::getLastName ()
Definition at line 2405 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::getCustomObjectName().
Referenced by server::zone::objects::creature::CreatureObject::getLastName().
ManagedWeakReference< CreatureObject * > CreatureObjectImplementation::getLinkedCreature ()
Definition at line 5281 of file CreatureObject.cpp.
References linkedCreature.
Referenced by server::zone::objects::creature::CreatureObject::getLinkedCreature().
unsigned long long CreatureObjectImplementation::getListenID ()
Definition at line 5322 of file CreatureObject.cpp.
References listenToID.
Referenced by server::zone::objects::creature::CreatureObject::getListenID().
byte CreatureObjectImplementation::getLocomotion ()
Definition at line 5271 of file CreatureObject.cpp.
References locomotion.
Referenced by server::zone::objects::creature::CreatureObject::getLocomotion().
int CreatureObjectImplementation::getMaxHAM (int idx)
Definition at line 5246 of file CreatureObject.cpp.
References server::zone::objects::scene::variables::DeltaVector< E >::get(), and maxHamList.
Referenced by server::zone::objects::creature::CreatureObject::getMaxHAM().
DeltaVector< int > * CreatureObjectImplementation::getMaxHAM ()
Definition at line 5251 of file CreatureObject.cpp.
References maxHamList.
byte CreatureObjectImplementation::getMoodID ()
Definition at line 5458 of file CreatureObject.cpp.
References moodID.
Referenced by server::zone::objects::creature::CreatureObject::getMoodID().
String CreatureObjectImplementation::getMoodString ()
Definition at line 5392 of file CreatureObject.cpp.
References moodString.
Referenced by server::zone::objects::creature::CreatureObject::getMoodString().
String CreatureObjectImplementation::getPerformanceAnimation ()
Definition at line 5387 of file CreatureObject.cpp.
References performanceAnimation.
Referenced by server::zone::objects::creature::CreatureObject::getPerformanceAnimation().
int CreatureObjectImplementation::getPerformanceCounter ()
Definition at line 5468 of file CreatureObject.cpp.
References performanceCounter.
Referenced by server::zone::objects::creature::CreatureObject::getPerformanceCounter().
Reference< PlayerObject * > CreatureObjectImplementation::getPlayerObject ()
Definition at line 2426 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::getSlottedObject().
Referenced by server::zone::objects::creature::CreatureObject::getPlayerObject(), isAggressiveTo(), isAttackableBy(), isHealableBy(), isOnline(), isPlayerCreature(), notifyLoadFromDatabase(), and notifyObjectDestructionObservers().
byte CreatureObjectImplementation::getPosture ()
Definition at line 5266 of file CreatureObject.cpp.
References posture.
Referenced by server::zone::objects::creature::CreatureObject::getPosture().
float CreatureObjectImplementation::getRunAcceleration ()
Definition at line 5377 of file CreatureObject.cpp.
References runAcceleration.
Referenced by server::zone::objects::creature::CreatureObject::getRunAcceleration().
float CreatureObjectImplementation::getRunSpeed ()
Definition at line 5362 of file CreatureObject.cpp.
References runSpeed.
Referenced by server::zone::objects::creature::CreatureObject::getRunSpeed().
unsigned long long CreatureObjectImplementation::getScreenPlayState (const String & screenPlay)
Definition at line 5158 of file CreatureObject.cpp.
References screenPlayStates.
Referenced by server::zone::objects::creature::CreatureObject::getScreenPlayState().
float CreatureObjectImplementation::getShockWounds ()
Definition at line 5297 of file CreatureObject.cpp.
References shockWounds.
Referenced by server::zone::objects::creature::CreatureObject::getShockWounds().
SkillList * CreatureObjectImplementation::getSkillList ()
Definition at line 5548 of file CreatureObject.cpp.
References skillList.
Referenced by server::zone::objects::creature::CreatureObject::getSkillList(), and notifyLoadFromDatabase().
int CreatureObjectImplementation::getSkillMod (const String & skillmod)
Definition at line 1260 of file CreatureObjectImplementation.cpp.
References SkillModList::getSkillMod(), skillModList, and skillModMutex.
Referenced by activatePassiveWoundRegeneration(), server::zone::objects::creature::CreatureObject::getSkillMod(), getTerrainNegotiation(), inflictDamage(), setAccelerationMultiplierMod(), setAimingState(), setBerserkedState(), setIntimidatedState(), setSpeedMultiplierMod(), setStunnedState(), and updateSpeedAndAccelerationMods().
long long CreatureObjectImplementation::getSkillModFromBuffs (const String & skillMod)
Definition at line 4963 of file CreatureObject.cpp.
References creatureBuffs.
Referenced by server::zone::objects::creature::CreatureObject::getSkillModFromBuffs().
SkillModList * CreatureObjectImplementation::getSkillModList ()
Definition at line 5558 of file CreatureObject.cpp.
References skillModList.
Referenced by server::zone::objects::creature::CreatureObject::getSkillModList().
Mutex * CreatureObjectImplementation::getSkillModMutex ()
Definition at line 5831 of file CreatureObject.cpp.
References skillModMutex.
Referenced by server::zone::objects::creature::CreatureObject::getSkillModMutex().
float CreatureObjectImplementation::getSlopeModPercent ()
Definition at line 5463 of file CreatureObject.cpp.
References slopeModPercent.
Referenced by server::zone::objects::creature::CreatureObject::getSlopeModPercent().
int CreatureObjectImplementation::getSpecies ()
Definition at line 5488 of file CreatureObject.cpp.
References species.
Referenced by server::zone::objects::creature::CreatureObject::getSpecies().
String CreatureObjectImplementation::getSpeciesName ()
Definition at line 5493 of file CreatureObject.cpp.
References species.
Referenced by server::zone::objects::creature::CreatureObject::getSpeciesName().
float CreatureObjectImplementation::getSpeedMultiplierBase ()
Definition at line 5337 of file CreatureObject.cpp.
References speedMultiplierBase.
Referenced by server::zone::objects::creature::CreatureObject::getSpeedMultiplierBase().
float CreatureObjectImplementation::getSpeedMultiplierMod ()
Definition at line 5342 of file CreatureObject.cpp.
References speedMultiplierMod.
Referenced by server::zone::objects::creature::CreatureObject::getSpeedMultiplierMod().
SpeedMultiplierModChanges * CreatureObjectImplementation::getSpeedMultiplierModChanges ()
Definition at line 5352 of file CreatureObject.cpp.
References speedMultiplierModChanges.
Referenced by server::zone::objects::creature::CreatureObject::getSpeedMultiplierModChanges().
unsigned long long CreatureObjectImplementation::getStateBitmask ()
Definition at line 5307 of file CreatureObject.cpp.
References stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::getStateBitmask().
float CreatureObjectImplementation::getSwimHeight ()
Definition at line 5603 of file CreatureObject.cpp.
References swimHeight.
Referenced by server::zone::objects::creature::AiAgentImplementation::findNextPosition(), and server::zone::objects::creature::CreatureObject::getSwimHeight().
unsigned long long CreatureObjectImplementation::getTargetID ()
Definition at line 5453 of file CreatureObject.cpp.
References targetID.
Referenced by server::zone::objects::creature::CreatureObject::getTargetID().
float CreatureObjectImplementation::getTerrainNegotiation ()
Definition at line 1626 of file CreatureObjectImplementation.cpp.
References getSkillMod(), and terrainNegotiation.
Referenced by server::zone::objects::creature::CreatureObject::getTerrainNegotiation().
float CreatureObjectImplementation::getTurnScale ()
Definition at line 5372 of file CreatureObject.cpp.
References turnScale.
Referenced by server::zone::objects::creature::CreatureObject::getTurnScale(), and updateSpeedAndAccelerationMods().
float CreatureObjectImplementation::getWalkAcceleration ()
Definition at line 5382 of file CreatureObject.cpp.
References walkAcceleration.
Referenced by server::zone::objects::creature::CreatureObject::getWalkAcceleration().
float CreatureObjectImplementation::getWalkSpeed ()
Definition at line 5367 of file CreatureObject.cpp.
References walkSpeed.
Referenced by server::zone::objects::creature::CreatureObject::getWalkSpeed().
unsigned long long CreatureObjectImplementation::getWatchToID ()
Definition at line 5302 of file CreatureObject.cpp.
References watchToID.
Referenced by server::zone::objects::creature::CreatureObject::getWatchToID().
Reference< WeaponObject * > CreatureObjectImplementation::getWeapon ()
Definition at line 2741 of file CreatureObjectImplementation.cpp.
References weapon.
Referenced by server::zone::objects::creature::AiAgentImplementation::doMovement(), server::zone::objects::creature::AiAgentImplementation::getDamageMax(), server::zone::objects::creature::AiAgentImplementation::getDamageMin(), server::zone::objects::creature::CreatureObject::getWeapon(), and server::zone::objects::creature::AiAgentImplementation::selectWeapon().
unsigned long long CreatureObjectImplementation::getWeaponID ()
Definition at line 5397 of file CreatureObject.cpp.
References weapon.
Referenced by server::zone::objects::creature::CreatureObject::getWeaponID().
WearablesDeltaVector * CreatureObjectImplementation::getWearablesDeltaVector ()
Definition at line 4940 of file CreatureObject.cpp.
References wearablesVector.
Referenced by server::zone::objects::creature::CreatureObject::getWearablesDeltaVector().
int CreatureObjectImplementation::getWounds (int idx)
Definition at line 5226 of file CreatureObject.cpp.
References server::zone::objects::scene::variables::DeltaVector< E >::get(), and wounds.
Referenced by server::zone::objects::creature::CreatureObject::getWounds().
DeltaVector< int > * CreatureObjectImplementation::getWounds ()
Definition at line 5231 of file CreatureObject.cpp.
References wounds.
int CreatureObjectImplementation::handleObjectMenuSelect (CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player CreatureObject that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 2715 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::creature::CreatureObject::executeObjectControllerAction(), server::zone::objects::scene::SceneObjectImplementation::getObjectID(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), isAiActor(), isDead(), and server::zone::managers::player::PlayerManager::lootAll().
Referenced by server::zone::objects::creature::AiAgentImplementation::handleObjectMenuSelect(), and server::zone::objects::creature::CreatureObject::handleObjectMenuSelect().
bool CreatureObjectImplementation::hasAttackDelay ()
Definition at line 5098 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::hasAttackDelay().
bool CreatureObjectImplementation::hasBuff (unsigned int buffcrc)
Definition at line 4988 of file CreatureObject.cpp.
References creatureBuffs.
Referenced by clearState(), getBuff(), server::zone::objects::creature::CreatureObject::hasBuff(), setSpeedMultiplierMod(), and updateSpeedAndAccelerationMods().
bool CreatureObjectImplementation::hasDamage (int attribute)
Definition at line 4930 of file CreatureObject.cpp.
References hamList, maxHamList, and wounds.
Referenced by server::zone::objects::creature::CreatureObject::hasDamage().
bool CreatureObjectImplementation::hasSkill (const String & skill)
Definition at line 5553 of file CreatureObject.cpp.
References skillList.
Referenced by server::zone::objects::creature::CreatureObject::hasSkill(), and setSpeedMultiplierMod().
bool CreatureObjectImplementation::hasSpice ()
Definition at line 5113 of file CreatureObject.cpp.
References creatureBuffs.
Referenced by server::zone::objects::creature::CreatureObject::hasSpice().
bool CreatureObjectImplementation::hasState (unsigned long long state)
Definition at line 5312 of file CreatureObject.cpp.
References stateBitmask.
Referenced by server::zone::objects::creature::AiAgentImplementation::findNextPosition(), server::zone::objects::creature::CreatureObject::hasState(), notifyLoadFromDatabase(), notifyPostureChange(), setAimingState(), setBerserkedState(), setBlindedState(), setCoverState(), setDizziedState(), setIntimidatedState(), setPosture(), setRalliedState(), setRootedState(), setSnaredState(), and setStunnedState().
bool CreatureObjectImplementation::hasStates ()
Definition at line 5317 of file CreatureObject.cpp.
References stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::hasStates().
int CreatureObjectImplementation::healDamage (TangibleObject * healer, int damageType, int damage, bool notifyClient = true, bool notifyObservers = true)
Heals damage
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
unused for now
Definition at line 901 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::objects::scene::variables::DeltaVector< E >::get(), hamList, ObserverEventType::HEALINGPERFORMED, isDead(), isIncapacitated(), maxHamList, setHAM(), setPosture(), server::zone::objects::scene::variables::DeltaVector< E >::size(), CreaturePosture::UPRIGHT, and wounds.
Referenced by activateHAMRegeneration(), server::zone::objects::creature::CreatureObject::healDamage(), and setMaxHAM().
bool CreatureObjectImplementation::healDot (unsigned long long dotType, int reduction)
Definition at line 4973 of file CreatureObject.cpp.
References _this, and damageOverTimeList.
Referenced by server::zone::objects::creature::CreatureObject::healDot().
int CreatureObjectImplementation::healWound (TangibleObject * healer, int damageType, int damage, bool notifyClient = true, bool notifyObservers = true)
Heals wound
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
unused for now
Definition at line 948 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::objects::scene::variables::DeltaVector< E >::get(), setWounds(), server::zone::objects::scene::variables::DeltaVector< E >::size(), ObserverEventType::WOUNDHEALINGPERFORMED, and wounds.
Referenced by activatePassiveWoundRegeneration(), and server::zone::objects::creature::CreatureObject::healWound().
int CreatureObjectImplementation::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, bool notifyClient = true) virtual
Inflicts damage into the object
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
unused for now
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Reimplemented in server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 864 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::objects::scene::variables::DeltaVector< E >::get(), getActorObject(), getSkillMod(), hamList, isAiActor(), isDead(), isIncapacitated(), notifyObjectDestructionObservers(), setHAM(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
Referenced by server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::creature::AiAgentImplementation::inflictDamage(), and inflictDamage().
int CreatureObjectImplementation::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, const String & xp, bool notifyClient = true) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Reimplemented in server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 852 of file CreatureObjectImplementation.cpp.
References server::zone::objects::tangible::threat::ThreatMap::addDamage(), server::zone::objects::tangible::TangibleObjectImplementation::getThreatMap(), inflictDamage(), and server::zone::objects::scene::SceneObject::isPlayerCreature().
void CreatureObjectImplementation::initializeMembers ()
Definition at line 141 of file CreatureObjectImplementation.cpp.
References accelerationMultiplierBase, accelerationMultiplierMod, actionWoundHeal, bankCredits, cashCredits, commandQueue, controlDevice, cooldownTimerMap, currentSpeed, server::zone::objects::tangible::TangibleObjectImplementation::faction, factionRank, group, groupInviteCounter, groupInviterID, guild, healthWoundHeal, height, immediateQueue, instrumentID, invisible, linkedCreature, listenToID, mindWoundHeal, moodID, moodString, server::zone::objects::tangible::TangibleObjectImplementation::optionsBitmask, performanceCounter, posture, server::zone::objects::tangible::TangibleObjectImplementation::pvpStatusBitmask, server::zone::objects::scene::SceneObjectImplementation::setContainerDefaultDenyPermission(), server::zone::objects::scene::SceneObjectImplementation::setContainerDenyPermission(), server::zone::objects::scene::SceneObjectImplementation::setContainerInheritPermissionsFromParent(), shockWounds, speedMultiplierBase, speedMultiplierMod, stateBitmask, targetID, terrainNegotiation, turnScale, watchToID, and weapon.
Referenced by CreatureObjectImplementation(), and server::zone::objects::creature::CreatureObject::initializeMembers().
void CreatureObjectImplementation::initializeTransientMembers ()
Initializes the transient members of SceneObject, must call the inherited object method first.
Precondition
{transient members are not initialized }
Postcondition
{ transient members are initialized }
Definition at line 127 of file CreatureObjectImplementation.cpp.
References currentWeather, currentWind, server::zone::objects::scene::SceneObjectImplementation::getObjectID(), groupInviteCounter, groupInviterID, moodID, server::zone::objects::scene::SceneObjectImplementation::setContainerOwnerID(), server::zone::objects::scene::SceneObjectImplementation::setLoggingName(), and setMood().
Referenced by server::zone::objects::creature::CreatureObject::initializeTransientMembers(), server::zone::objects::creature::AiAgentImplementation::initializeTransientMembers(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::readObject(), server::zone::objects::creature::VehicleObjectImplementation::readObject(), and readObject().
bool CreatureObjectImplementation::isAggressiveTo (CreatureObject * object) virtual
Evaluates if this creature is aggresive to the object
Precondition
{ }
Postcondition
{ }
Returns
returns true if its aggressive
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 2434 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::tangible::TangibleObjectImplementation::getFaction(), server::zone::objects::scene::SceneObject::getObjectID(), getPlayerObject(), guild, server::zone::objects::player::PlayerObject::isInBountyLockList(), CreatureFlag::OVERT, server::zone::objects::tangible::TangibleObjectImplementation::pvpStatusBitmask, and server::zone::objects::player::PlayerObject::requestedDuelTo().
Referenced by server::zone::objects::creature::CreatureObject::isAggressiveTo().
bool CreatureObjectImplementation::isAiActor ()
Definition at line 5773 of file CreatureObject.cpp.
References getActorObject().
Referenced by clearCombatState(), destroyObjectFromWorld(), fillAttributeList(), handleObjectMenuSelect(), inflictDamage(), server::zone::objects::creature::CreatureObject::isAiActor(), and sendConversationStartTo().
bool CreatureObjectImplementation::isAiming ()
Definition at line 5743 of file CreatureObject.cpp.
References CreatureState::AIMING, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isAiming().
bool CreatureObjectImplementation::isAttackableBy (CreatureObject * object) virtual
Evaluates if this object can be attacket by the passed creature object
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns true if the creature object can attack this
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Reimplemented in server::zone::objects::creature::VehicleObjectImplementation, and server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation.
Definition at line 2497 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::tangible::TangibleObjectImplementation::getFaction(), server::zone::objects::scene::SceneObject::getObjectID(), getPlayerObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObjectImplementation::getZone(), guild, server::zone::objects::scene::SceneObject::isAiAgent(), isDead(), server::zone::objects::player::PlayerObject::isInBountyLockList(), isInBountyMission(), isInvisible(), isPlayerCreature(), server::zone::objects::tangible::TangibleObject::isRebel(), FactionStatus::ONLEAVE, CreatureFlag::OVERT, server::zone::objects::tangible::TangibleObjectImplementation::pvpStatusBitmask, and server::zone::objects::player::PlayerObject::requestedDuelTo().
Referenced by server::zone::objects::creature::CreatureObject::isAttackableBy(), and isAttackableBy().
bool CreatureObjectImplementation::isAttackableBy (TangibleObject * attacker)
Definition at line 2462 of file CreatureObjectImplementation.cpp.
References server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::tangible::TangibleObjectImplementation::getFaction(), server::zone::objects::player::PlayerObject::getFactionStatus(), getPlayerObject(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), server::zone::objects::tangible::TangibleObjectImplementation::getPvpStatusBitmask(), server::zone::objects::scene::SceneObjectImplementation::isAiAgent(), isAttackableBy(), server::zone::objects::scene::SceneObject::isCreatureObject(), isDead(), isIncapacitated(), isInvisible(), FactionStatus::ONLEAVE, and CreatureFlag::OVERT.
bool CreatureObjectImplementation::isBerserked ()
Definition at line 5663 of file CreatureObject.cpp.
References CreatureState::BERSERK, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isBerserked().
bool CreatureObjectImplementation::isBleeding ()
Definition at line 5713 of file CreatureObject.cpp.
References CreatureState::BLEEDING, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isBleeding().
bool CreatureObjectImplementation::isBlinded ()
Definition at line 5673 of file CreatureObject.cpp.
References CreatureState::BLINDED, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isBlinded().
bool CreatureObjectImplementation::isCreature () virtual
Reimplemented in server::zone::objects::creature::CreatureImplementation.
Definition at line 5763 of file CreatureObject.cpp.
Referenced by server::zone::objects::creature::AiAgentImplementation::isConcealed(), server::zone::objects::creature::CreatureObject::isCreature(), and server::zone::objects::creature::AiAgentImplementation::loadTemplateData().
bool CreatureObjectImplementation::isCreatureObject () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 5568 of file CreatureObject.cpp.
Referenced by server::zone::objects::creature::CreatureObject::isCreatureObject().
bool CreatureObjectImplementation::isDancing ()
Definition at line 2334 of file CreatureObjectImplementation.cpp.
References SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObjectImplementation::getActiveSession(), and server::zone::objects::player::sessions::EntertainingSession::isDancing().
Referenced by server::zone::objects::creature::CreatureObject::isDancing(), and isEntertaining().
bool CreatureObjectImplementation::isDead ()
Definition at line 5613 of file CreatureObject.cpp.
References CreaturePosture::DEAD, and posture.
Referenced by activateHAMRegeneration(), server::zone::objects::creature::AiAgentImplementation::doAttack(), server::zone::objects::creature::AiAgentImplementation::doMovement(), server::zone::objects::creature::AiAgentImplementation::doRecovery(), server::zone::objects::creature::AiAgentImplementation::fillAttributeList(), server::zone::objects::creature::AiAgentImplementation::handleObjectMenuSelect(), handleObjectMenuSelect(), healDamage(), inflictDamage(), server::zone::objects::creature::AiAgentImplementation::isAttackableBy(), isAttackableBy(), server::zone::objects::creature::CreatureObject::isDead(), isResuscitable(), and server::zone::objects::creature::AiAgentImplementation::sendConversationStartTo().
bool CreatureObjectImplementation::isDiseased ()
Definition at line 5703 of file CreatureObject.cpp.
References CreatureState::DISEASED, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isDiseased().
bool CreatureObjectImplementation::isDizzied ()
Definition at line 5658 of file CreatureObject.cpp.
References CreatureState::DIZZY, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isDizzied().
bool CreatureObjectImplementation::isEntertaining ()
Definition at line 5029 of file CreatureObject.cpp.
References isDancing(), and isPlayingMusic().
Referenced by server::zone::objects::creature::CreatureObject::isEntertaining(), and setCombatState().
bool CreatureObjectImplementation::isFrozen ()
Definition at line 5698 of file CreatureObject.cpp.
References CreatureState::FROZEN, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isFrozen().
bool CreatureObjectImplementation::isGrouped ()
Definition at line 5206 of file CreatureObject.cpp.
References group.
Referenced by server::zone::objects::creature::CreatureObject::isGrouped().
bool CreatureObjectImplementation::isHealableBy (CreatureObject * object) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 2551 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::tangible::TangibleObjectImplementation::getFaction(), server::zone::objects::player::PlayerObject::getFactionStatus(), getPlayerObject(), server::zone::objects::player::PlayerObject::isBountyLocked(), isInvisible(), FactionStatus::ONLEAVE, and FactionStatus::OVERT.
Referenced by server::zone::objects::creature::CreatureObject::isHealableBy().
bool CreatureObjectImplementation::isImmobilized ()
Definition at line 5688 of file CreatureObject.cpp.
References CreatureState::IMMOBILIZED, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isImmobilized().
bool CreatureObjectImplementation::isInBountyMission (CreatureObject * bountyHunter, CreatureObject * target)
Evaluates if the bounty hunter has a mission with the target.
Parameters
bountyHunter the bounty hunter.
target the target.
Returns
true if bounty hunter has a mission with the target.
Definition at line 2587 of file CreatureObjectImplementation.cpp.
References server::zone::managers::mission::MissionManager::getBountyHunterMission(), server::zone::ZoneServer::getMissionManager(), server::zone::objects::scene::SceneObject::getObjectID(), and server::zone::objects::scene::SceneObject::getZoneServer().
Referenced by isAttackableBy(), and server::zone::objects::creature::CreatureObject::isInBountyMission().
bool CreatureObjectImplementation::isIncapacitated ()
Definition at line 5608 of file CreatureObject.cpp.
References CreaturePosture::INCAPACITATED, and posture.
Referenced by activateHAMRegeneration(), healDamage(), inflictDamage(), isAttackableBy(), server::zone::objects::creature::CreatureObject::isIncapacitated(), and notifyLoadFromDatabase().
bool CreatureObjectImplementation::isInCombat ()
Definition at line 5653 of file CreatureObject.cpp.
References CreatureState::COMBAT, and stateBitmask.
Referenced by server::zone::objects::creature::AiAgentImplementation::doAttack(), server::zone::objects::creature::CreatureObject::isInCombat(), and setMeditateState().
bool CreatureObjectImplementation::isInCover ()
Definition at line 5748 of file CreatureObject.cpp.
References CreatureState::COVER, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isInCover(), and setPosture().
bool CreatureObjectImplementation::isInformantCreature () virtual
Definition at line 5778 of file CreatureObject.cpp.
Referenced by server::zone::objects::creature::CreatureObject::isInformantCreature().
bool CreatureObjectImplementation::isInGuild ()
Definition at line 5419 of file CreatureObject.cpp.
References guild.
Referenced by server::zone::objects::creature::CreatureObject::isInGuild().
bool CreatureObjectImplementation::isIntimidated ()
Definition at line 5678 of file CreatureObject.cpp.
References CreatureState::INTIMIDATED, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isIntimidated().
bool CreatureObjectImplementation::isInvisible ()
Definition at line 5821 of file CreatureObject.cpp.
References invisible.
Referenced by isAttackableBy(), isHealableBy(), server::zone::objects::creature::CreatureObject::isInvisible(), and sendTo().
bool CreatureObjectImplementation::isKneeling ()
Definition at line 5623 of file CreatureObject.cpp.
References CreaturePosture::CROUCHED, and posture.
Referenced by activateHAMRegeneration(), server::zone::objects::creature::AiAgentImplementation::activatePostureRecovery(), and server::zone::objects::creature::CreatureObject::isKneeling().
bool CreatureObjectImplementation::isKnockedDown ()
Definition at line 5618 of file CreatureObject.cpp.
References CreaturePosture::KNOCKEDDOWN, and posture.
Referenced by server::zone::objects::creature::AiAgentImplementation::activatePostureRecovery(), and server::zone::objects::creature::CreatureObject::isKnockedDown().
bool CreatureObjectImplementation::isListening ()
Definition at line 5078 of file CreatureObject.cpp.
References listenToID.
Referenced by server::zone::objects::creature::CreatureObject::isListening().
bool CreatureObjectImplementation::isMeditating ()
Definition at line 5738 of file CreatureObject.cpp.
References CreatureState::ALERT, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isMeditating().
bool CreatureObjectImplementation::isMounted ()
Definition at line 5723 of file CreatureObject.cpp.
References CreatureState::RIDINGMOUNT, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isMounted().
bool CreatureObjectImplementation::isNextActionPast ()
Definition at line 5573 of file CreatureObject.cpp.
References nextAction.
Referenced by server::zone::objects::creature::CreatureObject::isNextActionPast().
bool CreatureObjectImplementation::isNonPlayerCreatureObject () virtual
Reimplemented in server::zone::objects::creature::NonPlayerCreatureObjectImplementation.
Definition at line 5758 of file CreatureObject.cpp.
Referenced by server::zone::objects::creature::CreatureObject::isNonPlayerCreatureObject().
bool CreatureObjectImplementation::isOnFire ()
Definition at line 5718 of file CreatureObject.cpp.
References CreatureState::ONFIRE, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isOnFire().
bool CreatureObjectImplementation::isOnline ()
Definition at line 5048 of file CreatureObject.cpp.
References getPlayerObject().
Referenced by server::zone::objects::creature::CreatureObject::isOnline().
bool CreatureObjectImplementation::isPeaced ()
Definition at line 5733 of file CreatureObject.cpp.
References CreatureState::PEACE, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isPeaced().
bool CreatureObjectImplementation::isPlayerCreature () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 5768 of file CreatureObject.cpp.
References getPlayerObject().
Referenced by activateHAMRegeneration(), clearQueueAction(), isAttackableBy(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), sendSystemMessage(), and setNextAttackDelay().
bool CreatureObjectImplementation::isPlayingMusic ()
Definition at line 2350 of file CreatureObjectImplementation.cpp.
References SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObjectImplementation::getActiveSession(), and server::zone::objects::player::sessions::EntertainingSession::isPlayingMusic().
Referenced by isEntertaining(), and server::zone::objects::creature::CreatureObject::isPlayingMusic().
bool CreatureObjectImplementation::isPoisoned ()
Definition at line 5708 of file CreatureObject.cpp.
References CreatureState::POISONED, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isPoisoned().
bool CreatureObjectImplementation::isProne ()
Definition at line 5628 of file CreatureObject.cpp.
References posture, and CreaturePosture::PRONE.
Referenced by server::zone::objects::creature::AiAgentImplementation::activatePostureRecovery(), and server::zone::objects::creature::CreatureObject::isProne().
bool CreatureObjectImplementation::isRallied ()
Definition at line 5648 of file CreatureObject.cpp.
References CreatureState::RALLIED, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isRallied().
bool CreatureObjectImplementation::isResuscitable ()
Definition at line 2330 of file CreatureObjectImplementation.cpp.
References DEAD_TOO_LONG, isDead(), and timeOfDeath.
Referenced by server::zone::objects::creature::CreatureObject::isResuscitable().
bool CreatureObjectImplementation::isRidingCreature ()
Definition at line 5728 of file CreatureObject.cpp.
References CreatureState::MOUNTEDCREATURE, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isRidingCreature().
bool CreatureObjectImplementation::isRidingMount ()
Definition at line 5593 of file CreatureObject.cpp.
References CreatureState::RIDINGMOUNT, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isRidingMount().
bool CreatureObjectImplementation::isRooted ()
Definition at line 5693 of file CreatureObject.cpp.
References CreatureState::FROZEN, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isRooted().
bool CreatureObjectImplementation::isRunning ()
Definition at line 5753 of file CreatureObject.cpp.
References currentSpeed, and runSpeed.
Referenced by server::zone::objects::creature::CreatureObject::isRunning().
bool CreatureObjectImplementation::isSitting ()
Definition at line 5638 of file CreatureObject.cpp.
References posture, and CreaturePosture::SITTING.
Referenced by activateHAMRegeneration(), and server::zone::objects::creature::CreatureObject::isSitting().
bool CreatureObjectImplementation::isSkillAnimating ()
Definition at line 5643 of file CreatureObject.cpp.
References posture, and CreaturePosture::SKILLANIMATING.
Referenced by server::zone::objects::creature::CreatureObject::isSkillAnimating().
bool CreatureObjectImplementation::isSnared ()
Definition at line 5683 of file CreatureObject.cpp.
References CreatureState::IMMOBILIZED, and stateBitmask.
Referenced by server::zone::objects::creature::CreatureObject::isSnared().
bool CreatureObjectImplementation::isStanding ()
Definition at line 5633 of file CreatureObject.cpp.
References posture, and CreaturePosture::UPRIGHT.
Referenced by server::zone::objects::creature::AiAgentImplementation::doMovement(), and server::zone::objects::creature::CreatureObject::isStanding().
bool CreatureObjectImplementation::isStunned ()
Definition at line 5668 of file CreatureObject.cpp.
References stateBitmask, and CreatureState::STUNNED.
Referenced by server::zone::objects::creature::CreatureObject::isStunned().
bool CreatureObjectImplementation::isSwimming ()
Definition at line 5583 of file CreatureObject.cpp.
References stateBitmask, and CreatureState::SWIMMING.
Referenced by server::zone::objects::creature::CreatureObject::isSwimming().
bool CreatureObjectImplementation::isTrainerCreature () virtual
Definition at line 5578 of file CreatureObject.cpp.
Referenced by server::zone::objects::creature::CreatureObject::isTrainerCreature().
bool CreatureObjectImplementation::isWatching ()
Definition at line 5083 of file CreatureObject.cpp.
References watchToID.
Referenced by server::zone::objects::creature::CreatureObject::isWatching().
void CreatureObjectImplementation::loadTemplateData (SharedObjectTemplate * templateData) virtual
Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
Precondition
{ templateData is a valid pointer }
Postcondition
{ TangibleObject members are initialized }
Parameters
templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::creature::VehicleObjectImplementation, and server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation.
Definition at line 203 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::variables::DeltaVector< E >::add(), baseHAM, encumbrances, frozen, gender, server::zone::objects::scene::variables::DeltaVector< E >::get(), SharedCreatureObjectTemplate::getAcceleration(), SharedCreatureObjectTemplate::getBaseHAM(), SharedCreatureObjectTemplate::getGender(), SharedTangibleObjectTemplate::getLevel(), server::zone::templates::SharedObjectTemplate::getMaxScale(), server::zone::templates::SharedObjectTemplate::getMinScale(), SharedCreatureObjectTemplate::getSlopeModAngle(), SharedCreatureObjectTemplate::getSlopeModPercent(), SharedCreatureObjectTemplate::getSpecies(), SharedCreatureObjectTemplate::getSpeed(), SharedCreatureObjectTemplate::getSwimHeight(), hamList, height, server::zone::objects::tangible::TangibleObjectImplementation::level, maxHamList, server::zone::objects::scene::variables::DeltaVector< E >::removeAll(), runAcceleration, runSpeed, slopeModAngle, slopeModPercent, species, swimHeight, walkAcceleration, walkSpeed, and wounds.
Referenced by server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::loadTemplateData(), server::zone::objects::creature::VehicleObjectImplementation::loadTemplateData(), server::zone::objects::creature::CreatureObject::loadTemplateData(), and server::zone::objects::creature::AiAgentImplementation::loadTemplateData().
void CreatureObjectImplementation::lock (bool doLock = true) protected
Definition at line 4140 of file CreatureObject.cpp.
References _this.
void CreatureObjectImplementation::lock (ManagedObject * obj) protected
Definition at line 4144 of file CreatureObject.cpp.
References _this.
void CreatureObjectImplementation::notifyLoadFromDatabase ()
Gets called when this objects is loaded from database
Precondition
{ this locked }
Postcondition
{ this locked }
Here we are loading the schematics based on the skills that the player has, we do this incase we change the items in the schematic group.
Definition at line 1796 of file CreatureObjectImplementation.cpp.
References _this, CreatureAttribute::ACTION, SchematicList::addRewardedSchematics(), CreatureState::ALERT, server::zone::managers::skill::SkillManager::awardDraftSchematics(), bankCredits, cashCredits, clearState(), creatureBuffs, server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::managers::player::PlayerManager::fixHAM(), server::zone::objects::scene::variables::DeltaVector< E >::get(), BuffList::getBuffByIndex(), BuffList::getBuffListSize(), getHAM(), server::zone::ZoneServer::getPlayerManager(), getPlayerObject(), server::zone::objects::player::PlayerObject::getSchematics(), getSkillList(), server::zone::objects::player::PlayerObject::getSkillPoints(), Skill::getSkillPointsRequired(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), hasState(), CreatureAttribute::HEALTH, isIncapacitated(), listenToID, server::zone::objects::creature::buffs::Buff::loadBuffDurationEvent(), CreatureAttribute::MIND, server::zone::objects::scene::SceneObjectImplementation::server, setHAM(), setMoodString(), setPosture(), server::zone::objects::player::PlayerObject::setSkillPoints(), server::zone::objects::scene::variables::DeltaVector< E >::size(), server::zone::managers::skill::SkillManager::updateXpLimits(), CreaturePosture::UPRIGHT, and watchToID.
Referenced by server::zone::objects::creature::CreatureObject::notifyLoadFromDatabase().
int CreatureObjectImplementation::notifyObjectDestructionObservers (TangibleObject * attacker, int condition) virtual
Is called when this object is destroyed
Precondition
{ this, attacker locked }
Postcondition
{ this, attacker locked }
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Reimplemented in server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 2614 of file CreatureObjectImplementation.cpp.
References _this, getActorObject(), server::zone::Zone::getCreatureManager(), server::zone::ZoneServer::getPlayerManager(), getPlayerObject(), server::zone::objects::scene::SceneObjectImplementation::getZone(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), and server::zone::managers::player::PlayerManager::notifyDestruction().
Referenced by inflictDamage(), server::zone::objects::creature::VehicleObjectImplementation::notifyObjectDestructionObservers(), server::zone::objects::creature::AiAgentImplementation::notifyObjectDestructionObservers(), and server::zone::objects::creature::CreatureObject::notifyObjectDestructionObservers().
int CreatureObjectImplementation::notifyObjectInserted (SceneObject * object) virtual
Is called when this object has been inserted with an object
Parameters
object object that has been inserted
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 1875 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObject::isWeaponObject(), and setWeapon().
Referenced by server::zone::objects::creature::CreatureObject::notifyObjectInserted().
int CreatureObjectImplementation::notifyObjectKillObservers (TangibleObject * killer)
Is called when this object is killed
Precondition
{ this, killer locked }
Postcondition
{ this, killer locked }
Parameters
killer The killer.
Definition at line 2635 of file CreatureObjectImplementation.cpp.
References ObserverEventType::PLAYERKILLED.
Referenced by server::zone::objects::creature::CreatureObject::notifyObjectKillObservers().
int CreatureObjectImplementation::notifyObjectRemoved (SceneObject * object) virtual
Is called when an object was removed
Parameters
object object that has been inserted
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 1882 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObject::isWeaponObject(), and setWeapon().
Referenced by server::zone::objects::creature::CreatureObject::notifyObjectRemoved().
void CreatureObjectImplementation::notifyPostureChange (int newPosture)
Definition at line 2185 of file CreatureObjectImplementation.cpp.
References CreatureState::ALERT, server::zone::objects::scene::SceneObjectImplementation::getObservers(), hasState(), ObserverEventType::POSITIONCHANGED, ObserverEventType::POSTURECHANGED, and server::zone::objects::scene::SceneObjectImplementation::server.
Referenced by server::zone::objects::creature::CreatureObject::notifyPostureChange(), and setPosture().
void CreatureObjectImplementation::notifySelfPositionUpdate () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 2199 of file CreatureObjectImplementation.cpp.
References _this, server::zone::Zone::getPlanetManager(), server::zone::objects::scene::SceneObjectImplementation::getZone(), TerrainManager::notifyPositionUpdate(), and updateLocomotion().
Referenced by server::zone::objects::creature::CreatureObject::notifySelfPositionUpdate().
CreatureObjectImplementation::operator const CreatureObject * ()
Definition at line 4136 of file CreatureObject.cpp.
void CreatureObjectImplementation::playEffect (const String & file, const String & aux)
Definition at line 1935 of file CreatureObjectImplementation.cpp.
References _this, and server::zone::objects::scene::SceneObjectImplementation::broadcastMessage().
Referenced by server::zone::objects::creature::CreatureObject::playEffect(), playEffect(), and setState().
void CreatureObjectImplementation::playEffect (const String & file)
Definition at line 5201 of file CreatureObject.cpp.
References playEffect().
void CreatureObjectImplementation::playMusicMessage (const String & file)
Sends a PlayMusicMessage
Definition at line 423 of file CreatureObjectImplementation.cpp.
References sendMessage().
Referenced by server::zone::objects::creature::CreatureObject::playMusicMessage().
void CreatureObjectImplementation::queueDizzyFallEvent () virtual
Reimplemented in server::zone::objects::creature::AiAgentImplementation.
Definition at line 2131 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::addPendingTask(), and server::zone::objects::scene::SceneObjectImplementation::getPendingTask().
Referenced by server::zone::objects::creature::AiAgentImplementation::queueDizzyFallEvent(), and server::zone::objects::creature::CreatureObject::queueDizzyFallEvent().
void CreatureObjectImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Reimplemented in server::zone::objects::creature::AiAgentImplementation, server::zone::objects::creature::VehicleObjectImplementation, server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation, server::zone::objects::creature::CreatureImplementation, and server::zone::objects::creature::NonPlayerCreatureObjectImplementation.
Definition at line 4175 of file CreatureObject.cpp.
References initializeTransientMembers(), and readObjectMember().
bool CreatureObjectImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 4194 of file CreatureObject.cpp.
References accelerationMultiplierBase, accelerationMultiplierMod, bankCredits, baseHAM, cashCredits, controlDevice, cooldownTimerMap, creatureBuffs, currentSpeed, damageOverTimeList, encumbrances, factionRank, frozen, gender, group, groupInviteCounter, groupInviterID, guild, hamList, height, instrumentID, invisible, lastSuccessfulCombatAction, linkedCreature, listenToID, locomotion, maxHamList, moodID, moodString, nextAction, performanceAnimation, performanceCounter, posture, runAcceleration, runSpeed, screenPlayStates, shockWounds, skillList, skillModList, slopeModAngle, slopeModPercent, species, speedMultiplierBase, speedMultiplierMod, speedMultiplierModChanges, stateBitmask, swimHeight, targetID, templateString, terrainNegotiation, timeOfDeath, turnScale, walkAcceleration, walkSpeed, watchToID, weapon, wearablesVector, and wounds.
Referenced by readObject(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::readObjectMember(), server::zone::objects::creature::VehicleObjectImplementation::readObjectMember(), and server::zone::objects::creature::AiAgentImplementation::readObjectMember().
void CreatureObjectImplementation::removeAllSkillModsOfType (const int modType, bool notifyClient = true) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 1245 of file CreatureObjectImplementation.cpp.
References SkillModList::getSkillModGroup(), removeSkillMod(), and skillModList.
Referenced by server::zone::objects::creature::CreatureObject::removeAllSkillModsOfType().
void CreatureObjectImplementation::removeAttackDelay ()
Definition at line 5103 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::removeAttackDelay().
bool server::zone::objects::creature::CreatureObjectImplementation::removeBuff (unsigned int buffcrc)
Removes the buff from the creature, activating it and sending packets if it is a player. Buffs should never be removed from the list without sending of packets.
Parameters
buffcrc The buff crc to remove from the buff list.
Referenced by clearState(), server::zone::objects::creature::CreatureObject::removeBuff(), removeStateBuff(), and setCombatState().
void CreatureObjectImplementation::removeBuff (Buff * buff)
Removes the buff from the creature, activating it and sending packets if it is a player. Buffs should never be removed from the list without sending of packets.
Parameters
buffcrc The buff object to remove from the list.
Definition at line 2171 of file CreatureObjectImplementation.cpp.
References creatureBuffs, server::zone::objects::creature::buffs::Buff::getBuffCRC(), and BuffList::removeBuff().
void CreatureObjectImplementation::removeSkill (Skill * skill, bool notifyClient = true)
Removes the specified skillbox from this object
Precondition
{ this object is locked }
Postcondition
{ this obejct is locked, skillbox is removed }
Parameters
skillBox skillBox to remove
notifyClient if set true the client will be updated with the changes
Definition at line 1174 of file CreatureObjectImplementation.cpp.
References DeltaMessage::close(), server::zone::objects::scene::variables::DeltaVector< E >::contains(), SkillList::remove(), sendMessage(), skillList, and DeltaMessage::startUpdate().
Referenced by server::zone::objects::creature::CreatureObject::removeSkill(), and removeSkill().
void CreatureObjectImplementation::removeSkill (const String & skill, bool notifyClient = true)
Removes the specified skillbox from this object
Precondition
{ this object is locked }
Postcondition
{ this obejct is locked, skillbox is removed }
Parameters
skillBox skillBox to remove
notifyClient if set true the client will be updated with the changes
Definition at line 1191 of file CreatureObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::managers::skill::SkillManager::getSkill(), removeSkill(), and server::zone::objects::scene::SceneObjectImplementation::server.
void CreatureObjectImplementation::removeSkillMod (const int modType, const String & skillMod, int value, bool notifyClient = true) virtual
Removes skill mod from the list (same as setting to 0)
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
skillMod skill mod to remove
notifyClient if set true the client will be updated with the changes
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 1241 of file CreatureObjectImplementation.cpp.
References addSkillMod().
Referenced by removeAllSkillModsOfType(), and server::zone::objects::creature::CreatureObject::removeSkillMod().
bool CreatureObjectImplementation::removeStateBuff (unsigned long long state)
Definition at line 4935 of file CreatureObject.cpp.
References removeBuff().
Referenced by server::zone::objects::creature::CreatureObject::removeStateBuff().
void CreatureObjectImplementation::removeWearableObject (TangibleObject * object, bool notifyClient = true)
Definition at line 2687 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), server::zone::objects::scene::variables::DeltaVector< E >::find(), WearablesDeltaVector::remove(), DeltaMessage::startUpdate(), and wearablesVector.
Referenced by server::zone::objects::creature::CreatureObject::removeWearableObject().
void CreatureObjectImplementation::rlock (bool doLock = true) protected
Definition at line 4148 of file CreatureObject.cpp.
References _this.
void CreatureObjectImplementation::runlock (bool doLock = true) protected
Definition at line 4164 of file CreatureObject.cpp.
References _this.
void CreatureObjectImplementation::selectConversationOption (int option, SceneObject * obj) virtual
sends the conversation list
Precondition
{this locked, player locked }
Postcondition
{ this locked, player locked }
Reimplemented in server::zone::objects::creature::AiAgentImplementation, and server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation.
Definition at line 5045 of file CreatureObject.cpp.
Referenced by server::zone::objects::creature::CreatureObject::selectConversationOption().
void CreatureObjectImplementation::sendBaselinesTo (SceneObject * player) virtual
Sends the CREO baseline messages of this object to the specified player
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the baseline messages }
Parameters
player SceneObject that will receive the baselines
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 346 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::getZone(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::sendMessage(), server::zone::objects::tangible::TangibleObjectImplementation::sendPvpStatusTo(), and server::zone::objects::scene::SceneObjectImplementation::zone.
Referenced by server::zone::objects::creature::CreatureObject::sendBaselinesTo(), and server::zone::objects::creature::AiAgentImplementation::sendBaselinesTo().
void CreatureObjectImplementation::sendBuffsTo (CreatureObject * creature)
Definition at line 4945 of file CreatureObject.cpp.
References creatureBuffs, and sendTo().
Referenced by server::zone::objects::creature::CreatureObject::sendBuffsTo().
void CreatureObjectImplementation::sendConversationStartTo (SceneObject * player) virtual
sends the conversation list
Precondition
{this locked, player locked }
Postcondition
{ this locked, player locked }
Reimplemented in server::zone::objects::creature::AiAgentImplementation, and server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation.
Definition at line 5039 of file CreatureObject.cpp.
References getActorObject(), isAiActor(), and server::zone::objects::creature::ai::AiActor::sendConversationStartTo().
Referenced by server::zone::objects::creature::CreatureObject::sendConversationStartTo().
void CreatureObjectImplementation::sendExecuteConsoleCommand (const String & command)
Sends a ExecuteConsoleCommand to the client
Parameters
command example "/attack"
Definition at line 2420 of file CreatureObjectImplementation.cpp.
References sendMessage().
Referenced by server::zone::objects::creature::CreatureObject::sendExecuteConsoleCommand().
void CreatureObjectImplementation::sendMessage (BasePacket * msg) virtual
Sends a message to client
Precondition
{ }
Postcondition
{ message is sent to client }
Parameters
msg BasePacket to send
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 2382 of file CreatureObjectImplementation.cpp.
References owner.
Referenced by addSkill(), addSkillMod(), clearQueueAction(), playMusicMessage(), removeSkill(), sendExecuteConsoleCommand(), server::zone::objects::creature::CreatureObject::sendMessage(), sendNewbieTutorialEnableHudElement(), sendNewbieTutorialRequest(), sendOpenHolocronToPageMessage(), sendSystemMessage(), setAccelerationMultiplierBase(), setAccelerationMultiplierMod(), setBankCredits(), setCashCredits(), setListenToID(), setRunSpeed(), setSpeedMultiplierBase(), setSpeedMultiplierMod(), setTerrainNegotiation(), and setTurnScale().
void CreatureObjectImplementation::sendNewbieTutorialEnableHudElement (const String & ui, bool enable = true)
Sends NewbieTutorialEnableHud
Definition at line 440 of file CreatureObjectImplementation.cpp.
References sendMessage().
Referenced by server::zone::objects::creature::CreatureObject::sendNewbieTutorialEnableHudElement().
void CreatureObjectImplementation::sendNewbieTutorialRequest (const String & request)
Sends a tutorial request
Definition at line 433 of file CreatureObjectImplementation.cpp.
References sendMessage().
Referenced by server::zone::objects::creature::CreatureObject::sendNewbieTutorialRequest().
void CreatureObjectImplementation::sendOpenHolocronToPageMessage ()
Definition at line 428 of file CreatureObjectImplementation.cpp.
References sendMessage().
Referenced by server::zone::objects::creature::CreatureObject::sendOpenHolocronToPageMessage().
void CreatureObjectImplementation::sendSlottedObjectsTo (SceneObject * player) virtual
Sends the contained slotted objects to the specified player
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the slotted objects }
Parameters
player SceneObject that will receive the objects
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 379 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::getSlottedObject(), and server::zone::objects::scene::SceneObjectImplementation::getSlottedObjectsSize().
Referenced by server::zone::objects::creature::CreatureObject::sendSlottedObjectsTo().
void CreatureObjectImplementation::sendSystemMessage (const String & message)
Sends a system message to the client of this object
Precondition
{}
Postcondition
{ this object received the message }
Parameters
message string message to send
Definition at line 415 of file CreatureObjectImplementation.cpp.
References isPlayerCreature().
Referenced by clearState(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), setNextAttackDelay(), and setState().
void CreatureObjectImplementation::sendSystemMessage (UnicodeString & message)
Sends a system message to the client of this object
Precondition
{}
Postcondition
{ this object received the message }
Parameters
message unicode message to send
Definition at line 467 of file CreatureObjectImplementation.cpp.
References isPlayerCreature(), and sendMessage().
void CreatureObjectImplementation::sendSystemMessage (StringIdChatParameter & stringid)
Sends a system message to the client of this object
Precondition
{}
Postcondition
{ this object received the message }
Parameters
message StringIdChatParameter message to send
Definition at line 458 of file CreatureObjectImplementation.cpp.
References isPlayerCreature(), and sendMessage().
void CreatureObjectImplementation::sendTo (SceneObject * player, bool doClose) virtual
Sends the necessary messages to player in order to create this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received this object }
Parameters
player SceneObject that will receive the messages
doClose if true a SceneObjectCloseMessage is sent to finish the object
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 283 of file CreatureObjectImplementation.cpp.
References _this, and isInvisible().
Referenced by sendBuffsTo(), server::zone::objects::creature::CreatureObject::sendTo(), sendToOwner(), and setState().
void CreatureObjectImplementation::sendToOwner (bool doClose = true) virtual
Sends the necessary messages to owner client
Precondition
{ this object is locked }
Postcondition
{ this object is locked, owner received its own scene object }
Parameters
doClose if true a SceneObjectCloseMessage is sent to finish the object
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 290 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::getRootParent(), group, server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::notifyDissapear(), server::zone::objects::scene::SceneObjectImplementation::notifyInsert(), owner, sendTo(), server::zone::objects::scene::SceneObjectImplementation::server, and server::zone::objects::scene::SceneObjectImplementation::setMovementCounter().
Referenced by server::zone::objects::creature::CreatureObject::sendToOwner().
void CreatureObjectImplementation::setAccelerationMultiplierBase (float newMultiplierBase, bool notifyClient = true)
Updates the acceleration speed multiplier base
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
newMultiplierBase new multiplier base to set
notifyClient if set true the client will be updated with the changes
Definition at line 1412 of file CreatureObjectImplementation.cpp.
References _this, accelerationMultiplierBase, DeltaMessage::close(), sendMessage(), and CreatureObjectDeltaMessage4::updateAccelerationMultiplierBase().
Referenced by server::zone::objects::creature::CreatureObject::setAccelerationMultiplierBase().
void CreatureObjectImplementation::setAccelerationMultiplierMod (float newMultiplierMod, bool notifyClient = true)
Updates the acceleration speed multiplier mod
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
newMultiplierMod new multiplier mod to set
notifyClient if set true the client will be updated with the changes
Definition at line 1429 of file CreatureObjectImplementation.cpp.
References _this, accelerationMultiplierMod, DeltaMessage::close(), getSkillMod(), sendMessage(), and CreatureObjectDeltaMessage4::updateAccelerationMultiplierMod().
Referenced by server::zone::objects::creature::CreatureObject::setAccelerationMultiplierMod(), and updateSpeedAndAccelerationMods().
void CreatureObjectImplementation::setAimingState (int durationSeconds = 5)
Definition at line 1965 of file CreatureObjectImplementation.cpp.
References _this, addBuff(), CreatureState::AIMING, getSkillMod(), hasState(), server::zone::objects::creature::buffs::Buff::setSkillModifier(), and weapon.
Referenced by server::zone::objects::creature::CreatureObject::setAimingState().
void CreatureObjectImplementation::setBankCredits (int credits, bool notifyClient = true)
Updates the bank credits of this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified bank credits }
Parameters
credits the new credits
notifyClient if set true the client will be updated with the changes
Definition at line 1123 of file CreatureObjectImplementation.cpp.
References bankCredits, DeltaMessage::close(), sendMessage(), and CreatureObjectDeltaMessage1::updateBankCredits().
Referenced by addBankCredits(), server::zone::objects::creature::CreatureObject::setBankCredits(), and subtractBankCredits().
void CreatureObjectImplementation::setBaseHAM (int type, int value, bool notifyClient = true)
Updates a specific type of the Base HAM
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the Base HAM type updated to the new value }
Parameters
type specifies which Base HAM type to update
value the new value
notifyClient if set true the client will be updated with the changes
Definition at line 975 of file CreatureObjectImplementation.cpp.
References baseHAM, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::scene::variables::DeltaVector< E >::set(), and DeltaMessage::startUpdate().
Referenced by server::zone::objects::creature::CreatureObject::setBaseHAM(), and server::zone::objects::creature::AiAgentImplementation::setLevel().
void CreatureObjectImplementation::setBerserkedState (unsigned int duration)
Definition at line 2009 of file CreatureObjectImplementation.cpp.
References _this, addBuff(), CreatureState::BERSERK, getSkillMod(), hasState(), and server::zone::objects::creature::buffs::Buff::setStartFlyText().
Referenced by server::zone::objects::creature::CreatureObject::setBerserkedState().
void CreatureObjectImplementation::setBlindedState (int durationSeconds = 5)
Definition at line 2049 of file CreatureObjectImplementation.cpp.
References _this, addBuff(), CreatureState::BLINDED, hasState(), and server::zone::objects::creature::buffs::Buff::setStartFlyText().
Referenced by server::zone::objects::creature::CreatureObject::setBlindedState().
void CreatureObjectImplementation::setCashCredits (int credits, bool notifyClient = true)
Update the cash credits of this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified cash credits }
Parameters
credits the new credits
notifyClient if set true the client will be updated with the changes
Definition at line 1140 of file CreatureObjectImplementation.cpp.
References cashCredits, DeltaMessage::close(), sendMessage(), and CreatureObjectDeltaMessage1::updateCashCredits().
Referenced by addCashCredits(), server::zone::objects::creature::CreatureObject::setCashCredits(), and subtractCashCredits().
void CreatureObjectImplementation::setClient (ZoneClientSession * cli)
Definition at line 5088 of file CreatureObject.cpp.
References owner.
Referenced by server::zone::objects::creature::CreatureObject::setClient().
void CreatureObjectImplementation::setCombatState () virtual
Sets the combat state
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object is in a combat state }
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 593 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), LogoutTask::cancelLogout(), DeltaMessage::close(), CreatureState::COMBAT, server::zone::objects::scene::SceneObjectImplementation::getPendingTask(), isEntertaining(), lastSuccessfulCombatAction, CreatureState::PEACE, posture, removeBuff(), setPosture(), CreaturePosture::SITTING, ObserverEventType::STARTCOMBAT, stateBitmask, stopEntertaining(), CreatureObjectDeltaMessage3::updateCreatureBitmask(), CreatureObjectDeltaMessage3::updateState(), and CreaturePosture::UPRIGHT.
Referenced by server::zone::objects::creature::CreatureObject::setCombatState().
void CreatureObjectImplementation::setControlDevice (ControlDevice * device)
Definition at line 5034 of file CreatureObject.cpp.
References controlDevice.
Referenced by server::zone::objects::creature::CreatureObject::setControlDevice().
void CreatureObjectImplementation::setCoverState (int durationSeconds = 40)
Definition at line 1993 of file CreatureObjectImplementation.cpp.
References _this, addBuff(), CreatureState::COVER, hasState(), CreaturePosture::PRONE, setPosture(), and server::zone::objects::creature::buffs::Buff::setStartFlyText().
Referenced by server::zone::objects::creature::CreatureObject::setCoverState().
void CreatureObjectImplementation::setCreatureLink (CreatureObject * object, bool notifyClient = true)
Updates creatureLinkID with specified object
Precondition
{ this is locked }
Postcondition
{ this is locked }
Definition at line 1889 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), linkedCreature, and CreatureObjectDeltaMessage3::updateCreatureLinkID().
Referenced by server::zone::objects::creature::CreatureObject::setCreatureLink().
void CreatureObjectImplementation::setCurrentSpeed (float newSpeed)
Definition at line 4925 of file CreatureObject.cpp.
References currentSpeed.
Referenced by server::zone::objects::creature::CreatureObject::setCurrentSpeed(), and setPosture().
void CreatureObjectImplementation::setCurrentWeather (byte value)
Definition at line 5788 of file CreatureObject.cpp.
References currentWeather.
Referenced by server::zone::objects::creature::CreatureObject::setCurrentWeather().
void CreatureObjectImplementation::setCurrentWind (byte value)
Definition at line 5798 of file CreatureObject.cpp.
References currentWind.
Referenced by server::zone::objects::creature::CreatureObject::setCurrentWind().
void CreatureObjectImplementation::setDizziedState (int durationSeconds = 5)
Definition at line 1954 of file CreatureObjectImplementation.cpp.
References _this, addBuff(), CreatureState::DIZZY, hasState(), and server::zone::objects::creature::buffs::Buff::setStartFlyText().
Referenced by server::zone::objects::creature::CreatureObject::setDizziedState().
void CreatureObjectImplementation::setEncumbrance (int type, int value, bool notifyClient = true)
Updates a specific type of the Encumbrance
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the Encumbrance type updated to the new value }
Parameters
type specifies which Encumbrance type to update
value the new value
notifyClient if set true the client will be updated with the changes
Definition at line 1079 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), encumbrances, server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::scene::variables::DeltaVector< E >::set(), and DeltaMessage::startUpdate().
Referenced by addEncumbrance(), and server::zone::objects::creature::CreatureObject::setEncumbrance().
void CreatureObjectImplementation::setFactionRank (int rank, bool notifyClient = true)
Definition at line 1481 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), factionRank, and CreatureObjectDeltaMessage3::updateFactionRank().
Referenced by server::zone::objects::creature::CreatureObject::setFactionRank().
void CreatureObjectImplementation::setGuildObject (GuildObject * guildobj)
Definition at line 5424 of file CreatureObject.cpp.
References guild.
Referenced by server::zone::objects::creature::CreatureObject::setGuildObject().
void CreatureObjectImplementation::setHAM (int type, int value, bool notifyClient = true)
Updates a specific type of the HAM
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the HAM type updated to the new value }
Parameters
type specifies which HAM type to update
value the new value
notifyClient if set true the client will be updated with the changes
Definition at line 830 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), server::zone::objects::scene::variables::DeltaVector< E >::get(), hamList, server::zone::objects::scene::variables::DeltaVector< E >::set(), and DeltaMessage::startUpdate().
Referenced by healDamage(), inflictDamage(), notifyLoadFromDatabase(), server::zone::objects::creature::CreatureObject::setHAM(), server::zone::objects::creature::AiAgentImplementation::setLevel(), and setWounds().
void CreatureObjectImplementation::setHeight (float heigh, bool notifyClient = true)
Definition at line 547 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), height, and CreatureObjectDeltaMessage3::updateHeight().
Referenced by server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), and server::zone::objects::creature::CreatureObject::setHeight().
void CreatureObjectImplementation::setInstrumentID (int instrumentid, bool notifyClient = true)
Updates the instrument id to the specified object id
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified weapon id }
Parameters
instrumentid the new instrument id
notifyClient if set true the client will be updated with the changes
Definition at line 516 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), instrumentID, and CreatureObjectDeltaMessage6::updateInstrumentID().
Referenced by server::zone::objects::creature::CreatureObject::setInstrumentID().
void CreatureObjectImplementation::setIntimidatedState (unsigned int mod, int durationSeconds = 15)
Definition at line 2062 of file CreatureObjectImplementation.cpp.
References _this, addBuff(), getSkillMod(), hasState(), CreatureState::INTIMIDATED, server::zone::objects::creature::buffs::Buff::setEndFlyText(), server::zone::objects::creature::buffs::Buff::setSkillModifier(), and server::zone::objects::creature::buffs::Buff::setStartFlyText().
Referenced by server::zone::objects::creature::CreatureObject::setIntimidatedState().
void CreatureObjectImplementation::setInvisible (bool invis)
Definition at line 5826 of file CreatureObject.cpp.
References invisible.
Referenced by server::zone::objects::creature::CreatureObject::setInvisible().
void CreatureObjectImplementation::setLevel (int level) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 502 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), and CreatureObjectDeltaMessage6::updateLevel().
Referenced by server::zone::objects::creature::AiAgentImplementation::setLevel(), and server::zone::objects::creature::CreatureObject::setLevel().
void CreatureObjectImplementation::setListenToID (unsigned long long id, bool notifyClient = true)
Updates listen id
Definition at line 1579 of file CreatureObjectImplementation.cpp.
References _this, DeltaMessage::close(), listenToID, sendMessage(), and CreatureObjectDeltaMessage4::updateListenToID().
Referenced by server::zone::objects::creature::CreatureObject::setListenToID().
void CreatureObjectImplementation::setMaxHAM (int type, int value, bool notifyClient = true)
Updates a specific type of the Max HAM
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the Max HAM type updated to the new value }
Parameters
type specifies which Max HAM type to update
value the new value
notifyClient if set true the client will be updated with the changes
Definition at line 1050 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), server::zone::objects::scene::variables::DeltaVector< E >::get(), hamList, healDamage(), maxHamList, server::zone::objects::scene::variables::DeltaVector< E >::set(), setWounds(), DeltaMessage::startUpdate(), and wounds.
Referenced by addMaxHAM(), server::zone::objects::creature::AiAgentImplementation::setLevel(), and server::zone::objects::creature::CreatureObject::setMaxHAM().
void CreatureObjectImplementation::setMeditateState ()
Definition at line 2122 of file CreatureObjectImplementation.cpp.
References CreatureState::ALERT, isInCombat(), setMoodString(), setPosture(), setState(), and CreaturePosture::SITTING.
Referenced by server::zone::objects::creature::CreatureObject::setMeditateState().
void CreatureObjectImplementation::setMood (byte moodID, bool notifyClient = true)
Sets characters mood
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
moodID mood to set
Definition at line 1397 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), Races::getMood(), Races::getMoodStr(), moodID, moodString, CreatureObjectDeltaMessage6::updateMoodID(), and CreatureObjectDeltaMessage6::updateMoodStr().
Referenced by initializeTransientMembers(), and server::zone::objects::creature::CreatureObject::setMood().
void CreatureObjectImplementation::setMoodString (const String & animation, bool notifyClient = true)
Sets a new mood animation
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
mood mood animation string
Definition at line 1549 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), moodString, and CreatureObjectDeltaMessage6::updateMoodStr().
Referenced by notifyLoadFromDatabase(), setMeditateState(), and server::zone::objects::creature::CreatureObject::setMoodString().
bool CreatureObjectImplementation::setNextAttackDelay (unsigned int mod, int del)
Definition at line 2102 of file CreatureObjectImplementation.cpp.
References cooldownTimerMap, isPlayerCreature(), sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), and server::zone::objects::scene::SceneObjectImplementation::showFlyText().
Referenced by server::zone::objects::creature::CreatureObject::setNextAttackDelay().
void CreatureObjectImplementation::setPerformanceAnimation (const String & animation, bool notifyClient = true)
Updates the preformance animation string
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the animation updated }
Parameters
animation new animation
notifyClient if set true the client will be updated with the changes
Definition at line 1594 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), performanceAnimation, and CreatureObjectDeltaMessage6::updatePerformanceAnimation().
Referenced by server::zone::objects::creature::CreatureObject::setPerformanceAnimation().
void CreatureObjectImplementation::setPerformanceCounter (int counter, bool notifyClient = true)
Updates the preformance counter
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the counter updated }
Parameters
counter new performance counter
notifyClient if set true the client will be updated with the changes
Definition at line 1563 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), performanceCounter, and CreatureObjectDeltaMessage6::updatePerformanceCounter().
Referenced by server::zone::objects::creature::CreatureObject::setPerformanceCounter().
void CreatureObjectImplementation::setPosture (int newPosture, bool notifyClient = true) virtual
Sets a new posture
Precondition
{ this object is locked }
Postcondition
{this object is locked, this object has the new posture set }
Parameters
newPosture posture to set
notifyClient if set true the client will be updated with the changes
Reimplemented in server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 1280 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessages(), clearState(), DeltaMessage::close(), CreatureState::COVER, CreaturePosture::DRIVINGVEHICLE, hasState(), isInCover(), notifyPostureChange(), posture, CreaturePosture::PRONE, CreaturePosture::RIDINGCREATURE, setCurrentSpeed(), CreaturePosture::SITTING, CreatureState::SITTINGONCHAIR, CreaturePosture::SKILLANIMATING, updateLocomotion(), CreatureObjectDeltaMessage3::updatePosture(), updateSpeedAndAccelerationMods(), and CreaturePosture::UPRIGHT.
Referenced by healDamage(), server::zone::objects::creature::AiAgentImplementation::notifyDespawn(), notifyLoadFromDatabase(), setCombatState(), setCoverState(), setMeditateState(), server::zone::objects::creature::CreatureObject::setPosture(), and setState().
void CreatureObjectImplementation::setRalliedState (int durationSeconds = 5)
Definition at line 1982 of file CreatureObjectImplementation.cpp.
References _this, addBuff(), hasState(), CreatureState::RALLIED, and server::zone::objects::creature::buffs::Buff::setStartFlyText().
Referenced by server::zone::objects::creature::CreatureObject::setRalliedState().
void CreatureObjectImplementation::setRootedState (int durationSeconds = 20)
Definition at line 2091 of file CreatureObjectImplementation.cpp.
References _this, addBuff(), CreatureState::FROZEN, hasState(), and server::zone::objects::creature::buffs::Buff::setStartFlyText().
Referenced by server::zone::objects::creature::CreatureObject::setRootedState().
void CreatureObjectImplementation::setRunSpeed (float newSpeed, bool notifyClient = true)
Updates the run speed
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Definition at line 1532 of file CreatureObjectImplementation.cpp.
References _this, DeltaMessage::close(), runSpeed, sendMessage(), and CreatureObjectDeltaMessage4::updateRunSpeed().
Referenced by server::zone::objects::creature::CreatureObject::setRunSpeed().
void CreatureObjectImplementation::setScreenPlayState (const String & screenPlay, unsigned long long state)
Definition at line 5163 of file CreatureObject.cpp.
References screenPlayStates.
Referenced by server::zone::objects::creature::CreatureObject::setScreenPlayState().
void CreatureObjectImplementation::setShockWounds (int newShock, bool notifyClient = true)
Updates shock wounds
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified target id }
Parameters
shock new shock wounds
notifyClient if set true the client will be updated with the changes
Definition at line 563 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), shockWounds, and CreatureObjectDeltaMessage3::updateShockWounds().
Referenced by addShockWounds(), and server::zone::objects::creature::CreatureObject::setShockWounds().
void CreatureObjectImplementation::setSnaredState (int durationSeconds = 20)
Definition at line 2080 of file CreatureObjectImplementation.cpp.
References _this, addBuff(), hasState(), CreatureState::IMMOBILIZED, and server::zone::objects::creature::buffs::Buff::setStartFlyText().
Referenced by server::zone::objects::creature::CreatureObject::setSnaredState().
void CreatureObjectImplementation::setSpeedMultiplierBase (float newMultiplierBase, bool notifyClient = true)
Updates the speed multiplier base
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
newMultiplierBase new multiplier base to set
notifyClient if set true the client will be updated with the changes
Definition at line 1447 of file CreatureObjectImplementation.cpp.
References _this, DeltaMessage::close(), sendMessage(), speedMultiplierBase, and CreatureObjectDeltaMessage4::updateSpeedMultiplierBase().
Referenced by server::zone::objects::creature::CreatureObject::setSpeedMultiplierBase().
void CreatureObjectImplementation::setSpeedMultiplierMod (float newMultiplierMod, bool notifyClient = true) virtual
Updates the speed multiplier mod
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
newMultiplierMod new multiplier mod to set
notifyClient if set true the client will be updated with the changes
Definition at line 1496 of file CreatureObjectImplementation.cpp.
References _this, DeltaMessage::close(), CreatureState::COVER, getSkillMod(), hasBuff(), hasSkill(), posture, CreaturePosture::PRONE, sendMessage(), speedMultiplierMod, speedMultiplierModChanges, CreatureObjectDeltaMessage4::updateSpeedMultiplierMod(), and CreaturePosture::UPRIGHT.
Referenced by server::zone::objects::creature::CreatureObject::setSpeedMultiplierMod(), and updateSpeedAndAccelerationMods().
bool CreatureObjectImplementation::setState (unsigned long long state, bool notifyClient = true)
Sets a new state to the statebitmask
Precondition
{ this object is locked }
Postcondition
{ this object is locked, stateBitmask has the new state }
Parameters
state state to add
Definition at line 658 of file CreatureObjectImplementation.cpp.
References _this, CreatureState::AIMING, CreatureState::BERSERK, CreatureState::BLEEDING, CreatureState::BLINDED, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), CreatureState::COVER, CreatureState::DISEASED, CreatureState::DIZZY, CreatureState::FROZEN, server::zone::Zone::getInRangeObjects(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObjectImplementation::getParent(), server::zone::objects::scene::SceneObjectImplementation::getWorldPositionX(), server::zone::objects::scene::SceneObjectImplementation::getWorldPositionY(), server::zone::objects::scene::SceneObjectImplementation::getZone(), CreatureState::IMMOBILIZED, CreatureState::INTIMIDATED, CreatureState::ONFIRE, playEffect(), CreatureState::POISONED, CreatureState::RALLIED, server::zone::objects::scene::SceneObjectImplementation::sendDestroyTo(), sendSystemMessage(), sendTo(), setPosture(), server::zone::objects::scene::SceneObjectImplementation::showFlyText(), CreaturePosture::SITTING, CreatureState::SITTINGONCHAIR, stateBitmask, CreatureState::STUNNED, CreatureObjectDeltaMessage3::updatePosture(), and CreatureObjectDeltaMessage3::updateState().
Referenced by setMeditateState(), and server::zone::objects::creature::CreatureObject::setState().
void CreatureObjectImplementation::setStunnedState (int durationSeconds = 5)
Definition at line 2026 of file CreatureObjectImplementation.cpp.
References _this, addBuff(), getSkillMod(), hasState(), server::zone::objects::creature::buffs::Buff::setStartFlyText(), and CreatureState::STUNNED.
Referenced by server::zone::objects::creature::CreatureObject::setStunnedState().
void CreatureObjectImplementation::setTargetID (unsigned long long targetID, bool notifyClient = true)
Updates the target id to the specified object id
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified target id }
Parameters
objectID the new target id
notifyClient if set true the client will be updated with the changes
Definition at line 533 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), targetID, and CreatureObjectDeltaMessage6::updateTarget().
Referenced by server::zone::objects::creature::CreatureObject::setTargetID().
void CreatureObjectImplementation::setTerrainNegotiation (float value, bool notifyClient = true)
Updates the terrain negotiation variable?
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified terrain negotiation }
Parameters
terrain new terrain negotiation
notifyClient if set true the client will be updated with the changes
Definition at line 1610 of file CreatureObjectImplementation.cpp.
References _this, DeltaMessage::close(), sendMessage(), terrainNegotiation, and CreatureObjectDeltaMessage4::updateTerrainNegotiation().
Referenced by server::zone::objects::creature::CreatureObject::setTerrainNegotiation().
void CreatureObjectImplementation::setTurnScale (float newMultiplierMod, bool notifyClient = true) virtual
Updates the turn scale mod
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
newMultiplierMod new multiplier mod to set
notifyClient if set true the client will be updated with the changes
Definition at line 1464 of file CreatureObjectImplementation.cpp.
References _this, DeltaMessage::close(), sendMessage(), turnScale, and CreatureObjectDeltaMessage4::updateTurnScale().
Referenced by server::zone::objects::creature::CreatureObject::setTurnScale(), and updateSpeedAndAccelerationMods().
void CreatureObjectImplementation::setWatchToID (unsigned long long id)
Definition at line 5563 of file CreatureObject.cpp.
References watchToID.
Referenced by server::zone::objects::creature::CreatureObject::setWatchToID().
void CreatureObjectImplementation::setWeapon (WeaponObject * weao, bool notifyClient = false)
Updates the weapon to the specified object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified weapon id }
Parameters
weao the new weapon
notifyClient if set true the client will be updated with the changes
Definition at line 485 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), CreatureObjectDeltaMessage6::updateWeapon(), and weapon.
Referenced by notifyObjectInserted(), notifyObjectRemoved(), and server::zone::objects::creature::CreatureObject::setWeapon().
void CreatureObjectImplementation::setWounds (int type, int value, bool notifyClient = true)
Updates a specific type of the Wounds
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the Wounds type updated to the new value }
Parameters
type specifies which Wounds type to update
value the new value
notifyClient if set true the client will be updated with the changes
Definition at line 997 of file CreatureObjectImplementation.cpp.
References _this, baseHAM, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), server::zone::objects::scene::variables::DeltaVector< E >::get(), getHAM(), maxHamList, server::zone::objects::scene::variables::DeltaVector< E >::set(), setHAM(), DeltaMessage::startUpdate(), and wounds.
Referenced by addWounds(), healWound(), setMaxHAM(), and server::zone::objects::creature::CreatureObject::setWounds().
void CreatureObjectImplementation::stopEntertaining ()
Definition at line 2366 of file CreatureObjectImplementation.cpp.
References server::zone::objects::player::sessions::EntertainingSession::cancelSession(), SessionFacadeType::ENTERTAINING, and server::zone::objects::scene::SceneObjectImplementation::getActiveSession().
Referenced by setCombatState(), and server::zone::objects::creature::CreatureObject::stopEntertaining().
void CreatureObjectImplementation::subtractBankCredits (int credits)
Definition at line 1780 of file CreatureObjectImplementation.cpp.
References bankCredits, and setBankCredits().
Referenced by server::zone::objects::creature::CreatureObject::subtractBankCredits().
void CreatureObjectImplementation::subtractCashCredits (int credits)
Definition at line 1788 of file CreatureObjectImplementation.cpp.
References cashCredits, and setCashCredits().
Referenced by server::zone::objects::creature::CreatureObject::subtractCashCredits().
void CreatureObjectImplementation::unlock (bool doLock = true) protected
Definition at line 4160 of file CreatureObject.cpp.
References _this.
void CreatureObjectImplementation::updateCooldownTimer (const String & coooldownTimer, unsigned int miliSecondsToAdd = 0)
Definition at line 5173 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::updateCooldownTimer().
void CreatureObjectImplementation::updateGroup (GroupObject * group, bool notifyClient = true)
Sets the group of this object
Precondition
{ this object is locked }
Postcondition
{this object is locked }
Parameters
group GroupObject to update
notifyClient if set true the client will be updated with the changes
Definition at line 1386 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), group, and CreatureObjectDeltaMessage6::updateGroupID().
Referenced by server::zone::objects::creature::CreatureObject::updateGroup().
void CreatureObjectImplementation::updateGroupInviterID (unsigned long long id, bool notifyClient = true)
Sets a new group inviter id
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
id object id of the inviter
notifyClient if set true the client will be updated with the changes
Definition at line 1374 of file CreatureObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), groupInviteCounter, groupInviterID, and CreatureObjectDeltaMessage6::updateInviterId().
Referenced by server::zone::objects::creature::CreatureObject::updateGroupInviterID().
void CreatureObjectImplementation::updateKnockdownRecovery ()
Definition at line 5123 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::updateKnockdownRecovery().
void CreatureObjectImplementation::updateLastKnockdown ()
Definition at line 5128 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::updateLastKnockdown().
void CreatureObjectImplementation::updateLastSuccessfulCombatAction ()
Definition at line 5118 of file CreatureObject.cpp.
References lastSuccessfulCombatAction.
Referenced by server::zone::objects::creature::CreatureObject::updateLastSuccessfulCombatAction().
void CreatureObjectImplementation::updateLocomotion () virtual
Definition at line 1356 of file CreatureObjectImplementation.cpp.
References currentSpeed, CreatureLocomotion::FAST, locomotion, posture, CreatureLocomotion::SLOW, CreatureLocomotion::STATIONARY, and walkSpeed.
Referenced by server::zone::objects::creature::AiAgentImplementation::doMovement(), notifySelfPositionUpdate(), setPosture(), and server::zone::objects::creature::CreatureObject::updateLocomotion().
void CreatureObjectImplementation::updatePostureDownRecovery ()
Definition at line 5143 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::updatePostureDownRecovery().
void CreatureObjectImplementation::updatePostureUpRecovery ()
Definition at line 5148 of file CreatureObject.cpp.
References cooldownTimerMap.
Referenced by server::zone::objects::creature::CreatureObject::updatePostureUpRecovery().
void CreatureObjectImplementation::updateSpeedAndAccelerationMods ()
Definition at line 1326 of file CreatureObjectImplementation.cpp.
References CreatureState::COVER, getSkillMod(), getTurnScale(), hasBuff(), posture, CreaturePosture::PRONE, setAccelerationMultiplierMod(), setSpeedMultiplierMod(), and setTurnScale().
Referenced by setPosture(), and server::zone::objects::creature::CreatureObject::updateSpeedAndAccelerationMods().
void CreatureObjectImplementation::updateTimeOfDeath ()
Definition at line 5093 of file CreatureObject.cpp.
References timeOfDeath.
Referenced by server::zone::objects::creature::CreatureObject::updateTimeOfDeath().
void CreatureObjectImplementation::updateToDatabaseAllObjects (bool startTask)
Definition at line 2148 of file CreatureObjectImplementation.cpp.
References creatureBuffs, and BuffList::updateBuffsToDatabase().
Referenced by server::zone::objects::creature::CreatureObject::updateToDatabaseAllObjects().
bool CreatureObjectImplementation::verifyBankCredits (int credits)
Definition at line 5018 of file CreatureObject.cpp.
References bankCredits.
Referenced by server::zone::objects::creature::CreatureObject::verifyBankCredits().
bool CreatureObjectImplementation::verifyCashCredits (int credits)
Definition at line 5007 of file CreatureObject.cpp.
References cashCredits.
Referenced by server::zone::objects::creature::CreatureObject::verifyCashCredits().
void CreatureObjectImplementation::wlock (bool doLock = true) protected
Definition at line 4152 of file CreatureObject.cpp.
References _this.
void CreatureObjectImplementation::wlock (ManagedObject * obj) protected
Definition at line 4156 of file CreatureObject.cpp.
References _this.
void CreatureObjectImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Reimplemented in server::zone::objects::creature::AiAgentImplementation, server::zone::objects::creature::VehicleObjectImplementation, server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation, server::zone::objects::creature::CreatureImplementation, and server::zone::objects::creature::NonPlayerCreatureObjectImplementation.
Definition at line 4436 of file CreatureObject.cpp.
References writeObjectMembers().
int CreatureObjectImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 4443 of file CreatureObject.cpp.
References accelerationMultiplierBase, accelerationMultiplierMod, bankCredits, baseHAM, cashCredits, controlDevice, cooldownTimerMap, creatureBuffs, currentSpeed, damageOverTimeList, encumbrances, factionRank, frozen, gender, group, groupInviteCounter, groupInviterID, guild, hamList, height, instrumentID, invisible, lastSuccessfulCombatAction, linkedCreature, listenToID, locomotion, maxHamList, moodID, moodString, nextAction, performanceAnimation, performanceCounter, posture, runAcceleration, runSpeed, screenPlayStates, shockWounds, skillList, skillModList, slopeModAngle, slopeModPercent, species, speedMultiplierBase, speedMultiplierMod, speedMultiplierModChanges, stateBitmask, swimHeight, targetID, templateString, terrainNegotiation, timeOfDeath, turnScale, walkAcceleration, walkSpeed, watchToID, weapon, wearablesVector, and wounds.
Referenced by writeObject(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::writeObjectMembers(), server::zone::objects::creature::VehicleObjectImplementation::writeObjectMembers(), and server::zone::objects::creature::AiAgentImplementation::writeObjectMembers().
Friends And Related Function Documentation
friend class CreatureObject friend
Definition at line 2667 of file CreatureObject.h.
Member Data Documentation
WeakReference<CreatureObject*> server::zone::objects::creature::CreatureObjectImplementation::_this
Definition at line 2635 of file CreatureObject.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), activateHAMRegeneration(), activateImmediateAction(), activatePassiveWoundRegeneration(), activateQueueAction(), activateStateRecovery(), addDotState(), addSkillMod(), addWearableObject(), clearCombatState(), clearDots(), clearQueueAction(), clearState(), createChildObjects(), doAnimation(), doCombatAnimation(), enqueueCommand(), executeObjectControllerAction(), handleObjectMenuSelect(), healDamage(), healDot(), healWound(), isAggressiveTo(), isAttackableBy(), isHealableBy(), lock(), notifyLoadFromDatabase(), notifyObjectDestructionObservers(), notifySelfPositionUpdate(), playEffect(), queueDizzyFallEvent(), removeWearableObject(), rlock(), runlock(), sendBaselinesTo(), sendSlottedObjectsTo(), sendTo(), sendToOwner(), setAccelerationMultiplierBase(), setAccelerationMultiplierMod(), setAimingState(), setBerserkedState(), setBlindedState(), setCombatState(), setCoverState(), setCreatureLink(), setDizziedState(), setEncumbrance(), setFactionRank(), setHAM(), setHeight(), setInstrumentID(), setIntimidatedState(), setLevel(), setListenToID(), setMaxHAM(), setMood(), setMoodString(), setPerformanceAnimation(), setPerformanceCounter(), setPosture(), setRalliedState(), setRootedState(), setRunSpeed(), setShockWounds(), setSnaredState(), setSpeedMultiplierBase(), setSpeedMultiplierMod(), setState(), setStunnedState(), setTargetID(), setTerrainNegotiation(), setTurnScale(), setWeapon(), setWounds(), unlock(), updateGroup(), updateGroupInviterID(), and wlock().
float server::zone::objects::creature::CreatureObjectImplementation::accelerationMultiplierBase protected
Definition at line 1455 of file CreatureObject.h.
Referenced by getAccelerationMultiplierBase(), initializeMembers(), readObjectMember(), setAccelerationMultiplierBase(), and writeObjectMembers().
float server::zone::objects::creature::CreatureObjectImplementation::accelerationMultiplierMod protected
Definition at line 1457 of file CreatureObject.h.
Referenced by getAccelerationMultiplierMod(), initializeMembers(), readObjectMember(), setAccelerationMultiplierMod(), and writeObjectMembers().
byte server::zone::objects::creature::CreatureObjectImplementation::actionWoundHeal protected
Definition at line 1547 of file CreatureObject.h.
Referenced by activatePassiveWoundRegeneration(), and initializeMembers().
int server::zone::objects::creature::CreatureObjectImplementation::bankCredits protected
Definition at line 1423 of file CreatureObject.h.
Referenced by addBankCredits(), getBankCredits(), initializeMembers(), notifyLoadFromDatabase(), readObjectMember(), setBankCredits(), subtractBankCredits(), verifyBankCredits(), and writeObjectMembers().
DeltaVector<int> server::zone::objects::creature::CreatureObjectImplementation::baseHAM protected
Definition at line 1431 of file CreatureObject.h.
Referenced by getBaseHAM(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), loadTemplateData(), readObjectMember(), setBaseHAM(), server::zone::objects::creature::AiAgentImplementation::setLevel(), setWounds(), and writeObjectMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::BOTHAN = 5 static
Definition at line 1570 of file CreatureObject.h.
int server::zone::objects::creature::CreatureObjectImplementation::cashCredits protected
Definition at line 1425 of file CreatureObject.h.
Referenced by addCashCredits(), getCashCredits(), initializeMembers(), notifyLoadFromDatabase(), readObjectMember(), setCashCredits(), subtractCashCredits(), verifyCashCredits(), and writeObjectMembers().
Reference<CommandQueueActionVector* > server::zone::objects::creature::CreatureObjectImplementation::commandQueue protected
Definition at line 1527 of file CreatureObject.h.
Referenced by activateQueueAction(), deleteQueueAction(), server::zone::objects::creature::AiAgentImplementation::doAttack(), enqueueCommand(), getCommandQueue(), and initializeMembers().
ManagedWeakReference<ControlDevice* > server::zone::objects::creature::CreatureObjectImplementation::controlDevice protected
Definition at line 1443 of file CreatureObject.h.
Referenced by getControlDevice(), server::zone::objects::creature::VehicleObjectImplementation::handleObjectMenuSelect(), initializeMembers(), readObjectMember(), setControlDevice(), and writeObjectMembers().
Reference<CooldownTimerMap* > server::zone::objects::creature::CreatureObjectImplementation::cooldownTimerMap protected
Definition at line 1533 of file CreatureObject.h.
Referenced by addCooldown(), checkCooldownRecovery(), checkKnockdownRecovery(), checkLastKnockdown(), checkPostureDownRecovery(), checkPostureUpRecovery(), getCooldownTime(), getCooldownTimerMap(), hasAttackDelay(), initializeMembers(), readObjectMember(), removeAttackDelay(), setNextAttackDelay(), updateCooldownTimer(), updateKnockdownRecovery(), updateLastKnockdown(), updatePostureDownRecovery(), updatePostureUpRecovery(), and writeObjectMembers().
BuffList server::zone::objects::creature::CreatureObjectImplementation::creatureBuffs protected
Definition at line 1535 of file CreatureObject.h.
Referenced by addBuff(), clearBuffs(), getBuff(), getBuffList(), getSkillModFromBuffs(), hasBuff(), hasSpice(), notifyLoadFromDatabase(), readObjectMember(), removeBuff(), sendBuffsTo(), updateToDatabaseAllObjects(), and writeObjectMembers().
float server::zone::objects::creature::CreatureObjectImplementation::currentSpeed protected
Definition at line 1471 of file CreatureObject.h.
Referenced by server::zone::objects::creature::AiAgentImplementation::doMovement(), getCurrentSpeed(), initializeMembers(), isRunning(), readObjectMember(), setCurrentSpeed(), updateLocomotion(), and writeObjectMembers().
byte server::zone::objects::creature::CreatureObjectImplementation::currentWeather protected
Definition at line 1551 of file CreatureObject.h.
Referenced by getCurrentWeather(), initializeTransientMembers(), and setCurrentWeather().
byte server::zone::objects::creature::CreatureObjectImplementation::currentWind protected
Definition at line 1553 of file CreatureObject.h.
Referenced by getCurrentWind(), initializeTransientMembers(), and setCurrentWind().
DamageOverTimeList server::zone::objects::creature::CreatureObjectImplementation::damageOverTimeList protected
Definition at line 1537 of file CreatureObject.h.
Referenced by activateStateRecovery(), addDotState(), clearDots(), server::zone::objects::creature::AiAgentImplementation::doRecovery(), getDamageOverTimeList(), healDot(), readObjectMember(), and writeObjectMembers().
unsigned const long long server::zone::objects::creature::CreatureObjectImplementation::DEAD_TOO_LONG = 1800000 static
Definition at line 1586 of file CreatureObject.h.
Referenced by isResuscitable().
float CreatureObjectImplementation::DEFAULTRUNSPEED = 5.376 static
Definition at line 1584 of file CreatureObject.h.
DeltaVector<int> server::zone::objects::creature::CreatureObjectImplementation::encumbrances protected
Definition at line 1451 of file CreatureObject.h.
Referenced by addEncumbrance(), getEncumbrance(), getEncumbrances(), loadTemplateData(), readObjectMember(), setEncumbrance(), and writeObjectMembers().
byte server::zone::objects::creature::CreatureObjectImplementation::factionRank protected
Definition at line 1437 of file CreatureObject.h.
Referenced by getFactionRank(), initializeMembers(), readObjectMember(), setFactionRank(), and writeObjectMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::FEMALE = 1 static
Definition at line 1582 of file CreatureObject.h.
byte server::zone::objects::creature::CreatureObjectImplementation::frozen protected
Definition at line 1517 of file CreatureObject.h.
Referenced by getFrozen(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::creature::CreatureObjectImplementation::gender protected
Definition at line 1427 of file CreatureObject.h.
Referenced by getGender(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
ManagedReference<GroupObject* > server::zone::objects::creature::CreatureObjectImplementation::group protected
Definition at line 1497 of file CreatureObject.h.
Referenced by getGroup(), getGroupID(), initializeMembers(), isGrouped(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), readObjectMember(), sendToOwner(), updateGroup(), and writeObjectMembers().
unsigned long long server::zone::objects::creature::CreatureObjectImplementation::groupInviteCounter protected
Definition at line 1501 of file CreatureObject.h.
Referenced by getGroupInviteCounter(), initializeMembers(), initializeTransientMembers(), readObjectMember(), updateGroupInviterID(), and writeObjectMembers().
unsigned long long server::zone::objects::creature::CreatureObjectImplementation::groupInviterID protected
Definition at line 1499 of file CreatureObject.h.
Referenced by getGroupInviterID(), initializeMembers(), initializeTransientMembers(), readObjectMember(), updateGroupInviterID(), and writeObjectMembers().
ManagedReference<GuildObject* > server::zone::objects::creature::CreatureObjectImplementation::guild protected
Definition at line 1503 of file CreatureObject.h.
Referenced by getGuildID(), getGuildObject(), initializeMembers(), isAggressiveTo(), isAttackableBy(), isInGuild(), readObjectMember(), setGuildObject(), and writeObjectMembers().
DeltaVector<int> server::zone::objects::creature::CreatureObjectImplementation::hamList protected
Definition at line 1513 of file CreatureObject.h.
Referenced by getHAM(), hasDamage(), healDamage(), inflictDamage(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), loadTemplateData(), readObjectMember(), setHAM(), setMaxHAM(), and writeObjectMembers().
byte server::zone::objects::creature::CreatureObjectImplementation::healthWoundHeal protected
Definition at line 1545 of file CreatureObject.h.
Referenced by activatePassiveWoundRegeneration(), and initializeMembers().
float server::zone::objects::creature::CreatureObjectImplementation::height protected
Definition at line 1479 of file CreatureObject.h.
Referenced by getHeight(), initializeMembers(), loadTemplateData(), readObjectMember(), setHeight(), and writeObjectMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::HUMAN = 0 static
Definition at line 1560 of file CreatureObject.h.
Reference<CommandQueueActionVector* > server::zone::objects::creature::CreatureObjectImplementation::immediateQueue protected
Definition at line 1529 of file CreatureObject.h.
Referenced by activateImmediateAction(), enqueueCommand(), and initializeMembers().
int server::zone::objects::creature::CreatureObjectImplementation::instrumentID protected
Definition at line 1511 of file CreatureObject.h.
Referenced by getInstrumentID(), initializeMembers(), readObjectMember(), setInstrumentID(), and writeObjectMembers().
bool server::zone::objects::creature::CreatureObjectImplementation::invisible protected
Definition at line 1439 of file CreatureObject.h.
Referenced by initializeMembers(), isInvisible(), readObjectMember(), setInvisible(), and writeObjectMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::ITHORIAN = 0x21 static
Definition at line 1576 of file CreatureObject.h.
Time server::zone::objects::creature::CreatureObjectImplementation::lastCombatActionTime protected
Definition at line 1555 of file CreatureObject.h.
Referenced by calculateSpeed().
Vector3 server::zone::objects::creature::CreatureObjectImplementation::lastCombatPosition protected
Definition at line 1557 of file CreatureObject.h.
Referenced by calculateSpeed().
Time server::zone::objects::creature::CreatureObjectImplementation::lastSuccessfulCombatAction protected
Definition at line 1539 of file CreatureObject.h.
Referenced by readObjectMember(), setCombatState(), updateLastSuccessfulCombatAction(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::objects::creature::CreatureObjectImplementation::linkedCreature protected
Definition at line 1441 of file CreatureObject.h.
Referenced by server::zone::objects::creature::VehicleObjectImplementation::fillAttributeList(), server::zone::objects::creature::VehicleObjectImplementation::fillObjectMenuResponse(), getCreatureLinkID(), getLinkedCreature(), server::zone::objects::creature::VehicleObjectImplementation::handleObjectMenuSelect(), initializeMembers(), server::zone::objects::creature::VehicleObjectImplementation::isAttackableBy(), server::zone::objects::creature::VehicleObjectImplementation::notifyInsertToZone(), server::zone::objects::creature::VehicleObjectImplementation::notifyObjectDestructionObservers(), readObjectMember(), server::zone::objects::creature::VehicleObjectImplementation::sendMessage(), setCreatureLink(), and writeObjectMembers().
unsigned long long server::zone::objects::creature::CreatureObjectImplementation::listenToID protected
Definition at line 1487 of file CreatureObject.h.
Referenced by getListenID(), initializeMembers(), isListening(), notifyLoadFromDatabase(), readObjectMember(), setListenToID(), and writeObjectMembers().
byte server::zone::objects::creature::CreatureObjectImplementation::locomotion protected
Definition at line 1435 of file CreatureObject.h.
Referenced by getLocomotion(), readObjectMember(), updateLocomotion(), and writeObjectMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::MALE = 0 static
Definition at line 1580 of file CreatureObject.h.
DeltaVector<int> server::zone::objects::creature::CreatureObjectImplementation::maxHamList protected
Definition at line 1515 of file CreatureObject.h.
Referenced by addMaxHAM(), getMaxHAM(), hasDamage(), healDamage(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), loadTemplateData(), readObjectMember(), setMaxHAM(), setWounds(), and writeObjectMembers().
byte server::zone::objects::creature::CreatureObjectImplementation::mindWoundHeal protected
Definition at line 1549 of file CreatureObject.h.
Referenced by activatePassiveWoundRegeneration(), and initializeMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::MONCAL = 3 static
Definition at line 1566 of file CreatureObject.h.
byte server::zone::objects::creature::CreatureObjectImplementation::moodID protected
Definition at line 1507 of file CreatureObject.h.
Referenced by getMoodID(), initializeMembers(), initializeTransientMembers(), readObjectMember(), setMood(), and writeObjectMembers().
String server::zone::objects::creature::CreatureObjectImplementation::moodString protected
Definition at line 1493 of file CreatureObject.h.
Referenced by getMoodString(), initializeMembers(), readObjectMember(), setMood(), setMoodString(), and writeObjectMembers().
Time server::zone::objects::creature::CreatureObjectImplementation::nextAction protected
Definition at line 1531 of file CreatureObject.h.
Referenced by activateQueueAction(), enqueueCommand(), isNextActionPast(), readObjectMember(), and writeObjectMembers().
ManagedReference<ZoneClientSession* > server::zone::objects::creature::CreatureObjectImplementation::owner protected
Definition at line 1421 of file CreatureObject.h.
Referenced by getClient(), sendMessage(), sendToOwner(), and setClient().
String server::zone::objects::creature::CreatureObjectImplementation::performanceAnimation protected
Definition at line 1491 of file CreatureObject.h.
Referenced by getPerformanceAnimation(), readObjectMember(), setPerformanceAnimation(), and writeObjectMembers().
int server::zone::objects::creature::CreatureObjectImplementation::performanceCounter protected
Definition at line 1509 of file CreatureObject.h.
Referenced by getPerformanceCounter(), initializeMembers(), readObjectMember(), setPerformanceCounter(), and writeObjectMembers().
byte server::zone::objects::creature::CreatureObjectImplementation::posture protected
Definition at line 1433 of file CreatureObject.h.
Referenced by getPosture(), initializeMembers(), isDead(), isIncapacitated(), isKneeling(), isKnockedDown(), isProne(), isSitting(), isSkillAnimating(), isStanding(), readObjectMember(), setCombatState(), setPosture(), setSpeedMultiplierMod(), updateLocomotion(), updateSpeedAndAccelerationMods(), and writeObjectMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::RODIAN = 1 static
Definition at line 1562 of file CreatureObject.h.
float server::zone::objects::creature::CreatureObjectImplementation::runAcceleration protected
Definition at line 1475 of file CreatureObject.h.
Referenced by getRunAcceleration(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
float server::zone::objects::creature::CreatureObjectImplementation::runSpeed protected
Definition at line 1467 of file CreatureObject.h.
Referenced by server::zone::objects::creature::AiAgentImplementation::findNextPosition(), getRunSpeed(), isRunning(), loadTemplateData(), readObjectMember(), setRunSpeed(), and writeObjectMembers().
VectorMap<String, unsigned long long> server::zone::objects::creature::CreatureObjectImplementation::screenPlayStates protected
Definition at line 1543 of file CreatureObject.h.
Referenced by getScreenPlayState(), readObjectMember(), setScreenPlayState(), and writeObjectMembers().
float server::zone::objects::creature::CreatureObjectImplementation::shockWounds protected
Definition at line 1445 of file CreatureObject.h.
Referenced by addShockWounds(), calculateBFRatio(), getShockWounds(), initializeMembers(), server::zone::objects::creature::AiAgentImplementation::notifyDespawn(), readObjectMember(), setShockWounds(), and writeObjectMembers().
SkillList server::zone::objects::creature::CreatureObjectImplementation::skillList protected
Definition at line 1521 of file CreatureObject.h.
Referenced by addSkill(), getSkillList(), hasSkill(), readObjectMember(), removeSkill(), and writeObjectMembers().
SkillModList server::zone::objects::creature::CreatureObjectImplementation::skillModList protected
Definition at line 1523 of file CreatureObject.h.
Referenced by addSkillMod(), getSkillMod(), getSkillModList(), readObjectMember(), removeAllSkillModsOfType(), and writeObjectMembers().
Mutex server::zone::objects::creature::CreatureObjectImplementation::skillModMutex protected
Definition at line 1525 of file CreatureObject.h.
Referenced by addSkillMod(), getSkillMod(), and getSkillModMutex().
float server::zone::objects::creature::CreatureObjectImplementation::slopeModAngle protected
Definition at line 1485 of file CreatureObject.h.
Referenced by loadTemplateData(), readObjectMember(), and writeObjectMembers().
float server::zone::objects::creature::CreatureObjectImplementation::slopeModPercent protected
Definition at line 1483 of file CreatureObject.h.
Referenced by getSlopeModPercent(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::creature::CreatureObjectImplementation::species protected
Definition at line 1429 of file CreatureObject.h.
Referenced by getSpecies(), getSpeciesName(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
float server::zone::objects::creature::CreatureObjectImplementation::speedMultiplierBase protected
Definition at line 1459 of file CreatureObject.h.
Referenced by getSpeedMultiplierBase(), initializeMembers(), readObjectMember(), setSpeedMultiplierBase(), and writeObjectMembers().
float server::zone::objects::creature::CreatureObjectImplementation::speedMultiplierMod protected
Definition at line 1463 of file CreatureObject.h.
Referenced by getSpeedMultiplierMod(), initializeMembers(), readObjectMember(), setSpeedMultiplierMod(), and writeObjectMembers().
SpeedMultiplierModChanges server::zone::objects::creature::CreatureObjectImplementation::speedMultiplierModChanges protected
Definition at line 1461 of file CreatureObject.h.
Referenced by getSpeedMultiplierModChanges(), readObjectMember(), setSpeedMultiplierMod(), and writeObjectMembers().
unsigned long long server::zone::objects::creature::CreatureObjectImplementation::stateBitmask protected
Definition at line 1449 of file CreatureObject.h.
Referenced by clearCombatState(), clearState(), getStateBitmask(), hasState(), hasStates(), initializeMembers(), isAiming(), isBerserked(), isBleeding(), isBlinded(), isDiseased(), isDizzied(), isFrozen(), isImmobilized(), isInCombat(), isInCover(), isIntimidated(), isMeditating(), isMounted(), isOnFire(), isPeaced(), isPoisoned(), isRallied(), isRidingCreature(), isRidingMount(), isRooted(), isSnared(), isStunned(), isSwimming(), server::zone::objects::creature::AiAgentImplementation::notifyDespawn(), readObjectMember(), setCombatState(), setState(), and writeObjectMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::SULLUSTAN = 0x31 static
Definition at line 1578 of file CreatureObject.h.
float server::zone::objects::creature::CreatureObjectImplementation::swimHeight protected
Definition at line 1481 of file CreatureObject.h.
Referenced by getSwimHeight(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
unsigned long long server::zone::objects::creature::CreatureObjectImplementation::targetID protected
Definition at line 1505 of file CreatureObject.h.
Referenced by enqueueCommand(), getTargetID(), initializeMembers(), readObjectMember(), setTargetID(), and writeObjectMembers().
String server::zone::objects::creature::CreatureObjectImplementation::templateString protected
Definition at line 1519 of file CreatureObject.h.
Referenced by readObjectMember(), and writeObjectMembers().
float server::zone::objects::creature::CreatureObjectImplementation::terrainNegotiation protected
Definition at line 1473 of file CreatureObject.h.
Referenced by getTerrainNegotiation(), initializeMembers(), readObjectMember(), setTerrainNegotiation(), and writeObjectMembers().
Time server::zone::objects::creature::CreatureObjectImplementation::timeOfDeath protected
Definition at line 1541 of file CreatureObject.h.
Referenced by isResuscitable(), readObjectMember(), updateTimeOfDeath(), and writeObjectMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::TRANDOSHAN = 2 static
Definition at line 1564 of file CreatureObject.h.
float server::zone::objects::creature::CreatureObjectImplementation::turnScale protected
Definition at line 1465 of file CreatureObject.h.
Referenced by getTurnScale(), initializeMembers(), readObjectMember(), setTurnScale(), and writeObjectMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::TWILEK = 6 static
Definition at line 1572 of file CreatureObject.h.
float server::zone::objects::creature::CreatureObjectImplementation::walkAcceleration protected
Definition at line 1477 of file CreatureObject.h.
Referenced by getWalkAcceleration(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
float server::zone::objects::creature::CreatureObjectImplementation::walkSpeed protected
Definition at line 1469 of file CreatureObject.h.
Referenced by getWalkSpeed(), loadTemplateData(), readObjectMember(), updateLocomotion(), and writeObjectMembers().
unsigned long long server::zone::objects::creature::CreatureObjectImplementation::watchToID protected
Definition at line 1489 of file CreatureObject.h.
Referenced by getWatchToID(), initializeMembers(), isWatching(), notifyLoadFromDatabase(), readObjectMember(), setWatchToID(), and writeObjectMembers().
ManagedReference<WeaponObject* > server::zone::objects::creature::CreatureObjectImplementation::weapon protected
Definition at line 1495 of file CreatureObject.h.
Referenced by getWeapon(), getWeaponID(), initializeMembers(), readObjectMember(), setAimingState(), setWeapon(), and writeObjectMembers().
WearablesDeltaVector server::zone::objects::creature::CreatureObjectImplementation::wearablesVector protected
Definition at line 1453 of file CreatureObject.h.
Referenced by addWearableObject(), getWearablesDeltaVector(), readObjectMember(), removeWearableObject(), and writeObjectMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::WOOKIE = 4 static
Definition at line 1568 of file CreatureObject.h.
DeltaVector<int> server::zone::objects::creature::CreatureObjectImplementation::wounds protected
Definition at line 1447 of file CreatureObject.h.
Referenced by addWounds(), getWounds(), hasDamage(), healDamage(), healWound(), loadTemplateData(), readObjectMember(), setMaxHAM(), setWounds(), and writeObjectMembers().
const int server::zone::objects::creature::CreatureObjectImplementation::ZABRAK = 7 static
Definition at line 1574 of file CreatureObject.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/CreatureObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/CreatureObject.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/CreatureObjectImplementation.cpp