Core3: server::zone::objects::player::sui::messagebox::SuiTransferBox Class Reference
server::zone::objects::player::sui::messagebox::SuiTransferBox Class Reference
#include <SuiTransferBox.h>
Public Member Functions
SuiTransferBox (CreatureObject *player, unsigned int windowType)
BaseMessage * generateMessage ()
void addFrom (const String &from, const String &startingFrom, const String &inputFrom, const String &rFrom)
void addTo (const String &to, const String &startingTo, const String &inputTo, const String &rTo)
bool isTransferBox ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::player::sui::SuiBox
SuiBox (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
void initialize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateMessage ()
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
bool isInputBox ()
bool isListBox ()
bool isMessageBox ()
bool isTransferBox ()
bool isBankTransferBox ()
bool isSlicingBox ()
bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
SuiTransferBox (DummyConstructorParameter *param)
virtual ~SuiTransferBox ()
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBox
SuiBox (DummyConstructorParameter *param)
virtual ~SuiBox ()
Friends
class SuiTransferBoxHelper
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::player::sui::SuiBox
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Detailed Description
Definition at line 71 of file SuiTransferBox.h.
Constructor & Destructor Documentation
SuiTransferBox::SuiTransferBox (CreatureObject * player, unsigned int windowType)
Definition at line 19 of file SuiTransferBox.cpp.
References server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::_setStub().
SuiTransferBox::SuiTransferBox (DummyConstructorParameter * param) protected
Definition at line 26 of file SuiTransferBox.cpp.
SuiTransferBox::~SuiTransferBox () protected virtual
Definition at line 30 of file SuiTransferBox.cpp.
Member Function Documentation
DistributedObjectServant * SuiTransferBox::_getImplementation ()
Definition at line 95 of file SuiTransferBox.cpp.
Referenced by addFrom(), addTo(), generateMessage(), and isTransferBox().
DistributedObjectServant * SuiTransferBox::_getImplementationForRead ()
Definition at line 101 of file SuiTransferBox.cpp.
void SuiTransferBox::_setImplementation (DistributedObjectServant * servant)
Definition at line 105 of file SuiTransferBox.cpp.
void SuiTransferBox::addFrom (const String & from, const String & startingFrom, const String & inputFrom, const String & rFrom)
Definition at line 48 of file SuiTransferBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::addFrom(), and RPC_ADDFROM__STRING_STRING_STRING_STRING_.
void SuiTransferBox::addTo (const String & to, const String & startingTo, const String & inputTo, const String & rTo)
Definition at line 65 of file SuiTransferBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::addTo(), and RPC_ADDTO__STRING_STRING_STRING_STRING_.
BaseMessage * SuiTransferBox::generateMessage ()
Definition at line 35 of file SuiTransferBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::generateMessage(), and RPC_GENERATEMESSAGE__.
bool SuiTransferBox::isTransferBox ()
Definition at line 82 of file SuiTransferBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::isTransferBox(), and RPC_ISTRANSFERBOX__.
Friends And Related Function Documentation
friend class SuiTransferBoxHelper friend
Definition at line 93 of file SuiTransferBox.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/transferbox/SuiTransferBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/transferbox/SuiTransferBox.cpp