Core3: server::zone::objects::tangible::threat::ThreatMapObserver Class Reference
server::zone::objects::tangible::threat::ThreatMapObserver Class Reference
#include <ThreatMapObserver.h>
Public Member Functions
ThreatMapObserver (TangibleObject *me)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ThreatMapObserver (DummyConstructorParameter *param)
virtual ~ThreatMapObserver ()
Friends
class ThreatMapObserverHelper
Detailed Description
Definition at line 50 of file ThreatMapObserver.h.
Constructor & Destructor Documentation
ThreatMapObserver::ThreatMapObserver (TangibleObject * me)
Definition at line 15 of file ThreatMapObserver.cpp.
References server::zone::objects::tangible::threat::ThreatMapObserverImplementation::_setStub().
ThreatMapObserver::ThreatMapObserver (DummyConstructorParameter * param) protected
Definition at line 22 of file ThreatMapObserver.cpp.
ThreatMapObserver::~ThreatMapObserver () protected virtual
Definition at line 26 of file ThreatMapObserver.cpp.
Member Function Documentation
DistributedObjectServant * ThreatMapObserver::_getImplementation ()
Definition at line 48 of file ThreatMapObserver.cpp.
Referenced by notifyObserverEvent().
DistributedObjectServant * ThreatMapObserver::_getImplementationForRead ()
Definition at line 54 of file ThreatMapObserver.cpp.
void ThreatMapObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 58 of file ThreatMapObserver.cpp.
int ThreatMapObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 31 of file ThreatMapObserver.cpp.
References _getImplementation(), server::zone::objects::tangible::threat::ThreatMapObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class ThreatMapObserverHelper friend
Definition at line 66 of file ThreatMapObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/threat/ThreatMapObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/threat/ThreatMapObserver.cpp