Core3: Vert Class Reference
Vert Class Reference
#include <FloorMesh.h>
Public Member Functions
Vert ()
Vert (const Vert &v)
Vert (float px, float py, float pz)
void readObject (IffStream *iffStream)
float getX ()
float getY ()
float getZ ()
Private Attributes
float x
float z
float y
Detailed Description
Definition at line 18 of file FloorMesh.h.
Constructor & Destructor Documentation
Vert::Vert () inline
Definition at line 22 of file FloorMesh.h.
References x, y, and z.
Vert::Vert (const Vert & v) inline
Definition at line 26 of file FloorMesh.h.
References x, y, and z.
Vert::Vert (float px, float py, float pz) inline
Definition at line 32 of file FloorMesh.h.
References x, y, and z.
Member Function Documentation
float Vert::getX () inline
Definition at line 44 of file FloorMesh.h.
References x.
Referenced by FloorMeshTriangleNode::readObject().
float Vert::getY () inline
Definition at line 48 of file FloorMesh.h.
References y.
Referenced by FloorMeshTriangleNode::readObject().
float Vert::getZ () inline
Definition at line 52 of file FloorMesh.h.
References z.
Referenced by FloorMeshTriangleNode::readObject().
void Vert::readObject (IffStream * iffStream) inline
Definition at line 38 of file FloorMesh.h.
References x, y, and z.
Referenced by FloorMesh::parseVersion0005(), and FloorMesh::parseVersion0006().
Member Data Documentation
float Vert::x private
Definition at line 19 of file FloorMesh.h.
Referenced by getX(), readObject(), and Vert().
float Vert::y private
Definition at line 19 of file FloorMesh.h.
Referenced by getY(), readObject(), and Vert().
float Vert::z private
Definition at line 19 of file FloorMesh.h.
Referenced by getZ(), readObject(), and Vert().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/FloorMesh.h