Core3: server::zone::objects::mission::SurveyMissionObjectiveAdapter Class Reference
server::zone::objects::mission::SurveyMissionObjectiveAdapter Class Reference
#include <SurveyMissionObjective.h>
Public Member Functions
SurveyMissionObjectiveAdapter (SurveyMissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void setSpawnFamily (String &spf)
void setEfficiency (unsigned int eff)
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveAdapter
MissionObjectiveAdapter (MissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Detailed Description
Definition at line 194 of file SurveyMissionObjective.h.
Constructor & Destructor Documentation
SurveyMissionObjectiveAdapter::SurveyMissionObjectiveAdapter (SurveyMissionObjective * impl)
Definition at line 341 of file SurveyMissionObjective.cpp.
Member Function Documentation
void SurveyMissionObjectiveAdapter::abort ()
Definition at line 406 of file SurveyMissionObjective.cpp.
Referenced by invokeMethod().
void SurveyMissionObjectiveAdapter::activate ()
Definition at line 402 of file SurveyMissionObjective.cpp.
Referenced by invokeMethod().
void SurveyMissionObjectiveAdapter::complete ()
Definition at line 410 of file SurveyMissionObjective.cpp.
Referenced by invokeMethod().
void SurveyMissionObjectiveAdapter::finalize ()
Definition at line 394 of file SurveyMissionObjective.cpp.
Referenced by invokeMethod().
void SurveyMissionObjectiveAdapter::initializeTransientMembers ()
Definition at line 398 of file SurveyMissionObjective.cpp.
Referenced by invokeMethod().
void SurveyMissionObjectiveAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 344 of file SurveyMissionObjective.cpp.
References abort(), activate(), complete(), finalize(), initializeTransientMembers(), notifyObserverEvent(), RPC_ABORT__, RPC_ACTIVATE__, RPC_COMPLETE__, RPC_FINALIZE__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_, RPC_SETEFFICIENCY__INT_, RPC_SETSPAWNFAMILY__STRING_, setEfficiency(), and setSpawnFamily().
int SurveyMissionObjectiveAdapter::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 414 of file SurveyMissionObjective.cpp.
Referenced by invokeMethod().
void SurveyMissionObjectiveAdapter::setEfficiency (unsigned int eff)
Definition at line 422 of file SurveyMissionObjective.cpp.
Referenced by invokeMethod().
void SurveyMissionObjectiveAdapter::setSpawnFamily (String & spf)
Definition at line 418 of file SurveyMissionObjective.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/SurveyMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/SurveyMissionObjective.cpp