Core3: server::zone::managers::director::ScreenPlayObserverImplementation Class Reference
server::zone::managers::director::ScreenPlayObserverImplementation Class Reference
#include <ScreenPlayObserver.h>
Public Member Functions
ScreenPlayObserverImplementation ()
ScreenPlayObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void setScreenPlay (const String &screen)
void setScreenKey (const String &screenKey)
String getScreenPlay ()
String getScreenKey ()
operator const ScreenPlayObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< ScreenPlayObserver * > _this
Protected Member Functions
virtual ~ScreenPlayObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
String play
String key
Friends
class ScreenPlayObserver
Detailed Description
Definition at line 64 of file ScreenPlayObserver.h.
Constructor & Destructor Documentation
ScreenPlayObserverImplementation::ScreenPlayObserverImplementation ()
Definition at line 260 of file ScreenPlayObserver.cpp.
References _initializeImplementation(), and play.
ScreenPlayObserverImplementation::ScreenPlayObserverImplementation (DummyConstructorParameter * param)
Definition at line 122 of file ScreenPlayObserver.cpp.
References _initializeImplementation().
ScreenPlayObserverImplementation::~ScreenPlayObserverImplementation () protected virtual
Definition at line 127 of file ScreenPlayObserver.cpp.
Member Function Documentation
DistributedObjectStub * ScreenPlayObserverImplementation::_getStub ()
Definition at line 147 of file ScreenPlayObserver.cpp.
References _this.
void ScreenPlayObserverImplementation::_initializeImplementation () protected
Definition at line 134 of file ScreenPlayObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ScreenPlayObserverImplementation().
void ScreenPlayObserverImplementation::_serializationHelperMethod () protected
Definition at line 183 of file ScreenPlayObserver.cpp.
Referenced by _initializeImplementation().
void ScreenPlayObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 142 of file ScreenPlayObserver.cpp.
References _this.
Referenced by server::zone::managers::director::ScreenPlayObserver::ScreenPlayObserver().
void ScreenPlayObserverImplementation::finalize () protected
Definition at line 131 of file ScreenPlayObserver.cpp.
String ScreenPlayObserverImplementation::getScreenKey ()
Definition at line 281 of file ScreenPlayObserver.cpp.
References key.
Referenced by server::zone::managers::director::ScreenPlayObserver::getScreenKey().
String ScreenPlayObserverImplementation::getScreenPlay ()
Definition at line 276 of file ScreenPlayObserver.cpp.
References play.
Referenced by server::zone::managers::director::ScreenPlayObserver::getScreenPlay().
void ScreenPlayObserverImplementation::lock (bool doLock = true) protected
Definition at line 155 of file ScreenPlayObserver.cpp.
References _this.
void ScreenPlayObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 159 of file ScreenPlayObserver.cpp.
References _this.
int ScreenPlayObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 47 of file ScreenPlayObserverImplementation.cpp.
References key, and play.
Referenced by server::zone::managers::director::ScreenPlayObserver::notifyObserverEvent().
ScreenPlayObserverImplementation::operator const ScreenPlayObserver * ()
Definition at line 151 of file ScreenPlayObserver.cpp.
void ScreenPlayObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 190 of file ScreenPlayObserver.cpp.
References readObjectMember().
bool ScreenPlayObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 209 of file ScreenPlayObserver.cpp.
References key, and play.
Referenced by readObject().
void ScreenPlayObserverImplementation::rlock (bool doLock = true) protected
Definition at line 163 of file ScreenPlayObserver.cpp.
References _this.
void ScreenPlayObserverImplementation::runlock (bool doLock = true) protected
Definition at line 179 of file ScreenPlayObserver.cpp.
References _this.
void ScreenPlayObserverImplementation::setScreenKey (const String & screenKey)
Definition at line 271 of file ScreenPlayObserver.cpp.
References key.
Referenced by server::zone::managers::director::ScreenPlayObserver::setScreenKey().
void ScreenPlayObserverImplementation::setScreenPlay (const String & screen)
Definition at line 266 of file ScreenPlayObserver.cpp.
References play.
Referenced by server::zone::managers::director::ScreenPlayObserver::setScreenPlay().
void ScreenPlayObserverImplementation::unlock (bool doLock = true) protected
Definition at line 175 of file ScreenPlayObserver.cpp.
References _this.
void ScreenPlayObserverImplementation::wlock (bool doLock = true) protected
Definition at line 167 of file ScreenPlayObserver.cpp.
References _this.
void ScreenPlayObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 171 of file ScreenPlayObserver.cpp.
References _this.
void ScreenPlayObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 227 of file ScreenPlayObserver.cpp.
References writeObjectMembers().
int ScreenPlayObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 234 of file ScreenPlayObserver.cpp.
References key, and play.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ScreenPlayObserver friend
Definition at line 119 of file ScreenPlayObserver.h.
Member Data Documentation
WeakReference<ScreenPlayObserver*> server::zone::managers::director::ScreenPlayObserverImplementation::_this
Definition at line 85 of file ScreenPlayObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
String server::zone::managers::director::ScreenPlayObserverImplementation::key protected
Definition at line 68 of file ScreenPlayObserver.h.
Referenced by getScreenKey(), notifyObserverEvent(), readObjectMember(), setScreenKey(), and writeObjectMembers().
String server::zone::managers::director::ScreenPlayObserverImplementation::play protected
Definition at line 66 of file ScreenPlayObserver.h.
Referenced by getScreenPlay(), notifyObserverEvent(), readObjectMember(), ScreenPlayObserverImplementation(), setScreenPlay(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/ScreenPlayObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/ScreenPlayObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/ScreenPlayObserverImplementation.cpp