Core3: server::zone::objects::creature::ai::AiActorImplementation Class Reference
server::zone::objects::creature::ai::AiActorImplementation Class Reference
#include <AiActor.h>
Public Member Functions
AiActorImplementation ()
AiActorImplementation (DummyConstructorParameter *param)
void setHost (CreatureObject *creo)
CreatureObject * getHost ()
void initializeTransientMembers ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void notifyPositionUpdate (QuadTreeEntry *entry)
void setCurrentMessage (unsigned short msg)
void next (unsigned short msg)
void next ()
void destroyActor ()
void doAwarenessCheck (Coordinate &start, unsigned long long time, CreatureObject *target)
void addTransition (const String &stateName, unsigned short msg, const String &resultState)
void loadTemplateData (CreatureTemplate *templateData)
CreatureTemplateReference * getNpcTemplate ()
void setLevel (int lvl)
int calculateAttackMinDamage (int level)
int calculateAttackMaxDamage (int level)
float calculateAttackSpeed (int level)
bool isCamouflaged (CreatureObject *target)
bool isScentMasked (CreatureObject *target)
bool isConcealed (CreatureObject *target)
virtual void activateRecovery ()
virtual void activateMovementEvent ()
void activateAwarenessEvent (CreatureObject *target)
void activatePostureRecovery ()
void queueDizzyFallEvent ()
void setNextPosition (PatrolPoint &point)
void setNextStepPosition (float x, float z, float y, SceneObject *cell=NULL)
PatrolPoint * getNextStepPosition ()
void setShowNextPosition (bool val)
bool isShowNextPosition ()
Vector< ManagedReference
< SceneObject * > > * getMovementMarkers ()
int getMovementMarkersSize ()
SceneObject * getMovementMarker (int i)
void dropMovementMarker (SceneObject *marker)
void dropAllMovemementMarkers ()
void addMovementMarker (SceneObject *marker)
void clearPatrolPoints ()
PatrolPointsVector * getPatrolPoints ()
void addPatrolPoint (PatrolPoint &point)
void setHomeLocation (float x, float z, float y, SceneObject *cell=NULL)
PatrolPoint * getHomeLocation ()
void setDespawnOnNoPlayerInRange (bool val)
void notifyDespawn (Zone *zone)
void scheduleDespawn (int timeToDespawn)
void respawn (Zone *zone, int level)
void scheduleDespawn ()
void clearDespawnEvent ()
void setRespawnTimer (float resp)
float getRespawnTimer ()
bool getDespawnOnNoPlayerInRange ()
int getNumberOfPlayersInRange ()
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
int notifyConverseObservers (CreatureObject *converser)
SceneObject * getFollowObject ()
void setFollowObject (SceneObject *targ)
void setTargetObject (SceneObject *obj)
void setOblivious ()
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
void updateLastDamageReceived ()
void sendConversationStartTo (SceneObject *player)
float getKinetic ()
float getEnergy ()
float getElectricity ()
float getStun ()
float getBlast ()
float getHeat ()
float getCold ()
float getAcid ()
float getLightSaber ()
bool isStalker ()
bool isKiller ()
unsigned int getFerocity ()
unsigned int getArmor ()
String getFactionString ()
String getSocialGroup ()
float getChanceHit ()
int getDamageMin ()
int getDamageMax ()
int getBaseXp ()
unsigned int getDiet ()
CreatureAttackMap * getAttackMap ()
LootGroupCollection * getLootGroups ()
CreatureTemplate * getCreatureTemplate ()
Vector< ManagedReference
< WeaponObject * > > getWeapons ()
Time getLastDamageReceived ()
bool isActorObject ()
int getBehaviorStatus (Behavior *b)
void setBehaviorStatus (Behavior *b, int status)
void addBehaviorToTree (BehaviorTree *tree, Behavior *b)
Behavior * getNextBehaviorFromTree (BehaviorTree *tree)
void resetBehaviorList (BehaviorTree *tree)
operator const AiActor * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void loadTemplateData (SharedObjectTemplate *templateData)
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendTo (SceneObject *player, bool doClose)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendBaselinesTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
virtual void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
virtual int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isTangibleObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
virtual void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< AiActor * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Static Public Attributes
static unsigned const short FINISHED = 0
static unsigned const short UNFINISHED = 1
static unsigned const short ATTACKED = 2
static unsigned const short INTERESTED = 3
static unsigned const short DEAD = 4
static unsigned const short ALMOSTDEAD = 5
static unsigned const short SCARED = 6
static unsigned const short FORGOT = 7
static unsigned const short NONE = 0xFFFF
static const int UPDATEMOVEMENTINTERVAL = 500
Protected Member Functions
virtual ~AiActorImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
VectorMap< String, String > transitions
HashTable< Behavior *, int > statuses
HashTable< BehaviorTree
*, BehaviorTreeList * > trees
Reference< AiStateComponent * > currentState
String currentStateName
String defaultStateName
Reference< AiTemplate * > aiTemplate
CreatureTemplateReference npcTemplate
Vector< ManagedReference
< WeaponObject * > > weapons
Vector< ManagedReference
< SceneObject * > > camouflagedObjects
bool loadedOutfit
unsigned short currentMessage
ManagedReference
< CreatureObject * > host
float respawnTimer
bool despawnOnNoPlayerInRange
int numberOfPlayersInRange
Reference< AiThinkEvent * > thinkEvent
Reference< AiMoveEvent * > moveEvent
Reference< AiAwarenessEvent * > awarenessEvent
Reference
< DespawnCreatureOnPlayerDissappear * > despawnEvent
Reference< Vector< String > * > skillCommands
PatrolPointsVector patrolPoints
PatrolPoint homeLocation
PatrolPoint nextStepPosition
bool baby
ManagedReference< SceneObject * > followObject
Mutex targetMutex
Time lastDamageReceived
bool showNextMovementPosition
Reference< Vector
< ManagedReference
< SceneObject * > > * > movementMarkers
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Friends
class AiActor
Detailed Description
Definition at line 506 of file AiActor.h.
Constructor & Destructor Documentation
AiActorImplementation::AiActorImplementation ()
Definition at line 1635 of file AiActor.cpp.
References _initializeImplementation(), aiTemplate, despawnOnNoPlayerInRange, host, loadedOutfit, numberOfPlayersInRange, respawnTimer, and showNextMovementPosition.
AiActorImplementation::AiActorImplementation (DummyConstructorParameter * param)
Definition at line 1293 of file AiActor.cpp.
References _initializeImplementation().
AiActorImplementation::~AiActorImplementation () protected virtual
Definition at line 1298 of file AiActor.cpp.
Member Function Documentation
DistributedObjectStub * AiActorImplementation::_getStub ()
Definition at line 1318 of file AiActor.cpp.
References _this.
void AiActorImplementation::_initializeImplementation () protected
Definition at line 1305 of file AiActor.cpp.
References _serializationHelperMethod(), and _this.
Referenced by AiActorImplementation().
void AiActorImplementation::_serializationHelperMethod () protected
Definition at line 1354 of file AiActor.cpp.
Referenced by _initializeImplementation().
void AiActorImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 1313 of file AiActor.cpp.
References _this.
Referenced by server::zone::objects::creature::ai::AiActor::AiActor().
void AiActorImplementation::activateAwarenessEvent (CreatureObject * target)
Definition at line 462 of file AiActorImplementation.cpp.
Referenced by server::zone::objects::creature::ai::AiActor::activateAwarenessEvent().
void AiActorImplementation::activateMovementEvent () virtual
Definition at line 444 of file AiActorImplementation.cpp.
Referenced by server::zone::objects::creature::ai::AiActor::activateMovementEvent().
void AiActorImplementation::activatePostureRecovery ()
Definition at line 491 of file AiActorImplementation.cpp.
References host.
Referenced by server::zone::objects::creature::ai::AiActor::activatePostureRecovery().
void AiActorImplementation::activateRecovery () virtual
Definition at line 429 of file AiActorImplementation.cpp.
Referenced by server::zone::objects::creature::ai::AiActor::activateRecovery().
void AiActorImplementation::addBehaviorToTree (BehaviorTree * tree, Behavior * b)
Definition at line 793 of file AiActorImplementation.cpp.
References trees.
Referenced by server::zone::objects::creature::ai::AiActor::addBehaviorToTree().
void AiActorImplementation::addDefender (SceneObject * defender)
Definition at line 717 of file AiActorImplementation.cpp.
References server::zone::objects::creature::ai::AiActor::ATTACKED, host, and next().
Referenced by server::zone::objects::creature::ai::AiActor::addDefender().
void AiActorImplementation::addMovementMarker (SceneObject * marker)
Definition at line 1737 of file AiActor.cpp.
References movementMarkers.
Referenced by server::zone::objects::creature::ai::AiActor::addMovementMarker().
void AiActorImplementation::addPatrolPoint (PatrolPoint & point)
Definition at line 774 of file AiActorImplementation.cpp.
References patrolPoints, and targetMutex.
Referenced by server::zone::objects::creature::ai::AiActor::addPatrolPoint().
void AiActorImplementation::addTransition (const String & stateName, unsigned short msg, const String & resultState)
Definition at line 361 of file AiActorImplementation.cpp.
References transitions.
Referenced by server::zone::objects::creature::ai::AiActor::addTransition().
int AiActorImplementation::calculateAttackMaxDamage (int level)
Definition at line 223 of file AiActorImplementation.cpp.
References calculateAttackMinDamage(), and npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::calculateAttackMaxDamage(), and setLevel().
int AiActorImplementation::calculateAttackMinDamage (int level)
Definition at line 217 of file AiActorImplementation.cpp.
References npcTemplate.
Referenced by calculateAttackMaxDamage(), server::zone::objects::creature::ai::AiActor::calculateAttackMinDamage(), and setLevel().
float AiActorImplementation::calculateAttackSpeed (int level)
Definition at line 229 of file AiActorImplementation.cpp.
Referenced by server::zone::objects::creature::ai::AiActor::calculateAttackSpeed(), and setLevel().
void AiActorImplementation::clearDespawnEvent ()
Definition at line 1775 of file AiActor.cpp.
References despawnEvent.
Referenced by server::zone::objects::creature::ai::AiActor::clearDespawnEvent().
void AiActorImplementation::clearPatrolPoints ()
Definition at line 1742 of file AiActor.cpp.
References patrolPoints, and targetMutex.
Referenced by server::zone::objects::creature::ai::AiActor::clearPatrolPoints(), and setTargetObject().
void AiActorImplementation::destroyActor ()
Definition at line 274 of file AiActorImplementation.cpp.
References awarenessEvent, despawnEvent, server::zone::objects::scene::SceneObjectImplementation::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObjectImplementation::destroyObjectFromWorld(), moveEvent, and thinkEvent.
Referenced by server::zone::objects::creature::ai::AiActor::destroyActor().
void AiActorImplementation::doAwarenessCheck (Coordinate & start, unsigned long long time, CreatureObject * target)
Definition at line 357 of file AiActorImplementation.cpp.
References _this, and currentState.
Referenced by server::zone::objects::creature::ai::AiActor::doAwarenessCheck(), and notifyPositionUpdate().
void AiActorImplementation::dropAllMovemementMarkers ()
Definition at line 1732 of file AiActor.cpp.
References movementMarkers.
Referenced by server::zone::objects::creature::ai::AiActor::dropAllMovemementMarkers().
void AiActorImplementation::dropMovementMarker (SceneObject * marker)
Definition at line 1727 of file AiActor.cpp.
References movementMarkers.
Referenced by server::zone::objects::creature::ai::AiActor::dropMovementMarker().
void AiActorImplementation::fillAttributeList (AttributeListMessage * msg, CreatureObject * object) virtual
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 558 of file AiActorImplementation.cpp.
References getAcid(), getArmor(), getBlast(), getCold(), getElectricity(), getEnergy(), getHeat(), getKinetic(), getLightSaber(), getStun(), host, and server::zone::packets::scene::AttributeListMessage::insertAttribute().
Referenced by server::zone::objects::creature::ai::AiActor::fillAttributeList().
void AiActorImplementation::finalize () protected
Definition at line 1302 of file AiActor.cpp.
float AiActorImplementation::getAcid ()
Definition at line 1926 of file AiActor.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::ai::AiActor::getAcid().
unsigned int AiActorImplementation::getArmor ()
Definition at line 1966 of file AiActor.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::ai::AiActor::getArmor().
CreatureAttackMap * AiActorImplementation::getAttackMap ()
Definition at line 2024 of file AiActor.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::getAttackMap().
int AiActorImplementation::getBaseXp ()
Definition at line 2008 of file AiActor.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::getBaseXp().
int AiActorImplementation::getBehaviorStatus (Behavior * b)
Definition at line 787 of file AiActorImplementation.cpp.
References statuses.
Referenced by server::zone::objects::creature::ai::AiActor::getBehaviorStatus().
float AiActorImplementation::getBlast ()
Definition at line 1902 of file AiActor.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::ai::AiActor::getBlast().
float AiActorImplementation::getChanceHit ()
Definition at line 1990 of file AiActor.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::getChanceHit().
float AiActorImplementation::getCold ()
Definition at line 1918 of file AiActor.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::ai::AiActor::getCold().
CreatureTemplate * AiActorImplementation::getCreatureTemplate ()
Definition at line 2040 of file AiActor.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::getCreatureTemplate().
int AiActorImplementation::getDamageMax ()
Definition at line 2003 of file AiActor.cpp.
References host.
Referenced by server::zone::objects::creature::ai::AiActor::getDamageMax().
int AiActorImplementation::getDamageMin ()
Definition at line 1998 of file AiActor.cpp.
References host.
Referenced by server::zone::objects::creature::ai::AiActor::getDamageMin().
bool AiActorImplementation::getDespawnOnNoPlayerInRange ()
Definition at line 1790 of file AiActor.cpp.
References despawnOnNoPlayerInRange.
Referenced by server::zone::objects::creature::ai::AiActor::getDespawnOnNoPlayerInRange().
unsigned int AiActorImplementation::getDiet ()
Definition at line 2016 of file AiActor.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::getDiet().
float AiActorImplementation::getElectricity ()
Definition at line 1886 of file AiActor.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::ai::AiActor::getElectricity().
float AiActorImplementation::getEnergy ()
Definition at line 1878 of file AiActor.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::ai::AiActor::getEnergy().
String AiActorImplementation::getFactionString ()
Definition at line 1974 of file AiActor.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::getFactionString().
unsigned int AiActorImplementation::getFerocity ()
Definition at line 1958 of file AiActor.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::getFerocity(), and notifyPositionUpdate().
SceneObject * AiActorImplementation::getFollowObject ()
Definition at line 1800 of file AiActor.cpp.
References followObject.
Referenced by server::zone::objects::creature::ai::AiActor::getFollowObject(), and notifyPositionUpdate().
float AiActorImplementation::getHeat ()
Definition at line 1910 of file AiActor.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::ai::AiActor::getHeat().
PatrolPoint * AiActorImplementation::getHomeLocation ()
Definition at line 1765 of file AiActor.cpp.
References homeLocation.
Referenced by server::zone::objects::creature::ai::AiActor::getHomeLocation().
CreatureObject * AiActorImplementation::getHost ()
Definition at line 1666 of file AiActor.cpp.
References host.
Referenced by server::zone::objects::creature::ai::AiActor::getHost().
float AiActorImplementation::getKinetic ()
Definition at line 1870 of file AiActor.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::ai::AiActor::getKinetic().
Time AiActorImplementation::getLastDamageReceived ()
Definition at line 783 of file AiActorImplementation.cpp.
References lastDamageReceived.
Referenced by server::zone::objects::creature::ai::AiActor::getLastDamageReceived().
float AiActorImplementation::getLightSaber ()
Definition at line 1934 of file AiActor.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::ai::AiActor::getLightSaber().
LootGroupCollection * AiActorImplementation::getLootGroups ()
Definition at line 2032 of file AiActor.cpp.
References LootGroupCollection::get(), LootGroupCollectionEntry::getLootGroups(), and npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::getLootGroups().
SceneObject * AiActorImplementation::getMovementMarker (int i)
Definition at line 1722 of file AiActor.cpp.
References movementMarkers.
Referenced by server::zone::objects::creature::ai::AiActor::getMovementMarker().
Vector< ManagedReference< SceneObject * > > * AiActorImplementation::getMovementMarkers ()
Definition at line 1712 of file AiActor.cpp.
References movementMarkers.
Referenced by server::zone::objects::creature::ai::AiActor::getMovementMarkers().
int AiActorImplementation::getMovementMarkersSize ()
Definition at line 1717 of file AiActor.cpp.
References movementMarkers.
Referenced by server::zone::objects::creature::ai::AiActor::getMovementMarkersSize().
Behavior * AiActorImplementation::getNextBehaviorFromTree (BehaviorTree * tree)
Definition at line 803 of file AiActorImplementation.cpp.
References trees.
Referenced by server::zone::objects::creature::ai::AiActor::getNextBehaviorFromTree().
PatrolPoint * AiActorImplementation::getNextStepPosition ()
Definition at line 1697 of file AiActor.cpp.
References nextStepPosition.
Referenced by server::zone::objects::creature::ai::AiActor::getNextStepPosition().
CreatureTemplateReference * AiActorImplementation::getNpcTemplate ()
Definition at line 1676 of file AiActor.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::getNpcTemplate().
int AiActorImplementation::getNumberOfPlayersInRange ()
Definition at line 1795 of file AiActor.cpp.
References numberOfPlayersInRange.
Referenced by server::zone::objects::creature::ai::AiActor::getNumberOfPlayersInRange(), and notifyPositionUpdate().
PatrolPointsVector * AiActorImplementation::getPatrolPoints ()
Definition at line 1751 of file AiActor.cpp.
References patrolPoints.
Referenced by server::zone::objects::creature::ai::AiActor::getPatrolPoints().
float AiActorImplementation::getRespawnTimer ()
Definition at line 1785 of file AiActor.cpp.
References respawnTimer.
Referenced by server::zone::objects::creature::ai::AiActor::getRespawnTimer().
String AiActorImplementation::getSocialGroup ()
Definition at line 1982 of file AiActor.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::getSocialGroup().
float AiActorImplementation::getStun ()
Definition at line 1894 of file AiActor.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::ai::AiActor::getStun().
Vector< ManagedReference< WeaponObject * > > AiActorImplementation::getWeapons ()
Definition at line 779 of file AiActorImplementation.cpp.
References weapons.
Referenced by server::zone::objects::creature::ai::AiActor::getWeapons().
void AiActorImplementation::initializeTransientMembers ()
Initializes the transient members of ManagedObject, must call the inherited object method first.
Precondition
{ transient members are not initialized }
Postcondition
{ transient members are initialized }
Definition at line 235 of file AiActorImplementation.cpp.
References currentMessage, currentState, currentStateName, defaultStateName, transitions, and server::zone::objects::creature::ai::AiActor::UNFINISHED.
Referenced by server::zone::objects::creature::ai::AiActor::initializeTransientMembers(), and readObject().
bool AiActorImplementation::isActorObject () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 2045 of file AiActor.cpp.
Referenced by server::zone::objects::creature::ai::AiActor::isActorObject().
bool AiActorImplementation::isAggressiveTo (CreatureObject * object)
Evaluates if this creature is aggresive to the object
Precondition
{ }
Postcondition
{ }
Returns
returns true if its aggressive
Definition at line 745 of file AiActorImplementation.cpp.
References CreatureFlag::AGGRESSIVE, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::player::PlayerObject::getFactionStatus(), server::zone::objects::creature::CreatureObject::getPlayerObject(), host, isAttackableBy(), and FactionStatus::ONLEAVE.
Referenced by server::zone::objects::creature::ai::AiActor::isAggressiveTo().
bool AiActorImplementation::isAttackableBy (CreatureObject * object)
Evaluates if this object can be attacket by the passed creature object
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns true if the creature object can attack this
Definition at line 1831 of file AiActor.cpp.
References host, server::zone::objects::creature::CreatureObject::isAiActor(), and FactionStatus::ONLEAVE.
Referenced by isAggressiveTo(), and server::zone::objects::creature::ai::AiActor::isAttackableBy().
bool AiActorImplementation::isCamouflaged (CreatureObject * target)
Definition at line 1681 of file AiActor.cpp.
References isConcealed(), and isScentMasked().
Referenced by server::zone::objects::creature::ai::AiActor::isCamouflaged(), and notifyPositionUpdate().
bool AiActorImplementation::isConcealed (CreatureObject * target)
Definition at line 397 of file AiActorImplementation.cpp.
References camouflagedObjects, server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::hasState(), host, CreatureState::MASKSCENT, and targetMutex.
Referenced by isCamouflaged(), and server::zone::objects::creature::ai::AiActor::isConcealed().
bool AiActorImplementation::isKiller ()
Definition at line 1950 of file AiActor.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::isKiller().
bool AiActorImplementation::isScentMasked (CreatureObject * target)
Definition at line 365 of file AiActorImplementation.cpp.
References camouflagedObjects, server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::hasState(), host, CreatureState::MASKSCENT, and targetMutex.
Referenced by isCamouflaged(), and server::zone::objects::creature::ai::AiActor::isScentMasked().
bool AiActorImplementation::isShowNextPosition ()
Definition at line 1707 of file AiActor.cpp.
References showNextMovementPosition.
Referenced by server::zone::objects::creature::ai::AiActor::isShowNextPosition().
bool AiActorImplementation::isStalker ()
Definition at line 1942 of file AiActor.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::ai::AiActor::isStalker().
void AiActorImplementation::loadTemplateData (CreatureTemplate * templateData)
Definition at line 39 of file AiActorImplementation.cpp.
References _this, aiTemplate, server::zone::ZoneServer::createObject(), currentMessage, currentState, currentStateName, defaultStateName, server::zone::objects::scene::SceneObjectImplementation::error(), OutfitTangibleObject::getCustomizationVariables(), server::zone::objects::scene::SceneObjectImplementation::getLoggingName(), MobileOutfit::getObjects(), OutfitTangibleObject::getObjectTemplate(), MobileOutfitGroup::getOutfits(), server::zone::templates::mobile::CreatureTemplate::getTemplateName(), server::zone::objects::scene::SceneObjectImplementation::getZoneProcessServer(), server::zone::ZoneProcessServer::getZoneServer(), host, loadedOutfit, npcTemplate, server::zone::objects::scene::SceneObjectImplementation::server, setLevel(), server::zone::objects::scene::SceneObjectImplementation::setLoggingName(), and weapons.
Referenced by server::zone::objects::creature::ai::AiActor::loadTemplateData().
void AiActorImplementation::lock (bool doLock = true) protected
Definition at line 1326 of file AiActor.cpp.
References _this.
void AiActorImplementation::lock (ManagedObject * obj) protected
Definition at line 1330 of file AiActor.cpp.
References _this.
void server::zone::objects::creature::ai::AiActorImplementation::next (unsigned short msg)
calculate next state based on initial state and message
Referenced by server::zone::objects::creature::ai::AiActor::next().
void AiActorImplementation::next ()
Definition at line 270 of file AiActorImplementation.cpp.
Referenced by addDefender(), removeDefender(), setDefender(), and setOblivious().
int AiActorImplementation::notifyConverseObservers (CreatureObject * converser)
Definition at line 351 of file AiActorImplementation.cpp.
References ObserverEventType::CONVERSE.
Referenced by server::zone::objects::creature::ai::AiActor::notifyConverseObservers().
void AiActorImplementation::notifyDespawn (Zone * zone)
Definition at line 520 of file AiActorImplementation.cpp.
References _this, currentState, moveEvent, and server::zone::objects::scene::SceneObjectImplementation::zone.
Referenced by server::zone::objects::creature::ai::AiActor::notifyDespawn().
void AiActorImplementation::notifyDissapear (QuadTreeEntry * entry)
Definition at line 334 of file AiActorImplementation.cpp.
References despawnEvent, followObject, host, server::zone::objects::scene::SceneObject::isPlayerCreature(), numberOfPlayersInRange, and setFollowObject().
Referenced by server::zone::objects::creature::ai::AiActor::notifyDissapear().
void AiActorImplementation::notifyInsert (QuadTreeEntry * entry)
Definition at line 324 of file AiActorImplementation.cpp.
References host, server::zone::objects::scene::SceneObject::isPlayerCreature(), and numberOfPlayersInRange.
Referenced by server::zone::objects::creature::ai::AiActor::notifyInsert().
void AiActorImplementation::notifyPositionUpdate (QuadTreeEntry * entry)
Uses position updates to perform a think
Definition at line 291 of file AiActorImplementation.cpp.
References _this, currentState, doAwarenessCheck(), getFerocity(), getFollowObject(), getNumberOfPlayersInRange(), host, isCamouflaged(), and CreatureFlag::NONE.
Referenced by server::zone::objects::creature::ai::AiActor::notifyPositionUpdate().
AiActorImplementation::operator const AiActor * ()
Definition at line 1322 of file AiActor.cpp.
void AiActorImplementation::queueDizzyFallEvent ()
Definition at line 496 of file AiActorImplementation.cpp.
References host.
Referenced by server::zone::objects::creature::ai::AiActor::queueDizzyFallEvent().
void AiActorImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 1361 of file AiActor.cpp.
References initializeTransientMembers(), and readObjectMember().
bool AiActorImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 1380 of file AiActor.cpp.
References baby, camouflagedObjects, currentMessage, currentStateName, defaultStateName, despawnOnNoPlayerInRange, followObject, homeLocation, host, loadedOutfit, movementMarkers, nextStepPosition, npcTemplate, numberOfPlayersInRange, patrolPoints, respawnTimer, showNextMovementPosition, skillCommands, and weapons.
Referenced by readObject().
void AiActorImplementation::removeDefender (SceneObject * defender)
Definition at line 722 of file AiActorImplementation.cpp.
References followObject, server::zone::objects::creature::ai::AiActor::FORGOT, host, server::zone::objects::scene::SceneObject::isCreatureObject(), next(), and setDefender().
Referenced by server::zone::objects::creature::ai::AiActor::removeDefender().
void AiActorImplementation::resetBehaviorList (BehaviorTree * tree)
Definition at line 811 of file AiActorImplementation.cpp.
References trees.
Referenced by server::zone::objects::creature::ai::AiActor::resetBehaviorList().
void AiActorImplementation::respawn (Zone * zone, int level)
Definition at line 540 of file AiActorImplementation.cpp.
References PatrolPoint::getCell(), PatrolPoint::getPositionX(), PatrolPoint::getPositionY(), PatrolPoint::getPositionZ(), homeLocation, host, setLevel(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::objects::creature::ai::AiActor::respawn().
void AiActorImplementation::rlock (bool doLock = true) protected
Definition at line 1334 of file AiActor.cpp.
References _this.
void AiActorImplementation::runlock (bool doLock = true) protected
Definition at line 1350 of file AiActor.cpp.
References _this.
void AiActorImplementation::scheduleDespawn (int timeToDespawn)
Definition at line 529 of file AiActorImplementation.cpp.
Referenced by server::zone::objects::creature::ai::AiActor::scheduleDespawn().
void AiActorImplementation::scheduleDespawn ()
Definition at line 1770 of file AiActor.cpp.
void AiActorImplementation::sendConversationStartTo (SceneObject * player)
Definition at line 681 of file AiActorImplementation.cpp.
References ObserverEventType::CONVERSE, currentState, server::zone::objects::scene::SceneObjectImplementation::error(), host, server::zone::objects::scene::SceneObject::isPlayerCreature(), npcTemplate, ObserverEventType::SELECTCONVERSATION, ObserverEventType::STARTCONVERSATION, and ObserverEventType::STOPCONVERSATION.
Referenced by server::zone::objects::creature::ai::AiActor::sendConversationStartTo().
void AiActorImplementation::setBehaviorStatus (Behavior * b, int status)
Definition at line 790 of file AiActorImplementation.cpp.
References statuses.
Referenced by server::zone::objects::creature::ai::AiActor::setBehaviorStatus().
void AiActorImplementation::setCurrentMessage (unsigned short msg)
Definition at line 1671 of file AiActor.cpp.
References currentMessage.
Referenced by server::zone::objects::creature::ai::AiActor::setCurrentMessage().
void AiActorImplementation::setDefender (SceneObject * defender)
Definition at line 711 of file AiActorImplementation.cpp.
References server::zone::objects::creature::ai::AiActor::ATTACKED, host, next(), and setFollowObject().
Referenced by removeDefender(), and server::zone::objects::creature::ai::AiActor::setDefender().
void AiActorImplementation::setDespawnOnNoPlayerInRange (bool val)
Definition at line 501 of file AiActorImplementation.cpp.
References despawnOnNoPlayerInRange.
Referenced by server::zone::objects::creature::ai::AiActor::setDespawnOnNoPlayerInRange().
void AiActorImplementation::setFollowObject (SceneObject * targ)
Definition at line 1805 of file AiActor.cpp.
References followObject.
Referenced by notifyDissapear(), setDefender(), and server::zone::objects::creature::ai::AiActor::setFollowObject().
void AiActorImplementation::setHomeLocation (float x, float z, float y, SceneObject * cell = NULL)
Definition at line 1756 of file AiActor.cpp.
References homeLocation.
Referenced by server::zone::objects::creature::ai::AiActor::setHomeLocation().
void AiActorImplementation::setHost (CreatureObject * creo)
Definition at line 1659 of file AiActor.cpp.
References _this, and host.
Referenced by server::zone::objects::creature::ai::AiActor::setHost().
void AiActorImplementation::setLevel (int lvl)
Definition at line 160 of file AiActorImplementation.cpp.
References calculateAttackMaxDamage(), calculateAttackMinDamage(), calculateAttackSpeed(), host, npcTemplate, server::zone::objects::tangible::weapon::WeaponObject::setAttackSpeed(), server::zone::objects::tangible::weapon::WeaponObject::setMaxDamage(), server::zone::objects::tangible::weapon::WeaponObject::setMinDamage(), and weapons.
Referenced by loadTemplateData(), respawn(), and server::zone::objects::creature::ai::AiActor::setLevel().
void AiActorImplementation::setNextPosition (PatrolPoint & point)
Definition at line 766 of file AiActorImplementation.cpp.
References patrolPoints, and targetMutex.
Referenced by server::zone::objects::creature::ai::AiActor::setNextPosition().
void AiActorImplementation::setNextStepPosition (float x, float z, float y, SceneObject * cell = NULL)
Definition at line 1686 of file AiActor.cpp.
References nextStepPosition, and targetMutex.
Referenced by server::zone::objects::creature::ai::AiActor::setNextStepPosition().
void AiActorImplementation::setOblivious ()
Definition at line 1824 of file AiActor.cpp.
References FORGOT, next(), and setTargetObject().
Referenced by server::zone::objects::creature::ai::AiActor::setOblivious().
void AiActorImplementation::setRespawnTimer (float resp)
Definition at line 1780 of file AiActor.cpp.
References respawnTimer.
Referenced by server::zone::objects::creature::ai::AiActor::setRespawnTimer().
void AiActorImplementation::setShowNextPosition (bool val)
Definition at line 1702 of file AiActor.cpp.
References showNextMovementPosition.
Referenced by server::zone::objects::creature::ai::AiActor::setShowNextPosition().
void AiActorImplementation::setTargetObject (SceneObject * obj)
Definition at line 1810 of file AiActor.cpp.
References clearPatrolPoints(), followObject, and targetMutex.
Referenced by setOblivious(), and server::zone::objects::creature::ai::AiActor::setTargetObject().
void AiActorImplementation::unlock (bool doLock = true) protected
Definition at line 1346 of file AiActor.cpp.
References _this.
void AiActorImplementation::updateLastDamageReceived ()
Definition at line 1865 of file AiActor.cpp.
References lastDamageReceived.
Referenced by server::zone::objects::creature::ai::AiActor::updateLastDamageReceived().
void AiActorImplementation::wlock (bool doLock = true) protected
Definition at line 1338 of file AiActor.cpp.
References _this.
void AiActorImplementation::wlock (ManagedObject * obj) protected
Definition at line 1342 of file AiActor.cpp.
References _this.
void AiActorImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 1466 of file AiActor.cpp.
References writeObjectMembers().
int AiActorImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 1473 of file AiActor.cpp.
References baby, camouflagedObjects, currentMessage, currentStateName, defaultStateName, despawnOnNoPlayerInRange, followObject, homeLocation, host, loadedOutfit, movementMarkers, nextStepPosition, npcTemplate, numberOfPlayersInRange, patrolPoints, respawnTimer, showNextMovementPosition, skillCommands, and weapons.
Referenced by writeObject().
Friends And Related Function Documentation
friend class AiActor friend
Definition at line 845 of file AiActor.h.
Member Data Documentation
WeakReference<AiActor*> server::zone::objects::creature::ai::AiActorImplementation::_this
Definition at line 811 of file AiActor.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), doAwarenessCheck(), loadTemplateData(), lock(), notifyDespawn(), notifyPositionUpdate(), rlock(), runlock(), setHost(), unlock(), and wlock().
Reference<AiTemplate* > server::zone::objects::creature::ai::AiActorImplementation::aiTemplate protected
Definition at line 539 of file AiActor.h.
Referenced by AiActorImplementation(), and loadTemplateData().
unsigned const short server::zone::objects::creature::ai::AiActorImplementation::ALMOSTDEAD = 5 static
Definition at line 518 of file AiActor.h.
unsigned const short server::zone::objects::creature::ai::AiActorImplementation::ATTACKED = 2 static
Definition at line 512 of file AiActor.h.
Reference<AiAwarenessEvent* > server::zone::objects::creature::ai::AiActorImplementation::awarenessEvent protected
Definition at line 563 of file AiActor.h.
Referenced by destroyActor().
bool server::zone::objects::creature::ai::AiActorImplementation::baby protected
Definition at line 575 of file AiActor.h.
Referenced by readObjectMember(), and writeObjectMembers().
Vector<ManagedReference<SceneObject* > > server::zone::objects::creature::ai::AiActorImplementation::camouflagedObjects protected
Definition at line 545 of file AiActor.h.
Referenced by isConcealed(), isScentMasked(), readObjectMember(), and writeObjectMembers().
unsigned short server::zone::objects::creature::ai::AiActorImplementation::currentMessage protected
Definition at line 549 of file AiActor.h.
Referenced by initializeTransientMembers(), loadTemplateData(), readObjectMember(), setCurrentMessage(), and writeObjectMembers().
Reference<AiStateComponent* > server::zone::objects::creature::ai::AiActorImplementation::currentState protected
Definition at line 533 of file AiActor.h.
Referenced by doAwarenessCheck(), initializeTransientMembers(), loadTemplateData(), notifyDespawn(), notifyPositionUpdate(), and sendConversationStartTo().
String server::zone::objects::creature::ai::AiActorImplementation::currentStateName protected
Definition at line 535 of file AiActor.h.
Referenced by initializeTransientMembers(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
unsigned const short server::zone::objects::creature::ai::AiActorImplementation::DEAD = 4 static
Definition at line 516 of file AiActor.h.
String server::zone::objects::creature::ai::AiActorImplementation::defaultStateName protected
Definition at line 537 of file AiActor.h.
Referenced by initializeTransientMembers(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
Reference<DespawnCreatureOnPlayerDissappear* > server::zone::objects::creature::ai::AiActorImplementation::despawnEvent protected
Definition at line 565 of file AiActor.h.
Referenced by clearDespawnEvent(), destroyActor(), and notifyDissapear().
bool server::zone::objects::creature::ai::AiActorImplementation::despawnOnNoPlayerInRange protected
Definition at line 555 of file AiActor.h.
Referenced by AiActorImplementation(), getDespawnOnNoPlayerInRange(), readObjectMember(), setDespawnOnNoPlayerInRange(), and writeObjectMembers().
unsigned const short server::zone::objects::creature::ai::AiActorImplementation::FINISHED = 0 static
Definition at line 508 of file AiActor.h.
ManagedReference<SceneObject* > server::zone::objects::creature::ai::AiActorImplementation::followObject protected
Definition at line 577 of file AiActor.h.
Referenced by getFollowObject(), notifyDissapear(), readObjectMember(), removeDefender(), setFollowObject(), setTargetObject(), and writeObjectMembers().
unsigned const short server::zone::objects::creature::ai::AiActorImplementation::FORGOT = 7 static
Definition at line 522 of file AiActor.h.
Referenced by setOblivious().
PatrolPoint server::zone::objects::creature::ai::AiActorImplementation::homeLocation protected
Definition at line 571 of file AiActor.h.
Referenced by getHomeLocation(), readObjectMember(), respawn(), setHomeLocation(), and writeObjectMembers().
ManagedReference<CreatureObject* > server::zone::objects::creature::ai::AiActorImplementation::host protected
Definition at line 551 of file AiActor.h.
Referenced by activatePostureRecovery(), addDefender(), AiActorImplementation(), fillAttributeList(), getDamageMax(), getDamageMin(), getHost(), isAggressiveTo(), isAttackableBy(), isConcealed(), isScentMasked(), loadTemplateData(), notifyDissapear(), notifyInsert(), notifyPositionUpdate(), queueDizzyFallEvent(), readObjectMember(), removeDefender(), respawn(), sendConversationStartTo(), setDefender(), setHost(), setLevel(), and writeObjectMembers().
unsigned const short server::zone::objects::creature::ai::AiActorImplementation::INTERESTED = 3 static
Definition at line 514 of file AiActor.h.
Time server::zone::objects::creature::ai::AiActorImplementation::lastDamageReceived protected
Definition at line 581 of file AiActor.h.
Referenced by getLastDamageReceived(), and updateLastDamageReceived().
bool server::zone::objects::creature::ai::AiActorImplementation::loadedOutfit protected
Definition at line 547 of file AiActor.h.
Referenced by AiActorImplementation(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
Reference<AiMoveEvent* > server::zone::objects::creature::ai::AiActorImplementation::moveEvent protected
Definition at line 561 of file AiActor.h.
Referenced by destroyActor(), and notifyDespawn().
Reference<Vector<ManagedReference<SceneObject* > >* > server::zone::objects::creature::ai::AiActorImplementation::movementMarkers protected
Definition at line 589 of file AiActor.h.
Referenced by addMovementMarker(), dropAllMovemementMarkers(), dropMovementMarker(), getMovementMarker(), getMovementMarkers(), getMovementMarkersSize(), readObjectMember(), and writeObjectMembers().
PatrolPoint server::zone::objects::creature::ai::AiActorImplementation::nextStepPosition protected
Definition at line 573 of file AiActor.h.
Referenced by getNextStepPosition(), readObjectMember(), setNextStepPosition(), and writeObjectMembers().
unsigned const short server::zone::objects::creature::ai::AiActorImplementation::NONE = 0xFFFF static
Definition at line 524 of file AiActor.h.
CreatureTemplateReference server::zone::objects::creature::ai::AiActorImplementation::npcTemplate protected
Definition at line 541 of file AiActor.h.
Referenced by calculateAttackMaxDamage(), calculateAttackMinDamage(), getAcid(), getArmor(), getAttackMap(), getBaseXp(), getBlast(), getChanceHit(), getCold(), getCreatureTemplate(), getDiet(), getElectricity(), getEnergy(), getFactionString(), getFerocity(), getHeat(), getKinetic(), getLightSaber(), getLootGroups(), getNpcTemplate(), getSocialGroup(), getStun(), isKiller(), isStalker(), loadTemplateData(), readObjectMember(), sendConversationStartTo(), setLevel(), and writeObjectMembers().
int server::zone::objects::creature::ai::AiActorImplementation::numberOfPlayersInRange protected
Definition at line 557 of file AiActor.h.
Referenced by AiActorImplementation(), getNumberOfPlayersInRange(), notifyDissapear(), notifyInsert(), readObjectMember(), and writeObjectMembers().
PatrolPointsVector server::zone::objects::creature::ai::AiActorImplementation::patrolPoints protected
Definition at line 569 of file AiActor.h.
Referenced by addPatrolPoint(), clearPatrolPoints(), getPatrolPoints(), readObjectMember(), setNextPosition(), and writeObjectMembers().
float server::zone::objects::creature::ai::AiActorImplementation::respawnTimer protected
Definition at line 553 of file AiActor.h.
Referenced by AiActorImplementation(), getRespawnTimer(), readObjectMember(), setRespawnTimer(), and writeObjectMembers().
unsigned const short server::zone::objects::creature::ai::AiActorImplementation::SCARED = 6 static
Definition at line 520 of file AiActor.h.
bool server::zone::objects::creature::ai::AiActorImplementation::showNextMovementPosition protected
Definition at line 587 of file AiActor.h.
Referenced by AiActorImplementation(), isShowNextPosition(), readObjectMember(), setShowNextPosition(), and writeObjectMembers().
Reference<Vector<String>* > server::zone::objects::creature::ai::AiActorImplementation::skillCommands protected
Definition at line 567 of file AiActor.h.
Referenced by readObjectMember(), and writeObjectMembers().
HashTable<Behavior*, int> server::zone::objects::creature::ai::AiActorImplementation::statuses protected
Definition at line 529 of file AiActor.h.
Referenced by getBehaviorStatus(), and setBehaviorStatus().
Mutex server::zone::objects::creature::ai::AiActorImplementation::targetMutex protected
Definition at line 579 of file AiActor.h.
Referenced by addPatrolPoint(), clearPatrolPoints(), isConcealed(), isScentMasked(), setNextPosition(), setNextStepPosition(), and setTargetObject().
Reference<AiThinkEvent* > server::zone::objects::creature::ai::AiActorImplementation::thinkEvent protected
Definition at line 559 of file AiActor.h.
Referenced by destroyActor().
VectorMap<String, String> server::zone::objects::creature::ai::AiActorImplementation::transitions protected
Definition at line 527 of file AiActor.h.
Referenced by addTransition(), and initializeTransientMembers().
HashTable<BehaviorTree*, BehaviorTreeList*> server::zone::objects::creature::ai::AiActorImplementation::trees protected
Definition at line 531 of file AiActor.h.
Referenced by addBehaviorToTree(), getNextBehaviorFromTree(), and resetBehaviorList().
unsigned const short server::zone::objects::creature::ai::AiActorImplementation::UNFINISHED = 1 static
Definition at line 510 of file AiActor.h.
const int server::zone::objects::creature::ai::AiActorImplementation::UPDATEMOVEMENTINTERVAL = 500 static
Definition at line 584 of file AiActor.h.
Vector<ManagedReference<WeaponObject* > > server::zone::objects::creature::ai::AiActorImplementation::weapons protected
Definition at line 543 of file AiActor.h.
Referenced by getWeapons(), loadTemplateData(), readObjectMember(), setLevel(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/AiActor.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/AiActor.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/AiActorImplementation.cpp