Core3: server::zone::managers::creature::CreatureManagerImplementation Class Reference
server::zone::managers::creature::CreatureManagerImplementation Class Reference
#include <CreatureManager.h>
Public Member Functions
CreatureManagerImplementation (Zone *planet)
CreatureManagerImplementation (DummyConstructorParameter *param)
void initialize ()
TangibleObject * spawnLair (unsigned int lairTemplate, int difficulty, float x, float z, float y, unsigned int faction)
CreatureObject * spawnCreatureWithAi (unsigned int templateCRC, float x, float z, float y, SceneObject *cell, bool persistent=false)
CreatureObject * spawnCreatureWithLevel (unsigned int mobileTemplateCRC, int level, float x, float z, float y, unsigned long long parentID=0)
CreatureObject * spawnCreature (unsigned int templateCRC, float x, float z, float y, unsigned long long parentID=0)
CreatureObject * spawnCreature (unsigned int templateCRC, unsigned int objectCRC, float x, float z, float y, unsigned long long parentID=0, bool persistent=false)
CreatureObject * createCreature (unsigned int templateCRC, bool persistent=false, unsigned int mobileTemplate=0)
void placeCreature (CreatureObject *creature, float x, float z, float y, unsigned long long parentID)
String getTemplateToSpawn (unsigned int templateCRC)
int notifyDestruction (TangibleObject *destructor, AiAgent *destructedObject, int condition)
void loadSpawnAreas ()
void loadAiTemplates ()
void loadSingleSpawns ()
void loadTrainers ()
void loadMissionSpawns ()
void loadInformants ()
void spawnRandomCreaturesAround (SceneObject *creature)
void spawnRandomCreature (int number, float x, float z, float y, unsigned long long parentID=0)
void harvest (Creature *creature, CreatureObject *player, int selectedID)
void milk (Creature *creature, CreatureObject *player)
void sample (Creature *creature, CreatureObject *player)
void addToReservePool (AiAgent *agent)
int getSpawnedRandomCreatures ()
Vector3 getRandomJediTrainer ()
Vector< ManagedReference
< SpawnArea * > > * getWorldSpawnAreas ()
Vector< ManagedReference
< SpawnArea * > > * getFactionalNeutralMissionSpawnAreas ()
Vector< ManagedReference
< SpawnArea * > > * getFactionalRebelMissionSpawnAreas ()
Vector< ManagedReference
< SpawnArea * > > * getFactionalImperialMissionSpawnAreas ()
Vector< ManagedReference
< SpawnArea * > > * getNonfactionalMissionSpawnAreas ()
SpawnArea * getSpawnArea (const String &areaname)
bool addWearableItem (CreatureObject *creature, TangibleObject *clothing)
operator const CreatureManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::manager::ZoneManagerImplementation
ZoneManagerImplementation (const String &name)
ZoneManagerImplementation (DummyConstructorParameter *param)
void setZoneProcessor (ZoneProcessServer *server)
operator const ZoneManager * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< CreatureManager * > _this
Public Attributes inherited from server::zone::manager::ZoneManagerImplementation
WeakReference< ZoneManager * > _this
Static Public Attributes
static const short NOTMILKED = 0x00
static const short BEINGMILKED = 0x01
static const short ALREADYMILKED = 0x02
static const short HASDNA = 0x00
static const short DNASAMPLED = 0x01
static const short DNADEATH = 0x03
Protected Member Functions
virtual ~CreatureManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::manager::ZoneManagerImplementation
virtual ~ZoneManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference< Zone * > zone
SpawnAreaMap spawnAreaMap
Reference< AiMap * > aiMap
Reference
< CreatureTemplateManager * > creatureTemplateManager
Reference< DnaManager * > dnaManager
SortedVector< ManagedReference
< AiAgent * > > reservePool
int spawnedRandomCreatures
Protected Attributes inherited from server::zone::manager::ZoneManagerImplementation
ManagedReference< ZoneServer * > zoneServer
ManagedReference
< ZoneProcessServer * > zoneProcessor
Reference< ObjectManager * > objectManager
Static Protected Attributes
static Mutex loadMutex
Private Member Functions
bool createCreatureChildrenObjects (CreatureObject *creature, unsigned int templateCRC, bool persistent=false, unsigned int mobileTemplateCRC=0)
void setCreatureTemplateManager ()
Friends
class CreatureManager
Detailed Description
Definition at line 315 of file CreatureManager.h.
Constructor & Destructor Documentation
CreatureManagerImplementation::CreatureManagerImplementation (Zone * planet)
Definition at line 666 of file CreatureManager.cpp.
References _initializeImplementation(), setCreatureTemplateManager(), spawnedRandomCreatures, and zone.
CreatureManagerImplementation::CreatureManagerImplementation (DummyConstructorParameter * param)
Definition at line 504 of file CreatureManager.cpp.
References _initializeImplementation().
CreatureManagerImplementation::~CreatureManagerImplementation () protected virtual
Definition at line 509 of file CreatureManager.cpp.
Member Function Documentation
DistributedObjectStub * CreatureManagerImplementation::_getStub ()
Definition at line 529 of file CreatureManager.cpp.
References _this.
void CreatureManagerImplementation::_initializeImplementation () protected
Definition at line 516 of file CreatureManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CreatureManagerImplementation().
void CreatureManagerImplementation::_serializationHelperMethod () protected
Definition at line 565 of file CreatureManager.cpp.
Referenced by _initializeImplementation().
void CreatureManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 524 of file CreatureManager.cpp.
References _this.
Referenced by server::zone::managers::creature::CreatureManager::CreatureManager().
void CreatureManagerImplementation::addToReservePool (AiAgent * agent)
Definition at line 691 of file CreatureManager.cpp.
References _this, reservePool, and spawnedRandomCreatures.
Referenced by server::zone::managers::creature::CreatureManager::addToReservePool().
bool CreatureManagerImplementation::addWearableItem (CreatureObject * creature, TangibleObject * clothing)
Definition at line 717 of file CreatureManagerImplementation.cpp.
References server::chat::ChatManager::broadcastMessage(), server::zone::objects::scene::SceneObject::broadcastObject(), server::zone::objects::creature::CreatureObject::doAnimation(), server::zone::objects::scene::SceneObject::getArrangementDescriptor(), server::zone::objects::scene::SceneObject::getArrangementDescriptorSize(), server::zone::templates::SharedObjectTemplate::getFullTemplateString(), server::zone::objects::creature::CreatureObject::getMoodID(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::scene::SceneObject::getParent(), SharedTangibleObjectTemplate::getPlayerRaces(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::isWeaponObject(), server::zone::objects::scene::SceneObject::isWearableObject(), server::zone::objects::scene::SceneObject::transferObject(), and server::zone::manager::ZoneManagerImplementation::zoneServer.
Referenced by server::zone::managers::creature::CreatureManager::addWearableItem().
CreatureObject * CreatureManagerImplementation::createCreature (unsigned int templateCRC, bool persistent = false, unsigned int mobileTemplate = 0)
Definition at line 253 of file CreatureManagerImplementation.cpp.
References createCreatureChildrenObjects(), and server::zone::manager::ZoneManagerImplementation::zoneServer.
Referenced by server::zone::managers::creature::CreatureManager::createCreature().
bool CreatureManagerImplementation::createCreatureChildrenObjects (CreatureObject * creature, unsigned int templateCRC, bool persistent = false, unsigned int mobileTemplateCRC = 0) private
Definition at line 325 of file CreatureManagerImplementation.cpp.
References creatureTemplateManager, server::zone::templates::mobile::CreatureTemplate::getDefaultWeapon(), server::zone::objects::scene::SceneObject::hasSlotDescriptor(), server::zone::objects::scene::SceneObject::transferObject(), and server::zone::manager::ZoneManagerImplementation::zoneServer.
Referenced by createCreature().
void CreatureManagerImplementation::finalize () protected
Definition at line 513 of file CreatureManager.cpp.
Vector< ManagedReference< SpawnArea * > > * CreatureManagerImplementation::getFactionalImperialMissionSpawnAreas ()
Definition at line 725 of file CreatureManager.cpp.
References spawnAreaMap.
Referenced by server::zone::managers::creature::CreatureManager::getFactionalImperialMissionSpawnAreas().
Vector< ManagedReference< SpawnArea * > > * CreatureManagerImplementation::getFactionalNeutralMissionSpawnAreas ()
Definition at line 715 of file CreatureManager.cpp.
References spawnAreaMap.
Referenced by server::zone::managers::creature::CreatureManager::getFactionalNeutralMissionSpawnAreas().
Vector< ManagedReference< SpawnArea * > > * CreatureManagerImplementation::getFactionalRebelMissionSpawnAreas ()
Definition at line 720 of file CreatureManager.cpp.
References spawnAreaMap.
Referenced by server::zone::managers::creature::CreatureManager::getFactionalRebelMissionSpawnAreas().
Vector< ManagedReference< SpawnArea * > > * CreatureManagerImplementation::getNonfactionalMissionSpawnAreas ()
Definition at line 730 of file CreatureManager.cpp.
References spawnAreaMap.
Referenced by server::zone::managers::creature::CreatureManager::getNonfactionalMissionSpawnAreas().
Vector3 CreatureManagerImplementation::getRandomJediTrainer ()
Definition at line 774 of file CreatureManagerImplementation.cpp.
References SpawnAreaMap::getRandomJediTrainer(), and spawnAreaMap.
Referenced by server::zone::managers::creature::CreatureManager::getRandomJediTrainer().
SpawnArea * CreatureManagerImplementation::getSpawnArea (const String & areaname)
Definition at line 321 of file CreatureManagerImplementation.cpp.
References spawnAreaMap.
Referenced by server::zone::managers::creature::CreatureManager::getSpawnArea().
int CreatureManagerImplementation::getSpawnedRandomCreatures ()
Definition at line 705 of file CreatureManager.cpp.
References spawnedRandomCreatures.
Referenced by server::zone::managers::creature::CreatureManager::getSpawnedRandomCreatures().
String CreatureManagerImplementation::getTemplateToSpawn (unsigned int templateCRC)
Definition at line 204 of file CreatureManagerImplementation.cpp.
References creatureTemplateManager, server::zone::templates::mobile::CreatureTemplate::getTemplateName(), and server::zone::templates::mobile::CreatureTemplate::getTemplates().
Referenced by server::zone::managers::creature::CreatureManager::getTemplateToSpawn().
Vector< ManagedReference< SpawnArea * > > * CreatureManagerImplementation::getWorldSpawnAreas ()
Definition at line 710 of file CreatureManager.cpp.
References spawnAreaMap.
Referenced by server::zone::managers::creature::CreatureManager::getWorldSpawnAreas().
void CreatureManagerImplementation::harvest (Creature * creature, CreatureObject * player, int selectedID)
Send System Messages
Send bonus message
Send group spam
Definition at line 515 of file CreatureManagerImplementation.cpp.
References server::zone::objects::creature::Creature::addAlreadyHarvested(), server::zone::objects::group::GroupObject::broadcastMessage(), server::zone::objects::creature::Creature::canHarvestMe(), server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::creature::Creature::getBoneMax(), server::zone::objects::creature::Creature::getBoneType(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::group::GroupObject::getGroupHarvestModifier(), server::zone::objects::creature::Creature::getHideMax(), server::zone::objects::creature::Creature::getHideType(), server::zone::objects::tangible::TangibleObject::getLevel(), server::zone::objects::creature::Creature::getMeatMax(), server::zone::objects::creature::Creature::getMeatType(), server::zone::objects::scene::SceneObject::getObjectNameStringIdFile(), server::zone::objects::scene::SceneObject::getObjectNameStringIdName(), server::zone::objects::scene::SceneObject::getPendingTask(), server::zone::ZoneServer::getResourceManager(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::Zone::getZoneServer(), server::zone::objects::creature::AiAgent::hasLoot(), server::zone::objects::creature::Creature::isCreature(), server::zone::objects::creature::CreatureObject::isGrouped(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), server::chat::StringIdChatParameter::setTU(), zone, and server::zone::manager::ZoneManagerImplementation::zoneServer.
Referenced by server::zone::managers::creature::CreatureManager::harvest().
void CreatureManagerImplementation::initialize ()
Definition at line 676 of file CreatureManager.cpp.
References loadAiTemplates(), loadInformants(), loadMissionSpawns(), loadSingleSpawns(), loadSpawnAreas(), and loadTrainers().
Referenced by server::zone::managers::creature::CreatureManager::initialize().
void CreatureManagerImplementation::loadAiTemplates ()
Definition at line 376 of file CreatureManagerImplementation.cpp.
References aiMap, and loadMutex.
Referenced by initialize(), and server::zone::managers::creature::CreatureManager::loadAiTemplates().
void CreatureManagerImplementation::loadInformants ()
Definition at line 509 of file CreatureManagerImplementation.cpp.
Referenced by initialize(), and server::zone::managers::creature::CreatureManager::loadInformants().
void CreatureManagerImplementation::loadMissionSpawns ()
Definition at line 503 of file CreatureManagerImplementation.cpp.
Referenced by initialize(), and server::zone::managers::creature::CreatureManager::loadMissionSpawns().
void CreatureManagerImplementation::loadSingleSpawns ()
Definition at line 387 of file CreatureManagerImplementation.cpp.
Referenced by initialize(), and server::zone::managers::creature::CreatureManager::loadSingleSpawns().
void CreatureManagerImplementation::loadSpawnAreas ()
Definition at line 371 of file CreatureManagerImplementation.cpp.
References SpawnAreaMap::loadMap(), spawnAreaMap, and zone.
Referenced by initialize(), and server::zone::managers::creature::CreatureManager::loadSpawnAreas().
void CreatureManagerImplementation::loadTrainers ()
Definition at line 498 of file CreatureManagerImplementation.cpp.
Referenced by initialize(), and server::zone::managers::creature::CreatureManager::loadTrainers().
void CreatureManagerImplementation::lock (bool doLock = true) protected
Definition at line 537 of file CreatureManager.cpp.
References _this.
void CreatureManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 541 of file CreatureManager.cpp.
References _this.
void CreatureManagerImplementation::milk (Creature * creature, CreatureObject * player)
Definition at line 660 of file CreatureManagerImplementation.cpp.
References BEINGMILKED, server::zone::objects::creature::Creature::canMilkMe(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::Creature::isCreature(), server::zone::objects::creature::CreatureObject::isMounted(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::Creature::setMilkState(), and zone.
Referenced by server::zone::managers::creature::CreatureManager::milk().
int CreatureManagerImplementation::notifyDestruction (TangibleObject * destructor, AiAgent * destructedObject, int condition)
Precondition
{ destructor and destructedObject locked }
Postcondition
{ destructor and destructedObject locked }
Definition at line 396 of file CreatureManagerImplementation.cpp.
References FactionManager::awardFactionStanding(), server::zone::managers::loot::LootManager::calculateLootCredits(), server::zone::managers::loot::LootManager::createLoot(), CreaturePosture::DEAD, server::zone::objects::creature::CreatureObject::getGroupID(), server::zone::objects::tangible::threat::ThreatMap::getHighestDamageGroupLeader(), server::zone::objects::tangible::threat::ThreatMap::getHighestDamagePlayer(), server::zone::objects::tangible::TangibleObject::getLevel(), server::zone::objects::scene::SceneObject::getPendingTask(), server::zone::objects::creature::AiAgent::getPvPFaction(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::tangible::TangibleObject::getThreatMap(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::AiAgent::isEventMob(), server::zone::objects::creature::CreatureObject::isNonPlayerCreatureObject(), ObserverEventType::KILLEDCREATURE, server::zone::objects::tangible::threat::ThreatMap::removeAll(), server::zone::objects::tangible::threat::ThreatMap::removeObservers(), server::zone::objects::creature::AiAgent::scheduleDespawn(), server::zone::objects::creature::CreatureObject::setCashCredits(), server::zone::objects::scene::SceneObject::setContainerOwnerID(), server::zone::objects::creature::CreatureObject::setPosture(), server::zone::objects::creature::CreatureObject::updateTimeOfDeath(), and server::zone::manager::ZoneManagerImplementation::zoneServer.
Referenced by server::zone::managers::creature::CreatureManager::notifyDestruction().
CreatureManagerImplementation::operator const CreatureManager * ()
Definition at line 533 of file CreatureManager.cpp.
void CreatureManagerImplementation::placeCreature (CreatureObject * creature, float x, float z, float y, unsigned long long parentID)
Definition at line 287 of file CreatureManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::creature::AiAgent::setHomeLocation(), server::zone::objects::scene::SceneObject::transferObject(), zone, and server::zone::manager::ZoneManagerImplementation::zoneServer.
Referenced by server::zone::managers::creature::CreatureManager::placeCreature(), and spawnRandomCreature().
void CreatureManagerImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::manager::ZoneManagerImplementation.
Definition at line 572 of file CreatureManager.cpp.
References readObjectMember().
bool CreatureManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 591 of file CreatureManager.cpp.
References reservePool, spawnAreaMap, spawnedRandomCreatures, and zone.
Referenced by readObject().
void CreatureManagerImplementation::rlock (bool doLock = true) protected
Definition at line 545 of file CreatureManager.cpp.
References _this.
void CreatureManagerImplementation::runlock (bool doLock = true) protected
Definition at line 561 of file CreatureManager.cpp.
References _this.
void CreatureManagerImplementation::sample (Creature * creature, CreatureObject * player)
Gather a DNA sample from the given creature
Definition at line 685 of file CreatureManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::addPendingTask(), server::zone::objects::creature::Creature::canCollectDna(), server::zone::objects::scene::SceneObject::getPendingTask(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::Creature::hasSkillToSampleMe(), server::zone::objects::creature::Creature::isCreature(), server::zone::objects::creature::CreatureObject::isMounted(), server::zone::objects::creature::CreatureObject::isNonPlayerCreatureObject(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zone.
Referenced by server::zone::managers::creature::CreatureManager::sample().
void CreatureManagerImplementation::setCreatureTemplateManager () private
Definition at line 45 of file CreatureManagerImplementation.cpp.
References creatureTemplateManager.
Referenced by CreatureManagerImplementation().
CreatureObject* server::zone::managers::creature::CreatureManagerImplementation::spawnCreature (unsigned int templateCRC, float x, float z, float y, unsigned long long parentID = 0)
Referenced by server::zone::managers::creature::CreatureManager::spawnCreature(), spawnCreatureWithLevel(), and spawnRandomCreature().
CreatureObject* server::zone::managers::creature::CreatureManagerImplementation::spawnCreature (unsigned int templateCRC, unsigned int objectCRC, float x, float z, float y, unsigned long long parentID = 0, bool persistent = false)
CreatureObject * CreatureManagerImplementation::spawnCreatureWithAi (unsigned int templateCRC, float x, float z, float y, SceneObject * cell, bool persistent = false)
Spawns the specified creature into zone
Precondition
{ this unlocked }
Postcondition
{ creature is in zone }
Parameters
templateCRC template string crc of the creature to spawn
x position x
y position y
parentID cell object id (optional)
Returns
returns creature object that has been spawned, NULL on error
Definition at line 182 of file CreatureManagerImplementation.cpp.
References creatureTemplateManager, server::zone::objects::creature::ai::AiActor::getHost(), server::zone::objects::creature::ai::AiActor::loadTemplateData(), server::zone::objects::creature::ai::AiActor::setHomeLocation(), and server::zone::manager::ZoneManagerImplementation::zoneServer.
Referenced by server::zone::managers::creature::CreatureManager::spawnCreatureWithAi().
CreatureObject * CreatureManagerImplementation::spawnCreatureWithLevel (unsigned int mobileTemplateCRC, int level, float x, float z, float y, unsigned long long parentID = 0)
Definition at line 173 of file CreatureManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::setLevel(), and spawnCreature().
Referenced by server::zone::managers::creature::CreatureManager::spawnCreatureWithLevel().
TangibleObject * CreatureManagerImplementation::spawnLair (unsigned int lairTemplate, int difficulty, float x, float z, float y, unsigned int faction)
Definition at line 70 of file CreatureManagerImplementation.cpp.
References CreatureFlag::ATTACKABLE, creatureTemplateManager, ObserverEventType::DAMAGERECEIVED, server::zone::templates::mobile::LairTemplate::getBuilding(), server::zone::templates::mobile::LairTemplate::getMobiles(), ObserverType::LAIR, ObserverEventType::OBJECTDESTRUCTION, zone, and server::zone::manager::ZoneManagerImplementation::zoneServer.
Referenced by server::zone::managers::creature::CreatureManager::spawnLair().
void CreatureManagerImplementation::spawnRandomCreature (int number, float x, float z, float y, unsigned long long parentID = 0)
Definition at line 127 of file CreatureManagerImplementation.cpp.
References _this, creatureTemplateManager, placeCreature(), reservePool, spawnCreature(), and spawnedRandomCreatures.
Referenced by server::zone::managers::creature::CreatureManager::spawnRandomCreature(), and spawnRandomCreaturesAround().
void CreatureManagerImplementation::spawnRandomCreaturesAround (SceneObject * creature)
Definition at line 60 of file CreatureManagerImplementation.cpp.
References spawnedRandomCreatures, spawnRandomCreature(), and zone.
Referenced by server::zone::managers::creature::CreatureManager::spawnRandomCreaturesAround().
void CreatureManagerImplementation::unlock (bool doLock = true) protected
Definition at line 557 of file CreatureManager.cpp.
References _this.
void CreatureManagerImplementation::wlock (bool doLock = true) protected
Definition at line 549 of file CreatureManager.cpp.
References _this.
void CreatureManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 553 of file CreatureManager.cpp.
References _this.
void CreatureManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::manager::ZoneManagerImplementation.
Definition at line 617 of file CreatureManager.cpp.
References writeObjectMembers().
int CreatureManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 624 of file CreatureManager.cpp.
References reservePool, spawnAreaMap, spawnedRandomCreatures, and zone.
Referenced by writeObject().
Friends And Related Function Documentation
friend class CreatureManager friend
Definition at line 469 of file CreatureManager.h.
Member Data Documentation
WeakReference<CreatureManager*> server::zone::managers::creature::CreatureManagerImplementation::_this
Definition at line 435 of file CreatureManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addToReservePool(), lock(), rlock(), runlock(), spawnRandomCreature(), unlock(), and wlock().
Reference<AiMap* > server::zone::managers::creature::CreatureManagerImplementation::aiMap protected
Definition at line 321 of file CreatureManager.h.
Referenced by loadAiTemplates().
const short server::zone::managers::creature::CreatureManagerImplementation::ALREADYMILKED = 0x02 static
Definition at line 338 of file CreatureManager.h.
const short server::zone::managers::creature::CreatureManagerImplementation::BEINGMILKED = 0x01 static
Definition at line 336 of file CreatureManager.h.
Referenced by milk().
Reference<CreatureTemplateManager* > server::zone::managers::creature::CreatureManagerImplementation::creatureTemplateManager protected
Definition at line 323 of file CreatureManager.h.
Referenced by createCreatureChildrenObjects(), getTemplateToSpawn(), setCreatureTemplateManager(), spawnCreatureWithAi(), spawnLair(), and spawnRandomCreature().
const short server::zone::managers::creature::CreatureManagerImplementation::DNADEATH = 0x03 static
Definition at line 344 of file CreatureManager.h.
Reference<DnaManager* > server::zone::managers::creature::CreatureManagerImplementation::dnaManager protected
Definition at line 325 of file CreatureManager.h.
const short server::zone::managers::creature::CreatureManagerImplementation::DNASAMPLED = 0x01 static
Definition at line 342 of file CreatureManager.h.
const short server::zone::managers::creature::CreatureManagerImplementation::HASDNA = 0x00 static
Definition at line 340 of file CreatureManager.h.
Mutex CreatureManagerImplementation::loadMutex static protected
Definition at line 331 of file CreatureManager.h.
Referenced by loadAiTemplates().
const short server::zone::managers::creature::CreatureManagerImplementation::NOTMILKED = 0x00 static
Definition at line 334 of file CreatureManager.h.
SortedVector<ManagedReference<AiAgent* > > server::zone::managers::creature::CreatureManagerImplementation::reservePool protected
Definition at line 327 of file CreatureManager.h.
Referenced by addToReservePool(), readObjectMember(), spawnRandomCreature(), and writeObjectMembers().
SpawnAreaMap server::zone::managers::creature::CreatureManagerImplementation::spawnAreaMap protected
Definition at line 319 of file CreatureManager.h.
Referenced by getFactionalImperialMissionSpawnAreas(), getFactionalNeutralMissionSpawnAreas(), getFactionalRebelMissionSpawnAreas(), getNonfactionalMissionSpawnAreas(), getRandomJediTrainer(), getSpawnArea(), getWorldSpawnAreas(), loadSpawnAreas(), readObjectMember(), and writeObjectMembers().
int server::zone::managers::creature::CreatureManagerImplementation::spawnedRandomCreatures protected
Definition at line 329 of file CreatureManager.h.
Referenced by addToReservePool(), CreatureManagerImplementation(), getSpawnedRandomCreatures(), readObjectMember(), spawnRandomCreature(), spawnRandomCreaturesAround(), and writeObjectMembers().
ManagedReference<Zone* > server::zone::managers::creature::CreatureManagerImplementation::zone protected
Definition at line 317 of file CreatureManager.h.
Referenced by CreatureManagerImplementation(), harvest(), loadSpawnAreas(), milk(), placeCreature(), readObjectMember(), sample(), spawnLair(), spawnRandomCreaturesAround(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/CreatureManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/CreatureManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/CreatureManagerImplementation.cpp