Core3: server::zone::objects::mission::MissionObject Class Reference
server::zone::objects::mission::MissionObject Class Reference
#include <MissionObject.h>
Public Member Functions
MissionObject ()
WaypointObject * createWaypoint ()
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
void updateToDatabaseAllObjects (bool startTask)
void setRefreshCounter (int ctr, bool notifyClient=true)
void setTypeCRC (unsigned int crc, bool notifyClient=true)
void initializeTransientMembers ()
void sendBaselinesTo (SceneObject *player)
void setMissionDescription (const String &file, const String &id, bool notifyClient=true)
void setMissionTitle (const String &file, const String &id, bool notifyClient=true)
void setMissionTargetName (const String &target, bool notifyClient=true)
void setMissionDifficulty (int difficulty, bool notifyClient=true)
void setMissionDifficulty (int difficulty, int display, bool notifyClient=true)
void setRewardCredits (int creds, bool notifyClient=true)
void setTargetTemplate (SharedObjectTemplate *templ, bool notifyClient=true)
void setStartPosition (float posX, float posY, const String &planet, bool notifyClient=true)
void setStartPosition (float posX, float posY, bool notifyClient=true)
void setEndPosition (float posX, float posY, const String &planet, bool notifyClient=true)
void setCreatorName (const String &name, bool notifyClient=true)
unsigned int getStartPlanetCRC ()
void updateMissionLocation ()
void abort ()
void setFaction (const int missionFaction)
void setMissionObjective (MissionObjective *obj)
void setStartPlanet (const String &planet)
void setRewardFactionPointsRebel (int points)
void setRewardFactionPointsImperial (int points)
void setEndPlanet (String &planetName)
void setMissionTarget (NpcSpawnPoint *target)
void setMissionTargetDest (NpcSpawnPoint *target)
void setMissionNumber (int num)
void setTargetOptionalTemplate (const String &tml)
void setTemplateStrings (const String &temp1, const String &temp2)
MissionObjective * getMissionObjective ()
int getFaction ()
int getRewardFactionPointsRebel ()
int getRewardFactionPointsImperial ()
float getStartPositionX ()
float getStartPositionY ()
String getTargetOptionalTemplate ()
String getStartPlanet ()
float getEndPositionX ()
float getEndPositionY ()
String getEndPlanet ()
WaypointObject * getWaypointToMission ()
NpcSpawnPoint * getMissionTarget ()
NpcSpawnPoint * getMissionTargetDest ()
unsigned int getTypeCRC ()
int getRewardCredits ()
UnicodeString getCreatorName ()
int getDifficultyLevel ()
int getDifficultyDisplay ()
StringId * getMissionDescription ()
StringId * getMissionTitle ()
String getTargetName ()
int getRefreshCounter ()
int getMissionNumber ()
SharedObjectTemplate * getTargetTemplate ()
bool isSurveyMission ()
bool isMissionObject ()
String getTemplateString1 ()
String getTemplateString2 ()
unsigned long long getTargetObjectId ()
void setTargetObjectId (unsigned long long id)
void setMissionLevel (int level)
int getMissionLevel ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::intangible::IntangibleObject
IntangibleObject ()
void initializeTransientMembers ()
void loadTemplateData (SharedObjectTemplate *templateData)
bool isIntangibleObject ()
void sendBaselinesTo (SceneObject *player)
void updateStatus (int newStatus, bool notifyClient=true)
unsigned int getStatus ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject ()
void initializePrivateData ()
void loadTemplateData (SharedObjectTemplate *templateData)
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendAttributeListTo (CreatureObject *object)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
void openContainerTo (CreatureObject *player)
byte checkContainerPermission (CreatureObject *player, unsigned short permission)
void closeContainerTo (CreatureObject *player, bool notify=true)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets=true)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
String getDetailedDescription ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static unsigned const int DESTROY = 0x74EF9BE3
static unsigned const int BOUNTY = 0x2904F372
static unsigned const int DELIVER = 0xE5C27EC6
static unsigned const int CRAFTING = 0xE5F6DC59
static unsigned const int ESCORT = 0x682B871E
static unsigned const int ESCORT2ME = 0x58F59884
static unsigned const int ESCORTTOCREATOR = 0x5E4C7163
static unsigned const int HUNTING = 0x906999A2
static unsigned const int MUSICIAN = 0x4AD93196
static unsigned const int DANCER = 0xF067B37
static unsigned const int RECON = 0x34F4C2E4
static unsigned const int SURVEY = 0x19C9FAC1
static const int FACTIONNEUTRAL = 0
static const int FACTIONIMPERIAL = 0xDB4ACC54
static const int FACTIONREBEL = 0x16148850
Protected Member Functions
MissionObject (DummyConstructorParameter *param)
virtual ~MissionObject ()
Protected Member Functions inherited from server::zone::objects::intangible::IntangibleObject
IntangibleObject (DummyConstructorParameter *param)
virtual ~IntangibleObject ()
Protected Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject (DummyConstructorParameter *param)
virtual ~SceneObject ()
Friends
class MissionObjectHelper
Detailed Description
Definition at line 123 of file MissionObject.h.
Constructor & Destructor Documentation
MissionObject::MissionObject ()
Definition at line 27 of file MissionObject.cpp.
References server::zone::objects::mission::MissionObjectImplementation::_setStub().
MissionObject::MissionObject (DummyConstructorParameter * param) protected
Definition at line 34 of file MissionObject.cpp.
MissionObject::~MissionObject () protected virtual
Definition at line 38 of file MissionObject.cpp.
Member Function Documentation
DistributedObjectServant * MissionObject::_getImplementation ()
Definition at line 935 of file MissionObject.cpp.
Referenced by abort(), createWaypoint(), destroyObjectFromDatabase(), getCreatorName(), getDifficultyDisplay(), getDifficultyLevel(), getEndPlanet(), getEndPositionX(), getEndPositionY(), getFaction(), getMissionDescription(), getMissionLevel(), getMissionNumber(), getMissionObjective(), getMissionTarget(), getMissionTargetDest(), getMissionTitle(), getRefreshCounter(), getRewardCredits(), getRewardFactionPointsImperial(), getRewardFactionPointsRebel(), getStartPlanet(), getStartPlanetCRC(), getStartPositionX(), getStartPositionY(), getTargetName(), getTargetObjectId(), getTargetOptionalTemplate(), getTargetTemplate(), getTemplateString1(), getTemplateString2(), getTypeCRC(), getWaypointToMission(), initializeTransientMembers(), isMissionObject(), isSurveyMission(), sendBaselinesTo(), setCreatorName(), setEndPlanet(), setEndPosition(), setFaction(), setMissionDescription(), setMissionDifficulty(), setMissionLevel(), setMissionNumber(), setMissionObjective(), setMissionTarget(), setMissionTargetDest(), setMissionTargetName(), setMissionTitle(), setRefreshCounter(), setRewardCredits(), setRewardFactionPointsImperial(), setRewardFactionPointsRebel(), setStartPlanet(), setStartPosition(), setTargetObjectId(), setTargetOptionalTemplate(), setTargetTemplate(), setTemplateStrings(), setTypeCRC(), updateMissionLocation(), and updateToDatabaseAllObjects().
DistributedObjectServant * MissionObject::_getImplementationForRead ()
Definition at line 941 of file MissionObject.cpp.
void MissionObject::_setImplementation (DistributedObjectServant * servant)
Definition at line 945 of file MissionObject.cpp.
void MissionObject::abort ()
Definition at line 334 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::abort(), and RPC_ABORT__.
Referenced by server::zone::managers::mission::MissionManagerImplementation::handleMissionAbort().
WaypointObject * MissionObject::createWaypoint ()
Definition at line 43 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::createWaypoint(), and RPC_CREATEWAYPOINT__.
void MissionObject::destroyObjectFromDatabase (bool destroyContainedObjects = false)
Destroys this object from database
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
destroyContainedObjects if true, will destroy from database all its contained objects
Definition at line 56 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::destroyObjectFromDatabase(), and RPC_DESTROYOBJECTFROMDATABASE__BOOL_.
Referenced by server::zone::managers::mission::MissionManagerImplementation::removeMission().
UnicodeString MissionObject::getCreatorName ()
Definition at line 716 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getCreatorName(), and RPC_GETCREATORNAME__.
Referenced by MissionObjectMessage3::MissionObjectMessage3(), and MissionObjectDeltaMessage3::updateCreator().
int MissionObject::getDifficultyDisplay ()
Definition at line 744 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getDifficultyDisplay(), and RPC_GETDIFFICULTYDISPLAY__.
int MissionObject::getDifficultyLevel ()
Definition at line 731 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getDifficultyLevel(), and RPC_GETDIFFICULTYLEVEL__.
Referenced by server::zone::managers::mission::MissionManagerImplementation::createDestroyMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::createSurveyMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::generateRandomFactionalDestroyMissionDescription(), and MissionObjectMessage3::MissionObjectMessage3().
String MissionObject::getEndPlanet ()
Definition at line 636 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getEndPlanet(), and RPC_GETENDPLANET__.
Referenced by MissionObjectMessage3::MissionObjectMessage3().
float MissionObject::getEndPositionX ()
Definition at line 610 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getEndPositionX(), and RPC_GETENDPOSITIONX__.
Referenced by server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::BountyHunterTargetTask(), and MissionObjectMessage3::MissionObjectMessage3().
float MissionObject::getEndPositionY ()
Definition at line 623 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getEndPositionY(), and RPC_GETENDPOSITIONY__.
Referenced by server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::BountyHunterTargetTask(), and MissionObjectMessage3::MissionObjectMessage3().
int MissionObject::getFaction ()
Definition at line 515 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getFaction(), and RPC_GETFACTION__.
Referenced by server::zone::managers::mission::MissionManagerImplementation::createCraftingMissionObjectives(), server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::performDeliverConversation(), and server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::performPickupConversation().
StringId * MissionObject::getMissionDescription ()
Definition at line 757 of file MissionObject.cpp.
References _getImplementation(), and server::zone::objects::mission::MissionObjectImplementation::getMissionDescription().
Referenced by MissionObjectMessage3::MissionObjectMessage3().
int MissionObject::getMissionLevel ()
Definition at line 922 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getMissionLevel(), and RPC_GETMISSIONLEVEL__.
Referenced by server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::BountyHunterTargetTask(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::callArakydDroid(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::findTarget(), server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::handleScreen(), and server::zone::objects::mission::bountyhunter::BountyHunterDroid::transmitBiologicalSignature().
int MissionObject::getMissionNumber ()
Definition at line 803 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getMissionNumber(), and RPC_GETMISSIONNUMBER__.
Referenced by server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::performDeliverConversation(), and server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::performPickupConversation().
MissionObjective * MissionObject::getMissionObjective ()
Definition at line 502 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getMissionObjective(), and RPC_GETMISSIONOBJECTIVE__.
Referenced by server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::BountyHunterTargetTask(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::callArakydDroid(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::findTarget(), server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::handleScreen(), and server::zone::objects::mission::bountyhunter::BountyHunterDroid::transmitBiologicalSignature().
NpcSpawnPoint * MissionObject::getMissionTarget ()
Definition at line 664 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getMissionTarget(), and RPC_GETMISSIONTARGET__.
NpcSpawnPoint * MissionObject::getMissionTargetDest ()
Definition at line 677 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getMissionTargetDest(), and RPC_GETMISSIONTARGETDEST__.
StringId * MissionObject::getMissionTitle ()
Definition at line 766 of file MissionObject.cpp.
References _getImplementation(), and server::zone::objects::mission::MissionObjectImplementation::getMissionTitle().
Referenced by MissionObjectMessage3::MissionObjectMessage3().
int MissionObject::getRefreshCounter ()
Definition at line 790 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getRefreshCounter(), and RPC_GETREFRESHCOUNTER__.
int MissionObject::getRewardCredits ()
Definition at line 703 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getRewardCredits(), and RPC_GETREWARDCREDITS__.
Referenced by MissionObjectMessage3::MissionObjectMessage3().
int MissionObject::getRewardFactionPointsImperial ()
Definition at line 541 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getRewardFactionPointsImperial(), and RPC_GETREWARDFACTIONPOINTSIMPERIAL__.
int MissionObject::getRewardFactionPointsRebel ()
Definition at line 528 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getRewardFactionPointsRebel(), and RPC_GETREWARDFACTIONPOINTSREBEL__.
String MissionObject::getStartPlanet ()
Definition at line 595 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getStartPlanet(), and RPC_GETSTARTPLANET__.
Referenced by MissionObjectMessage3::MissionObjectMessage3().
unsigned int MissionObject::getStartPlanetCRC ()
Definition at line 308 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getStartPlanetCRC(), and RPC_GETSTARTPLANETCRC__.
float MissionObject::getStartPositionX ()
Definition at line 554 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getStartPositionX(), and RPC_GETSTARTPOSITIONX__.
Referenced by MissionObjectMessage3::MissionObjectMessage3().
float MissionObject::getStartPositionY ()
Definition at line 567 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getStartPositionY(), and RPC_GETSTARTPOSITIONY__.
Referenced by MissionObjectMessage3::MissionObjectMessage3().
String MissionObject::getTargetName ()
Definition at line 775 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getTargetName(), and RPC_GETTARGETNAME__.
Referenced by server::zone::managers::mission::MissionManagerImplementation::createSurveyMissionObjectives(), and MissionObjectMessage3::MissionObjectMessage3().
unsigned long long MissionObject::getTargetObjectId ()
Definition at line 881 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getTargetObjectId(), and RPC_GETTARGETOBJECTID__.
Referenced by server::zone::managers::mission::MissionManagerImplementation::handleMissionAccept().
String MissionObject::getTargetOptionalTemplate ()
Definition at line 580 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getTargetOptionalTemplate(), and RPC_GETTARGETOPTIONALTEMPLATE__.
Referenced by server::zone::managers::mission::MissionManagerImplementation::createDestroyMissionObjectives(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission().
SharedObjectTemplate * MissionObject::getTargetTemplate ()
Definition at line 816 of file MissionObject.cpp.
References _getImplementation(), and server::zone::objects::mission::MissionObjectImplementation::getTargetTemplate().
Referenced by MissionObjectMessage3::MissionObjectMessage3().
String MissionObject::getTemplateString1 ()
Definition at line 851 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getTemplateString1(), and RPC_GETTEMPLATESTRING1__.
Referenced by server::zone::managers::mission::MissionManagerImplementation::createCraftingMissionObjectives().
String MissionObject::getTemplateString2 ()
Definition at line 866 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getTemplateString2(), and RPC_GETTEMPLATESTRING2__.
unsigned int MissionObject::getTypeCRC ()
Definition at line 690 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getTypeCRC(), and RPC_GETTYPECRC__.
Referenced by server::zone::managers::mission::MissionManagerImplementation::createMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAbort(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAccept(), MissionObjectMessage3::MissionObjectMessage3(), server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::performDeliverConversation(), server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::performPickupConversation(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericCraftingMission().
WaypointObject * MissionObject::getWaypointToMission ()
Definition at line 651 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::getWaypointToMission(), and RPC_GETWAYPOINTTOMISSION__.
Referenced by MissionObjectMessage3::MissionObjectMessage3().
void MissionObject::initializeTransientMembers ()
Definition at line 114 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
bool MissionObject::isMissionObject ()
Definition at line 838 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::isMissionObject(), and RPC_ISMISSIONOBJECT__.
bool MissionObject::isSurveyMission ()
Definition at line 825 of file MissionObject.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObjectImplementation::isSurveyMission(), and RPC_ISSURVEYMISSION__.
void MissionObject::sendBaselinesTo (SceneObject * player)
Definition at line 127 of file MissionObject.cpp.
References _getImplementation(), RPC_SENDBASELINESTO__SCENEOBJECT_, and server::zone::objects::mission::MissionObjectImplementation::sendBaselinesTo().
void MissionObject::setCreatorName (const String & name, bool notifyClient = true)
Definition at line 293 of file MissionObject.cpp.
References _getImplementation(), RPC_SETCREATORNAME__STRING_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setCreatorName().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission().
void MissionObject::setEndPlanet (String & planetName)
Definition at line 417 of file MissionObject.cpp.
References _getImplementation(), RPC_SETENDPLANET__STRING_, and server::zone::objects::mission::MissionObjectImplementation::setEndPlanet().
void MissionObject::setEndPosition (float posX, float posY, const String & planet, bool notifyClient = true)
Definition at line 276 of file MissionObject.cpp.
References _getImplementation(), RPC_SETENDPOSITION__FLOAT_FLOAT_STRING_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setEndPosition().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission().
void MissionObject::setFaction (const int missionFaction)
Definition at line 347 of file MissionObject.cpp.
References _getImplementation(), RPC_SETFACTION__INT_, and server::zone::objects::mission::MissionObjectImplementation::setFaction().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission().
void MissionObject::setMissionDescription (const String & file, const String & id, bool notifyClient = true)
Definition at line 141 of file MissionObject.cpp.
References _getImplementation(), RPC_SETMISSIONDESCRIPTION__STRING_STRING_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setMissionDescription().
Referenced by server::zone::managers::mission::MissionManagerImplementation::generateRandomFactionalDestroyMissionDescription(), server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericCraftingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission().
void MissionObject::setMissionDifficulty (int difficulty, bool notifyClient = true)
Definition at line 188 of file MissionObject.cpp.
References _getImplementation(), RPC_SETMISSIONDIFFICULTY__INT_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setMissionDifficulty().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission().
void MissionObject::setMissionDifficulty (int difficulty, int display, bool notifyClient = true)
Definition at line 203 of file MissionObject.cpp.
References _getImplementation(), RPC_SETMISSIONDIFFICULTY__INT_INT_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setMissionDifficulty().
void MissionObject::setMissionLevel (int level)
Definition at line 908 of file MissionObject.cpp.
References _getImplementation(), RPC_SETMISSIONLEVEL__INT_, and server::zone::objects::mission::MissionObjectImplementation::setMissionLevel().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission().
void MissionObject::setMissionNumber (int num)
Definition at line 459 of file MissionObject.cpp.
References _getImplementation(), RPC_SETMISSIONNUMBER__INT_, and server::zone::objects::mission::MissionObjectImplementation::setMissionNumber().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission().
void MissionObject::setMissionObjective (MissionObjective * obj)
Definition at line 361 of file MissionObject.cpp.
References _getImplementation(), RPC_SETMISSIONOBJECTIVE__MISSIONOBJECTIVE_, and server::zone::objects::mission::MissionObjectImplementation::setMissionObjective().
Referenced by server::zone::managers::mission::MissionManagerImplementation::createBountyMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::createCraftingMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::createDeliverMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::createDestroyMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::createEntertainerMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::createHuntingMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::createReconMissionObjectives(), and server::zone::managers::mission::MissionManagerImplementation::createSurveyMissionObjectives().
void MissionObject::setMissionTarget (NpcSpawnPoint * target)
Definition at line 431 of file MissionObject.cpp.
References _getImplementation(), RPC_SETMISSIONTARGET__NPCSPAWNPOINT_, and server::zone::objects::mission::MissionObjectImplementation::setMissionTarget().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission().
void MissionObject::setMissionTargetDest (NpcSpawnPoint * target)
Definition at line 445 of file MissionObject.cpp.
References _getImplementation(), RPC_SETMISSIONTARGETDEST__NPCSPAWNPOINT_, and server::zone::objects::mission::MissionObjectImplementation::setMissionTargetDest().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission().
void MissionObject::setMissionTargetName (const String & target, bool notifyClient = true)
Definition at line 173 of file MissionObject.cpp.
References _getImplementation(), RPC_SETMISSIONTARGETNAME__STRING_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setMissionTargetName().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission().
void MissionObject::setMissionTitle (const String & file, const String & id, bool notifyClient = true)
Definition at line 157 of file MissionObject.cpp.
References _getImplementation(), RPC_SETMISSIONTITLE__STRING_STRING_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setMissionTitle().
Referenced by server::zone::managers::mission::MissionManagerImplementation::generateRandomFactionalDestroyMissionDescription(), server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericCraftingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission().
void MissionObject::setRefreshCounter (int ctr, bool notifyClient = true)
Definition at line 84 of file MissionObject.cpp.
References _getImplementation(), RPC_SETREFRESHCOUNTER__INT_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setRefreshCounter().
void MissionObject::setRewardCredits (int creds, bool notifyClient = true)
Definition at line 219 of file MissionObject.cpp.
References _getImplementation(), RPC_SETREWARDCREDITS__INT_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setRewardCredits().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission().
void MissionObject::setRewardFactionPointsImperial (int points)
Definition at line 403 of file MissionObject.cpp.
References _getImplementation(), RPC_SETREWARDFACTIONPOINTSIMPERIAL__INT_, and server::zone::objects::mission::MissionObjectImplementation::setRewardFactionPointsImperial().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission().
void MissionObject::setRewardFactionPointsRebel (int points)
Definition at line 389 of file MissionObject.cpp.
References _getImplementation(), RPC_SETREWARDFACTIONPOINTSREBEL__INT_, and server::zone::objects::mission::MissionObjectImplementation::setRewardFactionPointsRebel().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission().
void MissionObject::setStartPlanet (const String & planet)
Definition at line 375 of file MissionObject.cpp.
References _getImplementation(), RPC_SETSTARTPLANET__STRING_, and server::zone::objects::mission::MissionObjectImplementation::setStartPlanet().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission().
void MissionObject::setStartPosition (float posX, float posY, const String & planet, bool notifyClient = true)
Definition at line 243 of file MissionObject.cpp.
References _getImplementation(), RPC_SETSTARTPOSITION__FLOAT_FLOAT_STRING_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setStartPosition().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission().
void MissionObject::setStartPosition (float posX, float posY, bool notifyClient = true)
Definition at line 260 of file MissionObject.cpp.
References _getImplementation(), RPC_SETSTARTPOSITION__FLOAT_FLOAT_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setStartPosition().
void MissionObject::setTargetObjectId (unsigned long long id)
Definition at line 894 of file MissionObject.cpp.
References _getImplementation(), RPC_SETTARGETOBJECTID__LONG_, and server::zone::objects::mission::MissionObjectImplementation::setTargetObjectId().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission().
void MissionObject::setTargetOptionalTemplate (const String & tml)
Definition at line 473 of file MissionObject.cpp.
References _getImplementation(), RPC_SETTARGETOPTIONALTEMPLATE__STRING_, and server::zone::objects::mission::MissionObjectImplementation::setTargetOptionalTemplate().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission().
void MissionObject::setTargetTemplate (SharedObjectTemplate * templ, bool notifyClient = true)
Definition at line 234 of file MissionObject.cpp.
References _getImplementation(), and server::zone::objects::mission::MissionObjectImplementation::setTargetTemplate().
Referenced by server::zone::managers::mission::MissionManagerImplementation::createCraftingMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericCraftingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission().
void MissionObject::setTemplateStrings (const String & temp1, const String & temp2)
Definition at line 487 of file MissionObject.cpp.
References _getImplementation(), RPC_SETTEMPLATESTRINGS__STRING_STRING_, and server::zone::objects::mission::MissionObjectImplementation::setTemplateStrings().
Referenced by server::zone::managers::mission::MissionManagerImplementation::createCraftingMissionObjectives(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission().
void MissionObject::setTypeCRC (unsigned int crc, bool notifyClient = true)
Definition at line 99 of file MissionObject.cpp.
References _getImplementation(), RPC_SETTYPECRC__INT_BOOL_, and server::zone::objects::mission::MissionObjectImplementation::setTypeCRC().
Referenced by server::zone::managers::mission::MissionManagerImplementation::populateMissionList(), server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericCraftingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission().
void MissionObject::updateMissionLocation ()
Definition at line 321 of file MissionObject.cpp.
References _getImplementation(), RPC_UPDATEMISSIONLOCATION__, and server::zone::objects::mission::MissionObjectImplementation::updateMissionLocation().
void MissionObject::updateToDatabaseAllObjects (bool startTask)
Updates this object and childre objects to database
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
startTask if true, queues a new update task
Definition at line 70 of file MissionObject.cpp.
References _getImplementation(), RPC_UPDATETODATABASEALLOBJECTS__BOOL_, and server::zone::objects::mission::MissionObjectImplementation::updateToDatabaseAllObjects().
Friends And Related Function Documentation
friend class MissionObjectHelper friend
Definition at line 309 of file MissionObject.h.
Member Data Documentation
unsigned const int server::zone::objects::mission::MissionObject::BOUNTY = 0x2904F372 static
Definition at line 127 of file MissionObject.h.
unsigned const int server::zone::objects::mission::MissionObject::CRAFTING = 0xE5F6DC59 static
Definition at line 131 of file MissionObject.h.
unsigned const int server::zone::objects::mission::MissionObject::DANCER = 0xF067B37 static
Definition at line 143 of file MissionObject.h.
unsigned const int server::zone::objects::mission::MissionObject::DELIVER = 0xE5C27EC6 static
Definition at line 129 of file MissionObject.h.
unsigned const int server::zone::objects::mission::MissionObject::DESTROY = 0x74EF9BE3 static
Definition at line 125 of file MissionObject.h.
unsigned const int server::zone::objects::mission::MissionObject::ESCORT = 0x682B871E static
Definition at line 133 of file MissionObject.h.
unsigned const int server::zone::objects::mission::MissionObject::ESCORT2ME = 0x58F59884 static
Definition at line 135 of file MissionObject.h.
unsigned const int server::zone::objects::mission::MissionObject::ESCORTTOCREATOR = 0x5E4C7163 static
Definition at line 137 of file MissionObject.h.
const int server::zone::objects::mission::MissionObject::FACTIONIMPERIAL = 0xDB4ACC54 static
Definition at line 151 of file MissionObject.h.
Referenced by server::zone::objects::mission::DeliverMissionObjectiveImplementation::activateWithResult(), and server::zone::objects::mission::MissionObjectiveImplementation::awardFactionPoints().
const int server::zone::objects::mission::MissionObject::FACTIONNEUTRAL = 0 static
Definition at line 149 of file MissionObject.h.
Referenced by server::zone::objects::mission::MissionObjectiveImplementation::awardFactionPoints().
const int server::zone::objects::mission::MissionObject::FACTIONREBEL = 0x16148850 static
Definition at line 153 of file MissionObject.h.
Referenced by server::zone::objects::mission::DeliverMissionObjectiveImplementation::activateWithResult(), and server::zone::objects::mission::MissionObjectiveImplementation::awardFactionPoints().
unsigned const int server::zone::objects::mission::MissionObject::HUNTING = 0x906999A2 static
Definition at line 139 of file MissionObject.h.
unsigned const int server::zone::objects::mission::MissionObject::MUSICIAN = 0x4AD93196 static
Definition at line 141 of file MissionObject.h.
unsigned const int server::zone::objects::mission::MissionObject::RECON = 0x34F4C2E4 static
Definition at line 145 of file MissionObject.h.
unsigned const int server::zone::objects::mission::MissionObject::SURVEY = 0x19C9FAC1 static
Definition at line 147 of file MissionObject.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObject.cpp