Core3: ResourceCommand Class Reference
ResourceCommand Class Reference
#include <ResourceCommand.h>
Public Member Functions
ResourceCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
void listResources (CreatureObject *creature, StringTokenizer *args)
void healthCheck (CreatureObject *creature, StringTokenizer *args)
void dumpResources (CreatureObject *creature, StringTokenizer *args)
void despawnResource (CreatureObject *creature, StringTokenizer *args)
void listResourceInfo (CreatureObject *creature, StringTokenizer *args)
Detailed Description
Definition at line 50 of file ResourceCommand.h.
Constructor & Destructor Documentation
ResourceCommand::ResourceCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file ResourceCommand.h.
Member Function Documentation
void ResourceCommand::despawnResource (CreatureObject * creature, StringTokenizer * args) inline
Definition at line 135 of file ResourceCommand.h.
References server::zone::ZoneServer::getResourceManager(), server::zone::objects::scene::SceneObject::getZoneServer(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
int ResourceCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 58 of file ResourceCommand.h.
References despawnResource(), dumpResources(), healthCheck(), listResourceInfo(), listResources(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
void ResourceCommand::dumpResources (CreatureObject * creature, StringTokenizer * args) inline
Definition at line 126 of file ResourceCommand.h.
References server::zone::ZoneServer::getResourceManager(), server::zone::objects::scene::SceneObject::getZoneServer(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
void ResourceCommand::healthCheck (CreatureObject * creature, StringTokenizer * args) inline
Definition at line 117 of file ResourceCommand.h.
References server::zone::ZoneServer::getResourceManager(), server::zone::objects::scene::SceneObject::getZoneServer(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
void ResourceCommand::listResourceInfo (CreatureObject * creature, StringTokenizer * args) inline
Definition at line 149 of file ResourceCommand.h.
References server::zone::ZoneServer::getResourceManager(), server::zone::objects::scene::SceneObject::getZoneServer(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
void ResourceCommand::listResources (CreatureObject * creature, StringTokenizer * args) inline
Definition at line 102 of file ResourceCommand.h.
References server::zone::ZoneServer::getResourceManager(), and server::zone::objects::scene::SceneObject::getZoneServer().
Referenced by doQueueCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/ResourceCommand.h