Core3: server::zone::managers::director::ScreenPlayObserver Class Reference
server::zone::managers::director::ScreenPlayObserver Class Reference
#include <ScreenPlayObserver.h>
Public Member Functions
ScreenPlayObserver ()
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void setScreenPlay (const String &screen)
void setScreenKey (const String &screenKey)
String getScreenPlay ()
String getScreenKey ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ScreenPlayObserver (DummyConstructorParameter *param)
virtual ~ScreenPlayObserver ()
Friends
class ScreenPlayObserverHelper
Detailed Description
Definition at line 25 of file ScreenPlayObserver.h.
Constructor & Destructor Documentation
ScreenPlayObserver::ScreenPlayObserver ()
Definition at line 13 of file ScreenPlayObserver.cpp.
References server::zone::managers::director::ScreenPlayObserverImplementation::_setStub().
ScreenPlayObserver::ScreenPlayObserver (DummyConstructorParameter * param) protected
Definition at line 20 of file ScreenPlayObserver.cpp.
ScreenPlayObserver::~ScreenPlayObserver () protected virtual
Definition at line 24 of file ScreenPlayObserver.cpp.
Member Function Documentation
DistributedObjectServant * ScreenPlayObserver::_getImplementation ()
Definition at line 104 of file ScreenPlayObserver.cpp.
Referenced by getScreenKey(), getScreenPlay(), notifyObserverEvent(), setScreenKey(), and setScreenPlay().
DistributedObjectServant * ScreenPlayObserver::_getImplementationForRead ()
Definition at line 110 of file ScreenPlayObserver.cpp.
void ScreenPlayObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 114 of file ScreenPlayObserver.cpp.
String ScreenPlayObserver::getScreenKey ()
Definition at line 89 of file ScreenPlayObserver.cpp.
References _getImplementation(), server::zone::managers::director::ScreenPlayObserverImplementation::getScreenKey(), and RPC_GETSCREENKEY__.
String ScreenPlayObserver::getScreenPlay ()
Definition at line 74 of file ScreenPlayObserver.cpp.
References _getImplementation(), server::zone::managers::director::ScreenPlayObserverImplementation::getScreenPlay(), and RPC_GETSCREENPLAY__.
int ScreenPlayObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 29 of file ScreenPlayObserver.cpp.
References _getImplementation(), server::zone::managers::director::ScreenPlayObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
void ScreenPlayObserver::setScreenKey (const String & screenKey)
Definition at line 60 of file ScreenPlayObserver.cpp.
References _getImplementation(), RPC_SETSCREENKEY__STRING_, and server::zone::managers::director::ScreenPlayObserverImplementation::setScreenKey().
void ScreenPlayObserver::setScreenPlay (const String & screen)
Definition at line 46 of file ScreenPlayObserver.cpp.
References _getImplementation(), RPC_SETSCREENPLAY__STRING_, and server::zone::managers::director::ScreenPlayObserverImplementation::setScreenPlay().
Referenced by server::zone::managers::director::DirectorManager::createObserver().
Friends And Related Function Documentation
friend class ScreenPlayObserverHelper friend
Definition at line 49 of file ScreenPlayObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/ScreenPlayObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/ScreenPlayObserver.cpp