Core3: PlanetMapCategoryList Class Reference
PlanetMapCategoryList Class Reference
#include <PlanetMapCategoryList.h>
Public Member Functions
PlanetMapCategoryList ()
bool containsKey (const String &key)
Reference< PlanetMapCategory * > & get (const String &key)
Reference< PlanetMapCategory * > & get (const int &key)
Reference< PlanetMapCategory * > & put (const String &key, const Reference< PlanetMapCategory * > &value)
Private Member Functions
int hash (const int &key)
int hash (const String &key)
Detailed Description
Definition at line 15 of file PlanetMapCategoryList.h.
Constructor & Destructor Documentation
PlanetMapCategoryList::PlanetMapCategoryList () inline
Definition at line 25 of file PlanetMapCategoryList.h.
Member Function Documentation
bool PlanetMapCategoryList::containsKey (const String & key) inline
Definition at line 32 of file PlanetMapCategoryList.h.
Reference<PlanetMapCategory*>& PlanetMapCategoryList::get (const String & key) inline
Definition at line 36 of file PlanetMapCategoryList.h.
Referenced by get(), TemplateManager::getPlanetMapCategoryByCrc(), and TemplateManager::getPlanetMapCategoryByName().
Reference<PlanetMapCategory*>& PlanetMapCategoryList::get (const int & key) inline
Definition at line 40 of file PlanetMapCategoryList.h.
References get().
int PlanetMapCategoryList::hash (const int & key) inline private
Definition at line 16 of file PlanetMapCategoryList.h.
int PlanetMapCategoryList::hash (const String & key) inline private
Definition at line 20 of file PlanetMapCategoryList.h.
Reference<PlanetMapCategory*>& PlanetMapCategoryList::put (const String & key, const Reference< PlanetMapCategory * > & value) inline
Definition at line 44 of file PlanetMapCategoryList.h.
Referenced by TemplateManager::loadPlanetMapCategories().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/templates/PlanetMapCategoryList.h