Core3: AlertStateComponent Class Reference
AlertStateComponent Class Reference
#include <AlertStateComponent.h>
Public Member Functions
uint16 onEnter (AiActor *actor)
uint16 doRecovery (AiActor *actor)
uint16 doMovement (AiActor *actor)
Public Member Functions inherited from AiStateComponent
virtual void notifyPositionUpdate (Observable *obs, QuadTreeEntry *entry)
void notifyDespawn (AiActor *actor, Zone *zone)
virtual void doAwarenessCheck (Observable *obs, Coordinate &start, uint64 time, CreatureObject *target)
virtual void onExit (AiActor *actor)
virtual uint16 tryRetreat (AiActor *actor)
virtual uint16 doAttack (AiActor *actor)
bool findNextPosition (Observable *obs, float maxDistance, float speed, PatrolPointsVector *patrolPoints, WorldCoordinates *nextPosition)
virtual float getMaxDistance (CreatureObject *host)
virtual float getSpeed (CreatureObject *host)
void setNextPosition (AiActor *actor, float x, float z, float y, SceneObject *cell=NULL)
void updateCurrentPosition (CreatureObject *host, PatrolPoint *pos)
void broadcastNextPositionUpdate (CreatureObject *host, PatrolPoint *point)
void checkNewAngle (AiActor *actor)
void sendConversationStartTo (CreatureObject *host, SceneObject *player)
void selectWeapon (AiActor *actor)
bool validateStateAttack (CreatureObject *target, String &args)
virtual bool isScared (CreatureObject *host, SceneObject *followObject)
Detailed Description
Definition at line 16 of file AlertStateComponent.h.
Member Function Documentation
uint16 AlertStateComponent::doMovement (AiActor * actor) inline virtual
Reimplemented from AiStateComponent.
Definition at line 64 of file AlertStateComponent.h.
References server::zone::objects::creature::ai::AiActor::activateMovementEvent(), AiStateComponent::checkNewAngle(), server::zone::objects::creature::ai::AiActor::getFollowObject(), server::zone::objects::creature::ai::AiActor::getHost(), AiStateComponent::isScared(), and server::zone::objects::scene::SceneObject::setDirection().
uint16 AlertStateComponent::doRecovery (AiActor * actor) inline virtual
Reimplemented from AiStateComponent.
Definition at line 37 of file AlertStateComponent.h.
References server::zone::objects::creature::CreatureObject::activateHAMRegeneration(), server::zone::objects::creature::ai::AiActor::activatePostureRecovery(), server::zone::objects::creature::ai::AiActor::activateRecovery(), server::zone::objects::creature::ai::AiActor::getFollowObject(), server::zone::objects::creature::ai::AiActor::getHost(), and AiStateComponent::isScared().
uint16 AlertStateComponent::onEnter (AiActor * actor) inline virtual
Reimplemented from AiStateComponent.
Definition at line 18 of file AlertStateComponent.h.
References server::zone::objects::creature::ai::AiActor::activateMovementEvent(), server::zone::objects::creature::ai::AiActor::activateRecovery(), server::zone::objects::creature::ai::AiActor::getHost(), and server::zone::objects::scene::SceneObject::showFlyText().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/components/AlertStateComponent.h