Core3: server::zone::ZoneServer Class Reference
server::zone::ZoneServer Class Reference
#include <ZoneServer.h>
Public Member Functions
ZoneServer (ConfigManager *config)
void initializeTransientMembers ()
ZoneClientSession * createConnection (Socket *sock, SocketAddress &addr)
void initialize ()
void shutdown ()
void startManagers ()
void startZones ()
void stopManagers ()
void start (int p, int mconn=10)
void stop ()
void timedShutdown (int minutes)
void handleMessage (ZoneClientSession *client, Packet *message)
void processMessage (Message *message)
bool handleError (ZoneClientSession *client, Exception &e)
void addTotalSentPacket (int count)
void addTotalResentPacket (int count)
void printInfo ()
String getInfo ()
void printEvents ()
Reference< SceneObject * > getObject (unsigned long long objectID, bool doLock=true)
Reference< SceneObject * > createObject (unsigned int templateCRC, const String &dbname, int persistenceLevel=2)
Reference< SceneObject * > createObject (unsigned int templateCRC, int persistenceLevel=2, unsigned long long objectID=0)
Reference< SceneObject * > createClientObject (unsigned int templateCRC, unsigned long long objectID=0)
void updateObjectToDatabase (SceneObject *object)
void updateObjectToStaticDatabase (SceneObject *object)
void destroyObjectFromDatabase (unsigned long long objectID)
void lock (bool doLock=true)
void unlock (bool doLock=true)
void fixScheduler ()
void changeUserCap (int amount=50)
int getConnectionCount ()
void increaseOnlinePlayers ()
void decreaseOnlinePlayers ()
void increaseTotalDeletedPlayers ()
int getGalaxyID ()
String getGalaxyName ()
void setGalaxyName (const String &name)
bool isServerLocked ()
bool isServerOnline ()
bool isServerOffline ()
bool isServerLoading ()
int getServerCap ()
int getServerState ()
Zone * getZone (const String &terrainName)
Zone * getZone (int idx)
int getZoneCount ()
int getMaxPlayers ()
int getTotalPlayers ()
int getDeletedPlayers ()
ObjectManager * getObjectManager ()
PlayerManager * getPlayerManager ()
ChatManager * getChatManager ()
CityManager * getCityManager ()
ObjectController * getObjectController ()
MissionManager * getMissionManager ()
RadialManager * getRadialManager ()
GuildManager * getGuildManager ()
ResourceManager * getResourceManager ()
CraftingManager * getCraftingManager ()
LootManager * getLootManager ()
AuctionManager * getAuctionManager ()
SkillManager * getSkillManager ()
Time * getStartTimestamp ()
void setGalaxyID (int galaxyid)
void setServerState (int state)
void setServerStateLocked ()
void setServerStateOnline ()
void loadLoginMessage ()
void changeLoginMessage (const String &motd)
String getLoginMessage ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int OFFLINE = 0
static const int LOADING = 1
static const int ONLINE = 2
static const int LOCKED = 3
Protected Member Functions
ZoneServer (DummyConstructorParameter *param)
virtual ~ZoneServer ()
Friends
class ZoneServerHelper
Detailed Description
Definition at line 389 of file ZoneServer.h.
Constructor & Destructor Documentation
ZoneServer::ZoneServer (ConfigManager * config)
Definition at line 65 of file ZoneServer.cpp.
References server::zone::ZoneServerImplementation::_setStub().
ZoneServer::ZoneServer (DummyConstructorParameter * param) protected
Definition at line 72 of file ZoneServer.cpp.
ZoneServer::~ZoneServer () protected virtual
Definition at line 76 of file ZoneServer.cpp.
Member Function Documentation
DistributedObjectServant * ZoneServer::_getImplementation ()
Definition at line 983 of file ZoneServer.cpp.
Referenced by addTotalResentPacket(), addTotalSentPacket(), changeLoginMessage(), changeUserCap(), createClientObject(), createConnection(), createObject(), decreaseOnlinePlayers(), destroyObjectFromDatabase(), fixScheduler(), getAuctionManager(), getChatManager(), getCityManager(), getConnectionCount(), getCraftingManager(), getDeletedPlayers(), getGalaxyID(), getGalaxyName(), getGuildManager(), getInfo(), getLoginMessage(), getLootManager(), getMaxPlayers(), getMissionManager(), getObject(), getObjectController(), getObjectManager(), getPlayerManager(), getRadialManager(), getResourceManager(), getServerCap(), getServerState(), getSkillManager(), getStartTimestamp(), getTotalPlayers(), getZone(), getZoneCount(), handleError(), handleMessage(), increaseOnlinePlayers(), increaseTotalDeletedPlayers(), initialize(), initializeTransientMembers(), isServerLoading(), isServerLocked(), isServerOffline(), isServerOnline(), loadLoginMessage(), lock(), printEvents(), printInfo(), processMessage(), setGalaxyID(), setGalaxyName(), setServerState(), setServerStateLocked(), setServerStateOnline(), shutdown(), start(), startManagers(), startZones(), stop(), stopManagers(), timedShutdown(), unlock(), updateObjectToDatabase(), and updateObjectToStaticDatabase().
DistributedObjectServant * ZoneServer::_getImplementationForRead ()
Definition at line 989 of file ZoneServer.cpp.
void ZoneServer::_setImplementation (DistributedObjectServant * servant)
Definition at line 993 of file ZoneServer.cpp.
void ZoneServer::addTotalResentPacket (int count)
Definition at line 251 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::addTotalResentPacket(), and RPC_ADDTOTALRESENTPACKET__INT_.
Referenced by server::zone::ZoneClientSessionImplementation::closeConnection().
void ZoneServer::addTotalSentPacket (int count)
Definition at line 237 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::addTotalSentPacket(), and RPC_ADDTOTALSENTPACKET__INT_.
Referenced by server::zone::ZoneClientSessionImplementation::closeConnection().
void ZoneServer::changeLoginMessage (const String & motd)
Definition at line 954 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::changeLoginMessage(), and RPC_CHANGELOGINMESSAGE__STRING_.
void ZoneServer::changeUserCap (int amount = 50)
Definition at line 451 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::changeUserCap(), and RPC_CHANGEUSERCAP__INT_.
Referenced by ServerCore::handleCommands().
Reference< SceneObject * > ZoneServer::createClientObject (unsigned int templateCRC, unsigned long long objectID = 0)
Definition at line 353 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::createClientObject(), and RPC_CREATECLIENTOBJECT__INT_LONG_.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadSnapshotObject().
ZoneClientSession * ZoneServer::createConnection (Socket * sock, SocketAddress & addr)
Definition at line 94 of file ZoneServer.cpp.
References _getImplementation(), and server::zone::ZoneServerImplementation::createConnection().
Referenced by server::zone::ZoneHandler::createConnection().
Reference< SceneObject * > ZoneServer::createObject (unsigned int templateCRC, const String & dbname, int persistenceLevel = 2)
Definition at line 321 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::createObject(), and RPC_CREATEOBJECT__INT_STRING_INT_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addWaypoint(), server::zone::objects::building::BuildingObjectImplementation::createCellObjects(), server::zone::objects::installation::InstallationObjectImplementation::createChildObjects(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), server::zone::objects::scene::SceneObjectImplementation::createChildObjects(), server::zone::objects::tangible::TangibleObjectImplementation::createFactoryCrate(), ImageDesignManager::createHairObject(), server::zone::objects::tangible::loot::LootkitObjectImplementation::createItem(), server::zone::objects::draftschematic::DraftSchematicImplementation::createManufactureSchematic(), server::zone::managers::minigames::FishingManagerImplementation::createMarker(), server::zone::objects::resource::ResourceSpawnImplementation::createResource(), server::zone::managers::minigames::FishingManagerImplementation::createSplash(), server::zone::objects::mission::MissionObjectImplementation::createWaypoint(), ProneCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), server::zone::managers::minigames::FishingManagerImplementation::freeBait(), server::zone::managers::creature::DnaManager::generateSample(), server::zone::managers::director::DirectorManager::giveControlDevice(), server::zone::managers::director::DirectorManager::giveItem(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), ForceShrineMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData(), server::zone::objects::area::LairSpawnAreaImplementation::notifyObserverEvent(), server::zone::objects::building::BuildingObjectImplementation::spawnChildSceneObject(), server::zone::objects::area::DynamicSpawnAreaImplementation::spawnCreature(), server::zone::objects::area::StaticSpawnAreaImplementation::spawnCreatures(), server::zone::managers::director::DirectorManager::spawnSceneObject(), server::zone::managers::minigames::FishingManagerImplementation::success(), server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus(), and server::zone::objects::mission::DeliverMissionObjectiveImplementation::updateMissionStatus().
Reference< SceneObject * > ZoneServer::createObject (unsigned int templateCRC, int persistenceLevel = 2, unsigned long long objectID = 0)
Definition at line 337 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::createObject(), and RPC_CREATEOBJECT__INT_INT_LONG_.
void ZoneServer::decreaseOnlinePlayers ()
Definition at line 491 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::decreaseOnlinePlayers(), and RPC_DECREASEONLINEPLAYERS__.
Referenced by server::zone::ZoneClientSessionImplementation::setPlayer().
void ZoneServer::destroyObjectFromDatabase (unsigned long long objectID)
Definition at line 396 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::destroyObjectFromDatabase(), and RPC_DESTROYOBJECTFROMDATABASE__LONG_.
Referenced by server::zone::objects::scene::SceneObjectImplementation::destroyObjectFromDatabase(), and server::zone::objects::scene::SceneObjectImplementation::destroyPlayerCreatureFromDatabase().
void ZoneServer::fixScheduler ()
Definition at line 438 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::fixScheduler(), and RPC_FIXSCHEDULER__.
Referenced by ServerCore::handleCommands().
AuctionManager * ZoneServer::getAuctionManager ()
Definition at line 856 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getAuctionManager(), and RPC_GETAUCTIONMANAGER__.
Referenced by MarketCommand::executeCommand(), and IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage().
ChatManager * ZoneServer::getChatManager ()
Definition at line 739 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getChatManager(), and RPC_GETCHATMANAGER__.
Referenced by SetNameCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), ServerCore::handleCommands(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetReceivesDamage(), SelectCharacterCallback::run(), server::zone::packets::chat::ChatInstantMessageToCharacter::run(), server::zone::packets::chat::ChatRequestRoomListCallback::run(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailCondemned(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailDecay(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailMaintenanceWithdrawnFromBank(), server::zone::managers::auction::AuctionsMapImplementation::sendVendorUpdateMail(), server::zone::managers::director::DirectorManager::spatialChat(), server::zone::managers::director::DirectorManager::spatialMoodChat(), and server::zone::objects::player::PlayerObjectImplementation::unload().
CityManager * ZoneServer::getCityManager ()
Definition at line 752 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getCityManager(), and RPC_GETCITYMANAGER__.
Referenced by server::zone::objects::region::CityRegionImplementation::applySpecializationModifiers(), StructureManager::declareResidence(), CityHallZoneComponent::destroyObjectFromWorld(), CityReportCommand::executeCommand(), CityManagementMenuComponent::handleObjectMenuSelect(), CityVotingMenuComponent::handleObjectMenuSelect(), PlaceDecorationComponent::placeStructure(), and PlaceCityHallComponent::placeStructure().
int ZoneServer::getConnectionCount ()
Definition at line 465 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getConnectionCount(), and RPC_GETCONNECTIONCOUNT__.
Referenced by StatusServer::getStatusXMLPacket(), and SelectCharacterCallback::run().
CraftingManager * ZoneServer::getCraftingManager ()
Definition at line 830 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getCraftingManager(), and RPC_GETCRAFTINGMANAGER__.
Referenced by RequestDraftSlotsBatchCommand::doQueueCommand(), RequestResourceWeightsBatchCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), and server::zone::managers::creature::DnaManager::generateSample().
int ZoneServer::getDeletedPlayers ()
Definition at line 704 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getDeletedPlayers(), and RPC_GETDELETEDPLAYERS__.
Referenced by StatusServer::getStatusXMLPacket().
int ZoneServer::getGalaxyID ()
Definition at line 517 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getGalaxyID(), and RPC_GETGALAXYID__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::cleanupCharacters(), AddBannedPlayerCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), server::zone::managers::player::PlayerManagerImplementation::getCleanupCharacterCount(), DeleteCharactersTask::run(), and SelectCharacterCallback::run().
String ZoneServer::getGalaxyName ()
Definition at line 530 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getGalaxyName(), and RPC_GETGALAXYNAME__.
Referenced by FriendsListMessage::FriendsListMessage(), and StatusServer::getStatusXMLPacket().
GuildManager * ZoneServer::getGuildManager ()
Definition at line 804 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getGuildManager(), and RPC_GETGUILDMANAGER__.
Referenced by ListGuildsCommand::doQueueCommand(), and PermissionListModifyCommand::doQueueCommand().
String ZoneServer::getInfo ()
Definition at line 278 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getInfo(), and RPC_GETINFO__.
Referenced by ServerInfoCommand::executeCommand().
String ZoneServer::getLoginMessage ()
Definition at line 968 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getLoginMessage(), and RPC_GETLOGINMESSAGE__.
LootManager * ZoneServer::getLootManager ()
Definition at line 843 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getLootManager(), and RPC_GETLOOTMANAGER__.
Referenced by server::zone::managers::director::DirectorManager::createLoot(), server::zone::managers::director::DirectorManager::createLootFromCollection(), ObjectCommand::doQueueCommand(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveItems(), and ArtCrateMenuComponent::handleObjectMenuSelect().
int ZoneServer::getMaxPlayers ()
Definition at line 678 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getMaxPlayers(), and RPC_GETMAXPLAYERS__.
Referenced by StatusServer::getStatusXMLPacket().
MissionManager * ZoneServer::getMissionManager ()
Definition at line 778 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getMissionManager(), and RPC_GETMISSIONMANAGER__.
Referenced by server::zone::objects::mission::DeliverMissionObjectiveImplementation::activateWithResult(), server::zone::managers::visibility::VisibilityManager::addPlayerToBountyList(), server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::BountyHunterTargetTask(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::despawnNpcs(), CreateMissionElementCommand::doQueueCommand(), BountyHunterDroidMenuComponent::getBountyHunterMission(), BountyHunterDroidMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObjectImplementation::isInBountyMission(), BountyHunterDroidMenuComponent::playerOwnsTheDroid(), server::zone::objects::mission::MissionObjectiveImplementation::removeMissionFromPlayer(), server::zone::managers::visibility::VisibilityManager::removePlayerFromBountyList(), and server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::updatePosition().
Reference< SceneObject * > ZoneServer::getObject (unsigned long long objectID, bool doLock = true)
Definition at line 306 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getObject(), and RPC_GETOBJECT__LONG_BOOL_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addFriend(), server::zone::objects::mission::BountyMissionObjectiveImplementation::addPlayerTargetObservers(), server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership(), server::zone::managers::gcw::GCWManagerImplementation::canPlaceMoreBases(), server::zone::objects::installation::InstallationObjectImplementation::changeActiveResourceID(), CharacterSheetResponseMessage::CharacterSheetResponseMessage(), StructureManager::declareResidence(), server::zone::objects::installation::InstallationObjectImplementation::destroyObjectFromDatabase(), server::zone::objects::building::BuildingObjectImplementation::destroyObjectFromDatabase(), server::zone::objects::player::PlayerObjectImplementation::destroyObjectFromDatabase(), HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), FireHeavyWeaponCommand::doQueueCommand(), AdjustLotCountCommand::doQueueCommand(), SetNameCommand::doQueueCommand(), SniperShotCommand::doQueueCommand(), SynchronizedUiStopListeningCommand::doQueueCommand(), TauntCommand::doQueueCommand(), GrantZoningRightsCommand::doQueueCommand(), ThrowGrenadeCommand::doQueueCommand(), CitypardonCommand::doQueueCommand(), Intimidate1Command::doQueueCommand(), Intimidate2Command::doQueueCommand(), KillCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), LootCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), RequestBiographyCommand::doQueueCommand(), ResourceContainerTransferCommand::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), ForceWeaken1Command::doQueueCommand(), SynchronizedUiListenCommand::doQueueCommand(), ForceWeaken2Command::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), Warcry1Command::doQueueCommand(), Warcry2Command::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), CloseContainerCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), MountCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), ForceChokeCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), GetAttributesBatchCommand::doQueueCommand(), TeachCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), ApplyPowerupCommand::doQueueCommand(), HarvesterDeactivateCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), CitybanCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), ServerDestroyObjectCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), SetFactionCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), HarvesterActivateCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), HarvesterDiscardHopperCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), MakeLeaderCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), InviteCommand::doQueueCommand(), GiveItemCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), TipCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), PlayerInfoCommand::executeCommand(), MinefieldMenuComponent::fillObjectMenuResponse(), FireHeavyWeaponCommand::getCommandDuration(), ThrowGrenadeCommand::getCommandDuration(), server::zone::managers::director::DirectorManager::getCreatureObject(), server::zone::managers::player::PlayerManagerImplementation::getInRangeStructureWithAdminRights(), server::zone::objects::player::sessions::EntertainingSessionImplementation::getInstrument(), server::zone::objects::player::PlayerObjectImplementation::getLotsRemaining(), server::zone::objects::structure::StructureObjectImplementation::getOwnerCreatureObject(), server::zone::managers::director::DirectorManager::getSceneObject(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::getTargetLevel(), server::zone::objects::mission::BountyMissionObjectiveImplementation::getTargetPosition(), server::zone::objects::mission::BountyMissionObjectiveImplementation::getTargetZoneName(), ValidatedPosition::getWorldPosition(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::handleObjectMenuSelect(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handlePlayerKilled(), GroupManager::joinGroup(), StructureManager::loadPlayerStructures(), server::zone::managers::planet::PlanetManagerImplementation::loadSnapshotObject(), MinefieldZoneComponent::notifyInsertToZone(), TurretZoneComponent::notifyInsertToZone(), server::zone::managers::gcw::GCWManagerImplementation::notifyInstallationDestruction(), server::zone::objects::region::CityRegionImplementation::notifyLoadFromDatabase(), server::zone::managers::gcw::GCWManagerImplementation::performDefenseDontation(), PlaceCityHallComponent::placeStructure(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), StructureManager::redeedStructure(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), server::zone::managers::gcw::GCWManagerImplementation::removeDefense(), server::zone::objects::player::PlayerObjectImplementation::removeFriend(), server::zone::objects::mission::BountyMissionObjectiveImplementation::removePlayerTargetObservers(), StructureManager::reportStructureStatus(), DeleteCharactersTask::run(), UpdateWarStatusTask::run(), SelectCharacterCallback::run(), server::zone::managers::gcw::GCWManagerImplementation::sendBaseDefenseStatus(), server::zone::managers::gcw::GCWManagerImplementation::sendTurretAttackListTo(), server::zone::managers::auction::AuctionsMapImplementation::sendVendorUpdateMail(), server::zone::objects::creature::aigroup::AiGroupImplementation::setup(), server::zone::objects::building::BuildingObjectImplementation::spawnChildSceneObject(), server::zone::managers::director::DirectorManager::spawnSceneObject(), ZoneComponent::switchZone(), ZoneComponent::teleport(), server::zone::objects::region::CityRegionImplementation::transferCivicStructuresToMayor(), and server::zone::objects::player::PlayerObjectImplementation::updateBountyPvpStatus().
ObjectController * ZoneServer::getObjectController ()
Definition at line 765 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getObjectController(), and RPC_GETOBJECTCONTROLLER__.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::activateImmediateAction(), server::zone::objects::creature::CreatureObjectImplementation::activateQueueAction(), MountCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), server::zone::objects::creature::CreatureObjectImplementation::enqueueCommand(), server::zone::objects::creature::CreatureObjectImplementation::executeObjectControllerAction(), and DataTransformWithParentCallback::updatePosition().
ObjectManager * ZoneServer::getObjectManager ()
Definition at line 717 of file ZoneServer.cpp.
References _getImplementation(), and server::zone::ZoneServerImplementation::getObjectManager().
PlayerManager * ZoneServer::getPlayerManager ()
Definition at line 726 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getPlayerManager(), and RPC_GETPLAYERMANAGER__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::awardBadge(), server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::gcw::GCWManagerImplementation::awardSlicingXP(), DotPackCommand::awardXp(), HealStateCommand::awardXp(), HealWoundCommand::awardXp(), TendCommand::awardXp(), CurePackCommand::awardXp(), RevivePlayerCommand::awardXp(), HealEnhanceCommand::awardXp(), HealDamageCommand::awardXp(), PlayerContainerComponent::canAddObject(), CombatManager::doAreaCombatAction(), HealDamageCommand::doAreaMedicActionTarget(), SetNameCommand::doQueueCommand(), CitypardonCommand::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), FreezePlayerCommand::doQueueCommand(), UnfreezePlayerCommand::doQueueCommand(), InsureCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), LootCommand::doQueueCommand(), MeditateCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), ActivateCloneCommand::doQueueCommand(), TeachCommand::doQueueCommand(), CitybanCommand::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TipCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation::enhanceCharacter(), PlayerInfoCommand::executeCommand(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::getTargetLevel(), ServerCore::handleCommands(), InsuranceTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::AiAgentImplementation::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObjectImplementation::handleObjectMenuSelect(), ServerCore::initialize(), server::zone::managers::creature::LairObserverImplementation::notifyDestruction(), server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::creature::CreatureObjectImplementation::notifyObjectDestructionObservers(), PlayerContainerComponent::notifyObjectInserted(), PlayerContainerComponent::notifyObjectRemoved(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), InsuranceAllConfirmSuiCallback::run(), SelectCharacterCallback::run(), server::zone::ZoneClientSessionImplementation::setPlayer(), server::zone::managers::minigames::FishingManagerImplementation::success(), and server::zone::managers::skill::SkillManager::surrenderSkill().
RadialManager * ZoneServer::getRadialManager ()
Definition at line 791 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getRadialManager(), and RPC_GETRADIALMANAGER__.
ResourceManager * ZoneServer::getResourceManager ()
Definition at line 817 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getResourceManager(), and RPC_GETRESOURCEMANAGER__.
Referenced by ResourceCommand::despawnResource(), AddPowerCommand::doQueueCommand(), GmCreateClassResourceCommand::doQueueCommand(), GmCreateSpecificResourceCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), ResourceCommand::dumpResources(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveResource(), server::zone::objects::installation::InstallationObjectImplementation::handleStructureAddEnergy(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), HarvesterObjectMessage7::HarvesterObjectMessage7(), ResourceCommand::healthCheck(), InstallationObjectMessage7::InstallationObjectMessage7(), ResourceCommand::listResourceInfo(), ResourceCommand::listResources(), InsertPowerSuiCallback::run(), and server::zone::managers::minigames::FishingManagerImplementation::success().
int ZoneServer::getServerCap ()
Definition at line 611 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getServerCap(), and RPC_GETSERVERCAP__.
Referenced by StatusServer::getStatusXMLPacket(), and SelectCharacterCallback::run().
int ZoneServer::getServerState ()
Definition at line 624 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getServerState(), and RPC_GETSERVERSTATE__.
SkillManager * ZoneServer::getSkillManager ()
Definition at line 869 of file ZoneServer.cpp.
References _getImplementation(), and server::zone::ZoneServerImplementation::getSkillManager().
Referenced by AbilityList::loadFromNames(), and server::zone::objects::player::PlayerObjectImplementation::removeSchematics().
Time * ZoneServer::getStartTimestamp ()
Definition at line 878 of file ZoneServer.cpp.
References _getImplementation(), and server::zone::ZoneServerImplementation::getStartTimestamp().
Referenced by StatusServer::getStatusXMLPacket().
int ZoneServer::getTotalPlayers ()
Definition at line 691 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getTotalPlayers(), and RPC_GETTOTALPLAYERS__.
Referenced by StatusServer::getStatusXMLPacket().
Zone * ZoneServer::getZone (const String & terrainName)
Definition at line 637 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getZone(), and RPC_GETZONE__STRING_.
Referenced by NewbieSelectStartingLocationCommand::doQueueCommand(), CreateCreatureCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), server::zone::managers::director::DirectorManager::getRegion(), ForceShrineMenuComponent::handleObjectMenuSelect(), server::zone::managers::director::DirectorManager::isZoneEnabled(), server::zone::objects::player::PlayerObjectImplementation::notifySceneReady(), server::zone::ZoneReference::parseFromBinaryStream(), SelectCharacterCallback::run(), server::zone::managers::director::DirectorManager::spawnMobile(), server::zone::managers::director::DirectorManager::spawnMobileRandom(), server::zone::managers::director::DirectorManager::spawnSceneObject(), server::zone::objects::mission::BountyMissionObjectiveImplementation::spawnTarget(), and ZoneComponent::switchZone().
Zone * ZoneServer::getZone (int idx)
Gets a note based on it's position in the zone map. NOTE: This idx is not to be considered consistent.
Parameters
idx The index in the map to get the zone.
Definition at line 651 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getZone(), and RPC_GETZONE__INT_.
int ZoneServer::getZoneCount ()
Definition at line 665 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::getZoneCount(), and RPC_GETZONECOUNT__.
Referenced by ForceShrineMenuComponent::handleObjectMenuSelect(), and server::zone::objects::player::PlayerObjectImplementation::notifySceneReady().
bool ZoneServer::handleError (ZoneClientSession * client, Exception & e)
Definition at line 228 of file ZoneServer.cpp.
References _getImplementation(), and server::zone::ZoneServerImplementation::handleError().
Referenced by server::zone::ZoneHandler::handleError().
void ZoneServer::handleMessage (ZoneClientSession * client, Packet * message)
Definition at line 210 of file ZoneServer.cpp.
References _getImplementation(), and server::zone::ZoneServerImplementation::handleMessage().
Referenced by server::zone::ZoneHandler::handleMessage().
void ZoneServer::increaseOnlinePlayers ()
Definition at line 478 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::increaseOnlinePlayers(), and RPC_INCREASEONLINEPLAYERS__.
Referenced by server::zone::ZoneClientSessionImplementation::setPlayer().
void ZoneServer::increaseTotalDeletedPlayers ()
Definition at line 504 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::increaseTotalDeletedPlayers(), and RPC_INCREASETOTALDELETEDPLAYERS__.
void ZoneServer::initialize ()
Definition at line 103 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::initialize(), and RPC_INITIALIZE__.
Referenced by server::zone::ZoneHandler::initialize().
void ZoneServer::initializeTransientMembers ()
Definition at line 81 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
bool ZoneServer::isServerLoading ()
Definition at line 598 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::isServerLoading(), and RPC_ISSERVERLOADING__.
Referenced by server::zone::objects::scene::SceneObjectImplementation::broadcastDestroyPrivate(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessagePrivate(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessagesPrivate(), server::zone::objects::scene::SceneObjectImplementation::broadcastObjectPrivate(), server::zone::objects::player::PlayerObjectImplementation::notifySceneReady(), DestroyStructureTask::run(), SelectCharacterCallback::run(), server::zone::objects::structure::events::StructureMaintenanceTask::run(), and server::zone::objects::area::events::CampDespawnTask::run().
bool ZoneServer::isServerLocked ()
Definition at line 559 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::isServerLocked(), and RPC_ISSERVERLOCKED__.
Referenced by SelectCharacterCallback::run().
bool ZoneServer::isServerOffline ()
Definition at line 585 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::isServerOffline(), and RPC_ISSERVEROFFLINE__.
bool ZoneServer::isServerOnline ()
Definition at line 572 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::isServerOnline(), and RPC_ISSERVERONLINE__.
void ZoneServer::loadLoginMessage ()
Definition at line 941 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::loadLoginMessage(), and RPC_LOADLOGINMESSAGE__.
void ZoneServer::lock (bool doLock = true)
Definition at line 410 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::lock(), and RPC_LOCK__BOOL_.
void ZoneServer::printEvents ()
Definition at line 293 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::printEvents(), and RPC_PRINTEVENTS__.
void ZoneServer::printInfo ()
Definition at line 265 of file ZoneServer.cpp.
References _getImplementation(), server::zone::ZoneServerImplementation::printInfo(), and RPC_PRINTINFO__.
Referenced by ServerCore::handleCommands().
void ZoneServer::processMessage (Message * message)
Definition at line 219 of file ZoneServer.cpp.
References _getImplementation(), and server::zone::ZoneServerImplementation::processMessage().
Referenced by server::zone::ZoneHandler::processMessage().
void ZoneServer::setGalaxyID (int galaxyid)
Definition at line 887 of file ZoneServer.cpp.
References _getImplementation(), RPC_SETGALAXYID__INT_, and server::zone::ZoneServerImplementation::setGalaxyID().
void ZoneServer::setGalaxyName (const String & name)
Definition at line 545 of file ZoneServer.cpp.
References _getImplementation(), RPC_SETGALAXYNAME__STRING_, and server::zone::ZoneServerImplementation::setGalaxyName().
void ZoneServer::setServerState (int state)
Definition at line 901 of file ZoneServer.cpp.
References _getImplementation(), RPC_SETSERVERSTATE__INT_, and server::zone::ZoneServerImplementation::setServerState().
void ZoneServer::setServerStateLocked ()
Definition at line 915 of file ZoneServer.cpp.
References _getImplementation(), RPC_SETSERVERSTATELOCKED__, and server::zone::ZoneServerImplementation::setServerStateLocked().
Referenced by ServerCore::handleCommands().
void ZoneServer::setServerStateOnline ()
Definition at line 928 of file ZoneServer.cpp.
References _getImplementation(), RPC_SETSERVERSTATEONLINE__, and server::zone::ZoneServerImplementation::setServerStateOnline().
Referenced by ServerCore::handleCommands().
void ZoneServer::shutdown ()
Definition at line 116 of file ZoneServer.cpp.
References _getImplementation(), RPC_SHUTDOWN__, and server::zone::ZoneServerImplementation::shutdown().
void ZoneServer::start (int p, int mconn = 10)
Definition at line 168 of file ZoneServer.cpp.
References _getImplementation(), RPC_START__INT_INT_, and server::zone::ZoneServerImplementation::start().
Referenced by ServerCore::initialize().
void ZoneServer::startManagers ()
Definition at line 129 of file ZoneServer.cpp.
References _getImplementation(), RPC_STARTMANAGERS__, and server::zone::ZoneServerImplementation::startManagers().
void ZoneServer::startZones ()
Definition at line 142 of file ZoneServer.cpp.
References _getImplementation(), RPC_STARTZONES__, and server::zone::ZoneServerImplementation::startZones().
void ZoneServer::stop ()
Definition at line 183 of file ZoneServer.cpp.
References _getImplementation(), RPC_STOP__, and server::zone::ZoneServerImplementation::stop().
Referenced by ServerCore::shutdown().
void ZoneServer::stopManagers ()
Definition at line 155 of file ZoneServer.cpp.
References _getImplementation(), RPC_STOPMANAGERS__, and server::zone::ZoneServerImplementation::stopManagers().
void ZoneServer::timedShutdown (int minutes)
Definition at line 196 of file ZoneServer.cpp.
References _getImplementation(), RPC_TIMEDSHUTDOWN__INT_, and server::zone::ZoneServerImplementation::timedShutdown().
Referenced by ServerCore::handleCommands().
void ZoneServer::unlock (bool doLock = true)
Definition at line 424 of file ZoneServer.cpp.
References _getImplementation(), RPC_UNLOCK__BOOL_, and server::zone::ZoneServerImplementation::unlock().
void ZoneServer::updateObjectToDatabase (SceneObject * object)
Definition at line 368 of file ZoneServer.cpp.
References _getImplementation(), RPC_UPDATEOBJECTTODATABASE__SCENEOBJECT_, and server::zone::ZoneServerImplementation::updateObjectToDatabase().
void ZoneServer::updateObjectToStaticDatabase (SceneObject * object)
Definition at line 382 of file ZoneServer.cpp.
References _getImplementation(), RPC_UPDATEOBJECTTOSTATICDATABASE__SCENEOBJECT_, and server::zone::ZoneServerImplementation::updateObjectToStaticDatabase().
Friends And Related Function Documentation
friend class ZoneServerHelper friend
Definition at line 554 of file ZoneServer.h.
Member Data Documentation
const int server::zone::ZoneServer::LOADING = 1 static
Definition at line 393 of file ZoneServer.h.
const int server::zone::ZoneServer::LOCKED = 3 static
Definition at line 397 of file ZoneServer.h.
const int server::zone::ZoneServer::OFFLINE = 0 static
Definition at line 391 of file ZoneServer.h.
const int server::zone::ZoneServer::ONLINE = 2 static
Definition at line 395 of file ZoneServer.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneServer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneServer.cpp