Core3: server::chat::ChatMessage Class Reference
server::chat::ChatMessage Class Reference
#include <ChatMessage.h>
Public Member Functions
ChatMessage ()
void setString (const String &msg)
String toString ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ChatMessage (DummyConstructorParameter *param)
virtual ~ChatMessage ()
Friends
class ChatMessageHelper
Detailed Description
Definition at line 47 of file ChatMessage.h.
Constructor & Destructor Documentation
ChatMessage::ChatMessage ()
Definition at line 15 of file ChatMessage.cpp.
References server::chat::ChatMessageImplementation::_setStub().
ChatMessage::ChatMessage (DummyConstructorParameter * param) protected
Definition at line 22 of file ChatMessage.cpp.
ChatMessage::~ChatMessage () protected virtual
Definition at line 26 of file ChatMessage.cpp.
Member Function Documentation
DistributedObjectServant * ChatMessage::_getImplementation ()
Definition at line 60 of file ChatMessage.cpp.
Referenced by setString(), and toString().
DistributedObjectServant * ChatMessage::_getImplementationForRead ()
Definition at line 66 of file ChatMessage.cpp.
void ChatMessage::_setImplementation (DistributedObjectServant * servant)
Definition at line 70 of file ChatMessage.cpp.
void ChatMessage::setString (const String & msg)
Definition at line 31 of file ChatMessage.cpp.
References _getImplementation(), RPC_SETSTRING__STRING_, and server::chat::ChatMessageImplementation::setString().
String ChatMessage::toString ()
Definition at line 45 of file ChatMessage.cpp.
References _getImplementation(), RPC_TOSTRING__, and server::chat::ChatMessageImplementation::toString().
Referenced by server::zone::managers::director::DirectorManager::getChatMessage().
Friends And Related Function Documentation
friend class ChatMessageHelper friend
Definition at line 65 of file ChatMessage.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatMessage.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatMessage.cpp