Core3: server::zone::objects::creature::buffs::SpiceBuffImplementation Class Reference
server::zone::objects::creature::buffs::SpiceBuffImplementation Class Reference
#include <SpiceBuff.h>
Public Member Functions
SpiceBuffImplementation (CreatureObject *creo, const String &name, unsigned int buffCRC, int duration)
SpiceBuffImplementation (DummyConstructorParameter *param)
void activate (bool applyModifiers)
void deactivate (bool removeModifiers)
void setDownerAttributes (CreatureObject *creature, Buff *buff)
operator const SpiceBuff * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
BuffImplementation (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype)
BuffImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
virtual void sendTo (CreatureObject *player)
virtual void sendDestroyTo (CreatureObject *player)
virtual void activate ()
virtual void deactivate ()
VectorMap< String, int > * getSkillModifiers ()
virtual void applyAttributeModifiers ()
virtual void applySkillModifiers ()
virtual void applyStates ()
virtual void removeAttributeModifiers ()
virtual void removeSkillModifiers ()
virtual void removeStates ()
virtual void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
virtual void parseAttributeModifierString (const String &modifierstring)
virtual void parseSkillModifierString (const String &modifierstring)
virtual String getAttributeModifierString ()
virtual String getSkillModifierString ()
virtual float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
VectorMap< byte, int > * getAttributeModifiers ()
virtual int getAttributeModifierValue (byte attribute)
virtual int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartMessage (StringIdChatParameter &start)
void setEndMessage (StringIdChatParameter &end)
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
operator const Buff * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< SpiceBuff * > _this
Public Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
WeakReference< Buff * > _this
Protected Member Functions
virtual ~SpiceBuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
virtual ~BuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class SpiceBuff
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
ManagedWeakReference
< CreatureObject * > creature
Reference< BuffDurationEvent * > buffEvent
VectorMap< byte, int > attributeModifiers
VectorMap< String, int > skillModifiers
Vector< unsigned long long > states
String buffName
float buffDuration
unsigned int buffCRC
int buffType
bool fillAttributesOnBuff
StringIdChatParameter startMessage
StringIdChatParameter endMessage
String startFlyFile
String startFlyAux
byte startFlyRed
byte startFlyGreen
byte startFlyBlue
String endFlyFile
String endFlyAux
byte endFlyRed
byte endFlyGreen
byte endFlyBlue
Time nextExecutionTime
Detailed Description
Definition at line 135 of file SpiceBuff.h.
Constructor & Destructor Documentation
SpiceBuffImplementation::SpiceBuffImplementation (CreatureObject * creo, const String & name, unsigned int buffCRC, int duration)
Definition at line 212 of file SpiceBuff.cpp.
References _initializeImplementation(), and server::zone::objects::creature::buffs::BuffImplementation::buffName.
SpiceBuffImplementation::SpiceBuffImplementation (DummyConstructorParameter * param)
Definition at line 98 of file SpiceBuff.cpp.
References _initializeImplementation().
SpiceBuffImplementation::~SpiceBuffImplementation () protected virtual
Definition at line 103 of file SpiceBuff.cpp.
Member Function Documentation
DistributedObjectStub * SpiceBuffImplementation::_getStub ()
Definition at line 123 of file SpiceBuff.cpp.
References _this.
void SpiceBuffImplementation::_initializeImplementation () protected
Definition at line 110 of file SpiceBuff.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SpiceBuffImplementation().
void SpiceBuffImplementation::_serializationHelperMethod () protected
Definition at line 159 of file SpiceBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void SpiceBuffImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 118 of file SpiceBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::buffs::SpiceBuff::SpiceBuff().
void SpiceBuffImplementation::activate (bool applyModifiers) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 220 of file SpiceBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::activate(), server::zone::objects::creature::buffs::BuffImplementation::buffName, and server::zone::objects::creature::buffs::BuffImplementation::creature.
Referenced by server::zone::objects::creature::buffs::SpiceBuff::activate().
void SpiceBuffImplementation::deactivate (bool removeModifiers) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 13 of file SpiceBuffImplementation.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::buffName, server::zone::objects::creature::buffs::BuffImplementation::creature, server::zone::objects::creature::buffs::BuffImplementation::deactivate(), and setDownerAttributes().
Referenced by server::zone::objects::creature::buffs::SpiceBuff::deactivate().
void SpiceBuffImplementation::finalize () protected
Definition at line 107 of file SpiceBuff.cpp.
void SpiceBuffImplementation::lock (bool doLock = true) protected
Definition at line 131 of file SpiceBuff.cpp.
References _this.
void SpiceBuffImplementation::lock (ManagedObject * obj) protected
Definition at line 135 of file SpiceBuff.cpp.
References _this.
SpiceBuffImplementation::operator const SpiceBuff * ()
Definition at line 127 of file SpiceBuff.cpp.
void SpiceBuffImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 166 of file SpiceBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::initializeTransientMembers(), and readObjectMember().
bool SpiceBuffImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 185 of file SpiceBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::readObjectMember().
Referenced by readObject().
void SpiceBuffImplementation::rlock (bool doLock = true) protected
Definition at line 139 of file SpiceBuff.cpp.
References _this.
void SpiceBuffImplementation::runlock (bool doLock = true) protected
Definition at line 155 of file SpiceBuff.cpp.
References _this.
void SpiceBuffImplementation::setDownerAttributes (CreatureObject * creature, Buff * buff)
Definition at line 31 of file SpiceBuffImplementation.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::attributeModifiers, server::zone::objects::creature::CreatureObject::getMaxHAM(), server::zone::objects::creature::CreatureObject::getWounds(), and server::zone::objects::creature::buffs::Buff::setAttributeModifier().
Referenced by deactivate(), and server::zone::objects::creature::buffs::SpiceBuff::setDownerAttributes().
void SpiceBuffImplementation::unlock (bool doLock = true) protected
Definition at line 151 of file SpiceBuff.cpp.
References _this.
void SpiceBuffImplementation::wlock (bool doLock = true) protected
Definition at line 143 of file SpiceBuff.cpp.
References _this.
void SpiceBuffImplementation::wlock (ManagedObject * obj) protected
Definition at line 147 of file SpiceBuff.cpp.
References _this.
void SpiceBuffImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 195 of file SpiceBuff.cpp.
References writeObjectMembers().
int SpiceBuffImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 202 of file SpiceBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class SpiceBuff friend
Definition at line 182 of file SpiceBuff.h.
Member Data Documentation
WeakReference<SpiceBuff*> server::zone::objects::creature::buffs::SpiceBuffImplementation::_this
Definition at line 148 of file SpiceBuff.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SpiceBuff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SpiceBuff.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SpiceBuffImplementation.cpp