Core3: server::zone::managers::planet::PlanetManagerAdapter Class Reference
server::zone::managers::planet::PlanetManagerAdapter Class Reference
#include <PlanetManager.h>
Public Member Functions
PlanetManagerAdapter (PlanetManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void finalize ()
void initialize ()
void loadClientRegions ()
void loadClientPoiData ()
void loadBadgeAreas ()
void loadPerformanceLocations ()
bool isBuildingPermittedAt (float x, float y, SceneObject *objectTryingToBuild)
bool isCampingPermittedAt (float x, float y, float margin)
Reference< SceneObject * > findObjectTooCloseToDecoration (float x, float y, float margin)
bool isInRangeWithPoi (float x, float y, float range)
bool isInObjectsNoBuildZone (float x, float y, float extraMargin)
int getTravelFare (const String &departurePlanet, const String &arrivalPlanet)
void sendPlanetTravelPointListResponse (CreatureObject *player)
Reference< SceneObject * > createTicket (const String &departurePoint, const String &arrivalPlanet, const String &arrivalPoint)
bool validateRegionName (const String &name)
bool validateClientCityInRange (CreatureObject *creatureObject, float x, float y)
WeatherManager * getWeatherManager ()
int getRegionCount ()
int getNumberOfCities ()
void increaseNumberOfCities ()
CityRegion * getRegion (int index)
CityRegion * getRegion (const String &region)
CityRegion * getRegionAt (float x, float y)
void addRegion (CityRegion *region)
void dropRegion (const String &region)
bool hasRegion (const String &name)
void addPerformanceLocation (SceneObject *obj)
bool isExistingPlanetTravelPoint (const String &pointName)
bool isInterplanetaryTravelAllowed (const String &pointName)
bool isIncomingTravelAllowed (const String &pointName)
bool isTravelToLocationPermitted (const String &destinationPoint, const String &arrivalPlanet, const String &arrivalPoint)
void scheduleShuttle (CreatureObject *shuttle, int shuttleType)
void removeShuttle (CreatureObject *shuttle)
bool checkShuttleStatus (CreatureObject *creature, CreatureObject *shuttle)
bool isInWater (float x, float y)
void removePlayerCityTravelPoint (const String &cityName)
Detailed Description
Definition at line 612 of file PlanetManager.h.
Constructor & Destructor Documentation
PlanetManagerAdapter::PlanetManagerAdapter (PlanetManager * impl)
Definition at line 1060 of file PlanetManager.cpp.
Member Function Documentation
void PlanetManagerAdapter::addPerformanceLocation (SceneObject * obj)
Definition at line 1376 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::addRegion (CityRegion * region)
Definition at line 1364 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::checkShuttleStatus (CreatureObject * creature, CreatureObject * shuttle)
Definition at line 1404 of file PlanetManager.cpp.
Referenced by invokeMethod().
Reference< SceneObject * > PlanetManagerAdapter::createTicket (const String & departurePoint, const String & arrivalPlanet, const String & arrivalPoint)
Definition at line 1324 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::dropRegion (const String & region)
Definition at line 1368 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::finalize ()
Definition at line 1272 of file PlanetManager.cpp.
Referenced by invokeMethod().
Reference< SceneObject * > PlanetManagerAdapter::findObjectTooCloseToDecoration (float x, float y, float margin)
Definition at line 1304 of file PlanetManager.cpp.
Referenced by invokeMethod().
int PlanetManagerAdapter::getNumberOfCities ()
Definition at line 1344 of file PlanetManager.cpp.
Referenced by invokeMethod().
CityRegion * PlanetManagerAdapter::getRegion (int index)
Definition at line 1352 of file PlanetManager.cpp.
References server::zone::objects::region::CityRegion::getRegion().
Referenced by invokeMethod().
CityRegion * PlanetManagerAdapter::getRegion (const String & region)
Definition at line 1356 of file PlanetManager.cpp.
References server::zone::objects::region::CityRegion::getRegion().
CityRegion * PlanetManagerAdapter::getRegionAt (float x, float y)
Definition at line 1360 of file PlanetManager.cpp.
Referenced by invokeMethod().
int PlanetManagerAdapter::getRegionCount ()
Definition at line 1340 of file PlanetManager.cpp.
Referenced by invokeMethod().
int PlanetManagerAdapter::getTravelFare (const String & departurePlanet, const String & arrivalPlanet)
Definition at line 1316 of file PlanetManager.cpp.
Referenced by invokeMethod().
WeatherManager * PlanetManagerAdapter::getWeatherManager ()
Definition at line 1336 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::hasRegion (const String & name)
Definition at line 1372 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::increaseNumberOfCities ()
Definition at line 1348 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::initialize ()
Definition at line 1276 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::initializeTransientMembers ()
Definition at line 1268 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1063 of file PlanetManager.cpp.
References addPerformanceLocation(), addRegion(), checkShuttleStatus(), createTicket(), dropRegion(), finalize(), findObjectTooCloseToDecoration(), getNumberOfCities(), getRegion(), getRegionAt(), getRegionCount(), getTravelFare(), getWeatherManager(), hasRegion(), increaseNumberOfCities(), initialize(), initializeTransientMembers(), isBuildingPermittedAt(), isCampingPermittedAt(), isExistingPlanetTravelPoint(), isIncomingTravelAllowed(), isInObjectsNoBuildZone(), isInRangeWithPoi(), isInterplanetaryTravelAllowed(), isInWater(), isTravelToLocationPermitted(), loadBadgeAreas(), loadClientPoiData(), loadClientRegions(), loadPerformanceLocations(), removePlayerCityTravelPoint(), removeShuttle(), RPC_ADDPERFORMANCELOCATION__SCENEOBJECT_, RPC_ADDREGION__CITYREGION_, RPC_CHECKSHUTTLESTATUS__CREATUREOBJECT_CREATUREOBJECT_, RPC_CREATETICKET__STRING_STRING_STRING_, RPC_DROPREGION__STRING_, RPC_FINALIZE__, RPC_FINDOBJECTTOOCLOSETODECORATION__FLOAT_FLOAT_FLOAT_, RPC_GETNUMBEROFCITIES__, RPC_GETREGION__INT_, RPC_GETREGION__STRING_, RPC_GETREGIONAT__FLOAT_FLOAT_, RPC_GETREGIONCOUNT__, RPC_GETTRAVELFARE__STRING_STRING_, RPC_GETWEATHERMANAGER__, RPC_HASREGION__STRING_, RPC_INCREASENUMBEROFCITIES__, RPC_INITIALIZE__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_ISBUILDINGPERMITTEDAT__FLOAT_FLOAT_SCENEOBJECT_, RPC_ISCAMPINGPERMITTEDAT__FLOAT_FLOAT_FLOAT_, RPC_ISEXISTINGPLANETTRAVELPOINT__STRING_, RPC_ISINCOMINGTRAVELALLOWED__STRING_, RPC_ISINOBJECTSNOBUILDZONE__FLOAT_FLOAT_FLOAT_, RPC_ISINRANGEWITHPOI__FLOAT_FLOAT_FLOAT_, RPC_ISINTERPLANETARYTRAVELALLOWED__STRING_, RPC_ISINWATER__FLOAT_FLOAT_, RPC_ISTRAVELTOLOCATIONPERMITTED__STRING_STRING_STRING_, RPC_LOADBADGEAREAS__, RPC_LOADCLIENTPOIDATA__, RPC_LOADCLIENTREGIONS__, RPC_LOADPERFORMANCELOCATIONS__, RPC_REMOVEPLAYERCITYTRAVELPOINT__STRING_, RPC_REMOVESHUTTLE__CREATUREOBJECT_, RPC_SCHEDULESHUTTLE__CREATUREOBJECT_INT_, RPC_SENDPLANETTRAVELPOINTLISTRESPONSE__CREATUREOBJECT_, RPC_VALIDATECLIENTCITYINRANGE__CREATUREOBJECT_FLOAT_FLOAT_, RPC_VALIDATEREGIONNAME__STRING_, scheduleShuttle(), sendPlanetTravelPointListResponse(), validateClientCityInRange(), and validateRegionName().
bool PlanetManagerAdapter::isBuildingPermittedAt (float x, float y, SceneObject * objectTryingToBuild)
Definition at line 1296 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::isCampingPermittedAt (float x, float y, float margin)
Definition at line 1300 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::isExistingPlanetTravelPoint (const String & pointName)
Definition at line 1380 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::isIncomingTravelAllowed (const String & pointName)
Definition at line 1388 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::isInObjectsNoBuildZone (float x, float y, float extraMargin)
Definition at line 1312 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::isInRangeWithPoi (float x, float y, float range)
Definition at line 1308 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::isInterplanetaryTravelAllowed (const String & pointName)
Definition at line 1384 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::isInWater (float x, float y)
Definition at line 1408 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::isTravelToLocationPermitted (const String & destinationPoint, const String & arrivalPlanet, const String & arrivalPoint)
Definition at line 1392 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::loadBadgeAreas ()
Definition at line 1288 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::loadClientPoiData ()
Definition at line 1284 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::loadClientRegions ()
Definition at line 1280 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::loadPerformanceLocations ()
Definition at line 1292 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::removePlayerCityTravelPoint (const String & cityName)
Definition at line 1412 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::removeShuttle (CreatureObject * shuttle)
Definition at line 1400 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::scheduleShuttle (CreatureObject * shuttle, int shuttleType)
Definition at line 1396 of file PlanetManager.cpp.
Referenced by invokeMethod().
void PlanetManagerAdapter::sendPlanetTravelPointListResponse (CreatureObject * player)
Definition at line 1320 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::validateClientCityInRange (CreatureObject * creatureObject, float x, float y)
Definition at line 1332 of file PlanetManager.cpp.
Referenced by invokeMethod().
bool PlanetManagerAdapter::validateRegionName (const String & name)
Definition at line 1328 of file PlanetManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/PlanetManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/PlanetManager.cpp