Core3: server::zone::managers::mission::MissionManager Class Reference
server::zone::managers::mission::MissionManager Class Reference
#include <MissionManager.h>
Public Member Functions
MissionManager (ZoneServer *srv, ZoneProcessServer *impl)
void loadLuaSettings ()
void handleMissionListRequest (MissionTerminal *missionTerminal, CreatureObject *player, int counter)
void handleMissionAccept (MissionTerminal *missionTerminal, MissionObject *mission, CreatureObject *player)
void handleMissionAbort (MissionObject *mission, CreatureObject *player)
void removeMission (MissionObject *mission, CreatureObject *player)
void populateMissionList (MissionTerminal *missionTerminal, CreatureObject *player, int counter)
bool randomGenericDeliverMission (CreatureObject *player, MissionObject *mission, bool inTownMission, const int faction)
void randomizeGenericBountyMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericCraftingMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericDeliverMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericDestroyMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericEntertainerMission (CreatureObject *player, MissionObject *mission, const int faction, const int missionType)
void randomizeGenericHuntingMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericReconMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericSurveyMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeSurveyMission (CreatureObject *player, MissionObject *mission)
void randomizeDestroyMission (CreatureObject *player, MissionObject *mission)
void randomizeBountyMission (CreatureObject *player, MissionObject *mission)
void randomizeDeliverMission (CreatureObject *player, MissionObject *mission)
void randomizeCraftingMission (CreatureObject *player, MissionObject *mission)
void randomizeHuntingMission (CreatureObject *player, MissionObject *mission)
void randomizeReconMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialDestroyMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialDeliverMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialCraftingMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialReconMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelDestroyMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelDeliverMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelCraftingMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelReconMission (CreatureObject *player, MissionObject *mission)
void createMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createSurveyMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createDestroyMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createDeliverMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createEntertainerMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createHuntingMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createReconMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createBountyMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createCraftingMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
NpcSpawnPoint * getRandomFreeNpcSpawnPoint (unsigned const int planetCRC, const float x, const float y, const int spawnType)
void createSpawnPoint (CreatureObject *player, const String &spawnTypes)
LairSpawn * getRandomLairSpawn (CreatureObject *player, const int faction, unsigned int type)
Vector3 getRandomBountyTargetPosition (CreatureObject *player)
Reference< MissionObject * > getBountyHunterMission (CreatureObject *player)
String getDeliveryMissionFileName (const int faction)
int getDeliverMissionNumberOfMissions (const int faction)
int getDeliverMissionSpawnType (const int faction)
void addPlayerToBountyList (unsigned long long targetId, int reward)
void removePlayerFromBountyList (unsigned long long targetId)
void updatePlayerBountyReward (unsigned long long targetId, int reward)
void addBountyHunterToPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
void removeBountyHunterFromPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
BountyTargetListElement * getRandomPlayerBounty (CreatureObject *player)
void completePlayerBounty (unsigned long long targetId, unsigned long long bountyHunter)
void failPlayerBountyMission (unsigned long long bountyHunter)
void allocateMissionNpcs (NpcSpawnPoint *target, NpcSpawnPoint *destination, TerrainManager *terrainManager, CreatureManager *creatureManager)
void freeMissionNpc (NpcSpawnPoint *npc)
void despawnMissionNpc (NpcSpawnPoint *npc)
void deactivateMissions (CreatureObject *player)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static unsigned const int UNKNOWN_TARGET = 0xB911DA26
Protected Member Functions
MissionManager (DummyConstructorParameter *param)
virtual ~MissionManager ()
Friends
class MissionManagerHelper
Detailed Description
Definition at line 171 of file MissionManager.h.
Constructor & Destructor Documentation
MissionManager::MissionManager (ZoneServer * srv, ZoneProcessServer * impl)
Definition at line 33 of file MissionManager.cpp.
References server::zone::managers::mission::MissionManagerImplementation::_setStub().
MissionManager::MissionManager (DummyConstructorParameter * param) protected
Definition at line 40 of file MissionManager.cpp.
MissionManager::~MissionManager () protected virtual
Definition at line 44 of file MissionManager.cpp.
Member Function Documentation
DistributedObjectServant * MissionManager::_getImplementation ()
Definition at line 931 of file MissionManager.cpp.
Referenced by addBountyHunterToPlayerBounty(), addPlayerToBountyList(), allocateMissionNpcs(), completePlayerBounty(), createBountyMissionObjectives(), createCraftingMissionObjectives(), createDeliverMissionObjectives(), createDestroyMissionObjectives(), createEntertainerMissionObjectives(), createHuntingMissionObjectives(), createMissionObjectives(), createReconMissionObjectives(), createSpawnPoint(), createSurveyMissionObjectives(), deactivateMissions(), despawnMissionNpc(), failPlayerBountyMission(), freeMissionNpc(), getBountyHunterMission(), getDeliverMissionNumberOfMissions(), getDeliverMissionSpawnType(), getDeliveryMissionFileName(), getRandomBountyTargetPosition(), getRandomFreeNpcSpawnPoint(), getRandomLairSpawn(), getRandomPlayerBounty(), handleMissionAbort(), handleMissionAccept(), handleMissionListRequest(), loadLuaSettings(), populateMissionList(), randomGenericDeliverMission(), randomizeBountyMission(), randomizeCraftingMission(), randomizeDeliverMission(), randomizeDestroyMission(), randomizeGenericBountyMission(), randomizeGenericCraftingMission(), randomizeGenericDeliverMission(), randomizeGenericDestroyMission(), randomizeGenericEntertainerMission(), randomizeGenericHuntingMission(), randomizeGenericReconMission(), randomizeGenericSurveyMission(), randomizeHuntingMission(), randomizeImperialCraftingMission(), randomizeImperialDeliverMission(), randomizeImperialDestroyMission(), randomizeImperialReconMission(), randomizeRebelCraftingMission(), randomizeRebelDeliverMission(), randomizeRebelDestroyMission(), randomizeRebelReconMission(), randomizeReconMission(), randomizeSurveyMission(), removeBountyHunterFromPlayerBounty(), removeMission(), removePlayerFromBountyList(), and updatePlayerBountyReward().
DistributedObjectServant * MissionManager::_getImplementationForRead ()
Definition at line 937 of file MissionManager.cpp.
void MissionManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 941 of file MissionManager.cpp.
void MissionManager::addBountyHunterToPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
Definition at line 807 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::addBountyHunterToPlayerBounty(), and RPC_ADDBOUNTYHUNTERTOPLAYERBOUNTY__LONG_LONG_.
void MissionManager::addPlayerToBountyList (unsigned long long targetId, int reward)
Definition at line 763 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::addPlayerToBountyList(), and RPC_ADDPLAYERTOBOUNTYLIST__LONG_INT_.
Referenced by server::zone::managers::visibility::VisibilityManager::addPlayerToBountyList(), and BountyHunterDroidMenuComponent::handleObjectMenuSelect().
void MissionManager::allocateMissionNpcs (NpcSpawnPoint * target, NpcSpawnPoint * destination, TerrainManager * terrainManager, CreatureManager * creatureManager)
Definition at line 880 of file MissionManager.cpp.
References _getImplementation(), and server::zone::managers::mission::MissionManagerImplementation::allocateMissionNpcs().
Referenced by server::zone::objects::mission::DeliverMissionObjectiveImplementation::activateWithResult().
void MissionManager::completePlayerBounty (unsigned long long targetId, unsigned long long bountyHunter)
Definition at line 851 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::completePlayerBounty(), and RPC_COMPLETEPLAYERBOUNTY__LONG_LONG_.
void MissionManager::createBountyMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 623 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::createBountyMissionObjectives(), and RPC_CREATEBOUNTYMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_.
void MissionManager::createCraftingMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 639 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::createCraftingMissionObjectives(), and RPC_CREATECRAFTINGMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_.
void MissionManager::createDeliverMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 559 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::createDeliverMissionObjectives(), and RPC_CREATEDELIVERMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_.
void MissionManager::createDestroyMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 543 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::createDestroyMissionObjectives(), and RPC_CREATEDESTROYMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_.
void MissionManager::createEntertainerMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 575 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::createEntertainerMissionObjectives(), and RPC_CREATEENTERTAINERMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_.
void MissionManager::createHuntingMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 591 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::createHuntingMissionObjectives(), and RPC_CREATEHUNTINGMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_.
void MissionManager::createMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 511 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::createMissionObjectives(), and RPC_CREATEMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_.
void MissionManager::createReconMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 607 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::createReconMissionObjectives(), and RPC_CREATERECONMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_.
void MissionManager::createSpawnPoint (CreatureObject * player, const String & spawnTypes)
Definition at line 672 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::createSpawnPoint(), and RPC_CREATESPAWNPOINT__CREATUREOBJECT_STRING_.
Referenced by CreateMissionElementCommand::doQueueCommand().
void MissionManager::createSurveyMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 527 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::createSurveyMissionObjectives(), and RPC_CREATESURVEYMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_.
void MissionManager::deactivateMissions (CreatureObject * player)
Definition at line 917 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::deactivateMissions(), and RPC_DEACTIVATEMISSIONS__CREATUREOBJECT_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::unload().
void MissionManager::despawnMissionNpc (NpcSpawnPoint * npc)
Definition at line 903 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::despawnMissionNpc(), and RPC_DESPAWNMISSIONNPC__NPCSPAWNPOINT_.
void MissionManager::failPlayerBountyMission (unsigned long long bountyHunter)
Definition at line 866 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::failPlayerBountyMission(), and RPC_FAILPLAYERBOUNTYMISSION__LONG_.
void MissionManager::freeMissionNpc (NpcSpawnPoint * npc)
Definition at line 889 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::freeMissionNpc(), and RPC_FREEMISSIONNPC__NPCSPAWNPOINT_.
Referenced by server::zone::objects::mission::DeliverMissionObjectiveImplementation::despawnNpcs().
Reference< MissionObject * > MissionManager::getBountyHunterMission (CreatureObject * player)
Definition at line 705 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::getBountyHunterMission(), and RPC_GETBOUNTYHUNTERMISSION__CREATUREOBJECT_.
Referenced by BountyHunterDroidMenuComponent::getBountyHunterMission(), server::zone::objects::creature::CreatureObjectImplementation::isInBountyMission(), and BountyHunterDroidMenuComponent::playerOwnsTheDroid().
int MissionManager::getDeliverMissionNumberOfMissions (const int faction)
Definition at line 735 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::getDeliverMissionNumberOfMissions(), and RPC_GETDELIVERMISSIONNUMBEROFMISSIONS__INT_.
int MissionManager::getDeliverMissionSpawnType (const int faction)
Definition at line 749 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::getDeliverMissionSpawnType(), and RPC_GETDELIVERMISSIONSPAWNTYPE__INT_.
String MissionManager::getDeliveryMissionFileName (const int faction)
Definition at line 719 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::getDeliveryMissionFileName(), and RPC_GETDELIVERYMISSIONFILENAME__INT_.
Vector3 MissionManager::getRandomBountyTargetPosition (CreatureObject * player)
Definition at line 696 of file MissionManager.cpp.
References _getImplementation(), and server::zone::managers::mission::MissionManagerImplementation::getRandomBountyTargetPosition().
Referenced by server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::BountyHunterTargetTask(), and server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::updatePosition().
NpcSpawnPoint * MissionManager::getRandomFreeNpcSpawnPoint (unsigned const int planetCRC, const float x, const float y, const int spawnType)
Definition at line 655 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::getRandomFreeNpcSpawnPoint(), and RPC_GETRANDOMFREENPCSPAWNPOINT__INT_FLOAT_FLOAT_INT_.
Referenced by server::zone::objects::mission::DeliverMissionObjectiveImplementation::activateWithResult().
LairSpawn * MissionManager::getRandomLairSpawn (CreatureObject * player, const int faction, unsigned int type)
Definition at line 687 of file MissionManager.cpp.
References _getImplementation(), and server::zone::managers::mission::MissionManagerImplementation::getRandomLairSpawn().
BountyTargetListElement * MissionManager::getRandomPlayerBounty (CreatureObject * player)
Definition at line 837 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::getRandomPlayerBounty(), and RPC_GETRANDOMPLAYERBOUNTY__CREATUREOBJECT_.
void MissionManager::handleMissionAbort (MissionObject * mission, CreatureObject * player)
Definition at line 94 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAbort(), and RPC_HANDLEMISSIONABORT__MISSIONOBJECT_CREATUREOBJECT_.
void MissionManager::handleMissionAccept (MissionTerminal * missionTerminal, MissionObject * mission, CreatureObject * player)
Definition at line 78 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAccept(), and RPC_HANDLEMISSIONACCEPT__MISSIONTERMINAL_MISSIONOBJECT_CREATUREOBJECT_.
Referenced by MissionAcceptCallback::run().
void MissionManager::handleMissionListRequest (MissionTerminal * missionTerminal, CreatureObject * player, int counter)
Definition at line 62 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::handleMissionListRequest(), and RPC_HANDLEMISSIONLISTREQUEST__MISSIONTERMINAL_CREATUREOBJECT_INT_.
void MissionManager::loadLuaSettings ()
Definition at line 49 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::loadLuaSettings(), and RPC_LOADLUASETTINGS__.
void MissionManager::populateMissionList (MissionTerminal * missionTerminal, CreatureObject * player, int counter)
Definition at line 124 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::populateMissionList(), and RPC_POPULATEMISSIONLIST__MISSIONTERMINAL_CREATUREOBJECT_INT_.
bool MissionManager::randomGenericDeliverMission (CreatureObject * player, MissionObject * mission, bool inTownMission, const int faction)
Definition at line 140 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), and RPC_RANDOMGENERICDELIVERMISSION__CREATUREOBJECT_MISSIONOBJECT_BOOL_INT_.
void MissionManager::randomizeBountyMission (CreatureObject * player, MissionObject * mission)
Definition at line 316 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeBountyMission(), and RPC_RANDOMIZEBOUNTYMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeCraftingMission (CreatureObject * player, MissionObject * mission)
Definition at line 346 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeCraftingMission(), and RPC_RANDOMIZECRAFTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeDeliverMission (CreatureObject * player, MissionObject * mission)
Definition at line 331 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeDeliverMission(), and RPC_RANDOMIZEDELIVERMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeDestroyMission (CreatureObject * player, MissionObject * mission)
Definition at line 301 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeDestroyMission(), and RPC_RANDOMIZEDESTROYMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeGenericBountyMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 157 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), and RPC_RANDOMIZEGENERICBOUNTYMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_.
void MissionManager::randomizeGenericCraftingMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 173 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericCraftingMission(), and RPC_RANDOMIZEGENERICCRAFTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_.
void MissionManager::randomizeGenericDeliverMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 189 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDeliverMission(), and RPC_RANDOMIZEGENERICDELIVERMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_.
void MissionManager::randomizeGenericDestroyMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 205 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), and RPC_RANDOMIZEGENERICDESTROYMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_.
void MissionManager::randomizeGenericEntertainerMission (CreatureObject * player, MissionObject * mission, const int faction, const int missionType)
Definition at line 221 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), and RPC_RANDOMIZEGENERICENTERTAINERMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_INT_.
void MissionManager::randomizeGenericHuntingMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 238 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), and RPC_RANDOMIZEGENERICHUNTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_.
void MissionManager::randomizeGenericReconMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 254 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), and RPC_RANDOMIZEGENERICRECONMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_.
void MissionManager::randomizeGenericSurveyMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 270 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission(), and RPC_RANDOMIZEGENERICSURVEYMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_.
void MissionManager::randomizeHuntingMission (CreatureObject * player, MissionObject * mission)
Definition at line 361 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeHuntingMission(), and RPC_RANDOMIZEHUNTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeImperialCraftingMission (CreatureObject * player, MissionObject * mission)
Definition at line 421 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeImperialCraftingMission(), and RPC_RANDOMIZEIMPERIALCRAFTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeImperialDeliverMission (CreatureObject * player, MissionObject * mission)
Definition at line 406 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeImperialDeliverMission(), and RPC_RANDOMIZEIMPERIALDELIVERMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeImperialDestroyMission (CreatureObject * player, MissionObject * mission)
Definition at line 391 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeImperialDestroyMission(), and RPC_RANDOMIZEIMPERIALDESTROYMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeImperialReconMission (CreatureObject * player, MissionObject * mission)
Definition at line 436 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeImperialReconMission(), and RPC_RANDOMIZEIMPERIALRECONMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeRebelCraftingMission (CreatureObject * player, MissionObject * mission)
Definition at line 481 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeRebelCraftingMission(), and RPC_RANDOMIZEREBELCRAFTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeRebelDeliverMission (CreatureObject * player, MissionObject * mission)
Definition at line 466 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeRebelDeliverMission(), and RPC_RANDOMIZEREBELDELIVERMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeRebelDestroyMission (CreatureObject * player, MissionObject * mission)
Definition at line 451 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeRebelDestroyMission(), and RPC_RANDOMIZEREBELDESTROYMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeRebelReconMission (CreatureObject * player, MissionObject * mission)
Definition at line 496 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeRebelReconMission(), and RPC_RANDOMIZEREBELRECONMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeReconMission (CreatureObject * player, MissionObject * mission)
Definition at line 376 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeReconMission(), and RPC_RANDOMIZERECONMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::randomizeSurveyMission (CreatureObject * player, MissionObject * mission)
Definition at line 286 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomizeSurveyMission(), and RPC_RANDOMIZESURVEYMISSION__CREATUREOBJECT_MISSIONOBJECT_.
void MissionManager::removeBountyHunterFromPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
Definition at line 822 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::removeBountyHunterFromPlayerBounty(), and RPC_REMOVEBOUNTYHUNTERFROMPLAYERBOUNTY__LONG_LONG_.
void MissionManager::removeMission (MissionObject * mission, CreatureObject * player)
Definition at line 109 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::removeMission(), and RPC_REMOVEMISSION__MISSIONOBJECT_CREATUREOBJECT_.
Referenced by server::zone::objects::mission::MissionObjectiveImplementation::removeMissionFromPlayer().
void MissionManager::removePlayerFromBountyList (unsigned long long targetId)
Definition at line 778 of file MissionManager.cpp.
References _getImplementation(), server::zone::managers::mission::MissionManagerImplementation::removePlayerFromBountyList(), and RPC_REMOVEPLAYERFROMBOUNTYLIST__LONG_.
Referenced by server::zone::managers::visibility::VisibilityManager::removePlayerFromBountyList().
void MissionManager::updatePlayerBountyReward (unsigned long long targetId, int reward)
Definition at line 792 of file MissionManager.cpp.
References _getImplementation(), RPC_UPDATEPLAYERBOUNTYREWARD__LONG_INT_, and server::zone::managers::mission::MissionManagerImplementation::updatePlayerBountyReward().
Friends And Related Function Documentation
friend class MissionManagerHelper friend
Definition at line 305 of file MissionManager.h.
Member Data Documentation
unsigned const int server::zone::managers::mission::MissionManager::UNKNOWN_TARGET = 0xB911DA26 static
Definition at line 173 of file MissionManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/mission/MissionManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/mission/MissionManager.cpp