Core3: server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap Class Reference
server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap Class Reference
#include <MissionNpcSpawnMap.h>
Public Member Functions
MissionNpcSpawnMap ()
~MissionNpcSpawnMap ()
void loadSpawnPointsFromLua ()
NpcSpawnPoint * getRandomNpcSpawnPoint (const uint32 planetCRC, const Vector3 *position, const int spawnType, const float minDistance, const float maxDistance)
Vector3 * getRandomCityCoordinates (const uint32 planetCRC, const Vector3 *notCloseToPosition)
NpcSpawnPoint * addSpawnPoint (uint32 planetCRC, Reference< NpcSpawnPoint * > npc)
NpcSpawnPoint * findSpawnAt (uint32 planetCRC, Vector3 *position)
bool parseFromBinaryStream (ObjectInputStream *stream)
bool toBinaryStream (ObjectOutputStream *stream)
void saveSpawnPoints ()
Protected Attributes
UniverseSpawnMap spawnMap
Detailed Description
Class implementing methods to find a suitable spawn point for mission NPC's.
Definition at line 62 of file MissionNpcSpawnMap.h.
Constructor & Destructor Documentation
server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::MissionNpcSpawnMap () inline
Constructor.
Definition at line 73 of file MissionNpcSpawnMap.h.
server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::~MissionNpcSpawnMap () inline
Destructor.
Definition at line 78 of file MissionNpcSpawnMap.h.
Member Function Documentation
NpcSpawnPoint * MissionNpcSpawnMap::addSpawnPoint (uint32 planetCRC, Reference< NpcSpawnPoint * > npc)
Add a spawn point to the specified planet.
Parameters
planetCRC the CRC of the planet name.
npc the NPC to add.
Returns
the added NPC spawn point or the nearest existing spawn point if the new is within minimum distance.
Definition at line 96 of file MissionNpcSpawnMap.cpp.
References server::zone::managers::mission::spawnmaps::PlanetSpawnMap::addToClosestCity(), server::zone::managers::mission::spawnmaps::UniverseSpawnMap::getPlanet(), and spawnMap.
Referenced by server::zone::managers::mission::MissionManagerImplementation::createSpawnPoint().
NpcSpawnPoint * MissionNpcSpawnMap::findSpawnAt (uint32 planetCRC, Vector3 * position)
Finds a spawn point on a certain location.
Parameters
planetCRC the CRC of the planet name.
position the position to search.
Returns
the spawn point on the position or NULL if none exist.
Definition at line 106 of file MissionNpcSpawnMap.cpp.
References server::zone::managers::mission::spawnmaps::PlanetSpawnMap::findSpawnAt(), server::zone::managers::mission::spawnmaps::UniverseSpawnMap::getPlanet(), and spawnMap.
Referenced by server::zone::managers::mission::MissionManagerImplementation::createSpawnPoint().
Vector3 * MissionNpcSpawnMap::getRandomCityCoordinates (const uint32 planetCRC, const Vector3 * notCloseToPosition)
Get the center coordinates of a random city not close to the supplied coordinates.
Parameters
planetCRC the CRC of the name of the planet to find a city on.
notCloseToPosition the city closest to this position will not be returned unless it is the only city.
Returns
random city not close to the coordinates.
Definition at line 85 of file MissionNpcSpawnMap.cpp.
References server::zone::managers::mission::spawnmaps::CitySpawnMap::getCityCenter(), server::zone::managers::mission::spawnmaps::UniverseSpawnMap::getPlanet(), server::zone::managers::mission::spawnmaps::PlanetSpawnMap::getRandomCityNotCloseTo(), and spawnMap.
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission().
NpcSpawnPoint * MissionNpcSpawnMap::getRandomNpcSpawnPoint (const uint32 planetCRC, const Vector3 * position, const int spawnType, const float minDistance, const float maxDistance)
Find a random spawn point on the requested planet within the minimum and maximum distance from the supplied position of the requested spawn type.
Parameters
planetCRC the CRC of the name of the planet to find a spawn on.
position the position to measure distance from/to.
spawnType the spawn type bitmask required for the spawn.
minDistance the minimum distance between the spawn point and the position supplied.
minDistance the maximum distance between the spawn point and the position supplied.
Returns
random npc matching requirements or NULL if none could be found.
Definition at line 69 of file MissionNpcSpawnMap.cpp.
References server::zone::managers::mission::spawnmaps::PlanetSpawnMap::getClosestCity(), server::zone::managers::mission::spawnmaps::UniverseSpawnMap::getPlanet(), server::zone::managers::mission::spawnmaps::CitySpawnMap::getRandomNpcSpawnPoint(), and spawnMap.
Referenced by server::zone::managers::mission::MissionManagerImplementation::getRandomFreeNpcSpawnPoint(), and server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission().
void MissionNpcSpawnMap::loadSpawnPointsFromLua ()
Load all spawn points from the lua script file.
Definition at line 48 of file MissionNpcSpawnMap.cpp.
References server::zone::managers::mission::spawnmaps::UniverseSpawnMap::addCities(), server::zone::managers::mission::spawnmaps::UniverseSpawnMap::readObject(), and spawnMap.
bool server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::parseFromBinaryStream (ObjectInputStream * stream) inline
Read the object from a stream.
Parameters
stream stream to read from.
Returns
true if successful.
Definition at line 126 of file MissionNpcSpawnMap.h.
References server::zone::managers::mission::spawnmaps::UniverseSpawnMap::parseFromBinaryStream(), and spawnMap.
void MissionNpcSpawnMap::saveSpawnPoints ()
Save all spawn points to lua script.
Definition at line 116 of file MissionNpcSpawnMap.cpp.
References server::zone::managers::mission::spawnmaps::UniverseSpawnMap::saveSpawnPoints(), and spawnMap.
Referenced by server::zone::managers::mission::MissionManagerImplementation::createSpawnPoint().
bool server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::toBinaryStream (ObjectOutputStream * stream) inline
Write the object to a stream.
Parameters
stream stream to write to.
true if successful.
Definition at line 135 of file MissionNpcSpawnMap.h.
References spawnMap, and server::zone::managers::mission::spawnmaps::UniverseSpawnMap::toBinaryStream().
Member Data Documentation
UniverseSpawnMap server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::spawnMap protected
Spawn points in the world.
Definition at line 67 of file MissionNpcSpawnMap.h.
Referenced by addSpawnPoint(), findSpawnAt(), getRandomCityCoordinates(), getRandomNpcSpawnPoint(), loadSpawnPointsFromLua(), parseFromBinaryStream(), saveSpawnPoints(), and toBinaryStream().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/mission/spawnmaps/MissionNpcSpawnMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/mission/spawnmaps/MissionNpcSpawnMap.cpp