Core3: CreatureAttackData Class Reference
CreatureAttackData Class Reference
#include <CreatureAttackData.h>
Public Member Functions
CreatureAttackData (const UnicodeString &dataString, CombatQueueCommand *base)
CreatureAttackData (const CreatureAttackData &data)
virtual ~CreatureAttackData ()
void fillFromBase ()
void setVariable (const String &var, const String &val)
String getCommandName () const
uint32 getCommandCRC () const
float getActionDamageMultiplier () const
void setActionDamageMultiplier (float actionDamageMultiplier)
float getHealthDamageMultiplier () const
void setHealthDamageMultiplier (float healthDamageMultiplier)
float getMindDamageMultiplier () const
void setMindDamageMultiplier (float mindDamageMultiplier)
CombatQueueCommand * getCommand () const
float getDamage () const
int getAccuracyBonus () const
float getActionCostMultiplier () const
uint32 getAnimationCRC () const
int getAreaRange () const
int getConeAngle () const
float getDamageMultiplier () const
uint32 getDotDuration () const
uint8 getDotPool () const
float getDotPotency () const
uint32 getDotStrength () const
uint64 getDotType () const
int getDurationStateTime () const
float getForceCostMultiplier () const
float getHealthCostMultiplier () const
float getMindCostMultiplier () const
int getNextAttackDelayChance () const
int getPoolsToDamage () const
int getRange () const
float getSpeedMultiplier () const
VectorMap< uint64, StateEffect > * getStateEffects () const
VectorMap< uint64, DotEffect > * getDotEffects () const
void setAnimationCRC (uint32 animationCRC)
uint8 getAttackType () const
void setAttackType (uint8 attackType)
uint8 getTrails () const
void setTrails (uint8 trails)
String getCombatSpam () const
void setCombatSpam (String spam)
Protected Attributes
CombatQueueCommand * baseCommand
float damage
float damageMultiplier
float healthDamageMultiplier
float actionDamageMultiplier
float mindDamageMultiplier
int accuracyBonus
float speedMultiplier
int poolsToDamage
float healthCostMultiplier
float actionCostMultiplier
float mindCostMultiplier
float forceCostMultiplier
int nextAttackDelayChance
int durationStateTime
uint32 dotDuration
uint64 dotType
uint8 dotPool
uint32 dotStrength
float dotPotency
int range
int coneAngle
int areaRange
uint32 animationCRC
VectorMap< uint64, StateEffect > * stateEffects
VectorMap< uint64, DotEffect > * dotEffects
uint8 attackType
uint8 trails
String combatSpam
Detailed Description
Definition at line 17 of file CreatureAttackData.h.
Constructor & Destructor Documentation
CreatureAttackData::CreatureAttackData (const UnicodeString & dataString, CombatQueueCommand * base)
Definition at line 11 of file CreatureAttackData.cpp.
References baseCommand, fillFromBase(), and setVariable().
CreatureAttackData::CreatureAttackData (const CreatureAttackData & data)
Definition at line 34 of file CreatureAttackData.cpp.
References accuracyBonus, actionCostMultiplier, actionDamageMultiplier, animationCRC, areaRange, attackType, baseCommand, combatSpam, coneAngle, damage, damageMultiplier, dotDuration, dotEffects, dotPool, dotPotency, dotStrength, dotType, durationStateTime, forceCostMultiplier, healthCostMultiplier, healthDamageMultiplier, mindCostMultiplier, mindDamageMultiplier, nextAttackDelayChance, poolsToDamage, range, speedMultiplier, stateEffects, and trails.
virtual CreatureAttackData::~CreatureAttackData () inline virtual
Definition at line 61 of file CreatureAttackData.h.
Member Function Documentation
void CreatureAttackData::fillFromBase ()
Definition at line 74 of file CreatureAttackData.cpp.
References accuracyBonus, actionCostMultiplier, actionDamageMultiplier, animationCRC, areaRange, attackType, baseCommand, combatSpam, coneAngle, damage, damageMultiplier, dotDuration, dotEffects, dotPool, dotPotency, dotStrength, dotType, durationStateTime, forceCostMultiplier, CombatQueueCommand::getAccuracyBonus(), CombatQueueCommand::getActionCostMultiplier(), CombatQueueCommand::getAnimationCRC(), CombatQueueCommand::getAreaRange(), CombatQueueCommand::getAttackType(), CombatQueueCommand::getCombatSpam(), CombatQueueCommand::getConeAngle(), CombatQueueCommand::getDamage(), CombatQueueCommand::getDamageMultiplier(), CombatQueueCommand::getDotDuration(), CombatQueueCommand::getDotEffects(), CombatQueueCommand::getDotPool(), CombatQueueCommand::getDotPotency(), CombatQueueCommand::getDotStrength(), CombatQueueCommand::getDotType(), CombatQueueCommand::getDurationStateTime(), CombatQueueCommand::getForceCostMultiplier(), CombatQueueCommand::getHealthCostMultiplier(), CombatQueueCommand::getMindCostMultiplier(), CombatQueueCommand::getNextAttackDelayChance(), CombatQueueCommand::getPoolsToDamage(), CombatQueueCommand::getRange(), CombatQueueCommand::getSpeedMultiplier(), CombatQueueCommand::getStateEffects(), CombatQueueCommand::getTrails(), healthCostMultiplier, healthDamageMultiplier, mindCostMultiplier, mindDamageMultiplier, nextAttackDelayChance, poolsToDamage, range, speedMultiplier, stateEffects, and trails.
Referenced by CreatureAttackData().
int CreatureAttackData::getAccuracyBonus () const inline
Definition at line 101 of file CreatureAttackData.h.
References accuracyBonus.
Referenced by CombatManager::doTargetCombatAction().
float CreatureAttackData::getActionCostMultiplier () const inline
Definition at line 105 of file CreatureAttackData.h.
References actionCostMultiplier.
Referenced by CombatManager::applySpecialAttackCost().
float CreatureAttackData::getActionDamageMultiplier () const inline
Definition at line 69 of file CreatureAttackData.h.
References actionDamageMultiplier.
Referenced by CombatManager::applyDamage().
uint32 CreatureAttackData::getAnimationCRC () const inline
Definition at line 109 of file CreatureAttackData.h.
References animationCRC.
Referenced by CombatManager::broadcastCombatAction(), and CombatManager::doTargetCombatAction().
int CreatureAttackData::getAreaRange () const inline
Definition at line 113 of file CreatureAttackData.h.
References areaRange.
Referenced by CombatManager::doAreaCombatAction().
uint8 CreatureAttackData::getAttackType () const inline
Definition at line 189 of file CreatureAttackData.h.
References attackType.
Referenced by CombatManager::applyDamage(), CombatManager::calculateDamage(), and CombatManager::getArmorReduction().
String CreatureAttackData::getCombatSpam () const inline
Definition at line 205 of file CreatureAttackData.h.
References combatSpam.
Referenced by CombatManager::doTargetCombatAction().
CombatQueueCommand* CreatureAttackData::getCommand () const inline
Definition at line 93 of file CreatureAttackData.h.
References baseCommand.
Referenced by CombatManager::applyDamage(), CombatManager::applyDots(), CombatManager::applyStates(), CombatManager::broadcastCombatAction(), CombatManager::doAreaCombatAction(), CombatManager::doCombatAction(), and CombatManager::doTargetCombatAction().
uint32 CreatureAttackData::getCommandCRC () const
Definition at line 196 of file CreatureAttackData.cpp.
References baseCommand, and server::zone::objects::creature::commands::QueueCommand::getNameCRC().
Referenced by CombatManager::doCombatAction().
String CreatureAttackData::getCommandName () const
Definition at line 192 of file CreatureAttackData.cpp.
References baseCommand, and server::zone::objects::creature::commands::QueueCommand::getQueueCommandName().
int CreatureAttackData::getConeAngle () const inline
Definition at line 117 of file CreatureAttackData.h.
References coneAngle.
Referenced by CombatManager::doAreaCombatAction().
float CreatureAttackData::getDamage () const inline
Definition at line 97 of file CreatureAttackData.h.
References damage.
Referenced by CombatManager::calculateDamage().
float CreatureAttackData::getDamageMultiplier () const inline
Definition at line 121 of file CreatureAttackData.h.
References damageMultiplier.
Referenced by CombatManager::applyDamage(), and CombatManager::doTargetCombatAction().
uint32 CreatureAttackData::getDotDuration () const inline
Definition at line 125 of file CreatureAttackData.h.
References dotDuration.
VectorMap<uint64, DotEffect>* CreatureAttackData::getDotEffects () const inline
Definition at line 181 of file CreatureAttackData.h.
References dotEffects.
Referenced by CombatManager::applyDots().
uint8 CreatureAttackData::getDotPool () const inline
Definition at line 129 of file CreatureAttackData.h.
References dotPool.
float CreatureAttackData::getDotPotency () const inline
Definition at line 133 of file CreatureAttackData.h.
References dotPotency.
uint32 CreatureAttackData::getDotStrength () const inline
Definition at line 137 of file CreatureAttackData.h.
References dotStrength.
uint64 CreatureAttackData::getDotType () const inline
Definition at line 141 of file CreatureAttackData.h.
References dotType.
int CreatureAttackData::getDurationStateTime () const inline
Definition at line 145 of file CreatureAttackData.h.
References durationStateTime.
float CreatureAttackData::getForceCostMultiplier () const inline
Definition at line 149 of file CreatureAttackData.h.
References forceCostMultiplier.
Referenced by CombatManager::applySpecialAttackCost().
float CreatureAttackData::getHealthCostMultiplier () const inline
Definition at line 153 of file CreatureAttackData.h.
References healthCostMultiplier.
Referenced by CombatManager::applySpecialAttackCost().
float CreatureAttackData::getHealthDamageMultiplier () const inline
Definition at line 77 of file CreatureAttackData.h.
References healthDamageMultiplier.
Referenced by CombatManager::applyDamage().
float CreatureAttackData::getMindCostMultiplier () const inline
Definition at line 157 of file CreatureAttackData.h.
References mindCostMultiplier.
Referenced by CombatManager::applySpecialAttackCost().
float CreatureAttackData::getMindDamageMultiplier () const inline
Definition at line 85 of file CreatureAttackData.h.
References mindDamageMultiplier.
Referenced by CombatManager::applyDamage().
int CreatureAttackData::getNextAttackDelayChance () const inline
Definition at line 161 of file CreatureAttackData.h.
References nextAttackDelayChance.
int CreatureAttackData::getPoolsToDamage () const inline
Definition at line 165 of file CreatureAttackData.h.
References poolsToDamage.
Referenced by CombatManager::doTargetCombatAction().
int CreatureAttackData::getRange () const inline
Definition at line 169 of file CreatureAttackData.h.
References range.
Referenced by CombatManager::doAreaCombatAction().
float CreatureAttackData::getSpeedMultiplier () const inline
Definition at line 173 of file CreatureAttackData.h.
References speedMultiplier.
VectorMap<uint64, StateEffect>* CreatureAttackData::getStateEffects () const inline
Definition at line 177 of file CreatureAttackData.h.
References stateEffects.
Referenced by CombatManager::applyStates().
uint8 CreatureAttackData::getTrails () const inline
Definition at line 197 of file CreatureAttackData.h.
References trails.
Referenced by CombatManager::broadcastCombatAction().
void CreatureAttackData::setActionDamageMultiplier (float actionDamageMultiplier) inline
Definition at line 73 of file CreatureAttackData.h.
References actionDamageMultiplier.
void CreatureAttackData::setAnimationCRC (uint32 animationCRC) inline
Definition at line 185 of file CreatureAttackData.h.
References animationCRC.
void CreatureAttackData::setAttackType (uint8 attackType) inline
Definition at line 193 of file CreatureAttackData.h.
References attackType.
void CreatureAttackData::setCombatSpam (String spam) inline
Definition at line 209 of file CreatureAttackData.h.
References combatSpam.
void CreatureAttackData::setHealthDamageMultiplier (float healthDamageMultiplier) inline
Definition at line 81 of file CreatureAttackData.h.
References healthDamageMultiplier.
void CreatureAttackData::setMindDamageMultiplier (float mindDamageMultiplier) inline
Definition at line 89 of file CreatureAttackData.h.
References mindDamageMultiplier.
void CreatureAttackData::setTrails (uint8 trails) inline
Definition at line 201 of file CreatureAttackData.h.
References trails.
void CreatureAttackData::setVariable (const String & var, const String & val)
Definition at line 106 of file CreatureAttackData.cpp.
References accuracyBonus, actionCostMultiplier, actionDamageMultiplier, animationCRC, areaRange, attackType, combatSpam, coneAngle, damage, damageMultiplier, dotDuration, dotPool, dotPotency, dotStrength, dotType, durationStateTime, forceCostMultiplier, healthCostMultiplier, healthDamageMultiplier, mindCostMultiplier, mindDamageMultiplier, nextAttackDelayChance, poolsToDamage, range, speedMultiplier, and trails.
Referenced by CreatureAttackData().
Member Data Documentation
int CreatureAttackData::accuracyBonus protected
Definition at line 26 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getAccuracyBonus(), and setVariable().
float CreatureAttackData::actionCostMultiplier protected
Definition at line 31 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getActionCostMultiplier(), and setVariable().
float CreatureAttackData::actionDamageMultiplier protected
Definition at line 24 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getActionDamageMultiplier(), setActionDamageMultiplier(), and setVariable().
uint32 CreatureAttackData::animationCRC protected
Definition at line 48 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getAnimationCRC(), setAnimationCRC(), and setVariable().
int CreatureAttackData::areaRange protected
Definition at line 46 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getAreaRange(), and setVariable().
uint8 CreatureAttackData::attackType protected
Definition at line 53 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getAttackType(), setAttackType(), and setVariable().
CombatQueueCommand* CreatureAttackData::baseCommand protected
Definition at line 19 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getCommand(), getCommandCRC(), and getCommandName().
String CreatureAttackData::combatSpam protected
Definition at line 56 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getCombatSpam(), setCombatSpam(), and setVariable().
int CreatureAttackData::coneAngle protected
Definition at line 45 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getConeAngle(), and setVariable().
float CreatureAttackData::damage protected
Definition at line 21 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getDamage(), and setVariable().
float CreatureAttackData::damageMultiplier protected
Definition at line 22 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getDamageMultiplier(), and setVariable().
uint32 CreatureAttackData::dotDuration protected
Definition at line 38 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getDotDuration(), and setVariable().
VectorMap<uint64, DotEffect>* CreatureAttackData::dotEffects protected
Definition at line 51 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), and getDotEffects().
uint8 CreatureAttackData::dotPool protected
Definition at line 40 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getDotPool(), and setVariable().
float CreatureAttackData::dotPotency protected
Definition at line 42 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getDotPotency(), and setVariable().
uint32 CreatureAttackData::dotStrength protected
Definition at line 41 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getDotStrength(), and setVariable().
uint64 CreatureAttackData::dotType protected
Definition at line 39 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getDotType(), and setVariable().
int CreatureAttackData::durationStateTime protected
Definition at line 36 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getDurationStateTime(), and setVariable().
float CreatureAttackData::forceCostMultiplier protected
Definition at line 33 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getForceCostMultiplier(), and setVariable().
float CreatureAttackData::healthCostMultiplier protected
Definition at line 30 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getHealthCostMultiplier(), and setVariable().
float CreatureAttackData::healthDamageMultiplier protected
Definition at line 23 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getHealthDamageMultiplier(), setHealthDamageMultiplier(), and setVariable().
float CreatureAttackData::mindCostMultiplier protected
Definition at line 32 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getMindCostMultiplier(), and setVariable().
float CreatureAttackData::mindDamageMultiplier protected
Definition at line 25 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getMindDamageMultiplier(), setMindDamageMultiplier(), and setVariable().
int CreatureAttackData::nextAttackDelayChance protected
Definition at line 35 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getNextAttackDelayChance(), and setVariable().
int CreatureAttackData::poolsToDamage protected
Definition at line 28 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getPoolsToDamage(), and setVariable().
int CreatureAttackData::range protected
Definition at line 44 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getRange(), and setVariable().
float CreatureAttackData::speedMultiplier protected
Definition at line 27 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getSpeedMultiplier(), and setVariable().
VectorMap<uint64, StateEffect>* CreatureAttackData::stateEffects protected
Definition at line 50 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), and getStateEffects().
uint8 CreatureAttackData::trails protected
Definition at line 54 of file CreatureAttackData.h.
Referenced by CreatureAttackData(), fillFromBase(), getTrails(), setTrails(), and setVariable().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/combat/CreatureAttackData.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/combat/CreatureAttackData.cpp