Core3: ChatPersistentMessageToServerCallback Class Reference
ChatPersistentMessageToServerCallback Class Reference
#include <ChatPersistentMessageToServerCallback.h>
Public Member Functions
ChatPersistentMessageToServerCallback (ZoneClientSession *client, ZoneProcessServer *server)
void parse (Message *message)
int sendMail (const String &recipient)
int sendMailToPlayer (const String &recipientName)
void run ()
Public Member Functions inherited from server::zone::packets::MessageCallback
MessageCallback (ZoneClientSession *client, ZoneProcessServer *server)
virtual ~MessageCallback ()
int getTaskQueue ()
bool parseMessage (Message *packet)
ZoneClientSession * getClient ()
ZoneProcessServer * getServer ()
Private Attributes
UnicodeString header
UnicodeString body
String recipientName
uint32 sequence
StringIdChatParameterVector stringIdParameters
WaypointChatParameterVector waypointParameters
Additional Inherited Members
Protected Attributes inherited from server::zone::packets::MessageCallback
Reference< ZoneClientSession * > client
ManagedReference
< ZoneProcessServer * > server
int taskqueue
Detailed Description
Definition at line 23 of file ChatPersistentMessageToServerCallback.h.
Constructor & Destructor Documentation
ChatPersistentMessageToServerCallback::ChatPersistentMessageToServerCallback (ZoneClientSession * client, ZoneProcessServer * server) inline
Definition at line 33 of file ChatPersistentMessageToServerCallback.h.
References sequence.
Member Function Documentation
void ChatPersistentMessageToServerCallback::parse (Message * message) inline virtual
Implements server::zone::packets::MessageCallback.
Definition at line 39 of file ChatPersistentMessageToServerCallback.h.
References body, header, server::chat::WaypointChatParameter::parse(), server::chat::StringIdChatParameter::parse(), recipientName, sequence, stringIdParameters, and waypointParameters.
void ChatPersistentMessageToServerCallback::run () inline
Definition at line 158 of file ChatPersistentMessageToServerCallback.h.
References server::zone::packets::MessageCallback::client, recipientName, sendMail(), sendMailToPlayer(), and sequence.
int ChatPersistentMessageToServerCallback::sendMail (const String & recipient) inline
Definition at line 81 of file ChatPersistentMessageToServerCallback.h.
References server::zone::packets::MessageCallback::client, server::zone::objects::creature::CreatureObject::getFirstName(), sendMailToPlayer(), and server::zone::packets::MessageCallback::server.
Referenced by run().
int ChatPersistentMessageToServerCallback::sendMailToPlayer (const String & recipientName) inline
Definition at line 125 of file ChatPersistentMessageToServerCallback.h.
References body, server::zone::packets::MessageCallback::client, server::zone::objects::creature::CreatureObject::getPlayerObject(), header, recipientName, server::chat::ChatManager::sendMail(), server::zone::packets::MessageCallback::server, server::chat::StringIdChatParameter::setTT(), stringIdParameters, and waypointParameters.
Referenced by run(), and sendMail().
Member Data Documentation
UnicodeString ChatPersistentMessageToServerCallback::body private
Definition at line 25 of file ChatPersistentMessageToServerCallback.h.
Referenced by parse(), and sendMailToPlayer().
UnicodeString ChatPersistentMessageToServerCallback::header private
Definition at line 24 of file ChatPersistentMessageToServerCallback.h.
Referenced by parse(), and sendMailToPlayer().
String ChatPersistentMessageToServerCallback::recipientName private
Definition at line 26 of file ChatPersistentMessageToServerCallback.h.
Referenced by parse(), run(), and sendMailToPlayer().
uint32 ChatPersistentMessageToServerCallback::sequence private
Definition at line 27 of file ChatPersistentMessageToServerCallback.h.
Referenced by ChatPersistentMessageToServerCallback(), parse(), and run().
StringIdChatParameterVector ChatPersistentMessageToServerCallback::stringIdParameters private
Definition at line 29 of file ChatPersistentMessageToServerCallback.h.
Referenced by parse(), and sendMailToPlayer().
WaypointChatParameterVector ChatPersistentMessageToServerCallback::waypointParameters private
Definition at line 30 of file ChatPersistentMessageToServerCallback.h.
Referenced by parse(), and sendMailToPlayer().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/chat/ChatPersistentMessageToServerCallback.h