Core3: CombatManager Class Reference
CombatManager Class Reference
#include <CombatManager.h>
Public Member Functions
CombatManager ()
bool startCombat (CreatureObject *attacker, TangibleObject *defender, bool lockDefender=true)
bool attemptPeace (CreatureObject *attacker)
void forcePeace (CreatureObject *attacker)
int doCombatAction (TangibleObject *attacker, WeaponObject *weapon, TangibleObject *defenderObject, CombatQueueCommand *command)
int doCombatAction (CreatureObject *attacker, WeaponObject *weapon, TangibleObject *defenderObject, CombatQueueCommand *command)
int doCombatAction (CreatureObject *attacker, WeaponObject *weapon, TangibleObject *defenderObject, const CreatureAttackData &data)
void requestDuel (CreatureObject *player, CreatureObject *targetPlayer)
void requestEndDuel (CreatureObject *player, CreatureObject *targetPlayer)
void freeDuelList (CreatureObject *player, bool spam=false)
void declineDuel (CreatureObject *player, CreatureObject *targetPlayer)
float calculateWeaponAttackSpeed (CreatureObject *attacker, WeaponObject *weapon, float skillSpeedRatio)
void broadcastCombatSpam (TangibleObject *attacker, TangibleObject *defender, TangibleObject *weapon, uint32 damage, const String &stringid)
void broadcastCombatSpam (CreatureObject *attacker, TangibleObject *defender, TangibleObject *weapon, uint32 damage, const String &stringid)
void broadcastCombatAction (CreatureObject *attacker, TangibleObject *defenderObject, WeaponObject *weapon, const CreatureAttackData &data, uint8 hit)
float hitChanceEquation (float attackerAccuracy, float accuracyBonus, float targetDefense)
Static Public Attributes
static const int MISS = 0x00
static const int HIT = 0x01
static const int BLOCK = 0x02
static const int DODGE = 0x03
static const int COUNTER = 0x05
static const int RICOCHET = 0x07
static const int REFLECT = 0x08
static const int REFLECT_TO_TARGET = 0x09
static const uint8 NOLOCATION = 0x00
static const uint8 CHEST = 0x01
static const uint8 ARMS = 0x02
static const uint8 LEGS = 0x04
static const uint8 HEAD = 0x08
static const int NOTRAIL = 0x00
static const int LEFTFOOTTRAIL = 0x01
static const int RIGHTFOOTTRAIL = 0x02
static const int LEFTHANDTRAIL = 0x04
static const int RIGHTHANDTRAIL = 0x08
static const int WEAPONTRAIL = 0x10
static const int DEFAULTTRAIL = 0xFF
static const int HEALTH = 1
static const int ACTION = 2
static const int MIND = 4
static const int RANDOM = 8
static const int MELEEWEAPON = 0x1
static const int RANGEDWEAPON = 0x2
static const int THROWNWEAPON = 0x4
static const int HEAVYWEAPON = 0x8
static const int MINE = 0x10
static const int SPECIALHEAVYWEAPON = 0x20
static const int ONEHANDMELEEWEAPON = 0x40
static const int TWOHANDMELEEWEAPON = 0x80
static const int POLEARM = 0x100
static const int PISTOL = 0x200
static const int CARBINE = 0x400
static const int RIFLE = 0x800
static const int GRENADE = 0x1000
static const int LIGHTNINGRIFLE = 0x2000
static const int WEAPONATTACK = 0x0
static const int FORCEATTACK = 0x1
Protected Member Functions
int doTargetCombatAction (CreatureObject *attacker, WeaponObject *weapon, CreatureObject *defenderObject, const CreatureAttackData &data)
int doAreaCombatAction (TangibleObject *attacker, WeaponObject *weapon, TangibleObject *defenderObject, const CreatureAttackData &data)
int doAreaCombatAction (CreatureObject *attacker, WeaponObject *weapon, TangibleObject *defenderObject, const CreatureAttackData &data)
int doTargetCombatAction (CreatureObject *attacker, WeaponObject *weapon, TangibleObject *defenderObject, const CreatureAttackData &data)
void applyDots (CreatureObject *attacker, CreatureObject *defender, const CreatureAttackData &data, int appliedDamage)
void applyWeaponDots (CreatureObject *attacker, CreatureObject *defender, WeaponObject *weapon)
float getWeaponRangeModifier (float currentRange, WeaponObject *weapon)
uint32 getDefaultAttackAnimation (CreatureObject *creature)
int getHitChance (CreatureObject *creature, CreatureObject *targetCreature, WeaponObject *weapon, int damage, int accuracyBonus)
int getHitChance (TangibleObject *creature, CreatureObject *targetCreature, WeaponObject *weapon, int damage, int accuracyBonus)
int calculatePostureModifier (CreatureObject *creature, WeaponObject *weapon)
int calculateTargetPostureModifier (WeaponObject *weapon, CreatureObject *targetCreature)
int getAttackerAccuracyModifier (CreatureObject *attacker, WeaponObject *weapon)
int getAttackerAccuracyBonus (CreatureObject *attacker, WeaponObject *weapon)
int getDefenderDefenseModifier (CreatureObject *defender, WeaponObject *weapon)
int getDefenderSecondaryDefenseModifier (CreatureObject *defender)
float getDefenderToughnessModifier (CreatureObject *defender, int damType, float damage)
int calculateDamageRange (CreatureObject *attacker, CreatureObject *defender, WeaponObject *weapon)
int getDamageModifier (CreatureObject *attacker, WeaponObject *weapon)
int getSpeedModifier (CreatureObject *attacker, WeaponObject *weapon)
float calculateDamage (CreatureObject *attacker, WeaponObject *weapon, CreatureObject *defender, const CreatureAttackData &data)
float calculateDamage (CreatureObject *attacker, WeaponObject *weapon, TangibleObject *defender)
bool checkConeAngle (SceneObject *targetCreature, float angle, float creatureVectorX, float creatureVectorY, float directionVectorX, float directionVectorY)
void doMiss (CreatureObject *attacker, WeaponObject *weapon, CreatureObject *defender, int damage, const String &cbtSpam)
void doCounterAttack (CreatureObject *creature, WeaponObject *weapon, CreatureObject *defender, int damage, const String &cbtSpam)
void doBlock (CreatureObject *creature, WeaponObject *weapon, CreatureObject *defender, int damage, const String &cbtSpam)
void doDodge (CreatureObject *creature, WeaponObject *weapon, CreatureObject *defender, int damage, const String &cbtSpam)
void doLightsaberBlock (CreatureObject *creature, WeaponObject *weapon, CreatureObject *defender, int damage, const String &cbtSpam)
int applyDamage (TangibleObject *attacker, WeaponObject *weapon, CreatureObject *defenderObject, float damageMultiplier, int poolsToDamage, const CreatureAttackData &data)
int applyDamage (CreatureObject *attacker, WeaponObject *weapon, TangibleObject *defender, int poolsToDamage, const CreatureAttackData &data)
int applyDamage (CreatureObject *attacker, WeaponObject *weapon, CreatureObject *defender, int damage, float damageMultiplier, int poolsToDamage, const CreatureAttackData &data)
void applyStates (CreatureObject *creature, CreatureObject *targetCreature, const CreatureAttackData &data)
int doTargetCombatAction (TangibleObject *attacker, WeaponObject *weapon, CreatureObject *defenderObject, const CreatureAttackData &data)
int doTargetCombatAction (TangibleObject *attacker, WeaponObject *weapon, TangibleObject *tano, const CreatureAttackData &data)
int getArmorObjectReduction (WeaponObject *weapon, ArmorObject *armor)
int getArmorReduction (TangibleObject *attacker, WeaponObject *weapon, CreatureObject *defender, float damage, int poolsToDamage, const CreatureAttackData &data)
int getArmorReduction (CreatureObject *attacker, WeaponObject *weapon, CreatureObject *defender, float damage, int poolsToDamage, const CreatureAttackData &data)
float getArmorPiercing (TangibleObject *defender, WeaponObject *weapon)
int getArmorNpcReduction (CreatureObject *attacker, AiAgent *defender, WeaponObject *weapon)
int getArmorTurretReduction (CreatureObject *attacker, TangibleObject *defender, WeaponObject *weapon)
ArmorObject * getHealthArmor (CreatureObject *defender)
ArmorObject * getActionArmor (CreatureObject *defender)
ArmorObject * getMindArmor (CreatureObject *defender)
ArmorObject * getPSGArmor (CreatureObject *defender)
void doMiss (TangibleObject *attacker, CreatureObject *defender, WeaponObject *weapon, int damage, const String &cbtSpam)
void doCounterAttack (TangibleObject *attacker, CreatureObject *defender, WeaponObject *weapon, int damage, const String &cbtSpam)
void doBlock (TangibleObject *attacker, CreatureObject *defender, WeaponObject *weapon, int damage, const String &cbtSpam)
void doDodge (TangibleObject *attacker, CreatureObject *defender, WeaponObject *weapon, int damage, const String &cbtSpam)
void doLightsaberBlock (TangibleObject *attacker, CreatureObject *defender, WeaponObject *weapon, int damage, const String &cbtSpam)
int calculatePoolsToDamage (int poolsToDamage)
bool applySpecialAttackCost (CreatureObject *attacker, WeaponObject *weapon, const CreatureAttackData &data)
Static Protected Attributes
static const uint32 defaultAttacks [9]
Detailed Description
Definition at line 20 of file CombatManager.h.
Constructor & Destructor Documentation
CombatManager::CombatManager () inline
Definition at line 74 of file CombatManager.h.
Member Function Documentation
int CombatManager::applyDamage (TangibleObject * attacker, WeaponObject * weapon, CreatureObject * defenderObject, float damageMultiplier, int poolsToDamage, const CreatureAttackData & data) protected
Definition at line 1817 of file CombatManager.cpp.
Referenced by doTargetCombatAction().
int CombatManager::applyDamage (CreatureObject * attacker, WeaponObject * weapon, TangibleObject * defender, int poolsToDamage, const CreatureAttackData & data) protected
Definition at line 1412 of file CombatManager.cpp.
References calculateDamage(), server::zone::objects::tangible::weapon::WeaponObject::decreasePowerupUses(), FORCEATTACK, getArmorPiercing(), getArmorTurretReduction(), CreatureAttackData::getAttackType(), CreatureAttackData::getCommand(), CreatureAttackData::getDamageMultiplier(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), server::zone::objects::tangible::weapon::WeaponObject::getXpType(), server::zone::objects::tangible::TangibleObject::inflictDamage(), CombatQueueCommand::isAreaAction(), CombatQueueCommand::isConeAction(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::isTurret(), and CreatureFlag::NONE.
int CombatManager::applyDamage (CreatureObject * attacker, WeaponObject * weapon, CreatureObject * defender, int damage, float damageMultiplier, int poolsToDamage, const CreatureAttackData & data) protected
Definition at line 1351 of file CombatManager.cpp.
References ACTION, CreatureAttribute::ACTION, server::zone::objects::creature::CreatureObject::addShockWounds(), server::zone::objects::creature::CreatureObject::addWounds(), server::zone::objects::tangible::weapon::WeaponObject::decreasePowerupUses(), FORCEATTACK, CreatureAttackData::getActionDamageMultiplier(), getArmorReduction(), CreatureAttackData::getAttackType(), CreatureAttackData::getCommand(), CreatureAttackData::getHealthDamageMultiplier(), CreatureAttackData::getMindDamageMultiplier(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), server::zone::objects::tangible::weapon::WeaponObject::getWoundsRatio(), server::zone::objects::tangible::weapon::WeaponObject::getXpType(), HEALTH, CreatureAttribute::HEALTH, server::zone::objects::creature::CreatureObject::inflictDamage(), CombatQueueCommand::isAreaAction(), CombatQueueCommand::isConeAction(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), MIND, CreatureAttribute::MIND, and CreatureFlag::NONE.
void CombatManager::applyDots (CreatureObject * attacker, CreatureObject * defender, const CreatureAttackData & data, int appliedDamage) protected
Definition at line 296 of file CombatManager.cpp.
References server::zone::objects::creature::CreatureObject::addDotState(), CreatureAttackData::getCommand(), DotEffect::getDefenderStateDefenseModifers(), DotEffect::getDotChance(), DotEffect::getDotDuration(), CreatureAttackData::getDotEffects(), DotEffect::getDotPool(), DotEffect::getDotPotency(), DotEffect::getDotStrength(), DotEffect::getDotType(), server::zone::objects::creature::commands::QueueCommand::getNameCRC(), DotEffect::getPrimaryPercent(), DotEffect::getSecondaryPercent(), server::zone::objects::creature::CreatureObject::getSkillMod(), and DotEffect::isDotDamageofHit().
Referenced by doTargetCombatAction().
bool CombatManager::applySpecialAttackCost (CreatureObject * attacker, WeaponObject * weapon, const CreatureAttackData & data) protected
returns false on insufficient
Definition at line 1179 of file CombatManager.cpp.
References CreatureAttribute::ACTION, server::zone::objects::tangible::weapon::WeaponObject::decay(), CreatureAttribute::FOCUS, server::zone::objects::tangible::weapon::WeaponObject::getActionAttackCost(), CreatureAttackData::getActionCostMultiplier(), server::zone::objects::tangible::weapon::WeaponObject::getForceCost(), CreatureAttackData::getForceCostMultiplier(), server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::tangible::weapon::WeaponObject::getHealthAttackCost(), CreatureAttackData::getHealthCostMultiplier(), server::zone::objects::tangible::weapon::WeaponObject::getMindAttackCost(), CreatureAttackData::getMindCostMultiplier(), server::zone::objects::creature::CreatureObject::getPlayerObject(), CreatureAttribute::HEALTH, server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::scene::SceneObject::isAiAgent(), CreatureAttribute::MIND, CreatureAttribute::QUICKNESS, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and CreatureAttribute::STRENGTH.
Referenced by doCombatAction().
void CombatManager::applyStates (CreatureObject * creature, CreatureObject * targetCreature, const CreatureAttackData & data) protected
Definition at line 1234 of file CombatManager.cpp.
References CombatQueueCommand::applyEffect(), server::zone::objects::creature::CreatureObject::calculateBFRatio(), server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), CombatQueueCommand::getAccuracySkillMod(), CreatureAttackData::getCommand(), StateEffect::getDefenderExclusionTimers(), StateEffect::getDefenderJediStateDefenseModifiers(), StateEffect::getDefenderStateDefenseModifiers(), StateEffect::getEffectType(), server::zone::objects::tangible::TangibleObject::getLevel(), server::zone::objects::creature::CreatureObject::getSkillMod(), StateEffect::getStateChance(), CreatureAttackData::getStateEffects(), CommandEffect::INTIMIDATE, server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIntimidated(), CommandEffect::KNOCKDOWN, CommandEffect::NEXTATTACKDELAY, CommandEffect::POSTUREDOWN, CommandEffect::POSTUREUP, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setPosture(), and CreaturePosture::UPRIGHT.
Referenced by doTargetCombatAction().
void CombatManager::applyWeaponDots (CreatureObject * attacker, CreatureObject * defender, WeaponObject * weapon) protected
Definition at line 316 of file CombatManager.cpp.
References server::zone::objects::creature::CreatureObject::addDotState(), CreatureState::BLEEDING, CreatureState::DISEASED, server::zone::objects::creature::CreatureObject::getSkillMod(), CreatureState::ONFIRE, and CreatureState::POISONED.
Referenced by doTargetCombatAction().
bool CombatManager::attemptPeace (CreatureObject * attacker)
Attempts to stop combat
Precondition
{ attacker locked }
Postcondition
{ attacker locked }
Parameters
attacker CreatureObject that attempts peace state
Returns
true on succes
Definition at line 64 of file CombatManager.cpp.
References server::zone::objects::creature::CreatureObject::clearCombatState(), server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::tangible::TangibleObject::getDefenderList(), server::zone::objects::tangible::TangibleObject::getMainDefender(), server::zone::objects::tangible::TangibleObject::hasDefender(), server::zone::objects::creature::CreatureObject::hasState(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::scene::SceneObject::isInRange(), CreatureState::PEACE, server::zone::objects::tangible::TangibleObject::removeDefender(), server::zone::objects::creature::CreatureObject::setState(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
void CombatManager::broadcastCombatAction (CreatureObject * attacker, TangibleObject * defenderObject, WeaponObject * weapon, const CreatureAttackData & data, uint8 hit)
Definition at line 1487 of file CombatManager.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), SceneObjectType::DROIDCREATURE, CreatureAttackData::getAnimationCRC(), CreatureAttackData::getCommand(), getDefaultAttackAnimation(), CombatQueueCommand::getEffectString(), server::zone::objects::scene::SceneObject::getGameObjectType(), server::zone::objects::scene::SceneObject::getObjectID(), CreatureAttackData::getTrails(), server::zone::objects::creature::CreatureObject::isCreature(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::creature::CreatureObject::playEffect(), and SceneObjectType::PROBOTCREATURE.
Referenced by doTargetCombatAction().
void CombatManager::broadcastCombatSpam (TangibleObject * attacker, TangibleObject * defender, TangibleObject * weapon, uint32 damage, const String & stringid)
Definition at line 2234 of file CombatManager.cpp.
References server::zone::Zone::getInRangeObjects(), server::zone::objects::scene::SceneObject::getWorldPositionX(), server::zone::objects::scene::SceneObject::getWorldPositionY(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::scene::SceneObject::isPlayerCreature(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by doBlock(), doCounterAttack(), doDodge(), doLightsaberBlock(), doMiss(), TauntCommand::doQueueCommand(), and doTargetCombatAction().
void CombatManager::broadcastCombatSpam (CreatureObject * attacker, TangibleObject * defender, TangibleObject * weapon, uint32 damage, const String & stringid)
Definition at line 1455 of file CombatManager.cpp.
References server::zone::Zone::getInRangeObjects(), server::zone::objects::scene::SceneObject::getWorldPositionX(), server::zone::objects::scene::SceneObject::getWorldPositionY(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::scene::SceneObject::isPlayerCreature(), and server::zone::objects::creature::CreatureObject::sendMessage().
float CombatManager::calculateDamage (CreatureObject * attacker, WeaponObject * weapon, CreatureObject * defender, const CreatureAttackData & data) protected
Definition at line 984 of file CombatManager.cpp.
References calculateDamageRange(), server::zone::objects::tangible::weapon::WeaponObject::decay(), FORCEATTACK, CreatureAttackData::getAttackType(), server::zone::objects::tangible::weapon::WeaponObject::getAttackType(), CreatureAttackData::getDamage(), getDamageModifier(), server::zone::objects::tangible::weapon::WeaponObject::getDamageType(), getDefenderToughnessModifier(), server::zone::objects::tangible::weapon::WeaponObject::getMinDamage(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::tangible::weapon::WeaponObject::isCertifiedFor(), server::zone::objects::creature::CreatureObject::isKnockedDown(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::creature::CreatureObject::isProne().
Referenced by applyDamage(), and doTargetCombatAction().
float CombatManager::calculateDamage (CreatureObject * attacker, WeaponObject * weapon, TangibleObject * defender) protected
Definition at line 935 of file CombatManager.cpp.
References server::zone::objects::tangible::weapon::WeaponObject::getAttackType(), getDamageModifier(), server::zone::objects::tangible::weapon::WeaponObject::getMaxDamage(), server::zone::objects::tangible::weapon::WeaponObject::getMinDamage(), server::zone::objects::scene::SceneObject::getObservers(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::tangible::weapon::WeaponObject::isCertifiedFor(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and ObserverEventType::OBJECTDESTRUCTION.
int CombatManager::calculateDamageRange (CreatureObject * attacker, CreatureObject * defender, WeaponObject * weapon) protected
Definition at line 584 of file CombatManager.cpp.
References server::zone::objects::tangible::weapon::WeaponObject::getAttackType(), server::zone::objects::tangible::weapon::WeaponObject::getMaxDamage(), server::zone::objects::tangible::weapon::WeaponObject::getMinDamage(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::getSkillMod(), and server::zone::objects::player::PlayerObject::hasAbility().
Referenced by calculateDamage().
int CombatManager::calculatePoolsToDamage (int poolsToDamage) protected
returns bitmask with what pools to damage
Definition at line 1335 of file CombatManager.cpp.
References ACTION, HEALTH, MIND, and RANDOM.
Referenced by doTargetCombatAction().
int CombatManager::calculatePostureModifier (CreatureObject * creature, WeaponObject * weapon) protected
Definition at line 414 of file CombatManager.cpp.
References server::zone::objects::creature::CreatureObject::calculateSpeed(), CreatureLocomotion::FAST, server::zone::objects::tangible::weapon::WeaponObject::getAttackType(), server::zone::objects::creature::CreatureObject::getLocomotion(), server::zone::objects::creature::CreatureObject::getPosture(), server::zone::objects::creature::CreatureObject::isKneeling(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isProne(), and CreatureLocomotion::SLOW.
Referenced by getAttackerAccuracyBonus().
int CombatManager::calculateTargetPostureModifier (WeaponObject * weapon, CreatureObject * targetCreature) protected
Definition at line 440 of file CombatManager.cpp.
References server::zone::objects::creature::CreatureObject::isKneeling(), server::zone::objects::tangible::weapon::WeaponObject::isMeleeWeapon(), and server::zone::objects::creature::CreatureObject::isProne().
Referenced by getHitChance().
float CombatManager::calculateWeaponAttackSpeed (CreatureObject * attacker, WeaponObject * weapon, float skillSpeedRatio)
Definition at line 1130 of file CombatManager.cpp.
References server::zone::objects::tangible::weapon::WeaponObject::getAttackSpeed(), server::zone::objects::creature::CreatureObject::getSkillMod(), and getSpeedModifier().
bool CombatManager::checkConeAngle (SceneObject * targetCreature, float angle, float creatureVectorX, float creatureVectorY, float directionVectorX, float directionVectorY) protected
Definition at line 1688 of file CombatManager.cpp.
Referenced by doAreaCombatAction().
void CombatManager::declineDuel (CreatureObject * player, CreatureObject * targetPlayer)
Declines duel
Parameters
player player that is trying to end duel to target
targetPlayer target
Precondition
{ player != targetPlayer, player is locked }
Postcondition
{ player is locked }
Definition at line 1665 of file CombatManager.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::player::PlayerObject::removeFromDuelList(), server::zone::objects::player::PlayerObject::requestedDuelTo(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::chat::StringIdChatParameter::setTT().
int CombatManager::doAreaCombatAction (TangibleObject * attacker, WeaponObject * weapon, TangibleObject * defenderObject, const CreatureAttackData & data) protected
Definition at line 1935 of file CombatManager.cpp.
References checkConeAngle(), CollisionManager::checkLineOfSight(), doTargetCombatAction(), CreatureAttackData::getAreaRange(), CreatureAttackData::getCommand(), CreatureAttackData::getConeAngle(), server::zone::Zone::getInRangeObjects(), server::zone::objects::tangible::weapon::WeaponObject::getMaxRange(), server::zone::ZoneServer::getPlayerManager(), CreatureAttackData::getRange(), server::zone::objects::scene::SceneObject::getWorldPositionX(), server::zone::objects::scene::SceneObject::getWorldPositionY(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneServer(), CombatQueueCommand::isConeAction(), server::zone::objects::scene::SceneObject::isCreatureObject(), and server::zone::objects::scene::SceneObject::isInRange().
Referenced by doCombatAction().
int CombatManager::doAreaCombatAction (CreatureObject * attacker, WeaponObject * weapon, TangibleObject * defenderObject, const CreatureAttackData & data) protected
Definition at line 1823 of file CombatManager.cpp.
References checkConeAngle(), CollisionManager::checkLineOfSight(), server::zone::objects::tangible::weapon::WeaponObject::decreasePowerupUses(), doTargetCombatAction(), CreatureAttackData::getAreaRange(), CreatureAttackData::getCommand(), CreatureAttackData::getConeAngle(), server::zone::Zone::getInRangeObjects(), server::zone::objects::tangible::weapon::WeaponObject::getMaxRange(), server::zone::ZoneServer::getPlayerManager(), CreatureAttackData::getRange(), server::zone::objects::scene::SceneObject::getWorldPositionX(), server::zone::objects::scene::SceneObject::getWorldPositionY(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneServer(), CombatQueueCommand::isConeAction(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::tangible::weapon::WeaponObject::isHeavyWeapon(), server::zone::objects::scene::SceneObject::isInRange(), and server::zone::objects::tangible::weapon::WeaponObject::isThrownWeapon().
void CombatManager::doBlock (CreatureObject * creature, WeaponObject * weapon, CreatureObject * defender, int damage, const String & cbtSpam) protected
Definition at line 1155 of file CombatManager.cpp.
References broadcastCombatSpam(), and server::zone::objects::scene::SceneObject::showFlyText().
Referenced by doTargetCombatAction().
void CombatManager::doBlock (TangibleObject * attacker, CreatureObject * defender, WeaponObject * weapon, int damage, const String & cbtSpam) protected
Definition at line 2279 of file CombatManager.cpp.
References broadcastCombatSpam(), and server::zone::objects::scene::SceneObject::showFlyText().
int CombatManager::doCombatAction (TangibleObject * attacker, WeaponObject * weapon, TangibleObject * defenderObject, CombatQueueCommand * command)
Attempts combat action
Precondition
{ attacker locked, defender unlocked }
Postcondition
{ attacker locked, defender unlocked }
Parameters
attacker Attacker trying the action
defender Defender of the action
poolsToDamage bitmask of what pool to damage (bit 1 health, 2 action, 4 mind, 8 random)
Returns
returns -1 on failure to start combat or damage on succesfull combat
Definition at line 1715 of file CombatManager.cpp.
References doAreaCombatAction(), doTargetCombatAction(), and CombatQueueCommand::isAreaAction().
Referenced by HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), doCombatAction(), and CombatQueueCommand::doCombatAction().
int CombatManager::doCombatAction (CreatureObject * attacker, WeaponObject * weapon, TangibleObject * defenderObject, CombatQueueCommand * command)
Definition at line 150 of file CombatManager.cpp.
References doCombatAction().
int CombatManager::doCombatAction (CreatureObject * attacker, WeaponObject * weapon, TangibleObject * defenderObject, const CreatureAttackData & data)
Definition at line 154 of file CombatManager.cpp.
References applySpecialAttackCost(), server::zone::objects::creature::CreatureObject::checkKnockdownRecovery(), doAreaCombatAction(), doTargetCombatAction(), CreatureAttackData::getCommand(), CreatureAttackData::getCommandCRC(), server::zone::objects::creature::CreatureObject::hasAttackDelay(), CombatQueueCommand::isAreaAction(), server::zone::objects::creature::CreatureObject::isBerserked(), CombatQueueCommand::isConeAction(), startCombat(), and server::zone::objects::creature::CreatureObject::updateLastSuccessfulCombatAction().
void CombatManager::doCounterAttack (CreatureObject * creature, WeaponObject * weapon, CreatureObject * defender, int damage, const String & cbtSpam) protected
Definition at line 1148 of file CombatManager.cpp.
References broadcastCombatSpam(), and server::zone::objects::scene::SceneObject::showFlyText().
Referenced by doTargetCombatAction().
void CombatManager::doCounterAttack (TangibleObject * attacker, CreatureObject * defender, WeaponObject * weapon, int damage, const String & cbtSpam) protected
Definition at line 2272 of file CombatManager.cpp.
References broadcastCombatSpam(), and server::zone::objects::scene::SceneObject::showFlyText().
void CombatManager::doDodge (CreatureObject * creature, WeaponObject * weapon, CreatureObject * defender, int damage, const String & cbtSpam) protected
Definition at line 1171 of file CombatManager.cpp.
References broadcastCombatSpam(), and server::zone::objects::scene::SceneObject::showFlyText().
Referenced by doTargetCombatAction().
void CombatManager::doDodge (TangibleObject * attacker, CreatureObject * defender, WeaponObject * weapon, int damage, const String & cbtSpam) protected
Definition at line 2295 of file CombatManager.cpp.
References broadcastCombatSpam(), and server::zone::objects::scene::SceneObject::showFlyText().
void CombatManager::doLightsaberBlock (CreatureObject * creature, WeaponObject * weapon, CreatureObject * defender, int damage, const String & cbtSpam) protected
Definition at line 1163 of file CombatManager.cpp.
References broadcastCombatSpam().
Referenced by doTargetCombatAction().
void CombatManager::doLightsaberBlock (TangibleObject * attacker, CreatureObject * defender, WeaponObject * weapon, int damage, const String & cbtSpam) protected
Definition at line 2287 of file CombatManager.cpp.
References broadcastCombatSpam().
void CombatManager::doMiss (CreatureObject * attacker, WeaponObject * weapon, CreatureObject * defender, int damage, const String & cbtSpam) protected
Definition at line 1142 of file CombatManager.cpp.
References broadcastCombatSpam(), and server::zone::objects::scene::SceneObject::showFlyText().
Referenced by doTargetCombatAction().
void CombatManager::doMiss (TangibleObject * attacker, CreatureObject * defender, WeaponObject * weapon, int damage, const String & cbtSpam) protected
Definition at line 2266 of file CombatManager.cpp.
References broadcastCombatSpam(), and server::zone::objects::scene::SceneObject::showFlyText().
int CombatManager::doTargetCombatAction (CreatureObject * attacker, WeaponObject * weapon, CreatureObject * defenderObject, const CreatureAttackData & data) protected
Definition at line 223 of file CombatManager.cpp.
References applyDamage(), applyDots(), applyStates(), applyWeaponDots(), BLOCK, broadcastCombatAction(), broadcastCombatSpam(), calculateDamage(), calculatePoolsToDamage(), COUNTER, doBlock(), doCounterAttack(), DODGE, doDodge(), doLightsaberBlock(), doMiss(), CreatureAttackData::getAccuracyBonus(), CombatQueueCommand::getAccuracySkillMod(), CreatureAttackData::getCombatSpam(), CreatureAttackData::getCommand(), CreatureAttackData::getDamageMultiplier(), getHitChance(), CreatureAttackData::getPoolsToDamage(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::hasAttackDelay(), HIT, server::zone::objects::creature::CreatureObject::isEntertaining(), MISS, server::zone::objects::creature::CreatureObject::removeAttackDelay(), RICOCHET, and server::zone::objects::creature::CreatureObject::stopEntertaining().
Referenced by doAreaCombatAction(), doCombatAction(), and doTargetCombatAction().
int CombatManager::doTargetCombatAction (CreatureObject * attacker, WeaponObject * weapon, TangibleObject * defenderObject, const CreatureAttackData & data) protected
Definition at line 193 of file CombatManager.cpp.
References server::zone::objects::tangible::TangibleObject::addDefender(), applyDamage(), broadcastCombatAction(), broadcastCombatSpam(), calculatePoolsToDamage(), ObserverEventType::DAMAGERECEIVED, doTargetCombatAction(), CreatureAttackData::getCombatSpam(), CreatureAttackData::getPoolsToDamage(), server::zone::objects::tangible::TangibleObject::isAttackableBy(), and server::zone::objects::scene::SceneObject::isCreatureObject().
int CombatManager::doTargetCombatAction (TangibleObject * attacker, WeaponObject * weapon, CreatureObject * defenderObject, const CreatureAttackData & data) protected
Definition at line 1745 of file CombatManager.cpp.
References server::zone::objects::tangible::TangibleObject::addDefender(), BLOCK, broadcastCombatSpam(), server::zone::objects::scene::SceneObject::broadcastMessage(), COUNTER, DEFAULTTRAIL, doBlock(), doCounterAttack(), DODGE, doDodge(), doLightsaberBlock(), doMiss(), CreatureAttackData::getAccuracyBonus(), CreatureAttackData::getAnimationCRC(), getArmorReduction(), CombatQueueCommand::getCombatSpam(), CreatureAttackData::getCommand(), CreatureAttackData::getDamageMultiplier(), getHitChance(), server::zone::objects::tangible::weapon::WeaponObject::getMaxDamage(), server::zone::objects::tangible::weapon::WeaponObject::getMinDamage(), HEALTH, CreatureAttribute::HEALTH, HIT, server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::creature::CreatureObject::isAttackableBy(), MISS, and RICOCHET.
int CombatManager::doTargetCombatAction (TangibleObject * attacker, WeaponObject * weapon, TangibleObject * tano, const CreatureAttackData & data) protected
Definition at line 1728 of file CombatManager.cpp.
References doTargetCombatAction(), and server::zone::objects::scene::SceneObject::isCreatureObject().
void CombatManager::forcePeace (CreatureObject * attacker)
Forces clear combat
Precondition
{ attacker locked }
Postcondition
{ attacker locked }
Parameters
attacker CreatureObject clears combat
Definition at line 119 of file CombatManager.cpp.
References server::zone::objects::creature::CreatureObject::clearCombatState(), server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::tangible::TangibleObject::getDefenderList(), server::zone::objects::tangible::TangibleObject::hasDefender(), CreatureState::PEACE, server::zone::objects::tangible::TangibleObject::removeDefender(), server::zone::objects::creature::CreatureObject::setState(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
void CombatManager::freeDuelList (CreatureObject * player, bool spam = false)
Clears duel list
Parameters
player player to clear duel list
Precondition
{ player is locked }
Postcondition
{ player is locked }
Definition at line 1611 of file CombatManager.cpp.
References server::zone::objects::player::PlayerObject::getDuelListObject(), server::zone::objects::player::PlayerObject::getDuelListSize(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::info(), server::zone::objects::player::PlayerObject::isDuelListEmpty(), server::zone::objects::tangible::TangibleObject::removeDefender(), server::zone::objects::player::PlayerObject::removeFromDuelList(), server::zone::objects::player::PlayerObject::requestedDuelTo(), server::zone::objects::tangible::TangibleObject::sendPvpStatusTo(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::chat::StringIdChatParameter::setTT().
Referenced by EndDuelCommand::doQueueCommand().
ArmorObject * CombatManager::getActionArmor (CreatureObject * defender) protected
Definition at line 741 of file CombatManager.cpp.
References WearablesDeltaVector::getArmorAtHitLocation(), server::zone::objects::creature::CreatureObject::getWearablesDeltaVector(), and LEGS.
Referenced by getArmorReduction().
int CombatManager::getArmorNpcReduction (CreatureObject * attacker, AiAgent * defender, WeaponObject * weapon) protected
Definition at line 773 of file CombatManager.cpp.
References server::zone::objects::creature::AiAgent::getAcid(), server::zone::objects::creature::AiAgent::getBlast(), server::zone::objects::creature::AiAgent::getCold(), server::zone::objects::tangible::weapon::WeaponObject::getDamageType(), server::zone::objects::creature::AiAgent::getElectricity(), server::zone::objects::creature::AiAgent::getEnergy(), server::zone::objects::creature::AiAgent::getHeat(), server::zone::objects::creature::AiAgent::getKinetic(), server::zone::objects::creature::AiAgent::getLightSaber(), and server::zone::objects::creature::AiAgent::getStun().
Referenced by getArmorReduction().
int CombatManager::getArmorObjectReduction (WeaponObject * weapon, ArmorObject * armor) protected
Definition at line 684 of file CombatManager.cpp.
References server::zone::objects::tangible::wearables::ArmorObject::getAcid(), server::zone::objects::tangible::wearables::ArmorObject::getBlast(), server::zone::objects::tangible::wearables::ArmorObject::getCold(), server::zone::objects::tangible::weapon::WeaponObject::getDamageType(), server::zone::objects::tangible::wearables::ArmorObject::getElectricity(), server::zone::objects::tangible::wearables::ArmorObject::getEnergy(), server::zone::objects::tangible::wearables::ArmorObject::getHeat(), server::zone::objects::tangible::wearables::ArmorObject::getKinetic(), server::zone::objects::tangible::wearables::ArmorObject::getLightSaber(), and server::zone::objects::tangible::wearables::ArmorObject::getStun().
Referenced by getArmorReduction().
float CombatManager::getArmorPiercing (TangibleObject * defender, WeaponObject * weapon) protected
Definition at line 902 of file CombatManager.cpp.
References server::zone::objects::creature::AiAgent::getArmor(), server::zone::objects::tangible::weapon::WeaponObject::getArmorPiercing(), TurretDataComponent::getArmorRating(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::tangible::wearables::ArmorObject::getRating(), server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::scene::SceneObject::isArmorObject(), and server::zone::objects::tangible::TangibleObject::isBroken().
Referenced by applyDamage(), and getArmorReduction().
int CombatManager::getArmorReduction (TangibleObject * attacker, WeaponObject * weapon, CreatureObject * defender, float damage, int poolsToDamage, const CreatureAttackData & data) protected
Definition at line 2035 of file CombatManager.cpp.
References ACTION, ObserverEventType::FORCEBUFFHIT, getActionArmor(), getArmorNpcReduction(), getArmorObjectReduction(), getArmorPiercing(), CreatureAttackData::getAttackType(), server::zone::objects::tangible::weapon::WeaponObject::getDamageType(), getHealthArmor(), getMindArmor(), getPSGArmor(), server::zone::objects::creature::CreatureObject::getSkillMod(), HEALTH, server::zone::objects::scene::SceneObject::isAiAgent(), MIND, and WEAPONATTACK.
Referenced by applyDamage(), and doTargetCombatAction().
int CombatManager::getArmorReduction (CreatureObject * attacker, WeaponObject * weapon, CreatureObject * defender, float damage, int poolsToDamage, const CreatureAttackData & data) protected
Definition at line 814 of file CombatManager.cpp.
References ACTION, FORCEATTACK, ObserverEventType::FORCEBUFFHIT, getActionArmor(), getArmorNpcReduction(), getArmorObjectReduction(), getArmorPiercing(), CreatureAttackData::getAttackType(), server::zone::objects::tangible::weapon::WeaponObject::getDamageType(), getHealthArmor(), getMindArmor(), server::zone::objects::creature::CreatureObject::getPlayerObject(), getPSGArmor(), server::zone::objects::creature::CreatureObject::getSkillMod(), HEALTH, server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), MIND, and WEAPONATTACK.
int CombatManager::getArmorTurretReduction (CreatureObject * attacker, TangibleObject * defender, WeaponObject * weapon) protected
Definition at line 2105 of file CombatManager.cpp.
References TurretDataComponent::getAcid(), TurretDataComponent::getBlast(), TurretDataComponent::getCold(), server::zone::objects::tangible::weapon::WeaponObject::getDamageType(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), TurretDataComponent::getElectricity(), TurretDataComponent::getEnergy(), TurretDataComponent::getHeat(), TurretDataComponent::getKinetic(), TurretDataComponent::getLightSaber(), TurretDataComponent::getStun(), and server::zone::objects::scene::SceneObject::isTurret().
Referenced by applyDamage().
int CombatManager::getAttackerAccuracyBonus (CreatureObject * attacker, WeaponObject * weapon) protected
Definition at line 478 of file CombatManager.cpp.
References calculatePostureModifier(), server::zone::objects::tangible::weapon::WeaponObject::getAttackType(), server::zone::objects::creature::AiAgent::getChanceHit(), server::zone::objects::creature::CreatureObject::getSkillMod(), and server::zone::objects::scene::SceneObject::isAiAgent().
Referenced by getHitChance().
int CombatManager::getAttackerAccuracyModifier (CreatureObject * attacker, WeaponObject * weapon) protected
Definition at line 458 of file CombatManager.cpp.
References server::zone::objects::tangible::weapon::WeaponObject::getCreatureAccuracyModifiers(), server::zone::objects::creature::CreatureObject::getSkillMod(), and server::zone::objects::creature::CreatureObject::isStanding().
Referenced by getHitChance().
int CombatManager::getDamageModifier (CreatureObject * attacker, WeaponObject * weapon) protected
Definition at line 634 of file CombatManager.cpp.
References server::zone::objects::tangible::weapon::WeaponObject::getAttackType(), server::zone::objects::tangible::weapon::WeaponObject::getDamageModifiers(), and server::zone::objects::creature::CreatureObject::getSkillMod().
Referenced by calculateDamage().
uint32 CombatManager::getDefaultAttackAnimation (CreatureObject * creature) protected
Definition at line 1706 of file CombatManager.cpp.
References defaultAttacks, server::zone::objects::creature::CreatureObject::getWeapon(), and server::zone::objects::tangible::weapon::WeaponObject::isRangedWeapon().
Referenced by broadcastCombatAction().
int CombatManager::getDefenderDefenseModifier (CreatureObject * defender, WeaponObject * weapon) protected
Definition at line 499 of file CombatManager.cpp.
References server::zone::objects::tangible::weapon::WeaponObject::getDefenderDefenseModifiers(), server::zone::objects::tangible::TangibleObject::getLevel(), server::zone::objects::creature::CreatureObject::getSkillMod(), and server::zone::objects::creature::CreatureObject::isPlayerCreature().
Referenced by getHitChance().
int CombatManager::getDefenderSecondaryDefenseModifier (CreatureObject * defender) protected
Definition at line 527 of file CombatManager.cpp.
References server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::getWeapon(), and server::zone::objects::creature::CreatureObject::isIntimidated().
Referenced by getHitChance().
float CombatManager::getDefenderToughnessModifier (CreatureObject * defender, int damType, float damage) protected
Definition at line 547 of file CombatManager.cpp.
References server::zone::objects::creature::CreatureObject::getSkillMod(), and server::zone::objects::creature::CreatureObject::getWeapon().
Referenced by calculateDamage().
ArmorObject * CombatManager::getHealthArmor (CreatureObject * defender) protected
Definition at line 727 of file CombatManager.cpp.
References ARMS, CHEST, WearablesDeltaVector::getArmorAtHitLocation(), and server::zone::objects::creature::CreatureObject::getWearablesDeltaVector().
Referenced by getArmorReduction().
int CombatManager::getHitChance (CreatureObject * creature, CreatureObject * targetCreature, WeaponObject * weapon, int damage, int accuracyBonus) protected
Returns
0 - hit, 1 - block, 2 - dodge, 3 - counter-attack, 4 - miss
Definition at line 1035 of file CombatManager.cpp.
References BLOCK, calculateTargetPostureModifier(), COUNTER, DODGE, getAttackerAccuracyBonus(), getAttackerAccuracyModifier(), server::zone::objects::tangible::weapon::WeaponObject::getAttackType(), getDefenderDefenseModifier(), getDefenderSecondaryDefenseModifier(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::getWeapon(), getWeaponRangeModifier(), HIT, hitChanceEquation(), server::zone::objects::creature::CreatureObject::isCreature(), MISS, and RICOCHET.
Referenced by doTargetCombatAction().
int CombatManager::getHitChance (TangibleObject * creature, CreatureObject * targetCreature, WeaponObject * weapon, int damage, int accuracyBonus) protected
Definition at line 2157 of file CombatManager.cpp.
References BLOCK, COUNTER, DODGE, server::zone::objects::tangible::weapon::WeaponObject::getAttackType(), getDefenderDefenseModifier(), getDefenderSecondaryDefenseModifier(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::objects::tangible::TangibleObject::getHitChance(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::getWeapon(), getWeaponRangeModifier(), HIT, hitChanceEquation(), server::zone::objects::scene::SceneObject::isTurret(), MISS, and RICOCHET.
ArmorObject * CombatManager::getMindArmor (CreatureObject * defender) protected
Definition at line 752 of file CombatManager.cpp.
References WearablesDeltaVector::getArmorAtHitLocation(), server::zone::objects::creature::CreatureObject::getWearablesDeltaVector(), and HEAD.
Referenced by getArmorReduction().
ArmorObject * CombatManager::getPSGArmor (CreatureObject * defender) protected
Definition at line 763 of file CombatManager.cpp.
References server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::scene::SceneObject::isPsgArmorObject().
Referenced by getArmorReduction().
int CombatManager::getSpeedModifier (CreatureObject * attacker, WeaponObject * weapon) protected
Definition at line 663 of file CombatManager.cpp.
References server::zone::objects::tangible::weapon::WeaponObject::getAttackType(), server::zone::objects::creature::CreatureObject::getSkillMod(), and server::zone::objects::tangible::weapon::WeaponObject::getSpeedModifiers().
Referenced by calculateWeaponAttackSpeed().
float CombatManager::getWeaponRangeModifier (float currentRange, WeaponObject * weapon) protected
Definition at line 378 of file CombatManager.cpp.
References server::zone::objects::tangible::weapon::WeaponObject::getIdealAccuracy(), server::zone::objects::tangible::weapon::WeaponObject::getIdealRange(), server::zone::objects::tangible::weapon::WeaponObject::getMaxRange(), server::zone::objects::tangible::weapon::WeaponObject::getMaxRangeAccuracy(), server::zone::objects::tangible::weapon::WeaponObject::getPointBlankAccuracy(), and server::zone::objects::tangible::weapon::WeaponObject::getPointBlankRange().
Referenced by getHitChance().
float CombatManager::hitChanceEquation (float attackerAccuracy, float accuracyBonus, float targetDefense)
Definition at line 571 of file CombatManager.cpp.
Referenced by getHitChance().
void CombatManager::requestDuel (CreatureObject * player, CreatureObject * targetPlayer)
Requests duel
Parameters
player player that is trying to duel target
targetPlayer target
Precondition
{ player != targetPlayer, player is locked }
Postcondition
{ player is locked }
Definition at line 1518 of file CombatManager.cpp.
References server::zone::objects::player::PlayerObject::addToDuelList(), CreatureFlag::AGGRESSIVE, CreatureFlag::ATTACKABLE, server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), server::zone::objects::scene::SceneObject::info(), server::zone::objects::player::PlayerObject::requestedDuelTo(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::chat::StringIdChatParameter::setTT().
Referenced by DuelCommand::doQueueCommand().
void CombatManager::requestEndDuel (CreatureObject * player, CreatureObject * targetPlayer)
Requests end duel
Parameters
player player that is trying to end duel to target
targetPlayer target
Precondition
{ player != targetPlayer, player is locked }
Postcondition
{ player is locked }
Definition at line 1570 of file CombatManager.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::info(), server::zone::objects::tangible::TangibleObject::removeDefender(), server::zone::objects::player::PlayerObject::removeFromDuelList(), server::zone::objects::player::PlayerObject::requestedDuelTo(), server::zone::objects::tangible::TangibleObject::sendPvpStatusTo(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::chat::StringIdChatParameter::setTT().
Referenced by EndDuelCommand::doQueueCommand().
bool CombatManager::startCombat (CreatureObject * attacker, TangibleObject * defender, bool lockDefender = true)
Attempts combat between 2 creature objects
Precondition
{ attacker locked }
Postcondition
{ attacker locked }
Parameters
attacker attacking object
defender defender object
lockDefender will crosslock with attacker if true
Returns
true on success
Definition at line 35 of file CombatManager.cpp.
References server::zone::objects::tangible::TangibleObject::addDefender(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::tangible::TangibleObject::isAttackableBy(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isRidingMount(), and server::zone::objects::tangible::TangibleObject::setDefender().
Referenced by doCombatAction().
Member Data Documentation
const int CombatManager::ACTION = 2 static
Definition at line 50 of file CombatManager.h.
Referenced by applyDamage(), calculatePoolsToDamage(), getArmorReduction(), and server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const uint8 CombatManager::ARMS = 0x02 static
Definition at line 36 of file CombatManager.h.
Referenced by getHealthArmor(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::loadTemplateData(), TemplateManager::registerGlobals(), and ForceChokeTickTask::run().
const int CombatManager::BLOCK = 0x02 static
Definition at line 26 of file CombatManager.h.
Referenced by doTargetCombatAction(), and getHitChance().
const int CombatManager::CARBINE = 0x400 static
Definition at line 64 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const uint8 CombatManager::CHEST = 0x01 static
Definition at line 35 of file CombatManager.h.
Referenced by getHealthArmor(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::loadTemplateData(), TemplateManager::registerGlobals(), and ForceChokeTickTask::run().
const int CombatManager::COUNTER = 0x05 static
Definition at line 28 of file CombatManager.h.
Referenced by doTargetCombatAction(), and getHitChance().
const uint32 CombatManager::defaultAttacks static protected
Initial value:
= {
                0x99476628, 0xF5547B91, 0x3CE273EC, 0x734C00C,
                0x43C4FFD0, 0x56D7CC78, 0x4B41CAFB, 0x2257D06B,
                0x306887EB
}
Definition at line 167 of file CombatManager.h.
Referenced by getDefaultAttackAnimation().
const int CombatManager::DEFAULTTRAIL = 0xFF static
Definition at line 47 of file CombatManager.h.
Referenced by CombatQueueCommand::CombatQueueCommand(), doTargetCombatAction(), and server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::DODGE = 0x03 static
Definition at line 27 of file CombatManager.h.
Referenced by doTargetCombatAction(), and getHitChance().
const int CombatManager::FORCEATTACK = 0x1 static
Definition at line 71 of file CombatManager.h.
Referenced by applyDamage(), calculateDamage(), getArmorReduction(), and server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::GRENADE = 0x1000 static
Definition at line 66 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const uint8 CombatManager::HEAD = 0x08 static
Definition at line 38 of file CombatManager.h.
Referenced by getMindArmor(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::loadTemplateData(), TemplateManager::registerGlobals(), and ForceChokeTickTask::run().
const int CombatManager::HEALTH = 1 static
Definition at line 49 of file CombatManager.h.
Referenced by applyDamage(), calculatePoolsToDamage(), doTargetCombatAction(), getArmorReduction(), and server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::HEAVYWEAPON = 0x8 static
Definition at line 57 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::HIT = 0x01 static
Definition at line 25 of file CombatManager.h.
Referenced by doTargetCombatAction(), and getHitChance().
const int CombatManager::LEFTFOOTTRAIL = 0x01 static
Definition at line 42 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::LEFTHANDTRAIL = 0x04 static
Definition at line 44 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const uint8 CombatManager::LEGS = 0x04 static
Definition at line 37 of file CombatManager.h.
Referenced by getActionArmor(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::loadTemplateData(), TemplateManager::registerGlobals(), and ForceChokeTickTask::run().
const int CombatManager::LIGHTNINGRIFLE = 0x2000 static
Definition at line 67 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::MELEEWEAPON = 0x1 static
Definition at line 54 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::MIND = 4 static
Definition at line 51 of file CombatManager.h.
Referenced by applyDamage(), calculatePoolsToDamage(), getArmorReduction(), and server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::MINE = 0x10 static
Definition at line 58 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::MISS = 0x00 static
Definition at line 24 of file CombatManager.h.
Referenced by doTargetCombatAction(), and getHitChance().
const uint8 CombatManager::NOLOCATION = 0x00 static
Definition at line 34 of file CombatManager.h.
Referenced by ArmorObjectTemplate::ArmorObjectTemplate(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::loadTemplateData(), and TemplateManager::registerGlobals().
const int CombatManager::NOTRAIL = 0x00 static
Definition at line 41 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::ONEHANDMELEEWEAPON = 0x40 static
Definition at line 60 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::PISTOL = 0x200 static
Definition at line 63 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::POLEARM = 0x100 static
Definition at line 62 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::RANDOM = 8 static
Definition at line 52 of file CombatManager.h.
Referenced by calculatePoolsToDamage(), CombatQueueCommand::CombatQueueCommand(), and server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::RANGEDWEAPON = 0x2 static
Definition at line 55 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::REFLECT = 0x08 static
Definition at line 30 of file CombatManager.h.
const int CombatManager::REFLECT_TO_TARGET = 0x09 static
Definition at line 31 of file CombatManager.h.
const int CombatManager::RICOCHET = 0x07 static
Definition at line 29 of file CombatManager.h.
Referenced by doTargetCombatAction(), and getHitChance().
const int CombatManager::RIFLE = 0x800 static
Definition at line 65 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::RIGHTFOOTTRAIL = 0x02 static
Definition at line 43 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::RIGHTHANDTRAIL = 0x08 static
Definition at line 45 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::SPECIALHEAVYWEAPON = 0x20 static
Definition at line 59 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::THROWNWEAPON = 0x4 static
Definition at line 56 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::TWOHANDMELEEWEAPON = 0x80 static
Definition at line 61 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::WEAPONATTACK = 0x0 static
Definition at line 70 of file CombatManager.h.
Referenced by CombatQueueCommand::CombatQueueCommand(), getArmorReduction(), and server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
const int CombatManager::WEAPONTRAIL = 0x10 static
Definition at line 46 of file CombatManager.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::registerGlobals().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/combat/CombatManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/combat/CombatManager.cpp