Core3: BandFlourishCommand Class Reference
BandFlourishCommand Class Reference
#include <BandFlourishCommand.h>
Public Member Functions
BandFlourishCommand (const String &name, ZoneProcessServer *server)
void printStatus (CreatureObject *leader)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Static Public Member Functions
static void doBandFlourish (CreatureObject *leader, String &number, bool musicflourish, int instrumentType)
static int determineInstrumentType (const String &instrument)
static bool parseOptions (CreatureObject *leader, const String &options, String &stringA, String &stringB)
static void changeStatus (CreatureObject *leader, bool newstatus)
Detailed Description
Definition at line 56 of file BandFlourishCommand.h.
Constructor & Destructor Documentation
BandFlourishCommand::BandFlourishCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 59 of file BandFlourishCommand.h.
Member Function Documentation
static void BandFlourishCommand::changeStatus (CreatureObject * leader, bool newstatus) inline static
Definition at line 225 of file BandFlourishCommand.h.
References SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
static int BandFlourishCommand::determineInstrumentType (const String & instrument) inline static
Definition at line 172 of file BandFlourishCommand.h.
Referenced by doQueueCommand().
static void BandFlourishCommand::doBandFlourish (CreatureObject * leader, String & number, bool musicflourish, int instrumentType) inline static
Definition at line 64 of file BandFlourishCommand.h.
References SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::player::sessions::EntertainingSession::getInstrument(), server::zone::objects::tangible::Instrument::getInstrumentType(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isPlayingMusic(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::variables::StringId::setStringId(), and server::chat::StringIdChatParameter::setTT().
Referenced by doQueueCommand().
int BandFlourishCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 260 of file BandFlourishCommand.h.
References changeStatus(), determineInstrumentType(), doBandFlourish(), server::zone::objects::creature::CreatureObject::isDancing(), server::zone::objects::creature::CreatureObject::isEntertaining(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isPlayingMusic(), parseOptions(), printStatus(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
static bool BandFlourishCommand::parseOptions (CreatureObject * leader, const String & options, String & stringA, String & stringB) inline static
Definition at line 198 of file BandFlourishCommand.h.
References server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
void BandFlourishCommand::printStatus (CreatureObject * leader) inline
Definition at line 248 of file BandFlourishCommand.h.
References SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/BandFlourishCommand.h