Core3: AreaTrackTask Class Reference
AreaTrackTask Class Reference
#include <AreaTrackTask.h>
Public Member Functions
AreaTrackTask (CreatureObject *cr, int index)
void run ()
String getDirection (CreatureObject *tracker, CreatureObject *trackee)
String getDistance (CreatureObject *tracker, CreatureObject *trackee)
Private Attributes
ManagedReference
< CreatureObject * > player
int type
Coordinate initialPosition
Detailed Description
AreaTrackTask.h
Created: Sat Feb 5 Author: Kyle
Definition at line 58 of file AreaTrackTask.h.
Constructor & Destructor Documentation
AreaTrackTask::AreaTrackTask (CreatureObject * cr, int index) inline
Definition at line 64 of file AreaTrackTask.h.
References initialPosition, player, and type.
Member Function Documentation
String AreaTrackTask::getDirection (CreatureObject * tracker, CreatureObject * trackee) inline
Definition at line 162 of file AreaTrackTask.h.
Referenced by run().
String AreaTrackTask::getDistance (CreatureObject * tracker, CreatureObject * trackee) inline
Definition at line 213 of file AreaTrackTask.h.
Referenced by run().
void AreaTrackTask::run () inline
Definition at line 70 of file AreaTrackTask.h.
References getDirection(), getDistance(), initialPosition, player, SuiWindowType::RANGER_TRACK_RESULTS, and type.
Member Data Documentation
Coordinate AreaTrackTask::initialPosition private
Definition at line 61 of file AreaTrackTask.h.
Referenced by AreaTrackTask(), and run().
ManagedReference<CreatureObject*> AreaTrackTask::player private
Definition at line 59 of file AreaTrackTask.h.
Referenced by AreaTrackTask(), and run().
int AreaTrackTask::type private
Definition at line 60 of file AreaTrackTask.h.
Referenced by AreaTrackTask(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/events/AreaTrackTask.h