Core3: server::zone::objects::area::SpawnArea Class Reference
server::zone::objects::area::SpawnArea Class Reference
#include <SpawnArea.h>
Public Member Functions
SpawnArea ()
void registerObservers ()
Vector3 getRandomPosition (SceneObject *player)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addTemplate (unsigned int tempCRC)
void setTier (int n)
void setSpawnConstant (int n)
void addNoSpawnArea (SpawnArea *area)
bool isStaticArea ()
bool isDynamicArea ()
bool isLairSpawnArea ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::area::ActiveArea
ActiveArea ()
void sendTo (SceneObject *player, bool doClose)
void enqueueEnterEvent (SceneObject *obj)
void enqueueExitEvent (SceneObject *obj)
void notifyEnter (SceneObject *object)
void notifyExit (SceneObject *object)
bool isActiveArea ()
bool isRegion ()
bool isCityRegion ()
bool isNoBuildArea ()
bool isCampingPermitted ()
bool containsPoint (float x, float y)
float getRadius2 ()
void setNoBuildArea (bool val)
void setCampingPermitted (bool val)
void setMunicipalZone (bool val)
void setRadius (float r)
bool isCampArea ()
void setNoSpawnArea (bool val)
bool isNoSpawnArea ()
bool isMunicipalZone ()
unsigned long long getCellObjectID ()
void setCellObjectID (unsigned long long celloid)
void setAreaShape (AreaShape *area)
AreaShape * getAreaShape ()
bool intersectsWith (ActiveArea *area)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject ()
void initializePrivateData ()
void loadTemplateData (SharedObjectTemplate *templateData)
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendAttributeListTo (CreatureObject *object)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
void openContainerTo (CreatureObject *player)
byte checkContainerPermission (CreatureObject *player, unsigned short permission)
void closeContainerTo (CreatureObject *player, bool notify=true)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets=true)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
String getDetailedDescription ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
SpawnArea (DummyConstructorParameter *param)
virtual ~SpawnArea ()
Protected Member Functions inherited from server::zone::objects::area::ActiveArea
ActiveArea (DummyConstructorParameter *param)
virtual ~ActiveArea ()
Protected Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject (DummyConstructorParameter *param)
virtual ~SceneObject ()
Friends
class SpawnAreaHelper
Detailed Description
Definition at line 71 of file SpawnArea.h.
Constructor & Destructor Documentation
SpawnArea::SpawnArea ()
Definition at line 19 of file SpawnArea.cpp.
References server::zone::objects::area::SpawnAreaImplementation::_setStub().
SpawnArea::SpawnArea (DummyConstructorParameter * param) protected
Definition at line 26 of file SpawnArea.cpp.
SpawnArea::~SpawnArea () protected virtual
Definition at line 30 of file SpawnArea.cpp.
Member Function Documentation
DistributedObjectServant * SpawnArea::_getImplementation ()
Definition at line 169 of file SpawnArea.cpp.
Referenced by addNoSpawnArea(), addTemplate(), getRandomPosition(), isDynamicArea(), isLairSpawnArea(), isStaticArea(), notifyObserverEvent(), registerObservers(), setSpawnConstant(), and setTier().
DistributedObjectServant * SpawnArea::_getImplementationForRead ()
Definition at line 175 of file SpawnArea.cpp.
void SpawnArea::_setImplementation (DistributedObjectServant * servant)
Definition at line 179 of file SpawnArea.cpp.
void SpawnArea::addNoSpawnArea (SpawnArea * area)
Definition at line 116 of file SpawnArea.cpp.
References _getImplementation(), server::zone::objects::area::SpawnAreaImplementation::addNoSpawnArea(), and RPC_ADDNOSPAWNAREA__SPAWNAREA_.
Referenced by SpawnAreaMap::loadMap().
void SpawnArea::addTemplate (unsigned int tempCRC)
Definition at line 74 of file SpawnArea.cpp.
References _getImplementation(), server::zone::objects::area::SpawnAreaImplementation::addTemplate(), and RPC_ADDTEMPLATE__INT_.
Vector3 SpawnArea::getRandomPosition (SceneObject * player)
Definition at line 48 of file SpawnArea.cpp.
References _getImplementation(), and server::zone::objects::area::SpawnAreaImplementation::getRandomPosition().
bool SpawnArea::isDynamicArea ()
Definition at line 143 of file SpawnArea.cpp.
References _getImplementation(), server::zone::objects::area::SpawnAreaImplementation::isDynamicArea(), and RPC_ISDYNAMICAREA__.
bool SpawnArea::isLairSpawnArea ()
Definition at line 156 of file SpawnArea.cpp.
References _getImplementation(), server::zone::objects::area::SpawnAreaImplementation::isLairSpawnArea(), and RPC_ISLAIRSPAWNAREA__.
bool SpawnArea::isStaticArea ()
Definition at line 130 of file SpawnArea.cpp.
References _getImplementation(), server::zone::objects::area::SpawnAreaImplementation::isStaticArea(), and RPC_ISSTATICAREA__.
int SpawnArea::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 57 of file SpawnArea.cpp.
References _getImplementation(), server::zone::objects::area::SpawnAreaImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
void SpawnArea::registerObservers ()
Definition at line 35 of file SpawnArea.cpp.
References _getImplementation(), server::zone::objects::area::SpawnAreaImplementation::registerObservers(), and RPC_REGISTEROBSERVERS__.
void SpawnArea::setSpawnConstant (int n)
Definition at line 102 of file SpawnArea.cpp.
References _getImplementation(), RPC_SETSPAWNCONSTANT__INT_, and server::zone::objects::area::SpawnAreaImplementation::setSpawnConstant().
void SpawnArea::setTier (int n)
Definition at line 88 of file SpawnArea.cpp.
References _getImplementation(), RPC_SETTIER__INT_, and server::zone::objects::area::SpawnAreaImplementation::setTier().
Friends And Related Function Documentation
friend class SpawnAreaHelper friend
Definition at line 105 of file SpawnArea.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/SpawnArea.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/SpawnArea.cpp