Core3: TreeDirectory Class Reference
TreeDirectory Class Reference
#include <TreeDirectory.h>
Public Member Functions
TreeDirectory ()
TreeDirectory (const TreeDirectory &d)
TreeDirectory & operator= (const TreeDirectory &d)
int compare (Reference< TreeFileRecord * > &o1, const Reference< TreeFileRecord * > &o2) const
int compare (Reference< TreeFileRecord * > &o1, const String &fileName) const
int find (const String &fileName) const
Detailed Description
Definition at line 14 of file TreeDirectory.h.
Constructor & Destructor Documentation
TreeDirectory::TreeDirectory () inline
Definition at line 16 of file TreeDirectory.h.
TreeDirectory::TreeDirectory (const TreeDirectory & d) inline
Definition at line 20 of file TreeDirectory.h.
Member Function Documentation
int TreeDirectory::compare (Reference< TreeFileRecord * > & o1, const Reference< TreeFileRecord * > & o2) const inline
Definition at line 33 of file TreeDirectory.h.
Referenced by find().
int TreeDirectory::compare (Reference< TreeFileRecord * > & o1, const String & fileName) const inline
Definition at line 37 of file TreeDirectory.h.
int TreeDirectory::find (const String & fileName) const inline
Definition at line 41 of file TreeDirectory.h.
References compare().
Referenced by TreeArchive::getBytes().
TreeDirectory& TreeDirectory::operator= (const TreeDirectory & d) inline
Definition at line 24 of file TreeDirectory.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/tre3/TreeDirectory.h