Core3: UpdateWarStatusTask Class Reference
UpdateWarStatusTask Class Reference
#include <UpdateWarStatusTask.h>
Public Member Functions
UpdateWarStatusTask (ZoneServer *zserv, GuildObject *guild, GuildObject *waringGuild)
void run ()
Private Attributes
ZoneServer * server
GuildMemberList guild1
GuildMemberList guild2
Detailed Description
Definition at line 15 of file UpdateWarStatusTask.h.
Constructor & Destructor Documentation
UpdateWarStatusTask::UpdateWarStatusTask (ZoneServer * zserv, GuildObject * guild, GuildObject * waringGuild) inline
Definition at line 22 of file UpdateWarStatusTask.h.
References server::zone::objects::guild::GuildObject::getGuildMemberList(), guild1, guild2, and server.
Member Function Documentation
void UpdateWarStatusTask::run () inline
Definition at line 29 of file UpdateWarStatusTask.h.
References server::zone::ZoneServer::getObject(), guild1, guild2, server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::tangible::TangibleObject::sendPvpStatusTo(), and server.
Member Data Documentation
GuildMemberList UpdateWarStatusTask::guild1 private
Definition at line 18 of file UpdateWarStatusTask.h.
Referenced by run(), and UpdateWarStatusTask().
GuildMemberList UpdateWarStatusTask::guild2 private
Definition at line 19 of file UpdateWarStatusTask.h.
Referenced by run(), and UpdateWarStatusTask().
ZoneServer* UpdateWarStatusTask::server private
Definition at line 16 of file UpdateWarStatusTask.h.
Referenced by run(), and UpdateWarStatusTask().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/guild/UpdateWarStatusTask.h