Core3: PathFinderManager Class Reference
PathFinderManager Class Reference
#include <PathFinderManager.h>
Public Member Functions
PathFinderManager ()
Vector< WorldCoordinates > * findPath (const WorldCoordinates &pointA, const WorldCoordinates &pointB)
void filterPastPoints (Vector< WorldCoordinates > *path, SceneObject *object)
int getFloorPath (const Vector3 &pointA, const Vector3 &pointB, FloorMesh *floor, Vector< Triangle * > *&nodes)
Static Public Member Functions
static Vector3 transformToModelSpace (const Vector3 &point, SceneObject *building)
static FloorMesh * getFloorMesh (CellObject *cell)
Protected Member Functions
Vector< WorldCoordinates > * findPathFromWorldToWorld (const WorldCoordinates &pointA, const WorldCoordinates &pointB)
Vector< WorldCoordinates > * findPathFromWorldToCell (const WorldCoordinates &pointA, const WorldCoordinates &pointB)
Vector< WorldCoordinates > * findPathFromCellToWorld (const WorldCoordinates &pointA, const WorldCoordinates &pointB)
Vector< WorldCoordinates > * findPathFromCellToCell (const WorldCoordinates &pointA, const WorldCoordinates &pointB)
Vector< WorldCoordinates > * findPathFromCellToDifferentCell (const WorldCoordinates &pointA, const WorldCoordinates &pointB)
void addTriangleNodeEdges (const Vector3 &source, const Vector3 &goal, Vector< Triangle * > *trianglePath, Vector< WorldCoordinates > *path, SceneObject *cell)
Detailed Description
Definition at line 34 of file PathFinderManager.h.
Constructor & Destructor Documentation
PathFinderManager::PathFinderManager () inline
Definition at line 37 of file PathFinderManager.h.
Member Function Documentation
void PathFinderManager::addTriangleNodeEdges (const Vector3 & source, const Vector3 & goal, Vector< Triangle * > * trianglePath, Vector< WorldCoordinates > * path, SceneObject * cell) protected
Definition at line 414 of file PathFinderManager.cpp.
Referenced by findPathFromCellToCell(), findPathFromCellToDifferentCell(), findPathFromCellToWorld(), and findPathFromWorldToCell().
void PathFinderManager::filterPastPoints (Vector< WorldCoordinates > * path, SceneObject * object)
Definition at line 45 of file PathFinderManager.cpp.
References WorldCoordinates::getCell(), and WorldCoordinates::getWorldPosition().
Referenced by server::zone::objects::creature::AiAgentImplementation::findNextPosition().
Vector< WorldCoordinates > * PathFinderManager::findPath (const WorldCoordinates & pointA, const WorldCoordinates & pointB)
Definition at line 22 of file PathFinderManager.cpp.
References findPathFromCellToCell(), findPathFromCellToWorld(), findPathFromWorldToCell(), findPathFromWorldToWorld(), WorldCoordinates::getCell(), WorldCoordinates::getX(), WorldCoordinates::getY(), and WorldCoordinates::getZ().
Referenced by FindObjectCommand::doQueueCommand(), and server::zone::objects::creature::AiAgentImplementation::findNextPosition().
Vector< WorldCoordinates > * PathFinderManager::findPathFromCellToCell (const WorldCoordinates & pointA, const WorldCoordinates & pointB) protected
Definition at line 618 of file PathFinderManager.cpp.
References addTriangleNodeEdges(), findPathFromCellToDifferentCell(), WorldCoordinates::getCell(), server::zone::objects::cell::CellObject::getCellNumber(), PortalLayout::getFloorMesh(), getFloorPath(), server::zone::objects::scene::SceneObject::getParent(), FloorMesh::getPathGraph(), and WorldCoordinates::getPoint().
Referenced by findPath().
Vector< WorldCoordinates > * PathFinderManager::findPathFromCellToDifferentCell (const WorldCoordinates & pointA, const WorldCoordinates & pointB) protected
Definition at line 469 of file PathFinderManager.cpp.
References addTriangleNodeEdges(), CollisionManager::findNearestPathNode(), WorldCoordinates::getCell(), FloorMesh::getCellID(), server::zone::objects::cell::CellObject::getCellNumber(), PortalLayout::getFloorMesh(), PathGraph::getFloorMesh(), getFloorPath(), PathNode::getID(), server::zone::objects::scene::SceneObject::getParent(), PortalLayout::getPath(), PathNode::getPathGraph(), FloorMesh::getPathGraph(), WorldCoordinates::getPoint(), server::zone::templates::SharedObjectTemplate::getPortalLayout(), PathNode::getPosition(), and CollisionManager::getTriangle().
Referenced by findPathFromCellToCell().
Vector< WorldCoordinates > * PathFinderManager::findPathFromCellToWorld (const WorldCoordinates & pointA, const WorldCoordinates & pointB) protected
Definition at line 310 of file PathFinderManager.cpp.
References addTriangleNodeEdges(), PathGraph::findNearestGlobalNode(), CollisionManager::findNearestPathNode(), WorldCoordinates::getCell(), FloorMesh::getCellID(), server::zone::objects::cell::CellObject::getCellNumber(), PortalLayout::getFloorMesh(), PathGraph::getFloorMesh(), getFloorPath(), server::zone::objects::scene::SceneObject::getParent(), PortalLayout::getPath(), PathNode::getPathGraph(), FloorMesh::getPathGraph(), WorldCoordinates::getPoint(), server::zone::templates::SharedObjectTemplate::getPortalLayout(), PathNode::getPosition(), CollisionManager::getTriangle(), and transformToModelSpace().
Referenced by findPath().
Vector< WorldCoordinates > * PathFinderManager::findPathFromWorldToCell (const WorldCoordinates & pointA, const WorldCoordinates & pointB) protected
Definition at line 98 of file PathFinderManager.cpp.
References addTriangleNodeEdges(), PathGraph::findNearestNode(), CollisionManager::findNearestPathNode(), WorldCoordinates::getCell(), FloorMesh::getCellID(), server::zone::objects::cell::CellObject::getCellNumber(), PortalLayout::getFloorMesh(), PathGraph::getFloorMesh(), getFloorPath(), server::zone::templates::SharedObjectTemplate::getFullTemplateString(), server::zone::objects::scene::SceneObject::getParent(), PortalLayout::getPath(), PathNode::getPathGraph(), FloorMesh::getPathGraph(), WorldCoordinates::getPoint(), server::zone::templates::SharedObjectTemplate::getPortalLayout(), PathNode::getPosition(), CollisionManager::getTriangle(), and transformToModelSpace().
Referenced by findPath().
Vector< WorldCoordinates > * PathFinderManager::findPathFromWorldToWorld (const WorldCoordinates & pointA, const WorldCoordinates & pointB) protected
Definition at line 88 of file PathFinderManager.cpp.
Referenced by findPath().
FloorMesh * PathFinderManager::getFloorMesh (CellObject * cell) static
Definition at line 216 of file PathFinderManager.cpp.
References server::zone::objects::cell::CellObject::getCellNumber(), PortalLayout::getFloorMesh(), server::zone::objects::scene::SceneObject::getParent(), and server::zone::templates::SharedObjectTemplate::getPortalLayout().
Referenced by server::zone::objects::creature::AiAgentImplementation::findNextPosition().
int PathFinderManager::getFloorPath (const Vector3 & pointA, const Vector3 & pointB, FloorMesh * floor, Vector< Triangle * > *& nodes)
Returns
-1 when points are in the same triangle
0 when a successful path is found, the path is in nodes
1 when no successful path is found
Definition at line 236 of file PathFinderManager.cpp.
References CollisionManager::getTriangle().
Referenced by server::zone::objects::creature::AiAgentImplementation::findNextPosition(), findPathFromCellToCell(), findPathFromCellToDifferentCell(), findPathFromCellToWorld(), and findPathFromWorldToCell().
Vector3 PathFinderManager::transformToModelSpace (const Vector3 & point, SceneObject * building) static
Definition at line 280 of file PathFinderManager.cpp.
References server::zone::objects::scene::SceneObject::getDirection().
Referenced by AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), findPathFromCellToWorld(), findPathFromWorldToCell(), and DragIncapacitatedPlayerCommand::getCoordinate().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/collision/PathFinderManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/collision/PathFinderManager.cpp