Core3: FirstAidCommand Class Reference
FirstAidCommand Class Reference
#include <FirstAidCommand.h>
Public Member Functions
FirstAidCommand (const String &name, ZoneProcessServer *server)
void doAnimations (CreatureObject *creature, CreatureObject *creatureTarget)
void sendCureMessage (CreatureObject *object, CreatureObject *target)
bool canPerformSkill (CreatureObject *creature, CreatureObject *creatureTarget)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Private Attributes
float mindCost
float range
Detailed Description
Definition at line 50 of file FirstAidCommand.h.
Constructor & Destructor Documentation
FirstAidCommand::FirstAidCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 55 of file FirstAidCommand.h.
References mindCost, and range.
Member Function Documentation
bool FirstAidCommand::canPerformSkill (CreatureObject * creature, CreatureObject * creatureTarget) inline
Definition at line 96 of file FirstAidCommand.h.
References CollisionManager::checkLineOfSight(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::isBleeding(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
void FirstAidCommand::doAnimations (CreatureObject * creature, CreatureObject * creatureTarget) inline
Definition at line 62 of file FirstAidCommand.h.
References server::zone::objects::creature::CreatureObject::doAnimation(), and server::zone::objects::creature::CreatureObject::playEffect().
Referenced by doQueueCommand().
int FirstAidCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 118 of file FirstAidCommand.h.
References CreatureState::BLEEDING, canPerformSkill(), doAnimations(), server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::healDot(), server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::creature::CreatureObject::isAttackableBy(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isHealableBy(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::CreatureObject::isMeditating(), server::zone::objects::creature::CreatureObject::isMounted(), server::zone::objects::creature::CreatureObject::isProne(), server::zone::objects::creature::CreatureObject::isRidingCreature(), CreatureAttribute::MIND, mindCost, range, sendCureMessage(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
void FirstAidCommand::sendCureMessage (CreatureObject * object, CreatureObject * target) inline
Definition at line 71 of file FirstAidCommand.h.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
Member Data Documentation
float FirstAidCommand::mindCost private
Definition at line 51 of file FirstAidCommand.h.
Referenced by doQueueCommand(), and FirstAidCommand().
float FirstAidCommand::range private
Definition at line 52 of file FirstAidCommand.h.
Referenced by doQueueCommand(), and FirstAidCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/FirstAidCommand.h