Core3: CreatureHabitatMenuComponent Class Reference
CreatureHabitatMenuComponent Class Reference
#include <CreatureHabitatMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 14 of file CreatureHabitatMenuComponent.h.
Member Function Documentation
void CreatureHabitatMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Release
Reimplemented from TangibleObjectMenuComponent.
Definition at line 17 of file CreatureHabitatMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), TangibleObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::scene::SceneObject::isCreatureHabitat().
int CreatureHabitatMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from TangibleObjectMenuComponent.
Definition at line 47 of file CreatureHabitatMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getZone(), TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::scene::SceneObject::isCreatureHabitat(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::removeAllContainerObjects(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/generic/CreatureHabitatMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/generic/CreatureHabitatMenuComponent.cpp