Core3: server::zone::objects::creature::AiAgentImplementation Class Reference
server::zone::objects::creature::AiAgentImplementation Class Reference
#include <AiAgent.h>
Public Member Functions
AiAgentImplementation ()
AiAgentImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void finalize ()
virtual void activateRecovery ()
virtual void activateMovementEvent ()
virtual void activateWaitEvent ()
void activateAwarenessEvent (CreatureObject *target)
bool tryRetreat ()
void doRecovery ()
void doAttack ()
void doMovement ()
void setLevel (int lvl)
void sendBaselinesTo (SceneObject *player)
int calculateAttackMinDamage (int level)
int calculateAttackMaxDamage (int level)
float calculateAttackSpeed (int level)
virtual bool isCamouflaged (CreatureObject *target)
bool isScentMasked (CreatureObject *target)
bool isConcealed (CreatureObject *target)
void doAwarenessCheck (Coordinate &start, unsigned long long time, CreatureObject *target)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
void checkNewAngle ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setNextPosition (float x, float z, float y, SceneObject *cell=NULL)
void notifyPositionUpdate (QuadTreeEntry *entry)
void updateCurrentPosition (PatrolPoint *point)
void broadcastNextPositionUpdate (PatrolPoint *point)
void clearPatrolPoints ()
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void loadTemplateData (SharedObjectTemplate *templateData)
void loadTemplateData (CreatureTemplate *templateData)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
void sendConversationStartTo (SceneObject *player)
void sendDefaultConversationTo (SceneObject *player)
void selectConversationOption (int option, SceneObject *obj)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
int notifyConverseObservers (CreatureObject *converser)
int notifyAttack (Observable *observable)
int notifyCallForHelp (Observable *observable, ManagedObject *arg1)
void destroyObjectFromWorld (bool sendSelfDestroy)
void activatePostureRecovery ()
void queueDizzyFallEvent ()
void clearCombatState (bool clearDefenders=true)
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
void setDespawnOnNoPlayerInRange (bool val)
virtual void notifyDespawn (Zone *zone)
virtual void scheduleDespawn ()
virtual void scheduleDespawn (int timeToDespawn)
void respawn (Zone *zone, int level)
void addPatrolPoint (PatrolPoint &point)
void setHomeLocation (float x, float z, float y, SceneObject *cell=NULL)
void setRespawnTimer (float resp)
void setRandomRespawn (bool resp)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
void setOblivious ()
void setWatchObject (SceneObject *obj)
void setStalkObject (SceneObject *obj)
void setFollowObject (SceneObject *obj)
void setTargetObject (SceneObject *obj)
SceneObject * getFollowObject ()
void selectWeapon ()
bool validateStateAttack (CreatureObject *target, String &args)
bool isRetreating ()
bool isFleeing ()
void clearDespawnEvent ()
float getKinetic ()
float getEnergy ()
float getElectricity ()
float getStun ()
float getBlast ()
float getHeat ()
float getCold ()
float getAcid ()
float getLightSaber ()
bool isStalker ()
bool isKiller ()
unsigned int getFerocity ()
unsigned int getArmor ()
bool getDespawnOnNoPlayerInRange ()
int getNumberOfPlayersInRange ()
String getFactionString ()
String getSocialGroup ()
float getChanceHit ()
int getDamageMin ()
int getDamageMax ()
int getBaseXp ()
unsigned int getDiet ()
CreatureAttackMap * getAttackMap ()
LootGroupCollection * getLootGroups ()
float getRespawnTimer ()
bool getRandomRespawn ()
PatrolPoint * getHomeLocation ()
bool isAiAgent ()
CreatureTemplate * getCreatureTemplate ()
bool hasLoot ()
void setShowNextPosition (bool val)
bool isEventMob ()
String getPvPFaction ()
int getBehaviorStatus (Behavior *b)
void setBehaviorStatus (Behavior *b, int status)
void addBehaviorToTree (BehaviorTree *tree, Behavior *b)
Behavior * getNextBehaviorFromTree (BehaviorTree *tree)
void resetBehaviorList (BehaviorTree *tree)
operator const AiAgent * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::CreatureObjectImplementation
CreatureObjectImplementation ()
CreatureObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
void finalize ()
void createChildObjects ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void clearQueueAction (unsigned int actioncntr, float timer=0, unsigned int tab1=0, unsigned int tab2=0)
void sendBaselinesTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendTo (SceneObject *player, bool doClose)
void sendSystemMessage (const String &message)
void playMusicMessage (const String &file)
void sendNewbieTutorialRequest (const String &request)
void sendNewbieTutorialEnableHudElement (const String &ui, bool enable=true)
void sendOpenHolocronToPageMessage ()
void sendSystemMessage (UnicodeString &message)
void sendSystemMessage (StringIdChatParameter &stringid)
void sendSlottedObjectsTo (SceneObject *player)
void setCombatState ()
void clearCombatState (bool clearDefenders=true)
virtual void setPosture (int newPosture, bool notifyClient=true)
float calculateSpeed ()
virtual void updateLocomotion ()
void setHeight (float heigh, bool notifyClient=true)
void setAccelerationMultiplierBase (float newMultiplierBase, bool notifyClient=true)
void setAccelerationMultiplierMod (float newMultiplierMod, bool notifyClient=true)
void setSpeedMultiplierBase (float newMultiplierBase, bool notifyClient=true)
virtual void setSpeedMultiplierMod (float newMultiplierMod, bool notifyClient=true)
virtual void setTurnScale (float newMultiplierMod, bool notifyClient=true)
void setRunSpeed (float newSpeed, bool notifyClient=true)
void setCurrentSpeed (float newSpeed)
void setHAM (int type, int value, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
bool hasDamage (int attribute)
int healDamage (TangibleObject *healer, int damageType, int damage, bool notifyClient=true, bool notifyObservers=true)
int healWound (TangibleObject *healer, int damageType, int damage, bool notifyClient=true, bool notifyObservers=true)
void setBaseHAM (int type, int value, bool notifyClient=true)
void setWounds (int type, int value, bool notifyClient=true)
int addWounds (int type, int value, bool notifyClient=true)
void setMaxHAM (int type, int value, bool notifyClient=true)
void addMaxHAM (int type, int value, bool notifyClient=true)
void setEncumbrance (int type, int value, bool notifyClient=true)
void addEncumbrance (int type, int value, bool notifyClient=true)
void setWeapon (WeaponObject *weao, bool notifyClient=false)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void setInstrumentID (int instrumentid, bool notifyClient=true)
void setListenToID (unsigned long long id, bool notifyClient=true)
void setPerformanceCounter (int counter, bool notifyClient=true)
void setPerformanceAnimation (const String &animation, bool notifyClient=true)
void setShockWounds (int newShock, bool notifyClient=true)
void addShockWounds (int shockToAdd, bool notiyClient=true)
void setTargetID (unsigned long long targetID, bool notifyClient=true)
void setBankCredits (int credits, bool notifyClient=true)
void addBuff (Buff *buff)
bool removeBuff (unsigned int buffcrc)
void removeBuff (Buff *buff)
bool removeStateBuff (unsigned long long state)
void clearBuffs (bool updateclient)
void addWearableObject (TangibleObject *object, bool notifyClient=true)
void removeWearableObject (TangibleObject *object, bool notifyClient=true)
WearablesDeltaVector * getWearablesDeltaVector ()
void sendBuffsTo (CreatureObject *creature)
BuffList * getBuffList ()
Buff * getBuff (unsigned int buffcrc)
long long getSkillModFromBuffs (const String &skillMod)
int addDotState (unsigned long long dotType, unsigned long long objectID, unsigned int strength, byte type, unsigned int duration, float potency, unsigned int defense, int secondaryStrength=0)
bool healDot (unsigned long long dotType, int reduction)
void clearDots ()
DamageOverTimeList * getDamageOverTimeList ()
bool hasBuff (unsigned int buffcrc)
void notifySelfPositionUpdate ()
void notifyPostureChange (int newPosture)
void setLevel (int level)
void updateToDatabaseAllObjects (bool startTask)
bool isResuscitable ()
void addBankCredits (int credits, bool notifyClient=true)
void addCashCredits (int credits, bool notifyClient=true)
void subtractBankCredits (int credits)
void subtractCashCredits (int credits)
bool verifyCashCredits (int credits)
bool verifyBankCredits (int credits)
bool isDancing ()
bool isPlayingMusic ()
void stopEntertaining ()
bool isEntertaining ()
void setCashCredits (int credits, bool notifyClient=true)
void setTerrainNegotiation (float value, bool notifyClient=true)
void addSkill (Skill *skill, bool notifyClient=true)
void addSkill (const String &skill, bool notifyClient=true)
void removeSkill (Skill *skill, bool notifyClient=true)
void removeSkill (const String &skill, bool notifyClient=true)
void addSkillMod (const int modType, const String &skillMod, int value, bool notifyClient=true)
void removeSkillMod (const int modType, const String &skillMod, int value, bool notifyClient=true)
void removeAllSkillModsOfType (const int modType, bool notifyClient=true)
void updateGroupInviterID (unsigned long long id, bool notifyClient=true)
void updateGroup (GroupObject *group, bool notifyClient=true)
void enqueueCommand (unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString &arguments, int priority=-1)
void setMood (byte moodID, bool notifyClient=true)
void setMoodString (const String &animation, bool notifyClient=true)
void deleteQueueAction (unsigned int actionCount)
bool setState (unsigned long long state, bool notifyClient=true)
bool clearState (unsigned long long state, bool notifyClient=true)
void setControlDevice (ControlDevice *device)
void setCreatureLink (CreatureObject *object, bool notifyClient=true)
void executeObjectControllerAction (unsigned int actionCRC)
void executeObjectControllerAction (unsigned int actionCRC, unsigned long long targetID, const UnicodeString &args)
bool isAttackableBy (CreatureObject *object)
bool isAttackableBy (TangibleObject *attacker)
bool isHealableBy (CreatureObject *object)
bool isInBountyMission (CreatureObject *bountyHunter, CreatureObject *target)
void sendMessage (BasePacket *msg)
void sendExecuteConsoleCommand (const String &command)
bool isAggressiveTo (CreatureObject *object)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
int notifyObjectKillObservers (TangibleObject *killer)
void notifyLoadFromDatabase ()
void setFactionRank (int rank, bool notifyClient=true)
String getFirstName ()
String getLastName ()
bool isOnline ()
bool canTreatInjuries ()
bool canTreatStates ()
bool canTreatWounds ()
bool canTreatConditions ()
Reference< PlayerObject * > getPlayerObject ()
AiActor * getActorObject ()
bool isListening ()
bool isWatching ()
void setClient (ZoneClientSession *cli)
void dismount ()
float calculateBFRatio ()
void setDizziedState (int durationSeconds=5)
void setRalliedState (int durationSeconds=5)
void setAimingState (int durationSeconds=5)
void setCoverState (int durationSeconds=40)
void setBerserkedState (unsigned int duration)
void setStunnedState (int durationSeconds=5)
void setBlindedState (int durationSeconds=5)
void setIntimidatedState (unsigned int mod, int durationSeconds=15)
void setSnaredState (int durationSeconds=20)
void setRootedState (int durationSeconds=20)
bool setNextAttackDelay (unsigned int mod, int del)
void setMeditateState ()
virtual void activateHAMRegeneration ()
virtual void activatePassiveWoundRegeneration ()
virtual void activateStateRecovery ()
void updateTimeOfDeath ()
bool hasAttackDelay ()
void removeAttackDelay ()
CooldownTimerMap * getCooldownTimerMap ()
bool hasSpice ()
void updateLastSuccessfulCombatAction ()
void updateKnockdownRecovery ()
void updateLastKnockdown ()
bool checkKnockdownRecovery ()
bool checkLastKnockdown ()
void updatePostureDownRecovery ()
void updatePostureUpRecovery ()
bool checkPostureDownRecovery ()
unsigned long long getScreenPlayState (const String &screenPlay)
void setScreenPlayState (const String &screenPlay, unsigned long long state)
bool checkPostureUpRecovery ()
void updateCooldownTimer (const String &coooldownTimer, unsigned int miliSecondsToAdd=0)
bool checkCooldownRecovery (const String &cooldown)
Time * getCooldownTime (const String &cooldown)
void addCooldown (const String &name, unsigned int miliseconds)
void doAnimation (const String &animation)
void doCombatAnimation (CreatureObject *defender, unsigned int animationCRC, byte hit, byte trails)
void playEffect (const String &file, const String &aux)
void playEffect (const String &file)
void activateQueueAction ()
void activateImmediateAction ()
UnicodeString getCreatureName ()
bool isGrouped ()
int getBankCredits ()
int getCashCredits ()
int getBaseHAM (int idx)
int getWounds (int idx)
DeltaVector< int > * getWounds ()
int getHAM (int idx)
DeltaVector< int > * getHAM ()
int getMaxHAM (int idx)
DeltaVector< int > * getMaxHAM ()
int getEncumbrance (int idx)
DeltaVector< int > * getEncumbrances ()
byte getPosture ()
byte getLocomotion ()
byte getFactionRank ()
ManagedWeakReference
< CreatureObject * > getLinkedCreature ()
unsigned long long getCreatureLinkID ()
float getShockWounds ()
unsigned long long getWatchToID ()
unsigned long long getStateBitmask ()
bool hasState (unsigned long long state)
bool hasStates ()
unsigned long long getListenID ()
float getAccelerationMultiplierBase ()
float getAccelerationMultiplierMod ()
float getSpeedMultiplierBase ()
float getSpeedMultiplierMod ()
float getCurrentSpeed ()
SpeedMultiplierModChanges * getSpeedMultiplierModChanges ()
CommandQueueActionVector * getCommandQueue ()
float getRunSpeed ()
float getWalkSpeed ()
float getTurnScale ()
float getTerrainNegotiation ()
float getRunAcceleration ()
float getWalkAcceleration ()
String getPerformanceAnimation ()
String getMoodString ()
unsigned long long getWeaponID ()
Reference< WeaponObject * > getWeapon ()
Reference< GuildObject * > getGuildObject ()
int getGuildID ()
bool isInGuild ()
void setGuildObject (GuildObject *guildobj)
unsigned long long getGroupID ()
unsigned long long getGroupInviterID ()
GroupObject * getGroup ()
unsigned long long getGroupInviteCounter ()
unsigned long long getTargetID ()
byte getMoodID ()
float getSlopeModPercent ()
int getPerformanceCounter ()
int getInstrumentID ()
byte getFrozen ()
float getHeight ()
int getSpecies ()
String getSpeciesName ()
int getGender ()
DeltaVector< int > * getBaseHAM ()
SkillList * getSkillList ()
int getSkillMod (const String &skillmod)
bool hasSkill (const String &skill)
SkillModList * getSkillModList ()
void setWatchToID (unsigned long long id)
bool isCreatureObject ()
bool isNextActionPast ()
virtual bool isTrainerCreature ()
bool isSwimming ()
ZoneClientSession * getClient ()
bool isRidingMount ()
ManagedWeakReference
< ControlDevice * > getControlDevice ()
float getSwimHeight ()
bool isIncapacitated ()
bool isDead ()
bool isKnockedDown ()
bool isKneeling ()
bool isProne ()
bool isStanding ()
bool isSitting ()
bool isSkillAnimating ()
bool isRallied ()
bool isInCombat ()
bool isDizzied ()
bool isBerserked ()
bool isStunned ()
bool isBlinded ()
bool isIntimidated ()
bool isSnared ()
bool isImmobilized ()
bool isRooted ()
bool isFrozen ()
bool isDiseased ()
bool isPoisoned ()
bool isBleeding ()
bool isOnFire ()
bool isMounted ()
bool isRidingCreature ()
bool isPeaced ()
bool isMeditating ()
bool isAiming ()
bool isInCover ()
bool isRunning ()
virtual bool isNonPlayerCreatureObject ()
virtual bool isCreature ()
bool isPlayerCreature ()
bool isAiActor ()
virtual bool isInformantCreature ()
CampSiteActiveArea * getCurrentCamp ()
byte getCurrentWeather ()
void setCurrentWeather (byte value)
byte getCurrentWind ()
void setCurrentWind (byte value)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void destroyObjectFromWorld (bool sendSelfDestroy)
bool isInvisible ()
void setInvisible (bool invis)
Mutex * getSkillModMutex ()
float calculateCostAdjustment (byte stat, float baseCost)
void updateSpeedAndAccelerationMods ()
operator const CreatureObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
TangibleObjectImplementation ()
TangibleObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
virtual void addTemplateSkillMods (TangibleObject *targetObject)
virtual void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
virtual void removeSkillModsFrom (CreatureObject *creature)
virtual void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
virtual void removeDefenders ()
virtual void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
bool hasDefender (SceneObject *defender)
virtual void sendPvpStatusTo (CreatureObject *player)
virtual int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
virtual void updateCraftingValues (CraftingValues *values, bool firstUpdate)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
virtual bool isTicketCollector ()
virtual bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
virtual int getUseCount ()
virtual int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
virtual bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
virtual String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
virtual int getJunkDealerNeeded ()
void setJunkValue (int jValue)
virtual int getJunkValue ()
void setSerialNumber (const String &serial)
virtual String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
virtual String repairAttempt (int repairChance)
bool isBroken ()
virtual float getHitChance ()
void broadcastPvpStatusBitmask ()
operator const TangibleObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< AiAgent * > _this
Public Attributes inherited from server::zone::objects::creature::CreatureObjectImplementation
WeakReference< CreatureObject * > _this
Public Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
WeakReference< TangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Static Public Attributes
static const int UPDATEMOVEMENTINTERVAL = 500
static unsigned const int OBLIVIOUS = 0
static unsigned const int WATCHING = 1
static unsigned const int STALKING = 2
static unsigned const int FOLLOWING = 3
static unsigned const int PATROLING = 4
Static Public Attributes inherited from server::zone::objects::creature::CreatureObjectImplementation
static const int HUMAN = 0
static const int RODIAN = 1
static const int TRANDOSHAN = 2
static const int MONCAL = 3
static const int WOOKIE = 4
static const int BOTHAN = 5
static const int TWILEK = 6
static const int ZABRAK = 7
static const int ITHORIAN = 0x21
static const int SULLUSTAN = 0x31
static const int MALE = 0
static const int FEMALE = 1
static float DEFAULTRUNSPEED = 5.376
static unsigned const long long DEAD_TOO_LONG = 1800000
Protected Member Functions
bool findNextPosition (float maxDistance, WorldCoordinates *nextPosition)
virtual ~AiAgentImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::CreatureObjectImplementation
virtual ~CreatureObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
float getConditionReduction (float value)
virtual ~TangibleObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
Reference< AiThinkEvent * > thinkEvent
Reference< AiMoveEvent * > moveEvent
Reference< AiWaitEvent * > waitEvent
Reference< AiAwarenessEvent * > awarenessEvent
ReadWriteLock despawnMutex
Vector< AiInterfaceComponent * > aiInterfaceComponents
Vector< String > skillCommands
PatrolPointsVector patrolPoints
PatrolPoint homeLocation
PatrolPoint nextStepPosition
Reference< CurrentFoundPath * > currentFoundPath
ManagedReference< SceneObject * > targetCellObject
Vector< ManagedReference
< WeaponObject * > > weapons
Vector< ManagedReference
< SceneObject * > > camouflagedObjects
CreatureTemplateReference npcTemplate
bool baby
bool showNextMovementPosition
Vector< ManagedReference
< SceneObject * > > movementMarkers
bool despawnOnNoPlayerInRange
ManagedReference< SceneObject * > followObject
unsigned int followState
Mutex targetMutex
Mutex awernessEventMutex
bool fleeing
Time lastDamageReceived
float respawnTimer
bool randomRespawn
int numberOfPlayersInRange
bool loadedOutfit
Reference
< DespawnCreatureOnPlayerDissappear * > despawnEvent
HashTable< Behavior *, int > statuses
HashTable< BehaviorTree
*, BehaviorTreeList * > trees
Protected Attributes inherited from server::zone::objects::creature::CreatureObjectImplementation
ManagedReference
< ZoneClientSession * > owner
int bankCredits
int cashCredits
int gender
int species
DeltaVector< int > baseHAM
byte posture
byte locomotion
byte factionRank
bool invisible
ManagedWeakReference
< CreatureObject * > linkedCreature
ManagedWeakReference
< ControlDevice * > controlDevice
float shockWounds
DeltaVector< int > wounds
unsigned long long stateBitmask
DeltaVector< int > encumbrances
WearablesDeltaVector wearablesVector
float accelerationMultiplierBase
float accelerationMultiplierMod
float speedMultiplierBase
SpeedMultiplierModChanges speedMultiplierModChanges
float speedMultiplierMod
float turnScale
float runSpeed
float walkSpeed
float currentSpeed
float terrainNegotiation
float runAcceleration
float walkAcceleration
float height
float swimHeight
float slopeModPercent
float slopeModAngle
unsigned long long listenToID
unsigned long long watchToID
String performanceAnimation
String moodString
ManagedReference< WeaponObject * > weapon
ManagedReference< GroupObject * > group
unsigned long long groupInviterID
unsigned long long groupInviteCounter
ManagedReference< GuildObject * > guild
unsigned long long targetID
byte moodID
int performanceCounter
int instrumentID
DeltaVector< int > hamList
DeltaVector< int > maxHamList
byte frozen
String templateString
SkillList skillList
SkillModList skillModList
Mutex skillModMutex
Reference
< CommandQueueActionVector * > commandQueue
Reference
< CommandQueueActionVector * > immediateQueue
Time nextAction
Reference< CooldownTimerMap * > cooldownTimerMap
BuffList creatureBuffs
DamageOverTimeList damageOverTimeList
Time lastSuccessfulCombatAction
Time timeOfDeath
VectorMap< String, unsigned
long long > screenPlayStates
byte healthWoundHeal
byte actionWoundHeal
byte mindWoundHeal
byte currentWeather
byte currentWind
Time lastCombatActionTime
Vector3 lastCombatPosition
Protected Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
bool targetable
float complexity
int volume
unsigned int faction
CustomizationVariables customizationVariables
float conditionDamage
int maxCondition
int useCount
short level
unsigned int optionsBitmask
unsigned int pvpStatusBitmask
byte unknownByte
String craftersName
int junkDealerNeeded
int junkValue
String objectSerial
Reference< ThreatMap * > threatMap
DeltaVector< ManagedReference
< SceneObject * > > defenderList
bool sliceable
bool sliced
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Friends
class AiAgent
Detailed Description
Definition at line 662 of file AiAgent.h.
Constructor & Destructor Documentation
AiAgentImplementation::AiAgentImplementation ()
Definition at line 1787 of file AiAgent.cpp.
References _initializeImplementation(), baby, despawnOnNoPlayerInRange, fleeing, followState, loadedOutfit, numberOfPlayersInRange, OBLIVIOUS, randomRespawn, respawnTimer, and showNextMovementPosition.
AiAgentImplementation::AiAgentImplementation (DummyConstructorParameter * param)
Definition at line 1459 of file AiAgent.cpp.
References _initializeImplementation().
AiAgentImplementation::~AiAgentImplementation () protected virtual
Definition at line 1464 of file AiAgent.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * AiAgentImplementation::_getStub ()
Definition at line 1482 of file AiAgent.cpp.
References _this.
void AiAgentImplementation::_initializeImplementation () protected
Definition at line 1469 of file AiAgent.cpp.
References _serializationHelperMethod(), and _this.
Referenced by AiAgentImplementation().
void AiAgentImplementation::_serializationHelperMethod () protected
Definition at line 1518 of file AiAgent.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation(), server::zone::objects::creature::NonPlayerCreatureObjectImplementation::_serializationHelperMethod(), and server::zone::objects::creature::CreatureImplementation::_serializationHelperMethod().
void AiAgentImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 1477 of file AiAgent.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::NonPlayerCreatureObjectImplementation::_setStub(), server::zone::objects::creature::CreatureImplementation::_setStub(), and server::zone::objects::creature::AiAgent::AiAgent().
void AiAgentImplementation::activateAwarenessEvent (CreatureObject * target)
Definition at line 802 of file AiAgentImplementation.cpp.
References _this, awarenessEvent, awernessEventMutex, and server::zone::objects::scene::SceneObjectImplementation::info().
Referenced by server::zone::objects::creature::AiAgent::activateAwarenessEvent().
void AiAgentImplementation::activateMovementEvent () virtual
Definition at line 1357 of file AiAgentImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::getZone(), moveEvent, and UPDATEMOVEMENTINTERVAL.
Referenced by server::zone::objects::creature::AiAgent::activateMovementEvent(), doMovement(), server::zone::objects::creature::CreatureImplementation::runAway(), setFollowObject(), setOblivious(), setStalkObject(), setWatchObject(), and tryRetreat().
void AiAgentImplementation::activatePostureRecovery ()
Definition at line 840 of file AiAgentImplementation.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::executeObjectControllerAction(), server::zone::objects::creature::CreatureObjectImplementation::isKneeling(), server::zone::objects::creature::CreatureObjectImplementation::isKnockedDown(), and server::zone::objects::creature::CreatureObjectImplementation::isProne().
Referenced by server::zone::objects::creature::AiAgent::activatePostureRecovery(), and doRecovery().
void AiAgentImplementation::activateRecovery () virtual
Definition at line 829 of file AiAgentImplementation.cpp.
References _this, and thinkEvent.
Referenced by server::zone::objects::creature::AiAgent::activateRecovery(), addDefender(), doAttack(), doRecovery(), inflictDamage(), removeDefender(), and setDefender().
void AiAgentImplementation::activateWaitEvent () virtual
Definition at line 1375 of file AiAgentImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::getZone(), UPDATEMOVEMENTINTERVAL, and waitEvent.
Referenced by server::zone::objects::creature::AiAgent::activateWaitEvent().
void AiAgentImplementation::addBehaviorToTree (BehaviorTree * tree, Behavior * b)
Definition at line 1853 of file AiAgentImplementation.cpp.
References trees.
Referenced by server::zone::objects::creature::AiAgent::addBehaviorToTree().
void AiAgentImplementation::addDefender (SceneObject * defender) virtual
Adds a SceneObject to the defender vector
Precondition
{ this object is locked }
Postcondition
{ this object is locked, defender is in the defender vector }
Parameters
defender SceneObject to add to the defender vector
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 607 of file AiAgentImplementation.cpp.
References activateRecovery(), server::zone::objects::tangible::TangibleObjectImplementation::addDefender(), server::zone::objects::tangible::TangibleObjectImplementation::defenderList, FOLLOWING, followState, server::zone::objects::scene::SceneObjectImplementation::showFlyText(), server::zone::objects::scene::variables::DeltaVector< E >::size(), and STALKING.
Referenced by server::zone::objects::creature::AiAgent::addDefender(), and doAttack().
void AiAgentImplementation::addPatrolPoint (PatrolPoint & point)
Definition at line 1851 of file AiAgent.cpp.
References patrolPoints, and targetMutex.
Referenced by server::zone::objects::creature::AiAgent::addPatrolPoint().
void AiAgentImplementation::broadcastNextPositionUpdate (PatrolPoint * point)
Definition at line 1400 of file AiAgentImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), PatrolPoint::getCell(), server::zone::objects::scene::SceneObject::getObjectID(), PatrolPoint::getPositionX(), PatrolPoint::getPositionY(), PatrolPoint::getPositionZ(), and server::zone::objects::scene::SceneObjectImplementation::movementCounter.
Referenced by server::zone::objects::creature::AiAgent::broadcastNextPositionUpdate(), checkNewAngle(), doMovement(), and sendConversationStartTo().
int AiAgentImplementation::calculateAttackMaxDamage (int level)
Definition at line 67 of file AiAgentImplementation.cpp.
References calculateAttackMinDamage(), and npcTemplate.
Referenced by server::zone::objects::creature::AiAgent::calculateAttackMaxDamage(), loadTemplateData(), and setLevel().
int AiAgentImplementation::calculateAttackMinDamage (int level)
Definition at line 61 of file AiAgentImplementation.cpp.
References npcTemplate.
Referenced by calculateAttackMaxDamage(), server::zone::objects::creature::AiAgent::calculateAttackMinDamage(), loadTemplateData(), and setLevel().
float AiAgentImplementation::calculateAttackSpeed (int level)
Definition at line 73 of file AiAgentImplementation.cpp.
Referenced by server::zone::objects::creature::AiAgent::calculateAttackSpeed(), loadTemplateData(), and setLevel().
void AiAgentImplementation::checkNewAngle ()
Definition at line 867 of file AiAgentImplementation.cpp.
References broadcastNextPositionUpdate(), server::zone::objects::scene::SceneObjectImplementation::faceObject(), followObject, server::zone::objects::scene::SceneObjectImplementation::getParent(), server::zone::objects::scene::SceneObjectImplementation::isCellObject(), PatrolPoint::isReached(), server::zone::objects::scene::SceneObjectImplementation::movementCounter, nextStepPosition, server::zone::objects::scene::SceneObjectImplementation::updateZone(), and server::zone::objects::scene::SceneObjectImplementation::updateZoneWithParent().
Referenced by server::zone::objects::creature::AiAgent::checkNewAngle(), and doMovement().
void AiAgentImplementation::clearCombatState (bool clearDefenders = true) virtual
Cleares the combat state
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object is not in a combat state }
Parameters
clearDefenders if true the defender vector willl be emptied
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 653 of file AiAgentImplementation.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::clearCombatState(), setOblivious(), and server::zone::objects::tangible::TangibleObjectImplementation::threatMap.
Referenced by server::zone::objects::creature::AiAgent::clearCombatState().
void AiAgentImplementation::clearDespawnEvent ()
Definition at line 672 of file AiAgentImplementation.cpp.
References despawnEvent.
Referenced by server::zone::objects::creature::AiAgent::clearDespawnEvent().
void AiAgentImplementation::clearPatrolPoints ()
Definition at line 1825 of file AiAgent.cpp.
References patrolPoints, and targetMutex.
Referenced by server::zone::objects::creature::AiAgent::clearPatrolPoints(), and setTargetObject().
void AiAgentImplementation::destroyObjectFromWorld (bool sendSelfDestroy) virtual
Destroys the object from the world
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 1834 of file AiAgent.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::destroyObjectFromWorld(), and moveEvent.
Referenced by server::zone::objects::creature::AiAgent::destroyObjectFromWorld().
void AiAgentImplementation::doAttack ()
Definition at line 327 of file AiAgentImplementation.cpp.
References _this, activateRecovery(), addDefender(), server::zone::objects::creature::CreatureObjectImplementation::commandQueue, server::zone::objects::scene::variables::DeltaVector< E >::contains(), server::zone::objects::tangible::TangibleObjectImplementation::defenderList, server::zone::objects::creature::CreatureObjectImplementation::enqueueCommand(), followObject, server::zone::objects::scene::variables::DeltaVector< E >::get(), CreatureAttackMap::getArguments(), CreatureAttackMap::getCommand(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::objects::tangible::threat::ThreatMap::getHighestThreatCreature(), server::zone::objects::scene::SceneObject::getObjectID(), CreatureAttackMap::getRandomAttackNumber(), server::zone::objects::tangible::TangibleObjectImplementation::getThreatMap(), server::zone::objects::creature::CreatureObject::hasState(), server::zone::objects::creature::CreatureObject::isAttackableBy(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObjectImplementation::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::creature::CreatureObjectImplementation::isInCombat(), server::zone::objects::scene::SceneObject::isInRange(), lastDamageReceived, server::zone::objects::tangible::TangibleObjectImplementation::level, npcTemplate, CreatureState::PEACE, removeDefender(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefenders(), selectWeapon(), setDefender(), setFollowObject(), server::zone::objects::scene::variables::DeltaVector< E >::size(), tryRetreat(), and validateStateAttack().
Referenced by server::zone::objects::creature::AiAgent::doAttack(), doMovement(), and doRecovery().
void AiAgentImplementation::doAwarenessCheck (Coordinate & start, unsigned long long time, CreatureObject * target)
Definition at line 303 of file AiAgentImplementation.cpp.
References _this, and aiInterfaceComponents.
Referenced by server::zone::objects::creature::AiAgent::doAwarenessCheck().
void AiAgentImplementation::doMovement ()
Definition at line 1161 of file AiAgentImplementation.cpp.
References _this, activateMovementEvent(), broadcastNextPositionUpdate(), CollisionManager::checkLineOfSight(), checkNewAngle(), server::zone::objects::creature::CreatureObjectImplementation::currentSpeed, ObserverEventType::DESTINATIONREACHED, server::zone::objects::scene::SceneObjectImplementation::direction, doAttack(), findNextPosition(), fleeing, server::zone::objects::creature::AiAgent::FOLLOWING, followObject, followState, WorldCoordinates::getCell(), server::zone::objects::scene::SceneObjectImplementation::getParent(), server::zone::objects::creature::CreatureObjectImplementation::getWeapon(), PatrolPoint::getWorldPosition(), server::zone::objects::scene::SceneObjectImplementation::getWorldPosition(), WorldCoordinates::getX(), WorldCoordinates::getY(), WorldCoordinates::getZ(), server::zone::objects::scene::SceneObjectImplementation::getZone(), homeLocation, server::zone::objects::creature::CreatureObjectImplementation::isDead(), isFleeing(), isRetreating(), server::zone::objects::creature::CreatureObjectImplementation::isStanding(), nextStepPosition, server::zone::objects::creature::AiAgent::OBLIVIOUS, patrolPoints, PatrolPoint::setCell(), server::zone::objects::scene::SceneObjectImplementation::setDirection(), setFollowObject(), setNextPosition(), setOblivious(), PatrolPoint::setPosition(), PatrolPoint::setReached(), server::zone::objects::creature::AiAgent::STALKING, updateCurrentPosition(), server::zone::objects::creature::CreatureObjectImplementation::updateLocomotion(), UPDATEMOVEMENTINTERVAL, and server::zone::objects::creature::AiAgent::WATCHING.
Referenced by server::zone::objects::creature::AiAgent::doMovement().
void AiAgentImplementation::doRecovery ()
Definition at line 310 of file AiAgentImplementation.cpp.
References _this, DamageOverTimeList::activateDots(), server::zone::objects::creature::CreatureObjectImplementation::activateHAMRegeneration(), activatePostureRecovery(), activateRecovery(), server::zone::objects::creature::CreatureObjectImplementation::activateStateRecovery(), server::zone::objects::creature::CreatureObjectImplementation::damageOverTimeList, doAttack(), server::zone::objects::scene::SceneObjectImplementation::getZone(), DamageOverTimeList::hasDot(), server::zone::objects::creature::CreatureObjectImplementation::isDead(), and DamageOverTimeList::isNextTickPast().
Referenced by server::zone::objects::creature::AiAgent::doRecovery().
void AiAgentImplementation::fillAttributeList (AttributeListMessage * msg, CreatureObject * object) virtual
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::creature::CreatureImplementation.
Definition at line 1476 of file AiAgentImplementation.cpp.
References getAcid(), getArmor(), getBlast(), getCold(), getElectricity(), getEnergy(), getHeat(), getKinetic(), getLightSaber(), getStun(), server::zone::packets::scene::AttributeListMessage::insertAttribute(), and server::zone::objects::creature::CreatureObjectImplementation::isDead().
Referenced by server::zone::objects::creature::CreatureImplementation::fillAttributeList(), and server::zone::objects::creature::AiAgent::fillAttributeList().
void AiAgentImplementation::finalize ()
Definition at line 1817 of file AiAgent.cpp.
Referenced by ~AiAgentImplementation().
bool AiAgentImplementation::findNextPosition (float maxDistance, WorldCoordinates * nextPosition) protected
Definition at line 885 of file AiAgentImplementation.cpp.
References _this, CreateClientPathMessage::addCoordinate(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), server::zone::ZoneServer::createObject(), currentFoundPath, PathFinderManager::filterPastPoints(), server::zone::managers::planet::PlanetManager::findClosestWorldFloor(), PathFinderManager::findPath(), followObject, CreatureState::FROZEN, WorldCoordinates::getCell(), PatrolPoint::getCell(), PatrolPoint::getCoordinates(), PathFinderManager::getFloorMesh(), PathFinderManager::getFloorPath(), server::zone::Zone::getHeight(), server::zone::objects::creature::CreatureObjectImplementation::getHeight(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObjectImplementation::getParent(), server::zone::Zone::getPlanetManager(), WorldCoordinates::getPoint(), PatrolPoint::getPositionX(), PatrolPoint::getPositionY(), PatrolPoint::getPositionZ(), server::zone::objects::creature::CreatureObjectImplementation::getSwimHeight(), WorldCoordinates::getWorldPosition(), PatrolPoint::getWorldPosition(), server::zone::objects::scene::SceneObjectImplementation::getWorldPosition(), WorldCoordinates::getX(), WorldCoordinates::getY(), WorldCoordinates::getZ(), server::zone::objects::scene::SceneObjectImplementation::getZone(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), server::zone::objects::creature::CreatureObjectImplementation::hasState(), CreatureState::IMMOBILIZED, movementMarkers, patrolPoints, server::zone::objects::creature::CreatureObjectImplementation::runSpeed, WorldCoordinates::setCell(), PatrolPoint::setPositionZ(), WorldCoordinates::setX(), WorldCoordinates::setY(), WorldCoordinates::setZ(), showNextMovementPosition, targetCellObject, targetMutex, server::zone::objects::scene::SceneObject::transferObject(), PathFinderManager::transformToModelSpace(), UPDATEMOVEMENTINTERVAL, and server::zone::objects::scene::SceneObjectImplementation::zone.
Referenced by doMovement().
float AiAgentImplementation::getAcid ()
Definition at line 2058 of file AiAgent.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::AiAgent::getAcid().
unsigned int AiAgentImplementation::getArmor ()
Definition at line 2098 of file AiAgent.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::AiAgent::getArmor().
CreatureAttackMap * AiAgentImplementation::getAttackMap ()
Definition at line 2178 of file AiAgent.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::CreatureImplementation::fillAttributeList(), and server::zone::objects::creature::AiAgent::getAttackMap().
int AiAgentImplementation::getBaseXp ()
Definition at line 2162 of file AiAgent.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::AiAgent::getBaseXp().
int AiAgentImplementation::getBehaviorStatus (Behavior * b)
Definition at line 1847 of file AiAgentImplementation.cpp.
References statuses.
Referenced by server::zone::objects::creature::AiAgent::getBehaviorStatus().
float AiAgentImplementation::getBlast ()
Definition at line 2034 of file AiAgent.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::AiAgent::getBlast().
float AiAgentImplementation::getChanceHit ()
Definition at line 2132 of file AiAgent.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::CreatureImplementation::fillAttributeList(), and server::zone::objects::creature::AiAgent::getChanceHit().
float AiAgentImplementation::getCold ()
Definition at line 2050 of file AiAgent.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::AiAgent::getCold().
CreatureTemplate * AiAgentImplementation::getCreatureTemplate ()
Definition at line 2214 of file AiAgent.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::AiAgent::getCreatureTemplate().
int AiAgentImplementation::getDamageMax ()
Definition at line 2151 of file AiAgent.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::getWeapon(), and npcTemplate.
Referenced by server::zone::objects::creature::CreatureImplementation::fillAttributeList(), and server::zone::objects::creature::AiAgent::getDamageMax().
int AiAgentImplementation::getDamageMin ()
Definition at line 2140 of file AiAgent.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::getWeapon(), and npcTemplate.
Referenced by server::zone::objects::creature::CreatureImplementation::fillAttributeList(), and server::zone::objects::creature::AiAgent::getDamageMin().
bool AiAgentImplementation::getDespawnOnNoPlayerInRange ()
Definition at line 2106 of file AiAgent.cpp.
References despawnOnNoPlayerInRange.
Referenced by server::zone::objects::creature::AiAgent::getDespawnOnNoPlayerInRange().
unsigned int AiAgentImplementation::getDiet ()
Definition at line 2170 of file AiAgent.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::AiAgent::getDiet().
float AiAgentImplementation::getElectricity ()
Definition at line 2018 of file AiAgent.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::AiAgent::getElectricity().
float AiAgentImplementation::getEnergy ()
Definition at line 2010 of file AiAgent.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::AiAgent::getEnergy().
String AiAgentImplementation::getFactionString ()
Definition at line 2116 of file AiAgent.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::AiAgent::getFactionString().
unsigned int AiAgentImplementation::getFerocity ()
Definition at line 2090 of file AiAgent.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::CreatureImplementation::fillAttributeList(), and server::zone::objects::creature::AiAgent::getFerocity().
SceneObject * AiAgentImplementation::getFollowObject ()
Definition at line 1987 of file AiAgent.cpp.
References followObject.
Referenced by server::zone::objects::creature::AiAgent::getFollowObject().
float AiAgentImplementation::getHeat ()
Definition at line 2042 of file AiAgent.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::AiAgent::getHeat().
PatrolPoint * AiAgentImplementation::getHomeLocation ()
Definition at line 2204 of file AiAgent.cpp.
References homeLocation.
Referenced by server::zone::objects::creature::AiAgent::getHomeLocation().
float AiAgentImplementation::getKinetic ()
Definition at line 2002 of file AiAgent.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::AiAgent::getKinetic().
float AiAgentImplementation::getLightSaber ()
Definition at line 2066 of file AiAgent.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::AiAgent::getLightSaber().
LootGroupCollection * AiAgentImplementation::getLootGroups ()
Definition at line 2186 of file AiAgent.cpp.
References LootGroupCollection::get(), LootGroupCollectionEntry::getLootGroups(), and npcTemplate.
Referenced by server::zone::objects::creature::AiAgent::getLootGroups().
Behavior * AiAgentImplementation::getNextBehaviorFromTree (BehaviorTree * tree)
Definition at line 1863 of file AiAgentImplementation.cpp.
References trees.
Referenced by server::zone::objects::creature::AiAgent::getNextBehaviorFromTree().
int AiAgentImplementation::getNumberOfPlayersInRange ()
Definition at line 2111 of file AiAgent.cpp.
References numberOfPlayersInRange.
Referenced by server::zone::objects::creature::AiAgent::getNumberOfPlayersInRange().
String AiAgentImplementation::getPvPFaction ()
Definition at line 2224 of file AiAgent.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::AiAgent::getPvPFaction().
bool AiAgentImplementation::getRandomRespawn ()
Definition at line 2199 of file AiAgent.cpp.
References randomRespawn.
Referenced by server::zone::objects::creature::AiAgent::getRandomRespawn().
float AiAgentImplementation::getRespawnTimer ()
Definition at line 2194 of file AiAgent.cpp.
References respawnTimer.
Referenced by server::zone::objects::creature::AiAgent::getRespawnTimer().
String AiAgentImplementation::getSocialGroup ()
Definition at line 2124 of file AiAgent.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::AiAgent::getSocialGroup().
float AiAgentImplementation::getStun ()
Definition at line 2026 of file AiAgent.cpp.
References npcTemplate.
Referenced by fillAttributeList(), and server::zone::objects::creature::AiAgent::getStun().
int AiAgentImplementation::handleObjectMenuSelect (CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player CreatureObject that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::creature::CreatureImplementation.
Definition at line 451 of file AiAgentImplementation.cpp.
References _this, server::zone::objects::creature::CreatureObject::executeObjectControllerAction(), server::zone::objects::scene::SceneObjectImplementation::getObjectID(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), server::zone::objects::creature::CreatureObjectImplementation::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObjectImplementation::isDead(), and server::zone::managers::player::PlayerManager::lootAll().
Referenced by server::zone::objects::creature::CreatureImplementation::handleObjectMenuSelect(), and server::zone::objects::creature::AiAgent::handleObjectMenuSelect().
bool AiAgentImplementation::hasLoot ()
Definition at line 1664 of file AiAgentImplementation.cpp.
References server::zone::objects::scene::SceneObject::getContainerObjectsSize(), and server::zone::objects::scene::SceneObjectImplementation::getSlottedObject().
Referenced by server::zone::objects::creature::AiAgent::hasLoot().
int AiAgentImplementation::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, bool notifyClient = true) virtual
Inflicts damage into the object
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
unused for now
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 1435 of file AiAgentImplementation.cpp.
References activateRecovery(), server::zone::objects::tangible::threat::ThreatMap::addDamage(), server::zone::objects::tangible::TangibleObjectImplementation::getThreatMap(), server::zone::objects::creature::CreatureObjectImplementation::inflictDamage(), server::zone::objects::scene::SceneObject::isPlayerCreature(), lastDamageReceived, and setDefender().
Referenced by server::zone::objects::creature::AiAgent::inflictDamage().
int AiAgentImplementation::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, const String & xp, bool notifyClient = true) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 1455 of file AiAgentImplementation.cpp.
References activateRecovery(), server::zone::objects::tangible::threat::ThreatMap::addDamage(), server::zone::objects::tangible::TangibleObjectImplementation::getThreatMap(), server::zone::objects::creature::CreatureObjectImplementation::inflictDamage(), server::zone::objects::scene::SceneObject::isPlayerCreature(), lastDamageReceived, and setDefender().
void AiAgentImplementation::initializeTransientMembers ()
Initializes the transient members of SceneObject, must call the inherited object method first.
Precondition
{transient members are not initialized }
Postcondition
{ transient members are initialized }
Definition at line 287 of file AiAgentImplementation.cpp.
References aiInterfaceComponents, and server::zone::objects::creature::CreatureObjectImplementation::initializeTransientMembers().
Referenced by server::zone::objects::creature::NonPlayerCreatureObjectImplementation::initializeTransientMembers(), server::zone::objects::creature::CreatureImplementation::initializeTransientMembers(), server::zone::objects::creature::AiAgent::initializeTransientMembers(), and readObject().
bool AiAgentImplementation::isAggressiveTo (CreatureObject * object) virtual
Evaluates if this creature is aggresive to the object
Precondition
{ }
Postcondition
{ }
Returns
returns true if its aggressive
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 1643 of file AiAgentImplementation.cpp.
References CreatureFlag::AGGRESSIVE, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::tangible::TangibleObjectImplementation::getFaction(), server::zone::objects::player::PlayerObject::getFactionStatus(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::tangible::TangibleObjectImplementation::getPvpStatusBitmask(), isAttackableBy(), and FactionStatus::ONLEAVE.
Referenced by server::zone::objects::creature::CreatureImplementation::fillAttributeList(), and server::zone::objects::creature::AiAgent::isAggressiveTo().
bool AiAgentImplementation::isAiAgent () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 2209 of file AiAgent.cpp.
Referenced by server::zone::objects::creature::AiAgent::isAiAgent().
bool AiAgentImplementation::isAttackableBy (CreatureObject * object) virtual
Evaluates if this object can be attacket by the passed creature object
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns true if the creature object can attack this
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 1879 of file AiAgent.cpp.
References _this, server::zone::objects::tangible::TangibleObjectImplementation::getFaction(), server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::creature::CreatureObjectImplementation::isDead(), isRetreating(), FactionStatus::ONLEAVE, and server::zone::objects::tangible::TangibleObjectImplementation::pvpStatusBitmask.
Referenced by isAggressiveTo(), and server::zone::objects::creature::AiAgent::isAttackableBy().
bool AiAgentImplementation::isCamouflaged (CreatureObject * target) virtual
Reimplemented in server::zone::objects::creature::CreatureImplementation, and server::zone::objects::creature::NonPlayerCreatureObjectImplementation.
Definition at line 1820 of file AiAgent.cpp.
Referenced by server::zone::objects::creature::AiAgent::isCamouflaged().
bool AiAgentImplementation::isConcealed (CreatureObject * target)
Definition at line 1323 of file AiAgentImplementation.cpp.
References _this, camouflagedObjects, server::zone::objects::tangible::TangibleObjectImplementation::getLevel(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::hasState(), server::zone::objects::creature::CreatureObjectImplementation::isCreature(), CreatureState::MASKSCENT, and targetMutex.
Referenced by server::zone::objects::creature::NonPlayerCreatureObjectImplementation::isCamouflaged(), server::zone::objects::creature::CreatureImplementation::isCamouflaged(), and server::zone::objects::creature::AiAgent::isConcealed().
bool AiAgentImplementation::isEventMob ()
Definition at line 1836 of file AiAgentImplementation.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::AiAgent::isEventMob().
bool AiAgentImplementation::isFleeing ()
Definition at line 1997 of file AiAgent.cpp.
References fleeing.
Referenced by doMovement(), and server::zone::objects::creature::AiAgent::isFleeing().
bool AiAgentImplementation::isKiller () virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 2082 of file AiAgent.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::CreatureImplementation::fillAttributeList(), and server::zone::objects::creature::AiAgent::isKiller().
bool AiAgentImplementation::isRetreating ()
Definition at line 1992 of file AiAgent.cpp.
References homeLocation.
Referenced by doMovement(), isAttackableBy(), and server::zone::objects::creature::AiAgent::isRetreating().
bool AiAgentImplementation::isScentMasked (CreatureObject * target)
Definition at line 1292 of file AiAgentImplementation.cpp.
References _this, camouflagedObjects, server::zone::objects::tangible::TangibleObjectImplementation::getLevel(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::hasState(), CreatureState::MASKSCENT, and targetMutex.
Referenced by server::zone::objects::creature::CreatureImplementation::isCamouflaged(), and server::zone::objects::creature::AiAgent::isScentMasked().
bool AiAgentImplementation::isStalker ()
Definition at line 2074 of file AiAgent.cpp.
References npcTemplate.
Referenced by server::zone::objects::creature::CreatureImplementation::fillAttributeList(), and server::zone::objects::creature::AiAgent::isStalker().
void AiAgentImplementation::loadTemplateData (SharedObjectTemplate * templateData) virtual
Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
Precondition
{ templateData is a valid pointer }
Postcondition
{ TangibleObject members are initialized }
Parameters
templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 57 of file AiAgentImplementation.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::loadTemplateData().
Referenced by server::zone::objects::creature::AiAgent::loadTemplateData(), and notifyDespawn().
void AiAgentImplementation::loadTemplateData (CreatureTemplate * templateData)
Definition at line 79 of file AiAgentImplementation.cpp.
References server::zone::objects::scene::variables::DeltaVector< E >::add(), server::zone::objects::creature::CreatureObjectImplementation::baseHAM, calculateAttackMaxDamage(), calculateAttackMinDamage(), calculateAttackSpeed(), server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::objects::scene::variables::DeltaVector< E >::get(), OutfitTangibleObject::getCustomizationVariables(), server::zone::templates::mobile::CreatureTemplate::getCustomName(), server::zone::objects::scene::SceneObjectImplementation::getLoggingName(), MobileOutfit::getObjects(), OutfitTangibleObject::getObjectTemplate(), MobileOutfitGroup::getOutfits(), server::zone::templates::mobile::CreatureTemplate::getScale(), server::zone::objects::scene::SceneObjectImplementation::getSlottedObject(), server::zone::objects::creature::CreatureObjectImplementation::group, server::zone::objects::creature::CreatureObjectImplementation::hamList, server::zone::objects::creature::CreatureObjectImplementation::isCreature(), server::zone::objects::tangible::TangibleObjectImplementation::level, loadedOutfit, server::zone::objects::creature::CreatureObjectImplementation::maxHamList, npcTemplate, server::zone::objects::scene::SceneObjectImplementation::objectName, server::zone::objects::tangible::TangibleObjectImplementation::optionsBitmask, server::zone::objects::scene::variables::DeltaVector< E >::removeAll(), server::zone::objects::scene::SceneObjectImplementation::server, server::zone::objects::tangible::TangibleObjectImplementation::setCustomObjectName(), server::zone::objects::tangible::TangibleObjectImplementation::setFaction(), server::zone::objects::creature::CreatureObjectImplementation::setHeight(), server::zone::objects::scene::SceneObjectImplementation::setLoggingName(), server::zone::objects::tangible::TangibleObjectImplementation::setPvpStatusBitmask(), server::zone::objects::scene::SceneObjectImplementation::transferObject(), and weapons.
void AiAgentImplementation::lock (bool doLock = true) protected
Definition at line 1490 of file AiAgent.cpp.
References _this.
void AiAgentImplementation::lock (ManagedObject * obj) protected
Definition at line 1494 of file AiAgent.cpp.
References _this.
int AiAgentImplementation::notifyAttack (Observable * observable)
Definition at line 441 of file AiAgentImplementation.cpp.
Referenced by server::zone::objects::creature::AiAgent::notifyAttack().
int AiAgentImplementation::notifyCallForHelp (Observable * observable, ManagedObject * arg1)
Definition at line 446 of file AiAgentImplementation.cpp.
Referenced by server::zone::objects::creature::AiAgent::notifyCallForHelp().
int AiAgentImplementation::notifyConverseObservers (CreatureObject * converser)
Is called when an object is talked to
Precondition
{ this, converser locked }
Postcondition
{this, converser locked }
Definition at line 1429 of file AiAgentImplementation.cpp.
References ObserverEventType::CONVERSE.
Referenced by server::zone::objects::creature::AiAgent::notifyConverseObservers().
void AiAgentImplementation::notifyDespawn (Zone * zone) virtual
Gets called when the creature was despawned
Reimplemented in server::zone::objects::creature::CreatureImplementation.
Definition at line 704 of file AiAgentImplementation.cpp.
References _this, despawnMutex, server::zone::objects::scene::SceneObjectImplementation::getSlottedObject(), server::zone::objects::tangible::TangibleObjectImplementation::level, loadTemplateData(), moveEvent, movementMarkers, npcTemplate, randomRespawn, respawn(), respawnTimer, server::zone::objects::scene::SceneObject::setContainerOwnerID(), setFollowObject(), setLevel(), server::zone::objects::creature::CreatureObjectImplementation::setPosture(), setTargetObject(), server::zone::objects::creature::CreatureObjectImplementation::shockWounds, server::zone::objects::creature::CreatureObjectImplementation::stateBitmask, server::zone::objects::scene::SceneObjectImplementation::templateObject, server::zone::objects::tangible::TangibleObjectImplementation::threatMap, CreaturePosture::UPRIGHT, and server::zone::objects::scene::SceneObjectImplementation::zone.
Referenced by server::zone::objects::creature::CreatureImplementation::notifyDespawn(), and server::zone::objects::creature::AiAgent::notifyDespawn().
void AiAgentImplementation::notifyDissapear (QuadTreeEntry * entry)
Definition at line 785 of file AiAgentImplementation.cpp.
References _this, despawnEvent, followObject, server::zone::objects::scene::SceneObject::isPlayerCreature(), numberOfPlayersInRange, and setFollowObject().
Referenced by server::zone::objects::creature::AiAgent::notifyDissapear().
void AiAgentImplementation::notifyInsert (QuadTreeEntry * entry)
Definition at line 662 of file AiAgentImplementation.cpp.
References _this, server::zone::objects::scene::SceneObject::isPlayerCreature(), and numberOfPlayersInRange.
Referenced by server::zone::objects::creature::AiAgent::notifyInsert().
int AiAgentImplementation::notifyObjectDestructionObservers (TangibleObject * attacker, int condition) virtual
Is called when this object is destroyed
Precondition
{ this, attacker locked }
Postcondition
{ this, attacker locked }
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 1419 of file AiAgentImplementation.cpp.
References _this, server::zone::Zone::getCreatureManager(), server::zone::objects::scene::SceneObjectImplementation::getZone(), server::zone::managers::creature::CreatureManager::notifyDestruction(), and server::zone::objects::creature::CreatureObjectImplementation::notifyObjectDestructionObservers().
Referenced by server::zone::objects::creature::AiAgent::notifyObjectDestructionObservers().
void AiAgentImplementation::notifyPositionUpdate (QuadTreeEntry * entry)
Definition at line 294 of file AiAgentImplementation.cpp.
References _this, aiInterfaceComponents, and server::zone::objects::scene::SceneObjectImplementation::notifyPositionUpdate().
Referenced by server::zone::objects::creature::AiAgent::notifyPositionUpdate().
AiAgentImplementation::operator const AiAgent * ()
Definition at line 1486 of file AiAgent.cpp.
void AiAgentImplementation::queueDizzyFallEvent () virtual
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 602 of file AiAgentImplementation.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::queueDizzyFallEvent().
Referenced by server::zone::objects::creature::AiAgent::queueDizzyFallEvent().
void AiAgentImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Reimplemented in server::zone::objects::creature::CreatureImplementation, and server::zone::objects::creature::NonPlayerCreatureObjectImplementation.
Definition at line 1525 of file AiAgent.cpp.
References initializeTransientMembers(), and readObjectMember().
bool AiAgentImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 1544 of file AiAgent.cpp.
References baby, camouflagedObjects, despawnOnNoPlayerInRange, fleeing, followObject, followState, homeLocation, loadedOutfit, movementMarkers, nextStepPosition, npcTemplate, numberOfPlayersInRange, patrolPoints, randomRespawn, server::zone::objects::creature::CreatureObjectImplementation::readObjectMember(), respawnTimer, showNextMovementPosition, skillCommands, and weapons.
Referenced by readObject(), server::zone::objects::creature::NonPlayerCreatureObjectImplementation::readObjectMember(), and server::zone::objects::creature::CreatureImplementation::readObjectMember().
void AiAgentImplementation::removeDefender (SceneObject * defender) virtual
Removes the specified defender from the defender vector
Precondition
{ this object is locked }
Postcondition
{ this object is locked, defender is not in the defender vector }
Parameters
defender SceneObject to remove from the defender vector
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 620 of file AiAgentImplementation.cpp.
References activateRecovery(), server::zone::objects::tangible::TangibleObjectImplementation::defenderList, server::zone::objects::tangible::threat::ThreatMap::dropDamage(), followObject, server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::tangible::threat::ThreatMap::getHighestThreatCreature(), server::zone::objects::tangible::TangibleObjectImplementation::getThreatMap(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefender(), setDefender(), setOblivious(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
Referenced by doAttack(), and server::zone::objects::creature::AiAgent::removeDefender().
void AiAgentImplementation::resetBehaviorList (BehaviorTree * tree)
Definition at line 1871 of file AiAgentImplementation.cpp.
References trees.
Referenced by server::zone::objects::creature::AiAgent::resetBehaviorList().
void AiAgentImplementation::respawn (Zone * zone, int level)
Respawns creature to specified zone with home location position
Definition at line 676 of file AiAgentImplementation.cpp.
References _this, PatrolPoint::getCell(), PatrolPoint::getPositionX(), PatrolPoint::getPositionY(), PatrolPoint::getPositionZ(), server::zone::objects::scene::SceneObjectImplementation::getZone(), homeLocation, nextStepPosition, PatrolPoint::setCell(), setLevel(), setNextPosition(), PatrolPoint::setPosition(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by notifyDespawn(), and server::zone::objects::creature::AiAgent::respawn().
void AiAgentImplementation::rlock (bool doLock = true) protected
Definition at line 1498 of file AiAgent.cpp.
References _this.
void AiAgentImplementation::runlock (bool doLock = true) protected
Definition at line 1514 of file AiAgent.cpp.
References _this.
void AiAgentImplementation::scheduleDespawn () virtual
Reimplemented in server::zone::objects::creature::CreatureImplementation.
Definition at line 1846 of file AiAgent.cpp.
Referenced by server::zone::objects::creature::AiAgent::scheduleDespawn().
void AiAgentImplementation::scheduleDespawn (int timeToDespawn) virtual
Schedules despawn of the AiAgent.
Parameters
timeToDespawn the time to despawn the AiAgent in seconds.
Definition at line 777 of file AiAgentImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::addPendingTask(), and server::zone::objects::scene::SceneObjectImplementation::getPendingTask().
void AiAgentImplementation::selectConversationOption (int option, SceneObject * obj) virtual
sends the conversation list
Precondition
{this locked, player locked }
Postcondition
{ this locked, player locked }
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 1762 of file AiAgentImplementation.cpp.
Referenced by server::zone::objects::creature::AiAgent::selectConversationOption().
void AiAgentImplementation::selectWeapon ()
Definition at line 468 of file AiAgentImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::broadcastObject(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), followObject, server::zone::objects::scene::SceneObjectImplementation::getDistanceTo(), server::zone::objects::tangible::weapon::WeaponObject::getIdealRange(), server::zone::objects::scene::SceneObjectImplementation::getSlottedObject(), server::zone::objects::creature::CreatureObjectImplementation::getWeapon(), server::zone::objects::tangible::weapon::WeaponObject::isMeleeWeapon(), server::zone::objects::tangible::weapon::WeaponObject::isRangedWeapon(), server::zone::objects::scene::SceneObjectImplementation::transferObject(), and weapons.
Referenced by doAttack(), and server::zone::objects::creature::AiAgent::selectWeapon().
void AiAgentImplementation::sendBaselinesTo (SceneObject * player) virtual
Sends the CREO baseline messages of this object to the specified player
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the baseline messages }
Parameters
player SceneObject that will receive the baselines
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 698 of file AiAgentImplementation.cpp.
References despawnMutex, and server::zone::objects::creature::CreatureObjectImplementation::sendBaselinesTo().
Referenced by server::zone::objects::creature::AiAgent::sendBaselinesTo().
void AiAgentImplementation::sendConversationStartTo (SceneObject * player) virtual
sends the conversation notification
Precondition
{this locked, player locked }
Postcondition
{ this locked, player locked }
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 1601 of file AiAgentImplementation.cpp.
References broadcastNextPositionUpdate(), ObserverEventType::CONVERSE, server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::objects::scene::SceneObjectImplementation::faceObject(), server::zone::objects::scene::SceneObjectImplementation::getObjectID(), server::zone::objects::scene::SceneObjectImplementation::getObservers(), server::zone::objects::scene::SceneObjectImplementation::getParent(), server::zone::objects::creature::CreatureObjectImplementation::isDead(), server::zone::objects::scene::SceneObject::isPlayerCreature(), npcTemplate, ObserverEventType::SELECTCONVERSATION, server::zone::objects::scene::SceneObject::sendMessage(), ObserverEventType::STARTCONVERSATION, and ObserverEventType::STOPCONVERSATION.
Referenced by server::zone::objects::creature::AiAgent::sendConversationStartTo().
void AiAgentImplementation::sendDefaultConversationTo (SceneObject * player)
sends the default conversation list
Precondition
{this locked, player locked }
Postcondition
{this locked, player locked }
Definition at line 1673 of file AiAgentImplementation.cpp.
Referenced by server::zone::objects::creature::AiAgent::sendDefaultConversationTo().
void AiAgentImplementation::setBehaviorStatus (Behavior * b, int status)
Definition at line 1850 of file AiAgentImplementation.cpp.
References statuses.
Referenced by server::zone::objects::creature::AiAgent::setBehaviorStatus().
void AiAgentImplementation::setDefender (SceneObject * defender) virtual
Sets the active defender
Precondition
{ this object is locked }
Postcondition
{ this object is locked, defender is active }
Parameters
defender SceneObject to set as the active defender
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 594 of file AiAgentImplementation.cpp.
References activateRecovery(), server::zone::objects::tangible::TangibleObjectImplementation::setDefender(), and setFollowObject().
Referenced by doAttack(), inflictDamage(), removeDefender(), and server::zone::objects::creature::AiAgent::setDefender().
void AiAgentImplementation::setDespawnOnNoPlayerInRange (bool val)
Definition at line 541 of file AiAgentImplementation.cpp.
References _this, despawnEvent, despawnOnNoPlayerInRange, and numberOfPlayersInRange.
Referenced by server::zone::objects::creature::AiAgent::setDespawnOnNoPlayerInRange().
void AiAgentImplementation::setFollowObject (SceneObject * obj)
Definition at line 1957 of file AiAgent.cpp.
References _this, activateMovementEvent(), FOLLOWING, followState, setTargetObject(), and targetMutex.
Referenced by doAttack(), doMovement(), notifyDespawn(), notifyDissapear(), setDefender(), and server::zone::objects::creature::AiAgent::setFollowObject().
void AiAgentImplementation::setHomeLocation (float x, float z, float y, SceneObject * cell = NULL)
Definition at line 1860 of file AiAgent.cpp.
References homeLocation.
Referenced by server::zone::objects::creature::AiAgent::setHomeLocation().
void AiAgentImplementation::setLevel (int lvl) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 217 of file AiAgentImplementation.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::baseHAM, calculateAttackMaxDamage(), calculateAttackMinDamage(), calculateAttackSpeed(), server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::scene::SceneObjectImplementation::getSlottedObject(), server::zone::objects::tangible::TangibleObjectImplementation::level, npcTemplate, server::zone::objects::tangible::weapon::WeaponObject::setAttackSpeed(), server::zone::objects::creature::CreatureObjectImplementation::setBaseHAM(), server::zone::objects::creature::CreatureObjectImplementation::setHAM(), server::zone::objects::creature::CreatureObjectImplementation::setLevel(), server::zone::objects::tangible::weapon::WeaponObject::setMaxDamage(), server::zone::objects::creature::CreatureObjectImplementation::setMaxHAM(), server::zone::objects::tangible::weapon::WeaponObject::setMinDamage(), and weapons.
Referenced by notifyDespawn(), respawn(), and server::zone::objects::creature::AiAgent::setLevel().
void AiAgentImplementation::setNextPosition (float x, float z, float y, SceneObject * cell = NULL)
Definition at line 1389 of file AiAgentImplementation.cpp.
References patrolPoints, and targetMutex.
Referenced by doMovement(), respawn(), server::zone::objects::creature::CreatureImplementation::runAway(), and server::zone::objects::creature::AiAgent::setNextPosition().
void AiAgentImplementation::setOblivious ()
Definition at line 1916 of file AiAgent.cpp.
References activateMovementEvent(), followState, OBLIVIOUS, and setTargetObject().
Referenced by clearCombatState(), doMovement(), removeDefender(), server::zone::objects::creature::CreatureImplementation::runAway(), server::zone::objects::creature::AiAgent::setOblivious(), and tryRetreat().
void AiAgentImplementation::setRandomRespawn (bool resp)
Definition at line 1874 of file AiAgent.cpp.
References randomRespawn.
Referenced by server::zone::objects::creature::AiAgent::setRandomRespawn().
void AiAgentImplementation::setRespawnTimer (float resp)
Definition at line 1869 of file AiAgent.cpp.
References respawnTimer.
Referenced by server::zone::objects::creature::AiAgent::setRespawnTimer().
void AiAgentImplementation::setShowNextPosition (bool val)
Definition at line 2219 of file AiAgent.cpp.
References showNextMovementPosition.
Referenced by server::zone::objects::creature::AiAgent::setShowNextPosition().
void AiAgentImplementation::setStalkObject (SceneObject * obj)
Definition at line 1941 of file AiAgent.cpp.
References _this, activateMovementEvent(), followState, setTargetObject(), STALKING, and targetMutex.
Referenced by server::zone::objects::creature::AiAgent::setStalkObject().
void AiAgentImplementation::setTargetObject (SceneObject * obj)
Definition at line 1973 of file AiAgent.cpp.
References clearPatrolPoints(), followObject, and targetMutex.
Referenced by notifyDespawn(), setFollowObject(), setOblivious(), setStalkObject(), server::zone::objects::creature::AiAgent::setTargetObject(), and setWatchObject().
void AiAgentImplementation::setWatchObject (SceneObject * obj)
Definition at line 1925 of file AiAgent.cpp.
References _this, activateMovementEvent(), followState, setTargetObject(), targetMutex, and WATCHING.
Referenced by server::zone::objects::creature::AiAgent::setWatchObject().
bool AiAgentImplementation::tryRetreat ()
Definition at line 557 of file AiAgentImplementation.cpp.
References _this, activateMovementEvent(), server::zone::objects::scene::SceneObjectImplementation::error(), PatrolPoint::getPositionX(), PatrolPoint::getPositionY(), PatrolPoint::getPositionZ(), homeLocation, PatrolPoint::isInRange(), patrolPoints, setOblivious(), PatrolPoint::setReached(), targetMutex, and server::zone::objects::tangible::TangibleObjectImplementation::threatMap.
Referenced by doAttack(), and server::zone::objects::creature::AiAgent::tryRetreat().
void AiAgentImplementation::unlock (bool doLock = true) protected
Definition at line 1510 of file AiAgent.cpp.
References _this.
void AiAgentImplementation::updateCurrentPosition (PatrolPoint * point)
Definition at line 845 of file AiAgentImplementation.cpp.
References PatrolPoint::getCell(), PatrolPoint::getPositionX(), PatrolPoint::getPositionY(), PatrolPoint::getPositionZ(), server::zone::objects::scene::SceneObjectImplementation::getZone(), server::zone::objects::scene::SceneObjectImplementation::updateZone(), and server::zone::objects::scene::SceneObjectImplementation::updateZoneWithParent().
Referenced by doMovement(), and server::zone::objects::creature::AiAgent::updateCurrentPosition().
bool AiAgentImplementation::validateStateAttack (CreatureObject * target, String & args)
Definition at line 520 of file AiAgentImplementation.cpp.
References server::zone::objects::creature::CreatureObject::hasState(), server::zone::objects::creature::CreatureObject::isKnockedDown(), server::zone::objects::creature::CreatureObject::isProne(), and server::zone::objects::creature::CreatureObject::isStanding().
Referenced by doAttack(), and server::zone::objects::creature::AiAgent::validateStateAttack().
void AiAgentImplementation::wlock (bool doLock = true) protected
Definition at line 1502 of file AiAgent.cpp.
References _this.
void AiAgentImplementation::wlock (ManagedObject * obj) protected
Definition at line 1506 of file AiAgent.cpp.
References _this.
void AiAgentImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Reimplemented in server::zone::objects::creature::CreatureImplementation, and server::zone::objects::creature::NonPlayerCreatureObjectImplementation.
Definition at line 1626 of file AiAgent.cpp.
References writeObjectMembers().
int AiAgentImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 1633 of file AiAgent.cpp.
References baby, camouflagedObjects, despawnOnNoPlayerInRange, fleeing, followObject, followState, homeLocation, loadedOutfit, movementMarkers, nextStepPosition, npcTemplate, numberOfPlayersInRange, patrolPoints, randomRespawn, respawnTimer, showNextMovementPosition, skillCommands, weapons, and server::zone::objects::creature::CreatureObjectImplementation::writeObjectMembers().
Referenced by writeObject(), server::zone::objects::creature::NonPlayerCreatureObjectImplementation::writeObjectMembers(), and server::zone::objects::creature::CreatureImplementation::writeObjectMembers().
Friends And Related Function Documentation
friend class AiAgent friend
Definition at line 1099 of file AiAgent.h.
Member Data Documentation
WeakReference<AiAgent*> server::zone::objects::creature::AiAgentImplementation::_this
Definition at line 1067 of file AiAgent.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), activateAwarenessEvent(), activateMovementEvent(), activateRecovery(), activateWaitEvent(), broadcastNextPositionUpdate(), doAttack(), doAwarenessCheck(), doMovement(), doRecovery(), findNextPosition(), handleObjectMenuSelect(), isAttackableBy(), isConcealed(), isScentMasked(), lock(), notifyDespawn(), notifyDissapear(), notifyInsert(), notifyObjectDestructionObservers(), notifyPositionUpdate(), respawn(), rlock(), runlock(), scheduleDespawn(), setDespawnOnNoPlayerInRange(), setFollowObject(), setStalkObject(), setWatchObject(), tryRetreat(), unlock(), and wlock().
Vector<AiInterfaceComponent*> server::zone::objects::creature::AiAgentImplementation::aiInterfaceComponents protected
Definition at line 674 of file AiAgent.h.
Referenced by doAwarenessCheck(), server::zone::objects::creature::NonPlayerCreatureObjectImplementation::initializeTransientMembers(), server::zone::objects::creature::CreatureImplementation::initializeTransientMembers(), initializeTransientMembers(), and notifyPositionUpdate().
Reference<AiAwarenessEvent* > server::zone::objects::creature::AiAgentImplementation::awarenessEvent protected
Definition at line 670 of file AiAgent.h.
Referenced by activateAwarenessEvent().
Mutex server::zone::objects::creature::AiAgentImplementation::awernessEventMutex protected
Definition at line 708 of file AiAgent.h.
Referenced by activateAwarenessEvent().
bool server::zone::objects::creature::AiAgentImplementation::baby protected
Definition at line 694 of file AiAgent.h.
Referenced by AiAgentImplementation(), server::zone::objects::creature::CreatureImplementation::isBaby(), readObjectMember(), and writeObjectMembers().
Vector<ManagedReference<SceneObject* > > server::zone::objects::creature::AiAgentImplementation::camouflagedObjects protected
Definition at line 690 of file AiAgent.h.
Referenced by isConcealed(), isScentMasked(), readObjectMember(), and writeObjectMembers().
Reference<CurrentFoundPath* > server::zone::objects::creature::AiAgentImplementation::currentFoundPath protected
Definition at line 684 of file AiAgent.h.
Referenced by findNextPosition().
Reference<DespawnCreatureOnPlayerDissappear* > server::zone::objects::creature::AiAgentImplementation::despawnEvent protected
Definition at line 722 of file AiAgent.h.
Referenced by clearDespawnEvent(), notifyDissapear(), and setDespawnOnNoPlayerInRange().
ReadWriteLock server::zone::objects::creature::AiAgentImplementation::despawnMutex protected
Definition at line 672 of file AiAgent.h.
Referenced by notifyDespawn(), and sendBaselinesTo().
bool server::zone::objects::creature::AiAgentImplementation::despawnOnNoPlayerInRange protected
Definition at line 700 of file AiAgent.h.
Referenced by AiAgentImplementation(), getDespawnOnNoPlayerInRange(), readObjectMember(), setDespawnOnNoPlayerInRange(), and writeObjectMembers().
bool server::zone::objects::creature::AiAgentImplementation::fleeing protected
Definition at line 710 of file AiAgent.h.
Referenced by AiAgentImplementation(), doMovement(), isFleeing(), readObjectMember(), server::zone::objects::creature::CreatureImplementation::runAway(), and writeObjectMembers().
unsigned const int server::zone::objects::creature::AiAgentImplementation::FOLLOWING = 3 static
Definition at line 733 of file AiAgent.h.
Referenced by addDefender(), and setFollowObject().
ManagedReference<SceneObject* > server::zone::objects::creature::AiAgentImplementation::followObject protected
Definition at line 702 of file AiAgent.h.
Referenced by checkNewAngle(), doAttack(), doMovement(), findNextPosition(), getFollowObject(), notifyDissapear(), readObjectMember(), removeDefender(), selectWeapon(), setTargetObject(), and writeObjectMembers().
unsigned int server::zone::objects::creature::AiAgentImplementation::followState protected
Definition at line 704 of file AiAgent.h.
Referenced by addDefender(), AiAgentImplementation(), doMovement(), readObjectMember(), setFollowObject(), setOblivious(), setStalkObject(), setWatchObject(), and writeObjectMembers().
PatrolPoint server::zone::objects::creature::AiAgentImplementation::homeLocation protected
Definition at line 680 of file AiAgent.h.
Referenced by doMovement(), getHomeLocation(), isRetreating(), readObjectMember(), respawn(), setHomeLocation(), tryRetreat(), and writeObjectMembers().
Time server::zone::objects::creature::AiAgentImplementation::lastDamageReceived protected
Definition at line 712 of file AiAgent.h.
Referenced by doAttack(), and inflictDamage().
bool server::zone::objects::creature::AiAgentImplementation::loadedOutfit protected
Definition at line 720 of file AiAgent.h.
Referenced by AiAgentImplementation(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
Reference<AiMoveEvent* > server::zone::objects::creature::AiAgentImplementation::moveEvent protected
Definition at line 666 of file AiAgent.h.
Referenced by activateMovementEvent(), destroyObjectFromWorld(), and notifyDespawn().
Vector<ManagedReference<SceneObject* > > server::zone::objects::creature::AiAgentImplementation::movementMarkers protected
Definition at line 698 of file AiAgent.h.
Referenced by findNextPosition(), notifyDespawn(), readObjectMember(), and writeObjectMembers().
PatrolPoint server::zone::objects::creature::AiAgentImplementation::nextStepPosition protected
Definition at line 682 of file AiAgent.h.
Referenced by checkNewAngle(), doMovement(), readObjectMember(), respawn(), and writeObjectMembers().
CreatureTemplateReference server::zone::objects::creature::AiAgentImplementation::npcTemplate protected
Definition at line 692 of file AiAgent.h.
Referenced by calculateAttackMaxDamage(), calculateAttackMinDamage(), doAttack(), getAcid(), getArmor(), getAttackMap(), getBaseXp(), getBlast(), server::zone::objects::creature::CreatureImplementation::getBoneMax(), server::zone::objects::creature::CreatureImplementation::getBoneType(), getChanceHit(), getCold(), getCreatureTemplate(), getDamageMax(), getDamageMin(), getDiet(), getElectricity(), getEnergy(), getFactionString(), getFerocity(), getHeat(), server::zone::objects::creature::CreatureImplementation::getHideMax(), server::zone::objects::creature::CreatureImplementation::getHideType(), getKinetic(), getLightSaber(), getLootGroups(), server::zone::objects::creature::CreatureImplementation::getMeatMax(), server::zone::objects::creature::CreatureImplementation::getMeatType(), server::zone::objects::creature::CreatureImplementation::getMilk(), server::zone::objects::creature::CreatureImplementation::getMilkType(), getPvPFaction(), getSocialGroup(), getStun(), server::zone::objects::creature::CreatureImplementation::getTame(), isEventMob(), isKiller(), isStalker(), loadTemplateData(), notifyDespawn(), readObjectMember(), sendConversationStartTo(), setLevel(), and writeObjectMembers().
int server::zone::objects::creature::AiAgentImplementation::numberOfPlayersInRange protected
Definition at line 718 of file AiAgent.h.
Referenced by AiAgentImplementation(), getNumberOfPlayersInRange(), notifyDissapear(), notifyInsert(), readObjectMember(), setDespawnOnNoPlayerInRange(), and writeObjectMembers().
unsigned const int server::zone::objects::creature::AiAgentImplementation::OBLIVIOUS = 0 static
Definition at line 727 of file AiAgent.h.
Referenced by AiAgentImplementation(), and setOblivious().
unsigned const int server::zone::objects::creature::AiAgentImplementation::PATROLING = 4 static
Definition at line 735 of file AiAgent.h.
PatrolPointsVector server::zone::objects::creature::AiAgentImplementation::patrolPoints protected
Definition at line 678 of file AiAgent.h.
Referenced by addPatrolPoint(), clearPatrolPoints(), doMovement(), findNextPosition(), readObjectMember(), server::zone::objects::creature::CreatureImplementation::runAway(), setNextPosition(), tryRetreat(), and writeObjectMembers().
bool server::zone::objects::creature::AiAgentImplementation::randomRespawn protected
Definition at line 716 of file AiAgent.h.
Referenced by AiAgentImplementation(), getRandomRespawn(), notifyDespawn(), readObjectMember(), setRandomRespawn(), and writeObjectMembers().
float server::zone::objects::creature::AiAgentImplementation::respawnTimer protected
Definition at line 714 of file AiAgent.h.
Referenced by AiAgentImplementation(), getRespawnTimer(), notifyDespawn(), readObjectMember(), setRespawnTimer(), and writeObjectMembers().
bool server::zone::objects::creature::AiAgentImplementation::showNextMovementPosition protected
Definition at line 696 of file AiAgent.h.
Referenced by AiAgentImplementation(), findNextPosition(), readObjectMember(), setShowNextPosition(), and writeObjectMembers().
Vector<String> server::zone::objects::creature::AiAgentImplementation::skillCommands protected
Definition at line 676 of file AiAgent.h.
Referenced by readObjectMember(), and writeObjectMembers().
unsigned const int server::zone::objects::creature::AiAgentImplementation::STALKING = 2 static
Definition at line 731 of file AiAgent.h.
Referenced by addDefender(), and setStalkObject().
HashTable<Behavior*, int> server::zone::objects::creature::AiAgentImplementation::statuses protected
Definition at line 738 of file AiAgent.h.
Referenced by getBehaviorStatus(), and setBehaviorStatus().
ManagedReference<SceneObject* > server::zone::objects::creature::AiAgentImplementation::targetCellObject protected
Definition at line 686 of file AiAgent.h.
Referenced by findNextPosition().
Mutex server::zone::objects::creature::AiAgentImplementation::targetMutex protected
Definition at line 706 of file AiAgent.h.
Referenced by addPatrolPoint(), clearPatrolPoints(), findNextPosition(), isConcealed(), isScentMasked(), setFollowObject(), setNextPosition(), setStalkObject(), setTargetObject(), setWatchObject(), and tryRetreat().
Reference<AiThinkEvent* > server::zone::objects::creature::AiAgentImplementation::thinkEvent protected
Definition at line 664 of file AiAgent.h.
Referenced by activateRecovery().
HashTable<BehaviorTree*, BehaviorTreeList*> server::zone::objects::creature::AiAgentImplementation::trees protected
Definition at line 740 of file AiAgent.h.
Referenced by addBehaviorToTree(), getNextBehaviorFromTree(), and resetBehaviorList().
const int server::zone::objects::creature::AiAgentImplementation::UPDATEMOVEMENTINTERVAL = 500 static
Definition at line 725 of file AiAgent.h.
Referenced by activateMovementEvent(), activateWaitEvent(), doMovement(), and findNextPosition().
Reference<AiWaitEvent* > server::zone::objects::creature::AiAgentImplementation::waitEvent protected
Definition at line 668 of file AiAgent.h.
Referenced by activateWaitEvent().
unsigned const int server::zone::objects::creature::AiAgentImplementation::WATCHING = 1 static
Definition at line 729 of file AiAgent.h.
Referenced by setWatchObject().
Vector<ManagedReference<WeaponObject* > > server::zone::objects::creature::AiAgentImplementation::weapons protected
Definition at line 688 of file AiAgent.h.
Referenced by loadTemplateData(), readObjectMember(), selectWeapon(), setLevel(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/AiAgent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/AiAgent.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/AiAgentImplementation.cpp