Core3: MeshAppearanceTemplate Class Reference
MeshAppearanceTemplate Class Reference
#include <MeshAppearanceTemplate.h>
Public Member Functions
MeshAppearanceTemplate ()
~MeshAppearanceTemplate ()
void createAABB ()
void readObject (IffStream *templateData)
void parse (IffStream *iffStream)
void parseSPS (IffStream *iffStream)
void parseVertexData (IffStream *iffStream, int idx)
bool testCollide (float x, float z, float y, float radius)
AppearanceTemplate * getFirstMesh ()
void getTriangles (Vector< Triangle * > &triangles)
AABBTree * getAABBTree ()
Public Member Functions inherited from AppearanceTemplate
virtual ~AppearanceTemplate ()
Private Attributes
Vector< MeshData > * meshes
AABBTree * aabbTree
Detailed Description
Definition at line 91 of file MeshAppearanceTemplate.h.
Constructor & Destructor Documentation
MeshAppearanceTemplate::MeshAppearanceTemplate () inline
Definition at line 100 of file MeshAppearanceTemplate.h.
References aabbTree, and meshes.
MeshAppearanceTemplate::~MeshAppearanceTemplate () inline
Definition at line 105 of file MeshAppearanceTemplate.h.
References aabbTree.
Member Function Documentation
void MeshAppearanceTemplate::createAABB ()
Definition at line 35 of file MeshAppearanceTemplate.cpp.
References aabbTree, MeshVertex::getX(), MeshVertex::getY(), MeshVertex::getZ(), meshes, MeshData::triangles, MeshTriangle::vertex1, MeshTriangle::vertex2, MeshTriangle::vertex3, and MeshData::vertices.
Referenced by parse().
AABBTree* MeshAppearanceTemplate::getAABBTree () inline
Definition at line 135 of file MeshAppearanceTemplate.h.
References aabbTree.
Referenced by CollisionManager::checkLineOfSightInBuilding(), CollisionManager::checkLineOfSightInParentCell(), CollisionManager::checkLineOfSightWorldToCell(), CollisionManager::getAABBTree(), and server::zone::objects::structure::StructureObjectImplementation::getAABBTree().
AppearanceTemplate* MeshAppearanceTemplate::getFirstMesh () inline virtual
Reimplemented from AppearanceTemplate.
Definition at line 122 of file MeshAppearanceTemplate.h.
void MeshAppearanceTemplate::getTriangles (Vector< Triangle * > & triangles) inline
Definition at line 126 of file MeshAppearanceTemplate.h.
References aabbTree.
void MeshAppearanceTemplate::parse (IffStream * iffStream)
Definition at line 10 of file MeshAppearanceTemplate.cpp.
References createAABB(), meshes, parseSPS(), and AppearanceTemplate::readObject().
Referenced by readObject().
void MeshAppearanceTemplate::parseSPS (IffStream * iffStream)
Definition at line 89 of file MeshAppearanceTemplate.cpp.
References parseVertexData().
Referenced by parse().
void MeshAppearanceTemplate::parseVertexData (IffStream * iffStream, int idx)
Definition at line 109 of file MeshAppearanceTemplate.cpp.
References meshes, and MeshData::readObject().
Referenced by parseSPS().
void MeshAppearanceTemplate::readObject (IffStream * templateData) inline virtual
Reimplemented from AppearanceTemplate.
Definition at line 112 of file MeshAppearanceTemplate.h.
References parse().
bool MeshAppearanceTemplate::testCollide (float x, float z, float y, float radius)
Definition at line 79 of file MeshAppearanceTemplate.cpp.
References aabbTree.
Member Data Documentation
AABBTree* MeshAppearanceTemplate::aabbTree private
Definition at line 95 of file MeshAppearanceTemplate.h.
Referenced by createAABB(), getAABBTree(), getTriangles(), MeshAppearanceTemplate(), testCollide(), and ~MeshAppearanceTemplate().
Vector<MeshData>* MeshAppearanceTemplate::meshes private
Definition at line 92 of file MeshAppearanceTemplate.h.
Referenced by createAABB(), MeshAppearanceTemplate(), parse(), and parseVertexData().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/MeshAppearanceTemplate.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/MeshAppearanceTemplate.cpp