Core3: BankTerminalMenuComponent Class Reference
BankTerminalMenuComponent Class Reference
#include <BankTerminalMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Static Protected Attributes
static const int JOIN = 71
static const int QUIT = 72
static const int DEPOSIT = 73
static const int WITHDRAW = 68
static const int DEPOSITALL = 69
static const int WITHDRAWALL = 70
static const bool GLOBALSAFETYDEPOSIT = false
Detailed Description
Definition at line 13 of file BankTerminalMenuComponent.h.
Member Function Documentation
void BankTerminalMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from TangibleObjectMenuComponent.
Definition at line 21 of file BankTerminalMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID(), TangibleObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZone(), and server::zone::Zone::getZoneName().
int BankTerminalMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from TangibleObjectMenuComponent.
Definition at line 61 of file BankTerminalMenuComponent.cpp.
References server::zone::objects::creature::CreatureObject::addBankCredits(), server::zone::objects::creature::CreatureObject::addCashCredits(), SuiWindowType::BANK_TRANSFER, DEPOSIT, DEPOSITALL, server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::Zone::getZoneServer(), server::zone::objects::scene::SceneObject::getZoneServer(), GLOBALSAFETYDEPOSIT, TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::isTangibleObject(), JOIN, QUIT, server::zone::objects::scene::SceneObject::sendDestroyTo(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::SceneObject::sendTo(), server::chat::StringIdChatParameter::setDI(), server::zone::objects::scene::variables::StringId::setStringId(), server::zone::objects::creature::CreatureObject::subtractBankCredits(), server::zone::objects::creature::CreatureObject::subtractCashCredits(), WITHDRAW, and WITHDRAWALL.
Member Data Documentation
const int BankTerminalMenuComponent::DEPOSIT = 73 static protected
Definition at line 17 of file BankTerminalMenuComponent.h.
Referenced by handleObjectMenuSelect().
const int BankTerminalMenuComponent::DEPOSITALL = 69 static protected
Definition at line 19 of file BankTerminalMenuComponent.h.
Referenced by handleObjectMenuSelect().
const bool BankTerminalMenuComponent::GLOBALSAFETYDEPOSIT = false static protected
Definition at line 23 of file BankTerminalMenuComponent.h.
Referenced by handleObjectMenuSelect().
const int BankTerminalMenuComponent::JOIN = 71 static protected
Definition at line 15 of file BankTerminalMenuComponent.h.
Referenced by handleObjectMenuSelect().
const int BankTerminalMenuComponent::QUIT = 72 static protected
Definition at line 16 of file BankTerminalMenuComponent.h.
Referenced by handleObjectMenuSelect().
const int BankTerminalMenuComponent::WITHDRAW = 68 static protected
Definition at line 18 of file BankTerminalMenuComponent.h.
Referenced by handleObjectMenuSelect().
const int BankTerminalMenuComponent::WITHDRAWALL = 70 static protected
Definition at line 20 of file BankTerminalMenuComponent.h.
Referenced by handleObjectMenuSelect().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/BankTerminalMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/BankTerminalMenuComponent.cpp