Core3: server::zone::objects::creature::conversation::TrainerConversationObserverImplementation Class Reference
server::zone::objects::creature::conversation::TrainerConversationObserverImplementation Class Reference
#include <TrainerConversationObserver.h>
Public Member Functions
TrainerConversationObserverImplementation (ConversationTemplate *conversationTemplate)
TrainerConversationObserverImplementation (DummyConstructorParameter *param)
operator const TrainerConversationObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
ConversationObserverImplementation (ConversationTemplate *conversationTemplate)
ConversationObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
virtual ConversationScreen * getNextConversationScreen (CreatureObject *conversingPlayer, int selectedOption, CreatureObject *conversingNPC)
virtual ConversationScreen * runScreenHandlers (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
operator const ConversationObserver * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< TrainerConversationObserver * > _this
Public Attributes inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
WeakReference
< ConversationObserver * > _this
Protected Member Functions
virtual void createConversationSession (CreatureObject *conversingPlayer, CreatureObject *npc)
virtual ~TrainerConversationObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
void registerScreenHandler (const String &screenId, ScreenHandler *screenHandler)
void removeScreenHandler (const String &screenId)
void createPositionObserver (CreatureObject *player)
virtual ~ConversationObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
TrainerScreenHandlers trainerScreenHandlers
Friends
class TrainerConversationObserver
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
Reference< ConversationTemplate * > conversationTemplate
Detailed Description
Definition at line 61 of file TrainerConversationObserver.h.
Constructor & Destructor Documentation
TrainerConversationObserverImplementation::TrainerConversationObserverImplementation (ConversationTemplate * conversationTemplate)
Definition at line 48 of file TrainerConversationObserverImplementation.cpp.
References server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::canLearnSkillScreenHandler, server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::infoScreenHandler, server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::nextSkillsScreenHandler, server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::notEnoughCreditsScreenHandler, server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::notEnoughSkillPointsScreenHandler, server::zone::objects::creature::conversation::ConversationObserverImplementation::registerScreenHandler(), server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::skillInfoScreenHandler, server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::trainableSkillsScreenHandler, server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::trainedMasterScreenHandler, trainerScreenHandlers, and server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::trainSkillScreenHandler.
TrainerConversationObserverImplementation::TrainerConversationObserverImplementation (DummyConstructorParameter * param)
Definition at line 45 of file TrainerConversationObserver.cpp.
References _initializeImplementation().
TrainerConversationObserverImplementation::~TrainerConversationObserverImplementation () protected virtual
Definition at line 50 of file TrainerConversationObserver.cpp.
Member Function Documentation
DistributedObjectStub * TrainerConversationObserverImplementation::_getStub ()
Definition at line 70 of file TrainerConversationObserver.cpp.
References _this.
void TrainerConversationObserverImplementation::_initializeImplementation () protected
Definition at line 57 of file TrainerConversationObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by TrainerConversationObserverImplementation().
void TrainerConversationObserverImplementation::_serializationHelperMethod () protected
Definition at line 106 of file TrainerConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void TrainerConversationObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 65 of file TrainerConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::conversation::TrainerConversationObserver::TrainerConversationObserver().
void TrainerConversationObserverImplementation::createConversationSession (CreatureObject * conversingPlayer, CreatureObject * npc) protected virtual
Reimplemented from server::zone::objects::creature::conversation::ConversationObserverImplementation.
Definition at line 70 of file TrainerConversationObserverImplementation.cpp.
References server::zone::objects::scene::SceneObject::addActiveSession(), and SessionFacadeType::CONVERSATION.
void TrainerConversationObserverImplementation::finalize () protected
Definition at line 54 of file TrainerConversationObserver.cpp.
void TrainerConversationObserverImplementation::lock (bool doLock = true) protected
Definition at line 78 of file TrainerConversationObserver.cpp.
References _this.
void TrainerConversationObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 82 of file TrainerConversationObserver.cpp.
References _this.
TrainerConversationObserverImplementation::operator const TrainerConversationObserver * ()
Definition at line 74 of file TrainerConversationObserver.cpp.
void TrainerConversationObserverImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::conversation::ConversationObserverImplementation.
Definition at line 113 of file TrainerConversationObserver.cpp.
References readObjectMember().
bool TrainerConversationObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 132 of file TrainerConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::readObjectMember(), and trainerScreenHandlers.
Referenced by readObject().
void TrainerConversationObserverImplementation::rlock (bool doLock = true) protected
Definition at line 86 of file TrainerConversationObserver.cpp.
References _this.
void TrainerConversationObserverImplementation::runlock (bool doLock = true) protected
Definition at line 102 of file TrainerConversationObserver.cpp.
References _this.
void TrainerConversationObserverImplementation::unlock (bool doLock = true) protected
Definition at line 98 of file TrainerConversationObserver.cpp.
References _this.
void TrainerConversationObserverImplementation::wlock (bool doLock = true) protected
Definition at line 90 of file TrainerConversationObserver.cpp.
References _this.
void TrainerConversationObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 94 of file TrainerConversationObserver.cpp.
References _this.
void TrainerConversationObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::conversation::ConversationObserverImplementation.
Definition at line 146 of file TrainerConversationObserver.cpp.
References writeObjectMembers().
int TrainerConversationObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 153 of file TrainerConversationObserver.cpp.
References trainerScreenHandlers, and server::zone::objects::creature::conversation::ConversationObserverImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class TrainerConversationObserver friend
Definition at line 107 of file TrainerConversationObserver.h.
Member Data Documentation
WeakReference<TrainerConversationObserver*> server::zone::objects::creature::conversation::TrainerConversationObserverImplementation::_this
Definition at line 73 of file TrainerConversationObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
TrainerScreenHandlers server::zone::objects::creature::conversation::TrainerConversationObserverImplementation::trainerScreenHandlers private
Definition at line 62 of file TrainerConversationObserver.h.
Referenced by readObjectMember(), TrainerConversationObserverImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/TrainerConversationObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/TrainerConversationObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/TrainerConversationObserverImplementation.cpp