Core3: DotPackCommand Class Reference
DotPackCommand Class Reference
#include <DotPackCommand.h>
Public Member Functions
DotPackCommand (const String &name, ZoneProcessServer *server)
void doAnimationsRange (CreatureObject *creature, CreatureObject *creatureTarget, uint64 oid, float range, bool area)
void parseModifier (const String &modifier, uint64 &objectId)
bool checkTarget (CreatureObject *creature, CreatureObject *targetCreature)
void awardXp (CreatureObject *creature, const String &type, int power)
void handleArea (CreatureObject *creature, CreatureObject *areaCenter, DotPack *pharma, float range)
void doAreaMedicActionTarget (CreatureObject *creature, CreatureObject *creatureTarget, DotPack *pharma)
int hasCost (CreatureObject *creature)
void applyCost (CreatureObject *creature, int mindDamage)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Public Member Functions inherited from server::zone::objects::creature::commands::QueueCommand
QueueCommand (const String &skillname, ZoneProcessServer *serv)
virtual ~QueueCommand ()
bool checkInvalidLocomotions (CreatureObject *creature)
void onStateFail (CreatureObject *creature, uint32 actioncntr)
void onLocomotionFail (CreatureObject *creature, uint32 actioncntr)
virtual String getSyntax () const
virtual void onFail (uint32 actioncntr, CreatureObject *creature, uint32 errorNumber)
virtual void onComplete (uint32 actioncntr, CreatureObject *creature, float commandDuration)
void setInvalidLocomotions (const String &lStr)
void addInvalidLocomotion (int l)
bool checkStateMask (CreatureObject *creature)
virtual float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
void setStateMask (uint64 mask)
void setDefaultTime (float time)
void setTargetType (int num)
void setDisabled (bool state)
void setDisabled (int state)
void setAddToCombatQueue (bool state)
void setAddToCombatQueue (int state)
void setCommandGroup (int val)
void setMaxRange (float r)
void setCharacterAbility (const String &ability)
void setDefaultPriority (const String &priority)
void setDefaultPriority (const int priority)
uint64 getStateMask ()
bool requiresAdmin ()
int getTargetType ()
uint32 getNameCRC ()
float getMaxRange ()
String & getQueueCommandName ()
String & getCharacterAbility ()
float getDefaultTime ()
int getDefaultPriority ()
bool isDisabled ()
bool addToCombatQueue ()
virtual bool isCombatCommand ()
int getSkillModSize ()
int getSkillMod (int index, String &skillMod)
int getCommandGroup ()
void addSkillMod (const String &skillMod, const int value)
bool isWearingArmor (CreatureObject *creo)
virtual void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Protected Attributes
String effectName
String skillName
Protected Attributes inherited from server::zone::objects::creature::commands::QueueCommand
ZoneProcessServer * server
String name
uint32 nameCRC
uint64 stateMask
Vector< int > invalidLocomotion
int targetType
int maxRangeToTarget
bool disabled
bool addToQueue
bool admin
uint32 cooldown
float defaultTime
String characterAbility
int defaultPriority
VectorMap< String, int > skillMods
int commandGroup
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::creature::commands::QueueCommand
static const int IMMEDIATE = 0
static const int FRONT = 1
static const int NORMAL = 2
static const int SUCCESS = 0
static const int GENERALERROR = 1
static const int INVALIDLOCOMOTION = 2
static const int INVALIDSTATE = 3
static const int INVALIDTARGET = 4
static const int INVALIDWEAPON = 5
static const int TOOFAR = 6
static const int INSUFFICIENTHAM = 7
static const int INVALIDPARAMETERS = 8
static const int NOPRONE = 9
static const int NOKNEELING = 10
static const int INSUFFICIENTPERMISSION = 11
static const int NOJEDIARMOR = 12
static const int INVALIDSYNTAX = 13
Detailed Description
Definition at line 26 of file DotPackCommand.h.
Constructor & Destructor Documentation
DotPackCommand::DotPackCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 31 of file DotPackCommand.h.
References effectName.
Member Function Documentation
void DotPackCommand::applyCost (CreatureObject * creature, int mindDamage) inline
Definition at line 218 of file DotPackCommand.h.
References server::zone::objects::creature::CreatureObject::inflictDamage(), and CreatureAttribute::MIND.
Referenced by doQueueCommand().
void DotPackCommand::awardXp (CreatureObject * creature, const String & type, int power) inline
Definition at line 89 of file DotPackCommand.h.
References server::zone::managers::player::PlayerManager::awardExperience(), server::zone::ZoneServer::getPlayerManager(), server::zone::ZoneProcessServer::getZoneServer(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::creature::commands::QueueCommand::server.
Referenced by doAreaMedicActionTarget(), and doQueueCommand().
bool DotPackCommand::checkTarget (CreatureObject * creature, CreatureObject * targetCreature) inline
Definition at line 71 of file DotPackCommand.h.
References CollisionManager::checkLineOfSight(), server::zone::ZoneProcessServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::isAttackableBy(), and server::zone::objects::creature::commands::QueueCommand::server.
Referenced by handleArea().
void DotPackCommand::doAnimationsRange (CreatureObject * creature, CreatureObject * creatureTarget, uint64 oid, float range, bool area) inline
Definition at line 37 of file DotPackCommand.h.
References server::zone::objects::scene::SceneObject::broadcastMessage().
Referenced by doQueueCommand().
void DotPackCommand::doAreaMedicActionTarget (CreatureObject * creature, CreatureObject * creatureTarget, DotPack * pharma) inline
Definition at line 148 of file DotPackCommand.h.
References server::zone::objects::tangible::threat::ThreatMap::addDamage(), server::zone::objects::tangible::TangibleObject::addDefender(), server::zone::objects::creature::CreatureObject::addDotState(), awardXp(), server::zone::objects::tangible::pharmaceutical::DotPack::calculatePower(), CreatureState::DISEASED, server::zone::objects::tangible::pharmaceutical::DotPack::getDuration(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::tangible::pharmaceutical::DotPack::getPool(), server::zone::objects::tangible::pharmaceutical::DotPack::getPotency(), server::zone::objects::scene::SceneObject::getServerObjectCRC(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::tangible::TangibleObject::getThreatMap(), server::zone::objects::tangible::pharmaceutical::DotPack::isDiseaseDeliveryUnit(), server::zone::objects::tangible::pharmaceutical::DotPack::isPoisonDeliveryUnit(), CreatureState::POISONED, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setTT(), and server::chat::StringIdChatParameter::setTU().
Referenced by handleArea().
int DotPackCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline virtual
Reimplemented from server::zone::objects::creature::commands::QueueCommand.
Definition at line 225 of file DotPackCommand.h.
References server::zone::objects::creature::CreatureObject::addCooldown(), server::zone::objects::tangible::threat::ThreatMap::addDamage(), server::zone::objects::creature::CreatureObject::addDotState(), applyCost(), awardXp(), server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), server::zone::objects::creature::commands::QueueCommand::checkInvalidLocomotions(), CollisionManager::checkLineOfSight(), server::zone::objects::creature::commands::QueueCommand::checkStateMask(), CreatureState::DISEASED, doAnimationsRange(), BuffCRC::FOOD_HEAL_RECOVERY, server::zone::objects::creature::commands::QueueCommand::GENERALERROR, server::zone::objects::creature::CreatureObject::getBuff(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::ZoneProcessServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::buffs::Buff::getSkillModifierValue(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::tangible::TangibleObject::getThreatMap(), server::zone::ZoneProcessServer::getZoneServer(), handleArea(), server::zone::objects::creature::CreatureObject::hasBuff(), hasCost(), server::zone::objects::creature::commands::QueueCommand::INSUFFICIENTHAM, server::zone::objects::creature::commands::QueueCommand::INVALIDLOCOMOTION, server::zone::objects::creature::commands::QueueCommand::INVALIDSTATE, server::zone::objects::creature::commands::QueueCommand::INVALIDTARGET, server::zone::objects::scene::SceneObject::isInRange(), ObserverEventType::MEDPACKUSED, parseModifier(), CreatureState::POISONED, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::commands::QueueCommand::server, server::chat::StringIdChatParameter::setTT(), server::chat::StringIdChatParameter::setTU(), skillName, server::zone::objects::creature::commands::QueueCommand::SUCCESS, and server::zone::objects::creature::commands::QueueCommand::TOOFAR.
void DotPackCommand::handleArea (CreatureObject * creature, CreatureObject * areaCenter, DotPack * pharma, float range) inline
Definition at line 104 of file DotPackCommand.h.
References checkTarget(), doAreaMedicActionTarget(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isAttackableBy(), server::zone::objects::scene::SceneObject::isCreatureObject(), and server::zone::objects::scene::SceneObject::isInRange().
Referenced by doQueueCommand().
int DotPackCommand::hasCost (CreatureObject * creature) inline
Definition at line 199 of file DotPackCommand.h.
References CreatureAttribute::FOCUS, server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and CreatureAttribute::MIND.
Referenced by doQueueCommand().
void DotPackCommand::parseModifier (const String & modifier, uint64 & objectId) inline
Definition at line 64 of file DotPackCommand.h.
Referenced by doQueueCommand().
Member Data Documentation
String DotPackCommand::effectName protected
Definition at line 28 of file DotPackCommand.h.
Referenced by DotPackCommand().
String DotPackCommand::skillName protected
Definition at line 29 of file DotPackCommand.h.
Referenced by ApplyDiseaseCommand::ApplyDiseaseCommand(), ApplyPoisonCommand::ApplyPoisonCommand(), and doQueueCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/DotPackCommand.h