Core3: CityAdjustTaxSuiCallback Class Reference
CityAdjustTaxSuiCallback Class Reference
#include <CityAdjustTaxSuiCallback.h>
Public Member Functions
CityAdjustTaxSuiCallback (ZoneServer *server, CityRegion *city)
void run (CreatureObject *player, SuiBox *suiBox, bool cancelPressed, Vector< UnicodeString > *args)
Public Member Functions inherited from server::zone::objects::player::sui::SuiCallback
SuiCallback (ZoneServer *serv)
Private Attributes
ManagedWeakReference
< CityRegion * > cityRegion
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::player::sui::SuiCallback
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 30 of file CityAdjustTaxSuiCallback.h.
Constructor & Destructor Documentation
CityAdjustTaxSuiCallback::CityAdjustTaxSuiCallback (ZoneServer * server, CityRegion * city) inline
Definition at line 34 of file CityAdjustTaxSuiCallback.h.
Member Function Documentation
void CityAdjustTaxSuiCallback::run (CreatureObject * player, SuiBox * suiBox, bool cancelPressed, Vector< UnicodeString > * args) inline virtual
Parameters
player The player that this suibox is assigned to.
suiBox The actual SuiBox object.
cancelPressed Was the cancel button pressed, or was the sui box closed via a similar method. (this might actually be more of a dialogResult type variable)
args A vector of UnicodeStrings containing the arguments passed to the sui box from the client.
Implements server::zone::objects::player::sui::SuiCallback.
Definition at line 40 of file CityAdjustTaxSuiCallback.h.
References server::zone::objects::player::sui::listbox::SuiListBox::getMenuObjectID(), server::zone::objects::player::sui::listbox::SuiListBox::getMenuSize(), server::zone::objects::player::sui::SuiBox::getUsingObject(), server::zone::objects::player::sui::SuiBox::isListBox(), and server::zone::managers::city::CityManager::promptSetTax().
Member Data Documentation
ManagedWeakReference<CityRegion*> CityAdjustTaxSuiCallback::cityRegion private
Definition at line 31 of file CityAdjustTaxSuiCallback.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/callbacks/CityAdjustTaxSuiCallback.h