Core3: WorldSnapshotIff Class Reference
WorldSnapshotIff Class Reference
#include <WorldSnapshotIff.h>
Public Member Functions
WorldSnapshotIff ()
void readObject (IffStream *iffStream)
int getNodeCount ()
WorldSnapshotNode * getNode (int idx)
String getObjectTemplateName (int idx) const
Public Member Functions inherited from IffTemplate
virtual ~IffTemplate ()
Public Member Functions inherited from TemplateData
virtual ~TemplateData ()
Private Attributes
Vector< WorldSnapshotNode > nodes
Vector< String > objectTemplateNameList
Detailed Description
Definition at line 15 of file WorldSnapshotIff.h.
Constructor & Destructor Documentation
WorldSnapshotIff::WorldSnapshotIff ()
Definition at line 10 of file WorldSnapshotIff.cpp.
Member Function Documentation
WorldSnapshotNode* WorldSnapshotIff::getNode (int idx) inline
Definition at line 28 of file WorldSnapshotIff.h.
References nodes.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadSnapshotObjects().
int WorldSnapshotIff::getNodeCount () inline
Definition at line 24 of file WorldSnapshotIff.h.
References nodes.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadSnapshotObjects().
String WorldSnapshotIff::getObjectTemplateName (int idx) const inline
Definition at line 32 of file WorldSnapshotIff.h.
References objectTemplateNameList.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadSnapshotObject().
void WorldSnapshotIff::readObject (IffStream * iffStream) virtual
Implements IffTemplate.
Definition at line 14 of file WorldSnapshotIff.cpp.
References nodes, objectTemplateNameList, and WorldSnapshotNode::parse().
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadSnapshotObjects().
Member Data Documentation
Vector<WorldSnapshotNode> WorldSnapshotIff::nodes private
Definition at line 16 of file WorldSnapshotIff.h.
Referenced by getNode(), getNodeCount(), and readObject().
Vector<String> WorldSnapshotIff::objectTemplateNameList private
Definition at line 17 of file WorldSnapshotIff.h.
Referenced by getObjectTemplateName(), and readObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/snapshot/WorldSnapshotIff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/snapshot/WorldSnapshotIff.cpp