Core3: server::zone::managers::sui::SuiManager Class Reference
server::zone::managers::sui::SuiManager Class Reference
#include <SuiManager.h>
Public Member Functions
SuiManager ()
void handleSuiEventNotification (uint32 boxID, CreatureObject *player, uint32 cancel, Vector< UnicodeString > *args)
void handleStartMusic (CreatureObject *player, SuiBox *suiBox, uint32 cancel, Vector< UnicodeString > *args)
void handleStartDancing (CreatureObject *player, SuiBox *suiBox, uint32 cancel, Vector< UnicodeString > *args)
void handleSetObjectName (CreatureObject *player, SuiBox *suiBox, uint32 cancel, Vector< UnicodeString > *args)
void handleBankTransfer (CreatureObject *player, SuiBox *suiBox, uint32 cancel, Vector< UnicodeString > *args)
void handleFishingAction (CreatureObject *player, SuiBox *suiBox, uint32 cancel, Vector< UnicodeString > *args)
void handleDiagnose (CreatureObject *player, SuiBox *suiBox, uint32 cancel, Vector< UnicodeString > *args)
void handleConsentBox (CreatureObject *player, SuiBox *suiBox, uint32 cancel, Vector< UnicodeString > *args)
void handleCharacterBuilderSelectItem (CreatureObject *player, SuiBox *suiBox, uint32 cancel, Vector< UnicodeString > *args)
void sendKeypadSui (SceneObject *keypad, SceneObject *creatureSceneObject, const String &play, const String &callback)
void sendConfirmSui (SceneObject *terminal, SceneObject *player, const String &play, const String &callback, const String &prompt, const String &button)
void sendMessageBox (SceneObject *usingObject, SceneObject *player, const String &title, const String &text, const String &okButton, const String &screenplay, const String &callback)
void sendInputBox (SceneObject *terminal, SceneObject *player, const String &play, const String &callback, const String &prompt, const String &button)
void sendListBox (SceneObject *usingObject, SceneObject *player, const String &title, const String &text, const uint8 &numOfButtons, const String &cancelButton, const String &otherButton, const String &okButton, const String &screenplay, const String &callback)
void setZoneProcessServer (ZoneProcessServer *srv)
Private Attributes
ManagedReference
< ZoneProcessServer * > server
Detailed Description
Definition at line 83 of file SuiManager.h.
Constructor & Destructor Documentation
SuiManager::SuiManager ()
Definition at line 101 of file SuiManager.cpp.
References server.
Member Function Documentation
void SuiManager::handleBankTransfer (CreatureObject * player, SuiBox * suiBox, uint32 cancel, Vector< UnicodeString > * args)
Definition at line 298 of file SuiManager.cpp.
References server::zone::objects::player::sui::banktransferbox::SuiBankTransferBox::getBank(), server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::player::sui::SuiBox::isBankTransferBox(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::CreatureObject::setBankCredits(), and server::zone::objects::creature::CreatureObject::setCashCredits().
Referenced by handleSuiEventNotification().
void SuiManager::handleCharacterBuilderSelectItem (CreatureObject * player, SuiBox * suiBox, uint32 cancel, Vector< UnicodeString > * args)
Definition at line 369 of file SuiManager.cpp.
References CreatureAttribute::ACTION, server::zone::objects::creature::CreatureObject::addCashCredits(), server::zone::objects::creature::CreatureObject::addDotState(), server::zone::objects::player::PlayerObject::addSuiBox(), CreatureState::BLEEDING, SceneObjectType::CHARACTERBUILDERTERMINAL, server::zone::objects::creature::CreatureObject::clearDots(), server::zone::ZoneServer::createObject(), CreatureState::DISEASED, server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminal::enhanceCharacter(), CharacterBuilderMenuNode::getChildNodeAt(), CharacterBuilderMenuNode::getDisplayName(), CharacterBuilderMenuNode::getParentNode(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getSlottedObject(), CharacterBuilderMenuNode::getTemplateCRC(), CharacterBuilderMenuNode::getTemplatePath(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminal::giveLanguages(), CharacterBuilderMenuNode::hasChildNodes(), server::zone::objects::creature::CreatureObject::hasSkill(), CreatureAttribute::HEALTH, server::zone::objects::player::sui::SuiBox::isCharacterBuilderBox(), server::zone::objects::creature::CreatureObject::isInCombat(), server::zone::objects::player::PlayerObject::maximizeExperience(), CreatureState::ONFIRE, CreatureState::POISONED, server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setShockWounds(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTO(), and server::zone::objects::creature::CreatureObject::setWounds().
Referenced by handleSuiEventNotification().
void SuiManager::handleConsentBox (CreatureObject * player, SuiBox * suiBox, uint32 cancel, Vector< UnicodeString > * args)
Definition at line 539 of file SuiManager.cpp.
References server::zone::objects::player::sui::listbox::SuiListBox::getMenuItemName(), server::zone::objects::player::sui::SuiBox::isListBox(), and UnconsentCommand::unconscent().
Referenced by handleSuiEventNotification().
void SuiManager::handleDiagnose (CreatureObject * player, SuiBox * suiBox, uint32 cancel, Vector< UnicodeString > * args)
Definition at line 536 of file SuiManager.cpp.
Referenced by handleSuiEventNotification().
void SuiManager::handleFishingAction (CreatureObject * player, SuiBox * suiBox, uint32 cancel, Vector< UnicodeString > * args)
Definition at line 328 of file SuiManager.cpp.
References server::zone::objects::player::sui::SuiBox::getBoxID(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server.
Referenced by handleSuiEventNotification().
void SuiManager::handleSetObjectName (CreatureObject * player, SuiBox * suiBox, uint32 cancel, Vector< UnicodeString > * args)
Definition at line 177 of file SuiManager.cpp.
References server::zone::objects::player::sui::SuiBox::getUsingObject(), server::zone::objects::player::sui::SuiBox::isInputBox(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::chat::StringIdChatParameter::setTO().
Referenced by handleSuiEventNotification().
void SuiManager::handleStartDancing (CreatureObject * player, SuiBox * suiBox, uint32 cancel, Vector< UnicodeString > * args)
Definition at line 201 of file SuiManager.cpp.
References SuiWindowType::DANCING_CHANGE, server::zone::objects::creature::CreatureObject::executeObjectControllerAction(), server::zone::objects::player::sui::SuiBox::getBoxID(), server::zone::objects::player::sui::listbox::SuiListBox::getMenuItemName(), and server::zone::objects::player::sui::SuiBox::isListBox().
Referenced by handleSuiEventNotification().
void SuiManager::handleStartMusic (CreatureObject * player, SuiBox * suiBox, uint32 cancel, Vector< UnicodeString > * args)
Definition at line 228 of file SuiManager.cpp.
References SuiWindowType::BAND_CHANGE, SuiWindowType::BAND_START, server::zone::objects::creature::CreatureObject::executeObjectControllerAction(), server::zone::objects::player::sui::SuiBox::getBoxID(), server::zone::objects::player::sui::listbox::SuiListBox::getMenuItemName(), server::zone::objects::creature::CreatureObject::getTargetID(), server::zone::objects::player::sui::SuiBox::isListBox(), SuiWindowType::MUSIC_CHANGE, and SuiWindowType::MUSIC_START.
Referenced by handleSuiEventNotification().
void SuiManager::handleSuiEventNotification (uint32 boxID, CreatureObject * player, uint32 cancel, Vector< UnicodeString > * args)
Definition at line 107 of file SuiManager.cpp.
References SuiWindowType::BAND_CHANGE, SuiWindowType::BAND_START, SuiWindowType::BANK_TRANSFER, SuiWindowType::CHARACTER_BUILDER_LIST, SuiWindowType::DANCING_CHANGE, SuiWindowType::DANCING_START, SuiWindowType::FISHING, server::zone::objects::creature::CreatureObject::getPlayerObject(), handleBankTransfer(), handleCharacterBuilderSelectItem(), handleConsentBox(), handleDiagnose(), handleFishingAction(), handleSetObjectName(), handleStartDancing(), handleStartMusic(), SuiWindowType::MEDIC_CONSENT, SuiWindowType::MEDIC_DIAGNOSE, SuiWindowType::MUSIC_CHANGE, SuiWindowType::MUSIC_START, and SuiWindowType::OBJECT_NAME.
void SuiManager::sendConfirmSui (SceneObject * terminal, SceneObject * player, const String & play, const String & callback, const String & prompt, const String & button)
Definition at line 580 of file SuiManager.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::isCreatureObject(), and server::zone::objects::creature::CreatureObject::sendMessage().
void SuiManager::sendInputBox (SceneObject * terminal, SceneObject * player, const String & play, const String & callback, const String & prompt, const String & button)
Definition at line 609 of file SuiManager.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::isCreatureObject(), and server::zone::objects::creature::CreatureObject::sendMessage().
void SuiManager::sendKeypadSui (SceneObject * keypad, SceneObject * creatureSceneObject, const String & play, const String & callback)
Definition at line 557 of file SuiManager.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::isCreatureObject(), and server::zone::objects::creature::CreatureObject::sendMessage().
void SuiManager::sendListBox (SceneObject * usingObject, SceneObject * player, const String & title, const String & text, const uint8 & numOfButtons, const String & cancelButton, const String & otherButton, const String & okButton, const String & screenplay, const String & callback)
Definition at line 660 of file SuiManager.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::isCreatureObject(), and server::zone::objects::creature::CreatureObject::sendMessage().
void SuiManager::sendMessageBox (SceneObject * usingObject, SceneObject * player, const String & title, const String & text, const String & okButton, const String & screenplay, const String & callback)
Definition at line 635 of file SuiManager.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::isCreatureObject(), and server::zone::objects::creature::CreatureObject::sendMessage().
void server::zone::managers::sui::SuiManager::setZoneProcessServer (ZoneProcessServer * srv) inline
Definition at line 146 of file SuiManager.h.
Member Data Documentation
ManagedReference<ZoneProcessServer*> server::zone::managers::sui::SuiManager::server private
Definition at line 84 of file SuiManager.h.
Referenced by handleFishingAction(), and SuiManager().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/sui/SuiManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/sui/SuiManager.cpp