Core3: ForceShrineMenuComponent Class Reference
ForceShrineMenuComponent Class Reference
#include <ForceShrineMenuComponent.h>
Public Member Functions
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
Detailed Description
Definition at line 37 of file ForceShrineMenuComponent.h.
Member Function Documentation
void ForceShrineMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Viewing components used to craft item, for admins
Reimplemented from TangibleObjectMenuComponent.
Definition at line 21 of file ForceShrineMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), and TangibleObjectMenuComponent::fillObjectMenuResponse().
int ForceShrineMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from TangibleObjectMenuComponent.
Definition at line 28 of file ForceShrineMenuComponent.cpp.
References server::zone::ZoneServer::createObject(), CreaturePosture::CROUCHED, server::zone::Zone::getCreatureManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::getPosture(), server::zone::managers::creature::CreatureManager::getRandomJediTrainer(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::ZoneServer::getZone(), server::zone::ZoneServer::getZoneCount(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::hasSkill(), SuiWindowType::NONE, server::zone::objects::creature::CreatureObject::playEffect(), server::zone::objects::creature::CreatureObject::sendMessage(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/ForceShrineMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/ForceShrineMenuComponent.cpp