Core3: server::zone::managers::director::DirectorManager Class Reference
server::zone::managers::director::DirectorManager Class Reference
#include <DirectorManager.h>
Public Types
enum LUA_ERROR_CODE { NO_ERROR = 0, MAIN_FILE_ERROR, GENERAL_ERROR, INCORRECT_ARGUMENTS }
Public Member Functions
DirectorManager ()
void startGlobalScreenPlays ()
void startScreenPlay (CreatureObject *creatureObject, const String &screenPlayName)
void activateEvent (ScreenPlayTask *task)
ConversationScreen * getNextConversationScreen (const String &luaClass, ConversationTemplate *conversationTemplate, CreatureObject *conversingPlayer, int selectedOption, CreatureObject *conversingNPC)
ConversationScreen * runScreenHandlers (const String &luaClass, ConversationTemplate *conversationTemplate, CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
virtual Lua * getLuaInstance ()
int runScreenPlays ()
Static Public Member Functions
static int writeScreenPlayData (lua_State *L)
static int readScreenPlayData (lua_State *L)
static int clearScreenPlayData (lua_State *L)
static int registerScreenPlay (lua_State *L)
static int includeFile (lua_State *L)
static int createEvent (lua_State *L)
static int createObserver (lua_State *L)
static int spawnMobile (lua_State *L)
static int spawnMobileRandom (lua_State *L)
static int spawnSceneObject (lua_State *L)
static int createLoot (lua_State *L)
static int createLootFromCollection (lua_State *L)
static int spatialChat (lua_State *L)
static int spatialMoodChat (lua_State *L)
static int readSharedMemory (lua_State *L)
static int writeSharedMemory (lua_State *L)
static int deleteSharedMemory (lua_State *L)
static int readStringSharedMemory (lua_State *L)
static int writeStringSharedMemory (lua_State *L)
static int deleteStringSharedMemory (lua_State *L)
static int getSceneObject (lua_State *L)
static int getCreatureObject (lua_State *L)
static int addStartingItemsInto (lua_State *L)
static int addStartingWeaponsInto (lua_State *L)
static int setAuthorizationState (lua_State *L)
static int giveItem (lua_State *L)
static int giveControlDevice (lua_State *L)
static int checkInt64Lua (lua_State *L)
static int getChatMessage (lua_State *L)
static int createConversationScreen (lua_State *L)
static int getRankName (lua_State *L)
static int getRankCost (lua_State *L)
static int getRankDelegateRatioFrom (lua_State *L)
static int getRankDelegateRatioTo (lua_State *L)
static int isHighestRank (lua_State *L)
static int isZoneEnabled (lua_State *L)
static int getFactionPointsCap (lua_State *L)
static int getRegion (lua_State *L)
static int forcePeace (lua_State *L)
static int getObjectTemplatePathByCRC (lua_State *L)
static int getContainerObjectByTemplate (lua_State *L)
static int updateCellPermission (lua_State *L)
static int updateCellPermissionGroup (lua_State *L)
static int setParameterDI (lua_State *L)
static int setParameterDF (lua_State *L)
static int setParameterTO (lua_State *L)
static int setParameterTU (lua_State *L)
static int setParameterTT (lua_State *L)
static int createParameterMessage (lua_State *L)
static int sendParameterMessage (lua_State *L)
static int getTimestamp (lua_State *L)
static int getSpawnPoint (lua_State *L)
static int makeCreatureName (lua_State *L)
static int getGCWDiscount (lua_State *L)
static int getTerrainHeight (lua_State *L)
static int checkArgumentCount (lua_State *L, int args)
static int awardSkill (lua_State *L)
Static Public Attributes
static int DEBUG_MODE = 0
static int ERROR_CODE = NO_ERROR
Private Member Functions
void initializeLuaEngine (Lua *luaEngine)
int loadScreenPlays (Lua *luaEngine)
void loadJediManager (Lua *luaEngine)
Private Attributes
ThreadLocal< Lua * > localLua
VectorMap< String, bool > screenPlays
Reference< DirectorSharedMemory * > sharedMemory
Detailed Description
Definition at line 47 of file DirectorManager.h.
Member Enumeration Documentation
enum server::zone::managers::director::DirectorManager::LUA_ERROR_CODE
Enumerator
NO_ERROR
MAIN_FILE_ERROR
GENERAL_ERROR
INCORRECT_ARGUMENTS
Definition at line 59 of file DirectorManager.h.
Constructor & Destructor Documentation
DirectorManager::DirectorManager ()
Definition at line 63 of file DirectorManager.cpp.
References DEBUG_MODE, screenPlays, and sharedMemory.
Member Function Documentation
void DirectorManager::activateEvent (ScreenPlayTask * task)
Definition at line 1590 of file DirectorManager.cpp.
References getLuaInstance(), ScreenPlayTask::getSceneObject(), ScreenPlayTask::getScreenPlay(), ScreenPlayTask::getTaskKey(), and startScreenPlay().
int DirectorManager::addStartingItemsInto (lua_State * L) static
Definition at line 1196 of file DirectorManager.cpp.
References server::zone::managers::player::creation::PlayerCreationManager::addStartingItemsInto(), checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::addStartingWeaponsInto (lua_State * L) static
Definition at line 1214 of file DirectorManager.cpp.
References server::zone::managers::player::creation::PlayerCreationManager::addStartingWeaponsInto(), checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::awardSkill (lua_State * L) static
Definition at line 1856 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::checkArgumentCount (lua_State * L, int args) static
Definition at line 1845 of file DirectorManager.cpp.
Referenced by addStartingItemsInto(), addStartingWeaponsInto(), awardSkill(), checkInt64Lua(), clearScreenPlayData(), createEvent(), createLoot(), createLootFromCollection(), createObserver(), createParameterMessage(), deleteSharedMemory(), deleteStringSharedMemory(), forcePeace(), getChatMessage(), getContainerObjectByTemplate(), getCreatureObject(), getFactionPointsCap(), getGCWDiscount(), getObjectTemplatePathByCRC(), getRankCost(), getRankDelegateRatioFrom(), getRankDelegateRatioTo(), getRankName(), getRegion(), getSceneObject(), getSpawnPoint(), getTerrainHeight(), giveControlDevice(), giveItem(), includeFile(), isHighestRank(), isZoneEnabled(), makeCreatureName(), readScreenPlayData(), readSharedMemory(), readStringSharedMemory(), registerScreenPlay(), sendParameterMessage(), setAuthorizationState(), setParameterDF(), setParameterDI(), setParameterTO(), setParameterTT(), setParameterTU(), spatialChat(), spatialMoodChat(), spawnMobile(), spawnMobileRandom(), spawnSceneObject(), updateCellPermission(), updateCellPermissionGroup(), writeScreenPlayData(), writeSharedMemory(), and writeStringSharedMemory().
int DirectorManager::checkInt64Lua (lua_State * L) static
Definition at line 558 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::clearScreenPlayData (lua_State * L) static
Definition at line 517 of file DirectorManager.cpp.
References checkArgumentCount(), server::zone::objects::player::PlayerObject::clearScreenPlayData(), server::zone::objects::scene::SceneObject::error(), ERROR_CODE, server::zone::objects::scene::SceneObject::getSlottedObject(), INCORRECT_ARGUMENTS, and server::zone::objects::scene::SceneObject::isPlayerCreature().
Referenced by initializeLuaEngine().
int DirectorManager::createConversationScreen (lua_State * L) static
Definition at line 1608 of file DirectorManager.cpp.
int DirectorManager::createEvent (lua_State * L) static
Definition at line 745 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::createLoot (lua_State * L) static
Definition at line 436 of file DirectorManager.cpp.
References checkArgumentCount(), server::zone::managers::loot::LootManager::createLoot(), ERROR_CODE, server::zone::ZoneServer::getLootManager(), ServerCore::getZoneServer(), and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::createLootFromCollection (lua_State * L) static
Definition at line 457 of file DirectorManager.cpp.
References checkArgumentCount(), server::zone::managers::loot::LootManager::createLootFromCollection(), ERROR_CODE, server::zone::ZoneServer::getLootManager(), ServerCore::getZoneServer(), INCORRECT_ARGUMENTS, and LootGroupCollection::readObject().
Referenced by initializeLuaEngine().
int DirectorManager::createObserver (lua_State * L) static
Definition at line 1492 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, INCORRECT_ARGUMENTS, and server::zone::managers::director::ScreenPlayObserver::setScreenPlay().
Referenced by initializeLuaEngine().
int DirectorManager::createParameterMessage (lua_State * L) static
Definition at line 839 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::deleteSharedMemory (lua_State * L) static
Definition at line 629 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::deleteStringSharedMemory (lua_State * L) static
Definition at line 700 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::forcePeace (lua_State * L) static
Definition at line 1179 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getChatMessage (lua_State * L) static
Definition at line 785 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, INCORRECT_ARGUMENTS, and server::chat::ChatMessage::toString().
Referenced by initializeLuaEngine().
int DirectorManager::getContainerObjectByTemplate (lua_State * L) static
Definition at line 1032 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::getServerObjectCRC(), and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getCreatureObject (lua_State * L) static
Definition at line 1011 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, server::zone::ZoneServer::getObject(), ServerCore::getZoneServer(), and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getFactionPointsCap (lua_State * L) static
Definition at line 1690 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getGCWDiscount (lua_State * L) static
Definition at line 1806 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, server::zone::managers::gcw::GCWManager::getGCWDiscount(), server::zone::Zone::getGCWManager(), server::zone::objects::scene::SceneObject::getZone(), and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
Lua * DirectorManager::getLuaInstance () virtual
Definition at line 1513 of file DirectorManager.cpp.
References initializeLuaEngine(), loadScreenPlays(), and localLua.
Referenced by activateEvent(), getNextConversationScreen(), runScreenHandlers(), and startScreenPlay().
ConversationScreen * DirectorManager::getNextConversationScreen (const String & luaClass, ConversationTemplate * conversationTemplate, CreatureObject * conversingPlayer, int selectedOption, CreatureObject * conversingNPC)
Definition at line 1553 of file DirectorManager.cpp.
References getLuaInstance().
int DirectorManager::getObjectTemplatePathByCRC (lua_State * L) static
Definition at line 1704 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getRankCost (lua_State * L) static
Definition at line 1632 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getRankDelegateRatioFrom (lua_State * L) static
Definition at line 1646 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getRankDelegateRatioTo (lua_State * L) static
Definition at line 1660 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getRankName (lua_State * L) static
Definition at line 1616 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getRegion (lua_State * L) static
Definition at line 980 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, server::zone::Zone::getCreatureManager(), server::zone::managers::creature::CreatureManager::getSpawnArea(), server::zone::ZoneServer::getZone(), ServerCore::getZoneServer(), and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getSceneObject (lua_State * L) static
Definition at line 959 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, server::zone::ZoneServer::getObject(), ServerCore::getZoneServer(), and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getSpawnPoint (lua_State * L) static
Definition at line 1734 of file DirectorManager.cpp.
References checkArgumentCount(), CollisionManager::checkSphereCollision(), ERROR_CODE, server::zone::Zone::getHeight(), server::zone::Zone::getPlanetManager(), server::zone::objects::scene::SceneObject::getZone(), INCORRECT_ARGUMENTS, server::zone::managers::planet::PlanetManager::isBuildingPermittedAt(), server::zone::managers::planet::PlanetManager::isInObjectsNoBuildZone(), and server::zone::Zone::isWithinBoundaries().
Referenced by initializeLuaEngine().
int DirectorManager::getTerrainHeight (lua_State * L) static
Definition at line 1827 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, server::zone::Zone::getHeight(), server::zone::objects::scene::SceneObject::getZone(), and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::getTimestamp (lua_State * L) static
Definition at line 485 of file DirectorManager.cpp.
Referenced by initializeLuaEngine().
int DirectorManager::giveControlDevice (lua_State * L) static
Definition at line 1264 of file DirectorManager.cpp.
References checkArgumentCount(), server::zone::ZoneServer::createObject(), ERROR_CODE, server::zone::objects::scene::SceneObject::getZoneServer(), INCORRECT_ARGUMENTS, and server::zone::objects::scene::SceneObject::transferObject().
Referenced by initializeLuaEngine().
int DirectorManager::giveItem (lua_State * L) static
Definition at line 1234 of file DirectorManager.cpp.
References checkArgumentCount(), server::zone::ZoneServer::createObject(), ERROR_CODE, server::zone::objects::scene::SceneObject::getZoneServer(), INCORRECT_ARGUMENTS, and server::zone::objects::scene::SceneObject::transferObject().
Referenced by initializeLuaEngine().
int DirectorManager::includeFile (lua_State * L) static
Definition at line 581 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, GENERAL_ERROR, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
void DirectorManager::initializeLuaEngine (Lua * luaEngine) private
Definition at line 84 of file DirectorManager.cpp.
References Badge::ACC_BRAVE_SOLDIER, Badge::ACC_FASCINATING_BACKGROUND, Badge::ACC_GOOD_SAMARITAN, Badge::ACC_INTERESTING_PERSONAGE, Badge::ACC_PROFESSIONAL_DEMEANOR, CreatureAttribute::ACTION, addStartingItemsInto(), addStartingWeaponsInto(), awardSkill(), ObserverEventType::BADGEAWARDED, Badge::BDG_ACCOLADE_LIVE_EVENT, Badge::BDG_ACCOLATE_HOME_SHOW, Badge::BDG_CORVETTE_IMP_ASSASSIN, Badge::BDG_CORVETTE_IMP_DESTROY, Badge::BDG_CORVETTE_IMP_RESCUE, Badge::BDG_CORVETTE_NEUTRAL_ASSASSIN, Badge::BDG_CORVETTE_NEUTRAL_DESTROY, Badge::BDG_CORVETTE_NEUTRAL_RESCUE, Badge::BDG_CORVETTE_REB_ASSASSIN, Badge::BDG_CORVETTE_REB_DESTROY, Badge::BDG_CORVETTE_REB_RESCUE, Badge::BDG_EXP_10_BADGES, Badge::BDG_EXP_20_BADGES, Badge::BDG_EXP_30_BADGES, Badge::BDG_EXP_40_BADGES, Badge::BDG_EXP_45_BADGES, Badge::BDG_EXP_COR_BELA_VISTAL_FOUNTAIN, Badge::BDG_EXP_COR_REBEL_HIDEOUT, Badge::BDG_EXP_COR_ROGUE_CORSEC_BASE, Badge::BDG_EXP_COR_TYRENA_THEATER, Badge::BDG_EXP_DAN_DANTARI_VILLAGE1, Badge::BDG_EXP_DAN_DANTARI_VILLAGE2, Badge::BDG_EXP_DAT_CRASHED_SHIP, Badge::BDG_EXP_DAT_IMP_PRISON, Badge::BDG_EXP_END_DULOK_VILLAGE, Badge::BDG_EXP_END_EWOK_LAKE_VILLAGE, Badge::BDG_EXP_END_EWOK_TREE_VILLAGE, Badge::BDG_EXP_END_IMP_OUTPOST, Badge::BDG_EXP_LOK_KIMOGILA_SKELETON, Badge::BDG_EXP_NAB_AMIDALAS_SANDY_BEACH, Badge::BDG_EXP_NAB_DEEJA_FALLS_TOP, Badge::BDG_EXP_NAB_THEED_FALLS_BOTTOM, Badge::BDG_EXP_ROR_IMP_CAMP, Badge::BDG_EXP_ROR_IMP_HYPERDRIVE_FAC, Badge::BDG_EXP_ROR_KOBALA_SPICE_MINE, Badge::BDG_EXP_ROR_REBEL_OUTPOST, Badge::BDG_EXP_TAL_AQUALISH_CAVE, Badge::BDG_EXP_TAL_CREATURE_VILLAGE, Badge::BDG_EXP_TAL_IMP_BASE, Badge::BDG_EXP_TAL_IMP_VS_REB_BATTLE, Badge::BDG_LIBRARY_TRIVIA, Badge::BDG_RACING_AGRILAT_SWAMP, Badge::BDG_RACING_KEREN_CITY, Badge::BDG_RACING_LOK_MARATHON, Badge::BDG_RACING_MOS_ESPA, Badge::BDG_RACING_NARMLE_MEMORIAL, Badge::BDG_RACING_NASHAL_RIVER, Badge::BDG_THM_PARK_IMPERIAL_BADGE, Badge::BDG_THM_PARK_JABBA_BADGE, Badge::BDG_THM_PARK_NYM_BADGE, Badge::BDG_THM_PARK_REBEL_BADGE, CreatureState::BLEEDING, ObserverEventType::CALLFORHELP, ObserverEventType::CHAT, checkInt64Lua(), clearScreenPlayData(), ObserverEventType::CLOSECONTAINER, Badge::COMBAT_1HSWORD_MASTER, Badge::COMBAT_2HSWORD_MASTER, Badge::COMBAT_BOUNTYHUNTER_MASTER, Badge::COMBAT_BRAWLER_MASTER, Badge::COMBAT_CARBINE_MASTER, Badge::COMBAT_COMMANDO_MASTER, Badge::COMBAT_MARKSMAN_MASTER, Badge::COMBAT_PISTOL_MASTER, Badge::COMBAT_POLEARM_MASTER, Badge::COMBAT_RIFLEMAN_MASTER, Badge::COMBAT_SMUGGLER_MASTER, Badge::COMBAT_UNARMED_MASTER, CreatureAttribute::CONSTITUTION, ObserverEventType::CONVERSE, Badge::COUNT_10, Badge::COUNT_100, Badge::COUNT_125, Badge::COUNT_25, Badge::COUNT_5, Badge::COUNT_50, Badge::COUNT_75, Badge::CRAFTING_ARCHITECT_MASTER, Badge::CRAFTING_ARMORSMITH_MASTER, Badge::CRAFTING_ARTISAN_MASTER, Badge::CRAFTING_CHEF_MASTER, Badge::CRAFTING_DROIDENGINEER_MASTER, Badge::CRAFTING_MERCHANT_MASTER, Badge::CRAFTING_SHIPWRIGHT, Badge::CRAFTING_TAILOR_MASTER, Badge::CRAFTING_WEAPONSMITH_MASTER, createEvent(), createLoot(), createLootFromCollection(), createObserver(), createParameterMessage(), ObserverEventType::DAMAGERECEIVED, DEBUG_MODE, ObserverEventType::DEFENDERADDED, ObserverEventType::DEFENDERDROPPED, deleteSharedMemory(), deleteStringSharedMemory(), ObserverEventType::DESTINATIONREACHED, Badge::DESTROY_DEATHSTAR, CreatureState::DISEASED, ObserverEventType::ENTEREDAREA, ObserverEventType::ENTEREDBUILDING, Badge::EVENT_COA2_IMPERIAL, Badge::EVENT_COA2_REBEL, Badge::EVENT_COA3_IMPERIAL, Badge::EVENT_COA3_REBEL, Badge::EVENT_PROJECT_DEAD_EYE_1, ObserverEventType::EXITEDAREA, ObserverEventType::EXITEDBUILDING, Badge::EXP_COR_AGRILAT_SWAMP, Badge::EXP_DAN_JEDI_TEMPLE, Badge::EXP_DAN_REBEL_BASE, Badge::EXP_DAT_ESCAPE_POD, Badge::EXP_DAT_MISTY_FALLS_1, Badge::EXP_DAT_MISTY_FALLS_2, Badge::EXP_DAT_SARLACC, Badge::EXP_DAT_TARPIT, Badge::EXP_LOK_VOLCANO, Badge::EXP_NAB_GUNGAN_SACRED_PLACE, Badge::EXP_TAT_BENS_HUT, Badge::EXP_TAT_ESCAPE_POD, Badge::EXP_TAT_KRAYT_GRAVEYARD, Badge::EXP_TAT_KRAYT_SKELETON, Badge::EXP_TAT_LARS_HOMESTEAD, Badge::EXP_TAT_SARLACC_PIT, Badge::EXP_TAT_TUSKEN_POOL, Badge::EXP_YAV_TEMPLE_BLUELEAF, Badge::EXP_YAV_TEMPLE_EXAR_KUN, Badge::EXP_YAV_TEMPLE_WOOLAMANDER, ObserverEventType::FACTIONBASEFLIPPED, CreatureAttribute::FOCUS, forcePeace(), ObserverEventType::GETATTRIBUTESBATCHCOMMAND, getChatMessage(), getContainerObjectByTemplate(), getCreatureObject(), getFactionPointsCap(), getGCWDiscount(), getObjectTemplatePathByCRC(), getRankCost(), getRankDelegateRatioFrom(), getRankDelegateRatioTo(), getRankName(), getRegion(), getSceneObject(), getSpawnPoint(), getTerrainHeight(), getTimestamp(), giveControlDevice(), giveItem(), ObserverEventType::HEALINGPERFORMED, CreatureAttribute::HEALTH, includeFile(), isHighestRank(), isZoneEnabled(), ObserverEventType::ITEMLOOTED, ObserverEventType::KILLEDCREATURE, makeCreatureName(), ObserverEventType::MEDPACKUSED, CreatureAttribute::MIND, ObserverEventType::NEWBIECLOSEINVENTORY, ObserverEventType::NEWBIEOPENINVENTORY, ObserverEventType::NEWBIETUTORIALHOLOCRON, ObserverEventType::NEWBIETUTORIALZOOMCAMERA, ObserverEventType::OBJECTDESTRUCTION, ObserverEventType::OBJECTINRANGEMOVED, ObserverEventType::OBJECTNAMECHANGED, ObserverEventType::OBJECTRADIALOPENED, ObserverEventType::OBJECTRADIALUSED, ObserverEventType::OBJECTREMOVEDFROMZONE, CreatureState::ONFIRE, ObserverEventType::OPENCONTAINER, Badge::OUTDOORS_BIOENGINEER_MASTER, Badge::OUTDOORS_CREATUREHANDLER_MASTER, Badge::OUTDOORS_RANGER_MASTER, Badge::OUTDOORS_SCOUT_MASTER, Badge::OUTDOORS_SQUADLEADER_MASTER, Badge::PILOT_CORELLIA, Badge::PILOT_IMPERIAL_NAVY_CORELLIA, Badge::PILOT_IMPERIAL_NAVY_NABOO, Badge::PILOT_IMPERIAL_NAVY_TATOOINE, Badge::PILOT_NEUTRAL_NABOO, Badge::PILOT_REBEL_NAVY_CORELLIA, Badge::PILOT_REBEL_NAVY_NABOO, Badge::PILOT_REBEL_NAVY_TATOOINE, Badge::PILOT_TATOOINE, ObserverEventType::PLAYERCHANGEDTARGET, Badge::POI_FACTORYLIBERATION, Badge::POI_HEROMARK, Badge::POI_PRISONBREAK, Badge::POI_RABIDBEAST, Badge::POI_TWOLIARS, CreatureState::POISONED, ObserverEventType::POSITIONCHANGED, CreaturePosture::PRONE, CreatureAttribute::QUICKNESS, readScreenPlayData(), readSharedMemory(), readStringSharedMemory(), registerScreenPlay(), ObserverEventType::SAMPLE, Badge::SCIENCE_COMBATMEDIC_MASTER, Badge::SCIENCE_DOCTOR_MASTER, Badge::SCIENCE_MEDIC_MASTER, ObserverEventType::SELECTCONVERSATION, sendParameterMessage(), setAuthorizationState(), setParameterDF(), setParameterDI(), setParameterTO(), setParameterTT(), setParameterTU(), CreaturePosture::SITTING, CreatureState::SITTINGONCHAIR, Badge::SOCIAL_DANCER_MASTER, Badge::SOCIAL_ENTERTAINER_MASTER, Badge::SOCIAL_IMAGEDESIGNER_MASTER, Badge::SOCIAL_MUSICIAN_MASTER, Badge::SOCIAL_POLITICIAN_MASTER, spatialChat(), ObserverEventType::SPATIALCHATRECEIVED, spatialMoodChat(), spawnMobile(), spawnMobileRandom(), spawnSceneObject(), ObserverEventType::SPECIALATTACK, CreatureAttribute::STAMINA, ObserverEventType::STARTCOMBAT, ObserverEventType::STARTCONVERSATION, ObserverEventType::STOPCONVERSATION, CreatureAttribute::STRENGTH, ObserverEventType::SURVEY, updateCellPermission(), updateCellPermissionGroup(), CreaturePosture::UPRIGHT, Badge::WARREN_COMPASSION, Badge::WARREN_HERO, CreatureAttribute::WILLPOWER, writeScreenPlayData(), writeSharedMemory(), and writeStringSharedMemory().
Referenced by getLuaInstance(), and runScreenPlays().
int DirectorManager::isHighestRank (lua_State * L) static
Definition at line 1674 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::isZoneEnabled (lua_State * L) static
Definition at line 1718 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, server::zone::ZoneServer::getZone(), ServerCore::getZoneServer(), and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
void server::zone::managers::director::DirectorManager::loadJediManager (Lua * luaEngine) private
int DirectorManager::loadScreenPlays (Lua * luaEngine) private
Definition at line 400 of file DirectorManager.cpp.
References DEBUG_MODE, and screenPlays.
Referenced by getLuaInstance(), and runScreenPlays().
int DirectorManager::makeCreatureName (lua_State * L) static
Definition at line 1789 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, INCORRECT_ARGUMENTS, and server::zone::managers::name::NameManager::makeCreatureName().
Referenced by initializeLuaEngine().
int DirectorManager::readScreenPlayData (lua_State * L) static
Definition at line 492 of file DirectorManager.cpp.
References checkArgumentCount(), server::zone::objects::scene::SceneObject::error(), ERROR_CODE, server::zone::objects::scene::SceneObject::getSlottedObject(), INCORRECT_ARGUMENTS, and server::zone::objects::scene::SceneObject::isPlayerCreature().
Referenced by initializeLuaEngine().
int DirectorManager::readSharedMemory (lua_State * L) static
Definition at line 605 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::readStringSharedMemory (lua_State * L) static
Definition at line 676 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::registerScreenPlay (lua_State * L) static
Definition at line 539 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
ConversationScreen * DirectorManager::runScreenHandlers (const String & luaClass, ConversationTemplate * conversationTemplate, CreatureObject * conversingPlayer, CreatureObject * conversingNPC, int selectedOption, ConversationScreen * conversationScreen)
Definition at line 1571 of file DirectorManager.cpp.
References getLuaInstance().
int DirectorManager::runScreenPlays ()
Definition at line 1528 of file DirectorManager.cpp.
References ERROR_CODE, initializeLuaEngine(), loadScreenPlays(), and localLua.
int DirectorManager::sendParameterMessage (lua_State * L) static
Definition at line 823 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, INCORRECT_ARGUMENTS, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by initializeLuaEngine().
int DirectorManager::setAuthorizationState (lua_State * L) static
Definition at line 1298 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, server::zone::objects::scene::SceneObject::getGameObjectType(), INCORRECT_ARGUMENTS, and SceneObjectType::NEWBIETUTORIALTERMINAL.
Referenced by initializeLuaEngine().
int DirectorManager::setParameterDF (lua_State * L) static
Definition at line 875 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, INCORRECT_ARGUMENTS, and server::chat::StringIdChatParameter::setDF().
Referenced by initializeLuaEngine().
int DirectorManager::setParameterDI (lua_State * L) static
Definition at line 859 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, INCORRECT_ARGUMENTS, and server::chat::StringIdChatParameter::setDI().
Referenced by initializeLuaEngine().
int DirectorManager::setParameterTO (lua_State * L) static
Definition at line 891 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, INCORRECT_ARGUMENTS, and server::chat::StringIdChatParameter::setTO().
Referenced by initializeLuaEngine().
int DirectorManager::setParameterTT (lua_State * L) static
Definition at line 923 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, INCORRECT_ARGUMENTS, and server::chat::StringIdChatParameter::setTT().
Referenced by initializeLuaEngine().
int DirectorManager::setParameterTU (lua_State * L) static
Definition at line 907 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, INCORRECT_ARGUMENTS, and server::chat::StringIdChatParameter::setTU().
Referenced by initializeLuaEngine().
int DirectorManager::spatialChat (lua_State * L) static
Definition at line 804 of file DirectorManager.cpp.
References server::chat::ChatManager::broadcastMessage(), checkArgumentCount(), ERROR_CODE, server::zone::ZoneServer::getChatManager(), ServerCore::getZoneServer(), and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::spatialMoodChat (lua_State * L) static
Definition at line 939 of file DirectorManager.cpp.
References server::chat::ChatManager::broadcastMessage(), checkArgumentCount(), ERROR_CODE, server::zone::ZoneServer::getChatManager(), ServerCore::getZoneServer(), and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::spawnMobile (lua_State * L) static
Definition at line 1326 of file DirectorManager.cpp.
References checkArgumentCount(), server::zone::objects::scene::SceneObject::error(), ERROR_CODE, server::zone::Zone::getCreatureManager(), server::zone::ZoneServer::getZone(), ServerCore::getZoneServer(), INCORRECT_ARGUMENTS, server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::creature::AiAgent::setRespawnTimer(), server::zone::managers::creature::CreatureManager::spawnCreature(), and server::zone::objects::scene::SceneObject::updateDirection().
Referenced by initializeLuaEngine().
int DirectorManager::spawnMobileRandom (lua_State * L) static
Definition at line 1379 of file DirectorManager.cpp.
References checkArgumentCount(), server::zone::objects::scene::SceneObject::error(), ERROR_CODE, server::zone::Zone::getCreatureManager(), server::zone::ZoneServer::getZone(), ServerCore::getZoneServer(), INCORRECT_ARGUMENTS, server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::creature::AiAgent::setRandomRespawn(), server::zone::objects::creature::AiAgent::setRespawnTimer(), server::zone::managers::creature::CreatureManager::spawnCreature(), and server::zone::objects::scene::SceneObject::updateDirection().
Referenced by initializeLuaEngine().
int DirectorManager::spawnSceneObject (lua_State * L) static
Definition at line 1433 of file DirectorManager.cpp.
References checkArgumentCount(), server::zone::ZoneServer::createObject(), ERROR_CODE, server::zone::ZoneServer::getObject(), server::zone::ZoneServer::getZone(), ServerCore::getZoneServer(), INCORRECT_ARGUMENTS, and server::zone::objects::scene::SceneObject::transferObject().
Referenced by initializeLuaEngine().
void DirectorManager::startGlobalScreenPlays ()
Definition at line 74 of file DirectorManager.cpp.
References screenPlays, and startScreenPlay().
void DirectorManager::startScreenPlay (CreatureObject * creatureObject, const String & screenPlayName)
Definition at line 1544 of file DirectorManager.cpp.
References getLuaInstance().
Referenced by activateEvent(), and startGlobalScreenPlays().
int DirectorManager::updateCellPermission (lua_State * L) static
Definition at line 1088 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, server::zone::objects::scene::SceneObject::getObjectID(), INCORRECT_ARGUMENTS, server::zone::objects::scene::SceneObject::info(), server::zone::objects::scene::SceneObject::isCellObject(), server::zone::objects::creature::CreatureObject::isCreatureObject(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by initializeLuaEngine().
int DirectorManager::updateCellPermissionGroup (lua_State * L) static
Definition at line 1134 of file DirectorManager.cpp.
References server::zone::objects::group::GroupObject::broadcastMessage(), checkArgumentCount(), ERROR_CODE, server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::scene::SceneObject::getObjectID(), INCORRECT_ARGUMENTS, server::zone::objects::scene::SceneObject::info(), server::zone::objects::scene::SceneObject::isCellObject(), server::zone::objects::creature::CreatureObject::isCreatureObject(), server::zone::objects::creature::CreatureObject::isGrouped(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by initializeLuaEngine().
int DirectorManager::writeScreenPlayData (lua_State * L) static
Definition at line 412 of file DirectorManager.cpp.
References checkArgumentCount(), server::zone::objects::scene::SceneObject::error(), ERROR_CODE, server::zone::objects::scene::SceneObject::getSlottedObject(), INCORRECT_ARGUMENTS, server::zone::objects::scene::SceneObject::isPlayerCreature(), and server::zone::objects::player::PlayerObject::setScreenPlayData().
Referenced by initializeLuaEngine().
int DirectorManager::writeSharedMemory (lua_State * L) static
Definition at line 651 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
int DirectorManager::writeStringSharedMemory (lua_State * L) static
Definition at line 722 of file DirectorManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by initializeLuaEngine().
Member Data Documentation
int DirectorManager::DEBUG_MODE = 0 static
Definition at line 57 of file DirectorManager.h.
Referenced by DirectorManager(), initializeLuaEngine(), and loadScreenPlays().
int DirectorManager::ERROR_CODE = NO_ERROR static
Definition at line 60 of file DirectorManager.h.
Referenced by addStartingItemsInto(), addStartingWeaponsInto(), awardSkill(), checkInt64Lua(), clearScreenPlayData(), createEvent(), createLoot(), createLootFromCollection(), createObserver(), createParameterMessage(), deleteSharedMemory(), deleteStringSharedMemory(), forcePeace(), getChatMessage(), getContainerObjectByTemplate(), getCreatureObject(), getFactionPointsCap(), getGCWDiscount(), getObjectTemplatePathByCRC(), getRankCost(), getRankDelegateRatioFrom(), getRankDelegateRatioTo(), getRankName(), getRegion(), getSceneObject(), getSpawnPoint(), getTerrainHeight(), giveControlDevice(), giveItem(), includeFile(), isHighestRank(), isZoneEnabled(), makeCreatureName(), readScreenPlayData(), readSharedMemory(), readStringSharedMemory(), registerScreenPlay(), runScreenPlays(), sendParameterMessage(), setAuthorizationState(), setParameterDF(), setParameterDI(), setParameterTO(), setParameterTT(), setParameterTU(), spatialChat(), spatialMoodChat(), spawnMobile(), spawnMobileRandom(), spawnSceneObject(), updateCellPermission(), updateCellPermissionGroup(), writeScreenPlayData(), writeSharedMemory(), and writeStringSharedMemory().
ThreadLocal<Lua*> server::zone::managers::director::DirectorManager::localLua private
Definition at line 48 of file DirectorManager.h.
Referenced by getLuaInstance(), and runScreenPlays().
VectorMap<String, bool> server::zone::managers::director::DirectorManager::screenPlays private
Definition at line 49 of file DirectorManager.h.
Referenced by DirectorManager(), loadScreenPlays(), and startGlobalScreenPlays().
Reference<DirectorSharedMemory* > server::zone::managers::director::DirectorManager::sharedMemory private
Definition at line 54 of file DirectorManager.h.
Referenced by DirectorManager().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/DirectorManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/DirectorManager.cpp