Core3: server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation Class Reference
server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation Class Reference
#include <SuiMessageBox.h>
Public Member Functions
SuiMessageBoxImplementation (CreatureObject *player, unsigned int windowType)
SuiMessageBoxImplementation (DummyConstructorParameter *param)
BaseMessage * generateMessage ()
bool isMessageBox ()
operator const SuiMessageBox * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
SuiBoxImplementation (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
SuiBoxImplementation (DummyConstructorParameter *param)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
virtual bool isInputBox ()
virtual bool isListBox ()
virtual bool isTransferBox ()
virtual bool isBankTransferBox ()
virtual bool isSlicingBox ()
virtual bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
operator const SuiBox * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< SuiMessageBox * > _this
Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
WeakReference< SuiBox * > _this
Protected Member Functions
virtual ~SuiMessageBoxImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
virtual ~SuiBoxImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class SuiMessageBox
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Protected Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
ManagedWeakReference
< CreatureObject * > player
Reference< SuiCallback * > suiCallback
unsigned int boxID
ManagedWeakReference
< SceneObject * > usingObject
String handlerStr
String cancelButtonText
bool cancelButton
String okButtonText
bool okButton
String otherButtonText
bool otherButton
String promptTitle
String promptText
int boxType
unsigned int windowType
float forceCloseDistance
Vector< String > headerSets
Vector< String > optionSets
int hdrOptCount
bool hasGenerated
Detailed Description
Definition at line 108 of file SuiMessageBox.h.
Constructor & Destructor Documentation
SuiMessageBoxImplementation::SuiMessageBoxImplementation (CreatureObject * player, unsigned int windowType)
Definition at line 193 of file SuiMessageBox.cpp.
References _initializeImplementation().
SuiMessageBoxImplementation::SuiMessageBoxImplementation (DummyConstructorParameter * param)
Definition at line 79 of file SuiMessageBox.cpp.
References _initializeImplementation().
SuiMessageBoxImplementation::~SuiMessageBoxImplementation () protected virtual
Definition at line 84 of file SuiMessageBox.cpp.
Member Function Documentation
DistributedObjectStub * SuiMessageBoxImplementation::_getStub ()
Definition at line 104 of file SuiMessageBox.cpp.
References _this.
void SuiMessageBoxImplementation::_initializeImplementation () protected
Definition at line 91 of file SuiMessageBox.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SuiMessageBoxImplementation().
void SuiMessageBoxImplementation::_serializationHelperMethod () protected
Definition at line 140 of file SuiMessageBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void SuiMessageBoxImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 99 of file SuiMessageBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_setStub(), and _this.
Referenced by server::zone::objects::player::sui::messagebox::SuiMessageBox::SuiMessageBox().
void SuiMessageBoxImplementation::finalize () protected
Definition at line 88 of file SuiMessageBox.cpp.
BaseMessage * SuiMessageBoxImplementation::generateMessage () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 47 of file SuiMessageBoxImplementation.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::addHeader(), server::zone::objects::player::sui::SuiBoxImplementation::addSetting(), server::zone::objects::player::sui::SuiBoxImplementation::boxID, server::zone::objects::player::sui::SuiBoxImplementation::cancelButton, server::zone::objects::player::sui::SuiBoxImplementation::cancelButtonText, server::zone::objects::player::sui::SuiBoxImplementation::generateBody(), server::zone::objects::player::sui::SuiBoxImplementation::generateFooter(), server::zone::objects::player::sui::SuiBoxImplementation::generateHeader(), server::zone::objects::player::sui::SuiBoxImplementation::hasGenerated, server::zone::objects::player::sui::SuiBoxImplementation::okButtonText, server::zone::objects::player::sui::SuiBoxImplementation::promptText, server::zone::objects::player::sui::SuiBoxImplementation::promptTitle, and server::zone::objects::player::sui::SuiBoxImplementation::setHandlerText().
Referenced by server::zone::objects::player::sui::messagebox::SuiMessageBox::generateMessage().
bool SuiMessageBoxImplementation::isMessageBox () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 198 of file SuiMessageBox.cpp.
Referenced by server::zone::objects::player::sui::messagebox::SuiMessageBox::isMessageBox().
void SuiMessageBoxImplementation::lock (bool doLock = true) protected
Definition at line 112 of file SuiMessageBox.cpp.
References _this.
void SuiMessageBoxImplementation::lock (ManagedObject * obj) protected
Definition at line 116 of file SuiMessageBox.cpp.
References _this.
SuiMessageBoxImplementation::operator const SuiMessageBox * ()
Definition at line 108 of file SuiMessageBox.cpp.
void SuiMessageBoxImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 147 of file SuiMessageBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::initializeTransientMembers(), and readObjectMember().
bool SuiMessageBoxImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 166 of file SuiMessageBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::readObjectMember().
Referenced by readObject().
void SuiMessageBoxImplementation::rlock (bool doLock = true) protected
Definition at line 120 of file SuiMessageBox.cpp.
References _this.
void SuiMessageBoxImplementation::runlock (bool doLock = true) protected
Definition at line 136 of file SuiMessageBox.cpp.
References _this.
void SuiMessageBoxImplementation::unlock (bool doLock = true) protected
Definition at line 132 of file SuiMessageBox.cpp.
References _this.
void SuiMessageBoxImplementation::wlock (bool doLock = true) protected
Definition at line 124 of file SuiMessageBox.cpp.
References _this.
void SuiMessageBoxImplementation::wlock (ManagedObject * obj) protected
Definition at line 128 of file SuiMessageBox.cpp.
References _this.
void SuiMessageBoxImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 176 of file SuiMessageBox.cpp.
References writeObjectMembers().
int SuiMessageBoxImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 183 of file SuiMessageBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class SuiMessageBox friend
Definition at line 153 of file SuiMessageBox.h.
Member Data Documentation
WeakReference<SuiMessageBox*> server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::_this
Definition at line 119 of file SuiMessageBox.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/messagebox/SuiMessageBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/messagebox/SuiMessageBox.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/messagebox/SuiMessageBoxImplementation.cpp