Core3: server::zone::managers::guild::GuildManagerAdapter Class Reference
server::zone::managers::guild::GuildManagerAdapter Class Reference
#include <GuildManager.h>
Public Member Functions
GuildManagerAdapter (GuildManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setChatManager (ChatManager *chatmanager)
void sendGuildListTo (CreatureObject *player, const String &guildFilter)
void addPendingGuild (unsigned long long playerID, const String &guildName)
void removePendingGuild (unsigned long long playerID)
String getPendingGuildName (unsigned long long playerID)
void addSponsoredPlayer (unsigned long long playerID, GuildObject *guild)
void removeSponsoredPlayer (unsigned long long playerID)
bool isCreatingGuild (unsigned long long playerID)
bool isSponsoredPlayer (unsigned long long playerID)
GuildObject * getSponsoredGuild (unsigned long long playerID)
void sendBaselinesTo (CreatureObject *player)
void loadGuilds ()
void sendGuildCreateNameTo (CreatureObject *player, GuildTerminal *guildTerminal)
void sendGuildCreateAbbrevTo (CreatureObject *player, GuildTerminal *guildTerminal)
void sendGuildInformationTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildMemberListTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildMemberOptionsTo (CreatureObject *player, GuildObject *guild, unsigned long long memberID, GuildTerminal *guildTerminal)
void sendGuildDisbandConfirmTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildSponsoredListTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildSponsoredOptionsTo (CreatureObject *player, GuildObject *guild, unsigned long long playerID, GuildTerminal *guildTerminal)
void sendGuildSponsorTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildSponsorVerifyTo (CreatureObject *player, CreatureObject *target)
void sendGuildKickPromptTo (CreatureObject *player, CreatureObject *target)
void sendGuildSetTitleTo (CreatureObject *player, CreatureObject *target)
void sendGuildWarStatusTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void promptAddNewEnemy (CreatureObject *player, GuildObject *guild, SceneObject *terminal)
void toggleWarStatus (CreatureObject *player, GuildObject *guild, unsigned long long guildoid)
void declareWarByName (CreatureObject *player, GuildObject *guild, const String &search)
void updateWarStatusToWaringGuild (GuildObject *guild, GuildObject *waringGuild)
void sendMemberPermissionsTo (CreatureObject *player, unsigned long long targetID, GuildTerminal *guildTerminal)
bool validateGuildName (CreatureObject *player, const String &guildName)
bool validateGuildAbbrev (CreatureObject *player, const String &guildAbbrev)
bool guildNameExists (const String &guildName)
bool guildAbbrevExists (const String &guildAbbrev)
GuildObject * createGuild (CreatureObject *player, GuildTerminal *guildTerminal, const String &guildName, const String &guildAbbrev)
bool disbandGuild (CreatureObject *player, GuildObject *guild)
void sponsorPlayer (CreatureObject *player, GuildTerminal *guildTerminal, const String &playerName)
void acceptSponsorshipRequest (CreatureObject *player, CreatureObject *target)
void acceptSponsoredPlayer (CreatureObject *player, unsigned long long targetID)
void kickMember (CreatureObject *player, CreatureObject *target)
void leaveGuild (CreatureObject *player, GuildObject *guild)
void setMemberTitle (CreatureObject *player, CreatureObject *target, const String &title)
void setAllegianceTo (CreatureObject *player, unsigned long long targetID, GuildTerminal *guildTerminal)
void toggleGuildPermission (CreatureObject *player, unsigned long long targetID, int permissionIndex, GuildTerminal *guildTerminal)
ChatRoom * createGuildChannels (GuildObject *guild)
void sendGuildTransferTo (CreatureObject *player, GuildTerminal *guildTerminal)
void sendTransferAckTo (CreatureObject *player, const String &newOwnerName, SceneObject *guildTerminal)
void transferLeadership (CreatureObject *newOwner, CreatureObject *oldOwner, SceneObject *guildTerminal)
void sendAcceptLotsTo (CreatureObject *newOwner, GuildTerminal *guildTerminal)
void transferGuildHall (CreatureObject *newOwner, SceneObject *guildTerminal)
GuildObject * getGuildFromAbbrev (const String &guildAbbrev)
Detailed Description
Definition at line 415 of file GuildManager.h.
Constructor & Destructor Documentation
GuildManagerAdapter::GuildManagerAdapter (GuildManager * impl)
Definition at line 1095 of file GuildManager.cpp.
Member Function Documentation
void GuildManagerAdapter::acceptSponsoredPlayer (CreatureObject * player, unsigned long long targetID)
Definition at line 1526 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::acceptSponsorshipRequest (CreatureObject * player, CreatureObject * target)
Definition at line 1522 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::addPendingGuild (unsigned long long playerID, const String & guildName)
Definition at line 1382 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::addSponsoredPlayer (unsigned long long playerID, GuildObject * guild)
Definition at line 1394 of file GuildManager.cpp.
Referenced by invokeMethod().
GuildObject * GuildManagerAdapter::createGuild (CreatureObject * player, GuildTerminal * guildTerminal, const String & guildName, const String & guildAbbrev)
Definition at line 1510 of file GuildManager.cpp.
Referenced by invokeMethod().
ChatRoom * GuildManagerAdapter::createGuildChannels (GuildObject * guild)
Definition at line 1550 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::declareWarByName (CreatureObject * player, GuildObject * guild, const String & search)
Definition at line 1482 of file GuildManager.cpp.
Referenced by invokeMethod().
bool GuildManagerAdapter::disbandGuild (CreatureObject * player, GuildObject * guild)
Definition at line 1514 of file GuildManager.cpp.
Referenced by invokeMethod().
GuildObject * GuildManagerAdapter::getGuildFromAbbrev (const String & guildAbbrev)
Definition at line 1574 of file GuildManager.cpp.
Referenced by invokeMethod().
String GuildManagerAdapter::getPendingGuildName (unsigned long long playerID)
Definition at line 1390 of file GuildManager.cpp.
Referenced by invokeMethod().
GuildObject * GuildManagerAdapter::getSponsoredGuild (unsigned long long playerID)
Definition at line 1410 of file GuildManager.cpp.
Referenced by invokeMethod().
bool GuildManagerAdapter::guildAbbrevExists (const String & guildAbbrev)
Definition at line 1506 of file GuildManager.cpp.
Referenced by invokeMethod().
bool GuildManagerAdapter::guildNameExists (const String & guildName)
Definition at line 1502 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1098 of file GuildManager.cpp.
References acceptSponsoredPlayer(), acceptSponsorshipRequest(), addPendingGuild(), addSponsoredPlayer(), createGuild(), createGuildChannels(), declareWarByName(), disbandGuild(), getGuildFromAbbrev(), getPendingGuildName(), getSponsoredGuild(), guildAbbrevExists(), guildNameExists(), isCreatingGuild(), isSponsoredPlayer(), kickMember(), leaveGuild(), loadGuilds(), promptAddNewEnemy(), removePendingGuild(), removeSponsoredPlayer(), RPC_ACCEPTSPONSOREDPLAYER__CREATUREOBJECT_LONG_, RPC_ACCEPTSPONSORSHIPREQUEST__CREATUREOBJECT_CREATUREOBJECT_, RPC_ADDPENDINGGUILD__LONG_STRING_, RPC_ADDSPONSOREDPLAYER__LONG_GUILDOBJECT_, RPC_CREATEGUILD__CREATUREOBJECT_GUILDTERMINAL_STRING_STRING_, RPC_CREATEGUILDCHANNELS__GUILDOBJECT_, RPC_DECLAREWARBYNAME__CREATUREOBJECT_GUILDOBJECT_STRING_, RPC_DISBANDGUILD__CREATUREOBJECT_GUILDOBJECT_, RPC_GETGUILDFROMABBREV__STRING_, RPC_GETPENDINGGUILDNAME__LONG_, RPC_GETSPONSOREDGUILD__LONG_, RPC_GUILDABBREVEXISTS__STRING_, RPC_GUILDNAMEEXISTS__STRING_, RPC_ISCREATINGGUILD__LONG_, RPC_ISSPONSOREDPLAYER__LONG_, RPC_KICKMEMBER__CREATUREOBJECT_CREATUREOBJECT_, RPC_LEAVEGUILD__CREATUREOBJECT_GUILDOBJECT_, RPC_LOADGUILDS__, RPC_PROMPTADDNEWENEMY__CREATUREOBJECT_GUILDOBJECT_SCENEOBJECT_, RPC_REMOVEPENDINGGUILD__LONG_, RPC_REMOVESPONSOREDPLAYER__LONG_, RPC_SENDACCEPTLOTSTO__CREATUREOBJECT_GUILDTERMINAL_, RPC_SENDBASELINESTO__CREATUREOBJECT_, RPC_SENDGUILDCREATEABBREVTO__CREATUREOBJECT_GUILDTERMINAL_, RPC_SENDGUILDCREATENAMETO__CREATUREOBJECT_GUILDTERMINAL_, RPC_SENDGUILDDISBANDCONFIRMTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, RPC_SENDGUILDINFORMATIONTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, RPC_SENDGUILDKICKPROMPTTO__CREATUREOBJECT_CREATUREOBJECT_, RPC_SENDGUILDLISTTO__CREATUREOBJECT_STRING_, RPC_SENDGUILDMEMBERLISTTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, RPC_SENDGUILDMEMBEROPTIONSTO__CREATUREOBJECT_GUILDOBJECT_LONG_GUILDTERMINAL_, RPC_SENDGUILDSETTITLETO__CREATUREOBJECT_CREATUREOBJECT_, RPC_SENDGUILDSPONSOREDLISTTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, RPC_SENDGUILDSPONSOREDOPTIONSTO__CREATUREOBJECT_GUILDOBJECT_LONG_GUILDTERMINAL_, RPC_SENDGUILDSPONSORTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, RPC_SENDGUILDSPONSORVERIFYTO__CREATUREOBJECT_CREATUREOBJECT_, RPC_SENDGUILDTRANSFERTO__CREATUREOBJECT_GUILDTERMINAL_, RPC_SENDGUILDWARSTATUSTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, RPC_SENDMEMBERPERMISSIONSTO__CREATUREOBJECT_LONG_GUILDTERMINAL_, RPC_SENDTRANSFERACKTO__CREATUREOBJECT_STRING_SCENEOBJECT_, RPC_SETALLEGIANCETO__CREATUREOBJECT_LONG_GUILDTERMINAL_, RPC_SETCHATMANAGER__CHATMANAGER_, RPC_SETMEMBERTITLE__CREATUREOBJECT_CREATUREOBJECT_STRING_, RPC_SPONSORPLAYER__CREATUREOBJECT_GUILDTERMINAL_STRING_, RPC_TOGGLEGUILDPERMISSION__CREATUREOBJECT_LONG_INT_GUILDTERMINAL_, RPC_TOGGLEWARSTATUS__CREATUREOBJECT_GUILDOBJECT_LONG_, RPC_TRANSFERGUILDHALL__CREATUREOBJECT_SCENEOBJECT_, RPC_TRANSFERLEADERSHIP__CREATUREOBJECT_CREATUREOBJECT_SCENEOBJECT_, RPC_UPDATEWARSTATUSTOWARINGGUILD__GUILDOBJECT_GUILDOBJECT_, RPC_VALIDATEGUILDABBREV__CREATUREOBJECT_STRING_, RPC_VALIDATEGUILDNAME__CREATUREOBJECT_STRING_, sendAcceptLotsTo(), sendBaselinesTo(), sendGuildCreateAbbrevTo(), sendGuildCreateNameTo(), sendGuildDisbandConfirmTo(), sendGuildInformationTo(), sendGuildKickPromptTo(), sendGuildListTo(), sendGuildMemberListTo(), sendGuildMemberOptionsTo(), sendGuildSetTitleTo(), sendGuildSponsoredListTo(), sendGuildSponsoredOptionsTo(), sendGuildSponsorTo(), sendGuildSponsorVerifyTo(), sendGuildTransferTo(), sendGuildWarStatusTo(), sendMemberPermissionsTo(), sendTransferAckTo(), setAllegianceTo(), setChatManager(), setMemberTitle(), sponsorPlayer(), toggleGuildPermission(), toggleWarStatus(), transferGuildHall(), transferLeadership(), updateWarStatusToWaringGuild(), validateGuildAbbrev(), and validateGuildName().
bool GuildManagerAdapter::isCreatingGuild (unsigned long long playerID)
Definition at line 1402 of file GuildManager.cpp.
Referenced by invokeMethod().
bool GuildManagerAdapter::isSponsoredPlayer (unsigned long long playerID)
Definition at line 1406 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::kickMember (CreatureObject * player, CreatureObject * target)
Definition at line 1530 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::leaveGuild (CreatureObject * player, GuildObject * guild)
Definition at line 1534 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::loadGuilds ()
Definition at line 1418 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::promptAddNewEnemy (CreatureObject * player, GuildObject * guild, SceneObject * terminal)
Definition at line 1474 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::removePendingGuild (unsigned long long playerID)
Definition at line 1386 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::removeSponsoredPlayer (unsigned long long playerID)
Definition at line 1398 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendAcceptLotsTo (CreatureObject * newOwner, GuildTerminal * guildTerminal)
Definition at line 1566 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendBaselinesTo (CreatureObject * player)
Definition at line 1414 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildCreateAbbrevTo (CreatureObject * player, GuildTerminal * guildTerminal)
Definition at line 1426 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildCreateNameTo (CreatureObject * player, GuildTerminal * guildTerminal)
Definition at line 1422 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildDisbandConfirmTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 1442 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildInformationTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 1430 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildKickPromptTo (CreatureObject * player, CreatureObject * target)
Definition at line 1462 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildListTo (CreatureObject * player, const String & guildFilter)
Definition at line 1378 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildMemberListTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 1434 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildMemberOptionsTo (CreatureObject * player, GuildObject * guild, unsigned long long memberID, GuildTerminal * guildTerminal)
Definition at line 1438 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildSetTitleTo (CreatureObject * player, CreatureObject * target)
Definition at line 1466 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildSponsoredListTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 1446 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildSponsoredOptionsTo (CreatureObject * player, GuildObject * guild, unsigned long long playerID, GuildTerminal * guildTerminal)
Definition at line 1450 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildSponsorTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 1454 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildSponsorVerifyTo (CreatureObject * player, CreatureObject * target)
Definition at line 1458 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildTransferTo (CreatureObject * player, GuildTerminal * guildTerminal)
Definition at line 1554 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendGuildWarStatusTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 1470 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendMemberPermissionsTo (CreatureObject * player, unsigned long long targetID, GuildTerminal * guildTerminal)
Definition at line 1490 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sendTransferAckTo (CreatureObject * player, const String & newOwnerName, SceneObject * guildTerminal)
Definition at line 1558 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::setAllegianceTo (CreatureObject * player, unsigned long long targetID, GuildTerminal * guildTerminal)
Definition at line 1542 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::setChatManager (ChatManager * chatmanager)
Definition at line 1374 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::setMemberTitle (CreatureObject * player, CreatureObject * target, const String & title)
Definition at line 1538 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::sponsorPlayer (CreatureObject * player, GuildTerminal * guildTerminal, const String & playerName)
Definition at line 1518 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::toggleGuildPermission (CreatureObject * player, unsigned long long targetID, int permissionIndex, GuildTerminal * guildTerminal)
Definition at line 1546 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::toggleWarStatus (CreatureObject * player, GuildObject * guild, unsigned long long guildoid)
Definition at line 1478 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::transferGuildHall (CreatureObject * newOwner, SceneObject * guildTerminal)
Definition at line 1570 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::transferLeadership (CreatureObject * newOwner, CreatureObject * oldOwner, SceneObject * guildTerminal)
Definition at line 1562 of file GuildManager.cpp.
Referenced by invokeMethod().
void GuildManagerAdapter::updateWarStatusToWaringGuild (GuildObject * guild, GuildObject * waringGuild)
Definition at line 1486 of file GuildManager.cpp.
Referenced by invokeMethod().
bool GuildManagerAdapter::validateGuildAbbrev (CreatureObject * player, const String & guildAbbrev)
Definition at line 1498 of file GuildManager.cpp.
Referenced by invokeMethod().
bool GuildManagerAdapter::validateGuildName (CreatureObject * player, const String & guildName)
Definition at line 1494 of file GuildManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/guild/GuildManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/guild/GuildManager.cpp