Core3: server::zone::objects::player::sessions::FindSession Class Reference
server::zone::objects::player::sessions::FindSession Class Reference
#include <FindSession.h>
Public Member Functions
FindSession (CreatureObject *pl)
int initializeSession ()
int cancelSession ()
int clearSession ()
void initalizeFindMenu ()
void addWaypoint (float x, float y, const String &name)
void findPlanetaryObject (String &maplocationtype)
void clearWaypoint ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
FindSession (DummyConstructorParameter *param)
virtual ~FindSession ()
Friends
class FindSessionHelper
Detailed Description
Definition at line 50 of file FindSession.h.
Constructor & Destructor Documentation
FindSession::FindSession (CreatureObject * pl)
Definition at line 15 of file FindSession.cpp.
References server::zone::objects::player::sessions::FindSessionImplementation::_setStub().
FindSession::FindSession (DummyConstructorParameter * param) protected
Definition at line 22 of file FindSession.cpp.
FindSession::~FindSession () protected virtual
Definition at line 26 of file FindSession.cpp.
Member Function Documentation
DistributedObjectServant * FindSession::_getImplementation ()
Definition at line 117 of file FindSession.cpp.
Referenced by addWaypoint(), cancelSession(), clearSession(), clearWaypoint(), findPlanetaryObject(), initalizeFindMenu(), and initializeSession().
DistributedObjectServant * FindSession::_getImplementationForRead ()
Definition at line 123 of file FindSession.cpp.
void FindSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 127 of file FindSession.cpp.
void FindSession::addWaypoint (float x, float y, const String & name)
Definition at line 79 of file FindSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::FindSessionImplementation::addWaypoint(), and RPC_ADDWAYPOINT__FLOAT_FLOAT_STRING_.
int FindSession::cancelSession ()
Definition at line 44 of file FindSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::FindSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
Referenced by FindSessionSuiCallback::run().
int FindSession::clearSession ()
Definition at line 57 of file FindSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::FindSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
void FindSession::clearWaypoint ()
Definition at line 104 of file FindSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::FindSessionImplementation::clearWaypoint(), and RPC_CLEARWAYPOINT__.
void FindSession::findPlanetaryObject (String & maplocationtype)
Definition at line 95 of file FindSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::FindSessionImplementation::findPlanetaryObject().
void FindSession::initalizeFindMenu ()
Definition at line 70 of file FindSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::FindSessionImplementation::initalizeFindMenu().
int FindSession::initializeSession ()
Definition at line 31 of file FindSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::FindSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
Friends And Related Function Documentation
friend class FindSessionHelper friend
Definition at line 78 of file FindSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/FindSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/FindSession.cpp