Core3: RegionMap Class Reference
RegionMap Class Reference
#include <RegionMap.h>
Public Member Functions
RegionMap ()
~RegionMap ()
void addRegion (CityRegion *region)
void dropRegion (const String &regionName)
CityRegion * getRegionAt (float x, float y)
bool containsRegion (const String &name)
CityRegion * getRegion (int index)
CityRegion * getRegion (const String &name)
int getTotalRegions ()
Private Attributes
VectorMap< String,
ManagedReference< CityRegion * > > regions
Detailed Description
Definition at line 16 of file RegionMap.h.
Constructor & Destructor Documentation
RegionMap::RegionMap () inline
Definition at line 20 of file RegionMap.h.
References regions.
RegionMap::~RegionMap () inline
Definition at line 25 of file RegionMap.h.
Member Function Documentation
void RegionMap::addRegion (CityRegion * region) inline
Definition at line 28 of file RegionMap.h.
References server::zone::objects::region::CityRegion::getRegionName(), and regions.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadClientRegions().
bool RegionMap::containsRegion (const String & name) inline
Definition at line 67 of file RegionMap.h.
References regions.
void RegionMap::dropRegion (const String & regionName) inline
Definition at line 36 of file RegionMap.h.
References regions.
CityRegion* RegionMap::getRegion (int index) inline
Definition at line 71 of file RegionMap.h.
References regions.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadClientRegions(), server::zone::managers::planet::PlanetManagerImplementation::validateClientCityInRange(), and server::zone::managers::planet::PlanetManagerImplementation::validateRegionName().
CityRegion* RegionMap::getRegion (const String & name) inline
Definition at line 75 of file RegionMap.h.
References regions.
CityRegion* RegionMap::getRegionAt (float x, float y) inline
Gets the first city region in the region map found at the specified coordinates.
Parameters
x The x coordinate.
y The y coordinate.
Returns
Returns a city region or NULL if one was not found.
Definition at line 50 of file RegionMap.h.
References server::zone::objects::region::CityRegion::containsPoint(), and regions.
int RegionMap::getTotalRegions () inline
Definition at line 79 of file RegionMap.h.
References regions.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadClientRegions(), server::zone::managers::planet::PlanetManagerImplementation::validateClientCityInRange(), and server::zone::managers::planet::PlanetManagerImplementation::validateRegionName().
Member Data Documentation
VectorMap<String, ManagedReference<CityRegion*> > RegionMap::regions private
Definition at line 17 of file RegionMap.h.
Referenced by addRegion(), containsRegion(), dropRegion(), getRegion(), getRegionAt(), getTotalRegions(), and RegionMap().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/RegionMap.h