Core3: DeleteCharactersTask Class Reference
DeleteCharactersTask Class Reference
#include <DeleteCharactersTask.h>
Public Member Functions
DeleteCharactersTask ()
void run ()
void updateDeletedCharacters ()
Private Attributes
SortedVector< uint64 > deletedCharacters
Detailed Description
Definition at line 16 of file DeleteCharactersTask.h.
Constructor & Destructor Documentation
DeleteCharactersTask::DeleteCharactersTask () inline
Definition at line 20 of file DeleteCharactersTask.h.
References deletedCharacters.
Member Function Documentation
void DeleteCharactersTask::run () inline
Definition at line 24 of file DeleteCharactersTask.h.
References deletedCharacters, server::zone::ZoneServer::getGalaxyID(), server::zone::ZoneServer::getObject(), ServerCore::getZoneServer(), and ServerDatabase::instance().
void DeleteCharactersTask::updateDeletedCharacters () inline
Definition at line 62 of file DeleteCharactersTask.h.
References deletedCharacters, and ServerDatabase::instance().
Member Data Documentation
SortedVector<uint64> DeleteCharactersTask::deletedCharacters private
Definition at line 17 of file DeleteCharactersTask.h.
Referenced by DeleteCharactersTask(), run(), and updateDeletedCharacters().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/object/DeleteCharactersTask.h