Core3: BitmapGroup Class Reference
BitmapGroup Class Reference
#include <BitmapGroup.h>
Public Member Functions
BitmapGroup ()
~BitmapGroup ()
void parseFromIffStream (engine::util::IffStream *iffStream)
void parseFromIffStream (engine::util::IffStream *iffStream, Version<'0000'>)
TargaBitmap * getBitmap (int index)
Public Member Functions inherited from TemplateVariable<'MGRP'>
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Private Attributes
Vector< BitMapFamily * > mfams
VectorMap< uint32, TargaBitmap * > mfrcs
Detailed Description
Definition at line 16 of file BitmapGroup.h.
Constructor & Destructor Documentation
BitmapGroup::BitmapGroup () inline
Definition at line 21 of file BitmapGroup.h.
BitmapGroup::~BitmapGroup () inline
Definition at line 24 of file BitmapGroup.h.
References mfams.
Member Function Documentation
TargaBitmap* BitmapGroup::getBitmap (int index) inline
Definition at line 57 of file BitmapGroup.h.
References mfrcs.
Referenced by FilterBitmap::process().
void BitmapGroup::parseFromIffStream (engine::util::IffStream * iffStream) inline virtual
Reimplemented from TemplateVariable<'MGRP'>.
Definition at line 29 of file BitmapGroup.h.
void BitmapGroup::parseFromIffStream (engine::util::IffStream * iffStream, Version<'0000'>) inline
Definition at line 46 of file BitmapGroup.h.
References BitMapFamily::getMap(), BitMapFamily::getVar1(), mfams, mfrcs, and TemplateVariable< formType >::readObject().
Member Data Documentation
Vector<BitMapFamily*> BitmapGroup::mfams private
Definition at line 17 of file BitmapGroup.h.
Referenced by parseFromIffStream(), and ~BitmapGroup().
VectorMap<uint32, TargaBitmap*> BitmapGroup::mfrcs private
Definition at line 18 of file BitmapGroup.h.
Referenced by getBitmap(), and parseFromIffStream().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/BitmapGroup.h