Core3: IffTemplateVariable Class Reference
IffTemplateVariable Class Reference abstract
#include <TemplateVariable.h>
Public Member Functions
virtual ~IffTemplateVariable ()
virtual void readObject (engine::util::IffStream *iffStream)=0
Detailed Description
Definition at line 22 of file TemplateVariable.h.
Constructor & Destructor Documentation
virtual IffTemplateVariable::~IffTemplateVariable () inline virtual
Definition at line 24 of file TemplateVariable.h.
Member Function Documentation
virtual void IffTemplateVariable::readObject (engine::util::IffStream * iffStream) pure virtual
Implemented in TemplateVariable< formType >, TemplateVariable<'FGRP'>, TemplateVariable<'0001'>, TemplateVariable<'LYRS'>, TemplateVariable<'IHDR'>, TemplateVariable<'EGRP'>, TemplateVariable<'ROAD'>, TemplateVariable<'TGEN'>, TemplateVariable<'SGRP'>, TemplateVariable<'LAYR'>, TemplateVariable<'MFAM'>, TemplateVariable<'RGRP'>, TemplateVariable<'PTAT'>, TemplateVariable<'HDTA'>, TemplateVariable<'MGRP'>, TemplateVariable<'FFAM'>, TemplateVariable<'EFAM'>, TemplateVariable<'SGMT'>, TemplateVariable< chunkType >, TemplateVariable<'SFAM'>, TemplateVariable<'MFRC'>, TemplateVariable<'RFAM'>, TerrainMap< chunkType >, TerrainMap<'WMAP'>, TerrainMap<'SMAP'>, and Segment.
Referenced by Layer::parseAffector(), Layer::parseBoundary(), and Layer::parseFilter().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/TemplateVariable.h