Core3: DamageOverTimeList Class Reference
DamageOverTimeList Class Reference
#include <DamageOverTimeList.h>
Public Member Functions
DamageOverTimeList ()
DamageOverTimeList (const DamageOverTimeList &list)
uint64 activateDots (CreatureObject *victim)
uint32 addDot (CreatureObject *victim, uint64 parentObjectID, uint32 duration, uint64 dotType, uint8 pool, uint32 strength, float potency, uint32 defense, int secondaryStrength=0)
bool healState (CreatureObject *victim, uint64 dotType, float reduction)
void clear (CreatureObject *creature)
void sendStartMessage (CreatureObject *victim, uint64 type)
void sendStopMessage (CreatureObject *victim, uint64 type)
void sendIncreaseMessage (CreatureObject *victim, uint64 type)
void sendDecreaseMessage (CreatureObject *victim, uint64 type)
int getStrength (uint8 pool, uint64 dotType)
uint64 generateKey (uint64 dotType, uint8 pool, uint64 parentObjectID)
void setNextTick (Time time)
void setNextTick (uint32 delay)
Time getNextTick ()
bool hasDot ()
bool isNextTickPast ()
Protected Attributes
Time nextTick
bool dot
Detailed Description
Definition at line 14 of file DamageOverTimeList.h.
Constructor & Destructor Documentation
DamageOverTimeList::DamageOverTimeList () inline
Definition at line 19 of file DamageOverTimeList.h.
References dot.
DamageOverTimeList::DamageOverTimeList (const DamageOverTimeList & list) inline
Definition at line 24 of file DamageOverTimeList.h.
References dot, and nextTick.
Member Function Documentation
uint64 DamageOverTimeList::activateDots (CreatureObject * victim)
Definition at line 11 of file DamageOverTimeList.cpp.
References DamageOverTime::applyDot(), CreatureState::BLEEDING, server::zone::objects::creature::CreatureObject::clearState(), CreatureState::DISEASED, dot, DamageOverTime::getNextTick(), DamageOverTime::getType(), DamageOverTime::isPast(), nextTick, DamageOverTime::nextTickPast(), CreatureState::ONFIRE, and CreatureState::POISONED.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::activateStateRecovery(), server::zone::objects::creature::AiAgentImplementation::doRecovery(), and server::zone::objects::player::PlayerObjectImplementation::doRecovery().
uint32 DamageOverTimeList::addDot (CreatureObject * victim, uint64 parentObjectID, uint32 duration, uint64 dotType, uint8 pool, uint32 strength, float potency, uint32 defense, int secondaryStrength = 0)
Definition at line 90 of file DamageOverTimeList.cpp.
References CreatureState::DISEASED, dot, generateKey(), DamageOverTime::getNextTick(), getStrength(), DamageOverTime::initDot(), nextTick, CreatureState::POISONED, sendIncreaseMessage(), sendStartMessage(), and server::zone::objects::creature::CreatureObject::setState().
void DamageOverTimeList::clear (CreatureObject * creature)
Definition at line 215 of file DamageOverTimeList.cpp.
References server::zone::objects::creature::CreatureObject::clearState(), dot, and DamageOverTime::getType().
uint64 DamageOverTimeList::generateKey (uint64 dotType, uint8 pool, uint64 parentObjectID) inline
Definition at line 43 of file DamageOverTimeList.h.
Referenced by addDot().
Time DamageOverTimeList::getNextTick () inline
Definition at line 61 of file DamageOverTimeList.h.
References nextTick.
int DamageOverTimeList::getStrength (uint8 pool, uint64 dotType)
Definition at line 69 of file DamageOverTimeList.cpp.
References DamageOverTime::getAttribute(), DamageOverTime::getStrength(), DamageOverTime::getType(), and DamageOverTime::isPast().
Referenced by addDot().
bool DamageOverTimeList::hasDot () inline
Definition at line 65 of file DamageOverTimeList.h.
References dot.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::activateStateRecovery(), server::zone::objects::creature::AiAgentImplementation::doRecovery(), server::zone::objects::player::PlayerObjectImplementation::doRecovery(), and healState().
bool DamageOverTimeList::healState (CreatureObject * victim, uint64 dotType, float reduction)
Definition at line 174 of file DamageOverTimeList.cpp.
References server::zone::objects::creature::CreatureObject::clearState(), dot, DamageOverTime::getType(), hasDot(), DamageOverTime::isPast(), DamageOverTime::reduceTick(), and sendDecreaseMessage().
bool DamageOverTimeList::isNextTickPast () inline
Definition at line 69 of file DamageOverTimeList.h.
References nextTick.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::activateStateRecovery(), server::zone::objects::creature::AiAgentImplementation::doRecovery(), and server::zone::objects::player::PlayerObjectImplementation::doRecovery().
void DamageOverTimeList::sendDecreaseMessage (CreatureObject * victim, uint64 type)
Definition at line 294 of file DamageOverTimeList.cpp.
References CreatureState::BLEEDING, CreatureState::DISEASED, server::zone::objects::creature::CreatureObject::isPlayerCreature(), CreatureState::ONFIRE, CreatureState::POISONED, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by healState().
void DamageOverTimeList::sendIncreaseMessage (CreatureObject * victim, uint64 type)
Definition at line 274 of file DamageOverTimeList.cpp.
References CreatureState::BLEEDING, CreatureState::DISEASED, server::zone::objects::creature::CreatureObject::isPlayerCreature(), CreatureState::ONFIRE, CreatureState::POISONED, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by addDot().
void DamageOverTimeList::sendStartMessage (CreatureObject * victim, uint64 type)
Definition at line 234 of file DamageOverTimeList.cpp.
References CreatureState::BLEEDING, CreatureState::DISEASED, server::zone::objects::creature::CreatureObject::isPlayerCreature(), CreatureState::ONFIRE, CreatureState::POISONED, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by addDot().
void DamageOverTimeList::sendStopMessage (CreatureObject * victim, uint64 type)
Definition at line 254 of file DamageOverTimeList.cpp.
References CreatureState::BLEEDING, CreatureState::DISEASED, server::zone::objects::creature::CreatureObject::isPlayerCreature(), CreatureState::ONFIRE, CreatureState::POISONED, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
void DamageOverTimeList::setNextTick (Time time) inline
Definition at line 53 of file DamageOverTimeList.h.
References nextTick.
void DamageOverTimeList::setNextTick (uint32 delay) inline
Definition at line 57 of file DamageOverTimeList.h.
References nextTick.
Member Data Documentation
bool DamageOverTimeList::dot protected
Definition at line 17 of file DamageOverTimeList.h.
Referenced by activateDots(), addDot(), clear(), DamageOverTimeList(), hasDot(), and healState().
Time DamageOverTimeList::nextTick protected
Definition at line 16 of file DamageOverTimeList.h.
Referenced by activateDots(), addDot(), DamageOverTimeList(), getNextTick(), isNextTickPast(), and setNextTick().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/damageovertime/DamageOverTimeList.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/damageovertime/DamageOverTimeList.cpp