Core3: Values Class Reference
Values Class Reference
#include <ValuesClasses.h>
Public Member Functions
Values (const String &n, const float &tempmin, const float &tempmax, const int &prec, const bool &filler, const int &combine)
Values (const Values &val)
~Values ()
float getPercentage ()
float getValue ()
float getMaxPercentage ()
float getMinValue ()
float getMaxValue ()
int getPrecision ()
bool isFiller ()
void setFiller (bool in)
String & getName ()
short getCombineType ()
void lockValue ()
void unlockValue ()
void setValue (const float &value)
void setMinValue (const float &value)
void setMaxValue (const float &value)
void setPrecision (const int &value)
void setMaxPercentage (float &value)
void setPercentage (float &value)
void resetValue ()
Private Attributes
VectorMap< String, float > values
String name
float minValue
float maxValue
short precision
short combineType
bool locked
bool experimentalProperties
Detailed Description
Definition at line 56 of file ValuesClasses.h.
Constructor & Destructor Documentation
Values::Values (const String & n, const float & tempmin, const float & tempmax, const int & prec, const bool & filler, const int & combine) inline
Definition at line 66 of file ValuesClasses.h.
References combineType, experimentalProperties, locked, maxValue, minValue, name, precision, and values.
Values::Values (const Values & val) inline
Definition at line 83 of file ValuesClasses.h.
References experimentalProperties, locked, maxValue, minValue, name, precision, and values.
Values::~Values () inline
Definition at line 93 of file ValuesClasses.h.
References values.
Member Function Documentation
short Values::getCombineType () inline
Definition at line 133 of file ValuesClasses.h.
References combineType.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCombineType().
float Values::getMaxPercentage () inline
Definition at line 105 of file ValuesClasses.h.
References values.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentVisiblePercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxPercentage(), Subclasses::getMaxPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxVisiblePercentage(), resetValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage(), and Subclasses::toString().
float Values::getMaxValue () inline
Definition at line 113 of file ValuesClasses.h.
References maxValue.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentVisiblePercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxVisiblePercentage(), Subclasses::hasAllHiddenItems(), and Subclasses::toString().
float Values::getMinValue () inline
Definition at line 109 of file ValuesClasses.h.
References minValue.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentVisiblePercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxVisiblePercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMinValue(), Subclasses::hasAllHiddenItems(), and Subclasses::toString().
String& Values::getName () inline
Definition at line 129 of file ValuesClasses.h.
References name.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCombineType(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertyTitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMinValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getPrecision(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::hasProperty(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::isHidden(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::lockValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::resetValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setHidden(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMinValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setPrecision(), Subclasses::toString(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::unlockValue(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::unsetHidden().
float Values::getPercentage () inline
Definition at line 97 of file ValuesClasses.h.
References values.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentVisiblePercentage(), Subclasses::getPercentage(), and Subclasses::toString().
int Values::getPrecision () inline
Definition at line 117 of file ValuesClasses.h.
References precision.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getPrecision().
float Values::getValue () inline
Definition at line 101 of file ValuesClasses.h.
References values.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentValue(), Subclasses::getValue(), lockValue(), Subclasses::Subclasses(), Subclasses::toString(), and unlockValue().
bool Values::isFiller () inline
Definition at line 121 of file ValuesClasses.h.
References experimentalProperties.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentVisiblePercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxVisiblePercentage(), Subclasses::hasAllHiddenItems(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::isHidden(), and Subclasses::toString().
void Values::lockValue () inline
Definition at line 137 of file ValuesClasses.h.
References getValue(), locked, maxValue, and minValue.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::lockValue().
void Values::resetValue () inline
Definition at line 234 of file ValuesClasses.h.
References getMaxPercentage(), maxValue, minValue, setPercentage(), and setValue().
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::resetValue().
void Values::setFiller (bool in) inline
Definition at line 125 of file ValuesClasses.h.
References experimentalProperties.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setHidden(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::unsetHidden().
void Values::setMaxPercentage (float & value) inline
Definition at line 200 of file ValuesClasses.h.
References locked, and values.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxPercentage(), and Subclasses::setMaxPercentage().
void Values::setMaxValue (const float & value) inline
Definition at line 184 of file ValuesClasses.h.
References locked, and maxValue.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentValue(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxValue().
void Values::setMinValue (const float & value) inline
Definition at line 178 of file ValuesClasses.h.
References locked, and minValue.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentValue(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMinValue().
void Values::setPercentage (float & value) inline
Definition at line 217 of file ValuesClasses.h.
References locked, and values.
Referenced by resetValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage(), and Subclasses::setPercentage().
void Values::setPrecision (const int & value) inline
Definition at line 190 of file ValuesClasses.h.
References locked, and precision.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setPrecision().
void Values::setValue (const float & value) inline
Definition at line 149 of file ValuesClasses.h.
References locked, maxValue, minValue, and values.
Referenced by resetValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentValue(), and Subclasses::setValue().
void Values::unlockValue () inline
Definition at line 143 of file ValuesClasses.h.
References getValue(), locked, maxValue, and minValue.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::unlockValue().
Member Data Documentation
short Values::combineType private
Definition at line 61 of file ValuesClasses.h.
Referenced by getCombineType(), and Values().
bool Values::experimentalProperties private
Definition at line 63 of file ValuesClasses.h.
Referenced by isFiller(), setFiller(), and Values().
bool Values::locked private
Definition at line 62 of file ValuesClasses.h.
Referenced by lockValue(), setMaxPercentage(), setMaxValue(), setMinValue(), setPercentage(), setPrecision(), setValue(), unlockValue(), and Values().
float Values::maxValue private
Definition at line 59 of file ValuesClasses.h.
Referenced by getMaxValue(), lockValue(), resetValue(), setMaxValue(), setValue(), unlockValue(), and Values().
float Values::minValue private
Definition at line 59 of file ValuesClasses.h.
Referenced by getMinValue(), lockValue(), resetValue(), setMinValue(), setValue(), unlockValue(), and Values().
String Values::name private
Definition at line 58 of file ValuesClasses.h.
Referenced by getName(), and Values().
short Values::precision private
Definition at line 60 of file ValuesClasses.h.
Referenced by getPrecision(), setPrecision(), and Values().
VectorMap<String, float> Values::values private
Definition at line 57 of file ValuesClasses.h.
Referenced by getMaxPercentage(), getPercentage(), getValue(), setMaxPercentage(), setPercentage(), setValue(), Values(), and ~Values().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/craftingvalues/ValuesClasses.h