Core3: server::zone::objects::player::sessions::CitySpecializationSessionAdapter Class Reference
server::zone::objects::player::sessions::CitySpecializationSessionAdapter Class Reference
#include <CitySpecializationSession.h>
Public Member Functions
CitySpecializationSessionAdapter (CitySpecializationSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession ()
int sendConfirmationBox (const String &choice)
int acceptChoice ()
int cancelSession ()
int clearSession ()
Detailed Description
Definition at line 183 of file CitySpecializationSession.h.
Constructor & Destructor Documentation
CitySpecializationSessionAdapter::CitySpecializationSessionAdapter (CitySpecializationSession * impl)
Definition at line 317 of file CitySpecializationSession.cpp.
Member Function Documentation
int CitySpecializationSessionAdapter::acceptChoice ()
Definition at line 363 of file CitySpecializationSession.cpp.
Referenced by invokeMethod().
int CitySpecializationSessionAdapter::cancelSession ()
Definition at line 367 of file CitySpecializationSession.cpp.
Referenced by invokeMethod().
int CitySpecializationSessionAdapter::clearSession ()
Definition at line 371 of file CitySpecializationSession.cpp.
Referenced by invokeMethod().
int CitySpecializationSessionAdapter::initializeSession ()
Definition at line 355 of file CitySpecializationSession.cpp.
Referenced by invokeMethod().
void CitySpecializationSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 320 of file CitySpecializationSession.cpp.
References acceptChoice(), cancelSession(), clearSession(), initializeSession(), RPC_ACCEPTCHOICE__, RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_INITIALIZESESSION__, RPC_SENDCONFIRMATIONBOX__STRING_, and sendConfirmationBox().
int CitySpecializationSessionAdapter::sendConfirmationBox (const String & choice)
Definition at line 359 of file CitySpecializationSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CitySpecializationSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CitySpecializationSession.cpp