Core3: NativePool Class Reference
NativePool Class Reference
#include <NativePool.h>
Public Member Functions
NativePool (ResourceSpawner *spawner)
~NativePool ()
void initialize (const String &includes, const String &excludes)
void addZone (const String &zoneName)
void addZoneMap (const String &zoneName)
void removeZone (const String &zoneName)
String healthCheck ()
void print ()
Public Member Functions inherited from ResourcePool
ResourcePool (ResourceSpawner *spawner)
virtual ~ResourcePool ()
void initialize (const String &includes, const String &excludes)
void initializeByTable (LuaObject includes, const String &excludes)
void print ()
Private Member Functions
void addResource (ManagedReference< ResourceSpawn * > resourceSpawn, const String &poolSlot)
bool update ()
Private Attributes
Vector< String > activeResourceZones
Current zones with active resources.
VectorMap< String, VectorMap
< String, ManagedReference
< ResourceSpawn * > > > spawnsPerZone
Friends
class ResourceSpawner
Additional Inherited Members
Static Public Attributes inherited from ResourcePool
static const short NOPOOL = 0
static const short MINIMUMPOOL = 1
static const short RANDOMPOOL = 2
static const short FIXEDPOOL = 3
static const short NATIVEPOOL = 4
static const short MANUALPOOL = 5
Protected Attributes inherited from ResourcePool
VectorMap< String,
ManagedReference
< ResourceSpawn * > > includedResources
Vector< String > excludedResources
ResourceSpawner * resourceSpawner
Detailed Description
The native pool class represents all of the planet specific organic resources
Definition at line 63 of file NativePool.h.
Constructor & Destructor Documentation
NativePool::NativePool (ResourceSpawner * spawner)
Ctor
Parameters
spawner The pointer to the resource spawner object
Definition at line 54 of file NativePool.cpp.
NativePool::~NativePool ()
Dtor
Definition at line 58 of file NativePool.cpp.
References spawnsPerZone.
Member Function Documentation
void NativePool::addResource (ManagedReference< ResourceSpawn * > resourceSpawn, const String & poolSlot) private virtual
Adds resource to this pool
Parameters
resourceSpawn Spawn object to add to the pool
Implements ResourcePool.
Definition at line 97 of file NativePool.cpp.
References ResourcePool::NOPOOL, and spawnsPerZone.
Referenced by ResourceSpawner::loadResourceSpawns().
void NativePool::addZone (const String & zoneName)
Definition at line 72 of file NativePool.cpp.
References activeResourceZones, addZoneMap(), and ResourcePool::includedResources.
Referenced by ResourceSpawner::addZone().
void NativePool::addZoneMap (const String & zoneName)
Definition at line 81 of file NativePool.cpp.
References ResourcePool::includedResources, and spawnsPerZone.
Referenced by addZone(), and initialize().
String NativePool::healthCheck () virtual
Implements ResourcePool.
Definition at line 160 of file NativePool.cpp.
References spawnsPerZone.
Referenced by ResourceSpawner::healthCheck().
void NativePool::initialize (const String & includes, const String & excludes)
Initialized what the pool spawns, and what is excluded
Parameters
includes Comma delimited list of resources to include
excludes Comma delimited list of resources to exclude
Definition at line 62 of file NativePool.cpp.
References activeResourceZones, addZoneMap(), and ResourcePool::initialize().
Referenced by ResourceSpawner::initializeNativePool().
void NativePool::print ()
Print the current state of the Resource Pool
Definition at line 200 of file NativePool.cpp.
References spawnsPerZone.
void NativePool::removeZone (const String & zoneName)
Definition at line 92 of file NativePool.cpp.
References activeResourceZones, and spawnsPerZone.
Referenced by ResourceSpawner::removeZone().
bool NativePool::update () private virtual
The update function checks the ResourceSpawn items in spawnedResources to see if they have expired. If they have not expired, no action is taken, but if they have expired, we replace them according to the rules.
Implements ResourcePool.
Definition at line 117 of file NativePool.cpp.
References ResourceSpawner::createResourceSpawn(), ResourceSpawner::despawn(), ResourcePool::excludedResources, ResourcePool::NATIVEPOOL, ResourcePool::resourceSpawner, server::zone::objects::resource::ResourceSpawn::setSpawnPool(), and spawnsPerZone.
Referenced by ResourceSpawner::shiftResources().
Friends And Related Function Documentation
friend class ResourceSpawner friend
Definition at line 122 of file NativePool.h.
Member Data Documentation
Vector<String> NativePool::activeResourceZones private
Current zones with active resources.
Definition at line 67 of file NativePool.h.
Referenced by addZone(), initialize(), and removeZone().
VectorMap<String, VectorMap<String, ManagedReference<ResourceSpawn*> > > NativePool::spawnsPerZone private
Definition at line 69 of file NativePool.h.
Referenced by addResource(), addZoneMap(), healthCheck(), print(), removeZone(), update(), and ~NativePool().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcepool/NativePool.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcepool/NativePool.cpp