Core3: server::zone::managers::minigames::FishingSession Class Reference
server::zone::managers::minigames::FishingSession Class Reference
#include <FishingSession.h>
Public Member Functions
FishingSession (CreatureObject *player, FishingEvent *event, SceneObject *marker, int nextAction, int fish, unsigned int boxID, int fishingState, const String &mood)
void setEvent (FishingEvent *ev)
void setMood (const String &m)
FishingEvent * getEvent ()
void setNextAction (int action)
int getNextAction ()
void setFishBoxID (unsigned int box)
unsigned int getFishBoxID ()
SceneObject * getMarker ()
void setMarker (SceneObject *mar)
int getFish ()
void setFish (int fi)
int getFishingState ()
void setFishingState (int state)
void setPlayer (CreatureObject *pl)
void update (int nextAction, SceneObject *marker, int fish, unsigned int boxID, int fishingState)
String getMoodString ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
FishingSession (DummyConstructorParameter *param)
virtual ~FishingSession ()
Friends
class FishingSessionHelper
Detailed Description
Definition at line 75 of file FishingSession.h.
Constructor & Destructor Documentation
FishingSession::FishingSession (CreatureObject * player, FishingEvent * event, SceneObject * marker, int nextAction, int fish, unsigned int boxID, int fishingState, const String & mood)
Definition at line 19 of file FishingSession.cpp.
References server::zone::managers::minigames::FishingSessionImplementation::_setStub().
FishingSession::FishingSession (DummyConstructorParameter * param) protected
Definition at line 26 of file FishingSession.cpp.
FishingSession::~FishingSession () protected virtual
Definition at line 30 of file FishingSession.cpp.
Member Function Documentation
DistributedObjectServant * FishingSession::_getImplementation ()
Definition at line 249 of file FishingSession.cpp.
Referenced by getEvent(), getFish(), getFishBoxID(), getFishingState(), getMarker(), getMoodString(), getNextAction(), setEvent(), setFish(), setFishBoxID(), setFishingState(), setMarker(), setMood(), setNextAction(), setPlayer(), and update().
DistributedObjectServant * FishingSession::_getImplementationForRead ()
Definition at line 255 of file FishingSession.cpp.
void FishingSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 259 of file FishingSession.cpp.
FishingEvent * FishingSession::getEvent ()
Definition at line 58 of file FishingSession.cpp.
References _getImplementation(), and server::zone::managers::minigames::FishingSessionImplementation::getEvent().
int FishingSession::getFish ()
Definition at line 148 of file FishingSession.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingSessionImplementation::getFish(), and RPC_GETFISH__.
unsigned int FishingSession::getFishBoxID ()
Definition at line 108 of file FishingSession.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingSessionImplementation::getFishBoxID(), and RPC_GETFISHBOXID__.
Referenced by server::zone::managers::minigames::FishingManagerImplementation::getFishBoxID().
int FishingSession::getFishingState ()
Definition at line 175 of file FishingSession.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingSessionImplementation::getFishingState(), and RPC_GETFISHINGSTATE__.
SceneObject * FishingSession::getMarker ()
Definition at line 121 of file FishingSession.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingSessionImplementation::getMarker(), and RPC_GETMARKER__.
Referenced by server::zone::managers::minigames::FishingManagerImplementation::checkFishingOnPositionUpdate(), and server::zone::managers::minigames::FishingManagerImplementation::getFishMarker().
String FishingSession::getMoodString ()
Definition at line 234 of file FishingSession.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingSessionImplementation::getMoodString(), and RPC_GETMOODSTRING__.
Referenced by server::zone::managers::minigames::FishingManagerImplementation::stopFishing().
int FishingSession::getNextAction ()
Definition at line 81 of file FishingSession.cpp.
References _getImplementation(), server::zone::managers::minigames::FishingSessionImplementation::getNextAction(), and RPC_GETNEXTACTION__.
Referenced by server::zone::managers::minigames::FishingManagerImplementation::fishingStep().
void FishingSession::setEvent (FishingEvent * ev)
Definition at line 35 of file FishingSession.cpp.
References _getImplementation(), and server::zone::managers::minigames::FishingSessionImplementation::setEvent().
Referenced by server::zone::managers::minigames::FishingManagerImplementation::stopFishingEvent().
void FishingSession::setFish (int fi)
Definition at line 161 of file FishingSession.cpp.
References _getImplementation(), RPC_SETFISH__INT_, and server::zone::managers::minigames::FishingSessionImplementation::setFish().
void FishingSession::setFishBoxID (unsigned int box)
Definition at line 94 of file FishingSession.cpp.
References _getImplementation(), RPC_SETFISHBOXID__INT_, and server::zone::managers::minigames::FishingSessionImplementation::setFishBoxID().
Referenced by server::zone::managers::minigames::FishingManagerImplementation::setFishBoxID(), and server::zone::managers::minigames::FishingManagerImplementation::startFishing().
void FishingSession::setFishingState (int state)
Definition at line 188 of file FishingSession.cpp.
References _getImplementation(), RPC_SETFISHINGSTATE__INT_, and server::zone::managers::minigames::FishingSessionImplementation::setFishingState().
Referenced by server::zone::managers::minigames::FishingManagerImplementation::setFishingState().
void FishingSession::setMarker (SceneObject * mar)
Definition at line 134 of file FishingSession.cpp.
References _getImplementation(), RPC_SETMARKER__SCENEOBJECT_, and server::zone::managers::minigames::FishingSessionImplementation::setMarker().
Referenced by server::zone::managers::minigames::FishingManagerImplementation::setFishMarker().
void FishingSession::setMood (const String & m)
Definition at line 44 of file FishingSession.cpp.
References _getImplementation(), RPC_SETMOOD__STRING_, and server::zone::managers::minigames::FishingSessionImplementation::setMood().
void FishingSession::setNextAction (int action)
Definition at line 67 of file FishingSession.cpp.
References _getImplementation(), RPC_SETNEXTACTION__INT_, and server::zone::managers::minigames::FishingSessionImplementation::setNextAction().
Referenced by server::zone::managers::minigames::FishingManagerImplementation::setNextAction().
void FishingSession::setPlayer (CreatureObject * pl)
Definition at line 202 of file FishingSession.cpp.
References _getImplementation(), RPC_SETPLAYER__CREATUREOBJECT_, and server::zone::managers::minigames::FishingSessionImplementation::setPlayer().
void FishingSession::update (int nextAction, SceneObject * marker, int fish, unsigned int boxID, int fishingState)
Definition at line 216 of file FishingSession.cpp.
References _getImplementation(), RPC_UPDATE__INT_SCENEOBJECT_INT_INT_INT_, and server::zone::managers::minigames::FishingSessionImplementation::update().
Friends And Related Function Documentation
friend class FishingSessionHelper friend
Definition at line 121 of file FishingSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingSession.cpp