Core3: server::zone::managers::creature::LairObserver Class Reference
server::zone::managers::creature::LairObserver Class Reference
#include <LairObserver.h>
Public Member Functions
LairObserver ()
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void notifyDestruction (TangibleObject *lair, TangibleObject *attacker, int condition)
bool checkForNewSpawns (TangibleObject *lair, bool forceSpawn=false)
void healLair (TangibleObject *lair, TangibleObject *attacker)
void checkForHeal (TangibleObject *lair, TangibleObject *attacker, bool forceNewUpdate=false)
void doAggro (TangibleObject *lair, TangibleObject *attacker)
void setLairTemplate (LairTemplate *tmpl)
void setDifficulty (int diff)
bool isLairObserver ()
int getLivingCreatureCount ()
int getLairType ()
int getSpawnNumber ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
LairObserver (DummyConstructorParameter *param)
virtual ~LairObserver ()
Friends
class LairObserverHelper
Detailed Description
Definition at line 69 of file LairObserver.h.
Constructor & Destructor Documentation
LairObserver::LairObserver ()
Definition at line 19 of file LairObserver.cpp.
References server::zone::managers::creature::LairObserverImplementation::_setStub().
LairObserver::LairObserver (DummyConstructorParameter * param) protected
Definition at line 26 of file LairObserver.cpp.
LairObserver::~LairObserver () protected virtual
Definition at line 30 of file LairObserver.cpp.
Member Function Documentation
DistributedObjectServant * LairObserver::_getImplementation ()
Definition at line 204 of file LairObserver.cpp.
Referenced by checkForHeal(), checkForNewSpawns(), doAggro(), getLairType(), getLivingCreatureCount(), getSpawnNumber(), healLair(), isLairObserver(), notifyDestruction(), notifyObserverEvent(), setDifficulty(), and setLairTemplate().
DistributedObjectServant * LairObserver::_getImplementationForRead ()
Definition at line 210 of file LairObserver.cpp.
void LairObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 214 of file LairObserver.cpp.
void LairObserver::checkForHeal (TangibleObject * lair, TangibleObject * attacker, bool forceNewUpdate = false)
Definition at line 98 of file LairObserver.cpp.
References _getImplementation(), server::zone::managers::creature::LairObserverImplementation::checkForHeal(), and RPC_CHECKFORHEAL__TANGIBLEOBJECT_TANGIBLEOBJECT_BOOL_.
bool LairObserver::checkForNewSpawns (TangibleObject * lair, bool forceSpawn = false)
Definition at line 68 of file LairObserver.cpp.
References _getImplementation(), server::zone::managers::creature::LairObserverImplementation::checkForNewSpawns(), and RPC_CHECKFORNEWSPAWNS__TANGIBLEOBJECT_BOOL_.
void LairObserver::doAggro (TangibleObject * lair, TangibleObject * attacker)
Definition at line 114 of file LairObserver.cpp.
References _getImplementation(), server::zone::managers::creature::LairObserverImplementation::doAggro(), and RPC_DOAGGRO__TANGIBLEOBJECT_TANGIBLEOBJECT_.
int LairObserver::getLairType ()
Definition at line 178 of file LairObserver.cpp.
References _getImplementation(), server::zone::managers::creature::LairObserverImplementation::getLairType(), and RPC_GETLAIRTYPE__.
int LairObserver::getLivingCreatureCount ()
Definition at line 165 of file LairObserver.cpp.
References _getImplementation(), server::zone::managers::creature::LairObserverImplementation::getLivingCreatureCount(), and RPC_GETLIVINGCREATURECOUNT__.
int LairObserver::getSpawnNumber ()
Definition at line 191 of file LairObserver.cpp.
References _getImplementation(), server::zone::managers::creature::LairObserverImplementation::getSpawnNumber(), and RPC_GETSPAWNNUMBER__.
void LairObserver::healLair (TangibleObject * lair, TangibleObject * attacker)
Definition at line 83 of file LairObserver.cpp.
References _getImplementation(), server::zone::managers::creature::LairObserverImplementation::healLair(), and RPC_HEALLAIR__TANGIBLEOBJECT_TANGIBLEOBJECT_.
bool LairObserver::isLairObserver ()
Definition at line 152 of file LairObserver.cpp.
References _getImplementation(), server::zone::managers::creature::LairObserverImplementation::isLairObserver(), and RPC_ISLAIROBSERVER__.
void LairObserver::notifyDestruction (TangibleObject * lair, TangibleObject * attacker, int condition)
Definition at line 52 of file LairObserver.cpp.
References _getImplementation(), server::zone::managers::creature::LairObserverImplementation::notifyDestruction(), and RPC_NOTIFYDESTRUCTION__TANGIBLEOBJECT_TANGIBLEOBJECT_INT_.
int LairObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 35 of file LairObserver.cpp.
References _getImplementation(), server::zone::managers::creature::LairObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
void LairObserver::setDifficulty (int diff)
Definition at line 138 of file LairObserver.cpp.
References _getImplementation(), RPC_SETDIFFICULTY__INT_, and server::zone::managers::creature::LairObserverImplementation::setDifficulty().
void LairObserver::setLairTemplate (LairTemplate * tmpl)
Definition at line 129 of file LairObserver.cpp.
References _getImplementation(), and server::zone::managers::creature::LairObserverImplementation::setLairTemplate().
Friends And Related Function Documentation
friend class LairObserverHelper friend
Definition at line 107 of file LairObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/LairObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/LairObserver.cpp