Core3: RadialMenuItem Class Reference
RadialMenuItem Class Reference
#include <RadialMenuItem.h>
Public Member Functions
RadialMenuItem (int itemidx, RadialMenuItem *parent, uint8 radialid, uint8 callback, const UnicodeString &text="")
RadialMenuItem ()
~RadialMenuItem ()
void addRadialMenuItem (int itemidx, uint8 radialid, uint8 callback, const UnicodeString &text="")
RadialMenuItem * getItem (int index)
RadialMenuItem * getItemByRadialID (uint8 index)
void setRadialID (uint8 radialid)
void setCallback (uint8 cback)
void setText (const UnicodeString &txt)
void setParent (RadialMenuItem *item)
void setItemIndex (int idx)
uint8 getRadialID ()
uint8 getCallback ()
UnicodeString & getText ()
RadialMenuItem * getChild (int idx)
RadialMenuItem * getParent ()
bool hasChildren ()
int getChildrenSize ()
int getParentIndex ()
int getItemIndex ()
Private Attributes
uint8 radialID
uint8 callback
UnicodeString text
RadialMenuItem * parent
Vector< Reference
< RadialMenuItem * > > children
int itemIndex
Detailed Description
Please see Radial in the wiki for a list of client side radial id's. Also, please note that radial id's are handled in RadialManager.cpp and most have already been defined. Try to find one suitable to your purpose, or piggy back the SERVER_MENUX ones which Call an objects associated virtual method.
Callback Types known: 0x01 = Default 0x03 = Callback
Definition at line 62 of file RadialMenuItem.h.
Constructor & Destructor Documentation
RadialMenuItem::RadialMenuItem (int itemidx, RadialMenuItem * parent, uint8 radialid, uint8 callback, const UnicodeString & text = "") inline
Definition at line 74 of file RadialMenuItem.h.
References itemIndex, parent, setCallback(), setRadialID(), setText(), and text.
RadialMenuItem::RadialMenuItem () inline
Definition at line 84 of file RadialMenuItem.h.
References callback, itemIndex, parent, and radialID.
Referenced by addRadialMenuItem().
RadialMenuItem::~RadialMenuItem () inline
Definition at line 93 of file RadialMenuItem.h.
Member Function Documentation
void RadialMenuItem::addRadialMenuItem (int itemidx, uint8 radialid, uint8 callback, const UnicodeString & text = "") inline
Definition at line 100 of file RadialMenuItem.h.
References children, RadialMenuItem(), and text.
Referenced by server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), and server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID().
uint8 RadialMenuItem::getCallback () inline
Definition at line 169 of file RadialMenuItem.h.
References callback.
Referenced by server::zone::packets::object::ObjectMenuResponse::addRadialOption().
RadialMenuItem* RadialMenuItem::getChild (int idx) inline
Definition at line 177 of file RadialMenuItem.h.
References children.
Referenced by server::zone::packets::object::ObjectMenuResponse::insertRadialItemToMessage().
int RadialMenuItem::getChildrenSize () inline
Definition at line 189 of file RadialMenuItem.h.
References children.
Referenced by server::zone::packets::object::ObjectMenuResponse::insertRadialItemToMessage().
RadialMenuItem* RadialMenuItem::getItem (int index) inline
Definition at line 105 of file RadialMenuItem.h.
References children, getItem(), and getItemIndex().
Referenced by getItem().
RadialMenuItem* RadialMenuItem::getItemByRadialID (uint8 index) inline
Definition at line 124 of file RadialMenuItem.h.
References children, getItemByRadialID(), and getRadialID().
Referenced by getItemByRadialID().
int RadialMenuItem::getItemIndex () inline
Definition at line 200 of file RadialMenuItem.h.
References itemIndex.
Referenced by server::zone::packets::object::ObjectMenuResponse::addRadialOption(), getItem(), and getParentIndex().
RadialMenuItem* RadialMenuItem::getParent () inline
Definition at line 181 of file RadialMenuItem.h.
References parent.
int RadialMenuItem::getParentIndex () inline
Definition at line 193 of file RadialMenuItem.h.
References getItemIndex(), and parent.
Referenced by server::zone::packets::object::ObjectMenuResponse::addRadialOption().
uint8 RadialMenuItem::getRadialID () inline
Definition at line 165 of file RadialMenuItem.h.
References radialID.
Referenced by server::zone::packets::object::ObjectMenuResponse::addRadialOption(), and getItemByRadialID().
UnicodeString& RadialMenuItem::getText () inline
Definition at line 173 of file RadialMenuItem.h.
References text.
Referenced by server::zone::packets::object::ObjectMenuResponse::addRadialOption().
bool RadialMenuItem::hasChildren () inline
Definition at line 185 of file RadialMenuItem.h.
References children.
void RadialMenuItem::setCallback (uint8 cback) inline
Definition at line 148 of file RadialMenuItem.h.
References callback.
Referenced by RadialMenuItem().
void RadialMenuItem::setItemIndex (int idx) inline
Definition at line 160 of file RadialMenuItem.h.
References itemIndex.
void RadialMenuItem::setParent (RadialMenuItem * item) inline
Definition at line 156 of file RadialMenuItem.h.
References parent.
void RadialMenuItem::setRadialID (uint8 radialid) inline
Definition at line 144 of file RadialMenuItem.h.
References radialID.
Referenced by RadialMenuItem().
void RadialMenuItem::setText (const UnicodeString & txt) inline
Definition at line 152 of file RadialMenuItem.h.
References text.
Referenced by RadialMenuItem().
Member Data Documentation
uint8 RadialMenuItem::callback private
Definition at line 64 of file RadialMenuItem.h.
Referenced by getCallback(), RadialMenuItem(), and setCallback().
Vector<Reference<RadialMenuItem*> > RadialMenuItem::children private
Definition at line 69 of file RadialMenuItem.h.
Referenced by addRadialMenuItem(), getChild(), getChildrenSize(), getItem(), getItemByRadialID(), and hasChildren().
int RadialMenuItem::itemIndex private
Definition at line 71 of file RadialMenuItem.h.
Referenced by getItemIndex(), RadialMenuItem(), and setItemIndex().
RadialMenuItem* RadialMenuItem::parent private
Definition at line 67 of file RadialMenuItem.h.
Referenced by getParent(), getParentIndex(), RadialMenuItem(), and setParent().
uint8 RadialMenuItem::radialID private
Definition at line 63 of file RadialMenuItem.h.
Referenced by getRadialID(), RadialMenuItem(), and setRadialID().
UnicodeString RadialMenuItem::text private
Definition at line 65 of file RadialMenuItem.h.
Referenced by addRadialMenuItem(), getText(), RadialMenuItem(), and setText().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/object/RadialMenuItem.h