Core3: server::zone::objects::player::sessions::MigrateStatsSessionAdapter Class Reference
server::zone::objects::player::sessions::MigrateStatsSessionAdapter Class Reference
#include <MigrateStatsSession.h>
Public Member Functions
MigrateStatsSessionAdapter (MigrateStatsSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession ()
int cancelSession ()
int clearSession ()
int getAttributeToModifyCount ()
void setAttributeToModify (int attribute, int value)
int getAttribtueToModify (int attribute)
void migrateStats ()
Detailed Description
Definition at line 171 of file MigrateStatsSession.h.
Constructor & Destructor Documentation
MigrateStatsSessionAdapter::MigrateStatsSessionAdapter (MigrateStatsSession * impl)
Definition at line 372 of file MigrateStatsSession.cpp.
Member Function Documentation
int MigrateStatsSessionAdapter::cancelSession ()
Definition at line 423 of file MigrateStatsSession.cpp.
Referenced by invokeMethod().
int MigrateStatsSessionAdapter::clearSession ()
Definition at line 427 of file MigrateStatsSession.cpp.
Referenced by invokeMethod().
int MigrateStatsSessionAdapter::getAttribtueToModify (int attribute)
Definition at line 439 of file MigrateStatsSession.cpp.
Referenced by invokeMethod().
int MigrateStatsSessionAdapter::getAttributeToModifyCount ()
Definition at line 431 of file MigrateStatsSession.cpp.
Referenced by invokeMethod().
int MigrateStatsSessionAdapter::initializeSession ()
Definition at line 419 of file MigrateStatsSession.cpp.
Referenced by invokeMethod().
void MigrateStatsSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 375 of file MigrateStatsSession.cpp.
References cancelSession(), clearSession(), getAttribtueToModify(), getAttributeToModifyCount(), initializeSession(), migrateStats(), RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_GETATTRIBTUETOMODIFY__INT_, RPC_GETATTRIBUTETOMODIFYCOUNT__, RPC_INITIALIZESESSION__, RPC_MIGRATESTATS__, RPC_SETATTRIBUTETOMODIFY__INT_INT_, and setAttributeToModify().
void MigrateStatsSessionAdapter::migrateStats ()
Definition at line 443 of file MigrateStatsSession.cpp.
Referenced by invokeMethod().
void MigrateStatsSessionAdapter::setAttributeToModify (int attribute, int value)
Definition at line 435 of file MigrateStatsSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/MigrateStatsSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/MigrateStatsSession.cpp