Core3: ResourceTreeNode Class Reference
ResourceTreeNode Class Reference
#include <ResourceTreeNode.h>
Public Member Functions
ResourceTreeNode (const String &t, const String &n, const int d)
~ResourceTreeNode ()
String getName ()
String getStfName ()
void setParentNode (ResourceTreeNode *parent)
ResourceTreeNode * getParentNode ()
void add (ResourceTreeEntry *entry)
ResourceTreeEntry * getEntry (const String &type, const Vector< String > &excludes=0, const String &zoneName="")
ResourceTreeEntry * find (const String &type, ResourceTreeEntry *entry=NULL)
ResourceTreeNode * findNode (const String &type, ResourceTreeNode *node=NULL)
ResourceTreeEntry * getPlanetSpecificEntry (const String &planet)
void addToSuiListBox (SuiListBox *suil)
void toString ()
Private Member Functions
void getEntryPool (Vector< ResourceTreeEntry * > &candidates, const Vector< String > excludes)
Private Attributes
String name
String stfName
int maxtype
int mintype
int maxpool
int minpool
int depth
Vector< ResourceTreeEntry * > entries
Vector< ResourceTreeNode * > nodes
ResourceTreeNode * parentNode
Detailed Description
Definition at line 57 of file ResourceTreeNode.h.
Constructor & Destructor Documentation
ResourceTreeNode::ResourceTreeNode (const String & t, const String & n, const int d)
Definition at line 53 of file ResourceTreeNode.cpp.
References depth, maxpool, maxtype, minpool, mintype, name, parentNode, and stfName.
Referenced by add().
ResourceTreeNode::~ResourceTreeNode ()
Definition at line 64 of file ResourceTreeNode.cpp.
References entries, nodes, and parentNode.
Member Function Documentation
void ResourceTreeNode::add (ResourceTreeEntry * entry)
Definition at line 90 of file ResourceTreeNode.cpp.
References add(), depth, entries, ResourceTreeEntry::getClass(), ResourceTreeEntry::getClassCount(), ResourceTreeEntry::getFinalClass(), getName(), ResourceTreeEntry::getType(), nodes, ResourceTreeNode(), ResourceTreeEntry::setChildren(), ResourceTreeEntry::setMyNode(), and setParentNode().
Referenced by add(), and ResourceTree::buildTreeFromClient().
void ResourceTreeNode::addToSuiListBox (SuiListBox * suil)
Definition at line 261 of file ResourceTreeNode.cpp.
References server::zone::objects::player::sui::listbox::SuiListBox::addMenuItem(), entries, ResourceTreeEntry::getFinalClass(), getName(), ResourceTreeEntry::hasChildren(), ResourceTreeEntry::isRecycled(), nodes, parentNode, server::zone::objects::player::sui::SuiBox::setPromptText(), and server::zone::objects::player::sui::SuiBox::setPromptTitle().
Referenced by ResourceSpawner::addNodeToListBox(), and ResourceSpawner::addParentNodeToListBox().
ResourceTreeEntry * ResourceTreeNode::find (const String & type, ResourceTreeEntry * entry = NULL)
Definition at line 131 of file ResourceTreeNode.cpp.
References entries, find(), ResourceTreeEntry::getFinalClass(), ResourceTreeEntry::getType(), and nodes.
Referenced by ResourceSpawner::addParentNodeToListBox(), find(), getEntry(), and ResourceSpawner::sendResourceRecycleType().
ResourceTreeNode * ResourceTreeNode::findNode (const String & type, ResourceTreeNode * node = NULL)
Definition at line 150 of file ResourceTreeNode.cpp.
References findNode(), getName(), getStfName(), and nodes.
Referenced by ResourceSpawner::addNodeToListBox(), ResourceSpawner::addParentNodeToListBox(), findNode(), and getEntry().
ResourceTreeEntry * ResourceTreeNode::getEntry (const String & type, const Vector< String > & excludes = 0, const String & zoneName = "")
Definition at line 166 of file ResourceTreeNode.cpp.
References find(), findNode(), getEntryPool(), ResourceTreeEntry::getMyNode(), getPlanetSpecificEntry(), and ResourceTreeEntry::hasChildren().
Referenced by ResourceTree::getEntry().
void ResourceTreeNode::getEntryPool (Vector< ResourceTreeEntry * > & candidates, const Vector< String > excludes) private
Definition at line 214 of file ResourceTreeNode.cpp.
References entries, getEntryPool(), ResourceTreeEntry::hasChildren(), ResourceTreeEntry::isRecycled(), ResourceTreeEntry::isType(), and nodes.
Referenced by getEntry(), and getEntryPool().
String ResourceTreeNode::getName ()
Definition at line 74 of file ResourceTreeNode.cpp.
References name.
Referenced by add(), ResourceSpawner::addParentNodeToListBox(), addToSuiListBox(), and findNode().
ResourceTreeNode * ResourceTreeNode::getParentNode ()
Definition at line 86 of file ResourceTreeNode.cpp.
References parentNode.
Referenced by ResourceSpawner::addParentNodeToListBox().
ResourceTreeEntry * ResourceTreeNode::getPlanetSpecificEntry (const String & planet)
Definition at line 204 of file ResourceTreeNode.cpp.
References entries, and ResourceTreeEntry::getType().
Referenced by getEntry().
String ResourceTreeNode::getStfName ()
Definition at line 78 of file ResourceTreeNode.cpp.
References stfName.
Referenced by findNode().
void ResourceTreeNode::setParentNode (ResourceTreeNode * parent)
Definition at line 82 of file ResourceTreeNode.cpp.
References parentNode.
Referenced by add().
void ResourceTreeNode::toString ()
Definition at line 281 of file ResourceTreeNode.cpp.
References depth, entries, name, nodes, and stfName.
Referenced by ResourceTree::toString().
Member Data Documentation
int ResourceTreeNode::depth private
Definition at line 63 of file ResourceTreeNode.h.
Referenced by add(), ResourceTreeNode(), and toString().
Vector<ResourceTreeEntry* > ResourceTreeNode::entries private
Definition at line 64 of file ResourceTreeNode.h.
Referenced by add(), addToSuiListBox(), find(), getEntryPool(), getPlanetSpecificEntry(), toString(), and ~ResourceTreeNode().
int ResourceTreeNode::maxpool private
Definition at line 61 of file ResourceTreeNode.h.
Referenced by ResourceTreeNode().
int ResourceTreeNode::maxtype private
Definition at line 61 of file ResourceTreeNode.h.
Referenced by ResourceTreeNode().
int ResourceTreeNode::minpool private
Definition at line 61 of file ResourceTreeNode.h.
Referenced by ResourceTreeNode().
int ResourceTreeNode::mintype private
Definition at line 61 of file ResourceTreeNode.h.
Referenced by ResourceTreeNode().
String ResourceTreeNode::name private
Definition at line 59 of file ResourceTreeNode.h.
Referenced by getName(), ResourceTreeNode(), and toString().
Vector<ResourceTreeNode* > ResourceTreeNode::nodes private
Definition at line 65 of file ResourceTreeNode.h.
Referenced by add(), addToSuiListBox(), find(), findNode(), getEntryPool(), toString(), and ~ResourceTreeNode().
ResourceTreeNode* ResourceTreeNode::parentNode private
Definition at line 67 of file ResourceTreeNode.h.
Referenced by addToSuiListBox(), getParentNode(), ResourceTreeNode(), setParentNode(), and ~ResourceTreeNode().
String ResourceTreeNode::stfName private
Definition at line 60 of file ResourceTreeNode.h.
Referenced by getStfName(), ResourceTreeNode(), and toString().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcetree/ResourceTreeNode.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcetree/ResourceTreeNode.cpp