Core3: server::zone::objects::player::sessions::TrainerConversationSession Class Reference
server::zone::objects::player::sessions::TrainerConversationSession Class Reference
#include <TrainerConversationSession.h>
Public Member Functions
TrainerConversationSession (CreatureObject *npc)
void clearTrainableSkills ()
void addTrainableSkill (String &skillName)
String getTrainableSkills (int selectedOption)
int getTrainableSkillsCount ()
void clearNextSkills ()
void addNextSkill (String &skillName)
String getNextSkill (int selectedOption)
int getNextSkillsCount ()
void setSelectedSkill (String &skillName)
String getSelectedSkill ()
String getMasterSkill ()
void setMasterSkill (String &skillName)
void addAdditionalMasterSkill (String &skillName)
String getAdditionalMasterSkill (int selectedOption)
int getAdditionalMasterSkillsCount ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::player::sessions::ConversationSession
ConversationSession (CreatureObject *conversingCreature)
void setLastConversationScreen (ConversationScreen *screen)
ConversationScreen * getLastConversationScreen ()
ManagedWeakReference
< CreatureObject * > getNPC ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
TrainerConversationSession (DummyConstructorParameter *param)
virtual ~TrainerConversationSession ()
Protected Member Functions inherited from server::zone::objects::player::sessions::ConversationSession
ConversationSession (DummyConstructorParameter *param)
virtual ~ConversationSession ()
Friends
class TrainerConversationSessionHelper
Detailed Description
Definition at line 40 of file TrainerConversationSession.h.
Constructor & Destructor Documentation
TrainerConversationSession::TrainerConversationSession (CreatureObject * npc)
Definition at line 15 of file TrainerConversationSession.cpp.
References server::zone::objects::player::sessions::TrainerConversationSessionImplementation::_setStub().
TrainerConversationSession::TrainerConversationSession (DummyConstructorParameter * param) protected
Definition at line 22 of file TrainerConversationSession.cpp.
TrainerConversationSession::~TrainerConversationSession () protected virtual
Definition at line 26 of file TrainerConversationSession.cpp.
Member Function Documentation
DistributedObjectServant * TrainerConversationSession::_getImplementation ()
Definition at line 244 of file TrainerConversationSession.cpp.
Referenced by addAdditionalMasterSkill(), addNextSkill(), addTrainableSkill(), clearNextSkills(), clearTrainableSkills(), getAdditionalMasterSkill(), getAdditionalMasterSkillsCount(), getMasterSkill(), getNextSkill(), getNextSkillsCount(), getSelectedSkill(), getTrainableSkills(), getTrainableSkillsCount(), setMasterSkill(), and setSelectedSkill().
DistributedObjectServant * TrainerConversationSession::_getImplementationForRead ()
Definition at line 250 of file TrainerConversationSession.cpp.
void TrainerConversationSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 254 of file TrainerConversationSession.cpp.
void TrainerConversationSession::addAdditionalMasterSkill (String & skillName)
Definition at line 201 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::addAdditionalMasterSkill(), and RPC_ADDADDITIONALMASTERSKILL__STRING_.
void TrainerConversationSession::addNextSkill (String & skillName)
Definition at line 100 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::addNextSkill(), and RPC_ADDNEXTSKILL__STRING_.
void TrainerConversationSession::addTrainableSkill (String & skillName)
Definition at line 44 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::addTrainableSkill(), and RPC_ADDTRAINABLESKILL__STRING_.
void TrainerConversationSession::clearNextSkills ()
Definition at line 87 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::clearNextSkills(), and RPC_CLEARNEXTSKILLS__.
void TrainerConversationSession::clearTrainableSkills ()
Definition at line 31 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::clearTrainableSkills(), and RPC_CLEARTRAINABLESKILLS__.
String TrainerConversationSession::getAdditionalMasterSkill (int selectedOption)
Definition at line 215 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::getAdditionalMasterSkill(), and RPC_GETADDITIONALMASTERSKILL__INT_.
int TrainerConversationSession::getAdditionalMasterSkillsCount ()
Definition at line 231 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::getAdditionalMasterSkillsCount(), and RPC_GETADDITIONALMASTERSKILLSCOUNT__.
String TrainerConversationSession::getMasterSkill ()
Definition at line 172 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::getMasterSkill(), and RPC_GETMASTERSKILL__.
String TrainerConversationSession::getNextSkill (int selectedOption)
Definition at line 114 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::getNextSkill(), and RPC_GETNEXTSKILL__INT_.
int TrainerConversationSession::getNextSkillsCount ()
Definition at line 130 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::getNextSkillsCount(), and RPC_GETNEXTSKILLSCOUNT__.
String TrainerConversationSession::getSelectedSkill ()
Definition at line 157 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::getSelectedSkill(), and RPC_GETSELECTEDSKILL__.
String TrainerConversationSession::getTrainableSkills (int selectedOption)
Definition at line 58 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::getTrainableSkills(), and RPC_GETTRAINABLESKILLS__INT_.
int TrainerConversationSession::getTrainableSkillsCount ()
Definition at line 74 of file TrainerConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TrainerConversationSessionImplementation::getTrainableSkillsCount(), and RPC_GETTRAINABLESKILLSCOUNT__.
void TrainerConversationSession::setMasterSkill (String & skillName)
Definition at line 187 of file TrainerConversationSession.cpp.
References _getImplementation(), RPC_SETMASTERSKILL__STRING_, and server::zone::objects::player::sessions::TrainerConversationSessionImplementation::setMasterSkill().
void TrainerConversationSession::setSelectedSkill (String & skillName)
Definition at line 143 of file TrainerConversationSession.cpp.
References _getImplementation(), RPC_SETSELECTEDSKILL__STRING_, and server::zone::objects::player::sessions::TrainerConversationSessionImplementation::setSelectedSkill().
Friends And Related Function Documentation
friend class TrainerConversationSessionHelper friend
Definition at line 84 of file TrainerConversationSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TrainerConversationSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TrainerConversationSession.cpp