Core3: server::zone::objects::creature::NonPlayerCreatureObjectImplementation Class Reference
server::zone::objects::creature::NonPlayerCreatureObjectImplementation Class Reference
#include <NonPlayerCreatureObject.h>
Public Member Functions
NonPlayerCreatureObjectImplementation ()
NonPlayerCreatureObjectImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
bool isNonPlayerCreatureObject ()
bool isCamouflaged (CreatureObject *target)
operator const NonPlayerCreatureObject * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::AiAgentImplementation
AiAgentImplementation ()
AiAgentImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void finalize ()
virtual void activateRecovery ()
virtual void activateMovementEvent ()
virtual void activateWaitEvent ()
void activateAwarenessEvent (CreatureObject *target)
bool tryRetreat ()
void doRecovery ()
void doAttack ()
void doMovement ()
void setLevel (int lvl)
void sendBaselinesTo (SceneObject *player)
int calculateAttackMinDamage (int level)
int calculateAttackMaxDamage (int level)
float calculateAttackSpeed (int level)
bool isScentMasked (CreatureObject *target)
bool isConcealed (CreatureObject *target)
void doAwarenessCheck (Coordinate &start, unsigned long long time, CreatureObject *target)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
void checkNewAngle ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setNextPosition (float x, float z, float y, SceneObject *cell=NULL)
void notifyPositionUpdate (QuadTreeEntry *entry)
void updateCurrentPosition (PatrolPoint *point)
void broadcastNextPositionUpdate (PatrolPoint *point)
void clearPatrolPoints ()
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void loadTemplateData (SharedObjectTemplate *templateData)
void loadTemplateData (CreatureTemplate *templateData)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
void sendConversationStartTo (SceneObject *player)
void sendDefaultConversationTo (SceneObject *player)
void selectConversationOption (int option, SceneObject *obj)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
int notifyConverseObservers (CreatureObject *converser)
int notifyAttack (Observable *observable)
int notifyCallForHelp (Observable *observable, ManagedObject *arg1)
void destroyObjectFromWorld (bool sendSelfDestroy)
void activatePostureRecovery ()
void queueDizzyFallEvent ()
void clearCombatState (bool clearDefenders=true)
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
void setDespawnOnNoPlayerInRange (bool val)
virtual void notifyDespawn (Zone *zone)
virtual void scheduleDespawn ()
virtual void scheduleDespawn (int timeToDespawn)
void respawn (Zone *zone, int level)
void addPatrolPoint (PatrolPoint &point)
void setHomeLocation (float x, float z, float y, SceneObject *cell=NULL)
void setRespawnTimer (float resp)
void setRandomRespawn (bool resp)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
void setOblivious ()
void setWatchObject (SceneObject *obj)
void setStalkObject (SceneObject *obj)
void setFollowObject (SceneObject *obj)
void setTargetObject (SceneObject *obj)
SceneObject * getFollowObject ()
void selectWeapon ()
bool validateStateAttack (CreatureObject *target, String &args)
bool isRetreating ()
bool isFleeing ()
void clearDespawnEvent ()
float getKinetic ()
float getEnergy ()
float getElectricity ()
float getStun ()
float getBlast ()
float getHeat ()
float getCold ()
float getAcid ()
float getLightSaber ()
bool isStalker ()
bool isKiller ()
unsigned int getFerocity ()
unsigned int getArmor ()
bool getDespawnOnNoPlayerInRange ()
int getNumberOfPlayersInRange ()
String getFactionString ()
String getSocialGroup ()
float getChanceHit ()
int getDamageMin ()
int getDamageMax ()
int getBaseXp ()
unsigned int getDiet ()
CreatureAttackMap * getAttackMap ()
LootGroupCollection * getLootGroups ()
float getRespawnTimer ()
bool getRandomRespawn ()
PatrolPoint * getHomeLocation ()
bool isAiAgent ()
CreatureTemplate * getCreatureTemplate ()
bool hasLoot ()
void setShowNextPosition (bool val)
bool isEventMob ()
String getPvPFaction ()
int getBehaviorStatus (Behavior *b)
void setBehaviorStatus (Behavior *b, int status)
void addBehaviorToTree (BehaviorTree *tree, Behavior *b)
Behavior * getNextBehaviorFromTree (BehaviorTree *tree)
void resetBehaviorList (BehaviorTree *tree)
operator const AiAgent * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::creature::CreatureObjectImplementation
CreatureObjectImplementation ()
CreatureObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
void finalize ()
void createChildObjects ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void clearQueueAction (unsigned int actioncntr, float timer=0, unsigned int tab1=0, unsigned int tab2=0)
void sendBaselinesTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendTo (SceneObject *player, bool doClose)
void sendSystemMessage (const String &message)
void playMusicMessage (const String &file)
void sendNewbieTutorialRequest (const String &request)
void sendNewbieTutorialEnableHudElement (const String &ui, bool enable=true)
void sendOpenHolocronToPageMessage ()
void sendSystemMessage (UnicodeString &message)
void sendSystemMessage (StringIdChatParameter &stringid)
void sendSlottedObjectsTo (SceneObject *player)
void setCombatState ()
void clearCombatState (bool clearDefenders=true)
virtual void setPosture (int newPosture, bool notifyClient=true)
float calculateSpeed ()
virtual void updateLocomotion ()
void setHeight (float heigh, bool notifyClient=true)
void setAccelerationMultiplierBase (float newMultiplierBase, bool notifyClient=true)
void setAccelerationMultiplierMod (float newMultiplierMod, bool notifyClient=true)
void setSpeedMultiplierBase (float newMultiplierBase, bool notifyClient=true)
virtual void setSpeedMultiplierMod (float newMultiplierMod, bool notifyClient=true)
virtual void setTurnScale (float newMultiplierMod, bool notifyClient=true)
void setRunSpeed (float newSpeed, bool notifyClient=true)
void setCurrentSpeed (float newSpeed)
void setHAM (int type, int value, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
bool hasDamage (int attribute)
int healDamage (TangibleObject *healer, int damageType, int damage, bool notifyClient=true, bool notifyObservers=true)
int healWound (TangibleObject *healer, int damageType, int damage, bool notifyClient=true, bool notifyObservers=true)
void setBaseHAM (int type, int value, bool notifyClient=true)
void setWounds (int type, int value, bool notifyClient=true)
int addWounds (int type, int value, bool notifyClient=true)
void setMaxHAM (int type, int value, bool notifyClient=true)
void addMaxHAM (int type, int value, bool notifyClient=true)
void setEncumbrance (int type, int value, bool notifyClient=true)
void addEncumbrance (int type, int value, bool notifyClient=true)
void setWeapon (WeaponObject *weao, bool notifyClient=false)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void setInstrumentID (int instrumentid, bool notifyClient=true)
void setListenToID (unsigned long long id, bool notifyClient=true)
void setPerformanceCounter (int counter, bool notifyClient=true)
void setPerformanceAnimation (const String &animation, bool notifyClient=true)
void setShockWounds (int newShock, bool notifyClient=true)
void addShockWounds (int shockToAdd, bool notiyClient=true)
void setTargetID (unsigned long long targetID, bool notifyClient=true)
void setBankCredits (int credits, bool notifyClient=true)
void addBuff (Buff *buff)
bool removeBuff (unsigned int buffcrc)
void removeBuff (Buff *buff)
bool removeStateBuff (unsigned long long state)
void clearBuffs (bool updateclient)
void addWearableObject (TangibleObject *object, bool notifyClient=true)
void removeWearableObject (TangibleObject *object, bool notifyClient=true)
WearablesDeltaVector * getWearablesDeltaVector ()
void sendBuffsTo (CreatureObject *creature)
BuffList * getBuffList ()
Buff * getBuff (unsigned int buffcrc)
long long getSkillModFromBuffs (const String &skillMod)
int addDotState (unsigned long long dotType, unsigned long long objectID, unsigned int strength, byte type, unsigned int duration, float potency, unsigned int defense, int secondaryStrength=0)
bool healDot (unsigned long long dotType, int reduction)
void clearDots ()
DamageOverTimeList * getDamageOverTimeList ()
bool hasBuff (unsigned int buffcrc)
void notifySelfPositionUpdate ()
void notifyPostureChange (int newPosture)
void setLevel (int level)
void updateToDatabaseAllObjects (bool startTask)
bool isResuscitable ()
void addBankCredits (int credits, bool notifyClient=true)
void addCashCredits (int credits, bool notifyClient=true)
void subtractBankCredits (int credits)
void subtractCashCredits (int credits)
bool verifyCashCredits (int credits)
bool verifyBankCredits (int credits)
bool isDancing ()
bool isPlayingMusic ()
void stopEntertaining ()
bool isEntertaining ()
void setCashCredits (int credits, bool notifyClient=true)
void setTerrainNegotiation (float value, bool notifyClient=true)
void addSkill (Skill *skill, bool notifyClient=true)
void addSkill (const String &skill, bool notifyClient=true)
void removeSkill (Skill *skill, bool notifyClient=true)
void removeSkill (const String &skill, bool notifyClient=true)
void addSkillMod (const int modType, const String &skillMod, int value, bool notifyClient=true)
void removeSkillMod (const int modType, const String &skillMod, int value, bool notifyClient=true)
void removeAllSkillModsOfType (const int modType, bool notifyClient=true)
void updateGroupInviterID (unsigned long long id, bool notifyClient=true)
void updateGroup (GroupObject *group, bool notifyClient=true)
void enqueueCommand (unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString &arguments, int priority=-1)
void setMood (byte moodID, bool notifyClient=true)
void setMoodString (const String &animation, bool notifyClient=true)
void deleteQueueAction (unsigned int actionCount)
bool setState (unsigned long long state, bool notifyClient=true)
bool clearState (unsigned long long state, bool notifyClient=true)
void setControlDevice (ControlDevice *device)
void setCreatureLink (CreatureObject *object, bool notifyClient=true)
void executeObjectControllerAction (unsigned int actionCRC)
void executeObjectControllerAction (unsigned int actionCRC, unsigned long long targetID, const UnicodeString &args)
bool isAttackableBy (CreatureObject *object)
bool isAttackableBy (TangibleObject *attacker)
bool isHealableBy (CreatureObject *object)
bool isInBountyMission (CreatureObject *bountyHunter, CreatureObject *target)
void sendMessage (BasePacket *msg)
void sendExecuteConsoleCommand (const String &command)
bool isAggressiveTo (CreatureObject *object)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
int notifyObjectKillObservers (TangibleObject *killer)
void notifyLoadFromDatabase ()
void setFactionRank (int rank, bool notifyClient=true)
String getFirstName ()
String getLastName ()
bool isOnline ()
bool canTreatInjuries ()
bool canTreatStates ()
bool canTreatWounds ()
bool canTreatConditions ()
Reference< PlayerObject * > getPlayerObject ()
AiActor * getActorObject ()
bool isListening ()
bool isWatching ()
void setClient (ZoneClientSession *cli)
void dismount ()
float calculateBFRatio ()
void setDizziedState (int durationSeconds=5)
void setRalliedState (int durationSeconds=5)
void setAimingState (int durationSeconds=5)
void setCoverState (int durationSeconds=40)
void setBerserkedState (unsigned int duration)
void setStunnedState (int durationSeconds=5)
void setBlindedState (int durationSeconds=5)
void setIntimidatedState (unsigned int mod, int durationSeconds=15)
void setSnaredState (int durationSeconds=20)
void setRootedState (int durationSeconds=20)
bool setNextAttackDelay (unsigned int mod, int del)
void setMeditateState ()
virtual void activateHAMRegeneration ()
virtual void activatePassiveWoundRegeneration ()
virtual void activateStateRecovery ()
void updateTimeOfDeath ()
bool hasAttackDelay ()
void removeAttackDelay ()
CooldownTimerMap * getCooldownTimerMap ()
bool hasSpice ()
void updateLastSuccessfulCombatAction ()
void updateKnockdownRecovery ()
void updateLastKnockdown ()
bool checkKnockdownRecovery ()
bool checkLastKnockdown ()
void updatePostureDownRecovery ()
void updatePostureUpRecovery ()
bool checkPostureDownRecovery ()
unsigned long long getScreenPlayState (const String &screenPlay)
void setScreenPlayState (const String &screenPlay, unsigned long long state)
bool checkPostureUpRecovery ()
void updateCooldownTimer (const String &coooldownTimer, unsigned int miliSecondsToAdd=0)
bool checkCooldownRecovery (const String &cooldown)
Time * getCooldownTime (const String &cooldown)
void addCooldown (const String &name, unsigned int miliseconds)
void doAnimation (const String &animation)
void doCombatAnimation (CreatureObject *defender, unsigned int animationCRC, byte hit, byte trails)
void playEffect (const String &file, const String &aux)
void playEffect (const String &file)
void activateQueueAction ()
void activateImmediateAction ()
UnicodeString getCreatureName ()
bool isGrouped ()
int getBankCredits ()
int getCashCredits ()
int getBaseHAM (int idx)
int getWounds (int idx)
DeltaVector< int > * getWounds ()
int getHAM (int idx)
DeltaVector< int > * getHAM ()
int getMaxHAM (int idx)
DeltaVector< int > * getMaxHAM ()
int getEncumbrance (int idx)
DeltaVector< int > * getEncumbrances ()
byte getPosture ()
byte getLocomotion ()
byte getFactionRank ()
ManagedWeakReference
< CreatureObject * > getLinkedCreature ()
unsigned long long getCreatureLinkID ()
float getShockWounds ()
unsigned long long getWatchToID ()
unsigned long long getStateBitmask ()
bool hasState (unsigned long long state)
bool hasStates ()
unsigned long long getListenID ()
float getAccelerationMultiplierBase ()
float getAccelerationMultiplierMod ()
float getSpeedMultiplierBase ()
float getSpeedMultiplierMod ()
float getCurrentSpeed ()
SpeedMultiplierModChanges * getSpeedMultiplierModChanges ()
CommandQueueActionVector * getCommandQueue ()
float getRunSpeed ()
float getWalkSpeed ()
float getTurnScale ()
float getTerrainNegotiation ()
float getRunAcceleration ()
float getWalkAcceleration ()
String getPerformanceAnimation ()
String getMoodString ()
unsigned long long getWeaponID ()
Reference< WeaponObject * > getWeapon ()
Reference< GuildObject * > getGuildObject ()
int getGuildID ()
bool isInGuild ()
void setGuildObject (GuildObject *guildobj)
unsigned long long getGroupID ()
unsigned long long getGroupInviterID ()
GroupObject * getGroup ()
unsigned long long getGroupInviteCounter ()
unsigned long long getTargetID ()
byte getMoodID ()
float getSlopeModPercent ()
int getPerformanceCounter ()
int getInstrumentID ()
byte getFrozen ()
float getHeight ()
int getSpecies ()
String getSpeciesName ()
int getGender ()
DeltaVector< int > * getBaseHAM ()
SkillList * getSkillList ()
int getSkillMod (const String &skillmod)
bool hasSkill (const String &skill)
SkillModList * getSkillModList ()
void setWatchToID (unsigned long long id)
bool isCreatureObject ()
bool isNextActionPast ()
virtual bool isTrainerCreature ()
bool isSwimming ()
ZoneClientSession * getClient ()
bool isRidingMount ()
ManagedWeakReference
< ControlDevice * > getControlDevice ()
float getSwimHeight ()
bool isIncapacitated ()
bool isDead ()
bool isKnockedDown ()
bool isKneeling ()
bool isProne ()
bool isStanding ()
bool isSitting ()
bool isSkillAnimating ()
bool isRallied ()
bool isInCombat ()
bool isDizzied ()
bool isBerserked ()
bool isStunned ()
bool isBlinded ()
bool isIntimidated ()
bool isSnared ()
bool isImmobilized ()
bool isRooted ()
bool isFrozen ()
bool isDiseased ()
bool isPoisoned ()
bool isBleeding ()
bool isOnFire ()
bool isMounted ()
bool isRidingCreature ()
bool isPeaced ()
bool isMeditating ()
bool isAiming ()
bool isInCover ()
bool isRunning ()
virtual bool isCreature ()
bool isPlayerCreature ()
bool isAiActor ()
virtual bool isInformantCreature ()
CampSiteActiveArea * getCurrentCamp ()
byte getCurrentWeather ()
void setCurrentWeather (byte value)
byte getCurrentWind ()
void setCurrentWind (byte value)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void destroyObjectFromWorld (bool sendSelfDestroy)
bool isInvisible ()
void setInvisible (bool invis)
Mutex * getSkillModMutex ()
float calculateCostAdjustment (byte stat, float baseCost)
void updateSpeedAndAccelerationMods ()
operator const CreatureObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
TangibleObjectImplementation ()
TangibleObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
virtual void addTemplateSkillMods (TangibleObject *targetObject)
virtual void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
virtual void removeSkillModsFrom (CreatureObject *creature)
virtual void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
virtual void removeDefenders ()
virtual void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
bool hasDefender (SceneObject *defender)
virtual void sendPvpStatusTo (CreatureObject *player)
virtual int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
virtual void updateCraftingValues (CraftingValues *values, bool firstUpdate)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
virtual bool isTicketCollector ()
virtual bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
virtual int getUseCount ()
virtual int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
virtual bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
virtual String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
virtual int getJunkDealerNeeded ()
void setJunkValue (int jValue)
virtual int getJunkValue ()
void setSerialNumber (const String &serial)
virtual String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
virtual String repairAttempt (int repairChance)
bool isBroken ()
virtual float getHitChance ()
void broadcastPvpStatusBitmask ()
operator const TangibleObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< NonPlayerCreatureObject * > _this
Public Attributes inherited from server::zone::objects::creature::AiAgentImplementation
WeakReference< AiAgent * > _this
Public Attributes inherited from server::zone::objects::creature::CreatureObjectImplementation
WeakReference< CreatureObject * > _this
Public Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
WeakReference< TangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Protected Member Functions
virtual ~NonPlayerCreatureObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::AiAgentImplementation
bool findNextPosition (float maxDistance, WorldCoordinates *nextPosition)
virtual ~AiAgentImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::CreatureObjectImplementation
virtual ~CreatureObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
float getConditionReduction (float value)
virtual ~TangibleObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class NonPlayerCreatureObject
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::creature::AiAgentImplementation
static const int UPDATEMOVEMENTINTERVAL = 500
static unsigned const int OBLIVIOUS = 0
static unsigned const int WATCHING = 1
static unsigned const int STALKING = 2
static unsigned const int FOLLOWING = 3
static unsigned const int PATROLING = 4
Protected Attributes inherited from server::zone::objects::creature::AiAgentImplementation
Reference< AiThinkEvent * > thinkEvent
Reference< AiMoveEvent * > moveEvent
Reference< AiWaitEvent * > waitEvent
Reference< AiAwarenessEvent * > awarenessEvent
ReadWriteLock despawnMutex
Vector< AiInterfaceComponent * > aiInterfaceComponents
Vector< String > skillCommands
PatrolPointsVector patrolPoints
PatrolPoint homeLocation
PatrolPoint nextStepPosition
Reference< CurrentFoundPath * > currentFoundPath
ManagedReference< SceneObject * > targetCellObject
Vector< ManagedReference
< WeaponObject * > > weapons
Vector< ManagedReference
< SceneObject * > > camouflagedObjects
CreatureTemplateReference npcTemplate
bool baby
bool showNextMovementPosition
Vector< ManagedReference
< SceneObject * > > movementMarkers
bool despawnOnNoPlayerInRange
ManagedReference< SceneObject * > followObject
unsigned int followState
Mutex targetMutex
Mutex awernessEventMutex
bool fleeing
Time lastDamageReceived
float respawnTimer
bool randomRespawn
int numberOfPlayersInRange
bool loadedOutfit
Reference
< DespawnCreatureOnPlayerDissappear * > despawnEvent
HashTable< Behavior *, int > statuses
HashTable< BehaviorTree
*, BehaviorTreeList * > trees
Detailed Description
Definition at line 93 of file NonPlayerCreatureObject.h.
Constructor & Destructor Documentation
NonPlayerCreatureObjectImplementation::NonPlayerCreatureObjectImplementation ()
Definition at line 205 of file NonPlayerCreatureObject.cpp.
References _initializeImplementation().
NonPlayerCreatureObjectImplementation::NonPlayerCreatureObjectImplementation (DummyConstructorParameter * param)
Definition at line 91 of file NonPlayerCreatureObject.cpp.
References _initializeImplementation().
NonPlayerCreatureObjectImplementation::~NonPlayerCreatureObjectImplementation () protected virtual
Definition at line 96 of file NonPlayerCreatureObject.cpp.
Member Function Documentation
DistributedObjectStub * NonPlayerCreatureObjectImplementation::_getStub ()
Definition at line 116 of file NonPlayerCreatureObject.cpp.
References _this.
void NonPlayerCreatureObjectImplementation::_initializeImplementation () protected
Definition at line 103 of file NonPlayerCreatureObject.cpp.
References _serializationHelperMethod(), and _this.
Referenced by NonPlayerCreatureObjectImplementation().
void NonPlayerCreatureObjectImplementation::_serializationHelperMethod () protected
Definition at line 152 of file NonPlayerCreatureObject.cpp.
References server::zone::objects::creature::AiAgentImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void NonPlayerCreatureObjectImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 111 of file NonPlayerCreatureObject.cpp.
References server::zone::objects::creature::AiAgentImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::NonPlayerCreatureObject::NonPlayerCreatureObject().
void NonPlayerCreatureObjectImplementation::finalize () protected
Definition at line 100 of file NonPlayerCreatureObject.cpp.
void NonPlayerCreatureObjectImplementation::initializeTransientMembers ()
Initializes the transient members of SceneObject, must call the inherited object method first.
Precondition
{transient members are not initialized }
Postcondition
{ transient members are initialized }
Definition at line 18 of file NonPlayerCreatureObjectImplementation.cpp.
References server::zone::objects::creature::AiAgentImplementation::aiInterfaceComponents, and server::zone::objects::creature::AiAgentImplementation::initializeTransientMembers().
Referenced by server::zone::objects::creature::NonPlayerCreatureObject::initializeTransientMembers(), and readObject().
bool NonPlayerCreatureObjectImplementation::isCamouflaged (CreatureObject * target) virtual
Reimplemented from server::zone::objects::creature::AiAgentImplementation.
Definition at line 220 of file NonPlayerCreatureObject.cpp.
References server::zone::objects::creature::AiAgentImplementation::isConcealed().
Referenced by server::zone::objects::creature::NonPlayerCreatureObject::isCamouflaged().
bool NonPlayerCreatureObjectImplementation::isNonPlayerCreatureObject () virtual
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 215 of file NonPlayerCreatureObject.cpp.
Referenced by server::zone::objects::creature::NonPlayerCreatureObject::isNonPlayerCreatureObject().
void NonPlayerCreatureObjectImplementation::lock (bool doLock = true) protected
Definition at line 124 of file NonPlayerCreatureObject.cpp.
References _this.
void NonPlayerCreatureObjectImplementation::lock (ManagedObject * obj) protected
Definition at line 128 of file NonPlayerCreatureObject.cpp.
References _this.
NonPlayerCreatureObjectImplementation::operator const NonPlayerCreatureObject * ()
Definition at line 120 of file NonPlayerCreatureObject.cpp.
void NonPlayerCreatureObjectImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::AiAgentImplementation.
Definition at line 159 of file NonPlayerCreatureObject.cpp.
References initializeTransientMembers(), and readObjectMember().
bool NonPlayerCreatureObjectImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 178 of file NonPlayerCreatureObject.cpp.
References server::zone::objects::creature::AiAgentImplementation::readObjectMember().
Referenced by readObject().
void NonPlayerCreatureObjectImplementation::rlock (bool doLock = true) protected
Definition at line 132 of file NonPlayerCreatureObject.cpp.
References _this.
void NonPlayerCreatureObjectImplementation::runlock (bool doLock = true) protected
Definition at line 148 of file NonPlayerCreatureObject.cpp.
References _this.
void NonPlayerCreatureObjectImplementation::unlock (bool doLock = true) protected
Definition at line 144 of file NonPlayerCreatureObject.cpp.
References _this.
void NonPlayerCreatureObjectImplementation::wlock (bool doLock = true) protected
Definition at line 136 of file NonPlayerCreatureObject.cpp.
References _this.
void NonPlayerCreatureObjectImplementation::wlock (ManagedObject * obj) protected
Definition at line 140 of file NonPlayerCreatureObject.cpp.
References _this.
void NonPlayerCreatureObjectImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::AiAgentImplementation.
Definition at line 188 of file NonPlayerCreatureObject.cpp.
References writeObjectMembers().
int NonPlayerCreatureObjectImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 195 of file NonPlayerCreatureObject.cpp.
References server::zone::objects::creature::AiAgentImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class NonPlayerCreatureObject friend
Definition at line 145 of file NonPlayerCreatureObject.h.
Member Data Documentation
WeakReference<NonPlayerCreatureObject*> server::zone::objects::creature::NonPlayerCreatureObjectImplementation::_this
Definition at line 111 of file NonPlayerCreatureObject.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/NonPlayerCreatureObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/NonPlayerCreatureObject.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/NonPlayerCreatureObjectImplementation.cpp