Core3: server::zone::managers::creature::LairObserverAdapter Class Reference
server::zone::managers::creature::LairObserverAdapter Class Reference
#include <LairObserver.h>
Public Member Functions
LairObserverAdapter (LairObserver *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void notifyDestruction (TangibleObject *lair, TangibleObject *attacker, int condition)
bool checkForNewSpawns (TangibleObject *lair, bool forceSpawn)
void healLair (TangibleObject *lair, TangibleObject *attacker)
void checkForHeal (TangibleObject *lair, TangibleObject *attacker, bool forceNewUpdate)
void doAggro (TangibleObject *lair, TangibleObject *attacker)
void setDifficulty (int diff)
bool isLairObserver ()
int getLivingCreatureCount ()
int getLairType ()
int getSpawnNumber ()
Detailed Description
Definition at line 200 of file LairObserver.h.
Constructor & Destructor Documentation
LairObserverAdapter::LairObserverAdapter (LairObserver * impl)
Definition at line 437 of file LairObserver.cpp.
Member Function Documentation
void LairObserverAdapter::checkForHeal (TangibleObject * lair, TangibleObject * attacker, bool forceNewUpdate)
Definition at line 520 of file LairObserver.cpp.
Referenced by invokeMethod().
bool LairObserverAdapter::checkForNewSpawns (TangibleObject * lair, bool forceSpawn)
Definition at line 512 of file LairObserver.cpp.
Referenced by invokeMethod().
void LairObserverAdapter::doAggro (TangibleObject * lair, TangibleObject * attacker)
Definition at line 524 of file LairObserver.cpp.
Referenced by invokeMethod().
int LairObserverAdapter::getLairType ()
Definition at line 540 of file LairObserver.cpp.
Referenced by invokeMethod().
int LairObserverAdapter::getLivingCreatureCount ()
Definition at line 536 of file LairObserver.cpp.
Referenced by invokeMethod().
int LairObserverAdapter::getSpawnNumber ()
Definition at line 544 of file LairObserver.cpp.
Referenced by invokeMethod().
void LairObserverAdapter::healLair (TangibleObject * lair, TangibleObject * attacker)
Definition at line 516 of file LairObserver.cpp.
Referenced by invokeMethod().
void LairObserverAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 440 of file LairObserver.cpp.
References checkForHeal(), checkForNewSpawns(), doAggro(), getLairType(), getLivingCreatureCount(), getSpawnNumber(), healLair(), isLairObserver(), notifyDestruction(), notifyObserverEvent(), RPC_CHECKFORHEAL__TANGIBLEOBJECT_TANGIBLEOBJECT_BOOL_, RPC_CHECKFORNEWSPAWNS__TANGIBLEOBJECT_BOOL_, RPC_DOAGGRO__TANGIBLEOBJECT_TANGIBLEOBJECT_, RPC_GETLAIRTYPE__, RPC_GETLIVINGCREATURECOUNT__, RPC_GETSPAWNNUMBER__, RPC_HEALLAIR__TANGIBLEOBJECT_TANGIBLEOBJECT_, RPC_ISLAIROBSERVER__, RPC_NOTIFYDESTRUCTION__TANGIBLEOBJECT_TANGIBLEOBJECT_INT_, RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_, RPC_SETDIFFICULTY__INT_, and setDifficulty().
bool LairObserverAdapter::isLairObserver ()
Definition at line 532 of file LairObserver.cpp.
Referenced by invokeMethod().
void LairObserverAdapter::notifyDestruction (TangibleObject * lair, TangibleObject * attacker, int condition)
Definition at line 508 of file LairObserver.cpp.
Referenced by invokeMethod().
int LairObserverAdapter::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 504 of file LairObserver.cpp.
Referenced by invokeMethod().
void LairObserverAdapter::setDifficulty (int diff)
Definition at line 528 of file LairObserver.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/LairObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/LairObserver.cpp