Core3: server::zone::managers::weather::WeatherManagerImplementation Class Reference
server::zone::managers::weather::WeatherManagerImplementation Class Reference
#include <WeatherManager.h>
Public Member Functions
WeatherManagerImplementation (Zone *planet)
WeatherManagerImplementation (DummyConstructorParameter *param)
void initialize ()
void createNewWeatherPattern ()
void sendWeatherTo (CreatureObject *player)
void enableWeather (CreatureObject *player)
void disableWeather (CreatureObject *player)
void changeWeather (CreatureObject *player, int newWeather)
bool isWeatherEnabled ()
void setWeatherEnabled (bool value)
void printInfo (CreatureObject *player)
operator const WeatherManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< WeatherManager * > _this
Static Public Attributes
static const int CLEAR = 0
static const int LIGHTSTORM = 1
static const int STORM = 2
static const int HEAVYSTORM = 3
static const int EXTREMESTORM = 4
Protected Member Functions
virtual ~WeatherManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
Reference< WeatherChangeEvent * > weatherChangeEvent
Private Member Functions
bool loadLuaConfig ()
void loadDefaultValues ()
void applySandstormDamage (CreatureObject *player)
int calculateSandstormProtection (CreatureObject *player)
Private Attributes
ManagedReference< Zone * > zone
bool weatherEnabled
byte baseWeather
unsigned int averageWeatherDuration
unsigned int weatherStability
bool hasDamagingSandstorms
Reference< WeatherMap * > currentMap
Vector< float > windX
Vector< float > windY
Vector< float > windMagnitude
int sandstormDamage
Friends
class WeatherManager
Detailed Description
Definition at line 154 of file WeatherManager.h.
Constructor & Destructor Documentation
WeatherManagerImplementation::WeatherManagerImplementation (Zone * planet)
Definition at line 293 of file WeatherManager.cpp.
References _initializeImplementation(), and zone.
WeatherManagerImplementation::WeatherManagerImplementation (DummyConstructorParameter * param)
Definition at line 179 of file WeatherManager.cpp.
References _initializeImplementation().
WeatherManagerImplementation::~WeatherManagerImplementation () protected virtual
Definition at line 184 of file WeatherManager.cpp.
Member Function Documentation
DistributedObjectStub * WeatherManagerImplementation::_getStub ()
Definition at line 204 of file WeatherManager.cpp.
References _this.
void WeatherManagerImplementation::_initializeImplementation () protected
Definition at line 191 of file WeatherManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by WeatherManagerImplementation().
void WeatherManagerImplementation::_serializationHelperMethod () protected
Definition at line 240 of file WeatherManager.cpp.
Referenced by _initializeImplementation().
void WeatherManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 199 of file WeatherManager.cpp.
References _this.
Referenced by server::zone::managers::weather::WeatherManager::WeatherManager().
void WeatherManagerImplementation::applySandstormDamage (CreatureObject * player) private
Applies sandstorm effects to exposed players on the planet. Calls calculateSandstormProtection() to determine how much of the effects to apply.
Precondition
Weather Manager and player are locked.
Postcondition
Weather Manager is locked.
Player is locked.
Parameters
player The player that the sandstorm effects will potentially be applied to.
Definition at line 177 of file WeatherManagerImplementation.cpp.
References CreatureAttribute::ACTION, calculateSandstormProtection(), server::zone::objects::creature::CreatureObject::dismount(), server::zone::objects::creature::CreatureObject::getCurrentCamp(), server::zone::objects::scene::SceneObject::getParentID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), CreatureAttribute::HEALTH, server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::creature::CreatureObject::isKnockedDown(), server::zone::objects::creature::CreatureObject::isMounted(), server::zone::objects::creature::CreatureObject::isOnline(), server::zone::objects::creature::CreatureObject::isProne(), server::zone::objects::player::PlayerObject::isTeleporting(), CreaturePosture::KNOCKEDDOWN, CreatureAttribute::MIND, sandstormDamage, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setBlindedState(), and server::zone::objects::creature::CreatureObject::setPosture().
Referenced by sendWeatherTo().
int WeatherManagerImplementation::calculateSandstormProtection (CreatureObject * player) private
Counts how many pieces of protecting clothing or armour a player is wearing for the purposes of sandstorm effects.
Precondition
Weather Manager and player are locked.
Postcondition
Weather Manager and player are locked.
Parameters
player The player we are applying sandstorm effects to.
sandstormCoverings A Vector created in applySandstormDamage() that will store the number of clothing and armour pieces the player is wearing.
Definition at line 219 of file WeatherManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getSlottedObject().
Referenced by applySandstormDamage().
void WeatherManagerImplementation::changeWeather (CreatureObject * player, int newWeather)
Definition at line 327 of file WeatherManagerImplementation.cpp.
References _this, baseWeather, and disableWeather().
Referenced by server::zone::managers::weather::WeatherManager::changeWeather().
void WeatherManagerImplementation::createNewWeatherPattern ()
Creates a new weather map
Definition at line 109 of file WeatherManagerImplementation.cpp.
References _this, averageWeatherDuration, baseWeather, currentMap, weatherChangeEvent, weatherStability, and zone.
Referenced by server::zone::managers::weather::WeatherManager::createNewWeatherPattern(), and initialize().
void WeatherManagerImplementation::disableWeather (CreatureObject * player)
Definition at line 306 of file WeatherManagerImplementation.cpp.
References _this, currentMap, server::zone::objects::creature::CreatureObject::sendSystemMessage(), weatherChangeEvent, and weatherEnabled.
Referenced by changeWeather(), and server::zone::managers::weather::WeatherManager::disableWeather().
void WeatherManagerImplementation::enableWeather (CreatureObject * player)
Definition at line 297 of file WeatherManagerImplementation.cpp.
References initialize(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::weather::WeatherManager::enableWeather().
void WeatherManagerImplementation::finalize () protected
Definition at line 188 of file WeatherManager.cpp.
void WeatherManagerImplementation::initialize ()
Initializes the weather manager events and some of the customization variables. Calls loadLuaConfig() to read in the lua values and schedules the weather change event.
Definition at line 23 of file WeatherManagerImplementation.cpp.
References createNewWeatherPattern(), loadDefaultValues(), loadLuaConfig(), weatherChangeEvent, weatherEnabled, windMagnitude, windX, windY, and zone.
Referenced by enableWeather(), and server::zone::managers::weather::WeatherManager::initialize().
bool WeatherManagerImplementation::isWeatherEnabled ()
Definition at line 299 of file WeatherManager.cpp.
References weatherEnabled.
Referenced by server::zone::managers::weather::WeatherManager::isWeatherEnabled().
void WeatherManagerImplementation::loadDefaultValues () private
Configures the weather manager with default values if lua loading fails.
Definition at line 96 of file WeatherManagerImplementation.cpp.
References _this, averageWeatherDuration, baseWeather, hasDamagingSandstorms, weatherEnabled, and weatherStability.
Referenced by initialize().
bool WeatherManagerImplementation::loadLuaConfig () private
Loads the weather customization values from the lua script. If there is an error during loading, loadDefaultValues() will be triggered.
Definition at line 55 of file WeatherManagerImplementation.cpp.
References _this, averageWeatherDuration, baseWeather, hasDamagingSandstorms, sandstormDamage, weatherStability, and zone.
Referenced by initialize().
void WeatherManagerImplementation::lock (bool doLock = true) protected
Definition at line 212 of file WeatherManager.cpp.
References _this.
void WeatherManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 216 of file WeatherManager.cpp.
References _this.
WeatherManagerImplementation::operator const WeatherManager * ()
Definition at line 208 of file WeatherManager.cpp.
void WeatherManagerImplementation::printInfo (CreatureObject * player)
Definition at line 340 of file WeatherManagerImplementation.cpp.
References baseWeather, currentMap, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::weather::WeatherManager::printInfo().
void WeatherManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 247 of file WeatherManager.cpp.
References readObjectMember().
bool WeatherManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 266 of file WeatherManager.cpp.
Referenced by readObject().
void WeatherManagerImplementation::rlock (bool doLock = true) protected
Definition at line 220 of file WeatherManager.cpp.
References _this.
void WeatherManagerImplementation::runlock (bool doLock = true) protected
Definition at line 236 of file WeatherManager.cpp.
References _this.
void WeatherManagerImplementation::sendWeatherTo (CreatureObject * player)
Sends the ServerWeatherMessage packet to the players.
Precondition
Locks the player for the duration of the method.
Parameters
player The player who will receive the new weather information.
Definition at line 138 of file WeatherManagerImplementation.cpp.
References applySandstormDamage(), baseWeather, currentMap, server::zone::managers::weather::WeatherManager::EXTREMESTORM, server::zone::objects::creature::CreatureObject::getCurrentWeather(), server::zone::objects::creature::CreatureObject::getCurrentWind(), hasDamagingSandstorms, server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setCurrentWeather(), windMagnitude, windX, and windY.
Referenced by server::zone::managers::weather::WeatherManager::sendWeatherTo().
void WeatherManagerImplementation::setWeatherEnabled (bool value)
Definition at line 304 of file WeatherManager.cpp.
References weatherEnabled.
Referenced by server::zone::managers::weather::WeatherManager::setWeatherEnabled().
void WeatherManagerImplementation::unlock (bool doLock = true) protected
Definition at line 232 of file WeatherManager.cpp.
References _this.
void WeatherManagerImplementation::wlock (bool doLock = true) protected
Definition at line 224 of file WeatherManager.cpp.
References _this.
void WeatherManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 228 of file WeatherManager.cpp.
References _this.
void WeatherManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 276 of file WeatherManager.cpp.
References writeObjectMembers().
int WeatherManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 283 of file WeatherManager.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class WeatherManager friend
Definition at line 297 of file WeatherManager.h.
Member Data Documentation
WeakReference<WeatherManager*> server::zone::managers::weather::WeatherManagerImplementation::_this
Definition at line 263 of file WeatherManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), changeWeather(), createNewWeatherPattern(), disableWeather(), loadDefaultValues(), loadLuaConfig(), lock(), rlock(), runlock(), unlock(), and wlock().
unsigned int server::zone::managers::weather::WeatherManagerImplementation::averageWeatherDuration private
Definition at line 173 of file WeatherManager.h.
Referenced by createNewWeatherPattern(), loadDefaultValues(), and loadLuaConfig().
byte server::zone::managers::weather::WeatherManagerImplementation::baseWeather private
Definition at line 171 of file WeatherManager.h.
Referenced by changeWeather(), createNewWeatherPattern(), loadDefaultValues(), loadLuaConfig(), printInfo(), and sendWeatherTo().
const int server::zone::managers::weather::WeatherManagerImplementation::CLEAR = 0 static
Definition at line 156 of file WeatherManager.h.
Reference<WeatherMap* > server::zone::managers::weather::WeatherManagerImplementation::currentMap private
Definition at line 179 of file WeatherManager.h.
Referenced by createNewWeatherPattern(), disableWeather(), printInfo(), and sendWeatherTo().
const int server::zone::managers::weather::WeatherManagerImplementation::EXTREMESTORM = 4 static
Definition at line 164 of file WeatherManager.h.
bool server::zone::managers::weather::WeatherManagerImplementation::hasDamagingSandstorms private
Definition at line 177 of file WeatherManager.h.
Referenced by loadDefaultValues(), loadLuaConfig(), and sendWeatherTo().
const int server::zone::managers::weather::WeatherManagerImplementation::HEAVYSTORM = 3 static
Definition at line 162 of file WeatherManager.h.
const int server::zone::managers::weather::WeatherManagerImplementation::LIGHTSTORM = 1 static
Definition at line 158 of file WeatherManager.h.
int server::zone::managers::weather::WeatherManagerImplementation::sandstormDamage private
Definition at line 187 of file WeatherManager.h.
Referenced by applySandstormDamage(), and loadLuaConfig().
const int server::zone::managers::weather::WeatherManagerImplementation::STORM = 2 static
Definition at line 160 of file WeatherManager.h.
Reference<WeatherChangeEvent* > server::zone::managers::weather::WeatherManagerImplementation::weatherChangeEvent protected
Definition at line 190 of file WeatherManager.h.
Referenced by createNewWeatherPattern(), disableWeather(), and initialize().
bool server::zone::managers::weather::WeatherManagerImplementation::weatherEnabled private
Definition at line 169 of file WeatherManager.h.
Referenced by disableWeather(), initialize(), isWeatherEnabled(), loadDefaultValues(), and setWeatherEnabled().
unsigned int server::zone::managers::weather::WeatherManagerImplementation::weatherStability private
Definition at line 175 of file WeatherManager.h.
Referenced by createNewWeatherPattern(), loadDefaultValues(), and loadLuaConfig().
Vector<float> server::zone::managers::weather::WeatherManagerImplementation::windMagnitude private
Definition at line 185 of file WeatherManager.h.
Referenced by initialize(), and sendWeatherTo().
Vector<float> server::zone::managers::weather::WeatherManagerImplementation::windX private
Definition at line 181 of file WeatherManager.h.
Referenced by initialize(), and sendWeatherTo().
Vector<float> server::zone::managers::weather::WeatherManagerImplementation::windY private
Definition at line 183 of file WeatherManager.h.
Referenced by initialize(), and sendWeatherTo().
ManagedReference<Zone* > server::zone::managers::weather::WeatherManagerImplementation::zone private
Definition at line 167 of file WeatherManager.h.
Referenced by createNewWeatherPattern(), initialize(), loadLuaConfig(), and WeatherManagerImplementation().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/weather/WeatherManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/weather/WeatherManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/weather/WeatherManagerImplementation.cpp