Core3: PlayerManagerCommand Class Reference
PlayerManagerCommand Class Reference
#include <PlayerManagerCommand.h>
Static Public Member Functions
static int executeCommand (CreatureObject *creature, uint64 target, const UnicodeString &arguments)
static void sendSyntax (CreatureObject *player)
Detailed Description
Definition at line 14 of file PlayerManagerCommand.h.
Member Function Documentation
static int PlayerManagerCommand::executeCommand (CreatureObject * creature, uint64 target, const UnicodeString & arguments) inline static
Definition at line 16 of file PlayerManagerCommand.h.
References server::zone::objects::creature::CreatureObject::isPlayerCreature(), sendSyntax(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
static void PlayerManagerCommand::sendSyntax (CreatureObject * player) inline static
Definition at line 65 of file PlayerManagerCommand.h.
References server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by executeCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/PlayerManagerCommand.h