Core3: server::zone::objects::auction::AuctionItemImplementation Class Reference
server::zone::objects::auction::AuctionItemImplementation Class Reference
#include <AuctionItem.h>
Public Member Functions
AuctionItemImplementation (unsigned long long objectid)
AuctionItemImplementation (DummyConstructorParameter *param)
int compareTo (AuctionItem *obj)
void notifyLoadFromDatabase ()
void setVendorID (unsigned long long val)
void setItemName (const String &name)
void setItemDescription (const String &descr)
void setPrice (int newPrice)
void setProxy (int newProxy)
void setAuctionedItemObjectID (unsigned long long objectID)
void setItemType (int type)
void setOwnerID (unsigned long long ownerObjectID)
void setOfferToID (unsigned long long vendorOwnerID)
void setBidderName (const String &name)
void setOwnerName (const String &name)
void setAuction (bool isAuction)
void setAuctionPremium ()
void clearAuctionWithdraw ()
void setOnBazaar (bool val)
void setExpireTime (int time)
void setBuyerID (unsigned long long id)
void setStatus (int value)
bool isOnBazaar ()
bool isAuction ()
int getStatus ()
unsigned long long getVendorID ()
unsigned long long getAuctionedItemObjectID ()
unsigned long long getOwnerID ()
unsigned long long getOfferToID ()
void setVendorUID (const String &uid)
const String getVendorUID ()
String getOwnerName ()
String getItemName ()
int getExpireTime ()
int getPrice ()
int getProxy ()
int getItemType ()
unsigned long long getBuyerID ()
String getBidderName ()
String getItemDescription ()
int getAuctionOptions ()
bool isPremiumAuction ()
bool isOwner (CreatureObject *player)
bool isAuctionObject ()
operator const AuctionItem * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< AuctionItem * > _this
Static Public Attributes
static const int OPTION_PREMIUM = 0x400
static const int OPTION_WITHDRAW = 0x800
static const int FORSALE = 1
static const int SOLD = 2
static const int EXPIRED = 4
static const int OFFERED = 5
static const int RETRIEVED = 6
Protected Member Functions
virtual ~AuctionItemImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
unsigned long long vendorID
unsigned long long auctionedItemObjectID
int itemType
unsigned long long ownerID
String ownerName
String bidderName
unsigned long long offerToID
String vuid
String itemName
String itemDescription
int price
int proxyBid
bool auction
int status
bool onBazaar
unsigned long long buyerID
unsigned int expireTime
bool updated
int auctionOptions
Friends
class AuctionItem
Detailed Description
Definition at line 189 of file AuctionItem.h.
Constructor & Destructor Documentation
AuctionItemImplementation::AuctionItemImplementation (unsigned long long objectid)
Definition at line 968 of file AuctionItem.cpp.
References _initializeImplementation(), auction, auctionedItemObjectID, auctionOptions, buyerID, expireTime, FORSALE, itemType, offerToID, onBazaar, ownerID, price, proxyBid, status, and updated.
AuctionItemImplementation::AuctionItemImplementation (DummyConstructorParameter * param)
Definition at line 626 of file AuctionItem.cpp.
References _initializeImplementation().
AuctionItemImplementation::~AuctionItemImplementation () protected virtual
Definition at line 631 of file AuctionItem.cpp.
Member Function Documentation
DistributedObjectStub * AuctionItemImplementation::_getStub ()
Definition at line 651 of file AuctionItem.cpp.
References _this.
void AuctionItemImplementation::_initializeImplementation () protected
Definition at line 638 of file AuctionItem.cpp.
References _serializationHelperMethod(), and _this.
Referenced by AuctionItemImplementation().
void AuctionItemImplementation::_serializationHelperMethod () protected
Definition at line 687 of file AuctionItem.cpp.
Referenced by _initializeImplementation().
void AuctionItemImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 646 of file AuctionItem.cpp.
References _this.
Referenced by server::zone::objects::auction::AuctionItem::AuctionItem().
void AuctionItemImplementation::clearAuctionWithdraw ()
Definition at line 13 of file AuctionItemImplementation.cpp.
References auctionOptions, and OPTION_WITHDRAW.
Referenced by server::zone::objects::auction::AuctionItem::clearAuctionWithdraw(), and notifyLoadFromDatabase().
int AuctionItemImplementation::compareTo (AuctionItem * obj)
Compares object ids of this object with obj
Precondition
{ this object is locked, obj is not null }
Postcondition
{this object is locked }
Parameters
obj SceneObject that will be compared to
Returns
returns 1 if this < obj, -1 if this > obj and 0 if this == obj
Definition at line 998 of file AuctionItem.cpp.
References server::zone::objects::auction::AuctionItem::getAuctionedItemObjectID(), and getAuctionedItemObjectID().
Referenced by server::zone::objects::auction::AuctionItem::compareTo().
void AuctionItemImplementation::finalize () protected
Definition at line 635 of file AuctionItem.cpp.
unsigned long long AuctionItemImplementation::getAuctionedItemObjectID ()
Definition at line 1116 of file AuctionItem.cpp.
References auctionedItemObjectID.
Referenced by compareTo(), and server::zone::objects::auction::AuctionItem::getAuctionedItemObjectID().
int AuctionItemImplementation::getAuctionOptions ()
Definition at line 1186 of file AuctionItem.cpp.
References auctionOptions.
Referenced by server::zone::objects::auction::AuctionItem::getAuctionOptions().
String AuctionItemImplementation::getBidderName ()
Definition at line 1176 of file AuctionItem.cpp.
References bidderName.
Referenced by server::zone::objects::auction::AuctionItem::getBidderName().
unsigned long long AuctionItemImplementation::getBuyerID ()
Definition at line 1171 of file AuctionItem.cpp.
References buyerID.
Referenced by server::zone::objects::auction::AuctionItem::getBuyerID().
int AuctionItemImplementation::getExpireTime ()
Definition at line 1151 of file AuctionItem.cpp.
References expireTime.
Referenced by server::zone::objects::auction::AuctionItem::getExpireTime().
String AuctionItemImplementation::getItemDescription ()
Definition at line 1181 of file AuctionItem.cpp.
References itemDescription.
Referenced by server::zone::objects::auction::AuctionItem::getItemDescription().
String AuctionItemImplementation::getItemName ()
Definition at line 1146 of file AuctionItem.cpp.
References itemName.
Referenced by server::zone::objects::auction::AuctionItem::getItemName().
int AuctionItemImplementation::getItemType ()
Definition at line 1166 of file AuctionItem.cpp.
References itemType.
Referenced by server::zone::objects::auction::AuctionItem::getItemType().
unsigned long long AuctionItemImplementation::getOfferToID ()
Definition at line 1126 of file AuctionItem.cpp.
References offerToID.
Referenced by server::zone::objects::auction::AuctionItem::getOfferToID().
unsigned long long AuctionItemImplementation::getOwnerID ()
Definition at line 1121 of file AuctionItem.cpp.
References ownerID.
Referenced by server::zone::objects::auction::AuctionItem::getOwnerID(), and isOwner().
String AuctionItemImplementation::getOwnerName ()
Definition at line 1141 of file AuctionItem.cpp.
References ownerName.
Referenced by server::zone::objects::auction::AuctionItem::getOwnerName().
int AuctionItemImplementation::getPrice ()
Definition at line 1156 of file AuctionItem.cpp.
References price.
Referenced by server::zone::objects::auction::AuctionItem::getPrice().
int AuctionItemImplementation::getProxy ()
Definition at line 1161 of file AuctionItem.cpp.
References proxyBid.
Referenced by server::zone::objects::auction::AuctionItem::getProxy().
int AuctionItemImplementation::getStatus ()
Definition at line 1106 of file AuctionItem.cpp.
References status.
Referenced by server::zone::objects::auction::AuctionItem::getStatus().
unsigned long long AuctionItemImplementation::getVendorID ()
Definition at line 1111 of file AuctionItem.cpp.
References vendorID.
Referenced by server::zone::objects::auction::AuctionItem::getVendorID().
const String AuctionItemImplementation::getVendorUID ()
Definition at line 1136 of file AuctionItem.cpp.
References vuid.
Referenced by server::zone::objects::auction::AuctionItem::getVendorUID().
bool AuctionItemImplementation::isAuction ()
Definition at line 1101 of file AuctionItem.cpp.
References auction.
Referenced by server::zone::objects::auction::AuctionItem::isAuction(), and setAuction().
bool AuctionItemImplementation::isAuctionObject ()
Definition at line 1201 of file AuctionItem.cpp.
Referenced by server::zone::objects::auction::AuctionItem::isAuctionObject().
bool AuctionItemImplementation::isOnBazaar ()
Definition at line 1096 of file AuctionItem.cpp.
References onBazaar.
Referenced by server::zone::objects::auction::AuctionItem::isOnBazaar().
bool AuctionItemImplementation::isOwner (CreatureObject * player)
Definition at line 1196 of file AuctionItem.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), and getOwnerID().
Referenced by server::zone::objects::auction::AuctionItem::isOwner().
bool AuctionItemImplementation::isPremiumAuction ()
Definition at line 1191 of file AuctionItem.cpp.
References auctionOptions, and OPTION_PREMIUM.
Referenced by server::zone::objects::auction::AuctionItem::isPremiumAuction().
void AuctionItemImplementation::lock (bool doLock = true) protected
Definition at line 659 of file AuctionItem.cpp.
References _this.
void AuctionItemImplementation::lock (ManagedObject * obj) protected
Definition at line 663 of file AuctionItem.cpp.
References _this.
void AuctionItemImplementation::notifyLoadFromDatabase ()
Definition at line 18 of file AuctionItemImplementation.cpp.
References clearAuctionWithdraw().
Referenced by server::zone::objects::auction::AuctionItem::notifyLoadFromDatabase().
AuctionItemImplementation::operator const AuctionItem * ()
Definition at line 655 of file AuctionItem.cpp.
void AuctionItemImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 694 of file AuctionItem.cpp.
References readObjectMember().
bool AuctionItemImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 713 of file AuctionItem.cpp.
References auction, auctionedItemObjectID, auctionOptions, bidderName, buyerID, expireTime, itemDescription, itemName, itemType, offerToID, onBazaar, ownerID, ownerName, price, proxyBid, status, updated, vendorID, and vuid.
Referenced by readObject().
void AuctionItemImplementation::rlock (bool doLock = true) protected
Definition at line 667 of file AuctionItem.cpp.
References _this.
void AuctionItemImplementation::runlock (bool doLock = true) protected
Definition at line 683 of file AuctionItem.cpp.
References _this.
void AuctionItemImplementation::setAuction (bool isAuction)
Definition at line 1066 of file AuctionItem.cpp.
References auction, and isAuction().
Referenced by server::zone::objects::auction::AuctionItem::setAuction().
void AuctionItemImplementation::setAuctionedItemObjectID (unsigned long long objectID)
Definition at line 1036 of file AuctionItem.cpp.
References auctionedItemObjectID.
Referenced by server::zone::objects::auction::AuctionItem::setAuctionedItemObjectID().
void AuctionItemImplementation::setAuctionPremium ()
Definition at line 1071 of file AuctionItem.cpp.
References auctionOptions, and OPTION_PREMIUM.
Referenced by server::zone::objects::auction::AuctionItem::setAuctionPremium().
void AuctionItemImplementation::setBidderName (const String & name)
Definition at line 1056 of file AuctionItem.cpp.
References bidderName.
Referenced by server::zone::objects::auction::AuctionItem::setBidderName().
void AuctionItemImplementation::setBuyerID (unsigned long long id)
Definition at line 1086 of file AuctionItem.cpp.
References buyerID.
Referenced by server::zone::objects::auction::AuctionItem::setBuyerID().
void AuctionItemImplementation::setExpireTime (int time)
Definition at line 1081 of file AuctionItem.cpp.
References expireTime.
Referenced by server::zone::objects::auction::AuctionItem::setExpireTime().
void AuctionItemImplementation::setItemDescription (const String & descr)
Definition at line 1021 of file AuctionItem.cpp.
References itemDescription.
Referenced by server::zone::objects::auction::AuctionItem::setItemDescription().
void AuctionItemImplementation::setItemName (const String & name)
Definition at line 1016 of file AuctionItem.cpp.
References itemName.
Referenced by server::zone::objects::auction::AuctionItem::setItemName().
void AuctionItemImplementation::setItemType (int type)
Definition at line 1041 of file AuctionItem.cpp.
References itemType.
Referenced by server::zone::objects::auction::AuctionItem::setItemType().
void AuctionItemImplementation::setOfferToID (unsigned long long vendorOwnerID)
Definition at line 1051 of file AuctionItem.cpp.
References offerToID.
Referenced by server::zone::objects::auction::AuctionItem::setOfferToID().
void AuctionItemImplementation::setOnBazaar (bool val)
Definition at line 1076 of file AuctionItem.cpp.
References onBazaar.
Referenced by server::zone::objects::auction::AuctionItem::setOnBazaar().
void AuctionItemImplementation::setOwnerID (unsigned long long ownerObjectID)
Definition at line 1046 of file AuctionItem.cpp.
References ownerID.
Referenced by server::zone::objects::auction::AuctionItem::setOwnerID().
void AuctionItemImplementation::setOwnerName (const String & name)
Definition at line 1061 of file AuctionItem.cpp.
References ownerName.
Referenced by server::zone::objects::auction::AuctionItem::setOwnerName().
void AuctionItemImplementation::setPrice (int newPrice)
Definition at line 1026 of file AuctionItem.cpp.
References price.
Referenced by server::zone::objects::auction::AuctionItem::setPrice().
void AuctionItemImplementation::setProxy (int newProxy)
Definition at line 1031 of file AuctionItem.cpp.
References proxyBid.
Referenced by server::zone::objects::auction::AuctionItem::setProxy().
void AuctionItemImplementation::setStatus (int value)
Definition at line 1091 of file AuctionItem.cpp.
References status.
Referenced by server::zone::objects::auction::AuctionItem::setStatus().
void AuctionItemImplementation::setVendorID (unsigned long long val)
Definition at line 1011 of file AuctionItem.cpp.
References vendorID.
Referenced by server::zone::objects::auction::AuctionItem::setVendorID().
void AuctionItemImplementation::setVendorUID (const String & uid)
Definition at line 1131 of file AuctionItem.cpp.
References vuid.
Referenced by server::zone::objects::auction::AuctionItem::setVendorUID().
void AuctionItemImplementation::unlock (bool doLock = true) protected
Definition at line 679 of file AuctionItem.cpp.
References _this.
void AuctionItemImplementation::wlock (bool doLock = true) protected
Definition at line 671 of file AuctionItem.cpp.
References _this.
void AuctionItemImplementation::wlock (ManagedObject * obj) protected
Definition at line 675 of file AuctionItem.cpp.
References _this.
void AuctionItemImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 799 of file AuctionItem.cpp.
References writeObjectMembers().
int AuctionItemImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 806 of file AuctionItem.cpp.
References auction, auctionedItemObjectID, auctionOptions, bidderName, buyerID, expireTime, itemDescription, itemName, itemType, offerToID, onBazaar, ownerID, ownerName, price, proxyBid, status, updated, vendorID, and vuid.
Referenced by writeObject().
Friends And Related Function Documentation
friend class AuctionItem friend
Definition at line 373 of file AuctionItem.h.
Member Data Documentation
WeakReference<AuctionItem*> server::zone::objects::auction::AuctionItemImplementation::_this
Definition at line 339 of file AuctionItem.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
bool server::zone::objects::auction::AuctionItemImplementation::auction protected
Definition at line 215 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), isAuction(), readObjectMember(), setAuction(), and writeObjectMembers().
unsigned long long server::zone::objects::auction::AuctionItemImplementation::auctionedItemObjectID protected
Definition at line 193 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), getAuctionedItemObjectID(), readObjectMember(), setAuctionedItemObjectID(), and writeObjectMembers().
int server::zone::objects::auction::AuctionItemImplementation::auctionOptions protected
Definition at line 227 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), clearAuctionWithdraw(), getAuctionOptions(), isPremiumAuction(), readObjectMember(), setAuctionPremium(), and writeObjectMembers().
String server::zone::objects::auction::AuctionItemImplementation::bidderName protected
Definition at line 201 of file AuctionItem.h.
Referenced by getBidderName(), readObjectMember(), setBidderName(), and writeObjectMembers().
unsigned long long server::zone::objects::auction::AuctionItemImplementation::buyerID protected
Definition at line 221 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), getBuyerID(), readObjectMember(), setBuyerID(), and writeObjectMembers().
const int server::zone::objects::auction::AuctionItemImplementation::EXPIRED = 4 static
Definition at line 238 of file AuctionItem.h.
unsigned int server::zone::objects::auction::AuctionItemImplementation::expireTime protected
Definition at line 223 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), getExpireTime(), readObjectMember(), setExpireTime(), and writeObjectMembers().
const int server::zone::objects::auction::AuctionItemImplementation::FORSALE = 1 static
Definition at line 234 of file AuctionItem.h.
Referenced by AuctionItemImplementation().
String server::zone::objects::auction::AuctionItemImplementation::itemDescription protected
Definition at line 209 of file AuctionItem.h.
Referenced by getItemDescription(), readObjectMember(), setItemDescription(), and writeObjectMembers().
String server::zone::objects::auction::AuctionItemImplementation::itemName protected
Definition at line 207 of file AuctionItem.h.
Referenced by getItemName(), readObjectMember(), setItemName(), and writeObjectMembers().
int server::zone::objects::auction::AuctionItemImplementation::itemType protected
Definition at line 195 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), getItemType(), readObjectMember(), setItemType(), and writeObjectMembers().
const int server::zone::objects::auction::AuctionItemImplementation::OFFERED = 5 static
Definition at line 240 of file AuctionItem.h.
unsigned long long server::zone::objects::auction::AuctionItemImplementation::offerToID protected
Definition at line 203 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), getOfferToID(), readObjectMember(), setOfferToID(), and writeObjectMembers().
bool server::zone::objects::auction::AuctionItemImplementation::onBazaar protected
Definition at line 219 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), isOnBazaar(), readObjectMember(), setOnBazaar(), and writeObjectMembers().
const int server::zone::objects::auction::AuctionItemImplementation::OPTION_PREMIUM = 0x400 static
Definition at line 230 of file AuctionItem.h.
Referenced by isPremiumAuction(), and setAuctionPremium().
const int server::zone::objects::auction::AuctionItemImplementation::OPTION_WITHDRAW = 0x800 static
Definition at line 232 of file AuctionItem.h.
Referenced by clearAuctionWithdraw().
unsigned long long server::zone::objects::auction::AuctionItemImplementation::ownerID protected
Definition at line 197 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), getOwnerID(), readObjectMember(), setOwnerID(), and writeObjectMembers().
String server::zone::objects::auction::AuctionItemImplementation::ownerName protected
Definition at line 199 of file AuctionItem.h.
Referenced by getOwnerName(), readObjectMember(), setOwnerName(), and writeObjectMembers().
int server::zone::objects::auction::AuctionItemImplementation::price protected
Definition at line 211 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), getPrice(), readObjectMember(), setPrice(), and writeObjectMembers().
int server::zone::objects::auction::AuctionItemImplementation::proxyBid protected
Definition at line 213 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), getProxy(), readObjectMember(), setProxy(), and writeObjectMembers().
const int server::zone::objects::auction::AuctionItemImplementation::RETRIEVED = 6 static
Definition at line 242 of file AuctionItem.h.
const int server::zone::objects::auction::AuctionItemImplementation::SOLD = 2 static
Definition at line 236 of file AuctionItem.h.
int server::zone::objects::auction::AuctionItemImplementation::status protected
Definition at line 217 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), getStatus(), readObjectMember(), setStatus(), and writeObjectMembers().
bool server::zone::objects::auction::AuctionItemImplementation::updated protected
Definition at line 225 of file AuctionItem.h.
Referenced by AuctionItemImplementation(), readObjectMember(), and writeObjectMembers().
unsigned long long server::zone::objects::auction::AuctionItemImplementation::vendorID protected
Definition at line 191 of file AuctionItem.h.
Referenced by getVendorID(), readObjectMember(), setVendorID(), and writeObjectMembers().
String server::zone::objects::auction::AuctionItemImplementation::vuid protected
Definition at line 205 of file AuctionItem.h.
Referenced by getVendorUID(), readObjectMember(), setVendorUID(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/auction/AuctionItem.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/auction/AuctionItem.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/auction/AuctionItemImplementation.cpp