Core3: server::zone::managers::minigames::ForageManagerAdapter Class Reference
server::zone::managers::minigames::ForageManagerAdapter Class Reference
#include <ForageManager.h>
Public Member Functions
ForageManagerAdapter (ForageManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void deleteForageAreaCollection (String &playerName)
void startForaging (CreatureObject *player, int forageType)
void finishForaging (CreatureObject *player, int forageType, float forageX, float forageY, const String &planet)
bool forageGiveItems (CreatureObject *player, int forageType, float forageX, float forageY, const String &planet)
bool forageGiveResource (CreatureObject *player, float forageX, float forageY, const String &planet, String &resType)
Detailed Description
Definition at line 281 of file ForageManager.h.
Constructor & Destructor Documentation
ForageManagerAdapter::ForageManagerAdapter (ForageManager * impl)
Definition at line 285 of file ForageManager.cpp.
Member Function Documentation
void ForageManagerAdapter::deleteForageAreaCollection (String & playerName)
Definition at line 326 of file ForageManager.cpp.
Referenced by invokeMethod().
void ForageManagerAdapter::finishForaging (CreatureObject * player, int forageType, float forageX, float forageY, const String & planet)
Definition at line 334 of file ForageManager.cpp.
Referenced by invokeMethod().
bool ForageManagerAdapter::forageGiveItems (CreatureObject * player, int forageType, float forageX, float forageY, const String & planet)
Definition at line 338 of file ForageManager.cpp.
Referenced by invokeMethod().
bool ForageManagerAdapter::forageGiveResource (CreatureObject * player, float forageX, float forageY, const String & planet, String & resType)
Definition at line 342 of file ForageManager.cpp.
Referenced by invokeMethod().
void ForageManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 288 of file ForageManager.cpp.
References deleteForageAreaCollection(), finishForaging(), forageGiveItems(), forageGiveResource(), RPC_DELETEFORAGEAREACOLLECTION__STRING_, RPC_FINISHFORAGING__CREATUREOBJECT_INT_FLOAT_FLOAT_STRING_, RPC_FORAGEGIVEITEMS__CREATUREOBJECT_INT_FLOAT_FLOAT_STRING_, RPC_FORAGEGIVERESOURCE__CREATUREOBJECT_FLOAT_FLOAT_STRING_STRING_, RPC_STARTFORAGING__CREATUREOBJECT_INT_, and startForaging().
void ForageManagerAdapter::startForaging (CreatureObject * player, int forageType)
Definition at line 330 of file ForageManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/ForageManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/ForageManager.cpp