Core3: server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation Class Reference
server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation Class Reference
#include <SuiColorBox.h>
Public Member Functions
SuiColorBoxImplementation (CreatureObject *player, unsigned int windowType)
SuiColorBoxImplementation (DummyConstructorParameter *param)
BaseMessage * generateMessage ()
String getColorPalette ()
void setColorPalette (String &pal)
bool isColorPicker ()
operator const SuiColorBox * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
SuiBoxImplementation (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
SuiBoxImplementation (DummyConstructorParameter *param)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
virtual bool isInputBox ()
virtual bool isListBox ()
virtual bool isMessageBox ()
virtual bool isTransferBox ()
virtual bool isBankTransferBox ()
virtual bool isSlicingBox ()
virtual bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
operator const SuiBox * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< SuiColorBox * > _this
Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
WeakReference< SuiBox * > _this
Protected Member Functions
virtual ~SuiColorBoxImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
virtual ~SuiBoxImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
String variable
Protected Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
ManagedWeakReference
< CreatureObject * > player
Reference< SuiCallback * > suiCallback
unsigned int boxID
ManagedWeakReference
< SceneObject * > usingObject
String handlerStr
String cancelButtonText
bool cancelButton
String okButtonText
bool okButton
String otherButtonText
bool otherButton
String promptTitle
String promptText
int boxType
unsigned int windowType
float forceCloseDistance
Vector< String > headerSets
Vector< String > optionSets
int hdrOptCount
bool hasGenerated
Friends
class SuiColorBox
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Detailed Description
Definition at line 98 of file SuiColorBox.h.
Constructor & Destructor Documentation
SuiColorBoxImplementation::SuiColorBoxImplementation (CreatureObject * player, unsigned int windowType)
Definition at line 232 of file SuiColorBox.cpp.
References _initializeImplementation().
SuiColorBoxImplementation::SuiColorBoxImplementation (DummyConstructorParameter * param)
Definition at line 106 of file SuiColorBox.cpp.
References _initializeImplementation().
SuiColorBoxImplementation::~SuiColorBoxImplementation () protected virtual
Definition at line 111 of file SuiColorBox.cpp.
Member Function Documentation
DistributedObjectStub * SuiColorBoxImplementation::_getStub ()
Definition at line 131 of file SuiColorBox.cpp.
References _this.
void SuiColorBoxImplementation::_initializeImplementation () protected
Definition at line 118 of file SuiColorBox.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SuiColorBoxImplementation().
void SuiColorBoxImplementation::_serializationHelperMethod () protected
Definition at line 167 of file SuiColorBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void SuiColorBoxImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 126 of file SuiColorBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_setStub(), and _this.
Referenced by server::zone::objects::player::sui::colorbox::SuiColorBox::SuiColorBox().
void SuiColorBoxImplementation::finalize () protected
Definition at line 115 of file SuiColorBox.cpp.
BaseMessage * SuiColorBoxImplementation::generateMessage () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 11 of file SuiColorBoxImplementation.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::addHeader(), server::zone::objects::player::sui::SuiBoxImplementation::addSetting(), server::zone::objects::player::sui::SuiBoxImplementation::boxID, server::zone::objects::player::sui::SuiBoxImplementation::generateBody(), server::zone::objects::player::sui::SuiBoxImplementation::generateFooter(), server::zone::objects::player::sui::SuiBoxImplementation::generateHeader(), server::zone::objects::player::sui::SuiBoxImplementation::hasGenerated, server::zone::objects::player::sui::SuiBoxImplementation::setHandlerText(), server::zone::objects::player::sui::SuiBoxImplementation::usingObject, and variable.
Referenced by server::zone::objects::player::sui::colorbox::SuiColorBox::generateMessage().
String SuiColorBoxImplementation::getColorPalette ()
Definition at line 236 of file SuiColorBox.cpp.
References variable.
Referenced by server::zone::objects::player::sui::colorbox::SuiColorBox::getColorPalette().
bool SuiColorBoxImplementation::isColorPicker ()
Definition at line 246 of file SuiColorBox.cpp.
Referenced by server::zone::objects::player::sui::colorbox::SuiColorBox::isColorPicker().
void SuiColorBoxImplementation::lock (bool doLock = true) protected
Definition at line 139 of file SuiColorBox.cpp.
References _this.
void SuiColorBoxImplementation::lock (ManagedObject * obj) protected
Definition at line 143 of file SuiColorBox.cpp.
References _this.
SuiColorBoxImplementation::operator const SuiColorBox * ()
Definition at line 135 of file SuiColorBox.cpp.
void SuiColorBoxImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 174 of file SuiColorBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::initializeTransientMembers(), and readObjectMember().
bool SuiColorBoxImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 193 of file SuiColorBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::readObjectMember(), and variable.
Referenced by readObject().
void SuiColorBoxImplementation::rlock (bool doLock = true) protected
Definition at line 147 of file SuiColorBox.cpp.
References _this.
void SuiColorBoxImplementation::runlock (bool doLock = true) protected
Definition at line 163 of file SuiColorBox.cpp.
References _this.
void SuiColorBoxImplementation::setColorPalette (String & pal)
Definition at line 241 of file SuiColorBox.cpp.
References variable.
Referenced by server::zone::objects::player::sui::colorbox::SuiColorBox::setColorPalette().
void SuiColorBoxImplementation::unlock (bool doLock = true) protected
Definition at line 159 of file SuiColorBox.cpp.
References _this.
void SuiColorBoxImplementation::wlock (bool doLock = true) protected
Definition at line 151 of file SuiColorBox.cpp.
References _this.
void SuiColorBoxImplementation::wlock (ManagedObject * obj) protected
Definition at line 155 of file SuiColorBox.cpp.
References _this.
void SuiColorBoxImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 207 of file SuiColorBox.cpp.
References writeObjectMembers().
int SuiColorBoxImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 214 of file SuiColorBox.cpp.
References variable, and server::zone::objects::player::sui::SuiBoxImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class SuiColorBox friend
Definition at line 149 of file SuiColorBox.h.
Member Data Documentation
WeakReference<SuiColorBox*> server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::_this
Definition at line 115 of file SuiColorBox.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
String server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::variable protected
Definition at line 100 of file SuiColorBox.h.
Referenced by generateMessage(), getColorPalette(), readObjectMember(), setColorPalette(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/colorbox/SuiColorBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/colorbox/SuiColorBox.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/colorbox/SuiColorBoxImplementation.cpp