Core3: TransferForceCommand Class Reference
TransferForceCommand Class Reference
#include <TransferForceCommand.h>
Public Member Functions
TransferForceCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file TransferForceCommand.h.
Constructor & Destructor Documentation
TransferForceCommand::TransferForceCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file TransferForceCommand.h.
Member Function Documentation
int TransferForceCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 58 of file TransferForceCommand.h.
References server::zone::objects::creature::CreatureObject::doCombatAnimation(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::isAiAgent(), and server::zone::objects::creature::CreatureObject::isHealableBy().
float TransferForceCommand::getCommandDuration (CreatureObject * object, const UnicodeString & arguments) inline
Definition at line 102 of file TransferForceCommand.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/TransferForceCommand.h