Core3: ZoneTest Class Reference
ZoneTest Class Reference
Public Member Functions
ZoneTest ()
~ZoneTest ()
void setDefaultComponents (SceneObject *object)
Reference< SceneObject * > createSceneObject ()
Reference< ActiveArea * > createActiveArea ()
void SetUp ()
void TearDown ()
Protected Attributes
Reference< ZoneServer * > zoneServer
Reference< Zone * > zone
Reference< ZoneProcessServer * > processServer
AtomicLong nextObjectId
Detailed Description
Definition at line 17 of file ZoneTest.cpp.
Constructor & Destructor Documentation
ZoneTest::ZoneTest () inline
Definition at line 24 of file ZoneTest.cpp.
References nextObjectId.
ZoneTest::~ZoneTest () inline
Definition at line 29 of file ZoneTest.cpp.
Member Function Documentation
Reference<ActiveArea*> ZoneTest::createActiveArea () inline
Definition at line 46 of file ZoneTest.cpp.
References nextObjectId, and setDefaultComponents().
Reference<SceneObject*> ZoneTest::createSceneObject () inline
Definition at line 38 of file ZoneTest.cpp.
References nextObjectId, and setDefaultComponents().
void ZoneTest::setDefaultComponents (SceneObject * object) inline
Definition at line 33 of file ZoneTest.cpp.
Referenced by createActiveArea(), and createSceneObject().
void ZoneTest::SetUp () inline
Definition at line 54 of file ZoneTest.cpp.
References processServer, zone, and zoneServer.
void ZoneTest::TearDown () inline
Definition at line 65 of file ZoneTest.cpp.
Member Data Documentation
AtomicLong ZoneTest::nextObjectId protected
Definition at line 22 of file ZoneTest.cpp.
Referenced by createActiveArea(), createSceneObject(), and ZoneTest().
Reference<ZoneProcessServer*> ZoneTest::processServer protected
Definition at line 21 of file ZoneTest.cpp.
Referenced by SetUp().
Reference<Zone*> ZoneTest::zone protected
Definition at line 20 of file ZoneTest.cpp.
Referenced by SetUp().
Reference<ZoneServer*> ZoneTest::zoneServer protected
Definition at line 19 of file ZoneTest.cpp.
Referenced by SetUp().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/tests/ZoneTest.cpp