Core3: CityDecorationTask Class Reference
CityDecorationTask Class Reference
#include <CityDecorationTask.h>
Public Member Functions
CityDecorationTask (CreatureObject *creature, SceneObject *object, byte function)
void run ()
void placeDecoration ()
void removeDecoration ()
Static Public Attributes
static const byte PLACE = 0
static const byte REMOVE = 1
Private Attributes
ManagedReference
< CreatureObject * > mayor
ManagedReference< SceneObject * > obj
byte option
Detailed Description
Definition at line 17 of file CityDecorationTask.h.
Constructor & Destructor Documentation
CityDecorationTask::CityDecorationTask (CreatureObject * creature, SceneObject * object, byte function) inline
Definition at line 26 of file CityDecorationTask.h.
References mayor, obj, and option.
Member Function Documentation
void CityDecorationTask::placeDecoration () inline
Definition at line 45 of file CityDecorationTask.h.
References server::zone::managers::city::CityManager::canSupportMoreDecorations(), server::zone::managers::planet::PlanetManager::findObjectTooCloseToDecoration(), server::zone::Zone::getPlanetManager(), mayor, obj, server::chat::StringIdChatParameter::setDI(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTO(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by run().
void CityDecorationTask::removeDecoration () inline
Definition at line 113 of file CityDecorationTask.h.
References mayor, and obj.
Referenced by run().
void CityDecorationTask::run () inline
Definition at line 32 of file CityDecorationTask.h.
References option, placeDecoration(), and removeDecoration().
Member Data Documentation
ManagedReference<CreatureObject*> CityDecorationTask::mayor private
Definition at line 18 of file CityDecorationTask.h.
Referenced by CityDecorationTask(), placeDecoration(), and removeDecoration().
ManagedReference<SceneObject*> CityDecorationTask::obj private
Definition at line 19 of file CityDecorationTask.h.
Referenced by CityDecorationTask(), placeDecoration(), and removeDecoration().
byte CityDecorationTask::option private
Definition at line 20 of file CityDecorationTask.h.
Referenced by CityDecorationTask(), and run().
const byte CityDecorationTask::PLACE = 0 static
Definition at line 23 of file CityDecorationTask.h.
Referenced by CityDecorationMenuComponent::handleObjectMenuSelect().
const byte CityDecorationTask::REMOVE = 1 static
Definition at line 24 of file CityDecorationTask.h.
Referenced by CityDecorationMenuComponent::handleObjectMenuSelect().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/city/CityDecorationTask.h