Core3: RangedIntCustomizationVariables Class Reference
RangedIntCustomizationVariables Class Reference
#include <RangedIntCustomizationVariables.h>
Public Member Functions
RangedIntCustomizationVariables ()
~RangedIntCustomizationVariables ()
String toString ()
void toString (String &str)
bool parse (Chunk *source)
void parseType1 (IffStream *source)
Public Member Functions inherited from Param
Param ()
virtual ~Param ()
virtual bool parse (engine::util::Chunk *source)=0
uint32 getType ()
void setType (uint32 tp)
bool isBool ()
bool isFloat ()
bool isInteger ()
bool isString ()
bool isStringId ()
Protected Attributes
Vector
< RangedIntCustomizationVariable * > variables
Additional Inherited Members
Static Public Attributes inherited from Param
static const uint32 BOOL = 0x01
static const uint32 FLOAT = 0x02
static const uint32 INTEGER = 0x04
static const uint32 STRING = 0x08
static const uint32 STRINGID = 0x10
static const uint32 VECTOR = 0x12
static const uint32 DYNAMICVARIABLE = 0x014
static const uint32 TRIGGERVOLUME = 0x16
static const uint32 PALETTECOLORCUSTOMIZATION = 0x18
static const uint32 RANGEDINTCUSTOMIZATIONVARIABLE = 0x20
static const uint32 CUSTOMIZATIONVARIABLEMAP = 0x22
Detailed Description
Definition at line 15 of file RangedIntCustomizationVariables.h.
Constructor & Destructor Documentation
RangedIntCustomizationVariables::RangedIntCustomizationVariables () inline
Definition at line 22 of file RangedIntCustomizationVariables.h.
RangedIntCustomizationVariables::~RangedIntCustomizationVariables () inline
Definition at line 25 of file RangedIntCustomizationVariables.h.
References variables.
Member Function Documentation
bool RangedIntCustomizationVariables::parse (Chunk * source)
Definition at line 11 of file RangedIntCustomizationVariables.cpp.
References parseType1(), and variables.
Referenced by SharedTangibleObjectTemplate::parseVariableData().
void RangedIntCustomizationVariables::parseType1 (IffStream * source)
Definition at line 66 of file RangedIntCustomizationVariables.cpp.
References RangedIntCustomizationVariable::parse(), Param::type, and variables.
Referenced by parse().
String RangedIntCustomizationVariables::toString () virtual
Implements Param.
Definition at line 93 of file RangedIntCustomizationVariables.cpp.
References variables.
void RangedIntCustomizationVariables::toString (String & str) inline
Definition at line 39 of file RangedIntCustomizationVariables.h.
Member Data Documentation
Vector<RangedIntCustomizationVariable*> RangedIntCustomizationVariables::variables protected
Definition at line 18 of file RangedIntCustomizationVariables.h.
Referenced by parse(), parseType1(), toString(), and ~RangedIntCustomizationVariables().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/params/RangedIntCustomizationVariables.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/params/RangedIntCustomizationVariables.cpp