Core3: MeditateTask Class Reference
MeditateTask Class Reference
#include <MeditateTask.h>
Public Member Functions
MeditateTask (CreatureObject *pl)
void setMoodString (const String &ms)
String getMoodString ()
void run ()
Private Attributes
ManagedReference
< CreatureObject * > player
String moodString
Detailed Description
Definition at line 62 of file MeditateTask.h.
Constructor & Destructor Documentation
MeditateTask::MeditateTask (CreatureObject * pl) inline
Definition at line 67 of file MeditateTask.h.
References player.
Member Function Documentation
String MeditateTask::getMoodString () inline
Definition at line 75 of file MeditateTask.h.
References moodString.
void MeditateTask::run () inline
Definition at line 79 of file MeditateTask.h.
References CreatureState::BLEEDING, CreatureState::DISEASED, CreatureAttribute::getName(), player, CreatureState::POISONED, server::chat::StringIdChatParameter::setDI(), server::zone::objects::scene::variables::StringId::setStringId(), and server::chat::StringIdChatParameter::setTO().
void MeditateTask::setMoodString (const String & ms) inline
Definition at line 71 of file MeditateTask.h.
References moodString.
Member Data Documentation
String MeditateTask::moodString private
Definition at line 64 of file MeditateTask.h.
Referenced by getMoodString(), and setMoodString().
ManagedReference<CreatureObject*> MeditateTask::player private
Definition at line 63 of file MeditateTask.h.
Referenced by MeditateTask(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/events/MeditateTask.h