Core3: DraftSlot Class Reference
DraftSlot Class Reference
#include <DraftSlot.h>
Public Member Functions
DraftSlot ()
~DraftSlot ()
void insertToMessage (BaseMessage *msg)
float getContribution () const
uint32 getQuantity () const
String getResourceType () const
int getSlotType () const
StringId getStringId () const
void setContribution (float contribution)
void setQuantity (uint32 quantity)
void setResourceType (String resourceType)
void setSlotType (int slotType)
void setStringId (String file, String name)
Static Public Attributes
static const int RESOURCESLOT = 0
static const int IDENTICALSLOT = 1
static const int MIXEDSLOT = 2
static const int OPTIONALIDENTICALSLOT = 3
static const int OPTIONALMIXEDSLOT = 4
Private Attributes
StringId stringId
String resourceType
uint32 quantity
int slotType
float contribution
Detailed Description
Definition at line 51 of file DraftSlot.h.
Constructor & Destructor Documentation
DraftSlot::DraftSlot () inline
Definition at line 76 of file DraftSlot.h.
DraftSlot::~DraftSlot () inline
Definition at line 80 of file DraftSlot.h.
Member Function Documentation
float DraftSlot::getContribution () const inline
Definition at line 116 of file DraftSlot.h.
References contribution.
uint32 DraftSlot::getQuantity () const inline
Definition at line 121 of file DraftSlot.h.
References quantity.
String DraftSlot::getResourceType () const inline
Definition at line 126 of file DraftSlot.h.
References resourceType.
Referenced by server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus().
int DraftSlot::getSlotType () const inline
Definition at line 131 of file DraftSlot.h.
References slotType.
StringId DraftSlot::getStringId () const inline
Definition at line 136 of file DraftSlot.h.
References stringId.
void DraftSlot::insertToMessage (BaseMessage * msg) inline
Definition at line 84 of file DraftSlot.h.
References server::zone::objects::scene::variables::StringId::getFile(), server::zone::objects::scene::variables::StringId::getStringID(), IDENTICALSLOT, MIXEDSLOT, OPTIONALIDENTICALSLOT, OPTIONALMIXEDSLOT, quantity, RESOURCESLOT, resourceType, slotType, and stringId.
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::sendIngredientForUIListen().
void DraftSlot::setContribution (float contribution) inline
Definition at line 141 of file DraftSlot.h.
Referenced by DraftSchematicObjectTemplate::readObject().
void DraftSlot::setQuantity (uint32 quantity) inline
Definition at line 146 of file DraftSlot.h.
References quantity.
Referenced by DraftSchematicObjectTemplate::readObject().
void DraftSlot::setResourceType (String resourceType) inline
Definition at line 151 of file DraftSlot.h.
References resourceType.
Referenced by DraftSchematicObjectTemplate::readObject().
void DraftSlot::setSlotType (int slotType) inline
Definition at line 156 of file DraftSlot.h.
References slotType.
Referenced by DraftSchematicObjectTemplate::readObject().
void DraftSlot::setStringId (String file, String name) inline
Definition at line 161 of file DraftSlot.h.
References server::zone::objects::scene::variables::StringId::setStringId(), and stringId.
Referenced by DraftSchematicObjectTemplate::readObject().
Member Data Documentation
float DraftSlot::contribution private
Definition at line 66 of file DraftSlot.h.
Referenced by getContribution().
const int DraftSlot::IDENTICALSLOT = 1 static
Definition at line 70 of file DraftSlot.h.
Referenced by insertToMessage().
const int DraftSlot::MIXEDSLOT = 2 static
Definition at line 71 of file DraftSlot.h.
Referenced by insertToMessage().
const int DraftSlot::OPTIONALIDENTICALSLOT = 3 static
Definition at line 72 of file DraftSlot.h.
Referenced by insertToMessage().
const int DraftSlot::OPTIONALMIXEDSLOT = 4 static
Definition at line 73 of file DraftSlot.h.
Referenced by insertToMessage().
uint32 DraftSlot::quantity private
Definition at line 60 of file DraftSlot.h.
Referenced by getQuantity(), insertToMessage(), and setQuantity().
const int DraftSlot::RESOURCESLOT = 0 static
Definition at line 69 of file DraftSlot.h.
Referenced by insertToMessage().
String DraftSlot::resourceType private
Definition at line 57 of file DraftSlot.h.
Referenced by getResourceType(), insertToMessage(), and setResourceType().
int DraftSlot::slotType private
Definition at line 63 of file DraftSlot.h.
Referenced by getSlotType(), insertToMessage(), and setSlotType().
StringId DraftSlot::stringId private
Definition at line 54 of file DraftSlot.h.
Referenced by getStringId(), insertToMessage(), and setStringId().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/draftschematic/draftslot/DraftSlot.h