Core3: server::zone::objects::mission::bountyhunter::BountyHunterDroid Class Reference
server::zone::objects::mission::bountyhunter::BountyHunterDroid Class Reference
#include <BountyHunterDroid.h>
Public Member Functions
BountyHunterDroid ()
Reference< Task * > performAction (int action, SceneObject *droidObject, CreatureObject *player, MissionObject *mission)
Static Public Attributes
static const int CALLDROID = 0
static const int TRANSMITBIOLOGICALSIGNATURE = 1
static const int FINDTARGET = 2
static const int FINDANDTRACKTARGET = 3
Private Member Functions
Reference< FindTargetTask * > findTarget (SceneObject *sceneObject, CreatureObject *player, MissionObject *mission, bool track)
Reference< CallArakydTask * > callArakydDroid (SceneObject *droidObject, CreatureObject *player, MissionObject *mission)
Reference< FindTargetTask * > transmitBiologicalSignature (SceneObject *sceneObject, CreatureObject *player, MissionObject *mission)
Detailed Description
Class implementing the functionality of the bounty hunter droids.
Definition at line 28 of file BountyHunterDroid.h.
Constructor & Destructor Documentation
server::zone::objects::mission::bountyhunter::BountyHunterDroid::BountyHunterDroid () inline
Definition at line 36 of file BountyHunterDroid.h.
Member Function Documentation
Reference< CallArakydTask * > BountyHunterDroid::callArakydDroid (SceneObject * droidObject, CreatureObject * player, MissionObject * mission) private
Definition at line 81 of file BountyHunterDroid.cpp.
References server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::getActiveAreas(), server::zone::objects::mission::MissionObject::getMissionLevel(), server::zone::objects::mission::MissionObject::getMissionObjective(), server::zone::objects::tangible::TangibleObject::getUseCount(), server::zone::objects::mission::BountyMissionObjective::INITSTATUS, server::zone::objects::creature::CreatureObject::isRidingCreature(), server::zone::objects::creature::CreatureObject::isRidingMount(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::objects::tangible::TangibleObject::setUseCount().
Referenced by performAction().
Reference< FindTargetTask * > BountyHunterDroid::findTarget (SceneObject * sceneObject, CreatureObject * player, MissionObject * mission, bool track) private
Definition at line 45 of file BountyHunterDroid.cpp.
References server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::Zone::getCreatureManager(), server::zone::objects::mission::MissionObject::getMissionLevel(), server::zone::objects::mission::MissionObject::getMissionObjective(), server::zone::objects::tangible::TangibleObject::getUseCount(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::mission::BountyMissionObjective::INITSTATUS, server::zone::objects::creature::CreatureObject::isRidingCreature(), server::zone::objects::creature::CreatureObject::isRidingMount(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::tangible::TangibleObject::setUseCount(), and server::zone::managers::creature::CreatureManager::spawnCreature().
Referenced by performAction().
Reference< Task * > BountyHunterDroid::performAction (int action, SceneObject * droidObject, CreatureObject * player, MissionObject * mission)
Definition at line 14 of file BountyHunterDroid.cpp.
References callArakydDroid(), CALLDROID, FINDANDTRACKTARGET, FINDTARGET, findTarget(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), TRANSMITBIOLOGICALSIGNATURE, and transmitBiologicalSignature().
Reference< FindTargetTask * > BountyHunterDroid::transmitBiologicalSignature (SceneObject * sceneObject, CreatureObject * player, MissionObject * mission) private
Definition at line 138 of file BountyHunterDroid.cpp.
References server::zone::objects::mission::MissionObject::getMissionLevel(), server::zone::objects::mission::MissionObject::getMissionObjective(), server::zone::objects::mission::BountyMissionObjective::INITSTATUS, server::zone::objects::creature::CreatureObject::isRidingCreature(), server::zone::objects::creature::CreatureObject::isRidingMount(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by performAction().
Member Data Documentation
const int server::zone::objects::mission::bountyhunter::BountyHunterDroid::CALLDROID = 0 static
Definition at line 31 of file BountyHunterDroid.h.
Referenced by performAction().
const int server::zone::objects::mission::bountyhunter::BountyHunterDroid::FINDANDTRACKTARGET = 3 static
Definition at line 34 of file BountyHunterDroid.h.
Referenced by performAction().
const int server::zone::objects::mission::bountyhunter::BountyHunterDroid::FINDTARGET = 2 static
Definition at line 33 of file BountyHunterDroid.h.
Referenced by performAction().
const int server::zone::objects::mission::bountyhunter::BountyHunterDroid::TRANSMITBIOLOGICALSIGNATURE = 1 static
Definition at line 32 of file BountyHunterDroid.h.
Referenced by performAction().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/bountyhunter/BountyHunterDroid.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/bountyhunter/BountyHunterDroid.cpp