Core3: PlanetTravelPointListResponse Class Reference
PlanetTravelPointListResponse Class Reference
#include <PlanetTravelPointListResponse.h>
Public Member Functions
PlanetTravelPointListResponse ()
PlanetTravelPointListResponse (const String &planet)
~PlanetTravelPointListResponse ()
void addPoint (const String &name, float x, float z, float y, uint32 tax, uint8 starport)
void generateMessage ()
void insertNames ()
void insertCoords ()
void insertTax ()
void insertStarport ()
Private Attributes
Vector< TravelPoint * > travelPoints
Detailed Description
Definition at line 75 of file PlanetTravelPointListResponse.h.
Constructor & Destructor Documentation
PlanetTravelPointListResponse::PlanetTravelPointListResponse () inline
Definition at line 79 of file PlanetTravelPointListResponse.h.
PlanetTravelPointListResponse::PlanetTravelPointListResponse (const String & planet) inline
Definition at line 86 of file PlanetTravelPointListResponse.h.
PlanetTravelPointListResponse::~PlanetTravelPointListResponse () inline
Definition at line 94 of file PlanetTravelPointListResponse.h.
References travelPoints.
Member Function Documentation
void PlanetTravelPointListResponse::addPoint (const String & name, float x, float z, float y, uint32 tax, uint8 starport) inline
Definition at line 102 of file PlanetTravelPointListResponse.h.
References travelPoints.
Referenced by PlanetTravelPointListRequestCallback::run().
void PlanetTravelPointListResponse::generateMessage () inline
Definition at line 106 of file PlanetTravelPointListResponse.h.
References insertCoords(), insertNames(), insertStarport(), and insertTax().
Referenced by PlanetTravelPointListRequestCallback::run().
void PlanetTravelPointListResponse::insertCoords () inline
Definition at line 123 of file PlanetTravelPointListResponse.h.
References TravelPoint::positionX, TravelPoint::positionY, TravelPoint::positionZ, and travelPoints.
Referenced by generateMessage().
void PlanetTravelPointListResponse::insertNames () inline
Definition at line 113 of file PlanetTravelPointListResponse.h.
References TravelPoint::name, and travelPoints.
Referenced by generateMessage().
void PlanetTravelPointListResponse::insertStarport () inline
Definition at line 145 of file PlanetTravelPointListResponse.h.
References TravelPoint::starport, and travelPoints.
Referenced by generateMessage().
void PlanetTravelPointListResponse::insertTax () inline
Definition at line 135 of file PlanetTravelPointListResponse.h.
References TravelPoint::tax, and travelPoints.
Referenced by generateMessage().
Member Data Documentation
Vector<TravelPoint*> PlanetTravelPointListResponse::travelPoints private
Definition at line 76 of file PlanetTravelPointListResponse.h.
Referenced by addPoint(), insertCoords(), insertNames(), insertStarport(), insertTax(), and ~PlanetTravelPointListResponse().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/player/PlanetTravelPointListResponse.h