Core3: server::zone::objects::player::sessions::ConversationSessionImplementation Class Reference
server::zone::objects::player::sessions::ConversationSessionImplementation Class Reference
#include <ConversationSession.h>
Public Member Functions
ConversationSessionImplementation (CreatureObject *conversingCreature)
ConversationSessionImplementation (DummyConstructorParameter *param)
void setLastConversationScreen (ConversationScreen *screen)
ConversationScreen * getLastConversationScreen ()
ManagedWeakReference
< CreatureObject * > getNPC ()
operator const ConversationSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< ConversationSession * > _this
Protected Member Functions
virtual ~ConversationSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
Reference< ConversationScreen * > lastConversationScreen
ManagedWeakReference
< CreatureObject * > npc
Friends
class ConversationSession
Detailed Description
Definition at line 89 of file ConversationSession.h.
Constructor & Destructor Documentation
ConversationSessionImplementation::ConversationSessionImplementation (CreatureObject * conversingCreature)
Definition at line 220 of file ConversationSession.cpp.
References _initializeImplementation(), lastConversationScreen, and npc.
ConversationSessionImplementation::ConversationSessionImplementation (DummyConstructorParameter * param)
Definition at line 82 of file ConversationSession.cpp.
References _initializeImplementation().
ConversationSessionImplementation::~ConversationSessionImplementation () protected virtual
Definition at line 87 of file ConversationSession.cpp.
Member Function Documentation
DistributedObjectStub * ConversationSessionImplementation::_getStub ()
Definition at line 107 of file ConversationSession.cpp.
References _this.
void ConversationSessionImplementation::_initializeImplementation () protected
Definition at line 94 of file ConversationSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ConversationSessionImplementation().
void ConversationSessionImplementation::_serializationHelperMethod () protected
Definition at line 143 of file ConversationSession.cpp.
Referenced by _initializeImplementation(), and server::zone::objects::player::sessions::TrainerConversationSessionImplementation::_serializationHelperMethod().
void ConversationSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 102 of file ConversationSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::TrainerConversationSessionImplementation::_setStub(), and server::zone::objects::player::sessions::ConversationSession::ConversationSession().
void ConversationSessionImplementation::finalize () protected
Definition at line 91 of file ConversationSession.cpp.
ConversationScreen * ConversationSessionImplementation::getLastConversationScreen ()
Definition at line 233 of file ConversationSession.cpp.
References lastConversationScreen.
Referenced by server::zone::objects::player::sessions::ConversationSession::getLastConversationScreen().
ManagedWeakReference< CreatureObject * > ConversationSessionImplementation::getNPC ()
Definition at line 238 of file ConversationSession.cpp.
References npc.
Referenced by server::zone::objects::player::sessions::ConversationSession::getNPC().
void ConversationSessionImplementation::lock (bool doLock = true) protected
Definition at line 115 of file ConversationSession.cpp.
References _this.
void ConversationSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 119 of file ConversationSession.cpp.
References _this.
ConversationSessionImplementation::operator const ConversationSession * ()
Definition at line 111 of file ConversationSession.cpp.
void ConversationSessionImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented in server::zone::objects::player::sessions::TrainerConversationSessionImplementation.
Definition at line 150 of file ConversationSession.cpp.
References readObjectMember().
bool ConversationSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 169 of file ConversationSession.cpp.
References lastConversationScreen, and npc.
Referenced by readObject(), and server::zone::objects::player::sessions::TrainerConversationSessionImplementation::readObjectMember().
void ConversationSessionImplementation::rlock (bool doLock = true) protected
Definition at line 123 of file ConversationSession.cpp.
References _this.
void ConversationSessionImplementation::runlock (bool doLock = true) protected
Definition at line 139 of file ConversationSession.cpp.
References _this.
void ConversationSessionImplementation::setLastConversationScreen (ConversationScreen * screen)
Definition at line 228 of file ConversationSession.cpp.
References lastConversationScreen.
Referenced by server::zone::objects::player::sessions::ConversationSession::setLastConversationScreen().
void ConversationSessionImplementation::unlock (bool doLock = true) protected
Definition at line 135 of file ConversationSession.cpp.
References _this.
void ConversationSessionImplementation::wlock (bool doLock = true) protected
Definition at line 127 of file ConversationSession.cpp.
References _this.
void ConversationSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 131 of file ConversationSession.cpp.
References _this.
void ConversationSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented in server::zone::objects::player::sessions::TrainerConversationSessionImplementation.
Definition at line 187 of file ConversationSession.cpp.
References writeObjectMembers().
int ConversationSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 194 of file ConversationSession.cpp.
References lastConversationScreen, and npc.
Referenced by writeObject(), and server::zone::objects::player::sessions::TrainerConversationSessionImplementation::writeObjectMembers().
Friends And Related Function Documentation
friend class ConversationSession friend
Definition at line 140 of file ConversationSession.h.
Member Data Documentation
WeakReference<ConversationSession*> server::zone::objects::player::sessions::ConversationSessionImplementation::_this
Definition at line 106 of file ConversationSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
Reference<ConversationScreen* > server::zone::objects::player::sessions::ConversationSessionImplementation::lastConversationScreen protected
Definition at line 91 of file ConversationSession.h.
Referenced by ConversationSessionImplementation(), getLastConversationScreen(), readObjectMember(), setLastConversationScreen(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sessions::ConversationSessionImplementation::npc protected
Definition at line 93 of file ConversationSession.h.
Referenced by ConversationSessionImplementation(), getNPC(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ConversationSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ConversationSession.cpp