Core3: server::zone::managers::mission::spawnmaps::PlanetSpawnMap Class Reference
server::zone::managers::mission::spawnmaps::PlanetSpawnMap Class Reference
#include <PlanetSpawnMap.h>
Public Member Functions
PlanetSpawnMap ()
PlanetSpawnMap (const String &planetName)
void readObject (LuaObject *luaObject)
void addCity (Reference< CitySpawnMap * > city)
String getPlanetName ()
CitySpawnMap * getClosestCity (const Vector3 *position)
CitySpawnMap * getRandomCityNotCloseTo (const Vector3 *position)
NpcSpawnPoint * addToClosestCity (Reference< NpcSpawnPoint * > npc, bool checkDistanceToOtherSpawnPoints)
NpcSpawnPoint * findSpawnAt (Vector3 *position)
bool parseFromBinaryStream (ObjectInputStream *stream)
bool toBinaryStream (ObjectOutputStream *stream)
void saveSpawnPoints (std::ofstream &file)
Protected Member Functions
int getClosestCityNumber (const Vector3 *position)
Protected Attributes
Vector< Reference
< CitySpawnMap * > > citySpawnMaps
String planetName
Detailed Description
Container for all cities on a planet and their mission NPC spawn points.
Definition at line 60 of file PlanetSpawnMap.h.
Constructor & Destructor Documentation
server::zone::managers::mission::spawnmaps::PlanetSpawnMap::PlanetSpawnMap () inline
Default constructor.
Definition at line 95 of file PlanetSpawnMap.h.
server::zone::managers::mission::spawnmaps::PlanetSpawnMap::PlanetSpawnMap (const String & planetName) inline
Constructor.
Parameters
planetName the name of the planet.
Definition at line 101 of file PlanetSpawnMap.h.
References planetName.
Member Function Documentation
void server::zone::managers::mission::spawnmaps::PlanetSpawnMap::addCity (Reference< CitySpawnMap * > city) inline
Adds a city on the planet.
Parameters
city the city to add.
Definition at line 134 of file PlanetSpawnMap.h.
References citySpawnMaps.
NpcSpawnPoint* server::zone::managers::mission::spawnmaps::PlanetSpawnMap::addToClosestCity (Reference< NpcSpawnPoint * > npc, bool checkDistanceToOtherSpawnPoints) inline
Add a NPC to the closest city.
Parameters
npc the NPC to add.
checkDistanceToOtherSpawnPoints if true the distance to all other spawn points in the city is checked and the new spawn point is only added if it is at least a certain distance from all other spawn points.
Returns
the added npc spawn point or the nearest existing spawn point if the supplied spawn point is to close.
Definition at line 191 of file PlanetSpawnMap.h.
References citySpawnMaps, getClosestCityNumber(), and server::zone::managers::mission::spawnmaps::NpcSpawnPoint::getPosition().
Referenced by server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::addSpawnPoint(), and readObject().
NpcSpawnPoint* server::zone::managers::mission::spawnmaps::PlanetSpawnMap::findSpawnAt (Vector3 * position) inline
Finds a spawn point on a certain location.
Parameters
position the position to search.
Returns
the spawn point on the position or NULL if none exist.
Definition at line 212 of file PlanetSpawnMap.h.
References citySpawnMaps, and getClosestCityNumber().
Referenced by server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::findSpawnAt().
CitySpawnMap* server::zone::managers::mission::spawnmaps::PlanetSpawnMap::getClosestCity (const Vector3 * position) inline
Finds the city closest to the supplied position on the planet.
Parameters
position the position to search from.
Returns
closest city or NULL if no city is available on the planet.
Definition at line 151 of file PlanetSpawnMap.h.
References citySpawnMaps, and getClosestCityNumber().
Referenced by server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::getRandomNpcSpawnPoint().
int server::zone::managers::mission::spawnmaps::PlanetSpawnMap::getClosestCityNumber (const Vector3 * position) inline protected
Finds the city number closest to the supplied position on the planet.
Parameters
position the position to search from.
Returns
closest city number or -1 if none is found.
Definition at line 77 of file PlanetSpawnMap.h.
References citySpawnMaps.
Referenced by addToClosestCity(), findSpawnAt(), getClosestCity(), and getRandomCityNotCloseTo().
String server::zone::managers::mission::spawnmaps::PlanetSpawnMap::getPlanetName () inline
Get the planet name.
Returns
planet name.
Definition at line 142 of file PlanetSpawnMap.h.
References planetName.
CitySpawnMap* server::zone::managers::mission::spawnmaps::PlanetSpawnMap::getRandomCityNotCloseTo (const Vector3 * position) inline
Definition at line 161 of file PlanetSpawnMap.h.
References citySpawnMaps, and getClosestCityNumber().
Referenced by server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::getRandomCityCoordinates().
bool server::zone::managers::mission::spawnmaps::PlanetSpawnMap::parseFromBinaryStream (ObjectInputStream * stream) inline
Load the object from a stream.
Parameters
stream the stream to load the object from.
Returns
true if successful.
Definition at line 226 of file PlanetSpawnMap.h.
References citySpawnMaps, and planetName.
void server::zone::managers::mission::spawnmaps::PlanetSpawnMap::readObject (LuaObject * luaObject) inline
Loads the object from a LuaObject.
Parameters
luaObject object to load from.
Definition at line 109 of file PlanetSpawnMap.h.
References addToClosestCity(), and planetName.
void server::zone::managers::mission::spawnmaps::PlanetSpawnMap::saveSpawnPoints (std::ofstream & file) inline
Saves the spawn points to a file.
Parameters
file the file stream to save the spawn points to.
Definition at line 245 of file PlanetSpawnMap.h.
References citySpawnMaps, and planetName.
bool server::zone::managers::mission::spawnmaps::PlanetSpawnMap::toBinaryStream (ObjectOutputStream * stream) inline
Write the object to a stream.
Parameters
stream the stream to write the object to.
Returns
true if successful.
Definition at line 236 of file PlanetSpawnMap.h.
References citySpawnMaps, and planetName.
Member Data Documentation
Vector<Reference<CitySpawnMap*> > server::zone::managers::mission::spawnmaps::PlanetSpawnMap::citySpawnMaps protected
Vector of cities.
Definition at line 65 of file PlanetSpawnMap.h.
Referenced by addCity(), addToClosestCity(), findSpawnAt(), getClosestCity(), getClosestCityNumber(), getRandomCityNotCloseTo(), parseFromBinaryStream(), saveSpawnPoints(), and toBinaryStream().
String server::zone::managers::mission::spawnmaps::PlanetSpawnMap::planetName protected
Name of the planet.
Definition at line 70 of file PlanetSpawnMap.h.
Referenced by getPlanetName(), parseFromBinaryStream(), PlanetSpawnMap(), readObject(), saveSpawnPoints(), and toBinaryStream().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/mission/spawnmaps/PlanetSpawnMap.h