Core3: WearablesDeltaVector Class Reference
WearablesDeltaVector Class Reference
#include <WearablesDeltaVector.h>
Public Member Functions
WearablesDeltaVector ()
void insertItemToMessage (ManagedReference< TangibleObject * > *item, BaseMessage *msg)
bool add (ManagedReference< TangibleObject * > element, DeltaMessage *message=NULL, int updates=1)
bool remove (int index, DeltaMessage *message=NULL, int updates=1)
Vector< ManagedReference
< ArmorObject * > > getArmorAtHitLocation (uint8 hl)
void addArmor (uint8 hitLocation, ManagedReference< ArmorObject * > armor)
void removeArmor (uint8 hitLocation, ManagedReference< ArmorObject * > armor)
Public Member Functions inherited from server::zone::objects::scene::variables::DeltaVector< ManagedReference< TangibleObject * > >
DeltaVector ()
DeltaVector (int initsize, int incr)
DeltaVector (const DeltaVector &v)
~DeltaVector ()
DeltaVector & operator= (const DeltaVector &v)
void addSerializableVariables ()
virtual ManagedReference
< TangibleObject * > set (int idx, const ManagedReference< TangibleObject * > &newValue, DeltaMessage *message=NULL, int updates=1)
virtual bool add (const ManagedReference< TangibleObject * > &element, DeltaMessage *message=NULL, int updates=1)
ManagedReference
< TangibleObject * > & get (int index) const
ManagedReference
< TangibleObject * > & getSafe (int index)
ManagedReference
< TangibleObject * > remove (int index, DeltaMessage *message=NULL, int updates=1)
void removeAll (DeltaMessage *message=NULL)
virtual void insertToMessage (BaseMessage *msg)
virtual void insertItemToMessage (ManagedReference< TangibleObject * > *item, BaseMessage *msg)
virtual bool contains (const ManagedReference< TangibleObject * > &element)
int find (const ManagedReference< TangibleObject * > &element)
uint32 getUpdateCounter ()
uint32 getNewUpdateCounter (int increment)
void setUpdateCounter (int count)
void resetUpdateCounter ()
int size ()
ReadWriteLock * getLock ()
Protected Attributes
VectorMap< uint8, Vector
< ManagedReference
< ArmorObject * > > > protectionArmorMap
Protected Attributes inherited from server::zone::objects::scene::variables::DeltaVector< ManagedReference< TangibleObject * > >
Vector< ManagedReference
< TangibleObject * > > vector
uint32 updateCounter
ReadWriteLock * mutex
Detailed Description
Definition at line 17 of file WearablesDeltaVector.h.
Constructor & Destructor Documentation
WearablesDeltaVector::WearablesDeltaVector () inline
Definition at line 22 of file WearablesDeltaVector.h.
References protectionArmorMap.
Member Function Documentation
bool WearablesDeltaVector::add (ManagedReference< TangibleObject * > element, DeltaMessage * message = NULL, int updates = 1) inline
Definition at line 40 of file WearablesDeltaVector.h.
References addArmor().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::addWearableObject().
void WearablesDeltaVector::addArmor (uint8 hitLocation, ManagedReference< ArmorObject * > armor) inline
Definition at line 88 of file WearablesDeltaVector.h.
References protectionArmorMap.
Referenced by add().
Vector<ManagedReference<ArmorObject*> > WearablesDeltaVector::getArmorAtHitLocation (uint8 hl) inline
Definition at line 84 of file WearablesDeltaVector.h.
References protectionArmorMap.
Referenced by CombatManager::getActionArmor(), CombatManager::getHealthArmor(), and CombatManager::getMindArmor().
void WearablesDeltaVector::insertItemToMessage (ManagedReference< TangibleObject * > * item, BaseMessage * msg) inline
Definition at line 28 of file WearablesDeltaVector.h.
References server::zone::objects::scene::SceneObject::getClientObjectCRC(), server::zone::objects::scene::SceneObject::getContainmentType(), server::zone::objects::tangible::TangibleObject::getCustomizationString(), and server::zone::objects::scene::SceneObject::getObjectID().
bool WearablesDeltaVector::remove (int index, DeltaMessage * message = NULL, int updates = 1) inline
Definition at line 61 of file WearablesDeltaVector.h.
References removeArmor().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::removeWearableObject().
void WearablesDeltaVector::removeArmor (uint8 hitLocation, ManagedReference< ArmorObject * > armor) inline
Definition at line 96 of file WearablesDeltaVector.h.
References protectionArmorMap.
Referenced by remove().
Member Data Documentation
VectorMap<uint8, Vector<ManagedReference<ArmorObject*> > > WearablesDeltaVector::protectionArmorMap protected
Definition at line 19 of file WearablesDeltaVector.h.
Referenced by addArmor(), getArmorAtHitLocation(), removeArmor(), and WearablesDeltaVector().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/variables/WearablesDeltaVector.h