Core3: CityVotingMenuComponent Class Reference
CityVotingMenuComponent Class Reference
#include <CityVotingMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file CityVotingMenuComponent.h.
Member Function Documentation
void CityVotingMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from ObjectMenuComponent.
Definition at line 14 of file CityVotingMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID(), server::zone::objects::scene::SceneObject::getCityRegion(), and server::zone::objects::scene::SceneObject::getObjectID().
int CityVotingMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from ObjectMenuComponent.
Definition at line 32 of file CityVotingMenuComponent.cpp.
References server::zone::ZoneServer::getCityManager(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::managers::city::CityManager::promptMayoralVote(), server::zone::managers::city::CityManager::registerForMayoralRace(), and server::zone::managers::city::CityManager::sendMayoralStandings().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/region/components/CityVotingMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/region/components/CityVotingMenuComponent.cpp