Core3: InstallationObjectMenuComponent Class Reference
InstallationObjectMenuComponent Class Reference
#include <InstallationObjectMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *creature)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *creature, byte selectedID)
Detailed Description
Definition at line 14 of file InstallationObjectMenuComponent.h.
Member Function Documentation
void InstallationObjectMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from ObjectMenuComponent.
Reimplemented in FactoryObjectMenuComponent.
Definition at line 18 of file InstallationObjectMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID(), server::zone::objects::installation::InstallationObject::isGeneratorObject(), server::zone::objects::scene::SceneObject::isInstallationObject(), and server::zone::objects::structure::StructureObject::isOnAdminList().
Referenced by FactoryObjectMenuComponent::fillObjectMenuResponse().
int InstallationObjectMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from ObjectMenuComponent.
Reimplemented in FactoryObjectMenuComponent.
Definition at line 43 of file InstallationObjectMenuComponent.cpp.
References server::zone::objects::creature::CreatureObject::executeObjectControllerAction(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::installation::InstallationObject::handleStructureAddEnergy(), server::zone::objects::installation::InstallationObject::isGeneratorObject(), server::zone::objects::scene::SceneObject::isInstallationObject(), server::zone::objects::structure::StructureObject::isOnAdminList(), StructureManager::promptNameStructure(), and server::zone::objects::structure::StructureObject::sendPermissionListTo().
Referenced by FactoryObjectMenuComponent::handleObjectMenuSelect().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/InstallationObjectMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/InstallationObjectMenuComponent.cpp