Core3: server::zone::managers::player::PlayerManager Class Reference
server::zone::managers::player::PlayerManager Class Reference
#include <PlayerManager.h>
Public Member Functions
PlayerManager (ZoneServer *zoneServer, ZoneProcessServer *impl)
void loadNameMap ()
int getHighestBadgeIndex ()
void sendStartingLocationsTo (CreatureObject *player)
StartingLocation * getStartingLocation (const String &city)
bool kickUser (const String &name, const String &admin, String &reason, bool doBan=true)
bool createPlayer (MessageCallback *callback)
bool checkPlayerName (MessageCallback *callback)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
int notifyDestruction (TangibleObject *destructor, TangibleObject *destructedObject, int condition)
bool shouldRescheduleCorpseDestruction (CreatureObject *player, CreatureObject *ai)
void rescheduleCorpseDestruction (CreatureObject *player, CreatureObject *ai)
bool canGroupMemberHarvestCorpse (CreatureObject *player, Creature *creature)
void killPlayer (TangibleObject *attacker, CreatureObject *player, int typeofdeath=0)
byte calculateIncapacitationTimer (CreatureObject *player, int condition)
bool checkEncumbrancies (CreatureObject *player, ArmorObject *armor)
void applyEncumbrancies (CreatureObject *player, ArmorObject *armor)
void removeEncumbrancies (CreatureObject *player, ArmorObject *armor)
void awardBadge (PlayerObject *ghost, unsigned int badge)
void setExperienceMultiplier (float globalMultiplier)
void awardExperience (CreatureObject *player, const String &xpType, int amount, bool sendSystemMessage=true, float localMultiplier=1.0f)
SortedVector< ManagedReference
< SceneObject * > > getInsurableItems (CreatureObject *player, bool onlyInsurable=true)
void addInsurableItemsRecursive (SceneObject *obj, SortedVector< ManagedReference< SceneObject * > > *items, bool onlyInsurable)
void handleAbortTradeMessage (CreatureObject *player)
void handleAddItemToTradeWindow (CreatureObject *player, unsigned long long itemID)
void handleGiveMoneyMessage (CreatureObject *player, unsigned int value)
void handleAcceptTransactionMessage (CreatureObject *player)
void handleUnAcceptTransactionMessage (CreatureObject *player)
void handleVerifyTradeMessage (CreatureObject *player)
bool checkTradeItems (CreatureObject *player, CreatureObject *receiver)
SceneObject * getInRangeStructureWithAdminRights (CreatureObject *creature, unsigned long long targetID=0)
StructureObject * getInRangeOwnedStructure (CreatureObject *creature, float range=128)
void sendBattleFatigueMessage (CreatureObject *player, CreatureObject *target)
void stopWatch (CreatureObject *creature, unsigned long long entid, bool doSendPackets=true, bool forced=false, bool doLock=true, bool outOfRange=false)
void stopListen (CreatureObject *creature, unsigned long long entid, bool doSendPackets=true, bool forced=false, bool doLock=true, bool outOfRange=false)
void startWatch (CreatureObject *creature, unsigned long long entid)
void startListen (CreatureObject *creature, unsigned long long entid)
void lootAll (CreatureObject *player, CreatureObject *creature)
int healEnhance (CreatureObject *enhancer, CreatureObject *patient, byte attribute, int buffvalue, float duration)
void disseminateExperience (TangibleObject *destructedObject, ThreatMap *threatMap)
int calculatePlayerLevel (CreatureObject *player)
void sendLoginMessage (CreatureObject *player)
void resendLoginMessageToAll ()
void sendActivateCloneRequest (CreatureObject *player, int typeofdeath=0)
void sendPlayerToCloner (CreatureObject *player, unsigned long long clonerID, int typeofdeath=0)
void ejectPlayerFromBuilding (CreatureObject *player)
bool checkExistentNameInDatabase (const String &firstName)
Reference< TangibleObject * > createHairObject (const String &hairObjectFile, const String &hairCustomization)
void createTutorialBuilding (CreatureObject *player)
void createSkippedTutorialBuilding (CreatureObject *player)
void updateSwimmingState (CreatureObject *player, float newZ, IntersectionResults *intersections=NULL, CloseObjectsVector *closeObjects=NULL)
int checkSpeedHackFirstTest (CreatureObject *player, float parsedSpeed, ValidatedPosition &teleportPosition, float errorMultiplier=1)
int checkSpeedHackSecondTest (CreatureObject *player, float newX, float newZ, float newY, unsigned int newStamp, SceneObject *newParent=NULL)
bool existsName (const String &name)
unsigned long long getObjectID (const String &name)
Reference< CreatureObject * > getPlayer (const String &name)
void updatePermissionLevel (CreatureObject *player, int adminLevel=1)
void updatePermissionName (CreatureObject *player, int adminLevel)
void addPlayer (CreatureObject *player)
void removePlayer (String &playerName)
String getBadgeKey (int idx)
CraftingStation * getNearbyCraftingStation (CreatureObject *player, int type)
void finishHologrind (CreatureObject *player)
Account * getAccount (const String &username)
Account * getAccount (unsigned int accountID)
String banAccount (PlayerObject *admin, Account *account, unsigned int seconds, const String &reason)
String unbanAccount (PlayerObject *admin, Account *account, const String &reason)
String banFromGalaxy (PlayerObject *admin, Account *account, unsigned const int galaxy, unsigned int seconds, const String &reason)
String unbanFromGalaxy (PlayerObject *admin, Account *account, unsigned const int galaxy, const String &reason)
String banCharacter (PlayerObject *admin, Account *account, const String &name, unsigned int galaxyID, unsigned int seconds, const String &reason)
String unbanCharacter (PlayerObject *admin, Account *account, const String &name, unsigned int galaxyID, const String &reason)
bool promptTeachableSkills (CreatureObject *teacher, SceneObject *target)
void decreaseOnlineCharCount (ZoneClientSession *client)
bool increaseOnlineCharCountIfPossible (ZoneClientSession *client)
void fixHAM (CreatureObject *player)
bool offerTeaching (CreatureObject *teacher, CreatureObject *student, Skill *skill)
bool acceptTeachingOffer (CreatureObject *teacher, CreatureObject *student, Skill *skill)
SortedVector< String > getTeachableSkills (CreatureObject *teacher, CreatureObject *student)
OnlineZoneClientMap * getOnlineZoneClientMap ()
void getCleanupCharacterCount ()
void cleanupCharacters ()
bool shouldDeleteCharacter (unsigned long long characterID, int galaxyID)
void enhanceCharacter (CreatureObject *player)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
PlayerManager (DummyConstructorParameter *param)
virtual ~PlayerManager ()
Friends
class PlayerManagerHelper
Detailed Description
Definition at line 281 of file PlayerManager.h.
Constructor & Destructor Documentation
PlayerManager::PlayerManager (ZoneServer * zoneServer, ZoneProcessServer * impl)
Definition at line 45 of file PlayerManager.cpp.
References server::zone::managers::player::PlayerManagerImplementation::_setStub().
PlayerManager::PlayerManager (DummyConstructorParameter * param) protected
Definition at line 52 of file PlayerManager.cpp.
PlayerManager::~PlayerManager () protected virtual
Definition at line 56 of file PlayerManager.cpp.
Member Function Documentation
DistributedObjectServant * PlayerManager::_getImplementation ()
Definition at line 1233 of file PlayerManager.cpp.
Referenced by acceptTeachingOffer(), addInsurableItemsRecursive(), addPlayer(), applyEncumbrancies(), awardBadge(), awardExperience(), banAccount(), banCharacter(), banFromGalaxy(), calculateIncapacitationTimer(), calculatePlayerLevel(), canGroupMemberHarvestCorpse(), checkEncumbrancies(), checkExistentNameInDatabase(), checkPlayerName(), checkSpeedHackFirstTest(), checkSpeedHackSecondTest(), checkTradeItems(), cleanupCharacters(), createHairObject(), createPlayer(), createSkippedTutorialBuilding(), createTutorialBuilding(), decreaseOnlineCharCount(), disseminateExperience(), ejectPlayerFromBuilding(), enhanceCharacter(), existsName(), finishHologrind(), fixHAM(), getAccount(), getBadgeKey(), getCleanupCharacterCount(), getHighestBadgeIndex(), getInRangeOwnedStructure(), getInRangeStructureWithAdminRights(), getInsurableItems(), getNearbyCraftingStation(), getObjectID(), getOnlineZoneClientMap(), getPlayer(), getStartingLocation(), getTeachableSkills(), handleAbortTradeMessage(), handleAcceptTransactionMessage(), handleAddItemToTradeWindow(), handleGiveMoneyMessage(), handleUnAcceptTransactionMessage(), handleVerifyTradeMessage(), healEnhance(), increaseOnlineCharCountIfPossible(), kickUser(), killPlayer(), loadNameMap(), lootAll(), notifyDestruction(), notifyObserverEvent(), offerTeaching(), promptTeachableSkills(), removeEncumbrancies(), removePlayer(), rescheduleCorpseDestruction(), resendLoginMessageToAll(), sendActivateCloneRequest(), sendBattleFatigueMessage(), sendLoginMessage(), sendPlayerToCloner(), sendStartingLocationsTo(), setExperienceMultiplier(), shouldDeleteCharacter(), shouldRescheduleCorpseDestruction(), startListen(), startWatch(), stopListen(), stopWatch(), unbanAccount(), unbanCharacter(), unbanFromGalaxy(), updatePermissionLevel(), updatePermissionName(), and updateSwimmingState().
DistributedObjectServant * PlayerManager::_getImplementationForRead ()
Definition at line 1239 of file PlayerManager.cpp.
void PlayerManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 1243 of file PlayerManager.cpp.
bool PlayerManager::acceptTeachingOffer (CreatureObject * teacher, CreatureObject * student, Skill * skill)
Accepts a teaching office.
Precondition
student crosslocked with teacher
Postcondition
student crosslocked with teacher
Definition at line 1151 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer().
Referenced by PlayerTeachConfirmSuiCallback::run().
void PlayerManager::addInsurableItemsRecursive (SceneObject * obj, SortedVector< ManagedReference< SceneObject * > > * items, bool onlyInsurable)
Definition at line 350 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::addInsurableItemsRecursive().
void PlayerManager::addPlayer (CreatureObject * player)
Definition at line 867 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::addPlayer(), and RPC_ADDPLAYER__CREATUREOBJECT_.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
void PlayerManager::applyEncumbrancies (CreatureObject * player, ArmorObject * armor)
Definition at line 264 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::applyEncumbrancies(), and RPC_APPLYENCUMBRANCIES__CREATUREOBJECT_ARMOROBJECT_.
Referenced by PlayerContainerComponent::notifyObjectInserted().
void PlayerManager::awardBadge (PlayerObject * ghost, unsigned int badge)
Definition at line 294 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::awardBadge(), and RPC_AWARDBADGE__PLAYEROBJECT_INT_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::awardBadge(), and server::zone::managers::skill::SkillManager::awardSkill().
void PlayerManager::awardExperience (CreatureObject * player, const String & xpType, int amount, bool sendSystemMessage = true, float localMultiplier = 1.0f)
Definition at line 323 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::awardExperience(), and RPC_AWARDEXPERIENCE__CREATUREOBJECT_STRING_INT_BOOL_FLOAT_.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::awardSlicingXP(), DotPackCommand::awardXp(), HealStateCommand::awardXp(), HealWoundCommand::awardXp(), TendCommand::awardXp(), CurePackCommand::awardXp(), RevivePlayerCommand::awardXp(), HealEnhanceCommand::awardXp(), HealDamageCommand::awardXp(), server::zone::objects::area::CampSiteActiveAreaImplementation::despawnCamp(), RegainConsciousnessCommand::doQueueCommand(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSlice(), and server::zone::objects::player::sessions::ImageDesignSessionImplementation::updateImageDesign().
String PlayerManager::banAccount (PlayerObject * admin, Account * account, unsigned int seconds, const String & reason)
Definition at line 968 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::banAccount(), and RPC_BANACCOUNT__PLAYEROBJECT_ACCOUNT_INT_STRING_.
String PlayerManager::banCharacter (PlayerObject * admin, Account * account, const String & name, unsigned int galaxyID, unsigned int seconds, const String & reason)
Definition at line 1044 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::banCharacter(), and RPC_BANCHARACTER__PLAYEROBJECT_ACCOUNT_STRING_INT_INT_STRING_.
String PlayerManager::banFromGalaxy (PlayerObject * admin, Account * account, unsigned const int galaxy, unsigned int seconds, const String & reason)
Definition at line 1005 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::banFromGalaxy(), and RPC_BANFROMGALAXY__PLAYEROBJECT_ACCOUNT_INT_INT_STRING_.
byte PlayerManager::calculateIncapacitationTimer (CreatureObject * player, int condition)
Calculates the length of time that incapacitation should last. Cannot exceed 1 minute.
Returns
Returns the number of seconds until the player should recover from incapacitation.
Definition at line 234 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::calculateIncapacitationTimer(), and RPC_CALCULATEINCAPACITATIONTIMER__CREATUREOBJECT_INT_.
int PlayerManager::calculatePlayerLevel (CreatureObject * player)
Definition at line 615 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::calculatePlayerLevel(), and RPC_CALCULATEPLAYERLEVEL__CREATUREOBJECT_.
Referenced by server::zone::objects::mission::bountyhunter::events::FindTargetTask::getTargetLevel().
bool PlayerManager::canGroupMemberHarvestCorpse (CreatureObject * player, Creature * creature)
Definition at line 203 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::canGroupMemberHarvestCorpse(), and RPC_CANGROUPMEMBERHARVESTCORPSE__CREATUREOBJECT_CREATURE_.
bool PlayerManager::checkEncumbrancies (CreatureObject * player, ArmorObject * armor)
Check for enough encumbrances
Definition at line 249 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::checkEncumbrancies(), and RPC_CHECKENCUMBRANCIES__CREATUREOBJECT_ARMOROBJECT_.
Referenced by PlayerContainerComponent::canAddObject().
bool PlayerManager::checkExistentNameInDatabase (const String & firstName)
Definition at line 701 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::checkExistentNameInDatabase(), and RPC_CHECKEXISTENTNAMEINDATABASE__STRING_.
bool PlayerManager::checkPlayerName (MessageCallback * callback)
Definition at line 131 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::checkPlayerName().
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
int PlayerManager::checkSpeedHackFirstTest (CreatureObject * player, float parsedSpeed, ValidatedPosition & teleportPosition, float errorMultiplier = 1)
Definition at line 767 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackFirstTest().
int PlayerManager::checkSpeedHackSecondTest (CreatureObject * player, float newX, float newZ, float newY, unsigned int newStamp, SceneObject * newParent = NULL)
Definition at line 776 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackSecondTest(), and RPC_CHECKSPEEDHACKSECONDTEST__CREATUREOBJECT_FLOAT_FLOAT_FLOAT_INT_SCENEOBJECT_.
bool PlayerManager::checkTradeItems (CreatureObject * player, CreatureObject * receiver)
Definition at line 445 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::checkTradeItems(), and RPC_CHECKTRADEITEMS__CREATUREOBJECT_CREATUREOBJECT_.
void PlayerManager::cleanupCharacters ()
Definition at line 1191 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::cleanupCharacters(), and RPC_CLEANUPCHARACTERS__.
Referenced by ServerCore::handleCommands(), and ServerCore::initialize().
Reference< TangibleObject * > PlayerManager::createHairObject (const String & hairObjectFile, const String & hairCustomization)
Definition at line 715 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::createHairObject(), and RPC_CREATEHAIROBJECT__STRING_STRING_.
bool PlayerManager::createPlayer (MessageCallback * callback)
Definition at line 122 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::createPlayer().
Referenced by ClientCreateCharacterCallback::run().
void PlayerManager::createSkippedTutorialBuilding (CreatureObject * player)
Definition at line 744 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::createSkippedTutorialBuilding(), and RPC_CREATESKIPPEDTUTORIALBUILDING__CREATUREOBJECT_.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
void PlayerManager::createTutorialBuilding (CreatureObject * player)
Definition at line 730 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::createTutorialBuilding(), and RPC_CREATETUTORIALBUILDING__CREATUREOBJECT_.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
void PlayerManager::decreaseOnlineCharCount (ZoneClientSession * client)
Definition at line 1100 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::decreaseOnlineCharCount(), and RPC_DECREASEONLINECHARCOUNT__ZONECLIENTSESSION_.
Referenced by server::zone::ZoneClientSessionImplementation::setPlayer().
void PlayerManager::disseminateExperience (TangibleObject * destructedObject, ThreatMap * threatMap)
Definition at line 606 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::disseminateExperience().
Referenced by server::zone::managers::creature::LairObserverImplementation::notifyDestruction().
void PlayerManager::ejectPlayerFromBuilding (CreatureObject * player)
Definition at line 687 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::ejectPlayerFromBuilding(), and RPC_EJECTPLAYERFROMBUILDING__CREATUREOBJECT_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::unload().
void PlayerManager::enhanceCharacter (CreatureObject * player)
Enhances the target character with doc/ent buffs
Precondition
{ player is locked }
Postcondition
{ player is locked }
Definition at line 1219 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::enhanceCharacter(), and RPC_ENHANCECHARACTER__CREATUREOBJECT_.
Referenced by server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation::enhanceCharacter().
bool PlayerManager::existsName (const String & name)
Definition at line 795 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::existsName(), and RPC_EXISTSNAME__STRING_.
Referenced by AddFriendCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), and ConsentCommand::doQueueCommand().
void PlayerManager::finishHologrind (CreatureObject * player)
Definition at line 926 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::finishHologrind(), and RPC_FINISHHOLOGRIND__CREATUREOBJECT_.
void PlayerManager::fixHAM (CreatureObject * player)
Definition at line 1128 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::fixHAM(), and RPC_FIXHAM__CREATUREOBJECT_.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase().
Account * PlayerManager::getAccount (const String & username)
Definition at line 940 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::getAccount(), and RPC_GETACCOUNT__STRING_.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), server::zone::managers::holocron::HolocronManager::getReporterId(), and PermissionsServlet::handlePost().
Account * PlayerManager::getAccount (unsigned int accountID)
Definition at line 954 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::getAccount(), and RPC_GETACCOUNT__INT_.
String PlayerManager::getBadgeKey (int idx)
Definition at line 895 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::getBadgeKey(), and RPC_GETBADGEKEY__INT_.
Referenced by PlayerInfoCommand::executeCommand().
void PlayerManager::getCleanupCharacterCount ()
Definition at line 1178 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::getCleanupCharacterCount(), and RPC_GETCLEANUPCHARACTERCOUNT__.
Referenced by ServerCore::handleCommands(), and ServerCore::initialize().
int PlayerManager::getHighestBadgeIndex ()
Definition at line 74 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::getHighestBadgeIndex(), and RPC_GETHIGHESTBADGEINDEX__.
StructureObject * PlayerManager::getInRangeOwnedStructure (CreatureObject * creature, float range = 128)
Definition at line 475 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::getInRangeOwnedStructure(), and RPC_GETINRANGEOWNEDSTRUCTURE__CREATUREOBJECT_FLOAT_.
SceneObject * PlayerManager::getInRangeStructureWithAdminRights (CreatureObject * creature, unsigned long long targetID = 0)
Finds the closest structure in range with Administration priveleges. This is primarily used for commands that require a building or installation. First checks the passed targetID, then checks if the player is inside a building. Finally searches for an installation in range.
Precondition
: creature locked, zone unlocked
Postcondition
: creature locked, zone unlocked
Parameters
targetID The object id of the players target.
Definition at line 460 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::getInRangeStructureWithAdminRights(), and RPC_GETINRANGESTRUCTUREWITHADMINRIGHTS__CREATUREOBJECT_LONG_.
Referenced by AddPowerCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), and TransferstructureCommand::doQueueCommand().
SortedVector< ManagedReference< SceneObject * > > PlayerManager::getInsurableItems (CreatureObject * player, bool onlyInsurable = true)
Definition at line 341 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::getInsurableItems().
Referenced by InsureCommand::doQueueCommand(), InsuranceTerminalMenuComponent::handleObjectMenuSelect(), and InsuranceAllConfirmSuiCallback::run().
CraftingStation * PlayerManager::getNearbyCraftingStation (CreatureObject * player, int type)
Definition at line 911 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::getNearbyCraftingStation(), and RPC_GETNEARBYCRAFTINGSTATION__CREATUREOBJECT_INT_.
unsigned long long PlayerManager::getObjectID (const String & name)
Definition at line 809 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::getObjectID(), and RPC_GETOBJECTID__STRING_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addFriend(), server::zone::managers::city::CityManagerImplementation::addMilitiaMember(), FindPlayerCommand::doQueueCommand(), and server::zone::objects::player::PlayerObjectImplementation::removeFriend().
OnlineZoneClientMap * PlayerManager::getOnlineZoneClientMap ()
Definition at line 1169 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::getOnlineZoneClientMap().
Referenced by GetAccountInfoCommand::doQueueCommand().
Reference< CreatureObject * > PlayerManager::getPlayer (const String & name)
Definition at line 823 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::getPlayer(), and RPC_GETPLAYER__STRING_.
Referenced by GetPlayerIdCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), TeleportToCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), TipCommand::doQueueCommand(), PlayerInfoCommand::executeCommand(), and PermissionsServlet::handlePost().
StartingLocation * PlayerManager::getStartingLocation (const String & city)
Definition at line 96 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::getStartingLocation().
Referenced by NewbieSelectStartingLocationCommand::doQueueCommand().
SortedVector< String > PlayerManager::getTeachableSkills (CreatureObject * teacher, CreatureObject * student)
Gets a vector skillboxes this teacher can teach this student.
Precondition
student crosslocked with teacher
Postcondition
student crosslocked with teacher
Definition at line 1160 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::getTeachableSkills().
void PlayerManager::handleAbortTradeMessage (CreatureObject * player)
Definition at line 359 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::handleAbortTradeMessage(), and RPC_HANDLEABORTTRADEMESSAGE__CREATUREOBJECT_.
Referenced by CreateManfSchematicCommand::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), and AbortTradeMessageCallback::run().
void PlayerManager::handleAcceptTransactionMessage (CreatureObject * player)
Definition at line 403 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::handleAcceptTransactionMessage(), and RPC_HANDLEACCEPTTRANSACTIONMESSAGE__CREATUREOBJECT_.
Referenced by AcceptTransactionMessageCallback::run().
void PlayerManager::handleAddItemToTradeWindow (CreatureObject * player, unsigned long long itemID)
Definition at line 373 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::handleAddItemToTradeWindow(), and RPC_HANDLEADDITEMTOTRADEWINDOW__CREATUREOBJECT_LONG_.
Referenced by AddItemMessageCallback::run().
void PlayerManager::handleGiveMoneyMessage (CreatureObject * player, unsigned int value)
Definition at line 388 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::handleGiveMoneyMessage(), and RPC_HANDLEGIVEMONEYMESSAGE__CREATUREOBJECT_INT_.
Referenced by GiveMoneyMessageCallback::run().
void PlayerManager::handleUnAcceptTransactionMessage (CreatureObject * player)
Definition at line 417 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::handleUnAcceptTransactionMessage(), and RPC_HANDLEUNACCEPTTRANSACTIONMESSAGE__CREATUREOBJECT_.
Referenced by UnAcceptTransactionMessageCallback::run().
void PlayerManager::handleVerifyTradeMessage (CreatureObject * player)
Definition at line 431 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::handleVerifyTradeMessage(), and RPC_HANDLEVERIFYTRADEMESSAGE__CREATUREOBJECT_.
Referenced by VerifyTradeMessageCallback::run().
int PlayerManager::healEnhance (CreatureObject * enhancer, CreatureObject * patient, byte attribute, int buffvalue, float duration)
Enhances the patients attribute by a specified amount for a specified duration.
Parameters
patient The patient to enhance.
attribute The attribute to enhance.
buffvalue The amount to enhance the attribute.
duration The duration in seconds the enhancement will last.
Returns
The amount that was enhanced. If a buff existed, this is the amount exceeding the previous buff.
Definition at line 588 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::healEnhance(), and RPC_HEALENHANCE__CREATUREOBJECT_CREATUREOBJECT_BYTE_INT_FLOAT_.
Referenced by HealEnhanceCommand::doQueueCommand().
bool PlayerManager::increaseOnlineCharCountIfPossible (ZoneClientSession * client)
Definition at line 1114 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::increaseOnlineCharCountIfPossible(), and RPC_INCREASEONLINECHARCOUNTIFPOSSIBLE__ZONECLIENTSESSION_.
Referenced by SelectCharacterCallback::run().
bool PlayerManager::kickUser (const String & name, const String & admin, String & reason, bool doBan = true)
Kicks a user
Definition at line 105 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::kickUser(), and RPC_KICKUSER__STRING_STRING_STRING_BOOL_.
void PlayerManager::killPlayer (TangibleObject * attacker, CreatureObject * player, int typeofdeath = 0)
Precondition
{ attacker and player locked }
Postcondition
{ attacker and player locked }
Definition at line 218 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::killPlayer(), and RPC_KILLPLAYER__TANGIBLEOBJECT_CREATUREOBJECT_INT_.
Referenced by SniperShotCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), and DeathBlowCommand::doQueueCommand().
void PlayerManager::loadNameMap ()
Definition at line 61 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::loadNameMap(), and RPC_LOADNAMEMAP__.
void PlayerManager::lootAll (CreatureObject * player, CreatureObject * creature)
Definition at line 573 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), and RPC_LOOTALL__CREATUREOBJECT_CREATUREOBJECT_.
Referenced by LootCommand::doQueueCommand(), server::zone::objects::creature::AiAgentImplementation::handleObjectMenuSelect(), and server::zone::objects::creature::CreatureObjectImplementation::handleObjectMenuSelect().
int PlayerManager::notifyDestruction (TangibleObject * destructor, TangibleObject * destructedObject, int condition)
Precondition
{ destructor and destructedObject locked }
Postcondition
{ destructor and destructedObject locked }
Definition at line 157 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), and RPC_NOTIFYDESTRUCTION__TANGIBLEOBJECT_TANGIBLEOBJECT_INT_.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::notifyObjectDestructionObservers().
int PlayerManager::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 140 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
bool PlayerManager::offerTeaching (CreatureObject * teacher, CreatureObject * student, Skill * skill)
Sends a confirmation box to the student asking if they want to learn the skill.
Precondition
student crosslocked with teacher
Postcondition
student crosslocked with teacher
Definition at line 1142 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::offerTeaching().
Referenced by PlayerTeachSuiCallback::run().
bool PlayerManager::promptTeachableSkills (CreatureObject * teacher, SceneObject * target)
Definition at line 1085 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::promptTeachableSkills(), and RPC_PROMPTTEACHABLESKILLS__CREATUREOBJECT_SCENEOBJECT_.
Referenced by TeachCommand::doQueueCommand().
void PlayerManager::removeEncumbrancies (CreatureObject * player, ArmorObject * armor)
Definition at line 279 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::removeEncumbrancies(), and RPC_REMOVEENCUMBRANCIES__CREATUREOBJECT_ARMOROBJECT_.
Referenced by PlayerContainerComponent::notifyObjectRemoved().
void PlayerManager::removePlayer (String & playerName)
Definition at line 881 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::removePlayer(), and RPC_REMOVEPLAYER__STRING_.
void PlayerManager::rescheduleCorpseDestruction (CreatureObject * player, CreatureObject * ai)
Definition at line 188 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::rescheduleCorpseDestruction(), and RPC_RESCHEDULECORPSEDESTRUCTION__CREATUREOBJECT_CREATUREOBJECT_.
void PlayerManager::resendLoginMessageToAll ()
Definition at line 643 of file PlayerManager.cpp.
References _getImplementation(), server::zone::managers::player::PlayerManagerImplementation::resendLoginMessageToAll(), and RPC_RESENDLOGINMESSAGETOALL__.
void PlayerManager::sendActivateCloneRequest (CreatureObject * player, int typeofdeath = 0)
Definition at line 656 of file PlayerManager.cpp.
References _getImplementation(), RPC_SENDACTIVATECLONEREQUEST__CREATUREOBJECT_INT_, and server::zone::managers::player::PlayerManagerImplementation::sendActivateCloneRequest().
Referenced by ActivateCloneCommand::doQueueCommand().
void PlayerManager::sendBattleFatigueMessage (CreatureObject * player, CreatureObject * target)
Definition at line 490 of file PlayerManager.cpp.
References _getImplementation(), RPC_SENDBATTLEFATIGUEMESSAGE__CREATUREOBJECT_CREATUREOBJECT_, and server::zone::managers::player::PlayerManagerImplementation::sendBattleFatigueMessage().
Referenced by HealDamageCommand::doAreaMedicActionTarget(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), and HealDamageCommand::doQueueCommand().
void PlayerManager::sendLoginMessage (CreatureObject * player)
Definition at line 629 of file PlayerManager.cpp.
References _getImplementation(), RPC_SENDLOGINMESSAGE__CREATUREOBJECT_, and server::zone::managers::player::PlayerManagerImplementation::sendLoginMessage().
Referenced by SelectCharacterCallback::run().
void PlayerManager::sendPlayerToCloner (CreatureObject * player, unsigned long long clonerID, int typeofdeath = 0)
Definition at line 671 of file PlayerManager.cpp.
References _getImplementation(), RPC_SENDPLAYERTOCLONER__CREATUREOBJECT_LONG_INT_, and server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner().
Referenced by CloningRequestSuiCallback::run().
void PlayerManager::sendStartingLocationsTo (CreatureObject * player)
Definition at line 87 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::sendStartingLocationsTo().
void PlayerManager::setExperienceMultiplier (float globalMultiplier)
Definition at line 309 of file PlayerManager.cpp.
References _getImplementation(), RPC_SETEXPERIENCEMULTIPLIER__FLOAT_, and server::zone::managers::player::PlayerManagerImplementation::setExperienceMultiplier().
bool PlayerManager::shouldDeleteCharacter (unsigned long long characterID, int galaxyID)
Definition at line 1204 of file PlayerManager.cpp.
References _getImplementation(), RPC_SHOULDDELETECHARACTER__LONG_INT_, and server::zone::managers::player::PlayerManagerImplementation::shouldDeleteCharacter().
bool PlayerManager::shouldRescheduleCorpseDestruction (CreatureObject * player, CreatureObject * ai)
Definition at line 173 of file PlayerManager.cpp.
References _getImplementation(), RPC_SHOULDRESCHEDULECORPSEDESTRUCTION__CREATUREOBJECT_CREATUREOBJECT_, and server::zone::managers::player::PlayerManagerImplementation::shouldRescheduleCorpseDestruction().
void PlayerManager::startListen (CreatureObject * creature, unsigned long long entid)
Definition at line 558 of file PlayerManager.cpp.
References _getImplementation(), RPC_STARTLISTEN__CREATUREOBJECT_LONG_, and server::zone::managers::player::PlayerManagerImplementation::startListen().
Referenced by ListenCommand::doQueueCommand().
void PlayerManager::startWatch (CreatureObject * creature, unsigned long long entid)
Definition at line 543 of file PlayerManager.cpp.
References _getImplementation(), RPC_STARTWATCH__CREATUREOBJECT_LONG_, and server::zone::managers::player::PlayerManagerImplementation::startWatch().
Referenced by WatchCommand::doQueueCommand().
void PlayerManager::stopListen (CreatureObject * creature, unsigned long long entid, bool doSendPackets = true, bool forced = false, bool doLock = true, bool outOfRange = false)
Definition at line 524 of file PlayerManager.cpp.
References _getImplementation(), RPC_STOPLISTEN__CREATUREOBJECT_LONG_BOOL_BOOL_BOOL_BOOL_, and server::zone::managers::player::PlayerManagerImplementation::stopListen().
Referenced by StoplisteningCommand::doQueueCommand().
void PlayerManager::stopWatch (CreatureObject * creature, unsigned long long entid, bool doSendPackets = true, bool forced = false, bool doLock = true, bool outOfRange = false)
Definition at line 505 of file PlayerManager.cpp.
References _getImplementation(), RPC_STOPWATCH__CREATUREOBJECT_LONG_BOOL_BOOL_BOOL_BOOL_, and server::zone::managers::player::PlayerManagerImplementation::stopWatch().
Referenced by StopwatchingCommand::doQueueCommand().
String PlayerManager::unbanAccount (PlayerObject * admin, Account * account, const String & reason)
Definition at line 987 of file PlayerManager.cpp.
References _getImplementation(), RPC_UNBANACCOUNT__PLAYEROBJECT_ACCOUNT_STRING_, and server::zone::managers::player::PlayerManagerImplementation::unbanAccount().
String PlayerManager::unbanCharacter (PlayerObject * admin, Account * account, const String & name, unsigned int galaxyID, const String & reason)
Definition at line 1065 of file PlayerManager.cpp.
References _getImplementation(), RPC_UNBANCHARACTER__PLAYEROBJECT_ACCOUNT_STRING_INT_STRING_, and server::zone::managers::player::PlayerManagerImplementation::unbanCharacter().
String PlayerManager::unbanFromGalaxy (PlayerObject * admin, Account * account, unsigned const int galaxy, const String & reason)
Definition at line 1025 of file PlayerManager.cpp.
References _getImplementation(), RPC_UNBANFROMGALAXY__PLAYEROBJECT_ACCOUNT_INT_STRING_, and server::zone::managers::player::PlayerManagerImplementation::unbanFromGalaxy().
void PlayerManager::updatePermissionLevel (CreatureObject * player, int adminLevel = 1)
Definition at line 837 of file PlayerManager.cpp.
References _getImplementation(), RPC_UPDATEPERMISSIONLEVEL__CREATUREOBJECT_INT_, and server::zone::managers::player::PlayerManagerImplementation::updatePermissionLevel().
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), and PermissionsServlet::handlePost().
void PlayerManager::updatePermissionName (CreatureObject * player, int adminLevel)
Definition at line 852 of file PlayerManager.cpp.
References _getImplementation(), RPC_UPDATEPERMISSIONNAME__CREATUREOBJECT_INT_, and server::zone::managers::player::PlayerManagerImplementation::updatePermissionName().
void PlayerManager::updateSwimmingState (CreatureObject * player, float newZ, IntersectionResults * intersections = NULL, CloseObjectsVector * closeObjects = NULL)
Definition at line 758 of file PlayerManager.cpp.
References _getImplementation(), and server::zone::managers::player::PlayerManagerImplementation::updateSwimmingState().
Referenced by DismountCommand::doQueueCommand().
Friends And Related Function Documentation
friend class PlayerManagerHelper friend
Definition at line 515 of file PlayerManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/PlayerManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/PlayerManager.cpp