Core3: TipCommandSuiCallback Class Reference
TipCommandSuiCallback Class Reference
#include <TipCommandSuiCallback.h>
Public Member Functions
TipCommandSuiCallback (ZoneServer *server, CreatureObject *target, int amount)
void run (CreatureObject *player, SuiBox *suiBox, bool cancelPressed, Vector< UnicodeString > *args)
Public Member Functions inherited from server::zone::objects::player::sui::SuiCallback
SuiCallback (ZoneServer *serv)
virtual void run (server::zone::objects::creature::CreatureObject *player, SuiBox *suiBox, bool cancelPressed, Vector< UnicodeString > *args)=0
Private Attributes
ManagedReference
< CreatureObject * > targetPlayer
int amount
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::player::sui::SuiCallback
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 13 of file TipCommandSuiCallback.h.
Constructor & Destructor Documentation
TipCommandSuiCallback::TipCommandSuiCallback (ZoneServer * server, CreatureObject * target, int amount) inline
Definition at line 19 of file TipCommandSuiCallback.h.
References amount, and targetPlayer.
Member Function Documentation
void TipCommandSuiCallback::run (CreatureObject * player, SuiBox * suiBox, bool cancelPressed, Vector< UnicodeString > * args) inline
Definition at line 26 of file TipCommandSuiCallback.h.
References amount, server::zone::objects::player::sui::SuiBox::isMessageBox(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), and targetPlayer.
Member Data Documentation
int TipCommandSuiCallback::amount private
Definition at line 16 of file TipCommandSuiCallback.h.
Referenced by run(), and TipCommandSuiCallback().
ManagedReference<CreatureObject*> TipCommandSuiCallback::targetPlayer private
Definition at line 15 of file TipCommandSuiCallback.h.
Referenced by run(), and TipCommandSuiCallback().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/callbacks/TipCommandSuiCallback.h