Core3: MaskscentCommand Class Reference
MaskscentCommand Class Reference
#include <MaskscentCommand.h>
Public Member Functions
MaskscentCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
bool checkMaskScent (CreatureObject *creature)
Detailed Description
Definition at line 50 of file MaskscentCommand.h.
Constructor & Destructor Documentation
MaskscentCommand::MaskscentCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file MaskscentCommand.h.
Member Function Documentation
bool MaskscentCommand::checkMaskScent (CreatureObject * creature) inline
Definition at line 97 of file MaskscentCommand.h.
References server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), server::zone::objects::creature::CreatureObject::getCooldownTime(), server::zone::objects::tangible::TangibleObject::getOptionsBitmask(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isInCombat(), CreatureState::MASKSCENT, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
int MaskscentCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 58 of file MaskscentCommand.h.
References server::zone::objects::creature::CreatureObject::addBuff(), checkMaskScent(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::hasBuff(), CreatureState::MASKSCENT, server::zone::objects::creature::CreatureObject::sendSystemMessage(), BuffType::SKILL, and server::zone::objects::creature::CreatureObject::updateCooldownTimer().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/MaskscentCommand.h