Core3: server::zone::objects::player::sessions::StructureStatusSessionAdapter Class Reference
server::zone::objects::player::sessions::StructureStatusSessionAdapter Class Reference
#include <StructureStatusSession.h>
Public Member Functions
StructureStatusSessionAdapter (StructureStatusSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession ()
int updateStatus ()
int cancelSession ()
int clearSession ()
Detailed Description
Definition at line 117 of file StructureStatusSession.h.
Constructor & Destructor Documentation
StructureStatusSessionAdapter::StructureStatusSessionAdapter (StructureStatusSession * impl)
Definition at line 265 of file StructureStatusSession.cpp.
Member Function Documentation
int StructureStatusSessionAdapter::cancelSession ()
Definition at line 305 of file StructureStatusSession.cpp.
Referenced by invokeMethod().
int StructureStatusSessionAdapter::clearSession ()
Definition at line 309 of file StructureStatusSession.cpp.
Referenced by invokeMethod().
int StructureStatusSessionAdapter::initializeSession ()
Definition at line 297 of file StructureStatusSession.cpp.
Referenced by invokeMethod().
void StructureStatusSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 268 of file StructureStatusSession.cpp.
References cancelSession(), clearSession(), initializeSession(), RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_INITIALIZESESSION__, RPC_UPDATESTATUS__, and updateStatus().
int StructureStatusSessionAdapter::updateStatus ()
Definition at line 301 of file StructureStatusSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureStatusSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureStatusSession.cpp