Core3: Races Class Reference
Races Class Reference
#include <Races.h>
Static Public Member Functions
static const char * getRace (int raceid)
static int getSpeciesID (int raceid)
static const char * getMood (int moodid)
static const char * getSpecies (int raceid)
static const char * getGender (int raceid)
static uint32 getRaceCRC (int raceid)
static const char * getCompleteRace (uint32 sharedRaceCRC)
static int getRaceID (const String &name)
static int getMoodID (const String &name)
static const char * getMoodStr (const String &name)
static unsigned int * getAttribLimits (int raceid)
Detailed Description
Definition at line 395 of file Races.h.
Member Function Documentation
static unsigned int* Races::getAttribLimits (int raceid) inline static
Definition at line 481 of file Races.h.
static const char* Races::getCompleteRace (uint32 sharedRaceCRC) inline static
Definition at line 439 of file Races.h.
static const char* Races::getGender (int raceid) inline static
Definition at line 425 of file Races.h.
static const char* Races::getMood (int moodid) inline static
Definition at line 411 of file Races.h.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::setMood().
static int Races::getMoodID (const String & name) inline static
Definition at line 463 of file Races.h.
Referenced by VendorDataComponent::performVendorBark().
static const char* Races::getMoodStr (const String & name) inline static
Definition at line 472 of file Races.h.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainmentUpdate(), and server::zone::objects::creature::CreatureObjectImplementation::setMood().
static const char* Races::getRace (int raceid) inline static
Definition at line 397 of file Races.h.
static uint32 Races::getRaceCRC (int raceid) inline static
Definition at line 432 of file Races.h.
static int Races::getRaceID (const String & name) inline static
Definition at line 454 of file Races.h.
Referenced by PlayersNearYouMessage::addFoundPlayer(), and ClientCreateCharacterCallback::parse().
static const char* Races::getSpecies (int raceid) inline static
Definition at line 418 of file Races.h.
static int Races::getSpeciesID (int raceid) inline static
Definition at line 404 of file Races.h.
Referenced by ClientCreateCharacterCallback::parse().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/Races.h