Core3: ChildObject Class Reference
ChildObject Class Reference
#include <ChildObject.h>
Public Member Functions
ChildObject ()
ChildObject (const ChildObject &obj)
ChildObject & operator= (const ChildObject &obj)
void parseFromLua (LuaObject *luaObject)
void setPosition (float x, float z, float y)
void setDirection (float fw, float fx, float fy, float fz)
void setCellId (int id)
void setContainmentType (int containment)
void setTemplateFile (const String &file)
Vector3 & getPosition ()
Quaternion & getDirection ()
String & getTemplateFile ()
int getCellId ()
int getContainmentType ()
Private Attributes
Vector3 position
Quaternion direction
String templateFile
int cellid
int containmentType
Detailed Description
Definition at line 13 of file ChildObject.h.
Constructor & Destructor Documentation
ChildObject::ChildObject () inline
Definition at line 21 of file ChildObject.h.
References cellid, and containmentType.
ChildObject::ChildObject (const ChildObject & obj) inline
Definition at line 26 of file ChildObject.h.
References cellid, containmentType, direction, position, and templateFile.
Member Function Documentation
int ChildObject::getCellId () inline
Definition at line 92 of file ChildObject.h.
References cellid.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), and server::zone::objects::scene::SceneObjectImplementation::createChildObjects().
int ChildObject::getContainmentType () inline
Definition at line 96 of file ChildObject.h.
References containmentType.
Referenced by server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), and server::zone::objects::scene::SceneObjectImplementation::createChildObjects().
Quaternion& ChildObject::getDirection () inline
Definition at line 84 of file ChildObject.h.
References direction.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addChildInstallationFromDeed(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), and server::zone::objects::scene::SceneObjectImplementation::createChildObjects().
Vector3& ChildObject::getPosition () inline
Definition at line 80 of file ChildObject.h.
References position.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addChildInstallationFromDeed(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), and server::zone::objects::scene::SceneObjectImplementation::createChildObjects().
String& ChildObject::getTemplateFile () inline
Definition at line 88 of file ChildObject.h.
References templateFile.
Referenced by server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), server::zone::objects::scene::SceneObjectImplementation::createChildObjects(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield(), and server::zone::managers::gcw::GCWManagerImplementation::performDonateTurret().
ChildObject& ChildObject::operator= (const ChildObject & obj) inline
Definition at line 34 of file ChildObject.h.
References cellid, containmentType, direction, position, and templateFile.
void ChildObject::parseFromLua (LuaObject * luaObject) inline
Definition at line 47 of file ChildObject.h.
References cellid, containmentType, direction, position, and templateFile.
Referenced by SharedBuildingObjectTemplate::parseVariableData(), and server::zone::templates::SharedObjectTemplate::parseVariableData().
void ChildObject::setCellId (int id) inline
Definition at line 68 of file ChildObject.h.
References cellid.
void ChildObject::setContainmentType (int containment) inline
Definition at line 72 of file ChildObject.h.
References containmentType.
void ChildObject::setDirection (float fw, float fx, float fy, float fz) inline
Definition at line 64 of file ChildObject.h.
References direction.
void ChildObject::setPosition (float x, float z, float y) inline
Definition at line 60 of file ChildObject.h.
References position.
void ChildObject::setTemplateFile (const String & file) inline
Definition at line 76 of file ChildObject.h.
References templateFile.
Member Data Documentation
int ChildObject::cellid private
Definition at line 17 of file ChildObject.h.
Referenced by ChildObject(), getCellId(), operator=(), parseFromLua(), and setCellId().
int ChildObject::containmentType private
Definition at line 18 of file ChildObject.h.
Referenced by ChildObject(), getContainmentType(), operator=(), parseFromLua(), and setContainmentType().
Quaternion ChildObject::direction private
Definition at line 15 of file ChildObject.h.
Referenced by ChildObject(), getDirection(), operator=(), parseFromLua(), and setDirection().
Vector3 ChildObject::position private
Definition at line 14 of file ChildObject.h.
Referenced by ChildObject(), getPosition(), operator=(), parseFromLua(), and setPosition().
String ChildObject::templateFile private
Definition at line 16 of file ChildObject.h.
Referenced by ChildObject(), getTemplateFile(), operator=(), parseFromLua(), and setTemplateFile().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/ChildObject.h