Core3: FilterSlope Class Reference
FilterSlope Class Reference
#include <FilterSlope.h>
Public Member Functions
FilterSlope ()
void parseFromIffStream (engine::util::IffStream *iffStream)
void setMinAngle (float newAngle)
void setMaxAngle (float newAngle)
void parseFromIffStream (engine::util::IffStream *iffStream, Version<'0002'>)
float process (float x, float y, float transformValue, float &baseValue, TerrainGenerator *terrainGenerator)
bool isEnabled ()
Public Member Functions inherited from ProceduralRule<'FSLP'>
ProceduralRule ()
bool isEnabled ()
Public Member Functions inherited from TemplateVariable< formType >
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Public Member Functions inherited from FilterProceduralRule
FilterProceduralRule (int type)
virtual ~FilterProceduralRule ()
virtual float process (float x, float y, float transformValue, float &baseValue, TerrainGenerator *terrainGenerator, FilterRectangle *rect)
int getFeatheringType ()
int getFilterType ()
int getInternalType ()
bool isType (int type)
Private Attributes
float minAngle
float max
float maxAngle
float min
Additional Inherited Members
Static Public Attributes inherited from FilterProceduralRule
static const int HEIGHTTYPE = 0x100
static const int ENVIRONMENT = 0x200
static const int HEIGHT = 0
static const int FRACTAL = 1
static const int SLOPE = 2
static const int DIRECTION = 3
static const int SHADER = 4
static const int BITMAP = 5
Protected Attributes inherited from ProceduralRule<'FSLP'>
InformationHeader informationHeader
Protected Attributes inherited from FilterProceduralRule
int featheringType
float featheringAmount
int filterType
int internalType
Detailed Description
Definition at line 17 of file FilterSlope.h.
Constructor & Destructor Documentation
FilterSlope::FilterSlope () inline
Definition at line 26 of file FilterSlope.h.
References FilterProceduralRule::filterType, and FilterProceduralRule::HEIGHTTYPE.
Member Function Documentation
bool FilterSlope::isEnabled () inline virtual
Reimplemented from FilterProceduralRule.
Definition at line 121 of file FilterSlope.h.
References ProceduralRule<'FSLP'>::informationHeader, and InformationHeader::isEnabled().
void FilterSlope::parseFromIffStream (engine::util::IffStream * iffStream) inline virtual
Reimplemented from TemplateVariable< formType >.
Definition at line 30 of file FilterSlope.h.
void FilterSlope::parseFromIffStream (engine::util::IffStream * iffStream, Version<'0002'>) inline
Definition at line 77 of file FilterSlope.h.
References FilterProceduralRule::featheringAmount, FilterProceduralRule::featheringType, ProceduralRule<'FSLP'>::informationHeader, maxAngle, minAngle, TemplateVariable< formType >::readObject(), setMaxAngle(), and setMinAngle().
float FilterSlope::process (float x, float y, float transformValue, float & baseValue, TerrainGenerator * terrainGenerator) inline
Definition at line 101 of file FilterSlope.h.
References FilterProceduralRule::featheringAmount, max, and min.
void FilterSlope::setMaxAngle (float newAngle) inline
Definition at line 62 of file FilterSlope.h.
References defaultValue, maxAngle, and min.
Referenced by parseFromIffStream().
void FilterSlope::setMinAngle (float newAngle) inline
Definition at line 47 of file FilterSlope.h.
References defaultValue, max, and minAngle.
Referenced by parseFromIffStream().
Member Data Documentation
float FilterSlope::max private
Definition at line 19 of file FilterSlope.h.
Referenced by process(), and setMinAngle().
float FilterSlope::maxAngle private
Definition at line 20 of file FilterSlope.h.
Referenced by parseFromIffStream(), and setMaxAngle().
float FilterSlope::min private
Definition at line 21 of file FilterSlope.h.
Referenced by process(), and setMaxAngle().
float FilterSlope::minAngle private
Definition at line 18 of file FilterSlope.h.
Referenced by parseFromIffStream(), and setMinAngle().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/layer/filters/FilterSlope.h