Core3: server::zone::manager::ZoneManager Class Reference
server::zone::manager::ZoneManager Class Reference
#include <ZoneManager.h>
Public Member Functions
ZoneManager (const String &name)
void setZoneProcessor (ZoneProcessServer *server)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ZoneManager (DummyConstructorParameter *param)
virtual ~ZoneManager ()
Friends
class ZoneManagerHelper
Detailed Description
Definition at line 56 of file ZoneManager.h.
Constructor & Destructor Documentation
ZoneManager::ZoneManager (const String & name)
Definition at line 19 of file ZoneManager.cpp.
References server::zone::manager::ZoneManagerImplementation::_setStub().
ZoneManager::ZoneManager (DummyConstructorParameter * param) protected
Definition at line 26 of file ZoneManager.cpp.
ZoneManager::~ZoneManager () protected virtual
Definition at line 30 of file ZoneManager.cpp.
Member Function Documentation
DistributedObjectServant * ZoneManager::_getImplementation ()
Definition at line 49 of file ZoneManager.cpp.
Referenced by setZoneProcessor().
DistributedObjectServant * ZoneManager::_getImplementationForRead ()
Definition at line 55 of file ZoneManager.cpp.
void ZoneManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 59 of file ZoneManager.cpp.
void ZoneManager::setZoneProcessor (ZoneProcessServer * server)
Definition at line 35 of file ZoneManager.cpp.
References _getImplementation(), RPC_SETZONEPROCESSOR__ZONEPROCESSSERVER_, and server::zone::manager::ZoneManagerImplementation::setZoneProcessor().
Friends And Related Function Documentation
friend class ZoneManagerHelper friend
Definition at line 72 of file ZoneManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/ZoneManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/ZoneManager.cpp