Core3: ValidatedPosition Class Reference
ValidatedPosition Class Reference
#include <ValidatedPosition.h>
Public Member Functions
ValidatedPosition ()
ValidatedPosition (const Vector3 &pos)
ValidatedPosition (const ValidatedPosition &a)
ValidatedPosition & operator= (const ValidatedPosition &a)
Vector3 getWorldPosition (server::zone::ZoneServer *zoneServer)
void update (server::zone::objects::scene::SceneObject *object)
uint64 getParent ()
Vector3 getPosition ()
void setParent (uint64 par)
void setPosition (const Vector3 &pos)
void setPosition (float x, float z, float y)
void addSerVariables ()
Private Attributes
Vector3 point
uint64 parent
Detailed Description
Definition at line 25 of file ValidatedPosition.h.
Constructor & Destructor Documentation
ValidatedPosition::ValidatedPosition () inline
Definition at line 29 of file ValidatedPosition.h.
References addSerVariables(), and parent.
ValidatedPosition::ValidatedPosition (const Vector3 & pos) inline
Definition at line 35 of file ValidatedPosition.h.
References addSerVariables(), parent, and point.
ValidatedPosition::ValidatedPosition (const ValidatedPosition & a) inline
Definition at line 42 of file ValidatedPosition.h.
References addSerVariables(), parent, and point.
Member Function Documentation
void ValidatedPosition::addSerVariables () inline
Definition at line 80 of file ValidatedPosition.h.
References parent, and point.
Referenced by ValidatedPosition().
uint64 ValidatedPosition::getParent () inline
Definition at line 60 of file ValidatedPosition.h.
References parent.
Referenced by DataTransformCallback::bounceBack(), DataTransformWithParentCallback::bounceBack(), server::zone::managers::gcw::GCWManagerImplementation::canUseTerminals(), server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackFirstTest(), NpcConversationSelectCommand::doQueueCommand(), and NpcConversationStartCommand::doQueueCommand().
Vector3 ValidatedPosition::getPosition () inline
Definition at line 64 of file ValidatedPosition.h.
References point.
Referenced by DataTransformCallback::bounceBack(), DataTransformWithParentCallback::bounceBack(), and server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackFirstTest().
Vector3 ValidatedPosition::getWorldPosition (server::zone::ZoneServer * zoneServer)
Definition at line 23 of file ValidatedPosition.cpp.
References server::zone::ZoneServer::getObject(), parent, and point.
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackSecondTest(), NpcConversationStartCommand::doQueueCommand(), and NpcConversationSelectCommand::doQueueCommand().
ValidatedPosition& ValidatedPosition::operator= (const ValidatedPosition & a) inline
Definition at line 49 of file ValidatedPosition.h.
References parent, and point.
void ValidatedPosition::setParent (uint64 par) inline
Definition at line 68 of file ValidatedPosition.h.
References parent.
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackSecondTest().
void ValidatedPosition::setPosition (const Vector3 & pos) inline
Definition at line 72 of file ValidatedPosition.h.
References point.
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackSecondTest(), and ShipUpdateTransformCallback::run().
void ValidatedPosition::setPosition (float x, float z, float y) inline
Definition at line 76 of file ValidatedPosition.h.
References point.
void ValidatedPosition::update (server::zone::objects::scene::SceneObject * object)
Definition at line 12 of file ValidatedPosition.cpp.
References parent, and point.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), server::zone::objects::player::PlayerObjectImplementation::notifyLoadFromDatabase(), DataTransformCallback::updatePosition(), and DataTransformWithParentCallback::updatePosition().
Member Data Documentation
uint64 ValidatedPosition::parent private
Definition at line 27 of file ValidatedPosition.h.
Referenced by addSerVariables(), getParent(), getWorldPosition(), operator=(), setParent(), update(), and ValidatedPosition().
Vector3 ValidatedPosition::point private
Definition at line 26 of file ValidatedPosition.h.
Referenced by addSerVariables(), getPosition(), getWorldPosition(), operator=(), setPosition(), update(), and ValidatedPosition().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/ValidatedPosition.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/ValidatedPosition.cpp