Core3: server::zone::managers::director::PersistentEventAdapter Class Reference
server::zone::managers::director::PersistentEventAdapter Class Reference
#include <PersistentEvent.h>
Public Member Functions
PersistentEventAdapter (PersistentEvent *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int getTimeStamp ()
const String getKey ()
const String getScreenplay ()
SceneObject * getObject ()
int getCurTime ()
void setCurTime (int time)
void setTimeStamp (int stamp)
void setKey (const String &k)
void setScreenplay (const String &sp)
void setObject (SceneObject *o)
void notifyLoadFromDatabase ()
Detailed Description
Definition at line 154 of file PersistentEvent.h.
Constructor & Destructor Documentation
PersistentEventAdapter::PersistentEventAdapter (PersistentEvent * impl)
Definition at line 437 of file PersistentEvent.cpp.
Member Function Documentation
int PersistentEventAdapter::getCurTime ()
Definition at line 522 of file PersistentEvent.cpp.
Referenced by invokeMethod().
const String PersistentEventAdapter::getKey ()
Definition at line 510 of file PersistentEvent.cpp.
Referenced by invokeMethod().
SceneObject * PersistentEventAdapter::getObject ()
Definition at line 518 of file PersistentEvent.cpp.
Referenced by invokeMethod().
const String PersistentEventAdapter::getScreenplay ()
Definition at line 514 of file PersistentEvent.cpp.
Referenced by invokeMethod().
int PersistentEventAdapter::getTimeStamp ()
Definition at line 506 of file PersistentEvent.cpp.
Referenced by invokeMethod().
void PersistentEventAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 440 of file PersistentEvent.cpp.
References getCurTime(), getKey(), getObject(), getScreenplay(), getTimeStamp(), notifyLoadFromDatabase(), RPC_GETCURTIME__, RPC_GETKEY__, RPC_GETOBJECT__, RPC_GETSCREENPLAY__, RPC_GETTIMESTAMP__, RPC_NOTIFYLOADFROMDATABASE__, RPC_SETCURTIME__INT_, RPC_SETKEY__STRING_, RPC_SETOBJECT__SCENEOBJECT_, RPC_SETSCREENPLAY__STRING_, RPC_SETTIMESTAMP__INT_, setCurTime(), setKey(), setObject(), setScreenplay(), and setTimeStamp().
void PersistentEventAdapter::notifyLoadFromDatabase ()
Definition at line 546 of file PersistentEvent.cpp.
Referenced by invokeMethod().
void PersistentEventAdapter::setCurTime (int time)
Definition at line 526 of file PersistentEvent.cpp.
Referenced by invokeMethod().
void PersistentEventAdapter::setKey (const String & k)
Definition at line 534 of file PersistentEvent.cpp.
Referenced by invokeMethod().
void PersistentEventAdapter::setObject (SceneObject * o)
Definition at line 542 of file PersistentEvent.cpp.
Referenced by invokeMethod().
void PersistentEventAdapter::setScreenplay (const String & sp)
Definition at line 538 of file PersistentEvent.cpp.
Referenced by invokeMethod().
void PersistentEventAdapter::setTimeStamp (int stamp)
Definition at line 530 of file PersistentEvent.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/PersistentEvent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/PersistentEvent.cpp