Core3: server::zone::ZoneProcessServerAdapter Class Reference
server::zone::ZoneProcessServerAdapter Class Reference
#include <ZoneProcessServer.h>
Public Member Functions
ZoneProcessServerAdapter (ZoneProcessServer *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initialize ()
void finalize ()
ZoneServer * getZoneServer ()
PlayerManager * getPlayerManager ()
ChatManager * getChatManager ()
FishingManager * getFishingManager ()
GamblingManager * getGamblingManager ()
ForageManager * getForageManager ()
Detailed Description
Definition at line 370 of file ZoneProcessServer.h.
Constructor & Destructor Documentation
ZoneProcessServerAdapter::ZoneProcessServerAdapter (ZoneProcessServer * impl)
Definition at line 416 of file ZoneProcessServer.cpp.
Member Function Documentation
void ZoneProcessServerAdapter::finalize ()
Definition at line 472 of file ZoneProcessServer.cpp.
Referenced by invokeMethod().
ChatManager * ZoneProcessServerAdapter::getChatManager ()
Definition at line 484 of file ZoneProcessServer.cpp.
Referenced by invokeMethod().
FishingManager * ZoneProcessServerAdapter::getFishingManager ()
Definition at line 488 of file ZoneProcessServer.cpp.
Referenced by invokeMethod().
ForageManager * ZoneProcessServerAdapter::getForageManager ()
Definition at line 496 of file ZoneProcessServer.cpp.
Referenced by invokeMethod().
GamblingManager * ZoneProcessServerAdapter::getGamblingManager ()
Definition at line 492 of file ZoneProcessServer.cpp.
Referenced by invokeMethod().
PlayerManager * ZoneProcessServerAdapter::getPlayerManager ()
Definition at line 480 of file ZoneProcessServer.cpp.
Referenced by invokeMethod().
ZoneServer * ZoneProcessServerAdapter::getZoneServer ()
Definition at line 476 of file ZoneProcessServer.cpp.
Referenced by invokeMethod().
void ZoneProcessServerAdapter::initialize ()
Definition at line 468 of file ZoneProcessServer.cpp.
Referenced by invokeMethod().
void ZoneProcessServerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 419 of file ZoneProcessServer.cpp.
References finalize(), getChatManager(), getFishingManager(), getForageManager(), getGamblingManager(), getPlayerManager(), getZoneServer(), initialize(), RPC_FINALIZE__, RPC_GETCHATMANAGER__, RPC_GETFISHINGMANAGER__, RPC_GETFORAGEMANAGER__, RPC_GETGAMBLINGMANAGER__, RPC_GETPLAYERMANAGER__, RPC_GETZONESERVER__, and RPC_INITIALIZE__.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneProcessServer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneProcessServer.cpp