Core3: server::zone::managers::guild::GuildManagerImplementation Class Reference
server::zone::managers::guild::GuildManagerImplementation Class Reference
#include <GuildManager.h>
Public Member Functions
GuildManagerImplementation (ZoneServer *serv, ZoneProcessServer *proc)
GuildManagerImplementation (DummyConstructorParameter *param)
void setChatManager (ChatManager *chatmanager)
void sendGuildListTo (CreatureObject *player, const String &guildFilter)
void addPendingGuild (unsigned long long playerID, const String &guildName)
void removePendingGuild (unsigned long long playerID)
String getPendingGuildName (unsigned long long playerID)
void addSponsoredPlayer (unsigned long long playerID, GuildObject *guild)
void removeSponsoredPlayer (unsigned long long playerID)
bool isCreatingGuild (unsigned long long playerID)
bool isSponsoredPlayer (unsigned long long playerID)
GuildObject * getSponsoredGuild (unsigned long long playerID)
void sendBaselinesTo (CreatureObject *player)
void loadGuilds ()
void sendGuildCreateNameTo (CreatureObject *player, GuildTerminal *guildTerminal)
void sendGuildCreateAbbrevTo (CreatureObject *player, GuildTerminal *guildTerminal)
void sendGuildInformationTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildMemberListTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildMemberOptionsTo (CreatureObject *player, GuildObject *guild, unsigned long long memberID, GuildTerminal *guildTerminal)
void sendGuildDisbandConfirmTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildSponsoredListTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildSponsoredOptionsTo (CreatureObject *player, GuildObject *guild, unsigned long long playerID, GuildTerminal *guildTerminal)
void sendGuildSponsorTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildSponsorVerifyTo (CreatureObject *player, CreatureObject *target)
void sendGuildKickPromptTo (CreatureObject *player, CreatureObject *target)
void sendGuildSetTitleTo (CreatureObject *player, CreatureObject *target)
void sendGuildWarStatusTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void promptAddNewEnemy (CreatureObject *player, GuildObject *guild, SceneObject *terminal)
void toggleWarStatus (CreatureObject *player, GuildObject *guild, unsigned long long guildoid)
void declareWarByName (CreatureObject *player, GuildObject *guild, const String &search)
void updateWarStatusToWaringGuild (GuildObject *guild, GuildObject *waringGuild)
void sendMemberPermissionsTo (CreatureObject *player, unsigned long long targetID, GuildTerminal *guildTerminal)
bool validateGuildName (CreatureObject *player, const String &guildName)
bool validateGuildAbbrev (CreatureObject *player, const String &guildAbbrev)
bool guildNameExists (const String &guildName)
bool guildAbbrevExists (const String &guildAbbrev)
GuildObject * createGuild (CreatureObject *player, GuildTerminal *guildTerminal, const String &guildName, const String &guildAbbrev)
bool disbandGuild (CreatureObject *player, GuildObject *guild)
void sponsorPlayer (CreatureObject *player, GuildTerminal *guildTerminal, const String &playerName)
void acceptSponsorshipRequest (CreatureObject *player, CreatureObject *target)
void acceptSponsoredPlayer (CreatureObject *player, unsigned long long targetID)
void kickMember (CreatureObject *player, CreatureObject *target)
void leaveGuild (CreatureObject *player, GuildObject *guild)
void setMemberTitle (CreatureObject *player, CreatureObject *target, const String &title)
void setAllegianceTo (CreatureObject *player, unsigned long long targetID, GuildTerminal *guildTerminal)
void toggleGuildPermission (CreatureObject *player, unsigned long long targetID, int permissionIndex, GuildTerminal *guildTerminal)
ChatRoom * createGuildChannels (GuildObject *guild)
void sendGuildTransferTo (CreatureObject *player, GuildTerminal *guildTerminal)
void sendTransferAckTo (CreatureObject *player, const String &newOwnerName, SceneObject *guildTerminal)
void transferLeadership (CreatureObject *newOwner, CreatureObject *oldOwner, SceneObject *guildTerminal)
void sendAcceptLotsTo (CreatureObject *newOwner, GuildTerminal *guildTerminal)
void transferGuildHall (CreatureObject *newOwner, SceneObject *guildTerminal)
void sendGuildMail (const String &subject, StringIdChatParameter &body, GuildObject *guild)
GuildObject * getGuildFromAbbrev (const String &guildAbbrev)
operator const GuildManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< GuildManager * > _this
Protected Member Functions
virtual ~GuildManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
ManagedReference< ZoneServer * > server
ManagedReference
< ZoneProcessServer * > processor
ManagedReference< ChatManager * > chatManager
DeltaSet< String,
ManagedReference< GuildObject * > > guildList
VectorMap< unsigned long long,
String > pendingGuilds
VectorMap< unsigned long long,
ManagedReference< GuildObject * > > sponsoredPlayers
int requiredMembers
int maximumMembers
int guildUpdateInterval
Friends
class GuildManager
Detailed Description
Definition at line 250 of file GuildManager.h.
Constructor & Destructor Documentation
GuildManagerImplementation::GuildManagerImplementation (ZoneServer * serv, ZoneProcessServer * proc)
Definition at line 1008 of file GuildManager.cpp.
References _initializeImplementation(), guildUpdateInterval, maximumMembers, pendingGuilds, processor, requiredMembers, server, and sponsoredPlayers.
GuildManagerImplementation::GuildManagerImplementation (DummyConstructorParameter * param)
Definition at line 846 of file GuildManager.cpp.
References _initializeImplementation().
GuildManagerImplementation::~GuildManagerImplementation () protected virtual
Definition at line 851 of file GuildManager.cpp.
Member Function Documentation
DistributedObjectStub * GuildManagerImplementation::_getStub ()
Definition at line 871 of file GuildManager.cpp.
References _this.
void GuildManagerImplementation::_initializeImplementation () protected
Definition at line 858 of file GuildManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by GuildManagerImplementation().
void GuildManagerImplementation::_serializationHelperMethod () protected
Definition at line 907 of file GuildManager.cpp.
Referenced by _initializeImplementation().
void GuildManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 866 of file GuildManager.cpp.
References _this.
Referenced by server::zone::managers::guild::GuildManager::GuildManager().
void GuildManagerImplementation::acceptSponsoredPlayer (CreatureObject * player, unsigned long long targetID)
Definition at line 885 of file GuildManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), chatManager, DeltaMessage::close(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getGuildObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::isInGuild(), server::zone::objects::creature::CreatureObject::isOnline(), sendGuildMail(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::zone::objects::creature::CreatureObject::setGuildObject(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTT(), server::chat::StringIdChatParameter::setTU(), and CreatureObjectDeltaMessage6::updateGuildID().
Referenced by server::zone::managers::guild::GuildManager::acceptSponsoredPlayer().
void GuildManagerImplementation::acceptSponsorshipRequest (CreatureObject * player, CreatureObject * target)
Definition at line 853 of file GuildManagerImplementation.cpp.
References addSponsoredPlayer(), server::zone::objects::scene::variables::StringId::clear(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getGuildObject(), server::zone::objects::scene::SceneObject::getObjectID(), sendGuildMail(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTT(), and server::chat::StringIdChatParameter::setTU().
Referenced by server::zone::managers::guild::GuildManager::acceptSponsorshipRequest().
void GuildManagerImplementation::addPendingGuild (unsigned long long playerID, const String & guildName)
Definition at line 1039 of file GuildManager.cpp.
References _this, and pendingGuilds.
Referenced by server::zone::managers::guild::GuildManager::addPendingGuild().
void GuildManagerImplementation::addSponsoredPlayer (unsigned long long playerID, GuildObject * guild)
Definition at line 1057 of file GuildManager.cpp.
References _this, and sponsoredPlayers.
Referenced by acceptSponsorshipRequest(), server::zone::managers::guild::GuildManager::addSponsoredPlayer(), and loadGuilds().
GuildObject * GuildManagerImplementation::createGuild (CreatureObject * player, GuildTerminal * guildTerminal, const String & guildName, const String & guildAbbrev)
Definition at line 640 of file GuildManagerImplementation.cpp.
References _this, DeltaSet< K, V >::add(), server::zone::objects::scene::SceneObject::broadcastMessage(), chatManager, DeltaMessage::close(), createGuildChannels(), server::zone::objects::scene::SceneObject::getObjectID(), guildList, isCreatingGuild(), server::zone::objects::creature::CreatureObject::isInGuild(), removePendingGuild(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::guild::GuildMemberInfo::setDeclaredAllegiance(), server::zone::objects::tangible::terminal::guild::GuildTerminal::setGuildObject(), server::zone::objects::creature::CreatureObject::setGuildObject(), server::zone::objects::guild::GuildMemberInfo::setPermissions(), DeltaMessage::startUpdate(), and CreatureObjectDeltaMessage6::updateGuildID().
Referenced by server::zone::managers::guild::GuildManager::createGuild().
ChatRoom * GuildManagerImplementation::createGuildChannels (GuildObject * guild)
Definition at line 623 of file GuildManagerImplementation.cpp.
References chatManager, server::zone::objects::guild::GuildObject::getGuildID(), and server::zone::objects::guild::GuildObject::setChatRoom().
Referenced by createGuild(), server::zone::managers::guild::GuildManager::createGuildChannels(), and loadGuilds().
void GuildManagerImplementation::declareWarByName (CreatureObject * player, GuildObject * guild, const String & search)
Definition at line 1388 of file GuildManagerImplementation.cpp.
References _this, DeltaSet< K, V >::get(), server::zone::objects::scene::SceneObject::getObjectID(), DeltaSet< K, V >::getValueAt(), guildList, server::zone::objects::creature::CreatureObject::sendSystemMessage(), DeltaSet< K, V >::size(), and toggleWarStatus().
Referenced by server::zone::managers::guild::GuildManager::declareWarByName().
bool GuildManagerImplementation::disbandGuild (CreatureObject * player, GuildObject * guild)
Definition at line 696 of file GuildManagerImplementation.cpp.
References _this, server::zone::objects::scene::SceneObject::broadcastMessage(), chatManager, DeltaMessage::close(), DeltaSet< K, V >::contains(), server::zone::objects::scene::SceneObject::destroyObjectFromDatabase(), DeltaSet< K, V >::drop(), DeltaSet< K, V >::get(), server::zone::objects::guild::GuildObject::getChatRoom(), server::zone::objects::guild::GuildObject::getGuildAbbrev(), server::zone::objects::guild::GuildObject::getGuildKey(), server::zone::objects::guild::GuildObject::getGuildMemberList(), server::zone::objects::guild::GuildObject::getGuildName(), DeltaSet< K, V >::getKeyAt(), server::zone::objects::scene::SceneObject::getObjectID(), server::chat::room::ChatRoom::getParent(), server::zone::objects::guild::GuildObject::getSponsoredPlayer(), server::zone::objects::guild::GuildObject::getSponsoredPlayerCount(), guildList, server::zone::objects::guild::GuildObject::hasDisbandPermission(), server::zone::objects::creature::CreatureObject::isOnline(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::zone::objects::creature::CreatureObject::setGuildObject(), DeltaSet< K, V >::size(), sponsoredPlayers, DeltaMessage::startUpdate(), and CreatureObjectDeltaMessage6::updateGuildID().
Referenced by server::zone::managers::guild::GuildManager::disbandGuild().
void GuildManagerImplementation::finalize () protected
Definition at line 855 of file GuildManager.cpp.
GuildObject * GuildManagerImplementation::getGuildFromAbbrev (const String & guildAbbrev)
Definition at line 1430 of file GuildManagerImplementation.cpp.
References _this, DeltaSet< K, V >::getValueAt(), guildList, and DeltaSet< K, V >::size().
Referenced by server::zone::managers::guild::GuildManager::getGuildFromAbbrev().
String GuildManagerImplementation::getPendingGuildName (unsigned long long playerID)
Definition at line 1051 of file GuildManager.cpp.
References _this, and pendingGuilds.
Referenced by server::zone::managers::guild::GuildManager::getPendingGuildName().
GuildObject * GuildManagerImplementation::getSponsoredGuild (unsigned long long playerID)
Definition at line 1081 of file GuildManager.cpp.
References _this, and sponsoredPlayers.
Referenced by server::zone::managers::guild::GuildManager::getSponsoredGuild().
bool GuildManagerImplementation::guildAbbrevExists (const String & guildAbbrev)
Definition at line 172 of file GuildManagerImplementation.cpp.
References _this, DeltaSet< K, V >::get(), DeltaSet< K, V >::getKeyAt(), guildList, and DeltaSet< K, V >::size().
Referenced by server::zone::managers::guild::GuildManager::guildAbbrevExists(), and validateGuildAbbrev().
bool GuildManagerImplementation::guildNameExists (const String & guildName)
Definition at line 156 of file GuildManagerImplementation.cpp.
References _this, DeltaSet< K, V >::get(), DeltaSet< K, V >::getKeyAt(), guildList, and DeltaSet< K, V >::size().
Referenced by server::zone::managers::guild::GuildManager::guildNameExists(), and validateGuildName().
bool GuildManagerImplementation::isCreatingGuild (unsigned long long playerID)
Definition at line 1069 of file GuildManager.cpp.
References _this, and pendingGuilds.
Referenced by createGuild(), and server::zone::managers::guild::GuildManager::isCreatingGuild().
bool GuildManagerImplementation::isSponsoredPlayer (unsigned long long playerID)
Definition at line 1075 of file GuildManager.cpp.
References _this, and sponsoredPlayers.
Referenced by server::zone::managers::guild::GuildManager::isSponsoredPlayer().
void GuildManagerImplementation::kickMember (CreatureObject * player, CreatureObject * target)
Definition at line 978 of file GuildManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), DeltaMessage::close(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getGuildObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::isOnline(), sendGuildMail(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setGuildObject(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTT(), server::chat::StringIdChatParameter::setTU(), and CreatureObjectDeltaMessage6::updateGuildID().
Referenced by server::zone::managers::guild::GuildManager::kickMember().
void GuildManagerImplementation::leaveGuild (CreatureObject * player, GuildObject * guild)
Definition at line 1214 of file GuildManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), DeltaMessage::close(), server::zone::objects::guild::GuildObject::getChatRoom(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::guild::GuildObject::getGuildName(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::guild::GuildObject::removeMember(), server::chat::room::ChatRoom::removePlayer(), sendGuildMail(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setGuildObject(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTU(), and CreatureObjectDeltaMessage6::updateGuildID().
Referenced by server::zone::managers::guild::GuildManager::leaveGuild().
void GuildManagerImplementation::loadGuilds ()
Definition at line 62 of file GuildManagerImplementation.cpp.
References _this, DeltaSet< K, V >::add(), addSponsoredPlayer(), chatManager, createGuildChannels(), server::zone::objects::guild::GuildObject::getGuildKey(), server::zone::objects::guild::GuildObject::getSponsoredPlayer(), server::zone::objects::guild::GuildObject::getSponsoredPlayerCount(), guildList, removeSponsoredPlayer(), server, DeltaSet< K, V >::size(), and sponsoredPlayers.
Referenced by server::zone::managers::guild::GuildManager::loadGuilds().
void GuildManagerImplementation::lock (bool doLock = true) protected
Definition at line 879 of file GuildManager.cpp.
References _this.
void GuildManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 883 of file GuildManager.cpp.
References _this.
GuildManagerImplementation::operator const GuildManager * ()
Definition at line 875 of file GuildManager.cpp.
void GuildManagerImplementation::promptAddNewEnemy (CreatureObject * player, GuildObject * guild, SceneObject * terminal)
Definition at line 1310 of file GuildManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_WAR_ENTER_NAME, server::zone::objects::guild::GuildObject::hasWarPermission(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::promptAddNewEnemy().
void GuildManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 914 of file GuildManager.cpp.
References readObjectMember().
bool GuildManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 933 of file GuildManager.cpp.
References guildList, guildUpdateInterval, maximumMembers, and requiredMembers.
Referenced by readObject().
void GuildManagerImplementation::removePendingGuild (unsigned long long playerID)
Definition at line 1045 of file GuildManager.cpp.
References _this, and pendingGuilds.
Referenced by createGuild(), and server::zone::managers::guild::GuildManager::removePendingGuild().
void GuildManagerImplementation::removeSponsoredPlayer (unsigned long long playerID)
Definition at line 1063 of file GuildManager.cpp.
References _this, and sponsoredPlayers.
Referenced by loadGuilds(), and server::zone::managers::guild::GuildManager::removeSponsoredPlayer().
void GuildManagerImplementation::rlock (bool doLock = true) protected
Definition at line 887 of file GuildManager.cpp.
References _this.
void GuildManagerImplementation::runlock (bool doLock = true) protected
Definition at line 903 of file GuildManager.cpp.
References _this.
void GuildManagerImplementation::sendAcceptLotsTo (CreatureObject * newOwner, GuildTerminal * guildTerminal)
Definition at line 387 of file GuildManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_TAKE_LOTS, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendAcceptLotsTo().
void GuildManagerImplementation::sendBaselinesTo (CreatureObject * player)
Definition at line 590 of file GuildManagerImplementation.cpp.
References _this, server::zone::objects::creature::CreatureObject::getGuildObject(), guildList, and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::managers::guild::GuildManager::sendBaselinesTo().
void GuildManagerImplementation::sendGuildCreateAbbrevTo (CreatureObject * player, GuildTerminal * guildTerminal)
Definition at line 188 of file GuildManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_CREATE_ABBREV, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildCreateAbbrevTo().
void GuildManagerImplementation::sendGuildCreateNameTo (CreatureObject * player, GuildTerminal * guildTerminal)
Definition at line 113 of file GuildManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_CREATE_NAME, server::zone::objects::creature::CreatureObject::isInGuild(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildCreateNameTo().
void GuildManagerImplementation::sendGuildDisbandConfirmTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 251 of file GuildManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_DISBAND, server::zone::objects::guild::GuildObject::hasDisbandPermission(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildDisbandConfirmTo().
void GuildManagerImplementation::sendGuildInformationTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 224 of file GuildManagerImplementation.cpp.
References server::zone::objects::guild::GuildObject::getGuildAbbrev(), server::zone::objects::guild::GuildObject::getGuildLeaderID(), server::zone::objects::guild::GuildObject::getGuildName(), server::zone::objects::guild::GuildObject::getTotalMembers(), server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildInformationTo(), and sendGuildListTo().
void GuildManagerImplementation::sendGuildKickPromptTo (CreatureObject * player, CreatureObject * target)
Definition at line 944 of file GuildManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_MEMBER_REMOVE, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildKickPromptTo().
void GuildManagerImplementation::sendGuildListTo (CreatureObject * player, const String & guildFilter)
Definition at line 1163 of file GuildManagerImplementation.cpp.
References _this, SuiWindowType::ADMIN_GUILDLIST, DeltaSet< K, V >::get(), DeltaSet< K, V >::getKeyAt(), server::zone::objects::creature::CreatureObject::getPlayerObject(), guildList, sendGuildInformationTo(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, and DeltaSet< K, V >::size().
Referenced by server::zone::managers::guild::GuildManager::sendGuildListTo().
void GuildManagerImplementation::sendGuildMail (const String & subject, StringIdChatParameter & body, GuildObject * guild)
Definition at line 1244 of file GuildManagerImplementation.cpp.
References chatManager, server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::guild::GuildObject::getGuildMemberList(), server::zone::objects::guild::GuildObject::getGuildName(), server::zone::objects::guild::GuildMemberInfo::getPlayerID(), and server.
Referenced by acceptSponsoredPlayer(), acceptSponsorshipRequest(), kickMember(), leaveGuild(), and server::zone::managers::guild::GuildManager::sendGuildMail().
void GuildManagerImplementation::sendGuildMemberListTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 477 of file GuildManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::guild::GuildObject::getGuildMemberList(), server::zone::objects::guild::GuildMemberInfo::getPlayerID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_MEMBER_LIST, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildMemberListTo().
void GuildManagerImplementation::sendGuildMemberOptionsTo (CreatureObject * player, GuildObject * guild, unsigned long long memberID, GuildTerminal * guildTerminal)
Definition at line 274 of file GuildManagerImplementation.cpp.
References server::zone::objects::guild::GuildObject::getGuildLeaderID(), server::zone::objects::guild::GuildObject::getGuildMemberList(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_MEMBER_OPTIONS, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildMemberOptionsTo().
void GuildManagerImplementation::sendGuildSetTitleTo (CreatureObject * player, CreatureObject * target)
Definition at line 958 of file GuildManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getGuildObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_MEMBER_TITLE, server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildSetTitleTo().
void GuildManagerImplementation::sendGuildSponsoredListTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 538 of file GuildManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::guild::GuildObject::getSponsoredPlayer(), server::zone::objects::guild::GuildObject::getSponsoredPlayerCount(), SuiWindowType::GUILD_SPONSORED_LIST, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildSponsoredListTo().
void GuildManagerImplementation::sendGuildSponsoredOptionsTo (CreatureObject * player, GuildObject * guild, unsigned long long playerID, GuildTerminal * guildTerminal)
Definition at line 512 of file GuildManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_SPONSORED_OPTIONS, server::zone::objects::guild::GuildObject::hasAcceptPermission(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildSponsoredOptionsTo().
void GuildManagerImplementation::sendGuildSponsorTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 568 of file GuildManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_SPONSOR, server::zone::objects::guild::GuildObject::hasSponsorPermission(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildSponsorTo().
void GuildManagerImplementation::sendGuildSponsorVerifyTo (CreatureObject * player, CreatureObject * target)
Definition at line 840 of file GuildManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_SPONSOR_VERIFY, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildSponsorVerifyTo(), and sponsorPlayer().
void GuildManagerImplementation::sendGuildTransferTo (CreatureObject * player, GuildTerminal * guildTerminal)
Definition at line 313 of file GuildManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_TRANSFER_LEADER, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildTransferTo().
void GuildManagerImplementation::sendGuildWarStatusTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 1270 of file GuildManagerImplementation.cpp.
References server::zone::objects::guild::GuildObject::getGuildAbbrev(), server::zone::objects::guild::GuildObject::getGuildName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::guild::GuildObject::getWaringGuilds(), SuiWindowType::GUILD_WAR_LIST, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendGuildWarStatusTo().
void GuildManagerImplementation::sendMemberPermissionsTo (CreatureObject * player, unsigned long long targetID, GuildTerminal * guildTerminal)
Definition at line 1070 of file GuildManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getGuildObject(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::GUILD_MEMBER_PERMISSIONS, server::zone::objects::guild::GuildMemberInfo::hasPermission(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server.
Referenced by server::zone::managers::guild::GuildManager::sendMemberPermissionsTo(), and toggleGuildPermission().
void GuildManagerImplementation::sendTransferAckTo (CreatureObject * player, const String & newOwnerName, SceneObject * guildTerminal)
Definition at line 329 of file GuildManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getGuildObject(), SuiWindowType::GUILD_TRANSFER_LEADER_CONFIRM, server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, and server::chat::StringIdChatParameter::setTO().
Referenced by server::zone::managers::guild::GuildManager::sendTransferAckTo().
void GuildManagerImplementation::setAllegianceTo (CreatureObject * player, unsigned long long targetID, GuildTerminal * guildTerminal)
Definition at line 1066 of file GuildManagerImplementation.cpp.
Referenced by server::zone::managers::guild::GuildManager::setAllegianceTo().
void GuildManagerImplementation::setChatManager (ChatManager * chatmanager)
Definition at line 1034 of file GuildManager.cpp.
References chatManager.
Referenced by server::zone::managers::guild::GuildManager::setChatManager().
void GuildManagerImplementation::setMemberTitle (CreatureObject * player, CreatureObject * target, const String & title)
Definition at line 1029 of file GuildManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getGuildObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::isOnline(), processor, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::guild::GuildMemberInfo::setGuildTitle(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTT(), server::chat::StringIdChatParameter::setTU(), and server::zone::managers::name::NameManager::validateName().
Referenced by server::zone::managers::guild::GuildManager::setMemberTitle().
void GuildManagerImplementation::sponsorPlayer (CreatureObject * player, GuildTerminal * guildTerminal, const String & playerName)
Definition at line 795 of file GuildManagerImplementation.cpp.
References server::zone::objects::tangible::terminal::guild::GuildTerminal::getGuildObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::isInRange(), maximumMembers, sendGuildSponsorVerifyTo(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTT(), and server::chat::StringIdChatParameter::setTU().
Referenced by server::zone::managers::guild::GuildManager::sponsorPlayer().
void GuildManagerImplementation::toggleGuildPermission (CreatureObject * player, unsigned long long targetID, int permissionIndex, GuildTerminal * guildTerminal)
Definition at line 1106 of file GuildManagerImplementation.cpp.
References server::zone::objects::tangible::terminal::guild::GuildTerminal::getGuildObject(), server::zone::objects::scene::SceneObject::getObjectID(), sendMemberPermissionsTo(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::objects::guild::GuildMemberInfo::togglePermission().
Referenced by server::zone::managers::guild::GuildManager::toggleGuildPermission().
void GuildManagerImplementation::toggleWarStatus (CreatureObject * player, GuildObject * guild, unsigned long long guildoid)
Definition at line 1332 of file GuildManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::guild::GuildObject::hasDeclaredWarBy(), server::zone::objects::guild::GuildObject::hasDeclaredWarOn(), server::zone::objects::guild::GuildObject::hasWarPermission(), server::zone::objects::guild::GuildObject::isAtWarWith(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::zone::objects::guild::GuildObject::setWarStatus(), and updateWarStatusToWaringGuild().
Referenced by declareWarByName(), and server::zone::managers::guild::GuildManager::toggleWarStatus().
void GuildManagerImplementation::transferGuildHall (CreatureObject * newOwner, SceneObject * guildTerminal)
Definition at line 438 of file GuildManagerImplementation.cpp.
References SceneObjectType::BUILDING, TransferstructureCommand::doTransferStructure(), server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::tangible::terminal::Terminal::isGuildTerminal(), server::zone::objects::scene::SceneObject::isTerminal(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::guild::GuildManager::transferGuildHall().
void GuildManagerImplementation::transferLeadership (CreatureObject * newOwner, CreatureObject * oldOwner, SceneObject * guildTerminal)
Definition at line 408 of file GuildManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getGuildObject(), server::zone::objects::guild::GuildObject::getMember(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::guild::GuildObject::setGuildLeaderID(), and server::zone::objects::guild::GuildMemberInfo::setPermissions().
Referenced by server::zone::managers::guild::GuildManager::transferLeadership().
void GuildManagerImplementation::unlock (bool doLock = true) protected
Definition at line 899 of file GuildManager.cpp.
References _this.
void GuildManagerImplementation::updateWarStatusToWaringGuild (GuildObject * guild, GuildObject * waringGuild)
Definition at line 1425 of file GuildManagerImplementation.cpp.
References server.
Referenced by toggleWarStatus(), and server::zone::managers::guild::GuildManager::updateWarStatusToWaringGuild().
bool GuildManagerImplementation::validateGuildAbbrev (CreatureObject * player, const String & guildAbbrev)
Definition at line 200 of file GuildManagerImplementation.cpp.
References guildAbbrevExists(), processor, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::managers::name::NameManager::validateName().
Referenced by server::zone::managers::guild::GuildManager::validateGuildAbbrev().
bool GuildManagerImplementation::validateGuildName (CreatureObject * player, const String & guildName)
Definition at line 130 of file GuildManagerImplementation.cpp.
References guildNameExists(), processor, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::managers::name::NameManager::validateName().
Referenced by server::zone::managers::guild::GuildManager::validateGuildName().
void GuildManagerImplementation::wlock (bool doLock = true) protected
Definition at line 891 of file GuildManager.cpp.
References _this.
void GuildManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 895 of file GuildManager.cpp.
References _this.
void GuildManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 959 of file GuildManager.cpp.
References writeObjectMembers().
int GuildManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 966 of file GuildManager.cpp.
References guildList, guildUpdateInterval, maximumMembers, and requiredMembers.
Referenced by writeObject().
Friends And Related Function Documentation
friend class GuildManager friend
Definition at line 412 of file GuildManager.h.
Member Data Documentation
WeakReference<GuildManager*> server::zone::managers::guild::GuildManagerImplementation::_this
Definition at line 378 of file GuildManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addPendingGuild(), addSponsoredPlayer(), createGuild(), declareWarByName(), disbandGuild(), getGuildFromAbbrev(), getPendingGuildName(), getSponsoredGuild(), guildAbbrevExists(), guildNameExists(), isCreatingGuild(), isSponsoredPlayer(), loadGuilds(), lock(), removePendingGuild(), removeSponsoredPlayer(), rlock(), runlock(), sendBaselinesTo(), sendGuildListTo(), unlock(), and wlock().
ManagedReference<ChatManager* > server::zone::managers::guild::GuildManagerImplementation::chatManager private
Definition at line 255 of file GuildManager.h.
Referenced by acceptSponsoredPlayer(), createGuild(), createGuildChannels(), disbandGuild(), loadGuilds(), sendGuildMail(), and setChatManager().
DeltaSet<String, ManagedReference<GuildObject* > > server::zone::managers::guild::GuildManagerImplementation::guildList private
Definition at line 257 of file GuildManager.h.
Referenced by createGuild(), declareWarByName(), disbandGuild(), getGuildFromAbbrev(), guildAbbrevExists(), guildNameExists(), loadGuilds(), readObjectMember(), sendBaselinesTo(), sendGuildListTo(), and writeObjectMembers().
int server::zone::managers::guild::GuildManagerImplementation::guildUpdateInterval private
Definition at line 267 of file GuildManager.h.
Referenced by GuildManagerImplementation(), readObjectMember(), and writeObjectMembers().
int server::zone::managers::guild::GuildManagerImplementation::maximumMembers private
Definition at line 265 of file GuildManager.h.
Referenced by GuildManagerImplementation(), readObjectMember(), sponsorPlayer(), and writeObjectMembers().
VectorMap<unsigned long long, String> server::zone::managers::guild::GuildManagerImplementation::pendingGuilds private
Definition at line 259 of file GuildManager.h.
Referenced by addPendingGuild(), getPendingGuildName(), GuildManagerImplementation(), isCreatingGuild(), and removePendingGuild().
ManagedReference<ZoneProcessServer* > server::zone::managers::guild::GuildManagerImplementation::processor private
Definition at line 253 of file GuildManager.h.
Referenced by GuildManagerImplementation(), setMemberTitle(), validateGuildAbbrev(), and validateGuildName().
int server::zone::managers::guild::GuildManagerImplementation::requiredMembers private
Definition at line 263 of file GuildManager.h.
Referenced by GuildManagerImplementation(), readObjectMember(), and writeObjectMembers().
ManagedReference<ZoneServer* > server::zone::managers::guild::GuildManagerImplementation::server private
Definition at line 251 of file GuildManager.h.
Referenced by acceptSponsoredPlayer(), disbandGuild(), GuildManagerImplementation(), loadGuilds(), promptAddNewEnemy(), sendAcceptLotsTo(), sendGuildCreateAbbrevTo(), sendGuildCreateNameTo(), sendGuildDisbandConfirmTo(), sendGuildInformationTo(), sendGuildKickPromptTo(), sendGuildListTo(), sendGuildMail(), sendGuildMemberListTo(), sendGuildMemberOptionsTo(), sendGuildSetTitleTo(), sendGuildSponsoredListTo(), sendGuildSponsoredOptionsTo(), sendGuildSponsorTo(), sendGuildSponsorVerifyTo(), sendGuildTransferTo(), sendGuildWarStatusTo(), sendMemberPermissionsTo(), sendTransferAckTo(), sponsorPlayer(), toggleWarStatus(), and updateWarStatusToWaringGuild().
VectorMap<unsigned long long, ManagedReference<GuildObject* > > server::zone::managers::guild::GuildManagerImplementation::sponsoredPlayers private
Definition at line 261 of file GuildManager.h.
Referenced by addSponsoredPlayer(), disbandGuild(), getSponsoredGuild(), GuildManagerImplementation(), isSponsoredPlayer(), loadGuilds(), and removeSponsoredPlayer().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/guild/GuildManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/guild/GuildManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/guild/GuildManagerImplementation.cpp