Core3: server::zone::objects::player::EntertainingObserverImplementation Class Reference
server::zone::objects::player::EntertainingObserverImplementation Class Reference
#include <EntertainingObserver.h>
Public Member Functions
EntertainingObserverImplementation ()
EntertainingObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const EntertainingObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< EntertainingObserver * > _this
Protected Member Functions
virtual ~EntertainingObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class EntertainingObserver
Detailed Description
Definition at line 82 of file EntertainingObserver.h.
Constructor & Destructor Documentation
EntertainingObserverImplementation::EntertainingObserverImplementation ()
Definition at line 180 of file EntertainingObserver.cpp.
References _initializeImplementation().
EntertainingObserverImplementation::EntertainingObserverImplementation (DummyConstructorParameter * param)
Definition at line 66 of file EntertainingObserver.cpp.
References _initializeImplementation().
EntertainingObserverImplementation::~EntertainingObserverImplementation () protected virtual
Definition at line 71 of file EntertainingObserver.cpp.
Member Function Documentation
DistributedObjectStub * EntertainingObserverImplementation::_getStub ()
Definition at line 91 of file EntertainingObserver.cpp.
References _this.
void EntertainingObserverImplementation::_initializeImplementation () protected
Definition at line 78 of file EntertainingObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by EntertainingObserverImplementation().
void EntertainingObserverImplementation::_serializationHelperMethod () protected
Definition at line 127 of file EntertainingObserver.cpp.
Referenced by _initializeImplementation().
void EntertainingObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 86 of file EntertainingObserver.cpp.
References _this.
Referenced by server::zone::objects::player::EntertainingObserver::EntertainingObserver().
void EntertainingObserverImplementation::finalize () protected
Definition at line 75 of file EntertainingObserver.cpp.
void EntertainingObserverImplementation::lock (bool doLock = true) protected
Definition at line 99 of file EntertainingObserver.cpp.
References _this.
void EntertainingObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 103 of file EntertainingObserver.cpp.
References _this.
int EntertainingObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 185 of file EntertainingObserver.cpp.
References ObserverEventType::POSTURECHANGED.
Referenced by server::zone::objects::player::EntertainingObserver::notifyObserverEvent().
EntertainingObserverImplementation::operator const EntertainingObserver * ()
Definition at line 95 of file EntertainingObserver.cpp.
void EntertainingObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 134 of file EntertainingObserver.cpp.
References readObjectMember().
bool EntertainingObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 153 of file EntertainingObserver.cpp.
Referenced by readObject().
void EntertainingObserverImplementation::rlock (bool doLock = true) protected
Definition at line 107 of file EntertainingObserver.cpp.
References _this.
void EntertainingObserverImplementation::runlock (bool doLock = true) protected
Definition at line 123 of file EntertainingObserver.cpp.
References _this.
void EntertainingObserverImplementation::unlock (bool doLock = true) protected
Definition at line 119 of file EntertainingObserver.cpp.
References _this.
void EntertainingObserverImplementation::wlock (bool doLock = true) protected
Definition at line 111 of file EntertainingObserver.cpp.
References _this.
void EntertainingObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 115 of file EntertainingObserver.cpp.
References _this.
void EntertainingObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 163 of file EntertainingObserver.cpp.
References writeObjectMembers().
int EntertainingObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 170 of file EntertainingObserver.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class EntertainingObserver friend
Definition at line 125 of file EntertainingObserver.h.
Member Data Documentation
WeakReference<EntertainingObserver*> server::zone::objects::player::EntertainingObserverImplementation::_this
Definition at line 91 of file EntertainingObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/EntertainingObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/EntertainingObserver.cpp