Core3: server::zone::objects::scene::SceneObjectAdapter Class Reference
server::zone::objects::scene::SceneObjectAdapter Class Reference
#include <SceneObject.h>
Public Member Functions
SceneObjectAdapter (SceneObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializePrivateData ()
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient, bool allowOverflow)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects)
void destroyObjectFromDatabase (bool destroyContainedObjects)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose)
void sendAttributeListTo (CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void openContainerTo (CreatureObject *player)
void closeContainerTo (CreatureObject *player, bool notify)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
unsigned long long getParentID ()
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
float getWorldPositionX ()
float getWorldPositionY ()
float getWorldPositionZ ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isDecoration ()
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZone (Zone *zone)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
bool containsChildObject (SceneObject *obj)
void createChildObjects ()
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
Detailed Description
Definition at line 2315 of file SceneObject.h.
Constructor & Destructor Documentation
SceneObjectAdapter::SceneObjectAdapter (SceneObject * impl)
Definition at line 5316 of file SceneObject.cpp.
Member Function Documentation
void SceneObjectAdapter::addActiveArea (ActiveArea * area)
Definition at line 6791 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::addActiveSession (unsigned int type, Facade * session)
Definition at line 6755 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::broadcastDestroy (SceneObject * object, bool sendSelf)
Definition at line 6715 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::broadcastDestroyPrivate (SceneObject * object, SceneObject * selfObject)
Definition at line 6719 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::broadcastMessage (BasePacket * message, bool sendSelf, bool lockZone)
Definition at line 6699 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::broadcastMessagePrivate (BasePacket * message, SceneObject * selfObject, bool lockZone)
Definition at line 6703 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::broadcastObject (SceneObject * object, bool sendSelf)
Definition at line 6707 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::broadcastObjectPrivate (SceneObject * object, SceneObject * selfObject)
Definition at line 6711 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::canAddObject (SceneObject * object, int containmentType, String & errorDescription)
Definition at line 6571 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::canBeDestroyed (CreatureObject * player)
Definition at line 6611 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::clearContainerDefaultAllowPermission (unsigned short perm)
Definition at line 7311 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::clearContainerDefaultDenyPermission (unsigned short perm)
Definition at line 7319 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::closeContainerTo (CreatureObject * player, bool notify)
Definition at line 6663 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::compareTo (SceneObject * obj)
Definition at line 6727 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::containsActiveSession (unsigned int type)
Definition at line 6759 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::containsChildObject (SceneObject * obj)
Definition at line 7431 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::containsPendingTask (const String & name)
Definition at line 6735 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::createChildObjects ()
Definition at line 7435 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::createComponents ()
Definition at line 6527 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::createContainerComponent ()
Definition at line 6531 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::destroyObjectFromDatabase (bool destroyContainedObjects)
Definition at line 6607 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::destroyObjectFromWorld (bool sendSelfDestroy)
Definition at line 6567 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::destroyPlayerCreatureFromDatabase (bool destroyContainedObjects)
Definition at line 6603 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::doSendToClient ()
Definition at line 7451 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::dropActiveArea (ActiveArea * area)
Definition at line 6795 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::dropActiveSession (unsigned int type)
Definition at line 6763 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::dropSlottedObject (const String & arrengementDescriptor)
Definition at line 6915 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::error (const String & msg)
Definition at line 6547 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::faceObject (SceneObject * obj)
Definition at line 7007 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::finalize ()
Definition at line 6519 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::getActiveAreasSize ()
Definition at line 6807 of file SceneObject.cpp.
Referenced by invokeMethod().
Reference< ActiveArea * > SceneObjectAdapter::getActiveRegion ()
Definition at line 6811 of file SceneObject.cpp.
Referenced by invokeMethod().
Reference< Facade * > SceneObjectAdapter::getActiveSession (unsigned int type)
Definition at line 6751 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::getActiveSessionsCount ()
Definition at line 6767 of file SceneObject.cpp.
Referenced by invokeMethod().
String SceneObjectAdapter::getArrangementDescriptor (int idx)
Definition at line 6883 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::getArrangementDescriptorSize ()
Definition at line 6879 of file SceneObject.cpp.
Referenced by invokeMethod().
ZoneClientSession * SceneObjectAdapter::getClient ()
Definition at line 6979 of file SceneObject.cpp.
Referenced by invokeMethod().
unsigned int SceneObjectAdapter::getClientGameObjectType ()
Definition at line 6987 of file SceneObject.cpp.
Referenced by invokeMethod().
unsigned int SceneObjectAdapter::getClientObjectCRC ()
Definition at line 6855 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::getContainedObjectsRecursive ()
Definition at line 6743 of file SceneObject.cpp.
Referenced by invokeMethod().
Reference< SceneObject * > SceneObjectAdapter::getContainerObject (int idx)
Definition at line 6939 of file SceneObject.cpp.
Referenced by invokeMethod().
Reference< SceneObject * > SceneObjectAdapter::getContainerObject (unsigned long long objectID)
Definition at line 6951 of file SceneObject.cpp.
Reference< SceneObject * > SceneObjectAdapter::getContainerObjectRecursive (unsigned long long oid)
Definition at line 6911 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::getContainerObjectsSize ()
Definition at line 6923 of file SceneObject.cpp.
Referenced by invokeMethod().
unsigned int SceneObjectAdapter::getContainerType ()
Definition at line 6975 of file SceneObject.cpp.
Referenced by invokeMethod().
unsigned int SceneObjectAdapter::getContainerVolumeLimit ()
Definition at line 6935 of file SceneObject.cpp.
Referenced by invokeMethod().
unsigned int SceneObjectAdapter::getContainmentType ()
Definition at line 6991 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::getCountableObjectsRecursive ()
Definition at line 6747 of file SceneObject.cpp.
Referenced by invokeMethod().
UnicodeString SceneObjectAdapter::getCustomObjectName ()
Definition at line 7051 of file SceneObject.cpp.
Referenced by invokeMethod().
float SceneObjectAdapter::getDirectionAngle ()
Definition at line 6995 of file SceneObject.cpp.
Referenced by invokeMethod().
float SceneObjectAdapter::getDirectionW ()
Definition at line 6851 of file SceneObject.cpp.
Referenced by invokeMethod().
float SceneObjectAdapter::getDirectionX ()
Definition at line 6839 of file SceneObject.cpp.
Referenced by invokeMethod().
float SceneObjectAdapter::getDirectionY ()
Definition at line 6847 of file SceneObject.cpp.
Referenced by invokeMethod().
float SceneObjectAdapter::getDirectionZ ()
Definition at line 6843 of file SceneObject.cpp.
Referenced by invokeMethod().
String SceneObjectAdapter::getDisplayedName ()
Definition at line 7447 of file SceneObject.cpp.
Referenced by invokeMethod().
float SceneObjectAdapter::getDistanceTo (SceneObject * object)
Definition at line 6775 of file SceneObject.cpp.
Referenced by invokeMethod().
unsigned int SceneObjectAdapter::getGameObjectType ()
Definition at line 6983 of file SceneObject.cpp.
Referenced by invokeMethod().
Zone * SceneObjectAdapter::getLocalZone ()
Definition at line 6819 of file SceneObject.cpp.
References server::zone::objects::scene::SceneObject::getLocalZone().
Referenced by invokeMethod().
String SceneObjectAdapter::getLoggingName ()
Definition at line 7055 of file SceneObject.cpp.
Referenced by invokeMethod().
unsigned int SceneObjectAdapter::getMovementCounter ()
Definition at line 7023 of file SceneObject.cpp.
Referenced by invokeMethod().
unsigned long long SceneObjectAdapter::getObjectID ()
Definition at line 6823 of file SceneObject.cpp.
Referenced by invokeMethod().
String SceneObjectAdapter::getObjectNameStringIdFile ()
Definition at line 6867 of file SceneObject.cpp.
Referenced by invokeMethod().
String SceneObjectAdapter::getObjectNameStringIdName ()
Definition at line 6871 of file SceneObject.cpp.
Referenced by invokeMethod().
ManagedWeakReference< SceneObject * > SceneObjectAdapter::getParent ()
Definition at line 7027 of file SceneObject.cpp.
Referenced by invokeMethod().
unsigned long long SceneObjectAdapter::getParentID ()
Definition at line 6731 of file SceneObject.cpp.
Referenced by invokeMethod().
ManagedWeakReference< SceneObject * > SceneObjectAdapter::getParentRecursively (unsigned int gameObjectType)
Definition at line 7043 of file SceneObject.cpp.
Referenced by invokeMethod().
unsigned int SceneObjectAdapter::getPlanetCRC ()
Definition at line 7383 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::getPlanetMapCategoryCRC ()
Definition at line 7423 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::getPlanetMapSubCategoryCRC ()
Definition at line 7427 of file SceneObject.cpp.
Referenced by invokeMethod().
ManagedWeakReference< SceneObject * > SceneObjectAdapter::getRootParent ()
Definition at line 7039 of file SceneObject.cpp.
Referenced by invokeMethod().
unsigned int SceneObjectAdapter::getServerObjectCRC ()
Definition at line 6859 of file SceneObject.cpp.
Referenced by invokeMethod().
String SceneObjectAdapter::getSlotDescriptor (int idx)
Definition at line 6887 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::getSlotDescriptorSize ()
Definition at line 6903 of file SceneObject.cpp.
Referenced by invokeMethod().
Reference< SceneObject * > SceneObjectAdapter::getSlottedObject (const String & slot)
Definition at line 6899 of file SceneObject.cpp.
Referenced by invokeMethod().
Reference< SceneObject * > SceneObjectAdapter::getSlottedObject (int idx)
Definition at line 6907 of file SceneObject.cpp.
int SceneObjectAdapter::getSlottedObjectsSize ()
Definition at line 6927 of file SceneObject.cpp.
Referenced by invokeMethod().
float SceneObjectAdapter::getSpecialDirectionAngle ()
Definition at line 6999 of file SceneObject.cpp.
Referenced by invokeMethod().
float SceneObjectAdapter::getWorldPositionX ()
Definition at line 6827 of file SceneObject.cpp.
Referenced by invokeMethod().
float SceneObjectAdapter::getWorldPositionY ()
Definition at line 6831 of file SceneObject.cpp.
Referenced by invokeMethod().
float SceneObjectAdapter::getWorldPositionZ ()
Definition at line 6835 of file SceneObject.cpp.
Referenced by invokeMethod().
Zone * SceneObjectAdapter::getZone ()
Definition at line 6815 of file SceneObject.cpp.
References server::zone::objects::scene::SceneObject::getZone().
Referenced by invokeMethod().
ZoneServer * SceneObjectAdapter::getZoneServer ()
Definition at line 7035 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::handleObjectMenuSelect (CreatureObject * player, byte selectedID)
Definition at line 6771 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::hasActiveArea (ActiveArea * area)
Definition at line 6799 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::hasActiveArea (unsigned long long objectid)
Definition at line 6803 of file SceneObject.cpp.
bool SceneObjectAdapter::hasArrangementDescriptor (const String & descr)
Definition at line 6895 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::hasFullContainerObjects ()
Definition at line 6931 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::hasObjectInContainer (unsigned long long objectID)
Definition at line 6943 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::hasObjectInSlottedContainer (SceneObject * object)
Definition at line 6947 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::hasSlotDescriptor (const String & descr)
Definition at line 6891 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::incrementMovementCounter ()
Definition at line 7367 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::info (const String & msg, bool forced)
Definition at line 6543 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::initializeChildObject (SceneObject * controllerObject)
Definition at line 7439 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::initializePrivateData ()
Definition at line 6523 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::initializeTransientMembers ()
Definition at line 6535 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::inRangeObjects (unsigned int gameObjectType, float range)
Definition at line 6551 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 5319 of file SceneObject.cpp.
References addActiveArea(), addActiveSession(), broadcastDestroy(), broadcastDestroyPrivate(), broadcastMessage(), broadcastMessagePrivate(), broadcastObject(), broadcastObjectPrivate(), canAddObject(), canBeDestroyed(), clearContainerDefaultAllowPermission(), clearContainerDefaultDenyPermission(), closeContainerTo(), compareTo(), containsActiveSession(), containsChildObject(), containsPendingTask(), createChildObjects(), createComponents(), createContainerComponent(), destroyObjectFromDatabase(), destroyObjectFromWorld(), destroyPlayerCreatureFromDatabase(), doSendToClient(), dropActiveArea(), dropActiveSession(), dropSlottedObject(), error(), faceObject(), finalize(), getActiveAreasSize(), getActiveRegion(), getActiveSession(), getActiveSessionsCount(), getArrangementDescriptor(), getArrangementDescriptorSize(), getClient(), getClientGameObjectType(), getClientObjectCRC(), getContainedObjectsRecursive(), getContainerObject(), getContainerObjectRecursive(), getContainerObjectsSize(), getContainerType(), getContainerVolumeLimit(), getContainmentType(), getCountableObjectsRecursive(), getCustomObjectName(), getDirectionAngle(), getDirectionW(), getDirectionX(), getDirectionY(), getDirectionZ(), getDisplayedName(), getDistanceTo(), getGameObjectType(), getLocalZone(), getLoggingName(), getMovementCounter(), getObjectID(), getObjectNameStringIdFile(), getObjectNameStringIdName(), getParent(), getParentID(), getParentRecursively(), getPlanetCRC(), getPlanetMapCategoryCRC(), getPlanetMapSubCategoryCRC(), getRootParent(), getServerObjectCRC(), getSlotDescriptor(), getSlotDescriptorSize(), getSlottedObject(), getSlottedObjectsSize(), getSpecialDirectionAngle(), getWorldPositionX(), getWorldPositionY(), getWorldPositionZ(), getZone(), getZoneServer(), handleObjectMenuSelect(), hasActiveArea(), hasArrangementDescriptor(), hasFullContainerObjects(), hasObjectInContainer(), hasObjectInSlottedContainer(), hasSlotDescriptor(), incrementMovementCounter(), info(), initializeChildObject(), initializePrivateData(), initializeTransientMembers(), inRangeObjects(), isActiveArea(), isActorObject(), isAiAgent(), isArmorObject(), isASubChildOf(), isAttachment(), isAuctionObject(), isBazaarTerminal(), isBuildingDeed(), isBuildingObject(), isCamoKit(), isCampKit(), isCampStructure(), isCellObject(), isCityTerminal(), isCityVoteTerminal(), isCloningBuildingObject(), isComponent(), isContainerFull(), isContainerObject(), isControlDevice(), isCraftingStation(), isCraftingTool(), isCreatureHabitat(), isCreatureObject(), isDecoration(), isDeedObject(), isDiceObject(), isFactory(), isFactoryCrate(), isFireworkObject(), isFishingBait(), isFishingPoleObject(), isGarage(), isGeneratorObject(), isGroupObject(), isGuildObject(), isHarvesterObject(), isInRange(), isInstallationDeed(), isInstallationObject(), isInstrument(), isIntangibleObject(), isInWater(), isJunkDealer(), isLightsaberCrystalObject(), isLiveSample(), isManufactureSchematic(), isMissionObject(), isMissionTerminal(), isNoTrade(), isPlayerCreature(), isPlayerObject(), isPsgArmorObject(), isRecycleToolObject(), isRegion(), isRepairTool(), isResourceContainer(), isResourceSpawn(), isRobeObject(), isShipObject(), isShuttleInstallation(), isSignObject(), isStaticObject(), isStructureObject(), isTangibleObject(), isTerminal(), isTrapObject(), isVehicleDeedObject(), isVehicleObject(), isWaypointObject(), isWeaponObject(), isWearableContainerObject(), isWearableObject(), link(), notifyCloseContainer(), notifyInsertToZone(), notifyLoadFromDatabase(), notifyObjectInserted(), notifyObjectInsertedToChild(), notifyObjectRemoved(), notifyObjectRemovedFromChild(), notifyPositionUpdate(), notifyRemoveFromZone(), notifySelfPositionUpdate(), openContainerTo(), putInContainer(), removeAllContainerObjects(), removeFromContainerObjects(), removeObject(), removeSlottedObject(), rotate(), RPC_ADDACTIVEAREA__ACTIVEAREA_, RPC_ADDACTIVESESSION__INT_FACADE_, RPC_BROADCASTDESTROY__SCENEOBJECT_BOOL_, RPC_BROADCASTDESTROYPRIVATE__SCENEOBJECT_SCENEOBJECT_, RPC_BROADCASTMESSAGE__BASEPACKET_BOOL_BOOL_, RPC_BROADCASTMESSAGEPRIVATE__BASEPACKET_SCENEOBJECT_BOOL_, RPC_BROADCASTOBJECT__SCENEOBJECT_BOOL_, RPC_BROADCASTOBJECTPRIVATE__SCENEOBJECT_SCENEOBJECT_, RPC_CANADDOBJECT__SCENEOBJECT_INT_STRING_, RPC_CANBEDESTROYED__CREATUREOBJECT_, RPC_CLEARCONTAINERDEFAULTALLOWPERMISSION__SHORT_, RPC_CLEARCONTAINERDEFAULTDENYPERMISSION__SHORT_, RPC_CLOSECONTAINERTO__CREATUREOBJECT_BOOL_, RPC_COMPARETO__SCENEOBJECT_, RPC_CONTAINSACTIVESESSION__INT_, RPC_CONTAINSCHILDOBJECT__SCENEOBJECT_, RPC_CONTAINSPENDINGTASK__STRING_, RPC_CREATECHILDOBJECTS__, RPC_CREATECOMPONENTS__, RPC_CREATECONTAINERCOMPONENT__, RPC_DESTROYOBJECTFROMDATABASE__BOOL_, RPC_DESTROYOBJECTFROMWORLD__BOOL_, RPC_DESTROYPLAYERCREATUREFROMDATABASE__BOOL_, RPC_DOSENDTOCLIENT__, RPC_DROPACTIVEAREA__ACTIVEAREA_, RPC_DROPACTIVESESSION__INT_, RPC_DROPSLOTTEDOBJECT__STRING_, RPC_ERROR__STRING_, RPC_FACEOBJECT__SCENEOBJECT_, RPC_FINALIZE__, RPC_GETACTIVEAREASSIZE__, RPC_GETACTIVEREGION__, RPC_GETACTIVESESSION__INT_, RPC_GETACTIVESESSIONSCOUNT__, RPC_GETARRANGEMENTDESCRIPTOR__INT_, RPC_GETARRANGEMENTDESCRIPTORSIZE__, RPC_GETCLIENT__, RPC_GETCLIENTGAMEOBJECTTYPE__, RPC_GETCLIENTOBJECTCRC__, RPC_GETCONTAINEDOBJECTSRECURSIVE__, RPC_GETCONTAINEROBJECT__INT_, RPC_GETCONTAINEROBJECT__LONG_, RPC_GETCONTAINEROBJECTRECURSIVE__LONG_, RPC_GETCONTAINEROBJECTSSIZE__, RPC_GETCONTAINERTYPE__, RPC_GETCONTAINERVOLUMELIMIT__, RPC_GETCONTAINMENTTYPE__, RPC_GETCOUNTABLEOBJECTSRECURSIVE__, RPC_GETCUSTOMOBJECTNAME__, RPC_GETDIRECTIONANGLE__, RPC_GETDIRECTIONW__, RPC_GETDIRECTIONX__, RPC_GETDIRECTIONY__, RPC_GETDIRECTIONZ__, RPC_GETDISPLAYEDNAME__, RPC_GETDISTANCETO__SCENEOBJECT_, RPC_GETGAMEOBJECTTYPE__, RPC_GETLOCALZONE__, RPC_GETLOGGINGNAME__, RPC_GETMOVEMENTCOUNTER__, RPC_GETOBJECTID__, RPC_GETOBJECTNAMESTRINGIDFILE__, RPC_GETOBJECTNAMESTRINGIDNAME__, RPC_GETPARENT__, RPC_GETPARENTID__, RPC_GETPARENTRECURSIVELY__INT_, RPC_GETPLANETCRC__, RPC_GETPLANETMAPCATEGORYCRC__, RPC_GETPLANETMAPSUBCATEGORYCRC__, RPC_GETROOTPARENT__, RPC_GETSERVEROBJECTCRC__, RPC_GETSLOTDESCRIPTOR__INT_, RPC_GETSLOTDESCRIPTORSIZE__, RPC_GETSLOTTEDOBJECT__INT_, RPC_GETSLOTTEDOBJECT__STRING_, RPC_GETSLOTTEDOBJECTSSIZE__, RPC_GETSPECIALDIRECTIONANGLE__, RPC_GETWORLDPOSITIONX__, RPC_GETWORLDPOSITIONY__, RPC_GETWORLDPOSITIONZ__, RPC_GETZONE__, RPC_GETZONESERVER__, RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_, RPC_HASACTIVEAREA__ACTIVEAREA_, RPC_HASACTIVEAREA__LONG_, RPC_HASARRANGEMENTDESCRIPTOR__STRING_, RPC_HASFULLCONTAINEROBJECTS__, RPC_HASOBJECTINCONTAINER__LONG_, RPC_HASOBJECTINSLOTTEDCONTAINER__SCENEOBJECT_, RPC_HASSLOTDESCRIPTOR__STRING_, RPC_INCREMENTMOVEMENTCOUNTER__, RPC_INFO__STRING_BOOL_, RPC_INITIALIZECHILDOBJECT__SCENEOBJECT_, RPC_INITIALIZEPRIVATEDATA__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_INRANGEOBJECTS__INT_FLOAT_, RPC_ISACTIVEAREA__, RPC_ISACTOROBJECT__, RPC_ISAIAGENT__, RPC_ISARMOROBJECT__, RPC_ISASUBCHILDOF__SCENEOBJECT_, RPC_ISATTACHMENT__, RPC_ISAUCTIONOBJECT__, RPC_ISBAZAARTERMINAL__, RPC_ISBUILDINGDEED__, RPC_ISBUILDINGOBJECT__, RPC_ISCAMOKIT__, RPC_ISCAMPKIT__, RPC_ISCAMPSTRUCTURE__, RPC_ISCELLOBJECT__, RPC_ISCITYTERMINAL__, RPC_ISCITYVOTETERMINAL__, RPC_ISCLONINGBUILDINGOBJECT__, RPC_ISCOMPONENT__, RPC_ISCONTAINERFULL__, RPC_ISCONTAINEROBJECT__, RPC_ISCONTROLDEVICE__, RPC_ISCRAFTINGSTATION__, RPC_ISCRAFTINGTOOL__, RPC_ISCREATUREHABITAT__, RPC_ISCREATUREOBJECT__, RPC_ISDECORATION__, RPC_ISDEEDOBJECT__, RPC_ISDICEOBJECT__, RPC_ISFACTORY__, RPC_ISFACTORYCRATE__, RPC_ISFIREWORKOBJECT__, RPC_ISFISHINGBAIT__, RPC_ISFISHINGPOLEOBJECT__, RPC_ISGARAGE__, RPC_ISGENERATOROBJECT__, RPC_ISGROUPOBJECT__, RPC_ISGUILDOBJECT__, RPC_ISHARVESTEROBJECT__, RPC_ISINRANGE__SCENEOBJECT_FLOAT_, RPC_ISINSTALLATIONDEED__, RPC_ISINSTALLATIONOBJECT__, RPC_ISINSTRUMENT__, RPC_ISINTANGIBLEOBJECT__, RPC_ISINWATER__, RPC_ISJUNKDEALER__, RPC_ISLIGHTSABERCRYSTALOBJECT__, RPC_ISLIVESAMPLE__, RPC_ISMANUFACTURESCHEMATIC__, RPC_ISMISSIONOBJECT__, RPC_ISMISSIONTERMINAL__, RPC_ISNOTRADE__, RPC_ISPLAYERCREATURE__, RPC_ISPLAYEROBJECT__, RPC_ISPSGARMOROBJECT__, RPC_ISRECYCLETOOLOBJECT__, RPC_ISREGION__, RPC_ISREPAIRTOOL__, RPC_ISRESOURCECONTAINER__, RPC_ISRESOURCESPAWN__, RPC_ISROBEOBJECT__, RPC_ISSHIPOBJECT__, RPC_ISSHUTTLEINSTALLATION__, RPC_ISSIGNOBJECT__, RPC_ISSTATICOBJECT__, RPC_ISSTRUCTUREOBJECT__, RPC_ISTANGIBLEOBJECT__, RPC_ISTERMINAL__, RPC_ISTRAPOBJECT__, RPC_ISVEHICLEDEEDOBJECT__, RPC_ISVEHICLEOBJECT__, RPC_ISWAYPOINTOBJECT__, RPC_ISWEAPONOBJECT__, RPC_ISWEARABLECONTAINEROBJECT__, RPC_ISWEARABLEOBJECT__, RPC_LINK__LONG_INT_, RPC_NOTIFYCLOSECONTAINER__CREATUREOBJECT_, RPC_NOTIFYINSERTTOZONE__ZONE_, RPC_NOTIFYLOADFROMDATABASE__, RPC_NOTIFYOBJECTINSERTED__SCENEOBJECT_, RPC_NOTIFYOBJECTINSERTEDTOCHILD__SCENEOBJECT_SCENEOBJECT_SCENEOBJECT_, RPC_NOTIFYOBJECTREMOVED__SCENEOBJECT_, RPC_NOTIFYOBJECTREMOVEDFROMCHILD__SCENEOBJECT_SCENEOBJECT_, RPC_NOTIFYPOSITIONUPDATE__QUADTREEENTRY_, RPC_NOTIFYREMOVEFROMZONE__, RPC_NOTIFYSELFPOSITIONUPDATE__, RPC_OPENCONTAINERTO__CREATUREOBJECT_, RPC_PUTINCONTAINER__SCENEOBJECT_LONG_, RPC_REMOVEALLCONTAINEROBJECTS__, RPC_REMOVEFROMCONTAINEROBJECTS__INT_, RPC_REMOVEOBJECT__SCENEOBJECT_SCENEOBJECT_BOOL_, RPC_REMOVESLOTTEDOBJECT__INT_, RPC_ROTATE__INT_, RPC_SENDATTRIBUTELISTTO__CREATUREOBJECT_, RPC_SENDBASELINESTO__SCENEOBJECT_, RPC_SENDCONTAINEROBJECTSTO__SCENEOBJECT_, RPC_SENDDESTROYTO__SCENEOBJECT_, RPC_SENDMESSAGE__BASEPACKET_, RPC_SENDSLOTTEDOBJECTSTO__SCENEOBJECT_, RPC_SENDTO__SCENEOBJECT_BOOL_, RPC_SENDTOOWNER__BOOL_, RPC_SENDWITHOUTCONTAINEROBJECTSTO__SCENEOBJECT_, RPC_SENDWITHOUTPARENTTO__SCENEOBJECT_, RPC_SETCLIENTOBJECT__BOOL_, RPC_SETCLIENTOBJECTCRC__INT_, RPC_SETCONTAINERALLOWPERMISSION__STRING_SHORT_, RPC_SETCONTAINERDEFAULTALLOWPERMISSION__SHORT_, RPC_SETCONTAINERDEFAULTDENYPERMISSION__SHORT_, RPC_SETCONTAINERDENYPERMISSION__STRING_SHORT_, RPC_SETCONTAINERINHERITPERMISSIONSFROMPARENT__BOOL_, RPC_SETCONTAINEROWNERID__LONG_, RPC_SETCONTAINERTYPE__INT_, RPC_SETCONTAINERVOLUMELIMIT__INT_, RPC_SETCONTAINMENTTYPE__INT_, RPC_SETCUSTOMOBJECTNAME__UNICODESTRING_BOOL_, RPC_SETDETAILEDDESCRIPTION__STRING_, RPC_SETDIRECTION__FLOAT_, RPC_SETDIRECTION__FLOAT_FLOAT_FLOAT_FLOAT_, RPC_SETGAMEOBJECTTYPE__INT_, RPC_SETLOGGINGNAME__STRING_, RPC_SETMOVEMENTCOUNTER__INT_, RPC_SETPARENT__QUADTREEENTRY_, RPC_SETSENDTOCLIENT__BOOL_, RPC_SETSERVEROBJECTCRC__INT_, RPC_SETZONE__ZONE_, RPC_SETZONECOMPONENT__STRING_, RPC_SHOWFLYTEXT__STRING_STRING_BYTE_BYTE_BYTE_, RPC_SWITCHZONE__STRING_FLOAT_FLOAT_FLOAT_LONG_, RPC_SYNCHRONIZEDUILISTEN__SCENEOBJECT_INT_, RPC_SYNCHRONIZEDUISTOPLISTEN__SCENEOBJECT_INT_, RPC_TELEPORT__FLOAT_FLOAT_FLOAT_LONG_, RPC_TRANSFEROBJECT__SCENEOBJECT_INT_BOOL_BOOL_, RPC_UPDATEDIRECTION__FLOAT_, RPC_UPDATEDIRECTION__FLOAT_FLOAT_FLOAT_FLOAT_, RPC_UPDATETODATABASE__, RPC_UPDATETODATABASEALLOBJECTS__BOOL_, RPC_UPDATETODATABASEWITHOUTCHILDREN__, RPC_UPDATEVEHICLEPOSITION__BOOL_, RPC_UPDATEZONE__BOOL_BOOL_, RPC_UPDATEZONEWITHPARENT__SCENEOBJECT_BOOL_BOOL_, sendAttributeListTo(), sendBaselinesTo(), sendContainerObjectsTo(), sendDestroyTo(), sendMessage(), sendSlottedObjectsTo(), sendTo(), sendToOwner(), sendWithoutContainerObjectsTo(), sendWithoutParentTo(), setClientObject(), setClientObjectCRC(), setContainerAllowPermission(), setContainerDefaultAllowPermission(), setContainerDefaultDenyPermission(), setContainerDenyPermission(), setContainerInheritPermissionsFromParent(), setContainerOwnerID(), setContainerType(), setContainerVolumeLimit(), setContainmentType(), setCustomObjectName(), setDetailedDescription(), setDirection(), setGameObjectType(), setLoggingName(), setMovementCounter(), setParent(), setSendToClient(), setServerObjectCRC(), setZone(), setZoneComponent(), showFlyText(), switchZone(), synchronizedUIListen(), synchronizedUIStopListen(), teleport(), transferObject(), updateDirection(), updateToDatabase(), updateToDatabaseAllObjects(), updateToDatabaseWithoutChildren(), updateVehiclePosition(), updateZone(), and updateZoneWithParent().
bool SceneObjectAdapter::isActiveArea ()
Definition at line 7087 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isActorObject ()
Definition at line 7419 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isAiAgent ()
Definition at line 7099 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isArmorObject ()
Definition at line 7139 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isASubChildOf (SceneObject * object)
Definition at line 7047 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isAttachment ()
Definition at line 7283 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isAuctionObject ()
Definition at line 7263 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isBazaarTerminal ()
Definition at line 7187 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isBuildingDeed ()
Definition at line 7235 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isBuildingObject ()
Definition at line 7115 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isCamoKit ()
Definition at line 7279 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isCampKit ()
Definition at line 7295 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isCampStructure ()
Definition at line 7299 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isCellObject ()
Definition at line 7159 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isCityTerminal ()
Definition at line 7207 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isCityVoteTerminal ()
Definition at line 7211 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isCloningBuildingObject ()
Definition at line 7119 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isComponent ()
Definition at line 7175 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isContainerFull ()
Definition at line 7075 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isContainerObject ()
Definition at line 7391 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isControlDevice ()
Definition at line 7407 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isCraftingStation ()
Definition at line 7251 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isCraftingTool ()
Definition at line 7247 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isCreatureHabitat ()
Definition at line 7291 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isCreatureObject ()
Definition at line 7095 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isDecoration ()
Definition at line 7063 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isDeedObject ()
Definition at line 7227 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isDiceObject ()
Definition at line 7287 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isFactory ()
Definition at line 7215 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isFactoryCrate ()
Definition at line 7219 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isFireworkObject ()
Definition at line 7151 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isFishingBait ()
Definition at line 7267 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isFishingPoleObject ()
Definition at line 7223 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isGarage ()
Definition at line 7123 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isGeneratorObject ()
Definition at line 7203 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isGroupObject ()
Definition at line 7399 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isGuildObject ()
Definition at line 7403 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isHarvesterObject ()
Definition at line 7199 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isInRange (SceneObject * obj, float range)
Definition at line 6555 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isInstallationDeed ()
Definition at line 7243 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isInstallationObject ()
Definition at line 7195 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isInstrument ()
Definition at line 7183 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isIntangibleObject ()
Definition at line 7179 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isInWater ()
Definition at line 7443 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isJunkDealer ()
Definition at line 7103 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isLightsaberCrystalObject ()
Definition at line 7147 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isLiveSample ()
Definition at line 7191 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isManufactureSchematic ()
Definition at line 7255 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isMissionObject ()
Definition at line 7415 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isMissionTerminal ()
Definition at line 7411 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isNoTrade ()
Definition at line 7071 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isPlayerCreature ()
Definition at line 7059 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isPlayerObject ()
Definition at line 7083 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isPsgArmorObject ()
Definition at line 7155 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isRecycleToolObject ()
Definition at line 7303 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isRegion ()
Definition at line 7091 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isRepairTool ()
Definition at line 7275 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isResourceContainer ()
Definition at line 7167 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isResourceSpawn ()
Definition at line 7171 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isRobeObject ()
Definition at line 7143 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isShipObject ()
Definition at line 7107 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isShuttleInstallation ()
Definition at line 7079 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isSignObject ()
Definition at line 7239 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isStaticObject ()
Definition at line 7387 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isStructureObject ()
Definition at line 7259 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isTangibleObject ()
Definition at line 7163 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isTerminal ()
Definition at line 7395 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isTrapObject ()
Definition at line 7271 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isVehicleDeedObject ()
Definition at line 7231 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isVehicleObject ()
Definition at line 7111 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isWaypointObject ()
Definition at line 6863 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isWeaponObject ()
Definition at line 7127 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isWearableContainerObject ()
Definition at line 7135 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::isWearableObject ()
Definition at line 7131 of file SceneObject.cpp.
Referenced by invokeMethod().
BaseMessage * SceneObjectAdapter::link (unsigned long long objectID, unsigned int containmentType)
Definition at line 6615 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::notifyCloseContainer (CreatureObject * player)
Definition at line 7019 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::notifyInsertToZone (Zone * zone)
Definition at line 6667 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::notifyLoadFromDatabase ()
Definition at line 6539 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::notifyObjectInserted (SceneObject * object)
Definition at line 6783 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::notifyObjectInsertedToChild (SceneObject * object, SceneObject * child, SceneObject * oldParent)
Definition at line 6575 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::notifyObjectRemoved (SceneObject * object)
Definition at line 6787 of file SceneObject.cpp.
Referenced by invokeMethod().
int SceneObjectAdapter::notifyObjectRemovedFromChild (SceneObject * object, SceneObject * child)
Definition at line 6579 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::notifyPositionUpdate (QuadTreeEntry * entry)
Definition at line 7015 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::notifyRemoveFromZone ()
Definition at line 6687 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::notifySelfPositionUpdate ()
Definition at line 7011 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::openContainerTo (CreatureObject * player)
Definition at line 6659 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::putInContainer (SceneObject * obj, unsigned long long key)
Definition at line 6959 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::removeAllContainerObjects ()
Definition at line 6955 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::removeFromContainerObjects (int index)
Definition at line 6963 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::removeObject (SceneObject * object, SceneObject * destination, bool notifyClient)
Definition at line 6563 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::removeSlottedObject (int index)
Definition at line 6919 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::rotate (int degrees)
Definition at line 7003 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::sendAttributeListTo (CreatureObject * object)
Definition at line 6651 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::sendBaselinesTo (SceneObject * player)
Definition at line 6635 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::sendContainerObjectsTo (SceneObject * player)
Definition at line 6639 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::sendDestroyTo (SceneObject * player)
Definition at line 6631 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::sendMessage (BasePacket * msg)
Definition at line 6723 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::sendSlottedObjectsTo (SceneObject * player)
Definition at line 6643 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::sendTo (SceneObject * player, bool doClose)
Definition at line 6619 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::sendToOwner (bool doClose)
Definition at line 6647 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::sendWithoutContainerObjectsTo (SceneObject * player)
Definition at line 6627 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::sendWithoutParentTo (SceneObject * player)
Definition at line 6623 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setClientObject (bool val)
Definition at line 7379 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setClientObjectCRC (unsigned int objCRC)
Definition at line 7343 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setContainerAllowPermission (const String & group, unsigned short perm)
Definition at line 7331 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setContainerDefaultAllowPermission (unsigned short perm)
Definition at line 7307 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setContainerDefaultDenyPermission (unsigned short perm)
Definition at line 7315 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setContainerDenyPermission (const String & group, unsigned short perm)
Definition at line 7335 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setContainerInheritPermissionsFromParent (bool val)
Definition at line 7323 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setContainerOwnerID (unsigned long long id)
Definition at line 7327 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setContainerType (int type)
Definition at line 6971 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setContainerVolumeLimit (int lim)
Definition at line 6967 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setContainmentType (unsigned int type)
Definition at line 7371 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setCustomObjectName (const UnicodeString & name, bool notifyClient)
Definition at line 6655 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setDetailedDescription (const String & detail)
Definition at line 6875 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setDirection (float fw, float fx, float fy, float fz)
Definition at line 7355 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setDirection (float headingAngleRadians)
Definition at line 7359 of file SceneObject.cpp.
void SceneObjectAdapter::setGameObjectType (unsigned int type)
Definition at line 7339 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setLoggingName (const String & name)
Definition at line 7375 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setMovementCounter (unsigned int count)
Definition at line 7363 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setParent (QuadTreeEntry * entry)
Definition at line 7031 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setSendToClient (bool val)
Definition at line 7455 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setServerObjectCRC (unsigned int objCRC)
Definition at line 7347 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setZone (Zone * zone)
Definition at line 7351 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::setZoneComponent (const String & name)
Definition at line 7067 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::showFlyText (const String & file, const String & uax, byte red, byte green, byte blue)
Definition at line 6739 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::switchZone (const String & newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID)
Definition at line 6671 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::synchronizedUIListen (SceneObject * player, int value)
Definition at line 6583 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::synchronizedUIStopListen (SceneObject * player, int value)
Definition at line 6587 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID)
Definition at line 6675 of file SceneObject.cpp.
Referenced by invokeMethod().
bool SceneObjectAdapter::transferObject (SceneObject * object, int containmentType, bool notifyClient, bool allowOverflow)
Definition at line 6559 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::updateDirection (float fw, float fx, float fy, float fz)
Definition at line 6679 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::updateDirection (float angleHeadingRadians)
Definition at line 6683 of file SceneObject.cpp.
void SceneObjectAdapter::updateToDatabase ()
Definition at line 6591 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::updateToDatabaseAllObjects (bool startTask)
Definition at line 6599 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::updateToDatabaseWithoutChildren ()
Definition at line 6595 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::updateVehiclePosition (bool sendPackets)
Definition at line 6779 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::updateZone (bool lightUpdate, bool sendPackets)
Definition at line 6691 of file SceneObject.cpp.
Referenced by invokeMethod().
void SceneObjectAdapter::updateZoneWithParent (SceneObject * newParent, bool lightUpdate, bool sendPackets)
Definition at line 6695 of file SceneObject.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/SceneObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/SceneObject.cpp