Core3: RecycleToolContainerComponent Class Reference
RecycleToolContainerComponent Class Reference
#include <RecycleToolContainerComponent.h>
Public Member Functions
int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient, bool allowOverflow=false)
Public Member Functions inherited from ContainerComponent
virtual bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
virtual int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Detailed Description
Definition at line 8 of file RecycleToolContainerComponent.h.
Member Function Documentation
int RecycleToolContainerComponent::canAddObject (SceneObject * sceneObject, SceneObject * object, int containmentType, String & errorDescription) inline virtual
Evaluates if this object has the necessary free slots to be able to add the specified SceneObject
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be checked
error error string that the player will receive on error
Returns
returns 0 on success, or error code
Reimplemented from ContainerComponent.
Definition at line 31 of file RecycleToolContainerComponent.h.
References ContainerComponent::canAddObject(), TransferErrorCode::CONTAINERFULL, server::zone::objects::scene::SceneObject::getParentRecursively(), TransferErrorCode::MUSTBEINPLAYERINVENTORY, and SceneObjectType::PLAYERCREATURE.
int RecycleToolContainerComponent::notifyObjectInserted (SceneObject * sceneObject, SceneObject * object) inline virtual
Is called when this object has been inserted with an object
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 10 of file RecycleToolContainerComponent.h.
References ContainerComponent::notifyObjectInserted(), and RecycleResourceTask::run().
bool RecycleToolContainerComponent::removeObject (SceneObject * sceneObject, SceneObject * object, SceneObject * destination, bool notifyClient) inline virtual
Tries to remove/unlink object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be removed from the current object
notifyClient not used currently
Returns
returns true if the object has been successfully removed
Reimplemented from ContainerComponent.
Definition at line 26 of file RecycleToolContainerComponent.h.
References ContainerComponent::removeObject().
bool RecycleToolContainerComponent::transferObject (SceneObject * sceneObject, SceneObject * object, int containmentType, bool notifyClient, bool allowOverflow = false) inline virtual
Tries to add/link object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be added to the current object
containmentType arrangement type that will be used to add the object
notifyClient if true in range objects will be updated with the change
allowOverflow if true will bypass the containerVolumeLimit check
Returns
returns true if the object has been successfully added
Reimplemented from ContainerComponent.
Definition at line 52 of file RecycleToolContainerComponent.h.
References ContainerComponent::transferObject().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/tool/recycle/RecycleToolContainerComponent.h