Core3: HealMindSelf2Command Class Reference
HealMindSelf2Command Class Reference
#include <HealMindSelf2Command.h>
Public Member Functions
HealMindSelf2Command (const String &name, ZoneProcessServer *server)
bool canPerformSkill (CreatureObject *creature)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file HealMindSelf2Command.h.
Constructor & Destructor Documentation
HealMindSelf2Command::HealMindSelf2Command (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file HealMindSelf2Command.h.
Member Function Documentation
bool HealMindSelf2Command::canPerformSkill (CreatureObject * creature) inline
Definition at line 58 of file HealMindSelf2Command.h.
References server::zone::objects::creature::CreatureObject::hasDamage(), CreatureAttribute::MIND, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
int HealMindSelf2Command::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 68 of file HealMindSelf2Command.h.
References canPerformSkill(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::healDamage(), CreatureAttribute::MIND, server::zone::objects::creature::CreatureObject::playEffect(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
float HealMindSelf2Command::getCommandDuration (CreatureObject * object, const UnicodeString & arguments) inline
Definition at line 128 of file HealMindSelf2Command.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/HealMindSelf2Command.h