Core3: server::zone::objects::player::sessions::ConversationSession Class Reference
server::zone::objects::player::sessions::ConversationSession Class Reference
#include <ConversationSession.h>
Public Member Functions
ConversationSession (CreatureObject *conversingCreature)
void setLastConversationScreen (ConversationScreen *screen)
ConversationScreen * getLastConversationScreen ()
ManagedWeakReference
< CreatureObject * > getNPC ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ConversationSession (DummyConstructorParameter *param)
virtual ~ConversationSession ()
Friends
class ConversationSessionHelper
Detailed Description
Definition at line 52 of file ConversationSession.h.
Constructor & Destructor Documentation
ConversationSession::ConversationSession (CreatureObject * conversingCreature)
Definition at line 17 of file ConversationSession.cpp.
References server::zone::objects::player::sessions::ConversationSessionImplementation::_setStub().
ConversationSession::ConversationSession (DummyConstructorParameter * param) protected
Definition at line 24 of file ConversationSession.cpp.
ConversationSession::~ConversationSession () protected virtual
Definition at line 28 of file ConversationSession.cpp.
Member Function Documentation
DistributedObjectServant * ConversationSession::_getImplementation ()
Definition at line 64 of file ConversationSession.cpp.
Referenced by getLastConversationScreen(), getNPC(), and setLastConversationScreen().
DistributedObjectServant * ConversationSession::_getImplementationForRead ()
Definition at line 70 of file ConversationSession.cpp.
void ConversationSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 74 of file ConversationSession.cpp.
ConversationScreen * ConversationSession::getLastConversationScreen ()
Definition at line 42 of file ConversationSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::ConversationSessionImplementation::getLastConversationScreen().
Referenced by server::zone::objects::creature::conversation::ConversationObserverImplementation::getNextConversationScreen().
ManagedWeakReference< CreatureObject * > ConversationSession::getNPC ()
Definition at line 51 of file ConversationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::ConversationSessionImplementation::getNPC(), and RPC_GETNPC__.
Referenced by server::zone::objects::creature::conversation::ConversationObserverImplementation::notifyObserverEvent().
void ConversationSession::setLastConversationScreen (ConversationScreen * screen)
Definition at line 33 of file ConversationSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::ConversationSessionImplementation::setLastConversationScreen().
Referenced by server::zone::objects::creature::conversation::ConversationObserverImplementation::sendConversationScreenToPlayer(), and server::zone::templates::mobile::ConversationScreen::sendTo().
Friends And Related Function Documentation
friend class ConversationSessionHelper friend
Definition at line 72 of file ConversationSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ConversationSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ConversationSession.cpp