Core3: server::zone::objects::player::sessions::MigrateStatsSession Class Reference
server::zone::objects::player::sessions::MigrateStatsSession Class Reference
#include <MigrateStatsSession.h>
Public Member Functions
MigrateStatsSession (CreatureObject *parent)
int initializeSession ()
int cancelSession ()
int clearSession ()
int getAttributeToModifyCount ()
void setAttributeToModify (int attribute, int value)
int getAttribtueToModify (int attribute)
void migrateStats ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
MigrateStatsSession (DummyConstructorParameter *param)
virtual ~MigrateStatsSession ()
Friends
class MigrateStatsSessionHelper
Detailed Description
Definition at line 64 of file MigrateStatsSession.h.
Constructor & Destructor Documentation
MigrateStatsSession::MigrateStatsSession (CreatureObject * parent)
Definition at line 17 of file MigrateStatsSession.cpp.
References server::zone::objects::player::sessions::MigrateStatsSessionImplementation::_setStub().
MigrateStatsSession::MigrateStatsSession (DummyConstructorParameter * param) protected
Definition at line 24 of file MigrateStatsSession.cpp.
MigrateStatsSession::~MigrateStatsSession () protected virtual
Definition at line 28 of file MigrateStatsSession.cpp.
Member Function Documentation
DistributedObjectServant * MigrateStatsSession::_getImplementation ()
Definition at line 127 of file MigrateStatsSession.cpp.
Referenced by cancelSession(), clearSession(), getAttribtueToModify(), getAttributeToModifyCount(), initializeSession(), migrateStats(), and setAttributeToModify().
DistributedObjectServant * MigrateStatsSession::_getImplementationForRead ()
Definition at line 133 of file MigrateStatsSession.cpp.
void MigrateStatsSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 137 of file MigrateStatsSession.cpp.
int MigrateStatsSession::cancelSession ()
Definition at line 46 of file MigrateStatsSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::MigrateStatsSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
int MigrateStatsSession::clearSession ()
Definition at line 59 of file MigrateStatsSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::MigrateStatsSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
int MigrateStatsSession::getAttribtueToModify (int attribute)
Definition at line 100 of file MigrateStatsSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::MigrateStatsSessionImplementation::getAttribtueToModify(), and RPC_GETATTRIBTUETOMODIFY__INT_.
int MigrateStatsSession::getAttributeToModifyCount ()
Definition at line 72 of file MigrateStatsSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::MigrateStatsSessionImplementation::getAttributeToModifyCount(), and RPC_GETATTRIBUTETOMODIFYCOUNT__.
int MigrateStatsSession::initializeSession ()
Definition at line 33 of file MigrateStatsSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::MigrateStatsSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
void MigrateStatsSession::migrateStats ()
Definition at line 114 of file MigrateStatsSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::MigrateStatsSessionImplementation::migrateStats(), and RPC_MIGRATESTATS__.
Referenced by server::zone::objects::player::sessions::ImageDesignSessionImplementation::updateImageDesign().
void MigrateStatsSession::setAttributeToModify (int attribute, int value)
Definition at line 85 of file MigrateStatsSession.cpp.
References _getImplementation(), RPC_SETATTRIBUTETOMODIFY__INT_INT_, and server::zone::objects::player::sessions::MigrateStatsSessionImplementation::setAttributeToModify().
Friends And Related Function Documentation
friend class MigrateStatsSessionHelper friend
Definition at line 92 of file MigrateStatsSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/MigrateStatsSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/MigrateStatsSession.cpp