Core3: server::zone::managers::player::PlayerManagerAdapter Class Reference
server::zone::managers::player::PlayerManagerAdapter Class Reference
#include <PlayerManager.h>
Public Member Functions
PlayerManagerAdapter (PlayerManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void loadNameMap ()
int getHighestBadgeIndex ()
void finalize ()
bool kickUser (const String &name, const String &admin, String &reason, bool doBan)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
int notifyDestruction (TangibleObject *destructor, TangibleObject *destructedObject, int condition)
bool shouldRescheduleCorpseDestruction (CreatureObject *player, CreatureObject *ai)
void rescheduleCorpseDestruction (CreatureObject *player, CreatureObject *ai)
bool canGroupMemberHarvestCorpse (CreatureObject *player, Creature *creature)
void killPlayer (TangibleObject *attacker, CreatureObject *player, int typeofdeath)
byte calculateIncapacitationTimer (CreatureObject *player, int condition)
bool checkEncumbrancies (CreatureObject *player, ArmorObject *armor)
void applyEncumbrancies (CreatureObject *player, ArmorObject *armor)
void removeEncumbrancies (CreatureObject *player, ArmorObject *armor)
void awardBadge (PlayerObject *ghost, unsigned int badge)
void setExperienceMultiplier (float globalMultiplier)
void awardExperience (CreatureObject *player, const String &xpType, int amount, bool sendSystemMessage, float localMultiplier)
void handleAbortTradeMessage (CreatureObject *player)
void handleAddItemToTradeWindow (CreatureObject *player, unsigned long long itemID)
void handleGiveMoneyMessage (CreatureObject *player, unsigned int value)
void handleAcceptTransactionMessage (CreatureObject *player)
void handleUnAcceptTransactionMessage (CreatureObject *player)
void handleVerifyTradeMessage (CreatureObject *player)
bool checkTradeItems (CreatureObject *player, CreatureObject *receiver)
SceneObject * getInRangeStructureWithAdminRights (CreatureObject *creature, unsigned long long targetID)
StructureObject * getInRangeOwnedStructure (CreatureObject *creature, float range)
void sendBattleFatigueMessage (CreatureObject *player, CreatureObject *target)
void stopWatch (CreatureObject *creature, unsigned long long entid, bool doSendPackets, bool forced, bool doLock, bool outOfRange)
void stopListen (CreatureObject *creature, unsigned long long entid, bool doSendPackets, bool forced, bool doLock, bool outOfRange)
void startWatch (CreatureObject *creature, unsigned long long entid)
void startListen (CreatureObject *creature, unsigned long long entid)
void lootAll (CreatureObject *player, CreatureObject *creature)
int healEnhance (CreatureObject *enhancer, CreatureObject *patient, byte attribute, int buffvalue, float duration)
int calculatePlayerLevel (CreatureObject *player)
void sendLoginMessage (CreatureObject *player)
void resendLoginMessageToAll ()
void sendActivateCloneRequest (CreatureObject *player, int typeofdeath)
void sendPlayerToCloner (CreatureObject *player, unsigned long long clonerID, int typeofdeath)
void ejectPlayerFromBuilding (CreatureObject *player)
bool checkExistentNameInDatabase (const String &firstName)
Reference< TangibleObject * > createHairObject (const String &hairObjectFile, const String &hairCustomization)
void createTutorialBuilding (CreatureObject *player)
void createSkippedTutorialBuilding (CreatureObject *player)
int checkSpeedHackSecondTest (CreatureObject *player, float newX, float newZ, float newY, unsigned int newStamp, SceneObject *newParent)
bool existsName (const String &name)
unsigned long long getObjectID (const String &name)
Reference< CreatureObject * > getPlayer (const String &name)
void updatePermissionLevel (CreatureObject *player, int adminLevel)
void updatePermissionName (CreatureObject *player, int adminLevel)
void addPlayer (CreatureObject *player)
void removePlayer (String &playerName)
String getBadgeKey (int idx)
CraftingStation * getNearbyCraftingStation (CreatureObject *player, int type)
void finishHologrind (CreatureObject *player)
Account * getAccount (const String &username)
Account * getAccount (unsigned int accountID)
String banAccount (PlayerObject *admin, Account *account, unsigned int seconds, const String &reason)
String unbanAccount (PlayerObject *admin, Account *account, const String &reason)
String banFromGalaxy (PlayerObject *admin, Account *account, unsigned const int galaxy, unsigned int seconds, const String &reason)
String unbanFromGalaxy (PlayerObject *admin, Account *account, unsigned const int galaxy, const String &reason)
String banCharacter (PlayerObject *admin, Account *account, const String &name, unsigned int galaxyID, unsigned int seconds, const String &reason)
String unbanCharacter (PlayerObject *admin, Account *account, const String &name, unsigned int galaxyID, const String &reason)
bool promptTeachableSkills (CreatureObject *teacher, SceneObject *target)
void decreaseOnlineCharCount (ZoneClientSession *client)
bool increaseOnlineCharCountIfPossible (ZoneClientSession *client)
void fixHAM (CreatureObject *player)
void getCleanupCharacterCount ()
void cleanupCharacters ()
bool shouldDeleteCharacter (unsigned long long characterID, int galaxyID)
void enhanceCharacter (CreatureObject *player)
Detailed Description
Definition at line 856 of file PlayerManager.h.
Constructor & Destructor Documentation
PlayerManagerAdapter::PlayerManagerAdapter (PlayerManager * impl)
Definition at line 1427 of file PlayerManager.cpp.
Member Function Documentation
void PlayerManagerAdapter::addPlayer (CreatureObject * player)
Definition at line 2000 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::applyEncumbrancies (CreatureObject * player, ArmorObject * armor)
Definition at line 1852 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::awardBadge (PlayerObject * ghost, unsigned int badge)
Definition at line 1860 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::awardExperience (CreatureObject * player, const String & xpType, int amount, bool sendSystemMessage, float localMultiplier)
Definition at line 1868 of file PlayerManager.cpp.
Referenced by invokeMethod().
String PlayerManagerAdapter::banAccount (PlayerObject * admin, Account * account, unsigned int seconds, const String & reason)
Definition at line 2028 of file PlayerManager.cpp.
Referenced by invokeMethod().
String PlayerManagerAdapter::banCharacter (PlayerObject * admin, Account * account, const String & name, unsigned int galaxyID, unsigned int seconds, const String & reason)
Definition at line 2044 of file PlayerManager.cpp.
Referenced by invokeMethod().
String PlayerManagerAdapter::banFromGalaxy (PlayerObject * admin, Account * account, unsigned const int galaxy, unsigned int seconds, const String & reason)
Definition at line 2036 of file PlayerManager.cpp.
Referenced by invokeMethod().
byte PlayerManagerAdapter::calculateIncapacitationTimer (CreatureObject * player, int condition)
Definition at line 1844 of file PlayerManager.cpp.
Referenced by invokeMethod().
int PlayerManagerAdapter::calculatePlayerLevel (CreatureObject * player)
Definition at line 1936 of file PlayerManager.cpp.
Referenced by invokeMethod().
bool PlayerManagerAdapter::canGroupMemberHarvestCorpse (CreatureObject * player, Creature * creature)
Definition at line 1836 of file PlayerManager.cpp.
Referenced by invokeMethod().
bool PlayerManagerAdapter::checkEncumbrancies (CreatureObject * player, ArmorObject * armor)
Definition at line 1848 of file PlayerManager.cpp.
Referenced by invokeMethod().
bool PlayerManagerAdapter::checkExistentNameInDatabase (const String & firstName)
Definition at line 1960 of file PlayerManager.cpp.
Referenced by invokeMethod().
int PlayerManagerAdapter::checkSpeedHackSecondTest (CreatureObject * player, float newX, float newZ, float newY, unsigned int newStamp, SceneObject * newParent)
Definition at line 1976 of file PlayerManager.cpp.
Referenced by invokeMethod().
bool PlayerManagerAdapter::checkTradeItems (CreatureObject * player, CreatureObject * receiver)
Definition at line 1896 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::cleanupCharacters ()
Definition at line 2072 of file PlayerManager.cpp.
Referenced by invokeMethod().
Reference< TangibleObject * > PlayerManagerAdapter::createHairObject (const String & hairObjectFile, const String & hairCustomization)
Definition at line 1964 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::createSkippedTutorialBuilding (CreatureObject * player)
Definition at line 1972 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::createTutorialBuilding (CreatureObject * player)
Definition at line 1968 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::decreaseOnlineCharCount (ZoneClientSession * client)
Definition at line 2056 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::ejectPlayerFromBuilding (CreatureObject * player)
Definition at line 1956 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::enhanceCharacter (CreatureObject * player)
Definition at line 2080 of file PlayerManager.cpp.
Referenced by invokeMethod().
bool PlayerManagerAdapter::existsName (const String & name)
Definition at line 1980 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::finalize ()
Definition at line 1812 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::finishHologrind (CreatureObject * player)
Definition at line 2016 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::fixHAM (CreatureObject * player)
Definition at line 2064 of file PlayerManager.cpp.
Referenced by invokeMethod().
Account * PlayerManagerAdapter::getAccount (const String & username)
Definition at line 2020 of file PlayerManager.cpp.
Referenced by invokeMethod().
Account * PlayerManagerAdapter::getAccount (unsigned int accountID)
Definition at line 2024 of file PlayerManager.cpp.
String PlayerManagerAdapter::getBadgeKey (int idx)
Definition at line 2008 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::getCleanupCharacterCount ()
Definition at line 2068 of file PlayerManager.cpp.
Referenced by invokeMethod().
int PlayerManagerAdapter::getHighestBadgeIndex ()
Definition at line 1808 of file PlayerManager.cpp.
Referenced by invokeMethod().
StructureObject * PlayerManagerAdapter::getInRangeOwnedStructure (CreatureObject * creature, float range)
Definition at line 1904 of file PlayerManager.cpp.
Referenced by invokeMethod().
SceneObject * PlayerManagerAdapter::getInRangeStructureWithAdminRights (CreatureObject * creature, unsigned long long targetID)
Definition at line 1900 of file PlayerManager.cpp.
Referenced by invokeMethod().
CraftingStation * PlayerManagerAdapter::getNearbyCraftingStation (CreatureObject * player, int type)
Definition at line 2012 of file PlayerManager.cpp.
Referenced by invokeMethod().
unsigned long long PlayerManagerAdapter::getObjectID (const String & name)
Definition at line 1984 of file PlayerManager.cpp.
Referenced by invokeMethod().
Reference< CreatureObject * > PlayerManagerAdapter::getPlayer (const String & name)
Definition at line 1988 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::handleAbortTradeMessage (CreatureObject * player)
Definition at line 1872 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::handleAcceptTransactionMessage (CreatureObject * player)
Definition at line 1884 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::handleAddItemToTradeWindow (CreatureObject * player, unsigned long long itemID)
Definition at line 1876 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::handleGiveMoneyMessage (CreatureObject * player, unsigned int value)
Definition at line 1880 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::handleUnAcceptTransactionMessage (CreatureObject * player)
Definition at line 1888 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::handleVerifyTradeMessage (CreatureObject * player)
Definition at line 1892 of file PlayerManager.cpp.
Referenced by invokeMethod().
int PlayerManagerAdapter::healEnhance (CreatureObject * enhancer, CreatureObject * patient, byte attribute, int buffvalue, float duration)
Definition at line 1932 of file PlayerManager.cpp.
Referenced by invokeMethod().
bool PlayerManagerAdapter::increaseOnlineCharCountIfPossible (ZoneClientSession * client)
Definition at line 2060 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1430 of file PlayerManager.cpp.
References addPlayer(), applyEncumbrancies(), awardBadge(), awardExperience(), banAccount(), banCharacter(), banFromGalaxy(), calculateIncapacitationTimer(), calculatePlayerLevel(), canGroupMemberHarvestCorpse(), checkEncumbrancies(), checkExistentNameInDatabase(), checkSpeedHackSecondTest(), checkTradeItems(), cleanupCharacters(), createHairObject(), createSkippedTutorialBuilding(), createTutorialBuilding(), decreaseOnlineCharCount(), ejectPlayerFromBuilding(), enhanceCharacter(), existsName(), finalize(), finishHologrind(), fixHAM(), getAccount(), getBadgeKey(), getCleanupCharacterCount(), getHighestBadgeIndex(), getInRangeOwnedStructure(), getInRangeStructureWithAdminRights(), getNearbyCraftingStation(), getObjectID(), getPlayer(), handleAbortTradeMessage(), handleAcceptTransactionMessage(), handleAddItemToTradeWindow(), handleGiveMoneyMessage(), handleUnAcceptTransactionMessage(), handleVerifyTradeMessage(), healEnhance(), increaseOnlineCharCountIfPossible(), kickUser(), killPlayer(), loadNameMap(), lootAll(), notifyDestruction(), notifyObserverEvent(), promptTeachableSkills(), removeEncumbrancies(), removePlayer(), rescheduleCorpseDestruction(), resendLoginMessageToAll(), RPC_ADDPLAYER__CREATUREOBJECT_, RPC_APPLYENCUMBRANCIES__CREATUREOBJECT_ARMOROBJECT_, RPC_AWARDBADGE__PLAYEROBJECT_INT_, RPC_AWARDEXPERIENCE__CREATUREOBJECT_STRING_INT_BOOL_FLOAT_, RPC_BANACCOUNT__PLAYEROBJECT_ACCOUNT_INT_STRING_, RPC_BANCHARACTER__PLAYEROBJECT_ACCOUNT_STRING_INT_INT_STRING_, RPC_BANFROMGALAXY__PLAYEROBJECT_ACCOUNT_INT_INT_STRING_, RPC_CALCULATEINCAPACITATIONTIMER__CREATUREOBJECT_INT_, RPC_CALCULATEPLAYERLEVEL__CREATUREOBJECT_, RPC_CANGROUPMEMBERHARVESTCORPSE__CREATUREOBJECT_CREATURE_, RPC_CHECKENCUMBRANCIES__CREATUREOBJECT_ARMOROBJECT_, RPC_CHECKEXISTENTNAMEINDATABASE__STRING_, RPC_CHECKSPEEDHACKSECONDTEST__CREATUREOBJECT_FLOAT_FLOAT_FLOAT_INT_SCENEOBJECT_, RPC_CHECKTRADEITEMS__CREATUREOBJECT_CREATUREOBJECT_, RPC_CLEANUPCHARACTERS__, RPC_CREATEHAIROBJECT__STRING_STRING_, RPC_CREATESKIPPEDTUTORIALBUILDING__CREATUREOBJECT_, RPC_CREATETUTORIALBUILDING__CREATUREOBJECT_, RPC_DECREASEONLINECHARCOUNT__ZONECLIENTSESSION_, RPC_EJECTPLAYERFROMBUILDING__CREATUREOBJECT_, RPC_ENHANCECHARACTER__CREATUREOBJECT_, RPC_EXISTSNAME__STRING_, RPC_FINALIZE__, RPC_FINISHHOLOGRIND__CREATUREOBJECT_, RPC_FIXHAM__CREATUREOBJECT_, RPC_GETACCOUNT__INT_, RPC_GETACCOUNT__STRING_, RPC_GETBADGEKEY__INT_, RPC_GETCLEANUPCHARACTERCOUNT__, RPC_GETHIGHESTBADGEINDEX__, RPC_GETINRANGEOWNEDSTRUCTURE__CREATUREOBJECT_FLOAT_, RPC_GETINRANGESTRUCTUREWITHADMINRIGHTS__CREATUREOBJECT_LONG_, RPC_GETNEARBYCRAFTINGSTATION__CREATUREOBJECT_INT_, RPC_GETOBJECTID__STRING_, RPC_GETPLAYER__STRING_, RPC_HANDLEABORTTRADEMESSAGE__CREATUREOBJECT_, RPC_HANDLEACCEPTTRANSACTIONMESSAGE__CREATUREOBJECT_, RPC_HANDLEADDITEMTOTRADEWINDOW__CREATUREOBJECT_LONG_, RPC_HANDLEGIVEMONEYMESSAGE__CREATUREOBJECT_INT_, RPC_HANDLEUNACCEPTTRANSACTIONMESSAGE__CREATUREOBJECT_, RPC_HANDLEVERIFYTRADEMESSAGE__CREATUREOBJECT_, RPC_HEALENHANCE__CREATUREOBJECT_CREATUREOBJECT_BYTE_INT_FLOAT_, RPC_INCREASEONLINECHARCOUNTIFPOSSIBLE__ZONECLIENTSESSION_, RPC_KICKUSER__STRING_STRING_STRING_BOOL_, RPC_KILLPLAYER__TANGIBLEOBJECT_CREATUREOBJECT_INT_, RPC_LOADNAMEMAP__, RPC_LOOTALL__CREATUREOBJECT_CREATUREOBJECT_, RPC_NOTIFYDESTRUCTION__TANGIBLEOBJECT_TANGIBLEOBJECT_INT_, RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_, RPC_PROMPTTEACHABLESKILLS__CREATUREOBJECT_SCENEOBJECT_, RPC_REMOVEENCUMBRANCIES__CREATUREOBJECT_ARMOROBJECT_, RPC_REMOVEPLAYER__STRING_, RPC_RESCHEDULECORPSEDESTRUCTION__CREATUREOBJECT_CREATUREOBJECT_, RPC_RESENDLOGINMESSAGETOALL__, RPC_SENDACTIVATECLONEREQUEST__CREATUREOBJECT_INT_, RPC_SENDBATTLEFATIGUEMESSAGE__CREATUREOBJECT_CREATUREOBJECT_, RPC_SENDLOGINMESSAGE__CREATUREOBJECT_, RPC_SENDPLAYERTOCLONER__CREATUREOBJECT_LONG_INT_, RPC_SETEXPERIENCEMULTIPLIER__FLOAT_, RPC_SHOULDDELETECHARACTER__LONG_INT_, RPC_SHOULDRESCHEDULECORPSEDESTRUCTION__CREATUREOBJECT_CREATUREOBJECT_, RPC_STARTLISTEN__CREATUREOBJECT_LONG_, RPC_STARTWATCH__CREATUREOBJECT_LONG_, RPC_STOPLISTEN__CREATUREOBJECT_LONG_BOOL_BOOL_BOOL_BOOL_, RPC_STOPWATCH__CREATUREOBJECT_LONG_BOOL_BOOL_BOOL_BOOL_, RPC_UNBANACCOUNT__PLAYEROBJECT_ACCOUNT_STRING_, RPC_UNBANCHARACTER__PLAYEROBJECT_ACCOUNT_STRING_INT_STRING_, RPC_UNBANFROMGALAXY__PLAYEROBJECT_ACCOUNT_INT_STRING_, RPC_UPDATEPERMISSIONLEVEL__CREATUREOBJECT_INT_, RPC_UPDATEPERMISSIONNAME__CREATUREOBJECT_INT_, sendActivateCloneRequest(), sendBattleFatigueMessage(), sendLoginMessage(), sendPlayerToCloner(), setExperienceMultiplier(), shouldDeleteCharacter(), shouldRescheduleCorpseDestruction(), startListen(), startWatch(), stopListen(), stopWatch(), unbanAccount(), unbanCharacter(), unbanFromGalaxy(), updatePermissionLevel(), and updatePermissionName().
bool PlayerManagerAdapter::kickUser (const String & name, const String & admin, String & reason, bool doBan)
Definition at line 1816 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::killPlayer (TangibleObject * attacker, CreatureObject * player, int typeofdeath)
Definition at line 1840 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::loadNameMap ()
Definition at line 1804 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::lootAll (CreatureObject * player, CreatureObject * creature)
Definition at line 1928 of file PlayerManager.cpp.
Referenced by invokeMethod().
int PlayerManagerAdapter::notifyDestruction (TangibleObject * destructor, TangibleObject * destructedObject, int condition)
Definition at line 1824 of file PlayerManager.cpp.
Referenced by invokeMethod().
int PlayerManagerAdapter::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 1820 of file PlayerManager.cpp.
Referenced by invokeMethod().
bool PlayerManagerAdapter::promptTeachableSkills (CreatureObject * teacher, SceneObject * target)
Definition at line 2052 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::removeEncumbrancies (CreatureObject * player, ArmorObject * armor)
Definition at line 1856 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::removePlayer (String & playerName)
Definition at line 2004 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::rescheduleCorpseDestruction (CreatureObject * player, CreatureObject * ai)
Definition at line 1832 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::resendLoginMessageToAll ()
Definition at line 1944 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::sendActivateCloneRequest (CreatureObject * player, int typeofdeath)
Definition at line 1948 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::sendBattleFatigueMessage (CreatureObject * player, CreatureObject * target)
Definition at line 1908 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::sendLoginMessage (CreatureObject * player)
Definition at line 1940 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::sendPlayerToCloner (CreatureObject * player, unsigned long long clonerID, int typeofdeath)
Definition at line 1952 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::setExperienceMultiplier (float globalMultiplier)
Definition at line 1864 of file PlayerManager.cpp.
Referenced by invokeMethod().
bool PlayerManagerAdapter::shouldDeleteCharacter (unsigned long long characterID, int galaxyID)
Definition at line 2076 of file PlayerManager.cpp.
Referenced by invokeMethod().
bool PlayerManagerAdapter::shouldRescheduleCorpseDestruction (CreatureObject * player, CreatureObject * ai)
Definition at line 1828 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::startListen (CreatureObject * creature, unsigned long long entid)
Definition at line 1924 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::startWatch (CreatureObject * creature, unsigned long long entid)
Definition at line 1920 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::stopListen (CreatureObject * creature, unsigned long long entid, bool doSendPackets, bool forced, bool doLock, bool outOfRange)
Definition at line 1916 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::stopWatch (CreatureObject * creature, unsigned long long entid, bool doSendPackets, bool forced, bool doLock, bool outOfRange)
Definition at line 1912 of file PlayerManager.cpp.
Referenced by invokeMethod().
String PlayerManagerAdapter::unbanAccount (PlayerObject * admin, Account * account, const String & reason)
Definition at line 2032 of file PlayerManager.cpp.
Referenced by invokeMethod().
String PlayerManagerAdapter::unbanCharacter (PlayerObject * admin, Account * account, const String & name, unsigned int galaxyID, const String & reason)
Definition at line 2048 of file PlayerManager.cpp.
Referenced by invokeMethod().
String PlayerManagerAdapter::unbanFromGalaxy (PlayerObject * admin, Account * account, unsigned const int galaxy, const String & reason)
Definition at line 2040 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::updatePermissionLevel (CreatureObject * player, int adminLevel)
Definition at line 1992 of file PlayerManager.cpp.
Referenced by invokeMethod().
void PlayerManagerAdapter::updatePermissionName (CreatureObject * player, int adminLevel)
Definition at line 1996 of file PlayerManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/PlayerManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/PlayerManager.cpp