Core3: server::zone::managers::player::PlayerManagerImplementation Class Reference
server::zone::managers::player::PlayerManagerImplementation Class Reference
#include <PlayerManager.h>
Public Member Functions
PlayerManagerImplementation (ZoneServer *zoneServer, ZoneProcessServer *impl)
PlayerManagerImplementation (DummyConstructorParameter *param)
void loadNameMap ()
int getHighestBadgeIndex ()
void finalize ()
void sendStartingLocationsTo (CreatureObject *player)
StartingLocation * getStartingLocation (const String &city)
bool kickUser (const String &name, const String &admin, String &reason, bool doBan=true)
bool createPlayer (MessageCallback *callback)
bool checkPlayerName (MessageCallback *callback)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
int notifyDestruction (TangibleObject *destructor, TangibleObject *destructedObject, int condition)
bool shouldRescheduleCorpseDestruction (CreatureObject *player, CreatureObject *ai)
void rescheduleCorpseDestruction (CreatureObject *player, CreatureObject *ai)
bool canGroupMemberHarvestCorpse (CreatureObject *player, Creature *creature)
void killPlayer (TangibleObject *attacker, CreatureObject *player, int typeofdeath=0)
byte calculateIncapacitationTimer (CreatureObject *player, int condition)
bool checkEncumbrancies (CreatureObject *player, ArmorObject *armor)
void applyEncumbrancies (CreatureObject *player, ArmorObject *armor)
void removeEncumbrancies (CreatureObject *player, ArmorObject *armor)
void awardBadge (PlayerObject *ghost, unsigned int badge)
void setExperienceMultiplier (float globalMultiplier)
void awardExperience (CreatureObject *player, const String &xpType, int amount, bool sendSystemMessage=true, float localMultiplier=1.0f)
SortedVector< ManagedReference
< SceneObject * > > getInsurableItems (CreatureObject *player, bool onlyInsurable=true)
void addInsurableItemsRecursive (SceneObject *obj, SortedVector< ManagedReference< SceneObject * > > *items, bool onlyInsurable)
void handleAbortTradeMessage (CreatureObject *player)
void handleAddItemToTradeWindow (CreatureObject *player, unsigned long long itemID)
void handleGiveMoneyMessage (CreatureObject *player, unsigned int value)
void handleAcceptTransactionMessage (CreatureObject *player)
void handleUnAcceptTransactionMessage (CreatureObject *player)
void handleVerifyTradeMessage (CreatureObject *player)
bool checkTradeItems (CreatureObject *player, CreatureObject *receiver)
SceneObject * getInRangeStructureWithAdminRights (CreatureObject *creature, unsigned long long targetID=0)
StructureObject * getInRangeOwnedStructure (CreatureObject *creature, float range=128)
void sendBattleFatigueMessage (CreatureObject *player, CreatureObject *target)
void stopWatch (CreatureObject *creature, unsigned long long entid, bool doSendPackets=true, bool forced=false, bool doLock=true, bool outOfRange=false)
void stopListen (CreatureObject *creature, unsigned long long entid, bool doSendPackets=true, bool forced=false, bool doLock=true, bool outOfRange=false)
void startWatch (CreatureObject *creature, unsigned long long entid)
void startListen (CreatureObject *creature, unsigned long long entid)
void lootAll (CreatureObject *player, CreatureObject *creature)
int healEnhance (CreatureObject *enhancer, CreatureObject *patient, byte attribute, int buffvalue, float duration)
void disseminateExperience (TangibleObject *destructedObject, ThreatMap *threatMap)
int calculatePlayerLevel (CreatureObject *player)
void sendLoginMessage (CreatureObject *player)
void resendLoginMessageToAll ()
void sendActivateCloneRequest (CreatureObject *player, int typeofdeath=0)
void sendPlayerToCloner (CreatureObject *player, unsigned long long clonerID, int typeofdeath=0)
void ejectPlayerFromBuilding (CreatureObject *player)
bool checkExistentNameInDatabase (const String &firstName)
Reference< TangibleObject * > createHairObject (const String &hairObjectFile, const String &hairCustomization)
void createTutorialBuilding (CreatureObject *player)
void createSkippedTutorialBuilding (CreatureObject *player)
void updateSwimmingState (CreatureObject *player, float newZ, IntersectionResults *intersections=NULL, CloseObjectsVector *closeObjects=NULL)
int checkSpeedHackFirstTest (CreatureObject *player, float parsedSpeed, ValidatedPosition &teleportPosition, float errorMultiplier=1)
int checkSpeedHackSecondTest (CreatureObject *player, float newX, float newZ, float newY, unsigned int newStamp, SceneObject *newParent=NULL)
bool existsName (const String &name)
unsigned long long getObjectID (const String &name)
Reference< CreatureObject * > getPlayer (const String &name)
void updatePermissionLevel (CreatureObject *player, int adminLevel=1)
void updatePermissionName (CreatureObject *player, int adminLevel)
void addPlayer (CreatureObject *player)
void removePlayer (String &playerName)
String getBadgeKey (int idx)
CraftingStation * getNearbyCraftingStation (CreatureObject *player, int type)
void finishHologrind (CreatureObject *player)
Account * getAccount (const String &username)
Account * getAccount (unsigned int accountID)
String banAccount (PlayerObject *admin, Account *account, unsigned int seconds, const String &reason)
String unbanAccount (PlayerObject *admin, Account *account, const String &reason)
String banFromGalaxy (PlayerObject *admin, Account *account, unsigned const int galaxy, unsigned int seconds, const String &reason)
String unbanFromGalaxy (PlayerObject *admin, Account *account, unsigned const int galaxy, const String &reason)
String banCharacter (PlayerObject *admin, Account *account, const String &name, unsigned int galaxyID, unsigned int seconds, const String &reason)
String unbanCharacter (PlayerObject *admin, Account *account, const String &name, unsigned int galaxyID, const String &reason)
bool promptTeachableSkills (CreatureObject *teacher, SceneObject *target)
void decreaseOnlineCharCount (ZoneClientSession *client)
bool increaseOnlineCharCountIfPossible (ZoneClientSession *client)
void fixHAM (CreatureObject *player)
bool offerTeaching (CreatureObject *teacher, CreatureObject *student, Skill *skill)
bool acceptTeachingOffer (CreatureObject *teacher, CreatureObject *student, Skill *skill)
SortedVector< String > getTeachableSkills (CreatureObject *teacher, CreatureObject *student)
OnlineZoneClientMap * getOnlineZoneClientMap ()
void getCleanupCharacterCount ()
void cleanupCharacters ()
bool shouldDeleteCharacter (unsigned long long characterID, int galaxyID)
void enhanceCharacter (CreatureObject *player)
operator const PlayerManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< PlayerManager * > _this
Static Public Attributes
static int MAX_CHAR_ONLINE_COUNT = 2
Protected Member Functions
virtual ~PlayerManagerImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Static Protected Attributes
static const int performanceBuff = 1000
static const int medicalBuff = 1900
static const int performanceDuration = 7200
static const int medicalDuration = 7200
Private Member Functions
void loadStartingItems ()
void loadStartingLocations ()
void loadBadgeMap ()
void loadPermissionLevels ()
Account * queryForAccount (const String &query)
bool doEnhanceCharacter (unsigned int crc, CreatureObject *player, int amount, int duration, int buffType, byte attribute)
Private Attributes
ManagedReference
< ZoneProcessServer * > processor
VectorMap< int, String > badgeMap
int highestBadgeIndex
ManagedReference< ZoneServer * > server
Reference< PlayerMap * > playerMap
Reference< CharacterNameMap * > nameMap
float globalExpMultiplier
ReadWriteLock onlineMapMutex
OnlineZoneClientMap onlineZoneClientMap
Reference< StartingItemList * > startingItemList
Reference< PermissionLevelList * > permissionLevelList
StartingLocationList startingLocationList
Friends
class PlayerManager
Detailed Description
Definition at line 530 of file PlayerManager.h.
Constructor & Destructor Documentation
PlayerManagerImplementation::PlayerManagerImplementation (ZoneServer * zoneServer, ZoneProcessServer * impl)
Definition at line 109 of file PlayerManagerImplementation.cpp.
References globalExpMultiplier, ServerDatabase::instance(), loadBadgeMap(), loadNameMap(), loadPermissionLevels(), loadStartingItems(), loadStartingLocations(), nameMap, playerMap, processor, server, and ServerCore::truncateDatabases().
PlayerManagerImplementation::PlayerManagerImplementation (DummyConstructorParameter * param)
Definition at line 1251 of file PlayerManager.cpp.
References _initializeImplementation().
PlayerManagerImplementation::~PlayerManagerImplementation () protected virtual
Definition at line 1256 of file PlayerManager.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * PlayerManagerImplementation::_getStub ()
Definition at line 1274 of file PlayerManager.cpp.
References _this.
void PlayerManagerImplementation::_initializeImplementation () protected
Definition at line 1261 of file PlayerManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by PlayerManagerImplementation().
void PlayerManagerImplementation::_serializationHelperMethod () protected
Definition at line 1310 of file PlayerManager.cpp.
Referenced by _initializeImplementation().
void PlayerManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 1269 of file PlayerManager.cpp.
References _this.
Referenced by server::zone::managers::player::PlayerManager::PlayerManager().
bool PlayerManagerImplementation::acceptTeachingOffer (CreatureObject * teacher, CreatureObject * student, Skill * skill)
Accepts a teaching office.
Precondition
student crosslocked with teacher
Postcondition
student crosslocked with teacher
Definition at line 3074 of file PlayerManagerImplementation.cpp.
References awardExperience(), server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getGroup(), Skill::getSkillName(), Skill::getTotalChildren(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::managers::skill::SkillManager::isApprenticeshipEnabled(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTO(), and server::chat::StringIdChatParameter::setTT().
Referenced by server::zone::managers::player::PlayerManager::acceptTeachingOffer().
void PlayerManagerImplementation::addInsurableItemsRecursive (SceneObject * obj, SortedVector< ManagedReference< SceneObject * > > * items, bool onlyInsurable)
Definition at line 2492 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::tangible::TangibleObject::getOptionsBitmask(), OptionBitmask::INSURED, server::zone::objects::scene::SceneObject::isArmorObject(), server::zone::objects::scene::SceneObject::isContainerObject(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::objects::scene::SceneObject::isWeaponObject(), and server::zone::objects::scene::SceneObject::isWearableObject().
Referenced by server::zone::managers::player::PlayerManager::addInsurableItemsRecursive(), and getInsurableItems().
void PlayerManagerImplementation::addPlayer (CreatureObject * player)
Definition at line 1404 of file PlayerManager.cpp.
References nameMap.
Referenced by server::zone::managers::player::PlayerManager::addPlayer().
void PlayerManagerImplementation::applyEncumbrancies (CreatureObject * player, ArmorObject * armor)
Definition at line 1025 of file PlayerManagerImplementation.cpp.
References CreatureEncumbrance::ACTION, server::zone::objects::creature::CreatureObject::addEncumbrance(), server::zone::objects::creature::CreatureObject::addMaxHAM(), CreatureAttribute::CONSTITUTION, CreatureAttribute::FOCUS, server::zone::objects::tangible::wearables::ArmorObject::getActionEncumbrance(), server::zone::objects::tangible::wearables::ArmorObject::getHealthEncumbrance(), server::zone::objects::tangible::wearables::ArmorObject::getMindEncumbrance(), CreatureEncumbrance::HEALTH, server::zone::objects::creature::CreatureObject::inflictDamage(), CreatureEncumbrance::MIND, CreatureAttribute::QUICKNESS, CreatureAttribute::STAMINA, CreatureAttribute::STRENGTH, and CreatureAttribute::WILLPOWER.
Referenced by server::zone::managers::player::PlayerManager::applyEncumbrancies().
void PlayerManagerImplementation::awardBadge (PlayerObject * ghost, unsigned int badge)
Definition at line 1082 of file PlayerManagerImplementation.cpp.
References ObserverEventType::BADGEAWARDED, Badge::BDG_EXP_10_BADGES, Badge::BDG_EXP_20_BADGES, Badge::BDG_EXP_30_BADGES, Badge::BDG_EXP_40_BADGES, Badge::BDG_EXP_45_BADGES, Badge::COUNT_10, Badge::COUNT_100, Badge::COUNT_125, Badge::COUNT_25, Badge::COUNT_5, Badge::COUNT_50, Badge::COUNT_75, Badge::exists(), Badge::EXPLORATION, server::zone::objects::player::PlayerObject::getBadgeTypeCount(), Badge::getName(), server::zone::objects::player::PlayerObject::getNumBadges(), server::zone::objects::scene::SceneObject::getParent(), Badge::getType(), server::zone::objects::player::PlayerObject::hasBadge(), server::zone::objects::player::PlayerObject::setBadge(), server::zone::objects::scene::variables::StringId::setStringId(), and server::chat::StringIdChatParameter::setTO().
Referenced by server::zone::managers::player::PlayerManager::awardBadge().
void PlayerManagerImplementation::awardExperience (CreatureObject * player, const String & xpType, int amount, bool sendSystemMessage = true, float localMultiplier = 1.0f)
Definition at line 1163 of file PlayerManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addExperience(), server::zone::objects::creature::CreatureObject::getPlayerObject(), globalExpMultiplier, server::zone::objects::player::PlayerObject::hasCappedExperience(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), and ObserverEventType::XPAWARDED.
Referenced by acceptTeachingOffer(), server::zone::managers::player::PlayerManager::awardExperience(), disseminateExperience(), and sendPlayerToCloner().
String PlayerManagerImplementation::banAccount (PlayerObject * admin, Account * account, unsigned int seconds, const String & reason)
Definition at line 2681 of file PlayerManagerImplementation.cpp.
References server::login::account::Account::getAccountID(), server::zone::objects::player::PlayerObject::getAccountID(), server::login::account::Account::getCharacterList(), CharacterListEntry::getFirstName(), CharacterListEntry::getGalaxyID(), getPlayer(), ServerDatabase::instance(), server::zone::objects::player::PlayerObject::isPrivileged(), and server.
Referenced by server::zone::managers::player::PlayerManager::banAccount(), and kickUser().
String PlayerManagerImplementation::banCharacter (PlayerObject * admin, Account * account, const String & name, unsigned int galaxyID, unsigned int seconds, const String & reason)
Definition at line 2820 of file PlayerManagerImplementation.cpp.
References server::login::account::Account::getAccountID(), server::zone::objects::player::PlayerObject::getAccountID(), getPlayer(), ServerDatabase::instance(), and server::zone::objects::player::PlayerObject::isPrivileged().
Referenced by server::zone::managers::player::PlayerManager::banCharacter().
String PlayerManagerImplementation::banFromGalaxy (PlayerObject * admin, Account * account, unsigned const int galaxy, unsigned int seconds, const String & reason)
Definition at line 2750 of file PlayerManagerImplementation.cpp.
References server::login::account::Account::getAccountID(), server::zone::objects::player::PlayerObject::getAccountID(), server::login::account::Account::getCharacterList(), CharacterListEntry::getFirstName(), CharacterListEntry::getGalaxyID(), getPlayer(), ServerDatabase::instance(), server::zone::objects::player::PlayerObject::isPrivileged(), and server.
Referenced by server::zone::managers::player::PlayerManager::banFromGalaxy().
uint8 PlayerManagerImplementation::calculateIncapacitationTimer (CreatureObject * player, int condition)
Calculates the length of time that incapacitation should last. Cannot exceed 1 minute.
Returns
Returns the number of seconds until the player should recover from incapacitation.
Definition at line 525 of file PlayerManagerImplementation.cpp.
Referenced by server::zone::managers::player::PlayerManager::calculateIncapacitationTimer(), and notifyDestruction().
int PlayerManagerImplementation::calculatePlayerLevel (CreatureObject * player)
Definition at line 2545 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::error(), server::zone::objects::creature::CreatureObject::getSkillMod(), and server::zone::objects::creature::CreatureObject::getWeapon().
Referenced by server::zone::managers::player::PlayerManager::calculatePlayerLevel(), and disseminateExperience().
bool PlayerManagerImplementation::canGroupMemberHarvestCorpse (CreatureObject * player, Creature * creature)
Definition at line 3269 of file PlayerManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::group::GroupObject::getGroupSize(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::Creature::hasSkillToHarvestMe(), server::zone::objects::creature::CreatureObject::isGrouped(), and server::zone::objects::scene::SceneObject::isInRange().
Referenced by server::zone::managers::player::PlayerManager::canGroupMemberHarvestCorpse(), and shouldRescheduleCorpseDestruction().
bool PlayerManagerImplementation::checkEncumbrancies (CreatureObject * player, ArmorObject * armor)
Check for enough encumbrances
Definition at line 1004 of file PlayerManagerImplementation.cpp.
References CreatureAttribute::CONSTITUTION, CreatureAttribute::FOCUS, server::zone::objects::tangible::wearables::ArmorObject::getActionEncumbrance(), server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::tangible::wearables::ArmorObject::getHealthEncumbrance(), server::zone::objects::tangible::wearables::ArmorObject::getMindEncumbrance(), CreatureAttribute::QUICKNESS, CreatureAttribute::STAMINA, CreatureAttribute::STRENGTH, and CreatureAttribute::WILLPOWER.
Referenced by server::zone::managers::player::PlayerManager::checkEncumbrancies().
bool PlayerManagerImplementation::checkExistentNameInDatabase (const String & firstName)
Definition at line 351 of file PlayerManagerImplementation.cpp.
References ServerDatabase::instance().
Referenced by server::zone::managers::player::PlayerManager::checkExistentNameInDatabase().
bool PlayerManagerImplementation::checkPlayerName (MessageCallback * callback)
Definition at line 372 of file PlayerManagerImplementation.cpp.
References NameManagerResult::ACCEPTED, NameManagerResult::DECLINED_DEVELOPER, NameManagerResult::DECLINED_EMPTY, NameManagerResult::DECLINED_FICT_RESERVED, NameManagerResult::DECLINED_PROFANE, NameManagerResult::DECLINED_RACE_INAPP, NameManagerResult::DECLINED_RESERVED, NameManagerResult::DECLINED_SYNTAX, ClientCreateCharacterCallback::getCharacterName(), server::zone::packets::MessageCallback::getClient(), ClientCreateCharacterCallback::getSpecies(), nameMap, processor, and server::zone::managers::name::NameManager::validateName().
Referenced by server::zone::managers::player::PlayerManager::checkPlayerName().
int PlayerManagerImplementation::checkSpeedHackFirstTest (CreatureObject * player, float parsedSpeed, ValidatedPosition & teleportPosition, float errorMultiplier = 1)
Definition at line 2238 of file PlayerManagerImplementation.cpp.
References SpeedModChange::getNewSpeed(), ValidatedPosition::getParent(), server::zone::objects::scene::SceneObject::getParent(), ValidatedPosition::getPosition(), server::zone::objects::creature::CreatureObject::getRunSpeed(), server::zone::objects::creature::CreatureObject::getSpeedMultiplierMod(), server::zone::objects::creature::CreatureObject::getSpeedMultiplierModChanges(), SpeedModChange::getTimeStamp(), server::zone::objects::scene::SceneObject::info(), and server::zone::objects::scene::SceneObject::teleport().
Referenced by server::zone::managers::player::PlayerManager::checkSpeedHackFirstTest(), and checkSpeedHackSecondTest().
int PlayerManagerImplementation::checkSpeedHackSecondTest (CreatureObject * player, float newX, float newZ, float newY, unsigned int newStamp, SceneObject * newParent = NULL)
Definition at line 2313 of file PlayerManagerImplementation.cpp.
References checkSpeedHackFirstTest(), server::zone::objects::player::PlayerObject::getClientLastMovementStamp(), server::zone::objects::player::PlayerObject::getLastValidatedPosition(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getRootParent(), server::zone::objects::player::PlayerObject::getServerMovementTimeDelta(), ValidatedPosition::getWorldPosition(), server, ValidatedPosition::setParent(), ValidatedPosition::setPosition(), and server::zone::objects::player::PlayerObject::updateServerLastMovementStamp().
Referenced by server::zone::managers::player::PlayerManager::checkSpeedHackSecondTest().
bool PlayerManagerImplementation::checkTradeItems (CreatureObject * player, CreatureObject * receiver)
Definition at line 1360 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::canAddObject(), server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::getContainerVolumeLimit(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::hasObjectInContainer(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and SessionFacadeType::TRADE.
Referenced by server::zone::managers::player::PlayerManager::checkTradeItems(), and handleVerifyTradeMessage().
void PlayerManagerImplementation::cleanupCharacters ()
Definition at line 3357 of file PlayerManagerImplementation.cpp.
References server::zone::ZoneServer::getGalaxyID(), ServerCore::getZoneServer(), server, and shouldDeleteCharacter().
Referenced by server::zone::managers::player::PlayerManager::cleanupCharacters().
Reference< TangibleObject * > PlayerManagerImplementation::createHairObject (const String & hairObjectFile, const String & hairCustomization)
Definition at line 440 of file PlayerManagerImplementation.cpp.
References SceneObjectType::GENERICITEM, server, and server::zone::objects::tangible::TangibleObject::setCustomizationString().
Referenced by server::zone::managers::player::PlayerManager::createHairObject().
bool PlayerManagerImplementation::createPlayer (MessageCallback * callback)
Definition at line 144 of file PlayerManagerImplementation.cpp.
References server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
Referenced by server::zone::managers::player::PlayerManager::createPlayer().
void PlayerManagerImplementation::createSkippedTutorialBuilding (CreatureObject * player)
Definition at line 498 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::Zone::getZoneName(), server, server::zone::objects::player::PlayerObject::setSavedParentID(), server::zone::objects::player::PlayerObject::setSavedTerrainName(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::managers::player::PlayerManager::createSkippedTutorialBuilding().
void PlayerManagerImplementation::createTutorialBuilding (CreatureObject * player)
Definition at line 471 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::Zone::getZoneName(), server, server::zone::objects::player::PlayerObject::setSavedParentID(), server::zone::objects::player::PlayerObject::setSavedTerrainName(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::managers::player::PlayerManager::createTutorialBuilding().
void PlayerManagerImplementation::decreaseOnlineCharCount (ZoneClientSession * client)
Definition at line 3144 of file PlayerManagerImplementation.cpp.
References OnlineZoneClientMap::accountLoggedOut(), server::zone::ZoneClientSession::getAccountID(), server::zone::ZoneClientSession::getSession(), onlineMapMutex, and onlineZoneClientMap.
Referenced by server::zone::managers::player::PlayerManager::decreaseOnlineCharCount().
void PlayerManagerImplementation::disseminateExperience (TangibleObject * destructedObject, ThreatMap * threatMap)
Definition at line 896 of file PlayerManagerImplementation.cpp.
References awardExperience(), calculatePlayerLevel(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::Zone::getGCWManager(), server::zone::managers::gcw::GCWManager::getGCWXPBonus(), server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::tangible::TangibleObject::getLevel(), server::zone::objects::tangible::threat::ThreatMap::getTotalDamage(), server::zone::managers::gcw::GCWManager::getWinningFaction(), server::zone::objects::scene::SceneObject::getWorldPosition(), server::zone::objects::scene::SceneObject::getWorldPositionX(), server::zone::objects::scene::SceneObject::getWorldPositionY(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::tangible::threat::ThreatMap::removeAll().
Referenced by server::zone::managers::player::PlayerManager::disseminateExperience().
bool PlayerManagerImplementation::doEnhanceCharacter (unsigned int crc, CreatureObject * player, int amount, int duration, int buffType, byte attribute) private
Creates and adds buff to Player
Precondition
{ player is locked }
Postcondition
{ player is locked }
Returns
true if it was added
Parameters
crc CRC of the buff, player target of buff, amount is the attribute modifier for the buff, duration of the buff, buffType specifies whether medical or performance and attribute sets the creature attribute to modify
Definition at line 3453 of file PlayerManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::addBuff(), and server::zone::objects::creature::CreatureObject::hasBuff().
Referenced by enhanceCharacter().
void PlayerManagerImplementation::ejectPlayerFromBuilding (CreatureObject * player)
Definition at line 869 of file PlayerManagerImplementation.cpp.
References server::zone::objects::building::BuildingObject::getEjectionPoint(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), and server::zone::objects::scene::SceneObject::switchZone().
Referenced by server::zone::managers::player::PlayerManager::ejectPlayerFromBuilding().
void PlayerManagerImplementation::enhanceCharacter (CreatureObject * player)
Enhances the target character with doc/ent buffs
Precondition
{ player is locked }
Postcondition
{ player is locked }
Definition at line 3467 of file PlayerManagerImplementation.cpp.
References doEnhanceCharacter(), BuffType::MEDICAL, medicalBuff, medicalDuration, BuffType::PERFORMANCE, performanceBuff, performanceDuration, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::player::PlayerManager::enhanceCharacter().
bool PlayerManagerImplementation::existsName (const String & name)
Definition at line 252 of file PlayerManagerImplementation.cpp.
References nameMap, rlock(), and runlock().
Referenced by server::zone::managers::player::PlayerManager::existsName().
void PlayerManagerImplementation::finalize ()
Definition at line 218 of file PlayerManagerImplementation.cpp.
References nameMap, and playerMap.
Referenced by ~PlayerManagerImplementation().
void PlayerManagerImplementation::finishHologrind (CreatureObject * player)
Definition at line 2609 of file PlayerManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::HOLOGRIND_UNLOCK, SuiWindowType::NONE, and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::managers::player::PlayerManager::finishHologrind().
void PlayerManagerImplementation::fixHAM (CreatureObject * player)
Definition at line 2887 of file PlayerManagerImplementation.cpp.
References server::zone::objects::creature::buffs::Buff::getAttributeModifiers(), server::zone::objects::creature::CreatureObject::getBaseHAM(), BuffList::getBuffByIndex(), server::zone::objects::creature::CreatureObject::getBuffList(), BuffList::getBuffListSize(), server::zone::objects::creature::CreatureObject::getEncumbrance(), server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::creature::CreatureObject::getMaxHAM(), server::zone::objects::creature::CreatureObject::removeBuff(), server::zone::objects::creature::CreatureObject::setHAM(), and server::zone::objects::creature::CreatureObject::setMaxHAM().
Referenced by server::zone::managers::player::PlayerManager::fixHAM().
Account * PlayerManagerImplementation::getAccount (const String & username)
Definition at line 2629 of file PlayerManagerImplementation.cpp.
References queryForAccount().
Referenced by server::zone::managers::player::PlayerManager::getAccount(), and kickUser().
Account* server::zone::managers::player::PlayerManagerImplementation::getAccount (unsigned int accountID)
String PlayerManagerImplementation::getBadgeKey (int idx)
Definition at line 2561 of file PlayerManagerImplementation.cpp.
References badgeMap.
Referenced by server::zone::managers::player::PlayerManager::getBadgeKey().
void PlayerManagerImplementation::getCleanupCharacterCount ()
Definition at line 3310 of file PlayerManagerImplementation.cpp.
References server::zone::ZoneServer::getGalaxyID(), ServerCore::getZoneServer(), server, and shouldDeleteCharacter().
Referenced by server::zone::managers::player::PlayerManager::getCleanupCharacterCount().
int PlayerManagerImplementation::getHighestBadgeIndex ()
Definition at line 1399 of file PlayerManager.cpp.
References highestBadgeIndex.
Referenced by server::zone::managers::player::PlayerManager::getHighestBadgeIndex().
StructureObject * PlayerManagerImplementation::getInRangeOwnedStructure (CreatureObject * creature, float range = 128)
Definition at line 2080 of file PlayerManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), and server::zone::objects::scene::SceneObject::getZone().
Referenced by server::zone::managers::player::PlayerManager::getInRangeOwnedStructure().
SceneObject * PlayerManagerImplementation::getInRangeStructureWithAdminRights (CreatureObject * creature, unsigned long long targetID = 0)
Finds the closest structure in range with Administration priveleges. This is primarily used for commands that require a building or installation. First checks the passed targetID, then checks if the player is inside a building. Finally searches for an installation in range.
Precondition
: creature locked, zone unlocked
Postcondition
: creature locked, zone unlocked
Parameters
targetID The object id of the players target.
Definition at line 2020 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getRootParent(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::structure::StructureObject::isOnAdminList(), and server.
Referenced by server::zone::managers::player::PlayerManager::getInRangeStructureWithAdminRights().
SortedVector< ManagedReference< SceneObject * > > PlayerManagerImplementation::getInsurableItems (CreatureObject * player, bool onlyInsurable = true)
Definition at line 2512 of file PlayerManagerImplementation.cpp.
References addInsurableItemsRecursive(), server::zone::objects::tangible::TangibleObject::getOptionsBitmask(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getSlottedObjectsSize(), OptionBitmask::INSURED, server::zone::objects::scene::SceneObject::isArmorObject(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::objects::scene::SceneObject::isWeaponObject(), and server::zone::objects::scene::SceneObject::isWearableObject().
Referenced by server::zone::managers::player::PlayerManager::getInsurableItems(), and sendPlayerToCloner().
CraftingStation * PlayerManagerImplementation::getNearbyCraftingStation (CreatureObject * player, int type)
Definition at line 2567 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isCraftingStation(), server::zone::objects::scene::SceneObject::isInRange(), and server.
Referenced by server::zone::managers::player::PlayerManager::getNearbyCraftingStation().
uint64 PlayerManagerImplementation::getObjectID (const String & name)
Definition at line 339 of file PlayerManagerImplementation.cpp.
References nameMap, rlock(), and runlock().
Referenced by server::zone::managers::player::PlayerManager::getObjectID().
OnlineZoneClientMap * PlayerManagerImplementation::getOnlineZoneClientMap ()
Definition at line 1414 of file PlayerManager.cpp.
References onlineZoneClientMap.
Referenced by server::zone::managers::player::PlayerManager::getOnlineZoneClientMap().
Reference< CreatureObject * > PlayerManagerImplementation::getPlayer (const String & name)
Definition at line 319 of file PlayerManagerImplementation.cpp.
References nameMap, rlock(), runlock(), and server.
Referenced by banAccount(), banCharacter(), banFromGalaxy(), and server::zone::managers::player::PlayerManager::getPlayer().
StartingLocation * PlayerManagerImplementation::getStartingLocation (const String & city)
Definition at line 2478 of file PlayerManagerImplementation.cpp.
References StartingLocation::getLocation(), and startingLocationList.
Referenced by server::zone::managers::player::PlayerManager::getStartingLocation().
SortedVector< String > PlayerManagerImplementation::getTeachableSkills (CreatureObject * teacher, CreatureObject * student)
Gets a vector skillboxes this teacher can teach this student.
Precondition
student crosslocked with teacher
Postcondition
student crosslocked with teacher
Definition at line 3124 of file PlayerManagerImplementation.cpp.
References server::zone::managers::skill::SkillManager::canLearnSkill(), server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::creature::CreatureObject::getSkillList(), Skill::getSkillName(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
Referenced by server::zone::managers::player::PlayerManager::getTeachableSkills(), and promptTeachableSkills().
void PlayerManagerImplementation::handleAbortTradeMessage (CreatureObject * player)
Definition at line 1206 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::dropActiveSession(), server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::sendMessage(), server, and SessionFacadeType::TRADE.
Referenced by server::zone::managers::player::PlayerManager::handleAbortTradeMessage(), handleAddItemToTradeWindow(), and handleVerifyTradeMessage().
void PlayerManagerImplementation::handleAcceptTransactionMessage (CreatureObject * player)
Definition at line 1317 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::creature::CreatureObject::sendMessage(), server, server::zone::objects::player::sessions::TradeSession::setAcceptedTrade(), and SessionFacadeType::TRADE.
Referenced by server::zone::managers::player::PlayerManager::handleAcceptTransactionMessage().
void PlayerManagerImplementation::handleAddItemToTradeWindow (CreatureObject * player, unsigned long long itemID)
Definition at line 1245 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::player::sessions::TradeSession::getTradeTargetPlayer(), handleAbortTradeMessage(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::SceneObject::sendWithoutContainerObjectsTo(), server, and SessionFacadeType::TRADE.
Referenced by server::zone::managers::player::PlayerManager::handleAddItemToTradeWindow().
void PlayerManagerImplementation::handleGiveMoneyMessage (CreatureObject * player, unsigned int value)
Definition at line 1291 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::creature::CreatureObject::sendMessage(), server, server::zone::objects::player::sessions::TradeSession::setMoneyToTrade(), and SessionFacadeType::TRADE.
Referenced by server::zone::managers::player::PlayerManager::handleGiveMoneyMessage().
void PlayerManagerImplementation::handleUnAcceptTransactionMessage (CreatureObject * player)
Definition at line 1338 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::creature::CreatureObject::sendMessage(), server, server::zone::objects::player::sessions::TradeSession::setAcceptedTrade(), and SessionFacadeType::TRADE.
Referenced by server::zone::managers::player::PlayerManager::handleUnAcceptTransactionMessage().
void PlayerManagerImplementation::handleVerifyTradeMessage (CreatureObject * player)
Definition at line 1503 of file PlayerManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::addCashCredits(), checkTradeItems(), server::zone::objects::scene::SceneObject::dropActiveSession(), server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getSlottedObject(), handleAbortTradeMessage(), server::zone::objects::creature::CreatureObject::sendMessage(), server, server::zone::objects::player::sessions::TradeSession::setVerifiedTrade(), server::zone::objects::creature::CreatureObject::subtractCashCredits(), and SessionFacadeType::TRADE.
Referenced by server::zone::managers::player::PlayerManager::handleVerifyTradeMessage().
int PlayerManagerImplementation::healEnhance (CreatureObject * enhancer, CreatureObject * patient, byte attribute, int buffvalue, float duration)
Enhances the patients attribute by a specified amount for a specified duration.
Parameters
patient The patient to enhance.
attribute The attribute to enhance.
buffvalue The amount to enhance the attribute.
duration The duration in seconds the enhancement will last.
Returns
The amount that was enhanced. If a buff existed, this is the amount exceeding the previous buff.
Definition at line 1661 of file PlayerManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::addBuff(), ObserverEventType::ENHANCINGPERFORMED, server::zone::objects::creature::buffs::Buff::getAttributeModifierValue(), server::zone::objects::creature::CreatureObject::getBuff(), BuffAttribute::getName(), BuffAttribute::getProtectionString(), server::zone::objects::creature::buffs::Buff::getSkillModifierValue(), server::zone::objects::creature::CreatureObject::hasBuff(), BuffAttribute::isProtection(), BuffType::MEDICAL, and server::zone::objects::creature::buffs::Buff::setSkillModifier().
Referenced by server::zone::managers::player::PlayerManager::healEnhance().
bool PlayerManagerImplementation::increaseOnlineCharCountIfPossible (ZoneClientSession * client)
Definition at line 3177 of file PlayerManagerImplementation.cpp.
References OnlineZoneClientMap::addAccount(), server::zone::ZoneClientSession::getAccountID(), server::zone::ZoneClientSession::getPlayer(), server::zone::ZoneClientSession::getSession(), MAX_CHAR_ONLINE_COUNT, onlineMapMutex, and onlineZoneClientMap.
Referenced by server::zone::managers::player::PlayerManager::increaseOnlineCharCountIfPossible().
bool PlayerManagerImplementation::kickUser (const String & name, const String & admin, String & reason, bool doBan = true)
Kicks a user
10 min ban
Definition at line 269 of file PlayerManagerImplementation.cpp.
References banAccount(), getAccount(), server::zone::objects::scene::SceneObject::getSlottedObject(), server, and server::zone::objects::player::PlayerObject::setLoggingOut().
Referenced by server::zone::managers::player::PlayerManager::kickUser().
void PlayerManagerImplementation::killPlayer (TangibleObject * attacker, CreatureObject * player, int typeofdeath = 0)
Precondition
{ attacker and player locked }
Postcondition
{ attacker and player locked }
Definition at line 618 of file PlayerManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::clearBuffs(), CreaturePosture::DEAD, server::zone::objects::creature::CreatureObject::executeObjectControllerAction(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isRidingMount(), server::zone::objects::creature::CreatureObject::notifyObjectKillObservers(), server::zone::objects::player::PlayerObject::requestedDuelTo(), sendActivateCloneRequest(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setCurrentSpeed(), server::zone::objects::creature::CreatureObject::setPosture(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTT(), server::zone::objects::creature::CreatureObject::updateLocomotion(), and server::zone::objects::creature::CreatureObject::updateTimeOfDeath().
Referenced by server::zone::managers::player::PlayerManager::killPlayer(), and notifyDestruction().
void PlayerManagerImplementation::loadBadgeMap () private
Definition at line 175 of file PlayerManagerImplementation.cpp.
References badgeMap, DataTableRow::getCell(), DataTableIff::getRow(), DataTableIff::getTotalRows(), DataTableCell::getValue(), highestBadgeIndex, and DataTableIff::readObject().
Referenced by PlayerManagerImplementation().
void PlayerManagerImplementation::loadNameMap ()
Definition at line 226 of file PlayerManagerImplementation.cpp.
References ServerDatabase::instance(), nameMap, and server.
Referenced by server::zone::managers::player::PlayerManager::loadNameMap(), and PlayerManagerImplementation().
void PlayerManagerImplementation::loadPermissionLevels () private
Definition at line 205 of file PlayerManagerImplementation.cpp.
References permissionLevelList.
Referenced by PlayerManagerImplementation().
void PlayerManagerImplementation::loadStartingItems () private
Definition at line 149 of file PlayerManagerImplementation.cpp.
References startingItemList.
Referenced by PlayerManagerImplementation().
void PlayerManagerImplementation::loadStartingLocations () private
Definition at line 160 of file PlayerManagerImplementation.cpp.
References StartingLocationList::getTotalLocations(), StartingLocationList::parseFromIffStream(), and startingLocationList.
Referenced by PlayerManagerImplementation().
void PlayerManagerImplementation::lock (bool doLock = true) protected
Definition at line 1282 of file PlayerManager.cpp.
References _this.
void PlayerManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 1286 of file PlayerManager.cpp.
References _this.
void PlayerManagerImplementation::lootAll (CreatureObject * player, CreatureObject * creature)
Definition at line 2406 of file PlayerManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::addCashCredits(), server::zone::objects::creature::CreatureObject::executeObjectControllerAction(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::getContainerPermissions(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::objects::creature::CreatureObject::getGroupID(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::variables::ContainerPermissions::getOwnerID(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::creature::CreatureObject::isDead(), rescheduleCorpseDestruction(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setCashCredits(), server::chat::StringIdChatParameter::setDI(), and server::chat::StringIdChatParameter::setTT().
Referenced by server::zone::managers::player::PlayerManager::lootAll().
int PlayerManagerImplementation::notifyDestruction (TangibleObject * destructor, TangibleObject * destructedObject, int condition)
Precondition
{ destructor and destructedObject locked }
Postcondition
{ destructor and destructedObject locked }
Definition at line 559 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::addPendingTask(), calculateIncapacitationTimer(), server::zone::objects::creature::CreatureObject::clearDots(), server::zone::objects::creature::CreatureObject::executeObjectControllerAction(), server::zone::objects::player::PlayerObject::getIncapacitationCounter(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getPendingTask(), server::zone::objects::creature::CreatureObject::getPlayerObject(), CreaturePosture::INCAPACITATED, server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::player::PlayerObject::isFirstIncapacitationExpired(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::tangible::TangibleObject::isKiller(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isRidingMount(), killPlayer(), server::zone::objects::tangible::TangibleObject::removeDefender(), server::zone::objects::scene::SceneObject::removePendingTask(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::tangible::TangibleObject::setCountdownTimer(), server::zone::objects::creature::CreatureObject::setCurrentSpeed(), server::zone::objects::creature::CreatureObject::setPosture(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTT(), server::zone::objects::player::PlayerObject::updateIncapacitationCounter(), and server::zone::objects::creature::CreatureObject::updateLocomotion().
Referenced by server::zone::managers::player::PlayerManager::notifyDestruction().
int PlayerManagerImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 1596 of file PlayerManagerImplementation.cpp.
References CreatureState::ALERT, LogoutTask::cancelLogout(), server::zone::objects::creature::CreatureObject::clearState(), server::zone::objects::creature::CreatureObject::getMoodID(), server::zone::objects::scene::SceneObject::getPendingTask(), server::zone::objects::creature::CreatureObject::hasState(), ObserverEventType::POSTURECHANGED, server::zone::objects::scene::SceneObject::removePendingTask(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::objects::creature::CreatureObject::setMood().
Referenced by server::zone::managers::player::PlayerManager::notifyObserverEvent().
bool PlayerManagerImplementation::offerTeaching (CreatureObject * teacher, CreatureObject * student, Skill * skill)
Sends a confirmation box to the student asking if they want to learn the skill.
Precondition
student crosslocked with teacher
Postcondition
student crosslocked with teacher
Definition at line 3031 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), Skill::getSkillName(), server::zone::managers::stringid::StringIdManager::getStringId(), Skill::getXpCost(), Skill::getXpType(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), and SuiWindowType::TEACH_OFFER.
Referenced by server::zone::managers::player::PlayerManager::offerTeaching().
PlayerManagerImplementation::operator const PlayerManager * ()
Definition at line 1278 of file PlayerManager.cpp.
bool PlayerManagerImplementation::promptTeachableSkills (CreatureObject * teacher, SceneObject * target)
Definition at line 2952 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::creature::CreatureObject::getPlayerObject(), getTeachableSkills(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::chat::StringIdChatParameter::setTT(), SuiWindowType::TEACH_OFFER, and SuiWindowType::TEACH_SKILL.
Referenced by server::zone::managers::player::PlayerManager::promptTeachableSkills().
Account * PlayerManagerImplementation::queryForAccount (const String & query) private
Definition at line 2649 of file PlayerManagerImplementation.cpp.
References ServerDatabase::instance(), server::login::account::Account::setAccountID(), server::login::account::Account::setActive(), server::login::account::Account::setAdminLevel(), server::login::account::Account::setStationID(), server::login::account::Account::setTimeCreated(), server::login::account::Account::setUsername(), and server::login::account::Account::updateFromDatabase().
Referenced by getAccount().
void PlayerManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 1317 of file PlayerManager.cpp.
References readObjectMember().
bool PlayerManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 1336 of file PlayerManager.cpp.
References globalExpMultiplier, highestBadgeIndex, and server.
Referenced by readObject().
void PlayerManagerImplementation::removeEncumbrancies (CreatureObject * player, ArmorObject * armor)
Definition at line 1053 of file PlayerManagerImplementation.cpp.
References CreatureEncumbrance::ACTION, server::zone::objects::creature::CreatureObject::addEncumbrance(), server::zone::objects::creature::CreatureObject::addMaxHAM(), CreatureAttribute::CONSTITUTION, CreatureAttribute::FOCUS, server::zone::objects::tangible::wearables::ArmorObject::getActionEncumbrance(), server::zone::objects::tangible::wearables::ArmorObject::getHealthEncumbrance(), server::zone::objects::tangible::wearables::ArmorObject::getMindEncumbrance(), server::zone::objects::creature::CreatureObject::healDamage(), CreatureEncumbrance::HEALTH, CreatureEncumbrance::MIND, CreatureAttribute::QUICKNESS, CreatureAttribute::STAMINA, CreatureAttribute::STRENGTH, and CreatureAttribute::WILLPOWER.
Referenced by server::zone::managers::player::PlayerManager::removeEncumbrancies().
void PlayerManagerImplementation::removePlayer (String & playerName)
Definition at line 1409 of file PlayerManager.cpp.
References nameMap.
Referenced by server::zone::managers::player::PlayerManager::removePlayer().
void PlayerManagerImplementation::rescheduleCorpseDestruction (CreatureObject * player, CreatureObject * ai)
Definition at line 3296 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getPendingTask(), and shouldRescheduleCorpseDestruction().
Referenced by lootAll(), and server::zone::managers::player::PlayerManager::rescheduleCorpseDestruction().
void PlayerManagerImplementation::resendLoginMessageToAll ()
Definition at line 1195 of file PlayerManagerImplementation.cpp.
References server::chat::ChatManager::broadcastMessage(), ChatSystemMessage::DISPLAY_CHATONLY, and server.
Referenced by server::zone::managers::player::PlayerManager::resendLoginMessageToAll().
void PlayerManagerImplementation::rlock (bool doLock = true) protected
Definition at line 1290 of file PlayerManager.cpp.
References _this.
Referenced by existsName(), getObjectID(), and getPlayer().
void PlayerManagerImplementation::runlock (bool doLock = true) protected
Definition at line 1306 of file PlayerManager.cpp.
References _this.
Referenced by existsName(), getObjectID(), and getPlayer().
void PlayerManagerImplementation::sendActivateCloneRequest (CreatureObject * player, int typeofdeath = 0)
Definition at line 669 of file PlayerManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), SuiWindowType::CLONE_REQUEST, SuiWindowType::CLONE_REQUEST_DECAY, server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::player::PlayerObject::getCloningFacility(), server::zone::Zone::getNearestPlanetaryObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::Zone::getPlanetaryObjectList(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::player::PlayerObject::removeSuiBoxType(), server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by killPlayer(), and server::zone::managers::player::PlayerManager::sendActivateCloneRequest().
void PlayerManagerImplementation::sendBattleFatigueMessage (CreatureObject * player, CreatureObject * target)
Definition at line 1637 of file PlayerManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getShockWounds(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::player::PlayerManager::sendBattleFatigueMessage().
void PlayerManagerImplementation::sendLoginMessage (CreatureObject * player)
Definition at line 1188 of file PlayerManagerImplementation.cpp.
References ChatSystemMessage::DISPLAY_CHATONLY, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::zone::managers::player::PlayerManager::sendLoginMessage().
void PlayerManagerImplementation::sendPlayerToCloner (CreatureObject * player, unsigned long long clonerID, int typeofdeath = 0)
Definition at line 770 of file PlayerManagerImplementation.cpp.
References CreatureAttribute::ACTION, server::zone::objects::creature::CreatureObject::addShockWounds(), server::zone::objects::creature::CreatureObject::addWounds(), awardExperience(), server::zone::objects::building::BuildingObject::getCell(), server::zone::objects::player::PlayerObject::getCloningFacility(), server::zone::objects::player::PlayerObject::getFactionStatus(), server::zone::templates::SharedObjectTemplate::getFullTemplateString(), getInsurableItems(), server::zone::objects::player::PlayerObject::getJediState(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), CloningBuildingObjectTemplate::getRandomSpawnPoint(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), CreatureAttribute::HEALTH, OptionBitmask::INSURED, server::zone::objects::scene::SceneObject::isTangibleObject(), CreatureAttribute::MIND, FactionStatus::ONLEAVE, ObserverEventType::PLAYERCLONED, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::zone::objects::player::PlayerObject::setCloningFacility(), server::zone::objects::player::PlayerObject::setFactionStatus(), and server::zone::objects::scene::SceneObject::switchZone().
Referenced by server::zone::managers::player::PlayerManager::sendPlayerToCloner().
void PlayerManagerImplementation::sendStartingLocationsTo (CreatureObject * player)
Definition at line 2471 of file PlayerManagerImplementation.cpp.
References StartingLocationList::insertToMessage(), server::zone::objects::creature::CreatureObject::sendMessage(), and startingLocationList.
Referenced by server::zone::managers::player::PlayerManager::sendStartingLocationsTo().
void PlayerManagerImplementation::setExperienceMultiplier (float globalMultiplier)
Definition at line 1152 of file PlayerManagerImplementation.cpp.
References globalExpMultiplier.
Referenced by server::zone::managers::player::PlayerManager::setExperienceMultiplier().
bool PlayerManagerImplementation::shouldDeleteCharacter (unsigned long long characterID, int galaxyID)
Definition at line 3427 of file PlayerManagerImplementation.cpp.
References ServerDatabase::instance().
Referenced by cleanupCharacters(), getCleanupCharacterCount(), and server::zone::managers::player::PlayerManager::shouldDeleteCharacter().
bool PlayerManagerImplementation::shouldRescheduleCorpseDestruction (CreatureObject * player, CreatureObject * ai)
Definition at line 3245 of file PlayerManagerImplementation.cpp.
References canGroupMemberHarvestCorpse(), server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::creature::AiAgent::hasLoot(), server::zone::objects::creature::Creature::hasSkillToHarvestMe(), server::zone::objects::creature::CreatureObject::isCreature(), and server::zone::objects::creature::CreatureObject::isNonPlayerCreatureObject().
Referenced by rescheduleCorpseDestruction(), and server::zone::managers::player::PlayerManager::shouldRescheduleCorpseDestruction().
void PlayerManagerImplementation::startListen (CreatureObject * creature, unsigned long long entid)
Definition at line 1946 of file PlayerManagerImplementation.cpp.
References server::zone::objects::player::sessions::EntertainingSession::addListener(), SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getCustomObjectName(), server::zone::objects::creature::CreatureObject::getListenID(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::info(), server::zone::objects::creature::CreatureObject::isDancing(), server::zone::objects::creature::CreatureObject::isListening(), server::zone::objects::creature::CreatureObject::isPlayingMusic(), server::zone::objects::player::sessions::EntertainingSession::sendEntertainmentUpdate(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::zone::objects::creature::CreatureObject::setListenToID(), and stopListen().
Referenced by server::zone::managers::player::PlayerManager::startListen().
void PlayerManagerImplementation::startWatch (CreatureObject * creature, unsigned long long entid)
Definition at line 1873 of file PlayerManagerImplementation.cpp.
References server::zone::objects::player::sessions::EntertainingSession::addWatcher(), SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getCustomObjectName(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getWatchToID(), server::zone::objects::scene::SceneObject::info(), server::zone::objects::creature::CreatureObject::isDancing(), server::zone::objects::creature::CreatureObject::isPlayingMusic(), server::zone::objects::creature::CreatureObject::isWatching(), server::zone::objects::player::sessions::EntertainingSession::sendEntertainmentUpdate(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::zone::objects::creature::CreatureObject::setWatchToID(), and stopWatch().
Referenced by server::zone::managers::player::PlayerManager::startWatch().
void PlayerManagerImplementation::stopListen (CreatureObject * creature, unsigned long long entid, bool doSendPackets = true, bool forced = false, bool doLock = true, bool outOfRange = false)
Definition at line 1699 of file PlayerManagerImplementation.cpp.
References server::zone::objects::player::sessions::EntertainingSession::activateEntertainerBuff(), SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getListenID(), server::zone::objects::creature::CreatureObject::getMoodID(), server::zone::objects::creature::CreatureObject::getMoodString(), server::zone::objects::scene::SceneObject::info(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), PerformanceType::MUSIC, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::zone::objects::creature::CreatureObject::setMood(), and server::chat::StringIdChatParameter::setTU().
Referenced by startListen(), and server::zone::managers::player::PlayerManager::stopListen().
void PlayerManagerImplementation::stopWatch (CreatureObject * creature, unsigned long long entid, bool doSendPackets = true, bool forced = false, bool doLock = true, bool outOfRange = false)
Definition at line 1784 of file PlayerManagerImplementation.cpp.
References server::zone::objects::player::sessions::EntertainingSession::activateEntertainerBuff(), PerformanceType::DANCE, SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getMoodID(), server::zone::objects::creature::CreatureObject::getMoodString(), server::zone::objects::creature::CreatureObject::getWatchToID(), server::zone::objects::scene::SceneObject::info(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::zone::objects::creature::CreatureObject::setMood(), server::chat::StringIdChatParameter::setTU(), and server::zone::objects::creature::CreatureObject::setWatchToID().
Referenced by startWatch(), and server::zone::managers::player::PlayerManager::stopWatch().
String PlayerManagerImplementation::unbanAccount (PlayerObject * admin, Account * account, const String & reason)
Definition at line 2727 of file PlayerManagerImplementation.cpp.
References server::login::account::Account::getAccountID(), ServerDatabase::instance(), and server::zone::objects::player::PlayerObject::isPrivileged().
Referenced by server::zone::managers::player::PlayerManager::unbanAccount().
String PlayerManagerImplementation::unbanCharacter (PlayerObject * admin, Account * account, const String & name, unsigned int galaxyID, const String & reason)
Definition at line 2861 of file PlayerManagerImplementation.cpp.
References server::login::account::Account::getAccountID(), ServerDatabase::instance(), and server::zone::objects::player::PlayerObject::isPrivileged().
Referenced by server::zone::managers::player::PlayerManager::unbanCharacter().
String PlayerManagerImplementation::unbanFromGalaxy (PlayerObject * admin, Account * account, unsigned const int galaxy, const String & reason)
Definition at line 2796 of file PlayerManagerImplementation.cpp.
References server::login::account::Account::getAccountID(), ServerDatabase::instance(), and server::zone::objects::player::PlayerObject::isPrivileged().
Referenced by server::zone::managers::player::PlayerManager::unbanFromGalaxy().
void PlayerManagerImplementation::unlock (bool doLock = true) protected
Definition at line 1302 of file PlayerManager.cpp.
References _this.
void PlayerManagerImplementation::updatePermissionLevel (CreatureObject * player, int adminLevel = 1)
Definition at line 2112 of file PlayerManagerImplementation.cpp.
References server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::creature::CreatureObject::getPlayerObject(), permissionLevelList, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::zone::managers::skill::SkillManager::surrenderSkill(), and updatePermissionName().
Referenced by server::zone::managers::player::PlayerManager::updatePermissionLevel().
void PlayerManagerImplementation::updatePermissionName (CreatureObject * player, int adminLevel)
Definition at line 2160 of file PlayerManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), DeltaMessage::close(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::isOnline(), permissionLevelList, and TangibleObjectDeltaMessage3::updateName().
Referenced by updatePermissionLevel(), and server::zone::managers::player::PlayerManager::updatePermissionName().
void PlayerManagerImplementation::updateSwimmingState (CreatureObject * player, float newZ, IntersectionResults * intersections = NULL, CloseObjectsVector * closeObjects = NULL)
Definition at line 2178 of file PlayerManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::clearState(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::creature::CreatureObject::getSwimHeight(), CollisionManager::getWorldFloorCollisions(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::info(), server::zone::objects::creature::CreatureObject::notifySelfPositionUpdate(), server::zone::objects::creature::CreatureObject::setState(), and CreatureState::SWIMMING.
Referenced by server::zone::managers::player::PlayerManager::updateSwimmingState().
void PlayerManagerImplementation::wlock (bool doLock = true) protected
Definition at line 1294 of file PlayerManager.cpp.
References _this.
void PlayerManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 1298 of file PlayerManager.cpp.
References _this.
void PlayerManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 1358 of file PlayerManager.cpp.
References writeObjectMembers().
int PlayerManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 1365 of file PlayerManager.cpp.
References globalExpMultiplier, highestBadgeIndex, and server.
Referenced by writeObject().
Friends And Related Function Documentation
friend class PlayerManager friend
Definition at line 853 of file PlayerManager.h.
Member Data Documentation
WeakReference<PlayerManager*> server::zone::managers::player::PlayerManagerImplementation::_this
Definition at line 821 of file PlayerManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
VectorMap<int, String> server::zone::managers::player::PlayerManagerImplementation::badgeMap private
Definition at line 543 of file PlayerManager.h.
Referenced by getBadgeKey(), and loadBadgeMap().
float server::zone::managers::player::PlayerManagerImplementation::globalExpMultiplier private
Definition at line 553 of file PlayerManager.h.
Referenced by awardExperience(), PlayerManagerImplementation(), readObjectMember(), setExperienceMultiplier(), and writeObjectMembers().
int server::zone::managers::player::PlayerManagerImplementation::highestBadgeIndex private
Definition at line 545 of file PlayerManager.h.
Referenced by getHighestBadgeIndex(), loadBadgeMap(), readObjectMember(), and writeObjectMembers().
int PlayerManagerImplementation::MAX_CHAR_ONLINE_COUNT = 2 static
Definition at line 560 of file PlayerManager.h.
Referenced by increaseOnlineCharCountIfPossible().
const int server::zone::managers::player::PlayerManagerImplementation::medicalBuff = 1900 static protected
Definition at line 536 of file PlayerManager.h.
Referenced by enhanceCharacter().
const int server::zone::managers::player::PlayerManagerImplementation::medicalDuration = 7200 static protected
Definition at line 540 of file PlayerManager.h.
Referenced by enhanceCharacter().
Reference<CharacterNameMap* > server::zone::managers::player::PlayerManagerImplementation::nameMap private
Definition at line 551 of file PlayerManager.h.
Referenced by addPlayer(), checkPlayerName(), existsName(), finalize(), getObjectID(), getPlayer(), loadNameMap(), PlayerManagerImplementation(), and removePlayer().
ReadWriteLock server::zone::managers::player::PlayerManagerImplementation::onlineMapMutex private
Definition at line 555 of file PlayerManager.h.
Referenced by decreaseOnlineCharCount(), and increaseOnlineCharCountIfPossible().
OnlineZoneClientMap server::zone::managers::player::PlayerManagerImplementation::onlineZoneClientMap private
Definition at line 557 of file PlayerManager.h.
Referenced by decreaseOnlineCharCount(), getOnlineZoneClientMap(), and increaseOnlineCharCountIfPossible().
const int server::zone::managers::player::PlayerManagerImplementation::performanceBuff = 1000 static protected
Definition at line 534 of file PlayerManager.h.
Referenced by enhanceCharacter().
const int server::zone::managers::player::PlayerManagerImplementation::performanceDuration = 7200 static protected
Definition at line 538 of file PlayerManager.h.
Referenced by enhanceCharacter().
Reference<PermissionLevelList* > server::zone::managers::player::PlayerManagerImplementation::permissionLevelList private
Definition at line 565 of file PlayerManager.h.
Referenced by loadPermissionLevels(), updatePermissionLevel(), and updatePermissionName().
Reference<PlayerMap* > server::zone::managers::player::PlayerManagerImplementation::playerMap private
Definition at line 549 of file PlayerManager.h.
Referenced by finalize(), and PlayerManagerImplementation().
ManagedReference<ZoneProcessServer* > server::zone::managers::player::PlayerManagerImplementation::processor private
Definition at line 531 of file PlayerManager.h.
Referenced by checkPlayerName(), and PlayerManagerImplementation().
ManagedReference<ZoneServer* > server::zone::managers::player::PlayerManagerImplementation::server private
Definition at line 547 of file PlayerManager.h.
Referenced by banAccount(), banFromGalaxy(), checkSpeedHackSecondTest(), cleanupCharacters(), createHairObject(), createSkippedTutorialBuilding(), createTutorialBuilding(), getCleanupCharacterCount(), getInRangeStructureWithAdminRights(), getNearbyCraftingStation(), getPlayer(), handleAbortTradeMessage(), handleAcceptTransactionMessage(), handleAddItemToTradeWindow(), handleGiveMoneyMessage(), handleUnAcceptTransactionMessage(), handleVerifyTradeMessage(), kickUser(), loadNameMap(), offerTeaching(), PlayerManagerImplementation(), promptTeachableSkills(), readObjectMember(), resendLoginMessageToAll(), sendActivateCloneRequest(), sendLoginMessage(), sendPlayerToCloner(), startListen(), startWatch(), stopListen(), stopWatch(), updatePermissionLevel(), and writeObjectMembers().
Reference<StartingItemList* > server::zone::managers::player::PlayerManagerImplementation::startingItemList private
Definition at line 563 of file PlayerManager.h.
Referenced by loadStartingItems().
StartingLocationList server::zone::managers::player::PlayerManagerImplementation::startingLocationList private
Definition at line 567 of file PlayerManager.h.
Referenced by getStartingLocation(), loadStartingLocations(), and sendStartingLocationsTo().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/PlayerManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/PlayerManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/PlayerManagerImplementation.cpp