Core3: LogoutTask Class Reference
LogoutTask Class Reference
#include <LogoutTask.h>
Public Member Functions
LogoutTask (CreatureObject *cr)
void cancelLogout ()
void run ()
Private Attributes
ManagedReference
< CreatureObject * > creature
int timeLeft
Detailed Description
LogoutTask.h
Created: Sat Oct 8 09:18:00 EDT 2011 Author: lordkator
Description: Task created by LogoutServerCommand to implement the /logout process
Definition at line 59 of file LogoutTask.h.
Constructor & Destructor Documentation
LogoutTask::LogoutTask (CreatureObject * cr) inline
Definition at line 64 of file LogoutTask.h.
References creature, and timeLeft.
Member Function Documentation
void LogoutTask::cancelLogout () inline
Definition at line 77 of file LogoutTask.h.
References creature.
Referenced by server::zone::managers::player::PlayerManagerImplementation::notifyObserverEvent(), run(), and server::zone::objects::creature::CreatureObjectImplementation::setCombatState().
void LogoutTask::run () inline
Definition at line 87 of file LogoutTask.h.
References cancelLogout(), creature, and timeLeft.
Member Data Documentation
ManagedReference<CreatureObject*> LogoutTask::creature private
Definition at line 60 of file LogoutTask.h.
Referenced by cancelLogout(), LogoutTask(), and run().
int LogoutTask::timeLeft private
Definition at line 61 of file LogoutTask.h.
Referenced by LogoutTask(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/events/LogoutTask.h