Core3: server::zone::objects::mission::bountyhunter::events::CallArakydTask Class Reference
server::zone::objects::mission::bountyhunter::events::CallArakydTask Class Reference
#include <CallArakydTask.h>
Public Member Functions
CallArakydTask (CreatureObject *player, BountyMissionObjective *objective)
~CallArakydTask ()
void run ()
Vector3 getLandingCoordinates (CreatureObject *player)
bool noInterferingObjects (CreatureObject *player, Vector3 position)
Private Attributes
ManagedWeakReference
< CreatureObject * > player
ManagedWeakReference
< BountyMissionObjective * > objective
int time
Vector3 droidPosition
Detailed Description
Definition at line 61 of file CallArakydTask.h.
Constructor & Destructor Documentation
server::zone::objects::mission::bountyhunter::events::CallArakydTask::CallArakydTask (CreatureObject * player, BountyMissionObjective * objective) inline
Definition at line 68 of file CallArakydTask.h.
References objective, player, and time.
server::zone::objects::mission::bountyhunter::events::CallArakydTask::~CallArakydTask () inline
Definition at line 75 of file CallArakydTask.h.
Member Function Documentation
Vector3 server::zone::objects::mission::bountyhunter::events::CallArakydTask::getLandingCoordinates (CreatureObject * player) inline
Definition at line 119 of file CallArakydTask.h.
References server::zone::Zone::getPlanetManager(), server::zone::objects::scene::SceneObject::getWorldCoordinate(), server::zone::objects::scene::SceneObject::getZone(), and noInterferingObjects().
Referenced by run().
bool server::zone::objects::mission::bountyhunter::events::CallArakydTask::noInterferingObjects (CreatureObject * player, Vector3 position) inline
Definition at line 147 of file CallArakydTask.h.
References server::zone::templates::SharedObjectTemplate::getNoBuildRadius(), server::zone::objects::scene::SceneObject::getObjectTemplate(), and server::zone::objects::scene::SceneObject::getWorldPosition().
Referenced by getLandingCoordinates().
void server::zone::objects::mission::bountyhunter::events::CallArakydTask::run () inline
Definition at line 79 of file CallArakydTask.h.
References droidPosition, getLandingCoordinates(), objective, player, and time.
Member Data Documentation
Vector3 server::zone::objects::mission::bountyhunter::events::CallArakydTask::droidPosition private
Definition at line 65 of file CallArakydTask.h.
Referenced by run().
ManagedWeakReference<BountyMissionObjective*> server::zone::objects::mission::bountyhunter::events::CallArakydTask::objective private
Definition at line 63 of file CallArakydTask.h.
Referenced by CallArakydTask(), and run().
ManagedWeakReference<CreatureObject*> server::zone::objects::mission::bountyhunter::events::CallArakydTask::player private
Definition at line 62 of file CallArakydTask.h.
Referenced by CallArakydTask(), and run().
int server::zone::objects::mission::bountyhunter::events::CallArakydTask::time private
Definition at line 64 of file CallArakydTask.h.
Referenced by CallArakydTask(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/bountyhunter/events/CallArakydTask.h