Core3: server::zone::objects::structure::events::StructureMaintenanceTask Class Reference
server::zone::objects::structure::events::StructureMaintenanceTask Class Reference
#include <StructureMaintenanceTask.h>
Public Member Functions
StructureMaintenanceTask (StructureObject *structure)
void run ()
Protected Attributes
ManagedWeakReference
< StructureObject * > structureObject
Static Protected Attributes
static const int oneDayTime = 24 * 60 * 60 * 1000
Private Member Functions
void sendMailMaintenanceWithdrawnFromBank (CreatureObject *owner, StructureObject *structure)
void sendMailDecay (CreatureObject *owner, StructureObject *structure)
void sendMailCondemned (CreatureObject *owner, StructureObject *structure)
bool shouldBuildingBeDestroyed (StructureObject *structure)
Detailed Description
Definition at line 35 of file StructureMaintenanceTask.h.
Constructor & Destructor Documentation
server::zone::objects::structure::events::StructureMaintenanceTask::StructureMaintenanceTask (StructureObject * structure) inline
Definition at line 42 of file StructureMaintenanceTask.h.
Member Function Documentation
void StructureMaintenanceTask::run ()
Definition at line 18 of file StructureMaintenanceTask.cpp.
References server::zone::ZoneServer::isServerLoading(), oneDayTime, sendMailCondemned(), sendMailDecay(), sendMailMaintenanceWithdrawnFromBank(), shouldBuildingBeDestroyed(), structureObject, and server::zone::objects::building::BuildingObject::updateSignName().
void StructureMaintenanceTask::sendMailCondemned (CreatureObject * owner, StructureObject * structure) private
Definition at line 148 of file StructureMaintenanceTask.cpp.
References server::zone::ZoneServer::getChatManager(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getObjectName(), server::zone::objects::structure::StructureObject::getSurplusMaintenance(), server::zone::objects::scene::SceneObject::getZoneServer(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), and server::chat::StringIdChatParameter::setTT().
Referenced by run().
void StructureMaintenanceTask::sendMailDecay (CreatureObject * owner, StructureObject * structure) private
Definition at line 126 of file StructureMaintenanceTask.cpp.
References server::zone::ZoneServer::getChatManager(), server::zone::objects::structure::StructureObject::getDecayPercentage(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getObjectName(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::isBuildingObject(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), and server::chat::StringIdChatParameter::setTT().
Referenced by run().
void StructureMaintenanceTask::sendMailMaintenanceWithdrawnFromBank (CreatureObject * owner, StructureObject * structure) private
Definition at line 111 of file StructureMaintenanceTask.cpp.
References server::zone::ZoneServer::getChatManager(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getObjectName(), server::zone::objects::scene::SceneObject::getZoneServer(), server::chat::StringIdChatParameter::setTO(), and server::chat::StringIdChatParameter::setTT().
Referenced by run().
bool StructureMaintenanceTask::shouldBuildingBeDestroyed (StructureObject * structure) private
Definition at line 164 of file StructureMaintenanceTask.cpp.
References server::zone::objects::structure::StructureObject::getMaintenanceRate(), and server::zone::objects::structure::StructureObject::getSurplusMaintenance().
Referenced by run().
Member Data Documentation
const int server::zone::objects::structure::events::StructureMaintenanceTask::oneDayTime = 24 * 60 * 60 * 1000 static protected
Definition at line 39 of file StructureMaintenanceTask.h.
Referenced by run().
ManagedWeakReference<StructureObject*> server::zone::objects::structure::events::StructureMaintenanceTask::structureObject protected
Definition at line 37 of file StructureMaintenanceTask.h.
Referenced by run().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/structure/events/StructureMaintenanceTask.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/structure/events/StructureMaintenanceTask.cpp