Core3: server::zone::objects::mission::BountyMissionObjectiveAdapter Class Reference
server::zone::objects::mission::BountyMissionObjectiveAdapter Class Reference
#include <BountyMissionObjective.h>
Public Member Functions
BountyMissionObjectiveAdapter (BountyMissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializeTransientMembers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void spawnTarget (const String &zoneName)
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void updateMissionStatus (int informantLevel)
int getObjectiveStatus ()
SceneObject * getArakydDroid ()
void setArakydDroid (SceneObject *droid)
void performDroidAction (int action, SceneObject *sceneObject, CreatureObject *player)
bool playerHasMissionOfCorrectLevel (int action)
void updateWaypoint ()
void cancelAllTasks ()
String getTargetZoneName ()
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveAdapter
MissionObjectiveAdapter (MissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Detailed Description
Definition at line 346 of file BountyMissionObjective.h.
Constructor & Destructor Documentation
BountyMissionObjectiveAdapter::BountyMissionObjectiveAdapter (BountyMissionObjective * impl)
Definition at line 558 of file BountyMissionObjective.cpp.
Member Function Documentation
void BountyMissionObjectiveAdapter::abort ()
Definition at line 672 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::activate ()
Definition at line 664 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::cancelAllTasks ()
Definition at line 716 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::complete ()
Definition at line 676 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::deactivate ()
Definition at line 668 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::finalize ()
Definition at line 656 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
SceneObject * BountyMissionObjectiveAdapter::getArakydDroid ()
Definition at line 696 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
int BountyMissionObjectiveAdapter::getObjectiveStatus ()
Definition at line 692 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
String BountyMissionObjectiveAdapter::getTargetZoneName ()
Definition at line 720 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::initializeTransientMembers ()
Definition at line 660 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 561 of file BountyMissionObjective.cpp.
References abort(), activate(), cancelAllTasks(), complete(), deactivate(), finalize(), getArakydDroid(), getObjectiveStatus(), getTargetZoneName(), initializeTransientMembers(), notifyObserverEvent(), performDroidAction(), playerHasMissionOfCorrectLevel(), RPC_ABORT__, RPC_ACTIVATE__, RPC_CANCELALLTASKS__, RPC_COMPLETE__, RPC_DEACTIVATE__, RPC_FINALIZE__, RPC_GETARAKYDDROID__, RPC_GETOBJECTIVESTATUS__, RPC_GETTARGETZONENAME__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_, RPC_PERFORMDROIDACTION__INT_SCENEOBJECT_CREATUREOBJECT_, RPC_PLAYERHASMISSIONOFCORRECTLEVEL__INT_, RPC_SETARAKYDDROID__SCENEOBJECT_, RPC_SPAWNTARGET__STRING_, RPC_UPDATEMISSIONSTATUS__INT_, RPC_UPDATEWAYPOINT__, setArakydDroid(), spawnTarget(), updateMissionStatus(), and updateWaypoint().
int BountyMissionObjectiveAdapter::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 684 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::performDroidAction (int action, SceneObject * sceneObject, CreatureObject * player)
Definition at line 704 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
bool BountyMissionObjectiveAdapter::playerHasMissionOfCorrectLevel (int action)
Definition at line 708 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::setArakydDroid (SceneObject * droid)
Definition at line 700 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::spawnTarget (const String & zoneName)
Definition at line 680 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::updateMissionStatus (int informantLevel)
Definition at line 688 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
void BountyMissionObjectiveAdapter::updateWaypoint ()
Definition at line 712 of file BountyMissionObjective.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/BountyMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/BountyMissionObjective.cpp