Core3: server::zone::objects::player::sessions::TradeSession Class Reference
server::zone::objects::player::sessions::TradeSession Class Reference
#include <TradeSession.h>
Public Member Functions
TradeSession ()
bool getAcceptedTrade ()
void addTradeItem (SceneObject *object)
SortedVector< ManagedReference
< SceneObject * > > * getItemsToTrade ()
SceneObject * getTradeItem (int index)
int getTradeSize ()
int getMoneyToTrade ()
unsigned long long getTradeTargetPlayer ()
bool isTryingToTrade ()
bool hasVerifiedTrade ()
void setAcceptedTrade (bool val)
void setMoneyToTrade (int val)
void setTradeTargetPlayer (unsigned long long val)
void setVerifiedTrade (bool val)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
TradeSession (DummyConstructorParameter *param)
virtual ~TradeSession ()
Friends
class TradeSessionHelper
Detailed Description
Definition at line 54 of file TradeSession.h.
Constructor & Destructor Documentation
TradeSession::TradeSession ()
Definition at line 17 of file TradeSession.cpp.
References server::zone::objects::player::sessions::TradeSessionImplementation::_setStub().
TradeSession::TradeSession (DummyConstructorParameter * param) protected
Definition at line 24 of file TradeSession.cpp.
TradeSession::~TradeSession () protected virtual
Definition at line 28 of file TradeSession.cpp.
Member Function Documentation
DistributedObjectServant * TradeSession::_getImplementation ()
Definition at line 204 of file TradeSession.cpp.
Referenced by addTradeItem(), getAcceptedTrade(), getItemsToTrade(), getMoneyToTrade(), getTradeItem(), getTradeSize(), getTradeTargetPlayer(), hasVerifiedTrade(), isTryingToTrade(), setAcceptedTrade(), setMoneyToTrade(), setTradeTargetPlayer(), and setVerifiedTrade().
DistributedObjectServant * TradeSession::_getImplementationForRead ()
Definition at line 210 of file TradeSession.cpp.
void TradeSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 214 of file TradeSession.cpp.
void TradeSession::addTradeItem (SceneObject * object)
Definition at line 46 of file TradeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TradeSessionImplementation::addTradeItem(), and RPC_ADDTRADEITEM__SCENEOBJECT_.
bool TradeSession::getAcceptedTrade ()
Definition at line 33 of file TradeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TradeSessionImplementation::getAcceptedTrade(), and RPC_GETACCEPTEDTRADE__.
SortedVector< ManagedReference< SceneObject * > > * TradeSession::getItemsToTrade ()
Definition at line 60 of file TradeSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::TradeSessionImplementation::getItemsToTrade().
int TradeSession::getMoneyToTrade ()
Definition at line 96 of file TradeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TradeSessionImplementation::getMoneyToTrade(), and RPC_GETMONEYTOTRADE__.
SceneObject * TradeSession::getTradeItem (int index)
Definition at line 69 of file TradeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TradeSessionImplementation::getTradeItem(), and RPC_GETTRADEITEM__INT_.
int TradeSession::getTradeSize ()
Definition at line 83 of file TradeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TradeSessionImplementation::getTradeSize(), and RPC_GETTRADESIZE__.
unsigned long long TradeSession::getTradeTargetPlayer ()
Definition at line 109 of file TradeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TradeSessionImplementation::getTradeTargetPlayer(), and RPC_GETTRADETARGETPLAYER__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::handleAddItemToTradeWindow().
bool TradeSession::hasVerifiedTrade ()
Definition at line 135 of file TradeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TradeSessionImplementation::hasVerifiedTrade(), and RPC_HASVERIFIEDTRADE__.
bool TradeSession::isTryingToTrade ()
Definition at line 122 of file TradeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::TradeSessionImplementation::isTryingToTrade(), and RPC_ISTRYINGTOTRADE__.
void TradeSession::setAcceptedTrade (bool val)
Definition at line 148 of file TradeSession.cpp.
References _getImplementation(), RPC_SETACCEPTEDTRADE__BOOL_, and server::zone::objects::player::sessions::TradeSessionImplementation::setAcceptedTrade().
Referenced by server::zone::managers::player::PlayerManagerImplementation::handleAcceptTransactionMessage(), and server::zone::managers::player::PlayerManagerImplementation::handleUnAcceptTransactionMessage().
void TradeSession::setMoneyToTrade (int val)
Definition at line 162 of file TradeSession.cpp.
References _getImplementation(), RPC_SETMONEYTOTRADE__INT_, and server::zone::objects::player::sessions::TradeSessionImplementation::setMoneyToTrade().
Referenced by server::zone::managers::player::PlayerManagerImplementation::handleGiveMoneyMessage().
void TradeSession::setTradeTargetPlayer (unsigned long long val)
Definition at line 176 of file TradeSession.cpp.
References _getImplementation(), RPC_SETTRADETARGETPLAYER__LONG_, and server::zone::objects::player::sessions::TradeSessionImplementation::setTradeTargetPlayer().
void TradeSession::setVerifiedTrade (bool val)
Definition at line 190 of file TradeSession.cpp.
References _getImplementation(), RPC_SETVERIFIEDTRADE__BOOL_, and server::zone::objects::player::sessions::TradeSessionImplementation::setVerifiedTrade().
Referenced by server::zone::managers::player::PlayerManagerImplementation::handleVerifyTradeMessage().
Friends And Related Function Documentation
friend class TradeSessionHelper friend
Definition at line 94 of file TradeSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TradeSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TradeSession.cpp