Core3: server::zone::objects::creature::buffs::StateBuffImplementation Class Reference
server::zone::objects::creature::buffs::StateBuffImplementation Class Reference
#include <StateBuff.h>
Public Member Functions
StateBuffImplementation (CreatureObject *creo, unsigned long long buffState, int duration)
StateBuffImplementation (DummyConstructorParameter *param)
void activate (bool applyModifiers)
void deactivate (bool removeModifiers)
operator const StateBuff * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
BuffImplementation (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype)
BuffImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
virtual void sendTo (CreatureObject *player)
virtual void sendDestroyTo (CreatureObject *player)
virtual void activate ()
virtual void deactivate ()
VectorMap< String, int > * getSkillModifiers ()
virtual void applyAttributeModifiers ()
virtual void applySkillModifiers ()
virtual void applyStates ()
virtual void removeAttributeModifiers ()
virtual void removeSkillModifiers ()
virtual void removeStates ()
virtual void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
virtual void parseAttributeModifierString (const String &modifierstring)
virtual void parseSkillModifierString (const String &modifierstring)
virtual String getAttributeModifierString ()
virtual String getSkillModifierString ()
virtual float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
VectorMap< byte, int > * getAttributeModifiers ()
virtual int getAttributeModifierValue (byte attribute)
virtual int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartMessage (StringIdChatParameter &start)
void setEndMessage (StringIdChatParameter &end)
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
operator const Buff * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< StateBuff * > _this
Public Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
WeakReference< Buff * > _this
Protected Member Functions
virtual ~StateBuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
virtual ~BuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
unsigned long long stateApplied
Protected Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
ManagedWeakReference
< CreatureObject * > creature
Reference< BuffDurationEvent * > buffEvent
VectorMap< byte, int > attributeModifiers
VectorMap< String, int > skillModifiers
Vector< unsigned long long > states
String buffName
float buffDuration
unsigned int buffCRC
int buffType
bool fillAttributesOnBuff
StringIdChatParameter startMessage
StringIdChatParameter endMessage
String startFlyFile
String startFlyAux
byte startFlyRed
byte startFlyGreen
byte startFlyBlue
String endFlyFile
String endFlyAux
byte endFlyRed
byte endFlyGreen
byte endFlyBlue
Time nextExecutionTime
Friends
class StateBuff
Detailed Description
Definition at line 81 of file StateBuff.h.
Constructor & Destructor Documentation
StateBuffImplementation::StateBuffImplementation (CreatureObject * creo, unsigned long long buffState, int duration)
Definition at line 203 of file StateBuff.cpp.
References _initializeImplementation(), and stateApplied.
StateBuffImplementation::StateBuffImplementation (DummyConstructorParameter * param)
Definition at line 77 of file StateBuff.cpp.
References _initializeImplementation().
StateBuffImplementation::~StateBuffImplementation () protected virtual
Definition at line 82 of file StateBuff.cpp.
Member Function Documentation
DistributedObjectStub * StateBuffImplementation::_getStub ()
Definition at line 102 of file StateBuff.cpp.
References _this.
void StateBuffImplementation::_initializeImplementation () protected
Definition at line 89 of file StateBuff.cpp.
References _serializationHelperMethod(), and _this.
Referenced by StateBuffImplementation().
void StateBuffImplementation::_serializationHelperMethod () protected
Definition at line 138 of file StateBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void StateBuffImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 97 of file StateBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::buffs::StateBuff::StateBuff().
void StateBuffImplementation::activate (bool applyModifiers) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 209 of file StateBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::activate(), server::zone::objects::creature::buffs::BuffImplementation::creature, and stateApplied.
Referenced by server::zone::objects::creature::buffs::StateBuff::activate().
void StateBuffImplementation::deactivate (bool removeModifiers) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 216 of file StateBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::creature, server::zone::objects::creature::buffs::BuffImplementation::deactivate(), and stateApplied.
Referenced by server::zone::objects::creature::buffs::StateBuff::deactivate().
void StateBuffImplementation::finalize () protected
Definition at line 86 of file StateBuff.cpp.
void StateBuffImplementation::lock (bool doLock = true) protected
Definition at line 110 of file StateBuff.cpp.
References _this.
void StateBuffImplementation::lock (ManagedObject * obj) protected
Definition at line 114 of file StateBuff.cpp.
References _this.
StateBuffImplementation::operator const StateBuff * ()
Definition at line 106 of file StateBuff.cpp.
void StateBuffImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 145 of file StateBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::initializeTransientMembers(), and readObjectMember().
bool StateBuffImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 164 of file StateBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::readObjectMember(), and stateApplied.
Referenced by readObject().
void StateBuffImplementation::rlock (bool doLock = true) protected
Definition at line 118 of file StateBuff.cpp.
References _this.
void StateBuffImplementation::runlock (bool doLock = true) protected
Definition at line 134 of file StateBuff.cpp.
References _this.
void StateBuffImplementation::unlock (bool doLock = true) protected
Definition at line 130 of file StateBuff.cpp.
References _this.
void StateBuffImplementation::wlock (bool doLock = true) protected
Definition at line 122 of file StateBuff.cpp.
References _this.
void StateBuffImplementation::wlock (ManagedObject * obj) protected
Definition at line 126 of file StateBuff.cpp.
References _this.
void StateBuffImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 178 of file StateBuff.cpp.
References writeObjectMembers().
int StateBuffImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 185 of file StateBuff.cpp.
References stateApplied, and server::zone::objects::creature::buffs::BuffImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class StateBuff friend
Definition at line 128 of file StateBuff.h.
Member Data Documentation
WeakReference<StateBuff*> server::zone::objects::creature::buffs::StateBuffImplementation::_this
Definition at line 94 of file StateBuff.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
unsigned long long server::zone::objects::creature::buffs::StateBuffImplementation::stateApplied protected
Definition at line 83 of file StateBuff.h.
Referenced by activate(), deactivate(), readObjectMember(), StateBuffImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/StateBuff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/StateBuff.cpp