Core3: server::zone::objects::player::sui::messagebox::SuiTransferBoxAdapter Class Reference
server::zone::objects::player::sui::messagebox::SuiTransferBoxAdapter Class Reference
#include <SuiTransferBox.h>
Public Member Functions
SuiTransferBoxAdapter (SuiTransferBox *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
BaseMessage * generateMessage ()
void addFrom (const String &from, const String &startingFrom, const String &inputFrom, const String &rFrom)
void addTo (const String &to, const String &startingTo, const String &inputTo, const String &rTo)
bool isTransferBox ()
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxAdapter
SuiBoxAdapter (SuiBox *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type)
BaseMessage * generateMessage ()
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
bool isInputBox ()
bool isListBox ()
bool isMessageBox ()
bool isTransferBox ()
bool isBankTransferBox ()
bool isSlicingBox ()
bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
Detailed Description
Definition at line 180 of file SuiTransferBox.h.
Constructor & Destructor Documentation
SuiTransferBoxAdapter::SuiTransferBoxAdapter (SuiTransferBox * impl)
Definition at line 340 of file SuiTransferBox.cpp.
Member Function Documentation
void SuiTransferBoxAdapter::addFrom (const String & from, const String & startingFrom, const String & inputFrom, const String & rFrom)
Definition at line 378 of file SuiTransferBox.cpp.
Referenced by invokeMethod().
void SuiTransferBoxAdapter::addTo (const String & to, const String & startingTo, const String & inputTo, const String & rTo)
Definition at line 382 of file SuiTransferBox.cpp.
Referenced by invokeMethod().
BaseMessage * SuiTransferBoxAdapter::generateMessage ()
Definition at line 374 of file SuiTransferBox.cpp.
Referenced by invokeMethod().
void SuiTransferBoxAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 343 of file SuiTransferBox.cpp.
References addFrom(), addTo(), generateMessage(), isTransferBox(), RPC_ADDFROM__STRING_STRING_STRING_STRING_, RPC_ADDTO__STRING_STRING_STRING_STRING_, RPC_GENERATEMESSAGE__, and RPC_ISTRANSFERBOX__.
bool SuiTransferBoxAdapter::isTransferBox ()
Definition at line 386 of file SuiTransferBox.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/transferbox/SuiTransferBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/transferbox/SuiTransferBox.cpp