Core3: IntegerParam Class Reference
IntegerParam Class Reference
#include <IntegerParam.h>
Public Member Functions
IntegerParam ()
IntegerParam (const IntegerParam &p)
IntegerParam & operator= (int val)
String toString ()
virtual bool parse (engine::util::Chunk *source)
Public Member Functions inherited from TemplateBase< int >
TemplateBase (const int &defaultValue)
TemplateBase (const TemplateBase &t)
virtual ~TemplateBase ()
void create (const int &val)
virtual int compareTo (const int &val) const
virtual bool operator== (const int &val) const
virtual bool operator< (const int &val) const
virtual bool operator> (const int &val) const
virtual bool operator!= (const int &val) const
operator int () const
virtual int getValue () const
virtual int get () const
virtual void setValue (const int &val)
Public Member Functions inherited from Param
Param ()
virtual ~Param ()
uint32 getType ()
void setType (uint32 tp)
bool isBool ()
bool isFloat ()
bool isInteger ()
bool isString ()
bool isStringId ()
Additional Inherited Members
Static Public Attributes inherited from Param
static const uint32 BOOL = 0x01
static const uint32 FLOAT = 0x02
static const uint32 INTEGER = 0x04
static const uint32 STRING = 0x08
static const uint32 STRINGID = 0x10
static const uint32 VECTOR = 0x12
static const uint32 DYNAMICVARIABLE = 0x014
static const uint32 TRIGGERVOLUME = 0x16
static const uint32 PALETTECOLORCUSTOMIZATION = 0x18
static const uint32 RANGEDINTCUSTOMIZATIONVARIABLE = 0x20
static const uint32 CUSTOMIZATIONVARIABLEMAP = 0x22
Protected Attributes inherited from TemplateBase< int >
int value
Detailed Description
Definition at line 13 of file IntegerParam.h.
Constructor & Destructor Documentation
IntegerParam::IntegerParam () inline
Definition at line 16 of file IntegerParam.h.
References Param::INTEGER, and Param::setType().
IntegerParam::IntegerParam (const IntegerParam & p) inline
Definition at line 20 of file IntegerParam.h.
References Param::INTEGER, and Param::setType().
Member Function Documentation
IntegerParam& IntegerParam::operator= (int val) inline
Definition at line 24 of file IntegerParam.h.
References TemplateBase< int >::create().
virtual bool IntegerParam::parse (engine::util::Chunk * source) inline virtual
Implements Param.
Definition at line 34 of file IntegerParam.h.
References TemplateBase< int >::create().
Referenced by RangedIntCustomizationVariable::parse(), PaletteColorCustomizationVariable::parse(), SharedCreatureObjectTemplate::parseVariableData(), SharedWeaponObjectTemplate::parseVariableData(), and server::zone::templates::SharedObjectTemplate::parseVariableData().
String IntegerParam::toString () inline virtual
Implements Param.
Definition at line 30 of file IntegerParam.h.
Referenced by RangedIntCustomizationVariable::toString(), and PaletteColorCustomizationVariable::toString().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/params/primitives/IntegerParam.h