Core3: ForceShield1Command Class Reference
ForceShield1Command Class Reference
#include <ForceShield1Command.h>
Public Member Functions
ForceShield1Command (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Detailed Description
Definition at line 51 of file ForceShield1Command.h.
Constructor & Destructor Documentation
ForceShield1Command::ForceShield1Command (const String & name, ZoneProcessServer * server) inline
Definition at line 54 of file ForceShield1Command.h.
Member Function Documentation
int ForceShield1Command::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 59 of file ForceShield1Command.h.
References server::zone::objects::creature::CreatureObject::addBuff(), ObserverEventType::FORCEBUFFHIT, server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::hasBuff(), BuffType::JEDI, BuffCRC::JEDI_FORCE_SHIELD_1, BuffCRC::JEDI_FORCE_SHIELD_2, server::zone::objects::creature::CreatureObject::playEffect(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
void ForceShield1Command::handleBuff (SceneObject * creature, ManagedObject * object, int64 param) inline
Definition at line 117 of file ForceShield1Command.h.
References BuffCRC::JEDI_FORCE_SHIELD_1.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/ForceShield1Command.h