Core3: Melee2hLunge1Command Class Reference
Melee2hLunge1Command Class Reference
#include <Melee2hLunge1Command.h>
Public Member Functions
Melee2hLunge1Command (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Public Member Functions inherited from CombatQueueCommand
CombatQueueCommand (const String &name, ZoneProcessServer *server)
int doCombatAction (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments="", ManagedReference< WeaponObject * > weapon=NULL)
float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
uint32 getDotDuration () const
uint64 getDotType () const
uint8 getDotPool () const
uint32 getDotStrength () const
float getDotPotency () const
float getHealthCostMultiplier () const
float getActionCostMultiplier () const
float getMindCostMultiplier () const
int getRange () const
String getAccuracySkillMod () const
int getBlindChance () const
float getDamageMultiplier () const
int getAccuracyBonus () const
int getDizzyChance () const
int getIntimidateChance () const
int getKnockdownChance () const
int getPostureDownChance () const
int getPostureUpChance () const
float getSpeedMultiplier () const
float getSpeed () const
int getStunChance () const
bool isAreaAction () const
bool isConeAction () const
bool isDotDamageOfHit () const
int getConeAngle () const
int getAreaRange () const
int getDurationStateTime () const
float getForceCostMultiplier () const
float getForceCost () const
int getNextAttackDelayChance () const
void setBlindStateChance (int blindStateChance)
void setDamageMultiplier (float damageMultiplier)
void setAccuracyBonus (int accuracyBonus)
void setHealthCostMultiplier (float f)
void setActionCostMultiplier (float f)
void setMindCostMultiplier (float f)
void setForceCostMultiplier (float f)
void setForceCost (float f)
void setDizzyStateChance (int dizzyStateChance)
void setIntimidateStateChance (int intimidateStateChance)
void setKnockdownStateChance (int knockdownStateChance)
void setPostureDownStateChance (int postureDownStateChance)
void setPostureUpStateChance (int postureUpStateChance)
void setNextAttackDelayChance (int i)
void setDurationStateTime (int i)
void setDotDuration (uint32 i)
void setDotType (uint64 l)
void setDotPool (uint8 c)
void setDotStrength (uint32 i)
void setDotPotency (float f)
void setConeAngle (int i)
void setDotDamageOfHit (bool b)
void setAreaAction (bool b)
void setConeAction (bool b)
void setAreaRange (int i)
void setEffectString (String s)
void setSpeedMultiplier (float speedMultiplier)
void setSpeed (float speedd)
void setStunStateChance (int stunStateChance)
uint32 getAnimationCRC () const
String getEffectString () const
String getCombatSpam () const
int getPoolsToDamage () const
VectorMap< uint64, StateEffect > * getStateEffects ()
VectorMap< uint64, DotEffect > * getDotEffects ()
void setAnimationCRC (uint32 animationCRC)
void setCombatSpam (String combatSpam)
void setPoolsToDamage (int poolsToDamage)
void setStateEffects (VectorMap< uint64, StateEffect > stateEffects)
void addStateEffect (StateEffect stateEffect)
StateEffect getStateEffect (uint64 type)
void setDotEffects (VectorMap< uint64, DotEffect > dotEffects)
float getDamage () const
void setDamage (float dm)
void addDotEffect (DotEffect dotEffect)
DotEffect getDotEffect (uint64 type)
void setRange (int i)
void setAccuracySkillMod (String acc)
bool hasCombatSpam ()
bool isCombatCommand ()
virtual bool isSquadLeaderCommand ()
virtual void applyEffect (CreatureObject *creature, uint8 effectType, uint32 mod)
uint8 getAttackType () const
void setAttackType (uint8 attackType)
uint8 getTrails () const
void setTrails (uint8 trails)
Public Member Functions inherited from server::zone::objects::creature::commands::QueueCommand
QueueCommand (const String &skillname, ZoneProcessServer *serv)
virtual ~QueueCommand ()
bool checkInvalidLocomotions (CreatureObject *creature)
void onStateFail (CreatureObject *creature, uint32 actioncntr)
void onLocomotionFail (CreatureObject *creature, uint32 actioncntr)
virtual String getSyntax () const
virtual void onFail (uint32 actioncntr, CreatureObject *creature, uint32 errorNumber)
virtual void onComplete (uint32 actioncntr, CreatureObject *creature, float commandDuration)
void setInvalidLocomotions (const String &lStr)
void addInvalidLocomotion (int l)
bool checkStateMask (CreatureObject *creature)
void setStateMask (uint64 mask)
void setDefaultTime (float time)
void setTargetType (int num)
void setDisabled (bool state)
void setDisabled (int state)
void setAddToCombatQueue (bool state)
void setAddToCombatQueue (int state)
void setCommandGroup (int val)
void setMaxRange (float r)
void setCharacterAbility (const String &ability)
void setDefaultPriority (const String &priority)
void setDefaultPriority (const int priority)
uint64 getStateMask ()
bool requiresAdmin ()
int getTargetType ()
uint32 getNameCRC ()
float getMaxRange ()
String & getQueueCommandName ()
String & getCharacterAbility ()
float getDefaultTime ()
int getDefaultPriority ()
bool isDisabled ()
bool addToCombatQueue ()
int getSkillModSize ()
int getSkillMod (int index, String &skillMod)
int getCommandGroup ()
void addSkillMod (const String &skillMod, const int value)
bool isWearingArmor (CreatureObject *creo)
virtual void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::creature::commands::QueueCommand
static const int IMMEDIATE = 0
static const int FRONT = 1
static const int NORMAL = 2
static const int SUCCESS = 0
static const int GENERALERROR = 1
static const int INVALIDLOCOMOTION = 2
static const int INVALIDSTATE = 3
static const int INVALIDTARGET = 4
static const int INVALIDWEAPON = 5
static const int TOOFAR = 6
static const int INSUFFICIENTHAM = 7
static const int INVALIDPARAMETERS = 8
static const int NOPRONE = 9
static const int NOKNEELING = 10
static const int INSUFFICIENTPERMISSION = 11
static const int NOJEDIARMOR = 12
static const int INVALIDSYNTAX = 13
Protected Attributes inherited from CombatQueueCommand
float damage
float damageMultiplier
int accuracyBonus
float speedMultiplier
float speed
int poolsToDamage
float healthCostMultiplier
float actionCostMultiplier
float mindCostMultiplier
float forceCostMultiplier
float forceCost
int knockdownStateChance
int postureDownStateChance
int postureUpStateChance
int dizzyStateChance
int blindStateChance
int stunStateChance
int intimidateStateChance
int nextAttackDelayChance
int durationStateTime
uint32 dotDuration
uint64 dotType
uint8 dotPool
uint32 dotStrength
float dotPotency
bool dotDamageOfHit
int range
String accuracySkillMod
bool areaAction
bool coneAction
int coneAngle
int areaRange
String combatSpam
String stateSpam
uint32 animationCRC
String effectString
VectorMap< uint64, StateEffect > stateEffects
VectorMap< uint64, DotEffect > dotEffects
uint8 attackType
uint8 trails
Detailed Description
Definition at line 51 of file Melee2hLunge1Command.h.
Constructor & Destructor Documentation
Melee2hLunge1Command::Melee2hLunge1Command (const String & name, ZoneProcessServer * server) inline
Definition at line 54 of file Melee2hLunge1Command.h.
Member Function Documentation
int Melee2hLunge1Command::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline virtual
Reimplemented from server::zone::objects::creature::commands::QueueCommand.
Definition at line 58 of file Melee2hLunge1Command.h.
References server::zone::objects::creature::commands::QueueCommand::checkInvalidLocomotions(), server::zone::objects::creature::commands::QueueCommand::checkStateMask(), CombatQueueCommand::doCombatAction(), server::zone::objects::creature::CreatureObject::getWeapon(), server::zone::objects::creature::commands::QueueCommand::INVALIDLOCOMOTION, server::zone::objects::creature::commands::QueueCommand::INVALIDSTATE, and server::zone::objects::creature::commands::QueueCommand::INVALIDWEAPON.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/Melee2hLunge1Command.h