Core3: server::zone::objects::mission::HuntingMissionObjectiveImplementation Class Reference
server::zone::objects::mission::HuntingMissionObjectiveImplementation Class Reference
#include <HuntingMissionObjective.h>
Public Member Functions
HuntingMissionObjectiveImplementation (MissionObject *mission)
HuntingMissionObjectiveImplementation (DummyConstructorParameter *param)
void finalize ()
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
Vector3 getEndPosition ()
operator const HuntingMissionObjective * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
MissionObjectiveImplementation (MissionObject *parent)
MissionObjectiveImplementation (DummyConstructorParameter *param)
virtual void destroyObjectFromDatabase ()
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
virtual void deactivate ()
virtual void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
operator const MissionObjective * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< HuntingMissionObjective * > _this
Public Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
WeakReference< MissionObjective * > _this
Protected Member Functions
virtual ~HuntingMissionObjectiveImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
virtual ~MissionObjectiveImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
int targetsKilled
Friends
class HuntingMissionObjective
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
ManagedWeakReference
< MissionObject * > mission
unsigned int objectiveType
Time missionStartTime
Reference
< FailMissionAfterCertainTimeTask * > failTask
unsigned long long timeRemaining
bool activated
Detailed Description
Definition at line 136 of file HuntingMissionObjective.h.
Constructor & Destructor Documentation
HuntingMissionObjectiveImplementation::HuntingMissionObjectiveImplementation (MissionObject * mission)
Definition at line 260 of file HuntingMissionObjective.cpp.
References _initializeImplementation().
HuntingMissionObjectiveImplementation::HuntingMissionObjectiveImplementation (DummyConstructorParameter * param)
Definition at line 136 of file HuntingMissionObjective.cpp.
References _initializeImplementation().
HuntingMissionObjectiveImplementation::~HuntingMissionObjectiveImplementation () protected virtual
Definition at line 141 of file HuntingMissionObjective.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * HuntingMissionObjectiveImplementation::_getStub ()
Definition at line 159 of file HuntingMissionObjective.cpp.
References _this.
void HuntingMissionObjectiveImplementation::_initializeImplementation () protected
Definition at line 146 of file HuntingMissionObjective.cpp.
References _serializationHelperMethod(), and _this.
Referenced by HuntingMissionObjectiveImplementation().
void HuntingMissionObjectiveImplementation::_serializationHelperMethod () protected
Definition at line 195 of file HuntingMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void HuntingMissionObjectiveImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 154 of file HuntingMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_setStub(), and _this.
Referenced by server::zone::objects::mission::HuntingMissionObjective::HuntingMissionObjective().
void HuntingMissionObjectiveImplementation::abort () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 41 of file HuntingMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::abort(), server::zone::objects::mission::MissionObjectiveImplementation::dropObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getObserverCount(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), and ObserverEventType::KILLEDCREATURE.
Referenced by server::zone::objects::mission::HuntingMissionObjective::abort().
void HuntingMissionObjectiveImplementation::activate () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 24 of file HuntingMissionObjectiveImplementation.cpp.
References _this, server::zone::objects::mission::MissionObjectiveImplementation::activate(), server::zone::objects::mission::MissionObjectiveImplementation::addObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getMissionObject(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::hasObservers(), ObserverEventType::KILLEDCREATURE, and targetsKilled.
Referenced by server::zone::objects::mission::HuntingMissionObjective::activate().
void HuntingMissionObjectiveImplementation::complete () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 59 of file HuntingMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::complete().
Referenced by server::zone::objects::mission::HuntingMissionObjective::complete(), and notifyObserverEvent().
void HuntingMissionObjectiveImplementation::finalize ()
Definition at line 266 of file HuntingMissionObjective.cpp.
Referenced by ~HuntingMissionObjectiveImplementation().
Vector3 HuntingMissionObjectiveImplementation::getEndPosition () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 104 of file HuntingMissionObjectiveImplementation.cpp.
References TerrainManager::getHeight(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), and server::zone::objects::mission::MissionObjectiveImplementation::mission.
Referenced by server::zone::objects::mission::HuntingMissionObjective::getEndPosition().
void HuntingMissionObjectiveImplementation::initializeTransientMembers () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 269 of file HuntingMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::initializeTransientMembers().
Referenced by server::zone::objects::mission::HuntingMissionObjective::initializeTransientMembers(), and readObject().
void HuntingMissionObjectiveImplementation::lock (bool doLock = true) protected
Definition at line 167 of file HuntingMissionObjective.cpp.
References _this.
void HuntingMissionObjectiveImplementation::lock (ManagedObject * obj) protected
Definition at line 171 of file HuntingMissionObjective.cpp.
References _this.
int HuntingMissionObjectiveImplementation::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 64 of file HuntingMissionObjectiveImplementation.cpp.
References complete(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::templates::mobile::CreatureTemplate::getTemplateName(), ObserverEventType::KILLEDCREATURE, server::zone::objects::mission::MissionObjectiveImplementation::mission, server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), and targetsKilled.
Referenced by server::zone::objects::mission::HuntingMissionObjective::notifyObserverEvent().
HuntingMissionObjectiveImplementation::operator const HuntingMissionObjective * ()
Definition at line 163 of file HuntingMissionObjective.cpp.
void HuntingMissionObjectiveImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 202 of file HuntingMissionObjective.cpp.
References initializeTransientMembers(), and readObjectMember().
bool HuntingMissionObjectiveImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 221 of file HuntingMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::readObjectMember(), and targetsKilled.
Referenced by readObject().
void HuntingMissionObjectiveImplementation::rlock (bool doLock = true) protected
Definition at line 175 of file HuntingMissionObjective.cpp.
References _this.
void HuntingMissionObjectiveImplementation::runlock (bool doLock = true) protected
Definition at line 191 of file HuntingMissionObjective.cpp.
References _this.
void HuntingMissionObjectiveImplementation::unlock (bool doLock = true) protected
Definition at line 187 of file HuntingMissionObjective.cpp.
References _this.
void HuntingMissionObjectiveImplementation::wlock (bool doLock = true) protected
Definition at line 179 of file HuntingMissionObjective.cpp.
References _this.
void HuntingMissionObjectiveImplementation::wlock (ManagedObject * obj) protected
Definition at line 183 of file HuntingMissionObjective.cpp.
References _this.
void HuntingMissionObjectiveImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 235 of file HuntingMissionObjective.cpp.
References writeObjectMembers().
int HuntingMissionObjectiveImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 242 of file HuntingMissionObjective.cpp.
References targetsKilled, and server::zone::objects::mission::MissionObjectiveImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class HuntingMissionObjective friend
Definition at line 190 of file HuntingMissionObjective.h.
Member Data Documentation
WeakReference<HuntingMissionObjective*> server::zone::objects::mission::HuntingMissionObjectiveImplementation::_this
Definition at line 158 of file HuntingMissionObjective.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), activate(), lock(), rlock(), runlock(), unlock(), and wlock().
int server::zone::objects::mission::HuntingMissionObjectiveImplementation::targetsKilled private
Definition at line 137 of file HuntingMissionObjective.h.
Referenced by activate(), notifyObserverEvent(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/HuntingMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/HuntingMissionObjective.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/HuntingMissionObjectiveImplementation.cpp