Core3: StartingItemList Class Reference
StartingItemList Class Reference
#include <StartingItemList.h>
Public Member Functions
StartingItemList ()
~StartingItemList ()
void loadItems ()
void addItemToSkill (const String &profession, const String &species, const String &sex, const StartingItem &item)
Vector< StartingItem > * getSkillItems (const String &profession, const String &species, const String &sex)
void init ()
Static Public Member Functions
static int addStartingItemToServer (lua_State *l)
Private Attributes
StartingItemSkillSet * professions
Detailed Description
Definition at line 142 of file StartingItemList.h.
Constructor & Destructor Documentation
StartingItemList::StartingItemList () inline
Definition at line 146 of file StartingItemList.h.
References addStartingItemToServer(), init(), and professions.
StartingItemList::~StartingItemList () inline
Definition at line 155 of file StartingItemList.h.
References professions.
Member Function Documentation
void StartingItemList::addItemToSkill (const String & profession, const String & species, const String & sex, const StartingItem & item) inline
Definition at line 221 of file StartingItemList.h.
References professions.
static int StartingItemList::addStartingItemToServer (lua_State * l) inline static
Definition at line 174 of file StartingItemList.h.
References StartingItem::equipped.
Referenced by StartingItemList().
Vector<StartingItem>* StartingItemList::getSkillItems (const String & profession, const String & species, const String & sex) inline
Definition at line 225 of file StartingItemList.h.
References professions.
void StartingItemList::init () inline
Definition at line 229 of file StartingItemList.h.
References professions.
Referenced by StartingItemList().
void StartingItemList::loadItems () inline
Definition at line 170 of file StartingItemList.h.
Member Data Documentation
StartingItemSkillSet* StartingItemList::professions private
Definition at line 143 of file StartingItemList.h.
Referenced by addItemToSkill(), getSkillItems(), init(), StartingItemList(), and ~StartingItemList().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/StartingItemList.h