Core3: ManualPool Class Reference
ManualPool Class Reference
#include <ManualPool.h>
Public Member Functions
ManualPool (ResourceSpawner *spawner)
~ManualPool ()
void initialize (const String &includes, const String &excludes, int size)
void addResource (ManagedReference< ResourceSpawn * > resourceSpawn, const String &poolSlot)
String healthCheck ()
void print ()
Public Member Functions inherited from ResourcePool
ResourcePool (ResourceSpawner *spawner)
virtual ~ResourcePool ()
void initialize (const String &includes, const String &excludes)
void initializeByTable (LuaObject includes, const String &excludes)
void print ()
Private Member Functions
bool update ()
Friends
class ResourceSpawner
Additional Inherited Members
Static Public Attributes inherited from ResourcePool
static const short NOPOOL = 0
static const short MINIMUMPOOL = 1
static const short RANDOMPOOL = 2
static const short FIXEDPOOL = 3
static const short NATIVEPOOL = 4
static const short MANUALPOOL = 5
Protected Attributes inherited from ResourcePool
VectorMap< String,
ManagedReference
< ResourceSpawn * > > includedResources
Vector< String > excludedResources
ResourceSpawner * resourceSpawner
Detailed Description
The manual pool contains resources manually spawned by admins. The pool should almost always be empty
Definition at line 64 of file ManualPool.h.
Constructor & Destructor Documentation
ManualPool::ManualPool (ResourceSpawner * spawner)
Ctor
Parameters
spawner The pointer to the resource spawner object
Definition at line 54 of file ManualPool.cpp.
ManualPool::~ManualPool ()
Dtor
Definition at line 58 of file ManualPool.cpp.
Member Function Documentation
void ManualPool::addResource (ManagedReference< ResourceSpawn * > resourceSpawn, const String & poolSlot) virtual
Adds resource to this pool
Parameters
resourceSpawn Spawn object to add to the pool
Implements ResourcePool.
Definition at line 62 of file ManualPool.cpp.
References ResourcePool::includedResources, and ResourcePool::MANUALPOOL.
Referenced by ResourceSpawner::loadResourceSpawns(), and ResourceSpawner::manualCreateResourceSpawn().
String ManualPool::healthCheck () virtual
Implements ResourcePool.
Definition at line 96 of file ManualPool.cpp.
References ResourcePool::includedResources.
Referenced by ResourceSpawner::healthCheck().
void ManualPool::initialize (const String & includes, const String & excludes, int size)
Initialized what the pool spawns, and what is excluded
Parameters
includes Comma delimited list of resources to include
excludes Comma delimited list of resources to exclude
void ManualPool::print ()
Print the current state of the Resource Pool
Definition at line 118 of file ManualPool.cpp.
References ResourcePool::includedResources.
bool ManualPool::update () private virtual
The update function checks the ResourceSpawn items in spawnedResources to see if they have expired. If they have not expired, no action is taken, but if they have expired, we replace them according to the rules.
The manual pool doesn't spawn anything on it's own it just removes anything that happens to be expired
Implements ResourcePool.
Definition at line 67 of file ManualPool.cpp.
References ResourceSpawner::despawn(), ResourcePool::includedResources, and ResourcePool::resourceSpawner.
Referenced by ResourceSpawner::shiftResources().
Friends And Related Function Documentation
friend class ResourceSpawner friend
Definition at line 110 of file ManualPool.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcepool/ManualPool.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcepool/ManualPool.cpp