Core3: server::zone::objects::player::sessions::EntertainingSessionAdapter Class Reference
server::zone::objects::player::sessions::EntertainingSessionAdapter Class Reference
#include <EntertainingSession.h>
Public Member Functions
EntertainingSessionAdapter (EntertainingSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void doEntertainerPatronEffects ()
void doPerformanceAction ()
void addEntertainerFlourishBuff ()
void startDancing (const String &dance, const String &animation)
void startPlayingMusic (const String &song, const String &instrumentAnimation, int instrid)
void startEntertaining ()
void finalize ()
void healWounds (CreatureObject *creature, float woundHeal, float shockHeal)
bool isInEntertainingBuilding (CreatureObject *creature)
void doFlourish (int flourishNumber)
bool canHealBattleFatigue ()
bool canGiveEntertainBuff ()
void addFlourishXp (int xp)
void addHealingXp (int xp)
void addHealingXpGroup (int xp)
int initializeSession ()
int cancelSession ()
int clearSession ()
void stopPlayingMusic ()
void stopDancing ()
void activateAction ()
void startTickTask ()
int getEntertainerBuffStrength (CreatureObject *creature, int performanceType)
int getEntertainerBuffDuration (CreatureObject *creature, int performanceType)
int getEntertainerBuffStartTime (CreatureObject *creature, int performanceType)
void sendEntertainingUpdate (CreatureObject *creature, float entval, const String &performance, unsigned int perfcntr, int instrid)
void sendEntertainmentUpdate (CreatureObject *creature, unsigned long long entid, const String &mood, bool updateEntValue)
void activateEntertainerBuff (CreatureObject *creature, int performanceType)
Instrument * getInstrument (CreatureObject *creature)
String getPerformanceName ()
void addWatcher (CreatureObject *creature)
void addListener (CreatureObject *listener)
bool isDancing ()
bool isPlayingMusic ()
bool isAcceptingBandFlourishes ()
void setAcceptingBandFlourishes (bool val)
void removeWatcher (CreatureObject *creature)
void removeListener (CreatureObject *creature)
void setPerformanceName (const String &name)
void setDancing (bool val)
void setTargetInstrument (bool var)
void updateEntertainerMissionStatus (bool entertaining, const int missionType)
bool isInDenyServiceList (CreatureObject *target)
void addToDenyServiceList (CreatureObject *target)
void removeFromDenyServiceList (CreatureObject *target)
void increaseEntertainerBuff (CreatureObject *patron)
void awardEntertainerExperience ()
Detailed Description
Definition at line 431 of file EntertainingSession.h.
Constructor & Destructor Documentation
EntertainingSessionAdapter::EntertainingSessionAdapter (EntertainingSession * impl)
Definition at line 1167 of file EntertainingSession.cpp.
Member Function Documentation
void EntertainingSessionAdapter::activateAction ()
Definition at line 1499 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::activateEntertainerBuff (CreatureObject * creature, int performanceType)
Definition at line 1527 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::addEntertainerFlourishBuff ()
Definition at line 1427 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::addFlourishXp (int xp)
Definition at line 1467 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::addHealingXp (int xp)
Definition at line 1471 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::addHealingXpGroup (int xp)
Definition at line 1475 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::addListener (CreatureObject * listener)
Definition at line 1543 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::addToDenyServiceList (CreatureObject * target)
Definition at line 1591 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::addWatcher (CreatureObject * creature)
Definition at line 1539 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::awardEntertainerExperience ()
Definition at line 1603 of file EntertainingSession.cpp.
Referenced by invokeMethod().
int EntertainingSessionAdapter::cancelSession ()
Definition at line 1483 of file EntertainingSession.cpp.
Referenced by invokeMethod().
bool EntertainingSessionAdapter::canGiveEntertainBuff ()
Definition at line 1463 of file EntertainingSession.cpp.
Referenced by invokeMethod().
bool EntertainingSessionAdapter::canHealBattleFatigue ()
Definition at line 1459 of file EntertainingSession.cpp.
Referenced by invokeMethod().
int EntertainingSessionAdapter::clearSession ()
Definition at line 1487 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::doEntertainerPatronEffects ()
Definition at line 1419 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::doFlourish (int flourishNumber)
Definition at line 1455 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::doPerformanceAction ()
Definition at line 1423 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::finalize ()
Definition at line 1443 of file EntertainingSession.cpp.
Referenced by invokeMethod().
int EntertainingSessionAdapter::getEntertainerBuffDuration (CreatureObject * creature, int performanceType)
Definition at line 1511 of file EntertainingSession.cpp.
Referenced by invokeMethod().
int EntertainingSessionAdapter::getEntertainerBuffStartTime (CreatureObject * creature, int performanceType)
Definition at line 1515 of file EntertainingSession.cpp.
Referenced by invokeMethod().
int EntertainingSessionAdapter::getEntertainerBuffStrength (CreatureObject * creature, int performanceType)
Definition at line 1507 of file EntertainingSession.cpp.
Referenced by invokeMethod().
Instrument * EntertainingSessionAdapter::getInstrument (CreatureObject * creature)
Definition at line 1531 of file EntertainingSession.cpp.
Referenced by invokeMethod().
String EntertainingSessionAdapter::getPerformanceName ()
Definition at line 1535 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::healWounds (CreatureObject * creature, float woundHeal, float shockHeal)
Definition at line 1447 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::increaseEntertainerBuff (CreatureObject * patron)
Definition at line 1599 of file EntertainingSession.cpp.
Referenced by invokeMethod().
int EntertainingSessionAdapter::initializeSession ()
Definition at line 1479 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1170 of file EntertainingSession.cpp.
References activateAction(), activateEntertainerBuff(), addEntertainerFlourishBuff(), addFlourishXp(), addHealingXp(), addHealingXpGroup(), addListener(), addToDenyServiceList(), addWatcher(), awardEntertainerExperience(), cancelSession(), canGiveEntertainBuff(), canHealBattleFatigue(), clearSession(), doEntertainerPatronEffects(), doFlourish(), doPerformanceAction(), finalize(), getEntertainerBuffDuration(), getEntertainerBuffStartTime(), getEntertainerBuffStrength(), getInstrument(), getPerformanceName(), healWounds(), increaseEntertainerBuff(), initializeSession(), isAcceptingBandFlourishes(), isDancing(), isInDenyServiceList(), isInEntertainingBuilding(), isPlayingMusic(), removeFromDenyServiceList(), removeListener(), removeWatcher(), RPC_ACTIVATEACTION__, RPC_ACTIVATEENTERTAINERBUFF__CREATUREOBJECT_INT_, RPC_ADDENTERTAINERFLOURISHBUFF__, RPC_ADDFLOURISHXP__INT_, RPC_ADDHEALINGXP__INT_, RPC_ADDHEALINGXPGROUP__INT_, RPC_ADDLISTENER__CREATUREOBJECT_, RPC_ADDTODENYSERVICELIST__CREATUREOBJECT_, RPC_ADDWATCHER__CREATUREOBJECT_, RPC_AWARDENTERTAINEREXPERIENCE__, RPC_CANCELSESSION__, RPC_CANGIVEENTERTAINBUFF__, RPC_CANHEALBATTLEFATIGUE__, RPC_CLEARSESSION__, RPC_DOENTERTAINERPATRONEFFECTS__, RPC_DOFLOURISH__INT_, RPC_DOPERFORMANCEACTION__, RPC_FINALIZE__, RPC_GETENTERTAINERBUFFDURATION__CREATUREOBJECT_INT_, RPC_GETENTERTAINERBUFFSTARTTIME__CREATUREOBJECT_INT_, RPC_GETENTERTAINERBUFFSTRENGTH__CREATUREOBJECT_INT_, RPC_GETINSTRUMENT__CREATUREOBJECT_, RPC_GETPERFORMANCENAME__, RPC_HEALWOUNDS__CREATUREOBJECT_FLOAT_FLOAT_, RPC_INCREASEENTERTAINERBUFF__CREATUREOBJECT_, RPC_INITIALIZESESSION__, RPC_ISACCEPTINGBANDFLOURISHES__, RPC_ISDANCING__, RPC_ISINDENYSERVICELIST__CREATUREOBJECT_, RPC_ISINENTERTAININGBUILDING__CREATUREOBJECT_, RPC_ISPLAYINGMUSIC__, RPC_REMOVEFROMDENYSERVICELIST__CREATUREOBJECT_, RPC_REMOVELISTENER__CREATUREOBJECT_, RPC_REMOVEWATCHER__CREATUREOBJECT_, RPC_SENDENTERTAININGUPDATE__CREATUREOBJECT_FLOAT_STRING_INT_INT_, RPC_SENDENTERTAINMENTUPDATE__CREATUREOBJECT_LONG_STRING_BOOL_, RPC_SETACCEPTINGBANDFLOURISHES__BOOL_, RPC_SETDANCING__BOOL_, RPC_SETPERFORMANCENAME__STRING_, RPC_SETTARGETINSTRUMENT__BOOL_, RPC_STARTDANCING__STRING_STRING_, RPC_STARTENTERTAINING__, RPC_STARTPLAYINGMUSIC__STRING_STRING_INT_, RPC_STARTTICKTASK__, RPC_STOPDANCING__, RPC_STOPPLAYINGMUSIC__, RPC_UPDATEENTERTAINERMISSIONSTATUS__BOOL_INT_, sendEntertainingUpdate(), sendEntertainmentUpdate(), setAcceptingBandFlourishes(), setDancing(), setPerformanceName(), setTargetInstrument(), startDancing(), startEntertaining(), startPlayingMusic(), startTickTask(), stopDancing(), stopPlayingMusic(), and updateEntertainerMissionStatus().
bool EntertainingSessionAdapter::isAcceptingBandFlourishes ()
Definition at line 1555 of file EntertainingSession.cpp.
Referenced by invokeMethod().
bool EntertainingSessionAdapter::isDancing ()
Definition at line 1547 of file EntertainingSession.cpp.
Referenced by invokeMethod().
bool EntertainingSessionAdapter::isInDenyServiceList (CreatureObject * target)
Definition at line 1587 of file EntertainingSession.cpp.
Referenced by invokeMethod().
bool EntertainingSessionAdapter::isInEntertainingBuilding (CreatureObject * creature)
Definition at line 1451 of file EntertainingSession.cpp.
Referenced by invokeMethod().
bool EntertainingSessionAdapter::isPlayingMusic ()
Definition at line 1551 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::removeFromDenyServiceList (CreatureObject * target)
Definition at line 1595 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::removeListener (CreatureObject * creature)
Definition at line 1567 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::removeWatcher (CreatureObject * creature)
Definition at line 1563 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::sendEntertainingUpdate (CreatureObject * creature, float entval, const String & performance, unsigned int perfcntr, int instrid)
Definition at line 1519 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::sendEntertainmentUpdate (CreatureObject * creature, unsigned long long entid, const String & mood, bool updateEntValue)
Definition at line 1523 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::setAcceptingBandFlourishes (bool val)
Definition at line 1559 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::setDancing (bool val)
Definition at line 1575 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::setPerformanceName (const String & name)
Definition at line 1571 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::setTargetInstrument (bool var)
Definition at line 1579 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::startDancing (const String & dance, const String & animation)
Definition at line 1431 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::startEntertaining ()
Definition at line 1439 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::startPlayingMusic (const String & song, const String & instrumentAnimation, int instrid)
Definition at line 1435 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::startTickTask ()
Definition at line 1503 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::stopDancing ()
Definition at line 1495 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::stopPlayingMusic ()
Definition at line 1491 of file EntertainingSession.cpp.
Referenced by invokeMethod().
void EntertainingSessionAdapter::updateEntertainerMissionStatus (bool entertaining, const int missionType)
Definition at line 1583 of file EntertainingSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/EntertainingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/EntertainingSession.cpp