Core3: server::zone::managers::auction::AuctionManagerImplementation Class Reference
server::zone::managers::auction::AuctionManagerImplementation Class Reference
#include <AuctionManager.h>
Public Member Functions
AuctionManagerImplementation (ZoneServer *server)
AuctionManagerImplementation (DummyConstructorParameter *param)
void initialize ()
void addSaleItem (CreatureObject *player, unsigned long long objectid, SceneObject *vendor, const UnicodeString &description, int price, unsigned int duration, bool auction, bool premium)
AuctionItem * createVendorItem (CreatureObject *player, SceneObject *objectToSell, SceneObject *vendor, const UnicodeString &description, int price, unsigned int duration, bool auction, bool premium)
int checkSaleItem (CreatureObject *player, SceneObject *object, SceneObject *vendor, int price, bool premium)
void getItemAttributes (CreatureObject *player, unsigned long long objectid)
void getData (CreatureObject *player, int extent, unsigned long long vendorObjectID, int screen, unsigned int category, int count, int offset)
void getAuctionData (CreatureObject *player, SceneObject *usedVendor, const String &planet, const String &region, SceneObject *vendor, int screen, unsigned int category, int count, int offset)
int checkRetrieve (CreatureObject *player, unsigned long long objectIdToRetrieve, SceneObject *vendor)
void retrieveItem (CreatureObject *player, unsigned long long objectid, unsigned long long vendorID)
void buyItem (CreatureObject *player, unsigned long long objectid, int price1, int price2)
void doAuctionBid (CreatureObject *player, AuctionItem *item, int price1, int price2)
void doInstantBuy (CreatureObject *player, AuctionItem *item)
int checkBidAuction (CreatureObject *player, AuctionItem *item, int price1, int price2)
void cancelItem (CreatureObject *player, unsigned long long objectID)
AuctionQueryHeadersResponseMessage * fillAuctionQueryHeadersResponseMessage (CreatureObject *player, SceneObject *vendor, TerminalListVector *terminalList, int screen, unsigned int category, int count, int offset)
AuctionsMap * getAuctionMap ()
void checkVendorItems ()
void checkAuctions ()
String getVendorUID (SceneObject *vendor)
void updateVendorUID (SceneObject *vendor, const String &oldUID, const String &newUID)
void updateVendorSearch (SceneObject *vendor, bool enabled)
void expireSale (AuctionItem *item)
void expireBidAuction (AuctionItem *item)
void expireAuction (AuctionItem *item)
void deleteExpiredSale (AuctionItem *item)
bool isMarketEnabled ()
void setMarketEnabled (bool value)
void displayInfo (CreatureObject *player)
void updateAuctionOwner (AuctionItem *item, CreatureObject *player)
operator const AuctionManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< AuctionManager * > _this
Static Public Attributes
static const int MAXBAZAARPRICE = 20000
static const int MAXSALES = 25
static const int SALESFEE = 20
static const int CHECKEVERY = 60
static const int MAXVENDORPRICE = 99999999
static const int ITEMSPERPAGE = 100
static const int VENDOREXPIREPERIOD = 2592000
static const int COMMODITYEXPIREPERIOD = 604800
Protected Member Functions
virtual ~AuctionManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference< AuctionsMap * > auctionMap
ManagedReference< ZoneServer * > zoneServer
AuctionEventsMap auctionEvents
VectorMap< ManagedReference
< SceneObject * >, String > pendingUIDUpdates
VectorMap< ManagedReference
< SceneObject * >, String > pendingOldUIDUpdates
Private Member Functions
void refundAuction (AuctionItem *item)
void doAuctionMaint (TerminalListVector *items)
Private Attributes
bool marketEnabled
Friends
class AuctionManager
Detailed Description
Definition at line 240 of file AuctionManager.h.
Constructor & Destructor Documentation
AuctionManagerImplementation::AuctionManagerImplementation (ZoneServer * server)
Definition at line 646 of file AuctionManager.cpp.
References _initializeImplementation(), auctionEvents, marketEnabled, and zoneServer.
AuctionManagerImplementation::AuctionManagerImplementation (DummyConstructorParameter * param)
Definition at line 460 of file AuctionManager.cpp.
References _initializeImplementation().
AuctionManagerImplementation::~AuctionManagerImplementation () protected virtual
Definition at line 465 of file AuctionManager.cpp.
Member Function Documentation
DistributedObjectStub * AuctionManagerImplementation::_getStub ()
Definition at line 485 of file AuctionManager.cpp.
References _this.
void AuctionManagerImplementation::_initializeImplementation () protected
Definition at line 472 of file AuctionManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by AuctionManagerImplementation().
void AuctionManagerImplementation::_serializationHelperMethod () protected
Definition at line 521 of file AuctionManager.cpp.
Referenced by _initializeImplementation().
void AuctionManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 480 of file AuctionManager.cpp.
References _this.
Referenced by server::zone::managers::auction::AuctionManager::AuctionManager().
void AuctionManagerImplementation::addSaleItem (CreatureObject * player, unsigned long long objectid, SceneObject * vendor, const UnicodeString & description, int price, unsigned int duration, bool auction, bool premium)
Is it being sold from the stockroom
Definition at line 200 of file AuctionManagerImplementation.cpp.
References _this, ItemSoldMessage::ALREADYFORSALE, auctionEvents, auctionMap, checkSaleItem(), createVendorItem(), server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getObjectID(), VendorDataComponent::getOwnerId(), getVendorUID(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::hasSkill(), ItemSoldMessage::INVALIDITEM, server::zone::objects::scene::SceneObject::isBazaarTerminal(), server::zone::objects::scene::SceneObject::isVendor(), SALESFEE, server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), server::zone::objects::creature::CreatureObject::subtractBankCredits(), ItemSoldMessage::SUCCESS, SessionFacadeType::TRADE, ItemSoldMessage::UNKNOWNERROR, ItemSoldMessage::VENDORNOTWORKING, and zoneServer.
Referenced by server::zone::managers::auction::AuctionManager::addSaleItem().
void AuctionManagerImplementation::buyItem (CreatureObject * player, unsigned long long objectid, int price1, int price2)
Definition at line 807 of file AuctionManagerImplementation.cpp.
References auctionMap, checkBidAuction(), doAuctionBid(), doInstantBuy(), server::zone::objects::scene::SceneObject::getObjectID(), BidAuctionResponseMessage::INVALIDITEM, BidAuctionResponseMessage::PURCHASEFAILED, server::zone::objects::creature::CreatureObject::sendMessage(), and zoneServer.
Referenced by server::zone::managers::auction::AuctionManager::buyItem().
void AuctionManagerImplementation::cancelItem (CreatureObject * player, unsigned long long objectID)
7 Days
If the offeree cancels
Definition at line 1252 of file AuctionManagerImplementation.cpp.
References CancelLiveAuctionResponseMessage::ALREADYCOMPLETED, auctionEvents, auctionMap, server::zone::managers::auction::AuctionManager::COMMODITYEXPIREPERIOD, server::zone::objects::scene::SceneObject::getObjectID(), CancelLiveAuctionResponseMessage::INVALIDITEM, CancelLiveAuctionResponseMessage::NOTOWNER, refundAuction(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::waypoint::WaypointObject::setPlanetCRC(), server::chat::StringIdChatParameter::setTO(), server::zone::managers::auction::AuctionManager::VENDOREXPIREPERIOD, and zoneServer.
Referenced by server::zone::managers::auction::AuctionManager::cancelItem().
void AuctionManagerImplementation::checkAuctions ()
Definition at line 146 of file AuctionManagerImplementation.cpp.
References _this, auctionMap, CHECKEVERY, and doAuctionMaint().
Referenced by server::zone::managers::auction::AuctionManager::checkAuctions(), and initialize().
int AuctionManagerImplementation::checkBidAuction (CreatureObject * player, AuctionItem * item, int price1, int price2)
Definition at line 496 of file AuctionManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getBankCredits(), BidAuctionResponseMessage::INVALIDPRICE, server::zone::objects::auction::AuctionItem::isOnBazaar(), MAXBAZAARPRICE, BidAuctionResponseMessage::NOTENOUGHCREDITS, and BidAuctionResponseMessage::PRICEOVERFLOW.
Referenced by buyItem(), and server::zone::managers::auction::AuctionManager::checkBidAuction().
int AuctionManagerImplementation::checkRetrieve (CreatureObject * player, unsigned long long objectIdToRetrieve, SceneObject * vendor)
Definition at line 852 of file AuctionManagerImplementation.cpp.
References auctionMap, RetrieveAuctionItemResponseMessage::FULLINVENTORY, server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::scene::SceneObject::isBazaarTerminal(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::scene::SceneObject::isVendor(), RetrieveAuctionItemResponseMessage::NOTALLOWED, server::zone::objects::creature::CreatureObject::sendSystemMessage(), RetrieveAuctionItemResponseMessage::TOOFAR, and zoneServer.
Referenced by server::zone::managers::auction::AuctionManager::checkRetrieve(), and retrieveItem().
int AuctionManagerImplementation::checkSaleItem (CreatureObject * player, SceneObject * object, SceneObject * vendor, int price, bool premium)
Definition at line 375 of file AuctionManagerImplementation.cpp.
References ItemSoldMessage::ALREADYFORSALE, auctionMap, server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getObjectID(), VendorDataComponent::getOwnerId(), server::zone::objects::creature::CreatureObject::getSkillMod(), ItemSoldMessage::INVALIDITEM, ItemSoldMessage::INVALIDSALEPRICE, server::zone::objects::scene::SceneObject::isBazaarTerminal(), server::zone::objects::scene::SceneObject::isIntangibleObject(), server::zone::objects::scene::SceneObject::isVendor(), MAXBAZAARPRICE, MAXSALES, MAXVENDORPRICE, ItemSoldMessage::NOTENOUGHCREDITS, SALESFEE, ItemSoldMessage::TOOMANYITEMS, and ItemSoldMessage::UNKNOWNERROR.
Referenced by addSaleItem(), and server::zone::managers::auction::AuctionManager::checkSaleItem().
void AuctionManagerImplementation::checkVendorItems ()
Definition at line 137 of file AuctionManagerImplementation.cpp.
References auctionMap, and doAuctionMaint().
Referenced by server::zone::managers::auction::AuctionManager::checkVendorItems(), and initialize().
AuctionItem * AuctionManagerImplementation::createVendorItem (CreatureObject * player, SceneObject * objectToSell, SceneObject * vendor, const UnicodeString & description, int price, unsigned int duration, bool auction, bool premium)
Definition at line 428 of file AuctionManagerImplementation.cpp.
References server::zone::managers::auction::AuctionManager::COMMODITYEXPIREPERIOD, server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getClientGameObjectType(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getObjectID(), VendorDataComponent::getOwnerId(), VendorDataComponent::getOwnershipRightsOf(), getVendorUID(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::scene::SceneObject::isBazaarTerminal(), server::zone::objects::auction::AuctionItem::setAuction(), server::zone::objects::auction::AuctionItem::setAuctionPremium(), server::zone::objects::auction::AuctionItem::setBidderName(), server::zone::objects::auction::AuctionItem::setBuyerID(), server::zone::objects::auction::AuctionItem::setExpireTime(), server::zone::objects::auction::AuctionItem::setItemDescription(), server::zone::objects::auction::AuctionItem::setItemName(), server::zone::objects::auction::AuctionItem::setItemType(), server::zone::objects::auction::AuctionItem::setOfferToID(), server::zone::objects::auction::AuctionItem::setOnBazaar(), server::zone::objects::auction::AuctionItem::setPrice(), server::zone::objects::auction::AuctionItem::setStatus(), server::zone::objects::auction::AuctionItem::setVendorID(), server::zone::objects::auction::AuctionItem::setVendorUID(), updateAuctionOwner(), and server::zone::managers::auction::AuctionManager::VENDOREXPIREPERIOD.
Referenced by addSaleItem(), and server::zone::managers::auction::AuctionManager::createVendorItem().
void AuctionManagerImplementation::deleteExpiredSale (AuctionItem * item)
Definition at line 1543 of file AuctionManagerImplementation.cpp.
References auctionMap, server::zone::objects::auction::AuctionItem::getItemName(), server::zone::objects::auction::AuctionItem::getOwnerName(), server::zone::objects::auction::AuctionItem::getVendorID(), server::zone::objects::waypoint::WaypointObject::setPlanetCRC(), server::chat::StringIdChatParameter::setTO(), and zoneServer.
Referenced by server::zone::managers::auction::AuctionManager::deleteExpiredSale(), and expireSale().
void AuctionManagerImplementation::displayInfo (CreatureObject * player)
Definition at line 1575 of file AuctionManagerImplementation.cpp.
References auctionMap, SuiWindowType::MARKET_INFO, and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::managers::auction::AuctionManager::displayInfo().
void AuctionManagerImplementation::doAuctionBid (CreatureObject * player, AuctionItem * item, int price1, int price2)
Use previous proxy
Definition at line 698 of file AuctionManagerImplementation.cpp.
References server::zone::objects::auction::AuctionItem::getAuctionedItemObjectID(), server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::auction::AuctionItem::getBidderName(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::auction::AuctionItem::getItemName(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::auction::AuctionItem::getOwnerName(), server::zone::objects::auction::AuctionItem::getPrice(), BidAuctionResponseMessage::NOTENOUGHCREDITS, server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::auction::AuctionItem::setBidderName(), server::zone::objects::auction::AuctionItem::setBuyerID(), server::zone::objects::auction::AuctionItem::setPrice(), server::zone::objects::auction::AuctionItem::setProxy(), server::chat::StringIdChatParameter::setTO(), server::zone::objects::creature::CreatureObject::subtractBankCredits(), BidAuctionResponseMessage::SUCCEDED, and zoneServer.
Referenced by buyItem(), and server::zone::managers::auction::AuctionManager::doAuctionBid().
void AuctionManagerImplementation::doAuctionMaint (TerminalListVector * items) private
Definition at line 158 of file AuctionManagerImplementation.cpp.
References auctionMap, expireSale(), getVendorUID(), and zoneServer.
Referenced by checkAuctions(), and checkVendorItems().
void AuctionManagerImplementation::doInstantBuy (CreatureObject * player, AuctionItem * item)
Definition at line 512 of file AuctionManagerImplementation.cpp.
References server::zone::objects::auction::AuctionItem::clearAuctionWithdraw(), server::zone::managers::auction::AuctionManager::COMMODITYEXPIREPERIOD, server::zone::objects::auction::AuctionItem::getAuctionedItemObjectID(), server::zone::objects::auction::AuctionItem::getBidderName(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::auction::AuctionItem::getItemName(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::auction::AuctionItem::getOwnerName(), server::zone::objects::auction::AuctionItem::getPrice(), server::zone::objects::auction::AuctionItem::getStatus(), server::zone::objects::auction::AuctionItem::getVendorID(), server::zone::objects::auction::AuctionItem::isOnBazaar(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::auction::AuctionItem::setBidderName(), server::zone::objects::auction::AuctionItem::setBuyerID(), server::chat::StringIdChatParameter::setDI(), server::zone::objects::auction::AuctionItem::setExpireTime(), server::zone::objects::waypoint::WaypointObject::setPlanetCRC(), server::zone::objects::auction::AuctionItem::setStatus(), server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), server::chat::StringIdChatParameter::setTU(), server::zone::objects::creature::CreatureObject::subtractBankCredits(), updateAuctionOwner(), server::zone::managers::auction::AuctionManager::VENDOREXPIREPERIOD, and zoneServer.
Referenced by buyItem(), and server::zone::managers::auction::AuctionManager::doInstantBuy().
void AuctionManagerImplementation::expireAuction (AuctionItem * item)
Definition at line 1426 of file AuctionManagerImplementation.cpp.
References server::zone::objects::auction::AuctionItem::clearAuctionWithdraw(), server::zone::managers::auction::AuctionManager::COMMODITYEXPIREPERIOD, expireBidAuction(), server::zone::objects::auction::AuctionItem::getBidderName(), server::zone::objects::auction::AuctionItem::getItemName(), server::zone::objects::auction::AuctionItem::getOwnerName(), server::zone::objects::auction::AuctionItem::getPrice(), server::zone::objects::auction::AuctionItem::getVendorID(), server::zone::objects::auction::AuctionItem::isOnBazaar(), server::chat::StringIdChatParameter::setDI(), server::zone::objects::auction::AuctionItem::setExpireTime(), server::zone::objects::waypoint::WaypointObject::setPlanetCRC(), server::zone::objects::auction::AuctionItem::setStatus(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), server::chat::StringIdChatParameter::setTU(), updateAuctionOwner(), and zoneServer.
Referenced by server::zone::managers::auction::AuctionManager::expireAuction().
void AuctionManagerImplementation::expireBidAuction (AuctionItem * item)
Definition at line 1394 of file AuctionManagerImplementation.cpp.
References server::zone::objects::auction::AuctionItem::clearAuctionWithdraw(), server::zone::managers::auction::AuctionManager::COMMODITYEXPIREPERIOD, server::zone::objects::auction::AuctionItem::getItemName(), server::zone::objects::auction::AuctionItem::getOwnerName(), server::zone::objects::auction::AuctionItem::isOnBazaar(), server::zone::objects::auction::AuctionItem::setExpireTime(), server::zone::objects::auction::AuctionItem::setStatus(), server::chat::StringIdChatParameter::setTO(), server::zone::managers::auction::AuctionManager::VENDOREXPIREPERIOD, and zoneServer.
Referenced by expireAuction(), and server::zone::managers::auction::AuctionManager::expireBidAuction().
void AuctionManagerImplementation::expireSale (AuctionItem * item)
Definition at line 1358 of file AuctionManagerImplementation.cpp.
References server::zone::objects::auction::AuctionItem::clearAuctionWithdraw(), server::zone::managers::auction::AuctionManager::COMMODITYEXPIREPERIOD, deleteExpiredSale(), server::zone::objects::auction::AuctionItem::getItemName(), server::zone::objects::auction::AuctionItem::getOwnerName(), server::zone::objects::auction::AuctionItem::getStatus(), server::zone::objects::auction::AuctionItem::isOnBazaar(), server::zone::objects::auction::AuctionItem::setExpireTime(), server::zone::objects::auction::AuctionItem::setStatus(), server::chat::StringIdChatParameter::setTO(), server::zone::managers::auction::AuctionManager::VENDOREXPIREPERIOD, and zoneServer.
Referenced by doAuctionMaint(), server::zone::managers::auction::AuctionManager::expireSale(), and fillAuctionQueryHeadersResponseMessage().
AuctionQueryHeadersResponseMessage * AuctionManagerImplementation::fillAuctionQueryHeadersResponseMessage (CreatureObject * player, SceneObject * vendor, TerminalListVector * terminalList, int screen, unsigned int category, int count, int offset)
Exclude non-searchable vendor Items
Definition at line 1019 of file AuctionManagerImplementation.cpp.
References AuctionQueryHeadersResponseMessage::addItemToList(), AuctionQueryHeadersResponseMessage::createMessage(), expireSale(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::isBazaarTerminal(), and server::zone::objects::scene::SceneObject::isVendor().
Referenced by server::zone::managers::auction::AuctionManager::fillAuctionQueryHeadersResponseMessage(), and getAuctionData().
void AuctionManagerImplementation::finalize () protected
Definition at line 469 of file AuctionManager.cpp.
void AuctionManagerImplementation::getAuctionData (CreatureObject * player, SceneObject * usedVendor, const String & planet, const String & region, SceneObject * vendor, int screen, unsigned int category, int count, int offset)
Definition at line 1205 of file AuctionManagerImplementation.cpp.
References auctionMap, fillAuctionQueryHeadersResponseMessage(), server::zone::objects::scene::SceneObject::isBazaarTerminal(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::managers::auction::AuctionManager::getAuctionData(), and getData().
AuctionsMap * AuctionManagerImplementation::getAuctionMap ()
Definition at line 664 of file AuctionManager.cpp.
References auctionMap.
Referenced by server::zone::managers::auction::AuctionManager::getAuctionMap().
void AuctionManagerImplementation::getData (CreatureObject * player, int extent, unsigned long long vendorObjectID, int screen, unsigned int category, int count, int offset)
Definition at line 1141 of file AuctionManagerImplementation.cpp.
References VendorDataComponent::awardUseXP(), getAuctionData(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getRootParent(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), and zoneServer.
Referenced by server::zone::managers::auction::AuctionManager::getData().
void AuctionManagerImplementation::getItemAttributes (CreatureObject * player, unsigned long long objectid)
Definition at line 1219 of file AuctionManagerImplementation.cpp.
References auctionMap, server::zone::objects::creature::CreatureObject::sendMessage(), and zoneServer.
Referenced by server::zone::managers::auction::AuctionManager::getItemAttributes().
String AuctionManagerImplementation::getVendorUID (SceneObject * vendor)
Definition at line 353 of file AuctionManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getObjectID(), and server::zone::objects::scene::SceneObject::getZone().
Referenced by addSaleItem(), createVendorItem(), doAuctionMaint(), server::zone::managers::auction::AuctionManager::getVendorUID(), initialize(), and retrieveItem().
void AuctionManagerImplementation::initialize ()
This is in case a bazaar is removed, it could move and item to a difference city, but at least it doesn't poof
Definition at line 38 of file AuctionManagerImplementation.cpp.
References _this, auctionEvents, auctionMap, checkAuctions(), checkVendorItems(), getVendorUID(), marketEnabled, pendingOldUIDUpdates, pendingUIDUpdates, and zoneServer.
Referenced by server::zone::managers::auction::AuctionManager::initialize().
bool AuctionManagerImplementation::isMarketEnabled ()
Definition at line 690 of file AuctionManager.cpp.
References marketEnabled.
Referenced by server::zone::managers::auction::AuctionManager::isMarketEnabled().
void AuctionManagerImplementation::lock (bool doLock = true) protected
Definition at line 493 of file AuctionManager.cpp.
References _this.
void AuctionManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 497 of file AuctionManager.cpp.
References _this.
AuctionManagerImplementation::operator const AuctionManager * ()
Definition at line 489 of file AuctionManager.cpp.
void AuctionManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 528 of file AuctionManager.cpp.
References readObjectMember().
bool AuctionManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 547 of file AuctionManager.cpp.
References auctionEvents, auctionMap, marketEnabled, pendingOldUIDUpdates, pendingUIDUpdates, and zoneServer.
Referenced by readObject().
void AuctionManagerImplementation::refundAuction (AuctionItem * item) private
Definition at line 933 of file AuctionManagerImplementation.cpp.
References server::zone::objects::auction::AuctionItem::getBidderName(), server::zone::objects::auction::AuctionItem::getItemName(), server::zone::objects::auction::AuctionItem::getOwnerName(), server::zone::objects::auction::AuctionItem::getPrice(), server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), and zoneServer.
Referenced by cancelItem().
void AuctionManagerImplementation::retrieveItem (CreatureObject * player, unsigned long long objectid, unsigned long long vendorID)
Definition at line 953 of file AuctionManagerImplementation.cpp.
References auctionMap, checkRetrieve(), RetrieveAuctionItemResponseMessage::DONTRETRIEVE, server::zone::objects::scene::SceneObject::getSlottedObject(), getVendorUID(), RetrieveAuctionItemResponseMessage::NOTALLOWED, server::zone::objects::creature::CreatureObject::sendMessage(), RetrieveAuctionItemResponseMessage::TOOFAR, and zoneServer.
Referenced by server::zone::managers::auction::AuctionManager::retrieveItem().
void AuctionManagerImplementation::rlock (bool doLock = true) protected
Definition at line 501 of file AuctionManager.cpp.
References _this.
void AuctionManagerImplementation::runlock (bool doLock = true) protected
Definition at line 517 of file AuctionManager.cpp.
References _this.
void AuctionManagerImplementation::setMarketEnabled (bool value)
Definition at line 695 of file AuctionManager.cpp.
References _this, and marketEnabled.
Referenced by server::zone::managers::auction::AuctionManager::setMarketEnabled().
void AuctionManagerImplementation::unlock (bool doLock = true) protected
Definition at line 513 of file AuctionManager.cpp.
References _this.
void AuctionManagerImplementation::updateAuctionOwner (AuctionItem * item, CreatureObject * player)
Definition at line 1588 of file AuctionManagerImplementation.cpp.
References auctionMap, server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::auction::AuctionItem::getOwnerName(), server::zone::objects::auction::AuctionItem::getStatus(), server::zone::objects::auction::AuctionItem::isOnBazaar(), server::zone::objects::auction::AuctionItem::setOwnerID(), server::zone::objects::auction::AuctionItem::setOwnerName(), and zoneServer.
Referenced by createVendorItem(), doInstantBuy(), expireAuction(), and server::zone::managers::auction::AuctionManager::updateAuctionOwner().
void AuctionManagerImplementation::updateVendorSearch (SceneObject * vendor, bool enabled)
Definition at line 684 of file AuctionManager.cpp.
References _this, and auctionMap.
Referenced by server::zone::managers::auction::AuctionManager::updateVendorSearch().
void AuctionManagerImplementation::updateVendorUID (SceneObject * vendor, const String & oldUID, const String & newUID)
Definition at line 669 of file AuctionManager.cpp.
References _this, auctionMap, pendingOldUIDUpdates, and pendingUIDUpdates.
Referenced by server::zone::managers::auction::AuctionManager::updateVendorUID().
void AuctionManagerImplementation::wlock (bool doLock = true) protected
Definition at line 505 of file AuctionManager.cpp.
References _this.
void AuctionManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 509 of file AuctionManager.cpp.
References _this.
void AuctionManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 581 of file AuctionManager.cpp.
References writeObjectMembers().
int AuctionManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 588 of file AuctionManager.cpp.
References auctionEvents, auctionMap, marketEnabled, pendingOldUIDUpdates, pendingUIDUpdates, and zoneServer.
Referenced by writeObject().
Friends And Related Function Documentation
friend class AuctionManager friend
Definition at line 377 of file AuctionManager.h.
Member Data Documentation
WeakReference<AuctionManager*> server::zone::managers::auction::AuctionManagerImplementation::_this
Definition at line 343 of file AuctionManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addSaleItem(), checkAuctions(), initialize(), lock(), rlock(), runlock(), setMarketEnabled(), unlock(), updateVendorSearch(), updateVendorUID(), and wlock().
AuctionEventsMap server::zone::managers::auction::AuctionManagerImplementation::auctionEvents protected
Definition at line 246 of file AuctionManager.h.
Referenced by addSaleItem(), AuctionManagerImplementation(), cancelItem(), initialize(), readObjectMember(), and writeObjectMembers().
ManagedReference<AuctionsMap* > server::zone::managers::auction::AuctionManagerImplementation::auctionMap protected
Definition at line 242 of file AuctionManager.h.
Referenced by addSaleItem(), buyItem(), cancelItem(), checkAuctions(), checkRetrieve(), checkSaleItem(), checkVendorItems(), deleteExpiredSale(), displayInfo(), doAuctionMaint(), getAuctionData(), getAuctionMap(), getItemAttributes(), initialize(), readObjectMember(), retrieveItem(), updateAuctionOwner(), updateVendorSearch(), updateVendorUID(), and writeObjectMembers().
const int server::zone::managers::auction::AuctionManagerImplementation::CHECKEVERY = 60 static
Definition at line 259 of file AuctionManager.h.
Referenced by checkAuctions().
const int server::zone::managers::auction::AuctionManagerImplementation::COMMODITYEXPIREPERIOD = 604800 static
Definition at line 267 of file AuctionManager.h.
const int server::zone::managers::auction::AuctionManagerImplementation::ITEMSPERPAGE = 100 static
Definition at line 263 of file AuctionManager.h.
bool server::zone::managers::auction::AuctionManagerImplementation::marketEnabled private
Definition at line 270 of file AuctionManager.h.
Referenced by AuctionManagerImplementation(), initialize(), isMarketEnabled(), readObjectMember(), setMarketEnabled(), and writeObjectMembers().
const int server::zone::managers::auction::AuctionManagerImplementation::MAXBAZAARPRICE = 20000 static
Definition at line 253 of file AuctionManager.h.
Referenced by checkBidAuction(), and checkSaleItem().
const int server::zone::managers::auction::AuctionManagerImplementation::MAXSALES = 25 static
Definition at line 255 of file AuctionManager.h.
Referenced by checkSaleItem().
const int server::zone::managers::auction::AuctionManagerImplementation::MAXVENDORPRICE = 99999999 static
Definition at line 261 of file AuctionManager.h.
Referenced by checkSaleItem().
VectorMap<ManagedReference<SceneObject* >, String> server::zone::managers::auction::AuctionManagerImplementation::pendingOldUIDUpdates protected
Definition at line 250 of file AuctionManager.h.
Referenced by initialize(), readObjectMember(), updateVendorUID(), and writeObjectMembers().
VectorMap<ManagedReference<SceneObject* >, String> server::zone::managers::auction::AuctionManagerImplementation::pendingUIDUpdates protected
Definition at line 248 of file AuctionManager.h.
Referenced by initialize(), readObjectMember(), updateVendorUID(), and writeObjectMembers().
const int server::zone::managers::auction::AuctionManagerImplementation::SALESFEE = 20 static
Definition at line 257 of file AuctionManager.h.
Referenced by addSaleItem(), and checkSaleItem().
const int server::zone::managers::auction::AuctionManagerImplementation::VENDOREXPIREPERIOD = 2592000 static
Definition at line 265 of file AuctionManager.h.
ManagedReference<ZoneServer* > server::zone::managers::auction::AuctionManagerImplementation::zoneServer protected
Definition at line 244 of file AuctionManager.h.
Referenced by addSaleItem(), AuctionManagerImplementation(), buyItem(), cancelItem(), checkRetrieve(), deleteExpiredSale(), doAuctionBid(), doAuctionMaint(), doInstantBuy(), expireAuction(), expireBidAuction(), expireSale(), getData(), getItemAttributes(), initialize(), readObjectMember(), refundAuction(), retrieveItem(), updateAuctionOwner(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionManagerImplementation.cpp