Core3: FactoryObjectMenuComponent Class Reference
FactoryObjectMenuComponent Class Reference
#include <FactoryObjectMenuComponent.h>
Public Member Functions
void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *creature)
int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *creature, byte selectedID)
Detailed Description
Definition at line 14 of file FactoryObjectMenuComponent.h.
Member Function Documentation
void FactoryObjectMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from InstallationObjectMenuComponent.
Definition at line 14 of file FactoryObjectMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID(), InstallationObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::isFactory(), server::zone::objects::structure::StructureObject::isOnAdminList(), and server::zone::objects::installation::InstallationObject::isOperating().
int FactoryObjectMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Send ingredient Hopper
Send output Hopper
Schematic Slot
Send ingredients list
Send schematic requirements
Reimplemented from InstallationObjectMenuComponent.
Definition at line 43 of file FactoryObjectMenuComponent.cpp.
References InstallationObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::installation::factory::FactoryObject::handleOperateToggle(), server::zone::objects::scene::SceneObject::isFactory(), server::zone::objects::structure::StructureObject::isOnAdminList(), server::zone::objects::installation::factory::FactoryObject::sendIngredientHopper(), server::zone::objects::installation::factory::FactoryObject::sendIngredientsNeededSui(), server::zone::objects::installation::factory::FactoryObject::sendInsertManuSui(), and server::zone::objects::installation::factory::FactoryObject::sendOutputHopper().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/FactoryObjectMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/FactoryObjectMenuComponent.cpp