Core3: server::zone::objects::mission::ReconMissionObjectiveAdapter Class Reference
server::zone::objects::mission::ReconMissionObjectiveAdapter Class Reference
#include <ReconMissionObjective.h>
Public Member Functions
ReconMissionObjectiveAdapter (ReconMissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveAdapter
MissionObjectiveAdapter (MissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Detailed Description
Definition at line 190 of file ReconMissionObjective.h.
Constructor & Destructor Documentation
ReconMissionObjectiveAdapter::ReconMissionObjectiveAdapter (ReconMissionObjective * impl)
Definition at line 268 of file ReconMissionObjective.cpp.
Member Function Documentation
void ReconMissionObjectiveAdapter::abort ()
Definition at line 317 of file ReconMissionObjective.cpp.
Referenced by invokeMethod().
void ReconMissionObjectiveAdapter::activate ()
Definition at line 313 of file ReconMissionObjective.cpp.
Referenced by invokeMethod().
void ReconMissionObjectiveAdapter::complete ()
Definition at line 321 of file ReconMissionObjective.cpp.
Referenced by invokeMethod().
void ReconMissionObjectiveAdapter::finalize ()
Definition at line 305 of file ReconMissionObjective.cpp.
Referenced by invokeMethod().
void ReconMissionObjectiveAdapter::initializeTransientMembers ()
Definition at line 309 of file ReconMissionObjective.cpp.
Referenced by invokeMethod().
void ReconMissionObjectiveAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 271 of file ReconMissionObjective.cpp.
References abort(), activate(), complete(), finalize(), initializeTransientMembers(), RPC_ABORT__, RPC_ACTIVATE__, RPC_COMPLETE__, RPC_FINALIZE__, and RPC_INITIALIZETRANSIENTMEMBERS__.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/ReconMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/ReconMissionObjective.cpp