Core3: server::zone::objects::player::sessions::FindSessionAdapter Class Reference
server::zone::objects::player::sessions::FindSessionAdapter Class Reference
#include <FindSession.h>
Public Member Functions
FindSessionAdapter (FindSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession ()
int cancelSession ()
int clearSession ()
void addWaypoint (float x, float y, const String &name)
void clearWaypoint ()
Detailed Description
Definition at line 157 of file FindSession.h.
Constructor & Destructor Documentation
FindSessionAdapter::FindSessionAdapter (FindSession * impl)
Definition at line 315 of file FindSession.cpp.
Member Function Documentation
void FindSessionAdapter::addWaypoint (float x, float y, const String & name)
Definition at line 365 of file FindSession.cpp.
Referenced by invokeMethod().
int FindSessionAdapter::cancelSession ()
Definition at line 357 of file FindSession.cpp.
Referenced by invokeMethod().
int FindSessionAdapter::clearSession ()
Definition at line 361 of file FindSession.cpp.
Referenced by invokeMethod().
void FindSessionAdapter::clearWaypoint ()
Definition at line 369 of file FindSession.cpp.
Referenced by invokeMethod().
int FindSessionAdapter::initializeSession ()
Definition at line 353 of file FindSession.cpp.
Referenced by invokeMethod().
void FindSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 318 of file FindSession.cpp.
References addWaypoint(), cancelSession(), clearSession(), clearWaypoint(), initializeSession(), RPC_ADDWAYPOINT__FLOAT_FLOAT_STRING_, RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_CLEARWAYPOINT__, and RPC_INITIALIZESESSION__.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/FindSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/FindSession.cpp