Core3: server::zone::objects::player::PlayerObjectAdapter Class Reference
server::zone::objects::player::PlayerObjectAdapter Class Reference
#include <PlayerObject.h>
Public Member Functions
PlayerObjectAdapter (PlayerObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void notifyLoadFromDatabase ()
void unload ()
void initializeTransientMembers ()
void sendBaselinesTo (SceneObject *player)
void sendMessage (BasePacket *msg)
void addOwnedStructure (StructureObject *obj)
void removeOwnedStructure (StructureObject *obj)
int getTotalOwnedStructureCount ()
bool isOwnedStructure (StructureObject *obj)
unsigned long long getOwnedStructure (int i)
int getLotsRemaining ()
bool hasLotsRemaining (int lots)
void notifySceneReady ()
int addExperience (const String &xpType, int xp, bool notifyClient)
void removeExperience (const String &xpType, bool notifyClient)
bool hasCappedExperience (const String &xpType)
void addWaypoint (WaypointObject *waypoint, bool checkName, bool notifyClient)
void setWaypoint (WaypointObject *waypoint, bool notifyClient)
void removeWaypoint (unsigned long long waypointID, bool notifyClient)
void setLanguageID (byte language, bool notifyClient)
void addFriend (const String &name, bool notifyClient)
void removeFriend (const String &name, bool notifyClient)
void addIgnore (const String &name, bool notifyClient)
void removeIgnore (const String &name, bool notifyClient)
void setTitle (const String &characterTitle, bool notifyClient)
void setFoodFilling (int newValue, bool notifyClient)
void setDrinkFilling (int newValue, bool notifyClient)
void increaseFactionStanding (const String &factionName, float amount)
void decreaseFactionStanding (const String &factionName, float amount)
float getFactionStanding (const String &factionName)
WaypointObject * getSurveyWaypoint ()
void setScreenPlayData (const String &screenPlay, const String &variable, const String &data)
String getScreenPlayData (const String &screenPlay, const String &variable)
void clearScreenPlayData (const String &screenPlay)
void activateRecovery ()
void doRecovery ()
void disconnect (bool closeClient, bool doLock)
void reload (ZoneClientSession *client)
void setOffline ()
void setLinkDead ()
void setOnline ()
void setLoggingOut ()
void sendBadgesResponseTo (CreatureObject *player)
void logout (bool doLock)
void setJediState (int state, bool notifyClient)
void setLastNpcConvStr (const String &conv)
void setLastNpcConvMessStr (const String &mess)
String getLastNpcConvStr ()
String getLastNpcConvMessStr ()
String getLastNpcConvOption (int idx)
void addLastNpcConvOptions (const String &option)
int countLastNpcConvOptions ()
void clearLastNpcConvOptions ()
void setConversatingCreature (CreatureObject *creature)
unsigned long long getConversatingCreature ()
void setTrainerZoneName (String &zoneName)
String getTrainerZoneName ()
void addPersistentMessage (unsigned long long id)
void dropPersistentMessage (unsigned long long id)
void unloadSpawnedChildren ()
void addToConsentList (const String &name)
bool hasInConsentList (const String &name)
void removeFromConsentList (const String &name)
String getConsentName (int i)
int getConsentListSize ()
void setCommandMessageString (unsigned int actionCRC, String &message)
void removeCommandMessageString (unsigned int actionCRC)
unsigned long long getDeclaredResidence ()
void setDeclaredResidence (BuildingObject *residence)
void setCloningFacility (BuildingObject *cloningfac)
unsigned long long getCloningFacility ()
void notifyOnline ()
void doDigest (int fillingReduction)
bool isDigesting ()
String getSavedTerrainName ()
void setSavedParentID (unsigned long long id)
void setSavedTerrainName (const String &name)
void setForcePower (int fp, bool notifyClient)
void setForcePowerMax (int newValue, bool notifyClient)
void activateForceRegen ()
void setForcePowerRegen (int val)
int getForcePowerRegen ()
unsigned long long getSavedParentID ()
unsigned int getNewSuiBoxID (unsigned int type)
bool hasSuiBox (unsigned int boxID)
SuiBox * getSuiBox (unsigned int boxID)
void removeSuiBox (unsigned int boxID, bool closeWindowToClient)
void removeSuiBoxType (unsigned int windowType)
bool hasSuiBoxWindowType (unsigned int windowType)
void closeSuiWindowType (unsigned int windowType)
SuiBox * getSuiBoxFromWindowType (unsigned int windowType)
void addSuiBox (SuiBox *sui)
void addPermissionGroup (const String &group, bool updateInRangeBuildingPermissions)
void removePermissionGroup (const String &group, bool updateInRangeBuildingPermissions)
bool hasPermissionGroup (const String &group)
bool isFirstIncapacitationExpired ()
void resetIncapacitationCounter ()
void resetFirstIncapacitationTime ()
void updateIncapacitationCounter ()
bool isFirstIncapacitation ()
byte getIncapacitationCounter ()
void addToDuelList (CreatureObject *targetPlayer)
void removeFromDuelList (CreatureObject *targetPlayer)
CreatureObject * getDuelListObject (int index)
bool requestedDuelTo (CreatureObject *targetPlayer)
bool isDuelListEmpty ()
int getDuelListSize ()
UnicodeString getBiography ()
void notifyOffline ()
void setBadge (unsigned int badge)
void awardBadge (unsigned int badge)
void setTeleporting (bool val)
int getNumBadges ()
int getBadgeTypeCount (byte type)
bool hasFriend (const String &name)
bool isIgnoring (const String &name)
void addReverseFriend (const String &name)
void removeReverseFriend (const String &name)
void sendFriendLists ()
bool hasWaypoint (unsigned long long objectID)
bool hasCommandMessageString (unsigned int actionCRC)
unsigned int getCharacterBitmask ()
String getTitle ()
unsigned int getAdminLevel ()
void setAdminLevel (unsigned int adminlvl)
void setBiography (const UnicodeString &bio)
bool isDeveloper ()
bool isCSR ()
bool isPrivileged ()
void setCharacterBitmask (unsigned int bitmask)
bool setCharacterBit (unsigned int bit, bool notifyClient)
bool clearCharacterBit (unsigned int bit, bool notifyClient)
void toggleCharacterBit (unsigned int bit)
bool isAFK ()
int getForcePower ()
int getForcePowerMax ()
DraftSchematic * getSchematic (int i)
int getFoodFilling ()
int getFoodFillingMax ()
int getDrinkFilling ()
int getDrinkFillingMax ()
int getJediState ()
byte getLanguageID ()
bool isTeleporting ()
void addChatRoom (ChatRoom *room)
void removeChatRoom (ChatRoom *room)
void setBankLocation (const String &location)
String getBankLocation ()
int getExperience (const String &xp)
void maximizeExperience ()
void activateMissions ()
String getCommandMessageString (unsigned int actionCRC)
bool hasBadge (unsigned int badge)
void clearDisconnectEvent ()
void clearRecoveryEvent ()
bool isOnline ()
bool isOffline ()
bool isLoading ()
bool isLinkDead ()
bool isLoggingIn ()
bool isLoggingOut ()
void setSkillPoints (int points)
void addSkillPoints (int points)
int getSkillPoints ()
void updateLastValidatedPosition ()
void setSpawnedBlueFrog ()
bool hasSpawnedBlueFrog ()
unsigned int getAccountID ()
unsigned long long getServerMovementTimeDelta ()
void setClientLastMovementStamp (unsigned int stamp)
void updateServerLastMovementStamp ()
void setAccountID (unsigned int id)
int getFactionStatus ()
void setFactionStatus (int status)
unsigned int getClientLastMovementStamp ()
void addHologrindProfession (byte prof)
byte getRaceID ()
void setRaceID (byte race)
void setMaximumLots (byte lots)
byte getMaximumLots ()
String getStarterProfession ()
void setStarterProfession (String &profession)
void addToBountyLockList (unsigned long long playerId)
bool isInBountyLockList (unsigned long long playerId)
void removeFromBountyLockList (unsigned long long playerId, bool immediately)
void removeFromBountyLockListDirectly (unsigned long long playerId)
bool isBountyLocked ()
unsigned long long getPerformanceBuffTarget ()
void setPerformanceBuffTarget (unsigned long long target)
void setDebug (bool value)
bool getDebug ()
float getVisibility ()
void setVisibility (float value)
void addVendor (SceneObject *vendor)
void removeVendor (SceneObject *vendor)
int getVendorCount ()
void destroyObjectFromDatabase (bool destroyContainedObjects)
bool isJedi ()
Public Member Functions inherited from server::zone::objects::intangible::IntangibleObjectAdapter
IntangibleObjectAdapter (IntangibleObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializeTransientMembers ()
bool isIntangibleObject ()
void sendBaselinesTo (SceneObject *player)
void updateStatus (int newStatus, bool notifyClient)
unsigned int getStatus ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectAdapter
SceneObjectAdapter (SceneObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializePrivateData ()
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient, bool allowOverflow)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects)
void destroyObjectFromDatabase (bool destroyContainedObjects)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose)
void sendAttributeListTo (CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void openContainerTo (CreatureObject *player)
void closeContainerTo (CreatureObject *player, bool notify)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
unsigned long long getParentID ()
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
float getWorldPositionX ()
float getWorldPositionY ()
float getWorldPositionZ ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isDecoration ()
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZone (Zone *zone)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
bool containsChildObject (SceneObject *obj)
void createChildObjects ()
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
Detailed Description
Definition at line 1758 of file PlayerObject.h.
Constructor & Destructor Documentation
PlayerObjectAdapter::PlayerObjectAdapter (PlayerObject * impl)
Definition at line 4890 of file PlayerObject.cpp.
Member Function Documentation
void PlayerObjectAdapter::activateForceRegen ()
Definition at line 6251 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::activateMissions ()
Definition at line 6535 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::activateRecovery ()
Definition at line 6071 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addChatRoom (ChatRoom * room)
Definition at line 6511 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::addExperience (const String & xpType, int xp, bool notifyClient)
Definition at line 5987 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addFriend (const String & name, bool notifyClient)
Definition at line 6015 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addHologrindProfession (byte prof)
Definition at line 6635 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addIgnore (const String & name, bool notifyClient)
Definition at line 6023 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addLastNpcConvOptions (const String & option)
Definition at line 6135 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addOwnedStructure (StructureObject * obj)
Definition at line 5955 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addPermissionGroup (const String & group, bool updateInRangeBuildingPermissions)
Definition at line 6303 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addPersistentMessage (unsigned long long id)
Definition at line 6163 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addReverseFriend (const String & name)
Definition at line 6399 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addSkillPoints (int points)
Definition at line 6583 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addSuiBox (SuiBox * sui)
Definition at line 6299 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addToBountyLockList (unsigned long long playerId)
Definition at line 6663 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addToConsentList (const String & name)
Definition at line 6175 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addToDuelList (CreatureObject * targetPlayer)
Definition at line 6339 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addVendor (SceneObject * vendor)
Definition at line 6707 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::addWaypoint (WaypointObject * waypoint, bool checkName, bool notifyClient)
Definition at line 5999 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::awardBadge (unsigned int badge)
Definition at line 6375 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::clearCharacterBit (unsigned int bit, bool notifyClient)
Definition at line 6459 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::clearDisconnectEvent ()
Definition at line 6547 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::clearLastNpcConvOptions ()
Definition at line 6143 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::clearRecoveryEvent ()
Definition at line 6551 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::clearScreenPlayData (const String & screenPlay)
Definition at line 6067 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::closeSuiWindowType (unsigned int windowType)
Definition at line 6291 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::countLastNpcConvOptions ()
Definition at line 6139 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::decreaseFactionStanding (const String & factionName, float amount)
Definition at line 6047 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::destroyObjectFromDatabase (bool destroyContainedObjects)
Definition at line 6719 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::disconnect (bool closeClient, bool doLock)
Definition at line 6079 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::doDigest (int fillingReduction)
Definition at line 6223 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::doRecovery ()
Definition at line 6075 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::dropPersistentMessage (unsigned long long id)
Definition at line 6167 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::finalize ()
Definition at line 5931 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned int PlayerObjectAdapter::getAccountID ()
Definition at line 6603 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned int PlayerObjectAdapter::getAdminLevel ()
Definition at line 6427 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getBadgeTypeCount (byte type)
Definition at line 6387 of file PlayerObject.cpp.
Referenced by invokeMethod().
String PlayerObjectAdapter::getBankLocation ()
Definition at line 6523 of file PlayerObject.cpp.
Referenced by invokeMethod().
UnicodeString PlayerObjectAdapter::getBiography ()
Definition at line 6363 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned int PlayerObjectAdapter::getCharacterBitmask ()
Definition at line 6419 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned int PlayerObjectAdapter::getClientLastMovementStamp ()
Definition at line 6631 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned long long PlayerObjectAdapter::getCloningFacility ()
Definition at line 6215 of file PlayerObject.cpp.
Referenced by invokeMethod().
String PlayerObjectAdapter::getCommandMessageString (unsigned int actionCRC)
Definition at line 6539 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getConsentListSize ()
Definition at line 6191 of file PlayerObject.cpp.
Referenced by invokeMethod().
String PlayerObjectAdapter::getConsentName (int i)
Definition at line 6187 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned long long PlayerObjectAdapter::getConversatingCreature ()
Definition at line 6151 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::getDebug ()
Definition at line 6695 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned long long PlayerObjectAdapter::getDeclaredResidence ()
Definition at line 6203 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getDrinkFilling ()
Definition at line 6491 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getDrinkFillingMax ()
Definition at line 6495 of file PlayerObject.cpp.
Referenced by invokeMethod().
CreatureObject * PlayerObjectAdapter::getDuelListObject (int index)
Definition at line 6347 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getDuelListSize ()
Definition at line 6359 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getExperience (const String & xp)
Definition at line 6527 of file PlayerObject.cpp.
Referenced by invokeMethod().
float PlayerObjectAdapter::getFactionStanding (const String & factionName)
Definition at line 6051 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getFactionStatus ()
Definition at line 6623 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getFoodFilling ()
Definition at line 6483 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getFoodFillingMax ()
Definition at line 6487 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getForcePower ()
Definition at line 6471 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getForcePowerMax ()
Definition at line 6475 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getForcePowerRegen ()
Definition at line 6259 of file PlayerObject.cpp.
Referenced by invokeMethod().
byte PlayerObjectAdapter::getIncapacitationCounter ()
Definition at line 6335 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getJediState ()
Definition at line 6499 of file PlayerObject.cpp.
Referenced by invokeMethod().
byte PlayerObjectAdapter::getLanguageID ()
Definition at line 6503 of file PlayerObject.cpp.
Referenced by invokeMethod().
String PlayerObjectAdapter::getLastNpcConvMessStr ()
Definition at line 6127 of file PlayerObject.cpp.
Referenced by invokeMethod().
String PlayerObjectAdapter::getLastNpcConvOption (int idx)
Definition at line 6131 of file PlayerObject.cpp.
Referenced by invokeMethod().
String PlayerObjectAdapter::getLastNpcConvStr ()
Definition at line 6123 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getLotsRemaining ()
Definition at line 5975 of file PlayerObject.cpp.
Referenced by invokeMethod().
byte PlayerObjectAdapter::getMaximumLots ()
Definition at line 6651 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned int PlayerObjectAdapter::getNewSuiBoxID (unsigned int type)
Definition at line 6267 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getNumBadges ()
Definition at line 6383 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned long long PlayerObjectAdapter::getOwnedStructure (int i)
Definition at line 5971 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned long long PlayerObjectAdapter::getPerformanceBuffTarget ()
Definition at line 6683 of file PlayerObject.cpp.
Referenced by invokeMethod().
byte PlayerObjectAdapter::getRaceID ()
Definition at line 6639 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned long long PlayerObjectAdapter::getSavedParentID ()
Definition at line 6263 of file PlayerObject.cpp.
Referenced by invokeMethod().
String PlayerObjectAdapter::getSavedTerrainName ()
Definition at line 6231 of file PlayerObject.cpp.
Referenced by invokeMethod().
DraftSchematic * PlayerObjectAdapter::getSchematic (int i)
Definition at line 6479 of file PlayerObject.cpp.
Referenced by invokeMethod().
String PlayerObjectAdapter::getScreenPlayData (const String & screenPlay, const String & variable)
Definition at line 6063 of file PlayerObject.cpp.
Referenced by invokeMethod().
unsigned long long PlayerObjectAdapter::getServerMovementTimeDelta ()
Definition at line 6607 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getSkillPoints ()
Definition at line 6587 of file PlayerObject.cpp.
Referenced by invokeMethod().
String PlayerObjectAdapter::getStarterProfession ()
Definition at line 6655 of file PlayerObject.cpp.
Referenced by invokeMethod().
SuiBox * PlayerObjectAdapter::getSuiBox (unsigned int boxID)
Definition at line 6275 of file PlayerObject.cpp.
Referenced by invokeMethod().
SuiBox * PlayerObjectAdapter::getSuiBoxFromWindowType (unsigned int windowType)
Definition at line 6295 of file PlayerObject.cpp.
Referenced by invokeMethod().
WaypointObject * PlayerObjectAdapter::getSurveyWaypoint ()
Definition at line 6055 of file PlayerObject.cpp.
Referenced by invokeMethod().
String PlayerObjectAdapter::getTitle ()
Definition at line 6423 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getTotalOwnedStructureCount ()
Definition at line 5963 of file PlayerObject.cpp.
Referenced by invokeMethod().
String PlayerObjectAdapter::getTrainerZoneName ()
Definition at line 6159 of file PlayerObject.cpp.
Referenced by invokeMethod().
int PlayerObjectAdapter::getVendorCount ()
Definition at line 6715 of file PlayerObject.cpp.
Referenced by invokeMethod().
float PlayerObjectAdapter::getVisibility ()
Definition at line 6699 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::hasBadge (unsigned int badge)
Definition at line 6543 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::hasCappedExperience (const String & xpType)
Definition at line 5995 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::hasCommandMessageString (unsigned int actionCRC)
Definition at line 6415 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::hasFriend (const String & name)
Definition at line 6391 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::hasInConsentList (const String & name)
Definition at line 6179 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::hasLotsRemaining (int lots)
Definition at line 5979 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::hasPermissionGroup (const String & group)
Definition at line 6311 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::hasSpawnedBlueFrog ()
Definition at line 6599 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::hasSuiBox (unsigned int boxID)
Definition at line 6271 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::hasSuiBoxWindowType (unsigned int windowType)
Definition at line 6287 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::hasWaypoint (unsigned long long objectID)
Definition at line 6411 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::increaseFactionStanding (const String & factionName, float amount)
Definition at line 6043 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::initializeTransientMembers ()
Definition at line 5943 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 4893 of file PlayerObject.cpp.
References activateForceRegen(), activateMissions(), activateRecovery(), addChatRoom(), addExperience(), addFriend(), addHologrindProfession(), addIgnore(), addLastNpcConvOptions(), addOwnedStructure(), addPermissionGroup(), addPersistentMessage(), addReverseFriend(), addSkillPoints(), addSuiBox(), addToBountyLockList(), addToConsentList(), addToDuelList(), addVendor(), addWaypoint(), awardBadge(), clearCharacterBit(), clearDisconnectEvent(), clearLastNpcConvOptions(), clearRecoveryEvent(), clearScreenPlayData(), closeSuiWindowType(), countLastNpcConvOptions(), decreaseFactionStanding(), destroyObjectFromDatabase(), disconnect(), doDigest(), doRecovery(), dropPersistentMessage(), finalize(), getAccountID(), getAdminLevel(), getBadgeTypeCount(), getBankLocation(), getBiography(), getCharacterBitmask(), getClientLastMovementStamp(), getCloningFacility(), getCommandMessageString(), getConsentListSize(), getConsentName(), getConversatingCreature(), getDebug(), getDeclaredResidence(), getDrinkFilling(), getDrinkFillingMax(), getDuelListObject(), getDuelListSize(), getExperience(), getFactionStanding(), getFactionStatus(), getFoodFilling(), getFoodFillingMax(), getForcePower(), getForcePowerMax(), getForcePowerRegen(), getIncapacitationCounter(), getJediState(), getLanguageID(), getLastNpcConvMessStr(), getLastNpcConvOption(), getLastNpcConvStr(), getLotsRemaining(), getMaximumLots(), getNewSuiBoxID(), getNumBadges(), getOwnedStructure(), getPerformanceBuffTarget(), getRaceID(), getSavedParentID(), getSavedTerrainName(), getSchematic(), getScreenPlayData(), getServerMovementTimeDelta(), getSkillPoints(), getStarterProfession(), getSuiBox(), getSuiBoxFromWindowType(), getSurveyWaypoint(), getTitle(), getTotalOwnedStructureCount(), getTrainerZoneName(), getVendorCount(), getVisibility(), hasBadge(), hasCappedExperience(), hasCommandMessageString(), hasFriend(), hasInConsentList(), hasLotsRemaining(), hasPermissionGroup(), hasSpawnedBlueFrog(), hasSuiBox(), hasSuiBoxWindowType(), hasWaypoint(), increaseFactionStanding(), initializeTransientMembers(), isAFK(), isBountyLocked(), isCSR(), isDeveloper(), isDigesting(), isDuelListEmpty(), isFirstIncapacitation(), isFirstIncapacitationExpired(), isIgnoring(), isInBountyLockList(), isJedi(), isLinkDead(), isLoading(), isLoggingIn(), isLoggingOut(), isOffline(), isOnline(), isOwnedStructure(), isPrivileged(), isTeleporting(), logout(), maximizeExperience(), notifyLoadFromDatabase(), notifyOffline(), notifyOnline(), notifySceneReady(), reload(), removeChatRoom(), removeCommandMessageString(), removeExperience(), removeFriend(), removeFromBountyLockList(), removeFromBountyLockListDirectly(), removeFromConsentList(), removeFromDuelList(), removeIgnore(), removeOwnedStructure(), removePermissionGroup(), removeReverseFriend(), removeSuiBox(), removeSuiBoxType(), removeVendor(), removeWaypoint(), requestedDuelTo(), resetFirstIncapacitationTime(), resetIncapacitationCounter(), RPC_ACTIVATEFORCEREGEN__, RPC_ACTIVATEMISSIONS__, RPC_ACTIVATERECOVERY__, RPC_ADDCHATROOM__CHATROOM_, RPC_ADDEXPERIENCE__STRING_INT_BOOL_, RPC_ADDFRIEND__STRING_BOOL_, RPC_ADDHOLOGRINDPROFESSION__BYTE_, RPC_ADDIGNORE__STRING_BOOL_, RPC_ADDLASTNPCCONVOPTIONS__STRING_, RPC_ADDOWNEDSTRUCTURE__STRUCTUREOBJECT_, RPC_ADDPERMISSIONGROUP__STRING_BOOL_, RPC_ADDPERSISTENTMESSAGE__LONG_, RPC_ADDREVERSEFRIEND__STRING_, RPC_ADDSKILLPOINTS__INT_, RPC_ADDSUIBOX__SUIBOX_, RPC_ADDTOBOUNTYLOCKLIST__LONG_, RPC_ADDTOCONSENTLIST__STRING_, RPC_ADDTODUELLIST__CREATUREOBJECT_, RPC_ADDVENDOR__SCENEOBJECT_, RPC_ADDWAYPOINT__WAYPOINTOBJECT_BOOL_BOOL_, RPC_AWARDBADGE__INT_, RPC_CLEARCHARACTERBIT__INT_BOOL_, RPC_CLEARDISCONNECTEVENT__, RPC_CLEARLASTNPCCONVOPTIONS__, RPC_CLEARRECOVERYEVENT__, RPC_CLEARSCREENPLAYDATA__STRING_, RPC_CLOSESUIWINDOWTYPE__INT_, RPC_COUNTLASTNPCCONVOPTIONS__, RPC_DECREASEFACTIONSTANDING__STRING_FLOAT_, RPC_DESTROYOBJECTFROMDATABASE__BOOL_, RPC_DISCONNECT__BOOL_BOOL_, RPC_DODIGEST__INT_, RPC_DORECOVERY__, RPC_DROPPERSISTENTMESSAGE__LONG_, RPC_FINALIZE__, RPC_GETACCOUNTID__, RPC_GETADMINLEVEL__, RPC_GETBADGETYPECOUNT__BYTE_, RPC_GETBANKLOCATION__, RPC_GETBIOGRAPHY__, RPC_GETCHARACTERBITMASK__, RPC_GETCLIENTLASTMOVEMENTSTAMP__, RPC_GETCLONINGFACILITY__, RPC_GETCOMMANDMESSAGESTRING__INT_, RPC_GETCONSENTLISTSIZE__, RPC_GETCONSENTNAME__INT_, RPC_GETCONVERSATINGCREATURE__, RPC_GETDEBUG__, RPC_GETDECLAREDRESIDENCE__, RPC_GETDRINKFILLING__, RPC_GETDRINKFILLINGMAX__, RPC_GETDUELLISTOBJECT__INT_, RPC_GETDUELLISTSIZE__, RPC_GETEXPERIENCE__STRING_, RPC_GETFACTIONSTANDING__STRING_, RPC_GETFACTIONSTATUS__, RPC_GETFOODFILLING__, RPC_GETFOODFILLINGMAX__, RPC_GETFORCEPOWER__, RPC_GETFORCEPOWERMAX__, RPC_GETFORCEPOWERREGEN__, RPC_GETINCAPACITATIONCOUNTER__, RPC_GETJEDISTATE__, RPC_GETLANGUAGEID__, RPC_GETLASTNPCCONVMESSSTR__, RPC_GETLASTNPCCONVOPTION__INT_, RPC_GETLASTNPCCONVSTR__, RPC_GETLOTSREMAINING__, RPC_GETMAXIMUMLOTS__, RPC_GETNEWSUIBOXID__INT_, RPC_GETNUMBADGES__, RPC_GETOWNEDSTRUCTURE__INT_, RPC_GETPERFORMANCEBUFFTARGET__, RPC_GETRACEID__, RPC_GETSAVEDPARENTID__, RPC_GETSAVEDTERRAINNAME__, RPC_GETSCHEMATIC__INT_, RPC_GETSCREENPLAYDATA__STRING_STRING_, RPC_GETSERVERMOVEMENTTIMEDELTA__, RPC_GETSKILLPOINTS__, RPC_GETSTARTERPROFESSION__, RPC_GETSUIBOX__INT_, RPC_GETSUIBOXFROMWINDOWTYPE__INT_, RPC_GETSURVEYWAYPOINT__, RPC_GETTITLE__, RPC_GETTOTALOWNEDSTRUCTURECOUNT__, RPC_GETTRAINERZONENAME__, RPC_GETVENDORCOUNT__, RPC_GETVISIBILITY__, RPC_HASBADGE__INT_, RPC_HASCAPPEDEXPERIENCE__STRING_, RPC_HASCOMMANDMESSAGESTRING__INT_, RPC_HASFRIEND__STRING_, RPC_HASINCONSENTLIST__STRING_, RPC_HASLOTSREMAINING__INT_, RPC_HASPERMISSIONGROUP__STRING_, RPC_HASSPAWNEDBLUEFROG__, RPC_HASSUIBOX__INT_, RPC_HASSUIBOXWINDOWTYPE__INT_, RPC_HASWAYPOINT__LONG_, RPC_INCREASEFACTIONSTANDING__STRING_FLOAT_, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_ISAFK__, RPC_ISBOUNTYLOCKED__, RPC_ISCSR__, RPC_ISDEVELOPER__, RPC_ISDIGESTING__, RPC_ISDUELLISTEMPTY__, RPC_ISFIRSTINCAPACITATION__, RPC_ISFIRSTINCAPACITATIONEXPIRED__, RPC_ISIGNORING__STRING_, RPC_ISINBOUNTYLOCKLIST__LONG_, RPC_ISJEDI__, RPC_ISLINKDEAD__, RPC_ISLOADING__, RPC_ISLOGGINGIN__, RPC_ISLOGGINGOUT__, RPC_ISOFFLINE__, RPC_ISONLINE__, RPC_ISOWNEDSTRUCTURE__STRUCTUREOBJECT_, RPC_ISPRIVILEGED__, RPC_ISTELEPORTING__, RPC_LOGOUT__BOOL_, RPC_MAXIMIZEEXPERIENCE__, RPC_NOTIFYLOADFROMDATABASE__, RPC_NOTIFYOFFLINE__, RPC_NOTIFYONLINE__, RPC_NOTIFYSCENEREADY__, RPC_RELOAD__ZONECLIENTSESSION_, RPC_REMOVECHATROOM__CHATROOM_, RPC_REMOVECOMMANDMESSAGESTRING__INT_, RPC_REMOVEEXPERIENCE__STRING_BOOL_, RPC_REMOVEFRIEND__STRING_BOOL_, RPC_REMOVEFROMBOUNTYLOCKLIST__LONG_BOOL_, RPC_REMOVEFROMBOUNTYLOCKLISTDIRECTLY__LONG_, RPC_REMOVEFROMCONSENTLIST__STRING_, RPC_REMOVEFROMDUELLIST__CREATUREOBJECT_, RPC_REMOVEIGNORE__STRING_BOOL_, RPC_REMOVEOWNEDSTRUCTURE__STRUCTUREOBJECT_, RPC_REMOVEPERMISSIONGROUP__STRING_BOOL_, RPC_REMOVEREVERSEFRIEND__STRING_, RPC_REMOVESUIBOX__INT_BOOL_, RPC_REMOVESUIBOXTYPE__INT_, RPC_REMOVEVENDOR__SCENEOBJECT_, RPC_REMOVEWAYPOINT__LONG_BOOL_, RPC_REQUESTEDDUELTO__CREATUREOBJECT_, RPC_RESETFIRSTINCAPACITATIONTIME__, RPC_RESETINCAPACITATIONCOUNTER__, RPC_SENDBADGESRESPONSETO__CREATUREOBJECT_, RPC_SENDBASELINESTO__SCENEOBJECT_, RPC_SENDFRIENDLISTS__, RPC_SENDMESSAGE__BASEPACKET_, RPC_SETACCOUNTID__INT_, RPC_SETADMINLEVEL__INT_, RPC_SETBADGE__INT_, RPC_SETBANKLOCATION__STRING_, RPC_SETBIOGRAPHY__UNICODESTRING_, RPC_SETCHARACTERBIT__INT_BOOL_, RPC_SETCHARACTERBITMASK__INT_, RPC_SETCLIENTLASTMOVEMENTSTAMP__INT_, RPC_SETCLONINGFACILITY__BUILDINGOBJECT_, RPC_SETCOMMANDMESSAGESTRING__INT_STRING_, RPC_SETCONVERSATINGCREATURE__CREATUREOBJECT_, RPC_SETDEBUG__BOOL_, RPC_SETDECLAREDRESIDENCE__BUILDINGOBJECT_, RPC_SETDRINKFILLING__INT_BOOL_, RPC_SETFACTIONSTATUS__INT_, RPC_SETFOODFILLING__INT_BOOL_, RPC_SETFORCEPOWER__INT_BOOL_, RPC_SETFORCEPOWERMAX__INT_BOOL_, RPC_SETFORCEPOWERREGEN__INT_, RPC_SETJEDISTATE__INT_BOOL_, RPC_SETLANGUAGEID__BYTE_BOOL_, RPC_SETLASTNPCCONVMESSSTR__STRING_, RPC_SETLASTNPCCONVSTR__STRING_, RPC_SETLINKDEAD__, RPC_SETLOGGINGOUT__, RPC_SETMAXIMUMLOTS__BYTE_, RPC_SETOFFLINE__, RPC_SETONLINE__, RPC_SETPERFORMANCEBUFFTARGET__LONG_, RPC_SETRACEID__BYTE_, RPC_SETSAVEDPARENTID__LONG_, RPC_SETSAVEDTERRAINNAME__STRING_, RPC_SETSCREENPLAYDATA__STRING_STRING_STRING_, RPC_SETSKILLPOINTS__INT_, RPC_SETSPAWNEDBLUEFROG__, RPC_SETSTARTERPROFESSION__STRING_, RPC_SETTELEPORTING__BOOL_, RPC_SETTITLE__STRING_BOOL_, RPC_SETTRAINERZONENAME__STRING_, RPC_SETVISIBILITY__FLOAT_, RPC_SETWAYPOINT__WAYPOINTOBJECT_BOOL_, RPC_TOGGLECHARACTERBIT__INT_, RPC_UNLOAD__, RPC_UNLOADSPAWNEDCHILDREN__, RPC_UPDATEINCAPACITATIONCOUNTER__, RPC_UPDATELASTVALIDATEDPOSITION__, RPC_UPDATESERVERLASTMOVEMENTSTAMP__, sendBadgesResponseTo(), sendBaselinesTo(), sendFriendLists(), sendMessage(), setAccountID(), setAdminLevel(), setBadge(), setBankLocation(), setBiography(), setCharacterBit(), setCharacterBitmask(), setClientLastMovementStamp(), setCloningFacility(), setCommandMessageString(), setConversatingCreature(), setDebug(), setDeclaredResidence(), setDrinkFilling(), setFactionStatus(), setFoodFilling(), setForcePower(), setForcePowerMax(), setForcePowerRegen(), setJediState(), setLanguageID(), setLastNpcConvMessStr(), setLastNpcConvStr(), setLinkDead(), setLoggingOut(), setMaximumLots(), setOffline(), setOnline(), setPerformanceBuffTarget(), setRaceID(), setSavedParentID(), setSavedTerrainName(), setScreenPlayData(), setSkillPoints(), setSpawnedBlueFrog(), setStarterProfession(), setTeleporting(), setTitle(), setTrainerZoneName(), setVisibility(), setWaypoint(), toggleCharacterBit(), unload(), unloadSpawnedChildren(), updateIncapacitationCounter(), updateLastValidatedPosition(), and updateServerLastMovementStamp().
bool PlayerObjectAdapter::isAFK ()
Definition at line 6467 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isBountyLocked ()
Definition at line 6679 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isCSR ()
Definition at line 6443 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isDeveloper ()
Definition at line 6439 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isDigesting ()
Definition at line 6227 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isDuelListEmpty ()
Definition at line 6355 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isFirstIncapacitation ()
Definition at line 6331 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isFirstIncapacitationExpired ()
Definition at line 6315 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isIgnoring (const String & name)
Definition at line 6395 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isInBountyLockList (unsigned long long playerId)
Definition at line 6667 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isJedi ()
Definition at line 6723 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isLinkDead ()
Definition at line 6567 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isLoading ()
Definition at line 6563 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isLoggingIn ()
Definition at line 6571 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isLoggingOut ()
Definition at line 6575 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isOffline ()
Definition at line 6559 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isOnline ()
Definition at line 6555 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isOwnedStructure (StructureObject * obj)
Definition at line 5967 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isPrivileged ()
Definition at line 6447 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::isTeleporting ()
Definition at line 6507 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::logout (bool doLock)
Definition at line 6107 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::maximizeExperience ()
Definition at line 6531 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::notifyLoadFromDatabase ()
Definition at line 5935 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::notifyOffline ()
Definition at line 6367 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::notifyOnline ()
Definition at line 6219 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::notifySceneReady ()
Definition at line 5983 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::reload (ZoneClientSession * client)
Definition at line 6083 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeChatRoom (ChatRoom * room)
Definition at line 6515 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeCommandMessageString (unsigned int actionCRC)
Definition at line 6199 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeExperience (const String & xpType, bool notifyClient)
Definition at line 5991 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeFriend (const String & name, bool notifyClient)
Definition at line 6019 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeFromBountyLockList (unsigned long long playerId, bool immediately)
Definition at line 6671 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeFromBountyLockListDirectly (unsigned long long playerId)
Definition at line 6675 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeFromConsentList (const String & name)
Definition at line 6183 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeFromDuelList (CreatureObject * targetPlayer)
Definition at line 6343 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeIgnore (const String & name, bool notifyClient)
Definition at line 6027 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeOwnedStructure (StructureObject * obj)
Definition at line 5959 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removePermissionGroup (const String & group, bool updateInRangeBuildingPermissions)
Definition at line 6307 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeReverseFriend (const String & name)
Definition at line 6403 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeSuiBox (unsigned int boxID, bool closeWindowToClient)
Definition at line 6279 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeSuiBoxType (unsigned int windowType)
Definition at line 6283 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeVendor (SceneObject * vendor)
Definition at line 6711 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::removeWaypoint (unsigned long long waypointID, bool notifyClient)
Definition at line 6007 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::requestedDuelTo (CreatureObject * targetPlayer)
Definition at line 6351 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::resetFirstIncapacitationTime ()
Definition at line 6323 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::resetIncapacitationCounter ()
Definition at line 6319 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::sendBadgesResponseTo (CreatureObject * player)
Definition at line 6103 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::sendBaselinesTo (SceneObject * player)
Definition at line 5947 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::sendFriendLists ()
Definition at line 6407 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::sendMessage (BasePacket * msg)
Definition at line 5951 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setAccountID (unsigned int id)
Definition at line 6619 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setAdminLevel (unsigned int adminlvl)
Definition at line 6431 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setBadge (unsigned int badge)
Definition at line 6371 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setBankLocation (const String & location)
Definition at line 6519 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setBiography (const UnicodeString & bio)
Definition at line 6435 of file PlayerObject.cpp.
Referenced by invokeMethod().
bool PlayerObjectAdapter::setCharacterBit (unsigned int bit, bool notifyClient)
Definition at line 6455 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setCharacterBitmask (unsigned int bitmask)
Definition at line 6451 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setClientLastMovementStamp (unsigned int stamp)
Definition at line 6611 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setCloningFacility (BuildingObject * cloningfac)
Definition at line 6211 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setCommandMessageString (unsigned int actionCRC, String & message)
Definition at line 6195 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setConversatingCreature (CreatureObject * creature)
Definition at line 6147 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setDebug (bool value)
Definition at line 6691 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setDeclaredResidence (BuildingObject * residence)
Definition at line 6207 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setDrinkFilling (int newValue, bool notifyClient)
Definition at line 6039 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setFactionStatus (int status)
Definition at line 6627 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setFoodFilling (int newValue, bool notifyClient)
Definition at line 6035 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setForcePower (int fp, bool notifyClient)
Definition at line 6243 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setForcePowerMax (int newValue, bool notifyClient)
Definition at line 6247 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setForcePowerRegen (int val)
Definition at line 6255 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setJediState (int state, bool notifyClient)
Definition at line 6111 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setLanguageID (byte language, bool notifyClient)
Definition at line 6011 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setLastNpcConvMessStr (const String & mess)
Definition at line 6119 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setLastNpcConvStr (const String & conv)
Definition at line 6115 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setLinkDead ()
Definition at line 6091 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setLoggingOut ()
Definition at line 6099 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setMaximumLots (byte lots)
Definition at line 6647 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setOffline ()
Definition at line 6087 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setOnline ()
Definition at line 6095 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setPerformanceBuffTarget (unsigned long long target)
Definition at line 6687 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setRaceID (byte race)
Definition at line 6643 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setSavedParentID (unsigned long long id)
Definition at line 6235 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setSavedTerrainName (const String & name)
Definition at line 6239 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setScreenPlayData (const String & screenPlay, const String & variable, const String & data)
Definition at line 6059 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setSkillPoints (int points)
Definition at line 6579 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setSpawnedBlueFrog ()
Definition at line 6595 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setStarterProfession (String & profession)
Definition at line 6659 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setTeleporting (bool val)
Definition at line 6379 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setTitle (const String & characterTitle, bool notifyClient)
Definition at line 6031 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setTrainerZoneName (String & zoneName)
Definition at line 6155 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setVisibility (float value)
Definition at line 6703 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::setWaypoint (WaypointObject * waypoint, bool notifyClient)
Definition at line 6003 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::toggleCharacterBit (unsigned int bit)
Definition at line 6463 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::unload ()
Definition at line 5939 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::unloadSpawnedChildren ()
Definition at line 6171 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::updateIncapacitationCounter ()
Definition at line 6327 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::updateLastValidatedPosition ()
Definition at line 6591 of file PlayerObject.cpp.
Referenced by invokeMethod().
void PlayerObjectAdapter::updateServerLastMovementStamp ()
Definition at line 6615 of file PlayerObject.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/PlayerObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/PlayerObject.cpp