Core3: server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation Class Reference
server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation Class Reference
#include <StructureSetAccessFeeSession.h>
Public Member Functions
StructureSetAccessFeeSessionImplementation (CreatureObject *play, BuildingObject *struc)
StructureSetAccessFeeSessionImplementation (DummyConstructorParameter *param)
int initializeSession ()
int cancelSession ()
int clearSession ()
void promptSetAccessFee ()
void setAccessFee (const int fee)
void promptSetAccessDuration ()
void setAccessDuration (const int duration)
operator const StructureSetAccessFeeSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< StructureSetAccessFeeSession * > _this
Protected Member Functions
virtual ~StructureSetAccessFeeSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference< PlayerObject * > playerGhost
ManagedReference
< CreatureObject * > player
ManagedReference
< BuildingObject * > structure
ManagedReference< SuiInputBox * > feeAmountBox
ManagedReference< SuiInputBox * > durationBox
int accessFee
Friends
class StructureSetAccessFeeSession
Detailed Description
Definition at line 121 of file StructureSetAccessFeeSession.h.
Constructor & Destructor Documentation
StructureSetAccessFeeSessionImplementation::StructureSetAccessFeeSessionImplementation (CreatureObject * play, BuildingObject * struc)
Definition at line 332 of file StructureSetAccessFeeSession.cpp.
References _initializeImplementation(), accessFee, durationBox, feeAmountBox, player, playerGhost, and structure.
StructureSetAccessFeeSessionImplementation::StructureSetAccessFeeSessionImplementation (DummyConstructorParameter * param)
Definition at line 146 of file StructureSetAccessFeeSession.cpp.
References _initializeImplementation().
StructureSetAccessFeeSessionImplementation::~StructureSetAccessFeeSessionImplementation () protected virtual
Definition at line 151 of file StructureSetAccessFeeSession.cpp.
Member Function Documentation
DistributedObjectStub * StructureSetAccessFeeSessionImplementation::_getStub ()
Definition at line 171 of file StructureSetAccessFeeSession.cpp.
References _this.
void StructureSetAccessFeeSessionImplementation::_initializeImplementation () protected
Definition at line 158 of file StructureSetAccessFeeSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by StructureSetAccessFeeSessionImplementation().
void StructureSetAccessFeeSessionImplementation::_serializationHelperMethod () protected
Definition at line 207 of file StructureSetAccessFeeSession.cpp.
Referenced by _initializeImplementation().
void StructureSetAccessFeeSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 166 of file StructureSetAccessFeeSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::StructureSetAccessFeeSession::StructureSetAccessFeeSession().
int StructureSetAccessFeeSessionImplementation::cancelSession ()
Definition at line 352 of file StructureSetAccessFeeSession.cpp.
References clearSession(), player, and SessionFacadeType::SETSTRUCTUREACCESSFEE.
Referenced by server::zone::objects::player::sessions::StructureSetAccessFeeSession::cancelSession(), initializeSession(), promptSetAccessDuration(), promptSetAccessFee(), and setAccessDuration().
int StructureSetAccessFeeSessionImplementation::clearSession ()
Definition at line 38 of file StructureSetAccessFeeSessionImplementation.cpp.
References durationBox, feeAmountBox, player, and playerGhost.
Referenced by cancelSession(), and server::zone::objects::player::sessions::StructureSetAccessFeeSession::clearSession().
void StructureSetAccessFeeSessionImplementation::finalize () protected
Definition at line 155 of file StructureSetAccessFeeSession.cpp.
int StructureSetAccessFeeSessionImplementation::initializeSession ()
Definition at line 17 of file StructureSetAccessFeeSessionImplementation.cpp.
References cancelSession(), player, and structure.
Referenced by server::zone::objects::player::sessions::StructureSetAccessFeeSession::initializeSession().
void StructureSetAccessFeeSessionImplementation::lock (bool doLock = true) protected
Definition at line 179 of file StructureSetAccessFeeSession.cpp.
References _this.
void StructureSetAccessFeeSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 183 of file StructureSetAccessFeeSession.cpp.
References _this.
StructureSetAccessFeeSessionImplementation::operator const StructureSetAccessFeeSession * ()
Definition at line 175 of file StructureSetAccessFeeSession.cpp.
void StructureSetAccessFeeSessionImplementation::promptSetAccessDuration ()
Definition at line 89 of file StructureSetAccessFeeSessionImplementation.cpp.
References cancelSession(), durationBox, player, playerGhost, structure, and SuiWindowType::STRUCTURE_SET_ACCESS_DURATION.
Referenced by server::zone::objects::player::sessions::StructureSetAccessFeeSession::promptSetAccessDuration(), and setAccessFee().
void StructureSetAccessFeeSessionImplementation::promptSetAccessFee ()
Definition at line 59 of file StructureSetAccessFeeSessionImplementation.cpp.
References cancelSession(), feeAmountBox, player, playerGhost, structure, and SuiWindowType::STRUCTURE_SET_ACCESS_FEE.
Referenced by server::zone::objects::player::sessions::StructureSetAccessFeeSession::promptSetAccessFee().
void StructureSetAccessFeeSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 214 of file StructureSetAccessFeeSession.cpp.
References readObjectMember().
bool StructureSetAccessFeeSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 233 of file StructureSetAccessFeeSession.cpp.
References accessFee, durationBox, feeAmountBox, player, playerGhost, and structure.
Referenced by readObject().
void StructureSetAccessFeeSessionImplementation::rlock (bool doLock = true) protected
Definition at line 187 of file StructureSetAccessFeeSession.cpp.
References _this.
void StructureSetAccessFeeSessionImplementation::runlock (bool doLock = true) protected
Definition at line 203 of file StructureSetAccessFeeSession.cpp.
References _this.
void StructureSetAccessFeeSessionImplementation::setAccessDuration (const int duration)
Definition at line 113 of file StructureSetAccessFeeSessionImplementation.cpp.
References accessFee, cancelSession(), player, and structure.
Referenced by server::zone::objects::player::sessions::StructureSetAccessFeeSession::setAccessDuration().
void StructureSetAccessFeeSessionImplementation::setAccessFee (const int fee)
Definition at line 84 of file StructureSetAccessFeeSessionImplementation.cpp.
References accessFee, and promptSetAccessDuration().
Referenced by server::zone::objects::player::sessions::StructureSetAccessFeeSession::setAccessFee().
void StructureSetAccessFeeSessionImplementation::unlock (bool doLock = true) protected
Definition at line 199 of file StructureSetAccessFeeSession.cpp.
References _this.
void StructureSetAccessFeeSessionImplementation::wlock (bool doLock = true) protected
Definition at line 191 of file StructureSetAccessFeeSession.cpp.
References _this.
void StructureSetAccessFeeSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 195 of file StructureSetAccessFeeSession.cpp.
References _this.
void StructureSetAccessFeeSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 267 of file StructureSetAccessFeeSession.cpp.
References writeObjectMembers().
int StructureSetAccessFeeSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 274 of file StructureSetAccessFeeSession.cpp.
References accessFee, durationBox, feeAmountBox, player, playerGhost, and structure.
Referenced by writeObject().
Friends And Related Function Documentation
friend class StructureSetAccessFeeSession friend
Definition at line 188 of file StructureSetAccessFeeSession.h.
Member Data Documentation
WeakReference<StructureSetAccessFeeSession*> server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::_this
Definition at line 154 of file StructureSetAccessFeeSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
int server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::accessFee protected
Definition at line 133 of file StructureSetAccessFeeSession.h.
Referenced by readObjectMember(), setAccessDuration(), setAccessFee(), StructureSetAccessFeeSessionImplementation(), and writeObjectMembers().
ManagedReference<SuiInputBox* > server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::durationBox protected
Definition at line 131 of file StructureSetAccessFeeSession.h.
Referenced by clearSession(), promptSetAccessDuration(), readObjectMember(), StructureSetAccessFeeSessionImplementation(), and writeObjectMembers().
ManagedReference<SuiInputBox* > server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::feeAmountBox protected
Definition at line 129 of file StructureSetAccessFeeSession.h.
Referenced by clearSession(), promptSetAccessFee(), readObjectMember(), StructureSetAccessFeeSessionImplementation(), and writeObjectMembers().
ManagedReference<CreatureObject* > server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::player protected
Definition at line 125 of file StructureSetAccessFeeSession.h.
Referenced by cancelSession(), clearSession(), initializeSession(), promptSetAccessDuration(), promptSetAccessFee(), readObjectMember(), setAccessDuration(), StructureSetAccessFeeSessionImplementation(), and writeObjectMembers().
ManagedReference<PlayerObject* > server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::playerGhost protected
Definition at line 123 of file StructureSetAccessFeeSession.h.
Referenced by clearSession(), promptSetAccessDuration(), promptSetAccessFee(), readObjectMember(), StructureSetAccessFeeSessionImplementation(), and writeObjectMembers().
ManagedReference<BuildingObject* > server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::structure protected
Definition at line 127 of file StructureSetAccessFeeSession.h.
Referenced by initializeSession(), promptSetAccessDuration(), promptSetAccessFee(), readObjectMember(), setAccessDuration(), StructureSetAccessFeeSessionImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureSetAccessFeeSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureSetAccessFeeSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureSetAccessFeeSessionImplementation.cpp