Core3: Zone Class Reference
Zone Class Reference
#include <Zone.h>
Public Member Functions
Zone (int instance, uint64 characterObjectID, uint32 account, uint32 session)
~Zone ()
void run ()
void disconnect ()
void sceneStarted ()
void follow (const String &name)
void stopFollow ()
void lurk ()
bool doCommand (const String &command, const String &arguments)
void insertPlayer ()
void insertPlayer (PlayerCreature *player)
PlayerCreature * getSelfPlayer ()
bool isSelfPlayer (SceneObject *pl)
bool hasSelfPlayer ()
SceneObject * getObject (uint64 objid)
void setCharacterID (uint64 val)
uint64 getCharacterID ()
ZoneClient * getZoneClient ()
ObjectManager * getObjectManager ()
ObjectController * getObjectController ()
Vector< PlayerCreature * > * getNotInitiatedPlayers ()
bool isStarted ()
Static Public Attributes
static int createdChar = 0
Private Attributes
uint64 characterID
uint32 accountID
uint32 sessionID
Reference< ZoneClient * > client
ZoneClientThread * clientThread
Reference< PlayerCreature * > player
ObjectController * objectController
Condition characterCreatedCondition
Vector< PlayerCreature * > playerArray
ObjectManager * objectManager
int instance
Time startTime
bool started
Detailed Description
Definition at line 60 of file Zone.h.
Constructor & Destructor Documentation
Zone::Zone (int instance, uint64 characterObjectID, uint32 account, uint32 session)
Definition at line 19 of file Zone.cpp.
References accountID, characterID, client, clientThread, instance, objectController, objectManager, player, sessionID, and ObjectManager::setZone().
Zone::~Zone ()
Definition at line 38 of file Zone.cpp.
References clientThread, objectManager, and ZoneClientThread::stop().
Member Function Documentation
void Zone::disconnect ()
Definition at line 119 of file Zone.cpp.
References client.
Referenced by ClientCore::logoutCharacter(), and ClientCore::run().
bool Zone::doCommand (const String & command, const String & arguments)
Definition at line 161 of file Zone.cpp.
References ObjectController::doCommand(), and objectController.
void Zone::follow (const String & name)
Definition at line 129 of file Zone.cpp.
References client, ObjectManager::getObject(), getSelfPlayer(), objectManager, player, and PlayerCreature::setFollow().
uint64 Zone::getCharacterID () inline
Definition at line 142 of file Zone.h.
References characterID.
Referenced by ZonePacketHandler::handleClientPermissionsMessage().
Vector<PlayerCreature*>* Zone::getNotInitiatedPlayers () inline
Definition at line 158 of file Zone.h.
References playerArray.
SceneObject * Zone::getObject (uint64 objid)
Definition at line 102 of file Zone.cpp.
References ObjectManager::getObject(), and objectManager.
Referenced by ZonePacketHandler::handleBaselineMessage(), ZonePacketHandler::handleObjectControllerMessage(), ObjectController::handleSpatialChat(), ZonePacketHandler::handleUpdateContainmentMessage(), and ZonePacketHandler::handleUpdateTransformMessage().
ObjectController* Zone::getObjectController () inline
Definition at line 154 of file Zone.h.
References objectController.
Referenced by ZonePacketHandler::handleObjectControllerMessage().
ObjectManager* Zone::getObjectManager () inline
Definition at line 150 of file Zone.h.
References objectManager.
Referenced by ZonePacketHandler::handleSceneObejctDestroyMessage(), and ZonePacketHandler::handleSceneObjectCreateMessage().
PlayerCreature * Zone::getSelfPlayer ()
Definition at line 115 of file Zone.cpp.
References characterID, ObjectManager::getObject(), and objectManager.
Referenced by ObjectController::doEnqueueCommand(), ObjectController::doSayCommand(), follow(), ZonePacketHandler::handleUpdateTransformMessage(), lurk(), and stopFollow().
ZoneClient* Zone::getZoneClient () inline
Definition at line 146 of file Zone.h.
References client.
Referenced by ZonePacketHandler::handleSceneObjectCreateMessage().
bool Zone::hasSelfPlayer () inline
Definition at line 127 of file Zone.h.
References characterID.
void Zone::insertPlayer ()
Definition at line 82 of file Zone.cpp.
References player.
void Zone::insertPlayer (PlayerCreature * player)
Definition at line 86 of file Zone.cpp.
bool Zone::isSelfPlayer (SceneObject * pl) inline
Definition at line 120 of file Zone.h.
References characterID, and SceneObject::getObjectID().
Referenced by ZonePacketHandler::handleSceneObjectCreateMessage().
bool Zone::isStarted () inline
Definition at line 162 of file Zone.h.
References started.
Referenced by ClientCore::logoutCharacter().
void Zone::lurk ()
Definition at line 155 of file Zone.cpp.
References getSelfPlayer(), and player.
void Zone::run ()
Definition at line 45 of file Zone.cpp.
References accountID, client, clientThread, instance, sessionID, started, and startTime.
void Zone::sceneStarted ()
Definition at line 125 of file Zone.cpp.
References client, and startTime.
Referenced by ZonePacketHandler::handleCmdStartScene().
void Zone::setCharacterID (uint64 val) inline
Definition at line 133 of file Zone.h.
References characterCreatedCondition, and characterID.
Referenced by ZonePacketHandler::handleCharacterCreateSucessMessage(), and ZonePacketHandler::handleCmdStartScene().
void Zone::stopFollow ()
Definition at line 146 of file Zone.cpp.
References client, getSelfPlayer(), player, and PlayerCreature::setFollow().
Member Data Documentation
uint32 Zone::accountID private
Definition at line 66 of file Zone.h.
Referenced by run(), and Zone().
Condition Zone::characterCreatedCondition private
Definition at line 76 of file Zone.h.
Referenced by setCharacterID().
uint64 Zone::characterID private
Definition at line 65 of file Zone.h.
Referenced by getCharacterID(), getSelfPlayer(), hasSelfPlayer(), isSelfPlayer(), setCharacterID(), and Zone().
Reference<ZoneClient*> Zone::client private
Definition at line 69 of file Zone.h.
Referenced by disconnect(), follow(), getZoneClient(), run(), sceneStarted(), stopFollow(), and Zone().
ZoneClientThread* Zone::clientThread private
Definition at line 70 of file Zone.h.
Referenced by run(), Zone(), and ~Zone().
int Zone::createdChar = 0 static
Definition at line 91 of file Zone.h.
int Zone::instance private
Definition at line 82 of file Zone.h.
Referenced by run(), and Zone().
ObjectController* Zone::objectController private
Definition at line 74 of file Zone.h.
Referenced by doCommand(), getObjectController(), and Zone().
ObjectManager* Zone::objectManager private
Definition at line 80 of file Zone.h.
Referenced by follow(), getObject(), getObjectManager(), getSelfPlayer(), Zone(), and ~Zone().
Reference<PlayerCreature*> Zone::player private
Definition at line 72 of file Zone.h.
Referenced by follow(), insertPlayer(), lurk(), stopFollow(), and Zone().
Vector<PlayerCreature*> Zone::playerArray private
Definition at line 78 of file Zone.h.
Referenced by getNotInitiatedPlayers().
uint32 Zone::sessionID private
Definition at line 67 of file Zone.h.
Referenced by run(), and Zone().
bool Zone::started private
Definition at line 85 of file Zone.h.
Referenced by isStarted(), and run().
Time Zone::startTime private
Definition at line 84 of file Zone.h.
Referenced by run(), and sceneStarted().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/zone/Zone.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/zone/Zone.cpp