Core3: TreeDataBlock Class Reference
TreeDataBlock Class Reference
#include <TreeDataBlock.h>
Public Member Functions
TreeDataBlock ()
TreeDataBlock (const TreeDataBlock &tdb)
TreeDataBlock & operator= (const TreeDataBlock &tdb)
void read (FileInputStream *fileStream, int offset)
byte * uncompress (FileInputStream *fileStream)
void compress ()
void setCompressionType (uint32 value)
void setCompressedSize (uint32 value)
void setUncompressedSize (uint32 value)
uint32 getCompressedSize ()
uint32 getUncompressedSize ()
Static Public Attributes
static const int SIZE = 6 * sizeof(int)
Private Attributes
uint32 compressionType
unsigned long compressedSize
unsigned long uncompressedSize
Detailed Description
Definition at line 17 of file TreeDataBlock.h.
Constructor & Destructor Documentation
TreeDataBlock::TreeDataBlock () inline
Definition at line 29 of file TreeDataBlock.h.
References compressedSize, compressionType, and uncompressedSize.
TreeDataBlock::TreeDataBlock (const TreeDataBlock & tdb) inline
Definition at line 35 of file TreeDataBlock.h.
References compressedSize, compressionType, and uncompressedSize.
Member Function Documentation
void TreeDataBlock::compress () inline
Definition at line 84 of file TreeDataBlock.h.
uint32 TreeDataBlock::getCompressedSize () inline
Definition at line 100 of file TreeDataBlock.h.
References compressedSize.
uint32 TreeDataBlock::getUncompressedSize () inline
Definition at line 104 of file TreeDataBlock.h.
References uncompressedSize.
TreeDataBlock& TreeDataBlock::operator= (const TreeDataBlock & tdb) inline
Definition at line 41 of file TreeDataBlock.h.
References compressedSize, compressionType, and uncompressedSize.
void TreeDataBlock::read (FileInputStream * fileStream, int offset) inline
Definition at line 52 of file TreeDataBlock.h.
void TreeDataBlock::setCompressedSize (uint32 value) inline
Definition at line 92 of file TreeDataBlock.h.
References compressedSize.
Referenced by TreeFileRecord::getBytes(), and TreeFile::readHeader().
void TreeDataBlock::setCompressionType (uint32 value) inline
Definition at line 88 of file TreeDataBlock.h.
References compressionType.
Referenced by TreeFileRecord::getBytes(), and TreeFile::readHeader().
void TreeDataBlock::setUncompressedSize (uint32 value) inline
Definition at line 96 of file TreeDataBlock.h.
References uncompressedSize.
Referenced by TreeFileRecord::getBytes(), and TreeFile::readHeader().
byte* TreeDataBlock::uncompress (FileInputStream * fileStream) inline
Uncompresses a block of data and returns it in a byte buffer.
Parameters
fileStream FileInputStream that has been advanced to the position of the compressedData and will be read for the compressedSize
Definition at line 60 of file TreeDataBlock.h.
References compressedSize, compressionType, and uncompressedSize.
Referenced by TreeFileRecord::getBytes(), TreeFile::readFileBlock(), and TreeFile::readNameBlock().
Member Data Documentation
unsigned long TreeDataBlock::compressedSize private
Definition at line 20 of file TreeDataBlock.h.
Referenced by getCompressedSize(), operator=(), setCompressedSize(), TreeDataBlock(), and uncompress().
uint32 TreeDataBlock::compressionType private
Definition at line 18 of file TreeDataBlock.h.
Referenced by operator=(), setCompressionType(), TreeDataBlock(), and uncompress().
const int TreeDataBlock::SIZE = 6 * sizeof(int) static
Definition at line 26 of file TreeDataBlock.h.
Referenced by TreeFile::readHeader().
unsigned long TreeDataBlock::uncompressedSize private
Definition at line 21 of file TreeDataBlock.h.
Referenced by getUncompressedSize(), operator=(), setUncompressedSize(), TreeDataBlock(), and uncompress().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/tre3/TreeDataBlock.h