Core3: server::login::packets::LoginClientToken Class Reference
server::login::packets::LoginClientToken Class Reference
#include <LoginClientToken.h>
Public Member Functions
LoginClientToken (String &username, uint32 sessionKey, uint32 accountid, uint32 stationid)
LoginClientToken (Account *account, uint32 sessionID)
Static Public Member Functions
static void parse (Packet *pack)
Detailed Description
Definition at line 62 of file LoginClientToken.h.
Constructor & Destructor Documentation
server::login::packets::LoginClientToken::LoginClientToken (String & username, uint32 sessionKey, uint32 accountid, uint32 stationid) inline
Definition at line 64 of file LoginClientToken.h.
server::login::packets::LoginClientToken::LoginClientToken (Account * account, uint32 sessionID) inline
Definition at line 101 of file LoginClientToken.h.
References server::login::account::Account::getAccountID(), server::login::account::Account::getStationID(), and server::login::account::Account::getUsername().
Member Function Documentation
static void server::login::packets::LoginClientToken::parse (Packet * pack) inline static
Definition at line 116 of file LoginClientToken.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/packets/LoginClientToken.h