Core3: OverrideTerminalSuiCallback Class Reference
OverrideTerminalSuiCallback Class Reference
#include <OverrideTerminalSuiCallback.h>
Public Member Functions
OverrideTerminalSuiCallback (ZoneServer *server, String dnaCode)
void run (CreatureObject *player, SuiBox *suiBox, bool cancelPressed, Vector< UnicodeString > *args)
Public Member Functions inherited from server::zone::objects::player::sui::SuiCallback
SuiCallback (ZoneServer *serv)
Private Attributes
String dnaString
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::player::sui::SuiCallback
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 16 of file OverrideTerminalSuiCallback.h.
Constructor & Destructor Documentation
OverrideTerminalSuiCallback::OverrideTerminalSuiCallback (ZoneServer * server, String dnaCode) inline
Definition at line 19 of file OverrideTerminalSuiCallback.h.
References dnaString.
Member Function Documentation
void OverrideTerminalSuiCallback::run (CreatureObject * player, SuiBox * suiBox, bool cancelPressed, Vector< UnicodeString > * args) inline virtual
Parameters
player The player that this suibox is assigned to.
suiBox The actual SuiBox object.
cancelPressed Was the cancel button pressed, or was the sui box closed via a similar method. (this might actually be more of a dialogResult type variable)
args A vector of UnicodeStrings containing the arguments passed to the sui box from the client.
Implements server::zone::objects::player::sui::SuiCallback.
Definition at line 25 of file OverrideTerminalSuiCallback.h.
References dnaString, server::zone::Zone::getGCWManager(), server::zone::objects::player::sui::SuiBox::getUsingObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::player::sui::SuiBox::isListBox(), and server::zone::managers::gcw::GCWManager::processDNASample().
Member Data Documentation
String OverrideTerminalSuiCallback::dnaString private
Definition at line 17 of file OverrideTerminalSuiCallback.h.
Referenced by OverrideTerminalSuiCallback(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/callbacks/OverrideTerminalSuiCallback.h