Core3: server::zone::objects::player::sessions::vendor::CreateVendorSessionAdapter Class Reference
server::zone::objects::player::sessions::vendor::CreateVendorSessionAdapter Class Reference
#include <CreateVendorSession.h>
Public Member Functions
CreateVendorSessionAdapter (CreateVendorSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession ()
int cancelSession ()
int clearSession ()
void handleVendorSelection (byte menuID)
void createVendor (String &name)
Detailed Description
Definition at line 209 of file CreateVendorSession.h.
Constructor & Destructor Documentation
CreateVendorSessionAdapter::CreateVendorSessionAdapter (CreateVendorSession * impl)
Definition at line 339 of file CreateVendorSession.cpp.
Member Function Documentation
int CreateVendorSessionAdapter::cancelSession ()
Definition at line 381 of file CreateVendorSession.cpp.
Referenced by invokeMethod().
int CreateVendorSessionAdapter::clearSession ()
Definition at line 385 of file CreateVendorSession.cpp.
Referenced by invokeMethod().
void CreateVendorSessionAdapter::createVendor (String & name)
Definition at line 393 of file CreateVendorSession.cpp.
Referenced by invokeMethod().
void CreateVendorSessionAdapter::handleVendorSelection (byte menuID)
Definition at line 389 of file CreateVendorSession.cpp.
Referenced by invokeMethod().
int CreateVendorSessionAdapter::initializeSession ()
Definition at line 377 of file CreateVendorSession.cpp.
Referenced by invokeMethod().
void CreateVendorSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 342 of file CreateVendorSession.cpp.
References cancelSession(), clearSession(), createVendor(), handleVendorSelection(), initializeSession(), RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_CREATEVENDOR__STRING_, RPC_HANDLEVENDORSELECTION__BYTE_, and RPC_INITIALIZESESSION__.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/CreateVendorSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/CreateVendorSession.cpp