Core3: server::zone::objects::tangible::threat::ThreatMatrix Class Reference
server::zone::objects::tangible::threat::ThreatMatrix Class Reference
#include <ThreatMatrix.h>
Public Member Functions
ThreatMatrix ()
~ThreatMatrix ()
ThreatMatrix (const ThreatMatrix &e)
ThreatMatrix & operator= (const ThreatMatrix &e)
void clear ()
void add (CreatureObject *creature, ThreatMapEntry *entry)
CreatureObject * getLargestThreat ()
void print ()
Protected Attributes
ManagedReference
< CreatureObject * > tauntThreat
ManagedReference
< CreatureObject * > focusedThreat
VectorMap< uint32,
ManagedReference
< CreatureObject * > > damageMap
VectorMap< int,
ManagedReference
< CreatureObject * > > aggroMap
VectorMap< int,
ManagedReference
< CreatureObject * > > healMap
Detailed Description
Definition at line 37 of file ThreatMatrix.h.
Constructor & Destructor Documentation
ThreatMatrix::ThreatMatrix ()
Definition at line 12 of file ThreatMatrix.cpp.
References focusedThreat, and tauntThreat.
ThreatMatrix::~ThreatMatrix ()
Definition at line 17 of file ThreatMatrix.cpp.
ThreatMatrix::ThreatMatrix (const ThreatMatrix & e)
Definition at line 21 of file ThreatMatrix.cpp.
Member Function Documentation
void ThreatMatrix::add (CreatureObject * creature, ThreatMapEntry * entry)
We don't want to add someone who hasn't done and damage to this
Anyone with an entry should be in this map
Only healers should be in this map
Definition at line 46 of file ThreatMatrix.cpp.
References aggroMap, damageMap, ThreatStates::FOCUSED, focusedThreat, server::zone::objects::tangible::threat::ThreatMapEntry::getAggroMod(), server::zone::objects::tangible::threat::ThreatMapEntry::getHeal(), server::zone::objects::tangible::threat::ThreatMapEntry::hasState(), healMap, server::zone::objects::creature::CreatureObject::isPlayerCreature(), ThreatStates::TAUNTED, and tauntThreat.
Referenced by server::zone::objects::tangible::threat::ThreatMap::getHighestThreatCreature().
void ThreatMatrix::clear ()
Definition at line 31 of file ThreatMatrix.cpp.
References aggroMap, damageMap, focusedThreat, healMap, and tauntThreat.
Referenced by server::zone::objects::tangible::threat::ThreatMap::getHighestThreatCreature(), getLargestThreat(), and server::zone::objects::tangible::threat::ThreatMap::removeAll().
CreatureObject * ThreatMatrix::getLargestThreat ()
Definition at line 79 of file ThreatMatrix.cpp.
References aggroMap, clear(), damageMap, focusedThreat, server::zone::objects::creature::CreatureObject::getFirstName(), healMap, print(), and tauntThreat.
Referenced by server::zone::objects::tangible::threat::ThreatMap::getHighestThreatCreature().
ThreatMatrix & ThreatMatrix::operator= (const ThreatMatrix & e)
Definition at line 25 of file ThreatMatrix.cpp.
void ThreatMatrix::print ()
Definition at line 127 of file ThreatMatrix.cpp.
References aggroMap, damageMap, focusedThreat, healMap, and tauntThreat.
Referenced by getLargestThreat().
Member Data Documentation
VectorMap<int, ManagedReference<CreatureObject*> > server::zone::objects::tangible::threat::ThreatMatrix::aggroMap protected
Definition at line 44 of file ThreatMatrix.h.
Referenced by add(), clear(), getLargestThreat(), and print().
VectorMap<uint32, ManagedReference<CreatureObject*> > server::zone::objects::tangible::threat::ThreatMatrix::damageMap protected
Definition at line 43 of file ThreatMatrix.h.
Referenced by add(), clear(), getLargestThreat(), and print().
ManagedReference<CreatureObject*> server::zone::objects::tangible::threat::ThreatMatrix::focusedThreat protected
Definition at line 41 of file ThreatMatrix.h.
Referenced by add(), clear(), getLargestThreat(), print(), and ThreatMatrix().
VectorMap<int, ManagedReference<CreatureObject*> > server::zone::objects::tangible::threat::ThreatMatrix::healMap protected
Definition at line 45 of file ThreatMatrix.h.
Referenced by add(), clear(), getLargestThreat(), and print().
ManagedReference<CreatureObject*> server::zone::objects::tangible::threat::ThreatMatrix::tauntThreat protected
Definition at line 40 of file ThreatMatrix.h.
Referenced by add(), clear(), getLargestThreat(), print(), and ThreatMatrix().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/threat/ThreatMatrix.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/threat/ThreatMatrix.cpp