Core3: server::zone::objects::creature::conversation::InformantMissionConversationObserverImplementation Class Reference
server::zone::objects::creature::conversation::InformantMissionConversationObserverImplementation Class Reference
#include <InformantMissionConversationObserver.h>
Public Member Functions
InformantMissionConversationObserverImplementation (ConversationTemplate *conversationTemplate)
InformantMissionConversationObserverImplementation (DummyConstructorParameter *param)
operator const InformantMissionConversationObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
ConversationObserverImplementation (ConversationTemplate *conversationTemplate)
ConversationObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
virtual ConversationScreen * getNextConversationScreen (CreatureObject *conversingPlayer, int selectedOption, CreatureObject *conversingNPC)
virtual ConversationScreen * runScreenHandlers (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
operator const ConversationObserver * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< InformantMissionConversationObserver * > _this
Public Attributes inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
WeakReference
< ConversationObserver * > _this
Protected Member Functions
virtual ~InformantMissionConversationObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
virtual void createConversationSession (CreatureObject *conversingPlayer, CreatureObject *npc)
void registerScreenHandler (const String &screenId, ScreenHandler *screenHandler)
void removeScreenHandler (const String &screenId)
void createPositionObserver (CreatureObject *player)
virtual ~ConversationObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
InformantMissionScreenHandler informantMissionScreenHandler
Friends
class InformantMissionConversationObserver
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
Reference< ConversationTemplate * > conversationTemplate
Detailed Description
Definition at line 61 of file InformantMissionConversationObserver.h.
Constructor & Destructor Documentation
InformantMissionConversationObserverImplementation::InformantMissionConversationObserverImplementation (ConversationTemplate * conversationTemplate)
Definition at line 47 of file InformantMissionConversationObserverImplementation.cpp.
References informantMissionScreenHandler, and server::zone::objects::creature::conversation::ConversationObserverImplementation::registerScreenHandler().
InformantMissionConversationObserverImplementation::InformantMissionConversationObserverImplementation (DummyConstructorParameter * param)
Definition at line 45 of file InformantMissionConversationObserver.cpp.
References _initializeImplementation().
InformantMissionConversationObserverImplementation::~InformantMissionConversationObserverImplementation () protected virtual
Definition at line 50 of file InformantMissionConversationObserver.cpp.
Member Function Documentation
DistributedObjectStub * InformantMissionConversationObserverImplementation::_getStub ()
Definition at line 70 of file InformantMissionConversationObserver.cpp.
References _this.
void InformantMissionConversationObserverImplementation::_initializeImplementation () protected
Definition at line 57 of file InformantMissionConversationObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by InformantMissionConversationObserverImplementation().
void InformantMissionConversationObserverImplementation::_serializationHelperMethod () protected
Definition at line 106 of file InformantMissionConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void InformantMissionConversationObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 65 of file InformantMissionConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::conversation::InformantMissionConversationObserver::InformantMissionConversationObserver().
void InformantMissionConversationObserverImplementation::finalize () protected
Definition at line 54 of file InformantMissionConversationObserver.cpp.
void InformantMissionConversationObserverImplementation::lock (bool doLock = true) protected
Definition at line 78 of file InformantMissionConversationObserver.cpp.
References _this.
void InformantMissionConversationObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 82 of file InformantMissionConversationObserver.cpp.
References _this.
InformantMissionConversationObserverImplementation::operator const InformantMissionConversationObserver * ()
Definition at line 74 of file InformantMissionConversationObserver.cpp.
void InformantMissionConversationObserverImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::conversation::ConversationObserverImplementation.
Definition at line 113 of file InformantMissionConversationObserver.cpp.
References readObjectMember().
bool InformantMissionConversationObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 132 of file InformantMissionConversationObserver.cpp.
References informantMissionScreenHandler, and server::zone::objects::creature::conversation::ConversationObserverImplementation::readObjectMember().
Referenced by readObject().
void InformantMissionConversationObserverImplementation::rlock (bool doLock = true) protected
Definition at line 86 of file InformantMissionConversationObserver.cpp.
References _this.
void InformantMissionConversationObserverImplementation::runlock (bool doLock = true) protected
Definition at line 102 of file InformantMissionConversationObserver.cpp.
References _this.
void InformantMissionConversationObserverImplementation::unlock (bool doLock = true) protected
Definition at line 98 of file InformantMissionConversationObserver.cpp.
References _this.
void InformantMissionConversationObserverImplementation::wlock (bool doLock = true) protected
Definition at line 90 of file InformantMissionConversationObserver.cpp.
References _this.
void InformantMissionConversationObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 94 of file InformantMissionConversationObserver.cpp.
References _this.
void InformantMissionConversationObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::conversation::ConversationObserverImplementation.
Definition at line 146 of file InformantMissionConversationObserver.cpp.
References writeObjectMembers().
int InformantMissionConversationObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 153 of file InformantMissionConversationObserver.cpp.
References informantMissionScreenHandler, and server::zone::objects::creature::conversation::ConversationObserverImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class InformantMissionConversationObserver friend
Definition at line 103 of file InformantMissionConversationObserver.h.
Member Data Documentation
WeakReference<InformantMissionConversationObserver*> server::zone::objects::creature::conversation::InformantMissionConversationObserverImplementation::_this
Definition at line 69 of file InformantMissionConversationObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
InformantMissionScreenHandler server::zone::objects::creature::conversation::InformantMissionConversationObserverImplementation::informantMissionScreenHandler private
Definition at line 62 of file InformantMissionConversationObserver.h.
Referenced by InformantMissionConversationObserverImplementation(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/InformantMissionConversationObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/InformantMissionConversationObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/InformantMissionConversationObserverImplementation.cpp