Core3: ClientPoiDataTable Class Reference
ClientPoiDataTable Class Reference
#include <ClientPoiDataTable.h>
Public Member Functions
ClientPoiDataTable ()
void readObject (DataTableIff *dataTable)
bool containsPlanet (const String &name)
Vector< Reference< PoiData * > > getPois (const String &planetName)
int size ()
Private Attributes
VectorMap< String, Vector
< Reference< PoiData * > > > pois
Detailed Description
Definition at line 57 of file ClientPoiDataTable.h.
Constructor & Destructor Documentation
ClientPoiDataTable::ClientPoiDataTable () inline
Definition at line 60 of file ClientPoiDataTable.h.
References pois.
Member Function Documentation
bool ClientPoiDataTable::containsPlanet (const String & name) inline
Definition at line 76 of file ClientPoiDataTable.h.
References pois.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::isInRangeWithPoi().
Vector<Reference<PoiData*> > ClientPoiDataTable::getPois (const String & planetName) inline
Definition at line 80 of file ClientPoiDataTable.h.
References pois.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::isInRangeWithPoi().
void ClientPoiDataTable::readObject (DataTableIff * dataTable) inline
Definition at line 64 of file ClientPoiDataTable.h.
References PoiData::getPlanet(), DataTableIff::getRow(), DataTableIff::getTotalRows(), pois, and PoiData::readObject().
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadClientPoiData().
int ClientPoiDataTable::size () inline
Definition at line 84 of file ClientPoiDataTable.h.
References pois.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadClientPoiData().
Member Data Documentation
VectorMap<String, Vector<Reference<PoiData*> > > ClientPoiDataTable::pois private
Definition at line 58 of file ClientPoiDataTable.h.
Referenced by ClientPoiDataTable(), containsPlanet(), getPois(), readObject(), and size().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/ClientPoiDataTable.h