Core3: server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation Class Reference
server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation Class Reference
#include <CityRemoveMilitiaSession.h>
Public Member Functions
CityRemoveMilitiaSessionImplementation (CreatureObject *creature, CityRegion *city, unsigned long long militiaid, SceneObject *terminal=NULL)
CityRemoveMilitiaSessionImplementation (DummyConstructorParameter *param)
unsigned long long getMilitiaID ()
int initializeSession ()
int cancelSession ()
int clearSession ()
operator const CityRemoveMilitiaSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< CityRemoveMilitiaSession * > _this
Protected Member Functions
virtual ~CityRemoveMilitiaSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > creatureObject
ManagedWeakReference
< CityRegion * > cityRegion
ManagedWeakReference
< SceneObject * > terminalObject
unsigned long long militiaID
Friends
class CityRemoveMilitiaSession
Detailed Description
Definition at line 119 of file CityRemoveMilitiaSession.h.
Constructor & Destructor Documentation
CityRemoveMilitiaSessionImplementation::CityRemoveMilitiaSessionImplementation (CreatureObject * creature, CityRegion * city, unsigned long long militiaid, SceneObject * terminal = NULL)
Definition at line 269 of file CityRemoveMilitiaSession.cpp.
References _initializeImplementation(), cityRegion, creatureObject, militiaID, and terminalObject.
CityRemoveMilitiaSessionImplementation::CityRemoveMilitiaSessionImplementation (DummyConstructorParameter * param)
Definition at line 107 of file CityRemoveMilitiaSession.cpp.
References _initializeImplementation().
CityRemoveMilitiaSessionImplementation::~CityRemoveMilitiaSessionImplementation () protected virtual
Definition at line 112 of file CityRemoveMilitiaSession.cpp.
Member Function Documentation
DistributedObjectStub * CityRemoveMilitiaSessionImplementation::_getStub ()
Definition at line 132 of file CityRemoveMilitiaSession.cpp.
References _this.
void CityRemoveMilitiaSessionImplementation::_initializeImplementation () protected
Definition at line 119 of file CityRemoveMilitiaSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CityRemoveMilitiaSessionImplementation().
void CityRemoveMilitiaSessionImplementation::_serializationHelperMethod () protected
Definition at line 168 of file CityRemoveMilitiaSession.cpp.
Referenced by _initializeImplementation().
void CityRemoveMilitiaSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 127 of file CityRemoveMilitiaSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::CityRemoveMilitiaSession::CityRemoveMilitiaSession().
int CityRemoveMilitiaSessionImplementation::cancelSession ()
Definition at line 290 of file CityRemoveMilitiaSession.cpp.
References SessionFacadeType::CITYMILITIA, and creatureObject.
Referenced by server::zone::objects::player::sessions::CityRemoveMilitiaSession::cancelSession(), and initializeSession().
int CityRemoveMilitiaSessionImplementation::clearSession ()
Definition at line 297 of file CityRemoveMilitiaSession.cpp.
Referenced by server::zone::objects::player::sessions::CityRemoveMilitiaSession::clearSession().
void CityRemoveMilitiaSessionImplementation::finalize () protected
Definition at line 116 of file CityRemoveMilitiaSession.cpp.
unsigned long long CityRemoveMilitiaSessionImplementation::getMilitiaID ()
Definition at line 285 of file CityRemoveMilitiaSession.cpp.
References militiaID.
Referenced by server::zone::objects::player::sessions::CityRemoveMilitiaSession::getMilitiaID().
int CityRemoveMilitiaSessionImplementation::initializeSession ()
Definition at line 18 of file CityRemoveMilitiaSessionImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), cancelSession(), SuiWindowType::CITY_REMOVE_MILITIA, cityRegion, creatureObject, militiaID, and terminalObject.
Referenced by server::zone::objects::player::sessions::CityRemoveMilitiaSession::initializeSession().
void CityRemoveMilitiaSessionImplementation::lock (bool doLock = true) protected
Definition at line 140 of file CityRemoveMilitiaSession.cpp.
References _this.
void CityRemoveMilitiaSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 144 of file CityRemoveMilitiaSession.cpp.
References _this.
CityRemoveMilitiaSessionImplementation::operator const CityRemoveMilitiaSession * ()
Definition at line 136 of file CityRemoveMilitiaSession.cpp.
void CityRemoveMilitiaSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 175 of file CityRemoveMilitiaSession.cpp.
References readObjectMember().
bool CityRemoveMilitiaSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 194 of file CityRemoveMilitiaSession.cpp.
References cityRegion, creatureObject, militiaID, and terminalObject.
Referenced by readObject().
void CityRemoveMilitiaSessionImplementation::rlock (bool doLock = true) protected
Definition at line 148 of file CityRemoveMilitiaSession.cpp.
References _this.
void CityRemoveMilitiaSessionImplementation::runlock (bool doLock = true) protected
Definition at line 164 of file CityRemoveMilitiaSession.cpp.
References _this.
void CityRemoveMilitiaSessionImplementation::unlock (bool doLock = true) protected
Definition at line 160 of file CityRemoveMilitiaSession.cpp.
References _this.
void CityRemoveMilitiaSessionImplementation::wlock (bool doLock = true) protected
Definition at line 152 of file CityRemoveMilitiaSession.cpp.
References _this.
void CityRemoveMilitiaSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 156 of file CityRemoveMilitiaSession.cpp.
References _this.
void CityRemoveMilitiaSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 220 of file CityRemoveMilitiaSession.cpp.
References writeObjectMembers().
int CityRemoveMilitiaSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 227 of file CityRemoveMilitiaSession.cpp.
References cityRegion, creatureObject, militiaID, and terminalObject.
Referenced by writeObject().
Friends And Related Function Documentation
friend class CityRemoveMilitiaSession friend
Definition at line 176 of file CityRemoveMilitiaSession.h.
Member Data Documentation
WeakReference<CityRemoveMilitiaSession*> server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation::_this
Definition at line 142 of file CityRemoveMilitiaSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<CityRegion* > server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation::cityRegion protected
Definition at line 123 of file CityRemoveMilitiaSession.h.
Referenced by CityRemoveMilitiaSessionImplementation(), initializeSession(), readObjectMember(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation::creatureObject protected
Definition at line 121 of file CityRemoveMilitiaSession.h.
Referenced by cancelSession(), CityRemoveMilitiaSessionImplementation(), initializeSession(), readObjectMember(), and writeObjectMembers().
unsigned long long server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation::militiaID protected
Definition at line 127 of file CityRemoveMilitiaSession.h.
Referenced by CityRemoveMilitiaSessionImplementation(), getMilitiaID(), initializeSession(), readObjectMember(), and writeObjectMembers().
ManagedWeakReference<SceneObject* > server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation::terminalObject protected
Definition at line 125 of file CityRemoveMilitiaSession.h.
Referenced by CityRemoveMilitiaSessionImplementation(), initializeSession(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityRemoveMilitiaSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityRemoveMilitiaSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityRemoveMilitiaSessionImplementation.cpp