Core3: DeltaMessage Class Reference
DeltaMessage Class Reference
#include <DeltaMessage.h>
Public Member Functions
DeltaMessage (uint64 oid, uint32 name, uint8 type)
uint32 generateRandomObjectCRC ()
void startUpdate (uint16 type)
void addByteUpdate (uint16 type, uint8 value)
void addShortUpdate (uint16 type, uint16 value)
void addIntUpdate (uint16 type, uint32 value)
void addLongUpdate (uint16 type, uint64 value)
void addFloatUpdate (uint16 type, float value)
void addAsciiUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const UnicodeString &val)
void startList (uint32 cnt, uint32 updcnt)
void addListIntElement (uint16 index, uint32 value)
void addListFloatElement (uint16 index, float value)
void addListLongElement (uint16 index, uint64 value)
void addListAsciiElement (const String &value)
void removeListIntElement (uint16 index, uint32 value)
void removeListFloatElement (uint16 index, float value)
void removeListLongElement (uint16 index, uint64 value)
void removeListLongElement (uint16 index)
void removeListAsciiElement (const String &value)
void close ()
Private Attributes
int updateCount
Detailed Description
Definition at line 50 of file DeltaMessage.h.
Constructor & Destructor Documentation
DeltaMessage::DeltaMessage (uint64 oid, uint32 name, uint8 type) inline
Definition at line 54 of file DeltaMessage.h.
References updateCount.
Member Function Documentation
void DeltaMessage::addAsciiUpdate (uint16 type, const String & val) inline
Definition at line 131 of file DeltaMessage.h.
References startUpdate().
Referenced by CreatureObjectDeltaMessage3::updateCharacterAppearance(), TangibleObjectDeltaMessage3::updateCustomizationString(), and CreatureObjectDeltaMessage6::updateMoodStr().
void DeltaMessage::addByteUpdate (uint16 type, uint8 value) inline
Definition at line 106 of file DeltaMessage.h.
References startUpdate().
Referenced by ManufactureSchematicObjectDeltaMessage6::insertToResourceSlot(), InstallationObjectDeltaMessage7::setNoHopperUpdate(), CreatureObjectDeltaMessage3::updateFactionRank(), InstallationObjectDeltaMessage7::updateHopper(), CreatureObjectDeltaMessage6::updateMoodID(), InstallationObjectDeltaMessage3::updateOperating(), InstallationObjectDeltaMessage7::updateOperating(), and CreatureObjectDeltaMessage3::updatePosture().
void DeltaMessage::addFloatUpdate (uint16 type, float value) inline
Definition at line 126 of file DeltaMessage.h.
References startUpdate().
Referenced by CreatureObjectDeltaMessage4::updateAccelerationMultiplierBase(), CreatureObjectDeltaMessage4::updateAccelerationMultiplierMod(), ManufactureSchematicObjectDeltaMessage3::updateComplexity(), TangibleObjectDeltaMessage3::updateComplexity(), InstallationObjectDeltaMessage7::updateExtractionRate(), CreatureObjectDeltaMessage3::updateHeight(), InstallationObjectDeltaMessage7::updateHopperSize(), CreatureObjectDeltaMessage4::updateRunSpeed(), CreatureObjectDeltaMessage4::updateSpeedMultiplierBase(), CreatureObjectDeltaMessage4::updateSpeedMultiplierMod(), CreatureObjectDeltaMessage4::updateTerrainNegotiation(), and CreatureObjectDeltaMessage4::updateTurnScale().
void DeltaMessage::addIntUpdate (uint16 type, uint32 value) inline
Definition at line 116 of file DeltaMessage.h.
References startUpdate().
Referenced by FactoryCrateObjectDeltaMessage3::setQuantity(), CellObjectDeltaMessage3::updateCellNumber(), ManufactureSchematicObjectDeltaMessage3::updateCondition(), TangibleObjectDeltaMessage3::updateConditionDamage(), TangibleObjectDeltaMessage3::updateCountdownTimer(), CreatureObjectDeltaMessage3::updateCreatureBitmask(), HarvesterObjectDeltaMessage3::updateDamage(), PlayerObjectDeltaMessage9::updateDrinkFilling(), PlayerObjectDeltaMessage9::updateFoodFilling(), PlayerObjectDeltaMessage8::updateForcePower(), PlayerObjectDeltaMessage8::updateForcePowerMax(), CreatureObjectDeltaMessage6::updateGuildID(), ManufactureSchematicObjectDeltaMessage3::updateManufactureLimit(), TangibleObjectDeltaMessage3::updateMaxCondition(), TangibleObjectDeltaMessage3::updateOptionsBitmask(), ResourceContainerObjectDeltaMessage3::updateQuantity(), CreatureObjectDeltaMessage3::updateShockWounds(), IntangibleObjectDeltaMessage3::updateStatus(), and PlayerObjectDeltaMessage9::updateStomachFilling().
void DeltaMessage::addListAsciiElement (const String & value) inline
Definition at line 170 of file DeltaMessage.h.
void DeltaMessage::addListFloatElement (uint16 index, float value) inline
Definition at line 158 of file DeltaMessage.h.
Referenced by ManufactureSchematicObjectDeltaMessage7::initialAssemblyUpdate().
void DeltaMessage::addListIntElement (uint16 index, uint32 value) inline
Definition at line 152 of file DeltaMessage.h.
void DeltaMessage::addListLongElement (uint16 index, uint64 value) inline
Definition at line 164 of file DeltaMessage.h.
void DeltaMessage::addLongUpdate (uint16 type, uint64 value) inline
Definition at line 121 of file DeltaMessage.h.
References startUpdate().
Referenced by InstallationObjectDeltaMessage7::updateActiveResourceSpawn(), CreatureObjectDeltaMessage3::updateCreatureLinkID(), CreatureObjectDeltaMessage6::updateGroupID(), CreatureObjectDeltaMessage3::updateState(), CreatureObjectDeltaMessage6::updateTarget(), and CreatureObjectDeltaMessage6::updateWeapon().
void DeltaMessage::addShortUpdate (uint16 type, uint16 value) inline
Definition at line 111 of file DeltaMessage.h.
References startUpdate().
void DeltaMessage::addUnicodeUpdate (uint16 type, const String & val) inline
Definition at line 136 of file DeltaMessage.h.
References startUpdate().
Referenced by ManufactureSchematicObjectDeltaMessage3::updateName(), and TangibleObjectDeltaMessage3::updateName().
void DeltaMessage::addUnicodeUpdate (uint16 type, const UnicodeString & val) inline
Definition at line 142 of file DeltaMessage.h.
References startUpdate().
void DeltaMessage::close () inline
Definition at line 203 of file DeltaMessage.h.
References updateCount.
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::objects::player::PlayerObjectImplementation::addAbilities(), server::zone::objects::player::PlayerObjectImplementation::addAbility(), server::zone::objects::tangible::TangibleObjectImplementation::addDefender(), server::zone::objects::player::PlayerObjectImplementation::addExperience(), server::zone::objects::player::PlayerObjectImplementation::addFriend(), server::zone::objects::player::PlayerObjectImplementation::addIgnore(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::addIngredientToSlot(), server::zone::objects::installation::InstallationObjectImplementation::addResourceToHopper(), server::zone::objects::player::PlayerObjectImplementation::addSchematics(), server::zone::objects::creature::CreatureObjectImplementation::addSkill(), server::zone::objects::creature::CreatureObjectImplementation::addSkillMod(), server::zone::objects::creature::CreatureObjectImplementation::addWearableObject(), server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::group::GroupObjectImplementation::calcGroupLevel(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::cancelSession(), server::zone::objects::installation::InstallationObjectImplementation::changeActiveResourceID(), server::zone::objects::player::PlayerObjectImplementation::clearCharacterBit(), server::zone::objects::creature::CreatureObjectImplementation::clearCombatState(), server::zone::objects::installation::InstallationObjectImplementation::clearResourceHopper(), server::zone::objects::creature::CreatureObjectImplementation::clearState(), server::zone::managers::guild::GuildManagerImplementation::createGuild(), server::zone::objects::installation::factory::FactoryObjectImplementation::createNewObject(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::customization(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), KipUpShotCommand::doQueueCommand(), RollShotCommand::doQueueCommand(), DiveShotCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::experiment(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::finishAssembly(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::finishStage1(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::finishStage2(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::initialAssembly(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), server::zone::managers::guild::GuildManagerImplementation::leaveGuild(), server::zone::objects::group::GroupObjectImplementation::makeLeader(), server::zone::objects::player::PlayerObjectImplementation::removeAbilities(), server::zone::objects::player::PlayerObjectImplementation::removeAbility(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefender(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefenders(), server::zone::objects::player::PlayerObjectImplementation::removeExperience(), server::zone::objects::player::PlayerObjectImplementation::removeFriend(), server::zone::objects::player::PlayerObjectImplementation::removeIgnore(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::removeIngredientFromSlot(), server::zone::objects::group::GroupObjectImplementation::removeMember(), server::zone::managers::resource::ResourceManagerImplementation::removePowerFromPlayer(), BlueprintEntry::removeResources(), server::zone::objects::player::PlayerObjectImplementation::removeSchematics(), server::zone::objects::creature::CreatureObjectImplementation::removeSkill(), server::zone::objects::player::PlayerObjectImplementation::removeWaypoint(), server::zone::objects::creature::CreatureObjectImplementation::removeWearableObject(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::selectDraftSchematic(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendDelta7(), server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainingUpdate(), server::zone::objects::player::PlayerObjectImplementation::sendFriendLists(), server::zone::objects::creature::CreatureObjectImplementation::setAccelerationMultiplierBase(), server::zone::objects::creature::CreatureObjectImplementation::setAccelerationMultiplierMod(), server::zone::objects::installation::InstallationObjectImplementation::setActiveResource(), server::zone::objects::creature::CreatureObjectImplementation::setBankCredits(), server::zone::objects::creature::CreatureObjectImplementation::setBaseHAM(), server::zone::objects::creature::CreatureObjectImplementation::setCashCredits(), server::zone::objects::player::PlayerObjectImplementation::setCharacterBit(), server::zone::objects::creature::CreatureObjectImplementation::setCombatState(), server::zone::objects::tangible::TangibleObjectImplementation::setConditionDamage(), server::zone::objects::tangible::TangibleObjectImplementation::setCountdownTimer(), server::zone::objects::mission::MissionObjectImplementation::setCreatorName(), server::zone::objects::creature::CreatureObjectImplementation::setCreatureLink(), server::zone::objects::tangible::TangibleObjectImplementation::setCustomObjectName(), server::zone::objects::tangible::TangibleObjectImplementation::setDefender(), server::zone::objects::player::PlayerObjectImplementation::setDrinkFilling(), server::zone::objects::creature::CreatureObjectImplementation::setEncumbrance(), server::zone::objects::mission::MissionObjectImplementation::setEndPosition(), server::zone::objects::creature::CreatureObjectImplementation::setFactionRank(), server::zone::objects::player::PlayerObjectImplementation::setFoodFilling(), server::zone::objects::player::PlayerObjectImplementation::setForcePower(), server::zone::objects::player::PlayerObjectImplementation::setForcePowerMax(), server::zone::objects::creature::CreatureObjectImplementation::setHAM(), server::zone::objects::creature::CreatureObjectImplementation::setHeight(), server::zone::objects::creature::CreatureObjectImplementation::setInstrumentID(), server::zone::objects::player::PlayerObjectImplementation::setJediState(), server::zone::objects::player::PlayerObjectImplementation::setLanguageID(), server::zone::objects::creature::CreatureObjectImplementation::setLevel(), server::zone::objects::creature::CreatureObjectImplementation::setListenToID(), server::zone::objects::tangible::TangibleObjectImplementation::setMaxCondition(), server::zone::objects::creature::CreatureObjectImplementation::setMaxHAM(), server::zone::objects::mission::MissionObjectImplementation::setMissionDescription(), server::zone::objects::mission::MissionObjectImplementation::setMissionDifficulty(), server::zone::objects::mission::MissionObjectImplementation::setMissionTargetName(), server::zone::objects::mission::MissionObjectImplementation::setMissionTitle(), server::zone::objects::creature::CreatureObjectImplementation::setMood(), server::zone::objects::creature::CreatureObjectImplementation::setMoodString(), server::zone::objects::installation::InstallationObjectImplementation::setOperating(), server::zone::objects::tangible::TangibleObjectImplementation::setOptionsBitmask(), server::zone::objects::creature::CreatureObjectImplementation::setPerformanceAnimation(), server::zone::objects::creature::CreatureObjectImplementation::setPerformanceCounter(), server::zone::objects::creature::CreatureObjectImplementation::setPosture(), server::zone::objects::resource::ResourceContainerImplementation::setQuantity(), server::zone::objects::mission::MissionObjectImplementation::setRefreshCounter(), server::zone::objects::mission::MissionObjectImplementation::setRewardCredits(), server::zone::objects::creature::CreatureObjectImplementation::setRunSpeed(), server::zone::objects::creature::CreatureObjectImplementation::setShockWounds(), server::zone::objects::creature::CreatureObjectImplementation::setSpeedMultiplierBase(), server::zone::objects::creature::CreatureObjectImplementation::setSpeedMultiplierMod(), server::zone::objects::mission::MissionObjectImplementation::setStartPosition(), server::zone::objects::creature::CreatureObjectImplementation::setState(), server::zone::objects::creature::CreatureObjectImplementation::setTargetID(), server::zone::objects::mission::MissionObjectImplementation::setTargetTemplate(), server::zone::objects::creature::CreatureObjectImplementation::setTerrainNegotiation(), server::zone::objects::player::PlayerObjectImplementation::setTitle(), server::zone::objects::creature::CreatureObjectImplementation::setTurnScale(), server::zone::objects::mission::MissionObjectImplementation::setTypeCRC(), server::zone::objects::factorycrate::FactoryCrateImplementation::setUseCount(), server::zone::objects::player::PlayerObjectImplementation::setWaypoint(), server::zone::objects::creature::CreatureObjectImplementation::setWeapon(), server::zone::objects::creature::CreatureObjectImplementation::setWounds(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::startSession(), server::zone::managers::skill::SkillManager::surrenderSkill(), server::zone::objects::creature::CreatureObjectImplementation::updateGroup(), server::zone::objects::creature::CreatureObjectImplementation::updateGroupInviterID(), server::zone::objects::mission::MissionObjectImplementation::updateMissionLocation(), server::zone::managers::player::PlayerManagerImplementation::updatePermissionName(), server::zone::objects::installation::InstallationObjectImplementation::updateResourceContainerQuantity(), and server::zone::objects::intangible::IntangibleObjectImplementation::updateStatus().
uint32 DeltaMessage::generateRandomObjectCRC () inline
Definition at line 69 of file DeltaMessage.h.
void DeltaMessage::removeListAsciiElement (const String & value) inline
Definition at line 198 of file DeltaMessage.h.
void DeltaMessage::removeListFloatElement (uint16 index, float value) inline
Definition at line 181 of file DeltaMessage.h.
Referenced by ManufactureSchematicObjectDeltaMessage7::update0A(), ManufactureSchematicObjectDeltaMessage7::update0B(), ManufactureSchematicObjectDeltaMessage7::update0C(), and ManufactureSchematicObjectDeltaMessage7::update9().
void DeltaMessage::removeListIntElement (uint16 index, uint32 value) inline
Definition at line 175 of file DeltaMessage.h.
void DeltaMessage::removeListLongElement (uint16 index, uint64 value) inline
Definition at line 187 of file DeltaMessage.h.
void DeltaMessage::removeListLongElement (uint16 index) inline
Definition at line 193 of file DeltaMessage.h.
void DeltaMessage::startList (uint32 cnt, uint32 updcnt) inline
Definition at line 147 of file DeltaMessage.h.
Referenced by AbilityList::add(), SchematicList::add(), SkillList::add(), GuildObjectDeltaMessage3::addGuild(), ManufactureSchematicObjectDeltaMessage7::initialAssemblyUpdate(), SkillList::remove(), DeltaSet< String, ManagedReference< GuildObject * > >::removeAll(), GuildObjectDeltaMessage3::removeGuild(), InstallationObjectDeltaMessage6::startDefenderUpdate(), ManufactureSchematicObjectDeltaMessage7::update0A(), ManufactureSchematicObjectDeltaMessage7::update0B(), ManufactureSchematicObjectDeltaMessage7::update0C(), ManufactureSchematicObjectDeltaMessage7::update0D(), ManufactureSchematicObjectDeltaMessage7::update0E(), ManufactureSchematicObjectDeltaMessage7::update0F(), ManufactureSchematicObjectDeltaMessage7::update10(), ManufactureSchematicObjectDeltaMessage7::update13(), ManufactureSchematicObjectDeltaMessage7::update9(), and ManufactureSchematicObjectDeltaMessage3::updateCraftingValues().
void DeltaMessage::startUpdate (uint16 type) inline
Definition at line 82 of file DeltaMessage.h.
References updateCount.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addAbilities(), server::zone::objects::player::PlayerObjectImplementation::addAbility(), addAsciiUpdate(), addByteUpdate(), server::zone::objects::tangible::TangibleObjectImplementation::addDefender(), server::zone::objects::player::PlayerObjectImplementation::addExperience(), addFloatUpdate(), GuildObjectDeltaMessage3::addGuild(), addIntUpdate(), addLongUpdate(), server::zone::objects::group::GroupObjectImplementation::addMember(), server::zone::objects::installation::InstallationObjectImplementation::addResourceToHopper(), server::zone::objects::player::PlayerObjectImplementation::addSchematics(), addShortUpdate(), server::zone::objects::creature::CreatureObjectImplementation::addSkill(), server::zone::objects::creature::CreatureObjectImplementation::addSkillMod(), addUnicodeUpdate(), server::zone::objects::creature::CreatureObjectImplementation::addWearableObject(), server::zone::objects::installation::InstallationObjectImplementation::clearResourceHopper(), server::zone::managers::guild::GuildManagerImplementation::createGuild(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), ManufactureSchematicObjectDeltaMessage7::initialAssemblyUpdate(), PlayerList< 8 >::insertToDeltaMessage(), server::zone::objects::group::GroupObjectImplementation::makeLeader(), server::zone::objects::player::PlayerObjectImplementation::removeAbilities(), server::zone::objects::player::PlayerObjectImplementation::removeAbility(), GuildObjectDeltaMessage3::removeAllGuilds(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefender(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefenders(), server::zone::objects::player::PlayerObjectImplementation::removeExperience(), GuildObjectDeltaMessage3::removeGuild(), server::zone::objects::group::GroupObjectImplementation::removeMember(), server::zone::objects::player::PlayerObjectImplementation::removeSchematics(), server::zone::objects::creature::CreatureObjectImplementation::removeSkill(), server::zone::objects::player::PlayerObjectImplementation::removeWaypoint(), server::zone::objects::creature::CreatureObjectImplementation::removeWearableObject(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendDelta7(), server::zone::objects::installation::InstallationObjectImplementation::setActiveResource(), PlayerObjectDeltaMessage6::setAdminLevel(), server::zone::objects::creature::CreatureObjectImplementation::setBaseHAM(), PlayerObjectDeltaMessage9::setClosestCraftingStation(), PlayerObjectDeltaMessage9::setCraftingState(), PlayerObjectDeltaMessage3::setCurrentTitle(), server::zone::objects::tangible::TangibleObjectImplementation::setDefender(), server::zone::objects::creature::CreatureObjectImplementation::setEncumbrance(), PlayerObjectDeltaMessage9::setExperimentationEnabled(), PlayerObjectDeltaMessage9::setExperimentationPoints(), server::zone::objects::creature::CreatureObjectImplementation::setHAM(), PlayerObjectDeltaMessage9::setJediState(), PlayerObjectDeltaMessage9::setLanguageID(), server::zone::objects::creature::CreatureObjectImplementation::setMaxHAM(), ResourceContainerObjectDeltaMessage6::setResourceName(), ResourceContainerObjectDeltaMessage6::setResourceType(), PlayerObjectDeltaMessage3::setUpdateTypeNine(), server::zone::objects::player::PlayerObjectImplementation::setWaypoint(), server::zone::objects::creature::CreatureObjectImplementation::setWounds(), InstallationObjectDeltaMessage6::startDefenderUpdate(), ManufactureSchematicObjectDeltaMessage7::update0A(), ManufactureSchematicObjectDeltaMessage7::update0B(), ManufactureSchematicObjectDeltaMessage7::update0C(), ManufactureSchematicObjectDeltaMessage7::update0D(), ManufactureSchematicObjectDeltaMessage7::update0E(), ManufactureSchematicObjectDeltaMessage7::update0F(), ManufactureSchematicObjectDeltaMessage7::update10(), ManufactureSchematicObjectDeltaMessage7::update11(), ManufactureSchematicObjectDeltaMessage7::update12(), ManufactureSchematicObjectDeltaMessage7::update13(), ManufactureSchematicObjectDeltaMessage7::update14(), ManufactureSchematicObjectDeltaMessage7::update9(), CreatureObjectDeltaMessage1::updateBankCredits(), CreatureObjectDeltaMessage1::updateCashCredits(), PlayerObjectDeltaMessage3::updateCharacterBitmask(), ManufactureSchematicObjectDeltaMessage3::updateCraftingValues(), MissionObjectDeltaMessage3::updateCreator(), MissionObjectDeltaMessage3::updateDescriptionStf(), MissionObjectDeltaMessage3::updateDestination(), MissionObjectDeltaMessage3::updateDifficultyLevel(), CreatureObjectDeltaMessage4::updateEntertainerValue(), CreatureObjectDeltaMessage6::updateInstrumentID(), CreatureObjectDeltaMessage6::updateInviterId(), GroupObjectDeltaMessage6::updateLevel(), CreatureObjectDeltaMessage6::updateLevel(), CreatureObjectDeltaMessage4::updateListenToID(), CreatureObjectDeltaMessage6::updatePerformanceAnimation(), CreatureObjectDeltaMessage6::updatePerformanceCounter(), MissionObjectDeltaMessage3::updateRefreshCount(), server::zone::objects::installation::InstallationObjectImplementation::updateResourceContainerQuantity(), MissionObjectDeltaMessage3::updateRewardCredits(), MissionObjectDeltaMessage3::updateStartPosition(), MissionObjectDeltaMessage3::updateTargetName(), MissionObjectDeltaMessage3::updateTemplateCRC(), MissionObjectDeltaMessage3::updateTitleStf(), MissionObjectDeltaMessage3::updateTypeCRC(), and MissionObjectDeltaMessage3::updateWaypoint().
Member Data Documentation
int DeltaMessage::updateCount private
Definition at line 51 of file DeltaMessage.h.
Referenced by close(), DeltaMessage(), and startUpdate().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/DeltaMessage.h