Core3: server::zone::objects::player::sessions::PlaceStructureSessionImplementation Class Reference
server::zone::objects::player::sessions::PlaceStructureSessionImplementation Class Reference
#include <PlaceStructureSession.h>
Public Member Functions
PlaceStructureSessionImplementation (CreatureObject *creature, StructureDeed *deed)
PlaceStructureSessionImplementation (DummyConstructorParameter *param)
int initializeSession ()
void placeTemporaryNoBuildZone (SharedStructureObjectTemplate *serverTemplate)
void removeTemporaryNoBuildZone ()
int constructStructure (float x, float y, int angle)
int completeSession ()
int cancelSession ()
int clearSession ()
operator const PlaceStructureSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< PlaceStructureSession * > _this
Protected Member Functions
virtual ~PlaceStructureSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference
< CreatureObject * > creatureObject
ManagedReference< StructureDeed * > deedObject
float positionX
float positionY
int directionAngle
ManagedReference< SceneObject * > constructionBarricade
ManagedReference< Zone * > zone
ManagedReference< ActiveArea * > temporaryNoBuildZone
Friends
class PlaceStructureSession
Detailed Description
Definition at line 155 of file PlaceStructureSession.h.
Constructor & Destructor Documentation
PlaceStructureSessionImplementation::PlaceStructureSessionImplementation (CreatureObject * creature, StructureDeed * deed)
Definition at line 359 of file PlaceStructureSession.cpp.
References _initializeImplementation(), constructionBarricade, creatureObject, deedObject, directionAngle, server::zone::objects::scene::SceneObject::getZone(), positionX, positionY, temporaryNoBuildZone, and zone.
PlaceStructureSessionImplementation::PlaceStructureSessionImplementation (DummyConstructorParameter * param)
Definition at line 149 of file PlaceStructureSession.cpp.
References _initializeImplementation().
PlaceStructureSessionImplementation::~PlaceStructureSessionImplementation () protected virtual
Definition at line 154 of file PlaceStructureSession.cpp.
Member Function Documentation
DistributedObjectStub * PlaceStructureSessionImplementation::_getStub ()
Definition at line 174 of file PlaceStructureSession.cpp.
References _this.
void PlaceStructureSessionImplementation::_initializeImplementation () protected
Definition at line 161 of file PlaceStructureSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by PlaceStructureSessionImplementation().
void PlaceStructureSessionImplementation::_serializationHelperMethod () protected
Definition at line 210 of file PlaceStructureSession.cpp.
Referenced by _initializeImplementation().
void PlaceStructureSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 169 of file PlaceStructureSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::PlaceStructureSession::PlaceStructureSession().
int PlaceStructureSessionImplementation::cancelSession ()
Definition at line 388 of file PlaceStructureSession.cpp.
References creatureObject, and SessionFacadeType::PLACESTRUCTURE.
Referenced by server::zone::objects::player::sessions::PlaceStructureSession::cancelSession(), completeSession(), and constructStructure().
int PlaceStructureSessionImplementation::clearSession ()
Definition at line 395 of file PlaceStructureSession.cpp.
Referenced by server::zone::objects::player::sessions::PlaceStructureSession::clearSession().
int PlaceStructureSessionImplementation::completeSession ()
Definition at line 96 of file PlaceStructureSessionImplementation.cpp.
References cancelSession(), constructionBarricade, creatureObject, deedObject, directionAngle, StructureManager::placeStructure(), positionX, positionY, removeTemporaryNoBuildZone(), server::zone::objects::building::BuildingObject::setCustomObjectName(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), and zone.
Referenced by server::zone::objects::player::sessions::PlaceStructureSession::completeSession().
int PlaceStructureSessionImplementation::constructStructure (float x, float y, int angle)
Definition at line 27 of file PlaceStructureSessionImplementation.cpp.
References cancelSession(), constructionBarricade, creatureObject, deedObject, directionAngle, StructureFootprint::getColSize(), StructureFootprint::getRowSize(), TemplateManager::getTemplate(), placeTemporaryNoBuildZone(), positionX, positionY, temporaryNoBuildZone, and zone.
Referenced by server::zone::objects::player::sessions::PlaceStructureSession::constructStructure().
void PlaceStructureSessionImplementation::finalize () protected
Definition at line 158 of file PlaceStructureSession.cpp.
int PlaceStructureSessionImplementation::initializeSession ()
Definition at line 383 of file PlaceStructureSession.cpp.
Referenced by server::zone::objects::player::sessions::PlaceStructureSession::initializeSession().
void PlaceStructureSessionImplementation::lock (bool doLock = true) protected
Definition at line 182 of file PlaceStructureSession.cpp.
References _this.
void PlaceStructureSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 186 of file PlaceStructureSession.cpp.
References _this.
PlaceStructureSessionImplementation::operator const PlaceStructureSession * ()
Definition at line 178 of file PlaceStructureSession.cpp.
void PlaceStructureSessionImplementation::placeTemporaryNoBuildZone (SharedStructureObjectTemplate * serverTemplate)
Definition at line 71 of file PlaceStructureSessionImplementation.cpp.
References SharedTangibleObjectTemplate::getStructureFootprint(), positionX, positionY, temporaryNoBuildZone, and zone.
Referenced by constructStructure(), and server::zone::objects::player::sessions::PlaceStructureSession::placeTemporaryNoBuildZone().
void PlaceStructureSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 217 of file PlaceStructureSession.cpp.
References readObjectMember().
bool PlaceStructureSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 236 of file PlaceStructureSession.cpp.
References constructionBarricade, creatureObject, deedObject, directionAngle, positionX, positionY, temporaryNoBuildZone, and zone.
Referenced by readObject().
void PlaceStructureSessionImplementation::removeTemporaryNoBuildZone ()
Definition at line 90 of file PlaceStructureSessionImplementation.cpp.
References temporaryNoBuildZone.
Referenced by completeSession(), and server::zone::objects::player::sessions::PlaceStructureSession::removeTemporaryNoBuildZone().
void PlaceStructureSessionImplementation::rlock (bool doLock = true) protected
Definition at line 190 of file PlaceStructureSession.cpp.
References _this.
void PlaceStructureSessionImplementation::runlock (bool doLock = true) protected
Definition at line 206 of file PlaceStructureSession.cpp.
References _this.
void PlaceStructureSessionImplementation::unlock (bool doLock = true) protected
Definition at line 202 of file PlaceStructureSession.cpp.
References _this.
void PlaceStructureSessionImplementation::wlock (bool doLock = true) protected
Definition at line 194 of file PlaceStructureSession.cpp.
References _this.
void PlaceStructureSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 198 of file PlaceStructureSession.cpp.
References _this.
void PlaceStructureSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 278 of file PlaceStructureSession.cpp.
References writeObjectMembers().
int PlaceStructureSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 285 of file PlaceStructureSession.cpp.
References constructionBarricade, creatureObject, deedObject, directionAngle, positionX, positionY, temporaryNoBuildZone, and zone.
Referenced by writeObject().
Friends And Related Function Documentation
friend class PlaceStructureSession friend
Definition at line 226 of file PlaceStructureSession.h.
Member Data Documentation
WeakReference<PlaceStructureSession*> server::zone::objects::player::sessions::PlaceStructureSessionImplementation::_this
Definition at line 192 of file PlaceStructureSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedReference<SceneObject* > server::zone::objects::player::sessions::PlaceStructureSessionImplementation::constructionBarricade protected
Definition at line 167 of file PlaceStructureSession.h.
Referenced by completeSession(), constructStructure(), PlaceStructureSessionImplementation(), readObjectMember(), and writeObjectMembers().
ManagedReference<CreatureObject* > server::zone::objects::player::sessions::PlaceStructureSessionImplementation::creatureObject protected
Definition at line 157 of file PlaceStructureSession.h.
Referenced by cancelSession(), completeSession(), constructStructure(), PlaceStructureSessionImplementation(), readObjectMember(), and writeObjectMembers().
ManagedReference<StructureDeed* > server::zone::objects::player::sessions::PlaceStructureSessionImplementation::deedObject protected
Definition at line 159 of file PlaceStructureSession.h.
Referenced by completeSession(), constructStructure(), PlaceStructureSessionImplementation(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::player::sessions::PlaceStructureSessionImplementation::directionAngle protected
Definition at line 165 of file PlaceStructureSession.h.
Referenced by completeSession(), constructStructure(), PlaceStructureSessionImplementation(), readObjectMember(), and writeObjectMembers().
float server::zone::objects::player::sessions::PlaceStructureSessionImplementation::positionX protected
Definition at line 161 of file PlaceStructureSession.h.
Referenced by completeSession(), constructStructure(), PlaceStructureSessionImplementation(), placeTemporaryNoBuildZone(), readObjectMember(), and writeObjectMembers().
float server::zone::objects::player::sessions::PlaceStructureSessionImplementation::positionY protected
Definition at line 163 of file PlaceStructureSession.h.
Referenced by completeSession(), constructStructure(), PlaceStructureSessionImplementation(), placeTemporaryNoBuildZone(), readObjectMember(), and writeObjectMembers().
ManagedReference<ActiveArea* > server::zone::objects::player::sessions::PlaceStructureSessionImplementation::temporaryNoBuildZone protected
Definition at line 171 of file PlaceStructureSession.h.
Referenced by constructStructure(), PlaceStructureSessionImplementation(), placeTemporaryNoBuildZone(), readObjectMember(), removeTemporaryNoBuildZone(), and writeObjectMembers().
ManagedReference<Zone* > server::zone::objects::player::sessions::PlaceStructureSessionImplementation::zone protected
Definition at line 169 of file PlaceStructureSession.h.
Referenced by completeSession(), constructStructure(), PlaceStructureSessionImplementation(), placeTemporaryNoBuildZone(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/PlaceStructureSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/PlaceStructureSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/PlaceStructureSessionImplementation.cpp