Core3: server::zone::objects::player::sui::SuiBoxAdapter Class Reference
server::zone::objects::player::sui::SuiBoxAdapter Class Reference
#include <SuiBox.h>
Public Member Functions
SuiBoxAdapter (SuiBox *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type)
BaseMessage * generateMessage ()
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
bool isInputBox ()
bool isListBox ()
bool isMessageBox ()
bool isTransferBox ()
bool isBankTransferBox ()
bool isSlicingBox ()
bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
Detailed Description
Definition at line 473 of file SuiBox.h.
Constructor & Destructor Documentation
SuiBoxAdapter::SuiBoxAdapter (SuiBox * impl)
Definition at line 1117 of file SuiBox.cpp.
Member Function Documentation
void SuiBoxAdapter::addHeader (const String & variable, const String & type)
Definition at line 1358 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::addSetting (const String & optType, const String & variable, const String & setting, const String & value)
Definition at line 1354 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::clearOptions ()
Definition at line 1362 of file SuiBox.cpp.
Referenced by invokeMethod().
int SuiBoxAdapter::compareTo (SuiBox * obj)
Definition at line 1366 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::finalize ()
Definition at line 1326 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::generateBody (SuiCreatePageMessage * message)
Definition at line 1338 of file SuiBox.cpp.
Referenced by invokeMethod().
BaseMessage * SuiBoxAdapter::generateCloseMessage ()
Definition at line 1350 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::generateFooter (SuiCreatePageMessage * message, int type)
Definition at line 1342 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::generateHeader (SuiCreatePageMessage * message)
Definition at line 1334 of file SuiBox.cpp.
Referenced by invokeMethod().
BaseMessage * SuiBoxAdapter::generateMessage ()
Definition at line 1346 of file SuiBox.cpp.
Referenced by invokeMethod().
unsigned int SuiBoxAdapter::getBoxID ()
Definition at line 1454 of file SuiBox.cpp.
Referenced by invokeMethod().
ManagedWeakReference< CreatureObject * > SuiBoxAdapter::getPlayer ()
Definition at line 1450 of file SuiBox.cpp.
Referenced by invokeMethod().
String SuiBoxAdapter::getPromptTitle ()
Definition at line 1382 of file SuiBox.cpp.
Referenced by invokeMethod().
ManagedWeakReference< SceneObject * > SuiBoxAdapter::getUsingObject ()
Definition at line 1462 of file SuiBox.cpp.
Referenced by invokeMethod().
int SuiBoxAdapter::getWindowType ()
Definition at line 1458 of file SuiBox.cpp.
Referenced by invokeMethod().
bool SuiBoxAdapter::hasGeneratedMessage ()
Definition at line 1370 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::initialize ()
Definition at line 1322 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::initializeTransientMembers ()
Definition at line 1330 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1120 of file SuiBox.cpp.
References addHeader(), addSetting(), clearOptions(), compareTo(), finalize(), generateBody(), generateCloseMessage(), generateFooter(), generateHeader(), generateMessage(), getBoxID(), getPlayer(), getPromptTitle(), getUsingObject(), getWindowType(), hasGeneratedMessage(), initialize(), initializeTransientMembers(), isBankTransferBox(), isCharacterBuilderBox(), isColorPicker(), isInputBox(), isListBox(), isMessageBox(), isSlicingBox(), isTransferBox(), RPC_ADDHEADER__STRING_STRING_, RPC_ADDSETTING__STRING_STRING_STRING_STRING_, RPC_CLEAROPTIONS__, RPC_COMPARETO__SUIBOX_, RPC_FINALIZE__, RPC_GENERATEBODY__SUICREATEPAGEMESSAGE_, RPC_GENERATECLOSEMESSAGE__, RPC_GENERATEFOOTER__SUICREATEPAGEMESSAGE_INT_, RPC_GENERATEHEADER__SUICREATEPAGEMESSAGE_, RPC_GENERATEMESSAGE__, RPC_GETBOXID__, RPC_GETPLAYER__, RPC_GETPROMPTTITLE__, RPC_GETUSINGOBJECT__, RPC_GETWINDOWTYPE__, RPC_HASGENERATEDMESSAGE__, RPC_INITIALIZE__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_ISBANKTRANSFERBOX__, RPC_ISCHARACTERBUILDERBOX__, RPC_ISCOLORPICKER__, RPC_ISINPUTBOX__, RPC_ISLISTBOX__, RPC_ISMESSAGEBOX__, RPC_ISSLICINGBOX__, RPC_ISTRANSFERBOX__, RPC_SETBOXTYPE__INT_, RPC_SETCANCELBUTTON__BOOL_STRING_, RPC_SETFORCECLOSEDISABLED__, RPC_SETFORCECLOSEDISTANCE__FLOAT_, RPC_SETHANDLERTEXT__STRING_, RPC_SETOKBUTTON__BOOL_STRING_, RPC_SETOTHERBUTTON__BOOL_STRING_, RPC_SETPROMPTTEXT__STRING_, RPC_SETPROMPTTITLE__STRING_, RPC_SETUSINGOBJECT__SCENEOBJECT_, RPC_SETWINDOWTYPE__INT_, setBoxType(), setCancelButton(), setForceCloseDisabled(), setForceCloseDistance(), setHandlerText(), setOkButton(), setOtherButton(), setPromptText(), setPromptTitle(), setUsingObject(), and setWindowType().
bool SuiBoxAdapter::isBankTransferBox ()
Definition at line 1414 of file SuiBox.cpp.
Referenced by invokeMethod().
bool SuiBoxAdapter::isCharacterBuilderBox ()
Definition at line 1422 of file SuiBox.cpp.
Referenced by invokeMethod().
bool SuiBoxAdapter::isColorPicker ()
Definition at line 1426 of file SuiBox.cpp.
Referenced by invokeMethod().
bool SuiBoxAdapter::isInputBox ()
Definition at line 1398 of file SuiBox.cpp.
Referenced by invokeMethod().
bool SuiBoxAdapter::isListBox ()
Definition at line 1402 of file SuiBox.cpp.
Referenced by invokeMethod().
bool SuiBoxAdapter::isMessageBox ()
Definition at line 1406 of file SuiBox.cpp.
Referenced by invokeMethod().
bool SuiBoxAdapter::isSlicingBox ()
Definition at line 1418 of file SuiBox.cpp.
Referenced by invokeMethod().
bool SuiBoxAdapter::isTransferBox ()
Definition at line 1410 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::setBoxType (int type)
Definition at line 1394 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::setCancelButton (bool value, const String & cancelText)
Definition at line 1430 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::setForceCloseDisabled ()
Definition at line 1446 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::setForceCloseDistance (float dist)
Definition at line 1442 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::setHandlerText (const String & text)
Definition at line 1386 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::setOkButton (bool value, const String & okText)
Definition at line 1438 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::setOtherButton (bool value, const String & backText)
Definition at line 1434 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::setPromptText (const String & name)
Definition at line 1378 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::setPromptTitle (const String & name)
Definition at line 1374 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::setUsingObject (SceneObject * object)
Definition at line 1466 of file SuiBox.cpp.
Referenced by invokeMethod().
void SuiBoxAdapter::setWindowType (unsigned int type)
Definition at line 1390 of file SuiBox.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/SuiBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/SuiBox.cpp