Core3: server::zone::managers::city::CityManagerAdapter Class Reference
server::zone::managers::city::CityManagerAdapter Class Reference
#include <CityManager.h>
Public Member Functions
CityManagerAdapter (CityManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void loadLuaConfig ()
void loadCityRegions ()
bool validateCityName (const String &name)
bool isCityInRange (Zone *zone, float x, float y)
CityRegion * createCity (CreatureObject *mayor, const String &cityName, float x, float y)
void processCityUpdate (CityRegion *city)
void processIncomeTax (CityRegion *city)
void updateCityVoting (CityRegion *city, bool override)
void deductCityMaintenance (CityRegion *city)
int collectNonStructureMaintenance (SceneObject *object, CityRegion *city, int maintenanceDue)
int collectCivicStructureMaintenance (StructureObject *structure, CityRegion *city, int maintenanceDue)
void sendMaintenanceEmail (CityRegion *city, int maintenancePaid)
void sendMaintenanceDecayEmail (CityRegion *city, StructureObject *structure, int maintenanceDue)
void sendMaintenanceDestroyEmail (CityRegion *city, StructureObject *structure)
void sendMaintenanceRepairEmail (CityRegion *city, StructureObject *structure)
void contractCity (CityRegion *city)
void expandCity (CityRegion *city)
void destroyCity (CityRegion *city)
void sendStatusReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void promptCitySpecialization (CityRegion *city, CreatureObject *mayor, SceneObject *terminal)
void changeCitySpecialization (CityRegion *city, CreatureObject *mayor, const String &spec)
void promptWithdrawCityTreasury (CityRegion *city, CreatureObject *mayor, SceneObject *terminal)
void promptDepositCityTreasury (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void withdrawFromCityTreasury (CityRegion *city, CreatureObject *mayor, int value, const String &reason, SceneObject *terminal)
void depositToCityTreasury (CityRegion *city, CreatureObject *creature, int value)
void sendTreasuryReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void sendCitizenshipReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void registerCitizen (CityRegion *city, CreatureObject *creature)
void unregisterCitizen (CityRegion *city, CreatureObject *creature, bool inactive)
void sendManageMilitia (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void promptAddMilitiaMember (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void addMilitiaMember (CityRegion *city, CreatureObject *mayor, const String &playerName)
void removeMilitiaMember (CityRegion *city, CreatureObject *mayor, unsigned long long militiaid)
void sendCityAdvancement (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void promptRegisterCity (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void promptUnregisterCity (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void registerCity (CityRegion *city, CreatureObject *mayor)
void unregisterCity (CityRegion *city, CreatureObject *mayor)
void promptAdjustTaxes (CityRegion *city, CreatureObject *mayor, SceneObject *terminal)
void promptSetTax (CityRegion *city, CreatureObject *mayor, int selectedTax, SceneObject *terminal)
void setTax (CityRegion *city, CreatureObject *mayor, int selectedTax, int value)
void sendMaintenanceReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
bool containsCityName (const String &name)
bool isCityRankCapped (const String &planetName, byte cityRank)
void sendCityReport (CreatureObject *creature, const String &planetName, byte rank)
bool validateCityInRange (CreatureObject *creature, Zone *zone, float x, float y)
void toggleZoningEnabled (CityRegion *city, CreatureObject *mayor)
int getTotalCities ()
bool renameCity (CityRegion *city, const String &newName)
void sendMayoralStandings (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void promptMayoralVote (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void registerForMayoralRace (CityRegion *city, CreatureObject *creature)
void castMayoralVote (CityRegion *city, CreatureObject *creature, unsigned long long oid)
void sendStructureReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal)
void fixMayor (CityRegion *city, CreatureObject *mayor)
bool canSupportMoreDecorations (CityRegion *city)
void sendChangeCityName (CityRegion *city, CreatureObject *mayor)
Detailed Description
Definition at line 565 of file CityManager.h.
Constructor & Destructor Documentation
CityManagerAdapter::CityManagerAdapter (CityManager * impl)
Definition at line 1151 of file CityManager.cpp.
Member Function Documentation
void CityManagerAdapter::addMilitiaMember (CityRegion * city, CreatureObject * mayor, const String & playerName)
Definition at line 1581 of file CityManager.cpp.
Referenced by invokeMethod().
bool CityManagerAdapter::canSupportMoreDecorations (CityRegion * city)
Definition at line 1677 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::castMayoralVote (CityRegion * city, CreatureObject * creature, unsigned long long oid)
Definition at line 1665 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::changeCitySpecialization (CityRegion * city, CreatureObject * mayor, const String & spec)
Definition at line 1537 of file CityManager.cpp.
Referenced by invokeMethod().
int CityManagerAdapter::collectCivicStructureMaintenance (StructureObject * structure, CityRegion * city, int maintenanceDue)
Definition at line 1497 of file CityManager.cpp.
Referenced by invokeMethod().
int CityManagerAdapter::collectNonStructureMaintenance (SceneObject * object, CityRegion * city, int maintenanceDue)
Definition at line 1493 of file CityManager.cpp.
Referenced by invokeMethod().
bool CityManagerAdapter::containsCityName (const String & name)
Definition at line 1625 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::contractCity (CityRegion * city)
Definition at line 1517 of file CityManager.cpp.
Referenced by invokeMethod().
CityRegion * CityManagerAdapter::createCity (CreatureObject * mayor, const String & cityName, float x, float y)
Definition at line 1473 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::deductCityMaintenance (CityRegion * city)
Definition at line 1489 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::depositToCityTreasury (CityRegion * city, CreatureObject * creature, int value)
Definition at line 1553 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::destroyCity (CityRegion * city)
Definition at line 1525 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::expandCity (CityRegion * city)
Definition at line 1521 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::fixMayor (CityRegion * city, CreatureObject * mayor)
Definition at line 1673 of file CityManager.cpp.
Referenced by invokeMethod().
int CityManagerAdapter::getTotalCities ()
Definition at line 1645 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1154 of file CityManager.cpp.
References addMilitiaMember(), canSupportMoreDecorations(), castMayoralVote(), changeCitySpecialization(), collectCivicStructureMaintenance(), collectNonStructureMaintenance(), containsCityName(), contractCity(), createCity(), deductCityMaintenance(), depositToCityTreasury(), destroyCity(), expandCity(), fixMayor(), getTotalCities(), isCityInRange(), isCityRankCapped(), loadCityRegions(), loadLuaConfig(), processCityUpdate(), processIncomeTax(), promptAddMilitiaMember(), promptAdjustTaxes(), promptCitySpecialization(), promptDepositCityTreasury(), promptMayoralVote(), promptRegisterCity(), promptSetTax(), promptUnregisterCity(), promptWithdrawCityTreasury(), registerCitizen(), registerCity(), registerForMayoralRace(), removeMilitiaMember(), renameCity(), RPC_ADDMILITIAMEMBER__CITYREGION_CREATUREOBJECT_STRING_, RPC_CANSUPPORTMOREDECORATIONS__CITYREGION_, RPC_CASTMAYORALVOTE__CITYREGION_CREATUREOBJECT_LONG_, RPC_CHANGECITYSPECIALIZATION__CITYREGION_CREATUREOBJECT_STRING_, RPC_COLLECTCIVICSTRUCTUREMAINTENANCE__STRUCTUREOBJECT_CITYREGION_INT_, RPC_COLLECTNONSTRUCTUREMAINTENANCE__SCENEOBJECT_CITYREGION_INT_, RPC_CONTAINSCITYNAME__STRING_, RPC_CONTRACTCITY__CITYREGION_, RPC_CREATECITY__CREATUREOBJECT_STRING_FLOAT_FLOAT_, RPC_DEDUCTCITYMAINTENANCE__CITYREGION_, RPC_DEPOSITTOCITYTREASURY__CITYREGION_CREATUREOBJECT_INT_, RPC_DESTROYCITY__CITYREGION_, RPC_EXPANDCITY__CITYREGION_, RPC_FIXMAYOR__CITYREGION_CREATUREOBJECT_, RPC_GETTOTALCITIES__, RPC_ISCITYINRANGE__ZONE_FLOAT_FLOAT_, RPC_ISCITYRANKCAPPED__STRING_BYTE_, RPC_LOADCITYREGIONS__, RPC_LOADLUACONFIG__, RPC_PROCESSCITYUPDATE__CITYREGION_, RPC_PROCESSINCOMETAX__CITYREGION_, RPC_PROMPTADDMILITIAMEMBER__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_PROMPTADJUSTTAXES__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_PROMPTCITYSPECIALIZATION__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_PROMPTDEPOSITCITYTREASURY__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_PROMPTMAYORALVOTE__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_PROMPTREGISTERCITY__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_PROMPTSETTAX__CITYREGION_CREATUREOBJECT_INT_SCENEOBJECT_, RPC_PROMPTUNREGISTERCITY__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_PROMPTWITHDRAWCITYTREASURY__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_REGISTERCITIZEN__CITYREGION_CREATUREOBJECT_, RPC_REGISTERCITY__CITYREGION_CREATUREOBJECT_, RPC_REGISTERFORMAYORALRACE__CITYREGION_CREATUREOBJECT_, RPC_REMOVEMILITIAMEMBER__CITYREGION_CREATUREOBJECT_LONG_, RPC_RENAMECITY__CITYREGION_STRING_, RPC_SENDCHANGECITYNAME__CITYREGION_CREATUREOBJECT_, RPC_SENDCITIZENSHIPREPORT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_SENDCITYADVANCEMENT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_SENDCITYREPORT__CREATUREOBJECT_STRING_BYTE_, RPC_SENDMAINTENANCEDECAYEMAIL__CITYREGION_STRUCTUREOBJECT_INT_, RPC_SENDMAINTENANCEDESTROYEMAIL__CITYREGION_STRUCTUREOBJECT_, RPC_SENDMAINTENANCEEMAIL__CITYREGION_INT_, RPC_SENDMAINTENANCEREPAIREMAIL__CITYREGION_STRUCTUREOBJECT_, RPC_SENDMAINTENANCEREPORT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_SENDMANAGEMILITIA__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_SENDMAYORALSTANDINGS__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_SENDSTATUSREPORT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_SENDSTRUCTUREREPORT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_SENDTREASURYREPORT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, RPC_SETTAX__CITYREGION_CREATUREOBJECT_INT_INT_, RPC_TOGGLEZONINGENABLED__CITYREGION_CREATUREOBJECT_, RPC_UNREGISTERCITIZEN__CITYREGION_CREATUREOBJECT_BOOL_, RPC_UNREGISTERCITY__CITYREGION_CREATUREOBJECT_, RPC_UPDATECITYVOTING__CITYREGION_BOOL_, RPC_VALIDATECITYINRANGE__CREATUREOBJECT_ZONE_FLOAT_FLOAT_, RPC_VALIDATECITYNAME__STRING_, RPC_WITHDRAWFROMCITYTREASURY__CITYREGION_CREATUREOBJECT_INT_STRING_SCENEOBJECT_, sendChangeCityName(), sendCitizenshipReport(), sendCityAdvancement(), sendCityReport(), sendMaintenanceDecayEmail(), sendMaintenanceDestroyEmail(), sendMaintenanceEmail(), sendMaintenanceRepairEmail(), sendMaintenanceReport(), sendManageMilitia(), sendMayoralStandings(), sendStatusReport(), sendStructureReport(), sendTreasuryReport(), setTax(), toggleZoningEnabled(), unregisterCitizen(), unregisterCity(), updateCityVoting(), validateCityInRange(), validateCityName(), and withdrawFromCityTreasury().
bool CityManagerAdapter::isCityInRange (Zone * zone, float x, float y)
Definition at line 1469 of file CityManager.cpp.
Referenced by invokeMethod().
bool CityManagerAdapter::isCityRankCapped (const String & planetName, byte cityRank)
Definition at line 1629 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::loadCityRegions ()
Definition at line 1461 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::loadLuaConfig ()
Definition at line 1457 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::processCityUpdate (CityRegion * city)
Definition at line 1477 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::processIncomeTax (CityRegion * city)
Definition at line 1481 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::promptAddMilitiaMember (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1577 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::promptAdjustTaxes (CityRegion * city, CreatureObject * mayor, SceneObject * terminal)
Definition at line 1609 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::promptCitySpecialization (CityRegion * city, CreatureObject * mayor, SceneObject * terminal)
Definition at line 1533 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::promptDepositCityTreasury (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1545 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::promptMayoralVote (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1657 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::promptRegisterCity (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1593 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::promptSetTax (CityRegion * city, CreatureObject * mayor, int selectedTax, SceneObject * terminal)
Definition at line 1613 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::promptUnregisterCity (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1597 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::promptWithdrawCityTreasury (CityRegion * city, CreatureObject * mayor, SceneObject * terminal)
Definition at line 1541 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::registerCitizen (CityRegion * city, CreatureObject * creature)
Definition at line 1565 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::registerCity (CityRegion * city, CreatureObject * mayor)
Definition at line 1601 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::registerForMayoralRace (CityRegion * city, CreatureObject * creature)
Definition at line 1661 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::removeMilitiaMember (CityRegion * city, CreatureObject * mayor, unsigned long long militiaid)
Definition at line 1585 of file CityManager.cpp.
Referenced by invokeMethod().
bool CityManagerAdapter::renameCity (CityRegion * city, const String & newName)
Definition at line 1649 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendChangeCityName (CityRegion * city, CreatureObject * mayor)
Definition at line 1681 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendCitizenshipReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1561 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendCityAdvancement (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1589 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendCityReport (CreatureObject * creature, const String & planetName, byte rank)
Definition at line 1633 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendMaintenanceDecayEmail (CityRegion * city, StructureObject * structure, int maintenanceDue)
Definition at line 1505 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendMaintenanceDestroyEmail (CityRegion * city, StructureObject * structure)
Definition at line 1509 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendMaintenanceEmail (CityRegion * city, int maintenancePaid)
Definition at line 1501 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendMaintenanceRepairEmail (CityRegion * city, StructureObject * structure)
Definition at line 1513 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendMaintenanceReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1621 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendManageMilitia (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1573 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendMayoralStandings (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1653 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendStatusReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1529 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendStructureReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1669 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::sendTreasuryReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal)
Definition at line 1557 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::setTax (CityRegion * city, CreatureObject * mayor, int selectedTax, int value)
Definition at line 1617 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::toggleZoningEnabled (CityRegion * city, CreatureObject * mayor)
Definition at line 1641 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::unregisterCitizen (CityRegion * city, CreatureObject * creature, bool inactive)
Definition at line 1569 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::unregisterCity (CityRegion * city, CreatureObject * mayor)
Definition at line 1605 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::updateCityVoting (CityRegion * city, bool override)
Definition at line 1485 of file CityManager.cpp.
Referenced by invokeMethod().
bool CityManagerAdapter::validateCityInRange (CreatureObject * creature, Zone * zone, float x, float y)
Definition at line 1637 of file CityManager.cpp.
Referenced by invokeMethod().
bool CityManagerAdapter::validateCityName (const String & name)
Definition at line 1465 of file CityManager.cpp.
Referenced by invokeMethod().
void CityManagerAdapter::withdrawFromCityTreasury (CityRegion * city, CreatureObject * mayor, int value, const String & reason, SceneObject * terminal)
Definition at line 1549 of file CityManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/city/CityManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/city/CityManager.cpp