Core3: AiStateComponent Class Reference
AiStateComponent Class Reference
#include <AiStateComponent.h>
Public Member Functions
virtual void notifyPositionUpdate (Observable *obs, QuadTreeEntry *entry)
void notifyDespawn (AiActor *actor, Zone *zone)
virtual void doAwarenessCheck (Observable *obs, Coordinate &start, uint64 time, CreatureObject *target)
virtual uint16 onEnter (AiActor *actor)
virtual void onExit (AiActor *actor)
virtual uint16 tryRetreat (AiActor *actor)
virtual uint16 doRecovery (AiActor *actor)
virtual uint16 doAttack (AiActor *actor)
virtual uint16 doMovement (AiActor *actor)
bool findNextPosition (Observable *obs, float maxDistance, float speed, PatrolPointsVector *patrolPoints, WorldCoordinates *nextPosition)
virtual float getMaxDistance (CreatureObject *host)
virtual float getSpeed (CreatureObject *host)
void setNextPosition (AiActor *actor, float x, float z, float y, SceneObject *cell=NULL)
void updateCurrentPosition (CreatureObject *host, PatrolPoint *pos)
void broadcastNextPositionUpdate (CreatureObject *host, PatrolPoint *point)
void checkNewAngle (AiActor *actor)
void sendConversationStartTo (CreatureObject *host, SceneObject *player)
void selectWeapon (AiActor *actor)
bool validateStateAttack (CreatureObject *target, String &args)
virtual bool isScared (CreatureObject *host, SceneObject *followObject)
Detailed Description
Definition at line 36 of file AiStateComponent.h.
Member Function Documentation
void AiStateComponent::broadcastNextPositionUpdate (CreatureObject * host, PatrolPoint * point)
Definition at line 330 of file AiStateComponent.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), PatrolPoint::getCell(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getParent(), PatrolPoint::getPositionX(), PatrolPoint::getPositionY(), PatrolPoint::getPositionZ(), and server::zone::objects::scene::SceneObject::incrementMovementCounter().
Referenced by checkNewAngle(), doMovement(), and sendConversationStartTo().
void AiStateComponent::checkNewAngle (AiActor * actor)
Definition at line 349 of file AiStateComponent.cpp.
References broadcastNextPositionUpdate(), server::zone::objects::scene::SceneObject::faceObject(), server::zone::objects::creature::ai::AiActor::getFollowObject(), server::zone::objects::creature::ai::AiActor::getHost(), server::zone::objects::creature::ai::AiActor::getNextStepPosition(), and PatrolPoint::isReached().
Referenced by AlertStateComponent::doMovement().
uint16 AiStateComponent::doAttack (AiActor * actor) virtual
Definition at line 500 of file AiStateComponent.cpp.
virtual void AiStateComponent::doAwarenessCheck (Observable * obs, Coordinate & start, uint64 time, CreatureObject * target) inline virtual
Definition at line 47 of file AiStateComponent.h.
uint16 AiStateComponent::doMovement (AiActor * actor) virtual
Reimplemented in AttackStateComponent, AlertStateComponent, SpawnStateComponent, StandingStateComponent, RetreatStateComponent, FleeStateComponent, and DeathStateComponent.
Definition at line 504 of file AiStateComponent.cpp.
References server::zone::objects::creature::ai::AiActor::activateMovementEvent(), broadcastNextPositionUpdate(), findNextPosition(), WorldCoordinates::getCell(), server::zone::objects::creature::CreatureObject::getCurrentSpeed(), server::zone::objects::creature::ai::AiActor::getHost(), getMaxDistance(), server::zone::objects::creature::ai::AiActor::getNextStepPosition(), server::zone::objects::creature::ai::AiActor::getPatrolPoints(), getSpeed(), WorldCoordinates::getX(), WorldCoordinates::getY(), WorldCoordinates::getZ(), PatrolPoint::setCell(), PatrolPoint::setPosition(), PatrolPoint::setReached(), and updateCurrentPosition().
Referenced by FleeStateComponent::doMovement(), RetreatStateComponent::doMovement(), and AttackStateComponent::doMovement().
uint16 AiStateComponent::doRecovery (AiActor * actor) virtual
Reimplemented in SpawnStateComponent, WanderingStateComponent, RetreatStateComponent, AlertStateComponent, DeathStateComponent, StandingStateComponent, AttackStateComponent, and FleeStateComponent.
Definition at line 496 of file AiStateComponent.cpp.
bool AiStateComponent::findNextPosition (Observable * obs, float maxDistance, float speed, PatrolPointsVector * patrolPoints, WorldCoordinates * nextPosition)
Definition at line 92 of file AiStateComponent.cpp.
References CreateClientPathMessage::addCoordinate(), server::zone::ZoneServer::createObject(), CreatureState::FROZEN, WorldCoordinates::getCell(), PatrolPoint::getCoordinates(), server::zone::Zone::getHeight(), server::zone::objects::scene::SceneObject::getParent(), WorldCoordinates::getPoint(), WorldCoordinates::getWorldPosition(), PatrolPoint::getWorldPosition(), WorldCoordinates::getX(), WorldCoordinates::getY(), WorldCoordinates::getZ(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::getZoneServer(), CreatureState::IMMOBILIZED, WorldCoordinates::setCell(), WorldCoordinates::setX(), WorldCoordinates::setY(), WorldCoordinates::setZ(), server::zone::objects::scene::SceneObject::transferObject(), and PathFinderManager::transformToModelSpace().
Referenced by doMovement().
virtual float AiStateComponent::getMaxDistance (CreatureObject * host) inline virtual
Reimplemented in AttackStateComponent.
Definition at line 77 of file AiStateComponent.h.
Referenced by doMovement().
virtual float AiStateComponent::getSpeed (CreatureObject * host) inline virtual
Reimplemented in AttackStateComponent, WanderingStateComponent, RetreatStateComponent, and FleeStateComponent.
Definition at line 81 of file AiStateComponent.h.
References server::zone::objects::creature::CreatureObject::getCurrentSpeed().
Referenced by doMovement().
bool AiStateComponent::isScared (CreatureObject * host, SceneObject * followObject) virtual
Definition at line 462 of file AiStateComponent.cpp.
References server::zone::objects::scene::SceneObject::isCreatureObject().
Referenced by AlertStateComponent::doMovement(), and AlertStateComponent::doRecovery().
void AiStateComponent::notifyDespawn (AiActor * actor, Zone * zone)
Definition at line 35 of file AiStateComponent.cpp.
References server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::creature::ai::AiActor::getCreatureTemplate(), server::zone::objects::creature::ai::AiActor::getHost(), server::zone::objects::tangible::TangibleObject::getLevel(), server::zone::objects::creature::ai::AiActor::getMovementMarker(), server::zone::objects::creature::ai::AiActor::getMovementMarkersSize(), server::zone::objects::creature::ai::AiActor::getRespawnTimer(), server::zone::objects::creature::ai::AiActor::loadTemplateData(), server::zone::objects::creature::ai::AiActor::setFollowObject(), server::zone::objects::creature::ai::AiActor::setLevel(), server::zone::objects::creature::ai::AiActor::setTargetObject(), and CreaturePosture::UPRIGHT.
virtual void AiStateComponent::notifyPositionUpdate (Observable * obs, QuadTreeEntry * entry) inline virtual
Definition at line 43 of file AiStateComponent.h.
uint16 AiStateComponent::onEnter (AiActor * actor) virtual
Reimplemented in AttackStateComponent, SpawnStateComponent, WanderingStateComponent, AlertStateComponent, DeathStateComponent, StandingStateComponent, and RetreatStateComponent.
Definition at line 475 of file AiStateComponent.cpp.
References server::zone::objects::creature::ai::AiActor::activateMovementEvent(), server::zone::objects::creature::ai::AiActor::activateRecovery(), and server::zone::objects::creature::ai::AiActor::getHost().
virtual void AiStateComponent::onExit (AiActor * actor) inline virtual
Definition at line 58 of file AiStateComponent.h.
void AiStateComponent::selectWeapon (AiActor * actor)
Definition at line 386 of file AiStateComponent.cpp.
References server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::objects::creature::ai::AiActor::getFollowObject(), server::zone::objects::creature::ai::AiActor::getHost(), server::zone::objects::tangible::weapon::WeaponObject::getIdealRange(), server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::creature::ai::AiActor::getWeapons().
Referenced by AttackStateComponent::doRecovery().
void AiStateComponent::sendConversationStartTo (CreatureObject * host, SceneObject * player)
Definition at line 373 of file AiStateComponent.cpp.
References broadcastNextPositionUpdate(), server::zone::objects::scene::SceneObject::faceObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getParent(), and server::zone::objects::scene::SceneObject::sendMessage().
void AiStateComponent::setNextPosition (AiActor * actor, float x, float z, float y, SceneObject * cell = NULL)
Definition at line 312 of file AiStateComponent.cpp.
References server::zone::objects::creature::ai::AiActor::setNextPosition().
Referenced by FleeStateComponent::doMovement(), AttackStateComponent::doMovement(), RetreatStateComponent::onEnter(), and WanderingStateComponent::onEnter().
uint16 AiStateComponent::tryRetreat (AiActor * actor) virtual
Definition at line 492 of file AiStateComponent.cpp.
void AiStateComponent::updateCurrentPosition (CreatureObject * host, PatrolPoint * pos)
Definition at line 317 of file AiStateComponent.cpp.
References PatrolPoint::getCell(), server::zone::objects::scene::SceneObject::getParent(), PatrolPoint::getPositionX(), PatrolPoint::getPositionY(), PatrolPoint::getPositionZ(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::updateZone(), and server::zone::objects::scene::SceneObject::updateZoneWithParent().
Referenced by doMovement().
bool AiStateComponent::validateStateAttack (CreatureObject * target, String & args)
Definition at line 441 of file AiStateComponent.cpp.
References server::zone::objects::creature::CreatureObject::hasState(), server::zone::objects::creature::CreatureObject::isKnockedDown(), server::zone::objects::creature::CreatureObject::isProne(), and server::zone::objects::creature::CreatureObject::isStanding().
Referenced by AttackStateComponent::doRecovery().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/components/AiStateComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/components/AiStateComponent.cpp