Core3: DragIncapacitatedPlayerCommand Class Reference
DragIncapacitatedPlayerCommand Class Reference
#include <DragIncapacitatedPlayerCommand.h>
Public Member Functions
DragIncapacitatedPlayerCommand (const String &name, ZoneProcessServer *server)
void getCoordinate (SceneObject *object1, SceneObject *object2, float distanceFromObject1, WorldCoordinates *newPosition)
void drag (CreatureObject *player, CreatureObject *targetPlayer, float maxRange, float maxMovement, bool needsConsent, bool canDragLiveTarget)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Private Attributes
float maxRange
float maxMovement
bool needsConsent
Detailed Description
Definition at line 50 of file DragIncapacitatedPlayerCommand.h.
Constructor & Destructor Documentation
DragIncapacitatedPlayerCommand::DragIncapacitatedPlayerCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 55 of file DragIncapacitatedPlayerCommand.h.
References maxMovement, maxRange, and needsConsent.
Member Function Documentation
int DragIncapacitatedPlayerCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 205 of file DragIncapacitatedPlayerCommand.h.
References drag(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isHealableBy(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), maxMovement, maxRange, needsConsent, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
void DragIncapacitatedPlayerCommand::drag (CreatureObject * player, CreatureObject * targetPlayer, float maxRange, float maxMovement, bool needsConsent, bool canDragLiveTarget) inline
Definition at line 108 of file DragIncapacitatedPlayerCommand.h.
References WorldCoordinates::getCell(), getCoordinate(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getWorldPosition(), WorldCoordinates::getX(), WorldCoordinates::getY(), WorldCoordinates::getZ(), server::zone::objects::scene::SceneObject::incrementMovementCounter(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::SceneObject::setDirection(), server::zone::objects::scene::SceneObject::showFlyText(), server::zone::objects::scene::SceneObject::teleport(), server::zone::objects::scene::SceneObject::updateZone(), and server::zone::objects::scene::SceneObject::updateZoneWithParent().
Referenced by doQueueCommand().
void DragIncapacitatedPlayerCommand::getCoordinate (SceneObject * object1, SceneObject * object2, float distanceFromObject1, WorldCoordinates * newPosition) inline
Definition at line 63 of file DragIncapacitatedPlayerCommand.h.
References server::zone::objects::scene::SceneObject::getParent(), server::zone::Zone::getPlanetManager(), server::zone::objects::scene::SceneObject::getWorldPosition(), server::zone::objects::scene::SceneObject::getWorldPositionZ(), WorldCoordinates::getX(), WorldCoordinates::getY(), server::zone::objects::scene::SceneObject::getZone(), WorldCoordinates::setCell(), WorldCoordinates::setCoordinates(), WorldCoordinates::setX(), WorldCoordinates::setY(), WorldCoordinates::setZ(), and PathFinderManager::transformToModelSpace().
Referenced by drag().
Member Data Documentation
float DragIncapacitatedPlayerCommand::maxMovement private
Definition at line 51 of file DragIncapacitatedPlayerCommand.h.
Referenced by doQueueCommand(), and DragIncapacitatedPlayerCommand().
float DragIncapacitatedPlayerCommand::maxRange private
Definition at line 51 of file DragIncapacitatedPlayerCommand.h.
Referenced by doQueueCommand(), and DragIncapacitatedPlayerCommand().
bool DragIncapacitatedPlayerCommand::needsConsent private
Definition at line 52 of file DragIncapacitatedPlayerCommand.h.
Referenced by doQueueCommand(), and DragIncapacitatedPlayerCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/DragIncapacitatedPlayerCommand.h