Core3: PowerupStat Class Reference
PowerupStat Class Reference
#include <PowerupStat.h>
Public Member Functions
PowerupStat ()
PowerupStat (const PowerupStat &p)
PowerupStat (const String &att, const String &n, const String &p)
PowerupStat & operator= (const PowerupStat &p)
bool operator== (const PowerupStat &stat)
void addSerializableVariables ()
String getAttributeToModify ()
String getName ()
String getPupAttribute ()
float getValue ()
void setValue (float v)
Protected Attributes
String attributeToModify
String name
String pupAttribute
float value
Detailed Description
Definition at line 11 of file PowerupStat.h.
Constructor & Destructor Documentation
PowerupStat::PowerupStat () inline
Definition at line 19 of file PowerupStat.h.
References addSerializableVariables(), and value.
PowerupStat::PowerupStat (const PowerupStat & p) inline
Definition at line 25 of file PowerupStat.h.
References addSerializableVariables(), attributeToModify, name, pupAttribute, and value.
PowerupStat::PowerupStat (const String & att, const String & n, const String & p) inline
Definition at line 34 of file PowerupStat.h.
References addSerializableVariables(), attributeToModify, name, pupAttribute, and value.
Member Function Documentation
void PowerupStat::addSerializableVariables () inline
Definition at line 63 of file PowerupStat.h.
References attributeToModify, name, pupAttribute, and value.
Referenced by PowerupStat().
String PowerupStat::getAttributeToModify () inline
Definition at line 70 of file PowerupStat.h.
References attributeToModify.
Referenced by server::zone::objects::tangible::powerup::PowerupObjectImplementation::fillWeaponAttributeList(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::getPowerupStat().
String PowerupStat::getName () inline
Definition at line 74 of file PowerupStat.h.
References name.
Referenced by server::zone::objects::tangible::powerup::PowerupObjectImplementation::updateCraftingValues().
String PowerupStat::getPupAttribute () inline
Definition at line 78 of file PowerupStat.h.
References pupAttribute.
Referenced by server::zone::objects::tangible::powerup::PowerupObjectImplementation::fillAttributeList(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::fillWeaponAttributeList().
float PowerupStat::getValue () inline
Definition at line 82 of file PowerupStat.h.
References value.
Referenced by server::zone::objects::tangible::powerup::PowerupObjectImplementation::fillAttributeList(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::fillWeaponAttributeList(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::getPowerupStat(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::updateCraftingValues().
PowerupStat& PowerupStat::operator= (const PowerupStat & p) inline
Definition at line 43 of file PowerupStat.h.
References attributeToModify, name, pupAttribute, and value.
bool PowerupStat::operator== (const PowerupStat & stat) inline
Definition at line 55 of file PowerupStat.h.
References attributeToModify, name, and pupAttribute.
void PowerupStat::setValue (float v) inline
Definition at line 86 of file PowerupStat.h.
References value.
Referenced by server::zone::objects::tangible::powerup::PowerupObjectImplementation::updateCraftingValues().
Member Data Documentation
String PowerupStat::attributeToModify protected
Definition at line 13 of file PowerupStat.h.
Referenced by addSerializableVariables(), getAttributeToModify(), operator=(), operator==(), and PowerupStat().
String PowerupStat::name protected
Definition at line 14 of file PowerupStat.h.
Referenced by addSerializableVariables(), getName(), operator=(), operator==(), and PowerupStat().
String PowerupStat::pupAttribute protected
Definition at line 15 of file PowerupStat.h.
Referenced by addSerializableVariables(), getPupAttribute(), operator=(), operator==(), and PowerupStat().
float PowerupStat::value protected
Definition at line 16 of file PowerupStat.h.
Referenced by addSerializableVariables(), getValue(), operator=(), PowerupStat(), and setValue().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/powerup/PowerupStat.h