Core3: ResourceTreeEntry Class Reference
ResourceTreeEntry Class Reference
#include <ResourceTreeEntry.h>
Public Member Functions
ResourceTreeEntry (const String &inType)
~ResourceTreeEntry ()
void setMyNode (ResourceTreeNode *node)
ResourceTreeNode * getMyNode ()
void addClass (const String newclass)
void addStfClass (const String newclass)
String getClass (const int index)
String getStfClass (const int index)
int getClassCount ()
int getStfClassCount ()
String getFinalClass ()
bool isOrganic ()
void addAttribute (ResourceAttribute *attrib)
ResourceAttribute * getAttribute (const String &attrib)
ResourceAttribute * getAttribute (const int index)
int getAttributeCount ()
int getMaxpool () const
int getMaxtype () const
int getMinpool () const
int getMintype () const
String getType () const
String getRandomNameClass () const
String & getZoneRestriction ()
bool isRecycled () const
String getResourceContainerType () const
void setMaxpool (int maxpool)
void setMaxtype (int maxtype)
void setMinpool (int minpool)
void setMintype (int mintype)
void setType (String name)
void setRandomNameClass (String randomNameClass)
void setRecycled (bool recycled)
void setResourceContainerType (String resourceContainerType)
bool hasChildren ()
void setChildren (bool child)
void setZoneRestriction (String zone)
bool isZoneRestricted ()
void setJTL (bool j)
bool isJTL ()
void setSurveyToolType (int type)
int getSurveyToolType ()
void setRecycleToolType (int type)
int getRecycleToolType ()
uint32 getContainerCRC ()
bool isType (String type)
void toString ()
Private Attributes
ResourceTreeNode * myNode
Node that this entry is on.
String type
Stf type.
Vector< String > classList
List of Class names in plain english Format.
Vector< String > stfClassList
List of Class names in swg stfname.
VectorMap< String,
ResourceAttribute * > attributeMap
List of Attributes.
int maxtype
Maximum of this type that can spawn.
int mintype
Minimum of this type that can spawn.
int minpool
Minimum number of resource pools this spawns in.
int maxpool
Maximum number of resource pools this spawns in.
bool recycled
If type is a recycled type.
bool children
Notates if this entry has children.
String zoneRestriction
Notates id this resource is restricted to a zone.
bool jtl
Lets us know if this resource was a JTL resource.
String resourceContainerType
The script that explains the resource container type.
String randomNameClass
Unused, but in the resource tree.
int surveyToolType
The type of survey tool that can survey this.
int recycleToolType
The recyler setting that can recycle this.
uint32 containerCRC
CRC of resourceContainerType.
Detailed Description
Definition at line 64 of file ResourceTreeEntry.h.
Constructor & Destructor Documentation
ResourceTreeEntry::ResourceTreeEntry (const String & inType) inline
Constructor
Parameters
inType The type of resource this in in stfname
Definition at line 125 of file ResourceTreeEntry.h.
References attributeMap, children, containerCRC, jtl, maxpool, maxtype, minpool, mintype, myNode, randomNameClass, recycled, recycleToolType, resourceContainerType, surveyToolType, type, and zoneRestriction.
ResourceTreeEntry::~ResourceTreeEntry () inline
Deconstructor
Definition at line 156 of file ResourceTreeEntry.h.
References attributeMap, classList, and stfClassList.
Member Function Documentation
void ResourceTreeEntry::addAttribute (ResourceAttribute * attrib) inline
Adds an attribute to this entry
Parameters
attrib ResourceAttribute to add
Definition at line 262 of file ResourceTreeEntry.h.
References attributeMap, and ResourceAttribute::getName().
Referenced by ResourceTree::buildTreeFromClient().
void ResourceTreeEntry::addClass (const String newclass) inline
Adds class to classList
Parameters
newclass New class string to add
Definition at line 183 of file ResourceTreeEntry.h.
References classList.
Referenced by ResourceTree::buildTreeFromClient().
void ResourceTreeEntry::addStfClass (const String newclass) inline
Adds stfClass to stfClassList
Parameters
newclass New class string to add
Definition at line 191 of file ResourceTreeEntry.h.
References stfClassList.
Referenced by ResourceTree::buildTreeFromClient().
ResourceAttribute* ResourceTreeEntry::getAttribute (const String & attrib) inline
Gets attribute
Parameters
index index of attribute
Returns
ResourceAttibute at index
Definition at line 271 of file ResourceTreeEntry.h.
References attributeMap.
Referenced by ResourceSpawner::createRecycledResourceSpawn(), and ResourceSpawner::createResourceSpawn().
ResourceAttribute* ResourceTreeEntry::getAttribute (const int index) inline
Gets attribute
Parameters
index index of attribute
Returns
ResourceAttibute at index
Definition at line 280 of file ResourceTreeEntry.h.
References attributeMap.
int ResourceTreeEntry::getAttributeCount () inline
Gets number of attributes
Returns
Number of attributes
Definition at line 288 of file ResourceTreeEntry.h.
References attributeMap.
Referenced by ResourceSpawner::createRecycledResourceSpawn(), and ResourceSpawner::createResourceSpawn().
String ResourceTreeEntry::getClass (const int index) inline
Gets class based in Vector index
Parameters
index index
Returns
Class at index
Definition at line 201 of file ResourceTreeEntry.h.
References classList.
Referenced by ResourceTreeNode::add(), ResourceSpawner::createRecycledResourceSpawn(), and ResourceSpawner::createResourceSpawn().
int ResourceTreeEntry::getClassCount () inline
Gets size on classList
Returns
classList size
Definition at line 224 of file ResourceTreeEntry.h.
References classList.
Referenced by ResourceTreeNode::add(), ResourceSpawner::createRecycledResourceSpawn(), and ResourceSpawner::createResourceSpawn().
uint32 ResourceTreeEntry::getContainerCRC () inline
Gets containerCRC
Returns
containerCRC
Definition at line 529 of file ResourceTreeEntry.h.
References containerCRC.
Referenced by ResourceSpawner::createRecycledResourceSpawn(), and ResourceSpawner::createResourceSpawn().
String ResourceTreeEntry::getFinalClass () inline
Gets the Final Class name
Returns
Final name of entry
Definition at line 240 of file ResourceTreeEntry.h.
References classList.
Referenced by ResourceTreeNode::add(), ResourceSpawner::addParentNodeToListBox(), ResourceTreeNode::addToSuiListBox(), ResourceSpawner::createRecycledResourceSpawn(), ResourceTreeNode::find(), and ResourceSpawner::getRecycledVersion().
int ResourceTreeEntry::getMaxpool () const inline
Gets maxpool
Returns
maxpool
Definition at line 296 of file ResourceTreeEntry.h.
References maxpool.
Referenced by ResourceSpawner::createResourceSpawn().
int ResourceTreeEntry::getMaxtype () const inline
Gets maxtype
Returns
maxtype
Definition at line 305 of file ResourceTreeEntry.h.
References maxtype.
int ResourceTreeEntry::getMinpool () const inline
Gets minpool
Returns
minpool
Definition at line 314 of file ResourceTreeEntry.h.
References minpool.
Referenced by ResourceSpawner::createResourceSpawn().
int ResourceTreeEntry::getMintype () const inline
Gets mintype
Returns
mintype
Definition at line 323 of file ResourceTreeEntry.h.
References mintype.
ResourceTreeNode* ResourceTreeEntry::getMyNode () inline
Gets the node this entry is on
Returns
Node this entry is on
Definition at line 175 of file ResourceTreeEntry.h.
References myNode.
Referenced by ResourceSpawner::addParentNodeToListBox(), and ResourceTreeNode::getEntry().
String ResourceTreeEntry::getRandomNameClass () const inline
Gets randomNameClass
Returns
randomNameClass
Definition at line 341 of file ResourceTreeEntry.h.
References randomNameClass.
int ResourceTreeEntry::getRecycleToolType () inline
Gets recycleToolType
Returns
recycleToolType
Definition at line 521 of file ResourceTreeEntry.h.
References recycleToolType.
Referenced by ResourceSpawner::getRecycledVersion(), and ResourceSpawner::sendResourceRecycleType().
String ResourceTreeEntry::getResourceContainerType () const inline
Gets resourceContainerType
Returns
resourceContainerType
Definition at line 367 of file ResourceTreeEntry.h.
References resourceContainerType.
String ResourceTreeEntry::getStfClass (const int index) inline
Gets stfClass based on vector index
Parameters
index index
Returns
StfClass at index
Definition at line 213 of file ResourceTreeEntry.h.
References stfClassList.
Referenced by ResourceSpawner::createRecycledResourceSpawn(), and ResourceSpawner::createResourceSpawn().
int ResourceTreeEntry::getStfClassCount () inline
Gets size of stfClassList
Returns
stfClassList size
Definition at line 232 of file ResourceTreeEntry.h.
References stfClassList.
Referenced by ResourceSpawner::createRecycledResourceSpawn(), and ResourceSpawner::createResourceSpawn().
int ResourceTreeEntry::getSurveyToolType () inline
Gets surveyToolType
Returns
surveyToolType
Definition at line 505 of file ResourceTreeEntry.h.
References surveyToolType.
Referenced by ResourceSpawner::createRecycledResourceSpawn(), and ResourceSpawner::createResourceSpawn().
String ResourceTreeEntry::getType () const inline
Gets type
Returns
type
Definition at line 332 of file ResourceTreeEntry.h.
References type.
Referenced by ResourceTreeNode::add(), ResourceSpawner::createRecycledResourceSpawn(), ResourceSpawner::createResourceSpawn(), ResourceTreeNode::find(), ResourceTreeNode::getPlanetSpecificEntry(), ResourceTree::setJtl(), ResourceTree::setRecycled(), ResourceTree::setSurveyToolType(), and ResourceTree::setZoneRestriction().
String& ResourceTreeEntry::getZoneRestriction () inline
Gets zoneRestriction
Returns
zoneRestriction
Definition at line 350 of file ResourceTreeEntry.h.
References zoneRestriction.
Referenced by ResourceSpawner::createRecycledResourceSpawn(), and ResourceSpawner::createResourceSpawn().
bool ResourceTreeEntry::hasChildren () inline
Does entry have children
Returns
children
Definition at line 449 of file ResourceTreeEntry.h.
References children.
Referenced by ResourceTreeNode::addToSuiListBox(), ResourceTreeNode::getEntry(), and ResourceTreeNode::getEntryPool().
bool ResourceTreeEntry::isJTL () inline
Is JTL?
Returns
is Jtl resource
Definition at line 489 of file ResourceTreeEntry.h.
References jtl.
Referenced by ResourceSpawner::createResourceSpawn(), and ResourceSpawner::getRandomExpirationTime().
bool ResourceTreeEntry::isOrganic () inline
Denotes if entry is organic
Returns
Is value organic
Definition at line 251 of file ResourceTreeEntry.h.
References classList.
Referenced by ResourceSpawner::createResourceSpawn(), and ResourceSpawner::getRandomExpirationTime().
bool ResourceTreeEntry::isRecycled () const inline
Gets recycled
Returns
recycled
Definition at line 358 of file ResourceTreeEntry.h.
References recycled.
Referenced by ResourceTreeNode::addToSuiListBox(), and ResourceTreeNode::getEntryPool().
bool ResourceTreeEntry::isType (String type) inline
Tells us is Entry if of type
Parameters
type
Definition at line 537 of file ResourceTreeEntry.h.
References classList, stfClassList, and type.
Referenced by ResourceTreeNode::getEntryPool(), ResourceTree::setRecycleToolType(), and ResourceTree::setSurveyToolType().
bool ResourceTreeEntry::isZoneRestricted () inline
Lets us know if it is zonerestricted type
Returns
isZoneRestricted
Definition at line 473 of file ResourceTreeEntry.h.
References zoneRestriction.
void ResourceTreeEntry::setChildren (bool child) inline
sets children
Parameters
child
Definition at line 457 of file ResourceTreeEntry.h.
References children.
Referenced by ResourceTreeNode::add().
void ResourceTreeEntry::setJTL (bool j) inline
sets jtl
Parameters
j
Definition at line 481 of file ResourceTreeEntry.h.
References jtl.
Referenced by ResourceTree::setJtl().
void ResourceTreeEntry::setMaxpool (int maxpool) inline
sets maxpool
Parameters
maxpool
Definition at line 376 of file ResourceTreeEntry.h.
References maxpool.
Referenced by ResourceTree::buildTreeFromClient().
void ResourceTreeEntry::setMaxtype (int maxtype) inline
sets maxtype
Parameters
maxtype
Definition at line 385 of file ResourceTreeEntry.h.
References maxtype.
Referenced by ResourceTree::buildTreeFromClient().
void ResourceTreeEntry::setMinpool (int minpool) inline
sets minpool
Parameters
minpool
Definition at line 394 of file ResourceTreeEntry.h.
References minpool.
Referenced by ResourceTree::buildTreeFromClient().
void ResourceTreeEntry::setMintype (int mintype) inline
sets mintype
Parameters
mintype
Definition at line 403 of file ResourceTreeEntry.h.
References mintype.
Referenced by ResourceTree::buildTreeFromClient().
void ResourceTreeEntry::setMyNode (ResourceTreeNode * node) inline
Sets the node this entry is on
Parameters
node Tree Node
Definition at line 167 of file ResourceTreeEntry.h.
References myNode.
Referenced by ResourceTreeNode::add().
void ResourceTreeEntry::setRandomNameClass (String randomNameClass) inline
sets randomNameClass
Parameters
randomNameClass
Definition at line 421 of file ResourceTreeEntry.h.
References randomNameClass.
Referenced by ResourceTree::buildTreeFromClient().
void ResourceTreeEntry::setRecycled (bool recycled) inline
sets recycled
Parameters
recycled
Definition at line 430 of file ResourceTreeEntry.h.
References recycled.
Referenced by ResourceTree::buildTreeFromClient(), and ResourceTree::setRecycled().
void ResourceTreeEntry::setRecycleToolType (int type) inline
Sets recycleToolType
Parameters
type
Definition at line 513 of file ResourceTreeEntry.h.
References recycleToolType, and type.
Referenced by ResourceTree::setRecycleToolType().
void ResourceTreeEntry::setResourceContainerType (String resourceContainerType) inline
sets resourceContainerType
Parameters
resourceContainerType
Definition at line 439 of file ResourceTreeEntry.h.
References containerCRC, and resourceContainerType.
Referenced by ResourceTree::buildTreeFromClient().
void ResourceTreeEntry::setSurveyToolType (int type) inline
Sets surveyToolType
Parameters
type
Definition at line 497 of file ResourceTreeEntry.h.
References surveyToolType, and type.
Referenced by ResourceTree::setSurveyToolType().
void ResourceTreeEntry::setType (String name) inline
sets type
Parameters
type
Definition at line 412 of file ResourceTreeEntry.h.
References type.
void ResourceTreeEntry::setZoneRestriction (String zone) inline
sets zoneRestriction
Parameters
zone
Definition at line 465 of file ResourceTreeEntry.h.
References zoneRestriction.
Referenced by ResourceTree::setZoneRestriction().
void ResourceTreeEntry::toString () inline
Outputs visual representation of class
Definition at line 554 of file ResourceTreeEntry.h.
References attributeMap, classList, maxpool, maxtype, minpool, mintype, randomNameClass, recycled, resourceContainerType, stfClassList, surveyToolType, type, and zoneRestriction.
Member Data Documentation
VectorMap<String, ResourceAttribute* > ResourceTreeEntry::attributeMap private
List of Attributes.
Definition at line 80 of file ResourceTreeEntry.h.
Referenced by addAttribute(), getAttribute(), getAttributeCount(), ResourceTreeEntry(), toString(), and ~ResourceTreeEntry().
bool ResourceTreeEntry::children private
Notates if this entry has children.
Definition at line 97 of file ResourceTreeEntry.h.
Referenced by hasChildren(), ResourceTreeEntry(), and setChildren().
Vector<String> ResourceTreeEntry::classList private
List of Class names in plain english Format.
Definition at line 74 of file ResourceTreeEntry.h.
Referenced by addClass(), getClass(), getClassCount(), getFinalClass(), isOrganic(), isType(), toString(), and ~ResourceTreeEntry().
uint32 ResourceTreeEntry::containerCRC private
CRC of resourceContainerType.
Definition at line 118 of file ResourceTreeEntry.h.
Referenced by getContainerCRC(), ResourceTreeEntry(), and setResourceContainerType().
bool ResourceTreeEntry::jtl private
Lets us know if this resource was a JTL resource.
Definition at line 103 of file ResourceTreeEntry.h.
Referenced by isJTL(), ResourceTreeEntry(), and setJTL().
int ResourceTreeEntry::maxpool private
Maximum number of resource pools this spawns in.
Definition at line 91 of file ResourceTreeEntry.h.
Referenced by getMaxpool(), ResourceTreeEntry(), setMaxpool(), and toString().
int ResourceTreeEntry::maxtype private
Maximum of this type that can spawn.
Definition at line 83 of file ResourceTreeEntry.h.
Referenced by getMaxtype(), ResourceTreeEntry(), setMaxtype(), and toString().
int ResourceTreeEntry::minpool private
Minimum number of resource pools this spawns in.
Definition at line 88 of file ResourceTreeEntry.h.
Referenced by getMinpool(), ResourceTreeEntry(), setMinpool(), and toString().
int ResourceTreeEntry::mintype private
Minimum of this type that can spawn.
Definition at line 85 of file ResourceTreeEntry.h.
Referenced by getMintype(), ResourceTreeEntry(), setMintype(), and toString().
ResourceTreeNode* ResourceTreeEntry::myNode private
Node that this entry is on.
Definition at line 68 of file ResourceTreeEntry.h.
Referenced by getMyNode(), ResourceTreeEntry(), and setMyNode().
String ResourceTreeEntry::randomNameClass private
Unused, but in the resource tree.
Definition at line 109 of file ResourceTreeEntry.h.
Referenced by getRandomNameClass(), ResourceTreeEntry(), setRandomNameClass(), and toString().
bool ResourceTreeEntry::recycled private
If type is a recycled type.
Definition at line 94 of file ResourceTreeEntry.h.
Referenced by isRecycled(), ResourceTreeEntry(), setRecycled(), and toString().
int ResourceTreeEntry::recycleToolType private
The recyler setting that can recycle this.
Definition at line 115 of file ResourceTreeEntry.h.
Referenced by getRecycleToolType(), ResourceTreeEntry(), and setRecycleToolType().
String ResourceTreeEntry::resourceContainerType private
The script that explains the resource container type.
Definition at line 106 of file ResourceTreeEntry.h.
Referenced by getResourceContainerType(), ResourceTreeEntry(), setResourceContainerType(), and toString().
Vector<String> ResourceTreeEntry::stfClassList private
List of Class names in swg stfname.
Definition at line 77 of file ResourceTreeEntry.h.
Referenced by addStfClass(), getStfClass(), getStfClassCount(), isType(), toString(), and ~ResourceTreeEntry().
int ResourceTreeEntry::surveyToolType private
The type of survey tool that can survey this.
Definition at line 112 of file ResourceTreeEntry.h.
Referenced by getSurveyToolType(), ResourceTreeEntry(), setSurveyToolType(), and toString().
String ResourceTreeEntry::type private
Stf type.
Definition at line 71 of file ResourceTreeEntry.h.
Referenced by getType(), isType(), ResourceTreeEntry(), setRecycleToolType(), setSurveyToolType(), setType(), and toString().
String ResourceTreeEntry::zoneRestriction private
Notates id this resource is restricted to a zone.
Definition at line 100 of file ResourceTreeEntry.h.
Referenced by getZoneRestriction(), isZoneRestricted(), ResourceTreeEntry(), setZoneRestriction(), and toString().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcetree/ResourceTreeEntry.h