Core3: LootItemTemplate Class Reference
LootItemTemplate Class Reference
#include <LootItemTemplate.h>
Public Member Functions
LootItemTemplate (const String &name)
void readObject (LuaObject *templateData)
String & getDirectObjectTemplate ()
String & getCustomObjectName ()
Vector< String > * getCustomizationStringNames ()
Vector< Vector< int > > * getCustomizationValues ()
CraftingValues getCraftingValuesCopy ()
VectorMap< String, int > * getSkillMods ()
float getRandomDotChance ()
float getStaticDotChance ()
int getStaticDotType ()
int getJunkDealerTypeNeeded ()
int getJunkMinValue ()
int getJunkMaxValue ()
VectorMap< String,
SortedVector< int > > * getStaticDotValues ()
Public Member Functions inherited from LuaTemplate
virtual ~LuaTemplate ()
Public Member Functions inherited from TemplateData
virtual ~TemplateData ()
Protected Attributes
String templateName
String customObjectName
String directObjectTemplate
int junkDealerTypeNeeded
int junkMinValue
int junkMaxValue
CraftingValues craftingValues
Vector< String > customizationStringNames
Vector< Vector< int > > customizationValues
float randomDotChance
float staticDotChance
int staticDotType
VectorMap< String,
SortedVector< int > > staticDotValues
VectorMap< String, int > skillMods
Detailed Description
Definition at line 17 of file LootItemTemplate.h.
Constructor & Destructor Documentation
LootItemTemplate::LootItemTemplate (const String & name) inline
Definition at line 40 of file LootItemTemplate.h.
References randomDotChance, staticDotChance, staticDotType, and templateName.
Member Function Documentation
CraftingValues LootItemTemplate::getCraftingValuesCopy () inline
Definition at line 201 of file LootItemTemplate.h.
References craftingValues.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootObject().
Vector<String>* LootItemTemplate::getCustomizationStringNames () inline
Definition at line 193 of file LootItemTemplate.h.
References customizationStringNames.
Referenced by server::zone::managers::loot::LootManagerImplementation::setInitialObjectStats().
Vector<Vector<int> >* LootItemTemplate::getCustomizationValues () inline
Definition at line 197 of file LootItemTemplate.h.
References customizationValues.
Referenced by server::zone::managers::loot::LootManagerImplementation::setInitialObjectStats().
String& LootItemTemplate::getCustomObjectName () inline
Definition at line 189 of file LootItemTemplate.h.
References customObjectName.
Referenced by server::zone::managers::loot::LootManagerImplementation::setCustomObjectName().
String& LootItemTemplate::getDirectObjectTemplate () inline
Definition at line 185 of file LootItemTemplate.h.
References directObjectTemplate.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootObject().
int LootItemTemplate::getJunkDealerTypeNeeded () inline
Definition at line 221 of file LootItemTemplate.h.
References junkDealerTypeNeeded.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootObject().
int LootItemTemplate::getJunkMaxValue () inline
Definition at line 227 of file LootItemTemplate.h.
References junkMaxValue.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootObject().
int LootItemTemplate::getJunkMinValue () inline
Definition at line 224 of file LootItemTemplate.h.
References junkMinValue.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootObject().
float LootItemTemplate::getRandomDotChance () inline
Definition at line 209 of file LootItemTemplate.h.
References randomDotChance.
Referenced by server::zone::managers::loot::LootManagerImplementation::addRandomDots().
VectorMap<String, int>* LootItemTemplate::getSkillMods () inline
Definition at line 205 of file LootItemTemplate.h.
References skillMods.
Referenced by server::zone::managers::loot::LootManagerImplementation::setSkillMods().
float LootItemTemplate::getStaticDotChance () inline
Definition at line 213 of file LootItemTemplate.h.
References staticDotChance.
Referenced by server::zone::managers::loot::LootManagerImplementation::addStaticDots().
int LootItemTemplate::getStaticDotType () inline
Definition at line 217 of file LootItemTemplate.h.
References staticDotType.
Referenced by server::zone::managers::loot::LootManagerImplementation::addStaticDots().
VectorMap<String, SortedVector<int> >* LootItemTemplate::getStaticDotValues () inline
Definition at line 230 of file LootItemTemplate.h.
References staticDotValues.
Referenced by server::zone::managers::loot::LootManagerImplementation::addStaticDots().
void LootItemTemplate::readObject (LuaObject * templateData) inline virtual
Implements LuaTemplate.
Definition at line 47 of file LootItemTemplate.h.
References server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::addExperimentalProperty(), craftingValues, customizationStringNames, customizationValues, customObjectName, directObjectTemplate, junkDealerTypeNeeded, junkMaxValue, junkMinValue, randomDotChance, server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxPercentage(), skillMods, staticDotChance, staticDotType, and staticDotValues.
Member Data Documentation
CraftingValues LootItemTemplate::craftingValues protected
Definition at line 27 of file LootItemTemplate.h.
Referenced by getCraftingValuesCopy(), and readObject().
Vector<String> LootItemTemplate::customizationStringNames protected
Definition at line 29 of file LootItemTemplate.h.
Referenced by getCustomizationStringNames(), and readObject().
Vector<Vector<int> > LootItemTemplate::customizationValues protected
Definition at line 30 of file LootItemTemplate.h.
Referenced by getCustomizationValues(), and readObject().
String LootItemTemplate::customObjectName protected
Definition at line 20 of file LootItemTemplate.h.
Referenced by getCustomObjectName(), and readObject().
String LootItemTemplate::directObjectTemplate protected
Definition at line 21 of file LootItemTemplate.h.
Referenced by getDirectObjectTemplate(), and readObject().
int LootItemTemplate::junkDealerTypeNeeded protected
Definition at line 23 of file LootItemTemplate.h.
Referenced by getJunkDealerTypeNeeded(), and readObject().
int LootItemTemplate::junkMaxValue protected
Definition at line 25 of file LootItemTemplate.h.
Referenced by getJunkMaxValue(), and readObject().
int LootItemTemplate::junkMinValue protected
Definition at line 24 of file LootItemTemplate.h.
Referenced by getJunkMinValue(), and readObject().
float LootItemTemplate::randomDotChance protected
Definition at line 32 of file LootItemTemplate.h.
Referenced by getRandomDotChance(), LootItemTemplate(), and readObject().
VectorMap<String, int> LootItemTemplate::skillMods protected
Definition at line 37 of file LootItemTemplate.h.
Referenced by getSkillMods(), and readObject().
float LootItemTemplate::staticDotChance protected
Definition at line 33 of file LootItemTemplate.h.
Referenced by getStaticDotChance(), LootItemTemplate(), and readObject().
int LootItemTemplate::staticDotType protected
Definition at line 34 of file LootItemTemplate.h.
Referenced by getStaticDotType(), LootItemTemplate(), and readObject().
VectorMap<String, SortedVector<int> > LootItemTemplate::staticDotValues protected
Definition at line 35 of file LootItemTemplate.h.
Referenced by getStaticDotValues(), and readObject().
String LootItemTemplate::templateName protected
Definition at line 19 of file LootItemTemplate.h.
Referenced by LootItemTemplate().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/LootItemTemplate.h