Core3: server::zone::objects::player::sessions::EntertainingSession Class Reference
server::zone::objects::player::sessions::EntertainingSession Class Reference
#include <EntertainingSession.h>
Public Member Functions
EntertainingSession (CreatureObject *ent)
void doEntertainerPatronEffects ()
void doPerformanceAction ()
void addEntertainerFlourishBuff ()
void startDancing (const String &dance, const String &animation)
void startPlayingMusic (const String &song, const String &instrumentAnimation, int instrid)
void startEntertaining ()
void healWounds (CreatureObject *creature, float woundHeal, float shockHeal)
bool isInEntertainingBuilding (CreatureObject *creature)
void doFlourish (int flourishNumber)
bool canHealBattleFatigue ()
bool canGiveEntertainBuff ()
void addFlourishXp (int xp)
void addHealingXp (int xp)
void addHealingXpGroup (int xp)
int initializeSession ()
int cancelSession ()
int clearSession ()
void stopPlayingMusic ()
void stopDancing ()
void activateAction ()
void startTickTask ()
void addEntertainerBuffDuration (CreatureObject *creature, int performanceType, float duration)
void addEntertainerBuffStrength (CreatureObject *creature, int performanceType, float strength)
void setEntertainerBuffDuration (CreatureObject *creature, int performanceType, float duration)
void setEntertainerBuffStrength (CreatureObject *creature, int performanceType, float strength)
int getEntertainerBuffStrength (CreatureObject *creature, int performanceType)
int getEntertainerBuffDuration (CreatureObject *creature, int performanceType)
int getEntertainerBuffStartTime (CreatureObject *creature, int performanceType)
void sendEntertainingUpdate (CreatureObject *creature, float entval, const String &performance, unsigned int perfcntr, int instrid)
void sendEntertainmentUpdate (CreatureObject *creature, unsigned long long entid, const String &mood, bool updateEntValue=false)
void activateEntertainerBuff (CreatureObject *creature, int performanceType)
Instrument * getInstrument (CreatureObject *creature)
String getPerformanceName ()
void addWatcher (CreatureObject *creature)
void addListener (CreatureObject *listener)
bool isDancing ()
bool isPlayingMusic ()
bool isAcceptingBandFlourishes ()
void setAcceptingBandFlourishes (bool val)
void removeWatcher (CreatureObject *creature)
void removeListener (CreatureObject *creature)
void setPerformanceName (const String &name)
void setDancing (bool val)
void setTargetInstrument (bool var)
void updateEntertainerMissionStatus (bool entertaining, const int missionType)
bool isInDenyServiceList (CreatureObject *target)
void addToDenyServiceList (CreatureObject *target)
void removeFromDenyServiceList (CreatureObject *target)
void increaseEntertainerBuff (CreatureObject *patron)
void awardEntertainerExperience ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
EntertainingSession (DummyConstructorParameter *param)
virtual ~EntertainingSession ()
Friends
class EntertainingSessionHelper
Detailed Description
Definition at line 124 of file EntertainingSession.h.
Constructor & Destructor Documentation
EntertainingSession::EntertainingSession (CreatureObject * ent)
Definition at line 25 of file EntertainingSession.cpp.
References server::zone::objects::player::sessions::EntertainingSessionImplementation::_setStub().
EntertainingSession::EntertainingSession (DummyConstructorParameter * param) protected
Definition at line 32 of file EntertainingSession.cpp.
EntertainingSession::~EntertainingSession () protected virtual
Definition at line 36 of file EntertainingSession.cpp.
Member Function Documentation
DistributedObjectServant * EntertainingSession::_getImplementation ()
Definition at line 722 of file EntertainingSession.cpp.
Referenced by activateAction(), activateEntertainerBuff(), addEntertainerBuffDuration(), addEntertainerBuffStrength(), addEntertainerFlourishBuff(), addFlourishXp(), addHealingXp(), addHealingXpGroup(), addListener(), addToDenyServiceList(), addWatcher(), awardEntertainerExperience(), cancelSession(), canGiveEntertainBuff(), canHealBattleFatigue(), clearSession(), doEntertainerPatronEffects(), doFlourish(), doPerformanceAction(), getEntertainerBuffDuration(), getEntertainerBuffStartTime(), getEntertainerBuffStrength(), getInstrument(), getPerformanceName(), healWounds(), increaseEntertainerBuff(), initializeSession(), isAcceptingBandFlourishes(), isDancing(), isInDenyServiceList(), isInEntertainingBuilding(), isPlayingMusic(), removeFromDenyServiceList(), removeListener(), removeWatcher(), sendEntertainingUpdate(), sendEntertainmentUpdate(), setAcceptingBandFlourishes(), setDancing(), setEntertainerBuffDuration(), setEntertainerBuffStrength(), setPerformanceName(), setTargetInstrument(), startDancing(), startEntertaining(), startPlayingMusic(), startTickTask(), stopDancing(), stopPlayingMusic(), and updateEntertainerMissionStatus().
DistributedObjectServant * EntertainingSession::_getImplementationForRead ()
Definition at line 728 of file EntertainingSession.cpp.
void EntertainingSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 732 of file EntertainingSession.cpp.
void EntertainingSession::activateAction ()
Definition at line 301 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::activateAction(), and RPC_ACTIVATEACTION__.
void EntertainingSession::activateEntertainerBuff (CreatureObject * creature, int performanceType)
Definition at line 443 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::activateEntertainerBuff(), and RPC_ACTIVATEENTERTAINERBUFF__CREATUREOBJECT_INT_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::stopListen(), and server::zone::managers::player::PlayerManagerImplementation::stopWatch().
void EntertainingSession::addEntertainerBuffDuration (CreatureObject * creature, int performanceType, float duration)
Definition at line 327 of file EntertainingSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::EntertainingSessionImplementation::addEntertainerBuffDuration().
void EntertainingSession::addEntertainerBuffStrength (CreatureObject * creature, int performanceType, float strength)
Definition at line 336 of file EntertainingSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::EntertainingSessionImplementation::addEntertainerBuffStrength().
void EntertainingSession::addEntertainerFlourishBuff ()
Definition at line 67 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::addEntertainerFlourishBuff(), and RPC_ADDENTERTAINERFLOURISHBUFF__.
void EntertainingSession::addFlourishXp (int xp)
Definition at line 194 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::addFlourishXp(), and RPC_ADDFLOURISHXP__INT_.
void EntertainingSession::addHealingXp (int xp)
Definition at line 208 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::addHealingXp(), and RPC_ADDHEALINGXP__INT_.
void EntertainingSession::addHealingXpGroup (int xp)
Definition at line 222 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::addHealingXpGroup(), and RPC_ADDHEALINGXPGROUP__INT_.
void EntertainingSession::addListener (CreatureObject * listener)
Definition at line 501 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::addListener(), and RPC_ADDLISTENER__CREATUREOBJECT_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::startListen().
void EntertainingSession::addToDenyServiceList (CreatureObject * target)
Definition at line 667 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::addToDenyServiceList(), and RPC_ADDTODENYSERVICELIST__CREATUREOBJECT_.
void EntertainingSession::addWatcher (CreatureObject * creature)
Definition at line 487 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::addWatcher(), and RPC_ADDWATCHER__CREATUREOBJECT_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::startWatch().
void EntertainingSession::awardEntertainerExperience ()
Definition at line 709 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::awardEntertainerExperience(), and RPC_AWARDENTERTAINEREXPERIENCE__.
int EntertainingSession::cancelSession ()
Definition at line 249 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::stopEntertaining().
bool EntertainingSession::canGiveEntertainBuff ()
Definition at line 181 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::canGiveEntertainBuff(), and RPC_CANGIVEENTERTAINBUFF__.
bool EntertainingSession::canHealBattleFatigue ()
Definition at line 168 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::canHealBattleFatigue(), and RPC_CANHEALBATTLEFATIGUE__.
int EntertainingSession::clearSession ()
Definition at line 262 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
void EntertainingSession::doEntertainerPatronEffects ()
Definition at line 41 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::doEntertainerPatronEffects(), and RPC_DOENTERTAINERPATRONEFFECTS__.
void EntertainingSession::doFlourish (int flourishNumber)
Definition at line 154 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::doFlourish(), and RPC_DOFLOURISH__INT_.
void EntertainingSession::doPerformanceAction ()
Definition at line 54 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::doPerformanceAction(), and RPC_DOPERFORMANCEACTION__.
int EntertainingSession::getEntertainerBuffDuration (CreatureObject * creature, int performanceType)
Definition at line 378 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::getEntertainerBuffDuration(), and RPC_GETENTERTAINERBUFFDURATION__CREATUREOBJECT_INT_.
int EntertainingSession::getEntertainerBuffStartTime (CreatureObject * creature, int performanceType)
Definition at line 393 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::getEntertainerBuffStartTime(), and RPC_GETENTERTAINERBUFFSTARTTIME__CREATUREOBJECT_INT_.
int EntertainingSession::getEntertainerBuffStrength (CreatureObject * creature, int performanceType)
Definition at line 363 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::getEntertainerBuffStrength(), and RPC_GETENTERTAINERBUFFSTRENGTH__CREATUREOBJECT_INT_.
Instrument * EntertainingSession::getInstrument (CreatureObject * creature)
Definition at line 458 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::getInstrument(), and RPC_GETINSTRUMENT__CREATUREOBJECT_.
Referenced by ChangeBandMusicCommand::canPlaySong(), and BandFlourishCommand::doBandFlourish().
String EntertainingSession::getPerformanceName ()
Definition at line 472 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::getPerformanceName(), and RPC_GETPERFORMANCENAME__.
Referenced by GroupManager::createGroup(), and GroupManager::joinGroup().
void EntertainingSession::healWounds (CreatureObject * creature, float woundHeal, float shockHeal)
Definition at line 124 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::healWounds(), and RPC_HEALWOUNDS__CREATUREOBJECT_FLOAT_FLOAT_.
void EntertainingSession::increaseEntertainerBuff (CreatureObject * patron)
Definition at line 695 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::increaseEntertainerBuff(), and RPC_INCREASEENTERTAINERBUFF__CREATUREOBJECT_.
int EntertainingSession::initializeSession ()
Definition at line 236 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
bool EntertainingSession::isAcceptingBandFlourishes ()
Definition at line 541 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::isAcceptingBandFlourishes(), and RPC_ISACCEPTINGBANDFLOURISHES__.
bool EntertainingSession::isDancing ()
Definition at line 515 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::isDancing(), and RPC_ISDANCING__.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::isDancing().
bool EntertainingSession::isInDenyServiceList (CreatureObject * target)
Definition at line 653 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::isInDenyServiceList(), and RPC_ISINDENYSERVICELIST__CREATUREOBJECT_.
bool EntertainingSession::isInEntertainingBuilding (CreatureObject * creature)
Definition at line 140 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::isInEntertainingBuilding(), and RPC_ISINENTERTAININGBUILDING__CREATUREOBJECT_.
bool EntertainingSession::isPlayingMusic ()
Definition at line 528 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::isPlayingMusic(), and RPC_ISPLAYINGMUSIC__.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::isPlayingMusic().
void EntertainingSession::removeFromDenyServiceList (CreatureObject * target)
Definition at line 681 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::removeFromDenyServiceList(), and RPC_REMOVEFROMDENYSERVICELIST__CREATUREOBJECT_.
void EntertainingSession::removeListener (CreatureObject * creature)
Definition at line 582 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::removeListener(), and RPC_REMOVELISTENER__CREATUREOBJECT_.
void EntertainingSession::removeWatcher (CreatureObject * creature)
Definition at line 568 of file EntertainingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::EntertainingSessionImplementation::removeWatcher(), and RPC_REMOVEWATCHER__CREATUREOBJECT_.
void EntertainingSession::sendEntertainingUpdate (CreatureObject * creature, float entval, const String & performance, unsigned int perfcntr, int instrid)
Definition at line 408 of file EntertainingSession.cpp.
References _getImplementation(), RPC_SENDENTERTAININGUPDATE__CREATUREOBJECT_FLOAT_STRING_INT_INT_, and server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainingUpdate().
void EntertainingSession::sendEntertainmentUpdate (CreatureObject * creature, unsigned long long entid, const String & mood, bool updateEntValue = false)
Definition at line 426 of file EntertainingSession.cpp.
References _getImplementation(), RPC_SENDENTERTAINMENTUPDATE__CREATUREOBJECT_LONG_STRING_BOOL_, and server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainmentUpdate().
Referenced by server::zone::managers::player::PlayerManagerImplementation::startListen(), and server::zone::managers::player::PlayerManagerImplementation::startWatch().
void EntertainingSession::setAcceptingBandFlourishes (bool val)
Definition at line 554 of file EntertainingSession.cpp.
References _getImplementation(), RPC_SETACCEPTINGBANDFLOURISHES__BOOL_, and server::zone::objects::player::sessions::EntertainingSessionImplementation::setAcceptingBandFlourishes().
void EntertainingSession::setDancing (bool val)
Definition at line 610 of file EntertainingSession.cpp.
References _getImplementation(), RPC_SETDANCING__BOOL_, and server::zone::objects::player::sessions::EntertainingSessionImplementation::setDancing().
void EntertainingSession::setEntertainerBuffDuration (CreatureObject * creature, int performanceType, float duration)
Definition at line 345 of file EntertainingSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::EntertainingSessionImplementation::setEntertainerBuffDuration().
void EntertainingSession::setEntertainerBuffStrength (CreatureObject * creature, int performanceType, float strength)
Definition at line 354 of file EntertainingSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::EntertainingSessionImplementation::setEntertainerBuffStrength().
void EntertainingSession::setPerformanceName (const String & name)
Definition at line 596 of file EntertainingSession.cpp.
References _getImplementation(), RPC_SETPERFORMANCENAME__STRING_, and server::zone::objects::player::sessions::EntertainingSessionImplementation::setPerformanceName().
void EntertainingSession::setTargetInstrument (bool var)
Definition at line 624 of file EntertainingSession.cpp.
References _getImplementation(), RPC_SETTARGETINSTRUMENT__BOOL_, and server::zone::objects::player::sessions::EntertainingSessionImplementation::setTargetInstrument().
void EntertainingSession::startDancing (const String & dance, const String & animation)
Definition at line 80 of file EntertainingSession.cpp.
References _getImplementation(), RPC_STARTDANCING__STRING_STRING_, and server::zone::objects::player::sessions::EntertainingSessionImplementation::startDancing().
void EntertainingSession::startEntertaining ()
Definition at line 111 of file EntertainingSession.cpp.
References _getImplementation(), RPC_STARTENTERTAINING__, and server::zone::objects::player::sessions::EntertainingSessionImplementation::startEntertaining().
void EntertainingSession::startPlayingMusic (const String & song, const String & instrumentAnimation, int instrid)
Definition at line 95 of file EntertainingSession.cpp.
References _getImplementation(), RPC_STARTPLAYINGMUSIC__STRING_STRING_INT_, and server::zone::objects::player::sessions::EntertainingSessionImplementation::startPlayingMusic().
void EntertainingSession::startTickTask ()
Definition at line 314 of file EntertainingSession.cpp.
References _getImplementation(), RPC_STARTTICKTASK__, and server::zone::objects::player::sessions::EntertainingSessionImplementation::startTickTask().
void EntertainingSession::stopDancing ()
Definition at line 288 of file EntertainingSession.cpp.
References _getImplementation(), RPC_STOPDANCING__, and server::zone::objects::player::sessions::EntertainingSessionImplementation::stopDancing().
Referenced by StartMusicCommand::doQueueCommand().
void EntertainingSession::stopPlayingMusic ()
Definition at line 275 of file EntertainingSession.cpp.
References _getImplementation(), RPC_STOPPLAYINGMUSIC__, and server::zone::objects::player::sessions::EntertainingSessionImplementation::stopPlayingMusic().
Referenced by GroupManager::createGroup(), and StartDanceCommand::doQueueCommand().
void EntertainingSession::updateEntertainerMissionStatus (bool entertaining, const int missionType)
Definition at line 638 of file EntertainingSession.cpp.
References _getImplementation(), RPC_UPDATEENTERTAINERMISSIONSTATUS__BOOL_INT_, and server::zone::objects::player::sessions::EntertainingSessionImplementation::updateEntertainerMissionStatus().
Friends And Related Function Documentation
friend class EntertainingSessionHelper friend
Definition at line 238 of file EntertainingSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/EntertainingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/EntertainingSession.cpp