Core3: server::zone::managers::stringid::StringIdManager Class Reference
server::zone::managers::stringid::StringIdManager Class Reference
#include <StringIdManager.h>
Public Member Functions
StringIdManager ()
~StringIdManager ()
UnicodeString getStringId (uint32 crc)
Protected Member Functions
void populateDatabase ()
Private Attributes
ObjectDatabaseManager * databaseManager
LocalDatabase * stringsDatabase
Detailed Description
Definition at line 20 of file StringIdManager.h.
Constructor & Destructor Documentation
StringIdManager::StringIdManager ()
Definition at line 89 of file StringIdManager.cpp.
References databaseManager, ServerCore::hasArgument(), populateDatabase(), stringsDatabase, and ServerCore::truncateDatabases().
StringIdManager::~StringIdManager ()
Definition at line 103 of file StringIdManager.cpp.
Member Function Documentation
UnicodeString StringIdManager::getStringId (uint32 crc)
Definition at line 105 of file StringIdManager.cpp.
References stringsDatabase.
Referenced by LootSchematicAttributeListComponent::fillAttributeList(), server::zone::objects::player::sessions::FindSessionImplementation::findPlanetaryObject(), and server::zone::managers::player::PlayerManagerImplementation::offerTeaching().
void StringIdManager::populateDatabase () protected
Definition at line 13 of file StringIdManager.cpp.
References TreeArchive::getFilesAndSubDirectoryFiles(), StringFile::getStringMap(), StringFile::load(), and stringsDatabase.
Referenced by StringIdManager().
Member Data Documentation
ObjectDatabaseManager* server::zone::managers::stringid::StringIdManager::databaseManager private
Definition at line 21 of file StringIdManager.h.
Referenced by StringIdManager().
LocalDatabase* server::zone::managers::stringid::StringIdManager::stringsDatabase private
Definition at line 23 of file StringIdManager.h.
Referenced by getStringId(), populateDatabase(), and StringIdManager().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/stringid/StringIdManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/stringid/StringIdManager.cpp