Core3: InformationHeader Class Reference
InformationHeader Class Reference
#include <InformationHeader.h>
Public Member Functions
void parseFromIffStream (engine::util::IffStream *iffStream)
void parseFromIffStream (engine::util::IffStream *iffStream, Version<'0001'>)
bool isEnabled ()
String & getDescription ()
Public Member Functions inherited from TemplateVariable<'IHDR'>
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Private Attributes
int var1
String description
Detailed Description
Definition at line 13 of file InformationHeader.h.
Member Function Documentation
String& InformationHeader::getDescription () inline
Definition at line 48 of file InformationHeader.h.
References description.
Referenced by Layer::getDescription(), AffectorHeightFractal::process(), FilterFractal::process(), and FilterBitmap::process().
bool InformationHeader::isEnabled () inline
Definition at line 44 of file InformationHeader.h.
References var1.
Referenced by ProceduralRule<'FFRA'>::isEnabled(), FilterFractal::isEnabled(), AffectorHeightFractal::isEnabled(), AffectorEnvironment::isEnabled(), FilterBitmap::isEnabled(), FilterHeight::isEnabled(), AffectorHeightTerrace::isEnabled(), BoundaryCircle::isEnabled(), Layer::isEnabled(), AffectorHeightConstant::isEnabled(), FilterSlope::isEnabled(), BoundaryPolyline::isEnabled(), BoundaryRectangle::isEnabled(), and BoundaryPolygon::isEnabled().
void InformationHeader::parseFromIffStream (engine::util::IffStream * iffStream) inline virtual
Reimplemented from TemplateVariable<'IHDR'>.
Definition at line 18 of file InformationHeader.h.
void InformationHeader::parseFromIffStream (engine::util::IffStream * iffStream, Version<'0001'>) inline
Definition at line 35 of file InformationHeader.h.
References description, and var1.
Member Data Documentation
String InformationHeader::description private
Definition at line 15 of file InformationHeader.h.
Referenced by getDescription(), and parseFromIffStream().
int InformationHeader::var1 private
Definition at line 14 of file InformationHeader.h.
Referenced by isEnabled(), and parseFromIffStream().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/layer/InformationHeader.h