Core3: HealMindCommand Class Reference
HealMindCommand Class Reference
#include <HealMindCommand.h>
Public Member Functions
HealMindCommand (const String &name, ZoneProcessServer *server)
void doAnimations (CreatureObject *creature, CreatureObject *creatureTarget)
void sendHealMessage (CreatureObject *creature, CreatureObject *creatureTarget, int mindDamage)
int calculateWound (int wound, int poolWounds, int poolMax)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Private Attributes
float mindCost
float mindWoundCost
float range
Detailed Description
Definition at line 51 of file HealMindCommand.h.
Constructor & Destructor Documentation
HealMindCommand::HealMindCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 57 of file HealMindCommand.h.
References mindCost, mindWoundCost, and range.
Member Function Documentation
int HealMindCommand::calculateWound (int wound, int poolWounds, int poolMax) inline
Definition at line 100 of file HealMindCommand.h.
void HealMindCommand::doAnimations (CreatureObject * creature, CreatureObject * creatureTarget) inline
Definition at line 65 of file HealMindCommand.h.
References server::zone::objects::creature::CreatureObject::doAnimation(), and server::zone::objects::creature::CreatureObject::playEffect().
Referenced by doQueueCommand().
int HealMindCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 105 of file HealMindCommand.h.
References server::zone::objects::creature::CreatureObject::addShockWounds(), server::zone::objects::creature::CreatureObject::addWounds(), server::zone::objects::creature::CreatureObject::calculateBFRatio(), CollisionManager::checkLineOfSight(), doAnimations(), CreatureAttribute::FOCUS, server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::hasDamage(), server::zone::objects::creature::CreatureObject::healDamage(), server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isHealableBy(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::CreatureObject::isMeditating(), server::zone::objects::creature::CreatureObject::isMounted(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isProne(), server::zone::objects::creature::CreatureObject::isRidingCreature(), CreatureAttribute::MIND, mindCost, range, sendHealMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and CreatureAttribute::WILLPOWER.
void HealMindCommand::sendHealMessage (CreatureObject * creature, CreatureObject * creatureTarget, int mindDamage) inline
Definition at line 74 of file HealMindCommand.h.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
Member Data Documentation
float HealMindCommand::mindCost private
Definition at line 52 of file HealMindCommand.h.
Referenced by doQueueCommand(), and HealMindCommand().
float HealMindCommand::mindWoundCost private
Definition at line 53 of file HealMindCommand.h.
Referenced by HealMindCommand().
float HealMindCommand::range private
Definition at line 54 of file HealMindCommand.h.
Referenced by doQueueCommand(), and HealMindCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/HealMindCommand.h