Core3: server::zone::managers::loot::LootManager Class Reference
server::zone::managers::loot::LootManager Class Reference
#include <LootManager.h>
Public Member Functions
LootManager (CraftingManager *craftman, ObjectManager *objMan, ZoneServer *server)
void initialize ()
TangibleObject * createLootObject (LootItemTemplate *templateObject, int level, bool maxCondition=false)
String getRandomLootableMod (unsigned int sceneObjectType)
int calculateLootCredits (int level)
bool createLoot (SceneObject *container, AiAgent *creature)
bool createLootFromCollection (SceneObject *container, LootGroupCollection *collection, int level)
bool createLoot (SceneObject *container, const String &lootGroup, int level=-1, bool maxCondition=false)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
LootManager (DummyConstructorParameter *param)
virtual ~LootManager ()
Friends
class LootManagerHelper
Detailed Description
Definition at line 133 of file LootManager.h.
Constructor & Destructor Documentation
LootManager::LootManager (CraftingManager * craftman, ObjectManager * objMan, ZoneServer * server)
Definition at line 27 of file LootManager.cpp.
References server::zone::managers::loot::LootManagerImplementation::_setStub().
LootManager::LootManager (DummyConstructorParameter * param) protected
Definition at line 34 of file LootManager.cpp.
LootManager::~LootManager () protected virtual
Definition at line 38 of file LootManager.cpp.
Member Function Documentation
DistributedObjectServant * LootManager::_getImplementation ()
Definition at line 129 of file LootManager.cpp.
Referenced by calculateLootCredits(), createLoot(), createLootFromCollection(), createLootObject(), getRandomLootableMod(), and initialize().
DistributedObjectServant * LootManager::_getImplementationForRead ()
Definition at line 135 of file LootManager.cpp.
void LootManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 139 of file LootManager.cpp.
int LootManager::calculateLootCredits (int level)
Definition at line 74 of file LootManager.cpp.
References _getImplementation(), server::zone::managers::loot::LootManagerImplementation::calculateLootCredits(), and RPC_CALCULATELOOTCREDITS__INT_.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction().
bool LootManager::createLoot (SceneObject * container, AiAgent * creature)
Definition at line 88 of file LootManager.cpp.
References _getImplementation(), server::zone::managers::loot::LootManagerImplementation::createLoot(), and RPC_CREATELOOT__SCENEOBJECT_AIAGENT_.
Referenced by server::zone::managers::director::DirectorManager::createLoot(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleContainerSlice(), and server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction().
bool LootManager::createLoot (SceneObject * container, const String & lootGroup, int level = -1, bool maxCondition = false)
Definition at line 112 of file LootManager.cpp.
References _getImplementation(), server::zone::managers::loot::LootManagerImplementation::createLoot(), and RPC_CREATELOOT__SCENEOBJECT_STRING_INT_BOOL_.
bool LootManager::createLootFromCollection (SceneObject * container, LootGroupCollection * collection, int level)
Definition at line 103 of file LootManager.cpp.
References _getImplementation(), and server::zone::managers::loot::LootManagerImplementation::createLootFromCollection().
Referenced by server::zone::managers::director::DirectorManager::createLootFromCollection().
TangibleObject * LootManager::createLootObject (LootItemTemplate * templateObject, int level, bool maxCondition = false)
Definition at line 56 of file LootManager.cpp.
References _getImplementation(), and server::zone::managers::loot::LootManagerImplementation::createLootObject().
String LootManager::getRandomLootableMod (unsigned int sceneObjectType)
Definition at line 65 of file LootManager.cpp.
References _getImplementation(), and server::zone::managers::loot::LootManagerImplementation::getRandomLootableMod().
void LootManager::initialize ()
Definition at line 43 of file LootManager.cpp.
References _getImplementation(), server::zone::managers::loot::LootManagerImplementation::initialize(), and RPC_INITIALIZE__.
Friends And Related Function Documentation
friend class LootManagerHelper friend
Definition at line 161 of file LootManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/LootManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/LootManager.cpp