Core3: server::chat::ChatParameter Class Reference
server::chat::ChatParameter Class Reference abstract
#include <ChatParameter.h>
Public Member Functions
ChatParameter ()
ChatParameter (const ChatParameter &id)
ChatParameter & operator= (const ChatParameter &id)
void insertToMessage (Message *message)
virtual void parse (Message *message)=0
bool isStringIdParameter ()
bool isWaypointParameter ()
Static Public Attributes
static const byte TYPE_STRINGID = 1
static const byte TYPE_WAYPOINT = 4
static const int STRINGID = 0xFFFFFFFF
static const int WAYPOINT = 0xFFFFFFFD
Protected Member Functions
virtual void addToPacketStream (Message *packet)=0
virtual void insertHeaderToMessage (Message *message)
Detailed Description
Definition at line 16 of file ChatParameter.h.
Constructor & Destructor Documentation
ChatParameter::ChatParameter ()
Definition at line 10 of file ChatParameter.cpp.
ChatParameter::ChatParameter (const ChatParameter & id)
Definition at line 13 of file ChatParameter.cpp.
Member Function Documentation
virtual void server::chat::ChatParameter::addToPacketStream (Message * packet) protected pure virtual
Implemented in server::chat::StringIdChatParameter, and server::chat::WaypointChatParameter.
Referenced by insertToMessage().
virtual void server::chat::ChatParameter::insertHeaderToMessage (Message * message) inline protected virtual
Reimplemented in server::chat::WaypointChatParameter.
Definition at line 20 of file ChatParameter.h.
References STRINGID, and TYPE_STRINGID.
Referenced by insertToMessage().
void ChatParameter::insertToMessage (Message * message)
Definition at line 16 of file ChatParameter.cpp.
References addToPacketStream(), and insertHeaderToMessage().
Referenced by ChatPersistentMessageToClient::ChatPersistentMessageToClient(), ChatSystemMessage::ChatSystemMessage(), ChatPersistentMessageToClient::insertParameters(), NpcConversationMessage::NpcConversationMessage(), and SpatialChat::SpatialChat().
bool server::chat::ChatParameter::isStringIdParameter () inline
Definition at line 45 of file ChatParameter.h.
bool server::chat::ChatParameter::isWaypointParameter () inline
Definition at line 49 of file ChatParameter.h.
ChatParameter& server::chat::ChatParameter::operator= (const ChatParameter & id) inline
Definition at line 35 of file ChatParameter.h.
virtual void server::chat::ChatParameter::parse (Message * message) pure virtual
Implemented in server::chat::StringIdChatParameter, and server::chat::WaypointChatParameter.
Member Data Documentation
const int server::chat::ChatParameter::STRINGID = 0xFFFFFFFF static
Definition at line 29 of file ChatParameter.h.
Referenced by insertHeaderToMessage().
const byte server::chat::ChatParameter::TYPE_STRINGID = 1 static
Definition at line 26 of file ChatParameter.h.
Referenced by insertHeaderToMessage().
const byte server::chat::ChatParameter::TYPE_WAYPOINT = 4 static
Definition at line 27 of file ChatParameter.h.
const int server::chat::ChatParameter::WAYPOINT = 0xFFFFFFFD static
Definition at line 30 of file ChatParameter.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatParameter.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatParameter.cpp