Core3: DestroyStructureTask Class Reference
DestroyStructureTask Class Reference
#include <DestroyStructureTask.h>
Public Member Functions
DestroyStructureTask (StructureObject *structure)
void run ()
Protected Attributes
ManagedReference
< StructureObject * > structureObject
Detailed Description
Definition at line 16 of file DestroyStructureTask.h.
Constructor & Destructor Documentation
DestroyStructureTask::DestroyStructureTask (StructureObject * structure) inline
Definition at line 21 of file DestroyStructureTask.h.
References structureObject.
Member Function Documentation
void DestroyStructureTask::run () inline
Definition at line 25 of file DestroyStructureTask.h.
References server::zone::objects::scene::SceneObject::error(), server::zone::ZoneServer::isServerLoading(), ObserverEventType::OBJECTDESTRUCTION, server::zone::objects::player::PlayerObject::removeOwnedStructure(), server::zone::objects::player::PlayerObject::removeVendor(), structureObject, and server::zone::objects::scene::SceneObject::teleport().
Member Data Documentation
ManagedReference<StructureObject*> DestroyStructureTask::structureObject protected
Definition at line 18 of file DestroyStructureTask.h.
Referenced by DestroyStructureTask(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/structure/tasks/DestroyStructureTask.h