Core3: MobileOutfit Class Reference
MobileOutfit Class Reference
#include <MobileOutfit.h>
Public Member Functions
MobileOutfit ()
MobileOutfit (const MobileOutfit &o)
MobileOutfit & operator= (const MobileOutfit &o)
void readObject (LuaObject *luaObject)
Vector< OutfitTangibleObject > * getObjects ()
Private Attributes
Vector< OutfitTangibleObject > objects
Detailed Description
Definition at line 64 of file MobileOutfit.h.
Constructor & Destructor Documentation
MobileOutfit::MobileOutfit () inline
Definition at line 67 of file MobileOutfit.h.
MobileOutfit::MobileOutfit (const MobileOutfit & o) inline
Definition at line 71 of file MobileOutfit.h.
References objects.
Member Function Documentation
Vector<OutfitTangibleObject>* MobileOutfit::getObjects () inline
Definition at line 97 of file MobileOutfit.h.
References objects.
Referenced by server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData(), and server::zone::objects::creature::AiAgentImplementation::loadTemplateData().
MobileOutfit& MobileOutfit::operator= (const MobileOutfit & o) inline
Definition at line 75 of file MobileOutfit.h.
References objects.
void MobileOutfit::readObject (LuaObject * luaObject) inline
Definition at line 84 of file MobileOutfit.h.
References objects, and OutfitTangibleObject::readObject().
Referenced by MobileOutfitGroup::readObject().
Member Data Documentation
Vector<OutfitTangibleObject> MobileOutfit::objects private
Definition at line 65 of file MobileOutfit.h.
Referenced by getObjects(), MobileOutfit(), operator=(), and readObject().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/mobile/MobileOutfit.h