Core3: server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation Class Reference
server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation Class Reference
#include <SuiTransferBox.h>
Public Member Functions
SuiTransferBoxImplementation (CreatureObject *player, unsigned int windowType)
SuiTransferBoxImplementation (DummyConstructorParameter *param)
BaseMessage * generateMessage ()
void addFrom (const String &from, const String &startingFrom, const String &inputFrom, const String &rFrom)
void addTo (const String &to, const String &startingTo, const String &inputTo, const String &rTo)
bool isTransferBox ()
operator const SuiTransferBox * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
SuiBoxImplementation (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
SuiBoxImplementation (DummyConstructorParameter *param)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
virtual bool isInputBox ()
virtual bool isListBox ()
virtual bool isMessageBox ()
virtual bool isBankTransferBox ()
virtual bool isSlicingBox ()
virtual bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
operator const SuiBox * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< SuiTransferBox * > _this
Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
WeakReference< SuiBox * > _this
Protected Member Functions
virtual ~SuiTransferBoxImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
virtual ~SuiBoxImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
String lblFrom
String lblStartingFrom
String lblInputFrom
String lblTo
String lblStartingTo
String lblInputTo
String convertRatioFrom
String convertRatioTo
Protected Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
ManagedWeakReference
< CreatureObject * > player
Reference< SuiCallback * > suiCallback
unsigned int boxID
ManagedWeakReference
< SceneObject * > usingObject
String handlerStr
String cancelButtonText
bool cancelButton
String okButtonText
bool okButton
String otherButtonText
bool otherButton
String promptTitle
String promptText
int boxType
unsigned int windowType
float forceCloseDistance
Vector< String > headerSets
Vector< String > optionSets
int hdrOptCount
bool hasGenerated
Friends
class SuiTransferBox
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Detailed Description
Definition at line 112 of file SuiTransferBox.h.
Constructor & Destructor Documentation
SuiTransferBoxImplementation::SuiTransferBoxImplementation (CreatureObject * player, unsigned int windowType)
Definition at line 323 of file SuiTransferBox.cpp.
References _initializeImplementation().
SuiTransferBoxImplementation::SuiTransferBoxImplementation (DummyConstructorParameter * param)
Definition at line 113 of file SuiTransferBox.cpp.
References _initializeImplementation().
SuiTransferBoxImplementation::~SuiTransferBoxImplementation () protected virtual
Definition at line 118 of file SuiTransferBox.cpp.
Member Function Documentation
DistributedObjectStub * SuiTransferBoxImplementation::_getStub ()
Definition at line 138 of file SuiTransferBox.cpp.
References _this.
void SuiTransferBoxImplementation::_initializeImplementation () protected
Definition at line 125 of file SuiTransferBox.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SuiTransferBoxImplementation().
void SuiTransferBoxImplementation::_serializationHelperMethod () protected
Definition at line 174 of file SuiTransferBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void SuiTransferBoxImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 133 of file SuiTransferBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_setStub(), and _this.
Referenced by server::zone::objects::player::sui::messagebox::SuiTransferBox::SuiTransferBox().
void SuiTransferBoxImplementation::addFrom (const String & from, const String & startingFrom, const String & inputFrom, const String & rFrom)
Definition at line 44 of file SuiTransferBoxImplementation.cpp.
References convertRatioFrom, lblFrom, lblInputFrom, and lblStartingFrom.
Referenced by server::zone::objects::player::sui::messagebox::SuiTransferBox::addFrom().
void SuiTransferBoxImplementation::addTo (const String & to, const String & startingTo, const String & inputTo, const String & rTo)
Definition at line 54 of file SuiTransferBoxImplementation.cpp.
References convertRatioTo, lblInputTo, lblStartingTo, and lblTo.
Referenced by server::zone::objects::player::sui::messagebox::SuiTransferBox::addTo().
void SuiTransferBoxImplementation::finalize () protected
Definition at line 122 of file SuiTransferBox.cpp.
BaseMessage * SuiTransferBoxImplementation::generateMessage () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 10 of file SuiTransferBoxImplementation.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::addHeader(), server::zone::objects::player::sui::SuiBoxImplementation::addSetting(), server::zone::objects::player::sui::SuiBoxImplementation::boxID, convertRatioFrom, convertRatioTo, server::zone::objects::player::sui::SuiBoxImplementation::generateBody(), server::zone::objects::player::sui::SuiBoxImplementation::generateFooter(), server::zone::objects::player::sui::SuiBoxImplementation::generateHeader(), server::zone::objects::player::sui::SuiBoxImplementation::hasGenerated, lblFrom, lblInputFrom, lblInputTo, lblStartingFrom, lblStartingTo, lblTo, server::zone::objects::player::sui::SuiBoxImplementation::promptText, server::zone::objects::player::sui::SuiBoxImplementation::promptTitle, and server::zone::objects::player::sui::SuiBoxImplementation::setHandlerText().
Referenced by server::zone::objects::player::sui::messagebox::SuiTransferBox::generateMessage().
bool SuiTransferBoxImplementation::isTransferBox () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 327 of file SuiTransferBox.cpp.
Referenced by server::zone::objects::player::sui::messagebox::SuiTransferBox::isTransferBox().
void SuiTransferBoxImplementation::lock (bool doLock = true) protected
Definition at line 146 of file SuiTransferBox.cpp.
References _this.
void SuiTransferBoxImplementation::lock (ManagedObject * obj) protected
Definition at line 150 of file SuiTransferBox.cpp.
References _this.
SuiTransferBoxImplementation::operator const SuiTransferBox * ()
Definition at line 142 of file SuiTransferBox.cpp.
void SuiTransferBoxImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 181 of file SuiTransferBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::initializeTransientMembers(), and readObjectMember().
bool SuiTransferBoxImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 200 of file SuiTransferBox.cpp.
References convertRatioFrom, convertRatioTo, lblFrom, lblInputFrom, lblInputTo, lblStartingFrom, lblStartingTo, lblTo, and server::zone::objects::player::sui::SuiBoxImplementation::readObjectMember().
Referenced by readObject().
void SuiTransferBoxImplementation::rlock (bool doLock = true) protected
Definition at line 154 of file SuiTransferBox.cpp.
References _this.
void SuiTransferBoxImplementation::runlock (bool doLock = true) protected
Definition at line 170 of file SuiTransferBox.cpp.
References _this.
void SuiTransferBoxImplementation::unlock (bool doLock = true) protected
Definition at line 166 of file SuiTransferBox.cpp.
References _this.
void SuiTransferBoxImplementation::wlock (bool doLock = true) protected
Definition at line 158 of file SuiTransferBox.cpp.
References _this.
void SuiTransferBoxImplementation::wlock (ManagedObject * obj) protected
Definition at line 162 of file SuiTransferBox.cpp.
References _this.
void SuiTransferBoxImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 242 of file SuiTransferBox.cpp.
References writeObjectMembers().
int SuiTransferBoxImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 249 of file SuiTransferBox.cpp.
References convertRatioFrom, convertRatioTo, lblFrom, lblInputFrom, lblInputTo, lblStartingFrom, lblStartingTo, lblTo, and server::zone::objects::player::sui::SuiBoxImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class SuiTransferBox friend
Definition at line 177 of file SuiTransferBox.h.
Member Data Documentation
WeakReference<SuiTransferBox*> server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::_this
Definition at line 143 of file SuiTransferBox.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
String server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::convertRatioFrom protected
Definition at line 126 of file SuiTransferBox.h.
Referenced by addFrom(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::convertRatioTo protected
Definition at line 128 of file SuiTransferBox.h.
Referenced by addTo(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::lblFrom protected
Definition at line 114 of file SuiTransferBox.h.
Referenced by addFrom(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::lblInputFrom protected
Definition at line 118 of file SuiTransferBox.h.
Referenced by addFrom(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::lblInputTo protected
Definition at line 124 of file SuiTransferBox.h.
Referenced by addTo(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::lblStartingFrom protected
Definition at line 116 of file SuiTransferBox.h.
Referenced by addFrom(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::lblStartingTo protected
Definition at line 122 of file SuiTransferBox.h.
Referenced by addTo(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::lblTo protected
Definition at line 120 of file SuiTransferBox.h.
Referenced by addTo(), generateMessage(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/transferbox/SuiTransferBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/transferbox/SuiTransferBox.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/transferbox/SuiTransferBoxImplementation.cpp