Core3: TreeArchive Class Reference
TreeArchive Class Reference
#include <TreeArchive.h>
Public Member Functions
TreeArchive ()
void unpackFile (const String &file)
void addRecord (const String &path, TreeFileRecord *record)
TreeDirectory * getTreeDirectory (const String &path)
byte * getBytes (const String &recordPath, int &size)
TreeDirectory * getDirectory (const String &path)
Vector< String > * getFilesAndSubDirectoryFiles (const String &directory)
Private Attributes
HashTable< String, Reference
< TreeDirectory * > > nodeMap
Detailed Description
Definition at line 15 of file TreeArchive.h.
Constructor & Destructor Documentation
TreeArchive::TreeArchive () inline
Definition at line 19 of file TreeArchive.h.
References nodeMap.
Member Function Documentation
void TreeArchive::addRecord (const String & path, TreeFileRecord * record) inline
Definition at line 34 of file TreeArchive.h.
References nodeMap, and TreeFileRecord::setRecordName().
Referenced by TreeFile::readNameBlock().
byte* TreeArchive::getBytes (const String & recordPath, int & size) inline
Gets a byte buffer from the specified path. Don't forget to delete the pointer when finished.
Definition at line 65 of file TreeArchive.h.
References TreeDirectory::find(), and nodeMap.
Referenced by DataArchiveStore::getData().
TreeDirectory* TreeArchive::getDirectory (const String & path) inline
Definition at line 94 of file TreeArchive.h.
References nodeMap.
Vector<String>* TreeArchive::getFilesAndSubDirectoryFiles (const String & directory) inline
Definition at line 98 of file TreeArchive.h.
References TreeFileRecord::getRecordName(), and nodeMap.
Referenced by server::zone::managers::stringid::StringIdManager::populateDatabase().
TreeDirectory* TreeArchive::getTreeDirectory (const String & path) inline
Definition at line 57 of file TreeArchive.h.
References nodeMap.
void TreeArchive::unpackFile (const String & file) inline
Definition at line 28 of file TreeArchive.h.
References TreeFile::read().
Referenced by DataArchiveStore::loadTres().
Member Data Documentation
HashTable<String, Reference<TreeDirectory*> > TreeArchive::nodeMap private
Definition at line 16 of file TreeArchive.h.
Referenced by addRecord(), getBytes(), getDirectory(), getFilesAndSubDirectoryFiles(), getTreeDirectory(), and TreeArchive().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/tre3/TreeArchive.h