Core3: server::web::HttpRequest Class Reference
server::web::HttpRequest Class Reference
#include <HttpRequest.h>
Public Member Functions
HttpRequest (HttpSession *session)
virtual ~HttpRequest ()
void update (const struct mg_request_info *request_info)
String getBaseContext ()
String getUri ()
String getRequestMethod ()
String getHeader (String key)
String getParameter (String key)
uint64 getRemoteIp ()
HttpSession * getSession ()
void updatePostData (String data)
Private Attributes
String requestMethod
Request members.
String uri
String httpVersion
uint64 remoteIp
short remotePort
short statusCode
bool ssl
String userData
Vector< String > contexts
VectorMap< String, String > headers
VectorMap< String, String > parameters
HttpSession * session
Detailed Description
Definition at line 18 of file HttpRequest.h.
Constructor & Destructor Documentation
HttpRequest::HttpRequest (HttpSession * session)
Definition at line 11 of file HttpRequest.cpp.
References session.
HttpRequest::~HttpRequest () virtual
Definition at line 17 of file HttpRequest.cpp.
Member Function Documentation
String HttpRequest::getBaseContext ()
Definition at line 83 of file HttpRequest.cpp.
References contexts.
Referenced by server::web::WebServer::handleRequest().
String server::web::HttpRequest::getHeader (String key) inline
Definition at line 54 of file HttpRequest.h.
References headers.
Referenced by server::web::WebServer::getSession().
String server::web::HttpRequest::getParameter (String key) inline
Definition at line 62 of file HttpRequest.h.
References parameters.
Referenced by LoginServlet::handlePost(), and PermissionsServlet::handlePost().
uint64 server::web::HttpRequest::getRemoteIp () inline
Definition at line 69 of file HttpRequest.h.
References remoteIp.
Referenced by LoginServlet::handlePost().
String server::web::HttpRequest::getRequestMethod () inline
Definition at line 50 of file HttpRequest.h.
References requestMethod.
Referenced by Servlet::handleRequest().
HttpSession* server::web::HttpRequest::getSession () inline
Definition at line 73 of file HttpRequest.h.
References session.
Referenced by LoginServlet::handleGet(), and LoginServlet::handlePost().
String server::web::HttpRequest::getUri () inline
Definition at line 46 of file HttpRequest.h.
References uri.
Referenced by server::web::WebServer::handleRequest().
void HttpRequest::update (const struct mg_request_info * request_info)
Definition at line 21 of file HttpRequest.cpp.
References contexts, headers, mg_request_info::http_headers, mg_request_info::http_version, httpVersion, mg_request_info::is_ssl, mg_request_info::mg_header::name, mg_request_info::num_headers, mg_request_info::remote_ip, mg_request_info::remote_port, remoteIp, remotePort, mg_request_info::request_method, requestMethod, ssl, mg_request_info::status_code, statusCode, uri, mg_request_info::uri, and mg_request_info::mg_header::value.
Referenced by server::web::session::HttpSession::update().
void HttpRequest::updatePostData (String data)
Definition at line 53 of file HttpRequest.cpp.
References parameters.
Referenced by server::web::WebServer::getSession().
Member Data Documentation
Vector<String> server::web::HttpRequest::contexts private
Definition at line 30 of file HttpRequest.h.
Referenced by getBaseContext(), and update().
VectorMap<String, String> server::web::HttpRequest::headers private
Definition at line 32 of file HttpRequest.h.
Referenced by getHeader(), and update().
String server::web::HttpRequest::httpVersion private
Definition at line 23 of file HttpRequest.h.
Referenced by update().
VectorMap<String, String> server::web::HttpRequest::parameters private
Definition at line 34 of file HttpRequest.h.
Referenced by getParameter(), and updatePostData().
uint64 server::web::HttpRequest::remoteIp private
Definition at line 24 of file HttpRequest.h.
Referenced by getRemoteIp(), and update().
short server::web::HttpRequest::remotePort private
Definition at line 25 of file HttpRequest.h.
Referenced by update().
String server::web::HttpRequest::requestMethod private
Request members.
Definition at line 21 of file HttpRequest.h.
Referenced by getRequestMethod(), and update().
HttpSession* server::web::HttpRequest::session private
Definition at line 36 of file HttpRequest.h.
Referenced by getSession(), and HttpRequest().
bool server::web::HttpRequest::ssl private
Definition at line 27 of file HttpRequest.h.
Referenced by update().
short server::web::HttpRequest::statusCode private
Definition at line 26 of file HttpRequest.h.
Referenced by update().
String server::web::HttpRequest::uri private
Definition at line 22 of file HttpRequest.h.
Referenced by getUri(), and update().
String server::web::HttpRequest::userData private
Definition at line 28 of file HttpRequest.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/HttpRequest.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/HttpRequest.cpp