Core3: PlaceStructureComponent Class Reference
PlaceStructureComponent Class Reference
#include <PlaceStructureComponent.h>
Public Member Functions
virtual int placeStructure (StructureDeed *deed, CreatureObject *creature, float x, float y, int angle)
virtual int notifyStructurePlaced (StructureDeed *deed, CreatureObject *creature, StructureObject *structure)
Detailed Description
Definition at line 37 of file PlaceStructureComponent.h.
Member Function Documentation
int PlaceStructureComponent::notifyStructurePlaced (StructureDeed * deed, CreatureObject * creature, StructureObject * structure) virtual
Reimplemented in PlaceCityHallComponent, and PlaceGCWBaseComponent.
Definition at line 27 of file PlaceStructureComponent.cpp.
References server::zone::objects::tangible::deed::structure::StructureDeed::getExtractionRate(), server::zone::objects::tangible::deed::structure::StructureDeed::getHopperSize(), server::zone::objects::tangible::deed::structure::StructureDeed::getSurplusMaintenance(), server::zone::objects::tangible::deed::structure::StructureDeed::getSurplusPower(), server::zone::objects::scene::SceneObject::isInstallationObject(), server::zone::objects::installation::InstallationObject::setExtractionRate(), server::zone::objects::installation::InstallationObject::setHopperSizeMax(), server::zone::objects::structure::StructureObject::setSurplusMaintenance(), and server::zone::objects::structure::StructureObject::setSurplusPower().
Referenced by PlaceCityHallComponent::notifyStructurePlaced(), and PlaceGCWBaseComponent::notifyStructurePlaced().
int PlaceStructureComponent::placeStructure (StructureDeed * deed, CreatureObject * creature, float x, float y, int angle) virtual
Reimplemented in PlaceCityHallComponent, PlaceDecorationComponent, and PlaceGCWBaseComponent.
Definition at line 18 of file PlaceStructureComponent.cpp.
References server::zone::objects::scene::SceneObject::getZone().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/deed/components/PlaceStructureComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/deed/components/PlaceStructureComponent.cpp