Core3: CityManagementMenuComponent Class Reference
CityManagementMenuComponent Class Reference
#include <CityManagementMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file CityManagementMenuComponent.h.
Member Function Documentation
void CityManagementMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from ObjectMenuComponent.
Definition at line 20 of file CityManagementMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID(), server::zone::objects::scene::SceneObject::error(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getObjectID(), and server::zone::objects::creature::CreatureObject::getPlayerObject().
int CityManagementMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from ObjectMenuComponent.
Definition at line 77 of file CityManagementMenuComponent.cpp.
References server::zone::managers::city::CityManager::contractCity(), server::zone::managers::city::CityManager::expandCity(), server::zone::managers::city::CityManager::fixMayor(), server::zone::ZoneServer::getCityManager(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::managers::city::CityManager::processCityUpdate(), server::zone::managers::city::CityManager::promptAdjustTaxes(), server::zone::managers::city::CityManager::promptCitySpecialization(), server::zone::managers::city::CityManager::promptDepositCityTreasury(), server::zone::managers::city::CityManager::promptRegisterCity(), server::zone::managers::city::CityManager::promptUnregisterCity(), server::zone::managers::city::CityManager::promptWithdrawCityTreasury(), server::zone::managers::city::CityManager::sendChangeCityName(), server::zone::managers::city::CityManager::sendCitizenshipReport(), server::zone::managers::city::CityManager::sendCityAdvancement(), server::zone::managers::city::CityManager::sendMaintenanceReport(), server::zone::managers::city::CityManager::sendManageMilitia(), server::zone::managers::city::CityManager::sendStatusReport(), server::zone::managers::city::CityManager::sendStructureReport(), server::zone::managers::city::CityManager::sendTreasuryReport(), server::zone::managers::city::CityManager::toggleZoningEnabled(), and server::zone::managers::city::CityManager::updateCityVoting().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/region/components/CityManagementMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/region/components/CityManagementMenuComponent.cpp