Core3: ObjectMenuComponent Class Reference
ObjectMenuComponent Class Reference
#include <ObjectMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 40 of file ObjectMenuComponent.h.
Member Function Documentation
void ObjectMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented in LuaObjectMenuComponent, ForceShrineMenuComponent, HQMenuComponent, BankTerminalMenuComponent, SecurityTerminalMenuComponent, UplinkTerminalMenuComponent, MinefieldMenuComponent, OverrideTerminalMenuComponent, PowerRegulatorMenuComponent, TurretControlMenuComponent, BountyHunterDroidMenuComponent, DiceMenuComponent, ArmorObjectMenuComponent, CampTerminalMenuComponent, CityDecorationMenuComponent, CreatureHabitatMenuComponent, FireworkShowMenuComponent, TrainerMenuComponent, PlayerObjectMenuComponent, CampKitMenuComponent, CloningTerminalMenuComponent, ArtCrateMenuComponent, LootSchematicMenuComponent, ShellfishHarvesterMenuComponent, GogglesObjectMenuComponent, InsuranceTerminalMenuComponent, LairMenuComponent, LightsaberObjectMenuComponent, RobeObjectMenuComponent, SkillBuffObjectMenuComponent, TangibleObjectMenuComponent, TrapMenuComponent, VehicleCustomKitObjectMenuComponent, VendorMenuComponent, WeaponObjectMenuComponent, WearableObjectMenuComponent, FireworkMenuComponent, FactoryObjectMenuComponent, InstallationObjectMenuComponent, ElevatorDownMenuComponent, ElevatorMenuComponent, ElevatorUpMenuComponent, FireHeavyWeaponMenuComponent, StructureTerminalMenuComponent, CityManagementMenuComponent, CityVotingMenuComponent, and ThrowGrenadeMenuComponent.
Definition at line 15 of file ObjectMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID(), server::zone::objects::scene::SceneObject::getParent(), and server::zone::objects::scene::SceneObject::isPlayerCreature().
Referenced by TangibleObjectMenuComponent::fillObjectMenuResponse().
int ObjectMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented in LuaObjectMenuComponent, HQMenuComponent, BankTerminalMenuComponent, ForceShrineMenuComponent, HolocronMenuComponent, SecurityTerminalMenuComponent, UplinkTerminalMenuComponent, MinefieldMenuComponent, OverrideTerminalMenuComponent, PowerRegulatorMenuComponent, TurretControlMenuComponent, BountyHunterDroidMenuComponent, DiceMenuComponent, ArmorObjectMenuComponent, CampTerminalMenuComponent, CityDecorationMenuComponent, CreatureHabitatMenuComponent, FireworkShowMenuComponent, TrainerMenuComponent, PlayerObjectMenuComponent, CampKitMenuComponent, CloningTerminalMenuComponent, ArtCrateMenuComponent, LootSchematicMenuComponent, ShellfishHarvesterMenuComponent, GogglesObjectMenuComponent, InsuranceTerminalMenuComponent, LairMenuComponent, LightsaberObjectMenuComponent, RobeObjectMenuComponent, SkillBuffObjectMenuComponent, TangibleObjectMenuComponent, TrapMenuComponent, VehicleCustomKitObjectMenuComponent, VendorMenuComponent, WeaponObjectMenuComponent, WearableObjectMenuComponent, FireworkMenuComponent, FireHeavyWeaponMenuComponent, FactoryObjectMenuComponent, InstallationObjectMenuComponent, ElevatorDownMenuComponent, ElevatorMenuComponent, ElevatorUpMenuComponent, ThrowGrenadeMenuComponent, StructureTerminalMenuComponent, CityManagementMenuComponent, and CityVotingMenuComponent.
Definition at line 55 of file ObjectMenuComponent.cpp.
Referenced by TangibleObjectMenuComponent::handleObjectMenuSelect().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/components/ObjectMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/components/ObjectMenuComponent.cpp