Core3: server::zone::objects::player::sui::messagebox::SuiMessageBoxAdapter Class Reference
server::zone::objects::player::sui::messagebox::SuiMessageBoxAdapter Class Reference
#include <SuiMessageBox.h>
Public Member Functions
SuiMessageBoxAdapter (SuiMessageBox *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
BaseMessage * generateMessage ()
bool isMessageBox ()
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxAdapter
SuiBoxAdapter (SuiBox *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type)
BaseMessage * generateMessage ()
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
bool isInputBox ()
bool isListBox ()
bool isMessageBox ()
bool isTransferBox ()
bool isBankTransferBox ()
bool isSlicingBox ()
bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
Detailed Description
Definition at line 156 of file SuiMessageBox.h.
Constructor & Destructor Documentation
SuiMessageBoxAdapter::SuiMessageBoxAdapter (SuiMessageBox * impl)
Definition at line 211 of file SuiMessageBox.cpp.
Member Function Documentation
BaseMessage * SuiMessageBoxAdapter::generateMessage ()
Definition at line 233 of file SuiMessageBox.cpp.
Referenced by invokeMethod().
void SuiMessageBoxAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 214 of file SuiMessageBox.cpp.
References generateMessage(), isMessageBox(), RPC_GENERATEMESSAGE__, and RPC_ISMESSAGEBOX__.
bool SuiMessageBoxAdapter::isMessageBox ()
Definition at line 237 of file SuiMessageBox.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/messagebox/SuiMessageBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/messagebox/SuiMessageBox.cpp