Core3: server::zone::managers::auction::AuctionsMapAdapter Class Reference
server::zone::managers::auction::AuctionsMapAdapter Class Reference
#include <AuctionsMap.h>
Public Member Functions
AuctionsMapAdapter (AuctionsMap *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int addItem (CreatureObject *player, SceneObject *vendor, AuctionItem *item)
void deleteItem (SceneObject *vendor, AuctionItem *item)
AuctionItem * getItem (unsigned long long id)
bool containsItem (unsigned long long id)
int getVendorItemCount (SceneObject *vendor)
void deleteTerminalItems (SceneObject *vendor)
int getCommodityCount (CreatureObject *player)
void updateUID (SceneObject *vendor, const String &oldUID, const String &newUID)
void updateVendorSearch (SceneObject *vendor, bool enabled)
void addToCommodityLimit (AuctionItem *item)
void removeFromCommodityLimit (AuctionItem *item)
int getBazaarCount ()
int getVendorCount ()
int getTotalItemCount ()
Detailed Description
Definition at line 228 of file AuctionsMap.h.
Constructor & Destructor Documentation
AuctionsMapAdapter::AuctionsMapAdapter (AuctionsMap * impl)
Definition at line 448 of file AuctionsMap.cpp.
Member Function Documentation
int AuctionsMapAdapter::addItem (CreatureObject * player, SceneObject * vendor, AuctionItem * item)
Definition at line 531 of file AuctionsMap.cpp.
Referenced by invokeMethod().
void AuctionsMapAdapter::addToCommodityLimit (AuctionItem * item)
Definition at line 567 of file AuctionsMap.cpp.
Referenced by invokeMethod().
bool AuctionsMapAdapter::containsItem (unsigned long long id)
Definition at line 543 of file AuctionsMap.cpp.
Referenced by invokeMethod().
void AuctionsMapAdapter::deleteItem (SceneObject * vendor, AuctionItem * item)
Definition at line 535 of file AuctionsMap.cpp.
Referenced by invokeMethod().
void AuctionsMapAdapter::deleteTerminalItems (SceneObject * vendor)
Definition at line 551 of file AuctionsMap.cpp.
Referenced by invokeMethod().
int AuctionsMapAdapter::getBazaarCount ()
Definition at line 575 of file AuctionsMap.cpp.
Referenced by invokeMethod().
int AuctionsMapAdapter::getCommodityCount (CreatureObject * player)
Definition at line 555 of file AuctionsMap.cpp.
Referenced by invokeMethod().
AuctionItem * AuctionsMapAdapter::getItem (unsigned long long id)
Definition at line 539 of file AuctionsMap.cpp.
Referenced by invokeMethod().
int AuctionsMapAdapter::getTotalItemCount ()
Definition at line 583 of file AuctionsMap.cpp.
Referenced by invokeMethod().
int AuctionsMapAdapter::getVendorCount ()
Definition at line 579 of file AuctionsMap.cpp.
Referenced by invokeMethod().
int AuctionsMapAdapter::getVendorItemCount (SceneObject * vendor)
Definition at line 547 of file AuctionsMap.cpp.
Referenced by invokeMethod().
void AuctionsMapAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 451 of file AuctionsMap.cpp.
References addItem(), addToCommodityLimit(), containsItem(), deleteItem(), deleteTerminalItems(), getBazaarCount(), getCommodityCount(), getItem(), getTotalItemCount(), getVendorCount(), getVendorItemCount(), removeFromCommodityLimit(), RPC_ADDITEM__CREATUREOBJECT_SCENEOBJECT_AUCTIONITEM_, RPC_ADDTOCOMMODITYLIMIT__AUCTIONITEM_, RPC_CONTAINSITEM__LONG_, RPC_DELETEITEM__SCENEOBJECT_AUCTIONITEM_, RPC_DELETETERMINALITEMS__SCENEOBJECT_, RPC_GETBAZAARCOUNT__, RPC_GETCOMMODITYCOUNT__CREATUREOBJECT_, RPC_GETITEM__LONG_, RPC_GETTOTALITEMCOUNT__, RPC_GETVENDORCOUNT__, RPC_GETVENDORITEMCOUNT__SCENEOBJECT_, RPC_REMOVEFROMCOMMODITYLIMIT__AUCTIONITEM_, RPC_UPDATEUID__SCENEOBJECT_STRING_STRING_, RPC_UPDATEVENDORSEARCH__SCENEOBJECT_BOOL_, updateUID(), and updateVendorSearch().
void AuctionsMapAdapter::removeFromCommodityLimit (AuctionItem * item)
Definition at line 571 of file AuctionsMap.cpp.
Referenced by invokeMethod().
void AuctionsMapAdapter::updateUID (SceneObject * vendor, const String & oldUID, const String & newUID)
Definition at line 559 of file AuctionsMap.cpp.
Referenced by invokeMethod().
void AuctionsMapAdapter::updateVendorSearch (SceneObject * vendor, bool enabled)
Definition at line 563 of file AuctionsMap.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionsMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionsMap.cpp