Core3: server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation Class Reference
server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation Class Reference
#include <CreateVendorSession.h>
Public Member Functions
CreateVendorSessionImplementation (CreatureObject *play)
CreateVendorSessionImplementation (DummyConstructorParameter *param)
int initializeSession ()
int cancelSession ()
int clearSession ()
void handleVendorSelection (byte menuID)
void createVendor (String &name)
operator const CreateVendorSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< CreateVendorSession * > _this
Protected Member Functions
virtual ~CreateVendorSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference
< CreatureObject * > player
ManagedReference< SuiListBox * > suiSelectVendor
ManagedReference< SuiInputBox * > suiNameVendor
Private Member Functions
void randomizeVendorLooks (CreatureObject *vendor)
Private Attributes
Reference< VendorSelectionNode * > currentNode
String templatePath
Friends
class CreateVendorSession
Detailed Description
Definition at line 138 of file CreateVendorSession.h.
Constructor & Destructor Documentation
CreateVendorSessionImplementation::CreateVendorSessionImplementation (CreatureObject * play)
Definition at line 296 of file CreateVendorSession.cpp.
References _initializeImplementation(), player, and suiNameVendor.
CreateVendorSessionImplementation::CreateVendorSessionImplementation (DummyConstructorParameter * param)
Definition at line 122 of file CreateVendorSession.cpp.
References _initializeImplementation().
CreateVendorSessionImplementation::~CreateVendorSessionImplementation () protected virtual
Definition at line 127 of file CreateVendorSession.cpp.
Member Function Documentation
DistributedObjectStub * CreateVendorSessionImplementation::_getStub ()
Definition at line 147 of file CreateVendorSession.cpp.
References _this.
void CreateVendorSessionImplementation::_initializeImplementation () protected
Definition at line 134 of file CreateVendorSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CreateVendorSessionImplementation().
void CreateVendorSessionImplementation::_serializationHelperMethod () protected
Definition at line 183 of file CreateVendorSession.cpp.
Referenced by _initializeImplementation().
void CreateVendorSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 142 of file CreateVendorSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSession::CreateVendorSession().
int CreateVendorSessionImplementation::cancelSession ()
Definition at line 308 of file CreateVendorSession.cpp.
References clearSession(), SessionFacadeType::CREATEVENDOR, and player.
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSession::cancelSession(), createVendor(), and initializeSession().
int CreateVendorSessionImplementation::clearSession ()
Definition at line 318 of file CreateVendorSession.cpp.
References currentNode, player, suiNameVendor, and suiSelectVendor.
Referenced by cancelSession(), and server::zone::objects::player::sessions::vendor::CreateVendorSession::clearSession().
void CreateVendorSessionImplementation::createVendor (String & name)
Definition at line 113 of file CreateVendorSessionImplementation.cpp.
References cancelSession(), server::zone::objects::player::sui::messagebox::SuiInputBox::generateMessage(), server::zone::objects::scene::SceneObject::getSlottedObject(), player, randomizeVendorLooks(), server::zone::objects::player::sui::SuiBox::setCallback(), server::zone::objects::player::sui::SuiBox::setCancelButton(), VendorDataComponent::setOwnerId(), server::zone::objects::player::sui::SuiBox::setPromptText(), server::zone::objects::player::sui::SuiBox::setPromptTitle(), SuiWindowType::STRUCTURE_NAME_VENDOR, and templatePath.
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSession::createVendor().
void CreateVendorSessionImplementation::finalize () protected
Definition at line 131 of file CreateVendorSession.cpp.
void CreateVendorSessionImplementation::handleVendorSelection (byte menuID)
If there are selections available for vendors
Definition at line 72 of file CreateVendorSessionImplementation.cpp.
References VendorSelectionNode::addChildrenToListBox(), currentNode, server::zone::objects::player::sui::messagebox::SuiInputBox::generateMessage(), VendorSelectionNode::getRandomTemplate(), VendorSelectionNode::getSuiDisplay(), VendorSelectionNode::getTemplatePath(), VendorSelectionNode::hasChildNode(), player, server::zone::objects::player::sui::SuiBox::setCallback(), server::zone::objects::player::sui::SuiBox::setCancelButton(), server::zone::objects::player::sui::SuiBox::setPromptText(), server::zone::objects::player::sui::SuiBox::setPromptTitle(), SuiWindowType::STRUCTURE_NAME_VENDOR, suiSelectVendor, and templatePath.
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSession::handleVendorSelection().
int CreateVendorSessionImplementation::initializeSession ()
Definition at line 25 of file CreateVendorSessionImplementation.cpp.
References _this, cancelSession(), SessionFacadeType::CREATEVENDOR, currentNode, player, SuiWindowType::STRUCTURE_CREATE_VENDOR, suiSelectVendor, and templatePath.
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSession::initializeSession().
void CreateVendorSessionImplementation::lock (bool doLock = true) protected
Definition at line 155 of file CreateVendorSession.cpp.
References _this.
void CreateVendorSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 159 of file CreateVendorSession.cpp.
References _this.
CreateVendorSessionImplementation::operator const CreateVendorSession * ()
Definition at line 151 of file CreateVendorSession.cpp.
void CreateVendorSessionImplementation::randomizeVendorLooks (CreatureObject * vendor) private
Definition at line 196 of file CreateVendorSessionImplementation.cpp.
References VendorCreatureTemplate::getHairFile(), VendorCreatureTemplate::getHairSize(), server::zone::objects::scene::SceneObject::getObjectTemplate(), VendorCreatureTemplate::getOutfitName(), VendorCreatureTemplate::getOutfitsSize(), server::zone::objects::scene::SceneObject::getSlottedObject(), player, and server::zone::objects::scene::SceneObject::transferObject().
Referenced by createVendor().
void CreateVendorSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 190 of file CreateVendorSession.cpp.
References readObjectMember().
bool CreateVendorSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 209 of file CreateVendorSession.cpp.
References currentNode, player, suiNameVendor, suiSelectVendor, and templatePath.
Referenced by readObject().
void CreateVendorSessionImplementation::rlock (bool doLock = true) protected
Definition at line 163 of file CreateVendorSession.cpp.
References _this.
void CreateVendorSessionImplementation::runlock (bool doLock = true) protected
Definition at line 179 of file CreateVendorSession.cpp.
References _this.
void CreateVendorSessionImplementation::unlock (bool doLock = true) protected
Definition at line 175 of file CreateVendorSession.cpp.
References _this.
void CreateVendorSessionImplementation::wlock (bool doLock = true) protected
Definition at line 167 of file CreateVendorSession.cpp.
References _this.
void CreateVendorSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 171 of file CreateVendorSession.cpp.
References _this.
void CreateVendorSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 239 of file CreateVendorSession.cpp.
References writeObjectMembers().
int CreateVendorSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 246 of file CreateVendorSession.cpp.
References currentNode, player, suiNameVendor, suiSelectVendor, and templatePath.
Referenced by writeObject().
Friends And Related Function Documentation
friend class CreateVendorSession friend
Definition at line 206 of file CreateVendorSession.h.
Member Data Documentation
WeakReference<CreateVendorSession*> server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::_this
Definition at line 172 of file CreateVendorSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), initializeSession(), lock(), rlock(), runlock(), unlock(), and wlock().
Reference<VendorSelectionNode* > server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::currentNode private
Definition at line 143 of file CreateVendorSession.h.
Referenced by clearSession(), handleVendorSelection(), initializeSession(), readObjectMember(), and writeObjectMembers().
ManagedReference<CreatureObject* > server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::player protected
Definition at line 140 of file CreateVendorSession.h.
Referenced by cancelSession(), clearSession(), createVendor(), CreateVendorSessionImplementation(), handleVendorSelection(), initializeSession(), randomizeVendorLooks(), readObjectMember(), and writeObjectMembers().
ManagedReference<SuiInputBox* > server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::suiNameVendor protected
Definition at line 148 of file CreateVendorSession.h.
Referenced by clearSession(), CreateVendorSessionImplementation(), readObjectMember(), and writeObjectMembers().
ManagedReference<SuiListBox* > server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::suiSelectVendor protected
Definition at line 146 of file CreateVendorSession.h.
Referenced by clearSession(), handleVendorSelection(), initializeSession(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::templatePath private
Definition at line 151 of file CreateVendorSession.h.
Referenced by createVendor(), handleVendorSelection(), initializeSession(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/CreateVendorSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/CreateVendorSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/CreateVendorSessionImplementation.cpp