Core3: server::zone::managers::holocron::HolocronManager Class Reference
server::zone::managers::holocron::HolocronManager Class Reference
#include <HolocronManager.h>
Public Member Functions
HolocronManager (ZoneProcessServer *pserv)
void loadBugCategories ()
void sendRequestCategoriesResponseTo (ZoneClientSession *client)
void submitTicket (ZoneClientSession *client, const UnicodeString &ticketBody)
uint32 getReporterId (ZoneClientSession *client)
uint32 createReporterId (ZoneClientSession *client)
String getTokenValue (const String &token, const UnicodeString &report)
uint32 getReproducibilityFromString (const String &str)
uint32 getSeverityFromString (const String &str)
Private Attributes
ZoneProcessServer * processor
SortedVector< BugCategory > categories
Detailed Description
Definition at line 28 of file HolocronManager.h.
Constructor & Destructor Documentation
server::zone::managers::holocron::HolocronManager::HolocronManager (ZoneProcessServer * pserv) inline
Definition at line 33 of file HolocronManager.h.
Member Function Documentation
uint32 HolocronManager::createReporterId (ZoneClientSession * client)
Definition at line 132 of file HolocronManager.cpp.
uint32 HolocronManager::getReporterId (ZoneClientSession * client)
Definition at line 98 of file HolocronManager.cpp.
References server::zone::managers::player::PlayerManager::getAccount(), server::zone::ZoneClientSession::getAccountID(), server::zone::ZoneProcessServer::getPlayerManager(), MantisDatabase::getTablePrefix(), server::zone::ZoneProcessServer::getZoneServer(), MantisDatabase::instance(), and processor.
Referenced by submitTicket().
uint32 HolocronManager::getReproducibilityFromString (const String & str)
Definition at line 154 of file HolocronManager.cpp.
Referenced by submitTicket().
uint32 HolocronManager::getSeverityFromString (const String & str)
Definition at line 143 of file HolocronManager.cpp.
Referenced by submitTicket().
String HolocronManager::getTokenValue (const String & token, const UnicodeString & report)
Definition at line 136 of file HolocronManager.cpp.
Referenced by submitTicket().
void HolocronManager::loadBugCategories ()
Definition at line 18 of file HolocronManager.cpp.
References BugCategory::addCategory(), categories, MantisDatabase::getTablePrefix(), and MantisDatabase::instance().
void HolocronManager::sendRequestCategoriesResponseTo (ZoneClientSession * client)
Definition at line 46 of file HolocronManager.cpp.
References categories, and server::zone::ZoneClientSession::sendMessage().
Referenced by RequestCategoriesMessageCallback::run().
void HolocronManager::submitTicket (ZoneClientSession * client, const UnicodeString & ticketBody)
Definition at line 51 of file HolocronManager.cpp.
References getReporterId(), getReproducibilityFromString(), getSeverityFromString(), MantisDatabase::getTablePrefix(), getTokenValue(), and MantisDatabase::instance().
Referenced by CreateTicketMessageCallback::run().
Member Data Documentation
SortedVector<BugCategory> server::zone::managers::holocron::HolocronManager::categories private
Definition at line 30 of file HolocronManager.h.
Referenced by loadBugCategories(), and sendRequestCategoriesResponseTo().
ZoneProcessServer* server::zone::managers::holocron::HolocronManager::processor private
Definition at line 29 of file HolocronManager.h.
Referenced by getReporterId().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/holocron/HolocronManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/holocron/HolocronManager.cpp