Core3: server::zone::ZoneClientSessionAdapter Class Reference
server::zone::ZoneClientSessionAdapter Class Reference
#include <ZoneClientSession.h>
Public Member Functions
ZoneClientSessionAdapter (ZoneClientSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void disconnect ()
void disconnect (bool doLock)
void sendMessage (BasePacket *msg)
void balancePacketCheckupTime ()
void resetPacketCheckupTime ()
void closeConnection (bool lockPlayer, bool doLock)
void info (const String &msg, bool force)
void error (const String &msg)
String getAddress ()
void setPlayer (SceneObject *playerCreature)
void setSessionID (unsigned int id)
void setAccountID (unsigned int acc)
int getCommandCount ()
void increaseCommandCount ()
void resetCommandCount ()
ManagedWeakReference
< SceneObject * > getPlayer ()
unsigned int getSessionID ()
unsigned int getAccountID ()
bool hasCharacter (unsigned long long cid, unsigned int galaxyId)
void addCharacter (unsigned long long cid, unsigned int galaxyId)
void addBannedCharacter (unsigned long long cid, unsigned int galaxyId)
int getCharacterCount ()
int getCharacterCount (int galaxyId)
void resetCharacters ()
Detailed Description
Definition at line 264 of file ZoneClientSession.h.
Constructor & Destructor Documentation
ZoneClientSessionAdapter::ZoneClientSessionAdapter (ZoneClientSession * impl)
Definition at line 685 of file ZoneClientSession.cpp.
Member Function Documentation
void ZoneClientSessionAdapter::addBannedCharacter (unsigned long long cid, unsigned int galaxyId)
Definition at line 899 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::addCharacter (unsigned long long cid, unsigned int galaxyId)
Definition at line 895 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::balancePacketCheckupTime ()
Definition at line 831 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::closeConnection (bool lockPlayer, bool doLock)
Definition at line 839 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::disconnect ()
Definition at line 819 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::disconnect (bool doLock)
Definition at line 823 of file ZoneClientSession.cpp.
void ZoneClientSessionAdapter::error (const String & msg)
Definition at line 847 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
unsigned int ZoneClientSessionAdapter::getAccountID ()
Definition at line 887 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
String ZoneClientSessionAdapter::getAddress ()
Definition at line 851 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
int ZoneClientSessionAdapter::getCharacterCount ()
Definition at line 903 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
int ZoneClientSessionAdapter::getCharacterCount (int galaxyId)
Definition at line 907 of file ZoneClientSession.cpp.
int ZoneClientSessionAdapter::getCommandCount ()
Definition at line 867 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
ManagedWeakReference< SceneObject * > ZoneClientSessionAdapter::getPlayer ()
Definition at line 879 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
unsigned int ZoneClientSessionAdapter::getSessionID ()
Definition at line 883 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
bool ZoneClientSessionAdapter::hasCharacter (unsigned long long cid, unsigned int galaxyId)
Definition at line 891 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::increaseCommandCount ()
Definition at line 871 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::info (const String & msg, bool force)
Definition at line 843 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 688 of file ZoneClientSession.cpp.
References addBannedCharacter(), addCharacter(), balancePacketCheckupTime(), closeConnection(), disconnect(), error(), getAccountID(), getAddress(), getCharacterCount(), getCommandCount(), getPlayer(), getSessionID(), hasCharacter(), increaseCommandCount(), info(), resetCharacters(), resetCommandCount(), resetPacketCheckupTime(), RPC_ADDBANNEDCHARACTER__LONG_INT_, RPC_ADDCHARACTER__LONG_INT_, RPC_BALANCEPACKETCHECKUPTIME__, RPC_CLOSECONNECTION__BOOL_BOOL_, RPC_DISCONNECT__, RPC_DISCONNECT__BOOL_, RPC_ERROR__STRING_, RPC_GETACCOUNTID__, RPC_GETADDRESS__, RPC_GETCHARACTERCOUNT__, RPC_GETCHARACTERCOUNT__INT_, RPC_GETCOMMANDCOUNT__, RPC_GETPLAYER__, RPC_GETSESSIONID__, RPC_HASCHARACTER__LONG_INT_, RPC_INCREASECOMMANDCOUNT__, RPC_INFO__STRING_BOOL_, RPC_RESETCHARACTERS__, RPC_RESETCOMMANDCOUNT__, RPC_RESETPACKETCHECKUPTIME__, RPC_SENDMESSAGE__BASEPACKET_, RPC_SETACCOUNTID__INT_, RPC_SETPLAYER__SCENEOBJECT_, RPC_SETSESSIONID__INT_, sendMessage(), setAccountID(), setPlayer(), and setSessionID().
void ZoneClientSessionAdapter::resetCharacters ()
Definition at line 911 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::resetCommandCount ()
Definition at line 875 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::resetPacketCheckupTime ()
Definition at line 835 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::sendMessage (BasePacket * msg)
Definition at line 827 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::setAccountID (unsigned int acc)
Definition at line 863 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::setPlayer (SceneObject * playerCreature)
Definition at line 855 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
void ZoneClientSessionAdapter::setSessionID (unsigned int id)
Definition at line 859 of file ZoneClientSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneClientSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneClientSession.cpp