Core3: PlayerContainerComponent Class Reference
PlayerContainerComponent Class Reference
#include <PlayerContainerComponent.h>
Public Member Functions
int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Public Member Functions inherited from ContainerComponent
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
virtual bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
Detailed Description
Definition at line 11 of file PlayerContainerComponent.h.
Member Function Documentation
int PlayerContainerComponent::canAddObject (SceneObject * sceneObject, SceneObject * object, int containmentType, String & errorDescription) virtual
Evaluates if this object has the necessary free slots to be able to add the specified SceneObject
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be checked
error error string that the player will receive on error
Returns
returns 0 on success, or error code
Reimplemented from ContainerComponent.
Definition at line 19 of file PlayerContainerComponent.cpp.
References ContainerComponent::canAddObject(), server::zone::managers::player::PlayerManager::checkEncumbrancies(), server::zone::templates::SharedObjectTemplate::getFullTemplateString(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SharedTangibleObjectTemplate::getPlayerRaces(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::scene::SceneObject::isArmorObject(), server::zone::objects::tangible::TangibleObject::isImperial(), server::zone::objects::tangible::TangibleObject::isNeutral(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::tangible::TangibleObject::isRebel(), server::zone::objects::scene::SceneObject::isRobeObject(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::objects::scene::SceneObject::isWeaponObject(), TransferErrorCode::NOTENOUGHENCUMBRANCE, FactionStatus::ONLEAVE, and TransferErrorCode::PLAYERUSEMASKERROR.
int PlayerContainerComponent::notifyObjectInserted (SceneObject * sceneObject, SceneObject * object) virtual
Is called when this object has been inserted with an object
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 95 of file PlayerContainerComponent.cpp.
References server::zone::objects::creature::CreatureObject::addWearableObject(), server::zone::managers::player::PlayerManager::applyEncumbrancies(), server::zone::objects::tangible::TangibleObject::applySkillModsTo(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::isArmorObject(), server::zone::objects::creature::CreatureObject::isEntertaining(), server::zone::objects::scene::SceneObject::isInstrument(), server::zone::objects::player::PlayerObject::isJedi(), server::zone::objects::scene::SceneObject::isRobeObject(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::objects::scene::SceneObject::isWeaponObject(), ContainerComponent::notifyObjectInserted(), and server::zone::objects::creature::CreatureObject::stopEntertaining().
int PlayerContainerComponent::notifyObjectRemoved (SceneObject * sceneObject, SceneObject * object, SceneObject * destination) virtual
Is called when an object was removed
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 143 of file PlayerContainerComponent.cpp.
References server::zone::ZoneServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::isArmorObject(), server::zone::objects::scene::SceneObject::isInstrument(), server::zone::objects::creature::CreatureObject::isPlayingMusic(), server::zone::objects::scene::SceneObject::isRobeObject(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::objects::scene::SceneObject::isWeaponObject(), ContainerComponent::notifyObjectRemoved(), server::zone::managers::player::PlayerManager::removeEncumbrancies(), server::zone::objects::tangible::TangibleObject::removeSkillModsFrom(), server::zone::objects::creature::CreatureObject::removeWearableObject(), and server::zone::objects::creature::CreatureObject::stopEntertaining().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/components/PlayerContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/components/PlayerContainerComponent.cpp