Core3: server::chat::PersistentMessage Class Reference
server::chat::PersistentMessage Class Reference
#include <PersistentMessage.h>
Public Member Functions
PersistentMessage ()
void sendTo (CreatureObject *player, bool sendBody=true)
StringIdChatParameterVector * getStringIdParameters ()
WaypointChatParameterVector * getWaypointParameters ()
int getMailID ()
unsigned long long getObjectID ()
String getSenderName ()
unsigned long long getReceiverObjectID ()
byte getStatus ()
int getTimeStamp ()
UnicodeString getBody ()
UnicodeString getSubject ()
void setSenderName (const String &name)
void setReceiverObjectID (unsigned long long oid)
void setStatus (byte stat)
void setTimeStamp (int stamp)
void setBody (const UnicodeString &message)
void setSubject (const UnicodeString &subj)
bool isNew ()
bool isRead ()
bool isUnread ()
void addStringIdParameter (StringIdChatParameter &param)
void addWaypointParameter (WaypointChatParameter &param)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const byte NEW = 0x4E
static const byte READ = 0x52
static const byte UNREAD = 0x55
Protected Member Functions
PersistentMessage (DummyConstructorParameter *param)
virtual ~PersistentMessage ()
Friends
class PersistentMessageHelper
Detailed Description
Definition at line 47 of file PersistentMessage.h.
Constructor & Destructor Documentation
PersistentMessage::PersistentMessage ()
Definition at line 15 of file PersistentMessage.cpp.
References server::chat::PersistentMessageImplementation::_setStub().
PersistentMessage::PersistentMessage (DummyConstructorParameter * param) protected
Definition at line 22 of file PersistentMessage.cpp.
PersistentMessage::~PersistentMessage () protected virtual
Definition at line 26 of file PersistentMessage.cpp.
Member Function Documentation
DistributedObjectServant * PersistentMessage::_getImplementation ()
Definition at line 315 of file PersistentMessage.cpp.
Referenced by addStringIdParameter(), addWaypointParameter(), setBody(), setReceiverObjectID(), setSenderName(), setStatus(), setSubject(), and setTimeStamp().
DistributedObjectServant * PersistentMessage::_getImplementationForRead ()
Definition at line 321 of file PersistentMessage.cpp.
Referenced by getBody(), getMailID(), getObjectID(), getReceiverObjectID(), getSenderName(), getStatus(), getStringIdParameters(), getSubject(), getTimeStamp(), getWaypointParameters(), isNew(), isRead(), isUnread(), and sendTo().
void PersistentMessage::_setImplementation (DistributedObjectServant * servant)
Definition at line 325 of file PersistentMessage.cpp.
void PersistentMessage::addStringIdParameter (StringIdChatParameter & param)
Definition at line 297 of file PersistentMessage.cpp.
References _getImplementation(), and server::chat::PersistentMessageImplementation::addStringIdParameter().
void PersistentMessage::addWaypointParameter (WaypointChatParameter & param)
Definition at line 306 of file PersistentMessage.cpp.
References _getImplementation(), and server::chat::PersistentMessageImplementation::addWaypointParameter().
UnicodeString PersistentMessage::getBody ()
Definition at line 144 of file PersistentMessage.cpp.
References _getImplementationForRead(), server::chat::PersistentMessageImplementation::getBody(), and RPC_GETBODY__.
Referenced by ChatPersistentMessageToClient::ChatPersistentMessageToClient().
int PersistentMessage::getMailID ()
Definition at line 64 of file PersistentMessage.cpp.
References _getImplementationForRead(), server::chat::PersistentMessageImplementation::getMailID(), and RPC_GETMAILID__.
Referenced by ChatPersistentMessageToClient::ChatPersistentMessageToClient().
unsigned long long PersistentMessage::getObjectID ()
Definition at line 77 of file PersistentMessage.cpp.
References _getImplementationForRead(), server::chat::PersistentMessageImplementation::getObjectID(), and RPC_GETOBJECTID__.
unsigned long long PersistentMessage::getReceiverObjectID ()
Definition at line 105 of file PersistentMessage.cpp.
References _getImplementationForRead(), server::chat::PersistentMessageImplementation::getReceiverObjectID(), and RPC_GETRECEIVEROBJECTID__.
String PersistentMessage::getSenderName ()
Definition at line 90 of file PersistentMessage.cpp.
References _getImplementationForRead(), server::chat::PersistentMessageImplementation::getSenderName(), and RPC_GETSENDERNAME__.
Referenced by ChatPersistentMessageToClient::ChatPersistentMessageToClient().
byte PersistentMessage::getStatus ()
Definition at line 118 of file PersistentMessage.cpp.
References _getImplementationForRead(), server::chat::PersistentMessageImplementation::getStatus(), and RPC_GETSTATUS__.
Referenced by ChatPersistentMessageToClient::ChatPersistentMessageToClient().
StringIdChatParameterVector * PersistentMessage::getStringIdParameters ()
Definition at line 46 of file PersistentMessage.cpp.
References _getImplementationForRead(), and server::chat::PersistentMessageImplementation::getStringIdParameters().
Referenced by ChatPersistentMessageToClient::insertParameters().
UnicodeString PersistentMessage::getSubject ()
Definition at line 159 of file PersistentMessage.cpp.
References _getImplementationForRead(), server::chat::PersistentMessageImplementation::getSubject(), and RPC_GETSUBJECT__.
Referenced by ChatPersistentMessageToClient::ChatPersistentMessageToClient().
int PersistentMessage::getTimeStamp ()
Definition at line 131 of file PersistentMessage.cpp.
References _getImplementationForRead(), server::chat::PersistentMessageImplementation::getTimeStamp(), and RPC_GETTIMESTAMP__.
Referenced by ChatPersistentMessageToClient::ChatPersistentMessageToClient().
WaypointChatParameterVector * PersistentMessage::getWaypointParameters ()
Definition at line 55 of file PersistentMessage.cpp.
References _getImplementationForRead(), and server::chat::PersistentMessageImplementation::getWaypointParameters().
Referenced by ChatPersistentMessageToClient::insertParameters().
bool PersistentMessage::isNew ()
Definition at line 258 of file PersistentMessage.cpp.
References _getImplementationForRead(), server::chat::PersistentMessageImplementation::isNew(), and RPC_ISNEW__.
bool PersistentMessage::isRead ()
Definition at line 271 of file PersistentMessage.cpp.
References _getImplementationForRead(), server::chat::PersistentMessageImplementation::isRead(), and RPC_ISREAD__.
bool PersistentMessage::isUnread ()
Definition at line 284 of file PersistentMessage.cpp.
References _getImplementationForRead(), server::chat::PersistentMessageImplementation::isUnread(), and RPC_ISUNREAD__.
void PersistentMessage::sendTo (CreatureObject * player, bool sendBody = true)
Definition at line 31 of file PersistentMessage.cpp.
References _getImplementationForRead(), RPC_SENDTO__CREATUREOBJECT_BOOL_, and server::chat::PersistentMessageImplementation::sendTo().
Referenced by server::chat::ChatManagerImplementation::loadMail().
void PersistentMessage::setBody (const UnicodeString & message)
Definition at line 230 of file PersistentMessage.cpp.
References _getImplementation(), RPC_SETBODY__UNICODESTRING_, and server::chat::PersistentMessageImplementation::setBody().
void PersistentMessage::setReceiverObjectID (unsigned long long oid)
Definition at line 188 of file PersistentMessage.cpp.
References _getImplementation(), RPC_SETRECEIVEROBJECTID__LONG_, and server::chat::PersistentMessageImplementation::setReceiverObjectID().
void PersistentMessage::setSenderName (const String & name)
Definition at line 174 of file PersistentMessage.cpp.
References _getImplementation(), RPC_SETSENDERNAME__STRING_, and server::chat::PersistentMessageImplementation::setSenderName().
void PersistentMessage::setStatus (byte stat)
Definition at line 202 of file PersistentMessage.cpp.
References _getImplementation(), RPC_SETSTATUS__BYTE_, and server::chat::PersistentMessageImplementation::setStatus().
Referenced by server::chat::ChatManagerImplementation::handleRequestPersistentMsg().
void PersistentMessage::setSubject (const UnicodeString & subj)
Definition at line 244 of file PersistentMessage.cpp.
References _getImplementation(), RPC_SETSUBJECT__UNICODESTRING_, and server::chat::PersistentMessageImplementation::setSubject().
void PersistentMessage::setTimeStamp (int stamp)
Definition at line 216 of file PersistentMessage.cpp.
References _getImplementation(), RPC_SETTIMESTAMP__INT_, and server::chat::PersistentMessageImplementation::setTimeStamp().
Friends And Related Function Documentation
friend class PersistentMessageHelper friend
Definition at line 111 of file PersistentMessage.h.
Member Data Documentation
const byte server::chat::PersistentMessage::NEW = 0x4E static
Definition at line 49 of file PersistentMessage.h.
const byte server::chat::PersistentMessage::READ = 0x52 static
Definition at line 51 of file PersistentMessage.h.
const byte server::chat::PersistentMessage::UNREAD = 0x55 static
Definition at line 53 of file PersistentMessage.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/PersistentMessage.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/PersistentMessage.cpp