Core3: server::zone::objects::creature::VehicleObjectImplementation Class Reference
server::zone::objects::creature::VehicleObjectImplementation Class Reference
#include <VehicleObject.h>
Public Member Functions
VehicleObjectImplementation ()
VehicleObjectImplementation (DummyConstructorParameter *param)
void loadTemplateData (SharedObjectTemplate *templateData)
void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
bool checkInRangeGarage ()
void notifyInsertToZone (Zone *zone)
void setPosture (int newPosture, bool notifyClient=true)
void sendMessage (BasePacket *msg)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
int healDamage (TangibleObject *healer, int damageType, int damageToHeal, bool notifyClient=true)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
void setDefender (SceneObject *defender)
bool isAttackableBy (CreatureObject *object)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
void repairVehicle (CreatureObject *player)
int calculateRepairCost (CreatureObject *player)
void sendRepairConfirmTo (CreatureObject *player)
void refreshPaint ()
int getPaintCount ()
bool isVehicleObject ()
operator const VehicleObject * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::CreatureObjectImplementation
CreatureObjectImplementation ()
CreatureObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
void finalize ()
void createChildObjects ()
void initializeTransientMembers ()
void clearQueueAction (unsigned int actioncntr, float timer=0, unsigned int tab1=0, unsigned int tab2=0)
void sendBaselinesTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendTo (SceneObject *player, bool doClose)
void sendSystemMessage (const String &message)
void playMusicMessage (const String &file)
void sendNewbieTutorialRequest (const String &request)
void sendNewbieTutorialEnableHudElement (const String &ui, bool enable=true)
void sendOpenHolocronToPageMessage ()
void sendSystemMessage (UnicodeString &message)
void sendSystemMessage (StringIdChatParameter &stringid)
void sendSlottedObjectsTo (SceneObject *player)
void setCombatState ()
void clearCombatState (bool clearDefenders=true)
float calculateSpeed ()
virtual void updateLocomotion ()
void setHeight (float heigh, bool notifyClient=true)
void setAccelerationMultiplierBase (float newMultiplierBase, bool notifyClient=true)
void setAccelerationMultiplierMod (float newMultiplierMod, bool notifyClient=true)
void setSpeedMultiplierBase (float newMultiplierBase, bool notifyClient=true)
virtual void setSpeedMultiplierMod (float newMultiplierMod, bool notifyClient=true)
virtual void setTurnScale (float newMultiplierMod, bool notifyClient=true)
void setRunSpeed (float newSpeed, bool notifyClient=true)
void setCurrentSpeed (float newSpeed)
void setHAM (int type, int value, bool notifyClient=true)
bool hasDamage (int attribute)
int healDamage (TangibleObject *healer, int damageType, int damage, bool notifyClient=true, bool notifyObservers=true)
int healWound (TangibleObject *healer, int damageType, int damage, bool notifyClient=true, bool notifyObservers=true)
void setBaseHAM (int type, int value, bool notifyClient=true)
void setWounds (int type, int value, bool notifyClient=true)
int addWounds (int type, int value, bool notifyClient=true)
void setMaxHAM (int type, int value, bool notifyClient=true)
void addMaxHAM (int type, int value, bool notifyClient=true)
void setEncumbrance (int type, int value, bool notifyClient=true)
void addEncumbrance (int type, int value, bool notifyClient=true)
void setWeapon (WeaponObject *weao, bool notifyClient=false)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void setInstrumentID (int instrumentid, bool notifyClient=true)
void setListenToID (unsigned long long id, bool notifyClient=true)
void setPerformanceCounter (int counter, bool notifyClient=true)
void setPerformanceAnimation (const String &animation, bool notifyClient=true)
void setShockWounds (int newShock, bool notifyClient=true)
void addShockWounds (int shockToAdd, bool notiyClient=true)
void setTargetID (unsigned long long targetID, bool notifyClient=true)
void setBankCredits (int credits, bool notifyClient=true)
void addBuff (Buff *buff)
bool removeBuff (unsigned int buffcrc)
void removeBuff (Buff *buff)
bool removeStateBuff (unsigned long long state)
void clearBuffs (bool updateclient)
void addWearableObject (TangibleObject *object, bool notifyClient=true)
void removeWearableObject (TangibleObject *object, bool notifyClient=true)
WearablesDeltaVector * getWearablesDeltaVector ()
void sendBuffsTo (CreatureObject *creature)
BuffList * getBuffList ()
Buff * getBuff (unsigned int buffcrc)
long long getSkillModFromBuffs (const String &skillMod)
int addDotState (unsigned long long dotType, unsigned long long objectID, unsigned int strength, byte type, unsigned int duration, float potency, unsigned int defense, int secondaryStrength=0)
bool healDot (unsigned long long dotType, int reduction)
void clearDots ()
DamageOverTimeList * getDamageOverTimeList ()
bool hasBuff (unsigned int buffcrc)
void notifySelfPositionUpdate ()
void notifyPostureChange (int newPosture)
void setLevel (int level)
void updateToDatabaseAllObjects (bool startTask)
bool isResuscitable ()
void addBankCredits (int credits, bool notifyClient=true)
void addCashCredits (int credits, bool notifyClient=true)
void subtractBankCredits (int credits)
void subtractCashCredits (int credits)
bool verifyCashCredits (int credits)
bool verifyBankCredits (int credits)
bool isDancing ()
bool isPlayingMusic ()
void stopEntertaining ()
bool isEntertaining ()
void setCashCredits (int credits, bool notifyClient=true)
void setTerrainNegotiation (float value, bool notifyClient=true)
void addSkill (Skill *skill, bool notifyClient=true)
void addSkill (const String &skill, bool notifyClient=true)
void removeSkill (Skill *skill, bool notifyClient=true)
void removeSkill (const String &skill, bool notifyClient=true)
void addSkillMod (const int modType, const String &skillMod, int value, bool notifyClient=true)
void removeSkillMod (const int modType, const String &skillMod, int value, bool notifyClient=true)
void removeAllSkillModsOfType (const int modType, bool notifyClient=true)
void updateGroupInviterID (unsigned long long id, bool notifyClient=true)
void updateGroup (GroupObject *group, bool notifyClient=true)
void enqueueCommand (unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString &arguments, int priority=-1)
void setMood (byte moodID, bool notifyClient=true)
void setMoodString (const String &animation, bool notifyClient=true)
void deleteQueueAction (unsigned int actionCount)
bool setState (unsigned long long state, bool notifyClient=true)
bool clearState (unsigned long long state, bool notifyClient=true)
void setControlDevice (ControlDevice *device)
void setCreatureLink (CreatureObject *object, bool notifyClient=true)
void executeObjectControllerAction (unsigned int actionCRC)
void executeObjectControllerAction (unsigned int actionCRC, unsigned long long targetID, const UnicodeString &args)
bool isAttackableBy (TangibleObject *attacker)
bool isHealableBy (CreatureObject *object)
bool isInBountyMission (CreatureObject *bountyHunter, CreatureObject *target)
virtual void sendConversationStartTo (SceneObject *player)
virtual void selectConversationOption (int option, SceneObject *obj)
void sendExecuteConsoleCommand (const String &command)
bool isAggressiveTo (CreatureObject *object)
int notifyObjectKillObservers (TangibleObject *killer)
void notifyLoadFromDatabase ()
void setFactionRank (int rank, bool notifyClient=true)
String getFirstName ()
String getLastName ()
bool isOnline ()
bool canTreatInjuries ()
bool canTreatStates ()
bool canTreatWounds ()
bool canTreatConditions ()
Reference< PlayerObject * > getPlayerObject ()
AiActor * getActorObject ()
bool isListening ()
bool isWatching ()
void setClient (ZoneClientSession *cli)
void dismount ()
float calculateBFRatio ()
void setDizziedState (int durationSeconds=5)
void setRalliedState (int durationSeconds=5)
void setAimingState (int durationSeconds=5)
void setCoverState (int durationSeconds=40)
void setBerserkedState (unsigned int duration)
void setStunnedState (int durationSeconds=5)
void setBlindedState (int durationSeconds=5)
void setIntimidatedState (unsigned int mod, int durationSeconds=15)
void setSnaredState (int durationSeconds=20)
void setRootedState (int durationSeconds=20)
bool setNextAttackDelay (unsigned int mod, int del)
void setMeditateState ()
virtual void activateHAMRegeneration ()
virtual void activatePassiveWoundRegeneration ()
virtual void activateStateRecovery ()
void updateTimeOfDeath ()
bool hasAttackDelay ()
void removeAttackDelay ()
CooldownTimerMap * getCooldownTimerMap ()
bool hasSpice ()
void updateLastSuccessfulCombatAction ()
void updateKnockdownRecovery ()
virtual void queueDizzyFallEvent ()
void updateLastKnockdown ()
bool checkKnockdownRecovery ()
bool checkLastKnockdown ()
void updatePostureDownRecovery ()
void updatePostureUpRecovery ()
bool checkPostureDownRecovery ()
unsigned long long getScreenPlayState (const String &screenPlay)
void setScreenPlayState (const String &screenPlay, unsigned long long state)
bool checkPostureUpRecovery ()
void updateCooldownTimer (const String &coooldownTimer, unsigned int miliSecondsToAdd=0)
bool checkCooldownRecovery (const String &cooldown)
Time * getCooldownTime (const String &cooldown)
void addCooldown (const String &name, unsigned int miliseconds)
void doAnimation (const String &animation)
void doCombatAnimation (CreatureObject *defender, unsigned int animationCRC, byte hit, byte trails)
void playEffect (const String &file, const String &aux)
void playEffect (const String &file)
void activateQueueAction ()
void activateImmediateAction ()
UnicodeString getCreatureName ()
bool isGrouped ()
int getBankCredits ()
int getCashCredits ()
int getBaseHAM (int idx)
int getWounds (int idx)
DeltaVector< int > * getWounds ()
int getHAM (int idx)
DeltaVector< int > * getHAM ()
int getMaxHAM (int idx)
DeltaVector< int > * getMaxHAM ()
int getEncumbrance (int idx)
DeltaVector< int > * getEncumbrances ()
byte getPosture ()
byte getLocomotion ()
byte getFactionRank ()
ManagedWeakReference
< CreatureObject * > getLinkedCreature ()
unsigned long long getCreatureLinkID ()
float getShockWounds ()
unsigned long long getWatchToID ()
unsigned long long getStateBitmask ()
bool hasState (unsigned long long state)
bool hasStates ()
unsigned long long getListenID ()
float getAccelerationMultiplierBase ()
float getAccelerationMultiplierMod ()
float getSpeedMultiplierBase ()
float getSpeedMultiplierMod ()
float getCurrentSpeed ()
SpeedMultiplierModChanges * getSpeedMultiplierModChanges ()
CommandQueueActionVector * getCommandQueue ()
float getRunSpeed ()
float getWalkSpeed ()
float getTurnScale ()
float getTerrainNegotiation ()
float getRunAcceleration ()
float getWalkAcceleration ()
String getPerformanceAnimation ()
String getMoodString ()
unsigned long long getWeaponID ()
Reference< WeaponObject * > getWeapon ()
Reference< GuildObject * > getGuildObject ()
int getGuildID ()
bool isInGuild ()
void setGuildObject (GuildObject *guildobj)
unsigned long long getGroupID ()
unsigned long long getGroupInviterID ()
GroupObject * getGroup ()
unsigned long long getGroupInviteCounter ()
unsigned long long getTargetID ()
byte getMoodID ()
float getSlopeModPercent ()
int getPerformanceCounter ()
int getInstrumentID ()
byte getFrozen ()
float getHeight ()
int getSpecies ()
String getSpeciesName ()
int getGender ()
DeltaVector< int > * getBaseHAM ()
SkillList * getSkillList ()
int getSkillMod (const String &skillmod)
bool hasSkill (const String &skill)
SkillModList * getSkillModList ()
void setWatchToID (unsigned long long id)
bool isCreatureObject ()
bool isNextActionPast ()
virtual bool isTrainerCreature ()
bool isSwimming ()
ZoneClientSession * getClient ()
bool isRidingMount ()
ManagedWeakReference
< ControlDevice * > getControlDevice ()
float getSwimHeight ()
bool isIncapacitated ()
bool isDead ()
bool isKnockedDown ()
bool isKneeling ()
bool isProne ()
bool isStanding ()
bool isSitting ()
bool isSkillAnimating ()
bool isRallied ()
bool isInCombat ()
bool isDizzied ()
bool isBerserked ()
bool isStunned ()
bool isBlinded ()
bool isIntimidated ()
bool isSnared ()
bool isImmobilized ()
bool isRooted ()
bool isFrozen ()
bool isDiseased ()
bool isPoisoned ()
bool isBleeding ()
bool isOnFire ()
bool isMounted ()
bool isRidingCreature ()
bool isPeaced ()
bool isMeditating ()
bool isAiming ()
bool isInCover ()
bool isRunning ()
virtual bool isNonPlayerCreatureObject ()
virtual bool isCreature ()
bool isPlayerCreature ()
bool isAiActor ()
virtual bool isInformantCreature ()
CampSiteActiveArea * getCurrentCamp ()
byte getCurrentWeather ()
void setCurrentWeather (byte value)
byte getCurrentWind ()
void setCurrentWind (byte value)
void destroyObjectFromWorld (bool sendSelfDestroy)
bool isInvisible ()
void setInvisible (bool invis)
Mutex * getSkillModMutex ()
float calculateCostAdjustment (byte stat, float baseCost)
void updateSpeedAndAccelerationMods ()
operator const CreatureObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
TangibleObjectImplementation ()
TangibleObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
virtual void addTemplateSkillMods (TangibleObject *targetObject)
virtual void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
virtual void removeSkillModsFrom (CreatureObject *creature)
virtual void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
virtual void removeDefenders ()
virtual void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
bool hasDefender (SceneObject *defender)
virtual void sendPvpStatusTo (CreatureObject *player)
virtual int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
virtual void updateCraftingValues (CraftingValues *values, bool firstUpdate)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
virtual bool isKiller ()
virtual bool isTicketCollector ()
virtual bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
virtual int getUseCount ()
virtual int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
virtual bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
virtual String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
virtual int getJunkDealerNeeded ()
void setJunkValue (int jValue)
virtual int getJunkValue ()
void setSerialNumber (const String &serial)
virtual String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
virtual String repairAttempt (int repairChance)
bool isBroken ()
virtual float getHitChance ()
void broadcastPvpStatusBitmask ()
operator const TangibleObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< VehicleObject * > _this
Public Attributes inherited from server::zone::objects::creature::CreatureObjectImplementation
WeakReference< CreatureObject * > _this
Public Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
WeakReference< TangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Static Public Attributes
static const int PAINTCHARGES = 20
Static Public Attributes inherited from server::zone::objects::creature::CreatureObjectImplementation
static const int HUMAN = 0
static const int RODIAN = 1
static const int TRANDOSHAN = 2
static const int MONCAL = 3
static const int WOOKIE = 4
static const int BOTHAN = 5
static const int TWILEK = 6
static const int ZABRAK = 7
static const int ITHORIAN = 0x21
static const int SULLUSTAN = 0x31
static const int MALE = 0
static const int FEMALE = 1
static float DEFAULTRUNSPEED = 5.376
static unsigned const long long DEAD_TOO_LONG = 1800000
Protected Member Functions
virtual ~VehicleObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::CreatureObjectImplementation
virtual ~CreatureObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
float getConditionReduction (float value)
virtual ~TangibleObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
int vehicleType
int paintCount
Protected Attributes inherited from server::zone::objects::creature::CreatureObjectImplementation
ManagedReference
< ZoneClientSession * > owner
int bankCredits
int cashCredits
int gender
int species
DeltaVector< int > baseHAM
byte posture
byte locomotion
byte factionRank
bool invisible
ManagedWeakReference
< CreatureObject * > linkedCreature
ManagedWeakReference
< ControlDevice * > controlDevice
float shockWounds
DeltaVector< int > wounds
unsigned long long stateBitmask
DeltaVector< int > encumbrances
WearablesDeltaVector wearablesVector
float accelerationMultiplierBase
float accelerationMultiplierMod
float speedMultiplierBase
SpeedMultiplierModChanges speedMultiplierModChanges
float speedMultiplierMod
float turnScale
float runSpeed
float walkSpeed
float currentSpeed
float terrainNegotiation
float runAcceleration
float walkAcceleration
float height
float swimHeight
float slopeModPercent
float slopeModAngle
unsigned long long listenToID
unsigned long long watchToID
String performanceAnimation
String moodString
ManagedReference< WeaponObject * > weapon
ManagedReference< GroupObject * > group
unsigned long long groupInviterID
unsigned long long groupInviteCounter
ManagedReference< GuildObject * > guild
unsigned long long targetID
byte moodID
int performanceCounter
int instrumentID
DeltaVector< int > hamList
DeltaVector< int > maxHamList
byte frozen
String templateString
SkillList skillList
SkillModList skillModList
Mutex skillModMutex
Reference
< CommandQueueActionVector * > commandQueue
Reference
< CommandQueueActionVector * > immediateQueue
Time nextAction
Reference< CooldownTimerMap * > cooldownTimerMap
BuffList creatureBuffs
DamageOverTimeList damageOverTimeList
Time lastSuccessfulCombatAction
Time timeOfDeath
VectorMap< String, unsigned
long long > screenPlayStates
byte healthWoundHeal
byte actionWoundHeal
byte mindWoundHeal
byte currentWeather
byte currentWind
Time lastCombatActionTime
Vector3 lastCombatPosition
Protected Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
bool targetable
float complexity
int volume
unsigned int faction
CustomizationVariables customizationVariables
float conditionDamage
int maxCondition
int useCount
short level
unsigned int optionsBitmask
unsigned int pvpStatusBitmask
byte unknownByte
String craftersName
int junkDealerNeeded
int junkValue
String objectSerial
Reference< ThreatMap * > threatMap
DeltaVector< ManagedReference
< SceneObject * > > defenderList
bool sliceable
bool sliced
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Friends
class VehicleObject
Detailed Description
Definition at line 278 of file VehicleObject.h.
Constructor & Destructor Documentation
VehicleObjectImplementation::VehicleObjectImplementation ()
Definition at line 503 of file VehicleObject.cpp.
References _initializeImplementation(), SceneObjectType::HOVERVEHICLE, paintCount, and vehicleType.
VehicleObjectImplementation::VehicleObjectImplementation (DummyConstructorParameter * param)
Definition at line 365 of file VehicleObject.cpp.
References _initializeImplementation().
VehicleObjectImplementation::~VehicleObjectImplementation () protected virtual
Definition at line 370 of file VehicleObject.cpp.
Member Function Documentation
DistributedObjectStub * VehicleObjectImplementation::_getStub ()
Definition at line 390 of file VehicleObject.cpp.
References _this.
void VehicleObjectImplementation::_initializeImplementation () protected
Definition at line 377 of file VehicleObject.cpp.
References _serializationHelperMethod(), and _this.
Referenced by VehicleObjectImplementation().
void VehicleObjectImplementation::_serializationHelperMethod () protected
Definition at line 426 of file VehicleObject.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void VehicleObjectImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 385 of file VehicleObject.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::VehicleObject::VehicleObject().
void VehicleObjectImplementation::addDefender (SceneObject * defender) virtual
Adds a SceneObject to the defender vector
Precondition
{ this object is locked }
Postcondition
{ this object is locked, defender is in the defender vector }
Parameters
defender SceneObject to add to the defender vector
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 531 of file VehicleObject.cpp.
Referenced by server::zone::objects::creature::VehicleObject::addDefender().
int VehicleObjectImplementation::calculateRepairCost (CreatureObject * player)
Definition at line 185 of file VehicleObjectImplementation.cpp.
References server::zone::objects::tangible::TangibleObjectImplementation::getConditionDamage(), and server::zone::objects::creature::CreatureObject::getPlayerObject().
Referenced by server::zone::objects::creature::VehicleObject::calculateRepairCost(), and sendRepairConfirmTo().
bool VehicleObjectImplementation::checkInRangeGarage ()
Definition at line 86 of file VehicleObjectImplementation.cpp.
References _this.
Referenced by server::zone::objects::creature::VehicleObject::checkInRangeGarage(), fillObjectMenuResponse(), and repairVehicle().
void VehicleObjectImplementation::fillAttributeList (AttributeListMessage * msg, CreatureObject * object) virtual
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 36 of file VehicleObjectImplementation.cpp.
References server::zone::packets::scene::AttributeListMessage::insertAttribute(), and server::zone::objects::creature::CreatureObjectImplementation::linkedCreature.
Referenced by server::zone::objects::creature::VehicleObject::fillAttributeList().
void VehicleObjectImplementation::fillObjectMenuResponse (ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 25 of file VehicleObjectImplementation.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), checkInRangeGarage(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::tangible::TangibleObjectImplementation::isDestroyed(), and server::zone::objects::creature::CreatureObjectImplementation::linkedCreature.
Referenced by server::zone::objects::creature::VehicleObject::fillObjectMenuResponse().
void VehicleObjectImplementation::finalize () protected
Definition at line 374 of file VehicleObject.cpp.
int VehicleObjectImplementation::getPaintCount ()
Definition at line 558 of file VehicleObject.cpp.
References paintCount.
Referenced by server::zone::objects::creature::VehicleObject::getPaintCount().
int VehicleObjectImplementation::handleObjectMenuSelect (CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player CreatureObject that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 96 of file VehicleObjectImplementation.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::controlDevice, server::zone::objects::creature::CreatureObjectImplementation::linkedCreature, repairVehicle(), unlock(), and wlock().
Referenced by server::zone::objects::creature::VehicleObject::handleObjectMenuSelect().
int VehicleObjectImplementation::healDamage (TangibleObject * healer, int damageType, int damageToHeal, bool notifyClient = true)
Heals damage
Precondition
{ this, healer locked }
Postcondition
{ this, healer locked }
Definition at line 200 of file VehicleObjectImplementation.cpp.
Referenced by server::zone::objects::creature::VehicleObject::healDamage().
int VehicleObjectImplementation::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, bool notifyClient = true) virtual
Inflicts damage into the object
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
unused for now
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 192 of file VehicleObjectImplementation.cpp.
Referenced by server::zone::objects::creature::VehicleObject::inflictDamage().
int VehicleObjectImplementation::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, const String & xp, bool notifyClient = true) virtual
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 196 of file VehicleObjectImplementation.cpp.
bool VehicleObjectImplementation::isAttackableBy (CreatureObject * object) virtual
Evaluates if this object can be attacket by the passed creature object
Precondition
{ this object is locked }
Postcondition
{ this object is locked}
Returns
returns true if the creature object can attack this
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 540 of file VehicleObject.cpp.
References server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObjectImplementation::getZone(), server::zone::objects::tangible::TangibleObjectImplementation::isDestroyed(), and server::zone::objects::creature::CreatureObjectImplementation::linkedCreature.
Referenced by server::zone::objects::creature::VehicleObject::isAttackableBy().
bool VehicleObjectImplementation::isVehicleObject () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 563 of file VehicleObject.cpp.
Referenced by server::zone::objects::creature::VehicleObject::isVehicleObject().
void VehicleObjectImplementation::loadTemplateData (SharedObjectTemplate * templateData) virtual
Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
Precondition
{ templateData is a valid pointer }
Postcondition
{ TangibleObject members are initialized }
Parameters
templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 517 of file VehicleObject.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::loadTemplateData(), server::zone::objects::tangible::TangibleObjectImplementation::optionsBitmask, and server::zone::objects::tangible::TangibleObjectImplementation::pvpStatusBitmask.
Referenced by server::zone::objects::creature::VehicleObject::loadTemplateData().
void VehicleObjectImplementation::lock (bool doLock = true) protected
Definition at line 398 of file VehicleObject.cpp.
References _this.
void VehicleObjectImplementation::lock (ManagedObject * obj) protected
Definition at line 402 of file VehicleObject.cpp.
References _this.
void VehicleObjectImplementation::notifyInsertToZone (Zone * zone) virtual
Inserts this object into zone
Precondition
{ this object is locked }
Postcondition
{ this object is locked and inserted into zone }
Parameters
zone Zone object where this object will be inserted
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 46 of file VehicleObjectImplementation.cpp.
References server::zone::templates::SharedObjectTemplate::getAppearanceFilename(), server::zone::objects::scene::SceneObjectImplementation::getObjectTemplate(), server::zone::objects::creature::CreatureObjectImplementation::linkedCreature, paintCount, and server::zone::objects::tangible::TangibleObjectImplementation::setCustomizationVariable().
Referenced by server::zone::objects::creature::VehicleObject::notifyInsertToZone().
int VehicleObjectImplementation::notifyObjectDestructionObservers (TangibleObject * attacker, int condition) virtual
Is called when this object is destroyed
Precondition
{ this, attacker locked }
Postcondition
{ this, attacker locked }
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 204 of file VehicleObjectImplementation.cpp.
References _this, server::zone::objects::creature::CreatureObjectImplementation::linkedCreature, server::zone::objects::creature::CreatureObjectImplementation::notifyObjectDestructionObservers(), unlock(), and wlock().
Referenced by server::zone::objects::creature::VehicleObject::notifyObjectDestructionObservers().
VehicleObjectImplementation::operator const VehicleObject * ()
Definition at line 394 of file VehicleObject.cpp.
void VehicleObjectImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 433 of file VehicleObject.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::initializeTransientMembers(), and readObjectMember().
bool VehicleObjectImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 452 of file VehicleObject.cpp.
References paintCount, server::zone::objects::creature::CreatureObjectImplementation::readObjectMember(), and vehicleType.
Referenced by readObject().
void VehicleObjectImplementation::refreshPaint ()
Definition at line 553 of file VehicleObject.cpp.
References PAINTCHARGES, and paintCount.
Referenced by server::zone::objects::creature::VehicleObject::refreshPaint().
void VehicleObjectImplementation::removeDefender (SceneObject * defender) virtual
Removes the specified defender from the defender vector
Precondition
{ this object is locked }
Postcondition
{ this object is locked, defender is not in the defender vector }
Parameters
defender SceneObject to remove from the defender vector
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 534 of file VehicleObject.cpp.
Referenced by server::zone::objects::creature::VehicleObject::removeDefender().
void VehicleObjectImplementation::repairVehicle (CreatureObject * player)
Attempts to see if the vehicle can be repaired. If tests are passed, then it sends the confirmation box to the player.
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player The player that is repairing the vehicle.
Definition at line 121 of file VehicleObjectImplementation.cpp.
References checkInRangeGarage(), server::zone::objects::scene::SceneObjectImplementation::getActiveRegion(), server::zone::objects::region::Region::getCityRegion(), server::zone::objects::tangible::TangibleObjectImplementation::getConditionDamage(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::tangible::TangibleObjectImplementation::isDestroyed(), sendRepairConfirmTo(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by handleObjectMenuSelect(), and server::zone::objects::creature::VehicleObject::repairVehicle().
void VehicleObjectImplementation::rlock (bool doLock = true) protected
Definition at line 406 of file VehicleObject.cpp.
References _this.
void VehicleObjectImplementation::runlock (bool doLock = true) protected
Definition at line 422 of file VehicleObject.cpp.
References _this.
void VehicleObjectImplementation::sendMessage (BasePacket * msg) virtual
Sends BasePacket msg to the owner of this object, needs to be overriden
Precondition
{ }
Postcondition
{owner of this object received message, message is deleted }
Parameters
msg BasePacket to be sent
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 236 of file VehicleObjectImplementation.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::linkedCreature.
Referenced by server::zone::objects::creature::VehicleObject::sendMessage().
void VehicleObjectImplementation::sendRepairConfirmTo (CreatureObject * player)
Definition at line 160 of file VehicleObjectImplementation.cpp.
References _this, calculateRepairCost(), SuiWindowType::GARAGE_REPAIR, server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::scene::SceneObjectImplementation::getCityRegion(), server::zone::objects::scene::SceneObjectImplementation::getDisplayedName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::sendMessage(), and server::zone::objects::scene::SceneObjectImplementation::server.
Referenced by repairVehicle(), and server::zone::objects::creature::VehicleObject::sendRepairConfirmTo().
void VehicleObjectImplementation::setDefender (SceneObject * defender) virtual
Sets the active defender
Precondition
{ this object is locked }
Postcondition
{ this object is locked, defender is active }
Parameters
defender SceneObject to set as the active defender
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 537 of file VehicleObject.cpp.
Referenced by server::zone::objects::creature::VehicleObject::setDefender().
void VehicleObjectImplementation::setPosture (int newPosture, bool notifyClient = true) virtual
Sets a new posture
Precondition
{ this object is locked }
Postcondition
{this object is locked, this object has the new posture set }
Parameters
newPosture posture to set
notifyClient if set true the client will be updated with the changes
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 526 of file VehicleObject.cpp.
Referenced by server::zone::objects::creature::VehicleObject::setPosture().
void VehicleObjectImplementation::unlock (bool doLock = true) protected
Definition at line 418 of file VehicleObject.cpp.
References _this.
Referenced by handleObjectMenuSelect(), and notifyObjectDestructionObservers().
void VehicleObjectImplementation::wlock (bool doLock = true) protected
Definition at line 410 of file VehicleObject.cpp.
References _this.
Referenced by handleObjectMenuSelect(), and notifyObjectDestructionObservers().
void VehicleObjectImplementation::wlock (ManagedObject * obj) protected
Definition at line 414 of file VehicleObject.cpp.
References _this.
void VehicleObjectImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 470 of file VehicleObject.cpp.
References writeObjectMembers().
int VehicleObjectImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 477 of file VehicleObject.cpp.
References paintCount, vehicleType, and server::zone::objects::creature::CreatureObjectImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class VehicleObject friend
Definition at line 449 of file VehicleObject.h.
Member Data Documentation
WeakReference<VehicleObject*> server::zone::objects::creature::VehicleObjectImplementation::_this
Definition at line 415 of file VehicleObject.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), checkInRangeGarage(), lock(), notifyObjectDestructionObservers(), rlock(), runlock(), sendRepairConfirmTo(), unlock(), and wlock().
const int server::zone::objects::creature::VehicleObjectImplementation::PAINTCHARGES = 20 static
Definition at line 285 of file VehicleObject.h.
Referenced by refreshPaint().
int server::zone::objects::creature::VehicleObjectImplementation::paintCount protected
Definition at line 282 of file VehicleObject.h.
Referenced by getPaintCount(), notifyInsertToZone(), readObjectMember(), refreshPaint(), VehicleObjectImplementation(), and writeObjectMembers().
int server::zone::objects::creature::VehicleObjectImplementation::vehicleType protected
Definition at line 280 of file VehicleObject.h.
Referenced by readObjectMember(), VehicleObjectImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/VehicleObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/VehicleObject.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/VehicleObjectImplementation.cpp