Core3: StartingLocationList Class Reference
StartingLocationList Class Reference
#include <StartingLocationList.h>
Public Member Functions
StartingLocationList ()
int getTotalLocations ()
void parseFromIffStream (IffStream *iffStream)
void insertToMessage (Message *msg)
Detailed Description
Definition at line 16 of file StartingLocationList.h.
Constructor & Destructor Documentation
StartingLocationList::StartingLocationList () inline
Definition at line 19 of file StartingLocationList.h.
Member Function Documentation
int StartingLocationList::getTotalLocations () inline
Definition at line 22 of file StartingLocationList.h.
Referenced by server::zone::managers::player::PlayerManagerImplementation::loadStartingLocations().
void StartingLocationList::insertToMessage (Message * msg) inline
Definition at line 43 of file StartingLocationList.h.
Referenced by server::zone::managers::player::PlayerManagerImplementation::sendStartingLocationsTo().
void StartingLocationList::parseFromIffStream (IffStream * iffStream) inline
Definition at line 26 of file StartingLocationList.h.
References DataTableIff::getRow(), DataTableIff::getTotalRows(), StartingLocation::parseFromDataTableRow(), and DataTableIff::readObject().
Referenced by server::zone::managers::player::PlayerManagerImplementation::loadStartingLocations().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/StartingLocationList.h