Core3: FixedPool Class Reference
FixedPool Class Reference
#include <FixedPool.h>
Public Member Functions
FixedPool (ResourceSpawner *spawner)
~FixedPool ()
void initialize (LuaObject includes, const String &excludes)
String healthCheck ()
void print ()
Public Member Functions inherited from ResourcePool
ResourcePool (ResourceSpawner *spawner)
virtual ~ResourcePool ()
void initialize (const String &includes, const String &excludes)
void initializeByTable (LuaObject includes, const String &excludes)
void print ()
Private Member Functions
void addResource (ManagedReference< ResourceSpawn * > resourceSpawn, const String &poolSlot)
bool update ()
Friends
class ResourceSpawner
Additional Inherited Members
Static Public Attributes inherited from ResourcePool
static const short NOPOOL = 0
static const short MINIMUMPOOL = 1
static const short RANDOMPOOL = 2
static const short FIXEDPOOL = 3
static const short NATIVEPOOL = 4
static const short MANUALPOOL = 5
Protected Attributes inherited from ResourcePool
VectorMap< String,
ManagedReference
< ResourceSpawn * > > includedResources
Vector< String > excludedResources
ResourceSpawner * resourceSpawner
Detailed Description
The FixedPool class represents the resource pool containing the "Fixed" resources consisting of Iron and the JTL resources. It spawns random resources based on the scripted entries.
Definition at line 65 of file FixedPool.h.
Constructor & Destructor Documentation
FixedPool::FixedPool (ResourceSpawner * spawner)
Ctor
Parameters
spawner The pointer to the resource spawner object
Definition at line 54 of file FixedPool.cpp.
FixedPool::~FixedPool ()
Dtor
Definition at line 58 of file FixedPool.cpp.
Member Function Documentation
void FixedPool::addResource (ManagedReference< ResourceSpawn * > resourceSpawn, const String & poolSlot) private virtual
Adds resource to this pool
Parameters
resourceSpawn Spawn object to add to the pool
Implements ResourcePool.
Definition at line 67 of file FixedPool.cpp.
References ResourcePool::includedResources, and ResourcePool::NOPOOL.
Referenced by ResourceSpawner::loadResourceSpawns().
String FixedPool::healthCheck () virtual
Implements ResourcePool.
Definition at line 140 of file FixedPool.cpp.
References ResourcePool::includedResources.
Referenced by ResourceSpawner::healthCheck().
void FixedPool::initialize (LuaObject includes, const String & excludes)
Initialized what the pool spawns, and what is excluded
Parameters
includes Comma delimited list of resources to include
excludes Comma delimited list of resources to exclude
Definition at line 62 of file FixedPool.cpp.
References ResourcePool::includedResources, and ResourcePool::initializeByTable().
Referenced by ResourceSpawner::initializeFixedPool().
void FixedPool::print ()
Print the current state of the Resource Pool
Definition at line 173 of file FixedPool.cpp.
References ResourcePool::print().
bool FixedPool::update () private virtual
The update function checks the ResourceSpawn items in spawnedResources to see if they have expired. If they have not expired, no action is taken, but if they have expired, we replace them according to the rules.
Returns
if update was successful
We remove any resources that have despawned from the pool.
Implements ResourcePool.
Definition at line 95 of file FixedPool.cpp.
References ResourceSpawner::createResourceSpawn(), ResourceSpawner::despawn(), ResourcePool::excludedResources, ResourcePool::FIXEDPOOL, ResourcePool::includedResources, ResourcePool::resourceSpawner, and server::zone::objects::resource::ResourceSpawn::setSpawnPool().
Referenced by ResourceSpawner::shiftResources().
Friends And Related Function Documentation
friend class ResourceSpawner friend
Definition at line 112 of file FixedPool.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcepool/FixedPool.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcepool/FixedPool.cpp