Core3: PlayerList< DeltaUpdate > Class Template Reference
PlayerList< DeltaUpdate > Class Template Reference
#include <PlayerList.h>
Public Member Functions
PlayerList ()
PlayerList (const PlayerList &list)
bool addPlayer (const String &player)
bool removePlayer (const String &player)
void insertToDeltaMessage (DeltaMessage *delta)
void insertToListMessage (Message *message)
bool canAddMorePlayers ()
Public Member Functions inherited from server::zone::objects::scene::variables::DeltaVector< String >
DeltaVector ()
DeltaVector (int initsize, int incr)
DeltaVector (const DeltaVector &v)
~DeltaVector ()
DeltaVector & operator= (const DeltaVector &v)
void addSerializableVariables ()
virtual String set (int idx, const String &newValue, DeltaMessage *message=NULL, int updates=1)
virtual bool add (const String &element, DeltaMessage *message=NULL, int updates=1)
String & get (int index) const
String & getSafe (int index)
String remove (int index, DeltaMessage *message=NULL, int updates=1)
void removeAll (DeltaMessage *message=NULL)
virtual void insertToMessage (BaseMessage *msg)
virtual void insertItemToMessage (String *item, BaseMessage *msg)
virtual bool contains (const String &element)
int find (const String &element)
uint32 getUpdateCounter ()
uint32 getNewUpdateCounter (int increment)
void setUpdateCounter (int count)
void resetUpdateCounter ()
int size ()
ReadWriteLock * getLock ()
Static Public Attributes
static const int MAXSIZE = 100
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::scene::variables::DeltaVector< String >
Vector< String > vector
uint32 updateCounter
ReadWriteLock * mutex
Detailed Description
template<int DeltaUpdate>
class PlayerList< DeltaUpdate >
Definition at line 14 of file PlayerList.h.
Constructor & Destructor Documentation
template<int DeltaUpdate> PlayerList< DeltaUpdate >::PlayerList () inline
Definition at line 21 of file PlayerList.h.
template<int DeltaUpdate> PlayerList< DeltaUpdate >::PlayerList (const PlayerList< DeltaUpdate > & list) inline
Definition at line 25 of file PlayerList.h.
Member Function Documentation
template<int DeltaUpdate> bool PlayerList< DeltaUpdate >::addPlayer (const String & player) inline
Definition at line 29 of file PlayerList.h.
template<int DeltaUpdate> bool PlayerList< DeltaUpdate >::canAddMorePlayers () inline
Definition at line 80 of file PlayerList.h.
template<int DeltaUpdate> void PlayerList< DeltaUpdate >::insertToDeltaMessage (DeltaMessage * delta) inline
Definition at line 57 of file PlayerList.h.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addFriend(), server::zone::objects::player::PlayerObjectImplementation::addIgnore(), server::zone::objects::player::PlayerObjectImplementation::removeFriend(), server::zone::objects::player::PlayerObjectImplementation::removeIgnore(), and server::zone::objects::player::PlayerObjectImplementation::sendFriendLists().
template<int DeltaUpdate> void PlayerList< DeltaUpdate >::insertToListMessage (Message * message) inline
Definition at line 70 of file PlayerList.h.
template<int DeltaUpdate> bool PlayerList< DeltaUpdate >::removePlayer (const String & player) inline
Definition at line 42 of file PlayerList.h.
Referenced by server::zone::objects::player::PlayerObjectImplementation::removeFriend(), and server::zone::objects::player::PlayerObjectImplementation::removeIgnore().
Member Data Documentation
template<int DeltaUpdate> const int PlayerList< DeltaUpdate >::MAXSIZE = 100 static
Definition at line 17 of file PlayerList.h.
Referenced by PlayerList< 8 >::canAddMorePlayers().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/variables/PlayerList.h