Core3: DataTableCell Class Reference
DataTableCell Class Reference abstract
#include <DataTableCell.h>
Public Member Functions
DataTableCell ()
virtual ~DataTableCell ()
virtual void parse (Chunk *chunk)=0
virtual void getValue (Vector< String > &out)
virtual void getValue (SortedVector< String > &out)
virtual void getValue (String &out)
virtual void getValue (int &out)
virtual void getValue (uint32 &out)
virtual void getValue (float &out)
virtual void getValue (bool &out)
virtual byte getType ()=0
virtual String toString ()=0
Detailed Description
Definition at line 13 of file DataTableCell.h.
Constructor & Destructor Documentation
DataTableCell::DataTableCell () inline
Definition at line 15 of file DataTableCell.h.
virtual DataTableCell::~DataTableCell () inline virtual
Definition at line 18 of file DataTableCell.h.
Member Function Documentation
virtual byte DataTableCell::getType () pure virtual
Implemented in DataTableCellBinary, DataTableCellFloat, DataTableCellHex, DataTableCellInt, and DataTableCellString.
Referenced by getValue().
virtual void DataTableCell::getValue (Vector< String > & out) inline virtual
Reimplemented in DataTableCellString.
Definition at line 29 of file DataTableCell.h.
References getType().
Referenced by ResourceTree::buildTreeFromClient(), server::zone::managers::player::PlayerManagerImplementation::loadBadgeMap(), SchematicMap::loadSchematicGroups(), and server::zone::managers::planet::PlanetManagerImplementation::loadTravelFares().
virtual void DataTableCell::getValue (SortedVector< String > & out) inline virtual
Reimplemented in DataTableCellString.
Definition at line 33 of file DataTableCell.h.
References getType().
virtual void DataTableCell::getValue (String & out) inline virtual
Reimplemented in DataTableCellString.
Definition at line 37 of file DataTableCell.h.
References getType().
virtual void DataTableCell::getValue (int & out) inline virtual
Reimplemented in DataTableCellInt.
Definition at line 41 of file DataTableCell.h.
References getType().
virtual void DataTableCell::getValue (uint32 & out) inline virtual
Reimplemented in DataTableCellHex.
Definition at line 45 of file DataTableCell.h.
References getType().
virtual void DataTableCell::getValue (float & out) inline virtual
Reimplemented in DataTableCellFloat.
Definition at line 49 of file DataTableCell.h.
References getType().
virtual void DataTableCell::getValue (bool & out) inline virtual
Reimplemented in DataTableCellBinary.
Definition at line 53 of file DataTableCell.h.
References getType().
virtual void DataTableCell::parse (Chunk * chunk) pure virtual
Implemented in DataTableCellBinary, DataTableCellFloat, DataTableCellHex, DataTableCellInt, and DataTableCellString.
Referenced by DataTableIff::readObject().
virtual String DataTableCell::toString () pure virtual
Implemented in DataTableCellBinary, DataTableCellFloat, DataTableCellHex, DataTableCellInt, and DataTableCellString.
Referenced by DataTableIff::getRowsByColumn(), and ImageDesignManager::loadCustomizationData().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/datatables/DataTableCell.h