Core3: ResourceContainerObjectDeltaMessage3 Class Reference
ResourceContainerObjectDeltaMessage3 Class Reference
#include <ResourceContainerObjectDeltaMessage3.h>
Public Member Functions
ResourceContainerObjectDeltaMessage3 (ResourceContainer *rcno)
void updateQuantity ()
Public Member Functions inherited from DeltaMessage
DeltaMessage (uint64 oid, uint32 name, uint8 type)
uint32 generateRandomObjectCRC ()
void startUpdate (uint16 type)
void addByteUpdate (uint16 type, uint8 value)
void addShortUpdate (uint16 type, uint16 value)
void addIntUpdate (uint16 type, uint32 value)
void addLongUpdate (uint16 type, uint64 value)
void addFloatUpdate (uint16 type, float value)
void addAsciiUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const UnicodeString &val)
void startList (uint32 cnt, uint32 updcnt)
void addListIntElement (uint16 index, uint32 value)
void addListFloatElement (uint16 index, float value)
void addListLongElement (uint16 index, uint64 value)
void addListAsciiElement (const String &value)
void removeListIntElement (uint16 index, uint32 value)
void removeListFloatElement (uint16 index, float value)
void removeListLongElement (uint16 index, uint64 value)
void removeListLongElement (uint16 index)
void removeListAsciiElement (const String &value)
void close ()
Private Attributes
ManagedReference
< ResourceContainer * > container
Detailed Description
Definition at line 51 of file ResourceContainerObjectDeltaMessage3.h.
Constructor & Destructor Documentation
ResourceContainerObjectDeltaMessage3::ResourceContainerObjectDeltaMessage3 (ResourceContainer * rcno) inline
Definition at line 56 of file ResourceContainerObjectDeltaMessage3.h.
References container.
Member Function Documentation
void ResourceContainerObjectDeltaMessage3::updateQuantity () inline
Definition at line 75 of file ResourceContainerObjectDeltaMessage3.h.
References DeltaMessage::addIntUpdate(), and container.
Referenced by server::zone::managers::resource::ResourceManagerImplementation::removePowerFromPlayer(), and server::zone::objects::resource::ResourceContainerImplementation::setQuantity().
Member Data Documentation
ManagedReference<ResourceContainer*> ResourceContainerObjectDeltaMessage3::container private
Definition at line 53 of file ResourceContainerObjectDeltaMessage3.h.
Referenced by ResourceContainerObjectDeltaMessage3(), and updateQuantity().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/resource/ResourceContainerObjectDeltaMessage3.h