Core3: CurePackCommand Class Reference
CurePackCommand Class Reference
#include <CurePackCommand.h>
Public Member Functions
CurePackCommand (const String &name, ZoneProcessServer *server)
void doAnimations (CreatureObject *creature, CreatureObject *creatureTarget)
void parseModifier (const String &modifier, uint64 &objectId)
CurePack * findCurePack (CreatureObject *creature)
void sendCureMessage (CreatureObject *object, CreatureObject *target)
void deactivateConditionTreatment (CreatureObject *creature)
void awardXp (CreatureObject *creature, const String &type, int power)
bool checkTarget (CreatureObject *creature, CreatureObject *creatureTarget)
void handleArea (CreatureObject *creature, CreatureObject *areaCenter, CurePack *pharma, float range)
void doAreaMedicActionTarget (CreatureObject *creature, CreatureObject *creatureTarget, PharmaceuticalObject *pharma)
bool canPerformSkill (CreatureObject *creature, CreatureObject *creatureTarget, CurePack *curePack)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Public Member Functions inherited from server::zone::objects::creature::commands::QueueCommand
QueueCommand (const String &skillname, ZoneProcessServer *serv)
virtual ~QueueCommand ()
bool checkInvalidLocomotions (CreatureObject *creature)
void onStateFail (CreatureObject *creature, uint32 actioncntr)
void onLocomotionFail (CreatureObject *creature, uint32 actioncntr)
virtual String getSyntax () const
virtual void onFail (uint32 actioncntr, CreatureObject *creature, uint32 errorNumber)
virtual void onComplete (uint32 actioncntr, CreatureObject *creature, float commandDuration)
void setInvalidLocomotions (const String &lStr)
void addInvalidLocomotion (int l)
bool checkStateMask (CreatureObject *creature)
virtual float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
void setStateMask (uint64 mask)
void setDefaultTime (float time)
void setTargetType (int num)
void setDisabled (bool state)
void setDisabled (int state)
void setAddToCombatQueue (bool state)
void setAddToCombatQueue (int state)
void setCommandGroup (int val)
void setMaxRange (float r)
void setCharacterAbility (const String &ability)
void setDefaultPriority (const String &priority)
void setDefaultPriority (const int priority)
uint64 getStateMask ()
bool requiresAdmin ()
int getTargetType ()
uint32 getNameCRC ()
float getMaxRange ()
String & getQueueCommandName ()
String & getCharacterAbility ()
float getDefaultTime ()
int getDefaultPriority ()
bool isDisabled ()
bool addToCombatQueue ()
virtual bool isCombatCommand ()
int getSkillModSize ()
int getSkillMod (int index, String &skillMod)
int getCommandGroup ()
void addSkillMod (const String &skillMod, const int value)
bool isWearingArmor (CreatureObject *creo)
virtual void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Protected Attributes
int mindCost
float range
uint64 state
Protected Attributes inherited from server::zone::objects::creature::commands::QueueCommand
ZoneProcessServer * server
String name
uint32 nameCRC
uint64 stateMask
Vector< int > invalidLocomotion
int targetType
int maxRangeToTarget
bool disabled
bool addToQueue
bool admin
uint32 cooldown
float defaultTime
String characterAbility
int defaultPriority
VectorMap< String, int > skillMods
int commandGroup
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::creature::commands::QueueCommand
static const int IMMEDIATE = 0
static const int FRONT = 1
static const int NORMAL = 2
static const int SUCCESS = 0
static const int GENERALERROR = 1
static const int INVALIDLOCOMOTION = 2
static const int INVALIDSTATE = 3
static const int INVALIDTARGET = 4
static const int INVALIDWEAPON = 5
static const int TOOFAR = 6
static const int INSUFFICIENTHAM = 7
static const int INVALIDPARAMETERS = 8
static const int NOPRONE = 9
static const int NOKNEELING = 10
static const int INSUFFICIENTPERMISSION = 11
static const int NOJEDIARMOR = 12
static const int INVALIDSYNTAX = 13
Detailed Description
Definition at line 22 of file CurePackCommand.h.
Constructor & Destructor Documentation
CurePackCommand::CurePackCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 28 of file CurePackCommand.h.
References mindCost, and range.
Member Function Documentation
void CurePackCommand::awardXp (CreatureObject * creature, const String & type, int power) inline
Definition at line 141 of file CurePackCommand.h.
References server::zone::managers::player::PlayerManager::awardExperience(), server::zone::ZoneServer::getPlayerManager(), server::zone::ZoneProcessServer::getZoneServer(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::creature::commands::QueueCommand::server.
Referenced by doAreaMedicActionTarget(), and doQueueCommand().
bool CurePackCommand::canPerformSkill (CreatureObject * creature, CreatureObject * creatureTarget, CurePack * curePack) inline
Definition at line 261 of file CurePackCommand.h.
References server::zone::objects::creature::CreatureObject::canTreatConditions(), CollisionManager::checkLineOfSight(), CreatureState::DISEASED, server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::ZoneProcessServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::isDiseased(), server::zone::objects::creature::CreatureObject::isHealableBy(), server::zone::objects::creature::CreatureObject::isMeditating(), server::zone::objects::creature::CreatureObject::isMounted(), server::zone::objects::creature::CreatureObject::isOnFire(), server::zone::objects::creature::CreatureObject::isPoisoned(), server::zone::objects::creature::CreatureObject::isProne(), server::zone::objects::creature::CreatureObject::isRidingCreature(), CreatureAttribute::MIND, mindCost, CreatureState::ONFIRE, CreatureState::POISONED, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::commands::QueueCommand::server, server::chat::StringIdChatParameter::setTT(), and state.
Referenced by doQueueCommand().
bool CurePackCommand::checkTarget (CreatureObject * creature, CreatureObject * creatureTarget) inline
Definition at line 156 of file CurePackCommand.h.
References CollisionManager::checkLineOfSight(), CreatureState::DISEASED, server::zone::ZoneProcessServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::isDiseased(), server::zone::objects::creature::CreatureObject::isHealableBy(), server::zone::objects::creature::CreatureObject::isOnFire(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isPoisoned(), CreatureState::ONFIRE, CreatureState::POISONED, server::zone::objects::creature::commands::QueueCommand::server, and state.
Referenced by handleArea().
void CurePackCommand::deactivateConditionTreatment (CreatureObject * creature) inline
Definition at line 119 of file CurePackCommand.h.
References server::zone::objects::scene::SceneObject::addPendingTask(), BuffCRC::FOOD_HEAL_RECOVERY, server::zone::objects::creature::CreatureObject::getBuff(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::buffs::Buff::getSkillModifierValue(), and server::zone::objects::creature::CreatureObject::hasBuff().
Referenced by doQueueCommand().
void CurePackCommand::doAnimations (CreatureObject * creature, CreatureObject * creatureTarget) inline
Definition at line 34 of file CurePackCommand.h.
References server::zone::objects::creature::CreatureObject::doAnimation(), and server::zone::objects::creature::CreatureObject::playEffect().
Referenced by doQueueCommand().
void CurePackCommand::doAreaMedicActionTarget (CreatureObject * creature, CreatureObject * creatureTarget, PharmaceuticalObject * pharma) inline
Definition at line 245 of file CurePackCommand.h.
References awardXp(), server::zone::objects::tangible::pharmaceutical::CurePack::calculatePower(), server::zone::objects::creature::CreatureObject::healDot(), server::zone::objects::tangible::pharmaceutical::PharmaceuticalObject::isCurePack(), sendCureMessage(), and state.
Referenced by handleArea().
int CurePackCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline virtual
Reimplemented from server::zone::objects::creature::commands::QueueCommand.
Definition at line 355 of file CurePackCommand.h.
References awardXp(), canPerformSkill(), server::zone::objects::creature::commands::QueueCommand::checkInvalidLocomotions(), server::zone::objects::creature::commands::QueueCommand::checkStateMask(), deactivateConditionTreatment(), doAnimations(), findCurePack(), server::zone::objects::creature::commands::QueueCommand::GENERALERROR, server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::ZoneProcessServer::getZoneServer(), handleArea(), server::zone::objects::creature::CreatureObject::healDot(), server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::creature::commands::QueueCommand::INVALIDLOCOMOTION, server::zone::objects::creature::commands::QueueCommand::INVALIDSTATE, server::zone::objects::creature::commands::QueueCommand::INVALIDTARGET, server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::creature::CreatureObject::isAttackableBy(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::CreatureObject::isMounted(), server::zone::objects::creature::CreatureObject::isRidingCreature(), ObserverEventType::MEDPACKUSED, CreatureAttribute::MIND, mindCost, parseModifier(), range, sendCureMessage(), server::zone::objects::creature::commands::QueueCommand::server, state, server::zone::objects::creature::commands::QueueCommand::SUCCESS, and server::zone::objects::creature::commands::QueueCommand::TOOFAR.
CurePack* CurePackCommand::findCurePack (CreatureObject * creature) inline
Definition at line 50 of file CurePackCommand.h.
References server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::tangible::pharmaceutical::PharmaceuticalObject::getMedicineUseRequired(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::tangible::pharmaceutical::CurePack::getState(), server::zone::objects::tangible::pharmaceutical::PharmaceuticalObject::isCurePack(), server::zone::objects::tangible::TangibleObject::isPharmaceuticalObject(), server::zone::objects::scene::SceneObject::isTangibleObject(), and state.
Referenced by doQueueCommand().
void CurePackCommand::handleArea (CreatureObject * creature, CreatureObject * areaCenter, CurePack * pharma, float range) inline
Definition at line 197 of file CurePackCommand.h.
References checkTarget(), doAreaMedicActionTarget(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isAttackableBy(), server::zone::objects::scene::SceneObject::isInRange(), and server::zone::objects::scene::SceneObject::isPlayerCreature().
Referenced by doQueueCommand().
void CurePackCommand::parseModifier (const String & modifier, uint64 & objectId) inline
Definition at line 43 of file CurePackCommand.h.
Referenced by doQueueCommand().
void CurePackCommand::sendCureMessage (CreatureObject * object, CreatureObject * target) inline
Definition at line 80 of file CurePackCommand.h.
References CreatureState::DISEASED, server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), CreatureState::ONFIRE, CreatureState::POISONED, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and state.
Referenced by doAreaMedicActionTarget(), and doQueueCommand().
Member Data Documentation
int CurePackCommand::mindCost protected
Definition at line 24 of file CurePackCommand.h.
Referenced by canPerformSkill(), CurePackCommand(), and doQueueCommand().
float CurePackCommand::range protected
Definition at line 25 of file CurePackCommand.h.
Referenced by CurePackCommand(), and doQueueCommand().
uint64 CurePackCommand::state protected
Definition at line 26 of file CurePackCommand.h.
Referenced by canPerformSkill(), checkTarget(), CureDiseaseCommand::CureDiseaseCommand(), CurePoisonCommand::CurePoisonCommand(), doAreaMedicActionTarget(), doQueueCommand(), ExtinguishFireCommand::ExtinguishFireCommand(), findCurePack(), and sendCureMessage().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/CurePackCommand.h