Core3: SquadLeaderCommand Class Reference
SquadLeaderCommand Class Reference
#include <SquadLeaderCommand.h>
Public Member Functions
SquadLeaderCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
bool checkGroupLeader (CreatureObject *player, GroupObject *group)
bool shoutCommand (CreatureObject *player, GroupObject *group)
float calculateGroupModifier (GroupObject *group)
bool inflictHAM (CreatureObject *player, int health, int action, int mind)
void sendCombatSpam (CreatureObject *player)
bool setCommandMessage (CreatureObject *creature, String message)
bool isSquadLeaderCommand ()
String getAction () const
void setAction (String action)
Public Member Functions inherited from CombatQueueCommand
CombatQueueCommand (const String &name, ZoneProcessServer *server)
int doCombatAction (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments="", ManagedReference< WeaponObject * > weapon=NULL)
float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
uint32 getDotDuration () const
uint64 getDotType () const
uint8 getDotPool () const
uint32 getDotStrength () const
float getDotPotency () const
float getHealthCostMultiplier () const
float getActionCostMultiplier () const
float getMindCostMultiplier () const
int getRange () const
String getAccuracySkillMod () const
int getBlindChance () const
float getDamageMultiplier () const
int getAccuracyBonus () const
int getDizzyChance () const
int getIntimidateChance () const
int getKnockdownChance () const
int getPostureDownChance () const
int getPostureUpChance () const
float getSpeedMultiplier () const
float getSpeed () const
int getStunChance () const
bool isAreaAction () const
bool isConeAction () const
bool isDotDamageOfHit () const
int getConeAngle () const
int getAreaRange () const
int getDurationStateTime () const
float getForceCostMultiplier () const
float getForceCost () const
int getNextAttackDelayChance () const
void setBlindStateChance (int blindStateChance)
void setDamageMultiplier (float damageMultiplier)
void setAccuracyBonus (int accuracyBonus)
void setHealthCostMultiplier (float f)
void setActionCostMultiplier (float f)
void setMindCostMultiplier (float f)
void setForceCostMultiplier (float f)
void setForceCost (float f)
void setDizzyStateChance (int dizzyStateChance)
void setIntimidateStateChance (int intimidateStateChance)
void setKnockdownStateChance (int knockdownStateChance)
void setPostureDownStateChance (int postureDownStateChance)
void setPostureUpStateChance (int postureUpStateChance)
void setNextAttackDelayChance (int i)
void setDurationStateTime (int i)
void setDotDuration (uint32 i)
void setDotType (uint64 l)
void setDotPool (uint8 c)
void setDotStrength (uint32 i)
void setDotPotency (float f)
void setConeAngle (int i)
void setDotDamageOfHit (bool b)
void setAreaAction (bool b)
void setConeAction (bool b)
void setAreaRange (int i)
void setEffectString (String s)
void setSpeedMultiplier (float speedMultiplier)
void setSpeed (float speedd)
void setStunStateChance (int stunStateChance)
uint32 getAnimationCRC () const
String getEffectString () const
String getCombatSpam () const
int getPoolsToDamage () const
VectorMap< uint64, StateEffect > * getStateEffects ()
VectorMap< uint64, DotEffect > * getDotEffects ()
void setAnimationCRC (uint32 animationCRC)
void setCombatSpam (String combatSpam)
void setPoolsToDamage (int poolsToDamage)
void setStateEffects (VectorMap< uint64, StateEffect > stateEffects)
void addStateEffect (StateEffect stateEffect)
StateEffect getStateEffect (uint64 type)
void setDotEffects (VectorMap< uint64, DotEffect > dotEffects)
float getDamage () const
void setDamage (float dm)
void addDotEffect (DotEffect dotEffect)
DotEffect getDotEffect (uint64 type)
void setRange (int i)
void setAccuracySkillMod (String acc)
bool hasCombatSpam ()
bool isCombatCommand ()
virtual void applyEffect (CreatureObject *creature, uint8 effectType, uint32 mod)
uint8 getAttackType () const
void setAttackType (uint8 attackType)
uint8 getTrails () const
void setTrails (uint8 trails)
Public Member Functions inherited from server::zone::objects::creature::commands::QueueCommand
QueueCommand (const String &skillname, ZoneProcessServer *serv)
virtual ~QueueCommand ()
bool checkInvalidLocomotions (CreatureObject *creature)
void onStateFail (CreatureObject *creature, uint32 actioncntr)
void onLocomotionFail (CreatureObject *creature, uint32 actioncntr)
virtual String getSyntax () const
virtual void onFail (uint32 actioncntr, CreatureObject *creature, uint32 errorNumber)
virtual void onComplete (uint32 actioncntr, CreatureObject *creature, float commandDuration)
void setInvalidLocomotions (const String &lStr)
void addInvalidLocomotion (int l)
bool checkStateMask (CreatureObject *creature)
void setStateMask (uint64 mask)
void setDefaultTime (float time)
void setTargetType (int num)
void setDisabled (bool state)
void setDisabled (int state)
void setAddToCombatQueue (bool state)
void setAddToCombatQueue (int state)
void setCommandGroup (int val)
void setMaxRange (float r)
void setCharacterAbility (const String &ability)
void setDefaultPriority (const String &priority)
void setDefaultPriority (const int priority)
uint64 getStateMask ()
bool requiresAdmin ()
int getTargetType ()
uint32 getNameCRC ()
float getMaxRange ()
String & getQueueCommandName ()
String & getCharacterAbility ()
float getDefaultTime ()
int getDefaultPriority ()
bool isDisabled ()
bool addToCombatQueue ()
int getSkillModSize ()
int getSkillMod (int index, String &skillMod)
int getCommandGroup ()
void addSkillMod (const String &skillMod, const int value)
bool isWearingArmor (CreatureObject *creo)
virtual void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Protected Attributes
String action
uint32 actionCRC
Protected Attributes inherited from CombatQueueCommand
float damage
float damageMultiplier
int accuracyBonus
float speedMultiplier
float speed
int poolsToDamage
float healthCostMultiplier
float actionCostMultiplier
float mindCostMultiplier
float forceCostMultiplier
float forceCost
int knockdownStateChance
int postureDownStateChance
int postureUpStateChance
int dizzyStateChance
int blindStateChance
int stunStateChance
int intimidateStateChance
int nextAttackDelayChance
int durationStateTime
uint32 dotDuration
uint64 dotType
uint8 dotPool
uint32 dotStrength
float dotPotency
bool dotDamageOfHit
int range
String accuracySkillMod
bool areaAction
bool coneAction
int coneAngle
int areaRange
String combatSpam
String stateSpam
uint32 animationCRC
String effectString
VectorMap< uint64, StateEffect > stateEffects
VectorMap< uint64, DotEffect > dotEffects
uint8 attackType
uint8 trails
Protected Attributes inherited from server::zone::objects::creature::commands::QueueCommand
ZoneProcessServer * server
String name
uint32 nameCRC
uint64 stateMask
Vector< int > invalidLocomotion
int targetType
int maxRangeToTarget
bool disabled
bool addToQueue
bool admin
uint32 cooldown
float defaultTime
String characterAbility
int defaultPriority
VectorMap< String, int > skillMods
int commandGroup
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::creature::commands::QueueCommand
static const int IMMEDIATE = 0
static const int FRONT = 1
static const int NORMAL = 2
static const int SUCCESS = 0
static const int GENERALERROR = 1
static const int INVALIDLOCOMOTION = 2
static const int INVALIDSTATE = 3
static const int INVALIDTARGET = 4
static const int INVALIDWEAPON = 5
static const int TOOFAR = 6
static const int INSUFFICIENTHAM = 7
static const int INVALIDPARAMETERS = 8
static const int NOPRONE = 9
static const int NOKNEELING = 10
static const int INSUFFICIENTPERMISSION = 11
static const int NOJEDIARMOR = 12
static const int INVALIDSYNTAX = 13
Detailed Description
Definition at line 15 of file SquadLeaderCommand.h.
Constructor & Destructor Documentation
SquadLeaderCommand::SquadLeaderCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 22 of file SquadLeaderCommand.h.
References action, actionCRC, and CombatQueueCommand::combatSpam.
Member Function Documentation
float SquadLeaderCommand::calculateGroupModifier (GroupObject * group) inline
Definition at line 80 of file SquadLeaderCommand.h.
References server::zone::objects::group::GroupObject::getGroupSize().
Referenced by FormupCommand::doQueueCommand(), SteadyaimCommand::doQueueCommand(), RallyCommand::doQueueCommand(), VolleyFireCommand::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), and RetreatCommand::doQueueCommand().
bool SquadLeaderCommand::checkGroupLeader (CreatureObject * player, GroupObject * group) inline
Definition at line 41 of file SquadLeaderCommand.h.
References server::zone::objects::group::GroupObject::getLeader(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by FormupCommand::doQueueCommand(), SteadyaimCommand::doQueueCommand(), RallyCommand::doQueueCommand(), VolleyFireCommand::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), and RetreatCommand::doQueueCommand().
int SquadLeaderCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline virtual
Reimplemented from server::zone::objects::creature::commands::QueueCommand.
Reimplemented in VolleyFireCommand, and SteadyaimCommand.
Definition at line 30 of file SquadLeaderCommand.h.
References server::zone::objects::creature::commands::QueueCommand::checkInvalidLocomotions(), server::zone::objects::creature::commands::QueueCommand::checkStateMask(), server::zone::objects::creature::commands::QueueCommand::INVALIDLOCOMOTION, server::zone::objects::creature::commands::QueueCommand::INVALIDSTATE, and server::zone::objects::creature::commands::QueueCommand::SUCCESS.
String SquadLeaderCommand::getAction () const inline
Definition at line 138 of file SquadLeaderCommand.h.
References action.
bool SquadLeaderCommand::inflictHAM (CreatureObject * player, int health, int action, int mind) inline
Definition at line 90 of file SquadLeaderCommand.h.
References CreatureAttribute::ACTION, server::zone::objects::creature::CreatureObject::getHAM(), CreatureAttribute::HEALTH, server::zone::objects::creature::CreatureObject::inflictDamage(), and CreatureAttribute::MIND.
Referenced by FormupCommand::doQueueCommand(), RallyCommand::doQueueCommand(), SteadyaimCommand::doQueueCommand(), VolleyFireCommand::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), RetreatCommand::doQueueCommand(), and RetreatCommand::doRetreat().
bool SquadLeaderCommand::isSquadLeaderCommand () inline virtual
Reimplemented from CombatQueueCommand.
Definition at line 134 of file SquadLeaderCommand.h.
void SquadLeaderCommand::sendCombatSpam (CreatureObject * player) inline
Definition at line 111 of file SquadLeaderCommand.h.
References CombatQueueCommand::combatSpam, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by BoostmoraleCommand::distributeWounds(), FormupCommand::doFormUp(), RetreatCommand::doQueueCommand(), RallyCommand::doRally(), and SteadyaimCommand::doSteadyAim().
void SquadLeaderCommand::setAction (String action) inline
Definition at line 142 of file SquadLeaderCommand.h.
References action.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
bool SquadLeaderCommand::setCommandMessage (CreatureObject * creature, String message) inline
Definition at line 120 of file SquadLeaderCommand.h.
References actionCRC, and server::zone::objects::creature::CreatureObject::isPlayerCreature().
Referenced by SetBoostmoraleCommand::doQueueCommand(), SetSteadyaimCommand::doQueueCommand(), SetRetreatCommand::doQueueCommand(), and SetFormupCommand::doQueueCommand().
bool SquadLeaderCommand::shoutCommand (CreatureObject * player, GroupObject * group) inline
Definition at line 63 of file SquadLeaderCommand.h.
References actionCRC, server::zone::ZoneProcessServer::getChatManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), and server::zone::objects::creature::commands::QueueCommand::server.
Referenced by FormupCommand::doQueueCommand(), SteadyaimCommand::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), and RetreatCommand::doQueueCommand().
Member Data Documentation
String SquadLeaderCommand::action protected
Definition at line 17 of file SquadLeaderCommand.h.
Referenced by getAction(), setAction(), and SquadLeaderCommand().
uint32 SquadLeaderCommand::actionCRC protected
Definition at line 18 of file SquadLeaderCommand.h.
Referenced by RallyCommand::doRally(), RetreatCommand::doRetreat(), SteadyaimCommand::doSteadyAim(), setCommandMessage(), shoutCommand(), and SquadLeaderCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/SquadLeaderCommand.h