Core3: DeltaVectorMap< K, V > Class Template Reference
DeltaVectorMap< K, V > Class Template Reference
#include <DeltaVectorMap.h>
Public Member Functions
DeltaVectorMap ()
DeltaVectorMap (int initsize, int incr)
DeltaVectorMap (const DeltaVectorMap &ds)
void addSerializableVariables ()
virtual int set (const K &key, const V &value, DeltaMessage *message=NULL, int updates=1)
virtual bool drop (const K &key, DeltaMessage *message=NULL, int updates=1)
virtual void insertToMessage (BaseMessage *msg)
V & getValueAt (int index)
K & getKeyAt (int index)
V & get (const K &key)
bool contains (const K &key)
int size ()
uint32 getUpdateCounter ()
void setNullValue (const V &val)
Protected Attributes
VectorMap< K, V > vectorMap
uint32 updateCounter
Detailed Description
template<class K, class V>
class DeltaVectorMap< K, V >
Definition at line 14 of file DeltaVectorMap.h.
Constructor & Destructor Documentation
template<class K, class V> DeltaVectorMap< K, V >::DeltaVectorMap () inline
Definition at line 20 of file DeltaVectorMap.h.
template<class K, class V> DeltaVectorMap< K, V >::DeltaVectorMap (int initsize, int incr) inline
Definition at line 28 of file DeltaVectorMap.h.
template<class K, class V> DeltaVectorMap< K, V >::DeltaVectorMap (const DeltaVectorMap< K, V > & ds) inline
Definition at line 36 of file DeltaVectorMap.h.
Member Function Documentation
template<class K, class V> void DeltaVectorMap< K, V >::addSerializableVariables () inline
Definition at line 44 of file DeltaVectorMap.h.
Referenced by DeltaVectorMap< String, SkillModEntry >::DeltaVectorMap().
template<class K, class V> bool DeltaVectorMap< K, V >::contains (const K & key) inline
Definition at line 116 of file DeltaVectorMap.h.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addExperience(), server::zone::objects::creature::CreatureObjectImplementation::addSkillMod(), server::zone::objects::player::PlayerObjectImplementation::addWaypoint(), server::zone::objects::player::PlayerObjectImplementation::hasCappedExperience(), and server::zone::objects::player::PlayerObjectImplementation::removeExperience().
template<class K, class V> virtual bool DeltaVectorMap< K, V >::drop (const K & key, DeltaMessage * message = NULL, int updates = 1) inline virtual
Reimplemented in WaypointList.
Definition at line 67 of file DeltaVectorMap.h.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::addSkillMod(), and server::zone::objects::player::PlayerObjectImplementation::removeExperience().
template<class K, class V> V& DeltaVectorMap< K, V >::get (const K & key) inline
Definition at line 112 of file DeltaVectorMap.h.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addExperience(), server::zone::objects::creature::CreatureObjectImplementation::addSkillMod(), server::zone::objects::player::PlayerObjectImplementation::getSurveyWaypoint(), server::zone::objects::player::PlayerObjectImplementation::hasCappedExperience(), server::zone::objects::player::PlayerObjectImplementation::removeWaypoint(), and server::zone::managers::skill::SkillManager::updateXpLimits().
template<class K, class V> K& DeltaVectorMap< K, V >::getKeyAt (int index) inline
Definition at line 108 of file DeltaVectorMap.h.
Referenced by DeltaVectorMap< String, SkillModEntry >::insertToMessage(), and server::zone::managers::skill::SkillManager::updateXpLimits().
template<class K, class V> uint32 DeltaVectorMap< K, V >::getUpdateCounter () inline
Definition at line 124 of file DeltaVectorMap.h.
Referenced by DeltaVectorMap< String, SkillModEntry >::insertToMessage().
template<class K, class V> V& DeltaVectorMap< K, V >::getValueAt (int index) inline
Definition at line 104 of file DeltaVectorMap.h.
Referenced by DeltaVectorMap< String, SkillModEntry >::insertToMessage().
template<class K, class V> virtual void DeltaVectorMap< K, V >::insertToMessage (BaseMessage * msg) inline virtual
Reimplemented in WaypointList.
Definition at line 90 of file DeltaVectorMap.h.
Referenced by CreatureObjectMessage4::CreatureObjectMessage4(), and PlayerObjectMessage8::PlayerObjectMessage8().
template<class K, class V> virtual int DeltaVectorMap< K, V >::set (const K & key, const V & value, DeltaMessage * message = NULL, int updates = 1) inline virtual
Definition at line 49 of file DeltaVectorMap.h.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addExperience(), and server::zone::objects::creature::CreatureObjectImplementation::addSkillMod().
template<class K, class V> void DeltaVectorMap< K, V >::setNullValue (const V & val) inline
Definition at line 128 of file DeltaVectorMap.h.
Referenced by server::zone::objects::player::PlayerObjectImplementation::loadTemplateData().
template<class K, class V> int DeltaVectorMap< K, V >::size () inline
Definition at line 120 of file DeltaVectorMap.h.
Referenced by DeltaVectorMap< String, SkillModEntry >::insertToMessage(), and server::zone::managers::skill::SkillManager::updateXpLimits().
Member Data Documentation
template<class K, class V> uint32 DeltaVectorMap< K, V >::updateCounter protected
Definition at line 17 of file DeltaVectorMap.h.
Referenced by DeltaVectorMap< String, SkillModEntry >::addSerializableVariables(), DeltaVectorMap< String, SkillModEntry >::DeltaVectorMap(), DeltaVectorMap< String, SkillModEntry >::drop(), DeltaVectorMap< String, SkillModEntry >::getUpdateCounter(), and DeltaVectorMap< String, SkillModEntry >::set().
template<class K, class V> VectorMap<K, V> DeltaVectorMap< K, V >::vectorMap protected
Definition at line 16 of file DeltaVectorMap.h.
Referenced by DeltaVectorMap< String, SkillModEntry >::addSerializableVariables(), DeltaVectorMap< String, SkillModEntry >::contains(), DeltaVectorMap< String, SkillModEntry >::DeltaVectorMap(), DeltaVectorMap< String, SkillModEntry >::drop(), DeltaVectorMap< String, SkillModEntry >::get(), DeltaVectorMap< String, SkillModEntry >::getKeyAt(), DeltaVectorMap< String, SkillModEntry >::getValueAt(), DeltaVectorMap< String, SkillModEntry >::set(), DeltaVectorMap< String, SkillModEntry >::setNullValue(), and DeltaVectorMap< String, SkillModEntry >::size().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/DeltaVectorMap.h