Core3: server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler Class Reference
server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler Class Reference
#include <InformantMissionScreenHandler.h>
Public Member Functions
InformantMissionScreenHandler ()
ConversationScreen * handleScreen (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::conversation::screenhandlers::ScreenHandler
ScreenHandler ()
~ScreenHandler ()
String getNextScreenId ()
Static Public Attributes
static const String STARTSCREENHANDLERID = "convoscreenstart"
Protected Member Functions
MissionObject * getBountyMissionObject (CreatureObject *player)
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::conversation::screenhandlers::ScreenHandler
String nextScreenId
Detailed Description
Definition at line 60 of file InformantMissionScreenHandler.h.
Constructor & Destructor Documentation
server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::InformantMissionScreenHandler () inline
Definition at line 67 of file InformantMissionScreenHandler.h.
Member Function Documentation
MissionObject * InformantMissionScreenHandler::getBountyMissionObject (CreatureObject * player) protected
Definition at line 51 of file InformantMissionScreenHandler.cpp.
References server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), and server::zone::objects::scene::SceneObject::getSlottedObject().
Referenced by handleScreen().
ConversationScreen * InformantMissionScreenHandler::handleScreen (CreatureObject * conversingPlayer, CreatureObject * conversingNPC, int selectedOption, ConversationScreen * conversationScreen) virtual
Implements server::zone::objects::creature::conversation::screenhandlers::ScreenHandler.
Definition at line 81 of file InformantMissionScreenHandler.cpp.
References getBountyMissionObject(), server::zone::objects::mission::MissionObject::getMissionLevel(), server::zone::objects::mission::MissionObject::getMissionObjective(), server::zone::objects::mission::BountyMissionObjective::getObjectiveStatus(), server::zone::templates::mobile::ConversationScreen::getOptionLink(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::templates::mobile::ConversationScreen::setDialogText(), and server::zone::objects::mission::BountyMissionObjective::updateMissionStatus().
bool server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::parseFromBinaryStream (ObjectInputStream * stream) inline
Definition at line 75 of file InformantMissionScreenHandler.h.
bool server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::toBinaryStream (ObjectOutputStream * stream) inline
Definition at line 71 of file InformantMissionScreenHandler.h.
Member Data Documentation
const String InformantMissionScreenHandler::STARTSCREENHANDLERID = "convoscreenstart" static
Definition at line 65 of file InformantMissionScreenHandler.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/screenhandlers/InformantMissionScreenHandler.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/screenhandlers/InformantMissionScreenHandler.cpp