Core3: server::zone::objects::mission::CraftingMissionObjective Class Reference
server::zone::objects::mission::CraftingMissionObjective Class Reference
#include <CraftingMissionObjective.h>
Public Member Functions
CraftingMissionObjective (MissionObject *mission)
void initializeTransientMembers ()
void updateMissionStatus (CreatureObject *player)
void abort ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::mission::DeliverMissionObjective
DeliverMissionObjective (MissionObject *mission)
void initializeTransientMembers ()
TangibleObject * getItem ()
int getObjectiveStatus ()
void activate ()
void deactivate ()
bool activateWithResult ()
void abort ()
void complete ()
void despawnNpcs ()
void updateMissionStatus (CreatureObject *player)
bool updateMissionTarget (CreatureObject *player)
NpcSpawnPoint * getTargetSpawnPoint ()
NpcSpawnPoint * getDestinationSpawnPoint ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (MissionObject *parent)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
CraftingMissionObjective (DummyConstructorParameter *param)
virtual ~CraftingMissionObjective ()
Protected Member Functions inherited from server::zone::objects::mission::DeliverMissionObjective
DeliverMissionObjective (DummyConstructorParameter *param)
virtual ~DeliverMissionObjective ()
Protected Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (DummyConstructorParameter *param)
virtual ~MissionObjective ()
Friends
class CraftingMissionObjectiveHelper
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::mission::DeliverMissionObjective
static const int INITSTATUS = 0
static const int PICKEDUPSTATUS = 1
static const int DELIVEREDSTATUS = 2
Detailed Description
Definition at line 49 of file CraftingMissionObjective.h.
Constructor & Destructor Documentation
CraftingMissionObjective::CraftingMissionObjective (MissionObject * mission)
Definition at line 17 of file CraftingMissionObjective.cpp.
References server::zone::objects::mission::CraftingMissionObjectiveImplementation::_setStub().
CraftingMissionObjective::CraftingMissionObjective (DummyConstructorParameter * param) protected
Definition at line 24 of file CraftingMissionObjective.cpp.
CraftingMissionObjective::~CraftingMissionObjective () protected virtual
Definition at line 28 of file CraftingMissionObjective.cpp.
Member Function Documentation
DistributedObjectServant * CraftingMissionObjective::_getImplementation ()
Definition at line 73 of file CraftingMissionObjective.cpp.
Referenced by abort(), initializeTransientMembers(), and updateMissionStatus().
DistributedObjectServant * CraftingMissionObjective::_getImplementationForRead ()
Definition at line 79 of file CraftingMissionObjective.cpp.
void CraftingMissionObjective::_setImplementation (DistributedObjectServant * servant)
Definition at line 83 of file CraftingMissionObjective.cpp.
void CraftingMissionObjective::abort ()
Definition at line 60 of file CraftingMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::CraftingMissionObjectiveImplementation::abort(), and RPC_ABORT__.
void CraftingMissionObjective::initializeTransientMembers ()
Definition at line 33 of file CraftingMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::CraftingMissionObjectiveImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
void CraftingMissionObjective::updateMissionStatus (CreatureObject * player)
Definition at line 46 of file CraftingMissionObjective.cpp.
References _getImplementation(), RPC_UPDATEMISSIONSTATUS__CREATUREOBJECT_, and server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus().
Friends And Related Function Documentation
friend class CraftingMissionObjectiveHelper friend
Definition at line 69 of file CraftingMissionObjective.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/CraftingMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/CraftingMissionObjective.cpp