Core3: server::zone::objects::mission::HuntingMissionObjective Class Reference
server::zone::objects::mission::HuntingMissionObjective Class Reference
#include <HuntingMissionObjective.h>
Public Member Functions
HuntingMissionObjective (MissionObject *mission)
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (MissionObject *parent)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
HuntingMissionObjective (DummyConstructorParameter *param)
virtual ~HuntingMissionObjective ()
Protected Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (DummyConstructorParameter *param)
virtual ~MissionObjective ()
Friends
class HuntingMissionObjectiveHelper
Detailed Description
Definition at line 95 of file HuntingMissionObjective.h.
Constructor & Destructor Documentation
HuntingMissionObjective::HuntingMissionObjective (MissionObject * mission)
Definition at line 23 of file HuntingMissionObjective.cpp.
References server::zone::objects::mission::HuntingMissionObjectiveImplementation::_setStub().
HuntingMissionObjective::HuntingMissionObjective (DummyConstructorParameter * param) protected
Definition at line 30 of file HuntingMissionObjective.cpp.
HuntingMissionObjective::~HuntingMissionObjective () protected virtual
Definition at line 34 of file HuntingMissionObjective.cpp.
Member Function Documentation
DistributedObjectServant * HuntingMissionObjective::_getImplementation ()
Definition at line 118 of file HuntingMissionObjective.cpp.
Referenced by abort(), activate(), complete(), getEndPosition(), initializeTransientMembers(), and notifyObserverEvent().
DistributedObjectServant * HuntingMissionObjective::_getImplementationForRead ()
Definition at line 124 of file HuntingMissionObjective.cpp.
void HuntingMissionObjective::_setImplementation (DistributedObjectServant * servant)
Definition at line 128 of file HuntingMissionObjective.cpp.
void HuntingMissionObjective::abort ()
Definition at line 65 of file HuntingMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::abort(), and RPC_ABORT__.
void HuntingMissionObjective::activate ()
Definition at line 52 of file HuntingMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::activate(), and RPC_ACTIVATE__.
void HuntingMissionObjective::complete ()
Definition at line 78 of file HuntingMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::complete(), and RPC_COMPLETE__.
Vector3 HuntingMissionObjective::getEndPosition ()
Definition at line 109 of file HuntingMissionObjective.cpp.
References _getImplementation(), and server::zone::objects::mission::HuntingMissionObjectiveImplementation::getEndPosition().
void HuntingMissionObjective::initializeTransientMembers ()
Definition at line 39 of file HuntingMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
int HuntingMissionObjective::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 91 of file HuntingMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class HuntingMissionObjectiveHelper friend
Definition at line 121 of file HuntingMissionObjective.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/HuntingMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/HuntingMissionObjective.cpp