Core3: server::zone::objects::player::sessions::StructureStatusSessionImplementation Class Reference
server::zone::objects::player::sessions::StructureStatusSessionImplementation Class Reference
#include <StructureStatusSession.h>
Public Member Functions
StructureStatusSessionImplementation (StructureObject *structure)
StructureStatusSessionImplementation (DummyConstructorParameter *param)
int initializeSession ()
int updateStatus ()
int cancelSession ()
int clearSession ()
operator const StructureStatusSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< StructureStatusSession * > _this
Protected Member Functions
virtual ~StructureStatusSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< StructureObject * > structureObject
Friends
class StructureStatusSession
Detailed Description
Definition at line 63 of file StructureStatusSession.h.
Constructor & Destructor Documentation
StructureStatusSessionImplementation::StructureStatusSessionImplementation (StructureObject * structure)
Definition at line 225 of file StructureStatusSession.cpp.
References _initializeImplementation(), initializeSession(), and structureObject.
StructureStatusSessionImplementation::StructureStatusSessionImplementation (DummyConstructorParameter * param)
Definition at line 99 of file StructureStatusSession.cpp.
References _initializeImplementation().
StructureStatusSessionImplementation::~StructureStatusSessionImplementation () protected virtual
Definition at line 104 of file StructureStatusSession.cpp.
Member Function Documentation
DistributedObjectStub * StructureStatusSessionImplementation::_getStub ()
Definition at line 124 of file StructureStatusSession.cpp.
References _this.
void StructureStatusSessionImplementation::_initializeImplementation () protected
Definition at line 111 of file StructureStatusSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by StructureStatusSessionImplementation().
void StructureStatusSessionImplementation::_serializationHelperMethod () protected
Definition at line 160 of file StructureStatusSession.cpp.
Referenced by _initializeImplementation().
void StructureStatusSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 119 of file StructureStatusSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::StructureStatusSession::StructureStatusSession().
int StructureStatusSessionImplementation::cancelSession ()
Definition at line 247 of file StructureStatusSession.cpp.
Referenced by server::zone::objects::player::sessions::StructureStatusSession::cancelSession().
int StructureStatusSessionImplementation::clearSession ()
Definition at line 252 of file StructureStatusSession.cpp.
Referenced by server::zone::objects::player::sessions::StructureStatusSession::clearSession().
void StructureStatusSessionImplementation::finalize () protected
Definition at line 108 of file StructureStatusSession.cpp.
int StructureStatusSessionImplementation::initializeSession ()
Definition at line 237 of file StructureStatusSession.cpp.
Referenced by server::zone::objects::player::sessions::StructureStatusSession::initializeSession(), and StructureStatusSessionImplementation().
void StructureStatusSessionImplementation::lock (bool doLock = true) protected
Definition at line 132 of file StructureStatusSession.cpp.
References _this.
void StructureStatusSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 136 of file StructureStatusSession.cpp.
References _this.
StructureStatusSessionImplementation::operator const StructureStatusSession * ()
Definition at line 128 of file StructureStatusSession.cpp.
void StructureStatusSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 167 of file StructureStatusSession.cpp.
References readObjectMember().
bool StructureStatusSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 186 of file StructureStatusSession.cpp.
References structureObject.
Referenced by readObject().
void StructureStatusSessionImplementation::rlock (bool doLock = true) protected
Definition at line 140 of file StructureStatusSession.cpp.
References _this.
void StructureStatusSessionImplementation::runlock (bool doLock = true) protected
Definition at line 156 of file StructureStatusSession.cpp.
References _this.
void StructureStatusSessionImplementation::unlock (bool doLock = true) protected
Definition at line 152 of file StructureStatusSession.cpp.
References _this.
int StructureStatusSessionImplementation::updateStatus ()
Definition at line 242 of file StructureStatusSession.cpp.
Referenced by server::zone::objects::player::sessions::StructureStatusSession::updateStatus().
void StructureStatusSessionImplementation::wlock (bool doLock = true) protected
Definition at line 144 of file StructureStatusSession.cpp.
References _this.
void StructureStatusSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 148 of file StructureStatusSession.cpp.
References _this.
void StructureStatusSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 200 of file StructureStatusSession.cpp.
References writeObjectMembers().
int StructureStatusSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 207 of file StructureStatusSession.cpp.
References structureObject.
Referenced by writeObject().
Friends And Related Function Documentation
friend class StructureStatusSession friend
Definition at line 114 of file StructureStatusSession.h.
Member Data Documentation
WeakReference<StructureStatusSession*> server::zone::objects::player::sessions::StructureStatusSessionImplementation::_this
Definition at line 80 of file StructureStatusSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<StructureObject* > server::zone::objects::player::sessions::StructureStatusSessionImplementation::structureObject protected
Definition at line 65 of file StructureStatusSession.h.
Referenced by readObjectMember(), StructureStatusSessionImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureStatusSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureStatusSession.cpp