Core3: server::zone::objects::creature::buffs::BuffImplementation Class Reference
server::zone::objects::creature::buffs::BuffImplementation Class Reference
#include <Buff.h>
Public Member Functions
BuffImplementation (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype)
BuffImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
virtual void sendTo (CreatureObject *player)
virtual void sendDestroyTo (CreatureObject *player)
virtual void activate (bool applyModifiers)
virtual void deactivate (bool removeModifiers)
virtual void activate ()
virtual void deactivate ()
VectorMap< String, int > * getSkillModifiers ()
virtual void applyAttributeModifiers ()
virtual void applySkillModifiers ()
virtual void applyStates ()
virtual void removeAttributeModifiers ()
virtual void removeSkillModifiers ()
virtual void removeStates ()
virtual void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
virtual void parseAttributeModifierString (const String &modifierstring)
virtual void parseSkillModifierString (const String &modifierstring)
virtual String getAttributeModifierString ()
virtual String getSkillModifierString ()
virtual float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
VectorMap< byte, int > * getAttributeModifiers ()
virtual int getAttributeModifierValue (byte attribute)
virtual int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartMessage (StringIdChatParameter &start)
void setEndMessage (StringIdChatParameter &end)
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
operator const Buff * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< Buff * > _this
Protected Member Functions
virtual ~BuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > creature
Reference< BuffDurationEvent * > buffEvent
VectorMap< byte, int > attributeModifiers
VectorMap< String, int > skillModifiers
Vector< unsigned long long > states
String buffName
float buffDuration
unsigned int buffCRC
int buffType
bool fillAttributesOnBuff
StringIdChatParameter startMessage
StringIdChatParameter endMessage
String startFlyFile
String startFlyAux
byte startFlyRed
byte startFlyGreen
byte startFlyBlue
String endFlyFile
String endFlyAux
byte endFlyRed
byte endFlyGreen
byte endFlyBlue
Time nextExecutionTime
Friends
class Buff
Detailed Description
Definition at line 206 of file Buff.h.
Constructor & Destructor Documentation
BuffImplementation::BuffImplementation (CreatureObject * creo, unsigned int buffcrc, float duration, int bufftype)
Definition at line 1033 of file Buff.cpp.
References _initializeImplementation(), buffCRC, buffDuration, buffType, creature, endFlyFile, fillAttributesOnBuff, init(), and startFlyFile.
BuffImplementation::BuffImplementation (DummyConstructorParameter * param)
Definition at line 655 of file Buff.cpp.
References _initializeImplementation().
BuffImplementation::~BuffImplementation () protected virtual
Definition at line 660 of file Buff.cpp.
Member Function Documentation
DistributedObjectStub * BuffImplementation::_getStub ()
Definition at line 680 of file Buff.cpp.
References _this.
void BuffImplementation::_initializeImplementation () protected
Definition at line 667 of file Buff.cpp.
References _serializationHelperMethod(), and _this.
Referenced by BuffImplementation().
void BuffImplementation::_serializationHelperMethod () protected
Definition at line 716 of file Buff.cpp.
Referenced by _initializeImplementation(), server::zone::objects::creature::buffs::StateBuffImplementation::_serializationHelperMethod(), server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::_serializationHelperMethod(), server::zone::objects::creature::buffs::PerformanceBuffImplementation::_serializationHelperMethod(), server::zone::objects::creature::buffs::DurationBuffImplementation::_serializationHelperMethod(), server::zone::objects::creature::buffs::SpiceBuffImplementation::_serializationHelperMethod(), server::zone::objects::creature::buffs::SingleUseBuffImplementation::_serializationHelperMethod(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::_serializationHelperMethod(), and server::zone::objects::creature::buffs::DelayedBuffImplementation::_serializationHelperMethod().
void BuffImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 675 of file Buff.cpp.
References _this.
Referenced by server::zone::objects::creature::buffs::StateBuffImplementation::_setStub(), server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::_setStub(), server::zone::objects::creature::buffs::PerformanceBuffImplementation::_setStub(), server::zone::objects::creature::buffs::DurationBuffImplementation::_setStub(), server::zone::objects::creature::buffs::SpiceBuffImplementation::_setStub(), server::zone::objects::creature::buffs::SingleUseBuffImplementation::_setStub(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::_setStub(), server::zone::objects::creature::buffs::DelayedBuffImplementation::_setStub(), and server::zone::objects::creature::buffs::Buff::Buff().
void BuffImplementation::activate (bool applyModifiers) virtual
Reimplemented in server::zone::objects::creature::buffs::PowerBoostBuffImplementation, server::zone::objects::creature::buffs::SpiceBuffImplementation, server::zone::objects::creature::buffs::DurationBuffImplementation, server::zone::objects::creature::buffs::PerformanceBuffImplementation, server::zone::objects::creature::buffs::SpiceDownerBuffImplementation, and server::zone::objects::creature::buffs::StateBuffImplementation.
Definition at line 113 of file BuffImplementation.cpp.
References _this, applyAttributeModifiers(), applySkillModifiers(), applyStates(), buffDuration, buffEvent, creature, server::zone::objects::scene::variables::StringId::isEmpty(), nextExecutionTime, sendTo(), startFlyAux, startFlyBlue, startFlyFile, startFlyGreen, startFlyRed, and startMessage.
Referenced by server::zone::objects::creature::buffs::Buff::activate().
void BuffImplementation::activate () virtual
Reimplemented in server::zone::objects::creature::buffs::DelayedBuffImplementation, and server::zone::objects::creature::buffs::SingleUseBuffImplementation.
Definition at line 1066 of file Buff.cpp.
Referenced by server::zone::objects::creature::buffs::StateBuffImplementation::activate(), server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::activate(), server::zone::objects::creature::buffs::PerformanceBuffImplementation::activate(), server::zone::objects::creature::buffs::DurationBuffImplementation::activate(), server::zone::objects::creature::buffs::SingleUseBuffImplementation::activate(), server::zone::objects::creature::buffs::SpiceBuffImplementation::activate(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::activate(), server::zone::objects::creature::buffs::DelayedBuffImplementation::activate(), and server::zone::objects::creature::buffs::PowerBoostBuffImplementation::deactivate().
void BuffImplementation::addState (unsigned long long option)
Definition at line 1099 of file Buff.cpp.
References states.
Referenced by server::zone::objects::creature::buffs::Buff::addState().
void BuffImplementation::applyAttributeModifiers () virtual
Definition at line 244 of file BuffImplementation.cpp.
References attributeModifiers, creature, and fillAttributesOnBuff.
Referenced by activate(), and server::zone::objects::creature::buffs::Buff::applyAttributeModifiers().
void BuffImplementation::applySkillModifiers () virtual
Definition at line 283 of file BuffImplementation.cpp.
References creature, and skillModifiers.
Referenced by activate(), and server::zone::objects::creature::buffs::Buff::applySkillModifiers().
void BuffImplementation::applyStates () virtual
Definition at line 303 of file BuffImplementation.cpp.
References creature, and states.
Referenced by activate(), and server::zone::objects::creature::buffs::Buff::applyStates().
void BuffImplementation::clearBuffEvent () virtual
Reimplemented in server::zone::objects::creature::buffs::PowerBoostBuffImplementation.
Definition at line 394 of file BuffImplementation.cpp.
References buffEvent, and nextExecutionTime.
Referenced by server::zone::objects::creature::buffs::Buff::clearBuffEvent(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::clearBuffEvent(), and deactivate().
void BuffImplementation::deactivate (bool removeModifiers) virtual
Reimplemented in server::zone::objects::creature::buffs::PowerBoostBuffImplementation, server::zone::objects::creature::buffs::SpiceBuffImplementation, server::zone::objects::creature::buffs::DurationBuffImplementation, server::zone::objects::creature::buffs::PerformanceBuffImplementation, server::zone::objects::creature::buffs::SpiceDownerBuffImplementation, and server::zone::objects::creature::buffs::StateBuffImplementation.
Definition at line 144 of file BuffImplementation.cpp.
References clearBuffEvent(), creature, endFlyAux, endFlyBlue, endFlyFile, endFlyGreen, endFlyRed, endMessage, server::zone::objects::scene::variables::StringId::isEmpty(), removeAttributeModifiers(), removeSkillModifiers(), removeStates(), and sendDestroyTo().
Referenced by server::zone::objects::creature::buffs::Buff::deactivate().
void BuffImplementation::deactivate () virtual
Reimplemented in server::zone::objects::creature::buffs::DelayedBuffImplementation, and server::zone::objects::creature::buffs::SingleUseBuffImplementation.
Definition at line 1071 of file Buff.cpp.
Referenced by server::zone::objects::creature::buffs::StateBuffImplementation::deactivate(), server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::deactivate(), server::zone::objects::creature::buffs::PerformanceBuffImplementation::deactivate(), server::zone::objects::creature::buffs::DurationBuffImplementation::deactivate(), server::zone::objects::creature::buffs::SingleUseBuffImplementation::deactivate(), server::zone::objects::creature::buffs::SpiceBuffImplementation::deactivate(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::deactivate(), and server::zone::objects::creature::buffs::DelayedBuffImplementation::deactivate().
void BuffImplementation::finalize () protected
Definition at line 664 of file Buff.cpp.
VectorMap< byte, int > * BuffImplementation::getAttributeModifiers ()
Definition at line 1139 of file Buff.cpp.
References attributeModifiers.
Referenced by server::zone::objects::creature::buffs::Buff::getAttributeModifiers().
String BuffImplementation::getAttributeModifierString () virtual
Definition at line 214 of file BuffImplementation.cpp.
Referenced by server::zone::objects::creature::buffs::Buff::getAttributeModifierString().
int BuffImplementation::getAttributeModifierValue (byte attribute) virtual
Definition at line 1144 of file Buff.cpp.
References attributeModifiers.
Referenced by server::zone::objects::creature::buffs::Buff::getAttributeModifierValue().
int BuffImplementation::getBuffCRC ()
Definition at line 1124 of file Buff.cpp.
References buffCRC.
Referenced by server::zone::objects::creature::buffs::Buff::getBuffCRC().
float BuffImplementation::getBuffDuration ()
Definition at line 1129 of file Buff.cpp.
References buffDuration.
Referenced by server::zone::objects::creature::buffs::Buff::getBuffDuration().
String BuffImplementation::getBuffName ()
Definition at line 1119 of file Buff.cpp.
References buffName.
Referenced by server::zone::objects::creature::buffs::Buff::getBuffName().
int BuffImplementation::getBuffType ()
Definition at line 1134 of file Buff.cpp.
References buffType.
Referenced by server::zone::objects::creature::buffs::Buff::getBuffType().
VectorMap< String, int > * BuffImplementation::getSkillModifiers ()
Definition at line 1076 of file Buff.cpp.
References skillModifiers.
Referenced by server::zone::objects::creature::buffs::Buff::getSkillModifiers().
String BuffImplementation::getSkillModifierString () virtual
Definition at line 218 of file BuffImplementation.cpp.
Referenced by server::zone::objects::creature::buffs::Buff::getSkillModifierString().
int BuffImplementation::getSkillModifierValue (const String & modname) virtual
Definition at line 1152 of file Buff.cpp.
References skillModifiers.
Referenced by server::zone::objects::creature::buffs::Buff::getSkillModifierValue().
float BuffImplementation::getTimeLeft () virtual
Definition at line 226 of file BuffImplementation.cpp.
References buffEvent.
Referenced by server::zone::objects::creature::buffs::Buff::getTimeLeft(), and sendTo().
void BuffImplementation::init ()
Definition at line 1055 of file Buff.cpp.
References attributeModifiers, and skillModifiers.
Referenced by BuffImplementation(), and server::zone::objects::creature::buffs::Buff::init().
void BuffImplementation::initializeTransientMembers ()
Definition at line 58 of file BuffImplementation.cpp.
References attributeModifiers, and skillModifiers.
Referenced by server::zone::objects::creature::buffs::Buff::initializeTransientMembers(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::initializeTransientMembers(), server::zone::objects::creature::buffs::StateBuffImplementation::readObject(), server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::readObject(), server::zone::objects::creature::buffs::PerformanceBuffImplementation::readObject(), server::zone::objects::creature::buffs::DurationBuffImplementation::readObject(), server::zone::objects::creature::buffs::SpiceBuffImplementation::readObject(), server::zone::objects::creature::buffs::SingleUseBuffImplementation::readObject(), server::zone::objects::creature::buffs::DelayedBuffImplementation::readObject(), and readObject().
bool BuffImplementation::isActive ()
Definition at line 405 of file BuffImplementation.cpp.
References buffEvent.
Referenced by server::zone::objects::creature::buffs::Buff::isActive().
bool BuffImplementation::isAttributeBuff ()
Definition at line 1165 of file Buff.cpp.
References attributeModifiers.
Referenced by server::zone::objects::creature::buffs::Buff::isAttributeBuff().
bool BuffImplementation::isSpiceBuff ()
Definition at line 1160 of file Buff.cpp.
References buffType, and BuffType::SPICE.
Referenced by server::zone::objects::creature::buffs::Buff::isSpiceBuff().
void BuffImplementation::loadBuffDurationEvent (CreatureObject * creo)
Definition at line 65 of file BuffImplementation.cpp.
References _this, buffDuration, buffEvent, and nextExecutionTime.
Referenced by server::zone::objects::creature::buffs::Buff::loadBuffDurationEvent().
void BuffImplementation::lock (bool doLock = true) protected
Definition at line 688 of file Buff.cpp.
References _this.
void BuffImplementation::lock (ManagedObject * obj) protected
Definition at line 692 of file Buff.cpp.
References _this.
void BuffImplementation::notifyLoadFromDatabase ()
Gets called when this objects is loaded from database
Precondition
{ this locked }
Postcondition
{ this locked }
Definition at line 83 of file BuffImplementation.cpp.
Referenced by server::zone::objects::creature::buffs::Buff::notifyLoadFromDatabase().
BuffImplementation::operator const Buff * ()
Definition at line 684 of file Buff.cpp.
void BuffImplementation::parseAttributeModifierString (const String & modifierstring) virtual
Definition at line 174 of file BuffImplementation.cpp.
References attributeModifiers, and CreatureAttribute::getAttribute().
Referenced by server::zone::objects::creature::buffs::Buff::parseAttributeModifierString().
void BuffImplementation::parseSkillModifierString (const String & modifierstring) virtual
Definition at line 194 of file BuffImplementation.cpp.
References skillModifiers.
Referenced by server::zone::objects::creature::buffs::Buff::parseSkillModifierString().
void BuffImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented in server::zone::objects::creature::buffs::DelayedBuffImplementation, server::zone::objects::creature::buffs::PowerBoostBuffImplementation, server::zone::objects::creature::buffs::SingleUseBuffImplementation, server::zone::objects::creature::buffs::SpiceBuffImplementation, server::zone::objects::creature::buffs::DurationBuffImplementation, server::zone::objects::creature::buffs::PerformanceBuffImplementation, server::zone::objects::creature::buffs::SpiceDownerBuffImplementation, and server::zone::objects::creature::buffs::StateBuffImplementation.
Definition at line 723 of file Buff.cpp.
References initializeTransientMembers(), and readObjectMember().
bool BuffImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 742 of file Buff.cpp.
References attributeModifiers, buffCRC, buffDuration, buffName, buffType, creature, endFlyAux, endFlyBlue, endFlyFile, endFlyGreen, endFlyRed, endMessage, fillAttributesOnBuff, nextExecutionTime, skillModifiers, startFlyAux, startFlyBlue, startFlyFile, startFlyGreen, startFlyRed, startMessage, and states.
Referenced by readObject(), server::zone::objects::creature::buffs::StateBuffImplementation::readObjectMember(), server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::readObjectMember(), server::zone::objects::creature::buffs::PerformanceBuffImplementation::readObjectMember(), server::zone::objects::creature::buffs::DurationBuffImplementation::readObjectMember(), server::zone::objects::creature::buffs::SpiceBuffImplementation::readObjectMember(), server::zone::objects::creature::buffs::SingleUseBuffImplementation::readObjectMember(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::readObjectMember(), and server::zone::objects::creature::buffs::DelayedBuffImplementation::readObjectMember().
void BuffImplementation::removeAttributeModifiers () virtual
Definition at line 315 of file BuffImplementation.cpp.
References attributeModifiers, and creature.
Referenced by deactivate(), and server::zone::objects::creature::buffs::Buff::removeAttributeModifiers().
void BuffImplementation::removeSkillModifiers () virtual
Definition at line 362 of file BuffImplementation.cpp.
References creature, and skillModifiers.
Referenced by deactivate(), and server::zone::objects::creature::buffs::Buff::removeSkillModifiers().
void BuffImplementation::removeStates () virtual
Definition at line 383 of file BuffImplementation.cpp.
References creature, and states.
Referenced by deactivate(), and server::zone::objects::creature::buffs::Buff::removeStates().
void BuffImplementation::rlock (bool doLock = true) protected
Definition at line 696 of file Buff.cpp.
References _this.
void BuffImplementation::runlock (bool doLock = true) protected
Definition at line 712 of file Buff.cpp.
References _this.
void BuffImplementation::scheduleBuffEvent ()
Definition at line 222 of file BuffImplementation.cpp.
Referenced by server::zone::objects::creature::buffs::Buff::scheduleBuffEvent().
void BuffImplementation::sendDestroyTo (CreatureObject * player) virtual
Definition at line 106 of file BuffImplementation.cpp.
References buffCRC, server::zone::objects::creature::CreatureObject::hasBuff(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by deactivate(), and server::zone::objects::creature::buffs::Buff::sendDestroyTo().
void BuffImplementation::sendTo (CreatureObject * player) virtual
Definition at line 95 of file BuffImplementation.cpp.
References buffCRC, getTimeLeft(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by activate(), and server::zone::objects::creature::buffs::Buff::sendTo().
void BuffImplementation::setAccelerationMultiplierMod (float multiplier)
Definition at line 1109 of file Buff.cpp.
References setSkillModifier().
Referenced by server::zone::objects::creature::buffs::Buff::setAccelerationMultiplierMod().
void BuffImplementation::setAttributeModifier (byte attribute, int value)
Definition at line 1081 of file Buff.cpp.
References attributeModifiers.
Referenced by server::zone::objects::creature::buffs::PerformanceBuffImplementation::activate(), and server::zone::objects::creature::buffs::Buff::setAttributeModifier().
void BuffImplementation::setBuffEventNull ()
Definition at line 102 of file BuffImplementation.cpp.
References buffEvent.
Referenced by server::zone::objects::creature::buffs::Buff::setBuffEventNull().
void BuffImplementation::setEndFlyText (const String & file, const String & aux, byte red, byte green, byte blue)
Definition at line 425 of file BuffImplementation.cpp.
References endFlyAux, endFlyBlue, endFlyFile, endFlyGreen, and endFlyRed.
Referenced by server::zone::objects::creature::buffs::Buff::setEndFlyText().
void BuffImplementation::setEndMessage (StringIdChatParameter & end)
Definition at line 413 of file BuffImplementation.cpp.
References endMessage.
Referenced by server::zone::objects::creature::buffs::Buff::setEndMessage().
void BuffImplementation::setFillAttributesOnBuff (bool val)
Definition at line 1114 of file Buff.cpp.
References fillAttributesOnBuff.
Referenced by server::zone::objects::creature::buffs::Buff::setFillAttributesOnBuff().
void BuffImplementation::setSkillModifier (const String & modname, int value)
Definition at line 1090 of file Buff.cpp.
References skillModifiers.
Referenced by setAccelerationMultiplierMod(), server::zone::objects::creature::buffs::Buff::setSkillModifier(), and setSpeedMultiplierMod().
void BuffImplementation::setSpeedMultiplierMod (float multiplier)
Definition at line 1104 of file Buff.cpp.
References setSkillModifier().
Referenced by server::zone::objects::creature::buffs::Buff::setSpeedMultiplierMod().
void BuffImplementation::setStartFlyText (const String & file, const String & aux, byte red, byte green, byte blue)
Definition at line 417 of file BuffImplementation.cpp.
References startFlyAux, startFlyBlue, startFlyFile, startFlyGreen, and startFlyRed.
Referenced by server::zone::objects::creature::buffs::Buff::setStartFlyText().
void BuffImplementation::setStartMessage (StringIdChatParameter & start)
Definition at line 409 of file BuffImplementation.cpp.
References startMessage.
Referenced by server::zone::objects::creature::buffs::Buff::setStartMessage().
void BuffImplementation::unlock (bool doLock = true) protected
Definition at line 708 of file Buff.cpp.
References _this.
void BuffImplementation::wlock (bool doLock = true) protected
Definition at line 700 of file Buff.cpp.
References _this.
void BuffImplementation::wlock (ManagedObject * obj) protected
Definition at line 704 of file Buff.cpp.
References _this.
void BuffImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented in server::zone::objects::creature::buffs::DelayedBuffImplementation, server::zone::objects::creature::buffs::PowerBoostBuffImplementation, server::zone::objects::creature::buffs::SingleUseBuffImplementation, server::zone::objects::creature::buffs::SpiceBuffImplementation, server::zone::objects::creature::buffs::DurationBuffImplementation, server::zone::objects::creature::buffs::PerformanceBuffImplementation, server::zone::objects::creature::buffs::SpiceDownerBuffImplementation, and server::zone::objects::creature::buffs::StateBuffImplementation.
Definition at line 840 of file Buff.cpp.
References writeObjectMembers().
int BuffImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 847 of file Buff.cpp.
References attributeModifiers, buffCRC, buffDuration, buffName, buffType, creature, endFlyAux, endFlyBlue, endFlyFile, endFlyGreen, endFlyRed, endMessage, fillAttributesOnBuff, nextExecutionTime, skillModifiers, startFlyAux, startFlyBlue, startFlyFile, startFlyGreen, startFlyRed, startMessage, and states.
Referenced by writeObject(), server::zone::objects::creature::buffs::StateBuffImplementation::writeObjectMembers(), server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::writeObjectMembers(), server::zone::objects::creature::buffs::PerformanceBuffImplementation::writeObjectMembers(), server::zone::objects::creature::buffs::DurationBuffImplementation::writeObjectMembers(), server::zone::objects::creature::buffs::SpiceBuffImplementation::writeObjectMembers(), server::zone::objects::creature::buffs::SingleUseBuffImplementation::writeObjectMembers(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::writeObjectMembers(), and server::zone::objects::creature::buffs::DelayedBuffImplementation::writeObjectMembers().
Friends And Related Function Documentation
friend class Buff friend
Definition at line 388 of file Buff.h.
Member Data Documentation
WeakReference<Buff*> server::zone::objects::creature::buffs::BuffImplementation::_this
Definition at line 354 of file Buff.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), activate(), loadBuffDurationEvent(), lock(), rlock(), runlock(), unlock(), and wlock().
VectorMap<byte, int> server::zone::objects::creature::buffs::BuffImplementation::attributeModifiers protected
Definition at line 212 of file Buff.h.
Referenced by applyAttributeModifiers(), getAttributeModifiers(), getAttributeModifierValue(), init(), initializeTransientMembers(), isAttributeBuff(), parseAttributeModifierString(), readObjectMember(), removeAttributeModifiers(), setAttributeModifier(), server::zone::objects::creature::buffs::SpiceBuffImplementation::setDownerAttributes(), and writeObjectMembers().
unsigned int server::zone::objects::creature::buffs::BuffImplementation::buffCRC protected
Definition at line 222 of file Buff.h.
Referenced by BuffImplementation(), getBuffCRC(), readObjectMember(), sendDestroyTo(), sendTo(), and writeObjectMembers().
float server::zone::objects::creature::buffs::BuffImplementation::buffDuration protected
Definition at line 220 of file Buff.h.
Referenced by server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::activate(), activate(), BuffImplementation(), getBuffDuration(), loadBuffDurationEvent(), readObjectMember(), and writeObjectMembers().
Reference<BuffDurationEvent* > server::zone::objects::creature::buffs::BuffImplementation::buffEvent protected
Definition at line 210 of file Buff.h.
Referenced by activate(), clearBuffEvent(), getTimeLeft(), isActive(), loadBuffDurationEvent(), and setBuffEventNull().
String server::zone::objects::creature::buffs::BuffImplementation::buffName protected
Definition at line 218 of file Buff.h.
Referenced by server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::activate(), server::zone::objects::creature::buffs::SpiceBuffImplementation::activate(), server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::deactivate(), server::zone::objects::creature::buffs::SpiceBuffImplementation::deactivate(), getBuffName(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::PowerBoostBuffImplementation(), readObjectMember(), server::zone::objects::creature::buffs::SpiceBuffImplementation::SpiceBuffImplementation(), server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::SpiceDownerBuffImplementation(), and writeObjectMembers().
int server::zone::objects::creature::buffs::BuffImplementation::buffType protected
Definition at line 224 of file Buff.h.
Referenced by BuffImplementation(), getBuffType(), isSpiceBuff(), readObjectMember(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::objects::creature::buffs::BuffImplementation::creature protected
Definition at line 208 of file Buff.h.
Referenced by server::zone::objects::creature::buffs::StateBuffImplementation::activate(), server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::activate(), server::zone::objects::creature::buffs::PerformanceBuffImplementation::activate(), server::zone::objects::creature::buffs::SpiceBuffImplementation::activate(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::activate(), activate(), applyAttributeModifiers(), applySkillModifiers(), applyStates(), BuffImplementation(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::clearBuffEvent(), server::zone::objects::creature::buffs::StateBuffImplementation::deactivate(), server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::deactivate(), server::zone::objects::creature::buffs::SpiceBuffImplementation::deactivate(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::deactivate(), deactivate(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::doHealthAndActionTick(), server::zone::objects::creature::buffs::PowerBoostBuffImplementation::doMindTick(), readObjectMember(), removeAttributeModifiers(), removeSkillModifiers(), removeStates(), and writeObjectMembers().
String server::zone::objects::creature::buffs::BuffImplementation::endFlyAux protected
Definition at line 244 of file Buff.h.
Referenced by deactivate(), readObjectMember(), setEndFlyText(), and writeObjectMembers().
byte server::zone::objects::creature::buffs::BuffImplementation::endFlyBlue protected
Definition at line 250 of file Buff.h.
Referenced by deactivate(), readObjectMember(), setEndFlyText(), and writeObjectMembers().
String server::zone::objects::creature::buffs::BuffImplementation::endFlyFile protected
Definition at line 242 of file Buff.h.
Referenced by BuffImplementation(), deactivate(), readObjectMember(), setEndFlyText(), and writeObjectMembers().
byte server::zone::objects::creature::buffs::BuffImplementation::endFlyGreen protected
Definition at line 248 of file Buff.h.
Referenced by deactivate(), readObjectMember(), setEndFlyText(), and writeObjectMembers().
byte server::zone::objects::creature::buffs::BuffImplementation::endFlyRed protected
Definition at line 246 of file Buff.h.
Referenced by deactivate(), readObjectMember(), setEndFlyText(), and writeObjectMembers().
StringIdChatParameter server::zone::objects::creature::buffs::BuffImplementation::endMessage protected
Definition at line 230 of file Buff.h.
Referenced by deactivate(), readObjectMember(), setEndMessage(), and writeObjectMembers().
bool server::zone::objects::creature::buffs::BuffImplementation::fillAttributesOnBuff protected
Definition at line 226 of file Buff.h.
Referenced by applyAttributeModifiers(), BuffImplementation(), readObjectMember(), setFillAttributesOnBuff(), and writeObjectMembers().
Time server::zone::objects::creature::buffs::BuffImplementation::nextExecutionTime protected
Definition at line 252 of file Buff.h.
Referenced by activate(), clearBuffEvent(), loadBuffDurationEvent(), readObjectMember(), and writeObjectMembers().
VectorMap<String, int> server::zone::objects::creature::buffs::BuffImplementation::skillModifiers protected
Definition at line 214 of file Buff.h.
Referenced by applySkillModifiers(), getSkillModifiers(), getSkillModifierValue(), init(), initializeTransientMembers(), parseSkillModifierString(), readObjectMember(), removeSkillModifiers(), setSkillModifier(), and writeObjectMembers().
String server::zone::objects::creature::buffs::BuffImplementation::startFlyAux protected
Definition at line 234 of file Buff.h.
Referenced by activate(), readObjectMember(), setStartFlyText(), and writeObjectMembers().
byte server::zone::objects::creature::buffs::BuffImplementation::startFlyBlue protected
Definition at line 240 of file Buff.h.
Referenced by activate(), readObjectMember(), setStartFlyText(), and writeObjectMembers().
String server::zone::objects::creature::buffs::BuffImplementation::startFlyFile protected
Definition at line 232 of file Buff.h.
Referenced by activate(), BuffImplementation(), readObjectMember(), setStartFlyText(), and writeObjectMembers().
byte server::zone::objects::creature::buffs::BuffImplementation::startFlyGreen protected
Definition at line 238 of file Buff.h.
Referenced by activate(), readObjectMember(), setStartFlyText(), and writeObjectMembers().
byte server::zone::objects::creature::buffs::BuffImplementation::startFlyRed protected
Definition at line 236 of file Buff.h.
Referenced by activate(), readObjectMember(), setStartFlyText(), and writeObjectMembers().
StringIdChatParameter server::zone::objects::creature::buffs::BuffImplementation::startMessage protected
Definition at line 228 of file Buff.h.
Referenced by activate(), readObjectMember(), setStartMessage(), and writeObjectMembers().
Vector<unsigned long long> server::zone::objects::creature::buffs::BuffImplementation::states protected
Definition at line 216 of file Buff.h.
Referenced by addState(), applyStates(), readObjectMember(), removeStates(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/Buff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/Buff.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/BuffImplementation.cpp