Core3: server::zone::objects::area::SpawnAreaImplementation Class Reference
server::zone::objects::area::SpawnAreaImplementation Class Reference
#include <SpawnArea.h>
Public Member Functions
SpawnAreaImplementation ()
SpawnAreaImplementation (DummyConstructorParameter *param)
virtual void registerObservers ()
Vector3 getRandomPosition (SceneObject *player)
virtual int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addTemplate (unsigned int tempCRC)
void setTier (int n)
void setSpawnConstant (int n)
void addNoSpawnArea (SpawnArea *area)
virtual bool isStaticArea ()
virtual bool isDynamicArea ()
virtual bool isLairSpawnArea ()
operator const SpawnArea * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::area::ActiveAreaImplementation
ActiveAreaImplementation ()
ActiveAreaImplementation (DummyConstructorParameter *param)
void sendTo (SceneObject *player, bool doClose)
virtual void enqueueEnterEvent (SceneObject *obj)
virtual void enqueueExitEvent (SceneObject *obj)
virtual void notifyEnter (SceneObject *object)
virtual void notifyExit (SceneObject *object)
bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCityRegion ()
bool isNoBuildArea ()
bool isCampingPermitted ()
bool containsPoint (float x, float y)
float getRadius2 ()
void setNoBuildArea (bool val)
void setCampingPermitted (bool val)
void setMunicipalZone (bool val)
void setRadius (float r)
virtual bool isCampArea ()
void setNoSpawnArea (bool val)
bool isNoSpawnArea ()
bool isMunicipalZone ()
unsigned long long getCellObjectID ()
void setCellObjectID (unsigned long long celloid)
void setAreaShape (AreaShape *area)
AreaShape * getAreaShape ()
bool intersectsWith (ActiveArea *area)
operator const ActiveArea * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void loadTemplateData (SharedObjectTemplate *templateData)
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendBaselinesTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
virtual void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
virtual void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
virtual int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isTangibleObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
virtual void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< SpawnArea * > _this
Public Attributes inherited from server::zone::objects::area::ActiveAreaImplementation
WeakReference< ActiveArea * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Protected Member Functions
virtual ~SpawnAreaImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::area::ActiveAreaImplementation
virtual ~ActiveAreaImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
SortedVector< unsigned int > spawnCreatureTemplates
SortedVector< ManagedReference
< SpawnObserver * > > observers
Vector< ManagedReference
< SpawnArea * > > noSpawnAreas
int tier
int spawnConstant
Protected Attributes inherited from server::zone::objects::area::ActiveAreaImplementation
bool noBuildArea
bool campingPermitted
bool municipalZone
unsigned long long cellObjectID
bool noSpawnArea
ManagedReference< AreaShape * > areaShape
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Friends
class SpawnArea
Detailed Description
Definition at line 120 of file SpawnArea.h.
Constructor & Destructor Documentation
SpawnAreaImplementation::SpawnAreaImplementation ()
Definition at line 361 of file SpawnArea.cpp.
References _initializeImplementation(), and spawnConstant.
SpawnAreaImplementation::SpawnAreaImplementation (DummyConstructorParameter * param)
Definition at line 187 of file SpawnArea.cpp.
References _initializeImplementation().
SpawnAreaImplementation::~SpawnAreaImplementation () protected virtual
Definition at line 192 of file SpawnArea.cpp.
Member Function Documentation
DistributedObjectStub * SpawnAreaImplementation::_getStub ()
Definition at line 212 of file SpawnArea.cpp.
References _this.
void SpawnAreaImplementation::_initializeImplementation () protected
Definition at line 199 of file SpawnArea.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SpawnAreaImplementation().
void SpawnAreaImplementation::_serializationHelperMethod () protected
Definition at line 248 of file SpawnArea.cpp.
References server::zone::objects::area::ActiveAreaImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation(), server::zone::objects::area::StaticSpawnAreaImplementation::_serializationHelperMethod(), server::zone::objects::area::LairSpawnAreaImplementation::_serializationHelperMethod(), and server::zone::objects::area::DynamicSpawnAreaImplementation::_serializationHelperMethod().
void SpawnAreaImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 207 of file SpawnArea.cpp.
References server::zone::objects::area::ActiveAreaImplementation::_setStub(), and _this.
Referenced by server::zone::objects::area::StaticSpawnAreaImplementation::_setStub(), server::zone::objects::area::LairSpawnAreaImplementation::_setStub(), server::zone::objects::area::DynamicSpawnAreaImplementation::_setStub(), and server::zone::objects::area::SpawnArea::SpawnArea().
void SpawnAreaImplementation::addNoSpawnArea (SpawnArea * area)
Definition at line 392 of file SpawnArea.cpp.
References noSpawnAreas.
Referenced by server::zone::objects::area::SpawnArea::addNoSpawnArea().
void SpawnAreaImplementation::addTemplate (unsigned int tempCRC)
Definition at line 377 of file SpawnArea.cpp.
References spawnCreatureTemplates.
Referenced by server::zone::objects::area::SpawnArea::addTemplate().
void SpawnAreaImplementation::finalize () protected
Definition at line 196 of file SpawnArea.cpp.
Vector3 SpawnAreaImplementation::getRandomPosition (SceneObject * player)
Definition at line 12 of file SpawnAreaImplementation.cpp.
References server::zone::objects::area::ActiveAreaImplementation::areaShape, server::zone::objects::area::ActiveArea::containsPoint(), server::zone::Zone::getBoundingRadius(), server::zone::objects::scene::SceneObject::getWorldPosition(), server::zone::objects::scene::SceneObjectImplementation::getZone(), server::zone::objects::area::ActiveAreaImplementation::noSpawnArea, and noSpawnAreas.
Referenced by server::zone::objects::area::SpawnArea::getRandomPosition(), and server::zone::objects::area::LairSpawnAreaImplementation::trySpawnLair().
bool SpawnAreaImplementation::isDynamicArea () virtual
Reimplemented in server::zone::objects::area::DynamicSpawnAreaImplementation.
Definition at line 402 of file SpawnArea.cpp.
Referenced by server::zone::objects::area::SpawnArea::isDynamicArea().
bool SpawnAreaImplementation::isLairSpawnArea () virtual
Reimplemented in server::zone::objects::area::LairSpawnAreaImplementation.
Definition at line 407 of file SpawnArea.cpp.
Referenced by server::zone::objects::area::SpawnArea::isLairSpawnArea().
bool SpawnAreaImplementation::isStaticArea () virtual
Reimplemented in server::zone::objects::area::StaticSpawnAreaImplementation.
Definition at line 397 of file SpawnArea.cpp.
Referenced by server::zone::objects::area::SpawnArea::isStaticArea().
void SpawnAreaImplementation::lock (bool doLock = true) protected
Definition at line 220 of file SpawnArea.cpp.
References _this.
void SpawnAreaImplementation::lock (ManagedObject * obj) protected
Definition at line 224 of file SpawnArea.cpp.
References _this.
int SpawnAreaImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2) virtual
Reimplemented in server::zone::objects::area::DynamicSpawnAreaImplementation, and server::zone::objects::area::LairSpawnAreaImplementation.
Definition at line 372 of file SpawnArea.cpp.
Referenced by server::zone::objects::area::SpawnArea::notifyObserverEvent().
SpawnAreaImplementation::operator const SpawnArea * ()
Definition at line 216 of file SpawnArea.cpp.
void SpawnAreaImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::area::ActiveAreaImplementation.
Reimplemented in server::zone::objects::area::DynamicSpawnAreaImplementation, server::zone::objects::area::LairSpawnAreaImplementation, and server::zone::objects::area::StaticSpawnAreaImplementation.
Definition at line 255 of file SpawnArea.cpp.
References server::zone::objects::scene::SceneObjectImplementation::initializeTransientMembers(), and readObjectMember().
bool SpawnAreaImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 274 of file SpawnArea.cpp.
References noSpawnAreas, observers, server::zone::objects::area::ActiveAreaImplementation::readObjectMember(), spawnConstant, spawnCreatureTemplates, and tier.
Referenced by readObject(), server::zone::objects::area::StaticSpawnAreaImplementation::readObjectMember(), server::zone::objects::area::LairSpawnAreaImplementation::readObjectMember(), and server::zone::objects::area::DynamicSpawnAreaImplementation::readObjectMember().
void SpawnAreaImplementation::registerObservers () virtual
Reimplemented in server::zone::objects::area::DynamicSpawnAreaImplementation.
Definition at line 369 of file SpawnArea.cpp.
Referenced by server::zone::objects::area::SpawnArea::registerObservers().
void SpawnAreaImplementation::rlock (bool doLock = true) protected
Definition at line 228 of file SpawnArea.cpp.
References _this.
void SpawnAreaImplementation::runlock (bool doLock = true) protected
Definition at line 244 of file SpawnArea.cpp.
References _this.
void SpawnAreaImplementation::setSpawnConstant (int n)
Definition at line 387 of file SpawnArea.cpp.
References spawnConstant.
Referenced by server::zone::objects::area::SpawnArea::setSpawnConstant().
void SpawnAreaImplementation::setTier (int n)
Definition at line 382 of file SpawnArea.cpp.
References tier.
Referenced by server::zone::objects::area::SpawnArea::setTier().
void SpawnAreaImplementation::unlock (bool doLock = true) protected
Definition at line 240 of file SpawnArea.cpp.
References _this.
void SpawnAreaImplementation::wlock (bool doLock = true) protected
Definition at line 232 of file SpawnArea.cpp.
References _this.
void SpawnAreaImplementation::wlock (ManagedObject * obj) protected
Definition at line 236 of file SpawnArea.cpp.
References _this.
void SpawnAreaImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::area::ActiveAreaImplementation.
Reimplemented in server::zone::objects::area::DynamicSpawnAreaImplementation, server::zone::objects::area::LairSpawnAreaImplementation, and server::zone::objects::area::StaticSpawnAreaImplementation.
Definition at line 304 of file SpawnArea.cpp.
References writeObjectMembers().
int SpawnAreaImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 311 of file SpawnArea.cpp.
References noSpawnAreas, observers, spawnConstant, spawnCreatureTemplates, tier, and server::zone::objects::area::ActiveAreaImplementation::writeObjectMembers().
Referenced by writeObject(), server::zone::objects::area::StaticSpawnAreaImplementation::writeObjectMembers(), server::zone::objects::area::LairSpawnAreaImplementation::writeObjectMembers(), and server::zone::objects::area::DynamicSpawnAreaImplementation::writeObjectMembers().
Friends And Related Function Documentation
friend class SpawnArea friend
Definition at line 191 of file SpawnArea.h.
Member Data Documentation
WeakReference<SpawnArea*> server::zone::objects::area::SpawnAreaImplementation::_this
Definition at line 157 of file SpawnArea.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
Vector<ManagedReference<SpawnArea* > > server::zone::objects::area::SpawnAreaImplementation::noSpawnAreas protected
Definition at line 126 of file SpawnArea.h.
Referenced by addNoSpawnArea(), getRandomPosition(), server::zone::objects::area::DynamicSpawnAreaImplementation::getRandomPosition(), readObjectMember(), server::zone::objects::area::DynamicSpawnAreaImplementation::registerObservers(), and writeObjectMembers().
SortedVector<ManagedReference<SpawnObserver* > > server::zone::objects::area::SpawnAreaImplementation::observers protected
Definition at line 124 of file SpawnArea.h.
Referenced by readObjectMember(), and writeObjectMembers().
int server::zone::objects::area::SpawnAreaImplementation::spawnConstant protected
Definition at line 130 of file SpawnArea.h.
Referenced by readObjectMember(), setSpawnConstant(), SpawnAreaImplementation(), and writeObjectMembers().
SortedVector<unsigned int> server::zone::objects::area::SpawnAreaImplementation::spawnCreatureTemplates protected
Definition at line 122 of file SpawnArea.h.
Referenced by addTemplate(), server::zone::objects::area::DynamicSpawnAreaImplementation::doSpawnEvent(), server::zone::objects::area::LairSpawnAreaImplementation::getSpawnGroup(), readObjectMember(), server::zone::objects::area::StaticSpawnAreaImplementation::spawnCreatures(), server::zone::objects::area::LairSpawnAreaImplementation::trySpawnLair(), and writeObjectMembers().
int server::zone::objects::area::SpawnAreaImplementation::tier protected
Definition at line 128 of file SpawnArea.h.
Referenced by readObjectMember(), setTier(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/SpawnArea.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/SpawnArea.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/SpawnAreaImplementation.cpp