Core3: CreatureAttackMap Class Reference
CreatureAttackMap Class Reference
#include <CreatureAttackMap.h>
Public Member Functions
CreatureAttackMap ()
virtual ~CreatureAttackMap ()
void addAttack (String c, String a)
String getCommand (int i)
String getArguments (int i)
int getRandomAttackNumber ()
Detailed Description
Definition at line 39 of file CreatureAttackMap.h.
Constructor & Destructor Documentation
CreatureAttackMap::CreatureAttackMap () inline
Definition at line 41 of file CreatureAttackMap.h.
virtual CreatureAttackMap::~CreatureAttackMap () inline virtual
Definition at line 42 of file CreatureAttackMap.h.
Member Function Documentation
void CreatureAttackMap::addAttack (String c, String a) inline
Definition at line 44 of file CreatureAttackMap.h.
References CreatureAttack::setArguments(), and CreatureAttack::setCommand().
Referenced by server::zone::templates::mobile::CreatureTemplate::readObject().
String CreatureAttackMap::getArguments (int i) inline
Definition at line 55 of file CreatureAttackMap.h.
Referenced by server::zone::objects::creature::AiAgentImplementation::doAttack(), and AttackStateComponent::doRecovery().
String CreatureAttackMap::getCommand (int i) inline
Definition at line 51 of file CreatureAttackMap.h.
Referenced by server::zone::objects::creature::AiAgentImplementation::doAttack(), AttackStateComponent::doRecovery(), server::zone::objects::creature::CreatureImplementation::fillAttributeList(), and server::zone::managers::creature::DnaManager::generateSample().
int CreatureAttackMap::getRandomAttackNumber () inline
Definition at line 59 of file CreatureAttackMap.h.
Referenced by server::zone::objects::creature::AiAgentImplementation::doAttack(), and AttackStateComponent::doRecovery().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/variables/CreatureAttackMap.h