Core3: server::zone::managers::name::NameManager Class Reference
server::zone::managers::name::NameManager Class Reference
#include <NameManager.h>
Public Member Functions
NameManager ()
NameManager (ZoneProcessServer *serv)
~NameManager ()
void test ()
bool isProfane (String name)
int validateName (CreatureObject *obj)
int validateName (const String &name, int species=0)
const String makeCreatureName (bool surname=true)
const String makeResourceName (bool isOrganic)
Private Member Functions
void initialize ()
bool loadConfigFile ()
bool loadConfigData ()
void loadDefaultConfig ()
void fillNames ()
char chooseNextLetter (const char, const char)
bool isReserved (String)
bool isDeveloper (String)
bool isFiction (String)
bool isVowel (const char)
void addPrefix (String &name, bool isOrganic)
void addSuffix (String &name, bool isOrganic)
char chooseLetterInclusive (String include)
String makeName (int nameLength)
Private Attributes
ManagedReference
< ZoneProcessServer * > server
Lua * lua
Vector< String > * profaneNames
BannedNameSet * developerNames
BannedNameSet * fictionNames
BannedNameSet * reservedNames
VectorMap< String, String > letterMappings
Vector< String > organicPrefixes
Vector< String > organicSuffixes
Vector< String > inorganicPrefixes
Vector< String > inorganicSuffixes
Vector< String > npcFirstNames
Vector< String > npcSurnames
Detailed Description
Definition at line 103 of file NameManager.h.
Constructor & Destructor Documentation
NameManager::NameManager ()
Definition at line 53 of file NameManager.cpp.
References developerNames, fictionNames, fillNames(), initialize(), profaneNames, and reservedNames.
NameManager::NameManager (ZoneProcessServer * serv)
Definition at line 66 of file NameManager.cpp.
References developerNames, fictionNames, fillNames(), initialize(), profaneNames, reservedNames, and server.
NameManager::~NameManager ()
Definition at line 82 of file NameManager.cpp.
References developerNames, fictionNames, lua, profaneNames, and reservedNames.
Member Function Documentation
void NameManager::addPrefix (String & name, bool isOrganic) inline private
Definition at line 445 of file NameManager.cpp.
References inorganicPrefixes, and organicPrefixes.
Referenced by makeResourceName().
void NameManager::addSuffix (String & name, bool isOrganic) inline private
Definition at line 454 of file NameManager.cpp.
References inorganicSuffixes, and organicSuffixes.
Referenced by makeResourceName().
char NameManager::chooseLetterInclusive (String include) private
Definition at line 440 of file NameManager.cpp.
Referenced by chooseNextLetter().
char NameManager::chooseNextLetter (const char lastLetter, const char letterBeforeLast) private
Definition at line 402 of file NameManager.cpp.
References chooseLetterInclusive(), isVowel(), and letterMappings.
Referenced by makeName(), and makeResourceName().
void NameManager::fillNames () private
Definition at line 191 of file NameManager.cpp.
References developerNames, fictionNames, profaneNames, and reservedNames.
Referenced by NameManager().
void NameManager::initialize () private
Definition at line 92 of file NameManager.cpp.
References loadConfigData(), loadDefaultConfig(), and lua.
Referenced by NameManager().
bool NameManager::isDeveloper (String name) inline private
Definition at line 253 of file NameManager.cpp.
References developerNames.
Referenced by validateName().
bool NameManager::isFiction (String name) inline private
Definition at line 257 of file NameManager.cpp.
References fictionNames.
Referenced by validateName().
bool NameManager::isProfane (String name)
Definition at line 240 of file NameManager.cpp.
References profaneNames.
Referenced by NameStructureCommand::doQueueCommand(), RenameCitySuiCallback::run(), PlaceCityHallSuiCallback::run(), and validateName().
bool NameManager::isReserved (String name) inline private
Definition at line 261 of file NameManager.cpp.
References reservedNames.
Referenced by validateName().
bool NameManager::isVowel (const char inChar) inline private
Definition at line 432 of file NameManager.cpp.
Referenced by chooseNextLetter(), and makeResourceName().
bool NameManager::loadConfigData () private
Definition at line 112 of file NameManager.cpp.
References inorganicPrefixes, inorganicSuffixes, letterMappings, loadConfigFile(), lua, npcFirstNames, npcSurnames, and organicPrefixes.
Referenced by initialize().
bool NameManager::loadConfigFile () private
Definition at line 108 of file NameManager.cpp.
References lua.
Referenced by loadConfigData().
void NameManager::loadDefaultConfig () private
Definition at line 186 of file NameManager.cpp.
Referenced by initialize().
const String NameManager::makeCreatureName (bool surname = true)
Definition at line 337 of file NameManager.cpp.
References makeName().
Referenced by server::zone::managers::mission::spawnmaps::NpcSpawnPoint::allocateNpc(), server::zone::managers::director::DirectorManager::makeCreatureName(), server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission(), ClientRandomNameRequest::run(), and test().
String NameManager::makeName (int nameLength) private
Get first 2 letters
Definition at line 349 of file NameManager.cpp.
References NameManagerResult::ACCEPTED, chooseNextLetter(), and validateName().
Referenced by makeCreatureName().
const String NameManager::makeResourceName (bool isOrganic)
Definition at line 371 of file NameManager.cpp.
References NameManagerResult::ACCEPTED, addPrefix(), addSuffix(), chooseNextLetter(), isVowel(), and validateName().
Referenced by ResourceSpawner::makeResourceName(), and test().
void NameManager::test ()
Definition at line 464 of file NameManager.cpp.
References makeCreatureName(), and makeResourceName().
int NameManager::validateName (CreatureObject * obj)
Definition at line 265 of file NameManager.cpp.
References server::zone::objects::scene::SceneObject::getCustomObjectName(), server::zone::objects::scene::SceneObject::getObjectName(), and server::zone::objects::creature::CreatureObject::getSpecies().
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkPlayerName(), makeName(), makeResourceName(), server::zone::managers::guild::GuildManagerImplementation::setMemberTitle(), server::zone::managers::guild::GuildManagerImplementation::validateGuildAbbrev(), and server::zone::managers::guild::GuildManagerImplementation::validateGuildName().
int NameManager::validateName (const String & name, int species = 0)
Definition at line 273 of file NameManager.cpp.
References NameManagerResult::ACCEPTED, NameManagerResult::DECLINED_DEVELOPER, NameManagerResult::DECLINED_EMPTY, NameManagerResult::DECLINED_FICT_RESERVED, NameManagerResult::DECLINED_PROFANE, NameManagerResult::DECLINED_RACE_INAPP, NameManagerResult::DECLINED_RESERVED, NameManagerResult::DECLINED_SYNTAX, isDeveloper(), isFiction(), isProfane(), and isReserved().
Member Data Documentation
BannedNameSet* server::zone::managers::name::NameManager::developerNames private
Definition at line 109 of file NameManager.h.
Referenced by fillNames(), isDeveloper(), NameManager(), and ~NameManager().
BannedNameSet* server::zone::managers::name::NameManager::fictionNames private
Definition at line 110 of file NameManager.h.
Referenced by fillNames(), isFiction(), NameManager(), and ~NameManager().
Vector<String> server::zone::managers::name::NameManager::inorganicPrefixes private
Definition at line 118 of file NameManager.h.
Referenced by addPrefix(), and loadConfigData().
Vector<String> server::zone::managers::name::NameManager::inorganicSuffixes private
Definition at line 119 of file NameManager.h.
Referenced by addSuffix(), and loadConfigData().
VectorMap<String, String> server::zone::managers::name::NameManager::letterMappings private
Definition at line 113 of file NameManager.h.
Referenced by chooseNextLetter(), and loadConfigData().
Lua* server::zone::managers::name::NameManager::lua private
Definition at line 106 of file NameManager.h.
Referenced by initialize(), loadConfigData(), loadConfigFile(), and ~NameManager().
Vector<String> server::zone::managers::name::NameManager::npcFirstNames private
Definition at line 121 of file NameManager.h.
Referenced by loadConfigData().
Vector<String> server::zone::managers::name::NameManager::npcSurnames private
Definition at line 122 of file NameManager.h.
Referenced by loadConfigData().
Vector<String> server::zone::managers::name::NameManager::organicPrefixes private
Definition at line 115 of file NameManager.h.
Referenced by addPrefix(), and loadConfigData().
Vector<String> server::zone::managers::name::NameManager::organicSuffixes private
Definition at line 116 of file NameManager.h.
Referenced by addSuffix().
Vector<String>* server::zone::managers::name::NameManager::profaneNames private
Definition at line 108 of file NameManager.h.
Referenced by fillNames(), isProfane(), NameManager(), and ~NameManager().
BannedNameSet* server::zone::managers::name::NameManager::reservedNames private
Definition at line 111 of file NameManager.h.
Referenced by fillNames(), isReserved(), NameManager(), and ~NameManager().
ManagedReference<ZoneProcessServer*> server::zone::managers::name::NameManager::server private
Definition at line 104 of file NameManager.h.
Referenced by NameManager().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/name/NameManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/name/NameManager.cpp