Core3: server::chat::room::ChatRoomAdapter Class Reference
server::chat::room::ChatRoomAdapter Class Reference
#include <ChatRoom.h>
Public Member Functions
ChatRoomAdapter (ChatRoom *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void init (ZoneServer *serv, ChatRoom *par, const String &roomName, unsigned int channelID)
void sendTo (CreatureObject *player)
void sendDestroyTo (CreatureObject *player)
void addSubRoom (ChatRoom *channel)
void removeSubRoom (ChatRoom *channel)
ChatRoom * getSubRoom (int i)
ChatRoom * getSubRoom (const String &name)
void addPlayer (CreatureObject *player, bool doLock)
void removePlayer (CreatureObject *player, bool doLock)
void removePlayer (const String &player)
void broadcastMessage (BaseMessage *msg)
bool hasPlayer (CreatureObject *player)
bool hasPlayer (const String &name)
void removeAllPlayers ()
void setPrivate ()
void setPublic ()
bool isPublic ()
bool isPrivate ()
bool isModerated ()
void setModerated (bool moderate)
CreatureObject * getPlayer (int idx)
int getPlayerSize ()
void setName (const String &Name)
String getName ()
String getFullPath ()
String getOwner ()
String getCreator ()
UnicodeString getTitle ()
String getGalaxyName ()
void setOwner (const String &Owner)
void setCreator (const String &Creator)
void setTitle (const String &Title)
void setRoomID (int id)
unsigned int getRoomID ()
int getSubRoomsSize ()
ChatRoom * getParent ()
int compareTo (ChatRoom *obj)
Detailed Description
Definition at line 327 of file ChatRoom.h.
Constructor & Destructor Documentation
ChatRoomAdapter::ChatRoomAdapter (ChatRoom * impl)
Definition at line 1122 of file ChatRoom.cpp.
Member Function Documentation
void ChatRoomAdapter::addPlayer (CreatureObject * player, bool doLock)
Definition at line 1355 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::addSubRoom (ChatRoom * channel)
Definition at line 1339 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::broadcastMessage (BaseMessage * msg)
Definition at line 1367 of file ChatRoom.cpp.
Referenced by invokeMethod().
int ChatRoomAdapter::compareTo (ChatRoom * obj)
Definition at line 1471 of file ChatRoom.cpp.
Referenced by invokeMethod().
String ChatRoomAdapter::getCreator ()
Definition at line 1431 of file ChatRoom.cpp.
Referenced by invokeMethod().
String ChatRoomAdapter::getFullPath ()
Definition at line 1423 of file ChatRoom.cpp.
Referenced by invokeMethod().
String ChatRoomAdapter::getGalaxyName ()
Definition at line 1439 of file ChatRoom.cpp.
Referenced by invokeMethod().
String ChatRoomAdapter::getName ()
Definition at line 1419 of file ChatRoom.cpp.
Referenced by invokeMethod().
String ChatRoomAdapter::getOwner ()
Definition at line 1427 of file ChatRoom.cpp.
Referenced by invokeMethod().
ChatRoom * ChatRoomAdapter::getParent ()
Definition at line 1467 of file ChatRoom.cpp.
References server::chat::room::ChatRoom::getParent().
Referenced by invokeMethod().
CreatureObject * ChatRoomAdapter::getPlayer (int idx)
Definition at line 1407 of file ChatRoom.cpp.
Referenced by invokeMethod().
int ChatRoomAdapter::getPlayerSize ()
Definition at line 1411 of file ChatRoom.cpp.
Referenced by invokeMethod().
unsigned int ChatRoomAdapter::getRoomID ()
Definition at line 1459 of file ChatRoom.cpp.
Referenced by invokeMethod().
ChatRoom * ChatRoomAdapter::getSubRoom (int i)
Definition at line 1347 of file ChatRoom.cpp.
References server::chat::room::ChatRoom::getSubRoom().
Referenced by invokeMethod().
ChatRoom * ChatRoomAdapter::getSubRoom (const String & name)
Definition at line 1351 of file ChatRoom.cpp.
References server::chat::room::ChatRoom::getSubRoom().
int ChatRoomAdapter::getSubRoomsSize ()
Definition at line 1463 of file ChatRoom.cpp.
Referenced by invokeMethod().
UnicodeString ChatRoomAdapter::getTitle ()
Definition at line 1435 of file ChatRoom.cpp.
Referenced by invokeMethod().
bool ChatRoomAdapter::hasPlayer (CreatureObject * player)
Definition at line 1371 of file ChatRoom.cpp.
Referenced by invokeMethod().
bool ChatRoomAdapter::hasPlayer (const String & name)
Definition at line 1375 of file ChatRoom.cpp.
void ChatRoomAdapter::init (ZoneServer * serv, ChatRoom * par, const String & roomName, unsigned int channelID)
Definition at line 1327 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1125 of file ChatRoom.cpp.
References addPlayer(), addSubRoom(), broadcastMessage(), compareTo(), getCreator(), getFullPath(), getGalaxyName(), getName(), getOwner(), getParent(), getPlayer(), getPlayerSize(), getRoomID(), getSubRoom(), getSubRoomsSize(), getTitle(), hasPlayer(), init(), isModerated(), isPrivate(), isPublic(), removeAllPlayers(), removePlayer(), removeSubRoom(), RPC_ADDPLAYER__CREATUREOBJECT_BOOL_, RPC_ADDSUBROOM__CHATROOM_, RPC_BROADCASTMESSAGE__BASEMESSAGE_, RPC_COMPARETO__CHATROOM_, RPC_GETCREATOR__, RPC_GETFULLPATH__, RPC_GETGALAXYNAME__, RPC_GETNAME__, RPC_GETOWNER__, RPC_GETPARENT__, RPC_GETPLAYER__INT_, RPC_GETPLAYERSIZE__, RPC_GETROOMID__, RPC_GETSUBROOM__INT_, RPC_GETSUBROOM__STRING_, RPC_GETSUBROOMSSIZE__, RPC_GETTITLE__, RPC_HASPLAYER__CREATUREOBJECT_, RPC_HASPLAYER__STRING_, RPC_INIT__ZONESERVER_CHATROOM_STRING_INT_, RPC_ISMODERATED__, RPC_ISPRIVATE__, RPC_ISPUBLIC__, RPC_REMOVEALLPLAYERS__, RPC_REMOVEPLAYER__CREATUREOBJECT_BOOL_, RPC_REMOVEPLAYER__STRING_, RPC_REMOVESUBROOM__CHATROOM_, RPC_SENDDESTROYTO__CREATUREOBJECT_, RPC_SENDTO__CREATUREOBJECT_, RPC_SETCREATOR__STRING_, RPC_SETMODERATED__BOOL_, RPC_SETNAME__STRING_, RPC_SETOWNER__STRING_, RPC_SETPRIVATE__, RPC_SETPUBLIC__, RPC_SETROOMID__INT_, RPC_SETTITLE__STRING_, sendDestroyTo(), sendTo(), setCreator(), setModerated(), setName(), setOwner(), setPrivate(), setPublic(), setRoomID(), and setTitle().
bool ChatRoomAdapter::isModerated ()
Definition at line 1399 of file ChatRoom.cpp.
Referenced by invokeMethod().
bool ChatRoomAdapter::isPrivate ()
Definition at line 1395 of file ChatRoom.cpp.
Referenced by invokeMethod().
bool ChatRoomAdapter::isPublic ()
Definition at line 1391 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::removeAllPlayers ()
Definition at line 1379 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::removePlayer (CreatureObject * player, bool doLock)
Definition at line 1359 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::removePlayer (const String & player)
Definition at line 1363 of file ChatRoom.cpp.
void ChatRoomAdapter::removeSubRoom (ChatRoom * channel)
Definition at line 1343 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::sendDestroyTo (CreatureObject * player)
Definition at line 1335 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::sendTo (CreatureObject * player)
Definition at line 1331 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::setCreator (const String & Creator)
Definition at line 1447 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::setModerated (bool moderate)
Definition at line 1403 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::setName (const String & Name)
Definition at line 1415 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::setOwner (const String & Owner)
Definition at line 1443 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::setPrivate ()
Definition at line 1383 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::setPublic ()
Definition at line 1387 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::setRoomID (int id)
Definition at line 1455 of file ChatRoom.cpp.
Referenced by invokeMethod().
void ChatRoomAdapter::setTitle (const String & Title)
Definition at line 1451 of file ChatRoom.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/room/ChatRoom.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/room/ChatRoom.cpp