Core3: CloningRequestSuiCallback Class Reference
CloningRequestSuiCallback Class Reference
#include <CloningRequestSuiCallback.h>
Public Member Functions
CloningRequestSuiCallback (ZoneServer *server, int tod)
void run (CreatureObject *player, SuiBox *suiBox, bool cancelPressed, Vector< UnicodeString > *args)
Public Member Functions inherited from server::zone::objects::player::sui::SuiCallback
SuiCallback (ZoneServer *serv)
Private Attributes
int typeofdeath
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::player::sui::SuiCallback
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 19 of file CloningRequestSuiCallback.h.
Constructor & Destructor Documentation
CloningRequestSuiCallback::CloningRequestSuiCallback (ZoneServer * server, int tod) inline
Definition at line 23 of file CloningRequestSuiCallback.h.
References typeofdeath.
Member Function Documentation
void CloningRequestSuiCallback::run (CreatureObject * player, SuiBox * suiBox, bool cancelPressed, Vector< UnicodeString > * args) inline virtual
Parameters
player The player that this suibox is assigned to.
suiBox The actual SuiBox object.
cancelPressed Was the cancel button pressed, or was the sui box closed via a similar method. (this might actually be more of a dialogResult type variable)
args A vector of UnicodeStrings containing the arguments passed to the sui box from the client.
Implements server::zone::objects::player::sui::SuiCallback.
Definition at line 29 of file CloningRequestSuiCallback.h.
References server::zone::objects::player::sui::listbox::SuiListBox::getMenuObjectID(), server::zone::objects::player::sui::listbox::SuiListBox::getMenuSize(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::player::sui::SuiBox::isListBox(), server::zone::managers::player::PlayerManager::sendPlayerToCloner(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::player::sui::SuiCallback::server, and typeofdeath.
Member Data Documentation
int CloningRequestSuiCallback::typeofdeath private
Definition at line 20 of file CloningRequestSuiCallback.h.
Referenced by CloningRequestSuiCallback(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/callbacks/CloningRequestSuiCallback.h