Core3: FactionRanks Class Reference
FactionRanks Class Reference
#include <FactionRanks.h>
Public Member Functions
FactionRanks ()
FactionRanks (const FactionRanks &f)
void readObject (DataTableIff *table)
FactionRank & getRank (int index)
int getCount ()
Protected Attributes
Vector< FactionRank > ranks
Detailed Description
Definition at line 15 of file FactionRanks.h.
Constructor & Destructor Documentation
FactionRanks::FactionRanks ()
Definition at line 11 of file FactionRanks.cpp.
FactionRanks::FactionRanks (const FactionRanks & f)
Definition at line 15 of file FactionRanks.cpp.
References ranks.
Member Function Documentation
int FactionRanks::getCount () inline
Definition at line 29 of file FactionRanks.h.
References ranks.
Referenced by FactionManager::getFactionPointsCap(), FactionManager::getRankCost(), FactionManager::getRankDelegateRatioFrom(), FactionManager::getRankDelegateRatioTo(), FactionManager::getRankName(), FactionManager::isHighestRank(), and FactionManager::loadFactionRanks().
FactionRank& FactionRanks::getRank (int index) inline
Definition at line 25 of file FactionRanks.h.
References ranks.
Referenced by FactionManager::getRankCost(), FactionManager::getRankDelegateRatioFrom(), FactionManager::getRankDelegateRatioTo(), and FactionManager::getRankName().
void FactionRanks::readObject (DataTableIff * table)
Definition at line 19 of file FactionRanks.cpp.
References DataTableIff::getRow(), DataTableIff::getTotalRows(), ranks, and FactionRank::readObject().
Referenced by FactionManager::loadFactionRanks().
Member Data Documentation
Vector<FactionRank> FactionRanks::ranks protected
Definition at line 17 of file FactionRanks.h.
Referenced by FactionRanks(), getCount(), getRank(), and readObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/faction/FactionRanks.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/faction/FactionRanks.cpp