Core3: server::zone::objects::region::CityRegionAdapter Class Reference
server::zone::objects::region::CityRegionAdapter Class Reference
#include <CityRegion.h>
Public Member Functions
CityRegionAdapter (CityRegion *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initialize ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void notifyEnter (SceneObject *object)
void notifyExit (SceneObject *object)
Region * addRegion (float x, float y, float radius, bool persistent)
void rescheduleUpdateEvent (unsigned int seconds)
void destroyActiveAreas ()
void addMilitiaMember (unsigned long long objectid)
void removeMilitiaMember (unsigned long long objectid)
bool isMilitiaMember (unsigned long long objectid)
void addZoningRights (unsigned long long objectid, unsigned int duration)
void removeZoningRights (unsigned long long objectid)
bool hasZoningRights (unsigned long long objectid)
bool containsPoint (float x, float y)
void cleanupCitizens ()
int getCurrentPlayerCount ()
void addCitizen (unsigned long long citizenID)
void removeCitizen (unsigned long long citizenID)
void addBannedPlayer (unsigned long long playerid)
void removeBannedPlayer (unsigned long long playerid)
bool isCitizen (unsigned long long citizenID)
int getTimeToUpdate ()
int getCitizenCount ()
byte getCityRank ()
bool isBanned (unsigned long long playerID)
bool isRegistered ()
Zone * getZone ()
String getRegionName ()
unsigned long long getMayorID ()
float getPositionX ()
float getPositionY ()
float getRadius ()
Region * getRegion (int idx)
int getRegionsCount ()
int getStructuresCount ()
int getCommercialStructuresCount ()
int getAllStructuresCount ()
String getCitySpecialization ()
float getCityTreasury ()
bool isMayor (unsigned long long objectid)
bool isZoningEnabled ()
bool isClientRegion ()
StructureObject * getCityHall ()
void setZone (Zone *zne)
void setCustomRegionName (const String &name)
void setCitySpecialization (const String &spec)
void setRegionName (const String &fullPath)
void setCityTreasury (float val)
float addToCityTreasury (float val)
float subtractFromCityTreasury (float val)
int getMaxWithdrawal ()
void setCityRank (byte rank)
void setMayorID (unsigned long long id)
void setRegistered (bool val)
void setZoningEnabled (bool val)
void setRadius (float rad)
void setCityHall (StructureObject *building)
void removeShuttleInstallation ()
bool hasShuttleInstallation ()
void setShuttleID (unsigned long long id)
int getMissionTerminalCount ()
int getDecorationCount ()
int getSkillTrainerCount ()
void addMissionTerminal (SceneObject *mt)
void addDecoration (SceneObject *deco)
void addSkillTrainer (SceneObject *trainer)
void removeMissionTerminal (SceneObject *mt)
void removeDecoration (SceneObject *deco)
void removeSkillTrainers (SceneObject *trainer)
void addBazaar (TangibleObject *ter)
TangibleObject * getBazaar (int idx)
int getBazaarCount ()
void removeAllSkillTrainers ()
void removeAllTerminals ()
void removeAllDecorations ()
void updateMilitia ()
void addStructure (StructureObject *structure)
void addCommercialStructure (StructureObject *structure)
void removeStructure (StructureObject *structure)
void removeCommercialStructure (StructureObject *structure)
bool hasUniqueStructure (unsigned int crc)
void destroyAllStructuresForRank (byte rank)
void addCandidate (unsigned long long candidateoid)
void setMayoralVote (unsigned long long voteroid, unsigned long long candidateoid)
int getCandidateVotes (unsigned long long candidateoid)
void resetCandidates ()
void resetMayoralVotes ()
void removeCandidate (unsigned long long candidateoid)
bool isCandidate (unsigned long long candidateoid)
bool isVotingPeriodOver ()
bool isVotingPeriod ()
bool isVotingLocked ()
void resetVotingPeriod ()
bool isLoaded ()
void setLoaded ()
void applySpecializationModifiers (CreatureObject *creature)
void removeSpecializationModifiers (CreatureObject *creature)
int getPropertyTax ()
int getIncomeTax ()
int getSalesTax ()
int getTravelTax ()
int getGarageTax ()
int getTax (int tax)
void setTax (int tax, int value)
void transferCivicStructuresToMayor ()
void cleanupDuplicateCityStructures ()
void removeDecorationsOutsideCity (int newRadius)
void removeTrainersOutsideCity (int newRadius)
void removeTerminalsOutsideCity (int newRadius)
void removeStructuresOutsideCity (int newRadius)
bool isInsideRadius (SceneObject *obj, int radiusToUse)
void removeAmenitiesOutsideCity (int newRadius)
void cleanupDecorations (int decorationLimit)
Detailed Description
Definition at line 870 of file CityRegion.h.
Constructor & Destructor Documentation
CityRegionAdapter::CityRegionAdapter (CityRegion * impl)
Definition at line 2791 of file CityRegion.cpp.
Member Function Documentation
void CityRegionAdapter::addBannedPlayer (unsigned long long playerid)
Definition at line 3452 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::addBazaar (TangibleObject * ter)
Definition at line 3656 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::addCandidate (unsigned long long candidateoid)
Definition at line 3708 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::addCitizen (unsigned long long citizenID)
Definition at line 3444 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::addCommercialStructure (StructureObject * structure)
Definition at line 3688 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::addDecoration (SceneObject * deco)
Definition at line 3636 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::addMilitiaMember (unsigned long long objectid)
Definition at line 3408 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::addMissionTerminal (SceneObject * mt)
Definition at line 3632 of file CityRegion.cpp.
Referenced by invokeMethod().
Region * CityRegionAdapter::addRegion (float x, float y, float radius, bool persistent)
Definition at line 3396 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::addSkillTrainer (SceneObject * trainer)
Definition at line 3640 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::addStructure (StructureObject * structure)
Definition at line 3684 of file CityRegion.cpp.
Referenced by invokeMethod().
float CityRegionAdapter::addToCityTreasury (float val)
Definition at line 3572 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::addZoningRights (unsigned long long objectid, unsigned int duration)
Definition at line 3420 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::applySpecializationModifiers (CreatureObject * creature)
Definition at line 3760 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::cleanupCitizens ()
Definition at line 3436 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::cleanupDecorations (int decorationLimit)
Definition at line 3828 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::cleanupDuplicateCityStructures ()
Definition at line 3800 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::containsPoint (float x, float y)
Definition at line 3432 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::destroyActiveAreas ()
Definition at line 3404 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::destroyAllStructuresForRank (byte rank)
Definition at line 3704 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getAllStructuresCount ()
Definition at line 3524 of file CityRegion.cpp.
Referenced by invokeMethod().
TangibleObject * CityRegionAdapter::getBazaar (int idx)
Definition at line 3660 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getBazaarCount ()
Definition at line 3664 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getCandidateVotes (unsigned long long candidateoid)
Definition at line 3716 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getCitizenCount ()
Definition at line 3468 of file CityRegion.cpp.
Referenced by invokeMethod().
StructureObject * CityRegionAdapter::getCityHall ()
Definition at line 3548 of file CityRegion.cpp.
Referenced by invokeMethod().
byte CityRegionAdapter::getCityRank ()
Definition at line 3472 of file CityRegion.cpp.
Referenced by invokeMethod().
String CityRegionAdapter::getCitySpecialization ()
Definition at line 3528 of file CityRegion.cpp.
Referenced by invokeMethod().
float CityRegionAdapter::getCityTreasury ()
Definition at line 3532 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getCommercialStructuresCount ()
Definition at line 3520 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getCurrentPlayerCount ()
Definition at line 3440 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getDecorationCount ()
Definition at line 3624 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getGarageTax ()
Definition at line 3784 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getIncomeTax ()
Definition at line 3772 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getMaxWithdrawal ()
Definition at line 3580 of file CityRegion.cpp.
Referenced by invokeMethod().
unsigned long long CityRegionAdapter::getMayorID ()
Definition at line 3492 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getMissionTerminalCount ()
Definition at line 3620 of file CityRegion.cpp.
Referenced by invokeMethod().
float CityRegionAdapter::getPositionX ()
Definition at line 3496 of file CityRegion.cpp.
Referenced by invokeMethod().
float CityRegionAdapter::getPositionY ()
Definition at line 3500 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getPropertyTax ()
Definition at line 3768 of file CityRegion.cpp.
Referenced by invokeMethod().
float CityRegionAdapter::getRadius ()
Definition at line 3504 of file CityRegion.cpp.
Referenced by invokeMethod().
Region * CityRegionAdapter::getRegion (int idx)
Definition at line 3508 of file CityRegion.cpp.
Referenced by invokeMethod().
String CityRegionAdapter::getRegionName ()
Definition at line 3488 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getRegionsCount ()
Definition at line 3512 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getSalesTax ()
Definition at line 3776 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getSkillTrainerCount ()
Definition at line 3628 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getStructuresCount ()
Definition at line 3516 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getTax (int tax)
Definition at line 3788 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getTimeToUpdate ()
Definition at line 3464 of file CityRegion.cpp.
Referenced by invokeMethod().
int CityRegionAdapter::getTravelTax ()
Definition at line 3780 of file CityRegion.cpp.
Referenced by invokeMethod().
Zone * CityRegionAdapter::getZone ()
Definition at line 3484 of file CityRegion.cpp.
References server::zone::objects::scene::SceneObject::getZone().
Referenced by invokeMethod().
bool CityRegionAdapter::hasShuttleInstallation ()
Definition at line 3612 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::hasUniqueStructure (unsigned int crc)
Definition at line 3700 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::hasZoningRights (unsigned long long objectid)
Definition at line 3428 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::initialize ()
Definition at line 3376 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::initializeTransientMembers ()
Definition at line 3380 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 2794 of file CityRegion.cpp.
References addBannedPlayer(), addBazaar(), addCandidate(), addCitizen(), addCommercialStructure(), addDecoration(), addMilitiaMember(), addMissionTerminal(), addRegion(), addSkillTrainer(), addStructure(), addToCityTreasury(), addZoningRights(), applySpecializationModifiers(), cleanupCitizens(), cleanupDecorations(), cleanupDuplicateCityStructures(), containsPoint(), destroyActiveAreas(), destroyAllStructuresForRank(), getAllStructuresCount(), getBazaar(), getBazaarCount(), getCandidateVotes(), getCitizenCount(), getCityHall(), getCityRank(), getCitySpecialization(), getCityTreasury(), getCommercialStructuresCount(), getCurrentPlayerCount(), getDecorationCount(), getGarageTax(), getIncomeTax(), getMaxWithdrawal(), getMayorID(), getMissionTerminalCount(), getPositionX(), getPositionY(), getPropertyTax(), getRadius(), getRegion(), getRegionName(), getRegionsCount(), getSalesTax(), getSkillTrainerCount(), getStructuresCount(), getTax(), getTimeToUpdate(), getTravelTax(), getZone(), hasShuttleInstallation(), hasUniqueStructure(), hasZoningRights(), initialize(), initializeTransientMembers(), isBanned(), isCandidate(), isCitizen(), isClientRegion(), isInsideRadius(), isLoaded(), isMayor(), isMilitiaMember(), isRegistered(), isVotingLocked(), isVotingPeriod(), isVotingPeriodOver(), isZoningEnabled(), notifyEnter(), notifyExit(), notifyLoadFromDatabase(), removeAllDecorations(), removeAllSkillTrainers(), removeAllTerminals(), removeAmenitiesOutsideCity(), removeBannedPlayer(), removeCandidate(), removeCitizen(), removeCommercialStructure(), removeDecoration(), removeDecorationsOutsideCity(), removeMilitiaMember(), removeMissionTerminal(), removeShuttleInstallation(), removeSkillTrainers(), removeSpecializationModifiers(), removeStructure(), removeStructuresOutsideCity(), removeTerminalsOutsideCity(), removeTrainersOutsideCity(), removeZoningRights(), rescheduleUpdateEvent(), resetCandidates(), resetMayoralVotes(), resetVotingPeriod(), RPC_ADDBANNEDPLAYER__LONG_, RPC_ADDBAZAAR__TANGIBLEOBJECT_, RPC_ADDCANDIDATE__LONG_, RPC_ADDCITIZEN__LONG_, RPC_ADDCOMMERCIALSTRUCTURE__STRUCTUREOBJECT_, RPC_ADDDECORATION__SCENEOBJECT_, RPC_ADDMILITIAMEMBER__LONG_, RPC_ADDMISSIONTERMINAL__SCENEOBJECT_, RPC_ADDREGION__FLOAT_FLOAT_FLOAT_BOOL_, RPC_ADDSKILLTRAINER__SCENEOBJECT_, RPC_ADDSTRUCTURE__STRUCTUREOBJECT_, RPC_ADDTOCITYTREASURY__FLOAT_, RPC_ADDZONINGRIGHTS__LONG_INT_, RPC_APPLYSPECIALIZATIONMODIFIERS__CREATUREOBJECT_, RPC_CLEANUPCITIZENS__, RPC_CLEANUPDECORATIONS__INT_, RPC_CLEANUPDUPLICATECITYSTRUCTURES__, RPC_CONTAINSPOINT__FLOAT_FLOAT_, RPC_DESTROYACTIVEAREAS__, RPC_DESTROYALLSTRUCTURESFORRANK__BYTE_, RPC_GETALLSTRUCTURESCOUNT__, RPC_GETBAZAAR__INT_, RPC_GETBAZAARCOUNT__, RPC_GETCANDIDATEVOTES__LONG_, RPC_GETCITIZENCOUNT__, RPC_GETCITYHALL__, RPC_GETCITYRANK__, RPC_GETCITYSPECIALIZATION__, RPC_GETCITYTREASURY__, RPC_GETCOMMERCIALSTRUCTURESCOUNT__, RPC_GETCURRENTPLAYERCOUNT__, RPC_GETDECORATIONCOUNT__, RPC_GETGARAGETAX__, RPC_GETINCOMETAX__, RPC_GETMAXWITHDRAWAL__, RPC_GETMAYORID__, RPC_GETMISSIONTERMINALCOUNT__, RPC_GETPOSITIONX__, RPC_GETPOSITIONY__, RPC_GETPROPERTYTAX__, RPC_GETRADIUS__, RPC_GETREGION__INT_, RPC_GETREGIONNAME__, RPC_GETREGIONSCOUNT__, RPC_GETSALESTAX__, RPC_GETSKILLTRAINERCOUNT__, RPC_GETSTRUCTURESCOUNT__, RPC_GETTAX__INT_, RPC_GETTIMETOUPDATE__, RPC_GETTRAVELTAX__, RPC_GETZONE__, RPC_HASSHUTTLEINSTALLATION__, RPC_HASUNIQUESTRUCTURE__INT_, RPC_HASZONINGRIGHTS__LONG_, RPC_INITIALIZE__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_ISBANNED__LONG_, RPC_ISCANDIDATE__LONG_, RPC_ISCITIZEN__LONG_, RPC_ISCLIENTREGION__, RPC_ISINSIDERADIUS__SCENEOBJECT_INT_, RPC_ISLOADED__, RPC_ISMAYOR__LONG_, RPC_ISMILITIAMEMBER__LONG_, RPC_ISREGISTERED__, RPC_ISVOTINGLOCKED__, RPC_ISVOTINGPERIOD__, RPC_ISVOTINGPERIODOVER__, RPC_ISZONINGENABLED__, RPC_NOTIFYENTER__SCENEOBJECT_, RPC_NOTIFYEXIT__SCENEOBJECT_, RPC_NOTIFYLOADFROMDATABASE__, RPC_REMOVEALLDECORATIONS__, RPC_REMOVEALLSKILLTRAINERS__, RPC_REMOVEALLTERMINALS__, RPC_REMOVEAMENITIESOUTSIDECITY__INT_, RPC_REMOVEBANNEDPLAYER__LONG_, RPC_REMOVECANDIDATE__LONG_, RPC_REMOVECITIZEN__LONG_, RPC_REMOVECOMMERCIALSTRUCTURE__STRUCTUREOBJECT_, RPC_REMOVEDECORATION__SCENEOBJECT_, RPC_REMOVEDECORATIONSOUTSIDECITY__INT_, RPC_REMOVEMILITIAMEMBER__LONG_, RPC_REMOVEMISSIONTERMINAL__SCENEOBJECT_, RPC_REMOVESHUTTLEINSTALLATION__, RPC_REMOVESKILLTRAINERS__SCENEOBJECT_, RPC_REMOVESPECIALIZATIONMODIFIERS__CREATUREOBJECT_, RPC_REMOVESTRUCTURE__STRUCTUREOBJECT_, RPC_REMOVESTRUCTURESOUTSIDECITY__INT_, RPC_REMOVETERMINALSOUTSIDECITY__INT_, RPC_REMOVETRAINERSOUTSIDECITY__INT_, RPC_REMOVEZONINGRIGHTS__LONG_, RPC_RESCHEDULEUPDATEEVENT__INT_, RPC_RESETCANDIDATES__, RPC_RESETMAYORALVOTES__, RPC_RESETVOTINGPERIOD__, RPC_SETCITYHALL__STRUCTUREOBJECT_, RPC_SETCITYRANK__BYTE_, RPC_SETCITYSPECIALIZATION__STRING_, RPC_SETCITYTREASURY__FLOAT_, RPC_SETCUSTOMREGIONNAME__STRING_, RPC_SETLOADED__, RPC_SETMAYORALVOTE__LONG_LONG_, RPC_SETMAYORID__LONG_, RPC_SETRADIUS__FLOAT_, RPC_SETREGIONNAME__STRING_, RPC_SETREGISTERED__BOOL_, RPC_SETSHUTTLEID__LONG_, RPC_SETTAX__INT_INT_, RPC_SETZONE__ZONE_, RPC_SETZONINGENABLED__BOOL_, RPC_SUBTRACTFROMCITYTREASURY__FLOAT_, RPC_TRANSFERCIVICSTRUCTURESTOMAYOR__, RPC_UPDATEMILITIA__, setCityHall(), setCityRank(), setCitySpecialization(), setCityTreasury(), setCustomRegionName(), setLoaded(), setMayoralVote(), setMayorID(), setRadius(), setRegionName(), setRegistered(), setShuttleID(), setTax(), setZone(), setZoningEnabled(), subtractFromCityTreasury(), transferCivicStructuresToMayor(), and updateMilitia().
bool CityRegionAdapter::isBanned (unsigned long long playerID)
Definition at line 3476 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isCandidate (unsigned long long candidateoid)
Definition at line 3732 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isCitizen (unsigned long long citizenID)
Definition at line 3460 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isClientRegion ()
Definition at line 3544 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isInsideRadius (SceneObject * obj, int radiusToUse)
Definition at line 3820 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isLoaded ()
Definition at line 3752 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isMayor (unsigned long long objectid)
Definition at line 3536 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isMilitiaMember (unsigned long long objectid)
Definition at line 3416 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isRegistered ()
Definition at line 3480 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isVotingLocked ()
Definition at line 3744 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isVotingPeriod ()
Definition at line 3740 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isVotingPeriodOver ()
Definition at line 3736 of file CityRegion.cpp.
Referenced by invokeMethod().
bool CityRegionAdapter::isZoningEnabled ()
Definition at line 3540 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::notifyEnter (SceneObject * object)
Definition at line 3388 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::notifyExit (SceneObject * object)
Definition at line 3392 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::notifyLoadFromDatabase ()
Definition at line 3384 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeAllDecorations ()
Definition at line 3676 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeAllSkillTrainers ()
Definition at line 3668 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeAllTerminals ()
Definition at line 3672 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeAmenitiesOutsideCity (int newRadius)
Definition at line 3824 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeBannedPlayer (unsigned long long playerid)
Definition at line 3456 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeCandidate (unsigned long long candidateoid)
Definition at line 3728 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeCitizen (unsigned long long citizenID)
Definition at line 3448 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeCommercialStructure (StructureObject * structure)
Definition at line 3696 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeDecoration (SceneObject * deco)
Definition at line 3648 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeDecorationsOutsideCity (int newRadius)
Definition at line 3804 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeMilitiaMember (unsigned long long objectid)
Definition at line 3412 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeMissionTerminal (SceneObject * mt)
Definition at line 3644 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeShuttleInstallation ()
Definition at line 3608 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeSkillTrainers (SceneObject * trainer)
Definition at line 3652 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeSpecializationModifiers (CreatureObject * creature)
Definition at line 3764 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeStructure (StructureObject * structure)
Definition at line 3692 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeStructuresOutsideCity (int newRadius)
Definition at line 3816 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeTerminalsOutsideCity (int newRadius)
Definition at line 3812 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeTrainersOutsideCity (int newRadius)
Definition at line 3808 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::removeZoningRights (unsigned long long objectid)
Definition at line 3424 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::rescheduleUpdateEvent (unsigned int seconds)
Definition at line 3400 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::resetCandidates ()
Definition at line 3720 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::resetMayoralVotes ()
Definition at line 3724 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::resetVotingPeriod ()
Definition at line 3748 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setCityHall (StructureObject * building)
Definition at line 3604 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setCityRank (byte rank)
Definition at line 3584 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setCitySpecialization (const String & spec)
Definition at line 3560 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setCityTreasury (float val)
Definition at line 3568 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setCustomRegionName (const String & name)
Definition at line 3556 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setLoaded ()
Definition at line 3756 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setMayoralVote (unsigned long long voteroid, unsigned long long candidateoid)
Definition at line 3712 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setMayorID (unsigned long long id)
Definition at line 3588 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setRadius (float rad)
Definition at line 3600 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setRegionName (const String & fullPath)
Definition at line 3564 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setRegistered (bool val)
Definition at line 3592 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setShuttleID (unsigned long long id)
Definition at line 3616 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setTax (int tax, int value)
Definition at line 3792 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setZone (Zone * zne)
Definition at line 3552 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::setZoningEnabled (bool val)
Definition at line 3596 of file CityRegion.cpp.
Referenced by invokeMethod().
float CityRegionAdapter::subtractFromCityTreasury (float val)
Definition at line 3576 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::transferCivicStructuresToMayor ()
Definition at line 3796 of file CityRegion.cpp.
Referenced by invokeMethod().
void CityRegionAdapter::updateMilitia ()
Definition at line 3680 of file CityRegion.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/region/CityRegion.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/region/CityRegion.cpp