Core3: LootGroups Class Reference
LootGroups Class Reference
#include <LootGroups.h>
Public Member Functions
LootGroups ()
void readObject (LuaObject *obj)
void put (const LootGroupEntry &entry)
int count ()
LootGroupEntry * get (int idx)
Private Attributes
SortedVector< LootGroupEntry > entries
Detailed Description
Definition at line 14 of file LootGroups.h.
Constructor & Destructor Documentation
LootGroups::LootGroups () inline
Definition at line 18 of file LootGroups.h.
Member Function Documentation
int LootGroups::count () inline
Definition at line 45 of file LootGroups.h.
References entries.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootFromCollection(), and TEST_F().
LootGroupEntry* LootGroups::get (int idx) inline
Definition at line 49 of file LootGroups.h.
References entries.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootFromCollection(), and TEST_F().
void LootGroups::put (const LootGroupEntry & entry) inline
Definition at line 41 of file LootGroups.h.
References entries.
Referenced by readObject().
void LootGroups::readObject (LuaObject * obj) inline
Definition at line 21 of file LootGroups.h.
References put(), and LootGroupEntry::readObject().
Referenced by LootGroupCollectionEntry::readObject().
Member Data Documentation
SortedVector<LootGroupEntry> LootGroups::entries private
Definition at line 15 of file LootGroups.h.
Referenced by count(), get(), and put().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/lootgroup/LootGroups.h