Core3: server::zone::managers::minigames::ForageManager Class Reference
server::zone::managers::minigames::ForageManager Class Reference
#include <ForageManager.h>
Public Member Functions
ForageManager ()
void deleteForageAreaCollection (String &playerName)
void startForaging (CreatureObject *player, int forageType)
void finishForaging (CreatureObject *player, int forageType, float forageX, float forageY, const String &planet)
bool forageGiveItems (CreatureObject *player, int forageType, float forageX, float forageY, const String &planet)
bool forageGiveResource (CreatureObject *player, float forageX, float forageY, const String &planet, String &resType)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int SCOUT = 1
static const int MEDICAL = 2
static const int LAIR = 3
static const int SHELLFISH = 4
Protected Member Functions
ForageManager (DummyConstructorParameter *param)
virtual ~ForageManager ()
Friends
class ForageManagerHelper
Detailed Description
Definition at line 65 of file ForageManager.h.
Constructor & Destructor Documentation
ForageManager::ForageManager ()
Definition at line 19 of file ForageManager.cpp.
References server::zone::managers::minigames::ForageManagerImplementation::_setStub().
ForageManager::ForageManager (DummyConstructorParameter * param) protected
Definition at line 26 of file ForageManager.cpp.
ForageManager::~ForageManager () protected virtual
Definition at line 30 of file ForageManager.cpp.
Member Function Documentation
DistributedObjectServant * ForageManager::_getImplementation ()
Definition at line 118 of file ForageManager.cpp.
Referenced by deleteForageAreaCollection(), finishForaging(), forageGiveItems(), forageGiveResource(), and startForaging().
DistributedObjectServant * ForageManager::_getImplementationForRead ()
Definition at line 124 of file ForageManager.cpp.
void ForageManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 128 of file ForageManager.cpp.
void ForageManager::deleteForageAreaCollection (String & playerName)
Definition at line 35 of file ForageManager.cpp.
References _getImplementation(), server::zone::managers::minigames::ForageManagerImplementation::deleteForageAreaCollection(), and RPC_DELETEFORAGEAREACOLLECTION__STRING_.
void ForageManager::finishForaging (CreatureObject * player, int forageType, float forageX, float forageY, const String & planet)
Finishes foraging. Checks if the player moved since first foraging. If so, cancels forage. Checks if the player entered combat. If so, cancels forage. Checks the forage areas to see if the player is allowed to forage here again. If not, cancels forage. Determines if the player is successful or not in the forage attempt. If successful, activates forageGiveItems().
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is not locked, player is not locked }
Parameters
player CreatureObject who is foraging.
scoutForage Determines if the player is using /forage or /medicalforage.
forageX The x coordinate of the player's position when they first started foraging.
forageY The y coordinate of the player's position when they first started foraging.
planet The planet (zone ID) the player was on when they first started foraging.
Definition at line 64 of file ForageManager.cpp.
References _getImplementation(), server::zone::managers::minigames::ForageManagerImplementation::finishForaging(), and RPC_FINISHFORAGING__CREATUREOBJECT_INT_FLOAT_FLOAT_STRING_.
bool ForageManager::forageGiveItems (CreatureObject * player, int forageType, float forageX, float forageY, const String & planet)
Gives the player items for a successful forage. Checks player's inventory space and discards items they could have received if they had space. Determines which loot group they will get an item from. If resource, calls giveForageResource().
Precondition
{ this object is not locked, player is locked }
Postcondition
{ this object is not locked, player is not locked }
Parameters
player CreatureObject who is foraging.
scoutForage Determines if the player is using /forage or /medicalforage.
forageX The x coordinate of the player's position when they first started foraging.
forageY The y coordinate of the player's position when they first started foraging.
planet The planet (zone ID) the player was on when they first started foraging.
Definition at line 82 of file ForageManager.cpp.
References _getImplementation(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveItems(), and RPC_FORAGEGIVEITEMS__CREATUREOBJECT_INT_FLOAT_FLOAT_STRING_.
bool ForageManager::forageGiveResource (CreatureObject * player, float forageX, float forageY, const String & planet, String & resType)
Gives the player resources for a successful forage. Pulls a list of all the flora resource spawns on that planet. Picks a random flora from the list and gives it to the player if there is some under them. If the density of the flora is zero, it picks a different resource.
Precondition
{ this object is not locked, player is locked }
Postcondition
{ this object is not locked, player is not locked }
Parameters
player CreatureObject who is foraging.
forageX The x coordinate of the player's position when they first started foraging.
forageY The y coordinate of the player's position when they first started foraging.
planet The planet (zone ID) the player was on when they first started foraging.
Definition at line 100 of file ForageManager.cpp.
References _getImplementation(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveResource(), and RPC_FORAGEGIVERESOURCE__CREATUREOBJECT_FLOAT_FLOAT_STRING_STRING_.
void ForageManager::startForaging (CreatureObject * player, int forageType)
Starts foraging. Checks the player's pending tasks to see if they are already foraging. If so, cancels forage. Checks if the player is inside a structure. If so, cancels forage. Deducts the foraging action cost from the player. Collects the player's current position so we can compare it after the forage animation is done. Creates the forage task and puts it into the player's pending tasks, it will activate in 8.5 seconds and will activate finishForaging().
Precondition
{ this object is not locked, player is locked }
Postcondition
{ this object is not locked, player is not locked }
Parameters
player CreatureObject who is trying to forage.
scoutForage Determines if the player is using /forage or /medicalforage.
Definition at line 49 of file ForageManager.cpp.
References _getImplementation(), RPC_STARTFORAGING__CREATUREOBJECT_INT_, and server::zone::managers::minigames::ForageManagerImplementation::startForaging().
Referenced by ForageCommand::doQueueCommand(), MedicalForageCommand::doQueueCommand(), ShellfishHarvesterMenuComponent::handleObjectMenuSelect(), and LairMenuComponent::handleObjectMenuSelect().
Friends And Related Function Documentation
friend class ForageManagerHelper friend
Definition at line 149 of file ForageManager.h.
Member Data Documentation
const int server::zone::managers::minigames::ForageManager::LAIR = 3 static
Definition at line 71 of file ForageManager.h.
Referenced by server::zone::managers::minigames::ForageManagerImplementation::finishForaging(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveItems(), and server::zone::managers::minigames::ForageManagerImplementation::startForaging().
const int server::zone::managers::minigames::ForageManager::MEDICAL = 2 static
Definition at line 69 of file ForageManager.h.
Referenced by server::zone::managers::minigames::ForageManagerImplementation::finishForaging(), and server::zone::managers::minigames::ForageManagerImplementation::forageGiveItems().
const int server::zone::managers::minigames::ForageManager::SCOUT = 1 static
Definition at line 67 of file ForageManager.h.
Referenced by server::zone::managers::minigames::ForageManagerImplementation::finishForaging(), and server::zone::managers::minigames::ForageManagerImplementation::forageGiveItems().
const int server::zone::managers::minigames::ForageManager::SHELLFISH = 4 static
Definition at line 73 of file ForageManager.h.
Referenced by server::zone::managers::minigames::ForageManagerImplementation::finishForaging(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveItems(), and server::zone::managers::minigames::ForageManagerImplementation::startForaging().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/ForageManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/ForageManager.cpp