Core3: server::zone::objects::creature::buffs::DurationBuffImplementation Class Reference
server::zone::objects::creature::buffs::DurationBuffImplementation Class Reference
#include <DurationBuff.h>
Public Member Functions
DurationBuffImplementation (CreatureObject *creo, unsigned int buffcrc, float duration)
DurationBuffImplementation (DummyConstructorParameter *param)
void activate (bool applyModifiers)
void deactivate (bool applyModifiers)
operator const DurationBuff * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
BuffImplementation (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype)
BuffImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
virtual void sendTo (CreatureObject *player)
virtual void sendDestroyTo (CreatureObject *player)
virtual void activate ()
virtual void deactivate ()
VectorMap< String, int > * getSkillModifiers ()
virtual void applyAttributeModifiers ()
virtual void applySkillModifiers ()
virtual void applyStates ()
virtual void removeAttributeModifiers ()
virtual void removeSkillModifiers ()
virtual void removeStates ()
virtual void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
virtual void parseAttributeModifierString (const String &modifierstring)
virtual void parseSkillModifierString (const String &modifierstring)
virtual String getAttributeModifierString ()
virtual String getSkillModifierString ()
virtual float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
VectorMap< byte, int > * getAttributeModifiers ()
virtual int getAttributeModifierValue (byte attribute)
virtual int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartMessage (StringIdChatParameter &start)
void setEndMessage (StringIdChatParameter &end)
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
operator const Buff * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< DurationBuff * > _this
Public Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
WeakReference< Buff * > _this
Protected Member Functions
virtual ~DurationBuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
virtual ~BuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class DurationBuff
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
ManagedWeakReference
< CreatureObject * > creature
Reference< BuffDurationEvent * > buffEvent
VectorMap< byte, int > attributeModifiers
VectorMap< String, int > skillModifiers
Vector< unsigned long long > states
String buffName
float buffDuration
unsigned int buffCRC
int buffType
bool fillAttributesOnBuff
StringIdChatParameter startMessage
StringIdChatParameter endMessage
String startFlyFile
String startFlyAux
byte startFlyRed
byte startFlyGreen
byte startFlyBlue
String endFlyFile
String endFlyAux
byte endFlyRed
byte endFlyGreen
byte endFlyBlue
Time nextExecutionTime
Detailed Description
Definition at line 133 of file DurationBuff.h.
Constructor & Destructor Documentation
DurationBuffImplementation::DurationBuffImplementation (CreatureObject * creo, unsigned int buffcrc, float duration)
Definition at line 197 of file DurationBuff.cpp.
References _initializeImplementation().
DurationBuffImplementation::DurationBuffImplementation (DummyConstructorParameter * param)
Definition at line 83 of file DurationBuff.cpp.
References _initializeImplementation().
DurationBuffImplementation::~DurationBuffImplementation () protected virtual
Definition at line 88 of file DurationBuff.cpp.
Member Function Documentation
DistributedObjectStub * DurationBuffImplementation::_getStub ()
Definition at line 108 of file DurationBuff.cpp.
References _this.
void DurationBuffImplementation::_initializeImplementation () protected
Definition at line 95 of file DurationBuff.cpp.
References _serializationHelperMethod(), and _this.
Referenced by DurationBuffImplementation().
void DurationBuffImplementation::_serializationHelperMethod () protected
Definition at line 144 of file DurationBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void DurationBuffImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 103 of file DurationBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::buffs::DurationBuff::DurationBuff().
void DurationBuffImplementation::activate (bool applyModifiers) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 201 of file DurationBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::activate().
Referenced by server::zone::objects::creature::buffs::DurationBuff::activate().
void DurationBuffImplementation::deactivate (bool applyModifiers) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 206 of file DurationBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::deactivate().
Referenced by server::zone::objects::creature::buffs::DurationBuff::deactivate().
void DurationBuffImplementation::finalize () protected
Definition at line 92 of file DurationBuff.cpp.
void DurationBuffImplementation::lock (bool doLock = true) protected
Definition at line 116 of file DurationBuff.cpp.
References _this.
void DurationBuffImplementation::lock (ManagedObject * obj) protected
Definition at line 120 of file DurationBuff.cpp.
References _this.
DurationBuffImplementation::operator const DurationBuff * ()
Definition at line 112 of file DurationBuff.cpp.
void DurationBuffImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 151 of file DurationBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::initializeTransientMembers(), and readObjectMember().
bool DurationBuffImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 170 of file DurationBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::readObjectMember().
Referenced by readObject().
void DurationBuffImplementation::rlock (bool doLock = true) protected
Definition at line 124 of file DurationBuff.cpp.
References _this.
void DurationBuffImplementation::runlock (bool doLock = true) protected
Definition at line 140 of file DurationBuff.cpp.
References _this.
void DurationBuffImplementation::unlock (bool doLock = true) protected
Definition at line 136 of file DurationBuff.cpp.
References _this.
void DurationBuffImplementation::wlock (bool doLock = true) protected
Definition at line 128 of file DurationBuff.cpp.
References _this.
void DurationBuffImplementation::wlock (ManagedObject * obj) protected
Definition at line 132 of file DurationBuff.cpp.
References _this.
void DurationBuffImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 180 of file DurationBuff.cpp.
References writeObjectMembers().
int DurationBuffImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 187 of file DurationBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class DurationBuff friend
Definition at line 178 of file DurationBuff.h.
Member Data Documentation
WeakReference<DurationBuff*> server::zone::objects::creature::buffs::DurationBuffImplementation::_this
Definition at line 144 of file DurationBuff.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/DurationBuff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/DurationBuff.cpp