Core3: server::zone::objects::mission::MissionObjectiveAdapter Class Reference
server::zone::objects::mission::MissionObjectiveAdapter Class Reference
#include <MissionObjective.h>
Public Member Functions
MissionObjectiveAdapter (MissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Detailed Description
Definition at line 284 of file MissionObjective.h.
Constructor & Destructor Documentation
MissionObjectiveAdapter::MissionObjectiveAdapter (MissionObjective * impl)
Definition at line 597 of file MissionObjective.cpp.
Member Function Documentation
void MissionObjectiveAdapter::abort ()
Definition at line 753 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::activate ()
Definition at line 745 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::addObserver (MissionObserver * observer, bool makePersistent)
Definition at line 721 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::awardFactionPoints ()
Definition at line 777 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::awardReward ()
Definition at line 785 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::complete ()
Definition at line 757 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::deactivate ()
Definition at line 749 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::destroyObjectFromDatabase ()
Definition at line 713 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::dropObserver (MissionObserver * observer, bool removeFromDatabase)
Definition at line 725 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::fail ()
Definition at line 761 of file MissionObjective.cpp.
Referenced by invokeMethod().
ManagedWeakReference< MissionObject * > MissionObjectiveAdapter::getMissionObject ()
Definition at line 765 of file MissionObjective.cpp.
Referenced by invokeMethod().
unsigned int MissionObjectiveAdapter::getObjectiveType ()
Definition at line 769 of file MissionObjective.cpp.
Referenced by invokeMethod().
MissionObserver * MissionObjectiveAdapter::getObserver (int index)
Definition at line 737 of file MissionObjective.cpp.
Referenced by invokeMethod().
int MissionObjectiveAdapter::getObserverCount ()
Definition at line 729 of file MissionObjective.cpp.
Referenced by invokeMethod().
ManagedWeakReference< CreatureObject * > MissionObjectiveAdapter::getPlayerOwner ()
Definition at line 773 of file MissionObjective.cpp.
Referenced by invokeMethod().
bool MissionObjectiveAdapter::hasObservers ()
Definition at line 741 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::initializeTransientMembers ()
Definition at line 709 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 600 of file MissionObjective.cpp.
References abort(), activate(), addObserver(), awardFactionPoints(), awardReward(), complete(), deactivate(), destroyObjectFromDatabase(), dropObserver(), fail(), getMissionObject(), getObjectiveType(), getObserver(), getObserverCount(), getPlayerOwner(), hasObservers(), initializeTransientMembers(), notifyObserverEvent(), removeAllObservers(), removeMissionFromPlayer(), RPC_ABORT__, RPC_ACTIVATE__, RPC_ADDOBSERVER__MISSIONOBSERVER_BOOL_, RPC_AWARDFACTIONPOINTS__, RPC_AWARDREWARD__, RPC_COMPLETE__, RPC_DEACTIVATE__, RPC_DESTROYOBJECTFROMDATABASE__, RPC_DROPOBSERVER__MISSIONOBSERVER_BOOL_, RPC_FAIL__, RPC_GETMISSIONOBJECT__, RPC_GETOBJECTIVETYPE__, RPC_GETOBSERVER__INT_, RPC_GETOBSERVERCOUNT__, RPC_GETPLAYEROWNER__, RPC_HASOBSERVERS__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_, RPC_REMOVEALLOBSERVERS__, and RPC_REMOVEMISSIONFROMPLAYER__.
int MissionObjectiveAdapter::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 717 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::removeAllObservers ()
Definition at line 733 of file MissionObjective.cpp.
Referenced by invokeMethod().
void MissionObjectiveAdapter::removeMissionFromPlayer ()
Definition at line 781 of file MissionObjective.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObjective.cpp