Core3: CharacterList Class Reference
CharacterList Class Reference
#include <CharacterList.h>
Public Member Functions
CharacterList (uint32 id)
~CharacterList ()
void update ()
Private Attributes
uint32 accountid
Detailed Description
Definition at line 54 of file CharacterList.h.
Constructor & Destructor Documentation
CharacterList::CharacterList (uint32 id) inline
Definition at line 59 of file CharacterList.h.
References accountid, and update().
CharacterList::~CharacterList () inline
Definition at line 64 of file CharacterList.h.
Member Function Documentation
void CharacterList::update () inline
Definition at line 68 of file CharacterList.h.
References accountid, ServerDatabase::instance(), CharacterListEntry::setAccountID(), CharacterListEntry::setBanAdmin(), CharacterListEntry::setBanExpiration(), CharacterListEntry::setBanReason(), CharacterListEntry::setCreationDate(), CharacterListEntry::setFirstName(), CharacterListEntry::setGalaxyID(), CharacterListEntry::setGalaxyName(), CharacterListEntry::setObjectID(), CharacterListEntry::setRace(), and CharacterListEntry::setSurName().
Referenced by CharacterList().
Member Data Documentation
uint32 CharacterList::accountid private
Definition at line 56 of file CharacterList.h.
Referenced by CharacterList(), and update().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/objects/CharacterList.h