Core3: IsVendorOwnerResponseMessage Class Reference
IsVendorOwnerResponseMessage Class Reference
#include <IsVendorOwnerResponseMessage.h>
Public Member Functions
IsVendorOwnerResponseMessage (SceneObject *vendor, CreatureObject *player, const String &planet, const String &region)
Detailed Description
Definition at line 55 of file IsVendorOwnerResponseMessage.h.
Constructor & Destructor Documentation
IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage (SceneObject * vendor, CreatureObject * player, const String & planet, const String & region) inline
Definition at line 58 of file IsVendorOwnerResponseMessage.h.
References server::zone::ZoneServer::getAuctionManager(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getObjectID(), VendorDataComponent::getOwnershipRightsOf(), server::zone::objects::scene::SceneObject::getWorldPositionX(), server::zone::objects::scene::SceneObject::getWorldPositionY(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::isBazaarTerminal(), server::zone::managers::auction::AuctionManager::isMarketEnabled(), VendorDataComponent::isOnStrike(), server::zone::objects::scene::SceneObject::isVendor(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/auction/IsVendorOwnerResponseMessage.h