Core3: FireworkShowMenuComponent Class Reference
FireworkShowMenuComponent Class Reference
#include <FireworkShowMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Private Member Functions
void startShow (CreatureObject *player, FireworkObject *firework)
void addEvent (CreatureObject *player, FireworkObject *firework)
Detailed Description
Definition at line 14 of file FireworkShowMenuComponent.h.
Member Function Documentation
void FireworkShowMenuComponent::addEvent (CreatureObject * player, FireworkObject * firework) private
Definition at line 87 of file FireworkShowMenuComponent.cpp.
Referenced by handleObjectMenuSelect().
void FireworkShowMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from TangibleObjectMenuComponent.
Definition at line 16 of file FireworkShowMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID(), TangibleObjectMenuComponent::fillObjectMenuResponse(), and server::zone::objects::scene::SceneObject::isFireworkObject().
int FireworkShowMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from TangibleObjectMenuComponent.
Definition at line 33 of file FireworkShowMenuComponent.cpp.
References addEvent(), server::zone::objects::scene::SceneObject::getZone(), TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::scene::SceneObject::isASubChildOf(), server::zone::objects::scene::SceneObject::isFireworkObject(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and startShow().
void FireworkShowMenuComponent::startShow (CreatureObject * player, FireworkObject * firework) private
Definition at line 73 of file FireworkShowMenuComponent.cpp.
Referenced by handleObjectMenuSelect().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/firework/components/FireworkShowMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/firework/components/FireworkShowMenuComponent.cpp