Core3: server::zone::ZoneServerImplementation Class Reference
server::zone::ZoneServerImplementation Class Reference
#include <ZoneServer.h>
Public Member Functions
ZoneServerImplementation (ConfigManager *config)
ZoneServerImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
ZoneClientSession * createConnection (Socket *sock, SocketAddress &addr)
void initialize ()
void shutdown ()
void startManagers ()
void startZones ()
void stopManagers ()
void start (int p, int mconn=10)
void stop ()
void timedShutdown (int minutes)
void handleMessage (ZoneClientSession *client, Packet *message)
void processMessage (Message *message)
bool handleError (ZoneClientSession *client, Exception &e)
void addTotalSentPacket (int count)
void addTotalResentPacket (int count)
void printInfo ()
String getInfo ()
void printEvents ()
Reference< SceneObject * > getObject (unsigned long long objectID, bool doLock=true)
Reference< SceneObject * > createObject (unsigned int templateCRC, const String &dbname, int persistenceLevel=2)
Reference< SceneObject * > createObject (unsigned int templateCRC, int persistenceLevel=2, unsigned long long objectID=0)
Reference< SceneObject * > createClientObject (unsigned int templateCRC, unsigned long long objectID=0)
void updateObjectToDatabase (SceneObject *object)
void updateObjectToStaticDatabase (SceneObject *object)
void destroyObjectFromDatabase (unsigned long long objectID)
void lock (bool doLock=true)
void unlock (bool doLock=true)
void fixScheduler ()
void changeUserCap (int amount=50)
int getConnectionCount ()
void increaseOnlinePlayers ()
void decreaseOnlinePlayers ()
void increaseTotalDeletedPlayers ()
int getGalaxyID ()
String getGalaxyName ()
void setGalaxyName (const String &name)
bool isServerLocked ()
bool isServerOnline ()
bool isServerOffline ()
bool isServerLoading ()
int getServerCap ()
int getServerState ()
Zone * getZone (const String &terrainName)
Zone * getZone (int idx)
int getZoneCount ()
int getMaxPlayers ()
int getTotalPlayers ()
int getDeletedPlayers ()
ObjectManager * getObjectManager ()
PlayerManager * getPlayerManager ()
ChatManager * getChatManager ()
CityManager * getCityManager ()
ObjectController * getObjectController ()
MissionManager * getMissionManager ()
RadialManager * getRadialManager ()
GuildManager * getGuildManager ()
ResourceManager * getResourceManager ()
CraftingManager * getCraftingManager ()
LootManager * getLootManager ()
AuctionManager * getAuctionManager ()
SkillManager * getSkillManager ()
Time * getStartTimestamp ()
void setGalaxyID (int galaxyid)
void setServerState (int state)
void setServerStateLocked ()
void setServerStateOnline ()
void loadLoginMessage ()
void changeLoginMessage (const String &motd)
String getLoginMessage ()
operator const ZoneServer * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< ZoneServer * > _this
Static Public Attributes
static const int OFFLINE = 0
static const int LOADING = 1
static const int ONLINE = 2
static const int LOCKED = 3
Protected Member Functions
virtual ~ZoneServerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Member Functions
void loadGalaxyName ()
Private Attributes
Reference
< DatagramServiceThread * > datagramService
Reference< BasePacketHandler * > phandler
Reference< ConfigManager * > configManager
Reference< ZoneHandler * > zoneHandler
ManagedReference
< ZoneProcessServer * > processor
Reference< VectorMap< String,
ManagedReference< Zone * > > * > zones
Reference< ObjectManager * > objectManager
ManagedReference< PlayerManager * > playerManager
ManagedReference< ChatManager * > chatManager
ManagedReference< RadialManager * > radialManager
ManagedReference< CityManager * > cityManager
ManagedReference
< ResourceManager * > resourceManager
ManagedReference
< CraftingManager * > craftingManager
ManagedReference< LootManager * > lootManager
ManagedReference
< AuctionManager * > auctionManager
ManagedReference
< MissionManager * > missionManager
ManagedReference< GuildManager * > guildManager
Reference< StringIdManager * > stringIdManager
Reference
< CreatureTemplateManager * > creatureTemplateManager
Reference< DnaManager * > dnaManager
int totalSentPackets
int serverCap
int totalResentPackets
AtomicInteger currentPlayers
AtomicInteger maximumPlayers
AtomicInteger totalPlayers
AtomicInteger totalDeletedPlayers
int serverState
String galaxyName
String loginMessage
int galaxyID
Time startTimestamp
Friends
class ZoneServer
Detailed Description
Definition at line 565 of file ZoneServer.h.
Constructor & Destructor Documentation
ZoneServerImplementation::ZoneServerImplementation (ConfigManager * config)
Definition at line 94 of file ZoneServerImplementation.cpp.
References chatManager, cityManager, configManager, craftingManager, creatureTemplateManager, currentPlayers, datagramService, galaxyID, galaxyName, server::conf::ConfigManager::getZoneGalaxyID(), guildManager, lootManager, maximumPlayers, objectManager, OFFLINE, phandler, playerManager, processor, radialManager, resourceManager, serverCap, serverState, stringIdManager, totalDeletedPlayers, totalPlayers, totalResentPackets, and totalSentPackets.
ZoneServerImplementation::ZoneServerImplementation (DummyConstructorParameter * param)
Definition at line 1001 of file ZoneServer.cpp.
References _initializeImplementation().
ZoneServerImplementation::~ZoneServerImplementation () protected virtual
Definition at line 1006 of file ZoneServer.cpp.
Member Function Documentation
DistributedObjectStub * ZoneServerImplementation::_getStub ()
Definition at line 1026 of file ZoneServer.cpp.
References _this.
void ZoneServerImplementation::_initializeImplementation () protected
Definition at line 1013 of file ZoneServer.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ZoneServerImplementation().
void ZoneServerImplementation::_serializationHelperMethod () protected
Definition at line 1034 of file ZoneServer.cpp.
Referenced by _initializeImplementation().
void ZoneServerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 1021 of file ZoneServer.cpp.
References _this.
Referenced by server::zone::ZoneServer::ZoneServer().
void ZoneServerImplementation::addTotalResentPacket (int count)
Definition at line 557 of file ZoneServerImplementation.cpp.
References totalResentPackets.
Referenced by server::zone::ZoneServer::addTotalResentPacket().
void ZoneServerImplementation::addTotalSentPacket (int count)
Definition at line 549 of file ZoneServerImplementation.cpp.
References totalSentPackets.
Referenced by server::zone::ZoneServer::addTotalSentPacket().
void ZoneServerImplementation::changeLoginMessage (const String & motd)
Definition at line 751 of file ZoneServerImplementation.cpp.
References _this, and loginMessage.
Referenced by server::zone::ZoneServer::changeLoginMessage().
void ZoneServerImplementation::changeUserCap (int amount = 50)
Definition at line 538 of file ZoneServerImplementation.cpp.
References lock(), serverCap, and unlock().
Referenced by server::zone::ZoneServer::changeUserCap().
Reference< SceneObject * > ZoneServerImplementation::createClientObject (unsigned int templateCRC, unsigned long long objectID = 0)
Definition at line 514 of file ZoneServerImplementation.cpp.
References objectManager.
Referenced by server::zone::ZoneServer::createClientObject().
ZoneClientSession * ZoneServerImplementation::createConnection (Socket * sock, SocketAddress & addr)
Definition at line 372 of file ZoneServerImplementation.cpp.
References datagramService.
Referenced by server::zone::ZoneServer::createConnection().
Reference<SceneObject* > server::zone::ZoneServerImplementation::createObject (unsigned int templateCRC, const String & dbname, int persistenceLevel = 2)
Referenced by server::zone::ZoneServer::createObject().
Reference<SceneObject* > server::zone::ZoneServerImplementation::createObject (unsigned int templateCRC, int persistenceLevel = 2, unsigned long long objectID = 0)
void ZoneServerImplementation::decreaseOnlinePlayers ()
Definition at line 681 of file ZoneServerImplementation.cpp.
References currentPlayers.
Referenced by server::zone::ZoneServer::decreaseOnlinePlayers().
void ZoneServerImplementation::destroyObjectFromDatabase (unsigned long long objectID)
Definition at line 534 of file ZoneServerImplementation.cpp.
References objectManager.
Referenced by server::zone::ZoneServer::destroyObjectFromDatabase().
void ZoneServerImplementation::finalize () protected
Definition at line 1010 of file ZoneServer.cpp.
void ZoneServerImplementation::fixScheduler ()
Definition at line 1363 of file ZoneServer.cpp.
Referenced by server::zone::ZoneServer::fixScheduler().
AuctionManager * ZoneServerImplementation::getAuctionManager ()
Definition at line 1496 of file ZoneServer.cpp.
References auctionManager.
Referenced by server::zone::ZoneServer::getAuctionManager().
ChatManager * ZoneServerImplementation::getChatManager ()
Definition at line 1451 of file ZoneServer.cpp.
References chatManager.
Referenced by server::zone::ZoneServer::getChatManager(), and timedShutdown().
CityManager * ZoneServerImplementation::getCityManager ()
Definition at line 1456 of file ZoneServer.cpp.
References cityManager.
Referenced by server::zone::ZoneServer::getCityManager().
int ZoneServerImplementation::getConnectionCount ()
Definition at line 565 of file ZoneServerImplementation.cpp.
References currentPlayers.
Referenced by server::zone::ZoneServer::getConnectionCount().
CraftingManager * ZoneServerImplementation::getCraftingManager ()
Definition at line 1486 of file ZoneServer.cpp.
References craftingManager.
Referenced by server::zone::ZoneServer::getCraftingManager().
int ZoneServerImplementation::getDeletedPlayers ()
Definition at line 1436 of file ZoneServer.cpp.
References totalDeletedPlayers.
Referenced by server::zone::ZoneServer::getDeletedPlayers().
int ZoneServerImplementation::getGalaxyID ()
Definition at line 1366 of file ZoneServer.cpp.
References galaxyID.
Referenced by server::zone::ZoneServer::getGalaxyID().
String ZoneServerImplementation::getGalaxyName ()
Definition at line 1371 of file ZoneServer.cpp.
References galaxyName.
Referenced by server::zone::ZoneServer::getGalaxyName().
GuildManager * ZoneServerImplementation::getGuildManager ()
Definition at line 1476 of file ZoneServer.cpp.
References guildManager.
Referenced by server::zone::ZoneServer::getGuildManager().
String ZoneServerImplementation::getInfo ()
Definition at line 617 of file ZoneServerImplementation.cpp.
References currentPlayers, server::zone::managers::creature::CreatureManager::getSpawnedRandomCreatures(), lock(), maximumPlayers, totalDeletedPlayers, totalPlayers, totalResentPackets, totalSentPackets, unlock(), and zones.
Referenced by server::zone::ZoneServer::getInfo().
String ZoneServerImplementation::getLoginMessage ()
Definition at line 722 of file ZoneServerImplementation.cpp.
References loginMessage.
Referenced by server::zone::ZoneServer::getLoginMessage().
LootManager * ZoneServerImplementation::getLootManager ()
Definition at line 1491 of file ZoneServer.cpp.
References lootManager.
Referenced by server::zone::ZoneServer::getLootManager().
int ZoneServerImplementation::getMaxPlayers ()
Definition at line 1426 of file ZoneServer.cpp.
References maximumPlayers.
Referenced by server::zone::ZoneServer::getMaxPlayers().
MissionManager * ZoneServerImplementation::getMissionManager ()
Definition at line 1466 of file ZoneServer.cpp.
References missionManager.
Referenced by server::zone::ZoneServer::getMissionManager().
Reference< SceneObject * > ZoneServerImplementation::getObject (unsigned long long objectID, bool doLock = true)
Definition at line 441 of file ZoneServerImplementation.cpp.
Referenced by server::zone::ZoneServer::getObject().
ObjectController * ZoneServerImplementation::getObjectController ()
Definition at line 1461 of file ZoneServer.cpp.
References processor.
Referenced by server::zone::ZoneServer::getObjectController().
ObjectManager * ZoneServerImplementation::getObjectManager ()
Definition at line 1441 of file ZoneServer.cpp.
References objectManager.
Referenced by server::zone::ZoneServer::getObjectManager().
PlayerManager * ZoneServerImplementation::getPlayerManager ()
Definition at line 1446 of file ZoneServer.cpp.
References playerManager.
Referenced by server::zone::ZoneServer::getPlayerManager().
RadialManager * ZoneServerImplementation::getRadialManager ()
Definition at line 1471 of file ZoneServer.cpp.
References radialManager.
Referenced by server::zone::ZoneServer::getRadialManager().
ResourceManager * ZoneServerImplementation::getResourceManager ()
Definition at line 1481 of file ZoneServer.cpp.
References resourceManager.
Referenced by server::zone::ZoneServer::getResourceManager().
int ZoneServerImplementation::getServerCap ()
Definition at line 1401 of file ZoneServer.cpp.
References serverCap.
Referenced by server::zone::ZoneServer::getServerCap().
int ZoneServerImplementation::getServerState ()
Definition at line 1406 of file ZoneServer.cpp.
References serverState.
Referenced by server::zone::ZoneServer::getServerState().
SkillManager * ZoneServerImplementation::getSkillManager ()
Definition at line 1501 of file ZoneServer.cpp.
References processor.
Referenced by server::zone::ZoneServer::getSkillManager().
Time * ZoneServerImplementation::getStartTimestamp ()
Definition at line 1506 of file ZoneServer.cpp.
References startTimestamp.
Referenced by server::zone::ZoneServer::getStartTimestamp().
int ZoneServerImplementation::getTotalPlayers ()
Definition at line 1431 of file ZoneServer.cpp.
References totalPlayers.
Referenced by server::zone::ZoneServer::getTotalPlayers().
Zone * ZoneServerImplementation::getZone (const String & terrainName)
Definition at line 1411 of file ZoneServer.cpp.
References zones.
Referenced by server::zone::ZoneServer::getZone().
Zone * ZoneServerImplementation::getZone (int idx)
Gets a note based on it's position in the zone map. NOTE: This idx is not to be considered consistent.
Parameters
idx The index in the map to get the zone.
Definition at line 1416 of file ZoneServer.cpp.
References zones.
int ZoneServerImplementation::getZoneCount ()
Definition at line 1421 of file ZoneServer.cpp.
References zones.
Referenced by server::zone::ZoneServer::getZoneCount().
bool ZoneServerImplementation::handleError (ZoneClientSession * client, Exception & e)
Definition at line 433 of file ZoneServerImplementation.cpp.
References server::zone::ZoneClientSession::disconnect(), and server::zone::ZoneClientSession::getSession().
Referenced by server::zone::ZoneServer::handleError().
void ZoneServerImplementation::handleMessage (ZoneClientSession * client, Packet * message)
Definition at line 398 of file ZoneServerImplementation.cpp.
References server::zone::ZoneClientSession::getSession(), and phandler.
Referenced by server::zone::ZoneServer::handleMessage().
void ZoneServerImplementation::increaseOnlinePlayers ()
Definition at line 672 of file ZoneServerImplementation.cpp.
References currentPlayers, maximumPlayers, and totalPlayers.
Referenced by server::zone::ZoneServer::increaseOnlinePlayers().
void ZoneServerImplementation::increaseTotalDeletedPlayers ()
Definition at line 685 of file ZoneServerImplementation.cpp.
References totalDeletedPlayers.
Referenced by server::zone::ZoneServer::increaseTotalDeletedPlayers().
void ZoneServerImplementation::initialize ()
Definition at line 165 of file ZoneServerImplementation.cpp.
References _this, auctionManager, chatManager, cityManager, craftingManager, creatureTemplateManager, dnaManager, loadGalaxyName(), LOADING, lootManager, missionManager, objectManager, ONLINE, phandler, playerManager, processor, resourceManager, serverState, startManagers(), startZones(), stringIdManager, zoneHandler, and zones.
Referenced by server::zone::ZoneServer::initialize().
void ZoneServerImplementation::initializeTransientMembers ()
Definition at line 139 of file ZoneServerImplementation.cpp.
References objectManager, and phandler.
Referenced by server::zone::ZoneServer::initializeTransientMembers(), and readObject().
bool ZoneServerImplementation::isServerLoading ()
Definition at line 1396 of file ZoneServer.cpp.
References LOADING, and serverState.
Referenced by server::zone::ZoneServer::isServerLoading().
bool ZoneServerImplementation::isServerLocked ()
Definition at line 1381 of file ZoneServer.cpp.
References LOCKED, and serverState.
Referenced by server::zone::ZoneServer::isServerLocked().
bool ZoneServerImplementation::isServerOffline ()
Definition at line 1391 of file ZoneServer.cpp.
References OFFLINE, and serverState.
Referenced by server::zone::ZoneServer::isServerOffline().
bool ZoneServerImplementation::isServerOnline ()
Definition at line 1386 of file ZoneServer.cpp.
References ONLINE, and serverState.
Referenced by server::zone::ZoneServer::isServerOnline().
void ZoneServerImplementation::loadGalaxyName () private
Definition at line 147 of file ZoneServerImplementation.cpp.
References galaxyID, galaxyName, ServerDatabase::instance(), and loadLoginMessage().
Referenced by initialize().
void ZoneServerImplementation::loadLoginMessage ()
Definition at line 726 of file ZoneServerImplementation.cpp.
References _this, and loginMessage.
Referenced by loadGalaxyName(), and server::zone::ZoneServer::loadLoginMessage().
void ZoneServerImplementation::lock (bool doLock = true)
Definition at line 689 of file ZoneServerImplementation.cpp.
References datagramService.
Referenced by changeUserCap(), getInfo(), server::zone::ZoneServer::lock(), printEvents(), and printInfo().
ZoneServerImplementation::operator const ZoneServer * ()
Definition at line 1030 of file ZoneServer.cpp.
void ZoneServerImplementation::printEvents ()
Definition at line 664 of file ZoneServerImplementation.cpp.
References lock(), and unlock().
Referenced by server::zone::ZoneServer::printEvents().
void ZoneServerImplementation::printInfo ()
Definition at line 569 of file ZoneServerImplementation.cpp.
References currentPlayers, server::zone::managers::creature::CreatureManager::getSpawnedRandomCreatures(), lock(), maximumPlayers, playerManager, totalDeletedPlayers, totalPlayers, totalResentPackets, totalSentPackets, unlock(), and zones.
Referenced by server::zone::ZoneServer::printInfo(), and shutdown().
void ZoneServerImplementation::processMessage (Message * message)
Definition at line 419 of file ZoneServerImplementation.cpp.
References server::zone::ZonePacketHandler::generateMessageTask(), processor, and zoneHandler.
Referenced by server::zone::ZoneServer::processMessage().
void ZoneServerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 1041 of file ZoneServer.cpp.
References initializeTransientMembers(), and readObjectMember().
bool ZoneServerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 1060 of file ZoneServer.cpp.
References auctionManager, chatManager, cityManager, craftingManager, currentPlayers, galaxyID, galaxyName, guildManager, loginMessage, lootManager, maximumPlayers, missionManager, playerManager, radialManager, resourceManager, serverCap, serverState, startTimestamp, totalDeletedPlayers, totalPlayers, totalResentPackets, totalSentPackets, and zones.
Referenced by readObject().
void server::zone::ZoneServerImplementation::rlock (bool doLock = true) protected
void server::zone::ZoneServerImplementation::runlock (bool doLock = true) protected
void ZoneServerImplementation::setGalaxyID (int galaxyid)
Definition at line 1511 of file ZoneServer.cpp.
References galaxyID.
Referenced by server::zone::ZoneServer::setGalaxyID().
void ZoneServerImplementation::setGalaxyName (const String & name)
Definition at line 1376 of file ZoneServer.cpp.
References galaxyName.
Referenced by server::zone::ZoneServer::setGalaxyName().
void ZoneServerImplementation::setServerState (int state)
Definition at line 1516 of file ZoneServer.cpp.
References serverState.
Referenced by server::zone::ZoneServer::setServerState().
void ZoneServerImplementation::setServerStateLocked ()
Definition at line 702 of file ZoneServerImplementation.cpp.
References _this, LOCKED, and serverState.
Referenced by server::zone::ZoneServer::setServerStateLocked().
void ZoneServerImplementation::setServerStateOnline ()
Definition at line 712 of file ZoneServerImplementation.cpp.
References _this, ONLINE, and serverState.
Referenced by server::zone::ZoneServer::setServerStateOnline().
void ZoneServerImplementation::shutdown ()
Definition at line 326 of file ZoneServerImplementation.cpp.
References printInfo(), stopManagers(), and zones.
Referenced by server::zone::ZoneServer::shutdown().
void ZoneServerImplementation::start (int p, int mconn = 10)
Definition at line 299 of file ZoneServerImplementation.cpp.
References _this, datagramService, and zoneHandler.
Referenced by server::zone::ZoneServer::start().
void ZoneServerImplementation::startManagers ()
Definition at line 275 of file ZoneServerImplementation.cpp.
References _this, auctionManager, chatManager, cityManager, guildManager, processor, and radialManager.
Referenced by initialize(), and server::zone::ZoneServer::startManagers().
void ZoneServerImplementation::startZones ()
Definition at line 234 of file ZoneServerImplementation.cpp.
References _this, configManager, server::zone::Zone::createContainerComponent(), server::zone::Zone::hasManagersStarted(), server::zone::Zone::initializePrivateData(), processor, resourceManager, StructureManager::setZoneServer(), and zones.
Referenced by initialize(), and server::zone::ZoneServer::startZones().
void ZoneServerImplementation::stop ()
Definition at line 311 of file ZoneServerImplementation.cpp.
References datagramService.
Referenced by server::zone::ZoneServer::stop().
void ZoneServerImplementation::stopManagers ()
Definition at line 351 of file ZoneServerImplementation.cpp.
References auctionManager, chatManager, cityManager, craftingManager, guildManager, lootManager, missionManager, playerManager, radialManager, and resourceManager.
Referenced by shutdown(), and server::zone::ZoneServer::stopManagers().
void ZoneServerImplementation::timedShutdown (int minutes)
Definition at line 316 of file ZoneServerImplementation.cpp.
References _this, server::chat::ChatManager::broadcastGalaxy(), and getChatManager().
Referenced by server::zone::ZoneServer::timedShutdown().
void ZoneServerImplementation::unlock (bool doLock = true)
Definition at line 698 of file ZoneServerImplementation.cpp.
References datagramService.
Referenced by changeUserCap(), getInfo(), printEvents(), printInfo(), and server::zone::ZoneServer::unlock().
void ZoneServerImplementation::updateObjectToDatabase (SceneObject * object)
Definition at line 468 of file ZoneServerImplementation.cpp.
References objectManager.
Referenced by server::zone::ZoneServer::updateObjectToDatabase().
void ZoneServerImplementation::updateObjectToStaticDatabase (SceneObject * object)
Definition at line 472 of file ZoneServerImplementation.cpp.
References objectManager.
Referenced by server::zone::ZoneServer::updateObjectToStaticDatabase().
void server::zone::ZoneServerImplementation::wlock (bool doLock = true) protected
void server::zone::ZoneServerImplementation::wlock (ManagedObject * obj) protected
void ZoneServerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 1162 of file ZoneServer.cpp.
References writeObjectMembers().
int ZoneServerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 1169 of file ZoneServer.cpp.
References auctionManager, chatManager, cityManager, craftingManager, currentPlayers, galaxyID, galaxyName, guildManager, loginMessage, lootManager, maximumPlayers, missionManager, playerManager, radialManager, resourceManager, serverCap, serverState, startTimestamp, totalDeletedPlayers, totalPlayers, totalResentPackets, totalSentPackets, and zones.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ZoneServer friend
Definition at line 818 of file ZoneServer.h.
Member Data Documentation
WeakReference<ZoneServer*> server::zone::ZoneServerImplementation::_this
Definition at line 790 of file ZoneServer.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), changeLoginMessage(), initialize(), loadLoginMessage(), setServerStateLocked(), setServerStateOnline(), start(), startManagers(), startZones(), and timedShutdown().
ManagedReference<AuctionManager* > server::zone::ZoneServerImplementation::auctionManager private
Definition at line 594 of file ZoneServer.h.
Referenced by getAuctionManager(), initialize(), readObjectMember(), startManagers(), stopManagers(), and writeObjectMembers().
ManagedReference<ChatManager* > server::zone::ZoneServerImplementation::chatManager private
Definition at line 582 of file ZoneServer.h.
Referenced by getChatManager(), initialize(), readObjectMember(), startManagers(), stopManagers(), writeObjectMembers(), and ZoneServerImplementation().
ManagedReference<CityManager* > server::zone::ZoneServerImplementation::cityManager private
Definition at line 586 of file ZoneServer.h.
Referenced by getCityManager(), initialize(), readObjectMember(), startManagers(), stopManagers(), writeObjectMembers(), and ZoneServerImplementation().
Reference<ConfigManager* > server::zone::ZoneServerImplementation::configManager private
Definition at line 570 of file ZoneServer.h.
Referenced by startZones(), and ZoneServerImplementation().
ManagedReference<CraftingManager* > server::zone::ZoneServerImplementation::craftingManager private
Definition at line 590 of file ZoneServer.h.
Referenced by getCraftingManager(), initialize(), readObjectMember(), stopManagers(), writeObjectMembers(), and ZoneServerImplementation().
Reference<CreatureTemplateManager* > server::zone::ZoneServerImplementation::creatureTemplateManager private
Definition at line 602 of file ZoneServer.h.
Referenced by initialize(), and ZoneServerImplementation().
AtomicInteger server::zone::ZoneServerImplementation::currentPlayers private
Definition at line 612 of file ZoneServer.h.
Referenced by decreaseOnlinePlayers(), getConnectionCount(), getInfo(), increaseOnlinePlayers(), printInfo(), readObjectMember(), writeObjectMembers(), and ZoneServerImplementation().
Reference<DatagramServiceThread* > server::zone::ZoneServerImplementation::datagramService private
Definition at line 566 of file ZoneServer.h.
Referenced by createConnection(), lock(), start(), stop(), unlock(), and ZoneServerImplementation().
Reference<DnaManager* > server::zone::ZoneServerImplementation::dnaManager private
Definition at line 604 of file ZoneServer.h.
Referenced by initialize().
int server::zone::ZoneServerImplementation::galaxyID private
Definition at line 626 of file ZoneServer.h.
Referenced by getGalaxyID(), loadGalaxyName(), readObjectMember(), setGalaxyID(), writeObjectMembers(), and ZoneServerImplementation().
String server::zone::ZoneServerImplementation::galaxyName private
Definition at line 622 of file ZoneServer.h.
Referenced by getGalaxyName(), loadGalaxyName(), readObjectMember(), setGalaxyName(), writeObjectMembers(), and ZoneServerImplementation().
ManagedReference<GuildManager* > server::zone::ZoneServerImplementation::guildManager private
Definition at line 598 of file ZoneServer.h.
Referenced by getGuildManager(), readObjectMember(), startManagers(), stopManagers(), writeObjectMembers(), and ZoneServerImplementation().
const int server::zone::ZoneServerImplementation::LOADING = 1 static
Definition at line 633 of file ZoneServer.h.
Referenced by initialize(), and isServerLoading().
const int server::zone::ZoneServerImplementation::LOCKED = 3 static
Definition at line 637 of file ZoneServer.h.
Referenced by isServerLocked(), and setServerStateLocked().
String server::zone::ZoneServerImplementation::loginMessage private
Definition at line 624 of file ZoneServer.h.
Referenced by changeLoginMessage(), getLoginMessage(), loadLoginMessage(), readObjectMember(), and writeObjectMembers().
ManagedReference<LootManager* > server::zone::ZoneServerImplementation::lootManager private
Definition at line 592 of file ZoneServer.h.
Referenced by getLootManager(), initialize(), readObjectMember(), stopManagers(), writeObjectMembers(), and ZoneServerImplementation().
AtomicInteger server::zone::ZoneServerImplementation::maximumPlayers private
Definition at line 614 of file ZoneServer.h.
Referenced by getInfo(), getMaxPlayers(), increaseOnlinePlayers(), printInfo(), readObjectMember(), writeObjectMembers(), and ZoneServerImplementation().
ManagedReference<MissionManager* > server::zone::ZoneServerImplementation::missionManager private
Definition at line 596 of file ZoneServer.h.
Referenced by getMissionManager(), initialize(), readObjectMember(), stopManagers(), and writeObjectMembers().
Reference<ObjectManager* > server::zone::ZoneServerImplementation::objectManager private
Definition at line 578 of file ZoneServer.h.
Referenced by createClientObject(), destroyObjectFromDatabase(), getObjectManager(), initialize(), initializeTransientMembers(), updateObjectToDatabase(), updateObjectToStaticDatabase(), and ZoneServerImplementation().
const int server::zone::ZoneServerImplementation::OFFLINE = 0 static
Definition at line 631 of file ZoneServer.h.
Referenced by isServerOffline(), and ZoneServerImplementation().
const int server::zone::ZoneServerImplementation::ONLINE = 2 static
Definition at line 635 of file ZoneServer.h.
Referenced by initialize(), isServerOnline(), and setServerStateOnline().
Reference<BasePacketHandler* > server::zone::ZoneServerImplementation::phandler private
Definition at line 568 of file ZoneServer.h.
Referenced by handleMessage(), initialize(), initializeTransientMembers(), and ZoneServerImplementation().
ManagedReference<PlayerManager* > server::zone::ZoneServerImplementation::playerManager private
Definition at line 580 of file ZoneServer.h.
Referenced by getPlayerManager(), initialize(), printInfo(), readObjectMember(), stopManagers(), writeObjectMembers(), and ZoneServerImplementation().
ManagedReference<ZoneProcessServer* > server::zone::ZoneServerImplementation::processor private
Definition at line 574 of file ZoneServer.h.
Referenced by getObjectController(), getSkillManager(), initialize(), processMessage(), startManagers(), startZones(), and ZoneServerImplementation().
ManagedReference<RadialManager* > server::zone::ZoneServerImplementation::radialManager private
Definition at line 584 of file ZoneServer.h.
Referenced by getRadialManager(), readObjectMember(), startManagers(), stopManagers(), writeObjectMembers(), and ZoneServerImplementation().
ManagedReference<ResourceManager* > server::zone::ZoneServerImplementation::resourceManager private
Definition at line 588 of file ZoneServer.h.
Referenced by getResourceManager(), initialize(), readObjectMember(), startZones(), stopManagers(), writeObjectMembers(), and ZoneServerImplementation().
int server::zone::ZoneServerImplementation::serverCap private
Definition at line 608 of file ZoneServer.h.
Referenced by changeUserCap(), getServerCap(), readObjectMember(), writeObjectMembers(), and ZoneServerImplementation().
int server::zone::ZoneServerImplementation::serverState private
Definition at line 620 of file ZoneServer.h.
Referenced by getServerState(), initialize(), isServerLoading(), isServerLocked(), isServerOffline(), isServerOnline(), readObjectMember(), setServerState(), setServerStateLocked(), setServerStateOnline(), writeObjectMembers(), and ZoneServerImplementation().
Time server::zone::ZoneServerImplementation::startTimestamp private
Definition at line 628 of file ZoneServer.h.
Referenced by getStartTimestamp(), readObjectMember(), and writeObjectMembers().
Reference<StringIdManager* > server::zone::ZoneServerImplementation::stringIdManager private
Definition at line 600 of file ZoneServer.h.
Referenced by initialize(), and ZoneServerImplementation().
AtomicInteger server::zone::ZoneServerImplementation::totalDeletedPlayers private
Definition at line 618 of file ZoneServer.h.
Referenced by getDeletedPlayers(), getInfo(), increaseTotalDeletedPlayers(), printInfo(), readObjectMember(), writeObjectMembers(), and ZoneServerImplementation().
AtomicInteger server::zone::ZoneServerImplementation::totalPlayers private
Definition at line 616 of file ZoneServer.h.
Referenced by getInfo(), getTotalPlayers(), increaseOnlinePlayers(), printInfo(), readObjectMember(), writeObjectMembers(), and ZoneServerImplementation().
int server::zone::ZoneServerImplementation::totalResentPackets private
Definition at line 610 of file ZoneServer.h.
Referenced by addTotalResentPacket(), getInfo(), printInfo(), readObjectMember(), writeObjectMembers(), and ZoneServerImplementation().
int server::zone::ZoneServerImplementation::totalSentPackets private
Definition at line 606 of file ZoneServer.h.
Referenced by addTotalSentPacket(), getInfo(), printInfo(), readObjectMember(), writeObjectMembers(), and ZoneServerImplementation().
Reference<ZoneHandler* > server::zone::ZoneServerImplementation::zoneHandler private
Definition at line 572 of file ZoneServer.h.
Referenced by initialize(), processMessage(), and start().
Reference<VectorMap<String, ManagedReference<Zone* > >* > server::zone::ZoneServerImplementation::zones private
Definition at line 576 of file ZoneServer.h.
Referenced by getInfo(), getZone(), getZoneCount(), initialize(), printInfo(), readObjectMember(), shutdown(), startZones(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneServer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneServer.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneServerImplementation.cpp