Core3: GroupManager Class Reference
GroupManager Class Reference
#include <GroupManager.h>
Public Member Functions
GroupManager ()
void inviteToGroup (CreatureObject *leader, CreatureObject *player)
void joinGroup (CreatureObject *player)
void kickFromGroup (ManagedReference< GroupObject * > group, CreatureObject *player, CreatureObject *playerToKick)
void leaveGroup (ManagedReference< GroupObject * > group, CreatureObject *player)
void makeLeader (GroupObject *group, CreatureObject *player, CreatureObject *newLeader)
void disbandGroup (ManagedReference< GroupObject * > group, CreatureObject *player)
GroupObject * createGroup (CreatureObject *leader)
Detailed Description
Definition at line 83 of file GroupManager.h.
Constructor & Destructor Documentation
GroupManager::GroupManager ()
Definition at line 62 of file GroupManager.cpp.
Member Function Documentation
GroupObject * GroupManager::createGroup (CreatureObject * leader)
Definition at line 223 of file GroupManager.cpp.
References server::zone::objects::player::PlayerObject::clearCharacterBit(), SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::creature::CreatureObject::getGroupInviterID(), server::zone::objects::player::sessions::EntertainingSession::getPerformanceName(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneServer(), server::zone::objects::creature::CreatureObject::isPlayingMusic(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::player::sessions::EntertainingSession::stopPlayingMusic(), server::zone::objects::creature::CreatureObject::updateGroup(), and server::zone::objects::creature::CreatureObject::updateGroupInviterID().
Referenced by joinGroup().
void GroupManager::disbandGroup (ManagedReference< GroupObject * > group, CreatureObject * player)
Definition at line 357 of file GroupManager.cpp.
References server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by DisbandCommand::doQueueCommand().
void GroupManager::inviteToGroup (CreatureObject * leader, CreatureObject * player)
Definition at line 65 of file GroupManager.cpp.
References server::zone::objects::creature::CreatureObject::getCreatureName(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::creature::CreatureObject::getGroupInviterID(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::isGrouped(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTT(), and server::zone::objects::creature::CreatureObject::updateGroupInviterID().
Referenced by InviteCommand::doQueueCommand().
void GroupManager::joinGroup (CreatureObject * player)
Definition at line 129 of file GroupManager.cpp.
References server::zone::objects::player::PlayerObject::clearCharacterBit(), createGroup(), SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::creature::CreatureObject::getGroupInviterID(), server::zone::ZoneServer::getObject(), server::zone::objects::player::sessions::EntertainingSession::getPerformanceName(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneServer(), server::zone::objects::scene::SceneObject::info(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isPlayingMusic(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setTT(), server::chat::StringIdChatParameter::setTU(), server::zone::objects::creature::CreatureObject::updateGroup(), and server::zone::objects::creature::CreatureObject::updateGroupInviterID().
Referenced by JoinCommand::doQueueCommand().
void GroupManager::kickFromGroup (ManagedReference< GroupObject * > group, CreatureObject * player, CreatureObject * playerToKick)
Definition at line 395 of file GroupManager.cpp.
References server::zone::objects::scene::SceneObject::info(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::sendDestroyTo(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::objects::creature::CreatureObject::updateGroup().
Referenced by DismissGroupMemberCommand::doQueueCommand().
void GroupManager::leaveGroup (ManagedReference< GroupObject * > group, CreatureObject * player)
Definition at line 305 of file GroupManager.cpp.
References server::chat::room::ChatRoom::getParent(), server::zone::objects::scene::SceneObject::info(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::chat::room::ChatRoom::removePlayer(), server::chat::room::ChatRoom::sendDestroyTo(), server::zone::objects::scene::SceneObject::sendDestroyTo(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::objects::creature::CreatureObject::updateGroup().
Referenced by DisbandCommand::doQueueCommand(), and LeaveGroupCommand::doQueueCommand().
void GroupManager::makeLeader (GroupObject * group, CreatureObject * player, CreatureObject * newLeader)
Definition at line 480 of file GroupManager.cpp.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::group::GroupObject::getGroupMember(), server::zone::objects::group::GroupObject::getGroupSize(), server::zone::objects::group::GroupObject::getLeader(), server::zone::objects::group::GroupObject::hasMember(), server::zone::objects::creature::CreatureObject::isOnline(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::group::GroupObject::makeLeader(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by MakeLeaderCommand::doQueueCommand().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/group/GroupManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/group/GroupManager.cpp