Core3: FloorMesh Class Reference
FloorMesh Class Reference
#include <FloorMesh.h>
Public Member Functions
FloorMesh ()
~FloorMesh ()
void readObject (IffStream *iffStream)
void parseBTRE (IffStream *iffStream)
void parseBEDG (IffStream *iffStream)
void parsePGRF (IffStream *iffStream)
void parseVersion0006 (IffStream *iffStream)
void parseVersion0005 (IffStream *iffStream)
Vector< TriangleNode * > * getNeighbors (uint32 triangleID)
TriangleNode * findNearestTriangle (const Vector3 &point)
bool testCollide (float x, float z, float y, float radius)
PathNode * getGlobalNode (int globalID)
PathGraph * getPathGraph ()
AABBTree * getAABBTree ()
Vert * getVertex (int vert)
int getCellID ()
void setCellID (int id)
float calculateManhattanDistance (TriangleNode *node1, TriangleNode *node2)
Public Member Functions inherited from IffTemplate
virtual ~IffTemplate ()
Public Member Functions inherited from TemplateData
virtual ~TemplateData ()
Private Attributes
Vector< Vert > vertices
Vector< FloorMeshTriangleNode * > tris
PathGraph * pathGraph
AABBTree * aabbTree
int cellID
Detailed Description
Definition at line 176 of file FloorMesh.h.
Constructor & Destructor Documentation
FloorMesh::FloorMesh ()
Definition at line 48 of file FloorMesh.cpp.
References aabbTree, cellID, and pathGraph.
FloorMesh::~FloorMesh ()
Definition at line 56 of file FloorMesh.cpp.
References aabbTree, pathGraph, and tris.
Member Function Documentation
float FloorMesh::calculateManhattanDistance (TriangleNode * node1, TriangleNode * node2) inline
Definition at line 230 of file FloorMesh.h.
TriangleNode * FloorMesh::findNearestTriangle (const Vector3 & point)
Definition at line 132 of file FloorMesh.cpp.
References tris.
Referenced by CollisionManager::getTriangle().
AABBTree* FloorMesh::getAABBTree () inline
Definition at line 211 of file FloorMesh.h.
References aabbTree.
Referenced by CollisionManager::getCellFloorCollision(), CollisionManager::getTriangle(), and CollisionManager::getWorldFloorCollision().
int FloorMesh::getCellID () inline
Definition at line 219 of file FloorMesh.h.
References cellID.
Referenced by PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), PathFinderManager::findPathFromWorldToCell(), and PathNode::getID().
PathNode * FloorMesh::getGlobalNode (int globalID)
Definition at line 335 of file FloorMesh.cpp.
References PathGraph::findGlobalNode(), and pathGraph.
Referenced by PortalLayout::getFloorMeshID().
Vector< TriangleNode * > * FloorMesh::getNeighbors (uint32 triangleID)
Definition at line 126 of file FloorMesh.cpp.
References tris.
PathGraph* FloorMesh::getPathGraph () inline
Definition at line 207 of file FloorMesh.h.
References pathGraph.
Referenced by PortalLayout::connectFloorMeshGraphs(), CollisionManager::findNearestPathNode(), PathFinderManager::findPathFromCellToCell(), PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), PathFinderManager::findPathFromWorldToCell(), and FleeStateComponent::getFleeLocation().
Vert* FloorMesh::getVertex (int vert) inline
Definition at line 215 of file FloorMesh.h.
References vertices.
Referenced by FloorMeshTriangleNode::readObject().
void FloorMesh::parseBEDG (IffStream * iffStream)
Definition at line 293 of file FloorMesh.cpp.
References Bedg::getTriangleID(), Bedg::readObject(), and tris.
Referenced by parseVersion0005(), and parseVersion0006().
void FloorMesh::parseBTRE (IffStream * iffStream)
Definition at line 259 of file FloorMesh.cpp.
Referenced by parseVersion0005(), and parseVersion0006().
void FloorMesh::parsePGRF (IffStream * iffStream)
Definition at line 313 of file FloorMesh.cpp.
References pathGraph, and PathGraph::readObject().
Referenced by parseVersion0005(), and parseVersion0006().
void FloorMesh::parseVersion0005 (IffStream * iffStream)
Definition at line 159 of file FloorMesh.cpp.
References parseBEDG(), parseBTRE(), parsePGRF(), Vert::readObject(), FloorMeshTriangleNode::readObject(), tris, and vertices.
Referenced by readObject().
void FloorMesh::parseVersion0006 (IffStream * iffStream)
Definition at line 211 of file FloorMesh.cpp.
References parseBEDG(), parseBTRE(), parsePGRF(), Vert::readObject(), FloorMeshTriangleNode::readObject(), tris, and vertices.
Referenced by readObject().
void FloorMesh::readObject (IffStream * iffStream) virtual
Implements IffTemplate.
Definition at line 69 of file FloorMesh.cpp.
References aabbTree, FloorMeshTriangleNode::addNeighbor(), FloorMeshTriangleNode::getNorthEastTriangle(), FloorMeshTriangleNode::getNorthWestTriangle(), FloorMeshTriangleNode::getSouthTriangle(), FloorMeshTriangleNode::hasNorthEastTriangle(), FloorMeshTriangleNode::hasNorthWestTriangle(), FloorMeshTriangleNode::hasSouthTriangle(), parseVersion0005(), parseVersion0006(), tris, and vertices.
Referenced by TemplateManager::getFloorMesh().
void FloorMesh::setCellID (int id) inline
Definition at line 223 of file FloorMesh.h.
References cellID.
Referenced by PortalLayout::parseCELSForm().
bool FloorMesh::testCollide (float x, float z, float y, float radius)
Definition at line 339 of file FloorMesh.cpp.
References aabbTree.
Member Data Documentation
AABBTree* FloorMesh::aabbTree private
Definition at line 184 of file FloorMesh.h.
Referenced by FloorMesh(), getAABBTree(), readObject(), testCollide(), and ~FloorMesh().
int FloorMesh::cellID private
Definition at line 186 of file FloorMesh.h.
Referenced by FloorMesh(), getCellID(), and setCellID().
PathGraph* FloorMesh::pathGraph private
Definition at line 182 of file FloorMesh.h.
Referenced by FloorMesh(), getGlobalNode(), getPathGraph(), parsePGRF(), and ~FloorMesh().
Vector<FloorMeshTriangleNode*> FloorMesh::tris private
Definition at line 178 of file FloorMesh.h.
Referenced by findNearestTriangle(), getNeighbors(), parseBEDG(), parseVersion0005(), parseVersion0006(), readObject(), and ~FloorMesh().
Vector<Vert> FloorMesh::vertices private
Definition at line 177 of file FloorMesh.h.
Referenced by getVertex(), parseVersion0005(), parseVersion0006(), and readObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/FloorMesh.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/FloorMesh.cpp