Core3: FlourishCommand Class Reference
FlourishCommand Class Reference
#include <FlourishCommand.h>
Public Member Functions
FlourishCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
Detailed Description
Definition at line 51 of file FlourishCommand.h.
Constructor & Destructor Documentation
FlourishCommand::FlourishCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 54 of file FlourishCommand.h.
Member Function Documentation
int FlourishCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 59 of file FlourishCommand.h.
References SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
float FlourishCommand::getCommandDuration (CreatureObject * object, const UnicodeString & arguments) inline
Definition at line 103 of file FlourishCommand.h.
References SessionFacadeType::ENTERTAINING.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/FlourishCommand.h