Core3: server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation Class Reference
server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation Class Reference
#include <SuiInputBox.h>
Public Member Functions
SuiInputBoxImplementation (CreatureObject *player, unsigned int windowType=0, int inputtype=0)
SuiInputBoxImplementation (DummyConstructorParameter *param)
BaseMessage * generateMessage ()
void setMaxInputSize (int size)
void setDefaultInput (const String &text)
bool isFilterBox ()
bool isInputBox ()
operator const SuiInputBox * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
SuiBoxImplementation (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
SuiBoxImplementation (DummyConstructorParameter *param)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
virtual bool isListBox ()
virtual bool isMessageBox ()
virtual bool isTransferBox ()
virtual bool isBankTransferBox ()
virtual bool isSlicingBox ()
virtual bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
operator const SuiBox * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< SuiInputBox * > _this
Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
WeakReference< SuiBox * > _this
Static Public Attributes
static const int DEFAULT = 0
static const int FILTER = 1
Static Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Protected Member Functions
virtual ~SuiInputBoxImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
virtual ~SuiBoxImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
int maxInputSize
String defaultInput
int inputType
Protected Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
ManagedWeakReference
< CreatureObject * > player
Reference< SuiCallback * > suiCallback
unsigned int boxID
ManagedWeakReference
< SceneObject * > usingObject
String handlerStr
String cancelButtonText
bool cancelButton
String okButtonText
bool okButton
String otherButtonText
bool otherButton
String promptTitle
String promptText
int boxType
unsigned int windowType
float forceCloseDistance
Vector< String > headerSets
Vector< String > optionSets
int hdrOptCount
bool hasGenerated
Friends
class SuiInputBox
Detailed Description
Definition at line 118 of file SuiInputBox.h.
Constructor & Destructor Documentation
SuiInputBoxImplementation::SuiInputBoxImplementation (CreatureObject * player, unsigned int windowType = 0, int inputtype = 0)
Definition at line 270 of file SuiInputBox.cpp.
References _initializeImplementation(), inputType, and maxInputSize.
SuiInputBoxImplementation::SuiInputBoxImplementation (DummyConstructorParameter * param)
Definition at line 120 of file SuiInputBox.cpp.
References _initializeImplementation().
SuiInputBoxImplementation::~SuiInputBoxImplementation () protected virtual
Definition at line 125 of file SuiInputBox.cpp.
Member Function Documentation
DistributedObjectStub * SuiInputBoxImplementation::_getStub ()
Definition at line 145 of file SuiInputBox.cpp.
References _this.
void SuiInputBoxImplementation::_initializeImplementation () protected
Definition at line 132 of file SuiInputBox.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SuiInputBoxImplementation().
void SuiInputBoxImplementation::_serializationHelperMethod () protected
Definition at line 181 of file SuiInputBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void SuiInputBoxImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 140 of file SuiInputBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_setStub(), and _this.
Referenced by server::zone::objects::player::sui::messagebox::SuiInputBox::SuiInputBox().
void SuiInputBoxImplementation::finalize () protected
Definition at line 129 of file SuiInputBox.cpp.
BaseMessage * SuiInputBoxImplementation::generateMessage () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 10 of file SuiInputBoxImplementation.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::addHeader(), server::zone::objects::player::sui::SuiBoxImplementation::addSetting(), server::zone::objects::player::sui::SuiBoxImplementation::boxID, server::zone::objects::player::sui::SuiBoxImplementation::cancelButton, defaultInput, server::zone::objects::player::sui::SuiBoxImplementation::generateBody(), server::zone::objects::player::sui::SuiBoxImplementation::generateFooter(), server::zone::objects::player::sui::SuiBoxImplementation::generateHeader(), server::zone::objects::player::sui::SuiBoxImplementation::hasGenerated, isFilterBox(), maxInputSize, server::zone::objects::player::sui::SuiBoxImplementation::promptText, server::zone::objects::player::sui::SuiBoxImplementation::promptTitle, and server::zone::objects::player::sui::SuiBoxImplementation::setHandlerText().
Referenced by server::zone::objects::player::sui::messagebox::SuiInputBox::generateMessage().
bool SuiInputBoxImplementation::isFilterBox ()
Definition at line 288 of file SuiInputBox.cpp.
References FILTER, and inputType.
Referenced by generateMessage(), and server::zone::objects::player::sui::messagebox::SuiInputBox::isFilterBox().
bool SuiInputBoxImplementation::isInputBox () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 293 of file SuiInputBox.cpp.
Referenced by server::zone::objects::player::sui::messagebox::SuiInputBox::isInputBox().
void SuiInputBoxImplementation::lock (bool doLock = true) protected
Definition at line 153 of file SuiInputBox.cpp.
References _this.
void SuiInputBoxImplementation::lock (ManagedObject * obj) protected
Definition at line 157 of file SuiInputBox.cpp.
References _this.
SuiInputBoxImplementation::operator const SuiInputBox * ()
Definition at line 149 of file SuiInputBox.cpp.
void SuiInputBoxImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 188 of file SuiInputBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::initializeTransientMembers(), and readObjectMember().
bool SuiInputBoxImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 207 of file SuiInputBox.cpp.
References defaultInput, inputType, maxInputSize, and server::zone::objects::player::sui::SuiBoxImplementation::readObjectMember().
Referenced by readObject().
void SuiInputBoxImplementation::rlock (bool doLock = true) protected
Definition at line 161 of file SuiInputBox.cpp.
References _this.
void SuiInputBoxImplementation::runlock (bool doLock = true) protected
Definition at line 177 of file SuiInputBox.cpp.
References _this.
void SuiInputBoxImplementation::setDefaultInput (const String & text)
Definition at line 283 of file SuiInputBox.cpp.
References defaultInput.
Referenced by server::zone::objects::player::sui::messagebox::SuiInputBox::setDefaultInput().
void SuiInputBoxImplementation::setMaxInputSize (int size)
Definition at line 278 of file SuiInputBox.cpp.
References maxInputSize.
Referenced by server::zone::objects::player::sui::messagebox::SuiInputBox::setMaxInputSize().
void SuiInputBoxImplementation::unlock (bool doLock = true) protected
Definition at line 173 of file SuiInputBox.cpp.
References _this.
void SuiInputBoxImplementation::wlock (bool doLock = true) protected
Definition at line 165 of file SuiInputBox.cpp.
References _this.
void SuiInputBoxImplementation::wlock (ManagedObject * obj) protected
Definition at line 169 of file SuiInputBox.cpp.
References _this.
void SuiInputBoxImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 229 of file SuiInputBox.cpp.
References writeObjectMembers().
int SuiInputBoxImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 236 of file SuiInputBox.cpp.
References defaultInput, inputType, maxInputSize, and server::zone::objects::player::sui::SuiBoxImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class SuiInputBox friend
Definition at line 179 of file SuiInputBox.h.
Member Data Documentation
WeakReference<SuiInputBox*> server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::_this
Definition at line 145 of file SuiInputBox.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
const int server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::DEFAULT = 0 static
Definition at line 127 of file SuiInputBox.h.
String server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::defaultInput protected
Definition at line 122 of file SuiInputBox.h.
Referenced by generateMessage(), readObjectMember(), setDefaultInput(), and writeObjectMembers().
const int server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::FILTER = 1 static
Definition at line 129 of file SuiInputBox.h.
Referenced by isFilterBox().
int server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::inputType protected
Definition at line 124 of file SuiInputBox.h.
Referenced by isFilterBox(), readObjectMember(), SuiInputBoxImplementation(), and writeObjectMembers().
int server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::maxInputSize protected
Definition at line 120 of file SuiInputBox.h.
Referenced by generateMessage(), readObjectMember(), setMaxInputSize(), SuiInputBoxImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/inputbox/SuiInputBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/inputbox/SuiInputBox.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/inputbox/SuiInputBoxImplementation.cpp