Core3: TurretControlTerminalDataComponent Class Reference
TurretControlTerminalDataComponent Class Reference
#include <TurretControlTerminalDataComponent.h>
Public Member Functions
TurretControlTerminalDataComponent ()
virtual ~TurretControlTerminalDataComponent ()
bool isTurretControlTerminalData ()
int getTurrteIndex ()
void setTurretIndex (int indx)
void setSuiBoxID (int id)
int getSuiBoxID ()
Public Member Functions inherited from DataObjectComponent
DataObjectComponent ()
~DataObjectComponent ()
virtual void initializeTransientMembers ()
virtual void notifyObjectDestroyingFromDatabase ()
void setParent (SceneObject *object)
SceneObject * getParent ()
virtual bool isDiceData ()
virtual bool isVendorData ()
virtual bool isAuctionTerminalData ()
virtual bool isCreatureHabitatData ()
virtual bool isBuildingData ()
virtual bool isDestructibleBuildingData ()
virtual bool isTurretData ()
virtual bool isDetectorData ()
virtual bool isGCWBaseData ()
virtual bool isSecurityTerminalData ()
virtual bool isMinefieldData ()
virtual bool isDecoration ()
Protected Attributes
int turretIndex
int suiBoxID
Protected Attributes inherited from DataObjectComponent
ManagedWeakReference
< SceneObject * > parent
Private Member Functions
void addSerializableVariables ()
Detailed Description
Definition at line 12 of file TurretControlTerminalDataComponent.h.
Constructor & Destructor Documentation
TurretControlTerminalDataComponent::TurretControlTerminalDataComponent () inline
Definition at line 18 of file TurretControlTerminalDataComponent.h.
References addSerializableVariables(), suiBoxID, and turretIndex.
virtual TurretControlTerminalDataComponent::~TurretControlTerminalDataComponent () inline virtual
Definition at line 24 of file TurretControlTerminalDataComponent.h.
Member Function Documentation
void TurretControlTerminalDataComponent::addSerializableVariables () inline private
Definition at line 50 of file TurretControlTerminalDataComponent.h.
References turretIndex.
Referenced by TurretControlTerminalDataComponent().
int TurretControlTerminalDataComponent::getSuiBoxID () inline
Definition at line 43 of file TurretControlTerminalDataComponent.h.
References suiBoxID.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::canUseTurret().
int TurretControlTerminalDataComponent::getTurrteIndex () inline
Definition at line 32 of file TurretControlTerminalDataComponent.h.
References turretIndex.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::sendTurretAttackListTo().
bool TurretControlTerminalDataComponent::isTurretControlTerminalData () inline virtual
Reimplemented from DataObjectComponent.
Definition at line 28 of file TurretControlTerminalDataComponent.h.
void TurretControlTerminalDataComponent::setSuiBoxID (int id) inline
Definition at line 40 of file TurretControlTerminalDataComponent.h.
References suiBoxID.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo().
void TurretControlTerminalDataComponent::setTurretIndex (int indx) inline
Definition at line 36 of file TurretControlTerminalDataComponent.h.
References turretIndex.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects().
Member Data Documentation
int TurretControlTerminalDataComponent::suiBoxID protected
Definition at line 15 of file TurretControlTerminalDataComponent.h.
Referenced by getSuiBoxID(), setSuiBoxID(), and TurretControlTerminalDataComponent().
int TurretControlTerminalDataComponent::turretIndex protected
Definition at line 14 of file TurretControlTerminalDataComponent.h.
Referenced by addSerializableVariables(), getTurrteIndex(), setTurretIndex(), and TurretControlTerminalDataComponent().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/terminal/components/TurretControlTerminalDataComponent.h