Core3: VendorSelectionNode Class Reference
VendorSelectionNode Class Reference
#include <VendorSelectionNode.h>
Public Member Functions
VendorSelectionNode ()
VendorSelectionNode (const VendorSelectionNode &node)
VendorSelectionNode & operator= (const VendorSelectionNode &node)
void parseFromLua (LuaObject &lua)
int compareTo (const VendorSelectionNode &node) const
void addChildNode (VendorSelectionNode *node)
void setNodeName (const String &name)
void setNodePath (const String &path)
void setHiringRequired (int hiring)
bool hasChildNode ()
void addChildrenToListBox (SuiListBox *listBox, int hiringSkill)
VendorSelectionNode * getNode (int idx)
int getChildNodeSize ()
String getRandomTemplate (int skillLevel)
String & getNodeName ()
int getHiringRequired ()
String & getSuiDisplay ()
String & getTemplatePath ()
Private Attributes
String nodeTitle
String nodePath
String suiDisplay
int hiringRequired
SortedVector< Reference
< VendorSelectionNode * > > childNodes
Detailed Description
Definition at line 14 of file VendorSelectionNode.h.
Constructor & Destructor Documentation
VendorSelectionNode::VendorSelectionNode () inline
Definition at line 24 of file VendorSelectionNode.h.
References hiringRequired.
Referenced by parseFromLua().
VendorSelectionNode::VendorSelectionNode (const VendorSelectionNode & node) inline
Definition at line 28 of file VendorSelectionNode.h.
References childNodes, hiringRequired, nodePath, nodeTitle, and suiDisplay.
Member Function Documentation
void VendorSelectionNode::addChildNode (VendorSelectionNode * node) inline
Definition at line 94 of file VendorSelectionNode.h.
References childNodes.
Referenced by parseFromLua().
void VendorSelectionNode::addChildrenToListBox (SuiListBox * listBox, int hiringSkill) inline
Definition at line 114 of file VendorSelectionNode.h.
References server::zone::objects::player::sui::listbox::SuiListBox::addMenuItem(), childNodes, getHiringRequired(), and getNodeName().
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::handleVendorSelection().
int VendorSelectionNode::compareTo (const VendorSelectionNode & node) const inline
Definition at line 84 of file VendorSelectionNode.h.
References hiringRequired.
int VendorSelectionNode::getChildNodeSize () inline
Definition at line 129 of file VendorSelectionNode.h.
References childNodes.
int VendorSelectionNode::getHiringRequired () inline
Definition at line 156 of file VendorSelectionNode.h.
References hiringRequired.
Referenced by addChildrenToListBox(), and getRandomTemplate().
VendorSelectionNode* VendorSelectionNode::getNode (int idx) inline
Definition at line 122 of file VendorSelectionNode.h.
References childNodes.
String& VendorSelectionNode::getNodeName () inline
Definition at line 152 of file VendorSelectionNode.h.
References nodeTitle.
Referenced by addChildrenToListBox().
String VendorSelectionNode::getRandomTemplate (int skillLevel) inline
Definition at line 133 of file VendorSelectionNode.h.
References childNodes, getHiringRequired(), and getTemplatePath().
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::handleVendorSelection().
String& VendorSelectionNode::getSuiDisplay () inline
Definition at line 160 of file VendorSelectionNode.h.
References suiDisplay.
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::handleVendorSelection().
String& VendorSelectionNode::getTemplatePath () inline
Definition at line 164 of file VendorSelectionNode.h.
References nodePath.
Referenced by getRandomTemplate(), and server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::handleVendorSelection().
bool VendorSelectionNode::hasChildNode () inline
Definition at line 110 of file VendorSelectionNode.h.
References childNodes.
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::handleVendorSelection().
VendorSelectionNode& VendorSelectionNode::operator= (const VendorSelectionNode & node) inline
Definition at line 37 of file VendorSelectionNode.h.
References childNodes, hiringRequired, nodePath, nodeTitle, and suiDisplay.
void VendorSelectionNode::parseFromLua (LuaObject & lua) inline
Definition at line 50 of file VendorSelectionNode.h.
References addChildNode(), childNodes, hiringRequired, nodePath, nodeTitle, suiDisplay, and VendorSelectionNode().
void VendorSelectionNode::setHiringRequired (int hiring) inline
Definition at line 106 of file VendorSelectionNode.h.
References hiringRequired.
void VendorSelectionNode::setNodeName (const String & name) inline
Definition at line 98 of file VendorSelectionNode.h.
References nodeTitle.
void VendorSelectionNode::setNodePath (const String & path) inline
Definition at line 102 of file VendorSelectionNode.h.
References nodePath.
Member Data Documentation
SortedVector<Reference<VendorSelectionNode*> > VendorSelectionNode::childNodes private
Definition at line 21 of file VendorSelectionNode.h.
Referenced by addChildNode(), addChildrenToListBox(), getChildNodeSize(), getNode(), getRandomTemplate(), hasChildNode(), operator=(), parseFromLua(), and VendorSelectionNode().
int VendorSelectionNode::hiringRequired private
Definition at line 19 of file VendorSelectionNode.h.
Referenced by compareTo(), getHiringRequired(), operator=(), parseFromLua(), setHiringRequired(), and VendorSelectionNode().
String VendorSelectionNode::nodePath private
Definition at line 17 of file VendorSelectionNode.h.
Referenced by getTemplatePath(), operator=(), parseFromLua(), setNodePath(), and VendorSelectionNode().
String VendorSelectionNode::nodeTitle private
Definition at line 16 of file VendorSelectionNode.h.
Referenced by getNodeName(), operator=(), parseFromLua(), setNodeName(), and VendorSelectionNode().
String VendorSelectionNode::suiDisplay private
Definition at line 18 of file VendorSelectionNode.h.
Referenced by getSuiDisplay(), operator=(), parseFromLua(), and VendorSelectionNode().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/vendor/VendorSelectionNode.h