Core3: SkillModEntry Class Reference
SkillModEntry Class Reference
#include <SkillModEntry.h>
Public Member Functions
SkillModEntry ()
SkillModEntry (const SkillModEntry &mod)
SkillModEntry & operator= (const SkillModEntry &mod)
bool operator== (SkillModEntry mod)
void setSkillMod (int mod)
int getSkillMod ()
void setSkillBonus (int bonus)
int getSkillBonus ()
int getTotalSkill ()
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
Private Attributes
int skillMod
int skillBonus
Detailed Description
Definition at line 50 of file SkillModEntry.h.
Constructor & Destructor Documentation
SkillModEntry::SkillModEntry () inline
Definition at line 56 of file SkillModEntry.h.
References skillBonus, and skillMod.
SkillModEntry::SkillModEntry (const SkillModEntry & mod) inline
Definition at line 62 of file SkillModEntry.h.
References skillBonus, and skillMod.
Member Function Documentation
int SkillModEntry::getSkillBonus () inline
Definition at line 96 of file SkillModEntry.h.
References skillBonus.
Referenced by getTotalSkill(), and SkillModList::getVisibleSkillMod().
int SkillModEntry::getSkillMod () inline
Definition at line 88 of file SkillModEntry.h.
References skillMod.
Referenced by getTotalSkill(), and SkillModList::getVisibleSkillMod().
int SkillModEntry::getTotalSkill () inline
Definition at line 100 of file SkillModEntry.h.
References getSkillBonus(), and getSkillMod().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::addSkillMod().
SkillModEntry& SkillModEntry::operator= (const SkillModEntry & mod) inline
Definition at line 68 of file SkillModEntry.h.
References skillBonus, and skillMod.
bool SkillModEntry::operator== (SkillModEntry mod) inline
Definition at line 78 of file SkillModEntry.h.
References skillBonus, and skillMod.
bool SkillModEntry::parseFromBinaryStream (ObjectInputStream * stream) inline
Definition at line 109 of file SkillModEntry.h.
References skillBonus, and skillMod.
void SkillModEntry::setSkillBonus (int bonus) inline
Definition at line 92 of file SkillModEntry.h.
References skillBonus.
Referenced by SkillModList::getVisibleSkillMod().
void SkillModEntry::setSkillMod (int mod) inline
Definition at line 84 of file SkillModEntry.h.
References skillMod.
Referenced by SkillModList::getVisibleSkillMod().
bool SkillModEntry::toBinaryStream (ObjectOutputStream * stream) inline
Definition at line 104 of file SkillModEntry.h.
References skillBonus, and skillMod.
Member Data Documentation
int SkillModEntry::skillBonus private
Definition at line 53 of file SkillModEntry.h.
Referenced by getSkillBonus(), operator=(), operator==(), parseFromBinaryStream(), setSkillBonus(), SkillModEntry(), and toBinaryStream().
int SkillModEntry::skillMod private
Definition at line 52 of file SkillModEntry.h.
Referenced by getSkillMod(), operator=(), operator==(), parseFromBinaryStream(), setSkillMod(), SkillModEntry(), and toBinaryStream().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/variables/SkillModEntry.h