Core3: WeaponRanges Class Reference
WeaponRanges Class Reference
#include <WeaponRanges.h>
Public Member Functions
WeaponRanges (CreatureObject *creo, WeaponObject *weao)
Public Member Functions inherited from ObjectControllerMessage
ObjectControllerMessage (uint64 objid, uint32 header1, uint32 header2, bool comp=true)
Detailed Description
Definition at line 54 of file WeaponRanges.h.
Constructor & Destructor Documentation
WeaponRanges::WeaponRanges (CreatureObject * creo, WeaponObject * weao) inline
Definition at line 56 of file WeaponRanges.h.
References server::zone::objects::tangible::weapon::WeaponObject::getIdealAccuracy(), server::zone::objects::tangible::weapon::WeaponObject::getIdealRange(), server::zone::objects::tangible::weapon::WeaponObject::getMaxRange(), server::zone::objects::tangible::weapon::WeaponObject::getMaxRangeAccuracy(), server::zone::objects::scene::SceneObject::getObjectID(), and server::zone::objects::tangible::weapon::WeaponObject::getPointBlankAccuracy().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/object/WeaponRanges.h