Core3: server::zone::objects::tangible::pharmaceutical::RevivePackImplementation Class Reference
server::zone::objects::tangible::pharmaceutical::RevivePackImplementation Class Reference
#include <RevivePack.h>
Public Member Functions
RevivePackImplementation ()
RevivePackImplementation (DummyConstructorParameter *param)
void updateCraftingValues (CraftingValues *values, bool firstUpdate)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getHealthWoundHealed ()
float getHealthHealed ()
float getActionWoundHealed ()
float getActionHealed ()
float getMindWoundHealed ()
float getMindHealed ()
bool isRevivePack ()
operator const RevivePack * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation
PharmaceuticalObjectImplementation ()
PharmaceuticalObjectImplementation (DummyConstructorParameter *param)
int getMedicineUseRequired ()
virtual float getRange (CreatureObject *creature=NULL)
virtual bool isArea ()
virtual float getArea ()
bool isPharmaceuticalObject ()
virtual bool isStimPack ()
virtual bool isRangedStimPack ()
virtual bool isEnhancePack ()
virtual bool isWoundPack ()
virtual bool isCurePack ()
virtual bool isStatePack ()
operator const PharmaceuticalObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
TangibleObjectImplementation ()
TangibleObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
virtual void addTemplateSkillMods (TangibleObject *targetObject)
virtual void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
virtual void removeSkillModsFrom (CreatureObject *creature)
virtual void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
virtual void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
virtual void removeAllSkillModsOfType (const int skillType, bool notifyClient=true)
virtual void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void sendBaselinesTo (SceneObject *player)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
virtual void setDefender (SceneObject *defender)
virtual void addDefender (SceneObject *defender)
virtual void removeDefender (SceneObject *defender)
virtual void removeDefenders ()
virtual void setCombatState ()
virtual void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
virtual void clearCombatState (bool clearDefenders=true)
bool hasDefender (SceneObject *defender)
virtual bool isAttackableBy (CreatureObject *object)
virtual bool isAggressiveTo (CreatureObject *object)
virtual bool isHealableBy (CreatureObject *object)
virtual void sendPvpStatusTo (CreatureObject *player)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
virtual int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
virtual int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
virtual bool isKiller ()
virtual bool isTicketCollector ()
virtual bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
virtual int getUseCount ()
virtual int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
virtual String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
virtual int getJunkDealerNeeded ()
void setJunkValue (int jValue)
virtual int getJunkValue ()
void setSerialNumber (const String &serial)
virtual void setLevel (int lev)
virtual String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
virtual String repairAttempt (int repairChance)
bool isBroken ()
virtual float getHitChance ()
void broadcastPvpStatusBitmask ()
operator const TangibleObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendTo (SceneObject *player, bool doClose)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
virtual void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
virtual void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< RevivePack * > _this
Public Attributes inherited from server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation
WeakReference
< PharmaceuticalObject * > _this
Public Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
WeakReference< TangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Protected Member Functions
virtual ~RevivePackImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation
virtual ~PharmaceuticalObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
float getConditionReduction (float value)
virtual ~TangibleObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
float healthWoundHealed
float healthHealed
float actionWoundHealed
float actionHealed
float mindWoundHealed
float mindHealed
Protected Attributes inherited from server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation
int medicineUseRequired
Protected Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
bool targetable
float complexity
int volume
unsigned int faction
CustomizationVariables customizationVariables
float conditionDamage
int maxCondition
int useCount
short level
unsigned int optionsBitmask
unsigned int pvpStatusBitmask
byte unknownByte
String craftersName
int junkDealerNeeded
int junkValue
String objectSerial
Reference< ThreatMap * > threatMap
DeltaVector< ManagedReference
< SceneObject * > > defenderList
bool sliceable
bool sliced
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Friends
class RevivePack
Detailed Description
Definition at line 196 of file RevivePack.h.
Constructor & Destructor Documentation
RevivePackImplementation::RevivePackImplementation ()
Definition at line 373 of file RevivePack.cpp.
References _initializeImplementation(), actionHealed, actionWoundHealed, healthHealed, healthWoundHealed, mindHealed, mindWoundHealed, and server::zone::objects::scene::SceneObjectImplementation::setLoggingName().
RevivePackImplementation::RevivePackImplementation (DummyConstructorParameter * param)
Definition at line 187 of file RevivePack.cpp.
References _initializeImplementation().
RevivePackImplementation::~RevivePackImplementation () protected virtual
Definition at line 192 of file RevivePack.cpp.
Member Function Documentation
DistributedObjectStub * RevivePackImplementation::_getStub ()
Definition at line 212 of file RevivePack.cpp.
References _this.
void RevivePackImplementation::_initializeImplementation () protected
Definition at line 199 of file RevivePack.cpp.
References _serializationHelperMethod(), and _this.
Referenced by RevivePackImplementation().
void RevivePackImplementation::_serializationHelperMethod () protected
Definition at line 248 of file RevivePack.cpp.
References server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void RevivePackImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 207 of file RevivePack.cpp.
References server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::_setStub(), and _this.
Referenced by server::zone::objects::tangible::pharmaceutical::RevivePack::RevivePack().
void RevivePackImplementation::fillAttributeList (AttributeListMessage * msg, CreatureObject * object) virtual
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 428 of file RevivePack.cpp.
References actionHealed, actionWoundHealed, server::zone::objects::tangible::TangibleObjectImplementation::fillAttributeList(), healthHealed, healthWoundHealed, server::zone::packets::scene::AttributeListMessage::insertAttribute(), server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::medicineUseRequired, mindHealed, and mindWoundHealed.
Referenced by server::zone::objects::tangible::pharmaceutical::RevivePack::fillAttributeList().
void RevivePackImplementation::finalize () protected
Definition at line 196 of file RevivePack.cpp.
float RevivePackImplementation::getActionHealed ()
Definition at line 489 of file RevivePack.cpp.
References actionHealed.
Referenced by server::zone::objects::tangible::pharmaceutical::RevivePack::getActionHealed().
float RevivePackImplementation::getActionWoundHealed ()
Definition at line 484 of file RevivePack.cpp.
References actionWoundHealed.
Referenced by server::zone::objects::tangible::pharmaceutical::RevivePack::getActionWoundHealed().
float RevivePackImplementation::getHealthHealed ()
Definition at line 479 of file RevivePack.cpp.
References healthHealed.
Referenced by server::zone::objects::tangible::pharmaceutical::RevivePack::getHealthHealed().
float RevivePackImplementation::getHealthWoundHealed ()
Definition at line 474 of file RevivePack.cpp.
References healthWoundHealed.
Referenced by server::zone::objects::tangible::pharmaceutical::RevivePack::getHealthWoundHealed().
float RevivePackImplementation::getMindHealed ()
Definition at line 499 of file RevivePack.cpp.
References mindHealed.
Referenced by server::zone::objects::tangible::pharmaceutical::RevivePack::getMindHealed().
float RevivePackImplementation::getMindWoundHealed ()
Definition at line 494 of file RevivePack.cpp.
References mindWoundHealed.
Referenced by server::zone::objects::tangible::pharmaceutical::RevivePack::getMindWoundHealed().
int RevivePackImplementation::handleObjectMenuSelect (CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player CreatureObject that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 447 of file RevivePack.cpp.
References server::zone::objects::scene::SceneObjectImplementation::getObjectID(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::scene::SceneObjectImplementation::isASubChildOf(), server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::medicineUseRequired, server::zone::objects::creature::CreatureObject::sendExecuteConsoleCommand(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::objects::tangible::pharmaceutical::RevivePack::handleObjectMenuSelect().
bool RevivePackImplementation::isRevivePack () virtual
Reimplemented from server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation.
Definition at line 504 of file RevivePack.cpp.
Referenced by server::zone::objects::tangible::pharmaceutical::RevivePack::isRevivePack().
void RevivePackImplementation::lock (bool doLock = true) protected
Definition at line 220 of file RevivePack.cpp.
References _this.
void RevivePackImplementation::lock (ManagedObject * obj) protected
Definition at line 224 of file RevivePack.cpp.
References _this.
RevivePackImplementation::operator const RevivePack * ()
Definition at line 216 of file RevivePack.cpp.
void RevivePackImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation.
Definition at line 255 of file RevivePack.cpp.
References server::zone::objects::tangible::TangibleObjectImplementation::initializeTransientMembers(), and readObjectMember().
bool RevivePackImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 274 of file RevivePack.cpp.
References actionHealed, actionWoundHealed, healthHealed, healthWoundHealed, mindHealed, mindWoundHealed, and server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::readObjectMember().
Referenced by readObject().
void RevivePackImplementation::rlock (bool doLock = true) protected
Definition at line 228 of file RevivePack.cpp.
References _this.
void RevivePackImplementation::runlock (bool doLock = true) protected
Definition at line 244 of file RevivePack.cpp.
References _this.
void RevivePackImplementation::unlock (bool doLock = true) protected
Definition at line 240 of file RevivePack.cpp.
References _this.
void RevivePackImplementation::updateCraftingValues (CraftingValues * values, bool firstUpdate) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 391 of file RevivePack.cpp.
References actionHealed, actionWoundHealed, server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentValue(), healthHealed, healthWoundHealed, server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::medicineUseRequired, mindHealed, mindWoundHealed, server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setHidden(), and server::zone::objects::tangible::TangibleObjectImplementation::setUseCount().
Referenced by server::zone::objects::tangible::pharmaceutical::RevivePack::updateCraftingValues().
void RevivePackImplementation::wlock (bool doLock = true) protected
Definition at line 232 of file RevivePack.cpp.
References _this.
void RevivePackImplementation::wlock (ManagedObject * obj) protected
Definition at line 236 of file RevivePack.cpp.
References _this.
void RevivePackImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation.
Definition at line 308 of file RevivePack.cpp.
References writeObjectMembers().
int RevivePackImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 315 of file RevivePack.cpp.
References actionHealed, actionWoundHealed, healthHealed, healthWoundHealed, mindHealed, mindWoundHealed, and server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class RevivePack friend
Definition at line 284 of file RevivePack.h.
Member Data Documentation
WeakReference<RevivePack*> server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::_this
Definition at line 250 of file RevivePack.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
float server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::actionHealed protected
Definition at line 204 of file RevivePack.h.
Referenced by fillAttributeList(), getActionHealed(), readObjectMember(), RevivePackImplementation(), updateCraftingValues(), and writeObjectMembers().
float server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::actionWoundHealed protected
Definition at line 202 of file RevivePack.h.
Referenced by fillAttributeList(), getActionWoundHealed(), readObjectMember(), RevivePackImplementation(), updateCraftingValues(), and writeObjectMembers().
float server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::healthHealed protected
Definition at line 200 of file RevivePack.h.
Referenced by fillAttributeList(), getHealthHealed(), readObjectMember(), RevivePackImplementation(), updateCraftingValues(), and writeObjectMembers().
float server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::healthWoundHealed protected
Definition at line 198 of file RevivePack.h.
Referenced by fillAttributeList(), getHealthWoundHealed(), readObjectMember(), RevivePackImplementation(), updateCraftingValues(), and writeObjectMembers().
float server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::mindHealed protected
Definition at line 208 of file RevivePack.h.
Referenced by fillAttributeList(), getMindHealed(), readObjectMember(), RevivePackImplementation(), updateCraftingValues(), and writeObjectMembers().
float server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::mindWoundHealed protected
Definition at line 206 of file RevivePack.h.
Referenced by fillAttributeList(), getMindWoundHealed(), readObjectMember(), RevivePackImplementation(), updateCraftingValues(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/pharmaceutical/RevivePack.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/pharmaceutical/RevivePack.cpp