Core3: GroupMember Class Reference
GroupMember Class Reference
#include <GroupMember.h>
Public Member Functions
GroupMember ()
GroupMember (const GroupMember &obj)
GroupMember (SceneObject *obj)
void operator= (SceneObject *obj)
SceneObject * operator-> () const
SceneObject * get ()
operator SceneObject * () const
bool toString (String &str)
bool parseFromString (const String &str, int version=0)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
Private Attributes
ManagedReference< SceneObject * > creature
Detailed Description
Definition at line 14 of file GroupMember.h.
Constructor & Destructor Documentation
GroupMember::GroupMember () inline
Definition at line 18 of file GroupMember.h.
References creature.
GroupMember::GroupMember (const GroupMember & obj) inline
Definition at line 22 of file GroupMember.h.
References creature.
GroupMember::GroupMember (SceneObject * obj) inline
Definition at line 26 of file GroupMember.h.
References creature.
Member Function Documentation
SceneObject* GroupMember::get () inline
Definition at line 38 of file GroupMember.h.
References creature.
Referenced by server::zone::objects::group::GroupObjectImplementation::addGroupModifiers(), server::zone::objects::group::GroupObjectImplementation::disband(), server::zone::objects::group::GroupObjectImplementation::getGroupHarvestModifier(), server::zone::objects::group::GroupObjectImplementation::makeLeader(), server::zone::objects::group::GroupObjectImplementation::removeGroupModifiers(), and server::zone::objects::group::GroupObjectImplementation::startChatRoom().
GroupMember::operator SceneObject * () const inline
Definition at line 42 of file GroupMember.h.
References creature.
SceneObject* GroupMember::operator-> () const inline
Definition at line 34 of file GroupMember.h.
References creature.
void GroupMember::operator= (SceneObject * obj) inline
Definition at line 30 of file GroupMember.h.
References creature.
bool GroupMember::parseFromBinaryStream (ObjectInputStream * stream) inline
Definition at line 69 of file GroupMember.h.
References creature.
bool GroupMember::parseFromString (const String & str, int version = 0) inline
Definition at line 50 of file GroupMember.h.
References creature.
bool GroupMember::toBinaryStream (ObjectOutputStream * stream) inline
Definition at line 54 of file GroupMember.h.
References creature.
bool GroupMember::toString (String & str) inline
Definition at line 46 of file GroupMember.h.
References creature.
Member Data Documentation
ManagedReference<SceneObject*> GroupMember::creature private
Definition at line 15 of file GroupMember.h.
Referenced by get(), GroupMember(), operator SceneObject *(), operator->(), operator=(), parseFromBinaryStream(), parseFromString(), toBinaryStream(), and toString().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/group/GroupMember.h