Core3: StopBandCommand Class Reference
StopBandCommand Class Reference
#include <StopBandCommand.h>
Public Member Functions
StopBandCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file StopBandCommand.h.
Constructor & Destructor Documentation
StopBandCommand::StopBandCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file StopBandCommand.h.
Member Function Documentation
int StopBandCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 58 of file StopBandCommand.h.
References SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getCustomObjectName(), server::zone::objects::creature::CreatureObject::getGroup(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/StopBandCommand.h