Core3: server::zone::objects::area::areashapes::RingAreaShapeAdapter Class Reference
server::zone::objects::area::areashapes::RingAreaShapeAdapter Class Reference
#include <RingAreaShape.h>
Public Member Functions
RingAreaShapeAdapter (RingAreaShape *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setInnerRadius (float r)
void setOuterRadius (float r)
float getInnerRadius ()
float getInnerRadius2 ()
float getOuterRadius ()
float getOuterRadius2 ()
bool containsPoint (float x, float y)
bool isRingAreaShape ()
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
Public Member Functions inherited from server::zone::objects::area::areashapes::AreaShapeAdapter
AreaShapeAdapter (AreaShape *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setAreaCenter (float x, float y)
bool containsPoint (float x, float y)
float getRadius ()
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
Detailed Description
Definition at line 332 of file RingAreaShape.h.
Constructor & Destructor Documentation
RingAreaShapeAdapter::RingAreaShapeAdapter (RingAreaShape * impl)
Definition at line 468 of file RingAreaShape.cpp.
Member Function Documentation
bool RingAreaShapeAdapter::containsPoint (float x, float y)
Definition at line 564 of file RingAreaShape.cpp.
Referenced by invokeMethod().
float RingAreaShapeAdapter::getArea ()
Definition at line 584 of file RingAreaShape.cpp.
Referenced by invokeMethod().
float RingAreaShapeAdapter::getInnerRadius ()
Definition at line 548 of file RingAreaShape.cpp.
Referenced by invokeMethod().
float RingAreaShapeAdapter::getInnerRadius2 ()
Definition at line 552 of file RingAreaShape.cpp.
Referenced by invokeMethod().
float RingAreaShapeAdapter::getOuterRadius ()
Definition at line 556 of file RingAreaShape.cpp.
Referenced by invokeMethod().
float RingAreaShapeAdapter::getOuterRadius2 ()
Definition at line 560 of file RingAreaShape.cpp.
Referenced by invokeMethod().
bool RingAreaShapeAdapter::intersectsWith (AreaShape * areaShape)
Definition at line 580 of file RingAreaShape.cpp.
Referenced by invokeMethod().
void RingAreaShapeAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 471 of file RingAreaShape.cpp.
References containsPoint(), getArea(), getInnerRadius(), getInnerRadius2(), getOuterRadius(), getOuterRadius2(), intersectsWith(), isCircularAreaShape(), isRectangularAreaShape(), isRingAreaShape(), RPC_CONTAINSPOINT__FLOAT_FLOAT_, RPC_GETAREA__, RPC_GETINNERRADIUS2__, RPC_GETINNERRADIUS__, RPC_GETOUTERRADIUS2__, RPC_GETOUTERRADIUS__, RPC_INTERSECTSWITH__AREASHAPE_, RPC_ISCIRCULARAREASHAPE__, RPC_ISRECTANGULARAREASHAPE__, RPC_ISRINGAREASHAPE__, RPC_SETINNERRADIUS__FLOAT_, RPC_SETOUTERRADIUS__FLOAT_, setInnerRadius(), and setOuterRadius().
bool RingAreaShapeAdapter::isCircularAreaShape ()
Definition at line 572 of file RingAreaShape.cpp.
Referenced by invokeMethod().
bool RingAreaShapeAdapter::isRectangularAreaShape ()
Definition at line 576 of file RingAreaShape.cpp.
Referenced by invokeMethod().
bool RingAreaShapeAdapter::isRingAreaShape ()
Definition at line 568 of file RingAreaShape.cpp.
Referenced by invokeMethod().
void RingAreaShapeAdapter::setInnerRadius (float r)
Definition at line 540 of file RingAreaShape.cpp.
Referenced by invokeMethod().
void RingAreaShapeAdapter::setOuterRadius (float r)
Definition at line 544 of file RingAreaShape.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RingAreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RingAreaShape.cpp