Core3: SuiCreatePageMessage Class Reference
SuiCreatePageMessage Class Reference
#include <SuiCreatePageMessage.h>
Public Member Functions
SuiCreatePageMessage (uint32 pageID, const String &scriptClass)
void insertOption (uint8 optionType, const String &value, const String &variable, const String &setting)
void insertHeaderOption (const String &variable, const String &type)
void insertFooter (uint64 usingObjectID, float distance=10, int type=0)
void setOptionCount (int optCnt)
int getOptionCount ()
Private Attributes
int optionOffset
int optionCount
Detailed Description
Packet. See trac documentation for detailed variable information. Manipulated and built heavily in SuiBoxImplementation
Definition at line 56 of file SuiCreatePageMessage.h.
Constructor & Destructor Documentation
SuiCreatePageMessage::SuiCreatePageMessage (uint32 pageID, const String & scriptClass) inline
Definition at line 61 of file SuiCreatePageMessage.h.
References optionCount, and optionOffset.
Member Function Documentation
int SuiCreatePageMessage::getOptionCount () inline
Definition at line 150 of file SuiCreatePageMessage.h.
References optionCount.
void SuiCreatePageMessage::insertFooter (uint64 usingObjectID, float distance = 10, int type = 0) inline
Insert's a UI-Footer option into the packet. Should only be accessed by methods in SuiBoxImplementation
Parameters
type Type of footer to insert.
Definition at line 132 of file SuiCreatePageMessage.h.
Referenced by server::zone::objects::player::sui::SuiBoxImplementation::generateFooter().
void SuiCreatePageMessage::insertHeaderOption (const String & variable, const String & type) inline
Insert's a UI-Header option into the packet. Should only be accessed by methods in SuiBoxImplementation See packet trac docs for more info
Parameters
variable SWG-UI Class var to access
type Datatype of the UI var
noCount Internal packet variable used to determine weather or not to count the option towards the total packet options
Definition at line 120 of file SuiCreatePageMessage.h.
Referenced by server::zone::objects::player::sui::SuiBoxImplementation::generateHeader().
void SuiCreatePageMessage::insertOption (uint8 optionType, const String & value, const String & variable, const String & setting) inline
Insert's a UI-Body option into the packet. Should only be accessed by methods in SuiBoxImplementation See packet trac docs for more info.
Parameters
optionType Type of UI option to add
value Value to set the setting to.
variable SWG-UI Classpath to access
setting SWG-UI setting within the UI class to modify
Definition at line 85 of file SuiCreatePageMessage.h.
References optionCount, and optionOffset.
Referenced by server::zone::objects::player::sui::SuiBoxImplementation::generateBody().
void SuiCreatePageMessage::setOptionCount (int optCnt) inline
Definition at line 146 of file SuiCreatePageMessage.h.
References optionCount.
Member Data Documentation
int SuiCreatePageMessage::optionCount private
Definition at line 58 of file SuiCreatePageMessage.h.
Referenced by getOptionCount(), insertOption(), setOptionCount(), and SuiCreatePageMessage().
int SuiCreatePageMessage::optionOffset private
Definition at line 57 of file SuiCreatePageMessage.h.
Referenced by insertOption(), and SuiCreatePageMessage().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/ui/SuiCreatePageMessage.h