Core3: CampKitMenuComponent Class Reference
CampKitMenuComponent Class Reference
#include <CampKitMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file CampKitMenuComponent.h.
Member Function Documentation
void CampKitMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from TangibleObjectMenuComponent.
Definition at line 26 of file CampKitMenuComponent.cpp.
References TangibleObjectMenuComponent::fillObjectMenuResponse(), and server::zone::objects::scene::SceneObject::isCampKit().
int CampKitMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Get Camp Kit Template
Get Camp Template
Get Ghost
Check for water
Make sure player doesn't already have a camp setup somewhere else
Check if player is in another camp
Check if player is elevated, on a building or porch
Check camps/lairs nearby
Check to see if you can camp here (Allows building in city no-build zone but not within city limits which are checked above)
Create Structure
Identify terminal for Active area
Create active area
Remove Camp
Reimplemented from TangibleObjectMenuComponent.
Definition at line 37 of file CampKitMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::addActiveArea(), server::zone::objects::tangible::TangibleObject::decreaseUseCount(), server::zone::objects::scene::SceneObject::getChildObjects(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::creature::CreatureObject::getCurrentCamp(), server::zone::objects::scene::SceneObject::getDirectionAngle(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getLastName(), server::zone::templates::SharedObjectTemplate::getNoBuildRadius(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::scene::SceneObject::getObservers(), server::zone::objects::scene::SceneObject::getParent(), CampStructureTemplate::getRadius(), server::zone::objects::scene::SceneObject::getServerObjectCRC(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::scene::SceneObject::getSlottedObject(), CampKitTemplate::getSpawnObjectTemplate(), server::zone::templates::SharedObjectTemplate::getTemplateFileName(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::getZoneServer(), TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::area::CampSiteActiveArea::init(), server::zone::objects::scene::SceneObject::isASubChildOf(), server::zone::objects::scene::SceneObject::isCampStructure(), server::zone::objects::creature::CreatureObject::isInCombat(), server::zone::objects::scene::SceneObject::isInWater(), server::zone::objects::creature::CreatureObject::isMounted(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isStanding(), server::zone::objects::scene::SceneObject::isStructureObject(), server::zone::objects::creature::CreatureObject::isSwimming(), server::zone::objects::scene::SceneObject::isTangibleObject(), ObserverType::LAIR, ObserverEventType::OBJECTDESTRUCTION, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::objects::tangible::TangibleObject::setCustomObjectName().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/CampKitMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/CampKitMenuComponent.cpp