Core3: server::login::LoginServerImplementation Class Reference
server::login::LoginServerImplementation Class Reference
#include <LoginServer.h>
Public Member Functions
LoginServerImplementation (ConfigManager *config)
LoginServerImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
LoginClient * createConnection (Socket *sock, SocketAddress &addr)
void initialize ()
void shutdown ()
void startManagers ()
void stopManagers ()
void start (int p, int mconn=10)
void stop ()
void handleMessage (LoginClient *client, Packet *message)
void processMessage (Message *message)
bool handleError (ServiceClient *client, Exception &e)
void printInfo ()
void populateGalaxyList ()
AccountManager * getAccountManager ()
Account * getAccount (unsigned int accountID)
LoginClient * getLoginClient (ServiceClient *session)
LoginEnumCluster * getLoginEnumClusterMessage ()
LoginClusterStatus * getLoginClusterStatusMessage ()
operator const LoginServer * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< LoginServer * > _this
Protected Member Functions
virtual ~LoginServerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
Reference
< DatagramServiceThread * > datagramService
Reference< BasePacketHandler * > phandler
Reference< LoginHandler * > loginHandler
Reference
< LoginProcessServerImplementation * > processor
Reference< ConfigManager * > configManager
Reference< LoginEnumCluster * > enumClusterMessage
Reference< LoginClusterStatus * > clusterStatusMessage
Reference< AccountManager * > accountManager
Friends
class LoginServer
Detailed Description
Definition at line 190 of file LoginServer.h.
Constructor & Destructor Documentation
LoginServerImplementation::LoginServerImplementation (ConfigManager * config)
Definition at line 60 of file LoginServerImplementation.cpp.
References accountManager, clusterStatusMessage, configManager, datagramService, enumClusterMessage, loginHandler, phandler, and processor.
LoginServerImplementation::LoginServerImplementation (DummyConstructorParameter * param)
Definition at line 276 of file LoginServer.cpp.
References _initializeImplementation().
LoginServerImplementation::~LoginServerImplementation () protected virtual
Definition at line 281 of file LoginServer.cpp.
Member Function Documentation
DistributedObjectStub * LoginServerImplementation::_getStub ()
Definition at line 301 of file LoginServer.cpp.
References _this.
void LoginServerImplementation::_initializeImplementation () protected
Definition at line 288 of file LoginServer.cpp.
References _serializationHelperMethod(), and _this.
Referenced by LoginServerImplementation().
void LoginServerImplementation::_serializationHelperMethod () protected
Definition at line 337 of file LoginServer.cpp.
Referenced by _initializeImplementation().
void LoginServerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 296 of file LoginServer.cpp.
References _this.
Referenced by server::login::LoginServer::LoginServer().
LoginClient * LoginServerImplementation::createConnection (Socket * sock, SocketAddress & addr)
Definition at line 143 of file LoginServerImplementation.cpp.
References datagramService.
Referenced by server::login::LoginServer::createConnection().
void LoginServerImplementation::finalize () protected
Definition at line 285 of file LoginServer.cpp.
Account * LoginServerImplementation::getAccount (unsigned int accountID)
Definition at line 244 of file LoginServerImplementation.cpp.
References accountManager.
Referenced by server::login::LoginServer::getAccount().
AccountManager * LoginServerImplementation::getAccountManager ()
Definition at line 390 of file LoginServer.cpp.
References accountManager.
Referenced by server::login::LoginServer::getAccountManager().
LoginClient * LoginServerImplementation::getLoginClient (ServiceClient * session)
Definition at line 185 of file LoginServerImplementation.cpp.
References loginHandler.
Referenced by server::login::LoginServer::getLoginClient().
LoginClusterStatus * LoginServerImplementation::getLoginClusterStatusMessage ()
Definition at line 400 of file LoginServer.cpp.
References clusterStatusMessage.
Referenced by server::login::LoginServer::getLoginClusterStatusMessage().
LoginEnumCluster * LoginServerImplementation::getLoginEnumClusterMessage ()
Definition at line 395 of file LoginServer.cpp.
References enumClusterMessage.
Referenced by server::login::LoginServer::getLoginEnumClusterMessage().
bool LoginServerImplementation::handleError (ServiceClient * client, Exception & e)
Definition at line 189 of file LoginServerImplementation.cpp.
Referenced by server::login::LoginServer::handleError().
void LoginServerImplementation::handleMessage (LoginClient * client, Packet * message)
Definition at line 158 of file LoginServerImplementation.cpp.
References server::login::LoginClient::getSession(), and phandler.
Referenced by server::login::LoginServer::handleMessage().
void LoginServerImplementation::initialize ()
Definition at line 92 of file LoginServerImplementation.cpp.
References _this, loginHandler, phandler, populateGalaxyList(), processor, and startManagers().
Referenced by server::login::LoginServer::initialize().
void LoginServerImplementation::initializeTransientMembers ()
Definition at line 84 of file LoginServerImplementation.cpp.
References phandler, and processor.
Referenced by server::login::LoginServer::initializeTransientMembers(), and readObject().
void LoginServerImplementation::lock (bool doLock = true) protected
Definition at line 309 of file LoginServer.cpp.
References _this.
Referenced by printInfo().
void LoginServerImplementation::lock (ManagedObject * obj) protected
Definition at line 313 of file LoginServer.cpp.
References _this.
LoginServerImplementation::operator const LoginServer * ()
Definition at line 305 of file LoginServer.cpp.
void LoginServerImplementation::populateGalaxyList ()
Definition at line 208 of file LoginServerImplementation.cpp.
References clusterStatusMessage, enumClusterMessage, GalaxyList::getGalaxyAddress(), GalaxyList::getGalaxyID(), GalaxyList::getGalaxyName(), GalaxyList::getGalaxyPingPort(), GalaxyList::getGalaxyPort(), GalaxyList::next(), and GalaxyList::size().
Referenced by initialize(), and server::login::LoginServer::populateGalaxyList().
void LoginServerImplementation::printInfo ()
Definition at line 198 of file LoginServerImplementation.cpp.
References datagramService, lock(), and unlock().
Referenced by server::login::LoginServer::printInfo(), and shutdown().
void LoginServerImplementation::processMessage (Message * message)
Definition at line 177 of file LoginServerImplementation.cpp.
References processor.
Referenced by server::login::LoginServer::processMessage().
void LoginServerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 344 of file LoginServer.cpp.
References initializeTransientMembers(), and readObjectMember().
bool LoginServerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 363 of file LoginServer.cpp.
Referenced by readObject().
void LoginServerImplementation::rlock (bool doLock = true) protected
Definition at line 317 of file LoginServer.cpp.
References _this.
void LoginServerImplementation::runlock (bool doLock = true) protected
Definition at line 333 of file LoginServer.cpp.
References _this.
void LoginServerImplementation::shutdown ()
Definition at line 129 of file LoginServerImplementation.cpp.
References printInfo(), and stopManagers().
Referenced by server::login::LoginServer::shutdown().
void LoginServerImplementation::start (int p, int mconn = 10)
Definition at line 119 of file LoginServerImplementation.cpp.
References _this, datagramService, and loginHandler.
Referenced by server::login::LoginServer::start().
void LoginServerImplementation::startManagers ()
Definition at line 109 of file LoginServerImplementation.cpp.
References _this, accountManager, and configManager.
Referenced by initialize(), and server::login::LoginServer::startManagers().
void LoginServerImplementation::stop ()
Definition at line 125 of file LoginServerImplementation.cpp.
References datagramService.
Referenced by server::login::LoginServer::stop().
void LoginServerImplementation::stopManagers ()
Definition at line 137 of file LoginServerImplementation.cpp.
References accountManager.
Referenced by shutdown(), and server::login::LoginServer::stopManagers().
void LoginServerImplementation::unlock (bool doLock = true) protected
Definition at line 329 of file LoginServer.cpp.
References _this.
Referenced by printInfo().
void LoginServerImplementation::wlock (bool doLock = true) protected
Definition at line 321 of file LoginServer.cpp.
References _this.
void LoginServerImplementation::wlock (ManagedObject * obj) protected
Definition at line 325 of file LoginServer.cpp.
References _this.
void LoginServerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 373 of file LoginServer.cpp.
References writeObjectMembers().
int LoginServerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 380 of file LoginServer.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class LoginServer friend
Definition at line 282 of file LoginServer.h.
Member Data Documentation
WeakReference<LoginServer*> server::login::LoginServerImplementation::_this
Definition at line 248 of file LoginServer.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), initialize(), lock(), rlock(), runlock(), start(), startManagers(), unlock(), and wlock().
Reference<AccountManager* > server::login::LoginServerImplementation::accountManager private
Definition at line 205 of file LoginServer.h.
Referenced by getAccount(), getAccountManager(), LoginServerImplementation(), startManagers(), and stopManagers().
Reference<LoginClusterStatus* > server::login::LoginServerImplementation::clusterStatusMessage private
Definition at line 203 of file LoginServer.h.
Referenced by getLoginClusterStatusMessage(), LoginServerImplementation(), and populateGalaxyList().
Reference<ConfigManager* > server::login::LoginServerImplementation::configManager private
Definition at line 199 of file LoginServer.h.
Referenced by LoginServerImplementation(), and startManagers().
Reference<DatagramServiceThread* > server::login::LoginServerImplementation::datagramService private
Definition at line 191 of file LoginServer.h.
Referenced by createConnection(), LoginServerImplementation(), printInfo(), start(), and stop().
Reference<LoginEnumCluster* > server::login::LoginServerImplementation::enumClusterMessage private
Definition at line 201 of file LoginServer.h.
Referenced by getLoginEnumClusterMessage(), LoginServerImplementation(), and populateGalaxyList().
Reference<LoginHandler* > server::login::LoginServerImplementation::loginHandler private
Definition at line 195 of file LoginServer.h.
Referenced by getLoginClient(), initialize(), LoginServerImplementation(), and start().
Reference<BasePacketHandler* > server::login::LoginServerImplementation::phandler private
Definition at line 193 of file LoginServer.h.
Referenced by handleMessage(), initialize(), initializeTransientMembers(), and LoginServerImplementation().
Reference<LoginProcessServerImplementation* > server::login::LoginServerImplementation::processor private
Definition at line 197 of file LoginServer.h.
Referenced by initialize(), initializeTransientMembers(), LoginServerImplementation(), and processMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginServer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginServer.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginServerImplementation.cpp