Core3: server::zone::objects::player::sui::listbox::SuiListBox Class Reference
server::zone::objects::player::sui::listbox::SuiListBox Class Reference
#include <SuiListBox.h>
Public Member Functions
SuiListBox (CreatureObject *player, unsigned int windowType=0, unsigned int listBoxType=0)
void init ()
void addMenuItem (const String &name, unsigned long long objectID=0)
String getMenuItemName (int index)
void removeAllMenuItems ()
unsigned long long getMenuObjectID (unsigned int idx)
int getMenuSize ()
BaseMessage * generateMessage ()
void setNextBox (unsigned int boxID)
void setPreviousBox (unsigned int boxID)
unsigned long long getNextBox ()
unsigned long long getPreviousBox ()
bool isListBox ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::player::sui::SuiBox
SuiBox (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
void initialize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateMessage ()
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
bool isInputBox ()
bool isListBox ()
bool isMessageBox ()
bool isTransferBox ()
bool isBankTransferBox ()
bool isSlicingBox ()
bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int MSGSELECTED = 0
static const int HANDLESINGLEBUTTON = 1
static const int HANDLETWOBUTTON = 2
static const int HANDLETHREEBUTTON = 3
Static Public Attributes inherited from server::zone::objects::player::sui::SuiBox
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Protected Member Functions
SuiListBox (DummyConstructorParameter *param)
virtual ~SuiListBox ()
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBox
SuiBox (DummyConstructorParameter *param)
virtual ~SuiBox ()
Friends
class SuiListBoxHelper
Detailed Description
Definition at line 73 of file SuiListBox.h.
Constructor & Destructor Documentation
SuiListBox::SuiListBox (CreatureObject * player, unsigned int windowType = 0, unsigned int listBoxType = 0)
Definition at line 19 of file SuiListBox.cpp.
References server::zone::objects::player::sui::listbox::SuiListBoxImplementation::_setStub().
SuiListBox::SuiListBox (DummyConstructorParameter * param) protected
Definition at line 26 of file SuiListBox.cpp.
SuiListBox::~SuiListBox () protected virtual
Definition at line 30 of file SuiListBox.cpp.
Member Function Documentation
DistributedObjectServant * SuiListBox::_getImplementation ()
Definition at line 199 of file SuiListBox.cpp.
Referenced by addMenuItem(), generateMessage(), getMenuItemName(), getMenuObjectID(), getMenuSize(), getNextBox(), getPreviousBox(), init(), isListBox(), removeAllMenuItems(), setNextBox(), and setPreviousBox().
DistributedObjectServant * SuiListBox::_getImplementationForRead ()
Definition at line 205 of file SuiListBox.cpp.
void SuiListBox::_setImplementation (DistributedObjectServant * servant)
Definition at line 209 of file SuiListBox.cpp.
void SuiListBox::addMenuItem (const String & name, unsigned long long objectID = 0)
Use to add Menu Item to the ListBox Sui class. List will be looped through in generateBody
Definition at line 48 of file SuiListBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::addMenuItem(), and RPC_ADDMENUITEM__STRING_LONG_.
Referenced by VendorSelectionNode::addChildrenToListBox(), server::zone::objects::resource::ResourceSpawnImplementation::addStatsToDeedListBox(), ResourceTreeNode::addToSuiListBox(), ResourceMap::addToSuiListBox(), server::zone::objects::player::sessions::SlicingSessionImplementation::generateSliceMenu(), BlueprintEntry::insertFactoryIngredient(), and server::zone::managers::vendor::VendorManager::sendRegisterVendorTo().
BaseMessage * SuiListBox::generateMessage ()
Definition at line 119 of file SuiListBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage(), and RPC_GENERATEMESSAGE__.
Referenced by server::zone::objects::player::sessions::SlicingSessionImplementation::generateSliceMenu(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSlice(), and server::zone::managers::vendor::VendorManager::sendRegisterVendorTo().
String SuiListBox::getMenuItemName (int index)
Definition at line 63 of file SuiListBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::getMenuItemName(), and RPC_GETMENUITEMNAME__INT_.
Referenced by PlayerManagementSessionSuiCallback::getPlayerGalaxyID(), server::zone::managers::sui::SuiManager::handleConsentBox(), AdBarkingPhraseSuiCallback::handleSelectAnimation(), AdBarkingPhraseSuiCallback::handleSelectMood(), AdBarkingPhraseSuiCallback::handleSelectPhrase(), server::zone::managers::sui::SuiManager::handleStartDancing(), server::zone::managers::sui::SuiManager::handleStartMusic(), FindSessionSuiCallback::run(), RegisterVendorSuiCallback::run(), CitySpecializationSuiCallback::run(), and PlayerManagementSessionSuiCallback::runAccountInfo().
unsigned long long SuiListBox::getMenuObjectID (unsigned int idx)
Definition at line 92 of file SuiListBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::getMenuObjectID(), and RPC_GETMENUOBJECTID__INT_.
Referenced by AdBarkingPhraseSuiCallback::handleSelectPhrase(), TicketSelectionSuiCallback::run(), SlicingSessionSuiCallback::run(), HQDefenseStatusSuiCallback::run(), CreateVendorSuiCallback::run(), GuildAddEnemySuiCallback::run(), DonateDefenseSuiCallback::run(), TurretControlSuiCallback::run(), CloningRequestSuiCallback::run(), CityManageMilitiaSuiCallback::run(), CityAdjustTaxSuiCallback::run(), and CityMayoralVoteSuiCallback::run().
int SuiListBox::getMenuSize ()
Definition at line 106 of file SuiListBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::getMenuSize(), and RPC_GETMENUSIZE__.
Referenced by GuildAddEnemySuiCallback::run(), CloningRequestSuiCallback::run(), CityMayoralVoteSuiCallback::run(), and CityAdjustTaxSuiCallback::run().
unsigned long long SuiListBox::getNextBox ()
Definition at line 160 of file SuiListBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::getNextBox(), and RPC_GETNEXTBOX__.
unsigned long long SuiListBox::getPreviousBox ()
Definition at line 173 of file SuiListBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::getPreviousBox(), and RPC_GETPREVIOUSBOX__.
void SuiListBox::init ()
Definition at line 35 of file SuiListBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::init(), and RPC_INIT__.
bool SuiListBox::isListBox ()
Definition at line 186 of file SuiListBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::isListBox(), and RPC_ISLISTBOX__.
void SuiListBox::removeAllMenuItems ()
Clears all Menu Items from the list box
Warning
If you are going to reuse the SuiBox object and call this method, you most likely need to call clearOptions() in SuiBoxImplementation
Definition at line 79 of file SuiListBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::removeAllMenuItems(), and RPC_REMOVEALLMENUITEMS__.
Referenced by server::zone::objects::player::sessions::SlicingSessionImplementation::generateSliceMenu(), and server::zone::objects::player::sessions::SlicingSessionImplementation::handleSlice().
void SuiListBox::setNextBox (unsigned int boxID)
Definition at line 132 of file SuiListBox.cpp.
References _getImplementation(), RPC_SETNEXTBOX__INT_, and server::zone::objects::player::sui::listbox::SuiListBoxImplementation::setNextBox().
void SuiListBox::setPreviousBox (unsigned int boxID)
Definition at line 146 of file SuiListBox.cpp.
References _getImplementation(), RPC_SETPREVIOUSBOX__INT_, and server::zone::objects::player::sui::listbox::SuiListBoxImplementation::setPreviousBox().
Friends And Related Function Documentation
friend class SuiListBoxHelper friend
Definition at line 126 of file SuiListBox.h.
Member Data Documentation
const int server::zone::objects::player::sui::listbox::SuiListBox::HANDLESINGLEBUTTON = 1 static
Definition at line 77 of file SuiListBox.h.
const int server::zone::objects::player::sui::listbox::SuiListBox::HANDLETHREEBUTTON = 3 static
Definition at line 81 of file SuiListBox.h.
const int server::zone::objects::player::sui::listbox::SuiListBox::HANDLETWOBUTTON = 2 static
Definition at line 79 of file SuiListBox.h.
const int server::zone::objects::player::sui::listbox::SuiListBox::MSGSELECTED = 0 static
Definition at line 75 of file SuiListBox.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/listbox/SuiListBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/listbox/SuiListBox.cpp