Core3: ShellfishHarvesterMenuComponent Class Reference
ShellfishHarvesterMenuComponent Class Reference
#include <ShellfishHarvesterMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file ShellfishHarvesterMenuComponent.h.
Member Function Documentation
void ShellfishHarvesterMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from TangibleObjectMenuComponent.
Definition at line 18 of file ShellfishHarvesterMenuComponent.cpp.
References TangibleObjectMenuComponent::fillObjectMenuResponse(), and server::zone::objects::scene::SceneObject::isTangibleObject().
int ShellfishHarvesterMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from TangibleObjectMenuComponent.
Definition at line 31 of file ShellfishHarvesterMenuComponent.cpp.
References server::zone::ZoneProcessServer::getForageManager(), server::zone::objects::scene::SceneObject::getZoneProcessServer(), TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::scene::SceneObject::isASubChildOf(), server::zone::objects::scene::SceneObject::isTangibleObject(), and server::zone::managers::minigames::ForageManager::startForaging().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/generic/ShellfishHarvesterMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/generic/ShellfishHarvesterMenuComponent.cpp