Core3: server::zone::objects::tangible::pharmaceutical::WoundPack Class Reference
server::zone::objects::tangible::pharmaceutical::WoundPack Class Reference
#include <WoundPack.h>
Public Member Functions
WoundPack ()
void updateCraftingValues (CraftingValues *values, bool firstUpdate)
void loadTemplateData (SharedObjectTemplate *templateData)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
unsigned int calculatePower (CreatureObject *healer, CreatureObject *patient, bool applyBattleFatigue=true)
float getEffectiveness ()
bool isWoundPack ()
byte getAttribute ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::tangible::pharmaceutical::PharmaceuticalObject
PharmaceuticalObject ()
int getMedicineUseRequired ()
float getRange (CreatureObject *creature=NULL)
bool isArea ()
float getArea ()
bool isPharmaceuticalObject ()
bool isStimPack ()
bool isRangedStimPack ()
bool isEnhancePack ()
bool isWoundPack ()
bool isCurePack ()
bool isStatePack ()
bool isRevivePack ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::tangible::TangibleObject
TangibleObject ()
void initializeMembers ()
void addTemplateSkillMods (TangibleObject *targetObject)
void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
void removeSkillModsFrom (CreatureObject *creature)
void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
void removeAllSkillModsOfType (const int skillType, bool notifyClient=true)
void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void sendBaselinesTo (SceneObject *player)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
void removeDefenders ()
void setCombatState ()
void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void clearCombatState (bool clearDefenders=true)
bool hasDefender (SceneObject *defender)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
bool isHealableBy (CreatureObject *object)
void sendPvpStatusTo (CreatureObject *player)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
void updateCraftingValues (CraftingValues *values, bool firstUpdate)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
bool isKiller ()
bool isTicketCollector ()
bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
int getUseCount ()
int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
int getJunkDealerNeeded ()
void setJunkValue (int jValue)
int getJunkValue ()
void setSerialNumber (const String &serial)
void setLevel (int lev)
String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
String repairAttempt (int repairChance)
bool isBroken ()
float getHitChance ()
void broadcastPvpStatusBitmask ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject ()
void initializePrivateData ()
void loadTemplateData (SharedObjectTemplate *templateData)
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendAttributeListTo (CreatureObject *object)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
void openContainerTo (CreatureObject *player)
byte checkContainerPermission (CreatureObject *player, unsigned short permission)
void closeContainerTo (CreatureObject *player, bool notify=true)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets=true)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
String getDetailedDescription ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
WoundPack (DummyConstructorParameter *param)
virtual ~WoundPack ()
Protected Member Functions inherited from server::zone::objects::tangible::pharmaceutical::PharmaceuticalObject
PharmaceuticalObject (DummyConstructorParameter *param)
virtual ~PharmaceuticalObject ()
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObject
TangibleObject (DummyConstructorParameter *param)
virtual ~TangibleObject ()
Protected Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject (DummyConstructorParameter *param)
virtual ~SceneObject ()
Friends
class WoundPackHelper
Detailed Description
Definition at line 148 of file WoundPack.h.
Constructor & Destructor Documentation
WoundPack::WoundPack ()
Definition at line 31 of file WoundPack.cpp.
References server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::_setStub().
WoundPack::WoundPack (DummyConstructorParameter * param) protected
Definition at line 38 of file WoundPack.cpp.
WoundPack::~WoundPack () protected virtual
Definition at line 42 of file WoundPack.cpp.
Member Function Documentation
DistributedObjectServant * WoundPack::_getImplementation ()
Definition at line 144 of file WoundPack.cpp.
Referenced by calculatePower(), fillAttributeList(), getAttribute(), getEffectiveness(), handleObjectMenuSelect(), isWoundPack(), loadTemplateData(), and updateCraftingValues().
DistributedObjectServant * WoundPack::_getImplementationForRead ()
Definition at line 150 of file WoundPack.cpp.
void WoundPack::_setImplementation (DistributedObjectServant * servant)
Definition at line 154 of file WoundPack.cpp.
unsigned int WoundPack::calculatePower (CreatureObject * healer, CreatureObject * patient, bool applyBattleFatigue = true)
Definition at line 89 of file WoundPack.cpp.
References _getImplementation(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::calculatePower(), and RPC_CALCULATEPOWER__CREATUREOBJECT_CREATUREOBJECT_BOOL_.
void WoundPack::fillAttributeList (AttributeListMessage * msg, CreatureObject * object)
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Definition at line 65 of file WoundPack.cpp.
References _getImplementation(), and server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::fillAttributeList().
byte WoundPack::getAttribute ()
Definition at line 131 of file WoundPack.cpp.
References _getImplementation(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::getAttribute(), and RPC_GETATTRIBUTE__.
Referenced by HealWoundCommand::findWoundPack().
float WoundPack::getEffectiveness ()
Definition at line 105 of file WoundPack.cpp.
References _getImplementation(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::getEffectiveness(), and RPC_GETEFFECTIVENESS__.
int WoundPack::handleObjectMenuSelect (CreatureObject * player, byte selectedID)
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player CreatureObject that selected the option
selectedID selected menu id
Returns
0 if successfull
Definition at line 74 of file WoundPack.cpp.
References _getImplementation(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::handleObjectMenuSelect(), and RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_.
bool WoundPack::isWoundPack ()
Definition at line 118 of file WoundPack.cpp.
References _getImplementation(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::isWoundPack(), and RPC_ISWOUNDPACK__.
void WoundPack::loadTemplateData (SharedObjectTemplate * templateData)
Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
Precondition
{ templateData is a valid pointer }
Postcondition
{ TangibleObject members are initialized }
Parameters
templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
Definition at line 56 of file WoundPack.cpp.
References _getImplementation(), and server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::loadTemplateData().
void WoundPack::updateCraftingValues (CraftingValues * values, bool firstUpdate)
Definition at line 47 of file WoundPack.cpp.
References _getImplementation(), and server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::updateCraftingValues().
Friends And Related Function Documentation
friend class WoundPackHelper friend
Definition at line 199 of file WoundPack.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/pharmaceutical/WoundPack.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/pharmaceutical/WoundPack.cpp