Core3: server::zone::ZoneHandler Class Reference
server::zone::ZoneHandler Class Reference
#include <ZoneHandler.h>
Public Member Functions
ZoneHandler (ZoneServer *server)
void initialize ()
ServiceClient * createConnection (Socket *sock, SocketAddress &addr)
bool deleteConnection (ServiceClient *session)
void handleMessage (ServiceClient *session, Packet *message)
void processMessage (Message *message)
bool handleError (ServiceClient *session, Exception &e)
ZoneClientSession * getClientSession (ServiceClient *session)
Private Attributes
ManagedReference< ZoneServer * > zoneServerRef
ZoneSessionMap clients
Detailed Description
Definition at line 82 of file ZoneHandler.h.
Constructor & Destructor Documentation
server::zone::ZoneHandler::ZoneHandler (ZoneServer * server) inline
Definition at line 88 of file ZoneHandler.h.
References zoneServerRef.
Member Function Documentation
ServiceClient* server::zone::ZoneHandler::createConnection (Socket * sock, SocketAddress & addr) inline
Definition at line 98 of file ZoneHandler.h.
References server::zone::ZoneSessionMap::add(), clients, server::zone::ZoneServer::createConnection(), server::zone::ZoneClientSession::getSession(), and zoneServerRef.
bool server::zone::ZoneHandler::deleteConnection (ServiceClient * session) inline
Definition at line 108 of file ZoneHandler.h.
References clients, server::zone::ZoneClientSession::disconnect(), getClientSession(), and server::zone::ZoneSessionMap::remove().
ZoneClientSession* server::zone::ZoneHandler::getClientSession (ServiceClient * session) inline
Definition at line 142 of file ZoneHandler.h.
References clients.
Referenced by deleteConnection(), handleError(), and handleMessage().
bool server::zone::ZoneHandler::handleError (ServiceClient * session, Exception & e) inline
Definition at line 134 of file ZoneHandler.h.
References getClientSession(), server::zone::ZoneServer::handleError(), and zoneServerRef.
void server::zone::ZoneHandler::handleMessage (ServiceClient * session, Packet * message) inline
Definition at line 120 of file ZoneHandler.h.
References getClientSession(), server::zone::ZoneServer::handleMessage(), and zoneServerRef.
void server::zone::ZoneHandler::initialize () inline
Definition at line 92 of file ZoneHandler.h.
References server::zone::ZoneServer::initialize(), and zoneServerRef.
void server::zone::ZoneHandler::processMessage (Message * message) inline
Definition at line 128 of file ZoneHandler.h.
References server::zone::ZoneServer::processMessage(), and zoneServerRef.
Member Data Documentation
ZoneSessionMap server::zone::ZoneHandler::clients private
Definition at line 85 of file ZoneHandler.h.
Referenced by createConnection(), deleteConnection(), and getClientSession().
ManagedReference<ZoneServer*> server::zone::ZoneHandler::zoneServerRef private
Definition at line 83 of file ZoneHandler.h.
Referenced by createConnection(), handleError(), handleMessage(), initialize(), processMessage(), and ZoneHandler().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneHandler.h