Core3: server::zone::managers::minigames::GamblingManager Class Reference
server::zone::managers::minigames::GamblingManager Class Reference
#include <GamblingManager.h>
Public Member Functions
GamblingManager ()
Vector< String > * getRoulette ()
void initializeSlotTimer ()
void initializeRouletteTimer ()
void initializeSlots ()
void initializeRouletteRed ()
void initializeRoulette ()
int notify (SceneObject *sceneObject)
bool isHigh (int value)
bool isLow (int value)
bool isEven (int value)
bool isOdd (int value)
bool isBlack (int value)
bool isRed (int value)
void handleSlot (CreatureObject *player, bool cancel, bool other)
void bet (CreatureObject *player, int amount, int target, int machineType)
void bet (GamblingTerminal *terminal, CreatureObject *player, int amount, int target)
void startGame (CreatureObject *player, int machineType)
void startGame (GamblingTerminal *terminal)
void leaveTerminal (CreatureObject *player, int machineType)
void registerPlayer (GamblingTerminal *terminal, CreatureObject *player)
void refreshRouletteMenu (CreatureObject *player)
void continueGame (GamblingTerminal *terminal)
void stopGame (GamblingTerminal *terminal, bool cancel)
void calculateOutcome (GamblingTerminal *terminal)
unsigned int createWindow (GamblingTerminal *terminal, CreatureObject *player)
unsigned int createPayoutWindow (CreatureObject *player)
unsigned int createSlotWindow (CreatureObject *player, unsigned int payoutBoxID)
unsigned int createRouletteWindow (CreatureObject *player)
void createEvent (GamblingTerminal *terminal, int time)
bool isPlaying (CreatureObject *player)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
GamblingManager (DummyConstructorParameter *param)
virtual ~GamblingManager ()
Friends
class GamblingManagerHelper
Detailed Description
Definition at line 115 of file GamblingManager.h.
Constructor & Destructor Documentation
GamblingManager::GamblingManager ()
Definition at line 25 of file GamblingManager.cpp.
References server::zone::managers::minigames::GamblingManagerImplementation::_setStub().
GamblingManager::GamblingManager (DummyConstructorParameter * param) protected
Definition at line 32 of file GamblingManager.cpp.
GamblingManager::~GamblingManager () protected virtual
Definition at line 36 of file GamblingManager.cpp.
Member Function Documentation
DistributedObjectServant * GamblingManager::_getImplementation ()
Definition at line 466 of file GamblingManager.cpp.
Referenced by bet(), calculateOutcome(), continueGame(), createEvent(), createPayoutWindow(), createRouletteWindow(), createSlotWindow(), createWindow(), getRoulette(), handleSlot(), initializeRoulette(), initializeRouletteRed(), initializeRouletteTimer(), initializeSlots(), initializeSlotTimer(), isBlack(), isEven(), isHigh(), isLow(), isOdd(), isPlaying(), isRed(), leaveTerminal(), notify(), refreshRouletteMenu(), registerPlayer(), startGame(), and stopGame().
DistributedObjectServant * GamblingManager::_getImplementationForRead ()
Definition at line 472 of file GamblingManager.cpp.
void GamblingManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 476 of file GamblingManager.cpp.
void GamblingManager::bet (CreatureObject * player, int amount, int target, int machineType)
Accept bet from /bet command This method receives the player who wants to bet, the amount he wants to bet, and the target he's betting on and calls bet(terminal, player, amount, target)
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject betting money
amount Amount of Credits to bet
target Target field (remains empty for slotMachine)
Definition at line 229 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::bet(), and RPC_BET__CREATUREOBJECT_INT_INT_INT_.
Referenced by BetCommand::doQueueCommand().
void GamblingManager::bet (GamblingTerminal * terminal, CreatureObject * player, int amount, int target)
Accept bet from /bet command or startGame This method receives the player who wants to bet, the amount he wants to bet, and the target he's betting on The method creates a bet and adds it to the GamblingTerminal's bets VectorMap
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
terminal GamblingTerminal for which to add bet
player CreatureObject betting money
amount Amount of Credits to bet
target Target field (remains empty for slotMachine)
Definition at line 246 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::bet(), and RPC_BET__GAMBLINGTERMINAL_CREATUREOBJECT_INT_INT_.
void GamblingManager::calculateOutcome (GamblingTerminal * terminal)
Calculates the results of each players' bets This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 365 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::calculateOutcome(), and RPC_CALCULATEOUTCOME__GAMBLINGTERMINAL_.
void GamblingManager::continueGame (GamblingTerminal * terminal)
Continues the Game This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 336 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::continueGame(), and RPC_CONTINUEGAME__GAMBLINGTERMINAL_.
void GamblingManager::createEvent (GamblingTerminal * terminal, int time)
Creates Events This method receives a Terminal and a time, creates a GamblingEvent, stores it in the Terminal and schedules it to time
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
terminal GamblingTerminal for which to create event
time Time in ms to schedule the Task
Definition at line 437 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::createEvent(), and RPC_CREATEEVENT__GAMBLINGTERMINAL_INT_.
unsigned int GamblingManager::createPayoutWindow (CreatureObject * player)
Creates the SlotPayoutWindow This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 394 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::createPayoutWindow(), and RPC_CREATEPAYOUTWINDOW__CREATUREOBJECT_.
unsigned int GamblingManager::createRouletteWindow (CreatureObject * player)
Creates the RouletteWindow This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 423 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::createRouletteWindow(), and RPC_CREATEROULETTEWINDOW__CREATUREOBJECT_.
unsigned int GamblingManager::createSlotWindow (CreatureObject * player, unsigned int payoutBoxID)
Creates the SlotWindow This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
payoutBoxID boxID of the payout menu so it can be closed later
Definition at line 408 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::createSlotWindow(), and RPC_CREATESLOTWINDOW__CREATUREOBJECT_INT_.
unsigned int GamblingManager::createWindow (GamblingTerminal * terminal, CreatureObject * player)
Creates the Windows This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 379 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::createWindow(), and RPC_CREATEWINDOW__GAMBLINGTERMINAL_CREATUREOBJECT_.
Vector< String > * GamblingManager::getRoulette ()
Definition at line 41 of file GamblingManager.cpp.
References _getImplementation(), and server::zone::managers::minigames::GamblingManagerImplementation::getRoulette().
Referenced by BetCommand::doQueueCommand().
void GamblingManager::handleSlot (CreatureObject * player, bool cancel, bool other)
Definition at line 213 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::handleSlot(), and RPC_HANDLESLOT__CREATUREOBJECT_BOOL_BOOL_.
void GamblingManager::initializeRoulette ()
Definition at line 102 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::initializeRoulette(), and RPC_INITIALIZEROULETTE__.
void GamblingManager::initializeRouletteRed ()
Definition at line 89 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::initializeRouletteRed(), and RPC_INITIALIZEROULETTERED__.
void GamblingManager::initializeRouletteTimer ()
Definition at line 63 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::initializeRouletteTimer(), and RPC_INITIALIZEROULETTETIMER__.
void GamblingManager::initializeSlots ()
Definition at line 76 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::initializeSlots(), and RPC_INITIALIZESLOTS__.
void GamblingManager::initializeSlotTimer ()
Definition at line 50 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::initializeSlotTimer(), and RPC_INITIALIZESLOTTIMER__.
bool GamblingManager::isBlack (int value)
Definition at line 185 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::isBlack(), and RPC_ISBLACK__INT_.
bool GamblingManager::isEven (int value)
Definition at line 157 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::isEven(), and RPC_ISEVEN__INT_.
bool GamblingManager::isHigh (int value)
Definition at line 129 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::isHigh(), and RPC_ISHIGH__INT_.
bool GamblingManager::isLow (int value)
Definition at line 143 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::isLow(), and RPC_ISLOW__INT_.
bool GamblingManager::isOdd (int value)
Definition at line 171 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::isOdd(), and RPC_ISODD__INT_.
bool GamblingManager::isPlaying (CreatureObject * player)
Definition at line 452 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::isPlaying(), and RPC_ISPLAYING__CREATUREOBJECT_.
Referenced by BetCommand::doQueueCommand().
bool GamblingManager::isRed (int value)
Definition at line 199 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::isRed(), and RPC_ISRED__INT_.
void GamblingManager::leaveTerminal (CreatureObject * player, int machineType)
LeaveTerminal called by SuiManager This method receives a CreatureObject, looks it up in the machineType's corresponding VectorMap and then calls Terminal::leaveTerminal(player)
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject who wants to leave the Terminal
machineType machine type of the Terminal, set in the SuiManager
Definition at line 292 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::leaveTerminal(), and RPC_LEAVETERMINAL__CREATUREOBJECT_INT_.
Referenced by GamblingRouletteSuiCallback::run().
int GamblingManager::notify (SceneObject * sceneObject)
Definition at line 115 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::notify(), and RPC_NOTIFY__SCENEOBJECT_.
void GamblingManager::refreshRouletteMenu (CreatureObject * player)
Refreshes the menu This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 322 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::refreshRouletteMenu(), and RPC_REFRESHROULETTEMENU__CREATUREOBJECT_.
Referenced by GamblingRouletteSuiCallback::run().
void GamblingManager::registerPlayer (GamblingTerminal * terminal, CreatureObject * player)
Adds player to VectorMap This method switches machineTypes adding the Player and GamblingTerminal to the machineType's corresponding VectorMap
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
terminal GamblingTerminal to register
player CreatureObject to register
Definition at line 307 of file GamblingManager.cpp.
References _getImplementation(), server::zone::managers::minigames::GamblingManagerImplementation::registerPlayer(), and RPC_REGISTERPLAYER__GAMBLINGTERMINAL_CREATUREOBJECT_.
void GamblingManager::startGame (CreatureObject * player, int machineType)
StartGame called by SuiManager This method receives a CreatureObject, looks it up in the machineType's corresponding VectorMap and then calls startGame(Terminal)
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to start the Game
machineType machine type of the Terminal, set in the SuiManager
Definition at line 263 of file GamblingManager.cpp.
References _getImplementation(), RPC_STARTGAME__CREATUREOBJECT_INT_, and server::zone::managers::minigames::GamblingManagerImplementation::startGame().
void GamblingManager::startGame (GamblingTerminal * terminal)
Starts Game This method receives a GamblingTerminal, starting the Event cycle of the Game
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
terminal GamblingTerminal for which to start the game
Definition at line 278 of file GamblingManager.cpp.
References _getImplementation(), RPC_STARTGAME__GAMBLINGTERMINAL_, and server::zone::managers::minigames::GamblingManagerImplementation::startGame().
void GamblingManager::stopGame (GamblingTerminal * terminal, bool cancel)
Ends the Game This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 350 of file GamblingManager.cpp.
References _getImplementation(), RPC_STOPGAME__GAMBLINGTERMINAL_BOOL_, and server::zone::managers::minigames::GamblingManagerImplementation::stopGame().
Friends And Related Function Documentation
friend class GamblingManagerHelper friend
Definition at line 317 of file GamblingManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/GamblingManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/GamblingManager.cpp