Core3: EndDuelCommand Class Reference
EndDuelCommand Class Reference
#include <EndDuelCommand.h>
Public Member Functions
EndDuelCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file EndDuelCommand.h.
Constructor & Destructor Documentation
EndDuelCommand::EndDuelCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file EndDuelCommand.h.
Member Function Documentation
int EndDuelCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 58 of file EndDuelCommand.h.
References CombatManager::freeDuelList(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and CombatManager::requestEndDuel().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/EndDuelCommand.h