Core3: server::zone::managers::player::creation::PlayerCreationManager Class Reference
server::zone::managers::player::creation::PlayerCreationManager Class Reference
#include <PlayerCreationManager.h>
Public Member Functions
PlayerCreationManager ()
~PlayerCreationManager ()
bool validateCharacterName (const String &characterName)
bool createCharacter (MessageCallback *data)
int getMaximumAttributeLimit (const String &race, int attributeNumber)
int getMinimumAttributeLimit (const String &race, int attributeNumber)
int getTotalAttributeLimit (const String &race)
void addStartingWeaponsInto (CreatureObject *creature, SceneObject *container)
void addStartingItemsInto (CreatureObject *creature, SceneObject *container)
Private Member Functions
void loadLuaConfig ()
void loadRacialCreationData ()
void loadDefaultCharacterItems ()
void loadProfessionDefaultsInfo ()
void loadHairStyleInfo ()
void loadLuaStartingItems (Lua *lua)
void addCustomization (CreatureObject *creature, const String &customizationString, const String &appearanceFilename)
void addHair (CreatureObject *creature, const String &hairTemplate, const String &hairCustomization)
void addRacialMods (CreatureObject *creature, const String &race, Vector< String > *startingSkills, Vector< String > *startingItems, bool equipmentOnly)
void addStartingItems (CreatureObject *creature, const String &clientTemplate, bool equipmentOnly)
void addProfessionStartingItems (CreatureObject *creature, const String &profession, const String &clientTemplate, bool equipmentOnly)
Private Attributes
ManagedReference< ZoneServer * > zoneServer
VectorMap< String, Reference
< RacialCreationData * > > racialCreationData
VectorMap< String, Reference
< ProfessionDefaultsInfo * > > professionDefaultsInfo
VectorMap< String,
SortedVector< String > > defaultCharacterEquipment
VectorMap< String, Reference
< HairStyleInfo * > > hairStyleInfo
Vector< String > commonStartingItems
int startingCash
int startingBank
int skillPoints
bool freeGodMode
HashTable< uint32, Time > lastCreatedCharacter
Mutex charCountMutex
Detailed Description
Definition at line 104 of file PlayerCreationManager.h.
Constructor & Destructor Documentation
PlayerCreationManager::PlayerCreationManager ()
Definition at line 73 of file PlayerCreationManager.cpp.
References freeGodMode, ServerCore::getZoneServer(), hairStyleInfo, loadDefaultCharacterItems(), loadHairStyleInfo(), loadLuaConfig(), loadProfessionDefaultsInfo(), loadRacialCreationData(), professionDefaultsInfo, racialCreationData, startingBank, startingCash, and zoneServer.
PlayerCreationManager::~PlayerCreationManager ()
Definition at line 97 of file PlayerCreationManager.cpp.
Member Function Documentation
void PlayerCreationManager::addCustomization (CreatureObject * creature, const String & customizationString, const String & appearanceFilename) private
Definition at line 852 of file PlayerCreationManager.cpp.
References CustomizationVariables::parseFromClientString(), server::zone::objects::tangible::TangibleObject::setCustomizationString(), and ImageDesignManager::validateCustomizationString().
Referenced by createCharacter().
void PlayerCreationManager::addHair (CreatureObject * creature, const String & hairTemplate, const String & hairCustomization) private
Definition at line 793 of file PlayerCreationManager.cpp.
References server::zone::templates::SharedObjectTemplate::getAppearanceFilename(), server::zone::templates::SharedObjectTemplate::getFullTemplateString(), server::zone::objects::scene::SceneObject::getObjectTemplate(), HairAssetData::getServerPlayerTemplate(), hairStyleInfo, HairAssetData::isAvailableAtCreation(), CustomizationVariables::parseFromClientString(), server::zone::objects::scene::SceneObject::setContainerDefaultDenyPermission(), server::zone::objects::scene::SceneObject::setContainerDenyPermission(), server::zone::objects::tangible::TangibleObject::setCustomizationString(), server::zone::objects::scene::SceneObject::transferObject(), ImageDesignManager::validateCustomizationString(), and zoneServer.
Referenced by createCharacter().
void PlayerCreationManager::addProfessionStartingItems (CreatureObject * creature, const String & profession, const String & clientTemplate, bool equipmentOnly) private
Definition at line 717 of file PlayerCreationManager.cpp.
References server::zone::objects::scene::SceneObject::canAddObject(), server::zone::managers::player::creation::ProfessionDefaultsInfo::getAttributeMod(), server::zone::managers::player::creation::ProfessionDefaultsInfo::getProfessionItems(), server::zone::managers::player::creation::ProfessionDefaultsInfo::getSkill(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::managers::player::creation::ProfessionDefaultsInfo::getStartingItems(), professionDefaultsInfo, server::zone::objects::creature::CreatureObject::setBaseHAM(), server::zone::objects::creature::CreatureObject::setHAM(), server::zone::objects::creature::CreatureObject::setMaxHAM(), server::zone::objects::scene::SceneObject::transferObject(), and zoneServer.
Referenced by createCharacter().
void PlayerCreationManager::addRacialMods (CreatureObject * creature, const String & race, Vector< String > * startingSkills, Vector< String > * startingItems, bool equipmentOnly) private
Definition at line 1005 of file PlayerCreationManager.cpp.
References server::zone::objects::creature::CreatureObject::getBaseHAM(), server::zone::objects::scene::SceneObject::getSlottedObject(), racialCreationData, server::zone::objects::creature::CreatureObject::setBaseHAM(), server::zone::objects::creature::CreatureObject::setHAM(), server::zone::objects::creature::CreatureObject::setMaxHAM(), server::zone::objects::scene::SceneObject::transferObject(), and zoneServer.
Referenced by createCharacter().
void PlayerCreationManager::addStartingItems (CreatureObject * creature, const String & clientTemplate, bool equipmentOnly) private
Definition at line 675 of file PlayerCreationManager.cpp.
References server::zone::objects::scene::SceneObject::canAddObject(), commonStartingItems, defaultCharacterEquipment, server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::transferObject(), and zoneServer.
Referenced by createCharacter().
void PlayerCreationManager::addStartingItemsInto (CreatureObject * creature, SceneObject * container)
Adds starting Items except Weapons into the target container
Parameters
creature the player creature
container the target container
Definition at line 864 of file PlayerCreationManager.cpp.
References commonStartingItems, server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::player::PlayerObject::getStarterProfession(), PlayerCreatureTemplate::getStartingItems(), server::zone::managers::player::creation::ProfessionDefaultsInfo::getStartingItems(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::isWeaponObject(), professionDefaultsInfo, server::zone::objects::scene::SceneObject::transferObject(), and zoneServer.
Referenced by server::zone::managers::director::DirectorManager::addStartingItemsInto().
void PlayerCreationManager::addStartingWeaponsInto (CreatureObject * creature, SceneObject * container)
Adds starting Weapons into the target container
Parameters
creature the player creature
container the target container
Definition at line 933 of file PlayerCreationManager.cpp.
References commonStartingItems, server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::player::PlayerObject::getStarterProfession(), PlayerCreatureTemplate::getStartingItems(), server::zone::managers::player::creation::ProfessionDefaultsInfo::getStartingItems(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::isWeaponObject(), professionDefaultsInfo, server::zone::objects::scene::SceneObject::transferObject(), and zoneServer.
Referenced by server::zone::managers::director::DirectorManager::addStartingWeaponsInto().
bool PlayerCreationManager::createCharacter (MessageCallback * data)
Attempts to create a character, validating the information passed back by the client.
Definition at line 372 of file PlayerCreationManager.cpp.
References addCustomization(), addHair(), server::chat::ChatManager::addPlayer(), server::zone::managers::player::PlayerManager::addPlayer(), addProfessionStartingItems(), addRacialMods(), addStartingItems(), charCountMutex, server::zone::managers::player::PlayerManager::checkPlayerName(), server::zone::managers::player::PlayerManager::createSkippedTutorialBuilding(), server::zone::managers::player::PlayerManager::createTutorialBuilding(), freeGodMode, server::zone::managers::player::PlayerManager::getAccount(), server::login::account::Account::getAdminLevel(), server::zone::templates::SharedObjectTemplate::getAppearanceFilename(), ClientCreateCharacterCallback::getBiography(), ClientCreateCharacterCallback::getCharacterName(), server::zone::packets::MessageCallback::getClient(), server::zone::templates::SharedObjectTemplate::getClientObjectCRC(), ClientCreateCharacterCallback::getCustomizationString(), ClientCreateCharacterCallback::getHairCustomization(), ClientCreateCharacterCallback::getHairObject(), ClientCreateCharacterCallback::getHeight(), server::zone::templates::SharedObjectTemplate::getMaxScale(), server::zone::templates::SharedObjectTemplate::getMinScale(), SharedCreatureObjectTemplate::getRace(), ClientCreateCharacterCallback::getRaceFile(), ClientCreateCharacterCallback::getSkill(), PlayerCreatureTemplate::getStartingItems(), PlayerCreatureTemplate::getStartingSkills(), TemplateManager::getTemplate(), TemplateManager::getTemplateFile(), server::zone::templates::SharedObjectTemplate::getTemplateFileName(), ClientCreateCharacterCallback::getTutorialFlag(), ServerDatabase::instance(), lastCreatedCharacter, racialCreationData, skillPoints, startingBank, startingCash, ValidatedPosition::update(), server::zone::managers::player::PlayerManager::updatePermissionLevel(), and zoneServer.
Referenced by server::zone::managers::player::PlayerManagerImplementation::createPlayer().
int PlayerCreationManager::getMaximumAttributeLimit (const String & race, int attributeNumber)
Returns the requested maximum attribute limit for the specified race.
Parameters
race the race of interest.
attributeNumber The attribute number (starting from 0).
Returns
maximum attribute limit.
Definition at line 620 of file PlayerCreationManager.cpp.
References racialCreationData.
int PlayerCreationManager::getMinimumAttributeLimit (const String & race, int attributeNumber)
Returns the requested minimum attribute limit for the specified race.
Parameters
race the race of interest.
attributeNumber The attribute number (starting from 0).
Returns
minimum attribute limit.
Definition at line 639 of file PlayerCreationManager.cpp.
References racialCreationData.
int PlayerCreationManager::getTotalAttributeLimit (const String & race)
Returns the total attribute limit for the specified race.
Parameters
race the race of interest.
Returns
total attribute limit.
Definition at line 658 of file PlayerCreationManager.cpp.
References racialCreationData.
void PlayerCreationManager::loadDefaultCharacterItems () private
Definition at line 227 of file PlayerCreationManager.cpp.
References defaultCharacterEquipment.
Referenced by PlayerCreationManager().
void PlayerCreationManager::loadHairStyleInfo () private
Definition at line 269 of file PlayerCreationManager.cpp.
References hairStyleInfo.
Referenced by PlayerCreationManager().
void PlayerCreationManager::loadLuaConfig () private
Definition at line 306 of file PlayerCreationManager.cpp.
References freeGodMode, loadLuaStartingItems(), skillPoints, startingBank, and startingCash.
Referenced by PlayerCreationManager().
void PlayerCreationManager::loadLuaStartingItems (Lua * lua) private
Loads all starting items (profession specific, race specific, common) and starting clothes.
Parameters
lua pointer to a Lua object which contains the starting items and clothes.
Definition at line 325 of file PlayerCreationManager.cpp.
References commonStartingItems, and professionDefaultsInfo.
Referenced by loadLuaConfig().
void PlayerCreationManager::loadProfessionDefaultsInfo () private
Definition at line 160 of file PlayerCreationManager.cpp.
References SkillDataForm::getPathBySkillName(), DataTableIff::getRow(), SkillDataForm::getSkillNameAt(), SkillDataForm::getTotalPaths(), DataTableIff::getTotalRows(), DataTableRow::getValue(), TemplateManager::openIffFile(), professionDefaultsInfo, DataTableIff::readObject(), and SkillDataForm::readObject().
Referenced by PlayerCreationManager().
void PlayerCreationManager::loadRacialCreationData () private
Definition at line 100 of file PlayerCreationManager.cpp.
References DataTableIff::getRow(), DataTableIff::getRowsByColumn(), DataTableIff::getTotalRows(), DataTableRow::getValue(), TemplateManager::openIffFile(), racialCreationData, and DataTableIff::readObject().
Referenced by PlayerCreationManager().
bool PlayerCreationManager::validateCharacterName (const String & characterName)
Validates the character's name.
Parameters
characterName The character's name.
Definition at line 671 of file PlayerCreationManager.cpp.
Member Data Documentation
Mutex server::zone::managers::player::creation::PlayerCreationManager::charCountMutex private
Definition at line 124 of file PlayerCreationManager.h.
Referenced by createCharacter().
Vector<String> server::zone::managers::player::creation::PlayerCreationManager::commonStartingItems private
Vector containing starting items common for all races and professions.
Definition at line 115 of file PlayerCreationManager.h.
Referenced by addStartingItems(), addStartingItemsInto(), addStartingWeaponsInto(), and loadLuaStartingItems().
VectorMap<String, SortedVector<String> > server::zone::managers::player::creation::PlayerCreationManager::defaultCharacterEquipment private
Definition at line 109 of file PlayerCreationManager.h.
Referenced by addStartingItems(), and loadDefaultCharacterItems().
bool server::zone::managers::player::creation::PlayerCreationManager::freeGodMode private
Definition at line 121 of file PlayerCreationManager.h.
Referenced by createCharacter(), loadLuaConfig(), and PlayerCreationManager().
VectorMap<String, Reference<HairStyleInfo*> > server::zone::managers::player::creation::PlayerCreationManager::hairStyleInfo private
Definition at line 110 of file PlayerCreationManager.h.
Referenced by addHair(), loadHairStyleInfo(), and PlayerCreationManager().
HashTable<uint32, Time> server::zone::managers::player::creation::PlayerCreationManager::lastCreatedCharacter private
Definition at line 123 of file PlayerCreationManager.h.
Referenced by createCharacter().
VectorMap<String, Reference<ProfessionDefaultsInfo*> > server::zone::managers::player::creation::PlayerCreationManager::professionDefaultsInfo private
Definition at line 108 of file PlayerCreationManager.h.
Referenced by addProfessionStartingItems(), addStartingItemsInto(), addStartingWeaponsInto(), loadLuaStartingItems(), loadProfessionDefaultsInfo(), and PlayerCreationManager().
VectorMap<String, Reference<RacialCreationData*> > server::zone::managers::player::creation::PlayerCreationManager::racialCreationData private
Definition at line 107 of file PlayerCreationManager.h.
Referenced by addRacialMods(), createCharacter(), getMaximumAttributeLimit(), getMinimumAttributeLimit(), getTotalAttributeLimit(), loadRacialCreationData(), and PlayerCreationManager().
int server::zone::managers::player::creation::PlayerCreationManager::skillPoints private
Definition at line 119 of file PlayerCreationManager.h.
Referenced by createCharacter(), and loadLuaConfig().
int server::zone::managers::player::creation::PlayerCreationManager::startingBank private
Definition at line 118 of file PlayerCreationManager.h.
Referenced by createCharacter(), loadLuaConfig(), and PlayerCreationManager().
int server::zone::managers::player::creation::PlayerCreationManager::startingCash private
Definition at line 117 of file PlayerCreationManager.h.
Referenced by createCharacter(), loadLuaConfig(), and PlayerCreationManager().
ManagedReference<ZoneServer*> server::zone::managers::player::creation::PlayerCreationManager::zoneServer private
Definition at line 105 of file PlayerCreationManager.h.
Referenced by addHair(), addProfessionStartingItems(), addRacialMods(), addStartingItems(), addStartingItemsInto(), addStartingWeaponsInto(), createCharacter(), and PlayerCreationManager().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/creation/PlayerCreationManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/creation/PlayerCreationManager.cpp