Core3: server::zone::objects::mission::DestroyMissionObjectiveImplementation Class Reference
server::zone::objects::mission::DestroyMissionObjectiveImplementation Class Reference
#include <DestroyMissionObjective.h>
Public Member Functions
DestroyMissionObjectiveImplementation (MissionObject *mission)
DestroyMissionObjectiveImplementation (DummyConstructorParameter *param)
void finalize ()
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
void spawnLair ()
void destroyObjectFromDatabase ()
Vector3 findValidSpawnPosition (Zone *zone)
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void setLairTemplateToSpawn (const String &sp)
void setDifficulty (int diff)
Vector3 getEndPosition ()
operator const DestroyMissionObjective * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
MissionObjectiveImplementation (MissionObject *parent)
MissionObjectiveImplementation (DummyConstructorParameter *param)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
virtual void deactivate ()
virtual void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
operator const MissionObjective * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< DestroyMissionObjective * > _this
Public Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
WeakReference< MissionObjective * > _this
Protected Member Functions
virtual ~DestroyMissionObjectiveImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
virtual ~MissionObjectiveImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
String lairTemplate
ManagedReference
< MissionSpawnActiveArea * > spawnActiveArea
ManagedReference
< TangibleObject * > lairObject
Protected Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
ManagedWeakReference
< MissionObject * > mission
unsigned int objectiveType
Time missionStartTime
Reference
< FailMissionAfterCertainTimeTask * > failTask
unsigned long long timeRemaining
bool activated
Private Attributes
int difficulty
Friends
class DestroyMissionObjective
Detailed Description
Definition at line 189 of file DestroyMissionObjective.h.
Constructor & Destructor Documentation
DestroyMissionObjectiveImplementation::DestroyMissionObjectiveImplementation (MissionObject * mission)
Definition at line 360 of file DestroyMissionObjective.cpp.
References _initializeImplementation(), and difficulty.
DestroyMissionObjectiveImplementation::DestroyMissionObjectiveImplementation (DummyConstructorParameter * param)
Definition at line 200 of file DestroyMissionObjective.cpp.
References _initializeImplementation().
DestroyMissionObjectiveImplementation::~DestroyMissionObjectiveImplementation () protected virtual
Definition at line 205 of file DestroyMissionObjective.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * DestroyMissionObjectiveImplementation::_getStub ()
Definition at line 223 of file DestroyMissionObjective.cpp.
References _this.
void DestroyMissionObjectiveImplementation::_initializeImplementation () protected
Definition at line 210 of file DestroyMissionObjective.cpp.
References _serializationHelperMethod(), and _this.
Referenced by DestroyMissionObjectiveImplementation().
void DestroyMissionObjectiveImplementation::_serializationHelperMethod () protected
Definition at line 259 of file DestroyMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void DestroyMissionObjectiveImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 218 of file DestroyMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_setStub(), and _this.
Referenced by server::zone::objects::mission::DestroyMissionObjective::DestroyMissionObjective().
void DestroyMissionObjectiveImplementation::abort () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 190 of file DestroyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::abort(), server::zone::objects::mission::MissionObjectiveImplementation::dropObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::hasObservers(), lairObject, ObserverEventType::OBJECTDESTRUCTION, and spawnActiveArea.
Referenced by server::zone::objects::mission::DestroyMissionObjective::abort().
void DestroyMissionObjectiveImplementation::activate () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 46 of file DestroyMissionObjectiveImplementation.cpp.
References _this, server::zone::objects::mission::MissionObjectiveImplementation::activate(), server::zone::objects::mission::MissionObjectiveImplementation::hasObservers(), lairObject, server::zone::objects::mission::MissionObjectiveImplementation::mission, server::zone::objects::waypoint::WaypointObject::setActive(), server::zone::objects::waypoint::WaypointObject::setPlanetCRC(), spawnActiveArea, and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::objects::mission::DestroyMissionObjective::activate().
void DestroyMissionObjectiveImplementation::complete () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 222 of file DestroyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::complete().
Referenced by server::zone::objects::mission::DestroyMissionObjective::complete(), and notifyObserverEvent().
void DestroyMissionObjectiveImplementation::destroyObjectFromDatabase () virtual
Destroys this object from database
Precondition
{ this is locked }
Postcondition
{ this is locked }
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 31 of file DestroyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::destroyObjectFromDatabase(), and spawnActiveArea.
Referenced by server::zone::objects::mission::DestroyMissionObjective::destroyObjectFromDatabase().
void DestroyMissionObjectiveImplementation::finalize ()
Definition at line 368 of file DestroyMissionObjective.cpp.
Referenced by ~DestroyMissionObjectiveImplementation().
Vector3 DestroyMissionObjectiveImplementation::findValidSpawnPosition (Zone * zone)
Definition at line 85 of file DestroyMissionObjectiveImplementation.cpp.
References CollisionManager::checkSphereCollision(), server::zone::objects::mission::MissionObjectiveImplementation::fail(), server::zone::Zone::getHeight(), server::zone::Zone::getPlanetManager(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::managers::planet::PlanetManager::getTerrainManager(), TerrainManager::getWaterHeight(), server::zone::managers::planet::PlanetManager::isInObjectsNoBuildZone(), server::zone::Zone::isWithinBoundaries(), and spawnActiveArea.
Referenced by server::zone::objects::mission::DestroyMissionObjective::findValidSpawnPosition(), and spawnLair().
Vector3 DestroyMissionObjectiveImplementation::getEndPosition () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 236 of file DestroyMissionObjectiveImplementation.cpp.
References server::zone::Zone::getHeight(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), and server::zone::objects::mission::MissionObjectiveImplementation::mission.
Referenced by server::zone::objects::mission::DestroyMissionObjective::getEndPosition().
void DestroyMissionObjectiveImplementation::initializeTransientMembers () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 371 of file DestroyMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::initializeTransientMembers().
Referenced by server::zone::objects::mission::DestroyMissionObjective::initializeTransientMembers(), and readObject().
void DestroyMissionObjectiveImplementation::lock (bool doLock = true) protected
Definition at line 231 of file DestroyMissionObjective.cpp.
References _this.
void DestroyMissionObjectiveImplementation::lock (ManagedObject * obj) protected
Definition at line 235 of file DestroyMissionObjective.cpp.
References _this.
int DestroyMissionObjectiveImplementation::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 227 of file DestroyMissionObjectiveImplementation.cpp.
References complete(), and ObserverEventType::OBJECTDESTRUCTION.
Referenced by server::zone::objects::mission::DestroyMissionObjective::notifyObserverEvent().
DestroyMissionObjectiveImplementation::operator const DestroyMissionObjective * ()
Definition at line 227 of file DestroyMissionObjective.cpp.
void DestroyMissionObjectiveImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 266 of file DestroyMissionObjective.cpp.
References initializeTransientMembers(), and readObjectMember().
bool DestroyMissionObjectiveImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 285 of file DestroyMissionObjective.cpp.
References difficulty, lairObject, lairTemplate, server::zone::objects::mission::MissionObjectiveImplementation::readObjectMember(), and spawnActiveArea.
Referenced by readObject().
void DestroyMissionObjectiveImplementation::rlock (bool doLock = true) protected
Definition at line 239 of file DestroyMissionObjective.cpp.
References _this.
void DestroyMissionObjectiveImplementation::runlock (bool doLock = true) protected
Definition at line 255 of file DestroyMissionObjective.cpp.
References _this.
void DestroyMissionObjectiveImplementation::setDifficulty (int diff)
Definition at line 378 of file DestroyMissionObjective.cpp.
References difficulty.
Referenced by server::zone::objects::mission::DestroyMissionObjective::setDifficulty().
void DestroyMissionObjectiveImplementation::setLairTemplateToSpawn (const String & sp)
Definition at line 27 of file DestroyMissionObjectiveImplementation.cpp.
References lairTemplate.
Referenced by server::zone::objects::mission::DestroyMissionObjective::setLairTemplateToSpawn().
void DestroyMissionObjectiveImplementation::spawnLair ()
Definition at line 130 of file DestroyMissionObjectiveImplementation.cpp.
References _this, server::zone::objects::mission::MissionObjectiveImplementation::addObserver(), difficulty, findValidSpawnPosition(), server::zone::Zone::getCreatureManager(), server::zone::templates::mobile::LairTemplate::getFaction(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::scene::SceneObject::getZone(), lairObject, lairTemplate, server::zone::objects::mission::MissionObjectiveImplementation::mission, ObserverEventType::OBJECTDESTRUCTION, spawnActiveArea, server::zone::managers::creature::CreatureManager::spawnLair(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::objects::mission::DestroyMissionObjective::spawnLair().
void DestroyMissionObjectiveImplementation::unlock (bool doLock = true) protected
Definition at line 251 of file DestroyMissionObjective.cpp.
References _this.
void DestroyMissionObjectiveImplementation::wlock (bool doLock = true) protected
Definition at line 243 of file DestroyMissionObjective.cpp.
References _this.
void DestroyMissionObjectiveImplementation::wlock (ManagedObject * obj) protected
Definition at line 247 of file DestroyMissionObjective.cpp.
References _this.
void DestroyMissionObjectiveImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 311 of file DestroyMissionObjective.cpp.
References writeObjectMembers().
int DestroyMissionObjectiveImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 318 of file DestroyMissionObjective.cpp.
References difficulty, lairObject, lairTemplate, spawnActiveArea, and server::zone::objects::mission::MissionObjectiveImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class DestroyMissionObjective friend
Definition at line 266 of file DestroyMissionObjective.h.
Member Data Documentation
WeakReference<DestroyMissionObjective*> server::zone::objects::mission::DestroyMissionObjectiveImplementation::_this
Definition at line 234 of file DestroyMissionObjective.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), activate(), lock(), rlock(), runlock(), spawnLair(), unlock(), and wlock().
int server::zone::objects::mission::DestroyMissionObjectiveImplementation::difficulty private
Definition at line 198 of file DestroyMissionObjective.h.
Referenced by DestroyMissionObjectiveImplementation(), readObjectMember(), setDifficulty(), spawnLair(), and writeObjectMembers().
ManagedReference<TangibleObject* > server::zone::objects::mission::DestroyMissionObjectiveImplementation::lairObject protected
Definition at line 195 of file DestroyMissionObjective.h.
Referenced by abort(), activate(), readObjectMember(), spawnLair(), and writeObjectMembers().
String server::zone::objects::mission::DestroyMissionObjectiveImplementation::lairTemplate protected
Definition at line 191 of file DestroyMissionObjective.h.
Referenced by readObjectMember(), setLairTemplateToSpawn(), spawnLair(), and writeObjectMembers().
ManagedReference<MissionSpawnActiveArea* > server::zone::objects::mission::DestroyMissionObjectiveImplementation::spawnActiveArea protected
Definition at line 193 of file DestroyMissionObjective.h.
Referenced by abort(), activate(), destroyObjectFromDatabase(), findValidSpawnPosition(), readObjectMember(), spawnLair(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DestroyMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DestroyMissionObjective.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DestroyMissionObjectiveImplementation.cpp