Core3: server::zone::objects::player::sessions::CityRemoveMilitiaSessionAdapter Class Reference
server::zone::objects::player::sessions::CityRemoveMilitiaSessionAdapter Class Reference
#include <CityRemoveMilitiaSession.h>
Public Member Functions
CityRemoveMilitiaSessionAdapter (CityRemoveMilitiaSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
unsigned long long getMilitiaID ()
int initializeSession ()
int cancelSession ()
int clearSession ()
Detailed Description
Definition at line 179 of file CityRemoveMilitiaSession.h.
Constructor & Destructor Documentation
CityRemoveMilitiaSessionAdapter::CityRemoveMilitiaSessionAdapter (CityRemoveMilitiaSession * impl)
Definition at line 310 of file CityRemoveMilitiaSession.cpp.
Member Function Documentation
int CityRemoveMilitiaSessionAdapter::cancelSession ()
Definition at line 350 of file CityRemoveMilitiaSession.cpp.
Referenced by invokeMethod().
int CityRemoveMilitiaSessionAdapter::clearSession ()
Definition at line 354 of file CityRemoveMilitiaSession.cpp.
Referenced by invokeMethod().
unsigned long long CityRemoveMilitiaSessionAdapter::getMilitiaID ()
Definition at line 342 of file CityRemoveMilitiaSession.cpp.
Referenced by invokeMethod().
int CityRemoveMilitiaSessionAdapter::initializeSession ()
Definition at line 346 of file CityRemoveMilitiaSession.cpp.
Referenced by invokeMethod().
void CityRemoveMilitiaSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 313 of file CityRemoveMilitiaSession.cpp.
References cancelSession(), clearSession(), getMilitiaID(), initializeSession(), RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_GETMILITIAID__, and RPC_INITIALIZESESSION__.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityRemoveMilitiaSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityRemoveMilitiaSession.cpp