Core3: CharacterBuilderMenuNode Class Reference
CharacterBuilderMenuNode Class Reference
#include <CharacterBuilderMenuNode.h>
Public Member Functions
CharacterBuilderMenuNode (const String &name)
CharacterBuilderMenuNode (const String &name, const String &tplPath)
int readLuaObject (LuaObject &luaObject, bool recursive)
int compareTo (CharacterBuilderMenuNode *obj)
void setTemplatePath (const String &tplPath)
void setParentNode (CharacterBuilderMenuNode *parent)
CharacterBuilderMenuNode * getParentNode ()
bool hasParentNode ()
bool hasChildNodes ()
String & getDisplayName ()
String & getTemplatePath ()
uint32 getTemplateCRC ()
int getChildNodeSize ()
CharacterBuilderMenuNode * getChildNodeAt (int index)
Private Attributes
WeakReference
< CharacterBuilderMenuNode * > parentNode
String displayName
String templatePath
uint32 templateCRC
SortedVector< Reference
< CharacterBuilderMenuNode * > > childNodes
Detailed Description
Definition at line 15 of file CharacterBuilderMenuNode.h.
Constructor & Destructor Documentation
CharacterBuilderMenuNode::CharacterBuilderMenuNode (const String & name) inline
Definition at line 25 of file CharacterBuilderMenuNode.h.
References childNodes, displayName, parentNode, and templateCRC.
Referenced by readLuaObject().
CharacterBuilderMenuNode::CharacterBuilderMenuNode (const String & name, const String & tplPath) inline
Definition at line 32 of file CharacterBuilderMenuNode.h.
References childNodes, displayName, parentNode, templateCRC, and templatePath.
Member Function Documentation
int CharacterBuilderMenuNode::compareTo (CharacterBuilderMenuNode * obj) inline
Definition at line 70 of file CharacterBuilderMenuNode.h.
References displayName, and getDisplayName().
CharacterBuilderMenuNode* CharacterBuilderMenuNode::getChildNodeAt (int index) inline
Definition at line 111 of file CharacterBuilderMenuNode.h.
References childNodes.
Referenced by server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem().
int CharacterBuilderMenuNode::getChildNodeSize () inline
Definition at line 107 of file CharacterBuilderMenuNode.h.
References childNodes.
String& CharacterBuilderMenuNode::getDisplayName () inline
Definition at line 95 of file CharacterBuilderMenuNode.h.
References displayName.
Referenced by compareTo(), server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), and server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem().
CharacterBuilderMenuNode* CharacterBuilderMenuNode::getParentNode () inline
Definition at line 83 of file CharacterBuilderMenuNode.h.
References parentNode.
Referenced by server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem().
uint32 CharacterBuilderMenuNode::getTemplateCRC () inline
Definition at line 103 of file CharacterBuilderMenuNode.h.
References templateCRC.
Referenced by server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem().
String& CharacterBuilderMenuNode::getTemplatePath () inline
Definition at line 99 of file CharacterBuilderMenuNode.h.
References templatePath.
Referenced by server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem().
bool CharacterBuilderMenuNode::hasChildNodes () inline
Definition at line 91 of file CharacterBuilderMenuNode.h.
References childNodes.
Referenced by server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem().
bool CharacterBuilderMenuNode::hasParentNode () inline
Definition at line 87 of file CharacterBuilderMenuNode.h.
References parentNode.
int CharacterBuilderMenuNode::readLuaObject (LuaObject & luaObject, bool recursive) inline
Definition at line 40 of file CharacterBuilderMenuNode.h.
References CharacterBuilderMenuNode(), childNodes, readLuaObject(), setParentNode(), and setTemplatePath().
Referenced by readLuaObject().
void CharacterBuilderMenuNode::setParentNode (CharacterBuilderMenuNode * parent) inline
Definition at line 79 of file CharacterBuilderMenuNode.h.
References parentNode.
Referenced by readLuaObject().
void CharacterBuilderMenuNode::setTemplatePath (const String & tplPath) inline
Definition at line 74 of file CharacterBuilderMenuNode.h.
References templateCRC, and templatePath.
Referenced by readLuaObject().
Member Data Documentation
SortedVector<Reference<CharacterBuilderMenuNode*> > CharacterBuilderMenuNode::childNodes private
Definition at line 22 of file CharacterBuilderMenuNode.h.
Referenced by CharacterBuilderMenuNode(), getChildNodeAt(), getChildNodeSize(), hasChildNodes(), and readLuaObject().
String CharacterBuilderMenuNode::displayName private
Definition at line 18 of file CharacterBuilderMenuNode.h.
Referenced by CharacterBuilderMenuNode(), compareTo(), and getDisplayName().
WeakReference<CharacterBuilderMenuNode*> CharacterBuilderMenuNode::parentNode private
Definition at line 16 of file CharacterBuilderMenuNode.h.
Referenced by CharacterBuilderMenuNode(), getParentNode(), hasParentNode(), and setParentNode().
uint32 CharacterBuilderMenuNode::templateCRC private
Definition at line 20 of file CharacterBuilderMenuNode.h.
Referenced by CharacterBuilderMenuNode(), getTemplateCRC(), and setTemplatePath().
String CharacterBuilderMenuNode::templatePath private
Definition at line 19 of file CharacterBuilderMenuNode.h.
Referenced by CharacterBuilderMenuNode(), getTemplatePath(), and setTemplatePath().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/terminal/characterbuilder/CharacterBuilderMenuNode.h