Core3: DetailAppearanceTemplate Class Reference
DetailAppearanceTemplate Class Reference
#include <DetailAppearanceTemplate.h>
Public Member Functions
DetailAppearanceTemplate ()
~DetailAppearanceTemplate ()
void readObject (IffStream *templateData)
void parse (IffStream *iffStream)
AppearanceTemplate * getFirstMesh ()
Public Member Functions inherited from AppearanceTemplate
virtual ~AppearanceTemplate ()
Private Attributes
AppearanceTemplate * firstMesh
Detailed Description
Definition at line 14 of file DetailAppearanceTemplate.h.
Constructor & Destructor Documentation
DetailAppearanceTemplate::DetailAppearanceTemplate () inline
Definition at line 18 of file DetailAppearanceTemplate.h.
References firstMesh.
DetailAppearanceTemplate::~DetailAppearanceTemplate () inline
Definition at line 22 of file DetailAppearanceTemplate.h.
Member Function Documentation
AppearanceTemplate* DetailAppearanceTemplate::getFirstMesh () inline virtual
Reimplemented from AppearanceTemplate.
Definition at line 31 of file DetailAppearanceTemplate.h.
References firstMesh.
void DetailAppearanceTemplate::parse (IffStream * iffStream)
Definition at line 11 of file DetailAppearanceTemplate.cpp.
References firstMesh, AppearanceTemplate::getFirstMesh(), and AppearanceTemplate::readObject().
Referenced by readObject().
void DetailAppearanceTemplate::readObject (IffStream * templateData) inline virtual
Reimplemented from AppearanceTemplate.
Definition at line 25 of file DetailAppearanceTemplate.h.
References parse().
Member Data Documentation
AppearanceTemplate* DetailAppearanceTemplate::firstMesh private
Definition at line 15 of file DetailAppearanceTemplate.h.
Referenced by DetailAppearanceTemplate(), getFirstMesh(), and parse().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/DetailAppearanceTemplate.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/DetailAppearanceTemplate.cpp