Core3: server::zone::packets::scene::AttributeListMessage Class Reference
server::zone::packets::scene::AttributeListMessage Class Reference
#include <AttributeListMessage.h>
Public Member Functions
AttributeListMessage (SceneObject *object)
AttributeListMessage (uint64 objectID, int listCount)
AttributeListMessage (uint64 objectID)
AttributeListMessage (uint64 objectid, UnicodeString &description)
void insertAttribute (const String &attribute, UnicodeString &value)
void insertAttribute (const String &attribute, String &value)
void insertAttribute (const String &attribute, const String &value)
void insertAttribute (const String &attribute, StringBuffer &value)
void insertAttribute (const String &attribute, float value)
void insertAttribute (const String &attribute, int value)
void insertAttribute (const String &attribute, int value, bool asInt)
void updateListCount ()
Private Attributes
int listcount
int countLocation
Detailed Description
Definition at line 61 of file AttributeListMessage.h.
Constructor & Destructor Documentation
server::zone::packets::scene::AttributeListMessage::AttributeListMessage (SceneObject * object) inline
Definition at line 66 of file AttributeListMessage.h.
References countLocation, server::zone::objects::scene::SceneObject::getObjectID(), and listcount.
server::zone::packets::scene::AttributeListMessage::AttributeListMessage (uint64 objectID, int listCount) inline
Definition at line 79 of file AttributeListMessage.h.
server::zone::packets::scene::AttributeListMessage::AttributeListMessage (uint64 objectID) inline
Definition at line 88 of file AttributeListMessage.h.
References countLocation, and listcount.
server::zone::packets::scene::AttributeListMessage::AttributeListMessage (uint64 objectid, UnicodeString & description) inline
Definition at line 99 of file AttributeListMessage.h.
References countLocation, and listcount.
Member Function Documentation
void server::zone::packets::scene::AttributeListMessage::insertAttribute (const String & attribute, UnicodeString & value) inline
Definition at line 113 of file AttributeListMessage.h.
References updateListCount().
Referenced by RobeObjectAttributeListComponent::fillAttributeList(), SkillBuffObjectAttributeListComponent::fillAttributeList(), TurretDataComponent::fillAttributeList(), server::zone::objects::tangible::wearables::WearableContainerObjectImplementation::fillAttributeList(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::fillAttributeList(), server::zone::objects::tangible::deed::structure::StructureDeedImplementation::fillAttributeList(), server::zone::objects::tangible::wearables::WearableObjectImplementation::fillAttributeList(), server::zone::objects::tangible::loot::LootkitObjectImplementation::fillAttributeList(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::fillAttributeList(), server::zone::objects::tangible::tool::repair::RepairToolImplementation::fillAttributeList(), server::zone::objects::tangible::ticket::TicketObjectImplementation::fillAttributeList(), server::zone::objects::resource::ResourceContainerImplementation::fillAttributeList(), server::zone::objects::tangible::component::ComponentImplementation::fillAttributeList(), server::zone::objects::tangible::fishing::FishObjectImplementation::fillAttributeList(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::fillAttributeList(), server::zone::objects::tangible::attachement::AttachmentImplementation::fillAttributeList(), server::zone::objects::tangible::tool::CraftingStationImplementation::fillAttributeList(), server::zone::objects::factorycrate::FactoryCrateImplementation::fillAttributeList(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::fillAttributeList(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::fillAttributeList(), server::zone::objects::installation::factory::FactoryObjectImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::fillAttributeList(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::fillAttributeList(), server::zone::objects::intangible::VehicleControlDeviceImplementation::fillAttributeList(), server::zone::objects::creature::CreatureImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::fillAttributeList(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::fillAttributeList(), server::zone::objects::tangible::component::genetic::GeneticComponentImplementation::fillAttributeList(), server::zone::objects::resource::ResourceSpawnImplementation::fillAttributeList(), server::zone::objects::creature::VehicleObjectImplementation::fillAttributeList(), server::zone::objects::tangible::tool::CraftingToolImplementation::fillAttributeList(), server::zone::objects::tangible::consumable::ConsumableImplementation::fillAttributeList(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::fillAttributeList(), server::zone::objects::tangible::component::dna::DnaComponentImplementation::fillAttributeList(), server::zone::objects::installation::InstallationObjectImplementation::fillAttributeList(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::fillAttributeList(), server::zone::objects::creature::ai::AiActorImplementation::fillAttributeList(), server::zone::objects::tangible::TangibleObjectImplementation::fillAttributeList(), server::zone::objects::creature::AiAgentImplementation::fillAttributeList(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::fillWeaponAttributeList(), BlueprintEntry::insertSchematicAttribute(), and server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::updateCharges().
void server::zone::packets::scene::AttributeListMessage::insertAttribute (const String & attribute, String & value) inline
Definition at line 120 of file AttributeListMessage.h.
References updateListCount().
void server::zone::packets::scene::AttributeListMessage::insertAttribute (const String & attribute, const String & value) inline
Definition at line 128 of file AttributeListMessage.h.
References updateListCount().
void server::zone::packets::scene::AttributeListMessage::insertAttribute (const String & attribute, StringBuffer & value) inline
Definition at line 136 of file AttributeListMessage.h.
References updateListCount().
void server::zone::packets::scene::AttributeListMessage::insertAttribute (const String & attribute, float value) inline
Definition at line 145 of file AttributeListMessage.h.
References updateListCount().
void server::zone::packets::scene::AttributeListMessage::insertAttribute (const String & attribute, int value) inline
Definition at line 157 of file AttributeListMessage.h.
References updateListCount().
void server::zone::packets::scene::AttributeListMessage::insertAttribute (const String & attribute, int value, bool asInt) inline
Definition at line 169 of file AttributeListMessage.h.
References updateListCount().
void server::zone::packets::scene::AttributeListMessage::updateListCount () inline
Definition at line 176 of file AttributeListMessage.h.
References countLocation, and listcount.
Referenced by insertAttribute().
Member Data Documentation
int server::zone::packets::scene::AttributeListMessage::countLocation private
Definition at line 63 of file AttributeListMessage.h.
Referenced by AttributeListMessage(), and updateListCount().
int server::zone::packets::scene::AttributeListMessage::listcount private
Definition at line 62 of file AttributeListMessage.h.
Referenced by AttributeListMessage(), and updateListCount().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/scene/AttributeListMessage.h