Core3: CombatQueueCommand Class Reference
CombatQueueCommand Class Reference
#include <CombatQueueCommand.h>
Public Member Functions
CombatQueueCommand (const String &name, ZoneProcessServer *server)
int doCombatAction (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments="", ManagedReference< WeaponObject * > weapon=NULL)
float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
uint32 getDotDuration () const
uint64 getDotType () const
uint8 getDotPool () const
uint32 getDotStrength () const
float getDotPotency () const
float getHealthCostMultiplier () const
float getActionCostMultiplier () const
float getMindCostMultiplier () const
int getRange () const
String getAccuracySkillMod () const
int getBlindChance () const
float getDamageMultiplier () const
int getAccuracyBonus () const
int getDizzyChance () const
int getIntimidateChance () const
int getKnockdownChance () const
int getPostureDownChance () const
int getPostureUpChance () const
float getSpeedMultiplier () const
float getSpeed () const
int getStunChance () const
bool isAreaAction () const
bool isConeAction () const
bool isDotDamageOfHit () const
int getConeAngle () const
int getAreaRange () const
int getDurationStateTime () const
float getForceCostMultiplier () const
float getForceCost () const
int getNextAttackDelayChance () const
void setBlindStateChance (int blindStateChance)
void setDamageMultiplier (float damageMultiplier)
void setAccuracyBonus (int accuracyBonus)
void setHealthCostMultiplier (float f)
void setActionCostMultiplier (float f)
void setMindCostMultiplier (float f)
void setForceCostMultiplier (float f)
void setForceCost (float f)
void setDizzyStateChance (int dizzyStateChance)
void setIntimidateStateChance (int intimidateStateChance)
void setKnockdownStateChance (int knockdownStateChance)
void setPostureDownStateChance (int postureDownStateChance)
void setPostureUpStateChance (int postureUpStateChance)
void setNextAttackDelayChance (int i)
void setDurationStateTime (int i)
void setDotDuration (uint32 i)
void setDotType (uint64 l)
void setDotPool (uint8 c)
void setDotStrength (uint32 i)
void setDotPotency (float f)
void setConeAngle (int i)
void setDotDamageOfHit (bool b)
void setAreaAction (bool b)
void setConeAction (bool b)
void setAreaRange (int i)
void setEffectString (String s)
void setSpeedMultiplier (float speedMultiplier)
void setSpeed (float speedd)
void setStunStateChance (int stunStateChance)
uint32 getAnimationCRC () const
String getEffectString () const
String getCombatSpam () const
int getPoolsToDamage () const
VectorMap< uint64, StateEffect > * getStateEffects ()
VectorMap< uint64, DotEffect > * getDotEffects ()
void setAnimationCRC (uint32 animationCRC)
void setCombatSpam (String combatSpam)
void setPoolsToDamage (int poolsToDamage)
void setStateEffects (VectorMap< uint64, StateEffect > stateEffects)
void addStateEffect (StateEffect stateEffect)
StateEffect getStateEffect (uint64 type)
void setDotEffects (VectorMap< uint64, DotEffect > dotEffects)
float getDamage () const
void setDamage (float dm)
void addDotEffect (DotEffect dotEffect)
DotEffect getDotEffect (uint64 type)
void setRange (int i)
void setAccuracySkillMod (String acc)
bool hasCombatSpam ()
bool isCombatCommand ()
virtual bool isSquadLeaderCommand ()
virtual void applyEffect (CreatureObject *creature, uint8 effectType, uint32 mod)
uint8 getAttackType () const
void setAttackType (uint8 attackType)
uint8 getTrails () const
void setTrails (uint8 trails)
Public Member Functions inherited from server::zone::objects::creature::commands::QueueCommand
QueueCommand (const String &skillname, ZoneProcessServer *serv)
virtual ~QueueCommand ()
bool checkInvalidLocomotions (CreatureObject *creature)
void onStateFail (CreatureObject *creature, uint32 actioncntr)
void onLocomotionFail (CreatureObject *creature, uint32 actioncntr)
virtual String getSyntax () const
virtual void onFail (uint32 actioncntr, CreatureObject *creature, uint32 errorNumber)
virtual void onComplete (uint32 actioncntr, CreatureObject *creature, float commandDuration)
void setInvalidLocomotions (const String &lStr)
void addInvalidLocomotion (int l)
virtual int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
bool checkStateMask (CreatureObject *creature)
void setStateMask (uint64 mask)
void setDefaultTime (float time)
void setTargetType (int num)
void setDisabled (bool state)
void setDisabled (int state)
void setAddToCombatQueue (bool state)
void setAddToCombatQueue (int state)
void setCommandGroup (int val)
void setMaxRange (float r)
void setCharacterAbility (const String &ability)
void setDefaultPriority (const String &priority)
void setDefaultPriority (const int priority)
uint64 getStateMask ()
bool requiresAdmin ()
int getTargetType ()
uint32 getNameCRC ()
float getMaxRange ()
String & getQueueCommandName ()
String & getCharacterAbility ()
float getDefaultTime ()
int getDefaultPriority ()
bool isDisabled ()
bool addToCombatQueue ()
int getSkillModSize ()
int getSkillMod (int index, String &skillMod)
int getCommandGroup ()
void addSkillMod (const String &skillMod, const int value)
bool isWearingArmor (CreatureObject *creo)
virtual void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Protected Attributes
float damage
float damageMultiplier
int accuracyBonus
float speedMultiplier
float speed
int poolsToDamage
float healthCostMultiplier
float actionCostMultiplier
float mindCostMultiplier
float forceCostMultiplier
float forceCost
int knockdownStateChance
int postureDownStateChance
int postureUpStateChance
int dizzyStateChance
int blindStateChance
int stunStateChance
int intimidateStateChance
int nextAttackDelayChance
int durationStateTime
uint32 dotDuration
uint64 dotType
uint8 dotPool
uint32 dotStrength
float dotPotency
bool dotDamageOfHit
int range
String accuracySkillMod
bool areaAction
bool coneAction
int coneAngle
int areaRange
String combatSpam
String stateSpam
uint32 animationCRC
String effectString
VectorMap< uint64, StateEffect > stateEffects
VectorMap< uint64, DotEffect > dotEffects
uint8 attackType
uint8 trails
Protected Attributes inherited from server::zone::objects::creature::commands::QueueCommand
ZoneProcessServer * server
String name
uint32 nameCRC
uint64 stateMask
Vector< int > invalidLocomotion
int targetType
int maxRangeToTarget
bool disabled
bool addToQueue
bool admin
uint32 cooldown
float defaultTime
String characterAbility
int defaultPriority
VectorMap< String, int > skillMods
int commandGroup
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::creature::commands::QueueCommand
static const int IMMEDIATE = 0
static const int FRONT = 1
static const int NORMAL = 2
static const int SUCCESS = 0
static const int GENERALERROR = 1
static const int INVALIDLOCOMOTION = 2
static const int INVALIDSTATE = 3
static const int INVALIDTARGET = 4
static const int INVALIDWEAPON = 5
static const int TOOFAR = 6
static const int INSUFFICIENTHAM = 7
static const int INVALIDPARAMETERS = 8
static const int NOPRONE = 9
static const int NOKNEELING = 10
static const int INSUFFICIENTPERMISSION = 11
static const int NOJEDIARMOR = 12
static const int INVALIDSYNTAX = 13
Detailed Description
Definition at line 26 of file CombatQueueCommand.h.
Constructor & Destructor Documentation
CombatQueueCommand::CombatQueueCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 81 of file CombatQueueCommand.h.
References accuracyBonus, accuracySkillMod, actionCostMultiplier, animationCRC, areaAction, areaRange, attackType, blindStateChance, combatSpam, coneAction, coneAngle, damage, damageMultiplier, CombatManager::DEFAULTTRAIL, dizzyStateChance, dotDamageOfHit, dotDuration, dotPool, dotPotency, dotStrength, dotType, durationStateTime, forceCost, forceCostMultiplier, healthCostMultiplier, intimidateStateChance, knockdownStateChance, mindCostMultiplier, nextAttackDelayChance, poolsToDamage, postureDownStateChance, postureUpStateChance, CombatManager::RANDOM, range, speed, speedMultiplier, stunStateChance, trails, and CombatManager::WEAPONATTACK.
Member Function Documentation
void CombatQueueCommand::addDotEffect (DotEffect dotEffect) inline
Definition at line 505 of file CombatQueueCommand.h.
References dotEffects, and DotEffect::getDotType().
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::addStateEffect (StateEffect stateEffect) inline
Definition at line 485 of file CombatQueueCommand.h.
References StateEffect::getEffectType(), and stateEffects.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
virtual void CombatQueueCommand::applyEffect (CreatureObject * creature, uint8 effectType, uint32 mod) inline virtual
Definition at line 534 of file CombatQueueCommand.h.
References CommandEffect::ACTIONDEGRADE, server::zone::objects::creature::CreatureObject::addBuff(), CommandEffect::BLIND, CreatureAttribute::CONSTITUTION, CreaturePosture::CROUCHED, server::zone::objects::creature::CreatureObject::dismount(), CommandEffect::DIZZY, CreatureAttribute::FOCUS, server::zone::objects::creature::CreatureObject::getPosture(), getStateEffect(), StateEffect::getStateLength(), StateEffect::getStateStrength(), CommandEffect::HEALTHDEGRADE, CommandEffect::INTIMIDATE, server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::creature::CreatureObject::isKnockedDown(), server::zone::objects::creature::CreatureObject::isMounted(), server::zone::objects::creature::CreatureObject::isProne(), CommandEffect::KNOCKDOWN, CreaturePosture::KNOCKEDDOWN, CommandEffect::MINDDEGRADE, CommandEffect::NEXTATTACKDELAY, CommandEffect::POSTUREDOWN, CommandEffect::POSTUREUP, CreaturePosture::PRONE, CreatureAttribute::QUICKNESS, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::buffs::Buff::setAttributeModifier(), server::zone::objects::creature::CreatureObject::setBlindedState(), server::zone::objects::creature::CreatureObject::setDizziedState(), server::zone::objects::creature::CreatureObject::setIntimidatedState(), server::zone::objects::creature::CreatureObject::setNextAttackDelay(), server::zone::objects::creature::CreatureObject::setPosture(), server::zone::objects::creature::CreatureObject::setStunnedState(), CreatureAttribute::STAMINA, BuffType::STATE, CreatureAttribute::STRENGTH, CommandEffect::STUN, server::zone::objects::creature::CreatureObject::updateCooldownTimer(), server::zone::objects::creature::CreatureObject::updateKnockdownRecovery(), server::zone::objects::creature::CreatureObject::updateLastKnockdown(), server::zone::objects::creature::CreatureObject::updatePostureDownRecovery(), server::zone::objects::creature::CreatureObject::updatePostureUpRecovery(), CreaturePosture::UPRIGHT, and CreatureAttribute::WILLPOWER.
Referenced by CombatManager::applyStates().
int CombatQueueCommand::doCombatAction (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments = "", ManagedReference< WeaponObject * > weapon = NULL) inline
Definition at line 134 of file CombatQueueCommand.h.
References CreatureState::AIMING, CollisionManager::checkLineOfSight(), CombatManager::doCombatAction(), server::zone::objects::creature::commands::QueueCommand::GENERALERROR, server::zone::ZoneServer::getObject(), server::zone::ZoneProcessServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::getWeapon(), server::zone::ZoneProcessServer::getZoneServer(), server::zone::objects::creature::commands::QueueCommand::INSUFFICIENTHAM, server::zone::objects::creature::commands::QueueCommand::INVALIDLOCOMOTION, server::zone::objects::creature::commands::QueueCommand::INVALIDTARGET, server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isKneeling(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isProne(), server::zone::objects::creature::commands::QueueCommand::NOKNEELING, server::zone::objects::creature::commands::QueueCommand::NOPRONE, range, server::zone::objects::creature::CreatureObject::removeBuff(), server::zone::objects::creature::CreatureObject::removeStateBuff(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::commands::QueueCommand::server, server::zone::objects::creature::commands::QueueCommand::SUCCESS, and server::zone::objects::creature::commands::QueueCommand::TOOFAR.
Referenced by VolleyFireCommand::attemptVolleyFire(), CreatureRangedAttackCommand::doQueueCommand(), DefaultDroidAttackCommand::doQueueCommand(), MildDiseaseCommand::doQueueCommand(), MildPoisonCommand::doQueueCommand(), MediumDiseaseCommand::doQueueCommand(), MediumPoisonCommand::doQueueCommand(), StrongDiseaseCommand::doQueueCommand(), StrongPoisonCommand::doQueueCommand(), TurretFireManualCommand::doQueueCommand(), CreatureAreaAttackCommand::doQueueCommand(), DizzyAttackCommand::doQueueCommand(), CreatureAreaBleedingCommand::doQueueCommand(), IntimidationAttackCommand::doQueueCommand(), PostureDownAttackCommand::doQueueCommand(), PostureUpAttackCommand::doQueueCommand(), KnockdownAttackCommand::doQueueCommand(), CreatureAreaDiseaseCommand::doQueueCommand(), CreatureAreaKnockdownCommand::doQueueCommand(), CreatureAreaPoisonCommand::doQueueCommand(), BlindAttackCommand::doQueueCommand(), FireHeavyWeaponCommand::doQueueCommand(), StunAttackCommand::doQueueCommand(), CreatureAreaComboCommand::doQueueCommand(), DefaultAttackCommand::doQueueCommand(), UnarmedHit1Command::doQueueCommand(), FlameSingle2Command::doQueueCommand(), UnarmedDizzy1Command::doQueueCommand(), UnderHandShotCommand::doQueueCommand(), VolleyFireAttackCommand::doQueueCommand(), FlurryShot1Command::doQueueCommand(), UnarmedBlind1Command::doQueueCommand(), Melee2hLunge1Command::doQueueCommand(), FlurryShot2Command::doQueueCommand(), WarningShotCommand::doQueueCommand(), TauntCommand::doQueueCommand(), WildShot1Command::doQueueCommand(), FlushingShot1Command::doQueueCommand(), WildShot2Command::doQueueCommand(), FireLightningCone1Command::doQueueCommand(), ChargeShot1Command::doQueueCommand(), FlushingShot2Command::doQueueCommand(), DisarmingShot1Command::doQueueCommand(), FullAutoArea1Command::doQueueCommand(), BurstShot2Command::doQueueCommand(), DisarmingShot2Command::doQueueCommand(), FullAutoArea2Command::doQueueCommand(), MindShot1Command::doQueueCommand(), FullAutoSingle1Command::doQueueCommand(), MindShot2Command::doQueueCommand(), MultiTargetPistolShotCommand::doQueueCommand(), BodyShot2Command::doQueueCommand(), BodyShot3Command::doQueueCommand(), FullAutoSingle2Command::doQueueCommand(), HeadShot1Command::doQueueCommand(), OverChargeShot1Command::doQueueCommand(), OverChargeShot2Command::doQueueCommand(), ChargeShot2Command::doQueueCommand(), PanicShotCommand::doQueueCommand(), HeadShot3Command::doQueueCommand(), PistolMeleeDefense1Command::doQueueCommand(), PistolMeleeDefense2Command::doQueueCommand(), DoubleTapCommand::doQueueCommand(), HealthShot1Command::doQueueCommand(), PointBlankArea1Command::doQueueCommand(), HealthShot2Command::doQueueCommand(), PointBlankSingle1Command::doQueueCommand(), PointBlankSingle2Command::doQueueCommand(), PolearmLunge1Command::doQueueCommand(), ConfusionShotCommand::doQueueCommand(), BleedingShotCommand::doQueueCommand(), KipUpShotCommand::doQueueCommand(), RollShotCommand::doQueueCommand(), ConcealShotCommand::doQueueCommand(), KnockdownFireCommand::doQueueCommand(), LastDitchCommand::doQueueCommand(), EyeShotCommand::doQueueCommand(), LegShot1Command::doQueueCommand(), LegShot2Command::doQueueCommand(), LegShot3Command::doQueueCommand(), FanShotCommand::doQueueCommand(), LowBlowCommand::doQueueCommand(), ActionShot1Command::doQueueCommand(), FastBlastCommand::doQueueCommand(), ActionShot2Command::doQueueCommand(), FireAcidCone1Command::doQueueCommand(), FireAcidCone2Command::doQueueCommand(), FireAcidSingle1Command::doQueueCommand(), ScatterShot1Command::doQueueCommand(), ScatterShot2Command::doQueueCommand(), FireAcidSingle2Command::doQueueCommand(), SniperShotCommand::doQueueCommand(), UnarmedHit3Command::doQueueCommand(), SprayShotCommand::doQueueCommand(), StartleShot1Command::doQueueCommand(), StartleShot2Command::doQueueCommand(), StoppingShotCommand::doQueueCommand(), StrafeShot1Command::doQueueCommand(), StrafeShot2Command::doQueueCommand(), BodyShot1Command::doQueueCommand(), CripplingShotCommand::doQueueCommand(), FireLightningCone2Command::doQueueCommand(), SuppressionFire1Command::doQueueCommand(), SuppressionFire2Command::doQueueCommand(), ThrowGrenadeCommand::doQueueCommand(), TorsoShotCommand::doQueueCommand(), FireLightningSingle1Command::doQueueCommand(), BurstShot1Command::doQueueCommand(), FireLightningSingle2Command::doQueueCommand(), UnarmedBodyHit1Command::doQueueCommand(), UnarmedCombo1Command::doQueueCommand(), UnarmedCombo2Command::doQueueCommand(), FlameCone1Command::doQueueCommand(), UnarmedHeadHit1Command::doQueueCommand(), UnarmedHit2Command::doQueueCommand(), UnarmedKnockdown2Command::doQueueCommand(), FlameCone2Command::doQueueCommand(), UnarmedKnockdown1Command::doQueueCommand(), UnarmedLegHit1Command::doQueueCommand(), FlameSingle1Command::doQueueCommand(), UnarmedSpinAttack1Command::doQueueCommand(), UnarmedSpinAttack2Command::doQueueCommand(), HeadShot2Command::doQueueCommand(), SaberPolearmDervishCommand::doQueueCommand(), ServerAsteroidDataListenCommand::doQueueCommand(), Warcry2Command::doQueueCommand(), Melee2hArea1Command::doQueueCommand(), Melee1hHit1Command::doQueueCommand(), DestroyTargetCommand::doQueueCommand(), Melee2hHit1Command::doQueueCommand(), UnpilotShipCommand::doQueueCommand(), Melee2hHit3Command::doQueueCommand(), Melee2hSweep2Command::doQueueCommand(), AttackCommand::doQueueCommand(), DisableTargetCommand::doQueueCommand(), Melee1hSpinAttack1Command::doQueueCommand(), Melee2hMindHit2Command::doQueueCommand(), ServerAsteroidDataStopListeningCommand::doQueueCommand(), Melee1hLunge1Command::doQueueCommand(), Melee2hSweep1Command::doQueueCommand(), UnarmedLunge1Command::doQueueCommand(), Warcry1Command::doQueueCommand(), Bstrike3Command::doQueueCommand(), SaberPolearmLegHit3Command::doQueueCommand(), SaberPolearmLegHit2Command::doQueueCommand(), SaberPolearmHit1Command::doQueueCommand(), DiveShotCommand::doQueueCommand(), NblastCommand::doQueueCommand(), OpenWingsCommand::doQueueCommand(), VrepairCommand::doQueueCommand(), SaberPolearmSpinAttack3Command::doQueueCommand(), SaberThrow3Command::doQueueCommand(), SaberThrow2Command::doQueueCommand(), SaberPolearmHit2Command::doQueueCommand(), SaberPolearmHit3Command::doQueueCommand(), SaberPolearmSpinAttack1Command::doQueueCommand(), SaberPolearmLegHit1Command::doQueueCommand(), RequestSpaceTrainerCommand::doQueueCommand(), CloseWingsCommand::doQueueCommand(), HyperspaceCommand::doQueueCommand(), SendFormObjectDataCommand::doQueueCommand(), IffscrambleCommand::doQueueCommand(), UndockCommand::doQueueCommand(), SaberSlash2Command::doQueueCommand(), Melee1hBodyHit1Command::doQueueCommand(), Melee1hBlindHit2Command::doQueueCommand(), DrainForceCommand::doQueueCommand(), Saber1hHit3Command::doQueueCommand(), InspacereloadCommand::doQueueCommand(), InspacerepairCommand::doQueueCommand(), BoosterOffCommand::doQueueCommand(), InspacerrCommand::doQueueCommand(), DroidCommand::doQueueCommand(), UnarmedStun1Command::doQueueCommand(), Epulse1Command::doQueueCommand(), LaunchMissileCommand::doQueueCommand(), LaunchCountermeasureCommand::doQueueCommand(), Saber1hHeadHit1Command::doQueueCommand(), Intimidate1Command::doQueueCommand(), BoosterOnCommand::doQueueCommand(), Saber1hComboHit1Command::doQueueCommand(), Jstart3Command::doQueueCommand(), Ptrap2Command::doQueueCommand(), Intimidate2Command::doQueueCommand(), Epulse2Command::doQueueCommand(), Melee2hHit2Command::doQueueCommand(), Epulse3Command::doQueueCommand(), Jstart2Command::doQueueCommand(), Ptrap1Command::doQueueCommand(), EscapePodCommand::doQueueCommand(), EshieldsCommand::doQueueCommand(), Saber1hFlurryCommand::doQueueCommand(), EthrustCommand::doQueueCommand(), PilotShipCommand::doQueueCommand(), Saber1hHeadHit3Command::doQueueCommand(), Melee2hLunge2Command::doQueueCommand(), LeaveStationCommand::doQueueCommand(), EweaponsCommand::doQueueCommand(), Bstrike1Command::doQueueCommand(), Saber1hHit1Command::doQueueCommand(), LightEngineScrambleCommand::doQueueCommand(), Saber1hHit2Command::doQueueCommand(), Saber1hHeadHit2Command::doQueueCommand(), Bstrike2Command::doQueueCommand(), Melee1hBlindHit1Command::doQueueCommand(), UnarmedLunge2Command::doQueueCommand(), Saber1hComboHit2Command::doQueueCommand(), PointBlankArea2Command::doQueueCommand(), Melee1hBodyHit3Command::doQueueCommand(), Saber1hComboHit3Command::doQueueCommand(), InspectCommand::doQueueCommand(), Jstart1Command::doQueueCommand(), PumpreactorCommand::doQueueCommand(), VrepairotherCommand::doQueueCommand(), AborthyperspaceCommand::doQueueCommand(), PolearmLunge2Command::doQueueCommand(), SaberThrow1Command::doQueueCommand(), DockCommand::doQueueCommand(), Saber1hFlurry2Command::doQueueCommand(), Melee1hHealthHit1Command::doQueueCommand(), PolearmArea1Command::doQueueCommand(), PolearmLegHit3Command::doQueueCommand(), PolearmSpinAttack2Command::doQueueCommand(), Saber2hPhantomCommand::doQueueCommand(), Saber2hSweep3Command::doQueueCommand(), Melee2hHeadHit2Command::doQueueCommand(), PolearmSweep1Command::doQueueCommand(), Saber2hBodyHit3Command::doQueueCommand(), Melee2hArea2Command::doQueueCommand(), Saber2hBodyHit1Command::doQueueCommand(), Saber2hSweep1Command::doQueueCommand(), Saber2hSweep2Command::doQueueCommand(), PolearmStun1Command::doQueueCommand(), PolearmHit3Command::doQueueCommand(), PolearmActionHit2Command::doQueueCommand(), Melee2hArea3Command::doQueueCommand(), Melee1hHit2Command::doQueueCommand(), Melee1hLunge2Command::doQueueCommand(), Melee2hHeadHit3Command::doQueueCommand(), PolearmHit1Command::doQueueCommand(), PolearmArea2Command::doQueueCommand(), PolearmStun2Command::doQueueCommand(), PolearmSpinAttack1Command::doQueueCommand(), Melee1hDizzyHit1Command::doQueueCommand(), Melee1hHealthHit2Command::doQueueCommand(), Saber2hFrenzyCommand::doQueueCommand(), PolearmHit2Command::doQueueCommand(), Saber2hHit1Command::doQueueCommand(), Saber2hBodyHit2Command::doQueueCommand(), Saber2hHit3Command::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), Saber2hHit2Command::doQueueCommand(), PolearmLegHit2Command::doQueueCommand(), SaberPolearmSpinAttack2Command::doQueueCommand(), Melee1hScatterHit1Command::doQueueCommand(), Melee1hScatterHit2Command::doQueueCommand(), PolearmLegHit1Command::doQueueCommand(), Melee2hSpinAttack2Command::doQueueCommand(), Melee1hSpinAttack2Command::doQueueCommand(), SaberPolearmDervish2Command::doQueueCommand(), Melee2hMindHit1Command::doQueueCommand(), Melee1hBodyHit2Command::doQueueCommand(), Melee2hHeadHit1Command::doQueueCommand(), Melee1hHit3Command::doQueueCommand(), PolearmActionHit1Command::doQueueCommand(), PolearmSweep2Command::doQueueCommand(), Melee1hDizzyHit2Command::doQueueCommand(), Melee2hSpinAttack1Command::doQueueCommand(), and MinefieldAttackTask::run().
int CombatQueueCommand::getAccuracyBonus () const inline
Definition at line 257 of file CombatQueueCommand.h.
References accuracyBonus.
Referenced by CreatureAttackData::fillFromBase().
String CombatQueueCommand::getAccuracySkillMod () const inline
Definition at line 245 of file CombatQueueCommand.h.
References accuracySkillMod.
Referenced by CombatManager::applyStates(), and CombatManager::doTargetCombatAction().
float CombatQueueCommand::getActionCostMultiplier () const inline
Definition at line 233 of file CombatQueueCommand.h.
References actionCostMultiplier.
Referenced by CreatureAttackData::fillFromBase().
uint32 CombatQueueCommand::getAnimationCRC () const inline
Definition at line 445 of file CombatQueueCommand.h.
References animationCRC.
Referenced by CreatureAttackData::fillFromBase().
int CombatQueueCommand::getAreaRange () const inline
Definition at line 309 of file CombatQueueCommand.h.
References areaRange.
Referenced by CreatureAttackData::fillFromBase().
uint8 CombatQueueCommand::getAttackType () const inline
Definition at line 633 of file CombatQueueCommand.h.
References attackType.
Referenced by CreatureAttackData::fillFromBase().
int CombatQueueCommand::getBlindChance () const inline
Definition at line 249 of file CombatQueueCommand.h.
References blindStateChance.
String CombatQueueCommand::getCombatSpam () const inline
Definition at line 453 of file CombatQueueCommand.h.
References combatSpam.
Referenced by CombatManager::doTargetCombatAction(), and CreatureAttackData::fillFromBase().
float CombatQueueCommand::getCommandDuration (CreatureObject * object, const UnicodeString & arguments) inline virtual
Returns duration of the command
Reimplemented from server::zone::objects::creature::commands::QueueCommand.
Reimplemented in ThrowGrenadeCommand, FireHeavyWeaponCommand, DrainForceCommand, ForcePowersQueueCommand, and HeavyWeaponQueueCommand.
Definition at line 205 of file CombatQueueCommand.h.
References server::zone::objects::creature::CreatureObject::getWeapon(), and speedMultiplier.
int CombatQueueCommand::getConeAngle () const inline
Definition at line 305 of file CombatQueueCommand.h.
References coneAngle.
Referenced by CreatureAttackData::fillFromBase().
float CombatQueueCommand::getDamage () const inline
Definition at line 497 of file CombatQueueCommand.h.
References damage.
Referenced by CreatureAttackData::fillFromBase().
float CombatQueueCommand::getDamageMultiplier () const inline
Definition at line 253 of file CombatQueueCommand.h.
References damageMultiplier.
Referenced by CreatureAttackData::fillFromBase().
int CombatQueueCommand::getDizzyChance () const inline
Definition at line 261 of file CombatQueueCommand.h.
References dizzyStateChance.
uint32 CombatQueueCommand::getDotDuration () const inline
Definition at line 209 of file CombatQueueCommand.h.
References dotDuration.
Referenced by CreatureAttackData::fillFromBase().
DotEffect CombatQueueCommand::getDotEffect (uint64 type) inline
Definition at line 509 of file CombatQueueCommand.h.
References dotEffects.
VectorMap<uint64, DotEffect>* CombatQueueCommand::getDotEffects () inline
Definition at line 465 of file CombatQueueCommand.h.
References dotEffects.
Referenced by CreatureAttackData::fillFromBase().
uint8 CombatQueueCommand::getDotPool () const inline
Definition at line 217 of file CombatQueueCommand.h.
References dotPool.
Referenced by CreatureAttackData::fillFromBase().
float CombatQueueCommand::getDotPotency () const inline
Definition at line 225 of file CombatQueueCommand.h.
References dotPotency.
Referenced by CreatureAttackData::fillFromBase().
uint32 CombatQueueCommand::getDotStrength () const inline
Definition at line 221 of file CombatQueueCommand.h.
References dotStrength.
Referenced by CreatureAttackData::fillFromBase().
uint64 CombatQueueCommand::getDotType () const inline
Definition at line 213 of file CombatQueueCommand.h.
References dotType.
Referenced by CreatureAttackData::fillFromBase().
int CombatQueueCommand::getDurationStateTime () const inline
Definition at line 313 of file CombatQueueCommand.h.
References durationStateTime.
Referenced by CreatureAttackData::fillFromBase().
String CombatQueueCommand::getEffectString () const inline
Definition at line 449 of file CombatQueueCommand.h.
References effectString.
Referenced by CombatManager::broadcastCombatAction().
float CombatQueueCommand::getForceCost () const inline
Definition at line 321 of file CombatQueueCommand.h.
References forceCost.
float CombatQueueCommand::getForceCostMultiplier () const inline
Definition at line 317 of file CombatQueueCommand.h.
References forceCostMultiplier.
Referenced by CreatureAttackData::fillFromBase().
float CombatQueueCommand::getHealthCostMultiplier () const inline
Definition at line 229 of file CombatQueueCommand.h.
References healthCostMultiplier.
Referenced by CreatureAttackData::fillFromBase().
int CombatQueueCommand::getIntimidateChance () const inline
Definition at line 265 of file CombatQueueCommand.h.
References intimidateStateChance.
int CombatQueueCommand::getKnockdownChance () const inline
Definition at line 269 of file CombatQueueCommand.h.
References knockdownStateChance.
float CombatQueueCommand::getMindCostMultiplier () const inline
Definition at line 237 of file CombatQueueCommand.h.
References mindCostMultiplier.
Referenced by CreatureAttackData::fillFromBase().
int CombatQueueCommand::getNextAttackDelayChance () const inline
Definition at line 325 of file CombatQueueCommand.h.
References nextAttackDelayChance.
Referenced by CreatureAttackData::fillFromBase().
int CombatQueueCommand::getPoolsToDamage () const inline
Definition at line 457 of file CombatQueueCommand.h.
References poolsToDamage.
Referenced by CreatureAttackData::fillFromBase().
int CombatQueueCommand::getPostureDownChance () const inline
Definition at line 273 of file CombatQueueCommand.h.
References postureDownStateChance.
int CombatQueueCommand::getPostureUpChance () const inline
Definition at line 277 of file CombatQueueCommand.h.
References postureUpStateChance.
int CombatQueueCommand::getRange () const inline
Definition at line 241 of file CombatQueueCommand.h.
References range.
Referenced by CreatureAttackData::fillFromBase().
float CombatQueueCommand::getSpeed () const inline
Definition at line 285 of file CombatQueueCommand.h.
References speed.
float CombatQueueCommand::getSpeedMultiplier () const inline
Definition at line 281 of file CombatQueueCommand.h.
References speedMultiplier.
Referenced by CreatureAttackData::fillFromBase().
StateEffect CombatQueueCommand::getStateEffect (uint64 type) inline
Definition at line 489 of file CombatQueueCommand.h.
References stateEffects.
Referenced by applyEffect().
VectorMap<uint64, StateEffect>* CombatQueueCommand::getStateEffects () inline
Definition at line 461 of file CombatQueueCommand.h.
References stateEffects.
Referenced by CreatureAttackData::fillFromBase().
int CombatQueueCommand::getStunChance () const inline
Definition at line 289 of file CombatQueueCommand.h.
References stunStateChance.
uint8 CombatQueueCommand::getTrails () const inline
Definition at line 641 of file CombatQueueCommand.h.
References trails.
Referenced by CreatureAttackData::fillFromBase().
bool CombatQueueCommand::hasCombatSpam () inline
Definition at line 521 of file CombatQueueCommand.h.
References combatSpam.
bool CombatQueueCommand::isAreaAction () const inline
Definition at line 293 of file CombatQueueCommand.h.
References areaAction.
Referenced by CombatManager::applyDamage(), and CombatManager::doCombatAction().
bool CombatQueueCommand::isCombatCommand () inline virtual
Reimplemented from server::zone::objects::creature::commands::QueueCommand.
Definition at line 525 of file CombatQueueCommand.h.
bool CombatQueueCommand::isConeAction () const inline
Definition at line 297 of file CombatQueueCommand.h.
References coneAction.
Referenced by CombatManager::applyDamage(), CombatManager::doAreaCombatAction(), and CombatManager::doCombatAction().
bool CombatQueueCommand::isDotDamageOfHit () const inline
Definition at line 301 of file CombatQueueCommand.h.
References dotDamageOfHit.
virtual bool CombatQueueCommand::isSquadLeaderCommand () inline virtual
Reimplemented in SquadLeaderCommand.
Definition at line 529 of file CombatQueueCommand.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setAccuracyBonus (int accuracyBonus) inline
Definition at line 337 of file CombatQueueCommand.h.
References accuracyBonus.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setAccuracySkillMod (String acc) inline
Definition at line 517 of file CombatQueueCommand.h.
References accuracySkillMod.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setActionCostMultiplier (float f) inline
Definition at line 345 of file CombatQueueCommand.h.
References actionCostMultiplier.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setAnimationCRC (uint32 animationCRC) inline
Definition at line 469 of file CombatQueueCommand.h.
References animationCRC.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setAreaAction (bool b) inline
Definition at line 417 of file CombatQueueCommand.h.
References areaAction.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setAreaRange (int i) inline
Definition at line 425 of file CombatQueueCommand.h.
References areaRange.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setAttackType (uint8 attackType) inline
Definition at line 637 of file CombatQueueCommand.h.
References attackType.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setBlindStateChance (int blindStateChance) inline
Definition at line 329 of file CombatQueueCommand.h.
References blindStateChance.
void CombatQueueCommand::setCombatSpam (String combatSpam) inline
Definition at line 473 of file CombatQueueCommand.h.
References combatSpam.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setConeAction (bool b) inline
Definition at line 421 of file CombatQueueCommand.h.
References coneAction.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setConeAngle (int i) inline
Definition at line 409 of file CombatQueueCommand.h.
References coneAngle.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setDamage (float dm) inline
Definition at line 501 of file CombatQueueCommand.h.
References damage.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setDamageMultiplier (float damageMultiplier) inline
Definition at line 333 of file CombatQueueCommand.h.
References damageMultiplier.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setDizzyStateChance (int dizzyStateChance) inline
Definition at line 361 of file CombatQueueCommand.h.
References dizzyStateChance.
void CombatQueueCommand::setDotDamageOfHit (bool b) inline
Definition at line 413 of file CombatQueueCommand.h.
References dotDamageOfHit.
void CombatQueueCommand::setDotDuration (uint32 i) inline
Definition at line 389 of file CombatQueueCommand.h.
References dotDuration.
void CombatQueueCommand::setDotEffects (VectorMap< uint64, DotEffect > dotEffects) inline
Definition at line 493 of file CombatQueueCommand.h.
References dotEffects.
void CombatQueueCommand::setDotPool (uint8 c) inline
Definition at line 397 of file CombatQueueCommand.h.
References dotPool.
void CombatQueueCommand::setDotPotency (float f) inline
Definition at line 405 of file CombatQueueCommand.h.
References dotPotency.
void CombatQueueCommand::setDotStrength (uint32 i) inline
Definition at line 401 of file CombatQueueCommand.h.
References dotStrength.
void CombatQueueCommand::setDotType (uint64 l) inline
Definition at line 393 of file CombatQueueCommand.h.
References dotType.
void CombatQueueCommand::setDurationStateTime (int i) inline
Definition at line 385 of file CombatQueueCommand.h.
References durationStateTime.
void CombatQueueCommand::setEffectString (String s) inline
Definition at line 429 of file CombatQueueCommand.h.
References effectString.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setForceCost (float f) inline
Definition at line 357 of file CombatQueueCommand.h.
References forceCost.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setForceCostMultiplier (float f) inline
Definition at line 353 of file CombatQueueCommand.h.
References forceCostMultiplier.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setHealthCostMultiplier (float f) inline
Definition at line 341 of file CombatQueueCommand.h.
References healthCostMultiplier.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setIntimidateStateChance (int intimidateStateChance) inline
Definition at line 365 of file CombatQueueCommand.h.
References intimidateStateChance.
void CombatQueueCommand::setKnockdownStateChance (int knockdownStateChance) inline
Definition at line 369 of file CombatQueueCommand.h.
References knockdownStateChance.
void CombatQueueCommand::setMindCostMultiplier (float f) inline
Definition at line 349 of file CombatQueueCommand.h.
References mindCostMultiplier.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setNextAttackDelayChance (int i) inline
Definition at line 381 of file CombatQueueCommand.h.
References nextAttackDelayChance.
void CombatQueueCommand::setPoolsToDamage (int poolsToDamage) inline
Definition at line 477 of file CombatQueueCommand.h.
References poolsToDamage.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setPostureDownStateChance (int postureDownStateChance) inline
Definition at line 373 of file CombatQueueCommand.h.
References postureDownStateChance.
void CombatQueueCommand::setPostureUpStateChance (int postureUpStateChance) inline
Definition at line 377 of file CombatQueueCommand.h.
References postureUpStateChance.
void CombatQueueCommand::setRange (int i) inline
Definition at line 513 of file CombatQueueCommand.h.
References range.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setSpeed (float speedd) inline
Definition at line 437 of file CombatQueueCommand.h.
References speed.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setSpeedMultiplier (float speedMultiplier) inline
Definition at line 433 of file CombatQueueCommand.h.
References speedMultiplier.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void CombatQueueCommand::setStateEffects (VectorMap< uint64, StateEffect > stateEffects) inline
Definition at line 481 of file CombatQueueCommand.h.
References stateEffects.
void CombatQueueCommand::setStunStateChance (int stunStateChance) inline
Definition at line 441 of file CombatQueueCommand.h.
References stunStateChance.
void CombatQueueCommand::setTrails (uint8 trails) inline
Definition at line 645 of file CombatQueueCommand.h.
References trails.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
Member Data Documentation
int CombatQueueCommand::accuracyBonus protected
Definition at line 30 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getAccuracyBonus(), and setAccuracyBonus().
String CombatQueueCommand::accuracySkillMod protected
Definition at line 61 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getAccuracySkillMod(), and setAccuracySkillMod().
float CombatQueueCommand::actionCostMultiplier protected
Definition at line 36 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getActionCostMultiplier(), and setActionCostMultiplier().
uint32 CombatQueueCommand::animationCRC protected
Definition at line 70 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getAnimationCRC(), and setAnimationCRC().
bool CombatQueueCommand::areaAction protected
Definition at line 63 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), isAreaAction(), and setAreaAction().
int CombatQueueCommand::areaRange protected
Definition at line 66 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getAreaRange(), and setAreaRange().
uint8 CombatQueueCommand::attackType protected
Definition at line 76 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getAttackType(), and setAttackType().
int CombatQueueCommand::blindStateChance protected
Definition at line 46 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getBlindChance(), and setBlindStateChance().
String CombatQueueCommand::combatSpam protected
Definition at line 68 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getCombatSpam(), hasCombatSpam(), SquadLeaderCommand::sendCombatSpam(), setCombatSpam(), and SquadLeaderCommand::SquadLeaderCommand().
bool CombatQueueCommand::coneAction protected
Definition at line 64 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), isConeAction(), and setConeAction().
int CombatQueueCommand::coneAngle protected
Definition at line 65 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getConeAngle(), and setConeAngle().
float CombatQueueCommand::damage protected
Definition at line 28 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), ThrowTrapCommand::doQueueCommand(), getDamage(), and setDamage().
float CombatQueueCommand::damageMultiplier protected
Definition at line 29 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getDamageMultiplier(), and setDamageMultiplier().
int CombatQueueCommand::dizzyStateChance protected
Definition at line 45 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getDizzyChance(), and setDizzyStateChance().
bool CombatQueueCommand::dotDamageOfHit protected
Definition at line 57 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), isDotDamageOfHit(), and setDotDamageOfHit().
uint32 CombatQueueCommand::dotDuration protected
Definition at line 52 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getDotDuration(), and setDotDuration().
VectorMap<uint64, DotEffect> CombatQueueCommand::dotEffects protected
Definition at line 74 of file CombatQueueCommand.h.
Referenced by addDotEffect(), getDotEffect(), getDotEffects(), and setDotEffects().
uint8 CombatQueueCommand::dotPool protected
Definition at line 54 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getDotPool(), and setDotPool().
float CombatQueueCommand::dotPotency protected
Definition at line 56 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getDotPotency(), and setDotPotency().
uint32 CombatQueueCommand::dotStrength protected
Definition at line 55 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getDotStrength(), and setDotStrength().
uint64 CombatQueueCommand::dotType protected
Definition at line 53 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getDotType(), and setDotType().
int CombatQueueCommand::durationStateTime protected
Definition at line 50 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getDurationStateTime(), and setDurationStateTime().
String CombatQueueCommand::effectString protected
Definition at line 71 of file CombatQueueCommand.h.
Referenced by getEffectString(), and setEffectString().
float CombatQueueCommand::forceCost protected
Definition at line 39 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), ForcePowersQueueCommand::doCombatAction(), getForceCost(), and setForceCost().
float CombatQueueCommand::forceCostMultiplier protected
Definition at line 38 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getForceCostMultiplier(), and setForceCostMultiplier().
float CombatQueueCommand::healthCostMultiplier protected
Definition at line 35 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getHealthCostMultiplier(), and setHealthCostMultiplier().
int CombatQueueCommand::intimidateStateChance protected
Definition at line 48 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getIntimidateChance(), and setIntimidateStateChance().
int CombatQueueCommand::knockdownStateChance protected
Definition at line 41 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getKnockdownChance(), and setKnockdownStateChance().
float CombatQueueCommand::mindCostMultiplier protected
Definition at line 37 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getMindCostMultiplier(), and setMindCostMultiplier().
int CombatQueueCommand::nextAttackDelayChance protected
Definition at line 49 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getNextAttackDelayChance(), and setNextAttackDelayChance().
int CombatQueueCommand::poolsToDamage protected
Definition at line 33 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getPoolsToDamage(), and setPoolsToDamage().
int CombatQueueCommand::postureDownStateChance protected
Definition at line 42 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getPostureDownChance(), and setPostureDownStateChance().
int CombatQueueCommand::postureUpStateChance protected
Definition at line 43 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getPostureUpChance(), and setPostureUpStateChance().
int CombatQueueCommand::range protected
Definition at line 59 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), doCombatAction(), getRange(), and setRange().
float CombatQueueCommand::speed protected
Definition at line 32 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), HeavyWeaponQueueCommand::getCommandDuration(), ForcePowersQueueCommand::getCommandDuration(), getSpeed(), and setSpeed().
float CombatQueueCommand::speedMultiplier protected
Definition at line 31 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), FireHeavyWeaponCommand::getCommandDuration(), ThrowGrenadeCommand::getCommandDuration(), getCommandDuration(), getSpeedMultiplier(), and setSpeedMultiplier().
VectorMap<uint64, StateEffect> CombatQueueCommand::stateEffects protected
Definition at line 73 of file CombatQueueCommand.h.
Referenced by addStateEffect(), getStateEffect(), getStateEffects(), and setStateEffects().
String CombatQueueCommand::stateSpam protected
Definition at line 69 of file CombatQueueCommand.h.
int CombatQueueCommand::stunStateChance protected
Definition at line 47 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getStunChance(), and setStunStateChance().
uint8 CombatQueueCommand::trails protected
Definition at line 77 of file CombatQueueCommand.h.
Referenced by CombatQueueCommand(), getTrails(), and setTrails().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/CombatQueueCommand.h