Core3: GiveItemCommand Class Reference
GiveItemCommand Class Reference
#include <GiveItemCommand.h>
Public Member Functions
GiveItemCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Public Member Functions inherited from server::zone::objects::creature::commands::QueueCommand
QueueCommand (const String &skillname, ZoneProcessServer *serv)
virtual ~QueueCommand ()
bool checkInvalidLocomotions (CreatureObject *creature)
void onStateFail (CreatureObject *creature, uint32 actioncntr)
void onLocomotionFail (CreatureObject *creature, uint32 actioncntr)
virtual String getSyntax () const
virtual void onFail (uint32 actioncntr, CreatureObject *creature, uint32 errorNumber)
virtual void onComplete (uint32 actioncntr, CreatureObject *creature, float commandDuration)
void setInvalidLocomotions (const String &lStr)
void addInvalidLocomotion (int l)
bool checkStateMask (CreatureObject *creature)
virtual float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
void setStateMask (uint64 mask)
void setDefaultTime (float time)
void setTargetType (int num)
void setDisabled (bool state)
void setDisabled (int state)
void setAddToCombatQueue (bool state)
void setAddToCombatQueue (int state)
void setCommandGroup (int val)
void setMaxRange (float r)
void setCharacterAbility (const String &ability)
void setDefaultPriority (const String &priority)
void setDefaultPriority (const int priority)
uint64 getStateMask ()
bool requiresAdmin ()
int getTargetType ()
uint32 getNameCRC ()
float getMaxRange ()
String & getQueueCommandName ()
String & getCharacterAbility ()
float getDefaultTime ()
int getDefaultPriority ()
bool isDisabled ()
bool addToCombatQueue ()
virtual bool isCombatCommand ()
int getSkillModSize ()
int getSkillMod (int index, String &skillMod)
int getCommandGroup ()
void addSkillMod (const String &skillMod, const int value)
bool isWearingArmor (CreatureObject *creo)
virtual void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::creature::commands::QueueCommand
static const int IMMEDIATE = 0
static const int FRONT = 1
static const int NORMAL = 2
static const int SUCCESS = 0
static const int GENERALERROR = 1
static const int INVALIDLOCOMOTION = 2
static const int INVALIDSTATE = 3
static const int INVALIDTARGET = 4
static const int INVALIDWEAPON = 5
static const int TOOFAR = 6
static const int INSUFFICIENTHAM = 7
static const int INVALIDPARAMETERS = 8
static const int NOPRONE = 9
static const int NOKNEELING = 10
static const int INSUFFICIENTPERMISSION = 11
static const int NOJEDIARMOR = 12
static const int INVALIDSYNTAX = 13
Protected Attributes inherited from server::zone::objects::creature::commands::QueueCommand
ZoneProcessServer * server
String name
uint32 nameCRC
uint64 stateMask
Vector< int > invalidLocomotion
int targetType
int maxRangeToTarget
bool disabled
bool addToQueue
bool admin
uint32 cooldown
float defaultTime
String characterAbility
int defaultPriority
VectorMap< String, int > skillMods
int commandGroup
Detailed Description
Definition at line 56 of file GiveItemCommand.h.
Constructor & Destructor Documentation
GiveItemCommand::GiveItemCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 59 of file GiveItemCommand.h.
Member Function Documentation
int GiveItemCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline virtual
Reimplemented from server::zone::objects::creature::commands::QueueCommand.
Definition at line 64 of file GiveItemCommand.h.
References server::zone::managers::creature::CreatureManager::addWearableItem(), server::zone::objects::tangible::wearables::WearableObject::applyAttachment(), server::chat::ChatManager::broadcastMessage(), server::zone::objects::creature::commands::QueueCommand::checkInvalidLocomotions(), server::zone::objects::creature::commands::QueueCommand::checkStateMask(), server::zone::objects::creature::commands::QueueCommand::GENERALERROR, server::zone::ZoneProcessServer::getChatManager(), server::zone::Zone::getCreatureManager(), server::zone::objects::creature::CreatureObject::getMoodID(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getObjectID(), VendorDataComponent::getOwnerId(), server::zone::objects::scene::SceneObject::getZone(), server::zone::ZoneProcessServer::getZoneServer(), server::zone::objects::creature::commands::QueueCommand::INVALIDLOCOMOTION, server::zone::objects::creature::commands::QueueCommand::INVALIDSTATE, server::zone::objects::creature::commands::QueueCommand::server, and server::zone::objects::creature::commands::QueueCommand::SUCCESS.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/GiveItemCommand.h