Core3: server::zone::managers::creature::StaticSpawnGroup Class Reference
server::zone::managers::creature::StaticSpawnGroup Class Reference
#include <StaticSpawnGroup.h>
Public Member Functions
StaticSpawnGroup ()
StaticSpawnGroup (const StaticSpawnGroup &gr)
StaticSpawnGroup (const String &tempName, LuaObject &group)
virtual ~StaticSpawnGroup ()
StaticSpawnGroup & operator= (const StaticSpawnGroup &gr)
Vector< SpawnCoordinate > * getSpawnList ()
int getRespawnTime () const
float getX () const
float getY () const
float getZ () const
uint64 getCellID () const
bool isStaticGroup ()
Public Member Functions inherited from server::zone::managers::creature::SpawnGroup
SpawnGroup ()
SpawnGroup (const String &tempName, LuaObject &group)
SpawnGroup (const SpawnGroup &gr)
virtual ~SpawnGroup ()
SpawnGroup & operator= (const SpawnGroup &gr)
String getTemplateName () const
float getWanderRadius () const
int getCommandLevel () const
unsigned int getType () const
void setWanderRadius (float wanderRadius)
void setTemplateName (String templateName)
void setCommandLevel (int commandLevel)
void setType (unsigned int type)
virtual bool isDynamicGroup ()
Protected Attributes
Vector< SpawnCoordinate > spawnMap
int respawnTime
float x
float y
float z
uint64 cellID
Protected Attributes inherited from server::zone::managers::creature::SpawnGroup
String templateName
float wanderRadius
int commandLevel
unsigned int type
Detailed Description
Definition at line 72 of file StaticSpawnGroup.h.
Constructor & Destructor Documentation
server::zone::managers::creature::StaticSpawnGroup::StaticSpawnGroup () inline
Definition at line 82 of file StaticSpawnGroup.h.
server::zone::managers::creature::StaticSpawnGroup::StaticSpawnGroup (const StaticSpawnGroup & gr) inline
Definition at line 84 of file StaticSpawnGroup.h.
References cellID, respawnTime, spawnMap, x, y, and z.
server::zone::managers::creature::StaticSpawnGroup::StaticSpawnGroup (const String & tempName, LuaObject & group) inline
Definition at line 93 of file StaticSpawnGroup.h.
References cellID, respawnTime, server::zone::managers::creature::SpawnCoordinate::set(), server::zone::managers::creature::SpawnCoordinate::setPosition(), server::zone::managers::creature::SpawnCoordinate::setTemplateName(), spawnMap, x, y, and z.
virtual server::zone::managers::creature::StaticSpawnGroup::~StaticSpawnGroup () inline virtual
Definition at line 129 of file StaticSpawnGroup.h.
Member Function Documentation
uint64 server::zone::managers::creature::StaticSpawnGroup::getCellID () const inline
Definition at line 165 of file StaticSpawnGroup.h.
References cellID.
Referenced by server::zone::objects::creature::aigroup::AiGroupImplementation::setup().
int server::zone::managers::creature::StaticSpawnGroup::getRespawnTime () const inline
Definition at line 149 of file StaticSpawnGroup.h.
References respawnTime.
Referenced by server::zone::objects::creature::aigroup::AiGroupImplementation::setup().
Vector<SpawnCoordinate>* server::zone::managers::creature::StaticSpawnGroup::getSpawnList () inline
Definition at line 145 of file StaticSpawnGroup.h.
References spawnMap.
Referenced by server::zone::objects::creature::aigroup::AiGroupImplementation::setup().
float server::zone::managers::creature::StaticSpawnGroup::getX () const inline
Definition at line 153 of file StaticSpawnGroup.h.
References x.
Referenced by server::zone::objects::area::StaticSpawnAreaImplementation::spawnCreatures().
float server::zone::managers::creature::StaticSpawnGroup::getY () const inline
Definition at line 157 of file StaticSpawnGroup.h.
References y.
Referenced by server::zone::objects::area::StaticSpawnAreaImplementation::spawnCreatures().
float server::zone::managers::creature::StaticSpawnGroup::getZ () const inline
Definition at line 161 of file StaticSpawnGroup.h.
References z.
Referenced by server::zone::objects::area::StaticSpawnAreaImplementation::spawnCreatures().
bool server::zone::managers::creature::StaticSpawnGroup::isStaticGroup () inline virtual
Reimplemented from server::zone::managers::creature::SpawnGroup.
Definition at line 169 of file StaticSpawnGroup.h.
StaticSpawnGroup& server::zone::managers::creature::StaticSpawnGroup::operator= (const StaticSpawnGroup & gr) inline
Definition at line 131 of file StaticSpawnGroup.h.
References cellID, respawnTime, spawnMap, x, y, and z.
Member Data Documentation
uint64 server::zone::managers::creature::StaticSpawnGroup::cellID protected
Definition at line 79 of file StaticSpawnGroup.h.
Referenced by getCellID(), operator=(), and StaticSpawnGroup().
int server::zone::managers::creature::StaticSpawnGroup::respawnTime protected
Definition at line 76 of file StaticSpawnGroup.h.
Referenced by getRespawnTime(), operator=(), and StaticSpawnGroup().
Vector<SpawnCoordinate> server::zone::managers::creature::StaticSpawnGroup::spawnMap protected
Definition at line 74 of file StaticSpawnGroup.h.
Referenced by getSpawnList(), operator=(), and StaticSpawnGroup().
float server::zone::managers::creature::StaticSpawnGroup::x protected
Definition at line 78 of file StaticSpawnGroup.h.
Referenced by getX(), operator=(), and StaticSpawnGroup().
float server::zone::managers::creature::StaticSpawnGroup::y protected
Definition at line 78 of file StaticSpawnGroup.h.
Referenced by getY(), operator=(), and StaticSpawnGroup().
float server::zone::managers::creature::StaticSpawnGroup::z protected
Definition at line 78 of file StaticSpawnGroup.h.
Referenced by getZ(), operator=(), and StaticSpawnGroup().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/StaticSpawnGroup.h