Core3: ServerCore Class Reference
ServerCore Class Reference
#include <ServerCore.h>
Public Member Functions
ServerCore (bool truncateDatabases, SortedVector< String > &args)
void initialize ()
void run ()
void shutdown ()
void handleCommands ()
void processConfig ()
void signalShutdown ()
Static Public Member Functions
static server::zone::ZoneServer * getZoneServer ()
static bool truncateDatabases ()
static ServerCore * getInstance ()
static bool hasArgument (const String &arg)
Private Attributes
ConfigManager * configManager
ServerDatabase * database
MantisDatabase * mantisDatabase
DistributedObjectBroker * orb
ManagedReference
< server::login::LoginServer * > loginServer
StatusServer * statusServer
Features * features
PingServer * pingServer
WebServer * webServer
Mutex shutdownBlockMutex
Condition waitCondition
Static Private Attributes
static SortedVector< String > arguments
static ManagedReference
< server::zone::ZoneServer * > zoneServerRef = NULL
static bool truncateAllData = false
static ServerCore * instance = NULL
Detailed Description
Definition at line 83 of file ServerCore.h.
Constructor & Destructor Documentation
ServerCore::ServerCore (bool truncateDatabases, SortedVector< String > & args)
Definition at line 76 of file ServerCore.cpp.
References arguments, configManager, database, features, instance, loginServer, mantisDatabase, orb, pingServer, statusServer, truncateAllData, truncateDatabases(), webServer, and zoneServerRef.
Member Function Documentation
static ServerCore* ServerCore::getInstance () inline static
Definition at line 137 of file ServerCore.h.
Referenced by ShutdownTask::run().
static server::zone::ZoneServer* ServerCore::getZoneServer () inline static
Definition at line 129 of file ServerCore.h.
Referenced by server::zone::managers::player::PlayerManagerImplementation::cleanupCharacters(), server::zone::managers::director::DirectorManager::createLoot(), server::zone::managers::director::DirectorManager::createLootFromCollection(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::despawnNpcs(), server::zone::managers::player::PlayerManagerImplementation::getCleanupCharacterCount(), server::zone::managers::director::DirectorManager::getCreatureObject(), server::zone::managers::director::DirectorManager::getRegion(), server::zone::managers::director::DirectorManager::getSceneObject(), server::zone::managers::director::DirectorManager::isZoneEnabled(), AbilityList::loadFromNames(), server::zone::objects::area::LairSpawnAreaImplementation::notifyObserverEvent(), server::zone::ZoneReference::parseFromBinaryStream(), server::zone::managers::player::creation::PlayerCreationManager::PlayerCreationManager(), server::zone::objects::region::CityRegionImplementation::rescheduleUpdateEvent(), DeleteCharactersTask::run(), server::zone::managers::director::DirectorManager::spatialChat(), server::zone::managers::director::DirectorManager::spatialMoodChat(), server::zone::managers::director::DirectorManager::spawnMobile(), server::zone::managers::director::DirectorManager::spawnMobileRandom(), and server::zone::managers::director::DirectorManager::spawnSceneObject().
void ServerCore::handleCommands ()
Definition at line 325 of file ServerCore.cpp.
References arguments, server::chat::ChatManager::broadcastGalaxy(), server::zone::ZoneServer::changeUserCap(), server::zone::managers::player::PlayerManager::cleanupCharacters(), server::zone::ZoneServer::fixScheduler(), server::zone::ZoneServer::getChatManager(), server::zone::managers::player::PlayerManager::getCleanupCharacterCount(), server::zone::ZoneServer::getPlayerManager(), loginServer, pingServer, PingServer::printInfo(), server::zone::ZoneServer::printInfo(), server::zone::ZoneServer::setServerStateLocked(), server::zone::ZoneServer::setServerStateOnline(), shutdownBlockMutex, server::zone::ZoneServer::timedShutdown(), waitCondition, and zoneServerRef.
Referenced by run().
static bool ServerCore::hasArgument (const String & arg) inline static
Definition at line 141 of file ServerCore.h.
Referenced by server::zone::managers::stringid::StringIdManager::StringIdManager().
void ServerCore::initialize ()
Definition at line 119 of file ServerCore.cpp.
References arguments, server::zone::managers::player::PlayerManager::cleanupCharacters(), configManager, database, server::zone::managers::player::PlayerManager::getCleanupCharacterCount(), server::conf::ConfigManager::getLoginAllowedConnections(), server::conf::ConfigManager::getLoginPort(), server::conf::ConfigManager::getMakeLogin(), server::conf::ConfigManager::getMakePing(), server::conf::ConfigManager::getMakeStatus(), server::conf::ConfigManager::getMakeWeb(), server::conf::ConfigManager::getMakeZone(), server::conf::ConfigManager::getORBNamingDirectoryAddress(), server::conf::ConfigManager::getPingAllowedConnections(), server::conf::ConfigManager::getPingPort(), server::zone::ZoneServer::getPlayerManager(), server::conf::ConfigManager::getStatusAllowedConnections(), server::conf::ConfigManager::getStatusPort(), server::conf::ConfigManager::getZoneAllowedConnections(), server::conf::ConfigManager::getZoneGalaxyID(), ServerDatabase::instance(), loginServer, mantisDatabase, orb, pingServer, processConfig(), shutdown(), server::web::WebServer::start(), server::zone::ZoneServer::start(), statusServer, truncateDatabases(), webServer, and zoneServerRef.
void ServerCore::processConfig ()
Definition at line 503 of file ServerCore.cpp.
References configManager, and server::conf::ConfigManager::loadConfigData().
Referenced by initialize().
void ServerCore::run ()
Definition at line 254 of file ServerCore.cpp.
References handleCommands(), and shutdown().
void ServerCore::shutdown ()
Definition at line 260 of file ServerCore.cpp.
References database, features, loginServer, mantisDatabase, pingServer, statusServer, server::web::WebServer::stop(), server::zone::ZoneServer::stop(), webServer, and zoneServerRef.
Referenced by initialize(), and run().
void ServerCore::signalShutdown ()
Definition at line 111 of file ServerCore.cpp.
References shutdownBlockMutex, and waitCondition.
Referenced by ShutdownTask::run().
static bool ServerCore::truncateDatabases () inline static
Definition at line 133 of file ServerCore.h.
Referenced by server::login::account::AccountManager::AccountManager(), initialize(), server::zone::managers::object::ObjectManager::loadLastUsedObjectID(), server::zone::managers::object::ObjectManager::ObjectManager(), server::zone::managers::player::PlayerManagerImplementation::PlayerManagerImplementation(), ServerCore(), and server::zone::managers::stringid::StringIdManager::StringIdManager().
Member Data Documentation
SortedVector< String > ServerCore::arguments static private
Definition at line 105 of file ServerCore.h.
Referenced by handleCommands(), initialize(), and ServerCore().
ConfigManager* ServerCore::configManager private
Definition at line 84 of file ServerCore.h.
Referenced by initialize(), processConfig(), and ServerCore().
ServerDatabase* ServerCore::database private
Definition at line 86 of file ServerCore.h.
Referenced by initialize(), ServerCore(), and shutdown().
Features* ServerCore::features private
Definition at line 96 of file ServerCore.h.
Referenced by ServerCore(), and shutdown().
ServerCore * ServerCore::instance = NULL static private
Definition at line 111 of file ServerCore.h.
Referenced by ServerCore().
ManagedReference<server::login::LoginServer*> ServerCore::loginServer private
Definition at line 92 of file ServerCore.h.
Referenced by handleCommands(), initialize(), ServerCore(), and shutdown().
MantisDatabase* ServerCore::mantisDatabase private
Definition at line 88 of file ServerCore.h.
Referenced by initialize(), ServerCore(), and shutdown().
DistributedObjectBroker* ServerCore::orb private
Definition at line 90 of file ServerCore.h.
Referenced by initialize(), and ServerCore().
PingServer* ServerCore::pingServer private
Definition at line 98 of file ServerCore.h.
Referenced by handleCommands(), initialize(), ServerCore(), and shutdown().
Mutex ServerCore::shutdownBlockMutex private
Definition at line 102 of file ServerCore.h.
Referenced by handleCommands(), and signalShutdown().
StatusServer* ServerCore::statusServer private
Definition at line 94 of file ServerCore.h.
Referenced by initialize(), ServerCore(), and shutdown().
bool ServerCore::truncateAllData = false static private
Definition at line 109 of file ServerCore.h.
Referenced by ServerCore().
Condition ServerCore::waitCondition private
Definition at line 103 of file ServerCore.h.
Referenced by handleCommands(), and signalShutdown().
WebServer* ServerCore::webServer private
Definition at line 100 of file ServerCore.h.
Referenced by initialize(), ServerCore(), and shutdown().
ManagedReference< ZoneServer * > ServerCore::zoneServerRef = NULL static private
Definition at line 107 of file ServerCore.h.
Referenced by handleCommands(), initialize(), ServerCore(), and shutdown().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/ServerCore.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/ServerCore.cpp