Core3: server::zone::managers::gcw::GCWManager Class Reference
server::zone::managers::gcw::GCWManager Class Reference
#include <GCWManager.h>
Public Member Functions
GCWManager (Zone *zne)
void loadLuaConfig ()
void initialize ()
void start ()
void registerGCWBase (BuildingObject *building, bool initializeBase)
void unregisterGCWBase (BuildingObject *building)
void performGCWTasks ()
void startVulnerability (BuildingObject *building)
void endVulnerability (BuildingObject *building)
bool isBaseVulnerable (BuildingObject *building)
bool isBandIdentified (BuildingObject *building)
bool isUplinkJammed (BuildingObject *building)
bool isShutdownSequenceStarted (BuildingObject *building)
bool isSecurityTermSliced (BuildingObject *building)
bool isPowerOverloaded (BuildingObject *building)
void resetVulnerability (CreatureObject *creature, BuildingObject *building)
void sendBaseDefenseStatus (CreatureObject *creature, BuildingObject *building)
void doBaseDestruction (StructureObject *structure)
void doBaseDestruction (BuildingObject *building)
void sendResetVerification (CreatureObject *creature, BuildingObject *building)
void sendJamUplinkMenu (CreatureObject *creature, BuildingObject *building, TangibleObject *uplinkTerminal)
void verifyUplinkBand (CreatureObject *creature, BuildingObject *building, int band)
bool canStartSlice (CreatureObject *creature, TangibleObject *terminal)
void sendDNASampleMenu (CreatureObject *creature, BuildingObject *building, TangibleObject *overrideTerminal)
void completeSecuritySlice (CreatureObject *creature, TangibleObject *securityTerminal)
void failSecuritySlice (TangibleObject *securityTerminal)
bool isTerminalDamaged (TangibleObject *securityTerminal)
bool isDNASampled (BuildingObject *building)
void repairTerminal (CreatureObject *creature, TangibleObject *securityTerminal)
void abortShutdownSequence (BuildingObject *building, CreatureObject *creature)
void processDNASample (CreatureObject *creature, TangibleObject *overrideTerminal, const String &sampleChain, int indx)
void handlePowerRegulatorSwitch (CreatureObject *creature, TangibleObject *powerRegulator, int indx)
void sendPowerRegulatorControls (CreatureObject *creature, BuildingObject *building, TangibleObject *powerRegulator)
String getDNAHash (const String &usersample)
bool isPlanetCapped ()
void scheduleBaseDestruction (BuildingObject *building, CreatureObject *creature)
void initializeNewVulnerability (BuildingObject *building)
void notifyInstallationDestruction (InstallationObject *installation)
void notifyTurretDestruction (BuildingObject *building, InstallationObject *turret)
void notifyMinefieldDestruction (BuildingObject *building, InstallationObject *turret)
void sendSelectDeedToDonate (BuildingObject *building, CreatureObject *creature, int turretIndex)
void sendRemoveDefenseConfirmation (BuildingObject *building, CreatureObject *creature, unsigned long long deedOID)
void performDefenseDontation (BuildingObject *building, CreatureObject *creature, unsigned long long deedOID, int turretIndex)
void sendStatus (BuildingObject *building, CreatureObject *creature)
void addMinefield (BuildingObject *building, SceneObject *minefield)
void addTurret (BuildingObject *building, SceneObject *turret)
void addScanner (BuildingObject *building, SceneObject *scanner)
void removeDefense (BuildingObject *building, CreatureObject *creature, unsigned long long deedOID)
bool canUseTerminals (CreatureObject *creature, BuildingObject *building, SceneObject *terminal)
void sendTurretAttackListTo (CreatureObject *creature, SceneObject *turretControlTerminal)
bool canPlaceMoreBases (CreatureObject *creature)
int getImperialBaseCount ()
int getRebelBaseCount ()
int getRebelScore ()
int getImperialScore ()
void setRebelScore (int val)
void setImperialScore (int val)
unsigned int getWinningFaction ()
float getGCWDiscount (CreatureObject *creature)
int getGCWXPBonus ()
void broadcastBuilding (BuildingObject *building, StringIdChatParameter &params)
int getPointValue (const String &templateString)
void addPointValue (const String &templateString, int val)
void addRacialPenalty (int race, float val)
float getRacialPenalty (int race)
bool isRacialPenaltyEnabled ()
bool shouldSpawnDefenses ()
int getInitialVulnerabilityDelay ()
void awardSlicingXP (CreatureObject *creature, const String &xpType, int value)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int IMPERIALHASH = 3679112276
static const int REBELHASH = 370444368
static const int NOTAFACTIONBASE = 0
static const int PLAYERFACTIONBASE = 1
static const int STATICFACTIONBASE = 2
Protected Member Functions
GCWManager (DummyConstructorParameter *param)
virtual ~GCWManager ()
Friends
class GCWManagerHelper
Detailed Description
Definition at line 169 of file GCWManager.h.
Constructor & Destructor Documentation
GCWManager::GCWManager (Zone * zne)
Definition at line 31 of file GCWManager.cpp.
References server::zone::managers::gcw::GCWManagerImplementation::_setStub().
GCWManager::GCWManager (DummyConstructorParameter * param) protected
Definition at line 38 of file GCWManager.cpp.
GCWManager::~GCWManager () protected virtual
Definition at line 42 of file GCWManager.cpp.
Member Function Documentation
DistributedObjectServant * GCWManager::_getImplementation ()
Definition at line 966 of file GCWManager.cpp.
Referenced by abortShutdownSequence(), addMinefield(), addPointValue(), addRacialPenalty(), addScanner(), addTurret(), awardSlicingXP(), broadcastBuilding(), canPlaceMoreBases(), canStartSlice(), canUseTerminals(), completeSecuritySlice(), doBaseDestruction(), endVulnerability(), failSecuritySlice(), getDNAHash(), getGCWDiscount(), getImperialBaseCount(), getPointValue(), getRacialPenalty(), getRebelBaseCount(), getWinningFaction(), handlePowerRegulatorSwitch(), initialize(), initializeNewVulnerability(), isBandIdentified(), isBaseVulnerable(), isDNASampled(), isPlanetCapped(), isPowerOverloaded(), isSecurityTermSliced(), isShutdownSequenceStarted(), isTerminalDamaged(), isUplinkJammed(), loadLuaConfig(), notifyInstallationDestruction(), notifyMinefieldDestruction(), notifyTurretDestruction(), performDefenseDontation(), performGCWTasks(), processDNASample(), registerGCWBase(), removeDefense(), repairTerminal(), resetVulnerability(), scheduleBaseDestruction(), sendBaseDefenseStatus(), sendDNASampleMenu(), sendJamUplinkMenu(), sendPowerRegulatorControls(), sendRemoveDefenseConfirmation(), sendResetVerification(), sendSelectDeedToDonate(), sendStatus(), sendTurretAttackListTo(), setImperialScore(), setRebelScore(), start(), startVulnerability(), unregisterGCWBase(), and verifyUplinkBand().
DistributedObjectServant * GCWManager::_getImplementationForRead ()
Definition at line 972 of file GCWManager.cpp.
Referenced by getGCWXPBonus(), getImperialScore(), getInitialVulnerabilityDelay(), getRebelScore(), isRacialPenaltyEnabled(), and shouldSpawnDefenses().
void GCWManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 976 of file GCWManager.cpp.
void GCWManager::abortShutdownSequence (BuildingObject * building, CreatureObject * creature)
Definition at line 448 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::abortShutdownSequence(), and RPC_ABORTSHUTDOWNSEQUENCE__BUILDINGOBJECT_CREATUREOBJECT_.
void GCWManager::addMinefield (BuildingObject * building, SceneObject * minefield)
Definition at line 678 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::addMinefield(), and RPC_ADDMINEFIELD__BUILDINGOBJECT_SCENEOBJECT_.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects().
void GCWManager::addPointValue (const String & templateString, int val)
Definition at line 896 of file GCWManager.cpp.
References _getImplementation(), and server::zone::managers::gcw::GCWManagerImplementation::addPointValue().
void GCWManager::addRacialPenalty (int race, float val)
Definition at line 905 of file GCWManager.cpp.
References _getImplementation(), and server::zone::managers::gcw::GCWManagerImplementation::addRacialPenalty().
void GCWManager::addScanner (BuildingObject * building, SceneObject * scanner)
Definition at line 708 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::addScanner(), and RPC_ADDSCANNER__BUILDINGOBJECT_SCENEOBJECT_.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects().
void GCWManager::addTurret (BuildingObject * building, SceneObject * turret)
Definition at line 693 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::addTurret(), and RPC_ADDTURRET__BUILDINGOBJECT_SCENEOBJECT_.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects().
void GCWManager::awardSlicingXP (CreatureObject * creature, const String & xpType, int value)
Definition at line 950 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::awardSlicingXP(), and RPC_AWARDSLICINGXP__CREATUREOBJECT_STRING_INT_.
void GCWManager::broadcastBuilding (BuildingObject * building, StringIdChatParameter & params)
Definition at line 878 of file GCWManager.cpp.
References _getImplementation(), and server::zone::managers::gcw::GCWManagerImplementation::broadcastBuilding().
bool GCWManager::canPlaceMoreBases (CreatureObject * creature)
Definition at line 770 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::canPlaceMoreBases(), and RPC_CANPLACEMOREBASES__CREATUREOBJECT_.
Referenced by StructureManager::placeStructureFromDeed().
bool GCWManager::canStartSlice (CreatureObject * creature, TangibleObject * terminal)
Definition at line 345 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::canStartSlice(), and RPC_CANSTARTSLICE__CREATUREOBJECT_TANGIBLEOBJECT_.
Referenced by server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::handleObjectMenuSelect().
bool GCWManager::canUseTerminals (CreatureObject * creature, BuildingObject * building, SceneObject * terminal)
Definition at line 739 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::canUseTerminals(), and RPC_CANUSETERMINALS__CREATUREOBJECT_BUILDINGOBJECT_SCENEOBJECT_.
Referenced by PowerRegulatorMenuComponent::fillObjectMenuResponse(), TurretControlMenuComponent::fillObjectMenuResponse(), OverrideTerminalMenuComponent::fillObjectMenuResponse(), UplinkTerminalMenuComponent::fillObjectMenuResponse(), SecurityTerminalMenuComponent::fillObjectMenuResponse(), HQMenuComponent::fillObjectMenuResponse(), PowerRegulatorMenuComponent::handleObjectMenuSelect(), and OverrideTerminalMenuComponent::handleObjectMenuSelect().
void GCWManager::completeSecuritySlice (CreatureObject * creature, TangibleObject * securityTerminal)
Definition at line 376 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::completeSecuritySlice(), and RPC_COMPLETESECURITYSLICE__CREATUREOBJECT_TANGIBLEOBJECT_.
void GCWManager::doBaseDestruction (StructureObject * structure)
Definition at line 270 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::doBaseDestruction(), and RPC_DOBASEDESTRUCTION__STRUCTUREOBJECT_.
Referenced by server::zone::objects::player::sessions::DestroyStructureSessionImplementation::destroyStructure().
void GCWManager::doBaseDestruction (BuildingObject * building)
Definition at line 284 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::doBaseDestruction(), and RPC_DOBASEDESTRUCTION__BUILDINGOBJECT_.
void GCWManager::endVulnerability (BuildingObject * building)
Definition at line 142 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::endVulnerability(), and RPC_ENDVULNERABILITY__BUILDINGOBJECT_.
void GCWManager::failSecuritySlice (TangibleObject * securityTerminal)
Definition at line 391 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::failSecuritySlice(), and RPC_FAILSECURITYSLICE__TANGIBLEOBJECT_.
Referenced by server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceFailed().
String GCWManager::getDNAHash (const String & usersample)
Definition at line 512 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::getDNAHash(), and RPC_GETDNAHASH__STRING_.
float GCWManager::getGCWDiscount (CreatureObject * creature)
Definition at line 855 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::getGCWDiscount(), and RPC_GETGCWDISCOUNT__CREATUREOBJECT_.
Referenced by server::zone::managers::director::DirectorManager::getGCWDiscount().
int GCWManager::getGCWXPBonus ()
Definition at line 869 of file GCWManager.cpp.
References _getImplementationForRead(), and server::zone::managers::gcw::GCWManagerImplementation::getGCWXPBonus().
Referenced by server::zone::managers::player::PlayerManagerImplementation::disseminateExperience().
int GCWManager::getImperialBaseCount ()
Definition at line 784 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::getImperialBaseCount(), and RPC_GETIMPERIALBASECOUNT__.
Referenced by GcwStatusCommand::doQueueCommand().
int GCWManager::getImperialScore ()
Definition at line 819 of file GCWManager.cpp.
References _getImplementationForRead(), and server::zone::managers::gcw::GCWManagerImplementation::getImperialScore().
Referenced by GcwStatusCommand::doQueueCommand().
int GCWManager::getInitialVulnerabilityDelay ()
Definition at line 941 of file GCWManager.cpp.
References _getImplementationForRead(), and server::zone::managers::gcw::GCWManagerImplementation::getInitialVulnerabilityDelay().
int GCWManager::getPointValue (const String & templateString)
Definition at line 887 of file GCWManager.cpp.
References _getImplementation(), and server::zone::managers::gcw::GCWManagerImplementation::getPointValue().
float GCWManager::getRacialPenalty (int race)
Definition at line 914 of file GCWManager.cpp.
References _getImplementation(), and server::zone::managers::gcw::GCWManagerImplementation::getRacialPenalty().
int GCWManager::getRebelBaseCount ()
Definition at line 797 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::getRebelBaseCount(), and RPC_GETREBELBASECOUNT__.
Referenced by GcwStatusCommand::doQueueCommand().
int GCWManager::getRebelScore ()
Definition at line 810 of file GCWManager.cpp.
References _getImplementationForRead(), and server::zone::managers::gcw::GCWManagerImplementation::getRebelScore().
Referenced by GcwStatusCommand::doQueueCommand().
unsigned int GCWManager::getWinningFaction ()
Definition at line 846 of file GCWManager.cpp.
References _getImplementation(), and server::zone::managers::gcw::GCWManagerImplementation::getWinningFaction().
Referenced by server::zone::managers::player::PlayerManagerImplementation::disseminateExperience().
void GCWManager::handlePowerRegulatorSwitch (CreatureObject * creature, TangibleObject * powerRegulator, int indx)
Definition at line 480 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::handlePowerRegulatorSwitch(), and RPC_HANDLEPOWERREGULATORSWITCH__CREATUREOBJECT_TANGIBLEOBJECT_INT_.
Referenced by PowerRegulatorSuiCallback::run().
void GCWManager::initialize ()
Definition at line 60 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::initialize(), and RPC_INITIALIZE__.
void GCWManager::initializeNewVulnerability (BuildingObject * building)
Definition at line 556 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::initializeNewVulnerability(), and RPC_INITIALIZENEWVULNERABILITY__BUILDINGOBJECT_.
Referenced by server::zone::objects::building::LuaBuildingObject::initializeStaticGCWBase().
bool GCWManager::isBandIdentified (BuildingObject * building)
Definition at line 170 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::isBandIdentified(), and RPC_ISBANDIDENTIFIED__BUILDINGOBJECT_.
bool GCWManager::isBaseVulnerable (BuildingObject * building)
Definition at line 156 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::isBaseVulnerable(), and RPC_ISBASEVULNERABLE__BUILDINGOBJECT_.
Referenced by UplinkTerminalMenuComponent::fillObjectMenuResponse().
bool GCWManager::isDNASampled (BuildingObject * building)
Definition at line 419 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::isDNASampled(), and RPC_ISDNASAMPLED__BUILDINGOBJECT_.
Referenced by PowerRegulatorMenuComponent::fillObjectMenuResponse(), and OverrideTerminalMenuComponent::fillObjectMenuResponse().
bool GCWManager::isPlanetCapped ()
Definition at line 528 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::isPlanetCapped(), and RPC_ISPLANETCAPPED__.
Referenced by PlaceGCWBaseComponent::placeStructure().
bool GCWManager::isPowerOverloaded (BuildingObject * building)
Definition at line 226 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::isPowerOverloaded(), and RPC_ISPOWEROVERLOADED__BUILDINGOBJECT_.
Referenced by PowerRegulatorMenuComponent::fillObjectMenuResponse(), and HQMenuComponent::fillObjectMenuResponse().
bool GCWManager::isRacialPenaltyEnabled ()
Definition at line 923 of file GCWManager.cpp.
References _getImplementationForRead(), and server::zone::managers::gcw::GCWManagerImplementation::isRacialPenaltyEnabled().
bool GCWManager::isSecurityTermSliced (BuildingObject * building)
Definition at line 212 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::isSecurityTermSliced(), and RPC_ISSECURITYTERMSLICED__BUILDINGOBJECT_.
Referenced by OverrideTerminalMenuComponent::fillObjectMenuResponse(), and SecurityTerminalMenuComponent::fillObjectMenuResponse().
bool GCWManager::isShutdownSequenceStarted (BuildingObject * building)
Definition at line 198 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::isShutdownSequenceStarted(), and RPC_ISSHUTDOWNSEQUENCESTARTED__BUILDINGOBJECT_.
Referenced by HQMenuComponent::fillObjectMenuResponse().
bool GCWManager::isTerminalDamaged (TangibleObject * securityTerminal)
Definition at line 405 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::isTerminalDamaged(), and RPC_ISTERMINALDAMAGED__TANGIBLEOBJECT_.
Referenced by SecurityTerminalMenuComponent::fillObjectMenuResponse().
bool GCWManager::isUplinkJammed (BuildingObject * building)
Definition at line 184 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::isUplinkJammed(), and RPC_ISUPLINKJAMMED__BUILDINGOBJECT_.
Referenced by SecurityTerminalMenuComponent::fillObjectMenuResponse(), and UplinkTerminalMenuComponent::fillObjectMenuResponse().
void GCWManager::loadLuaConfig ()
Definition at line 47 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::loadLuaConfig(), and RPC_LOADLUACONFIG__.
void GCWManager::notifyInstallationDestruction (InstallationObject * installation)
Definition at line 570 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::notifyInstallationDestruction(), and RPC_NOTIFYINSTALLATIONDESTRUCTION__INSTALLATIONOBJECT_.
Referenced by DestroyFactionInstallationTask::run().
void GCWManager::notifyMinefieldDestruction (BuildingObject * building, InstallationObject * turret)
Definition at line 599 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::notifyMinefieldDestruction(), and RPC_NOTIFYMINEFIELDDESTRUCTION__BUILDINGOBJECT_INSTALLATIONOBJECT_.
void GCWManager::notifyTurretDestruction (BuildingObject * building, InstallationObject * turret)
Definition at line 584 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::notifyTurretDestruction(), and RPC_NOTIFYTURRETDESTRUCTION__BUILDINGOBJECT_INSTALLATIONOBJECT_.
void GCWManager::performDefenseDontation (BuildingObject * building, CreatureObject * creature, unsigned long long deedOID, int turretIndex)
Definition at line 646 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::performDefenseDontation(), and RPC_PERFORMDEFENSEDONTATION__BUILDINGOBJECT_CREATUREOBJECT_LONG_INT_.
Referenced by DonateDefenseSuiCallback::run().
void GCWManager::performGCWTasks ()
Definition at line 115 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::performGCWTasks(), and RPC_PERFORMGCWTASKS__.
void GCWManager::processDNASample (CreatureObject * creature, TangibleObject * overrideTerminal, const String & sampleChain, int indx)
Definition at line 463 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::processDNASample(), and RPC_PROCESSDNASAMPLE__CREATUREOBJECT_TANGIBLEOBJECT_STRING_INT_.
Referenced by OverrideTerminalSuiCallback::run().
void GCWManager::registerGCWBase (BuildingObject * building, bool initializeBase)
Definition at line 86 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::registerGCWBase(), and RPC_REGISTERGCWBASE__BUILDINGOBJECT_BOOL_.
Referenced by server::zone::objects::building::LuaBuildingObject::initializeStaticGCWBase(), StructureManager::loadPlayerStructures(), and PlaceGCWBaseComponent::notifyStructurePlaced().
void GCWManager::removeDefense (BuildingObject * building, CreatureObject * creature, unsigned long long deedOID)
Definition at line 723 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::removeDefense(), and RPC_REMOVEDEFENSE__BUILDINGOBJECT_CREATUREOBJECT_LONG_.
Referenced by RemoveDefenseSuiCallback::run().
void GCWManager::repairTerminal (CreatureObject * creature, TangibleObject * securityTerminal)
Definition at line 433 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::repairTerminal(), and RPC_REPAIRTERMINAL__CREATUREOBJECT_TANGIBLEOBJECT_.
Referenced by SecurityTerminalMenuComponent::handleObjectMenuSelect().
void GCWManager::resetVulnerability (CreatureObject * creature, BuildingObject * building)
Definition at line 240 of file GCWManager.cpp.
References _getImplementation(), server::zone::managers::gcw::GCWManagerImplementation::resetVulnerability(), and RPC_RESETVULNERABILITY__CREATUREOBJECT_BUILDINGOBJECT_.
Referenced by HQSendResetVerificationSuiCallback::run().
void GCWManager::scheduleBaseDestruction (BuildingObject * building, CreatureObject * creature)
Definition at line 541 of file GCWManager.cpp.
References _getImplementation(), RPC_SCHEDULEBASEDESTRUCTION__BUILDINGOBJECT_CREATUREOBJECT_, and server::zone::managers::gcw::GCWManagerImplementation::scheduleBaseDestruction().
void GCWManager::sendBaseDefenseStatus (CreatureObject * creature, BuildingObject * building)
Definition at line 255 of file GCWManager.cpp.
References _getImplementation(), RPC_SENDBASEDEFENSESTATUS__CREATUREOBJECT_BUILDINGOBJECT_, and server::zone::managers::gcw::GCWManagerImplementation::sendBaseDefenseStatus().
void GCWManager::sendDNASampleMenu (CreatureObject * creature, BuildingObject * building, TangibleObject * overrideTerminal)
Definition at line 360 of file GCWManager.cpp.
References _getImplementation(), RPC_SENDDNASAMPLEMENU__CREATUREOBJECT_BUILDINGOBJECT_TANGIBLEOBJECT_, and server::zone::managers::gcw::GCWManagerImplementation::sendDNASampleMenu().
Referenced by OverrideTerminalMenuComponent::handleObjectMenuSelect().
void GCWManager::sendJamUplinkMenu (CreatureObject * creature, BuildingObject * building, TangibleObject * uplinkTerminal)
Definition at line 313 of file GCWManager.cpp.
References _getImplementation(), RPC_SENDJAMUPLINKMENU__CREATUREOBJECT_BUILDINGOBJECT_TANGIBLEOBJECT_, and server::zone::managers::gcw::GCWManagerImplementation::sendJamUplinkMenu().
Referenced by UplinkTerminalMenuComponent::handleObjectMenuSelect().
void GCWManager::sendPowerRegulatorControls (CreatureObject * creature, BuildingObject * building, TangibleObject * powerRegulator)
Definition at line 496 of file GCWManager.cpp.
References _getImplementation(), RPC_SENDPOWERREGULATORCONTROLS__CREATUREOBJECT_BUILDINGOBJECT_TANGIBLEOBJECT_, and server::zone::managers::gcw::GCWManagerImplementation::sendPowerRegulatorControls().
Referenced by PowerRegulatorMenuComponent::handleObjectMenuSelect().
void GCWManager::sendRemoveDefenseConfirmation (BuildingObject * building, CreatureObject * creature, unsigned long long deedOID)
Definition at line 630 of file GCWManager.cpp.
References _getImplementation(), RPC_SENDREMOVEDEFENSECONFIRMATION__BUILDINGOBJECT_CREATUREOBJECT_LONG_, and server::zone::managers::gcw::GCWManagerImplementation::sendRemoveDefenseConfirmation().
void GCWManager::sendResetVerification (CreatureObject * creature, BuildingObject * building)
Definition at line 298 of file GCWManager.cpp.
References _getImplementation(), RPC_SENDRESETVERIFICATION__CREATUREOBJECT_BUILDINGOBJECT_, and server::zone::managers::gcw::GCWManagerImplementation::sendResetVerification().
void GCWManager::sendSelectDeedToDonate (BuildingObject * building, CreatureObject * creature, int turretIndex)
Definition at line 614 of file GCWManager.cpp.
References _getImplementation(), RPC_SENDSELECTDEEDTODONATE__BUILDINGOBJECT_CREATUREOBJECT_INT_, and server::zone::managers::gcw::GCWManagerImplementation::sendSelectDeedToDonate().
Referenced by SelectTurretDonationSuiCallback::run().
void GCWManager::sendStatus (BuildingObject * building, CreatureObject * creature)
Definition at line 663 of file GCWManager.cpp.
References _getImplementation(), RPC_SENDSTATUS__BUILDINGOBJECT_CREATUREOBJECT_, and server::zone::managers::gcw::GCWManagerImplementation::sendStatus().
Referenced by HQMenuComponent::handleObjectMenuSelect().
void GCWManager::sendTurretAttackListTo (CreatureObject * creature, SceneObject * turretControlTerminal)
Definition at line 755 of file GCWManager.cpp.
References _getImplementation(), RPC_SENDTURRETATTACKLISTTO__CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::gcw::GCWManagerImplementation::sendTurretAttackListTo().
Referenced by TurretControlMenuComponent::handleObjectMenuSelect(), and TurretControlSuiCallback::run().
void GCWManager::setImperialScore (int val)
Definition at line 837 of file GCWManager.cpp.
References _getImplementation(), and server::zone::managers::gcw::GCWManagerImplementation::setImperialScore().
void GCWManager::setRebelScore (int val)
Definition at line 828 of file GCWManager.cpp.
References _getImplementation(), and server::zone::managers::gcw::GCWManagerImplementation::setRebelScore().
bool GCWManager::shouldSpawnDefenses ()
Definition at line 932 of file GCWManager.cpp.
References _getImplementationForRead(), and server::zone::managers::gcw::GCWManagerImplementation::shouldSpawnDefenses().
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects().
void GCWManager::start ()
Definition at line 73 of file GCWManager.cpp.
References _getImplementation(), RPC_START__, and server::zone::managers::gcw::GCWManagerImplementation::start().
void GCWManager::startVulnerability (BuildingObject * building)
Definition at line 128 of file GCWManager.cpp.
References _getImplementation(), RPC_STARTVULNERABILITY__BUILDINGOBJECT_, and server::zone::managers::gcw::GCWManagerImplementation::startVulnerability().
void GCWManager::unregisterGCWBase (BuildingObject * building)
Definition at line 101 of file GCWManager.cpp.
References _getImplementation(), RPC_UNREGISTERGCWBASE__BUILDINGOBJECT_, and server::zone::managers::gcw::GCWManagerImplementation::unregisterGCWBase().
Referenced by server::zone::objects::building::LuaBuildingObject::initializeStaticGCWBase().
void GCWManager::verifyUplinkBand (CreatureObject * creature, BuildingObject * building, int band)
Definition at line 329 of file GCWManager.cpp.
References _getImplementation(), RPC_VERIFYUPLINKBAND__CREATUREOBJECT_BUILDINGOBJECT_INT_, and server::zone::managers::gcw::GCWManagerImplementation::verifyUplinkBand().
Referenced by JamUplinkSuiCallback::run().
Friends And Related Function Documentation
friend class GCWManagerHelper friend
Definition at line 329 of file GCWManager.h.
Member Data Documentation
const int server::zone::managers::gcw::GCWManager::IMPERIALHASH = 3679112276 static
Definition at line 171 of file GCWManager.h.
const int server::zone::managers::gcw::GCWManager::NOTAFACTIONBASE = 0 static
Definition at line 175 of file GCWManager.h.
const int server::zone::managers::gcw::GCWManager::PLAYERFACTIONBASE = 1 static
Definition at line 177 of file GCWManager.h.
const int server::zone::managers::gcw::GCWManager::REBELHASH = 370444368 static
Definition at line 173 of file GCWManager.h.
const int server::zone::managers::gcw::GCWManager::STATICFACTIONBASE = 2 static
Definition at line 179 of file GCWManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/gcw/GCWManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/gcw/GCWManager.cpp