Core3: server::zone::managers::city::CityManagerImplementation Class Reference
server::zone::managers::city::CityManagerImplementation Class Reference
#include <CityManager.h>
Public Member Functions
CityManagerImplementation (ZoneServer *zserv)
CityManagerImplementation (DummyConstructorParameter *param)
void loadLuaConfig ()
void loadCityRegions ()
bool validateCityName (const String &name)
bool isCityInRange (Zone *zone, float x, float y)
CityRegion * createCity (CreatureObject *mayor, const String &cityName, float x, float y)
void processCityUpdate (CityRegion *city)
void processIncomeTax (CityRegion *city)
void updateCityVoting (CityRegion *city, bool override=false)
void deductCityMaintenance (CityRegion *city)
int collectNonStructureMaintenance (SceneObject *object, CityRegion *city, int maintenanceDue)
int collectCivicStructureMaintenance (StructureObject *structure, CityRegion *city, int maintenanceDue)
void sendMaintenanceEmail (CityRegion *city, int maintenancePaid)
void sendMaintenanceDecayEmail (CityRegion *city, StructureObject *structure, int maintenanceDue)
void sendMaintenanceDestroyEmail (CityRegion *city, StructureObject *structure)
void sendMaintenanceRepairEmail (CityRegion *city, StructureObject *structure)
void contractCity (CityRegion *city)
void expandCity (CityRegion *city)
void destroyCity (CityRegion *city)
void sendStatusReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void promptCitySpecialization (CityRegion *city, CreatureObject *mayor, SceneObject *terminal=NULL)
void changeCitySpecialization (CityRegion *city, CreatureObject *mayor, const String &spec)
void promptWithdrawCityTreasury (CityRegion *city, CreatureObject *mayor, SceneObject *terminal=NULL)
void promptDepositCityTreasury (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void withdrawFromCityTreasury (CityRegion *city, CreatureObject *mayor, int value, const String &reason, SceneObject *terminal=NULL)
void depositToCityTreasury (CityRegion *city, CreatureObject *creature, int value)
void sendTreasuryReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void sendCitizenshipReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void registerCitizen (CityRegion *city, CreatureObject *creature)
void unregisterCitizen (CityRegion *city, CreatureObject *creature, bool inactive=false)
void sendManageMilitia (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void promptAddMilitiaMember (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void addMilitiaMember (CityRegion *city, CreatureObject *mayor, const String &playerName)
void removeMilitiaMember (CityRegion *city, CreatureObject *mayor, unsigned long long militiaid)
void sendCityAdvancement (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void promptRegisterCity (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void promptUnregisterCity (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void registerCity (CityRegion *city, CreatureObject *mayor)
void unregisterCity (CityRegion *city, CreatureObject *mayor)
void promptAdjustTaxes (CityRegion *city, CreatureObject *mayor, SceneObject *terminal=NULL)
void promptSetTax (CityRegion *city, CreatureObject *mayor, int selectedTax, SceneObject *terminal=NULL)
void setTax (CityRegion *city, CreatureObject *mayor, int selectedTax, int value)
void sendMaintenanceReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void sendMail (CityRegion *city, const String &sender, const UnicodeString &subject, StringIdChatParameter &params, WaypointObject *waypoint)
bool containsCityName (const String &name)
bool isCityRankCapped (const String &planetName, byte cityRank)
void sendCityReport (CreatureObject *creature, const String &planetName, byte rank)
bool validateCityInRange (CreatureObject *creature, Zone *zone, float x, float y)
void toggleZoningEnabled (CityRegion *city, CreatureObject *mayor)
int getTotalCities ()
bool renameCity (CityRegion *city, const String &newName)
void sendMayoralStandings (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void promptMayoralVote (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void registerForMayoralRace (CityRegion *city, CreatureObject *creature)
void castMayoralVote (CityRegion *city, CreatureObject *creature, unsigned long long oid)
void sendStructureReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void fixMayor (CityRegion *city, CreatureObject *mayor)
bool canSupportMoreDecorations (CityRegion *city)
CitySpecialization * getCitySpecialization (const String &cityspec)
CityTax * getCityTax (int idx)
void sendChangeCityName (CityRegion *city, CreatureObject *mayor)
operator const CityManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< CityManager * > _this
Static Public Attributes
static Vector< unsigned short > radiusPerRank
static Vector< byte > citizensPerRank
static int cityUpdateInterval = 0
static int newCityGracePeriod = 0
static unsigned long long citySpecializationCooldown = 0
static int cityVotingDuration = 0
static unsigned long long treasuryWithdrawalCooldown = 0
static byte cityVotingCycles = 0
static byte cityVotingCyclesUntilLocked = 0
static int decorationsPerRank = 10
static float maintenanceDiscount = 1.0f
static const byte CLIENT = 0
static const byte OUTPOST = 1
static const byte VILLAGE = 2
static const byte TOWNSHIP = 3
static const byte CITY = 4
static const byte METROPOLIS = 5
Protected Member Functions
virtual ~CityManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
ManagedReference< ZoneServer * > zoneServer
VectorMap< String,
ManagedReference< CityRegion * > > cities
Static Private Attributes
static CitiesAllowed citiesAllowedPerRank
static CitySpecializationMap citySpecializations
static CityTaxMap cityTaxes
Friends
class CityManager
Detailed Description
Definition at line 329 of file CityManager.h.
Constructor & Destructor Documentation
CityManagerImplementation::CityManagerImplementation (ZoneServer * zserv)
Definition at line 1082 of file CityManager.cpp.
References _initializeImplementation(), cities, and zoneServer.
CityManagerImplementation::CityManagerImplementation (DummyConstructorParameter * param)
Definition at line 968 of file CityManager.cpp.
References _initializeImplementation().
CityManagerImplementation::~CityManagerImplementation () protected virtual
Definition at line 973 of file CityManager.cpp.
Member Function Documentation
DistributedObjectStub * CityManagerImplementation::_getStub ()
Definition at line 993 of file CityManager.cpp.
References _this.
void CityManagerImplementation::_initializeImplementation () protected
Definition at line 980 of file CityManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CityManagerImplementation().
void CityManagerImplementation::_serializationHelperMethod () protected
Definition at line 1029 of file CityManager.cpp.
Referenced by _initializeImplementation().
void CityManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 988 of file CityManager.cpp.
References _this.
Referenced by server::zone::managers::city::CityManager::CityManager().
void CityManagerImplementation::addMilitiaMember (CityRegion * city, CreatureObject * mayor, const String & playerName)
Definition at line 1456 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::addMilitiaMember(), server::zone::managers::player::PlayerManager::getObjectID(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::region::CityRegion::isCitizen(), server::zone::objects::region::CityRegion::isMayor(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::addMilitiaMember().
bool CityManagerImplementation::canSupportMoreDecorations (CityRegion * city)
Definition at line 2244 of file CityManagerImplementation.cpp.
References decorationsPerRank, server::zone::objects::region::CityRegion::getCityRank(), and server::zone::objects::region::CityRegion::getDecorationCount().
Referenced by server::zone::managers::city::CityManager::canSupportMoreDecorations().
void CityManagerImplementation::castMayoralVote (CityRegion * city, CreatureObject * creature, unsigned long long oid)
Definition at line 2065 of file CityManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::region::CityRegion::isCandidate(), server::zone::objects::region::CityRegion::isCitizen(), server::zone::objects::region::CityRegion::isMayor(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::region::CityRegion::setMayoralVote(), server::chat::StringIdChatParameter::setTO(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::castMayoralVote().
void CityManagerImplementation::changeCitySpecialization (CityRegion * city, CreatureObject * mayor, const String & spec)
Definition at line 366 of file CityManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::addCooldown(), server::zone::objects::region::CityRegion::addMilitiaMember(), citySpecializationCooldown, server::zone::objects::region::CityRegion::getMilitiaMembers(), server::zone::objects::region::CityRegion::getRadius(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::region::CityRegion::setCitySpecialization(), server::zone::objects::region::CityRegion::setRadius(), and server::chat::StringIdChatParameter::setTO().
Referenced by server::zone::managers::city::CityManager::changeCitySpecialization().
int CityManagerImplementation::collectCivicStructureMaintenance (StructureObject * structure, CityRegion * city, int maintenanceDue)
Definition at line 896 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::getCityTreasury(), server::zone::objects::tangible::TangibleObject::getConditionDamage(), server::zone::objects::tangible::TangibleObject::getMaxCondition(), server::zone::objects::structure::StructureObject::getSurplusMaintenance(), sendMaintenanceDecayEmail(), sendMaintenanceDestroyEmail(), sendMaintenanceRepairEmail(), server::zone::objects::tangible::TangibleObject::setConditionDamage(), server::zone::objects::structure::StructureObject::setSurplusMaintenance(), and server::zone::objects::region::CityRegion::subtractFromCityTreasury().
Referenced by server::zone::managers::city::CityManager::collectCivicStructureMaintenance(), and deductCityMaintenance().
int CityManagerImplementation::collectNonStructureMaintenance (SceneObject * object, CityRegion * city, int maintenanceDue)
Definition at line 870 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::getCityTreasury(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::scene::SceneObject::isDecoration(), server::zone::objects::scene::SceneObject::isMissionTerminal(), server::zone::objects::region::CityRegion::removeDecoration(), server::zone::objects::region::CityRegion::removeMissionTerminal(), server::zone::objects::region::CityRegion::removeSkillTrainers(), and server::zone::objects::region::CityRegion::subtractFromCityTreasury().
Referenced by server::zone::managers::city::CityManager::collectNonStructureMaintenance(), and deductCityMaintenance().
bool CityManagerImplementation::containsCityName (const String & name)
Definition at line 1098 of file CityManager.cpp.
References _this, and cities.
Referenced by server::zone::managers::city::CityManager::containsCityName().
void CityManagerImplementation::contractCity (CityRegion * city)
Definition at line 1189 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::addMilitiaMember(), server::zone::objects::region::CityRegion::cleanupCitizens(), CLIENT, server::zone::objects::region::CityRegion::destroyAllStructuresForRank(), server::zone::objects::region::CityRegion::getCityHall(), server::zone::objects::region::CityRegion::getCityRank(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::region::CityRegion::getMilitiaMembers(), server::zone::objects::region::CityRegion::getRegionName(), OUTPOST, radiusPerRank, server::zone::objects::region::CityRegion::removeAmenitiesOutsideCity(), server::chat::ChatManager::sendMail(), server::zone::objects::region::CityRegion::setCityRank(), server::zone::objects::region::CityRegion::setRadius(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::contractCity(), and processCityUpdate().
CityRegion * CityManagerImplementation::createCity (CreatureObject * mayor, const String & cityName, float x, float y)
Definition at line 195 of file CityManagerImplementation.cpp.
References cities, server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getZone(), newCityGracePeriod, OUTPOST, and radiusPerRank.
Referenced by server::zone::managers::city::CityManager::createCity().
void CityManagerImplementation::deductCityMaintenance (CityRegion * city)
Definition at line 780 of file CityManagerImplementation.cpp.
References collectCivicStructureMaintenance(), collectNonStructureMaintenance(), server::zone::objects::region::CityRegion::getCityDecoration(), server::zone::objects::region::CityRegion::getCityHall(), server::zone::objects::region::CityRegion::getCityMissionTerminal(), server::zone::objects::region::CityRegion::getCityRank(), server::zone::objects::region::CityRegion::getCitySkillTrainer(), server::zone::objects::region::CityRegion::getCitySpecialization(), getCitySpecialization(), server::zone::objects::region::CityRegion::getCivicStructure(), CitySpecialization::getCost(), server::zone::objects::region::CityRegion::getDecorationCount(), server::zone::objects::region::CityRegion::getMissionTerminalCount(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::region::CityRegion::getSkillTrainerCount(), server::zone::objects::region::CityRegion::getStructuresCount(), server::zone::objects::region::CityRegion::isRegistered(), maintenanceDiscount, and sendMaintenanceEmail().
Referenced by server::zone::managers::city::CityManager::deductCityMaintenance(), and processCityUpdate().
void CityManagerImplementation::depositToCityTreasury (CityRegion * city, CreatureObject * creature, int value)
Definition at line 607 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::addToCityTreasury(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), and server::zone::objects::creature::CreatureObject::subtractCashCredits().
Referenced by server::zone::managers::city::CityManager::depositToCityTreasury().
void CityManagerImplementation::destroyCity (CityRegion * city)
Definition at line 1294 of file CityManagerImplementation.cpp.
References _this, cities, server::zone::objects::region::CityRegion::destroyActiveAreas(), server::zone::objects::region::CityRegion::getCityHall(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::region::CityRegion::getRegionName(), server::zone::objects::region::CityRegion::getZone(), server::chat::ChatManager::sendMail(), server::zone::objects::region::CityRegion::setCityHall(), server::zone::objects::region::CityRegion::setZone(), unregisterCity(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::destroyCity().
void CityManagerImplementation::expandCity (CityRegion * city)
Definition at line 1241 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::addMilitiaMember(), server::zone::objects::region::CityRegion::getCityRank(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::region::CityRegion::getMilitiaMembers(), server::zone::objects::region::CityRegion::getRegionName(), server::zone::objects::region::CityRegion::getZone(), server::zone::Zone::getZoneName(), isCityRankCapped(), METROPOLIS, radiusPerRank, server::chat::ChatManager::sendMail(), server::zone::objects::region::CityRegion::setCityRank(), server::zone::objects::region::CityRegion::setRadius(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::expandCity(), and processCityUpdate().
void CityManagerImplementation::finalize () protected
Definition at line 977 of file CityManager.cpp.
void CityManagerImplementation::fixMayor (CityRegion * city, CreatureObject * mayor)
Definition at line 2224 of file CityManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::region::CityRegion::isCitizen(), server::zone::objects::region::CityRegion::isMayor(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), registerCitizen(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::city::CityManager::fixMayor().
CitySpecialization * CityManagerImplementation::getCitySpecialization (const String & cityspec)
Definition at line 2185 of file CityManagerImplementation.cpp.
References citySpecializations.
Referenced by deductCityMaintenance(), server::zone::managers::city::CityManager::getCitySpecialization(), and sendMaintenanceReport().
CityTax * CityManagerImplementation::getCityTax (int idx)
Definition at line 2193 of file CityManagerImplementation.cpp.
References cityTaxes.
Referenced by server::zone::managers::city::CityManager::getCityTax(), promptSetTax(), and setTax().
int CityManagerImplementation::getTotalCities ()
Definition at line 1124 of file CityManager.cpp.
References cities.
Referenced by server::zone::managers::city::CityManager::getTotalCities().
bool CityManagerImplementation::isCityInRange (Zone * zone, float x, float y)
Definition at line 1952 of file CityManagerImplementation.cpp.
Referenced by server::zone::managers::city::CityManager::isCityInRange().
bool CityManagerImplementation::isCityRankCapped (const String & planetName, byte cityRank)
Definition at line 216 of file CityManagerImplementation.cpp.
References _this, cities, citiesAllowedPerRank, server::zone::objects::region::CityRegion::getCityRank(), server::zone::objects::region::CityRegion::getZone(), and server::zone::Zone::getZoneName().
Referenced by expandCity(), and server::zone::managers::city::CityManager::isCityRankCapped().
void CityManagerImplementation::loadCityRegions ()
Definition at line 147 of file CityManagerImplementation.cpp.
References cities.
Referenced by server::zone::managers::city::CityManager::loadCityRegions().
void CityManagerImplementation::loadLuaConfig ()
Loads configuration settings for cities from the lua for the city manager.
Definition at line 59 of file CityManagerImplementation.cpp.
References citiesAllowedPerRank, citizensPerRank, citySpecializationCooldown, citySpecializations, cityTaxes, cityUpdateInterval, cityVotingCycles, cityVotingCyclesUntilLocked, cityVotingDuration, decorationsPerRank, maintenanceDiscount, newCityGracePeriod, radiusPerRank, CityTaxMap::readObject(), CitySpecializationMap::readObject(), and treasuryWithdrawalCooldown.
Referenced by server::zone::managers::city::CityManager::loadLuaConfig().
void CityManagerImplementation::lock (bool doLock = true) protected
Definition at line 1001 of file CityManager.cpp.
References _this.
Referenced by processCityUpdate(), and sendMaintenanceReport().
void CityManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 1005 of file CityManager.cpp.
References _this.
CityManagerImplementation::operator const CityManager * ()
Definition at line 997 of file CityManager.cpp.
void CityManagerImplementation::processCityUpdate (CityRegion * city)
Definition at line 669 of file CityManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addExperience(), citizensPerRank, cityUpdateInterval, server::zone::objects::region::CityRegion::cleanupCitizens(), server::zone::objects::region::CityRegion::cleanupDecorations(), server::zone::objects::region::CityRegion::cleanupDuplicateCityStructures(), CLIENT, contractCity(), decorationsPerRank, deductCityMaintenance(), expandCity(), server::zone::objects::region::CityRegion::getCitizenCount(), server::zone::objects::region::CityRegion::getCityRank(), server::zone::objects::region::CityRegion::getDecorationCount(), server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::region::CityRegion::getRadius(), server::zone::objects::region::CityRegion::getRegionName(), lock(), METROPOLIS, processIncomeTax(), server::zone::objects::region::CityRegion::rescheduleUpdateEvent(), updateCityVoting(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::processCityUpdate().
void CityManagerImplementation::processIncomeTax (CityRegion * city)
Processes income tax from all citizens
Precondition
city locked
Postcondition
city locked
Definition at line 735 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::getCitizenList(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::region::CityRegion::getIncomeTax(), server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::region::CityRegion::getRegionName(), and zoneServer.
Referenced by processCityUpdate(), and server::zone::managers::city::CityManager::processIncomeTax().
void CityManagerImplementation::promptAddMilitiaMember (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 1437 of file CityManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), SuiWindowType::CITY_ADD_MILITIA, server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::sendMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::promptAddMilitiaMember().
void CityManagerImplementation::promptAdjustTaxes (CityRegion * city, CreatureObject * mayor, SceneObject * terminal = NULL)
Definition at line 1679 of file CityManagerImplementation.cpp.
References SuiWindowType::CITY_ADJUST_TAX, cityTaxes, CityTax::getMenuText(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::promptAdjustTaxes().
void CityManagerImplementation::promptCitySpecialization (CityRegion * city, CreatureObject * mayor, SceneObject * terminal = NULL)
Definition at line 341 of file CityManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::addActiveSession(), server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), SessionFacadeType::CITYSPEC, server::zone::objects::creature::CreatureObject::getCooldownTime(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::chat::StringIdChatParameter::setTO().
Referenced by server::zone::managers::city::CityManager::promptCitySpecialization().
void CityManagerImplementation::promptDepositCityTreasury (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 584 of file CityManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), SuiWindowType::CITY_TREASURY_DEPOSIT, server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::sendMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::promptDepositCityTreasury().
void CityManagerImplementation::promptMayoralVote (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Precondition
city locked, creature locked, sceneObject locked
Postcondition
city locked, creature locked, sceneObject locked
Definition at line 2008 of file CityManagerImplementation.cpp.
References SuiWindowType::CITY_MAYOR_VOTE, server::zone::objects::region::CityRegion::getCandidates(), server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::region::CityRegion::isCitizen(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::promptMayoralVote().
void CityManagerImplementation::promptRegisterCity (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 1563 of file CityManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), SuiWindowType::CITY_REGISTER, server::zone::objects::region::CityRegion::getCityRank(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::player::PlayerObject::hasAbility(), server::zone::objects::region::CityRegion::isMayor(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), TOWNSHIP, and zoneServer.
Referenced by server::zone::managers::city::CityManager::promptRegisterCity().
void CityManagerImplementation::promptSetTax (CityRegion * city, CreatureObject * mayor, int selectedTax, SceneObject * terminal = NULL)
Definition at line 1708 of file CityManagerImplementation.cpp.
References SuiWindowType::CITY_TAX_PROMPT, getCityTax(), CityTax::getInputText(), CityTax::getInputTitle(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::promptSetTax().
void CityManagerImplementation::promptUnregisterCity (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 1595 of file CityManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), SuiWindowType::CITY_REGISTER, server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::region::CityRegion::isMayor(), server::zone::objects::creature::CreatureObject::sendMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::promptUnregisterCity().
void CityManagerImplementation::promptWithdrawCityTreasury (CityRegion * city, CreatureObject * mayor, SceneObject * terminal = NULL)
Definition at line 506 of file CityManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::addActiveSession(), server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), SessionFacadeType::CITYWITHDRAW, server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::region::CityRegion::isMayor(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::city::CityManager::promptWithdrawCityTreasury().
void CityManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 1036 of file CityManager.cpp.
References readObjectMember().
bool CityManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 1055 of file CityManager.cpp.
Referenced by readObject().
void CityManagerImplementation::registerCitizen (CityRegion * city, CreatureObject * creature)
Definition at line 1343 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::addCitizen(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::region::CityRegion::getRegionName(), server::chat::ChatManager::sendMail(), and zoneServer.
Referenced by fixMayor(), and server::zone::managers::city::CityManager::registerCitizen().
void CityManagerImplementation::registerCity (CityRegion * city, CreatureObject * mayor)
Definition at line 1617 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::getCivicStructure(), server::zone::objects::region::CityRegion::getCommercialStructure(), server::zone::objects::region::CityRegion::getCommercialStructuresCount(), server::zone::objects::region::CityRegion::getRegion(), server::zone::objects::region::CityRegion::getStructuresCount(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::registerObjectWithPlanetaryMap(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::SceneObject::setPlanetMapCategory(), and server::zone::objects::region::CityRegion::setRegistered().
Referenced by server::zone::managers::city::CityManager::registerCity().
void CityManagerImplementation::registerForMayoralRace (CityRegion * city, CreatureObject * creature)
Precondition
city locked, creature locked
Postcondition
city locked, creature locked
Definition at line 2094 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::addCandidate(), server::zone::objects::creature::CreatureObject::addCooldown(), server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), server::zone::objects::region::CityRegion::getCitizenList(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::player::PlayerObject::getDeclaredResidence(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::region::CityRegion::isCandidate(), server::zone::objects::region::CityRegion::isCitizen(), server::zone::objects::region::CityRegion::isVotingLocked(), server::zone::objects::region::CityRegion::removeCandidate(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setTO(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::registerForMayoralRace().
void CityManagerImplementation::removeMilitiaMember (CityRegion * city, CreatureObject * mayor, unsigned long long militiaid)
Definition at line 1492 of file CityManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::region::CityRegion::isMayor(), server::zone::objects::region::CityRegion::removeMilitiaMember(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::removeMilitiaMember().
bool CityManagerImplementation::renameCity (CityRegion * city, const String & newName)
Definition at line 1129 of file CityManager.cpp.
References cities, and server::zone::objects::region::CityRegion::getRegionName().
Referenced by server::zone::managers::city::CityManager::renameCity().
void CityManagerImplementation::rlock (bool doLock = true) protected
Definition at line 1009 of file CityManager.cpp.
References _this.
void CityManagerImplementation::runlock (bool doLock = true) protected
Definition at line 1025 of file CityManager.cpp.
References _this.
void CityManagerImplementation::sendChangeCityName (CityRegion * city, CreatureObject * mayor)
Definition at line 2253 of file CityManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), SuiWindowType::CITY_RENAME, server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::player::PlayerObject::hasSuiBoxWindowType(), server::zone::objects::player::PlayerObject::isPrivileged(), server::zone::objects::creature::CreatureObject::sendMessage(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::city::CityManager::sendChangeCityName().
void CityManagerImplementation::sendCitizenshipReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 631 of file CityManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), SuiWindowType::CITY_CITIZEN_REPORT, server::zone::objects::region::CityRegion::getCitizenList(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::player::PlayerObject::hasSuiBoxWindowType(), server::zone::objects::region::CityRegion::isMilitiaMember(), server::zone::objects::creature::CreatureObject::sendMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::sendCitizenshipReport().
void CityManagerImplementation::sendCityAdvancement (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 1526 of file CityManagerImplementation.cpp.
References citizensPerRank, SuiWindowType::CITY_ADVANCEMENT, server::zone::objects::region::CityRegion::getCitizenCount(), server::zone::objects::region::CityRegion::getCityRank(), METROPOLIS, and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::managers::city::CityManager::sendCityAdvancement().
void CityManagerImplementation::sendCityReport (CreatureObject * creature, const String & planetName, byte rank)
Definition at line 243 of file CityManagerImplementation.cpp.
References _this, cities, citiesAllowedPerRank, server::zone::objects::region::CityRegion::getAllStructuresCount(), server::zone::objects::region::CityRegion::getCitizenCount(), server::zone::objects::region::CityRegion::getCityRank(), server::zone::objects::region::CityRegion::getCityTreasury(), server::zone::objects::region::CityRegion::getNextUpdateTime(), server::zone::objects::region::CityRegion::getPositionX(), server::zone::objects::region::CityRegion::getPositionY(), server::zone::objects::region::CityRegion::getRegionName(), server::zone::objects::region::CityRegion::getZone(), server::zone::Zone::getZoneName(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::city::CityManager::sendCityReport().
void CityManagerImplementation::sendMail (CityRegion * city, const String & sender, const UnicodeString & subject, StringIdChatParameter & params, WaypointObject * waypoint)
Definition at line 2200 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::getCitizenList(), server::zone::objects::creature::CreatureObject::getFirstName(), server::chat::ChatManager::sendMail(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::sendMail(), setTax(), updateCityVoting(), and withdrawFromCityTreasury().
void CityManagerImplementation::sendMaintenanceDecayEmail (CityRegion * city, StructureObject * structure, int maintenanceDue)
Definition at line 1025 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::getMayorID(), server::chat::ChatManager::sendMail(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), and zoneServer.
Referenced by collectCivicStructureMaintenance(), and server::zone::managers::city::CityManager::sendMaintenanceDecayEmail().
void CityManagerImplementation::sendMaintenanceDestroyEmail (CityRegion * city, StructureObject * structure)
Definition at line 1049 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::scene::SceneObject::getObjectNameStringIdName(), server::chat::ChatManager::sendMail(), server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), and zoneServer.
Referenced by collectCivicStructureMaintenance(), and server::zone::managers::city::CityManager::sendMaintenanceDestroyEmail().
void CityManagerImplementation::sendMaintenanceEmail (CityRegion * city, int maintenancePaid)
Definition at line 979 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::getMayorID(), server::chat::ChatManager::sendMail(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), and zoneServer.
Referenced by deductCityMaintenance(), and server::zone::managers::city::CityManager::sendMaintenanceEmail().
void CityManagerImplementation::sendMaintenanceRepairEmail (CityRegion * city, StructureObject * structure)
Definition at line 1002 of file CityManagerImplementation.cpp.
References server::zone::objects::region::CityRegion::getMayorID(), server::chat::ChatManager::sendMail(), server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), and zoneServer.
Referenced by collectCivicStructureMaintenance(), and server::zone::managers::city::CityManager::sendMaintenanceRepairEmail().
void CityManagerImplementation::sendMaintenanceReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 1770 of file CityManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), SuiWindowType::CITY_TREASURY_REPORT, server::zone::objects::region::CityRegion::getCityDecoration(), server::zone::objects::region::CityRegion::getCityMissionTerminal(), server::zone::objects::region::CityRegion::getCityRank(), server::zone::objects::region::CityRegion::getCitySkillTrainer(), server::zone::objects::region::CityRegion::getCitySpecialization(), getCitySpecialization(), server::zone::objects::region::CityRegion::getCivicStructure(), CitySpecialization::getCost(), server::zone::objects::region::CityRegion::getDecorationCount(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::region::CityRegion::getMissionTerminalCount(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::region::CityRegion::getSkillTrainerCount(), server::zone::objects::region::CityRegion::getStructuresCount(), server::zone::objects::region::CityRegion::getTimeToUpdate(), server::zone::objects::region::CityRegion::isRegistered(), lock(), maintenanceDiscount, and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::managers::city::CityManager::sendMaintenanceReport().
void CityManagerImplementation::sendManageMilitia (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 1400 of file CityManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), SuiWindowType::CITY_MILITIA, server::zone::objects::region::CityRegion::getMilitiaMembers(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::player::PlayerObject::hasAbility(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::sendManageMilitia().
void CityManagerImplementation::sendMayoralStandings (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Precondition
city locked, creature locked, sceneObject locked
Postcondition
city locked, creature locked, sceneObject locked
Definition at line 1956 of file CityManagerImplementation.cpp.
References SuiWindowType::CITY_MAYOR_STANDINGS, server::zone::objects::region::CityRegion::getCandidates(), server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::sendMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::sendMayoralStandings().
void CityManagerImplementation::sendStatusReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 396 of file CityManagerImplementation.cpp.
References SuiWindowType::CITY_STATUS_REPORT, cityTaxes, server::zone::objects::region::CityRegion::getAllStructuresCount(), server::zone::objects::region::CityRegion::getCitizenCount(), server::zone::objects::region::CityRegion::getCitySpecialization(), server::zone::objects::region::CityRegion::getDecorationCount(), server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::region::CityRegion::getPositionX(), server::zone::objects::region::CityRegion::getPositionY(), server::zone::objects::region::CityRegion::getRadius(), server::zone::objects::region::CityRegion::getRegionName(), CityTax::getStatusPrompt(), server::zone::objects::region::CityRegion::getStructuresCount(), server::zone::objects::region::CityRegion::getTax(), server::zone::objects::creature::CreatureObject::sendMessage(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::sendStatusReport().
void CityManagerImplementation::sendStructureReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 461 of file CityManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), SuiWindowType::CITY_TREASURY_REPORT, server::zone::objects::region::CityRegion::getCityDecoration(), server::zone::objects::region::CityRegion::getCivicStructure(), server::zone::objects::region::CityRegion::getDecorationCount(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::region::CityRegion::getStructuresCount(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::managers::city::CityManager::sendStructureReport().
void CityManagerImplementation::sendTreasuryReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 1509 of file CityManagerImplementation.cpp.
References SuiWindowType::CITY_TREASURY_REPORT, server::zone::objects::region::CityRegion::getCityTreasury(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::managers::city::CityManager::sendTreasuryReport().
void CityManagerImplementation::setTax (CityRegion * city, CreatureObject * mayor, int selectedTax, int value)
Definition at line 1738 of file CityManagerImplementation.cpp.
References getCityTax(), CityTax::getEmailBody(), CityTax::getEmailSubject(), CityTax::getMaxValue(), server::zone::objects::region::CityRegion::getRegionName(), CityTax::getSystemMessage(), sendMail(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), and server::zone::objects::region::CityRegion::setTax().
Referenced by server::zone::managers::city::CityManager::setTax().
void CityManagerImplementation::toggleZoningEnabled (CityRegion * city, CreatureObject * mayor)
Definition at line 1104 of file CityManager.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::region::CityRegion::isMayor(), server::zone::objects::region::CityRegion::isZoningEnabled(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::objects::region::CityRegion::setZoningEnabled().
Referenced by server::zone::managers::city::CityManager::toggleZoningEnabled().
void CityManagerImplementation::unlock (bool doLock = true) protected
Definition at line 1021 of file CityManager.cpp.
References _this.
void CityManagerImplementation::unregisterCitizen (CityRegion * city, CreatureObject * creature, bool inactive = false)
Definition at line 1372 of file CityManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::region::CityRegion::removeCitizen(), server::chat::ChatManager::sendMail(), and zoneServer.
Referenced by server::zone::managers::city::CityManager::unregisterCitizen().
void CityManagerImplementation::unregisterCity (CityRegion * city, CreatureObject * mayor)
Definition at line 1647 of file CityManagerImplementation.cpp.
References server::zone::managers::planet::PlanetManager::dropRegion(), server::zone::objects::region::CityRegion::getCivicStructure(), server::zone::objects::region::CityRegion::getCommercialStructure(), server::zone::objects::region::CityRegion::getCommercialStructuresCount(), server::zone::Zone::getPlanetManager(), server::zone::objects::region::CityRegion::getRegion(), server::zone::objects::region::CityRegion::getRegionName(), server::zone::objects::region::CityRegion::getRegionsCount(), server::zone::objects::region::CityRegion::getStructuresCount(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::region::CityRegion::setRegistered(), and server::zone::Zone::unregisterObjectWithPlanetaryMap().
Referenced by destroyCity(), and server::zone::managers::city::CityManager::unregisterCity().
void CityManagerImplementation::updateCityVoting (CityRegion * city, bool override = false)
Handles the voting of the city, tallys votes, see's who won. Resets the voting process.
Precondition
city locked
Postcondition
city locked
Definition at line 1069 of file CityManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addExperience(), server::zone::objects::region::CityRegion::getCandidates(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::region::CityRegion::getMayorID(), server::zone::objects::region::CityRegion::getRegionName(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::region::CityRegion::isCandidate(), server::zone::objects::region::CityRegion::isCitizen(), server::zone::objects::region::CityRegion::isVotingPeriodOver(), server::zone::objects::region::CityRegion::resetCandidates(), server::zone::objects::region::CityRegion::resetMayoralVotes(), server::zone::objects::region::CityRegion::resetVotingPeriod(), server::chat::ChatManager::sendMail(), sendMail(), server::zone::objects::region::CityRegion::setMayorID(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), server::zone::objects::region::CityRegion::transferCivicStructuresToMayor(), and zoneServer.
Referenced by processCityUpdate(), and server::zone::managers::city::CityManager::updateCityVoting().
bool CityManagerImplementation::validateCityInRange (CreatureObject * creature, Zone * zone, float x, float y)
Definition at line 300 of file CityManagerImplementation.cpp.
References _this, cities, server::zone::objects::region::CityRegion::getPositionX(), server::zone::objects::region::CityRegion::getPositionY(), server::zone::objects::region::CityRegion::getRegionName(), server::zone::objects::region::CityRegion::getZone(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::chat::StringIdChatParameter::setTO().
Referenced by server::zone::managers::city::CityManager::validateCityInRange().
bool CityManagerImplementation::validateCityName (const String & name)
Definition at line 332 of file CityManagerImplementation.cpp.
References _this, and cities.
Referenced by server::zone::managers::city::CityManager::validateCityName().
void CityManagerImplementation::withdrawFromCityTreasury (CityRegion * city, CreatureObject * mayor, int value, const String & reason, SceneObject * terminal = NULL)
string/en/city/city.stf 264 treasury_withdraw_from City Treasury Authority string/en/city/city.stf 265 treasury_withdraw_subject City Treasury Withdrawal string/en/city/city.stf 266 treasury_withdraw_body Attention! Mayor TO has made a withdrawal from the City Treasury. Amount: DI Reason: TT - Treasury Authority
Definition at line 523 of file CityManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::addBankCredits(), server::zone::objects::creature::CreatureObject::addCooldown(), server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), SessionFacadeType::CITYWITHDRAW, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::region::CityRegion::getCityTreasury(), server::zone::objects::region::CityRegion::getMaxWithdrawal(), server::zone::objects::creature::CreatureObject::getPlayerObject(), sendMail(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), server::zone::objects::region::CityRegion::subtractFromCityTreasury(), and treasuryWithdrawalCooldown.
Referenced by server::zone::managers::city::CityManager::withdrawFromCityTreasury().
void CityManagerImplementation::wlock (bool doLock = true) protected
Definition at line 1013 of file CityManager.cpp.
References _this.
void CityManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 1017 of file CityManager.cpp.
References _this.
void CityManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 1065 of file CityManager.cpp.
References writeObjectMembers().
int CityManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 1072 of file CityManager.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class CityManager friend
Definition at line 562 of file CityManager.h.
Member Data Documentation
WeakReference<CityManager*> server::zone::managers::city::CityManagerImplementation::_this
Definition at line 528 of file CityManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), containsCityName(), destroyCity(), isCityRankCapped(), lock(), rlock(), runlock(), sendCityReport(), unlock(), validateCityInRange(), validateCityName(), and wlock().
VectorMap<String, ManagedReference<CityRegion* > > server::zone::managers::city::CityManagerImplementation::cities private
Definition at line 364 of file CityManager.h.
Referenced by CityManagerImplementation(), containsCityName(), createCity(), destroyCity(), getTotalCities(), isCityRankCapped(), loadCityRegions(), renameCity(), sendCityReport(), validateCityInRange(), and validateCityName().
CitiesAllowed CityManagerImplementation::citiesAllowedPerRank static private
Definition at line 338 of file CityManager.h.
Referenced by isCityRankCapped(), loadLuaConfig(), and sendCityReport().
Vector< uint8 > CityManagerImplementation::citizensPerRank static
Definition at line 335 of file CityManager.h.
Referenced by loadLuaConfig(), processCityUpdate(), and sendCityAdvancement().
const byte server::zone::managers::city::CityManagerImplementation::CITY = 4 static
Definition at line 375 of file CityManager.h.
uint64 CityManagerImplementation::citySpecializationCooldown = 0 static
Definition at line 349 of file CityManager.h.
Referenced by changeCitySpecialization(), and loadLuaConfig().
CitySpecializationMap CityManagerImplementation::citySpecializations static private
Definition at line 340 of file CityManager.h.
Referenced by getCitySpecialization(), and loadLuaConfig().
CityTaxMap CityManagerImplementation::cityTaxes static private
Definition at line 342 of file CityManager.h.
Referenced by getCityTax(), loadLuaConfig(), promptAdjustTaxes(), and sendStatusReport().
int CityManagerImplementation::cityUpdateInterval = 0 static
Definition at line 345 of file CityManager.h.
Referenced by loadLuaConfig(), and processCityUpdate().
byte CityManagerImplementation::cityVotingCycles = 0 static
Definition at line 355 of file CityManager.h.
Referenced by loadLuaConfig().
byte CityManagerImplementation::cityVotingCyclesUntilLocked = 0 static
Definition at line 357 of file CityManager.h.
Referenced by loadLuaConfig().
int CityManagerImplementation::cityVotingDuration = 0 static
Definition at line 351 of file CityManager.h.
Referenced by loadLuaConfig().
const byte server::zone::managers::city::CityManagerImplementation::CLIENT = 0 static
Definition at line 367 of file CityManager.h.
Referenced by contractCity(), and processCityUpdate().
int CityManagerImplementation::decorationsPerRank = 10 static
Definition at line 359 of file CityManager.h.
Referenced by canSupportMoreDecorations(), loadLuaConfig(), and processCityUpdate().
float CityManagerImplementation::maintenanceDiscount = 1.0f static
Definition at line 361 of file CityManager.h.
Referenced by deductCityMaintenance(), loadLuaConfig(), and sendMaintenanceReport().
const byte server::zone::managers::city::CityManagerImplementation::METROPOLIS = 5 static
Definition at line 377 of file CityManager.h.
Referenced by expandCity(), processCityUpdate(), and sendCityAdvancement().
int CityManagerImplementation::newCityGracePeriod = 0 static
Definition at line 347 of file CityManager.h.
Referenced by createCity(), and loadLuaConfig().
const byte server::zone::managers::city::CityManagerImplementation::OUTPOST = 1 static
Definition at line 369 of file CityManager.h.
Referenced by contractCity(), and createCity().
Vector< uint16 > CityManagerImplementation::radiusPerRank static
Definition at line 333 of file CityManager.h.
Referenced by contractCity(), createCity(), expandCity(), and loadLuaConfig().
const byte server::zone::managers::city::CityManagerImplementation::TOWNSHIP = 3 static
Definition at line 373 of file CityManager.h.
Referenced by promptRegisterCity().
uint64 CityManagerImplementation::treasuryWithdrawalCooldown = 0 static
Definition at line 353 of file CityManager.h.
Referenced by loadLuaConfig(), and withdrawFromCityTreasury().
const byte server::zone::managers::city::CityManagerImplementation::VILLAGE = 2 static
Definition at line 371 of file CityManager.h.
ManagedReference<ZoneServer* > server::zone::managers::city::CityManagerImplementation::zoneServer private
Definition at line 330 of file CityManager.h.
Referenced by addMilitiaMember(), castMayoralVote(), CityManagerImplementation(), contractCity(), destroyCity(), expandCity(), processCityUpdate(), processIncomeTax(), promptAddMilitiaMember(), promptAdjustTaxes(), promptDepositCityTreasury(), promptMayoralVote(), promptRegisterCity(), promptSetTax(), promptUnregisterCity(), registerCitizen(), registerForMayoralRace(), removeMilitiaMember(), sendCitizenshipReport(), sendMail(), sendMaintenanceDecayEmail(), sendMaintenanceDestroyEmail(), sendMaintenanceEmail(), sendMaintenanceRepairEmail(), sendManageMilitia(), sendMayoralStandings(), sendStatusReport(), unregisterCitizen(), and updateCityVoting().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/city/CityManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/city/CityManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/city/CityManagerImplementation.cpp