Core3: server::zone::objects::tangible::InstrumentObserverImplementation Class Reference
server::zone::objects::tangible::InstrumentObserverImplementation Class Reference
#include <InstrumentObserver.h>
Public Member Functions
InstrumentObserverImplementation (Instrument *instr)
InstrumentObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const InstrumentObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< InstrumentObserver * > _this
Protected Member Functions
virtual ~InstrumentObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< Instrument * > instrument
Friends
class InstrumentObserver
Detailed Description
Definition at line 96 of file InstrumentObserver.h.
Constructor & Destructor Documentation
InstrumentObserverImplementation::InstrumentObserverImplementation (Instrument * instr)
Definition at line 194 of file InstrumentObserver.cpp.
References _initializeImplementation(), and instrument.
InstrumentObserverImplementation::InstrumentObserverImplementation (DummyConstructorParameter * param)
Definition at line 68 of file InstrumentObserver.cpp.
References _initializeImplementation().
InstrumentObserverImplementation::~InstrumentObserverImplementation () protected virtual
Definition at line 73 of file InstrumentObserver.cpp.
Member Function Documentation
DistributedObjectStub * InstrumentObserverImplementation::_getStub ()
Definition at line 93 of file InstrumentObserver.cpp.
References _this.
void InstrumentObserverImplementation::_initializeImplementation () protected
Definition at line 80 of file InstrumentObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by InstrumentObserverImplementation().
void InstrumentObserverImplementation::_serializationHelperMethod () protected
Definition at line 129 of file InstrumentObserver.cpp.
Referenced by _initializeImplementation().
void InstrumentObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 88 of file InstrumentObserver.cpp.
References _this.
Referenced by server::zone::objects::tangible::InstrumentObserver::InstrumentObserver().
void InstrumentObserverImplementation::finalize () protected
Definition at line 77 of file InstrumentObserver.cpp.
void InstrumentObserverImplementation::lock (bool doLock = true) protected
Definition at line 101 of file InstrumentObserver.cpp.
References _this.
void InstrumentObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 105 of file InstrumentObserver.cpp.
References _this.
int InstrumentObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 13 of file InstrumentObserverImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDistanceTo(), instrument, ObserverEventType::OBJECTREMOVEDFROMZONE, and ObserverEventType::POSITIONCHANGED.
Referenced by server::zone::objects::tangible::InstrumentObserver::notifyObserverEvent().
InstrumentObserverImplementation::operator const InstrumentObserver * ()
Definition at line 97 of file InstrumentObserver.cpp.
void InstrumentObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 136 of file InstrumentObserver.cpp.
References readObjectMember().
bool InstrumentObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 155 of file InstrumentObserver.cpp.
References instrument.
Referenced by readObject().
void InstrumentObserverImplementation::rlock (bool doLock = true) protected
Definition at line 109 of file InstrumentObserver.cpp.
References _this.
void InstrumentObserverImplementation::runlock (bool doLock = true) protected
Definition at line 125 of file InstrumentObserver.cpp.
References _this.
void InstrumentObserverImplementation::unlock (bool doLock = true) protected
Definition at line 121 of file InstrumentObserver.cpp.
References _this.
void InstrumentObserverImplementation::wlock (bool doLock = true) protected
Definition at line 113 of file InstrumentObserver.cpp.
References _this.
void InstrumentObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 117 of file InstrumentObserver.cpp.
References _this.
void InstrumentObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 169 of file InstrumentObserver.cpp.
References writeObjectMembers().
int InstrumentObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 176 of file InstrumentObserver.cpp.
References instrument.
Referenced by writeObject().
Friends And Related Function Documentation
friend class InstrumentObserver friend
Definition at line 141 of file InstrumentObserver.h.
Member Data Documentation
WeakReference<InstrumentObserver*> server::zone::objects::tangible::InstrumentObserverImplementation::_this
Definition at line 107 of file InstrumentObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<Instrument* > server::zone::objects::tangible::InstrumentObserverImplementation::instrument protected
Definition at line 98 of file InstrumentObserver.h.
Referenced by InstrumentObserverImplementation(), notifyObserverEvent(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/InstrumentObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/InstrumentObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/InstrumentObserverImplementation.cpp