Core3: server::zone::objects::creature::ai::bt::Behavior Class Reference
server::zone::objects::creature::ai::bt::Behavior Class Reference abstract
#include <Behavior.h>
Public Member Functions
Behavior ()
virtual ~Behavior ()
int tick (AiAgent *actor)
virtual int update (AiAgent *actor)=0
virtual void onInitialize (AiAgent *actor)
virtual void onTerminate (AiAgent *actor, int s)
virtual void observe (AiAgent *actor)
virtual bool canObserve ()
Static Public Attributes
static const int INVALID = 0
static const int SUCCESS = 1
static const int FAILURE = 2
static const int RUNNING = 3
static const int SUSPENDED = 4
Detailed Description
Definition at line 21 of file Behavior.h.
Constructor & Destructor Documentation
server::zone::objects::creature::ai::bt::Behavior::Behavior () inline
Definition at line 24 of file Behavior.h.
virtual server::zone::objects::creature::ai::bt::Behavior::~Behavior () inline virtual
Definition at line 31 of file Behavior.h.
Member Function Documentation
virtual bool server::zone::objects::creature::ai::bt::Behavior::canObserve () inline virtual
Reimplemented in server::zone::objects::creature::ai::bt::SequenceBehavior.
Definition at line 42 of file Behavior.h.
Referenced by server::zone::objects::creature::ai::bt::BehaviorTree::step(), and server::zone::objects::creature::ai::bt::BehaviorTree::stop().
virtual void server::zone::objects::creature::ai::bt::Behavior::observe (AiAgent * actor) inline virtual
Reimplemented in server::zone::objects::creature::ai::bt::SequenceBehavior.
Definition at line 41 of file Behavior.h.
Referenced by server::zone::objects::creature::ai::bt::BehaviorTree::step(), and server::zone::objects::creature::ai::bt::BehaviorTree::stop().
virtual void server::zone::objects::creature::ai::bt::Behavior::onInitialize (AiAgent * actor) inline virtual
Reimplemented in server::zone::objects::creature::ai::bt::SequenceBehavior, and server::zone::objects::creature::ai::bt::LuaBehavior.
Definition at line 39 of file Behavior.h.
References INVALID, and server::zone::objects::creature::AiAgent::setBehaviorStatus().
Referenced by server::zone::objects::creature::ai::bt::SequenceBehavior::onInitialize(), and tick().
virtual void server::zone::objects::creature::ai::bt::Behavior::onTerminate (AiAgent * actor, int s) inline virtual
Reimplemented in server::zone::objects::creature::ai::bt::LuaBehavior.
Definition at line 40 of file Behavior.h.
Referenced by tick().
int server::zone::objects::creature::ai::bt::Behavior::tick (AiAgent * actor) inline
Definition at line 32 of file Behavior.h.
References server::zone::objects::creature::AiAgent::getBehaviorStatus(), INVALID, onInitialize(), onTerminate(), RUNNING, and update().
Referenced by server::zone::objects::creature::ai::bt::BehaviorTree::step().
virtual int server::zone::objects::creature::ai::bt::Behavior::update (AiAgent * actor) pure virtual
Implemented in server::zone::objects::creature::ai::bt::SequenceBehavior, and server::zone::objects::creature::ai::bt::LuaBehavior.
Referenced by tick().
Member Data Documentation
const int server::zone::objects::creature::ai::bt::Behavior::FAILURE = 2 static
Definition at line 28 of file Behavior.h.
Referenced by server::zone::objects::creature::ai::bt::SequenceBehavior::observe(), and server::zone::objects::creature::ai::bt::test::TEST_F().
const int server::zone::objects::creature::ai::bt::Behavior::INVALID = 0 static
Definition at line 26 of file Behavior.h.
Referenced by onInitialize(), and tick().
const int server::zone::objects::creature::ai::bt::Behavior::RUNNING = 3 static
Definition at line 29 of file Behavior.h.
Referenced by server::zone::objects::creature::ai::bt::BehaviorTree::step(), server::zone::objects::creature::ai::bt::BehaviorTree::stop(), server::zone::objects::creature::ai::bt::test::TEST_F(), tick(), and server::zone::objects::creature::ai::bt::SequenceBehavior::update().
const int server::zone::objects::creature::ai::bt::Behavior::SUCCESS = 1 static
Definition at line 27 of file Behavior.h.
Referenced by server::zone::objects::creature::ai::bt::SequenceBehavior::observe(), and server::zone::objects::creature::ai::bt::test::TEST_F().
const int server::zone::objects::creature::ai::bt::Behavior::SUSPENDED = 4 static
Definition at line 30 of file Behavior.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/bt/Behavior.h