Core3: server::zone::ZonePacketHandler Class Reference
server::zone::ZonePacketHandler Class Reference
#include <ZonePacketHandler.h>
Public Member Functions
ZonePacketHandler ()
ZonePacketHandler (const String &s, ZoneProcessServer *serv)
~ZonePacketHandler ()
void registerMessages ()
void registerObjectControllerMessages ()
Task * generateMessageTask (ZoneClientSession *client, Message *pack)
Private Attributes
ManagedReference
< ZoneProcessServer * > processServer
ManagedReference< ZoneServer * > server
MessageCallbackFactory
< MessageCallback
*(ZoneClientSession
*, ZoneProcessServer
*), uint32 > messageCallbackFactory
Detailed Description
Definition at line 60 of file ZonePacketHandler.h.
Constructor & Destructor Documentation
server::zone::ZonePacketHandler::ZonePacketHandler () inline
Definition at line 68 of file ZonePacketHandler.h.
References server.
ZonePacketHandler::ZonePacketHandler (const String & s, ZoneProcessServer * serv)
Definition at line 128 of file ZonePacketHandler.cpp.
References processServer, registerMessages(), registerObjectControllerMessages(), and server.
server::zone::ZonePacketHandler::~ZonePacketHandler () inline
Definition at line 74 of file ZonePacketHandler.h.
Member Function Documentation
Task * ZonePacketHandler::generateMessageTask (ZoneClientSession * client, Message * pack)
Definition at line 223 of file ZonePacketHandler.cpp.
References messageCallbackFactory, server::zone::packets::MessageCallback::parseMessage(), and processServer.
Referenced by server::zone::ZoneServerImplementation::processMessage().
void ZonePacketHandler::registerMessages ()
Definition at line 142 of file ZonePacketHandler.cpp.
References messageCallbackFactory.
Referenced by ZonePacketHandler().
void ZonePacketHandler::registerObjectControllerMessages ()
Definition at line 194 of file ZonePacketHandler.cpp.
References ObjectControllerMessageCallback::objectMessageControllerFactory.
Referenced by ZonePacketHandler().
Member Data Documentation
MessageCallbackFactory<MessageCallback* (ZoneClientSession*, ZoneProcessServer*), uint32> server::zone::ZonePacketHandler::messageCallbackFactory private
Definition at line 65 of file ZonePacketHandler.h.
Referenced by generateMessageTask(), and registerMessages().
ManagedReference<ZoneProcessServer*> server::zone::ZonePacketHandler::processServer private
Definition at line 61 of file ZonePacketHandler.h.
Referenced by generateMessageTask(), and ZonePacketHandler().
ManagedReference<ZoneServer*> server::zone::ZonePacketHandler::server private
Definition at line 63 of file ZonePacketHandler.h.
Referenced by ZonePacketHandler().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZonePacketHandler.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZonePacketHandler.cpp