Core3: server::zone::managers::gcw::GCWManagerAdapter Class Reference
server::zone::managers::gcw::GCWManagerAdapter Class Reference
#include <GCWManager.h>
Public Member Functions
GCWManagerAdapter (GCWManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void loadLuaConfig ()
void initialize ()
void start ()
void registerGCWBase (BuildingObject *building, bool initializeBase)
void unregisterGCWBase (BuildingObject *building)
void performGCWTasks ()
void startVulnerability (BuildingObject *building)
void endVulnerability (BuildingObject *building)
bool isBaseVulnerable (BuildingObject *building)
bool isBandIdentified (BuildingObject *building)
bool isUplinkJammed (BuildingObject *building)
bool isShutdownSequenceStarted (BuildingObject *building)
bool isSecurityTermSliced (BuildingObject *building)
bool isPowerOverloaded (BuildingObject *building)
void resetVulnerability (CreatureObject *creature, BuildingObject *building)
void sendBaseDefenseStatus (CreatureObject *creature, BuildingObject *building)
void doBaseDestruction (StructureObject *structure)
void doBaseDestruction (BuildingObject *building)
void sendResetVerification (CreatureObject *creature, BuildingObject *building)
void sendJamUplinkMenu (CreatureObject *creature, BuildingObject *building, TangibleObject *uplinkTerminal)
void verifyUplinkBand (CreatureObject *creature, BuildingObject *building, int band)
bool canStartSlice (CreatureObject *creature, TangibleObject *terminal)
void sendDNASampleMenu (CreatureObject *creature, BuildingObject *building, TangibleObject *overrideTerminal)
void completeSecuritySlice (CreatureObject *creature, TangibleObject *securityTerminal)
void failSecuritySlice (TangibleObject *securityTerminal)
bool isTerminalDamaged (TangibleObject *securityTerminal)
bool isDNASampled (BuildingObject *building)
void repairTerminal (CreatureObject *creature, TangibleObject *securityTerminal)
void abortShutdownSequence (BuildingObject *building, CreatureObject *creature)
void processDNASample (CreatureObject *creature, TangibleObject *overrideTerminal, const String &sampleChain, int indx)
void handlePowerRegulatorSwitch (CreatureObject *creature, TangibleObject *powerRegulator, int indx)
void sendPowerRegulatorControls (CreatureObject *creature, BuildingObject *building, TangibleObject *powerRegulator)
String getDNAHash (const String &usersample)
bool isPlanetCapped ()
void scheduleBaseDestruction (BuildingObject *building, CreatureObject *creature)
void initializeNewVulnerability (BuildingObject *building)
void notifyInstallationDestruction (InstallationObject *installation)
void notifyTurretDestruction (BuildingObject *building, InstallationObject *turret)
void notifyMinefieldDestruction (BuildingObject *building, InstallationObject *turret)
void sendSelectDeedToDonate (BuildingObject *building, CreatureObject *creature, int turretIndex)
void sendRemoveDefenseConfirmation (BuildingObject *building, CreatureObject *creature, unsigned long long deedOID)
void performDefenseDontation (BuildingObject *building, CreatureObject *creature, unsigned long long deedOID, int turretIndex)
void sendStatus (BuildingObject *building, CreatureObject *creature)
void addMinefield (BuildingObject *building, SceneObject *minefield)
void addTurret (BuildingObject *building, SceneObject *turret)
void addScanner (BuildingObject *building, SceneObject *scanner)
void removeDefense (BuildingObject *building, CreatureObject *creature, unsigned long long deedOID)
bool canUseTerminals (CreatureObject *creature, BuildingObject *building, SceneObject *terminal)
void sendTurretAttackListTo (CreatureObject *creature, SceneObject *turretControlTerminal)
bool canPlaceMoreBases (CreatureObject *creature)
int getImperialBaseCount ()
int getRebelBaseCount ()
float getGCWDiscount (CreatureObject *creature)
void awardSlicingXP (CreatureObject *creature, const String &xpType, int value)
Detailed Description
Definition at line 693 of file GCWManager.h.
Constructor & Destructor Documentation
GCWManagerAdapter::GCWManagerAdapter (GCWManager * impl)
Definition at line 1390 of file GCWManager.cpp.
Member Function Documentation
void GCWManagerAdapter::abortShutdownSequence (BuildingObject * building, CreatureObject * creature)
Definition at line 1787 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::addMinefield (BuildingObject * building, SceneObject * minefield)
Definition at line 1847 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::addScanner (BuildingObject * building, SceneObject * scanner)
Definition at line 1855 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::addTurret (BuildingObject * building, SceneObject * turret)
Definition at line 1851 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::awardSlicingXP (CreatureObject * creature, const String & xpType, int value)
Definition at line 1887 of file GCWManager.cpp.
Referenced by invokeMethod().
bool GCWManagerAdapter::canPlaceMoreBases (CreatureObject * creature)
Definition at line 1871 of file GCWManager.cpp.
Referenced by invokeMethod().
bool GCWManagerAdapter::canStartSlice (CreatureObject * creature, TangibleObject * terminal)
Definition at line 1759 of file GCWManager.cpp.
Referenced by invokeMethod().
bool GCWManagerAdapter::canUseTerminals (CreatureObject * creature, BuildingObject * building, SceneObject * terminal)
Definition at line 1863 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::completeSecuritySlice (CreatureObject * creature, TangibleObject * securityTerminal)
Definition at line 1767 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::doBaseDestruction (StructureObject * structure)
Definition at line 1739 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::doBaseDestruction (BuildingObject * building)
Definition at line 1743 of file GCWManager.cpp.
void GCWManagerAdapter::endVulnerability (BuildingObject * building)
Definition at line 1703 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::failSecuritySlice (TangibleObject * securityTerminal)
Definition at line 1771 of file GCWManager.cpp.
Referenced by invokeMethod().
String GCWManagerAdapter::getDNAHash (const String & usersample)
Definition at line 1803 of file GCWManager.cpp.
Referenced by invokeMethod().
float GCWManagerAdapter::getGCWDiscount (CreatureObject * creature)
Definition at line 1883 of file GCWManager.cpp.
Referenced by invokeMethod().
int GCWManagerAdapter::getImperialBaseCount ()
Definition at line 1875 of file GCWManager.cpp.
Referenced by invokeMethod().
int GCWManagerAdapter::getRebelBaseCount ()
Definition at line 1879 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::handlePowerRegulatorSwitch (CreatureObject * creature, TangibleObject * powerRegulator, int indx)
Definition at line 1795 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::initialize ()
Definition at line 1679 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::initializeNewVulnerability (BuildingObject * building)
Definition at line 1815 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1393 of file GCWManager.cpp.
References abortShutdownSequence(), addMinefield(), addScanner(), addTurret(), awardSlicingXP(), canPlaceMoreBases(), canStartSlice(), canUseTerminals(), completeSecuritySlice(), doBaseDestruction(), endVulnerability(), failSecuritySlice(), getDNAHash(), getGCWDiscount(), getImperialBaseCount(), getRebelBaseCount(), handlePowerRegulatorSwitch(), initialize(), initializeNewVulnerability(), isBandIdentified(), isBaseVulnerable(), isDNASampled(), isPlanetCapped(), isPowerOverloaded(), isSecurityTermSliced(), isShutdownSequenceStarted(), isTerminalDamaged(), isUplinkJammed(), loadLuaConfig(), notifyInstallationDestruction(), notifyMinefieldDestruction(), notifyTurretDestruction(), performDefenseDontation(), performGCWTasks(), processDNASample(), registerGCWBase(), removeDefense(), repairTerminal(), resetVulnerability(), RPC_ABORTSHUTDOWNSEQUENCE__BUILDINGOBJECT_CREATUREOBJECT_, RPC_ADDMINEFIELD__BUILDINGOBJECT_SCENEOBJECT_, RPC_ADDSCANNER__BUILDINGOBJECT_SCENEOBJECT_, RPC_ADDTURRET__BUILDINGOBJECT_SCENEOBJECT_, RPC_AWARDSLICINGXP__CREATUREOBJECT_STRING_INT_, RPC_CANPLACEMOREBASES__CREATUREOBJECT_, RPC_CANSTARTSLICE__CREATUREOBJECT_TANGIBLEOBJECT_, RPC_CANUSETERMINALS__CREATUREOBJECT_BUILDINGOBJECT_SCENEOBJECT_, RPC_COMPLETESECURITYSLICE__CREATUREOBJECT_TANGIBLEOBJECT_, RPC_DOBASEDESTRUCTION__BUILDINGOBJECT_, RPC_DOBASEDESTRUCTION__STRUCTUREOBJECT_, RPC_ENDVULNERABILITY__BUILDINGOBJECT_, RPC_FAILSECURITYSLICE__TANGIBLEOBJECT_, RPC_GETDNAHASH__STRING_, RPC_GETGCWDISCOUNT__CREATUREOBJECT_, RPC_GETIMPERIALBASECOUNT__, RPC_GETREBELBASECOUNT__, RPC_HANDLEPOWERREGULATORSWITCH__CREATUREOBJECT_TANGIBLEOBJECT_INT_, RPC_INITIALIZE__, RPC_INITIALIZENEWVULNERABILITY__BUILDINGOBJECT_, RPC_ISBANDIDENTIFIED__BUILDINGOBJECT_, RPC_ISBASEVULNERABLE__BUILDINGOBJECT_, RPC_ISDNASAMPLED__BUILDINGOBJECT_, RPC_ISPLANETCAPPED__, RPC_ISPOWEROVERLOADED__BUILDINGOBJECT_, RPC_ISSECURITYTERMSLICED__BUILDINGOBJECT_, RPC_ISSHUTDOWNSEQUENCESTARTED__BUILDINGOBJECT_, RPC_ISTERMINALDAMAGED__TANGIBLEOBJECT_, RPC_ISUPLINKJAMMED__BUILDINGOBJECT_, RPC_LOADLUACONFIG__, RPC_NOTIFYINSTALLATIONDESTRUCTION__INSTALLATIONOBJECT_, RPC_NOTIFYMINEFIELDDESTRUCTION__BUILDINGOBJECT_INSTALLATIONOBJECT_, RPC_NOTIFYTURRETDESTRUCTION__BUILDINGOBJECT_INSTALLATIONOBJECT_, RPC_PERFORMDEFENSEDONTATION__BUILDINGOBJECT_CREATUREOBJECT_LONG_INT_, RPC_PERFORMGCWTASKS__, RPC_PROCESSDNASAMPLE__CREATUREOBJECT_TANGIBLEOBJECT_STRING_INT_, RPC_REGISTERGCWBASE__BUILDINGOBJECT_BOOL_, RPC_REMOVEDEFENSE__BUILDINGOBJECT_CREATUREOBJECT_LONG_, RPC_REPAIRTERMINAL__CREATUREOBJECT_TANGIBLEOBJECT_, RPC_RESETVULNERABILITY__CREATUREOBJECT_BUILDINGOBJECT_, RPC_SCHEDULEBASEDESTRUCTION__BUILDINGOBJECT_CREATUREOBJECT_, RPC_SENDBASEDEFENSESTATUS__CREATUREOBJECT_BUILDINGOBJECT_, RPC_SENDDNASAMPLEMENU__CREATUREOBJECT_BUILDINGOBJECT_TANGIBLEOBJECT_, RPC_SENDJAMUPLINKMENU__CREATUREOBJECT_BUILDINGOBJECT_TANGIBLEOBJECT_, RPC_SENDPOWERREGULATORCONTROLS__CREATUREOBJECT_BUILDINGOBJECT_TANGIBLEOBJECT_, RPC_SENDREMOVEDEFENSECONFIRMATION__BUILDINGOBJECT_CREATUREOBJECT_LONG_, RPC_SENDRESETVERIFICATION__CREATUREOBJECT_BUILDINGOBJECT_, RPC_SENDSELECTDEEDTODONATE__BUILDINGOBJECT_CREATUREOBJECT_INT_, RPC_SENDSTATUS__BUILDINGOBJECT_CREATUREOBJECT_, RPC_SENDTURRETATTACKLISTTO__CREATUREOBJECT_SCENEOBJECT_, RPC_START__, RPC_STARTVULNERABILITY__BUILDINGOBJECT_, RPC_UNREGISTERGCWBASE__BUILDINGOBJECT_, RPC_VERIFYUPLINKBAND__CREATUREOBJECT_BUILDINGOBJECT_INT_, scheduleBaseDestruction(), sendBaseDefenseStatus(), sendDNASampleMenu(), sendJamUplinkMenu(), sendPowerRegulatorControls(), sendRemoveDefenseConfirmation(), sendResetVerification(), sendSelectDeedToDonate(), sendStatus(), sendTurretAttackListTo(), start(), startVulnerability(), unregisterGCWBase(), and verifyUplinkBand().
bool GCWManagerAdapter::isBandIdentified (BuildingObject * building)
Definition at line 1711 of file GCWManager.cpp.
Referenced by invokeMethod().
bool GCWManagerAdapter::isBaseVulnerable (BuildingObject * building)
Definition at line 1707 of file GCWManager.cpp.
Referenced by invokeMethod().
bool GCWManagerAdapter::isDNASampled (BuildingObject * building)
Definition at line 1779 of file GCWManager.cpp.
Referenced by invokeMethod().
bool GCWManagerAdapter::isPlanetCapped ()
Definition at line 1807 of file GCWManager.cpp.
Referenced by invokeMethod().
bool GCWManagerAdapter::isPowerOverloaded (BuildingObject * building)
Definition at line 1727 of file GCWManager.cpp.
Referenced by invokeMethod().
bool GCWManagerAdapter::isSecurityTermSliced (BuildingObject * building)
Definition at line 1723 of file GCWManager.cpp.
Referenced by invokeMethod().
bool GCWManagerAdapter::isShutdownSequenceStarted (BuildingObject * building)
Definition at line 1719 of file GCWManager.cpp.
Referenced by invokeMethod().
bool GCWManagerAdapter::isTerminalDamaged (TangibleObject * securityTerminal)
Definition at line 1775 of file GCWManager.cpp.
Referenced by invokeMethod().
bool GCWManagerAdapter::isUplinkJammed (BuildingObject * building)
Definition at line 1715 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::loadLuaConfig ()
Definition at line 1675 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::notifyInstallationDestruction (InstallationObject * installation)
Definition at line 1819 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::notifyMinefieldDestruction (BuildingObject * building, InstallationObject * turret)
Definition at line 1827 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::notifyTurretDestruction (BuildingObject * building, InstallationObject * turret)
Definition at line 1823 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::performDefenseDontation (BuildingObject * building, CreatureObject * creature, unsigned long long deedOID, int turretIndex)
Definition at line 1839 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::performGCWTasks ()
Definition at line 1695 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::processDNASample (CreatureObject * creature, TangibleObject * overrideTerminal, const String & sampleChain, int indx)
Definition at line 1791 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::registerGCWBase (BuildingObject * building, bool initializeBase)
Definition at line 1687 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::removeDefense (BuildingObject * building, CreatureObject * creature, unsigned long long deedOID)
Definition at line 1859 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::repairTerminal (CreatureObject * creature, TangibleObject * securityTerminal)
Definition at line 1783 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::resetVulnerability (CreatureObject * creature, BuildingObject * building)
Definition at line 1731 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::scheduleBaseDestruction (BuildingObject * building, CreatureObject * creature)
Definition at line 1811 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::sendBaseDefenseStatus (CreatureObject * creature, BuildingObject * building)
Definition at line 1735 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::sendDNASampleMenu (CreatureObject * creature, BuildingObject * building, TangibleObject * overrideTerminal)
Definition at line 1763 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::sendJamUplinkMenu (CreatureObject * creature, BuildingObject * building, TangibleObject * uplinkTerminal)
Definition at line 1751 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::sendPowerRegulatorControls (CreatureObject * creature, BuildingObject * building, TangibleObject * powerRegulator)
Definition at line 1799 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::sendRemoveDefenseConfirmation (BuildingObject * building, CreatureObject * creature, unsigned long long deedOID)
Definition at line 1835 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::sendResetVerification (CreatureObject * creature, BuildingObject * building)
Definition at line 1747 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::sendSelectDeedToDonate (BuildingObject * building, CreatureObject * creature, int turretIndex)
Definition at line 1831 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::sendStatus (BuildingObject * building, CreatureObject * creature)
Definition at line 1843 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::sendTurretAttackListTo (CreatureObject * creature, SceneObject * turretControlTerminal)
Definition at line 1867 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::start ()
Definition at line 1683 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::startVulnerability (BuildingObject * building)
Definition at line 1699 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::unregisterGCWBase (BuildingObject * building)
Definition at line 1691 of file GCWManager.cpp.
Referenced by invokeMethod().
void GCWManagerAdapter::verifyUplinkBand (CreatureObject * creature, BuildingObject * building, int band)
Definition at line 1755 of file GCWManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/gcw/GCWManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/gcw/GCWManager.cpp