Core3: ServerDatabase Class Reference
ServerDatabase Class Reference
#include <ServerDatabase.h>
Public Member Functions
ServerDatabase (ConfigManager *configManager)
~ServerDatabase ()
Static Public Member Functions
static Database * instance ()
Static Public Attributes
static const int DEFAULT_SERVERDATABASE_INSTANCES = 8
Static Private Attributes
static Vector< Database * > * databases = NULL
static AtomicInteger currentDB
Detailed Description
Definition at line 52 of file ServerDatabase.h.
Constructor & Destructor Documentation
ServerDatabase::ServerDatabase (ConfigManager * configManager) inline
Definition at line 57 of file ServerDatabase.h.
References databases, DEFAULT_SERVERDATABASE_INSTANCES, server::conf::ConfigManager::getDBHost(), server::conf::ConfigManager::getDBName(), server::conf::ConfigManager::getDBPass(), server::conf::ConfigManager::getDBPort(), and server::conf::ConfigManager::getDBUser().
ServerDatabase::~ServerDatabase () inline
Definition at line 77 of file ServerDatabase.h.
References databases.
Member Function Documentation
static Database* ServerDatabase::instance () inline static
Definition at line 88 of file ServerDatabase.h.
References currentDB, and databases.
Referenced by OnlineZoneClientMap::accountLoggedOut(), server::login::account::AccountManager::AccountManager(), OnlineZoneClientMap::addAccount(), server::zone::managers::player::PlayerManagerImplementation::banAccount(), server::zone::managers::player::PlayerManagerImplementation::banCharacter(), server::zone::managers::player::PlayerManagerImplementation::banFromGalaxy(), server::zone::managers::player::PlayerManagerImplementation::checkExistentNameInDatabase(), server::login::account::AccountManager::createAccount(), server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), SetNameCommand::doQueueCommand(), DatabaseCommand::doSQLQuery(), GalaxyList::GalaxyList(), server::login::account::AccountManager::getAccount(), server::login::LoginPacketHandler::handleDeleteCharacterMessage(), AdminServlet::handleGet(), ServerCore::initialize(), server::zone::ZoneServerImplementation::loadGalaxyName(), server::zone::managers::player::PlayerManagerImplementation::loadNameMap(), server::login::account::AccountManager::loginAccount(), server::zone::managers::object::ObjectManager::onCommitData(), server::zone::managers::object::ObjectManager::onUpdateModifiedObjectsToDatabase(), server::zone::managers::player::PlayerManagerImplementation::PlayerManagerImplementation(), server::zone::managers::player::PlayerManagerImplementation::queryForAccount(), DeleteCharactersTask::run(), ClientIDMessageCallback::run(), server::zone::managers::player::PlayerManagerImplementation::shouldDeleteCharacter(), server::zone::managers::player::PlayerManagerImplementation::unbanAccount(), server::zone::managers::player::PlayerManagerImplementation::unbanCharacter(), server::zone::managers::player::PlayerManagerImplementation::unbanFromGalaxy(), CharacterList::update(), server::login::account::AccountImplementation::updateAccount(), DeleteCharactersTask::updateDeletedCharacters(), server::login::account::AccountImplementation::updateGalaxyBans(), server::login::account::AccountManager::updateHash(), and server::web::WebServer::validateAccountCredentials().
Member Data Documentation
AtomicInteger ServerDatabase::currentDB static private
Definition at line 54 of file ServerDatabase.h.
Referenced by instance().
Vector< Database * > * ServerDatabase::databases = NULL static private
Definition at line 53 of file ServerDatabase.h.
Referenced by instance(), ServerDatabase(), and ~ServerDatabase().
const int ServerDatabase::DEFAULT_SERVERDATABASE_INSTANCES = 8 static
Definition at line 75 of file ServerDatabase.h.
Referenced by ServerDatabase().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/db/ServerDatabase.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/db/ServerDatabase.cpp