Core3: server::zone::objects::player::sessions::StructureSetAccessFeeSessionAdapter Class Reference
server::zone::objects::player::sessions::StructureSetAccessFeeSessionAdapter Class Reference
#include <StructureSetAccessFeeSession.h>
Public Member Functions
StructureSetAccessFeeSessionAdapter (StructureSetAccessFeeSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession ()
int cancelSession ()
int clearSession ()
void promptSetAccessFee ()
void setAccessFee (const int fee)
void promptSetAccessDuration ()
void setAccessDuration (const int duration)
Detailed Description
Definition at line 191 of file StructureSetAccessFeeSession.h.
Constructor & Destructor Documentation
StructureSetAccessFeeSessionAdapter::StructureSetAccessFeeSessionAdapter (StructureSetAccessFeeSession * impl)
Definition at line 370 of file StructureSetAccessFeeSession.cpp.
Member Function Documentation
int StructureSetAccessFeeSessionAdapter::cancelSession ()
Definition at line 421 of file StructureSetAccessFeeSession.cpp.
Referenced by invokeMethod().
int StructureSetAccessFeeSessionAdapter::clearSession ()
Definition at line 425 of file StructureSetAccessFeeSession.cpp.
Referenced by invokeMethod().
int StructureSetAccessFeeSessionAdapter::initializeSession ()
Definition at line 417 of file StructureSetAccessFeeSession.cpp.
Referenced by invokeMethod().
void StructureSetAccessFeeSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 373 of file StructureSetAccessFeeSession.cpp.
References cancelSession(), clearSession(), initializeSession(), promptSetAccessDuration(), promptSetAccessFee(), RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_INITIALIZESESSION__, RPC_PROMPTSETACCESSDURATION__, RPC_PROMPTSETACCESSFEE__, RPC_SETACCESSDURATION__INT_, RPC_SETACCESSFEE__INT_, setAccessDuration(), and setAccessFee().
void StructureSetAccessFeeSessionAdapter::promptSetAccessDuration ()
Definition at line 437 of file StructureSetAccessFeeSession.cpp.
Referenced by invokeMethod().
void StructureSetAccessFeeSessionAdapter::promptSetAccessFee ()
Definition at line 429 of file StructureSetAccessFeeSession.cpp.
Referenced by invokeMethod().
void StructureSetAccessFeeSessionAdapter::setAccessDuration (const int duration)
Definition at line 441 of file StructureSetAccessFeeSession.cpp.
Referenced by invokeMethod().
void StructureSetAccessFeeSessionAdapter::setAccessFee (const int fee)
Definition at line 433 of file StructureSetAccessFeeSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureSetAccessFeeSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureSetAccessFeeSession.cpp