Core3: ForceOfWillCommand Class Reference
ForceOfWillCommand Class Reference
#include <ForceOfWillCommand.h>
Public Member Functions
ForceOfWillCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Private Member Functions
void doDowner (CreatureObject *player, int buffDownerValue, float duration)
Detailed Description
Definition at line 54 of file ForceOfWillCommand.h.
Constructor & Destructor Documentation
ForceOfWillCommand::ForceOfWillCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 77 of file ForceOfWillCommand.h.
Member Function Documentation
void ForceOfWillCommand::doDowner (CreatureObject * player, int buffDownerValue, float duration) inline private
Definition at line 56 of file ForceOfWillCommand.h.
References CreatureAttribute::ACTION, server::zone::objects::creature::CreatureObject::addBuff(), CreatureAttribute::CONSTITUTION, CreatureAttribute::FOCUS, CreatureAttribute::HEALTH, CreatureAttribute::MIND, CreatureAttribute::QUICKNESS, server::zone::objects::creature::buffs::Buff::setAttributeModifier(), BuffType::SKILL, CreatureAttribute::STAMINA, CreatureAttribute::STRENGTH, and CreatureAttribute::WILLPOWER.
Referenced by doQueueCommand().
int ForceOfWillCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 83 of file ForceOfWillCommand.h.
References CreatureAttribute::ACTION, server::zone::objects::creature::CreatureObject::addCooldown(), server::zone::objects::creature::CreatureObject::addShockWounds(), server::zone::objects::creature::CreatureObject::addWounds(), server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), CreatureAttribute::CONSTITUTION, doDowner(), CreatureAttribute::FOCUS, server::zone::objects::scene::SceneObject::getPendingTask(), server::zone::objects::creature::CreatureObject::getSkillMod(), CreatureAttribute::HEALTH, server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), CreatureAttribute::MIND, CreatureAttribute::QUICKNESS, server::zone::objects::scene::SceneObject::removePendingTask(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setPosture(), CreatureAttribute::STAMINA, CreatureAttribute::STRENGTH, CreaturePosture::UPRIGHT, and CreatureAttribute::WILLPOWER.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/ForceOfWillCommand.h