Core3: server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation Class Reference
server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation Class Reference
#include <SuiCharacterBuilderBox.h>
Public Member Functions
SuiCharacterBuilderBoxImplementation (CreatureObject *player, CharacterBuilderMenuNode *root)
SuiCharacterBuilderBoxImplementation (DummyConstructorParameter *param)
BaseMessage * generateMessage ()
CharacterBuilderMenuNode * getCurrentNode ()
void setCurrentNode (CharacterBuilderMenuNode *node)
bool isCharacterBuilderBox ()
operator const SuiCharacterBuilderBox * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::player::sui::listbox::SuiListBoxImplementation
SuiListBoxImplementation (CreatureObject *player, unsigned int windowType=0, unsigned int listBoxType=0)
SuiListBoxImplementation (DummyConstructorParameter *param)
void init ()
void addMenuItem (const String &name, unsigned long long objectID=0)
String getMenuItemName (int index)
void removeAllMenuItems ()
unsigned long long getMenuObjectID (unsigned int idx)
int getMenuSize ()
BaseMessage * generateMessage ()
void setNextBox (unsigned int boxID)
void setPreviousBox (unsigned int boxID)
unsigned long long getNextBox ()
unsigned long long getPreviousBox ()
bool isListBox ()
operator const SuiListBox * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
SuiBoxImplementation (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
SuiBoxImplementation (DummyConstructorParameter *param)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
virtual bool isInputBox ()
virtual bool isMessageBox ()
virtual bool isTransferBox ()
virtual bool isBankTransferBox ()
virtual bool isSlicingBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
operator const SuiBox * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< SuiCharacterBuilderBox * > _this
Public Attributes inherited from server::zone::objects::player::sui::listbox::SuiListBoxImplementation
WeakReference< SuiListBox * > _this
Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
WeakReference< SuiBox * > _this
Protected Member Functions
virtual ~SuiCharacterBuilderBoxImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sui::listbox::SuiListBoxImplementation
virtual ~SuiListBoxImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
virtual ~SuiBoxImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
Reference
< CharacterBuilderMenuNode * > rootNode
Reference
< CharacterBuilderMenuNode * > currentNode
Protected Attributes inherited from server::zone::objects::player::sui::listbox::SuiListBoxImplementation
Vector< ManagedReference
< SuiListBoxMenuItem * > > menuItems
int type
Protected Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
ManagedWeakReference
< CreatureObject * > player
Reference< SuiCallback * > suiCallback
unsigned int boxID
ManagedWeakReference
< SceneObject * > usingObject
String handlerStr
String cancelButtonText
bool cancelButton
String okButtonText
bool okButton
String otherButtonText
bool otherButton
String promptTitle
String promptText
int boxType
unsigned int windowType
float forceCloseDistance
Vector< String > headerSets
Vector< String > optionSets
int hdrOptCount
bool hasGenerated
Friends
class SuiCharacterBuilderBox
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::player::sui::listbox::SuiListBoxImplementation
static const int MSGSELECTED = 0
static const int HANDLESINGLEBUTTON = 1
static const int HANDLETWOBUTTON = 2
static const int HANDLETHREEBUTTON = 3
Detailed Description
Definition at line 94 of file SuiCharacterBuilderBox.h.
Constructor & Destructor Documentation
SuiCharacterBuilderBoxImplementation::SuiCharacterBuilderBoxImplementation (CreatureObject * player, CharacterBuilderMenuNode * root)
Definition at line 209 of file SuiCharacterBuilderBox.cpp.
References _initializeImplementation(), currentNode, rootNode, server::zone::objects::player::sui::SuiBoxImplementation::setPromptText(), and server::zone::objects::player::sui::SuiBoxImplementation::setPromptTitle().
SuiCharacterBuilderBoxImplementation::SuiCharacterBuilderBoxImplementation (DummyConstructorParameter * param)
Definition at line 95 of file SuiCharacterBuilderBox.cpp.
References _initializeImplementation().
SuiCharacterBuilderBoxImplementation::~SuiCharacterBuilderBoxImplementation () protected virtual
Definition at line 100 of file SuiCharacterBuilderBox.cpp.
Member Function Documentation
DistributedObjectStub * SuiCharacterBuilderBoxImplementation::_getStub ()
Definition at line 120 of file SuiCharacterBuilderBox.cpp.
References _this.
void SuiCharacterBuilderBoxImplementation::_initializeImplementation () protected
Definition at line 107 of file SuiCharacterBuilderBox.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SuiCharacterBuilderBoxImplementation().
void SuiCharacterBuilderBoxImplementation::_serializationHelperMethod () protected
Definition at line 156 of file SuiCharacterBuilderBox.cpp.
Referenced by _initializeImplementation().
void SuiCharacterBuilderBoxImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 115 of file SuiCharacterBuilderBox.cpp.
References _this.
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBox::SuiCharacterBuilderBox().
void SuiCharacterBuilderBoxImplementation::finalize () protected
Definition at line 104 of file SuiCharacterBuilderBox.cpp.
BaseMessage * SuiCharacterBuilderBoxImplementation::generateMessage () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 13 of file SuiCharacterBuilderBoxImplementation.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::addHeader(), server::zone::objects::player::sui::SuiBoxImplementation::addSetting(), server::zone::objects::player::sui::SuiBoxImplementation::boxID, server::zone::objects::player::sui::SuiBoxImplementation::cancelButtonText, currentNode, server::zone::objects::player::sui::SuiBoxImplementation::generateBody(), server::zone::objects::player::sui::SuiBoxImplementation::generateFooter(), server::zone::objects::player::sui::SuiBoxImplementation::generateHeader(), CharacterBuilderMenuNode::getDisplayName(), server::zone::objects::player::sui::SuiBoxImplementation::hasGenerated, server::zone::objects::player::sui::SuiBoxImplementation::okButtonText, server::zone::objects::player::sui::SuiBoxImplementation::otherButtonText, server::zone::objects::player::sui::SuiBoxImplementation::promptText, server::zone::objects::player::sui::SuiBoxImplementation::promptTitle, and server::zone::objects::player::sui::SuiBoxImplementation::setHandlerText().
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBox::generateMessage().
CharacterBuilderMenuNode * SuiCharacterBuilderBoxImplementation::getCurrentNode ()
Definition at line 78 of file SuiCharacterBuilderBoxImplementation.cpp.
References currentNode.
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBox::getCurrentNode().
bool SuiCharacterBuilderBoxImplementation::isCharacterBuilderBox () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 223 of file SuiCharacterBuilderBox.cpp.
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBox::isCharacterBuilderBox().
void SuiCharacterBuilderBoxImplementation::lock (bool doLock = true) protected
Definition at line 128 of file SuiCharacterBuilderBox.cpp.
References _this.
void SuiCharacterBuilderBoxImplementation::lock (ManagedObject * obj) protected
Definition at line 132 of file SuiCharacterBuilderBox.cpp.
References _this.
SuiCharacterBuilderBoxImplementation::operator const SuiCharacterBuilderBox * ()
Definition at line 124 of file SuiCharacterBuilderBox.cpp.
void SuiCharacterBuilderBoxImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::listbox::SuiListBoxImplementation.
Definition at line 163 of file SuiCharacterBuilderBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::initializeTransientMembers(), and readObjectMember().
bool SuiCharacterBuilderBoxImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 182 of file SuiCharacterBuilderBox.cpp.
Referenced by readObject().
void SuiCharacterBuilderBoxImplementation::rlock (bool doLock = true) protected
Definition at line 136 of file SuiCharacterBuilderBox.cpp.
References _this.
void SuiCharacterBuilderBoxImplementation::runlock (bool doLock = true) protected
Definition at line 152 of file SuiCharacterBuilderBox.cpp.
References _this.
void SuiCharacterBuilderBoxImplementation::setCurrentNode (CharacterBuilderMenuNode * node)
Definition at line 82 of file SuiCharacterBuilderBoxImplementation.cpp.
References currentNode.
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBox::setCurrentNode().
void SuiCharacterBuilderBoxImplementation::unlock (bool doLock = true) protected
Definition at line 148 of file SuiCharacterBuilderBox.cpp.
References _this.
void SuiCharacterBuilderBoxImplementation::wlock (bool doLock = true) protected
Definition at line 140 of file SuiCharacterBuilderBox.cpp.
References _this.
void SuiCharacterBuilderBoxImplementation::wlock (ManagedObject * obj) protected
Definition at line 144 of file SuiCharacterBuilderBox.cpp.
References _this.
void SuiCharacterBuilderBoxImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::listbox::SuiListBoxImplementation.
Definition at line 192 of file SuiCharacterBuilderBox.cpp.
References writeObjectMembers().
int SuiCharacterBuilderBoxImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 199 of file SuiCharacterBuilderBox.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class SuiCharacterBuilderBox friend
Definition at line 147 of file SuiCharacterBuilderBox.h.
Member Data Documentation
WeakReference<SuiCharacterBuilderBox*> server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::_this
Definition at line 113 of file SuiCharacterBuilderBox.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
Reference<CharacterBuilderMenuNode* > server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::currentNode protected
Definition at line 98 of file SuiCharacterBuilderBox.h.
Referenced by generateMessage(), getCurrentNode(), setCurrentNode(), and SuiCharacterBuilderBoxImplementation().
Reference<CharacterBuilderMenuNode* > server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::rootNode protected
Definition at line 96 of file SuiCharacterBuilderBox.h.
Referenced by SuiCharacterBuilderBoxImplementation().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/characterbuilderbox/SuiCharacterBuilderBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/characterbuilderbox/SuiCharacterBuilderBox.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/characterbuilderbox/SuiCharacterBuilderBoxImplementation.cpp