Core3: RepairVehicleSuiCallback Class Reference
RepairVehicleSuiCallback Class Reference
#include <RepairVehicleSuiCallback.h>
Public Member Functions
RepairVehicleSuiCallback (ZoneServer *server)
void run (CreatureObject *player, SuiBox *suiBox, bool cancelPressed, Vector< UnicodeString > *args)
Public Member Functions inherited from server::zone::objects::player::sui::SuiCallback
SuiCallback (ZoneServer *serv)
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::player::sui::SuiCallback
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 18 of file RepairVehicleSuiCallback.h.
Constructor & Destructor Documentation
RepairVehicleSuiCallback::RepairVehicleSuiCallback (ZoneServer * server) inline
Definition at line 20 of file RepairVehicleSuiCallback.h.
Member Function Documentation
void RepairVehicleSuiCallback::run (CreatureObject * player, SuiBox * suiBox, bool cancelPressed, Vector< UnicodeString > * args) inline virtual
Parameters
player The player that this suibox is assigned to.
suiBox The actual SuiBox object.
cancelPressed Was the cancel button pressed, or was the sui box closed via a similar method. (this might actually be more of a dialogResult type variable)
args A vector of UnicodeStrings containing the arguments passed to the sui box from the client.
Implements server::zone::objects::player::sui::SuiCallback.
Definition at line 24 of file RepairVehicleSuiCallback.h.
References server::zone::objects::creature::VehicleObject::calculateRepairCost(), server::zone::objects::creature::VehicleObject::checkInRangeGarage(), server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::tangible::TangibleObject::getConditionDamage(), server::zone::objects::creature::VehicleObject::healDamage(), server::zone::objects::player::sui::SuiBox::isListBox(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setBankCredits(), and server::chat::StringIdChatParameter::setDI().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/sui/RepairVehicleSuiCallback.h