Core3: FactoryBlueprint Class Reference
FactoryBlueprint Class Reference
#include <FactoryBlueprint.h>
Public Member Functions
FactoryBlueprint ()
FactoryBlueprint (const FactoryBlueprint &blueprint)
~FactoryBlueprint ()
FactoryBlueprint & operator= (const FactoryBlueprint &blueprint)
void addIngredient (SceneObject *ingredient, int quantity, bool isIdentical)
void addConsolidatedEntry (BlueprintEntry *entry)
BlueprintEntry * getConsolidatedEntry (int i)
int getConsolidatedSize ()
BlueprintEntry * getCompleteEntry (int i)
int getCompleteSize ()
void canManufactureItem (String &type, String &displayedName)
void manufactureItem (FactoryObject *factory)
void addSerializableVariables ()
void print ()
Private Attributes
Vector< BlueprintEntry > completeEntries
Vector< BlueprintEntry > consolidatedEntries
Detailed Description
Definition at line 16 of file FactoryBlueprint.h.
Constructor & Destructor Documentation
FactoryBlueprint::FactoryBlueprint ()
Definition at line 12 of file FactoryBlueprint.cpp.
References addSerializableVariables().
FactoryBlueprint::FactoryBlueprint (const FactoryBlueprint & blueprint)
Definition at line 17 of file FactoryBlueprint.cpp.
References addSerializableVariables(), completeEntries, and consolidatedEntries.
FactoryBlueprint::~FactoryBlueprint ()
Definition at line 28 of file FactoryBlueprint.cpp.
Member Function Documentation
void FactoryBlueprint::addConsolidatedEntry (BlueprintEntry * entry)
Definition at line 87 of file FactoryBlueprint.cpp.
References consolidatedEntries, BlueprintEntry::equals(), BlueprintEntry::getQuantity(), and BlueprintEntry::increaseQuantity().
Referenced by addIngredient().
void FactoryBlueprint::addIngredient (SceneObject * ingredient, int quantity, bool isIdentical)
Definition at line 49 of file FactoryBlueprint.cpp.
References addConsolidatedEntry(), completeEntries, server::zone::objects::scene::SceneObject::isResourceSpawn(), BlueprintEntry::setDisplayedName(), BlueprintEntry::setIdentical(), BlueprintEntry::setKey(), BlueprintEntry::setQuantity(), BlueprintEntry::setSerial(), and BlueprintEntry::setType().
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::createFactoryBlueprint().
void FactoryBlueprint::addSerializableVariables ()
Definition at line 134 of file FactoryBlueprint.cpp.
References completeEntries, and consolidatedEntries.
Referenced by FactoryBlueprint().
void FactoryBlueprint::canManufactureItem (String & type, String & displayedName)
Definition at line 112 of file FactoryBlueprint.cpp.
References consolidatedEntries, BlueprintEntry::getDisplayedName(), BlueprintEntry::getType(), and BlueprintEntry::hasEnoughResources().
BlueprintEntry * FactoryBlueprint::getCompleteEntry (int i)
Definition at line 108 of file FactoryBlueprint.cpp.
References completeEntries.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::fillAttributeList().
int FactoryBlueprint::getCompleteSize ()
Definition at line 104 of file FactoryBlueprint.cpp.
References completeEntries.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::fillAttributeList().
BlueprintEntry * FactoryBlueprint::getConsolidatedEntry (int i)
Definition at line 100 of file FactoryBlueprint.cpp.
References consolidatedEntries.
int FactoryBlueprint::getConsolidatedSize ()
Definition at line 83 of file FactoryBlueprint.cpp.
References consolidatedEntries.
void FactoryBlueprint::manufactureItem (FactoryObject * factory)
Definition at line 125 of file FactoryBlueprint.cpp.
References consolidatedEntries, and BlueprintEntry::removeResources().
FactoryBlueprint & FactoryBlueprint::operator= (const FactoryBlueprint & blueprint)
Definition at line 32 of file FactoryBlueprint.cpp.
References completeEntries, and consolidatedEntries.
void FactoryBlueprint::print ()
Definition at line 139 of file FactoryBlueprint.cpp.
References completeEntries, consolidatedEntries, and BlueprintEntry::print().
Member Data Documentation
Vector<BlueprintEntry> FactoryBlueprint::completeEntries private
Definition at line 18 of file FactoryBlueprint.h.
Referenced by addIngredient(), addSerializableVariables(), FactoryBlueprint(), getCompleteEntry(), getCompleteSize(), operator=(), and print().
Vector<BlueprintEntry> FactoryBlueprint::consolidatedEntries private
Definition at line 19 of file FactoryBlueprint.h.
Referenced by addConsolidatedEntry(), addSerializableVariables(), canManufactureItem(), FactoryBlueprint(), getConsolidatedEntry(), getConsolidatedSize(), manufactureItem(), operator=(), and print().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/factoryblueprint/FactoryBlueprint.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/factoryblueprint/FactoryBlueprint.cpp