Core3: server::login::account::Account Class Reference
server::login::account::Account Class Reference
#include <Account.h>
Public Member Functions
Account ()
void setActive (bool act)
void setAccountID (unsigned int accountid)
void setStationID (unsigned int stationid)
void setAdminLevel (unsigned int adminlvl)
void setUsername (const String &usern)
void setBanExpires (unsigned int expires)
void setBanReason (const String &reason)
void setSalt (const String &s)
void setBanAdmin (unsigned int value)
unsigned int getBanAdmin ()
void setTimeCreated (unsigned int seconds)
bool isActive ()
unsigned int getAccountID ()
unsigned int getStationID ()
unsigned int getAdminLevel ()
String getUsername ()
String getSalt ()
unsigned int getTimeCreated ()
void updateFromDatabase ()
void updateAccount ()
void updateCharacters ()
void updateGalaxyBans ()
unsigned int getBanExpires ()
String getBanReason ()
bool isBanned ()
CharacterList * getCharacterList ()
GalaxyBanEntry * getGalaxyBan (unsigned const int galaxy)
CharacterListEntry * getCharacterBan (unsigned const int galaxy, const String &name)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
Account (DummyConstructorParameter *param)
virtual ~Account ()
Friends
class AccountHelper
Detailed Description
Definition at line 56 of file Account.h.
Constructor & Destructor Documentation
Account::Account ()
Definition at line 17 of file Account.cpp.
References server::login::account::AccountImplementation::_setStub().
Account::Account (DummyConstructorParameter * param) protected
Definition at line 24 of file Account.cpp.
Account::~Account () protected virtual
Definition at line 28 of file Account.cpp.
Member Function Documentation
DistributedObjectServant * Account::_getImplementation ()
Definition at line 401 of file Account.cpp.
Referenced by getAccountID(), getAdminLevel(), getBanAdmin(), getBanExpires(), getBanReason(), getCharacterBan(), getCharacterList(), getGalaxyBan(), getSalt(), getStationID(), getTimeCreated(), getUsername(), isActive(), isBanned(), setAccountID(), setActive(), setAdminLevel(), setBanAdmin(), setBanExpires(), setBanReason(), setSalt(), setStationID(), setTimeCreated(), setUsername(), updateAccount(), updateCharacters(), updateFromDatabase(), and updateGalaxyBans().
DistributedObjectServant * Account::_getImplementationForRead ()
Definition at line 407 of file Account.cpp.
void Account::_setImplementation (DistributedObjectServant * servant)
Definition at line 411 of file Account.cpp.
unsigned int Account::getAccountID ()
Definition at line 199 of file Account.cpp.
References _getImplementation(), server::login::account::AccountImplementation::getAccountID(), and RPC_GETACCOUNTID__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::banAccount(), server::zone::managers::player::PlayerManagerImplementation::banCharacter(), server::zone::managers::player::PlayerManagerImplementation::banFromGalaxy(), server::login::packets::LoginClientToken::LoginClientToken(), server::zone::managers::player::PlayerManagerImplementation::unbanAccount(), server::zone::managers::player::PlayerManagerImplementation::unbanCharacter(), and server::zone::managers::player::PlayerManagerImplementation::unbanFromGalaxy().
unsigned int Account::getAdminLevel ()
Definition at line 225 of file Account.cpp.
References _getImplementation(), server::login::account::AccountImplementation::getAdminLevel(), and RPC_GETADMINLEVEL__.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
unsigned int Account::getBanAdmin ()
Definition at line 159 of file Account.cpp.
References _getImplementation(), server::login::account::AccountImplementation::getBanAdmin(), and RPC_GETBANADMIN__.
unsigned int Account::getBanExpires ()
Definition at line 333 of file Account.cpp.
References _getImplementation(), server::login::account::AccountImplementation::getBanExpires(), and RPC_GETBANEXPIRES__.
Referenced by server::login::account::AccountManager::validateAccountCredentials().
String Account::getBanReason ()
Definition at line 346 of file Account.cpp.
References _getImplementation(), server::login::account::AccountImplementation::getBanReason(), and RPC_GETBANREASON__.
Referenced by server::login::account::AccountManager::validateAccountCredentials().
CharacterListEntry * Account::getCharacterBan (unsigned const int galaxy, const String & name)
Definition at line 392 of file Account.cpp.
References _getImplementation(), and server::login::account::AccountImplementation::getCharacterBan().
CharacterList * Account::getCharacterList ()
Definition at line 374 of file Account.cpp.
References _getImplementation(), and server::login::account::AccountImplementation::getCharacterList().
Referenced by server::zone::managers::player::PlayerManagerImplementation::banAccount(), server::zone::managers::player::PlayerManagerImplementation::banFromGalaxy(), and EnumerateCharacterID::EnumerateCharacterID().
GalaxyBanEntry * Account::getGalaxyBan (unsigned const int galaxy)
Definition at line 383 of file Account.cpp.
References _getImplementation(), and server::login::account::AccountImplementation::getGalaxyBan().
Referenced by EnumerateCharacterID::EnumerateCharacterID().
String Account::getSalt ()
Definition at line 253 of file Account.cpp.
References _getImplementation(), server::login::account::AccountImplementation::getSalt(), and RPC_GETSALT__.
Referenced by server::login::account::AccountManager::validateAccountCredentials().
unsigned int Account::getStationID ()
Definition at line 212 of file Account.cpp.
References _getImplementation(), server::login::account::AccountImplementation::getStationID(), and RPC_GETSTATIONID__.
Referenced by server::login::packets::LoginClientToken::LoginClientToken().
unsigned int Account::getTimeCreated ()
Definition at line 268 of file Account.cpp.
References _getImplementation(), server::login::account::AccountImplementation::getTimeCreated(), and RPC_GETTIMECREATED__.
String Account::getUsername ()
Definition at line 238 of file Account.cpp.
References _getImplementation(), server::login::account::AccountImplementation::getUsername(), and RPC_GETUSERNAME__.
Referenced by server::login::packets::LoginClientToken::LoginClientToken().
bool Account::isActive ()
Definition at line 186 of file Account.cpp.
References _getImplementation(), server::login::account::AccountImplementation::isActive(), and RPC_ISACTIVE__.
Referenced by server::login::account::AccountManager::validateAccountCredentials().
bool Account::isBanned ()
Definition at line 361 of file Account.cpp.
References _getImplementation(), server::login::account::AccountImplementation::isBanned(), and RPC_ISBANNED__.
Referenced by server::login::account::AccountManager::validateAccountCredentials().
void Account::setAccountID (unsigned int accountid)
Definition at line 47 of file Account.cpp.
References _getImplementation(), RPC_SETACCOUNTID__INT_, and server::login::account::AccountImplementation::setAccountID().
Referenced by server::login::account::AccountManager::getAccount(), and server::zone::managers::player::PlayerManagerImplementation::queryForAccount().
void Account::setActive (bool act)
Definition at line 33 of file Account.cpp.
References _getImplementation(), RPC_SETACTIVE__BOOL_, and server::login::account::AccountImplementation::setActive().
Referenced by server::login::account::AccountManager::getAccount(), and server::zone::managers::player::PlayerManagerImplementation::queryForAccount().
void Account::setAdminLevel (unsigned int adminlvl)
Definition at line 75 of file Account.cpp.
References _getImplementation(), RPC_SETADMINLEVEL__INT_, and server::login::account::AccountImplementation::setAdminLevel().
Referenced by server::login::account::AccountManager::getAccount(), and server::zone::managers::player::PlayerManagerImplementation::queryForAccount().
void Account::setBanAdmin (unsigned int value)
Definition at line 145 of file Account.cpp.
References _getImplementation(), RPC_SETBANADMIN__INT_, and server::login::account::AccountImplementation::setBanAdmin().
void Account::setBanExpires (unsigned int expires)
Definition at line 103 of file Account.cpp.
References _getImplementation(), RPC_SETBANEXPIRES__INT_, and server::login::account::AccountImplementation::setBanExpires().
void Account::setBanReason (const String & reason)
Definition at line 117 of file Account.cpp.
References _getImplementation(), RPC_SETBANREASON__STRING_, and server::login::account::AccountImplementation::setBanReason().
void Account::setSalt (const String & s)
Definition at line 131 of file Account.cpp.
References _getImplementation(), RPC_SETSALT__STRING_, and server::login::account::AccountImplementation::setSalt().
Referenced by server::login::account::AccountManager::getAccount().
void Account::setStationID (unsigned int stationid)
Definition at line 61 of file Account.cpp.
References _getImplementation(), RPC_SETSTATIONID__INT_, and server::login::account::AccountImplementation::setStationID().
Referenced by server::login::account::AccountManager::getAccount(), and server::zone::managers::player::PlayerManagerImplementation::queryForAccount().
void Account::setTimeCreated (unsigned int seconds)
Definition at line 172 of file Account.cpp.
References _getImplementation(), RPC_SETTIMECREATED__INT_, and server::login::account::AccountImplementation::setTimeCreated().
Referenced by server::login::account::AccountManager::getAccount(), and server::zone::managers::player::PlayerManagerImplementation::queryForAccount().
void Account::setUsername (const String & usern)
Definition at line 89 of file Account.cpp.
References _getImplementation(), RPC_SETUSERNAME__STRING_, and server::login::account::AccountImplementation::setUsername().
Referenced by server::login::account::AccountManager::getAccount(), and server::zone::managers::player::PlayerManagerImplementation::queryForAccount().
void Account::updateAccount ()
Definition at line 294 of file Account.cpp.
References _getImplementation(), RPC_UPDATEACCOUNT__, and server::login::account::AccountImplementation::updateAccount().
void Account::updateCharacters ()
Definition at line 307 of file Account.cpp.
References _getImplementation(), RPC_UPDATECHARACTERS__, and server::login::account::AccountImplementation::updateCharacters().
void Account::updateFromDatabase ()
Definition at line 281 of file Account.cpp.
References _getImplementation(), RPC_UPDATEFROMDATABASE__, and server::login::account::AccountImplementation::updateFromDatabase().
Referenced by server::login::account::AccountManager::getAccount(), and server::zone::managers::player::PlayerManagerImplementation::queryForAccount().
void Account::updateGalaxyBans ()
Definition at line 320 of file Account.cpp.
References _getImplementation(), RPC_UPDATEGALAXYBANS__, and server::login::account::AccountImplementation::updateGalaxyBans().
Friends And Related Function Documentation
friend class AccountHelper friend
Definition at line 126 of file Account.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/account/Account.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/account/Account.cpp