Core3: DamageOverTime Class Reference
DamageOverTime Class Reference
#include <DamageOverTime.h>
Public Member Functions
DamageOverTime ()
DamageOverTime (uint64 tp, uint8 attrib, uint32 str, uint32 dur, float potency, int secondaryStr=0)
DamageOverTime (const DamageOverTime &dot)
DamageOverTime & operator= (const DamageOverTime &dot)
void addSerializableVariables ()
void activate ()
uint32 applyDot (CreatureObject *victim)
uint32 initDot (CreatureObject *victim)
float reduceTick (float reduction)
uint32 doBleedingTick (CreatureObject *victim)
uint32 doFireTick (CreatureObject *victim)
uint32 doPoisonTick (CreatureObject *victim)
uint32 doDiseaseTick (CreatureObject *victim)
void setType (uint64 value)
void setAttribute (uint8 value)
void setStrength (uint32 value)
void setDuration (uint32 seconds)
void setPotency (float percent)
void setExpires (Time time)
void setSecondaryStrength (int str)
uint64 getType ()
uint8 getAttribute ()
uint32 getStrength ()
uint32 getDuration ()
float getPotency ()
bool isActivated ()
bool isPast ()
bool isFuture ()
bool isPresent ()
bool nextTickPast ()
Time getNextTick ()
int getSecondaryStrength ()
Protected Attributes
uint64 type
uint8 attribute
uint32 strength
uint32 duration
float potency
Time expires
Time nextTick
int secondaryStrength
Detailed Description
Definition at line 25 of file DamageOverTime.h.
Constructor & Destructor Documentation
DamageOverTime::DamageOverTime ()
Definition at line 53 of file DamageOverTime.cpp.
References addSerializableVariables(), CreatureState::BLEEDING, CreatureAttribute::HEALTH, setAttribute(), setDuration(), setExpires(), setPotency(), setSecondaryStrength(), setType(), and strength.
DamageOverTime::DamageOverTime (uint64 tp, uint8 attrib, uint32 str, uint32 dur, float potency, int secondaryStr = 0)
Definition at line 64 of file DamageOverTime.cpp.
References activate(), addSerializableVariables(), setAttribute(), setDuration(), setPotency(), setSecondaryStrength(), setType(), and strength.
DamageOverTime::DamageOverTime (const DamageOverTime & dot)
Definition at line 76 of file DamageOverTime.cpp.
References addSerializableVariables(), attribute, duration, expires, nextTick, potency, secondaryStrength, strength, and type.
Member Function Documentation
void DamageOverTime::activate ()
Definition at line 128 of file DamageOverTime.cpp.
References duration, and expires.
Referenced by DamageOverTime().
void DamageOverTime::addSerializableVariables ()
Definition at line 107 of file DamageOverTime.cpp.
References attribute, duration, expires, nextTick, potency, secondaryStrength, strength, and type.
Referenced by DamageOverTime().
uint32 DamageOverTime::applyDot (CreatureObject * victim)
Definition at line 133 of file DamageOverTime.cpp.
References CreatureState::BLEEDING, CreatureState::DISEASED, doBleedingTick(), doDiseaseTick(), doFireTick(), doPoisonTick(), expires, nextTick, CreatureState::ONFIRE, CreatureState::POISONED, and type.
Referenced by DamageOverTimeList::activateDots().
uint32 DamageOverTime::doBleedingTick (CreatureObject * victim) inline
Definition at line 211 of file DamageOverTime.cpp.
References attribute, server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::creature::CreatureObject::hasAttackDelay(), server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::creature::CreatureObject::playEffect(), server::zone::objects::creature::CreatureObject::removeAttackDelay(), and strength.
Referenced by applyDot().
uint32 DamageOverTime::doDiseaseTick (CreatureObject * victim) inline
Definition at line 268 of file DamageOverTime.cpp.
References server::zone::objects::creature::CreatureObject::addShockWounds(), server::zone::objects::creature::CreatureObject::addWounds(), attribute, server::zone::objects::creature::CreatureObject::getShockWounds(), server::zone::objects::creature::CreatureObject::hasAttackDelay(), server::zone::objects::creature::CreatureObject::playEffect(), server::zone::objects::creature::CreatureObject::removeAttackDelay(), and strength.
Referenced by applyDot().
uint32 DamageOverTime::doFireTick (CreatureObject * victim) inline
Definition at line 229 of file DamageOverTime.cpp.
References server::zone::objects::creature::CreatureObject::addShockWounds(), server::zone::objects::creature::CreatureObject::addWounds(), attribute, server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::creature::CreatureObject::getShockWounds(), server::zone::objects::creature::CreatureObject::hasAttackDelay(), server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::creature::CreatureObject::playEffect(), server::zone::objects::creature::CreatureObject::removeAttackDelay(), secondaryStrength, and strength.
Referenced by applyDot().
uint32 DamageOverTime::doPoisonTick (CreatureObject * victim) inline
Definition at line 252 of file DamageOverTime.cpp.
References attribute, server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::creature::CreatureObject::hasAttackDelay(), server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::creature::CreatureObject::playEffect(), server::zone::objects::creature::CreatureObject::removeAttackDelay(), and strength.
Referenced by applyDot().
uint8 DamageOverTime::getAttribute () inline
Definition at line 95 of file DamageOverTime.h.
Referenced by DamageOverTimeList::getStrength().
uint32 DamageOverTime::getDuration () inline
Definition at line 103 of file DamageOverTime.h.
Time DamageOverTime::getNextTick () inline
Definition at line 131 of file DamageOverTime.h.
Referenced by DamageOverTimeList::activateDots(), and DamageOverTimeList::addDot().
float DamageOverTime::getPotency () inline
Definition at line 107 of file DamageOverTime.h.
int DamageOverTime::getSecondaryStrength () inline
Definition at line 135 of file DamageOverTime.h.
uint32 DamageOverTime::getStrength () inline
Definition at line 99 of file DamageOverTime.h.
Referenced by DamageOverTimeList::getStrength().
uint64 DamageOverTime::getType () inline
Definition at line 91 of file DamageOverTime.h.
Referenced by DamageOverTimeList::activateDots(), DamageOverTimeList::clear(), DamageOverTimeList::getStrength(), and DamageOverTimeList::healState().
uint32 DamageOverTime::initDot (CreatureObject * victim)
Definition at line 186 of file DamageOverTime.cpp.
References CreatureState::BLEEDING, CreatureState::DISEASED, server::zone::objects::creature::CreatureObject::getShockWounds(), nextTick, CreatureState::ONFIRE, CreatureState::POISONED, strength, and type.
Referenced by DamageOverTimeList::addDot().
bool DamageOverTime::isActivated () inline
Definition at line 111 of file DamageOverTime.h.
bool DamageOverTime::isFuture () inline
Definition at line 119 of file DamageOverTime.h.
bool DamageOverTime::isPast () inline
Definition at line 115 of file DamageOverTime.h.
Referenced by DamageOverTimeList::activateDots(), DamageOverTimeList::getStrength(), and DamageOverTimeList::healState().
bool DamageOverTime::isPresent () inline
Definition at line 123 of file DamageOverTime.h.
bool DamageOverTime::nextTickPast () inline
Definition at line 127 of file DamageOverTime.h.
Referenced by DamageOverTimeList::activateDots().
DamageOverTime & DamageOverTime::operator= (const DamageOverTime & dot)
Definition at line 90 of file DamageOverTime.cpp.
References attribute, duration, expires, nextTick, potency, secondaryStrength, strength, and type.
float DamageOverTime::reduceTick (float reduction)
Definition at line 287 of file DamageOverTime.cpp.
References expires, and strength.
Referenced by DamageOverTimeList::healState().
void DamageOverTime::setAttribute (uint8 value) inline
Definition at line 67 of file DamageOverTime.h.
Referenced by DamageOverTime().
void DamageOverTime::setDuration (uint32 seconds) inline
Definition at line 75 of file DamageOverTime.h.
Referenced by DamageOverTime().
void DamageOverTime::setExpires (Time time) inline
Definition at line 83 of file DamageOverTime.h.
Referenced by DamageOverTime().
void DamageOverTime::setPotency (float percent) inline
Definition at line 79 of file DamageOverTime.h.
Referenced by DamageOverTime().
void DamageOverTime::setSecondaryStrength (int str) inline
Definition at line 87 of file DamageOverTime.h.
Referenced by DamageOverTime().
void DamageOverTime::setStrength (uint32 value) inline
Definition at line 71 of file DamageOverTime.h.
void DamageOverTime::setType (uint64 value) inline
Definition at line 63 of file DamageOverTime.h.
Referenced by DamageOverTime().
Member Data Documentation
uint8 DamageOverTime::attribute protected
Definition at line 28 of file DamageOverTime.h.
Referenced by addSerializableVariables(), DamageOverTime(), doBleedingTick(), doDiseaseTick(), doFireTick(), doPoisonTick(), and operator=().
uint32 DamageOverTime::duration protected
Definition at line 30 of file DamageOverTime.h.
Referenced by activate(), addSerializableVariables(), DamageOverTime(), and operator=().
Time DamageOverTime::expires protected
Definition at line 33 of file DamageOverTime.h.
Referenced by activate(), addSerializableVariables(), applyDot(), DamageOverTime(), operator=(), and reduceTick().
Time DamageOverTime::nextTick protected
Definition at line 34 of file DamageOverTime.h.
Referenced by addSerializableVariables(), applyDot(), DamageOverTime(), initDot(), and operator=().
float DamageOverTime::potency protected
Definition at line 31 of file DamageOverTime.h.
Referenced by addSerializableVariables(), DamageOverTime(), and operator=().
int DamageOverTime::secondaryStrength protected
Definition at line 35 of file DamageOverTime.h.
Referenced by addSerializableVariables(), DamageOverTime(), doFireTick(), and operator=().
uint32 DamageOverTime::strength protected
Definition at line 29 of file DamageOverTime.h.
Referenced by addSerializableVariables(), DamageOverTime(), doBleedingTick(), doDiseaseTick(), doFireTick(), doPoisonTick(), initDot(), operator=(), and reduceTick().
uint64 DamageOverTime::type protected
Definition at line 27 of file DamageOverTime.h.
Referenced by addSerializableVariables(), applyDot(), DamageOverTime(), initDot(), and operator=().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/damageovertime/DamageOverTime.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/damageovertime/DamageOverTime.cpp