Core3: server::chat::PersistentMessageImplementation Class Reference
server::chat::PersistentMessageImplementation Class Reference
#include <PersistentMessage.h>
Public Member Functions
PersistentMessageImplementation ()
PersistentMessageImplementation (DummyConstructorParameter *param)
virtual void sendTo (CreatureObject *player, bool sendBody=true)
StringIdChatParameterVector * getStringIdParameters ()
WaypointChatParameterVector * getWaypointParameters ()
int getMailID ()
unsigned long long getObjectID ()
String getSenderName ()
unsigned long long getReceiverObjectID ()
byte getStatus ()
int getTimeStamp ()
UnicodeString getBody ()
UnicodeString getSubject ()
void setSenderName (const String &name)
void setReceiverObjectID (unsigned long long oid)
void setStatus (byte stat)
void setTimeStamp (int stamp)
void setBody (const UnicodeString &message)
void setSubject (const UnicodeString &subj)
bool isNew ()
bool isRead ()
bool isUnread ()
void addStringIdParameter (StringIdChatParameter &param)
void addWaypointParameter (WaypointChatParameter &param)
operator const PersistentMessage * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< PersistentMessage * > _this
Static Public Attributes
static const byte NEW = 0x4E
static const byte READ = 0x52
static const byte UNREAD = 0x55
Protected Member Functions
virtual ~PersistentMessageImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
String senderName
UnicodeString subject
UnicodeString body
unsigned int timeStamp
byte status
unsigned long long receiverObjectID
StringIdChatParameterVector stringIdParameters
WaypointChatParameterVector waypointParameters
Friends
class PersistentMessage
Detailed Description
Definition at line 122 of file PersistentMessage.h.
Constructor & Destructor Documentation
PersistentMessageImplementation::PersistentMessageImplementation ()
Definition at line 543 of file PersistentMessage.cpp.
References _initializeImplementation(), NEW, receiverObjectID, status, and timeStamp.
PersistentMessageImplementation::PersistentMessageImplementation (DummyConstructorParameter * param)
Definition at line 333 of file PersistentMessage.cpp.
References _initializeImplementation().
PersistentMessageImplementation::~PersistentMessageImplementation () protected virtual
Definition at line 338 of file PersistentMessage.cpp.
Member Function Documentation
DistributedObjectStub * PersistentMessageImplementation::_getStub ()
Definition at line 358 of file PersistentMessage.cpp.
References _this.
void PersistentMessageImplementation::_initializeImplementation () protected
Definition at line 345 of file PersistentMessage.cpp.
References _serializationHelperMethod(), and _this.
Referenced by PersistentMessageImplementation().
void PersistentMessageImplementation::_serializationHelperMethod () protected
Definition at line 394 of file PersistentMessage.cpp.
Referenced by _initializeImplementation().
void PersistentMessageImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 353 of file PersistentMessage.cpp.
References _this.
Referenced by server::chat::PersistentMessage::PersistentMessage().
void PersistentMessageImplementation::addStringIdParameter (StringIdChatParameter & param)
Definition at line 28 of file PersistentMessageImplementation.cpp.
References stringIdParameters.
Referenced by server::chat::PersistentMessage::addStringIdParameter().
void PersistentMessageImplementation::addWaypointParameter (WaypointChatParameter & param)
Definition at line 32 of file PersistentMessageImplementation.cpp.
References waypointParameters.
Referenced by server::chat::PersistentMessage::addWaypointParameter().
void PersistentMessageImplementation::finalize () protected
Definition at line 342 of file PersistentMessage.cpp.
UnicodeString PersistentMessageImplementation::getBody ()
Definition at line 583 of file PersistentMessage.cpp.
References body.
Referenced by server::chat::PersistentMessage::getBody().
int PersistentMessageImplementation::getMailID ()
Definition at line 12 of file PersistentMessageImplementation.cpp.
References _this.
Referenced by server::chat::PersistentMessage::getMailID().
uint64 PersistentMessageImplementation::getObjectID ()
Definition at line 16 of file PersistentMessageImplementation.cpp.
References _this.
Referenced by server::chat::PersistentMessage::getObjectID().
unsigned long long PersistentMessageImplementation::getReceiverObjectID ()
Definition at line 568 of file PersistentMessage.cpp.
References receiverObjectID.
Referenced by server::chat::PersistentMessage::getReceiverObjectID().
String PersistentMessageImplementation::getSenderName ()
Definition at line 563 of file PersistentMessage.cpp.
References senderName.
Referenced by server::chat::PersistentMessage::getSenderName().
byte PersistentMessageImplementation::getStatus ()
Definition at line 573 of file PersistentMessage.cpp.
References status.
Referenced by server::chat::PersistentMessage::getStatus().
StringIdChatParameterVector * PersistentMessageImplementation::getStringIdParameters ()
Definition at line 553 of file PersistentMessage.cpp.
References stringIdParameters.
Referenced by server::chat::PersistentMessage::getStringIdParameters().
UnicodeString PersistentMessageImplementation::getSubject ()
Definition at line 588 of file PersistentMessage.cpp.
References subject.
Referenced by server::chat::PersistentMessage::getSubject().
int PersistentMessageImplementation::getTimeStamp ()
Definition at line 578 of file PersistentMessage.cpp.
References timeStamp.
Referenced by server::chat::PersistentMessage::getTimeStamp().
WaypointChatParameterVector * PersistentMessageImplementation::getWaypointParameters ()
Definition at line 558 of file PersistentMessage.cpp.
References waypointParameters.
Referenced by server::chat::PersistentMessage::getWaypointParameters().
bool PersistentMessageImplementation::isNew ()
Definition at line 623 of file PersistentMessage.cpp.
References NEW, and status.
Referenced by server::chat::PersistentMessage::isNew().
bool PersistentMessageImplementation::isRead ()
Definition at line 628 of file PersistentMessage.cpp.
References READ, and status.
Referenced by server::chat::PersistentMessage::isRead().
bool PersistentMessageImplementation::isUnread ()
Definition at line 633 of file PersistentMessage.cpp.
References status, and UNREAD.
Referenced by server::chat::PersistentMessage::isUnread().
void PersistentMessageImplementation::lock (bool doLock = true) protected
Definition at line 366 of file PersistentMessage.cpp.
References _this.
void PersistentMessageImplementation::lock (ManagedObject * obj) protected
Definition at line 370 of file PersistentMessage.cpp.
References _this.
PersistentMessageImplementation::operator const PersistentMessage * ()
Definition at line 362 of file PersistentMessage.cpp.
void PersistentMessageImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 401 of file PersistentMessage.cpp.
References readObjectMember().
bool PersistentMessageImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 420 of file PersistentMessage.cpp.
References body, receiverObjectID, senderName, status, stringIdParameters, subject, timeStamp, and waypointParameters.
Referenced by readObject().
void PersistentMessageImplementation::rlock (bool doLock = true) protected
Definition at line 374 of file PersistentMessage.cpp.
References _this.
void PersistentMessageImplementation::runlock (bool doLock = true) protected
Definition at line 390 of file PersistentMessage.cpp.
References _this.
void PersistentMessageImplementation::sendTo (CreatureObject * player, bool sendBody = true) virtual
Definition at line 20 of file PersistentMessageImplementation.cpp.
References _this, and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::chat::PersistentMessage::sendTo().
void PersistentMessageImplementation::setBody (const UnicodeString & message)
Definition at line 613 of file PersistentMessage.cpp.
References body.
Referenced by server::chat::PersistentMessage::setBody().
void PersistentMessageImplementation::setReceiverObjectID (unsigned long long oid)
Definition at line 598 of file PersistentMessage.cpp.
References receiverObjectID.
Referenced by server::chat::PersistentMessage::setReceiverObjectID().
void PersistentMessageImplementation::setSenderName (const String & name)
Definition at line 593 of file PersistentMessage.cpp.
References senderName.
Referenced by server::chat::PersistentMessage::setSenderName().
void PersistentMessageImplementation::setStatus (byte stat)
Definition at line 603 of file PersistentMessage.cpp.
References status.
Referenced by server::chat::PersistentMessage::setStatus().
void PersistentMessageImplementation::setSubject (const UnicodeString & subj)
Definition at line 618 of file PersistentMessage.cpp.
References subject.
Referenced by server::chat::PersistentMessage::setSubject().
void PersistentMessageImplementation::setTimeStamp (int stamp)
Definition at line 608 of file PersistentMessage.cpp.
References timeStamp.
Referenced by server::chat::PersistentMessage::setTimeStamp().
void PersistentMessageImplementation::unlock (bool doLock = true) protected
Definition at line 386 of file PersistentMessage.cpp.
References _this.
void PersistentMessageImplementation::wlock (bool doLock = true) protected
Definition at line 378 of file PersistentMessage.cpp.
References _this.
void PersistentMessageImplementation::wlock (ManagedObject * obj) protected
Definition at line 382 of file PersistentMessage.cpp.
References _this.
void PersistentMessageImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 462 of file PersistentMessage.cpp.
References writeObjectMembers().
int PersistentMessageImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 469 of file PersistentMessage.cpp.
References body, receiverObjectID, senderName, status, stringIdParameters, subject, timeStamp, and waypointParameters.
Referenced by writeObject().
Friends And Related Function Documentation
friend class PersistentMessage friend
Definition at line 229 of file PersistentMessage.h.
Member Data Documentation
WeakReference<PersistentMessage*> server::chat::PersistentMessageImplementation::_this
Definition at line 195 of file PersistentMessage.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), getMailID(), getObjectID(), lock(), rlock(), runlock(), sendTo(), unlock(), and wlock().
UnicodeString server::chat::PersistentMessageImplementation::body protected
Definition at line 128 of file PersistentMessage.h.
Referenced by getBody(), readObjectMember(), setBody(), and writeObjectMembers().
const byte server::chat::PersistentMessageImplementation::NEW = 0x4E static
Definition at line 141 of file PersistentMessage.h.
Referenced by isNew(), and PersistentMessageImplementation().
const byte server::chat::PersistentMessageImplementation::READ = 0x52 static
Definition at line 143 of file PersistentMessage.h.
Referenced by isRead().
unsigned long long server::chat::PersistentMessageImplementation::receiverObjectID protected
Definition at line 134 of file PersistentMessage.h.
Referenced by getReceiverObjectID(), PersistentMessageImplementation(), readObjectMember(), setReceiverObjectID(), and writeObjectMembers().
String server::chat::PersistentMessageImplementation::senderName protected
Definition at line 124 of file PersistentMessage.h.
Referenced by getSenderName(), readObjectMember(), setSenderName(), and writeObjectMembers().
byte server::chat::PersistentMessageImplementation::status protected
Definition at line 132 of file PersistentMessage.h.
Referenced by getStatus(), isNew(), isRead(), isUnread(), PersistentMessageImplementation(), readObjectMember(), setStatus(), and writeObjectMembers().
StringIdChatParameterVector server::chat::PersistentMessageImplementation::stringIdParameters protected
Definition at line 136 of file PersistentMessage.h.
Referenced by addStringIdParameter(), getStringIdParameters(), readObjectMember(), and writeObjectMembers().
UnicodeString server::chat::PersistentMessageImplementation::subject protected
Definition at line 126 of file PersistentMessage.h.
Referenced by getSubject(), readObjectMember(), setSubject(), and writeObjectMembers().
unsigned int server::chat::PersistentMessageImplementation::timeStamp protected
Definition at line 130 of file PersistentMessage.h.
Referenced by getTimeStamp(), PersistentMessageImplementation(), readObjectMember(), setTimeStamp(), and writeObjectMembers().
const byte server::chat::PersistentMessageImplementation::UNREAD = 0x55 static
Definition at line 145 of file PersistentMessage.h.
Referenced by isUnread().
WaypointChatParameterVector server::chat::PersistentMessageImplementation::waypointParameters protected
Definition at line 138 of file PersistentMessage.h.
Referenced by addWaypointParameter(), getWaypointParameters(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/PersistentMessage.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/PersistentMessage.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/PersistentMessageImplementation.cpp