Core3: TendCommand Class Reference
TendCommand Class Reference
#include <TendCommand.h>
Public Member Functions
TendCommand (const String &name, ZoneProcessServer *server)
void doAnimations (CreatureObject *creature, CreatureObject *creatureTarget)
void sendHealMessage (CreatureObject *creature, CreatureObject *creatureTarget, int healthDamage, int actionDamage)
void sendWoundMessage (CreatureObject *creature, CreatureObject *creatureTarget, int poolAffected, int woundsHealed)
void awardXp (CreatureObject *creature, const String &type, int power)
uint8 findAttribute (CreatureObject *creature, uint8 startAttribute=0)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Public Member Functions inherited from server::zone::objects::creature::commands::QueueCommand
QueueCommand (const String &skillname, ZoneProcessServer *serv)
virtual ~QueueCommand ()
bool checkInvalidLocomotions (CreatureObject *creature)
void onStateFail (CreatureObject *creature, uint32 actioncntr)
void onLocomotionFail (CreatureObject *creature, uint32 actioncntr)
virtual String getSyntax () const
virtual void onFail (uint32 actioncntr, CreatureObject *creature, uint32 errorNumber)
virtual void onComplete (uint32 actioncntr, CreatureObject *creature, float commandDuration)
void setInvalidLocomotions (const String &lStr)
void addInvalidLocomotion (int l)
bool checkStateMask (CreatureObject *creature)
virtual float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
void setStateMask (uint64 mask)
void setDefaultTime (float time)
void setTargetType (int num)
void setDisabled (bool state)
void setDisabled (int state)
void setAddToCombatQueue (bool state)
void setAddToCombatQueue (int state)
void setCommandGroup (int val)
void setMaxRange (float r)
void setCharacterAbility (const String &ability)
void setDefaultPriority (const String &priority)
void setDefaultPriority (const int priority)
uint64 getStateMask ()
bool requiresAdmin ()
int getTargetType ()
uint32 getNameCRC ()
float getMaxRange ()
String & getQueueCommandName ()
String & getCharacterAbility ()
float getDefaultTime ()
int getDefaultPriority ()
bool isDisabled ()
bool addToCombatQueue ()
virtual bool isCombatCommand ()
int getSkillModSize ()
int getSkillMod (int index, String &skillMod)
int getCommandGroup ()
void addSkillMod (const String &skillMod, const int value)
bool isWearingArmor (CreatureObject *creo)
virtual void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Protected Attributes
int mindCost
int mindWoundCost
int healthHealed
int actionHealed
int mindHealed
uint8 woundPool
int woundsHealed
bool tendDamage
bool tendWound
float speed
float range
String effectName
Protected Attributes inherited from server::zone::objects::creature::commands::QueueCommand
ZoneProcessServer * server
String name
uint32 nameCRC
uint64 stateMask
Vector< int > invalidLocomotion
int targetType
int maxRangeToTarget
bool disabled
bool addToQueue
bool admin
uint32 cooldown
float defaultTime
String characterAbility
int defaultPriority
VectorMap< String, int > skillMods
int commandGroup
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::creature::commands::QueueCommand
static const int IMMEDIATE = 0
static const int FRONT = 1
static const int NORMAL = 2
static const int SUCCESS = 0
static const int GENERALERROR = 1
static const int INVALIDLOCOMOTION = 2
static const int INVALIDSTATE = 3
static const int INVALIDTARGET = 4
static const int INVALIDWEAPON = 5
static const int TOOFAR = 6
static const int INSUFFICIENTHAM = 7
static const int INVALIDPARAMETERS = 8
static const int NOPRONE = 9
static const int NOKNEELING = 10
static const int INSUFFICIENTPERMISSION = 11
static const int NOJEDIARMOR = 12
static const int INVALIDSYNTAX = 13
Detailed Description
Definition at line 23 of file TendCommand.h.
Constructor & Destructor Documentation
TendCommand::TendCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 43 of file TendCommand.h.
References actionHealed, healthHealed, mindCost, mindHealed, mindWoundCost, range, speed, tendDamage, tendWound, woundPool, and woundsHealed.
Member Function Documentation
void TendCommand::awardXp (CreatureObject * creature, const String & type, int power) inline
Definition at line 139 of file TendCommand.h.
References server::zone::managers::player::PlayerManager::awardExperience(), server::zone::ZoneServer::getPlayerManager(), server::zone::ZoneProcessServer::getZoneServer(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::creature::commands::QueueCommand::server.
Referenced by doQueueCommand().
void TendCommand::doAnimations (CreatureObject * creature, CreatureObject * creatureTarget) inline
Definition at line 64 of file TendCommand.h.
References server::zone::objects::creature::CreatureObject::doAnimation(), effectName, and server::zone::objects::creature::CreatureObject::playEffect().
Referenced by doQueueCommand().
int TendCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline virtual
Reimplemented from server::zone::objects::creature::commands::QueueCommand.
Definition at line 165 of file TendCommand.h.
References CreatureAttribute::ACTION, server::zone::objects::creature::CreatureObject::addShockWounds(), server::zone::objects::creature::CreatureObject::addWounds(), awardXp(), server::zone::objects::creature::CreatureObject::calculateBFRatio(), server::zone::objects::creature::commands::QueueCommand::checkInvalidLocomotions(), server::zone::objects::creature::commands::QueueCommand::checkStateMask(), doAnimations(), findAttribute(), CreatureAttribute::FOCUS, server::zone::objects::creature::commands::QueueCommand::GENERALERROR, server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getHAM(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::getWounds(), server::zone::ZoneProcessServer::getZoneServer(), server::zone::objects::creature::CreatureObject::hasDamage(), server::zone::objects::creature::CreatureObject::healDamage(), CreatureAttribute::HEALTH, server::zone::objects::creature::CreatureObject::healWound(), server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::creature::commands::QueueCommand::INVALIDLOCOMOTION, server::zone::objects::creature::commands::QueueCommand::INVALIDSTATE, server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::tangible::TangibleObject::isAttackableBy(), server::zone::objects::creature::CreatureObject::isAttackableBy(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isHealableBy(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::CreatureObject::isMeditating(), server::zone::objects::creature::CreatureObject::isMounted(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isProne(), server::zone::objects::creature::CreatureObject::isRidingCreature(), CreatureAttribute::MIND, mindCost, mindWoundCost, range, server::zone::managers::player::PlayerManager::sendBattleFatigueMessage(), sendHealMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), sendWoundMessage(), server::zone::objects::creature::commands::QueueCommand::server, server::chat::StringIdChatParameter::setTT(), server::zone::objects::creature::commands::QueueCommand::SUCCESS, tendDamage, tendWound, server::zone::objects::creature::commands::QueueCommand::TOOFAR, CreatureAttribute::UNKNOWN, and CreatureAttribute::WILLPOWER.
uint8 TendCommand::findAttribute (CreatureObject * creature, uint8 startAttribute = 0) inline
Definition at line 154 of file TendCommand.h.
References server::zone::objects::creature::CreatureObject::getWounds(), and CreatureAttribute::UNKNOWN.
Referenced by doQueueCommand().
void TendCommand::sendHealMessage (CreatureObject * creature, CreatureObject * creatureTarget, int healthDamage, int actionDamage) inline
Definition at line 74 of file TendCommand.h.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
void TendCommand::sendWoundMessage (CreatureObject * creature, CreatureObject * creatureTarget, int poolAffected, int woundsHealed) inline
Definition at line 107 of file TendCommand.h.
References server::zone::objects::creature::CreatureObject::getFirstName(), CreatureAttribute::getName(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
Member Data Documentation
int TendCommand::actionHealed protected
Definition at line 29 of file TendCommand.h.
Referenced by TendCommand(), and TendDamageCommand::TendDamageCommand().
String TendCommand::effectName protected
Definition at line 40 of file TendCommand.h.
Referenced by doAnimations(), TendDamageCommand::TendDamageCommand(), and TendWoundCommand::TendWoundCommand().
int TendCommand::healthHealed protected
Definition at line 28 of file TendCommand.h.
Referenced by TendCommand(), and TendDamageCommand::TendDamageCommand().
int TendCommand::mindCost protected
Definition at line 25 of file TendCommand.h.
Referenced by doQueueCommand(), TendCommand(), TendDamageCommand::TendDamageCommand(), and TendWoundCommand::TendWoundCommand().
int TendCommand::mindHealed protected
Definition at line 30 of file TendCommand.h.
Referenced by TendCommand().
int TendCommand::mindWoundCost protected
Definition at line 26 of file TendCommand.h.
Referenced by doQueueCommand(), TendCommand(), TendDamageCommand::TendDamageCommand(), and TendWoundCommand::TendWoundCommand().
float TendCommand::range protected
Definition at line 39 of file TendCommand.h.
Referenced by doQueueCommand(), TendCommand(), TendDamageCommand::TendDamageCommand(), and TendWoundCommand::TendWoundCommand().
float TendCommand::speed protected
Definition at line 38 of file TendCommand.h.
Referenced by TendCommand().
bool TendCommand::tendDamage protected
Definition at line 35 of file TendCommand.h.
Referenced by doQueueCommand(), TendCommand(), and TendDamageCommand::TendDamageCommand().
bool TendCommand::tendWound protected
Definition at line 36 of file TendCommand.h.
Referenced by doQueueCommand(), TendCommand(), and TendWoundCommand::TendWoundCommand().
uint8 TendCommand::woundPool protected
Definition at line 32 of file TendCommand.h.
Referenced by TendCommand(), and TendWoundCommand::TendWoundCommand().
int TendCommand::woundsHealed protected
Definition at line 33 of file TendCommand.h.
Referenced by TendCommand(), and TendWoundCommand::TendWoundCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/TendCommand.h