Core3: server::chat::ChatManagerAdapter Class Reference
server::chat::ChatManagerAdapter Class Reference
#include <ChatManager.h>
Public Member Functions
ChatManagerAdapter (ChatManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initiateRooms ()
void initiatePlanetRooms ()
void destroyRooms ()
ChatRoom * createRoom (const String &roomName, ChatRoom *parent)
void addRoom (ChatRoom *channel)
void removeRoom (ChatRoom *channel)
void populateRoomListMessage (ChatRoom *channel, ChatRoomList *msg)
void sendRoomList (CreatureObject *player)
void addPlayer (CreatureObject *player)
CreatureObject * getPlayer (const String &name)
CreatureObject * removePlayer (const String &name)
void broadcastMessage (BaseMessage *message)
void broadcastMessage (CreatureObject *player, const UnicodeString &message, unsigned long long target, unsigned int moodid, unsigned int mood2)
void handleSpatialChatInternalMessage (CreatureObject *player, const UnicodeString &args)
void handleGroupChat (CreatureObject *player, const UnicodeString &message)
void handleGuildChat (CreatureObject *player, const UnicodeString &message)
void handlePlanetChat (CreatureObject *player, const UnicodeString &message)
ChatRoom * createRoomByFullPath (const String &path)
ChatRoom * getChatRoomByFullPath (const String &path)
ChatRoom * getChatRoomByGamePath (ChatRoom *game, const String &path)
void handleChatRoomMessage (CreatureObject *sender, const UnicodeString &message, unsigned int roomID, unsigned int counter)
void handleChatEnterRoomById (CreatureObject *player, unsigned int counter, unsigned int roomID)
void handleSocialInternalMessage (CreatureObject *sender, const UnicodeString &arguments)
void destroyRoom (ChatRoom *room)
ChatRoom * createGroupRoom (unsigned long long groupID, CreatureObject *creator)
void loadMail (CreatureObject *player)
void sendMail (const String &sendername, const UnicodeString &header, const UnicodeString &body, const String &name)
void handleRequestPersistentMsg (CreatureObject *player, unsigned int mailID)
void deletePersistentMessage (CreatureObject *player, unsigned int mailID)
void broadcastGalaxy (CreatureObject *player, const String &message)
void broadcastGalaxy (const String &message, const String &faction)
void setPlayerManager (PlayerManager *manager)
ChatRoom * getChatRoom (unsigned int id)
ChatRoom * getGameRoom (const String &game)
unsigned int getNextRoomID ()
int getPlayerCount ()
ChatRoom * getGuildRoom ()
ChatRoom * getGroupRoom ()
Detailed Description
Definition at line 473 of file ChatManager.h.
Constructor & Destructor Documentation
ChatManagerAdapter::ChatManagerAdapter (ChatManager * impl)
Definition at line 926 of file ChatManager.cpp.
Member Function Documentation
void ChatManagerAdapter::addPlayer (CreatureObject * player)
Definition at line 1186 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::addRoom (ChatRoom * channel)
Definition at line 1170 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::broadcastGalaxy (CreatureObject * player, const String & message)
Definition at line 1270 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::broadcastGalaxy (const String & message, const String & faction)
Definition at line 1274 of file ChatManager.cpp.
void ChatManagerAdapter::broadcastMessage (BaseMessage * message)
Definition at line 1198 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::broadcastMessage (CreatureObject * player, const UnicodeString & message, unsigned long long target, unsigned int moodid, unsigned int mood2)
Definition at line 1202 of file ChatManager.cpp.
ChatRoom * ChatManagerAdapter::createGroupRoom (unsigned long long groupID, CreatureObject * creator)
Definition at line 1250 of file ChatManager.cpp.
Referenced by invokeMethod().
ChatRoom * ChatManagerAdapter::createRoom (const String & roomName, ChatRoom * parent)
Definition at line 1166 of file ChatManager.cpp.
Referenced by invokeMethod().
ChatRoom * ChatManagerAdapter::createRoomByFullPath (const String & path)
Definition at line 1222 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::deletePersistentMessage (CreatureObject * player, unsigned int mailID)
Definition at line 1266 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::destroyRoom (ChatRoom * room)
Definition at line 1246 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::destroyRooms ()
Definition at line 1162 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::finalize ()
Definition at line 1150 of file ChatManager.cpp.
Referenced by invokeMethod().
ChatRoom * ChatManagerAdapter::getChatRoom (unsigned int id)
Definition at line 1282 of file ChatManager.cpp.
Referenced by invokeMethod().
ChatRoom * ChatManagerAdapter::getChatRoomByFullPath (const String & path)
Definition at line 1226 of file ChatManager.cpp.
Referenced by invokeMethod().
ChatRoom * ChatManagerAdapter::getChatRoomByGamePath (ChatRoom * game, const String & path)
Definition at line 1230 of file ChatManager.cpp.
Referenced by invokeMethod().
ChatRoom * ChatManagerAdapter::getGameRoom (const String & game)
Definition at line 1286 of file ChatManager.cpp.
Referenced by invokeMethod().
ChatRoom * ChatManagerAdapter::getGroupRoom ()
Definition at line 1302 of file ChatManager.cpp.
Referenced by invokeMethod().
ChatRoom * ChatManagerAdapter::getGuildRoom ()
Definition at line 1298 of file ChatManager.cpp.
Referenced by invokeMethod().
unsigned int ChatManagerAdapter::getNextRoomID ()
Definition at line 1290 of file ChatManager.cpp.
Referenced by invokeMethod().
CreatureObject * ChatManagerAdapter::getPlayer (const String & name)
Definition at line 1190 of file ChatManager.cpp.
Referenced by invokeMethod().
int ChatManagerAdapter::getPlayerCount ()
Definition at line 1294 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::handleChatEnterRoomById (CreatureObject * player, unsigned int counter, unsigned int roomID)
Definition at line 1238 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::handleChatRoomMessage (CreatureObject * sender, const UnicodeString & message, unsigned int roomID, unsigned int counter)
Definition at line 1234 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::handleGroupChat (CreatureObject * player, const UnicodeString & message)
Definition at line 1210 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::handleGuildChat (CreatureObject * player, const UnicodeString & message)
Definition at line 1214 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::handlePlanetChat (CreatureObject * player, const UnicodeString & message)
Definition at line 1218 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::handleRequestPersistentMsg (CreatureObject * player, unsigned int mailID)
Definition at line 1262 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::handleSocialInternalMessage (CreatureObject * sender, const UnicodeString & arguments)
Definition at line 1242 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::handleSpatialChatInternalMessage (CreatureObject * player, const UnicodeString & args)
Definition at line 1206 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::initiatePlanetRooms ()
Definition at line 1158 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::initiateRooms ()
Definition at line 1154 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 929 of file ChatManager.cpp.
References addPlayer(), addRoom(), broadcastGalaxy(), broadcastMessage(), createGroupRoom(), createRoom(), createRoomByFullPath(), deletePersistentMessage(), destroyRoom(), destroyRooms(), finalize(), getChatRoom(), getChatRoomByFullPath(), getChatRoomByGamePath(), getGameRoom(), getGroupRoom(), getGuildRoom(), getNextRoomID(), getPlayer(), getPlayerCount(), handleChatEnterRoomById(), handleChatRoomMessage(), handleGroupChat(), handleGuildChat(), handlePlanetChat(), handleRequestPersistentMsg(), handleSocialInternalMessage(), handleSpatialChatInternalMessage(), initiatePlanetRooms(), initiateRooms(), loadMail(), populateRoomListMessage(), removePlayer(), removeRoom(), RPC_ADDPLAYER__CREATUREOBJECT_, RPC_ADDROOM__CHATROOM_, RPC_BROADCASTGALAXY__CREATUREOBJECT_STRING_, RPC_BROADCASTGALAXY__STRING_STRING_, RPC_BROADCASTMESSAGE__BASEMESSAGE_, RPC_BROADCASTMESSAGE__CREATUREOBJECT_UNICODESTRING_LONG_INT_INT_, RPC_CREATEGROUPROOM__LONG_CREATUREOBJECT_, RPC_CREATEROOM__STRING_CHATROOM_, RPC_CREATEROOMBYFULLPATH__STRING_, RPC_DELETEPERSISTENTMESSAGE__CREATUREOBJECT_INT_, RPC_DESTROYROOM__CHATROOM_, RPC_DESTROYROOMS__, RPC_FINALIZE__, RPC_GETCHATROOM__INT_, RPC_GETCHATROOMBYFULLPATH__STRING_, RPC_GETCHATROOMBYGAMEPATH__CHATROOM_STRING_, RPC_GETGAMEROOM__STRING_, RPC_GETGROUPROOM__, RPC_GETGUILDROOM__, RPC_GETNEXTROOMID__, RPC_GETPLAYER__STRING_, RPC_GETPLAYERCOUNT__, RPC_HANDLECHATENTERROOMBYID__CREATUREOBJECT_INT_INT_, RPC_HANDLECHATROOMMESSAGE__CREATUREOBJECT_UNICODESTRING_INT_INT_, RPC_HANDLEGROUPCHAT__CREATUREOBJECT_UNICODESTRING_, RPC_HANDLEGUILDCHAT__CREATUREOBJECT_UNICODESTRING_, RPC_HANDLEPLANETCHAT__CREATUREOBJECT_UNICODESTRING_, RPC_HANDLEREQUESTPERSISTENTMSG__CREATUREOBJECT_INT_, RPC_HANDLESOCIALINTERNALMESSAGE__CREATUREOBJECT_UNICODESTRING_, RPC_HANDLESPATIALCHATINTERNALMESSAGE__CREATUREOBJECT_UNICODESTRING_, RPC_INITIATEPLANETROOMS__, RPC_INITIATEROOMS__, RPC_LOADMAIL__CREATUREOBJECT_, RPC_POPULATEROOMLISTMESSAGE__CHATROOM_CHATROOMLIST_, RPC_REMOVEPLAYER__STRING_, RPC_REMOVEROOM__CHATROOM_, RPC_SENDMAIL__STRING_UNICODESTRING_UNICODESTRING_STRING_, RPC_SENDROOMLIST__CREATUREOBJECT_, RPC_SETPLAYERMANAGER__PLAYERMANAGER_, sendMail(), sendRoomList(), and setPlayerManager().
void ChatManagerAdapter::loadMail (CreatureObject * player)
Definition at line 1254 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::populateRoomListMessage (ChatRoom * channel, ChatRoomList * msg)
Definition at line 1178 of file ChatManager.cpp.
Referenced by invokeMethod().
CreatureObject * ChatManagerAdapter::removePlayer (const String & name)
Definition at line 1194 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::removeRoom (ChatRoom * channel)
Definition at line 1174 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::sendMail (const String & sendername, const UnicodeString & header, const UnicodeString & body, const String & name)
Definition at line 1258 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::sendRoomList (CreatureObject * player)
Definition at line 1182 of file ChatManager.cpp.
Referenced by invokeMethod().
void ChatManagerAdapter::setPlayerManager (PlayerManager * manager)
Definition at line 1278 of file ChatManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatManager.cpp