Core3: MissionTargetMap Class Reference
MissionTargetMap Class Reference
#include <MissionTargetMap.h>
Public Member Functions
MissionTargetMap ()
bool add (SceneObject *mission)
int size ()
SceneObject * getRandomTarget (SceneObject *origin, int diff)
Private Attributes
SortedVector< ManagedReference
< SceneObject * > > missions
Detailed Description
Definition at line 15 of file MissionTargetMap.h.
Constructor & Destructor Documentation
MissionTargetMap::MissionTargetMap () inline
Definition at line 19 of file MissionTargetMap.h.
References missions.
Member Function Documentation
bool MissionTargetMap::add (SceneObject * mission) inline
Definition at line 27 of file MissionTargetMap.h.
References missions.
SceneObject* MissionTargetMap::getRandomTarget (SceneObject * origin, int diff) inline
Definition at line 35 of file MissionTargetMap.h.
References server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::Zone::getMaxX(), server::zone::Zone::getMaxY(), server::zone::Zone::getMinX(), server::zone::Zone::getMinY(), server::zone::objects::scene::SceneObject::getZone(), and missions.
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission().
int MissionTargetMap::size () inline
Definition at line 31 of file MissionTargetMap.h.
References missions.
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission().
Member Data Documentation
SortedVector<ManagedReference<SceneObject*> > MissionTargetMap::missions private
Definition at line 16 of file MissionTargetMap.h.
Referenced by add(), getRandomTarget(), MissionTargetMap(), and size().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/MissionTargetMap.h