Core3: HealStatesSelfCommand Class Reference
HealStatesSelfCommand Class Reference
#include <HealStatesSelfCommand.h>
Public Member Functions
HealStatesSelfCommand (const String &name, ZoneProcessServer *server)
bool canPerformSkill (CreatureObject *creature)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file HealStatesSelfCommand.h.
Constructor & Destructor Documentation
HealStatesSelfCommand::HealStatesSelfCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file HealStatesSelfCommand.h.
Member Function Documentation
bool HealStatesSelfCommand::canPerformSkill (CreatureObject * creature) inline
Definition at line 58 of file HealStatesSelfCommand.h.
References CreatureState::BLINDED, CreatureState::DIZZY, server::zone::objects::creature::CreatureObject::hasState(), CreatureState::INTIMIDATED, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and CreatureState::STUNNED.
Referenced by doQueueCommand().
int HealStatesSelfCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 67 of file HealStatesSelfCommand.h.
References CreatureState::BLINDED, canPerformSkill(), CreatureState::DIZZY, server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::hasState(), CreatureState::INTIMIDATED, server::zone::objects::creature::CreatureObject::playEffect(), server::zone::objects::creature::CreatureObject::removeStateBuff(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and CreatureState::STUNNED.
float HealStatesSelfCommand::getCommandDuration (CreatureObject * object, const UnicodeString & arguments) inline
Definition at line 120 of file HealStatesSelfCommand.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/HealStatesSelfCommand.h