Core3: server::zone::ZoneImplementation Class Reference
server::zone::ZoneImplementation Class Reference
#include <Zone.h>
Public Member Functions
ZoneImplementation (ZoneProcessServer *processor, const String &zoneName)
ZoneImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void finalize ()
SceneObject * getNearestPlanetaryObject (SceneObject *object, const String &mapObjectLocationType)
void initializePrivateData ()
QuadTree * getRegionTree ()
int getInRangeObjects (float x, float y, float range, SortedVector< ManagedReference< QuadTreeEntry * > > *objects, bool readLockZone)
void createContainerComponent ()
int getInRangeActiveAreas (float x, float y, SortedVector< ManagedReference< ActiveArea * > > *objects, bool readLockZone)
SortedVector< ManagedReference
< SceneObject * > > getPlanetaryObjectList (const String &mapObjectLocationType)
void insert (QuadTreeEntry *entry)
void remove (QuadTreeEntry *entry)
void update (QuadTreeEntry *entry)
void inRange (QuadTreeEntry *entry, float range)
void updateActiveAreas (SceneObject *object)
void startManagers ()
void stopManagers ()
float getHeight (float x, float y)
void addSceneObject (SceneObject *object)
void addCityRegionToUpdate (CityRegion *city)
void updateCityRegions ()
void sendMapLocationsTo (SceneObject *player)
void dropSceneObject (SceneObject *object)
PlanetManager * getPlanetManager ()
ZoneServer * getZoneServer ()
CreatureManager * getCreatureManager ()
unsigned long long getGalacticTime ()
bool hasManagersStarted ()
float getMinX ()
float getMaxX ()
float getMinY ()
float getMaxY ()
bool isWithinBoundaries (const Vector3 &position)
float getBoundingRadius ()
void registerObjectWithPlanetaryMap (SceneObject *object)
void unregisterObjectWithPlanetaryMap (SceneObject *object)
String getZoneName ()
unsigned int getZoneCRC ()
GCWManager * getGCWManager ()
void setChatRoom (ChatRoom *room)
ChatRoom * getChatRoom ()
operator const Zone * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void loadTemplateData (SharedObjectTemplate *templateData)
virtual void createComponents ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendTo (SceneObject *player, bool doClose)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendBaselinesTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
virtual void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
virtual void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
virtual int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isTangibleObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
virtual void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< Zone * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Protected Member Functions
virtual ~ZoneImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
String zoneName
unsigned int zoneCRC
ManagedReference
< ZoneProcessServer * > processor
Reference< ObjectMap * > objectMap
ManagedReference< PlanetManager * > planetManager
ManagedReference
< CreatureManager * > creatureManager
ManagedReference< GCWManager * > gcwManager
ManagedReference< ChatRoom * > chatRoom
SortedVector< ManagedReference
< CityRegion * > > cityRegionUpdateVector
ManagedReference< ZoneServer * > server
QuadTreeReference regionTree
QuadTreeReference quadTree
Time galacticTime
Reference< HeightMap * > heightMap
Reference< MapLocationTable * > mapLocations
bool managersStarted
Friends
class Zone
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Detailed Description
Definition at line 315 of file Zone.h.
Constructor & Destructor Documentation
ZoneImplementation::ZoneImplementation (ZoneProcessServer * processor, const String & zoneName)
Definition at line 71 of file ZoneImplementation.cpp.
References gcwManager, heightMap, managersStarted, mapLocations, objectMap, planetManager, processor, quadTree, regionTree, server, server::zone::objects::scene::SceneObjectImplementation::setLoggingName(), zoneCRC, and zoneName.
ZoneImplementation::ZoneImplementation (DummyConstructorParameter * param)
Definition at line 554 of file Zone.cpp.
References _initializeImplementation().
ZoneImplementation::~ZoneImplementation () protected virtual
Definition at line 559 of file Zone.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * ZoneImplementation::_getStub ()
Definition at line 577 of file Zone.cpp.
References _this.
void ZoneImplementation::_initializeImplementation () protected
Definition at line 564 of file Zone.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ZoneImplementation().
void ZoneImplementation::_serializationHelperMethod () protected
Definition at line 613 of file Zone.cpp.
Referenced by _initializeImplementation().
void ZoneImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 572 of file Zone.cpp.
References _this.
Referenced by server::zone::Zone::Zone().
void ZoneImplementation::addCityRegionToUpdate (CityRegion * city)
Definition at line 731 of file Zone.cpp.
References _this, and cityRegionUpdateVector.
Referenced by server::zone::Zone::addCityRegionToUpdate().
void ZoneImplementation::addSceneObject (SceneObject * object)
Definition at line 386 of file ZoneImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::structure::StructureObject::isCivicStructure(), server::zone::objects::structure::StructureObject::isCommercialStructure(), server::zone::objects::scene::SceneObject::isStructureObject(), objectMap, and registerObjectWithPlanetaryMap().
Referenced by server::zone::Zone::addSceneObject().
void ZoneImplementation::createContainerComponent () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 97 of file ZoneImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::containerComponent.
Referenced by server::zone::Zone::createContainerComponent().
void ZoneImplementation::dropSceneObject (SceneObject * object)
Definition at line 415 of file ZoneImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), objectMap, and unregisterObjectWithPlanetaryMap().
Referenced by server::zone::Zone::dropSceneObject().
void ZoneImplementation::finalize ()
Definition at line 111 of file ZoneImplementation.cpp.
Referenced by ~ZoneImplementation().
float ZoneImplementation::getBoundingRadius ()
Definition at line 557 of file ZoneImplementation.cpp.
References planetManager.
Referenced by server::zone::Zone::getBoundingRadius().
ChatRoom * ZoneImplementation::getChatRoom ()
Definition at line 782 of file Zone.cpp.
References chatRoom.
Referenced by server::zone::Zone::getChatRoom().
CreatureManager * ZoneImplementation::getCreatureManager ()
Definition at line 747 of file Zone.cpp.
References creatureManager.
Referenced by server::zone::Zone::getCreatureManager().
unsigned long long ZoneImplementation::getGalacticTime ()
Definition at line 752 of file Zone.cpp.
References galacticTime.
Referenced by server::zone::Zone::getGalacticTime().
GCWManager * ZoneImplementation::getGCWManager ()
Definition at line 772 of file Zone.cpp.
References gcwManager.
Referenced by server::zone::Zone::getGCWManager().
float ZoneImplementation::getHeight (float x, float y)
Definition at line 164 of file ZoneImplementation.cpp.
References TerrainManager::getHeight(), heightMap, and planetManager.
Referenced by server::zone::Zone::getHeight().
int ZoneImplementation::getInRangeActiveAreas (float x, float y, SortedVector< ManagedReference< ActiveArea * > > * objects, bool readLockZone)
Definition at line 257 of file ZoneImplementation.cpp.
References _this, and regionTree.
Referenced by server::zone::Zone::getInRangeActiveAreas().
int ZoneImplementation::getInRangeObjects (float x, float y, float range, SortedVector< ManagedReference< QuadTreeEntry * > > * objects, bool readLockZone)
Definition at line 201 of file ZoneImplementation.cpp.
References _this, server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::isVehicleObject(), and quadTree.
Referenced by server::zone::Zone::getInRangeObjects().
float ZoneImplementation::getMaxX ()
Definition at line 484 of file ZoneImplementation.cpp.
References planetManager.
Referenced by server::zone::Zone::getMaxX(), and isWithinBoundaries().
float ZoneImplementation::getMaxY ()
Definition at line 492 of file ZoneImplementation.cpp.
References planetManager.
Referenced by server::zone::Zone::getMaxY(), and isWithinBoundaries().
float ZoneImplementation::getMinX ()
These functions return the size of the terrain file for this zone.
Definition at line 480 of file ZoneImplementation.cpp.
References planetManager.
Referenced by server::zone::Zone::getMinX(), and isWithinBoundaries().
float ZoneImplementation::getMinY ()
Definition at line 488 of file ZoneImplementation.cpp.
References planetManager.
Referenced by server::zone::Zone::getMinY(), and isWithinBoundaries().
SceneObject * ZoneImplementation::getNearestPlanetaryObject (SceneObject * object, const String & mapObjectLocationType)
Definition at line 425 of file ZoneImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDistanceTo(), and mapLocations.
Referenced by server::zone::Zone::getNearestPlanetaryObject().
SortedVector< ManagedReference< SceneObject * > > ZoneImplementation::getPlanetaryObjectList (const String & mapObjectLocationType)
Definition at line 454 of file ZoneImplementation.cpp.
References MapLocationEntry::getObject(), and mapLocations.
Referenced by server::zone::Zone::getPlanetaryObjectList().
PlanetManager * ZoneImplementation::getPlanetManager ()
Definition at line 737 of file Zone.cpp.
References planetManager.
Referenced by server::zone::Zone::getPlanetManager().
QuadTree * ZoneImplementation::getRegionTree ()
Definition at line 726 of file Zone.cpp.
References regionTree.
Referenced by server::zone::Zone::getRegionTree().
unsigned int ZoneImplementation::getZoneCRC ()
Definition at line 767 of file Zone.cpp.
References zoneCRC.
Referenced by server::zone::Zone::getZoneCRC().
String ZoneImplementation::getZoneName ()
Definition at line 762 of file Zone.cpp.
References zoneName.
Referenced by server::zone::Zone::getZoneName(), and startManagers().
ZoneServer * ZoneImplementation::getZoneServer ()
Definition at line 742 of file Zone.cpp.
References server.
Referenced by server::zone::Zone::getZoneServer().
bool ZoneImplementation::hasManagersStarted ()
Definition at line 757 of file Zone.cpp.
References managersStarted.
Referenced by server::zone::Zone::hasManagersStarted().
void ZoneImplementation::initializePrivateData ()
Definition at line 101 of file ZoneImplementation.cpp.
References _this, creatureManager, gcwManager, planetManager, processor, and zoneName.
Referenced by server::zone::Zone::initializePrivateData().
void ZoneImplementation::initializeTransientMembers ()
Definition at line 115 of file ZoneImplementation.cpp.
References heightMap, and mapLocations.
Referenced by server::zone::Zone::initializeTransientMembers(), and readObject().
void ZoneImplementation::inRange (QuadTreeEntry * entry, float range)
Definition at line 197 of file ZoneImplementation.cpp.
References quadTree.
Referenced by server::zone::Zone::inRange().
void ZoneImplementation::insert (QuadTreeEntry * entry)
Definition at line 178 of file ZoneImplementation.cpp.
References _this, and quadTree.
Referenced by server::zone::Zone::insert().
bool ZoneImplementation::isWithinBoundaries (const Vector3 & position)
Definition at line 541 of file ZoneImplementation.cpp.
References getMaxX(), getMaxY(), getMinX(), and getMinY().
Referenced by server::zone::Zone::isWithinBoundaries().
void ZoneImplementation::lock (bool doLock = true) protected
Definition at line 585 of file Zone.cpp.
References _this.
void ZoneImplementation::lock (ManagedObject * obj) protected
Definition at line 589 of file Zone.cpp.
References _this.
ZoneImplementation::operator const Zone * ()
Definition at line 581 of file Zone.cpp.
void ZoneImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 620 of file Zone.cpp.
References initializeTransientMembers(), and readObjectMember().
bool ZoneImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 639 of file Zone.cpp.
References chatRoom, quadTree, regionTree, zoneCRC, and zoneName.
Referenced by readObject().
void ZoneImplementation::registerObjectWithPlanetaryMap (SceneObject * object)
Registers the object to the planetary map. This also makes the object visible to the find command.
Parameters
object The object to register to the planetary map.
Definition at line 401 of file ZoneImplementation.cpp.
References mapLocations.
Referenced by addSceneObject(), server::zone::Zone::registerObjectWithPlanetaryMap(), and updateCityRegions().
void ZoneImplementation::remove (QuadTreeEntry * entry)
Definition at line 184 of file ZoneImplementation.cpp.
References _this, and quadTree.
Referenced by server::zone::Zone::remove().
void ZoneImplementation::rlock (bool doLock = true) protected
Definition at line 593 of file Zone.cpp.
References _this.
void ZoneImplementation::runlock (bool doLock = true) protected
Definition at line 609 of file Zone.cpp.
References _this.
void ZoneImplementation::sendMapLocationsTo (SceneObject * player)
Definition at line 420 of file ZoneImplementation.cpp.
References mapLocations, server::zone::objects::scene::SceneObject::sendMessage(), and zoneName.
Referenced by server::zone::Zone::sendMapLocationsTo().
void ZoneImplementation::setChatRoom (ChatRoom * room)
Definition at line 777 of file Zone.cpp.
References chatRoom.
Referenced by server::zone::Zone::setChatRoom().
void ZoneImplementation::startManagers ()
Definition at line 125 of file ZoneImplementation.cpp.
References creatureManager, gcwManager, getZoneName(), managersStarted, planetManager, and updateCityRegions().
Referenced by server::zone::Zone::startManagers().
void ZoneImplementation::stopManagers ()
Definition at line 145 of file ZoneImplementation.cpp.
Referenced by server::zone::Zone::stopManagers().
void ZoneImplementation::unlock (bool doLock = true) protected
Definition at line 605 of file Zone.cpp.
References _this.
void ZoneImplementation::unregisterObjectWithPlanetaryMap (SceneObject * object)
Unregisters the object from the planetary map.
Parameters
object The object to unregister from the planetary map.
Definition at line 408 of file ZoneImplementation.cpp.
References mapLocations.
Referenced by dropSceneObject(), server::zone::Zone::unregisterObjectWithPlanetaryMap(), and updateCityRegions().
void ZoneImplementation::update (QuadTreeEntry * entry)
Definition at line 191 of file ZoneImplementation.cpp.
References _this, and quadTree.
Referenced by server::zone::Zone::update().
void ZoneImplementation::updateActiveAreas (SceneObject * object)
Definition at line 290 of file ZoneImplementation.cpp.
References _this, server::zone::objects::scene::SceneObject::addActiveArea(), server::zone::objects::area::ActiveArea::containsPoint(), creatureManager, server::zone::objects::scene::SceneObject::dropActiveArea(), server::zone::objects::area::ActiveArea::enqueueEnterEvent(), server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::objects::scene::SceneObject::getContainerLock(), server::zone::objects::scene::SceneObject::hasActiveArea(), server::zone::objects::area::ActiveArea::notifyEnter(), server::zone::objects::scene::SceneObject::notifyPositionUpdate(), and regionTree.
Referenced by server::zone::Zone::updateActiveAreas().
void ZoneImplementation::updateCityRegions ()
Definition at line 496 of file ZoneImplementation.cpp.
References cityRegionUpdateVector, server::zone::objects::region::CityRegion::cleanupCitizens(), server::zone::objects::region::CityRegion::getCivicStructure(), server::zone::objects::region::CityRegion::getCommercialStructure(), server::zone::objects::region::CityRegion::getCommercialStructuresCount(), server::zone::objects::region::CityRegion::getNextUpdateTime(), server::zone::objects::region::CityRegion::getRegion(), server::zone::objects::region::CityRegion::getRegionsCount(), server::zone::objects::region::CityRegion::getStructuresCount(), server::zone::objects::scene::SceneObjectImplementation::info(), server::zone::objects::region::CityRegion::isRegistered(), registerObjectWithPlanetaryMap(), server::zone::objects::region::CityRegion::rescheduleUpdateEvent(), server::zone::objects::region::CityRegion::setLoaded(), and unregisterObjectWithPlanetaryMap().
Referenced by startManagers(), and server::zone::Zone::updateCityRegions().
void ZoneImplementation::wlock (bool doLock = true) protected
Definition at line 597 of file Zone.cpp.
References _this.
void ZoneImplementation::wlock (ManagedObject * obj) protected
Definition at line 601 of file Zone.cpp.
References _this.
void ZoneImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 669 of file Zone.cpp.
References writeObjectMembers().
int ZoneImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 676 of file Zone.cpp.
References chatRoom, quadTree, regionTree, zoneCRC, and zoneName.
Referenced by writeObject().
Friends And Related Function Documentation
friend class Zone friend
Definition at line 476 of file Zone.h.
Member Data Documentation
WeakReference<Zone*> server::zone::ZoneImplementation::_this
Definition at line 444 of file Zone.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addCityRegionToUpdate(), getInRangeActiveAreas(), getInRangeObjects(), initializePrivateData(), insert(), lock(), remove(), rlock(), runlock(), unlock(), update(), updateActiveAreas(), and wlock().
ManagedReference<ChatRoom* > server::zone::ZoneImplementation::chatRoom private
Definition at line 330 of file Zone.h.
Referenced by getChatRoom(), readObjectMember(), setChatRoom(), and writeObjectMembers().
SortedVector<ManagedReference<CityRegion* > > server::zone::ZoneImplementation::cityRegionUpdateVector private
Definition at line 332 of file Zone.h.
Referenced by addCityRegionToUpdate(), and updateCityRegions().
ManagedReference<CreatureManager* > server::zone::ZoneImplementation::creatureManager private
Definition at line 326 of file Zone.h.
Referenced by getCreatureManager(), initializePrivateData(), startManagers(), and updateActiveAreas().
Time server::zone::ZoneImplementation::galacticTime private
Definition at line 340 of file Zone.h.
Referenced by getGalacticTime().
ManagedReference<GCWManager* > server::zone::ZoneImplementation::gcwManager private
Definition at line 328 of file Zone.h.
Referenced by getGCWManager(), initializePrivateData(), startManagers(), and ZoneImplementation().
Reference<HeightMap* > server::zone::ZoneImplementation::heightMap private
Definition at line 342 of file Zone.h.
Referenced by getHeight(), initializeTransientMembers(), and ZoneImplementation().
bool server::zone::ZoneImplementation::managersStarted private
Definition at line 346 of file Zone.h.
Referenced by hasManagersStarted(), startManagers(), and ZoneImplementation().
Reference<MapLocationTable* > server::zone::ZoneImplementation::mapLocations private
Definition at line 344 of file Zone.h.
Referenced by getNearestPlanetaryObject(), getPlanetaryObjectList(), initializeTransientMembers(), registerObjectWithPlanetaryMap(), sendMapLocationsTo(), unregisterObjectWithPlanetaryMap(), and ZoneImplementation().
Reference<ObjectMap* > server::zone::ZoneImplementation::objectMap private
Definition at line 322 of file Zone.h.
Referenced by addSceneObject(), dropSceneObject(), and ZoneImplementation().
ManagedReference<PlanetManager* > server::zone::ZoneImplementation::planetManager private
Definition at line 324 of file Zone.h.
Referenced by getBoundingRadius(), getHeight(), getMaxX(), getMaxY(), getMinX(), getMinY(), getPlanetManager(), initializePrivateData(), startManagers(), and ZoneImplementation().
ManagedReference<ZoneProcessServer* > server::zone::ZoneImplementation::processor private
Definition at line 320 of file Zone.h.
Referenced by initializePrivateData(), and ZoneImplementation().
QuadTreeReference server::zone::ZoneImplementation::quadTree private
Definition at line 338 of file Zone.h.
Referenced by getInRangeObjects(), inRange(), insert(), readObjectMember(), remove(), update(), writeObjectMembers(), and ZoneImplementation().
QuadTreeReference server::zone::ZoneImplementation::regionTree private
Definition at line 336 of file Zone.h.
Referenced by getInRangeActiveAreas(), getRegionTree(), readObjectMember(), updateActiveAreas(), writeObjectMembers(), and ZoneImplementation().
ManagedReference<ZoneServer* > server::zone::ZoneImplementation::server private
Definition at line 334 of file Zone.h.
Referenced by getZoneServer(), and ZoneImplementation().
unsigned int server::zone::ZoneImplementation::zoneCRC private
Definition at line 318 of file Zone.h.
Referenced by getZoneCRC(), readObjectMember(), writeObjectMembers(), and ZoneImplementation().
String server::zone::ZoneImplementation::zoneName private
Definition at line 316 of file Zone.h.
Referenced by getZoneName(), initializePrivateData(), readObjectMember(), sendMapLocationsTo(), writeObjectMembers(), and ZoneImplementation().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/Zone.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/Zone.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneImplementation.cpp