Core3: LootGroupCollectionEntry Class Reference
LootGroupCollectionEntry Class Reference
#include <LootGroupCollectionEntry.h>
Public Member Functions
LootGroupCollectionEntry ()
LootGroupCollectionEntry (const LootGroupCollectionEntry &lgce)
LootGroupCollectionEntry & operator= (const LootGroupCollectionEntry &lgce)
void readObject (LuaObject *lua)
int getLootChance ()
LootGroups * getLootGroups ()
Private Attributes
LootGroups lootGroups
int lootChance
Detailed Description
Definition at line 14 of file LootGroupCollectionEntry.h.
Constructor & Destructor Documentation
LootGroupCollectionEntry::LootGroupCollectionEntry () inline
Definition at line 20 of file LootGroupCollectionEntry.h.
References lootChance.
LootGroupCollectionEntry::LootGroupCollectionEntry (const LootGroupCollectionEntry & lgce) inline
Definition at line 24 of file LootGroupCollectionEntry.h.
References lootChance, and lootGroups.
Member Function Documentation
int LootGroupCollectionEntry::getLootChance () inline
Definition at line 48 of file LootGroupCollectionEntry.h.
References lootChance.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootFromCollection().
LootGroups* LootGroupCollectionEntry::getLootGroups () inline
Definition at line 52 of file LootGroupCollectionEntry.h.
References lootGroups.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootFromCollection(), server::zone::objects::creature::ai::AiActorImplementation::getLootGroups(), server::zone::objects::creature::AiAgentImplementation::getLootGroups(), and TEST_F().
LootGroupCollectionEntry& LootGroupCollectionEntry::operator= (const LootGroupCollectionEntry & lgce) inline
Definition at line 29 of file LootGroupCollectionEntry.h.
References lootChance, and lootGroups.
void LootGroupCollectionEntry::readObject (LuaObject * lua) inline
Definition at line 39 of file LootGroupCollectionEntry.h.
References lootChance, lootGroups, and LootGroups::readObject().
Referenced by LootGroupCollection::readObject().
Member Data Documentation
int LootGroupCollectionEntry::lootChance private
Definition at line 17 of file LootGroupCollectionEntry.h.
Referenced by getLootChance(), LootGroupCollectionEntry(), operator=(), and readObject().
LootGroups LootGroupCollectionEntry::lootGroups private
Definition at line 15 of file LootGroupCollectionEntry.h.
Referenced by getLootGroups(), LootGroupCollectionEntry(), operator=(), and readObject().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/lootgroup/LootGroupCollectionEntry.h