Core3: server::zone::objects::player::sessions::SlicingSessionImplementation Class Reference
server::zone::objects::player::sessions::SlicingSessionImplementation Class Reference
#include <SlicingSession.h>
Public Member Functions
SlicingSessionImplementation (CreatureObject *parent)
SlicingSessionImplementation (DummyConstructorParameter *param)
void initalizeSlicingMenu (CreatureObject *pl, TangibleObject *obj)
void handleMenuSelect (CreatureObject *pl, byte menuID, SuiListBox *suiBox)
int initializeSession ()
int cancelSession ()
int clearSession ()
void endSlicing ()
bool isBaseSlice ()
void setBaseSlice (bool val)
int getSlicingSkill (CreatureObject *slicer)
bool hasPrecisionLaserKnife (bool removeItem=true)
bool hasWeaponUpgradeKit ()
bool hasArmorUpgradeKit ()
void useClampFromInventory (SlicingTool *clamp)
operator const SlicingSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< SlicingSession * > _this
Protected Member Functions
virtual ~SlicingSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > player
ManagedWeakReference
< TangibleObject * > tangibleObject
ManagedReference< SuiListBox * > slicingSuiBox
Reference
< RelockLootContainerEvent * > relockEvent
byte firstCable
byte nodeCable
bool cableBlue
bool cableRed
bool usedNode
bool usedClamp
bool baseSlice
Private Member Functions
void generateSliceMenu (SuiListBox *suiBox)
String getPrefix (TangibleObject *obj)
byte getProgress ()
void handleSliceFailed ()
void handleUseClamp ()
void handleUseFlowAnalyzer ()
void handleSlice (SuiListBox *suiBox)
void handleWeaponSlice ()
void handleSliceDamage (byte percent)
void handleSliceSpeed (byte percent)
void handleArmorSlice ()
void handleSliceEncumbrance (byte percent)
void handleSliceEffectiveness (byte percent)
void handleContainerSlice ()
Friends
class SlicingSession
Detailed Description
Definition at line 125 of file SlicingSession.h.
Constructor & Destructor Documentation
SlicingSessionImplementation::SlicingSessionImplementation (CreatureObject * parent)
Definition at line 438 of file SlicingSession.cpp.
References _initializeImplementation(), and initializeSession().
SlicingSessionImplementation::SlicingSessionImplementation (DummyConstructorParameter * param)
Definition at line 216 of file SlicingSession.cpp.
References _initializeImplementation().
SlicingSessionImplementation::~SlicingSessionImplementation () protected virtual
Definition at line 221 of file SlicingSession.cpp.
Member Function Documentation
DistributedObjectStub * SlicingSessionImplementation::_getStub ()
Definition at line 241 of file SlicingSession.cpp.
References _this.
void SlicingSessionImplementation::_initializeImplementation () protected
Definition at line 228 of file SlicingSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SlicingSessionImplementation().
void SlicingSessionImplementation::_serializationHelperMethod () protected
Definition at line 277 of file SlicingSession.cpp.
Referenced by _initializeImplementation().
void SlicingSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 236 of file SlicingSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::SlicingSession::SlicingSession().
int SlicingSessionImplementation::cancelSession ()
Definition at line 448 of file SlicingSession.cpp.
References clearSession(), player, SessionFacadeType::SLICING, and tangibleObject.
Referenced by server::zone::objects::player::sessions::SlicingSession::cancelSession(), endSlicing(), and handleMenuSelect().
int SlicingSessionImplementation::clearSession ()
Definition at line 461 of file SlicingSession.cpp.
References player, and tangibleObject.
Referenced by cancelSession(), and server::zone::objects::player::sessions::SlicingSession::clearSession().
void SlicingSessionImplementation::endSlicing ()
Definition at line 215 of file SlicingSessionImplementation.cpp.
References cancelSession(), player, and tangibleObject.
Referenced by server::zone::objects::player::sessions::SlicingSession::endSlicing(), handleSlice(), and handleSliceFailed().
void SlicingSessionImplementation::finalize () protected
Definition at line 225 of file SlicingSession.cpp.
void SlicingSessionImplementation::generateSliceMenu (SuiListBox * suiBox) private
Definition at line 114 of file SlicingSessionImplementation.cpp.
References server::zone::objects::player::sui::listbox::SuiListBox::addMenuItem(), cableBlue, cableRed, firstCable, server::zone::objects::player::sui::listbox::SuiListBox::generateMessage(), getPrefix(), getProgress(), nodeCable, player, server::zone::objects::player::sui::listbox::SuiListBox::removeAllMenuItems(), server::zone::objects::player::sui::SuiBox::setPromptText(), tangibleObject, usedClamp, and usedNode.
Referenced by handleMenuSelect(), and initalizeSlicingMenu().
String SlicingSessionImplementation::getPrefix (TangibleObject * obj) private
Definition at line 470 of file SlicingSession.cpp.
References server::zone::objects::scene::SceneObject::isArmorObject(), isBaseSlice(), server::zone::objects::scene::SceneObject::isContainerObject(), server::zone::objects::scene::SceneObject::isMissionTerminal(), server::zone::objects::scene::SceneObject::isWeaponObject(), and tangibleObject.
Referenced by generateSliceMenu(), and handleSlice().
byte SlicingSessionImplementation::getProgress () private
Definition at line 491 of file SlicingSession.cpp.
References cableBlue, and cableRed.
Referenced by generateSliceMenu(), and handleMenuSelect().
int SlicingSessionImplementation::getSlicingSkill (CreatureObject * slicer)
Definition at line 232 of file SlicingSessionImplementation.cpp.
References server::zone::objects::creature::CreatureObject::hasSkill().
Referenced by server::zone::objects::player::sessions::SlicingSession::getSlicingSkill(), handleArmorSlice(), and handleWeaponSlice().
void SlicingSessionImplementation::handleArmorSlice () private
Definition at line 583 of file SlicingSessionImplementation.cpp.
References getSlicingSkill(), handleSliceEffectiveness(), handleSliceEncumbrance(), player, and tangibleObject.
Referenced by handleSlice().
void SlicingSessionImplementation::handleContainerSlice () private
Definition at line 664 of file SlicingSessionImplementation.cpp.
References server::zone::managers::loot::LootManager::createLoot(), player, SceneObjectType::PLAYERLOOTCRATE, relockEvent, server::zone::objects::scene::SceneObject::sendTo(), server::zone::objects::tangible::Container::setLockedStatus(), server::zone::objects::tangible::TangibleObject::setSliced(), and tangibleObject.
Referenced by handleSlice().
void SlicingSessionImplementation::handleMenuSelect (CreatureObject * pl, byte menuID, SuiListBox * suiBox)
Definition at line 157 of file SlicingSessionImplementation.cpp.
References cableBlue, cableRed, cancelSession(), firstCable, generateSliceMenu(), getProgress(), handleSlice(), handleSliceFailed(), handleUseClamp(), handleUseFlowAnalyzer(), hasPrecisionLaserKnife(), player, and tangibleObject.
Referenced by server::zone::objects::player::sessions::SlicingSession::handleMenuSelect().
void SlicingSessionImplementation::handleSlice (SuiListBox * suiBox) private
Definition at line 439 of file SlicingSessionImplementation.cpp.
References server::zone::objects::tangible::terminal::mission::MissionTerminal::addSlicer(), server::zone::managers::player::PlayerManager::awardExperience(), endSlicing(), server::zone::objects::player::sui::listbox::SuiListBox::generateMessage(), server::zone::Zone::getGCWManager(), getPrefix(), server::zone::objects::scene::SceneObject::getZone(), handleArmorSlice(), handleContainerSlice(), handleWeaponSlice(), isBaseSlice(), player, SceneObjectType::PLAYERLOOTCRATE, server::zone::objects::player::sui::listbox::SuiListBox::removeAllMenuItems(), server::zone::objects::player::sui::SuiBox::setCancelButton(), server::zone::objects::player::sui::SuiBox::setPromptText(), and tangibleObject.
Referenced by handleMenuSelect().
void SlicingSessionImplementation::handleSliceDamage (byte percent) private
Definition at line 536 of file SlicingSessionImplementation.cpp.
References player, server::zone::objects::tangible::weapon::WeaponObject::setDamageSlice(), server::chat::StringIdChatParameter::setDI(), server::zone::objects::tangible::TangibleObject::setSliced(), server::zone::objects::scene::variables::StringId::setStringId(), and tangibleObject.
Referenced by handleWeaponSlice().
void SlicingSessionImplementation::handleSliceEffectiveness (byte percent) private
Definition at line 643 of file SlicingSessionImplementation.cpp.
References player, server::chat::StringIdChatParameter::setDI(), server::zone::objects::tangible::wearables::ArmorObject::setEffectivenessSlice(), server::zone::objects::tangible::TangibleObject::setSliced(), server::zone::objects::scene::variables::StringId::setStringId(), and tangibleObject.
Referenced by handleArmorSlice().
void SlicingSessionImplementation::handleSliceEncumbrance (byte percent) private
Definition at line 622 of file SlicingSessionImplementation.cpp.
References player, server::chat::StringIdChatParameter::setDI(), server::zone::objects::tangible::wearables::ArmorObject::setEncumbranceSlice(), server::zone::objects::tangible::TangibleObject::setSliced(), server::zone::objects::scene::variables::StringId::setStringId(), and tangibleObject.
Referenced by handleArmorSlice().
void SlicingSessionImplementation::handleSliceFailed () private
Definition at line 724 of file SlicingSessionImplementation.cpp.
References endSlicing(), server::zone::managers::gcw::GCWManager::failSecuritySlice(), server::zone::Zone::getGCWManager(), server::zone::objects::scene::SceneObject::getZone(), isBaseSlice(), player, SceneObjectType::PLAYERLOOTCRATE, relockEvent, and tangibleObject.
Referenced by handleMenuSelect().
void SlicingSessionImplementation::handleSliceSpeed (byte percent) private
Definition at line 560 of file SlicingSessionImplementation.cpp.
References player, server::chat::StringIdChatParameter::setDI(), server::zone::objects::tangible::TangibleObject::setSliced(), server::zone::objects::tangible::weapon::WeaponObject::setSpeedSlice(), server::zone::objects::scene::variables::StringId::setStringId(), and tangibleObject.
Referenced by handleWeaponSlice().
void SlicingSessionImplementation::handleUseClamp () private
Definition at line 369 of file SlicingSessionImplementation.cpp.
References SceneObjectType::MOLECULARCLAMP, player, tangibleObject, and usedClamp.
Referenced by handleMenuSelect().
void SlicingSessionImplementation::handleUseFlowAnalyzer () private
Definition at line 399 of file SlicingSessionImplementation.cpp.
References server::zone::objects::tangible::tool::smuggler::SlicingTool::calculateSuccessRate(), firstCable, SceneObjectType::FLOWANALYZER, nodeCable, player, tangibleObject, and usedNode.
Referenced by handleMenuSelect().
void SlicingSessionImplementation::handleWeaponSlice () private
Definition at line 496 of file SlicingSessionImplementation.cpp.
References getSlicingSkill(), handleSliceDamage(), handleSliceSpeed(), player, and tangibleObject.
Referenced by handleSlice().
bool SlicingSessionImplementation::hasArmorUpgradeKit ()
Definition at line 318 of file SlicingSessionImplementation.cpp.
References SceneObjectType::ARMORUPGRADEKIT, player, and tangibleObject.
Referenced by server::zone::objects::player::sessions::SlicingSession::hasArmorUpgradeKit(), and initalizeSlicingMenu().
bool SlicingSessionImplementation::hasPrecisionLaserKnife (bool removeItem = true)
Definition at line 258 of file SlicingSessionImplementation.cpp.
References SceneObjectType::LASERKNIFE, player, tangibleObject, and server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnife::useCharge().
Referenced by handleMenuSelect(), server::zone::objects::player::sessions::SlicingSession::hasPrecisionLaserKnife(), and initalizeSlicingMenu().
bool SlicingSessionImplementation::hasWeaponUpgradeKit ()
Definition at line 289 of file SlicingSessionImplementation.cpp.
References player, tangibleObject, and SceneObjectType::WEAPONUPGRADEKIT.
Referenced by server::zone::objects::player::sessions::SlicingSession::hasWeaponUpgradeKit(), and initalizeSlicingMenu().
void SlicingSessionImplementation::initalizeSlicingMenu (CreatureObject * pl, TangibleObject * obj)
Definition at line 49 of file SlicingSessionImplementation.cpp.
References _this, generateSliceMenu(), server::zone::objects::scene::SceneObject::getSlottedObject(), hasArmorUpgradeKit(), hasPrecisionLaserKnife(), hasWeaponUpgradeKit(), isBaseSlice(), SceneObjectType::MISSIONTERMINAL, player, SceneObjectType::PLAYERLOOTCRATE, SessionFacadeType::SLICING, SuiWindowType::SLICING_MENU, slicingSuiBox, SceneObjectType::STATICLOOTCONTAINER, and tangibleObject.
Referenced by server::zone::objects::player::sessions::SlicingSession::initalizeSlicingMenu().
int SlicingSessionImplementation::initializeSession ()
Definition at line 32 of file SlicingSessionImplementation.cpp.
References baseSlice, cableBlue, cableRed, firstCable, nodeCable, relockEvent, usedClamp, and usedNode.
Referenced by server::zone::objects::player::sessions::SlicingSession::initializeSession(), and SlicingSessionImplementation().
bool SlicingSessionImplementation::isBaseSlice ()
Definition at line 496 of file SlicingSession.cpp.
References baseSlice.
Referenced by getPrefix(), handleSlice(), handleSliceFailed(), initalizeSlicingMenu(), and server::zone::objects::player::sessions::SlicingSession::isBaseSlice().
void SlicingSessionImplementation::lock (bool doLock = true) protected
Definition at line 249 of file SlicingSession.cpp.
References _this.
void SlicingSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 253 of file SlicingSession.cpp.
References _this.
SlicingSessionImplementation::operator const SlicingSession * ()
Definition at line 245 of file SlicingSession.cpp.
void SlicingSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 284 of file SlicingSession.cpp.
References readObjectMember().
bool SlicingSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 303 of file SlicingSession.cpp.
References baseSlice, cableBlue, cableRed, firstCable, nodeCable, player, slicingSuiBox, usedClamp, and usedNode.
Referenced by readObject().
void SlicingSessionImplementation::rlock (bool doLock = true) protected
Definition at line 257 of file SlicingSession.cpp.
References _this.
void SlicingSessionImplementation::runlock (bool doLock = true) protected
Definition at line 273 of file SlicingSession.cpp.
References _this.
void SlicingSessionImplementation::setBaseSlice (bool val)
Definition at line 501 of file SlicingSession.cpp.
References baseSlice.
Referenced by server::zone::objects::player::sessions::SlicingSession::setBaseSlice().
void SlicingSessionImplementation::unlock (bool doLock = true) protected
Definition at line 269 of file SlicingSession.cpp.
References _this.
void SlicingSessionImplementation::useClampFromInventory (SlicingTool * clamp)
Definition at line 347 of file SlicingSessionImplementation.cpp.
References server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::getGameObjectType(), SceneObjectType::MOLECULARCLAMP, player, tangibleObject, and usedClamp.
Referenced by server::zone::objects::player::sessions::SlicingSession::useClampFromInventory().
void SlicingSessionImplementation::wlock (bool doLock = true) protected
Definition at line 261 of file SlicingSession.cpp.
References _this.
void SlicingSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 265 of file SlicingSession.cpp.
References _this.
void SlicingSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 349 of file SlicingSession.cpp.
References writeObjectMembers().
int SlicingSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 356 of file SlicingSession.cpp.
References baseSlice, cableBlue, cableRed, firstCable, nodeCable, player, slicingSuiBox, usedClamp, and usedNode.
Referenced by writeObject().
Friends And Related Function Documentation
friend class SlicingSession friend
Definition at line 248 of file SlicingSession.h.
Member Data Documentation
WeakReference<SlicingSession*> server::zone::objects::player::sessions::SlicingSessionImplementation::_this
Definition at line 214 of file SlicingSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), initalizeSlicingMenu(), lock(), rlock(), runlock(), unlock(), and wlock().
bool server::zone::objects::player::sessions::SlicingSessionImplementation::baseSlice protected
Definition at line 147 of file SlicingSession.h.
Referenced by initializeSession(), isBaseSlice(), readObjectMember(), setBaseSlice(), and writeObjectMembers().
bool server::zone::objects::player::sessions::SlicingSessionImplementation::cableBlue protected
Definition at line 139 of file SlicingSession.h.
Referenced by generateSliceMenu(), getProgress(), handleMenuSelect(), initializeSession(), readObjectMember(), and writeObjectMembers().
bool server::zone::objects::player::sessions::SlicingSessionImplementation::cableRed protected
Definition at line 141 of file SlicingSession.h.
Referenced by generateSliceMenu(), getProgress(), handleMenuSelect(), initializeSession(), readObjectMember(), and writeObjectMembers().
byte server::zone::objects::player::sessions::SlicingSessionImplementation::firstCable protected
Definition at line 135 of file SlicingSession.h.
Referenced by generateSliceMenu(), handleMenuSelect(), handleUseFlowAnalyzer(), initializeSession(), readObjectMember(), and writeObjectMembers().
byte server::zone::objects::player::sessions::SlicingSessionImplementation::nodeCable protected
Definition at line 137 of file SlicingSession.h.
Referenced by generateSliceMenu(), handleUseFlowAnalyzer(), initializeSession(), readObjectMember(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sessions::SlicingSessionImplementation::player protected
Definition at line 127 of file SlicingSession.h.
Referenced by cancelSession(), clearSession(), endSlicing(), generateSliceMenu(), handleArmorSlice(), handleContainerSlice(), handleMenuSelect(), handleSlice(), handleSliceDamage(), handleSliceEffectiveness(), handleSliceEncumbrance(), handleSliceFailed(), handleSliceSpeed(), handleUseClamp(), handleUseFlowAnalyzer(), handleWeaponSlice(), hasArmorUpgradeKit(), hasPrecisionLaserKnife(), hasWeaponUpgradeKit(), initalizeSlicingMenu(), readObjectMember(), useClampFromInventory(), and writeObjectMembers().
Reference<RelockLootContainerEvent* > server::zone::objects::player::sessions::SlicingSessionImplementation::relockEvent protected
Definition at line 133 of file SlicingSession.h.
Referenced by handleContainerSlice(), handleSliceFailed(), and initializeSession().
ManagedReference<SuiListBox* > server::zone::objects::player::sessions::SlicingSessionImplementation::slicingSuiBox protected
Definition at line 131 of file SlicingSession.h.
Referenced by initalizeSlicingMenu(), readObjectMember(), and writeObjectMembers().
ManagedWeakReference<TangibleObject* > server::zone::objects::player::sessions::SlicingSessionImplementation::tangibleObject protected
Definition at line 129 of file SlicingSession.h.
Referenced by cancelSession(), clearSession(), endSlicing(), generateSliceMenu(), getPrefix(), handleArmorSlice(), handleContainerSlice(), handleMenuSelect(), handleSlice(), handleSliceDamage(), handleSliceEffectiveness(), handleSliceEncumbrance(), handleSliceFailed(), handleSliceSpeed(), handleUseClamp(), handleUseFlowAnalyzer(), handleWeaponSlice(), hasArmorUpgradeKit(), hasPrecisionLaserKnife(), hasWeaponUpgradeKit(), initalizeSlicingMenu(), and useClampFromInventory().
bool server::zone::objects::player::sessions::SlicingSessionImplementation::usedClamp protected
Definition at line 145 of file SlicingSession.h.
Referenced by generateSliceMenu(), handleUseClamp(), initializeSession(), readObjectMember(), useClampFromInventory(), and writeObjectMembers().
bool server::zone::objects::player::sessions::SlicingSessionImplementation::usedNode protected
Definition at line 143 of file SlicingSession.h.
Referenced by generateSliceMenu(), handleUseFlowAnalyzer(), initializeSession(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/SlicingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/SlicingSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/SlicingSessionImplementation.cpp