Core3: server::zone::managers::jedi::JediManager Class Reference
server::zone::managers::jedi::JediManager Class Reference
#include <JediManager.h>
Public Member Functions
JediManager ()
~JediManager ()
void loadConfiguration (Lua *luaEngine)
void onPlayerCreated (CreatureObject *creature)
void onPlayerLoggedIn (CreatureObject *creature)
void onPlayerLoggedOut (CreatureObject *creature)
void checkForceStatusCommand (CreatureObject *creature)
String getJediManagerName ()
void setJediManagerName (String name)
void useHolocron (SceneObject *holocron, CreatureObject *creature)
Static Public Attributes
static const int NOJEDIPROGRESSION = 0
static const int HOLOCRONJEDIPROGRESSION = 1
static const int VILLAGEJEDIPROGRESSION = 2
static const int CUSTOMJEDIPROGRESSION = 3
Private Attributes
int jediProgressionType
String jediManagerName
Detailed Description
Singleton class with a common interface for all different Jedi progression systems.
Definition at line 59 of file JediManager.h.
Constructor & Destructor Documentation
JediManager::JediManager ()
Constructor for the Jedi Manager.
Definition at line 48 of file JediManager.cpp.
References jediProgressionType, NOJEDIPROGRESSION, and setJediManagerName().
JediManager::~JediManager ()
Destructor for the Jedi Manager.
Definition at line 53 of file JediManager.cpp.
Member Function Documentation
void JediManager::checkForceStatusCommand (CreatureObject * creature)
Check force status command. Calls the checkForceStatusCommand in the lua manager.
Parameters
creature the creature that performed the command.
Definition at line 119 of file JediManager.cpp.
References getJediManagerName().
String JediManager::getJediManagerName ()
Get the name of the currently active lua jedi manager.
Returns
the name of the currently active lua jedi manager.
Definition at line 57 of file JediManager.cpp.
References jediManagerName.
Referenced by checkForceStatusCommand(), onPlayerCreated(), onPlayerLoggedIn(), onPlayerLoggedOut(), and useHolocron().
void JediManager::loadConfiguration (Lua * luaEngine)
Load the Jedi Manager configuration.
Parameters
luaEngine the lua engine to use for loading the configuration.
Definition at line 71 of file JediManager.cpp.
References CUSTOMJEDIPROGRESSION, HOLOCRONJEDIPROGRESSION, jediProgressionType, setJediManagerName(), and VILLAGEJEDIPROGRESSION.
void JediManager::onPlayerCreated (CreatureObject * creature)
On player created.
Parameters
creature the creature/player that was created.
Definition at line 95 of file JediManager.cpp.
References getJediManagerName().
void JediManager::onPlayerLoggedIn (CreatureObject * creature)
On player logged in.
Parameters
creature the creature/player that logged in.
Definition at line 103 of file JediManager.cpp.
References getJediManagerName().
void JediManager::onPlayerLoggedOut (CreatureObject * creature)
On player logged out.
Parameters
creature the creature/player that logged out.
Definition at line 111 of file JediManager.cpp.
References getJediManagerName().
void JediManager::setJediManagerName (String name)
Set the name of the currently active lua jedi manager.
Parameters
name the name of the currently active lua jedi manager.
Definition at line 65 of file JediManager.cpp.
References jediManagerName.
Referenced by JediManager(), loadConfiguration(), and server::zone::managers::jedi::tests::JediManagerTest::SetUp().
void JediManager::useHolocron (SceneObject * holocron, CreatureObject * creature)
Handle the holocron use messages.
Parameters
holocron pointer to the holocron object.
creature the creature that used the holocron.
Definition at line 127 of file JediManager.cpp.
References getJediManagerName().
Member Data Documentation
const int server::zone::managers::jedi::JediManager::CUSTOMJEDIPROGRESSION = 3 static
Custom defined jedi progression system.
Definition at line 90 of file JediManager.h.
Referenced by loadConfiguration(), and server::zone::managers::jedi::tests::TEST_F().
const int server::zone::managers::jedi::JediManager::HOLOCRONJEDIPROGRESSION = 1 static
Jedi progression through the holocron system, i.e. master five random professions.
Definition at line 80 of file JediManager.h.
Referenced by loadConfiguration(), and server::zone::managers::jedi::tests::TEST_F().
String server::zone::managers::jedi::JediManager::jediManagerName private
The name of the jedi manager class in Lua.
Definition at line 69 of file JediManager.h.
Referenced by getJediManagerName(), and setJediManagerName().
int server::zone::managers::jedi::JediManager::jediProgressionType private
The Jedi progression type currently configured.
Definition at line 64 of file JediManager.h.
Referenced by JediManager(), and loadConfiguration().
const int server::zone::managers::jedi::JediManager::NOJEDIPROGRESSION = 0 static
Jedi progression not available.
Definition at line 75 of file JediManager.h.
Referenced by JediManager(), and server::zone::managers::jedi::tests::TEST_F().
const int server::zone::managers::jedi::JediManager::VILLAGEJEDIPROGRESSION = 2 static
Jedi progression through the village system.
Definition at line 85 of file JediManager.h.
Referenced by loadConfiguration(), and server::zone::managers::jedi::tests::TEST_F().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/jedi/JediManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/jedi/JediManager.cpp