Core3: server::zone::objects::intangible::VehicleControlObserverImplementation Class Reference
server::zone::objects::intangible::VehicleControlObserverImplementation Class Reference
#include <VehicleControlObserver.h>
Public Member Functions
VehicleControlObserverImplementation (VehicleControlDevice *device)
VehicleControlObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const VehicleControlObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< VehicleControlObserver * > _this
Protected Member Functions
virtual ~VehicleControlObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
ManagedWeakReference
< VehicleControlDevice * > vehicleControlDevice
Friends
class VehicleControlObserver
Detailed Description
Definition at line 94 of file VehicleControlObserver.h.
Constructor & Destructor Documentation
VehicleControlObserverImplementation::VehicleControlObserverImplementation (VehicleControlDevice * device)
Definition at line 194 of file VehicleControlObserver.cpp.
References _initializeImplementation(), and vehicleControlDevice.
VehicleControlObserverImplementation::VehicleControlObserverImplementation (DummyConstructorParameter * param)
Definition at line 68 of file VehicleControlObserver.cpp.
References _initializeImplementation().
VehicleControlObserverImplementation::~VehicleControlObserverImplementation () protected virtual
Definition at line 73 of file VehicleControlObserver.cpp.
Member Function Documentation
DistributedObjectStub * VehicleControlObserverImplementation::_getStub ()
Definition at line 93 of file VehicleControlObserver.cpp.
References _this.
void VehicleControlObserverImplementation::_initializeImplementation () protected
Definition at line 80 of file VehicleControlObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by VehicleControlObserverImplementation().
void VehicleControlObserverImplementation::_serializationHelperMethod () protected
Definition at line 129 of file VehicleControlObserver.cpp.
Referenced by _initializeImplementation().
void VehicleControlObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 88 of file VehicleControlObserver.cpp.
References _this.
Referenced by server::zone::objects::intangible::VehicleControlObserver::VehicleControlObserver().
void VehicleControlObserverImplementation::finalize () protected
Definition at line 77 of file VehicleControlObserver.cpp.
void VehicleControlObserverImplementation::lock (bool doLock = true) protected
Definition at line 101 of file VehicleControlObserver.cpp.
References _this.
void VehicleControlObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 105 of file VehicleControlObserver.cpp.
References _this.
int VehicleControlObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 200 of file VehicleControlObserver.cpp.
References ObserverEventType::STARTCOMBAT, and vehicleControlDevice.
Referenced by server::zone::objects::intangible::VehicleControlObserver::notifyObserverEvent().
VehicleControlObserverImplementation::operator const VehicleControlObserver * ()
Definition at line 97 of file VehicleControlObserver.cpp.
void VehicleControlObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 136 of file VehicleControlObserver.cpp.
References readObjectMember().
bool VehicleControlObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 155 of file VehicleControlObserver.cpp.
References vehicleControlDevice.
Referenced by readObject().
void VehicleControlObserverImplementation::rlock (bool doLock = true) protected
Definition at line 109 of file VehicleControlObserver.cpp.
References _this.
void VehicleControlObserverImplementation::runlock (bool doLock = true) protected
Definition at line 125 of file VehicleControlObserver.cpp.
References _this.
void VehicleControlObserverImplementation::unlock (bool doLock = true) protected
Definition at line 121 of file VehicleControlObserver.cpp.
References _this.
void VehicleControlObserverImplementation::wlock (bool doLock = true) protected
Definition at line 113 of file VehicleControlObserver.cpp.
References _this.
void VehicleControlObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 117 of file VehicleControlObserver.cpp.
References _this.
void VehicleControlObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 169 of file VehicleControlObserver.cpp.
References writeObjectMembers().
int VehicleControlObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 176 of file VehicleControlObserver.cpp.
References vehicleControlDevice.
Referenced by writeObject().
Friends And Related Function Documentation
friend class VehicleControlObserver friend
Definition at line 138 of file VehicleControlObserver.h.
Member Data Documentation
WeakReference<VehicleControlObserver*> server::zone::objects::intangible::VehicleControlObserverImplementation::_this
Definition at line 104 of file VehicleControlObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<VehicleControlDevice* > server::zone::objects::intangible::VehicleControlObserverImplementation::vehicleControlDevice private
Definition at line 95 of file VehicleControlObserver.h.
Referenced by notifyObserverEvent(), readObjectMember(), VehicleControlObserverImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/intangible/VehicleControlObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/intangible/VehicleControlObserver.cpp