Core3: server::zone::objects::creature::ai::bt::BehaviorTree Class Reference
server::zone::objects::creature::ai::bt::BehaviorTree Class Reference
#include <BehaviorTree.h>
Public Member Functions
BehaviorTree ()
virtual ~BehaviorTree ()
void start (Behavior *behavior, AiAgent *actor)
void stop (Behavior *behavior, AiAgent *actor)
void tick (AiAgent *actor)
bool step (AiAgent *actor)
Detailed Description
Definition at line 21 of file BehaviorTree.h.
Constructor & Destructor Documentation
BehaviorTree::BehaviorTree ()
Definition at line 12 of file BehaviorTree.cpp.
BehaviorTree::~BehaviorTree () virtual
Definition at line 15 of file BehaviorTree.cpp.
Member Function Documentation
void BehaviorTree::start (Behavior * behavior, AiAgent * actor)
Definition at line 18 of file BehaviorTree.cpp.
References server::zone::objects::creature::AiAgent::addBehaviorToTree().
Referenced by server::zone::objects::creature::ai::bt::SequenceBehavior::observe(), server::zone::objects::creature::ai::bt::SequenceBehavior::onInitialize(), and server::zone::objects::creature::ai::bt::test::TEST_F().
bool BehaviorTree::step (AiAgent * actor)
Definition at line 39 of file BehaviorTree.cpp.
References server::zone::objects::creature::AiAgent::addBehaviorToTree(), server::zone::objects::creature::ai::bt::Behavior::canObserve(), server::zone::objects::creature::AiAgent::getBehaviorStatus(), server::zone::objects::creature::AiAgent::getNextBehaviorFromTree(), server::zone::objects::creature::ai::bt::Behavior::observe(), server::zone::objects::creature::ai::bt::Behavior::RUNNING, and server::zone::objects::creature::ai::bt::Behavior::tick().
Referenced by tick().
void BehaviorTree::stop (Behavior * behavior, AiAgent * actor)
Definition at line 21 of file BehaviorTree.cpp.
References server::zone::objects::creature::ai::bt::Behavior::canObserve(), server::zone::objects::creature::AiAgent::getBehaviorStatus(), server::zone::objects::creature::ai::bt::Behavior::observe(), and server::zone::objects::creature::ai::bt::Behavior::RUNNING.
Referenced by server::zone::objects::creature::ai::bt::SequenceBehavior::observe(), and tick().
void BehaviorTree::tick (AiAgent * actor)
Definition at line 29 of file BehaviorTree.cpp.
References server::zone::objects::creature::AiAgent::addBehaviorToTree(), step(), and stop().
Referenced by server::zone::objects::creature::ai::bt::test::TEST_F().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/bt/BehaviorTree.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/bt/BehaviorTree.cpp