Core3: InvisibleDelayEvent Class Reference
InvisibleDelayEvent Class Reference
#include <InvisibleDelayEvent.h>
Public Member Functions
InvisibleDelayEvent (CreatureObject *pl)
void run ()
Private Attributes
ManagedReference
< CreatureObject * > player
Detailed Description
file InvisibleDelayEvent.h author Polonel date 10.01.2010
Definition at line 60 of file InvisibleDelayEvent.h.
Constructor & Destructor Documentation
InvisibleDelayEvent::InvisibleDelayEvent (CreatureObject * pl) inline
Definition at line 64 of file InvisibleDelayEvent.h.
References player.
Member Function Documentation
void InvisibleDelayEvent::run () inline
Definition at line 68 of file InvisibleDelayEvent.h.
References server::zone::objects::player::PlayerObject::isLoggingOut(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::notifyDissapear(), server::zone::objects::scene::SceneObject::notifyInsert(), and player.
Member Data Documentation
ManagedReference<CreatureObject*> InvisibleDelayEvent::player private
Definition at line 61 of file InvisibleDelayEvent.h.
Referenced by InvisibleDelayEvent(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/events/InvisibleDelayEvent.h