Core3: ClearDefenderListsTask Class Reference
ClearDefenderListsTask Class Reference
#include <ClearDefenderListsTask.h>
Public Member Functions
ClearDefenderListsTask (const DeltaVector< ManagedReference< SceneObject * > > &list, TangibleObject *tano)
void run ()
Private Attributes
DeltaVector< ManagedReference
< SceneObject * > > defenderList
ManagedReference
< TangibleObject * > tangibleObject
Detailed Description
Definition at line 13 of file ClearDefenderListsTask.h.
Constructor & Destructor Documentation
ClearDefenderListsTask::ClearDefenderListsTask (const DeltaVector< ManagedReference< SceneObject * > > & list, TangibleObject * tano) inline
Definition at line 17 of file ClearDefenderListsTask.h.
Member Function Documentation
void ClearDefenderListsTask::run () inline
Definition at line 22 of file ClearDefenderListsTask.h.
References defenderList, server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::objects::scene::variables::DeltaVector< E >::size(), and tangibleObject.
Member Data Documentation
DeltaVector<ManagedReference<SceneObject* > > ClearDefenderListsTask::defenderList private
Definition at line 14 of file ClearDefenderListsTask.h.
Referenced by run().
ManagedReference<TangibleObject*> ClearDefenderListsTask::tangibleObject private
Definition at line 15 of file ClearDefenderListsTask.h.
Referenced by run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/tasks/ClearDefenderListsTask.h