Core3: SetFactionStandingCommand Class Reference
SetFactionStandingCommand Class Reference
#include <SetFactionStandingCommand.h>
Public Member Functions
SetFactionStandingCommand (const String &name, ZoneProcessServer *server)
void sendInvalidParameterMessage (CreatureObject *creature)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file SetFactionStandingCommand.h.
Constructor & Destructor Documentation
SetFactionStandingCommand::SetFactionStandingCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file SetFactionStandingCommand.h.
Member Function Documentation
int SetFactionStandingCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 62 of file SetFactionStandingCommand.h.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), sendInvalidParameterMessage(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
void SetFactionStandingCommand::sendInvalidParameterMessage (CreatureObject * creature) inline
Definition at line 58 of file SetFactionStandingCommand.h.
References server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/SetFactionStandingCommand.h