Core3: PowerRegulatorMenuComponent Class Reference
PowerRegulatorMenuComponent Class Reference
#include <PowerRegulatorMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file PowerRegulatorMenuComponent.h.
Member Function Documentation
void PowerRegulatorMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from ObjectMenuComponent.
Definition at line 22 of file PowerRegulatorMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::managers::gcw::GCWManager::canUseTerminals(), SceneObjectType::FACTIONBUILDING, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::Zone::getGCWManager(), server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::managers::gcw::GCWManager::isDNASampled(), server::zone::objects::creature::CreatureObject::isIncapacitated(), and server::zone::managers::gcw::GCWManager::isPowerOverloaded().
int PowerRegulatorMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from ObjectMenuComponent.
Definition at line 48 of file PowerRegulatorMenuComponent.cpp.
References server::zone::managers::gcw::GCWManager::canUseTerminals(), SceneObjectType::FACTIONBUILDING, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::Zone::getGCWManager(), server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::managers::gcw::GCWManager::sendPowerRegulatorControls(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/terminal/components/PowerRegulatorMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/terminal/components/PowerRegulatorMenuComponent.cpp