Core3: server::zone::objects::tangible::consumable::DelayedBuffObserverImplementation Class Reference
server::zone::objects::tangible::consumable::DelayedBuffObserverImplementation Class Reference
#include <DelayedBuffObserver.h>
Public Member Functions
DelayedBuffObserverImplementation (DelayedBuff *b)
DelayedBuffObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const DelayedBuffObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< DelayedBuffObserver * > _this
Protected Member Functions
virtual ~DelayedBuffObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< DelayedBuff * > buff
Friends
class DelayedBuffObserver
Detailed Description
Definition at line 103 of file DelayedBuffObserver.h.
Constructor & Destructor Documentation
DelayedBuffObserverImplementation::DelayedBuffObserverImplementation (DelayedBuff * b)
Definition at line 196 of file DelayedBuffObserver.cpp.
References _initializeImplementation(), and buff.
DelayedBuffObserverImplementation::DelayedBuffObserverImplementation (DummyConstructorParameter * param)
Definition at line 70 of file DelayedBuffObserver.cpp.
References _initializeImplementation().
DelayedBuffObserverImplementation::~DelayedBuffObserverImplementation () protected virtual
Definition at line 75 of file DelayedBuffObserver.cpp.
Member Function Documentation
DistributedObjectStub * DelayedBuffObserverImplementation::_getStub ()
Definition at line 95 of file DelayedBuffObserver.cpp.
References _this.
void DelayedBuffObserverImplementation::_initializeImplementation () protected
Definition at line 82 of file DelayedBuffObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by DelayedBuffObserverImplementation().
void DelayedBuffObserverImplementation::_serializationHelperMethod () protected
Definition at line 131 of file DelayedBuffObserver.cpp.
Referenced by _initializeImplementation().
void DelayedBuffObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 90 of file DelayedBuffObserver.cpp.
References _this.
Referenced by server::zone::objects::tangible::consumable::DelayedBuffObserver::DelayedBuffObserver().
void DelayedBuffObserverImplementation::finalize () protected
Definition at line 79 of file DelayedBuffObserver.cpp.
void DelayedBuffObserverImplementation::lock (bool doLock = true) protected
Definition at line 103 of file DelayedBuffObserver.cpp.
References _this.
void DelayedBuffObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 107 of file DelayedBuffObserver.cpp.
References _this.
int DelayedBuffObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 50 of file DelayedBuffObserverImplementation.cpp.
References buff.
Referenced by server::zone::objects::tangible::consumable::DelayedBuffObserver::notifyObserverEvent().
DelayedBuffObserverImplementation::operator const DelayedBuffObserver * ()
Definition at line 99 of file DelayedBuffObserver.cpp.
void DelayedBuffObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 138 of file DelayedBuffObserver.cpp.
References readObjectMember().
bool DelayedBuffObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 157 of file DelayedBuffObserver.cpp.
References buff.
Referenced by readObject().
void DelayedBuffObserverImplementation::rlock (bool doLock = true) protected
Definition at line 111 of file DelayedBuffObserver.cpp.
References _this.
void DelayedBuffObserverImplementation::runlock (bool doLock = true) protected
Definition at line 127 of file DelayedBuffObserver.cpp.
References _this.
void DelayedBuffObserverImplementation::unlock (bool doLock = true) protected
Definition at line 123 of file DelayedBuffObserver.cpp.
References _this.
void DelayedBuffObserverImplementation::wlock (bool doLock = true) protected
Definition at line 115 of file DelayedBuffObserver.cpp.
References _this.
void DelayedBuffObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 119 of file DelayedBuffObserver.cpp.
References _this.
void DelayedBuffObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 171 of file DelayedBuffObserver.cpp.
References writeObjectMembers().
int DelayedBuffObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 178 of file DelayedBuffObserver.cpp.
References buff.
Referenced by writeObject().
Friends And Related Function Documentation
friend class DelayedBuffObserver friend
Definition at line 148 of file DelayedBuffObserver.h.
Member Data Documentation
WeakReference<DelayedBuffObserver*> server::zone::objects::tangible::consumable::DelayedBuffObserverImplementation::_this
Definition at line 114 of file DelayedBuffObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<DelayedBuff* > server::zone::objects::tangible::consumable::DelayedBuffObserverImplementation::buff protected
Definition at line 105 of file DelayedBuffObserver.h.
Referenced by DelayedBuffObserverImplementation(), notifyObserverEvent(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/consumable/DelayedBuffObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/consumable/DelayedBuffObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/consumable/DelayedBuffObserverImplementation.cpp