Core3: TargaBitmap Class Reference
TargaBitmap Class Reference
#include <TargaBitmap.h>
Public Member Functions
TargaBitmap ()
~TargaBitmap ()
void readObject (ObjectInputStream *stream)
int getWidth ()
int getHeight ()
unsigned char getData (int offset)
Protected Attributes
TargaHeader header
TargaPixel ** pixelData
Detailed Description
Definition at line 74 of file TargaBitmap.h.
Constructor & Destructor Documentation
TargaBitmap::TargaBitmap ()
Definition at line 70 of file TargaBitmap.cpp.
References pixelData.
TargaBitmap::~TargaBitmap ()
Definition at line 74 of file TargaBitmap.cpp.
References header, TargaHeader::height, pixelData, and TargaHeader::width.
Member Function Documentation
unsigned char TargaBitmap::getData (int offset)
Definition at line 134 of file TargaBitmap.cpp.
References header, TargaHeader::height, pixelData, and TargaHeader::width.
Referenced by FilterBitmap::process().
int TargaBitmap::getHeight () inline
Definition at line 90 of file TargaBitmap.h.
References header, and TargaHeader::height.
Referenced by FilterBitmap::process().
int TargaBitmap::getWidth () inline
Definition at line 86 of file TargaBitmap.h.
References header, and TargaHeader::width.
Referenced by FilterBitmap::process().
void TargaBitmap::readObject (ObjectInputStream * stream)
Definition at line 87 of file TargaBitmap.cpp.
References TargaHeader::bitsperpixel, TargaPixel::clear(), TargaHeader::colourmaplength, TargaHeader::colourmaptype, TargaHeader::datatypecode, header, TargaHeader::height, TargaHeader::idlength, pixelData, TargaPixel::read(), TargaHeader::readData(), and TargaHeader::width.
Referenced by BitMapFamily::parseFromIffStream().
Member Data Documentation
TargaHeader TargaBitmap::header protected
Definition at line 76 of file TargaBitmap.h.
Referenced by getData(), getHeight(), getWidth(), readObject(), and ~TargaBitmap().
TargaPixel** TargaBitmap::pixelData protected
Definition at line 77 of file TargaBitmap.h.
Referenced by getData(), readObject(), TargaBitmap(), and ~TargaBitmap().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/TargaBitmap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/TargaBitmap.cpp