Core3: SaberInventoryContainerComponent Class Reference
SaberInventoryContainerComponent Class Reference
#include <SaberInventoryContainerComponent.h>
Public Member Functions
virtual int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Public Member Functions inherited from ContainerComponent
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
virtual bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
Detailed Description
Definition at line 33 of file SaberInventoryContainerComponent.h.
Member Function Documentation
int SaberInventoryContainerComponent::canAddObject (SceneObject * sceneObject, SceneObject * object, int containmentType, String & errorDescription) virtual
Evaluates if this object has the necessary free slots to be able to add the specified SceneObject
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be checked
error error string that the player will receive on error
Returns
returns 0 on success, or error code
Reimplemented from ContainerComponent.
Definition at line 53 of file SaberInventoryContainerComponent.cpp.
References TransferErrorCode::CONTAINERFULL, server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponent::getColor(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjects(), server::zone::objects::scene::SceneObject::getContainerVolumeLimit(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponent::getOwner(), TransferErrorCode::INVALIDTYPE, and server::zone::objects::scene::SceneObject::isLightsaberCrystalObject().
int SaberInventoryContainerComponent::notifyObjectInserted (SceneObject * sceneObject, SceneObject * object) virtual
Is called when this object has been inserted with an object
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 104 of file SaberInventoryContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::getParent(), and server::zone::objects::scene::SceneObject::notifyObjectInserted().
int SaberInventoryContainerComponent::notifyObjectRemoved (SceneObject * sceneObject, SceneObject * object, SceneObject * destination) virtual
Is called when an object was removed
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 133 of file SaberInventoryContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::getParent(), and server::zone::objects::scene::SceneObject::notifyObjectRemoved().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/SaberInventoryContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/SaberInventoryContainerComponent.cpp