Core3: server::zone::objects::player::sessions::admin::PlayerManagementSession Class Reference
server::zone::objects::player::sessions::admin::PlayerManagementSession Class Reference
#include <PlayerManagementSession.h>
Public Member Functions
PlayerManagementSession (Account *account, CreatureObject *adm)
int initializeSession ()
int cancelSession ()
int clearSession ()
void addAccountSui (SuiListBox *box)
void ban (const int tablevel, unsigned const int galaxy, const String &gname, const String &name)
void getPlayerInfo (const int tablevel, const String &firstName)
void sendAccountInfo ()
void sendBanDuration ()
void parseBanDuration (const String &duration)
void sendBanReason (bool unban=false)
void setBanReason (const String &reason)
void showBanSummary ()
void showUnbanSummary ()
void completeBan ()
String getBanDuration (unsigned int timestamp)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
PlayerManagementSession (DummyConstructorParameter *param)
virtual ~PlayerManagementSession ()
Friends
class PlayerManagementSessionHelper
Detailed Description
Definition at line 107 of file PlayerManagementSession.h.
Constructor & Destructor Documentation
PlayerManagementSession::PlayerManagementSession (Account * account, CreatureObject * adm)
Definition at line 23 of file PlayerManagementSession.cpp.
References server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::_setStub().
PlayerManagementSession::PlayerManagementSession (DummyConstructorParameter * param) protected
Definition at line 30 of file PlayerManagementSession.cpp.
PlayerManagementSession::~PlayerManagementSession () protected virtual
Definition at line 34 of file PlayerManagementSession.cpp.
Member Function Documentation
DistributedObjectServant * PlayerManagementSession::_getImplementation ()
Definition at line 247 of file PlayerManagementSession.cpp.
Referenced by addAccountSui(), ban(), cancelSession(), clearSession(), completeBan(), getBanDuration(), getPlayerInfo(), initializeSession(), parseBanDuration(), sendAccountInfo(), sendBanDuration(), sendBanReason(), setBanReason(), showBanSummary(), and showUnbanSummary().
DistributedObjectServant * PlayerManagementSession::_getImplementationForRead ()
Definition at line 253 of file PlayerManagementSession.cpp.
void PlayerManagementSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 257 of file PlayerManagementSession.cpp.
void PlayerManagementSession::addAccountSui (SuiListBox * box)
Definition at line 78 of file PlayerManagementSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::addAccountSui(), and RPC_ADDACCOUNTSUI__SUILISTBOX_.
void PlayerManagementSession::ban (const int tablevel, unsigned const int galaxy, const String & gname, const String & name)
Definition at line 92 of file PlayerManagementSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::ban(), and RPC_BAN__INT_INT_STRING_STRING_.
int PlayerManagementSession::cancelSession ()
Definition at line 52 of file PlayerManagementSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
int PlayerManagementSession::clearSession ()
Definition at line 65 of file PlayerManagementSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
void PlayerManagementSession::completeBan ()
Definition at line 218 of file PlayerManagementSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::completeBan(), and RPC_COMPLETEBAN__.
String PlayerManagementSession::getBanDuration (unsigned int timestamp)
Definition at line 231 of file PlayerManagementSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::getBanDuration(), and RPC_GETBANDURATION__INT_.
void PlayerManagementSession::getPlayerInfo (const int tablevel, const String & firstName)
Definition at line 109 of file PlayerManagementSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::getPlayerInfo(), and RPC_GETPLAYERINFO__INT_STRING_.
int PlayerManagementSession::initializeSession ()
Definition at line 39 of file PlayerManagementSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
void PlayerManagementSession::parseBanDuration (const String & duration)
Definition at line 150 of file PlayerManagementSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::parseBanDuration(), and RPC_PARSEBANDURATION__STRING_.
void PlayerManagementSession::sendAccountInfo ()
Definition at line 124 of file PlayerManagementSession.cpp.
References _getImplementation(), RPC_SENDACCOUNTINFO__, and server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::sendAccountInfo().
void PlayerManagementSession::sendBanDuration ()
Definition at line 137 of file PlayerManagementSession.cpp.
References _getImplementation(), RPC_SENDBANDURATION__, and server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::sendBanDuration().
void PlayerManagementSession::sendBanReason (bool unban = false)
Definition at line 164 of file PlayerManagementSession.cpp.
References _getImplementation(), RPC_SENDBANREASON__BOOL_, and server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::sendBanReason().
void PlayerManagementSession::setBanReason (const String & reason)
Definition at line 178 of file PlayerManagementSession.cpp.
References _getImplementation(), RPC_SETBANREASON__STRING_, and server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::setBanReason().
void PlayerManagementSession::showBanSummary ()
Definition at line 192 of file PlayerManagementSession.cpp.
References _getImplementation(), RPC_SHOWBANSUMMARY__, and server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::showBanSummary().
void PlayerManagementSession::showUnbanSummary ()
Definition at line 205 of file PlayerManagementSession.cpp.
References _getImplementation(), RPC_SHOWUNBANSUMMARY__, and server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::showUnbanSummary().
Friends And Related Function Documentation
friend class PlayerManagementSessionHelper friend
Definition at line 151 of file PlayerManagementSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/admin/PlayerManagementSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/admin/PlayerManagementSession.cpp