Core3: server::zone::objects::player::sessions::PlaceStructureSession Class Reference
server::zone::objects::player::sessions::PlaceStructureSession Class Reference
#include <PlaceStructureSession.h>
Public Member Functions
PlaceStructureSession (CreatureObject *creature, StructureDeed *deed)
int initializeSession ()
void placeTemporaryNoBuildZone (SharedStructureObjectTemplate *serverTemplate)
void removeTemporaryNoBuildZone ()
int constructStructure (float x, float y, int angle)
int completeSession ()
int cancelSession ()
int clearSession ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
PlaceStructureSession (DummyConstructorParameter *param)
virtual ~PlaceStructureSession ()
Friends
class PlaceStructureSessionHelper
Detailed Description
Definition at line 110 of file PlaceStructureSession.h.
Constructor & Destructor Documentation
PlaceStructureSession::PlaceStructureSession (CreatureObject * creature, StructureDeed * deed)
Definition at line 25 of file PlaceStructureSession.cpp.
References server::zone::objects::player::sessions::PlaceStructureSessionImplementation::_setStub().
PlaceStructureSession::PlaceStructureSession (DummyConstructorParameter * param) protected
Definition at line 32 of file PlaceStructureSession.cpp.
PlaceStructureSession::~PlaceStructureSession () protected virtual
Definition at line 36 of file PlaceStructureSession.cpp.
Member Function Documentation
DistributedObjectServant * PlaceStructureSession::_getImplementation ()
Definition at line 131 of file PlaceStructureSession.cpp.
Referenced by cancelSession(), clearSession(), completeSession(), constructStructure(), initializeSession(), placeTemporaryNoBuildZone(), and removeTemporaryNoBuildZone().
DistributedObjectServant * PlaceStructureSession::_getImplementationForRead ()
Definition at line 137 of file PlaceStructureSession.cpp.
void PlaceStructureSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 141 of file PlaceStructureSession.cpp.
int PlaceStructureSession::cancelSession ()
Definition at line 105 of file PlaceStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::PlaceStructureSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
int PlaceStructureSession::clearSession ()
Definition at line 118 of file PlaceStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::PlaceStructureSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
int PlaceStructureSession::completeSession ()
Definition at line 92 of file PlaceStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::PlaceStructureSessionImplementation::completeSession(), and RPC_COMPLETESESSION__.
Referenced by StructureConstructionCompleteTask::run().
int PlaceStructureSession::constructStructure (float x, float y, int angle)
Definition at line 76 of file PlaceStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::PlaceStructureSessionImplementation::constructStructure(), and RPC_CONSTRUCTSTRUCTURE__FLOAT_FLOAT_INT_.
int PlaceStructureSession::initializeSession ()
Definition at line 41 of file PlaceStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::PlaceStructureSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
void PlaceStructureSession::placeTemporaryNoBuildZone (SharedStructureObjectTemplate * serverTemplate)
Definition at line 54 of file PlaceStructureSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::PlaceStructureSessionImplementation::placeTemporaryNoBuildZone().
void PlaceStructureSession::removeTemporaryNoBuildZone ()
Definition at line 63 of file PlaceStructureSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::PlaceStructureSessionImplementation::removeTemporaryNoBuildZone(), and RPC_REMOVETEMPORARYNOBUILDZONE__.
Friends And Related Function Documentation
friend class PlaceStructureSessionHelper friend
Definition at line 138 of file PlaceStructureSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/PlaceStructureSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/PlaceStructureSession.cpp