Core3: ThrowGrenadeMenuComponent Class Reference
ThrowGrenadeMenuComponent Class Reference
#include <ThrowGrenadeMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file ThrowGrenadeMenuComponent.h.
Member Function Documentation
void ThrowGrenadeMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from WeaponObjectMenuComponent.
Definition at line 14 of file ThrowGrenadeMenuComponent.cpp.
References WeaponObjectMenuComponent::fillObjectMenuResponse(), and server::zone::objects::scene::SceneObject::isTangibleObject().
int ThrowGrenadeMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from WeaponObjectMenuComponent.
Definition at line 21 of file ThrowGrenadeMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getZoneServer(), WeaponObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::scene::SceneObject::isASubChildOf(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::isTangibleObject(), and server::zone::objects::creature::CreatureObject::sendExecuteConsoleCommand().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/ThrowGrenadeMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/ThrowGrenadeMenuComponent.cpp