Core3: CreatureObjectMessage6 Class Reference
CreatureObjectMessage6 Class Reference
#include <CreatureObjectMessage6.h>
Public Member Functions
CreatureObjectMessage6 (CreatureObject *creo)
void insertEquipmentList (CreatureObject *creo)
Public Member Functions inherited from TangibleObjectMessage6
TangibleObjectMessage6 (TangibleObject *tano, uint32 objType=0x54414E4F, uint16 opcnt=0x02)
void insertDefenders (TangibleObject *tano)
Public Member Functions inherited from BaseLineMessage
BaseLineMessage (uint64 oid, uint32 name, uint8 type, uint16 opcnt)
uint32 generateRandomObjectCRC ()
void setSize ()
void insertStringId (StringId *id)
void insertCustomName (const UnicodeString &name)
Detailed Description
Definition at line 54 of file CreatureObjectMessage6.h.
Constructor & Destructor Documentation
CreatureObjectMessage6::CreatureObjectMessage6 (CreatureObject * creo) inline
Definition at line 56 of file CreatureObjectMessage6.h.
References server::zone::objects::creature::CreatureObject::getFrozen(), server::zone::objects::creature::CreatureObject::getGroupID(), server::zone::objects::creature::CreatureObject::getGroupInviteCounter(), server::zone::objects::creature::CreatureObject::getGroupInviterID(), server::zone::objects::creature::CreatureObject::getGuildID(), server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::creature::CreatureObject::getInstrumentID(), server::zone::objects::tangible::TangibleObject::getLevel(), server::zone::objects::creature::CreatureObject::getMaxHAM(), server::zone::objects::creature::CreatureObject::getMoodID(), server::zone::objects::creature::CreatureObject::getMoodString(), server::zone::objects::creature::CreatureObject::getPerformanceAnimation(), server::zone::objects::creature::CreatureObject::getPerformanceCounter(), server::zone::objects::creature::CreatureObject::getTargetID(), server::zone::objects::creature::CreatureObject::getWeaponID(), insertEquipmentList(), server::zone::objects::scene::variables::DeltaVector< E >::insertToMessage(), and BaseLineMessage::setSize().
Member Function Documentation
void CreatureObjectMessage6::insertEquipmentList (CreatureObject * creo) inline
Definition at line 87 of file CreatureObjectMessage6.h.
References server::zone::objects::creature::CreatureObject::getWearablesDeltaVector(), and server::zone::objects::scene::variables::DeltaVector< E >::insertToMessage().
Referenced by CreatureObjectMessage6().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/creature/CreatureObjectMessage6.h