Core3: DeedTemplate Class Reference
DeedTemplate Class Reference
#include <DeedTemplate.h>
Public Member Functions
DeedTemplate ()
~DeedTemplate ()
void readObject (LuaObject *templateData)
String & getGeneratedObjectTemplate ()
Public Member Functions inherited from SharedTangibleObjectTemplate
SharedTangibleObjectTemplate ()
~SharedTangibleObjectTemplate ()
void readObject (IffStream *iffStream)
void parseFileData (IffStream *str)
void parseVariableData (const String &varName, Chunk *data)
void parseVariableData (const String &varName, LuaObject *data)
int getMaxCondition () const
uint32 getOptionsBitmask () const
uint32 getPvpStatusBitmask () const
void setMaxCondition (int maxCondition)
void setOptionsBitmask (uint32 optionsBitmask)
void setPvpStatusBitmask (uint32 pvpStatusBitmask)
Vector< String > getCertificationsRequired () const
int getLevel () const
int getUseCount () const
int getFactoryCrateSize () const
uint16 getPlayerUseMask () const
int getFaction () const
StructureFootprint * getStructureFootprint () const
bool getTargetable () const
void setCertificationsRequired (Vector< String > certificationsRequired)
void setPlayerUseMask (uint16 playerUseMask)
void setTargetable (bool targetable)
bool getSliceable () const
Vector< short > * getNumberExperimentalProperties ()
Vector< String > * getExperimentalProperties ()
Vector< short > * getExperimentalWeights ()
Vector< String > * getExperimentalGroupTitles ()
Vector< String > * getExperimentalSubGroupTitles ()
Vector< float > * getExperimentalMin ()
Vector< float > * getExperimentalMax ()
Vector< short > * getExperimentalPrecision ()
Vector< uint32 > * getPlayerRaces ()
Vector< Reference
< ResourceWeight * > > * getResourceWeights ()
VectorMap< String, int > * getSkillMods ()
int getSkillMod (const String &mod)
bool isSharedTangibleObjectTemplate ()
Public Member Functions inherited from server::zone::templates::SharedObjectTemplate
SharedObjectTemplate ()
virtual ~SharedObjectTemplate ()
void parseVariableData (const String &varName, Chunk *data)
void parseVariableData (const String &varName, LuaObject *templateData)
void loadDerv (IffStream *iffStream)
void parseFileData (IffStream *iffStream)
bool isDerivedFrom (const String &iffPath, bool includeSelf=true)
String getAppearanceFilename () const
float getClearFloraRadius () const
String getClientDataFile () const
int getCollisionActionBlockFlags () const
int getCollisionActionFlags () const
int getCollisionActionPassFlags () const
int getCollisionMaterialBlockFlags () const
int getCollisionMaterialFlags () const
int getCollisionMaterialPassFlags () const
int getContainerType () const
int getContainerVolumeLimit () const
String getDetailedDescription ()
int getGameObjectType () const
int getClientGameObjectType () const
float getLocationReservationRadius () const
String getLookAtText () const
float getNoBuildRadius () const
String getObjectName () const
bool getOnlyVisibleInTools () const
String getPortalLayoutFilename () const
PortalLayout * getPortalLayout ()
AppearanceTemplate * getAppearanceTemplate ()
Vector< String > * getArrangementDescriptors ()
void addDerivedFile (const String &name)
float getMinScale ()
float getMaxScale ()
bool isNoTrade ()
float getScaleThresholdBeforeExtentTest () const
bool getSendToClient () const
Vector< String > * getSlotDescriptors ()
bool getSnapToTerrain () const
int getSurfaceType () const
String getTintPallete () const
int getTotalCellNumber () const
uint32 getClientObjectCRC () const
String getClientTemplateFileName ()
uint32 getServerObjectCRC ()
String getFullTemplateString ()
String getDataObjectComponent ()
String getTemplateFileName ()
SceneObjectComponent * getContainerComponent ()
String getZoneComponent ()
SceneObjectComponent * getObjectMenuComponent ()
String getAttributeListComponent ()
PlanetMapCategory * getPlanetMapCategory () const
PlanetMapCategory * getPlanetMapSubCategory () const
bool isAutoRegistering ()
int getChildObjectsSize ()
ChildObject * getChildObject (int idx)
bool hasInheritPermissionsFromParent ()
HashTable< uint32, uint32 > * getGroupPermissions ()
bool hasArrangementDescriptor (String s)
void setAppearanceFilename (String appearanceFilename)
void setClearFloraRadius (float clearFloraRadius)
void setClientDataFile (String clientDataFile)
void setCollisionActionBlockFlags (int collisionActionBlockFlags)
void setCollisionActionFlags (int collisionActionFlags)
void setCollisionActionPassFlags (int collisionActionPassFlags)
void setCollisionMaterialBlockFlags (int collisionMaterialBlockFlags)
void setCollisionMaterialFlags (int collisionMaterialFlags)
void setCollisionMaterialPassFlags (int collisionMaterialPassFlags)
void setContainerType (int containerType)
void setContainerVolumeLimit (int containerVolumeLimit)
void setDetailedDescription (String detailedDescription)
void setGameObjectType (int gameObjectType)
void setLocationReservationRadius (float locationReservationRadius)
void setLookAtText (String lookAtText)
void setNoBuildRadius (float noBuildRadius)
void setObjectName (String objectName)
void setOnlyVisibleInTools (bool onlyVisibleInTools)
void setPortalLayoutFilename (String portalLayoutFilename)
void setScale (float scale)
void setScaleThresholdBeforeExtentTest (float scaleThresholdBeforeExtentTest)
void setSendToClient (bool sendToClient)
void setSnapToTerrain (bool snapToTerrain)
void setSurfaceType (int surfaceType)
void setTintPallete (String tintPallete)
void setTotalCellNumber (int totalCellNumber)
void setFullTemplateString (const String &str)
void setTemplateFileName (const String &str)
virtual bool isArmorObjectTemplate ()
virtual bool isSharedBuildingObjectTemplate ()
virtual bool isSharedInstallationObjectTemplate ()
virtual bool isMissionTerminalTemplate ()
virtual bool isGamblingTerminalTemplate ()
virtual bool isFireworkObjectTemplate ()
virtual bool isCloningBuildingObjectTemplate ()
virtual bool isHospitalBuildingObjectTemplate ()
virtual bool isRecreationBuildingObjectTemplate ()
virtual bool isNonPlayerCreatureObjectTemplate ()
virtual bool isStimPackTemplate ()
virtual bool isStatePackTemplate ()
virtual bool isRangedStimPackTemplate ()
virtual bool isEnhancePackTemplate ()
virtual bool isCurePackTemplate ()
virtual bool isDotPackTemplate ()
virtual bool isWoundPackTemplate ()
virtual bool isSkillBuffTemplate ()
virtual bool isLairObjectTemplate ()
virtual bool isElevatorTerminalTemplate ()
virtual bool isInstrumentObjectTemplate ()
virtual bool isCampKitTemplate ()
virtual bool isCamoKitTemplate ()
virtual bool isCampStructureTemplate ()
virtual bool isDiceTemplate ()
virtual bool isVendorCreatureTemplate ()
virtual bool isCreatureHabitatTemplate ()
virtual bool isRepairToolTemplate ()
virtual bool isRobeObjectTemplate ()
virtual bool isLightsaberCrystalTemplate ()
virtual bool isShipChassisTemplate ()
virtual bool isShipDeedTemplate ()
virtual bool isRecycleToolTemplate ()
virtual bool isVehicleCustomKitTemplate ()
virtual bool isDnaSampleTemplate ()
virtual bool isPetDeedTemplate ()
Public Member Functions inherited from LuaTemplate
virtual ~LuaTemplate ()
Public Member Functions inherited from TemplateData
virtual ~TemplateData ()
Public Member Functions inherited from IffTemplate
virtual ~IffTemplate ()
Private Attributes
String generatedObjectTemplate
Additional Inherited Members
Static Public Member Functions inherited from server::zone::templates::SharedObjectTemplate
static String getType (int type)
Static Public Attributes inherited from server::zone::templates::SharedObjectTemplate
static const int SHOT = 'SHOT'
static const int STOT = 'STOT'
static const int SBMK = 'SBMK'
static const int SBOT = 'SBOT'
static const int STAT = 'STAT'
static const int SIOT = 'SIOT'
static const int CCLT = 'CCLT'
static const int SCOU = 'SCOU'
static const int SDSC = 'SDSC'
static const int SFOT = 'SFOT'
static const int SGRP = 'SGRP'
static const int SITN = 'SITN'
static const int SGLD = 'SGLD'
static const int SJED = 'SJED'
static const int SMSC = 'SMSC'
static const int SMSO = 'SMSO'
static const int SMSD = 'SMSD'
static const int SMLE = 'SMLE'
static const int SPLY = 'SPLY'
static const int RCCT = 'RCCT'
static const int SSHP = 'SSHP'
static const int SUNI = 'SUNI'
static const int SWAY = 'SWAY'
static const int STOK = 'STOK'
static const int SWOT = 'SWOT'
static const int SCNC = 'SCNC'
static const int SCOT = 'SCOT'
static const int CHARACTERBUILDERTERMINAL = 0x4000001
static const int SURVEYTOOL = 0x4000002
static const int RESOURCESPAWN = 0x4000003
static const int RESOURCECONTAINER = 0x4000004
static const int ARMOROBJECT = 0x4000005
static const int DEED = 0x4000006
static const int CRAFTINGTOOL = 0x4000007
static const int CRAFTINGSTATION = 0x4000008
static const int MISSIONTERMINAL = 0x4000009
static const int CLONINGBUILDING = 0x400000A
static const int DRAFTSCHEMATIC = 0x400000B
static const int NPCCREATURE = 0x400000C
static const int LAIRTEMPLATE = 0x400000D
static const int FACTORY = 0x400000E
static const int STIMPACK = 0x400000F
static const int RANGEDSTIMPACK = 0x4000010
static const int ENHANCEPACK = 0x4000011
static const int CUREPACK = 0x4000012
static const int DOTPACK = 0x4000013
static const int WOUNDPACK = 0x4000014
static const int STATEPACK = 0x4000015
static const int CONSUMABLE = 0x4000016
static const int ELEVATORTERMINAL = 0x4000017
static const int GAMBLINGTERMINAL = 0x4000018
static const int LOOTKIT = 0x4000019
static const int INSTRUMENT = 0x400001A
static const int FIREWORK = 0x400001B
static const int VEHICLEDEED = 0x400001C
static const int CAMPKIT = 0x400001D
static const int PLAYERCREATURE = 0x400001E
static const int SLICINGTOOL = 0x400001F
static const int CONTAINER = 0x4000020
static const int VENDORCREATURE = 0x4000021
static const int LOOTSCHEMATIC = 0x4000022
static const int CAMPSTRUCTURE = 0x4000023
static const int HOSPITALBUILDING = 0x4000024
static const int RECREATIONBUILDING = 0x4000025
static const int TRAP = 0x4000026
static const int STRUCTUREDEED = 0x4000027
static const int CAMOKIT = 0x4000028
static const int POWERUP = 0x4000029
static const int DICE = 0x4000030
static const int LIVESAMPLE = 0x4000031
static const int CREATUREHABITAT = 0x4000032
static const int REPAIRTOOL = 0x4000033
static const int ROBEOBJECT = 0x4000034
static const int LIGHTSABERCRYSTAL = 0x4000035
static const int SHIPCHASSIS = 0x4000036
static const int SHIPDEED = 0x4000037
static const int RECYCLETOOL = 0x4000038
static const int DNASAMPLE = 0x4000039
static const int PETDEED = 0x4000040
static const int VEHICLECUSTOMKIT = 0x4000041
static const int SKILLBUFF = 0x4000042
Protected Attributes inherited from SharedTangibleObjectTemplate
Reference< StructureFootprint * > structureFootprint
BoolParam targetable
uint16 playerUseMask
int level
Vector< String > certificationsRequired
int maxCondition
uint32 optionsBitmask
uint32 pvpStatusBitmask
int useCount
int factoryCrateSize
bool sliceable
int faction
VectorMap< String, int > skillMods
Vector< short > * numberExperimentalProperties
Vector< String > * experimentalProperties
Vector< short > * experimentalWeights
Vector< String > * experimentalGroupTitles
Vector< String > * experimentalSubGroupTitles
Vector< float > * experimentalMin
Vector< float > * experimentalMax
Vector< short > * experimentalPrecision
Vector< short > * experimentalCombineType
Vector< uint32 > * playerRaces
Vector< Reference
< ResourceWeight * > > * resourceWeights
Detailed Description
Definition at line 13 of file DeedTemplate.h.
Constructor & Destructor Documentation
DeedTemplate::DeedTemplate () inline
Definition at line 17 of file DeedTemplate.h.
DeedTemplate::~DeedTemplate () inline
Definition at line 21 of file DeedTemplate.h.
Member Function Documentation
String& DeedTemplate::getGeneratedObjectTemplate () inline
Definition at line 31 of file DeedTemplate.h.
References generatedObjectTemplate.
Referenced by server::zone::objects::tangible::deed::DeedImplementation::loadTemplateData().
void DeedTemplate::readObject (LuaObject * templateData) inline virtual
Reimplemented from SharedTangibleObjectTemplate.
Reimplemented in VehicleDeedTemplate, StructureDeedTemplate, and PetDeedTemplate.
Definition at line 25 of file DeedTemplate.h.
References generatedObjectTemplate, and SharedTangibleObjectTemplate::readObject().
Referenced by PetDeedTemplate::readObject(), StructureDeedTemplate::readObject(), and VehicleDeedTemplate::readObject().
Member Data Documentation
String DeedTemplate::generatedObjectTemplate private
Definition at line 14 of file DeedTemplate.h.
Referenced by getGeneratedObjectTemplate(), and readObject().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/tangible/DeedTemplate.h