Core3: server::zone::objects::player::sui::listbox::SuiListBoxMenuItem Class Reference
server::zone::objects::player::sui::listbox::SuiListBoxMenuItem Class Reference
#include <SuiListBoxMenuItem.h>
Public Member Functions
SuiListBoxMenuItem (const String &name, unsigned long long oid=0)
unsigned long long getObjectID ()
String getOptionName ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
SuiListBoxMenuItem (DummyConstructorParameter *param)
virtual ~SuiListBoxMenuItem ()
Friends
class SuiListBoxMenuItemHelper
Detailed Description
Definition at line 39 of file SuiListBoxMenuItem.h.
Constructor & Destructor Documentation
SuiListBoxMenuItem::SuiListBoxMenuItem (const String & name, unsigned long long oid = 0)
Definition at line 15 of file SuiListBoxMenuItem.cpp.
References server::zone::objects::player::sui::listbox::SuiListBoxMenuItemImplementation::_setStub().
SuiListBoxMenuItem::SuiListBoxMenuItem (DummyConstructorParameter * param) protected
Definition at line 22 of file SuiListBoxMenuItem.cpp.
SuiListBoxMenuItem::~SuiListBoxMenuItem () protected virtual
Definition at line 26 of file SuiListBoxMenuItem.cpp.
Member Function Documentation
DistributedObjectServant * SuiListBoxMenuItem::_getImplementation ()
Definition at line 59 of file SuiListBoxMenuItem.cpp.
Referenced by getObjectID(), and getOptionName().
DistributedObjectServant * SuiListBoxMenuItem::_getImplementationForRead ()
Definition at line 65 of file SuiListBoxMenuItem.cpp.
void SuiListBoxMenuItem::_setImplementation (DistributedObjectServant * servant)
Definition at line 69 of file SuiListBoxMenuItem.cpp.
unsigned long long SuiListBoxMenuItem::getObjectID ()
Definition at line 31 of file SuiListBoxMenuItem.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxMenuItemImplementation::getObjectID(), and RPC_GETOBJECTID__.
String SuiListBoxMenuItem::getOptionName ()
Definition at line 44 of file SuiListBoxMenuItem.cpp.
References _getImplementation(), server::zone::objects::player::sui::listbox::SuiListBoxMenuItemImplementation::getOptionName(), and RPC_GETOPTIONNAME__.
Friends And Related Function Documentation
friend class SuiListBoxMenuItemHelper friend
Definition at line 57 of file SuiListBoxMenuItem.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/listbox/SuiListBoxMenuItem.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/listbox/SuiListBoxMenuItem.cpp