Core3: server::zone::managers::weather::WeatherManagerAdapter Class Reference
server::zone::managers::weather::WeatherManagerAdapter Class Reference
#include <WeatherManager.h>
Public Member Functions
WeatherManagerAdapter (WeatherManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initialize ()
void createNewWeatherPattern ()
void sendWeatherTo (CreatureObject *player)
void enableWeather (CreatureObject *player)
void disableWeather (CreatureObject *player)
void changeWeather (CreatureObject *player, int newWeather)
bool isWeatherEnabled ()
void setWeatherEnabled (bool value)
void printInfo (CreatureObject *player)
Detailed Description
Definition at line 300 of file WeatherManager.h.
Constructor & Destructor Documentation
WeatherManagerAdapter::WeatherManagerAdapter (WeatherManager * impl)
Definition at line 317 of file WeatherManager.cpp.
Member Function Documentation
void WeatherManagerAdapter::changeWeather (CreatureObject * player, int newWeather)
Definition at line 394 of file WeatherManager.cpp.
Referenced by invokeMethod().
void WeatherManagerAdapter::createNewWeatherPattern ()
Definition at line 378 of file WeatherManager.cpp.
Referenced by invokeMethod().
void WeatherManagerAdapter::disableWeather (CreatureObject * player)
Definition at line 390 of file WeatherManager.cpp.
Referenced by invokeMethod().
void WeatherManagerAdapter::enableWeather (CreatureObject * player)
Definition at line 386 of file WeatherManager.cpp.
Referenced by invokeMethod().
void WeatherManagerAdapter::initialize ()
Definition at line 374 of file WeatherManager.cpp.
Referenced by invokeMethod().
void WeatherManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 320 of file WeatherManager.cpp.
References changeWeather(), createNewWeatherPattern(), disableWeather(), enableWeather(), initialize(), isWeatherEnabled(), printInfo(), RPC_CHANGEWEATHER__CREATUREOBJECT_INT_, RPC_CREATENEWWEATHERPATTERN__, RPC_DISABLEWEATHER__CREATUREOBJECT_, RPC_ENABLEWEATHER__CREATUREOBJECT_, RPC_INITIALIZE__, RPC_ISWEATHERENABLED__, RPC_PRINTINFO__CREATUREOBJECT_, RPC_SENDWEATHERTO__CREATUREOBJECT_, RPC_SETWEATHERENABLED__BOOL_, sendWeatherTo(), and setWeatherEnabled().
bool WeatherManagerAdapter::isWeatherEnabled ()
Definition at line 398 of file WeatherManager.cpp.
Referenced by invokeMethod().
void WeatherManagerAdapter::printInfo (CreatureObject * player)
Definition at line 406 of file WeatherManager.cpp.
Referenced by invokeMethod().
void WeatherManagerAdapter::sendWeatherTo (CreatureObject * player)
Definition at line 382 of file WeatherManager.cpp.
Referenced by invokeMethod().
void WeatherManagerAdapter::setWeatherEnabled (bool value)
Definition at line 402 of file WeatherManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/weather/WeatherManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/weather/WeatherManager.cpp