Core3: GrantSkillCommand Class Reference
GrantSkillCommand Class Reference
#include <GrantSkillCommand.h>
Public Member Functions
GrantSkillCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Detailed Description
Definition at line 51 of file GrantSkillCommand.h.
Constructor & Destructor Documentation
GrantSkillCommand::GrantSkillCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 54 of file GrantSkillCommand.h.
Member Function Documentation
int GrantSkillCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 59 of file GrantSkillCommand.h.
References server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::managers::skill::SkillManager::surrenderSkill().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/GrantSkillCommand.h