Core3: server::chat::PersistentMessageAdapter Class Reference
server::chat::PersistentMessageAdapter Class Reference
#include <PersistentMessage.h>
Public Member Functions
PersistentMessageAdapter (PersistentMessage *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void sendTo (CreatureObject *player, bool sendBody)
int getMailID ()
unsigned long long getObjectID ()
String getSenderName ()
unsigned long long getReceiverObjectID ()
byte getStatus ()
int getTimeStamp ()
UnicodeString getBody ()
UnicodeString getSubject ()
void setSenderName (const String &name)
void setReceiverObjectID (unsigned long long oid)
void setStatus (byte stat)
void setTimeStamp (int stamp)
void setBody (const UnicodeString &message)
void setSubject (const UnicodeString &subj)
bool isNew ()
bool isRead ()
bool isUnread ()
Detailed Description
Definition at line 232 of file PersistentMessage.h.
Constructor & Destructor Documentation
PersistentMessageAdapter::PersistentMessageAdapter (PersistentMessage * impl)
Definition at line 646 of file PersistentMessage.cpp.
Member Function Documentation
UnicodeString PersistentMessageAdapter::getBody ()
Definition at line 779 of file PersistentMessage.cpp.
Referenced by invokeMethod().
int PersistentMessageAdapter::getMailID ()
Definition at line 755 of file PersistentMessage.cpp.
Referenced by invokeMethod().
unsigned long long PersistentMessageAdapter::getObjectID ()
Definition at line 759 of file PersistentMessage.cpp.
Referenced by invokeMethod().
unsigned long long PersistentMessageAdapter::getReceiverObjectID ()
Definition at line 767 of file PersistentMessage.cpp.
Referenced by invokeMethod().
String PersistentMessageAdapter::getSenderName ()
Definition at line 763 of file PersistentMessage.cpp.
Referenced by invokeMethod().
byte PersistentMessageAdapter::getStatus ()
Definition at line 771 of file PersistentMessage.cpp.
Referenced by invokeMethod().
UnicodeString PersistentMessageAdapter::getSubject ()
Definition at line 783 of file PersistentMessage.cpp.
Referenced by invokeMethod().
int PersistentMessageAdapter::getTimeStamp ()
Definition at line 775 of file PersistentMessage.cpp.
Referenced by invokeMethod().
void PersistentMessageAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 649 of file PersistentMessage.cpp.
References getBody(), getMailID(), getObjectID(), getReceiverObjectID(), getSenderName(), getStatus(), getSubject(), getTimeStamp(), isNew(), isRead(), isUnread(), RPC_GETBODY__, RPC_GETMAILID__, RPC_GETOBJECTID__, RPC_GETRECEIVEROBJECTID__, RPC_GETSENDERNAME__, RPC_GETSTATUS__, RPC_GETSUBJECT__, RPC_GETTIMESTAMP__, RPC_ISNEW__, RPC_ISREAD__, RPC_ISUNREAD__, RPC_SENDTO__CREATUREOBJECT_BOOL_, RPC_SETBODY__UNICODESTRING_, RPC_SETRECEIVEROBJECTID__LONG_, RPC_SETSENDERNAME__STRING_, RPC_SETSTATUS__BYTE_, RPC_SETSUBJECT__UNICODESTRING_, RPC_SETTIMESTAMP__INT_, sendTo(), setBody(), setReceiverObjectID(), setSenderName(), setStatus(), setSubject(), and setTimeStamp().
bool PersistentMessageAdapter::isNew ()
Definition at line 811 of file PersistentMessage.cpp.
Referenced by invokeMethod().
bool PersistentMessageAdapter::isRead ()
Definition at line 815 of file PersistentMessage.cpp.
Referenced by invokeMethod().
bool PersistentMessageAdapter::isUnread ()
Definition at line 819 of file PersistentMessage.cpp.
Referenced by invokeMethod().
void PersistentMessageAdapter::sendTo (CreatureObject * player, bool sendBody)
Definition at line 751 of file PersistentMessage.cpp.
Referenced by invokeMethod().
void PersistentMessageAdapter::setBody (const UnicodeString & message)
Definition at line 803 of file PersistentMessage.cpp.
Referenced by invokeMethod().
void PersistentMessageAdapter::setReceiverObjectID (unsigned long long oid)
Definition at line 791 of file PersistentMessage.cpp.
Referenced by invokeMethod().
void PersistentMessageAdapter::setSenderName (const String & name)
Definition at line 787 of file PersistentMessage.cpp.
Referenced by invokeMethod().
void PersistentMessageAdapter::setStatus (byte stat)
Definition at line 795 of file PersistentMessage.cpp.
Referenced by invokeMethod().
void PersistentMessageAdapter::setSubject (const UnicodeString & subj)
Definition at line 807 of file PersistentMessage.cpp.
Referenced by invokeMethod().
void PersistentMessageAdapter::setTimeStamp (int stamp)
Definition at line 799 of file PersistentMessage.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/PersistentMessage.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/PersistentMessage.cpp