Core3: server::zone::managers::weather::WeatherManager Class Reference
server::zone::managers::weather::WeatherManager Class Reference
#include <WeatherManager.h>
Public Member Functions
WeatherManager (Zone *planet)
void initialize ()
void createNewWeatherPattern ()
void sendWeatherTo (CreatureObject *player)
void enableWeather (CreatureObject *player)
void disableWeather (CreatureObject *player)
void changeWeather (CreatureObject *player, int newWeather)
bool isWeatherEnabled ()
void setWeatherEnabled (bool value)
void printInfo (CreatureObject *player)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int CLEAR = 0
static const int LIGHTSTORM = 1
static const int STORM = 2
static const int HEAVYSTORM = 3
static const int EXTREMESTORM = 4
Protected Member Functions
WeatherManager (DummyConstructorParameter *param)
virtual ~WeatherManager ()
Friends
class WeatherManagerHelper
Detailed Description
Definition at line 85 of file WeatherManager.h.
Constructor & Destructor Documentation
WeatherManager::WeatherManager (Zone * planet)
Definition at line 21 of file WeatherManager.cpp.
References server::zone::managers::weather::WeatherManagerImplementation::_setStub().
WeatherManager::WeatherManager (DummyConstructorParameter * param) protected
Definition at line 28 of file WeatherManager.cpp.
WeatherManager::~WeatherManager () protected virtual
Definition at line 32 of file WeatherManager.cpp.
Member Function Documentation
DistributedObjectServant * WeatherManager::_getImplementation ()
Definition at line 161 of file WeatherManager.cpp.
Referenced by changeWeather(), createNewWeatherPattern(), disableWeather(), enableWeather(), initialize(), isWeatherEnabled(), printInfo(), sendWeatherTo(), and setWeatherEnabled().
DistributedObjectServant * WeatherManager::_getImplementationForRead ()
Definition at line 167 of file WeatherManager.cpp.
void WeatherManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 171 of file WeatherManager.cpp.
void WeatherManager::changeWeather (CreatureObject * player, int newWeather)
Definition at line 105 of file WeatherManager.cpp.
References _getImplementation(), server::zone::managers::weather::WeatherManagerImplementation::changeWeather(), and RPC_CHANGEWEATHER__CREATUREOBJECT_INT_.
void WeatherManager::createNewWeatherPattern ()
Creates a new weather map
Definition at line 50 of file WeatherManager.cpp.
References _getImplementation(), server::zone::managers::weather::WeatherManagerImplementation::createNewWeatherPattern(), and RPC_CREATENEWWEATHERPATTERN__.
void WeatherManager::disableWeather (CreatureObject * player)
Definition at line 91 of file WeatherManager.cpp.
References _getImplementation(), server::zone::managers::weather::WeatherManagerImplementation::disableWeather(), and RPC_DISABLEWEATHER__CREATUREOBJECT_.
void WeatherManager::enableWeather (CreatureObject * player)
Definition at line 77 of file WeatherManager.cpp.
References _getImplementation(), server::zone::managers::weather::WeatherManagerImplementation::enableWeather(), and RPC_ENABLEWEATHER__CREATUREOBJECT_.
void WeatherManager::initialize ()
Initializes the weather manager events and some of the customization variables. Calls loadLuaConfig() to read in the lua values and schedules the weather change event.
Definition at line 37 of file WeatherManager.cpp.
References _getImplementation(), server::zone::managers::weather::WeatherManagerImplementation::initialize(), and RPC_INITIALIZE__.
bool WeatherManager::isWeatherEnabled ()
Definition at line 120 of file WeatherManager.cpp.
References _getImplementation(), server::zone::managers::weather::WeatherManagerImplementation::isWeatherEnabled(), and RPC_ISWEATHERENABLED__.
void WeatherManager::printInfo (CreatureObject * player)
Definition at line 147 of file WeatherManager.cpp.
References _getImplementation(), server::zone::managers::weather::WeatherManagerImplementation::printInfo(), and RPC_PRINTINFO__CREATUREOBJECT_.
void WeatherManager::sendWeatherTo (CreatureObject * player)
Sends the ServerWeatherMessage packet to the players.
Precondition
Locks the player for the duration of the method.
Parameters
player The player who will receive the new weather information.
Definition at line 63 of file WeatherManager.cpp.
References _getImplementation(), RPC_SENDWEATHERTO__CREATUREOBJECT_, and server::zone::managers::weather::WeatherManagerImplementation::sendWeatherTo().
Referenced by server::zone::objects::player::PlayerObjectImplementation::doRecovery().
void WeatherManager::setWeatherEnabled (bool value)
Definition at line 133 of file WeatherManager.cpp.
References _getImplementation(), RPC_SETWEATHERENABLED__BOOL_, and server::zone::managers::weather::WeatherManagerImplementation::setWeatherEnabled().
Friends And Related Function Documentation
friend class WeatherManagerHelper friend
Definition at line 139 of file WeatherManager.h.
Member Data Documentation
const int server::zone::managers::weather::WeatherManager::CLEAR = 0 static
Definition at line 87 of file WeatherManager.h.
const int server::zone::managers::weather::WeatherManager::EXTREMESTORM = 4 static
Definition at line 95 of file WeatherManager.h.
Referenced by server::zone::managers::weather::WeatherManagerImplementation::sendWeatherTo().
const int server::zone::managers::weather::WeatherManager::HEAVYSTORM = 3 static
Definition at line 93 of file WeatherManager.h.
const int server::zone::managers::weather::WeatherManager::LIGHTSTORM = 1 static
Definition at line 89 of file WeatherManager.h.
const int server::zone::managers::weather::WeatherManager::STORM = 2 static
Definition at line 91 of file WeatherManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/weather/WeatherManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/weather/WeatherManager.cpp