Core3: AppearanceTemplate Class Reference
AppearanceTemplate Class Reference
#include <AppearanceTemplate.h>
Public Member Functions
virtual void readObject (IffStream *iffStream)
virtual ~AppearanceTemplate ()
virtual AppearanceTemplate * getFirstMesh ()
Detailed Description
Definition at line 14 of file AppearanceTemplate.h.
Constructor & Destructor Documentation
virtual AppearanceTemplate::~AppearanceTemplate () inline virtual
Definition at line 22 of file AppearanceTemplate.h.
Member Function Documentation
virtual AppearanceTemplate* AppearanceTemplate::getFirstMesh () inline virtual
Reimplemented in MeshAppearanceTemplate, ComponentAppearanceTemplate, and DetailAppearanceTemplate.
Definition at line 28 of file AppearanceTemplate.h.
Referenced by CollisionManager::getAABBTree(), DetailAppearanceTemplate::parse(), ComponentAppearanceTemplate::parse(), and PortalLayout::parseCELSForm().
virtual void AppearanceTemplate::readObject (IffStream * iffStream) inline virtual
Reimplemented in MeshAppearanceTemplate, ComponentAppearanceTemplate, and DetailAppearanceTemplate.
Definition at line 16 of file AppearanceTemplate.h.
Referenced by TemplateManager::instantiateAppearanceTemplate(), DetailAppearanceTemplate::parse(), ComponentAppearanceTemplate::parse(), and MeshAppearanceTemplate::parse().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/AppearanceTemplate.h