Core3: AbilityList Class Reference
AbilityList Class Reference
#include <AbilityList.h>
Public Member Functions
bool add (Ability *ability, DeltaMessage *message=NULL, int updates=1)
bool contains (const String &element)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
void insertToMessage (BaseMessage *msg)
Public Member Functions inherited from server::zone::objects::scene::variables::DeltaVector< Ability * >
DeltaVector ()
DeltaVector (int initsize, int incr)
DeltaVector (const DeltaVector &v)
~DeltaVector ()
DeltaVector & operator= (const DeltaVector &v)
void addSerializableVariables ()
virtual Ability * set (int idx, const Ability *&newValue, DeltaMessage *message=NULL, int updates=1)
virtual bool add (const Ability *&element, DeltaMessage *message=NULL, int updates=1)
Ability *& get (int index) const
Ability *& getSafe (int index)
Ability * remove (int index, DeltaMessage *message=NULL, int updates=1)
void removeAll (DeltaMessage *message=NULL)
virtual void insertItemToMessage (Ability **item, BaseMessage *msg)
virtual bool contains (const Ability *&element)
int find (const Ability *&element)
uint32 getUpdateCounter ()
uint32 getNewUpdateCounter (int increment)
void setUpdateCounter (int count)
void resetUpdateCounter ()
int size ()
ReadWriteLock * getLock ()
Private Member Functions
void getStringList (Vector< String > &abilities)
void loadFromNames (Vector< String > &abilities)
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::scene::variables::DeltaVector< Ability * >
Vector< Ability * > vector
uint32 updateCounter
ReadWriteLock * mutex
Detailed Description
The ability list is just a vector of strings that award the ability to perform specific actions.
Definition at line 19 of file AbilityList.h.
Member Function Documentation
bool AbilityList::add (Ability * ability, DeltaMessage * message = NULL, int updates = 1)
Definition at line 90 of file AbilityList.cpp.
References DeltaMessage::startList(), Ability::toBinaryStream(), server::zone::objects::scene::variables::DeltaVector< Ability * >::updateCounter, and server::zone::objects::scene::variables::DeltaVector< Ability * >::vector.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addAbilities(), and server::zone::objects::player::PlayerObjectImplementation::addAbility().
bool AbilityList::contains (const String & element)
Definition at line 16 of file AbilityList.cpp.
References Ability::getAbilityName(), and server::zone::objects::scene::variables::DeltaVector< Ability * >::vector.
void AbilityList::getStringList (Vector< String > & abilities) private
Definition at line 55 of file AbilityList.cpp.
References Ability::getAbilityName(), and server::zone::objects::scene::variables::DeltaVector< Ability * >::vector.
Referenced by toBinaryStream().
void AbilityList::insertToMessage (BaseMessage * msg) virtual
Reimplemented from server::zone::objects::scene::variables::DeltaVector< Ability * >.
Definition at line 34 of file AbilityList.cpp.
References server::zone::objects::scene::variables::DeltaVector< Ability * >::size(), and server::zone::objects::scene::variables::DeltaVector< Ability * >::updateCounter.
Referenced by PlayerObjectMessage9::PlayerObjectMessage9().
void AbilityList::loadFromNames (Vector< String > & abilities) private
Definition at line 76 of file AbilityList.cpp.
References server::zone::managers::skill::SkillManager::getAbility(), server::zone::ZoneServer::getSkillManager(), ServerCore::getZoneServer(), and server::zone::objects::scene::variables::DeltaVector< Ability * >::vector.
Referenced by parseFromBinaryStream().
bool AbilityList::parseFromBinaryStream (ObjectInputStream * stream)
Definition at line 65 of file AbilityList.cpp.
References loadFromNames(), and server::zone::objects::scene::variables::DeltaVector< Ability * >::updateCounter.
bool AbilityList::toBinaryStream (ObjectOutputStream * stream)
Definition at line 45 of file AbilityList.cpp.
References getStringList(), and server::zone::objects::scene::variables::DeltaVector< Ability * >::updateCounter.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/variables/AbilityList.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/variables/AbilityList.cpp