Core3: AuctionQueryHeadersResponseMessage Class Reference
AuctionQueryHeadersResponseMessage Class Reference
#include <AuctionQueryHeadersResponseMessage.h>
Public Member Functions
AuctionQueryHeadersResponseMessage (int screen, int counter, CreatureObject *player)
void addItemToList (AuctionItem *ai)
void dumpLocationList ()
void dumpItemNameList ()
void dumpItemInfoList ()
void createMessage (int offset=0, bool continues=false)
int getListSize ()
Private Attributes
Vector< ManagedReference
< AuctionItem * > > itemList
SortedVector< String > locationList
ManagedReference
< CreatureObject * > player
Detailed Description
Definition at line 55 of file AuctionQueryHeadersResponseMessage.h.
Constructor & Destructor Documentation
AuctionQueryHeadersResponseMessage::AuctionQueryHeadersResponseMessage (int screen, int counter, CreatureObject * player) inline
Definition at line 64 of file AuctionQueryHeadersResponseMessage.h.
References locationList, and player.
Member Function Documentation
void AuctionQueryHeadersResponseMessage::addItemToList (AuctionItem * ai) inline
Definition at line 78 of file AuctionQueryHeadersResponseMessage.h.
References server::zone::objects::auction::AuctionItem::getBidderName(), server::zone::objects::auction::AuctionItem::getOwnerName(), server::zone::objects::auction::AuctionItem::getStatus(), server::zone::objects::auction::AuctionItem::getVendorUID(), server::zone::objects::auction::AuctionItem::isAuction(), itemList, and locationList.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::fillAuctionQueryHeadersResponseMessage().
void AuctionQueryHeadersResponseMessage::createMessage (int offset = 0, bool continues = false) inline
Definition at line 181 of file AuctionQueryHeadersResponseMessage.h.
References dumpItemInfoList(), dumpItemNameList(), and dumpLocationList().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::fillAuctionQueryHeadersResponseMessage().
void AuctionQueryHeadersResponseMessage::dumpItemInfoList () inline
Definition at line 113 of file AuctionQueryHeadersResponseMessage.h.
References server::zone::objects::building::BuildingObject::getAccessFee(), server::zone::objects::auction::AuctionItem::getAuctionedItemObjectID(), server::zone::objects::auction::AuctionItem::getAuctionOptions(), server::zone::objects::auction::AuctionItem::getBidderName(), server::zone::objects::auction::AuctionItem::getBuyerID(), server::zone::objects::auction::AuctionItem::getExpireTime(), server::zone::objects::auction::AuctionItem::getItemType(), server::zone::objects::auction::AuctionItem::getOwnerID(), server::zone::objects::auction::AuctionItem::getOwnerName(), server::zone::objects::auction::AuctionItem::getPrice(), server::zone::objects::auction::AuctionItem::getProxy(), server::zone::objects::auction::AuctionItem::getStatus(), server::zone::objects::auction::AuctionItem::getVendorID(), server::zone::objects::auction::AuctionItem::getVendorUID(), server::zone::objects::auction::AuctionItem::isAuction(), itemList, locationList, and player.
Referenced by createMessage().
void AuctionQueryHeadersResponseMessage::dumpItemNameList () inline
Definition at line 100 of file AuctionQueryHeadersResponseMessage.h.
References server::zone::objects::auction::AuctionItem::getItemName(), and itemList.
Referenced by createMessage().
void AuctionQueryHeadersResponseMessage::dumpLocationList () inline
Definition at line 90 of file AuctionQueryHeadersResponseMessage.h.
References locationList.
Referenced by createMessage().
int AuctionQueryHeadersResponseMessage::getListSize () inline
Definition at line 193 of file AuctionQueryHeadersResponseMessage.h.
References itemList.
Member Data Documentation
Vector<ManagedReference<AuctionItem*> > AuctionQueryHeadersResponseMessage::itemList private
Definition at line 57 of file AuctionQueryHeadersResponseMessage.h.
Referenced by addItemToList(), dumpItemInfoList(), dumpItemNameList(), and getListSize().
SortedVector<String> AuctionQueryHeadersResponseMessage::locationList private
Definition at line 59 of file AuctionQueryHeadersResponseMessage.h.
Referenced by addItemToList(), AuctionQueryHeadersResponseMessage(), dumpItemInfoList(), and dumpLocationList().
ManagedReference<CreatureObject*> AuctionQueryHeadersResponseMessage::player private
Definition at line 61 of file AuctionQueryHeadersResponseMessage.h.
Referenced by AuctionQueryHeadersResponseMessage(), and dumpItemInfoList().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/auction/AuctionQueryHeadersResponseMessage.h