Core3: PortalLayout Class Reference
PortalLayout Class Reference
#include <PortalLayout.h>
Public Member Functions
PortalLayout ()
~PortalLayout ()
void readObject (IffStream *templateData)
void parse (IffStream *iffStream)
void parseCELSForm (IffStream *iffStream)
void connectFloorMeshGraphs ()
int getFloorMeshID (int globalNodeID, int floorMeshToExclude)
Vector< PathNode * > * getPath (PathNode *node1, PathNode *node2)
int getCellTotalNumber ()
int getFloorMeshNumber ()
FloorMesh * getFloorMesh (int cellIndex)
MeshAppearanceTemplate * getMeshAppearanceTemplate (int cellIndex)
int getAppearanceTemplatesSize ()
Public Member Functions inherited from IffTemplate
virtual ~IffTemplate ()
Public Member Functions inherited from TemplateData
virtual ~TemplateData ()
Private Attributes
int cellTotalNumber
Vector< FloorMesh * > floorMeshes
Vector< MeshAppearanceTemplate * > appearanceTemplates
PathGraph * pathGraph
Detailed Description
Definition at line 18 of file PortalLayout.h.
Constructor & Destructor Documentation
PortalLayout::PortalLayout ()
Definition at line 15 of file PortalLayout.cpp.
References cellTotalNumber, and pathGraph.
PortalLayout::~PortalLayout ()
Definition at line 22 of file PortalLayout.cpp.
References pathGraph.
Member Function Documentation
void PortalLayout::connectFloorMeshGraphs ()
Definition at line 80 of file PortalLayout.cpp.
References PathNode::addChild(), floorMeshes, PathNode::getGlobalGraphNodeID(), PathGraph::getGlobalNodes(), FloorMesh::getPathGraph(), and pathGraph.
Referenced by parse().
int PortalLayout::getAppearanceTemplatesSize () inline
Definition at line 58 of file PortalLayout.h.
References appearanceTemplates.
Referenced by CollisionManager::checkLineOfSightInBuilding(), and CollisionManager::checkLineOfSightWorldToCell().
int PortalLayout::getCellTotalNumber () inline
Definition at line 42 of file PortalLayout.h.
References cellTotalNumber.
FloorMesh* PortalLayout::getFloorMesh (int cellIndex) inline
Definition at line 50 of file PortalLayout.h.
References floorMeshes.
Referenced by PathFinderManager::findPathFromCellToCell(), PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), PathFinderManager::findPathFromWorldToCell(), CollisionManager::getCellFloorCollision(), FleeStateComponent::getFleeLocation(), PathFinderManager::getFloorMesh(), and CollisionManager::getWorldFloorCollision().
int PortalLayout::getFloorMeshID (int globalNodeID, int floorMeshToExclude)
Definition at line 126 of file PortalLayout.cpp.
References floorMeshes, and FloorMesh::getGlobalNode().
Referenced by FleeStateComponent::getFleeLocation().
int PortalLayout::getFloorMeshNumber () inline
Definition at line 46 of file PortalLayout.h.
References floorMeshes.
Referenced by CollisionManager::getWorldFloorCollision(), and server::zone::objects::building::BuildingObjectImplementation::loadTemplateData().
MeshAppearanceTemplate* PortalLayout::getMeshAppearanceTemplate (int cellIndex) inline
Definition at line 54 of file PortalLayout.h.
References appearanceTemplates.
Referenced by CollisionManager::checkLineOfSightInBuilding(), CollisionManager::checkLineOfSightInParentCell(), CollisionManager::checkLineOfSightWorldToCell(), CollisionManager::getAABBTree(), and server::zone::objects::structure::StructureObjectImplementation::getAABBTree().
Vector< PathNode * > * PortalLayout::getPath (PathNode * node1, PathNode * node2)
Definition at line 231 of file PortalLayout.cpp.
References PathNode::getPathGraph().
Referenced by PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), and PathFinderManager::findPathFromWorldToCell().
void PortalLayout::parse (IffStream * iffStream)
Definition at line 27 of file PortalLayout.cpp.
References connectFloorMeshGraphs(), parseCELSForm(), pathGraph, and PathGraph::readObject().
Referenced by readObject().
void PortalLayout::parseCELSForm (IffStream * iffStream)
Definition at line 141 of file PortalLayout.cpp.
References appearanceTemplates, cellTotalNumber, floorMeshes, AppearanceTemplate::getFirstMesh(), and FloorMesh::setCellID().
Referenced by parse().
void PortalLayout::readObject (IffStream * templateData) inline virtual
Implements IffTemplate.
Definition at line 28 of file PortalLayout.h.
References parse().
Referenced by TemplateManager::getPortalLayout().
Member Data Documentation
Vector<MeshAppearanceTemplate*> PortalLayout::appearanceTemplates private
Definition at line 21 of file PortalLayout.h.
Referenced by getAppearanceTemplatesSize(), getMeshAppearanceTemplate(), and parseCELSForm().
int PortalLayout::cellTotalNumber private
Definition at line 19 of file PortalLayout.h.
Referenced by getCellTotalNumber(), parseCELSForm(), and PortalLayout().
Vector<FloorMesh*> PortalLayout::floorMeshes private
Definition at line 20 of file PortalLayout.h.
Referenced by connectFloorMeshGraphs(), getFloorMesh(), getFloorMeshID(), getFloorMeshNumber(), and parseCELSForm().
PathGraph* PortalLayout::pathGraph private
Definition at line 22 of file PortalLayout.h.
Referenced by connectFloorMeshGraphs(), parse(), PortalLayout(), and ~PortalLayout().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/PortalLayout.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/PortalLayout.cpp