Core3: BlueprintEntry Class Reference
BlueprintEntry Class Reference
#include <BlueprintEntry.h>
Public Member Functions
BlueprintEntry ()
Default Constructor.
BlueprintEntry (const BlueprintEntry &entry)
BlueprintEntry (TangibleObject *ingredient, bool isIdentical=false)
Constructor.
~BlueprintEntry ()
BlueprintEntry & operator= (const BlueprintEntry &entry)
bool operator== (const BlueprintEntry &entry)
bool equals (BlueprintEntry *entry)
void insertSchematicAttribute (AttributeListMessage *alm)
Inserts string for ManufactureSchematic attributes.
void insertFactoryIngredient (SuiListBox *ingredientList)
Inserts factory ingredient for ingredient list sui.
void clearMatches ()
Clear contents.
bool hasEnoughResources ()
See if this entry has enough resources to continue.
void removeResources (FactoryObject *factory)
Remove resources from vector.
void print ()
Print internal state.
bool needsIdentical ()
If item requires identical.
void setIdentical (bool value)
String getType ()
Getter for type.
String getKey ()
Getter for key.
String getSerial ()
Getter for serial.
String getDisplayedName ()
Getter for displayed name.
int getQuantity ()
getter for quantity
void setQuantity (int value)
void increaseQuantity (int value)
increase for quantity
void addMatch (TangibleObject *object)
Add a match to the vector.
void setDisplayedName (String value)
void setType (String value)
void setKey (String value)
void setSerial (String value)
void setHopper (SceneObject *hopper)
Private Member Functions
void addSerializableVariables ()
Adds members to be serialized.
Private Attributes
String type
Type of resource.
String key
Unique identifier - Resource = spawnName; Component = server script crc.
String displayedName
Name to display in UI.
String serialNumber
Serial number of tangible item.
bool identical
Designates if this item needs to be identical.
int quantity
Quantity of ingredient neededs.
ManagedReference< SceneObject * > inputHopper
Input hopper.
Vector< ManagedReference
< TangibleObject * > > matchingHopperItems
Matching items from factory hopper.
Detailed Description
This class defines a collective entry that makes up a single blueprint item Ex. If a schematic contains 2 identical ingredients, they will combine to a single blueprint entry
Definition at line 37 of file BlueprintEntry.h.
Constructor & Destructor Documentation
BlueprintEntry::BlueprintEntry ()
Default Constructor.
Definition at line 14 of file BlueprintEntry.cpp.
References addSerializableVariables(), and serialNumber.
BlueprintEntry::BlueprintEntry (const BlueprintEntry & entry)
Definition at line 19 of file BlueprintEntry.cpp.
References addSerializableVariables(), displayedName, identical, key, quantity, serialNumber, and type.
BlueprintEntry::BlueprintEntry (TangibleObject * ingredient, bool isIdentical = false)
Constructor.
BlueprintEntry::~BlueprintEntry ()
Definition at line 31 of file BlueprintEntry.cpp.
Member Function Documentation
void BlueprintEntry::addMatch (TangibleObject * object) inline
Add a match to the vector.
Definition at line 145 of file BlueprintEntry.h.
Referenced by server::zone::objects::installation::factory::FactoryObjectImplementation::collectMatchesInInputHopper().
void BlueprintEntry::addSerializableVariables () private
Adds members to be serialized.
Definition at line 68 of file BlueprintEntry.cpp.
References displayedName, identical, key, quantity, serialNumber, and type.
Referenced by BlueprintEntry().
void BlueprintEntry::clearMatches ()
Clear contents.
Definition at line 102 of file BlueprintEntry.cpp.
References matchingHopperItems.
Referenced by server::zone::objects::installation::factory::FactoryObjectImplementation::collectMatchesInInputHopper().
bool BlueprintEntry::equals (BlueprintEntry * entry)
Definition at line 60 of file BlueprintEntry.cpp.
References identical, key, serialNumber, and type.
Referenced by FactoryBlueprint::addConsolidatedEntry().
String BlueprintEntry::getDisplayedName () inline
Getter for displayed name.
Definition at line 126 of file BlueprintEntry.h.
Referenced by FactoryBlueprint::canManufactureItem().
String BlueprintEntry::getKey () inline
Getter for key.
Definition at line 116 of file BlueprintEntry.h.
Referenced by server::zone::objects::installation::factory::FactoryObjectImplementation::collectMatchesInInputHopper().
int BlueprintEntry::getQuantity () inline
getter for quantity
Definition at line 131 of file BlueprintEntry.h.
Referenced by FactoryBlueprint::addConsolidatedEntry().
String BlueprintEntry::getSerial () inline
Getter for serial.
Definition at line 121 of file BlueprintEntry.h.
Referenced by server::zone::objects::installation::factory::FactoryObjectImplementation::collectMatchesInInputHopper().
String BlueprintEntry::getType () inline
Getter for type.
Definition at line 111 of file BlueprintEntry.h.
Referenced by FactoryBlueprint::canManufactureItem().
bool BlueprintEntry::hasEnoughResources ()
See if this entry has enough resources to continue.
Definition at line 106 of file BlueprintEntry.cpp.
References server::zone::objects::scene::SceneObject::getParentID(), inputHopper, matchingHopperItems, and quantity.
Referenced by FactoryBlueprint::canManufactureItem().
void BlueprintEntry::increaseQuantity (int value) inline
increase for quantity
Definition at line 140 of file BlueprintEntry.h.
Referenced by FactoryBlueprint::addConsolidatedEntry().
void BlueprintEntry::insertFactoryIngredient (SuiListBox * ingredientList)
Inserts factory ingredient for ingredient list sui.
Definition at line 89 of file BlueprintEntry.cpp.
References server::zone::objects::player::sui::listbox::SuiListBox::addMenuItem(), displayedName, quantity, serialNumber, and type.
Referenced by server::zone::objects::installation::factory::FactoryObjectImplementation::sendIngredientsNeededSui().
void BlueprintEntry::insertSchematicAttribute (AttributeListMessage * alm)
Inserts string for ManufactureSchematic attributes.
Definition at line 77 of file BlueprintEntry.cpp.
References displayedName, server::zone::packets::scene::AttributeListMessage::insertAttribute(), quantity, serialNumber, and type.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::fillAttributeList().
bool BlueprintEntry::needsIdentical () inline
If item requires identical.
Definition at line 102 of file BlueprintEntry.h.
Referenced by server::zone::objects::installation::factory::FactoryObjectImplementation::collectMatchesInInputHopper().
BlueprintEntry & BlueprintEntry::operator= (const BlueprintEntry & entry)
Definition at line 35 of file BlueprintEntry.cpp.
References displayedName, identical, key, quantity, serialNumber, and type.
bool BlueprintEntry::operator== (const BlueprintEntry & entry)
Definition at line 49 of file BlueprintEntry.cpp.
References displayedName, identical, key, serialNumber, and type.
void BlueprintEntry::print ()
Print internal state.
Definition at line 179 of file BlueprintEntry.cpp.
References displayedName, identical, key, matchingHopperItems, quantity, serialNumber, and type.
Referenced by FactoryBlueprint::print().
void BlueprintEntry::removeResources (FactoryObject * factory)
Remove resources from vector.
Definition at line 135 of file BlueprintEntry.cpp.
References server::zone::objects::installation::InstallationObject::broadcastToOperators(), DeltaMessage::close(), server::zone::objects::tangible::TangibleObject::getUseCount(), server::zone::objects::scene::SceneObject::isResourceContainer(), matchingHopperItems, quantity, and TangibleObjectDeltaMessage3::updateCountdownTimer().
Referenced by FactoryBlueprint::manufactureItem().
void BlueprintEntry::setDisplayedName (String value) inline
Definition at line 149 of file BlueprintEntry.h.
Referenced by FactoryBlueprint::addIngredient().
void BlueprintEntry::setHopper (SceneObject * hopper) inline
Definition at line 165 of file BlueprintEntry.h.
Referenced by server::zone::objects::installation::factory::FactoryObjectImplementation::populateSchematicBlueprint().
void BlueprintEntry::setIdentical (bool value) inline
Definition at line 106 of file BlueprintEntry.h.
Referenced by FactoryBlueprint::addIngredient().
void BlueprintEntry::setKey (String value) inline
Definition at line 157 of file BlueprintEntry.h.
Referenced by FactoryBlueprint::addIngredient().
void BlueprintEntry::setQuantity (int value) inline
Definition at line 135 of file BlueprintEntry.h.
Referenced by FactoryBlueprint::addIngredient().
void BlueprintEntry::setSerial (String value) inline
Definition at line 161 of file BlueprintEntry.h.
Referenced by FactoryBlueprint::addIngredient().
void BlueprintEntry::setType (String value) inline
Definition at line 153 of file BlueprintEntry.h.
Referenced by FactoryBlueprint::addIngredient().
Member Data Documentation
String BlueprintEntry::displayedName private
Name to display in UI.
Definition at line 47 of file BlueprintEntry.h.
Referenced by addSerializableVariables(), BlueprintEntry(), insertFactoryIngredient(), insertSchematicAttribute(), operator=(), operator==(), and print().
bool BlueprintEntry::identical private
Designates if this item needs to be identical.
Definition at line 53 of file BlueprintEntry.h.
Referenced by addSerializableVariables(), BlueprintEntry(), equals(), operator=(), operator==(), and print().
ManagedReference<SceneObject* > BlueprintEntry::inputHopper private
Input hopper.
Definition at line 59 of file BlueprintEntry.h.
Referenced by hasEnoughResources().
String BlueprintEntry::key private
Unique identifier - Resource = spawnName; Component = server script crc.
Definition at line 44 of file BlueprintEntry.h.
Referenced by addSerializableVariables(), BlueprintEntry(), equals(), operator=(), operator==(), and print().
Vector<ManagedReference<TangibleObject*> > BlueprintEntry::matchingHopperItems private
Matching items from factory hopper.
Definition at line 62 of file BlueprintEntry.h.
Referenced by clearMatches(), hasEnoughResources(), print(), and removeResources().
int BlueprintEntry::quantity private
Quantity of ingredient neededs.
Definition at line 56 of file BlueprintEntry.h.
Referenced by addSerializableVariables(), BlueprintEntry(), hasEnoughResources(), insertFactoryIngredient(), insertSchematicAttribute(), operator=(), print(), and removeResources().
String BlueprintEntry::serialNumber private
Serial number of tangible item.
Definition at line 50 of file BlueprintEntry.h.
Referenced by addSerializableVariables(), BlueprintEntry(), equals(), insertFactoryIngredient(), insertSchematicAttribute(), operator=(), operator==(), and print().
String BlueprintEntry::type private
Type of resource.
Definition at line 41 of file BlueprintEntry.h.
Referenced by addSerializableVariables(), BlueprintEntry(), equals(), insertFactoryIngredient(), insertSchematicAttribute(), operator=(), operator==(), and print().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/factoryblueprint/BlueprintEntry.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/factoryblueprint/BlueprintEntry.cpp