Core3: ManufactureSchematicObjectDeltaMessage3 Class Reference
ManufactureSchematicObjectDeltaMessage3 Class Reference
#include <ManufactureSchematicObjectDeltaMessage3.h>
Public Member Functions
ManufactureSchematicObjectDeltaMessage3 (SceneObject *schematic)
void updateComplexity (float complexity)
void updateName (String name)
void updateCondition (int condition)
void updateManufactureLimit (int limit)
void updateCraftingValues (ManufactureSchematic *manufactureSchematic)
Public Member Functions inherited from DeltaMessage
DeltaMessage (uint64 oid, uint32 name, uint8 type)
uint32 generateRandomObjectCRC ()
void startUpdate (uint16 type)
void addByteUpdate (uint16 type, uint8 value)
void addShortUpdate (uint16 type, uint16 value)
void addIntUpdate (uint16 type, uint32 value)
void addLongUpdate (uint16 type, uint64 value)
void addFloatUpdate (uint16 type, float value)
void addAsciiUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const UnicodeString &val)
void startList (uint32 cnt, uint32 updcnt)
void addListIntElement (uint16 index, uint32 value)
void addListFloatElement (uint16 index, float value)
void addListLongElement (uint16 index, uint64 value)
void addListAsciiElement (const String &value)
void removeListIntElement (uint16 index, uint32 value)
void removeListFloatElement (uint16 index, float value)
void removeListLongElement (uint16 index, uint64 value)
void removeListLongElement (uint16 index)
void removeListAsciiElement (const String &value)
void close ()
Detailed Description
Definition at line 53 of file ManufactureSchematicObjectDeltaMessage3.h.
Constructor & Destructor Documentation
ManufactureSchematicObjectDeltaMessage3::ManufactureSchematicObjectDeltaMessage3 (SceneObject * schematic) inline
Definition at line 55 of file ManufactureSchematicObjectDeltaMessage3.h.
Member Function Documentation
void ManufactureSchematicObjectDeltaMessage3::updateComplexity (float complexity) inline
Definition at line 59 of file ManufactureSchematicObjectDeltaMessage3.h.
References DeltaMessage::addFloatUpdate().
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::addIngredientToSlot(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::experiment(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::initialAssembly(), and server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::removeIngredientFromSlot().
void ManufactureSchematicObjectDeltaMessage3::updateCondition (int condition) inline
Definition at line 67 of file ManufactureSchematicObjectDeltaMessage3.h.
References DeltaMessage::addIntUpdate().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::customization().
void ManufactureSchematicObjectDeltaMessage3::updateCraftingValues (ManufactureSchematic * manufactureSchematic) inline
Definition at line 75 of file ManufactureSchematicObjectDeltaMessage3.h.
References DeltaMessage::startList(), and DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::experiment(), and server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::initialAssembly().
void ManufactureSchematicObjectDeltaMessage3::updateManufactureLimit (int limit) inline
Definition at line 71 of file ManufactureSchematicObjectDeltaMessage3.h.
References DeltaMessage::addIntUpdate().
void ManufactureSchematicObjectDeltaMessage3::updateName (String name) inline
Definition at line 63 of file ManufactureSchematicObjectDeltaMessage3.h.
References DeltaMessage::addUnicodeUpdate().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::customization().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/manufactureschematic/ManufactureSchematicObjectDeltaMessage3.h