Core3: TangibleObjectMenuComponent Class Reference
TangibleObjectMenuComponent Class Reference
#include <TangibleObjectMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file TangibleObjectMenuComponent.h.
Member Function Documentation
void TangibleObjectMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Viewing components used to craft item, for admins
Reimplemented from ObjectMenuComponent.
Reimplemented in ForceShrineMenuComponent, BankTerminalMenuComponent, BountyHunterDroidMenuComponent, DiceMenuComponent, ArmorObjectMenuComponent, CampTerminalMenuComponent, CreatureHabitatMenuComponent, FireworkShowMenuComponent, TrainerMenuComponent, CampKitMenuComponent, CloningTerminalMenuComponent, ArtCrateMenuComponent, LootSchematicMenuComponent, ShellfishHarvesterMenuComponent, GogglesObjectMenuComponent, InsuranceTerminalMenuComponent, LairMenuComponent, LightsaberObjectMenuComponent, RobeObjectMenuComponent, SkillBuffObjectMenuComponent, TrapMenuComponent, VehicleCustomKitObjectMenuComponent, VendorMenuComponent, WeaponObjectMenuComponent, WearableObjectMenuComponent, FireworkMenuComponent, ElevatorDownMenuComponent, ElevatorMenuComponent, ElevatorUpMenuComponent, FireHeavyWeaponMenuComponent, and ThrowGrenadeMenuComponent.
Definition at line 13 of file TangibleObjectMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), ObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::getGameObjectType(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::scene::SceneObject::isArmorObject(), server::zone::objects::scene::SceneObject::isContainerObject(), server::zone::objects::scene::SceneObject::isMissionTerminal(), server::zone::objects::tangible::TangibleObject::isSliceable(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::objects::scene::SceneObject::isWeaponObject(), SceneObjectType::PLAYERLOOTCRATE, and SceneObjectType::STATICLOOTCONTAINER.
Referenced by TrainerMenuComponent::fillObjectMenuResponse(), CampKitMenuComponent::fillObjectMenuResponse(), FireworkMenuComponent::fillObjectMenuResponse(), ArtCrateMenuComponent::fillObjectMenuResponse(), WeaponObjectMenuComponent::fillObjectMenuResponse(), LightsaberObjectMenuComponent::fillObjectMenuResponse(), RobeObjectMenuComponent::fillObjectMenuResponse(), SkillBuffObjectMenuComponent::fillObjectMenuResponse(), TrapMenuComponent::fillObjectMenuResponse(), LootSchematicMenuComponent::fillObjectMenuResponse(), LairMenuComponent::fillObjectMenuResponse(), VehicleCustomKitObjectMenuComponent::fillObjectMenuResponse(), GogglesObjectMenuComponent::fillObjectMenuResponse(), WearableObjectMenuComponent::fillObjectMenuResponse(), CloningTerminalMenuComponent::fillObjectMenuResponse(), ShellfishHarvesterMenuComponent::fillObjectMenuResponse(), InsuranceTerminalMenuComponent::fillObjectMenuResponse(), FireworkShowMenuComponent::fillObjectMenuResponse(), CampTerminalMenuComponent::fillObjectMenuResponse(), CreatureHabitatMenuComponent::fillObjectMenuResponse(), BountyHunterDroidMenuComponent::fillObjectMenuResponse(), DiceMenuComponent::fillObjectMenuResponse(), BankTerminalMenuComponent::fillObjectMenuResponse(), and ForceShrineMenuComponent::fillObjectMenuResponse().
int TangibleObjectMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from ObjectMenuComponent.
Reimplemented in BankTerminalMenuComponent, ForceShrineMenuComponent, HolocronMenuComponent, BountyHunterDroidMenuComponent, DiceMenuComponent, ArmorObjectMenuComponent, CampTerminalMenuComponent, CreatureHabitatMenuComponent, FireworkShowMenuComponent, TrainerMenuComponent, CampKitMenuComponent, CloningTerminalMenuComponent, ArtCrateMenuComponent, LootSchematicMenuComponent, ShellfishHarvesterMenuComponent, GogglesObjectMenuComponent, InsuranceTerminalMenuComponent, LairMenuComponent, LightsaberObjectMenuComponent, RobeObjectMenuComponent, SkillBuffObjectMenuComponent, TrapMenuComponent, VehicleCustomKitObjectMenuComponent, VendorMenuComponent, WeaponObjectMenuComponent, WearableObjectMenuComponent, FireworkMenuComponent, FireHeavyWeaponMenuComponent, ElevatorDownMenuComponent, ElevatorMenuComponent, ElevatorUpMenuComponent, and ThrowGrenadeMenuComponent.
Definition at line 63 of file TangibleObjectMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::containsActiveSession(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getSlottedObject(), ObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::objects::scene::SceneObject::openContainerTo(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::SceneObject::sendWithoutContainerObjectsTo(), and SessionFacadeType::SLICING.
Referenced by TrainerMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), FireworkMenuComponent::handleObjectMenuSelect(), WearableObjectMenuComponent::handleObjectMenuSelect(), LootSchematicMenuComponent::handleObjectMenuSelect(), VendorMenuComponent::handleObjectMenuSelect(), SkillBuffObjectMenuComponent::handleObjectMenuSelect(), TrapMenuComponent::handleObjectMenuSelect(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), RobeObjectMenuComponent::handleObjectMenuSelect(), ShellfishHarvesterMenuComponent::handleObjectMenuSelect(), LairMenuComponent::handleObjectMenuSelect(), WeaponObjectMenuComponent::handleObjectMenuSelect(), GogglesObjectMenuComponent::handleObjectMenuSelect(), ArtCrateMenuComponent::handleObjectMenuSelect(), InsuranceTerminalMenuComponent::handleObjectMenuSelect(), LightsaberObjectMenuComponent::handleObjectMenuSelect(), FireworkShowMenuComponent::handleObjectMenuSelect(), CampTerminalMenuComponent::handleObjectMenuSelect(), CreatureHabitatMenuComponent::handleObjectMenuSelect(), DiceMenuComponent::handleObjectMenuSelect(), BountyHunterDroidMenuComponent::handleObjectMenuSelect(), and BankTerminalMenuComponent::handleObjectMenuSelect().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/TangibleObjectMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/TangibleObjectMenuComponent.cpp