Core3: server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation Class Reference
server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation Class Reference
#include <CityTreasuryWithdrawalSession.h>
Public Member Functions
CityTreasuryWithdrawalSessionImplementation (CreatureObject *creature, CityRegion *city, SceneObject *terminal=NULL)
CityTreasuryWithdrawalSessionImplementation (DummyConstructorParameter *param)
void setReason (const String &r)
int initializeSession ()
int sendTransferBox (const String &reason)
int withdrawCredits (int value)
int cancelSession ()
int clearSession ()
operator const CityTreasuryWithdrawalSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< CityTreasuryWithdrawalSession * > _this
Protected Member Functions
virtual ~CityTreasuryWithdrawalSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > creatureObject
ManagedWeakReference
< CityRegion * > cityRegion
ManagedWeakReference
< SceneObject * > terminalObject
String reason
Friends
class CityTreasuryWithdrawalSession
Detailed Description
Definition at line 123 of file CityTreasuryWithdrawalSession.h.
Constructor & Destructor Documentation
CityTreasuryWithdrawalSessionImplementation::CityTreasuryWithdrawalSessionImplementation (CreatureObject * creature, CityRegion * city, SceneObject * terminal = NULL)
Definition at line 298 of file CityTreasuryWithdrawalSession.cpp.
References _initializeImplementation(), cityRegion, creatureObject, and terminalObject.
CityTreasuryWithdrawalSessionImplementation::CityTreasuryWithdrawalSessionImplementation (DummyConstructorParameter * param)
Definition at line 136 of file CityTreasuryWithdrawalSession.cpp.
References _initializeImplementation().
CityTreasuryWithdrawalSessionImplementation::~CityTreasuryWithdrawalSessionImplementation () protected virtual
Definition at line 141 of file CityTreasuryWithdrawalSession.cpp.
Member Function Documentation
DistributedObjectStub * CityTreasuryWithdrawalSessionImplementation::_getStub ()
Definition at line 161 of file CityTreasuryWithdrawalSession.cpp.
References _this.
void CityTreasuryWithdrawalSessionImplementation::_initializeImplementation () protected
Definition at line 148 of file CityTreasuryWithdrawalSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CityTreasuryWithdrawalSessionImplementation().
void CityTreasuryWithdrawalSessionImplementation::_serializationHelperMethod () protected
Definition at line 197 of file CityTreasuryWithdrawalSession.cpp.
Referenced by _initializeImplementation().
void CityTreasuryWithdrawalSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 156 of file CityTreasuryWithdrawalSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::CityTreasuryWithdrawalSession::CityTreasuryWithdrawalSession().
int CityTreasuryWithdrawalSessionImplementation::cancelSession ()
Definition at line 317 of file CityTreasuryWithdrawalSession.cpp.
References SessionFacadeType::CITYWITHDRAW, and creatureObject.
Referenced by server::zone::objects::player::sessions::CityTreasuryWithdrawalSession::cancelSession(), initializeSession(), sendTransferBox(), and withdrawCredits().
int CityTreasuryWithdrawalSessionImplementation::clearSession ()
Definition at line 324 of file CityTreasuryWithdrawalSession.cpp.
Referenced by server::zone::objects::player::sessions::CityTreasuryWithdrawalSession::clearSession().
void CityTreasuryWithdrawalSessionImplementation::finalize () protected
Definition at line 145 of file CityTreasuryWithdrawalSession.cpp.
int CityTreasuryWithdrawalSessionImplementation::initializeSession ()
Definition at line 20 of file CityTreasuryWithdrawalSessionImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), cancelSession(), SuiWindowType::CITY_TREASURY_WITHDRAWAL_REASON, cityRegion, creatureObject, and terminalObject.
Referenced by server::zone::objects::player::sessions::CityTreasuryWithdrawalSession::initializeSession().
void CityTreasuryWithdrawalSessionImplementation::lock (bool doLock = true) protected
Definition at line 169 of file CityTreasuryWithdrawalSession.cpp.
References _this.
void CityTreasuryWithdrawalSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 173 of file CityTreasuryWithdrawalSession.cpp.
References _this.
CityTreasuryWithdrawalSessionImplementation::operator const CityTreasuryWithdrawalSession * ()
Definition at line 165 of file CityTreasuryWithdrawalSession.cpp.
void CityTreasuryWithdrawalSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 204 of file CityTreasuryWithdrawalSession.cpp.
References readObjectMember().
bool CityTreasuryWithdrawalSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 223 of file CityTreasuryWithdrawalSession.cpp.
References cityRegion, creatureObject, reason, and terminalObject.
Referenced by readObject().
void CityTreasuryWithdrawalSessionImplementation::rlock (bool doLock = true) protected
Definition at line 177 of file CityTreasuryWithdrawalSession.cpp.
References _this.
void CityTreasuryWithdrawalSessionImplementation::runlock (bool doLock = true) protected
Definition at line 193 of file CityTreasuryWithdrawalSession.cpp.
References _this.
int CityTreasuryWithdrawalSessionImplementation::sendTransferBox (const String & reason)
Definition at line 43 of file CityTreasuryWithdrawalSessionImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), cancelSession(), SuiWindowType::CITY_TREASURY_WITHDRAWAL, cityRegion, creatureObject, setReason(), and terminalObject.
Referenced by server::zone::objects::player::sessions::CityTreasuryWithdrawalSession::sendTransferBox().
void CityTreasuryWithdrawalSessionImplementation::setReason (const String & r)
Definition at line 312 of file CityTreasuryWithdrawalSession.cpp.
References reason.
Referenced by sendTransferBox(), and server::zone::objects::player::sessions::CityTreasuryWithdrawalSession::setReason().
void CityTreasuryWithdrawalSessionImplementation::unlock (bool doLock = true) protected
Definition at line 189 of file CityTreasuryWithdrawalSession.cpp.
References _this.
int CityTreasuryWithdrawalSessionImplementation::withdrawCredits (int value)
Definition at line 71 of file CityTreasuryWithdrawalSessionImplementation.cpp.
References cancelSession(), cityRegion, creatureObject, reason, terminalObject, and server::zone::managers::city::CityManager::withdrawFromCityTreasury().
Referenced by server::zone::objects::player::sessions::CityTreasuryWithdrawalSession::withdrawCredits().
void CityTreasuryWithdrawalSessionImplementation::wlock (bool doLock = true) protected
Definition at line 181 of file CityTreasuryWithdrawalSession.cpp.
References _this.
void CityTreasuryWithdrawalSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 185 of file CityTreasuryWithdrawalSession.cpp.
References _this.
void CityTreasuryWithdrawalSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 249 of file CityTreasuryWithdrawalSession.cpp.
References writeObjectMembers().
int CityTreasuryWithdrawalSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 256 of file CityTreasuryWithdrawalSession.cpp.
References cityRegion, creatureObject, reason, and terminalObject.
Referenced by writeObject().
Friends And Related Function Documentation
friend class CityTreasuryWithdrawalSession friend
Definition at line 184 of file CityTreasuryWithdrawalSession.h.
Member Data Documentation
WeakReference<CityTreasuryWithdrawalSession*> server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::_this
Definition at line 150 of file CityTreasuryWithdrawalSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<CityRegion* > server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::cityRegion protected
Definition at line 127 of file CityTreasuryWithdrawalSession.h.
Referenced by CityTreasuryWithdrawalSessionImplementation(), initializeSession(), readObjectMember(), sendTransferBox(), withdrawCredits(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::creatureObject protected
Definition at line 125 of file CityTreasuryWithdrawalSession.h.
Referenced by cancelSession(), CityTreasuryWithdrawalSessionImplementation(), initializeSession(), readObjectMember(), sendTransferBox(), withdrawCredits(), and writeObjectMembers().
String server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::reason protected
Definition at line 131 of file CityTreasuryWithdrawalSession.h.
Referenced by readObjectMember(), setReason(), withdrawCredits(), and writeObjectMembers().
ManagedWeakReference<SceneObject* > server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::terminalObject protected
Definition at line 129 of file CityTreasuryWithdrawalSession.h.
Referenced by CityTreasuryWithdrawalSessionImplementation(), initializeSession(), readObjectMember(), sendTransferBox(), withdrawCredits(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityTreasuryWithdrawalSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityTreasuryWithdrawalSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityTreasuryWithdrawalSessionImplementation.cpp