Core3: GroupObjectMessage6 Class Reference
GroupObjectMessage6 Class Reference
#include <GroupObjectMessage6.h>
Public Member Functions
GroupObjectMessage6 (GroupObject *gr)
void groupLists ()
Public Member Functions inherited from BaseLineMessage
BaseLineMessage (uint64 oid, uint32 name, uint8 type, uint16 opcnt)
uint32 generateRandomObjectCRC ()
void setSize ()
void insertStringId (StringId *id)
void insertCustomName (const UnicodeString &name)
Private Attributes
GroupObject * grup
Detailed Description
Definition at line 52 of file GroupObjectMessage6.h.
Constructor & Destructor Documentation
GroupObjectMessage6::GroupObjectMessage6 (GroupObject * gr) inline
Definition at line 56 of file GroupObjectMessage6.h.
References server::zone::objects::group::GroupObject::getGroupLevel(), groupLists(), grup, and BaseLineMessage::setSize().
Member Function Documentation
void GroupObjectMessage6::groupLists () inline
Definition at line 73 of file GroupObjectMessage6.h.
References server::zone::objects::group::GroupObject::getGroupList(), grup, and server::zone::objects::scene::variables::DeltaVector< E >::insertToMessage().
Referenced by GroupObjectMessage6().
Member Data Documentation
GroupObject* GroupObjectMessage6::grup private
Definition at line 53 of file GroupObjectMessage6.h.
Referenced by groupLists(), and GroupObjectMessage6().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/group/GroupObjectMessage6.h