Core3: server::zone::objects::player::sessions::StructureSetAccessFeeSession Class Reference
server::zone::objects::player::sessions::StructureSetAccessFeeSession Class Reference
#include <StructureSetAccessFeeSession.h>
Public Member Functions
StructureSetAccessFeeSession (CreatureObject *play, BuildingObject *struc)
int initializeSession ()
int cancelSession ()
int clearSession ()
void promptSetAccessFee ()
void setAccessFee (const int fee)
void promptSetAccessDuration ()
void setAccessDuration (const int duration)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
StructureSetAccessFeeSession (DummyConstructorParameter *param)
virtual ~StructureSetAccessFeeSession ()
Friends
class StructureSetAccessFeeSessionHelper
Detailed Description
Definition at line 76 of file StructureSetAccessFeeSession.h.
Constructor & Destructor Documentation
StructureSetAccessFeeSession::StructureSetAccessFeeSession (CreatureObject * play, BuildingObject * struc)
Definition at line 19 of file StructureSetAccessFeeSession.cpp.
References server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::_setStub().
StructureSetAccessFeeSession::StructureSetAccessFeeSession (DummyConstructorParameter * param) protected
Definition at line 26 of file StructureSetAccessFeeSession.cpp.
StructureSetAccessFeeSession::~StructureSetAccessFeeSession () protected virtual
Definition at line 30 of file StructureSetAccessFeeSession.cpp.
Member Function Documentation
DistributedObjectServant * StructureSetAccessFeeSession::_getImplementation ()
Definition at line 128 of file StructureSetAccessFeeSession.cpp.
Referenced by cancelSession(), clearSession(), initializeSession(), promptSetAccessDuration(), promptSetAccessFee(), setAccessDuration(), and setAccessFee().
DistributedObjectServant * StructureSetAccessFeeSession::_getImplementationForRead ()
Definition at line 134 of file StructureSetAccessFeeSession.cpp.
void StructureSetAccessFeeSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 138 of file StructureSetAccessFeeSession.cpp.
int StructureSetAccessFeeSession::cancelSession ()
Definition at line 48 of file StructureSetAccessFeeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
int StructureSetAccessFeeSession::clearSession ()
Definition at line 61 of file StructureSetAccessFeeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
int StructureSetAccessFeeSession::initializeSession ()
Definition at line 35 of file StructureSetAccessFeeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
void StructureSetAccessFeeSession::promptSetAccessDuration ()
Definition at line 101 of file StructureSetAccessFeeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::promptSetAccessDuration(), and RPC_PROMPTSETACCESSDURATION__.
void StructureSetAccessFeeSession::promptSetAccessFee ()
Definition at line 74 of file StructureSetAccessFeeSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::promptSetAccessFee(), and RPC_PROMPTSETACCESSFEE__.
void StructureSetAccessFeeSession::setAccessDuration (const int duration)
Definition at line 114 of file StructureSetAccessFeeSession.cpp.
References _getImplementation(), RPC_SETACCESSDURATION__INT_, and server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::setAccessDuration().
void StructureSetAccessFeeSession::setAccessFee (const int fee)
Definition at line 87 of file StructureSetAccessFeeSession.cpp.
References _getImplementation(), RPC_SETACCESSFEE__INT_, and server::zone::objects::player::sessions::StructureSetAccessFeeSessionImplementation::setAccessFee().
Friends And Related Function Documentation
friend class StructureSetAccessFeeSessionHelper friend
Definition at line 104 of file StructureSetAccessFeeSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureSetAccessFeeSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureSetAccessFeeSession.cpp