Core3: ObjectVersionUpdateManager Class Reference
ObjectVersionUpdateManager Class Reference
#include <ObjectVersionUpdateManager.h>
Public Member Functions
ObjectVersionUpdateManager ()
void initialize ()
void checkCurrentRevision ()
void runScripts ()
int updateToVersion2 ()
int updateToVersion3 ()
ObjectOutputStream * addVariable (String variableName, ObjectInputStream *object, Stream *newVariableData)
int getVariableDataOffset (const uint32 &variableHashCode, ObjectInputStream *stream)
ObjectOutputStream * changeVariableData (const uint32 &variableHashCode, ObjectInputStream *object, Stream *newVariableData)
void updateResidences ()
void setResidence (uint64 buildingID, bool isResidence)
void verifyResidenceVariables ()
void updateWeaponsDots ()
void updateStructurePermissionLists ()
String getOwnerName (uint64 ownerID)
void updateCityTreasury ()
int run ()
Private Attributes
Lua * luaInstance
Detailed Description
Definition at line 13 of file ObjectVersionUpdateManager.h.
Constructor & Destructor Documentation
ObjectVersionUpdateManager::ObjectVersionUpdateManager ()
Definition at line 17 of file ObjectVersionUpdateManager.cpp.
References luaInstance.
Member Function Documentation
ObjectOutputStream * ObjectVersionUpdateManager::addVariable (String variableName, ObjectInputStream * object, Stream * newVariableData)
Definition at line 99 of file ObjectVersionUpdateManager.cpp.
Referenced by setResidence().
ObjectOutputStream * ObjectVersionUpdateManager::changeVariableData (const uint32 & variableHashCode, ObjectInputStream * object, Stream * newVariableData)
Definition at line 147 of file ObjectVersionUpdateManager.cpp.
References getVariableDataOffset().
Referenced by setResidence(), updateCityTreasury(), updateStructurePermissionLists(), and updateWeaponsDots().
void ObjectVersionUpdateManager::checkCurrentRevision ()
String ObjectVersionUpdateManager::getOwnerName (uint64 ownerID)
Definition at line 327 of file ObjectVersionUpdateManager.cpp.
Referenced by updateStructurePermissionLists().
int ObjectVersionUpdateManager::getVariableDataOffset (const uint32 & variableHashCode, ObjectInputStream * stream)
Definition at line 121 of file ObjectVersionUpdateManager.cpp.
Referenced by changeVariableData().
void ObjectVersionUpdateManager::initialize ()
int ObjectVersionUpdateManager::run ()
Definition at line 23 of file ObjectVersionUpdateManager.cpp.
References INITIAL_DATABASE_VERSION, updateCityTreasury(), updateResidences(), updateStructurePermissionLists(), and updateWeaponsDots().
void ObjectVersionUpdateManager::runScripts ()
void ObjectVersionUpdateManager::setResidence (uint64 buildingID, bool isResidence)
Definition at line 418 of file ObjectVersionUpdateManager.cpp.
References addVariable(), and changeVariableData().
Referenced by updateResidences().
void ObjectVersionUpdateManager::updateCityTreasury ()
Definition at line 458 of file ObjectVersionUpdateManager.cpp.
References changeVariableData().
Referenced by run().
void ObjectVersionUpdateManager::updateResidences ()
Definition at line 358 of file ObjectVersionUpdateManager.cpp.
References setResidence().
Referenced by run().
void ObjectVersionUpdateManager::updateStructurePermissionLists ()
Definition at line 264 of file ObjectVersionUpdateManager.cpp.
References changeVariableData(), getOwnerName(), StructurePermissionList::setOwnerName(), and StructurePermissionList::toBinaryStream().
Referenced by run().
int ObjectVersionUpdateManager::updateToVersion2 ()
int ObjectVersionUpdateManager::updateToVersion3 ()
void ObjectVersionUpdateManager::updateWeaponsDots ()
Definition at line 175 of file ObjectVersionUpdateManager.cpp.
References changeVariableData().
Referenced by run().
void ObjectVersionUpdateManager::verifyResidenceVariables ()
Member Data Documentation
Lua* ObjectVersionUpdateManager::luaInstance private
Definition at line 14 of file ObjectVersionUpdateManager.h.
Referenced by ObjectVersionUpdateManager().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/object/ObjectVersionUpdateManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/object/ObjectVersionUpdateManager.cpp