Core3: server::zone::objects::player::sui::slotmachinebox::SuiSlotMachineBoxImplementation Class Reference
server::zone::objects::player::sui::slotmachinebox::SuiSlotMachineBoxImplementation Class Reference
#include <SuiSlotMachineBox.h>
Public Member Functions
SuiSlotMachineBoxImplementation (CreatureObject *player, unsigned int windowType, unsigned int payoutBox, unsigned int listBoxType=0)
SuiSlotMachineBoxImplementation (DummyConstructorParameter *param)
unsigned int getPayoutBoxID ()
operator const SuiSlotMachineBox * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::player::sui::listbox::SuiListBoxImplementation
SuiListBoxImplementation (CreatureObject *player, unsigned int windowType=0, unsigned int listBoxType=0)
SuiListBoxImplementation (DummyConstructorParameter *param)
void init ()
void addMenuItem (const String &name, unsigned long long objectID=0)
String getMenuItemName (int index)
void removeAllMenuItems ()
unsigned long long getMenuObjectID (unsigned int idx)
int getMenuSize ()
BaseMessage * generateMessage ()
void setNextBox (unsigned int boxID)
void setPreviousBox (unsigned int boxID)
unsigned long long getNextBox ()
unsigned long long getPreviousBox ()
bool isListBox ()
operator const SuiListBox * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
SuiBoxImplementation (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
SuiBoxImplementation (DummyConstructorParameter *param)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
virtual bool isInputBox ()
virtual bool isMessageBox ()
virtual bool isTransferBox ()
virtual bool isBankTransferBox ()
virtual bool isSlicingBox ()
virtual bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
operator const SuiBox * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< SuiSlotMachineBox * > _this
Public Attributes inherited from server::zone::objects::player::sui::listbox::SuiListBoxImplementation
WeakReference< SuiListBox * > _this
Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
WeakReference< SuiBox * > _this
Protected Member Functions
virtual ~SuiSlotMachineBoxImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sui::listbox::SuiListBoxImplementation
virtual ~SuiListBoxImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
virtual ~SuiBoxImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
unsigned int payoutBoxID
Protected Attributes inherited from server::zone::objects::player::sui::listbox::SuiListBoxImplementation
Vector< ManagedReference
< SuiListBoxMenuItem * > > menuItems
int type
Protected Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
ManagedWeakReference
< CreatureObject * > player
Reference< SuiCallback * > suiCallback
unsigned int boxID
ManagedWeakReference
< SceneObject * > usingObject
String handlerStr
String cancelButtonText
bool cancelButton
String okButtonText
bool okButton
String otherButtonText
bool otherButton
String promptTitle
String promptText
int boxType
unsigned int windowType
float forceCloseDistance
Vector< String > headerSets
Vector< String > optionSets
int hdrOptCount
bool hasGenerated
Friends
class SuiSlotMachineBox
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::player::sui::listbox::SuiListBoxImplementation
static const int MSGSELECTED = 0
static const int HANDLESINGLEBUTTON = 1
static const int HANDLETWOBUTTON = 2
static const int HANDLETHREEBUTTON = 3
Detailed Description
Definition at line 126 of file SuiSlotMachineBox.h.
Constructor & Destructor Documentation
SuiSlotMachineBoxImplementation::SuiSlotMachineBoxImplementation (CreatureObject * player, unsigned int windowType, unsigned int payoutBox, unsigned int listBoxType = 0)
Definition at line 194 of file SuiSlotMachineBox.cpp.
References _initializeImplementation(), and payoutBoxID.
SuiSlotMachineBoxImplementation::SuiSlotMachineBoxImplementation (DummyConstructorParameter * param)
Definition at line 68 of file SuiSlotMachineBox.cpp.
References _initializeImplementation().
SuiSlotMachineBoxImplementation::~SuiSlotMachineBoxImplementation () protected virtual
Definition at line 73 of file SuiSlotMachineBox.cpp.
Member Function Documentation
DistributedObjectStub * SuiSlotMachineBoxImplementation::_getStub ()
Definition at line 93 of file SuiSlotMachineBox.cpp.
References _this.
void SuiSlotMachineBoxImplementation::_initializeImplementation () protected
Definition at line 80 of file SuiSlotMachineBox.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SuiSlotMachineBoxImplementation().
void SuiSlotMachineBoxImplementation::_serializationHelperMethod () protected
Definition at line 129 of file SuiSlotMachineBox.cpp.
Referenced by _initializeImplementation().
void SuiSlotMachineBoxImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 88 of file SuiSlotMachineBox.cpp.
References _this.
Referenced by server::zone::objects::player::sui::slotmachinebox::SuiSlotMachineBox::SuiSlotMachineBox().
void SuiSlotMachineBoxImplementation::finalize () protected
Definition at line 77 of file SuiSlotMachineBox.cpp.
unsigned int SuiSlotMachineBoxImplementation::getPayoutBoxID ()
Definition at line 200 of file SuiSlotMachineBox.cpp.
References payoutBoxID.
Referenced by server::zone::objects::player::sui::slotmachinebox::SuiSlotMachineBox::getPayoutBoxID().
void SuiSlotMachineBoxImplementation::lock (bool doLock = true) protected
Definition at line 101 of file SuiSlotMachineBox.cpp.
References _this.
void SuiSlotMachineBoxImplementation::lock (ManagedObject * obj) protected
Definition at line 105 of file SuiSlotMachineBox.cpp.
References _this.
SuiSlotMachineBoxImplementation::operator const SuiSlotMachineBox * ()
Definition at line 97 of file SuiSlotMachineBox.cpp.
void SuiSlotMachineBoxImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::listbox::SuiListBoxImplementation.
Definition at line 136 of file SuiSlotMachineBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::initializeTransientMembers(), and readObjectMember().
bool SuiSlotMachineBoxImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 155 of file SuiSlotMachineBox.cpp.
References payoutBoxID.
Referenced by readObject().
void SuiSlotMachineBoxImplementation::rlock (bool doLock = true) protected
Definition at line 109 of file SuiSlotMachineBox.cpp.
References _this.
void SuiSlotMachineBoxImplementation::runlock (bool doLock = true) protected
Definition at line 125 of file SuiSlotMachineBox.cpp.
References _this.
void SuiSlotMachineBoxImplementation::unlock (bool doLock = true) protected
Definition at line 121 of file SuiSlotMachineBox.cpp.
References _this.
void SuiSlotMachineBoxImplementation::wlock (bool doLock = true) protected
Definition at line 113 of file SuiSlotMachineBox.cpp.
References _this.
void SuiSlotMachineBoxImplementation::wlock (ManagedObject * obj) protected
Definition at line 117 of file SuiSlotMachineBox.cpp.
References _this.
void SuiSlotMachineBoxImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::listbox::SuiListBoxImplementation.
Definition at line 169 of file SuiSlotMachineBox.cpp.
References writeObjectMembers().
int SuiSlotMachineBoxImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 176 of file SuiSlotMachineBox.cpp.
References payoutBoxID.
Referenced by writeObject().
Friends And Related Function Documentation
friend class SuiSlotMachineBox friend
Definition at line 171 of file SuiSlotMachineBox.h.
Member Data Documentation
WeakReference<SuiSlotMachineBox*> server::zone::objects::player::sui::slotmachinebox::SuiSlotMachineBoxImplementation::_this
Definition at line 137 of file SuiSlotMachineBox.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
unsigned int server::zone::objects::player::sui::slotmachinebox::SuiSlotMachineBoxImplementation::payoutBoxID protected
Definition at line 128 of file SuiSlotMachineBox.h.
Referenced by getPayoutBoxID(), readObjectMember(), SuiSlotMachineBoxImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/slotmachinebox/SuiSlotMachineBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/slotmachinebox/SuiSlotMachineBox.cpp