Core3: server::zone::managers::radial::RadialManager Class Reference
server::zone::managers::radial::RadialManager Class Reference
#include <RadialManager.h>
Public Member Functions
RadialManager (ZoneServer *server)
void handleObjectMenuSelect (CreatureObject *player, byte selectID, unsigned long long objectID)
void handleObjectMenuRequest (CreatureObject *player, ObjectMenuResponse *defaultMenuResponse, unsigned long long objectID)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
RadialManager (DummyConstructorParameter *param)
virtual ~RadialManager ()
Friends
class RadialManagerHelper
Detailed Description
Definition at line 75 of file RadialManager.h.
Constructor & Destructor Documentation
RadialManager::RadialManager (ZoneServer * server)
Definition at line 21 of file RadialManager.cpp.
References server::zone::managers::radial::RadialManagerImplementation::_setStub().
RadialManager::RadialManager (DummyConstructorParameter * param) protected
Definition at line 28 of file RadialManager.cpp.
RadialManager::~RadialManager () protected virtual
Definition at line 32 of file RadialManager.cpp.
Member Function Documentation
DistributedObjectServant * RadialManager::_getImplementation ()
Definition at line 69 of file RadialManager.cpp.
Referenced by handleObjectMenuRequest(), and handleObjectMenuSelect().
DistributedObjectServant * RadialManager::_getImplementationForRead ()
Definition at line 75 of file RadialManager.cpp.
void RadialManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 79 of file RadialManager.cpp.
void RadialManager::handleObjectMenuRequest (CreatureObject * player, ObjectMenuResponse * defaultMenuResponse, unsigned long long objectID)
Definition at line 53 of file RadialManager.cpp.
References _getImplementation(), server::zone::managers::radial::RadialManagerImplementation::handleObjectMenuRequest(), and RPC_HANDLEOBJECTMENUREQUEST__CREATUREOBJECT_OBJECTMENURESPONSE_LONG_.
Referenced by ObjectMenuRequestCallback::run().
void RadialManager::handleObjectMenuSelect (CreatureObject * player, byte selectID, unsigned long long objectID)
Definition at line 37 of file RadialManager.cpp.
References _getImplementation(), server::zone::managers::radial::RadialManagerImplementation::handleObjectMenuSelect(), and RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_LONG_.
Friends And Related Function Documentation
friend class RadialManagerHelper friend
Definition at line 93 of file RadialManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/radial/RadialManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/radial/RadialManager.cpp