Core3: ImageDesignManager Class Reference
ImageDesignManager Class Reference
#include <ImageDesignManager.h>
Public Member Functions
ImageDesignManager ()
~ImageDesignManager ()
void updateCustomization (CreatureObject *imageDesigner, const String &customizationName, float value, CreatureObject *creo=NULL)
void updateColorCustomization (CreatureObject *imageDesigner, const String &customizationName, uint32 value, TangibleObject *hairObject, CreatureObject *creo=NULL)
CustomizationData * getCustomizationData (const String &speciesGender, const String &customizationName)
String getSpeciesGenderString (CreatureObject *creo=NULL)
TangibleObject * updateHairObject (CreatureObject *creo, TangibleObject *hairObject)
TangibleObject * createHairObject (CreatureObject *imageDesigner, CreatureObject *targetObject, const String &hairTemplate, const String &hairCustomization)
Static Public Member Functions
static bool validateCustomizationString (CustomizationVariables *data, const String &appearanceFilename, int skillLevel)
static bool validatePalette (PaletteColorCustomizationVariable *variable, int value, int skillLevel)
Private Member Functions
void loadCustomizationData ()
void updateColorVariable (const Vector< String > &fullVariables, uint32 value, TangibleObject *tano, int skillLevel)
int getSkillLevel (CreatureObject *imageDesigner, const String &skillMod)
Detailed Description
Definition at line 19 of file ImageDesignManager.h.
Constructor & Destructor Documentation
ImageDesignManager::ImageDesignManager ()
Definition at line 59 of file ImageDesignManager.cpp.
References loadCustomizationData().
ImageDesignManager::~ImageDesignManager ()
Definition at line 561 of file ImageDesignManager.cpp.
Member Function Documentation
TangibleObject * ImageDesignManager::createHairObject (CreatureObject * imageDesigner, CreatureObject * targetObject, const String & hairTemplate, const String & hairCustomization)
Definition at line 379 of file ImageDesignManager.cpp.
References server::zone::ZoneServer::createObject(), server::zone::templates::SharedObjectTemplate::getAppearanceFilename(), server::zone::templates::SharedObjectTemplate::getFullTemplateString(), server::zone::objects::scene::SceneObject::getObjectTemplate(), getSkillLevel(), server::zone::objects::creature::CreatureObject::getSkillMod(), HairAssetData::getSkillModValue(), server::zone::objects::scene::SceneObject::getSlottedObject(), getSpeciesGenderString(), server::zone::objects::scene::SceneObject::getZoneServer(), CustomizationVariables::parseFromClientString(), server::zone::objects::scene::SceneObject::setContainerDefaultDenyPermission(), server::zone::objects::scene::SceneObject::setContainerDenyPermission(), server::zone::objects::tangible::TangibleObject::setCustomizationString(), and validateCustomizationString().
Referenced by server::zone::objects::player::sessions::ImageDesignSessionImplementation::updateImageDesign().
CustomizationData * ImageDesignManager::getCustomizationData (const String & speciesGender, const String & customizationName)
Definition at line 349 of file ImageDesignManager.cpp.
References PlayerCreatureTemplate::getCustomizationData(), and TemplateManager::getTemplate().
Referenced by updateColorCustomization(), and updateCustomization().
int ImageDesignManager::getSkillLevel (CreatureObject * imageDesigner, const String & skillMod) private
Definition at line 263 of file ImageDesignManager.cpp.
References server::zone::objects::creature::CreatureObject::hasSkill().
Referenced by createHairObject(), and updateColorCustomization().
String ImageDesignManager::getSpeciesGenderString (CreatureObject * creo = NULL)
Definition at line 363 of file ImageDesignManager.cpp.
References server::zone::objects::creature::CreatureObject::getGender(), and server::zone::objects::creature::CreatureObject::getSpeciesName().
Referenced by createHairObject(), updateColorCustomization(), and updateCustomization().
void ImageDesignManager::loadCustomizationData () private
Definition at line 300 of file ImageDesignManager.cpp.
References DataTableRow::getCell(), PlayerCreatureTemplate::getCustomizationDataMap(), CustomizationData::getCustomizationName(), server::zone::templates::SharedObjectTemplate::getMaxScale(), server::zone::templates::SharedObjectTemplate::getMinScale(), DataTableIff::getRow(), TemplateManager::getTemplate(), DataTableIff::getTotalRows(), TemplateManager::openIffFile(), CustomizationData::parseRow(), DataTableIff::readObject(), CustomizationData::setMaxScale(), CustomizationData::setMinScale(), and DataTableCell::toString().
Referenced by ImageDesignManager().
void ImageDesignManager::updateColorCustomization (CreatureObject * imageDesigner, const String & customizationName, uint32 value, TangibleObject * hairObject, CreatureObject * creo = NULL)
Definition at line 215 of file ImageDesignManager.cpp.
References getCustomizationData(), CustomizationData::getImageDesignSkillMod(), CustomizationData::getIsVarHairColor(), getSkillLevel(), server::zone::objects::creature::CreatureObject::getSkillMod(), CustomizationData::getSkillModValue(), getSpeciesGenderString(), CustomizationData::getType(), CustomizationData::getVariables(), and updateColorVariable().
Referenced by server::zone::objects::player::sessions::ImageDesignSessionImplementation::updateImageDesign().
void ImageDesignManager::updateColorVariable (const Vector< String > & fullVariables, uint32 value, TangibleObject * tano, int skillLevel) private
Definition at line 169 of file ImageDesignManager.cpp.
References server::zone::templates::SharedObjectTemplate::getAppearanceFilename(), RangedIntCustomizationVariable::getDefaultValue(), BasicRangedIntCustomizationVariable::getMaxValueExclusive(), BasicRangedIntCustomizationVariable::getMinValueInclusive(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::tangible::TangibleObject::setCustomizationVariable(), and validatePalette().
Referenced by updateColorCustomization().
void ImageDesignManager::updateCustomization (CreatureObject * imageDesigner, const String & customizationName, float value, CreatureObject * creo = NULL)
Definition at line 65 of file ImageDesignManager.cpp.
References server::zone::templates::SharedObjectTemplate::getAppearanceFilename(), getCustomizationData(), CustomizationData::getImageDesignSkillMod(), CustomizationData::getIsScale(), CustomizationData::getMaxScale(), BasicRangedIntCustomizationVariable::getMaxValueExclusive(), CustomizationData::getMinScale(), BasicRangedIntCustomizationVariable::getMinValueInclusive(), server::zone::objects::scene::SceneObject::getObjectTemplate(), CustomizationData::getReverse(), server::zone::objects::creature::CreatureObject::getSkillMod(), CustomizationData::getSkillModValue(), getSpeciesGenderString(), CustomizationData::getType(), and CustomizationData::getVariables().
Referenced by server::zone::objects::player::sessions::ImageDesignSessionImplementation::updateImageDesign().
TangibleObject * ImageDesignManager::updateHairObject (CreatureObject * creo, TangibleObject * hairObject)
Definition at line 426 of file ImageDesignManager.cpp.
References server::zone::objects::scene::SceneObject::broadcastObject(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::objects::player::sessions::ImageDesignSessionImplementation::updateImageDesign().
bool ImageDesignManager::validateCustomizationString (CustomizationVariables * data, const String & appearanceFilename, int skillLevel) static
Definition at line 502 of file ImageDesignManager.cpp.
References BasicRangedIntCustomizationVariable::getMaxValueExclusive(), BasicRangedIntCustomizationVariable::getMinValueInclusive(), and validatePalette().
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addCustomization(), server::zone::managers::player::creation::PlayerCreationManager::addHair(), and createHairObject().
bool ImageDesignManager::validatePalette (PaletteColorCustomizationVariable * variable, int value, int skillLevel) static
Definition at line 445 of file ImageDesignManager.cpp.
References PaletteData::getCreationIndexes(), PaletteData::getIdLevel1Indexes(), PaletteData::getIdLevel2Indexes(), PaletteData::getIdLevel3Indexes(), PaletteData::getIdLevel4Indexes(), PaletteData::getIdMasterIndexes(), PaletteData::getIdNoviceIndexes(), and PaletteColorCustomizationVariable::getPaletteFileName().
Referenced by updateColorVariable(), and validateCustomizationString().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/skill/imagedesign/ImageDesignManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/skill/imagedesign/ImageDesignManager.cpp