Core3: CreatureObjectDeltaMessage6 Class Reference
CreatureObjectDeltaMessage6 Class Reference
#include <CreatureObjectDeltaMessage6.h>
Public Member Functions
CreatureObjectDeltaMessage6 (CreatureObject *cr)
void updateWeapon ()
void updateTarget ()
void updateInviterId ()
void updateGroupID ()
void updateGuildID ()
void updateMoodID ()
void updateMoodStr ()
void updateInstrumentID (int value)
void updatePerformanceCounter (uint32 pCounter)
void updatePerformanceAnimation (const String &pAnimation)
void updateLevel (uint16 value)
Public Member Functions inherited from TangibleObjectDeltaMessage6
TangibleObjectDeltaMessage6 (TangibleObject *ta, uint32 objType=0x54414E4F)
Public Member Functions inherited from DeltaMessage
DeltaMessage (uint64 oid, uint32 name, uint8 type)
uint32 generateRandomObjectCRC ()
void startUpdate (uint16 type)
void addByteUpdate (uint16 type, uint8 value)
void addShortUpdate (uint16 type, uint16 value)
void addIntUpdate (uint16 type, uint32 value)
void addLongUpdate (uint16 type, uint64 value)
void addFloatUpdate (uint16 type, float value)
void addAsciiUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const UnicodeString &val)
void startList (uint32 cnt, uint32 updcnt)
void addListIntElement (uint16 index, uint32 value)
void addListFloatElement (uint16 index, float value)
void addListLongElement (uint16 index, uint64 value)
void addListAsciiElement (const String &value)
void removeListIntElement (uint16 index, uint32 value)
void removeListFloatElement (uint16 index, float value)
void removeListLongElement (uint16 index, uint64 value)
void removeListLongElement (uint16 index)
void removeListAsciiElement (const String &value)
void close ()
Private Attributes
CreatureObject * creo
Detailed Description
Definition at line 54 of file CreatureObjectDeltaMessage6.h.
Constructor & Destructor Documentation
CreatureObjectDeltaMessage6::CreatureObjectDeltaMessage6 (CreatureObject * cr) inline
Definition at line 58 of file CreatureObjectDeltaMessage6.h.
References creo.
Member Function Documentation
void CreatureObjectDeltaMessage6::updateGroupID () inline
Definition at line 78 of file CreatureObjectDeltaMessage6.h.
References DeltaMessage::addLongUpdate(), creo, and server::zone::objects::creature::CreatureObject::getGroupID().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::updateGroup().
void CreatureObjectDeltaMessage6::updateGuildID () inline
Definition at line 82 of file CreatureObjectDeltaMessage6.h.
References DeltaMessage::addIntUpdate(), creo, and server::zone::objects::creature::CreatureObject::getGuildID().
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::managers::guild::GuildManagerImplementation::createGuild(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), and server::zone::managers::guild::GuildManagerImplementation::leaveGuild().
void CreatureObjectDeltaMessage6::updateInstrumentID (int value) inline
Definition at line 94 of file CreatureObjectDeltaMessage6.h.
References DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainingUpdate(), and server::zone::objects::creature::CreatureObjectImplementation::setInstrumentID().
void CreatureObjectDeltaMessage6::updateInviterId () inline
Definition at line 71 of file CreatureObjectDeltaMessage6.h.
References creo, server::zone::objects::creature::CreatureObject::getGroupInviteCounter(), server::zone::objects::creature::CreatureObject::getGroupInviterID(), and DeltaMessage::startUpdate().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::updateGroupInviterID().
void CreatureObjectDeltaMessage6::updateLevel (uint16 value) inline
Definition at line 109 of file CreatureObjectDeltaMessage6.h.
References DeltaMessage::startUpdate().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::setLevel().
void CreatureObjectDeltaMessage6::updateMoodID () inline
Definition at line 86 of file CreatureObjectDeltaMessage6.h.
References DeltaMessage::addByteUpdate(), creo, and server::zone::objects::creature::CreatureObject::getMoodID().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::setMood().
void CreatureObjectDeltaMessage6::updateMoodStr () inline
Definition at line 90 of file CreatureObjectDeltaMessage6.h.
References DeltaMessage::addAsciiUpdate(), creo, and server::zone::objects::creature::CreatureObject::getMoodString().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::setMood(), and server::zone::objects::creature::CreatureObjectImplementation::setMoodString().
void CreatureObjectDeltaMessage6::updatePerformanceAnimation (const String & pAnimation) inline
Definition at line 104 of file CreatureObjectDeltaMessage6.h.
References DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainingUpdate(), and server::zone::objects::creature::CreatureObjectImplementation::setPerformanceAnimation().
void CreatureObjectDeltaMessage6::updatePerformanceCounter (uint32 pCounter) inline
Definition at line 99 of file CreatureObjectDeltaMessage6.h.
References DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainingUpdate(), and server::zone::objects::creature::CreatureObjectImplementation::setPerformanceCounter().
void CreatureObjectDeltaMessage6::updateTarget () inline
Definition at line 67 of file CreatureObjectDeltaMessage6.h.
References DeltaMessage::addLongUpdate(), creo, and server::zone::objects::creature::CreatureObject::getTargetID().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::setTargetID().
void CreatureObjectDeltaMessage6::updateWeapon () inline
Definition at line 63 of file CreatureObjectDeltaMessage6.h.
References DeltaMessage::addLongUpdate(), creo, and server::zone::objects::creature::CreatureObject::getWeaponID().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::setWeapon().
Member Data Documentation
CreatureObject* CreatureObjectDeltaMessage6::creo private
Definition at line 55 of file CreatureObjectDeltaMessage6.h.
Referenced by CreatureObjectDeltaMessage6(), updateGroupID(), updateGuildID(), updateInviterId(), updateMoodID(), updateMoodStr(), updateTarget(), and updateWeapon().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/creature/CreatureObjectDeltaMessage6.h