Core3: PlayersNearYouMessage Class Reference
PlayersNearYouMessage Class Reference
#include <PlayersNearYou.h>
Public Member Functions
PlayersNearYouMessage (CreatureObject *creo)
void addFoundPlayer (CreatureObject *player)
void insertPlayerCounter (uint32 foundCount)
Public Member Functions inherited from ObjectControllerMessage
ObjectControllerMessage (uint64 objid, uint32 header1, uint32 header2, bool comp=true)
Detailed Description
Definition at line 57 of file PlayersNearYou.h.
Constructor & Destructor Documentation
PlayersNearYouMessage::PlayersNearYouMessage (CreatureObject * creo) inline
Definition at line 59 of file PlayersNearYou.h.
Member Function Documentation
void PlayersNearYouMessage::addFoundPlayer (CreatureObject * player) inline
Definition at line 64 of file PlayersNearYou.h.
References server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), Races::getRaceID(), Region::getRegionName(), server::zone::objects::scene::SceneObject::getZone(), and server::zone::Zone::getZoneName().
void PlayersNearYouMessage::insertPlayerCounter (uint32 foundCount) inline
Definition at line 82 of file PlayersNearYou.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/object/PlayersNearYou.h