Core3: server::zone::objects::tangible::threat::ThreatMapEntry Class Reference
server::zone::objects::tangible::threat::ThreatMapEntry Class Reference
#include <ThreatMap.h>
Public Member Functions
ThreatMapEntry ()
ThreatMapEntry (const ThreatMapEntry &e)
ThreatMapEntry & operator= (const ThreatMapEntry &e)
void addDamage (WeaponObject *weapon, uint32 damage)
void addDamage (String xp, uint32 damage)
void setThreatState (uint64 state)
bool hasState (uint64 state)
void clearThreatState (uint64 state)
void addAggro (int value)
void addHeal (int value)
int getHeal ()
int getAggroMod ()
void removeAggro (int value)
void clearAggro ()
Private Attributes
int aggroMod
uint64 threatBitmask
int healAmount
Detailed Description
Definition at line 41 of file ThreatMap.h.
Constructor & Destructor Documentation
server::zone::objects::tangible::threat::ThreatMapEntry::ThreatMapEntry () inline
Definition at line 48 of file ThreatMap.h.
server::zone::objects::tangible::threat::ThreatMapEntry::ThreatMapEntry (const ThreatMapEntry & e) inline
Definition at line 55 of file ThreatMap.h.
References aggroMod, healAmount, and threatBitmask.
Member Function Documentation
void server::zone::objects::tangible::threat::ThreatMapEntry::addAggro (int value) inline
Definition at line 78 of file ThreatMap.h.
Referenced by server::zone::objects::tangible::threat::ThreatMap::addAggro(), server::zone::objects::tangible::threat::ThreatMap::addDamage(), and server::zone::objects::tangible::threat::ThreatMap::addHeal().
void ThreatMapEntry::addDamage (WeaponObject * weapon, uint32 damage)
Definition at line 16 of file ThreatMap.cpp.
References server::zone::objects::tangible::weapon::WeaponObject::getXpType().
Referenced by server::zone::objects::tangible::threat::ThreatMap::addDamage().
void ThreatMapEntry::addDamage (String xp, uint32 damage)
Definition at line 20 of file ThreatMap.cpp.
void server::zone::objects::tangible::threat::ThreatMapEntry::addHeal (int value) inline
Definition at line 82 of file ThreatMap.h.
Referenced by server::zone::objects::tangible::threat::ThreatMap::addHeal().
void server::zone::objects::tangible::threat::ThreatMapEntry::clearAggro () inline
Definition at line 98 of file ThreatMap.h.
Referenced by server::zone::objects::tangible::threat::ThreatMap::clearAggro().
void ThreatMapEntry::clearThreatState (uint64 state)
Definition at line 46 of file ThreatMap.cpp.
References threatBitmask.
Referenced by server::zone::objects::tangible::threat::ThreatMap::clearThreatState().
int server::zone::objects::tangible::threat::ThreatMapEntry::getAggroMod () inline
Definition at line 90 of file ThreatMap.h.
Referenced by server::zone::objects::tangible::threat::ThreatMatrix::add().
int server::zone::objects::tangible::threat::ThreatMapEntry::getHeal () inline
Definition at line 86 of file ThreatMap.h.
Referenced by server::zone::objects::tangible::threat::ThreatMatrix::add().
bool ThreatMapEntry::hasState (uint64 state)
Definition at line 39 of file ThreatMap.cpp.
References threatBitmask.
Referenced by server::zone::objects::tangible::threat::ThreatMatrix::add(), and server::zone::objects::tangible::threat::ThreatMap::hasState().
ThreatMapEntry& server::zone::objects::tangible::threat::ThreatMapEntry::operator= (const ThreatMapEntry & e) inline
Definition at line 62 of file ThreatMap.h.
References aggroMod, healAmount, and threatBitmask.
void server::zone::objects::tangible::threat::ThreatMapEntry::removeAggro (int value) inline
Definition at line 94 of file ThreatMap.h.
Referenced by server::zone::objects::tangible::threat::ThreatMap::removeAggro().
void ThreatMapEntry::setThreatState (uint64 state)
Definition at line 33 of file ThreatMap.cpp.
References threatBitmask.
Referenced by server::zone::objects::tangible::threat::ThreatMap::setThreatState().
Member Data Documentation
int server::zone::objects::tangible::threat::ThreatMapEntry::aggroMod private
Definition at line 43 of file ThreatMap.h.
Referenced by operator=(), and ThreatMapEntry().
int server::zone::objects::tangible::threat::ThreatMapEntry::healAmount private
Definition at line 45 of file ThreatMap.h.
Referenced by operator=(), and ThreatMapEntry().
uint64 server::zone::objects::tangible::threat::ThreatMapEntry::threatBitmask private
Definition at line 44 of file ThreatMap.h.
Referenced by clearThreatState(), hasState(), operator=(), setThreatState(), and ThreatMapEntry().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/threat/ThreatMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/threat/ThreatMap.cpp