Core3: ResourceMap Class Reference
ResourceMap Class Reference
#include <ResourceMap.h>
Public Member Functions
ResourceMap ()
~ResourceMap ()
void add (const String &resname, ManagedReference< ResourceSpawn * > resourceSpawn)
void remove (ManagedReference< ResourceSpawn * > resourceSpawn)
void remove (ManagedReference< ResourceSpawn * > resourceSpawn, String zoneName)
float getDensityAt (const String &resourcename, String zoneName, float x, float y)
ZoneResourceMap * getZoneResourceList (String zoneName)
bool containsType (const String &typeName)
bool containsSpawn (const String &spawnName)
void addToSuiListBox (SuiListBox *sui, const String &nodeName)
Private Attributes
VectorMap< String,
ZoneResourceMap * > zoneResourceMap
VectorMap< String,
TypeResourceMap * > typeResourceMap
Detailed Description
ResourceMap contains all resources ever spawned indexed by unique spawn name. Also contains a map of active resources separated by a zone id
Definition at line 106 of file ResourceMap.h.
Constructor & Destructor Documentation
ResourceMap::ResourceMap ()
Definition at line 54 of file ResourceMap.cpp.
References typeResourceMap, and zoneResourceMap.
ResourceMap::~ResourceMap ()
Definition at line 64 of file ResourceMap.cpp.
Member Function Documentation
void ResourceMap::add (const String & resname, ManagedReference< ResourceSpawn * > resourceSpawn)
Adds the resource spawn to the global spawn map and if spawned, it add it to the individual region map for surveying and sampling/.
Parameters
resname The unique name of the resource spawn
resourceSpawn The ResourceSpawn object to be added
Index the resources by type, for resource deeds
Definition at line 73 of file ResourceMap.cpp.
References typeResourceMap, and zoneResourceMap.
Referenced by ResourceSpawner::createRecycledResourceSpawn(), ResourceSpawner::createResourceSpawn(), ResourceSpawner::loadResourceSpawns(), and ResourceSpawner::spawnScriptResources().
void ResourceMap::addToSuiListBox (SuiListBox * sui, const String & nodeName)
Adds the resources in particular map to SUI for resource deed
Parameters
sui Listbox
nodeName name of resource
Definition at line 125 of file ResourceMap.cpp.
References server::zone::objects::player::sui::listbox::SuiListBox::addMenuItem(), and typeResourceMap.
Referenced by ResourceSpawner::addNodeToListBox(), and ResourceSpawner::addParentNodeToListBox().
bool ResourceMap::containsSpawn (const String & spawnName) inline
Definition at line 169 of file ResourceMap.h.
bool ResourceMap::containsType (const String & typeName) inline
Checks to see if the type resource map contains the specified type or not.
Parameters
typeName The type to check. For example, "aluminum_phrik".
Returns
Returns true if the map contains the type.
Definition at line 165 of file ResourceMap.h.
Referenced by ResourceSpawner::addNodeToListBox(), and ResourceSpawner::getRecycledVersion().
float ResourceMap::getDensityAt (const String & resourcename, String zoneName, float x, float y)
Get's the density value of resource at given point
Parameters
resourcename The name of the resource
zoneid The zone map id
x The value of the x coordinate
y The value of the y coordinate
Returns
Value between -1 and 1 indicating density
Definition at line 68 of file ResourceMap.cpp.
Referenced by ResourceSpawner::sendSample(), and ResourceSpawner::sendSurvey().
ZoneResourceMap* ResourceMap::getZoneResourceList (String zoneName) inline
Get's the density value of resource at given point
Parameters
zoneid ID of zone being requesting
Returns
ZoneResourceMap* value of the zoneid requested
Definition at line 153 of file ResourceMap.h.
Referenced by ResourceSpawner::getCurrentSpawn(), server::zone::managers::resource::ResourceManagerImplementation::getResourceListByType(), ResourceSpawner::harvestResource(), ResourceSpawner::listResourcesForPlanetOnScreen(), and ResourceSpawner::sendResourceListForSurvey().
void ResourceMap::remove (ManagedReference< ResourceSpawn * > resourceSpawn)
Removes resource from global spawn map
Parameters
resourceSpawn The ResourceSpawn object to be removed
Even though we want to drop items from the Zone maps, we need to keep all spawns in the ResourceMap for lookup.
Definition at line 104 of file ResourceMap.cpp.
References zoneResourceMap.
Referenced by ResourceSpawner::despawn().
void ResourceMap::remove (ManagedReference< ResourceSpawn * > resourceSpawn, String zoneName)
Removes resource from the zone spawn map
Parameters
resourceSpawn The ResourceSpawn object to be removed
zoneid The zone that is despawning resource
Definition at line 118 of file ResourceMap.cpp.
References zoneResourceMap.
Member Data Documentation
VectorMap<String, TypeResourceMap*> ResourceMap::typeResourceMap private
Definition at line 110 of file ResourceMap.h.
Referenced by add(), addToSuiListBox(), and ResourceMap().
VectorMap<String, ZoneResourceMap*> ResourceMap::zoneResourceMap private
Definition at line 109 of file ResourceMap.h.
Referenced by add(), remove(), and ResourceMap().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcemap/ResourceMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcemap/ResourceMap.cpp