Core3: server::zone::objects::creature::buffs::BuffAdapter Class Reference
server::zone::objects::creature::buffs::BuffAdapter Class Reference
#include <Buff.h>
Public Member Functions
BuffAdapter (Buff *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
void sendTo (CreatureObject *player)
void sendDestroyTo (CreatureObject *player)
void activate (bool applyModifiers)
void deactivate (bool removeModifiers)
void activate ()
void deactivate ()
void applyAttributeModifiers ()
void applySkillModifiers ()
void applyStates ()
void removeAttributeModifiers ()
void removeSkillModifiers ()
void removeStates ()
void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
void parseAttributeModifierString (const String &modifierstring)
void parseSkillModifierString (const String &modifierstring)
String getAttributeModifierString ()
String getSkillModifierString ()
float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
int getAttributeModifierValue (byte attribute)
int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
Detailed Description
Definition at line 391 of file Buff.h.
Constructor & Destructor Documentation
BuffAdapter::BuffAdapter (Buff * impl)
Definition at line 1178 of file Buff.cpp.
Member Function Documentation
void BuffAdapter::activate (bool applyModifiers)
Definition at line 1425 of file Buff.cpp.
void BuffAdapter::activate ()
Definition at line 1433 of file Buff.cpp.
Referenced by server::zone::objects::creature::buffs::StateBuffAdapter::invokeMethod(), server::zone::objects::creature::buffs::SpiceDownerBuffAdapter::invokeMethod(), server::zone::objects::creature::buffs::PerformanceBuffAdapter::invokeMethod(), server::zone::objects::creature::buffs::DurationBuffAdapter::invokeMethod(), server::zone::objects::creature::buffs::SpiceBuffAdapter::invokeMethod(), server::zone::objects::creature::buffs::PowerBoostBuffAdapter::invokeMethod(), and invokeMethod().
void BuffAdapter::addState (unsigned long long option)
Definition at line 1505 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::applyAttributeModifiers ()
Definition at line 1441 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::applySkillModifiers ()
Definition at line 1445 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::applyStates ()
Definition at line 1449 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::clearBuffEvent ()
Definition at line 1465 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::deactivate (bool removeModifiers)
Definition at line 1429 of file Buff.cpp.
void BuffAdapter::deactivate ()
Definition at line 1437 of file Buff.cpp.
Referenced by server::zone::objects::creature::buffs::StateBuffAdapter::invokeMethod(), server::zone::objects::creature::buffs::SpiceDownerBuffAdapter::invokeMethod(), server::zone::objects::creature::buffs::PerformanceBuffAdapter::invokeMethod(), server::zone::objects::creature::buffs::DurationBuffAdapter::invokeMethod(), server::zone::objects::creature::buffs::SpiceBuffAdapter::invokeMethod(), server::zone::objects::creature::buffs::PowerBoostBuffAdapter::invokeMethod(), and invokeMethod().
String BuffAdapter::getAttributeModifierString ()
Definition at line 1485 of file Buff.cpp.
Referenced by invokeMethod().
int BuffAdapter::getAttributeModifierValue (byte attribute)
Definition at line 1537 of file Buff.cpp.
Referenced by invokeMethod().
int BuffAdapter::getBuffCRC ()
Definition at line 1525 of file Buff.cpp.
Referenced by invokeMethod().
float BuffAdapter::getBuffDuration ()
Definition at line 1529 of file Buff.cpp.
Referenced by invokeMethod().
String BuffAdapter::getBuffName ()
Definition at line 1521 of file Buff.cpp.
Referenced by invokeMethod().
int BuffAdapter::getBuffType ()
Definition at line 1533 of file Buff.cpp.
Referenced by invokeMethod().
String BuffAdapter::getSkillModifierString ()
Definition at line 1489 of file Buff.cpp.
Referenced by invokeMethod().
int BuffAdapter::getSkillModifierValue (const String & modname)
Definition at line 1541 of file Buff.cpp.
Referenced by invokeMethod().
float BuffAdapter::getTimeLeft ()
Definition at line 1493 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::init ()
Definition at line 1413 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::initializeTransientMembers ()
Definition at line 1401 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1181 of file Buff.cpp.
References activate(), addState(), applyAttributeModifiers(), applySkillModifiers(), applyStates(), clearBuffEvent(), deactivate(), getAttributeModifierString(), getAttributeModifierValue(), getBuffCRC(), getBuffDuration(), getBuffName(), getBuffType(), getSkillModifierString(), getSkillModifierValue(), getTimeLeft(), init(), initializeTransientMembers(), isActive(), isAttributeBuff(), isSpiceBuff(), loadBuffDurationEvent(), notifyLoadFromDatabase(), parseAttributeModifierString(), parseSkillModifierString(), removeAttributeModifiers(), removeSkillModifiers(), removeStates(), RPC_ACTIVATE__, RPC_ACTIVATE__BOOL_, RPC_ADDSTATE__LONG_, RPC_APPLYATTRIBUTEMODIFIERS__, RPC_APPLYSKILLMODIFIERS__, RPC_APPLYSTATES__, RPC_CLEARBUFFEVENT__, RPC_DEACTIVATE__, RPC_DEACTIVATE__BOOL_, RPC_GETATTRIBUTEMODIFIERSTRING__, RPC_GETATTRIBUTEMODIFIERVALUE__BYTE_, RPC_GETBUFFCRC__, RPC_GETBUFFDURATION__, RPC_GETBUFFNAME__, RPC_GETBUFFTYPE__, RPC_GETSKILLMODIFIERSTRING__, RPC_GETSKILLMODIFIERVALUE__STRING_, RPC_GETTIMELEFT__, RPC_INIT__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_ISACTIVE__, RPC_ISATTRIBUTEBUFF__, RPC_ISSPICEBUFF__, RPC_LOADBUFFDURATIONEVENT__CREATUREOBJECT_, RPC_NOTIFYLOADFROMDATABASE__, RPC_PARSEATTRIBUTEMODIFIERSTRING__STRING_, RPC_PARSESKILLMODIFIERSTRING__STRING_, RPC_REMOVEATTRIBUTEMODIFIERS__, RPC_REMOVESKILLMODIFIERS__, RPC_REMOVESTATES__, RPC_SCHEDULEBUFFEVENT__, RPC_SENDDESTROYTO__CREATUREOBJECT_, RPC_SENDTO__CREATUREOBJECT_, RPC_SETACCELERATIONMULTIPLIERMOD__FLOAT_, RPC_SETATTRIBUTEMODIFIER__BYTE_INT_, RPC_SETBUFFEVENTNULL__, RPC_SETENDFLYTEXT__STRING_STRING_BYTE_BYTE_BYTE_, RPC_SETFILLATTRIBUTESONBUFF__BOOL_, RPC_SETSKILLMODIFIER__STRING_INT_, RPC_SETSPEEDMULTIPLIERMOD__FLOAT_, RPC_SETSTARTFLYTEXT__STRING_STRING_BYTE_BYTE_BYTE_, scheduleBuffEvent(), sendDestroyTo(), sendTo(), setAccelerationMultiplierMod(), setAttributeModifier(), setBuffEventNull(), setEndFlyText(), setFillAttributesOnBuff(), setSkillModifier(), setSpeedMultiplierMod(), and setStartFlyText().
bool BuffAdapter::isActive ()
Definition at line 1545 of file Buff.cpp.
Referenced by invokeMethod().
bool BuffAdapter::isAttributeBuff ()
Definition at line 1553 of file Buff.cpp.
Referenced by invokeMethod().
bool BuffAdapter::isSpiceBuff ()
Definition at line 1549 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::loadBuffDurationEvent (CreatureObject * creo)
Definition at line 1409 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::notifyLoadFromDatabase ()
Definition at line 1405 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::parseAttributeModifierString (const String & modifierstring)
Definition at line 1477 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::parseSkillModifierString (const String & modifierstring)
Definition at line 1481 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::removeAttributeModifiers ()
Definition at line 1453 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::removeSkillModifiers ()
Definition at line 1457 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::removeStates ()
Definition at line 1461 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::scheduleBuffEvent ()
Definition at line 1473 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::sendDestroyTo (CreatureObject * player)
Definition at line 1421 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::sendTo (CreatureObject * player)
Definition at line 1417 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::setAccelerationMultiplierMod (float multiplier)
Definition at line 1513 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::setAttributeModifier (byte attribute, int value)
Definition at line 1497 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::setBuffEventNull ()
Definition at line 1469 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::setEndFlyText (const String & file, const String & aux, byte red, byte green, byte blue)
Definition at line 1561 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::setFillAttributesOnBuff (bool val)
Definition at line 1517 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::setSkillModifier (const String & modname, int value)
Definition at line 1501 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::setSpeedMultiplierMod (float multiplier)
Definition at line 1509 of file Buff.cpp.
Referenced by invokeMethod().
void BuffAdapter::setStartFlyText (const String & file, const String & aux, byte red, byte green, byte blue)
Definition at line 1557 of file Buff.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/Buff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/Buff.cpp