Core3: server::zone::objects::player::sessions::TrainerConversationSessionImplementation Class Reference
server::zone::objects::player::sessions::TrainerConversationSessionImplementation Class Reference
#include <TrainerConversationSession.h>
Public Member Functions
TrainerConversationSessionImplementation (CreatureObject *npc)
TrainerConversationSessionImplementation (DummyConstructorParameter *param)
void clearTrainableSkills ()
void addTrainableSkill (String &skillName)
String getTrainableSkills (int selectedOption)
int getTrainableSkillsCount ()
void clearNextSkills ()
void addNextSkill (String &skillName)
String getNextSkill (int selectedOption)
int getNextSkillsCount ()
void setSelectedSkill (String &skillName)
String getSelectedSkill ()
String getMasterSkill ()
void setMasterSkill (String &skillName)
void addAdditionalMasterSkill (String &skillName)
String getAdditionalMasterSkill (int selectedOption)
int getAdditionalMasterSkillsCount ()
operator const TrainerConversationSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::player::sessions::ConversationSessionImplementation
ConversationSessionImplementation (CreatureObject *conversingCreature)
ConversationSessionImplementation (DummyConstructorParameter *param)
void setLastConversationScreen (ConversationScreen *screen)
ConversationScreen * getLastConversationScreen ()
ManagedWeakReference
< CreatureObject * > getNPC ()
operator const ConversationSession * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< TrainerConversationSession * > _this
Public Attributes inherited from server::zone::objects::player::sessions::ConversationSessionImplementation
WeakReference
< ConversationSession * > _this
Protected Member Functions
virtual ~TrainerConversationSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sessions::ConversationSessionImplementation
virtual ~ConversationSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
Vector< String > trainableSkills
Vector< String > nextSkills
String masterSkill
Vector< String > additionalMasterSkills
String selectedSkill
Friends
class TrainerConversationSession
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::player::sessions::ConversationSessionImplementation
Reference< ConversationScreen * > lastConversationScreen
ManagedWeakReference
< CreatureObject * > npc
Detailed Description
Definition at line 101 of file TrainerConversationSession.h.
Constructor & Destructor Documentation
TrainerConversationSessionImplementation::TrainerConversationSessionImplementation (CreatureObject * npc)
Definition at line 436 of file TrainerConversationSession.cpp.
References _initializeImplementation().
TrainerConversationSessionImplementation::TrainerConversationSessionImplementation (DummyConstructorParameter * param)
Definition at line 262 of file TrainerConversationSession.cpp.
References _initializeImplementation().
TrainerConversationSessionImplementation::~TrainerConversationSessionImplementation () protected virtual
Definition at line 267 of file TrainerConversationSession.cpp.
Member Function Documentation
DistributedObjectStub * TrainerConversationSessionImplementation::_getStub ()
Definition at line 287 of file TrainerConversationSession.cpp.
References _this.
void TrainerConversationSessionImplementation::_initializeImplementation () protected
Definition at line 274 of file TrainerConversationSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by TrainerConversationSessionImplementation().
void TrainerConversationSessionImplementation::_serializationHelperMethod () protected
Definition at line 323 of file TrainerConversationSession.cpp.
References server::zone::objects::player::sessions::ConversationSessionImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void TrainerConversationSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 282 of file TrainerConversationSession.cpp.
References server::zone::objects::player::sessions::ConversationSessionImplementation::_setStub(), and _this.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::TrainerConversationSession().
void TrainerConversationSessionImplementation::addAdditionalMasterSkill (String & skillName)
Definition at line 490 of file TrainerConversationSession.cpp.
References additionalMasterSkills.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::addAdditionalMasterSkill().
void TrainerConversationSessionImplementation::addNextSkill (String & skillName)
Definition at line 455 of file TrainerConversationSession.cpp.
References nextSkills.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::addNextSkill().
void TrainerConversationSessionImplementation::addTrainableSkill (String & skillName)
Definition at line 440 of file TrainerConversationSession.cpp.
References trainableSkills.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::addTrainableSkill().
void TrainerConversationSessionImplementation::clearNextSkills ()
Definition at line 53 of file TrainerConversationSessionImplementation.cpp.
References nextSkills.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::clearNextSkills().
void TrainerConversationSessionImplementation::clearTrainableSkills ()
Definition at line 47 of file TrainerConversationSessionImplementation.cpp.
References trainableSkills.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::clearTrainableSkills().
void TrainerConversationSessionImplementation::finalize () protected
Definition at line 271 of file TrainerConversationSession.cpp.
String TrainerConversationSessionImplementation::getAdditionalMasterSkill (int selectedOption)
Definition at line 495 of file TrainerConversationSession.cpp.
References additionalMasterSkills.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::getAdditionalMasterSkill().
int TrainerConversationSessionImplementation::getAdditionalMasterSkillsCount ()
Definition at line 500 of file TrainerConversationSession.cpp.
References additionalMasterSkills.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::getAdditionalMasterSkillsCount().
String TrainerConversationSessionImplementation::getMasterSkill ()
Definition at line 480 of file TrainerConversationSession.cpp.
References masterSkill.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::getMasterSkill().
String TrainerConversationSessionImplementation::getNextSkill (int selectedOption)
Definition at line 460 of file TrainerConversationSession.cpp.
References nextSkills.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::getNextSkill().
int TrainerConversationSessionImplementation::getNextSkillsCount ()
Definition at line 465 of file TrainerConversationSession.cpp.
References nextSkills.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::getNextSkillsCount().
String TrainerConversationSessionImplementation::getSelectedSkill ()
Definition at line 475 of file TrainerConversationSession.cpp.
References selectedSkill.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::getSelectedSkill().
String TrainerConversationSessionImplementation::getTrainableSkills (int selectedOption)
Definition at line 445 of file TrainerConversationSession.cpp.
References trainableSkills.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::getTrainableSkills().
int TrainerConversationSessionImplementation::getTrainableSkillsCount ()
Definition at line 450 of file TrainerConversationSession.cpp.
References trainableSkills.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::getTrainableSkillsCount().
void TrainerConversationSessionImplementation::lock (bool doLock = true) protected
Definition at line 295 of file TrainerConversationSession.cpp.
References _this.
void TrainerConversationSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 299 of file TrainerConversationSession.cpp.
References _this.
TrainerConversationSessionImplementation::operator const TrainerConversationSession * ()
Definition at line 291 of file TrainerConversationSession.cpp.
void TrainerConversationSessionImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::player::sessions::ConversationSessionImplementation.
Definition at line 330 of file TrainerConversationSession.cpp.
References readObjectMember().
bool TrainerConversationSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 349 of file TrainerConversationSession.cpp.
References additionalMasterSkills, masterSkill, nextSkills, server::zone::objects::player::sessions::ConversationSessionImplementation::readObjectMember(), selectedSkill, and trainableSkills.
Referenced by readObject().
void TrainerConversationSessionImplementation::rlock (bool doLock = true) protected
Definition at line 303 of file TrainerConversationSession.cpp.
References _this.
void TrainerConversationSessionImplementation::runlock (bool doLock = true) protected
Definition at line 319 of file TrainerConversationSession.cpp.
References _this.
void TrainerConversationSessionImplementation::setMasterSkill (String & skillName)
Definition at line 485 of file TrainerConversationSession.cpp.
References masterSkill.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::setMasterSkill().
void TrainerConversationSessionImplementation::setSelectedSkill (String & skillName)
Definition at line 470 of file TrainerConversationSession.cpp.
References selectedSkill.
Referenced by server::zone::objects::player::sessions::TrainerConversationSession::setSelectedSkill().
void TrainerConversationSessionImplementation::unlock (bool doLock = true) protected
Definition at line 315 of file TrainerConversationSession.cpp.
References _this.
void TrainerConversationSessionImplementation::wlock (bool doLock = true) protected
Definition at line 307 of file TrainerConversationSession.cpp.
References _this.
void TrainerConversationSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 311 of file TrainerConversationSession.cpp.
References _this.
void TrainerConversationSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::player::sessions::ConversationSessionImplementation.
Definition at line 379 of file TrainerConversationSession.cpp.
References writeObjectMembers().
int TrainerConversationSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 386 of file TrainerConversationSession.cpp.
References additionalMasterSkills, masterSkill, nextSkills, selectedSkill, trainableSkills, and server::zone::objects::player::sessions::ConversationSessionImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class TrainerConversationSession friend
Definition at line 181 of file TrainerConversationSession.h.
Member Data Documentation
WeakReference<TrainerConversationSession*> server::zone::objects::player::sessions::TrainerConversationSessionImplementation::_this
Definition at line 147 of file TrainerConversationSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
Vector<String> server::zone::objects::player::sessions::TrainerConversationSessionImplementation::additionalMasterSkills private
Definition at line 108 of file TrainerConversationSession.h.
Referenced by addAdditionalMasterSkill(), getAdditionalMasterSkill(), getAdditionalMasterSkillsCount(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sessions::TrainerConversationSessionImplementation::masterSkill private
Definition at line 106 of file TrainerConversationSession.h.
Referenced by getMasterSkill(), readObjectMember(), setMasterSkill(), and writeObjectMembers().
Vector<String> server::zone::objects::player::sessions::TrainerConversationSessionImplementation::nextSkills private
Definition at line 104 of file TrainerConversationSession.h.
Referenced by addNextSkill(), clearNextSkills(), getNextSkill(), getNextSkillsCount(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sessions::TrainerConversationSessionImplementation::selectedSkill private
Definition at line 110 of file TrainerConversationSession.h.
Referenced by getSelectedSkill(), readObjectMember(), setSelectedSkill(), and writeObjectMembers().
Vector<String> server::zone::objects::player::sessions::TrainerConversationSessionImplementation::trainableSkills private
Definition at line 102 of file TrainerConversationSession.h.
Referenced by addTrainableSkill(), clearTrainableSkills(), getTrainableSkills(), getTrainableSkillsCount(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TrainerConversationSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TrainerConversationSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TrainerConversationSessionImplementation.cpp