Core3: VehicleCustomKitObjectMenuComponent Class Reference
VehicleCustomKitObjectMenuComponent Class Reference
#include <VehicleCustomKitObjectMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file VehicleCustomKitObjectMenuComponent.h.
Member Function Documentation
void VehicleCustomKitObjectMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from TangibleObjectMenuComponent.
Definition at line 21 of file VehicleCustomKitObjectMenuComponent.cpp.
References TangibleObjectMenuComponent::fillObjectMenuResponse(), and server::zone::objects::scene::SceneObject::isTangibleObject().
int VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from TangibleObjectMenuComponent.
Definition at line 33 of file VehicleCustomKitObjectMenuComponent.cpp.
References SuiWindowType::CUSTOMIZE_KIT, server::zone::objects::creature::CreatureObject::getCreatureLinkID(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::getTargetID(), server::zone::objects::scene::SceneObject::getZoneServer(), TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::scene::SceneObject::isASubChildOf(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::objects::creature::VehicleObject::refreshPaint(), server::zone::objects::creature::CreatureObject::sendMessage(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/VehicleCustomKitObjectMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/VehicleCustomKitObjectMenuComponent.cpp