Core3: server::zone::objects::player::sessions::DestroyStructureSessionImplementation Class Reference
server::zone::objects::player::sessions::DestroyStructureSessionImplementation Class Reference
#include <DestroyStructureSession.h>
Public Member Functions
DestroyStructureSessionImplementation (CreatureObject *creature, StructureObject *structure)
DestroyStructureSessionImplementation (DummyConstructorParameter *param)
bool isDestroyCode (unsigned int code)
int initializeSession ()
int sendDestroyCode ()
int destroyStructure ()
int cancelSession ()
int clearSession ()
StructureObject * getStructureObject ()
operator const DestroyStructureSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< DestroyStructureSession * > _this
Protected Member Functions
virtual ~DestroyStructureSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference
< CreatureObject * > creatureObject
ManagedReference
< StructureObject * > structureObject
unsigned int destroyCode
Friends
class DestroyStructureSession
Detailed Description
Definition at line 111 of file DestroyStructureSession.h.
Constructor & Destructor Documentation
DestroyStructureSessionImplementation::DestroyStructureSessionImplementation (CreatureObject * creature, StructureObject * structure)
Definition at line 295 of file DestroyStructureSession.cpp.
References _initializeImplementation(), creatureObject, destroyCode, and structureObject.
DestroyStructureSessionImplementation::DestroyStructureSessionImplementation (DummyConstructorParameter * param)
Definition at line 145 of file DestroyStructureSession.cpp.
References _initializeImplementation().
DestroyStructureSessionImplementation::~DestroyStructureSessionImplementation () protected virtual
Definition at line 150 of file DestroyStructureSession.cpp.
Member Function Documentation
DistributedObjectStub * DestroyStructureSessionImplementation::_getStub ()
Definition at line 170 of file DestroyStructureSession.cpp.
References _this.
void DestroyStructureSessionImplementation::_initializeImplementation () protected
Definition at line 157 of file DestroyStructureSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by DestroyStructureSessionImplementation().
void DestroyStructureSessionImplementation::_serializationHelperMethod () protected
Definition at line 206 of file DestroyStructureSession.cpp.
Referenced by _initializeImplementation().
void DestroyStructureSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 165 of file DestroyStructureSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::DestroyStructureSession::DestroyStructureSession().
int DestroyStructureSessionImplementation::cancelSession ()
Definition at line 314 of file DestroyStructureSession.cpp.
References creatureObject, and SessionFacadeType::DESTROYSTRUCTURE.
Referenced by server::zone::objects::player::sessions::DestroyStructureSession::cancelSession(), destroyStructure(), initializeSession(), and sendDestroyCode().
int DestroyStructureSessionImplementation::clearSession ()
Definition at line 321 of file DestroyStructureSession.cpp.
Referenced by server::zone::objects::player::sessions::DestroyStructureSession::clearSession().
int DestroyStructureSessionImplementation::destroyStructure ()
Definition at line 106 of file DestroyStructureSessionImplementation.cpp.
References cancelSession(), creatureObject, server::zone::managers::gcw::GCWManager::doBaseDestruction(), server::zone::Zone::getGCWManager(), and structureObject.
Referenced by server::zone::objects::player::sessions::DestroyStructureSession::destroyStructure().
void DestroyStructureSessionImplementation::finalize () protected
Definition at line 154 of file DestroyStructureSession.cpp.
StructureObject * DestroyStructureSessionImplementation::getStructureObject ()
Definition at line 326 of file DestroyStructureSession.cpp.
References structureObject.
Referenced by server::zone::objects::player::sessions::DestroyStructureSession::getStructureObject().
int DestroyStructureSessionImplementation::initializeSession ()
Definition at line 21 of file DestroyStructureSessionImplementation.cpp.
References _this, cancelSession(), creatureObject, SessionFacadeType::DESTROYSTRUCTURE, server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::sendMessage(), and structureObject.
Referenced by server::zone::objects::player::sessions::DestroyStructureSession::initializeSession().
bool DestroyStructureSessionImplementation::isDestroyCode (unsigned int code)
Definition at line 309 of file DestroyStructureSession.cpp.
References destroyCode.
Referenced by server::zone::objects::player::sessions::DestroyStructureSession::isDestroyCode().
void DestroyStructureSessionImplementation::lock (bool doLock = true) protected
Definition at line 178 of file DestroyStructureSession.cpp.
References _this.
void DestroyStructureSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 182 of file DestroyStructureSession.cpp.
References _this.
DestroyStructureSessionImplementation::operator const DestroyStructureSession * ()
Definition at line 174 of file DestroyStructureSession.cpp.
void DestroyStructureSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 213 of file DestroyStructureSession.cpp.
References readObjectMember().
bool DestroyStructureSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 232 of file DestroyStructureSession.cpp.
References creatureObject, destroyCode, and structureObject.
Referenced by readObject().
void DestroyStructureSessionImplementation::rlock (bool doLock = true) protected
Definition at line 186 of file DestroyStructureSession.cpp.
References _this.
void DestroyStructureSessionImplementation::runlock (bool doLock = true) protected
Definition at line 202 of file DestroyStructureSession.cpp.
References _this.
int DestroyStructureSessionImplementation::sendDestroyCode ()
Definition at line 69 of file DestroyStructureSessionImplementation.cpp.
References cancelSession(), creatureObject, destroyCode, server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::sendMessage(), and structureObject.
Referenced by server::zone::objects::player::sessions::DestroyStructureSession::sendDestroyCode().
void DestroyStructureSessionImplementation::unlock (bool doLock = true) protected
Definition at line 198 of file DestroyStructureSession.cpp.
References _this.
void DestroyStructureSessionImplementation::wlock (bool doLock = true) protected
Definition at line 190 of file DestroyStructureSession.cpp.
References _this.
void DestroyStructureSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 194 of file DestroyStructureSession.cpp.
References _this.
void DestroyStructureSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 254 of file DestroyStructureSession.cpp.
References writeObjectMembers().
int DestroyStructureSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 261 of file DestroyStructureSession.cpp.
References creatureObject, destroyCode, and structureObject.
Referenced by writeObject().
Friends And Related Function Documentation
friend class DestroyStructureSession friend
Definition at line 172 of file DestroyStructureSession.h.
Member Data Documentation
WeakReference<DestroyStructureSession*> server::zone::objects::player::sessions::DestroyStructureSessionImplementation::_this
Definition at line 138 of file DestroyStructureSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), initializeSession(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedReference<CreatureObject* > server::zone::objects::player::sessions::DestroyStructureSessionImplementation::creatureObject protected
Definition at line 113 of file DestroyStructureSession.h.
Referenced by cancelSession(), destroyStructure(), DestroyStructureSessionImplementation(), initializeSession(), readObjectMember(), sendDestroyCode(), and writeObjectMembers().
unsigned int server::zone::objects::player::sessions::DestroyStructureSessionImplementation::destroyCode protected
Definition at line 117 of file DestroyStructureSession.h.
Referenced by DestroyStructureSessionImplementation(), isDestroyCode(), readObjectMember(), sendDestroyCode(), and writeObjectMembers().
ManagedReference<StructureObject* > server::zone::objects::player::sessions::DestroyStructureSessionImplementation::structureObject protected
Definition at line 115 of file DestroyStructureSession.h.
Referenced by destroyStructure(), DestroyStructureSessionImplementation(), getStructureObject(), initializeSession(), readObjectMember(), sendDestroyCode(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/DestroyStructureSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/DestroyStructureSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/DestroyStructureSessionImplementation.cpp