Core3: server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler Class Reference
server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler Class Reference
#include <DeliverMissionScreenHandler.h>
Public Member Functions
DeliverMissionScreenHandler ()
ConversationScreen * handleScreen (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::conversation::screenhandlers::ScreenHandler
ScreenHandler ()
~ScreenHandler ()
String getNextScreenId ()
Static Public Attributes
static const String STARTSCREENHANDLERID = "convoscreenstart"
Protected Member Functions
MissionObject * getRelevantMissionObject (CreatureObject *player, CreatureObject *npc)
bool isTargetNpc (DeliverMissionObjective *objective, const Vector3 &npcPosition)
bool isDestinationNpc (DeliverMissionObjective *objective, const Vector3 &npcPosition)
bool isSameSpawnPoint (const float &positionX, const float &positionY, const Vector3 &comparisonPosition)
void performPickupConversation (ConversationScreen *conversationScreen, MissionObject *mission)
void performDeliverConversation (ConversationScreen *conversationScreen, MissionObject *mission)
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::conversation::screenhandlers::ScreenHandler
String nextScreenId
Detailed Description
Definition at line 60 of file DeliverMissionScreenHandler.h.
Constructor & Destructor Documentation
server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::DeliverMissionScreenHandler () inline
Definition at line 77 of file DeliverMissionScreenHandler.h.
Member Function Documentation
MissionObject * DeliverMissionScreenHandler::getRelevantMissionObject (CreatureObject * player, CreatureObject * npc) protected
Definition at line 51 of file DeliverMissionScreenHandler.cpp.
References server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::getSlottedObject(), isDestinationNpc(), and isTargetNpc().
Referenced by handleScreen().
ConversationScreen * DeliverMissionScreenHandler::handleScreen (CreatureObject * conversingPlayer, CreatureObject * conversingNPC, int selectedOption, ConversationScreen * conversationScreen) virtual
Implements server::zone::objects::creature::conversation::screenhandlers::ScreenHandler.
Definition at line 159 of file DeliverMissionScreenHandler.cpp.
References server::zone::objects::mission::MissionObject::getMissionObjective(), server::zone::objects::mission::DeliverMissionObjective::getObjectiveStatus(), getRelevantMissionObject(), isTargetNpc(), performDeliverConversation(), performPickupConversation(), server::zone::templates::mobile::ConversationScreen::setDialogText(), and server::zone::objects::mission::DeliverMissionObjective::updateMissionStatus().
bool DeliverMissionScreenHandler::isDestinationNpc (DeliverMissionObjective * objective, const Vector3 & npcPosition) protected
Definition at line 90 of file DeliverMissionScreenHandler.cpp.
References server::zone::objects::mission::DeliverMissionObjective::getDestinationSpawnPoint(), server::zone::managers::mission::spawnmaps::NpcSpawnPoint::getPosition(), and isSameSpawnPoint().
Referenced by getRelevantMissionObject().
bool DeliverMissionScreenHandler::isSameSpawnPoint (const float & positionX, const float & positionY, const Vector3 & comparisonPosition) protected
Definition at line 94 of file DeliverMissionScreenHandler.cpp.
Referenced by isDestinationNpc(), and isTargetNpc().
bool DeliverMissionScreenHandler::isTargetNpc (DeliverMissionObjective * objective, const Vector3 & npcPosition) protected
Definition at line 86 of file DeliverMissionScreenHandler.cpp.
References server::zone::managers::mission::spawnmaps::NpcSpawnPoint::getPosition(), server::zone::objects::mission::DeliverMissionObjective::getTargetSpawnPoint(), and isSameSpawnPoint().
Referenced by getRelevantMissionObject(), and handleScreen().
bool server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::parseFromBinaryStream (ObjectInputStream * stream) inline
Definition at line 85 of file DeliverMissionScreenHandler.h.
void DeliverMissionScreenHandler::performDeliverConversation (ConversationScreen * conversationScreen, MissionObject * mission) protected
Definition at line 131 of file DeliverMissionScreenHandler.cpp.
References server::zone::objects::mission::MissionObject::getFaction(), server::zone::objects::mission::MissionObject::getMissionNumber(), server::zone::objects::mission::MissionObject::getTypeCRC(), and server::zone::templates::mobile::ConversationScreen::setDialogText().
Referenced by handleScreen().
void DeliverMissionScreenHandler::performPickupConversation (ConversationScreen * conversationScreen, MissionObject * mission) protected
Definition at line 103 of file DeliverMissionScreenHandler.cpp.
References server::zone::objects::mission::MissionObject::getFaction(), server::zone::objects::mission::MissionObject::getMissionNumber(), server::zone::objects::mission::MissionObject::getTypeCRC(), and server::zone::templates::mobile::ConversationScreen::setDialogText().
Referenced by handleScreen().
bool server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::toBinaryStream (ObjectOutputStream * stream) inline
Definition at line 81 of file DeliverMissionScreenHandler.h.
Member Data Documentation
const String DeliverMissionScreenHandler::STARTSCREENHANDLERID = "convoscreenstart" static
Definition at line 75 of file DeliverMissionScreenHandler.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/screenhandlers/DeliverMissionScreenHandler.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/screenhandlers/DeliverMissionScreenHandler.cpp