Core3: TreeFile Class Reference
TreeFile Class Reference
#include <TreeFile.h>
Public Member Functions
TreeFile (TreeArchive *archive)
~TreeFile ()
void read (const String &path)
Private Member Functions
void readHeader (FileInputStream *fileStream)
void readFileBlock (FileInputStream *fileStream)
void readNameBlock (FileInputStream *fileStream)
void readMD5Sums (FileInputStream *fileStream)
Private Attributes
TreeArchive * treeArchive
String filePath
int version
int totalRecords
int dataOffset
TreeDataBlock fileBlock
TreeDataBlock nameBlock
Vector< Reference
< TreeFileRecord * > > records
Detailed Description
Definition at line 17 of file TreeFile.h.
Constructor & Destructor Documentation
TreeFile::TreeFile (TreeArchive * archive)
Definition at line 12 of file TreeFile.cpp.
References treeArchive, and version.
TreeFile::~TreeFile ()
Definition at line 17 of file TreeFile.cpp.
Member Function Documentation
void TreeFile::read (const String & path)
Definition at line 20 of file TreeFile.cpp.
References filePath, and readHeader().
Referenced by TreeArchive::unpackFile().
void TreeFile::readFileBlock (FileInputStream * fileStream) private
Definition at line 95 of file TreeFile.cpp.
References dataOffset, fileBlock, filePath, records, totalRecords, and TreeDataBlock::uncompress().
Referenced by readHeader().
void TreeFile::readHeader (FileInputStream * fileStream) private
Definition at line 43 of file TreeFile.cpp.
References dataOffset, fileBlock, nameBlock, readFileBlock(), readMD5Sums(), readNameBlock(), TreeDataBlock::setCompressedSize(), TreeDataBlock::setCompressionType(), TreeDataBlock::setUncompressedSize(), TreeDataBlock::SIZE, totalRecords, and version.
Referenced by read().
void TreeFile::readMD5Sums (FileInputStream * fileStream) private
Definition at line 125 of file TreeFile.cpp.
References records, TreeFileRecord::setMD5Sum(), and totalRecords.
Referenced by readHeader().
void TreeFile::readNameBlock (FileInputStream * fileStream) private
Definition at line 112 of file TreeFile.cpp.
References TreeArchive::addRecord(), TreeFileRecord::getNameOffset(), nameBlock, records, totalRecords, treeArchive, and TreeDataBlock::uncompress().
Referenced by readHeader().
Member Data Documentation
int TreeFile::dataOffset private
Definition at line 23 of file TreeFile.h.
Referenced by readFileBlock(), and readHeader().
TreeDataBlock TreeFile::fileBlock private
Definition at line 25 of file TreeFile.h.
Referenced by readFileBlock(), and readHeader().
String TreeFile::filePath private
Definition at line 20 of file TreeFile.h.
Referenced by read(), and readFileBlock().
TreeDataBlock TreeFile::nameBlock private
Definition at line 26 of file TreeFile.h.
Referenced by readHeader(), and readNameBlock().
Vector<Reference<TreeFileRecord*> > TreeFile::records private
Definition at line 28 of file TreeFile.h.
Referenced by readFileBlock(), readMD5Sums(), and readNameBlock().
int TreeFile::totalRecords private
Definition at line 22 of file TreeFile.h.
Referenced by readFileBlock(), readHeader(), readMD5Sums(), and readNameBlock().
TreeArchive* TreeFile::treeArchive private
Definition at line 18 of file TreeFile.h.
Referenced by readNameBlock(), and TreeFile().
int TreeFile::version private
Definition at line 21 of file TreeFile.h.
Referenced by readHeader(), and TreeFile().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/tre3/TreeFile.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/tre3/TreeFile.cpp