Core3: server::zone::objects::creature::buffs::SingleUseBuff Class Reference
server::zone::objects::creature::buffs::SingleUseBuff Class Reference
#include <SingleUseBuff.h>
Public Member Functions
SingleUseBuff (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype, unsigned int comCRC)
void init (Vector< unsigned int > *events)
unsigned int getCommandCRC ()
CreatureObject * getPlayer ()
void activate ()
void deactivate ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::creature::buffs::Buff
Buff (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
void sendTo (CreatureObject *player)
void sendDestroyTo (CreatureObject *player)
void activate (bool applyModifiers)
void deactivate (bool removeModifiers)
void activate ()
void deactivate ()
VectorMap< String, int > * getSkillModifiers ()
void applyAttributeModifiers ()
void applySkillModifiers ()
void applyStates ()
void removeAttributeModifiers ()
void removeSkillModifiers ()
void removeStates ()
void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
void parseAttributeModifierString (const String &modifierstring)
void parseSkillModifierString (const String &modifierstring)
String getAttributeModifierString ()
String getSkillModifierString ()
float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
VectorMap< byte, int > * getAttributeModifiers ()
int getAttributeModifierValue (byte attribute)
int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartMessage (StringIdChatParameter &start)
void setEndMessage (StringIdChatParameter &end)
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
SingleUseBuff (DummyConstructorParameter *param)
virtual ~SingleUseBuff ()
Protected Member Functions inherited from server::zone::objects::creature::buffs::Buff
Buff (DummyConstructorParameter *param)
virtual ~Buff ()
Friends
class SingleUseBuffHelper
Detailed Description
Definition at line 80 of file SingleUseBuff.h.
Constructor & Destructor Documentation
SingleUseBuff::SingleUseBuff (CreatureObject * creo, unsigned int buffcrc, float duration, int bufftype, unsigned int comCRC)
Definition at line 19 of file SingleUseBuff.cpp.
References server::zone::objects::creature::buffs::SingleUseBuffImplementation::_setStub().
SingleUseBuff::SingleUseBuff (DummyConstructorParameter * param) protected
Definition at line 26 of file SingleUseBuff.cpp.
SingleUseBuff::~SingleUseBuff () protected virtual
Definition at line 30 of file SingleUseBuff.cpp.
Member Function Documentation
DistributedObjectServant * SingleUseBuff::_getImplementation ()
Definition at line 96 of file SingleUseBuff.cpp.
Referenced by activate(), deactivate(), getCommandCRC(), getPlayer(), and init().
DistributedObjectServant * SingleUseBuff::_getImplementationForRead ()
Definition at line 102 of file SingleUseBuff.cpp.
void SingleUseBuff::_setImplementation (DistributedObjectServant * servant)
Definition at line 106 of file SingleUseBuff.cpp.
void SingleUseBuff::activate ()
Definition at line 70 of file SingleUseBuff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::SingleUseBuffImplementation::activate(), and RPC_ACTIVATE__.
void SingleUseBuff::deactivate ()
Definition at line 83 of file SingleUseBuff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::SingleUseBuffImplementation::deactivate(), and RPC_DEACTIVATE__.
unsigned int SingleUseBuff::getCommandCRC ()
Definition at line 44 of file SingleUseBuff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::SingleUseBuffImplementation::getCommandCRC(), and RPC_GETCOMMANDCRC__.
CreatureObject * SingleUseBuff::getPlayer ()
Definition at line 57 of file SingleUseBuff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::SingleUseBuffImplementation::getPlayer(), and RPC_GETPLAYER__.
void SingleUseBuff::init (Vector< unsigned int > * events)
Definition at line 35 of file SingleUseBuff.cpp.
References _getImplementation(), and server::zone::objects::creature::buffs::SingleUseBuffImplementation::init().
Friends And Related Function Documentation
friend class SingleUseBuffHelper friend
Definition at line 104 of file SingleUseBuff.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SingleUseBuff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SingleUseBuff.cpp