Core3: SelectCharacterCallback Class Reference
SelectCharacterCallback Class Reference
#include <SelectCharacterCallback.h>
Public Member Functions
SelectCharacterCallback (ZoneClientSession *client, ZoneProcessServer *server)
void parse (Message *message)
void run ()
Public Member Functions inherited from server::zone::packets::MessageCallback
MessageCallback (ZoneClientSession *client, ZoneProcessServer *server)
virtual ~MessageCallback ()
int getTaskQueue ()
bool parseMessage (Message *packet)
ZoneClientSession * getClient ()
ZoneProcessServer * getServer ()
Private Attributes
uint64 characterID
Additional Inherited Members
Protected Attributes inherited from server::zone::packets::MessageCallback
Reference< ZoneClientSession * > client
ManagedReference
< ZoneProcessServer * > server
int taskqueue
Detailed Description
Definition at line 25 of file SelectCharacterCallback.h.
Constructor & Destructor Documentation
SelectCharacterCallback::SelectCharacterCallback (ZoneClientSession * client, ZoneProcessServer * server) inline
Definition at line 28 of file SelectCharacterCallback.h.
Member Function Documentation
void SelectCharacterCallback::parse (Message * message) inline virtual
Implements server::zone::packets::MessageCallback.
Definition at line 33 of file SelectCharacterCallback.h.
References characterID.
void SelectCharacterCallback::run () inline
Definition at line 37 of file SelectCharacterCallback.h.
References server::chat::ChatManager::addPlayer(), characterID, server::zone::packets::MessageCallback::client, DisconnectClientEvent::DISCONNECT, server::zone::ZoneClientSession::disconnect(), server::zone::ZoneServer::getChatManager(), server::zone::objects::creature::CreatureObject::getClient(), server::zone::ZoneServer::getConnectionCount(), server::zone::ZoneServer::getGalaxyID(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getParent(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getRootParent(), server::zone::ZoneServer::getServerCap(), server::zone::ZoneServer::getZone(), server::zone::objects::scene::SceneObject::getZone(), server::zone::managers::player::PlayerManager::increaseOnlineCharCountIfPossible(), server::zone::ZoneServer::isServerLoading(), server::zone::ZoneServer::isServerLocked(), server::chat::ChatManager::loadMail(), server::zone::managers::player::PlayerManager::sendLoginMessage(), server::zone::objects::creature::CreatureObject::sendToOwner(), server::zone::packets::MessageCallback::server, server::zone::objects::creature::CreatureObject::setClient(), server::zone::objects::scene::SceneObject::setMovementCounter(), and server::zone::objects::scene::SceneObject::transferObject().
Member Data Documentation
uint64 SelectCharacterCallback::characterID private
Definition at line 26 of file SelectCharacterCallback.h.
Referenced by parse(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/zone/SelectCharacterCallback.h