Core3: server::zone::objects::player::sessions::vendor::VendorAdBarkingSession Class Reference
server::zone::objects::player::sessions::vendor::VendorAdBarkingSession Class Reference
#include <VendorAdBarkingSession.h>
Public Member Functions
VendorAdBarkingSession (CreatureObject *play, SceneObject *vend)
int initializeSession ()
int cancelSession ()
int clearSession ()
void setMessage (const String &mess)
void setMood (const String &mo)
void setAnimation (const String &ani)
void sendPhraseOptions ()
void sendCustomMessageInput ()
void sendMoodSelect ()
void sendAnimationSelect ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
VendorAdBarkingSession (DummyConstructorParameter *param)
virtual ~VendorAdBarkingSession ()
Friends
class VendorAdBarkingSessionHelper
Detailed Description
Definition at line 65 of file VendorAdBarkingSession.h.
Constructor & Destructor Documentation
VendorAdBarkingSession::VendorAdBarkingSession (CreatureObject * play, SceneObject * vend)
Definition at line 17 of file VendorAdBarkingSession.cpp.
References server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::_setStub().
VendorAdBarkingSession::VendorAdBarkingSession (DummyConstructorParameter * param) protected
Definition at line 24 of file VendorAdBarkingSession.cpp.
VendorAdBarkingSession::~VendorAdBarkingSession () protected virtual
Definition at line 28 of file VendorAdBarkingSession.cpp.
Member Function Documentation
DistributedObjectServant * VendorAdBarkingSession::_getImplementation ()
Definition at line 166 of file VendorAdBarkingSession.cpp.
Referenced by cancelSession(), clearSession(), initializeSession(), sendAnimationSelect(), sendCustomMessageInput(), sendMoodSelect(), sendPhraseOptions(), setAnimation(), setMessage(), and setMood().
DistributedObjectServant * VendorAdBarkingSession::_getImplementationForRead ()
Definition at line 172 of file VendorAdBarkingSession.cpp.
void VendorAdBarkingSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 176 of file VendorAdBarkingSession.cpp.
int VendorAdBarkingSession::cancelSession ()
Definition at line 46 of file VendorAdBarkingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
Referenced by AdBarkingPhraseSuiCallback::handleSelectPhrase().
int VendorAdBarkingSession::clearSession ()
Definition at line 59 of file VendorAdBarkingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
int VendorAdBarkingSession::initializeSession ()
Definition at line 33 of file VendorAdBarkingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
void VendorAdBarkingSession::sendAnimationSelect ()
Definition at line 153 of file VendorAdBarkingSession.cpp.
References _getImplementation(), RPC_SENDANIMATIONSELECT__, and server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::sendAnimationSelect().
void VendorAdBarkingSession::sendCustomMessageInput ()
Definition at line 127 of file VendorAdBarkingSession.cpp.
References _getImplementation(), RPC_SENDCUSTOMMESSAGEINPUT__, and server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::sendCustomMessageInput().
Referenced by AdBarkingPhraseSuiCallback::handleSelectPhrase().
void VendorAdBarkingSession::sendMoodSelect ()
Definition at line 140 of file VendorAdBarkingSession.cpp.
References _getImplementation(), RPC_SENDMOODSELECT__, and server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::sendMoodSelect().
void VendorAdBarkingSession::sendPhraseOptions ()
Definition at line 114 of file VendorAdBarkingSession.cpp.
References _getImplementation(), RPC_SENDPHRASEOPTIONS__, and server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::sendPhraseOptions().
Referenced by AdBarkingPhraseSuiCallback::handleCustomMessage(), AdBarkingPhraseSuiCallback::handleSelectAnimation(), and AdBarkingPhraseSuiCallback::handleSelectMood().
void VendorAdBarkingSession::setAnimation (const String & ani)
Definition at line 100 of file VendorAdBarkingSession.cpp.
References _getImplementation(), RPC_SETANIMATION__STRING_, and server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::setAnimation().
Referenced by AdBarkingPhraseSuiCallback::handleSelectAnimation().
void VendorAdBarkingSession::setMessage (const String & mess)
Definition at line 72 of file VendorAdBarkingSession.cpp.
References _getImplementation(), RPC_SETMESSAGE__STRING_, and server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::setMessage().
Referenced by AdBarkingPhraseSuiCallback::handleCustomMessage(), and AdBarkingPhraseSuiCallback::handleSelectPhrase().
void VendorAdBarkingSession::setMood (const String & mo)
Definition at line 86 of file VendorAdBarkingSession.cpp.
References _getImplementation(), RPC_SETMOOD__STRING_, and server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::setMood().
Referenced by AdBarkingPhraseSuiCallback::handleSelectMood().
Friends And Related Function Documentation
friend class VendorAdBarkingSessionHelper friend
Definition at line 99 of file VendorAdBarkingSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/VendorAdBarkingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/VendorAdBarkingSession.cpp