Core3: OnlineZoneClientMap Class Reference
OnlineZoneClientMap Class Reference
#include <OnlineZoneClientMap.h>
Public Member Functions
void addAccount (const String &ip, uint32 accountId)
void accountLoggedOut (const String &ip, uint32 accountId)
SortedVector< uint32 > getAccountsLoggedIn (const String &ip)
int getDistinctIps ()
Protected Attributes
HashTable< String, Reference
< SortedVector< uint32 > * > > ips
ReadWriteLock mutex
Detailed Description
Definition at line 15 of file OnlineZoneClientMap.h.
Member Function Documentation
void OnlineZoneClientMap::accountLoggedOut (const String & ip, uint32 accountId) inline
Definition at line 42 of file OnlineZoneClientMap.h.
References ServerDatabase::instance(), ips, and mutex.
Referenced by server::zone::managers::player::PlayerManagerImplementation::decreaseOnlineCharCount().
void OnlineZoneClientMap::addAccount (const String & ip, uint32 accountId) inline
Definition at line 21 of file OnlineZoneClientMap.h.
References ServerDatabase::instance(), ips, and mutex.
Referenced by server::zone::managers::player::PlayerManagerImplementation::increaseOnlineCharCountIfPossible().
SortedVector<uint32> OnlineZoneClientMap::getAccountsLoggedIn (const String & ip) inline
Definition at line 61 of file OnlineZoneClientMap.h.
References ips, and mutex.
Referenced by GetAccountInfoCommand::doQueueCommand().
int OnlineZoneClientMap::getDistinctIps () inline
Definition at line 75 of file OnlineZoneClientMap.h.
References ips.
Member Data Documentation
HashTable<String, Reference<SortedVector<uint32>*> > OnlineZoneClientMap::ips protected
Definition at line 17 of file OnlineZoneClientMap.h.
Referenced by accountLoggedOut(), addAccount(), getAccountsLoggedIn(), and getDistinctIps().
ReadWriteLock OnlineZoneClientMap::mutex protected
Definition at line 18 of file OnlineZoneClientMap.h.
Referenced by accountLoggedOut(), addAccount(), and getAccountsLoggedIn().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/OnlineZoneClientMap.h