Core3: ComponentAppearanceTemplate Class Reference
ComponentAppearanceTemplate Class Reference
#include <ComponentAppearanceTemplate.h>
Public Member Functions
ComponentAppearanceTemplate ()
~ComponentAppearanceTemplate ()
void readObject (IffStream *templateData)
void parse (IffStream *iffStream)
AppearanceTemplate * getFirstMesh ()
Public Member Functions inherited from AppearanceTemplate
virtual ~AppearanceTemplate ()
Private Attributes
AppearanceTemplate * firstMesh
Detailed Description
Definition at line 15 of file ComponentAppearanceTemplate.h.
Constructor & Destructor Documentation
ComponentAppearanceTemplate::ComponentAppearanceTemplate () inline
Definition at line 19 of file ComponentAppearanceTemplate.h.
References firstMesh.
ComponentAppearanceTemplate::~ComponentAppearanceTemplate () inline
Definition at line 23 of file ComponentAppearanceTemplate.h.
Member Function Documentation
AppearanceTemplate* ComponentAppearanceTemplate::getFirstMesh () inline virtual
Reimplemented from AppearanceTemplate.
Definition at line 68 of file ComponentAppearanceTemplate.h.
References firstMesh.
void ComponentAppearanceTemplate::parse (IffStream * iffStream) inline
Definition at line 31 of file ComponentAppearanceTemplate.h.
References firstMesh, AppearanceTemplate::getFirstMesh(), and AppearanceTemplate::readObject().
Referenced by readObject().
void ComponentAppearanceTemplate::readObject (IffStream * templateData) inline virtual
Reimplemented from AppearanceTemplate.
Definition at line 27 of file ComponentAppearanceTemplate.h.
References parse().
Member Data Documentation
AppearanceTemplate* ComponentAppearanceTemplate::firstMesh private
Definition at line 16 of file ComponentAppearanceTemplate.h.
Referenced by ComponentAppearanceTemplate(), getFirstMesh(), and parse().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/ComponentAppearanceTemplate.h