Core3: server::zone::objects::player::sessions::SlicingSessionAdapter Class Reference
server::zone::objects::player::sessions::SlicingSessionAdapter Class Reference
#include <SlicingSession.h>
Public Member Functions
SlicingSessionAdapter (SlicingSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession ()
int cancelSession ()
int clearSession ()
void endSlicing ()
bool isBaseSlice ()
void setBaseSlice (bool val)
int getSlicingSkill (CreatureObject *slicer)
bool hasPrecisionLaserKnife (bool removeItem)
bool hasWeaponUpgradeKit ()
bool hasArmorUpgradeKit ()
void useClampFromInventory (SlicingTool *clamp)
Detailed Description
Definition at line 251 of file SlicingSession.h.
Constructor & Destructor Documentation
SlicingSessionAdapter::SlicingSessionAdapter (SlicingSession * impl)
Definition at line 514 of file SlicingSession.cpp.
Member Function Documentation
int SlicingSessionAdapter::cancelSession ()
Definition at line 585 of file SlicingSession.cpp.
Referenced by invokeMethod().
int SlicingSessionAdapter::clearSession ()
Definition at line 589 of file SlicingSession.cpp.
Referenced by invokeMethod().
void SlicingSessionAdapter::endSlicing ()
Definition at line 593 of file SlicingSession.cpp.
Referenced by invokeMethod().
int SlicingSessionAdapter::getSlicingSkill (CreatureObject * slicer)
Definition at line 605 of file SlicingSession.cpp.
Referenced by invokeMethod().
bool SlicingSessionAdapter::hasArmorUpgradeKit ()
Definition at line 617 of file SlicingSession.cpp.
Referenced by invokeMethod().
bool SlicingSessionAdapter::hasPrecisionLaserKnife (bool removeItem)
Definition at line 609 of file SlicingSession.cpp.
Referenced by invokeMethod().
bool SlicingSessionAdapter::hasWeaponUpgradeKit ()
Definition at line 613 of file SlicingSession.cpp.
Referenced by invokeMethod().
int SlicingSessionAdapter::initializeSession ()
Definition at line 581 of file SlicingSession.cpp.
Referenced by invokeMethod().
void SlicingSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 517 of file SlicingSession.cpp.
References cancelSession(), clearSession(), endSlicing(), getSlicingSkill(), hasArmorUpgradeKit(), hasPrecisionLaserKnife(), hasWeaponUpgradeKit(), initializeSession(), isBaseSlice(), RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_ENDSLICING__, RPC_GETSLICINGSKILL__CREATUREOBJECT_, RPC_HASARMORUPGRADEKIT__, RPC_HASPRECISIONLASERKNIFE__BOOL_, RPC_HASWEAPONUPGRADEKIT__, RPC_INITIALIZESESSION__, RPC_ISBASESLICE__, RPC_SETBASESLICE__BOOL_, RPC_USECLAMPFROMINVENTORY__SLICINGTOOL_, setBaseSlice(), and useClampFromInventory().
bool SlicingSessionAdapter::isBaseSlice ()
Definition at line 597 of file SlicingSession.cpp.
Referenced by invokeMethod().
void SlicingSessionAdapter::setBaseSlice (bool val)
Definition at line 601 of file SlicingSession.cpp.
Referenced by invokeMethod().
void SlicingSessionAdapter::useClampFromInventory (SlicingTool * clamp)
Definition at line 621 of file SlicingSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/SlicingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/SlicingSession.cpp