Core3: server::zone::objects::installation::TurretObserverImplementation Class Reference
server::zone::objects::installation::TurretObserverImplementation Class Reference
#include <TurretObserver.h>
Public Member Functions
TurretObserverImplementation ()
TurretObserverImplementation (DummyConstructorParameter *param)
virtual int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const TurretObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< TurretObserver * > _this
Protected Member Functions
virtual ~TurretObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class TurretObserver
Detailed Description
Definition at line 86 of file TurretObserver.h.
Constructor & Destructor Documentation
TurretObserverImplementation::TurretObserverImplementation ()
Definition at line 182 of file TurretObserver.cpp.
References _initializeImplementation().
TurretObserverImplementation::TurretObserverImplementation (DummyConstructorParameter * param)
Definition at line 68 of file TurretObserver.cpp.
References _initializeImplementation().
TurretObserverImplementation::~TurretObserverImplementation () protected virtual
Definition at line 73 of file TurretObserver.cpp.
Member Function Documentation
DistributedObjectStub * TurretObserverImplementation::_getStub ()
Definition at line 93 of file TurretObserver.cpp.
References _this.
void TurretObserverImplementation::_initializeImplementation () protected
Definition at line 80 of file TurretObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by TurretObserverImplementation().
void TurretObserverImplementation::_serializationHelperMethod () protected
Definition at line 129 of file TurretObserver.cpp.
Referenced by _initializeImplementation().
void TurretObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 88 of file TurretObserver.cpp.
References _this.
Referenced by server::zone::objects::installation::TurretObserver::TurretObserver().
void TurretObserverImplementation::finalize () protected
Definition at line 77 of file TurretObserver.cpp.
void TurretObserverImplementation::lock (bool doLock = true) protected
Definition at line 101 of file TurretObserver.cpp.
References _this.
void TurretObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 105 of file TurretObserver.cpp.
References _this.
int TurretObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2) virtual
Definition at line 14 of file TurretObserverImplementation.cpp.
References ObserverEventType::OBJECTDESTRUCTION.
Referenced by server::zone::objects::installation::TurretObserver::notifyObserverEvent().
TurretObserverImplementation::operator const TurretObserver * ()
Definition at line 97 of file TurretObserver.cpp.
void TurretObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 136 of file TurretObserver.cpp.
References readObjectMember().
bool TurretObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 155 of file TurretObserver.cpp.
Referenced by readObject().
void TurretObserverImplementation::rlock (bool doLock = true) protected
Definition at line 109 of file TurretObserver.cpp.
References _this.
void TurretObserverImplementation::runlock (bool doLock = true) protected
Definition at line 125 of file TurretObserver.cpp.
References _this.
void TurretObserverImplementation::unlock (bool doLock = true) protected
Definition at line 121 of file TurretObserver.cpp.
References _this.
void TurretObserverImplementation::wlock (bool doLock = true) protected
Definition at line 113 of file TurretObserver.cpp.
References _this.
void TurretObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 117 of file TurretObserver.cpp.
References _this.
void TurretObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 165 of file TurretObserver.cpp.
References writeObjectMembers().
int TurretObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 172 of file TurretObserver.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class TurretObserver friend
Definition at line 129 of file TurretObserver.h.
Member Data Documentation
WeakReference<TurretObserver*> server::zone::objects::installation::TurretObserverImplementation::_this
Definition at line 95 of file TurretObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/TurretObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/TurretObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/TurretObserverImplementation.cpp