Core3: AuctionTerminalDataComponent Class Reference
AuctionTerminalDataComponent Class Reference
#include <AuctionTerminalDataComponent.h>
Public Member Functions
AuctionTerminalDataComponent ()
virtual ~AuctionTerminalDataComponent ()
void initializeTransientMembers ()
void updateUID ()
String getUID ()
bool isAuctionTerminalData ()
Public Member Functions inherited from DataObjectComponent
DataObjectComponent ()
~DataObjectComponent ()
virtual void notifyObjectDestroyingFromDatabase ()
void setParent (SceneObject *object)
SceneObject * getParent ()
virtual bool isDiceData ()
virtual bool isVendorData ()
virtual bool isCreatureHabitatData ()
virtual bool isBuildingData ()
virtual bool isDestructibleBuildingData ()
virtual bool isTurretData ()
virtual bool isDetectorData ()
virtual bool isGCWBaseData ()
virtual bool isSecurityTerminalData ()
virtual bool isMinefieldData ()
virtual bool isTurretControlTerminalData ()
virtual bool isDecoration ()
Protected Attributes
ManagedReference
< AuctionManager * > auctionManager
String uid
Protected Attributes inherited from DataObjectComponent
ManagedWeakReference
< SceneObject * > parent
Private Member Functions
void addSerializableVariables ()
Detailed Description
Definition at line 16 of file AuctionTerminalDataComponent.h.
Constructor & Destructor Documentation
AuctionTerminalDataComponent::AuctionTerminalDataComponent () inline
Definition at line 23 of file AuctionTerminalDataComponent.h.
References addSerializableVariables(), and uid.
virtual AuctionTerminalDataComponent::~AuctionTerminalDataComponent () inline virtual
Definition at line 28 of file AuctionTerminalDataComponent.h.
Member Function Documentation
void AuctionTerminalDataComponent::addSerializableVariables () inline private
Definition at line 72 of file AuctionTerminalDataComponent.h.
References uid.
Referenced by AuctionTerminalDataComponent().
String AuctionTerminalDataComponent::getUID () inline
Definition at line 63 of file AuctionTerminalDataComponent.h.
References uid.
void AuctionTerminalDataComponent::initializeTransientMembers () inline virtual
Reimplemented from DataObjectComponent.
Reimplemented in VendorDataComponent.
Definition at line 32 of file AuctionTerminalDataComponent.h.
References auctionManager, DataObjectComponent::parent, uid, and updateUID().
Referenced by VendorDataComponent::initializeTransientMembers().
bool AuctionTerminalDataComponent::isAuctionTerminalData () inline virtual
Reimplemented from DataObjectComponent.
Definition at line 67 of file AuctionTerminalDataComponent.h.
void AuctionTerminalDataComponent::updateUID () inline
Definition at line 41 of file AuctionTerminalDataComponent.h.
References auctionManager, DataObjectComponent::parent, and uid.
Referenced by initializeTransientMembers(), server::zone::objects::region::CityRegionImplementation::notifyEnter(), server::zone::objects::region::CityRegionImplementation::notifyExit(), VendorDataComponent::setInitialized(), and VendorDataComponent::setRegistered().
Member Data Documentation
ManagedReference<AuctionManager*> AuctionTerminalDataComponent::auctionManager protected
Definition at line 19 of file AuctionTerminalDataComponent.h.
Referenced by initializeTransientMembers(), VendorDataComponent::isEmpty(), VendorDataComponent::setVendorSearchEnabled(), updateUID(), and VendorDataComponent::VendorDataComponent().
String AuctionTerminalDataComponent::uid protected
Definition at line 20 of file AuctionTerminalDataComponent.h.
Referenced by addSerializableVariables(), AuctionTerminalDataComponent(), getUID(), initializeTransientMembers(), and updateUID().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/vendor/AuctionTerminalDataComponent.h