Core3: PerlinNoise Class Reference
PerlinNoise Class Reference
#include <PerlinNoise.h>
Public Member Functions
PerlinNoise (trn::ptat::Random *r)
float noise2 (double vec[2])
void init ()
Static Public Member Functions
static void normalize2 (float v[2])
static void normalize3 (float v[3])
Private Attributes
int p [B+B+2]
float g2 [B+B+2][2]
float g1 [B+B+2]
int start
trn::ptat::Random * rand
Detailed Description
Definition at line 24 of file PerlinNoise.h.
Constructor & Destructor Documentation
PerlinNoise::PerlinNoise (trn::ptat::Random * r) inline
Definition at line 46 of file PerlinNoise.h.
References rand, and start.
Member Function Documentation
void PerlinNoise::init () inline
Definition at line 120 of file PerlinNoise.h.
References B, g1, g2, trn::ptat::Random::next(), normalize2(), p, and rand.
Referenced by noise2().
float PerlinNoise::noise2 (double vec[2]) inline
Definition at line 51 of file PerlinNoise.h.
References at2, g2, init(), lerp, p, s_curve, setup, and start.
static void PerlinNoise::normalize2 (float v[2]) inline static
Definition at line 103 of file PerlinNoise.h.
Referenced by init().
static void PerlinNoise::normalize3 (float v[3]) inline static
Definition at line 111 of file PerlinNoise.h.
Member Data Documentation
float PerlinNoise::g1[B+B+2] private
Definition at line 28 of file PerlinNoise.h.
Referenced by init().
float PerlinNoise::g2[B+B+2][2] private
Definition at line 27 of file PerlinNoise.h.
Referenced by init(), and noise2().
int PerlinNoise::p[B+B+2] private
Definition at line 25 of file PerlinNoise.h.
Referenced by init(), and noise2().
trn::ptat::Random* PerlinNoise::rand private
Definition at line 32 of file PerlinNoise.h.
Referenced by init(), and PerlinNoise().
int PerlinNoise::start private
Definition at line 30 of file PerlinNoise.h.
Referenced by noise2(), and PerlinNoise().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/PerlinNoise.h