Core3: server::zone::managers::planet::PlanetManagerImplementation Class Reference
server::zone::managers::planet::PlanetManagerImplementation Class Reference
#include <PlanetManager.h>
Public Member Functions
PlanetManagerImplementation (Zone *planet, ZoneProcessServer *srv)
PlanetManagerImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void finalize ()
void initialize ()
void loadClientRegions ()
void loadClientPoiData ()
void loadBadgeAreas ()
void loadPerformanceLocations ()
PlanetTravelPoint * getNearestPlanetTravelPoint (SceneObject *object, float range=16000.0)
PlanetTravelPoint * getNearestPlanetTravelPoint (const Vector3 &position, float range=16000.0)
bool isBuildingPermittedAt (float x, float y, SceneObject *objectTryingToBuild=NULL)
bool isCampingPermittedAt (float x, float y, float margin)
Reference< SceneObject * > findObjectTooCloseToDecoration (float x, float y, float margin)
bool isInRangeWithPoi (float x, float y, float range)
bool isInObjectsNoBuildZone (float x, float y, float extraMargin)
int getTravelFare (const String &departurePlanet, const String &arrivalPlanet)
void sendPlanetTravelPointListResponse (CreatureObject *player)
Reference< SceneObject * > createTicket (const String &departurePoint, const String &arrivalPlanet, const String &arrivalPoint)
bool validateRegionName (const String &name)
bool validateClientCityInRange (CreatureObject *creatureObject, float x, float y)
WeatherManager * getWeatherManager ()
TerrainManager * getTerrainManager ()
int getRegionCount ()
int getNumberOfCities ()
void increaseNumberOfCities ()
CityRegion * getRegion (int index)
CityRegion * getRegion (const String &region)
CityRegion * getRegionAt (float x, float y)
void addRegion (CityRegion *region)
void dropRegion (const String &region)
bool hasRegion (const String &name)
void addPerformanceLocation (SceneObject *obj)
MissionTargetMap * getPerformanceLocations ()
bool isExistingPlanetTravelPoint (const String &pointName)
bool isInterplanetaryTravelAllowed (const String &pointName)
bool isIncomingTravelAllowed (const String &pointName)
PlanetTravelPoint * getPlanetTravelPoint (const String &pointName)
bool isTravelToLocationPermitted (const String &destinationPoint, const String &arrivalPlanet, const String &arrivalPoint)
void scheduleShuttle (CreatureObject *shuttle, int shuttleType)
void removeShuttle (CreatureObject *shuttle)
bool checkShuttleStatus (CreatureObject *creature, CreatureObject *shuttle)
bool isInWater (float x, float y)
float findClosestWorldFloor (float x, float y, float z, float swimHeight, IntersectionResults *intersections=NULL, CloseObjectsVector *closeObjects=NULL)
void addPlayerCityTravelPoint (PlanetTravelPoint *ptp)
void removePlayerCityTravelPoint (const String &cityName)
operator const PlanetManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< PlanetManager * > _this
Static Public Attributes
static const int SHUTTLEPORT = 0
static const int STARPORT = 1
Protected Member Functions
void loadStaticTangibleObjects ()
virtual ~PlanetManagerImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference< Zone * > zone
RegionMap regionMap
ShuttleMap shuttleMap
TravelFare travelFares
Reference
< PlanetTravelPointList * > planetTravelPointList
int shuttleportAwayTime
int shuttleportLandedTime
int shuttleportLandingTime
int starportAwayTime
int starportLandedTime
int starportLandingTime
ManagedReference
< WeatherManager * > weatherManager
int numberOfCities
ManagedReference
< ZoneProcessServer * > server
Reference< TerrainManager * > terrainManager
Reference< MissionTargetMap * > performanceLocations
Static Protected Attributes
static ClientPoiDataTable clientPoiDataTable
static Mutex poiMutex
Private Member Functions
Reference< SceneObject * > loadSnapshotObject (WorldSnapshotNode *node, WorldSnapshotIff *wsiff, int &totalObjects)
void loadSnapshotObjects ()
void loadTravelFares ()
void loadPlanetObjects (LuaObject *lua)
void loadLuaConfig ()
Friends
class PlanetManager
Detailed Description
Definition at line 371 of file PlanetManager.h.
Constructor & Destructor Documentation
PlanetManagerImplementation::PlanetManagerImplementation (Zone * planet, ZoneProcessServer * srv)
Definition at line 901 of file PlanetManager.cpp.
References _initializeImplementation(), numberOfCities, planetTravelPointList, server, shuttleportAwayTime, shuttleportLandedTime, shuttleportLandingTime, starportAwayTime, starportLandedTime, starportLandingTime, terrainManager, travelFares, weatherManager, and zone.
PlanetManagerImplementation::PlanetManagerImplementation (DummyConstructorParameter * param)
Definition at line 645 of file PlanetManager.cpp.
References _initializeImplementation().
PlanetManagerImplementation::~PlanetManagerImplementation () protected virtual
Definition at line 650 of file PlanetManager.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * PlanetManagerImplementation::_getStub ()
Definition at line 668 of file PlanetManager.cpp.
References _this.
void PlanetManagerImplementation::_initializeImplementation () protected
Definition at line 655 of file PlanetManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by PlanetManagerImplementation().
void PlanetManagerImplementation::_serializationHelperMethod () protected
Definition at line 704 of file PlanetManager.cpp.
Referenced by _initializeImplementation().
void PlanetManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 663 of file PlanetManager.cpp.
References _this.
Referenced by server::zone::managers::planet::PlanetManager::PlanetManager().
void PlanetManagerImplementation::addPerformanceLocation (SceneObject * obj)
Definition at line 1006 of file PlanetManager.cpp.
References performanceLocations.
Referenced by server::zone::managers::planet::PlanetManager::addPerformanceLocation(), and loadPerformanceLocations().
void PlanetManagerImplementation::addPlayerCityTravelPoint (PlanetTravelPoint * ptp)
Definition at line 867 of file PlanetManagerImplementation.cpp.
References planetTravelPointList.
Referenced by server::zone::managers::planet::PlanetManager::addPlayerCityTravelPoint().
void PlanetManagerImplementation::addRegion (CityRegion * region)
Definition at line 989 of file PlanetManager.cpp.
References _this, and regionMap.
Referenced by server::zone::managers::planet::PlanetManager::addRegion().
bool PlanetManagerImplementation::checkShuttleStatus (CreatureObject * creature, CreatureObject * shuttle)
Definition at line 783 of file PlanetManagerImplementation.cpp.
References _this, server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and shuttleMap.
Referenced by server::zone::managers::planet::PlanetManager::checkShuttleStatus().
Reference< SceneObject * > PlanetManagerImplementation::createTicket (const String & departurePoint, const String & arrivalPlanet, const String & arrivalPoint)
Creates a travel ticket from the departure point on this planet to the arrival point on the arrival planet.
Parameters
departurePoint The point on this planet from which the ticket is set to depart.
arrivalPlanet The planet to which the ticket is set to arrive.
departurePoint The point on the arrival planet to which the ticket is set to arrive.
Returns
Returns a travel ticket for the route specified, or NULL if it could not be created.
Definition at line 763 of file PlanetManagerImplementation.cpp.
References server::zone::objects::tangible::TangibleObject::isTicketObject(), server, server::zone::objects::tangible::ticket::TicketObject::setArrivalPlanet(), server::zone::objects::tangible::ticket::TicketObject::setArrivalPoint(), server::zone::objects::tangible::ticket::TicketObject::setDeparturePlanet(), server::zone::objects::tangible::ticket::TicketObject::setDeparturePoint(), and zone.
Referenced by server::zone::managers::planet::PlanetManager::createTicket().
void PlanetManagerImplementation::dropRegion (const String & region)
Definition at line 995 of file PlanetManager.cpp.
References _this, and regionMap.
Referenced by server::zone::managers::planet::PlanetManager::dropRegion().
void PlanetManagerImplementation::finalize ()
Definition at line 580 of file PlanetManagerImplementation.cpp.
References terrainManager.
Referenced by ~PlanetManagerImplementation().
float PlanetManagerImplementation::findClosestWorldFloor (float x, float y, float z, float swimHeight, IntersectionResults * intersections = NULL, CloseObjectsVector * closeObjects = NULL)
Definition at line 834 of file PlanetManagerImplementation.cpp.
References getTerrainManager(), TerrainManager::getWaterHeight(), CollisionManager::getWorldFloorCollisions(), and zone.
Referenced by server::zone::managers::planet::PlanetManager::findClosestWorldFloor().
Reference< SceneObject * > PlanetManagerImplementation::findObjectTooCloseToDecoration (float x, float y, float margin)
Definition at line 731 of file PlanetManagerImplementation.cpp.
References zone.
Referenced by server::zone::managers::planet::PlanetManager::findObjectTooCloseToDecoration().
PlanetTravelPoint * PlanetManagerImplementation::getNearestPlanetTravelPoint (SceneObject * object, float range = 16000.0)
Returns the closest PlanetTravelPoint within the given range.
Parameters
object The object to use as reference.
range The maximum range to search within.
Returns
Returns a PlanetTravelPoint or NULL if not found in range
Definition at line 388 of file PlanetManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getWorldPosition(), and PlanetTravelPoint::toString().
Referenced by server::zone::managers::planet::PlanetManager::getNearestPlanetTravelPoint().
PlanetTravelPoint * PlanetManagerImplementation::getNearestPlanetTravelPoint (const Vector3 & position, float range = 16000.0)
Returns the closest PlanetTravelPoint within the given range.
Parameters
position The position to use as reference.
range The maximum range to search within.
Returns
Returns a PlanetTravelPoint or NULL if not found in range
Definition at line 413 of file PlanetManagerImplementation.cpp.
References planetTravelPointList.
int PlanetManagerImplementation::getNumberOfCities ()
Definition at line 964 of file PlanetManager.cpp.
References numberOfCities.
Referenced by server::zone::managers::planet::PlanetManager::getNumberOfCities().
MissionTargetMap * PlanetManagerImplementation::getPerformanceLocations ()
Definition at line 1011 of file PlanetManager.cpp.
References performanceLocations.
Referenced by server::zone::managers::planet::PlanetManager::getPerformanceLocations().
PlanetTravelPoint * PlanetManagerImplementation::getPlanetTravelPoint (const String & pointName)
Gets the PlanetTravelPoint that corresponds to the point name. If the point doesn't exist then it will return NULL.
Parameters
pointName The planet travel point's name.
Returns
PlanetTravelPoint for the given point name.
Definition at line 1041 of file PlanetManager.cpp.
References planetTravelPointList.
Referenced by server::zone::managers::planet::PlanetManager::getPlanetTravelPoint().
CityRegion * PlanetManagerImplementation::getRegion (int index)
Definition at line 974 of file PlanetManager.cpp.
References server::zone::objects::region::CityRegion::getRegion(), and regionMap.
Referenced by server::zone::managers::planet::PlanetManager::getRegion().
CityRegion * PlanetManagerImplementation::getRegion (const String & region)
Definition at line 979 of file PlanetManager.cpp.
References server::zone::objects::region::CityRegion::getRegion(), and regionMap.
CityRegion * PlanetManagerImplementation::getRegionAt (float x, float y)
Definition at line 984 of file PlanetManager.cpp.
References regionMap.
Referenced by server::zone::managers::planet::PlanetManager::getRegionAt().
int PlanetManagerImplementation::getRegionCount ()
Definition at line 959 of file PlanetManager.cpp.
References regionMap.
Referenced by server::zone::managers::planet::PlanetManager::getRegionCount().
TerrainManager * PlanetManagerImplementation::getTerrainManager ()
Definition at line 954 of file PlanetManager.cpp.
References terrainManager.
Referenced by findClosestWorldFloor(), server::zone::managers::planet::PlanetManager::getTerrainManager(), and isInWater().
int PlanetManagerImplementation::getTravelFare (const String & departurePlanet, const String & arrivalPlanet)
Gets the cost to travel via shuttleport/starport to the destination planet. If the value is 0, then travel to the planet from this planet is disabled.
Parameters
destinationPlanet The planet that to which is being travelled. Can be the same planet.
Returns
The cost to travel to the destination planet.
Definition at line 249 of file PlanetManagerImplementation.cpp.
References travelFares.
Referenced by server::zone::managers::planet::PlanetManager::getTravelFare().
WeatherManager * PlanetManagerImplementation::getWeatherManager ()
Definition at line 949 of file PlanetManager.cpp.
References weatherManager.
Referenced by server::zone::managers::planet::PlanetManager::getWeatherManager().
bool PlanetManagerImplementation::hasRegion (const String & name)
Definition at line 1001 of file PlanetManager.cpp.
References regionMap.
Referenced by server::zone::managers::planet::PlanetManager::hasRegion(), and validateRegionName().
void PlanetManagerImplementation::increaseNumberOfCities ()
Definition at line 969 of file PlanetManager.cpp.
References numberOfCities.
Referenced by server::zone::managers::planet::PlanetManager::increaseNumberOfCities().
void PlanetManagerImplementation::initialize ()
Definition at line 51 of file PlanetManagerImplementation.cpp.
References loadBadgeAreas(), loadClientPoiData(), loadClientRegions(), loadLuaConfig(), loadPerformanceLocations(), loadStaticTangibleObjects(), loadTravelFares(), numberOfCities, performanceLocations, planetTravelPointList, server::zone::objects::area::ActiveArea::setRadius(), and zone.
Referenced by server::zone::managers::planet::PlanetManager::initialize().
void PlanetManagerImplementation::initializeTransientMembers ()
Definition at line 573 of file PlanetManagerImplementation.cpp.
References terrainManager, and zone.
Referenced by server::zone::managers::planet::PlanetManager::initializeTransientMembers(), and readObject().
bool PlanetManagerImplementation::isBuildingPermittedAt (float x, float y, SceneObject * objectTryingToBuild = NULL)
Definition at line 667 of file PlanetManagerImplementation.cpp.
References isInObjectsNoBuildZone(), isInRangeWithPoi(), isInWater(), server::zone::objects::area::ActiveArea::isNoBuildArea(), and zone.
Referenced by server::zone::managers::planet::PlanetManager::isBuildingPermittedAt().
bool PlanetManagerImplementation::isCampingPermittedAt (float x, float y, float margin)
Definition at line 696 of file PlanetManagerImplementation.cpp.
References server::zone::objects::area::ActiveArea::isCampingPermitted(), isInObjectsNoBuildZone(), isInRangeWithPoi(), isInWater(), server::zone::objects::area::ActiveArea::isNoBuildArea(), and zone.
Referenced by server::zone::managers::planet::PlanetManager::isCampingPermittedAt().
bool PlanetManagerImplementation::isExistingPlanetTravelPoint (const String & pointName)
Checks to see if the point is an existing planet travel point.
Parameters
pointName The name of the point to check for.
Returns
Returns true if the point exists.
Definition at line 1016 of file PlanetManager.cpp.
References planetTravelPointList.
Referenced by server::zone::managers::planet::PlanetManager::isExistingPlanetTravelPoint(), and isTravelToLocationPermitted().
bool PlanetManagerImplementation::isIncomingTravelAllowed (const String & pointName)
Checks to see if incoming travel is allowed to the specified point.
Parameters
pointName The point name representing a travel point belonging to this planet.
Returns
Returns true if incoming travel is allowed.
Definition at line 1031 of file PlanetManager.cpp.
References PlanetTravelPoint::isIncomingAllowed(), and planetTravelPointList.
Referenced by server::zone::managers::planet::PlanetManager::isIncomingTravelAllowed().
bool PlanetManagerImplementation::isInObjectsNoBuildZone (float x, float y, float extraMargin)
Definition at line 635 of file PlanetManagerImplementation.cpp.
References server::zone::templates::SharedObjectTemplate::getNoBuildRadius(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::scene::SceneObject::getWorldPosition(), and zone.
Referenced by isBuildingPermittedAt(), isCampingPermittedAt(), and server::zone::managers::planet::PlanetManager::isInObjectsNoBuildZone().
bool PlanetManagerImplementation::isInRangeWithPoi (float x, float y, float range)
Definition at line 617 of file PlanetManagerImplementation.cpp.
References clientPoiDataTable, ClientPoiDataTable::containsPlanet(), ClientPoiDataTable::getPois(), and zone.
Referenced by isBuildingPermittedAt(), isCampingPermittedAt(), and server::zone::managers::planet::PlanetManager::isInRangeWithPoi().
bool PlanetManagerImplementation::isInterplanetaryTravelAllowed (const String & pointName)
Checks to see if interplanetary travel is allowed to the specified point.
Parameters
pointName The point name representing a travel point belonging to this planet.
Returns
Returns true if interplanetary travel is allowed.
Definition at line 1021 of file PlanetManager.cpp.
References PlanetTravelPoint::isInterplanetary(), and planetTravelPointList.
Referenced by server::zone::managers::planet::PlanetManager::isInterplanetaryTravelAllowed(), and isTravelToLocationPermitted().
bool PlanetManagerImplementation::isInWater (float x, float y)
Definition at line 824 of file PlanetManagerImplementation.cpp.
References getTerrainManager(), and zone.
Referenced by isBuildingPermittedAt(), isCampingPermittedAt(), and server::zone::managers::planet::PlanetManager::isInWater().
bool PlanetManagerImplementation::isTravelToLocationPermitted (const String & destinationPoint, const String & arrivalPlanet, const String & arrivalPoint)
Checks to see the travel between the points is allowed based on their settings.
Parameters
destinationPoint The point from which is being traveled.
arrivalPlanet The planet to which is being traveled.
arrivalPoint The point to which is being traveled.
Returns
Returns true if travel is permitted between the two points.
Definition at line 349 of file PlanetManagerImplementation.cpp.
References server::zone::managers::planet::PlanetManager::isExistingPlanetTravelPoint(), isExistingPlanetTravelPoint(), server::zone::managers::planet::PlanetManager::isIncomingTravelAllowed(), server::zone::managers::planet::PlanetManager::isInterplanetaryTravelAllowed(), isInterplanetaryTravelAllowed(), and zone.
Referenced by server::zone::managers::planet::PlanetManager::isTravelToLocationPermitted().
void PlanetManagerImplementation::loadBadgeAreas ()
Definition at line 585 of file PlanetManagerImplementation.cpp.
Referenced by initialize(), and server::zone::managers::planet::PlanetManager::loadBadgeAreas().
void PlanetManagerImplementation::loadClientPoiData ()
Definition at line 434 of file PlanetManagerImplementation.cpp.
References clientPoiDataTable, poiMutex, DataTableIff::readObject(), ClientPoiDataTable::readObject(), and ClientPoiDataTable::size().
Referenced by initialize(), and server::zone::managers::planet::PlanetManager::loadClientPoiData().
void PlanetManagerImplementation::loadClientRegions ()
Definition at line 458 of file PlanetManagerImplementation.cpp.
References RegionMap::addRegion(), RegionMap::getRegion(), DataTableIff::getRow(), RegionMap::getTotalRegions(), DataTableIff::getTotalRows(), DataTableRow::getValue(), TemplateManager::openIffFile(), DataTableIff::readObject(), regionMap, and zone.
Referenced by initialize(), and server::zone::managers::planet::PlanetManager::loadClientRegions().
void PlanetManagerImplementation::loadLuaConfig () private
Definition at line 78 of file PlanetManagerImplementation.cpp.
References loadPlanetObjects(), loadSnapshotObjects(), planetTravelPointList, server, server::zone::objects::area::ActiveArea::setRadius(), shuttleportAwayTime, shuttleportLandedTime, shuttleportLandingTime, starportAwayTime, starportLandedTime, starportLandingTime, weatherManager, and zone.
Referenced by initialize().
void PlanetManagerImplementation::loadPerformanceLocations ()
Definition at line 588 of file PlanetManagerImplementation.cpp.
References addPerformanceLocation(), and zone.
Referenced by initialize(), and server::zone::managers::planet::PlanetManager::loadPerformanceLocations().
void PlanetManagerImplementation::loadPlanetObjects (LuaObject * lua) private
Definition at line 169 of file PlanetManagerImplementation.cpp.
References zone.
Referenced by loadLuaConfig().
Reference< SceneObject * > PlanetManagerImplementation::loadSnapshotObject (WorldSnapshotNode * node, WorldSnapshotIff * wsiff, int & totalObjects) private
Definition at line 254 of file PlanetManagerImplementation.cpp.
References server::zone::objects::building::BuildingObject::addCell(), server::zone::ZoneServer::createClientObject(), WorldSnapshotNode::getCellID(), WorldSnapshotNode::getDirection(), WorldSnapshotNode::getNameID(), WorldSnapshotNode::getNode(), WorldSnapshotNode::getNodeCount(), server::zone::ZoneServer::getObject(), WorldSnapshotNode::getObjectID(), WorldSnapshotIff::getObjectTemplateName(), WorldSnapshotNode::getParentID(), WorldSnapshotNode::getPosition(), server, and zone.
Referenced by loadSnapshotObjects().
void PlanetManagerImplementation::loadSnapshotObjects () private
Definition at line 311 of file PlanetManagerImplementation.cpp.
References WorldSnapshotIff::getNode(), WorldSnapshotIff::getNodeCount(), loadSnapshotObject(), TemplateManager::openIffFile(), WorldSnapshotIff::readObject(), and zone.
Referenced by loadLuaConfig().
void PlanetManagerImplementation::loadStaticTangibleObjects () protected
Definition at line 430 of file PlanetManagerImplementation.cpp.
Referenced by initialize().
void PlanetManagerImplementation::loadTravelFares () private
Definition at line 208 of file PlanetManagerImplementation.cpp.
References DataTableRow::getCell(), DataTableIff::getColumnNameByIndex(), DataTableIff::getRow(), DataTableIff::getTotalColumns(), DataTableIff::getTotalRows(), DataTableCell::getValue(), TemplateManager::openIffFile(), DataTableIff::readObject(), and travelFares.
Referenced by initialize().
void PlanetManagerImplementation::lock (bool doLock = true) protected
Definition at line 676 of file PlanetManager.cpp.
References _this.
void PlanetManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 680 of file PlanetManager.cpp.
References _this.
PlanetManagerImplementation::operator const PlanetManager * ()
Definition at line 672 of file PlanetManager.cpp.
void PlanetManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 711 of file PlanetManager.cpp.
References initializeTransientMembers(), and readObjectMember().
bool PlanetManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 730 of file PlanetManager.cpp.
References numberOfCities, planetTravelPointList, regionMap, shuttleportAwayTime, shuttleportLandedTime, shuttleportLandingTime, starportAwayTime, starportLandedTime, starportLandingTime, travelFares, weatherManager, and zone.
Referenced by readObject().
void PlanetManagerImplementation::removePlayerCityTravelPoint (const String & cityName)
Definition at line 873 of file PlanetManagerImplementation.cpp.
References planetTravelPointList.
Referenced by server::zone::managers::planet::PlanetManager::removePlayerCityTravelPoint().
void PlanetManagerImplementation::removeShuttle (CreatureObject * shuttle)
Definition at line 1046 of file PlanetManager.cpp.
References _this, server::zone::objects::scene::SceneObject::getObjectID(), and shuttleMap.
Referenced by server::zone::managers::planet::PlanetManager::removeShuttle().
void PlanetManagerImplementation::rlock (bool doLock = true) protected
Definition at line 684 of file PlanetManager.cpp.
References _this.
void PlanetManagerImplementation::runlock (bool doLock = true) protected
Definition at line 700 of file PlanetManager.cpp.
References _this.
void PlanetManagerImplementation::scheduleShuttle (CreatureObject * shuttle, int shuttleType)
Definition at line 879 of file PlanetManagerImplementation.cpp.
References _this, ShuttleDepartureTask::getLandedTime(), ShuttleDepartureTask::getLandingTime(), server::zone::objects::scene::SceneObject::getObjectID(), ShuttleDepartureTask::setDepartedTime(), ShuttleDepartureTask::setLandedTime(), ShuttleDepartureTask::setLandingTime(), server::zone::objects::creature::CreatureObject::setPosture(), shuttleMap, SHUTTLEPORT, shuttleportAwayTime, shuttleportLandedTime, shuttleportLandingTime, STARPORT, starportAwayTime, starportLandedTime, starportLandingTime, and CreaturePosture::UPRIGHT.
Referenced by server::zone::managers::planet::PlanetManager::scheduleShuttle().
void PlanetManagerImplementation::sendPlanetTravelPointListResponse (CreatureObject * player)
Definition at line 381 of file PlanetManagerImplementation.cpp.
References planetTravelPointList, server::zone::objects::creature::CreatureObject::sendMessage(), and zone.
Referenced by server::zone::managers::planet::PlanetManager::sendPlanetTravelPointListResponse().
void PlanetManagerImplementation::unlock (bool doLock = true) protected
Definition at line 696 of file PlanetManager.cpp.
References _this.
bool PlanetManagerImplementation::validateClientCityInRange (CreatureObject * creatureObject, float x, float y)
Definition at line 520 of file PlanetManagerImplementation.cpp.
References _this, RegionMap::getRegion(), server::zone::objects::region::CityRegion::getRegion(), server::zone::objects::region::CityRegion::getRegionName(), server::zone::objects::region::CityRegion::getRegionsCount(), RegionMap::getTotalRegions(), regionMap, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::chat::StringIdChatParameter::setTO().
Referenced by server::zone::managers::planet::PlanetManager::validateClientCityInRange().
bool PlanetManagerImplementation::validateRegionName (const String & name)
Definition at line 552 of file PlanetManagerImplementation.cpp.
References _this, RegionMap::getRegion(), server::zone::objects::region::CityRegion::getRegionName(), RegionMap::getTotalRegions(), hasRegion(), and regionMap.
Referenced by server::zone::managers::planet::PlanetManager::validateRegionName().
void PlanetManagerImplementation::wlock (bool doLock = true) protected
Definition at line 688 of file PlanetManager.cpp.
References _this.
void PlanetManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 692 of file PlanetManager.cpp.
References _this.
void PlanetManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 788 of file PlanetManager.cpp.
References writeObjectMembers().
int PlanetManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 795 of file PlanetManager.cpp.
References numberOfCities, planetTravelPointList, regionMap, shuttleportAwayTime, shuttleportLandedTime, shuttleportLandingTime, starportAwayTime, starportLandedTime, starportLandingTime, travelFares, weatherManager, and zone.
Referenced by writeObject().
Friends And Related Function Documentation
friend class PlanetManager friend
Definition at line 609 of file PlanetManager.h.
Member Data Documentation
WeakReference<PlanetManager*> server::zone::managers::planet::PlanetManagerImplementation::_this
Definition at line 577 of file PlanetManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addRegion(), checkShuttleStatus(), dropRegion(), lock(), removeShuttle(), rlock(), runlock(), scheduleShuttle(), unlock(), validateClientCityInRange(), validateRegionName(), and wlock().
ClientPoiDataTable PlanetManagerImplementation::clientPoiDataTable static protected
Definition at line 411 of file PlanetManager.h.
Referenced by isInRangeWithPoi(), and loadClientPoiData().
int server::zone::managers::planet::PlanetManagerImplementation::numberOfCities protected
Definition at line 403 of file PlanetManager.h.
Referenced by getNumberOfCities(), increaseNumberOfCities(), initialize(), PlanetManagerImplementation(), readObjectMember(), and writeObjectMembers().
Reference<MissionTargetMap* > server::zone::managers::planet::PlanetManagerImplementation::performanceLocations protected
Definition at line 409 of file PlanetManager.h.
Referenced by addPerformanceLocation(), getPerformanceLocations(), and initialize().
Reference<PlanetTravelPointList* > server::zone::managers::planet::PlanetManagerImplementation::planetTravelPointList protected
Definition at line 381 of file PlanetManager.h.
Referenced by addPlayerCityTravelPoint(), getNearestPlanetTravelPoint(), getPlanetTravelPoint(), initialize(), isExistingPlanetTravelPoint(), isIncomingTravelAllowed(), isInterplanetaryTravelAllowed(), loadLuaConfig(), PlanetManagerImplementation(), readObjectMember(), removePlayerCityTravelPoint(), sendPlanetTravelPointListResponse(), and writeObjectMembers().
Mutex PlanetManagerImplementation::poiMutex static protected
Definition at line 413 of file PlanetManager.h.
Referenced by loadClientPoiData().
RegionMap server::zone::managers::planet::PlanetManagerImplementation::regionMap protected
Definition at line 375 of file PlanetManager.h.
Referenced by addRegion(), dropRegion(), getRegion(), getRegionAt(), getRegionCount(), hasRegion(), loadClientRegions(), readObjectMember(), validateClientCityInRange(), validateRegionName(), and writeObjectMembers().
ManagedReference<ZoneProcessServer* > server::zone::managers::planet::PlanetManagerImplementation::server protected
Definition at line 405 of file PlanetManager.h.
Referenced by createTicket(), loadLuaConfig(), loadSnapshotObject(), and PlanetManagerImplementation().
ShuttleMap server::zone::managers::planet::PlanetManagerImplementation::shuttleMap protected
Definition at line 377 of file PlanetManager.h.
Referenced by checkShuttleStatus(), removeShuttle(), and scheduleShuttle().
const int server::zone::managers::planet::PlanetManagerImplementation::SHUTTLEPORT = 0 static
Definition at line 396 of file PlanetManager.h.
Referenced by scheduleShuttle().
int server::zone::managers::planet::PlanetManagerImplementation::shuttleportAwayTime protected
Definition at line 383 of file PlanetManager.h.
Referenced by loadLuaConfig(), PlanetManagerImplementation(), readObjectMember(), scheduleShuttle(), and writeObjectMembers().
int server::zone::managers::planet::PlanetManagerImplementation::shuttleportLandedTime protected
Definition at line 385 of file PlanetManager.h.
Referenced by loadLuaConfig(), PlanetManagerImplementation(), readObjectMember(), scheduleShuttle(), and writeObjectMembers().
int server::zone::managers::planet::PlanetManagerImplementation::shuttleportLandingTime protected
Definition at line 387 of file PlanetManager.h.
Referenced by loadLuaConfig(), PlanetManagerImplementation(), readObjectMember(), scheduleShuttle(), and writeObjectMembers().
const int server::zone::managers::planet::PlanetManagerImplementation::STARPORT = 1 static
Definition at line 398 of file PlanetManager.h.
Referenced by scheduleShuttle().
int server::zone::managers::planet::PlanetManagerImplementation::starportAwayTime protected
Definition at line 389 of file PlanetManager.h.
Referenced by loadLuaConfig(), PlanetManagerImplementation(), readObjectMember(), scheduleShuttle(), and writeObjectMembers().
int server::zone::managers::planet::PlanetManagerImplementation::starportLandedTime protected
Definition at line 391 of file PlanetManager.h.
Referenced by loadLuaConfig(), PlanetManagerImplementation(), readObjectMember(), scheduleShuttle(), and writeObjectMembers().
int server::zone::managers::planet::PlanetManagerImplementation::starportLandingTime protected
Definition at line 393 of file PlanetManager.h.
Referenced by loadLuaConfig(), PlanetManagerImplementation(), readObjectMember(), scheduleShuttle(), and writeObjectMembers().
Reference<TerrainManager* > server::zone::managers::planet::PlanetManagerImplementation::terrainManager protected
Definition at line 407 of file PlanetManager.h.
Referenced by finalize(), getTerrainManager(), initializeTransientMembers(), and PlanetManagerImplementation().
TravelFare server::zone::managers::planet::PlanetManagerImplementation::travelFares protected
Definition at line 379 of file PlanetManager.h.
Referenced by getTravelFare(), loadTravelFares(), PlanetManagerImplementation(), readObjectMember(), and writeObjectMembers().
ManagedReference<WeatherManager* > server::zone::managers::planet::PlanetManagerImplementation::weatherManager protected
Definition at line 401 of file PlanetManager.h.
Referenced by getWeatherManager(), loadLuaConfig(), PlanetManagerImplementation(), readObjectMember(), and writeObjectMembers().
ManagedReference<Zone* > server::zone::managers::planet::PlanetManagerImplementation::zone protected
Definition at line 373 of file PlanetManager.h.
Referenced by createTicket(), findClosestWorldFloor(), findObjectTooCloseToDecoration(), initialize(), initializeTransientMembers(), isBuildingPermittedAt(), isCampingPermittedAt(), isInObjectsNoBuildZone(), isInRangeWithPoi(), isInWater(), isTravelToLocationPermitted(), loadClientRegions(), loadLuaConfig(), loadPerformanceLocations(), loadPlanetObjects(), loadSnapshotObject(), loadSnapshotObjects(), PlanetManagerImplementation(), readObjectMember(), sendPlanetTravelPointListResponse(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/PlanetManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/PlanetManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/PlanetManagerImplementation.cpp