Core3: CharacterListEntry Class Reference
CharacterListEntry Class Reference
#include <CharacterListEntry.h>
Public Member Functions
CharacterListEntry ()
CharacterListEntry (const CharacterListEntry &e)
CharacterListEntry & operator= (const CharacterListEntry &e)
~CharacterListEntry ()
uint32 getAccountID () const
Time getCreationDate () const
String getFirstName () const
uint32 getGalaxyID () const
String getGalaxyName () const
uint32 getGender () const
uint64 getObjectID () const
uint32 getRace () const
String getSurName () const
void setAccountID (uint32 accountID)
void setCreationDate (Time creationDate)
void setFirstName (String firstName)
void setGalaxyName (String galaxyName)
void setGalaxyID (uint32 galaxyID)
void setGender (uint32 gender)
void setObjectID (uint64 objectID)
void setRace (uint32 race)
void setSurName (String surName)
String getFullName ()
bool isBanned ()
void setBanReason (String banReason)
String getBanReason () const
void setBanExpiration (Time banExpiration)
uint32 getBanExpiration ()
void setBanAdmin (uint32 banAdmin)
uint32 getBanAdmin () const
Private Attributes
uint64 objectID
uint32 accountID
uint32 galaxyID
String firstName
String surName
uint32 race
uint32 gender
Time creationDate
String galaxyName
String banReason
uint32 banAdmin
Time banExpiration
Detailed Description
Definition at line 48 of file CharacterListEntry.h.
Constructor & Destructor Documentation
CharacterListEntry::CharacterListEntry () inline
Definition at line 65 of file CharacterListEntry.h.
References accountID, banAdmin, galaxyID, gender, objectID, and race.
CharacterListEntry::CharacterListEntry (const CharacterListEntry & e) inline
Definition at line 69 of file CharacterListEntry.h.
References accountID, banAdmin, banExpiration, banReason, creationDate, firstName, galaxyID, galaxyName, gender, objectID, race, and surName.
CharacterListEntry::~CharacterListEntry () inline
Definition at line 106 of file CharacterListEntry.h.
Member Function Documentation
uint32 CharacterListEntry::getAccountID () const inline
Definition at line 110 of file CharacterListEntry.h.
References accountID.
uint32 CharacterListEntry::getBanAdmin () const inline
Definition at line 215 of file CharacterListEntry.h.
References banAdmin.
Referenced by server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::completeBan(), and RemoveBannedPlayerCommand::doQueueCommand().
uint32 CharacterListEntry::getBanExpiration () inline
Definition at line 207 of file CharacterListEntry.h.
References banExpiration.
Referenced by server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::showUnbanSummary().
String CharacterListEntry::getBanReason () const inline
Definition at line 199 of file CharacterListEntry.h.
References banReason.
Referenced by server::zone::objects::player::sessions::admin::PlayerManagementSessionImplementation::completeBan(), RemoveBannedPlayerCommand::doQueueCommand(), and GetAccountInfoCommand::doQueueCommand().
Time CharacterListEntry::getCreationDate () const inline
Definition at line 114 of file CharacterListEntry.h.
References creationDate.
String CharacterListEntry::getFirstName () const inline
Definition at line 118 of file CharacterListEntry.h.
References firstName.
Referenced by server::zone::managers::player::PlayerManagerImplementation::banAccount(), server::zone::managers::player::PlayerManagerImplementation::banFromGalaxy(), GetAccountInfoCommand::doQueueCommand(), server::login::account::AccountImplementation::getCharacterBan(), and PermissionsServlet::handlePost().
String CharacterListEntry::getFullName () inline
Definition at line 182 of file CharacterListEntry.h.
References firstName, and surName.
Referenced by GetAccountInfoCommand::doQueueCommand(), and EnumerateCharacterID::EnumerateCharacterID().
uint32 CharacterListEntry::getGalaxyID () const inline
Definition at line 122 of file CharacterListEntry.h.
References galaxyID.
Referenced by server::zone::managers::player::PlayerManagerImplementation::banAccount(), server::zone::managers::player::PlayerManagerImplementation::banFromGalaxy(), RemoveBannedPlayerCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), EnumerateCharacterID::EnumerateCharacterID(), server::login::account::AccountImplementation::getCharacterBan(), and ClientIDMessageCallback::run().
String CharacterListEntry::getGalaxyName () const inline
Definition at line 126 of file CharacterListEntry.h.
References galaxyName.
Referenced by GetAccountInfoCommand::doQueueCommand().
uint32 CharacterListEntry::getGender () const inline
Definition at line 130 of file CharacterListEntry.h.
References gender.
uint64 CharacterListEntry::getObjectID () const inline
Definition at line 134 of file CharacterListEntry.h.
References objectID.
Referenced by EnumerateCharacterID::EnumerateCharacterID(), and ClientIDMessageCallback::run().
uint32 CharacterListEntry::getRace () const inline
Definition at line 138 of file CharacterListEntry.h.
References race.
Referenced by EnumerateCharacterID::EnumerateCharacterID().
String CharacterListEntry::getSurName () const inline
Definition at line 142 of file CharacterListEntry.h.
References surName.
bool CharacterListEntry::isBanned () inline
Definition at line 191 of file CharacterListEntry.h.
References banExpiration.
Referenced by GetAccountInfoCommand::doQueueCommand(), EnumerateCharacterID::EnumerateCharacterID(), server::login::account::AccountImplementation::getCharacterBan(), and ClientIDMessageCallback::run().
CharacterListEntry& CharacterListEntry::operator= (const CharacterListEntry & e) inline
Definition at line 85 of file CharacterListEntry.h.
References accountID, banAdmin, banExpiration, banReason, creationDate, firstName, galaxyID, galaxyName, gender, objectID, race, and surName.
void CharacterListEntry::setAccountID (uint32 accountID) inline
Definition at line 146 of file CharacterListEntry.h.
References accountID.
Referenced by CharacterList::update().
void CharacterListEntry::setBanAdmin (uint32 banAdmin) inline
Definition at line 211 of file CharacterListEntry.h.
References banAdmin.
Referenced by CharacterList::update().
void CharacterListEntry::setBanExpiration (Time banExpiration) inline
Definition at line 203 of file CharacterListEntry.h.
References banExpiration.
Referenced by CharacterList::update().
void CharacterListEntry::setBanReason (String banReason) inline
Definition at line 195 of file CharacterListEntry.h.
References banReason.
Referenced by CharacterList::update().
void CharacterListEntry::setCreationDate (Time creationDate) inline
Definition at line 150 of file CharacterListEntry.h.
References creationDate.
Referenced by CharacterList::update().
void CharacterListEntry::setFirstName (String firstName) inline
Definition at line 154 of file CharacterListEntry.h.
References firstName.
Referenced by CharacterList::update().
void CharacterListEntry::setGalaxyID (uint32 galaxyID) inline
Definition at line 162 of file CharacterListEntry.h.
References galaxyID.
Referenced by CharacterList::update().
void CharacterListEntry::setGalaxyName (String galaxyName) inline
Definition at line 158 of file CharacterListEntry.h.
References galaxyName.
Referenced by CharacterList::update().
void CharacterListEntry::setGender (uint32 gender) inline
Definition at line 166 of file CharacterListEntry.h.
References gender.
void CharacterListEntry::setObjectID (uint64 objectID) inline
Definition at line 170 of file CharacterListEntry.h.
References objectID.
Referenced by CharacterList::update().
void CharacterListEntry::setRace (uint32 race) inline
Definition at line 174 of file CharacterListEntry.h.
References race.
Referenced by CharacterList::update().
void CharacterListEntry::setSurName (String surName) inline
Definition at line 178 of file CharacterListEntry.h.
References surName.
Referenced by CharacterList::update().
Member Data Documentation
uint32 CharacterListEntry::accountID private
Definition at line 51 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getAccountID(), operator=(), and setAccountID().
uint32 CharacterListEntry::banAdmin private
Definition at line 61 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getBanAdmin(), operator=(), and setBanAdmin().
Time CharacterListEntry::banExpiration private
Definition at line 62 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getBanExpiration(), isBanned(), operator=(), and setBanExpiration().
String CharacterListEntry::banReason private
Definition at line 60 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getBanReason(), operator=(), and setBanReason().
Time CharacterListEntry::creationDate private
Definition at line 57 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getCreationDate(), operator=(), and setCreationDate().
String CharacterListEntry::firstName private
Definition at line 53 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getFirstName(), getFullName(), operator=(), and setFirstName().
uint32 CharacterListEntry::galaxyID private
Definition at line 52 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getGalaxyID(), operator=(), and setGalaxyID().
String CharacterListEntry::galaxyName private
Definition at line 59 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getGalaxyName(), operator=(), and setGalaxyName().
uint32 CharacterListEntry::gender private
Definition at line 56 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getGender(), operator=(), and setGender().
uint64 CharacterListEntry::objectID private
Definition at line 50 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getObjectID(), operator=(), and setObjectID().
uint32 CharacterListEntry::race private
Definition at line 55 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getRace(), operator=(), and setRace().
String CharacterListEntry::surName private
Definition at line 54 of file CharacterListEntry.h.
Referenced by CharacterListEntry(), getFullName(), getSurName(), operator=(), and setSurName().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/objects/CharacterListEntry.h