Core3: server::zone::objects::installation::factory::FactoryHopperObserver Class Reference
server::zone::objects::installation::factory::FactoryHopperObserver Class Reference
#include <FactoryHopperObserver.h>
Public Member Functions
FactoryHopperObserver (FactoryObject *fact)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
FactoryHopperObserver (DummyConstructorParameter *param)
virtual ~FactoryHopperObserver ()
Friends
class FactoryHopperObserverHelper
Detailed Description
Definition at line 54 of file FactoryHopperObserver.h.
Constructor & Destructor Documentation
FactoryHopperObserver::FactoryHopperObserver (FactoryObject * fact)
Definition at line 15 of file FactoryHopperObserver.cpp.
References server::zone::objects::installation::factory::FactoryHopperObserverImplementation::_setStub().
FactoryHopperObserver::FactoryHopperObserver (DummyConstructorParameter * param) protected
Definition at line 22 of file FactoryHopperObserver.cpp.
FactoryHopperObserver::~FactoryHopperObserver () protected virtual
Definition at line 26 of file FactoryHopperObserver.cpp.
Member Function Documentation
DistributedObjectServant * FactoryHopperObserver::_getImplementation ()
Definition at line 48 of file FactoryHopperObserver.cpp.
Referenced by notifyObserverEvent().
DistributedObjectServant * FactoryHopperObserver::_getImplementationForRead ()
Definition at line 54 of file FactoryHopperObserver.cpp.
void FactoryHopperObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 58 of file FactoryHopperObserver.cpp.
int FactoryHopperObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 31 of file FactoryHopperObserver.cpp.
References _getImplementation(), server::zone::objects::installation::factory::FactoryHopperObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class FactoryHopperObserverHelper friend
Definition at line 70 of file FactoryHopperObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/factory/FactoryHopperObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/factory/FactoryHopperObserver.cpp