Core3: server::zone::objects::creature::buffs::SpiceDownerBuffImplementation Class Reference
server::zone::objects::creature::buffs::SpiceDownerBuffImplementation Class Reference
#include <SpiceDownerBuff.h>
Public Member Functions
SpiceDownerBuffImplementation (CreatureObject *creo, const String &name, unsigned int buffCRC, int duration)
SpiceDownerBuffImplementation (DummyConstructorParameter *param)
void activate (bool applyModifiers)
void deactivate (bool applyModifiers)
operator const SpiceDownerBuff * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
BuffImplementation (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype)
BuffImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
virtual void sendTo (CreatureObject *player)
virtual void sendDestroyTo (CreatureObject *player)
virtual void activate ()
virtual void deactivate ()
VectorMap< String, int > * getSkillModifiers ()
virtual void applyAttributeModifiers ()
virtual void applySkillModifiers ()
virtual void applyStates ()
virtual void removeAttributeModifiers ()
virtual void removeSkillModifiers ()
virtual void removeStates ()
virtual void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
virtual void parseAttributeModifierString (const String &modifierstring)
virtual void parseSkillModifierString (const String &modifierstring)
virtual String getAttributeModifierString ()
virtual String getSkillModifierString ()
virtual float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
VectorMap< byte, int > * getAttributeModifiers ()
virtual int getAttributeModifierValue (byte attribute)
virtual int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartMessage (StringIdChatParameter &start)
void setEndMessage (StringIdChatParameter &end)
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
operator const Buff * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< SpiceDownerBuff * > _this
Public Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
WeakReference< Buff * > _this
Protected Member Functions
virtual ~SpiceDownerBuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
virtual ~BuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class SpiceDownerBuff
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
ManagedWeakReference
< CreatureObject * > creature
Reference< BuffDurationEvent * > buffEvent
VectorMap< byte, int > attributeModifiers
VectorMap< String, int > skillModifiers
Vector< unsigned long long > states
String buffName
float buffDuration
unsigned int buffCRC
int buffType
bool fillAttributesOnBuff
StringIdChatParameter startMessage
StringIdChatParameter endMessage
String startFlyFile
String startFlyAux
byte startFlyRed
byte startFlyGreen
byte startFlyBlue
String endFlyFile
String endFlyAux
byte endFlyRed
byte endFlyGreen
byte endFlyBlue
Time nextExecutionTime
Detailed Description
Definition at line 117 of file SpiceDownerBuff.h.
Constructor & Destructor Documentation
SpiceDownerBuffImplementation::SpiceDownerBuffImplementation (CreatureObject * creo, const String & name, unsigned int buffCRC, int duration)
Definition at line 195 of file SpiceDownerBuff.cpp.
References _initializeImplementation(), and server::zone::objects::creature::buffs::BuffImplementation::buffName.
SpiceDownerBuffImplementation::SpiceDownerBuffImplementation (DummyConstructorParameter * param)
Definition at line 81 of file SpiceDownerBuff.cpp.
References _initializeImplementation().
SpiceDownerBuffImplementation::~SpiceDownerBuffImplementation () protected virtual
Definition at line 86 of file SpiceDownerBuff.cpp.
Member Function Documentation
DistributedObjectStub * SpiceDownerBuffImplementation::_getStub ()
Definition at line 106 of file SpiceDownerBuff.cpp.
References _this.
void SpiceDownerBuffImplementation::_initializeImplementation () protected
Definition at line 93 of file SpiceDownerBuff.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SpiceDownerBuffImplementation().
void SpiceDownerBuffImplementation::_serializationHelperMethod () protected
Definition at line 142 of file SpiceDownerBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void SpiceDownerBuffImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 101 of file SpiceDownerBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::buffs::SpiceDownerBuff::SpiceDownerBuff().
void SpiceDownerBuffImplementation::activate (bool applyModifiers) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 201 of file SpiceDownerBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::activate(), server::zone::objects::creature::buffs::BuffImplementation::buffDuration, server::zone::objects::creature::buffs::BuffImplementation::buffName, server::zone::objects::creature::buffs::BuffImplementation::creature, BuffCRC::FOOD_REDUCE_SPICE_DOWNTIME, and ObserverEventType::SPICEDOWNERACTIVATED.
Referenced by server::zone::objects::creature::buffs::SpiceDownerBuff::activate().
void SpiceDownerBuffImplementation::deactivate (bool applyModifiers) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 220 of file SpiceDownerBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::buffName, server::zone::objects::creature::buffs::BuffImplementation::creature, and server::zone::objects::creature::buffs::BuffImplementation::deactivate().
Referenced by server::zone::objects::creature::buffs::SpiceDownerBuff::deactivate().
void SpiceDownerBuffImplementation::finalize () protected
Definition at line 90 of file SpiceDownerBuff.cpp.
void SpiceDownerBuffImplementation::lock (bool doLock = true) protected
Definition at line 114 of file SpiceDownerBuff.cpp.
References _this.
void SpiceDownerBuffImplementation::lock (ManagedObject * obj) protected
Definition at line 118 of file SpiceDownerBuff.cpp.
References _this.
SpiceDownerBuffImplementation::operator const SpiceDownerBuff * ()
Definition at line 110 of file SpiceDownerBuff.cpp.
void SpiceDownerBuffImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 149 of file SpiceDownerBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::initializeTransientMembers(), and readObjectMember().
bool SpiceDownerBuffImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 168 of file SpiceDownerBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::readObjectMember().
Referenced by readObject().
void SpiceDownerBuffImplementation::rlock (bool doLock = true) protected
Definition at line 122 of file SpiceDownerBuff.cpp.
References _this.
void SpiceDownerBuffImplementation::runlock (bool doLock = true) protected
Definition at line 138 of file SpiceDownerBuff.cpp.
References _this.
void SpiceDownerBuffImplementation::unlock (bool doLock = true) protected
Definition at line 134 of file SpiceDownerBuff.cpp.
References _this.
void SpiceDownerBuffImplementation::wlock (bool doLock = true) protected
Definition at line 126 of file SpiceDownerBuff.cpp.
References _this.
void SpiceDownerBuffImplementation::wlock (ManagedObject * obj) protected
Definition at line 130 of file SpiceDownerBuff.cpp.
References _this.
void SpiceDownerBuffImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 178 of file SpiceDownerBuff.cpp.
References writeObjectMembers().
int SpiceDownerBuffImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 185 of file SpiceDownerBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class SpiceDownerBuff friend
Definition at line 162 of file SpiceDownerBuff.h.
Member Data Documentation
WeakReference<SpiceDownerBuff*> server::zone::objects::creature::buffs::SpiceDownerBuffImplementation::_this
Definition at line 128 of file SpiceDownerBuff.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SpiceDownerBuff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SpiceDownerBuff.cpp