Core3: PlaceableLootContainerComponent Class Reference
PlaceableLootContainerComponent Class Reference
#include <PlaceableLootContainerComponent.h>
Public Member Functions
bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
Public Member Functions inherited from ContainerComponent
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
virtual int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Detailed Description
Definition at line 12 of file PlaceableLootContainerComponent.h.
Member Function Documentation
int PlaceableLootContainerComponent::canAddObject (SceneObject * sceneObject, SceneObject * object, int containmentType, String & errorDescription) virtual
Evaluates if this object has the necessary free slots to be able to add the specified SceneObject
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be checked
error error string that the player will receive on error
Returns
returns 0 on success, or error code
Reimplemented from ContainerComponent.
Definition at line 29 of file PlaceableLootContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::getContainerObjectsSize(), and TransferErrorCode::INVALIDTYPE.
bool PlaceableLootContainerComponent::checkContainerPermission (SceneObject * sceneObject, CreatureObject * creature, uint16 permission) virtual
Reimplemented from ContainerComponent.
Definition at line 10 of file PlaceableLootContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::getContainerPermissions(), and server::zone::objects::scene::SceneObject::isContainerObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/PlaceableLootContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/PlaceableLootContainerComponent.cpp