Core3: AffectorHeightConstant Class Reference
AffectorHeightConstant Class Reference
#include <AffectorHeightConstant.h>
Public Member Functions
AffectorHeightConstant ()
void parseFromIffStream (engine::util::IffStream *iffStream)
void parseFromIffStream (engine::util::IffStream *iffStream, Version<'0000'>)
void process (float x, float y, float transformValue, float &baseValue, TerrainGenerator *terrainGenerator)
float getHeight ()
int getOperationType ()
void setHeight (float val)
void setOperationType (int val)
bool isEnabled ()
Public Member Functions inherited from ProceduralRule<'AHCN'>
ProceduralRule ()
bool isEnabled ()
Public Member Functions inherited from TemplateVariable< formType >
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Public Member Functions inherited from AffectorProceduralRule
AffectorProceduralRule ()
virtual ~AffectorProceduralRule ()
bool isHeightTypeAffector ()
bool isEnvoronmentTypeAffector ()
int getAffectorType ()
Private Attributes
int operationType
float height
Additional Inherited Members
Static Public Attributes inherited from AffectorProceduralRule
static const int HEIGHTTYPE = 0x100
static const int HEIGHTFRACTAL = 0x101
static const int HEIGHTTERRACE = 0x102
static const int HEIGHTCONSTANT = 0x103
static const int ENVIRONMENT = 0x200
Protected Attributes inherited from ProceduralRule<'AHCN'>
InformationHeader informationHeader
Protected Attributes inherited from AffectorProceduralRule
int affectorType
Detailed Description
Definition at line 15 of file AffectorHeightConstant.h.
Constructor & Destructor Documentation
AffectorHeightConstant::AffectorHeightConstant () inline
Definition at line 20 of file AffectorHeightConstant.h.
References AffectorProceduralRule::affectorType, and AffectorProceduralRule::HEIGHTCONSTANT.
Member Function Documentation
float AffectorHeightConstant::getHeight () inline
Definition at line 78 of file AffectorHeightConstant.h.
References height.
Referenced by ProceduralTerrainAppearance::setHeight().
int AffectorHeightConstant::getOperationType () inline
Definition at line 82 of file AffectorHeightConstant.h.
References operationType.
Referenced by ProceduralTerrainAppearance::setHeight().
bool AffectorHeightConstant::isEnabled () inline virtual
Reimplemented from AffectorProceduralRule.
Definition at line 94 of file AffectorHeightConstant.h.
References ProceduralRule<'AHCN'>::informationHeader, and InformationHeader::isEnabled().
void AffectorHeightConstant::parseFromIffStream (engine::util::IffStream * iffStream) inline virtual
Reimplemented from TemplateVariable< formType >.
Definition at line 24 of file AffectorHeightConstant.h.
void AffectorHeightConstant::parseFromIffStream (engine::util::IffStream * iffStream, Version<'0000'>) inline
Definition at line 41 of file AffectorHeightConstant.h.
References height, ProceduralRule<'AHCN'>::informationHeader, operationType, and TemplateVariable< formType >::readObject().
void AffectorHeightConstant::process (float x, float y, float transformValue, float & baseValue, TerrainGenerator * terrainGenerator) inline virtual
Reimplemented from AffectorProceduralRule.
Definition at line 52 of file AffectorHeightConstant.h.
References height, and operationType.
void AffectorHeightConstant::setHeight (float val) inline
Definition at line 86 of file AffectorHeightConstant.h.
References height.
Referenced by ProceduralTerrainAppearance::setHeight().
void AffectorHeightConstant::setOperationType (int val) inline
Definition at line 90 of file AffectorHeightConstant.h.
References operationType.
Member Data Documentation
float AffectorHeightConstant::height private
Definition at line 17 of file AffectorHeightConstant.h.
Referenced by getHeight(), parseFromIffStream(), process(), and setHeight().
int AffectorHeightConstant::operationType private
Definition at line 16 of file AffectorHeightConstant.h.
Referenced by getOperationType(), parseFromIffStream(), process(), and setOperationType().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/layer/affectors/AffectorHeightConstant.h