Core3: TerrainManager Class Reference
TerrainManager Class Reference
#include <TerrainManager.h>
Public Member Functions
TerrainManager (Zone *planet)
TerrainManager (ManagedWeakReference< Zone * > planet)
bool initialize (const String &terrainFile)
bool getWaterHeight (float x, float y, float &waterHeight)
float getHighestHeight (float x0, float y0, float x1, float y1, int stepping=1)
int notifyPositionUpdate (CreatureObject *object)
void addTerrainModification (float x, float y, const String &terrainModificationFilename, uint64 objectid)
void removeTerrainModification (uint64 objectid)
ProceduralTerrainAppearance * getProceduralTerrainAppearance ()
float getHeight (float x, float y)
float getMin ()
float getMax ()
float getSize ()
Private Attributes
ProceduralTerrainAppearance terrainData
Zone * zone
Detailed Description
Definition at line 25 of file TerrainManager.h.
Constructor & Destructor Documentation
TerrainManager::TerrainManager (Zone * planet)
Definition at line 12 of file TerrainManager.cpp.
References zone.
TerrainManager::TerrainManager (ManagedWeakReference< Zone * > planet)
Definition at line 16 of file TerrainManager.cpp.
References zone.
Member Function Documentation
void TerrainManager::addTerrainModification (float x, float y, const String & terrainModificationFilename, uint64 objectid)
Definition at line 82 of file TerrainManager.cpp.
References ProceduralTerrainAppearance::addTerrainModification(), and terrainData.
Referenced by ZoneContainerComponent::transferObject().
float TerrainManager::getHeight (float x, float y) inline
Definition at line 58 of file TerrainManager.h.
Referenced by server::zone::managers::mission::spawnmaps::NpcSpawnPoint::allocateNpc(), CollisionManager::checkShipCollision(), server::zone::objects::mission::ReconMissionObjectiveImplementation::getEndPosition(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::getEndPosition(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::getEndPosition(), server::zone::objects::mission::MissionObjectiveImplementation::getEndPosition(), server::zone::ZoneImplementation::getHeight(), CollisionManager::getWorldFloorCollision(), and CollisionManager::getWorldFloorCollisions().
float TerrainManager::getHighestHeight (float x0, float y0, float x1, float y1, int stepping = 1)
    |--------------- | x1,y1
    |----------------| <- stepping
        |----------------|
    |----------------|
*x0,y0 |-------------—|
    |----------------| x1,y1
    |----------------| <- stepping
        |----------------|
    |----------------|
*x0,y0 |-------------—|
Definition at line 39 of file TerrainManager.cpp.
References server::zone::Zone::getHeight(), and zone.
Referenced by StructureManager::placeStructure().
float TerrainManager::getMax () inline
Definition at line 66 of file TerrainManager.h.
float TerrainManager::getMin () inline
Definition at line 62 of file TerrainManager.h.
ProceduralTerrainAppearance* TerrainManager::getProceduralTerrainAppearance () inline
Definition at line 54 of file TerrainManager.h.
float TerrainManager::getSize () inline
Definition at line 70 of file TerrainManager.h.
bool TerrainManager::getWaterHeight (float x, float y, float & waterHeight) inline
Definition at line 36 of file TerrainManager.h.
Referenced by server::zone::managers::minigames::FishingManagerImplementation::checkLocation(), CollisionManager::checkShipCollision(), server::zone::managers::minigames::FishingManagerImplementation::checkUpdateMarker(), server::zone::managers::planet::PlanetManagerImplementation::findClosestWorldFloor(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::findValidSpawnPosition(), CollisionManager::getWorldFloorCollision(), CollisionManager::getWorldFloorCollisions(), notifyPositionUpdate(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission().
bool TerrainManager::initialize (const String & terrainFile)
Definition at line 20 of file TerrainManager.cpp.
References ProceduralTerrainAppearance::load(), and terrainData.
int TerrainManager::notifyPositionUpdate (CreatureObject * object)
Definition at line 65 of file TerrainManager.cpp.
References server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::creature::CreatureObject::getSwimHeight(), getWaterHeight(), server::zone::objects::creature::CreatureObject::hasState(), server::zone::objects::creature::CreatureObject::healDot(), and CreatureState::ONFIRE.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::notifySelfPositionUpdate().
void TerrainManager::removeTerrainModification (uint64 objectid)
Definition at line 97 of file TerrainManager.cpp.
References ProceduralTerrainAppearance::removeTerrainModification(), and terrainData.
Referenced by ZoneContainerComponent::removeObject().
Member Data Documentation
ProceduralTerrainAppearance TerrainManager::terrainData private
Definition at line 26 of file TerrainManager.h.
Referenced by addTerrainModification(), initialize(), and removeTerrainModification().
Zone* TerrainManager::zone private
Definition at line 28 of file TerrainManager.h.
Referenced by getHighestHeight(), and TerrainManager().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/terrain/TerrainManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/terrain/TerrainManager.cpp