Core3: DeltaSet< K, V > Class Template Reference
DeltaSet< K, V > Class Template Reference
#include <DeltaSet.h>
Public Member Functions
DeltaSet ()
DeltaSet (int initsize, int incr)
DeltaSet (const DeltaSet &ds)
void addSerializableVariables ()
virtual int add (const K &key, const V &value, DeltaMessage *message=NULL, int updates=1)
virtual bool drop (const K &key, DeltaMessage *message=NULL, int updates=1)
virtual void removeAll (DeltaMessage *msg)
virtual void insertToMessage (BaseMessage *msg)
V & getValueAt (int index)
K & getKeyAt (int index)
V & get (const K &key)
bool contains (const K &key)
int size ()
uint32 getUpdateCounter ()
void setNullValue (const V &val)
Protected Attributes
VectorMap< K, V > vectorMap
uint32 updateCounter
Detailed Description
template<class K, class V>
class DeltaSet< K, V >
Definition at line 14 of file DeltaSet.h.
Constructor & Destructor Documentation
template<class K, class V> DeltaSet< K, V >::DeltaSet () inline
Definition at line 20 of file DeltaSet.h.
template<class K, class V> DeltaSet< K, V >::DeltaSet (int initsize, int incr) inline
Definition at line 28 of file DeltaSet.h.
template<class K, class V> DeltaSet< K, V >::DeltaSet (const DeltaSet< K, V > & ds) inline
Definition at line 36 of file DeltaSet.h.
Member Function Documentation
template<class K, class V> virtual int DeltaSet< K, V >::add (const K & key, const V & value, DeltaMessage * message = NULL, int updates = 1) inline virtual
Definition at line 49 of file DeltaSet.h.
Referenced by server::zone::managers::guild::GuildManagerImplementation::createGuild(), and server::zone::managers::guild::GuildManagerImplementation::loadGuilds().
template<class K, class V> void DeltaSet< K, V >::addSerializableVariables () inline
Definition at line 44 of file DeltaSet.h.
Referenced by DeltaSet< String, ManagedReference< GuildObject * > >::DeltaSet().
template<class K, class V> bool DeltaSet< K, V >::contains (const K & key) inline
Definition at line 118 of file DeltaSet.h.
Referenced by server::zone::managers::guild::GuildManagerImplementation::disbandGuild().
template<class K, class V> virtual bool DeltaSet< K, V >::drop (const K & key, DeltaMessage * message = NULL, int updates = 1) inline virtual
Definition at line 65 of file DeltaSet.h.
Referenced by server::zone::managers::guild::GuildManagerImplementation::disbandGuild().
template<class K, class V> V& DeltaSet< K, V >::get (const K & key) inline
Definition at line 114 of file DeltaSet.h.
Referenced by server::zone::managers::guild::GuildManagerImplementation::declareWarByName(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::managers::guild::GuildManagerImplementation::guildAbbrevExists(), server::zone::managers::guild::GuildManagerImplementation::guildNameExists(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildListTo().
template<class K, class V> K& DeltaSet< K, V >::getKeyAt (int index) inline
Definition at line 110 of file DeltaSet.h.
Referenced by server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::managers::guild::GuildManagerImplementation::guildAbbrevExists(), server::zone::managers::guild::GuildManagerImplementation::guildNameExists(), DeltaSet< String, ManagedReference< GuildObject * > >::insertToMessage(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildListTo().
template<class K, class V> uint32 DeltaSet< K, V >::getUpdateCounter () inline
Definition at line 126 of file DeltaSet.h.
Referenced by DeltaSet< String, ManagedReference< GuildObject * > >::insertToMessage().
template<class K, class V> V& DeltaSet< K, V >::getValueAt (int index) inline
Definition at line 106 of file DeltaSet.h.
Referenced by server::zone::managers::guild::GuildManagerImplementation::declareWarByName(), and server::zone::managers::guild::GuildManagerImplementation::getGuildFromAbbrev().
template<class K, class V> virtual void DeltaSet< K, V >::insertToMessage (BaseMessage * msg) inline virtual
Definition at line 95 of file DeltaSet.h.
template<class K, class V> virtual void DeltaSet< K, V >::removeAll (DeltaMessage * msg) inline virtual
Definition at line 86 of file DeltaSet.h.
template<class K, class V> void DeltaSet< K, V >::setNullValue (const V & val) inline
Definition at line 130 of file DeltaSet.h.
template<class K, class V> int DeltaSet< K, V >::size () inline
Definition at line 122 of file DeltaSet.h.
Referenced by server::zone::managers::guild::GuildManagerImplementation::declareWarByName(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::managers::guild::GuildManagerImplementation::getGuildFromAbbrev(), server::zone::managers::guild::GuildManagerImplementation::guildAbbrevExists(), server::zone::managers::guild::GuildManagerImplementation::guildNameExists(), DeltaSet< String, ManagedReference< GuildObject * > >::insertToMessage(), server::zone::managers::guild::GuildManagerImplementation::loadGuilds(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildListTo().
Member Data Documentation
template<class K, class V> uint32 DeltaSet< K, V >::updateCounter protected
Definition at line 17 of file DeltaSet.h.
Referenced by DeltaSet< String, ManagedReference< GuildObject * > >::add(), DeltaSet< String, ManagedReference< GuildObject * > >::addSerializableVariables(), DeltaSet< String, ManagedReference< GuildObject * > >::DeltaSet(), DeltaSet< String, ManagedReference< GuildObject * > >::drop(), DeltaSet< String, ManagedReference< GuildObject * > >::getUpdateCounter(), and DeltaSet< String, ManagedReference< GuildObject * > >::removeAll().
template<class K, class V> VectorMap<K, V> DeltaSet< K, V >::vectorMap protected
Definition at line 16 of file DeltaSet.h.
Referenced by DeltaSet< String, ManagedReference< GuildObject * > >::add(), DeltaSet< String, ManagedReference< GuildObject * > >::addSerializableVariables(), DeltaSet< String, ManagedReference< GuildObject * > >::contains(), DeltaSet< String, ManagedReference< GuildObject * > >::DeltaSet(), DeltaSet< String, ManagedReference< GuildObject * > >::drop(), DeltaSet< String, ManagedReference< GuildObject * > >::get(), DeltaSet< String, ManagedReference< GuildObject * > >::getKeyAt(), DeltaSet< String, ManagedReference< GuildObject * > >::getValueAt(), DeltaSet< String, ManagedReference< GuildObject * > >::removeAll(), DeltaSet< String, ManagedReference< GuildObject * > >::setNullValue(), and DeltaSet< String, ManagedReference< GuildObject * > >::size().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/DeltaSet.h