Core3: ZoneContainerComponent Class Reference
ZoneContainerComponent Class Reference
#include <ZoneContainerComponent.h>
Public Member Functions
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
Public Member Functions inherited from ContainerComponent
virtual int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
virtual bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
virtual int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Protected Member Functions
bool insertActiveArea (Zone *zone, ActiveArea *activeArea)
bool removeActiveArea (Zone *zone, ActiveArea *activeArea)
Detailed Description
Definition at line 28 of file ZoneContainerComponent.h.
Member Function Documentation
bool ZoneContainerComponent::insertActiveArea (Zone * zone, ActiveArea * activeArea) protected
Definition at line 18 of file ZoneContainerComponent.cpp.
References server::zone::Zone::addSceneObject(), server::zone::objects::area::ActiveArea::containsPoint(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::area::ActiveArea::enqueueEnterEvent(), server::zone::objects::scene::SceneObject::error(), server::zone::Zone::getInRangeObjects(), server::zone::Zone::getRegionTree(), server::zone::objects::scene::SceneObject::getWorldPosition(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::hasActiveArea(), server::zone::objects::scene::SceneObject::notifyInsertToZone(), and server::zone::objects::scene::SceneObject::setZone().
Referenced by transferObject().
bool ZoneContainerComponent::removeActiveArea (Zone * zone, ActiveArea * activeArea) protected
Definition at line 70 of file ZoneContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::dropActiveArea(), server::zone::Zone::dropSceneObject(), server::zone::objects::area::ActiveArea::enqueueExitEvent(), server::zone::Zone::getInRangeObjects(), server::zone::Zone::getRegionTree(), server::zone::objects::scene::SceneObject::hasActiveArea(), server::zone::objects::scene::SceneObject::notifyRemoveFromZone(), and server::zone::objects::scene::SceneObject::setZone().
Referenced by removeObject().
bool ZoneContainerComponent::removeObject (SceneObject * sceneObject, SceneObject * object, SceneObject * destination, bool notifyClient) virtual
Tries to remove/unlink object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be removed from the current object
notifyClient not used currently
Returns
returns true if the object has been successfully removed
Reimplemented from ContainerComponent.
Definition at line 206 of file ZoneContainerComponent.cpp.
References server::zone::Zone::dropSceneObject(), server::zone::objects::scene::SceneObject::getContainerLock(), server::zone::Zone::getInRangeObjects(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::Zone::getPlanetManager(), server::zone::managers::planet::PlanetManager::getTerrainManager(), SharedBuildingObjectTemplate::getTerrainModificationFile(), server::zone::objects::scene::SceneObject::isActiveArea(), ObserverEventType::OBJECTREMOVEDFROMZONE, server::zone::Zone::remove(), removeActiveArea(), and TerrainManager::removeTerrainModification().
bool ZoneContainerComponent::transferObject (SceneObject * sceneObject, SceneObject * object, int containmentType, bool notifyClient = false, bool allowOverflow = false) virtual
Tries to add/link object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be added to the current object
containmentType arrangement type that will be used to add the object
notifyClient if true in range objects will be updated with the change
Returns
returns true if the object has been successfully added
Reimplemented from ContainerComponent.
Definition at line 122 of file ZoneContainerComponent.cpp.
References server::zone::Zone::addSceneObject(), TerrainManager::addTerrainModification(), server::zone::objects::scene::SceneObject::getParent(), server::zone::Zone::getPlanetManager(), server::zone::managers::planet::PlanetManager::getTerrainManager(), SharedBuildingObjectTemplate::getTerrainModificationFile(), server::zone::objects::scene::SceneObject::getWorldPositionX(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::inRange(), server::zone::Zone::insert(), insertActiveArea(), server::zone::objects::scene::SceneObject::isActiveArea(), server::zone::objects::scene::SceneObject::setZone(), and server::zone::Zone::updateActiveAreas().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneContainerComponent.cpp