Core3: ResourceTree Class Reference
ResourceTree Class Reference
#include <ResourceTree.h>
Public Member Functions
ResourceTree (ResourceSpawner *spawn)
~ResourceTree ()
ResourceTreeEntry * getEntry (const String &type, const Vector< String > &excludes=0, const String &zoneName="")
ResourceTreeNode * getBaseNode ()
void toString ()
Private Member Functions
bool buildTreeFromClient ()
void setZoneRestriction (ResourceTreeEntry *entry)
void setJtl (ResourceTreeEntry *entry)
void setRecycled (ResourceTreeEntry *entry)
void setSurveyToolType (ResourceTreeEntry *entry)
void setRecycleToolType (ResourceTreeEntry *entry)
Private Attributes
ResourceTreeNode * baseNode
The tree's base node.
ResourceSpawner * spawner
Resource Spawner object.
Detailed Description
Definition at line 68 of file ResourceTree.h.
Constructor & Destructor Documentation
ResourceTree::ResourceTree (ResourceSpawner * spawn)
Constructor
Definition at line 59 of file ResourceTree.cpp.
References buildTreeFromClient(), and spawner.
ResourceTree::~ResourceTree ()
Destructor
Definition at line 65 of file ResourceTree.cpp.
References baseNode.
Member Function Documentation
bool ResourceTree::buildTreeFromClient () private
Add entry to the tree
Update the Stf Entries now that the tree is built
Definition at line 70 of file ResourceTree.cpp.
References ResourceTreeNode::add(), ResourceTreeEntry::addAttribute(), ResourceTreeEntry::addClass(), ResourceTreeEntry::addStfClass(), baseNode, DataTableRow::getCell(), DataTableIff::getRow(), DataTableIff::getTotalRows(), DataTableCell::getValue(), DataTableRow::getValue(), TemplateManager::openIffFile(), DataTableIff::readObject(), setJtl(), ResourceTreeEntry::setMaxpool(), ResourceTreeEntry::setMaxtype(), ResourceTreeEntry::setMinpool(), ResourceTreeEntry::setMintype(), ResourceTreeEntry::setRandomNameClass(), setRecycled(), ResourceTreeEntry::setRecycled(), setRecycleToolType(), ResourceTreeEntry::setResourceContainerType(), setSurveyToolType(), and setZoneRestriction().
Referenced by ResourceTree().
ResourceTreeNode* ResourceTree::getBaseNode () inline
Definition at line 97 of file ResourceTree.h.
References baseNode.
Referenced by ResourceSpawner::addNodeToListBox(), ResourceSpawner::addParentNodeToListBox(), and ResourceSpawner::sendResourceRecycleType().
ResourceTreeEntry * ResourceTree::getEntry (const String & type, const Vector< String > & excludes = 0, const String & zoneName = "")
Locates 'type' in Tree
Parameters
type Resource Type
Excludes Vector of items that can't be chosen
zoneid If the resource is tied to a certain zone
Definition at line 175 of file ResourceTree.cpp.
References baseNode, and ResourceTreeNode::getEntry().
Referenced by ResourceSpawner::createResourceSpawn(), ResourceSpawner::getRecycledVersion(), and ResourceSpawner::makeResourceName().
void ResourceTree::setJtl (ResourceTreeEntry * entry) private
Definition at line 194 of file ResourceTree.cpp.
References ResourceSpawner::getJtlResources(), ResourceTreeEntry::getType(), ResourceTreeEntry::setJTL(), and spawner.
Referenced by buildTreeFromClient().
void ResourceTree::setRecycled (ResourceTreeEntry * entry) private
Definition at line 209 of file ResourceTree.cpp.
References ResourceSpawner::getRecycledResources(), ResourceTreeEntry::getType(), ResourceTreeEntry::setRecycled(), and spawner.
Referenced by buildTreeFromClient().
void ResourceTree::setRecycleToolType (ResourceTreeEntry * entry) private
Definition at line 258 of file ResourceTree.cpp.
References ResourceTreeEntry::isType(), and ResourceTreeEntry::setRecycleToolType().
Referenced by buildTreeFromClient().
void ResourceTree::setSurveyToolType (ResourceTreeEntry * entry) private
Definition at line 224 of file ResourceTree.cpp.
References ResourceTreeEntry::getType(), ResourceTreeEntry::isType(), and ResourceTreeEntry::setSurveyToolType().
Referenced by buildTreeFromClient().
void ResourceTree::setZoneRestriction (ResourceTreeEntry * entry) private
Definition at line 179 of file ResourceTree.cpp.
References ResourceSpawner::getActiveResourceZones(), ResourceTreeEntry::getType(), ResourceTreeEntry::setZoneRestriction(), and spawner.
Referenced by buildTreeFromClient().
void ResourceTree::toString ()
Prints the tree
Definition at line 314 of file ResourceTree.cpp.
References baseNode, and ResourceTreeNode::toString().
Member Data Documentation
ResourceTreeNode* ResourceTree::baseNode private
The tree's base node.
Definition at line 72 of file ResourceTree.h.
Referenced by buildTreeFromClient(), getBaseNode(), getEntry(), toString(), and ~ResourceTree().
ResourceSpawner* ResourceTree::spawner private
Resource Spawner object.
Definition at line 75 of file ResourceTree.h.
Referenced by ResourceTree(), setJtl(), setRecycled(), and setZoneRestriction().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcetree/ResourceTree.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/resourcetree/ResourceTree.cpp