Core3: server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionAdapter Class Reference
server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionAdapter Class Reference
#include <CityTreasuryWithdrawalSession.h>
Public Member Functions
CityTreasuryWithdrawalSessionAdapter (CityTreasuryWithdrawalSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setReason (const String &r)
int initializeSession ()
int sendTransferBox (const String &reason)
int withdrawCredits (int value)
int cancelSession ()
int clearSession ()
Detailed Description
Definition at line 187 of file CityTreasuryWithdrawalSession.h.
Constructor & Destructor Documentation
CityTreasuryWithdrawalSessionAdapter::CityTreasuryWithdrawalSessionAdapter (CityTreasuryWithdrawalSession * impl)
Definition at line 337 of file CityTreasuryWithdrawalSession.cpp.
Member Function Documentation
int CityTreasuryWithdrawalSessionAdapter::cancelSession ()
Definition at line 397 of file CityTreasuryWithdrawalSession.cpp.
Referenced by invokeMethod().
int CityTreasuryWithdrawalSessionAdapter::clearSession ()
Definition at line 401 of file CityTreasuryWithdrawalSession.cpp.
Referenced by invokeMethod().
int CityTreasuryWithdrawalSessionAdapter::initializeSession ()
Definition at line 385 of file CityTreasuryWithdrawalSession.cpp.
Referenced by invokeMethod().
void CityTreasuryWithdrawalSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 340 of file CityTreasuryWithdrawalSession.cpp.
References cancelSession(), clearSession(), initializeSession(), RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_INITIALIZESESSION__, RPC_SENDTRANSFERBOX__STRING_, RPC_SETREASON__STRING_, RPC_WITHDRAWCREDITS__INT_, sendTransferBox(), setReason(), and withdrawCredits().
int CityTreasuryWithdrawalSessionAdapter::sendTransferBox (const String & reason)
Definition at line 389 of file CityTreasuryWithdrawalSession.cpp.
Referenced by invokeMethod().
void CityTreasuryWithdrawalSessionAdapter::setReason (const String & r)
Definition at line 381 of file CityTreasuryWithdrawalSession.cpp.
Referenced by invokeMethod().
int CityTreasuryWithdrawalSessionAdapter::withdrawCredits (int value)
Definition at line 393 of file CityTreasuryWithdrawalSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityTreasuryWithdrawalSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityTreasuryWithdrawalSession.cpp