Core3: server::zone::managers::minigames::ForageManagerImplementation Class Reference
server::zone::managers::minigames::ForageManagerImplementation Class Reference
#include <ForageManager.h>
Public Member Functions
ForageManagerImplementation ()
ForageManagerImplementation (DummyConstructorParameter *param)
void deleteForageAreaCollection (String &playerName)
void startForaging (CreatureObject *player, int forageType)
void finishForaging (CreatureObject *player, int forageType, float forageX, float forageY, const String &planet)
bool forageGiveItems (CreatureObject *player, int forageType, float forageX, float forageY, const String &planet)
bool forageGiveResource (CreatureObject *player, float forageX, float forageY, const String &planet, String &resType)
operator const ForageManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< ForageManager * > _this
Static Public Attributes
static const int SCOUT = 1
static const int MEDICAL = 2
static const int LAIR = 3
static const int SHELLFISH = 4
Protected Member Functions
virtual ~ForageManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ForageMap forageAreas
Friends
class ForageManager
Detailed Description
Definition at line 164 of file ForageManager.h.
Constructor & Destructor Documentation
ForageManagerImplementation::ForageManagerImplementation ()
Definition at line 262 of file ForageManager.cpp.
References _initializeImplementation(), and forageAreas.
ForageManagerImplementation::ForageManagerImplementation (DummyConstructorParameter * param)
Definition at line 136 of file ForageManager.cpp.
References _initializeImplementation().
ForageManagerImplementation::~ForageManagerImplementation () protected virtual
Definition at line 141 of file ForageManager.cpp.
Member Function Documentation
DistributedObjectStub * ForageManagerImplementation::_getStub ()
Definition at line 161 of file ForageManager.cpp.
References _this.
void ForageManagerImplementation::_initializeImplementation () protected
Definition at line 148 of file ForageManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ForageManagerImplementation().
void ForageManagerImplementation::_serializationHelperMethod () protected
Definition at line 197 of file ForageManager.cpp.
Referenced by _initializeImplementation().
void ForageManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 156 of file ForageManager.cpp.
References _this.
Referenced by server::zone::managers::minigames::ForageManager::ForageManager().
void ForageManagerImplementation::deleteForageAreaCollection (String & playerName)
Definition at line 272 of file ForageManager.cpp.
References forageAreas.
Referenced by server::zone::managers::minigames::ForageManager::deleteForageAreaCollection().
void ForageManagerImplementation::finalize () protected
Definition at line 145 of file ForageManager.cpp.
void ForageManagerImplementation::finishForaging (CreatureObject * player, int forageType, float forageX, float forageY, const String & planet)
Finishes foraging. Checks if the player moved since first foraging. If so, cancels forage. Checks if the player entered combat. If so, cancels forage. Checks the forage areas to see if the player is allowed to forage here again. If not, cancels forage. Determines if the player is successful or not in the forage attempt. If successful, activates forageGiveItems().
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is not locked, player is not locked }
Parameters
player CreatureObject who is foraging.
scoutForage Determines if the player is using /forage or /medicalforage.
forageX The x coordinate of the player's position when they first started foraging.
forageY The y coordinate of the player's position when they first started foraging.
planet The planet (zone ID) the player was on when they first started foraging.
Definition at line 112 of file ForageManagerImplementation.cpp.
References _this, forageAreas, forageGiveItems(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::creature::CreatureObject::isInCombat(), server::zone::managers::minigames::ForageManager::LAIR, server::zone::managers::minigames::ForageManager::MEDICAL, server::zone::objects::scene::SceneObject::removePendingTask(), server::zone::managers::minigames::ForageManager::SCOUT, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::managers::minigames::ForageManager::SHELLFISH.
Referenced by server::zone::managers::minigames::ForageManager::finishForaging().
bool ForageManagerImplementation::forageGiveItems (CreatureObject * player, int forageType, float forageX, float forageY, const String & planet)
Gives the player items for a successful forage. Checks player's inventory space and discards items they could have received if they had space. Determines which loot group they will get an item from. If resource, calls giveForageResource().
Precondition
{ this object is not locked, player is locked }
Postcondition
{ this object is not locked, player is not locked }
Parameters
player CreatureObject who is foraging.
scoutForage Determines if the player is using /forage or /medicalforage.
forageX The x coordinate of the player's position when they first started foraging.
forageY The y coordinate of the player's position when they first started foraging.
planet The planet (zone ID) the player was on when they first started foraging.
Definition at line 196 of file ForageManagerImplementation.cpp.
References forageGiveResource(), server::zone::ZoneServer::getLootManager(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::managers::minigames::ForageManager::LAIR, server::zone::managers::minigames::ForageManager::MEDICAL, server::zone::managers::minigames::ForageManager::SCOUT, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::managers::minigames::ForageManager::SHELLFISH.
Referenced by finishForaging(), and server::zone::managers::minigames::ForageManager::forageGiveItems().
bool ForageManagerImplementation::forageGiveResource (CreatureObject * player, float forageX, float forageY, const String & planet, String & resType)
Gives the player resources for a successful forage. Pulls a list of all the flora resource spawns on that planet. Picks a random flora from the list and gives it to the player if there is some under them. If the density of the flora is zero, it picks a different resource.
Precondition
{ this object is not locked, player is locked }
Postcondition
{ this object is not locked, player is not locked }
Parameters
player CreatureObject who is foraging.
forageX The x coordinate of the player's position when they first started foraging.
forageY The y coordinate of the player's position when they first started foraging.
planet The planet (zone ID) the player was on when they first started foraging.
Definition at line 338 of file ForageManagerImplementation.cpp.
References server::zone::managers::resource::ResourceManager::getResourceListByType(), server::zone::ZoneServer::getResourceManager(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), and server::zone::objects::scene::SceneObject::getZoneServer().
Referenced by forageGiveItems(), and server::zone::managers::minigames::ForageManager::forageGiveResource().
void ForageManagerImplementation::lock (bool doLock = true) protected
Definition at line 169 of file ForageManager.cpp.
References _this.
void ForageManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 173 of file ForageManager.cpp.
References _this.
ForageManagerImplementation::operator const ForageManager * ()
Definition at line 165 of file ForageManager.cpp.
void ForageManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 204 of file ForageManager.cpp.
References readObjectMember().
bool ForageManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 223 of file ForageManager.cpp.
References forageAreas.
Referenced by readObject().
void ForageManagerImplementation::rlock (bool doLock = true) protected
Definition at line 177 of file ForageManager.cpp.
References _this.
void ForageManagerImplementation::runlock (bool doLock = true) protected
Definition at line 193 of file ForageManager.cpp.
References _this.
void ForageManagerImplementation::startForaging (CreatureObject * player, int forageType)
Starts foraging. Checks the player's pending tasks to see if they are already foraging. If so, cancels forage. Checks if the player is inside a structure. If so, cancels forage. Deducts the foraging action cost from the player. Collects the player's current position so we can compare it after the forage animation is done. Creates the forage task and puts it into the player's pending tasks, it will activate in 8.5 seconds and will activate finishForaging().
Precondition
{ this object is not locked, player is locked }
Postcondition
{ this object is not locked, player is not locked }
Parameters
player CreatureObject who is trying to forage.
scoutForage Determines if the player is using /forage or /medicalforage.
Definition at line 17 of file ForageManagerImplementation.cpp.
References CreatureAttribute::ACTION, server::zone::objects::scene::SceneObject::addPendingTask(), server::zone::objects::creature::CreatureObject::calculateCostAdjustment(), server::zone::objects::creature::CreatureObject::doAnimation(), CreatureAttribute::FOCUS, server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::scene::SceneObject::getParentID(), server::zone::objects::scene::SceneObject::getPendingTask(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::scene::SceneObject::isInWater(), server::zone::objects::creature::CreatureObject::isSwimming(), server::zone::managers::minigames::ForageManager::LAIR, CreatureAttribute::MIND, CreatureAttribute::QUICKNESS, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::managers::minigames::ForageManager::SHELLFISH.
Referenced by server::zone::managers::minigames::ForageManager::startForaging().
void ForageManagerImplementation::unlock (bool doLock = true) protected
Definition at line 189 of file ForageManager.cpp.
References _this.
void ForageManagerImplementation::wlock (bool doLock = true) protected
Definition at line 181 of file ForageManager.cpp.
References _this.
void ForageManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 185 of file ForageManager.cpp.
References _this.
void ForageManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 237 of file ForageManager.cpp.
References writeObjectMembers().
int ForageManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 244 of file ForageManager.cpp.
References forageAreas.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ForageManager friend
Definition at line 278 of file ForageManager.h.
Member Data Documentation
WeakReference<ForageManager*> server::zone::managers::minigames::ForageManagerImplementation::_this
Definition at line 244 of file ForageManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), finishForaging(), lock(), rlock(), runlock(), unlock(), and wlock().
ForageMap server::zone::managers::minigames::ForageManagerImplementation::forageAreas protected
Definition at line 175 of file ForageManager.h.
Referenced by deleteForageAreaCollection(), finishForaging(), ForageManagerImplementation(), readObjectMember(), and writeObjectMembers().
const int server::zone::managers::minigames::ForageManagerImplementation::LAIR = 3 static
Definition at line 170 of file ForageManager.h.
const int server::zone::managers::minigames::ForageManagerImplementation::MEDICAL = 2 static
Definition at line 168 of file ForageManager.h.
const int server::zone::managers::minigames::ForageManagerImplementation::SCOUT = 1 static
Definition at line 166 of file ForageManager.h.
const int server::zone::managers::minigames::ForageManagerImplementation::SHELLFISH = 4 static
Definition at line 172 of file ForageManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/ForageManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/ForageManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/ForageManagerImplementation.cpp