Core3: server::zone::objects::area::areashapes::AreaShapeAdapter Class Reference
server::zone::objects::area::areashapes::AreaShapeAdapter Class Reference
#include <AreaShape.h>
Public Member Functions
AreaShapeAdapter (AreaShape *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setAreaCenter (float x, float y)
bool containsPoint (float x, float y)
float getRadius ()
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
Detailed Description
Definition at line 264 of file AreaShape.h.
Constructor & Destructor Documentation
AreaShapeAdapter::AreaShapeAdapter (AreaShape * impl)
Definition at line 377 of file AreaShape.cpp.
Member Function Documentation
bool AreaShapeAdapter::containsPoint (float x, float y)
Definition at line 433 of file AreaShape.cpp.
Referenced by invokeMethod().
float AreaShapeAdapter::getArea ()
Definition at line 457 of file AreaShape.cpp.
Referenced by invokeMethod().
float AreaShapeAdapter::getRadius ()
Definition at line 437 of file AreaShape.cpp.
Referenced by invokeMethod().
bool AreaShapeAdapter::intersectsWith (AreaShape * areaShape)
Definition at line 453 of file AreaShape.cpp.
Referenced by invokeMethod().
void AreaShapeAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 380 of file AreaShape.cpp.
References containsPoint(), getArea(), getRadius(), intersectsWith(), isCircularAreaShape(), isRectangularAreaShape(), isRingAreaShape(), RPC_CONTAINSPOINT__FLOAT_FLOAT_, RPC_GETAREA__, RPC_GETRADIUS__, RPC_INTERSECTSWITH__AREASHAPE_, RPC_ISCIRCULARAREASHAPE__, RPC_ISRECTANGULARAREASHAPE__, RPC_ISRINGAREASHAPE__, RPC_SETAREACENTER__FLOAT_FLOAT_, and setAreaCenter().
bool AreaShapeAdapter::isCircularAreaShape ()
Definition at line 441 of file AreaShape.cpp.
Referenced by invokeMethod().
bool AreaShapeAdapter::isRectangularAreaShape ()
Definition at line 445 of file AreaShape.cpp.
Referenced by invokeMethod().
bool AreaShapeAdapter::isRingAreaShape ()
Definition at line 449 of file AreaShape.cpp.
Referenced by invokeMethod().
void AreaShapeAdapter::setAreaCenter (float x, float y)
Definition at line 429 of file AreaShape.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/AreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/AreaShape.cpp