Core3: server::web::HttpResponse Class Reference
server::web::HttpResponse Class Reference
#include <HttpResponse.h>
Public Member Functions
HttpResponse (HttpSession *session)
virtual ~HttpResponse ()
void update (struct mg_connection *conn)
void print (String item)
void println (String line)
void forwardTo (String context)
String generatePage ()
void setDocType (String value)
HttpSession * getSession ()
Private Attributes
StringBuffer out
String docType
HttpSession * session
struct mg_connection * conn
Detailed Description
Definition at line 18 of file HttpResponse.h.
Constructor & Destructor Documentation
HttpResponse::HttpResponse (HttpSession * session)
Definition at line 11 of file HttpResponse.cpp.
References docType, and session.
HttpResponse::~HttpResponse () virtual
Definition at line 18 of file HttpResponse.cpp.
Member Function Documentation
void HttpResponse::forwardTo (String context)
Definition at line 27 of file HttpResponse.cpp.
References conn, server::web::session::HttpSession::getRequest(), and session.
Referenced by LoginServlet::handlePost().
String HttpResponse::generatePage ()
Definition at line 39 of file HttpResponse.cpp.
References out.
Referenced by Servlet::outputResponse().
HttpSession* server::web::HttpResponse::getSession () inline
Definition at line 43 of file HttpResponse.h.
References session.
void HttpResponse::print (String item)
Definition at line 31 of file HttpResponse.cpp.
References out.
void HttpResponse::println (String line)
Definition at line 35 of file HttpResponse.cpp.
References out.
Referenced by AdminServlet::handleGet(), LoginServlet::handleGet(), LogsServlet::handleGet(), MainServlet::handleGet(), PermissionsServlet::handleGet(), LoginServlet::handlePost(), PermissionsServlet::handlePost(), and Servlet::handleRequest().
void server::web::HttpResponse::setDocType (String value) inline
Definition at line 39 of file HttpResponse.h.
References docType.
void HttpResponse::update (struct mg_connection * conn)
Definition at line 22 of file HttpResponse.cpp.
References conn, and out.
Referenced by server::web::session::HttpSession::update().
Member Data Documentation
struct mg_connection* server::web::HttpResponse::conn private
Definition at line 25 of file HttpResponse.h.
Referenced by forwardTo(), and update().
String server::web::HttpResponse::docType private
Definition at line 21 of file HttpResponse.h.
Referenced by HttpResponse(), and setDocType().
StringBuffer server::web::HttpResponse::out private
Definition at line 20 of file HttpResponse.h.
Referenced by generatePage(), print(), println(), and update().
HttpSession* server::web::HttpResponse::session private
Definition at line 23 of file HttpResponse.h.
Referenced by forwardTo(), getSession(), and HttpResponse().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/HttpResponse.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/HttpResponse.cpp