Core3: MapGroup Class Reference
MapGroup Class Reference
#include <MapGroup.h>
Public Member Functions
MapGroup ()
~MapGroup ()
void parseFromIffStream (engine::util::IffStream *iffStream)
void parseFromIffStream (engine::util::IffStream *iffStream, Version<'0000'>)
MapFractal * getMfrc (int index)
Public Member Functions inherited from TemplateVariable<'MGRP'>
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Private Attributes
Vector< MapFamily * > mfams
VectorMap< uint32, MapFractal * > mfrcs
Detailed Description
Definition at line 14 of file MapGroup.h.
Constructor & Destructor Documentation
MapGroup::MapGroup () inline
Definition at line 20 of file MapGroup.h.
References mfrcs.
MapGroup::~MapGroup () inline
Definition at line 25 of file MapGroup.h.
References mfams.
Member Function Documentation
MapFractal* MapGroup::getMfrc (int index) inline
Definition at line 58 of file MapGroup.h.
References mfrcs.
Referenced by TerrainGenerator::getMfrc().
void MapGroup::parseFromIffStream (engine::util::IffStream * iffStream) inline virtual
Reimplemented from TemplateVariable<'MGRP'>.
Definition at line 30 of file MapGroup.h.
void MapGroup::parseFromIffStream (engine::util::IffStream * iffStream, Version<'0000'>) inline
Definition at line 47 of file MapGroup.h.
References MapFamily::getMfrc(), MapFamily::getVar1(), mfams, mfrcs, and TemplateVariable< formType >::readObject().
Member Data Documentation
Vector<MapFamily*> MapGroup::mfams private
Definition at line 15 of file MapGroup.h.
Referenced by parseFromIffStream(), and ~MapGroup().
VectorMap<uint32, MapFractal*> MapGroup::mfrcs private
Definition at line 16 of file MapGroup.h.
Referenced by getMfrc(), MapGroup(), and parseFromIffStream().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/MapGroup.h