Core3: server::zone::ZoneSessionMap Class Reference
server::zone::ZoneSessionMap Class Reference
#include <ZoneHandler.h>
Public Member Functions
ZoneSessionMap (int maxconn=10000)
bool add (ZoneClientSession *client)
bool remove (ZoneClientSession *client)
Private Attributes
int maxConnections
Detailed Description
Definition at line 55 of file ZoneHandler.h.
Constructor & Destructor Documentation
server::zone::ZoneSessionMap::ZoneSessionMap (int maxconn = 10000) inline
Definition at line 61 of file ZoneHandler.h.
References maxConnections.
Member Function Documentation
bool server::zone::ZoneSessionMap::add (ZoneClientSession * client) inline
Definition at line 66 of file ZoneHandler.h.
References server::zone::ZoneClientSession::getSession().
Referenced by server::zone::ZoneHandler::createConnection().
bool server::zone::ZoneSessionMap::remove (ZoneClientSession * client) inline
Definition at line 73 of file ZoneHandler.h.
Referenced by server::zone::ZoneHandler::deleteConnection().
Member Data Documentation
int server::zone::ZoneSessionMap::maxConnections private
Definition at line 58 of file ZoneHandler.h.
Referenced by ZoneSessionMap().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneHandler.h