Core3: LootGroupCollection Class Reference
LootGroupCollection Class Reference
#include <LootGroupCollection.h>
Public Member Functions
LootGroupCollection ()
void readObject (LuaObject *obj)
int count ()
LootGroupCollectionEntry * get (int i)
Private Attributes
Vector< LootGroupCollectionEntry > entries
Detailed Description
Definition at line 14 of file LootGroupCollection.h.
Constructor & Destructor Documentation
LootGroupCollection::LootGroupCollection () inline
Definition at line 18 of file LootGroupCollection.h.
Member Function Documentation
int LootGroupCollection::count () inline
Definition at line 41 of file LootGroupCollection.h.
References entries.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootFromCollection().
LootGroupCollectionEntry* LootGroupCollection::get (int i) inline
Definition at line 45 of file LootGroupCollection.h.
References entries.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootFromCollection(), server::zone::objects::creature::ai::AiActorImplementation::getLootGroups(), and server::zone::objects::creature::AiAgentImplementation::getLootGroups().
void LootGroupCollection::readObject (LuaObject * obj) inline
Definition at line 21 of file LootGroupCollection.h.
References entries, and LootGroupCollectionEntry::readObject().
Referenced by server::zone::managers::director::DirectorManager::createLootFromCollection(), and server::zone::templates::mobile::CreatureTemplate::readObject().
Member Data Documentation
Vector<LootGroupCollectionEntry> LootGroupCollection::entries private
Definition at line 15 of file LootGroupCollection.h.
Referenced by count(), get(), and readObject().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/lootgroup/LootGroupCollection.h