Core3: server::zone::managers::object::ObjectManager Class Reference
server::zone::managers::object::ObjectManager Class Reference
#include <ObjectManager.h>
Public Member Functions
ObjectManager ()
~ObjectManager ()
bool contains (uint32 objectCRC)
void loadStaticObjects ()
SceneObject * createObject (uint32 objectCRC, int persistenceLevel, const String &database, uint64 oid=0)
ManagedObject * createObject (const String &className, int persistenceLevel, const String &database, uint64 oid=0, bool initializeTransientMembers=true)
void createObjectID (const String &name, DistributedObjectStub *object)
SceneObject * cloneObject (SceneObject *object, bool makeTransient=false)
void persistObject (ManagedObject *object, int persistenceLevel, const String &database)
void printInfo ()
String getInfo ()
Reference
< DistributedObjectStub * > loadPersistentObject (uint64 objectID)
int updatePersistentObject (DistributedObject *object)
int destroyObjectFromDatabase (uint64 objectID)
uint64 getNextObjectID (const String &database)
uint64 getNextFreeObjectID ()
void onUpdateModifiedObjectsToDatabase ()
void onCommitData ()
ObjectDatabase * loadTable (const String &database, uint64 objectID=0)
void updateObjectVersion ()
void setZoneProcessor (ZoneProcessServer *srv)
Public Attributes
SceneObjectFactory
< SceneObject *(), uint32 > objectFactory
Private Member Functions
void loadLastUsedObjectID ()
void registerObjectTypes ()
SceneObject * loadObjectFromTemplate (uint32 objectCRC)
void deSerializeObject (ManagedObject *object, ObjectInputStream *data)
SceneObject * instantiateSceneObject (uint32 objectCRC, uint64 oid, bool createComponents)
Private Attributes
ManagedReference
< ZoneProcessServer * > server
TemplateManager * templateManager
int galaxyId
Reference< ResultSet * > charactersSaved
AtomicInteger saveCounter
Reference< DeleteCharactersTask * > deleteCharactersTask
Static Private Attributes
static uint32 serverObjectCrcHashCode = String("SceneObject.serverObjectCRC").hashCode()
static uint32 _classNameHashCode = String("_className").hashCode()
Detailed Description
Definition at line 76 of file ObjectManager.h.
Constructor & Destructor Documentation
ObjectManager::ObjectManager ()
Definition at line 38 of file ObjectManager.cpp.
References deleteCharactersTask, loadLastUsedObjectID(), TemplateManager::loadLuaTemplates(), registerObjectTypes(), server, templateManager, and ServerCore::truncateDatabases().
ObjectManager::~ObjectManager ()
Definition at line 73 of file ObjectManager.cpp.
Member Function Documentation
SceneObject * ObjectManager::cloneObject (SceneObject * object, bool makeTransient = false)
Returns a clone of the passed object with new object id if the passed object is persistent, the new object will be too
Definition at line 537 of file ObjectManager.cpp.
References server::zone::objects::scene::SceneObject::createComponents(), getNextFreeObjectID(), getNextObjectID(), server::zone::objects::scene::SceneObject::getObjectID(), instantiateSceneObject(), server::zone::objects::scene::SceneObject::setParent(), and updatePersistentObject().
Referenced by ComponentSlot::add(), server::zone::objects::tangible::TangibleObjectImplementation::createFactoryCrate(), server::zone::objects::factorycrate::FactoryCrateImplementation::extractObject(), server::zone::objects::factorycrate::FactoryCrateImplementation::extractObjectToParent(), server::zone::objects::factorycrate::FactoryCrateImplementation::split(), and FireworkShowContainerComponent::transferObject().
bool server::zone::managers::object::ObjectManager::contains (uint32 objectCRC) inline
Definition at line 113 of file ObjectManager.h.
References objectFactory.
SceneObject * ObjectManager::createObject (uint32 objectCRC, int persistenceLevel, const String & database, uint64 oid = 0)
Definition at line 758 of file ObjectManager.cpp.
References getNextObjectID(), TemplateManager::getTemplateFile(), instantiateSceneObject(), loadTable(), templateManager, and updatePersistentObject().
Referenced by ResourceSpawner::createRecycledResourceSpawn(), ResourceSpawner::createResourceSpawn(), SchematicMap::loadDraftSchematicFile(), loadPersistentObject(), loadStaticObjects(), and ResourceSpawner::spawnScriptResources().
ManagedObject * ObjectManager::createObject (const String & className, int persistenceLevel, const String & database, uint64 oid = 0, bool initializeTransientMembers = true)
Definition at line 789 of file ObjectManager.cpp.
References getNextObjectID(), loadTable(), and updatePersistentObject().
void ObjectManager::createObjectID (const String & name, DistributedObjectStub * object)
Definition at line 827 of file ObjectManager.cpp.
References getNextFreeObjectID().
void ObjectManager::deSerializeObject (ManagedObject * object, ObjectInputStream * data) private
Definition at line 700 of file ObjectManager.cpp.
Referenced by loadPersistentObject(), and loadStaticObjects().
int ObjectManager::destroyObjectFromDatabase (uint64 objectID)
Definition at line 892 of file ObjectManager.cpp.
String ObjectManager::getInfo ()
Definition at line 915 of file ObjectManager.cpp.
uint64 ObjectManager::getNextFreeObjectID ()
Definition at line 866 of file ObjectManager.cpp.
Referenced by cloneObject(), createObjectID(), and getNextObjectID().
uint64 ObjectManager::getNextObjectID (const String & database)
Definition at line 848 of file ObjectManager.cpp.
References getNextFreeObjectID().
Referenced by cloneObject(), createObject(), and persistObject().
SceneObject * ObjectManager::instantiateSceneObject (uint32 objectCRC, uint64 oid, bool createComponents) private
Definition at line 728 of file ObjectManager.cpp.
References loadObjectFromTemplate(), and server.
Referenced by cloneObject(), createObject(), and loadPersistentObject().
void ObjectManager::loadLastUsedObjectID () private
Loads the highest object id without the highest 16 bits that specify the table.
Definition at line 360 of file ObjectManager.cpp.
References ServerCore::truncateDatabases().
Referenced by ObjectManager().
SceneObject * ObjectManager::loadObjectFromTemplate (uint32 objectCRC) private
Definition at line 462 of file ObjectManager.cpp.
References server::zone::templates::SharedObjectTemplate::getGameObjectType(), TemplateManager::getTemplate(), objectFactory, and templateManager.
Referenced by instantiateSceneObject().
Reference< DistributedObjectStub * > ObjectManager::loadPersistentObject (uint64 objectID)
Definition at line 616 of file ObjectManager.cpp.
References _classNameHashCode, createObject(), deSerializeObject(), server::zone::objects::scene::SceneObject::getGameObjectType(), server::zone::objects::scene::SceneObject::getLoggingName(), instantiateSceneObject(), serverObjectCrcHashCode, server::zone::objects::scene::SceneObject::setGameObjectType(), and server::zone::objects::scene::SceneObject::setLoggingName().
void ObjectManager::loadStaticObjects ()
Definition at line 408 of file ObjectManager.cpp.
References createObject(), deSerializeObject(), and serverObjectCrcHashCode.
ObjectDatabase * ObjectManager::loadTable (const String & database, uint64 objectID = 0)
Definition at line 876 of file ObjectManager.cpp.
Referenced by createObject().
void ObjectManager::onCommitData ()
Definition at line 936 of file ObjectManager.cpp.
References charactersSaved, deleteCharactersTask, galaxyId, and ServerDatabase::instance().
void ObjectManager::onUpdateModifiedObjectsToDatabase ()
Definition at line 921 of file ObjectManager.cpp.
References charactersSaved, galaxyId, ServerDatabase::instance(), and server.
void ObjectManager::persistObject (ManagedObject * object, int persistenceLevel, const String & database)
Assigns a new persistent object id, stores in the specified database
Definition at line 585 of file ObjectManager.cpp.
References getNextObjectID(), and updatePersistentObject().
void ObjectManager::printInfo ()
Definition at line 909 of file ObjectManager.cpp.
void ObjectManager::registerObjectTypes () private
Definition at line 82 of file ObjectManager.cpp.
References SceneObjectType::ACTIVEAREA, SceneObjectType::AIGROUP, SceneObjectType::ARMARMOR, SceneObjectType::ARMOR, SceneObjectType::ARMORATTACHMENT, SceneObjectType::ARMORCOMPONENT, SceneObjectType::ARMORUPGRADEKIT, SceneObjectType::BADGEAREA, SceneObjectType::BANDOLIER, SceneObjectType::BANK, SceneObjectType::BAZAAR, SceneObjectType::BELT, SceneObjectType::BODYARMOR, SceneObjectType::BODYSUIT, SceneObjectType::BRACELET, SceneObjectType::BUILDING, SceneObjectType::BUILDINGDEED, SceneObjectType::CAMOKIT, SceneObjectType::CAMPAREA, SceneObjectType::CAMPKIT, SceneObjectType::CAPE, SceneObjectType::CAPITOLBUILDING, SceneObjectType::CARBINE, SceneObjectType::CELLOBJECT, SceneObjectType::CHARACTERBUILDERTERMINAL, SceneObjectType::CHEMISTRYCOMPONENT, SceneObjectType::CLOAK, SceneObjectType::CLONING, SceneObjectType::CLOTHING, SceneObjectType::CLOTHINGATTACHMENT, SceneObjectType::CLOTHINGCOMPONENT, SceneObjectType::COMBATBUILDING, SceneObjectType::COMMERCEBUILDING, SceneObjectType::COMMUNITYCRAFTINGCOMPONENT, SceneObjectType::COMPONENT, SceneObjectType::CONTAINER, SceneObjectType::CRAFTINGSTATION, SceneObjectType::CRAFTINGTOOL, SceneObjectType::CREATURE, SceneObjectType::CUREPACK, SceneObjectType::DATA2, SceneObjectType::DEED, SceneObjectType::DNACOMPONENT, SceneObjectType::DOTPACK, SceneObjectType::DRAFTSCHEMATIC, SceneObjectType::DRESS, SceneObjectType::DRINK, SceneObjectType::DROIDCOMPONENT, SceneObjectType::DROIDCREATURE, SceneObjectType::DYNAMICSPAWNAREA, SceneObjectType::EARRING, SceneObjectType::ELECTRONICSCOMPONENT, SceneObjectType::ENERGYGAS, SceneObjectType::ENERGYLIQUID, SceneObjectType::ENERGYRADIOACTIVE, SceneObjectType::ENERGYSOLID, SceneObjectType::ENHANCEPACK, SceneObjectType::EYEWEAR, SceneObjectType::FACTIONBUILDING, SceneObjectType::FACTORY, SceneObjectType::FACTORYCRATE, SceneObjectType::FIREWORK, SceneObjectType::FISH, SceneObjectType::FISHINGBAIT, SceneObjectType::FISHINGPOLE, SceneObjectType::FLORA, SceneObjectType::FLOWANALYZER, SceneObjectType::FOOD, SceneObjectType::FOOTARMOR, SceneObjectType::FOOTWEAR, SceneObjectType::FSVILLAGEAREA, SceneObjectType::FURNITURE, SceneObjectType::GAMBLINGTERMINAL, SceneObjectType::GARAGEAREA, SceneObjectType::GARAGEBUILDING, SceneObjectType::GARAGEINSTALLATION, SceneObjectType::GENERATOR, SceneObjectType::GENERICITEM, SceneObjectType::GENETICCOMPONENT, SceneObjectType::GROUPOBJECT, SceneObjectType::GUILDOBJECT, SceneObjectType::GUILDTERMINAL, SceneObjectType::HANDARMOR, SceneObjectType::HANDWEAR, SceneObjectType::HARVESTER, SceneObjectType::HEADARMOR, SceneObjectType::HEADWEAR, SceneObjectType::HEAVYWEAPON, SceneObjectType::HEAVYWEAPONPOWERUP, SceneObjectType::HERDGROUP, SceneObjectType::HOSPITALBUILDING, SceneObjectType::HOTELBUILDING, SceneObjectType::HOVERVEHICLE, SceneObjectType::INORGANICCHEMICAL, SceneObjectType::INORGANICGAS, SceneObjectType::INORGANICMINERAL, SceneObjectType::INSTALLATION, SceneObjectType::INSTALLATIONDEED, SceneObjectType::INSTRUMENT, SceneObjectType::INSURANCE, SceneObjectType::INTANGIBLE, SceneObjectType::INTERACTIVETERMINAL, SceneObjectType::ITEM, SceneObjectType::JACKET, SceneObjectType::JEWELRY, SceneObjectType::JUNKDEALERCREATURE, SceneObjectType::LAIR, SceneObjectType::LAIRGROUP, SceneObjectType::LAIRSPAWNAREA, SceneObjectType::LASERKNIFE, SceneObjectType::LEGARMOR, SceneObjectType::LIGHTSABERCRYSTAL, SceneObjectType::LIVESAMPLE, SceneObjectType::LOOTKIT, SceneObjectType::MANUFACTURINGSCHEMATIC, SceneObjectType::MELEEWEAPON, SceneObjectType::MELEEWEAPONCOMPONENT, SceneObjectType::MELEEWEAPONPOWERUP, SceneObjectType::MINE, SceneObjectType::MINEFIELD, SceneObjectType::MINEPOWERUP, SceneObjectType::MISCARMOR, SceneObjectType::MISCCLOTHING, SceneObjectType::MISSIONOBJECT, SceneObjectType::MISSIONRECONAREA, SceneObjectType::MISSIONSPAWNAREA, SceneObjectType::MISSIONTERMINAL, SceneObjectType::MOLECULARCLAMP, SceneObjectType::MUNITIONCOMPONENT, SceneObjectType::NECKLACE, SceneObjectType::NEWBIETUTORIALTERMINAL, SceneObjectType::NPCCREATURE, objectFactory, SceneObjectType::ONEHANDMELEEWEAPON, SceneObjectType::ORGANICFOOD, SceneObjectType::ORGANICHIDE, SceneObjectType::ORGANICSTRUCTURAL, SceneObjectType::PACKGROUP, SceneObjectType::PANTS, SceneObjectType::PETDEED, SceneObjectType::PISTOL, SceneObjectType::PLAYERCREATURE, SceneObjectType::PLAYERLOOTCRATE, SceneObjectType::PLAYEROBJECT, SceneObjectType::PLAYERTERMINALSTRUCTURE, SceneObjectType::POLEARM, SceneObjectType::PROBOTCREATURE, SceneObjectType::QUESTREOURCE, SceneObjectType::RANGEDSTIMPACK, SceneObjectType::RANGEDWEAPON, SceneObjectType::RANGEDWEAPONCOMPONENT, SceneObjectType::RANGEDWEAPONPOWERUP, SceneObjectType::RECREATIONBUILDING, SceneObjectType::RECYCLETOOL, SceneObjectType::REGIONAREA, SceneObjectType::REPAIRTOOL, SceneObjectType::RESOURCECONTAINER, SceneObjectType::RESOURCEDEED, SceneObjectType::RESOURCESPAWN, SceneObjectType::REVIVEPACK, SceneObjectType::RIFLE, SceneObjectType::RING, SceneObjectType::ROBE, SceneObjectType::SALONBUILDING, SceneObjectType::SHIELDGENERATOR, SceneObjectType::SHIPARMOR, SceneObjectType::SHIPATTACHMENT, SceneObjectType::SHIPBOOSTER, SceneObjectType::SHIPCHASSIS, SceneObjectType::SHIPCONTROLDEVICE, SceneObjectType::SHIPCOUNTERMEASURE, SceneObjectType::SHIPCOUNTERMEASURELAUNCHER, SceneObjectType::SHIPDRIODINTERFACE, SceneObjectType::SHIPENGINE, SceneObjectType::SHIPFIGHTER, SceneObjectType::SHIPMISSILE, SceneObjectType::SHIPPINGTERMINAL, SceneObjectType::SHIPREACTOR, SceneObjectType::SHIPSHIELDGENERATOR, SceneObjectType::SHIPSTATION, SceneObjectType::SHIPWEAPON, SceneObjectType::SHIPWEAPONCAPACITOR, SceneObjectType::SHIPWEAPONLAUNCHER, SceneObjectType::SHIRT, SceneObjectType::SHUTTLEINSTALLATION, SceneObjectType::SIGN, SceneObjectType::SKIRT, SceneObjectType::SLICINGTOOL, SceneObjectType::SPACETERMINAL, SceneObjectType::SPECIALHEAVYWEAPON, SceneObjectType::SPECIALHEAVYWEAPONPOWERUP, SceneObjectType::STARPORTBUILDING, SceneObjectType::STATEPACK, SceneObjectType::STATICLOOTCONTAINER, SceneObjectType::STATICOBJECT, SceneObjectType::STATICSPAWNAREA, SceneObjectType::STIMPACK, SceneObjectType::STRUCTURECOMPONENT, SceneObjectType::SURVEYTOOL, SceneObjectType::TANGIBLE, SceneObjectType::TERMINAL, SceneObjectType::THEATERBUILDING, SceneObjectType::THROWNWEAPON, SceneObjectType::THROWNWEAPONPOWERUP, SceneObjectType::TICKETCOLLECTOR, SceneObjectType::TISSUECOMPONENT, SceneObjectType::TOOL, SceneObjectType::TRAP, SceneObjectType::TRAVELBUILDING, SceneObjectType::TRAVELTERMINAL, SceneObjectType::TRAVELTICKET, SceneObjectType::TURRET, SceneObjectType::TUTORIALBUILDING, SceneObjectType::TWOHANDMELEEWEAPON, SceneObjectType::UNIVERSITYBUILDING, SceneObjectType::VEHICLE, SceneObjectType::VEHICLECONTROLDEVICE, SceneObjectType::VEHICLEDEED, SceneObjectType::VENDOR, SceneObjectType::VEST, SceneObjectType::WATER, SceneObjectType::WAYPOINT, SceneObjectType::WEAPON, SceneObjectType::WEAPONPOWERUP, SceneObjectType::WEAPONUPGRADEKIT, SceneObjectType::WEARABLECONTAINER, SceneObjectType::WOOKIEGARB, and SceneObjectType::WOUNDPACK.
Referenced by ObjectManager().
void server::zone::managers::object::ObjectManager::setZoneProcessor (ZoneProcessServer * srv) inline
Definition at line 156 of file ObjectManager.h.
References server.
void ObjectManager::updateObjectVersion ()
Definition at line 352 of file ObjectManager.cpp.
References LoginClientThread::run().
int ObjectManager::updatePersistentObject (DistributedObject * object)
Definition at line 455 of file ObjectManager.cpp.
Referenced by cloneObject(), createObject(), and persistObject().
Member Data Documentation
uint32 ObjectManager::_classNameHashCode = String("_className").hashCode() static private
Definition at line 89 of file ObjectManager.h.
Referenced by loadPersistentObject().
Reference<ResultSet*> server::zone::managers::object::ObjectManager::charactersSaved private
Definition at line 82 of file ObjectManager.h.
Referenced by onCommitData(), and onUpdateModifiedObjectsToDatabase().
Reference<DeleteCharactersTask*> server::zone::managers::object::ObjectManager::deleteCharactersTask private
Definition at line 86 of file ObjectManager.h.
Referenced by ObjectManager(), and onCommitData().
int server::zone::managers::object::ObjectManager::galaxyId private
Definition at line 81 of file ObjectManager.h.
Referenced by onCommitData(), and onUpdateModifiedObjectsToDatabase().
SceneObjectFactory<SceneObject* (), uint32> server::zone::managers::object::ObjectManager::objectFactory
Definition at line 92 of file ObjectManager.h.
Referenced by contains(), loadObjectFromTemplate(), and registerObjectTypes().
AtomicInteger server::zone::managers::object::ObjectManager::saveCounter private
Definition at line 84 of file ObjectManager.h.
ManagedReference<ZoneProcessServer*> server::zone::managers::object::ObjectManager::server private
Definition at line 77 of file ObjectManager.h.
Referenced by instantiateSceneObject(), ObjectManager(), onUpdateModifiedObjectsToDatabase(), and setZoneProcessor().
uint32 ObjectManager::serverObjectCrcHashCode = String("SceneObject.serverObjectCRC").hashCode() static private
Definition at line 88 of file ObjectManager.h.
Referenced by loadPersistentObject(), and loadStaticObjects().
TemplateManager* server::zone::managers::object::ObjectManager::templateManager private
Definition at line 79 of file ObjectManager.h.
Referenced by createObject(), loadObjectFromTemplate(), and ObjectManager().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/object/ObjectManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/object/ObjectManager.cpp