Core3: server::zone::objects::player::sessions::survey::SurveySessionAdapter Class Reference
server::zone::objects::player::sessions::survey::SurveySessionAdapter Class Reference
#include <SurveySession.h>
Public Member Functions
SurveySessionAdapter (SurveySession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession (SurveyTool *tool)
int cancelSession ()
int clearSession ()
void startSurvey (const String &resname)
void reSample ()
void startSample (const String &resname)
void surveyCnodeMinigame (int value)
void surveyGnodeMinigame (int value)
ManagedWeakReference
< SurveyTool * > getActiveSurveyTool ()
void setActiveSurveyTool (SurveyTool *tool)
ManagedWeakReference
< SurveyTool * > getOpenSurveyTool ()
void setOpenSurveyTool (SurveyTool *tool)
bool tryGamble ()
void clearGamble ()
void clearRichSampleLocation ()
Detailed Description
Definition at line 334 of file SurveySession.h.
Constructor & Destructor Documentation
SurveySessionAdapter::SurveySessionAdapter (SurveySession * impl)
Definition at line 484 of file SurveySession.cpp.
Member Function Documentation
int SurveySessionAdapter::cancelSession ()
Definition at line 577 of file SurveySession.cpp.
Referenced by invokeMethod().
void SurveySessionAdapter::clearGamble ()
Definition at line 625 of file SurveySession.cpp.
Referenced by invokeMethod().
void SurveySessionAdapter::clearRichSampleLocation ()
Definition at line 629 of file SurveySession.cpp.
Referenced by invokeMethod().
int SurveySessionAdapter::clearSession ()
Definition at line 581 of file SurveySession.cpp.
Referenced by invokeMethod().
ManagedWeakReference< SurveyTool * > SurveySessionAdapter::getActiveSurveyTool ()
Definition at line 605 of file SurveySession.cpp.
Referenced by invokeMethod().
ManagedWeakReference< SurveyTool * > SurveySessionAdapter::getOpenSurveyTool ()
Definition at line 613 of file SurveySession.cpp.
Referenced by invokeMethod().
int SurveySessionAdapter::initializeSession (SurveyTool * tool)
Definition at line 573 of file SurveySession.cpp.
Referenced by invokeMethod().
void SurveySessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 487 of file SurveySession.cpp.
References cancelSession(), clearGamble(), clearRichSampleLocation(), clearSession(), getActiveSurveyTool(), getOpenSurveyTool(), initializeSession(), reSample(), RPC_CANCELSESSION__, RPC_CLEARGAMBLE__, RPC_CLEARRICHSAMPLELOCATION__, RPC_CLEARSESSION__, RPC_GETACTIVESURVEYTOOL__, RPC_GETOPENSURVEYTOOL__, RPC_INITIALIZESESSION__SURVEYTOOL_, RPC_RESAMPLE__, RPC_SETACTIVESURVEYTOOL__SURVEYTOOL_, RPC_SETOPENSURVEYTOOL__SURVEYTOOL_, RPC_STARTSAMPLE__STRING_, RPC_STARTSURVEY__STRING_, RPC_SURVEYCNODEMINIGAME__INT_, RPC_SURVEYGNODEMINIGAME__INT_, RPC_TRYGAMBLE__, setActiveSurveyTool(), setOpenSurveyTool(), startSample(), startSurvey(), surveyCnodeMinigame(), surveyGnodeMinigame(), and tryGamble().
void SurveySessionAdapter::reSample ()
Definition at line 589 of file SurveySession.cpp.
Referenced by invokeMethod().
void SurveySessionAdapter::setActiveSurveyTool (SurveyTool * tool)
Definition at line 609 of file SurveySession.cpp.
Referenced by invokeMethod().
void SurveySessionAdapter::setOpenSurveyTool (SurveyTool * tool)
Definition at line 617 of file SurveySession.cpp.
Referenced by invokeMethod().
void SurveySessionAdapter::startSample (const String & resname)
Definition at line 593 of file SurveySession.cpp.
Referenced by invokeMethod().
void SurveySessionAdapter::startSurvey (const String & resname)
Definition at line 585 of file SurveySession.cpp.
Referenced by invokeMethod().
void SurveySessionAdapter::surveyCnodeMinigame (int value)
Definition at line 597 of file SurveySession.cpp.
Referenced by invokeMethod().
void SurveySessionAdapter::surveyGnodeMinigame (int value)
Definition at line 601 of file SurveySession.cpp.
Referenced by invokeMethod().
bool SurveySessionAdapter::tryGamble ()
Definition at line 621 of file SurveySession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/survey/SurveySession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/survey/SurveySession.cpp