Core3: server::zone::managers::mission::spawnmaps::UniverseSpawnMap Class Reference
server::zone::managers::mission::spawnmaps::UniverseSpawnMap Class Reference
#include <UniverseSpawnMap.h>
Public Member Functions
void readObject (LuaObject *luaObject)
void addCities (LuaObject *cities)
PlanetSpawnMap * getPlanet (const uint32 planetCRC)
bool parseFromBinaryStream (ObjectInputStream *stream)
bool toBinaryStream (ObjectOutputStream *stream)
void saveSpawnPoints (std::ofstream &file)
Protected Attributes
VectorMap< uint32, Reference
< PlanetSpawnMap * > > planetSpawnMaps
Detailed Description
Container for all planets in the universe and their spawn points.
Definition at line 59 of file UniverseSpawnMap.h.
Member Function Documentation
void server::zone::managers::mission::spawnmaps::UniverseSpawnMap::addCities (LuaObject * cities) inline
Add cities from lua object.
Parameters
cities the cities to add.
Definition at line 100 of file UniverseSpawnMap.h.
References planetSpawnMaps.
Referenced by server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::loadSpawnPointsFromLua().
PlanetSpawnMap* server::zone::managers::mission::spawnmaps::UniverseSpawnMap::getPlanet (const uint32 planetCRC) inline
Return a requested planet.
Parameters
planetName the name of the planet.
Returns
the requested planet.
Definition at line 128 of file UniverseSpawnMap.h.
References planetSpawnMaps.
Referenced by server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::addSpawnPoint(), server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::findSpawnAt(), server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::getRandomCityCoordinates(), and server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::getRandomNpcSpawnPoint().
bool server::zone::managers::mission::spawnmaps::UniverseSpawnMap::parseFromBinaryStream (ObjectInputStream * stream) inline
Load the object from a stream.
Parameters
stream the stream to load the object from.
Returns
true if successful.
Definition at line 137 of file UniverseSpawnMap.h.
References planetSpawnMaps.
Referenced by server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::parseFromBinaryStream().
void server::zone::managers::mission::spawnmaps::UniverseSpawnMap::readObject (LuaObject * luaObject) inline
Read the object from a LuaObject.
Parameters
luaObject the object to load from.
Definition at line 71 of file UniverseSpawnMap.h.
References planetSpawnMaps.
Referenced by server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::loadSpawnPointsFromLua().
void server::zone::managers::mission::spawnmaps::UniverseSpawnMap::saveSpawnPoints (std::ofstream & file) inline
Saves the spawn points to a file.
Parameters
file the file stream to save the spawn points to.
Definition at line 154 of file UniverseSpawnMap.h.
References planetSpawnMaps.
Referenced by server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::saveSpawnPoints().
bool server::zone::managers::mission::spawnmaps::UniverseSpawnMap::toBinaryStream (ObjectOutputStream * stream) inline
Write the object to a stream.
Parameters
stream the stream to write the object to.
Returns
true if successful.
Definition at line 146 of file UniverseSpawnMap.h.
References planetSpawnMaps.
Referenced by server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::toBinaryStream().
Member Data Documentation
VectorMap<uint32, Reference<PlanetSpawnMap* > > server::zone::managers::mission::spawnmaps::UniverseSpawnMap::planetSpawnMaps protected
Map for all planets and their spawn points.
Definition at line 64 of file UniverseSpawnMap.h.
Referenced by addCities(), getPlanet(), parseFromBinaryStream(), readObject(), saveSpawnPoints(), and toBinaryStream().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/mission/spawnmaps/UniverseSpawnMap.h