Core3: server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation Class Reference
server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation Class Reference
#include <TutorialBuildingObject.h>
Public Member Functions
TutorialBuildingObjectImplementation ()
TutorialBuildingObjectImplementation (DummyConstructorParameter *param)
void notifyRemoveFromZone ()
void initializeTransientMembers ()
void onEnter (CreatureObject *player)
void onExit (CreatureObject *player)
void clearUnloadEvent ()
operator const TutorialBuildingObject * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::building::BuildingObjectImplementation
BuildingObjectImplementation ()
BuildingObjectImplementation (DummyConstructorParameter *param)
void createCellObjects ()
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void createContainerComponent ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void updateSignName (bool notifyClient)
void sendContainerObjectsTo (SceneObject *player)
void updateCellPermissionsTo (CreatureObject *creature)
void broadcastCellPermissions ()
void broadcastCellPermissions (unsigned long long objectid)
bool isAllowedEntry (CreatureObject *player)
bool isCityBanned (CreatureObject *player)
virtual int notifyStructurePlaced (CreatureObject *player)
bool hasTemplateEjectionPoint ()
Vector3 getTemplateEjectionPoint ()
Vector3 getEjectionPoint ()
void ejectObject (CreatureObject *creature)
void notifyLoadFromDatabase ()
void notifyInsert (QuadTreeEntry *obj)
void notifyInsertToZone (Zone *zone)
void notifyDissapear (QuadTreeEntry *obj)
void notifyObjectInsertedToZone (SceneObject *object)
void insert (QuadTreeEntry *obj)
void remove (QuadTreeEntry *obj)
void update (QuadTreeEntry *obj)
void inRange (QuadTreeEntry *obj, float range)
void sendTo (SceneObject *player, bool doClose)
void sendBaselinesTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void addCell (CellObject *cell, unsigned int cellNumber)
bool isStaticBuilding ()
CellObject * getCell (unsigned int idx)
int getTotalCellNumber ()
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
int getCurrentNumberOfPlayerItems ()
void destroyAllPlayerItems ()
virtual void onExit (CreatureObject *player, unsigned long long parentid)
bool isBuildingObject ()
void setSignObject (SignObject *sign)
SignObject * getSignObject ()
bool isPublicStructure ()
bool isPrivateStructure ()
void setPublicStructure (bool privacy)
bool isCondemned ()
int getMapCellSize ()
bool togglePrivacy ()
virtual unsigned int getMaximumNumberOfPlayerItems ()
String getRedeedMessage ()
bool hasAccessFee ()
int getAccessFee ()
bool canChangeAccessFee ()
void setAccessFee (int fee, int duration)
void removeAccessFee ()
int getAccessFeeDelay ()
void payAccessFee (CreatureObject *player)
void updatePaidAccessList ()
void createChildObjects ()
void spawnChildSceneObject (String &templatePath, float x, float z, float y, unsigned long long cellID, float dw, float dx, float dy, float dz)
void spawnChildCreaturesFromTemplate ()
void spawnChildCreature (String &mobile, int respawnTimer, float x, float z, float y, float heading, unsigned long long cellID)
bool hasTemplateChildCreatures ()
void destroyChildObjects ()
bool isResidence ()
void setResidence (bool isResidence)
int getFactionBaseType ()
operator const BuildingObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::structure::StructureObjectImplementation
StructureObjectImplementation ()
StructureObjectImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void finalize ()
void loadTemplateData (SharedObjectTemplate *templateData)
void notifyInsertToZone (Zone *zone)
void createChildObjects ()
virtual bool checkRequisitesForPlacement (CreatureObject *player)
String getTimeString (unsigned int timestamp)
void scheduleMaintenanceExpirationEvent ()
void scheduleMaintenanceTask (int timeFromNow)
virtual void updateStructureStatus ()
bool isOnAdminList (CreatureObject *player)
bool isOnAdminList (const String &firstName, bool caseSensitive=false)
bool isOnEntryList (CreatureObject *player)
bool isOnBanList (CreatureObject *player)
bool isOnBanList (const String &firstName, bool caseSensitive=false)
bool isOnHopperList (CreatureObject *player)
bool isOnPermissionList (const String &listName, CreatureObject *player)
bool isOnPermissionList (const String &listName, const String &firstName, bool caseSensitive=false)
bool isOwnerOf (SceneObject *obj)
bool isOwnerOf (unsigned long long oid)
bool isOnAccessList (SceneObject *obj)
bool isOnAccessList (unsigned long long oid)
void sendPermissionListTo (CreatureObject *creature, const String &listName)
bool hasPermissionList (const String &listName)
bool isPermissionListFull (const String &listName)
int togglePermission (const String &listName, const String &targetName, bool caseSensitive=false)
int grantPermission (const String &listName, const String &targetName, bool caseSensitive=false)
int revokePermission (const String &listName, const String &targetName, bool caseSensitive=false)
int revokeAllPermissions (const String &targetName, bool caseSensitive=false)
void setOwnerName (const String &ownerName)
int getRedeedCost ()
CreatureObject * getOwnerCreatureObject ()
unsigned long long getOwnerObjectID ()
unsigned long long getDeedObjectID ()
int getLotSize ()
void setMaintenanceReduced (bool value)
float getMaintenanceRate ()
String getMaintenanceMods ()
int getBaseMaintenanceRate ()
int getBasePowerRate ()
int getSurplusMaintenance ()
int getSurplusPower ()
void setOwnerObjectID (unsigned long long objectID)
void setDeedObjectID (unsigned long long deedID)
void setBaseMaintenanceRate (int rate)
void setBasePowerRate (int rate)
void setSurplusMaintenance (int surplus)
void addMaintenance (float add)
void payMaintenance (int maintenance, CreatureObject *payer, bool cashFirst)
void setSurplusPower (int surplus)
void addPower (float add)
bool isDecaying ()
bool isDecayed ()
int getDecayPercentage ()
bool isStructureObject ()
bool isCampStructure ()
bool isRedeedable ()
AABBTree * getAABBTree ()
void addTemplateSkillMods (TangibleObject *targetObject)
void removeTemplateSkillMods (TangibleObject *tangibleObject)
bool isCivicStructure ()
bool isCityHall ()
bool isCommercialStructure ()
operator const StructureObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
TangibleObjectImplementation ()
TangibleObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
virtual void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
virtual void removeSkillModsFrom (CreatureObject *creature)
virtual void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
virtual void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
virtual void removeAllSkillModsOfType (const int skillType, bool notifyClient=true)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
virtual void setDefender (SceneObject *defender)
virtual void addDefender (SceneObject *defender)
virtual void removeDefender (SceneObject *defender)
virtual void removeDefenders ()
virtual void setCombatState ()
virtual void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
virtual void clearCombatState (bool clearDefenders=true)
bool hasDefender (SceneObject *defender)
virtual bool isAttackableBy (CreatureObject *object)
virtual bool isAggressiveTo (CreatureObject *object)
virtual bool isHealableBy (CreatureObject *object)
virtual void sendPvpStatusTo (CreatureObject *player)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
virtual int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
virtual void updateCraftingValues (CraftingValues *values, bool firstUpdate)
virtual int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
virtual bool isKiller ()
virtual bool isTicketCollector ()
virtual bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
virtual int getUseCount ()
virtual int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
virtual bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
virtual String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
virtual int getJunkDealerNeeded ()
void setJunkValue (int jValue)
virtual int getJunkValue ()
void setSerialNumber (const String &serial)
virtual void setLevel (int lev)
virtual String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
virtual String repairAttempt (int repairChance)
bool isBroken ()
virtual float getHitChance ()
void broadcastPvpStatusBitmask ()
operator const TangibleObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
virtual void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
virtual int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< TutorialBuildingObject * > _this
Public Attributes inherited from server::zone::objects::building::BuildingObjectImplementation
bool publicStructure
WeakReference< BuildingObject * > _this
Public Attributes inherited from server::zone::objects::structure::StructureObjectImplementation
WeakReference< StructureObject * > _this
Public Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
WeakReference< TangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Protected Member Functions
void dequeueUnloadEvent ()
void enqueueUnloadEvent ()
virtual ~TutorialBuildingObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::building::BuildingObjectImplementation
virtual ~BuildingObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::structure::StructureObjectImplementation
virtual ~StructureObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
float getConditionReduction (float value)
virtual ~TangibleObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
Reference< UnloadBuildingTask * > unloadTask
Protected Attributes inherited from server::zone::objects::building::BuildingObjectImplementation
VectorMap< unsigned int,
ManagedReference< CellObject * > > cells
int totalCellNumber
ManagedReference< SignObject * > signObject
unsigned long long deedObjectID
int accessFee
int accessDuration
unsigned int lastAccessFeeChange
Mutex paidAccessListMutex
VectorMap< unsigned long long,
unsigned int > paidAccessList
SortedVector< ManagedReference
< CreatureObject * > > childCreatureObjects
UnicodeString signName
bool isOwnerResidence
int factionBaseType
Protected Attributes inherited from server::zone::objects::structure::StructureObjectImplementation
Reference
< StructureMaintenanceTask * > structureMaintenanceTask
StructurePermissionList structurePermissionList
Time lastMaintenanceTime
Time maintenanceExpires
Time powerExpires
unsigned long long ownerObjectID
unsigned long long deedObjectID
int baseMaintenanceRate
int basePowerRate
float surplusMaintenance
float surplusPower
bool maintenanceReduced
Protected Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
bool targetable
float complexity
int volume
unsigned int faction
CustomizationVariables customizationVariables
float conditionDamage
int maxCondition
int useCount
short level
unsigned int optionsBitmask
unsigned int pvpStatusBitmask
byte unknownByte
String craftersName
int junkDealerNeeded
int junkValue
String objectSerial
Reference< ThreatMap * > threatMap
DeltaVector< ManagedReference
< SceneObject * > > defenderList
bool sliceable
bool sliced
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Friends
class TutorialBuildingObject
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::building::BuildingObjectImplementation
static const int MAXPLAYERITEMS = 400
Detailed Description
Definition at line 153 of file TutorialBuildingObject.h.
Constructor & Destructor Documentation
TutorialBuildingObjectImplementation::TutorialBuildingObjectImplementation ()
Definition at line 240 of file TutorialBuildingObject.cpp.
References _initializeImplementation(), and unloadTask.
TutorialBuildingObjectImplementation::TutorialBuildingObjectImplementation (DummyConstructorParameter * param)
Definition at line 126 of file TutorialBuildingObject.cpp.
References _initializeImplementation().
TutorialBuildingObjectImplementation::~TutorialBuildingObjectImplementation () protected virtual
Definition at line 131 of file TutorialBuildingObject.cpp.
Member Function Documentation
DistributedObjectStub * TutorialBuildingObjectImplementation::_getStub ()
Definition at line 151 of file TutorialBuildingObject.cpp.
References _this.
void TutorialBuildingObjectImplementation::_initializeImplementation () protected
Definition at line 138 of file TutorialBuildingObject.cpp.
References _serializationHelperMethod(), and _this.
Referenced by TutorialBuildingObjectImplementation().
void TutorialBuildingObjectImplementation::_serializationHelperMethod () protected
Definition at line 187 of file TutorialBuildingObject.cpp.
References server::zone::objects::building::BuildingObjectImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void TutorialBuildingObjectImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 146 of file TutorialBuildingObject.cpp.
References server::zone::objects::building::BuildingObjectImplementation::_setStub(), and _this.
Referenced by server::zone::objects::building::tutorial::TutorialBuildingObject::TutorialBuildingObject().
void TutorialBuildingObjectImplementation::clearUnloadEvent ()
Definition at line 269 of file TutorialBuildingObject.cpp.
References unloadTask.
Referenced by server::zone::objects::building::tutorial::TutorialBuildingObject::clearUnloadEvent(), and dequeueUnloadEvent().
void TutorialBuildingObjectImplementation::dequeueUnloadEvent () protected
Definition at line 274 of file TutorialBuildingObject.cpp.
References clearUnloadEvent(), and unloadTask.
Referenced by onEnter().
void TutorialBuildingObjectImplementation::enqueueUnloadEvent () protected
Definition at line 49 of file TutorialBuildingObjectImplementation.cpp.
References _this, and unloadTask.
Referenced by onExit().
void TutorialBuildingObjectImplementation::finalize () protected
Definition at line 135 of file TutorialBuildingObject.cpp.
void TutorialBuildingObjectImplementation::initializeTransientMembers ()
Definition at line 248 of file TutorialBuildingObject.cpp.
References server::zone::objects::building::BuildingObjectImplementation::initializeTransientMembers(), and unloadTask.
Referenced by server::zone::objects::building::tutorial::TutorialBuildingObject::initializeTransientMembers(), and readObject().
void TutorialBuildingObjectImplementation::lock (bool doLock = true) protected
Definition at line 159 of file TutorialBuildingObject.cpp.
References _this.
void TutorialBuildingObjectImplementation::lock (ManagedObject * obj) protected
Definition at line 163 of file TutorialBuildingObject.cpp.
References _this.
void TutorialBuildingObjectImplementation::notifyRemoveFromZone () virtual
Reimplemented from server::zone::objects::building::BuildingObjectImplementation.
Definition at line 54 of file TutorialBuildingObjectImplementation.cpp.
Referenced by server::zone::objects::building::tutorial::TutorialBuildingObject::notifyRemoveFromZone().
void TutorialBuildingObjectImplementation::onEnter (CreatureObject * player) virtual
Abstract function that is triggered when a player enters a building. This function should only be called from CreatureObject::insertToBuilding. Overloaded functions must meet the post conditions for this function.
Precondition
{ player is locked, zone is locked }
Postcondition
{ player is locked, zone is locked }
Parameters
player CreatureObject that entered the building
Reimplemented from server::zone::objects::building::BuildingObjectImplementation.
Definition at line 257 of file TutorialBuildingObject.cpp.
References dequeueUnloadEvent(), and server::zone::objects::creature::CreatureObject::isPlayerCreature().
Referenced by server::zone::objects::building::tutorial::TutorialBuildingObject::onEnter().
void TutorialBuildingObjectImplementation::onExit (CreatureObject * player)
Definition at line 263 of file TutorialBuildingObject.cpp.
References enqueueUnloadEvent(), and server::zone::objects::creature::CreatureObject::isPlayerCreature().
Referenced by server::zone::objects::building::tutorial::TutorialBuildingObject::onExit().
TutorialBuildingObjectImplementation::operator const TutorialBuildingObject * ()
Definition at line 155 of file TutorialBuildingObject.cpp.
void TutorialBuildingObjectImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::building::BuildingObjectImplementation.
Definition at line 194 of file TutorialBuildingObject.cpp.
References initializeTransientMembers(), and readObjectMember().
bool TutorialBuildingObjectImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 213 of file TutorialBuildingObject.cpp.
References server::zone::objects::building::BuildingObjectImplementation::readObjectMember().
Referenced by readObject().
void TutorialBuildingObjectImplementation::rlock (bool doLock = true) protected
Definition at line 167 of file TutorialBuildingObject.cpp.
References _this.
void TutorialBuildingObjectImplementation::runlock (bool doLock = true) protected
Definition at line 183 of file TutorialBuildingObject.cpp.
References _this.
void TutorialBuildingObjectImplementation::unlock (bool doLock = true) protected
Definition at line 179 of file TutorialBuildingObject.cpp.
References _this.
void TutorialBuildingObjectImplementation::wlock (bool doLock = true) protected
Definition at line 171 of file TutorialBuildingObject.cpp.
References _this.
void TutorialBuildingObjectImplementation::wlock (ManagedObject * obj) protected
Definition at line 175 of file TutorialBuildingObject.cpp.
References _this.
void TutorialBuildingObjectImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::building::BuildingObjectImplementation.
Definition at line 223 of file TutorialBuildingObject.cpp.
References writeObjectMembers().
int TutorialBuildingObjectImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 230 of file TutorialBuildingObject.cpp.
References server::zone::objects::building::BuildingObjectImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class TutorialBuildingObject friend
Definition at line 212 of file TutorialBuildingObject.h.
Member Data Documentation
WeakReference<TutorialBuildingObject*> server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation::_this
Definition at line 178 of file TutorialBuildingObject.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), enqueueUnloadEvent(), lock(), rlock(), runlock(), unlock(), and wlock().
Reference<UnloadBuildingTask* > server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation::unloadTask protected
Definition at line 155 of file TutorialBuildingObject.h.
Referenced by clearUnloadEvent(), dequeueUnloadEvent(), enqueueUnloadEvent(), initializeTransientMembers(), and TutorialBuildingObjectImplementation().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/building/tutorial/TutorialBuildingObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/building/tutorial/TutorialBuildingObject.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/building/tutorial/TutorialBuildingObjectImplementation.cpp