Core3: DiceDataComponent Class Reference
DiceDataComponent Class Reference
#include <DiceDataComponent.h>
Public Member Functions
DiceDataComponent ()
virtual ~DiceDataComponent ()
void setSides (byte count)
byte getSides ()
bool isDiceData ()
Public Member Functions inherited from DataObjectComponent
DataObjectComponent ()
~DataObjectComponent ()
virtual void initializeTransientMembers ()
virtual void notifyObjectDestroyingFromDatabase ()
void setParent (SceneObject *object)
SceneObject * getParent ()
virtual bool isVendorData ()
virtual bool isAuctionTerminalData ()
virtual bool isCreatureHabitatData ()
virtual bool isBuildingData ()
virtual bool isDestructibleBuildingData ()
virtual bool isTurretData ()
virtual bool isDetectorData ()
virtual bool isGCWBaseData ()
virtual bool isSecurityTerminalData ()
virtual bool isMinefieldData ()
virtual bool isTurretControlTerminalData ()
virtual bool isDecoration ()
Protected Attributes
byte sides
Protected Attributes inherited from DataObjectComponent
ManagedWeakReference
< SceneObject * > parent
Private Member Functions
void addSerializableVariables ()
Detailed Description
Definition at line 13 of file DiceDataComponent.h.
Constructor & Destructor Documentation
DiceDataComponent::DiceDataComponent () inline
Definition at line 17 of file DiceDataComponent.h.
References addSerializableVariables(), and sides.
virtual DiceDataComponent::~DiceDataComponent () inline virtual
Definition at line 22 of file DiceDataComponent.h.
Member Function Documentation
void DiceDataComponent::addSerializableVariables () inline private
Definition at line 39 of file DiceDataComponent.h.
References sides.
Referenced by DiceDataComponent().
byte DiceDataComponent::getSides () inline
Definition at line 30 of file DiceDataComponent.h.
References sides.
Referenced by DiceMenuComponent::handleObjectMenuSelect().
bool DiceDataComponent::isDiceData () inline virtual
Reimplemented from DataObjectComponent.
Definition at line 34 of file DiceDataComponent.h.
void DiceDataComponent::setSides (byte count) inline
Definition at line 26 of file DiceDataComponent.h.
References sides.
Referenced by DiceMenuComponent::handleObjectMenuSelect().
Member Data Documentation
byte DiceDataComponent::sides protected
Definition at line 15 of file DiceDataComponent.h.
Referenced by addSerializableVariables(), DiceDataComponent(), getSides(), and setSides().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/generic/DiceDataComponent.h