Core3: DataTransformWithParent Class Reference
DataTransformWithParent Class Reference
#include <DataTransformWithParent.h>
Public Member Functions
DataTransformWithParent (SceneObject *creo)
Public Member Functions inherited from ObjectControllerMessage
ObjectControllerMessage (uint64 objid, uint32 header1, uint32 header2, bool comp=true)
Detailed Description
Definition at line 60 of file DataTransformWithParent.h.
Constructor & Destructor Documentation
DataTransformWithParent::DataTransformWithParent (SceneObject * creo) inline
Definition at line 62 of file DataTransformWithParent.h.
References server::zone::objects::scene::SceneObject::getDirectionW(), server::zone::objects::scene::SceneObject::getDirectionX(), server::zone::objects::scene::SceneObject::getDirectionY(), server::zone::objects::scene::SceneObject::getDirectionZ(), server::zone::objects::scene::SceneObject::getMovementCounter(), and server::zone::objects::scene::SceneObject::getParentID().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/object/DataTransformWithParent.h