Core3: InstallationObjectMessage7 Class Reference
InstallationObjectMessage7 Class Reference
#include <InstallationObjectMessage7.h>
Public Member Functions
InstallationObjectMessage7 (InstallationObject *inso)
void insertResourceIDList (ResourceList *list)
void insertResourceNameList (ResourceList *list)
void insertResourceTypeList (ResourceList *list)
void insertHopperItems (InstallationObject *inso)
Public Member Functions inherited from BaseLineMessage
BaseLineMessage (uint64 oid, uint32 name, uint8 type, uint16 opcnt)
uint32 generateRandomObjectCRC ()
void setSize ()
void insertStringId (StringId *id)
void insertCustomName (const UnicodeString &name)
Detailed Description
Definition at line 56 of file InstallationObjectMessage7.h.
Constructor & Destructor Documentation
InstallationObjectMessage7::InstallationObjectMessage7 (InstallationObject * inso) inline
Definition at line 58 of file InstallationObjectMessage7.h.
References server::zone::objects::installation::InstallationObject::getActualRate(), server::zone::objects::installation::InstallationObject::getExtractionRate(), server::zone::objects::installation::InstallationObject::getHopperSize(), server::zone::objects::installation::InstallationObject::getHopperSizeMax(), server::zone::ZoneServer::getResourceManager(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::Zone::getZoneServer(), insertHopperItems(), insertResourceIDList(), insertResourceNameList(), insertResourceTypeList(), server::zone::objects::installation::InstallationObject::isOperating(), and BaseLineMessage::setSize().
Member Function Documentation
void InstallationObjectMessage7::insertHopperItems (InstallationObject * inso) inline
Definition at line 155 of file InstallationObjectMessage7.h.
References server::zone::objects::installation::InstallationObject::getHopperItemQuantity().
Referenced by InstallationObjectMessage7().
void InstallationObjectMessage7::insertResourceIDList (ResourceList * list) inline
Definition at line 116 of file InstallationObjectMessage7.h.
Referenced by InstallationObjectMessage7().
void InstallationObjectMessage7::insertResourceNameList (ResourceList * list) inline
Definition at line 130 of file InstallationObjectMessage7.h.
Referenced by InstallationObjectMessage7().
void InstallationObjectMessage7::insertResourceTypeList (ResourceList * list) inline
Definition at line 143 of file InstallationObjectMessage7.h.
Referenced by InstallationObjectMessage7().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/installation/InstallationObjectMessage7.h