Core3: HQMenuComponent Class Reference
HQMenuComponent Class Reference
#include <HQMenuComponent.h>
Public Member Functions
void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Static Protected Attributes
static const int MAKEREBEL = 222
static const int MAKEIMPERIAL = 223
static const int MAKENEUTRAL = 224
static const int DESTROY = 225
static const int ABORTSHUTDOWN = 226
static const int JAMUPLINK = 227
Detailed Description
Definition at line 15 of file HQMenuComponent.h.
Member Function Documentation
void HQMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from ObjectMenuComponent.
Definition at line 31 of file HQMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID(), server::zone::managers::gcw::GCWManager::canUseTerminals(), SceneObjectType::FACTIONBUILDING, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::Zone::getGCWManager(), server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::managers::gcw::GCWManager::isPowerOverloaded(), server::zone::managers::gcw::GCWManager::isShutdownSequenceStarted(), and CreatureFlag::OVERT.
int HQMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from ObjectMenuComponent.
Definition at line 90 of file HQMenuComponent.cpp.
References SceneObjectType::FACTIONBUILDING, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::creature::CreatureObject::getFactionRank(), server::zone::Zone::getGCWManager(), server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::managers::gcw::GCWManager::sendStatus(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Member Data Documentation
const int HQMenuComponent::ABORTSHUTDOWN = 226 static protected
Definition at line 23 of file HQMenuComponent.h.
const int HQMenuComponent::DESTROY = 225 static protected
Definition at line 22 of file HQMenuComponent.h.
const int HQMenuComponent::JAMUPLINK = 227 static protected
Definition at line 25 of file HQMenuComponent.h.
const int HQMenuComponent::MAKEIMPERIAL = 223 static protected
Definition at line 19 of file HQMenuComponent.h.
const int HQMenuComponent::MAKENEUTRAL = 224 static protected
Definition at line 21 of file HQMenuComponent.h.
const int HQMenuComponent::MAKEREBEL = 222 static protected
Definition at line 18 of file HQMenuComponent.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/terminal/components/HQMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/terminal/components/HQMenuComponent.cpp