Core3: server::zone::objects::mission::BountyMissionObjectiveImplementation Class Reference
server::zone::objects::mission::BountyMissionObjectiveImplementation Class Reference
#include <BountyMissionObjective.h>
Public Member Functions
BountyMissionObjectiveImplementation (MissionObject *mission)
BountyMissionObjectiveImplementation (DummyConstructorParameter *param)
void finalize ()
void initializeTransientMembers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void spawnTarget (const String &zoneName)
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void setNpcTemplateToSpawn (SharedObjectTemplate *sp)
void updateMissionStatus (int informantLevel)
int getObjectiveStatus ()
SceneObject * getArakydDroid ()
void setArakydDroid (SceneObject *droid)
void performDroidAction (int action, SceneObject *sceneObject, CreatureObject *player)
bool playerHasMissionOfCorrectLevel (int action)
void updateWaypoint ()
Vector3 getTargetPosition ()
void cancelAllTasks ()
String getTargetZoneName ()
Vector3 getEndPosition ()
operator const BountyMissionObjective * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
MissionObjectiveImplementation (MissionObject *parent)
MissionObjectiveImplementation (DummyConstructorParameter *param)
virtual void destroyObjectFromDatabase ()
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
virtual void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
operator const MissionObjective * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< BountyMissionObjective * > _this
Public Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
WeakReference< MissionObjective * > _this
Static Public Attributes
static const int INITSTATUS = 0
static const int HASBIOSIGNATURESTATUS = 1
static const int HASTALKED = 2
static const int TARGETELIMINATEDSTATUS = 3
Protected Member Functions
virtual ~BountyMissionObjectiveImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
virtual ~MissionObjectiveImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
TemplateReference
< SharedObjectTemplate * > npcTemplateToSpawn
ManagedReference< AiAgent * > npcTarget
int objectiveStatus
ManagedReference< SceneObject * > activeDroid
Reference< BountyHunterDroid * > droid
FindTargetTaskList droidTasks
Reference
< BountyHunterTargetTask * > targetTask
Mutex syncMutex
Protected Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
ManagedWeakReference
< MissionObject * > mission
unsigned int objectiveType
Time missionStartTime
Reference
< FailMissionAfterCertainTimeTask * > failTask
unsigned long long timeRemaining
bool activated
Private Member Functions
void addToBountyLock ()
void removeFromBountyLock (bool immediately)
void removePlayerTargetObservers ()
void removeNpcTargetObservers ()
void removeObserver (int observerNumber, unsigned int observerType, CreatureObject *creature)
void addObserverToCreature (unsigned int observerType, CreatureObject *creature)
bool addPlayerTargetObservers ()
void startNpcTargetTask ()
bool isPlayerTarget ()
void handleNpcTargetKilled (ManagedObject *arg1)
int handleNpcTargetReceivesDamage (ManagedObject *arg1)
void handlePlayerKilled (ManagedObject *arg1)
void handleDefenderAdded (ManagedObject *arg1)
void handleDefenderDropped (ManagedObject *arg1)
Friends
class BountyMissionObjective
Detailed Description
Definition at line 210 of file BountyMissionObjective.h.
Constructor & Destructor Documentation
BountyMissionObjectiveImplementation::BountyMissionObjectiveImplementation (MissionObject * mission)
Definition at line 506 of file BountyMissionObjective.cpp.
References _initializeImplementation(), activeDroid, droid, INITSTATUS, and objectiveStatus.
BountyMissionObjectiveImplementation::BountyMissionObjectiveImplementation (DummyConstructorParameter * param)
Definition at line 310 of file BountyMissionObjective.cpp.
References _initializeImplementation().
BountyMissionObjectiveImplementation::~BountyMissionObjectiveImplementation () protected virtual
Definition at line 315 of file BountyMissionObjective.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * BountyMissionObjectiveImplementation::_getStub ()
Definition at line 333 of file BountyMissionObjective.cpp.
References _this.
void BountyMissionObjectiveImplementation::_initializeImplementation () protected
Definition at line 320 of file BountyMissionObjective.cpp.
References _serializationHelperMethod(), and _this.
Referenced by BountyMissionObjectiveImplementation().
void BountyMissionObjectiveImplementation::_serializationHelperMethod () protected
Definition at line 369 of file BountyMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void BountyMissionObjectiveImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 328 of file BountyMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_setStub(), and _this.
Referenced by server::zone::objects::mission::BountyMissionObjective::BountyMissionObjective().
void BountyMissionObjectiveImplementation::abort () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 66 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::abort(), cancelAllTasks(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::hasObservers(), server::zone::objects::waypoint::WaypointObject::isActive(), isPlayerTarget(), server::zone::objects::mission::MissionObjectiveImplementation::mission, removeFromBountyLock(), removeNpcTargetObservers(), removePlayerTargetObservers(), server::zone::objects::waypoint::WaypointObject::setActive(), and syncMutex.
Referenced by server::zone::objects::mission::BountyMissionObjective::abort(), activate(), and handleNpcTargetKilled().
void BountyMissionObjectiveImplementation::activate () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 30 of file BountyMissionObjectiveImplementation.cpp.
References abort(), server::zone::objects::mission::MissionObjectiveImplementation::activate(), addPlayerTargetObservers(), server::zone::objects::mission::MissionObjectiveImplementation::getObserverCount(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), isPlayerTarget(), server::zone::objects::mission::MissionObjectiveImplementation::removeMissionFromPlayer(), removeNpcTargetObservers(), startNpcTargetTask(), and syncMutex.
Referenced by server::zone::objects::mission::BountyMissionObjective::activate().
void BountyMissionObjectiveImplementation::addObserverToCreature (unsigned int observerType, CreatureObject * creature) private
Definition at line 420 of file BountyMissionObjectiveImplementation.cpp.
References _this, and server::zone::objects::mission::MissionObjectiveImplementation::addObserver().
Referenced by addPlayerTargetObservers(), and spawnTarget().
bool BountyMissionObjectiveImplementation::addPlayerTargetObservers () private
Definition at line 427 of file BountyMissionObjectiveImplementation.cpp.
References addObserverToCreature(), ObserverEventType::DEFENDERADDED, ObserverEventType::DEFENDERDROPPED, server::zone::ZoneServer::getObject(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::mission, ObserverEventType::PLAYERKILLED, and syncMutex.
Referenced by activate().
void BountyMissionObjectiveImplementation::addToBountyLock () private
Definition at line 337 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::mission, and syncMutex.
Referenced by handleDefenderAdded().
void BountyMissionObjectiveImplementation::cancelAllTasks ()
Definition at line 292 of file BountyMissionObjectiveImplementation.cpp.
References droidTasks, syncMutex, and targetTask.
Referenced by abort(), server::zone::objects::mission::BountyMissionObjective::cancelAllTasks(), complete(), and finalize().
void BountyMissionObjectiveImplementation::complete () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 100 of file BountyMissionObjectiveImplementation.cpp.
References cancelAllTasks(), server::zone::objects::mission::MissionObjectiveImplementation::complete(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::mission, removeFromBountyLock(), and syncMutex.
Referenced by server::zone::objects::mission::BountyMissionObjective::complete(), handleNpcTargetKilled(), and handlePlayerKilled().
void BountyMissionObjectiveImplementation::deactivate () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 56 of file BountyMissionObjectiveImplementation.cpp.
References activeDroid, and server::zone::objects::mission::MissionObjectiveImplementation::deactivate().
Referenced by server::zone::objects::mission::BountyMissionObjective::deactivate().
void BountyMissionObjectiveImplementation::finalize ()
Definition at line 518 of file BountyMissionObjective.cpp.
References cancelAllTasks().
Referenced by ~BountyMissionObjectiveImplementation().
SceneObject * BountyMissionObjectiveImplementation::getArakydDroid ()
Definition at line 535 of file BountyMissionObjective.cpp.
References activeDroid.
Referenced by server::zone::objects::mission::BountyMissionObjective::getArakydDroid().
Vector3 BountyMissionObjectiveImplementation::getEndPosition () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 545 of file BountyMissionObjective.cpp.
References getTargetPosition().
Referenced by server::zone::objects::mission::BountyMissionObjective::getEndPosition().
int BountyMissionObjectiveImplementation::getObjectiveStatus ()
Definition at line 530 of file BountyMissionObjective.cpp.
References objectiveStatus.
Referenced by server::zone::objects::mission::BountyMissionObjective::getObjectiveStatus().
Vector3 BountyMissionObjectiveImplementation::getTargetPosition ()
Definition at line 266 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::ZoneServer::getObject(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::scene::SceneObject::getWorldPosition(), isPlayerTarget(), server::zone::objects::mission::MissionObjectiveImplementation::mission, syncMutex, and targetTask.
Referenced by getEndPosition(), server::zone::objects::mission::BountyMissionObjective::getTargetPosition(), spawnTarget(), and updateWaypoint().
String BountyMissionObjectiveImplementation::getTargetZoneName ()
Definition at line 311 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::ZoneServer::getObject(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), isPlayerTarget(), server::zone::objects::mission::MissionObjectiveImplementation::mission, syncMutex, and targetTask.
Referenced by server::zone::objects::mission::BountyMissionObjective::getTargetZoneName(), and updateWaypoint().
void BountyMissionObjectiveImplementation::handleDefenderAdded (ManagedObject * arg1) private
Definition at line 558 of file BountyMissionObjectiveImplementation.cpp.
References addToBountyLock(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), and server::zone::objects::mission::MissionObjectiveImplementation::mission.
Referenced by notifyObserverEvent().
void BountyMissionObjectiveImplementation::handleDefenderDropped (ManagedObject * arg1) private
Definition at line 574 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::mission, and removeFromBountyLock().
Referenced by notifyObserverEvent().
void BountyMissionObjectiveImplementation::handleNpcTargetKilled (ManagedObject * arg1) private
Definition at line 477 of file BountyMissionObjectiveImplementation.cpp.
References abort(), complete(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::mission::MissionObjectiveImplementation::mission, server::zone::objects::mission::MissionObjectiveImplementation::removeMissionFromPlayer(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by notifyObserverEvent().
int BountyMissionObjectiveImplementation::handleNpcTargetReceivesDamage (ManagedObject * arg1) private
Definition at line 500 of file BountyMissionObjectiveImplementation.cpp.
References server::chat::ChatManager::broadcastMessage(), server::zone::ZoneServer::getChatManager(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::scene::SceneObject::getZoneServer(), HASBIOSIGNATURESTATUS, server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::mission::MissionObjectiveImplementation::mission, npcTarget, objectiveStatus, and updateMissionStatus().
Referenced by notifyObserverEvent().
void BountyMissionObjectiveImplementation::handlePlayerKilled (ManagedObject * arg1) private
Definition at line 526 of file BountyMissionObjectiveImplementation.cpp.
References complete(), server::zone::objects::mission::MissionObjectiveImplementation::fail(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::mission, npcTarget, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by notifyObserverEvent().
void BountyMissionObjectiveImplementation::initializeTransientMembers () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 523 of file BountyMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::initializeTransientMembers().
Referenced by server::zone::objects::mission::BountyMissionObjective::initializeTransientMembers(), and readObject().
bool BountyMissionObjectiveImplementation::isPlayerTarget () private
Definition at line 471 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::mission.
Referenced by abort(), activate(), getTargetPosition(), getTargetZoneName(), and spawnTarget().
void BountyMissionObjectiveImplementation::lock (bool doLock = true) protected
Definition at line 341 of file BountyMissionObjective.cpp.
References _this.
void BountyMissionObjectiveImplementation::lock (ManagedObject * obj) protected
Definition at line 345 of file BountyMissionObjective.cpp.
References _this.
int BountyMissionObjectiveImplementation::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 159 of file BountyMissionObjectiveImplementation.cpp.
References ObserverEventType::DAMAGERECEIVED, ObserverEventType::DEFENDERADDED, ObserverEventType::DEFENDERDROPPED, handleDefenderAdded(), handleDefenderDropped(), handleNpcTargetKilled(), handleNpcTargetReceivesDamage(), handlePlayerKilled(), ObserverEventType::OBJECTDESTRUCTION, ObserverEventType::PLAYERKILLED, and syncMutex.
Referenced by server::zone::objects::mission::BountyMissionObjective::notifyObserverEvent().
BountyMissionObjectiveImplementation::operator const BountyMissionObjective * ()
Definition at line 337 of file BountyMissionObjective.cpp.
void BountyMissionObjectiveImplementation::performDroidAction (int action, SceneObject * sceneObject, CreatureObject * player)
Definition at line 236 of file BountyMissionObjectiveImplementation.cpp.
References droid, droidTasks, server::zone::objects::mission::MissionObjectiveImplementation::getMissionObject(), playerHasMissionOfCorrectLevel(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and syncMutex.
Referenced by server::zone::objects::mission::BountyMissionObjective::performDroidAction().
bool BountyMissionObjectiveImplementation::playerHasMissionOfCorrectLevel (int action)
Definition at line 253 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::mission, and syncMutex.
Referenced by performDroidAction(), and server::zone::objects::mission::BountyMissionObjective::playerHasMissionOfCorrectLevel().
void BountyMissionObjectiveImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 376 of file BountyMissionObjective.cpp.
References initializeTransientMembers(), and readObjectMember().
bool BountyMissionObjectiveImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 395 of file BountyMissionObjective.cpp.
References activeDroid, droid, droidTasks, npcTarget, npcTemplateToSpawn, objectiveStatus, server::zone::objects::mission::MissionObjectiveImplementation::readObjectMember(), and targetTask.
Referenced by readObject().
void BountyMissionObjectiveImplementation::removeFromBountyLock (bool immediately) private
Definition at line 351 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::mission, and syncMutex.
Referenced by abort(), complete(), and handleDefenderDropped().
void BountyMissionObjectiveImplementation::removeNpcTargetObservers () private
Definition at line 386 of file BountyMissionObjectiveImplementation.cpp.
References ObserverEventType::DAMAGERECEIVED, server::zone::objects::mission::MissionObjectiveImplementation::dropObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getObserver(), npcTarget, ObserverEventType::OBJECTDESTRUCTION, removeObserver(), and syncMutex.
Referenced by abort(), and activate().
void BountyMissionObjectiveImplementation::removeObserver (int observerNumber, unsigned int observerType, CreatureObject * creature) private
Definition at line 407 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::dropObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getObserverCount(), and syncMutex.
Referenced by removeNpcTargetObservers(), and removePlayerTargetObservers().
void BountyMissionObjectiveImplementation::removePlayerTargetObservers () private
Definition at line 365 of file BountyMissionObjectiveImplementation.cpp.
References ObserverEventType::DEFENDERADDED, ObserverEventType::DEFENDERDROPPED, server::zone::ZoneServer::getObject(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::mission, ObserverEventType::PLAYERKILLED, removeObserver(), and syncMutex.
Referenced by abort().
void BountyMissionObjectiveImplementation::rlock (bool doLock = true) protected
Definition at line 349 of file BountyMissionObjective.cpp.
References _this.
void BountyMissionObjectiveImplementation::runlock (bool doLock = true) protected
Definition at line 365 of file BountyMissionObjective.cpp.
References _this.
void BountyMissionObjectiveImplementation::setArakydDroid (SceneObject * droid)
Definition at line 540 of file BountyMissionObjective.cpp.
References activeDroid, and droid.
Referenced by server::zone::objects::mission::BountyMissionObjective::setArakydDroid().
void BountyMissionObjectiveImplementation::setNpcTemplateToSpawn (SharedObjectTemplate * sp)
Definition at line 26 of file BountyMissionObjectiveImplementation.cpp.
References npcTemplateToSpawn.
Referenced by server::zone::objects::mission::BountyMissionObjective::setNpcTemplateToSpawn().
void BountyMissionObjectiveImplementation::spawnTarget (const String & zoneName)
Definition at line 117 of file BountyMissionObjectiveImplementation.cpp.
References addObserverToCreature(), ObserverEventType::DAMAGERECEIVED, server::zone::objects::mission::MissionObjectiveImplementation::fail(), server::zone::Zone::getCreatureManager(), server::zone::Zone::getHeight(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), getTargetPosition(), server::zone::ZoneServer::getZone(), isPlayerTarget(), server::zone::objects::mission::MissionObjectiveImplementation::mission, npcTarget, ObserverEventType::OBJECTDESTRUCTION, server::zone::managers::creature::CreatureManager::spawnCreature(), and syncMutex.
Referenced by server::zone::objects::mission::BountyMissionObjective::spawnTarget().
void BountyMissionObjectiveImplementation::startNpcTargetTask () private
Definition at line 459 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::mission, syncMutex, and targetTask.
Referenced by activate(), and updateMissionStatus().
void BountyMissionObjectiveImplementation::unlock (bool doLock = true) protected
Definition at line 361 of file BountyMissionObjective.cpp.
References _this.
void BountyMissionObjectiveImplementation::updateMissionStatus (int informantLevel)
Definition at line 177 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), HASBIOSIGNATURESTATUS, HASTALKED, INITSTATUS, server::zone::objects::mission::MissionObjectiveImplementation::mission, objectiveStatus, startNpcTargetTask(), syncMutex, and updateWaypoint().
Referenced by handleNpcTargetReceivesDamage(), and server::zone::objects::mission::BountyMissionObjective::updateMissionStatus().
void BountyMissionObjectiveImplementation::updateWaypoint ()
Definition at line 213 of file BountyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), getTargetPosition(), getTargetZoneName(), server::zone::objects::mission::MissionObjectiveImplementation::mission, server::zone::objects::waypoint::WaypointObject::setActive(), server::zone::objects::waypoint::WaypointObject::setPlanetCRC(), and syncMutex.
Referenced by updateMissionStatus(), and server::zone::objects::mission::BountyMissionObjective::updateWaypoint().
void BountyMissionObjectiveImplementation::wlock (bool doLock = true) protected
Definition at line 353 of file BountyMissionObjective.cpp.
References _this.
void BountyMissionObjectiveImplementation::wlock (ManagedObject * obj) protected
Definition at line 357 of file BountyMissionObjective.cpp.
References _this.
void BountyMissionObjectiveImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 433 of file BountyMissionObjective.cpp.
References writeObjectMembers().
int BountyMissionObjectiveImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 440 of file BountyMissionObjective.cpp.
References activeDroid, droid, droidTasks, npcTarget, npcTemplateToSpawn, objectiveStatus, targetTask, and server::zone::objects::mission::MissionObjectiveImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class BountyMissionObjective friend
Definition at line 343 of file BountyMissionObjective.h.
Member Data Documentation
WeakReference<BountyMissionObjective*> server::zone::objects::mission::BountyMissionObjectiveImplementation::_this
Definition at line 311 of file BountyMissionObjective.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addObserverToCreature(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedReference<SceneObject* > server::zone::objects::mission::BountyMissionObjectiveImplementation::activeDroid protected
Definition at line 218 of file BountyMissionObjective.h.
Referenced by BountyMissionObjectiveImplementation(), deactivate(), getArakydDroid(), readObjectMember(), setArakydDroid(), and writeObjectMembers().
Reference<BountyHunterDroid* > server::zone::objects::mission::BountyMissionObjectiveImplementation::droid protected
Definition at line 220 of file BountyMissionObjective.h.
Referenced by BountyMissionObjectiveImplementation(), performDroidAction(), readObjectMember(), setArakydDroid(), and writeObjectMembers().
FindTargetTaskList server::zone::objects::mission::BountyMissionObjectiveImplementation::droidTasks protected
Definition at line 222 of file BountyMissionObjective.h.
Referenced by cancelAllTasks(), performDroidAction(), readObjectMember(), and writeObjectMembers().
const int server::zone::objects::mission::BountyMissionObjectiveImplementation::HASBIOSIGNATURESTATUS = 1 static
Definition at line 231 of file BountyMissionObjective.h.
Referenced by handleNpcTargetReceivesDamage(), and updateMissionStatus().
const int server::zone::objects::mission::BountyMissionObjectiveImplementation::HASTALKED = 2 static
Definition at line 233 of file BountyMissionObjective.h.
Referenced by updateMissionStatus().
const int server::zone::objects::mission::BountyMissionObjectiveImplementation::INITSTATUS = 0 static
Definition at line 229 of file BountyMissionObjective.h.
Referenced by BountyMissionObjectiveImplementation(), and updateMissionStatus().
ManagedReference<AiAgent* > server::zone::objects::mission::BountyMissionObjectiveImplementation::npcTarget protected
Definition at line 214 of file BountyMissionObjective.h.
Referenced by handleNpcTargetReceivesDamage(), handlePlayerKilled(), readObjectMember(), removeNpcTargetObservers(), spawnTarget(), and writeObjectMembers().
TemplateReference<SharedObjectTemplate*> server::zone::objects::mission::BountyMissionObjectiveImplementation::npcTemplateToSpawn protected
Definition at line 212 of file BountyMissionObjective.h.
Referenced by readObjectMember(), setNpcTemplateToSpawn(), and writeObjectMembers().
int server::zone::objects::mission::BountyMissionObjectiveImplementation::objectiveStatus protected
Definition at line 216 of file BountyMissionObjective.h.
Referenced by BountyMissionObjectiveImplementation(), getObjectiveStatus(), handleNpcTargetReceivesDamage(), readObjectMember(), updateMissionStatus(), and writeObjectMembers().
Mutex server::zone::objects::mission::BountyMissionObjectiveImplementation::syncMutex protected
Definition at line 226 of file BountyMissionObjective.h.
Referenced by abort(), activate(), addPlayerTargetObservers(), addToBountyLock(), cancelAllTasks(), complete(), getTargetPosition(), getTargetZoneName(), notifyObserverEvent(), performDroidAction(), playerHasMissionOfCorrectLevel(), removeFromBountyLock(), removeNpcTargetObservers(), removeObserver(), removePlayerTargetObservers(), spawnTarget(), startNpcTargetTask(), updateMissionStatus(), and updateWaypoint().
const int server::zone::objects::mission::BountyMissionObjectiveImplementation::TARGETELIMINATEDSTATUS = 3 static
Definition at line 235 of file BountyMissionObjective.h.
Reference<BountyHunterTargetTask* > server::zone::objects::mission::BountyMissionObjectiveImplementation::targetTask protected
Definition at line 224 of file BountyMissionObjective.h.
Referenced by cancelAllTasks(), getTargetPosition(), getTargetZoneName(), readObjectMember(), startNpcTargetTask(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/BountyMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/BountyMissionObjective.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/BountyMissionObjectiveImplementation.cpp