Core3: server::login::account::AccountManager Class Reference
server::login::account::AccountManager Class Reference
#include <AccountManager.h>
Public Member Functions
AccountManager (LoginServer *loginserv)
~AccountManager ()
void loginAccount (LoginClient *client, Message *packet)
Account * validateAccountCredentials (LoginClient *client, const String &username, const String &password)
Account * createAccount (const String &username, const String &password, String &passwordStored)
void updateHash (const String &username, const String &password)
void setMaxOnlineCharacters (uint32 maxonline)
uint32 getMaxOnlineCharacters ()
void setRequiredVersion (const String &version)
void setAutoRegistrationEnabled (bool enabled)
void setDBSecret (const String &secret)
bool isRequiredVersion (const String &version)
bool isAutoRegistrationEnabled ()
Account * getAccount (uint32 accountID)
Account * getAccount (uint32 accountID, String &passwordStored)
Private Member Functions
Account * getAccount (String query, String &passwordStored)
Private Attributes
ManagedReference< LoginServer * > loginServer
String requiredVersion
bool autoRegistration
uint32 maxOnlineCharacters
String dbSecret
Detailed Description
Definition at line 25 of file AccountManager.h.
Constructor & Destructor Documentation
AccountManager::AccountManager (LoginServer * loginserv)
Definition at line 22 of file AccountManager.cpp.
References autoRegistration, ServerDatabase::instance(), loginServer, maxOnlineCharacters, requiredVersion, and ServerCore::truncateDatabases().
AccountManager::~AccountManager ()
Definition at line 45 of file AccountManager.cpp.
Member Function Documentation
Account * AccountManager::createAccount (const String & username, const String & password, String & passwordStored)
Definition at line 204 of file AccountManager.cpp.
References dbSecret, getAccount(), and ServerDatabase::instance().
Referenced by validateAccountCredentials().
Account * AccountManager::getAccount (uint32 accountID)
Definition at line 228 of file AccountManager.cpp.
Referenced by createAccount(), getAccount(), and validateAccountCredentials().
Account * AccountManager::getAccount (uint32 accountID, String & passwordStored)
Definition at line 234 of file AccountManager.cpp.
References getAccount().
Account * AccountManager::getAccount (String query, String & passwordStored) private
Definition at line 241 of file AccountManager.cpp.
References ServerDatabase::instance(), server::login::account::Account::setAccountID(), server::login::account::Account::setActive(), server::login::account::Account::setAdminLevel(), server::login::account::Account::setSalt(), server::login::account::Account::setStationID(), server::login::account::Account::setTimeCreated(), server::login::account::Account::setUsername(), and server::login::account::Account::updateFromDatabase().
uint32 server::login::account::AccountManager::getMaxOnlineCharacters () inline
Definition at line 57 of file AccountManager.h.
References maxOnlineCharacters.
bool server::login::account::AccountManager::isAutoRegistrationEnabled () inline
Definition at line 80 of file AccountManager.h.
References autoRegistration.
Referenced by validateAccountCredentials().
bool server::login::account::AccountManager::isRequiredVersion (const String & version) inline
Definition at line 73 of file AccountManager.h.
References requiredVersion.
Referenced by loginAccount().
void AccountManager::loginAccount (LoginClient * client, Message * packet)
Definition at line 49 of file AccountManager.cpp.
References server::login::LoginClient::getSession(), server::login::LoginClient::info(), ServerDatabase::instance(), isRequiredVersion(), loginServer, AccountVersionMessage::parse(), server::login::LoginClient::sendErrorMessage(), server::login::LoginClient::sendMessage(), server::login::LoginClient::setAccountID(), and validateAccountCredentials().
Referenced by server::login::LoginPacketHandler::handleLoginClientID().
void server::login::account::AccountManager::setAutoRegistrationEnabled (bool enabled) inline
Definition at line 65 of file AccountManager.h.
References autoRegistration.
void server::login::account::AccountManager::setDBSecret (const String & secret) inline
Definition at line 69 of file AccountManager.h.
References dbSecret.
void server::login::account::AccountManager::setMaxOnlineCharacters (uint32 maxonline) inline
Definition at line 53 of file AccountManager.h.
References maxOnlineCharacters.
void server::login::account::AccountManager::setRequiredVersion (const String & version) inline
Definition at line 61 of file AccountManager.h.
References requiredVersion.
void AccountManager::updateHash (const String & username, const String & password)
Definition at line 188 of file AccountManager.cpp.
References dbSecret, and ServerDatabase::instance().
Referenced by validateAccountCredentials().
Account * AccountManager::validateAccountCredentials (LoginClient * client, const String & username, const String & password)
Definition at line 100 of file AccountManager.cpp.
References createAccount(), dbSecret, getAccount(), server::login::account::Account::getBanExpires(), server::login::account::Account::getBanReason(), server::login::account::Account::getSalt(), server::login::account::Account::isActive(), isAutoRegistrationEnabled(), server::login::account::Account::isBanned(), server::login::LoginClient::sendErrorMessage(), and updateHash().
Referenced by loginAccount().
Member Data Documentation
bool server::login::account::AccountManager::autoRegistration private
Definition at line 30 of file AccountManager.h.
Referenced by AccountManager(), isAutoRegistrationEnabled(), and setAutoRegistrationEnabled().
String server::login::account::AccountManager::dbSecret private
Definition at line 34 of file AccountManager.h.
Referenced by createAccount(), setDBSecret(), updateHash(), and validateAccountCredentials().
ManagedReference<LoginServer*> server::login::account::AccountManager::loginServer private
Definition at line 26 of file AccountManager.h.
Referenced by AccountManager(), and loginAccount().
uint32 server::login::account::AccountManager::maxOnlineCharacters private
Definition at line 32 of file AccountManager.h.
Referenced by AccountManager(), getMaxOnlineCharacters(), and setMaxOnlineCharacters().
String server::login::account::AccountManager::requiredVersion private
Definition at line 28 of file AccountManager.h.
Referenced by AccountManager(), isRequiredVersion(), and setRequiredVersion().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/account/AccountManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/account/AccountManager.cpp