Core3: server::zone::objects::guild::GuildMemberInfo Class Reference
server::zone::objects::guild::GuildMemberInfo Class Reference
#include <GuildMemberInfo.h>
Public Member Functions
GuildMemberInfo ()
GuildMemberInfo (uint64 playerid)
GuildMemberInfo (const GuildMemberInfo &gmi)
int compareTo (const GuildMemberInfo &gmi) const
GuildMemberInfo & operator= (const GuildMemberInfo &gmi)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
uint64 getPlayerID ()
void setPlayerID (uint64 playerid)
String & getGuildTitle ()
void setGuildTitle (const String &title)
uint8 getPermissions ()
void setPermissions (uint8 permission)
void addPermission (uint8 permission)
void removePermission (uint8 permission)
void togglePermission (uint8 permission)
bool hasPermission (uint8 permission)
uint64 getDeclaredAllegiance ()
void setDeclaredAllegiance (uint64 playerid)
Private Attributes
uint64 playerID
String guildTitle
uint8 permissions
uint64 declaredAllegiance
Detailed Description
Definition at line 20 of file GuildMemberInfo.h.
Constructor & Destructor Documentation
server::zone::objects::guild::GuildMemberInfo::GuildMemberInfo () inline
Definition at line 27 of file GuildMemberInfo.h.
References declaredAllegiance, permissions, and playerID.
GuildMemberInfo::GuildMemberInfo (uint64 playerid)
Definition at line 11 of file GuildMemberInfo.cpp.
References declaredAllegiance, server::zone::objects::guild::GuildObject::PERMISSION_NONE, permissions, and playerID.
server::zone::objects::guild::GuildMemberInfo::GuildMemberInfo (const GuildMemberInfo & gmi) inline
Definition at line 37 of file GuildMemberInfo.h.
References declaredAllegiance, guildTitle, permissions, and playerID.
Member Function Documentation
void server::zone::objects::guild::GuildMemberInfo::addPermission (uint8 permission) inline
Definition at line 99 of file GuildMemberInfo.h.
References permissions.
int GuildMemberInfo::compareTo (const GuildMemberInfo & gmi) const
Definition at line 19 of file GuildMemberInfo.cpp.
References playerID.
uint64 server::zone::objects::guild::GuildMemberInfo::getDeclaredAllegiance () inline
Definition at line 115 of file GuildMemberInfo.h.
References declaredAllegiance.
String& server::zone::objects::guild::GuildMemberInfo::getGuildTitle () inline
Definition at line 83 of file GuildMemberInfo.h.
References guildTitle.
Referenced by GuildstatusCommand::doQueueCommand().
uint8 server::zone::objects::guild::GuildMemberInfo::getPermissions () inline
Definition at line 91 of file GuildMemberInfo.h.
References permissions.
uint64 server::zone::objects::guild::GuildMemberInfo::getPlayerID () inline
Definition at line 75 of file GuildMemberInfo.h.
References playerID.
Referenced by server::zone::managers::guild::GuildManagerImplementation::sendGuildMail(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberListTo().
bool server::zone::objects::guild::GuildMemberInfo::hasPermission (uint8 permission) inline
Definition at line 111 of file GuildMemberInfo.h.
References permissions.
Referenced by server::zone::objects::guild::GuildObjectImplementation::hasAcceptPermission(), server::zone::objects::guild::GuildObjectImplementation::hasDisbandPermission(), server::zone::objects::guild::GuildObjectImplementation::hasKickPermission(), server::zone::objects::guild::GuildObjectImplementation::hasMailPermission(), server::zone::objects::guild::GuildObjectImplementation::hasNamePermission(), server::zone::objects::guild::GuildObjectImplementation::hasSponsorPermission(), server::zone::objects::guild::GuildObjectImplementation::hasTitlePermission(), server::zone::objects::guild::GuildObjectImplementation::hasWarPermission(), and server::zone::managers::guild::GuildManagerImplementation::sendMemberPermissionsTo().
GuildMemberInfo & GuildMemberInfo::operator= (const GuildMemberInfo & gmi)
Definition at line 28 of file GuildMemberInfo.cpp.
References declaredAllegiance, guildTitle, permissions, and playerID.
bool server::zone::objects::guild::GuildMemberInfo::parseFromBinaryStream (ObjectInputStream * stream) inline
Definition at line 59 of file GuildMemberInfo.h.
References declaredAllegiance, guildTitle, permissions, and playerID.
void server::zone::objects::guild::GuildMemberInfo::removePermission (uint8 permission) inline
Definition at line 103 of file GuildMemberInfo.h.
References permissions.
void server::zone::objects::guild::GuildMemberInfo::setDeclaredAllegiance (uint64 playerid) inline
Definition at line 119 of file GuildMemberInfo.h.
References declaredAllegiance.
Referenced by server::zone::managers::guild::GuildManagerImplementation::createGuild().
void server::zone::objects::guild::GuildMemberInfo::setGuildTitle (const String & title) inline
Definition at line 87 of file GuildMemberInfo.h.
References guildTitle.
Referenced by server::zone::managers::guild::GuildManagerImplementation::setMemberTitle().
void server::zone::objects::guild::GuildMemberInfo::setPermissions (uint8 permission) inline
Definition at line 95 of file GuildMemberInfo.h.
References permissions.
Referenced by server::zone::managers::guild::GuildManagerImplementation::createGuild(), and server::zone::managers::guild::GuildManagerImplementation::transferLeadership().
void server::zone::objects::guild::GuildMemberInfo::setPlayerID (uint64 playerid) inline
Definition at line 79 of file GuildMemberInfo.h.
References playerID.
bool server::zone::objects::guild::GuildMemberInfo::toBinaryStream (ObjectOutputStream * stream) inline
Definition at line 50 of file GuildMemberInfo.h.
References declaredAllegiance, guildTitle, permissions, and playerID.
void server::zone::objects::guild::GuildMemberInfo::togglePermission (uint8 permission) inline
Definition at line 107 of file GuildMemberInfo.h.
References permissions.
Referenced by server::zone::managers::guild::GuildManagerImplementation::toggleGuildPermission().
Member Data Documentation
uint64 server::zone::objects::guild::GuildMemberInfo::declaredAllegiance private
Definition at line 24 of file GuildMemberInfo.h.
Referenced by getDeclaredAllegiance(), GuildMemberInfo(), operator=(), parseFromBinaryStream(), setDeclaredAllegiance(), and toBinaryStream().
String server::zone::objects::guild::GuildMemberInfo::guildTitle private
Definition at line 22 of file GuildMemberInfo.h.
Referenced by getGuildTitle(), GuildMemberInfo(), operator=(), parseFromBinaryStream(), setGuildTitle(), and toBinaryStream().
uint8 server::zone::objects::guild::GuildMemberInfo::permissions private
Definition at line 23 of file GuildMemberInfo.h.
Referenced by addPermission(), getPermissions(), GuildMemberInfo(), hasPermission(), operator=(), parseFromBinaryStream(), removePermission(), setPermissions(), toBinaryStream(), and togglePermission().
uint64 server::zone::objects::guild::GuildMemberInfo::playerID private
Definition at line 21 of file GuildMemberInfo.h.
Referenced by compareTo(), getPlayerID(), GuildMemberInfo(), operator=(), parseFromBinaryStream(), setPlayerID(), and toBinaryStream().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/guild/GuildMemberInfo.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/guild/GuildMemberInfo.cpp