Core3: server::zone::objects::player::sessions::CityRemoveMilitiaSession Class Reference
server::zone::objects::player::sessions::CityRemoveMilitiaSession Class Reference
#include <CityRemoveMilitiaSession.h>
Public Member Functions
CityRemoveMilitiaSession (CreatureObject *creature, CityRegion *city, unsigned long long militiaid, SceneObject *terminal=NULL)
unsigned long long getMilitiaID ()
int initializeSession ()
int cancelSession ()
int clearSession ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
CityRemoveMilitiaSession (DummyConstructorParameter *param)
virtual ~CityRemoveMilitiaSession ()
Friends
class CityRemoveMilitiaSessionHelper
Detailed Description
Definition at line 80 of file CityRemoveMilitiaSession.h.
Constructor & Destructor Documentation
CityRemoveMilitiaSession::CityRemoveMilitiaSession (CreatureObject * creature, CityRegion * city, unsigned long long militiaid, SceneObject * terminal = NULL)
Definition at line 21 of file CityRemoveMilitiaSession.cpp.
References server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation::_setStub().
CityRemoveMilitiaSession::CityRemoveMilitiaSession (DummyConstructorParameter * param) protected
Definition at line 28 of file CityRemoveMilitiaSession.cpp.
CityRemoveMilitiaSession::~CityRemoveMilitiaSession () protected virtual
Definition at line 32 of file CityRemoveMilitiaSession.cpp.
Member Function Documentation
DistributedObjectServant * CityRemoveMilitiaSession::_getImplementation ()
Definition at line 89 of file CityRemoveMilitiaSession.cpp.
Referenced by cancelSession(), clearSession(), getMilitiaID(), and initializeSession().
DistributedObjectServant * CityRemoveMilitiaSession::_getImplementationForRead ()
Definition at line 95 of file CityRemoveMilitiaSession.cpp.
void CityRemoveMilitiaSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 99 of file CityRemoveMilitiaSession.cpp.
int CityRemoveMilitiaSession::cancelSession ()
Definition at line 63 of file CityRemoveMilitiaSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
int CityRemoveMilitiaSession::clearSession ()
Definition at line 76 of file CityRemoveMilitiaSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
unsigned long long CityRemoveMilitiaSession::getMilitiaID ()
Definition at line 37 of file CityRemoveMilitiaSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation::getMilitiaID(), and RPC_GETMILITIAID__.
int CityRemoveMilitiaSession::initializeSession ()
Definition at line 50 of file CityRemoveMilitiaSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::CityRemoveMilitiaSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
Friends And Related Function Documentation
friend class CityRemoveMilitiaSessionHelper friend
Definition at line 102 of file CityRemoveMilitiaSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityRemoveMilitiaSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityRemoveMilitiaSession.cpp