Core3: server::zone::managers::loot::LootManagerImplementation Class Reference
server::zone::managers::loot::LootManagerImplementation Class Reference
#include <LootManager.h>
Public Member Functions
LootManagerImplementation (CraftingManager *craftman, ObjectManager *objMan, ZoneServer *server)
LootManagerImplementation (DummyConstructorParameter *param)
void initialize ()
TangibleObject * createLootObject (LootItemTemplate *templateObject, int level, bool maxCondition=false)
String getRandomLootableMod (unsigned int sceneObjectType)
int calculateLootCredits (int level)
bool createLoot (SceneObject *container, AiAgent *creature)
bool createLootFromCollection (SceneObject *container, LootGroupCollection *collection, int level)
bool createLoot (SceneObject *container, const String &lootGroup, int level=-1, bool maxCondition=false)
operator const LootManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< LootManager * > _this
Protected Member Functions
virtual ~LootManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Member Functions
bool loadConfigFile ()
bool loadConfigData ()
void loadDefaultConfig ()
void setInitialObjectStats (LootItemTemplate *templateObject, CraftingValues *craftingValues, TangibleObject *prototype)
void setSkillMods (TangibleObject *object, LootItemTemplate *templateObject, int level, float excMod)
void setCustomObjectName (TangibleObject *object, LootItemTemplate *templateObject)
void setSockets (TangibleObject *object, CraftingValues *craftingValues)
void addRandomDots (TangibleObject *object, LootItemTemplate *templateObject, int level, float excMod)
void addStaticDots (TangibleObject *object, LootItemTemplate *templateObject, int level)
float calculateDotValue (float min, float max, float level)
void addConditionDamage (TangibleObject *loot, CraftingValues *craftingValues)
void loadLootableMods (LuaObject *modTable, SortedVector< String > *mods)
Private Attributes
ManagedReference
< CraftingManager * > craftingManager
Reference< Lua * > lua
ManagedReference< ZoneServer * > zoneServer
Reference< ObjectManager * > objectManager
Reference< LootGroupMap * > lootGroupMap
float yellowChance
float yellowModifier
float exceptionalChance
float exceptionalModifier
float legendaryChance
float legendaryModifier
float skillModChance
SortedVector< int > randomDotAttribute
SortedVector< int > randomDotStrength
SortedVector< int > randomDotDuration
SortedVector< int > randomDotPotency
SortedVector< int > randomDotUses
SortedVector< String > lootableArmorAttachmentMods
SortedVector< String > lootableClothingAttachmentMods
SortedVector< String > lootableArmorMods
SortedVector< String > lootableClothingMods
SortedVector< String > lootableOneHandedMeleeMods
SortedVector< String > lootableTwoHandedMeleeMods
SortedVector< String > lootableUnarmedMods
SortedVector< String > lootablePistolMods
SortedVector< String > lootableRifleMods
SortedVector< String > lootableCarbineMods
SortedVector< String > lootablePolearmMods
SortedVector< String > lootableHeavyWeaponMods
Friends
class LootManager
Detailed Description
Definition at line 176 of file LootManager.h.
Constructor & Destructor Documentation
LootManagerImplementation::LootManagerImplementation (CraftingManager * craftman, ObjectManager * objMan, ZoneServer * server)
Definition at line 261 of file LootManager.cpp.
References _initializeImplementation(), craftingManager, exceptionalChance, exceptionalModifier, legendaryChance, legendaryModifier, lootableArmorAttachmentMods, lootableArmorMods, lootableCarbineMods, lootableClothingAttachmentMods, lootableClothingMods, lootableHeavyWeaponMods, lootableOneHandedMeleeMods, lootablePistolMods, lootablePolearmMods, lootableRifleMods, lootableTwoHandedMeleeMods, lootableUnarmedMods, lootGroupMap, objectManager, skillModChance, and zoneServer.
LootManagerImplementation::LootManagerImplementation (DummyConstructorParameter * param)
Definition at line 147 of file LootManager.cpp.
References _initializeImplementation().
LootManagerImplementation::~LootManagerImplementation () protected virtual
Definition at line 152 of file LootManager.cpp.
Member Function Documentation
DistributedObjectStub * LootManagerImplementation::_getStub ()
Definition at line 172 of file LootManager.cpp.
References _this.
void LootManagerImplementation::_initializeImplementation () protected
Definition at line 159 of file LootManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by LootManagerImplementation().
void LootManagerImplementation::_serializationHelperMethod () protected
Definition at line 208 of file LootManager.cpp.
Referenced by _initializeImplementation().
void LootManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 167 of file LootManager.cpp.
References _this.
Referenced by server::zone::managers::loot::LootManager::LootManager().
void LootManagerImplementation::addConditionDamage (TangibleObject * loot, CraftingValues * craftingValues) private
Definition at line 425 of file LootManagerImplementation.cpp.
References server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMinValue(), server::zone::objects::scene::SceneObject::isArmorObject(), server::zone::objects::scene::SceneObject::isWeaponObject(), and server::zone::objects::tangible::TangibleObject::setConditionDamage().
Referenced by createLootObject().
void LootManagerImplementation::addRandomDots (TangibleObject * object, LootItemTemplate * templateObject, int level, float excMod) private
Definition at line 723 of file LootManagerImplementation.cpp.
References calculateDotValue(), LootItemTemplate::getRandomDotChance(), server::zone::objects::scene::SceneObject::isWeaponObject(), randomDotAttribute, randomDotDuration, randomDotPotency, randomDotStrength, randomDotUses, OptionBitmask::YELLOW, yellowChance, and yellowModifier.
Referenced by createLootObject().
void LootManagerImplementation::addStaticDots (TangibleObject * object, LootItemTemplate * templateObject, int level) private
Definition at line 652 of file LootManagerImplementation.cpp.
References calculateDotValue(), LootItemTemplate::getStaticDotChance(), LootItemTemplate::getStaticDotType(), LootItemTemplate::getStaticDotValues(), and server::zone::objects::scene::SceneObject::isWeaponObject().
Referenced by createLootObject().
float LootManagerImplementation::calculateDotValue (float min, float max, float level) private
Definition at line 854 of file LootManagerImplementation.cpp.
Referenced by addRandomDots(), and addStaticDots().
int LootManagerImplementation::calculateLootCredits (int level)
Definition at line 230 of file LootManagerImplementation.cpp.
Referenced by server::zone::managers::loot::LootManager::calculateLootCredits().
bool LootManagerImplementation::createLoot (SceneObject * container, AiAgent * creature)
Definition at line 574 of file LootManagerImplementation.cpp.
References createLootFromCollection(), server::zone::objects::tangible::TangibleObject::getLevel(), and server::zone::objects::creature::AiAgent::getLootGroups().
Referenced by server::zone::managers::loot::LootManager::createLoot(), and createLootFromCollection().
bool LootManagerImplementation::createLoot (SceneObject * container, const String & lootGroup, int level = -1, bool maxCondition = false)
Definition at line 622 of file LootManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::broadcastObject(), createLootObject(), lootGroupMap, and server::zone::objects::scene::SceneObject::transferObject().
bool LootManagerImplementation::createLootFromCollection (SceneObject * container, LootGroupCollection * collection, int level)
Definition at line 583 of file LootManagerImplementation.cpp.
References LootGroupCollection::count(), LootGroups::count(), createLoot(), LootGroupCollection::get(), LootGroups::get(), LootGroupCollectionEntry::getLootChance(), LootGroupEntry::getLootChance(), LootGroupEntry::getLootGroupName(), and LootGroupCollectionEntry::getLootGroups().
Referenced by createLoot(), and server::zone::managers::loot::LootManager::createLootFromCollection().
TangibleObject * LootManagerImplementation::createLootObject (LootItemTemplate * templateObject, int level, bool maxCondition = false)
Definition at line 239 of file LootManagerImplementation.cpp.
References addConditionDamage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::addExperimentalProperty(), addRandomDots(), addStaticDots(), craftingManager, exceptionalChance, exceptionalModifier, LootItemTemplate::getCraftingValuesCopy(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentValue(), LootItemTemplate::getDirectObjectTemplate(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitleSize(), LootItemTemplate::getJunkDealerTypeNeeded(), LootItemTemplate::getJunkMaxValue(), LootItemTemplate::getJunkMinValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMinValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::hasProperty(), legendaryChance, legendaryModifier, server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::recalculateValues(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentValue(), setCustomObjectName(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setHidden(), setInitialObjectStats(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMinValue(), setSkillMods(), setSockets(), OptionBitmask::YELLOW, yellowChance, yellowModifier, and zoneServer.
Referenced by createLoot(), and server::zone::managers::loot::LootManager::createLootObject().
void LootManagerImplementation::finalize () protected
Definition at line 156 of file LootManager.cpp.
String LootManagerImplementation::getRandomLootableMod (unsigned int sceneObjectType)
Definition at line 508 of file LootManagerImplementation.cpp.
References SceneObjectType::ARMARMOR, SceneObjectType::ARMOR, SceneObjectType::ARMORATTACHMENT, SceneObjectType::BANDOLIER, SceneObjectType::BELT, SceneObjectType::BODYARMOR, SceneObjectType::BODYSUIT, SceneObjectType::BRACELET, SceneObjectType::CAPE, SceneObjectType::CARBINE, SceneObjectType::CLOAK, SceneObjectType::CLOTHING, SceneObjectType::CLOTHINGATTACHMENT, SceneObjectType::DRESS, SceneObjectType::EARRING, SceneObjectType::EYEWEAR, SceneObjectType::FOOTARMOR, SceneObjectType::FOOTWEAR, SceneObjectType::HANDARMOR, SceneObjectType::HANDWEAR, SceneObjectType::HEADARMOR, SceneObjectType::HEADWEAR, SceneObjectType::JACKET, SceneObjectType::JEWELRY, SceneObjectType::LEGARMOR, lootableArmorAttachmentMods, lootableArmorMods, lootableCarbineMods, lootableClothingAttachmentMods, lootableClothingMods, lootableHeavyWeaponMods, lootableOneHandedMeleeMods, lootablePistolMods, lootablePolearmMods, lootableRifleMods, lootableTwoHandedMeleeMods, lootableUnarmedMods, SceneObjectType::MELEEWEAPON, SceneObjectType::MISCARMOR, SceneObjectType::MISCCLOTHING, SceneObjectType::NECKLACE, SceneObjectType::ONEHANDMELEEWEAPON, SceneObjectType::PANTS, SceneObjectType::PISTOL, SceneObjectType::POLEARM, SceneObjectType::RIFLE, SceneObjectType::RING, SceneObjectType::ROBE, SceneObjectType::SHIRT, SceneObjectType::SKIRT, SceneObjectType::SPECIALHEAVYWEAPON, SceneObjectType::TWOHANDMELEEWEAPON, SceneObjectType::VEST, SceneObjectType::WEARABLECONTAINER, and SceneObjectType::WOOKIEGARB.
Referenced by server::zone::managers::loot::LootManager::getRandomLootableMod(), and setSkillMods().
void LootManagerImplementation::initialize ()
Definition at line 22 of file LootManagerImplementation.cpp.
References loadConfigData(), loadDefaultConfig(), lootableArmorAttachmentMods, lootableArmorMods, lootableCarbineMods, lootableClothingAttachmentMods, lootableClothingMods, lootableHeavyWeaponMods, lootableOneHandedMeleeMods, lootablePistolMods, lootablePolearmMods, lootableRifleMods, lootableTwoHandedMeleeMods, lootableUnarmedMods, lootGroupMap, and lua.
Referenced by server::zone::managers::loot::LootManager::initialize().
bool LootManagerImplementation::loadConfigData () private
Definition at line 60 of file LootManagerImplementation.cpp.
References exceptionalChance, exceptionalModifier, legendaryChance, legendaryModifier, loadConfigFile(), loadLootableMods(), lootableArmorAttachmentMods, lootableArmorMods, lootableCarbineMods, lootableClothingAttachmentMods, lootableClothingMods, lootableHeavyWeaponMods, lootableOneHandedMeleeMods, lootablePistolMods, lootablePolearmMods, lootableRifleMods, lootableTwoHandedMeleeMods, lootableUnarmedMods, lua, randomDotAttribute, randomDotDuration, randomDotPotency, randomDotStrength, randomDotUses, skillModChance, yellowChance, and yellowModifier.
Referenced by initialize().
bool LootManagerImplementation::loadConfigFile () private
Definition at line 56 of file LootManagerImplementation.cpp.
References lua.
Referenced by loadConfigData().
void LootManagerImplementation::loadDefaultConfig () private
Definition at line 174 of file LootManagerImplementation.cpp.
Referenced by initialize().
void LootManagerImplementation::loadLootableMods (LuaObject * modTable, SortedVector< String > * mods) private
Definition at line 160 of file LootManagerImplementation.cpp.
Referenced by loadConfigData().
void LootManagerImplementation::lock (bool doLock = true) protected
Definition at line 180 of file LootManager.cpp.
References _this.
void LootManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 184 of file LootManager.cpp.
References _this.
LootManagerImplementation::operator const LootManager * ()
Definition at line 176 of file LootManager.cpp.
void LootManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 215 of file LootManager.cpp.
References readObjectMember().
bool LootManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 234 of file LootManager.cpp.
Referenced by readObject().
void LootManagerImplementation::rlock (bool doLock = true) protected
Definition at line 188 of file LootManager.cpp.
References _this.
void LootManagerImplementation::runlock (bool doLock = true) protected
Definition at line 204 of file LootManager.cpp.
References _this.
void LootManagerImplementation::setCustomObjectName (TangibleObject * object, LootItemTemplate * templateObject) private
Definition at line 216 of file LootManagerImplementation.cpp.
References LootItemTemplate::getCustomObjectName().
Referenced by createLootObject().
void LootManagerImplementation::setInitialObjectStats (LootItemTemplate * templateObject, CraftingValues * craftingValues, TangibleObject * prototype) private
Definition at line 178 of file LootManagerImplementation.cpp.
References server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::addExperimentalProperty(), LootItemTemplate::getCustomizationStringNames(), LootItemTemplate::getCustomizationValues(), SharedTangibleObjectTemplate::getExperimentalGroupTitles(), SharedTangibleObjectTemplate::getExperimentalMax(), SharedTangibleObjectTemplate::getExperimentalMin(), SharedTangibleObjectTemplate::getExperimentalPrecision(), SharedTangibleObjectTemplate::getExperimentalSubGroupTitles(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::hasProperty(), server::zone::objects::tangible::TangibleObject::setCustomizationVariable(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setHidden().
Referenced by createLootObject().
void LootManagerImplementation::setSkillMods (TangibleObject * object, LootItemTemplate * templateObject, int level, float excMod) private
Definition at line 442 of file LootManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getGameObjectType(), getRandomLootableMod(), LootItemTemplate::getSkillMods(), server::zone::objects::scene::SceneObject::isWeaponObject(), server::zone::objects::scene::SceneObject::isWearableObject(), skillModChance, and OptionBitmask::YELLOW.
Referenced by createLootObject().
void LootManagerImplementation::setSockets (TangibleObject * object, CraftingValues * craftingValues) private
Definition at line 566 of file LootManagerImplementation.cpp.
References server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::hasProperty(), and server::zone::objects::scene::SceneObject::isWearableObject().
Referenced by createLootObject().
void LootManagerImplementation::unlock (bool doLock = true) protected
Definition at line 200 of file LootManager.cpp.
References _this.
void LootManagerImplementation::wlock (bool doLock = true) protected
Definition at line 192 of file LootManager.cpp.
References _this.
void LootManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 196 of file LootManager.cpp.
References _this.
void LootManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 244 of file LootManager.cpp.
References writeObjectMembers().
int LootManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 251 of file LootManager.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class LootManager friend
Definition at line 314 of file LootManager.h.
Member Data Documentation
WeakReference<LootManager*> server::zone::managers::loot::LootManagerImplementation::_this
Definition at line 280 of file LootManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedReference<CraftingManager* > server::zone::managers::loot::LootManagerImplementation::craftingManager private
Definition at line 177 of file LootManager.h.
Referenced by createLootObject(), and LootManagerImplementation().
float server::zone::managers::loot::LootManagerImplementation::exceptionalChance private
Definition at line 191 of file LootManager.h.
Referenced by createLootObject(), loadConfigData(), and LootManagerImplementation().
float server::zone::managers::loot::LootManagerImplementation::exceptionalModifier private
Definition at line 193 of file LootManager.h.
Referenced by createLootObject(), loadConfigData(), and LootManagerImplementation().
float server::zone::managers::loot::LootManagerImplementation::legendaryChance private
Definition at line 195 of file LootManager.h.
Referenced by createLootObject(), loadConfigData(), and LootManagerImplementation().
float server::zone::managers::loot::LootManagerImplementation::legendaryModifier private
Definition at line 197 of file LootManager.h.
Referenced by createLootObject(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootableArmorAttachmentMods private
Definition at line 211 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootableArmorMods private
Definition at line 215 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootableCarbineMods private
Definition at line 229 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootableClothingAttachmentMods private
Definition at line 213 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootableClothingMods private
Definition at line 217 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootableHeavyWeaponMods private
Definition at line 233 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootableOneHandedMeleeMods private
Definition at line 219 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootablePistolMods private
Definition at line 225 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootablePolearmMods private
Definition at line 231 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootableRifleMods private
Definition at line 227 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootableTwoHandedMeleeMods private
Definition at line 221 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
SortedVector<String> server::zone::managers::loot::LootManagerImplementation::lootableUnarmedMods private
Definition at line 223 of file LootManager.h.
Referenced by getRandomLootableMod(), initialize(), loadConfigData(), and LootManagerImplementation().
Reference<LootGroupMap* > server::zone::managers::loot::LootManagerImplementation::lootGroupMap private
Definition at line 185 of file LootManager.h.
Referenced by createLoot(), initialize(), and LootManagerImplementation().
Reference<Lua* > server::zone::managers::loot::LootManagerImplementation::lua private
Definition at line 179 of file LootManager.h.
Referenced by initialize(), loadConfigData(), and loadConfigFile().
Reference<ObjectManager* > server::zone::managers::loot::LootManagerImplementation::objectManager private
Definition at line 183 of file LootManager.h.
Referenced by LootManagerImplementation().
SortedVector<int> server::zone::managers::loot::LootManagerImplementation::randomDotAttribute private
Definition at line 201 of file LootManager.h.
Referenced by addRandomDots(), and loadConfigData().
SortedVector<int> server::zone::managers::loot::LootManagerImplementation::randomDotDuration private
Definition at line 205 of file LootManager.h.
Referenced by addRandomDots(), and loadConfigData().
SortedVector<int> server::zone::managers::loot::LootManagerImplementation::randomDotPotency private
Definition at line 207 of file LootManager.h.
Referenced by addRandomDots(), and loadConfigData().
SortedVector<int> server::zone::managers::loot::LootManagerImplementation::randomDotStrength private
Definition at line 203 of file LootManager.h.
Referenced by addRandomDots(), and loadConfigData().
SortedVector<int> server::zone::managers::loot::LootManagerImplementation::randomDotUses private
Definition at line 209 of file LootManager.h.
Referenced by addRandomDots(), and loadConfigData().
float server::zone::managers::loot::LootManagerImplementation::skillModChance private
Definition at line 199 of file LootManager.h.
Referenced by loadConfigData(), LootManagerImplementation(), and setSkillMods().
float server::zone::managers::loot::LootManagerImplementation::yellowChance private
Definition at line 187 of file LootManager.h.
Referenced by addRandomDots(), createLootObject(), and loadConfigData().
float server::zone::managers::loot::LootManagerImplementation::yellowModifier private
Definition at line 189 of file LootManager.h.
Referenced by addRandomDots(), createLootObject(), and loadConfigData().
ManagedReference<ZoneServer* > server::zone::managers::loot::LootManagerImplementation::zoneServer private
Definition at line 181 of file LootManager.h.
Referenced by createLootObject(), and LootManagerImplementation().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/LootManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/LootManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/LootManagerImplementation.cpp