Core3: ChatOnLeaveRoom Class Reference
ChatOnLeaveRoom Class Reference
#include <ChatOnLeaveRoom.h>
Public Member Functions
ChatOnLeaveRoom (ChatRoom *room, CreatureObject *player)
Detailed Description
Definition at line 54 of file ChatOnLeaveRoom.h.
Constructor & Destructor Documentation
ChatOnLeaveRoom::ChatOnLeaveRoom (ChatRoom * room, CreatureObject * player) inline
Definition at line 57 of file ChatOnLeaveRoom.h.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::chat::room::ChatRoom::getGalaxyName(), and server::chat::room::ChatRoom::getRoomID().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/chat/ChatOnLeaveRoom.h