Core3: server::zone::objects::player::sessions::StructureStatusSession Class Reference
server::zone::objects::player::sessions::StructureStatusSession Class Reference
#include <StructureStatusSession.h>
Public Member Functions
StructureStatusSession (StructureObject *structure)
int initializeSession ()
int updateStatus ()
int cancelSession ()
int clearSession ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
StructureStatusSession (DummyConstructorParameter *param)
virtual ~StructureStatusSession ()
Friends
class StructureStatusSessionHelper
Detailed Description
Definition at line 24 of file StructureStatusSession.h.
Constructor & Destructor Documentation
StructureStatusSession::StructureStatusSession (StructureObject * structure)
Definition at line 13 of file StructureStatusSession.cpp.
References server::zone::objects::player::sessions::StructureStatusSessionImplementation::_setStub().
StructureStatusSession::StructureStatusSession (DummyConstructorParameter * param) protected
Definition at line 20 of file StructureStatusSession.cpp.
StructureStatusSession::~StructureStatusSession () protected virtual
Definition at line 24 of file StructureStatusSession.cpp.
Member Function Documentation
DistributedObjectServant * StructureStatusSession::_getImplementation ()
Definition at line 81 of file StructureStatusSession.cpp.
Referenced by cancelSession(), clearSession(), initializeSession(), and updateStatus().
DistributedObjectServant * StructureStatusSession::_getImplementationForRead ()
Definition at line 87 of file StructureStatusSession.cpp.
void StructureStatusSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 91 of file StructureStatusSession.cpp.
int StructureStatusSession::cancelSession ()
Definition at line 55 of file StructureStatusSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::StructureStatusSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
int StructureStatusSession::clearSession ()
Definition at line 68 of file StructureStatusSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::StructureStatusSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
int StructureStatusSession::initializeSession ()
Definition at line 29 of file StructureStatusSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::StructureStatusSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
int StructureStatusSession::updateStatus ()
Definition at line 42 of file StructureStatusSession.cpp.
References _getImplementation(), RPC_UPDATESTATUS__, and server::zone::objects::player::sessions::StructureStatusSessionImplementation::updateStatus().
Friends And Related Function Documentation
friend class StructureStatusSessionHelper friend
Definition at line 46 of file StructureStatusSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureStatusSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/StructureStatusSession.cpp