Core3: server::zone::managers::crafting::labratories::SharedLabratory Class Reference
server::zone::managers::crafting::labratories::SharedLabratory Class Reference abstract
#include <SharedLabratory.h>
Public Member Functions
SharedLabratory ()
virtual ~SharedLabratory ()
virtual void setInitialCraftingValues (TangibleObject *prototype, ManufactureSchematic *manufactureSchematic, int assemblySuccess)=0
virtual void experimentRow (CraftingValues *craftingValues, int rowEffected, int pointsAttempted, float failure, int experimentationResult)=0
virtual void initialize (ZoneServer *server)
virtual float getWeightedValue (ManufactureSchematic *manufactureSchematic, int type)
virtual bool allowFactoryRun (ManufactureSchematic *manufactureSchematic)
Protected Member Functions
float calculateExperimentationValueModifier (int experimentationResult, int pointsAttempted)
float calculateAssemblyValueModifier (int assemblyResult)
float getAssemblyPercentage (float value)
Protected Attributes
ManagedReference< ZoneServer * > zoneServer
Detailed Description
Definition at line 28 of file SharedLabratory.h.
Constructor & Destructor Documentation
SharedLabratory::SharedLabratory ()
Definition at line 48 of file SharedLabratory.cpp.
SharedLabratory::~SharedLabratory () virtual
Definition at line 51 of file SharedLabratory.cpp.
Member Function Documentation
bool SharedLabratory::allowFactoryRun (ManufactureSchematic * manufactureSchematic) virtual
Reimplemented in server::zone::managers::crafting::labratories::GeneticLabratory, and server::zone::managers::crafting::labratories::ResourceLabratory.
Definition at line 54 of file SharedLabratory.cpp.
References server::zone::objects::manufactureschematic::ManufactureSchematic::allowFactoryRun().
Referenced by server::zone::managers::crafting::CraftingManagerImplementation::allowManufactureSchematic().
float SharedLabratory::calculateAssemblyValueModifier (int assemblyResult) protected
Definition at line 100 of file SharedLabratory.cpp.
References server::zone::managers::crafting::CraftingManager::AMAZINGSUCCESS.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::setInitialCraftingValues(), and server::zone::managers::crafting::labratories::GeneticLabratory::setInitialCraftingValues().
float SharedLabratory::calculateExperimentationValueModifier (int experimentationResult, int pointsAttempted) protected
Definition at line 62 of file SharedLabratory.cpp.
References server::zone::managers::crafting::CraftingManager::AMAZINGSUCCESS, server::zone::managers::crafting::CraftingManager::BARELYSUCCESSFUL, server::zone::managers::crafting::CraftingManager::CRITICALFAILURE, server::zone::managers::crafting::CraftingManager::GOODSUCCESS, server::zone::managers::crafting::CraftingManager::GREATSUCCESS, server::zone::managers::crafting::CraftingManager::MARGINALSUCCESS, server::zone::managers::crafting::CraftingManager::MODERATESUCCESS, server::zone::managers::crafting::CraftingManager::OK, and server::zone::managers::crafting::CraftingManager::SUCCESS.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::experimentRow(), and server::zone::managers::crafting::labratories::GeneticLabratory::experimentRow().
virtual void server::zone::managers::crafting::labratories::SharedLabratory::experimentRow (CraftingValues * craftingValues, int rowEffected, int pointsAttempted, float failure, int experimentationResult) pure virtual
Implemented in server::zone::managers::crafting::labratories::GeneticLabratory, and server::zone::managers::crafting::labratories::ResourceLabratory.
Referenced by server::zone::managers::crafting::CraftingManagerImplementation::experimentRow().
float SharedLabratory::getAssemblyPercentage (float value) protected
Definition at line 108 of file SharedLabratory.cpp.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::setInitialCraftingValues(), and server::zone::managers::crafting::labratories::GeneticLabratory::setInitialCraftingValues().
float SharedLabratory::getWeightedValue (ManufactureSchematic * manufactureSchematic, int type) virtual
If resource slot, continue
Definition at line 113 of file SharedLabratory.cpp.
References ResourceSlot::getCurrentSpawn(), server::zone::objects::manufactureschematic::ManufactureSchematic::getDraftSchematic(), server::zone::objects::draftschematic::DraftSchematic::getDraftSlot(), server::zone::objects::manufactureschematic::ManufactureSchematic::getSlot(), and server::zone::objects::manufactureschematic::ManufactureSchematic::getSlotCount().
Referenced by server::zone::managers::crafting::CraftingManagerImplementation::calculateExperimentationFailureRate(), and server::zone::managers::crafting::labratories::ResourceLabratory::setInitialCraftingValues().
void SharedLabratory::initialize (ZoneServer * server) virtual
Reimplemented in server::zone::managers::crafting::labratories::GeneticLabratory, and server::zone::managers::crafting::labratories::ResourceLabratory.
Definition at line 58 of file SharedLabratory.cpp.
References zoneServer.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::initialize(), and server::zone::managers::crafting::labratories::GeneticLabratory::initialize().
virtual void server::zone::managers::crafting::labratories::SharedLabratory::setInitialCraftingValues (TangibleObject * prototype, ManufactureSchematic * manufactureSchematic, int assemblySuccess) pure virtual
Implemented in server::zone::managers::crafting::labratories::GeneticLabratory, and server::zone::managers::crafting::labratories::ResourceLabratory.
Referenced by server::zone::managers::crafting::CraftingManagerImplementation::setInitialCraftingValues().
Member Data Documentation
ManagedReference<ZoneServer*> server::zone::managers::crafting::labratories::SharedLabratory::zoneServer protected
Definition at line 40 of file SharedLabratory.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/labratories/SharedLabratory.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/labratories/SharedLabratory.cpp