Core3: ResourceSpawner Class Reference
ResourceSpawner Class Reference
#include <ResourceSpawner.h>
Public Member Functions
ResourceSpawner (ManagedReference< ZoneServer * > serv, ZoneProcessServer *impl, ObjectManager *objMan)
~ResourceSpawner ()
void init ()
void initializeMinimumPool (LuaObject includes, const String &excludes)
void initializeFixedPool (LuaObject includes, const String &excludes)
void initializeRandomPool (LuaObject includes, const String &excludes, const int size)
void initializeNativePool (const String &includes, const String &excludes)
void addZone (const String &zoneName)
void removeZone (const String &zoneName)
void addJtlResource (const String &resourceName)
void addRecycledResource (const String &resourceName)
void setSpawningParameters (bool loadFromScript, const int dur, const float throt, const int override, const int spawnquantity)
void spawnScriptResources ()
bool writeAllSpawnsToScript ()
void start ()
void shiftResources ()
ResourceSpawn * createResourceSpawn (const String &type, const String &zonerestriction="")
ResourceSpawn * createResourceSpawn (const String &type, const Vector< String > &excludes, const String &zonerestriction="")
ResourceSpawn * createResourceSpawn (const Vector< String > &includes, const Vector< String > &excludes=0, const String &zonerestriction="")
void despawn (ResourceSpawn *spawn)
ResourceSpawn * manualCreateResourceSpawn (const String &type)
ResourceSpawn * createRecycledResourceSpawn (ResourceTreeEntry *entry)
ResourceSpawn * getRecycledVersion (ResourceSpawn *resource)
bool isRecycledResource (ResourceSpawn *resource)
int sendResourceRecycleType (ResourceSpawn *resource)
void sendResourceListForSurvey (CreatureObject *player, const int toolType, const String &surveyType)
void sendSurvey (CreatureObject *player, const String &resname)
void sendSample (CreatureObject *player, const String &resname, const String &sampleAnimation)
void sendSampleResults (CreatureObject *player, const float density, const String &resname)
ResourceContainer * harvestResource (CreatureObject *player, const String &type, const int quantity)
void harvestResource (CreatureObject *player, ResourceSpawn *resourceSpawn, int quantity)
void addResourceToPlayerInventory (CreatureObject *player, ResourceSpawn *resourceSpawn, int unitsExtracted)
ResourceSpawn * getCurrentSpawn (const String &restype, const String &zoneName)
ResourceSpawn * getFromRandomPool (const String &type)
void addNodeToListBox (SuiListBox *sui, const String &nodeName)
String addParentNodeToListBox (SuiListBox *sui, const String &currentNode)
ResourceMap * getResourceMap ()
void listResourcesForPlanetOnScreen (CreatureObject *creature, const String &planet)
String healthCheck ()
String dumpResources ()
Private Member Functions
void loadResourceSpawns ()
String makeResourceName (bool isOrganic)
int randomizeValue (int min, int max)
long getRandomExpirationTime (ResourceTreeEntry *resourceEntry)
long getRandomUnixTimestamp (int min, int max)
Vector< String > & getJtlResources ()
Vector< String > & getRecycledResources ()
Vector< String > & getActiveResourceZones ()
Private Attributes
ManagedReference< ZoneServer * > server
ManagedReference
< ZoneProcessServer * > processor
NameManager * nameManager
ObjectManager * objectManager
ResourceTree * resourceTree
ObjectDatabaseManager * databaseManager
ResourceMap * resourceMap
Vector< String > jtlResources
Vector< String > recycledResources
Vector< String > activeResourceZones
MinimumPool * minimumPool
FixedPool * fixedPool
RandomPool * randomPool
NativePool * nativePool
ManualPool * manualPool
bool scriptLoading
int shiftDuration
int lowerGateOverride
int maxSpawnAmount
float spawnThrottling
int samplingMultiplier
Friends
class ResourceTree
class ResourceManager
class NativePool
Detailed Description
The ResourceSpawner class represents all the functions related to ResourceSpawns Including spawning, despawning rules,
Definition at line 89 of file ResourceSpawner.h.
Constructor & Destructor Documentation
ResourceSpawner::ResourceSpawner (ManagedReference< ZoneServer * > serv, ZoneProcessServer * impl, ObjectManager * objMan)
Definition at line 62 of file ResourceSpawner.cpp.
References databaseManager, fixedPool, manualPool, minimumPool, nameManager, nativePool, NativePool, objectManager, processor, randomPool, samplingMultiplier, and server.
ResourceSpawner::~ResourceSpawner ()
Definition at line 82 of file ResourceSpawner.cpp.
References activeResourceZones, fixedPool, manualPool, minimumPool, nativePool, randomPool, resourceMap, and resourceTree.
Member Function Documentation
void ResourceSpawner::addJtlResource (const String & resourceName)
Definition at line 132 of file ResourceSpawner.cpp.
References jtlResources.
void ResourceSpawner::addNodeToListBox (SuiListBox * sui, const String & nodeName)
Definition at line 1116 of file ResourceSpawner.cpp.
References ResourceTreeNode::addToSuiListBox(), ResourceMap::addToSuiListBox(), ResourceMap::containsType(), ResourceTreeNode::findNode(), ResourceTree::getBaseNode(), resourceMap, and resourceTree.
String ResourceSpawner::addParentNodeToListBox (SuiListBox * sui, const String & currentNode)
Definition at line 1135 of file ResourceSpawner.cpp.
References ResourceTreeNode::addToSuiListBox(), ResourceMap::addToSuiListBox(), ResourceTreeNode::find(), ResourceTreeNode::findNode(), ResourceTree::getBaseNode(), ResourceTreeEntry::getFinalClass(), ResourceTreeEntry::getMyNode(), ResourceTreeNode::getName(), ResourceTreeNode::getParentNode(), resourceMap, and resourceTree.
void ResourceSpawner::addRecycledResource (const String & resourceName)
Definition at line 136 of file ResourceSpawner.cpp.
References recycledResources.
void ResourceSpawner::addResourceToPlayerInventory (CreatureObject * player, ResourceSpawn * resourceSpawn, int unitsExtracted)
Definition at line 1020 of file ResourceSpawner.cpp.
References server::zone::objects::resource::ResourceSpawn::createResource(), server::zone::objects::resource::ResourceSpawn::getName(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setPosture(), and CreaturePosture::UPRIGHT.
Referenced by harvestResource(), and sendSampleResults().
void ResourceSpawner::addZone (const String & zoneName)
Definition at line 122 of file ResourceSpawner.cpp.
References activeResourceZones, NativePool::addZone(), and nativePool.
ResourceSpawn * ResourceSpawner::createRecycledResourceSpawn (ResourceTreeEntry * entry)
Definition at line 386 of file ResourceSpawner.cpp.
References ResourceMap::add(), server::zone::objects::resource::ResourceSpawn::addAttribute(), server::zone::objects::resource::ResourceSpawn::addClass(), server::zone::objects::resource::ResourceSpawn::addStfClass(), server::zone::managers::object::ObjectManager::createObject(), ResourceTreeEntry::getAttribute(), ResourceTreeEntry::getAttributeCount(), ResourceTreeEntry::getClass(), ResourceTreeEntry::getClassCount(), ResourceTreeEntry::getContainerCRC(), ResourceTreeEntry::getFinalClass(), ResourceAttribute::getName(), server::zone::objects::resource::ResourceSpawn::getName(), ResourceTreeEntry::getStfClass(), ResourceTreeEntry::getStfClassCount(), ResourceTreeEntry::getSurveyToolType(), ResourceTreeEntry::getType(), ResourceTreeEntry::getZoneRestriction(), server::zone::objects::resource::ResourceSpawn::isType(), objectManager, resourceMap, server::zone::objects::resource::ResourceSpawn::setContainerCRC(), server::zone::objects::resource::ResourceSpawn::setIsEnergy(), server::zone::objects::resource::ResourceSpawn::setName(), server::zone::objects::resource::ResourceSpawn::setSurveyToolType(), server::zone::objects::resource::ResourceSpawn::setType(), and server::zone::objects::resource::ResourceSpawn::setZoneRestriction().
Referenced by getRecycledVersion().
ResourceSpawn * ResourceSpawner::createResourceSpawn (const String & type, const String & zonerestriction = "")
Definition at line 512 of file ResourceSpawner.cpp.
Referenced by createResourceSpawn(), manualCreateResourceSpawn(), MinimumPool::update(), FixedPool::update(), NativePool::update(), and RandomPool::update().
ResourceSpawn * ResourceSpawner::createResourceSpawn (const String & type, const Vector< String > & excludes, const String & zonerestriction = "")
Definition at line 436 of file ResourceSpawner.cpp.
References activeResourceZones, ResourceMap::add(), server::zone::managers::object::ObjectManager::createObject(), ResourceTreeEntry::getAttribute(), ResourceTreeEntry::getAttributeCount(), ResourceTreeEntry::getClass(), ResourceTreeEntry::getClassCount(), ResourceTreeEntry::getContainerCRC(), ResourceTree::getEntry(), ResourceAttribute::getIndex(), ResourceAttribute::getMaximum(), ResourceTreeEntry::getMaxpool(), ResourceAttribute::getMinimum(), ResourceTreeEntry::getMinpool(), ResourceAttribute::getName(), getRandomExpirationTime(), ResourceTreeEntry::getStfClass(), ResourceTreeEntry::getStfClassCount(), ResourceTreeEntry::getSurveyToolType(), ResourceTreeEntry::getType(), ResourceTreeEntry::getZoneRestriction(), ResourceTreeEntry::isJTL(), ResourceTreeEntry::isOrganic(), makeResourceName(), objectManager, randomizeValue(), resourceMap, and resourceTree.
ResourceSpawn * ResourceSpawner::createResourceSpawn (const Vector< String > & includes, const Vector< String > & excludes = 0, const String & zonerestriction = "")
Definition at line 519 of file ResourceSpawner.cpp.
References createResourceSpawn().
void ResourceSpawner::despawn (ResourceSpawn * spawn)
Definition at line 528 of file ResourceSpawner.cpp.
References server::zone::objects::resource::ResourceSpawn::getSpawnMapSize(), server::zone::objects::resource::ResourceSpawn::getSpawnMapZone(), ResourcePool::NOPOOL, ResourceMap::remove(), resourceMap, and server::zone::objects::resource::ResourceSpawn::setSpawnPool().
Referenced by loadResourceSpawns(), ManualPool::update(), MinimumPool::update(), FixedPool::update(), RandomPool::update(), and NativePool::update().
String ResourceSpawner::dumpResources () inline
Definition at line 185 of file ResourceSpawner.h.
Referenced by shiftResources().
Vector< String > & ResourceSpawner::getActiveResourceZones () private
Definition at line 595 of file ResourceSpawner.cpp.
References activeResourceZones.
Referenced by ResourceTree::setZoneRestriction().
ResourceSpawn * ResourceSpawner::getCurrentSpawn (const String & restype, const String & zoneName)
Definition at line 1092 of file ResourceSpawner.cpp.
References ResourceMap::getZoneResourceList(), and resourceMap.
ResourceSpawn * ResourceSpawner::getFromRandomPool (const String & type)
Definition at line 1112 of file ResourceSpawner.cpp.
References randomPool, and RandomPool::removeSpawn().
Referenced by MinimumPool::update().
Vector< String > & ResourceSpawner::getJtlResources () private
Definition at line 599 of file ResourceSpawner.cpp.
References jtlResources.
Referenced by ResourceTree::setJtl().
long ResourceSpawner::getRandomExpirationTime (ResourceTreeEntry * resourceEntry) private
Definition at line 576 of file ResourceSpawner.cpp.
References getRandomUnixTimestamp(), ResourceTreeEntry::isJTL(), and ResourceTreeEntry::isOrganic().
Referenced by createResourceSpawn().
long ResourceSpawner::getRandomUnixTimestamp (int min, int max) private
Definition at line 588 of file ResourceSpawner.cpp.
References shiftDuration.
Referenced by getRandomExpirationTime().
Vector< String > & ResourceSpawner::getRecycledResources () private
Definition at line 603 of file ResourceSpawner.cpp.
References recycledResources.
Referenced by ResourceTree::setRecycled().
ResourceSpawn * ResourceSpawner::getRecycledVersion (ResourceSpawn * resource)
Definition at line 616 of file ResourceSpawner.cpp.
References ResourceMap::containsType(), createRecycledResourceSpawn(), ResourceTree::getEntry(), ResourceTreeEntry::getFinalClass(), ResourceTreeEntry::getRecycleToolType(), server::zone::objects::resource::ResourceSpawn::getType(), server::zone::objects::resource::ResourceSpawn::isType(), server::zone::objects::resource::ResourceSpawn::isUnknownType(), resourceMap, and resourceTree.
ResourceMap* ResourceSpawner::getResourceMap () inline
Definition at line 177 of file ResourceSpawner.h.
ResourceContainer * ResourceSpawner::harvestResource (CreatureObject * player, const String & type, const int quantity)
Definition at line 1059 of file ResourceSpawner.cpp.
References server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), ResourceMap::getZoneResourceList(), resourceMap, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
void ResourceSpawner::harvestResource (CreatureObject * player, ResourceSpawn * resourceSpawn, int quantity)
Definition at line 1085 of file ResourceSpawner.cpp.
References addResourceToPlayerInventory(), server::zone::objects::resource::ResourceSpawn::extractResource(), server::zone::objects::scene::SceneObject::getZone(), and server::zone::Zone::getZoneName().
String ResourceSpawner::healthCheck ()
Definition at line 1205 of file ResourceSpawner.cpp.
References fixedPool, MinimumPool::healthCheck(), FixedPool::healthCheck(), ManualPool::healthCheck(), NativePool::healthCheck(), RandomPool::healthCheck(), manualPool, minimumPool, nativePool, and randomPool.
void ResourceSpawner::init ()
Definition at line 96 of file ResourceSpawner.cpp.
References resourceMap, resourceTree, and ResourceTree.
void ResourceSpawner::initializeFixedPool (LuaObject includes, const String & excludes)
Definition at line 107 of file ResourceSpawner.cpp.
References fixedPool, and FixedPool::initialize().
void ResourceSpawner::initializeMinimumPool (LuaObject includes, const String & excludes)
Definition at line 102 of file ResourceSpawner.cpp.
References MinimumPool::initialize(), and minimumPool.
void ResourceSpawner::initializeNativePool (const String & includes, const String & excludes)
Definition at line 117 of file ResourceSpawner.cpp.
References NativePool::initialize(), and nativePool.
void ResourceSpawner::initializeRandomPool (LuaObject includes, const String & excludes, const int size)
Definition at line 112 of file ResourceSpawner.cpp.
References RandomPool::initialize(), and randomPool.
bool ResourceSpawner::isRecycledResource (ResourceSpawn * resource)
Definition at line 607 of file ResourceSpawner.cpp.
References server::zone::objects::resource::ResourceSpawn::getType(), and recycledResources.
void ResourceSpawner::listResourcesForPlanetOnScreen (CreatureObject * creature, const String & planet)
Definition at line 1177 of file ResourceSpawner.cpp.
References ResourceMap::getZoneResourceList(), resourceMap, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
void ResourceSpawner::loadResourceSpawns () private
Definition at line 166 of file ResourceSpawner.cpp.
References ResourceMap::add(), ManualPool::addResource(), MinimumPool::addResource(), FixedPool::addResource(), RandomPool::addResource(), NativePool::addResource(), despawn(), ResourcePool::FIXEDPOOL, fixedPool, ResourcePool::MANUALPOOL, manualPool, ResourcePool::MINIMUMPOOL, minimumPool, ResourcePool::NATIVEPOOL, nativePool, ResourcePool::RANDOMPOOL, randomPool, resourceMap, scriptLoading, and spawnScriptResources().
Referenced by start().
String ResourceSpawner::makeResourceName (bool isOrganic) private
Definition at line 538 of file ResourceSpawner.cpp.
References ResourceTree::getEntry(), server::zone::managers::name::NameManager::makeResourceName(), nameManager, resourceMap, and resourceTree.
Referenced by createResourceSpawn().
ResourceSpawn * ResourceSpawner::manualCreateResourceSpawn (const String & type)
Definition at line 427 of file ResourceSpawner.cpp.
References ManualPool::addResource(), createResourceSpawn(), and manualPool.
int ResourceSpawner::randomizeValue (int min, int max) private
Definition at line 551 of file ResourceSpawner.cpp.
References lowerGateOverride, and spawnThrottling.
Referenced by createResourceSpawn().
void ResourceSpawner::removeZone (const String & zoneName)
Definition at line 127 of file ResourceSpawner.cpp.
References activeResourceZones, nativePool, and NativePool::removeZone().
void ResourceSpawner::sendResourceListForSurvey (CreatureObject * player, const int toolType, const String & surveyType)
Definition at line 710 of file ResourceSpawner.cpp.
References ResourceListForSurveyMessage::addResource(), ResourceListForSurveyMessage::finish(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), ResourceMap::getZoneResourceList(), resourceMap, server::zone::objects::creature::CreatureObject::sendMessage(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
int ResourceSpawner::sendResourceRecycleType (ResourceSpawn * resource)
Definition at line 705 of file ResourceSpawner.cpp.
References ResourceTreeNode::find(), ResourceTree::getBaseNode(), ResourceTreeEntry::getRecycleToolType(), server::zone::objects::resource::ResourceSpawn::getType(), and resourceTree.
void ResourceSpawner::sendSample (CreatureObject * player, const String & resname, const String & sampleAnimation)
Definition at line 845 of file ResourceSpawner.cpp.
References CreatureAttribute::ACTION, server::zone::objects::scene::SceneObject::broadcastMessage(), server::zone::objects::creature::CreatureObject::calculateCostAdjustment(), server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::player::sessions::survey::SurveySession::getActiveSurveyTool(), ResourceMap::getDensityAt(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::creature::CreatureObject::inflictDamage(), CreatureAttribute::QUICKNESS, resourceMap, and SessionFacadeType::SURVEY.
void ResourceSpawner::sendSampleResults (CreatureObject * player, const float density, const String & resname)
Definition at line 891 of file ResourceSpawner.cpp.
References CreatureAttribute::ACTION, addResourceToPlayerInventory(), server::zone::objects::creature::CreatureObject::addWounds(), server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::player::sessions::survey::SurveySession::getActiveSurveyTool(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), CreatureAttribute::HEALTH, CreatureAttribute::MIND, resourceMap, samplingMultiplier, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::chat::StringIdChatParameter::setDI(), server::zone::objects::creature::CreatureObject::setPosture(), server::chat::StringIdChatParameter::setTO(), SessionFacadeType::SURVEY, and CreaturePosture::UPRIGHT.
void ResourceSpawner::sendSurvey (CreatureObject * player, const String & resname)
Definition at line 747 of file ResourceSpawner.cpp.
References SurveyMessage::add(), server::zone::objects::creature::CreatureObject::calculateCostAdjustment(), CreatureAttribute::FOCUS, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::player::sessions::survey::SurveySession::getActiveSurveyTool(), ResourceMap::getDensityAt(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneCRC(), server::zone::Zone::getZoneName(), server::zone::objects::creature::CreatureObject::inflictDamage(), CreatureAttribute::MIND, resourceMap, server::zone::objects::creature::CreatureObject::sendMessage(), server, server::chat::StringIdChatParameter::setTO(), and SessionFacadeType::SURVEY.
void ResourceSpawner::setSpawningParameters (bool loadFromScript, const int dur, const float throt, const int override, const int spawnquantity)
Definition at line 140 of file ResourceSpawner.cpp.
References lowerGateOverride, maxSpawnAmount, scriptLoading, shiftDuration, and spawnThrottling.
void ResourceSpawner::shiftResources ()
Definition at line 376 of file ResourceSpawner.cpp.
References dumpResources(), fixedPool, manualPool, minimumPool, nativePool, randomPool, ManualPool::update(), MinimumPool::update(), FixedPool::update(), NativePool::update(), and RandomPool::update().
Referenced by start().
void ResourceSpawner::spawnScriptResources ()
Definition at line 228 of file ResourceSpawner.cpp.
References ResourceMap::add(), server::zone::managers::object::ObjectManager::createObject(), objectManager, and resourceMap.
Referenced by loadResourceSpawns().
void ResourceSpawner::start ()
Definition at line 161 of file ResourceSpawner.cpp.
References loadResourceSpawns(), and shiftResources().
bool ResourceSpawner::writeAllSpawnsToScript ()
Definition at line 305 of file ResourceSpawner.cpp.
References resourceMap, and scriptLoading.
Friends And Related Function Documentation
friend class NativePool friend
Definition at line 206 of file ResourceSpawner.h.
Referenced by ResourceSpawner().
friend class ResourceManager friend
Definition at line 205 of file ResourceSpawner.h.
friend class ResourceTree friend
Definition at line 204 of file ResourceSpawner.h.
Referenced by init().
Member Data Documentation
Vector<String> ResourceSpawner::activeResourceZones private
Definition at line 104 of file ResourceSpawner.h.
Referenced by addZone(), createResourceSpawn(), getActiveResourceZones(), removeZone(), and ~ResourceSpawner().
ObjectDatabaseManager* ResourceSpawner::databaseManager private
Definition at line 98 of file ResourceSpawner.h.
Referenced by ResourceSpawner().
FixedPool* ResourceSpawner::fixedPool private
Definition at line 107 of file ResourceSpawner.h.
Referenced by healthCheck(), initializeFixedPool(), loadResourceSpawns(), ResourceSpawner(), shiftResources(), and ~ResourceSpawner().
Vector<String> ResourceSpawner::jtlResources private
Definition at line 102 of file ResourceSpawner.h.
Referenced by addJtlResource(), and getJtlResources().
int ResourceSpawner::lowerGateOverride private
Definition at line 114 of file ResourceSpawner.h.
Referenced by randomizeValue(), and setSpawningParameters().
ManualPool* ResourceSpawner::manualPool private
Definition at line 110 of file ResourceSpawner.h.
Referenced by healthCheck(), loadResourceSpawns(), manualCreateResourceSpawn(), ResourceSpawner(), shiftResources(), and ~ResourceSpawner().
int ResourceSpawner::maxSpawnAmount private
Definition at line 114 of file ResourceSpawner.h.
Referenced by setSpawningParameters().
MinimumPool* ResourceSpawner::minimumPool private
Definition at line 106 of file ResourceSpawner.h.
Referenced by healthCheck(), initializeMinimumPool(), loadResourceSpawns(), ResourceSpawner(), shiftResources(), and ~ResourceSpawner().
NameManager* ResourceSpawner::nameManager private
Definition at line 94 of file ResourceSpawner.h.
Referenced by makeResourceName(), and ResourceSpawner().
NativePool* ResourceSpawner::nativePool private
Definition at line 109 of file ResourceSpawner.h.
Referenced by addZone(), healthCheck(), initializeNativePool(), loadResourceSpawns(), removeZone(), ResourceSpawner(), shiftResources(), and ~ResourceSpawner().
ObjectManager* ResourceSpawner::objectManager private
Definition at line 95 of file ResourceSpawner.h.
Referenced by createRecycledResourceSpawn(), createResourceSpawn(), ResourceSpawner(), and spawnScriptResources().
ManagedReference<ZoneProcessServer*> ResourceSpawner::processor private
Definition at line 92 of file ResourceSpawner.h.
Referenced by ResourceSpawner().
RandomPool* ResourceSpawner::randomPool private
Definition at line 108 of file ResourceSpawner.h.
Referenced by getFromRandomPool(), healthCheck(), initializeRandomPool(), loadResourceSpawns(), ResourceSpawner(), shiftResources(), and ~ResourceSpawner().
Vector<String> ResourceSpawner::recycledResources private
Definition at line 103 of file ResourceSpawner.h.
Referenced by addRecycledResource(), getRecycledResources(), and isRecycledResource().
ResourceMap* ResourceSpawner::resourceMap private
Definition at line 100 of file ResourceSpawner.h.
Referenced by addNodeToListBox(), addParentNodeToListBox(), createRecycledResourceSpawn(), createResourceSpawn(), despawn(), getCurrentSpawn(), getRecycledVersion(), harvestResource(), init(), listResourcesForPlanetOnScreen(), loadResourceSpawns(), makeResourceName(), sendResourceListForSurvey(), sendSample(), sendSampleResults(), sendSurvey(), spawnScriptResources(), writeAllSpawnsToScript(), and ~ResourceSpawner().
ResourceTree* ResourceSpawner::resourceTree private
Definition at line 97 of file ResourceSpawner.h.
Referenced by addNodeToListBox(), addParentNodeToListBox(), createResourceSpawn(), getRecycledVersion(), init(), makeResourceName(), sendResourceRecycleType(), and ~ResourceSpawner().
int ResourceSpawner::samplingMultiplier private
Definition at line 117 of file ResourceSpawner.h.
Referenced by ResourceSpawner(), and sendSampleResults().
bool ResourceSpawner::scriptLoading private
Definition at line 112 of file ResourceSpawner.h.
Referenced by loadResourceSpawns(), setSpawningParameters(), and writeAllSpawnsToScript().
ManagedReference<ZoneServer* > ResourceSpawner::server private
Definition at line 91 of file ResourceSpawner.h.
Referenced by ResourceSpawner(), sendSampleResults(), and sendSurvey().
int ResourceSpawner::shiftDuration private
Definition at line 114 of file ResourceSpawner.h.
Referenced by getRandomUnixTimestamp(), and setSpawningParameters().
float ResourceSpawner::spawnThrottling private
Definition at line 115 of file ResourceSpawner.h.
Referenced by randomizeValue(), and setSpawningParameters().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/ResourceSpawner.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/ResourceSpawner.cpp