Core3: server::zone::objects::player::sessions::admin::PlayerManagementSessionAdapter Class Reference
server::zone::objects::player::sessions::admin::PlayerManagementSessionAdapter Class Reference
#include <PlayerManagementSession.h>
Public Member Functions
PlayerManagementSessionAdapter (PlayerManagementSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession ()
int cancelSession ()
int clearSession ()
void addAccountSui (SuiListBox *box)
void ban (const int tablevel, unsigned const int galaxy, const String &gname, const String &name)
void getPlayerInfo (const int tablevel, const String &firstName)
void sendAccountInfo ()
void sendBanDuration ()
void parseBanDuration (const String &duration)
void sendBanReason (bool unban)
void setBanReason (const String &reason)
void showBanSummary ()
void showUnbanSummary ()
void completeBan ()
String getBanDuration (unsigned int timestamp)
Detailed Description
Definition at line 288 of file PlayerManagementSession.h.
Constructor & Destructor Documentation
PlayerManagementSessionAdapter::PlayerManagementSessionAdapter (PlayerManagementSession * impl)
Definition at line 618 of file PlayerManagementSession.cpp.
Member Function Documentation
void PlayerManagementSessionAdapter::addAccountSui (SuiListBox * box)
Definition at line 721 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
void PlayerManagementSessionAdapter::ban (const int tablevel, unsigned const int galaxy, const String & gname, const String & name)
Definition at line 725 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
int PlayerManagementSessionAdapter::cancelSession ()
Definition at line 713 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
int PlayerManagementSessionAdapter::clearSession ()
Definition at line 717 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
void PlayerManagementSessionAdapter::completeBan ()
Definition at line 761 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
String PlayerManagementSessionAdapter::getBanDuration (unsigned int timestamp)
Definition at line 765 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
void PlayerManagementSessionAdapter::getPlayerInfo (const int tablevel, const String & firstName)
Definition at line 729 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
int PlayerManagementSessionAdapter::initializeSession ()
Definition at line 709 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
void PlayerManagementSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 621 of file PlayerManagementSession.cpp.
References addAccountSui(), ban(), cancelSession(), clearSession(), completeBan(), getBanDuration(), getPlayerInfo(), initializeSession(), parseBanDuration(), RPC_ADDACCOUNTSUI__SUILISTBOX_, RPC_BAN__INT_INT_STRING_STRING_, RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_COMPLETEBAN__, RPC_GETBANDURATION__INT_, RPC_GETPLAYERINFO__INT_STRING_, RPC_INITIALIZESESSION__, RPC_PARSEBANDURATION__STRING_, RPC_SENDACCOUNTINFO__, RPC_SENDBANDURATION__, RPC_SENDBANREASON__BOOL_, RPC_SETBANREASON__STRING_, RPC_SHOWBANSUMMARY__, RPC_SHOWUNBANSUMMARY__, sendAccountInfo(), sendBanDuration(), sendBanReason(), setBanReason(), showBanSummary(), and showUnbanSummary().
void PlayerManagementSessionAdapter::parseBanDuration (const String & duration)
Definition at line 741 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
void PlayerManagementSessionAdapter::sendAccountInfo ()
Definition at line 733 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
void PlayerManagementSessionAdapter::sendBanDuration ()
Definition at line 737 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
void PlayerManagementSessionAdapter::sendBanReason (bool unban)
Definition at line 745 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
void PlayerManagementSessionAdapter::setBanReason (const String & reason)
Definition at line 749 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
void PlayerManagementSessionAdapter::showBanSummary ()
Definition at line 753 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
void PlayerManagementSessionAdapter::showUnbanSummary ()
Definition at line 757 of file PlayerManagementSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/admin/PlayerManagementSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/admin/PlayerManagementSession.cpp