Core3: server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionAdapter Class Reference
server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionAdapter Class Reference
#include <VendorAdBarkingSession.h>
Public Member Functions
VendorAdBarkingSessionAdapter (VendorAdBarkingSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession ()
int cancelSession ()
int clearSession ()
void setMessage (const String &mess)
void setMood (const String &mo)
void setAnimation (const String &ani)
void sendPhraseOptions ()
void sendCustomMessageInput ()
void sendMoodSelect ()
void sendAnimationSelect ()
Detailed Description
Definition at line 198 of file VendorAdBarkingSession.h.
Constructor & Destructor Documentation
VendorAdBarkingSessionAdapter::VendorAdBarkingSessionAdapter (VendorAdBarkingSession * impl)
Definition at line 392 of file VendorAdBarkingSession.cpp.
Member Function Documentation
int VendorAdBarkingSessionAdapter::cancelSession ()
Definition at line 461 of file VendorAdBarkingSession.cpp.
Referenced by invokeMethod().
int VendorAdBarkingSessionAdapter::clearSession ()
Definition at line 465 of file VendorAdBarkingSession.cpp.
Referenced by invokeMethod().
int VendorAdBarkingSessionAdapter::initializeSession ()
Definition at line 457 of file VendorAdBarkingSession.cpp.
Referenced by invokeMethod().
void VendorAdBarkingSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 395 of file VendorAdBarkingSession.cpp.
References cancelSession(), clearSession(), initializeSession(), RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_INITIALIZESESSION__, RPC_SENDANIMATIONSELECT__, RPC_SENDCUSTOMMESSAGEINPUT__, RPC_SENDMOODSELECT__, RPC_SENDPHRASEOPTIONS__, RPC_SETANIMATION__STRING_, RPC_SETMESSAGE__STRING_, RPC_SETMOOD__STRING_, sendAnimationSelect(), sendCustomMessageInput(), sendMoodSelect(), sendPhraseOptions(), setAnimation(), setMessage(), and setMood().
void VendorAdBarkingSessionAdapter::sendAnimationSelect ()
Definition at line 493 of file VendorAdBarkingSession.cpp.
Referenced by invokeMethod().
void VendorAdBarkingSessionAdapter::sendCustomMessageInput ()
Definition at line 485 of file VendorAdBarkingSession.cpp.
Referenced by invokeMethod().
void VendorAdBarkingSessionAdapter::sendMoodSelect ()
Definition at line 489 of file VendorAdBarkingSession.cpp.
Referenced by invokeMethod().
void VendorAdBarkingSessionAdapter::sendPhraseOptions ()
Definition at line 481 of file VendorAdBarkingSession.cpp.
Referenced by invokeMethod().
void VendorAdBarkingSessionAdapter::setAnimation (const String & ani)
Definition at line 477 of file VendorAdBarkingSession.cpp.
Referenced by invokeMethod().
void VendorAdBarkingSessionAdapter::setMessage (const String & mess)
Definition at line 469 of file VendorAdBarkingSession.cpp.
Referenced by invokeMethod().
void VendorAdBarkingSessionAdapter::setMood (const String & mo)
Definition at line 473 of file VendorAdBarkingSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/VendorAdBarkingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/VendorAdBarkingSession.cpp