Core3: server::zone::objects::mission::EntertainerMissionObjectiveAdapter Class Reference
server::zone::objects::mission::EntertainerMissionObjectiveAdapter Class Reference
#include <EntertainerMissionObjective.h>
Public Member Functions
EntertainerMissionObjectiveAdapter (EntertainerMissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
void setIsEntertaining (bool value)
void clearLocationActiveAreaAndObservers ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void startCompleteTask ()
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveAdapter
MissionObjectiveAdapter (MissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Detailed Description
Definition at line 240 of file EntertainerMissionObjective.h.
Constructor & Destructor Documentation
EntertainerMissionObjectiveAdapter::EntertainerMissionObjectiveAdapter (EntertainerMissionObjective * impl)
Definition at line 372 of file EntertainerMissionObjective.cpp.
Member Function Documentation
void EntertainerMissionObjectiveAdapter::abort ()
Definition at line 441 of file EntertainerMissionObjective.cpp.
Referenced by invokeMethod().
void EntertainerMissionObjectiveAdapter::activate ()
Definition at line 437 of file EntertainerMissionObjective.cpp.
Referenced by invokeMethod().
void EntertainerMissionObjectiveAdapter::clearLocationActiveAreaAndObservers ()
Definition at line 453 of file EntertainerMissionObjective.cpp.
Referenced by invokeMethod().
void EntertainerMissionObjectiveAdapter::complete ()
Definition at line 445 of file EntertainerMissionObjective.cpp.
Referenced by invokeMethod().
void EntertainerMissionObjectiveAdapter::finalize ()
Definition at line 429 of file EntertainerMissionObjective.cpp.
Referenced by invokeMethod().
void EntertainerMissionObjectiveAdapter::initializeTransientMembers ()
Definition at line 433 of file EntertainerMissionObjective.cpp.
Referenced by invokeMethod().
void EntertainerMissionObjectiveAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 375 of file EntertainerMissionObjective.cpp.
References abort(), activate(), clearLocationActiveAreaAndObservers(), complete(), finalize(), initializeTransientMembers(), notifyObserverEvent(), RPC_ABORT__, RPC_ACTIVATE__, RPC_CLEARLOCATIONACTIVEAREAANDOBSERVERS__, RPC_COMPLETE__, RPC_FINALIZE__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_, RPC_SETISENTERTAINING__BOOL_, RPC_STARTCOMPLETETASK__, setIsEntertaining(), and startCompleteTask().
int EntertainerMissionObjectiveAdapter::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 457 of file EntertainerMissionObjective.cpp.
Referenced by invokeMethod().
void EntertainerMissionObjectiveAdapter::setIsEntertaining (bool value)
Definition at line 449 of file EntertainerMissionObjective.cpp.
Referenced by invokeMethod().
void EntertainerMissionObjectiveAdapter::startCompleteTask ()
Definition at line 461 of file EntertainerMissionObjective.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/EntertainerMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/EntertainerMissionObjective.cpp