Core3: server::zone::managers::skill::SkillManager Class Reference
server::zone::managers::skill::SkillManager Class Reference
#include <SkillManager.h>
Public Member Functions
SkillManager ()
~SkillManager ()
void loadLuaConfig ()
void loadClientData ()
void loadAdminCommands ()
void loadSkill (LuaObject *skill)
void loadXpLimits ()
void addAbility (PlayerObject *ghost, const String &abilityName, bool notifyClient=true)
void removeAbility (PlayerObject *ghost, const String &abilityName, bool notifyClient=true)
void addAbilities (PlayerObject *ghost, Vector< String > &abilityNames, bool notifyClient=true)
void removeAbilities (PlayerObject *ghost, Vector< String > &abilityNames, bool notifyClient=true)
bool awardSkill (const String &skillName, CreatureObject *creature, bool notifyClient=true, bool awardRequiredSkills=false, bool noXpRequired=false)
void awardDraftSchematics (Skill *skill, PlayerObject *ghost, bool notifyClient=true)
bool surrenderSkill (const String &skillName, CreatureObject *creature, bool notifyClient=true)
void surrenderAllSkills (CreatureObject *creature, bool notifyClient=true)
bool canLearnSkill (const String &skillName, CreatureObject *creature, bool noXpRequired)
bool fullfillsSkillPrerequisitesAndXp (const String &skillName, CreatureObject *creature)
bool fullfillsSkillPrerequisites (const String &skillName, CreatureObject *creature)
void updateXpLimits (PlayerObject *ghost)
Skill * getSkill (const String &skillName)
Skill * getSkill (uint32 hashCode)
Ability * getAbility (const String &abilityName)
PerformanceManager * getPerformanceManager ()
bool isApprenticeshipEnabled ()
Static Public Member Functions
static int includeFile (lua_State *L)
static int addSkill (lua_State *L)
Private Attributes
PerformanceManager * performanceManager
HashTable< String, Reference
< Ability * > > abilityMap
HashTable< uint32, Reference
< Skill * > > skillMap
Reference< Skill * > rootNode
VectorMap< String, int > defaultXpLimits
bool apprenticeshipEnabled
Detailed Description
Definition at line 83 of file SkillManager.h.
Constructor & Destructor Documentation
SkillManager::SkillManager ()
Definition at line 60 of file SkillManager.cpp.
References apprenticeshipEnabled, performanceManager, and rootNode.
SkillManager::~SkillManager ()
Definition at line 70 of file SkillManager.cpp.
Member Function Documentation
void SkillManager::addAbilities (PlayerObject * ghost, Vector< String > & abilityNames, bool notifyClient = true)
Definition at line 229 of file SkillManager.cpp.
References abilityMap, server::zone::objects::player::PlayerObject::addAbilities(), and server::zone::objects::player::PlayerObject::hasAbility().
Referenced by awardSkill().
void SkillManager::addAbility (PlayerObject * ghost, const String & abilityName, bool notifyClient = true)
Definition at line 215 of file SkillManager.cpp.
References abilityMap, and server::zone::objects::player::PlayerObject::addAbility().
Referenced by SetGodModeCommand::doQueueCommand().
int SkillManager::addSkill (lua_State * L) static
Definition at line 80 of file SkillManager.cpp.
Referenced by loadAdminCommands().
void SkillManager::awardDraftSchematics (Skill * skill, PlayerObject * ghost, bool notifyClient = true)
Definition at line 526 of file SkillManager.cpp.
References Skill::getSchematicsGranted().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), and server::zone::objects::player::PlayerObjectImplementation::removeSchematics().
bool SkillManager::awardSkill (const String & skillName, CreatureObject * creature, bool notifyClient = true, bool awardRequiredSkills = false, bool noXpRequired = false)
Update client with new values for things like Terrain Negotiation
Definition at line 263 of file SkillManager.cpp.
References addAbilities(), server::zone::objects::creature::CreatureObject::addSkill(), server::zone::objects::creature::CreatureObject::addSkillMod(), server::zone::managers::player::PlayerManager::awardBadge(), canLearnSkill(), DeltaMessage::close(), server::zone::objects::scene::SceneObject::error(), server::zone::objects::scene::variables::DeltaVector< E >::get(), Skill::getAbilities(), Badge::getID(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), Skill::getSchematicsGranted(), server::zone::objects::creature::CreatureObject::getSkillList(), server::zone::objects::creature::CreatureObject::getSkillMod(), Skill::getSkillModifiers(), Skill::getSkillName(), Skill::getSkillPointsRequired(), Skill::getSkillsRequired(), Skill::getXpCost(), Skill::getXpType(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::hasSkill(), Skill::isGodOnly(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setLevel(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTU(), server::zone::objects::scene::variables::DeltaVector< E >::size(), server::zone::managers::skill::SkillModManager::SKILLBOX, skillMap, CreatureObjectDeltaMessage4::updateAccelerationMultiplierBase(), CreatureObjectDeltaMessage4::updateAccelerationMultiplierMod(), CreatureObjectDeltaMessage4::updateRunSpeed(), CreatureObjectDeltaMessage4::updateSpeedMultiplierBase(), CreatureObjectDeltaMessage4::updateSpeedMultiplierMod(), CreatureObjectDeltaMessage4::updateTerrainNegotiation(), and updateXpLimits().
Referenced by server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer(), GrantSkillCommand::doQueueCommand(), server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation::giveLanguages(), and server::zone::managers::player::PlayerManagerImplementation::updatePermissionLevel().
bool SkillManager::canLearnSkill (const String & skillName, CreatureObject * creature, bool noXpRequired)
Checks if the player can learn the skill (fullfills skill prerequisites, enough skill points and enough XP).
Parameters
skillName the name of the skill to check if the player can learn.
creature the player creatur.
noXpRequired XP check is skipped if this is set to true (used for character builder terminals and grant skill command).
Returns
true if the player fullfills the requirements.
Definition at line 579 of file SkillManager.cpp.
References fullfillsSkillPrerequisites(), server::zone::objects::creature::CreatureObject::getPlayerObject(), Skill::getSkillPointsRequired(), Skill::getXpCost(), Skill::getXpType(), server::zone::objects::creature::CreatureObject::hasSkill(), and skillMap.
Referenced by awardSkill(), and server::zone::managers::player::PlayerManagerImplementation::getTeachableSkills().
bool SkillManager::fullfillsSkillPrerequisites (const String & skillName, CreatureObject * creature)
Checks if the player fullfills the skill prerequisites.
Parameters
skillName the name of the skill to check.
creature the player creatur.
Returns
true if the player fullfills the requirements.
Definition at line 639 of file SkillManager.cpp.
References Skill::getSkillsRequired(), server::zone::objects::creature::CreatureObject::getSpeciesName(), Skill::getSpeciesRequired(), server::zone::objects::creature::CreatureObject::hasSkill(), and skillMap.
Referenced by canLearnSkill(), and fullfillsSkillPrerequisitesAndXp().
bool SkillManager::fullfillsSkillPrerequisitesAndXp (const String & skillName, CreatureObject * creature)
Checks if the player fullfills the skill prerequisites and has enough XP for the skill.
Parameters
skillName the name of the skill to check.
creature the player creatur.
Returns
true if the player fullfills the requirements.
Definition at line 617 of file SkillManager.cpp.
References fullfillsSkillPrerequisites(), server::zone::objects::creature::CreatureObject::getPlayerObject(), Skill::getXpCost(), Skill::getXpType(), and skillMap.
Ability* server::zone::managers::skill::SkillManager::getAbility (const String & abilityName) inline
Definition at line 156 of file SkillManager.h.
Referenced by AbilityList::loadFromNames().
PerformanceManager* server::zone::managers::skill::SkillManager::getPerformanceManager () inline
Definition at line 160 of file SkillManager.h.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::doEntertainerPatronEffects().
Skill* server::zone::managers::skill::SkillManager::getSkill (const String & skillName) inline
Definition at line 148 of file SkillManager.h.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::addSkill(), SkillList::containsSkill(), SkillList::loadFromNames(), server::zone::managers::player::creation::ProfessionDefaultsInfo::readObject(), and server::zone::objects::creature::CreatureObjectImplementation::removeSkill().
Skill* server::zone::managers::skill::SkillManager::getSkill (uint32 hashCode) inline
Definition at line 152 of file SkillManager.h.
int SkillManager::includeFile (lua_State * L) static
Definition at line 73 of file SkillManager.cpp.
Referenced by loadAdminCommands().
bool server::zone::managers::skill::SkillManager::isApprenticeshipEnabled () inline
Definition at line 164 of file SkillManager.h.
Referenced by server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer().
void SkillManager::loadAdminCommands ()
Definition at line 155 of file SkillManager.cpp.
References addSkill(), and includeFile().
Referenced by loadClientData().
void SkillManager::loadClientData ()
Definition at line 100 of file SkillManager.cpp.
References abilityMap, Skill::addChild(), DataTableIff::getRow(), DataTableIff::getTotalRows(), loadAdminCommands(), loadXpLimits(), DataTableIff::readObject(), rootNode, and skillMap.
void SkillManager::loadLuaConfig ()
Definition at line 88 of file SkillManager.cpp.
References apprenticeshipEnabled.
void SkillManager::loadSkill (LuaObject * skill)
Definition at line 166 of file SkillManager.cpp.
References abilityMap, Skill::addChild(), rootNode, and skillMap.
void SkillManager::loadXpLimits ()
Definition at line 190 of file SkillManager.cpp.
References defaultXpLimits, DataTableIff::getRow(), DataTableIff::getTotalRows(), DataTableRow::getValue(), and DataTableIff::readObject().
Referenced by loadClientData().
void SkillManager::removeAbilities (PlayerObject * ghost, Vector< String > & abilityNames, bool notifyClient = true)
Definition at line 244 of file SkillManager.cpp.
References abilityMap, server::zone::objects::player::PlayerObject::hasAbility(), and server::zone::objects::player::PlayerObject::removeAbilities().
Referenced by surrenderAllSkills(), and surrenderSkill().
void SkillManager::removeAbility (PlayerObject * ghost, const String & abilityName, bool notifyClient = true)
Definition at line 222 of file SkillManager.cpp.
References abilityMap, and server::zone::objects::player::PlayerObject::removeAbility().
Referenced by SetGodModeCommand::doQueueCommand().
void SkillManager::surrenderAllSkills (CreatureObject * creature, bool notifyClient = true)
update force
Definition at line 486 of file SkillManager.cpp.
References server::zone::objects::scene::variables::DeltaVector< E >::get(), Skill::getAbilities(), server::zone::objects::creature::CreatureObject::getPlayerObject(), Skill::getSchematicsGranted(), server::zone::objects::creature::CreatureObject::getSkillList(), server::zone::objects::creature::CreatureObject::getSkillMod(), Skill::getSkillModifiers(), Skill::getSkillPointsRequired(), removeAbilities(), server::zone::objects::creature::CreatureObject::removeSkill(), server::zone::objects::creature::CreatureObject::removeSkillMod(), server::zone::objects::scene::variables::DeltaVector< E >::size(), and server::zone::managers::skill::SkillModManager::SKILLBOX.
bool SkillManager::surrenderSkill (const String & skillName, CreatureObject * creature, bool notifyClient = true)
Update Force Power Max and Regen
Update client with new values for things like Terrain Negotiation
Definition at line 396 of file SkillManager.cpp.
References DeltaMessage::close(), server::zone::objects::scene::SceneObject::error(), server::zone::objects::scene::variables::DeltaVector< E >::get(), Skill::getAbilities(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), Skill::getSchematicsGranted(), server::zone::objects::creature::CreatureObject::getSkillList(), server::zone::objects::creature::CreatureObject::getSkillMod(), Skill::getSkillModifiers(), Skill::getSkillName(), Skill::getSkillPointsRequired(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::hasSkill(), Skill::isRequiredSkillOf(), removeAbilities(), server::zone::objects::creature::CreatureObject::removeSkill(), server::zone::objects::creature::CreatureObject::removeSkillMod(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::setLevel(), server::zone::objects::scene::variables::DeltaVector< E >::size(), server::zone::managers::skill::SkillModManager::SKILLBOX, skillMap, CreatureObjectDeltaMessage4::updateAccelerationMultiplierBase(), CreatureObjectDeltaMessage4::updateAccelerationMultiplierMod(), CreatureObjectDeltaMessage4::updateRunSpeed(), CreatureObjectDeltaMessage4::updateSpeedMultiplierBase(), CreatureObjectDeltaMessage4::updateSpeedMultiplierMod(), CreatureObjectDeltaMessage4::updateTerrainNegotiation(), and updateXpLimits().
Referenced by GrantSkillCommand::doQueueCommand(), SurrenderSkillCommand::doQueueCommand(), and server::zone::managers::player::PlayerManagerImplementation::updatePermissionLevel().
void SkillManager::updateXpLimits (PlayerObject * ghost)
Definition at line 534 of file SkillManager.cpp.
References server::zone::objects::player::PlayerObject::addExperience(), defaultXpLimits, DeltaVectorMap< K, V >::get(), server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::player::PlayerObject::getExperienceList(), DeltaVectorMap< K, V >::getKeyAt(), server::zone::objects::scene::SceneObject::getParentRecursively(), Skill::getXpCap(), Skill::getXpType(), server::zone::objects::player::PlayerObject::getXpTypeCapList(), server::zone::objects::scene::SceneObject::isPlayerObject(), SceneObjectType::PLAYERCREATURE, DeltaVectorMap< K, V >::size(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
Referenced by awardSkill(), server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), and surrenderSkill().
Member Data Documentation
HashTable<String, Reference<Ability*> > server::zone::managers::skill::SkillManager::abilityMap private
Definition at line 86 of file SkillManager.h.
Referenced by addAbilities(), addAbility(), loadClientData(), loadSkill(), removeAbilities(), and removeAbility().
bool server::zone::managers::skill::SkillManager::apprenticeshipEnabled private
Definition at line 93 of file SkillManager.h.
Referenced by loadLuaConfig(), and SkillManager().
VectorMap<String, int> server::zone::managers::skill::SkillManager::defaultXpLimits private
Definition at line 91 of file SkillManager.h.
Referenced by loadXpLimits(), and updateXpLimits().
PerformanceManager* server::zone::managers::skill::SkillManager::performanceManager private
Definition at line 84 of file SkillManager.h.
Referenced by SkillManager().
Reference<Skill*> server::zone::managers::skill::SkillManager::rootNode private
Definition at line 89 of file SkillManager.h.
Referenced by loadClientData(), loadSkill(), and SkillManager().
HashTable<uint32, Reference<Skill*> > server::zone::managers::skill::SkillManager::skillMap private
Definition at line 87 of file SkillManager.h.
Referenced by awardSkill(), canLearnSkill(), fullfillsSkillPrerequisites(), fullfillsSkillPrerequisitesAndXp(), loadClientData(), loadSkill(), and surrenderSkill().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/skill/SkillManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/skill/SkillManager.cpp