Core3: StartDanceCommand Class Reference
StartDanceCommand Class Reference
#include <StartDanceCommand.h>
Public Member Functions
StartDanceCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Static Public Member Functions
static void startDance (CreatureObject *creature, const String &dance, const String &animation)
static void sendAvailableDances (CreatureObject *player, PlayerObject *ghost, uint32 suiType=SuiWindowType::DANCING_START)
Detailed Description
Definition at line 54 of file StartDanceCommand.h.
Constructor & Destructor Documentation
StartDanceCommand::StartDanceCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 57 of file StartDanceCommand.h.
Member Function Documentation
int StartDanceCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 108 of file StartDanceCommand.h.
References SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), PerformanceManager::getDanceAnimation(), server::zone::objects::scene::SceneObject::getSlottedObject(), PerformanceManager::hasDanceAnimation(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), sendAvailableDances(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), startDance(), and server::zone::objects::player::sessions::EntertainingSession::stopPlayingMusic().
static void StartDanceCommand::sendAvailableDances (CreatureObject * player, PlayerObject * ghost, uint32 suiType = SuiWindowType::DANCING_START) inline static
Definition at line 77 of file StartDanceCommand.h.
References server::zone::objects::player::PlayerObject::addSuiBox(), server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::player::PlayerObject::getAbilityList(), Ability::getAbilityName(), server::zone::objects::creature::CreatureObject::sendMessage(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
Referenced by ChangeDanceCommand::doQueueCommand(), and doQueueCommand().
static void StartDanceCommand::startDance (CreatureObject * creature, const String & dance, const String & animation) inline static
Definition at line 62 of file StartDanceCommand.h.
References server::zone::objects::scene::SceneObject::addActiveSession(), SessionFacadeType::ENTERTAINING, and server::zone::objects::scene::SceneObject::getActiveSession().
Referenced by doQueueCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/StartDanceCommand.h