Core3: VendorContainerComponent Class Reference
VendorContainerComponent Class Reference
#include <VendorContainerComponent.h>
Public Member Functions
bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
Public Member Functions inherited from ContainerComponent
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
virtual int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Detailed Description
Definition at line 13 of file VendorContainerComponent.h.
Member Function Documentation
bool VendorContainerComponent::checkContainerPermission (SceneObject * sceneObject, CreatureObject * creature, uint16 permission) virtual
Reimplemented from ContainerComponent.
Definition at line 13 of file VendorContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getObjectID(), VendorDataComponent::getOwnerId(), VendorDataComponent::isInitialized(), server::zone::objects::scene::SceneObject::isVendor(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/vendor/VendorContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/vendor/VendorContainerComponent.cpp