Core3: MilkCreatureTask Class Reference
MilkCreatureTask Class Reference
#include <MilkCreatureTask.h>
Public Member Functions
MilkCreatureTask (Creature *cre, CreatureObject *playo)
void run ()
void giveMilkToPlayer ()
void updateMilkState (const short milkState)
Private Types
enum Phase { INITIAL, ONESUCCESS, ONEFAILURE, FINAL }
Private Attributes
enum MilkCreatureTask::Phase currentPhase
ManagedReference< Creature * > creature
ManagedReference
< CreatureObject * > player
Detailed Description
Definition at line 11 of file MilkCreatureTask.h.
Member Enumeration Documentation
enum MilkCreatureTask::Phase private
Enumerator
INITIAL
ONESUCCESS
ONEFAILURE
FINAL
Definition at line 14 of file MilkCreatureTask.h.
Constructor & Destructor Documentation
MilkCreatureTask::MilkCreatureTask (Creature * cre, CreatureObject * playo) inline
Definition at line 19 of file MilkCreatureTask.h.
References creature, currentPhase, INITIAL, and player.
Member Function Documentation
void MilkCreatureTask::giveMilkToPlayer () inline
Definition at line 97 of file MilkCreatureTask.h.
References creature, player, and updateMilkState().
Referenced by run().
void MilkCreatureTask::run () inline
Definition at line 25 of file MilkCreatureTask.h.
References creature, currentPhase, FINAL, giveMilkToPlayer(), INITIAL, CreatureState::MASKSCENT, ONEFAILURE, ONESUCCESS, player, and updateMilkState().
void MilkCreatureTask::updateMilkState (const short milkState) inline
Definition at line 129 of file MilkCreatureTask.h.
References creature.
Referenced by giveMilkToPlayer(), and run().
Member Data Documentation
ManagedReference<Creature*> MilkCreatureTask::creature private
Definition at line 15 of file MilkCreatureTask.h.
Referenced by giveMilkToPlayer(), MilkCreatureTask(), run(), and updateMilkState().
enum MilkCreatureTask::Phase MilkCreatureTask::currentPhase private
Referenced by MilkCreatureTask(), and run().
ManagedReference<CreatureObject*> MilkCreatureTask::player private
Definition at line 16 of file MilkCreatureTask.h.
Referenced by giveMilkToPlayer(), MilkCreatureTask(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/events/MilkCreatureTask.h