Core3: server::zone::objects::area::CampSiteObserverImplementation Class Reference
server::zone::objects::area::CampSiteObserverImplementation Class Reference
#include <CampSiteObserver.h>
Public Member Functions
CampSiteObserverImplementation (CampSiteActiveArea *area)
CampSiteObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const CampSiteObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< CampSiteObserver * > _this
Protected Member Functions
virtual ~CampSiteObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CampSiteActiveArea * > campArea
Friends
class CampSiteObserver
Detailed Description
Definition at line 58 of file CampSiteObserver.h.
Constructor & Destructor Documentation
CampSiteObserverImplementation::CampSiteObserverImplementation (CampSiteActiveArea * area)
Definition at line 190 of file CampSiteObserver.cpp.
References _initializeImplementation(), and campArea.
CampSiteObserverImplementation::CampSiteObserverImplementation (DummyConstructorParameter * param)
Definition at line 64 of file CampSiteObserver.cpp.
References _initializeImplementation().
CampSiteObserverImplementation::~CampSiteObserverImplementation () protected virtual
Definition at line 69 of file CampSiteObserver.cpp.
Member Function Documentation
DistributedObjectStub * CampSiteObserverImplementation::_getStub ()
Definition at line 89 of file CampSiteObserver.cpp.
References _this.
void CampSiteObserverImplementation::_initializeImplementation () protected
Definition at line 76 of file CampSiteObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CampSiteObserverImplementation().
void CampSiteObserverImplementation::_serializationHelperMethod () protected
Definition at line 125 of file CampSiteObserver.cpp.
Referenced by _initializeImplementation().
void CampSiteObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 84 of file CampSiteObserver.cpp.
References _this.
Referenced by server::zone::objects::area::CampSiteObserver::CampSiteObserver().
void CampSiteObserverImplementation::finalize () protected
Definition at line 73 of file CampSiteObserver.cpp.
void CampSiteObserverImplementation::lock (bool doLock = true) protected
Definition at line 97 of file CampSiteObserver.cpp.
References _this.
void CampSiteObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 101 of file CampSiteObserver.cpp.
References _this.
int CampSiteObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 198 of file CampSiteObserver.cpp.
References campArea, ObserverEventType::HEALINGPERFORMED, and ObserverEventType::STARTCOMBAT.
Referenced by server::zone::objects::area::CampSiteObserver::notifyObserverEvent().
CampSiteObserverImplementation::operator const CampSiteObserver * ()
Definition at line 93 of file CampSiteObserver.cpp.
void CampSiteObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 132 of file CampSiteObserver.cpp.
References readObjectMember().
bool CampSiteObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 151 of file CampSiteObserver.cpp.
References campArea.
Referenced by readObject().
void CampSiteObserverImplementation::rlock (bool doLock = true) protected
Definition at line 105 of file CampSiteObserver.cpp.
References _this.
void CampSiteObserverImplementation::runlock (bool doLock = true) protected
Definition at line 121 of file CampSiteObserver.cpp.
References _this.
void CampSiteObserverImplementation::unlock (bool doLock = true) protected
Definition at line 117 of file CampSiteObserver.cpp.
References _this.
void CampSiteObserverImplementation::wlock (bool doLock = true) protected
Definition at line 109 of file CampSiteObserver.cpp.
References _this.
void CampSiteObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 113 of file CampSiteObserver.cpp.
References _this.
void CampSiteObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 165 of file CampSiteObserver.cpp.
References writeObjectMembers().
int CampSiteObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 172 of file CampSiteObserver.cpp.
References campArea.
Referenced by writeObject().
Friends And Related Function Documentation
friend class CampSiteObserver friend
Definition at line 103 of file CampSiteObserver.h.
Member Data Documentation
WeakReference<CampSiteObserver*> server::zone::objects::area::CampSiteObserverImplementation::_this
Definition at line 69 of file CampSiteObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<CampSiteActiveArea* > server::zone::objects::area::CampSiteObserverImplementation::campArea protected
Definition at line 60 of file CampSiteObserver.h.
Referenced by CampSiteObserverImplementation(), notifyObserverEvent(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/CampSiteObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/CampSiteObserver.cpp