Core3: server::zone::objects::tangible::consumable::DelayedBuffObserver Class Reference
server::zone::objects::tangible::consumable::DelayedBuffObserver Class Reference
#include <DelayedBuffObserver.h>
Public Member Functions
DelayedBuffObserver (DelayedBuff *b)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
DelayedBuffObserver (DummyConstructorParameter *param)
virtual ~DelayedBuffObserver ()
Friends
class DelayedBuffObserverHelper
Detailed Description
Definition at line 70 of file DelayedBuffObserver.h.
Constructor & Destructor Documentation
DelayedBuffObserver::DelayedBuffObserver (DelayedBuff * b)
Definition at line 19 of file DelayedBuffObserver.cpp.
References server::zone::objects::tangible::consumable::DelayedBuffObserverImplementation::_setStub().
DelayedBuffObserver::DelayedBuffObserver (DummyConstructorParameter * param) protected
Definition at line 26 of file DelayedBuffObserver.cpp.
DelayedBuffObserver::~DelayedBuffObserver () protected virtual
Definition at line 30 of file DelayedBuffObserver.cpp.
Member Function Documentation
DistributedObjectServant * DelayedBuffObserver::_getImplementation ()
Definition at line 52 of file DelayedBuffObserver.cpp.
Referenced by notifyObserverEvent().
DistributedObjectServant * DelayedBuffObserver::_getImplementationForRead ()
Definition at line 58 of file DelayedBuffObserver.cpp.
void DelayedBuffObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 62 of file DelayedBuffObserver.cpp.
int DelayedBuffObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 35 of file DelayedBuffObserver.cpp.
References _getImplementation(), server::zone::objects::tangible::consumable::DelayedBuffObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class DelayedBuffObserverHelper friend
Definition at line 86 of file DelayedBuffObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/consumable/DelayedBuffObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/consumable/DelayedBuffObserver.cpp