Core3: MantisDatabase Class Reference
MantisDatabase Class Reference
#include <MantisDatabase.h>
Public Member Functions
MantisDatabase (ConfigManager *configManager)
~MantisDatabase ()
Static Public Member Functions
static Database * instance ()
static String & getTablePrefix ()
Static Public Attributes
static const int DEFAULT_SERVERDATABASE_INSTANCES = 1
Static Private Attributes
static Vector< Database * > * databases = NULL
static AtomicInteger currentDB
static String tablePrefix
Detailed Description
Definition at line 16 of file MantisDatabase.h.
Constructor & Destructor Documentation
MantisDatabase::MantisDatabase (ConfigManager * configManager) inline
Definition at line 23 of file MantisDatabase.h.
References databases, DEFAULT_SERVERDATABASE_INSTANCES, server::conf::ConfigManager::getMantisHost(), server::conf::ConfigManager::getMantisName(), server::conf::ConfigManager::getMantisPass(), server::conf::ConfigManager::getMantisPort(), server::conf::ConfigManager::getMantisPrefix(), server::conf::ConfigManager::getMantisUser(), and tablePrefix.
MantisDatabase::~MantisDatabase () inline
Definition at line 48 of file MantisDatabase.h.
References databases.
Member Function Documentation
static String& MantisDatabase::getTablePrefix () inline static
Definition at line 70 of file MantisDatabase.h.
References tablePrefix.
Referenced by server::zone::managers::holocron::HolocronManager::getReporterId(), server::zone::managers::holocron::HolocronManager::loadBugCategories(), and server::zone::managers::holocron::HolocronManager::submitTicket().
static Database* MantisDatabase::instance () inline static
Definition at line 59 of file MantisDatabase.h.
References currentDB, and databases.
Referenced by server::zone::managers::holocron::HolocronManager::getReporterId(), server::zone::managers::holocron::HolocronManager::loadBugCategories(), and server::zone::managers::holocron::HolocronManager::submitTicket().
Member Data Documentation
AtomicInteger MantisDatabase::currentDB static private
Definition at line 18 of file MantisDatabase.h.
Referenced by instance().
Vector< Database * > * MantisDatabase::databases = NULL static private
Definition at line 17 of file MantisDatabase.h.
Referenced by instance(), MantisDatabase(), and ~MantisDatabase().
const int MantisDatabase::DEFAULT_SERVERDATABASE_INSTANCES = 1 static
Definition at line 46 of file MantisDatabase.h.
Referenced by MantisDatabase().
String MantisDatabase::tablePrefix static private
Definition at line 20 of file MantisDatabase.h.
Referenced by getTablePrefix(), and MantisDatabase().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/db/MantisDatabase.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/db/MantisDatabase.cpp