Core3: server::chat::room::ChatRoomImplementation Class Reference
server::chat::room::ChatRoomImplementation Class Reference
#include <ChatRoom.h>
Public Member Functions
ChatRoomImplementation ()
ChatRoomImplementation (DummyConstructorParameter *param)
void init (ZoneServer *serv, ChatRoom *par, const String &roomName, unsigned int channelID)
void sendTo (CreatureObject *player)
void sendDestroyTo (CreatureObject *player)
void addSubRoom (ChatRoom *channel)
void removeSubRoom (ChatRoom *channel)
ChatRoom * getSubRoom (int i)
ChatRoom * getSubRoom (const String &name)
void addPlayer (CreatureObject *player, bool doLock=true)
void removePlayer (CreatureObject *player, bool doLock=true)
void removePlayer (const String &player)
void broadcastMessage (BaseMessage *msg)
void broadcastMessages (Vector< BaseMessage * > *messages)
bool hasPlayer (CreatureObject *player)
bool hasPlayer (const String &name)
void removeAllPlayers ()
void setPrivate ()
void setPublic ()
bool isPublic ()
bool isPrivate ()
bool isModerated ()
void setModerated (bool moderate)
CreatureObject * getPlayer (int idx)
int getPlayerSize ()
void setName (const String &Name)
String getName ()
String getFullPath ()
String getOwner ()
String getCreator ()
UnicodeString getTitle ()
String getGalaxyName ()
void setOwner (const String &Owner)
void setCreator (const String &Creator)
void setTitle (const String &Title)
void setRoomID (int id)
unsigned int getRoomID ()
int getSubRoomsSize ()
ChatRoom * getParent ()
int compareTo (ChatRoom *obj)
operator const ChatRoom * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< ChatRoom * > _this
Protected Member Functions
virtual ~ChatRoomImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference< ZoneServer * > server
String name
String fullPath
String owner
String creator
UnicodeString title
unsigned int roomID
ManagedReference< ChatRoom * > parent
VectorMap< String,
ManagedReference
< CreatureObject * > > playerList
VectorMap< String,
ManagedReference
< CreatureObject * > > moderatorList
VectorMap< String,
ManagedReference< ChatRoom * > > subRooms
bool isPublicRoom
bool moderated
Friends
class ChatRoom
Detailed Description
Definition at line 181 of file ChatRoom.h.
Constructor & Destructor Documentation
ChatRoomImplementation::ChatRoomImplementation ()
Definition at line 853 of file ChatRoom.cpp.
References _initializeImplementation(), creator, fullPath, isPublicRoom, moderated, moderatorList, name, owner, parent, playerList, roomID, server, subRooms, and title.
ChatRoomImplementation::ChatRoomImplementation (DummyConstructorParameter * param)
Definition at line 583 of file ChatRoom.cpp.
References _initializeImplementation().
ChatRoomImplementation::~ChatRoomImplementation () protected virtual
Definition at line 588 of file ChatRoom.cpp.
Member Function Documentation
DistributedObjectStub * ChatRoomImplementation::_getStub ()
Definition at line 608 of file ChatRoom.cpp.
References _this.
void ChatRoomImplementation::_initializeImplementation () protected
Definition at line 595 of file ChatRoom.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ChatRoomImplementation().
void ChatRoomImplementation::_serializationHelperMethod () protected
Definition at line 644 of file ChatRoom.cpp.
Referenced by _initializeImplementation().
void ChatRoomImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 603 of file ChatRoom.cpp.
References _this.
Referenced by server::chat::room::ChatRoom::ChatRoom().
void ChatRoomImplementation::addPlayer (CreatureObject * player, bool doLock = true)
Definition at line 70 of file ChatRoomImplementation.cpp.
References _this, server::zone::objects::player::PlayerObject::addChatRoom(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), playerList, roomID, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::chat::room::ChatRoom::addPlayer().
void ChatRoomImplementation::addSubRoom (ChatRoom * channel)
Definition at line 926 of file ChatRoom.cpp.
References _this, server::chat::room::ChatRoom::getName(), and subRooms.
Referenced by server::chat::room::ChatRoom::addSubRoom().
void ChatRoomImplementation::broadcastMessage (BaseMessage * msg)
Definition at line 134 of file ChatRoomImplementation.cpp.
References _this, and playerList.
Referenced by server::chat::room::ChatRoom::broadcastMessage().
void ChatRoomImplementation::broadcastMessages (Vector< BaseMessage * > * messages)
Definition at line 950 of file ChatRoom.cpp.
References _this, and playerList.
Referenced by server::chat::room::ChatRoom::broadcastMessages().
int ChatRoomImplementation::compareTo (ChatRoom * obj)
Definition at line 1101 of file ChatRoom.cpp.
References server::chat::room::ChatRoom::getRoomID(), getRoomID(), and roomID.
Referenced by server::chat::room::ChatRoom::compareTo().
void ChatRoomImplementation::finalize () protected
Definition at line 592 of file ChatRoom.cpp.
String ChatRoomImplementation::getCreator ()
Definition at line 1056 of file ChatRoom.cpp.
References creator.
Referenced by server::chat::room::ChatRoom::getCreator().
String ChatRoomImplementation::getFullPath ()
Definition at line 1046 of file ChatRoom.cpp.
References fullPath.
Referenced by server::chat::room::ChatRoom::getFullPath().
String ChatRoomImplementation::getGalaxyName ()
Definition at line 164 of file ChatRoomImplementation.cpp.
References server.
Referenced by server::chat::room::ChatRoom::getGalaxyName().
String ChatRoomImplementation::getName ()
Definition at line 1041 of file ChatRoom.cpp.
References name.
Referenced by server::chat::room::ChatRoom::getName().
String ChatRoomImplementation::getOwner ()
Definition at line 1051 of file ChatRoom.cpp.
References owner.
Referenced by server::chat::room::ChatRoom::getOwner().
ChatRoom * ChatRoomImplementation::getParent ()
Definition at line 1096 of file ChatRoom.cpp.
References parent.
Referenced by server::chat::room::ChatRoom::getParent().
CreatureObject * ChatRoomImplementation::getPlayer (int idx)
Definition at line 1026 of file ChatRoom.cpp.
References playerList.
Referenced by server::chat::room::ChatRoom::getPlayer().
int ChatRoomImplementation::getPlayerSize ()
Definition at line 1031 of file ChatRoom.cpp.
References playerList.
Referenced by server::chat::room::ChatRoom::getPlayerSize().
unsigned int ChatRoomImplementation::getRoomID ()
Definition at line 1086 of file ChatRoom.cpp.
References roomID.
Referenced by compareTo(), and server::chat::room::ChatRoom::getRoomID().
ChatRoom * ChatRoomImplementation::getSubRoom (int i)
Definition at line 938 of file ChatRoom.cpp.
References _this, and subRooms.
Referenced by server::chat::room::ChatRoom::getSubRoom().
ChatRoom * ChatRoomImplementation::getSubRoom (const String & name)
Definition at line 944 of file ChatRoom.cpp.
References _this, and subRooms.
int ChatRoomImplementation::getSubRoomsSize ()
Definition at line 1091 of file ChatRoom.cpp.
References subRooms.
Referenced by server::chat::room::ChatRoom::getSubRoomsSize().
UnicodeString ChatRoomImplementation::getTitle ()
Definition at line 1061 of file ChatRoom.cpp.
References title.
Referenced by server::chat::room::ChatRoom::getTitle().
bool ChatRoomImplementation::hasPlayer (CreatureObject * player)
Definition at line 984 of file ChatRoom.cpp.
References _this, server::zone::objects::creature::CreatureObject::getFirstName(), and playerList.
Referenced by server::chat::room::ChatRoom::hasPlayer().
bool ChatRoomImplementation::hasPlayer (const String & name)
Definition at line 990 of file ChatRoom.cpp.
References _this, and playerList.
void ChatRoomImplementation::init (ZoneServer * serv, ChatRoom * par, const String & roomName, unsigned int channelID)
Definition at line 889 of file ChatRoom.cpp.
References creator, fullPath, server::chat::room::ChatRoom::getFullPath(), isPublicRoom, name, owner, parent, playerList, roomID, server, subRooms, and title.
Referenced by server::chat::room::ChatRoom::init().
bool ChatRoomImplementation::isModerated ()
Definition at line 1016 of file ChatRoom.cpp.
References moderated.
Referenced by server::chat::room::ChatRoom::isModerated().
bool ChatRoomImplementation::isPrivate ()
Definition at line 1011 of file ChatRoom.cpp.
References isPublicRoom.
Referenced by server::chat::room::ChatRoom::isPrivate().
bool ChatRoomImplementation::isPublic ()
Definition at line 1006 of file ChatRoom.cpp.
References isPublicRoom.
Referenced by server::chat::room::ChatRoom::isPublic().
void ChatRoomImplementation::lock (bool doLock = true) protected
Definition at line 616 of file ChatRoom.cpp.
References _this.
void ChatRoomImplementation::lock (ManagedObject * obj) protected
Definition at line 620 of file ChatRoom.cpp.
References _this.
ChatRoomImplementation::operator const ChatRoom * ()
Definition at line 612 of file ChatRoom.cpp.
void ChatRoomImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 651 of file ChatRoom.cpp.
References readObjectMember().
bool ChatRoomImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 670 of file ChatRoom.cpp.
References creator, fullPath, isPublicRoom, moderated, moderatorList, name, owner, parent, playerList, roomID, server, subRooms, and title.
Referenced by readObject().
void ChatRoomImplementation::removeAllPlayers ()
Definition at line 147 of file ChatRoomImplementation.cpp.
References _this, playerList, and server::zone::objects::player::PlayerObject::removeChatRoom().
Referenced by server::chat::room::ChatRoom::removeAllPlayers().
void ChatRoomImplementation::removePlayer (CreatureObject * player, bool doLock = true)
Definition at line 95 of file ChatRoomImplementation.cpp.
References _this, server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), playerList, server::zone::objects::player::PlayerObject::removeChatRoom(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::chat::room::ChatRoom::removePlayer().
void ChatRoomImplementation::removePlayer (const String & player)
Definition at line 112 of file ChatRoomImplementation.cpp.
References _this, playerList, and server::zone::objects::player::PlayerObject::removeChatRoom().
void ChatRoomImplementation::removeSubRoom (ChatRoom * channel)
Definition at line 932 of file ChatRoom.cpp.
References _this, server::chat::room::ChatRoom::getName(), and subRooms.
Referenced by server::chat::room::ChatRoom::removeSubRoom().
void ChatRoomImplementation::rlock (bool doLock = true) protected
Definition at line 624 of file ChatRoom.cpp.
References _this.
void ChatRoomImplementation::runlock (bool doLock = true) protected
Definition at line 640 of file ChatRoom.cpp.
References _this.
void ChatRoomImplementation::sendDestroyTo (CreatureObject * player)
Definition at line 65 of file ChatRoomImplementation.cpp.
References roomID, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by server::chat::room::ChatRoom::sendDestroyTo().
void ChatRoomImplementation::sendTo (CreatureObject * player)
Definition at line 57 of file ChatRoomImplementation.cpp.
References _this, server::zone::packets::chat::ChatRoomList::addChannel(), server::zone::packets::chat::ChatRoomList::insertChannelListCount(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::chat::room::ChatRoom::sendTo().
void ChatRoomImplementation::setCreator (const String & Creator)
Definition at line 1071 of file ChatRoom.cpp.
References creator.
Referenced by server::chat::room::ChatRoom::setCreator().
void ChatRoomImplementation::setModerated (bool moderate)
Definition at line 1021 of file ChatRoom.cpp.
References moderated.
Referenced by server::chat::room::ChatRoom::setModerated().
void ChatRoomImplementation::setName (const String & Name)
Definition at line 1036 of file ChatRoom.cpp.
References name.
Referenced by server::chat::room::ChatRoom::setName().
void ChatRoomImplementation::setOwner (const String & Owner)
Definition at line 1066 of file ChatRoom.cpp.
References owner.
Referenced by server::chat::room::ChatRoom::setOwner().
void ChatRoomImplementation::setPrivate ()
Definition at line 996 of file ChatRoom.cpp.
References isPublicRoom.
Referenced by server::chat::room::ChatRoom::setPrivate().
void ChatRoomImplementation::setPublic ()
Definition at line 1001 of file ChatRoom.cpp.
References isPublicRoom.
Referenced by server::chat::room::ChatRoom::setPublic().
void ChatRoomImplementation::setRoomID (int id)
Definition at line 1081 of file ChatRoom.cpp.
References roomID.
Referenced by server::chat::room::ChatRoom::setRoomID().
void ChatRoomImplementation::setTitle (const String & Title)
Definition at line 1076 of file ChatRoom.cpp.
References title.
Referenced by server::chat::room::ChatRoom::setTitle().
void ChatRoomImplementation::unlock (bool doLock = true) protected
Definition at line 636 of file ChatRoom.cpp.
References _this.
void ChatRoomImplementation::wlock (bool doLock = true) protected
Definition at line 628 of file ChatRoom.cpp.
References _this.
void ChatRoomImplementation::wlock (ManagedObject * obj) protected
Definition at line 632 of file ChatRoom.cpp.
References _this.
void ChatRoomImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 732 of file ChatRoom.cpp.
References writeObjectMembers().
int ChatRoomImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 739 of file ChatRoom.cpp.
References creator, fullPath, isPublicRoom, moderated, moderatorList, name, owner, parent, playerList, roomID, server, subRooms, and title.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ChatRoom friend
Definition at line 324 of file ChatRoom.h.
Member Data Documentation
WeakReference<ChatRoom*> server::chat::room::ChatRoomImplementation::_this
Definition at line 290 of file ChatRoom.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addPlayer(), addSubRoom(), broadcastMessage(), broadcastMessages(), getSubRoom(), hasPlayer(), lock(), removeAllPlayers(), removePlayer(), removeSubRoom(), rlock(), runlock(), sendTo(), unlock(), and wlock().
String server::chat::room::ChatRoomImplementation::creator protected
Definition at line 191 of file ChatRoom.h.
Referenced by ChatRoomImplementation(), getCreator(), init(), readObjectMember(), setCreator(), and writeObjectMembers().
String server::chat::room::ChatRoomImplementation::fullPath protected
Definition at line 187 of file ChatRoom.h.
Referenced by ChatRoomImplementation(), getFullPath(), init(), readObjectMember(), and writeObjectMembers().
bool server::chat::room::ChatRoomImplementation::isPublicRoom protected
Definition at line 205 of file ChatRoom.h.
Referenced by ChatRoomImplementation(), init(), isPrivate(), isPublic(), readObjectMember(), setPrivate(), setPublic(), and writeObjectMembers().
bool server::chat::room::ChatRoomImplementation::moderated protected
Definition at line 207 of file ChatRoom.h.
Referenced by ChatRoomImplementation(), isModerated(), readObjectMember(), setModerated(), and writeObjectMembers().
VectorMap<String, ManagedReference<CreatureObject* > > server::chat::room::ChatRoomImplementation::moderatorList protected
Definition at line 201 of file ChatRoom.h.
Referenced by ChatRoomImplementation(), readObjectMember(), and writeObjectMembers().
String server::chat::room::ChatRoomImplementation::name protected
Definition at line 185 of file ChatRoom.h.
Referenced by ChatRoomImplementation(), getName(), init(), readObjectMember(), setName(), and writeObjectMembers().
String server::chat::room::ChatRoomImplementation::owner protected
Definition at line 189 of file ChatRoom.h.
Referenced by ChatRoomImplementation(), getOwner(), init(), readObjectMember(), setOwner(), and writeObjectMembers().
ManagedReference<ChatRoom* > server::chat::room::ChatRoomImplementation::parent protected
Definition at line 197 of file ChatRoom.h.
Referenced by ChatRoomImplementation(), getParent(), init(), readObjectMember(), and writeObjectMembers().
VectorMap<String, ManagedReference<CreatureObject* > > server::chat::room::ChatRoomImplementation::playerList protected
Definition at line 199 of file ChatRoom.h.
Referenced by addPlayer(), broadcastMessage(), broadcastMessages(), ChatRoomImplementation(), getPlayer(), getPlayerSize(), hasPlayer(), init(), readObjectMember(), removeAllPlayers(), removePlayer(), and writeObjectMembers().
unsigned int server::chat::room::ChatRoomImplementation::roomID protected
Definition at line 195 of file ChatRoom.h.
Referenced by addPlayer(), ChatRoomImplementation(), compareTo(), getRoomID(), init(), readObjectMember(), sendDestroyTo(), setRoomID(), and writeObjectMembers().
ManagedReference<ZoneServer* > server::chat::room::ChatRoomImplementation::server protected
Definition at line 183 of file ChatRoom.h.
Referenced by addPlayer(), ChatRoomImplementation(), getGalaxyName(), init(), readObjectMember(), sendDestroyTo(), and writeObjectMembers().
VectorMap<String, ManagedReference<ChatRoom* > > server::chat::room::ChatRoomImplementation::subRooms protected
Definition at line 203 of file ChatRoom.h.
Referenced by addSubRoom(), ChatRoomImplementation(), getSubRoom(), getSubRoomsSize(), init(), readObjectMember(), removeSubRoom(), and writeObjectMembers().
UnicodeString server::chat::room::ChatRoomImplementation::title protected
Definition at line 193 of file ChatRoom.h.
Referenced by ChatRoomImplementation(), getTitle(), init(), readObjectMember(), setTitle(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/room/ChatRoom.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/room/ChatRoom.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/room/ChatRoomImplementation.cpp