Core3: server::zone::managers::objectcontroller::ObjectControllerImplementation Class Reference
server::zone::managers::objectcontroller::ObjectControllerImplementation Class Reference
#include <ObjectController.h>
Public Member Functions
ObjectControllerImplementation (ZoneProcessServer *srv)
ObjectControllerImplementation (DummyConstructorParameter *param)
void finalize ()
void loadCommands ()
bool transferObject (SceneObject *objectToTransfer, SceneObject *destinationObject, int containmentType, bool notifyClient=false)
float activateCommand (CreatureObject *object, unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString &arguments)
void addQueueCommand (QueueCommand *command)
QueueCommand * getQueueCommand (const String &name)
QueueCommand * getQueueCommand (unsigned int crc)
operator const ObjectController * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< ObjectController * > _this
Protected Member Functions
virtual ~ObjectControllerImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
ManagedReference
< ZoneProcessServer * > server
Reference< CommandConfigManager * > configManager
Reference< CommandList * > queueCommands
Logger adminLog
Friends
class ObjectController
Detailed Description
Definition at line 171 of file ObjectController.h.
Constructor & Destructor Documentation
ObjectControllerImplementation::ObjectControllerImplementation (ZoneProcessServer * srv)
Definition at line 248 of file ObjectController.cpp.
References _initializeImplementation(), loadCommands(), and server.
ObjectControllerImplementation::ObjectControllerImplementation (DummyConstructorParameter * param)
Definition at line 136 of file ObjectController.cpp.
References _initializeImplementation().
ObjectControllerImplementation::~ObjectControllerImplementation () protected virtual
Definition at line 141 of file ObjectController.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * ObjectControllerImplementation::_getStub ()
Definition at line 159 of file ObjectController.cpp.
References _this.
void ObjectControllerImplementation::_initializeImplementation () protected
Definition at line 146 of file ObjectController.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ObjectControllerImplementation().
void ObjectControllerImplementation::_serializationHelperMethod () protected
Definition at line 195 of file ObjectController.cpp.
Referenced by _initializeImplementation().
void ObjectControllerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 154 of file ObjectController.cpp.
References _this.
Referenced by server::zone::managers::objectcontroller::ObjectController::ObjectController().
float ObjectControllerImplementation::activateCommand (CreatureObject * object, unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString & arguments)
Activates a queue command from a creature object
Parameters
object creature object that the command will be run on
actionCRC crc of the command to run
actionCount count of the command targetID target object id
arguments arguments of the command
Returns
time in seconds of command execution
Add Skillmods if any
Remove Skillmods if any
Definition at line 145 of file ObjectControllerImplementation.cpp.
References adminLog, server::zone::objects::creature::commands::QueueCommand::doQueueCommand(), server::zone::objects::creature::commands::QueueCommand::getCharacterAbility(), server::zone::objects::creature::commands::QueueCommand::getCommandDuration(), server::zone::objects::creature::commands::QueueCommand::getCommandGroup(), server::zone::objects::creature::commands::QueueCommand::getDefaultPriority(), server::zone::objects::scene::SceneObject::getDisplayedName(), getQueueCommand(), server::zone::objects::creature::commands::QueueCommand::getQueueCommandName(), server::zone::objects::creature::commands::QueueCommand::getSkillMod(), server::zone::objects::creature::commands::QueueCommand::getSkillModSize(), server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::commands::QueueCommand::onComplete(), server::zone::objects::creature::commands::QueueCommand::onFail(), and server::zone::objects::creature::commands::QueueCommand::requiresAdmin().
Referenced by server::zone::managers::objectcontroller::ObjectController::activateCommand().
void ObjectControllerImplementation::addQueueCommand (QueueCommand * command)
Definition at line 281 of file ObjectControllerImplementation.cpp.
References queueCommands.
Referenced by server::zone::managers::objectcontroller::ObjectController::addQueueCommand().
void ObjectControllerImplementation::finalize ()
Definition at line 48 of file ObjectControllerImplementation.cpp.
References configManager, and queueCommands.
Referenced by ~ObjectControllerImplementation().
QueueCommand * ObjectControllerImplementation::getQueueCommand (const String & name)
Definition at line 285 of file ObjectControllerImplementation.cpp.
References queueCommands.
Referenced by activateCommand(), and server::zone::managers::objectcontroller::ObjectController::getQueueCommand().
QueueCommand* server::zone::managers::objectcontroller::ObjectControllerImplementation::getQueueCommand (unsigned int crc)
void ObjectControllerImplementation::loadCommands ()
Definition at line 23 of file ObjectControllerImplementation.cpp.
References adminLog, configManager, queueCommands, and server.
Referenced by server::zone::managers::objectcontroller::ObjectController::loadCommands(), and ObjectControllerImplementation().
void ObjectControllerImplementation::lock (bool doLock = true) protected
Definition at line 167 of file ObjectController.cpp.
References _this.
void ObjectControllerImplementation::lock (ManagedObject * obj) protected
Definition at line 171 of file ObjectController.cpp.
References _this.
ObjectControllerImplementation::operator const ObjectController * ()
Definition at line 163 of file ObjectController.cpp.
void ObjectControllerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 202 of file ObjectController.cpp.
References readObjectMember().
bool ObjectControllerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 221 of file ObjectController.cpp.
Referenced by readObject().
void ObjectControllerImplementation::rlock (bool doLock = true) protected
Definition at line 175 of file ObjectController.cpp.
References _this.
void ObjectControllerImplementation::runlock (bool doLock = true) protected
Definition at line 191 of file ObjectController.cpp.
References _this.
bool ObjectControllerImplementation::transferObject (SceneObject * objectToTransfer, SceneObject * destinationObject, int containmentType, bool notifyClient = false)
Definition at line 60 of file ObjectControllerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getContainmentType(), server::zone::objects::scene::SceneObject::getParent(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::managers::objectcontroller::ObjectController::transferObject().
void ObjectControllerImplementation::unlock (bool doLock = true) protected
Definition at line 187 of file ObjectController.cpp.
References _this.
void ObjectControllerImplementation::wlock (bool doLock = true) protected
Definition at line 179 of file ObjectController.cpp.
References _this.
void ObjectControllerImplementation::wlock (ManagedObject * obj) protected
Definition at line 183 of file ObjectController.cpp.
References _this.
void ObjectControllerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 231 of file ObjectController.cpp.
References writeObjectMembers().
int ObjectControllerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 238 of file ObjectController.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ObjectController friend
Definition at line 240 of file ObjectController.h.
Member Data Documentation
WeakReference<ObjectController*> server::zone::managers::objectcontroller::ObjectControllerImplementation::_this
Definition at line 208 of file ObjectController.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
Logger server::zone::managers::objectcontroller::ObjectControllerImplementation::adminLog private
Definition at line 178 of file ObjectController.h.
Referenced by activateCommand(), and loadCommands().
Reference<CommandConfigManager* > server::zone::managers::objectcontroller::ObjectControllerImplementation::configManager private
Definition at line 174 of file ObjectController.h.
Referenced by finalize(), and loadCommands().
Reference<CommandList* > server::zone::managers::objectcontroller::ObjectControllerImplementation::queueCommands private
Definition at line 176 of file ObjectController.h.
Referenced by addQueueCommand(), finalize(), getQueueCommand(), and loadCommands().
ManagedReference<ZoneProcessServer* > server::zone::managers::objectcontroller::ObjectControllerImplementation::server private
Definition at line 172 of file ObjectController.h.
Referenced by loadCommands(), and ObjectControllerImplementation().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/objectcontroller/ObjectController.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/objectcontroller/ObjectController.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/objectcontroller/ObjectControllerImplementation.cpp