Core3: PathNode Class Reference
PathNode Class Reference
#include <PathNode.h>
Public Member Functions
PathNode (PathGraph *graph)
void addChild (PathNode *node)
void readObject (IffStream *iffStream)
float getX ()
float getY ()
float getZ ()
uint32 getID ()
Vector3 getPosition ()
Vector< PathNode * > * getNeighbors ()
int getGlobalGraphNodeID ()
PathGraph * getPathGraph ()
Private Attributes
Vector< PathNode * > children
uint32 id
int var2
int globalGraphNodeID
int var4
float x
float z
float y
float var8
PathGraph * pathGraph
Detailed Description
Definition at line 15 of file PathNode.h.
Constructor & Destructor Documentation
PathNode::PathNode (PathGraph * graph) inline
Definition at line 25 of file PathNode.h.
References globalGraphNodeID, pathGraph, var2, var4, var8, x, y, and z.
Member Function Documentation
void PathNode::addChild (PathNode * node) inline
Definition at line 32 of file PathNode.h.
References children.
Referenced by PortalLayout::connectFloorMeshGraphs(), and PathGraph::connectNodes().
int PathNode::getGlobalGraphNodeID () inline
Definition at line 74 of file PathNode.h.
References globalGraphNodeID.
Referenced by PortalLayout::connectFloorMeshGraphs(), PathGraph::findGlobalNode(), PathGraph::findNearestGlobalNode(), FleeStateComponent::getFleeLocation(), and PathGraph::getNode().
uint32 PathNode::getID ()
Definition at line 12 of file PathGraph.cpp.
References FloorMesh::getCellID(), PathGraph::getFloorMesh(), id, and pathGraph.
Referenced by PathFinderManager::findPathFromCellToDifferentCell().
Vector<PathNode*>* PathNode::getNeighbors () inline
Definition at line 70 of file PathNode.h.
References children.
PathGraph* PathNode::getPathGraph () inline
Definition at line 78 of file PathNode.h.
References pathGraph.
Referenced by PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), PathFinderManager::findPathFromWorldToCell(), and PortalLayout::getPath().
Vector3 PathNode::getPosition () inline
Definition at line 66 of file PathNode.h.
References x, y, and z.
Referenced by PathGraph::calculateManhattanDistance(), CollisionManager::findNearestPathNode(), PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), and PathFinderManager::findPathFromWorldToCell().
float PathNode::getX () inline
Definition at line 48 of file PathNode.h.
References x.
Referenced by PathGraph::findNearestGlobalNode(), and PathGraph::findNearestNode().
float PathNode::getY () inline
Definition at line 52 of file PathNode.h.
References y.
Referenced by PathGraph::findNearestGlobalNode(), and PathGraph::findNearestNode().
float PathNode::getZ () inline
Definition at line 56 of file PathNode.h.
References z.
Referenced by PathGraph::findNearestGlobalNode(), and PathGraph::findNearestNode().
void PathNode::readObject (IffStream * iffStream) inline
Definition at line 36 of file PathNode.h.
References globalGraphNodeID, var2, var4, var8, x, y, and z.
Referenced by PathGraph::readObject().
Member Data Documentation
Vector<PathNode*> PathNode::children private
Definition at line 16 of file PathNode.h.
Referenced by addChild(), and getNeighbors().
int PathNode::globalGraphNodeID private
Definition at line 19 of file PathNode.h.
Referenced by getGlobalGraphNodeID(), PathNode(), and readObject().
uint32 PathNode::id private
Definition at line 18 of file PathNode.h.
Referenced by getID().
PathGraph* PathNode::pathGraph private
Definition at line 22 of file PathNode.h.
Referenced by getID(), getPathGraph(), and PathNode().
int PathNode::var2 private
Definition at line 19 of file PathNode.h.
Referenced by PathNode(), and readObject().
int PathNode::var4 private
Definition at line 19 of file PathNode.h.
Referenced by PathNode(), and readObject().
float PathNode::var8 private
Definition at line 20 of file PathNode.h.
Referenced by PathNode(), and readObject().
float PathNode::x private
Definition at line 20 of file PathNode.h.
Referenced by getPosition(), getX(), PathNode(), and readObject().
float PathNode::y private
Definition at line 20 of file PathNode.h.
Referenced by getPosition(), getY(), PathNode(), and readObject().
float PathNode::z private
Definition at line 20 of file PathNode.h.
Referenced by getPosition(), getZ(), PathNode(), and readObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/PathNode.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/PathGraph.cpp