Core3: server::zone::managers::resource::ResourceManagerAdapter Class Reference
server::zone::managers::resource::ResourceManagerAdapter Class Reference
#include <ResourceManager.h>
Public Member Functions
ResourceManagerAdapter (ResourceManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void stop ()
void initialize ()
void shiftResources ()
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
int getResourceRecycleType (ResourceSpawn *resource)
void sendResourceListForSurvey (CreatureObject *playerCreature, const int toolType, const String &surveyType)
void sendSurvey (CreatureObject *playerCreature, const String &resname)
void sendSample (CreatureObject *playerCreature, const String &resname, const String &sampleAnimation)
ResourceContainer * harvestResource (CreatureObject *player, const String &type, const int quantity)
void harvestResourceToPlayer (CreatureObject *player, ResourceSpawn *resourceSpawn, const int quantity)
unsigned int getAvailablePowerFromPlayer (CreatureObject *player)
void removePowerFromPlayer (CreatureObject *player, unsigned int power)
void createResourceSpawn (CreatureObject *playerCreature, const String &restype)
void givePlayerResource (CreatureObject *playerCreature, const String &restype, const int quantity)
ResourceSpawn * getCurrentSpawn (const String &restype, const String &zoneName)
ResourceSpawn * getResourceSpawn (const String &spawnName)
bool isRecycledResource (ResourceSpawn *resource)
ResourceSpawn * getRecycledVersion (ResourceSpawn *resource)
void addNodeToListBox (SuiListBox *sui, const String &nodeName)
String addParentNodeToListBox (SuiListBox *sui, const String &currentNode)
void listResourcesForPlanetOnScreen (CreatureObject *creature, const String &planet)
String healthCheck ()
String dumpResources ()
String despawnResource (String &resourceName)
Detailed Description
Definition at line 345 of file ResourceManager.h.
Constructor & Destructor Documentation
ResourceManagerAdapter::ResourceManagerAdapter (ResourceManager * impl)
Definition at line 586 of file ResourceManager.cpp.
Member Function Documentation
void ResourceManagerAdapter::addNodeToListBox (SuiListBox * sui, const String & nodeName)
Definition at line 802 of file ResourceManager.cpp.
Referenced by invokeMethod().
String ResourceManagerAdapter::addParentNodeToListBox (SuiListBox * sui, const String & currentNode)
Definition at line 806 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::createResourceSpawn (CreatureObject * playerCreature, const String & restype)
Definition at line 778 of file ResourceManager.cpp.
Referenced by invokeMethod().
String ResourceManagerAdapter::despawnResource (String & resourceName)
Definition at line 822 of file ResourceManager.cpp.
Referenced by invokeMethod().
String ResourceManagerAdapter::dumpResources ()
Definition at line 818 of file ResourceManager.cpp.
Referenced by invokeMethod().
unsigned int ResourceManagerAdapter::getAvailablePowerFromPlayer (CreatureObject * player)
Definition at line 770 of file ResourceManager.cpp.
Referenced by invokeMethod().
ResourceSpawn * ResourceManagerAdapter::getCurrentSpawn (const String & restype, const String & zoneName)
Definition at line 786 of file ResourceManager.cpp.
Referenced by invokeMethod().
ResourceSpawn * ResourceManagerAdapter::getRecycledVersion (ResourceSpawn * resource)
Definition at line 798 of file ResourceManager.cpp.
Referenced by invokeMethod().
int ResourceManagerAdapter::getResourceRecycleType (ResourceSpawn * resource)
Definition at line 746 of file ResourceManager.cpp.
Referenced by invokeMethod().
ResourceSpawn * ResourceManagerAdapter::getResourceSpawn (const String & spawnName)
Definition at line 790 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::givePlayerResource (CreatureObject * playerCreature, const String & restype, const int quantity)
Definition at line 782 of file ResourceManager.cpp.
Referenced by invokeMethod().
ResourceContainer * ResourceManagerAdapter::harvestResource (CreatureObject * player, const String & type, const int quantity)
Definition at line 762 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::harvestResourceToPlayer (CreatureObject * player, ResourceSpawn * resourceSpawn, const int quantity)
Definition at line 766 of file ResourceManager.cpp.
Referenced by invokeMethod().
String ResourceManagerAdapter::healthCheck ()
Definition at line 814 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::initialize ()
Definition at line 734 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 589 of file ResourceManager.cpp.
References addNodeToListBox(), addParentNodeToListBox(), createResourceSpawn(), despawnResource(), dumpResources(), getAvailablePowerFromPlayer(), getCurrentSpawn(), getRecycledVersion(), getResourceRecycleType(), getResourceSpawn(), givePlayerResource(), harvestResource(), harvestResourceToPlayer(), healthCheck(), initialize(), isRecycledResource(), listResourcesForPlanetOnScreen(), notifyObserverEvent(), removePowerFromPlayer(), RPC_ADDNODETOLISTBOX__SUILISTBOX_STRING_, RPC_ADDPARENTNODETOLISTBOX__SUILISTBOX_STRING_, RPC_CREATERESOURCESPAWN__CREATUREOBJECT_STRING_, RPC_DESPAWNRESOURCE__STRING_, RPC_DUMPRESOURCES__, RPC_GETAVAILABLEPOWERFROMPLAYER__CREATUREOBJECT_, RPC_GETCURRENTSPAWN__STRING_STRING_, RPC_GETRECYCLEDVERSION__RESOURCESPAWN_, RPC_GETRESOURCERECYCLETYPE__RESOURCESPAWN_, RPC_GETRESOURCESPAWN__STRING_, RPC_GIVEPLAYERRESOURCE__CREATUREOBJECT_STRING_INT_, RPC_HARVESTRESOURCE__CREATUREOBJECT_STRING_INT_, RPC_HARVESTRESOURCETOPLAYER__CREATUREOBJECT_RESOURCESPAWN_INT_, RPC_HEALTHCHECK__, RPC_INITIALIZE__, RPC_ISRECYCLEDRESOURCE__RESOURCESPAWN_, RPC_LISTRESOURCESFORPLANETONSCREEN__CREATUREOBJECT_STRING_, RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_, RPC_REMOVEPOWERFROMPLAYER__CREATUREOBJECT_INT_, RPC_SENDRESOURCELISTFORSURVEY__CREATUREOBJECT_INT_STRING_, RPC_SENDSAMPLE__CREATUREOBJECT_STRING_STRING_, RPC_SENDSURVEY__CREATUREOBJECT_STRING_, RPC_SHIFTRESOURCES__, RPC_STOP__, sendResourceListForSurvey(), sendSample(), sendSurvey(), shiftResources(), and stop().
bool ResourceManagerAdapter::isRecycledResource (ResourceSpawn * resource)
Definition at line 794 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::listResourcesForPlanetOnScreen (CreatureObject * creature, const String & planet)
Definition at line 810 of file ResourceManager.cpp.
Referenced by invokeMethod().
int ResourceManagerAdapter::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 742 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::removePowerFromPlayer (CreatureObject * player, unsigned int power)
Definition at line 774 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::sendResourceListForSurvey (CreatureObject * playerCreature, const int toolType, const String & surveyType)
Definition at line 750 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::sendSample (CreatureObject * playerCreature, const String & resname, const String & sampleAnimation)
Definition at line 758 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::sendSurvey (CreatureObject * playerCreature, const String & resname)
Definition at line 754 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::shiftResources ()
Definition at line 738 of file ResourceManager.cpp.
Referenced by invokeMethod().
void ResourceManagerAdapter::stop ()
Definition at line 730 of file ResourceManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/ResourceManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/ResourceManager.cpp