Core3: server::zone::objects::creature::conversation::ConversationObserver Class Reference
server::zone::objects::creature::conversation::ConversationObserver Class Reference
#include <ConversationObserver.h>
Public Member Functions
ConversationObserver (ConversationTemplate *conversationTemplate)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
ConversationScreen * getNextConversationScreen (CreatureObject *conversingPlayer, int selectedOption, CreatureObject *conversingNPC)
ConversationScreen * runScreenHandlers (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ConversationObserver (DummyConstructorParameter *param)
virtual ~ConversationObserver ()
Friends
class ConversationObserverHelper
Detailed Description
Definition at line 32 of file ConversationObserver.h.
Constructor & Destructor Documentation
ConversationObserver::ConversationObserver (ConversationTemplate * conversationTemplate)
Definition at line 13 of file ConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::_setStub().
ConversationObserver::ConversationObserver (DummyConstructorParameter * param) protected
Definition at line 20 of file ConversationObserver.cpp.
ConversationObserver::~ConversationObserver () protected virtual
Definition at line 24 of file ConversationObserver.cpp.
Member Function Documentation
DistributedObjectServant * ConversationObserver::_getImplementation ()
Definition at line 64 of file ConversationObserver.cpp.
Referenced by getNextConversationScreen(), notifyObserverEvent(), and runScreenHandlers().
DistributedObjectServant * ConversationObserver::_getImplementationForRead ()
Definition at line 70 of file ConversationObserver.cpp.
void ConversationObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 74 of file ConversationObserver.cpp.
ConversationScreen * ConversationObserver::getNextConversationScreen (CreatureObject * conversingPlayer, int selectedOption, CreatureObject * conversingNPC)
Definition at line 46 of file ConversationObserver.cpp.
References _getImplementation(), and server::zone::objects::creature::conversation::ConversationObserverImplementation::getNextConversationScreen().
int ConversationObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 29 of file ConversationObserver.cpp.
References _getImplementation(), server::zone::objects::creature::conversation::ConversationObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
ConversationScreen * ConversationObserver::runScreenHandlers (CreatureObject * conversingPlayer, CreatureObject * conversingNPC, int selectedOption, ConversationScreen * conversationScreen)
Definition at line 55 of file ConversationObserver.cpp.
References _getImplementation(), and server::zone::objects::creature::conversation::ConversationObserverImplementation::runScreenHandlers().
Friends And Related Function Documentation
friend class ConversationObserverHelper friend
Definition at line 52 of file ConversationObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/ConversationObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/ConversationObserver.cpp