Core3: server::zone::objects::player::sui::listbox::SuiListBoxMenuItemImplementation Class Reference
server::zone::objects::player::sui::listbox::SuiListBoxMenuItemImplementation Class Reference
#include <SuiListBoxMenuItem.h>
Public Member Functions
SuiListBoxMenuItemImplementation (const String &name, unsigned long long oid=0)
SuiListBoxMenuItemImplementation (DummyConstructorParameter *param)
unsigned long long getObjectID ()
String getOptionName ()
operator const SuiListBoxMenuItem * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< SuiListBoxMenuItem * > _this
Protected Member Functions
virtual ~SuiListBoxMenuItemImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
String optionName
unsigned long long objectID
Friends
class SuiListBoxMenuItem
Detailed Description
Definition at line 76 of file SuiListBoxMenuItem.h.
Constructor & Destructor Documentation
SuiListBoxMenuItemImplementation::SuiListBoxMenuItemImplementation (const String & name, unsigned long long oid = 0)
Definition at line 215 of file SuiListBoxMenuItem.cpp.
References _initializeImplementation(), objectID, and optionName.
SuiListBoxMenuItemImplementation::SuiListBoxMenuItemImplementation (DummyConstructorParameter * param)
Definition at line 77 of file SuiListBoxMenuItem.cpp.
References _initializeImplementation().
SuiListBoxMenuItemImplementation::~SuiListBoxMenuItemImplementation () protected virtual
Definition at line 82 of file SuiListBoxMenuItem.cpp.
Member Function Documentation
DistributedObjectStub * SuiListBoxMenuItemImplementation::_getStub ()
Definition at line 102 of file SuiListBoxMenuItem.cpp.
References _this.
void SuiListBoxMenuItemImplementation::_initializeImplementation () protected
Definition at line 89 of file SuiListBoxMenuItem.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SuiListBoxMenuItemImplementation().
void SuiListBoxMenuItemImplementation::_serializationHelperMethod () protected
Definition at line 138 of file SuiListBoxMenuItem.cpp.
Referenced by _initializeImplementation().
void SuiListBoxMenuItemImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 97 of file SuiListBoxMenuItem.cpp.
References _this.
Referenced by server::zone::objects::player::sui::listbox::SuiListBoxMenuItem::SuiListBoxMenuItem().
void SuiListBoxMenuItemImplementation::finalize () protected
Definition at line 86 of file SuiListBoxMenuItem.cpp.
unsigned long long SuiListBoxMenuItemImplementation::getObjectID ()
Definition at line 223 of file SuiListBoxMenuItem.cpp.
References objectID.
Referenced by server::zone::objects::player::sui::listbox::SuiListBoxMenuItem::getObjectID().
String SuiListBoxMenuItemImplementation::getOptionName ()
Definition at line 228 of file SuiListBoxMenuItem.cpp.
References optionName.
Referenced by server::zone::objects::player::sui::listbox::SuiListBoxMenuItem::getOptionName().
void SuiListBoxMenuItemImplementation::lock (bool doLock = true) protected
Definition at line 110 of file SuiListBoxMenuItem.cpp.
References _this.
void SuiListBoxMenuItemImplementation::lock (ManagedObject * obj) protected
Definition at line 114 of file SuiListBoxMenuItem.cpp.
References _this.
SuiListBoxMenuItemImplementation::operator const SuiListBoxMenuItem * ()
Definition at line 106 of file SuiListBoxMenuItem.cpp.
void SuiListBoxMenuItemImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 145 of file SuiListBoxMenuItem.cpp.
References readObjectMember().
bool SuiListBoxMenuItemImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 164 of file SuiListBoxMenuItem.cpp.
References objectID, and optionName.
Referenced by readObject().
void SuiListBoxMenuItemImplementation::rlock (bool doLock = true) protected
Definition at line 118 of file SuiListBoxMenuItem.cpp.
References _this.
void SuiListBoxMenuItemImplementation::runlock (bool doLock = true) protected
Definition at line 134 of file SuiListBoxMenuItem.cpp.
References _this.
void SuiListBoxMenuItemImplementation::unlock (bool doLock = true) protected
Definition at line 130 of file SuiListBoxMenuItem.cpp.
References _this.
void SuiListBoxMenuItemImplementation::wlock (bool doLock = true) protected
Definition at line 122 of file SuiListBoxMenuItem.cpp.
References _this.
void SuiListBoxMenuItemImplementation::wlock (ManagedObject * obj) protected
Definition at line 126 of file SuiListBoxMenuItem.cpp.
References _this.
void SuiListBoxMenuItemImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 182 of file SuiListBoxMenuItem.cpp.
References writeObjectMembers().
int SuiListBoxMenuItemImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 189 of file SuiListBoxMenuItem.cpp.
References objectID, and optionName.
Referenced by writeObject().
Friends And Related Function Documentation
friend class SuiListBoxMenuItem friend
Definition at line 125 of file SuiListBoxMenuItem.h.
Member Data Documentation
WeakReference<SuiListBoxMenuItem*> server::zone::objects::player::sui::listbox::SuiListBoxMenuItemImplementation::_this
Definition at line 91 of file SuiListBoxMenuItem.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
unsigned long long server::zone::objects::player::sui::listbox::SuiListBoxMenuItemImplementation::objectID protected
Definition at line 80 of file SuiListBoxMenuItem.h.
Referenced by getObjectID(), readObjectMember(), SuiListBoxMenuItemImplementation(), and writeObjectMembers().
String server::zone::objects::player::sui::listbox::SuiListBoxMenuItemImplementation::optionName protected
Definition at line 78 of file SuiListBoxMenuItem.h.
Referenced by getOptionName(), readObjectMember(), SuiListBoxMenuItemImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/listbox/SuiListBoxMenuItem.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/listbox/SuiListBoxMenuItem.cpp