Core3: server::zone::managers::creature::CreatureManagerAdapter Class Reference
server::zone::managers::creature::CreatureManagerAdapter Class Reference
#include <CreatureManager.h>
Public Member Functions
CreatureManagerAdapter (CreatureManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initialize ()
TangibleObject * spawnLair (unsigned int lairTemplate, int difficulty, float x, float z, float y, unsigned int faction)
CreatureObject * spawnCreatureWithAi (unsigned int templateCRC, float x, float z, float y, SceneObject *cell, bool persistent)
CreatureObject * spawnCreatureWithLevel (unsigned int mobileTemplateCRC, int level, float x, float z, float y, unsigned long long parentID)
CreatureObject * spawnCreature (unsigned int templateCRC, float x, float z, float y, unsigned long long parentID)
CreatureObject * spawnCreature (unsigned int templateCRC, unsigned int objectCRC, float x, float z, float y, unsigned long long parentID, bool persistent)
CreatureObject * createCreature (unsigned int templateCRC, bool persistent, unsigned int mobileTemplate)
void placeCreature (CreatureObject *creature, float x, float z, float y, unsigned long long parentID)
String getTemplateToSpawn (unsigned int templateCRC)
void loadSpawnAreas ()
void loadAiTemplates ()
void loadSingleSpawns ()
void loadTrainers ()
void loadMissionSpawns ()
void loadInformants ()
void spawnRandomCreaturesAround (SceneObject *creature)
void spawnRandomCreature (int number, float x, float z, float y, unsigned long long parentID)
void harvest (Creature *creature, CreatureObject *player, int selectedID)
void milk (Creature *creature, CreatureObject *player)
void sample (Creature *creature, CreatureObject *player)
void addToReservePool (AiAgent *agent)
int getSpawnedRandomCreatures ()
SpawnArea * getSpawnArea (const String &areaname)
bool addWearableItem (CreatureObject *creature, TangibleObject *clothing)
Public Member Functions inherited from server::zone::manager::ZoneManagerAdapter
ZoneManagerAdapter (ZoneManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setZoneProcessor (ZoneProcessServer *server)
Detailed Description
Definition at line 472 of file CreatureManager.h.
Constructor & Destructor Documentation
CreatureManagerAdapter::CreatureManagerAdapter (CreatureManager * impl)
Definition at line 743 of file CreatureManager.cpp.
Member Function Documentation
void CreatureManagerAdapter::addToReservePool (AiAgent * agent)
Definition at line 956 of file CreatureManager.cpp.
Referenced by invokeMethod().
bool CreatureManagerAdapter::addWearableItem (CreatureObject * creature, TangibleObject * clothing)
Definition at line 968 of file CreatureManager.cpp.
Referenced by invokeMethod().
CreatureObject * CreatureManagerAdapter::createCreature (unsigned int templateCRC, bool persistent, unsigned int mobileTemplate)
Definition at line 900 of file CreatureManager.cpp.
Referenced by invokeMethod().
SpawnArea * CreatureManagerAdapter::getSpawnArea (const String & areaname)
Definition at line 964 of file CreatureManager.cpp.
Referenced by invokeMethod().
int CreatureManagerAdapter::getSpawnedRandomCreatures ()
Definition at line 960 of file CreatureManager.cpp.
Referenced by invokeMethod().
String CreatureManagerAdapter::getTemplateToSpawn (unsigned int templateCRC)
Definition at line 908 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::harvest (Creature * creature, CreatureObject * player, int selectedID)
Definition at line 944 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::initialize ()
Definition at line 876 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 746 of file CreatureManager.cpp.
References addToReservePool(), addWearableItem(), createCreature(), getSpawnArea(), getSpawnedRandomCreatures(), getTemplateToSpawn(), harvest(), initialize(), loadAiTemplates(), loadInformants(), loadMissionSpawns(), loadSingleSpawns(), loadSpawnAreas(), loadTrainers(), milk(), placeCreature(), RPC_ADDTORESERVEPOOL__AIAGENT_, RPC_ADDWEARABLEITEM__CREATUREOBJECT_TANGIBLEOBJECT_, RPC_CREATECREATURE__INT_BOOL_INT_, RPC_GETSPAWNAREA__STRING_, RPC_GETSPAWNEDRANDOMCREATURES__, RPC_GETTEMPLATETOSPAWN__INT_, RPC_HARVEST__CREATURE_CREATUREOBJECT_INT_, RPC_INITIALIZE__, RPC_LOADAITEMPLATES__, RPC_LOADINFORMANTS__, RPC_LOADMISSIONSPAWNS__, RPC_LOADSINGLESPAWNS__, RPC_LOADSPAWNAREAS__, RPC_LOADTRAINERS__, RPC_MILK__CREATURE_CREATUREOBJECT_, RPC_PLACECREATURE__CREATUREOBJECT_FLOAT_FLOAT_FLOAT_LONG_, RPC_SAMPLE__CREATURE_CREATUREOBJECT_, RPC_SPAWNCREATURE__INT_FLOAT_FLOAT_FLOAT_LONG_, RPC_SPAWNCREATURE__INT_INT_FLOAT_FLOAT_FLOAT_LONG_BOOL_, RPC_SPAWNCREATUREWITHAI__INT_FLOAT_FLOAT_FLOAT_SCENEOBJECT_BOOL_, RPC_SPAWNCREATUREWITHLEVEL__INT_INT_FLOAT_FLOAT_FLOAT_LONG_, RPC_SPAWNLAIR__INT_INT_FLOAT_FLOAT_FLOAT_INT_, RPC_SPAWNRANDOMCREATURE__INT_FLOAT_FLOAT_FLOAT_LONG_, RPC_SPAWNRANDOMCREATURESAROUND__SCENEOBJECT_, sample(), spawnCreature(), spawnCreatureWithAi(), spawnCreatureWithLevel(), spawnLair(), spawnRandomCreature(), and spawnRandomCreaturesAround().
void CreatureManagerAdapter::loadAiTemplates ()
Definition at line 916 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::loadInformants ()
Definition at line 932 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::loadMissionSpawns ()
Definition at line 928 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::loadSingleSpawns ()
Definition at line 920 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::loadSpawnAreas ()
Definition at line 912 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::loadTrainers ()
Definition at line 924 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::milk (Creature * creature, CreatureObject * player)
Definition at line 948 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::placeCreature (CreatureObject * creature, float x, float z, float y, unsigned long long parentID)
Definition at line 904 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::sample (Creature * creature, CreatureObject * player)
Definition at line 952 of file CreatureManager.cpp.
Referenced by invokeMethod().
CreatureObject * CreatureManagerAdapter::spawnCreature (unsigned int templateCRC, float x, float z, float y, unsigned long long parentID)
Definition at line 892 of file CreatureManager.cpp.
Referenced by invokeMethod().
CreatureObject * CreatureManagerAdapter::spawnCreature (unsigned int templateCRC, unsigned int objectCRC, float x, float z, float y, unsigned long long parentID, bool persistent)
Definition at line 896 of file CreatureManager.cpp.
CreatureObject * CreatureManagerAdapter::spawnCreatureWithAi (unsigned int templateCRC, float x, float z, float y, SceneObject * cell, bool persistent)
Definition at line 884 of file CreatureManager.cpp.
Referenced by invokeMethod().
CreatureObject * CreatureManagerAdapter::spawnCreatureWithLevel (unsigned int mobileTemplateCRC, int level, float x, float z, float y, unsigned long long parentID)
Definition at line 888 of file CreatureManager.cpp.
Referenced by invokeMethod().
TangibleObject * CreatureManagerAdapter::spawnLair (unsigned int lairTemplate, int difficulty, float x, float z, float y, unsigned int faction)
Definition at line 880 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::spawnRandomCreature (int number, float x, float z, float y, unsigned long long parentID)
Definition at line 940 of file CreatureManager.cpp.
Referenced by invokeMethod().
void CreatureManagerAdapter::spawnRandomCreaturesAround (SceneObject * creature)
Definition at line 936 of file CreatureManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/CreatureManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/CreatureManager.cpp