Core3: server::login::account::AccountImplementation Class Reference
server::login::account::AccountImplementation Class Reference
#include <Account.h>
Public Member Functions
AccountImplementation ()
AccountImplementation (DummyConstructorParameter *param)
void setActive (bool act)
void setAccountID (unsigned int accountid)
void setStationID (unsigned int stationid)
void setAdminLevel (unsigned int adminlvl)
void setUsername (const String &usern)
void setBanExpires (unsigned int expires)
void setBanReason (const String &reason)
void setSalt (const String &s)
void setBanAdmin (unsigned int value)
unsigned int getBanAdmin ()
void setTimeCreated (unsigned int seconds)
bool isActive ()
unsigned int getAccountID ()
unsigned int getStationID ()
unsigned int getAdminLevel ()
String getUsername ()
String getSalt ()
unsigned int getTimeCreated ()
void updateFromDatabase ()
void updateAccount ()
void updateCharacters ()
void updateGalaxyBans ()
unsigned int getBanExpires ()
String getBanReason ()
bool isBanned ()
CharacterList * getCharacterList ()
GalaxyBanEntry * getGalaxyBan (unsigned const int galaxy)
CharacterListEntry * getCharacterBan (unsigned const int galaxy, const String &name)
operator const Account * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< Account * > _this
Protected Member Functions
virtual ~AccountImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
bool active
String username
String salt
unsigned int accountID
unsigned int stationID
unsigned int adminLevel
unsigned int created
Reference< CharacterList * > characterList
VectorMap< unsigned int,
Reference< GalaxyBanEntry * > > galaxyBans
unsigned int banExpires
String banReason
unsigned int banAdmin
Friends
class Account
Detailed Description
Definition at line 139 of file Account.h.
Constructor & Destructor Documentation
AccountImplementation::AccountImplementation ()
Definition at line 51 of file AccountImplementation.cpp.
AccountImplementation::AccountImplementation (DummyConstructorParameter * param)
Definition at line 419 of file Account.cpp.
References _initializeImplementation().
AccountImplementation::~AccountImplementation () protected virtual
Definition at line 424 of file Account.cpp.
Member Function Documentation
DistributedObjectStub * AccountImplementation::_getStub ()
Definition at line 444 of file Account.cpp.
References _this.
void AccountImplementation::_initializeImplementation () protected
Definition at line 431 of file Account.cpp.
References _serializationHelperMethod(), and _this.
Referenced by AccountImplementation().
void AccountImplementation::_serializationHelperMethod () protected
Definition at line 480 of file Account.cpp.
Referenced by _initializeImplementation().
void AccountImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 439 of file Account.cpp.
References _this.
Referenced by server::login::account::Account::Account().
void AccountImplementation::finalize () protected
Definition at line 428 of file Account.cpp.
unsigned int AccountImplementation::getAccountID ()
Definition at line 593 of file Account.cpp.
References accountID.
Referenced by server::login::account::Account::getAccountID(), updateCharacters(), and updateGalaxyBans().
unsigned int AccountImplementation::getAdminLevel ()
Definition at line 603 of file Account.cpp.
References adminLevel.
Referenced by server::login::account::Account::getAdminLevel().
unsigned int AccountImplementation::getBanAdmin ()
Definition at line 578 of file Account.cpp.
References banAdmin.
Referenced by server::login::account::Account::getBanAdmin().
unsigned int AccountImplementation::getBanExpires ()
Definition at line 623 of file Account.cpp.
References banExpires.
Referenced by server::login::account::Account::getBanExpires().
String AccountImplementation::getBanReason ()
Definition at line 628 of file Account.cpp.
References banReason.
Referenced by server::login::account::Account::getBanReason().
CharacterListEntry * AccountImplementation::getCharacterBan (unsigned const int galaxy, const String & name)
Definition at line 129 of file AccountImplementation.cpp.
References characterList, CharacterListEntry::getFirstName(), CharacterListEntry::getGalaxyID(), and CharacterListEntry::isBanned().
Referenced by server::login::account::Account::getCharacterBan().
CharacterList * AccountImplementation::getCharacterList ()
Definition at line 143 of file AccountImplementation.cpp.
References characterList.
Referenced by server::login::account::Account::getCharacterList().
GalaxyBanEntry * AccountImplementation::getGalaxyBan (unsigned const int galaxy)
Definition at line 122 of file AccountImplementation.cpp.
References galaxyBans.
Referenced by server::login::account::Account::getGalaxyBan().
String AccountImplementation::getSalt ()
Definition at line 613 of file Account.cpp.
References salt.
Referenced by server::login::account::Account::getSalt().
unsigned int AccountImplementation::getStationID ()
Definition at line 598 of file Account.cpp.
References stationID.
Referenced by server::login::account::Account::getStationID().
unsigned int AccountImplementation::getTimeCreated ()
Definition at line 618 of file Account.cpp.
References created.
Referenced by server::login::account::Account::getTimeCreated().
String AccountImplementation::getUsername ()
Definition at line 608 of file Account.cpp.
References username.
Referenced by server::login::account::Account::getUsername().
bool AccountImplementation::isActive ()
Definition at line 588 of file Account.cpp.
References active.
Referenced by server::login::account::Account::isActive().
bool AccountImplementation::isBanned ()
Definition at line 118 of file AccountImplementation.cpp.
References banExpires.
Referenced by server::login::account::Account::isBanned().
void AccountImplementation::lock (bool doLock = true) protected
Definition at line 452 of file Account.cpp.
References _this.
void AccountImplementation::lock (ManagedObject * obj) protected
Definition at line 456 of file Account.cpp.
References _this.
AccountImplementation::operator const Account * ()
Definition at line 448 of file Account.cpp.
void AccountImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 487 of file Account.cpp.
References readObjectMember().
bool AccountImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 506 of file Account.cpp.
Referenced by readObject().
void AccountImplementation::rlock (bool doLock = true) protected
Definition at line 460 of file Account.cpp.
References _this.
void AccountImplementation::runlock (bool doLock = true) protected
Definition at line 476 of file Account.cpp.
References _this.
void AccountImplementation::setAccountID (unsigned int accountid)
Definition at line 538 of file Account.cpp.
References accountID.
Referenced by server::login::account::Account::setAccountID().
void AccountImplementation::setActive (bool act)
Definition at line 533 of file Account.cpp.
References active.
Referenced by server::login::account::Account::setActive(), and updateAccount().
void AccountImplementation::setAdminLevel (unsigned int adminlvl)
Definition at line 548 of file Account.cpp.
References adminLevel.
Referenced by server::login::account::Account::setAdminLevel(), and updateAccount().
void AccountImplementation::setBanAdmin (unsigned int value)
Definition at line 573 of file Account.cpp.
References banAdmin.
Referenced by server::login::account::Account::setBanAdmin(), and updateAccount().
void AccountImplementation::setBanExpires (unsigned int expires)
Definition at line 558 of file Account.cpp.
References banExpires.
Referenced by server::login::account::Account::setBanExpires(), and updateAccount().
void AccountImplementation::setBanReason (const String & reason)
Definition at line 563 of file Account.cpp.
References banReason.
Referenced by server::login::account::Account::setBanReason(), and updateAccount().
void AccountImplementation::setSalt (const String & s)
Definition at line 568 of file Account.cpp.
References salt.
Referenced by server::login::account::Account::setSalt().
void AccountImplementation::setStationID (unsigned int stationid)
Definition at line 543 of file Account.cpp.
References stationID.
Referenced by server::login::account::Account::setStationID().
void AccountImplementation::setTimeCreated (unsigned int seconds)
Definition at line 583 of file Account.cpp.
References created.
Referenced by server::login::account::Account::setTimeCreated().
void AccountImplementation::setUsername (const String & usern)
Definition at line 553 of file Account.cpp.
References username.
Referenced by server::login::account::Account::setUsername().
void AccountImplementation::unlock (bool doLock = true) protected
Definition at line 472 of file Account.cpp.
References _this.
void AccountImplementation::updateAccount ()
Definition at line 62 of file AccountImplementation.cpp.
References accountID, ServerDatabase::instance(), setActive(), setAdminLevel(), setBanAdmin(), setBanExpires(), and setBanReason().
Referenced by server::login::account::Account::updateAccount(), and updateFromDatabase().
void AccountImplementation::updateCharacters ()
Definition at line 86 of file AccountImplementation.cpp.
References characterList, and getAccountID().
Referenced by server::login::account::Account::updateCharacters(), and updateFromDatabase().
void AccountImplementation::updateFromDatabase ()
Definition at line 54 of file AccountImplementation.cpp.
References updateAccount(), updateCharacters(), and updateGalaxyBans().
Referenced by server::login::account::Account::updateFromDatabase().
void AccountImplementation::updateGalaxyBans ()
Definition at line 90 of file AccountImplementation.cpp.
References galaxyBans, getAccountID(), and ServerDatabase::instance().
Referenced by updateFromDatabase(), and server::login::account::Account::updateGalaxyBans().
void AccountImplementation::wlock (bool doLock = true) protected
Definition at line 464 of file Account.cpp.
References _this.
void AccountImplementation::wlock (ManagedObject * obj) protected
Definition at line 468 of file Account.cpp.
References _this.
void AccountImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 516 of file Account.cpp.
References writeObjectMembers().
int AccountImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 523 of file Account.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class Account friend
Definition at line 260 of file Account.h.
Member Data Documentation
WeakReference<Account*> server::login::account::AccountImplementation::_this
Definition at line 226 of file Account.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
unsigned int server::login::account::AccountImplementation::accountID protected
Definition at line 147 of file Account.h.
Referenced by getAccountID(), setAccountID(), and updateAccount().
bool server::login::account::AccountImplementation::active protected
Definition at line 141 of file Account.h.
Referenced by isActive(), and setActive().
unsigned int server::login::account::AccountImplementation::adminLevel protected
Definition at line 151 of file Account.h.
Referenced by getAdminLevel(), and setAdminLevel().
unsigned int server::login::account::AccountImplementation::banAdmin protected
Definition at line 163 of file Account.h.
Referenced by getBanAdmin(), and setBanAdmin().
unsigned int server::login::account::AccountImplementation::banExpires protected
Definition at line 159 of file Account.h.
Referenced by getBanExpires(), isBanned(), and setBanExpires().
String server::login::account::AccountImplementation::banReason protected
Definition at line 161 of file Account.h.
Referenced by getBanReason(), and setBanReason().
Reference<CharacterList* > server::login::account::AccountImplementation::characterList protected
Definition at line 155 of file Account.h.
Referenced by getCharacterBan(), getCharacterList(), and updateCharacters().
unsigned int server::login::account::AccountImplementation::created protected
Definition at line 153 of file Account.h.
Referenced by getTimeCreated(), and setTimeCreated().
VectorMap<unsigned int, Reference<GalaxyBanEntry*> > server::login::account::AccountImplementation::galaxyBans protected
Definition at line 157 of file Account.h.
Referenced by getGalaxyBan(), and updateGalaxyBans().
String server::login::account::AccountImplementation::salt protected
Definition at line 145 of file Account.h.
Referenced by getSalt(), and setSalt().
unsigned int server::login::account::AccountImplementation::stationID protected
Definition at line 149 of file Account.h.
Referenced by getStationID(), and setStationID().
String server::login::account::AccountImplementation::username protected
Definition at line 143 of file Account.h.
Referenced by getUsername(), and setUsername().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/account/Account.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/account/Account.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/account/AccountImplementation.cpp