Core3: WeaponObjectMenuComponent Class Reference
WeaponObjectMenuComponent Class Reference
#include <WeaponObjectMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file WeaponObjectMenuComponent.h.
Member Function Documentation
void WeaponObjectMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from TangibleObjectMenuComponent.
Reimplemented in FireHeavyWeaponMenuComponent, and ThrowGrenadeMenuComponent.
Definition at line 18 of file WeaponObjectMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), TangibleObjectMenuComponent::fillObjectMenuResponse(), and server::zone::objects::scene::SceneObject::isTangibleObject().
Referenced by ThrowGrenadeMenuComponent::fillObjectMenuResponse(), and FireHeavyWeaponMenuComponent::fillObjectMenuResponse().
int WeaponObjectMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from TangibleObjectMenuComponent.
Reimplemented in FireHeavyWeaponMenuComponent, and ThrowGrenadeMenuComponent.
Definition at line 42 of file WeaponObjectMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getSlottedObject(), TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setTT(), and SessionFacadeType::SLICING.
Referenced by ThrowGrenadeMenuComponent::handleObjectMenuSelect(), and FireHeavyWeaponMenuComponent::handleObjectMenuSelect().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/WeaponObjectMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/WeaponObjectMenuComponent.cpp