Core3: ClientCreateCharacterCallback Class Reference
ClientCreateCharacterCallback Class Reference
#include <ClientCreateCharacterCallback.h>
Public Member Functions
ClientCreateCharacterCallback (ZoneClientSession *client, ZoneProcessServer *server)
void parse (Message *message)
void run ()
void getRaceFile (String &file)
void getCustomizationString (String &customizationString)
void getLocation (String &location)
void getHairObject (String &hair)
void getHairCustomization (String &hairCustomization)
void getSkill (String &profession)
float getHeight ()
void getBiography (UnicodeString &biography)
bool getTutorialFlag ()
void getCharacterName (UnicodeString &name)
int getSpecies ()
Public Member Functions inherited from server::zone::packets::MessageCallback
MessageCallback (ZoneClientSession *client, ZoneProcessServer *server)
virtual ~MessageCallback ()
int getTaskQueue ()
bool parseMessage (Message *packet)
ZoneClientSession * getClient ()
ZoneProcessServer * getServer ()
Private Attributes
String customization
UnicodeString characterName
String racefile
String location
String hairobj
String haircust
String profession
int species
float height
UnicodeString bio
uint8 tutflag
Additional Inherited Members
Protected Attributes inherited from server::zone::packets::MessageCallback
Reference< ZoneClientSession * > client
ManagedReference
< ZoneProcessServer * > server
int taskqueue
Detailed Description
Definition at line 13 of file ClientCreateCharacterCallback.h.
Constructor & Destructor Documentation
ClientCreateCharacterCallback::ClientCreateCharacterCallback (ZoneClientSession * client, ZoneProcessServer * server) inline
Definition at line 31 of file ClientCreateCharacterCallback.h.
References server::zone::packets::MessageCallback::taskqueue.
Member Function Documentation
void ClientCreateCharacterCallback::getBiography (UnicodeString & biography) inline
Definition at line 70 of file ClientCreateCharacterCallback.h.
References bio.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
void ClientCreateCharacterCallback::getCharacterName (UnicodeString & name) inline
Definition at line 81 of file ClientCreateCharacterCallback.h.
References characterName.
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkPlayerName(), and server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
void ClientCreateCharacterCallback::getCustomizationString (String & customizationString) inline
Definition at line 46 of file ClientCreateCharacterCallback.h.
References customization.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
void ClientCreateCharacterCallback::getHairCustomization (String & hairCustomization) inline
Definition at line 58 of file ClientCreateCharacterCallback.h.
References haircust.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
void ClientCreateCharacterCallback::getHairObject (String & hair) inline
Definition at line 54 of file ClientCreateCharacterCallback.h.
References hairobj.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
float ClientCreateCharacterCallback::getHeight () inline
Definition at line 66 of file ClientCreateCharacterCallback.h.
References height.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
void ClientCreateCharacterCallback::getLocation (String & location) inline
Definition at line 50 of file ClientCreateCharacterCallback.h.
References location.
void ClientCreateCharacterCallback::getRaceFile (String & file) inline
Definition at line 42 of file ClientCreateCharacterCallback.h.
References racefile.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
void ClientCreateCharacterCallback::getSkill (String & profession) inline
Definition at line 62 of file ClientCreateCharacterCallback.h.
References profession.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
int ClientCreateCharacterCallback::getSpecies () inline
Definition at line 85 of file ClientCreateCharacterCallback.h.
References species.
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkPlayerName().
bool ClientCreateCharacterCallback::getTutorialFlag () inline
Definition at line 74 of file ClientCreateCharacterCallback.h.
References tutflag.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter().
void ClientCreateCharacterCallback::parse (Message * message) virtual
Implements server::zone::packets::MessageCallback.
Definition at line 21 of file ClientCreateCharacterCallback.cpp.
References bio, characterName, customization, Races::getRaceID(), Races::getSpeciesID(), haircust, hairobj, height, location, profession, racefile, species, and tutflag.
void ClientCreateCharacterCallback::run ()
Definition at line 50 of file ClientCreateCharacterCallback.cpp.
References server::zone::packets::MessageCallback::client, server::zone::managers::player::PlayerManager::createPlayer(), and server::zone::packets::MessageCallback::server.
Member Data Documentation
UnicodeString ClientCreateCharacterCallback::bio private
Definition at line 27 of file ClientCreateCharacterCallback.h.
Referenced by getBiography(), and parse().
UnicodeString ClientCreateCharacterCallback::characterName private
Definition at line 16 of file ClientCreateCharacterCallback.h.
Referenced by getCharacterName(), and parse().
String ClientCreateCharacterCallback::customization private
Definition at line 14 of file ClientCreateCharacterCallback.h.
Referenced by getCustomizationString(), and parse().
String ClientCreateCharacterCallback::haircust private
Definition at line 21 of file ClientCreateCharacterCallback.h.
Referenced by getHairCustomization(), and parse().
String ClientCreateCharacterCallback::hairobj private
Definition at line 20 of file ClientCreateCharacterCallback.h.
Referenced by getHairObject(), and parse().
float ClientCreateCharacterCallback::height private
Definition at line 26 of file ClientCreateCharacterCallback.h.
Referenced by getHeight(), and parse().
String ClientCreateCharacterCallback::location private
Definition at line 19 of file ClientCreateCharacterCallback.h.
Referenced by getLocation(), and parse().
String ClientCreateCharacterCallback::profession private
Definition at line 22 of file ClientCreateCharacterCallback.h.
Referenced by getSkill(), and parse().
String ClientCreateCharacterCallback::racefile private
Definition at line 18 of file ClientCreateCharacterCallback.h.
Referenced by getRaceFile(), and parse().
int ClientCreateCharacterCallback::species private
Definition at line 24 of file ClientCreateCharacterCallback.h.
Referenced by getSpecies(), and parse().
uint8 ClientCreateCharacterCallback::tutflag private
Definition at line 28 of file ClientCreateCharacterCallback.h.
Referenced by getTutorialFlag(), and parse().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/charcreation/ClientCreateCharacterCallback.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/charcreation/ClientCreateCharacterCallback.cpp