Core3: FactionManager Class Reference
FactionManager Class Reference
#include <FactionManager.h>
Public Member Functions
FactionManager ()
void loadData ()
void awardFactionStanding (CreatureObject *player, const String &factionName)
void awardPvpFactionPoints (TangibleObject *killer, CreatureObject *destructedObject)
SortedVector< String > getEnemyFactions (const String &faction)
SortedVector< String > getAllyFactions (const String &faction)
FactionMap * getFactionMap ()
String getRankName (int idx)
int getRankCost (int rank)
int getRankDelegateRatioFrom (int rank)
int getRankDelegateRatioTo (int rank)
int getFactionPointsCap (int rank)
bool isHighestRank (int rank)
Static Public Member Functions
static int addFaction (lua_State *L)
Protected Member Functions
void loadFactionRanks ()
void loadLuaConfig ()
Private Attributes
FactionMap factionMap
FactionRanks factionRanks
Detailed Description
Definition at line 18 of file FactionManager.h.
Constructor & Destructor Documentation
FactionManager::FactionManager ()
Definition at line 13 of file FactionManager.cpp.
Member Function Documentation
int FactionManager::addFaction (lua_State * L) static
Lua Interface function that adds a faction relationship to the FactionMap.
Parameters
L The Lua State containing the data.
Definition at line 57 of file FactionManager.cpp.
References FactionMap::addFaction(), factionMap, getFactionMap(), Faction::parseAlliesFromList(), and Faction::parseEnemiesFromList().
Referenced by loadLuaConfig().
void FactionManager::awardFactionStanding (CreatureObject * player, const String & factionName)
Awards points to the player based on the faction they killed.
Precondition
: player locked
Postcondition
: player locked
Parameters
player The player receiving the faction points for the kill.
faction The string key of the faction that was killed.
Definition at line 82 of file FactionManager.cpp.
References factionMap, Faction::getAllies(), Faction::getEnemies(), and server::zone::objects::creature::CreatureObject::getPlayerObject().
Referenced by server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction().
void FactionManager::awardPvpFactionPoints (TangibleObject * killer, CreatureObject * destructedObject)
Definition at line 114 of file FactionManager.cpp.
References server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::tangible::TangibleObject::isImperial(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::tangible::TangibleObject::isRebel().
SortedVector<String> FactionManager::getAllyFactions (const String & faction)
Gets a list of ally factions to the faction passed to the method.
Parameters
faction The faction to check for enemies.
SortedVector<String> FactionManager::getEnemyFactions (const String & faction)
Gets a list of enemy factions to the faction passed to the method.
Parameters
faction The faction to check for enemies.
FactionMap * FactionManager::getFactionMap ()
Definition at line 78 of file FactionManager.cpp.
References factionMap.
Referenced by addFaction().
int FactionManager::getFactionPointsCap (int rank)
Definition at line 173 of file FactionManager.cpp.
References factionRanks, FactionRanks::getCount(), and getRankCost().
int FactionManager::getRankCost (int rank)
Definition at line 152 of file FactionManager.cpp.
References factionRanks, FactionRank::getCost(), FactionRanks::getCount(), and FactionRanks::getRank().
Referenced by getFactionPointsCap().
int FactionManager::getRankDelegateRatioFrom (int rank)
Definition at line 159 of file FactionManager.cpp.
References factionRanks, FactionRanks::getCount(), FactionRank::getDelegateRatioFrom(), and FactionRanks::getRank().
int FactionManager::getRankDelegateRatioTo (int rank)
Definition at line 166 of file FactionManager.cpp.
References factionRanks, FactionRanks::getCount(), FactionRank::getDelegateRatioTo(), and FactionRanks::getRank().
String FactionManager::getRankName (int idx)
Definition at line 145 of file FactionManager.cpp.
References factionRanks, FactionRanks::getCount(), FactionRank::getName(), and FactionRanks::getRank().
bool FactionManager::isHighestRank (int rank) inline
Definition at line 69 of file FactionManager.h.
References factionRanks, and FactionRanks::getCount().
void FactionManager::loadData ()
Loads faction configuration information from the faction manager lua file: managers/faction_manager.lua Loads faction ranks from datatable Sets up faction relationships
Definition at line 19 of file FactionManager.cpp.
References loadFactionRanks(), and loadLuaConfig().
void FactionManager::loadFactionRanks () protected
Definition at line 24 of file FactionManager.cpp.
References factionRanks, FactionRanks::getCount(), FactionRanks::readObject(), and DataTableIff::readObject().
Referenced by loadData().
void FactionManager::loadLuaConfig () protected
Definition at line 42 of file FactionManager.cpp.
References addFaction().
Referenced by loadData().
Member Data Documentation
FactionMap FactionManager::factionMap private
Definition at line 19 of file FactionManager.h.
Referenced by addFaction(), awardFactionStanding(), and getFactionMap().
FactionRanks FactionManager::factionRanks private
Definition at line 20 of file FactionManager.h.
Referenced by getFactionPointsCap(), getRankCost(), getRankDelegateRatioFrom(), getRankDelegateRatioTo(), getRankName(), isHighestRank(), and loadFactionRanks().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/faction/FactionManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/faction/FactionManager.cpp