Core3: server::zone::objects::player::sui::colorbox::SuiColorBox Class Reference
server::zone::objects::player::sui::colorbox::SuiColorBox Class Reference
#include <SuiColorBox.h>
Public Member Functions
SuiColorBox (CreatureObject *player, unsigned int windowType)
BaseMessage * generateMessage ()
String getColorPalette ()
void setColorPalette (String &pal)
bool isColorPicker ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::player::sui::SuiBox
SuiBox (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
void initialize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateMessage ()
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
bool isInputBox ()
bool isListBox ()
bool isMessageBox ()
bool isTransferBox ()
bool isBankTransferBox ()
bool isSlicingBox ()
bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
SuiColorBox (DummyConstructorParameter *param)
virtual ~SuiColorBox ()
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBox
SuiBox (DummyConstructorParameter *param)
virtual ~SuiBox ()
Friends
class SuiColorBoxHelper
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::player::sui::SuiBox
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Detailed Description
Definition at line 57 of file SuiColorBox.h.
Constructor & Destructor Documentation
SuiColorBox::SuiColorBox (CreatureObject * player, unsigned int windowType)
Definition at line 17 of file SuiColorBox.cpp.
References server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::_setStub().
SuiColorBox::SuiColorBox (DummyConstructorParameter * param) protected
Definition at line 24 of file SuiColorBox.cpp.
SuiColorBox::~SuiColorBox () protected virtual
Definition at line 28 of file SuiColorBox.cpp.
Member Function Documentation
DistributedObjectServant * SuiColorBox::_getImplementation ()
Definition at line 88 of file SuiColorBox.cpp.
Referenced by generateMessage(), getColorPalette(), isColorPicker(), and setColorPalette().
DistributedObjectServant * SuiColorBox::_getImplementationForRead ()
Definition at line 94 of file SuiColorBox.cpp.
void SuiColorBox::_setImplementation (DistributedObjectServant * servant)
Definition at line 98 of file SuiColorBox.cpp.
BaseMessage * SuiColorBox::generateMessage ()
Definition at line 33 of file SuiColorBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::generateMessage(), and RPC_GENERATEMESSAGE__.
String SuiColorBox::getColorPalette ()
Definition at line 46 of file SuiColorBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::getColorPalette(), and RPC_GETCOLORPALETTE__.
bool SuiColorBox::isColorPicker ()
Definition at line 75 of file SuiColorBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::isColorPicker(), and RPC_ISCOLORPICKER__.
void SuiColorBox::setColorPalette (String & pal)
Definition at line 61 of file SuiColorBox.cpp.
References _getImplementation(), RPC_SETCOLORPALETTE__STRING_, and server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::setColorPalette().
Friends And Related Function Documentation
friend class SuiColorBoxHelper friend
Definition at line 79 of file SuiColorBox.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/colorbox/SuiColorBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/colorbox/SuiColorBox.cpp