Core3: server::zone::objects::scene::ContainerObjectsMap Class Reference
server::zone::objects::scene::ContainerObjectsMap Class Reference
#include <ContainerObjectsMap.h>
Public Types
enum { NORMAL_LOAD = 0, DELAYED_LOAD }
Public Member Functions
ContainerObjectsMap ()
~ContainerObjectsMap ()
ContainerObjectsMap (const ContainerObjectsMap &c)
ContainerObjectsMap & operator= (const ContainerObjectsMap &c)
VectorMap< uint64,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
void notifyLoadFromDatabase ()
void loadObjects ()
void removeAll ()
void removeElementAt (int index)
bool contains (uint64 oid)
int size ()
ManagedReference< SceneObject * > get (int index)
ManagedReference< SceneObject * > get (uint64 oid)
void put (uint64 oid, SceneObject *object)
void drop (uint64 oid)
void setDelayedLoadOperationMode ()
bool hasDelayedLoadOperationMode ()
Private Member Functions
void copyData (const ContainerObjectsMap &c)
Private Attributes
int operationMode
VectorMap< uint64,
ManagedReference< SceneObject * > > containerObjects
VectorMap< uint64, uint64 > * oids
Mutex loadMutex
Detailed Description
Definition at line 19 of file ContainerObjectsMap.h.
Member Enumeration Documentation
anonymous enum
Enumerator
NORMAL_LOAD
DELAYED_LOAD
Definition at line 27 of file ContainerObjectsMap.h.
Constructor & Destructor Documentation
ContainerObjectsMap::ContainerObjectsMap ()
Definition at line 12 of file ContainerObjectsMap.cpp.
References containerObjects, NORMAL_LOAD, oids, and operationMode.
ContainerObjectsMap::~ContainerObjectsMap ()
Definition at line 28 of file ContainerObjectsMap.cpp.
References oids.
ContainerObjectsMap::ContainerObjectsMap (const ContainerObjectsMap & c)
Definition at line 19 of file ContainerObjectsMap.cpp.
References containerObjects, copyData(), NORMAL_LOAD, oids, and operationMode.
Member Function Documentation
bool ContainerObjectsMap::contains (uint64 oid)
Definition at line 160 of file ContainerObjectsMap.cpp.
References containerObjects, loadMutex, and oids.
void ContainerObjectsMap::copyData (const ContainerObjectsMap & c) private
Definition at line 35 of file ContainerObjectsMap.cpp.
References containerObjects, oids, and operationMode.
Referenced by ContainerObjectsMap(), and operator=().
void ContainerObjectsMap::drop (uint64 oid)
Definition at line 178 of file ContainerObjectsMap.cpp.
References containerObjects, loadMutex, and oids.
ManagedReference< SceneObject * > ContainerObjectsMap::get (int index)
Definition at line 117 of file ContainerObjectsMap.cpp.
References containerObjects, and loadObjects().
Referenced by server::zone::objects::scene::SceneObjectImplementation::getContainedObjectsRecursive(), server::zone::objects::scene::SceneObjectImplementation::getContainerObjectRecursive(), server::zone::objects::scene::SceneObjectImplementation::getCountableObjectsRecursive(), and server::zone::objects::scene::SceneObjectImplementation::notifyLoadFromDatabase().
ManagedReference< SceneObject * > ContainerObjectsMap::get (uint64 oid)
Definition at line 123 of file ContainerObjectsMap.cpp.
References containerObjects, and loadObjects().
VectorMap< uint64, ManagedReference< SceneObject * > > * ContainerObjectsMap::getContainerObjects ()
Definition at line 111 of file ContainerObjectsMap.cpp.
References containerObjects, and loadObjects().
bool server::zone::objects::scene::ContainerObjectsMap::hasDelayedLoadOperationMode () inline
Definition at line 64 of file ContainerObjectsMap.h.
References DELAYED_LOAD, and operationMode.
Referenced by server::zone::objects::scene::SceneObjectImplementation::notifyLoadFromDatabase().
void ContainerObjectsMap::loadObjects ()
Definition at line 58 of file ContainerObjectsMap.cpp.
References containerObjects, loadMutex, and oids.
Referenced by get(), getContainerObjects(), put(), and size().
void ContainerObjectsMap::notifyLoadFromDatabase ()
Definition at line 82 of file ContainerObjectsMap.cpp.
ContainerObjectsMap & ContainerObjectsMap::operator= (const ContainerObjectsMap & c)
Definition at line 49 of file ContainerObjectsMap.cpp.
References copyData().
bool ContainerObjectsMap::parseFromBinaryStream (ObjectInputStream * stream)
Definition at line 95 of file ContainerObjectsMap.cpp.
References containerObjects, DELAYED_LOAD, NORMAL_LOAD, oids, and operationMode.
void ContainerObjectsMap::put (uint64 oid, SceneObject * object)
Definition at line 129 of file ContainerObjectsMap.cpp.
References containerObjects, and loadObjects().
void ContainerObjectsMap::removeAll ()
Definition at line 169 of file ContainerObjectsMap.cpp.
References containerObjects, loadMutex, and oids.
Referenced by server::zone::objects::cell::CellObjectImplementation::notifyLoadFromDatabase().
void ContainerObjectsMap::removeElementAt (int index)
Definition at line 135 of file ContainerObjectsMap.cpp.
References containerObjects, loadMutex, and oids.
void server::zone::objects::scene::ContainerObjectsMap::setDelayedLoadOperationMode () inline
Definition at line 60 of file ContainerObjectsMap.h.
References DELAYED_LOAD, and operationMode.
Referenced by server::zone::objects::tangible::ContainerImplementation::loadTemplateData().
int ContainerObjectsMap::size ()
Definition at line 144 of file ContainerObjectsMap.cpp.
References containerObjects, and loadObjects().
Referenced by server::zone::objects::scene::SceneObjectImplementation::getContainedObjectsRecursive(), server::zone::objects::scene::SceneObjectImplementation::getContainerObjectRecursive(), server::zone::objects::scene::SceneObjectImplementation::getCountableObjectsRecursive(), and server::zone::objects::scene::SceneObjectImplementation::notifyLoadFromDatabase().
bool ContainerObjectsMap::toBinaryStream (ObjectOutputStream * stream)
Definition at line 86 of file ContainerObjectsMap.cpp.
References containerObjects, loadMutex, and oids.
Member Data Documentation
VectorMap<uint64, ManagedReference<SceneObject*> > server::zone::objects::scene::ContainerObjectsMap::containerObjects private
Definition at line 22 of file ContainerObjectsMap.h.
Referenced by ContainerObjectsMap(), contains(), copyData(), drop(), get(), getContainerObjects(), loadObjects(), parseFromBinaryStream(), put(), removeAll(), removeElementAt(), size(), and toBinaryStream().
Mutex server::zone::objects::scene::ContainerObjectsMap::loadMutex private
Definition at line 25 of file ContainerObjectsMap.h.
Referenced by contains(), drop(), loadObjects(), removeAll(), removeElementAt(), and toBinaryStream().
VectorMap<uint64, uint64>* server::zone::objects::scene::ContainerObjectsMap::oids private
Definition at line 23 of file ContainerObjectsMap.h.
Referenced by ContainerObjectsMap(), contains(), copyData(), drop(), loadObjects(), parseFromBinaryStream(), removeAll(), removeElementAt(), toBinaryStream(), and ~ContainerObjectsMap().
int server::zone::objects::scene::ContainerObjectsMap::operationMode private
Definition at line 20 of file ContainerObjectsMap.h.
Referenced by ContainerObjectsMap(), copyData(), hasDelayedLoadOperationMode(), parseFromBinaryStream(), and setDelayedLoadOperationMode().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/ContainerObjectsMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/ContainerObjectsMap.cpp