Core3: server::zone::ZoneProcessServer Class Reference
server::zone::ZoneProcessServer Class Reference
#include <ZoneProcessServer.h>
Public Member Functions
ZoneProcessServer (ZoneServer *server)
void initialize ()
VendorManager * getVendorManager ()
ZoneServer * getZoneServer ()
ZonePacketHandler * getPacketHandler ()
SkillManager * getSkillManager ()
ObjectController * getObjectController ()
PlayerManager * getPlayerManager ()
NameManager * getNameManager ()
HolocronManager * getHolocronManager ()
ChatManager * getChatManager ()
SuiManager * getSuiManager ()
FishingManager * getFishingManager ()
GamblingManager * getGamblingManager ()
ForageManager * getForageManager ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ZoneProcessServer (DummyConstructorParameter *param)
virtual ~ZoneProcessServer ()
Friends
class ZoneProcessServerHelper
Detailed Description
Definition at line 219 of file ZoneProcessServer.h.
Constructor & Destructor Documentation
ZoneProcessServer::ZoneProcessServer (ZoneServer * server)
Definition at line 43 of file ZoneProcessServer.cpp.
References server::zone::ZoneProcessServerImplementation::_setStub().
ZoneProcessServer::ZoneProcessServer (DummyConstructorParameter * param) protected
Definition at line 50 of file ZoneProcessServer.cpp.
ZoneProcessServer::~ZoneProcessServer () protected virtual
Definition at line 54 of file ZoneProcessServer.cpp.
Member Function Documentation
DistributedObjectServant * ZoneProcessServer::_getImplementation ()
Definition at line 213 of file ZoneProcessServer.cpp.
Referenced by getChatManager(), getFishingManager(), getForageManager(), getGamblingManager(), getHolocronManager(), getNameManager(), getObjectController(), getPacketHandler(), getPlayerManager(), getSkillManager(), getSuiManager(), getVendorManager(), getZoneServer(), and initialize().
DistributedObjectServant * ZoneProcessServer::_getImplementationForRead ()
Definition at line 219 of file ZoneProcessServer.cpp.
void ZoneProcessServer::_setImplementation (DistributedObjectServant * servant)
Definition at line 223 of file ZoneProcessServer.cpp.
ChatManager * ZoneProcessServer::getChatManager ()
Definition at line 152 of file ZoneProcessServer.cpp.
References _getImplementation(), server::zone::ZoneProcessServerImplementation::getChatManager(), and RPC_GETCHATMANAGER__.
Referenced by GiveItemCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), and SquadLeaderCommand::shoutCommand().
FishingManager * ZoneProcessServer::getFishingManager ()
Definition at line 174 of file ZoneProcessServer.cpp.
References _getImplementation(), server::zone::ZoneProcessServerImplementation::getFishingManager(), and RPC_GETFISHINGMANAGER__.
Referenced by FishCommand::doQueueCommand().
ForageManager * ZoneProcessServer::getForageManager ()
Definition at line 200 of file ZoneProcessServer.cpp.
References _getImplementation(), server::zone::ZoneProcessServerImplementation::getForageManager(), and RPC_GETFORAGEMANAGER__.
Referenced by ForageCommand::doQueueCommand(), MedicalForageCommand::doQueueCommand(), ShellfishHarvesterMenuComponent::handleObjectMenuSelect(), and LairMenuComponent::handleObjectMenuSelect().
GamblingManager * ZoneProcessServer::getGamblingManager ()
Definition at line 187 of file ZoneProcessServer.cpp.
References _getImplementation(), server::zone::ZoneProcessServerImplementation::getGamblingManager(), and RPC_GETGAMBLINGMANAGER__.
Referenced by BetCommand::doQueueCommand(), GamblingSlotSuiCallback::run(), and GamblingRouletteSuiCallback::run().
HolocronManager * ZoneProcessServer::getHolocronManager ()
Definition at line 143 of file ZoneProcessServer.cpp.
References _getImplementation(), and server::zone::ZoneProcessServerImplementation::getHolocronManager().
NameManager * ZoneProcessServer::getNameManager ()
Definition at line 134 of file ZoneProcessServer.cpp.
References _getImplementation(), and server::zone::ZoneProcessServerImplementation::getNameManager().
Referenced by NameStructureCommand::doQueueCommand().
ObjectController * ZoneProcessServer::getObjectController ()
Definition at line 112 of file ZoneProcessServer.cpp.
References _getImplementation(), and server::zone::ZoneProcessServerImplementation::getObjectController().
ZonePacketHandler * ZoneProcessServer::getPacketHandler ()
Definition at line 94 of file ZoneProcessServer.cpp.
References _getImplementation(), and server::zone::ZoneProcessServerImplementation::getPacketHandler().
PlayerManager * ZoneProcessServer::getPlayerManager ()
Definition at line 121 of file ZoneProcessServer.cpp.
References _getImplementation(), server::zone::ZoneProcessServerImplementation::getPlayerManager(), and RPC_GETPLAYERMANAGER__.
Referenced by ForceCureDiseaseCommand::canPerformSkill(), ForceCurePoisonCommand::canPerformSkill(), StopBleedingCommand::canPerformSkill(), HealStatesOtherCommand::canPerformSkill(), HealAllOther1Command::canPerformSkill(), HealAllOther2Command::canPerformSkill(), HealHealthWoundOther1Command::canPerformSkill(), HealHealthWoundOther2Command::canPerformSkill(), HealMindWoundOther1Command::canPerformSkill(), HealMindWoundOther2Command::canPerformSkill(), HealActionWoundOther1Command::canPerformSkill(), HealActionWoundOther2Command::canPerformSkill(), CurePackCommand::canPerformSkill(), TotalHealOtherCommand::canPerformSkill(), DotPackCommand::checkTarget(), ForceCurePoisonCommand::checkTarget(), HealStatesOtherCommand::checkTarget(), StopBleedingCommand::checkTarget(), ForceCureDiseaseCommand::checkTarget(), HealAllOther1Command::checkTarget(), HealAllOther2Command::checkTarget(), HealHealthWoundOther2Command::checkTarget(), HealMindWoundOther1Command::checkTarget(), HealMindWoundOther2Command::checkTarget(), HealActionWoundOther1Command::checkTarget(), HealActionWoundOther2Command::checkTarget(), HealHealthWoundOther1Command::checkTarget(), TotalHealOtherCommand::checkTarget(), CurePackCommand::checkTarget(), HealDamageCommand::checkTarget(), HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), SniperShotCommand::doQueueCommand(), AddPowerCommand::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), StopwatchingCommand::doQueueCommand(), StoplisteningCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), DismountCommand::doQueueCommand(), TeleportToCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), WatchCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), ListenCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), and server::zone::managers::holocron::HolocronManager::getReporterId().
SkillManager * ZoneProcessServer::getSkillManager ()
Definition at line 103 of file ZoneProcessServer.cpp.
References _getImplementation(), and server::zone::ZoneProcessServerImplementation::getSkillManager().
Referenced by SetGodModeCommand::doQueueCommand().
SuiManager * ZoneProcessServer::getSuiManager ()
Definition at line 165 of file ZoneProcessServer.cpp.
References _getImplementation(), and server::zone::ZoneProcessServerImplementation::getSuiManager().
VendorManager * ZoneProcessServer::getVendorManager ()
Definition at line 72 of file ZoneProcessServer.cpp.
References _getImplementation(), and server::zone::ZoneProcessServerImplementation::getVendorManager().
ZoneServer * ZoneProcessServer::getZoneServer ()
Definition at line 81 of file ZoneProcessServer.cpp.
References _getImplementation(), server::zone::ZoneProcessServerImplementation::getZoneServer(), and RPC_GETZONESERVER__.
Referenced by DotPackCommand::awardXp(), HealStateCommand::awardXp(), HealWoundCommand::awardXp(), TendCommand::awardXp(), CurePackCommand::awardXp(), RevivePlayerCommand::awardXp(), HealEnhanceCommand::awardXp(), HealDamageCommand::awardXp(), HealDamageCommand::doAreaMedicActionTarget(), HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), FireHeavyWeaponCommand::doQueueCommand(), SniperShotCommand::doQueueCommand(), ThrowGrenadeCommand::doQueueCommand(), Intimidate1Command::doQueueCommand(), Intimidate2Command::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), ForceWeaken1Command::doQueueCommand(), KillCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), LootCommand::doQueueCommand(), ForceWeaken2Command::doQueueCommand(), BroadcastCommand::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), GmCreateClassResourceCommand::doQueueCommand(), GmCreateSpecificResourceCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), RequestBiographyCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), AddPowerCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), Warcry1Command::doQueueCommand(), Warcry2Command::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), ForceChokeCommand::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), MeditateCommand::doQueueCommand(), MountCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), HarvesterDeactivateCommand::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), ActivateCloneCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), CloseContainerCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), HarvesterDiscardHopperCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), ServerDestroyObjectCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), HarvesterActivateCommand::doQueueCommand(), SetFactionCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), MakeLeaderCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), InviteCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), GiveItemCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), TipCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), FireHeavyWeaponCommand::getCommandDuration(), ThrowGrenadeCommand::getCommandDuration(), server::zone::managers::holocron::HolocronManager::getReporterId(), server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData(), TipCommand::performBankTip(), BoardShuttleCommand::sendTicketSelectionBoxTo(), and server::zone::manager::ZoneManagerImplementation::setZoneProcessor().
void ZoneProcessServer::initialize ()
Definition at line 59 of file ZoneProcessServer.cpp.
References _getImplementation(), server::zone::ZoneProcessServerImplementation::initialize(), and RPC_INITIALIZE__.
Friends And Related Function Documentation
friend class ZoneProcessServerHelper friend
Definition at line 261 of file ZoneProcessServer.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneProcessServer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneProcessServer.cpp