Core3: server::zone::managers::minigames::FishingSessionAdapter Class Reference
server::zone::managers::minigames::FishingSessionAdapter Class Reference
#include <FishingSession.h>
Public Member Functions
FishingSessionAdapter (FishingSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setMood (const String &m)
void setNextAction (int action)
int getNextAction ()
void setFishBoxID (unsigned int box)
unsigned int getFishBoxID ()
SceneObject * getMarker ()
void setMarker (SceneObject *mar)
int getFish ()
void setFish (int fi)
int getFishingState ()
void setFishingState (int state)
void setPlayer (CreatureObject *pl)
void update (int nextAction, SceneObject *marker, int fish, unsigned int boxID, int fishingState)
String getMoodString ()
Detailed Description
Definition at line 228 of file FishingSession.h.
Constructor & Destructor Documentation
FishingSessionAdapter::FishingSessionAdapter (FishingSession * impl)
Definition at line 581 of file FishingSession.cpp.
Member Function Documentation
int FishingSessionAdapter::getFish ()
Definition at line 692 of file FishingSession.cpp.
Referenced by invokeMethod().
unsigned int FishingSessionAdapter::getFishBoxID ()
Definition at line 680 of file FishingSession.cpp.
Referenced by invokeMethod().
int FishingSessionAdapter::getFishingState ()
Definition at line 700 of file FishingSession.cpp.
Referenced by invokeMethod().
SceneObject * FishingSessionAdapter::getMarker ()
Definition at line 684 of file FishingSession.cpp.
Referenced by invokeMethod().
String FishingSessionAdapter::getMoodString ()
Definition at line 716 of file FishingSession.cpp.
Referenced by invokeMethod().
int FishingSessionAdapter::getNextAction ()
Definition at line 672 of file FishingSession.cpp.
Referenced by invokeMethod().
void FishingSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 584 of file FishingSession.cpp.
References getFish(), getFishBoxID(), getFishingState(), getMarker(), getMoodString(), getNextAction(), RPC_GETFISH__, RPC_GETFISHBOXID__, RPC_GETFISHINGSTATE__, RPC_GETMARKER__, RPC_GETMOODSTRING__, RPC_GETNEXTACTION__, RPC_SETFISH__INT_, RPC_SETFISHBOXID__INT_, RPC_SETFISHINGSTATE__INT_, RPC_SETMARKER__SCENEOBJECT_, RPC_SETMOOD__STRING_, RPC_SETNEXTACTION__INT_, RPC_SETPLAYER__CREATUREOBJECT_, RPC_UPDATE__INT_SCENEOBJECT_INT_INT_INT_, setFish(), setFishBoxID(), setFishingState(), setMarker(), setMood(), setNextAction(), setPlayer(), and update().
void FishingSessionAdapter::setFish (int fi)
Definition at line 696 of file FishingSession.cpp.
Referenced by invokeMethod().
void FishingSessionAdapter::setFishBoxID (unsigned int box)
Definition at line 676 of file FishingSession.cpp.
Referenced by invokeMethod().
void FishingSessionAdapter::setFishingState (int state)
Definition at line 704 of file FishingSession.cpp.
Referenced by invokeMethod().
void FishingSessionAdapter::setMarker (SceneObject * mar)
Definition at line 688 of file FishingSession.cpp.
Referenced by invokeMethod().
void FishingSessionAdapter::setMood (const String & m)
Definition at line 664 of file FishingSession.cpp.
Referenced by invokeMethod().
void FishingSessionAdapter::setNextAction (int action)
Definition at line 668 of file FishingSession.cpp.
Referenced by invokeMethod().
void FishingSessionAdapter::setPlayer (CreatureObject * pl)
Definition at line 708 of file FishingSession.cpp.
Referenced by invokeMethod().
void FishingSessionAdapter::update (int nextAction, SceneObject * marker, int fish, unsigned int boxID, int fishingState)
Definition at line 712 of file FishingSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingSession.cpp