Core3: AiNPCComponent Class Reference
AiNPCComponent Class Reference
#include <AiNPCComponent.h>
Public Member Functions
void notifyPositionUpdate (SceneObject *scno, QuadTreeEntry *entry)
void doAwarenessCheck (SceneObject *scno, Coordinate &start, uint64 time, CreatureObject *target)
Public Member Functions inherited from AiInterfaceComponent
virtual void doAwarenessCheck (SceneObject *scno, Coordinate &start, uint64 time, CreatureObject *target)
Detailed Description
Definition at line 32 of file AiNPCComponent.h.
Member Function Documentation
void AiNPCComponent::doAwarenessCheck (SceneObject * scno, Coordinate & start, uint64 time, CreatureObject * target) inline
Definition at line 101 of file AiNPCComponent.h.
References CollisionManager::checkLineOfSight(), server::zone::objects::scene::SceneObject::getDistanceTo(), and server::zone::objects::scene::SceneObject::isCreatureObject().
void AiNPCComponent::notifyPositionUpdate (SceneObject * scno, QuadTreeEntry * entry) inline virtual
If not in combat, ignore creatures in different cells
Reimplemented from AiInterfaceComponent.
Definition at line 34 of file AiNPCComponent.h.
References server::zone::objects::creature::AiAgent::activateAwarenessEvent(), server::zone::objects::creature::AiAgent::getFerocity(), server::zone::objects::creature::AiAgent::getFollowObject(), server::zone::objects::tangible::TangibleObject::getLevel(), server::zone::objects::creature::AiAgent::getNumberOfPlayersInRange(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::creature::AiAgent::isAttackableBy(), server::zone::objects::creature::AiAgent::isConcealed(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::AiAgent::isFleeing(), server::zone::objects::creature::CreatureObject::isInCombat(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::AiAgent::isRetreating(), and CreatureFlag::NONE.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/components/AiNPCComponent.h