Core3: server::zone::objects::auction::AuctionItemAdapter Class Reference
server::zone::objects::auction::AuctionItemAdapter Class Reference
#include <AuctionItem.h>
Public Member Functions
AuctionItemAdapter (AuctionItem *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int compareTo (AuctionItem *obj)
void notifyLoadFromDatabase ()
void setVendorID (unsigned long long val)
void setItemName (const String &name)
void setItemDescription (const String &descr)
void setPrice (int newPrice)
void setProxy (int newProxy)
void setAuctionedItemObjectID (unsigned long long objectID)
void setItemType (int type)
void setOwnerID (unsigned long long ownerObjectID)
void setOfferToID (unsigned long long vendorOwnerID)
void setBidderName (const String &name)
void setOwnerName (const String &name)
void setAuction (bool isAuction)
void setAuctionPremium ()
void clearAuctionWithdraw ()
void setOnBazaar (bool val)
void setExpireTime (int time)
void setBuyerID (unsigned long long id)
void setStatus (int value)
bool isOnBazaar ()
bool isAuction ()
int getStatus ()
unsigned long long getVendorID ()
unsigned long long getAuctionedItemObjectID ()
unsigned long long getOwnerID ()
unsigned long long getOfferToID ()
void setVendorUID (const String &uid)
const String getVendorUID ()
String getOwnerName ()
String getItemName ()
int getExpireTime ()
int getPrice ()
int getProxy ()
int getItemType ()
unsigned long long getBuyerID ()
String getBidderName ()
String getItemDescription ()
int getAuctionOptions ()
bool isPremiumAuction ()
bool isOwner (CreatureObject *player)
bool isAuctionObject ()
Detailed Description
Definition at line 376 of file AuctionItem.h.
Constructor & Destructor Documentation
AuctionItemAdapter::AuctionItemAdapter (AuctionItem * impl)
Definition at line 1214 of file AuctionItem.cpp.
Member Function Documentation
void AuctionItemAdapter::clearAuctionWithdraw ()
Definition at line 1501 of file AuctionItem.cpp.
Referenced by invokeMethod().
int AuctionItemAdapter::compareTo (AuctionItem * obj)
Definition at line 1441 of file AuctionItem.cpp.
Referenced by invokeMethod().
unsigned long long AuctionItemAdapter::getAuctionedItemObjectID ()
Definition at line 1537 of file AuctionItem.cpp.
Referenced by invokeMethod().
int AuctionItemAdapter::getAuctionOptions ()
Definition at line 1593 of file AuctionItem.cpp.
Referenced by invokeMethod().
String AuctionItemAdapter::getBidderName ()
Definition at line 1585 of file AuctionItem.cpp.
Referenced by invokeMethod().
unsigned long long AuctionItemAdapter::getBuyerID ()
Definition at line 1581 of file AuctionItem.cpp.
Referenced by invokeMethod().
int AuctionItemAdapter::getExpireTime ()
Definition at line 1565 of file AuctionItem.cpp.
Referenced by invokeMethod().
String AuctionItemAdapter::getItemDescription ()
Definition at line 1589 of file AuctionItem.cpp.
Referenced by invokeMethod().
String AuctionItemAdapter::getItemName ()
Definition at line 1561 of file AuctionItem.cpp.
Referenced by invokeMethod().
int AuctionItemAdapter::getItemType ()
Definition at line 1577 of file AuctionItem.cpp.
Referenced by invokeMethod().
unsigned long long AuctionItemAdapter::getOfferToID ()
Definition at line 1545 of file AuctionItem.cpp.
Referenced by invokeMethod().
unsigned long long AuctionItemAdapter::getOwnerID ()
Definition at line 1541 of file AuctionItem.cpp.
Referenced by invokeMethod().
String AuctionItemAdapter::getOwnerName ()
Definition at line 1557 of file AuctionItem.cpp.
Referenced by invokeMethod().
int AuctionItemAdapter::getPrice ()
Definition at line 1569 of file AuctionItem.cpp.
Referenced by invokeMethod().
int AuctionItemAdapter::getProxy ()
Definition at line 1573 of file AuctionItem.cpp.
Referenced by invokeMethod().
int AuctionItemAdapter::getStatus ()
Definition at line 1529 of file AuctionItem.cpp.
Referenced by invokeMethod().
unsigned long long AuctionItemAdapter::getVendorID ()
Definition at line 1533 of file AuctionItem.cpp.
Referenced by invokeMethod().
const String AuctionItemAdapter::getVendorUID ()
Definition at line 1553 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1217 of file AuctionItem.cpp.
References clearAuctionWithdraw(), compareTo(), getAuctionedItemObjectID(), getAuctionOptions(), getBidderName(), getBuyerID(), getExpireTime(), getItemDescription(), getItemName(), getItemType(), getOfferToID(), getOwnerID(), getOwnerName(), getPrice(), getProxy(), getStatus(), getVendorID(), getVendorUID(), isAuction(), isAuctionObject(), isOnBazaar(), isOwner(), isPremiumAuction(), notifyLoadFromDatabase(), RPC_CLEARAUCTIONWITHDRAW__, RPC_COMPARETO__AUCTIONITEM_, RPC_GETAUCTIONEDITEMOBJECTID__, RPC_GETAUCTIONOPTIONS__, RPC_GETBIDDERNAME__, RPC_GETBUYERID__, RPC_GETEXPIRETIME__, RPC_GETITEMDESCRIPTION__, RPC_GETITEMNAME__, RPC_GETITEMTYPE__, RPC_GETOFFERTOID__, RPC_GETOWNERID__, RPC_GETOWNERNAME__, RPC_GETPRICE__, RPC_GETPROXY__, RPC_GETSTATUS__, RPC_GETVENDORID__, RPC_GETVENDORUID__, RPC_ISAUCTION__, RPC_ISAUCTIONOBJECT__, RPC_ISONBAZAAR__, RPC_ISOWNER__CREATUREOBJECT_, RPC_ISPREMIUMAUCTION__, RPC_NOTIFYLOADFROMDATABASE__, RPC_SETAUCTION__BOOL_, RPC_SETAUCTIONEDITEMOBJECTID__LONG_, RPC_SETAUCTIONPREMIUM__, RPC_SETBIDDERNAME__STRING_, RPC_SETBUYERID__LONG_, RPC_SETEXPIRETIME__INT_, RPC_SETITEMDESCRIPTION__STRING_, RPC_SETITEMNAME__STRING_, RPC_SETITEMTYPE__INT_, RPC_SETOFFERTOID__LONG_, RPC_SETONBAZAAR__BOOL_, RPC_SETOWNERID__LONG_, RPC_SETOWNERNAME__STRING_, RPC_SETPRICE__INT_, RPC_SETPROXY__INT_, RPC_SETSTATUS__INT_, RPC_SETVENDORID__LONG_, RPC_SETVENDORUID__STRING_, setAuction(), setAuctionedItemObjectID(), setAuctionPremium(), setBidderName(), setBuyerID(), setExpireTime(), setItemDescription(), setItemName(), setItemType(), setOfferToID(), setOnBazaar(), setOwnerID(), setOwnerName(), setPrice(), setProxy(), setStatus(), setVendorID(), and setVendorUID().
bool AuctionItemAdapter::isAuction ()
Definition at line 1525 of file AuctionItem.cpp.
Referenced by invokeMethod().
bool AuctionItemAdapter::isAuctionObject ()
Definition at line 1605 of file AuctionItem.cpp.
Referenced by invokeMethod().
bool AuctionItemAdapter::isOnBazaar ()
Definition at line 1521 of file AuctionItem.cpp.
Referenced by invokeMethod().
bool AuctionItemAdapter::isOwner (CreatureObject * player)
Definition at line 1601 of file AuctionItem.cpp.
Referenced by invokeMethod().
bool AuctionItemAdapter::isPremiumAuction ()
Definition at line 1597 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::notifyLoadFromDatabase ()
Definition at line 1445 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setAuction (bool isAuction)
Definition at line 1493 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setAuctionedItemObjectID (unsigned long long objectID)
Definition at line 1469 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setAuctionPremium ()
Definition at line 1497 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setBidderName (const String & name)
Definition at line 1485 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setBuyerID (unsigned long long id)
Definition at line 1513 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setExpireTime (int time)
Definition at line 1509 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setItemDescription (const String & descr)
Definition at line 1457 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setItemName (const String & name)
Definition at line 1453 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setItemType (int type)
Definition at line 1473 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setOfferToID (unsigned long long vendorOwnerID)
Definition at line 1481 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setOnBazaar (bool val)
Definition at line 1505 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setOwnerID (unsigned long long ownerObjectID)
Definition at line 1477 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setOwnerName (const String & name)
Definition at line 1489 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setPrice (int newPrice)
Definition at line 1461 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setProxy (int newProxy)
Definition at line 1465 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setStatus (int value)
Definition at line 1517 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setVendorID (unsigned long long val)
Definition at line 1449 of file AuctionItem.cpp.
Referenced by invokeMethod().
void AuctionItemAdapter::setVendorUID (const String & uid)
Definition at line 1549 of file AuctionItem.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/auction/AuctionItem.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/auction/AuctionItem.cpp