Core3: server::zone::objects::installation::shuttle::ShuttleInstallationImplementation Class Reference
server::zone::objects::installation::shuttle::ShuttleInstallationImplementation Class Reference
#include <ShuttleInstallation.h>
Public Member Functions
ShuttleInstallationImplementation ()
ShuttleInstallationImplementation (DummyConstructorParameter *param)
bool checkRequisitesForPlacement (CreatureObject *player)
bool isShuttleInstallation ()
operator const ShuttleInstallation * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::installation::InstallationObjectImplementation
InstallationObjectImplementation ()
InstallationObjectImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
void fillAttributeList (AttributeListMessage *alm, CreatureObject *object)
void loadTemplateData (SharedObjectTemplate *templateData)
void broadcastMessage (BasePacket *message, bool sendSelf)
void updateResourceContainerQuantity (ResourceContainer *container, int newQuantity, bool notifyClient=true)
virtual void setOperating (bool operating, bool notifyClient=true)
void activateUiSync ()
virtual void updateOperators ()
void verifyOperators ()
virtual void updateInstallationWork ()
void handleStructureAddEnergy (CreatureObject *player)
void setActiveResource (ResourceContainer *container)
void changeActiveResourceID (unsigned long long spawnObjectID)
void addResourceToHopper (ResourceContainer *container)
void clearResourceHopper ()
float getHopperSize ()
bool updateMaintenance (Time &workingTime)
void updateHopper (Time &workingTime, bool shutdownAfterUpdate)
int getHopperItemQuantity (ResourceSpawn *spawn)
ResourceContainer * getContainerFromHopper (ResourceSpawn *spawn)
unsigned long long getActiveResourceSpawnID ()
float getActualRate ()
void broadcastToOperators (BasePacket *packet)
void addOperator (CreatureObject *player)
void removeOperator (CreatureObject *player)
void sendBaselinesTo (SceneObject *player)
bool isInstallationObject ()
bool isOperating ()
int getInstallationType ()
float getExtractionRate ()
float getHopperSizeMax ()
void updateStructureStatus ()
HopperList * getHopperList ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
void setHopperSizeMax (float size)
void setExtractionRate (float rate)
bool isAttackableBy (CreatureObject *object)
void createChildObjects ()
float getHitChance ()
operator const InstallationObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::structure::StructureObjectImplementation
StructureObjectImplementation ()
StructureObjectImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void finalize ()
void loadTemplateData (SharedObjectTemplate *templateData)
void notifyInsertToZone (Zone *zone)
void createChildObjects ()
virtual int notifyStructurePlaced (CreatureObject *creature)
String getTimeString (unsigned int timestamp)
void scheduleMaintenanceExpirationEvent ()
void scheduleMaintenanceTask (int timeFromNow)
bool isOnAdminList (CreatureObject *player)
bool isOnAdminList (const String &firstName, bool caseSensitive=false)
bool isOnEntryList (CreatureObject *player)
bool isOnBanList (CreatureObject *player)
bool isOnBanList (const String &firstName, bool caseSensitive=false)
bool isOnHopperList (CreatureObject *player)
bool isOnPermissionList (const String &listName, CreatureObject *player)
bool isOnPermissionList (const String &listName, const String &firstName, bool caseSensitive=false)
bool isOwnerOf (SceneObject *obj)
bool isOwnerOf (unsigned long long oid)
bool isOnAccessList (SceneObject *obj)
bool isOnAccessList (unsigned long long oid)
void sendPermissionListTo (CreatureObject *creature, const String &listName)
bool hasPermissionList (const String &listName)
bool isPermissionListFull (const String &listName)
int togglePermission (const String &listName, const String &targetName, bool caseSensitive=false)
int grantPermission (const String &listName, const String &targetName, bool caseSensitive=false)
int revokePermission (const String &listName, const String &targetName, bool caseSensitive=false)
int revokeAllPermissions (const String &targetName, bool caseSensitive=false)
void setOwnerName (const String &ownerName)
int getRedeedCost ()
CreatureObject * getOwnerCreatureObject ()
unsigned long long getOwnerObjectID ()
unsigned long long getDeedObjectID ()
int getLotSize ()
void setMaintenanceReduced (bool value)
float getMaintenanceRate ()
String getMaintenanceMods ()
int getBaseMaintenanceRate ()
int getBasePowerRate ()
int getSurplusMaintenance ()
int getSurplusPower ()
virtual bool isPublicStructure ()
virtual bool isPrivateStructure ()
void setOwnerObjectID (unsigned long long objectID)
void setDeedObjectID (unsigned long long deedID)
void setBaseMaintenanceRate (int rate)
void setBasePowerRate (int rate)
void setSurplusMaintenance (int surplus)
void addMaintenance (float add)
void payMaintenance (int maintenance, CreatureObject *payer, bool cashFirst)
void setSurplusPower (int surplus)
void addPower (float add)
bool isDecaying ()
bool isDecayed ()
int getDecayPercentage ()
virtual bool isCondemned ()
virtual void setPublicStructure (bool privacy)
bool isStructureObject ()
bool isCampStructure ()
bool isRedeedable ()
AABBTree * getAABBTree ()
void addTemplateSkillMods (TangibleObject *targetObject)
void removeTemplateSkillMods (TangibleObject *tangibleObject)
virtual String getRedeedMessage ()
bool isCivicStructure ()
bool isCityHall ()
bool isCommercialStructure ()
operator const StructureObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
TangibleObjectImplementation ()
TangibleObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
virtual void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
virtual void removeSkillModsFrom (CreatureObject *creature)
virtual void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
virtual void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
virtual void removeAllSkillModsOfType (const int skillType, bool notifyClient=true)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
virtual void setDefender (SceneObject *defender)
virtual void addDefender (SceneObject *defender)
virtual void removeDefender (SceneObject *defender)
virtual void removeDefenders ()
virtual void setCombatState ()
virtual void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
virtual void clearCombatState (bool clearDefenders=true)
bool hasDefender (SceneObject *defender)
virtual bool isAggressiveTo (CreatureObject *object)
virtual bool isHealableBy (CreatureObject *object)
virtual void sendPvpStatusTo (CreatureObject *player)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
virtual int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
virtual void updateCraftingValues (CraftingValues *values, bool firstUpdate)
virtual int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
virtual bool isKiller ()
virtual bool isTicketCollector ()
virtual bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
virtual int getUseCount ()
virtual int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
virtual bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
virtual String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
virtual int getJunkDealerNeeded ()
void setJunkValue (int jValue)
virtual int getJunkValue ()
void setSerialNumber (const String &serial)
virtual void setLevel (int lev)
virtual String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
virtual String repairAttempt (int repairChance)
bool isBroken ()
void broadcastPvpStatusBitmask ()
operator const TangibleObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendTo (SceneObject *player, bool doClose)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
virtual void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
virtual int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< ShuttleInstallation * > _this
Public Attributes inherited from server::zone::objects::installation::InstallationObjectImplementation
WeakReference
< InstallationObject * > _this
Public Attributes inherited from server::zone::objects::structure::StructureObjectImplementation
WeakReference< StructureObject * > _this
Public Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
WeakReference< TangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Protected Member Functions
virtual ~ShuttleInstallationImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::installation::InstallationObjectImplementation
virtual ~InstallationObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::structure::StructureObjectImplementation
virtual ~StructureObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
float getConditionReduction (float value)
virtual ~TangibleObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class ShuttleInstallation
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::installation::InstallationObjectImplementation
Reference
< SyncrhonizedUiListenInstallationTask * > syncUiTask
bool operating
SortedVector< ManagedReference
< CreatureObject * > > operatorList
int installationType
Time resourceHopperTimestamp
Time lastStartTime
Time lastStopTime
HopperList resourceHopper
float hopperSizeMax
float extractionRate
float extractionRemainder
float spawnDensity
ManagedReference< ResourceSpawn * > currentSpawn
Detailed Description
Definition at line 195 of file ShuttleInstallation.h.
Constructor & Destructor Documentation
ShuttleInstallationImplementation::ShuttleInstallationImplementation ()
Definition at line 206 of file ShuttleInstallation.cpp.
References _initializeImplementation(), and server::zone::objects::scene::SceneObjectImplementation::setLoggingName().
ShuttleInstallationImplementation::ShuttleInstallationImplementation (DummyConstructorParameter * param)
Definition at line 92 of file ShuttleInstallation.cpp.
References _initializeImplementation().
ShuttleInstallationImplementation::~ShuttleInstallationImplementation () protected virtual
Definition at line 97 of file ShuttleInstallation.cpp.
Member Function Documentation
DistributedObjectStub * ShuttleInstallationImplementation::_getStub ()
Definition at line 117 of file ShuttleInstallation.cpp.
References _this.
void ShuttleInstallationImplementation::_initializeImplementation () protected
Definition at line 104 of file ShuttleInstallation.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ShuttleInstallationImplementation().
void ShuttleInstallationImplementation::_serializationHelperMethod () protected
Definition at line 153 of file ShuttleInstallation.cpp.
References server::zone::objects::installation::InstallationObjectImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void ShuttleInstallationImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 112 of file ShuttleInstallation.cpp.
References server::zone::objects::installation::InstallationObjectImplementation::_setStub(), and _this.
Referenced by server::zone::objects::installation::shuttle::ShuttleInstallation::ShuttleInstallation().
bool ShuttleInstallationImplementation::checkRequisitesForPlacement (CreatureObject * player) virtual
Reimplemented from server::zone::objects::structure::StructureObjectImplementation.
Definition at line 15 of file ShuttleInstallationImplementation.cpp.
Referenced by server::zone::objects::installation::shuttle::ShuttleInstallation::checkRequisitesForPlacement().
void ShuttleInstallationImplementation::finalize () protected
Definition at line 101 of file ShuttleInstallation.cpp.
bool ShuttleInstallationImplementation::isShuttleInstallation () virtual
Reimplemented from server::zone::objects::installation::InstallationObjectImplementation.
Definition at line 212 of file ShuttleInstallation.cpp.
Referenced by server::zone::objects::installation::shuttle::ShuttleInstallation::isShuttleInstallation().
void ShuttleInstallationImplementation::lock (bool doLock = true) protected
Definition at line 125 of file ShuttleInstallation.cpp.
References _this.
void ShuttleInstallationImplementation::lock (ManagedObject * obj) protected
Definition at line 129 of file ShuttleInstallation.cpp.
References _this.
ShuttleInstallationImplementation::operator const ShuttleInstallation * ()
Definition at line 121 of file ShuttleInstallation.cpp.
void ShuttleInstallationImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::installation::InstallationObjectImplementation.
Definition at line 160 of file ShuttleInstallation.cpp.
References server::zone::objects::installation::InstallationObjectImplementation::initializeTransientMembers(), and readObjectMember().
bool ShuttleInstallationImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 179 of file ShuttleInstallation.cpp.
References server::zone::objects::installation::InstallationObjectImplementation::readObjectMember().
Referenced by readObject().
void ShuttleInstallationImplementation::rlock (bool doLock = true) protected
Definition at line 133 of file ShuttleInstallation.cpp.
References _this.
void ShuttleInstallationImplementation::runlock (bool doLock = true) protected
Definition at line 149 of file ShuttleInstallation.cpp.
References _this.
void ShuttleInstallationImplementation::unlock (bool doLock = true) protected
Definition at line 145 of file ShuttleInstallation.cpp.
References _this.
void ShuttleInstallationImplementation::wlock (bool doLock = true) protected
Definition at line 137 of file ShuttleInstallation.cpp.
References _this.
void ShuttleInstallationImplementation::wlock (ManagedObject * obj) protected
Definition at line 141 of file ShuttleInstallation.cpp.
References _this.
void ShuttleInstallationImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::installation::InstallationObjectImplementation.
Definition at line 189 of file ShuttleInstallation.cpp.
References writeObjectMembers().
int ShuttleInstallationImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 196 of file ShuttleInstallation.cpp.
References server::zone::objects::installation::InstallationObjectImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class ShuttleInstallation friend
Definition at line 240 of file ShuttleInstallation.h.
Member Data Documentation
WeakReference<ShuttleInstallation*> server::zone::objects::installation::shuttle::ShuttleInstallationImplementation::_this
Definition at line 206 of file ShuttleInstallation.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/shuttle/ShuttleInstallation.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/shuttle/ShuttleInstallation.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/shuttle/ShuttleInstallationImplementation.cpp