Core3: Layer Class Reference
Layer Class Reference
#include <Layer.h>
Public Member Functions
Layer (Layer *par=NULL)
~Layer ()
void parseFromIffStream (engine::util::IffStream *iffStream)
void parseFromIffStream (engine::util::IffStream *iffStream, Version<'0003'>)
IffTemplateVariable * parseAffector (IffStream *iffStream)
IffTemplateVariable * parseBoundary (IffStream *iffStream)
IffTemplateVariable * parseFilter (IffStream *iffStream)
Vector< Layer * > * getChildren ()
Vector< Boundary * > * getBoundaries ()
Vector< AffectorProceduralRule * > * getAffectors ()
Vector< FilterProceduralRule * > * getFilters ()
Layer * getParent ()
bool invertBoundaries ()
bool invertFilters ()
bool isEnabled ()
String & getDescription ()
Public Member Functions inherited from TemplateVariable<'LAYR'>
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Private Attributes
InformationHeader infoHeader
Vector< Layer * > children
Vector< Boundary * > boundaries
Vector< AffectorProceduralRule * > affectors
Vector< FilterProceduralRule * > filters
Layer * parent
int boundariesFlag
int filterFlag
Detailed Description
Definition at line 22 of file Layer.h.
Constructor & Destructor Documentation
Layer::Layer (Layer * par = NULL) inline
Definition at line 41 of file Layer.h.
References boundariesFlag, filterFlag, and parent.
Referenced by parseFromIffStream().
Layer::~Layer ()
Definition at line 18 of file Layer.cpp.
References affectors, boundaries, children, and filters.
Member Function Documentation
Vector<AffectorProceduralRule*>* Layer::getAffectors () inline
Definition at line 64 of file Layer.h.
References affectors.
Referenced by ProceduralTerrainAppearance::processTerrain(), and ProceduralTerrainAppearance::setHeight().
Vector<Boundary*>* Layer::getBoundaries () inline
Definition at line 60 of file Layer.h.
References boundaries.
Referenced by ProceduralTerrainAppearance::getLayerRecursive(), TerrainGenerator::processLayer(), ProceduralTerrainAppearance::processTerrain(), and ProceduralTerrainAppearance::translateBoundaries().
Vector<Layer*>* Layer::getChildren () inline
Definition at line 56 of file Layer.h.
References children.
Referenced by ProceduralTerrainAppearance::getLayerRecursive(), TerrainGenerator::processLayer(), ProceduralTerrainAppearance::processTerrain(), ProceduralTerrainAppearance::setHeight(), and ProceduralTerrainAppearance::translateBoundaries().
String& Layer::getDescription () inline
Definition at line 92 of file Layer.h.
References InformationHeader::getDescription(), and infoHeader.
Vector<FilterProceduralRule*>* Layer::getFilters () inline
Definition at line 72 of file Layer.h.
References filters.
Referenced by ProceduralTerrainAppearance::processTerrain().
Layer* Layer::getParent () inline
Definition at line 76 of file Layer.h.
References parent.
bool Layer::invertBoundaries () inline
Definition at line 80 of file Layer.h.
References boundariesFlag.
Referenced by ProceduralTerrainAppearance::processTerrain().
bool Layer::invertFilters () inline
Definition at line 84 of file Layer.h.
References filterFlag.
Referenced by ProceduralTerrainAppearance::processTerrain().
bool Layer::isEnabled () inline
Definition at line 88 of file Layer.h.
References infoHeader, and InformationHeader::isEnabled().
Referenced by ProceduralTerrainAppearance::addTerrainModification(), ProceduralTerrainAppearance::getEnvironmentID(), ProceduralTerrainAppearance::getHeight(), ProceduralTerrainAppearance::getLayer(), ProceduralTerrainAppearance::processTerrain(), ProceduralTerrainAppearance::setHeight(), and ProceduralTerrainAppearance::translateBoundaries().
IffTemplateVariable * Layer::parseAffector (IffStream * iffStream)
Definition at line 122 of file Layer.cpp.
References IffTemplateVariable::readObject().
Referenced by parseFromIffStream().
IffTemplateVariable * Layer::parseBoundary (IffStream * iffStream)
Definition at line 229 of file Layer.cpp.
References IffTemplateVariable::readObject().
Referenced by parseFromIffStream().
IffTemplateVariable * Layer::parseFilter (IffStream * iffStream)
Definition at line 267 of file Layer.cpp.
References IffTemplateVariable::readObject().
Referenced by parseFromIffStream().
void Layer::parseFromIffStream (engine::util::IffStream * iffStream) virtual
Reimplemented from TemplateVariable<'LAYR'>.
Definition at line 36 of file Layer.cpp.
void Layer::parseFromIffStream (engine::util::IffStream * iffStream, Version<'0003'>)
Definition at line 53 of file Layer.cpp.
References affectors, boundaries, boundariesFlag, children, filterFlag, filters, infoHeader, Layer(), parseAffector(), parseBoundary(), parseFilter(), and TemplateVariable< formType >::readObject().
Member Data Documentation
Vector<AffectorProceduralRule*> Layer::affectors private
Definition at line 29 of file Layer.h.
Referenced by getAffectors(), parseFromIffStream(), and ~Layer().
Vector<Boundary*> Layer::boundaries private
Definition at line 28 of file Layer.h.
Referenced by getBoundaries(), parseFromIffStream(), and ~Layer().
int Layer::boundariesFlag private
Definition at line 37 of file Layer.h.
Referenced by invertBoundaries(), Layer(), and parseFromIffStream().
Vector<Layer*> Layer::children private
Definition at line 25 of file Layer.h.
Referenced by getChildren(), parseFromIffStream(), and ~Layer().
int Layer::filterFlag private
Definition at line 38 of file Layer.h.
Referenced by invertFilters(), Layer(), and parseFromIffStream().
Vector<FilterProceduralRule*> Layer::filters private
Definition at line 30 of file Layer.h.
Referenced by getFilters(), parseFromIffStream(), and ~Layer().
InformationHeader Layer::infoHeader private
Definition at line 23 of file Layer.h.
Referenced by getDescription(), isEnabled(), and parseFromIffStream().
Layer* Layer::parent private
Definition at line 35 of file Layer.h.
Referenced by getParent(), and Layer().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/layer/Layer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/layer/Layer.cpp