Core3: SkillModList Class Reference
SkillModList Class Reference
#include <SkillModList.h>
Public Member Functions
SkillModList ()
void addSerializableVariables ()
bool add (const uint32 modType, const String &skillMod, int value)
SkillModEntry getVisibleSkillMod (const String &skillMod)
SkillModGroup * getSkillModGroup (const uint32 type)
int getSkillMod (const String &skillMod)
String getPrintableSkillModList ()
Public Member Functions inherited from DeltaVectorMap< String, SkillModEntry >
DeltaVectorMap ()
DeltaVectorMap (int initsize, int incr)
DeltaVectorMap (const DeltaVectorMap &ds)
void addSerializableVariables ()
virtual int set (const String &key, const SkillModEntry &value, DeltaMessage *message=NULL, int updates=1)
virtual bool drop (const String &key, DeltaMessage *message=NULL, int updates=1)
virtual void insertToMessage (BaseMessage *msg)
SkillModEntry & getValueAt (int index)
String & getKeyAt (int index)
SkillModEntry & get (const String &key)
bool contains (const String &key)
int size ()
uint32 getUpdateCounter ()
void setNullValue (const SkillModEntry &val)
Protected Attributes
VectorMap< uint32, SkillModGroup > mods
Protected Attributes inherited from DeltaVectorMap< String, SkillModEntry >
VectorMap< String, SkillModEntry > vectorMap
uint32 updateCounter
Detailed Description
Definition at line 75 of file SkillModList.h.
Constructor & Destructor Documentation
SkillModList::SkillModList () inline
Definition at line 82 of file SkillModList.h.
References addSerializableVariables(), and mods.
Member Function Documentation
bool SkillModList::add (const uint32 modType, const String & skillMod, int value) inline
Definition at line 91 of file SkillModList.h.
References mods.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::addSkillMod().
void SkillModList::addSerializableVariables () inline
Definition at line 87 of file SkillModList.h.
References mods.
Referenced by SkillModList().
String SkillModList::getPrintableSkillModList () inline
Definition at line 192 of file SkillModList.h.
References mods.
Referenced by PlayerInfoCommand::executeCommand().
int SkillModList::getSkillMod (const String & skillMod) inline
Definition at line 162 of file SkillModList.h.
References mods.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::getSkillMod().
SkillModGroup* SkillModList::getSkillModGroup (const uint32 type) inline
Definition at line 153 of file SkillModList.h.
References mods.
Referenced by server::zone::managers::skill::SkillModManager::compareMods(), and server::zone::objects::creature::CreatureObjectImplementation::removeAllSkillModsOfType().
SkillModEntry SkillModList::getVisibleSkillMod (const String & skillMod) inline
Definition at line 110 of file SkillModList.h.
References SkillModEntry::getSkillBonus(), SkillModEntry::getSkillMod(), mods, SkillModEntry::setSkillBonus(), and SkillModEntry::setSkillMod().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::addSkillMod().
Member Data Documentation
VectorMap<uint32, SkillModGroup> SkillModList::mods protected
Definition at line 78 of file SkillModList.h.
Referenced by add(), addSerializableVariables(), getPrintableSkillModList(), getSkillMod(), getSkillModGroup(), getVisibleSkillMod(), and SkillModList().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/variables/SkillModList.h