Core3: server::zone::objects::player::sessions::crafting::CraftingSessionImplementation Class Reference
server::zone::objects::player::sessions::crafting::CraftingSessionImplementation Class Reference
#include <CraftingSession.h>
Public Member Functions
CraftingSessionImplementation (CreatureObject *creature)
CraftingSessionImplementation (DummyConstructorParameter *param)
int initializeSession (CraftingTool *tool, CraftingStation *station)
int cancelSession ()
int clearSession ()
ManagedWeakReference
< ManufactureSchematic * > getSchematic ()
void selectDraftSchematic (int index)
void sendIngredientForUIListen ()
void addIngredient (TangibleObject *tano, int slotUpdated, int clientCounter)
void removeIngredient (TangibleObject *tano, int slotUpdated, int clientCounter)
void nextCraftingStage (int clientCounter)
void experiment (int rowsAttempted, const String &expAttempt, int clientCounter)
void customization (const String &name, byte templateChoice, int schematicCount, const String &customizationString)
void createPrototype (int clientCounter, bool practice)
void createManufactureSchematic (int clientCounter)
int getState ()
operator const CraftingSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< CraftingSession * > _this
Protected Member Functions
virtual ~CraftingSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > crafter
ManagedWeakReference
< PlayerObject * > crafterGhost
ManagedWeakReference
< CraftingTool * > craftingTool
ManagedWeakReference
< CraftingStation * > craftingStation
ManagedWeakReference
< CraftingManager * > craftingManager
ManagedWeakReference
< ManufactureSchematic * > manufactureSchematic
ManagedWeakReference
< TangibleObject * > prototype
int experimentationPointsTotal
int experimentationPointsUsed
byte state
Vector< ManagedReference
< DraftSchematic * > > currentSchematicList
byte assemblyResult
byte experimentationResult
unsigned long long lastExperimentTime
VectorMap< String, Reference
< CustomizationVariable * > > variables
Private Member Functions
int startSession ()
void closeCraftingWindow (int clientCounter)
void sendSlotMessage (int counter, int message)
bool createSessionObjects (DraftSchematic *draftSchematic)
bool createManufactureSchematic (DraftSchematic *draftschematic)
bool createPrototypeObject (DraftSchematic *draftschematic)
void initialAssembly (int clientCounter)
void finishAssembly (int clientCounter)
void finishStage1 (int clientCounter)
void finishStage2 (int clientCounter)
void startCreationTasks (int timer, bool practice)
void addSkillMods ()
void addWeaponDots ()
Friends
class CraftingSession
Detailed Description
Definition at line 258 of file CraftingSession.h.
Constructor & Destructor Documentation
CraftingSessionImplementation::CraftingSessionImplementation (CreatureObject * creature)
Definition at line 381 of file CraftingSession.cpp.
References _initializeImplementation(), crafter, and craftingManager.
CraftingSessionImplementation::CraftingSessionImplementation (DummyConstructorParameter * param)
Definition at line 267 of file CraftingSession.cpp.
References _initializeImplementation().
CraftingSessionImplementation::~CraftingSessionImplementation () protected virtual
Definition at line 272 of file CraftingSession.cpp.
Member Function Documentation
DistributedObjectStub * CraftingSessionImplementation::_getStub ()
Definition at line 292 of file CraftingSession.cpp.
References _this.
void CraftingSessionImplementation::_initializeImplementation () protected
Definition at line 279 of file CraftingSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CraftingSessionImplementation().
void CraftingSessionImplementation::_serializationHelperMethod () protected
Definition at line 328 of file CraftingSession.cpp.
Referenced by _initializeImplementation().
void CraftingSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 287 of file CraftingSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::CraftingSession().
void CraftingSessionImplementation::addIngredient (TangibleObject * tano, int slotUpdated, int clientCounter)
The CraftingAddIngredientCallback executes this method when an object is added in the crafting window
Check if item is on the player, but not in a crafting tool Or if the item is in a crafting station to prevent some duping
Add Components to crafted object
Definition at line 436 of file CraftingSessionImplementation.cpp.
References _this, crafter, crafterGhost, craftingStation, craftingTool, server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::scene::SceneObject::getSlottedObject(), IngredientSlot::INVALID, IngredientSlot::INVALIDINGREDIENT, server::zone::objects::scene::SceneObject::isASubChildOf(), manufactureSchematic, IngredientSlot::NOINVENTORY, IngredientSlot::NOSCHEMATIC, prototype, IngredientSlot::PROTOTYPENOTFOUND, and sendSlotMessage().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::addIngredient().
void CraftingSessionImplementation::addSkillMods () private
Definition at line 1295 of file CraftingSessionImplementation.cpp.
References manufactureSchematic, and prototype.
Referenced by initialAssembly().
void CraftingSessionImplementation::addWeaponDots () private
Definition at line 1309 of file CraftingSessionImplementation.cpp.
References manufactureSchematic, and prototype.
Referenced by initialAssembly().
int CraftingSessionImplementation::cancelSession ()
Cancels the current session
Definition at line 130 of file CraftingSessionImplementation.cpp.
References clearSession(), DeltaMessage::close(), crafter, crafterGhost, SessionFacadeType::CRAFTING, craftingStation, craftingTool, and PlayerObjectDeltaMessage9::setCraftingState().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::cancelSession(), createManufactureSchematic(), createPrototype(), createPrototypeObject(), selectDraftSchematic(), and startSession().
int CraftingSessionImplementation::clearSession ()
Definition at line 157 of file CraftingSessionImplementation.cpp.
References _this, crafter, crafterGhost, craftingStation, craftingTool, manufactureSchematic, and prototype.
Referenced by cancelSession(), server::zone::objects::player::sessions::crafting::CraftingSession::clearSession(), and selectDraftSchematic().
void CraftingSessionImplementation::closeCraftingWindow (int clientCounter) private
Closes an open crafting windows
Definition at line 212 of file CraftingSessionImplementation.cpp.
References crafter, and crafterGhost.
Referenced by createManufactureSchematic(), createPrototype(), createPrototypeObject(), and selectDraftSchematic().
bool CraftingSessionImplementation::createManufactureSchematic (DraftSchematic * draftschematic) private
Creates the manufacture schematic
Definition at line 328 of file CraftingSessionImplementation.cpp.
References cancelSession(), closeCraftingWindow(), crafter, crafterGhost, craftingTool, server::zone::objects::draftschematic::DraftSchematic::createManufactureSchematic(), and manufactureSchematic.
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::createManufactureSchematic(), and createSessionObjects().
void CraftingSessionImplementation::createManufactureSchematic (int clientCounter)
CreateManfSchematicCommand calls this
Definition at line 1237 of file CraftingSessionImplementation.cpp.
References _this, cancelSession(), closeCraftingWindow(), crafter, crafterGhost, craftingManager, craftingStation, craftingTool, manufactureSchematic, IngredientSlot::NOSCHEMATIC, prototype, IngredientSlot::PROTOTYPENOTFOUND, sendSlotMessage(), and IngredientSlot::WEIRDFAILEDMESSAGE.
void CraftingSessionImplementation::createPrototype (int clientCounter, bool practice)
CreatePrototypeCommand calls this
Definition at line 1143 of file CraftingSessionImplementation.cpp.
References _this, cancelSession(), closeCraftingWindow(), crafter, craftingTool, manufactureSchematic, IngredientSlot::NOSCHEMATIC, prototype, IngredientSlot::PROTOTYPENOTFOUND, sendSlotMessage(), startCreationTasks(), and IngredientSlot::WEIRDFAILEDMESSAGE.
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::createPrototype().
bool CraftingSessionImplementation::createPrototypeObject (DraftSchematic * draftschematic) private
Creates the prototype to be crafted
Definition at line 350 of file CraftingSessionImplementation.cpp.
References cancelSession(), closeCraftingWindow(), crafter, crafterGhost, craftingTool, server::zone::objects::draftschematic::DraftSchematic::getTanoCRC(), and prototype.
Referenced by createSessionObjects(), and initialAssembly().
bool CraftingSessionImplementation::createSessionObjects (DraftSchematic * draftSchematic) private
Creates the needed objects when a schematic is selected
Definition at line 320 of file CraftingSessionImplementation.cpp.
References createManufactureSchematic(), and createPrototypeObject().
Referenced by selectDraftSchematic().
void CraftingSessionImplementation::customization (const String & name, byte templateChoice, int schematicCount, const String & customizationString)
The CraftingCustomizationCallback executes this method a user customizes a tano in the crafting tool
Set Name
Set Manufacture Schematic Custom name
Definition at line 986 of file CraftingSessionImplementation.cpp.
References _this, DeltaMessage::close(), crafter, crafterGhost, craftingManager, craftingStation, craftingTool, manufactureSchematic, IngredientSlot::NOSCHEMATIC, prototype, IngredientSlot::PROTOTYPENOTFOUND, sendSlotMessage(), state, ManufactureSchematicObjectDeltaMessage3::updateCondition(), TangibleObjectDeltaMessage3::updateCustomizationString(), ManufactureSchematicObjectDeltaMessage3::updateName(), TangibleObjectDeltaMessage3::updateName(), and variables.
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::customization().
void CraftingSessionImplementation::experiment (int rowsAttempted, const String & expAttempt, int clientCounter)
The CraftingExperimentCallback executes this method when a player experiments in a crafting tool
Definition at line 854 of file CraftingSessionImplementation.cpp.
References _this, DeltaMessage::close(), crafter, crafterGhost, ObserverEventType::CRAFTINGEXPERIMENTATION, craftingManager, craftingStation, craftingTool, experimentationPointsTotal, experimentationPointsUsed, experimentationResult, manufactureSchematic, IngredientSlot::NOSCHEMATIC, prototype, IngredientSlot::PROTOTYPENOTFOUND, sendSlotMessage(), PlayerObjectDeltaMessage9::setExperimentationPoints(), ManufactureSchematicObjectDeltaMessage7::update9(), ManufactureSchematicObjectDeltaMessage3::updateComplexity(), TangibleObjectDeltaMessage3::updateComplexity(), and ManufactureSchematicObjectDeltaMessage3::updateCraftingValues().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::experiment().
void CraftingSessionImplementation::finalize () protected
Definition at line 276 of file CraftingSession.cpp.
void CraftingSessionImplementation::finishAssembly (int clientCounter) private
Sends the crafting process to customization
Definition at line 827 of file CraftingSessionImplementation.cpp.
References DeltaMessage::close(), crafter, PlayerObjectDeltaMessage9::setCraftingState(), and state.
Referenced by nextCraftingStage().
void CraftingSessionImplementation::finishStage1 (int clientCounter) private
Definition at line 1100 of file CraftingSessionImplementation.cpp.
References DeltaMessage::close(), crafter, PlayerObjectDeltaMessage9::setCraftingState(), and state.
Referenced by nextCraftingStage().
void CraftingSessionImplementation::finishStage2 (int clientCounter) private
Definition at line 1122 of file CraftingSessionImplementation.cpp.
References DeltaMessage::close(), crafter, PlayerObjectDeltaMessage9::setCraftingState(), and state.
Referenced by nextCraftingStage().
ManagedWeakReference< ManufactureSchematic * > CraftingSessionImplementation::getSchematic ()
Definition at line 393 of file CraftingSession.cpp.
References manufactureSchematic.
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::getSchematic().
int CraftingSessionImplementation::getState ()
Definition at line 398 of file CraftingSession.cpp.
References state.
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::getState().
void CraftingSessionImplementation::initialAssembly (int clientCounter) private
Ends the ingredient phase, resources/components are unrecoverable
Definition at line 660 of file CraftingSessionImplementation.cpp.
References addSkillMods(), addWeaponDots(), assemblyResult, DeltaMessage::close(), crafter, crafterGhost, ObserverEventType::CRAFTINGASSEMBLY, craftingManager, craftingStation, craftingTool, createPrototypeObject(), experimentationPointsTotal, experimentationPointsUsed, server::zone::templates::SharedObjectTemplate::getAppearanceFilename(), manufactureSchematic, prototype, PlayerObjectDeltaMessage9::setCraftingState(), PlayerObjectDeltaMessage9::setExperimentationPoints(), state, ManufactureSchematicObjectDeltaMessage3::updateComplexity(), TangibleObjectDeltaMessage3::updateComplexity(), ManufactureSchematicObjectDeltaMessage3::updateCraftingValues(), ManufactureSchematicObjectDeltaMessage7::updateCustomizationOptions(), ManufactureSchematicObjectDeltaMessage7::updateForAssembly(), TangibleObjectDeltaMessage3::updateMaxCondition(), and variables.
Referenced by nextCraftingStage().
int CraftingSessionImplementation::initializeSession (CraftingTool * tool, CraftingStation * station)
The crafting tool and station have been identified pre calling initializeSession
Definition at line 30 of file CraftingSessionImplementation.cpp.
References _this, crafter, crafterGhost, SessionFacadeType::CRAFTING, craftingManager, craftingStation, craftingTool, experimentationPointsTotal, experimentationPointsUsed, and startSession().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::initializeSession().
void CraftingSessionImplementation::lock (bool doLock = true) protected
Definition at line 300 of file CraftingSession.cpp.
References _this.
void CraftingSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 304 of file CraftingSession.cpp.
References _this.
void CraftingSessionImplementation::nextCraftingStage (int clientCounter)
The NextCraftingStageCommand uses this
Add Components to crafted object
Definition at line 589 of file CraftingSessionImplementation.cpp.
References _this, crafter, crafterGhost, craftingStation, craftingTool, finishAssembly(), finishStage1(), finishStage2(), initialAssembly(), manufactureSchematic, IngredientSlot::NOSCHEMATIC, IngredientSlot::PARTIALASSEMBLE, prototype, IngredientSlot::PROTOTYPENOTFOUND, sendSlotMessage(), and state.
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::nextCraftingStage().
CraftingSessionImplementation::operator const CraftingSession * ()
Definition at line 296 of file CraftingSession.cpp.
void CraftingSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 335 of file CraftingSession.cpp.
References readObjectMember().
bool CraftingSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 354 of file CraftingSession.cpp.
Referenced by readObject().
void CraftingSessionImplementation::removeIngredient (TangibleObject * tano, int slotUpdated, int clientCounter)
The CraftingRemoveIngredientCallback executes this method when an object is removed from the crafting window
Definition at line 532 of file CraftingSessionImplementation.cpp.
References _this, crafter, crafterGhost, craftingStation, craftingTool, server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::scene::SceneObject::getSlottedObject(), IngredientSlot::INVALID, IngredientSlot::INVALIDINGREDIENT, manufactureSchematic, IngredientSlot::NOINVENTORY, IngredientSlot::NOSCHEMATIC, IngredientSlot::OK, prototype, IngredientSlot::PROTOTYPENOTFOUND, and sendSlotMessage().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::removeIngredient().
void CraftingSessionImplementation::rlock (bool doLock = true) protected
Definition at line 308 of file CraftingSession.cpp.
References _this.
void CraftingSessionImplementation::runlock (bool doLock = true) protected
Definition at line 324 of file CraftingSession.cpp.
References _this.
void CraftingSessionImplementation::selectDraftSchematic (int index)
The SelectDraftSchematicCommand uses this
Definition at line 256 of file CraftingSessionImplementation.cpp.
References _this, cancelSession(), clearSession(), DeltaMessage::close(), closeCraftingWindow(), crafter, crafterGhost, craftingTool, createSessionObjects(), currentSchematicList, server::zone::objects::draftschematic::DraftSchematic::getCustomName(), prototype, PlayerObjectDeltaMessage9::setCraftingState(), PlayerObjectDeltaMessage9::setExperimentationPoints(), and state.
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::selectDraftSchematic().
void CraftingSessionImplementation::sendIngredientForUIListen ()
Sends ingredients on ManufactureSchematic::synchronizedUIListen
Definition at line 380 of file CraftingSessionImplementation.cpp.
References crafter, crafterGhost, craftingManager, craftingStation, craftingTool, DraftSlot::insertToMessage(), manufactureSchematic, and prototype.
Referenced by server::zone::objects::player::sessions::crafting::CraftingSession::sendIngredientForUIListen().
void CraftingSessionImplementation::sendSlotMessage (int counter, int message) private
Sends various crafting messages
Definition at line 241 of file CraftingSessionImplementation.cpp.
References crafter.
Referenced by addIngredient(), createManufactureSchematic(), createPrototype(), customization(), experiment(), nextCraftingStage(), and removeIngredient().
void CraftingSessionImplementation::startCreationTasks (int timer, bool practice) private
Starts tasks for counting down and creating item based on complexity
Definition at line 1197 of file CraftingSessionImplementation.cpp.
References crafter, crafterGhost, craftingManager, craftingStation, craftingTool, manufactureSchematic, and prototype.
Referenced by createPrototype().
int CraftingSessionImplementation::startSession () private
Sends the packets and creates the objects to start the crafting session
Get current allowed complexity
Get filtered schematic list based on tool type and complexity
DPlay9 ***********************************
Object Controller Message 102 - Schematic List
Reset session state
Definition at line 55 of file CraftingSessionImplementation.cpp.
References cancelSession(), DeltaMessage::close(), crafter, crafterGhost, craftingStation, craftingTool, currentSchematicList, experimentationPointsTotal, server::zone::objects::scene::SceneObject::getClientObjectCRC(), server::zone::objects::draftschematic::DraftSchematic::getToolTab(), PlayerObjectDeltaMessage9::setClosestCraftingStation(), PlayerObjectDeltaMessage9::setCraftingState(), PlayerObjectDeltaMessage9::setExperimentationEnabled(), PlayerObjectDeltaMessage9::setExperimentationPoints(), and state.
Referenced by initializeSession().
void CraftingSessionImplementation::unlock (bool doLock = true) protected
Definition at line 320 of file CraftingSession.cpp.
References _this.
void CraftingSessionImplementation::wlock (bool doLock = true) protected
Definition at line 312 of file CraftingSession.cpp.
References _this.
void CraftingSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 316 of file CraftingSession.cpp.
References _this.
void CraftingSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 364 of file CraftingSession.cpp.
References writeObjectMembers().
int CraftingSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 371 of file CraftingSession.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class CraftingSession friend
Definition at line 473 of file CraftingSession.h.
Member Data Documentation
WeakReference<CraftingSession*> server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::_this
Definition at line 439 of file CraftingSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addIngredient(), clearSession(), createManufactureSchematic(), createPrototype(), customization(), experiment(), initializeSession(), lock(), nextCraftingStage(), removeIngredient(), rlock(), runlock(), selectDraftSchematic(), unlock(), and wlock().
byte server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::assemblyResult protected
Definition at line 282 of file CraftingSession.h.
Referenced by initialAssembly().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::crafter protected
Definition at line 260 of file CraftingSession.h.
Referenced by addIngredient(), cancelSession(), clearSession(), closeCraftingWindow(), CraftingSessionImplementation(), createManufactureSchematic(), createPrototype(), createPrototypeObject(), customization(), experiment(), finishAssembly(), finishStage1(), finishStage2(), initialAssembly(), initializeSession(), nextCraftingStage(), removeIngredient(), selectDraftSchematic(), sendIngredientForUIListen(), sendSlotMessage(), startCreationTasks(), and startSession().
ManagedWeakReference<PlayerObject* > server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::crafterGhost protected
Definition at line 262 of file CraftingSession.h.
Referenced by addIngredient(), cancelSession(), clearSession(), closeCraftingWindow(), createManufactureSchematic(), createPrototypeObject(), customization(), experiment(), initialAssembly(), initializeSession(), nextCraftingStage(), removeIngredient(), selectDraftSchematic(), sendIngredientForUIListen(), startCreationTasks(), and startSession().
ManagedWeakReference<CraftingManager* > server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::craftingManager protected
Definition at line 268 of file CraftingSession.h.
Referenced by CraftingSessionImplementation(), createManufactureSchematic(), customization(), experiment(), initialAssembly(), initializeSession(), sendIngredientForUIListen(), and startCreationTasks().
ManagedWeakReference<CraftingStation* > server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::craftingStation protected
Definition at line 266 of file CraftingSession.h.
Referenced by addIngredient(), cancelSession(), clearSession(), createManufactureSchematic(), customization(), experiment(), initialAssembly(), initializeSession(), nextCraftingStage(), removeIngredient(), sendIngredientForUIListen(), startCreationTasks(), and startSession().
ManagedWeakReference<CraftingTool* > server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::craftingTool protected
Definition at line 264 of file CraftingSession.h.
Referenced by addIngredient(), cancelSession(), clearSession(), createManufactureSchematic(), createPrototype(), createPrototypeObject(), customization(), experiment(), initialAssembly(), initializeSession(), nextCraftingStage(), removeIngredient(), selectDraftSchematic(), sendIngredientForUIListen(), startCreationTasks(), and startSession().
Vector<ManagedReference<DraftSchematic* > > server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::currentSchematicList protected
Definition at line 280 of file CraftingSession.h.
Referenced by selectDraftSchematic(), and startSession().
int server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::experimentationPointsTotal protected
Definition at line 274 of file CraftingSession.h.
Referenced by experiment(), initialAssembly(), initializeSession(), and startSession().
int server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::experimentationPointsUsed protected
Definition at line 276 of file CraftingSession.h.
Referenced by experiment(), initialAssembly(), and initializeSession().
byte server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::experimentationResult protected
Definition at line 284 of file CraftingSession.h.
Referenced by experiment().
unsigned long long server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::lastExperimentTime protected
Definition at line 286 of file CraftingSession.h.
ManagedWeakReference<ManufactureSchematic* > server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::manufactureSchematic protected
Definition at line 270 of file CraftingSession.h.
Referenced by addIngredient(), addSkillMods(), addWeaponDots(), clearSession(), createManufactureSchematic(), createPrototype(), customization(), experiment(), getSchematic(), initialAssembly(), nextCraftingStage(), removeIngredient(), sendIngredientForUIListen(), and startCreationTasks().
ManagedWeakReference<TangibleObject* > server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::prototype protected
Definition at line 272 of file CraftingSession.h.
Referenced by addIngredient(), addSkillMods(), addWeaponDots(), clearSession(), createManufactureSchematic(), createPrototype(), createPrototypeObject(), customization(), experiment(), initialAssembly(), nextCraftingStage(), removeIngredient(), selectDraftSchematic(), sendIngredientForUIListen(), and startCreationTasks().
byte server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::state protected
Definition at line 278 of file CraftingSession.h.
Referenced by customization(), finishAssembly(), finishStage1(), finishStage2(), getState(), initialAssembly(), nextCraftingStage(), selectDraftSchematic(), and startSession().
VectorMap<String, Reference<CustomizationVariable*> > server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::variables protected
Definition at line 288 of file CraftingSession.h.
Referenced by customization(), and initialAssembly().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/crafting/CraftingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/crafting/CraftingSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/crafting/CraftingSessionImplementation.cpp