Core3: server::zone::objects::player::PlayerObjectImplementation Class Reference
server::zone::objects::player::PlayerObjectImplementation Class Reference
#include <PlayerObject.h>
Public Member Functions
PlayerObjectImplementation ()
PlayerObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void notifyLoadFromDatabase ()
void unload ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void sendBaselinesTo (SceneObject *player)
void sendMessage (BasePacket *msg)
void addOwnedStructure (StructureObject *obj)
void removeOwnedStructure (StructureObject *obj)
int getTotalOwnedStructureCount ()
bool isOwnedStructure (StructureObject *obj)
unsigned long long getOwnedStructure (int i)
int getLotsRemaining ()
bool hasLotsRemaining (int lots)
void notifySceneReady ()
int addExperience (const String &xpType, int xp, bool notifyClient=true)
void removeExperience (const String &xpType, bool notifyClient=true)
bool hasCappedExperience (const String &xpType)
void addWaypoint (WaypointObject *waypoint, bool checkName, bool notifyClient=true)
void setWaypoint (WaypointObject *waypoint, bool notifyClient=true)
WaypointObject * addWaypoint (const String &planet, float positionX, float positionY, bool notifyClient=true)
void removeWaypoint (unsigned long long waypointID, bool notifyClient=true)
void addAbilities (Vector< Ability * > &abilities, bool notifyClient=true)
void addAbility (Ability *ability, bool notifyClient=true)
void removeAbilities (Vector< Ability * > &abilities, bool notifyClient=true)
void removeAbility (Ability *ability, bool notifyClient=true)
bool addSchematics (Vector< ManagedReference< DraftSchematic * > > &schematics, bool notifyClient=true)
void removeSchematics (Vector< ManagedReference< DraftSchematic * > > &schematics, bool notifyClient=true)
bool addRewardedSchematic (DraftSchematic *schematic, short type, int quantity=1, bool notifyClient=true)
void removeRewardedSchematic (DraftSchematic *schematic, bool notifyClient=true)
void decreaseSchematicUseCount (DraftSchematic *schematic)
void setLanguageID (byte language, bool notifyClient=true)
void addFriend (const String &name, bool notifyClient=true)
void removeFriend (const String &name, bool notifyClient=true)
void addIgnore (const String &name, bool notifyClient=true)
void removeIgnore (const String &name, bool notifyClient=true)
void setTitle (const String &characterTitle, bool notifyClient=true)
void setFoodFilling (int newValue, bool notifyClient=true)
void setDrinkFilling (int newValue, bool notifyClient=true)
void increaseFactionStanding (const String &factionName, float amount)
void decreaseFactionStanding (const String &factionName, float amount)
float getFactionStanding (const String &factionName)
WaypointObject * getSurveyWaypoint ()
void setScreenPlayData (const String &screenPlay, const String &variable, const String &data)
String getScreenPlayData (const String &screenPlay, const String &variable)
void clearScreenPlayData (const String &screenPlay)
void activateRecovery ()
void doRecovery ()
void disconnect (bool closeClient, bool doLock)
void reload (ZoneClientSession *client)
void setOffline ()
void setLinkDead ()
void setOnline ()
void setLoggingOut ()
void sendBadgesResponseTo (CreatureObject *player)
void logout (bool doLock)
void setJediState (int state, bool notifyClient=true)
FactionStandingList * getFactionStandingList ()
void setLastNpcConvStr (const String &conv)
void setLastNpcConvMessStr (const String &mess)
String getLastNpcConvStr ()
String getLastNpcConvMessStr ()
String getLastNpcConvOption (int idx)
void addLastNpcConvOptions (const String &option)
int countLastNpcConvOptions ()
void clearLastNpcConvOptions ()
void setConversatingCreature (CreatureObject *creature)
unsigned long long getConversatingCreature ()
void setTrainerCoordinates (const Vector3 &trainer)
Vector3 getTrainerCoordinates ()
void setTrainerZoneName (String &zoneName)
String getTrainerZoneName ()
SortedVector< unsigned long
long > * getPersistentMessages ()
void addPersistentMessage (unsigned long long id)
void dropPersistentMessage (unsigned long long id)
void unloadSpawnedChildren ()
void addToConsentList (const String &name)
bool hasInConsentList (const String &name)
void removeFromConsentList (const String &name)
String getConsentName (int i)
int getConsentListSize ()
String getFactionRank ()
void setFactionRank (const String &rank)
void setCommandMessageString (unsigned int actionCRC, String &message)
void removeCommandMessageString (unsigned int actionCRC)
unsigned long long getDeclaredResidence ()
void setDeclaredResidence (BuildingObject *residence)
void setCloningFacility (BuildingObject *cloningfac)
unsigned long long getCloningFacility ()
void notifyOnline ()
void doDigest (int fillingReduction)
bool isDigesting ()
String getSavedTerrainName ()
void setSavedParentID (unsigned long long id)
void setSavedTerrainName (const String &name)
void setForcePower (int fp, bool notifyClient=true)
void setForcePowerMax (int newValue, bool notifyClient=true)
void activateForceRegen ()
void setForcePowerRegen (int val)
int getForcePowerRegen ()
unsigned long long getSavedParentID ()
unsigned int getNewSuiBoxID (unsigned int type)
bool hasSuiBox (unsigned int boxID)
SuiBox * getSuiBox (unsigned int boxID)
void removeSuiBox (unsigned int boxID, bool closeWindowToClient=false)
void removeSuiBoxType (unsigned int windowType)
bool hasSuiBoxWindowType (unsigned int windowType)
void closeSuiWindowType (unsigned int windowType)
SuiBox * getSuiBoxFromWindowType (unsigned int windowType)
void addSuiBox (SuiBox *sui)
void addPermissionGroup (const String &group, bool updateInRangeBuildingPermissions=false)
void removePermissionGroup (const String &group, bool updateInRangeBuildingPermissions=false)
bool hasPermissionGroup (const String &group)
SortedVector< String > * getPermissionGroups ()
bool isFirstIncapacitationExpired ()
void resetIncapacitationCounter ()
void resetFirstIncapacitationTime ()
void updateIncapacitationCounter ()
bool isFirstIncapacitation ()
byte getIncapacitationCounter ()
void addToDuelList (CreatureObject *targetPlayer)
void removeFromDuelList (CreatureObject *targetPlayer)
CreatureObject * getDuelListObject (int index)
bool requestedDuelTo (CreatureObject *targetPlayer)
bool isDuelListEmpty ()
int getDuelListSize ()
UnicodeString getBiography ()
void notifyOffline ()
void setBadge (unsigned int badge)
void awardBadge (unsigned int badge)
void setTeleporting (bool val)
int getNumBadges ()
int getBadgeTypeCount (byte type)
bool hasFriend (const String &name)
bool isIgnoring (const String &name)
void addReverseFriend (const String &name)
void removeReverseFriend (const String &name)
void sendFriendLists ()
bool hasWaypoint (unsigned long long objectID)
bool hasAbility (const String &ability)
bool hasCommandMessageString (unsigned int actionCRC)
unsigned int getCharacterBitmask ()
String getTitle ()
unsigned int getAdminLevel ()
void setAdminLevel (unsigned int adminlvl)
void setBiography (const UnicodeString &bio)
bool isDeveloper ()
bool isCSR ()
bool isPrivileged ()
void setCharacterBitmask (unsigned int bitmask)
bool setCharacterBit (unsigned int bit, bool notifyClient=false)
bool clearCharacterBit (unsigned int bit, bool notifyClient=false)
void toggleCharacterBit (unsigned int bit)
bool isAFK ()
VectorMap< String, int > * getXpTypeCapList ()
DeltaVectorMap< String, int > * getExperienceList ()
int getForcePower ()
int getForcePowerMax ()
WaypointList * getWaypointList ()
AbilityList * getAbilityList ()
SchematicList * getSchematics ()
DraftSchematic * getSchematic (int i)
Vector< ManagedReference
< DraftSchematic * > > filterSchematicList (CreatureObject *player, Vector< unsigned int > *enabledTabs, int complexityLevel)
int getFoodFilling ()
int getFoodFillingMax ()
int getDrinkFilling ()
int getDrinkFillingMax ()
int getJediState ()
byte getLanguageID ()
DeltaVector< String > * getFriendList ()
bool isTeleporting ()
void addChatRoom (ChatRoom *room)
void removeChatRoom (ChatRoom *room)
void setBankLocation (const String &location)
String getBankLocation ()
DeltaVector< String > * getIgnoreList ()
int getExperience (const String &xp)
void maximizeExperience ()
void activateMissions ()
String getCommandMessageString (unsigned int actionCRC)
bool hasBadge (unsigned int badge)
void clearDisconnectEvent ()
void clearRecoveryEvent ()
bool isOnline ()
bool isOffline ()
bool isLoading ()
bool isLinkDead ()
bool isLoggingIn ()
bool isLoggingOut ()
void setSkillPoints (int points)
void addSkillPoints (int points)
int getSkillPoints ()
ValidatedPosition * getLastValidatedPosition ()
void updateLastValidatedPosition ()
void setSpawnedBlueFrog ()
bool hasSpawnedBlueFrog ()
unsigned int getAccountID ()
unsigned long long getServerMovementTimeDelta ()
Time * getServerMovementTimeStamp ()
void setClientLastMovementStamp (unsigned int stamp)
void updateServerLastMovementStamp ()
void setAccountID (unsigned int id)
int getFactionStatus ()
void setFactionStatus (int status)
unsigned int getClientLastMovementStamp ()
void addHologrindProfession (byte prof)
Vector< byte > * getHologrindProfessions ()
byte getRaceID ()
void setRaceID (byte race)
void setMaximumLots (byte lots)
byte getMaximumLots ()
String getStarterProfession ()
void setStarterProfession (String &profession)
void addToBountyLockList (unsigned long long playerId)
bool isInBountyLockList (unsigned long long playerId)
void removeFromBountyLockList (unsigned long long playerId, bool immediately)
void removeFromBountyLockListDirectly (unsigned long long playerId)
bool isBountyLocked ()
unsigned long long getPerformanceBuffTarget ()
void setPerformanceBuffTarget (unsigned long long target)
void setDebug (bool value)
bool getDebug ()
float getVisibility ()
void setVisibility (float value)
Time getLastVisibilityUpdateTimestamp ()
void addVendor (SceneObject *vendor)
void removeVendor (SceneObject *vendor)
int getVendorCount ()
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
bool isJedi ()
operator const PlayerObject * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::intangible::IntangibleObjectImplementation
IntangibleObjectImplementation ()
IntangibleObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializeTransientMembers ()
bool isIntangibleObject ()
void updateStatus (int newStatus, bool notifyClient=true)
unsigned int getStatus ()
operator const IntangibleObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendTo (SceneObject *player, bool doClose)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
virtual void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
virtual int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isTangibleObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
virtual void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< PlayerObject * > _this
Public Attributes inherited from server::zone::objects::intangible::IntangibleObjectImplementation
WeakReference< IntangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Static Public Attributes
static const int LFG = 1
static const int NEWBIEHELPER = 2
static const int ROLEPLAYER = 4
static const int AFK = 0x80
static const int LD = 0x100
static const int FACTIONRANK = 0x200
static const int ANONYMOUS = 0x80000000
static const int NORMALPLAYER = 0
static const int CSR = 1
static const int DEV = 2
static const int ONLINE = 1
static const int OFFLINE = 2
static const int LINKDEAD = 3
static const int LOGGINGIN = 4
static const int LOGGINGOUT = 5
static const int LOADING = 6
Protected Member Functions
virtual ~PlayerObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::intangible::IntangibleObjectImplementation
virtual ~IntangibleObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
unsigned int characterBitmask
String title
String savedTerrainName
unsigned long long savedParentID
Badges badges
int forcePower
int forcePowerMax
int forcePowerRegen
int foodFilling
int foodFillingMax
int drinkFilling
int drinkFillingMax
String starterProfession
String bankLocation
bool teleporting
SortedVector< unsigned long long > ownedStructures
SortedVector< unsigned long long > ownedVendors
byte maximumLots
int jediState
unsigned int adminLevel
byte languageID
VectorMap< String, int > xpTypeCapList
VectorMap< unsigned int, String > commandMessageStrings
DeltaVectorMap< String, int > experienceList
WaypointList waypointList
AbilityList abilityList
FriendList friendList
IgnoreList ignoreList
FactionStandingList factionStandingList
SchematicList schematicList
byte incapacitationCounter
unsigned int suiBoxNextID
VectorMap< unsigned int,
ManagedReference< SuiBox * > > suiBoxes
SortedVector< ManagedReference
< ChatRoom * > > chatRooms
SortedVector< ManagedReference
< CreatureObject * > > duelList
BountyHunterTefRemovalTaskMap bountyLockList
unsigned long long declaredResidence
unsigned long long cloningFacility
SortedVector< unsigned long long > persistentMessages
UnicodeString biography
SortedVector< String > consentList
String lastNpcConvoMessage
String lastNpcConvo
Vector< String > lastNpcConvoOptions
unsigned long long conversatingCreature
Vector3 trainerCoordinates
String trainerZoneName
Reference
< PlayerDisconnectEvent * > disconnectEvent
Reference< PlayerRecoveryEvent * > recoveryEvent
Time logoutTimeStamp
int onlineStatus
int skillPoints
int pvpRating
int factionStatus
bool spawnedBlueFrog
Vector< byte > hologrindProfessions
unsigned int clientLastMovementStamp
Time serverLastMovementStamp
ValidatedPosition lastValidatedPosition
unsigned int accountID
byte raceID
VectorMap< String, String > screenPlayData
SortedVector< String > permissionGroups
unsigned long long performanceBuffTarget
bool debugOutput
float visibility
Time lastVisibilityUpdateTimestamp
Time lastDigestion
Protected Attributes inherited from server::zone::objects::intangible::IntangibleObjectImplementation
unsigned int status
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Private Member Functions
void updateBountyPvpStatus (unsigned long long playerId)
Friends
class PlayerObject
Detailed Description
Definition at line 939 of file PlayerObject.h.
Constructor & Destructor Documentation
PlayerObjectImplementation::PlayerObjectImplementation ()
Definition at line 3977 of file PlayerObject.cpp.
References _initializeImplementation(), accountID, bankLocation, clientLastMovementStamp, cloningFacility, commandMessageStrings, consentList, conversatingCreature, debugOutput, declaredResidence, duelList, factionStatus, forcePower, forcePowerMax, forcePowerRegen, jediState, lastDigestion, lastVisibilityUpdateTimestamp, maximumLots, performanceBuffTarget, persistentMessages, raceID, savedParentID, setOffline(), skillPoints, spawnedBlueFrog, suiBoxNextID, teleporting, trainerZoneName, and visibility.
PlayerObjectImplementation::PlayerObjectImplementation (DummyConstructorParameter * param)
Definition at line 3097 of file PlayerObject.cpp.
References _initializeImplementation().
PlayerObjectImplementation::~PlayerObjectImplementation () protected virtual
Definition at line 3102 of file PlayerObject.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * PlayerObjectImplementation::_getStub ()
Definition at line 3120 of file PlayerObject.cpp.
References _this.
void PlayerObjectImplementation::_initializeImplementation () protected
Definition at line 3107 of file PlayerObject.cpp.
References _serializationHelperMethod(), and _this.
Referenced by PlayerObjectImplementation().
void PlayerObjectImplementation::_serializationHelperMethod () protected
Definition at line 3156 of file PlayerObject.cpp.
Referenced by _initializeImplementation().
void PlayerObjectImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 3115 of file PlayerObject.cpp.
References _this.
Referenced by server::zone::objects::player::PlayerObject::PlayerObject().
void PlayerObjectImplementation::activateForceRegen ()
Definition at line 1625 of file PlayerObjectImplementation.cpp.
References getForcePower(), getForcePowerMax(), getForcePowerRegen(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::creature::CreatureObject::isMeditating(), and setForcePower().
Referenced by server::zone::objects::player::PlayerObject::activateForceRegen(), and doRecovery().
void PlayerObjectImplementation::activateMissions ()
Definition at line 1558 of file PlayerObjectImplementation.cpp.
References server::zone::objects::mission::MissionObjective::activate(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), and server::zone::objects::scene::SceneObject::getSlottedObject().
Referenced by server::zone::objects::player::PlayerObject::activateMissions(), and setOnline().
void PlayerObjectImplementation::activateRecovery ()
Definition at line 1421 of file PlayerObjectImplementation.cpp.
References _this, and recoveryEvent.
Referenced by server::zone::objects::player::PlayerObject::activateRecovery(), doRecovery(), notifyLoadFromDatabase(), and setLinkDead().
void PlayerObjectImplementation::addAbilities (Vector< Ability * > & abilities, bool notifyClient = true)
Adds new abilities commands to player
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
abilities Vector of abilities to add
notifyClient determines whether to update the client with the changes
Definition at line 681 of file PlayerObjectImplementation.cpp.
References _this, abilityList, AbilityList::add(), DeltaMessage::close(), sendMessage(), and DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::PlayerObject::addAbilities().
void PlayerObjectImplementation::addAbility (Ability * ability, bool notifyClient = true)
Definition at line 669 of file PlayerObjectImplementation.cpp.
References _this, abilityList, AbilityList::add(), DeltaMessage::close(), sendMessage(), and DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::PlayerObject::addAbility().
void PlayerObjectImplementation::addChatRoom (ChatRoom * room)
Definition at line 4628 of file PlayerObject.cpp.
References chatRooms.
Referenced by server::zone::objects::player::PlayerObject::addChatRoom().
int PlayerObjectImplementation::addExperience (const String & xpType, int xp, bool notifyClient = true)
Adds experience of a type to the player's experience pool.
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
xpType The string value for the type of experience to add.
xp The value of experience to add.
notifyClient Boolean to determing whether the client should receive a delta packet for the experience gain.
Returns
returns total experience awarded
Definition at line 526 of file PlayerObjectImplementation.cpp.
References _this, DeltaMessage::close(), DeltaVectorMap< K, V >::contains(), experienceList, DeltaVectorMap< K, V >::get(), removeExperience(), sendMessage(), DeltaVectorMap< K, V >::set(), DeltaMessage::startUpdate(), and xpTypeCapList.
Referenced by server::zone::objects::player::PlayerObject::addExperience(), and maximizeExperience().
void PlayerObjectImplementation::addFriend (const String & name, bool notifyClient = true)
Adds a friend to the friend list
Precondition
{ this is locked}
Postcondition
{ this is locked }
Parameters
name friends name
notifyClient determines whether to update the client with the changes
Definition at line 893 of file PlayerObjectImplementation.cpp.
References _this, server::zone::objects::player::PlayerObject::addReverseFriend(), DeltaMessage::close(), friendList, server::zone::ZoneServer::getObject(), server::zone::managers::player::PlayerManager::getObjectID(), server::zone::objects::scene::SceneObjectImplementation::getParent(), PlayerList< DeltaUpdate >::insertToDeltaMessage(), server::zone::objects::scene::SceneObjectImplementation::server, server::chat::StringIdChatParameter::setTT(), and server::zone::objects::scene::SceneObject::updateToDatabase().
Referenced by server::zone::objects::player::PlayerObject::addFriend().
void PlayerObjectImplementation::addHologrindProfession (byte prof)
Definition at line 4785 of file PlayerObject.cpp.
References hologrindProfessions.
Referenced by server::zone::objects::player::PlayerObject::addHologrindProfession().
void PlayerObjectImplementation::addIgnore (const String & name, bool notifyClient = true)
Adds a player to the ignore list
Precondition
{ this is locked}
Postcondition
{ this is locked }
Parameters
name player name
notifyClient determines whether to update the client with the changes
Definition at line 1015 of file PlayerObjectImplementation.cpp.
References _this, DeltaMessage::close(), server::zone::objects::scene::SceneObjectImplementation::getParent(), ignoreList, PlayerList< DeltaUpdate >::insertToDeltaMessage(), and server::chat::StringIdChatParameter::setTT().
Referenced by server::zone::objects::player::PlayerObject::addIgnore().
void PlayerObjectImplementation::addLastNpcConvOptions (const String & option)
Definition at line 4145 of file PlayerObject.cpp.
References lastNpcConvoOptions.
Referenced by server::zone::objects::player::PlayerObject::addLastNpcConvOptions().
void PlayerObjectImplementation::addOwnedStructure (StructureObject * obj)
Definition at line 4044 of file PlayerObject.cpp.
References _this, server::zone::objects::scene::SceneObject::getObjectID(), and ownedStructures.
Referenced by server::zone::objects::player::PlayerObject::addOwnedStructure().
void PlayerObjectImplementation::addPermissionGroup (const String & group, bool updateInRangeBuildingPermissions = false)
Definition at line 1735 of file PlayerObjectImplementation.cpp.
References server::zone::objects::building::BuildingObject::broadcastCellPermissions(), server::zone::objects::scene::SceneObjectImplementation::getParent(), permissionGroups, and server::zone::objects::scene::SceneObjectImplementation::zone.
Referenced by server::zone::objects::player::PlayerObject::addPermissionGroup().
void PlayerObjectImplementation::addPersistentMessage (unsigned long long id)
Definition at line 4189 of file PlayerObject.cpp.
References persistentMessages.
Referenced by server::zone::objects::player::PlayerObject::addPersistentMessage().
void PlayerObjectImplementation::addReverseFriend (const String & name)
Definition at line 4478 of file PlayerObject.cpp.
References friendList.
Referenced by server::zone::objects::player::PlayerObject::addReverseFriend().
bool PlayerObjectImplementation::addRewardedSchematic (DraftSchematic * schematic, short type, int quantity = 1, bool notifyClient = true)
Definition at line 775 of file PlayerObjectImplementation.cpp.
References _this, SchematicList::addRewardedSchematic(), addSchematics(), SchematicList::contains(), SchematicList::LOOT, schematicList, server::zone::objects::draftschematic::DraftSchematic::sendDraftSlotsTo(), server::zone::objects::draftschematic::DraftSchematic::sendResourceWeightsTo(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::objects::player::PlayerObject::addRewardedSchematic().
bool PlayerObjectImplementation::addSchematics (Vector< ManagedReference< DraftSchematic * > > & schematics, bool notifyClient = true)
If schematic is not already in the schematic list, we want to send it if not, we don't want to send it to the datapad
Definition at line 737 of file PlayerObjectImplementation.cpp.
References _this, SchematicList::add(), DeltaMessage::close(), SchematicList::contains(), schematicList, sendMessage(), and DeltaMessage::startUpdate().
Referenced by addRewardedSchematic(), and server::zone::objects::player::PlayerObject::addSchematics().
void PlayerObjectImplementation::addSkillPoints (int points)
Definition at line 4711 of file PlayerObject.cpp.
References skillPoints.
Referenced by server::zone::objects::player::PlayerObject::addSkillPoints().
void PlayerObjectImplementation::addSuiBox (SuiBox * sui)
Definition at line 4378 of file PlayerObject.cpp.
References server::zone::objects::player::sui::SuiBox::getBoxID(), and suiBoxes.
Referenced by server::zone::objects::player::PlayerObject::addSuiBox().
void PlayerObjectImplementation::addToBountyLockList (unsigned long long playerId)
Definition at line 1656 of file PlayerObjectImplementation.cpp.
References _this, bountyLockList, and updateBountyPvpStatus().
Referenced by server::zone::objects::player::PlayerObject::addToBountyLockList().
void PlayerObjectImplementation::addToConsentList (const String & name)
Definition at line 4199 of file PlayerObject.cpp.
References consentList.
Referenced by server::zone::objects::player::PlayerObject::addToConsentList().
void PlayerObjectImplementation::addToDuelList (CreatureObject * targetPlayer)
Definition at line 4413 of file PlayerObject.cpp.
References duelList.
Referenced by server::zone::objects::player::PlayerObject::addToDuelList().
void PlayerObjectImplementation::addVendor (SceneObject * vendor)
Definition at line 4862 of file PlayerObject.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), and ownedVendors.
Referenced by server::zone::objects::player::PlayerObject::addVendor().
void PlayerObjectImplementation::addWaypoint (WaypointObject * waypoint, bool checkName, bool notifyClient = true)
Adds waypoint object to waypointList
Precondition
{ this is locked }
Postcondition
{ this is locked, waypoint object is in the list }
Parameters
waypoint waypoint object to add
checkName determines whether to remove existing Waypoint with equal customName
notifyClient determines whether to update the client with the changes
Definition at line 609 of file PlayerObjectImplementation.cpp.
References DeltaVectorMap< K, V >::contains(), WaypointList::find(), server::zone::objects::scene::SceneObject::getCustomObjectName(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::waypoint::WaypointObject::getSpecialTypeID(), WaypointList::getWaypointBySpecialType(), removeWaypoint(), setWaypoint(), and waypointList.
Referenced by server::zone::objects::player::PlayerObject::addWaypoint(), and addWaypoint().
WaypointObject * PlayerObjectImplementation::addWaypoint (const String & planet, float positionX, float positionY, bool notifyClient = true)
Adds a new waypoint with the specified coordinates
Precondition
{ this is locked }
Postcondition
{ this is locked, waypoint object is in the list }
Parameters
planet planet where waypoint will be created
positionX waypoint position X
positionY waypoint position Y
notifyClient determines whether to update the client with the changes
Definition at line 658 of file PlayerObjectImplementation.cpp.
References addWaypoint(), server::zone::ZoneServer::createObject(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), and server::zone::objects::waypoint::WaypointObject::setPlanetCRC().
void PlayerObjectImplementation::awardBadge (unsigned int badge)
Definition at line 445 of file PlayerObjectImplementation.cpp.
References _this, server::zone::managers::player::PlayerManager::awardBadge(), server::zone::ZoneServer::getPlayerManager(), and server::zone::objects::scene::SceneObjectImplementation::getZoneServer().
Referenced by server::zone::objects::player::PlayerObject::awardBadge().
bool PlayerObjectImplementation::clearCharacterBit (unsigned int bit, bool notifyClient = false)
Definition at line 423 of file PlayerObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), characterBitmask, DeltaMessage::close(), and PlayerObjectDeltaMessage3::updateCharacterBitmask().
Referenced by server::zone::objects::player::PlayerObject::clearCharacterBit(), setOnline(), and toggleCharacterBit().
void PlayerObjectImplementation::clearDisconnectEvent ()
Definition at line 1529 of file PlayerObjectImplementation.cpp.
References disconnectEvent.
Referenced by server::zone::objects::player::PlayerObject::clearDisconnectEvent().
void PlayerObjectImplementation::clearLastNpcConvOptions ()
Definition at line 4155 of file PlayerObject.cpp.
References lastNpcConvoOptions.
Referenced by server::zone::objects::player::PlayerObject::clearLastNpcConvOptions().
void PlayerObjectImplementation::clearRecoveryEvent ()
Definition at line 1533 of file PlayerObjectImplementation.cpp.
References recoveryEvent.
Referenced by server::zone::objects::player::PlayerObject::clearRecoveryEvent().
void PlayerObjectImplementation::clearScreenPlayData (const String & screenPlay)
Definition at line 1649 of file PlayerObjectImplementation.cpp.
References screenPlayData.
Referenced by server::zone::objects::player::PlayerObject::clearScreenPlayData().
void PlayerObjectImplementation::closeSuiWindowType (unsigned int windowType)
Definition at line 4345 of file PlayerObject.cpp.
References getSuiBoxFromWindowType(), hasSuiBoxWindowType(), removeSuiBox(), and sendMessage().
Referenced by server::zone::objects::player::PlayerObject::closeSuiWindowType().
int PlayerObjectImplementation::countLastNpcConvOptions ()
Definition at line 4150 of file PlayerObject.cpp.
References lastNpcConvoOptions.
Referenced by server::zone::objects::player::PlayerObject::countLastNpcConvOptions().
void PlayerObjectImplementation::decreaseFactionStanding (const String & factionName, float amount)
Definition at line 1271 of file PlayerObjectImplementation.cpp.
References factionStandingList, FactionStandingList::get(), FactionStandingList::put(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), server::zone::objects::scene::variables::StringId::setStringId(), and server::chat::StringIdChatParameter::setTO().
Referenced by server::zone::objects::player::PlayerObject::decreaseFactionStanding().
void PlayerObjectImplementation::decreaseSchematicUseCount (DraftSchematic * schematic)
Definition at line 816 of file PlayerObjectImplementation.cpp.
References SchematicList::decreaseSchematicUseCount(), removeSchematics(), and schematicList.
Referenced by server::zone::objects::player::PlayerObject::decreaseSchematicUseCount().
void PlayerObjectImplementation::destroyObjectFromDatabase (bool destroyContainedObjects = false) virtual
Destroys this object from database
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
destroyContainedObjects if true, will destroy from database all its contained objects
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 1793 of file PlayerObjectImplementation.cpp.
References server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), ownedStructures, and server::zone::objects::scene::SceneObjectImplementation::zone.
Referenced by server::zone::objects::player::PlayerObject::destroyObjectFromDatabase().
void PlayerObjectImplementation::disconnect (bool closeClient, bool doLock)
Definition at line 1483 of file PlayerObjectImplementation.cpp.
References server::zone::ZoneClientSession::closeConnection(), disconnectEvent, server::zone::objects::scene::SceneObjectImplementation::info(), isLinkDead(), isOnline(), setLinkDead(), setOffline(), and unload().
Referenced by server::zone::objects::player::PlayerObject::disconnect().
void PlayerObjectImplementation::doDigest (int fillingReduction)
Definition at line 868 of file PlayerObjectImplementation.cpp.
References drinkFilling, foodFilling, isDigesting(), setDrinkFilling(), and setFoodFilling().
Referenced by server::zone::objects::player::PlayerObject::doDigest(), and doRecovery().
void PlayerObjectImplementation::doRecovery ()
Definition at line 1341 of file PlayerObjectImplementation.cpp.
References DamageOverTimeList::activateDots(), activateForceRegen(), server::zone::objects::creature::CreatureObject::activateHAMRegeneration(), activateRecovery(), server::zone::objects::creature::CreatureObject::activateStateRecovery(), server::zone::ZoneClientSession::closeConnection(), doDigest(), server::zone::objects::creature::CreatureObject::getClient(), server::zone::objects::creature::CreatureObject::getCommandQueue(), server::zone::objects::creature::CreatureObject::getCooldownTimerMap(), server::zone::objects::creature::CreatureObject::getDamageOverTimeList(), getForcePower(), getForcePowerMax(), server::zone::Zone::getPlanetManager(), server::zone::objects::creature::CreatureObject::getTargetID(), server::zone::managers::planet::PlanetManager::getWeatherManager(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), DamageOverTimeList::hasDot(), server::zone::objects::scene::SceneObjectImplementation::info(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::creature::CreatureObject::isInCombat(), isLinkDead(), server::zone::objects::creature::CreatureObject::isNextActionPast(), DamageOverTimeList::isNextTickPast(), CooldownTimerMap::isPast(), server::zone::objects::creature::CreatureObject::isPeaced(), lastDigestion, logoutTimeStamp, server::zone::objects::creature::CreatureObject::sendExecuteConsoleCommand(), server::zone::managers::weather::WeatherManager::sendWeatherTo(), setOffline(), unload(), and CooldownTimerMap::updateToCurrentAndAddMili().
Referenced by server::zone::objects::player::PlayerObject::doRecovery(), and setOnline().
void PlayerObjectImplementation::dropPersistentMessage (unsigned long long id)
Definition at line 4194 of file PlayerObject.cpp.
References persistentMessages.
Referenced by server::zone::objects::player::PlayerObject::dropPersistentMessage().
Vector< ManagedReference< DraftSchematic * > > PlayerObjectImplementation::filterSchematicList (CreatureObject * player, Vector< unsigned int > * enabledTabs, int complexityLevel)
Definition at line 885 of file PlayerObjectImplementation.cpp.
References _this, SchematicList::filterSchematicList(), and schematicList.
Referenced by server::zone::objects::player::PlayerObject::filterSchematicList().
void PlayerObjectImplementation::finalize ()
Definition at line 4041 of file PlayerObject.cpp.
Referenced by ~PlayerObjectImplementation().
AbilityList * PlayerObjectImplementation::getAbilityList ()
Definition at line 4573 of file PlayerObject.cpp.
References abilityList.
Referenced by server::zone::objects::player::PlayerObject::getAbilityList(), and PlayerObjectMessage9::PlayerObjectMessage9().
unsigned int PlayerObjectImplementation::getAccountID ()
Definition at line 4745 of file PlayerObject.cpp.
References accountID.
Referenced by server::zone::objects::player::PlayerObject::getAccountID().
unsigned int PlayerObjectImplementation::getAdminLevel ()
Definition at line 4513 of file PlayerObject.cpp.
References adminLevel.
Referenced by server::zone::objects::player::PlayerObject::getAdminLevel().
int PlayerObjectImplementation::getBadgeTypeCount (byte type)
Definition at line 4463 of file PlayerObject.cpp.
References badges.
Referenced by server::zone::objects::player::PlayerObject::getBadgeTypeCount().
String PlayerObjectImplementation::getBankLocation ()
Definition at line 4643 of file PlayerObject.cpp.
References bankLocation.
Referenced by server::zone::objects::player::PlayerObject::getBankLocation().
UnicodeString PlayerObjectImplementation::getBiography ()
Definition at line 4443 of file PlayerObject.cpp.
References biography.
Referenced by server::zone::objects::player::PlayerObject::getBiography().
unsigned int PlayerObjectImplementation::getCharacterBitmask ()
Definition at line 4503 of file PlayerObject.cpp.
References characterBitmask.
Referenced by server::zone::objects::player::PlayerObject::getCharacterBitmask().
unsigned int PlayerObjectImplementation::getClientLastMovementStamp ()
Definition at line 4780 of file PlayerObject.cpp.
References clientLastMovementStamp.
Referenced by server::zone::objects::player::PlayerObject::getClientLastMovementStamp().
unsigned long long PlayerObjectImplementation::getCloningFacility ()
Definition at line 4267 of file PlayerObject.cpp.
References cloningFacility.
Referenced by server::zone::objects::player::PlayerObject::getCloningFacility().
String PlayerObjectImplementation::getCommandMessageString (unsigned int actionCRC)
Definition at line 4666 of file PlayerObject.cpp.
References commandMessageStrings.
Referenced by server::zone::objects::player::PlayerObject::getCommandMessageString().
int PlayerObjectImplementation::getConsentListSize ()
Definition at line 4219 of file PlayerObject.cpp.
References consentList.
Referenced by server::zone::objects::player::PlayerObject::getConsentListSize().
String PlayerObjectImplementation::getConsentName (int i)
Definition at line 4214 of file PlayerObject.cpp.
References consentList.
Referenced by server::zone::objects::player::PlayerObject::getConsentName().
unsigned long long PlayerObjectImplementation::getConversatingCreature ()
Definition at line 4169 of file PlayerObject.cpp.
References conversatingCreature.
Referenced by server::zone::objects::player::PlayerObject::getConversatingCreature().
bool PlayerObjectImplementation::getDebug ()
Definition at line 4840 of file PlayerObject.cpp.
References debugOutput.
Referenced by server::zone::objects::player::PlayerObject::getDebug().
unsigned long long PlayerObjectImplementation::getDeclaredResidence ()
Definition at line 4244 of file PlayerObject.cpp.
References declaredResidence.
Referenced by server::zone::objects::player::PlayerObject::getDeclaredResidence(), and removeOwnedStructure().
int PlayerObjectImplementation::getDrinkFilling ()
Definition at line 4598 of file PlayerObject.cpp.
References drinkFilling.
Referenced by server::zone::objects::player::PlayerObject::getDrinkFilling(), isDigesting(), and PlayerObjectMessage9::PlayerObjectMessage9().
int PlayerObjectImplementation::getDrinkFillingMax ()
Definition at line 4603 of file PlayerObject.cpp.
References drinkFillingMax.
Referenced by server::zone::objects::player::PlayerObject::getDrinkFillingMax(), and PlayerObjectMessage9::PlayerObjectMessage9().
CreatureObject * PlayerObjectImplementation::getDuelListObject (int index)
Definition at line 4423 of file PlayerObject.cpp.
References duelList.
Referenced by server::zone::objects::player::PlayerObject::getDuelListObject().
int PlayerObjectImplementation::getDuelListSize ()
Definition at line 4438 of file PlayerObject.cpp.
References duelList.
Referenced by server::zone::objects::player::PlayerObject::getDuelListSize().
int PlayerObjectImplementation::getExperience (const String & xp)
Definition at line 4653 of file PlayerObject.cpp.
References experienceList.
Referenced by server::zone::objects::player::PlayerObject::getExperience().
DeltaVectorMap< String, int > * PlayerObjectImplementation::getExperienceList ()
Definition at line 4553 of file PlayerObject.cpp.
References experienceList.
Referenced by server::zone::objects::player::PlayerObject::getExperienceList(), and PlayerObjectMessage8::PlayerObjectMessage8().
String PlayerObjectImplementation::getFactionRank ()
Definition at line 4224 of file PlayerObject.cpp.
References factionStandingList.
Referenced by server::zone::objects::player::PlayerObject::getFactionRank().
float PlayerObjectImplementation::getFactionStanding (const String & factionName)
Definition at line 1298 of file PlayerObjectImplementation.cpp.
References factionStandingList, and FactionStandingList::getFactionStanding().
Referenced by server::zone::objects::player::PlayerObject::getFactionStanding().
FactionStandingList * PlayerObjectImplementation::getFactionStandingList ()
Gets the faction point list.
Definition at line 4115 of file PlayerObject.cpp.
References factionStandingList.
Referenced by server::zone::objects::player::PlayerObject::getFactionStandingList().
int PlayerObjectImplementation::getFactionStatus ()
Definition at line 4775 of file PlayerObject.cpp.
References factionStatus.
Referenced by server::zone::objects::player::PlayerObject::getFactionStatus().
int PlayerObjectImplementation::getFoodFilling ()
Definition at line 4588 of file PlayerObject.cpp.
References foodFilling.
Referenced by server::zone::objects::player::PlayerObject::getFoodFilling(), isDigesting(), and PlayerObjectMessage9::PlayerObjectMessage9().
int PlayerObjectImplementation::getFoodFillingMax ()
Definition at line 4593 of file PlayerObject.cpp.
References foodFillingMax.
Referenced by server::zone::objects::player::PlayerObject::getFoodFillingMax(), and PlayerObjectMessage9::PlayerObjectMessage9().
int PlayerObjectImplementation::getForcePower ()
Definition at line 4558 of file PlayerObject.cpp.
References forcePower.
Referenced by activateForceRegen(), doRecovery(), server::zone::objects::player::PlayerObject::getForcePower(), loadTemplateData(), PlayerObjectMessage8::PlayerObjectMessage8(), setForcePower(), and PlayerObjectDeltaMessage8::updateForcePower().
int PlayerObjectImplementation::getForcePowerMax ()
Definition at line 4563 of file PlayerObject.cpp.
References forcePowerMax.
Referenced by activateForceRegen(), doRecovery(), server::zone::objects::player::PlayerObject::getForcePowerMax(), loadTemplateData(), PlayerObjectMessage8::PlayerObjectMessage8(), setForcePowerMax(), and PlayerObjectDeltaMessage8::updateForcePowerMax().
int PlayerObjectImplementation::getForcePowerRegen ()
Definition at line 4305 of file PlayerObject.cpp.
References forcePowerRegen.
Referenced by activateForceRegen(), server::zone::objects::player::PlayerObject::getForcePowerRegen(), and loadTemplateData().
DeltaVector< String > * PlayerObjectImplementation::getFriendList ()
Definition at line 4618 of file PlayerObject.cpp.
References friendList.
Referenced by server::zone::objects::player::PlayerObject::getFriendList().
Vector< byte > * PlayerObjectImplementation::getHologrindProfessions ()
Definition at line 4790 of file PlayerObject.cpp.
References hologrindProfessions.
Referenced by server::zone::objects::player::PlayerObject::getHologrindProfessions().
DeltaVector< String > * PlayerObjectImplementation::getIgnoreList ()
Definition at line 4648 of file PlayerObject.cpp.
References ignoreList.
Referenced by server::zone::objects::player::PlayerObject::getIgnoreList().
byte PlayerObjectImplementation::getIncapacitationCounter ()
Definition at line 4408 of file PlayerObject.cpp.
References incapacitationCounter.
Referenced by server::zone::objects::player::PlayerObject::getIncapacitationCounter().
int PlayerObjectImplementation::getJediState ()
Definition at line 4608 of file PlayerObject.cpp.
References jediState.
Referenced by server::zone::objects::player::PlayerObject::getJediState(), loadTemplateData(), and PlayerObjectMessage9::PlayerObjectMessage9().
byte PlayerObjectImplementation::getLanguageID ()
Definition at line 4613 of file PlayerObject.cpp.
References languageID.
Referenced by server::zone::objects::player::PlayerObject::getLanguageID(), and PlayerObjectMessage9::PlayerObjectMessage9().
String PlayerObjectImplementation::getLastNpcConvMessStr ()
Definition at line 4135 of file PlayerObject.cpp.
References lastNpcConvoMessage.
Referenced by server::zone::objects::player::PlayerObject::getLastNpcConvMessStr().
String PlayerObjectImplementation::getLastNpcConvOption (int idx)
Definition at line 4140 of file PlayerObject.cpp.
References lastNpcConvoOptions.
Referenced by server::zone::objects::player::PlayerObject::getLastNpcConvOption().
String PlayerObjectImplementation::getLastNpcConvStr ()
Definition at line 4130 of file PlayerObject.cpp.
References lastNpcConvo.
Referenced by server::zone::objects::player::PlayerObject::getLastNpcConvStr().
ValidatedPosition * PlayerObjectImplementation::getLastValidatedPosition ()
Definition at line 4721 of file PlayerObject.cpp.
References lastValidatedPosition.
Referenced by server::zone::objects::player::PlayerObject::getLastValidatedPosition().
Time PlayerObjectImplementation::getLastVisibilityUpdateTimestamp ()
Definition at line 1723 of file PlayerObjectImplementation.cpp.
References lastVisibilityUpdateTimestamp.
Referenced by server::zone::objects::player::PlayerObject::getLastVisibilityUpdateTimestamp().
int PlayerObjectImplementation::getLotsRemaining ()
Definition at line 1814 of file PlayerObjectImplementation.cpp.
References _this, server::zone::objects::structure::StructureObject::getLotSize(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), maximumLots, and ownedStructures.
Referenced by server::zone::objects::player::PlayerObject::getLotsRemaining(), and hasLotsRemaining().
byte PlayerObjectImplementation::getMaximumLots ()
Definition at line 4810 of file PlayerObject.cpp.
References maximumLots.
Referenced by server::zone::objects::player::PlayerObject::getMaximumLots().
uint32 PlayerObjectImplementation::getNewSuiBoxID (unsigned int type)
Definition at line 1247 of file PlayerObjectImplementation.cpp.
References suiBoxNextID.
Referenced by server::zone::objects::player::PlayerObject::getNewSuiBoxID().
int PlayerObjectImplementation::getNumBadges ()
Definition at line 4458 of file PlayerObject.cpp.
References badges.
Referenced by server::zone::objects::player::PlayerObject::getNumBadges().
unsigned long long PlayerObjectImplementation::getOwnedStructure (int i)
Definition at line 4080 of file PlayerObject.cpp.
References _this, and ownedStructures.
Referenced by server::zone::objects::player::PlayerObject::getOwnedStructure().
unsigned long long PlayerObjectImplementation::getPerformanceBuffTarget ()
Definition at line 4825 of file PlayerObject.cpp.
References performanceBuffTarget.
Referenced by server::zone::objects::player::PlayerObject::getPerformanceBuffTarget().
SortedVector< String > * PlayerObjectImplementation::getPermissionGroups ()
Definition at line 4385 of file PlayerObject.cpp.
References permissionGroups.
Referenced by server::zone::objects::player::PlayerObject::getPermissionGroups().
SortedVector< unsigned long long > * PlayerObjectImplementation::getPersistentMessages ()
Definition at line 4184 of file PlayerObject.cpp.
References persistentMessages.
Referenced by server::zone::objects::player::PlayerObject::getPersistentMessages().
byte PlayerObjectImplementation::getRaceID ()
Definition at line 4795 of file PlayerObject.cpp.
References raceID.
Referenced by server::zone::objects::player::PlayerObject::getRaceID().
unsigned long long PlayerObjectImplementation::getSavedParentID ()
Definition at line 4310 of file PlayerObject.cpp.
References savedParentID.
Referenced by server::zone::objects::player::PlayerObject::getSavedParentID().
String PlayerObjectImplementation::getSavedTerrainName ()
Definition at line 4285 of file PlayerObject.cpp.
References savedTerrainName.
Referenced by server::zone::objects::player::PlayerObject::getSavedTerrainName().
DraftSchematic * PlayerObjectImplementation::getSchematic (int i)
Definition at line 4583 of file PlayerObject.cpp.
References schematicList.
Referenced by server::zone::objects::player::PlayerObject::getSchematic().
SchematicList * PlayerObjectImplementation::getSchematics ()
Definition at line 4578 of file PlayerObject.cpp.
References schematicList.
Referenced by server::zone::objects::player::PlayerObject::getSchematics(), and PlayerObjectMessage9::PlayerObjectMessage9().
String PlayerObjectImplementation::getScreenPlayData (const String & screenPlay, const String & variable)
Definition at line 4097 of file PlayerObject.cpp.
References screenPlayData.
Referenced by server::zone::objects::player::PlayerObject::getScreenPlayData().
unsigned long long PlayerObjectImplementation::getServerMovementTimeDelta ()
Definition at line 4750 of file PlayerObject.cpp.
References serverLastMovementStamp.
Referenced by server::zone::objects::player::PlayerObject::getServerMovementTimeDelta().
Time * PlayerObjectImplementation::getServerMovementTimeStamp ()
Definition at line 4755 of file PlayerObject.cpp.
References serverLastMovementStamp.
Referenced by server::zone::objects::player::PlayerObject::getServerMovementTimeStamp().
int PlayerObjectImplementation::getSkillPoints ()
Definition at line 4716 of file PlayerObject.cpp.
References skillPoints.
Referenced by server::zone::objects::player::PlayerObject::getSkillPoints().
String PlayerObjectImplementation::getStarterProfession ()
Definition at line 4815 of file PlayerObject.cpp.
References starterProfession.
Referenced by server::zone::objects::player::PlayerObject::getStarterProfession().
SuiBox * PlayerObjectImplementation::getSuiBox (unsigned int boxID)
Definition at line 4320 of file PlayerObject.cpp.
References suiBoxes.
Referenced by server::zone::objects::player::PlayerObject::getSuiBox().
SuiBox * PlayerObjectImplementation::getSuiBoxFromWindowType (unsigned int windowType)
Definition at line 4360 of file PlayerObject.cpp.
References suiBoxes.
Referenced by closeSuiWindowType(), server::zone::objects::player::PlayerObject::getSuiBoxFromWindowType(), notifySceneReady(), and removeSuiBoxType().
WaypointObject * PlayerObjectImplementation::getSurveyWaypoint ()
Returns the active SurveyWaypoint
Definition at line 1538 of file PlayerObjectImplementation.cpp.
References DeltaVectorMap< K, V >::get(), WaypointList::getWaypointBySpecialType(), and getWaypointList().
Referenced by server::zone::objects::player::PlayerObject::getSurveyWaypoint().
String PlayerObjectImplementation::getTitle ()
Definition at line 4508 of file PlayerObject.cpp.
References title.
Referenced by server::zone::objects::player::PlayerObject::getTitle().
int PlayerObjectImplementation::getTotalOwnedStructureCount ()
Definition at line 4065 of file PlayerObject.cpp.
References _this, and ownedStructures.
Referenced by server::zone::objects::player::PlayerObject::getTotalOwnedStructureCount().
Vector3 PlayerObjectImplementation::getTrainerCoordinates ()
Definition at line 1727 of file PlayerObjectImplementation.cpp.
References trainerCoordinates.
Referenced by server::zone::objects::player::PlayerObject::getTrainerCoordinates().
String PlayerObjectImplementation::getTrainerZoneName ()
Definition at line 4179 of file PlayerObject.cpp.
References trainerZoneName.
Referenced by server::zone::objects::player::PlayerObject::getTrainerZoneName(), and loadTemplateData().
int PlayerObjectImplementation::getVendorCount ()
Definition at line 4872 of file PlayerObject.cpp.
References ownedVendors.
Referenced by server::zone::objects::player::PlayerObject::getVendorCount().
float PlayerObjectImplementation::getVisibility ()
Definition at line 4845 of file PlayerObject.cpp.
References visibility.
Referenced by server::zone::objects::player::PlayerObject::getVisibility().
WaypointList * PlayerObjectImplementation::getWaypointList ()
Definition at line 4568 of file PlayerObject.cpp.
References waypointList.
Referenced by getSurveyWaypoint(), server::zone::objects::player::PlayerObject::getWaypointList(), and PlayerObjectMessage8::PlayerObjectMessage8().
VectorMap< String, int > * PlayerObjectImplementation::getXpTypeCapList ()
Definition at line 4548 of file PlayerObject.cpp.
References xpTypeCapList.
Referenced by server::zone::objects::player::PlayerObject::getXpTypeCapList(), and maximizeExperience().
bool PlayerObjectImplementation::hasAbility (const String & ability)
Checks to see if this player object has the specified ability.
Parameters
ability The ability to search for.
Returns
True if the player has the ability.
Definition at line 4493 of file PlayerObject.cpp.
References abilityList.
Referenced by server::zone::objects::player::PlayerObject::hasAbility(), and isPrivileged().
bool PlayerObjectImplementation::hasBadge (unsigned int badge)
Definition at line 4671 of file PlayerObject.cpp.
References badges.
Referenced by server::zone::objects::player::PlayerObject::hasBadge().
bool PlayerObjectImplementation::hasCappedExperience (const String & xpType)
Checks if the player has capped the experience type.
Parameters
xpType The string value for the type of experience to check.
Returns
true if experience is capped, false otherwise.
Definition at line 586 of file PlayerObjectImplementation.cpp.
References DeltaVectorMap< K, V >::contains(), experienceList, DeltaVectorMap< K, V >::get(), and xpTypeCapList.
Referenced by server::zone::objects::player::PlayerObject::hasCappedExperience().
bool PlayerObjectImplementation::hasCommandMessageString (unsigned int actionCRC)
Definition at line 4498 of file PlayerObject.cpp.
References commandMessageStrings.
Referenced by server::zone::objects::player::PlayerObject::hasCommandMessageString().
bool PlayerObjectImplementation::hasFriend (const String & name)
Definition at line 4468 of file PlayerObject.cpp.
References friendList.
Referenced by server::zone::objects::player::PlayerObject::hasFriend().
bool PlayerObjectImplementation::hasInConsentList (const String & name)
Definition at line 4204 of file PlayerObject.cpp.
References consentList.
Referenced by server::zone::objects::player::PlayerObject::hasInConsentList().
bool PlayerObjectImplementation::hasLotsRemaining (int lots)
Definition at line 4086 of file PlayerObject.cpp.
References _this, and getLotsRemaining().
Referenced by server::zone::objects::player::PlayerObject::hasLotsRemaining().
bool PlayerObjectImplementation::hasPermissionGroup (const String & group)
Definition at line 1789 of file PlayerObjectImplementation.cpp.
References permissionGroups.
Referenced by server::zone::objects::player::PlayerObject::hasPermissionGroup().
bool PlayerObjectImplementation::hasSpawnedBlueFrog ()
Definition at line 4740 of file PlayerObject.cpp.
References spawnedBlueFrog.
Referenced by server::zone::objects::player::PlayerObject::hasSpawnedBlueFrog().
bool PlayerObjectImplementation::hasSuiBox (unsigned int boxID)
Definition at line 4315 of file PlayerObject.cpp.
References suiBoxes.
Referenced by server::zone::objects::player::PlayerObject::hasSuiBox().
bool PlayerObjectImplementation::hasSuiBoxWindowType (unsigned int windowType)
Definition at line 4325 of file PlayerObject.cpp.
References suiBoxes.
Referenced by closeSuiWindowType(), and server::zone::objects::player::PlayerObject::hasSuiBoxWindowType().
bool PlayerObjectImplementation::hasWaypoint (unsigned long long objectID)
Definition at line 4488 of file PlayerObject.cpp.
References waypointList.
Referenced by server::zone::objects::player::PlayerObject::hasWaypoint().
void PlayerObjectImplementation::increaseFactionStanding (const String & factionName, float amount)
Adds the amount of faction points to the faction point list.
Precondition
{ this locked }
Postcondition
{ this locked }
Parameters
factionName The string key for the faction the faction points are to be added.
amount The float amount of faction points to add.
Definition at line 1214 of file PlayerObjectImplementation.cpp.
References factionStandingList, server::zone::objects::creature::CreatureObject::getFactionRank(), FactionStandingList::getFactionStanding(), FactionStandingList::isPvpFaction(), FactionStandingList::put(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), server::zone::objects::scene::variables::StringId::setStringId(), and server::chat::StringIdChatParameter::setTO().
Referenced by server::zone::objects::player::PlayerObject::increaseFactionStanding().
void PlayerObjectImplementation::initializeTransientMembers ()
Definition at line 118 of file PlayerObjectImplementation.cpp.
References drinkFillingMax, duelList, foodFillingMax, and server::zone::objects::scene::SceneObjectImplementation::setLoggingName().
Referenced by server::zone::objects::player::PlayerObject::initializeTransientMembers(), and readObject().
bool PlayerObjectImplementation::isAFK ()
is the player AFK
Definition at line 420 of file PlayerObjectImplementation.cpp.
References AFK, and characterBitmask.
Referenced by server::zone::objects::player::PlayerObject::isAFK().
bool PlayerObjectImplementation::isBountyLocked ()
Definition at line 1715 of file PlayerObjectImplementation.cpp.
References bountyLockList.
Referenced by server::zone::objects::player::PlayerObject::isBountyLocked().
bool PlayerObjectImplementation::isCSR ()
Definition at line 4533 of file PlayerObject.cpp.
References adminLevel, and CSR.
Referenced by server::zone::objects::player::PlayerObject::isCSR().
bool PlayerObjectImplementation::isDeveloper ()
Definition at line 4528 of file PlayerObject.cpp.
References adminLevel, and DEV.
Referenced by server::zone::objects::player::PlayerObject::isDeveloper().
bool PlayerObjectImplementation::isDigesting ()
Definition at line 4272 of file PlayerObject.cpp.
References getDrinkFilling(), and getFoodFilling().
Referenced by doDigest(), and server::zone::objects::player::PlayerObject::isDigesting().
bool PlayerObjectImplementation::isDuelListEmpty ()
Definition at line 4433 of file PlayerObject.cpp.
References duelList.
Referenced by server::zone::objects::player::PlayerObject::isDuelListEmpty().
bool PlayerObjectImplementation::isFirstIncapacitation ()
Definition at line 4403 of file PlayerObject.cpp.
References incapacitationCounter.
Referenced by server::zone::objects::player::PlayerObject::isFirstIncapacitation(), resetFirstIncapacitationTime(), and updateIncapacitationCounter().
bool PlayerObjectImplementation::isFirstIncapacitationExpired ()
Definition at line 1302 of file PlayerObjectImplementation.cpp.
References server::zone::objects::creature::CreatureObject::checkCooldownRecovery().
Referenced by server::zone::objects::player::PlayerObject::isFirstIncapacitationExpired(), and updateIncapacitationCounter().
bool PlayerObjectImplementation::isIgnoring (const String & name)
Definition at line 4473 of file PlayerObject.cpp.
References ignoreList.
Referenced by server::zone::objects::player::PlayerObject::isIgnoring().
bool PlayerObjectImplementation::isInBountyLockList (unsigned long long playerId)
Definition at line 1719 of file PlayerObjectImplementation.cpp.
References bountyLockList.
Referenced by server::zone::objects::player::PlayerObject::isInBountyLockList().
bool PlayerObjectImplementation::isJedi ()
Definition at line 4877 of file PlayerObject.cpp.
References jediState.
Referenced by server::zone::objects::player::PlayerObject::isJedi().
bool PlayerObjectImplementation::isLinkDead ()
Definition at line 4691 of file PlayerObject.cpp.
References LINKDEAD, and onlineStatus.
Referenced by disconnect(), doRecovery(), server::zone::objects::player::PlayerObject::isLinkDead(), and setOffline().
bool PlayerObjectImplementation::isLoading ()
Definition at line 4686 of file PlayerObject.cpp.
References LOADING, LOGGINGOUT, and onlineStatus.
Referenced by server::zone::objects::player::PlayerObject::isLoading().
bool PlayerObjectImplementation::isLoggingIn ()
Definition at line 4696 of file PlayerObject.cpp.
References LOGGINGIN, and onlineStatus.
Referenced by server::zone::objects::player::PlayerObject::isLoggingIn(), and reload().
bool PlayerObjectImplementation::isLoggingOut ()
Definition at line 4701 of file PlayerObject.cpp.
References LOGGINGOUT, and onlineStatus.
Referenced by server::zone::objects::player::PlayerObject::isLoggingOut(), and logout().
bool PlayerObjectImplementation::isOffline ()
Definition at line 4681 of file PlayerObject.cpp.
References OFFLINE, and onlineStatus.
Referenced by server::zone::objects::player::PlayerObject::isOffline().
bool PlayerObjectImplementation::isOnline ()
Definition at line 4676 of file PlayerObject.cpp.
References LINKDEAD, OFFLINE, and onlineStatus.
Referenced by disconnect(), and server::zone::objects::player::PlayerObject::isOnline().
bool PlayerObjectImplementation::isOwnedStructure (StructureObject * obj)
Definition at line 4071 of file PlayerObject.cpp.
References _this, server::zone::objects::scene::SceneObject::getObjectID(), and ownedStructures.
Referenced by server::zone::objects::player::PlayerObject::isOwnedStructure().
bool PlayerObjectImplementation::isPrivileged ()
Definition at line 4538 of file PlayerObject.cpp.
References adminLevel, and hasAbility().
Referenced by server::zone::objects::player::PlayerObject::isPrivileged().
bool PlayerObjectImplementation::isTeleporting ()
Definition at line 4623 of file PlayerObject.cpp.
References teleporting.
Referenced by server::zone::objects::player::PlayerObject::isTeleporting().
void PlayerObjectImplementation::loadTemplateData (SharedObjectTemplate * templateData) virtual
Reads and sets the template data from a SharedObjectTemplate LuaObject
Precondition
{ templateData is a valid pointer }
Postcondition
{ SceneObject members are initialized }
Parameters
templateData templateData points to the LuaObject that is used to initialize SceneObejct members
Reimplemented from server::zone::objects::intangible::IntangibleObjectImplementation.
Definition at line 129 of file PlayerObjectImplementation.cpp.
References adminLevel, ANONYMOUS, characterBitmask, drinkFilling, drinkFillingMax, experienceList, foodFilling, foodFillingMax, forcePower, forcePowerMax, forcePowerRegen, getForcePower(), getForcePowerMax(), getForcePowerRegen(), getJediState(), SharedPlayerObjectTemplate::getPlayerDefaultGroupPermissions(), getTrainerZoneName(), jediState, languageID, permissionGroups, DeltaVectorMap< K, V >::setNullValue(), and trainerZoneName.
Referenced by server::zone::objects::player::PlayerObject::loadTemplateData().
void PlayerObjectImplementation::lock (bool doLock = true) protected
Definition at line 3128 of file PlayerObject.cpp.
References _this.
void PlayerObjectImplementation::lock (ManagedObject * obj) protected
Definition at line 3132 of file PlayerObject.cpp.
References _this.
void PlayerObjectImplementation::logout (bool doLock)
Definition at line 1318 of file PlayerObjectImplementation.cpp.
References _this, disconnectEvent, server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::objects::scene::SceneObjectImplementation::info(), isLoggingOut(), and setLoggingOut().
Referenced by server::zone::objects::player::PlayerObject::logout().
void PlayerObjectImplementation::maximizeExperience ()
Maximizes all types of experience for the player.
Definition at line 1550 of file PlayerObjectImplementation.cpp.
References addExperience(), and getXpTypeCapList().
Referenced by server::zone::objects::player::PlayerObject::maximizeExperience().
void PlayerObjectImplementation::notifyLoadFromDatabase ()
Gets called when this objects is loaded from database
Precondition
{ this locked }
Postcondition
{ this locked }
Definition at line 159 of file PlayerObjectImplementation.cpp.
References activateRecovery(), chatRooms, clientLastMovementStamp, server::zone::objects::scene::SceneObjectImplementation::getParent(), lastValidatedPosition, serverLastMovementStamp, setLinkDead(), and ValidatedPosition::update().
Referenced by server::zone::objects::player::PlayerObject::notifyLoadFromDatabase().
void PlayerObjectImplementation::notifyOffline ()
Notifies all reverse friends offline status
Precondition
{ }
Postcondition
{ }
Definition at line 1135 of file PlayerObjectImplementation.cpp.
References friendList, FriendList::getReverseTable(), and server::zone::objects::scene::SceneObjectImplementation::server.
Referenced by server::zone::objects::player::PlayerObject::notifyOffline(), and unload().
void PlayerObjectImplementation::notifyOnline ()
Notifies all reverse friends online status
Precondition
{ }
Postcondition
{ }
Definition at line 1090 of file PlayerObjectImplementation.cpp.
References friendList, server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObjectImplementation::getParent(), FriendList::getReverseTable(), server::zone::objects::scene::SceneObjectImplementation::server, and suiBoxes.
Referenced by server::zone::objects::player::PlayerObject::notifyOnline().
void PlayerObjectImplementation::notifySceneReady ()
Definition at line 296 of file PlayerObjectImplementation.cpp.
References SuiWindowType::CLONE_REQUEST, server::zone::objects::guild::GuildObject::getChatRoom(), server::zone::Zone::getChatRoom(), getSuiBoxFromWindowType(), server::zone::ZoneServer::getZone(), server::zone::ZoneServer::getZoneCount(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), server::zone::ZoneServer::isServerLoading(), server::chat::room::ChatRoom::removePlayer(), sendFriendLists(), sendMessage(), server::chat::room::ChatRoom::sendTo(), server::zone::objects::scene::SceneObjectImplementation::server, teleporting, and server::zone::objects::scene::SceneObjectImplementation::zone.
Referenced by server::zone::objects::player::PlayerObject::notifySceneReady().
PlayerObjectImplementation::operator const PlayerObject * ()
Definition at line 3124 of file PlayerObject.cpp.
void PlayerObjectImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::intangible::IntangibleObjectImplementation.
Definition at line 3163 of file PlayerObject.cpp.
References initializeTransientMembers(), and readObjectMember().
bool PlayerObjectImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 3182 of file PlayerObject.cpp.
References abilityList, accountID, adminLevel, badges, bankLocation, biography, bountyLockList, characterBitmask, chatRooms, clientLastMovementStamp, cloningFacility, commandMessageStrings, consentList, conversatingCreature, debugOutput, declaredResidence, drinkFilling, drinkFillingMax, experienceList, factionStandingList, factionStatus, foodFilling, foodFillingMax, forcePower, forcePowerMax, forcePowerRegen, friendList, hologrindProfessions, ignoreList, incapacitationCounter, jediState, languageID, lastDigestion, lastNpcConvo, lastNpcConvoMessage, lastNpcConvoOptions, lastValidatedPosition, lastVisibilityUpdateTimestamp, logoutTimeStamp, maximumLots, onlineStatus, ownedStructures, ownedVendors, performanceBuffTarget, permissionGroups, persistentMessages, pvpRating, raceID, savedParentID, savedTerrainName, schematicList, screenPlayData, serverLastMovementStamp, skillPoints, starterProfession, suiBoxes, suiBoxNextID, teleporting, title, trainerCoordinates, trainerZoneName, visibility, waypointList, and xpTypeCapList.
Referenced by readObject().
void PlayerObjectImplementation::reload (ZoneClientSession * client)
Definition at line 1450 of file PlayerObjectImplementation.cpp.
References server::zone::objects::creature::CreatureObject::clearState(), server::zone::ZoneClientSession::disconnect(), disconnectEvent, server::zone::objects::creature::CreatureObject::getClient(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getZone(), isLoggingIn(), server::zone::objects::creature::CreatureObject::isRidingMount(), CreatureState::RIDINGMOUNT, server::zone::objects::scene::SceneObject::setMovementCounter(), setOnline(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::objects::player::PlayerObject::reload().
void PlayerObjectImplementation::removeAbilities (Vector< Ability * > & abilities, bool notifyClient = true)
Removes certifications from player
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
skills Vector of skills to add
notifyClient determines whether to update the client with the changes
Definition at line 715 of file PlayerObjectImplementation.cpp.
References _this, abilityList, DeltaMessage::close(), server::zone::objects::scene::variables::DeltaVector< E >::find(), server::zone::objects::scene::variables::DeltaVector< E >::remove(), sendMessage(), and DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::PlayerObject::removeAbilities().
void PlayerObjectImplementation::removeAbility (Ability * ability, bool notifyClient = true)
Definition at line 703 of file PlayerObjectImplementation.cpp.
References _this, abilityList, DeltaMessage::close(), server::zone::objects::scene::variables::DeltaVector< E >::find(), server::zone::objects::scene::variables::DeltaVector< E >::remove(), sendMessage(), and DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::PlayerObject::removeAbility().
void PlayerObjectImplementation::removeChatRoom (ChatRoom * room)
Definition at line 4633 of file PlayerObject.cpp.
References chatRooms.
Referenced by server::zone::objects::player::PlayerObject::removeChatRoom().
void PlayerObjectImplementation::removeCommandMessageString (unsigned int actionCRC)
Definition at line 4239 of file PlayerObject.cpp.
References commandMessageStrings.
Referenced by server::zone::objects::player::PlayerObject::removeCommandMessageString().
void PlayerObjectImplementation::removeExperience (const String & xpType, bool notifyClient = true)
Removes experience of a type from the player's experience pool.
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
xpType The string value for the type of experience to remove.
notifyClient Boolean to determing whether the client should receive a delta packet for the experience loss.
Definition at line 570 of file PlayerObjectImplementation.cpp.
References DeltaMessage::close(), DeltaVectorMap< K, V >::contains(), DeltaVectorMap< K, V >::drop(), experienceList, sendMessage(), and DeltaMessage::startUpdate().
Referenced by addExperience(), and server::zone::objects::player::PlayerObject::removeExperience().
void PlayerObjectImplementation::removeFriend (const String & name, bool notifyClient = true)
Removes the specified friend from the friend list
Precondition
{ this is locked }
Postcondition
{ this is locked}
Parameters
name friend name to remove
notifyClient determines whether to update the client with the changes
Definition at line 953 of file PlayerObjectImplementation.cpp.
References _this, DeltaMessage::close(), friendList, server::zone::ZoneServer::getObject(), server::zone::managers::player::PlayerManager::getObjectID(), server::zone::objects::scene::SceneObjectImplementation::getParent(), PlayerList< DeltaUpdate >::insertToDeltaMessage(), PlayerList< DeltaUpdate >::removePlayer(), server::zone::objects::player::PlayerObject::removeReverseFriend(), server::zone::objects::scene::SceneObjectImplementation::server, server::chat::StringIdChatParameter::setTT(), and server::zone::objects::scene::SceneObject::updateToDatabase().
Referenced by server::zone::objects::player::PlayerObject::removeFriend().
void PlayerObjectImplementation::removeFromBountyLockList (unsigned long long playerId, bool immediately)
Definition at line 1667 of file PlayerObjectImplementation.cpp.
References bountyLockList.
Referenced by server::zone::objects::player::PlayerObject::removeFromBountyLockList().
void PlayerObjectImplementation::removeFromBountyLockListDirectly (unsigned long long playerId)
Definition at line 1683 of file PlayerObjectImplementation.cpp.
References bountyLockList, and updateBountyPvpStatus().
Referenced by server::zone::objects::player::PlayerObject::removeFromBountyLockListDirectly().
void PlayerObjectImplementation::removeFromConsentList (const String & name)
Definition at line 4209 of file PlayerObject.cpp.
References consentList.
Referenced by server::zone::objects::player::PlayerObject::removeFromConsentList().
void PlayerObjectImplementation::removeFromDuelList (CreatureObject * targetPlayer)
Definition at line 4418 of file PlayerObject.cpp.
References duelList.
Referenced by server::zone::objects::player::PlayerObject::removeFromDuelList().
void PlayerObjectImplementation::removeIgnore (const String & name, bool notifyClient = true)
Removes the specified player from the ignore list
Precondition
{ this is locked }
Postcondition
{ this is locked}
Parameters
name player name to remove
notifyClient determines whether to update the client with the changes
Definition at line 1041 of file PlayerObjectImplementation.cpp.
References _this, DeltaMessage::close(), server::zone::objects::scene::SceneObjectImplementation::getParent(), ignoreList, PlayerList< DeltaUpdate >::insertToDeltaMessage(), PlayerList< DeltaUpdate >::removePlayer(), and server::chat::StringIdChatParameter::setTT().
Referenced by server::zone::objects::player::PlayerObject::removeIgnore().
void PlayerObjectImplementation::removeOwnedStructure (StructureObject * obj)
Definition at line 4053 of file PlayerObject.cpp.
References _this, getDeclaredResidence(), server::zone::objects::scene::SceneObject::getObjectID(), ownedStructures, and setDeclaredResidence().
Referenced by server::zone::objects::player::PlayerObject::removeOwnedStructure().
void PlayerObjectImplementation::removePermissionGroup (const String & group, bool updateInRangeBuildingPermissions = false)
Definition at line 1762 of file PlayerObjectImplementation.cpp.
References server::zone::objects::building::BuildingObject::broadcastCellPermissions(), server::zone::objects::scene::SceneObjectImplementation::getParent(), permissionGroups, and server::zone::objects::scene::SceneObjectImplementation::zone.
Referenced by server::zone::objects::player::PlayerObject::removePermissionGroup().
void PlayerObjectImplementation::removeReverseFriend (const String & name)
Definition at line 4483 of file PlayerObject.cpp.
References friendList.
Referenced by server::zone::objects::player::PlayerObject::removeReverseFriend().
void PlayerObjectImplementation::removeRewardedSchematic (DraftSchematic * schematic, bool notifyClient = true)
For use when manually removing a schematic, like if a quest termination removed a schematic from a player, not needed when schematics are automatically removed by usecount decreasing
Definition at line 807 of file PlayerObjectImplementation.cpp.
References SchematicList::removeRewardedSchematic(), removeSchematics(), and schematicList.
Referenced by server::zone::objects::player::PlayerObject::removeRewardedSchematic().
void PlayerObjectImplementation::removeSchematics (Vector< ManagedReference< DraftSchematic * > > & schematics, bool notifyClient = true)
Here we are loading the schematics based on the skills that the player has, we do this incase we change the items in the schematic group.
Definition at line 826 of file PlayerObjectImplementation.cpp.
References _this, SchematicList::addRewardedSchematics(), server::zone::managers::skill::SkillManager::awardDraftSchematics(), DeltaMessage::close(), server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::scene::SceneObjectImplementation::getParentRecursively(), server::zone::ZoneServer::getSkillManager(), SceneObjectType::PLAYERCREATURE, server::zone::objects::scene::variables::DeltaVector< E >::removeAll(), schematicList, sendMessage(), server::zone::objects::scene::SceneObjectImplementation::server, server::zone::objects::scene::variables::DeltaVector< E >::size(), and DeltaMessage::startUpdate().
Referenced by decreaseSchematicUseCount(), removeRewardedSchematic(), and server::zone::objects::player::PlayerObject::removeSchematics().
void PlayerObjectImplementation::removeSuiBox (unsigned int boxID, bool closeWindowToClient = false)
Removes the specified box id and optionally closes the client sui
Definition at line 1251 of file PlayerObjectImplementation.cpp.
References server::zone::objects::player::sui::SuiBox::generateCloseMessage(), sendMessage(), and suiBoxes.
Referenced by closeSuiWindowType(), server::zone::objects::player::PlayerObject::removeSuiBox(), and removeSuiBoxType().
void PlayerObjectImplementation::removeSuiBoxType (unsigned int windowType)
Definition at line 1263 of file PlayerObjectImplementation.cpp.
References server::zone::objects::player::sui::SuiBox::getBoxID(), getSuiBoxFromWindowType(), and removeSuiBox().
Referenced by server::zone::objects::player::PlayerObject::removeSuiBoxType().
void PlayerObjectImplementation::removeVendor (SceneObject * vendor)
Definition at line 4867 of file PlayerObject.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), and ownedVendors.
Referenced by server::zone::objects::player::PlayerObject::removeVendor().
void PlayerObjectImplementation::removeWaypoint (unsigned long long waypointID, bool notifyClient = true)
Removes a waypoint from this player
Precondition
{ this is locked }
Postcondition
{ this is locked, waypoint list doesnt contain the specified waypoint }
Parameters
waypointID waypoint object id to remove
notifyClient determines whether to update the client with the changes
Definition at line 638 of file PlayerObjectImplementation.cpp.
References DeltaMessage::close(), WaypointList::drop(), DeltaVectorMap< K, V >::get(), sendMessage(), DeltaMessage::startUpdate(), and waypointList.
Referenced by addWaypoint(), and server::zone::objects::player::PlayerObject::removeWaypoint().
bool PlayerObjectImplementation::requestedDuelTo (CreatureObject * targetPlayer)
Definition at line 4428 of file PlayerObject.cpp.
References duelList.
Referenced by server::zone::objects::player::PlayerObject::requestedDuelTo().
void PlayerObjectImplementation::resetFirstIncapacitationTime ()
Definition at line 1309 of file PlayerObjectImplementation.cpp.
References server::zone::objects::creature::CreatureObject::addCooldown(), isFirstIncapacitation(), and resetIncapacitationCounter().
Referenced by server::zone::objects::player::PlayerObject::resetFirstIncapacitationTime(), and updateIncapacitationCounter().
void PlayerObjectImplementation::resetIncapacitationCounter ()
Definition at line 4390 of file PlayerObject.cpp.
References incapacitationCounter.
Referenced by resetFirstIncapacitationTime(), and server::zone::objects::player::PlayerObject::resetIncapacitationCounter().
void PlayerObjectImplementation::rlock (bool doLock = true) protected
Definition at line 3136 of file PlayerObject.cpp.
References _this.
void PlayerObjectImplementation::runlock (bool doLock = true) protected
Definition at line 3152 of file PlayerObject.cpp.
References _this.
void PlayerObjectImplementation::sendBadgesResponseTo (CreatureObject * player)
Sends a badges response message
Precondition
{ }
Postcondition
{ }
Parameters
player CreatureObject to receive badges response message
Definition at line 440 of file PlayerObjectImplementation.cpp.
References badges, server::zone::objects::scene::SceneObjectImplementation::getParent(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::objects::player::PlayerObject::sendBadgesResponseTo().
void PlayerObjectImplementation::sendBaselinesTo (SceneObject * player) virtual
Sends the baseline messages of this object to the specified player, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the baseline messages }
Parameters
player SceneObject that will receive the baselines
Reimplemented from server::zone::objects::intangible::IntangibleObjectImplementation.
Definition at line 278 of file PlayerObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::info(), and server::zone::objects::scene::SceneObject::sendMessage().
Referenced by server::zone::objects::player::PlayerObject::sendBaselinesTo().
void PlayerObjectImplementation::sendFriendLists ()
Definition at line 375 of file PlayerObjectImplementation.cpp.
References _this, DeltaMessage::close(), friendList, server::zone::objects::scene::SceneObjectImplementation::getParent(), ignoreList, server::zone::objects::scene::SceneObjectImplementation::info(), PlayerList< DeltaUpdate >::insertToDeltaMessage(), and server::zone::objects::scene::SceneObjectImplementation::server.
Referenced by notifySceneReady(), and server::zone::objects::player::PlayerObject::sendFriendLists().
void PlayerObjectImplementation::sendMessage (BasePacket * msg) virtual
Sends BasePacket msg to the owner of this object, needs to be overriden
Precondition
{ }
Postcondition
{owner of this object received message, message is deleted }
Parameters
msg BasePacket to be sent
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 397 of file PlayerObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::getParent().
Referenced by addAbilities(), addAbility(), addExperience(), addSchematics(), closeSuiWindowType(), notifySceneReady(), removeAbilities(), removeAbility(), removeExperience(), removeSchematics(), removeSuiBox(), removeWaypoint(), server::zone::objects::player::PlayerObject::sendMessage(), setForcePower(), setForcePowerMax(), setJediState(), and setWaypoint().
void PlayerObjectImplementation::setAccountID (unsigned int id)
Definition at line 4770 of file PlayerObject.cpp.
References accountID.
Referenced by server::zone::objects::player::PlayerObject::setAccountID().
void PlayerObjectImplementation::setAdminLevel (unsigned int adminlvl)
Definition at line 4518 of file PlayerObject.cpp.
References adminLevel.
Referenced by server::zone::objects::player::PlayerObject::setAdminLevel().
void PlayerObjectImplementation::setBadge (unsigned int badge)
Definition at line 4448 of file PlayerObject.cpp.
References badges.
Referenced by server::zone::objects::player::PlayerObject::setBadge().
void PlayerObjectImplementation::setBankLocation (const String & location)
Definition at line 4638 of file PlayerObject.cpp.
References bankLocation.
Referenced by server::zone::objects::player::PlayerObject::setBankLocation().
void PlayerObjectImplementation::setBiography (const UnicodeString & bio)
Definition at line 4523 of file PlayerObject.cpp.
References biography.
Referenced by server::zone::objects::player::PlayerObject::setBiography().
bool PlayerObjectImplementation::setCharacterBit (unsigned int bit, bool notifyClient = false)
Definition at line 405 of file PlayerObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), characterBitmask, DeltaMessage::close(), and PlayerObjectDeltaMessage3::updateCharacterBitmask().
Referenced by server::zone::objects::player::PlayerObject::setCharacterBit(), setLinkDead(), and toggleCharacterBit().
void PlayerObjectImplementation::setCharacterBitmask (unsigned int bitmask)
Definition at line 4543 of file PlayerObject.cpp.
References characterBitmask.
Referenced by server::zone::objects::player::PlayerObject::setCharacterBitmask().
void PlayerObjectImplementation::setClientLastMovementStamp (unsigned int stamp)
Definition at line 4760 of file PlayerObject.cpp.
References clientLastMovementStamp.
Referenced by server::zone::objects::player::PlayerObject::setClientLastMovementStamp().
void PlayerObjectImplementation::setCloningFacility (BuildingObject * cloningfac)
Definition at line 4258 of file PlayerObject.cpp.
References cloningFacility, and server::zone::objects::scene::SceneObject::getObjectID().
Referenced by server::zone::objects::player::PlayerObject::setCloningFacility().
void PlayerObjectImplementation::setCommandMessageString (unsigned int actionCRC, String & message)
Definition at line 4234 of file PlayerObject.cpp.
References commandMessageStrings.
Referenced by server::zone::objects::player::PlayerObject::setCommandMessageString().
void PlayerObjectImplementation::setConversatingCreature (CreatureObject * creature)
Definition at line 4160 of file PlayerObject.cpp.
References conversatingCreature, and server::zone::objects::scene::SceneObject::getObjectID().
Referenced by server::zone::objects::player::PlayerObject::setConversatingCreature().
void PlayerObjectImplementation::setDebug (bool value)
Definition at line 4835 of file PlayerObject.cpp.
References debugOutput.
Referenced by server::zone::objects::player::PlayerObject::setDebug().
void PlayerObjectImplementation::setDeclaredResidence (BuildingObject * residence)
Definition at line 4249 of file PlayerObject.cpp.
References declaredResidence, and server::zone::objects::scene::SceneObject::getObjectID().
Referenced by removeOwnedStructure(), and server::zone::objects::player::PlayerObject::setDeclaredResidence().
void PlayerObjectImplementation::setDrinkFilling (int newValue, bool notifyClient = true)
Definition at line 1200 of file PlayerObjectImplementation.cpp.
References _this, DeltaMessage::close(), drinkFilling, server::zone::objects::scene::SceneObjectImplementation::getParent(), and PlayerObjectDeltaMessage9::updateDrinkFilling().
Referenced by doDigest(), and server::zone::objects::player::PlayerObject::setDrinkFilling().
void PlayerObjectImplementation::setFactionRank (const String & rank)
Definition at line 4229 of file PlayerObject.cpp.
References factionStandingList.
Referenced by server::zone::objects::player::PlayerObject::setFactionRank().
void PlayerObjectImplementation::setFactionStatus (int status)
Definition at line 450 of file PlayerObjectImplementation.cpp.
References server::zone::objects::creature::CreatureObject::addCooldown(), CreatureFlag::CHANGEFACTIONSTATUS, FactionStatus::CHANGINGSTATUS, FactionStatus::COVERT, factionStatus, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::scene::SceneObjectImplementation::getParent(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), FactionStatus::ONLEAVE, FactionStatus::OVERT, CreatureFlag::OVERT, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::tangible::TangibleObject::setPvpStatusBitmask(), server::zone::objects::intangible::IntangibleObjectImplementation::status, server::zone::objects::building::BuildingObject::updateCellPermissionsTo(), and server::zone::objects::scene::SceneObjectImplementation::zone.
Referenced by server::zone::objects::player::PlayerObject::setFactionStatus().
void PlayerObjectImplementation::setFoodFilling (int newValue, bool notifyClient = true)
Definition at line 1186 of file PlayerObjectImplementation.cpp.
References _this, DeltaMessage::close(), foodFilling, server::zone::objects::scene::SceneObjectImplementation::getParent(), and PlayerObjectDeltaMessage9::updateFoodFilling().
Referenced by doDigest(), and server::zone::objects::player::PlayerObject::setFoodFilling().
void PlayerObjectImplementation::setForcePower (int fp, bool notifyClient = true)
Definition at line 1607 of file PlayerObjectImplementation.cpp.
References DeltaMessage::close(), forcePower, getForcePower(), sendMessage(), and PlayerObjectDeltaMessage8::updateForcePower().
Referenced by activateForceRegen(), server::zone::objects::player::PlayerObject::setForcePower(), and setForcePowerMax().
void PlayerObjectImplementation::setForcePowerMax (int newValue, bool notifyClient = true)
Definition at line 1588 of file PlayerObjectImplementation.cpp.
References DeltaMessage::close(), forcePower, forcePowerMax, getForcePowerMax(), sendMessage(), setForcePower(), and PlayerObjectDeltaMessage8::updateForcePowerMax().
Referenced by server::zone::objects::player::PlayerObject::setForcePowerMax().
void PlayerObjectImplementation::setForcePowerRegen (int val)
Definition at line 4300 of file PlayerObject.cpp.
References forcePowerRegen.
Referenced by server::zone::objects::player::PlayerObject::setForcePowerRegen().
void PlayerObjectImplementation::setJediState (int state, bool notifyClient = true)
Definition at line 1832 of file PlayerObjectImplementation.cpp.
References _this, DeltaMessage::close(), jediState, sendMessage(), and PlayerObjectDeltaMessage9::setJediState().
Referenced by server::zone::objects::player::PlayerObject::setJediState().
void PlayerObjectImplementation::setLanguageID (byte language, bool notifyClient = true)
Sets the specified language id
Precondition
{ }
Postcondition
{ }
Parameters
language language id to set
notifyClient determines whether to update the client with the changes
Definition at line 1164 of file PlayerObjectImplementation.cpp.
References _this, DeltaMessage::close(), server::zone::objects::scene::SceneObjectImplementation::getParent(), languageID, and PlayerObjectDeltaMessage9::setLanguageID().
Referenced by server::zone::objects::player::PlayerObject::setLanguageID().
void PlayerObjectImplementation::setLastNpcConvMessStr (const String & mess)
Definition at line 4125 of file PlayerObject.cpp.
References lastNpcConvoMessage.
Referenced by server::zone::objects::player::PlayerObject::setLastNpcConvMessStr().
void PlayerObjectImplementation::setLastNpcConvStr (const String & conv)
Definition at line 4120 of file PlayerObject.cpp.
References lastNpcConvo.
Referenced by server::zone::objects::player::PlayerObject::setLastNpcConvStr().
void PlayerObjectImplementation::setLinkDead ()
Definition at line 1429 of file PlayerObjectImplementation.cpp.
References activateRecovery(), LD, LINKDEAD, logoutTimeStamp, onlineStatus, and setCharacterBit().
Referenced by disconnect(), notifyLoadFromDatabase(), and server::zone::objects::player::PlayerObject::setLinkDead().
void PlayerObjectImplementation::setLoggingOut ()
Definition at line 4110 of file PlayerObject.cpp.
References LOGGINGOUT, and onlineStatus.
Referenced by logout(), and server::zone::objects::player::PlayerObject::setLoggingOut().
void PlayerObjectImplementation::setMaximumLots (byte lots)
Definition at line 4805 of file PlayerObject.cpp.
References maximumLots.
Referenced by server::zone::objects::player::PlayerObject::setMaximumLots().
void PlayerObjectImplementation::setOffline ()
Definition at line 4102 of file PlayerObject.cpp.
References isLinkDead(), OFFLINE, and onlineStatus.
Referenced by disconnect(), doRecovery(), PlayerObjectImplementation(), and server::zone::objects::player::PlayerObject::setOffline().
void PlayerObjectImplementation::setOnline ()
Definition at line 1440 of file PlayerObjectImplementation.cpp.
References activateMissions(), clearCharacterBit(), doRecovery(), LD, ONLINE, and onlineStatus.
Referenced by reload(), and server::zone::objects::player::PlayerObject::setOnline().
void PlayerObjectImplementation::setPerformanceBuffTarget (unsigned long long target)
Definition at line 4830 of file PlayerObject.cpp.
References performanceBuffTarget.
Referenced by server::zone::objects::player::PlayerObject::setPerformanceBuffTarget().
void PlayerObjectImplementation::setRaceID (byte race)
Definition at line 4800 of file PlayerObject.cpp.
References raceID.
Referenced by server::zone::objects::player::PlayerObject::setRaceID().
void PlayerObjectImplementation::setSavedParentID (unsigned long long id)
Definition at line 4290 of file PlayerObject.cpp.
References savedParentID.
Referenced by server::zone::objects::player::PlayerObject::setSavedParentID().
void PlayerObjectImplementation::setSavedTerrainName (const String & name)
Definition at line 4295 of file PlayerObject.cpp.
References savedTerrainName.
Referenced by server::zone::objects::player::PlayerObject::setSavedTerrainName().
void PlayerObjectImplementation::setScreenPlayData (const String & screenPlay, const String & variable, const String & data)
Definition at line 4092 of file PlayerObject.cpp.
References screenPlayData.
Referenced by server::zone::objects::player::PlayerObject::setScreenPlayData().
void PlayerObjectImplementation::setSkillPoints (int points)
Definition at line 4706 of file PlayerObject.cpp.
References skillPoints.
Referenced by server::zone::objects::player::PlayerObject::setSkillPoints().
void PlayerObjectImplementation::setSpawnedBlueFrog ()
Definition at line 4735 of file PlayerObject.cpp.
References spawnedBlueFrog.
Referenced by server::zone::objects::player::PlayerObject::setSpawnedBlueFrog().
void PlayerObjectImplementation::setStarterProfession (String & profession)
Definition at line 4820 of file PlayerObject.cpp.
References starterProfession.
Referenced by server::zone::objects::player::PlayerObject::setStarterProfession().
void PlayerObjectImplementation::setTeleporting (bool val)
Definition at line 4453 of file PlayerObject.cpp.
References teleporting.
Referenced by server::zone::objects::player::PlayerObject::setTeleporting().
void PlayerObjectImplementation::setTitle (const String & characterTitle, bool notifyClient = true)
Definition at line 1076 of file PlayerObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), PlayerObjectDeltaMessage3::setCurrentTitle(), and title.
Referenced by server::zone::objects::player::PlayerObject::setTitle().
void PlayerObjectImplementation::setTrainerCoordinates (const Vector3 & trainer)
Definition at line 1731 of file PlayerObjectImplementation.cpp.
References trainerCoordinates.
Referenced by server::zone::objects::player::PlayerObject::setTrainerCoordinates().
void PlayerObjectImplementation::setTrainerZoneName (String & zoneName)
Definition at line 4174 of file PlayerObject.cpp.
References trainerZoneName.
Referenced by server::zone::objects::player::PlayerObject::setTrainerZoneName().
void PlayerObjectImplementation::setVisibility (float value)
Definition at line 4850 of file PlayerObject.cpp.
References lastVisibilityUpdateTimestamp, and visibility.
Referenced by server::zone::objects::player::PlayerObject::setVisibility().
void PlayerObjectImplementation::setWaypoint (WaypointObject * waypoint, bool notifyClient = true)
Definition at line 594 of file PlayerObjectImplementation.cpp.
References DeltaMessage::close(), server::zone::objects::scene::SceneObject::getObjectID(), sendMessage(), WaypointList::set(), DeltaMessage::startUpdate(), and waypointList.
Referenced by addWaypoint(), and server::zone::objects::player::PlayerObject::setWaypoint().
void PlayerObjectImplementation::toggleCharacterBit (unsigned int bit)
Definition at line 1178 of file PlayerObjectImplementation.cpp.
References characterBitmask, clearCharacterBit(), and setCharacterBit().
Referenced by server::zone::objects::player::PlayerObject::toggleCharacterBit().
void PlayerObjectImplementation::unload ()
Definition at line 194 of file PlayerObjectImplementation.cpp.
References chatRooms, server::zone::managers::mission::MissionManager::deactivateMissions(), server::zone::managers::player::PlayerManager::ejectPlayerFromBuilding(), server::zone::ZoneServer::getChatManager(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), server::zone::objects::scene::SceneObjectImplementation::info(), notifyOffline(), server::chat::room::ChatRoom::removePlayer(), server::chat::ChatManager::removePlayer(), savedParentID, savedTerrainName, SessionFacadeType::TRADE, unloadSpawnedChildren(), and server::zone::objects::scene::SceneObjectImplementation::updateToDatabase().
Referenced by disconnect(), doRecovery(), and server::zone::objects::player::PlayerObject::unload().
void PlayerObjectImplementation::unloadSpawnedChildren ()
Unloads all the spawned creatures from the datapad control devices
Definition at line 175 of file PlayerObjectImplementation.cpp.
References server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObjectImplementation::getParent(), and server::zone::objects::intangible::ControlDevice::storeObject().
Referenced by unload(), and server::zone::objects::player::PlayerObject::unloadSpawnedChildren().
void PlayerObjectImplementation::unlock (bool doLock = true) protected
Definition at line 3148 of file PlayerObject.cpp.
References _this.
void PlayerObjectImplementation::updateBountyPvpStatus (unsigned long long playerId) private
Definition at line 1693 of file PlayerObjectImplementation.cpp.
References server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObjectImplementation::getParent(), and server::zone::objects::tangible::TangibleObject::sendPvpStatusTo().
Referenced by addToBountyLockList(), and removeFromBountyLockListDirectly().
void PlayerObjectImplementation::updateIncapacitationCounter ()
Definition at line 4395 of file PlayerObject.cpp.
References incapacitationCounter, isFirstIncapacitation(), isFirstIncapacitationExpired(), and resetFirstIncapacitationTime().
Referenced by server::zone::objects::player::PlayerObject::updateIncapacitationCounter().
void PlayerObjectImplementation::updateLastValidatedPosition ()
Definition at line 4726 of file PlayerObject.cpp.
References lastValidatedPosition, and serverLastMovementStamp.
Referenced by server::zone::objects::player::PlayerObject::updateLastValidatedPosition().
void PlayerObjectImplementation::updateServerLastMovementStamp ()
Definition at line 4765 of file PlayerObject.cpp.
References serverLastMovementStamp.
Referenced by server::zone::objects::player::PlayerObject::updateServerLastMovementStamp().
void PlayerObjectImplementation::wlock (bool doLock = true) protected
Definition at line 3140 of file PlayerObject.cpp.
References _this.
void PlayerObjectImplementation::wlock (ManagedObject * obj) protected
Definition at line 3144 of file PlayerObject.cpp.
References _this.
void PlayerObjectImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::intangible::IntangibleObjectImplementation.
Definition at line 3448 of file PlayerObject.cpp.
References writeObjectMembers().
int PlayerObjectImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 3455 of file PlayerObject.cpp.
References abilityList, accountID, adminLevel, badges, bankLocation, biography, bountyLockList, characterBitmask, chatRooms, clientLastMovementStamp, cloningFacility, commandMessageStrings, consentList, conversatingCreature, debugOutput, declaredResidence, drinkFilling, drinkFillingMax, experienceList, factionStandingList, factionStatus, foodFilling, foodFillingMax, forcePower, forcePowerMax, forcePowerRegen, friendList, hologrindProfessions, ignoreList, incapacitationCounter, jediState, languageID, lastDigestion, lastNpcConvo, lastNpcConvoMessage, lastNpcConvoOptions, lastValidatedPosition, lastVisibilityUpdateTimestamp, logoutTimeStamp, maximumLots, onlineStatus, ownedStructures, ownedVendors, performanceBuffTarget, permissionGroups, persistentMessages, pvpRating, raceID, savedParentID, savedTerrainName, schematicList, screenPlayData, serverLastMovementStamp, skillPoints, starterProfession, suiBoxes, suiBoxNextID, teleporting, title, trainerCoordinates, trainerZoneName, visibility, waypointList, and xpTypeCapList.
Referenced by writeObject().
Friends And Related Function Documentation
friend class PlayerObject friend
Definition at line 1755 of file PlayerObject.h.
Member Data Documentation
WeakReference<PlayerObject*> server::zone::objects::player::PlayerObjectImplementation::_this
Definition at line 1723 of file PlayerObject.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), activateRecovery(), addAbilities(), addAbility(), addExperience(), addFriend(), addIgnore(), addOwnedStructure(), addRewardedSchematic(), addSchematics(), addToBountyLockList(), awardBadge(), clearCharacterBit(), filterSchematicList(), getLotsRemaining(), getOwnedStructure(), getTotalOwnedStructureCount(), hasLotsRemaining(), isOwnedStructure(), lock(), logout(), removeAbilities(), removeAbility(), removeFriend(), removeIgnore(), removeOwnedStructure(), removeSchematics(), rlock(), runlock(), sendBaselinesTo(), sendFriendLists(), setCharacterBit(), setDrinkFilling(), setFoodFilling(), setJediState(), setLanguageID(), setTitle(), unlock(), and wlock().
AbilityList server::zone::objects::player::PlayerObjectImplementation::abilityList protected
Definition at line 991 of file PlayerObject.h.
Referenced by addAbilities(), addAbility(), getAbilityList(), hasAbility(), readObjectMember(), removeAbilities(), removeAbility(), and writeObjectMembers().
unsigned int server::zone::objects::player::PlayerObjectImplementation::accountID protected
Definition at line 1059 of file PlayerObject.h.
Referenced by getAccountID(), PlayerObjectImplementation(), readObjectMember(), setAccountID(), and writeObjectMembers().
unsigned int server::zone::objects::player::PlayerObjectImplementation::adminLevel protected
Definition at line 979 of file PlayerObject.h.
Referenced by getAdminLevel(), isCSR(), isDeveloper(), isPrivileged(), loadTemplateData(), readObjectMember(), setAdminLevel(), and writeObjectMembers().
const int server::zone::objects::player::PlayerObjectImplementation::AFK = 0x80 static
Definition at line 1084 of file PlayerObject.h.
Referenced by isAFK().
const int server::zone::objects::player::PlayerObjectImplementation::ANONYMOUS = 0x80000000 static
Definition at line 1090 of file PlayerObject.h.
Referenced by loadTemplateData().
Badges server::zone::objects::player::PlayerObjectImplementation::badges protected
Definition at line 949 of file PlayerObject.h.
Referenced by getBadgeTypeCount(), getNumBadges(), hasBadge(), readObjectMember(), sendBadgesResponseTo(), setBadge(), and writeObjectMembers().
String server::zone::objects::player::PlayerObjectImplementation::bankLocation protected
Definition at line 967 of file PlayerObject.h.
Referenced by getBankLocation(), PlayerObjectImplementation(), readObjectMember(), setBankLocation(), and writeObjectMembers().
UnicodeString server::zone::objects::player::PlayerObjectImplementation::biography protected
Definition at line 1019 of file PlayerObject.h.
Referenced by getBiography(), readObjectMember(), setBiography(), and writeObjectMembers().
BountyHunterTefRemovalTaskMap server::zone::objects::player::PlayerObjectImplementation::bountyLockList protected
Definition at line 1011 of file PlayerObject.h.
Referenced by addToBountyLockList(), isBountyLocked(), isInBountyLockList(), readObjectMember(), removeFromBountyLockList(), removeFromBountyLockListDirectly(), and writeObjectMembers().
unsigned int server::zone::objects::player::PlayerObjectImplementation::characterBitmask protected
Definition at line 941 of file PlayerObject.h.
Referenced by clearCharacterBit(), getCharacterBitmask(), isAFK(), loadTemplateData(), readObjectMember(), setCharacterBit(), setCharacterBitmask(), toggleCharacterBit(), and writeObjectMembers().
SortedVector<ManagedReference<ChatRoom* > > server::zone::objects::player::PlayerObjectImplementation::chatRooms protected
Definition at line 1007 of file PlayerObject.h.
Referenced by addChatRoom(), notifyLoadFromDatabase(), readObjectMember(), removeChatRoom(), unload(), and writeObjectMembers().
unsigned int server::zone::objects::player::PlayerObjectImplementation::clientLastMovementStamp protected
Definition at line 1053 of file PlayerObject.h.
Referenced by getClientLastMovementStamp(), notifyLoadFromDatabase(), PlayerObjectImplementation(), readObjectMember(), setClientLastMovementStamp(), and writeObjectMembers().
unsigned long long server::zone::objects::player::PlayerObjectImplementation::cloningFacility protected
Definition at line 1015 of file PlayerObject.h.
Referenced by getCloningFacility(), PlayerObjectImplementation(), readObjectMember(), setCloningFacility(), and writeObjectMembers().
VectorMap<unsigned int, String> server::zone::objects::player::PlayerObjectImplementation::commandMessageStrings protected
Definition at line 985 of file PlayerObject.h.
Referenced by getCommandMessageString(), hasCommandMessageString(), PlayerObjectImplementation(), readObjectMember(), removeCommandMessageString(), setCommandMessageString(), and writeObjectMembers().
SortedVector<String> server::zone::objects::player::PlayerObjectImplementation::consentList protected
Definition at line 1021 of file PlayerObject.h.
Referenced by addToConsentList(), getConsentListSize(), getConsentName(), hasInConsentList(), PlayerObjectImplementation(), readObjectMember(), removeFromConsentList(), and writeObjectMembers().
unsigned long long server::zone::objects::player::PlayerObjectImplementation::conversatingCreature protected
Definition at line 1029 of file PlayerObject.h.
Referenced by getConversatingCreature(), PlayerObjectImplementation(), readObjectMember(), setConversatingCreature(), and writeObjectMembers().
const int server::zone::objects::player::PlayerObjectImplementation::CSR = 1 static
Definition at line 1094 of file PlayerObject.h.
Referenced by isCSR().
bool server::zone::objects::player::PlayerObjectImplementation::debugOutput protected
Definition at line 1069 of file PlayerObject.h.
Referenced by getDebug(), PlayerObjectImplementation(), readObjectMember(), setDebug(), and writeObjectMembers().
unsigned long long server::zone::objects::player::PlayerObjectImplementation::declaredResidence protected
Definition at line 1013 of file PlayerObject.h.
Referenced by getDeclaredResidence(), PlayerObjectImplementation(), readObjectMember(), setDeclaredResidence(), and writeObjectMembers().
const int server::zone::objects::player::PlayerObjectImplementation::DEV = 2 static
Definition at line 1096 of file PlayerObject.h.
Referenced by isDeveloper().
Reference<PlayerDisconnectEvent*> server::zone::objects::player::PlayerObjectImplementation::disconnectEvent protected
Definition at line 1035 of file PlayerObject.h.
Referenced by clearDisconnectEvent(), disconnect(), logout(), and reload().
int server::zone::objects::player::PlayerObjectImplementation::drinkFilling protected
Definition at line 961 of file PlayerObject.h.
Referenced by doDigest(), getDrinkFilling(), loadTemplateData(), readObjectMember(), setDrinkFilling(), and writeObjectMembers().
int server::zone::objects::player::PlayerObjectImplementation::drinkFillingMax protected
Definition at line 963 of file PlayerObject.h.
Referenced by getDrinkFillingMax(), initializeTransientMembers(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
SortedVector<ManagedReference<CreatureObject* > > server::zone::objects::player::PlayerObjectImplementation::duelList protected
Definition at line 1009 of file PlayerObject.h.
Referenced by addToDuelList(), getDuelListObject(), getDuelListSize(), initializeTransientMembers(), isDuelListEmpty(), PlayerObjectImplementation(), removeFromDuelList(), and requestedDuelTo().
DeltaVectorMap<String, int> server::zone::objects::player::PlayerObjectImplementation::experienceList protected
Definition at line 987 of file PlayerObject.h.
Referenced by addExperience(), getExperience(), getExperienceList(), hasCappedExperience(), loadTemplateData(), readObjectMember(), removeExperience(), and writeObjectMembers().
const int server::zone::objects::player::PlayerObjectImplementation::FACTIONRANK = 0x200 static
Definition at line 1088 of file PlayerObject.h.
FactionStandingList server::zone::objects::player::PlayerObjectImplementation::factionStandingList protected
Definition at line 997 of file PlayerObject.h.
Referenced by decreaseFactionStanding(), getFactionRank(), getFactionStanding(), getFactionStandingList(), increaseFactionStanding(), readObjectMember(), setFactionRank(), and writeObjectMembers().
int server::zone::objects::player::PlayerObjectImplementation::factionStatus protected
Definition at line 1047 of file PlayerObject.h.
Referenced by getFactionStatus(), PlayerObjectImplementation(), readObjectMember(), setFactionStatus(), and writeObjectMembers().
int server::zone::objects::player::PlayerObjectImplementation::foodFilling protected
Definition at line 957 of file PlayerObject.h.
Referenced by doDigest(), getFoodFilling(), loadTemplateData(), readObjectMember(), setFoodFilling(), and writeObjectMembers().
int server::zone::objects::player::PlayerObjectImplementation::foodFillingMax protected
Definition at line 959 of file PlayerObject.h.
Referenced by getFoodFillingMax(), initializeTransientMembers(), loadTemplateData(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::player::PlayerObjectImplementation::forcePower protected
Definition at line 951 of file PlayerObject.h.
Referenced by getForcePower(), loadTemplateData(), PlayerObjectImplementation(), readObjectMember(), setForcePower(), setForcePowerMax(), and writeObjectMembers().
int server::zone::objects::player::PlayerObjectImplementation::forcePowerMax protected
Definition at line 953 of file PlayerObject.h.
Referenced by getForcePowerMax(), loadTemplateData(), PlayerObjectImplementation(), readObjectMember(), setForcePowerMax(), and writeObjectMembers().
int server::zone::objects::player::PlayerObjectImplementation::forcePowerRegen protected
Definition at line 955 of file PlayerObject.h.
Referenced by getForcePowerRegen(), loadTemplateData(), PlayerObjectImplementation(), readObjectMember(), setForcePowerRegen(), and writeObjectMembers().
FriendList server::zone::objects::player::PlayerObjectImplementation::friendList protected
Definition at line 993 of file PlayerObject.h.
Referenced by addFriend(), addReverseFriend(), getFriendList(), hasFriend(), notifyOffline(), notifyOnline(), readObjectMember(), removeFriend(), removeReverseFriend(), sendFriendLists(), and writeObjectMembers().
Vector<byte> server::zone::objects::player::PlayerObjectImplementation::hologrindProfessions protected
Definition at line 1051 of file PlayerObject.h.
Referenced by addHologrindProfession(), getHologrindProfessions(), readObjectMember(), and writeObjectMembers().
IgnoreList server::zone::objects::player::PlayerObjectImplementation::ignoreList protected
Definition at line 995 of file PlayerObject.h.
Referenced by addIgnore(), getIgnoreList(), isIgnoring(), readObjectMember(), removeIgnore(), sendFriendLists(), and writeObjectMembers().
byte server::zone::objects::player::PlayerObjectImplementation::incapacitationCounter protected
Definition at line 1001 of file PlayerObject.h.
Referenced by getIncapacitationCounter(), isFirstIncapacitation(), readObjectMember(), resetIncapacitationCounter(), updateIncapacitationCounter(), and writeObjectMembers().
int server::zone::objects::player::PlayerObjectImplementation::jediState protected
Definition at line 977 of file PlayerObject.h.
Referenced by getJediState(), isJedi(), loadTemplateData(), PlayerObjectImplementation(), readObjectMember(), setJediState(), and writeObjectMembers().
byte server::zone::objects::player::PlayerObjectImplementation::languageID protected
Definition at line 981 of file PlayerObject.h.
Referenced by getLanguageID(), loadTemplateData(), readObjectMember(), setLanguageID(), and writeObjectMembers().
Time server::zone::objects::player::PlayerObjectImplementation::lastDigestion protected
Definition at line 1075 of file PlayerObject.h.
Referenced by doRecovery(), PlayerObjectImplementation(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::PlayerObjectImplementation::lastNpcConvo protected
Definition at line 1025 of file PlayerObject.h.
Referenced by getLastNpcConvStr(), readObjectMember(), setLastNpcConvStr(), and writeObjectMembers().
String server::zone::objects::player::PlayerObjectImplementation::lastNpcConvoMessage protected
Definition at line 1023 of file PlayerObject.h.
Referenced by getLastNpcConvMessStr(), readObjectMember(), setLastNpcConvMessStr(), and writeObjectMembers().
Vector<String> server::zone::objects::player::PlayerObjectImplementation::lastNpcConvoOptions protected
Definition at line 1027 of file PlayerObject.h.
Referenced by addLastNpcConvOptions(), clearLastNpcConvOptions(), countLastNpcConvOptions(), getLastNpcConvOption(), readObjectMember(), and writeObjectMembers().
ValidatedPosition server::zone::objects::player::PlayerObjectImplementation::lastValidatedPosition protected
Definition at line 1057 of file PlayerObject.h.
Referenced by getLastValidatedPosition(), notifyLoadFromDatabase(), readObjectMember(), updateLastValidatedPosition(), and writeObjectMembers().
Time server::zone::objects::player::PlayerObjectImplementation::lastVisibilityUpdateTimestamp protected
Definition at line 1073 of file PlayerObject.h.
Referenced by getLastVisibilityUpdateTimestamp(), PlayerObjectImplementation(), readObjectMember(), setVisibility(), and writeObjectMembers().
const int server::zone::objects::player::PlayerObjectImplementation::LD = 0x100 static
Definition at line 1086 of file PlayerObject.h.
Referenced by setLinkDead(), and setOnline().
const int server::zone::objects::player::PlayerObjectImplementation::LFG = 1 static
Definition at line 1078 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObjectImplementation::LINKDEAD = 3 static
Definition at line 1102 of file PlayerObject.h.
Referenced by isLinkDead(), isOnline(), and setLinkDead().
const int server::zone::objects::player::PlayerObjectImplementation::LOADING = 6 static
Definition at line 1108 of file PlayerObject.h.
Referenced by isLoading().
const int server::zone::objects::player::PlayerObjectImplementation::LOGGINGIN = 4 static
Definition at line 1104 of file PlayerObject.h.
Referenced by isLoggingIn().
const int server::zone::objects::player::PlayerObjectImplementation::LOGGINGOUT = 5 static
Definition at line 1106 of file PlayerObject.h.
Referenced by isLoading(), isLoggingOut(), and setLoggingOut().
Time server::zone::objects::player::PlayerObjectImplementation::logoutTimeStamp protected
Definition at line 1039 of file PlayerObject.h.
Referenced by doRecovery(), readObjectMember(), setLinkDead(), and writeObjectMembers().
byte server::zone::objects::player::PlayerObjectImplementation::maximumLots protected
Definition at line 975 of file PlayerObject.h.
Referenced by getLotsRemaining(), getMaximumLots(), PlayerObjectImplementation(), readObjectMember(), setMaximumLots(), and writeObjectMembers().
const int server::zone::objects::player::PlayerObjectImplementation::NEWBIEHELPER = 2 static
Definition at line 1080 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObjectImplementation::NORMALPLAYER = 0 static
Definition at line 1092 of file PlayerObject.h.
const int server::zone::objects::player::PlayerObjectImplementation::OFFLINE = 2 static
Definition at line 1100 of file PlayerObject.h.
Referenced by isOffline(), isOnline(), and setOffline().
const int server::zone::objects::player::PlayerObjectImplementation::ONLINE = 1 static
Definition at line 1098 of file PlayerObject.h.
Referenced by setOnline().
int server::zone::objects::player::PlayerObjectImplementation::onlineStatus protected
Definition at line 1041 of file PlayerObject.h.
Referenced by isLinkDead(), isLoading(), isLoggingIn(), isLoggingOut(), isOffline(), isOnline(), readObjectMember(), setLinkDead(), setLoggingOut(), setOffline(), setOnline(), and writeObjectMembers().
SortedVector<unsigned long long> server::zone::objects::player::PlayerObjectImplementation::ownedStructures protected
Definition at line 971 of file PlayerObject.h.
Referenced by addOwnedStructure(), destroyObjectFromDatabase(), getLotsRemaining(), getOwnedStructure(), getTotalOwnedStructureCount(), isOwnedStructure(), readObjectMember(), removeOwnedStructure(), and writeObjectMembers().
SortedVector<unsigned long long> server::zone::objects::player::PlayerObjectImplementation::ownedVendors protected
Definition at line 973 of file PlayerObject.h.
Referenced by addVendor(), getVendorCount(), readObjectMember(), removeVendor(), and writeObjectMembers().
unsigned long long server::zone::objects::player::PlayerObjectImplementation::performanceBuffTarget protected
Definition at line 1067 of file PlayerObject.h.
Referenced by getPerformanceBuffTarget(), PlayerObjectImplementation(), readObjectMember(), setPerformanceBuffTarget(), and writeObjectMembers().
SortedVector<String> server::zone::objects::player::PlayerObjectImplementation::permissionGroups protected
Definition at line 1065 of file PlayerObject.h.
Referenced by addPermissionGroup(), getPermissionGroups(), hasPermissionGroup(), loadTemplateData(), readObjectMember(), removePermissionGroup(), and writeObjectMembers().
SortedVector<unsigned long long> server::zone::objects::player::PlayerObjectImplementation::persistentMessages protected
Definition at line 1017 of file PlayerObject.h.
Referenced by addPersistentMessage(), dropPersistentMessage(), getPersistentMessages(), PlayerObjectImplementation(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::player::PlayerObjectImplementation::pvpRating protected
Definition at line 1045 of file PlayerObject.h.
Referenced by readObjectMember(), and writeObjectMembers().
byte server::zone::objects::player::PlayerObjectImplementation::raceID protected
Definition at line 1061 of file PlayerObject.h.
Referenced by getRaceID(), PlayerObjectImplementation(), readObjectMember(), setRaceID(), and writeObjectMembers().
Reference<PlayerRecoveryEvent*> server::zone::objects::player::PlayerObjectImplementation::recoveryEvent protected
Definition at line 1037 of file PlayerObject.h.
Referenced by activateRecovery(), and clearRecoveryEvent().
const int server::zone::objects::player::PlayerObjectImplementation::ROLEPLAYER = 4 static
Definition at line 1082 of file PlayerObject.h.
unsigned long long server::zone::objects::player::PlayerObjectImplementation::savedParentID protected
Definition at line 947 of file PlayerObject.h.
Referenced by getSavedParentID(), PlayerObjectImplementation(), readObjectMember(), setSavedParentID(), unload(), and writeObjectMembers().
String server::zone::objects::player::PlayerObjectImplementation::savedTerrainName protected
Definition at line 945 of file PlayerObject.h.
Referenced by getSavedTerrainName(), readObjectMember(), setSavedTerrainName(), unload(), and writeObjectMembers().
SchematicList server::zone::objects::player::PlayerObjectImplementation::schematicList protected
Definition at line 999 of file PlayerObject.h.
Referenced by addRewardedSchematic(), addSchematics(), decreaseSchematicUseCount(), filterSchematicList(), getSchematic(), getSchematics(), readObjectMember(), removeRewardedSchematic(), removeSchematics(), and writeObjectMembers().
VectorMap<String, String> server::zone::objects::player::PlayerObjectImplementation::screenPlayData protected
Definition at line 1063 of file PlayerObject.h.
Referenced by clearScreenPlayData(), getScreenPlayData(), readObjectMember(), setScreenPlayData(), and writeObjectMembers().
Time server::zone::objects::player::PlayerObjectImplementation::serverLastMovementStamp protected
Definition at line 1055 of file PlayerObject.h.
Referenced by getServerMovementTimeDelta(), getServerMovementTimeStamp(), notifyLoadFromDatabase(), readObjectMember(), updateLastValidatedPosition(), updateServerLastMovementStamp(), and writeObjectMembers().
int server::zone::objects::player::PlayerObjectImplementation::skillPoints protected
Definition at line 1043 of file PlayerObject.h.
Referenced by addSkillPoints(), getSkillPoints(), PlayerObjectImplementation(), readObjectMember(), setSkillPoints(), and writeObjectMembers().
bool server::zone::objects::player::PlayerObjectImplementation::spawnedBlueFrog protected
Definition at line 1049 of file PlayerObject.h.
Referenced by hasSpawnedBlueFrog(), PlayerObjectImplementation(), and setSpawnedBlueFrog().
String server::zone::objects::player::PlayerObjectImplementation::starterProfession protected
Definition at line 965 of file PlayerObject.h.
Referenced by getStarterProfession(), readObjectMember(), setStarterProfession(), and writeObjectMembers().
VectorMap<unsigned int, ManagedReference<SuiBox* > > server::zone::objects::player::PlayerObjectImplementation::suiBoxes protected
Definition at line 1005 of file PlayerObject.h.
Referenced by addSuiBox(), getSuiBox(), getSuiBoxFromWindowType(), hasSuiBox(), hasSuiBoxWindowType(), notifyOnline(), readObjectMember(), removeSuiBox(), and writeObjectMembers().
unsigned int server::zone::objects::player::PlayerObjectImplementation::suiBoxNextID protected
Definition at line 1003 of file PlayerObject.h.
Referenced by getNewSuiBoxID(), PlayerObjectImplementation(), readObjectMember(), and writeObjectMembers().
bool server::zone::objects::player::PlayerObjectImplementation::teleporting protected
Definition at line 969 of file PlayerObject.h.
Referenced by isTeleporting(), notifySceneReady(), PlayerObjectImplementation(), readObjectMember(), setTeleporting(), and writeObjectMembers().
String server::zone::objects::player::PlayerObjectImplementation::title protected
Definition at line 943 of file PlayerObject.h.
Referenced by getTitle(), readObjectMember(), setTitle(), and writeObjectMembers().
Vector3 server::zone::objects::player::PlayerObjectImplementation::trainerCoordinates protected
Definition at line 1031 of file PlayerObject.h.
Referenced by getTrainerCoordinates(), readObjectMember(), setTrainerCoordinates(), and writeObjectMembers().
String server::zone::objects::player::PlayerObjectImplementation::trainerZoneName protected
Definition at line 1033 of file PlayerObject.h.
Referenced by getTrainerZoneName(), loadTemplateData(), PlayerObjectImplementation(), readObjectMember(), setTrainerZoneName(), and writeObjectMembers().
float server::zone::objects::player::PlayerObjectImplementation::visibility protected
Definition at line 1071 of file PlayerObject.h.
Referenced by getVisibility(), PlayerObjectImplementation(), readObjectMember(), setVisibility(), and writeObjectMembers().
WaypointList server::zone::objects::player::PlayerObjectImplementation::waypointList protected
Definition at line 989 of file PlayerObject.h.
Referenced by addWaypoint(), getWaypointList(), hasWaypoint(), readObjectMember(), removeWaypoint(), setWaypoint(), and writeObjectMembers().
VectorMap<String, int> server::zone::objects::player::PlayerObjectImplementation::xpTypeCapList protected
Definition at line 983 of file PlayerObject.h.
Referenced by addExperience(), getXpTypeCapList(), hasCappedExperience(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/PlayerObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/PlayerObject.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/PlayerObjectImplementation.cpp