Core3: AuctionTerminalMap Class Reference
AuctionTerminalMap Class Reference
#include <AuctionTerminalMap.h>
Public Member Functions
AuctionTerminalMap ()
bool createTerminalListing (const String &planet, const String &region, SceneObject *vendor)
bool dropTerminalListing (SceneObject *vendor)
bool updateTerminalUID (const String &planet, const String &region, SceneObject *vendor, const String &newVuid)
void updateTerminalSearch (SceneObject *vendor, bool enabled)
TerminalListVector getTerminalData (const String &planet, const String &region, SceneObject *vendor)
TerminalListVector getGalaxyListing ()
TerminalListVector getPlanetListing (const String &planet)
TerminalListVector getRegionListing (const String &planet, const String &region)
Private Member Functions
bool addPlanetListing (const String &planet)
bool removePlanetListing (const String &planet)
bool addRegionListing (TerminalPlanetList *planetList, const String &region)
bool removeRegionListing (TerminalPlanetList *planetList, const String &region)
TerminalRegionList * getVendorRegion (SceneObject *vendor)
Pre Locked.
void getPlanetListing (TerminalListVector *terminals, TerminalPlanetList *planetList)
void getRegionListing (TerminalListVector *terminals, TerminalRegionList *regionList)
Private Attributes
TerminalGalaxyList galaxyListing
Detailed Description
Definition at line 17 of file AuctionTerminalMap.h.
Constructor & Destructor Documentation
AuctionTerminalMap::AuctionTerminalMap () inline
Definition at line 22 of file AuctionTerminalMap.h.
References galaxyListing.
Member Function Documentation
bool AuctionTerminalMap::addPlanetListing (const String & planet) inline private
Definition at line 217 of file AuctionTerminalMap.h.
References galaxyListing.
Referenced by createTerminalListing().
bool AuctionTerminalMap::addRegionListing (TerminalPlanetList * planetList, const String & region) inline private
Definition at line 237 of file AuctionTerminalMap.h.
Referenced by createTerminalListing().
bool AuctionTerminalMap::createTerminalListing (const String & planet, const String & region, SceneObject * vendor) inline
Definition at line 32 of file AuctionTerminalMap.h.
References addPlanetListing(), addRegionListing(), galaxyListing, server::zone::objects::scene::SceneObject::getObjectID(), and getVendorRegion().
Referenced by server::zone::managers::auction::AuctionsMapImplementation::addBazaarItem(), server::zone::managers::auction::AuctionsMapImplementation::addVendorItem(), and updateTerminalUID().
bool AuctionTerminalMap::dropTerminalListing (SceneObject * vendor) inline
Definition at line 81 of file AuctionTerminalMap.h.
References server::zone::objects::scene::SceneObject::getObjectID(), and getVendorRegion().
Referenced by server::zone::managers::auction::AuctionsMapImplementation::deleteTerminalItems().
TerminalListVector AuctionTerminalMap::getGalaxyListing () inline
Definition at line 165 of file AuctionTerminalMap.h.
Referenced by getTerminalData().
TerminalListVector AuctionTerminalMap::getPlanetListing (const String & planet) inline
Definition at line 187 of file AuctionTerminalMap.h.
References galaxyListing.
Referenced by getTerminalData().
void AuctionTerminalMap::getPlanetListing (TerminalListVector * terminals, TerminalPlanetList * planetList) inline private
Definition at line 283 of file AuctionTerminalMap.h.
References getRegionListing().
TerminalListVector AuctionTerminalMap::getRegionListing (const String & planet, const String & region) inline
Definition at line 200 of file AuctionTerminalMap.h.
References galaxyListing.
Referenced by getPlanetListing(), and getTerminalData().
void AuctionTerminalMap::getRegionListing (TerminalListVector * terminals, TerminalRegionList * regionList) inline private
Definition at line 299 of file AuctionTerminalMap.h.
TerminalListVector AuctionTerminalMap::getTerminalData (const String & planet, const String & region, SceneObject * vendor) inline
Definition at line 145 of file AuctionTerminalMap.h.
References getGalaxyListing(), server::zone::objects::scene::SceneObject::getObjectID(), getPlanetListing(), and getRegionListing().
Referenced by server::zone::managers::auction::AuctionsMapImplementation::getBazaarTerminalData(), and server::zone::managers::auction::AuctionsMapImplementation::getVendorTerminalData().
TerminalRegionList* AuctionTerminalMap::getVendorRegion (SceneObject * vendor) inline private
Pre Locked.
Definition at line 258 of file AuctionTerminalMap.h.
References galaxyListing, and server::zone::objects::scene::SceneObject::getObjectID().
Referenced by createTerminalListing(), and dropTerminalListing().
bool AuctionTerminalMap::removePlanetListing (const String & planet) inline private
Definition at line 229 of file AuctionTerminalMap.h.
References galaxyListing.
bool AuctionTerminalMap::removeRegionListing (TerminalPlanetList * planetList, const String & region) inline private
Definition at line 249 of file AuctionTerminalMap.h.
void AuctionTerminalMap::updateTerminalSearch (SceneObject * vendor, bool enabled) inline
Definition at line 131 of file AuctionTerminalMap.h.
References server::zone::objects::scene::SceneObject::getObjectID(), and server::zone::objects::scene::SceneObject::isBazaarTerminal().
Referenced by server::zone::managers::auction::AuctionsMapImplementation::updateVendorSearch().
bool AuctionTerminalMap::updateTerminalUID (const String & planet, const String & region, SceneObject * vendor, const String & newVuid) inline
Definition at line 101 of file AuctionTerminalMap.h.
References createTerminalListing(), and server::zone::objects::scene::SceneObject::getObjectID().
Referenced by server::zone::managers::auction::AuctionsMapImplementation::updateUID().
Member Data Documentation
TerminalGalaxyList AuctionTerminalMap::galaxyListing private
Definition at line 19 of file AuctionTerminalMap.h.
Referenced by addPlanetListing(), AuctionTerminalMap(), createTerminalListing(), getPlanetListing(), getRegionListing(), getVendorRegion(), and removePlanetListing().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionTerminalMap.h