Core3: ResourceContainerObjectMessage6 Class Reference
ResourceContainerObjectMessage6 Class Reference
#include <ResourceContainerObjectMessage6.h>
Public Member Functions
ResourceContainerObjectMessage6 (ResourceContainer *rcno)
Public Member Functions inherited from BaseLineMessage
BaseLineMessage (uint64 oid, uint32 name, uint8 type, uint16 opcnt)
uint32 generateRandomObjectCRC ()
void setSize ()
void insertStringId (StringId *id)
void insertCustomName (const UnicodeString &name)
Detailed Description
Definition at line 51 of file ResourceContainerObjectMessage6.h.
Constructor & Destructor Documentation
ResourceContainerObjectMessage6::ResourceContainerObjectMessage6 (ResourceContainer * rcno) inline
Definition at line 53 of file ResourceContainerObjectMessage6.h.
References server::zone::objects::resource::ResourceContainer::getSpawnName(), server::zone::objects::resource::ResourceContainer::getSpawnType(), and BaseLineMessage::setSize().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/resource/ResourceContainerObjectMessage6.h