Core3: RegisterVendorSuiCallback Class Reference
RegisterVendorSuiCallback Class Reference
#include <RegisterVendorSuiCallback.h>
Public Member Functions
RegisterVendorSuiCallback (ZoneServer *server)
void run (CreatureObject *player, SuiBox *suiBox, bool cancelPressed, Vector< UnicodeString > *args)
Public Member Functions inherited from server::zone::objects::player::sui::SuiCallback
SuiCallback (ZoneServer *serv)
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::player::sui::SuiCallback
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 15 of file RegisterVendorSuiCallback.h.
Constructor & Destructor Documentation
RegisterVendorSuiCallback::RegisterVendorSuiCallback (ZoneServer * server) inline
Definition at line 17 of file RegisterVendorSuiCallback.h.
Member Function Documentation
void RegisterVendorSuiCallback::run (CreatureObject * player, SuiBox * suiBox, bool cancelPressed, Vector< UnicodeString > * args) inline virtual
Parameters
player The player that this suibox is assigned to.
suiBox The actual SuiBox object.
cancelPressed Was the cancel button pressed, or was the sui box closed via a similar method. (this might actually be more of a dialogResult type variable)
args A vector of UnicodeStrings containing the arguments passed to the sui box from the client.
Implements server::zone::objects::player::sui::SuiCallback.
Definition at line 21 of file RegisterVendorSuiCallback.h.
References server::zone::objects::player::sui::listbox::SuiListBox::getMenuItemName(), server::zone::objects::player::sui::SuiBox::getUsingObject(), and server::zone::objects::player::sui::SuiBox::isListBox().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/vendor/sui/RegisterVendorSuiCallback.h