Core3: FloorMeshTriangleNode Class Reference
FloorMeshTriangleNode Class Reference
#include <FloorMesh.h>
Public Member Functions
FloorMeshTriangleNode (FloorMesh *floorMesh)
void readObject (IffStream *iffStream)
void setEdge (bool val)
bool isEdge ()
bool hasNorthWestTriangle ()
bool hasNorthEastTriangle ()
bool hasSouthTriangle ()
uint32 getID ()
void addNeighbor (TriangleNode *node)
int getNorthWestTriangle ()
int getNorthEastTriangle ()
int getSouthTriangle ()
Vector< TriangleNode * > * getNeighbors ()
Private Attributes
int northWestTriangle
int northEastTriangle
int southTriangle
uint32 id
Vector< TriangleNode * > neighbors
float var8
float var9
float var10
byte var14
int var15
int var16
int var17
int var18
FloorMesh * mesh
bool edge
Detailed Description
Definition at line 105 of file FloorMesh.h.
Constructor & Destructor Documentation
FloorMeshTriangleNode::FloorMeshTriangleNode (FloorMesh * floorMesh) inline
Definition at line 118 of file FloorMesh.h.
References edge, mesh, northEastTriangle, northWestTriangle, southTriangle, var10, var14, var15, var16, var17, var18, var8, and var9.
Member Function Documentation
void FloorMeshTriangleNode::addNeighbor (TriangleNode * node) inline
Definition at line 155 of file FloorMesh.h.
References neighbors.
Referenced by FloorMesh::readObject().
uint32 FloorMeshTriangleNode::getID () inline
Definition at line 151 of file FloorMesh.h.
References id.
Vector<TriangleNode*>* FloorMeshTriangleNode::getNeighbors () inline
Definition at line 171 of file FloorMesh.h.
References neighbors.
int FloorMeshTriangleNode::getNorthEastTriangle () inline
Definition at line 163 of file FloorMesh.h.
References northEastTriangle.
Referenced by FloorMesh::readObject().
int FloorMeshTriangleNode::getNorthWestTriangle () inline
Definition at line 159 of file FloorMesh.h.
References northWestTriangle.
Referenced by FloorMesh::readObject().
int FloorMeshTriangleNode::getSouthTriangle () inline
Definition at line 167 of file FloorMesh.h.
References southTriangle.
Referenced by FloorMesh::readObject().
bool FloorMeshTriangleNode::hasNorthEastTriangle () inline
Definition at line 143 of file FloorMesh.h.
References northEastTriangle.
Referenced by readObject(), and FloorMesh::readObject().
bool FloorMeshTriangleNode::hasNorthWestTriangle () inline
Definition at line 139 of file FloorMesh.h.
References northWestTriangle.
Referenced by readObject(), and FloorMesh::readObject().
bool FloorMeshTriangleNode::hasSouthTriangle () inline
Definition at line 147 of file FloorMesh.h.
References southTriangle.
Referenced by readObject(), and FloorMesh::readObject().
bool FloorMeshTriangleNode::isEdge () inline
Definition at line 134 of file FloorMesh.h.
References neighbors.
void FloorMeshTriangleNode::readObject (IffStream * iffStream)
Definition at line 12 of file FloorMesh.cpp.
References FloorMesh::getVertex(), Vert::getX(), Vert::getY(), Vert::getZ(), hasNorthEastTriangle(), hasNorthWestTriangle(), hasSouthTriangle(), mesh, northEastTriangle, northWestTriangle, southTriangle, var10, var14, var15, var16, var17, var18, var8, and var9.
Referenced by FloorMesh::parseVersion0005(), and FloorMesh::parseVersion0006().
void FloorMeshTriangleNode::setEdge (bool val) inline
Definition at line 130 of file FloorMesh.h.
References edge.
Member Data Documentation
bool FloorMeshTriangleNode::edge private
Definition at line 115 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), and setEdge().
uint32 FloorMeshTriangleNode::id private
Definition at line 108 of file FloorMesh.h.
Referenced by getID().
FloorMesh* FloorMeshTriangleNode::mesh private
Definition at line 114 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), and readObject().
Vector<TriangleNode*> FloorMeshTriangleNode::neighbors private
Definition at line 109 of file FloorMesh.h.
Referenced by addNeighbor(), getNeighbors(), and isEdge().
int FloorMeshTriangleNode::northEastTriangle private
Definition at line 107 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), getNorthEastTriangle(), hasNorthEastTriangle(), and readObject().
int FloorMeshTriangleNode::northWestTriangle private
Definition at line 107 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), getNorthWestTriangle(), hasNorthWestTriangle(), and readObject().
int FloorMeshTriangleNode::southTriangle private
Definition at line 107 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), getSouthTriangle(), hasSouthTriangle(), and readObject().
float FloorMeshTriangleNode::var10 private
Definition at line 111 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), and readObject().
byte FloorMeshTriangleNode::var14 private
Definition at line 112 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), and readObject().
int FloorMeshTriangleNode::var15 private
Definition at line 113 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), and readObject().
int FloorMeshTriangleNode::var16 private
Definition at line 113 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), and readObject().
int FloorMeshTriangleNode::var17 private
Definition at line 113 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), and readObject().
int FloorMeshTriangleNode::var18 private
Definition at line 113 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), and readObject().
float FloorMeshTriangleNode::var8 private
Definition at line 111 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), and readObject().
float FloorMeshTriangleNode::var9 private
Definition at line 111 of file FloorMesh.h.
Referenced by FloorMeshTriangleNode(), and readObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/FloorMesh.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/FloorMesh.cpp