Core3: LootContainerComponent Class Reference
LootContainerComponent Class Reference
#include <LootContainerComponent.h>
Public Member Functions
int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
Public Member Functions inherited from ContainerComponent
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
virtual int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
Detailed Description
Definition at line 13 of file LootContainerComponent.h.
Member Function Documentation
int LootContainerComponent::canAddObject (SceneObject * sceneObject, SceneObject * object, int containmentType, String & errorDescription) virtual
Evaluates if this object has the necessary free slots to be able to add the specified SceneObject
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be checked
error error string that the player will receive on error
Returns
returns 0 on success, or error code
Reimplemented from ContainerComponent.
Definition at line 54 of file LootContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::getContainerObjectsSize(), and TransferErrorCode::INVALIDTYPE.
bool LootContainerComponent::checkContainerPermission (SceneObject * sceneObject, CreatureObject * creature, uint16 permission) virtual
Reimplemented from ContainerComponent.
Definition at line 43 of file LootContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::getContainerPermissions(), server::zone::objects::creature::CreatureObject::getGroupID(), server::zone::objects::scene::SceneObject::getObjectID(), and server::zone::objects::scene::variables::ContainerPermissions::getOwnerID().
int LootContainerComponent::notifyObjectRemoved (SceneObject * sceneObject, SceneObject * object, SceneObject * destination) virtual
Is called when an object was removed
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 12 of file LootContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setTO(), server::chat::StringIdChatParameter::setTT(), and server::chat::StringIdChatParameter::setTU().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/LootContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/LootContainerComponent.cpp