Core3: WanderingStateComponent Class Reference
WanderingStateComponent Class Reference
#include <WanderingStateComponent.h>
Public Member Functions
uint16 onEnter (AiActor *actor)
uint16 doRecovery (AiActor *actor)
float getSpeed (CreatureObject *host)
Public Member Functions inherited from AiStateComponent
virtual void notifyPositionUpdate (Observable *obs, QuadTreeEntry *entry)
void notifyDespawn (AiActor *actor, Zone *zone)
virtual void doAwarenessCheck (Observable *obs, Coordinate &start, uint64 time, CreatureObject *target)
virtual void onExit (AiActor *actor)
virtual uint16 tryRetreat (AiActor *actor)
virtual uint16 doAttack (AiActor *actor)
virtual uint16 doMovement (AiActor *actor)
bool findNextPosition (Observable *obs, float maxDistance, float speed, PatrolPointsVector *patrolPoints, WorldCoordinates *nextPosition)
virtual float getMaxDistance (CreatureObject *host)
void setNextPosition (AiActor *actor, float x, float z, float y, SceneObject *cell=NULL)
void updateCurrentPosition (CreatureObject *host, PatrolPoint *pos)
void broadcastNextPositionUpdate (CreatureObject *host, PatrolPoint *point)
void checkNewAngle (AiActor *actor)
void sendConversationStartTo (CreatureObject *host, SceneObject *player)
void selectWeapon (AiActor *actor)
bool validateStateAttack (CreatureObject *target, String &args)
virtual bool isScared (CreatureObject *host, SceneObject *followObject)
Detailed Description
Definition at line 17 of file WanderingStateComponent.h.
Member Function Documentation
uint16 WanderingStateComponent::doRecovery (AiActor * actor) inline virtual
Reimplemented from AiStateComponent.
Definition at line 52 of file WanderingStateComponent.h.
References server::zone::objects::creature::CreatureObject::activateHAMRegeneration(), server::zone::objects::creature::ai::AiActor::activatePostureRecovery(), and server::zone::objects::creature::ai::AiActor::getHost().
float WanderingStateComponent::getSpeed (CreatureObject * host) inline virtual
Reimplemented from AiStateComponent.
Definition at line 73 of file WanderingStateComponent.h.
References server::zone::objects::creature::CreatureObject::getWalkSpeed().
uint16 WanderingStateComponent::onEnter (AiActor * actor) inline virtual
Reimplemented from AiStateComponent.
Definition at line 19 of file WanderingStateComponent.h.
References server::zone::objects::creature::ai::AiActor::activateMovementEvent(), server::zone::objects::creature::ai::AiActor::activateRecovery(), PatrolPoint::getCoordinates(), server::zone::objects::creature::ai::AiActor::getHomeLocation(), server::zone::objects::creature::ai::AiActor::getHost(), server::zone::objects::creature::ai::AiActor::getPatrolPoints(), WorldCoordinates::getX(), WorldCoordinates::getY(), WorldCoordinates::getZ(), and AiStateComponent::setNextPosition().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/components/WanderingStateComponent.h