Core3: MapLocationEntry Class Reference
MapLocationEntry Class Reference
#include <MapLocationEntry.h>
Public Member Functions
MapLocationEntry ()
MapLocationEntry (SceneObject *obj)
MapLocationEntry (const MapLocationEntry &entry)
int compareTo (const MapLocationEntry &entry) const
bool insertToMessage (BaseMessage *message, unsigned int faction=0) const
MapLocationEntry & operator= (const MapLocationEntry &entry)
uint64 getObjectID () const
void setObject (SceneObject *obj)
SceneObject * getObject ()
bool isActive ()
void setActive (bool act)
Private Attributes
ManagedReference< SceneObject * > object
UnicodeString displayName
bool active
Detailed Description
Definition at line 30 of file MapLocationEntry.h.
Constructor & Destructor Documentation
MapLocationEntry::MapLocationEntry () inline
Definition at line 36 of file MapLocationEntry.h.
MapLocationEntry::MapLocationEntry (SceneObject * obj) inline
Definition at line 40 of file MapLocationEntry.h.
MapLocationEntry::MapLocationEntry (const MapLocationEntry & entry) inline
Definition at line 45 of file MapLocationEntry.h.
References active, displayName, and object.
Member Function Documentation
int MapLocationEntry::compareTo (const MapLocationEntry & entry) const
Definition at line 24 of file MapLocationEntry.cpp.
References getObjectID().
SceneObject* MapLocationEntry::getObject () inline
Definition at line 61 of file MapLocationEntry.h.
Referenced by server::zone::ZoneImplementation::getPlanetaryObjectList().
uint64 MapLocationEntry::getObjectID () const
Definition at line 20 of file MapLocationEntry.cpp.
Referenced by compareTo().
bool MapLocationEntry::insertToMessage (BaseMessage * message, unsigned int faction = 0) const
Definition at line 117 of file MapLocationEntry.cpp.
References active, displayName, PlanetMapCategory::getFaction(), PlanetMapCategory::getIndex(), PlanetMapCategory::isFactionVisibleOnly(), and object.
bool MapLocationEntry::isActive () inline
Definition at line 65 of file MapLocationEntry.h.
MapLocationEntry & MapLocationEntry::operator= (const MapLocationEntry & entry)
Definition at line 33 of file MapLocationEntry.cpp.
References active, and object.
void MapLocationEntry::setActive (bool act) inline
Sets whether or not this map location entry is currently active.
Parameters
act This parameter should be true if you wish this location's status be marked as active.
Definition at line 73 of file MapLocationEntry.h.
void MapLocationEntry::setObject (SceneObject * obj)
Definition at line 43 of file MapLocationEntry.cpp.
References displayName, server::zone::objects::creature::CreatureObject::getFirstName(), PlanetMapCategory::getIndex(), server::zone::objects::creature::CreatureObject::getLastName(), PlanetTravelPoint::getPointName(), server::zone::objects::tangible::terminal::mission::MissionTerminal::getTerminalName(), object, MapLocationType::SHUTTLEPORT, and MapLocationType::TERMINAL.
Member Data Documentation
bool MapLocationEntry::active private
Definition at line 33 of file MapLocationEntry.h.
Referenced by insertToMessage(), MapLocationEntry(), and operator=().
UnicodeString MapLocationEntry::displayName private
Definition at line 32 of file MapLocationEntry.h.
Referenced by insertToMessage(), MapLocationEntry(), and setObject().
ManagedReference<SceneObject*> MapLocationEntry::object private
Definition at line 31 of file MapLocationEntry.h.
Referenced by insertToMessage(), MapLocationEntry(), operator=(), and setObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/MapLocationEntry.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/MapLocationEntry.cpp