Core3: server::zone::objects::player::sessions::survey::SurveySessionImplementation Class Reference
server::zone::objects::player::sessions::survey::SurveySessionImplementation Class Reference
#include <SurveySession.h>
Public Member Functions
SurveySessionImplementation (CreatureObject *creature)
SurveySessionImplementation (DummyConstructorParameter *param)
int initializeSession (SurveyTool *tool)
int cancelSession ()
int clearSession ()
void startSurvey (const String &resname)
void reSample ()
void startSample (const String &resname)
void surveyCnodeMinigame (int value)
void surveyGnodeMinigame (int value)
ManagedWeakReference
< SurveyTool * > getActiveSurveyTool ()
void setActiveSurveyTool (SurveyTool *tool)
ManagedWeakReference
< SurveyTool * > getOpenSurveyTool ()
void setOpenSurveyTool (SurveyTool *tool)
bool tryGamble ()
void clearGamble ()
Coordinate * getRichSampleLocation ()
void clearRichSampleLocation ()
void rescheduleSurvey (SurveyMessage *surveyMessage, WaypointObject *waypoint, float maxDensity, ResourceSpawn *resourceSpawn)
void rescheduleSample ()
void rescheduleSampleResults (ResourceSpawner *resourceSpawner, float density, const String &resname)
operator const SurveySession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< SurveySession * > _this
Protected Member Functions
virtual ~SurveySessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > surveyer
ManagedWeakReference
< PlayerObject * > surveyerGhost
ManagedWeakReference
< SurveyTool * > activeSurveyTool
ManagedWeakReference
< SurveyTool * > openSurveyTool
ManagedWeakReference
< ResourceManager * > resourceManager
Reference< Coordinate * > richSampleLocation
bool doGamble
String lastResourceSampleName
Reference< Task * > surveyTask
Reference< Task * > sampleTask
Reference< Task * > sampleResultsTask
Private Member Functions
int startSession ()
void surveyCnodeMinigameSui ()
void surveyGnodeMinigameSui ()
Friends
class SurveySession
Detailed Description
Definition at line 218 of file SurveySession.h.
Constructor & Destructor Documentation
SurveySessionImplementation::SurveySessionImplementation (CreatureObject * creature)
Definition at line 415 of file SurveySession.cpp.
References _initializeImplementation(), doGamble, lastResourceSampleName, richSampleLocation, and surveyer.
SurveySessionImplementation::SurveySessionImplementation (DummyConstructorParameter * param)
Definition at line 301 of file SurveySession.cpp.
References _initializeImplementation().
SurveySessionImplementation::~SurveySessionImplementation () protected virtual
Definition at line 306 of file SurveySession.cpp.
Member Function Documentation
DistributedObjectStub * SurveySessionImplementation::_getStub ()
Definition at line 326 of file SurveySession.cpp.
References _this.
void SurveySessionImplementation::_initializeImplementation () protected
Definition at line 313 of file SurveySession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SurveySessionImplementation().
void SurveySessionImplementation::_serializationHelperMethod () protected
Definition at line 362 of file SurveySession.cpp.
Referenced by _initializeImplementation().
void SurveySessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 321 of file SurveySession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::SurveySession().
int SurveySessionImplementation::cancelSession ()
Definition at line 51 of file SurveySessionImplementation.cpp.
References clearSession(), SessionFacadeType::SURVEY, and surveyer.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::cancelSession(), and startSession().
void SurveySessionImplementation::clearGamble ()
Definition at line 461 of file SurveySession.cpp.
References doGamble.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::clearGamble().
void SurveySessionImplementation::clearRichSampleLocation ()
Definition at line 471 of file SurveySession.cpp.
References richSampleLocation.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::clearRichSampleLocation().
int SurveySessionImplementation::clearSession ()
Definition at line 61 of file SurveySessionImplementation.cpp.
Referenced by cancelSession(), and server::zone::objects::player::sessions::survey::SurveySession::clearSession().
void SurveySessionImplementation::finalize () protected
Definition at line 310 of file SurveySession.cpp.
ManagedWeakReference< SurveyTool * > SurveySessionImplementation::getActiveSurveyTool ()
Definition at line 436 of file SurveySession.cpp.
References activeSurveyTool.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::getActiveSurveyTool().
ManagedWeakReference< SurveyTool * > SurveySessionImplementation::getOpenSurveyTool ()
Definition at line 446 of file SurveySession.cpp.
References openSurveyTool.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::getOpenSurveyTool().
Coordinate * SurveySessionImplementation::getRichSampleLocation ()
Definition at line 466 of file SurveySession.cpp.
References richSampleLocation.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::getRichSampleLocation().
int SurveySessionImplementation::initializeSession (SurveyTool * tool)
Definition at line 23 of file SurveySessionImplementation.cpp.
References activeSurveyTool, startSession(), surveyer, and surveyerGhost.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::initializeSession().
void SurveySessionImplementation::lock (bool doLock = true) protected
Definition at line 334 of file SurveySession.cpp.
References _this.
void SurveySessionImplementation::lock (ManagedObject * obj) protected
Definition at line 338 of file SurveySession.cpp.
References _this.
SurveySessionImplementation::operator const SurveySession * ()
Definition at line 330 of file SurveySession.cpp.
void SurveySessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 369 of file SurveySession.cpp.
References readObjectMember().
bool SurveySessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 388 of file SurveySession.cpp.
Referenced by readObject().
void SurveySessionImplementation::reSample ()
Definition at line 431 of file SurveySession.cpp.
References lastResourceSampleName, and startSample().
Referenced by server::zone::objects::player::sessions::survey::SurveySession::reSample().
void SurveySessionImplementation::rescheduleSample ()
Definition at line 360 of file SurveySessionImplementation.cpp.
References activeSurveyTool, sampleTask, and surveyer.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::rescheduleSample(), surveyCnodeMinigame(), and surveyGnodeMinigame().
void SurveySessionImplementation::rescheduleSampleResults (ResourceSpawner * resourceSpawner, float density, const String & resname)
Definition at line 369 of file SurveySessionImplementation.cpp.
References sampleResultsTask, and surveyer.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::rescheduleSampleResults().
void SurveySessionImplementation::rescheduleSurvey (SurveyMessage * surveyMessage, WaypointObject * waypoint, float maxDensity, ResourceSpawn * resourceSpawn)
Definition at line 355 of file SurveySessionImplementation.cpp.
References surveyer, and surveyTask.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::rescheduleSurvey().
void SurveySessionImplementation::rlock (bool doLock = true) protected
Definition at line 342 of file SurveySession.cpp.
References _this.
void SurveySessionImplementation::runlock (bool doLock = true) protected
Definition at line 358 of file SurveySession.cpp.
References _this.
void SurveySessionImplementation::setActiveSurveyTool (SurveyTool * tool)
Definition at line 441 of file SurveySession.cpp.
References activeSurveyTool.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::setActiveSurveyTool().
void SurveySessionImplementation::setOpenSurveyTool (SurveyTool * tool)
Definition at line 451 of file SurveySession.cpp.
References openSurveyTool.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::setOpenSurveyTool().
void SurveySessionImplementation::startSample (const String & resname)
Definition at line 139 of file SurveySessionImplementation.cpp.
References CreatureAttribute::ACTION, activeSurveyTool, CreaturePosture::CROUCHED, doGamble, lastResourceSampleName, CreatureAttribute::QUICKNESS, resourceManager, richSampleLocation, server::chat::StringIdChatParameter::setTO(), SuiWindowType::SURVEY_TOOL_CONCENTRATED_MINIGAME, SuiWindowType::SURVEY_TOOL_CONCENTRATED_MINIGAME2, surveyCnodeMinigameSui(), surveyer, surveyerGhost, surveyGnodeMinigameSui(), and CreaturePosture::UPRIGHT.
Referenced by reSample(), and server::zone::objects::player::sessions::survey::SurveySession::startSample().
int SurveySessionImplementation::startSession () private
Definition at line 30 of file SurveySessionImplementation.cpp.
References _this, activeSurveyTool, cancelSession(), resourceManager, SessionFacadeType::SURVEY, surveyer, and surveyerGhost.
Referenced by initializeSession().
void SurveySessionImplementation::startSurvey (const String & resname)
Definition at line 66 of file SurveySessionImplementation.cpp.
References activeSurveyTool, CreatureAttribute::FOCUS, CreatureAttribute::MIND, resourceManager, server::chat::StringIdChatParameter::setTO(), surveyer, and CreaturePosture::UPRIGHT.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::startSurvey().
void SurveySessionImplementation::surveyCnodeMinigame (int value)
Definition at line 270 of file SurveySessionImplementation.cpp.
References activeSurveyTool, server::zone::objects::player::PlayerObject::addWaypoint(), server::zone::objects::player::PlayerObject::getSurveyWaypoint(), server::zone::objects::player::PlayerObject::removeWaypoint(), rescheduleSample(), resourceManager, richSampleLocation, surveyer, surveyerGhost, and CreaturePosture::UPRIGHT.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::surveyCnodeMinigame().
void SurveySessionImplementation::surveyCnodeMinigameSui () private
Definition at line 249 of file SurveySessionImplementation.cpp.
References SuiWindowType::SURVEY_TOOL_CONCENTRATED_MINIGAME, and surveyer.
Referenced by startSample().
void SurveySessionImplementation::surveyGnodeMinigame (int value)
Definition at line 337 of file SurveySessionImplementation.cpp.
References CreatureAttribute::ACTION, activeSurveyTool, doGamble, rescheduleSample(), and surveyer.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::surveyGnodeMinigame().
void SurveySessionImplementation::surveyGnodeMinigameSui () private
Definition at line 317 of file SurveySessionImplementation.cpp.
References SuiWindowType::SURVEY_TOOL_CONCENTRATED_MINIGAME2, and surveyer.
Referenced by startSample().
bool SurveySessionImplementation::tryGamble ()
Definition at line 456 of file SurveySession.cpp.
References doGamble.
Referenced by server::zone::objects::player::sessions::survey::SurveySession::tryGamble().
void SurveySessionImplementation::unlock (bool doLock = true) protected
Definition at line 354 of file SurveySession.cpp.
References _this.
void SurveySessionImplementation::wlock (bool doLock = true) protected
Definition at line 346 of file SurveySession.cpp.
References _this.
void SurveySessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 350 of file SurveySession.cpp.
References _this.
void SurveySessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 398 of file SurveySession.cpp.
References writeObjectMembers().
int SurveySessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 405 of file SurveySession.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class SurveySession friend
Definition at line 331 of file SurveySession.h.
Member Data Documentation
WeakReference<SurveySession*> server::zone::objects::player::sessions::survey::SurveySessionImplementation::_this
Definition at line 297 of file SurveySession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), startSession(), unlock(), and wlock().
ManagedWeakReference<SurveyTool* > server::zone::objects::player::sessions::survey::SurveySessionImplementation::activeSurveyTool protected
Definition at line 224 of file SurveySession.h.
Referenced by getActiveSurveyTool(), initializeSession(), rescheduleSample(), setActiveSurveyTool(), startSample(), startSession(), startSurvey(), surveyCnodeMinigame(), and surveyGnodeMinigame().
bool server::zone::objects::player::sessions::survey::SurveySessionImplementation::doGamble protected
Definition at line 232 of file SurveySession.h.
Referenced by clearGamble(), startSample(), surveyGnodeMinigame(), SurveySessionImplementation(), and tryGamble().
String server::zone::objects::player::sessions::survey::SurveySessionImplementation::lastResourceSampleName protected
Definition at line 234 of file SurveySession.h.
Referenced by reSample(), startSample(), and SurveySessionImplementation().
ManagedWeakReference<SurveyTool* > server::zone::objects::player::sessions::survey::SurveySessionImplementation::openSurveyTool protected
Definition at line 226 of file SurveySession.h.
Referenced by getOpenSurveyTool(), and setOpenSurveyTool().
ManagedWeakReference<ResourceManager* > server::zone::objects::player::sessions::survey::SurveySessionImplementation::resourceManager protected
Definition at line 228 of file SurveySession.h.
Referenced by startSample(), startSession(), startSurvey(), and surveyCnodeMinigame().
Reference<Coordinate* > server::zone::objects::player::sessions::survey::SurveySessionImplementation::richSampleLocation protected
Definition at line 230 of file SurveySession.h.
Referenced by clearRichSampleLocation(), getRichSampleLocation(), startSample(), surveyCnodeMinigame(), and SurveySessionImplementation().
Reference<Task* > server::zone::objects::player::sessions::survey::SurveySessionImplementation::sampleResultsTask protected
Definition at line 240 of file SurveySession.h.
Referenced by rescheduleSampleResults().
Reference<Task* > server::zone::objects::player::sessions::survey::SurveySessionImplementation::sampleTask protected
Definition at line 238 of file SurveySession.h.
Referenced by rescheduleSample().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sessions::survey::SurveySessionImplementation::surveyer protected
Definition at line 220 of file SurveySession.h.
Referenced by cancelSession(), initializeSession(), rescheduleSample(), rescheduleSampleResults(), rescheduleSurvey(), startSample(), startSession(), startSurvey(), surveyCnodeMinigame(), surveyCnodeMinigameSui(), surveyGnodeMinigame(), surveyGnodeMinigameSui(), and SurveySessionImplementation().
ManagedWeakReference<PlayerObject* > server::zone::objects::player::sessions::survey::SurveySessionImplementation::surveyerGhost protected
Definition at line 222 of file SurveySession.h.
Referenced by initializeSession(), startSample(), startSession(), and surveyCnodeMinigame().
Reference<Task* > server::zone::objects::player::sessions::survey::SurveySessionImplementation::surveyTask protected
Definition at line 236 of file SurveySession.h.
Referenced by rescheduleSurvey().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/survey/SurveySession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/survey/SurveySession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/survey/SurveySessionImplementation.cpp