Core3: PatrolPoint Class Reference
PatrolPoint Class Reference
#include <PatrolPoint.h>
Public Member Functions
PatrolPoint ()
PatrolPoint (const Vector3 &pos, SceneObject *cell=NULL)
PatrolPoint (float posX, float posZ, float posY, SceneObject *cell=NULL)
PatrolPoint (const PatrolPoint &point)
PatrolPoint & operator= (const PatrolPoint &p)
void addSerializableVariables ()
Vector3 getWorldPosition ()
bool isInRange (SceneObject *obj, float range)
bool isInRange (PatrolPoint *obj, float range)
WorldCoordinates getCoordinates ()
float getPositionX ()
float getPositionY ()
float getPositionZ ()
SceneObject * getCell ()
Time * getEstimatedTimeOfArrival ()
bool isReached ()
bool isPastTimeOfArrival ()
void setPosition (float x, float z, float y)
void setPositionX (float x)
void setPositionZ (float z)
void setPositionY (float y)
void setCell (SceneObject *cell)
void setReached (bool value)
void addEstimatedTimeOfArrival (uint32 mili)
Private Attributes
WorldCoordinates position
bool reached
Time estimatedTimeOfArrival
Detailed Description
Definition at line 54 of file PatrolPoint.h.
Constructor & Destructor Documentation
PatrolPoint::PatrolPoint () inline
Definition at line 62 of file PatrolPoint.h.
References addSerializableVariables(), and reached.
PatrolPoint::PatrolPoint (const Vector3 & pos, SceneObject * cell = NULL) inline
Definition at line 68 of file PatrolPoint.h.
References addSerializableVariables(), and reached.
PatrolPoint::PatrolPoint (float posX, float posZ, float posY, SceneObject * cell = NULL) inline
Definition at line 74 of file PatrolPoint.h.
References addSerializableVariables(), and reached.
PatrolPoint::PatrolPoint (const PatrolPoint & point) inline
Definition at line 80 of file PatrolPoint.h.
References addSerializableVariables(), position, and reached.
Member Function Documentation
void PatrolPoint::addEstimatedTimeOfArrival (uint32 mili) inline
Definition at line 182 of file PatrolPoint.h.
References estimatedTimeOfArrival.
void PatrolPoint::addSerializableVariables () inline
Definition at line 99 of file PatrolPoint.h.
References estimatedTimeOfArrival, position, and reached.
Referenced by PatrolPoint().
SceneObject* PatrolPoint::getCell () inline
Definition at line 140 of file PatrolPoint.h.
References WorldCoordinates::getCell(), and position.
Referenced by AiStateComponent::broadcastNextPositionUpdate(), server::zone::objects::creature::AiAgentImplementation::broadcastNextPositionUpdate(), FleeStateComponent::doMovement(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), RetreatStateComponent::onEnter(), SpawnStateComponent::onEnter(), server::zone::objects::creature::ai::AiActorImplementation::respawn(), server::zone::objects::creature::AiAgentImplementation::respawn(), AiStateComponent::updateCurrentPosition(), and server::zone::objects::creature::AiAgentImplementation::updateCurrentPosition().
WorldCoordinates PatrolPoint::getCoordinates () inline
Definition at line 123 of file PatrolPoint.h.
References position.
Referenced by AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), and WanderingStateComponent::onEnter().
Time* PatrolPoint::getEstimatedTimeOfArrival () inline
Definition at line 144 of file PatrolPoint.h.
References estimatedTimeOfArrival.
float PatrolPoint::getPositionX () inline
Definition at line 128 of file PatrolPoint.h.
References WorldCoordinates::getX(), and position.
Referenced by AiStateComponent::broadcastNextPositionUpdate(), server::zone::objects::creature::AiAgentImplementation::broadcastNextPositionUpdate(), FleeStateComponent::doMovement(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), FleeStateComponent::getFleeLocation(), RetreatStateComponent::onEnter(), SpawnStateComponent::onEnter(), server::zone::objects::creature::ai::AiActorImplementation::respawn(), server::zone::objects::creature::AiAgentImplementation::respawn(), server::zone::objects::creature::AiAgentImplementation::tryRetreat(), AiStateComponent::updateCurrentPosition(), and server::zone::objects::creature::AiAgentImplementation::updateCurrentPosition().
float PatrolPoint::getPositionY () inline
Definition at line 132 of file PatrolPoint.h.
References WorldCoordinates::getY(), and position.
Referenced by AiStateComponent::broadcastNextPositionUpdate(), server::zone::objects::creature::AiAgentImplementation::broadcastNextPositionUpdate(), FleeStateComponent::doMovement(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), FleeStateComponent::getFleeLocation(), RetreatStateComponent::onEnter(), SpawnStateComponent::onEnter(), server::zone::objects::creature::ai::AiActorImplementation::respawn(), server::zone::objects::creature::AiAgentImplementation::respawn(), server::zone::objects::creature::AiAgentImplementation::tryRetreat(), AiStateComponent::updateCurrentPosition(), and server::zone::objects::creature::AiAgentImplementation::updateCurrentPosition().
float PatrolPoint::getPositionZ () inline
Definition at line 136 of file PatrolPoint.h.
References WorldCoordinates::getZ(), and position.
Referenced by AiStateComponent::broadcastNextPositionUpdate(), server::zone::objects::creature::AiAgentImplementation::broadcastNextPositionUpdate(), FleeStateComponent::doMovement(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), RetreatStateComponent::onEnter(), SpawnStateComponent::onEnter(), server::zone::objects::creature::ai::AiActorImplementation::respawn(), server::zone::objects::creature::AiAgentImplementation::respawn(), server::zone::objects::creature::AiAgentImplementation::tryRetreat(), AiStateComponent::updateCurrentPosition(), and server::zone::objects::creature::AiAgentImplementation::updateCurrentPosition().
Vector3 PatrolPoint::getWorldPosition () inline
Definition at line 105 of file PatrolPoint.h.
References WorldCoordinates::getWorldPosition(), and position.
Referenced by server::zone::objects::creature::AiAgentImplementation::doMovement(), AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), and isInRange().
bool PatrolPoint::isInRange (SceneObject * obj, float range) inline
Definition at line 109 of file PatrolPoint.h.
References getWorldPosition(), and server::zone::objects::scene::SceneObject::getWorldPosition().
Referenced by server::zone::objects::creature::AiAgentImplementation::tryRetreat().
bool PatrolPoint::isInRange (PatrolPoint * obj, float range) inline
Definition at line 116 of file PatrolPoint.h.
References getWorldPosition().
bool PatrolPoint::isPastTimeOfArrival () inline
Definition at line 152 of file PatrolPoint.h.
References estimatedTimeOfArrival.
bool PatrolPoint::isReached () inline
Definition at line 148 of file PatrolPoint.h.
References reached.
Referenced by AiStateComponent::checkNewAngle(), and server::zone::objects::creature::AiAgentImplementation::checkNewAngle().
PatrolPoint& PatrolPoint::operator= (const PatrolPoint & p) inline
Definition at line 88 of file PatrolPoint.h.
References position, and reached.
void PatrolPoint::setCell (SceneObject * cell) inline
Definition at line 173 of file PatrolPoint.h.
References server::zone::objects::scene::SceneObject::isCellObject(), position, and WorldCoordinates::setCell().
Referenced by AiStateComponent::doMovement(), server::zone::objects::creature::AiAgentImplementation::doMovement(), FleeStateComponent::getFleeLocation(), and server::zone::objects::creature::AiAgentImplementation::respawn().
void PatrolPoint::setPosition (float x, float z, float y) inline
Definition at line 157 of file PatrolPoint.h.
References position, and WorldCoordinates::setCoordinates().
Referenced by AiStateComponent::doMovement(), server::zone::objects::creature::AiAgentImplementation::doMovement(), FleeStateComponent::getFleeLocation(), and server::zone::objects::creature::AiAgentImplementation::respawn().
void PatrolPoint::setPositionX (float x) inline
Definition at line 161 of file PatrolPoint.h.
References position, and WorldCoordinates::setX().
void PatrolPoint::setPositionY (float y) inline
Definition at line 169 of file PatrolPoint.h.
References position, and WorldCoordinates::setY().
void PatrolPoint::setPositionZ (float z) inline
Definition at line 165 of file PatrolPoint.h.
References position, and WorldCoordinates::setZ().
Referenced by server::zone::objects::creature::AiAgentImplementation::findNextPosition(), and FleeStateComponent::getFleeLocation().
void PatrolPoint::setReached (bool value) inline
Definition at line 178 of file PatrolPoint.h.
References reached.
Referenced by AiStateComponent::doMovement(), server::zone::objects::creature::AiAgentImplementation::doMovement(), RetreatStateComponent::onEnter(), and server::zone::objects::creature::AiAgentImplementation::tryRetreat().
Member Data Documentation
Time PatrolPoint::estimatedTimeOfArrival private
Definition at line 59 of file PatrolPoint.h.
Referenced by addEstimatedTimeOfArrival(), addSerializableVariables(), getEstimatedTimeOfArrival(), and isPastTimeOfArrival().
WorldCoordinates PatrolPoint::position private
Definition at line 55 of file PatrolPoint.h.
Referenced by addSerializableVariables(), getCell(), getCoordinates(), getPositionX(), getPositionY(), getPositionZ(), getWorldPosition(), operator=(), PatrolPoint(), setCell(), setPosition(), setPositionX(), setPositionY(), and setPositionZ().
bool PatrolPoint::reached private
Definition at line 57 of file PatrolPoint.h.
Referenced by addSerializableVariables(), isReached(), operator=(), PatrolPoint(), and setReached().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/PatrolPoint.h