Core3: server::zone::packets::chat::ChatInstantMessageToCharacter Class Reference
server::zone::packets::chat::ChatInstantMessageToCharacter Class Reference
#include <ChatInstantMessageToCharacter.h>
Public Member Functions
ChatInstantMessageToCharacter (ZoneClientSession *client, ZoneProcessServer *server)
void parse (Message *pack)
void run ()
String & getName ()
String & getGalaxy ()
String & getGame ()
UnicodeString & getMessage ()
int getSequence ()
Public Member Functions inherited from server::zone::packets::MessageCallback
MessageCallback (ZoneClientSession *client, ZoneProcessServer *server)
virtual ~MessageCallback ()
int getTaskQueue ()
bool parseMessage (Message *packet)
ZoneClientSession * getClient ()
ZoneProcessServer * getServer ()
Private Attributes
String game
String galaxy
String name
UnicodeString message
uint32 sequence
Additional Inherited Members
Protected Attributes inherited from server::zone::packets::MessageCallback
Reference< ZoneClientSession * > client
ManagedReference
< ZoneProcessServer * > server
int taskqueue
Detailed Description
Definition at line 61 of file ChatInstantMessageToCharacter.h.
Constructor & Destructor Documentation
server::zone::packets::chat::ChatInstantMessageToCharacter::ChatInstantMessageToCharacter (ZoneClientSession * client, ZoneProcessServer * server) inline
Definition at line 69 of file ChatInstantMessageToCharacter.h.
Member Function Documentation
String& server::zone::packets::chat::ChatInstantMessageToCharacter::getGalaxy () inline
Definition at line 98 of file ChatInstantMessageToCharacter.h.
References galaxy.
String& server::zone::packets::chat::ChatInstantMessageToCharacter::getGame () inline
Definition at line 102 of file ChatInstantMessageToCharacter.h.
References game.
UnicodeString& server::zone::packets::chat::ChatInstantMessageToCharacter::getMessage () inline
Definition at line 106 of file ChatInstantMessageToCharacter.h.
References message.
Referenced by server::chat::ChatManagerImplementation::handleChatInstantMessageToCharacter().
String& server::zone::packets::chat::ChatInstantMessageToCharacter::getName () inline
Definition at line 94 of file ChatInstantMessageToCharacter.h.
References name.
Referenced by server::chat::ChatManagerImplementation::handleChatInstantMessageToCharacter().
int server::zone::packets::chat::ChatInstantMessageToCharacter::getSequence () inline
Definition at line 110 of file ChatInstantMessageToCharacter.h.
References sequence.
Referenced by server::chat::ChatManagerImplementation::handleChatInstantMessageToCharacter().
void server::zone::packets::chat::ChatInstantMessageToCharacter::parse (Message * pack) inline virtual
Implements server::zone::packets::MessageCallback.
Definition at line 74 of file ChatInstantMessageToCharacter.h.
References galaxy, game, message, name, and sequence.
void server::zone::packets::chat::ChatInstantMessageToCharacter::run () inline
Definition at line 87 of file ChatInstantMessageToCharacter.h.
References server::zone::ZoneServer::getChatManager(), server::chat::ChatManager::handleChatInstantMessageToCharacter(), and server::zone::packets::MessageCallback::server.
Member Data Documentation
String server::zone::packets::chat::ChatInstantMessageToCharacter::galaxy private
Definition at line 63 of file ChatInstantMessageToCharacter.h.
Referenced by getGalaxy(), and parse().
String server::zone::packets::chat::ChatInstantMessageToCharacter::game private
Definition at line 62 of file ChatInstantMessageToCharacter.h.
Referenced by getGame(), and parse().
UnicodeString server::zone::packets::chat::ChatInstantMessageToCharacter::message private
Definition at line 65 of file ChatInstantMessageToCharacter.h.
Referenced by getMessage(), and parse().
String server::zone::packets::chat::ChatInstantMessageToCharacter::name private
Definition at line 64 of file ChatInstantMessageToCharacter.h.
Referenced by getName(), and parse().
uint32 server::zone::packets::chat::ChatInstantMessageToCharacter::sequence private
Definition at line 67 of file ChatInstantMessageToCharacter.h.
Referenced by getSequence(), and parse().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/chat/ChatInstantMessageToCharacter.h