Core3: server::zone::objects::area::SpawnObserverImplementation Class Reference
server::zone::objects::area::SpawnObserverImplementation Class Reference
#include <SpawnObserver.h>
Public Member Functions
SpawnObserverImplementation (SpawnArea *area)
SpawnObserverImplementation (DummyConstructorParameter *param)
virtual int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const SpawnObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< SpawnObserver * > _this
Protected Member Functions
virtual ~SpawnObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference< SpawnArea * > spawnArea
Friends
class SpawnObserver
Detailed Description
Definition at line 72 of file SpawnObserver.h.
Constructor & Destructor Documentation
SpawnObserverImplementation::SpawnObserverImplementation (SpawnArea * area)
Definition at line 192 of file SpawnObserver.cpp.
References _initializeImplementation(), and spawnArea.
SpawnObserverImplementation::SpawnObserverImplementation (DummyConstructorParameter * param)
Definition at line 66 of file SpawnObserver.cpp.
References _initializeImplementation().
SpawnObserverImplementation::~SpawnObserverImplementation () protected virtual
Definition at line 71 of file SpawnObserver.cpp.
Member Function Documentation
DistributedObjectStub * SpawnObserverImplementation::_getStub ()
Definition at line 91 of file SpawnObserver.cpp.
References _this.
void SpawnObserverImplementation::_initializeImplementation () protected
Definition at line 78 of file SpawnObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SpawnObserverImplementation().
void SpawnObserverImplementation::_serializationHelperMethod () protected
Definition at line 127 of file SpawnObserver.cpp.
Referenced by _initializeImplementation().
void SpawnObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 86 of file SpawnObserver.cpp.
References _this.
Referenced by server::zone::objects::area::SpawnObserver::SpawnObserver().
void SpawnObserverImplementation::finalize () protected
Definition at line 75 of file SpawnObserver.cpp.
void SpawnObserverImplementation::lock (bool doLock = true) protected
Definition at line 99 of file SpawnObserver.cpp.
References _this.
void SpawnObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 103 of file SpawnObserver.cpp.
References _this.
int SpawnObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2) virtual
Definition at line 200 of file SpawnObserver.cpp.
References spawnArea.
Referenced by server::zone::objects::area::SpawnObserver::notifyObserverEvent().
SpawnObserverImplementation::operator const SpawnObserver * ()
Definition at line 95 of file SpawnObserver.cpp.
void SpawnObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 134 of file SpawnObserver.cpp.
References readObjectMember().
bool SpawnObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 153 of file SpawnObserver.cpp.
References spawnArea.
Referenced by readObject().
void SpawnObserverImplementation::rlock (bool doLock = true) protected
Definition at line 107 of file SpawnObserver.cpp.
References _this.
void SpawnObserverImplementation::runlock (bool doLock = true) protected
Definition at line 123 of file SpawnObserver.cpp.
References _this.
void SpawnObserverImplementation::unlock (bool doLock = true) protected
Definition at line 119 of file SpawnObserver.cpp.
References _this.
void SpawnObserverImplementation::wlock (bool doLock = true) protected
Definition at line 111 of file SpawnObserver.cpp.
References _this.
void SpawnObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 115 of file SpawnObserver.cpp.
References _this.
void SpawnObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 167 of file SpawnObserver.cpp.
References writeObjectMembers().
int SpawnObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 174 of file SpawnObserver.cpp.
References spawnArea.
Referenced by writeObject().
Friends And Related Function Documentation
friend class SpawnObserver friend
Definition at line 117 of file SpawnObserver.h.
Member Data Documentation
WeakReference<SpawnObserver*> server::zone::objects::area::SpawnObserverImplementation::_this
Definition at line 83 of file SpawnObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<SpawnArea* > server::zone::objects::area::SpawnObserverImplementation::spawnArea protected
Definition at line 74 of file SpawnObserver.h.
Referenced by notifyObserverEvent(), readObjectMember(), SpawnObserverImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/SpawnObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/SpawnObserver.cpp