Core3: InstallMissionTerminalCommand Class Reference
InstallMissionTerminalCommand Class Reference
#include <InstallMissionTerminalCommand.h>
Public Member Functions
InstallMissionTerminalCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Detailed Description
Definition at line 52 of file InstallMissionTerminalCommand.h.
Constructor & Destructor Documentation
InstallMissionTerminalCommand::InstallMissionTerminalCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 55 of file InstallMissionTerminalCommand.h.
Member Function Documentation
int InstallMissionTerminalCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 60 of file InstallMissionTerminalCommand.h.
References server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::hasSkill(), SuiWindowType::INSTALL_MISSION_TERMINAL, and server::zone::objects::creature::CreatureObject::sendMessage().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/InstallMissionTerminalCommand.h