Core3: server::zone::objects::tangible::threat::ThreatMap Class Reference
server::zone::objects::tangible::threat::ThreatMap Class Reference
#include <ThreatMap.h>
Public Member Functions
ThreatMap (TangibleObject *me)
ThreatMap (const ThreatMap &map)
ThreatMap & operator= (const ThreatMap &map)
~ThreatMap ()
void removeAll ()
void removeObservers ()
void addDamage (CreatureObject *target, uint32 damage, String xp="")
void dropDamage (CreatureObject *target)
bool setThreatState (CreatureObject *target, uint64 state, uint64 duration=0, uint64 cooldown=0)
void clearThreatState (CreatureObject *target, uint64 state)
bool hasState (uint64 state)
bool isUniqueState (uint64 state)
CreatureObject * getHighestDamagePlayer ()
CreatureObject * getHighestDamageGroupLeader ()
CreatureObject * getHighestThreatCreature ()
uint32 getTotalDamage ()
void addAggro (CreatureObject *target, int value, uint64 duration=0)
void removeAggro (CreatureObject *target, int value)
void clearAggro (CreatureObject *target)
void addHeal (CreatureObject *target, int value)
Static Public Attributes
static const int EVALUATIONCOOLDOWN = 24000
Time between normal target evaluation.
Protected Attributes
ManagedWeakReference
< TangibleObject * > self
CooldownTimerMap cooldownTimerMap
ManagedWeakReference
< CreatureObject * > currentThreat
ThreatMatrix threatMatrix
ManagedReference
< ThreatMapObserver * > threatMapObserver
Mutex lockMutex
Private Member Functions
void registerObserver (CreatureObject *target)
Detailed Description
Definition at line 103 of file ThreatMap.h.
Constructor & Destructor Documentation
server::zone::objects::tangible::threat::ThreatMap::ThreatMap (TangibleObject * me) inline
Definition at line 117 of file ThreatMap.h.
server::zone::objects::tangible::threat::ThreatMap::ThreatMap (const ThreatMap & map) inline
Definition at line 123 of file ThreatMap.h.
References cooldownTimerMap, currentThreat, self, threatMapObserver, and threatMatrix.
server::zone::objects::tangible::threat::ThreatMap::~ThreatMap () inline
Definition at line 149 of file ThreatMap.h.
Member Function Documentation
void ThreatMap::addAggro (CreatureObject * target, int value, uint64 duration = 0)
Definition at line 342 of file ThreatMap.cpp.
References server::zone::objects::tangible::threat::ThreatMapEntry::addAggro(), lockMutex, and registerObserver().
void ThreatMap::addDamage (CreatureObject * target, uint32 damage, String xp = "")
Definition at line 82 of file ThreatMap.cpp.
References server::zone::objects::tangible::threat::ThreatMapEntry::addAggro(), server::zone::objects::tangible::threat::ThreatMapEntry::addDamage(), currentThreat, server::zone::objects::creature::CreatureObject::getWeapon(), server::zone::objects::tangible::weapon::WeaponObject::getXpType(), lockMutex, and registerObserver().
Referenced by DotPackCommand::doAreaMedicActionTarget(), DotPackCommand::doQueueCommand(), server::zone::objects::tangible::TangibleObjectImplementation::inflictDamage(), server::zone::objects::creature::AiAgentImplementation::inflictDamage(), and server::zone::objects::creature::CreatureObjectImplementation::inflictDamage().
void ThreatMap::addHeal (CreatureObject * target, int value)
Definition at line 386 of file ThreatMap.cpp.
References server::zone::objects::tangible::threat::ThreatMapEntry::addAggro(), server::zone::objects::tangible::threat::ThreatMapEntry::addHeal(), lockMutex, and registerObserver().
Referenced by server::zone::objects::tangible::threat::ThreatMapObserverImplementation::notifyObserverEvent().
void ThreatMap::clearAggro (CreatureObject * target)
Definition at line 375 of file ThreatMap.cpp.
References server::zone::objects::tangible::threat::ThreatMapEntry::clearAggro(), and lockMutex.
void ThreatMap::clearThreatState (CreatureObject * target, uint64 state)
Definition at line 193 of file ThreatMap.cpp.
References server::zone::objects::tangible::threat::ThreatMapEntry::clearThreatState(), server::zone::objects::scene::SceneObject::getObjectID(), and lockMutex.
Referenced by ClearThreatStateTask::run().
void ThreatMap::dropDamage (CreatureObject * target)
Definition at line 122 of file ThreatMap.cpp.
References currentThreat, ObserverEventType::HEALINGPERFORMED, lockMutex, and threatMapObserver.
Referenced by server::zone::objects::creature::AiAgentImplementation::removeDefender().
CreatureObject * ThreatMap::getHighestDamageGroupLeader ()
Definition at line 255 of file ThreatMap.cpp.
References server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::creature::CreatureObject::getGroupID(), server::zone::objects::group::GroupObject::getLeader(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::isGrouped(), and lockMutex.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction().
CreatureObject * ThreatMap::getHighestDamagePlayer ()
Definition at line 226 of file ThreatMap.cpp.
References server::zone::objects::creature::CreatureObject::isPlayerCreature(), and lockMutex.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction().
CreatureObject * ThreatMap::getHighestThreatCreature ()
Definition at line 315 of file ThreatMap.cpp.
References server::zone::objects::tangible::threat::ThreatMatrix::add(), server::zone::objects::tangible::threat::ThreatMatrix::clear(), cooldownTimerMap, currentThreat, EVALUATIONCOOLDOWN, server::zone::objects::tangible::threat::ThreatMatrix::getLargestThreat(), server::zone::objects::creature::CreatureObject::isAttackableBy(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::scene::SceneObject::isInRange(), CooldownTimerMap::isPast(), lockMutex, threatMatrix, and CooldownTimerMap::updateToCurrentAndAddMili().
Referenced by server::zone::objects::creature::AiAgentImplementation::doAttack(), AttackStateComponent::doRecovery(), and server::zone::objects::creature::AiAgentImplementation::removeDefender().
uint32 ThreatMap::getTotalDamage ()
Definition at line 208 of file ThreatMap.cpp.
References lockMutex.
Referenced by server::zone::managers::player::PlayerManagerImplementation::disseminateExperience().
bool ThreatMap::hasState (uint64 state)
Definition at line 177 of file ThreatMap.cpp.
References server::zone::objects::tangible::threat::ThreatMapEntry::hasState(), and lockMutex.
Referenced by setThreatState().
bool ThreatMap::isUniqueState (uint64 state)
Definition at line 189 of file ThreatMap.cpp.
References ThreatStates::UNIQUESTATE.
Referenced by setThreatState().
ThreatMap& server::zone::objects::tangible::threat::ThreatMap::operator= (const ThreatMap & map) inline
Definition at line 132 of file ThreatMap.h.
References cooldownTimerMap, currentThreat, self, threatMapObserver, and threatMatrix.
void ThreatMap::registerObserver (CreatureObject * target) private
Definition at line 51 of file ThreatMap.cpp.
References ObserverEventType::HEALINGPERFORMED, and threatMapObserver.
Referenced by addAggro(), addDamage(), addHeal(), and setThreatState().
void ThreatMap::removeAggro (CreatureObject * target, int value)
Definition at line 364 of file ThreatMap.cpp.
References lockMutex, and server::zone::objects::tangible::threat::ThreatMapEntry::removeAggro().
Referenced by RemoveAggroTask::run().
void ThreatMap::removeAll ()
Definition at line 113 of file ThreatMap.cpp.
References server::zone::objects::tangible::threat::ThreatMatrix::clear(), currentThreat, lockMutex, removeObservers(), and threatMatrix.
Referenced by server::zone::managers::player::PlayerManagerImplementation::disseminateExperience(), server::zone::managers::creature::LairObserverImplementation::notifyDestruction(), and server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction().
void ThreatMap::removeObservers ()
Definition at line 61 of file ThreatMap.cpp.
References threatMapObserver.
Referenced by server::zone::managers::creature::LairObserverImplementation::notifyDestruction(), server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction(), and removeAll().
bool ThreatMap::setThreatState (CreatureObject * target, uint64 state, uint64 duration = 0, uint64 cooldown = 0)
Definition at line 137 of file ThreatMap.cpp.
References cooldownTimerMap, server::zone::objects::scene::SceneObject::getObjectID(), hasState(), CooldownTimerMap::isPast(), isUniqueState(), lockMutex, registerObserver(), server::zone::objects::tangible::threat::ThreatMapEntry::setThreatState(), CooldownTimerMap::updateToCurrentAndAddMili(), and CooldownTimerMap::updateToCurrentTime().
Referenced by RescueCommand::doQueueCommand().
Member Data Documentation
CooldownTimerMap server::zone::objects::tangible::threat::ThreatMap::cooldownTimerMap protected
Definition at line 110 of file ThreatMap.h.
Referenced by getHighestThreatCreature(), operator=(), setThreatState(), and ThreatMap().
ManagedWeakReference<CreatureObject*> server::zone::objects::tangible::threat::ThreatMap::currentThreat protected
Definition at line 111 of file ThreatMap.h.
Referenced by addDamage(), dropDamage(), getHighestThreatCreature(), operator=(), removeAll(), and ThreatMap().
const int server::zone::objects::tangible::threat::ThreatMap::EVALUATIONCOOLDOWN = 24000 static
Time between normal target evaluation.
Definition at line 106 of file ThreatMap.h.
Referenced by getHighestThreatCreature().
Mutex server::zone::objects::tangible::threat::ThreatMap::lockMutex protected
Definition at line 114 of file ThreatMap.h.
Referenced by addAggro(), addDamage(), addHeal(), clearAggro(), clearThreatState(), dropDamage(), getHighestDamageGroupLeader(), getHighestDamagePlayer(), getHighestThreatCreature(), getTotalDamage(), hasState(), removeAggro(), removeAll(), and setThreatState().
ManagedWeakReference<TangibleObject*> server::zone::objects::tangible::threat::ThreatMap::self protected
Definition at line 109 of file ThreatMap.h.
Referenced by operator=(), and ThreatMap().
ManagedReference<ThreatMapObserver*> server::zone::objects::tangible::threat::ThreatMap::threatMapObserver protected
Definition at line 113 of file ThreatMap.h.
Referenced by dropDamage(), operator=(), registerObserver(), removeObservers(), and ThreatMap().
ThreatMatrix server::zone::objects::tangible::threat::ThreatMap::threatMatrix protected
Definition at line 112 of file ThreatMap.h.
Referenced by getHighestThreatCreature(), operator=(), removeAll(), and ThreatMap().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/threat/ThreatMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/threat/ThreatMap.cpp