Core3: server::zone::manager::ZoneManagerImplementation Class Reference
server::zone::manager::ZoneManagerImplementation Class Reference
#include <ZoneManager.h>
Public Member Functions
ZoneManagerImplementation (const String &name)
ZoneManagerImplementation (DummyConstructorParameter *param)
void setZoneProcessor (ZoneProcessServer *server)
operator const ZoneManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< ZoneManager * > _this
Protected Member Functions
virtual ~ZoneManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference< ZoneServer * > zoneServer
ManagedReference
< ZoneProcessServer * > zoneProcessor
Reference< ObjectManager * > objectManager
Friends
class ZoneManager
Detailed Description
Definition at line 85 of file ZoneManager.h.
Constructor & Destructor Documentation
ZoneManagerImplementation::ZoneManagerImplementation (const String & name)
Definition at line 181 of file ZoneManager.cpp.
References _initializeImplementation(), objectManager, zoneProcessor, and zoneServer.
ZoneManagerImplementation::ZoneManagerImplementation (DummyConstructorParameter * param)
Definition at line 67 of file ZoneManager.cpp.
References _initializeImplementation().
ZoneManagerImplementation::~ZoneManagerImplementation () protected virtual
Definition at line 72 of file ZoneManager.cpp.
Member Function Documentation
DistributedObjectStub * ZoneManagerImplementation::_getStub ()
Definition at line 92 of file ZoneManager.cpp.
References _this.
void ZoneManagerImplementation::_initializeImplementation () protected
Definition at line 79 of file ZoneManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ZoneManagerImplementation().
void ZoneManagerImplementation::_serializationHelperMethod () protected
Definition at line 128 of file ZoneManager.cpp.
Referenced by _initializeImplementation().
void ZoneManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 87 of file ZoneManager.cpp.
References _this.
Referenced by server::zone::manager::ZoneManager::ZoneManager().
void ZoneManagerImplementation::finalize () protected
Definition at line 76 of file ZoneManager.cpp.
void ZoneManagerImplementation::lock (bool doLock = true) protected
Definition at line 100 of file ZoneManager.cpp.
References _this.
void ZoneManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 104 of file ZoneManager.cpp.
References _this.
ZoneManagerImplementation::operator const ZoneManager * ()
Definition at line 96 of file ZoneManager.cpp.
void ZoneManagerImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented in server::zone::managers::creature::CreatureManagerImplementation, and server::zone::managers::crafting::CraftingManagerImplementation.
Definition at line 135 of file ZoneManager.cpp.
References readObjectMember().
bool ZoneManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 154 of file ZoneManager.cpp.
Referenced by readObject().
void ZoneManagerImplementation::rlock (bool doLock = true) protected
Definition at line 108 of file ZoneManager.cpp.
References _this.
void ZoneManagerImplementation::runlock (bool doLock = true) protected
Definition at line 124 of file ZoneManager.cpp.
References _this.
void ZoneManagerImplementation::setZoneProcessor (ZoneProcessServer * server)
Definition at line 197 of file ZoneManager.cpp.
References server::zone::ZoneProcessServer::getZoneServer(), objectManager, zoneProcessor, and zoneServer.
Referenced by server::zone::manager::ZoneManager::setZoneProcessor().
void ZoneManagerImplementation::unlock (bool doLock = true) protected
Definition at line 120 of file ZoneManager.cpp.
References _this.
void ZoneManagerImplementation::wlock (bool doLock = true) protected
Definition at line 112 of file ZoneManager.cpp.
References _this.
void ZoneManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 116 of file ZoneManager.cpp.
References _this.
void ZoneManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented in server::zone::managers::creature::CreatureManagerImplementation, and server::zone::managers::crafting::CraftingManagerImplementation.
Definition at line 164 of file ZoneManager.cpp.
References writeObjectMembers().
int ZoneManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 171 of file ZoneManager.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ZoneManager friend
Definition at line 134 of file ZoneManager.h.
Member Data Documentation
WeakReference<ZoneManager*> server::zone::manager::ZoneManagerImplementation::_this
Definition at line 100 of file ZoneManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
Reference<ObjectManager* > server::zone::manager::ZoneManagerImplementation::objectManager protected
Definition at line 91 of file ZoneManager.h.
Referenced by setZoneProcessor(), and ZoneManagerImplementation().
ManagedReference<ZoneProcessServer* > server::zone::manager::ZoneManagerImplementation::zoneProcessor protected
Definition at line 89 of file ZoneManager.h.
Referenced by setZoneProcessor(), and ZoneManagerImplementation().
ManagedReference<ZoneServer* > server::zone::manager::ZoneManagerImplementation::zoneServer protected
Definition at line 87 of file ZoneManager.h.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), server::zone::managers::crafting::CraftingManagerImplementation::configureLabratories(), server::zone::managers::creature::CreatureManagerImplementation::createCreature(), server::zone::managers::creature::CreatureManagerImplementation::createCreatureChildrenObjects(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), server::zone::managers::crafting::CraftingManagerImplementation::initialize(), server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction(), server::zone::managers::creature::CreatureManagerImplementation::placeCreature(), setZoneProcessor(), server::zone::managers::creature::CreatureManagerImplementation::spawnCreatureWithAi(), server::zone::managers::creature::CreatureManagerImplementation::spawnLair(), and ZoneManagerImplementation().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/ZoneManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/ZoneManager.cpp