Core3: server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask Class Reference
server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask Class Reference
#include <BountyHunterTargetTask.h>
Public Member Functions
BountyHunterTargetTask (MissionObject *mission, CreatureObject *player, const String &zoneName)
~BountyHunterTargetTask ()
void run ()
Vector3 getTargetPosition ()
String getTargetZoneName ()
Private Member Functions
void updatePosition (CreatureObject *player)
void updateToSpawnableTargetPosition ()
bool canSpawnTargetAt (const Vector3 &position)
Private Attributes
ManagedWeakReference
< MissionObject * > mission
ManagedWeakReference
< BountyMissionObjective * > objective
ManagedWeakReference
< CreatureObject * > player
Vector3 nextPosition
Vector3 currentPosition
bool move
String zoneName
Detailed Description
Definition at line 61 of file BountyHunterTargetTask.h.
Constructor & Destructor Documentation
server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::BountyHunterTargetTask (MissionObject * mission, CreatureObject * player, const String & zoneName) inline
Definition at line 72 of file BountyHunterTargetTask.h.
References currentPosition, server::zone::objects::mission::MissionObject::getEndPositionX(), server::zone::objects::mission::MissionObject::getEndPositionY(), server::zone::objects::mission::MissionObject::getMissionLevel(), server::zone::ZoneServer::getMissionManager(), server::zone::objects::mission::MissionObject::getMissionObjective(), server::zone::managers::mission::MissionManager::getRandomBountyTargetPosition(), server::zone::objects::scene::SceneObject::getZoneServer(), mission, move, nextPosition, objective, player, and zoneName.
server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::~BountyHunterTargetTask () inline
Definition at line 93 of file BountyHunterTargetTask.h.
Member Function Documentation
bool server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::canSpawnTargetAt (const Vector3 & position) inline private
Definition at line 198 of file BountyHunterTargetTask.h.
References server::zone::Zone::getPlanetManager(), server::zone::objects::scene::SceneObject::getZone(), server::zone::managers::planet::PlanetManager::isBuildingPermittedAt(), server::zone::managers::planet::PlanetManager::isInWater(), server::zone::Zone::isWithinBoundaries(), and player.
Referenced by updateToSpawnableTargetPosition().
Vector3 server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::getTargetPosition () inline
Definition at line 142 of file BountyHunterTargetTask.h.
References currentPosition.
String server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::getTargetZoneName () inline
Definition at line 146 of file BountyHunterTargetTask.h.
References zoneName.
void server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::run () inline
Definition at line 98 of file BountyHunterTargetTask.h.
References currentPosition, server::zone::objects::scene::SceneObject::getWorldPosition(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), move, objective, player, updatePosition(), updateToSpawnableTargetPosition(), and zoneName.
void server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::updatePosition (CreatureObject * player) inline private
Definition at line 151 of file BountyHunterTargetTask.h.
References currentPosition, server::zone::ZoneServer::getMissionManager(), server::zone::managers::mission::MissionManager::getRandomBountyTargetPosition(), server::zone::objects::scene::SceneObject::getZoneServer(), and nextPosition.
Referenced by run().
void server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::updateToSpawnableTargetPosition () inline private
Definition at line 165 of file BountyHunterTargetTask.h.
References canSpawnTargetAt(), and currentPosition.
Referenced by run().
Member Data Documentation
Vector3 server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::currentPosition private
Definition at line 67 of file BountyHunterTargetTask.h.
Referenced by BountyHunterTargetTask(), getTargetPosition(), run(), updatePosition(), and updateToSpawnableTargetPosition().
ManagedWeakReference<MissionObject*> server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::mission private
Definition at line 62 of file BountyHunterTargetTask.h.
Referenced by BountyHunterTargetTask().
bool server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::move private
Definition at line 68 of file BountyHunterTargetTask.h.
Referenced by BountyHunterTargetTask(), and run().
Vector3 server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::nextPosition private
Definition at line 66 of file BountyHunterTargetTask.h.
Referenced by BountyHunterTargetTask(), and updatePosition().
ManagedWeakReference<BountyMissionObjective*> server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::objective private
Definition at line 63 of file BountyHunterTargetTask.h.
Referenced by BountyHunterTargetTask(), and run().
ManagedWeakReference<CreatureObject*> server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::player private
Definition at line 64 of file BountyHunterTargetTask.h.
Referenced by BountyHunterTargetTask(), canSpawnTargetAt(), and run().
String server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::zoneName private
Definition at line 69 of file BountyHunterTargetTask.h.
Referenced by BountyHunterTargetTask(), getTargetZoneName(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/bountyhunter/events/BountyHunterTargetTask.h