Core3: server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation Class Reference
server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation Class Reference
#include <SuiBankTransferBox.h>
Public Member Functions
SuiBankTransferBoxImplementation (SceneObject *bankObject, CreatureObject *player, unsigned int windowtype)
SuiBankTransferBoxImplementation (DummyConstructorParameter *param)
void addCash (int cash)
void addBank (int bank)
SceneObject * getBank ()
BaseMessage * generateMessage ()
bool isBankTransferBox ()
operator const SuiBankTransferBox * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
SuiBoxImplementation (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
SuiBoxImplementation (DummyConstructorParameter *param)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
virtual bool isInputBox ()
virtual bool isListBox ()
virtual bool isMessageBox ()
virtual bool isTransferBox ()
virtual bool isSlicingBox ()
virtual bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
operator const SuiBox * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< SuiBankTransferBox * > _this
Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
WeakReference< SuiBox * > _this
Protected Member Functions
virtual ~SuiBankTransferBoxImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
virtual ~SuiBoxImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
String lblFrom
String lblStartingFrom
String lblInputFrom
String lblTo
String lblStartingTo
String lblInputTo
String convertRatioFrom
String convertRatioTo
ManagedReference< SceneObject * > bank
Protected Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
ManagedWeakReference
< CreatureObject * > player
Reference< SuiCallback * > suiCallback
unsigned int boxID
ManagedWeakReference
< SceneObject * > usingObject
String handlerStr
String cancelButtonText
bool cancelButton
String okButtonText
bool okButton
String otherButtonText
bool otherButton
String promptTitle
String promptText
int boxType
unsigned int windowType
float forceCloseDistance
Vector< String > headerSets
Vector< String > optionSets
int hdrOptCount
bool hasGenerated
Friends
class SuiBankTransferBox
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Detailed Description
Definition at line 118 of file SuiBankTransferBox.h.
Constructor & Destructor Documentation
SuiBankTransferBoxImplementation::SuiBankTransferBoxImplementation (SceneObject * bankObject, CreatureObject * player, unsigned int windowtype)
Definition at line 342 of file SuiBankTransferBox.cpp.
References _initializeImplementation(), and bank.
SuiBankTransferBoxImplementation::SuiBankTransferBoxImplementation (DummyConstructorParameter * param)
Definition at line 120 of file SuiBankTransferBox.cpp.
References _initializeImplementation().
SuiBankTransferBoxImplementation::~SuiBankTransferBoxImplementation () protected virtual
Definition at line 125 of file SuiBankTransferBox.cpp.
Member Function Documentation
DistributedObjectStub * SuiBankTransferBoxImplementation::_getStub ()
Definition at line 145 of file SuiBankTransferBox.cpp.
References _this.
void SuiBankTransferBoxImplementation::_initializeImplementation () protected
Definition at line 132 of file SuiBankTransferBox.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SuiBankTransferBoxImplementation().
void SuiBankTransferBoxImplementation::_serializationHelperMethod () protected
Definition at line 181 of file SuiBankTransferBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void SuiBankTransferBoxImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 140 of file SuiBankTransferBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_setStub(), and _this.
Referenced by server::zone::objects::player::sui::banktransferbox::SuiBankTransferBox::SuiBankTransferBox().
void SuiBankTransferBoxImplementation::addBank (int bank)
Definition at line 359 of file SuiBankTransferBox.cpp.
References convertRatioTo, lblInputTo, lblStartingTo, and lblTo.
Referenced by server::zone::objects::player::sui::banktransferbox::SuiBankTransferBox::addBank().
void SuiBankTransferBoxImplementation::addCash (int cash)
Definition at line 348 of file SuiBankTransferBox.cpp.
References convertRatioFrom, lblFrom, lblInputFrom, and lblStartingFrom.
Referenced by server::zone::objects::player::sui::banktransferbox::SuiBankTransferBox::addCash().
void SuiBankTransferBoxImplementation::finalize () protected
Definition at line 129 of file SuiBankTransferBox.cpp.
BaseMessage * SuiBankTransferBoxImplementation::generateMessage () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 11 of file SuiBankTransferBoxImplementation.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::addHeader(), server::zone::objects::player::sui::SuiBoxImplementation::addSetting(), server::zone::objects::player::sui::SuiBoxImplementation::boxID, convertRatioFrom, convertRatioTo, server::zone::objects::player::sui::SuiBoxImplementation::generateBody(), server::zone::objects::player::sui::SuiBoxImplementation::generateFooter(), server::zone::objects::player::sui::SuiBoxImplementation::generateHeader(), server::zone::objects::player::sui::SuiBoxImplementation::hasGenerated, lblFrom, lblInputFrom, lblInputTo, lblStartingFrom, lblStartingTo, lblTo, server::zone::objects::player::sui::SuiBoxImplementation::promptText, server::zone::objects::player::sui::SuiBoxImplementation::promptTitle, and server::zone::objects::player::sui::SuiBoxImplementation::setHandlerText().
Referenced by server::zone::objects::player::sui::banktransferbox::SuiBankTransferBox::generateMessage().
SceneObject * SuiBankTransferBoxImplementation::getBank ()
Definition at line 370 of file SuiBankTransferBox.cpp.
References bank.
Referenced by server::zone::objects::player::sui::banktransferbox::SuiBankTransferBox::getBank().
bool SuiBankTransferBoxImplementation::isBankTransferBox () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 375 of file SuiBankTransferBox.cpp.
Referenced by server::zone::objects::player::sui::banktransferbox::SuiBankTransferBox::isBankTransferBox().
void SuiBankTransferBoxImplementation::lock (bool doLock = true) protected
Definition at line 153 of file SuiBankTransferBox.cpp.
References _this.
void SuiBankTransferBoxImplementation::lock (ManagedObject * obj) protected
Definition at line 157 of file SuiBankTransferBox.cpp.
References _this.
SuiBankTransferBoxImplementation::operator const SuiBankTransferBox * ()
Definition at line 149 of file SuiBankTransferBox.cpp.
void SuiBankTransferBoxImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 188 of file SuiBankTransferBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::initializeTransientMembers(), and readObjectMember().
bool SuiBankTransferBoxImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 207 of file SuiBankTransferBox.cpp.
References bank, convertRatioFrom, convertRatioTo, lblFrom, lblInputFrom, lblInputTo, lblStartingFrom, lblStartingTo, lblTo, and server::zone::objects::player::sui::SuiBoxImplementation::readObjectMember().
Referenced by readObject().
void SuiBankTransferBoxImplementation::rlock (bool doLock = true) protected
Definition at line 161 of file SuiBankTransferBox.cpp.
References _this.
void SuiBankTransferBoxImplementation::runlock (bool doLock = true) protected
Definition at line 177 of file SuiBankTransferBox.cpp.
References _this.
void SuiBankTransferBoxImplementation::unlock (bool doLock = true) protected
Definition at line 173 of file SuiBankTransferBox.cpp.
References _this.
void SuiBankTransferBoxImplementation::wlock (bool doLock = true) protected
Definition at line 165 of file SuiBankTransferBox.cpp.
References _this.
void SuiBankTransferBoxImplementation::wlock (ManagedObject * obj) protected
Definition at line 169 of file SuiBankTransferBox.cpp.
References _this.
void SuiBankTransferBoxImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 253 of file SuiBankTransferBox.cpp.
References writeObjectMembers().
int SuiBankTransferBoxImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 260 of file SuiBankTransferBox.cpp.
References bank, convertRatioFrom, convertRatioTo, lblFrom, lblInputFrom, lblInputTo, lblStartingFrom, lblStartingTo, lblTo, and server::zone::objects::player::sui::SuiBoxImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class SuiBankTransferBox friend
Definition at line 187 of file SuiBankTransferBox.h.
Member Data Documentation
WeakReference<SuiBankTransferBox*> server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::_this
Definition at line 153 of file SuiBankTransferBox.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedReference<SceneObject* > server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::bank protected
Definition at line 136 of file SuiBankTransferBox.h.
Referenced by getBank(), readObjectMember(), SuiBankTransferBoxImplementation(), and writeObjectMembers().
String server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::convertRatioFrom protected
Definition at line 132 of file SuiBankTransferBox.h.
Referenced by addCash(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::convertRatioTo protected
Definition at line 134 of file SuiBankTransferBox.h.
Referenced by addBank(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::lblFrom protected
Definition at line 120 of file SuiBankTransferBox.h.
Referenced by addCash(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::lblInputFrom protected
Definition at line 124 of file SuiBankTransferBox.h.
Referenced by addCash(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::lblInputTo protected
Definition at line 130 of file SuiBankTransferBox.h.
Referenced by addBank(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::lblStartingFrom protected
Definition at line 122 of file SuiBankTransferBox.h.
Referenced by addCash(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::lblStartingTo protected
Definition at line 128 of file SuiBankTransferBox.h.
Referenced by addBank(), generateMessage(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::lblTo protected
Definition at line 126 of file SuiBankTransferBox.h.
Referenced by addBank(), generateMessage(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/banktransferbox/SuiBankTransferBox.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/banktransferbox/SuiBankTransferBoxImplementation.cpp