Core3: ForceAbsorb2Command Class Reference
ForceAbsorb2Command Class Reference
#include <ForceAbsorb2Command.h>
Public Member Functions
ForceAbsorb2Command (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Detailed Description
Definition at line 51 of file ForceAbsorb2Command.h.
Constructor & Destructor Documentation
ForceAbsorb2Command::ForceAbsorb2Command (const String & name, ZoneProcessServer * server) inline
Definition at line 54 of file ForceAbsorb2Command.h.
Member Function Documentation
int ForceAbsorb2Command::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 59 of file ForceAbsorb2Command.h.
References server::zone::objects::creature::CreatureObject::addBuff(), ObserverEventType::FORCEBUFFHIT, server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::hasBuff(), BuffType::JEDI, BuffCRC::JEDI_FORCE_ABSORB_1, BuffCRC::JEDI_FORCE_ABSORB_2, server::zone::objects::creature::CreatureObject::playEffect(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
void ForceAbsorb2Command::handleBuff (SceneObject * creature, ManagedObject * object, int64 param) inline
Definition at line 117 of file ForceAbsorb2Command.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/ForceAbsorb2Command.h