Core3: HealHealthWoundSelf2Command Class Reference
HealHealthWoundSelf2Command Class Reference
#include <HealHealthWoundSelf2Command.h>
Public Member Functions
HealHealthWoundSelf2Command (const String &name, ZoneProcessServer *server)
bool canPerformSkill (CreatureObject *creature)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file HealHealthWoundSelf2Command.h.
Constructor & Destructor Documentation
HealHealthWoundSelf2Command::HealHealthWoundSelf2Command (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file HealHealthWoundSelf2Command.h.
Member Function Documentation
bool HealHealthWoundSelf2Command::canPerformSkill (CreatureObject * creature) inline
Definition at line 58 of file HealHealthWoundSelf2Command.h.
References CreatureAttribute::CONSTITUTION, server::zone::objects::creature::CreatureObject::getWounds(), CreatureAttribute::HEALTH, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and CreatureAttribute::STRENGTH.
Referenced by doQueueCommand().
int HealHealthWoundSelf2Command::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 67 of file HealHealthWoundSelf2Command.h.
References canPerformSkill(), CreatureAttribute::CONSTITUTION, server::zone::objects::creature::CreatureObject::getPlayerObject(), CreatureAttribute::HEALTH, server::zone::objects::creature::CreatureObject::healWound(), server::zone::objects::creature::CreatureObject::playEffect(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and CreatureAttribute::STRENGTH.
float HealHealthWoundSelf2Command::getCommandDuration (CreatureObject * object, const UnicodeString & arguments) inline
Definition at line 144 of file HealHealthWoundSelf2Command.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/HealHealthWoundSelf2Command.h