Core3: server::zone::managers::crafting::labratories::ResourceLabratory Class Reference
server::zone::managers::crafting::labratories::ResourceLabratory Class Reference
#include <ResourceLabratory.h>
Public Member Functions
ResourceLabratory ()
virtual ~ResourceLabratory ()
void setInitialCraftingValues (TangibleObject *prototype, ManufactureSchematic *manufactureSchematic, int assemblySuccess)
void experimentRow (CraftingValues *craftingValues, int rowEffected, int pointsAttempted, float failure, int experimentationResult)
void initialize (ZoneServer *server)
bool allowFactoryRun (ManufactureSchematic *manufactureSchematic)
Public Member Functions inherited from server::zone::managers::crafting::labratories::SharedLabratory
SharedLabratory ()
virtual ~SharedLabratory ()
virtual float getWeightedValue (ManufactureSchematic *manufactureSchematic, int type)
Protected Member Functions
bool applyComponentStats (TangibleObject *prototype, ManufactureSchematic *manufactureSchematic)
String checkBioSkillMods (const String &property)
Protected Member Functions inherited from server::zone::managers::crafting::labratories::SharedLabratory
float calculateExperimentationValueModifier (int experimentationResult, int pointsAttempted)
float calculateAssemblyValueModifier (int assemblyResult)
float getAssemblyPercentage (float value)
Protected Attributes
SortedVector< String > bioMods
Protected Attributes inherited from server::zone::managers::crafting::labratories::SharedLabratory
ManagedReference< ZoneServer * > zoneServer
Detailed Description
Definition at line 18 of file ResourceLabratory.h.
Constructor & Destructor Documentation
ResourceLabratory::ResourceLabratory ()
Definition at line 10 of file ResourceLabratory.cpp.
ResourceLabratory::~ResourceLabratory () virtual
Definition at line 14 of file ResourceLabratory.cpp.
Member Function Documentation
bool ResourceLabratory::allowFactoryRun (ManufactureSchematic * manufactureSchematic) virtual
Reimplemented from server::zone::managers::crafting::labratories::SharedLabratory.
Definition at line 17 of file ResourceLabratory.cpp.
References server::zone::objects::manufactureschematic::ManufactureSchematic::allowFactoryRun().
bool ResourceLabratory::applyComponentStats (TangibleObject * prototype, ManufactureSchematic * manufactureSchematic) protected
Definition at line 125 of file ResourceLabratory.cpp.
References server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::addExperimentalProperty(), server::zone::objects::tangible::wearables::WearableObject::addSkillMod(), server::zone::managers::crafting::CraftingManager::BITSETCOMBINE, checkBioSkillMods(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCombineType(), server::zone::objects::manufactureschematic::ManufactureSchematic::getCraftingValues(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentValue(), server::zone::objects::manufactureschematic::ManufactureSchematic::getDraftSchematic(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMinValue(), ComponentSlot::getPrototype(), server::zone::objects::manufactureschematic::ManufactureSchematic::getSlot(), server::zone::objects::manufactureschematic::ManufactureSchematic::getSlotCount(), server::zone::objects::tangible::wearables::WearableObject::getWearableSkillMods(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::hasProperty(), server::zone::objects::scene::SceneObject::isArmorObject(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::isHidden(), server::zone::objects::scene::SceneObject::isWearableObject(), server::zone::managers::crafting::CraftingManager::LINEARCOMBINE, server::zone::managers::crafting::CraftingManager::OVERRIDECOMBINE, server::zone::managers::crafting::CraftingManager::PERCENTAGECOMBINE, server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxValue(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMinValue().
Referenced by setInitialCraftingValues().
String ResourceLabratory::checkBioSkillMods (const String & property) protected
Definition at line 257 of file ResourceLabratory.cpp.
References bioMods.
Referenced by applyComponentStats().
void ResourceLabratory::experimentRow (CraftingValues * craftingValues, int rowEffected, int pointsAttempted, float failure, int experimentationResult) virtual
Implements server::zone::managers::crafting::labratories::SharedLabratory.
Definition at line 103 of file ResourceLabratory.cpp.
References server::zone::managers::crafting::labratories::SharedLabratory::calculateExperimentationValueModifier(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitleSize(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitlesTitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getVisibleExperimentalPropertyTitle(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage().
void ResourceLabratory::initialize (ZoneServer * server) virtual
Reimplemented from server::zone::managers::crafting::labratories::SharedLabratory.
Definition at line 22 of file ResourceLabratory.cpp.
References bioMods, and server::zone::managers::crafting::labratories::SharedLabratory::initialize().
Referenced by server::zone::managers::crafting::CraftingManagerImplementation::configureLabratories().
void ResourceLabratory::setInitialCraftingValues (TangibleObject * prototype, ManufactureSchematic * manufactureSchematic, int assemblySuccess) virtual
Implements server::zone::managers::crafting::labratories::SharedLabratory.
Definition at line 39 of file ResourceLabratory.cpp.
References server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::addExperimentalProperty(), applyComponentStats(), server::zone::managers::crafting::labratories::SharedLabratory::calculateAssemblyValueModifier(), server::zone::managers::crafting::labratories::SharedLabratory::getAssemblyPercentage(), server::zone::objects::manufactureschematic::ManufactureSchematic::getComplexity(), server::zone::objects::manufactureschematic::ManufactureSchematic::getCraftingValues(), server::zone::objects::manufactureschematic::ManufactureSchematic::getDraftSchematic(), server::zone::managers::crafting::labratories::SharedLabratory::getWeightedValue(), server::zone::managers::crafting::CraftingManager::OVERRIDECOMBINE, server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::recalculateValues(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxPercentage().
Member Data Documentation
SortedVector<String> server::zone::managers::crafting::labratories::ResourceLabratory::bioMods protected
Definition at line 27 of file ResourceLabratory.h.
Referenced by checkBioSkillMods(), and initialize().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/labratories/ResourceLabratory.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/labratories/ResourceLabratory.cpp