Core3: CollisionManager Class Reference
CollisionManager Class Reference
#include <CollisionManager.h>
Static Public Member Functions
static TriangleNode * getTriangle (const Vector3 &point, FloorMesh *floor)
static PathNode * findNearestPathNode (TriangleNode *triangle, FloorMesh *floor, const Vector3 &finalTarget)
static bool checkLineOfSightInBuilding (SceneObject *object1, SceneObject *object2, SceneObject *building)
static bool checkLineOfSight (SceneObject *object1, SceneObject *object2)
static bool checkLineOfSightWorldToCell (const Vector3 &rayOrigin, const Vector3 &rayEnd, float distance, CellObject *cell)
static bool checkMovementCollision (CreatureObject *creature, float x, float z, float y, Zone *zone)
static float getRayOriginPoint (CreatureObject *creature)
static float getWorldFloorCollision (float x, float y, Zone *zone, bool testWater)
static void getWorldFloorCollisions (float x, float y, Zone *zone, bool testWater, SortedVector< IntersectionResult > *result, CloseObjectsVector *closeObjectsVector=NULL)
static Vector< float > * getCellFloorCollision (float x, float y, CellObject *cellObject)
static bool checkShipCollision (ShipObject *ship, const Vector3 &targetPosition, Vector3 &collisionPoint)
static bool checkSphereCollision (const Vector3 &sphereOrigin, float radius, Zone *zone)
static bool checkLineOfSightInParentCell (SceneObject *object, Vector3 &endPoint)
Static Protected Member Functions
static AABBTree * getAABBTree (SceneObject *scno, int collisionBlockFlags)
static Ray convertToModelSpace (const Vector3 &rayOrigin, const Vector3 &rayEnd, SceneObject *model)
static Vector3 convertToModelSpace (const Vector3 &point, SceneObject *model)
static Reference< Matrix4 * > getTransformMatrix (SceneObject *model)
Detailed Description
Definition at line 46 of file CollisionManager.h.
Member Function Documentation
bool CollisionManager::checkLineOfSight (SceneObject * object1, SceneObject * object2) static
Definition at line 421 of file CollisionManager.cpp.
References checkLineOfSightInBuilding(), checkLineOfSightWorldToCell(), convertToModelSpace(), getAABBTree(), server::zone::Zone::getInRangeObjects(), server::zone::objects::scene::SceneObject::getParent(), getRayOriginPoint(), server::zone::objects::scene::SceneObject::getRootParent(), server::zone::objects::scene::SceneObject::getWorldPosition(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isAiAgent(), and server::zone::objects::scene::SceneObject::isCreatureObject().
Referenced by FirstAidCommand::canPerformSkill(), StopBleedingCommand::canPerformSkill(), ForceCureDiseaseCommand::canPerformSkill(), ForceCurePoisonCommand::canPerformSkill(), HealStatesOtherCommand::canPerformSkill(), HealEnhanceCommand::canPerformSkill(), HealWoundCommand::canPerformSkill(), HealAllOther1Command::canPerformSkill(), HealAllOther2Command::canPerformSkill(), HealMindWoundOther1Command::canPerformSkill(), HealMindWoundOther2Command::canPerformSkill(), HealActionWoundOther2Command::canPerformSkill(), HealActionWoundOther1Command::canPerformSkill(), HealHealthWoundOther1Command::canPerformSkill(), HealHealthWoundOther2Command::canPerformSkill(), CurePackCommand::canPerformSkill(), TotalHealOtherCommand::canPerformSkill(), DotPackCommand::checkTarget(), HealStatesOtherCommand::checkTarget(), ForceCureDiseaseCommand::checkTarget(), StopBleedingCommand::checkTarget(), ForceCurePoisonCommand::checkTarget(), HealAllOther2Command::checkTarget(), HealAllOther1Command::checkTarget(), HealActionWoundOther1Command::checkTarget(), HealMindWoundOther1Command::checkTarget(), HealMindWoundOther2Command::checkTarget(), HealActionWoundOther2Command::checkTarget(), HealHealthWoundOther1Command::checkTarget(), HealHealthWoundOther2Command::checkTarget(), TotalHealOtherCommand::checkTarget(), TurretFireTask::checkTarget(), CurePackCommand::checkTarget(), HealDamageCommand::checkTarget(), CombatManager::doAreaCombatAction(), AiNPCComponent::doAwarenessCheck(), AiCreatureComponent::doAwarenessCheck(), HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), server::zone::objects::creature::AiAgentImplementation::doMovement(), SniperShotCommand::doQueueCommand(), SampleDNACommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), and server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo().
bool CollisionManager::checkLineOfSightInBuilding (SceneObject * object1, SceneObject * object2, SceneObject * building) static
Definition at line 36 of file CollisionManager.cpp.
References MeshAppearanceTemplate::getAABBTree(), PortalLayout::getAppearanceTemplatesSize(), PortalLayout::getMeshAppearanceTemplate(), server::zone::objects::scene::SceneObject::getObjectTemplate(), and server::zone::templates::SharedObjectTemplate::getPortalLayout().
Referenced by checkLineOfSight().
bool CollisionManager::checkLineOfSightInParentCell (SceneObject * object, Vector3 & endPoint) static
Definition at line 764 of file CollisionManager.cpp.
References MeshAppearanceTemplate::getAABBTree(), server::zone::objects::cell::CellObject::getCellNumber(), and PortalLayout::getMeshAppearanceTemplate().
Referenced by MoveFurnitureCommand::checkCollision(), and TransferItemMiscCommand::doQueueCommand().
bool CollisionManager::checkLineOfSightWorldToCell (const Vector3 & rayOrigin, const Vector3 & rayEnd, float distance, CellObject * cell) static
Definition at line 148 of file CollisionManager.cpp.
References convertToModelSpace(), MeshAppearanceTemplate::getAABBTree(), PortalLayout::getAppearanceTemplatesSize(), server::zone::objects::cell::CellObject::getCellNumber(), PortalLayout::getMeshAppearanceTemplate(), server::zone::objects::scene::SceneObject::getParent(), and server::zone::templates::SharedObjectTemplate::getPortalLayout().
Referenced by checkLineOfSight().
bool CollisionManager::checkMovementCollision (CreatureObject * creature, float x, float z, float y, Zone * zone) static
Definition at line 181 of file CollisionManager.cpp.
References convertToModelSpace(), getAABBTree(), server::zone::Zone::getInRangeObjects(), and server::zone::objects::scene::SceneObject::getWorldPosition().
bool CollisionManager::checkShipCollision (ShipObject * ship, const Vector3 & targetPosition, Vector3 & collisionPoint) static
Definition at line 640 of file CollisionManager.cpp.
References convertToModelSpace(), server::zone::objects::scene::SceneObject::error(), getAABBTree(), TerrainManager::getHeight(), server::zone::Zone::getInRangeObjects(), server::zone::Zone::getPlanetManager(), server::zone::managers::planet::PlanetManager::getTerrainManager(), TerrainManager::getWaterHeight(), server::zone::objects::scene::SceneObject::getWorldPosition(), and server::zone::objects::scene::SceneObject::getZone().
Referenced by ShipUpdateTransformCallback::run().
bool CollisionManager::checkSphereCollision (const Vector3 & sphereOrigin, float radius, Zone * zone) static
Definition at line 104 of file CollisionManager.cpp.
References convertToModelSpace(), server::zone::objects::scene::SceneObject::error(), getAABBTree(), and server::zone::Zone::getInRangeObjects().
Referenced by server::zone::objects::mission::DestroyMissionObjectiveImplementation::findValidSpawnPosition(), server::zone::managers::director::DirectorManager::getSpawnPoint(), and server::zone::objects::area::LairSpawnAreaImplementation::trySpawnLair().
Ray CollisionManager::convertToModelSpace (const Vector3 & rayOrigin, const Vector3 & rayEnd, SceneObject * model) static protected
Definition at line 626 of file CollisionManager.cpp.
References getTransformMatrix().
Referenced by checkLineOfSight(), checkLineOfSightWorldToCell(), checkMovementCollision(), checkShipCollision(), checkSphereCollision(), getWorldFloorCollision(), and getWorldFloorCollisions().
Vector3 CollisionManager::convertToModelSpace (const Vector3 & point, SceneObject * model) static protected
Definition at line 583 of file CollisionManager.cpp.
References getTransformMatrix().
PathNode * CollisionManager::findNearestPathNode (TriangleNode * triangle, FloorMesh * floor, const Vector3 & finalTarget) static
Returns
nearest available path node int the floor path graph with the lowest distance from triangle to final target
Definition at line 726 of file CollisionManager.cpp.
References FloorMesh::getPathGraph(), PathGraph::getPathNodes(), PathNode::getPosition(), and getTriangle().
Referenced by PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), and PathFinderManager::findPathFromWorldToCell().
AABBTree * CollisionManager::getAABBTree (SceneObject * scno, int collisionBlockFlags) static protected
Definition at line 75 of file CollisionManager.cpp.
References MeshAppearanceTemplate::getAABBTree(), server::zone::templates::SharedObjectTemplate::getAppearanceTemplate(), server::zone::templates::SharedObjectTemplate::getCollisionActionBlockFlags(), AppearanceTemplate::getFirstMesh(), PortalLayout::getMeshAppearanceTemplate(), server::zone::objects::scene::SceneObject::getObjectTemplate(), and server::zone::templates::SharedObjectTemplate::getPortalLayout().
Referenced by checkLineOfSight(), checkMovementCollision(), checkShipCollision(), checkSphereCollision(), and getWorldFloorCollisions().
Vector< float > * CollisionManager::getCellFloorCollision (float x, float y, CellObject * cellObject) static
Definition at line 241 of file CollisionManager.cpp.
References FloorMesh::getAABBTree(), server::zone::objects::cell::CellObject::getCellNumber(), PortalLayout::getFloorMesh(), server::zone::templates::SharedObjectTemplate::getPortalLayout(), and server::zone::objects::scene::SceneObject::getRootParent().
Referenced by ElevatorMenuComponent::handleObjectMenuSelect(), and DataTransformWithParentCallback::updatePosition().
float CollisionManager::getRayOriginPoint (CreatureObject * creature) static
Definition at line 24 of file CollisionManager.cpp.
References server::zone::objects::creature::CreatureObject::getHeight(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::creature::CreatureObject::isKneeling(), server::zone::objects::creature::CreatureObject::isKnockedDown(), and server::zone::objects::creature::CreatureObject::isProne().
Referenced by checkLineOfSight().
Reference< Matrix4 * > CollisionManager::getTransformMatrix (SceneObject * model) static protected
Definition at line 591 of file CollisionManager.cpp.
References server::zone::objects::scene::SceneObject::getDirection(), server::zone::objects::scene::SceneObject::getTransformForCollisionMatrix(), and server::zone::objects::scene::SceneObject::setTransformForCollisionMatrixIfNull().
Referenced by convertToModelSpace().
TriangleNode * CollisionManager::getTriangle (const Vector3 & point, FloorMesh * floor) static
Definition at line 553 of file CollisionManager.cpp.
References FloorMesh::findNearestTriangle(), and FloorMesh::getAABBTree().
Referenced by findNearestPathNode(), PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), PathFinderManager::findPathFromWorldToCell(), and PathFinderManager::getFloorPath().
float CollisionManager::getWorldFloorCollision (float x, float y, Zone * zone, bool testWater) static
Definition at line 295 of file CollisionManager.cpp.
References convertToModelSpace(), FloorMesh::getAABBTree(), PortalLayout::getFloorMesh(), PortalLayout::getFloorMeshNumber(), TerrainManager::getHeight(), server::zone::Zone::getInRangeObjects(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::Zone::getPlanetManager(), server::zone::templates::SharedObjectTemplate::getPortalLayout(), server::zone::managers::planet::PlanetManager::getTerrainManager(), and TerrainManager::getWaterHeight().
void CollisionManager::getWorldFloorCollisions (float x, float y, Zone * zone, bool testWater, SortedVector< IntersectionResult > * result, CloseObjectsVector * closeObjectsVector = NULL) static
Definition at line 367 of file CollisionManager.cpp.
References convertToModelSpace(), getAABBTree(), TerrainManager::getHeight(), server::zone::Zone::getInRangeObjects(), server::zone::Zone::getPlanetManager(), server::zone::managers::planet::PlanetManager::getTerrainManager(), and TerrainManager::getWaterHeight().
Referenced by server::zone::managers::planet::PlanetManagerImplementation::findClosestWorldFloor(), DataTransformCallback::updatePosition(), and server::zone::managers::player::PlayerManagerImplementation::updateSwimmingState().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/collision/CollisionManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/collision/CollisionManager.cpp