Core3: TemplateVariable< formType > Class Template Reference
TemplateVariable< formType > Class Template Reference
#include <TemplateVariable.h>
Public Member Functions
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
virtual void parseFromIffStream (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Detailed Description
template<int formType>
class TemplateVariable< formType >
Definition at line 32 of file TemplateVariable.h.
Constructor & Destructor Documentation
template<int formType> virtual TemplateVariable< formType >::~TemplateVariable () inline virtual
Definition at line 36 of file TemplateVariable.h.
Member Function Documentation
template<int formType> virtual void TemplateVariable< formType >::parseFromIffStream (engine::util::IffStream * iffStream) inline virtual
Reimplemented in BoundaryPolygon, ProceduralTerrainAppearance, BoundaryRectangle, AffectorRiver, Layer, MapFractal, AffectorRoad, TerrainGenerator, BoundaryPolyline, FilterBitmap, FilterFractal, AffectorHeightFractal, FilterSlope, MapGroup, BitmapGroup, LayersGroup, ShadersGroup, EnvironmentGroup, AffectorFloraNonCollidableConstant, AffectorRCN, AffectorShaderReplace, EnvironmentData, AffectorColorConstant, AffectorColorRampHeight, AffectorFCN, AffectorNoncollideFloraConstant, AffectorRadialConstant, AffectorRadialFarConstant, BoundaryCircle, FilterDirection, Hdta, FloraGroup, AffectorHeightConstant, AffectorShaderConstant, FilterHeight, Road, RadialGroup, AffectorColorRampFractal, AffectorEnvironment, AffectorHeightTerrace, FilterShader, TerrainMaps, BitMapFamily, AffectorPassable, AffectorExclude, MapFamily, and InformationHeader.
Definition at line 49 of file TemplateVariable.h.
Referenced by TemplateVariable<'RFAM'>::readObject().
template<int formType> void TemplateVariable< formType >::readObject (engine::util::IffStream * iffStream) inline virtual
Implements IffTemplateVariable.
Reimplemented in TerrainMap<'WMAP'>, and TerrainMap<'SMAP'>.
Definition at line 40 of file TemplateVariable.h.
Referenced by MapFamily::parseFromIffStream(), AffectorHeightFractal::parseFromIffStream(), FilterFractal::parseFromIffStream(), LayersGroup::parseFromIffStream(), AffectorExclude::parseFromIffStream(), AffectorPassable::parseFromIffStream(), AffectorHeightTerrace::parseFromIffStream(), AffectorColorRampFractal::parseFromIffStream(), AffectorEnvironment::parseFromIffStream(), FilterShader::parseFromIffStream(), AffectorHeightConstant::parseFromIffStream(), AffectorShaderConstant::parseFromIffStream(), FilterHeight::parseFromIffStream(), AffectorRadialFarConstant::parseFromIffStream(), AffectorFCN::parseFromIffStream(), AffectorColorRampHeight::parseFromIffStream(), AffectorColorConstant::parseFromIffStream(), BoundaryCircle::parseFromIffStream(), AffectorNoncollideFloraConstant::parseFromIffStream(), AffectorRadialConstant::parseFromIffStream(), AffectorRCN::parseFromIffStream(), AffectorFloraNonCollidableConstant::parseFromIffStream(), TerrainGenerator::parseFromIffStream(), AffectorShaderReplace::parseFromIffStream(), EnvironmentGroup::parseFromIffStream(), BitmapGroup::parseFromIffStream(), MapGroup::parseFromIffStream(), FilterBitmap::parseFromIffStream(), Layer::parseFromIffStream(), BoundaryPolyline::parseFromIffStream(), AffectorRoad::parseFromIffStream(), FilterSlope::parseFromIffStream(), AffectorRiver::parseFromIffStream(), ProceduralTerrainAppearance::parseFromIffStream(), FilterDirection::parseFromIffStream(), BoundaryRectangle::parseFromIffStream(), BoundaryPolygon::parseFromIffStream(), and TEST_F().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/TemplateVariable.h