Core3: Subclasses Class Reference
Subclasses Class Reference
#include <ValuesClasses.h>
Public Member Functions
Subclasses (const String &title, const String &subtitle, const float min, const float max, const int precision, const bool filler, const int combine)
Subclasses (const Subclasses &sub)
~Subclasses ()
void addSubtitle (const String &s, const float min, const float max, const int precision, const bool filler, const int combine)
Values * get (const int i)
Values * get (const String &subTitle)
int size ()
bool isClassHidden ()
bool hasAllHiddenItems ()
float getPercentage (const String &subTitle)
float getMaxPercentage (const String &subTitle)
float getValue (const String &subTitle)
String & getClassTitle ()
void setMaxPercentage (const String &subtitle, float value)
void setValue (const String &subtitle, const float value)
void setPercentage (const String &subtitle, float value)
String toString ()
Private Attributes
VectorMap< String, Reference
< Values * > > valueList
float avePercentage
String name
String classTitle
bool hidden
Detailed Description
Definition at line 248 of file ValuesClasses.h.
Constructor & Destructor Documentation
Subclasses::Subclasses (const String & title, const String & subtitle, const float min, const float max, const int precision, const bool filler, const int combine) inline
Definition at line 256 of file ValuesClasses.h.
References avePercentage, classTitle, hidden, name, and valueList.
Subclasses::Subclasses (const Subclasses & sub) inline
Definition at line 276 of file ValuesClasses.h.
References avePercentage, classTitle, Values::getValue(), hidden, name, and valueList.
Subclasses::~Subclasses () inline
Definition at line 293 of file ValuesClasses.h.
Member Function Documentation
void Subclasses::addSubtitle (const String & s, const float min, const float max, const int precision, const bool filler, const int combine) inline
Definition at line 296 of file ValuesClasses.h.
References valueList.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::addExperimentalProperty().
Values* Subclasses::get (const int i) inline
Definition at line 308 of file ValuesClasses.h.
References valueList.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCombineType(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentVisiblePercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertyTitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxVisiblePercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMinValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getPrecision(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getSubtitleCount(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getTitleLine(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getVisibleExperimentalPropertyTitleSize(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::hasProperty(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::isHidden(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::lockValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::resetValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setHidden(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMinValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setPrecision(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::unlockValue(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::unsetHidden().
Values* Subclasses::get (const String & subTitle) inline
Definition at line 312 of file ValuesClasses.h.
References valueList.
String& Subclasses::getClassTitle () inline
Definition at line 353 of file ValuesClasses.h.
References classTitle.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitlesTitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertyTitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getTitleLine(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getVisibleExperimentalPropertyTitle(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::toString().
float Subclasses::getMaxPercentage (const String & subTitle) inline
Definition at line 339 of file ValuesClasses.h.
References Values::getMaxPercentage(), and valueList.
float Subclasses::getPercentage (const String & subTitle) inline
Definition at line 334 of file ValuesClasses.h.
References Values::getPercentage(), and valueList.
float Subclasses::getValue (const String & subTitle) inline
Definition at line 344 of file ValuesClasses.h.
References Values::getValue(), and valueList.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::CraftingValues().
bool Subclasses::hasAllHiddenItems () inline
Definition at line 324 of file ValuesClasses.h.
References Values::getMaxValue(), Values::getMinValue(), Values::isFiller(), and valueList.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getVisibleExperimentalPropertyTitle(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getVisibleExperimentalPropertyTitleSize().
bool Subclasses::isClassHidden () inline
Definition at line 320 of file ValuesClasses.h.
References hidden.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getTitleLine().
void Subclasses::setMaxPercentage (const String & subtitle, float value) inline
Definition at line 357 of file ValuesClasses.h.
References Values::setMaxPercentage(), and valueList.
void Subclasses::setPercentage (const String & subtitle, float value) inline
Definition at line 368 of file ValuesClasses.h.
References Values::setPercentage(), and valueList.
void Subclasses::setValue (const String & subtitle, const float value) inline
Definition at line 363 of file ValuesClasses.h.
References Values::setValue(), and valueList.
int Subclasses::size () inline
Definition at line 316 of file ValuesClasses.h.
References valueList.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCombineType(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentVisiblePercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitleSize(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitlesTitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertyTitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxVisiblePercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMinValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getPrecision(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getSubtitleCount(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::hasProperty(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::isHidden(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::lockValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::resetValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setHidden(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMinValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setPrecision(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::unlockValue(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::unsetHidden().
String Subclasses::toString () inline
Definition at line 373 of file ValuesClasses.h.
References Values::getMaxPercentage(), Values::getMaxValue(), Values::getMinValue(), Values::getName(), Values::getPercentage(), Values::getValue(), Values::isFiller(), and valueList.
Referenced by server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::toString().
Member Data Documentation
float Subclasses::avePercentage private
Definition at line 250 of file ValuesClasses.h.
Referenced by Subclasses().
String Subclasses::classTitle private
Definition at line 251 of file ValuesClasses.h.
Referenced by getClassTitle(), and Subclasses().
bool Subclasses::hidden private
Definition at line 253 of file ValuesClasses.h.
Referenced by isClassHidden(), and Subclasses().
String Subclasses::name private
Definition at line 251 of file ValuesClasses.h.
Referenced by Subclasses().
VectorMap<String, Reference<Values*> > Subclasses::valueList private
Definition at line 249 of file ValuesClasses.h.
Referenced by addSubtitle(), get(), getMaxPercentage(), getPercentage(), getValue(), hasAllHiddenItems(), setMaxPercentage(), setPercentage(), setValue(), size(), Subclasses(), and toString().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/craftingvalues/ValuesClasses.h