Core3: AvoidIncapacitationCommand Class Reference
AvoidIncapacitationCommand Class Reference
#include <AvoidIncapacitationCommand.h>
Public Member Functions
AvoidIncapacitationCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file AvoidIncapacitationCommand.h.
Constructor & Destructor Documentation
AvoidIncapacitationCommand::AvoidIncapacitationCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file AvoidIncapacitationCommand.h.
Member Function Documentation
int AvoidIncapacitationCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 58 of file AvoidIncapacitationCommand.h.
References server::zone::objects::creature::CreatureObject::addBuff(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::hasBuff(), BuffType::JEDI, BuffCRC::JEDI_AVOID_INCAPACITATION, BuffCRC::JEDI_AVOID_INCAPACITATION_1, BuffCRC::JEDI_AVOID_INCAPACITATION_2, BuffCRC::JEDI_AVOID_INCAPACITATION_3, BuffCRC::JEDI_AVOID_INCAPACITATION_4, BuffCRC::JEDI_AVOID_INCAPACITATION_5, server::zone::objects::creature::CreatureObject::playEffect(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/AvoidIncapacitationCommand.h