Core3: server::zone::managers::player::PlayerMap Class Reference
server::zone::managers::player::PlayerMap Class Reference
#include <PlayerMap.h>
Public Member Functions
PlayerMap (int initsize)
CreatureObject * put (const String &name, CreatureObject *player, bool doLock=true)
CreatureObject * get (const String &name, bool doLock=true)
CreatureObject * remove (const String &name, bool doLock=true)
CreatureObject * getNextValue (bool doLock=true)
CreatureObject * next (bool doLock=true)
bool hasNext (bool doLock=true)
void resetIterator (bool doLock=true)
int size (bool doLock=true)
Private Attributes
HashTable< String,
ManagedReference
< CreatureObject * > > players
HashTableIterator< String,
ManagedReference
< CreatureObject * > > iter
Detailed Description
Definition at line 59 of file PlayerMap.h.
Constructor & Destructor Documentation
server::zone::managers::player::PlayerMap::PlayerMap (int initsize) inline
Definition at line 64 of file PlayerMap.h.
Member Function Documentation
CreatureObject* server::zone::managers::player::PlayerMap::get (const String & name, bool doLock = true) inline
Definition at line 90 of file PlayerMap.h.
References players.
CreatureObject* server::zone::managers::player::PlayerMap::getNextValue (bool doLock = true) inline
Definition at line 136 of file PlayerMap.h.
References iter.
Referenced by BroadcastPlanetCommand::doQueueCommand(), and next().
bool server::zone::managers::player::PlayerMap::hasNext (bool doLock = true) inline
Definition at line 152 of file PlayerMap.h.
References iter.
Referenced by BroadcastPlanetCommand::doQueueCommand().
CreatureObject* server::zone::managers::player::PlayerMap::next (bool doLock = true) inline
Definition at line 148 of file PlayerMap.h.
References getNextValue().
CreatureObject* server::zone::managers::player::PlayerMap::put (const String & name, CreatureObject * player, bool doLock = true) inline
Definition at line 67 of file PlayerMap.h.
References players.
CreatureObject* server::zone::managers::player::PlayerMap::remove (const String & name, bool doLock = true) inline
Definition at line 113 of file PlayerMap.h.
References players.
void server::zone::managers::player::PlayerMap::resetIterator (bool doLock = true) inline
Definition at line 164 of file PlayerMap.h.
References iter.
Referenced by BroadcastPlanetCommand::doQueueCommand().
int server::zone::managers::player::PlayerMap::size (bool doLock = true) inline
Definition at line 172 of file PlayerMap.h.
References players.
Member Data Documentation
HashTableIterator<String, ManagedReference<CreatureObject*> > server::zone::managers::player::PlayerMap::iter private
Definition at line 61 of file PlayerMap.h.
Referenced by getNextValue(), hasNext(), and resetIterator().
HashTable<String, ManagedReference<CreatureObject*> > server::zone::managers::player::PlayerMap::players private
Definition at line 60 of file PlayerMap.h.
Referenced by get(), put(), remove(), and size().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/PlayerMap.h