Core3: SkillDataForm Class Reference
SkillDataForm Class Reference
#include <SkillDataForm.h>
Public Member Functions
SkillDataForm ()
~SkillDataForm ()
void readObject (IffStream *iffStream)
int getTotalPaths ()
String getPathBySkillName (const String &professionName)
String getSkillNameAt (int idx)
Public Member Functions inherited from IffTemplate
virtual ~IffTemplate ()
Public Member Functions inherited from TemplateData
virtual ~TemplateData ()
Private Attributes
VectorMap< String, String > professionInfoPaths
Detailed Description
Definition at line 14 of file SkillDataForm.h.
Constructor & Destructor Documentation
SkillDataForm::SkillDataForm () inline
Definition at line 18 of file SkillDataForm.h.
SkillDataForm::~SkillDataForm () inline
Definition at line 22 of file SkillDataForm.h.
Member Function Documentation
String SkillDataForm::getPathBySkillName (const String & professionName) inline
Definition at line 61 of file SkillDataForm.h.
References professionInfoPaths.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::loadProfessionDefaultsInfo().
String SkillDataForm::getSkillNameAt (int idx) inline
Definition at line 65 of file SkillDataForm.h.
References professionInfoPaths.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::loadProfessionDefaultsInfo().
int SkillDataForm::getTotalPaths () inline
Definition at line 57 of file SkillDataForm.h.
References professionInfoPaths.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::loadProfessionDefaultsInfo().
void SkillDataForm::readObject (IffStream * iffStream) inline virtual
Implements IffTemplate.
Definition at line 26 of file SkillDataForm.h.
References professionInfoPaths.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::loadProfessionDefaultsInfo().
Member Data Documentation
VectorMap<String, String> SkillDataForm::professionInfoPaths private
Definition at line 15 of file SkillDataForm.h.
Referenced by getPathBySkillName(), getSkillNameAt(), getTotalPaths(), and readObject().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/creation/SkillDataForm.h