Core3: server::zone::objects::area::areashapes::CircularAreaShape Class Reference
server::zone::objects::area::areashapes::CircularAreaShape Class Reference
#include <CircularAreaShape.h>
Public Member Functions
CircularAreaShape ()
void setRadius (float r)
float getRadius ()
float getRadius2 ()
bool containsPoint (float x, float y)
bool containsPoint (const Vector3 &point)
Vector3 getRandomPosition ()
Vector3 getRandomPosition (const Vector3 &origin, float minDistance, float maxDistance)
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::area::areashapes::AreaShape
AreaShape ()
void setAreaCenter (float x, float y)
Vector3 getAreaCenter ()
bool containsPoint (float x, float y)
float getRadius ()
Vector3 getRandomPosition ()
Vector3 getRandomPosition (const Vector3 &origin, float minDistance, float maxDistance)
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
CircularAreaShape (DummyConstructorParameter *param)
virtual ~CircularAreaShape ()
Protected Member Functions inherited from server::zone::objects::area::areashapes::AreaShape
AreaShape (DummyConstructorParameter *param)
virtual ~AreaShape ()
Friends
class CircularAreaShapeHelper
Detailed Description
Definition at line 22 of file CircularAreaShape.h.
Constructor & Destructor Documentation
CircularAreaShape::CircularAreaShape ()
Constructor
Definition at line 13 of file CircularAreaShape.cpp.
References server::zone::objects::area::areashapes::CircularAreaShapeImplementation::_setStub().
CircularAreaShape::CircularAreaShape (DummyConstructorParameter * param) protected
Definition at line 20 of file CircularAreaShape.cpp.
CircularAreaShape::~CircularAreaShape () protected virtual
Definition at line 24 of file CircularAreaShape.cpp.
Member Function Documentation
DistributedObjectServant * CircularAreaShape::_getImplementation ()
Definition at line 177 of file CircularAreaShape.cpp.
Referenced by containsPoint(), getArea(), getRadius(), getRadius2(), getRandomPosition(), intersectsWith(), isCircularAreaShape(), isRectangularAreaShape(), isRingAreaShape(), and setRadius().
DistributedObjectServant * CircularAreaShape::_getImplementationForRead ()
Definition at line 183 of file CircularAreaShape.cpp.
void CircularAreaShape::_setImplementation (DistributedObjectServant * servant)
Definition at line 187 of file CircularAreaShape.cpp.
bool CircularAreaShape::containsPoint (float x, float y)
Check if the coordinate is within the area shape.
Parameters
x the x coordinate.
y the y coordinate.
Returns
true if the coordinate is within the area shape.
Definition at line 69 of file CircularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::containsPoint(), and RPC_CONTAINSPOINT__FLOAT_FLOAT_.
bool CircularAreaShape::containsPoint (const Vector3 & point) virtual
Check if the coordinate is within the area shape.
Parameters
point the point to check if it is within the area shape.
Returns
true if the coordinate is within the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShape.
Definition at line 84 of file CircularAreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::CircularAreaShapeImplementation::containsPoint().
float CircularAreaShape::getArea ()
Get the area of the areaShape.
Returns
the area of the area shape.
Definition at line 164 of file CircularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::getArea(), and RPC_GETAREA__.
float CircularAreaShape::getRadius ()
Get the radius of the circle.
Returns
radius of the circle
Definition at line 43 of file CircularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::getRadius(), and RPC_GETRADIUS__.
float CircularAreaShape::getRadius2 ()
Get the squared radius of the circle.
Returns
squared radius of the circle
Definition at line 56 of file CircularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::getRadius2(), and RPC_GETRADIUS2__.
Referenced by server::zone::objects::area::areashapes::CircularAreaShapeImplementation::intersectsWithCircle(), and server::zone::objects::area::areashapes::RingAreaShapeImplementation::intersectsWithCircle().
Vector3 CircularAreaShape::getRandomPosition ()
Generate a random position within the area.
Returns
a random position within the area.
Definition at line 93 of file CircularAreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::CircularAreaShapeImplementation::getRandomPosition().
Vector3 CircularAreaShape::getRandomPosition (const Vector3 & origin, float minDistance, float maxDistance)
Generate a random position within the area with the supplied origin and radius as limits.
Parameters
origin the origin coordinate to generate the random position from.
minDistance the minimum distance from the origin.
maxDistance the maximum distance from the origin.
Returns
a random position within the area.
Definition at line 102 of file CircularAreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::CircularAreaShapeImplementation::getRandomPosition().
bool CircularAreaShape::intersectsWith (AreaShape * areaShape)
Check if this area shape intersects with the supplied area shape.
Parameters
areaShape the area shape to check for intersections with.s
Returns
true if the area shapes intersects each other.
Definition at line 150 of file CircularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::intersectsWith(), and RPC_INTERSECTSWITH__AREASHAPE_.
bool CircularAreaShape::isCircularAreaShape ()
Check if this is a circular area shape.
Returns
true if it is a circular area shape.
Definition at line 111 of file CircularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::isCircularAreaShape(), and RPC_ISCIRCULARAREASHAPE__.
bool CircularAreaShape::isRectangularAreaShape ()
Check if this is a rectangular area shape.
Returns
true if it is a rectangular area shape.
Definition at line 124 of file CircularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::isRectangularAreaShape(), and RPC_ISRECTANGULARAREASHAPE__.
bool CircularAreaShape::isRingAreaShape ()
Check if this is a ring area shape.
Returns
true if it is a ring area shape.
Definition at line 137 of file CircularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::isRingAreaShape(), and RPC_ISRINGAREASHAPE__.
void CircularAreaShape::setRadius (float r)
Set the radius of the cirle.
Parameters
r the new radius of the circle.
Definition at line 29 of file CircularAreaShape.cpp.
References _getImplementation(), RPC_SETRADIUS__FLOAT_, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation::setRadius().
Friends And Related Function Documentation
friend class CircularAreaShapeHelper friend
Definition at line 116 of file CircularAreaShape.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/CircularAreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/CircularAreaShape.cpp