Core3: server::zone::objects::area::areashapes::RectangularAreaShapeAdapter Class Reference
server::zone::objects::area::areashapes::RectangularAreaShapeAdapter Class Reference
#include <RectangularAreaShape.h>
Public Member Functions
RectangularAreaShapeAdapter (RectangularAreaShape *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setDimensions (float h, float w)
float getHeight ()
float getWidth ()
bool containsPoint (float x, float y)
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
Public Member Functions inherited from server::zone::objects::area::areashapes::AreaShapeAdapter
AreaShapeAdapter (AreaShape *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setAreaCenter (float x, float y)
bool containsPoint (float x, float y)
float getRadius ()
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
Detailed Description
Definition at line 296 of file RectangularAreaShape.h.
Constructor & Destructor Documentation
RectangularAreaShapeAdapter::RectangularAreaShapeAdapter (RectangularAreaShape * impl)
Definition at line 389 of file RectangularAreaShape.cpp.
Member Function Documentation
bool RectangularAreaShapeAdapter::containsPoint (float x, float y)
Definition at line 458 of file RectangularAreaShape.cpp.
Referenced by invokeMethod().
float RectangularAreaShapeAdapter::getArea ()
Definition at line 478 of file RectangularAreaShape.cpp.
Referenced by invokeMethod().
float RectangularAreaShapeAdapter::getHeight ()
Definition at line 450 of file RectangularAreaShape.cpp.
Referenced by invokeMethod().
float RectangularAreaShapeAdapter::getWidth ()
Definition at line 454 of file RectangularAreaShape.cpp.
Referenced by invokeMethod().
bool RectangularAreaShapeAdapter::intersectsWith (AreaShape * areaShape)
Definition at line 474 of file RectangularAreaShape.cpp.
Referenced by invokeMethod().
void RectangularAreaShapeAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 392 of file RectangularAreaShape.cpp.
References containsPoint(), getArea(), getHeight(), getWidth(), intersectsWith(), isCircularAreaShape(), isRectangularAreaShape(), isRingAreaShape(), RPC_CONTAINSPOINT__FLOAT_FLOAT_, RPC_GETAREA__, RPC_GETHEIGHT__, RPC_GETWIDTH__, RPC_INTERSECTSWITH__AREASHAPE_, RPC_ISCIRCULARAREASHAPE__, RPC_ISRECTANGULARAREASHAPE__, RPC_ISRINGAREASHAPE__, RPC_SETDIMENSIONS__FLOAT_FLOAT_, and setDimensions().
bool RectangularAreaShapeAdapter::isCircularAreaShape ()
Definition at line 462 of file RectangularAreaShape.cpp.
Referenced by invokeMethod().
bool RectangularAreaShapeAdapter::isRectangularAreaShape ()
Definition at line 466 of file RectangularAreaShape.cpp.
Referenced by invokeMethod().
bool RectangularAreaShapeAdapter::isRingAreaShape ()
Definition at line 470 of file RectangularAreaShape.cpp.
Referenced by invokeMethod().
void RectangularAreaShapeAdapter::setDimensions (float h, float w)
Definition at line 446 of file RectangularAreaShape.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RectangularAreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RectangularAreaShape.cpp