Core3: server::zone::objects::creature::ai::AiActorAdapter Class Reference
server::zone::objects::creature::ai::AiActorAdapter Class Reference
#include <AiActor.h>
Public Member Functions
AiActorAdapter (AiActor *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setHost (CreatureObject *creo)
CreatureObject * getHost ()
void initializeTransientMembers ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void notifyPositionUpdate (QuadTreeEntry *entry)
void setCurrentMessage (unsigned short msg)
void next (unsigned short msg)
void next ()
void destroyActor ()
void addTransition (const String &stateName, unsigned short msg, const String &resultState)
void setLevel (int lvl)
int calculateAttackMinDamage (int level)
int calculateAttackMaxDamage (int level)
float calculateAttackSpeed (int level)
bool isCamouflaged (CreatureObject *target)
bool isScentMasked (CreatureObject *target)
bool isConcealed (CreatureObject *target)
void activateRecovery ()
void activateMovementEvent ()
void activateAwarenessEvent (CreatureObject *target)
void activatePostureRecovery ()
void queueDizzyFallEvent ()
void setNextStepPosition (float x, float z, float y, SceneObject *cell)
void setShowNextPosition (bool val)
bool isShowNextPosition ()
int getMovementMarkersSize ()
SceneObject * getMovementMarker (int i)
void dropMovementMarker (SceneObject *marker)
void dropAllMovemementMarkers ()
void addMovementMarker (SceneObject *marker)
void clearPatrolPoints ()
void setHomeLocation (float x, float z, float y, SceneObject *cell)
void setDespawnOnNoPlayerInRange (bool val)
void notifyDespawn (Zone *zone)
void scheduleDespawn (int timeToDespawn)
void respawn (Zone *zone, int level)
void scheduleDespawn ()
void clearDespawnEvent ()
void setRespawnTimer (float resp)
float getRespawnTimer ()
bool getDespawnOnNoPlayerInRange ()
int getNumberOfPlayersInRange ()
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
int notifyConverseObservers (CreatureObject *converser)
SceneObject * getFollowObject ()
void setFollowObject (SceneObject *targ)
void setTargetObject (SceneObject *obj)
void setOblivious ()
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
void updateLastDamageReceived ()
void sendConversationStartTo (SceneObject *player)
float getKinetic ()
float getEnergy ()
float getElectricity ()
float getStun ()
float getBlast ()
float getHeat ()
float getCold ()
float getAcid ()
float getLightSaber ()
bool isStalker ()
bool isKiller ()
unsigned int getFerocity ()
unsigned int getArmor ()
String getFactionString ()
String getSocialGroup ()
float getChanceHit ()
int getDamageMin ()
int getDamageMax ()
int getBaseXp ()
unsigned int getDiet ()
bool isActorObject ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectAdapter
SceneObjectAdapter (SceneObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializePrivateData ()
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient, bool allowOverflow)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects)
void destroyObjectFromDatabase (bool destroyContainedObjects)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose)
void sendAttributeListTo (CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void openContainerTo (CreatureObject *player)
void closeContainerTo (CreatureObject *player, bool notify)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
unsigned long long getParentID ()
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
float getWorldPositionX ()
float getWorldPositionY ()
float getWorldPositionZ ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isDecoration ()
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZone (Zone *zone)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
bool containsChildObject (SceneObject *obj)
void createChildObjects ()
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
Detailed Description
Definition at line 848 of file AiActor.h.
Constructor & Destructor Documentation
AiActorAdapter::AiActorAdapter (AiActor * impl)
Definition at line 2058 of file AiActor.cpp.
Member Function Documentation
void AiActorAdapter::activateAwarenessEvent (CreatureObject * target)
Definition at line 2532 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::activateMovementEvent ()
Definition at line 2528 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::activatePostureRecovery ()
Definition at line 2536 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::activateRecovery ()
Definition at line 2524 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::addDefender (SceneObject * defender)
Definition at line 2656 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::addMovementMarker (SceneObject * marker)
Definition at line 2572 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::addTransition (const String & stateName, unsigned short msg, const String & resultState)
Definition at line 2492 of file AiActor.cpp.
Referenced by invokeMethod().
int AiActorAdapter::calculateAttackMaxDamage (int level)
Definition at line 2504 of file AiActor.cpp.
Referenced by invokeMethod().
int AiActorAdapter::calculateAttackMinDamage (int level)
Definition at line 2500 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::calculateAttackSpeed (int level)
Definition at line 2508 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::clearDespawnEvent ()
Definition at line 2604 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::clearPatrolPoints ()
Definition at line 2576 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::destroyActor ()
Definition at line 2488 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::dropAllMovemementMarkers ()
Definition at line 2568 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::dropMovementMarker (SceneObject * marker)
Definition at line 2564 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::fillAttributeList (AttributeListMessage * msg, CreatureObject * object)
Definition at line 2468 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::getAcid ()
Definition at line 2708 of file AiActor.cpp.
Referenced by invokeMethod().
unsigned int AiActorAdapter::getArmor ()
Definition at line 2728 of file AiActor.cpp.
Referenced by invokeMethod().
int AiActorAdapter::getBaseXp ()
Definition at line 2752 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::getBlast ()
Definition at line 2696 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::getChanceHit ()
Definition at line 2740 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::getCold ()
Definition at line 2704 of file AiActor.cpp.
Referenced by invokeMethod().
int AiActorAdapter::getDamageMax ()
Definition at line 2748 of file AiActor.cpp.
Referenced by invokeMethod().
int AiActorAdapter::getDamageMin ()
Definition at line 2744 of file AiActor.cpp.
Referenced by invokeMethod().
bool AiActorAdapter::getDespawnOnNoPlayerInRange ()
Definition at line 2616 of file AiActor.cpp.
Referenced by invokeMethod().
unsigned int AiActorAdapter::getDiet ()
Definition at line 2756 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::getElectricity ()
Definition at line 2688 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::getEnergy ()
Definition at line 2684 of file AiActor.cpp.
Referenced by invokeMethod().
String AiActorAdapter::getFactionString ()
Definition at line 2732 of file AiActor.cpp.
Referenced by invokeMethod().
unsigned int AiActorAdapter::getFerocity ()
Definition at line 2724 of file AiActor.cpp.
Referenced by invokeMethod().
SceneObject * AiActorAdapter::getFollowObject ()
Definition at line 2636 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::getHeat ()
Definition at line 2700 of file AiActor.cpp.
Referenced by invokeMethod().
CreatureObject * AiActorAdapter::getHost ()
Definition at line 2460 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::getKinetic ()
Definition at line 2680 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::getLightSaber ()
Definition at line 2712 of file AiActor.cpp.
Referenced by invokeMethod().
SceneObject * AiActorAdapter::getMovementMarker (int i)
Definition at line 2560 of file AiActor.cpp.
Referenced by invokeMethod().
int AiActorAdapter::getMovementMarkersSize ()
Definition at line 2556 of file AiActor.cpp.
Referenced by invokeMethod().
int AiActorAdapter::getNumberOfPlayersInRange ()
Definition at line 2620 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::getRespawnTimer ()
Definition at line 2612 of file AiActor.cpp.
Referenced by invokeMethod().
String AiActorAdapter::getSocialGroup ()
Definition at line 2736 of file AiActor.cpp.
Referenced by invokeMethod().
float AiActorAdapter::getStun ()
Definition at line 2692 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::initializeTransientMembers ()
Definition at line 2464 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 2061 of file AiActor.cpp.
References activateAwarenessEvent(), activateMovementEvent(), activatePostureRecovery(), activateRecovery(), addDefender(), addMovementMarker(), addTransition(), calculateAttackMaxDamage(), calculateAttackMinDamage(), calculateAttackSpeed(), clearDespawnEvent(), clearPatrolPoints(), destroyActor(), dropAllMovemementMarkers(), dropMovementMarker(), fillAttributeList(), getAcid(), getArmor(), getBaseXp(), getBlast(), getChanceHit(), getCold(), getDamageMax(), getDamageMin(), getDespawnOnNoPlayerInRange(), getDiet(), getElectricity(), getEnergy(), getFactionString(), getFerocity(), getFollowObject(), getHeat(), getHost(), getKinetic(), getLightSaber(), getMovementMarker(), getMovementMarkersSize(), getNumberOfPlayersInRange(), getRespawnTimer(), getSocialGroup(), getStun(), initializeTransientMembers(), isActorObject(), isAggressiveTo(), isAttackableBy(), isCamouflaged(), isConcealed(), isKiller(), isScentMasked(), isShowNextPosition(), isStalker(), next(), notifyConverseObservers(), notifyDespawn(), notifyDissapear(), notifyInsert(), notifyPositionUpdate(), queueDizzyFallEvent(), removeDefender(), respawn(), RPC_ACTIVATEAWARENESSEVENT__CREATUREOBJECT_, RPC_ACTIVATEMOVEMENTEVENT__, RPC_ACTIVATEPOSTURERECOVERY__, RPC_ACTIVATERECOVERY__, RPC_ADDDEFENDER__SCENEOBJECT_, RPC_ADDMOVEMENTMARKER__SCENEOBJECT_, RPC_ADDTRANSITION__STRING_SHORT_STRING_, RPC_CALCULATEATTACKMAXDAMAGE__INT_, RPC_CALCULATEATTACKMINDAMAGE__INT_, RPC_CALCULATEATTACKSPEED__INT_, RPC_CLEARDESPAWNEVENT__, RPC_CLEARPATROLPOINTS__, RPC_DESTROYACTOR__, RPC_DROPALLMOVEMEMENTMARKERS__, RPC_DROPMOVEMENTMARKER__SCENEOBJECT_, RPC_FILLATTRIBUTELIST__ATTRIBUTELISTMESSAGE_CREATUREOBJECT_, RPC_GETACID__, RPC_GETARMOR__, RPC_GETBASEXP__, RPC_GETBLAST__, RPC_GETCHANCEHIT__, RPC_GETCOLD__, RPC_GETDAMAGEMAX__, RPC_GETDAMAGEMIN__, RPC_GETDESPAWNONNOPLAYERINRANGE__, RPC_GETDIET__, RPC_GETELECTRICITY__, RPC_GETENERGY__, RPC_GETFACTIONSTRING__, RPC_GETFEROCITY__, RPC_GETFOLLOWOBJECT__, RPC_GETHEAT__, RPC_GETHOST__, RPC_GETKINETIC__, RPC_GETLIGHTSABER__, RPC_GETMOVEMENTMARKER__INT_, RPC_GETMOVEMENTMARKERSSIZE__, RPC_GETNUMBEROFPLAYERSINRANGE__, RPC_GETRESPAWNTIMER__, RPC_GETSOCIALGROUP__, RPC_GETSTUN__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_ISACTOROBJECT__, RPC_ISAGGRESSIVETO__CREATUREOBJECT_, RPC_ISATTACKABLEBY__CREATUREOBJECT_, RPC_ISCAMOUFLAGED__CREATUREOBJECT_, RPC_ISCONCEALED__CREATUREOBJECT_, RPC_ISKILLER__, RPC_ISSCENTMASKED__CREATUREOBJECT_, RPC_ISSHOWNEXTPOSITION__, RPC_ISSTALKER__, RPC_NEXT__, RPC_NEXT__SHORT_, RPC_NOTIFYCONVERSEOBSERVERS__CREATUREOBJECT_, RPC_NOTIFYDESPAWN__ZONE_, RPC_NOTIFYDISSAPEAR__QUADTREEENTRY_, RPC_NOTIFYINSERT__QUADTREEENTRY_, RPC_NOTIFYPOSITIONUPDATE__QUADTREEENTRY_, RPC_QUEUEDIZZYFALLEVENT__, RPC_REMOVEDEFENDER__SCENEOBJECT_, RPC_RESPAWN__ZONE_INT_, RPC_SCHEDULEDESPAWN__, RPC_SCHEDULEDESPAWN__INT_, RPC_SENDCONVERSATIONSTARTTO__SCENEOBJECT_, RPC_SETCURRENTMESSAGE__SHORT_, RPC_SETDEFENDER__SCENEOBJECT_, RPC_SETDESPAWNONNOPLAYERINRANGE__BOOL_, RPC_SETFOLLOWOBJECT__SCENEOBJECT_, RPC_SETHOMELOCATION__FLOAT_FLOAT_FLOAT_SCENEOBJECT_, RPC_SETHOST__CREATUREOBJECT_, RPC_SETLEVEL__INT_, RPC_SETNEXTSTEPPOSITION__FLOAT_FLOAT_FLOAT_SCENEOBJECT_, RPC_SETOBLIVIOUS__, RPC_SETRESPAWNTIMER__FLOAT_, RPC_SETSHOWNEXTPOSITION__BOOL_, RPC_SETTARGETOBJECT__SCENEOBJECT_, RPC_UPDATELASTDAMAGERECEIVED__, scheduleDespawn(), sendConversationStartTo(), setCurrentMessage(), setDefender(), setDespawnOnNoPlayerInRange(), setFollowObject(), setHomeLocation(), setHost(), setLevel(), setNextStepPosition(), setOblivious(), setRespawnTimer(), setShowNextPosition(), setTargetObject(), and updateLastDamageReceived().
bool AiActorAdapter::isActorObject ()
Definition at line 2760 of file AiActor.cpp.
Referenced by invokeMethod().
bool AiActorAdapter::isAggressiveTo (CreatureObject * object)
Definition at line 2668 of file AiActor.cpp.
Referenced by invokeMethod().
bool AiActorAdapter::isAttackableBy (CreatureObject * object)
Definition at line 2664 of file AiActor.cpp.
Referenced by invokeMethod().
bool AiActorAdapter::isCamouflaged (CreatureObject * target)
Definition at line 2512 of file AiActor.cpp.
Referenced by invokeMethod().
bool AiActorAdapter::isConcealed (CreatureObject * target)
Definition at line 2520 of file AiActor.cpp.
Referenced by invokeMethod().
bool AiActorAdapter::isKiller ()
Definition at line 2720 of file AiActor.cpp.
Referenced by invokeMethod().
bool AiActorAdapter::isScentMasked (CreatureObject * target)
Definition at line 2516 of file AiActor.cpp.
Referenced by invokeMethod().
bool AiActorAdapter::isShowNextPosition ()
Definition at line 2552 of file AiActor.cpp.
Referenced by invokeMethod().
bool AiActorAdapter::isStalker ()
Definition at line 2716 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::next (unsigned short msg)
Definition at line 2480 of file AiActor.cpp.
void AiActorAdapter::next ()
Definition at line 2484 of file AiActor.cpp.
Referenced by invokeMethod().
int AiActorAdapter::notifyConverseObservers (CreatureObject * converser)
Definition at line 2632 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::notifyDespawn (Zone * zone)
Definition at line 2588 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::notifyDissapear (QuadTreeEntry * entry)
Definition at line 2628 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::notifyInsert (QuadTreeEntry * entry)
Definition at line 2624 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::notifyPositionUpdate (QuadTreeEntry * entry)
Definition at line 2472 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::queueDizzyFallEvent ()
Definition at line 2540 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::removeDefender (SceneObject * defender)
Definition at line 2660 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::respawn (Zone * zone, int level)
Definition at line 2596 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::scheduleDespawn (int timeToDespawn)
Definition at line 2592 of file AiActor.cpp.
void AiActorAdapter::scheduleDespawn ()
Definition at line 2600 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::sendConversationStartTo (SceneObject * player)
Definition at line 2676 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setCurrentMessage (unsigned short msg)
Definition at line 2476 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setDefender (SceneObject * defender)
Definition at line 2652 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setDespawnOnNoPlayerInRange (bool val)
Definition at line 2584 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setFollowObject (SceneObject * targ)
Definition at line 2640 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setHomeLocation (float x, float z, float y, SceneObject * cell)
Definition at line 2580 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setHost (CreatureObject * creo)
Definition at line 2456 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setLevel (int lvl)
Definition at line 2496 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setNextStepPosition (float x, float z, float y, SceneObject * cell)
Definition at line 2544 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setOblivious ()
Definition at line 2648 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setRespawnTimer (float resp)
Definition at line 2608 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setShowNextPosition (bool val)
Definition at line 2548 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::setTargetObject (SceneObject * obj)
Definition at line 2644 of file AiActor.cpp.
Referenced by invokeMethod().
void AiActorAdapter::updateLastDamageReceived ()
Definition at line 2672 of file AiActor.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/AiActor.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/AiActor.cpp