Core3: server::zone::ZoneServerAdapter Class Reference
server::zone::ZoneServerAdapter Class Reference
#include <ZoneServer.h>
Public Member Functions
ZoneServerAdapter (ZoneServer *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void initialize ()
void shutdown ()
void startManagers ()
void startZones ()
void stopManagers ()
void start (int p, int mconn)
void stop ()
void timedShutdown (int minutes)
void addTotalSentPacket (int count)
void addTotalResentPacket (int count)
void printInfo ()
String getInfo ()
void printEvents ()
Reference< SceneObject * > getObject (unsigned long long objectID, bool doLock)
Reference< SceneObject * > createObject (unsigned int templateCRC, const String &dbname, int persistenceLevel)
Reference< SceneObject * > createObject (unsigned int templateCRC, int persistenceLevel, unsigned long long objectID)
Reference< SceneObject * > createClientObject (unsigned int templateCRC, unsigned long long objectID)
void updateObjectToDatabase (SceneObject *object)
void updateObjectToStaticDatabase (SceneObject *object)
void destroyObjectFromDatabase (unsigned long long objectID)
void lock (bool doLock)
void unlock (bool doLock)
void fixScheduler ()
void changeUserCap (int amount)
int getConnectionCount ()
void increaseOnlinePlayers ()
void decreaseOnlinePlayers ()
void increaseTotalDeletedPlayers ()
int getGalaxyID ()
String getGalaxyName ()
void setGalaxyName (const String &name)
bool isServerLocked ()
bool isServerOnline ()
bool isServerOffline ()
bool isServerLoading ()
int getServerCap ()
int getServerState ()
Zone * getZone (const String &terrainName)
Zone * getZone (int idx)
int getZoneCount ()
int getMaxPlayers ()
int getTotalPlayers ()
int getDeletedPlayers ()
PlayerManager * getPlayerManager ()
ChatManager * getChatManager ()
CityManager * getCityManager ()
ObjectController * getObjectController ()
MissionManager * getMissionManager ()
RadialManager * getRadialManager ()
GuildManager * getGuildManager ()
ResourceManager * getResourceManager ()
CraftingManager * getCraftingManager ()
LootManager * getLootManager ()
AuctionManager * getAuctionManager ()
void setGalaxyID (int galaxyid)
void setServerState (int state)
void setServerStateLocked ()
void setServerStateOnline ()
void loadLoginMessage ()
void changeLoginMessage (const String &motd)
String getLoginMessage ()
Detailed Description
Definition at line 821 of file ZoneServer.h.
Constructor & Destructor Documentation
ZoneServerAdapter::ZoneServerAdapter (ZoneServer * impl)
Definition at line 1529 of file ZoneServer.cpp.
Member Function Documentation
void ZoneServerAdapter::addTotalResentPacket (int count)
Definition at line 1895 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::addTotalSentPacket (int count)
Definition at line 1891 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::changeLoginMessage (const String & motd)
Definition at line 2095 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::changeUserCap (int amount)
Definition at line 1951 of file ZoneServer.cpp.
Referenced by invokeMethod().
Reference< SceneObject * > ZoneServerAdapter::createClientObject (unsigned int templateCRC, unsigned long long objectID)
Definition at line 1923 of file ZoneServer.cpp.
Referenced by invokeMethod().
Reference< SceneObject * > ZoneServerAdapter::createObject (unsigned int templateCRC, const String & dbname, int persistenceLevel)
Definition at line 1915 of file ZoneServer.cpp.
Referenced by invokeMethod().
Reference< SceneObject * > ZoneServerAdapter::createObject (unsigned int templateCRC, int persistenceLevel, unsigned long long objectID)
Definition at line 1919 of file ZoneServer.cpp.
void ZoneServerAdapter::decreaseOnlinePlayers ()
Definition at line 1963 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::destroyObjectFromDatabase (unsigned long long objectID)
Definition at line 1935 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::fixScheduler ()
Definition at line 1947 of file ZoneServer.cpp.
Referenced by invokeMethod().
AuctionManager * ZoneServerAdapter::getAuctionManager ()
Definition at line 2071 of file ZoneServer.cpp.
Referenced by invokeMethod().
ChatManager * ZoneServerAdapter::getChatManager ()
Definition at line 2035 of file ZoneServer.cpp.
Referenced by invokeMethod().
CityManager * ZoneServerAdapter::getCityManager ()
Definition at line 2039 of file ZoneServer.cpp.
Referenced by invokeMethod().
int ZoneServerAdapter::getConnectionCount ()
Definition at line 1955 of file ZoneServer.cpp.
Referenced by invokeMethod().
CraftingManager * ZoneServerAdapter::getCraftingManager ()
Definition at line 2063 of file ZoneServer.cpp.
Referenced by invokeMethod().
int ZoneServerAdapter::getDeletedPlayers ()
Definition at line 2027 of file ZoneServer.cpp.
Referenced by invokeMethod().
int ZoneServerAdapter::getGalaxyID ()
Definition at line 1971 of file ZoneServer.cpp.
Referenced by invokeMethod().
String ZoneServerAdapter::getGalaxyName ()
Definition at line 1975 of file ZoneServer.cpp.
Referenced by invokeMethod().
GuildManager * ZoneServerAdapter::getGuildManager ()
Definition at line 2055 of file ZoneServer.cpp.
Referenced by invokeMethod().
String ZoneServerAdapter::getInfo ()
Definition at line 1903 of file ZoneServer.cpp.
Referenced by invokeMethod().
String ZoneServerAdapter::getLoginMessage ()
Definition at line 2099 of file ZoneServer.cpp.
Referenced by invokeMethod().
LootManager * ZoneServerAdapter::getLootManager ()
Definition at line 2067 of file ZoneServer.cpp.
Referenced by invokeMethod().
int ZoneServerAdapter::getMaxPlayers ()
Definition at line 2019 of file ZoneServer.cpp.
Referenced by invokeMethod().
MissionManager * ZoneServerAdapter::getMissionManager ()
Definition at line 2047 of file ZoneServer.cpp.
Referenced by invokeMethod().
Reference< SceneObject * > ZoneServerAdapter::getObject (unsigned long long objectID, bool doLock)
Definition at line 1911 of file ZoneServer.cpp.
Referenced by invokeMethod().
ObjectController * ZoneServerAdapter::getObjectController ()
Definition at line 2043 of file ZoneServer.cpp.
Referenced by invokeMethod().
PlayerManager * ZoneServerAdapter::getPlayerManager ()
Definition at line 2031 of file ZoneServer.cpp.
Referenced by invokeMethod().
RadialManager * ZoneServerAdapter::getRadialManager ()
Definition at line 2051 of file ZoneServer.cpp.
Referenced by invokeMethod().
ResourceManager * ZoneServerAdapter::getResourceManager ()
Definition at line 2059 of file ZoneServer.cpp.
Referenced by invokeMethod().
int ZoneServerAdapter::getServerCap ()
Definition at line 1999 of file ZoneServer.cpp.
Referenced by invokeMethod().
int ZoneServerAdapter::getServerState ()
Definition at line 2003 of file ZoneServer.cpp.
Referenced by invokeMethod().
int ZoneServerAdapter::getTotalPlayers ()
Definition at line 2023 of file ZoneServer.cpp.
Referenced by invokeMethod().
Zone * ZoneServerAdapter::getZone (const String & terrainName)
Definition at line 2007 of file ZoneServer.cpp.
References server::zone::objects::scene::SceneObject::getZone().
Referenced by invokeMethod().
Zone * ZoneServerAdapter::getZone (int idx)
Definition at line 2011 of file ZoneServer.cpp.
References server::zone::objects::scene::SceneObject::getZone().
int ZoneServerAdapter::getZoneCount ()
Definition at line 2015 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::increaseOnlinePlayers ()
Definition at line 1959 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::increaseTotalDeletedPlayers ()
Definition at line 1967 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::initialize ()
Definition at line 1859 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::initializeTransientMembers ()
Definition at line 1855 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1532 of file ZoneServer.cpp.
References addTotalResentPacket(), addTotalSentPacket(), changeLoginMessage(), changeUserCap(), createClientObject(), createObject(), decreaseOnlinePlayers(), destroyObjectFromDatabase(), fixScheduler(), getAuctionManager(), getChatManager(), getCityManager(), getConnectionCount(), getCraftingManager(), getDeletedPlayers(), getGalaxyID(), getGalaxyName(), getGuildManager(), getInfo(), getLoginMessage(), getLootManager(), getMaxPlayers(), getMissionManager(), getObject(), getObjectController(), getPlayerManager(), getRadialManager(), getResourceManager(), getServerCap(), getServerState(), getTotalPlayers(), getZone(), getZoneCount(), increaseOnlinePlayers(), increaseTotalDeletedPlayers(), initialize(), initializeTransientMembers(), isServerLoading(), isServerLocked(), isServerOffline(), isServerOnline(), loadLoginMessage(), lock(), printEvents(), printInfo(), RPC_ADDTOTALRESENTPACKET__INT_, RPC_ADDTOTALSENTPACKET__INT_, RPC_CHANGELOGINMESSAGE__STRING_, RPC_CHANGEUSERCAP__INT_, RPC_CREATECLIENTOBJECT__INT_LONG_, RPC_CREATEOBJECT__INT_INT_LONG_, RPC_CREATEOBJECT__INT_STRING_INT_, RPC_DECREASEONLINEPLAYERS__, RPC_DESTROYOBJECTFROMDATABASE__LONG_, RPC_FIXSCHEDULER__, RPC_GETAUCTIONMANAGER__, RPC_GETCHATMANAGER__, RPC_GETCITYMANAGER__, RPC_GETCONNECTIONCOUNT__, RPC_GETCRAFTINGMANAGER__, RPC_GETDELETEDPLAYERS__, RPC_GETGALAXYID__, RPC_GETGALAXYNAME__, RPC_GETGUILDMANAGER__, RPC_GETINFO__, RPC_GETLOGINMESSAGE__, RPC_GETLOOTMANAGER__, RPC_GETMAXPLAYERS__, RPC_GETMISSIONMANAGER__, RPC_GETOBJECT__LONG_BOOL_, RPC_GETOBJECTCONTROLLER__, RPC_GETPLAYERMANAGER__, RPC_GETRADIALMANAGER__, RPC_GETRESOURCEMANAGER__, RPC_GETSERVERCAP__, RPC_GETSERVERSTATE__, RPC_GETTOTALPLAYERS__, RPC_GETZONE__INT_, RPC_GETZONE__STRING_, RPC_GETZONECOUNT__, RPC_INCREASEONLINEPLAYERS__, RPC_INCREASETOTALDELETEDPLAYERS__, RPC_INITIALIZE__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_ISSERVERLOADING__, RPC_ISSERVERLOCKED__, RPC_ISSERVEROFFLINE__, RPC_ISSERVERONLINE__, RPC_LOADLOGINMESSAGE__, RPC_LOCK__BOOL_, RPC_PRINTEVENTS__, RPC_PRINTINFO__, RPC_SETGALAXYID__INT_, RPC_SETGALAXYNAME__STRING_, RPC_SETSERVERSTATE__INT_, RPC_SETSERVERSTATELOCKED__, RPC_SETSERVERSTATEONLINE__, RPC_SHUTDOWN__, RPC_START__INT_INT_, RPC_STARTMANAGERS__, RPC_STARTZONES__, RPC_STOP__, RPC_STOPMANAGERS__, RPC_TIMEDSHUTDOWN__INT_, RPC_UNLOCK__BOOL_, RPC_UPDATEOBJECTTODATABASE__SCENEOBJECT_, RPC_UPDATEOBJECTTOSTATICDATABASE__SCENEOBJECT_, setGalaxyID(), setGalaxyName(), setServerState(), setServerStateLocked(), setServerStateOnline(), shutdown(), start(), startManagers(), startZones(), stop(), stopManagers(), timedShutdown(), unlock(), updateObjectToDatabase(), and updateObjectToStaticDatabase().
bool ZoneServerAdapter::isServerLoading ()
Definition at line 1995 of file ZoneServer.cpp.
Referenced by invokeMethod().
bool ZoneServerAdapter::isServerLocked ()
Definition at line 1983 of file ZoneServer.cpp.
Referenced by invokeMethod().
bool ZoneServerAdapter::isServerOffline ()
Definition at line 1991 of file ZoneServer.cpp.
Referenced by invokeMethod().
bool ZoneServerAdapter::isServerOnline ()
Definition at line 1987 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::loadLoginMessage ()
Definition at line 2091 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::lock (bool doLock)
Definition at line 1939 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::printEvents ()
Definition at line 1907 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::printInfo ()
Definition at line 1899 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::setGalaxyID (int galaxyid)
Definition at line 2075 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::setGalaxyName (const String & name)
Definition at line 1979 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::setServerState (int state)
Definition at line 2079 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::setServerStateLocked ()
Definition at line 2083 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::setServerStateOnline ()
Definition at line 2087 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::shutdown ()
Definition at line 1863 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::start (int p, int mconn)
Definition at line 1879 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::startManagers ()
Definition at line 1867 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::startZones ()
Definition at line 1871 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::stop ()
Definition at line 1883 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::stopManagers ()
Definition at line 1875 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::timedShutdown (int minutes)
Definition at line 1887 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::unlock (bool doLock)
Definition at line 1943 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::updateObjectToDatabase (SceneObject * object)
Definition at line 1927 of file ZoneServer.cpp.
Referenced by invokeMethod().
void ZoneServerAdapter::updateObjectToStaticDatabase (SceneObject * object)
Definition at line 1931 of file ZoneServer.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneServer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneServer.cpp