Core3: server::zone::objects::player::sessions::TrainerConversationSessionAdapter Class Reference
server::zone::objects::player::sessions::TrainerConversationSessionAdapter Class Reference
#include <TrainerConversationSession.h>
Public Member Functions
TrainerConversationSessionAdapter (TrainerConversationSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void clearTrainableSkills ()
void addTrainableSkill (String &skillName)
String getTrainableSkills (int selectedOption)
int getTrainableSkillsCount ()
void clearNextSkills ()
void addNextSkill (String &skillName)
String getNextSkill (int selectedOption)
int getNextSkillsCount ()
void setSelectedSkill (String &skillName)
String getSelectedSkill ()
String getMasterSkill ()
void setMasterSkill (String &skillName)
void addAdditionalMasterSkill (String &skillName)
String getAdditionalMasterSkill (int selectedOption)
int getAdditionalMasterSkillsCount ()
Public Member Functions inherited from server::zone::objects::player::sessions::ConversationSessionAdapter
ConversationSessionAdapter (ConversationSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
ManagedWeakReference
< CreatureObject * > getNPC ()
Detailed Description
Definition at line 184 of file TrainerConversationSession.h.
Constructor & Destructor Documentation
TrainerConversationSessionAdapter::TrainerConversationSessionAdapter (TrainerConversationSession * impl)
Definition at line 513 of file TrainerConversationSession.cpp.
Member Function Documentation
void TrainerConversationSessionAdapter::addAdditionalMasterSkill (String & skillName)
Definition at line 653 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
void TrainerConversationSessionAdapter::addNextSkill (String & skillName)
Definition at line 625 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
void TrainerConversationSessionAdapter::addTrainableSkill (String & skillName)
Definition at line 609 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
void TrainerConversationSessionAdapter::clearNextSkills ()
Definition at line 621 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
void TrainerConversationSessionAdapter::clearTrainableSkills ()
Definition at line 605 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
String TrainerConversationSessionAdapter::getAdditionalMasterSkill (int selectedOption)
Definition at line 657 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
int TrainerConversationSessionAdapter::getAdditionalMasterSkillsCount ()
Definition at line 661 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
String TrainerConversationSessionAdapter::getMasterSkill ()
Definition at line 645 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
String TrainerConversationSessionAdapter::getNextSkill (int selectedOption)
Definition at line 629 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
int TrainerConversationSessionAdapter::getNextSkillsCount ()
Definition at line 633 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
String TrainerConversationSessionAdapter::getSelectedSkill ()
Definition at line 641 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
String TrainerConversationSessionAdapter::getTrainableSkills (int selectedOption)
Definition at line 613 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
int TrainerConversationSessionAdapter::getTrainableSkillsCount ()
Definition at line 617 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
void TrainerConversationSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 516 of file TrainerConversationSession.cpp.
References addAdditionalMasterSkill(), addNextSkill(), addTrainableSkill(), clearNextSkills(), clearTrainableSkills(), getAdditionalMasterSkill(), getAdditionalMasterSkillsCount(), getMasterSkill(), getNextSkill(), getNextSkillsCount(), getSelectedSkill(), getTrainableSkills(), getTrainableSkillsCount(), RPC_ADDADDITIONALMASTERSKILL__STRING_, RPC_ADDNEXTSKILL__STRING_, RPC_ADDTRAINABLESKILL__STRING_, RPC_CLEARNEXTSKILLS__, RPC_CLEARTRAINABLESKILLS__, RPC_GETADDITIONALMASTERSKILL__INT_, RPC_GETADDITIONALMASTERSKILLSCOUNT__, RPC_GETMASTERSKILL__, RPC_GETNEXTSKILL__INT_, RPC_GETNEXTSKILLSCOUNT__, RPC_GETSELECTEDSKILL__, RPC_GETTRAINABLESKILLS__INT_, RPC_GETTRAINABLESKILLSCOUNT__, RPC_SETMASTERSKILL__STRING_, RPC_SETSELECTEDSKILL__STRING_, setMasterSkill(), and setSelectedSkill().
void TrainerConversationSessionAdapter::setMasterSkill (String & skillName)
Definition at line 649 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
void TrainerConversationSessionAdapter::setSelectedSkill (String & skillName)
Definition at line 637 of file TrainerConversationSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TrainerConversationSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/TrainerConversationSession.cpp