Core3: StartMusicCommand Class Reference
StartMusicCommand Class Reference
#include <StartMusicCommand.h>
Public Member Functions
StartMusicCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Static Public Member Functions
static void startMusic (CreatureObject *creature, const String &song, const String &instrumentAnimation, int intid, bool targetInstrument=false)
static void sendAvailableSongs (CreatureObject *player, PlayerObject *ghost, uint32 suiType=SuiWindowType::MUSIC_START)
Detailed Description
Definition at line 58 of file StartMusicCommand.h.
Constructor & Destructor Documentation
StartMusicCommand::StartMusicCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 61 of file StartMusicCommand.h.
Member Function Documentation
int StartMusicCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 112 of file StartMusicCommand.h.
References SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::group::GroupObject::getBandSong(), server::zone::objects::scene::SceneObject::getDirection(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::objects::creature::CreatureObject::getGroup(), PerformanceManager::getInstrument(), PerformanceManager::getInstrumentAnimation(), PerformanceManager::getInstrumentId(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getParentID(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::creature::CreatureObject::getTargetID(), server::zone::objects::scene::SceneObject::getZoneServer(), PerformanceManager::hasInstrumentId(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), sendAvailableSongs(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), startMusic(), and server::zone::objects::player::sessions::EntertainingSession::stopDancing().
static void StartMusicCommand::sendAvailableSongs (CreatureObject * player, PlayerObject * ghost, uint32 suiType = SuiWindowType::MUSIC_START) inline static
Definition at line 83 of file StartMusicCommand.h.
References server::zone::objects::player::PlayerObject::addSuiBox(), server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::player::PlayerObject::getAbilityList(), Ability::getAbilityName(), server::zone::objects::creature::CreatureObject::sendMessage(), and server::zone::objects::scene::variables::DeltaVector< E >::size().
Referenced by StartBandCommand::doQueueCommand(), ChangeMusicCommand::doQueueCommand(), ChangeBandMusicCommand::doQueueCommand(), and doQueueCommand().
static void StartMusicCommand::startMusic (CreatureObject * creature, const String & song, const String & instrumentAnimation, int intid, bool targetInstrument = false) inline static
Definition at line 66 of file StartMusicCommand.h.
References server::zone::objects::scene::SceneObject::addActiveSession(), SessionFacadeType::ENTERTAINING, and server::zone::objects::scene::SceneObject::getActiveSession().
Referenced by StartBandCommand::doQueueCommand(), and doQueueCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/StartMusicCommand.h