Core3: server::zone::objects::player::sessions::survey::SurveySession Class Reference
server::zone::objects::player::sessions::survey::SurveySession Class Reference
#include <SurveySession.h>
Public Member Functions
SurveySession (CreatureObject *creature)
int initializeSession (SurveyTool *tool)
int cancelSession ()
int clearSession ()
void startSurvey (const String &resname)
void reSample ()
void startSample (const String &resname)
void surveyCnodeMinigame (int value)
void surveyGnodeMinigame (int value)
ManagedWeakReference
< SurveyTool * > getActiveSurveyTool ()
void setActiveSurveyTool (SurveyTool *tool)
ManagedWeakReference
< SurveyTool * > getOpenSurveyTool ()
void setOpenSurveyTool (SurveyTool *tool)
bool tryGamble ()
void clearGamble ()
Coordinate * getRichSampleLocation ()
void clearRichSampleLocation ()
void rescheduleSurvey (SurveyMessage *surveyMessage, WaypointObject *waypoint, float maxDensity, ResourceSpawn *resourceSpawn)
void rescheduleSample ()
void rescheduleSampleResults (ResourceSpawner *resourceSpawner, float density, const String &resname)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
SurveySession (DummyConstructorParameter *param)
virtual ~SurveySession ()
Friends
class SurveySessionHelper
Detailed Description
Definition at line 147 of file SurveySession.h.
Constructor & Destructor Documentation
SurveySession::SurveySession (CreatureObject * creature)
Definition at line 29 of file SurveySession.cpp.
References server::zone::objects::player::sessions::survey::SurveySessionImplementation::_setStub().
SurveySession::SurveySession (DummyConstructorParameter * param) protected
Definition at line 36 of file SurveySession.cpp.
SurveySession::~SurveySession () protected virtual
Definition at line 40 of file SurveySession.cpp.
Member Function Documentation
DistributedObjectServant * SurveySession::_getImplementation ()
Definition at line 283 of file SurveySession.cpp.
Referenced by cancelSession(), clearGamble(), clearRichSampleLocation(), clearSession(), getActiveSurveyTool(), getOpenSurveyTool(), getRichSampleLocation(), initializeSession(), reSample(), rescheduleSample(), rescheduleSampleResults(), rescheduleSurvey(), setActiveSurveyTool(), setOpenSurveyTool(), startSample(), startSurvey(), surveyCnodeMinigame(), surveyGnodeMinigame(), and tryGamble().
DistributedObjectServant * SurveySession::_getImplementationForRead ()
Definition at line 289 of file SurveySession.cpp.
void SurveySession::_setImplementation (DistributedObjectServant * servant)
Definition at line 293 of file SurveySession.cpp.
int SurveySession::cancelSession ()
Definition at line 59 of file SurveySession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::survey::SurveySessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
void SurveySession::clearGamble ()
Definition at line 221 of file SurveySession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::survey::SurveySessionImplementation::clearGamble(), and RPC_CLEARGAMBLE__.
void SurveySession::clearRichSampleLocation ()
Definition at line 243 of file SurveySession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::survey::SurveySessionImplementation::clearRichSampleLocation(), and RPC_CLEARRICHSAMPLELOCATION__.
int SurveySession::clearSession ()
Definition at line 72 of file SurveySession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::survey::SurveySessionImplementation::clearSession(), and RPC_CLEARSESSION__.
ManagedWeakReference< SurveyTool * > SurveySession::getActiveSurveyTool ()
Definition at line 154 of file SurveySession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::survey::SurveySessionImplementation::getActiveSurveyTool(), and RPC_GETACTIVESURVEYTOOL__.
Referenced by ResourceSpawner::sendSample(), ResourceSpawner::sendSampleResults(), and ResourceSpawner::sendSurvey().
ManagedWeakReference< SurveyTool * > SurveySession::getOpenSurveyTool ()
Definition at line 181 of file SurveySession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::survey::SurveySessionImplementation::getOpenSurveyTool(), and RPC_GETOPENSURVEYTOOL__.
Coordinate * SurveySession::getRichSampleLocation ()
Definition at line 234 of file SurveySession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::survey::SurveySessionImplementation::getRichSampleLocation().
int SurveySession::initializeSession (SurveyTool * tool)
Definition at line 45 of file SurveySession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::survey::SurveySessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__SURVEYTOOL_.
void SurveySession::reSample ()
Definition at line 99 of file SurveySession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::survey::SurveySessionImplementation::reSample(), and RPC_RESAMPLE__.
Referenced by SampleTask::run().
void SurveySession::rescheduleSample ()
Definition at line 265 of file SurveySession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::survey::SurveySessionImplementation::rescheduleSample().
void SurveySession::rescheduleSampleResults (ResourceSpawner * resourceSpawner, float density, const String & resname)
Definition at line 274 of file SurveySession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::survey::SurveySessionImplementation::rescheduleSampleResults().
void SurveySession::rescheduleSurvey (SurveyMessage * surveyMessage, WaypointObject * waypoint, float maxDensity, ResourceSpawn * resourceSpawn)
Definition at line 256 of file SurveySession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::survey::SurveySessionImplementation::rescheduleSurvey().
void SurveySession::setActiveSurveyTool (SurveyTool * tool)
Definition at line 167 of file SurveySession.cpp.
References _getImplementation(), RPC_SETACTIVESURVEYTOOL__SURVEYTOOL_, and server::zone::objects::player::sessions::survey::SurveySessionImplementation::setActiveSurveyTool().
void SurveySession::setOpenSurveyTool (SurveyTool * tool)
Definition at line 194 of file SurveySession.cpp.
References _getImplementation(), RPC_SETOPENSURVEYTOOL__SURVEYTOOL_, and server::zone::objects::player::sessions::survey::SurveySessionImplementation::setOpenSurveyTool().
void SurveySession::startSample (const String & resname)
Definition at line 112 of file SurveySession.cpp.
References _getImplementation(), RPC_STARTSAMPLE__STRING_, and server::zone::objects::player::sessions::survey::SurveySessionImplementation::startSample().
void SurveySession::startSurvey (const String & resname)
Definition at line 85 of file SurveySession.cpp.
References _getImplementation(), RPC_STARTSURVEY__STRING_, and server::zone::objects::player::sessions::survey::SurveySessionImplementation::startSurvey().
void SurveySession::surveyCnodeMinigame (int value)
Definition at line 126 of file SurveySession.cpp.
References _getImplementation(), RPC_SURVEYCNODEMINIGAME__INT_, and server::zone::objects::player::sessions::survey::SurveySessionImplementation::surveyCnodeMinigame().
Referenced by SurveyCMinigameSuiCallback::run().
void SurveySession::surveyGnodeMinigame (int value)
Definition at line 140 of file SurveySession.cpp.
References _getImplementation(), RPC_SURVEYGNODEMINIGAME__INT_, and server::zone::objects::player::sessions::survey::SurveySessionImplementation::surveyGnodeMinigame().
Referenced by SurveyGMinigameSuiCallback::run().
bool SurveySession::tryGamble ()
Definition at line 208 of file SurveySession.cpp.
References _getImplementation(), RPC_TRYGAMBLE__, and server::zone::objects::player::sessions::survey::SurveySessionImplementation::tryGamble().
Friends And Related Function Documentation
friend class SurveySessionHelper friend
Definition at line 199 of file SurveySession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/survey/SurveySession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/survey/SurveySession.cpp