Core3: DataTableRow Class Reference
DataTableRow Class Reference
#include <DataTableRow.h>
Public Member Functions
DataTableRow ()
~DataTableRow ()
void addCell (DataTableCell *c)
DataTableCell * getCell (int idx)
int getCellsSize ()
template<typename V >
void getValue (int idx, V &out)
Private Attributes
Vector< DataTableCell * > cells
Detailed Description
Definition at line 14 of file DataTableRow.h.
Constructor & Destructor Documentation
DataTableRow::DataTableRow () inline
Definition at line 18 of file DataTableRow.h.
DataTableRow::~DataTableRow () inline
Definition at line 22 of file DataTableRow.h.
References cells.
Member Function Documentation
void DataTableRow::addCell (DataTableCell * c) inline
Definition at line 31 of file DataTableRow.h.
References cells.
Referenced by DataTableIff::readObject().
DataTableCell* DataTableRow::getCell (int idx) inline
Definition at line 35 of file DataTableRow.h.
References cells.
Referenced by ResourceTree::buildTreeFromClient(), DataTableIff::getRowsByColumn(), server::zone::managers::player::PlayerManagerImplementation::loadBadgeMap(), ImageDesignManager::loadCustomizationData(), SchematicMap::loadSchematicGroups(), and server::zone::managers::planet::PlanetManagerImplementation::loadTravelFares().
int DataTableRow::getCellsSize () inline
Definition at line 39 of file DataTableRow.h.
References cells.
Referenced by StartingLocation::parseFromDataTableRow().
template<typename V > void DataTableRow::getValue (int idx, V & out) inline
Definition at line 44 of file DataTableRow.h.
References cells.
Referenced by ResourceTree::buildTreeFromClient(), CustomizationIdManager::loadAllowBald(), server::zone::managers::planet::PlanetManagerImplementation::loadClientRegions(), server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), CreaturePosture::loadMovementData(), server::zone::managers::player::creation::PlayerCreationManager::loadProfessionDefaultsInfo(), server::zone::managers::player::creation::PlayerCreationManager::loadRacialCreationData(), CreatureState::loadStateData(), server::zone::managers::skill::SkillManager::loadXpLimits(), server::zone::managers::player::creation::RacialCreationData::parseAttributeData(), Skill::parseDataTableRow(), Performance::parseDataTableRow(), SkillInfo::parseFromDataTableRow(), PlanetMapCategory::parseFromDataTableRow(), StartingLocation::parseFromDataTableRow(), server::zone::managers::player::creation::RacialCreationData::parseRacialModData(), CustomizationData::parseRow(), PoiData::readObject(), HairAssetData::readObject(), PaletteData::readObject(), and FactionRank::readObject().
Member Data Documentation
Vector<DataTableCell*> DataTableRow::cells private
Definition at line 15 of file DataTableRow.h.
Referenced by addCell(), getCell(), getCellsSize(), getValue(), and ~DataTableRow().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/datatables/DataTableRow.h