Core3: server::zone::objects::player::EntertainingObserver Class Reference
server::zone::objects::player::EntertainingObserver Class Reference
#include <EntertainingObserver.h>
Public Member Functions
EntertainingObserver ()
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
EntertainingObserver (DummyConstructorParameter *param)
virtual ~EntertainingObserver ()
Friends
class EntertainingObserverHelper
Detailed Description
Definition at line 51 of file EntertainingObserver.h.
Constructor & Destructor Documentation
EntertainingObserver::EntertainingObserver ()
Definition at line 15 of file EntertainingObserver.cpp.
References server::zone::objects::player::EntertainingObserverImplementation::_setStub().
EntertainingObserver::EntertainingObserver (DummyConstructorParameter * param) protected
Definition at line 22 of file EntertainingObserver.cpp.
EntertainingObserver::~EntertainingObserver () protected virtual
Definition at line 26 of file EntertainingObserver.cpp.
Member Function Documentation
DistributedObjectServant * EntertainingObserver::_getImplementation ()
Definition at line 48 of file EntertainingObserver.cpp.
Referenced by notifyObserverEvent().
DistributedObjectServant * EntertainingObserver::_getImplementationForRead ()
Definition at line 54 of file EntertainingObserver.cpp.
void EntertainingObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 58 of file EntertainingObserver.cpp.
int EntertainingObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 31 of file EntertainingObserver.cpp.
References _getImplementation(), server::zone::objects::player::EntertainingObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class EntertainingObserverHelper friend
Definition at line 67 of file EntertainingObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/EntertainingObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/EntertainingObserver.cpp