Core3: server::zone::objects::tangible::TangibleObjectImplementation Class Reference
server::zone::objects::tangible::TangibleObjectImplementation Class Reference
#include <TangibleObject.h>
Public Member Functions
TangibleObjectImplementation ()
TangibleObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
virtual void addTemplateSkillMods (TangibleObject *targetObject)
virtual void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
virtual void removeSkillModsFrom (CreatureObject *creature)
virtual void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
virtual void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
virtual void removeAllSkillModsOfType (const int skillType, bool notifyClient=true)
virtual void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void sendBaselinesTo (SceneObject *player)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
virtual void setDefender (SceneObject *defender)
virtual void addDefender (SceneObject *defender)
virtual void removeDefender (SceneObject *defender)
virtual void removeDefenders ()
virtual void setCombatState ()
virtual void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
virtual void clearCombatState (bool clearDefenders=true)
bool hasDefender (SceneObject *defender)
virtual bool isAttackableBy (CreatureObject *object)
virtual bool isAggressiveTo (CreatureObject *object)
virtual bool isHealableBy (CreatureObject *object)
virtual void sendPvpStatusTo (CreatureObject *player)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
virtual int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
virtual void updateCraftingValues (CraftingValues *values, bool firstUpdate)
virtual int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
virtual bool isKiller ()
virtual bool isTicketCollector ()
virtual bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
virtual int getUseCount ()
virtual int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
virtual bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
virtual String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
virtual int getJunkDealerNeeded ()
void setJunkValue (int jValue)
virtual int getJunkValue ()
void setSerialNumber (const String &serial)
virtual void setLevel (int lev)
virtual String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
virtual String repairAttempt (int repairChance)
bool isBroken ()
virtual float getHitChance ()
void broadcastPvpStatusBitmask ()
operator const TangibleObject * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendTo (SceneObject *player, bool doClose)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
virtual void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
virtual int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
virtual void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< TangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Protected Member Functions
float getConditionReduction (float value)
virtual ~TangibleObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
bool targetable
float complexity
int volume
unsigned int faction
CustomizationVariables customizationVariables
float conditionDamage
int maxCondition
int useCount
short level
unsigned int optionsBitmask
unsigned int pvpStatusBitmask
byte unknownByte
String craftersName
int junkDealerNeeded
int junkValue
String objectSerial
Reference< ThreatMap * > threatMap
DeltaVector< ManagedReference
< SceneObject * > > defenderList
bool sliceable
bool sliced
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Friends
class TangibleObject
Detailed Description
Definition at line 550 of file TangibleObject.h.
Constructor & Destructor Documentation
TangibleObjectImplementation::TangibleObjectImplementation ()
Definition at line 1631 of file TangibleObject.cpp.
References _initializeImplementation(), and initializeMembers().
TangibleObjectImplementation::TangibleObjectImplementation (DummyConstructorParameter * param)
Definition at line 1289 of file TangibleObject.cpp.
References _initializeImplementation().
TangibleObjectImplementation::~TangibleObjectImplementation () protected virtual
Definition at line 1294 of file TangibleObject.cpp.
Member Function Documentation
DistributedObjectStub * TangibleObjectImplementation::_getStub ()
Definition at line 1314 of file TangibleObject.cpp.
References _this.
void TangibleObjectImplementation::_initializeImplementation () protected
Definition at line 1301 of file TangibleObject.cpp.
References _serializationHelperMethod(), and _this.
Referenced by TangibleObjectImplementation().
void TangibleObjectImplementation::_serializationHelperMethod () protected
Definition at line 1350 of file TangibleObject.cpp.
Referenced by _initializeImplementation(), server::zone::objects::tangible::tool::ToolTangibleObjectImplementation::_serializationHelperMethod(), server::zone::objects::tangible::sign::SignObjectImplementation::_serializationHelperMethod(), server::zone::objects::tangible::terminal::TerminalImplementation::_serializationHelperMethod(), server::zone::objects::tangible::fishing::FishingBaitObjectImplementation::_serializationHelperMethod(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::_serializationHelperMethod(), server::zone::objects::tangible::loot::LootkitObjectImplementation::_serializationHelperMethod(), server::zone::objects::tangible::deed::DeedImplementation::_serializationHelperMethod(), server::zone::objects::tangible::tool::repair::RepairToolImplementation::_serializationHelperMethod(), server::zone::objects::tangible::firework::FireworkObjectImplementation::_serializationHelperMethod(), server::zone::objects::tangible::wearables::WearableObjectImplementation::_serializationHelperMethod(), server::zone::objects::tangible::ContainerImplementation::_serializationHelperMethod(), server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::_serializationHelperMethod(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::_serializationHelperMethod(), server::zone::objects::tangible::fishing::FishObjectImplementation::_serializationHelperMethod(), server::zone::objects::tangible::ticket::TicketObjectImplementation::_serializationHelperMethod(), server::zone::objects::tangible::attachement::AttachmentImplementation::_serializationHelperMethod(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::_serializationHelperMethod(), server::zone::objects::tangible::component::ComponentImplementation::_serializationHelperMethod(), server::zone::objects::tangible::InstrumentImplementation::_serializationHelperMethod(), server::zone::objects::tangible::consumable::ConsumableImplementation::_serializationHelperMethod(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::_serializationHelperMethod().
void TangibleObjectImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 1309 of file TangibleObject.cpp.
References _this.
Referenced by server::zone::objects::tangible::tool::ToolTangibleObjectImplementation::_setStub(), server::zone::objects::tangible::sign::SignObjectImplementation::_setStub(), server::zone::objects::tangible::terminal::TerminalImplementation::_setStub(), server::zone::objects::tangible::fishing::FishingBaitObjectImplementation::_setStub(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::_setStub(), server::zone::objects::tangible::deed::DeedImplementation::_setStub(), server::zone::objects::tangible::loot::LootkitObjectImplementation::_setStub(), server::zone::objects::tangible::tool::repair::RepairToolImplementation::_setStub(), server::zone::objects::tangible::firework::FireworkObjectImplementation::_setStub(), server::zone::objects::tangible::wearables::WearableObjectImplementation::_setStub(), server::zone::objects::tangible::ContainerImplementation::_setStub(), server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::_setStub(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::_setStub(), server::zone::objects::tangible::fishing::FishObjectImplementation::_setStub(), server::zone::objects::tangible::ticket::TicketObjectImplementation::_setStub(), server::zone::objects::tangible::attachement::AttachmentImplementation::_setStub(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::_setStub(), server::zone::objects::tangible::component::ComponentImplementation::_setStub(), server::zone::objects::tangible::InstrumentImplementation::_setStub(), server::zone::objects::tangible::consumable::ConsumableImplementation::_setStub(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::_setStub(), and server::zone::objects::tangible::TangibleObject::TangibleObject().
void TangibleObjectImplementation::addDefender (SceneObject * defender) virtual
Adds a SceneObject to the defender vector
Precondition
{ this object is locked }
Postcondition
{ this object is locked, defender is in the defender vector }
Parameters
defender SceneObject to add to the defender vector
Reimplemented in server::zone::objects::creature::AiAgentImplementation, and server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 242 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::scene::variables::DeltaVector< E >::add(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), ObserverEventType::DEFENDERADDED, defenderList, server::zone::objects::scene::variables::DeltaVector< E >::get(), setCombatState(), server::zone::objects::scene::variables::DeltaVector< E >::size(), and DeltaMessage::startUpdate().
Referenced by server::zone::objects::tangible::TangibleObject::addDefender(), server::zone::objects::creature::AiAgentImplementation::addDefender(), and setDefender().
void TangibleObjectImplementation::addSkillMod (const int skillType, const String & skillMod, int value, bool notifyClient = true) virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::tangible::wearables::WearableObjectImplementation, and server::zone::objects::tangible::wearables::WearableContainerObjectImplementation.
Definition at line 1674 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::addSkillMod().
void TangibleObjectImplementation::addTemplateSkillMods (TangibleObject * targetObject) virtual
Adds this object's skill mod map to the target object's skill mod map
Parameters
targetObject The targeted object containing the SkillModMap which will be affected.
Reimplemented in server::zone::objects::structure::StructureObjectImplementation.
Definition at line 624 of file TangibleObjectImplementation.cpp.
References server::zone::objects::tangible::TangibleObject::addSkillMod(), SharedTangibleObjectTemplate::getSkillMods(), and server::zone::objects::scene::SceneObjectImplementation::templateObject.
Referenced by server::zone::objects::tangible::TangibleObject::addTemplateSkillMods().
void TangibleObjectImplementation::applySkillModsTo (CreatureObject * creature, bool doCheck = true) virtual
Reimplemented in server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::tangible::wearables::WearableObjectImplementation, and server::zone::objects::tangible::wearables::WearableContainerObjectImplementation.
Definition at line 1668 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::applySkillModsTo().
void TangibleObjectImplementation::broadcastPvpStatusBitmask ()
Definition at line 148 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::getZone(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::tangible::TangibleObject::sendPvpStatusTo(), sendPvpStatusTo(), and server::zone::objects::scene::SceneObjectImplementation::zone.
Referenced by server::zone::objects::tangible::TangibleObject::broadcastPvpStatusBitmask(), and setPvpStatusBitmask().
bool TangibleObjectImplementation::canRepair (CreatureObject * player)
Definition at line 663 of file TangibleObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::error(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObjectImplementation::getGameObjectType(), server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::scene::SceneObjectImplementation::isASubChildOf().
Referenced by server::zone::objects::tangible::TangibleObject::canRepair().
void TangibleObjectImplementation::clearCombatState (bool clearDefenders = true) virtual
Cleares the combat state
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object is not in a combat state }
Parameters
clearDefenders if true the defender vector willl be emptied
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, and server::zone::objects::creature::AiAgentImplementation.
Definition at line 1686 of file TangibleObject.cpp.
References removeDefenders().
Referenced by server::zone::objects::tangible::TangibleObject::clearCombatState(), dropFromDefenderLists(), and removeDefender().
Reference< FactoryCrate * > TangibleObjectImplementation::createFactoryCrate (bool insertSelf = false)
Definition at line 567 of file TangibleObjectImplementation.cpp.
References _this, SceneObjectType::ARMOR, SceneObjectType::CHEMICAL, server::zone::managers::object::ObjectManager::cloneObject(), SceneObjectType::CLOTHING, server::zone::ZoneServer::createObject(), SceneObjectType::DRINK, SceneObjectType::ELECTRONICS, SceneObjectType::FOOD, SceneObjectType::FURNITURE, server::zone::objects::scene::SceneObjectImplementation::getCustomObjectName(), SharedTangibleObjectTemplate::getFactoryCrateSize(), server::zone::objects::scene::SceneObjectImplementation::getGameObjectType(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), SceneObjectType::INSTALLATION, SceneObjectType::PETMEDECINE, SceneObjectType::PHARMACEUTICAL, server::zone::objects::scene::SceneObjectImplementation::templateObject, and SceneObjectType::WEAPON.
Referenced by server::zone::objects::tangible::TangibleObject::createFactoryCrate().
void TangibleObjectImplementation::decreaseUseCount ()
Decreases use count, when reaches 0 destroys itself
Definition at line 404 of file TangibleObjectImplementation.cpp.
References setUseCount(), and useCount.
Referenced by server::zone::objects::tangible::TangibleObject::decreaseUseCount(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), and server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::useCharge().
void TangibleObjectImplementation::dropFromDefenderLists (TangibleObject * destructor)
Definition at line 495 of file TangibleObjectImplementation.cpp.
References _this, clearCombatState(), defenderList, and server::zone::objects::scene::variables::DeltaVector< E >::size().
Referenced by server::zone::objects::tangible::TangibleObject::dropFromDefenderLists(), and notifyObjectDestructionObservers().
void TangibleObjectImplementation::fillAttributeList (AttributeListMessage * msg, CreatureObject * object) virtual
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::tangible::tool::CraftingToolImplementation, server::zone::objects::tangible::wearables::ArmorObjectImplementation, server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation, server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, server::zone::objects::tangible::ticket::TicketObjectImplementation, server::zone::objects::tangible::tool::repair::RepairToolImplementation, server::zone::objects::tangible::wearables::WearableObjectImplementation, server::zone::objects::tangible::wearables::WearableContainerObjectImplementation, and server::zone::objects::tangible::wearables::PsgArmorObjectImplementation.
Definition at line 321 of file TangibleObjectImplementation.cpp.
References conditionDamage, craftersName, server::zone::packets::scene::AttributeListMessage::insertAttribute(), maxCondition, objectSerial, useCount, and volume.
Referenced by server::zone::objects::tangible::wearables::WearableContainerObjectImplementation::fillAttributeList(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::fillAttributeList(), server::zone::objects::tangible::fishing::FishingBaitObjectImplementation::fillAttributeList(), server::zone::objects::tangible::deed::DeedImplementation::fillAttributeList(), server::zone::objects::tangible::wearables::WearableObjectImplementation::fillAttributeList(), server::zone::objects::tangible::loot::LootkitObjectImplementation::fillAttributeList(), server::zone::objects::tangible::tool::repair::RepairToolImplementation::fillAttributeList(), server::zone::objects::tangible::component::ComponentImplementation::fillAttributeList(), server::zone::objects::tangible::fishing::FishObjectImplementation::fillAttributeList(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::fillAttributeList(), server::zone::objects::tangible::attachement::AttachmentImplementation::fillAttributeList(), server::zone::objects::tangible::tool::CraftingStationImplementation::fillAttributeList(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::fillAttributeList(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::fillAttributeList(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::fillAttributeList(), server::zone::objects::tangible::component::genetic::GeneticComponentImplementation::fillAttributeList(), server::zone::objects::tangible::tool::CraftingToolImplementation::fillAttributeList(), server::zone::objects::tangible::TangibleObject::fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::fillAttributeList().
void TangibleObjectImplementation::finalize () protected
Definition at line 1298 of file TangibleObject.cpp.
float TangibleObjectImplementation::getComplexity ()
Definition at line 1799 of file TangibleObject.cpp.
References complexity.
Referenced by server::zone::objects::tangible::TangibleObject::getComplexity(), and repair().
int TangibleObjectImplementation::getConditionDamage ()
Definition at line 1784 of file TangibleObject.cpp.
References conditionDamage.
Referenced by server::zone::objects::creature::VehicleObjectImplementation::calculateRepairCost(), server::zone::objects::tangible::TangibleObject::getConditionDamage(), getConditionReduction(), server::zone::objects::structure::StructureObjectImplementation::getDecayPercentage(), repair(), and server::zone::objects::creature::VehicleObjectImplementation::repairVehicle().
float TangibleObjectImplementation::getConditionReduction (float value) protected
Definition at line 1979 of file TangibleObject.cpp.
References getConditionDamage(), getMaxCondition(), and isBroken().
Referenced by server::zone::objects::tangible::wearables::ArmorObjectImplementation::getAcid(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getAttackSpeed(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::getBlast(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::getCold(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::getElectricity(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::getEnergy(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::getHeat(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::getKinetic(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::getLightSaber(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getMaxDamage(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getMinDamage(), and server::zone::objects::tangible::wearables::ArmorObjectImplementation::getStun().
String TangibleObjectImplementation::getCraftersName () virtual
Reimplemented in server::zone::objects::factorycrate::FactoryCrateImplementation.
Definition at line 1934 of file TangibleObject.cpp.
References craftersName.
Referenced by server::zone::objects::tangible::TangibleObject::getCraftersName().
void TangibleObjectImplementation::getCustomizationString (String & variables)
Definition at line 1824 of file TangibleObject.cpp.
References customizationVariables.
Referenced by server::zone::objects::tangible::TangibleObject::getCustomizationString().
CustomizationVariables * TangibleObjectImplementation::getCustomizationVariables ()
Definition at line 1761 of file TangibleObject.cpp.
References customizationVariables.
Referenced by server::zone::objects::tangible::TangibleObject::getCustomizationVariables().
DeltaVector< ManagedReference< SceneObject * > > * TangibleObjectImplementation::getDefenderList ()
Definition at line 1829 of file TangibleObject.cpp.
References defenderList.
Referenced by server::zone::objects::tangible::TangibleObject::getDefenderList().
int TangibleObjectImplementation::getDisplayedUseCount () virtual
Reimplemented in server::zone::objects::tangible::firework::FireworkObjectImplementation.
Definition at line 1771 of file TangibleObject.cpp.
References SceneObjectType::TRAP, and useCount.
Referenced by server::zone::objects::tangible::firework::FireworkObjectImplementation::getDisplayedUseCount(), and server::zone::objects::tangible::TangibleObject::getDisplayedUseCount().
unsigned int TangibleObjectImplementation::getFaction ()
Definition at line 1852 of file TangibleObject.cpp.
References faction.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::creature::AiAgentImplementation::isAggressiveTo(), server::zone::objects::creature::CreatureObjectImplementation::isAggressiveTo(), server::zone::objects::installation::InstallationObjectImplementation::isAttackableBy(), server::zone::objects::creature::AiAgentImplementation::isAttackableBy(), server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy(), and server::zone::objects::creature::CreatureObjectImplementation::isHealableBy().
float TangibleObjectImplementation::getHitChance () virtual
Reimplemented in server::zone::objects::installation::InstallationObjectImplementation.
Definition at line 1994 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::getHitChance().
int TangibleObjectImplementation::getJunkDealerNeeded () virtual
Definition at line 1944 of file TangibleObject.cpp.
References junkDealerNeeded.
Referenced by server::zone::objects::tangible::TangibleObject::getJunkDealerNeeded().
int TangibleObjectImplementation::getJunkValue () virtual
Definition at line 1954 of file TangibleObject.cpp.
References junkValue.
Referenced by server::zone::objects::tangible::TangibleObject::getJunkValue().
int TangibleObjectImplementation::getLevel ()
Definition at line 1809 of file TangibleObject.cpp.
References level.
Referenced by server::zone::objects::creature::CreatureImplementation::fillAttributeList(), server::zone::objects::tangible::TangibleObject::getLevel(), server::zone::objects::creature::AiAgentImplementation::isConcealed(), and server::zone::objects::creature::AiAgentImplementation::isScentMasked().
SceneObject * TangibleObjectImplementation::getMainDefender ()
Definition at line 1834 of file TangibleObject.cpp.
References defenderList.
Referenced by server::zone::objects::tangible::TangibleObject::getMainDefender().
int TangibleObjectImplementation::getMaxCondition ()
Definition at line 1779 of file TangibleObject.cpp.
References maxCondition.
Referenced by getConditionReduction(), server::zone::objects::structure::StructureObjectImplementation::getDecayPercentage(), server::zone::objects::tangible::TangibleObject::getMaxCondition(), isBroken(), repair(), server::zone::objects::tangible::wearables::WearableObjectImplementation::repairAttempt(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::repairAttempt().
unsigned int TangibleObjectImplementation::getOptionsBitmask ()
Definition at line 1804 of file TangibleObject.cpp.
References optionsBitmask.
Referenced by server::zone::objects::tangible::TangibleObject::getOptionsBitmask(), and setSerialNumber().
unsigned int TangibleObjectImplementation::getPvpStatusBitmask ()
Definition at line 1814 of file TangibleObject.cpp.
References pvpStatusBitmask.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), server::zone::objects::creature::AiAgentImplementation::isAggressiveTo(), server::zone::objects::installation::InstallationObjectImplementation::isAttackableBy(), and server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy().
String TangibleObjectImplementation::getSerialNumber () virtual
Reimplemented in server::zone::objects::factorycrate::FactoryCrateImplementation.
Definition at line 1964 of file TangibleObject.cpp.
References objectSerial.
Referenced by server::zone::objects::tangible::TangibleObject::getSerialNumber().
VectorMap< String, int > * TangibleObjectImplementation::getTemplateSkillMods ()
Definition at line 654 of file TangibleObjectImplementation.cpp.
References SharedTangibleObjectTemplate::getSkillMods(), and server::zone::objects::scene::SceneObjectImplementation::templateObject.
Referenced by server::zone::objects::tangible::TangibleObject::getTemplateSkillMods().
ThreatMap * TangibleObjectImplementation::getThreatMap ()
Definition at line 787 of file TangibleObjectImplementation.cpp.
References _this, and threatMap.
Referenced by server::zone::objects::creature::AiAgentImplementation::doAttack(), server::zone::objects::tangible::TangibleObject::getThreatMap(), inflictDamage(), server::zone::objects::creature::AiAgentImplementation::inflictDamage(), server::zone::objects::creature::CreatureObjectImplementation::inflictDamage(), and server::zone::objects::creature::AiAgentImplementation::removeDefender().
byte TangibleObjectImplementation::getUnknownByte ()
Definition at line 1741 of file TangibleObject.cpp.
References unknownByte.
Referenced by server::zone::objects::tangible::TangibleObject::getUnknownByte().
int TangibleObjectImplementation::getUseCount () virtual
Reimplemented in server::zone::objects::resource::ResourceContainerImplementation, and server::zone::objects::tangible::fishing::FishingBaitObjectImplementation.
Definition at line 1766 of file TangibleObject.cpp.
References useCount.
Referenced by server::zone::objects::tangible::firework::FireworkObjectImplementation::completeLaunch(), server::zone::objects::factorycrate::FactoryCrateImplementation::extractObject(), server::zone::objects::factorycrate::FactoryCrateImplementation::extractObjectToParent(), server::zone::objects::factorycrate::FactoryCrateImplementation::fillAttributeList(), server::zone::objects::tangible::fishing::FishingBaitObjectImplementation::getUseCount(), server::zone::objects::tangible::TangibleObject::getUseCount(), server::zone::objects::factorycrate::FactoryCrateImplementation::split(), and server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::useCharge().
int TangibleObjectImplementation::getVolume ()
Definition at line 1789 of file TangibleObject.cpp.
References volume.
Referenced by server::zone::objects::tangible::TangibleObject::getVolume().
bool TangibleObjectImplementation::hasDefender (SceneObject * defender)
Evaluates if this object contains the specified defender
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns true if SceneObject defender exists in the defender vector
Definition at line 1692 of file TangibleObject.cpp.
References defenderList.
Referenced by server::zone::objects::tangible::TangibleObject::hasDefender().
int TangibleObjectImplementation::healDamage (TangibleObject * healer, int damageType, float damageToHeal, bool notifyClient = true) virtual
Heals damage
Precondition
{ this, healer locked }
Postcondition
{ this, healer locked }
Returns
returns total health healed
Definition at line 505 of file TangibleObjectImplementation.cpp.
References conditionDamage, and setConditionDamage().
Referenced by server::zone::objects::tangible::TangibleObject::healDamage().
int TangibleObjectImplementation::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, bool notifyClient = true) virtual
Inflicts damage into the object
Precondition
{ attacker, this object is locked }
Postcondition
{ attacker, this object is locked }
Returns
unused for now
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::creature::AiAgentImplementation, and server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 440 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::tangible::threat::ThreatMap::addDamage(), conditionDamage, getThreatMap(), server::zone::objects::scene::SceneObject::isPlayerCreature(), maxCondition, notifyObjectDestructionObservers(), and setConditionDamage().
Referenced by server::zone::objects::tangible::weapon::WeaponObjectImplementation::decay(), and server::zone::objects::tangible::TangibleObject::inflictDamage().
int TangibleObjectImplementation::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, const String & xp, bool notifyClient = true) virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::creature::AiAgentImplementation, and server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 463 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::tangible::threat::ThreatMap::addDamage(), conditionDamage, getThreatMap(), server::zone::objects::scene::SceneObject::isPlayerCreature(), maxCondition, notifyObjectDestructionObservers(), and setConditionDamage().
void TangibleObjectImplementation::initializeMembers ()
Definition at line 1639 of file TangibleObject.cpp.
References complexity, conditionDamage, faction, junkDealerNeeded, junkValue, level, sliceable, sliced, threatMap, unknownByte, useCount, and volume.
Referenced by server::zone::objects::tangible::TangibleObject::initializeMembers(), and TangibleObjectImplementation().
void TangibleObjectImplementation::initializeTransientMembers ()
Initializes the transient members of SceneObject, must call the inherited object method first.
Precondition
{transient members are not initialized }
Postcondition
{ transient members are initialized }
Definition at line 78 of file TangibleObjectImplementation.cpp.
References faction, server::zone::objects::scene::SceneObjectImplementation::setLoggingName(), and threatMap.
Referenced by server::zone::objects::tangible::tool::ToolTangibleObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::consumable::DrinkImplementation::initializeTransientMembers(), server::zone::objects::tangible::consumable::FoodImplementation::initializeTransientMembers(), server::zone::objects::tangible::terminal::TerminalImplementation::initializeTransientMembers(), server::zone::objects::tangible::fishing::FishingBaitObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::deed::DeedImplementation::initializeTransientMembers(), server::zone::objects::tangible::loot::LootkitObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::wearables::WearableObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::ContainerImplementation::initializeTransientMembers(), server::zone::objects::tangible::ticket::TicketObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::firework::FireworkObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::fishing::FishObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::attachement::AttachmentImplementation::initializeTransientMembers(), server::zone::objects::tangible::component::ComponentImplementation::initializeTransientMembers(), server::zone::objects::tangible::TangibleObject::initializeTransientMembers(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::InstrumentImplementation::initializeTransientMembers(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::initializeTransientMembers(), server::zone::objects::tangible::sign::SignObjectImplementation::readObject(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::readObject(), server::zone::objects::tangible::tool::repair::RepairToolImplementation::readObject(), server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::readObject(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::readObject(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::readObject(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::readObject(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::readObject(), server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::readObject(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::readObject(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::readObject(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::readObject(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::readObject(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::readObject(), server::zone::objects::tangible::consumable::ConsumableImplementation::readObject(), and readObject().
bool TangibleObjectImplementation::isAggressiveTo (CreatureObject * object) virtual
Evaluates if this creature is aggresive to the object
Precondition
{ }
Postcondition
{ }
Returns
returns true if its aggressive
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, and server::zone::objects::creature::AiAgentImplementation.
Definition at line 1731 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::isAggressiveTo(), and sendPvpStatusTo().
bool TangibleObjectImplementation::isAttackableBy (CreatureObject * object) virtual
Evaluates if this object can be attacket by the passed creature object
Precondition
{ this object is locked }
Postcondition
{ this object is locked}
Returns
returns true if the creature object can attack this
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::creature::AiAgentImplementation, server::zone::objects::installation::InstallationObjectImplementation, server::zone::objects::creature::VehicleObjectImplementation, and server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation.
Definition at line 1706 of file TangibleObject.cpp.
References CreatureFlag::ATTACKABLE, isImperial(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::tangible::TangibleObject::isRebel(), isRebel(), and pvpStatusBitmask.
Referenced by server::zone::objects::tangible::TangibleObject::isAttackableBy(), and sendPvpStatusTo().
bool TangibleObjectImplementation::isBroken ()
Definition at line 1974 of file TangibleObject.cpp.
References getMaxCondition().
Referenced by getConditionReduction(), and server::zone::objects::tangible::TangibleObject::isBroken().
bool TangibleObjectImplementation::isDestroyed ()
Definition at line 1842 of file TangibleObject.cpp.
References conditionDamage, and maxCondition.
Referenced by server::zone::objects::creature::VehicleObjectImplementation::fillObjectMenuResponse(), server::zone::objects::creature::VehicleObjectImplementation::isAttackableBy(), server::zone::objects::tangible::TangibleObject::isDestroyed(), and server::zone::objects::creature::VehicleObjectImplementation::repairVehicle().
bool TangibleObjectImplementation::isHealableBy (CreatureObject * object) virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 1736 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::isHealableBy().
bool TangibleObjectImplementation::isImperial ()
Definition at line 1862 of file TangibleObject.cpp.
References faction.
Referenced by isAttackableBy(), and server::zone::objects::tangible::TangibleObject::isImperial().
bool TangibleObjectImplementation::isKiller () virtual
Reimplemented in server::zone::objects::creature::AiAgentImplementation.
Definition at line 1746 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::isKiller().
bool TangibleObjectImplementation::isNeutral ()
Definition at line 1867 of file TangibleObject.cpp.
References faction.
Referenced by server::zone::objects::tangible::TangibleObject::isNeutral().
bool TangibleObjectImplementation::isPharmaceuticalObject () virtual
Reimplemented in server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation.
Definition at line 1919 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::isPharmaceuticalObject().
bool TangibleObjectImplementation::isRebel ()
Definition at line 1857 of file TangibleObject.cpp.
References faction.
Referenced by isAttackableBy(), and server::zone::objects::tangible::TangibleObject::isRebel().
bool TangibleObjectImplementation::isSliceable ()
Definition at line 1872 of file TangibleObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::isArmorObject(), server::zone::objects::scene::SceneObjectImplementation::isContainerObject(), server::zone::objects::scene::SceneObjectImplementation::isMissionTerminal(), server::zone::objects::scene::SceneObjectImplementation::isSecurityTerminal(), server::zone::objects::scene::SceneObjectImplementation::isWeaponObject(), SceneObjectType::PLAYERLOOTCRATE, sliceable, and sliced.
Referenced by server::zone::objects::tangible::ContainerImplementation::fillObjectMenuResponse(), and server::zone::objects::tangible::TangibleObject::isSliceable().
bool TangibleObjectImplementation::isSliced ()
Definition at line 1904 of file TangibleObject.cpp.
References sliced.
Referenced by server::zone::objects::tangible::weapon::WeaponObjectImplementation::decay(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::handleObjectMenuSelect(), and server::zone::objects::tangible::TangibleObject::isSliced().
bool TangibleObjectImplementation::isTangibleObject () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 1819 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::isTangibleObject().
bool TangibleObjectImplementation::isTicketCollector () virtual
Reimplemented in server::zone::objects::tangible::terminal::ticketcollector::TicketCollectorImplementation.
Definition at line 1751 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::isTicketCollector().
bool TangibleObjectImplementation::isTicketObject () virtual
Reimplemented in server::zone::objects::tangible::ticket::TicketObjectImplementation.
Definition at line 1756 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::isTicketObject().
void TangibleObjectImplementation::loadTemplateData (SharedObjectTemplate * templateData) virtual
Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
Precondition
{ templateData is a valid pointer }
Postcondition
{ TangibleObject members are initialized }
Parameters
templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation, server::zone::objects::tangible::tool::CraftingToolImplementation, server::zone::objects::tangible::tool::recycle::RecycleToolImplementation, server::zone::objects::tangible::wearables::ArmorObjectImplementation, server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation, server::zone::objects::tangible::tool::SurveyToolImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation, server::zone::objects::tangible::tool::repair::RepairToolImplementation, server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation, and server::zone::objects::tangible::wearables::RobeObjectImplementation.
Definition at line 90 of file TangibleObjectImplementation.cpp.
References faction, SharedTangibleObjectTemplate::getFaction(), SharedTangibleObjectTemplate::getMaxCondition(), SharedTangibleObjectTemplate::getOptionsBitmask(), SharedTangibleObjectTemplate::getPvpStatusBitmask(), SharedTangibleObjectTemplate::getSliceable(), SharedTangibleObjectTemplate::getTargetable(), SharedTangibleObjectTemplate::getUseCount(), maxCondition, optionsBitmask, pvpStatusBitmask, sliceable, targetable, threatMap, and useCount.
Referenced by server::zone::objects::tangible::wearables::RobeObjectImplementation::loadTemplateData(), server::zone::objects::tangible::deed::DeedImplementation::loadTemplateData(), server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation::loadTemplateData(), server::zone::objects::tangible::ContainerImplementation::loadTemplateData(), server::zone::objects::tangible::loot::LootkitObjectImplementation::loadTemplateData(), server::zone::objects::tangible::tool::repair::RepairToolImplementation::loadTemplateData(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::loadTemplateData(), server::zone::objects::tangible::firework::FireworkObjectImplementation::loadTemplateData(), server::zone::objects::tangible::tool::CraftingStationImplementation::loadTemplateData(), server::zone::objects::tangible::attachement::AttachmentImplementation::loadTemplateData(), server::zone::objects::tangible::tool::SurveyToolImplementation::loadTemplateData(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::loadTemplateData(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::loadTemplateData(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::loadTemplateData(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::loadTemplateData(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::loadTemplateData(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::loadTemplateData(), server::zone::objects::tangible::TangibleObject::loadTemplateData(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::loadTemplateData(), server::zone::objects::tangible::InstrumentImplementation::loadTemplateData(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::loadTemplateData(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::loadTemplateData(), server::zone::objects::tangible::tool::CraftingToolImplementation::loadTemplateData(), server::zone::objects::tangible::consumable::ConsumableImplementation::loadTemplateData(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::loadTemplateData(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::loadTemplateData().
void TangibleObjectImplementation::lock (bool doLock = true) protected
Definition at line 1322 of file TangibleObject.cpp.
References _this.
void TangibleObjectImplementation::lock (ManagedObject * obj) protected
Definition at line 1326 of file TangibleObject.cpp.
References _this.
int TangibleObjectImplementation::notifyObjectDestructionObservers (TangibleObject * attacker, int condition) virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::creature::AiAgentImplementation, and server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 484 of file TangibleObjectImplementation.cpp.
References dropFromDefenderLists(), ObserverEventType::OBJECTDESTRUCTION, and threatMap.
Referenced by inflictDamage(), and server::zone::objects::tangible::TangibleObject::notifyObjectDestructionObservers().
TangibleObjectImplementation::operator const TangibleObject * ()
Definition at line 1318 of file TangibleObject.cpp.
void TangibleObjectImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::creature::AiAgentImplementation, server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::structure::StructureObjectImplementation, server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation, server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::installation::InstallationObjectImplementation, server::zone::objects::creature::VehicleObjectImplementation, server::zone::objects::tangible::component::dna::DnaComponentImplementation, server::zone::objects::tangible::wearables::ArmorObjectImplementation, server::zone::objects::tangible::tool::CraftingToolImplementation, server::zone::objects::tangible::consumable::ConsumableImplementation, server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation, server::zone::objects::creature::CreatureImplementation, server::zone::objects::tangible::pharmaceutical::DotPackImplementation, server::zone::objects::tangible::InstrumentImplementation, server::zone::objects::tangible::tool::recycle::RecycleToolImplementation, server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation, server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation, server::zone::objects::installation::factory::FactoryObjectImplementation, server::zone::objects::tangible::component::genetic::GeneticComponentImplementation, server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation, server::zone::objects::tangible::pharmaceutical::WoundPackImplementation, server::zone::objects::factorycrate::FactoryCrateImplementation, server::zone::objects::tangible::pharmaceutical::CurePackImplementation, server::zone::objects::tangible::pharmaceutical::RevivePackImplementation, server::zone::objects::tangible::pharmaceutical::StimPackImplementation, server::zone::objects::tangible::tool::SurveyToolImplementation, server::zone::objects::tangible::pharmaceutical::StatePackImplementation, server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation, server::zone::objects::tangible::component::ComponentImplementation, server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, server::zone::objects::resource::ResourceContainerImplementation, server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation, server::zone::objects::tangible::attachement::AttachmentImplementation, server::zone::objects::tangible::ticket::TicketObjectImplementation, server::zone::objects::tangible::fishing::FishingPoleObjectImplementation, server::zone::objects::tangible::fishing::FishObjectImplementation, server::zone::objects::installation::shuttle::ShuttleInstallationImplementation, server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation, server::zone::objects::tangible::ContainerImplementation, server::zone::objects::tangible::wearables::WearableObjectImplementation, server::zone::objects::tangible::firework::FireworkObjectImplementation, server::zone::objects::tangible::deed::pet::PetDeedImplementation, server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation, server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation, server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation, server::zone::objects::tangible::tool::repair::RepairToolImplementation, server::zone::objects::tangible::deed::ResourceDeedImplementation, server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation, server::zone::objects::installation::harvester::HarvesterObjectImplementation, server::zone::objects::tangible::deed::structure::StructureDeedImplementation, server::zone::objects::tangible::deed::DeedImplementation, server::zone::objects::tangible::loot::LootkitObjectImplementation, server::zone::objects::tangible::component::armor::ArmorComponentImplementation, server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation, server::zone::objects::installation::GeneratorObjectImplementation, server::zone::objects::tangible::terminal::ticketcollector::TicketCollectorImplementation, server::zone::objects::tangible::powerup::PowerupObjectImplementation, server::zone::objects::tangible::fishing::FishingBaitObjectImplementation, server::zone::objects::tangible::wearables::WearableContainerObjectImplementation, server::zone::objects::tangible::terminal::startinglocation::StartingLocationTerminalImplementation, server::zone::objects::tangible::terminal::TerminalImplementation, server::zone::objects::tangible::sign::SignObjectImplementation, server::zone::objects::creature::NonPlayerCreatureObjectImplementation, server::zone::objects::tangible::wearables::RobeObjectImplementation, server::zone::objects::tangible::wearables::PsgArmorObjectImplementation, server::zone::objects::tangible::wearables::ClothingObjectImplementation, server::zone::objects::building::hospital::HospitalBuildingObjectImplementation, server::zone::objects::building::recreation::RecreationBuildingObjectImplementation, server::zone::objects::tangible::consumable::DrinkImplementation, server::zone::objects::tangible::consumable::FoodImplementation, server::zone::objects::ship::ShipObjectImplementation, server::zone::objects::tangible::tool::ToolTangibleObjectImplementation, server::zone::objects::installation::garage::GarageInstallationImplementation, server::zone::objects::building::travel::TravelBuildingObjectImplementation, server::zone::objects::tangible::terminal::spaceship::SpaceshipTerminalImplementation, server::zone::objects::ship::FighterShipObjectImplementation, and server::zone::objects::ship::SpaceStationObjectImplementation.
Definition at line 1357 of file TangibleObject.cpp.
References initializeTransientMembers(), and readObjectMember().
bool TangibleObjectImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 1376 of file TangibleObject.cpp.
References complexity, conditionDamage, craftersName, customizationVariables, defenderList, faction, junkDealerNeeded, junkValue, level, maxCondition, objectSerial, optionsBitmask, pvpStatusBitmask, sliceable, sliced, targetable, unknownByte, useCount, and volume.
Referenced by readObject(), server::zone::objects::tangible::tool::ToolTangibleObjectImplementation::readObjectMember(), server::zone::objects::tangible::sign::SignObjectImplementation::readObjectMember(), server::zone::objects::tangible::terminal::TerminalImplementation::readObjectMember(), server::zone::objects::tangible::fishing::FishingBaitObjectImplementation::readObjectMember(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::readObjectMember(), server::zone::objects::tangible::loot::LootkitObjectImplementation::readObjectMember(), server::zone::objects::tangible::deed::DeedImplementation::readObjectMember(), server::zone::objects::tangible::tool::repair::RepairToolImplementation::readObjectMember(), server::zone::objects::tangible::firework::FireworkObjectImplementation::readObjectMember(), server::zone::objects::tangible::wearables::WearableObjectImplementation::readObjectMember(), server::zone::objects::tangible::ContainerImplementation::readObjectMember(), server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::readObjectMember(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::readObjectMember(), server::zone::objects::tangible::fishing::FishObjectImplementation::readObjectMember(), server::zone::objects::tangible::ticket::TicketObjectImplementation::readObjectMember(), server::zone::objects::tangible::attachement::AttachmentImplementation::readObjectMember(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::readObjectMember(), server::zone::objects::tangible::component::ComponentImplementation::readObjectMember(), server::zone::objects::tangible::InstrumentImplementation::readObjectMember(), server::zone::objects::tangible::consumable::ConsumableImplementation::readObjectMember(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::readObjectMember().
void TangibleObjectImplementation::removeAllSkillModsOfType (const int skillType, bool notifyClient = true) virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 1680 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::removeAllSkillModsOfType().
void TangibleObjectImplementation::removeDefender (SceneObject * defender) virtual
Removes the specified defender from the defender vector
Precondition
{ this object is locked }
Postcondition
{ this object is locked, defender is not in the defender vector }
Parameters
defender SceneObject to remove from the defender vector
Reimplemented in server::zone::objects::creature::AiAgentImplementation, and server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 289 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), clearCombatState(), DeltaMessage::close(), ObserverEventType::DEFENDERDROPPED, defenderList, server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::scene::SceneObjectImplementation::info(), server::zone::objects::scene::variables::DeltaVector< E >::remove(), server::zone::objects::scene::variables::DeltaVector< E >::removeAll(), server::zone::objects::scene::variables::DeltaVector< E >::size(), and DeltaMessage::startUpdate().
Referenced by server::zone::objects::tangible::TangibleObject::removeDefender(), and server::zone::objects::creature::AiAgentImplementation::removeDefender().
void TangibleObjectImplementation::removeDefenders () virtual
Removes all the defenders from the defender vector
Precondition
{ this object is locked }
Postcondition
{ this object is locked, defender vector is empty }
Definition at line 267 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), ObserverEventType::DEFENDERDROPPED, defenderList, server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::scene::variables::DeltaVector< E >::removeAll(), server::zone::objects::scene::variables::DeltaVector< E >::size(), and DeltaMessage::startUpdate().
Referenced by clearCombatState(), server::zone::objects::creature::CreatureObjectImplementation::clearCombatState(), server::zone::objects::creature::AiAgentImplementation::doAttack(), and server::zone::objects::tangible::TangibleObject::removeDefenders().
void TangibleObjectImplementation::removeSkillMod (const int skillType, const String & skillMod, int value, bool notifyClient = true) virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 1677 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::removeSkillMod().
void TangibleObjectImplementation::removeSkillModsFrom (CreatureObject * creature) virtual
Reimplemented in server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::tangible::wearables::WearableObjectImplementation, and server::zone::objects::tangible::wearables::WearableContainerObjectImplementation.
Definition at line 1671 of file TangibleObject.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::removeSkillModsFrom().
void TangibleObjectImplementation::removeTemplateSkillMods (TangibleObject * tangibleObject) virtual
Removes this object's skill mod map from the target object's skill mod map
Parameters
targetObject the targeted object containing the SkillModMap which will be affected.
Reimplemented in server::zone::objects::structure::StructureObjectImplementation.
Definition at line 639 of file TangibleObjectImplementation.cpp.
References SharedTangibleObjectTemplate::getSkillMods(), server::zone::objects::tangible::TangibleObject::removeSkillMod(), and server::zone::objects::scene::SceneObjectImplementation::templateObject.
Referenced by server::zone::objects::tangible::TangibleObject::removeTemplateSkillMods().
void TangibleObjectImplementation::repair (CreatureObject * player)
Luck Roll + Profession Mod(25) + Luck Tapes
Station Mod - BF
Luck Roll
Profession Bonus
Get Skill mods
use tool quality to lower chances if bad tool
Increase if near station
Subtract battle fatigue
Subtract complexity
5% random failure
Definition at line 692 of file TangibleObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::error(), getComplexity(), getConditionDamage(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObjectImplementation::getDisplayedName(), server::zone::objects::scene::SceneObjectImplementation::getGameObjectType(), getMaxCondition(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::creature::CreatureObject::getShockWounds(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::scene::SceneObjectImplementation::isASubChildOf(), repairAttempt(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::chat::StringIdChatParameter::setTT().
Referenced by server::zone::objects::tangible::TangibleObject::repair().
String TangibleObjectImplementation::repairAttempt (int repairChance) virtual
Reimplemented in server::zone::objects::tangible::weapon::WeaponObjectImplementation, and server::zone::objects::tangible::wearables::WearableObjectImplementation.
Definition at line 1969 of file TangibleObject.cpp.
Referenced by repair(), and server::zone::objects::tangible::TangibleObject::repairAttempt().
void TangibleObjectImplementation::rlock (bool doLock = true) protected
Definition at line 1330 of file TangibleObject.cpp.
References _this.
void TangibleObjectImplementation::runlock (bool doLock = true) protected
Definition at line 1346 of file TangibleObject.cpp.
References _this.
void TangibleObjectImplementation::sendBaselinesTo (SceneObject * player) virtual
Sends the TANO baseline messages of this object to the specified player
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the baseline messages }
Parameters
player SceneObject that will receive the baselines
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::creature::AiAgentImplementation, server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::installation::InstallationObjectImplementation, server::zone::objects::factorycrate::FactoryCrateImplementation, server::zone::objects::resource::ResourceContainerImplementation, and server::zone::objects::ship::ShipObjectImplementation.
Definition at line 114 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::info(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::sendMessage(), and sendPvpStatusTo().
Referenced by server::zone::objects::tangible::TangibleObject::sendBaselinesTo().
void TangibleObjectImplementation::sendPvpStatusTo (CreatureObject * player) virtual
Sends the pvp options bitmask
Precondition
{ this object is locked}
Postcondition
{ this object is locked }
Definition at line 129 of file TangibleObjectImplementation.cpp.
References _this, CreatureFlag::AGGRESSIVE, CreatureFlag::ATTACKABLE, isAggressiveTo(), isAttackableBy(), pvpStatusBitmask, and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by broadcastPvpStatusBitmask(), server::zone::objects::installation::InstallationObjectImplementation::sendBaselinesTo(), sendBaselinesTo(), server::zone::objects::creature::CreatureObjectImplementation::sendBaselinesTo(), and server::zone::objects::tangible::TangibleObject::sendPvpStatusTo().
void TangibleObjectImplementation::setCombatState () virtual
Sets the combat state, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object is in a combat state }
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation.
Definition at line 1683 of file TangibleObject.cpp.
Referenced by addDefender(), server::zone::objects::tangible::TangibleObject::setCombatState(), and setDefender().
void TangibleObjectImplementation::setComplexity (float value)
Definition at line 1794 of file TangibleObject.cpp.
References complexity.
Referenced by server::zone::objects::tangible::TangibleObject::setComplexity().
void TangibleObjectImplementation::setConditionDamage (float condDamage, bool notifyClient = true)
Sets the condition damage variable
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
condDamage new condition damage
Definition at line 424 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), conditionDamage, and TangibleObjectDeltaMessage3::updateConditionDamage().
Referenced by healDamage(), inflictDamage(), server::zone::objects::tangible::wearables::WearableObjectImplementation::repairAttempt(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::repairAttempt(), server::zone::objects::tangible::TangibleObject::setConditionDamage(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::updateCraftingValues(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::updateCraftingValues(), server::zone::objects::structure::StructureObjectImplementation::updateStructureStatus(), and server::zone::objects::installation::InstallationObjectImplementation::updateStructureStatus().
void TangibleObjectImplementation::setCountdownTimer (unsigned int newCount, bool notifyClient = true)
Definition at line 373 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), TangibleObjectDeltaMessage3::updateCountdownTimer(), and useCount.
Referenced by server::zone::objects::tangible::tool::CraftingToolImplementation::initializeTransientMembers(), server::zone::objects::tangible::TangibleObject::setCountdownTimer(), and setUseCount().
void TangibleObjectImplementation::setCraftersName (String & name)
Definition at line 1929 of file TangibleObject.cpp.
References craftersName.
Referenced by server::zone::objects::tangible::TangibleObject::setCraftersName().
void TangibleObjectImplementation::setCustomizationString (const String & vars)
Definition at line 1924 of file TangibleObject.cpp.
References customizationVariables.
Referenced by server::zone::objects::tangible::TangibleObject::setCustomizationString().
void server::zone::objects::tangible::TangibleObjectImplementation::setCustomizationVariable (byte type, short value, bool notifyClient = true)
Updates a customization variable
Referenced by server::zone::objects::creature::VehicleObjectImplementation::notifyInsertToZone(), server::zone::objects::tangible::TangibleObject::setCustomizationVariable(), and server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::updateCrystal().
void server::zone::objects::tangible::TangibleObjectImplementation::setCustomizationVariable (const String & type, short value, bool notifyClient = true)
void TangibleObjectImplementation::setCustomObjectName (const UnicodeString & name, bool notifyClient) virtual
Updates the custom name of the object
Precondition
{ this locked }
Postcondition
{ this locked }
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 521 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), server::zone::objects::scene::SceneObjectImplementation::customName, and TangibleObjectDeltaMessage3::updateName().
Referenced by server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), server::zone::objects::tangible::TangibleObject::setCustomObjectName(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::tuneCrystal(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::updateCraftingValues().
void TangibleObjectImplementation::setDefender (SceneObject * defender) virtual
Sets the active defender
Precondition
{ this object is locked }
Postcondition
{ this object is locked, defender is active }
Parameters
defender SceneObject to set as the active defender
Reimplemented in server::zone::objects::creature::AiAgentImplementation, and server::zone::objects::creature::VehicleObjectImplementation.
Definition at line 203 of file TangibleObjectImplementation.cpp.
References _this, addDefender(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), defenderList, server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::scene::variables::DeltaVector< E >::set(), setCombatState(), server::zone::objects::scene::variables::DeltaVector< E >::size(), and DeltaMessage::startUpdate().
Referenced by server::zone::objects::tangible::TangibleObject::setDefender(), and server::zone::objects::creature::AiAgentImplementation::setDefender().
void TangibleObjectImplementation::setFaction (unsigned int crc)
Definition at line 1847 of file TangibleObject.cpp.
References faction.
Referenced by server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), and server::zone::objects::tangible::TangibleObject::setFaction().
void TangibleObjectImplementation::setJunkDealerNeeded (int jdNeeded)
Definition at line 1939 of file TangibleObject.cpp.
References junkDealerNeeded.
Referenced by server::zone::objects::tangible::TangibleObject::setJunkDealerNeeded().
void TangibleObjectImplementation::setJunkValue (int jValue)
Definition at line 1949 of file TangibleObject.cpp.
References junkValue.
Referenced by server::zone::objects::tangible::TangibleObject::setJunkValue().
void TangibleObjectImplementation::setLevel (int lev) virtual
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, and server::zone::objects::creature::AiAgentImplementation.
Definition at line 1959 of file TangibleObject.cpp.
References level.
Referenced by server::zone::objects::tangible::TangibleObject::setLevel().
void TangibleObjectImplementation::setMaxCondition (int maxCond, bool notifyClient = true)
Definition at line 408 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), maxCondition, and TangibleObjectDeltaMessage3::updateMaxCondition().
Referenced by server::zone::objects::tangible::wearables::WearableObjectImplementation::repairAttempt(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::repairAttempt(), server::zone::objects::tangible::TangibleObject::setMaxCondition(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::updateCraftingValues(), server::zone::objects::tangible::consumable::ConsumableImplementation::updateCraftingValues(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::updateCraftingValues().
void TangibleObjectImplementation::setOptionsBitmask (unsigned int bitmask, bool notifyClient = true)
Definition at line 534 of file TangibleObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), DeltaMessage::close(), optionsBitmask, and TangibleObjectDeltaMessage3::updateOptionsBitmask().
Referenced by server::zone::objects::tangible::attachement::AttachmentImplementation::initializeMembers(), server::zone::objects::tangible::TangibleObject::setOptionsBitmask(), and setSerialNumber().
void TangibleObjectImplementation::setPvpStatusBitmask (int bitmask, bool notifyClient = true)
Definition at line 179 of file TangibleObjectImplementation.cpp.
References broadcastPvpStatusBitmask(), and pvpStatusBitmask.
Referenced by server::zone::objects::building::BuildingObjectImplementation::initializeTransientMembers(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), and server::zone::objects::tangible::TangibleObject::setPvpStatusBitmask().
void TangibleObjectImplementation::setSerialNumber (const String & serial)
Definition at line 196 of file TangibleObjectImplementation.cpp.
References getOptionsBitmask(), OptionBitmask::HASSERIAL, objectSerial, and setOptionsBitmask().
Referenced by server::zone::objects::tangible::TangibleObject::setSerialNumber().
void TangibleObjectImplementation::setSliceable (bool val)
Definition at line 1909 of file TangibleObject.cpp.
References sliceable.
Referenced by server::zone::objects::tangible::wearables::ArmorObjectImplementation::ArmorObjectImplementation(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::loadTemplateData(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::loadTemplateData(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::loadTemplateData(), and server::zone::objects::tangible::TangibleObject::setSliceable().
void TangibleObjectImplementation::setSliced (bool slice)
Definition at line 1914 of file TangibleObject.cpp.
References sliced.
Referenced by server::zone::objects::tangible::TangibleObject::setSliced().
void TangibleObjectImplementation::setUseCount (unsigned int newUseCount, bool notifyClient = true) virtual
Updates the object count delta
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
newUseCount new value to update
Reimplemented in server::zone::objects::factorycrate::FactoryCrateImplementation, and server::zone::objects::resource::ResourceContainerImplementation.
Definition at line 389 of file TangibleObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObjectImplementation::destroyObjectFromWorld(), server::zone::objects::scene::SceneObjectImplementation::isCreatureObject(), setCountdownTimer(), and useCount.
Referenced by server::zone::objects::tangible::firework::FireworkObjectImplementation::completeLaunch(), decreaseUseCount(), server::zone::objects::tangible::TangibleObject::setUseCount(), server::zone::objects::tangible::firework::FireworkObjectImplementation::updateCraftingValues(), server::zone::objects::tangible::component::ComponentImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::updateCraftingValues(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::updateCraftingValues(), server::zone::objects::tangible::consumable::ConsumableImplementation::updateCraftingValues(), and updateCraftingValues().
void TangibleObjectImplementation::synchronizedUIListen (SceneObject * player, int value) virtual
Calls the appropriate UI Listener Function
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
player CreatureObject using the item
value value from packet
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::installation::harvester::HarvesterObjectImplementation, and server::zone::objects::installation::GeneratorObjectImplementation.
Definition at line 186 of file TangibleObjectImplementation.cpp.
References _this, and server::zone::objects::scene::SceneObject::sendMessage().
Referenced by server::zone::objects::tangible::TangibleObject::synchronizedUIListen().
void TangibleObjectImplementation::synchronizedUIStopListen (SceneObject * player, int value) virtual
Calls the appropriate UI Stop Listener Function
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
player CreatureObject using the item
value value from packet
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::installation::harvester::HarvesterObjectImplementation, and server::zone::objects::installation::GeneratorObjectImplementation.
Definition at line 192 of file TangibleObjectImplementation.cpp.
Referenced by server::zone::objects::tangible::TangibleObject::synchronizedUIStopListen().
void TangibleObjectImplementation::unlock (bool doLock = true) protected
Definition at line 1342 of file TangibleObject.cpp.
References _this.
void TangibleObjectImplementation::updateCraftingValues (CraftingValues * values, bool firstUpdate) virtual
I know its kind dirty, but we want generics to have quantities Without needing their own classes
Reimplemented in server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::tangible::component::dna::DnaComponentImplementation, server::zone::objects::tangible::tool::CraftingToolImplementation, server::zone::objects::tangible::consumable::ConsumableImplementation, server::zone::objects::tangible::wearables::ArmorObjectImplementation, server::zone::objects::tangible::tool::recycle::RecycleToolImplementation, server::zone::objects::tangible::component::genetic::GeneticComponentImplementation, server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation, server::zone::objects::tangible::pharmaceutical::DotPackImplementation, server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation, server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation, server::zone::objects::tangible::pharmaceutical::WoundPackImplementation, server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation, server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation, server::zone::objects::tangible::pharmaceutical::RevivePackImplementation, server::zone::objects::tangible::tool::SurveyToolImplementation, server::zone::objects::tangible::pharmaceutical::StimPackImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, server::zone::objects::tangible::pharmaceutical::CurePackImplementation, server::zone::objects::tangible::pharmaceutical::StatePackImplementation, server::zone::objects::tangible::component::ComponentImplementation, server::zone::objects::tangible::fishing::FishingPoleObjectImplementation, server::zone::objects::tangible::attachement::AttachmentImplementation, server::zone::objects::tangible::deed::pet::PetDeedImplementation, server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation, server::zone::objects::tangible::firework::FireworkObjectImplementation, server::zone::objects::tangible::tool::repair::RepairToolImplementation, server::zone::objects::tangible::wearables::WearableObjectImplementation, server::zone::objects::tangible::deed::DeedImplementation, server::zone::objects::tangible::deed::structure::StructureDeedImplementation, server::zone::objects::tangible::component::armor::ArmorComponentImplementation, server::zone::objects::tangible::powerup::PowerupObjectImplementation, server::zone::objects::tangible::wearables::PsgArmorObjectImplementation, and server::zone::objects::tangible::wearables::ClothingObjectImplementation.
Definition at line 550 of file TangibleObjectImplementation.cpp.
References server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::hasProperty(), and setUseCount().
Referenced by server::zone::objects::tangible::TangibleObject::updateCraftingValues().
void TangibleObjectImplementation::wlock (bool doLock = true) protected
Definition at line 1334 of file TangibleObject.cpp.
References _this.
void TangibleObjectImplementation::wlock (ManagedObject * obj) protected
Definition at line 1338 of file TangibleObject.cpp.
References _this.
void TangibleObjectImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Reimplemented in server::zone::objects::creature::CreatureObjectImplementation, server::zone::objects::creature::AiAgentImplementation, server::zone::objects::tangible::weapon::WeaponObjectImplementation, server::zone::objects::structure::StructureObjectImplementation, server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation, server::zone::objects::building::BuildingObjectImplementation, server::zone::objects::installation::InstallationObjectImplementation, server::zone::objects::creature::VehicleObjectImplementation, server::zone::objects::tangible::component::dna::DnaComponentImplementation, server::zone::objects::tangible::wearables::ArmorObjectImplementation, server::zone::objects::tangible::tool::CraftingToolImplementation, server::zone::objects::tangible::consumable::ConsumableImplementation, server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation, server::zone::objects::creature::CreatureImplementation, server::zone::objects::tangible::pharmaceutical::DotPackImplementation, server::zone::objects::tangible::InstrumentImplementation, server::zone::objects::tangible::tool::recycle::RecycleToolImplementation, server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation, server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation, server::zone::objects::installation::factory::FactoryObjectImplementation, server::zone::objects::tangible::component::genetic::GeneticComponentImplementation, server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation, server::zone::objects::tangible::pharmaceutical::WoundPackImplementation, server::zone::objects::factorycrate::FactoryCrateImplementation, server::zone::objects::tangible::pharmaceutical::CurePackImplementation, server::zone::objects::tangible::pharmaceutical::RevivePackImplementation, server::zone::objects::tangible::pharmaceutical::StimPackImplementation, server::zone::objects::tangible::tool::SurveyToolImplementation, server::zone::objects::tangible::pharmaceutical::StatePackImplementation, server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation, server::zone::objects::tangible::component::ComponentImplementation, server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation, server::zone::objects::tangible::tool::CraftingStationImplementation, server::zone::objects::resource::ResourceContainerImplementation, server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation, server::zone::objects::tangible::attachement::AttachmentImplementation, server::zone::objects::tangible::ticket::TicketObjectImplementation, server::zone::objects::tangible::fishing::FishingPoleObjectImplementation, server::zone::objects::tangible::fishing::FishObjectImplementation, server::zone::objects::installation::shuttle::ShuttleInstallationImplementation, server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation, server::zone::objects::tangible::ContainerImplementation, server::zone::objects::tangible::wearables::WearableObjectImplementation, server::zone::objects::tangible::firework::FireworkObjectImplementation, server::zone::objects::tangible::deed::pet::PetDeedImplementation, server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation, server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation, server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation, server::zone::objects::tangible::tool::repair::RepairToolImplementation, server::zone::objects::tangible::deed::ResourceDeedImplementation, server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation, server::zone::objects::installation::harvester::HarvesterObjectImplementation, server::zone::objects::tangible::deed::structure::StructureDeedImplementation, server::zone::objects::tangible::deed::DeedImplementation, server::zone::objects::tangible::loot::LootkitObjectImplementation, server::zone::objects::tangible::component::armor::ArmorComponentImplementation, server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation, server::zone::objects::installation::GeneratorObjectImplementation, server::zone::objects::tangible::terminal::ticketcollector::TicketCollectorImplementation, server::zone::objects::tangible::powerup::PowerupObjectImplementation, server::zone::objects::tangible::fishing::FishingBaitObjectImplementation, server::zone::objects::tangible::wearables::WearableContainerObjectImplementation, server::zone::objects::tangible::terminal::startinglocation::StartingLocationTerminalImplementation, server::zone::objects::tangible::terminal::TerminalImplementation, server::zone::objects::tangible::sign::SignObjectImplementation, server::zone::objects::creature::NonPlayerCreatureObjectImplementation, server::zone::objects::tangible::wearables::RobeObjectImplementation, server::zone::objects::tangible::wearables::PsgArmorObjectImplementation, server::zone::objects::tangible::wearables::ClothingObjectImplementation, server::zone::objects::building::hospital::HospitalBuildingObjectImplementation, server::zone::objects::building::recreation::RecreationBuildingObjectImplementation, server::zone::objects::tangible::consumable::DrinkImplementation, server::zone::objects::tangible::consumable::FoodImplementation, server::zone::objects::ship::ShipObjectImplementation, server::zone::objects::tangible::tool::ToolTangibleObjectImplementation, server::zone::objects::installation::garage::GarageInstallationImplementation, server::zone::objects::building::travel::TravelBuildingObjectImplementation, server::zone::objects::tangible::terminal::spaceship::SpaceshipTerminalImplementation, server::zone::objects::ship::FighterShipObjectImplementation, and server::zone::objects::ship::SpaceStationObjectImplementation.
Definition at line 1462 of file TangibleObject.cpp.
References writeObjectMembers().
int TangibleObjectImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 1469 of file TangibleObject.cpp.
References complexity, conditionDamage, craftersName, customizationVariables, defenderList, faction, junkDealerNeeded, junkValue, level, maxCondition, objectSerial, optionsBitmask, pvpStatusBitmask, sliceable, sliced, targetable, unknownByte, useCount, and volume.
Referenced by writeObject(), server::zone::objects::tangible::tool::ToolTangibleObjectImplementation::writeObjectMembers(), server::zone::objects::tangible::sign::SignObjectImplementation::writeObjectMembers(), server::zone::objects::tangible::terminal::TerminalImplementation::writeObjectMembers(), server::zone::objects::tangible::fishing::FishingBaitObjectImplementation::writeObjectMembers(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::writeObjectMembers(), server::zone::objects::tangible::loot::LootkitObjectImplementation::writeObjectMembers(), server::zone::objects::tangible::deed::DeedImplementation::writeObjectMembers(), server::zone::objects::tangible::tool::repair::RepairToolImplementation::writeObjectMembers(), server::zone::objects::tangible::firework::FireworkObjectImplementation::writeObjectMembers(), server::zone::objects::tangible::wearables::WearableObjectImplementation::writeObjectMembers(), server::zone::objects::tangible::ContainerImplementation::writeObjectMembers(), server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectImplementation::writeObjectMembers(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::writeObjectMembers(), server::zone::objects::tangible::fishing::FishObjectImplementation::writeObjectMembers(), server::zone::objects::tangible::ticket::TicketObjectImplementation::writeObjectMembers(), server::zone::objects::tangible::attachement::AttachmentImplementation::writeObjectMembers(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::writeObjectMembers(), server::zone::objects::tangible::component::ComponentImplementation::writeObjectMembers(), server::zone::objects::tangible::InstrumentImplementation::writeObjectMembers(), server::zone::objects::tangible::consumable::ConsumableImplementation::writeObjectMembers(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::writeObjectMembers().
Friends And Related Function Documentation
friend class TangibleObject friend
Definition at line 953 of file TangibleObject.h.
Member Data Documentation
WeakReference<TangibleObject*> server::zone::objects::tangible::TangibleObjectImplementation::_this
Definition at line 919 of file TangibleObject.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addDefender(), broadcastPvpStatusBitmask(), createFactoryCrate(), dropFromDefenderLists(), getThreatMap(), inflictDamage(), lock(), removeDefender(), removeDefenders(), rlock(), runlock(), sendBaselinesTo(), sendPvpStatusTo(), setConditionDamage(), setCountdownTimer(), setCustomObjectName(), setDefender(), setMaxCondition(), setOptionsBitmask(), synchronizedUIListen(), unlock(), and wlock().
float server::zone::objects::tangible::TangibleObjectImplementation::complexity protected
Definition at line 554 of file TangibleObject.h.
Referenced by getComplexity(), initializeMembers(), readObjectMember(), setComplexity(), and writeObjectMembers().
float server::zone::objects::tangible::TangibleObjectImplementation::conditionDamage protected
Definition at line 562 of file TangibleObject.h.
Referenced by server::zone::objects::tangible::weapon::WeaponObjectImplementation::decay(), server::zone::objects::tangible::consumable::ConsumableImplementation::fillAttributeList(), fillAttributeList(), getConditionDamage(), healDamage(), inflictDamage(), initializeMembers(), isDestroyed(), readObjectMember(), setConditionDamage(), and writeObjectMembers().
String server::zone::objects::tangible::TangibleObjectImplementation::craftersName protected
Definition at line 576 of file TangibleObject.h.
Referenced by server::zone::objects::tangible::consumable::ConsumableImplementation::fillAttributeList(), fillAttributeList(), getCraftersName(), readObjectMember(), setCraftersName(), and writeObjectMembers().
CustomizationVariables server::zone::objects::tangible::TangibleObjectImplementation::customizationVariables protected
Definition at line 560 of file TangibleObject.h.
Referenced by getCustomizationString(), getCustomizationVariables(), readObjectMember(), setCustomizationString(), and writeObjectMembers().
DeltaVector<ManagedReference<SceneObject* > > server::zone::objects::tangible::TangibleObjectImplementation::defenderList protected
Definition at line 586 of file TangibleObject.h.
Referenced by addDefender(), server::zone::objects::creature::AiAgentImplementation::addDefender(), server::zone::objects::creature::AiAgentImplementation::doAttack(), dropFromDefenderLists(), getDefenderList(), getMainDefender(), hasDefender(), readObjectMember(), removeDefender(), server::zone::objects::creature::AiAgentImplementation::removeDefender(), removeDefenders(), setDefender(), and writeObjectMembers().
unsigned int server::zone::objects::tangible::TangibleObjectImplementation::faction protected
Definition at line 558 of file TangibleObject.h.
Referenced by getFaction(), initializeMembers(), server::zone::objects::creature::CreatureObjectImplementation::initializeMembers(), initializeTransientMembers(), isImperial(), isNeutral(), isRebel(), loadTemplateData(), readObjectMember(), setFaction(), and writeObjectMembers().
int server::zone::objects::tangible::TangibleObjectImplementation::junkDealerNeeded protected
Definition at line 578 of file TangibleObject.h.
Referenced by getJunkDealerNeeded(), initializeMembers(), readObjectMember(), setJunkDealerNeeded(), and writeObjectMembers().
int server::zone::objects::tangible::TangibleObjectImplementation::junkValue protected
Definition at line 580 of file TangibleObject.h.
Referenced by getJunkValue(), initializeMembers(), readObjectMember(), setJunkValue(), and writeObjectMembers().
short server::zone::objects::tangible::TangibleObjectImplementation::level protected
Definition at line 568 of file TangibleObject.h.
Referenced by server::zone::objects::creature::AiAgentImplementation::doAttack(), getLevel(), initializeMembers(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), server::zone::objects::creature::CreatureObjectImplementation::loadTemplateData(), server::zone::objects::creature::AiAgentImplementation::notifyDespawn(), readObjectMember(), server::zone::objects::tangible::tool::CraftingStationImplementation::setComplexityLevel(), server::zone::objects::creature::AiAgentImplementation::setLevel(), setLevel(), server::zone::objects::tangible::attachement::AttachmentImplementation::updateCraftingValues(), and writeObjectMembers().
int server::zone::objects::tangible::TangibleObjectImplementation::maxCondition protected
Definition at line 564 of file TangibleObject.h.
Referenced by server::zone::objects::tangible::weapon::WeaponObjectImplementation::decay(), server::zone::objects::tangible::consumable::ConsumableImplementation::fillAttributeList(), fillAttributeList(), getMaxCondition(), inflictDamage(), isDestroyed(), loadTemplateData(), server::zone::objects::structure::StructureObjectImplementation::notifyInsertToZone(), readObjectMember(), setMaxCondition(), and writeObjectMembers().
String server::zone::objects::tangible::TangibleObjectImplementation::objectSerial protected
Definition at line 582 of file TangibleObject.h.
Referenced by server::zone::objects::tangible::consumable::ConsumableImplementation::fillAttributeList(), fillAttributeList(), getSerialNumber(), readObjectMember(), setSerialNumber(), and writeObjectMembers().
unsigned int server::zone::objects::tangible::TangibleObjectImplementation::optionsBitmask protected
Definition at line 570 of file TangibleObject.h.
Referenced by getOptionsBitmask(), server::zone::objects::creature::CreatureObjectImplementation::initializeMembers(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::loadTemplateData(), server::zone::objects::creature::VehicleObjectImplementation::loadTemplateData(), server::zone::objects::building::BuildingObjectImplementation::loadTemplateData(), loadTemplateData(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), readObjectMember(), server::zone::objects::installation::InstallationObjectImplementation::setOperating(), setOptionsBitmask(), and writeObjectMembers().
unsigned int server::zone::objects::tangible::TangibleObjectImplementation::pvpStatusBitmask protected
Definition at line 572 of file TangibleObject.h.
Referenced by getPvpStatusBitmask(), server::zone::objects::creature::CreatureObjectImplementation::initializeMembers(), server::zone::objects::creature::CreatureObjectImplementation::isAggressiveTo(), isAttackableBy(), server::zone::objects::creature::AiAgentImplementation::isAttackableBy(), server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::loadTemplateData(), server::zone::objects::creature::VehicleObjectImplementation::loadTemplateData(), loadTemplateData(), readObjectMember(), sendPvpStatusTo(), setPvpStatusBitmask(), and writeObjectMembers().
bool server::zone::objects::tangible::TangibleObjectImplementation::sliceable protected
Definition at line 588 of file TangibleObject.h.
Referenced by initializeMembers(), isSliceable(), loadTemplateData(), readObjectMember(), setSliceable(), and writeObjectMembers().
bool server::zone::objects::tangible::TangibleObjectImplementation::sliced protected
Definition at line 590 of file TangibleObject.h.
Referenced by server::zone::objects::tangible::wearables::ArmorObjectImplementation::fillAttributeList(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::fillAttributeList(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getAttackSpeed(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getMaxDamage(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getMinDamage(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::getTypeValue(), initializeMembers(), isSliceable(), isSliced(), readObjectMember(), setSliced(), and writeObjectMembers().
bool server::zone::objects::tangible::TangibleObjectImplementation::targetable protected
Definition at line 552 of file TangibleObject.h.
Referenced by loadTemplateData(), readObjectMember(), and writeObjectMembers().
Reference<ThreatMap* > server::zone::objects::tangible::TangibleObjectImplementation::threatMap protected
Definition at line 584 of file TangibleObject.h.
Referenced by server::zone::objects::creature::AiAgentImplementation::clearCombatState(), getThreatMap(), initializeMembers(), initializeTransientMembers(), loadTemplateData(), server::zone::objects::creature::AiAgentImplementation::notifyDespawn(), notifyObjectDestructionObservers(), server::zone::objects::creature::CreatureImplementation::runAway(), and server::zone::objects::creature::AiAgentImplementation::tryRetreat().
byte server::zone::objects::tangible::TangibleObjectImplementation::unknownByte protected
Definition at line 574 of file TangibleObject.h.
Referenced by getUnknownByte(), initializeMembers(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::tangible::TangibleObjectImplementation::useCount protected
Definition at line 566 of file TangibleObject.h.
Referenced by decreaseUseCount(), server::zone::objects::tangible::consumable::ConsumableImplementation::fillAttributeList(), fillAttributeList(), getDisplayedUseCount(), getUseCount(), initializeMembers(), loadTemplateData(), readObjectMember(), setCountdownTimer(), server::zone::objects::factorycrate::FactoryCrateImplementation::setUseCount(), setUseCount(), and writeObjectMembers().
int server::zone::objects::tangible::TangibleObjectImplementation::volume protected
Definition at line 556 of file TangibleObject.h.
Referenced by server::zone::objects::tangible::consumable::ConsumableImplementation::fillAttributeList(), fillAttributeList(), getVolume(), initializeMembers(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/TangibleObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/TangibleObject.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/TangibleObjectImplementation.cpp