Core3: server::chat::ChatMessageAdapter Class Reference
server::chat::ChatMessageAdapter Class Reference
#include <ChatMessage.h>
Public Member Functions
ChatMessageAdapter (ChatMessage *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setString (const String &msg)
String toString ()
Detailed Description
Definition at line 126 of file ChatMessage.h.
Constructor & Destructor Documentation
ChatMessageAdapter::ChatMessageAdapter (ChatMessage * impl)
Definition at line 228 of file ChatMessage.cpp.
Member Function Documentation
void ChatMessageAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 231 of file ChatMessage.cpp.
References RPC_SETSTRING__STRING_, RPC_TOSTRING__, setString(), and toString().
void ChatMessageAdapter::setString (const String & msg)
Definition at line 251 of file ChatMessage.cpp.
Referenced by invokeMethod().
String ChatMessageAdapter::toString ()
Definition at line 255 of file ChatMessage.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatMessage.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatMessage.cpp