Core3: server::zone::managers::objectcontroller::command::CommandConfigManager Class Reference
server::zone::managers::objectcontroller::command::CommandConfigManager Class Reference
#include <CommandConfigManager.h>
Public Member Functions
CommandConfigManager (ZoneProcessServer *serv)
void registerFunctions ()
void registerGlobals ()
void registerCommands ()
void registerSpecialCommands (CommandList *sCommands)
bool loadSlashCommandsFile ()
bool contains (String name)
void loadCommandData (const String &filename)
QueueCommand * createCommand (const String &name)
Static Public Member Functions
static int runSlashCommandsFile (lua_State *L)
static void parseOptions (LuaObject &slashcommand, QueueCommand *command)
static void parseAlternativeNames (String &alternativeNames, QueueCommand *slashCommand)
static void parseVariableData (String varName, LuaObject &command, QueueCommand *slashCommand)
static int addCommand (lua_State *L)
static int hashCode (lua_State *L)
Public Attributes
CommandFactory< QueueCommand
*(String, ZoneProcessServer
*), String > commandFactory
Static Public Attributes
static const int COMMANDNAME = 0
static const int DEFAULTPRIORITY = 1
static const int SCRIPTHOOK = 2
static const int FAILSCRIPT_HOOK = 3
static const int CPPHOOK = 4
static const int FAILCPPHOOK = 5
static const int DEFAULTTIME = 6
static const int CHARACTERABILITY = 7
static const int STANDING = 8
static const int SNEAKING = 9
static const int WALKING = 10
static const int RUNNING = 11
static const int KNEELING = 12
static const int CROUCHSNEAKING = 13
static const int CROUCHWALKING = 14
static const int PRONE = 15
static const int CRAWLING = 16
static const int CLIMBINGSTATIONARY = 17
static const int CLIMBING = 18
static const int HOVERING = 19
static const int FLYING = 20
static const int LYINGDOWN = 21
static const int SITTING = 22
static const int SKILLANIMATING = 23
static const int DRIVINGVEHICLE = 24
static const int RIDINGCREATURE = 25
static const int KNOCKEDDOWN = 26
static const int INCAPACITATED = 27
static const int DEAD = 28
static const int BLOCKING = 29
static const int COVER = 30
static const int COMBAT = 31
static const int PEACE = 32
static const int AIMING = 33
static const int ALERT = 34
static const int BERSERK = 35
static const int FEIGNDEATH = 36
static const int COMBATATTITUDEEVASIVE = 37
static const int COMBATATTITUDENORMAL = 38
static const int COMBATATTITUDEAGGRESSIVE = 39
static const int TUMBLING = 40
static const int RALLIED = 41
static const int STUNNED = 42
static const int BLINDED = 43
static const int DIZZY = 44
static const int INTIMIDATED = 45
static const int IMMOBILIZED = 46
static const int FROZEN = 47
static const int SWIMMING = 48
static const int SITTINGONCHAIR = 49
static const int CRAFTING = 50
static const int GLOWINGJEDI = 51
static const int MASKSCENT = 52
static const int POISONED = 53
static const int BLEEDING = 54
static const int DISEASED = 55
static const int ONFIRE = 56
static const int RIDINGMOUNT = 57
static const int MOUNTEDCREATURE = 58
static const int PILOTINGSHIP = 59
static const int PILOTINGPOBSHIP = 60
static const int SHIPOPERATIONS = 61
static const int SHIPGUNNER = 62
static const int SHIPINTERIOR = 63
static const int TEMPSCRIPT = 64
static const int TARGETTYPE = 65
static const int STRINGID = 66
static const int VISIBLE = 67
static const int CALLONTARGET = 68
static const int COMMANDGROUP = 69
static const int DISABLED = 70
static const int MAXRANGETOTARGET = 71
static const int GODLEVEL = 72
static const int DISPLAYGROUP = 73
static const int ADDTOCOMBATQUEUE = 74
static ZoneProcessServer * server = NULL
static CommandList * slashCommands = NULL
Detailed Description
Definition at line 69 of file CommandConfigManager.h.
Constructor & Destructor Documentation
CommandConfigManager::CommandConfigManager (ZoneProcessServer * serv)
Definition at line 62 of file CommandConfigManager.cpp.
References registerCommands(), registerFunctions(), registerGlobals(), and server.
Member Function Documentation
int CommandConfigManager::addCommand (lua_State * L) static
Definition at line 624 of file CommandConfigManager.cpp.
References server::zone::managers::objectcontroller::command::CommandList::getSlashCommand(), parseOptions(), and slashCommands.
Referenced by registerFunctions().
bool server::zone::managers::objectcontroller::command::CommandConfigManager::contains (String name) inline
Definition at line 176 of file CommandConfigManager.h.
QueueCommand * CommandConfigManager::createCommand (const String & name)
Definition at line 284 of file CommandConfigManager.cpp.
References commandFactory, server::zone::managers::objectcontroller::command::CommandList::put(), server, and slashCommands.
Referenced by loadCommandData(), and registerSpecialCommands().
int CommandConfigManager::hashCode (lua_State * L) static
Definition at line 616 of file CommandConfigManager.cpp.
Referenced by registerFunctions().
void CommandConfigManager::loadCommandData (const String & filename)
Definition at line 75 of file CommandConfigManager.cpp.
References server::zone::objects::creature::commands::QueueCommand::addInvalidLocomotion(), ADDTOCOMBATQUEUE, CreatureState::AIMING, AIMING, CreatureState::ALERT, ALERT, CreatureState::BERSERK, BERSERK, CreatureState::BLEEDING, BLEEDING, CreatureState::BLINDED, BLINDED, CreatureLocomotion::BLOCKING, BLOCKING, CHARACTERABILITY, CreatureLocomotion::CLIMBING, CLIMBING, CreatureLocomotion::CLIMBINGSTATIONARY, CLIMBINGSTATIONARY, CreatureState::COMBAT, COMBAT, CreatureState::COMBATATTITUDEAGGRESSIVE, COMBATATTITUDEAGGRESSIVE, CreatureState::COMBATATTITUDEEVASIVE, COMBATATTITUDEEVASIVE, CreatureState::COMBATATTITUDENORMAL, COMBATATTITUDENORMAL, COMMANDGROUP, COMMANDNAME, CreatureState::COVER, COVER, CreatureState::CRAFTING, CRAFTING, CreatureLocomotion::CRAWLING, CRAWLING, createCommand(), CreatureLocomotion::CROUCHSNEAKING, CROUCHSNEAKING, CreatureLocomotion::CROUCHWALKING, CROUCHWALKING, CreatureLocomotion::DEAD, DEAD, DEFAULTPRIORITY, DEFAULTTIME, CreatureState::DISEASED, DISEASED, CreatureState::DIZZY, DIZZY, CreatureLocomotion::DRIVINGVEHICLE, DRIVINGVEHICLE, CreatureState::FEIGNDEATH, FEIGNDEATH, CreatureLocomotion::FLYING, FLYING, CreatureState::FROZEN, FROZEN, DataTableIff::getRow(), DataTableIff::getTotalRows(), DataTableRow::getValue(), CreatureState::GLOWINGJEDI, GLOWINGJEDI, CreatureLocomotion::HOVERING, HOVERING, CreatureState::IMMOBILIZED, IMMOBILIZED, CreatureLocomotion::INCAPACITATED, INCAPACITATED, CreatureState::INTIMIDATED, INTIMIDATED, CreatureLocomotion::KNEELING, KNEELING, CreatureLocomotion::KNOCKEDDOWN, KNOCKEDDOWN, CreatureLocomotion::LYINGDOWN, LYINGDOWN, CreatureState::MASKSCENT, MASKSCENT, MAXRANGETOTARGET, CreatureState::MOUNTEDCREATURE, MOUNTEDCREATURE, CreatureState::ONFIRE, ONFIRE, CreatureState::PEACE, PEACE, CreatureState::PILOTINGPOBSHIP, PILOTINGPOBSHIP, CreatureState::PILOTINGSHIP, PILOTINGSHIP, CreatureState::POISONED, POISONED, CreatureLocomotion::PRONE, PRONE, CreatureState::RALLIED, RALLIED, DataTableIff::readObject(), CreatureLocomotion::RIDINGCREATURE, RIDINGCREATURE, CreatureState::RIDINGMOUNT, RIDINGMOUNT, CreatureLocomotion::RUNNING, RUNNING, server::zone::objects::creature::commands::QueueCommand::setAddToCombatQueue(), server::zone::objects::creature::commands::QueueCommand::setCharacterAbility(), server::zone::objects::creature::commands::QueueCommand::setCommandGroup(), server::zone::objects::creature::commands::QueueCommand::setDefaultPriority(), server::zone::objects::creature::commands::QueueCommand::setDefaultTime(), server::zone::objects::creature::commands::QueueCommand::setMaxRange(), server::zone::objects::creature::commands::QueueCommand::setStateMask(), server::zone::objects::creature::commands::QueueCommand::setTargetType(), CreatureState::SHIPGUNNER, SHIPGUNNER, CreatureState::SHIPINTERIOR, SHIPINTERIOR, CreatureState::SHIPOPERATIONS, SHIPOPERATIONS, CreatureLocomotion::SITTING, SITTING, CreatureState::SITTINGONCHAIR, SITTINGONCHAIR, CreatureLocomotion::SKILLANIMATING, SKILLANIMATING, CreatureLocomotion::SNEAKING, SNEAKING, CreatureLocomotion::STANDING, STANDING, CreatureState::STUNNED, STUNNED, CreatureState::SWIMMING, SWIMMING, TARGETTYPE, CreatureState::TUMBLING, TUMBLING, CreatureLocomotion::WALKING, and WALKING.
bool server::zone::managers::objectcontroller::command::CommandConfigManager::loadSlashCommandsFile () inline
Definition at line 166 of file CommandConfigManager.h.
void CommandConfigManager::parseAlternativeNames (String & alternativeNames, QueueCommand * slashCommand) static
Definition at line 604 of file CommandConfigManager.cpp.
References server::zone::managers::objectcontroller::command::CommandList::put(), and slashCommands.
void CommandConfigManager::parseOptions (LuaObject & slashcommand, QueueCommand * command) static
Definition at line 462 of file CommandConfigManager.cpp.
References parseVariableData().
Referenced by addCommand().
void CommandConfigManager::parseVariableData (String varName, LuaObject & command, QueueCommand * slashCommand) static
Definition at line 479 of file CommandConfigManager.cpp.
References CombatQueueCommand::addDotEffect(), server::zone::objects::creature::commands::QueueCommand::addSkillMod(), CombatQueueCommand::addStateEffect(), server::zone::objects::creature::commands::QueueCommand::getQueueCommandName(), server::zone::objects::creature::commands::QueueCommand::isCombatCommand(), CombatQueueCommand::isSquadLeaderCommand(), CombatQueueCommand::setAccuracyBonus(), CombatQueueCommand::setAccuracySkillMod(), SquadLeaderCommand::setAction(), CombatQueueCommand::setActionCostMultiplier(), server::zone::objects::creature::commands::QueueCommand::setAddToCombatQueue(), CombatQueueCommand::setAnimationCRC(), CombatQueueCommand::setAreaAction(), CombatQueueCommand::setAreaRange(), CombatQueueCommand::setAttackType(), server::zone::objects::creature::commands::QueueCommand::setCharacterAbility(), CombatQueueCommand::setCombatSpam(), CombatQueueCommand::setConeAction(), CombatQueueCommand::setConeAngle(), CombatQueueCommand::setDamage(), CombatQueueCommand::setDamageMultiplier(), server::zone::objects::creature::commands::QueueCommand::setDefaultPriority(), server::zone::objects::creature::commands::QueueCommand::setDefaultTime(), server::zone::objects::creature::commands::QueueCommand::setDisabled(), CombatQueueCommand::setEffectString(), CombatQueueCommand::setForceCost(), CombatQueueCommand::setForceCostMultiplier(), CombatQueueCommand::setHealthCostMultiplier(), server::zone::objects::creature::commands::QueueCommand::setInvalidLocomotions(), server::zone::objects::creature::commands::QueueCommand::setMaxRange(), CombatQueueCommand::setMindCostMultiplier(), CombatQueueCommand::setPoolsToDamage(), CombatQueueCommand::setRange(), CombatQueueCommand::setSpeed(), CombatQueueCommand::setSpeedMultiplier(), server::zone::objects::creature::commands::QueueCommand::setStateMask(), server::zone::objects::creature::commands::QueueCommand::setTargetType(), and CombatQueueCommand::setTrails().
Referenced by parseOptions().
void CommandConfigManager::registerCommands ()
Definition at line 640 of file CommandConfigManager.cpp.
References commandFactory.
Referenced by CommandConfigManager().
void CommandConfigManager::registerFunctions ()
Definition at line 327 of file CommandConfigManager.cpp.
References addCommand(), hashCode(), and runSlashCommandsFile().
Referenced by CommandConfigManager().
void CommandConfigManager::registerGlobals ()
Definition at line 334 of file CommandConfigManager.cpp.
References CombatManager::ACTION, CreatureAttribute::ACTION, CommandEffect::ACTIONDEGRADE, CreatureState::AIMING, CreatureState::ALERT, CreatureState::BERSERK, CreatureState::BLEEDING, CommandEffect::BLIND, CreatureState::BLINDED, CreatureLocomotion::BLOCKING, CombatManager::CARBINE, CreatureLocomotion::CLIMBING, CreatureLocomotion::CLIMBINGSTATIONARY, CreatureState::COMBAT, CreatureState::COMBATATTITUDEAGGRESSIVE, CreatureState::COMBATATTITUDEEVASIVE, CreatureState::COMBATATTITUDENORMAL, CreatureState::COVER, CreatureState::CRAFTING, CreatureLocomotion::CRAWLING, CreatureLocomotion::CROUCHSNEAKING, CreatureLocomotion::CROUCHWALKING, CreatureLocomotion::DEAD, CombatManager::DEFAULTTRAIL, CreatureState::DISEASED, CommandEffect::DIZZY, CreatureState::DIZZY, CreatureLocomotion::DRIVINGVEHICLE, CreatureState::FEIGNDEATH, CreatureLocomotion::FLYING, CombatManager::FORCEATTACK, CreatureState::FROZEN, CreatureState::GLOWINGJEDI, CombatManager::GRENADE, CombatManager::HEALTH, CreatureAttribute::HEALTH, CommandEffect::HEALTHDEGRADE, CombatManager::HEAVYWEAPON, CreatureLocomotion::HOVERING, CreatureState::IMMOBILIZED, CreatureLocomotion::INCAPACITATED, CommandEffect::INTIMIDATE, CreatureState::INTIMIDATED, CreatureLocomotion::INVALID, CommandEffect::INVALID, CreatureState::INVALID, CreatureLocomotion::KNEELING, CommandEffect::KNOCKDOWN, CreatureLocomotion::KNOCKEDDOWN, CombatManager::LEFTFOOTTRAIL, CombatManager::LEFTHANDTRAIL, CombatManager::LIGHTNINGRIFLE, CreatureLocomotion::LYINGDOWN, CreatureState::MASKSCENT, CombatManager::MELEEWEAPON, CombatManager::MIND, CreatureAttribute::MIND, CommandEffect::MINDDEGRADE, CombatManager::MINE, CreatureState::MOUNTEDCREATURE, CommandEffect::NEXTATTACKDELAY, CombatManager::NOTRAIL, CombatManager::ONEHANDMELEEWEAPON, CreatureState::ONFIRE, CreatureState::PEACE, CreatureState::PILOTINGPOBSHIP, CreatureState::PILOTINGSHIP, CombatManager::PISTOL, CreatureState::POISONED, CombatManager::POLEARM, CommandEffect::POSTUREDOWN, CommandEffect::POSTUREUP, CreatureLocomotion::PRONE, CreatureState::RALLIED, CombatManager::RANDOM, CombatManager::RANGEDWEAPON, CreatureLocomotion::RIDINGCREATURE, CreatureState::RIDINGMOUNT, CombatManager::RIFLE, CombatManager::RIGHTFOOTTRAIL, CombatManager::RIGHTHANDTRAIL, CreatureLocomotion::RUNNING, CreatureState::SHIPGUNNER, CreatureState::SHIPINTERIOR, CreatureState::SHIPOPERATIONS, CreatureLocomotion::SITTING, CreatureState::SITTINGONCHAIR, CreatureLocomotion::SKILLANIMATING, CreatureLocomotion::SNEAKING, CombatManager::SPECIALHEAVYWEAPON, CreatureLocomotion::STANDING, CommandEffect::STUN, CreatureState::STUNNED, CreatureState::SWIMMING, CombatManager::THROWNWEAPON, CreatureState::TUMBLING, CombatManager::TWOHANDMELEEWEAPON, CreatureLocomotion::WALKING, CombatManager::WEAPONATTACK, and CombatManager::WEAPONTRAIL.
Referenced by CommandConfigManager().
void CommandConfigManager::registerSpecialCommands (CommandList * sCommands)
Definition at line 299 of file CommandConfigManager.cpp.
References createCommand(), server::zone::managers::objectcontroller::command::CommandList::put(), server, server::zone::objects::creature::commands::QueueCommand::setCommandGroup(), and slashCommands.
int CommandConfigManager::runSlashCommandsFile (lua_State * L) static
Definition at line 452 of file CommandConfigManager.cpp.
Referenced by registerFunctions().
Member Data Documentation
const int server::zone::managers::objectcontroller::command::CommandConfigManager::ADDTOCOMBATQUEUE = 74 static
Definition at line 151 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::AIMING = 33 static
Definition at line 109 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::ALERT = 34 static
Definition at line 110 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::BERSERK = 35 static
Definition at line 111 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::BLEEDING = 54 static
Definition at line 130 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::BLINDED = 43 static
Definition at line 119 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::BLOCKING = 29 static
Definition at line 103 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::CALLONTARGET = 68 static
Definition at line 145 of file CommandConfigManager.h.
const int server::zone::managers::objectcontroller::command::CommandConfigManager::CHARACTERABILITY = 7 static
Definition at line 79 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::CLIMBING = 18 static
Definition at line 92 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::CLIMBINGSTATIONARY = 17 static
Definition at line 91 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::COMBAT = 31 static
Definition at line 107 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::COMBATATTITUDEAGGRESSIVE = 39 static
Definition at line 115 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::COMBATATTITUDEEVASIVE = 37 static
Definition at line 113 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::COMBATATTITUDENORMAL = 38 static
Definition at line 114 of file CommandConfigManager.h.
Referenced by loadCommandData().
CommandFactory<QueueCommand* (String, ZoneProcessServer*), String> server::zone::managers::objectcontroller::command::CommandConfigManager::commandFactory
Definition at line 153 of file CommandConfigManager.h.
Referenced by createCommand(), and registerCommands().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::COMMANDGROUP = 69 static
Definition at line 146 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::COMMANDNAME = 0 static
Definition at line 72 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::COVER = 30 static
Definition at line 106 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::CPPHOOK = 4 static
Definition at line 76 of file CommandConfigManager.h.
const int server::zone::managers::objectcontroller::command::CommandConfigManager::CRAFTING = 50 static
Definition at line 126 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::CRAWLING = 16 static
Definition at line 90 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::CROUCHSNEAKING = 13 static
Definition at line 87 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::CROUCHWALKING = 14 static
Definition at line 88 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::DEAD = 28 static
Definition at line 102 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::DEFAULTPRIORITY = 1 static
Definition at line 73 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::DEFAULTTIME = 6 static
Definition at line 78 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::DISABLED = 70 static
Definition at line 147 of file CommandConfigManager.h.
const int server::zone::managers::objectcontroller::command::CommandConfigManager::DISEASED = 55 static
Definition at line 131 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::DISPLAYGROUP = 73 static
Definition at line 150 of file CommandConfigManager.h.
const int server::zone::managers::objectcontroller::command::CommandConfigManager::DIZZY = 44 static
Definition at line 120 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::DRIVINGVEHICLE = 24 static
Definition at line 98 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::FAILCPPHOOK = 5 static
Definition at line 77 of file CommandConfigManager.h.
const int server::zone::managers::objectcontroller::command::CommandConfigManager::FAILSCRIPT_HOOK = 3 static
Definition at line 75 of file CommandConfigManager.h.
const int server::zone::managers::objectcontroller::command::CommandConfigManager::FEIGNDEATH = 36 static
Definition at line 112 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::FLYING = 20 static
Definition at line 94 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::FROZEN = 47 static
Definition at line 123 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::GLOWINGJEDI = 51 static
Definition at line 127 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::GODLEVEL = 72 static
Definition at line 149 of file CommandConfigManager.h.
const int server::zone::managers::objectcontroller::command::CommandConfigManager::HOVERING = 19 static
Definition at line 93 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::IMMOBILIZED = 46 static
Definition at line 122 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::INCAPACITATED = 27 static
Definition at line 101 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::INTIMIDATED = 45 static
Definition at line 121 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::KNEELING = 12 static
Definition at line 86 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::KNOCKEDDOWN = 26 static
Definition at line 100 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::LYINGDOWN = 21 static
Definition at line 95 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::MASKSCENT = 52 static
Definition at line 128 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::MAXRANGETOTARGET = 71 static
Definition at line 148 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::MOUNTEDCREATURE = 58 static
Definition at line 134 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::ONFIRE = 56 static
Definition at line 132 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::PEACE = 32 static
Definition at line 108 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::PILOTINGPOBSHIP = 60 static
Definition at line 136 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::PILOTINGSHIP = 59 static
Definition at line 135 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::POISONED = 53 static
Definition at line 129 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::PRONE = 15 static
Definition at line 89 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::RALLIED = 41 static
Definition at line 117 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::RIDINGCREATURE = 25 static
Definition at line 99 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::RIDINGMOUNT = 57 static
Definition at line 133 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::RUNNING = 11 static
Definition at line 85 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::SCRIPTHOOK = 2 static
Definition at line 74 of file CommandConfigManager.h.
ZoneProcessServer * CommandConfigManager::server = NULL static
Definition at line 155 of file CommandConfigManager.h.
Referenced by CommandConfigManager(), createCommand(), and registerSpecialCommands().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::SHIPGUNNER = 62 static
Definition at line 138 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::SHIPINTERIOR = 63 static
Definition at line 139 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::SHIPOPERATIONS = 61 static
Definition at line 137 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::SITTING = 22 static
Definition at line 96 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::SITTINGONCHAIR = 49 static
Definition at line 125 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::SKILLANIMATING = 23 static
Definition at line 97 of file CommandConfigManager.h.
Referenced by loadCommandData().
CommandList * CommandConfigManager::slashCommands = NULL static
Definition at line 156 of file CommandConfigManager.h.
Referenced by addCommand(), createCommand(), parseAlternativeNames(), and registerSpecialCommands().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::SNEAKING = 9 static
Definition at line 83 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::STANDING = 8 static
Definition at line 82 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::STRINGID = 66 static
Definition at line 143 of file CommandConfigManager.h.
const int server::zone::managers::objectcontroller::command::CommandConfigManager::STUNNED = 42 static
Definition at line 118 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::SWIMMING = 48 static
Definition at line 124 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::TARGETTYPE = 65 static
Definition at line 142 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::TEMPSCRIPT = 64 static
Definition at line 141 of file CommandConfigManager.h.
const int server::zone::managers::objectcontroller::command::CommandConfigManager::TUMBLING = 40 static
Definition at line 116 of file CommandConfigManager.h.
Referenced by loadCommandData().
const int server::zone::managers::objectcontroller::command::CommandConfigManager::VISIBLE = 67 static
Definition at line 144 of file CommandConfigManager.h.
const int server::zone::managers::objectcontroller::command::CommandConfigManager::WALKING = 10 static
Definition at line 84 of file CommandConfigManager.h.
Referenced by loadCommandData().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/objectcontroller/command/CommandConfigManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/objectcontroller/command/CommandConfigManager.cpp