Core3: MobileOutfitGroup Class Reference
MobileOutfitGroup Class Reference
#include <MobileOutfitGroup.h>
Public Member Functions
MobileOutfitGroup ()
MobileOutfitGroup (const MobileOutfitGroup &o)
MobileOutfitGroup & operator= (const MobileOutfitGroup &o)
void readObject (LuaObject *luaObject)
Vector< MobileOutfit > * getOutfits ()
Private Attributes
Vector< MobileOutfit > outfits
Detailed Description
Definition at line 13 of file MobileOutfitGroup.h.
Constructor & Destructor Documentation
MobileOutfitGroup::MobileOutfitGroup () inline
Definition at line 16 of file MobileOutfitGroup.h.
MobileOutfitGroup::MobileOutfitGroup (const MobileOutfitGroup & o) inline
Definition at line 20 of file MobileOutfitGroup.h.
References outfits.
Member Function Documentation
Vector<MobileOutfit>* MobileOutfitGroup::getOutfits () inline
Definition at line 48 of file MobileOutfitGroup.h.
References outfits.
Referenced by server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData(), and server::zone::objects::creature::AiAgentImplementation::loadTemplateData().
MobileOutfitGroup& MobileOutfitGroup::operator= (const MobileOutfitGroup & o) inline
Definition at line 24 of file MobileOutfitGroup.h.
References outfits.
void MobileOutfitGroup::readObject (LuaObject * luaObject) inline
Definition at line 33 of file MobileOutfitGroup.h.
References outfits, and MobileOutfit::readObject().
Member Data Documentation
Vector<MobileOutfit> MobileOutfitGroup::outfits private
Definition at line 14 of file MobileOutfitGroup.h.
Referenced by getOutfits(), MobileOutfitGroup(), operator=(), and readObject().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/mobile/MobileOutfitGroup.h