Core3: server::zone::objects::player::sessions::crafting::CraftingSessionAdapter Class Reference
server::zone::objects::player::sessions::crafting::CraftingSessionAdapter Class Reference
#include <CraftingSession.h>
Public Member Functions
CraftingSessionAdapter (CraftingSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession (CraftingTool *tool, CraftingStation *station)
int cancelSession ()
int clearSession ()
ManagedWeakReference
< ManufactureSchematic * > getSchematic ()
void selectDraftSchematic (int index)
void sendIngredientForUIListen ()
void addIngredient (TangibleObject *tano, int slotUpdated, int clientCounter)
void removeIngredient (TangibleObject *tano, int slotUpdated, int clientCounter)
void nextCraftingStage (int clientCounter)
void experiment (int rowsAttempted, const String &expAttempt, int clientCounter)
void customization (const String &name, byte templateChoice, int schematicCount, const String &customizationString)
void createPrototype (int clientCounter, bool practice)
void createManufactureSchematic (int clientCounter)
int getState ()
Detailed Description
Definition at line 476 of file CraftingSession.h.
Constructor & Destructor Documentation
CraftingSessionAdapter::CraftingSessionAdapter (CraftingSession * impl)
Definition at line 411 of file CraftingSession.cpp.
Member Function Documentation
void CraftingSessionAdapter::addIngredient (TangibleObject * tano, int slotUpdated, int clientCounter)
Definition at line 519 of file CraftingSession.cpp.
Referenced by invokeMethod().
int CraftingSessionAdapter::cancelSession ()
Definition at line 499 of file CraftingSession.cpp.
Referenced by invokeMethod().
int CraftingSessionAdapter::clearSession ()
Definition at line 503 of file CraftingSession.cpp.
Referenced by invokeMethod().
void CraftingSessionAdapter::createManufactureSchematic (int clientCounter)
Definition at line 543 of file CraftingSession.cpp.
Referenced by invokeMethod().
void CraftingSessionAdapter::createPrototype (int clientCounter, bool practice)
Definition at line 539 of file CraftingSession.cpp.
Referenced by invokeMethod().
void CraftingSessionAdapter::customization (const String & name, byte templateChoice, int schematicCount, const String & customizationString)
Definition at line 535 of file CraftingSession.cpp.
Referenced by invokeMethod().
void CraftingSessionAdapter::experiment (int rowsAttempted, const String & expAttempt, int clientCounter)
Definition at line 531 of file CraftingSession.cpp.
Referenced by invokeMethod().
ManagedWeakReference< ManufactureSchematic * > CraftingSessionAdapter::getSchematic ()
Definition at line 507 of file CraftingSession.cpp.
Referenced by invokeMethod().
int CraftingSessionAdapter::getState ()
Definition at line 547 of file CraftingSession.cpp.
Referenced by invokeMethod().
int CraftingSessionAdapter::initializeSession (CraftingTool * tool, CraftingStation * station)
Definition at line 495 of file CraftingSession.cpp.
Referenced by invokeMethod().
void CraftingSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 414 of file CraftingSession.cpp.
References addIngredient(), cancelSession(), clearSession(), createManufactureSchematic(), createPrototype(), customization(), experiment(), getSchematic(), getState(), initializeSession(), nextCraftingStage(), removeIngredient(), RPC_ADDINGREDIENT__TANGIBLEOBJECT_INT_INT_, RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_CREATEMANUFACTURESCHEMATIC__INT_, RPC_CREATEPROTOTYPE__INT_BOOL_, RPC_CUSTOMIZATION__STRING_BYTE_INT_STRING_, RPC_EXPERIMENT__INT_STRING_INT_, RPC_GETSCHEMATIC__, RPC_GETSTATE__, RPC_INITIALIZESESSION__CRAFTINGTOOL_CRAFTINGSTATION_, RPC_NEXTCRAFTINGSTAGE__INT_, RPC_REMOVEINGREDIENT__TANGIBLEOBJECT_INT_INT_, RPC_SELECTDRAFTSCHEMATIC__INT_, RPC_SENDINGREDIENTFORUILISTEN__, selectDraftSchematic(), and sendIngredientForUIListen().
void CraftingSessionAdapter::nextCraftingStage (int clientCounter)
Definition at line 527 of file CraftingSession.cpp.
Referenced by invokeMethod().
void CraftingSessionAdapter::removeIngredient (TangibleObject * tano, int slotUpdated, int clientCounter)
Definition at line 523 of file CraftingSession.cpp.
Referenced by invokeMethod().
void CraftingSessionAdapter::selectDraftSchematic (int index)
Definition at line 511 of file CraftingSession.cpp.
Referenced by invokeMethod().
void CraftingSessionAdapter::sendIngredientForUIListen ()
Definition at line 515 of file CraftingSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/crafting/CraftingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/crafting/CraftingSession.cpp