Core3: server::zone::objects::region::CityRegionImplementation Class Reference
server::zone::objects::region::CityRegionImplementation Class Reference
#include <CityRegion.h>
Public Member Functions
CityRegionImplementation ()
CityRegionImplementation (DummyConstructorParameter *param)
void initialize ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void notifyEnter (SceneObject *object)
void notifyExit (SceneObject *object)
Region * addRegion (float x, float y, float radius, bool persistent)
void rescheduleUpdateEvent (unsigned int seconds)
void destroyActiveAreas ()
void addMilitiaMember (unsigned long long objectid)
void removeMilitiaMember (unsigned long long objectid)
bool isMilitiaMember (unsigned long long objectid)
void addZoningRights (unsigned long long objectid, unsigned int duration=86400)
void removeZoningRights (unsigned long long objectid)
bool hasZoningRights (unsigned long long objectid)
bool containsPoint (float x, float y)
void cleanupCitizens ()
Time * getNextUpdateTime ()
int getCurrentPlayerCount ()
void addCitizen (unsigned long long citizenID)
void removeCitizen (unsigned long long citizenID)
void addBannedPlayer (unsigned long long playerid)
void removeBannedPlayer (unsigned long long playerid)
bool isCitizen (unsigned long long citizenID)
int getTimeToUpdate ()
int getCitizenCount ()
byte getCityRank ()
bool isBanned (unsigned long long playerID)
CitizenList * getCitizenList ()
CitizenList * getMilitiaMembers ()
CitizenList * getBannedPlayers ()
bool isRegistered ()
Zone * getZone ()
String getRegionName ()
unsigned long long getMayorID ()
float getPositionX ()
float getPositionY ()
float getRadius ()
Region * getRegion (int idx)
int getRegionsCount ()
int getStructuresCount ()
int getCommercialStructuresCount ()
int getAllStructuresCount ()
String getCitySpecialization ()
float getCityTreasury ()
bool isMayor (unsigned long long objectid)
bool isZoningEnabled ()
bool isClientRegion ()
StructureObject * getCityHall ()
void setZone (Zone *zne)
void setCustomRegionName (const String &name)
void setCitySpecialization (const String &spec)
void setRegionName (const String &fullPath)
void setCityTreasury (float val)
float addToCityTreasury (float val)
float subtractFromCityTreasury (float val)
int getMaxWithdrawal ()
Vector< ManagedReference
< TangibleObject * > > * getVendorsInCity ()
void setRegionName (const StringId &name)
void setCityRank (byte rank)
void setMayorID (unsigned long long id)
void setRegistered (bool val)
void setZoningEnabled (bool val)
void setRadius (float rad)
void setCityHall (StructureObject *building)
void removeShuttleInstallation ()
bool hasShuttleInstallation ()
void setShuttleID (unsigned long long id)
int getMissionTerminalCount ()
int getDecorationCount ()
int getSkillTrainerCount ()
void addMissionTerminal (SceneObject *mt)
void addDecoration (SceneObject *deco)
void addSkillTrainer (SceneObject *trainer)
void removeMissionTerminal (SceneObject *mt)
void removeDecoration (SceneObject *deco)
void removeSkillTrainers (SceneObject *trainer)
void addBazaar (TangibleObject *ter)
TangibleObject * getBazaar (int idx)
int getBazaarCount ()
void removeAllSkillTrainers ()
void removeAllTerminals ()
void removeAllDecorations ()
void updateMilitia ()
void addStructure (StructureObject *structure)
void addCommercialStructure (StructureObject *structure)
void removeStructure (StructureObject *structure)
void removeCommercialStructure (StructureObject *structure)
bool hasUniqueStructure (unsigned int crc)
void destroyAllStructuresForRank (byte rank)
void addCandidate (unsigned long long candidateoid)
void setMayoralVote (unsigned long long voteroid, unsigned long long candidateoid)
int getCandidateVotes (unsigned long long candidateoid)
VectorMap< unsigned long long,
int > * getCandidates ()
VectorMap< unsigned long long,
unsigned long long > * getMayoralVotes ()
void resetCandidates ()
void resetMayoralVotes ()
void removeCandidate (unsigned long long candidateoid)
bool isCandidate (unsigned long long candidateoid)
bool isVotingPeriodOver ()
bool isVotingPeriod ()
bool isVotingLocked ()
void resetVotingPeriod ()
bool isLoaded ()
void setLoaded ()
void applySpecializationModifiers (CreatureObject *creature)
void removeSpecializationModifiers (CreatureObject *creature)
int getPropertyTax ()
int getIncomeTax ()
int getSalesTax ()
int getTravelTax ()
int getGarageTax ()
int getTax (int tax)
void setTax (int tax, int value)
StructureObject * getCivicStructure (int indx)
StructureObject * getCommercialStructure (int indx)
SceneObject * getCityDecoration (int indx)
SceneObject * getCityMissionTerminal (int indx)
SceneObject * getCitySkillTrainer (int indx)
void transferCivicStructuresToMayor ()
void cleanupDuplicateCityStructures ()
void removeDecorationsOutsideCity (int newRadius)
void removeTrainersOutsideCity (int newRadius)
void removeTerminalsOutsideCity (int newRadius)
void removeStructuresOutsideCity (int newRadius)
bool isInsideRadius (SceneObject *obj, int radiusToUse)
void removeAmenitiesOutsideCity (int newRadius)
void cleanupDecorations (int decorationLimit)
operator const CityRegion * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< CityRegion * > _this
Static Public Attributes
static const byte RANK_CLIENT = 0
static const byte RANK_OUTPOST = 1
static const byte RANK_VILLAGE = 2
static const byte RANK_TOWNSHIP = 3
static const byte RANK_CITY = 4
static const byte RANK_METROPOLIS = 5
static const byte TAX_PROPERTY = 0
static const byte TAX_INCOME = 1
static const byte TAX_SALES = 2
static const byte TAX_TRAVEL = 3
static const byte TAX_GARAGE = 4
Protected Member Functions
virtual ~CityRegionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
byte cityRank
StringId regionName
VectorMap< unsigned long long,
int > candidates
VectorMap< unsigned long long,
unsigned long long > mayoralVotes
AtomicInteger currentPlayers
String customRegionName
ZoneReference zone
VectorMap< unsigned long long,
unsigned int > zoningRights
CitizenList militiaMembers
CitizenList citizenList
CitizenList bannedList
SortedVector< unsigned long long > completeStructureList
Mutex structureListMutex
float cityTreasury
unsigned long long mayorID
bool zoningEnabled
bool registered
bool hasShuttle
unsigned long long shuttleID
bool loaded
Vector< int > taxes
Time nextUpdateTime
Time nextInauguration
Reference< CityUpdateEvent * > cityUpdateEvent
String citySpecialization
ManagedReference
< StructureObject * > cityHall
SortedVector< ManagedReference
< Region * > > regions
SortedVector< ManagedReference
< StructureObject * > > structures
SortedVector< ManagedReference
< StructureObject * > > commercialStructures
SortedVector< ManagedReference
< SceneObject * > > cityMissionTerminals
SortedVector< ManagedReference
< SceneObject * > > cityDecorations
SortedVector< ManagedReference
< SceneObject * > > citySkillTrainers
VectorMap< unsigned long long,
ManagedReference
< TangibleObject * > > bazaars
Friends
class CityRegion
Detailed Description
Definition at line 461 of file CityRegion.h.
Constructor & Destructor Documentation
CityRegionImplementation::CityRegionImplementation ()
Definition at line 2185 of file CityRegion.cpp.
References _initializeImplementation(), candidates, commercialStructures, completeStructureList, initialize(), loaded, mayoralVotes, structures, and taxes.
CityRegionImplementation::CityRegionImplementation (DummyConstructorParameter * param)
Definition at line 1735 of file CityRegion.cpp.
References _initializeImplementation().
CityRegionImplementation::~CityRegionImplementation () protected virtual
Definition at line 1740 of file CityRegion.cpp.
Member Function Documentation
DistributedObjectStub * CityRegionImplementation::_getStub ()
Definition at line 1760 of file CityRegion.cpp.
References _this.
void CityRegionImplementation::_initializeImplementation () protected
Definition at line 1747 of file CityRegion.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CityRegionImplementation().
void CityRegionImplementation::_serializationHelperMethod () protected
Definition at line 1796 of file CityRegion.cpp.
Referenced by _initializeImplementation().
void CityRegionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 1755 of file CityRegion.cpp.
References _this.
Referenced by server::zone::objects::region::CityRegion::CityRegion().
void CityRegionImplementation::addBannedPlayer (unsigned long long playerid)
Definition at line 2282 of file CityRegion.cpp.
References bannedList.
Referenced by server::zone::objects::region::CityRegion::addBannedPlayer().
void CityRegionImplementation::addBazaar (TangibleObject * ter)
Definition at line 2580 of file CityRegion.cpp.
References bazaars, and server::zone::objects::scene::SceneObject::getObjectID().
Referenced by server::zone::objects::region::CityRegion::addBazaar().
void CityRegionImplementation::addCandidate (unsigned long long candidateoid)
Adds a candidate to the ballot.
Definition at line 2631 of file CityRegion.cpp.
References candidates.
Referenced by server::zone::objects::region::CityRegion::addCandidate().
void CityRegionImplementation::addCitizen (unsigned long long citizenID)
Definition at line 2263 of file CityRegion.cpp.
References citizenList.
Referenced by server::zone::objects::region::CityRegion::addCitizen(), and notifyEnter().
void CityRegionImplementation::addCommercialStructure (StructureObject * structure)
Definition at line 2604 of file CityRegion.cpp.
References commercialStructures, and structureListMutex.
Referenced by server::zone::objects::region::CityRegion::addCommercialStructure(), and notifyEnter().
void CityRegionImplementation::addDecoration (SceneObject * deco)
Definition at line 2547 of file CityRegion.cpp.
References cityDecorations, and structureListMutex.
Referenced by server::zone::objects::region::CityRegion::addDecoration(), and notifyEnter().
void CityRegionImplementation::addMilitiaMember (unsigned long long objectid)
Definition at line 2217 of file CityRegion.cpp.
References militiaMembers.
Referenced by server::zone::objects::region::CityRegion::addMilitiaMember().
void CityRegionImplementation::addMissionTerminal (SceneObject * mt)
Definition at line 2542 of file CityRegion.cpp.
References cityMissionTerminals.
Referenced by server::zone::objects::region::CityRegion::addMissionTerminal().
Region * CityRegionImplementation::addRegion (float x, float y, float radius, bool persistent)
Definition at line 142 of file CityRegionImplementation.cpp.
References _this, isClientRegion(), regionName, regions, and zone.
Referenced by server::zone::objects::region::CityRegion::addRegion().
void CityRegionImplementation::addSkillTrainer (SceneObject * trainer)
Definition at line 2556 of file CityRegion.cpp.
References citySkillTrainers.
Referenced by server::zone::objects::region::CityRegion::addSkillTrainer().
void CityRegionImplementation::addStructure (StructureObject * structure)
Definition at line 2595 of file CityRegion.cpp.
References structureListMutex, and structures.
Referenced by server::zone::objects::region::CityRegion::addStructure(), and notifyEnter().
float CityRegionImplementation::addToCityTreasury (float val)
Definition at line 2454 of file CityRegion.cpp.
References cityTreasury.
Referenced by server::zone::objects::region::CityRegion::addToCityTreasury().
void CityRegionImplementation::addZoningRights (unsigned long long objectid, unsigned int duration = 86400)
Definition at line 393 of file CityRegionImplementation.cpp.
References zoningRights.
Referenced by server::zone::objects::region::CityRegion::addZoningRights().
void CityRegionImplementation::applySpecializationModifiers (CreatureObject * creature)
Definition at line 553 of file CityRegionImplementation.cpp.
References server::zone::objects::creature::CreatureObject::addSkillMod(), citySpecialization, server::zone::ZoneServer::getCityManager(), server::zone::managers::city::CityManager::getCitySpecialization(), CitySpecialization::getSkillMods(), getZone(), server::zone::Zone::getZoneServer(), and server::zone::objects::creature::CreatureObject::removeAllSkillModsOfType().
Referenced by server::zone::objects::region::CityRegion::applySpecializationModifiers(), and notifyEnter().
void CityRegionImplementation::cleanupCitizens ()
Definition at line 346 of file CityRegionImplementation.cpp.
References citizenList, completeStructureList, getMayorID(), server::zone::objects::structure::StructureObject::getOwnerObjectID(), isCitizen(), removeCitizen(), structureListMutex, and zone.
Referenced by server::zone::objects::region::CityRegion::cleanupCitizens().
void CityRegionImplementation::cleanupDecorations (int decorationLimit)
Definition at line 789 of file CityRegionImplementation.cpp.
References _this, cityDecorations, server::zone::objects::scene::SceneObject::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), StructureManager::destroyStructure(), getCityDecoration(), and server::zone::objects::scene::SceneObject::isStructureObject().
Referenced by server::zone::objects::region::CityRegion::cleanupDecorations().
void CityRegionImplementation::cleanupDuplicateCityStructures ()
Definition at line 661 of file CityRegionImplementation.cpp.
References cityDecorations, commercialStructures, getCommercialStructuresCount(), getDecorationCount(), getStructuresCount(), and structures.
Referenced by server::zone::objects::region::CityRegion::cleanupDuplicateCityStructures().
bool CityRegionImplementation::containsPoint (float x, float y)
Definition at line 2237 of file CityRegion.cpp.
References regions.
Referenced by server::zone::objects::region::CityRegion::containsPoint().
void CityRegionImplementation::destroyActiveAreas ()
Definition at line 429 of file CityRegionImplementation.cpp.
References regions.
Referenced by server::zone::objects::region::CityRegion::destroyActiveAreas().
void CityRegionImplementation::destroyAllStructuresForRank (byte rank)
Definition at line 462 of file CityRegionImplementation.cpp.
References _this, StructureManager::destroyStructure(), SharedStructureObjectTemplate::getCityRankRequired(), SharedStructureObjectTemplate::isCivicStructure(), structures, and zone.
Referenced by server::zone::objects::region::CityRegion::destroyAllStructuresForRank().
void CityRegionImplementation::finalize () protected
Definition at line 1744 of file CityRegion.cpp.
int CityRegionImplementation::getAllStructuresCount ()
Definition at line 2399 of file CityRegion.cpp.
References completeStructureList.
Referenced by server::zone::objects::region::CityRegion::getAllStructuresCount().
CitizenList * CityRegionImplementation::getBannedPlayers ()
Definition at line 2322 of file CityRegion.cpp.
References bannedList.
Referenced by server::zone::objects::region::CityRegion::getBannedPlayers().
TangibleObject * CityRegionImplementation::getBazaar (int idx)
Definition at line 2585 of file CityRegion.cpp.
References bazaars.
Referenced by server::zone::objects::region::CityRegion::getBazaar().
int CityRegionImplementation::getBazaarCount ()
Definition at line 2590 of file CityRegion.cpp.
References bazaars.
Referenced by server::zone::objects::region::CityRegion::getBazaarCount().
VectorMap< unsigned long long, int > * CityRegionImplementation::getCandidates ()
Definition at line 2656 of file CityRegion.cpp.
References candidates.
Referenced by server::zone::objects::region::CityRegion::getCandidates().
int CityRegionImplementation::getCandidateVotes (unsigned long long candidateoid)
Definition at line 2651 of file CityRegion.cpp.
References candidates.
Referenced by server::zone::objects::region::CityRegion::getCandidateVotes().
int CityRegionImplementation::getCitizenCount ()
Definition at line 2297 of file CityRegion.cpp.
References citizenList.
Referenced by server::zone::objects::region::CityRegion::getCitizenCount().
CitizenList * CityRegionImplementation::getCitizenList ()
Definition at line 2312 of file CityRegion.cpp.
References citizenList.
Referenced by server::zone::objects::region::CityRegion::getCitizenList().
SceneObject * CityRegionImplementation::getCityDecoration (int indx)
Definition at line 2757 of file CityRegion.cpp.
References cityDecorations.
Referenced by cleanupDecorations(), server::zone::objects::region::CityRegion::getCityDecoration(), and removeDecorationsOutsideCity().
StructureObject * CityRegionImplementation::getCityHall ()
Definition at line 2429 of file CityRegion.cpp.
References cityHall.
Referenced by server::zone::objects::region::CityRegion::getCityHall(), and transferCivicStructuresToMayor().
SceneObject * CityRegionImplementation::getCityMissionTerminal (int indx)
Definition at line 2762 of file CityRegion.cpp.
References cityMissionTerminals.
Referenced by server::zone::objects::region::CityRegion::getCityMissionTerminal(), and removeTerminalsOutsideCity().
byte CityRegionImplementation::getCityRank ()
Definition at line 2302 of file CityRegion.cpp.
References cityRank.
Referenced by server::zone::objects::region::CityRegion::getCityRank().
SceneObject * CityRegionImplementation::getCitySkillTrainer (int indx)
Definition at line 2767 of file CityRegion.cpp.
References citySkillTrainers.
Referenced by server::zone::objects::region::CityRegion::getCitySkillTrainer(), and removeTrainersOutsideCity().
String CityRegionImplementation::getCitySpecialization ()
Definition at line 2404 of file CityRegion.cpp.
References citySpecialization.
Referenced by server::zone::objects::region::CityRegion::getCitySpecialization().
float CityRegionImplementation::getCityTreasury ()
Definition at line 2409 of file CityRegion.cpp.
References cityTreasury.
Referenced by server::zone::objects::region::CityRegion::getCityTreasury().
StructureObject * CityRegionImplementation::getCivicStructure (int indx)
Definition at line 2747 of file CityRegion.cpp.
References structures.
Referenced by server::zone::objects::region::CityRegion::getCivicStructure(), and removeStructuresOutsideCity().
StructureObject * CityRegionImplementation::getCommercialStructure (int indx)
Definition at line 2752 of file CityRegion.cpp.
References commercialStructures.
Referenced by server::zone::objects::region::CityRegion::getCommercialStructure().
int CityRegionImplementation::getCommercialStructuresCount ()
Definition at line 2394 of file CityRegion.cpp.
References commercialStructures.
Referenced by cleanupDuplicateCityStructures(), and server::zone::objects::region::CityRegion::getCommercialStructuresCount().
int CityRegionImplementation::getCurrentPlayerCount ()
Definition at line 2258 of file CityRegion.cpp.
References currentPlayers.
Referenced by server::zone::objects::region::CityRegion::getCurrentPlayerCount().
int CityRegionImplementation::getDecorationCount ()
Definition at line 2532 of file CityRegion.cpp.
References cityDecorations.
Referenced by cleanupDuplicateCityStructures(), server::zone::objects::region::CityRegion::getDecorationCount(), and removeDecorationsOutsideCity().
int CityRegionImplementation::getGarageTax ()
Definition at line 2726 of file CityRegion.cpp.
References TAX_GARAGE, and taxes.
Referenced by server::zone::objects::region::CityRegion::getGarageTax().
int CityRegionImplementation::getIncomeTax ()
Definition at line 2711 of file CityRegion.cpp.
References TAX_INCOME, and taxes.
Referenced by server::zone::objects::region::CityRegion::getIncomeTax().
int CityRegionImplementation::getMaxWithdrawal ()
Definition at line 2478 of file CityRegion.cpp.
Referenced by server::zone::objects::region::CityRegion::getMaxWithdrawal().
VectorMap< unsigned long long, unsigned long long > * CityRegionImplementation::getMayoralVotes ()
Definition at line 2661 of file CityRegion.cpp.
References mayoralVotes.
Referenced by server::zone::objects::region::CityRegion::getMayoralVotes().
unsigned long long CityRegionImplementation::getMayorID ()
Definition at line 2337 of file CityRegion.cpp.
References mayorID.
Referenced by cleanupCitizens(), server::zone::objects::region::CityRegion::getMayorID(), hasZoningRights(), and transferCivicStructuresToMayor().
CitizenList * CityRegionImplementation::getMilitiaMembers ()
Definition at line 2317 of file CityRegion.cpp.
References militiaMembers.
Referenced by server::zone::objects::region::CityRegion::getMilitiaMembers().
int CityRegionImplementation::getMissionTerminalCount ()
Definition at line 2527 of file CityRegion.cpp.
References cityMissionTerminals.
Referenced by server::zone::objects::region::CityRegion::getMissionTerminalCount(), and removeTerminalsOutsideCity().
Time * CityRegionImplementation::getNextUpdateTime ()
Definition at line 2253 of file CityRegion.cpp.
References nextUpdateTime.
Referenced by server::zone::objects::region::CityRegion::getNextUpdateTime().
float CityRegionImplementation::getPositionX ()
Definition at line 2342 of file CityRegion.cpp.
References regions.
Referenced by server::zone::objects::region::CityRegion::getPositionX().
float CityRegionImplementation::getPositionY ()
Definition at line 2352 of file CityRegion.cpp.
References regions.
Referenced by server::zone::objects::region::CityRegion::getPositionY().
int CityRegionImplementation::getPropertyTax ()
Definition at line 2706 of file CityRegion.cpp.
References TAX_PROPERTY, and taxes.
Referenced by server::zone::objects::region::CityRegion::getPropertyTax().
float CityRegionImplementation::getRadius ()
Definition at line 2362 of file CityRegion.cpp.
References customRegionName, regionName, and regions.
Referenced by server::zone::objects::region::CityRegion::getRadius().
Region * CityRegionImplementation::getRegion (int idx)
Definition at line 2379 of file CityRegion.cpp.
References regions.
Referenced by server::zone::objects::region::CityRegion::getRegion().
String CityRegionImplementation::getRegionName ()
Definition at line 442 of file CityRegionImplementation.cpp.
References customRegionName, server::zone::objects::scene::variables::StringId::getFullPath(), and regionName.
Referenced by server::zone::objects::region::CityRegion::getRegionName(), notifyEnter(), notifyExit(), and notifyLoadFromDatabase().
int CityRegionImplementation::getRegionsCount ()
Definition at line 2384 of file CityRegion.cpp.
References regions.
Referenced by server::zone::objects::region::CityRegion::getRegionsCount().
int CityRegionImplementation::getSalesTax ()
Definition at line 2716 of file CityRegion.cpp.
References TAX_SALES, and taxes.
Referenced by server::zone::objects::region::CityRegion::getSalesTax().
int CityRegionImplementation::getSkillTrainerCount ()
Definition at line 2537 of file CityRegion.cpp.
References citySkillTrainers.
Referenced by server::zone::objects::region::CityRegion::getSkillTrainerCount(), and removeTrainersOutsideCity().
int CityRegionImplementation::getStructuresCount ()
Definition at line 2389 of file CityRegion.cpp.
References structures.
Referenced by cleanupDuplicateCityStructures(), server::zone::objects::region::CityRegion::getStructuresCount(), and removeStructuresOutsideCity().
int CityRegionImplementation::getTax (int tax)
Definition at line 2731 of file CityRegion.cpp.
References taxes.
Referenced by server::zone::objects::region::CityRegion::getTax().
int CityRegionImplementation::getTimeToUpdate ()
Definition at line 185 of file CityRegionImplementation.cpp.
References nextUpdateTime.
Referenced by server::zone::objects::region::CityRegion::getTimeToUpdate().
int CityRegionImplementation::getTravelTax ()
Definition at line 2721 of file CityRegion.cpp.
References TAX_TRAVEL, and taxes.
Referenced by server::zone::objects::region::CityRegion::getTravelTax().
Vector< ManagedReference< TangibleObject * > > * CityRegionImplementation::getVendorsInCity ()
Definition at line 387 of file CityRegionImplementation.cpp.
Referenced by server::zone::objects::region::CityRegion::getVendorsInCity().
Zone * CityRegionImplementation::getZone ()
Definition at line 2332 of file CityRegion.cpp.
References zone.
Referenced by applySpecializationModifiers(), server::zone::objects::region::CityRegion::getZone(), and notifyLoadFromDatabase().
bool CityRegionImplementation::hasShuttleInstallation ()
Definition at line 2515 of file CityRegion.cpp.
References hasShuttle.
Referenced by server::zone::objects::region::CityRegion::hasShuttleInstallation().
bool CityRegionImplementation::hasUniqueStructure (unsigned int crc)
Checks if the city has a structure in it's structures list of a particular template type.
Parameters
crc The crc of the template of the structure to search for.
Returns
True if the city has a structure of this type.
Definition at line 449 of file CityRegionImplementation.cpp.
References _this, and structures.
Referenced by server::zone::objects::region::CityRegion::hasUniqueStructure().
bool CityRegionImplementation::hasZoningRights (unsigned long long objectid)
Definition at line 399 of file CityRegionImplementation.cpp.
References getMayorID(), and zoningRights.
Referenced by server::zone::objects::region::CityRegion::hasZoningRights().
void CityRegionImplementation::initialize ()
Definition at line 106 of file CityRegionImplementation.cpp.
References bazaars, cityDecorations, cityHall, cityMissionTerminals, cityRank, citySkillTrainers, cityTreasury, cityUpdateEvent, hasShuttle, mayorID, RANK_CLIENT, registered, shuttleID, zone, zoningEnabled, and zoningRights.
Referenced by CityRegionImplementation(), and server::zone::objects::region::CityRegion::initialize().
void CityRegionImplementation::initializeTransientMembers ()
Definition at line 36 of file CityRegionImplementation.cpp.
References loaded.
Referenced by server::zone::objects::region::CityRegion::initializeTransientMembers(), and readObject().
bool CityRegionImplementation::isBanned (unsigned long long playerID)
Definition at line 2307 of file CityRegion.cpp.
References bannedList.
Referenced by server::zone::objects::region::CityRegion::isBanned().
bool CityRegionImplementation::isCandidate (unsigned long long candidateoid)
Definition at line 2681 of file CityRegion.cpp.
References candidates.
Referenced by server::zone::objects::region::CityRegion::isCandidate().
bool CityRegionImplementation::isCitizen (unsigned long long citizenID)
Definition at line 2292 of file CityRegion.cpp.
References citizenList.
Referenced by cleanupCitizens(), server::zone::objects::region::CityRegion::isCitizen(), and updateMilitia().
bool CityRegionImplementation::isClientRegion ()
Definition at line 2424 of file CityRegion.cpp.
References cityRank, and RANK_CLIENT.
Referenced by addRegion(), server::zone::objects::region::CityRegion::isClientRegion(), notifyEnter(), and notifyExit().
bool CityRegionImplementation::isInsideRadius (SceneObject * obj, int radiusToUse)
Definition at line 781 of file CityRegionImplementation.cpp.
References cityHall.
Referenced by server::zone::objects::region::CityRegion::isInsideRadius(), removeDecorationsOutsideCity(), removeStructuresOutsideCity(), removeTerminalsOutsideCity(), and removeTrainersOutsideCity().
bool CityRegionImplementation::isLoaded ()
Definition at line 2696 of file CityRegion.cpp.
References loaded.
Referenced by server::zone::objects::region::CityRegion::isLoaded(), notifyEnter(), and removeCitizen().
bool CityRegionImplementation::isMayor (unsigned long long objectid)
Definition at line 2414 of file CityRegion.cpp.
References mayorID.
Referenced by server::zone::objects::region::CityRegion::isMayor().
bool CityRegionImplementation::isMilitiaMember (unsigned long long objectid)
Definition at line 2227 of file CityRegion.cpp.
References mayorID, and militiaMembers.
Referenced by server::zone::objects::region::CityRegion::isMilitiaMember().
bool CityRegionImplementation::isRegistered ()
Definition at line 2327 of file CityRegion.cpp.
References registered.
Referenced by server::zone::objects::region::CityRegion::isRegistered(), and notifyLoadFromDatabase().
bool CityRegionImplementation::isVotingLocked ()
Definition at line 535 of file CityRegionImplementation.cpp.
References nextInauguration.
Referenced by server::zone::objects::region::CityRegion::isVotingLocked().
bool CityRegionImplementation::isVotingPeriod ()
Definition at line 2691 of file CityRegion.cpp.
References nextInauguration.
Referenced by server::zone::objects::region::CityRegion::isVotingPeriod().
bool CityRegionImplementation::isVotingPeriodOver ()
Definition at line 2686 of file CityRegion.cpp.
References nextInauguration.
Referenced by server::zone::objects::region::CityRegion::isVotingPeriodOver().
bool CityRegionImplementation::isZoningEnabled ()
Definition at line 2419 of file CityRegion.cpp.
References zoningEnabled.
Referenced by server::zone::objects::region::CityRegion::isZoningEnabled().
void CityRegionImplementation::lock (bool doLock = true) protected
Definition at line 1768 of file CityRegion.cpp.
References _this.
void CityRegionImplementation::lock (ManagedObject * obj) protected
Definition at line 1772 of file CityRegion.cpp.
References _this.
void CityRegionImplementation::notifyEnter (SceneObject * object)
Definition at line 189 of file CityRegionImplementation.cpp.
References _this, addCitizen(), addCommercialStructure(), addDecoration(), addStructure(), applySpecializationModifiers(), bazaars, citizenList, cityRank, citySpecialization, completeStructureList, currentPlayers, server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::structure::StructureObject::getOwnerObjectID(), getRegionName(), server::zone::objects::scene::SceneObject::isBazaarTerminal(), server::zone::objects::scene::SceneObject::isBuildingObject(), server::zone::objects::structure::StructureObject::isCivicStructure(), isClientRegion(), server::zone::objects::structure::StructureObject::isCommercialStructure(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::scene::SceneObject::isDecoration(), isLoaded(), server::zone::objects::building::BuildingObject::isResidence(), server::zone::objects::scene::SceneObject::isStructureObject(), registered, server::zone::objects::creature::CreatureObject::sendSystemMessage(), structureListMutex, AuctionTerminalDataComponent::updateUID(), and zone.
Referenced by server::zone::objects::region::CityRegion::notifyEnter().
void CityRegionImplementation::notifyExit (SceneObject * object)
Definition at line 268 of file CityRegionImplementation.cpp.
References _this, bazaars, citizenList, completeStructureList, currentPlayers, server::zone::objects::region::Region::getCityRegion(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::structure::StructureObject::getOwnerObjectID(), getRegionName(), server::zone::objects::scene::SceneObject::isBazaarTerminal(), server::zone::objects::scene::SceneObject::isBuildingObject(), server::zone::objects::structure::StructureObject::isCivicStructure(), isClientRegion(), server::zone::objects::structure::StructureObject::isCommercialStructure(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::scene::SceneObject::isDecoration(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::building::BuildingObject::isResidence(), server::zone::objects::scene::SceneObject::isStructureObject(), removeCitizen(), removeCommercialStructure(), removeDecoration(), removeSpecializationModifiers(), removeStructure(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), structureListMutex, and AuctionTerminalDataComponent::updateUID().
Referenced by server::zone::objects::region::CityRegion::notifyExit().
void CityRegionImplementation::notifyLoadFromDatabase ()
Gets called when this objects is loaded from database
Precondition
{ this locked }
Postcondition
{ this locked }
Definition at line 42 of file CityRegionImplementation.cpp.
References _this, server::zone::Zone::addCityRegionToUpdate(), server::zone::managers::planet::PlanetManager::addPlayerCityTravelPoint(), server::zone::managers::planet::PlanetManager::addRegion(), cityRank, server::zone::ZoneServer::getObject(), server::zone::Zone::getPlanetManager(), getRegionName(), getZone(), server::zone::Zone::getZoneName(), server::zone::Zone::getZoneServer(), hasShuttle, isRegistered(), server::zone::Zone::registerObjectWithPlanetaryMap(), server::zone::managers::planet::PlanetManager::scheduleShuttle(), shuttleID, taxes, and zone.
Referenced by server::zone::objects::region::CityRegion::notifyLoadFromDatabase().
CityRegionImplementation::operator const CityRegion * ()
Definition at line 1764 of file CityRegion.cpp.
void CityRegionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 1803 of file CityRegion.cpp.
References initializeTransientMembers(), and readObjectMember().
bool CityRegionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 1822 of file CityRegion.cpp.
References bannedList, candidates, citizenList, cityDecorations, cityHall, cityMissionTerminals, cityRank, citySkillTrainers, citySpecialization, cityTreasury, commercialStructures, currentPlayers, customRegionName, hasShuttle, mayoralVotes, mayorID, militiaMembers, nextInauguration, nextUpdateTime, regionName, regions, registered, shuttleID, structures, taxes, zone, zoningEnabled, and zoningRights.
Referenced by readObject().
void CityRegionImplementation::removeAllDecorations ()
Definition at line 521 of file CityRegionImplementation.cpp.
References cityDecorations.
Referenced by server::zone::objects::region::CityRegion::removeAllDecorations().
void CityRegionImplementation::removeAllSkillTrainers ()
Definition at line 511 of file CityRegionImplementation.cpp.
References citySkillTrainers.
Referenced by server::zone::objects::region::CityRegion::removeAllSkillTrainers().
void CityRegionImplementation::removeAllTerminals ()
Definition at line 502 of file CityRegionImplementation.cpp.
References cityMissionTerminals.
Referenced by server::zone::objects::region::CityRegion::removeAllTerminals().
void CityRegionImplementation::removeAmenitiesOutsideCity (int newRadius)
Definition at line 2772 of file CityRegion.cpp.
References removeDecorationsOutsideCity(), removeStructuresOutsideCity(), removeTerminalsOutsideCity(), and removeTrainersOutsideCity().
Referenced by server::zone::objects::region::CityRegion::removeAmenitiesOutsideCity().
void CityRegionImplementation::removeBannedPlayer (unsigned long long playerid)
Definition at line 2287 of file CityRegion.cpp.
References bannedList.
Referenced by server::zone::objects::region::CityRegion::removeBannedPlayer().
void CityRegionImplementation::removeCandidate (unsigned long long candidateoid)
Definition at line 2676 of file CityRegion.cpp.
References candidates.
Referenced by server::zone::objects::region::CityRegion::removeCandidate().
void CityRegionImplementation::removeCitizen (unsigned long long citizenID)
Definition at line 2268 of file CityRegion.cpp.
References citizenList, isLoaded(), militiaMembers, and structureListMutex.
Referenced by cleanupCitizens(), notifyExit(), and server::zone::objects::region::CityRegion::removeCitizen().
void CityRegionImplementation::removeCommercialStructure (StructureObject * structure)
Definition at line 2622 of file CityRegion.cpp.
References commercialStructures, and structureListMutex.
Referenced by notifyExit(), and server::zone::objects::region::CityRegion::removeCommercialStructure().
void CityRegionImplementation::removeDecoration (SceneObject * deco)
Definition at line 2566 of file CityRegion.cpp.
References cityDecorations, and structureListMutex.
Referenced by notifyExit(), server::zone::objects::region::CityRegion::removeDecoration(), and removeDecorationsOutsideCity().
void CityRegionImplementation::removeDecorationsOutsideCity (int newRadius)
Definition at line 702 of file CityRegionImplementation.cpp.
References _this, cityHall, StructureManager::destroyStructure(), getCityDecoration(), getDecorationCount(), isInsideRadius(), and removeDecoration().
Referenced by removeAmenitiesOutsideCity(), and server::zone::objects::region::CityRegion::removeDecorationsOutsideCity().
void CityRegionImplementation::removeMilitiaMember (unsigned long long objectid)
Definition at line 2222 of file CityRegion.cpp.
References militiaMembers.
Referenced by server::zone::objects::region::CityRegion::removeMilitiaMember(), and updateMilitia().
void CityRegionImplementation::removeMissionTerminal (SceneObject * mt)
Definition at line 2561 of file CityRegion.cpp.
References cityMissionTerminals.
Referenced by server::zone::objects::region::CityRegion::removeMissionTerminal(), and removeTerminalsOutsideCity().
void CityRegionImplementation::removeShuttleInstallation ()
Definition at line 2508 of file CityRegion.cpp.
References hasShuttle, and shuttleID.
Referenced by server::zone::objects::region::CityRegion::removeShuttleInstallation().
void CityRegionImplementation::removeSkillTrainers (SceneObject * trainer)
Definition at line 2575 of file CityRegion.cpp.
References citySkillTrainers.
Referenced by server::zone::objects::region::CityRegion::removeSkillTrainers(), and removeTrainersOutsideCity().
void CityRegionImplementation::removeSpecializationModifiers (CreatureObject * creature)
Definition at line 575 of file CityRegionImplementation.cpp.
References server::zone::objects::creature::CreatureObject::removeAllSkillModsOfType().
Referenced by notifyExit(), and server::zone::objects::region::CityRegion::removeSpecializationModifiers().
void CityRegionImplementation::removeStructure (StructureObject * structure)
Definition at line 2613 of file CityRegion.cpp.
References structureListMutex, and structures.
Referenced by notifyExit(), server::zone::objects::region::CityRegion::removeStructure(), and removeStructuresOutsideCity().
void CityRegionImplementation::removeStructuresOutsideCity (int newRadius)
Definition at line 764 of file CityRegionImplementation.cpp.
References cityHall, StructureManager::destroyStructure(), getCivicStructure(), getStructuresCount(), isInsideRadius(), and removeStructure().
Referenced by removeAmenitiesOutsideCity(), and server::zone::objects::region::CityRegion::removeStructuresOutsideCity().
void CityRegionImplementation::removeTerminalsOutsideCity (int newRadius)
Definition at line 746 of file CityRegionImplementation.cpp.
References _this, cityHall, getCityMissionTerminal(), getMissionTerminalCount(), isInsideRadius(), and removeMissionTerminal().
Referenced by removeAmenitiesOutsideCity(), and server::zone::objects::region::CityRegion::removeTerminalsOutsideCity().
void CityRegionImplementation::removeTrainersOutsideCity (int newRadius)
Definition at line 727 of file CityRegionImplementation.cpp.
References _this, cityHall, getCitySkillTrainer(), getSkillTrainerCount(), isInsideRadius(), and removeSkillTrainers().
Referenced by removeAmenitiesOutsideCity(), and server::zone::objects::region::CityRegion::removeTrainersOutsideCity().
void CityRegionImplementation::removeZoningRights (unsigned long long objectid)
Definition at line 2232 of file CityRegion.cpp.
References zoningRights.
Referenced by server::zone::objects::region::CityRegion::removeZoningRights().
void CityRegionImplementation::rescheduleUpdateEvent (unsigned int seconds)
Definition at line 170 of file CityRegionImplementation.cpp.
References _this, cityRank, cityUpdateEvent, ServerCore::getZoneServer(), and nextUpdateTime.
Referenced by server::zone::objects::region::CityRegion::rescheduleUpdateEvent().
void CityRegionImplementation::resetCandidates ()
At the end of a voting term, all candidates are removed from the ballot.
Definition at line 2666 of file CityRegion.cpp.
References candidates.
Referenced by server::zone::objects::region::CityRegion::resetCandidates().
void CityRegionImplementation::resetMayoralVotes ()
All votes are removed from the ballot.
Definition at line 2671 of file CityRegion.cpp.
References mayoralVotes.
Referenced by server::zone::objects::region::CityRegion::resetMayoralVotes().
void CityRegionImplementation::resetVotingPeriod ()
Definition at line 548 of file CityRegionImplementation.cpp.
References nextInauguration.
Referenced by server::zone::objects::region::CityRegion::resetVotingPeriod().
void CityRegionImplementation::rlock (bool doLock = true) protected
Definition at line 1776 of file CityRegion.cpp.
References _this.
void CityRegionImplementation::runlock (bool doLock = true) protected
Definition at line 1792 of file CityRegion.cpp.
References _this.
void CityRegionImplementation::setCityHall (StructureObject * building)
Definition at line 2503 of file CityRegion.cpp.
References cityHall.
Referenced by server::zone::objects::region::CityRegion::setCityHall().
void CityRegionImplementation::setCityRank (byte rank)
Definition at line 2483 of file CityRegion.cpp.
References cityRank.
Referenced by server::zone::objects::region::CityRegion::setCityRank().
void CityRegionImplementation::setCitySpecialization (const String & spec)
Definition at line 2439 of file CityRegion.cpp.
References citySpecialization.
Referenced by server::zone::objects::region::CityRegion::setCitySpecialization().
void CityRegionImplementation::setCityTreasury (float val)
Definition at line 2449 of file CityRegion.cpp.
References cityTreasury.
Referenced by server::zone::objects::region::CityRegion::setCityTreasury().
void CityRegionImplementation::setCustomRegionName (const String & name)
Definition at line 2434 of file CityRegion.cpp.
References customRegionName.
Referenced by server::zone::objects::region::CityRegion::setCustomRegionName().
void CityRegionImplementation::setLoaded ()
Definition at line 2701 of file CityRegion.cpp.
References loaded.
Referenced by server::zone::objects::region::CityRegion::setLoaded().
void CityRegionImplementation::setMayoralVote (unsigned long long voteroid, unsigned long long candidateoid)
This method does not check to see if they have previously voted. That logic should be contained in the Manager. This is just a data container.
Definition at line 2636 of file CityRegion.cpp.
References candidates, and mayoralVotes.
Referenced by server::zone::objects::region::CityRegion::setMayoralVote().
void CityRegionImplementation::setMayorID (unsigned long long id)
Definition at line 2488 of file CityRegion.cpp.
References mayorID.
Referenced by server::zone::objects::region::CityRegion::setMayorID().
void CityRegionImplementation::setRadius (float rad)
Definition at line 418 of file CityRegionImplementation.cpp.
References regions, and zone.
Referenced by server::zone::objects::region::CityRegion::setRadius().
void CityRegionImplementation::setRegionName (const String & fullPath)
Definition at line 2444 of file CityRegion.cpp.
References regionName.
Referenced by server::zone::objects::region::CityRegion::setRegionName().
void CityRegionImplementation::setRegionName (const StringId & name)
Definition at line 383 of file CityRegionImplementation.cpp.
References regionName.
void CityRegionImplementation::setRegistered (bool val)
Definition at line 2493 of file CityRegion.cpp.
References registered.
Referenced by server::zone::objects::region::CityRegion::setRegistered().
void CityRegionImplementation::setShuttleID (unsigned long long id)
Definition at line 2520 of file CityRegion.cpp.
References hasShuttle, and shuttleID.
Referenced by server::zone::objects::region::CityRegion::setShuttleID().
void CityRegionImplementation::setTax (int tax, int value)
Definition at line 2739 of file CityRegion.cpp.
References taxes.
Referenced by server::zone::objects::region::CityRegion::setTax().
void CityRegionImplementation::setZone (Zone * zne)
Definition at line 414 of file CityRegionImplementation.cpp.
References zone.
Referenced by server::zone::objects::region::CityRegion::setZone().
void CityRegionImplementation::setZoningEnabled (bool val)
Definition at line 2498 of file CityRegion.cpp.
References zoningEnabled.
Referenced by server::zone::objects::region::CityRegion::setZoningEnabled().
float CityRegionImplementation::subtractFromCityTreasury (float val)
Definition at line 2466 of file CityRegion.cpp.
References cityTreasury.
Referenced by server::zone::objects::region::CityRegion::subtractFromCityTreasury().
void CityRegionImplementation::transferCivicStructuresToMayor ()
Definition at line 579 of file CityRegionImplementation.cpp.
References cityDecorations, TransferstructureCommand::doTransferStructure(), getCityHall(), server::zone::objects::player::PlayerObject::getDeclaredResidence(), getMayorID(), server::zone::ZoneServer::getObject(), server::zone::objects::structure::StructureObject::getOwnerCreatureObject(), server::zone::objects::player::PlayerObject::setDeclaredResidence(), structureListMutex, structures, and zone.
Referenced by server::zone::objects::region::CityRegion::transferCivicStructuresToMayor().
void CityRegionImplementation::unlock (bool doLock = true) protected
Definition at line 1788 of file CityRegion.cpp.
References _this.
void CityRegionImplementation::updateMilitia ()
Definition at line 487 of file CityRegionImplementation.cpp.
References _this, isCitizen(), militiaMembers, and removeMilitiaMember().
Referenced by server::zone::objects::region::CityRegion::updateMilitia().
void CityRegionImplementation::wlock (bool doLock = true) protected
Definition at line 1780 of file CityRegion.cpp.
References _this.
void CityRegionImplementation::wlock (ManagedObject * obj) protected
Definition at line 1784 of file CityRegion.cpp.
References _this.
void CityRegionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 1944 of file CityRegion.cpp.
References writeObjectMembers().
int CityRegionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 1951 of file CityRegion.cpp.
References bannedList, candidates, citizenList, cityDecorations, cityHall, cityMissionTerminals, cityRank, citySkillTrainers, citySpecialization, cityTreasury, commercialStructures, currentPlayers, customRegionName, hasShuttle, mayoralVotes, mayorID, militiaMembers, nextInauguration, nextUpdateTime, regionName, regions, registered, shuttleID, structures, taxes, zone, zoningEnabled, and zoningRights.
Referenced by writeObject().
Friends And Related Function Documentation
friend class CityRegion friend
Definition at line 867 of file CityRegion.h.
Member Data Documentation
WeakReference<CityRegion*> server::zone::objects::region::CityRegionImplementation::_this
Definition at line 833 of file CityRegion.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addRegion(), cleanupDecorations(), destroyAllStructuresForRank(), hasUniqueStructure(), lock(), notifyEnter(), notifyExit(), notifyLoadFromDatabase(), removeDecorationsOutsideCity(), removeTerminalsOutsideCity(), removeTrainersOutsideCity(), rescheduleUpdateEvent(), rlock(), runlock(), unlock(), updateMilitia(), and wlock().
CitizenList server::zone::objects::region::CityRegionImplementation::bannedList protected
Definition at line 483 of file CityRegion.h.
Referenced by addBannedPlayer(), getBannedPlayers(), isBanned(), readObjectMember(), removeBannedPlayer(), and writeObjectMembers().
VectorMap<unsigned long long, ManagedReference<TangibleObject* > > server::zone::objects::region::CityRegionImplementation::bazaars protected
Definition at line 527 of file CityRegion.h.
Referenced by addBazaar(), getBazaar(), getBazaarCount(), initialize(), notifyEnter(), and notifyExit().
VectorMap<unsigned long long, int> server::zone::objects::region::CityRegionImplementation::candidates protected
Definition at line 467 of file CityRegion.h.
Referenced by addCandidate(), CityRegionImplementation(), getCandidates(), getCandidateVotes(), isCandidate(), readObjectMember(), removeCandidate(), resetCandidates(), setMayoralVote(), and writeObjectMembers().
CitizenList server::zone::objects::region::CityRegionImplementation::citizenList protected
Definition at line 481 of file CityRegion.h.
Referenced by addCitizen(), cleanupCitizens(), getCitizenCount(), getCitizenList(), isCitizen(), notifyEnter(), notifyExit(), readObjectMember(), removeCitizen(), and writeObjectMembers().
SortedVector<ManagedReference<SceneObject* > > server::zone::objects::region::CityRegionImplementation::cityDecorations protected
Definition at line 523 of file CityRegion.h.
Referenced by addDecoration(), cleanupDecorations(), cleanupDuplicateCityStructures(), getCityDecoration(), getDecorationCount(), initialize(), readObjectMember(), removeAllDecorations(), removeDecoration(), transferCivicStructuresToMayor(), and writeObjectMembers().
ManagedReference<StructureObject* > server::zone::objects::region::CityRegionImplementation::cityHall protected
Definition at line 513 of file CityRegion.h.
Referenced by getCityHall(), initialize(), isInsideRadius(), readObjectMember(), removeDecorationsOutsideCity(), removeStructuresOutsideCity(), removeTerminalsOutsideCity(), removeTrainersOutsideCity(), setCityHall(), and writeObjectMembers().
SortedVector<ManagedReference<SceneObject* > > server::zone::objects::region::CityRegionImplementation::cityMissionTerminals protected
Definition at line 521 of file CityRegion.h.
Referenced by addMissionTerminal(), getCityMissionTerminal(), getMissionTerminalCount(), initialize(), readObjectMember(), removeAllTerminals(), removeMissionTerminal(), and writeObjectMembers().
byte server::zone::objects::region::CityRegionImplementation::cityRank protected
Definition at line 463 of file CityRegion.h.
Referenced by getCityRank(), initialize(), isClientRegion(), notifyEnter(), notifyLoadFromDatabase(), readObjectMember(), rescheduleUpdateEvent(), setCityRank(), and writeObjectMembers().
SortedVector<ManagedReference<SceneObject* > > server::zone::objects::region::CityRegionImplementation::citySkillTrainers protected
Definition at line 525 of file CityRegion.h.
Referenced by addSkillTrainer(), getCitySkillTrainer(), getSkillTrainerCount(), initialize(), readObjectMember(), removeAllSkillTrainers(), removeSkillTrainers(), and writeObjectMembers().
String server::zone::objects::region::CityRegionImplementation::citySpecialization protected
Definition at line 511 of file CityRegion.h.
Referenced by applySpecializationModifiers(), getCitySpecialization(), notifyEnter(), readObjectMember(), setCitySpecialization(), and writeObjectMembers().
float server::zone::objects::region::CityRegionImplementation::cityTreasury protected
Definition at line 489 of file CityRegion.h.
Referenced by addToCityTreasury(), getCityTreasury(), initialize(), readObjectMember(), setCityTreasury(), subtractFromCityTreasury(), and writeObjectMembers().
Reference<CityUpdateEvent* > server::zone::objects::region::CityRegionImplementation::cityUpdateEvent protected
Definition at line 509 of file CityRegion.h.
Referenced by initialize(), and rescheduleUpdateEvent().
SortedVector<ManagedReference<StructureObject* > > server::zone::objects::region::CityRegionImplementation::commercialStructures protected
Definition at line 519 of file CityRegion.h.
Referenced by addCommercialStructure(), CityRegionImplementation(), cleanupDuplicateCityStructures(), getCommercialStructure(), getCommercialStructuresCount(), readObjectMember(), removeCommercialStructure(), and writeObjectMembers().
SortedVector<unsigned long long> server::zone::objects::region::CityRegionImplementation::completeStructureList protected
Definition at line 485 of file CityRegion.h.
Referenced by CityRegionImplementation(), cleanupCitizens(), getAllStructuresCount(), notifyEnter(), and notifyExit().
AtomicInteger server::zone::objects::region::CityRegionImplementation::currentPlayers protected
Definition at line 471 of file CityRegion.h.
Referenced by getCurrentPlayerCount(), notifyEnter(), notifyExit(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::region::CityRegionImplementation::customRegionName protected
Definition at line 473 of file CityRegion.h.
Referenced by getRadius(), getRegionName(), readObjectMember(), setCustomRegionName(), and writeObjectMembers().
bool server::zone::objects::region::CityRegionImplementation::hasShuttle protected
Definition at line 497 of file CityRegion.h.
Referenced by hasShuttleInstallation(), initialize(), notifyLoadFromDatabase(), readObjectMember(), removeShuttleInstallation(), setShuttleID(), and writeObjectMembers().
bool server::zone::objects::region::CityRegionImplementation::loaded protected
Definition at line 501 of file CityRegion.h.
Referenced by CityRegionImplementation(), initializeTransientMembers(), isLoaded(), and setLoaded().
VectorMap<unsigned long long, unsigned long long> server::zone::objects::region::CityRegionImplementation::mayoralVotes protected
Definition at line 469 of file CityRegion.h.
Referenced by CityRegionImplementation(), getMayoralVotes(), readObjectMember(), resetMayoralVotes(), setMayoralVote(), and writeObjectMembers().
unsigned long long server::zone::objects::region::CityRegionImplementation::mayorID protected
Definition at line 491 of file CityRegion.h.
Referenced by getMayorID(), initialize(), isMayor(), isMilitiaMember(), readObjectMember(), setMayorID(), and writeObjectMembers().
CitizenList server::zone::objects::region::CityRegionImplementation::militiaMembers protected
Definition at line 479 of file CityRegion.h.
Referenced by addMilitiaMember(), getMilitiaMembers(), isMilitiaMember(), readObjectMember(), removeCitizen(), removeMilitiaMember(), updateMilitia(), and writeObjectMembers().
Time server::zone::objects::region::CityRegionImplementation::nextInauguration protected
Definition at line 507 of file CityRegion.h.
Referenced by isVotingLocked(), isVotingPeriod(), isVotingPeriodOver(), readObjectMember(), resetVotingPeriod(), and writeObjectMembers().
Time server::zone::objects::region::CityRegionImplementation::nextUpdateTime protected
Definition at line 505 of file CityRegion.h.
Referenced by getNextUpdateTime(), getTimeToUpdate(), readObjectMember(), rescheduleUpdateEvent(), and writeObjectMembers().
const byte server::zone::objects::region::CityRegionImplementation::RANK_CITY = 4 static
Definition at line 538 of file CityRegion.h.
const byte server::zone::objects::region::CityRegionImplementation::RANK_CLIENT = 0 static
Definition at line 530 of file CityRegion.h.
Referenced by initialize(), and isClientRegion().
const byte server::zone::objects::region::CityRegionImplementation::RANK_METROPOLIS = 5 static
Definition at line 540 of file CityRegion.h.
const byte server::zone::objects::region::CityRegionImplementation::RANK_OUTPOST = 1 static
Definition at line 532 of file CityRegion.h.
const byte server::zone::objects::region::CityRegionImplementation::RANK_TOWNSHIP = 3 static
Definition at line 536 of file CityRegion.h.
const byte server::zone::objects::region::CityRegionImplementation::RANK_VILLAGE = 2 static
Definition at line 534 of file CityRegion.h.
StringId server::zone::objects::region::CityRegionImplementation::regionName protected
Definition at line 465 of file CityRegion.h.
Referenced by addRegion(), getRadius(), getRegionName(), readObjectMember(), setRegionName(), and writeObjectMembers().
SortedVector<ManagedReference<Region* > > server::zone::objects::region::CityRegionImplementation::regions protected
Definition at line 515 of file CityRegion.h.
Referenced by addRegion(), containsPoint(), destroyActiveAreas(), getPositionX(), getPositionY(), getRadius(), getRegion(), getRegionsCount(), readObjectMember(), setRadius(), and writeObjectMembers().
bool server::zone::objects::region::CityRegionImplementation::registered protected
Definition at line 495 of file CityRegion.h.
Referenced by initialize(), isRegistered(), notifyEnter(), readObjectMember(), setRegistered(), and writeObjectMembers().
unsigned long long server::zone::objects::region::CityRegionImplementation::shuttleID protected
Definition at line 499 of file CityRegion.h.
Referenced by initialize(), notifyLoadFromDatabase(), readObjectMember(), removeShuttleInstallation(), setShuttleID(), and writeObjectMembers().
Mutex server::zone::objects::region::CityRegionImplementation::structureListMutex protected
Definition at line 487 of file CityRegion.h.
Referenced by addCommercialStructure(), addDecoration(), addStructure(), cleanupCitizens(), notifyEnter(), notifyExit(), removeCitizen(), removeCommercialStructure(), removeDecoration(), removeStructure(), and transferCivicStructuresToMayor().
SortedVector<ManagedReference<StructureObject* > > server::zone::objects::region::CityRegionImplementation::structures protected
Definition at line 517 of file CityRegion.h.
Referenced by addStructure(), CityRegionImplementation(), cleanupDuplicateCityStructures(), destroyAllStructuresForRank(), getCivicStructure(), getStructuresCount(), hasUniqueStructure(), readObjectMember(), removeStructure(), transferCivicStructuresToMayor(), and writeObjectMembers().
const byte server::zone::objects::region::CityRegionImplementation::TAX_GARAGE = 4 static
Definition at line 550 of file CityRegion.h.
Referenced by getGarageTax().
const byte server::zone::objects::region::CityRegionImplementation::TAX_INCOME = 1 static
Definition at line 544 of file CityRegion.h.
Referenced by getIncomeTax().
const byte server::zone::objects::region::CityRegionImplementation::TAX_PROPERTY = 0 static
Definition at line 542 of file CityRegion.h.
Referenced by getPropertyTax().
const byte server::zone::objects::region::CityRegionImplementation::TAX_SALES = 2 static
Definition at line 546 of file CityRegion.h.
Referenced by getSalesTax().
const byte server::zone::objects::region::CityRegionImplementation::TAX_TRAVEL = 3 static
Definition at line 548 of file CityRegion.h.
Referenced by getTravelTax().
Vector<int> server::zone::objects::region::CityRegionImplementation::taxes protected
Definition at line 503 of file CityRegion.h.
Referenced by CityRegionImplementation(), getGarageTax(), getIncomeTax(), getPropertyTax(), getSalesTax(), getTax(), getTravelTax(), notifyLoadFromDatabase(), readObjectMember(), setTax(), and writeObjectMembers().
ZoneReference server::zone::objects::region::CityRegionImplementation::zone protected
Definition at line 475 of file CityRegion.h.
Referenced by addRegion(), cleanupCitizens(), destroyAllStructuresForRank(), getZone(), initialize(), notifyEnter(), notifyLoadFromDatabase(), readObjectMember(), setRadius(), setZone(), transferCivicStructuresToMayor(), and writeObjectMembers().
bool server::zone::objects::region::CityRegionImplementation::zoningEnabled protected
Definition at line 493 of file CityRegion.h.
Referenced by initialize(), isZoningEnabled(), readObjectMember(), setZoningEnabled(), and writeObjectMembers().
VectorMap<unsigned long long, unsigned int> server::zone::objects::region::CityRegionImplementation::zoningRights protected
Definition at line 477 of file CityRegion.h.
Referenced by addZoningRights(), hasZoningRights(), initialize(), readObjectMember(), removeZoningRights(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/region/CityRegion.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/region/CityRegion.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/region/CityRegionImplementation.cpp