Core3: InsertSchematicSuiCallback Class Reference
InsertSchematicSuiCallback Class Reference
#include <InsertSchematicSuiCallback.h>
Public Member Functions
InsertSchematicSuiCallback (ZoneServer *server)
void run (CreatureObject *player, SuiBox *suiBox, bool cancelPressed, Vector< UnicodeString > *args)
void handleInsertFactorySchem2 (CreatureObject *player, SuiBox *suiBox, uint32 cancel, Vector< UnicodeString > *args)
void handleInsertFactorySchem3 (CreatureObject *player, SuiBox *suiBox, uint32 cancel, Vector< UnicodeString > *args)
Public Member Functions inherited from server::zone::objects::player::sui::SuiCallback
SuiCallback (ZoneServer *serv)
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::player::sui::SuiCallback
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 16 of file InsertSchematicSuiCallback.h.
Constructor & Destructor Documentation
InsertSchematicSuiCallback::InsertSchematicSuiCallback (ZoneServer * server) inline
Definition at line 18 of file InsertSchematicSuiCallback.h.
Member Function Documentation
void InsertSchematicSuiCallback::handleInsertFactorySchem2 (CreatureObject * player, SuiBox * suiBox, uint32 cancel, Vector< UnicodeString > * args) inline
Definition at line 31 of file InsertSchematicSuiCallback.h.
References server::zone::objects::player::sui::SuiBox::getUsingObject(), server::zone::objects::installation::factory::FactoryObject::handleInsertFactorySchem(), server::zone::objects::player::sui::SuiBox::isListBox(), and server::zone::objects::player::sui::SuiCallback::server.
Referenced by run().
void InsertSchematicSuiCallback::handleInsertFactorySchem3 (CreatureObject * player, SuiBox * suiBox, uint32 cancel, Vector< UnicodeString > * args) inline
Definition at line 56 of file InsertSchematicSuiCallback.h.
References server::zone::objects::player::sui::SuiBox::getUsingObject(), server::zone::objects::installation::factory::FactoryObject::handleInsertFactorySchem(), server::zone::objects::installation::factory::FactoryObject::handleRemoveFactorySchem(), server::zone::objects::player::sui::SuiBox::isListBox(), and server::zone::objects::player::sui::SuiCallback::server.
Referenced by run().
void InsertSchematicSuiCallback::run (CreatureObject * player, SuiBox * suiBox, bool cancelPressed, Vector< UnicodeString > * args) inline virtual
Parameters
player The player that this suibox is assigned to.
suiBox The actual SuiBox object.
cancelPressed Was the cancel button pressed, or was the sui box closed via a similar method. (this might actually be more of a dialogResult type variable)
args A vector of UnicodeStrings containing the arguments passed to the sui box from the client.
Implements server::zone::objects::player::sui::SuiCallback.
Definition at line 22 of file InsertSchematicSuiCallback.h.
References SuiWindowType::FACTORY_SCHEMATIC2BUTTON, SuiWindowType::FACTORY_SCHEMATIC3BUTTON, server::zone::objects::player::sui::SuiBox::getWindowType(), handleInsertFactorySchem2(), and handleInsertFactorySchem3().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/factory/sui/InsertSchematicSuiCallback.h