Core3: server::zone::objects::guild::GuildObject Class Reference
server::zone::objects::guild::GuildObject Class Reference
#include <GuildObject.h>
Public Member Functions
GuildObject ()
void sendBaselinesTo (SceneObject *player)
void broadcastMessage (BaseMessage *msg)
void broadcastMessage (CreatureObject *player, BaseMessage *msg, bool sendSelf=false)
void addMember (unsigned long long playerID)
void removeMember (unsigned long long playerID)
bool hasMember (unsigned long long playerID)
GuildMemberInfo * getMember (unsigned long long playerID)
unsigned long long getMember (int index)
void addSponsoredPlayer (unsigned long long playerID)
void removeSponsoredPlayer (unsigned long long playerID)
bool hasSponsoredPlayer (unsigned long long playerID)
unsigned long long getSponsoredPlayer (int idx)
int getSponsoredPlayerCount ()
void setChatRoom (ChatRoom *room)
ChatRoom * getChatRoom ()
int getTotalMembers ()
unsigned long long getGuildLeaderID ()
GuildMemberList * getGuildMemberList ()
String getGuildAbbrev ()
void setGuildAbbrev (const String &abbrev)
void setGuildLeaderID (unsigned long long leaderID)
void setGuildID (unsigned int id)
unsigned int getGuildID ()
void setGuildName (const String &gname)
String getGuildName ()
String getGuildKey ()
bool isGuildObject ()
bool isGuildLeader (CreatureObject *player)
byte getWarStatus (unsigned long long guildoid)
void setWarStatus (unsigned long long guildoid, byte status)
bool isInWaringGuild (CreatureObject *creature)
bool isAtWarWith (unsigned long long guildoid)
bool hasDeclaredWarOn (unsigned long long guildoid)
bool hasDeclaredWarBy (unsigned long long guildoid)
VectorMap< unsigned long long,
byte > * getWaringGuilds ()
bool hasMailPermission (unsigned long long playerID)
bool hasSponsorPermission (unsigned long long playerID)
bool hasAcceptPermission (unsigned long long playerID)
bool hasDisbandPermission (unsigned long long playerID)
bool hasKickPermission (unsigned long long playerID)
bool hasNamePermission (unsigned long long playerID)
bool hasTitlePermission (unsigned long long playerID)
bool hasWarPermission (unsigned long long playerID)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject ()
void initializePrivateData ()
void loadTemplateData (SharedObjectTemplate *templateData)
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendAttributeListTo (CreatureObject *object)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
void openContainerTo (CreatureObject *player)
byte checkContainerPermission (CreatureObject *player, unsigned short permission)
void closeContainerTo (CreatureObject *player, bool notify=true)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets=true)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
String getDetailedDescription ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const byte PERMISSION_NONE = 0x00
static const byte PERMISSION_MAIL = 0x01
static const byte PERMISSION_SPONSOR = 0x02
static const byte PERMISSION_TITLE = 0x04
static const byte PERMISSION_ACCEPT = 0x08
static const byte PERMISSION_KICK = 0x10
static const byte PERMISSION_WAR = 0x20
static const byte PERMISSION_NAME = 0x40
static const byte PERMISSION_DISBAND = 0x80
static const byte PERMISSION_ALL = 0xFF
static const byte WAR_NONE = 0
static const byte WAR_MUTUAL = 0x3D
static const byte WAR_IN = 0x3C
static const byte WAR_OUT = 0x3E
Protected Member Functions
GuildObject (DummyConstructorParameter *param)
virtual ~GuildObject ()
Protected Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject (DummyConstructorParameter *param)
virtual ~SceneObject ()
Friends
class GuildObjectHelper
Detailed Description
Definition at line 77 of file GuildObject.h.
Constructor & Destructor Documentation
GuildObject::GuildObject ()
Definition at line 19 of file GuildObject.cpp.
References server::zone::objects::guild::GuildObjectImplementation::_setStub().
GuildObject::GuildObject (DummyConstructorParameter * param) protected
Definition at line 26 of file GuildObject.cpp.
GuildObject::~GuildObject () protected virtual
Definition at line 30 of file GuildObject.cpp.
Member Function Documentation
DistributedObjectServant * GuildObject::_getImplementation ()
Definition at line 622 of file GuildObject.cpp.
Referenced by addMember(), addSponsoredPlayer(), broadcastMessage(), getChatRoom(), getGuildAbbrev(), getGuildID(), getGuildKey(), getGuildLeaderID(), getGuildMemberList(), getGuildName(), getMember(), getSponsoredPlayer(), getSponsoredPlayerCount(), getTotalMembers(), getWaringGuilds(), getWarStatus(), hasAcceptPermission(), hasDeclaredWarBy(), hasDeclaredWarOn(), hasDisbandPermission(), hasKickPermission(), hasMailPermission(), hasMember(), hasNamePermission(), hasSponsoredPlayer(), hasSponsorPermission(), hasTitlePermission(), hasWarPermission(), isAtWarWith(), isGuildLeader(), isGuildObject(), isInWaringGuild(), removeMember(), removeSponsoredPlayer(), sendBaselinesTo(), setChatRoom(), setGuildAbbrev(), setGuildID(), setGuildLeaderID(), setGuildName(), and setWarStatus().
DistributedObjectServant * GuildObject::_getImplementationForRead ()
Definition at line 628 of file GuildObject.cpp.
void GuildObject::_setImplementation (DistributedObjectServant * servant)
Definition at line 632 of file GuildObject.cpp.
void GuildObject::addMember (unsigned long long playerID)
Adds the Player to the GuildMemberList. Doesn't do anything else! Use the GuildManager for adding and removing of players that sends messages etc.
Parameters
player The player's objectid to add
Definition at line 79 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::addMember(), and RPC_ADDMEMBER__LONG_.
void GuildObject::addSponsoredPlayer (unsigned long long playerID)
Definition at line 144 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::addSponsoredPlayer(), and RPC_ADDSPONSOREDPLAYER__LONG_.
void GuildObject::broadcastMessage (BaseMessage * msg)
Definition at line 49 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::broadcastMessage(), and RPC_BROADCASTMESSAGE__BASEMESSAGE_.
void GuildObject::broadcastMessage (CreatureObject * player, BaseMessage * msg, bool sendSelf = false)
Definition at line 63 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::broadcastMessage(), and RPC_BROADCASTMESSAGE__CREATUREOBJECT_BASEMESSAGE_BOOL_.
ChatRoom * GuildObject::getChatRoom ()
Definition at line 227 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::getChatRoom(), and RPC_GETCHATROOM__.
Referenced by server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::managers::guild::GuildManagerImplementation::leaveGuild(), and server::zone::objects::player::PlayerObjectImplementation::notifySceneReady().
String GuildObject::getGuildAbbrev ()
Definition at line 275 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::getGuildAbbrev(), and RPC_GETGUILDABBREV__.
Referenced by GuildObjectDeltaMessage3::addGuild(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::objects::structure::StructureObjectImplementation::isOnAdminList(), server::zone::objects::structure::StructureObjectImplementation::isOnBanList(), server::zone::objects::structure::StructureObjectImplementation::isOnEntryList(), server::zone::objects::structure::StructureObjectImplementation::isOnHopperList(), server::zone::objects::structure::StructureObjectImplementation::isOnPermissionList(), GuildObjectDeltaMessage3::removeGuild(), server::zone::managers::guild::GuildManagerImplementation::sendGuildInformationTo(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildWarStatusTo().
unsigned int GuildObject::getGuildID ()
Definition at line 332 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::getGuildID(), and RPC_GETGUILDID__.
Referenced by GuildObjectDeltaMessage3::addGuild(), server::zone::managers::guild::GuildManagerImplementation::createGuildChannels(), and GuildObjectDeltaMessage3::removeGuild().
String GuildObject::getGuildKey ()
Definition at line 374 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::getGuildKey(), and RPC_GETGUILDKEY__.
Referenced by server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), and server::zone::managers::guild::GuildManagerImplementation::loadGuilds().
unsigned long long GuildObject::getGuildLeaderID ()
Definition at line 253 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::getGuildLeaderID(), and RPC_GETGUILDLEADERID__.
Referenced by GuildTransferLeaderAckSuiCallback::run(), server::zone::managers::guild::GuildManagerImplementation::sendGuildInformationTo(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberOptionsTo().
GuildMemberList * GuildObject::getGuildMemberList ()
Definition at line 266 of file GuildObject.cpp.
References _getImplementation(), and server::zone::objects::guild::GuildObjectImplementation::getGuildMemberList().
Referenced by server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::managers::guild::GuildManagerImplementation::sendGuildMail(), server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberListTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberOptionsTo(), and UpdateWarStatusTask::UpdateWarStatusTask().
String GuildObject::getGuildName ()
Definition at line 359 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::getGuildName(), and RPC_GETGUILDNAME__.
Referenced by server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::managers::guild::GuildManagerImplementation::leaveGuild(), server::zone::managers::guild::GuildManagerImplementation::sendGuildInformationTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildMail(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildWarStatusTo().
GuildMemberInfo * GuildObject::getMember (unsigned long long playerID)
Definition at line 121 of file GuildObject.cpp.
References _getImplementation(), and server::zone::objects::guild::GuildObjectImplementation::getMember().
Referenced by server::zone::managers::guild::GuildManagerImplementation::transferLeadership().
unsigned long long GuildObject::getMember (int index)
Definition at line 130 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::getMember(), and RPC_GETMEMBER__INT_.
unsigned long long GuildObject::getSponsoredPlayer (int idx)
Definition at line 186 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::getSponsoredPlayer(), and RPC_GETSPONSOREDPLAYER__INT_.
Referenced by server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::managers::guild::GuildManagerImplementation::loadGuilds(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredListTo().
int GuildObject::getSponsoredPlayerCount ()
Definition at line 200 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::getSponsoredPlayerCount(), and RPC_GETSPONSOREDPLAYERCOUNT__.
Referenced by server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::managers::guild::GuildManagerImplementation::loadGuilds(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredListTo().
int GuildObject::getTotalMembers ()
Definition at line 240 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::getTotalMembers(), and RPC_GETTOTALMEMBERS__.
Referenced by server::zone::managers::guild::GuildManagerImplementation::sendGuildInformationTo().
VectorMap< unsigned long long, byte > * GuildObject::getWaringGuilds ()
Definition at line 501 of file GuildObject.cpp.
References _getImplementation(), and server::zone::objects::guild::GuildObjectImplementation::getWaringGuilds().
Referenced by server::zone::managers::guild::GuildManagerImplementation::sendGuildWarStatusTo().
byte GuildObject::getWarStatus (unsigned long long guildoid)
Definition at line 416 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::getWarStatus(), and RPC_GETWARSTATUS__LONG_.
bool GuildObject::hasAcceptPermission (unsigned long long playerID)
Definition at line 538 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasAcceptPermission(), and RPC_HASACCEPTPERMISSION__LONG_.
Referenced by server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredOptionsTo().
bool GuildObject::hasDeclaredWarBy (unsigned long long guildoid)
Definition at line 487 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasDeclaredWarBy(), and RPC_HASDECLAREDWARBY__LONG_.
Referenced by server::zone::managers::guild::GuildManagerImplementation::toggleWarStatus().
bool GuildObject::hasDeclaredWarOn (unsigned long long guildoid)
Definition at line 473 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasDeclaredWarOn(), and RPC_HASDECLAREDWARON__LONG_.
Referenced by server::zone::managers::guild::GuildManagerImplementation::toggleWarStatus().
bool GuildObject::hasDisbandPermission (unsigned long long playerID)
Definition at line 552 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasDisbandPermission(), and RPC_HASDISBANDPERMISSION__LONG_.
Referenced by server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildDisbandConfirmTo().
bool GuildObject::hasKickPermission (unsigned long long playerID)
Definition at line 566 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasKickPermission(), and RPC_HASKICKPERMISSION__LONG_.
bool GuildObject::hasMailPermission (unsigned long long playerID)
Definition at line 510 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasMailPermission(), and RPC_HASMAILPERMISSION__LONG_.
bool GuildObject::hasMember (unsigned long long playerID)
Definition at line 107 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasMember(), and RPC_HASMEMBER__LONG_.
bool GuildObject::hasNamePermission (unsigned long long playerID)
Definition at line 580 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasNamePermission(), and RPC_HASNAMEPERMISSION__LONG_.
bool GuildObject::hasSponsoredPlayer (unsigned long long playerID)
Definition at line 172 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasSponsoredPlayer(), and RPC_HASSPONSOREDPLAYER__LONG_.
bool GuildObject::hasSponsorPermission (unsigned long long playerID)
Definition at line 524 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasSponsorPermission(), and RPC_HASSPONSORPERMISSION__LONG_.
Referenced by server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsorTo().
bool GuildObject::hasTitlePermission (unsigned long long playerID)
Definition at line 594 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasTitlePermission(), and RPC_HASTITLEPERMISSION__LONG_.
bool GuildObject::hasWarPermission (unsigned long long playerID)
Definition at line 608 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::hasWarPermission(), and RPC_HASWARPERMISSION__LONG_.
Referenced by server::zone::managers::guild::GuildManagerImplementation::promptAddNewEnemy(), and server::zone::managers::guild::GuildManagerImplementation::toggleWarStatus().
bool GuildObject::isAtWarWith (unsigned long long guildoid)
Definition at line 459 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::isAtWarWith(), and RPC_ISATWARWITH__LONG_.
Referenced by server::zone::managers::guild::GuildManagerImplementation::toggleWarStatus().
bool GuildObject::isGuildLeader (CreatureObject * player)
Definition at line 402 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::isGuildLeader(), and RPC_ISGUILDLEADER__CREATUREOBJECT_.
bool GuildObject::isGuildObject ()
Definition at line 389 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::isGuildObject(), and RPC_ISGUILDOBJECT__.
bool GuildObject::isInWaringGuild (CreatureObject * creature)
Definition at line 445 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::isInWaringGuild(), and RPC_ISINWARINGGUILD__CREATUREOBJECT_.
void GuildObject::removeMember (unsigned long long playerID)
Definition at line 93 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::removeMember(), and RPC_REMOVEMEMBER__LONG_.
Referenced by server::zone::managers::guild::GuildManagerImplementation::leaveGuild().
void GuildObject::removeSponsoredPlayer (unsigned long long playerID)
Definition at line 158 of file GuildObject.cpp.
References _getImplementation(), server::zone::objects::guild::GuildObjectImplementation::removeSponsoredPlayer(), and RPC_REMOVESPONSOREDPLAYER__LONG_.
void GuildObject::sendBaselinesTo (SceneObject * player)
Definition at line 35 of file GuildObject.cpp.
References _getImplementation(), RPC_SENDBASELINESTO__SCENEOBJECT_, and server::zone::objects::guild::GuildObjectImplementation::sendBaselinesTo().
void GuildObject::setChatRoom (ChatRoom * room)
Definition at line 213 of file GuildObject.cpp.
References _getImplementation(), RPC_SETCHATROOM__CHATROOM_, and server::zone::objects::guild::GuildObjectImplementation::setChatRoom().
Referenced by server::zone::managers::guild::GuildManagerImplementation::createGuildChannels().
void GuildObject::setGuildAbbrev (const String & abbrev)
Definition at line 290 of file GuildObject.cpp.
References _getImplementation(), RPC_SETGUILDABBREV__STRING_, and server::zone::objects::guild::GuildObjectImplementation::setGuildAbbrev().
void GuildObject::setGuildID (unsigned int id)
Definition at line 318 of file GuildObject.cpp.
References _getImplementation(), RPC_SETGUILDID__INT_, and server::zone::objects::guild::GuildObjectImplementation::setGuildID().
void GuildObject::setGuildLeaderID (unsigned long long leaderID)
Definition at line 304 of file GuildObject.cpp.
References _getImplementation(), RPC_SETGUILDLEADERID__LONG_, and server::zone::objects::guild::GuildObjectImplementation::setGuildLeaderID().
Referenced by server::zone::managers::guild::GuildManagerImplementation::transferLeadership().
void GuildObject::setGuildName (const String & gname)
Definition at line 345 of file GuildObject.cpp.
References _getImplementation(), RPC_SETGUILDNAME__STRING_, and server::zone::objects::guild::GuildObjectImplementation::setGuildName().
void GuildObject::setWarStatus (unsigned long long guildoid, byte status)
Definition at line 430 of file GuildObject.cpp.
References _getImplementation(), RPC_SETWARSTATUS__LONG_BYTE_, and server::zone::objects::guild::GuildObjectImplementation::setWarStatus().
Referenced by server::zone::managers::guild::GuildManagerImplementation::toggleWarStatus().
Friends And Related Function Documentation
friend class GuildObjectHelper friend
Definition at line 210 of file GuildObject.h.
Member Data Documentation
const byte server::zone::objects::guild::GuildObject::PERMISSION_ACCEPT = 0x08 static
Definition at line 87 of file GuildObject.h.
Referenced by server::zone::objects::guild::GuildObjectImplementation::hasAcceptPermission().
const byte server::zone::objects::guild::GuildObject::PERMISSION_ALL = 0xFF static
Definition at line 97 of file GuildObject.h.
const byte server::zone::objects::guild::GuildObject::PERMISSION_DISBAND = 0x80 static
Definition at line 95 of file GuildObject.h.
Referenced by server::zone::objects::guild::GuildObjectImplementation::hasDisbandPermission().
const byte server::zone::objects::guild::GuildObject::PERMISSION_KICK = 0x10 static
Definition at line 89 of file GuildObject.h.
Referenced by server::zone::objects::guild::GuildObjectImplementation::hasKickPermission().
const byte server::zone::objects::guild::GuildObject::PERMISSION_MAIL = 0x01 static
Definition at line 81 of file GuildObject.h.
Referenced by server::zone::objects::guild::GuildObjectImplementation::hasMailPermission().
const byte server::zone::objects::guild::GuildObject::PERMISSION_NAME = 0x40 static
Definition at line 93 of file GuildObject.h.
Referenced by server::zone::objects::guild::GuildObjectImplementation::hasNamePermission().
const byte server::zone::objects::guild::GuildObject::PERMISSION_NONE = 0x00 static
Definition at line 79 of file GuildObject.h.
Referenced by server::zone::objects::guild::GuildMemberInfo::GuildMemberInfo().
const byte server::zone::objects::guild::GuildObject::PERMISSION_SPONSOR = 0x02 static
Definition at line 83 of file GuildObject.h.
Referenced by server::zone::objects::guild::GuildObjectImplementation::hasSponsorPermission().
const byte server::zone::objects::guild::GuildObject::PERMISSION_TITLE = 0x04 static
Definition at line 85 of file GuildObject.h.
Referenced by server::zone::objects::guild::GuildObjectImplementation::hasTitlePermission().
const byte server::zone::objects::guild::GuildObject::PERMISSION_WAR = 0x20 static
Definition at line 91 of file GuildObject.h.
Referenced by server::zone::objects::guild::GuildObjectImplementation::hasWarPermission().
const byte server::zone::objects::guild::GuildObject::WAR_IN = 0x3C static
Definition at line 103 of file GuildObject.h.
const byte server::zone::objects::guild::GuildObject::WAR_MUTUAL = 0x3D static
Definition at line 101 of file GuildObject.h.
const byte server::zone::objects::guild::GuildObject::WAR_NONE = 0 static
Definition at line 99 of file GuildObject.h.
const byte server::zone::objects::guild::GuildObject::WAR_OUT = 0x3E static
Definition at line 105 of file GuildObject.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/guild/GuildObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/guild/GuildObject.cpp