Core3: server::zone::objects::mission::CraftingMissionObjectiveImplementation Class Reference
server::zone::objects::mission::CraftingMissionObjectiveImplementation Class Reference
#include <CraftingMissionObjective.h>
Public Member Functions
CraftingMissionObjectiveImplementation (MissionObject *mission)
CraftingMissionObjectiveImplementation (DummyConstructorParameter *param)
void finalize ()
void initializeTransientMembers ()
virtual void updateMissionStatus (CreatureObject *player)
virtual void abort ()
operator const CraftingMissionObjective * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::mission::DeliverMissionObjectiveImplementation
DeliverMissionObjectiveImplementation (MissionObject *mission)
DeliverMissionObjectiveImplementation (DummyConstructorParameter *param)
void finalize ()
void initializeTransientMembers ()
TangibleObject * getItem ()
int getObjectiveStatus ()
virtual void activate ()
virtual void deactivate ()
bool activateWithResult ()
virtual void complete ()
void despawnNpcs ()
virtual bool updateMissionTarget (CreatureObject *player)
NpcSpawnPoint * getTargetSpawnPoint ()
NpcSpawnPoint * getDestinationSpawnPoint ()
operator const DeliverMissionObjective * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
MissionObjectiveImplementation (MissionObject *parent)
MissionObjectiveImplementation (DummyConstructorParameter *param)
virtual void destroyObjectFromDatabase ()
virtual int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
virtual void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
virtual Vector3 getEndPosition ()
operator const MissionObjective * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< CraftingMissionObjective * > _this
Public Attributes inherited from server::zone::objects::mission::DeliverMissionObjectiveImplementation
WeakReference
< DeliverMissionObjective * > _this
Public Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
WeakReference< MissionObjective * > _this
Protected Member Functions
virtual ~CraftingMissionObjectiveImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::mission::DeliverMissionObjectiveImplementation
virtual ~DeliverMissionObjectiveImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
virtual ~MissionObjectiveImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class CraftingMissionObjective
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::mission::DeliverMissionObjectiveImplementation
static const int INITSTATUS = 0
static const int PICKEDUPSTATUS = 1
static const int DELIVEREDSTATUS = 2
Protected Attributes inherited from server::zone::objects::mission::DeliverMissionObjectiveImplementation
ManagedReference
< TangibleObject * > item
Reference< NpcSpawnPoint * > targetSpawnPoint
Reference< NpcSpawnPoint * > destinationSpawnPoint
int objectiveStatus
Detailed Description
Definition at line 84 of file CraftingMissionObjective.h.
Constructor & Destructor Documentation
CraftingMissionObjectiveImplementation::CraftingMissionObjectiveImplementation (MissionObject * mission)
Definition at line 203 of file CraftingMissionObjective.cpp.
References _initializeImplementation().
CraftingMissionObjectiveImplementation::CraftingMissionObjectiveImplementation (DummyConstructorParameter * param)
Definition at line 91 of file CraftingMissionObjective.cpp.
References _initializeImplementation().
CraftingMissionObjectiveImplementation::~CraftingMissionObjectiveImplementation () protected virtual
Definition at line 96 of file CraftingMissionObjective.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * CraftingMissionObjectiveImplementation::_getStub ()
Definition at line 114 of file CraftingMissionObjective.cpp.
References _this.
void CraftingMissionObjectiveImplementation::_initializeImplementation () protected
Definition at line 101 of file CraftingMissionObjective.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CraftingMissionObjectiveImplementation().
void CraftingMissionObjectiveImplementation::_serializationHelperMethod () protected
Definition at line 150 of file CraftingMissionObjective.cpp.
References server::zone::objects::mission::DeliverMissionObjectiveImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void CraftingMissionObjectiveImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 109 of file CraftingMissionObjective.cpp.
References server::zone::objects::mission::DeliverMissionObjectiveImplementation::_setStub(), and _this.
Referenced by server::zone::objects::mission::CraftingMissionObjective::CraftingMissionObjective().
void CraftingMissionObjectiveImplementation::abort () virtual
Reimplemented from server::zone::objects::mission::DeliverMissionObjectiveImplementation.
Definition at line 69 of file CraftingMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::DeliverMissionObjectiveImplementation::abort(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), and server::zone::objects::mission::MissionObjectiveImplementation::mission.
Referenced by server::zone::objects::mission::CraftingMissionObjective::abort().
void CraftingMissionObjectiveImplementation::finalize ()
Definition at line 209 of file CraftingMissionObjective.cpp.
Referenced by ~CraftingMissionObjectiveImplementation().
void CraftingMissionObjectiveImplementation::initializeTransientMembers () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 212 of file CraftingMissionObjective.cpp.
References server::zone::objects::mission::DeliverMissionObjectiveImplementation::initializeTransientMembers().
Referenced by server::zone::objects::mission::CraftingMissionObjective::initializeTransientMembers(), and readObject().
void CraftingMissionObjectiveImplementation::lock (bool doLock = true) protected
Definition at line 122 of file CraftingMissionObjective.cpp.
References _this.
void CraftingMissionObjectiveImplementation::lock (ManagedObject * obj) protected
Definition at line 126 of file CraftingMissionObjective.cpp.
References _this.
CraftingMissionObjectiveImplementation::operator const CraftingMissionObjective * ()
Definition at line 118 of file CraftingMissionObjective.cpp.
void CraftingMissionObjectiveImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::mission::DeliverMissionObjectiveImplementation.
Definition at line 157 of file CraftingMissionObjective.cpp.
References initializeTransientMembers(), and readObjectMember().
bool CraftingMissionObjectiveImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 176 of file CraftingMissionObjective.cpp.
References server::zone::objects::mission::DeliverMissionObjectiveImplementation::readObjectMember().
Referenced by readObject().
void CraftingMissionObjectiveImplementation::rlock (bool doLock = true) protected
Definition at line 130 of file CraftingMissionObjective.cpp.
References _this.
void CraftingMissionObjectiveImplementation::runlock (bool doLock = true) protected
Definition at line 146 of file CraftingMissionObjective.cpp.
References _this.
void CraftingMissionObjectiveImplementation::unlock (bool doLock = true) protected
Definition at line 142 of file CraftingMissionObjective.cpp.
References _this.
void CraftingMissionObjectiveImplementation::updateMissionStatus (CreatureObject * player) virtual
Reimplemented from server::zone::objects::mission::DeliverMissionObjectiveImplementation.
Definition at line 12 of file CraftingMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::DeliverMissionObjectiveImplementation::complete(), server::zone::ZoneServer::createObject(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::DELIVEREDSTATUS, server::zone::objects::draftschematic::DraftSchematic::getDraftSlot(), server::zone::objects::draftschematic::DraftSchematic::getDraftSlotCount(), server::zone::objects::creature::CreatureObject::getPlayerObject(), DraftSlot::getResourceType(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::item, SchematicList::MISSION, server::zone::objects::mission::MissionObjectiveImplementation::mission, server::zone::objects::mission::DeliverMissionObjectiveImplementation::objectiveStatus, server::zone::objects::mission::DeliverMissionObjectiveImplementation::PICKEDUPSTATUS, server::zone::objects::scene::SceneObject::sendTo(), and server::zone::objects::mission::DeliverMissionObjectiveImplementation::updateMissionTarget().
Referenced by server::zone::objects::mission::CraftingMissionObjective::updateMissionStatus().
void CraftingMissionObjectiveImplementation::wlock (bool doLock = true) protected
Definition at line 134 of file CraftingMissionObjective.cpp.
References _this.
void CraftingMissionObjectiveImplementation::wlock (ManagedObject * obj) protected
Definition at line 138 of file CraftingMissionObjective.cpp.
References _this.
void CraftingMissionObjectiveImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::mission::DeliverMissionObjectiveImplementation.
Definition at line 186 of file CraftingMissionObjective.cpp.
References writeObjectMembers().
int CraftingMissionObjectiveImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 193 of file CraftingMissionObjective.cpp.
References server::zone::objects::mission::DeliverMissionObjectiveImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class CraftingMissionObjective friend
Definition at line 131 of file CraftingMissionObjective.h.
Member Data Documentation
WeakReference<CraftingMissionObjective*> server::zone::objects::mission::CraftingMissionObjectiveImplementation::_this
Definition at line 99 of file CraftingMissionObjective.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/CraftingMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/CraftingMissionObjective.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/CraftingMissionObjectiveImplementation.cpp