Core3: ChatOnCreateRoom Class Reference
ChatOnCreateRoom Class Reference
#include <ChatOnCreateRoom.h>
Public Member Functions
ChatOnCreateRoom (ChatRoom *room, uint32 counter)
void addToUnknownListA (ChatRoom *room)
void addToUnknownListB ()
Detailed Description
Definition at line 52 of file ChatOnCreateRoom.h.
Constructor & Destructor Documentation
ChatOnCreateRoom::ChatOnCreateRoom (ChatRoom * room, uint32 counter) inline
Definition at line 55 of file ChatOnCreateRoom.h.
References addToUnknownListA(), addToUnknownListB(), server::chat::room::ChatRoom::getCreator(), server::chat::room::ChatRoom::getFullPath(), server::chat::room::ChatRoom::getGalaxyName(), server::chat::room::ChatRoom::getRoomID(), and server::chat::room::ChatRoom::getTitle().
Member Function Documentation
void ChatOnCreateRoom::addToUnknownListA (ChatRoom * room) inline
Definition at line 85 of file ChatOnCreateRoom.h.
Referenced by ChatOnCreateRoom().
void ChatOnCreateRoom::addToUnknownListB () inline
Definition at line 103 of file ChatOnCreateRoom.h.
Referenced by ChatOnCreateRoom().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/chat/ChatOnCreateRoom.h