Core3: server::zone::objects::mission::MissionObjectiveImplementation Class Reference
server::zone::objects::mission::MissionObjectiveImplementation Class Reference
#include <MissionObjective.h>
Public Member Functions
MissionObjectiveImplementation (MissionObject *parent)
MissionObjectiveImplementation (DummyConstructorParameter *param)
virtual void initializeTransientMembers ()
virtual void destroyObjectFromDatabase ()
virtual int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
virtual void activate ()
virtual void deactivate ()
virtual void abort ()
virtual void complete ()
virtual void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
virtual Vector3 getEndPosition ()
operator const MissionObjective * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< MissionObjective * > _this
Protected Member Functions
virtual ~MissionObjectiveImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< MissionObject * > mission
unsigned int objectiveType
Time missionStartTime
Reference
< FailMissionAfterCertainTimeTask * > failTask
unsigned long long timeRemaining
bool activated
Private Attributes
SortedVector< ManagedReference
< MissionObserver * > > observers
Friends
class MissionObjective
Detailed Description
Definition at line 179 of file MissionObjective.h.
Constructor & Destructor Documentation
MissionObjectiveImplementation::MissionObjectiveImplementation (MissionObject * parent)
Definition at line 522 of file MissionObjective.cpp.
References _initializeImplementation(), activated, mission, missionStartTime, and timeRemaining.
MissionObjectiveImplementation::MissionObjectiveImplementation (DummyConstructorParameter * param)
Definition at line 336 of file MissionObjective.cpp.
References _initializeImplementation().
MissionObjectiveImplementation::~MissionObjectiveImplementation () protected virtual
Definition at line 341 of file MissionObjective.cpp.
Member Function Documentation
DistributedObjectStub * MissionObjectiveImplementation::_getStub ()
Definition at line 361 of file MissionObjective.cpp.
References _this.
void MissionObjectiveImplementation::_initializeImplementation () protected
Definition at line 348 of file MissionObjective.cpp.
References _serializationHelperMethod(), and _this.
Referenced by MissionObjectiveImplementation().
void MissionObjectiveImplementation::_serializationHelperMethod () protected
Definition at line 397 of file MissionObjective.cpp.
Referenced by _initializeImplementation(), server::zone::objects::mission::ReconMissionObjectiveImplementation::_serializationHelperMethod(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::_serializationHelperMethod(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::_serializationHelperMethod(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::_serializationHelperMethod(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::_serializationHelperMethod(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::_serializationHelperMethod(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::_serializationHelperMethod().
void MissionObjectiveImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 356 of file MissionObjective.cpp.
References _this.
Referenced by server::zone::objects::mission::ReconMissionObjectiveImplementation::_setStub(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::_setStub(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::_setStub(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::_setStub(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::_setStub(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::_setStub(), server::zone::objects::mission::BountyMissionObjectiveImplementation::_setStub(), and server::zone::objects::mission::MissionObjective::MissionObjective().
void MissionObjectiveImplementation::abort () virtual
Reimplemented in server::zone::objects::mission::BountyMissionObjectiveImplementation, server::zone::objects::mission::DeliverMissionObjectiveImplementation, server::zone::objects::mission::DestroyMissionObjectiveImplementation, server::zone::objects::mission::EntertainerMissionObjectiveImplementation, server::zone::objects::mission::HuntingMissionObjectiveImplementation, server::zone::objects::mission::ReconMissionObjectiveImplementation, server::zone::objects::mission::SurveyMissionObjectiveImplementation, and server::zone::objects::mission::CraftingMissionObjectiveImplementation.
Definition at line 89 of file MissionObjectiveImplementation.cpp.
References failTask.
Referenced by server::zone::objects::mission::MissionObjective::abort(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::abort(), server::zone::objects::mission::ReconMissionObjectiveImplementation::abort(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::abort(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::abort(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::abort(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::abort(), server::zone::objects::mission::BountyMissionObjectiveImplementation::abort(), and fail().
void MissionObjectiveImplementation::activate () virtual
Reimplemented in server::zone::objects::mission::BountyMissionObjectiveImplementation, server::zone::objects::mission::DeliverMissionObjectiveImplementation, server::zone::objects::mission::DestroyMissionObjectiveImplementation, server::zone::objects::mission::EntertainerMissionObjectiveImplementation, server::zone::objects::mission::HuntingMissionObjectiveImplementation, server::zone::objects::mission::ReconMissionObjectiveImplementation, and server::zone::objects::mission::SurveyMissionObjectiveImplementation.
Definition at line 45 of file MissionObjectiveImplementation.cpp.
References _this, activated, failTask, missionStartTime, and timeRemaining.
Referenced by server::zone::objects::mission::MissionObjective::activate(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::activate(), server::zone::objects::mission::ReconMissionObjectiveImplementation::activate(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::activate(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::activate(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::activate(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::activate(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::activate().
void MissionObjectiveImplementation::addObserver (MissionObserver * observer, bool makePersistent)
Definition at line 78 of file MissionObjectiveImplementation.cpp.
References _this, and observers.
Referenced by server::zone::objects::mission::SurveyMissionObjectiveImplementation::activate(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::activate(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::activate(), server::zone::objects::mission::MissionObjective::addObserver(), server::zone::objects::mission::BountyMissionObjectiveImplementation::addObserverToCreature(), and server::zone::objects::mission::DestroyMissionObjectiveImplementation::spawnLair().
void MissionObjectiveImplementation::awardFactionPoints ()
Definition at line 95 of file MissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObject::FACTIONIMPERIAL, server::zone::objects::mission::MissionObject::FACTIONNEUTRAL, server::zone::objects::mission::MissionObject::FACTIONREBEL, getPlayerOwner(), and mission.
Referenced by server::zone::objects::mission::MissionObjective::awardFactionPoints().
void MissionObjectiveImplementation::awardReward ()
Definition at line 153 of file MissionObjectiveImplementation.cpp.
References _this, getEndPosition(), getPlayerOwner(), mission, and server::chat::StringIdChatParameter::setDI().
Referenced by server::zone::objects::mission::MissionObjective::awardReward().
void MissionObjectiveImplementation::complete () virtual
Reimplemented in server::zone::objects::mission::BountyMissionObjectiveImplementation, server::zone::objects::mission::DeliverMissionObjectiveImplementation, server::zone::objects::mission::DestroyMissionObjectiveImplementation, server::zone::objects::mission::EntertainerMissionObjectiveImplementation, server::zone::objects::mission::HuntingMissionObjectiveImplementation, server::zone::objects::mission::ReconMissionObjectiveImplementation, and server::zone::objects::mission::SurveyMissionObjectiveImplementation.
Definition at line 59 of file MissionObjectiveImplementation.cpp.
References _this, and getPlayerOwner().
Referenced by server::zone::objects::mission::MissionObjective::complete(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::complete(), server::zone::objects::mission::ReconMissionObjectiveImplementation::complete(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::complete(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::complete(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::complete(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::complete(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::complete().
void MissionObjectiveImplementation::deactivate () virtual
Reimplemented in server::zone::objects::mission::BountyMissionObjectiveImplementation, and server::zone::objects::mission::DeliverMissionObjectiveImplementation.
Definition at line 574 of file MissionObjective.cpp.
References activated.
Referenced by server::zone::objects::mission::MissionObjective::deactivate(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::deactivate(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::deactivate().
void MissionObjectiveImplementation::destroyObjectFromDatabase () virtual
Destroys this object from database
Precondition
{ this is locked }
Postcondition
{ this is locked }
Reimplemented in server::zone::objects::mission::DestroyMissionObjectiveImplementation.
Definition at line 25 of file MissionObjectiveImplementation.cpp.
References _this, server::zone::objects::mission::MissionObserver::destroyObjectFromDatabase(), and observers.
Referenced by server::zone::objects::mission::MissionObjective::destroyObjectFromDatabase(), and server::zone::objects::mission::DestroyMissionObjectiveImplementation::destroyObjectFromDatabase().
void MissionObjectiveImplementation::dropObserver (MissionObserver * observer, bool removeFromDatabase)
Definition at line 546 of file MissionObjective.cpp.
References server::zone::objects::mission::MissionObserver::destroyObjectFromDatabase(), and observers.
Referenced by server::zone::objects::mission::SurveyMissionObjectiveImplementation::abort(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::abort(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::abort(), server::zone::objects::mission::MissionObjective::dropObserver(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::notifyObserverEvent(), server::zone::objects::mission::BountyMissionObjectiveImplementation::removeNpcTargetObservers(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::removeObserver().
void MissionObjectiveImplementation::fail () virtual
Definition at line 148 of file MissionObjectiveImplementation.cpp.
References abort(), and removeMissionFromPlayer().
Referenced by server::zone::objects::mission::MissionObjective::fail(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::findValidSpawnPosition(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handlePlayerKilled(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::spawnTarget().
void MissionObjectiveImplementation::finalize () protected
Definition at line 345 of file MissionObjective.cpp.
Vector3 MissionObjectiveImplementation::getEndPosition () virtual
Reimplemented in server::zone::objects::mission::BountyMissionObjectiveImplementation, server::zone::objects::mission::DestroyMissionObjectiveImplementation, server::zone::objects::mission::EntertainerMissionObjectiveImplementation, server::zone::objects::mission::SurveyMissionObjectiveImplementation, server::zone::objects::mission::HuntingMissionObjectiveImplementation, and server::zone::objects::mission::ReconMissionObjectiveImplementation.
Definition at line 207 of file MissionObjectiveImplementation.cpp.
References TerrainManager::getHeight(), getPlayerOwner(), and mission.
Referenced by awardReward(), and server::zone::objects::mission::MissionObjective::getEndPosition().
ManagedWeakReference< MissionObject * > MissionObjectiveImplementation::getMissionObject ()
Definition at line 579 of file MissionObjective.cpp.
References mission.
Referenced by server::zone::objects::mission::HuntingMissionObjectiveImplementation::activate(), server::zone::objects::mission::MissionObjective::getMissionObject(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::performDroidAction().
unsigned int MissionObjectiveImplementation::getObjectiveType ()
Definition at line 584 of file MissionObjective.cpp.
References objectiveType.
Referenced by server::zone::objects::mission::MissionObjective::getObjectiveType().
MissionObserver * MissionObjectiveImplementation::getObserver (int index)
Definition at line 564 of file MissionObjective.cpp.
References observers.
Referenced by server::zone::objects::mission::SurveyMissionObjectiveImplementation::abort(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::abort(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::abort(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::clearLocationActiveAreaAndObservers(), server::zone::objects::mission::MissionObjective::getObserver(), server::zone::objects::mission::BountyMissionObjectiveImplementation::removeNpcTargetObservers(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::removeObserver().
int MissionObjectiveImplementation::getObserverCount ()
Definition at line 554 of file MissionObjective.cpp.
References observers.
Referenced by server::zone::objects::mission::HuntingMissionObjectiveImplementation::abort(), server::zone::objects::mission::BountyMissionObjectiveImplementation::activate(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::clearLocationActiveAreaAndObservers(), server::zone::objects::mission::MissionObjective::getObserverCount(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::removeObserver().
ManagedWeakReference< CreatureObject * > MissionObjectiveImplementation::getPlayerOwner ()
Definition at line 35 of file MissionObjectiveImplementation.cpp.
References mission, and SceneObjectType::PLAYERCREATURE.
Referenced by server::zone::objects::mission::CraftingMissionObjectiveImplementation::abort(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::abort(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::abort(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::abort(), server::zone::objects::mission::BountyMissionObjectiveImplementation::abort(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::activate(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::activate(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::activate(), server::zone::objects::mission::BountyMissionObjectiveImplementation::activate(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::activateWithResult(), server::zone::objects::mission::BountyMissionObjectiveImplementation::addPlayerTargetObservers(), server::zone::objects::mission::BountyMissionObjectiveImplementation::addToBountyLock(), awardFactionPoints(), awardReward(), complete(), server::zone::objects::mission::BountyMissionObjectiveImplementation::complete(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::findValidSpawnPosition(), server::zone::objects::mission::ReconMissionObjectiveImplementation::getEndPosition(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::getEndPosition(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::getEndPosition(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::getEndPosition(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::getEndPosition(), getEndPosition(), server::zone::objects::mission::MissionObjective::getPlayerOwner(), server::zone::objects::mission::BountyMissionObjectiveImplementation::getTargetPosition(), server::zone::objects::mission::BountyMissionObjectiveImplementation::getTargetZoneName(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleDefenderAdded(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleDefenderDropped(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetKilled(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetReceivesDamage(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handlePlayerKilled(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::notifyObserverEvent(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::notifyObserverEvent(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::notifyObserverEvent(), server::zone::objects::mission::BountyMissionObjectiveImplementation::removeFromBountyLock(), removeMissionFromPlayer(), server::zone::objects::mission::BountyMissionObjectiveImplementation::removePlayerTargetObservers(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::spawnLair(), server::zone::objects::mission::BountyMissionObjectiveImplementation::spawnTarget(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::startCompleteTask(), server::zone::objects::mission::BountyMissionObjectiveImplementation::startNpcTargetTask(), server::zone::objects::mission::BountyMissionObjectiveImplementation::updateMissionStatus(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::updateWaypoint().
bool MissionObjectiveImplementation::hasObservers ()
Definition at line 569 of file MissionObjective.cpp.
References observers.
Referenced by server::zone::objects::mission::SurveyMissionObjectiveImplementation::abort(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::abort(), server::zone::objects::mission::BountyMissionObjectiveImplementation::abort(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::activate(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::activate(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::activate(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::activate(), and server::zone::objects::mission::MissionObjective::hasObservers().
void MissionObjectiveImplementation::initializeTransientMembers () virtual
Reimplemented in server::zone::objects::mission::BountyMissionObjectiveImplementation, server::zone::objects::mission::DeliverMissionObjectiveImplementation, server::zone::objects::mission::DestroyMissionObjectiveImplementation, server::zone::objects::mission::EntertainerMissionObjectiveImplementation, server::zone::objects::mission::HuntingMissionObjectiveImplementation, server::zone::objects::mission::ReconMissionObjectiveImplementation, server::zone::objects::mission::SurveyMissionObjectiveImplementation, and server::zone::objects::mission::CraftingMissionObjectiveImplementation.
Definition at line 536 of file MissionObjective.cpp.
References activated.
Referenced by server::zone::objects::mission::MissionObjective::initializeTransientMembers(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::initializeTransientMembers(), server::zone::objects::mission::ReconMissionObjectiveImplementation::initializeTransientMembers(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::initializeTransientMembers(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::initializeTransientMembers(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::initializeTransientMembers(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::initializeTransientMembers(), server::zone::objects::mission::BountyMissionObjectiveImplementation::initializeTransientMembers(), and readObject().
void MissionObjectiveImplementation::lock (bool doLock = true) protected
Definition at line 369 of file MissionObjective.cpp.
References _this.
void MissionObjectiveImplementation::lock (ManagedObject * obj) protected
Definition at line 373 of file MissionObjective.cpp.
References _this.
int MissionObjectiveImplementation::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2) virtual
Reimplemented in server::zone::objects::mission::BountyMissionObjectiveImplementation, server::zone::objects::mission::DestroyMissionObjectiveImplementation, server::zone::objects::mission::EntertainerMissionObjectiveImplementation, server::zone::objects::mission::HuntingMissionObjectiveImplementation, and server::zone::objects::mission::SurveyMissionObjectiveImplementation.
Definition at line 541 of file MissionObjective.cpp.
Referenced by server::zone::objects::mission::MissionObjective::notifyObserverEvent().
MissionObjectiveImplementation::operator const MissionObjective * ()
Definition at line 365 of file MissionObjective.cpp.
void MissionObjectiveImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented in server::zone::objects::mission::BountyMissionObjectiveImplementation, server::zone::objects::mission::DeliverMissionObjectiveImplementation, server::zone::objects::mission::DestroyMissionObjectiveImplementation, server::zone::objects::mission::EntertainerMissionObjectiveImplementation, server::zone::objects::mission::SurveyMissionObjectiveImplementation, server::zone::objects::mission::HuntingMissionObjectiveImplementation, server::zone::objects::mission::ReconMissionObjectiveImplementation, and server::zone::objects::mission::CraftingMissionObjectiveImplementation.
Definition at line 404 of file MissionObjective.cpp.
References initializeTransientMembers(), and readObjectMember().
bool MissionObjectiveImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 423 of file MissionObjective.cpp.
References failTask, mission, missionStartTime, objectiveType, observers, and timeRemaining.
Referenced by readObject(), server::zone::objects::mission::ReconMissionObjectiveImplementation::readObjectMember(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::readObjectMember(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::readObjectMember(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::readObjectMember(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::readObjectMember(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::readObjectMember(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::readObjectMember().
void MissionObjectiveImplementation::removeAllObservers ()
Definition at line 559 of file MissionObjective.cpp.
References observers.
Referenced by server::zone::objects::mission::EntertainerMissionObjectiveImplementation::clearLocationActiveAreaAndObservers(), and server::zone::objects::mission::MissionObjective::removeAllObservers().
void MissionObjectiveImplementation::removeMissionFromPlayer ()
Definition at line 136 of file MissionObjectiveImplementation.cpp.
References server::zone::ZoneServer::getMissionManager(), getPlayerOwner(), mission, and server::zone::managers::mission::MissionManager::removeMission().
Referenced by server::zone::objects::mission::DeliverMissionObjectiveImplementation::activate(), server::zone::objects::mission::BountyMissionObjectiveImplementation::activate(), fail(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetKilled(), and server::zone::objects::mission::MissionObjective::removeMissionFromPlayer().
void MissionObjectiveImplementation::rlock (bool doLock = true) protected
Definition at line 377 of file MissionObjective.cpp.
References _this.
void MissionObjectiveImplementation::runlock (bool doLock = true) protected
Definition at line 393 of file MissionObjective.cpp.
References _this.
void MissionObjectiveImplementation::unlock (bool doLock = true) protected
Definition at line 389 of file MissionObjective.cpp.
References _this.
void MissionObjectiveImplementation::wlock (bool doLock = true) protected
Definition at line 381 of file MissionObjective.cpp.
References _this.
void MissionObjectiveImplementation::wlock (ManagedObject * obj) protected
Definition at line 385 of file MissionObjective.cpp.
References _this.
void MissionObjectiveImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented in server::zone::objects::mission::BountyMissionObjectiveImplementation, server::zone::objects::mission::DeliverMissionObjectiveImplementation, server::zone::objects::mission::DestroyMissionObjectiveImplementation, server::zone::objects::mission::EntertainerMissionObjectiveImplementation, server::zone::objects::mission::SurveyMissionObjectiveImplementation, server::zone::objects::mission::HuntingMissionObjectiveImplementation, server::zone::objects::mission::ReconMissionObjectiveImplementation, and server::zone::objects::mission::CraftingMissionObjectiveImplementation.
Definition at line 457 of file MissionObjective.cpp.
References writeObjectMembers().
int MissionObjectiveImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 464 of file MissionObjective.cpp.
References failTask, mission, missionStartTime, objectiveType, observers, and timeRemaining.
Referenced by writeObject(), server::zone::objects::mission::ReconMissionObjectiveImplementation::writeObjectMembers(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::writeObjectMembers(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::writeObjectMembers(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::writeObjectMembers(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::writeObjectMembers(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::writeObjectMembers(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::writeObjectMembers().
Friends And Related Function Documentation
friend class MissionObjective friend
Definition at line 281 of file MissionObjective.h.
Member Data Documentation
WeakReference<MissionObjective*> server::zone::objects::mission::MissionObjectiveImplementation::_this
Definition at line 247 of file MissionObjective.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), activate(), addObserver(), awardReward(), complete(), destroyObjectFromDatabase(), lock(), rlock(), runlock(), unlock(), and wlock().
bool server::zone::objects::mission::MissionObjectiveImplementation::activated protected
Definition at line 193 of file MissionObjective.h.
Referenced by activate(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::activate(), deactivate(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::deactivate(), initializeTransientMembers(), and MissionObjectiveImplementation().
Reference<FailMissionAfterCertainTimeTask* > server::zone::objects::mission::MissionObjectiveImplementation::failTask protected
Definition at line 189 of file MissionObjective.h.
Referenced by abort(), activate(), readObjectMember(), and writeObjectMembers().
ManagedWeakReference<MissionObject* > server::zone::objects::mission::MissionObjectiveImplementation::mission protected
Definition at line 183 of file MissionObjective.h.
Referenced by server::zone::objects::mission::CraftingMissionObjectiveImplementation::abort(), server::zone::objects::mission::BountyMissionObjectiveImplementation::abort(), server::zone::objects::mission::ReconMissionObjectiveImplementation::activate(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::activate(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::activate(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::activateWithResult(), server::zone::objects::mission::BountyMissionObjectiveImplementation::addPlayerTargetObservers(), server::zone::objects::mission::BountyMissionObjectiveImplementation::addToBountyLock(), awardFactionPoints(), awardReward(), server::zone::objects::mission::BountyMissionObjectiveImplementation::complete(), server::zone::objects::mission::ReconMissionObjectiveImplementation::getEndPosition(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::getEndPosition(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::getEndPosition(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::getEndPosition(), getEndPosition(), getMissionObject(), getPlayerOwner(), server::zone::objects::mission::BountyMissionObjectiveImplementation::getTargetPosition(), server::zone::objects::mission::BountyMissionObjectiveImplementation::getTargetZoneName(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleDefenderAdded(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleDefenderDropped(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetKilled(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetReceivesDamage(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handlePlayerKilled(), server::zone::objects::mission::BountyMissionObjectiveImplementation::isPlayerTarget(), MissionObjectiveImplementation(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::notifyObserverEvent(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::notifyObserverEvent(), server::zone::objects::mission::BountyMissionObjectiveImplementation::playerHasMissionOfCorrectLevel(), readObjectMember(), server::zone::objects::mission::BountyMissionObjectiveImplementation::removeFromBountyLock(), removeMissionFromPlayer(), server::zone::objects::mission::BountyMissionObjectiveImplementation::removePlayerTargetObservers(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::spawnLair(), server::zone::objects::mission::BountyMissionObjectiveImplementation::spawnTarget(), server::zone::objects::mission::BountyMissionObjectiveImplementation::startNpcTargetTask(), server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::updateMissionStatus(), server::zone::objects::mission::BountyMissionObjectiveImplementation::updateMissionStatus(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::updateMissionTarget(), server::zone::objects::mission::BountyMissionObjectiveImplementation::updateWaypoint(), and writeObjectMembers().
Time server::zone::objects::mission::MissionObjectiveImplementation::missionStartTime protected
Definition at line 187 of file MissionObjective.h.
Referenced by activate(), MissionObjectiveImplementation(), readObjectMember(), and writeObjectMembers().
unsigned int server::zone::objects::mission::MissionObjectiveImplementation::objectiveType protected
Definition at line 185 of file MissionObjective.h.
Referenced by getObjectiveType(), readObjectMember(), and writeObjectMembers().
SortedVector<ManagedReference<MissionObserver* > > server::zone::objects::mission::MissionObjectiveImplementation::observers private
Definition at line 180 of file MissionObjective.h.
Referenced by addObserver(), destroyObjectFromDatabase(), dropObserver(), getObserver(), getObserverCount(), hasObservers(), readObjectMember(), removeAllObservers(), and writeObjectMembers().
unsigned long long server::zone::objects::mission::MissionObjectiveImplementation::timeRemaining protected
Definition at line 191 of file MissionObjective.h.
Referenced by activate(), MissionObjectiveImplementation(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObjective.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObjectiveImplementation.cpp