Core3: RecycleResourceTask Class Reference
RecycleResourceTask Class Reference
#include <RecycleResourceTask.h>
Public Member Functions
RecycleResourceTask (RecycleTool *reco, TangibleObject *tano)
void run ()
void removeFromRecycler ()
Private Attributes
ManagedReference< RecycleTool * > recycler
ManagedReference
< TangibleObject * > insertedItem
ManagedReference< ResourceSpawn * > resource
ManagedReference
< CreatureObject * > player
ManagedReference< SceneObject * > inventory
int resourceRecycleType
Detailed Description
Definition at line 17 of file RecycleResourceTask.h.
Constructor & Destructor Documentation
RecycleResourceTask::RecycleResourceTask (RecycleTool * reco, TangibleObject * tano) inline
Definition at line 27 of file RecycleResourceTask.h.
References insertedItem, inventory, player, recycler, resource, and resourceRecycleType.
Member Function Documentation
void RecycleResourceTask::removeFromRecycler () inline
Definition at line 124 of file RecycleResourceTask.h.
References insertedItem, inventory, and player.
Referenced by run().
void RecycleResourceTask::run () inline
Definition at line 36 of file RecycleResourceTask.h.
References server::zone::objects::resource::ResourceContainer::getQuantity(), server::zone::managers::resource::ResourceManager::getRecycledVersion(), server::zone::managers::resource::ResourceManager::getResourceRecycleType(), server::zone::objects::resource::ResourceContainer::getSpawnObject(), server::zone::managers::resource::ResourceManager::harvestResourceToPlayer(), insertedItem, inventory, server::zone::managers::resource::ResourceManager::isRecycledResource(), player, SceneObjectType::PLAYERCREATURE, recycler, removeFromRecycler(), resource, and resourceRecycleType.
Referenced by RecycleToolContainerComponent::notifyObjectInserted().
Member Data Documentation
ManagedReference<TangibleObject*> RecycleResourceTask::insertedItem private
Definition at line 20 of file RecycleResourceTask.h.
Referenced by RecycleResourceTask(), removeFromRecycler(), and run().
ManagedReference<SceneObject*> RecycleResourceTask::inventory private
Definition at line 23 of file RecycleResourceTask.h.
Referenced by RecycleResourceTask(), removeFromRecycler(), and run().
ManagedReference<CreatureObject*> RecycleResourceTask::player private
Definition at line 22 of file RecycleResourceTask.h.
Referenced by RecycleResourceTask(), removeFromRecycler(), and run().
ManagedReference<RecycleTool*> RecycleResourceTask::recycler private
Definition at line 19 of file RecycleResourceTask.h.
Referenced by RecycleResourceTask(), and run().
ManagedReference<ResourceSpawn*> RecycleResourceTask::resource private
Definition at line 21 of file RecycleResourceTask.h.
Referenced by RecycleResourceTask(), and run().
int RecycleResourceTask::resourceRecycleType private
Definition at line 24 of file RecycleResourceTask.h.
Referenced by RecycleResourceTask(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/tool/recycle/RecycleResourceTask.h