Core3: ConcealCommand Class Reference
ConcealCommand Class Reference
#include <ConcealCommand.h>
Public Member Functions
ConcealCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Detailed Description
Definition at line 51 of file ConcealCommand.h.
Constructor & Destructor Documentation
ConcealCommand::ConcealCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 54 of file ConcealCommand.h.
Member Function Documentation
int ConcealCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Check if anything is attackable in range
Definition at line 59 of file ConcealCommand.h.
References CreatureFlag::ATTACKABLE, CamoKitTemplate::getEffectiveZone(), server::zone::Zone::getInRangeObjects(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), server::zone::templates::SharedObjectTemplate::getServerObjectCRC(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::creature::CreatureObject::isDead(), CreatureState::MASKSCENT, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and BuffType::SKILL.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/ConcealCommand.h