Core3: server::zone::objects::mission::bountyhunter::events::FindTargetTask Class Reference
server::zone::objects::mission::bountyhunter::events::FindTargetTask Class Reference
#include <FindTargetTask.h>
Public Member Functions
FindTargetTask (CreatureObject *droid, CreatureObject *player, BountyMissionObjective *objective, bool track, bool arakyd)
~FindTargetTask ()
void run ()
Private Types
enum states {
Init, DroidSent, Searching, Tracking,
Completed
}
Private Member Functions
void init (CreatureObject *player, CreatureObject *droid)
void droidSent (CreatureObject *droid)
void searching (CreatureObject *player, BountyMissionObjective *objective)
void tracking (CreatureObject *player, BountyMissionObjective *objective)
bool findAndTrackSuccess (CreatureObject *player, BountyMissionObjective *objective)
bool getSuccess (CreatureObject *player, BountyMissionObjective *objective)
int calculateTime (CreatureObject *player)
int getTargetLevel (CreatureObject *player, BountyMissionObjective *objective)
int getDistanceToTarget (CreatureObject *player, BountyMissionObjective *objective)
String getDirectionToTarget (CreatureObject *player, BountyMissionObjective *objective)
Private Attributes
ManagedWeakReference
< CreatureObject * > weakDroid
ManagedWeakReference
< CreatureObject * > weakPlayer
ManagedWeakReference
< BountyMissionObjective * > weakObjective
int timeLeft
bool success
bool track
bool arakyd
int trackingsLeft
String zoneName
states state
Detailed Description
Definition at line 61 of file FindTargetTask.h.
Member Enumeration Documentation
enum server::zone::objects::mission::bountyhunter::events::FindTargetTask::states private
Enumerator
Init
DroidSent
Searching
Tracking
Completed
Definition at line 72 of file FindTargetTask.h.
Constructor & Destructor Documentation
server::zone::objects::mission::bountyhunter::events::FindTargetTask::FindTargetTask (CreatureObject * droid, CreatureObject * player, BountyMissionObjective * objective, bool track, bool arakyd) inline
Definition at line 312 of file FindTargetTask.h.
References arakyd, calculateTime(), server::zone::objects::creature::CreatureObject::getSkillMod(), getSuccess(), Init, state, success, timeLeft, track, trackingsLeft, weakDroid, weakObjective, and weakPlayer.
server::zone::objects::mission::bountyhunter::events::FindTargetTask::~FindTargetTask () inline
Definition at line 331 of file FindTargetTask.h.
Member Function Documentation
int server::zone::objects::mission::bountyhunter::events::FindTargetTask::calculateTime (CreatureObject * player) inline private
Definition at line 210 of file FindTargetTask.h.
References server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::getSkillModFromBuffs(), and track.
Referenced by FindTargetTask(), and tracking().
void server::zone::objects::mission::bountyhunter::events::FindTargetTask::droidSent (CreatureObject * droid) inline private
Definition at line 99 of file FindTargetTask.h.
References server::zone::objects::creature::CreatureObject::destroyObjectFromWorld(), Searching, state, timeLeft, track, and Tracking.
Referenced by run().
bool server::zone::objects::mission::bountyhunter::events::FindTargetTask::findAndTrackSuccess (CreatureObject * player, BountyMissionObjective * objective) inline private
Definition at line 155 of file FindTargetTask.h.
References arakyd, getDirectionToTarget(), getDistanceToTarget(), server::zone::objects::mission::MissionObjective::getPlayerOwner(), server::zone::objects::mission::BountyMissionObjective::getTargetZoneName(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), server::zone::objects::mission::BountyMissionObjective::updateMissionStatus(), and zoneName.
Referenced by searching(), and tracking().
String server::zone::objects::mission::bountyhunter::events::FindTargetTask::getDirectionToTarget (CreatureObject * player, BountyMissionObjective * objective) inline private
Definition at line 267 of file FindTargetTask.h.
References server::zone::objects::mission::BountyMissionObjective::getTargetPosition().
Referenced by findAndTrackSuccess().
int server::zone::objects::mission::bountyhunter::events::FindTargetTask::getDistanceToTarget (CreatureObject * player, BountyMissionObjective * objective) inline private
Definition at line 257 of file FindTargetTask.h.
References server::zone::objects::mission::BountyMissionObjective::getTargetPosition().
Referenced by findAndTrackSuccess().
bool server::zone::objects::mission::bountyhunter::events::FindTargetTask::getSuccess (CreatureObject * player, BountyMissionObjective * objective) inline private
Definition at line 181 of file FindTargetTask.h.
References server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::CreatureObject::getSkillModFromBuffs(), getTargetLevel(), and track.
Referenced by FindTargetTask().
int server::zone::objects::mission::bountyhunter::events::FindTargetTask::getTargetLevel (CreatureObject * player, BountyMissionObjective * objective) inline private
Definition at line 232 of file FindTargetTask.h.
References server::zone::managers::player::PlayerManager::calculatePlayerLevel(), server::zone::templates::mobile::CreatureTemplate::getLevel(), server::zone::objects::mission::MissionObjective::getMissionObject(), server::zone::ZoneServer::getObject(), server::zone::ZoneServer::getPlayerManager(), and server::zone::objects::scene::SceneObject::getZoneServer().
Referenced by getSuccess().
void server::zone::objects::mission::bountyhunter::events::FindTargetTask::init (CreatureObject * player, CreatureObject * droid) inline private
Definition at line 76 of file FindTargetTask.h.
References arakyd, DroidSent, server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setPosture(), CreaturePosture::SITTING, state, timeLeft, and zoneName.
Referenced by run().
void server::zone::objects::mission::bountyhunter::events::FindTargetTask::run () inline
Definition at line 335 of file FindTargetTask.h.
References arakyd, Completed, DroidSent, droidSent(), Init, init(), Searching, searching(), state, success, Tracking, tracking(), weakDroid, weakObjective, weakPlayer, and zoneName.
void server::zone::objects::mission::bountyhunter::events::FindTargetTask::searching (CreatureObject * player, BountyMissionObjective * objective) inline private
Definition at line 113 of file FindTargetTask.h.
References arakyd, Completed, findAndTrackSuccess(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::mission::BountyMissionObjective::setArakydDroid(), state, and success.
Referenced by run().
void server::zone::objects::mission::bountyhunter::events::FindTargetTask::tracking (CreatureObject * player, BountyMissionObjective * objective) inline private
Definition at line 127 of file FindTargetTask.h.
References arakyd, calculateTime(), Completed, findAndTrackSuccess(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::mission::BountyMissionObjective::setArakydDroid(), state, success, Tracking, and trackingsLeft.
Referenced by run().
Member Data Documentation
bool server::zone::objects::mission::bountyhunter::events::FindTargetTask::arakyd private
Definition at line 68 of file FindTargetTask.h.
Referenced by findAndTrackSuccess(), FindTargetTask(), init(), run(), searching(), and tracking().
states server::zone::objects::mission::bountyhunter::events::FindTargetTask::state private
Definition at line 74 of file FindTargetTask.h.
Referenced by droidSent(), FindTargetTask(), init(), run(), searching(), and tracking().
bool server::zone::objects::mission::bountyhunter::events::FindTargetTask::success private
Definition at line 66 of file FindTargetTask.h.
Referenced by FindTargetTask(), run(), searching(), and tracking().
int server::zone::objects::mission::bountyhunter::events::FindTargetTask::timeLeft private
Definition at line 65 of file FindTargetTask.h.
Referenced by droidSent(), FindTargetTask(), and init().
bool server::zone::objects::mission::bountyhunter::events::FindTargetTask::track private
Definition at line 67 of file FindTargetTask.h.
Referenced by calculateTime(), droidSent(), FindTargetTask(), and getSuccess().
int server::zone::objects::mission::bountyhunter::events::FindTargetTask::trackingsLeft private
Definition at line 69 of file FindTargetTask.h.
Referenced by FindTargetTask(), and tracking().
ManagedWeakReference<CreatureObject*> server::zone::objects::mission::bountyhunter::events::FindTargetTask::weakDroid private
Definition at line 62 of file FindTargetTask.h.
Referenced by FindTargetTask(), and run().
ManagedWeakReference<BountyMissionObjective*> server::zone::objects::mission::bountyhunter::events::FindTargetTask::weakObjective private
Definition at line 64 of file FindTargetTask.h.
Referenced by FindTargetTask(), and run().
ManagedWeakReference<CreatureObject*> server::zone::objects::mission::bountyhunter::events::FindTargetTask::weakPlayer private
Definition at line 63 of file FindTargetTask.h.
Referenced by FindTargetTask(), and run().
String server::zone::objects::mission::bountyhunter::events::FindTargetTask::zoneName private
Definition at line 70 of file FindTargetTask.h.
Referenced by findAndTrackSuccess(), init(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/bountyhunter/events/FindTargetTask.h