Core3: server::zone::objects::creature::ai::bt::SequenceBehavior Class Reference
server::zone::objects::creature::ai::bt::SequenceBehavior Class Reference
#include <SequenceBehavior.h>
Public Member Functions
SequenceBehavior (BehaviorTree *sequenceTree)
virtual ~SequenceBehavior ()
Protected Member Functions
virtual void onInitialize (AiAgent *actor)
virtual int update (AiAgent *actor)
virtual void observe (AiAgent *actor)
virtual bool canObserve ()
virtual void addChild (Behavior *child)
Protected Attributes
BehaviorTree * tree
int position
int end
Protected Attributes inherited from server::zone::objects::creature::ai::bt::CompositeBehavior
Vector< Behavior * > children
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::creature::ai::bt::Behavior
static const int INVALID = 0
static const int SUCCESS = 1
static const int FAILURE = 2
static const int RUNNING = 3
static const int SUSPENDED = 4
Detailed Description
Definition at line 21 of file SequenceBehavior.h.
Constructor & Destructor Documentation
SequenceBehavior::SequenceBehavior (BehaviorTree * sequenceTree)
Definition at line 10 of file SequenceBehavior.cpp.
References tree.
SequenceBehavior::~SequenceBehavior () virtual
Definition at line 14 of file SequenceBehavior.cpp.
Member Function Documentation
virtual void server::zone::objects::creature::ai::bt::SequenceBehavior::addChild (Behavior * child) inline protected virtual
Reimplemented from server::zone::objects::creature::ai::bt::CompositeBehavior.
Definition at line 33 of file SequenceBehavior.h.
References server::zone::objects::creature::ai::bt::CompositeBehavior::addChild(), server::zone::objects::creature::ai::bt::CompositeBehavior::children, and end.
virtual bool server::zone::objects::creature::ai::bt::SequenceBehavior::canObserve () inline protected virtual
Reimplemented from server::zone::objects::creature::ai::bt::Behavior.
Definition at line 30 of file SequenceBehavior.h.
void SequenceBehavior::observe (AiAgent * actor) protected virtual
Reimplemented from server::zone::objects::creature::ai::bt::Behavior.
Definition at line 23 of file SequenceBehavior.cpp.
References server::zone::objects::creature::ai::bt::CompositeBehavior::children, end, server::zone::objects::creature::ai::bt::Behavior::FAILURE, server::zone::objects::creature::AiAgent::getBehaviorStatus(), position, server::zone::objects::creature::ai::bt::BehaviorTree::start(), server::zone::objects::creature::ai::bt::BehaviorTree::stop(), server::zone::objects::creature::ai::bt::Behavior::SUCCESS, and tree.
void SequenceBehavior::onInitialize (AiAgent * actor) protected virtual
Reimplemented from server::zone::objects::creature::ai::bt::Behavior.
Definition at line 17 of file SequenceBehavior.cpp.
References server::zone::objects::creature::ai::bt::CompositeBehavior::children, end, server::zone::objects::creature::ai::bt::Behavior::onInitialize(), position, server::zone::objects::creature::ai::bt::BehaviorTree::start(), and tree.
virtual int server::zone::objects::creature::ai::bt::SequenceBehavior::update (AiAgent * actor) inline protected virtual
Implements server::zone::objects::creature::ai::bt::Behavior.
Definition at line 28 of file SequenceBehavior.h.
References server::zone::objects::creature::ai::bt::Behavior::RUNNING.
Member Data Documentation
int server::zone::objects::creature::ai::bt::SequenceBehavior::end protected
Definition at line 32 of file SequenceBehavior.h.
Referenced by addChild(), observe(), and onInitialize().
int server::zone::objects::creature::ai::bt::SequenceBehavior::position protected
Definition at line 31 of file SequenceBehavior.h.
Referenced by observe(), and onInitialize().
BehaviorTree* server::zone::objects::creature::ai::bt::SequenceBehavior::tree protected
Definition at line 26 of file SequenceBehavior.h.
Referenced by observe(), onInitialize(), SequenceBehavior(), and server::zone::objects::creature::ai::bt::LuaSequence::setTree().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/bt/SequenceBehavior.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/bt/SequenceBehavior.cpp