Core3: server::zone::ZoneClientSessionImplementation Class Reference
server::zone::ZoneClientSessionImplementation Class Reference
#include <ZoneClientSession.h>
Public Member Functions
ZoneClientSessionImplementation (BaseClientProxy *session)
ZoneClientSessionImplementation (DummyConstructorParameter *param)
void disconnect ()
void disconnect (bool doLock)
void sendMessage (BasePacket *msg)
void balancePacketCheckupTime ()
void resetPacketCheckupTime ()
void closeConnection (bool lockPlayer, bool doLock=true)
void info (const String &msg, bool force=false)
void error (const String &msg)
String getAddress ()
void setPlayer (SceneObject *playerCreature)
void setSessionID (unsigned int id)
void setAccountID (unsigned int acc)
int getCommandCount ()
void increaseCommandCount ()
void resetCommandCount ()
Time * getCommandSpamCooldown ()
BaseClientProxy * getSession ()
ManagedWeakReference
< SceneObject * > getPlayer ()
unsigned int getSessionID ()
unsigned int getAccountID ()
bool hasCharacter (unsigned long long cid, unsigned int galaxyId)
void addCharacter (unsigned long long cid, unsigned int galaxyId)
void addBannedCharacter (unsigned long long cid, unsigned int galaxyId)
int getCharacterCount ()
int getCharacterCount (int galaxyId)
void resetCharacters ()
operator const ZoneClientSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< ZoneClientSession * > _this
Protected Member Functions
virtual ~ZoneClientSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
Reference< BaseClientProxy * > session
VectorMap< unsigned int,
unsigned long long > characters
VectorMap< unsigned int,
unsigned long long > bannedCharacters
ManagedWeakReference
< SceneObject * > player
unsigned int sessionID
unsigned int accountID
Time commandSpamCooldown
int commandCount
Private Attributes
bool disconnecting
Friends
class ZoneClientSession
Detailed Description
Definition at line 148 of file ZoneClientSession.h.
Constructor & Destructor Documentation
ZoneClientSessionImplementation::ZoneClientSessionImplementation (BaseClientProxy * session)
Definition at line 57 of file ZoneClientSessionImplementation.cpp.
References accountID, bannedCharacters, characters, commandCount, disconnecting, player, session, and sessionID.
ZoneClientSessionImplementation::ZoneClientSessionImplementation (DummyConstructorParameter * param)
Definition at line 400 of file ZoneClientSession.cpp.
References _initializeImplementation().
ZoneClientSessionImplementation::~ZoneClientSessionImplementation () protected virtual
Definition at line 405 of file ZoneClientSession.cpp.
Member Function Documentation
DistributedObjectStub * ZoneClientSessionImplementation::_getStub ()
Definition at line 425 of file ZoneClientSession.cpp.
References _this.
void ZoneClientSessionImplementation::_initializeImplementation () protected
Definition at line 412 of file ZoneClientSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ZoneClientSessionImplementation().
void ZoneClientSessionImplementation::_serializationHelperMethod () protected
Definition at line 461 of file ZoneClientSession.cpp.
Referenced by _initializeImplementation().
void ZoneClientSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 420 of file ZoneClientSession.cpp.
References _this.
Referenced by server::zone::ZoneClientSession::ZoneClientSession().
void ZoneClientSessionImplementation::addBannedCharacter (unsigned long long cid, unsigned int galaxyId)
Definition at line 660 of file ZoneClientSession.cpp.
References bannedCharacters.
Referenced by server::zone::ZoneClientSession::addBannedCharacter().
void ZoneClientSessionImplementation::addCharacter (unsigned long long cid, unsigned int galaxyId)
Definition at line 655 of file ZoneClientSession.cpp.
References characters.
Referenced by server::zone::ZoneClientSession::addCharacter().
void ZoneClientSessionImplementation::balancePacketCheckupTime ()
Definition at line 200 of file ZoneClientSessionImplementation.cpp.
References session.
Referenced by server::zone::ZoneClientSession::balancePacketCheckupTime().
void ZoneClientSessionImplementation::closeConnection (bool lockPlayer, bool doLock = true)
Definition at line 171 of file ZoneClientSessionImplementation.cpp.
References _this, server::zone::ZoneServer::addTotalResentPacket(), server::zone::ZoneServer::addTotalSentPacket(), player, session, and setPlayer().
Referenced by server::zone::ZoneClientSession::closeConnection(), and disconnect().
void ZoneClientSessionImplementation::disconnect ()
Definition at line 79 of file ZoneClientSessionImplementation.cpp.
References session.
Referenced by server::zone::ZoneClientSession::disconnect().
void ZoneClientSessionImplementation::disconnect (bool doLock)
Definition at line 89 of file ZoneClientSessionImplementation.cpp.
References _this, closeConnection(), DisconnectClientEvent::DISCONNECT, disconnecting, DisconnectClientEvent::LOGOUT, player, session, and DisconnectClientEvent::SETLINKDEAD.
void ZoneClientSessionImplementation::error (const String & msg)
Definition at line 212 of file ZoneClientSessionImplementation.cpp.
References session.
Referenced by server::zone::ZoneClientSession::error().
void ZoneClientSessionImplementation::finalize () protected
Definition at line 409 of file ZoneClientSession.cpp.
unsigned int ZoneClientSessionImplementation::getAccountID ()
Definition at line 650 of file ZoneClientSession.cpp.
References accountID.
Referenced by server::zone::ZoneClientSession::getAccountID().
String ZoneClientSessionImplementation::getAddress ()
Definition at line 216 of file ZoneClientSessionImplementation.cpp.
References session.
Referenced by server::zone::ZoneClientSession::getAddress().
int ZoneClientSessionImplementation::getCharacterCount ()
Definition at line 665 of file ZoneClientSession.cpp.
References bannedCharacters, and characters.
Referenced by server::zone::ZoneClientSession::getCharacterCount().
int ZoneClientSessionImplementation::getCharacterCount (int galaxyId)
Definition at line 224 of file ZoneClientSessionImplementation.cpp.
References bannedCharacters, and characters.
int ZoneClientSessionImplementation::getCommandCount ()
Definition at line 620 of file ZoneClientSession.cpp.
References commandCount.
Referenced by server::zone::ZoneClientSession::getCommandCount().
Time * ZoneClientSessionImplementation::getCommandSpamCooldown ()
Definition at line 635 of file ZoneClientSession.cpp.
References commandSpamCooldown.
Referenced by server::zone::ZoneClientSession::getCommandSpamCooldown().
ManagedWeakReference< SceneObject * > ZoneClientSessionImplementation::getPlayer ()
Definition at line 640 of file ZoneClientSession.cpp.
References player.
Referenced by server::zone::ZoneClientSession::getPlayer().
BaseClientProxy * ZoneClientSessionImplementation::getSession ()
Definition at line 220 of file ZoneClientSessionImplementation.cpp.
References session.
Referenced by server::zone::ZoneClientSession::getSession().
unsigned int ZoneClientSessionImplementation::getSessionID ()
Definition at line 645 of file ZoneClientSession.cpp.
References sessionID.
Referenced by server::zone::ZoneClientSession::getSessionID().
bool ZoneClientSessionImplementation::hasCharacter (unsigned long long cid, unsigned int galaxyId)
Definition at line 240 of file ZoneClientSessionImplementation.cpp.
References characters.
Referenced by server::zone::ZoneClientSession::hasCharacter().
void ZoneClientSessionImplementation::increaseCommandCount ()
Definition at line 625 of file ZoneClientSession.cpp.
References commandCount.
Referenced by server::zone::ZoneClientSession::increaseCommandCount().
void ZoneClientSessionImplementation::info (const String & msg, bool force = false)
Definition at line 208 of file ZoneClientSessionImplementation.cpp.
References session.
Referenced by server::zone::ZoneClientSession::info().
void ZoneClientSessionImplementation::lock (bool doLock = true) protected
Definition at line 433 of file ZoneClientSession.cpp.
References _this.
void ZoneClientSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 437 of file ZoneClientSession.cpp.
References _this.
ZoneClientSessionImplementation::operator const ZoneClientSession * ()
Definition at line 429 of file ZoneClientSession.cpp.
void ZoneClientSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 468 of file ZoneClientSession.cpp.
References readObjectMember().
bool ZoneClientSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 487 of file ZoneClientSession.cpp.
References accountID, bannedCharacters, characters, commandCount, commandSpamCooldown, disconnecting, player, and sessionID.
Referenced by readObject().
void ZoneClientSessionImplementation::resetCharacters ()
Definition at line 670 of file ZoneClientSession.cpp.
References bannedCharacters, and characters.
Referenced by server::zone::ZoneClientSession::resetCharacters().
void ZoneClientSessionImplementation::resetCommandCount ()
Definition at line 630 of file ZoneClientSession.cpp.
References commandCount.
Referenced by server::zone::ZoneClientSession::resetCommandCount().
void ZoneClientSessionImplementation::resetPacketCheckupTime ()
Definition at line 204 of file ZoneClientSessionImplementation.cpp.
References session.
Referenced by server::zone::ZoneClientSession::resetPacketCheckupTime().
void ZoneClientSessionImplementation::rlock (bool doLock = true) protected
Definition at line 441 of file ZoneClientSession.cpp.
References _this.
void ZoneClientSessionImplementation::runlock (bool doLock = true) protected
Definition at line 457 of file ZoneClientSession.cpp.
References _this.
void ZoneClientSessionImplementation::sendMessage (BasePacket * msg)
Definition at line 83 of file ZoneClientSessionImplementation.cpp.
References session.
Referenced by server::zone::ZoneClientSession::sendMessage().
void ZoneClientSessionImplementation::setAccountID (unsigned int acc)
Definition at line 615 of file ZoneClientSession.cpp.
References accountID.
Referenced by server::zone::ZoneClientSession::setAccountID().
void ZoneClientSessionImplementation::setPlayer (SceneObject * playerCreature)
Definition at line 143 of file ZoneClientSessionImplementation.cpp.
References _this, server::zone::managers::player::PlayerManager::decreaseOnlineCharCount(), server::zone::ZoneServer::decreaseOnlinePlayers(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::ZoneServer::increaseOnlinePlayers(), and player.
Referenced by closeConnection(), and server::zone::ZoneClientSession::setPlayer().
void ZoneClientSessionImplementation::setSessionID (unsigned int id)
Definition at line 610 of file ZoneClientSession.cpp.
References sessionID.
Referenced by server::zone::ZoneClientSession::setSessionID().
void ZoneClientSessionImplementation::unlock (bool doLock = true) protected
Definition at line 453 of file ZoneClientSession.cpp.
References _this.
void ZoneClientSessionImplementation::wlock (bool doLock = true) protected
Definition at line 445 of file ZoneClientSession.cpp.
References _this.
void ZoneClientSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 449 of file ZoneClientSession.cpp.
References _this.
void ZoneClientSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 529 of file ZoneClientSession.cpp.
References writeObjectMembers().
int ZoneClientSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 536 of file ZoneClientSession.cpp.
References accountID, bannedCharacters, characters, commandCount, commandSpamCooldown, disconnecting, player, and sessionID.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ZoneClientSession friend
Definition at line 261 of file ZoneClientSession.h.
Member Data Documentation
WeakReference<ZoneClientSession*> server::zone::ZoneClientSessionImplementation::_this
Definition at line 227 of file ZoneClientSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), closeConnection(), disconnect(), lock(), rlock(), runlock(), setPlayer(), unlock(), and wlock().
unsigned int server::zone::ZoneClientSessionImplementation::accountID protected
Definition at line 160 of file ZoneClientSession.h.
Referenced by getAccountID(), readObjectMember(), setAccountID(), writeObjectMembers(), and ZoneClientSessionImplementation().
VectorMap<unsigned int, unsigned long long> server::zone::ZoneClientSessionImplementation::bannedCharacters protected
Definition at line 154 of file ZoneClientSession.h.
Referenced by addBannedCharacter(), getCharacterCount(), readObjectMember(), resetCharacters(), writeObjectMembers(), and ZoneClientSessionImplementation().
VectorMap<unsigned int, unsigned long long> server::zone::ZoneClientSessionImplementation::characters protected
Definition at line 152 of file ZoneClientSession.h.
Referenced by addCharacter(), getCharacterCount(), hasCharacter(), readObjectMember(), resetCharacters(), writeObjectMembers(), and ZoneClientSessionImplementation().
int server::zone::ZoneClientSessionImplementation::commandCount protected
Definition at line 168 of file ZoneClientSession.h.
Referenced by getCommandCount(), increaseCommandCount(), readObjectMember(), resetCommandCount(), writeObjectMembers(), and ZoneClientSessionImplementation().
Time server::zone::ZoneClientSessionImplementation::commandSpamCooldown protected
Definition at line 166 of file ZoneClientSession.h.
Referenced by getCommandSpamCooldown(), readObjectMember(), and writeObjectMembers().
bool server::zone::ZoneClientSessionImplementation::disconnecting private
Definition at line 163 of file ZoneClientSession.h.
Referenced by disconnect(), readObjectMember(), writeObjectMembers(), and ZoneClientSessionImplementation().
ManagedWeakReference<SceneObject* > server::zone::ZoneClientSessionImplementation::player protected
Definition at line 156 of file ZoneClientSession.h.
Referenced by closeConnection(), disconnect(), getPlayer(), readObjectMember(), setPlayer(), writeObjectMembers(), and ZoneClientSessionImplementation().
Reference<BaseClientProxy* > server::zone::ZoneClientSessionImplementation::session protected
Definition at line 150 of file ZoneClientSession.h.
Referenced by balancePacketCheckupTime(), closeConnection(), disconnect(), error(), getAddress(), getSession(), info(), resetPacketCheckupTime(), sendMessage(), and ZoneClientSessionImplementation().
unsigned int server::zone::ZoneClientSessionImplementation::sessionID protected
Definition at line 158 of file ZoneClientSession.h.
Referenced by getSessionID(), readObjectMember(), setSessionID(), writeObjectMembers(), and ZoneClientSessionImplementation().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneClientSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneClientSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneClientSessionImplementation.cpp