Core3: server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation Class Reference
server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation Class Reference
#include <VendorAdBarkingSession.h>
Public Member Functions
VendorAdBarkingSessionImplementation (CreatureObject *play, SceneObject *vend)
VendorAdBarkingSessionImplementation (DummyConstructorParameter *param)
int initializeSession ()
int cancelSession ()
int clearSession ()
void setMessage (const String &mess)
void setMood (const String &mo)
void setAnimation (const String &ani)
void sendPhraseOptions ()
void sendCustomMessageInput ()
void sendMoodSelect ()
void sendAnimationSelect ()
operator const VendorAdBarkingSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< VendorAdBarkingSession * > _this
Protected Member Functions
virtual ~VendorAdBarkingSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference
< CreatureObject * > owner
ManagedReference< SceneObject * > vendor
int advertisingMod
String message
String mood
String animation
Private Member Functions
void completeSession ()
Friends
class VendorAdBarkingSession
Detailed Description
Definition at line 118 of file VendorAdBarkingSession.h.
Constructor & Destructor Documentation
VendorAdBarkingSessionImplementation::VendorAdBarkingSessionImplementation (CreatureObject * play, SceneObject * vend)
Definition at line 334 of file VendorAdBarkingSession.cpp.
References _initializeImplementation(), owner, and vendor.
VendorAdBarkingSessionImplementation::VendorAdBarkingSessionImplementation (DummyConstructorParameter * param)
Definition at line 184 of file VendorAdBarkingSession.cpp.
References _initializeImplementation().
VendorAdBarkingSessionImplementation::~VendorAdBarkingSessionImplementation () protected virtual
Definition at line 189 of file VendorAdBarkingSession.cpp.
Member Function Documentation
DistributedObjectStub * VendorAdBarkingSessionImplementation::_getStub ()
Definition at line 209 of file VendorAdBarkingSession.cpp.
References _this.
void VendorAdBarkingSessionImplementation::_initializeImplementation () protected
Definition at line 196 of file VendorAdBarkingSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by VendorAdBarkingSessionImplementation().
void VendorAdBarkingSessionImplementation::_serializationHelperMethod () protected
Definition at line 245 of file VendorAdBarkingSession.cpp.
Referenced by _initializeImplementation().
void VendorAdBarkingSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 204 of file VendorAdBarkingSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::VendorAdBarkingSession().
int VendorAdBarkingSessionImplementation::cancelSession ()
Definition at line 346 of file VendorAdBarkingSession.cpp.
References clearSession(), owner, and SessionFacadeType::VENDORADBARKING.
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::cancelSession(), completeSession(), sendAnimationSelect(), sendCustomMessageInput(), sendMoodSelect(), and sendPhraseOptions().
int VendorAdBarkingSessionImplementation::clearSession ()
Definition at line 356 of file VendorAdBarkingSession.cpp.
References owner.
Referenced by cancelSession(), and server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::clearSession().
void VendorAdBarkingSessionImplementation::completeSession () private
Definition at line 154 of file VendorAdBarkingSessionImplementation.cpp.
References animation, cancelSession(), message, mood, owner, VendorDataComponent::setAdAnimation(), VendorDataComponent::setAdBarking(), VendorDataComponent::setAdMood(), VendorDataComponent::setAdPhrase(), and vendor.
Referenced by setAnimation().
void VendorAdBarkingSessionImplementation::finalize () protected
Definition at line 193 of file VendorAdBarkingSession.cpp.
int VendorAdBarkingSessionImplementation::initializeSession ()
Definition at line 15 of file VendorAdBarkingSessionImplementation.cpp.
References _this, advertisingMod, owner, sendPhraseOptions(), and SessionFacadeType::VENDORADBARKING.
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::initializeSession().
void VendorAdBarkingSessionImplementation::lock (bool doLock = true) protected
Definition at line 217 of file VendorAdBarkingSession.cpp.
References _this.
void VendorAdBarkingSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 221 of file VendorAdBarkingSession.cpp.
References _this.
VendorAdBarkingSessionImplementation::operator const VendorAdBarkingSession * ()
Definition at line 213 of file VendorAdBarkingSession.cpp.
void VendorAdBarkingSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 252 of file VendorAdBarkingSession.cpp.
References readObjectMember().
bool VendorAdBarkingSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 271 of file VendorAdBarkingSession.cpp.
References advertisingMod, owner, and vendor.
Referenced by readObject().
void VendorAdBarkingSessionImplementation::rlock (bool doLock = true) protected
Definition at line 225 of file VendorAdBarkingSession.cpp.
References _this.
void VendorAdBarkingSessionImplementation::runlock (bool doLock = true) protected
Definition at line 241 of file VendorAdBarkingSession.cpp.
References _this.
void VendorAdBarkingSessionImplementation::sendAnimationSelect ()
Definition at line 123 of file VendorAdBarkingSessionImplementation.cpp.
References cancelSession(), owner, vendor, and SuiWindowType::VENDOR_ANIMATION.
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::sendAnimationSelect(), and setMood().
void VendorAdBarkingSessionImplementation::sendCustomMessageInput ()
Definition at line 68 of file VendorAdBarkingSessionImplementation.cpp.
References cancelSession(), owner, vendor, and SuiWindowType::VENDOR_CUSTOM_PHRASE.
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::sendCustomMessageInput().
void VendorAdBarkingSessionImplementation::sendMoodSelect ()
Definition at line 86 of file VendorAdBarkingSessionImplementation.cpp.
References cancelSession(), owner, vendor, and SuiWindowType::VENDOR_MOODS.
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::sendMoodSelect(), and setMessage().
void VendorAdBarkingSessionImplementation::sendPhraseOptions ()
Definition at line 31 of file VendorAdBarkingSessionImplementation.cpp.
References cancelSession(), owner, vendor, and SuiWindowType::VENDOR_PHRASES.
Referenced by initializeSession(), and server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::sendPhraseOptions().
void VendorAdBarkingSessionImplementation::setAnimation (const String & ani)
Definition at line 377 of file VendorAdBarkingSession.cpp.
References animation, and completeSession().
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::setAnimation().
void VendorAdBarkingSessionImplementation::setMessage (const String & mess)
Definition at line 363 of file VendorAdBarkingSession.cpp.
References message, and sendMoodSelect().
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::setMessage().
void VendorAdBarkingSessionImplementation::setMood (const String & mo)
Definition at line 370 of file VendorAdBarkingSession.cpp.
References mood, and sendAnimationSelect().
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::setMood().
void VendorAdBarkingSessionImplementation::unlock (bool doLock = true) protected
Definition at line 237 of file VendorAdBarkingSession.cpp.
References _this.
void VendorAdBarkingSessionImplementation::wlock (bool doLock = true) protected
Definition at line 229 of file VendorAdBarkingSession.cpp.
References _this.
void VendorAdBarkingSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 233 of file VendorAdBarkingSession.cpp.
References _this.
void VendorAdBarkingSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 293 of file VendorAdBarkingSession.cpp.
References writeObjectMembers().
int VendorAdBarkingSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 300 of file VendorAdBarkingSession.cpp.
References advertisingMod, owner, and vendor.
Referenced by writeObject().
Friends And Related Function Documentation
friend class VendorAdBarkingSession friend
Definition at line 195 of file VendorAdBarkingSession.h.
Member Data Documentation
WeakReference<VendorAdBarkingSession*> server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::_this
Definition at line 161 of file VendorAdBarkingSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), initializeSession(), lock(), rlock(), runlock(), unlock(), and wlock().
int server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::advertisingMod protected
Definition at line 124 of file VendorAdBarkingSession.h.
Referenced by initializeSession(), readObjectMember(), and writeObjectMembers().
String server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::animation protected
Definition at line 130 of file VendorAdBarkingSession.h.
Referenced by completeSession(), and setAnimation().
String server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::message protected
Definition at line 126 of file VendorAdBarkingSession.h.
Referenced by completeSession(), and setMessage().
String server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::mood protected
Definition at line 128 of file VendorAdBarkingSession.h.
Referenced by completeSession(), and setMood().
ManagedReference<CreatureObject* > server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::owner protected
Definition at line 120 of file VendorAdBarkingSession.h.
Referenced by cancelSession(), clearSession(), completeSession(), initializeSession(), readObjectMember(), sendAnimationSelect(), sendCustomMessageInput(), sendMoodSelect(), sendPhraseOptions(), VendorAdBarkingSessionImplementation(), and writeObjectMembers().
ManagedReference<SceneObject* > server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::vendor protected
Definition at line 122 of file VendorAdBarkingSession.h.
Referenced by completeSession(), readObjectMember(), sendAnimationSelect(), sendCustomMessageInput(), sendMoodSelect(), sendPhraseOptions(), VendorAdBarkingSessionImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/VendorAdBarkingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/VendorAdBarkingSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/vendor/VendorAdBarkingSessionImplementation.cpp