Core3: SchematicList Class Reference
SchematicList Class Reference
#include <SchematicList.h>
Public Types
enum { MISSION = 0, LOOT, QUEST }
Public Member Functions
SchematicList ()
SchematicList (const SchematicList &list)
bool add (DraftSchematic *schematic, DeltaMessage *message=NULL, int updates=1)
bool addRewardedSchematic (DraftSchematic *schematic, short type, int quantity)
void addRewardedSchematics (SceneObject *player)
void removeRewardedSchematic (DraftSchematic *schematic)
bool decreaseSchematicUseCount (DraftSchematic *schematic)
bool contains (DraftSchematic *schematic)
bool contains (Vector< ManagedReference< DraftSchematic * > > filteredschematics, DraftSchematic *schematic)
DraftSchematic * searchForDuplicate (Vector< ManagedReference< DraftSchematic * > > filteredschematics, DraftSchematic *schematic)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
Vector< ManagedReference
< DraftSchematic * > > filterSchematicList (CreatureObject *player, Vector< uint32 > *enabledTabs, int complexityLevel)
void insertToMessage (BaseMessage *msg)
Public Member Functions inherited from server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >
DeltaVector ()
DeltaVector (int initsize, int incr)
DeltaVector (const DeltaVector &v)
~DeltaVector ()
DeltaVector & operator= (const DeltaVector &v)
void addSerializableVariables ()
virtual ManagedReference
< DraftSchematic * > set (int idx, const ManagedReference< DraftSchematic * > &newValue, DeltaMessage *message=NULL, int updates=1)
virtual bool add (const ManagedReference< DraftSchematic * > &element, DeltaMessage *message=NULL, int updates=1)
ManagedReference
< DraftSchematic * > & get (int index) const
ManagedReference
< DraftSchematic * > & getSafe (int index)
ManagedReference
< DraftSchematic * > remove (int index, DeltaMessage *message=NULL, int updates=1)
void removeAll (DeltaMessage *message=NULL)
virtual void insertItemToMessage (ManagedReference< DraftSchematic * > *item, BaseMessage *msg)
virtual bool contains (const ManagedReference< DraftSchematic * > &element)
int find (const ManagedReference< DraftSchematic * > &element)
uint32 getUpdateCounter ()
uint32 getNewUpdateCounter (int increment)
void setUpdateCounter (int count)
void resetUpdateCounter ()
int size ()
ReadWriteLock * getLock ()
Protected Attributes
VectorMap< ManagedReference
< DraftSchematic * >, int > rewardedSchematics
Protected Attributes inherited from server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >
Vector< ManagedReference
< DraftSchematic * > > vector
uint32 updateCounter
ReadWriteLock * mutex
Detailed Description
Definition at line 15 of file SchematicList.h.
Member Enumeration Documentation
anonymous enum
Enumerator
MISSION
LOOT
QUEST
Definition at line 23 of file SchematicList.h.
Constructor & Destructor Documentation
SchematicList::SchematicList () inline
Definition at line 25 of file SchematicList.h.
References rewardedSchematics.
SchematicList::SchematicList (const SchematicList & list) inline
Definition at line 29 of file SchematicList.h.
References rewardedSchematics.
Member Function Documentation
bool SchematicList::add (DraftSchematic * schematic, DeltaMessage * message = NULL, int updates = 1)
Must be client CRC
Definition at line 88 of file SchematicList.cpp.
References server::zone::objects::scene::SceneObject::getClientObjectCRC(), DeltaMessage::startList(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::updateCounter, and server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::vector.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addSchematics().
bool SchematicList::addRewardedSchematic (DraftSchematic * schematic, short type, int quantity)
Definition at line 48 of file SchematicList.cpp.
References MISSION, and rewardedSchematics.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addRewardedSchematic().
void SchematicList::addRewardedSchematics (SceneObject * player)
Definition at line 31 of file SchematicList.cpp.
References server::zone::objects::player::PlayerObject::addSchematics(), server::zone::objects::scene::SceneObject::isPlayerObject(), and rewardedSchematics.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), and server::zone::objects::player::PlayerObjectImplementation::removeSchematics().
bool SchematicList::contains (DraftSchematic * schematic)
Definition at line 106 of file SchematicList.cpp.
References server::zone::objects::scene::SceneObject::getClientObjectCRC(), server::zone::objects::draftschematic::DraftSchematic::getCustomName(), and server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::size().
Referenced by server::zone::objects::player::PlayerObjectImplementation::addRewardedSchematic(), and server::zone::objects::player::PlayerObjectImplementation::addSchematics().
bool SchematicList::contains (Vector< ManagedReference< DraftSchematic * > > filteredschematics, DraftSchematic * schematic)
Definition at line 124 of file SchematicList.cpp.
References server::zone::objects::scene::SceneObject::getClientObjectCRC(), and server::zone::objects::draftschematic::DraftSchematic::getCustomName().
bool SchematicList::decreaseSchematicUseCount (DraftSchematic * schematic)
Definition at line 68 of file SchematicList.cpp.
References removeRewardedSchematic(), and rewardedSchematics.
Referenced by server::zone::objects::player::PlayerObjectImplementation::decreaseSchematicUseCount().
Vector< ManagedReference< DraftSchematic * > > SchematicList::filterSchematicList (CreatureObject * player, Vector< uint32 > * enabledTabs, int complexityLevel)
Complexity Requirements 1 - 15 General Crafting Tool 16 - 20 Specialized Crafting Tool 21 - 25 Specialized Crafting Tool + Public Crafting Station 26 - Specialized Crafting Tool + Private Crafting Station
http://swg.stratics.com/content/gameplay/guides/guides.php?Cat=664&uid=902
Definition at line 152 of file SchematicList.cpp.
References server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::size().
Referenced by server::zone::objects::player::PlayerObjectImplementation::filterSchematicList().
void SchematicList::insertToMessage (BaseMessage * msg) virtual
Must be client CRC
Reimplemented from server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >.
Definition at line 173 of file SchematicList.cpp.
References server::zone::objects::scene::SceneObject::getClientObjectCRC(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::size(), and server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::updateCounter.
bool SchematicList::parseFromBinaryStream (ObjectInputStream * stream)
Definition at line 23 of file SchematicList.cpp.
References rewardedSchematics.
void SchematicList::removeRewardedSchematic (DraftSchematic * schematic)
Definition at line 63 of file SchematicList.cpp.
References rewardedSchematics.
Referenced by decreaseSchematicUseCount(), and server::zone::objects::player::PlayerObjectImplementation::removeRewardedSchematic().
DraftSchematic* SchematicList::searchForDuplicate (Vector< ManagedReference< DraftSchematic * > > filteredschematics, DraftSchematic * schematic)
bool SchematicList::toBinaryStream (ObjectOutputStream * stream)
Definition at line 15 of file SchematicList.cpp.
References rewardedSchematics.
Member Data Documentation
VectorMap<ManagedReference<DraftSchematic* >, int > SchematicList::rewardedSchematics protected
This vector is for schematics without skills when we need to reload them when skills are dropped
Definition at line 20 of file SchematicList.h.
Referenced by addRewardedSchematic(), addRewardedSchematics(), decreaseSchematicUseCount(), parseFromBinaryStream(), removeRewardedSchematic(), SchematicList(), and toBinaryStream().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/variables/SchematicList.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/variables/SchematicList.cpp