Core3: VitalizeCommand Class Reference
VitalizeCommand Class Reference
#include <VitalizeCommand.h>
Public Member Functions
VitalizeCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file VitalizeCommand.h.
Constructor & Destructor Documentation
VitalizeCommand::VitalizeCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file VitalizeCommand.h.
Member Function Documentation
int VitalizeCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 58 of file VitalizeCommand.h.
References CreatureAttribute::ACTION, server::zone::objects::creature::CreatureObject::addBuff(), server::zone::objects::creature::CreatureObject::addCooldown(), server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), server::zone::objects::creature::CreatureObject::getCooldownTime(), server::zone::objects::creature::CreatureObject::getSpecies(), CreatureAttribute::HEALTH, BuffType::INNATE, BuffCRC::INNATE_BUFF_VITALIZE, server::zone::objects::creature::CreatureObject::isPlayerCreature(), CreatureAttribute::MIND, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::objects::scene::SceneObject::showFlyText().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/VitalizeCommand.h