Core3: server::zone::objects::mission::HuntingMissionObjectiveAdapter Class Reference
server::zone::objects::mission::HuntingMissionObjectiveAdapter Class Reference
#include <HuntingMissionObjective.h>
Public Member Functions
HuntingMissionObjectiveAdapter (HuntingMissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveAdapter
MissionObjectiveAdapter (MissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Detailed Description
Definition at line 193 of file HuntingMissionObjective.h.
Constructor & Destructor Documentation
HuntingMissionObjectiveAdapter::HuntingMissionObjectiveAdapter (HuntingMissionObjective * impl)
Definition at line 284 of file HuntingMissionObjective.cpp.
Member Function Documentation
void HuntingMissionObjectiveAdapter::abort ()
Definition at line 338 of file HuntingMissionObjective.cpp.
Referenced by invokeMethod().
void HuntingMissionObjectiveAdapter::activate ()
Definition at line 334 of file HuntingMissionObjective.cpp.
Referenced by invokeMethod().
void HuntingMissionObjectiveAdapter::complete ()
Definition at line 342 of file HuntingMissionObjective.cpp.
Referenced by invokeMethod().
void HuntingMissionObjectiveAdapter::finalize ()
Definition at line 326 of file HuntingMissionObjective.cpp.
Referenced by invokeMethod().
void HuntingMissionObjectiveAdapter::initializeTransientMembers ()
Definition at line 330 of file HuntingMissionObjective.cpp.
Referenced by invokeMethod().
void HuntingMissionObjectiveAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 287 of file HuntingMissionObjective.cpp.
References abort(), activate(), complete(), finalize(), initializeTransientMembers(), notifyObserverEvent(), RPC_ABORT__, RPC_ACTIVATE__, RPC_COMPLETE__, RPC_FINALIZE__, RPC_INITIALIZETRANSIENTMEMBERS__, and RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
int HuntingMissionObjectiveAdapter::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 346 of file HuntingMissionObjective.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/HuntingMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/HuntingMissionObjective.cpp