Core3: server::web::session::HttpSession Class Reference
server::web::session::HttpSession Class Reference
#include <HttpSession.h>
Public Member Functions
HttpSession ()
#include "../HttpRequest.h"
virtual ~HttpSession ()
void update (struct mg_connection *conn, const struct mg_request_info *request_info)
bool hasExpired ()
HttpRequest * getRequest ()
HttpResponse * getResponse ()
String getUserName ()
void setUserName (String value)
String getPassword ()
void setPassword (String value)
String getSessionId ()
void setSessionId (String value)
long getSessionIp ()
void setSessionIp (long value)
bool isAuthenticated ()
void setAuthenticated (bool auth)
Private Member Functions
void updateTimestamp ()
String generateRandomKey (int length)
Private Attributes
HttpRequest * request
The request.
HttpResponse * response
The response.
bool authenticated
Request members.
uint64 timestamp
Last Activity.
String user
Current user - Core3 Account Name.
String password
Current users password.
String sessionId
Session id.
long ip
ip
bool canSetId
Detailed Description
Definition at line 28 of file HttpSession.h.
Constructor & Destructor Documentation
HttpSession::HttpSession ()
#include "../HttpRequest.h"
Definition at line 13 of file HttpSession.cpp.
References authenticated, canSetId, generateRandomKey(), request, response, and sessionId.
HttpSession::~HttpSession () virtual
Definition at line 30 of file HttpSession.cpp.
References request, and response.
Member Function Documentation
String HttpSession::generateRandomKey (int length) private
Definition at line 59 of file HttpSession.cpp.
Referenced by HttpSession().
String server::web::session::HttpSession::getPassword () inline
Definition at line 82 of file HttpSession.h.
Referenced by server::web::WebServer::authorize().
HttpRequest* server::web::session::HttpSession::getRequest () inline
Definition at line 66 of file HttpSession.h.
Referenced by server::web::WebServer::dispatch(), server::web::HttpResponse::forwardTo(), server::web::WebServer::getSession(), and server::web::WebServer::handleRequest().
HttpResponse* server::web::session::HttpSession::getResponse () inline
Definition at line 70 of file HttpSession.h.
Referenced by server::web::WebServer::dispatch(), and server::web::WebServer::handleRequest().
String server::web::session::HttpSession::getSessionId () inline
Definition at line 90 of file HttpSession.h.
Referenced by server::web::WebServer::getSession(), and LoginServlet::handleGet().
long server::web::session::HttpSession::getSessionIp () inline
Definition at line 107 of file HttpSession.h.
String server::web::session::HttpSession::getUserName () inline
Definition at line 74 of file HttpSession.h.
Referenced by server::web::WebServer::authorize().
bool HttpSession::hasExpired ()
Definition at line 39 of file HttpSession.cpp.
References authenticated, server::web::WebServer::sessionTimeout, and timestamp.
Referenced by server::web::WebServer::getSession().
bool server::web::session::HttpSession::isAuthenticated () inline
Definition at line 115 of file HttpSession.h.
Referenced by server::web::WebServer::handleRequest().
void server::web::session::HttpSession::setAuthenticated (bool auth) inline
Definition at line 119 of file HttpSession.h.
Referenced by server::web::WebServer::authorize().
void server::web::session::HttpSession::setPassword (String value) inline
Definition at line 86 of file HttpSession.h.
Referenced by server::web::WebServer::authorize(), and LoginServlet::handlePost().
void server::web::session::HttpSession::setSessionId (String value) inline
Definition at line 94 of file HttpSession.h.
Referenced by server::web::WebServer::getSession().
void server::web::session::HttpSession::setSessionIp (long value) inline
Definition at line 111 of file HttpSession.h.
Referenced by server::web::WebServer::getSession(), and LoginServlet::handlePost().
void server::web::session::HttpSession::setUserName (String value) inline
Definition at line 78 of file HttpSession.h.
Referenced by LoginServlet::handlePost().
void HttpSession::update (struct mg_connection * conn, const struct mg_request_info * request_info)
Definition at line 47 of file HttpSession.cpp.
References request, response, server::web::HttpResponse::update(), server::web::HttpRequest::update(), and updateTimestamp().
Referenced by server::web::WebServer::getSession().
void HttpSession::updateTimestamp () private
Definition at line 55 of file HttpSession.cpp.
References timestamp.
Referenced by update().
Member Data Documentation
bool server::web::session::HttpSession::authenticated private
Request members.
Definition at line 38 of file HttpSession.h.
Referenced by hasExpired(), and HttpSession().
bool server::web::session::HttpSession::canSetId private
Definition at line 55 of file HttpSession.h.
Referenced by HttpSession().
long server::web::session::HttpSession::ip private
ip
Definition at line 53 of file HttpSession.h.
String server::web::session::HttpSession::password private
Current users password.
Definition at line 47 of file HttpSession.h.
HttpRequest* server::web::session::HttpSession::request private
The request.
Definition at line 32 of file HttpSession.h.
Referenced by HttpSession(), update(), and ~HttpSession().
HttpResponse* server::web::session::HttpSession::response private
The response.
Definition at line 35 of file HttpSession.h.
Referenced by HttpSession(), update(), and ~HttpSession().
String server::web::session::HttpSession::sessionId private
Session id.
Definition at line 50 of file HttpSession.h.
Referenced by HttpSession().
uint64 server::web::session::HttpSession::timestamp private
Last Activity.
Definition at line 41 of file HttpSession.h.
Referenced by hasExpired(), and updateTimestamp().
String server::web::session::HttpSession::user private
Current user - Core3 Account Name.
Definition at line 44 of file HttpSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/session/HttpSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/session/HttpSession.cpp