Core3: server::zone::objects::creature::conversation::ConversationObserverImplementation Class Reference
server::zone::objects::creature::conversation::ConversationObserverImplementation Class Reference
#include <ConversationObserver.h>
Public Member Functions
ConversationObserverImplementation (ConversationTemplate *conversationTemplate)
ConversationObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
virtual ConversationScreen * getNextConversationScreen (CreatureObject *conversingPlayer, int selectedOption, CreatureObject *conversingNPC)
virtual ConversationScreen * runScreenHandlers (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
operator const ConversationObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< ConversationObserver * > _this
Protected Member Functions
virtual void createConversationSession (CreatureObject *conversingPlayer, CreatureObject *npc)
void registerScreenHandler (const String &screenId, ScreenHandler *screenHandler)
void removeScreenHandler (const String &screenId)
void createPositionObserver (CreatureObject *player)
virtual ~ConversationObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
Reference< ConversationTemplate * > conversationTemplate
Private Member Functions
ConversationScreen * getInitialScreen ()
ConversationScreen * getConversationScreen (const String &screenName)
void cancelConversationSession (CreatureObject *conversingPlayer, CreatureObject *npc, bool forceClose=false)
void sendConversationScreenToPlayer (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, ConversationScreen *conversationScreen)
Private Attributes
VectorMap< String,
ScreenHandler * > screenHandlers
Friends
class ConversationObserver
Detailed Description
Definition at line 69 of file ConversationObserver.h.
Constructor & Destructor Documentation
ConversationObserverImplementation::ConversationObserverImplementation (ConversationTemplate * conversationTemplate)
Definition at line 52 of file ConversationObserverImplementation.cpp.
References conversationTemplate.
ConversationObserverImplementation::ConversationObserverImplementation (DummyConstructorParameter * param)
Definition at line 82 of file ConversationObserver.cpp.
References _initializeImplementation().
ConversationObserverImplementation::~ConversationObserverImplementation () protected virtual
Definition at line 87 of file ConversationObserver.cpp.
Member Function Documentation
DistributedObjectStub * ConversationObserverImplementation::_getStub ()
Definition at line 107 of file ConversationObserver.cpp.
References _this.
void ConversationObserverImplementation::_initializeImplementation () protected
Definition at line 94 of file ConversationObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ConversationObserverImplementation().
void ConversationObserverImplementation::_serializationHelperMethod () protected
Definition at line 143 of file ConversationObserver.cpp.
Referenced by _initializeImplementation(), server::zone::objects::creature::conversation::DeliverMissionConversationObserverImplementation::_serializationHelperMethod(), server::zone::objects::creature::conversation::InformantMissionConversationObserverImplementation::_serializationHelperMethod(), server::zone::objects::creature::conversation::TrainerConversationObserverImplementation::_serializationHelperMethod(), and server::zone::objects::creature::conversation::LuaConversationObserverImplementation::_serializationHelperMethod().
void ConversationObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 102 of file ConversationObserver.cpp.
References _this.
Referenced by server::zone::objects::creature::conversation::DeliverMissionConversationObserverImplementation::_setStub(), server::zone::objects::creature::conversation::InformantMissionConversationObserverImplementation::_setStub(), server::zone::objects::creature::conversation::TrainerConversationObserverImplementation::_setStub(), server::zone::objects::creature::conversation::LuaConversationObserverImplementation::_setStub(), and server::zone::objects::creature::conversation::ConversationObserver::ConversationObserver().
void ConversationObserverImplementation::cancelConversationSession (CreatureObject * conversingPlayer, CreatureObject * npc, bool forceClose = false) private
Definition at line 154 of file ConversationObserverImplementation.cpp.
References _this, SessionFacadeType::CONVERSATION, server::zone::objects::scene::SceneObject::dropActiveSession(), server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getObjectID(), ObserverEventType::POSITIONCHANGED, and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by notifyObserverEvent().
void ConversationObserverImplementation::createConversationSession (CreatureObject * conversingPlayer, CreatureObject * npc) protected virtual
Reimplemented in server::zone::objects::creature::conversation::TrainerConversationObserverImplementation.
Definition at line 146 of file ConversationObserverImplementation.cpp.
References server::zone::objects::scene::SceneObject::addActiveSession(), and SessionFacadeType::CONVERSATION.
Referenced by notifyObserverEvent().
void ConversationObserverImplementation::createPositionObserver (CreatureObject * player) protected
Definition at line 150 of file ConversationObserverImplementation.cpp.
References _this, and ObserverEventType::POSITIONCHANGED.
Referenced by notifyObserverEvent().
void ConversationObserverImplementation::finalize () protected
Definition at line 91 of file ConversationObserver.cpp.
ConversationScreen * ConversationObserverImplementation::getConversationScreen (const String & screenName) private
Definition at line 225 of file ConversationObserver.cpp.
References conversationTemplate.
Referenced by runScreenHandlers().
ConversationScreen * ConversationObserverImplementation::getInitialScreen () private
Definition at line 220 of file ConversationObserver.cpp.
References conversationTemplate.
ConversationScreen * ConversationObserverImplementation::getNextConversationScreen (CreatureObject * conversingPlayer, int selectedOption, CreatureObject * conversingNPC) virtual
Reimplemented in server::zone::objects::creature::conversation::LuaConversationObserverImplementation.
Definition at line 169 of file ConversationObserverImplementation.cpp.
References SessionFacadeType::CONVERSATION, conversationTemplate, server::zone::objects::scene::SceneObject::getActiveSession(), and server::zone::objects::player::sessions::ConversationSession::getLastConversationScreen().
Referenced by server::zone::objects::creature::conversation::ConversationObserver::getNextConversationScreen(), and notifyObserverEvent().
void ConversationObserverImplementation::lock (bool doLock = true) protected
Definition at line 115 of file ConversationObserver.cpp.
References _this.
void ConversationObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 119 of file ConversationObserver.cpp.
References _this.
int ConversationObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 56 of file ConversationObserverImplementation.cpp.
References cancelConversationSession(), SessionFacadeType::CONVERSATION, ObserverEventType::CONVERSE, createConversationSession(), createPositionObserver(), server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getDistanceTo(), getNextConversationScreen(), server::zone::objects::player::sessions::ConversationSession::getNPC(), ObserverEventType::POSITIONCHANGED, runScreenHandlers(), ObserverEventType::SELECTCONVERSATION, sendConversationScreenToPlayer(), ObserverEventType::STARTCONVERSATION, and ObserverEventType::STOPCONVERSATION.
Referenced by server::zone::objects::creature::conversation::ConversationObserver::notifyObserverEvent().
ConversationObserverImplementation::operator const ConversationObserver * ()
Definition at line 111 of file ConversationObserver.cpp.
void ConversationObserverImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented in server::zone::objects::creature::conversation::LuaConversationObserverImplementation, server::zone::objects::creature::conversation::TrainerConversationObserverImplementation, server::zone::objects::creature::conversation::DeliverMissionConversationObserverImplementation, and server::zone::objects::creature::conversation::InformantMissionConversationObserverImplementation.
Definition at line 150 of file ConversationObserver.cpp.
References readObjectMember().
bool ConversationObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 169 of file ConversationObserver.cpp.
References conversationTemplate, and screenHandlers.
Referenced by readObject(), server::zone::objects::creature::conversation::DeliverMissionConversationObserverImplementation::readObjectMember(), server::zone::objects::creature::conversation::InformantMissionConversationObserverImplementation::readObjectMember(), server::zone::objects::creature::conversation::TrainerConversationObserverImplementation::readObjectMember(), and server::zone::objects::creature::conversation::LuaConversationObserverImplementation::readObjectMember().
void ConversationObserverImplementation::registerScreenHandler (const String & screenId, ScreenHandler * screenHandler) protected
Definition at line 230 of file ConversationObserver.cpp.
References screenHandlers.
Referenced by server::zone::objects::creature::conversation::DeliverMissionConversationObserverImplementation::DeliverMissionConversationObserverImplementation(), server::zone::objects::creature::conversation::InformantMissionConversationObserverImplementation::InformantMissionConversationObserverImplementation(), and server::zone::objects::creature::conversation::TrainerConversationObserverImplementation::TrainerConversationObserverImplementation().
void ConversationObserverImplementation::removeScreenHandler (const String & screenId) protected
Definition at line 238 of file ConversationObserver.cpp.
References screenHandlers.
void ConversationObserverImplementation::rlock (bool doLock = true) protected
Definition at line 123 of file ConversationObserver.cpp.
References _this.
void ConversationObserverImplementation::runlock (bool doLock = true) protected
Definition at line 139 of file ConversationObserver.cpp.
References _this.
ConversationScreen * ConversationObserverImplementation::runScreenHandlers (CreatureObject * conversingPlayer, CreatureObject * conversingNPC, int selectedOption, ConversationScreen * conversationScreen) virtual
Reimplemented in server::zone::objects::creature::conversation::LuaConversationObserverImplementation.
Definition at line 195 of file ConversationObserverImplementation.cpp.
References server::zone::templates::mobile::ConversationScreen::cloneScreen(), getConversationScreen(), server::zone::templates::mobile::ConversationScreen::getScreenID(), and screenHandlers.
Referenced by notifyObserverEvent(), and server::zone::objects::creature::conversation::ConversationObserver::runScreenHandlers().
void ConversationObserverImplementation::sendConversationScreenToPlayer (CreatureObject * conversingPlayer, CreatureObject * conversingNPC, ConversationScreen * conversationScreen) private
Definition at line 224 of file ConversationObserverImplementation.cpp.
References SessionFacadeType::CONVERSATION, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::templates::mobile::ConversationScreen::sendTo(), and server::zone::objects::player::sessions::ConversationSession::setLastConversationScreen().
Referenced by notifyObserverEvent().
void ConversationObserverImplementation::unlock (bool doLock = true) protected
Definition at line 135 of file ConversationObserver.cpp.
References _this.
void ConversationObserverImplementation::wlock (bool doLock = true) protected
Definition at line 127 of file ConversationObserver.cpp.
References _this.
void ConversationObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 131 of file ConversationObserver.cpp.
References _this.
void ConversationObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented in server::zone::objects::creature::conversation::LuaConversationObserverImplementation, server::zone::objects::creature::conversation::TrainerConversationObserverImplementation, server::zone::objects::creature::conversation::DeliverMissionConversationObserverImplementation, and server::zone::objects::creature::conversation::InformantMissionConversationObserverImplementation.
Definition at line 187 of file ConversationObserver.cpp.
References writeObjectMembers().
int ConversationObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 194 of file ConversationObserver.cpp.
References conversationTemplate, and screenHandlers.
Referenced by writeObject(), server::zone::objects::creature::conversation::DeliverMissionConversationObserverImplementation::writeObjectMembers(), server::zone::objects::creature::conversation::InformantMissionConversationObserverImplementation::writeObjectMembers(), server::zone::objects::creature::conversation::TrainerConversationObserverImplementation::writeObjectMembers(), and server::zone::objects::creature::conversation::LuaConversationObserverImplementation::writeObjectMembers().
Friends And Related Function Documentation
friend class ConversationObserver friend
Definition at line 143 of file ConversationObserver.h.
Member Data Documentation
WeakReference<ConversationObserver*> server::zone::objects::creature::conversation::ConversationObserverImplementation::_this
Definition at line 109 of file ConversationObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), cancelConversationSession(), createPositionObserver(), lock(), rlock(), runlock(), unlock(), and wlock().
Reference<ConversationTemplate* > server::zone::objects::creature::conversation::ConversationObserverImplementation::conversationTemplate protected
Definition at line 71 of file ConversationObserver.h.
Referenced by ConversationObserverImplementation(), getConversationScreen(), getInitialScreen(), server::zone::objects::creature::conversation::LuaConversationObserverImplementation::getNextConversationScreen(), getNextConversationScreen(), readObjectMember(), server::zone::objects::creature::conversation::LuaConversationObserverImplementation::runScreenHandlers(), and writeObjectMembers().
VectorMap<String, ScreenHandler*> server::zone::objects::creature::conversation::ConversationObserverImplementation::screenHandlers private
Definition at line 74 of file ConversationObserver.h.
Referenced by readObjectMember(), registerScreenHandler(), removeScreenHandler(), runScreenHandlers(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/ConversationObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/ConversationObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/ConversationObserverImplementation.cpp