Core3: server::zone::managers::objectcontroller::ObjectControllerAdapter Class Reference
server::zone::managers::objectcontroller::ObjectControllerAdapter Class Reference
#include <ObjectController.h>
Public Member Functions
ObjectControllerAdapter (ObjectController *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void loadCommands ()
bool transferObject (SceneObject *objectToTransfer, SceneObject *destinationObject, int containmentType, bool notifyClient)
float activateCommand (CreatureObject *object, unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString &arguments)
Detailed Description
Definition at line 243 of file ObjectController.h.
Constructor & Destructor Documentation
ObjectControllerAdapter::ObjectControllerAdapter (ObjectController * impl)
Definition at line 270 of file ObjectController.cpp.
Member Function Documentation
float ObjectControllerAdapter::activateCommand (CreatureObject * object, unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString & arguments)
Definition at line 315 of file ObjectController.cpp.
Referenced by invokeMethod().
void ObjectControllerAdapter::finalize ()
Definition at line 303 of file ObjectController.cpp.
Referenced by invokeMethod().
void ObjectControllerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 273 of file ObjectController.cpp.
References activateCommand(), finalize(), loadCommands(), RPC_ACTIVATECOMMAND__CREATUREOBJECT_INT_INT_LONG_UNICODESTRING_, RPC_FINALIZE__, RPC_LOADCOMMANDS__, RPC_TRANSFEROBJECT__SCENEOBJECT_SCENEOBJECT_INT_BOOL_, and transferObject().
void ObjectControllerAdapter::loadCommands ()
Definition at line 307 of file ObjectController.cpp.
Referenced by invokeMethod().
bool ObjectControllerAdapter::transferObject (SceneObject * objectToTransfer, SceneObject * destinationObject, int containmentType, bool notifyClient)
Definition at line 311 of file ObjectController.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/objectcontroller/ObjectController.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/objectcontroller/ObjectController.cpp