Core3: BuffList Class Reference
BuffList Class Reference
#include <BuffList.h>
Public Member Functions
BuffList ()
BuffList (const BuffList &bf)
void sendTo (CreatureObject *player)
void sendDestroyTo (CreatureObject *player)
void updateBuffsToDatabase ()
void addBuff (Buff *buff)
bool removeBuff (uint32 buffcrc)
void removeBuff (Buff *buff)
void clearBuffs (bool updateclient)
String getDurationString (bool showhours=true, bool showminutes=true) const
int getBuffListSize ()
Buff * getBuffByIndex (int index)
Buff * getBuffByCRC (uint32 buffcrc)
long long getModifierByName (const String &skillMod)
bool hasBuff (uint32 buffcrc)
bool hasSpice ()
Protected Attributes
bool spiceActive
VectorMap< uint32,
ManagedReference< Buff * > > buffList
Detailed Description
Definition at line 51 of file BuffList.h.
Constructor & Destructor Documentation
BuffList::BuffList ()
Definition at line 50 of file BuffList.cpp.
References buffList, and spiceActive.
BuffList::BuffList (const BuffList & bf)
Definition at line 60 of file BuffList.cpp.
References buffList, and spiceActive.
Member Function Documentation
void BuffList::addBuff (Buff * buff)
Definition at line 95 of file BuffList.cpp.
References server::zone::objects::creature::buffs::Buff::activate(), buffList, BuffType::FOOD, server::zone::objects::creature::buffs::Buff::getBuffCRC(), server::zone::objects::creature::buffs::Buff::getBuffType(), server::zone::objects::creature::buffs::Buff::isActive(), server::zone::objects::creature::buffs::Buff::isAttributeBuff(), server::zone::objects::creature::buffs::Buff::isSpiceBuff(), removeBuff(), and spiceActive.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::addBuff().
void BuffList::clearBuffs (bool updateclient)
Definition at line 159 of file BuffList.cpp.
References buffList, and spiceActive.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::clearBuffs().
Buff* BuffList::getBuffByCRC (uint32 buffcrc) inline
Definition at line 87 of file BuffList.h.
References buffList.
Buff* BuffList::getBuffByIndex (int index) inline
Definition at line 78 of file BuffList.h.
References buffList.
Referenced by server::zone::managers::player::PlayerManagerImplementation::fixHAM(), server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), updateBuffsToDatabase(), and server::zone::managers::skill::SkillModManager::verifyBuffSkillMods().
int BuffList::getBuffListSize () inline
Definition at line 74 of file BuffList.h.
References buffList.
Referenced by server::zone::managers::player::PlayerManagerImplementation::fixHAM(), server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), updateBuffsToDatabase(), and server::zone::managers::skill::SkillModManager::verifyBuffSkillMods().
String BuffList::getDurationString (bool showhours = true, bool showminutes = true) const
long long BuffList::getModifierByName (const String & skillMod) inline
Definition at line 94 of file BuffList.h.
References buffList, and server::zone::objects::creature::buffs::Buff::getSkillModifierValue().
bool BuffList::hasBuff (uint32 buffcrc) inline
Definition at line 105 of file BuffList.h.
References buffList.
bool BuffList::hasSpice () inline
Definition at line 109 of file BuffList.h.
References spiceActive.
bool BuffList::removeBuff (uint32 buffcrc)
Definition at line 120 of file BuffList.cpp.
References buffList.
Referenced by addBuff(), and server::zone::objects::creature::CreatureObjectImplementation::removeBuff().
void BuffList::removeBuff (Buff * buff)
Definition at line 131 of file BuffList.cpp.
References buffList, server::zone::objects::creature::buffs::Buff::clearBuffEvent(), server::zone::objects::creature::buffs::Buff::deactivate(), server::zone::objects::creature::buffs::Buff::getBuffCRC(), server::zone::objects::creature::buffs::Buff::isActive(), server::zone::objects::creature::buffs::Buff::isSpiceBuff(), and spiceActive.
void BuffList::sendDestroyTo (CreatureObject * player)
Definition at line 87 of file BuffList.cpp.
References buffList, and server::zone::objects::creature::buffs::Buff::sendDestroyTo().
void BuffList::sendTo (CreatureObject * player)
Definition at line 79 of file BuffList.cpp.
References buffList, and server::zone::objects::creature::buffs::Buff::sendTo().
void BuffList::updateBuffsToDatabase ()
Definition at line 68 of file BuffList.cpp.
References getBuffByIndex(), and getBuffListSize().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::updateToDatabaseAllObjects().
Member Data Documentation
VectorMap<uint32, ManagedReference<Buff*> > BuffList::buffList protected
Definition at line 54 of file BuffList.h.
Referenced by addBuff(), BuffList(), clearBuffs(), getBuffByCRC(), getBuffByIndex(), getBuffListSize(), getModifierByName(), hasBuff(), removeBuff(), sendDestroyTo(), and sendTo().
bool BuffList::spiceActive protected
Definition at line 53 of file BuffList.h.
Referenced by addBuff(), BuffList(), clearBuffs(), hasSpice(), and removeBuff().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/BuffList.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/BuffList.cpp