Core3: server::zone::objects::creature::CreatureObjectAdapter Class Reference
server::zone::objects::creature::CreatureObjectAdapter Class Reference
#include <CreatureObject.h>
Public Member Functions
CreatureObjectAdapter (CreatureObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeMembers ()
void finalize ()
void createChildObjects ()
void initializeTransientMembers ()
void clearQueueAction (unsigned int actioncntr, float timer, unsigned int tab1, unsigned int tab2)
void sendBaselinesTo (SceneObject *player)
void sendToOwner (bool doClose)
void sendTo (SceneObject *player, bool doClose)
void sendSystemMessage (const String &message)
void playMusicMessage (const String &file)
void sendNewbieTutorialRequest (const String &request)
void sendNewbieTutorialEnableHudElement (const String &ui, bool enable)
void sendOpenHolocronToPageMessage ()
void sendSystemMessage (UnicodeString &message)
void sendSlottedObjectsTo (SceneObject *player)
void setCombatState ()
void clearCombatState (bool clearDefenders)
void setPosture (int newPosture, bool notifyClient)
float calculateSpeed ()
void updateLocomotion ()
void setHeight (float heigh, bool notifyClient)
void setAccelerationMultiplierBase (float newMultiplierBase, bool notifyClient)
void setAccelerationMultiplierMod (float newMultiplierMod, bool notifyClient)
void setSpeedMultiplierBase (float newMultiplierBase, bool notifyClient)
void setSpeedMultiplierMod (float newMultiplierMod, bool notifyClient)
void setTurnScale (float newMultiplierMod, bool notifyClient)
void setRunSpeed (float newSpeed, bool notifyClient)
void setCurrentSpeed (float newSpeed)
void setHAM (int type, int value, bool notifyClient)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient)
bool hasDamage (int attribute)
int healDamage (TangibleObject *healer, int damageType, int damage, bool notifyClient, bool notifyObservers)
int healWound (TangibleObject *healer, int damageType, int damage, bool notifyClient, bool notifyObservers)
void setBaseHAM (int type, int value, bool notifyClient)
void setWounds (int type, int value, bool notifyClient)
int addWounds (int type, int value, bool notifyClient)
void setMaxHAM (int type, int value, bool notifyClient)
void addMaxHAM (int type, int value, bool notifyClient)
void setEncumbrance (int type, int value, bool notifyClient)
void addEncumbrance (int type, int value, bool notifyClient)
void setWeapon (WeaponObject *weao, bool notifyClient)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void setInstrumentID (int instrumentid, bool notifyClient)
void setListenToID (unsigned long long id, bool notifyClient)
void setPerformanceCounter (int counter, bool notifyClient)
void setPerformanceAnimation (const String &animation, bool notifyClient)
void setShockWounds (int newShock, bool notifyClient)
void addShockWounds (int shockToAdd, bool notiyClient)
void setTargetID (unsigned long long targetID, bool notifyClient)
void setBankCredits (int credits, bool notifyClient)
void addBuff (Buff *buff)
bool removeBuff (unsigned int buffcrc)
void removeBuff (Buff *buff)
bool removeStateBuff (unsigned long long state)
void clearBuffs (bool updateclient)
void addWearableObject (TangibleObject *object, bool notifyClient)
void removeWearableObject (TangibleObject *object, bool notifyClient)
void sendBuffsTo (CreatureObject *creature)
Buff * getBuff (unsigned int buffcrc)
long long getSkillModFromBuffs (const String &skillMod)
int addDotState (unsigned long long dotType, unsigned long long objectID, unsigned int strength, byte type, unsigned int duration, float potency, unsigned int defense, int secondaryStrength)
bool healDot (unsigned long long dotType, int reduction)
void clearDots ()
bool hasBuff (unsigned int buffcrc)
void notifySelfPositionUpdate ()
void notifyPostureChange (int newPosture)
void setLevel (int level)
void updateToDatabaseAllObjects (bool startTask)
bool isResuscitable ()
void addBankCredits (int credits, bool notifyClient)
void addCashCredits (int credits, bool notifyClient)
void subtractBankCredits (int credits)
void subtractCashCredits (int credits)
bool verifyCashCredits (int credits)
bool verifyBankCredits (int credits)
bool isDancing ()
bool isPlayingMusic ()
void stopEntertaining ()
bool isEntertaining ()
void setCashCredits (int credits, bool notifyClient)
void setTerrainNegotiation (float value, bool notifyClient)
void addSkill (const String &skill, bool notifyClient)
void removeSkill (const String &skill, bool notifyClient)
void addSkillMod (const int modType, const String &skillMod, int value, bool notifyClient)
void removeSkillMod (const int modType, const String &skillMod, int value, bool notifyClient)
void removeAllSkillModsOfType (const int modType, bool notifyClient)
void updateGroupInviterID (unsigned long long id, bool notifyClient)
void updateGroup (GroupObject *group, bool notifyClient)
void enqueueCommand (unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString &arguments, int priority)
void setMood (byte moodID, bool notifyClient)
void setMoodString (const String &animation, bool notifyClient)
void deleteQueueAction (unsigned int actionCount)
bool setState (unsigned long long state, bool notifyClient)
bool clearState (unsigned long long state, bool notifyClient)
void setControlDevice (ControlDevice *device)
void setCreatureLink (CreatureObject *object, bool notifyClient)
void executeObjectControllerAction (unsigned int actionCRC)
void executeObjectControllerAction (unsigned int actionCRC, unsigned long long targetID, const UnicodeString &args)
bool isAttackableBy (CreatureObject *object)
bool isAttackableBy (TangibleObject *attacker)
bool isHealableBy (CreatureObject *object)
bool isInBountyMission (CreatureObject *bountyHunter, CreatureObject *target)
void sendConversationStartTo (SceneObject *player)
void selectConversationOption (int option, SceneObject *obj)
void sendMessage (BasePacket *msg)
void sendExecuteConsoleCommand (const String &command)
bool isAggressiveTo (CreatureObject *object)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
int notifyObjectKillObservers (TangibleObject *killer)
void notifyLoadFromDatabase ()
void setFactionRank (int rank, bool notifyClient)
String getFirstName ()
String getLastName ()
bool isOnline ()
bool canTreatInjuries ()
bool canTreatStates ()
bool canTreatWounds ()
bool canTreatConditions ()
Reference< PlayerObject * > getPlayerObject ()
AiActor * getActorObject ()
bool isListening ()
bool isWatching ()
void setClient (ZoneClientSession *cli)
void dismount ()
float calculateBFRatio ()
void setDizziedState (int durationSeconds)
void setRalliedState (int durationSeconds)
void setAimingState (int durationSeconds)
void setCoverState (int durationSeconds)
void setBerserkedState (unsigned int duration)
void setStunnedState (int durationSeconds)
void setBlindedState (int durationSeconds)
void setIntimidatedState (unsigned int mod, int durationSeconds)
void setSnaredState (int durationSeconds)
void setRootedState (int durationSeconds)
bool setNextAttackDelay (unsigned int mod, int del)
void setMeditateState ()
void activateHAMRegeneration ()
void activatePassiveWoundRegeneration ()
void activateStateRecovery ()
void updateTimeOfDeath ()
bool hasAttackDelay ()
void removeAttackDelay ()
bool hasSpice ()
void updateLastSuccessfulCombatAction ()
void updateKnockdownRecovery ()
void queueDizzyFallEvent ()
void updateLastKnockdown ()
bool checkKnockdownRecovery ()
bool checkLastKnockdown ()
void updatePostureDownRecovery ()
void updatePostureUpRecovery ()
bool checkPostureDownRecovery ()
unsigned long long getScreenPlayState (const String &screenPlay)
void setScreenPlayState (const String &screenPlay, unsigned long long state)
bool checkPostureUpRecovery ()
void updateCooldownTimer (const String &coooldownTimer, unsigned int miliSecondsToAdd)
bool checkCooldownRecovery (const String &cooldown)
void addCooldown (const String &name, unsigned int miliseconds)
void doAnimation (const String &animation)
void doCombatAnimation (CreatureObject *defender, unsigned int animationCRC, byte hit, byte trails)
void playEffect (const String &file, const String &aux)
void playEffect (const String &file)
void activateQueueAction ()
void activateImmediateAction ()
UnicodeString getCreatureName ()
bool isGrouped ()
int getBankCredits ()
int getCashCredits ()
int getBaseHAM (int idx)
int getWounds (int idx)
int getHAM (int idx)
int getMaxHAM (int idx)
int getEncumbrance (int idx)
byte getPosture ()
byte getLocomotion ()
byte getFactionRank ()
ManagedWeakReference
< CreatureObject * > getLinkedCreature ()
unsigned long long getCreatureLinkID ()
float getShockWounds ()
unsigned long long getWatchToID ()
unsigned long long getStateBitmask ()
bool hasState (unsigned long long state)
bool hasStates ()
unsigned long long getListenID ()
float getAccelerationMultiplierBase ()
float getAccelerationMultiplierMod ()
float getSpeedMultiplierBase ()
float getSpeedMultiplierMod ()
float getCurrentSpeed ()
float getRunSpeed ()
float getWalkSpeed ()
float getTurnScale ()
float getTerrainNegotiation ()
float getRunAcceleration ()
float getWalkAcceleration ()
String getPerformanceAnimation ()
String getMoodString ()
unsigned long long getWeaponID ()
Reference< WeaponObject * > getWeapon ()
Reference< GuildObject * > getGuildObject ()
int getGuildID ()
bool isInGuild ()
void setGuildObject (GuildObject *guildobj)
unsigned long long getGroupID ()
unsigned long long getGroupInviterID ()
GroupObject * getGroup ()
unsigned long long getGroupInviteCounter ()
unsigned long long getTargetID ()
byte getMoodID ()
float getSlopeModPercent ()
int getPerformanceCounter ()
int getInstrumentID ()
byte getFrozen ()
float getHeight ()
int getSpecies ()
String getSpeciesName ()
int getGender ()
int getSkillMod (const String &skillmod)
bool hasSkill (const String &skill)
void setWatchToID (unsigned long long id)
bool isCreatureObject ()
bool isNextActionPast ()
bool isTrainerCreature ()
bool isSwimming ()
ZoneClientSession * getClient ()
bool isRidingMount ()
ManagedWeakReference
< ControlDevice * > getControlDevice ()
float getSwimHeight ()
bool isIncapacitated ()
bool isDead ()
bool isKnockedDown ()
bool isKneeling ()
bool isProne ()
bool isStanding ()
bool isSitting ()
bool isSkillAnimating ()
bool isRallied ()
bool isInCombat ()
bool isDizzied ()
bool isBerserked ()
bool isStunned ()
bool isBlinded ()
bool isIntimidated ()
bool isSnared ()
bool isImmobilized ()
bool isRooted ()
bool isFrozen ()
bool isDiseased ()
bool isPoisoned ()
bool isBleeding ()
bool isOnFire ()
bool isMounted ()
bool isRidingCreature ()
bool isPeaced ()
bool isMeditating ()
bool isAiming ()
bool isInCover ()
bool isRunning ()
bool isNonPlayerCreatureObject ()
bool isCreature ()
bool isPlayerCreature ()
bool isAiActor ()
bool isInformantCreature ()
CampSiteActiveArea * getCurrentCamp ()
byte getCurrentWeather ()
void setCurrentWeather (byte value)
byte getCurrentWind ()
void setCurrentWind (byte value)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void destroyObjectFromWorld (bool sendSelfDestroy)
bool isInvisible ()
void setInvisible (bool invis)
float calculateCostAdjustment (byte stat, float baseCost)
void updateSpeedAndAccelerationMods ()
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectAdapter
TangibleObjectAdapter (TangibleObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeMembers ()
void applySkillModsTo (CreatureObject *creature, bool doCheck)
void removeSkillModsFrom (CreatureObject *creature)
void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient)
void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient)
void removeAllSkillModsOfType (const int skillType, bool notifyClient)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void sendBaselinesTo (SceneObject *player)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
void removeDefenders ()
void setCombatState ()
void setUseCount (unsigned int newUseCount, bool notifyClient)
void setCountdownTimer (unsigned int newCount, bool notifyClient)
void decreaseUseCount ()
void clearCombatState (bool clearDefenders)
bool hasDefender (SceneObject *defender)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
bool isHealableBy (CreatureObject *object)
void sendPvpStatusTo (CreatureObject *player)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient)
int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient)
void setConditionDamage (float condDamage, bool notifyClient)
void setCustomizationVariable (byte type, short value, bool notifyClient)
void setCustomizationVariable (const String &type, short value, bool notifyClient)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
bool isKiller ()
bool isTicketCollector ()
bool isTicketObject ()
int getUseCount ()
int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient)
void setCraftersName (String &name)
String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
int getJunkDealerNeeded ()
void setJunkValue (int jValue)
int getJunkValue ()
void setSerialNumber (const String &serial)
void setLevel (int lev)
String getSerialNumber ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
String repairAttempt (int repairChance)
bool isBroken ()
float getHitChance ()
void broadcastPvpStatusBitmask ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectAdapter
SceneObjectAdapter (SceneObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializePrivateData ()
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient, bool allowOverflow)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects)
void destroyObjectFromDatabase (bool destroyContainedObjects)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose)
void sendAttributeListTo (CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void openContainerTo (CreatureObject *player)
void closeContainerTo (CreatureObject *player, bool notify)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
unsigned long long getParentID ()
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
float getWorldPositionX ()
float getWorldPositionY ()
float getWorldPositionZ ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isDecoration ()
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZone (Zone *zone)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
bool containsChildObject (SceneObject *obj)
void createChildObjects ()
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
Detailed Description
Definition at line 2670 of file CreatureObject.h.
Constructor & Destructor Documentation
CreatureObjectAdapter::CreatureObjectAdapter (CreatureObject * impl)
Definition at line 5844 of file CreatureObject.cpp.
Member Function Documentation
void CreatureObjectAdapter::activateHAMRegeneration ()
Definition at line 7828 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::activateImmediateAction ()
Definition at line 7936 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::activatePassiveWoundRegeneration ()
Definition at line 7832 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::activateQueueAction ()
Definition at line 7932 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::activateStateRecovery ()
Definition at line 7836 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::addBankCredits (int credits, bool notifyClient)
Definition at line 7556 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::addBuff (Buff * buff)
Definition at line 7480 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::addCashCredits (int credits, bool notifyClient)
Definition at line 7560 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::addCooldown (const String & name, unsigned int miliseconds)
Definition at line 7912 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::addDotState (unsigned long long dotType, unsigned long long objectID, unsigned int strength, byte type, unsigned int duration, float potency, unsigned int defense, int secondaryStrength)
Definition at line 7520 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::addEncumbrance (int type, int value, bool notifyClient)
Definition at line 7432 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::addMaxHAM (int type, int value, bool notifyClient)
Definition at line 7424 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::addShockWounds (int shockToAdd, bool notiyClient)
Definition at line 7468 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::addSkill (const String & skill, bool notifyClient)
Definition at line 7604 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::addSkillMod (const int modType, const String & skillMod, int value, bool notifyClient)
Definition at line 7612 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::addWearableObject (TangibleObject * object, bool notifyClient)
Definition at line 7500 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::addWounds (int type, int value, bool notifyClient)
Definition at line 7416 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::calculateBFRatio ()
Definition at line 7776 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::calculateCostAdjustment (byte stat, float baseCost)
Definition at line 8376 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::calculateSpeed ()
Definition at line 7344 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::canTreatConditions ()
Definition at line 7748 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::canTreatInjuries ()
Definition at line 7736 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::canTreatStates ()
Definition at line 7740 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::canTreatWounds ()
Definition at line 7744 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::checkCooldownRecovery (const String & cooldown)
Definition at line 7908 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::checkKnockdownRecovery ()
Definition at line 7872 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::checkLastKnockdown ()
Definition at line 7876 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::checkPostureDownRecovery ()
Definition at line 7888 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::checkPostureUpRecovery ()
Definition at line 7900 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::clearBuffs (bool updateclient)
Definition at line 7496 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::clearCombatState (bool clearDefenders)
Definition at line 7336 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::clearDots ()
Definition at line 7528 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::clearQueueAction (unsigned int actioncntr, float timer, unsigned int tab1, unsigned int tab2)
Definition at line 7288 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::clearState (unsigned long long state, bool notifyClient)
Definition at line 7652 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::createChildObjects ()
Definition at line 7280 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::deleteQueueAction (unsigned int actionCount)
Definition at line 7644 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::destroyObjectFromWorld (bool sendSelfDestroy)
Definition at line 8364 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::dismount ()
Definition at line 7772 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::doAnimation (const String & animation)
Definition at line 7916 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::doCombatAnimation (CreatureObject * defender, unsigned int animationCRC, byte hit, byte trails)
Definition at line 7920 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::enqueueCommand (unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString & arguments, int priority)
Definition at line 7632 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::executeObjectControllerAction (unsigned int actionCRC)
Definition at line 7664 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::executeObjectControllerAction (unsigned int actionCRC, unsigned long long targetID, const UnicodeString & args)
Definition at line 7668 of file CreatureObject.cpp.
void CreatureObjectAdapter::fillAttributeList (AttributeListMessage * msg, CreatureObject * object)
Definition at line 8360 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::finalize ()
Definition at line 7276 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getAccelerationMultiplierBase ()
Definition at line 8020 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getAccelerationMultiplierMod ()
Definition at line 8024 of file CreatureObject.cpp.
Referenced by invokeMethod().
AiActor * CreatureObjectAdapter::getActorObject ()
Definition at line 7756 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getBankCredits ()
Definition at line 7948 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getBaseHAM (int idx)
Definition at line 7956 of file CreatureObject.cpp.
Referenced by invokeMethod().
Buff * CreatureObjectAdapter::getBuff (unsigned int buffcrc)
Definition at line 7512 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getCashCredits ()
Definition at line 7952 of file CreatureObject.cpp.
Referenced by invokeMethod().
ZoneClientSession * CreatureObjectAdapter::getClient ()
Definition at line 8180 of file CreatureObject.cpp.
Referenced by invokeMethod().
ManagedWeakReference< ControlDevice * > CreatureObjectAdapter::getControlDevice ()
Definition at line 8188 of file CreatureObject.cpp.
Referenced by invokeMethod().
unsigned long long CreatureObjectAdapter::getCreatureLinkID ()
Definition at line 7992 of file CreatureObject.cpp.
Referenced by invokeMethod().
UnicodeString CreatureObjectAdapter::getCreatureName ()
Definition at line 7940 of file CreatureObject.cpp.
Referenced by invokeMethod().
CampSiteActiveArea * CreatureObjectAdapter::getCurrentCamp ()
Definition at line 8336 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getCurrentSpeed ()
Definition at line 8036 of file CreatureObject.cpp.
Referenced by invokeMethod().
byte CreatureObjectAdapter::getCurrentWeather ()
Definition at line 8340 of file CreatureObject.cpp.
Referenced by invokeMethod().
byte CreatureObjectAdapter::getCurrentWind ()
Definition at line 8348 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getEncumbrance (int idx)
Definition at line 7972 of file CreatureObject.cpp.
Referenced by invokeMethod().
byte CreatureObjectAdapter::getFactionRank ()
Definition at line 7984 of file CreatureObject.cpp.
Referenced by invokeMethod().
String CreatureObjectAdapter::getFirstName ()
Definition at line 7724 of file CreatureObject.cpp.
Referenced by invokeMethod().
byte CreatureObjectAdapter::getFrozen ()
Definition at line 8132 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getGender ()
Definition at line 8148 of file CreatureObject.cpp.
Referenced by invokeMethod().
GroupObject * CreatureObjectAdapter::getGroup ()
Definition at line 8104 of file CreatureObject.cpp.
Referenced by invokeMethod().
unsigned long long CreatureObjectAdapter::getGroupID ()
Definition at line 8096 of file CreatureObject.cpp.
Referenced by invokeMethod().
unsigned long long CreatureObjectAdapter::getGroupInviteCounter ()
Definition at line 8108 of file CreatureObject.cpp.
Referenced by invokeMethod().
unsigned long long CreatureObjectAdapter::getGroupInviterID ()
Definition at line 8100 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getGuildID ()
Definition at line 8084 of file CreatureObject.cpp.
Referenced by invokeMethod().
Reference< GuildObject * > CreatureObjectAdapter::getGuildObject ()
Definition at line 8080 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getHAM (int idx)
Definition at line 7964 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getHeight ()
Definition at line 8136 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getInstrumentID ()
Definition at line 8128 of file CreatureObject.cpp.
Referenced by invokeMethod().
String CreatureObjectAdapter::getLastName ()
Definition at line 7728 of file CreatureObject.cpp.
Referenced by invokeMethod().
ManagedWeakReference< CreatureObject * > CreatureObjectAdapter::getLinkedCreature ()
Definition at line 7988 of file CreatureObject.cpp.
Referenced by invokeMethod().
unsigned long long CreatureObjectAdapter::getListenID ()
Definition at line 8016 of file CreatureObject.cpp.
Referenced by invokeMethod().
byte CreatureObjectAdapter::getLocomotion ()
Definition at line 7980 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getMaxHAM (int idx)
Definition at line 7968 of file CreatureObject.cpp.
Referenced by invokeMethod().
byte CreatureObjectAdapter::getMoodID ()
Definition at line 8116 of file CreatureObject.cpp.
Referenced by invokeMethod().
String CreatureObjectAdapter::getMoodString ()
Definition at line 8068 of file CreatureObject.cpp.
Referenced by invokeMethod().
String CreatureObjectAdapter::getPerformanceAnimation ()
Definition at line 8064 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getPerformanceCounter ()
Definition at line 8124 of file CreatureObject.cpp.
Referenced by invokeMethod().
Reference< PlayerObject * > CreatureObjectAdapter::getPlayerObject ()
Definition at line 7752 of file CreatureObject.cpp.
Referenced by invokeMethod().
byte CreatureObjectAdapter::getPosture ()
Definition at line 7976 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getRunAcceleration ()
Definition at line 8056 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getRunSpeed ()
Definition at line 8040 of file CreatureObject.cpp.
Referenced by invokeMethod().
unsigned long long CreatureObjectAdapter::getScreenPlayState (const String & screenPlay)
Definition at line 7892 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getShockWounds ()
Definition at line 7996 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getSkillMod (const String & skillmod)
Definition at line 8152 of file CreatureObject.cpp.
Referenced by invokeMethod().
long long CreatureObjectAdapter::getSkillModFromBuffs (const String & skillMod)
Definition at line 7516 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getSlopeModPercent ()
Definition at line 8120 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getSpecies ()
Definition at line 8140 of file CreatureObject.cpp.
Referenced by invokeMethod().
String CreatureObjectAdapter::getSpeciesName ()
Definition at line 8144 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getSpeedMultiplierBase ()
Definition at line 8028 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getSpeedMultiplierMod ()
Definition at line 8032 of file CreatureObject.cpp.
Referenced by invokeMethod().
unsigned long long CreatureObjectAdapter::getStateBitmask ()
Definition at line 8004 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getSwimHeight ()
Definition at line 8192 of file CreatureObject.cpp.
Referenced by invokeMethod().
unsigned long long CreatureObjectAdapter::getTargetID ()
Definition at line 8112 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getTerrainNegotiation ()
Definition at line 8052 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getTurnScale ()
Definition at line 8048 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getWalkAcceleration ()
Definition at line 8060 of file CreatureObject.cpp.
Referenced by invokeMethod().
float CreatureObjectAdapter::getWalkSpeed ()
Definition at line 8044 of file CreatureObject.cpp.
Referenced by invokeMethod().
unsigned long long CreatureObjectAdapter::getWatchToID ()
Definition at line 8000 of file CreatureObject.cpp.
Referenced by invokeMethod().
Reference< WeaponObject * > CreatureObjectAdapter::getWeapon ()
Definition at line 8076 of file CreatureObject.cpp.
Referenced by invokeMethod().
unsigned long long CreatureObjectAdapter::getWeaponID ()
Definition at line 8072 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::getWounds (int idx)
Definition at line 7960 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::handleObjectMenuSelect (CreatureObject * player, byte selectedID)
Definition at line 8356 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::hasAttackDelay ()
Definition at line 7844 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::hasBuff (unsigned int buffcrc)
Definition at line 7532 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::hasDamage (int attribute)
Definition at line 7396 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::hasSkill (const String & skill)
Definition at line 8156 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::hasSpice ()
Definition at line 7852 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::hasState (unsigned long long state)
Definition at line 8008 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::hasStates ()
Definition at line 8012 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::healDamage (TangibleObject * healer, int damageType, int damage, bool notifyClient, bool notifyObservers)
Definition at line 7400 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::healDot (unsigned long long dotType, int reduction)
Definition at line 7524 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::healWound (TangibleObject * healer, int damageType, int damage, bool notifyClient, bool notifyObservers)
Definition at line 7404 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, bool notifyClient)
Definition at line 7388 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, const String & xp, bool notifyClient)
Definition at line 7392 of file CreatureObject.cpp.
void CreatureObjectAdapter::initializeMembers ()
Definition at line 7272 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::initializeTransientMembers ()
Definition at line 7284 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 5847 of file CreatureObject.cpp.
References activateHAMRegeneration(), activateImmediateAction(), activatePassiveWoundRegeneration(), activateQueueAction(), activateStateRecovery(), addBankCredits(), addBuff(), addCashCredits(), addCooldown(), addDotState(), addEncumbrance(), addMaxHAM(), addShockWounds(), addSkill(), addSkillMod(), addWearableObject(), addWounds(), calculateBFRatio(), calculateCostAdjustment(), calculateSpeed(), canTreatConditions(), canTreatInjuries(), canTreatStates(), canTreatWounds(), checkCooldownRecovery(), checkKnockdownRecovery(), checkLastKnockdown(), checkPostureDownRecovery(), checkPostureUpRecovery(), clearBuffs(), clearCombatState(), clearDots(), clearQueueAction(), clearState(), createChildObjects(), deleteQueueAction(), destroyObjectFromWorld(), dismount(), doAnimation(), doCombatAnimation(), enqueueCommand(), executeObjectControllerAction(), fillAttributeList(), finalize(), getAccelerationMultiplierBase(), getAccelerationMultiplierMod(), getActorObject(), getBankCredits(), getBaseHAM(), getBuff(), getCashCredits(), getClient(), getControlDevice(), getCreatureLinkID(), getCreatureName(), getCurrentCamp(), getCurrentSpeed(), getCurrentWeather(), getCurrentWind(), getEncumbrance(), getFactionRank(), getFirstName(), getFrozen(), getGender(), getGroup(), getGroupID(), getGroupInviteCounter(), getGroupInviterID(), getGuildID(), getGuildObject(), getHAM(), getHeight(), getInstrumentID(), getLastName(), getLinkedCreature(), getListenID(), getLocomotion(), getMaxHAM(), getMoodID(), getMoodString(), getPerformanceAnimation(), getPerformanceCounter(), getPlayerObject(), getPosture(), getRunAcceleration(), getRunSpeed(), getScreenPlayState(), getShockWounds(), getSkillMod(), getSkillModFromBuffs(), getSlopeModPercent(), getSpecies(), getSpeciesName(), getSpeedMultiplierBase(), getSpeedMultiplierMod(), getStateBitmask(), getSwimHeight(), getTargetID(), getTerrainNegotiation(), getTurnScale(), getWalkAcceleration(), getWalkSpeed(), getWatchToID(), getWeapon(), getWeaponID(), getWounds(), handleObjectMenuSelect(), hasAttackDelay(), hasBuff(), hasDamage(), hasSkill(), hasSpice(), hasState(), hasStates(), healDamage(), healDot(), healWound(), inflictDamage(), initializeMembers(), initializeTransientMembers(), isAggressiveTo(), isAiActor(), isAiming(), isAttackableBy(), isBerserked(), isBleeding(), isBlinded(), isCreature(), isCreatureObject(), isDancing(), isDead(), isDiseased(), isDizzied(), isEntertaining(), isFrozen(), isGrouped(), isHealableBy(), isImmobilized(), isInBountyMission(), isIncapacitated(), isInCombat(), isInCover(), isInformantCreature(), isInGuild(), isIntimidated(), isInvisible(), isKneeling(), isKnockedDown(), isListening(), isMeditating(), isMounted(), isNextActionPast(), isNonPlayerCreatureObject(), isOnFire(), isOnline(), isPeaced(), isPlayerCreature(), isPlayingMusic(), isPoisoned(), isProne(), isRallied(), isResuscitable(), isRidingCreature(), isRidingMount(), isRooted(), isRunning(), isSitting(), isSkillAnimating(), isSnared(), isStanding(), isStunned(), isSwimming(), isTrainerCreature(), isWatching(), notifyLoadFromDatabase(), notifyObjectDestructionObservers(), notifyObjectInserted(), notifyObjectKillObservers(), notifyObjectRemoved(), notifyPostureChange(), notifySelfPositionUpdate(), playEffect(), playMusicMessage(), queueDizzyFallEvent(), removeAllSkillModsOfType(), removeAttackDelay(), removeBuff(), removeSkill(), removeSkillMod(), removeStateBuff(), removeWearableObject(), RPC_ACTIVATEHAMREGENERATION__, RPC_ACTIVATEIMMEDIATEACTION__, RPC_ACTIVATEPASSIVEWOUNDREGENERATION__, RPC_ACTIVATEQUEUEACTION__, RPC_ACTIVATESTATERECOVERY__, RPC_ADDBANKCREDITS__INT_BOOL_, RPC_ADDBUFF__BUFF_, RPC_ADDCASHCREDITS__INT_BOOL_, RPC_ADDCOOLDOWN__STRING_INT_, RPC_ADDDOTSTATE__LONG_LONG_INT_BYTE_INT_FLOAT_INT_INT_, RPC_ADDENCUMBRANCE__INT_INT_BOOL_, RPC_ADDMAXHAM__INT_INT_BOOL_, RPC_ADDSHOCKWOUNDS__INT_BOOL_, RPC_ADDSKILL__STRING_BOOL_, RPC_ADDSKILLMOD__INT_STRING_INT_BOOL_, RPC_ADDWEARABLEOBJECT__TANGIBLEOBJECT_BOOL_, RPC_ADDWOUNDS__INT_INT_BOOL_, RPC_CALCULATEBFRATIO__, RPC_CALCULATECOSTADJUSTMENT__BYTE_FLOAT_, RPC_CALCULATESPEED__, RPC_CANTREATCONDITIONS__, RPC_CANTREATINJURIES__, RPC_CANTREATSTATES__, RPC_CANTREATWOUNDS__, RPC_CHECKCOOLDOWNRECOVERY__STRING_, RPC_CHECKKNOCKDOWNRECOVERY__, RPC_CHECKLASTKNOCKDOWN__, RPC_CHECKPOSTUREDOWNRECOVERY__, RPC_CHECKPOSTUREUPRECOVERY__, RPC_CLEARBUFFS__BOOL_, RPC_CLEARCOMBATSTATE__BOOL_, RPC_CLEARDOTS__, RPC_CLEARQUEUEACTION__INT_FLOAT_INT_INT_, RPC_CLEARSTATE__LONG_BOOL_, RPC_CREATECHILDOBJECTS__, RPC_DELETEQUEUEACTION__INT_, RPC_DESTROYOBJECTFROMWORLD__BOOL_, RPC_DISMOUNT__, RPC_DOANIMATION__STRING_, RPC_DOCOMBATANIMATION__CREATUREOBJECT_INT_BYTE_BYTE_, RPC_ENQUEUECOMMAND__INT_INT_LONG_UNICODESTRING_INT_, RPC_EXECUTEOBJECTCONTROLLERACTION__INT_, RPC_EXECUTEOBJECTCONTROLLERACTION__INT_LONG_UNICODESTRING_, RPC_FILLATTRIBUTELIST__ATTRIBUTELISTMESSAGE_CREATUREOBJECT_, RPC_FINALIZE__, RPC_GETACCELERATIONMULTIPLIERBASE__, RPC_GETACCELERATIONMULTIPLIERMOD__, RPC_GETACTOROBJECT__, RPC_GETBANKCREDITS__, RPC_GETBASEHAM__INT_, RPC_GETBUFF__INT_, RPC_GETCASHCREDITS__, RPC_GETCLIENT__, RPC_GETCONTROLDEVICE__, RPC_GETCREATURELINKID__, RPC_GETCREATURENAME__, RPC_GETCURRENTCAMP__, RPC_GETCURRENTSPEED__, RPC_GETCURRENTWEATHER__, RPC_GETCURRENTWIND__, RPC_GETENCUMBRANCE__INT_, RPC_GETFACTIONRANK__, RPC_GETFIRSTNAME__, RPC_GETFROZEN__, RPC_GETGENDER__, RPC_GETGROUP__, RPC_GETGROUPID__, RPC_GETGROUPINVITECOUNTER__, RPC_GETGROUPINVITERID__, RPC_GETGUILDID__, RPC_GETGUILDOBJECT__, RPC_GETHAM__INT_, RPC_GETHEIGHT__, RPC_GETINSTRUMENTID__, RPC_GETLASTNAME__, RPC_GETLINKEDCREATURE__, RPC_GETLISTENID__, RPC_GETLOCOMOTION__, RPC_GETMAXHAM__INT_, RPC_GETMOODID__, RPC_GETMOODSTRING__, RPC_GETPERFORMANCEANIMATION__, RPC_GETPERFORMANCECOUNTER__, RPC_GETPLAYEROBJECT__, RPC_GETPOSTURE__, RPC_GETRUNACCELERATION__, RPC_GETRUNSPEED__, RPC_GETSCREENPLAYSTATE__STRING_, RPC_GETSHOCKWOUNDS__, RPC_GETSKILLMOD__STRING_, RPC_GETSKILLMODFROMBUFFS__STRING_, RPC_GETSLOPEMODPERCENT__, RPC_GETSPECIES__, RPC_GETSPECIESNAME__, RPC_GETSPEEDMULTIPLIERBASE__, RPC_GETSPEEDMULTIPLIERMOD__, RPC_GETSTATEBITMASK__, RPC_GETSWIMHEIGHT__, RPC_GETTARGETID__, RPC_GETTERRAINNEGOTIATION__, RPC_GETTURNSCALE__, RPC_GETWALKACCELERATION__, RPC_GETWALKSPEED__, RPC_GETWATCHTOID__, RPC_GETWEAPON__, RPC_GETWEAPONID__, RPC_GETWOUNDS__INT_, RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_, RPC_HASATTACKDELAY__, RPC_HASBUFF__INT_, RPC_HASDAMAGE__INT_, RPC_HASSKILL__STRING_, RPC_HASSPICE__, RPC_HASSTATE__LONG_, RPC_HASSTATES__, RPC_HEALDAMAGE__TANGIBLEOBJECT_INT_INT_BOOL_BOOL_, RPC_HEALDOT__LONG_INT_, RPC_HEALWOUND__TANGIBLEOBJECT_INT_INT_BOOL_BOOL_, RPC_INFLICTDAMAGE__TANGIBLEOBJECT_INT_FLOAT_BOOL_BOOL_, RPC_INFLICTDAMAGE__TANGIBLEOBJECT_INT_FLOAT_BOOL_STRING_BOOL_, RPC_INITIALIZEMEMBERS__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_ISAGGRESSIVETO__CREATUREOBJECT_, RPC_ISAIACTOR__, RPC_ISAIMING__, RPC_ISATTACKABLEBY__CREATUREOBJECT_, RPC_ISATTACKABLEBY__TANGIBLEOBJECT_, RPC_ISBERSERKED__, RPC_ISBLEEDING__, RPC_ISBLINDED__, RPC_ISCREATURE__, RPC_ISCREATUREOBJECT__, RPC_ISDANCING__, RPC_ISDEAD__, RPC_ISDISEASED__, RPC_ISDIZZIED__, RPC_ISENTERTAINING__, RPC_ISFROZEN__, RPC_ISGROUPED__, RPC_ISHEALABLEBY__CREATUREOBJECT_, RPC_ISIMMOBILIZED__, RPC_ISINBOUNTYMISSION__CREATUREOBJECT_CREATUREOBJECT_, RPC_ISINCAPACITATED__, RPC_ISINCOMBAT__, RPC_ISINCOVER__, RPC_ISINFORMANTCREATURE__, RPC_ISINGUILD__, RPC_ISINTIMIDATED__, RPC_ISINVISIBLE__, RPC_ISKNEELING__, RPC_ISKNOCKEDDOWN__, RPC_ISLISTENING__, RPC_ISMEDITATING__, RPC_ISMOUNTED__, RPC_ISNEXTACTIONPAST__, RPC_ISNONPLAYERCREATUREOBJECT__, RPC_ISONFIRE__, RPC_ISONLINE__, RPC_ISPEACED__, RPC_ISPLAYERCREATURE__, RPC_ISPLAYINGMUSIC__, RPC_ISPOISONED__, RPC_ISPRONE__, RPC_ISRALLIED__, RPC_ISRESUSCITABLE__, RPC_ISRIDINGCREATURE__, RPC_ISRIDINGMOUNT__, RPC_ISROOTED__, RPC_ISRUNNING__, RPC_ISSITTING__, RPC_ISSKILLANIMATING__, RPC_ISSNARED__, RPC_ISSTANDING__, RPC_ISSTUNNED__, RPC_ISSWIMMING__, RPC_ISTRAINERCREATURE__, RPC_ISWATCHING__, RPC_NOTIFYLOADFROMDATABASE__, RPC_NOTIFYOBJECTDESTRUCTIONOBSERVERS__TANGIBLEOBJECT_INT_, RPC_NOTIFYOBJECTINSERTED__SCENEOBJECT_, RPC_NOTIFYOBJECTKILLOBSERVERS__TANGIBLEOBJECT_, RPC_NOTIFYOBJECTREMOVED__SCENEOBJECT_, RPC_NOTIFYPOSTURECHANGE__INT_, RPC_NOTIFYSELFPOSITIONUPDATE__, RPC_PLAYEFFECT__STRING_, RPC_PLAYEFFECT__STRING_STRING_, RPC_PLAYMUSICMESSAGE__STRING_, RPC_QUEUEDIZZYFALLEVENT__, RPC_REMOVEALLSKILLMODSOFTYPE__INT_BOOL_, RPC_REMOVEATTACKDELAY__, RPC_REMOVEBUFF__BUFF_, RPC_REMOVEBUFF__INT_, RPC_REMOVESKILL__STRING_BOOL_, RPC_REMOVESKILLMOD__INT_STRING_INT_BOOL_, RPC_REMOVESTATEBUFF__LONG_, RPC_REMOVEWEARABLEOBJECT__TANGIBLEOBJECT_BOOL_, RPC_SELECTCONVERSATIONOPTION__INT_SCENEOBJECT_, RPC_SENDBASELINESTO__SCENEOBJECT_, RPC_SENDBUFFSTO__CREATUREOBJECT_, RPC_SENDCONVERSATIONSTARTTO__SCENEOBJECT_, RPC_SENDEXECUTECONSOLECOMMAND__STRING_, RPC_SENDMESSAGE__BASEPACKET_, RPC_SENDNEWBIETUTORIALENABLEHUDELEMENT__STRING_BOOL_, RPC_SENDNEWBIETUTORIALREQUEST__STRING_, RPC_SENDOPENHOLOCRONTOPAGEMESSAGE__, RPC_SENDSLOTTEDOBJECTSTO__SCENEOBJECT_, RPC_SENDSYSTEMMESSAGE__STRING_, RPC_SENDSYSTEMMESSAGE__UNICODESTRING_, RPC_SENDTO__SCENEOBJECT_BOOL_, RPC_SENDTOOWNER__BOOL_, RPC_SETACCELERATIONMULTIPLIERBASE__FLOAT_BOOL_, RPC_SETACCELERATIONMULTIPLIERMOD__FLOAT_BOOL_, RPC_SETAIMINGSTATE__INT_, RPC_SETBANKCREDITS__INT_BOOL_, RPC_SETBASEHAM__INT_INT_BOOL_, RPC_SETBERSERKEDSTATE__INT_, RPC_SETBLINDEDSTATE__INT_, RPC_SETCASHCREDITS__INT_BOOL_, RPC_SETCLIENT__ZONECLIENTSESSION_, RPC_SETCOMBATSTATE__, RPC_SETCONTROLDEVICE__CONTROLDEVICE_, RPC_SETCOVERSTATE__INT_, RPC_SETCREATURELINK__CREATUREOBJECT_BOOL_, RPC_SETCURRENTSPEED__FLOAT_, RPC_SETCURRENTWEATHER__BYTE_, RPC_SETCURRENTWIND__BYTE_, RPC_SETDIZZIEDSTATE__INT_, RPC_SETENCUMBRANCE__INT_INT_BOOL_, RPC_SETFACTIONRANK__INT_BOOL_, RPC_SETGUILDOBJECT__GUILDOBJECT_, RPC_SETHAM__INT_INT_BOOL_, RPC_SETHEIGHT__FLOAT_BOOL_, RPC_SETINSTRUMENTID__INT_BOOL_, RPC_SETINTIMIDATEDSTATE__INT_INT_, RPC_SETINVISIBLE__BOOL_, RPC_SETLEVEL__INT_, RPC_SETLISTENTOID__LONG_BOOL_, RPC_SETMAXHAM__INT_INT_BOOL_, RPC_SETMEDITATESTATE__, RPC_SETMOOD__BYTE_BOOL_, RPC_SETMOODSTRING__STRING_BOOL_, RPC_SETNEXTATTACKDELAY__INT_INT_, RPC_SETPERFORMANCEANIMATION__STRING_BOOL_, RPC_SETPERFORMANCECOUNTER__INT_BOOL_, RPC_SETPOSTURE__INT_BOOL_, RPC_SETRALLIEDSTATE__INT_, RPC_SETROOTEDSTATE__INT_, RPC_SETRUNSPEED__FLOAT_BOOL_, RPC_SETSCREENPLAYSTATE__STRING_LONG_, RPC_SETSHOCKWOUNDS__INT_BOOL_, RPC_SETSNAREDSTATE__INT_, RPC_SETSPEEDMULTIPLIERBASE__FLOAT_BOOL_, RPC_SETSPEEDMULTIPLIERMOD__FLOAT_BOOL_, RPC_SETSTATE__LONG_BOOL_, RPC_SETSTUNNEDSTATE__INT_, RPC_SETTARGETID__LONG_BOOL_, RPC_SETTERRAINNEGOTIATION__FLOAT_BOOL_, RPC_SETTURNSCALE__FLOAT_BOOL_, RPC_SETWATCHTOID__LONG_, RPC_SETWEAPON__WEAPONOBJECT_BOOL_, RPC_SETWOUNDS__INT_INT_BOOL_, RPC_STOPENTERTAINING__, RPC_SUBTRACTBANKCREDITS__INT_, RPC_SUBTRACTCASHCREDITS__INT_, RPC_UPDATECOOLDOWNTIMER__STRING_INT_, RPC_UPDATEGROUP__GROUPOBJECT_BOOL_, RPC_UPDATEGROUPINVITERID__LONG_BOOL_, RPC_UPDATEKNOCKDOWNRECOVERY__, RPC_UPDATELASTKNOCKDOWN__, RPC_UPDATELASTSUCCESSFULCOMBATACTION__, RPC_UPDATELOCOMOTION__, RPC_UPDATEPOSTUREDOWNRECOVERY__, RPC_UPDATEPOSTUREUPRECOVERY__, RPC_UPDATESPEEDANDACCELERATIONMODS__, RPC_UPDATETIMEOFDEATH__, RPC_UPDATETODATABASEALLOBJECTS__BOOL_, RPC_VERIFYBANKCREDITS__INT_, RPC_VERIFYCASHCREDITS__INT_, selectConversationOption(), sendBaselinesTo(), sendBuffsTo(), sendConversationStartTo(), sendExecuteConsoleCommand(), sendMessage(), sendNewbieTutorialEnableHudElement(), sendNewbieTutorialRequest(), sendOpenHolocronToPageMessage(), sendSlottedObjectsTo(), sendSystemMessage(), sendTo(), sendToOwner(), setAccelerationMultiplierBase(), setAccelerationMultiplierMod(), setAimingState(), setBankCredits(), setBaseHAM(), setBerserkedState(), setBlindedState(), setCashCredits(), setClient(), setCombatState(), setControlDevice(), setCoverState(), setCreatureLink(), setCurrentSpeed(), setCurrentWeather(), setCurrentWind(), setDizziedState(), setEncumbrance(), setFactionRank(), setGuildObject(), setHAM(), setHeight(), setInstrumentID(), setIntimidatedState(), setInvisible(), setLevel(), setListenToID(), setMaxHAM(), setMeditateState(), setMood(), setMoodString(), setNextAttackDelay(), setPerformanceAnimation(), setPerformanceCounter(), setPosture(), setRalliedState(), setRootedState(), setRunSpeed(), setScreenPlayState(), setShockWounds(), setSnaredState(), setSpeedMultiplierBase(), setSpeedMultiplierMod(), setState(), setStunnedState(), setTargetID(), setTerrainNegotiation(), setTurnScale(), setWatchToID(), setWeapon(), setWounds(), stopEntertaining(), subtractBankCredits(), subtractCashCredits(), updateCooldownTimer(), updateGroup(), updateGroupInviterID(), updateKnockdownRecovery(), updateLastKnockdown(), updateLastSuccessfulCombatAction(), updateLocomotion(), updatePostureDownRecovery(), updatePostureUpRecovery(), updateSpeedAndAccelerationMods(), updateTimeOfDeath(), updateToDatabaseAllObjects(), verifyBankCredits(), and verifyCashCredits().
bool CreatureObjectAdapter::isAggressiveTo (CreatureObject * object)
Definition at line 7704 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isAiActor ()
Definition at line 8328 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isAiming ()
Definition at line 8304 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isAttackableBy (CreatureObject * object)
Definition at line 7672 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isAttackableBy (TangibleObject * attacker)
Definition at line 7676 of file CreatureObject.cpp.
bool CreatureObjectAdapter::isBerserked ()
Definition at line 8240 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isBleeding ()
Definition at line 8280 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isBlinded ()
Definition at line 8248 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isCreature ()
Definition at line 8320 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isCreatureObject ()
Definition at line 8164 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isDancing ()
Definition at line 7580 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isDead ()
Definition at line 8200 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isDiseased ()
Definition at line 8272 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isDizzied ()
Definition at line 8236 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isEntertaining ()
Definition at line 7592 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isFrozen ()
Definition at line 8268 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isGrouped ()
Definition at line 7944 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isHealableBy (CreatureObject * object)
Definition at line 7680 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isImmobilized ()
Definition at line 8260 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isInBountyMission (CreatureObject * bountyHunter, CreatureObject * target)
Definition at line 7684 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isIncapacitated ()
Definition at line 8196 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isInCombat ()
Definition at line 8232 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isInCover ()
Definition at line 8308 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isInformantCreature ()
Definition at line 8332 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isInGuild ()
Definition at line 8088 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isIntimidated ()
Definition at line 8252 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isInvisible ()
Definition at line 8368 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isKneeling ()
Definition at line 8208 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isKnockedDown ()
Definition at line 8204 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isListening ()
Definition at line 7760 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isMeditating ()
Definition at line 8300 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isMounted ()
Definition at line 8288 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isNextActionPast ()
Definition at line 8168 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isNonPlayerCreatureObject ()
Definition at line 8316 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isOnFire ()
Definition at line 8284 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isOnline ()
Definition at line 7732 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isPeaced ()
Definition at line 8296 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isPlayerCreature ()
Definition at line 8324 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isPlayingMusic ()
Definition at line 7584 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isPoisoned ()
Definition at line 8276 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isProne ()
Definition at line 8212 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isRallied ()
Definition at line 8228 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isResuscitable ()
Definition at line 7552 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isRidingCreature ()
Definition at line 8292 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isRidingMount ()
Definition at line 8184 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isRooted ()
Definition at line 8264 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isRunning ()
Definition at line 8312 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isSitting ()
Definition at line 8220 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isSkillAnimating ()
Definition at line 8224 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isSnared ()
Definition at line 8256 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isStanding ()
Definition at line 8216 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isStunned ()
Definition at line 8244 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isSwimming ()
Definition at line 8176 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isTrainerCreature ()
Definition at line 8172 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::isWatching ()
Definition at line 7764 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::notifyLoadFromDatabase ()
Definition at line 7716 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::notifyObjectDestructionObservers (TangibleObject * attacker, int condition)
Definition at line 7708 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::notifyObjectInserted (SceneObject * object)
Definition at line 7440 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::notifyObjectKillObservers (TangibleObject * killer)
Definition at line 7712 of file CreatureObject.cpp.
Referenced by invokeMethod().
int CreatureObjectAdapter::notifyObjectRemoved (SceneObject * object)
Definition at line 7444 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::notifyPostureChange (int newPosture)
Definition at line 7540 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::notifySelfPositionUpdate ()
Definition at line 7536 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::playEffect (const String & file, const String & aux)
Definition at line 7924 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::playEffect (const String & file)
Definition at line 7928 of file CreatureObject.cpp.
void CreatureObjectAdapter::playMusicMessage (const String & file)
Definition at line 7308 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::queueDizzyFallEvent ()
Definition at line 7864 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::removeAllSkillModsOfType (const int modType, bool notifyClient)
Definition at line 7620 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::removeAttackDelay ()
Definition at line 7848 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::removeBuff (unsigned int buffcrc)
Definition at line 7484 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::removeBuff (Buff * buff)
Definition at line 7488 of file CreatureObject.cpp.
void CreatureObjectAdapter::removeSkill (const String & skill, bool notifyClient)
Definition at line 7608 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::removeSkillMod (const int modType, const String & skillMod, int value, bool notifyClient)
Definition at line 7616 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::removeStateBuff (unsigned long long state)
Definition at line 7492 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::removeWearableObject (TangibleObject * object, bool notifyClient)
Definition at line 7504 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::selectConversationOption (int option, SceneObject * obj)
Definition at line 7692 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendBaselinesTo (SceneObject * player)
Definition at line 7292 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendBuffsTo (CreatureObject * creature)
Definition at line 7508 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendConversationStartTo (SceneObject * player)
Definition at line 7688 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendExecuteConsoleCommand (const String & command)
Definition at line 7700 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendMessage (BasePacket * msg)
Definition at line 7696 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendNewbieTutorialEnableHudElement (const String & ui, bool enable)
Definition at line 7316 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendNewbieTutorialRequest (const String & request)
Definition at line 7312 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendOpenHolocronToPageMessage ()
Definition at line 7320 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendSlottedObjectsTo (SceneObject * player)
Definition at line 7328 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendSystemMessage (const String & message)
Definition at line 7304 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendSystemMessage (UnicodeString & message)
Definition at line 7324 of file CreatureObject.cpp.
void CreatureObjectAdapter::sendTo (SceneObject * player, bool doClose)
Definition at line 7300 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::sendToOwner (bool doClose)
Definition at line 7296 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setAccelerationMultiplierBase (float newMultiplierBase, bool notifyClient)
Definition at line 7356 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setAccelerationMultiplierMod (float newMultiplierMod, bool notifyClient)
Definition at line 7360 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setAimingState (int durationSeconds)
Definition at line 7788 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setBankCredits (int credits, bool notifyClient)
Definition at line 7476 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setBaseHAM (int type, int value, bool notifyClient)
Definition at line 7408 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setBerserkedState (unsigned int duration)
Definition at line 7796 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setBlindedState (int durationSeconds)
Definition at line 7804 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setCashCredits (int credits, bool notifyClient)
Definition at line 7596 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setClient (ZoneClientSession * cli)
Definition at line 7768 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setCombatState ()
Definition at line 7332 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setControlDevice (ControlDevice * device)
Definition at line 7656 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setCoverState (int durationSeconds)
Definition at line 7792 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setCreatureLink (CreatureObject * object, bool notifyClient)
Definition at line 7660 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setCurrentSpeed (float newSpeed)
Definition at line 7380 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setCurrentWeather (byte value)
Definition at line 8344 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setCurrentWind (byte value)
Definition at line 8352 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setDizziedState (int durationSeconds)
Definition at line 7780 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setEncumbrance (int type, int value, bool notifyClient)
Definition at line 7428 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setFactionRank (int rank, bool notifyClient)
Definition at line 7720 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setGuildObject (GuildObject * guildobj)
Definition at line 8092 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setHAM (int type, int value, bool notifyClient)
Definition at line 7384 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setHeight (float heigh, bool notifyClient)
Definition at line 7352 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setInstrumentID (int instrumentid, bool notifyClient)
Definition at line 7448 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setIntimidatedState (unsigned int mod, int durationSeconds)
Definition at line 7808 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setInvisible (bool invis)
Definition at line 8372 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setLevel (int level)
Definition at line 7544 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setListenToID (unsigned long long id, bool notifyClient)
Definition at line 7452 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setMaxHAM (int type, int value, bool notifyClient)
Definition at line 7420 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setMeditateState ()
Definition at line 7824 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setMood (byte moodID, bool notifyClient)
Definition at line 7636 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setMoodString (const String & animation, bool notifyClient)
Definition at line 7640 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::setNextAttackDelay (unsigned int mod, int del)
Definition at line 7820 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setPerformanceAnimation (const String & animation, bool notifyClient)
Definition at line 7460 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setPerformanceCounter (int counter, bool notifyClient)
Definition at line 7456 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setPosture (int newPosture, bool notifyClient)
Definition at line 7340 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setRalliedState (int durationSeconds)
Definition at line 7784 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setRootedState (int durationSeconds)
Definition at line 7816 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setRunSpeed (float newSpeed, bool notifyClient)
Definition at line 7376 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setScreenPlayState (const String & screenPlay, unsigned long long state)
Definition at line 7896 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setShockWounds (int newShock, bool notifyClient)
Definition at line 7464 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setSnaredState (int durationSeconds)
Definition at line 7812 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setSpeedMultiplierBase (float newMultiplierBase, bool notifyClient)
Definition at line 7364 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setSpeedMultiplierMod (float newMultiplierMod, bool notifyClient)
Definition at line 7368 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::setState (unsigned long long state, bool notifyClient)
Definition at line 7648 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setStunnedState (int durationSeconds)
Definition at line 7800 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setTargetID (unsigned long long targetID, bool notifyClient)
Definition at line 7472 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setTerrainNegotiation (float value, bool notifyClient)
Definition at line 7600 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setTurnScale (float newMultiplierMod, bool notifyClient)
Definition at line 7372 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setWatchToID (unsigned long long id)
Definition at line 8160 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setWeapon (WeaponObject * weao, bool notifyClient)
Definition at line 7436 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::setWounds (int type, int value, bool notifyClient)
Definition at line 7412 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::stopEntertaining ()
Definition at line 7588 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::subtractBankCredits (int credits)
Definition at line 7564 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::subtractCashCredits (int credits)
Definition at line 7568 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updateCooldownTimer (const String & coooldownTimer, unsigned int miliSecondsToAdd)
Definition at line 7904 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updateGroup (GroupObject * group, bool notifyClient)
Definition at line 7628 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updateGroupInviterID (unsigned long long id, bool notifyClient)
Definition at line 7624 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updateKnockdownRecovery ()
Definition at line 7860 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updateLastKnockdown ()
Definition at line 7868 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updateLastSuccessfulCombatAction ()
Definition at line 7856 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updateLocomotion ()
Definition at line 7348 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updatePostureDownRecovery ()
Definition at line 7880 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updatePostureUpRecovery ()
Definition at line 7884 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updateSpeedAndAccelerationMods ()
Definition at line 8380 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updateTimeOfDeath ()
Definition at line 7840 of file CreatureObject.cpp.
Referenced by invokeMethod().
void CreatureObjectAdapter::updateToDatabaseAllObjects (bool startTask)
Definition at line 7548 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::verifyBankCredits (int credits)
Definition at line 7576 of file CreatureObject.cpp.
Referenced by invokeMethod().
bool CreatureObjectAdapter::verifyCashCredits (int credits)
Definition at line 7572 of file CreatureObject.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/CreatureObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/CreatureObject.cpp