Core3: server::zone::objects::area::areashapes::RingAreaShape Class Reference
server::zone::objects::area::areashapes::RingAreaShape Class Reference
#include <RingAreaShape.h>
Public Member Functions
RingAreaShape ()
void setInnerRadius (float r)
void setOuterRadius (float r)
float getInnerRadius ()
float getInnerRadius2 ()
float getOuterRadius ()
float getOuterRadius2 ()
bool containsPoint (float x, float y)
bool containsPoint (const Vector3 &point)
Vector3 getRandomPosition ()
Vector3 getRandomPosition (const Vector3 &origin, float minDistance, float maxDistance)
bool isRingAreaShape ()
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::area::areashapes::AreaShape
AreaShape ()
void setAreaCenter (float x, float y)
Vector3 getAreaCenter ()
bool containsPoint (float x, float y)
float getRadius ()
Vector3 getRandomPosition ()
Vector3 getRandomPosition (const Vector3 &origin, float minDistance, float maxDistance)
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
RingAreaShape (DummyConstructorParameter *param)
virtual ~RingAreaShape ()
Protected Member Functions inherited from server::zone::objects::area::areashapes::AreaShape
AreaShape (DummyConstructorParameter *param)
virtual ~AreaShape ()
Friends
class RingAreaShapeHelper
Detailed Description
Definition at line 38 of file RingAreaShape.h.
Constructor & Destructor Documentation
RingAreaShape::RingAreaShape ()
Constructor
Definition at line 15 of file RingAreaShape.cpp.
References server::zone::objects::area::areashapes::RingAreaShapeImplementation::_setStub().
RingAreaShape::RingAreaShape (DummyConstructorParameter * param) protected
Definition at line 22 of file RingAreaShape.cpp.
RingAreaShape::~RingAreaShape () protected virtual
Definition at line 26 of file RingAreaShape.cpp.
Member Function Documentation
DistributedObjectServant * RingAreaShape::_getImplementation ()
Definition at line 219 of file RingAreaShape.cpp.
Referenced by containsPoint(), getArea(), getInnerRadius(), getInnerRadius2(), getOuterRadius(), getOuterRadius2(), getRandomPosition(), intersectsWith(), isCircularAreaShape(), isRectangularAreaShape(), isRingAreaShape(), setInnerRadius(), and setOuterRadius().
DistributedObjectServant * RingAreaShape::_getImplementationForRead ()
Definition at line 225 of file RingAreaShape.cpp.
void RingAreaShape::_setImplementation (DistributedObjectServant * servant)
Definition at line 229 of file RingAreaShape.cpp.
bool RingAreaShape::containsPoint (float x, float y)
Check if the coordinate is within the area shape.
Parameters
x the x coordinate.
y the y coordinate.
Returns
true if the coordinate is within the area shape.
Definition at line 111 of file RingAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::containsPoint(), and RPC_CONTAINSPOINT__FLOAT_FLOAT_.
bool RingAreaShape::containsPoint (const Vector3 & point) virtual
Check if the coordinate is within the area shape.
Parameters
point the point to check if it is within the area shape.
Returns
true if the coordinate is within the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShape.
Definition at line 126 of file RingAreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::RingAreaShapeImplementation::containsPoint().
float RingAreaShape::getArea ()
Get the area of the areaShape.
Returns
the area of the area shape.
Definition at line 206 of file RingAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::getArea(), and RPC_GETAREA__.
float RingAreaShape::getInnerRadius ()
Get the inner radius of the ring.
Returns
inner radius of the ring
Definition at line 59 of file RingAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::getInnerRadius(), and RPC_GETINNERRADIUS__.
float RingAreaShape::getInnerRadius2 ()
Get the inner squared radius of the ring.
Returns
inner squared radius of the ring
Definition at line 72 of file RingAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::getInnerRadius2(), and RPC_GETINNERRADIUS2__.
Referenced by server::zone::objects::area::areashapes::RingAreaShapeImplementation::intersectsWithRing().
float RingAreaShape::getOuterRadius ()
Get the outer radius of the ring.
Returns
outer radius of the ring
Definition at line 85 of file RingAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::getOuterRadius(), and RPC_GETOUTERRADIUS__.
float RingAreaShape::getOuterRadius2 ()
Get the outer squared radius of the ring.
Returns
outer squared radius of the ring
Definition at line 98 of file RingAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::getOuterRadius2(), and RPC_GETOUTERRADIUS2__.
Referenced by server::zone::objects::area::areashapes::RingAreaShapeImplementation::intersectsWithRing().
Vector3 RingAreaShape::getRandomPosition ()
Generate a random position within the area.
Returns
a random position within the area.
Definition at line 135 of file RingAreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::RingAreaShapeImplementation::getRandomPosition().
Vector3 RingAreaShape::getRandomPosition (const Vector3 & origin, float minDistance, float maxDistance)
Generate a random position within the area with the supplied origin and radius as limits.
Parameters
origin the origin coordinate to generate the random position from.
minDistance the minimum distance from the origin.
maxDistance the maximum distance from the origin.
Returns
a random position within the area.
Definition at line 144 of file RingAreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::RingAreaShapeImplementation::getRandomPosition().
bool RingAreaShape::intersectsWith (AreaShape * areaShape)
Check if this area shape intersects with the supplied area shape.
Parameters
areaShape the area shape to check for intersections with.s
Returns
true if the area shapes intersects each other.
Definition at line 192 of file RingAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::intersectsWith(), and RPC_INTERSECTSWITH__AREASHAPE_.
bool RingAreaShape::isCircularAreaShape ()
Check if this is a circular area shape.
Returns
true if it is a circular area shape.
Definition at line 166 of file RingAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::isCircularAreaShape(), and RPC_ISCIRCULARAREASHAPE__.
bool RingAreaShape::isRectangularAreaShape ()
Check if this is a rectangular area shape.
Returns
true if it is a rectangular area shape.
Definition at line 179 of file RingAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::isRectangularAreaShape(), and RPC_ISRECTANGULARAREASHAPE__.
bool RingAreaShape::isRingAreaShape ()
Check if this is a ring area shape.
Returns
true if it is a ring area shape.
Definition at line 153 of file RingAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::isRingAreaShape(), and RPC_ISRINGAREASHAPE__.
void RingAreaShape::setInnerRadius (float r)
Set the inner radius of the ring.
Parameters
r the new inner radius of the ring.
Definition at line 31 of file RingAreaShape.cpp.
References _getImplementation(), RPC_SETINNERRADIUS__FLOAT_, and server::zone::objects::area::areashapes::RingAreaShapeImplementation::setInnerRadius().
void RingAreaShape::setOuterRadius (float r)
Set the outer radius of the ring.
Parameters
r the new outer radius of the ring.
Definition at line 45 of file RingAreaShape.cpp.
References _getImplementation(), RPC_SETOUTERRADIUS__FLOAT_, and server::zone::objects::area::areashapes::RingAreaShapeImplementation::setOuterRadius().
Friends And Related Function Documentation
friend class RingAreaShapeHelper friend
Definition at line 150 of file RingAreaShape.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RingAreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RingAreaShape.cpp