Core3: server::zone::objects::installation::TurretObserver Class Reference
server::zone::objects::installation::TurretObserver Class Reference
#include <TurretObserver.h>
Public Member Functions
TurretObserver ()
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
TurretObserver (DummyConstructorParameter *param)
virtual ~TurretObserver ()
Friends
class TurretObserverHelper
Detailed Description
Definition at line 55 of file TurretObserver.h.
Constructor & Destructor Documentation
TurretObserver::TurretObserver ()
Definition at line 17 of file TurretObserver.cpp.
References server::zone::objects::installation::TurretObserverImplementation::_setStub().
TurretObserver::TurretObserver (DummyConstructorParameter * param) protected
Definition at line 24 of file TurretObserver.cpp.
TurretObserver::~TurretObserver () protected virtual
Definition at line 28 of file TurretObserver.cpp.
Member Function Documentation
DistributedObjectServant * TurretObserver::_getImplementation ()
Definition at line 50 of file TurretObserver.cpp.
Referenced by notifyObserverEvent().
DistributedObjectServant * TurretObserver::_getImplementationForRead ()
Definition at line 56 of file TurretObserver.cpp.
void TurretObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 60 of file TurretObserver.cpp.
int TurretObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 33 of file TurretObserver.cpp.
References _getImplementation(), server::zone::objects::installation::TurretObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class TurretObserverHelper friend
Definition at line 71 of file TurretObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/TurretObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/TurretObserver.cpp