Core3: server::zone::objects::tangible::wearables::PsgArmorObjectImplementation Class Reference
server::zone::objects::tangible::wearables::PsgArmorObjectImplementation Class Reference
#include <PsgArmorObject.h>
Public Member Functions
PsgArmorObjectImplementation ()
PsgArmorObjectImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
bool isPsgArmorObject ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void updateCraftingValues (CraftingValues *schematic, bool firstUpdate)
operator const PsgArmorObject * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::tangible::wearables::ArmorObjectImplementation
ArmorObjectImplementation ()
ArmorObjectImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadTemplateData (SharedObjectTemplate *templateData)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
bool isSpecial (int type)
bool isVulnerable (int type)
bool isArmorObject ()
void setRating (int rate)
int getRating ()
float getKinetic ()
void setKinetic (float value)
float getEnergy ()
void setEnergy (float value)
float getElectricity ()
void setElectricity (float value)
float getStun ()
void setStun (float value)
float getBlast ()
void setBlast (float value)
float getHeat ()
void setHeat (float value)
float getCold ()
void setCold (float value)
float getAcid ()
void setAcid (float value)
float getLightSaber ()
void setLightSaber (float value)
int getHealthEncumbrance ()
void setHealthEncumbrance (int encumber)
int getActionEncumbrance ()
void setActionEncumbrance (int encumber)
int getMindEncumbrance ()
void setMindEncumbrance (int encumber)
void setEffectivenessSlice (float value)
void setEncumbranceSlice (float value)
byte getHitLocation ()
void setHitLocation (byte h)
operator const ArmorObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::tangible::wearables::WearableObjectImplementation
WearableObjectImplementation ()
WearableObjectImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void updateCraftingValues (CraftingValues *values, bool initialUpdate)
void applyAttachment (CreatureObject *player, Attachment *attachment)
virtual void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
virtual void removeSkillModsFrom (CreatureObject *creature)
bool isWearableObject ()
bool isEquipped ()
int getMaxSockets ()
int socketsUsed ()
int socketsLeft ()
String repairAttempt (int repairChance)
VectorMap< String, int > * getWearableSkillMods ()
virtual void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
void setMaxSockets (int maxSockets)
operator const WearableObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
TangibleObjectImplementation ()
TangibleObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
virtual void addTemplateSkillMods (TangibleObject *targetObject)
virtual void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
virtual void removeAllSkillModsOfType (const int skillType, bool notifyClient=true)
virtual void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void sendBaselinesTo (SceneObject *player)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
virtual void setDefender (SceneObject *defender)
virtual void addDefender (SceneObject *defender)
virtual void removeDefender (SceneObject *defender)
virtual void removeDefenders ()
virtual void setCombatState ()
virtual void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
virtual void clearCombatState (bool clearDefenders=true)
bool hasDefender (SceneObject *defender)
virtual bool isAttackableBy (CreatureObject *object)
virtual bool isAggressiveTo (CreatureObject *object)
virtual bool isHealableBy (CreatureObject *object)
virtual void sendPvpStatusTo (CreatureObject *player)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
virtual int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
virtual int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
virtual bool isKiller ()
virtual bool isTicketCollector ()
virtual bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
virtual int getUseCount ()
virtual int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
virtual bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
virtual String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
virtual int getJunkDealerNeeded ()
void setJunkValue (int jValue)
virtual int getJunkValue ()
void setSerialNumber (const String &serial)
virtual void setLevel (int lev)
virtual String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
bool isBroken ()
virtual float getHitChance ()
void broadcastPvpStatusBitmask ()
operator const TangibleObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendTo (SceneObject *player, bool doClose)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
virtual void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableContainerObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
virtual void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< PsgArmorObject * > _this
Public Attributes inherited from server::zone::objects::tangible::wearables::ArmorObjectImplementation
WeakReference< ArmorObject * > _this
Public Attributes inherited from server::zone::objects::tangible::wearables::WearableObjectImplementation
WeakReference< WearableObject * > _this
Public Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
WeakReference< TangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Protected Member Functions
virtual ~PsgArmorObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::wearables::ArmorObjectImplementation
virtual ~ArmorObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::wearables::WearableObjectImplementation
virtual ~WearableObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
float getConditionReduction (float value)
virtual ~TangibleObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class PsgArmorObject
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::tangible::wearables::ArmorObjectImplementation
static const int LIGHT = 0x1
static const int MEDIUM = 0x2
static const int HEAVY = 0x3
Protected Attributes inherited from server::zone::objects::tangible::wearables::ArmorObjectImplementation
int healthEncumbrance
int actionEncumbrance
int mindEncumbrance
int rating
float kinetic
float energy
float electricity
float stun
float blast
float heat
float cold
float acid
float lightSaber
int specialResists
int vulnerabilites
byte hitLocation
float baseProtection
float specialProtection
float effectivenessSlice
float encumbranceSlice
Detailed Description
Definition at line 82 of file PsgArmorObject.h.
Constructor & Destructor Documentation
PsgArmorObjectImplementation::PsgArmorObjectImplementation ()
Definition at line 207 of file PsgArmorObject.cpp.
References _initializeImplementation().
PsgArmorObjectImplementation::PsgArmorObjectImplementation (DummyConstructorParameter * param)
Definition at line 93 of file PsgArmorObject.cpp.
References _initializeImplementation().
PsgArmorObjectImplementation::~PsgArmorObjectImplementation () protected virtual
Definition at line 98 of file PsgArmorObject.cpp.
Member Function Documentation
DistributedObjectStub * PsgArmorObjectImplementation::_getStub ()
Definition at line 118 of file PsgArmorObject.cpp.
References _this.
void PsgArmorObjectImplementation::_initializeImplementation () protected
Definition at line 105 of file PsgArmorObject.cpp.
References _serializationHelperMethod(), and _this.
Referenced by PsgArmorObjectImplementation().
void PsgArmorObjectImplementation::_serializationHelperMethod () protected
Definition at line 154 of file PsgArmorObject.cpp.
References server::zone::objects::tangible::wearables::ArmorObjectImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void PsgArmorObjectImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 113 of file PsgArmorObject.cpp.
References server::zone::objects::tangible::wearables::ArmorObjectImplementation::_setStub(), and _this.
Referenced by server::zone::objects::tangible::wearables::PsgArmorObject::PsgArmorObject().
void PsgArmorObjectImplementation::fillAttributeList (AttributeListMessage * msg, CreatureObject * object) virtual
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Reimplemented from server::zone::objects::tangible::wearables::ArmorObjectImplementation.
Definition at line 20 of file PsgArmorObjectImplementation.cpp.
Referenced by server::zone::objects::tangible::wearables::PsgArmorObject::fillAttributeList().
void PsgArmorObjectImplementation::finalize () protected
Definition at line 102 of file PsgArmorObject.cpp.
void PsgArmorObjectImplementation::initializeTransientMembers ()
Definition at line 14 of file PsgArmorObjectImplementation.cpp.
References server::zone::objects::tangible::wearables::WearableObjectImplementation::initializeTransientMembers(), and server::zone::objects::scene::SceneObjectImplementation::setLoggingName().
Referenced by server::zone::objects::tangible::wearables::PsgArmorObject::initializeTransientMembers(), and readObject().
bool PsgArmorObjectImplementation::isPsgArmorObject ()
Definition at line 213 of file PsgArmorObject.cpp.
Referenced by server::zone::objects::tangible::wearables::PsgArmorObject::isPsgArmorObject().
void PsgArmorObjectImplementation::lock (bool doLock = true) protected
Definition at line 126 of file PsgArmorObject.cpp.
References _this.
void PsgArmorObjectImplementation::lock (ManagedObject * obj) protected
Definition at line 130 of file PsgArmorObject.cpp.
References _this.
PsgArmorObjectImplementation::operator const PsgArmorObject * ()
Definition at line 122 of file PsgArmorObject.cpp.
void PsgArmorObjectImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::tangible::wearables::ArmorObjectImplementation.
Definition at line 161 of file PsgArmorObject.cpp.
References initializeTransientMembers(), and readObjectMember().
bool PsgArmorObjectImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 180 of file PsgArmorObject.cpp.
References server::zone::objects::tangible::wearables::ArmorObjectImplementation::readObjectMember().
Referenced by readObject().
void PsgArmorObjectImplementation::rlock (bool doLock = true) protected
Definition at line 134 of file PsgArmorObject.cpp.
References _this.
void PsgArmorObjectImplementation::runlock (bool doLock = true) protected
Definition at line 150 of file PsgArmorObject.cpp.
References _this.
void PsgArmorObjectImplementation::unlock (bool doLock = true) protected
Definition at line 146 of file PsgArmorObject.cpp.
References _this.
void PsgArmorObjectImplementation::updateCraftingValues (CraftingValues * schematic, bool firstUpdate) virtual
Reimplemented from server::zone::objects::tangible::wearables::ArmorObjectImplementation.
Definition at line 24 of file PsgArmorObjectImplementation.cpp.
Referenced by server::zone::objects::tangible::wearables::PsgArmorObject::updateCraftingValues().
void PsgArmorObjectImplementation::wlock (bool doLock = true) protected
Definition at line 138 of file PsgArmorObject.cpp.
References _this.
void PsgArmorObjectImplementation::wlock (ManagedObject * obj) protected
Definition at line 142 of file PsgArmorObject.cpp.
References _this.
void PsgArmorObjectImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::tangible::wearables::ArmorObjectImplementation.
Definition at line 190 of file PsgArmorObject.cpp.
References writeObjectMembers().
int PsgArmorObjectImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 197 of file PsgArmorObject.cpp.
References server::zone::objects::tangible::wearables::ArmorObjectImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class PsgArmorObject friend
Definition at line 138 of file PsgArmorObject.h.
Member Data Documentation
WeakReference<PsgArmorObject*> server::zone::objects::tangible::wearables::PsgArmorObjectImplementation::_this
Definition at line 104 of file PsgArmorObject.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/wearables/PsgArmorObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/wearables/PsgArmorObject.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/wearables/PsgArmorObjectImplementation.cpp