Core3: server::zone::objects::player::sessions::EntertainingSessionImplementation Class Reference
server::zone::objects::player::sessions::EntertainingSessionImplementation Class Reference
#include <EntertainingSession.h>
Public Member Functions
EntertainingSessionImplementation (CreatureObject *ent)
EntertainingSessionImplementation (DummyConstructorParameter *param)
void doEntertainerPatronEffects ()
void doPerformanceAction ()
void addEntertainerFlourishBuff ()
void startDancing (const String &dance, const String &animation)
void startPlayingMusic (const String &song, const String &instrumentAnimation, int instrid)
void startEntertaining ()
void finalize ()
void healWounds (CreatureObject *creature, float woundHeal, float shockHeal)
bool isInEntertainingBuilding (CreatureObject *creature)
void doFlourish (int flourishNumber)
bool canHealBattleFatigue ()
bool canGiveEntertainBuff ()
void addFlourishXp (int xp)
void addHealingXp (int xp)
void addHealingXpGroup (int xp)
int initializeSession ()
int cancelSession ()
int clearSession ()
void stopPlayingMusic ()
void stopDancing ()
void activateAction ()
void startTickTask ()
void addEntertainerBuffDuration (CreatureObject *creature, int performanceType, float duration)
void addEntertainerBuffStrength (CreatureObject *creature, int performanceType, float strength)
void setEntertainerBuffDuration (CreatureObject *creature, int performanceType, float duration)
void setEntertainerBuffStrength (CreatureObject *creature, int performanceType, float strength)
int getEntertainerBuffStrength (CreatureObject *creature, int performanceType)
int getEntertainerBuffDuration (CreatureObject *creature, int performanceType)
int getEntertainerBuffStartTime (CreatureObject *creature, int performanceType)
void sendEntertainingUpdate (CreatureObject *creature, float entval, const String &performance, unsigned int perfcntr, int instrid)
void sendEntertainmentUpdate (CreatureObject *creature, unsigned long long entid, const String &mood, bool updateEntValue=false)
void activateEntertainerBuff (CreatureObject *creature, int performanceType)
Instrument * getInstrument (CreatureObject *creature)
String getPerformanceName ()
void addWatcher (CreatureObject *creature)
void addListener (CreatureObject *listener)
bool isDancing ()
bool isPlayingMusic ()
bool isAcceptingBandFlourishes ()
void setAcceptingBandFlourishes (bool val)
void removeWatcher (CreatureObject *creature)
void removeListener (CreatureObject *creature)
void setPerformanceName (const String &name)
void setDancing (bool val)
void setTargetInstrument (bool var)
void updateEntertainerMissionStatus (bool entertaining, const int missionType)
bool isInDenyServiceList (CreatureObject *target)
void addToDenyServiceList (CreatureObject *target)
void removeFromDenyServiceList (CreatureObject *target)
void increaseEntertainerBuff (CreatureObject *patron)
void awardEntertainerExperience ()
operator const EntertainingSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< EntertainingSession * > _this
Protected Member Functions
virtual ~EntertainingSessionImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > entertainer
ManagedReference
< EntertainingObserver * > observer
EntertainingDataMap watchers
EntertainingDataMap listeners
SortedVector< ManagedReference
< CreatureObject * > > denyServiceList
Reference
< EntertainingSessionTask * > tickTask
Time nextTick
String performanceName
bool dancing
bool playingMusic
int flourishXp
int healingXp
int flourishCount
bool acceptingBandFlourishes
bool targetInstrument
ManagedReference< Instrument * > externalInstrument
Friends
class EntertainingSession
Detailed Description
Definition at line 255 of file EntertainingSession.h.
Constructor & Destructor Documentation
EntertainingSessionImplementation::EntertainingSessionImplementation (CreatureObject * ent)
Definition at line 1032 of file EntertainingSession.cpp.
References _initializeImplementation(), acceptingBandFlourishes, dancing, entertainer, flourishCount, flourishXp, healingXp, listeners, observer, playingMusic, targetInstrument, and watchers.
EntertainingSessionImplementation::EntertainingSessionImplementation (DummyConstructorParameter * param)
Definition at line 740 of file EntertainingSession.cpp.
References _initializeImplementation().
EntertainingSessionImplementation::~EntertainingSessionImplementation () protected virtual
Definition at line 745 of file EntertainingSession.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * EntertainingSessionImplementation::_getStub ()
Definition at line 763 of file EntertainingSession.cpp.
References _this.
void EntertainingSessionImplementation::_initializeImplementation () protected
Definition at line 750 of file EntertainingSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by EntertainingSessionImplementation().
void EntertainingSessionImplementation::_serializationHelperMethod () protected
Definition at line 799 of file EntertainingSession.cpp.
Referenced by _initializeImplementation().
void EntertainingSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 758 of file EntertainingSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::EntertainingSession::EntertainingSession().
void EntertainingSessionImplementation::activateAction ()
Definition at line 212 of file EntertainingSessionImplementation.cpp.
References awardEntertainerExperience(), doEntertainerPatronEffects(), doPerformanceAction(), entertainer, isDancing(), isPlayingMusic(), and startTickTask().
Referenced by server::zone::objects::player::sessions::EntertainingSession::activateAction().
void EntertainingSessionImplementation::activateEntertainerBuff (CreatureObject * creature, int performanceType)
Definition at line 809 of file EntertainingSessionImplementation.cpp.
References server::zone::objects::creature::CreatureObject::addBuff(), canGiveEntertainBuff(), PerformanceType::DANCE, PerformanceBuffType::DANCE_MIND, entertainer, server::zone::objects::creature::CreatureObject::getBuff(), getEntertainerBuffDuration(), getEntertainerBuffStartTime(), getEntertainerBuffStrength(), server::zone::objects::creature::CreatureObject::getGroupID(), server::zone::objects::scene::SceneObject::getObjectID(), isInDenyServiceList(), PerformanceType::MUSIC, PerformanceBuffType::MUSIC_FOCUS, PerformanceBuffType::MUSIC_WILLPOWER, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::objects::player::sessions::EntertainingSession::activateEntertainerBuff().
void EntertainingSessionImplementation::addEntertainerBuffDuration (CreatureObject * creature, int performanceType, float duration)
Definition at line 609 of file EntertainingSessionImplementation.cpp.
References getEntertainerBuffDuration(), and setEntertainerBuffDuration().
Referenced by server::zone::objects::player::sessions::EntertainingSession::addEntertainerBuffDuration(), and increaseEntertainerBuff().
void EntertainingSessionImplementation::addEntertainerBuffStrength (CreatureObject * creature, int performanceType, float strength)
Definition at line 620 of file EntertainingSessionImplementation.cpp.
References dancing, entertainer, getEntertainerBuffStrength(), healingXp, playingMusic, and setEntertainerBuffStrength().
Referenced by server::zone::objects::player::sessions::EntertainingSession::addEntertainerBuffStrength(), and increaseEntertainerBuff().
void EntertainingSessionImplementation::addEntertainerFlourishBuff ()
Definition at line 515 of file EntertainingSessionImplementation.cpp.
References dancing, increaseEntertainerBuff(), listeners, playingMusic, and watchers.
Referenced by server::zone::objects::player::sessions::EntertainingSession::addEntertainerFlourishBuff(), and doFlourish().
void EntertainingSessionImplementation::addFlourishXp (int xp)
Definition at line 1065 of file EntertainingSession.cpp.
References flourishXp.
Referenced by server::zone::objects::player::sessions::EntertainingSession::addFlourishXp().
void EntertainingSessionImplementation::addHealingXp (int xp)
Definition at line 1070 of file EntertainingSession.cpp.
References healingXp.
Referenced by server::zone::objects::player::sessions::EntertainingSession::addHealingXp(), and healWounds().
void EntertainingSessionImplementation::addHealingXpGroup (int xp)
Definition at line 186 of file EntertainingSessionImplementation.cpp.
References entertainer.
Referenced by server::zone::objects::player::sessions::EntertainingSession::addHealingXpGroup(), and healWounds().
void EntertainingSessionImplementation::addListener (CreatureObject * listener)
Definition at line 662 of file EntertainingSessionImplementation.cpp.
References listeners.
Referenced by server::zone::objects::player::sessions::EntertainingSession::addListener().
void EntertainingSessionImplementation::addToDenyServiceList (CreatureObject * target)
Definition at line 1149 of file EntertainingSession.cpp.
References denyServiceList.
Referenced by server::zone::objects::player::sessions::EntertainingSession::addToDenyServiceList().
void EntertainingSessionImplementation::addWatcher (CreatureObject * creature)
Definition at line 653 of file EntertainingSessionImplementation.cpp.
References watchers.
Referenced by server::zone::objects::player::sessions::EntertainingSession::addWatcher().
void EntertainingSessionImplementation::awardEntertainerExperience ()
Definition at line 966 of file EntertainingSessionImplementation.cpp.
References entertainer, flourishCount, flourishXp, server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::group::GroupObject::getGroupSize(), healingXp, isDancing(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and isPlayingMusic().
Referenced by activateAction(), and server::zone::objects::player::sessions::EntertainingSession::awardEntertainerExperience().
int EntertainingSessionImplementation::cancelSession ()
Definition at line 1080 of file EntertainingSession.cpp.
References stopDancing(), and stopPlayingMusic().
Referenced by server::zone::objects::player::sessions::EntertainingSession::cancelSession(), doEntertainerPatronEffects(), doFlourish(), doPerformanceAction(), and increaseEntertainerBuff().
bool EntertainingSessionImplementation::canGiveEntertainBuff ()
Definition at line 505 of file EntertainingSessionImplementation.cpp.
References entertainer.
Referenced by activateEntertainerBuff(), server::zone::objects::player::sessions::EntertainingSession::canGiveEntertainBuff(), healWounds(), and increaseEntertainerBuff().
bool EntertainingSessionImplementation::canHealBattleFatigue ()
Definition at line 496 of file EntertainingSessionImplementation.cpp.
References entertainer.
Referenced by server::zone::objects::player::sessions::EntertainingSession::canHealBattleFatigue(), and healWounds().
int EntertainingSessionImplementation::clearSession ()
Definition at line 1089 of file EntertainingSession.cpp.
Referenced by server::zone::objects::player::sessions::EntertainingSession::clearSession().
void EntertainingSessionImplementation::doEntertainerPatronEffects ()
Definition at line 28 of file EntertainingSessionImplementation.cpp.
References cancelSession(), dancing, entertainer, flourishCount, PerformanceManager::getDance(), Performance::getHealMindWound(), Performance::getHealShockWound(), getInstrument(), server::zone::managers::skill::SkillManager::getPerformanceManager(), PerformanceManager::getSong(), healWounds(), increaseEntertainerBuff(), listeners, performanceName, playingMusic, sendEntertainmentUpdate(), and watchers.
Referenced by activateAction(), and server::zone::objects::player::sessions::EntertainingSession::doEntertainerPatronEffects().
void EntertainingSessionImplementation::doFlourish (int flourishNumber)
Definition at line 538 of file EntertainingSessionImplementation.cpp.
References CreatureAttribute::ACTION, addEntertainerFlourishBuff(), cancelSession(), dancing, entertainer, flourishCount, flourishXp, Performance::getActionPointsPerLoop(), Performance::getBaseXp(), PerformanceManager::getDance(), Performance::getFlourishXpMod(), getInstrument(), PerformanceManager::getSong(), performanceName, playingMusic, and CreatureAttribute::QUICKNESS.
Referenced by server::zone::objects::player::sessions::EntertainingSession::doFlourish().
void EntertainingSessionImplementation::doPerformanceAction ()
Definition at line 244 of file EntertainingSessionImplementation.cpp.
References CreatureAttribute::ACTION, cancelSession(), entertainer, Performance::getActionPointsPerLoop(), PerformanceManager::getDance(), getInstrument(), PerformanceManager::getSong(), isDancing(), isPlayingMusic(), performanceName, CreatureAttribute::QUICKNESS, stopDancing(), and stopPlayingMusic().
Referenced by activateAction(), and server::zone::objects::player::sessions::EntertainingSession::doPerformanceAction().
void EntertainingSessionImplementation::finalize ()
Definition at line 1062 of file EntertainingSession.cpp.
Referenced by ~EntertainingSessionImplementation().
int EntertainingSessionImplementation::getEntertainerBuffDuration (CreatureObject * creature, int performanceType)
Definition at line 694 of file EntertainingSessionImplementation.cpp.
References PerformanceType::DANCE, EntertainingData::getDuration(), listeners, PerformanceType::MUSIC, and watchers.
Referenced by activateEntertainerBuff(), addEntertainerBuffDuration(), and server::zone::objects::player::sessions::EntertainingSession::getEntertainerBuffDuration().
int EntertainingSessionImplementation::getEntertainerBuffStartTime (CreatureObject * creature, int performanceType)
Definition at line 739 of file EntertainingSessionImplementation.cpp.
References PerformanceType::DANCE, EntertainingData::getTimeStarted(), listeners, PerformanceType::MUSIC, and watchers.
Referenced by activateEntertainerBuff(), and server::zone::objects::player::sessions::EntertainingSession::getEntertainerBuffStartTime().
int EntertainingSessionImplementation::getEntertainerBuffStrength (CreatureObject * creature, int performanceType)
Definition at line 717 of file EntertainingSessionImplementation.cpp.
References PerformanceType::DANCE, EntertainingData::getStrength(), listeners, PerformanceType::MUSIC, and watchers.
Referenced by activateEntertainerBuff(), addEntertainerBuffStrength(), and server::zone::objects::player::sessions::EntertainingSession::getEntertainerBuffStrength().
Instrument * EntertainingSessionImplementation::getInstrument (CreatureObject * creature)
Definition at line 294 of file EntertainingSessionImplementation.cpp.
References externalInstrument, server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::creature::CreatureObject::getTargetID(), server::zone::objects::scene::SceneObject::getZoneServer(), and targetInstrument.
Referenced by doEntertainerPatronEffects(), doFlourish(), doPerformanceAction(), server::zone::objects::player::sessions::EntertainingSession::getInstrument(), increaseEntertainerBuff(), and startPlayingMusic().
String EntertainingSessionImplementation::getPerformanceName ()
Definition at line 1094 of file EntertainingSession.cpp.
References performanceName.
Referenced by server::zone::objects::player::sessions::EntertainingSession::getPerformanceName().
void EntertainingSessionImplementation::healWounds (CreatureObject * creature, float woundHeal, float shockHeal)
Definition at line 150 of file EntertainingSessionImplementation.cpp.
References addHealingXp(), addHealingXpGroup(), server::zone::objects::creature::CreatureObject::addShockWounds(), server::zone::objects::creature::CreatureObject::addWounds(), canGiveEntertainBuff(), canHealBattleFatigue(), entertainer, CreatureAttribute::FOCUS, server::zone::objects::creature::CreatureObject::getShockWounds(), server::zone::objects::creature::CreatureObject::getWounds(), isInDenyServiceList(), CreatureAttribute::MIND, and CreatureAttribute::WILLPOWER.
Referenced by doEntertainerPatronEffects(), and server::zone::objects::player::sessions::EntertainingSession::healWounds().
void EntertainingSessionImplementation::increaseEntertainerBuff (CreatureObject * patron)
Definition at line 921 of file EntertainingSessionImplementation.cpp.
References addEntertainerBuffDuration(), addEntertainerBuffStrength(), cancelSession(), canGiveEntertainBuff(), dancing, entertainer, PerformanceManager::getDance(), server::zone::objects::creature::CreatureObject::getGroupID(), Performance::getHealShockWound(), getInstrument(), server::zone::objects::scene::SceneObject::getObjectID(), PerformanceManager::getSong(), Performance::getType(), isInDenyServiceList(), performanceName, and playingMusic.
Referenced by addEntertainerFlourishBuff(), doEntertainerPatronEffects(), and server::zone::objects::player::sessions::EntertainingSession::increaseEntertainerBuff().
int EntertainingSessionImplementation::initializeSession ()
Definition at line 1075 of file EntertainingSession.cpp.
Referenced by server::zone::objects::player::sessions::EntertainingSession::initializeSession().
bool EntertainingSessionImplementation::isAcceptingBandFlourishes ()
Definition at line 1109 of file EntertainingSession.cpp.
References acceptingBandFlourishes.
Referenced by server::zone::objects::player::sessions::EntertainingSession::isAcceptingBandFlourishes().
bool EntertainingSessionImplementation::isDancing ()
Definition at line 1099 of file EntertainingSession.cpp.
References dancing.
Referenced by activateAction(), awardEntertainerExperience(), doPerformanceAction(), and server::zone::objects::player::sessions::EntertainingSession::isDancing().
bool EntertainingSessionImplementation::isInDenyServiceList (CreatureObject * target)
Definition at line 1144 of file EntertainingSession.cpp.
References denyServiceList.
Referenced by activateEntertainerBuff(), healWounds(), increaseEntertainerBuff(), and server::zone::objects::player::sessions::EntertainingSession::isInDenyServiceList().
bool EntertainingSessionImplementation::isInEntertainingBuilding (CreatureObject * creature)
Definition at line 133 of file EntertainingSessionImplementation.cpp.
References server::zone::objects::scene::SceneObject::getRootParent(), SceneObjectType::HOTELBUILDING, SceneObjectType::RECREATIONBUILDING, and SceneObjectType::THEATERBUILDING.
Referenced by server::zone::objects::player::sessions::EntertainingSession::isInEntertainingBuilding().
bool EntertainingSessionImplementation::isPlayingMusic ()
Definition at line 1104 of file EntertainingSession.cpp.
References playingMusic.
Referenced by activateAction(), awardEntertainerExperience(), doPerformanceAction(), and server::zone::objects::player::sessions::EntertainingSession::isPlayingMusic().
void EntertainingSessionImplementation::lock (bool doLock = true) protected
Definition at line 771 of file EntertainingSession.cpp.
References _this.
void EntertainingSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 775 of file EntertainingSession.cpp.
References _this.
EntertainingSessionImplementation::operator const EntertainingSession * ()
Definition at line 767 of file EntertainingSession.cpp.
void EntertainingSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 806 of file EntertainingSession.cpp.
References readObjectMember().
bool EntertainingSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 825 of file EntertainingSession.cpp.
References acceptingBandFlourishes, dancing, denyServiceList, entertainer, externalInstrument, flourishCount, flourishXp, healingXp, listeners, nextTick, observer, performanceName, playingMusic, targetInstrument, and watchers.
Referenced by readObject().
void EntertainingSessionImplementation::removeFromDenyServiceList (CreatureObject * target)
Definition at line 1154 of file EntertainingSession.cpp.
References denyServiceList.
Referenced by server::zone::objects::player::sessions::EntertainingSession::removeFromDenyServiceList().
void EntertainingSessionImplementation::removeListener (CreatureObject * creature)
Definition at line 1124 of file EntertainingSession.cpp.
References listeners.
Referenced by server::zone::objects::player::sessions::EntertainingSession::removeListener().
void EntertainingSessionImplementation::removeWatcher (CreatureObject * creature)
Definition at line 1119 of file EntertainingSession.cpp.
References watchers.
Referenced by server::zone::objects::player::sessions::EntertainingSession::removeWatcher().
void EntertainingSessionImplementation::rlock (bool doLock = true) protected
Definition at line 779 of file EntertainingSession.cpp.
References _this.
void EntertainingSessionImplementation::runlock (bool doLock = true) protected
Definition at line 795 of file EntertainingSession.cpp.
References _this.
void EntertainingSessionImplementation::sendEntertainingUpdate (CreatureObject * creature, float entval, const String & performance, unsigned int perfcntr, int instrid)
Definition at line 793 of file EntertainingSessionImplementation.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), DeltaMessage::close(), server::zone::objects::creature::CreatureObject::setInstrumentID(), server::zone::objects::creature::CreatureObject::setPerformanceAnimation(), server::zone::objects::creature::CreatureObject::setPerformanceCounter(), CreatureObjectDeltaMessage6::updateInstrumentID(), CreatureObjectDeltaMessage6::updatePerformanceAnimation(), and CreatureObjectDeltaMessage6::updatePerformanceCounter().
Referenced by server::zone::objects::player::sessions::EntertainingSession::sendEntertainingUpdate(), startDancing(), startPlayingMusic(), stopDancing(), and stopPlayingMusic().
void EntertainingSessionImplementation::sendEntertainmentUpdate (CreatureObject * creature, unsigned long long entid, const String & mood, bool updateEntValue = false)
Definition at line 782 of file EntertainingSessionImplementation.cpp.
References Races::getMoodStr(), server::zone::objects::creature::CreatureObject::setListenToID(), and server::zone::objects::creature::CreatureObject::setMoodString().
Referenced by doEntertainerPatronEffects(), server::zone::objects::player::sessions::EntertainingSession::sendEntertainmentUpdate(), stopDancing(), and stopPlayingMusic().
void EntertainingSessionImplementation::setAcceptingBandFlourishes (bool val)
Definition at line 1114 of file EntertainingSession.cpp.
References acceptingBandFlourishes.
Referenced by server::zone::objects::player::sessions::EntertainingSession::setAcceptingBandFlourishes().
void EntertainingSessionImplementation::setDancing (bool val)
Definition at line 1134 of file EntertainingSession.cpp.
References dancing.
Referenced by server::zone::objects::player::sessions::EntertainingSession::setDancing().
void EntertainingSessionImplementation::setEntertainerBuffDuration (CreatureObject * creature, int performanceType, float duration)
Definition at line 671 of file EntertainingSessionImplementation.cpp.
References PerformanceType::DANCE, listeners, PerformanceType::MUSIC, EntertainingData::setDuration(), and watchers.
Referenced by addEntertainerBuffDuration(), and server::zone::objects::player::sessions::EntertainingSession::setEntertainerBuffDuration().
void EntertainingSessionImplementation::setEntertainerBuffStrength (CreatureObject * creature, int performanceType, float strength)
Definition at line 760 of file EntertainingSessionImplementation.cpp.
References PerformanceType::DANCE, listeners, PerformanceType::MUSIC, EntertainingData::setStrength(), and watchers.
Referenced by addEntertainerBuffStrength(), and server::zone::objects::player::sessions::EntertainingSession::setEntertainerBuffStrength().
void EntertainingSessionImplementation::setPerformanceName (const String & name)
Definition at line 1129 of file EntertainingSession.cpp.
References performanceName.
Referenced by server::zone::objects::player::sessions::EntertainingSession::setPerformanceName().
void EntertainingSessionImplementation::setTargetInstrument (bool var)
Definition at line 1139 of file EntertainingSession.cpp.
References targetInstrument.
Referenced by server::zone::objects::player::sessions::EntertainingSession::setTargetInstrument().
void EntertainingSessionImplementation::startDancing (const String & dance, const String & animation)
Definition at line 380 of file EntertainingSessionImplementation.cpp.
References dancing, entertainer, performanceName, sendEntertainingUpdate(), startEntertaining(), and updateEntertainerMissionStatus().
Referenced by server::zone::objects::player::sessions::EntertainingSession::startDancing().
void EntertainingSessionImplementation::startEntertaining ()
Definition at line 429 of file EntertainingSessionImplementation.cpp.
References entertainer, observer, ObserverEventType::POSTURECHANGED, CreaturePosture::SKILLANIMATING, and startTickTask().
Referenced by startDancing(), server::zone::objects::player::sessions::EntertainingSession::startEntertaining(), and startPlayingMusic().
void EntertainingSessionImplementation::startPlayingMusic (const String & song, const String & instrumentAnimation, int instrid)
Definition at line 396 of file EntertainingSessionImplementation.cpp.
References entertainer, externalInstrument, getInstrument(), performanceName, playingMusic, sendEntertainingUpdate(), startEntertaining(), and updateEntertainerMissionStatus().
Referenced by server::zone::objects::player::sessions::EntertainingSession::startPlayingMusic().
void EntertainingSessionImplementation::startTickTask ()
Definition at line 234 of file EntertainingSessionImplementation.cpp.
References _this, and tickTask.
Referenced by activateAction(), startEntertaining(), and server::zone::objects::player::sessions::EntertainingSession::startTickTask().
void EntertainingSessionImplementation::stopDancing ()
Definition at line 446 of file EntertainingSessionImplementation.cpp.
References dancing, entertainer, SessionFacadeType::ENTERTAINING, observer, performanceName, playingMusic, ObserverEventType::POSTURECHANGED, sendEntertainingUpdate(), sendEntertainmentUpdate(), CreaturePosture::SKILLANIMATING, tickTask, updateEntertainerMissionStatus(), CreaturePosture::UPRIGHT, and watchers.
Referenced by cancelSession(), doPerformanceAction(), and server::zone::objects::player::sessions::EntertainingSession::stopDancing().
void EntertainingSessionImplementation::stopPlayingMusic ()
Definition at line 316 of file EntertainingSessionImplementation.cpp.
References dancing, entertainer, SessionFacadeType::ENTERTAINING, externalInstrument, listeners, observer, performanceName, playingMusic, ObserverEventType::POSTURECHANGED, sendEntertainingUpdate(), sendEntertainmentUpdate(), CreaturePosture::SKILLANIMATING, targetInstrument, tickTask, updateEntertainerMissionStatus(), and CreaturePosture::UPRIGHT.
Referenced by cancelSession(), doPerformanceAction(), and server::zone::objects::player::sessions::EntertainingSession::stopPlayingMusic().
void EntertainingSessionImplementation::unlock (bool doLock = true) protected
Definition at line 791 of file EntertainingSession.cpp.
References _this.
void EntertainingSessionImplementation::updateEntertainerMissionStatus (bool entertaining, const int missionType)
Definition at line 889 of file EntertainingSessionImplementation.cpp.
References entertainer, server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::mission::EntertainerMissionObjective::setIsEntertaining().
Referenced by startDancing(), startPlayingMusic(), stopDancing(), stopPlayingMusic(), and server::zone::objects::player::sessions::EntertainingSession::updateEntertainerMissionStatus().
void EntertainingSessionImplementation::wlock (bool doLock = true) protected
Definition at line 783 of file EntertainingSession.cpp.
References _this.
void EntertainingSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 787 of file EntertainingSession.cpp.
References _this.
void EntertainingSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 895 of file EntertainingSession.cpp.
References writeObjectMembers().
int EntertainingSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 902 of file EntertainingSession.cpp.
References acceptingBandFlourishes, dancing, denyServiceList, entertainer, externalInstrument, flourishCount, flourishXp, healingXp, listeners, nextTick, observer, performanceName, playingMusic, targetInstrument, and watchers.
Referenced by writeObject().
Friends And Related Function Documentation
friend class EntertainingSession friend
Definition at line 428 of file EntertainingSession.h.
Member Data Documentation
WeakReference<EntertainingSession*> server::zone::objects::player::sessions::EntertainingSessionImplementation::_this
Definition at line 396 of file EntertainingSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), startTickTask(), unlock(), and wlock().
bool server::zone::objects::player::sessions::EntertainingSessionImplementation::acceptingBandFlourishes protected
Definition at line 283 of file EntertainingSession.h.
Referenced by EntertainingSessionImplementation(), isAcceptingBandFlourishes(), readObjectMember(), setAcceptingBandFlourishes(), and writeObjectMembers().
bool server::zone::objects::player::sessions::EntertainingSessionImplementation::dancing protected
Definition at line 273 of file EntertainingSession.h.
Referenced by addEntertainerBuffStrength(), addEntertainerFlourishBuff(), doEntertainerPatronEffects(), doFlourish(), EntertainingSessionImplementation(), increaseEntertainerBuff(), isDancing(), readObjectMember(), setDancing(), startDancing(), stopDancing(), stopPlayingMusic(), and writeObjectMembers().
SortedVector<ManagedReference<CreatureObject* > > server::zone::objects::player::sessions::EntertainingSessionImplementation::denyServiceList protected
Definition at line 265 of file EntertainingSession.h.
Referenced by addToDenyServiceList(), isInDenyServiceList(), readObjectMember(), removeFromDenyServiceList(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sessions::EntertainingSessionImplementation::entertainer protected
Definition at line 257 of file EntertainingSession.h.
Referenced by activateAction(), activateEntertainerBuff(), addEntertainerBuffStrength(), addHealingXpGroup(), awardEntertainerExperience(), canGiveEntertainBuff(), canHealBattleFatigue(), doEntertainerPatronEffects(), doFlourish(), doPerformanceAction(), EntertainingSessionImplementation(), healWounds(), increaseEntertainerBuff(), readObjectMember(), startDancing(), startEntertaining(), startPlayingMusic(), stopDancing(), stopPlayingMusic(), updateEntertainerMissionStatus(), and writeObjectMembers().
ManagedReference<Instrument* > server::zone::objects::player::sessions::EntertainingSessionImplementation::externalInstrument protected
Definition at line 287 of file EntertainingSession.h.
Referenced by getInstrument(), readObjectMember(), startPlayingMusic(), stopPlayingMusic(), and writeObjectMembers().
int server::zone::objects::player::sessions::EntertainingSessionImplementation::flourishCount protected
Definition at line 281 of file EntertainingSession.h.
Referenced by awardEntertainerExperience(), doEntertainerPatronEffects(), doFlourish(), EntertainingSessionImplementation(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::player::sessions::EntertainingSessionImplementation::flourishXp protected
Definition at line 277 of file EntertainingSession.h.
Referenced by addFlourishXp(), awardEntertainerExperience(), doFlourish(), EntertainingSessionImplementation(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::player::sessions::EntertainingSessionImplementation::healingXp protected
Definition at line 279 of file EntertainingSession.h.
Referenced by addEntertainerBuffStrength(), addHealingXp(), awardEntertainerExperience(), EntertainingSessionImplementation(), readObjectMember(), and writeObjectMembers().
EntertainingDataMap server::zone::objects::player::sessions::EntertainingSessionImplementation::listeners protected
Definition at line 263 of file EntertainingSession.h.
Referenced by addEntertainerFlourishBuff(), addListener(), doEntertainerPatronEffects(), EntertainingSessionImplementation(), getEntertainerBuffDuration(), getEntertainerBuffStartTime(), getEntertainerBuffStrength(), readObjectMember(), removeListener(), setEntertainerBuffDuration(), setEntertainerBuffStrength(), stopPlayingMusic(), and writeObjectMembers().
Time server::zone::objects::player::sessions::EntertainingSessionImplementation::nextTick protected
Definition at line 269 of file EntertainingSession.h.
Referenced by readObjectMember(), and writeObjectMembers().
ManagedReference<EntertainingObserver* > server::zone::objects::player::sessions::EntertainingSessionImplementation::observer protected
Definition at line 259 of file EntertainingSession.h.
Referenced by EntertainingSessionImplementation(), readObjectMember(), startEntertaining(), stopDancing(), stopPlayingMusic(), and writeObjectMembers().
String server::zone::objects::player::sessions::EntertainingSessionImplementation::performanceName protected
Definition at line 271 of file EntertainingSession.h.
Referenced by doEntertainerPatronEffects(), doFlourish(), doPerformanceAction(), getPerformanceName(), increaseEntertainerBuff(), readObjectMember(), setPerformanceName(), startDancing(), startPlayingMusic(), stopDancing(), stopPlayingMusic(), and writeObjectMembers().
bool server::zone::objects::player::sessions::EntertainingSessionImplementation::playingMusic protected
Definition at line 275 of file EntertainingSession.h.
Referenced by addEntertainerBuffStrength(), addEntertainerFlourishBuff(), doEntertainerPatronEffects(), doFlourish(), EntertainingSessionImplementation(), increaseEntertainerBuff(), isPlayingMusic(), readObjectMember(), startPlayingMusic(), stopDancing(), stopPlayingMusic(), and writeObjectMembers().
bool server::zone::objects::player::sessions::EntertainingSessionImplementation::targetInstrument protected
Definition at line 285 of file EntertainingSession.h.
Referenced by EntertainingSessionImplementation(), getInstrument(), readObjectMember(), setTargetInstrument(), stopPlayingMusic(), and writeObjectMembers().
Reference<EntertainingSessionTask* > server::zone::objects::player::sessions::EntertainingSessionImplementation::tickTask protected
Definition at line 267 of file EntertainingSession.h.
Referenced by startTickTask(), stopDancing(), and stopPlayingMusic().
EntertainingDataMap server::zone::objects::player::sessions::EntertainingSessionImplementation::watchers protected
Definition at line 261 of file EntertainingSession.h.
Referenced by addEntertainerFlourishBuff(), addWatcher(), doEntertainerPatronEffects(), EntertainingSessionImplementation(), getEntertainerBuffDuration(), getEntertainerBuffStartTime(), getEntertainerBuffStrength(), readObjectMember(), removeWatcher(), setEntertainerBuffDuration(), setEntertainerBuffStrength(), stopDancing(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/EntertainingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/EntertainingSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/EntertainingSessionImplementation.cpp