Core3: server::login::LoginHandler Class Reference
server::login::LoginHandler Class Reference
#include <LoginHandler.h>
Public Member Functions
LoginHandler ()
void initialize ()
ServiceClient * createConnection (Socket *sock, SocketAddress &addr)
bool deleteConnection (ServiceClient *session)
void handleMessage (ServiceClient *session, Packet *message)
void processMessage (Message *message)
bool handleError (ServiceClient *client, Exception &e)
void setLoginSerrver (LoginServer *server)
LoginClient * getClient (ServiceClient *session)
Private Attributes
ManagedReference< LoginServer * > loginServerRef
LoginSessionMap clients
Detailed Description
Definition at line 47 of file LoginHandler.h.
Constructor & Destructor Documentation
server::login::LoginHandler::LoginHandler () inline
Definition at line 53 of file LoginHandler.h.
Member Function Documentation
ServiceClient* server::login::LoginHandler::createConnection (Socket * sock, SocketAddress & addr) inline
Definition at line 62 of file LoginHandler.h.
References server::login::LoginSessionMap::add(), clients, server::login::LoginServer::createConnection(), server::login::LoginClient::getSession(), and loginServerRef.
bool server::login::LoginHandler::deleteConnection (ServiceClient * session) inline
Definition at line 72 of file LoginHandler.h.
References clients, getClient(), and server::login::LoginSessionMap::remove().
LoginClient* server::login::LoginHandler::getClient (ServiceClient * session) inline
Definition at line 108 of file LoginHandler.h.
References clients, and server::login::LoginSessionMap::get().
Referenced by deleteConnection(), and handleMessage().
bool server::login::LoginHandler::handleError (ServiceClient * client, Exception & e) inline
Definition at line 98 of file LoginHandler.h.
References server::login::LoginServer::handleError(), and loginServerRef.
void server::login::LoginHandler::handleMessage (ServiceClient * session, Packet * message) inline
Definition at line 84 of file LoginHandler.h.
References getClient(), server::login::LoginServer::handleMessage(), and loginServerRef.
void server::login::LoginHandler::initialize () inline
Definition at line 56 of file LoginHandler.h.
References server::login::LoginServer::initialize(), and loginServerRef.
void server::login::LoginHandler::processMessage (Message * message) inline
Definition at line 92 of file LoginHandler.h.
References loginServerRef, and server::login::LoginServer::processMessage().
void server::login::LoginHandler::setLoginSerrver (LoginServer * server) inline
Definition at line 104 of file LoginHandler.h.
References loginServerRef.
Member Data Documentation
LoginSessionMap server::login::LoginHandler::clients private
Definition at line 50 of file LoginHandler.h.
Referenced by createConnection(), deleteConnection(), and getClient().
ManagedReference<LoginServer*> server::login::LoginHandler::loginServerRef private
Definition at line 48 of file LoginHandler.h.
Referenced by createConnection(), handleError(), handleMessage(), initialize(), processMessage(), and setLoginSerrver().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginHandler.h