Core3: server::zone::objects::player::sessions::crafting::CraftingSession Class Reference
server::zone::objects::player::sessions::crafting::CraftingSession Class Reference
#include <CraftingSession.h>
Public Member Functions
CraftingSession (CreatureObject *creature)
int initializeSession (CraftingTool *tool, CraftingStation *station)
int cancelSession ()
int clearSession ()
ManagedWeakReference
< ManufactureSchematic * > getSchematic ()
void selectDraftSchematic (int index)
void sendIngredientForUIListen ()
void addIngredient (TangibleObject *tano, int slotUpdated, int clientCounter)
void removeIngredient (TangibleObject *tano, int slotUpdated, int clientCounter)
void nextCraftingStage (int clientCounter)
void experiment (int rowsAttempted, const String &expAttempt, int clientCounter)
void customization (const String &name, byte templateChoice, int schematicCount, const String &customizationString)
void createPrototype (int clientCounter, bool practice)
void createManufactureSchematic (int clientCounter)
int getState ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
CraftingSession (DummyConstructorParameter *param)
virtual ~CraftingSession ()
Friends
class CraftingSessionHelper
Detailed Description
Definition at line 157 of file CraftingSession.h.
Constructor & Destructor Documentation
CraftingSession::CraftingSession (CreatureObject * creature)
Definition at line 31 of file CraftingSession.cpp.
References server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::_setStub().
CraftingSession::CraftingSession (DummyConstructorParameter * param) protected
Definition at line 38 of file CraftingSession.cpp.
CraftingSession::~CraftingSession () protected virtual
Definition at line 42 of file CraftingSession.cpp.
Member Function Documentation
DistributedObjectServant * CraftingSession::_getImplementation ()
Definition at line 249 of file CraftingSession.cpp.
Referenced by addIngredient(), cancelSession(), clearSession(), createManufactureSchematic(), createPrototype(), customization(), experiment(), getSchematic(), getState(), initializeSession(), nextCraftingStage(), removeIngredient(), selectDraftSchematic(), and sendIngredientForUIListen().
DistributedObjectServant * CraftingSession::_getImplementationForRead ()
Definition at line 255 of file CraftingSession.cpp.
void CraftingSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 259 of file CraftingSession.cpp.
void CraftingSession::addIngredient (TangibleObject * tano, int slotUpdated, int clientCounter)
The CraftingAddIngredientCallback executes this method when an object is added in the crafting window
Definition at line 128 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::addIngredient(), and RPC_ADDINGREDIENT__TANGIBLEOBJECT_INT_INT_.
int CraftingSession::cancelSession ()
Cancels the current session
Definition at line 62 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
int CraftingSession::clearSession ()
Definition at line 75 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
void CraftingSession::createManufactureSchematic (int clientCounter)
CreateManfSchematicCommand calls this
Definition at line 222 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::createManufactureSchematic(), and RPC_CREATEMANUFACTURESCHEMATIC__INT_.
void CraftingSession::createPrototype (int clientCounter, bool practice)
CreatePrototypeCommand calls this
Definition at line 207 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::createPrototype(), and RPC_CREATEPROTOTYPE__INT_BOOL_.
void CraftingSession::customization (const String & name, byte templateChoice, int schematicCount, const String & customizationString)
The CraftingCustomizationCallback executes this method a user customizes a tano in the crafting tool
Definition at line 190 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::customization(), and RPC_CUSTOMIZATION__STRING_BYTE_INT_STRING_.
void CraftingSession::experiment (int rowsAttempted, const String & expAttempt, int clientCounter)
The CraftingExperimentCallback executes this method when a player experiments in a crafting tool
Definition at line 174 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::experiment(), and RPC_EXPERIMENT__INT_STRING_INT_.
ManagedWeakReference< ManufactureSchematic * > CraftingSession::getSchematic ()
Definition at line 88 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::getSchematic(), and RPC_GETSCHEMATIC__.
int CraftingSession::getState ()
Definition at line 236 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::getState(), and RPC_GETSTATE__.
int CraftingSession::initializeSession (CraftingTool * tool, CraftingStation * station)
The crafting tool and station have been identified pre calling initializeSession
Definition at line 47 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__CRAFTINGTOOL_CRAFTINGSTATION_.
void CraftingSession::nextCraftingStage (int clientCounter)
The NextCraftingStageCommand uses this
Definition at line 160 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::nextCraftingStage(), and RPC_NEXTCRAFTINGSTAGE__INT_.
void CraftingSession::removeIngredient (TangibleObject * tano, int slotUpdated, int clientCounter)
The CraftingRemoveIngredientCallback executes this method when an object is removed from the crafting window
Definition at line 144 of file CraftingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::removeIngredient(), and RPC_REMOVEINGREDIENT__TANGIBLEOBJECT_INT_INT_.
void CraftingSession::selectDraftSchematic (int index)
The SelectDraftSchematicCommand uses this
Definition at line 101 of file CraftingSession.cpp.
References _getImplementation(), RPC_SELECTDRAFTSCHEMATIC__INT_, and server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::selectDraftSchematic().
void CraftingSession::sendIngredientForUIListen ()
Sends ingredients on ManufactureSchematic::synchronizedUIListen
Definition at line 115 of file CraftingSession.cpp.
References _getImplementation(), RPC_SENDINGREDIENTFORUILISTEN__, and server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::sendIngredientForUIListen().
Friends And Related Function Documentation
friend class CraftingSessionHelper friend
Definition at line 239 of file CraftingSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/crafting/CraftingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/crafting/CraftingSession.cpp