Core3: FleeStateComponent Class Reference
FleeStateComponent Class Reference
#include <FleeStateComponent.h>
Public Member Functions
uint16 doRecovery (AiActor *actor)
uint16 doMovement (AiActor *actor)
float getSpeed (CreatureObject *host)
PatrolPoint getFleeLocation (CreatureObject *host, SceneObject *followObject)
Public Member Functions inherited from AiStateComponent
virtual void notifyPositionUpdate (Observable *obs, QuadTreeEntry *entry)
void notifyDespawn (AiActor *actor, Zone *zone)
virtual void doAwarenessCheck (Observable *obs, Coordinate &start, uint64 time, CreatureObject *target)
virtual uint16 onEnter (AiActor *actor)
virtual void onExit (AiActor *actor)
virtual uint16 tryRetreat (AiActor *actor)
virtual uint16 doAttack (AiActor *actor)
bool findNextPosition (Observable *obs, float maxDistance, float speed, PatrolPointsVector *patrolPoints, WorldCoordinates *nextPosition)
virtual float getMaxDistance (CreatureObject *host)
void setNextPosition (AiActor *actor, float x, float z, float y, SceneObject *cell=NULL)
void updateCurrentPosition (CreatureObject *host, PatrolPoint *pos)
void broadcastNextPositionUpdate (CreatureObject *host, PatrolPoint *point)
void checkNewAngle (AiActor *actor)
void sendConversationStartTo (CreatureObject *host, SceneObject *player)
void selectWeapon (AiActor *actor)
bool validateStateAttack (CreatureObject *target, String &args)
virtual bool isScared (CreatureObject *host, SceneObject *followObject)
Detailed Description
Definition at line 20 of file FleeStateComponent.h.
Member Function Documentation
uint16 FleeStateComponent::doMovement (AiActor * actor) inline virtual
Reimplemented from AiStateComponent.
Definition at line 43 of file FleeStateComponent.h.
References AiStateComponent::doMovement(), PatrolPoint::getCell(), getFleeLocation(), server::zone::objects::creature::ai::AiActor::getFollowObject(), server::zone::objects::creature::ai::AiActor::getHost(), server::zone::objects::creature::ai::AiActor::getPatrolPoints(), PatrolPoint::getPositionX(), PatrolPoint::getPositionY(), PatrolPoint::getPositionZ(), and AiStateComponent::setNextPosition().
uint16 FleeStateComponent::doRecovery (AiActor * actor) inline virtual
Reimplemented from AiStateComponent.
Definition at line 22 of file FleeStateComponent.h.
References server::zone::objects::creature::CreatureObject::activateHAMRegeneration(), server::zone::objects::creature::ai::AiActor::activatePostureRecovery(), server::zone::objects::creature::ai::AiActor::activateRecovery(), server::zone::objects::creature::ai::AiActor::getFollowObject(), and server::zone::objects::creature::ai::AiActor::getHost().
PatrolPoint FleeStateComponent::getFleeLocation (CreatureObject * host, SceneObject * followObject) inline
Definition at line 68 of file FleeStateComponent.h.
References PathGraph::findNearestGlobalNode(), server::zone::objects::cell::CellObject::getCellNumber(), PortalLayout::getFloorMesh(), PortalLayout::getFloorMeshID(), PathNode::getGlobalGraphNodeID(), server::zone::Zone::getHeight(), server::zone::objects::scene::SceneObject::getParent(), FloorMesh::getPathGraph(), PathGraph::getPathNodes(), server::zone::templates::SharedObjectTemplate::getPortalLayout(), PatrolPoint::getPositionX(), PatrolPoint::getPositionY(), server::zone::objects::scene::SceneObject::getWorldPosition(), server::zone::objects::scene::SceneObject::getZone(), PatrolPoint::setCell(), PatrolPoint::setPosition(), and PatrolPoint::setPositionZ().
Referenced by doMovement().
float FleeStateComponent::getSpeed (CreatureObject * host) inline virtual
Reimplemented from AiStateComponent.
Definition at line 64 of file FleeStateComponent.h.
References server::zone::objects::creature::CreatureObject::getRunSpeed().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/components/FleeStateComponent.h