Core3: server::zone::objects::mission::ReconMissionObjectiveImplementation Class Reference
server::zone::objects::mission::ReconMissionObjectiveImplementation Class Reference
#include <ReconMissionObjective.h>
Public Member Functions
ReconMissionObjectiveImplementation (MissionObject *mission)
ReconMissionObjectiveImplementation (DummyConstructorParameter *param)
void finalize ()
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
Vector3 getEndPosition ()
operator const ReconMissionObjective * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
MissionObjectiveImplementation (MissionObject *parent)
MissionObjectiveImplementation (DummyConstructorParameter *param)
virtual void destroyObjectFromDatabase ()
virtual int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
virtual void deactivate ()
virtual void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
operator const MissionObjective * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< ReconMissionObjective * > _this
Public Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
WeakReference< MissionObjective * > _this
Protected Member Functions
virtual ~ReconMissionObjectiveImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
virtual ~MissionObjectiveImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference
< MissionReconActiveArea * > locationActiveArea
Protected Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
ManagedWeakReference
< MissionObject * > mission
unsigned int objectiveType
Time missionStartTime
Reference
< FailMissionAfterCertainTimeTask * > failTask
unsigned long long timeRemaining
bool activated
Friends
class ReconMissionObjective
Detailed Description
Definition at line 134 of file ReconMissionObjective.h.
Constructor & Destructor Documentation
ReconMissionObjectiveImplementation::ReconMissionObjectiveImplementation (MissionObject * mission)
Definition at line 242 of file ReconMissionObjective.cpp.
References _initializeImplementation().
ReconMissionObjectiveImplementation::ReconMissionObjectiveImplementation (DummyConstructorParameter * param)
Definition at line 118 of file ReconMissionObjective.cpp.
References _initializeImplementation().
ReconMissionObjectiveImplementation::~ReconMissionObjectiveImplementation () protected virtual
Definition at line 123 of file ReconMissionObjective.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * ReconMissionObjectiveImplementation::_getStub ()
Definition at line 141 of file ReconMissionObjective.cpp.
References _this.
void ReconMissionObjectiveImplementation::_initializeImplementation () protected
Definition at line 128 of file ReconMissionObjective.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ReconMissionObjectiveImplementation().
void ReconMissionObjectiveImplementation::_serializationHelperMethod () protected
Definition at line 177 of file ReconMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void ReconMissionObjectiveImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 136 of file ReconMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_setStub(), and _this.
Referenced by server::zone::objects::mission::ReconMissionObjective::ReconMissionObjective().
void ReconMissionObjectiveImplementation::abort () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 65 of file ReconMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::abort(), and locationActiveArea.
Referenced by server::zone::objects::mission::ReconMissionObjective::abort().
void ReconMissionObjectiveImplementation::activate () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 23 of file ReconMissionObjectiveImplementation.cpp.
References _this, server::zone::objects::mission::MissionObjectiveImplementation::activate(), server::zone::objects::scene::SceneObject::getZone(), locationActiveArea, server::zone::objects::mission::MissionObjectiveImplementation::mission, and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::objects::mission::ReconMissionObjective::activate(), and initializeTransientMembers().
void ReconMissionObjectiveImplementation::complete () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 72 of file ReconMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::complete(), and locationActiveArea.
Referenced by server::zone::objects::mission::ReconMissionObjective::complete().
void ReconMissionObjectiveImplementation::finalize ()
Definition at line 248 of file ReconMissionObjective.cpp.
Referenced by ~ReconMissionObjectiveImplementation().
Vector3 ReconMissionObjectiveImplementation::getEndPosition () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 78 of file ReconMissionObjectiveImplementation.cpp.
References TerrainManager::getHeight(), server::zone::Zone::getPlanetManager(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::managers::planet::PlanetManager::getTerrainManager(), and server::zone::objects::mission::MissionObjectiveImplementation::mission.
Referenced by server::zone::objects::mission::ReconMissionObjective::getEndPosition().
void ReconMissionObjectiveImplementation::initializeTransientMembers () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 251 of file ReconMissionObjective.cpp.
References activate(), and server::zone::objects::mission::MissionObjectiveImplementation::initializeTransientMembers().
Referenced by server::zone::objects::mission::ReconMissionObjective::initializeTransientMembers(), and readObject().
void ReconMissionObjectiveImplementation::lock (bool doLock = true) protected
Definition at line 149 of file ReconMissionObjective.cpp.
References _this.
void ReconMissionObjectiveImplementation::lock (ManagedObject * obj) protected
Definition at line 153 of file ReconMissionObjective.cpp.
References _this.
ReconMissionObjectiveImplementation::operator const ReconMissionObjective * ()
Definition at line 145 of file ReconMissionObjective.cpp.
void ReconMissionObjectiveImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 184 of file ReconMissionObjective.cpp.
References initializeTransientMembers(), and readObjectMember().
bool ReconMissionObjectiveImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 203 of file ReconMissionObjective.cpp.
References locationActiveArea, and server::zone::objects::mission::MissionObjectiveImplementation::readObjectMember().
Referenced by readObject().
void ReconMissionObjectiveImplementation::rlock (bool doLock = true) protected
Definition at line 157 of file ReconMissionObjective.cpp.
References _this.
void ReconMissionObjectiveImplementation::runlock (bool doLock = true) protected
Definition at line 173 of file ReconMissionObjective.cpp.
References _this.
void ReconMissionObjectiveImplementation::unlock (bool doLock = true) protected
Definition at line 169 of file ReconMissionObjective.cpp.
References _this.
void ReconMissionObjectiveImplementation::wlock (bool doLock = true) protected
Definition at line 161 of file ReconMissionObjective.cpp.
References _this.
void ReconMissionObjectiveImplementation::wlock (ManagedObject * obj) protected
Definition at line 165 of file ReconMissionObjective.cpp.
References _this.
void ReconMissionObjectiveImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 217 of file ReconMissionObjective.cpp.
References writeObjectMembers().
int ReconMissionObjectiveImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 224 of file ReconMissionObjective.cpp.
References locationActiveArea, and server::zone::objects::mission::MissionObjectiveImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class ReconMissionObjective friend
Definition at line 187 of file ReconMissionObjective.h.
Member Data Documentation
WeakReference<ReconMissionObjective*> server::zone::objects::mission::ReconMissionObjectiveImplementation::_this
Definition at line 155 of file ReconMissionObjective.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), activate(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedReference<MissionReconActiveArea* > server::zone::objects::mission::ReconMissionObjectiveImplementation::locationActiveArea protected
Definition at line 136 of file ReconMissionObjective.h.
Referenced by abort(), activate(), complete(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/ReconMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/ReconMissionObjective.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/ReconMissionObjectiveImplementation.cpp