Core3: server::login::LoginSessionMap Class Reference
server::login::LoginSessionMap Class Reference
#include <LoginHandler.h>
Public Member Functions
LoginSessionMap (int maxconn=10000)
bool add (LoginClient *client)
bool remove (LoginClient *client)
LoginClient * get (uint64 id)
Private Attributes
int maxConnections
Detailed Description
Definition at line 17 of file LoginHandler.h.
Constructor & Destructor Documentation
server::login::LoginSessionMap::LoginSessionMap (int maxconn = 10000) inline
Definition at line 22 of file LoginHandler.h.
References maxConnections.
Member Function Documentation
bool server::login::LoginSessionMap::add (LoginClient * client) inline
Definition at line 27 of file LoginHandler.h.
References server::login::LoginClient::getSession().
Referenced by server::login::LoginHandler::createConnection().
LoginClient* server::login::LoginSessionMap::get (uint64 id) inline
Definition at line 41 of file LoginHandler.h.
Referenced by server::login::LoginHandler::getClient().
bool server::login::LoginSessionMap::remove (LoginClient * client) inline
Definition at line 34 of file LoginHandler.h.
Referenced by server::login::LoginHandler::deleteConnection().
Member Data Documentation
int server::login::LoginSessionMap::maxConnections private
Definition at line 20 of file LoginHandler.h.
Referenced by LoginSessionMap().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginHandler.h