Core3: ClientCore Class Reference
ClientCore Class Reference
#include <ClientCore.h>
Public Member Functions
ClientCore (int instances)
void initialize ()
void run ()
void loginCharacter (int index)
void logoutCharacter (int index)
void handleCommands ()
Private Attributes
int instances
Vector< Zone * > zones
Detailed Description
Definition at line 53 of file ClientCore.h.
Constructor & Destructor Documentation
ClientCore::ClientCore (int instances)
Definition at line 52 of file ClientCore.cpp.
References instances.
Member Function Documentation
void ClientCore::handleCommands ()
Definition at line 151 of file ClientCore.cpp.
References zones.
void ClientCore::initialize ()
Definition at line 58 of file ClientCore.cpp.
void ClientCore::loginCharacter (int index)
Definition at line 105 of file ClientCore.cpp.
References connectCount, and zones.
Referenced by run().
void ClientCore::logoutCharacter (int index)
Definition at line 137 of file ClientCore.cpp.
References Zone::disconnect(), disconnectCount, Zone::isStarted(), and zones.
Referenced by run().
void ClientCore::run ()
Definition at line 64 of file ClientCore.cpp.
References connectCount, Zone::disconnect(), disconnectCount, instances, loginCharacter(), logoutCharacter(), and zones.
Member Data Documentation
int ClientCore::instances private
Definition at line 54 of file ClientCore.h.
Referenced by ClientCore(), and run().
Vector<Zone*> ClientCore::zones private
Definition at line 56 of file ClientCore.h.
Referenced by handleCommands(), loginCharacter(), logoutCharacter(), and run().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/ClientCore.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/ClientCore.cpp