Core3: server::zone::objects::creature::conversation::LuaConversationObserverImplementation Class Reference
server::zone::objects::creature::conversation::LuaConversationObserverImplementation Class Reference
#include <LuaConversationObserver.h>
Public Member Functions
LuaConversationObserverImplementation (ConversationTemplate *conversationTemplate)
LuaConversationObserverImplementation (DummyConstructorParameter *param)
ConversationScreen * getNextConversationScreen (CreatureObject *conversingPlayer, int selectedOption, CreatureObject *conversingNPC)
ConversationScreen * runScreenHandlers (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
operator const LuaConversationObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
ConversationObserverImplementation (ConversationTemplate *conversationTemplate)
ConversationObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const ConversationObserver * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< LuaConversationObserver * > _this
Public Attributes inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
WeakReference
< ConversationObserver * > _this
Protected Member Functions
virtual ~LuaConversationObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
virtual void createConversationSession (CreatureObject *conversingPlayer, CreatureObject *npc)
void registerScreenHandler (const String &screenId, ScreenHandler *screenHandler)
void removeScreenHandler (const String &screenId)
void createPositionObserver (CreatureObject *player)
virtual ~ConversationObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class LuaConversationObserver
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
Reference< ConversationTemplate * > conversationTemplate
Detailed Description
Definition at line 83 of file LuaConversationObserver.h.
Constructor & Destructor Documentation
LuaConversationObserverImplementation::LuaConversationObserverImplementation (ConversationTemplate * conversationTemplate)
Definition at line 179 of file LuaConversationObserver.cpp.
References _initializeImplementation().
LuaConversationObserverImplementation::LuaConversationObserverImplementation (DummyConstructorParameter * param)
Definition at line 65 of file LuaConversationObserver.cpp.
References _initializeImplementation().
LuaConversationObserverImplementation::~LuaConversationObserverImplementation () protected virtual
Definition at line 70 of file LuaConversationObserver.cpp.
Member Function Documentation
DistributedObjectStub * LuaConversationObserverImplementation::_getStub ()
Definition at line 90 of file LuaConversationObserver.cpp.
References _this.
void LuaConversationObserverImplementation::_initializeImplementation () protected
Definition at line 77 of file LuaConversationObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by LuaConversationObserverImplementation().
void LuaConversationObserverImplementation::_serializationHelperMethod () protected
Definition at line 126 of file LuaConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void LuaConversationObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 85 of file LuaConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::conversation::LuaConversationObserver::LuaConversationObserver().
void LuaConversationObserverImplementation::finalize () protected
Definition at line 74 of file LuaConversationObserver.cpp.
ConversationScreen * LuaConversationObserverImplementation::getNextConversationScreen (CreatureObject * conversingPlayer, int selectedOption, CreatureObject * conversingNPC) virtual
Reimplemented from server::zone::objects::creature::conversation::ConversationObserverImplementation.
Definition at line 183 of file LuaConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::conversationTemplate.
Referenced by server::zone::objects::creature::conversation::LuaConversationObserver::getNextConversationScreen().
void LuaConversationObserverImplementation::lock (bool doLock = true) protected
Definition at line 98 of file LuaConversationObserver.cpp.
References _this.
void LuaConversationObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 102 of file LuaConversationObserver.cpp.
References _this.
LuaConversationObserverImplementation::operator const LuaConversationObserver * ()
Definition at line 94 of file LuaConversationObserver.cpp.
void LuaConversationObserverImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::conversation::ConversationObserverImplementation.
Definition at line 133 of file LuaConversationObserver.cpp.
References readObjectMember().
bool LuaConversationObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 152 of file LuaConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::readObjectMember().
Referenced by readObject().
void LuaConversationObserverImplementation::rlock (bool doLock = true) protected
Definition at line 106 of file LuaConversationObserver.cpp.
References _this.
void LuaConversationObserverImplementation::runlock (bool doLock = true) protected
Definition at line 122 of file LuaConversationObserver.cpp.
References _this.
ConversationScreen * LuaConversationObserverImplementation::runScreenHandlers (CreatureObject * conversingPlayer, CreatureObject * conversingNPC, int selectedOption, ConversationScreen * conversationScreen) virtual
Reimplemented from server::zone::objects::creature::conversation::ConversationObserverImplementation.
Definition at line 188 of file LuaConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::conversationTemplate.
Referenced by server::zone::objects::creature::conversation::LuaConversationObserver::runScreenHandlers().
void LuaConversationObserverImplementation::unlock (bool doLock = true) protected
Definition at line 118 of file LuaConversationObserver.cpp.
References _this.
void LuaConversationObserverImplementation::wlock (bool doLock = true) protected
Definition at line 110 of file LuaConversationObserver.cpp.
References _this.
void LuaConversationObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 114 of file LuaConversationObserver.cpp.
References _this.
void LuaConversationObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::conversation::ConversationObserverImplementation.
Definition at line 162 of file LuaConversationObserver.cpp.
References writeObjectMembers().
int LuaConversationObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 169 of file LuaConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class LuaConversationObserver friend
Definition at line 128 of file LuaConversationObserver.h.
Member Data Documentation
WeakReference<LuaConversationObserver*> server::zone::objects::creature::conversation::LuaConversationObserverImplementation::_this
Definition at line 94 of file LuaConversationObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/LuaConversationObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/LuaConversationObserver.cpp