Core3: server::zone::managers::creature::LairObserverImplementation Class Reference
server::zone::managers::creature::LairObserverImplementation Class Reference
#include <LairObserver.h>
Public Member Functions
LairObserverImplementation ()
LairObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void notifyDestruction (TangibleObject *lair, TangibleObject *attacker, int condition)
bool checkForNewSpawns (TangibleObject *lair, bool forceSpawn=false)
void healLair (TangibleObject *lair, TangibleObject *attacker)
void checkForHeal (TangibleObject *lair, TangibleObject *attacker, bool forceNewUpdate=false)
void doAggro (TangibleObject *lair, TangibleObject *attacker)
void setLairTemplate (LairTemplate *tmpl)
void setDifficulty (int diff)
bool isLairObserver ()
int getLivingCreatureCount ()
int getLairType ()
int getSpawnNumber ()
operator const LairObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< LairObserver * > _this
Protected Member Functions
virtual ~LairObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
Reference< LairTemplate * > lairTemplate
Vector< ManagedReference
< CreatureObject * > > spawnedCreatures
int spawnNumber
Reference
< HealLairObserverEvent * > healLairEvent
int difficulty
Friends
class LairObserver
Detailed Description
Definition at line 122 of file LairObserver.h.
Constructor & Destructor Documentation
LairObserverImplementation::LairObserverImplementation ()
Definition at line 372 of file LairObserver.cpp.
References _initializeImplementation(), difficulty, healLairEvent, lairTemplate, and spawnNumber.
LairObserverImplementation::LairObserverImplementation (DummyConstructorParameter * param)
Definition at line 222 of file LairObserver.cpp.
References _initializeImplementation().
LairObserverImplementation::~LairObserverImplementation () protected virtual
Definition at line 227 of file LairObserver.cpp.
Member Function Documentation
DistributedObjectStub * LairObserverImplementation::_getStub ()
Definition at line 247 of file LairObserver.cpp.
References _this.
void LairObserverImplementation::_initializeImplementation () protected
Definition at line 234 of file LairObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by LairObserverImplementation().
void LairObserverImplementation::_serializationHelperMethod () protected
Definition at line 283 of file LairObserver.cpp.
Referenced by _initializeImplementation().
void LairObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 242 of file LairObserver.cpp.
References _this.
Referenced by server::zone::managers::creature::LairObserver::LairObserver().
void LairObserverImplementation::checkForHeal (TangibleObject * lair, TangibleObject * attacker, bool forceNewUpdate = false)
Definition at line 138 of file LairObserverImplementation.cpp.
References _this, server::zone::objects::tangible::TangibleObject::getConditionDamage(), getLairType(), getLivingCreatureCount(), healLairEvent, and server::zone::objects::tangible::TangibleObject::isDestroyed().
Referenced by server::zone::managers::creature::LairObserver::checkForHeal(), and notifyObserverEvent().
bool LairObserverImplementation::checkForNewSpawns (TangibleObject * lair, bool forceSpawn = false)
Definition at line 192 of file LairObserverImplementation.cpp.
References difficulty, server::zone::objects::tangible::TangibleObject::getConditionDamage(), server::zone::Zone::getCreatureManager(), server::zone::Zone::getHeight(), server::zone::objects::tangible::TangibleObject::getMaxCondition(), server::zone::objects::scene::SceneObject::getZone(), lairTemplate, server::zone::objects::creature::AiAgent::setDespawnOnNoPlayerInRange(), server::zone::objects::creature::AiAgent::setHomeLocation(), server::zone::objects::creature::AiAgent::setRespawnTimer(), server::zone::managers::creature::CreatureManager::spawnCreatureWithLevel(), spawnedCreatures, and spawnNumber.
Referenced by server::zone::managers::creature::LairObserver::checkForNewSpawns(), and notifyObserverEvent().
void LairObserverImplementation::doAggro (TangibleObject * lair, TangibleObject * attacker)
Definition at line 117 of file LairObserverImplementation.cpp.
References server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::tangible::TangibleObject::setDefender(), and spawnedCreatures.
Referenced by server::zone::managers::creature::LairObserver::doAggro().
void LairObserverImplementation::finalize () protected
Definition at line 231 of file LairObserver.cpp.
int LairObserverImplementation::getLairType ()
Definition at line 419 of file LairObserver.cpp.
References lairTemplate.
Referenced by checkForHeal(), and server::zone::managers::creature::LairObserver::getLairType().
int LairObserverImplementation::getLivingCreatureCount ()
Definition at line 401 of file LairObserver.cpp.
References spawnedCreatures.
Referenced by checkForHeal(), server::zone::managers::creature::LairObserver::getLivingCreatureCount(), and notifyObserverEvent().
int LairObserverImplementation::getSpawnNumber ()
Definition at line 424 of file LairObserver.cpp.
References spawnNumber.
Referenced by server::zone::managers::creature::LairObserver::getSpawnNumber().
void LairObserverImplementation::healLair (TangibleObject * lair, TangibleObject * attacker)
Definition at line 154 of file LairObserverImplementation.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), server::zone::objects::tangible::TangibleObject::getMaxCondition(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::tangible::TangibleObject::healDamage(), server::zone::objects::creature::CreatureObject::isDead(), and spawnedCreatures.
Referenced by server::zone::managers::creature::LairObserver::healLair().
bool LairObserverImplementation::isLairObserver ()
Definition at line 396 of file LairObserver.cpp.
Referenced by server::zone::managers::creature::LairObserver::isLairObserver().
void LairObserverImplementation::lock (bool doLock = true) protected
Definition at line 255 of file LairObserver.cpp.
References _this.
void LairObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 259 of file LairObserver.cpp.
References _this.
void LairObserverImplementation::notifyDestruction (TangibleObject * lair, TangibleObject * attacker, int condition)
Definition at line 84 of file LairObserverImplementation.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::managers::player::PlayerManager::disseminateExperience(), server::zone::ZoneServer::getPlayerManager(), server::zone::objects::tangible::TangibleObject::getThreatMap(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::tangible::threat::ThreatMap::removeAll(), server::zone::objects::tangible::threat::ThreatMap::removeObservers(), and spawnedCreatures.
Referenced by server::zone::managers::creature::LairObserver::notifyDestruction(), and notifyObserverEvent().
int LairObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 58 of file LairObserverImplementation.cpp.
References _this, checkForHeal(), checkForNewSpawns(), ObserverEventType::DAMAGERECEIVED, getLivingCreatureCount(), notifyDestruction(), and ObserverEventType::OBJECTDESTRUCTION.
Referenced by server::zone::managers::creature::LairObserver::notifyObserverEvent().
LairObserverImplementation::operator const LairObserver * ()
Definition at line 251 of file LairObserver.cpp.
void LairObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 290 of file LairObserver.cpp.
References readObjectMember().
bool LairObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 309 of file LairObserver.cpp.
References difficulty, spawnedCreatures, and spawnNumber.
Referenced by readObject().
void LairObserverImplementation::rlock (bool doLock = true) protected
Definition at line 263 of file LairObserver.cpp.
References _this.
void LairObserverImplementation::runlock (bool doLock = true) protected
Definition at line 279 of file LairObserver.cpp.
References _this.
void LairObserverImplementation::setDifficulty (int diff)
Definition at line 391 of file LairObserver.cpp.
References difficulty.
Referenced by server::zone::managers::creature::LairObserver::setDifficulty().
void LairObserverImplementation::setLairTemplate (LairTemplate * tmpl)
Definition at line 386 of file LairObserver.cpp.
References lairTemplate.
Referenced by server::zone::managers::creature::LairObserver::setLairTemplate().
void LairObserverImplementation::unlock (bool doLock = true) protected
Definition at line 275 of file LairObserver.cpp.
References _this.
void LairObserverImplementation::wlock (bool doLock = true) protected
Definition at line 267 of file LairObserver.cpp.
References _this.
void LairObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 271 of file LairObserver.cpp.
References _this.
void LairObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 331 of file LairObserver.cpp.
References writeObjectMembers().
int LairObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 338 of file LairObserver.cpp.
References difficulty, spawnedCreatures, and spawnNumber.
Referenced by writeObject().
Friends And Related Function Documentation
friend class LairObserver friend
Definition at line 197 of file LairObserver.h.
Member Data Documentation
WeakReference<LairObserver*> server::zone::managers::creature::LairObserverImplementation::_this
Definition at line 163 of file LairObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), checkForHeal(), lock(), notifyObserverEvent(), rlock(), runlock(), unlock(), and wlock().
int server::zone::managers::creature::LairObserverImplementation::difficulty protected
Definition at line 132 of file LairObserver.h.
Referenced by checkForNewSpawns(), LairObserverImplementation(), readObjectMember(), setDifficulty(), and writeObjectMembers().
Reference<HealLairObserverEvent* > server::zone::managers::creature::LairObserverImplementation::healLairEvent protected
Definition at line 130 of file LairObserver.h.
Referenced by checkForHeal(), and LairObserverImplementation().
Reference<LairTemplate* > server::zone::managers::creature::LairObserverImplementation::lairTemplate protected
Definition at line 124 of file LairObserver.h.
Referenced by checkForNewSpawns(), getLairType(), LairObserverImplementation(), and setLairTemplate().
Vector<ManagedReference<CreatureObject* > > server::zone::managers::creature::LairObserverImplementation::spawnedCreatures protected
Definition at line 126 of file LairObserver.h.
Referenced by checkForNewSpawns(), doAggro(), getLivingCreatureCount(), healLair(), notifyDestruction(), readObjectMember(), and writeObjectMembers().
int server::zone::managers::creature::LairObserverImplementation::spawnNumber protected
Definition at line 128 of file LairObserver.h.
Referenced by checkForNewSpawns(), getSpawnNumber(), LairObserverImplementation(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/LairObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/LairObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/LairObserverImplementation.cpp