Core3: PathEdge Class Reference
PathEdge Class Reference
#include <PathNode.h>
Public Member Functions
PathEdge ()
void readObject (IffStream *iffStream)
int getFromConnection ()
int getToConnection ()
Private Attributes
int from
int to
int var3
int var4
Detailed Description
Definition at line 85 of file PathNode.h.
Constructor & Destructor Documentation
PathEdge::PathEdge () inline
Definition at line 89 of file PathNode.h.
Member Function Documentation
int PathEdge::getFromConnection () inline
Definition at line 100 of file PathNode.h.
References from.
Referenced by PathGraph::connectNodes().
int PathEdge::getToConnection () inline
Definition at line 104 of file PathNode.h.
References to.
Referenced by PathGraph::connectNodes().
void PathEdge::readObject (IffStream * iffStream) inline
Definition at line 93 of file PathNode.h.
References from, to, var3, and var4.
Referenced by PathGraph::readObject().
Member Data Documentation
int PathEdge::from private
Definition at line 86 of file PathNode.h.
Referenced by getFromConnection(), and readObject().
int PathEdge::to private
Definition at line 86 of file PathNode.h.
Referenced by getToConnection(), and readObject().
int PathEdge::var3 private
Definition at line 86 of file PathNode.h.
Referenced by readObject().
int PathEdge::var4 private
Definition at line 86 of file PathNode.h.
Referenced by readObject().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/PathNode.h