Core3: server::zone::managers::crafting::CraftingManagerAdapter Class Reference
server::zone::managers::crafting::CraftingManagerAdapter Class Reference
#include <CraftingManager.h>
Public Member Functions
CraftingManagerAdapter (CraftingManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
DraftSchematic * getSchematic (unsigned int schematicID)
void sendDraftSlotsTo (CreatureObject *player, unsigned int schematicID)
void sendResourceWeightsTo (CreatureObject *player, unsigned int schematicID)
int calculateAssemblySuccess (CreatureObject *player, DraftSchematic *draftSchematic, float effectiveness)
int calculateExperimentationFailureRate (CreatureObject *player, ManufactureSchematic *manufactureSchematic, int pointsUsed)
int calculateExperimentationSuccess (CreatureObject *player, DraftSchematic *draftSchematic, float effectiveness)
String generateSerial ()
String checkBioSkillMods (const String &property)
void setInitialCraftingValues (TangibleObject *prototype, ManufactureSchematic *manufactureSchematic, int assemblySuccess)
bool allowManufactureSchematic (ManufactureSchematic *manufactureSchematic)
Public Member Functions inherited from server::zone::manager::ZoneManagerAdapter
ZoneManagerAdapter (ZoneManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setZoneProcessor (ZoneProcessServer *server)
Detailed Description
Definition at line 365 of file CraftingManager.h.
Constructor & Destructor Documentation
CraftingManagerAdapter::CraftingManagerAdapter (CraftingManager * impl)
Definition at line 379 of file CraftingManager.cpp.
Member Function Documentation
bool CraftingManagerAdapter::allowManufactureSchematic (ManufactureSchematic * manufactureSchematic)
Definition at line 478 of file CraftingManager.cpp.
Referenced by invokeMethod().
int CraftingManagerAdapter::calculateAssemblySuccess (CreatureObject * player, DraftSchematic * draftSchematic, float effectiveness)
Definition at line 454 of file CraftingManager.cpp.
Referenced by invokeMethod().
int CraftingManagerAdapter::calculateExperimentationFailureRate (CreatureObject * player, ManufactureSchematic * manufactureSchematic, int pointsUsed)
Definition at line 458 of file CraftingManager.cpp.
Referenced by invokeMethod().
int CraftingManagerAdapter::calculateExperimentationSuccess (CreatureObject * player, DraftSchematic * draftSchematic, float effectiveness)
Definition at line 462 of file CraftingManager.cpp.
Referenced by invokeMethod().
String CraftingManagerAdapter::checkBioSkillMods (const String & property)
Definition at line 470 of file CraftingManager.cpp.
Referenced by invokeMethod().
String CraftingManagerAdapter::generateSerial ()
Definition at line 466 of file CraftingManager.cpp.
Referenced by invokeMethod().
DraftSchematic * CraftingManagerAdapter::getSchematic (unsigned int schematicID)
Definition at line 442 of file CraftingManager.cpp.
Referenced by invokeMethod().
void CraftingManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 382 of file CraftingManager.cpp.
References allowManufactureSchematic(), calculateAssemblySuccess(), calculateExperimentationFailureRate(), calculateExperimentationSuccess(), checkBioSkillMods(), generateSerial(), getSchematic(), RPC_ALLOWMANUFACTURESCHEMATIC__MANUFACTURESCHEMATIC_, RPC_CALCULATEASSEMBLYSUCCESS__CREATUREOBJECT_DRAFTSCHEMATIC_FLOAT_, RPC_CALCULATEEXPERIMENTATIONFAILURERATE__CREATUREOBJECT_MANUFACTURESCHEMATIC_INT_, RPC_CALCULATEEXPERIMENTATIONSUCCESS__CREATUREOBJECT_DRAFTSCHEMATIC_FLOAT_, RPC_CHECKBIOSKILLMODS__STRING_, RPC_GENERATESERIAL__, RPC_GETSCHEMATIC__INT_, RPC_SENDDRAFTSLOTSTO__CREATUREOBJECT_INT_, RPC_SENDRESOURCEWEIGHTSTO__CREATUREOBJECT_INT_, RPC_SETINITIALCRAFTINGVALUES__TANGIBLEOBJECT_MANUFACTURESCHEMATIC_INT_, sendDraftSlotsTo(), sendResourceWeightsTo(), and setInitialCraftingValues().
void CraftingManagerAdapter::sendDraftSlotsTo (CreatureObject * player, unsigned int schematicID)
Definition at line 446 of file CraftingManager.cpp.
Referenced by invokeMethod().
void CraftingManagerAdapter::sendResourceWeightsTo (CreatureObject * player, unsigned int schematicID)
Definition at line 450 of file CraftingManager.cpp.
Referenced by invokeMethod().
void CraftingManagerAdapter::setInitialCraftingValues (TangibleObject * prototype, ManufactureSchematic * manufactureSchematic, int assemblySuccess)
Definition at line 474 of file CraftingManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/CraftingManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/CraftingManager.cpp