Core3: server::zone::objects::player::sessions::ImageDesignPositionObserverImplementation Class Reference
server::zone::objects::player::sessions::ImageDesignPositionObserverImplementation Class Reference
#include <ImageDesignPositionObserver.h>
Public Member Functions
ImageDesignPositionObserverImplementation (ImageDesignSession *designSession)
ImageDesignPositionObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const ImageDesignPositionObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< ImageDesignPositionObserver * > _this
Protected Member Functions
virtual ~ImageDesignPositionObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
ManagedWeakReference
< ImageDesignSession * > session
Friends
class ImageDesignPositionObserver
Detailed Description
Definition at line 77 of file ImageDesignPositionObserver.h.
Constructor & Destructor Documentation
ImageDesignPositionObserverImplementation::ImageDesignPositionObserverImplementation (ImageDesignSession * designSession)
Definition at line 192 of file ImageDesignPositionObserver.cpp.
References _initializeImplementation(), ObserverType::IMAGEDESIGNPOSITION, and session.
ImageDesignPositionObserverImplementation::ImageDesignPositionObserverImplementation (DummyConstructorParameter * param)
Definition at line 66 of file ImageDesignPositionObserver.cpp.
References _initializeImplementation().
ImageDesignPositionObserverImplementation::~ImageDesignPositionObserverImplementation () protected virtual
Definition at line 71 of file ImageDesignPositionObserver.cpp.
Member Function Documentation
DistributedObjectStub * ImageDesignPositionObserverImplementation::_getStub ()
Definition at line 91 of file ImageDesignPositionObserver.cpp.
References _this.
void ImageDesignPositionObserverImplementation::_initializeImplementation () protected
Definition at line 78 of file ImageDesignPositionObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ImageDesignPositionObserverImplementation().
void ImageDesignPositionObserverImplementation::_serializationHelperMethod () protected
Definition at line 127 of file ImageDesignPositionObserver.cpp.
Referenced by _initializeImplementation().
void ImageDesignPositionObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 86 of file ImageDesignPositionObserver.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::ImageDesignPositionObserver::ImageDesignPositionObserver().
void ImageDesignPositionObserverImplementation::finalize () protected
Definition at line 75 of file ImageDesignPositionObserver.cpp.
void ImageDesignPositionObserverImplementation::lock (bool doLock = true) protected
Definition at line 99 of file ImageDesignPositionObserver.cpp.
References _this.
void ImageDesignPositionObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 103 of file ImageDesignPositionObserver.cpp.
References _this.
int ImageDesignPositionObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 49 of file ImageDesignPositionObserverImplementation.cpp.
References server::zone::objects::scene::SceneObject::getParentRecursively(), ObserverEventType::POSITIONCHANGED, SceneObjectType::SALONBUILDING, and session.
Referenced by server::zone::objects::player::sessions::ImageDesignPositionObserver::notifyObserverEvent().
ImageDesignPositionObserverImplementation::operator const ImageDesignPositionObserver * ()
Definition at line 95 of file ImageDesignPositionObserver.cpp.
void ImageDesignPositionObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 134 of file ImageDesignPositionObserver.cpp.
References readObjectMember().
bool ImageDesignPositionObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 153 of file ImageDesignPositionObserver.cpp.
References session.
Referenced by readObject().
void ImageDesignPositionObserverImplementation::rlock (bool doLock = true) protected
Definition at line 107 of file ImageDesignPositionObserver.cpp.
References _this.
void ImageDesignPositionObserverImplementation::runlock (bool doLock = true) protected
Definition at line 123 of file ImageDesignPositionObserver.cpp.
References _this.
void ImageDesignPositionObserverImplementation::unlock (bool doLock = true) protected
Definition at line 119 of file ImageDesignPositionObserver.cpp.
References _this.
void ImageDesignPositionObserverImplementation::wlock (bool doLock = true) protected
Definition at line 111 of file ImageDesignPositionObserver.cpp.
References _this.
void ImageDesignPositionObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 115 of file ImageDesignPositionObserver.cpp.
References _this.
void ImageDesignPositionObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 167 of file ImageDesignPositionObserver.cpp.
References writeObjectMembers().
int ImageDesignPositionObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 174 of file ImageDesignPositionObserver.cpp.
References session.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ImageDesignPositionObserver friend
Definition at line 121 of file ImageDesignPositionObserver.h.
Member Data Documentation
WeakReference<ImageDesignPositionObserver*> server::zone::objects::player::sessions::ImageDesignPositionObserverImplementation::_this
Definition at line 87 of file ImageDesignPositionObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<ImageDesignSession* > server::zone::objects::player::sessions::ImageDesignPositionObserverImplementation::session private
Definition at line 78 of file ImageDesignPositionObserver.h.
Referenced by ImageDesignPositionObserverImplementation(), notifyObserverEvent(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignPositionObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignPositionObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignPositionObserverImplementation.cpp