Core3: server::login::LoginPacketHandler Class Reference
server::login::LoginPacketHandler Class Reference
#include <LoginPacketHandler.h>
Public Member Functions
LoginPacketHandler ()
LoginPacketHandler (const String &s, LoginProcessServerImplementation *serv)
~LoginPacketHandler ()
void handleMessage (Message *pack)
void handleClientPermissionsMessage (Message *pack)
void handleSelectCharacter (Message *pack)
void handleCmdSceneReady (Message *packet)
void handleLoginClientID (LoginClient *client, Message *packet)
void handleDeleteCharacterMessage (LoginClient *client, Message *pack)
Private Attributes
LoginProcessServerImplementation * processServer
ManagedReference< LoginServer * > server
Detailed Description
Definition at line 58 of file LoginPacketHandler.h.
Constructor & Destructor Documentation
server::login::LoginPacketHandler::LoginPacketHandler () inline
Definition at line 64 of file LoginPacketHandler.h.
References server.
LoginPacketHandler::LoginPacketHandler (const String & s, LoginProcessServerImplementation * serv)
Definition at line 55 of file LoginPacketHandler.cpp.
References server::login::LoginProcessServerImplementation::getLoginServer(), processServer, and server.
server::login::LoginPacketHandler::~LoginPacketHandler () inline
Definition at line 70 of file LoginPacketHandler.h.
Member Function Documentation
void server::login::LoginPacketHandler::handleClientPermissionsMessage (Message * pack)
void server::login::LoginPacketHandler::handleCmdSceneReady (Message * packet)
void LoginPacketHandler::handleDeleteCharacterMessage (LoginClient * client, Message * pack)
Definition at line 110 of file LoginPacketHandler.cpp.
References server::login::LoginClient::getAccountID(), server::login::LoginClient::hasAccount(), ServerDatabase::instance(), and server::login::LoginClient::sendMessage().
Referenced by handleMessage().
void LoginPacketHandler::handleLoginClientID (LoginClient * client, Message * packet)
Definition at line 105 of file LoginPacketHandler.cpp.
References server::login::account::AccountManager::loginAccount(), and server.
Referenced by handleMessage().
void LoginPacketHandler::handleMessage (Message * pack)
Definition at line 66 of file LoginPacketHandler.cpp.
References handleDeleteCharacterMessage(), handleLoginClientID(), and server.
Referenced by server::login::LoginMessageProcessorTask::run().
void server::login::LoginPacketHandler::handleSelectCharacter (Message * pack)
Member Data Documentation
LoginProcessServerImplementation* server::login::LoginPacketHandler::processServer private
Definition at line 59 of file LoginPacketHandler.h.
Referenced by LoginPacketHandler().
ManagedReference<LoginServer*> server::login::LoginPacketHandler::server private
Definition at line 60 of file LoginPacketHandler.h.
Referenced by handleLoginClientID(), handleMessage(), and LoginPacketHandler().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginPacketHandler.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginPacketHandler.cpp