Core3: InstallationObjectDeltaMessage7 Class Reference
InstallationObjectDeltaMessage7 Class Reference
#include <InstallationObjectDeltaMessage7.h>
Public Member Functions
InstallationObjectDeltaMessage7 (InstallationObject *ins)
void updateExtractionRate (float rate)
void setNoHopperUpdate ()
void updateOperating (bool state)
void updateHopper ()
void updateHopperSize (float size)
void updateActiveResourceSpawn (uint64 id)
Public Member Functions inherited from DeltaMessage
DeltaMessage (uint64 oid, uint32 name, uint8 type)
uint32 generateRandomObjectCRC ()
void startUpdate (uint16 type)
void addByteUpdate (uint16 type, uint8 value)
void addShortUpdate (uint16 type, uint16 value)
void addIntUpdate (uint16 type, uint32 value)
void addLongUpdate (uint16 type, uint64 value)
void addFloatUpdate (uint16 type, float value)
void addAsciiUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const UnicodeString &val)
void startList (uint32 cnt, uint32 updcnt)
void addListIntElement (uint16 index, uint32 value)
void addListFloatElement (uint16 index, float value)
void addListLongElement (uint16 index, uint64 value)
void addListAsciiElement (const String &value)
void removeListIntElement (uint16 index, uint32 value)
void removeListFloatElement (uint16 index, float value)
void removeListLongElement (uint16 index, uint64 value)
void removeListLongElement (uint16 index)
void removeListAsciiElement (const String &value)
void close ()
Private Attributes
InstallationObject * inso
Detailed Description
Definition at line 53 of file InstallationObjectDeltaMessage7.h.
Constructor & Destructor Documentation
InstallationObjectDeltaMessage7::InstallationObjectDeltaMessage7 (InstallationObject * ins) inline
Definition at line 57 of file InstallationObjectDeltaMessage7.h.
References inso.
Member Function Documentation
void InstallationObjectDeltaMessage7::setNoHopperUpdate () inline
Definition at line 66 of file InstallationObjectDeltaMessage7.h.
References DeltaMessage::addByteUpdate().
void InstallationObjectDeltaMessage7::updateActiveResourceSpawn (uint64 id) inline
Definition at line 82 of file InstallationObjectDeltaMessage7.h.
References DeltaMessage::addLongUpdate().
Referenced by server::zone::objects::installation::InstallationObjectImplementation::changeActiveResourceID(), and server::zone::objects::installation::InstallationObjectImplementation::clearResourceHopper().
void InstallationObjectDeltaMessage7::updateExtractionRate (float rate) inline
Definition at line 62 of file InstallationObjectDeltaMessage7.h.
References DeltaMessage::addFloatUpdate().
Referenced by server::zone::objects::installation::InstallationObjectImplementation::changeActiveResourceID(), server::zone::objects::installation::InstallationObjectImplementation::clearResourceHopper(), server::zone::objects::installation::InstallationObjectImplementation::setActiveResource(), server::zone::objects::installation::InstallationObjectImplementation::setOperating(), and server::zone::objects::installation::InstallationObjectImplementation::updateResourceContainerQuantity().
void InstallationObjectDeltaMessage7::updateHopper () inline
Definition at line 74 of file InstallationObjectDeltaMessage7.h.
References DeltaMessage::addByteUpdate().
Referenced by server::zone::objects::installation::InstallationObjectImplementation::addResourceToHopper(), server::zone::objects::installation::InstallationObjectImplementation::clearResourceHopper(), server::zone::objects::installation::InstallationObjectImplementation::setActiveResource(), and server::zone::objects::installation::InstallationObjectImplementation::updateResourceContainerQuantity().
void InstallationObjectDeltaMessage7::updateHopperSize (float size) inline
Definition at line 78 of file InstallationObjectDeltaMessage7.h.
References DeltaMessage::addFloatUpdate().
Referenced by server::zone::objects::installation::InstallationObjectImplementation::clearResourceHopper(), server::zone::objects::installation::InstallationObjectImplementation::setActiveResource(), and server::zone::objects::installation::InstallationObjectImplementation::updateResourceContainerQuantity().
void InstallationObjectDeltaMessage7::updateOperating (bool state) inline
Definition at line 70 of file InstallationObjectDeltaMessage7.h.
References DeltaMessage::addByteUpdate().
Referenced by server::zone::objects::installation::InstallationObjectImplementation::setOperating().
Member Data Documentation
InstallationObject* InstallationObjectDeltaMessage7::inso private
Definition at line 54 of file InstallationObjectDeltaMessage7.h.
Referenced by InstallationObjectDeltaMessage7().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/installation/InstallationObjectDeltaMessage7.h