Core3: MinefieldMenuComponent Class Reference
MinefieldMenuComponent Class Reference
#include <MinefieldMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 14 of file MinefieldMenuComponent.h.
Member Function Documentation
void MinefieldMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from ObjectMenuComponent.
Definition at line 17 of file MinefieldMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::ZoneServer::getObject(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::scene::SceneObject::isMinefield(), and CreatureFlag::OVERT.
int MinefieldMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from ObjectMenuComponent.
Definition at line 56 of file MinefieldMenuComponent.cpp.
References server::zone::Zone::getGCWManager(), server::zone::objects::scene::SceneObject::getZone(), ObserverEventType::OPENCONTAINER, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/MinefieldMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/MinefieldMenuComponent.cpp