Core3: server::zone::objects::player::sui::SuiBox Class Reference
server::zone::objects::player::sui::SuiBox Class Reference
#include <SuiBox.h>
Public Member Functions
SuiBox (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
void initialize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateMessage ()
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
bool isInputBox ()
bool isListBox ()
bool isMessageBox ()
bool isTransferBox ()
bool isBankTransferBox ()
bool isSlicingBox ()
bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Protected Member Functions
SuiBox (DummyConstructorParameter *param)
virtual ~SuiBox ()
Friends
class SuiBoxHelper
Detailed Description
Definition at line 88 of file SuiBox.h.
Constructor & Destructor Documentation
SuiBox::SuiBox (CreatureObject * play, unsigned int windowtype, unsigned int boxtype)
Definition at line 21 of file SuiBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_setStub().
SuiBox::SuiBox (DummyConstructorParameter * param) protected
Definition at line 28 of file SuiBox.cpp.
SuiBox::~SuiBox () protected virtual
Definition at line 32 of file SuiBox.cpp.
Member Function Documentation
DistributedObjectServant * SuiBox::_getImplementation ()
Definition at line 549 of file SuiBox.cpp.
Referenced by addHeader(), addSetting(), clearOptions(), compareTo(), generateBody(), generateCloseMessage(), generateFooter(), generateHeader(), generateMessage(), getBoxID(), getCallback(), getPlayer(), getPromptTitle(), getUsingObject(), getWindowType(), hasGeneratedMessage(), initialize(), initializeTransientMembers(), isBankTransferBox(), isCharacterBuilderBox(), isColorPicker(), isInputBox(), isListBox(), isMessageBox(), isSlicingBox(), isTransferBox(), setBoxType(), setCallback(), setCancelButton(), setForceCloseDisabled(), setForceCloseDistance(), setHandlerText(), setOkButton(), setOtherButton(), setPromptText(), setPromptTitle(), setUsingObject(), and setWindowType().
DistributedObjectServant * SuiBox::_getImplementationForRead ()
Definition at line 555 of file SuiBox.cpp.
void SuiBox::_setImplementation (DistributedObjectServant * servant)
Definition at line 559 of file SuiBox.cpp.
void SuiBox::addHeader (const String & variable, const String & type)
Use to add a UI-Header that will eventually be included in the UI generation. See trac documentation of SuiCreatePageMessage for when to use Variables are concated into a string and placed in a vector (headerSets) of all the header settings for the SuiBoxImplementation object. Each string separates variables with a tilde (~) character.
Parameters
variable UI Variable to declare header for
type Data type of the UI variable being declared
Definition at line 149 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::addHeader(), and RPC_ADDHEADER__STRING_STRING_.
void SuiBox::addSetting (const String & optType, const String & variable, const String & setting, const String & value)
Use to add a UI-body option that will be included in UI generation See trac documentation of SuiCreatePageMessage for when to use Variables are concated into a string and placed in a vector (optionSets) of all the body settings for the SuiBoxImplementation object. Each string separates variables with a tilde (~) character.
Parameters
optType Type of setting to add. See packet docs for info
variable UI Classpath in the script to access
setting SWG UI setting to modify
value The value of the setting being modified
Definition at line 132 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::addSetting(), and RPC_ADDSETTING__STRING_STRING_STRING_STRING_.
void SuiBox::clearOptions ()
Definition at line 164 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::clearOptions(), and RPC_CLEAROPTIONS__.
int SuiBox::compareTo (SuiBox * obj)
Definition at line 177 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::compareTo(), and RPC_COMPARETO__SUIBOX_.
void SuiBox::generateBody (SuiCreatePageMessage * message)
Call after all Body Settings have been added with addSetting() and the header has been generated Generates the UI-Body of the packet, SuiCreatePageMessage, based on the optionSets vector. If you are reusing the SuiBox and rebuilding with different variables, make sure you reset the object with clearOptions()
See Also
addSetting(), clearOptions()
Definition at line 77 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::generateBody(), and RPC_GENERATEBODY__SUICREATEPAGEMESSAGE_.
BaseMessage * SuiBox::generateCloseMessage ()
Use to close the UI object on the client. Sends the SuiForceClosePage packet to the client.
Definition at line 119 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::generateCloseMessage(), and RPC_GENERATECLOSEMESSAGE__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::removeSuiBox(), and GamblingSlotPayoutSuiCallback::run().
void SuiBox::generateFooter (SuiCreatePageMessage * message, int type = 0)
Call after generating both the header and body. Footer of SuiCreatePageMessage is largely unknown. Subject to change based on research. See trac
Parameters
type Type of footer to place into packet
Definition at line 91 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::generateFooter(), and RPC_GENERATEFOOTER__SUICREATEPAGEMESSAGE_INT_.
void SuiBox::generateHeader (SuiCreatePageMessage * message)
Call after all Header settings have been added with addHeader() Generates the UI-Header of the packet, SuiCreatePageMessage, based on the headerSets vector. If you are reusing the SuiBox and rebuilding with different variables, make sure you reset the object with clearOptions()
See Also
addHeader(), clearOptions()
Definition at line 63 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::generateHeader(), and RPC_GENERATEHEADER__SUICREATEPAGEMESSAGE_.
BaseMessage * SuiBox::generateMessage ()
Definition at line 106 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::generateMessage(), and RPC_GENERATEMESSAGE__.
Referenced by DeleteAllItemsSuiCallback::run(), GuildCreateAbbrevResponseSuiCallback::run(), and GuildCreateNameResponseSuiCallback::run().
unsigned int SuiBox::getBoxID ()
Definition at line 478 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::getBoxID(), and RPC_GETBOXID__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addSuiBox(), server::zone::objects::player::sui::SuiBoxImplementation::compareTo(), server::zone::managers::sui::SuiManager::handleFishingAction(), server::zone::managers::sui::SuiManager::handleStartDancing(), server::zone::managers::sui::SuiManager::handleStartMusic(), and server::zone::objects::player::PlayerObjectImplementation::removeSuiBoxType().
SuiCallback * SuiBox::getCallback ()
Definition at line 540 of file SuiBox.cpp.
References _getImplementation(), and server::zone::objects::player::sui::SuiBoxImplementation::getCallback().
ManagedWeakReference< CreatureObject * > SuiBox::getPlayer ()
Definition at line 465 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::getPlayer(), and RPC_GETPLAYER__.
String SuiBox::getPromptTitle ()
Definition at line 232 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::getPromptTitle(), and RPC_GETPROMPTTITLE__.
ManagedWeakReference< SceneObject * > SuiBox::getUsingObject ()
Definition at line 504 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::getUsingObject(), and RPC_GETUSINGOBJECT__.
Referenced by InsertSchematicSuiCallback::handleInsertFactorySchem2(), InsertSchematicSuiCallback::handleInsertFactorySchem3(), server::zone::managers::sui::SuiManager::handleSetObjectName(), DelegateSuiCallback::run(), GuildTransferLotsSuiCallback::run(), DestroyCommandSuiCallback::run(), GuildTransferLeadershipSuiCallback::run(), StructureStatusSuiCallback::run(), GuildTransferLeaderAckSuiCallback::run(), FindLostItemsSuiCallback::run(), FindSessionSuiCallback::run(), SlicingSessionSuiCallback::run(), GuildSponsorVerifySuiCallback::run(), GuildCreateAbbrevResponseSuiCallback::run(), DeleteAllItemsConfirmSuiCallback::run(), SurveyToolApproveRadioactiveSuiCallback::run(), NameStructureSuiCallback::run(), GuildTitleResponseSuiCallback::run(), HQDefenseStatusSuiCallback::run(), RenameVendorSuiCallback::run(), InsuranceAllConfirmSuiCallback::run(), GuildMemberListSuiCallback::run(), LightsaberCrystalTuneSuiCallback::run(), RegisterVendorSuiCallback::run(), GuildMemberOptionsSuiCallback::run(), GuildMemberPermissionsResponseSuiCallback::run(), StructurePayAccessFeeSuiCallback::run(), StructureSetAccessDurationSuiCallback::run(), StructureSetAccessFeeSuiCallback::run(), VendorMaintSuiCallback::run(), GuildSponsoredListSuiCallback::run(), SurveyToolSetRangeSuiCallback::run(), StructurePayMaintenanceSuiCallback::run(), GuildSponsorSuiCallback::run(), DestroyVendorSuiCallback::run(), GuildCreateNameResponseSuiCallback::run(), GuildDisbandSuiCallback::run(), HQSendResetVerificationSuiCallback::run(), PlayerTeachConfirmSuiCallback::run(), ResourceDeedSuiCallback::run(), GuildMemberRemoveSuiCallback::run(), CloningStoreSuiCallback::run(), JamUplinkSuiCallback::run(), InsertPowerSuiCallback::run(), JunkDealerSellListSuiCallback::run(), SelectTurretDonationSuiCallback::run(), RemoveDefenseSuiCallback::run(), OverrideTerminalSuiCallback::run(), PowerRegulatorSuiCallback::run(), GuildAddEnemySuiCallback::run(), CustomVehicleSuiCallback::run(), DonateDefenseSuiCallback::run(), CityManageMilitiaSuiCallback::run(), CityAdjustTaxSuiCallback::run(), StructurePayUncondemnMaintenanceSuiCallback::run(), PlayerManagementSessionSuiCallback::runAccountInfo(), PlayerManagementSessionSuiCallback::runDurationCallback(), PlayerManagementSessionSuiCallback::runReasonCallback(), PlayerManagementSessionSuiCallback::runSummaryCallback(), and PlayerManagementSessionSuiCallback::runUnbanSummaryCallback().
int SuiBox::getWindowType ()
Definition at line 491 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::getWindowType(), and RPC_GETWINDOWTYPE__.
Referenced by VendorMaintSuiCallback::run(), InsertSchematicSuiCallback::run(), AdBarkingPhraseSuiCallback::run(), and PlayerManagementSessionSuiCallback::run().
bool SuiBox::hasGeneratedMessage ()
Definition at line 191 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::hasGeneratedMessage(), and RPC_HASGENERATEDMESSAGE__.
void SuiBox::initialize ()
Definition at line 37 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::initialize(), and RPC_INITIALIZE__.
void SuiBox::initializeTransientMembers ()
Definition at line 50 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
bool SuiBox::isBankTransferBox ()
Definition at line 341 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::isBankTransferBox(), and RPC_ISBANKTRANSFERBOX__.
Referenced by server::zone::managers::sui::SuiManager::handleBankTransfer(), and BankTerminalSuiCallback::run().
bool SuiBox::isCharacterBuilderBox ()
Definition at line 367 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::isCharacterBuilderBox(), and RPC_ISCHARACTERBUILDERBOX__.
Referenced by server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem().
bool SuiBox::isColorPicker ()
Definition at line 380 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::isColorPicker(), and RPC_ISCOLORPICKER__.
bool SuiBox::isInputBox ()
Definition at line 289 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::isInputBox(), and RPC_ISINPUTBOX__.
Referenced by server::zone::managers::sui::SuiManager::handleSetObjectName(), GuildTransferLeadershipSuiCallback::run(), RenameVendorSuiCallback::run(), StructureSetAccessDurationSuiCallback::run(), StructureSetAccessFeeSuiCallback::run(), NameStructureSuiCallback::run(), CityTreasuryWithdrawalReasonSuiCallback::run(), NameVendorSuiCallback::run(), VendorMaintSuiCallback::run(), GuildTitleResponseSuiCallback::run(), GuildCreateAbbrevResponseSuiCallback::run(), GuildCreateNameResponseSuiCallback::run(), GuildSponsorSuiCallback::run(), GuildWarEnemyNameSuiCallback::run(), CityAddMilitiaMemberSuiCallback::run(), PlaceCityHallSuiCallback::run(), CitySetTaxSuiCallback::run(), PlayerManagementSessionSuiCallback::runDurationCallback(), and PlayerManagementSessionSuiCallback::runReasonCallback().
bool SuiBox::isListBox ()
Definition at line 302 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::isListBox(), and RPC_ISLISTBOX__.
Referenced by server::zone::managers::sui::SuiManager::handleConsentBox(), InsertSchematicSuiCallback::handleInsertFactorySchem2(), InsertSchematicSuiCallback::handleInsertFactorySchem3(), server::zone::managers::sui::SuiManager::handleStartDancing(), server::zone::managers::sui::SuiManager::handleStartMusic(), StructureStatusSuiCallback::run(), TicketSelectionSuiCallback::run(), PlayerTeachSuiCallback::run(), SlicingSessionSuiCallback::run(), RevokeConsentSuiCallback::run(), ListGuildsResponseSuiCallback::run(), FindSessionSuiCallback::run(), RegisterVendorSuiCallback::run(), CreateVendorSuiCallback::run(), GuildMemberListSuiCallback::run(), GuildMemberOptionsSuiCallback::run(), GuildMemberPermissionsResponseSuiCallback::run(), CitySpecializationSuiCallback::run(), GuildSponsoredListSuiCallback::run(), HQDefenseStatusSuiCallback::run(), ResourceDeedSuiCallback::run(), InsuranceMenuSuiCallback::run(), JamUplinkSuiCallback::run(), GamblingRouletteSuiCallback::run(), GamblingSlotPayoutSuiCallback::run(), JunkDealerSellListSuiCallback::run(), SelectTurretDonationSuiCallback::run(), GamblingSlotSuiCallback::run(), RepairVehicleSuiCallback::run(), RemoveDefenseSuiCallback::run(), AreaTrackSuiCallback::run(), GuildAddEnemySuiCallback::run(), PowerRegulatorSuiCallback::run(), OverrideTerminalSuiCallback::run(), DonateDefenseSuiCallback::run(), CustomVehicleSuiCallback::run(), CloningRequestSuiCallback::run(), CityManageMilitiaSuiCallback::run(), CityAdjustTaxSuiCallback::run(), and CityMayoralVoteSuiCallback::run().
bool SuiBox::isMessageBox ()
Definition at line 315 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::isMessageBox(), and RPC_ISMESSAGEBOX__.
Referenced by DestroyCommandSuiCallback::run(), GuildTransferLotsSuiCallback::run(), DeleteAllItemsSuiCallback::run(), FindLostItemsSuiCallback::run(), LightsaberCrystalTuneSuiCallback::run(), StructurePayAccessFeeSuiCallback::run(), DeleteAllItemsConfirmSuiCallback::run(), GuildSponsorVerifySuiCallback::run(), InsuranceAllConfirmSuiCallback::run(), CitySpecializationConfirmSuiCallback::run(), GuildDisbandSuiCallback::run(), GuildMemberRemoveSuiCallback::run(), DestroyVendorSuiCallback::run(), HQSendResetVerificationSuiCallback::run(), CloningStoreSuiCallback::run(), TipCommandSuiCallback::run(), and StructurePayUncondemnMaintenanceSuiCallback::run().
bool SuiBox::isSlicingBox ()
Definition at line 354 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::isSlicingBox(), and RPC_ISSLICINGBOX__.
bool SuiBox::isTransferBox ()
Definition at line 328 of file SuiBox.cpp.
References _getImplementation(), server::zone::objects::player::sui::SuiBoxImplementation::isTransferBox(), and RPC_ISTRANSFERBOX__.
Referenced by DelegateSuiCallback::run(), CityTreasuryWithdrawalSuiCallback::run(), StructurePayMaintenanceSuiCallback::run(), InsertPowerSuiCallback::run(), and CityTreasuryDepositSuiCallback::run().
void SuiBox::setBoxType (int type)
Definition at line 275 of file SuiBox.cpp.
References _getImplementation(), RPC_SETBOXTYPE__INT_, and server::zone::objects::player::sui::SuiBoxImplementation::setBoxType().
void SuiBox::setCallback (SuiCallback * callback)
Definition at line 531 of file SuiBox.cpp.
References _getImplementation(), and server::zone::objects::player::sui::SuiBoxImplementation::setCallback().
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::createVendor(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::handleVendorSelection(), server::zone::managers::vendor::VendorManager::promptDestroyVendor(), server::zone::managers::vendor::VendorManager::promptRenameVendorTo(), DeleteAllItemsSuiCallback::run(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::sendConfirmationBox(), and server::zone::managers::vendor::VendorManager::sendRegisterVendorTo().
void SuiBox::setCancelButton (bool value, const String & cancelText)
Definition at line 393 of file SuiBox.cpp.
References _getImplementation(), RPC_SETCANCELBUTTON__BOOL_STRING_, and server::zone::objects::player::sui::SuiBoxImplementation::setCancelButton().
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::createVendor(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSlice(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::handleVendorSelection(), server::zone::managers::vendor::VendorManager::promptDestroyVendor(), server::zone::managers::vendor::VendorManager::promptRenameVendorTo(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::sendConfirmationBox(), and server::zone::managers::vendor::VendorManager::sendRegisterVendorTo().
void SuiBox::setForceCloseDisabled ()
Definition at line 452 of file SuiBox.cpp.
References _getImplementation(), RPC_SETFORCECLOSEDISABLED__, and server::zone::objects::player::sui::SuiBoxImplementation::setForceCloseDisabled().
void SuiBox::setForceCloseDistance (float dist)
Definition at line 438 of file SuiBox.cpp.
References _getImplementation(), RPC_SETFORCECLOSEDISTANCE__FLOAT_, and server::zone::objects::player::sui::SuiBoxImplementation::setForceCloseDistance().
void SuiBox::setHandlerText (const String & text)
Definition at line 247 of file SuiBox.cpp.
References _getImplementation(), RPC_SETHANDLERTEXT__STRING_, and server::zone::objects::player::sui::SuiBoxImplementation::setHandlerText().
void SuiBox::setOkButton (bool value, const String & okText)
Definition at line 423 of file SuiBox.cpp.
References _getImplementation(), RPC_SETOKBUTTON__BOOL_STRING_, and server::zone::objects::player::sui::SuiBoxImplementation::setOkButton().
Referenced by server::zone::managers::vendor::VendorManager::promptDestroyVendor(), and server::zone::objects::player::sessions::CitySpecializationSessionImplementation::sendConfirmationBox().
void SuiBox::setOtherButton (bool value, const String & backText)
Definition at line 408 of file SuiBox.cpp.
References _getImplementation(), RPC_SETOTHERBUTTON__BOOL_STRING_, and server::zone::objects::player::sui::SuiBoxImplementation::setOtherButton().
void SuiBox::setPromptText (const String & name)
Definition at line 218 of file SuiBox.cpp.
References _getImplementation(), RPC_SETPROMPTTEXT__STRING_, and server::zone::objects::player::sui::SuiBoxImplementation::setPromptText().
Referenced by server::zone::objects::resource::ResourceSpawnImplementation::addStatsToDeedListBox(), ResourceTreeNode::addToSuiListBox(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::createVendor(), server::zone::objects::player::sessions::SlicingSessionImplementation::generateSliceMenu(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSlice(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::handleVendorSelection(), server::zone::managers::vendor::VendorManager::promptDestroyVendor(), server::zone::managers::vendor::VendorManager::promptRenameVendorTo(), DeleteAllItemsSuiCallback::run(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::sendConfirmationBox(), and server::zone::managers::vendor::VendorManager::sendRegisterVendorTo().
void SuiBox::setPromptTitle (const String & name)
Definition at line 204 of file SuiBox.cpp.
References _getImplementation(), RPC_SETPROMPTTITLE__STRING_, and server::zone::objects::player::sui::SuiBoxImplementation::setPromptTitle().
Referenced by server::zone::objects::resource::ResourceSpawnImplementation::addStatsToDeedListBox(), ResourceTreeNode::addToSuiListBox(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::createVendor(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::handleVendorSelection(), server::zone::managers::vendor::VendorManager::promptDestroyVendor(), server::zone::managers::vendor::VendorManager::promptRenameVendorTo(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::sendConfirmationBox(), and server::zone::managers::vendor::VendorManager::sendRegisterVendorTo().
void SuiBox::setUsingObject (SceneObject * object)
Definition at line 517 of file SuiBox.cpp.
References _getImplementation(), RPC_SETUSINGOBJECT__SCENEOBJECT_, and server::zone::objects::player::sui::SuiBoxImplementation::setUsingObject().
Referenced by server::zone::managers::vendor::VendorManager::promptDestroyVendor(), server::zone::managers::vendor::VendorManager::promptRenameVendorTo(), and server::zone::managers::vendor::VendorManager::sendRegisterVendorTo().
void SuiBox::setWindowType (unsigned int type)
Definition at line 261 of file SuiBox.cpp.
References _getImplementation(), RPC_SETWINDOWTYPE__INT_, and server::zone::objects::player::sui::SuiBoxImplementation::setWindowType().
Friends And Related Function Documentation
friend class SuiBoxHelper friend
Definition at line 237 of file SuiBox.h.
Member Data Documentation
const int server::zone::objects::player::sui::SuiBox::BANKTIPCONFIRMBOX = 10 static
Definition at line 102 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBox::BANKTRANSFERBOX = 5 static
Definition at line 100 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBox::COLORPICKER = 4 static
Definition at line 98 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBox::INPUTBOX = 0 static
Definition at line 90 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBox::KEYPAD = 21 static
Definition at line 106 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBox::LISTBOX = 1 static
Definition at line 92 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBox::MESSAGEBOX = 2 static
Definition at line 94 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBox::SLICINGBOX = 20 static
Definition at line 104 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBox::TRANSFERBOX = 3 static
Definition at line 96 of file SuiBox.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/SuiBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/SuiBox.cpp