Core3: Ability Class Reference
Ability Class Reference
#include <Ability.h>
Public Member Functions
Ability ()
Ability (const String &name)
Ability (const Ability &a)
Ability & operator= (const Ability &a)
int compareTo (const Ability &a)
String & getAbilityName ()
void setAbilityName (const String &name)
bool toBinaryStream (ObjectOutputStream *stream)
Private Attributes
String abilityName
Detailed Description
Definition at line 13 of file Ability.h.
Constructor & Destructor Documentation
Ability::Ability () inline
Definition at line 17 of file Ability.h.
Ability::Ability (const String & name) inline
Definition at line 20 of file Ability.h.
References abilityName.
Ability::Ability (const Ability & a) inline
Definition at line 24 of file Ability.h.
References abilityName.
Member Function Documentation
int Ability::compareTo (const Ability & a) inline
Definition at line 37 of file Ability.h.
References abilityName.
String& Ability::getAbilityName () inline
Definition at line 41 of file Ability.h.
References abilityName.
Referenced by AbilityList::contains(), PlayerInfoCommand::executeCommand(), AbilityList::getStringList(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::initializeSession(), StartDanceCommand::sendAvailableDances(), and StartMusicCommand::sendAvailableSongs().
Ability& Ability::operator= (const Ability & a) inline
Definition at line 28 of file Ability.h.
References abilityName.
void Ability::setAbilityName (const String & name) inline
Definition at line 45 of file Ability.h.
References abilityName.
bool Ability::toBinaryStream (ObjectOutputStream * stream) inline
Definition at line 49 of file Ability.h.
References abilityName.
Referenced by AbilityList::add().
Member Data Documentation
String Ability::abilityName private
Definition at line 14 of file Ability.h.
Referenced by Ability(), compareTo(), getAbilityName(), operator=(), setAbilityName(), and toBinaryStream().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/variables/Ability.h