Core3: LightUpdateTransformWithParentMessage Class Reference
LightUpdateTransformWithParentMessage Class Reference
#include <LightUpdateTransformWithParentMessage.h>
Public Member Functions
LightUpdateTransformWithParentMessage (SceneObject *object)
LightUpdateTransformWithParentMessage (SceneObject *object, float posX, float posZ, float posY, uint64 cellID)
Detailed Description
Definition at line 52 of file LightUpdateTransformWithParentMessage.h.
Constructor & Destructor Documentation
LightUpdateTransformWithParentMessage::LightUpdateTransformWithParentMessage (SceneObject * object) inline
Definition at line 54 of file LightUpdateTransformWithParentMessage.h.
References server::zone::objects::scene::SceneObject::getMovementCounter(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getParentID(), and server::zone::objects::scene::SceneObject::getSpecialDirectionAngle().
LightUpdateTransformWithParentMessage::LightUpdateTransformWithParentMessage (SceneObject * object, float posX, float posZ, float posY, uint64 cellID) inline
Definition at line 78 of file LightUpdateTransformWithParentMessage.h.
References server::zone::objects::scene::SceneObject::getMovementCounter(), server::zone::objects::scene::SceneObject::getObjectID(), and server::zone::objects::scene::SceneObject::getSpecialDirectionAngle().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/scene/LightUpdateTransformWithParentMessage.h