Core3: server::zone::objects::tangible::InstrumentObserver Class Reference
server::zone::objects::tangible::InstrumentObserver Class Reference
#include <InstrumentObserver.h>
Public Member Functions
InstrumentObserver (Instrument *instr)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
InstrumentObserver (DummyConstructorParameter *param)
virtual ~InstrumentObserver ()
Friends
class InstrumentObserverHelper
Detailed Description
Definition at line 65 of file InstrumentObserver.h.
Constructor & Destructor Documentation
InstrumentObserver::InstrumentObserver (Instrument * instr)
Definition at line 17 of file InstrumentObserver.cpp.
References server::zone::objects::tangible::InstrumentObserverImplementation::_setStub().
InstrumentObserver::InstrumentObserver (DummyConstructorParameter * param) protected
Definition at line 24 of file InstrumentObserver.cpp.
InstrumentObserver::~InstrumentObserver () protected virtual
Definition at line 28 of file InstrumentObserver.cpp.
Member Function Documentation
DistributedObjectServant * InstrumentObserver::_getImplementation ()
Definition at line 50 of file InstrumentObserver.cpp.
Referenced by notifyObserverEvent().
DistributedObjectServant * InstrumentObserver::_getImplementationForRead ()
Definition at line 56 of file InstrumentObserver.cpp.
void InstrumentObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 60 of file InstrumentObserver.cpp.
int InstrumentObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 33 of file InstrumentObserver.cpp.
References _getImplementation(), server::zone::objects::tangible::InstrumentObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class InstrumentObserverHelper friend
Definition at line 81 of file InstrumentObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/InstrumentObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/InstrumentObserver.cpp