Core3: TotalHealSelfCommand Class Reference
TotalHealSelfCommand Class Reference
#include <TotalHealSelfCommand.h>
Public Member Functions
TotalHealSelfCommand (const String &name, ZoneProcessServer *server)
void doAnimations (CreatureObject *creature)
void sendWoundMessage (CreatureObject *creature, int healthWound, int actionWound, int mindWound, int strengthWound, int constitutionWound, int quicknessWound, int staminaWound, int focusWound, int willpowerWound)
void sendHealMessage (CreatureObject *creature, int healthDamage, int actionDamage, int mindDamage)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Public Member Functions inherited from server::zone::objects::creature::commands::QueueCommand
QueueCommand (const String &skillname, ZoneProcessServer *serv)
virtual ~QueueCommand ()
bool checkInvalidLocomotions (CreatureObject *creature)
void onStateFail (CreatureObject *creature, uint32 actioncntr)
void onLocomotionFail (CreatureObject *creature, uint32 actioncntr)
virtual String getSyntax () const
virtual void onFail (uint32 actioncntr, CreatureObject *creature, uint32 errorNumber)
virtual void onComplete (uint32 actioncntr, CreatureObject *creature, float commandDuration)
void setInvalidLocomotions (const String &lStr)
void addInvalidLocomotion (int l)
bool checkStateMask (CreatureObject *creature)
virtual float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
void setStateMask (uint64 mask)
void setDefaultTime (float time)
void setTargetType (int num)
void setDisabled (bool state)
void setDisabled (int state)
void setAddToCombatQueue (bool state)
void setAddToCombatQueue (int state)
void setCommandGroup (int val)
void setMaxRange (float r)
void setCharacterAbility (const String &ability)
void setDefaultPriority (const String &priority)
void setDefaultPriority (const int priority)
uint64 getStateMask ()
bool requiresAdmin ()
int getTargetType ()
uint32 getNameCRC ()
float getMaxRange ()
String & getQueueCommandName ()
String & getCharacterAbility ()
float getDefaultTime ()
int getDefaultPriority ()
bool isDisabled ()
bool addToCombatQueue ()
virtual bool isCombatCommand ()
int getSkillModSize ()
int getSkillMod (int index, String &skillMod)
int getCommandGroup ()
void addSkillMod (const String &skillMod, const int value)
bool isWearingArmor (CreatureObject *creo)
virtual void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Protected Attributes
int forceCost
int heal
int healthHealed
int actionHealed
int mindHealed
int healthWoundHealed
int strengthWoundHealed
int constitutionWoundHealed
int actionWoundHealed
int quicknessWoundHealed
int staminaWoundHealed
int mindWoundHealed
int focusWoundHealed
int willpowerWoundHealed
float speed
float range
String effectName
Protected Attributes inherited from server::zone::objects::creature::commands::QueueCommand
ZoneProcessServer * server
String name
uint32 nameCRC
uint64 stateMask
Vector< int > invalidLocomotion
int targetType
int maxRangeToTarget
bool disabled
bool addToQueue
bool admin
uint32 cooldown
float defaultTime
String characterAbility
int defaultPriority
VectorMap< String, int > skillMods
int commandGroup
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::creature::commands::QueueCommand
static const int IMMEDIATE = 0
static const int FRONT = 1
static const int NORMAL = 2
static const int SUCCESS = 0
static const int GENERALERROR = 1
static const int INVALIDLOCOMOTION = 2
static const int INVALIDSTATE = 3
static const int INVALIDTARGET = 4
static const int INVALIDWEAPON = 5
static const int TOOFAR = 6
static const int INSUFFICIENTHAM = 7
static const int INVALIDPARAMETERS = 8
static const int NOPRONE = 9
static const int NOKNEELING = 10
static const int INSUFFICIENTPERMISSION = 11
static const int NOJEDIARMOR = 12
static const int INVALIDSYNTAX = 13
Detailed Description
Definition at line 58 of file TotalHealSelfCommand.h.
Constructor & Destructor Documentation
TotalHealSelfCommand::TotalHealSelfCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 85 of file TotalHealSelfCommand.h.
References actionHealed, actionWoundHealed, constitutionWoundHealed, focusWoundHealed, forceCost, heal, healthHealed, healthWoundHealed, mindHealed, mindWoundHealed, quicknessWoundHealed, speed, staminaWoundHealed, strengthWoundHealed, and willpowerWoundHealed.
Member Function Documentation
void TotalHealSelfCommand::doAnimations (CreatureObject * creature) inline
Definition at line 111 of file TotalHealSelfCommand.h.
References server::zone::objects::creature::CreatureObject::playEffect().
Referenced by doQueueCommand().
int TotalHealSelfCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline virtual
Reimplemented from server::zone::objects::creature::commands::QueueCommand.
Definition at line 177 of file TotalHealSelfCommand.h.
References CreatureAttribute::ACTION, server::zone::objects::creature::CreatureObject::addShockWounds(), CreatureState::BLEEDING, CreatureState::BLINDED, server::zone::objects::creature::commands::QueueCommand::checkInvalidLocomotions(), server::zone::objects::creature::commands::QueueCommand::checkStateMask(), CreatureAttribute::CONSTITUTION, CreatureState::DISEASED, CreatureState::DIZZY, doAnimations(), CreatureAttribute::FOCUS, forceCost, server::zone::objects::creature::commands::QueueCommand::GENERALERROR, server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::getWounds(), server::zone::objects::creature::CreatureObject::hasDamage(), server::zone::objects::creature::CreatureObject::hasState(), heal, server::zone::objects::creature::CreatureObject::healDamage(), server::zone::objects::creature::CreatureObject::healDot(), CreatureAttribute::HEALTH, server::zone::objects::creature::CreatureObject::healWound(), CreatureState::INTIMIDATED, server::zone::objects::creature::commands::QueueCommand::INVALIDLOCOMOTION, server::zone::objects::creature::commands::QueueCommand::INVALIDSTATE, server::zone::objects::creature::commands::QueueCommand::isWearingArmor(), CreatureAttribute::MIND, server::zone::objects::creature::commands::QueueCommand::NOJEDIARMOR, CreatureState::ONFIRE, CreatureState::POISONED, CreatureAttribute::QUICKNESS, server::zone::objects::creature::CreatureObject::removeStateBuff(), sendHealMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), sendWoundMessage(), CreatureAttribute::STAMINA, CreatureAttribute::STRENGTH, CreatureState::STUNNED, server::zone::objects::creature::commands::QueueCommand::SUCCESS, and CreatureAttribute::WILLPOWER.
void TotalHealSelfCommand::sendHealMessage (CreatureObject * creature, int healthDamage, int actionDamage, int mindDamage) inline
Definition at line 152 of file TotalHealSelfCommand.h.
References server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
void TotalHealSelfCommand::sendWoundMessage (CreatureObject * creature, int healthWound, int actionWound, int mindWound, int strengthWound, int constitutionWound, int quicknessWound, int staminaWound, int focusWound, int willpowerWound) inline
Definition at line 116 of file TotalHealSelfCommand.h.
References server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
Member Data Documentation
int TotalHealSelfCommand::actionHealed protected
Definition at line 65 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
int TotalHealSelfCommand::actionWoundHealed protected
Definition at line 72 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
int TotalHealSelfCommand::constitutionWoundHealed protected
Definition at line 70 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
String TotalHealSelfCommand::effectName protected
Definition at line 82 of file TotalHealSelfCommand.h.
int TotalHealSelfCommand::focusWoundHealed protected
Definition at line 77 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
int TotalHealSelfCommand::forceCost protected
Definition at line 61 of file TotalHealSelfCommand.h.
Referenced by doQueueCommand(), and TotalHealSelfCommand().
int TotalHealSelfCommand::heal protected
Definition at line 62 of file TotalHealSelfCommand.h.
Referenced by doQueueCommand(), and TotalHealSelfCommand().
int TotalHealSelfCommand::healthHealed protected
Definition at line 64 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
int TotalHealSelfCommand::healthWoundHealed protected
Definition at line 68 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
int TotalHealSelfCommand::mindHealed protected
Definition at line 66 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
int TotalHealSelfCommand::mindWoundHealed protected
Definition at line 76 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
int TotalHealSelfCommand::quicknessWoundHealed protected
Definition at line 73 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
float TotalHealSelfCommand::range protected
Definition at line 81 of file TotalHealSelfCommand.h.
float TotalHealSelfCommand::speed protected
Definition at line 80 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
int TotalHealSelfCommand::staminaWoundHealed protected
Definition at line 74 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
int TotalHealSelfCommand::strengthWoundHealed protected
Definition at line 69 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
int TotalHealSelfCommand::willpowerWoundHealed protected
Definition at line 78 of file TotalHealSelfCommand.h.
Referenced by TotalHealSelfCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/TotalHealSelfCommand.h