Core3: CmdStartScene Class Reference
CmdStartScene Class Reference
#include <CmdStartScene.h>
Public Member Functions
CmdStartScene (CreatureObject *creo)
Static Public Member Functions
static void parse (Packet *pack)
Detailed Description
Definition at line 58 of file CmdStartScene.h.
Constructor & Destructor Documentation
CmdStartScene::CmdStartScene (CreatureObject * creo) inline
Definition at line 60 of file CmdStartScene.h.
References server::zone::objects::scene::SceneObject::getClientObjectCRC(), server::zone::Zone::getGalacticTime(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getZone(), and server::zone::Zone::getZoneName().
Member Function Documentation
static void CmdStartScene::parse (Packet * pack) inline static
Definition at line 83 of file CmdStartScene.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/zone/CmdStartScene.h