Core3: server::zone::managers::mission::MissionManagerImplementation Class Reference
server::zone::managers::mission::MissionManagerImplementation Class Reference
#include <MissionManager.h>
Public Member Functions
MissionManagerImplementation (ZoneServer *srv, ZoneProcessServer *impl)
MissionManagerImplementation (DummyConstructorParameter *param)
void loadLuaSettings ()
void handleMissionListRequest (MissionTerminal *missionTerminal, CreatureObject *player, int counter)
void handleMissionAccept (MissionTerminal *missionTerminal, MissionObject *mission, CreatureObject *player)
void handleMissionAbort (MissionObject *mission, CreatureObject *player)
void removeMission (MissionObject *mission, CreatureObject *player)
void populateMissionList (MissionTerminal *missionTerminal, CreatureObject *player, int counter)
bool randomGenericDeliverMission (CreatureObject *player, MissionObject *mission, bool inTownMission, const int faction)
void randomizeGenericBountyMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericCraftingMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericDeliverMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericDestroyMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericEntertainerMission (CreatureObject *player, MissionObject *mission, const int faction, const int missionType)
void randomizeGenericHuntingMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericReconMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericSurveyMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeSurveyMission (CreatureObject *player, MissionObject *mission)
void randomizeDestroyMission (CreatureObject *player, MissionObject *mission)
void randomizeBountyMission (CreatureObject *player, MissionObject *mission)
void randomizeDeliverMission (CreatureObject *player, MissionObject *mission)
void randomizeCraftingMission (CreatureObject *player, MissionObject *mission)
void randomizeHuntingMission (CreatureObject *player, MissionObject *mission)
void randomizeReconMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialDestroyMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialDeliverMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialCraftingMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialReconMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelDestroyMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelDeliverMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelCraftingMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelReconMission (CreatureObject *player, MissionObject *mission)
void createMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createSurveyMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createDestroyMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createDeliverMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createEntertainerMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createHuntingMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createReconMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createBountyMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createCraftingMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
NpcSpawnPoint * getRandomFreeNpcSpawnPoint (unsigned const int planetCRC, const float x, const float y, const int spawnType)
void createSpawnPoint (CreatureObject *player, const String &spawnTypes)
LairSpawn * getRandomLairSpawn (CreatureObject *player, const int faction, unsigned int type)
Vector3 getRandomBountyTargetPosition (CreatureObject *player)
Reference< MissionObject * > getBountyHunterMission (CreatureObject *player)
String getDeliveryMissionFileName (const int faction)
int getDeliverMissionNumberOfMissions (const int faction)
int getDeliverMissionSpawnType (const int faction)
void addPlayerToBountyList (unsigned long long targetId, int reward)
void removePlayerFromBountyList (unsigned long long targetId)
void updatePlayerBountyReward (unsigned long long targetId, int reward)
void addBountyHunterToPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
void removeBountyHunterFromPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
BountyTargetListElement * getRandomPlayerBounty (CreatureObject *player)
void completePlayerBounty (unsigned long long targetId, unsigned long long bountyHunter)
void failPlayerBountyMission (unsigned long long bountyHunter)
void allocateMissionNpcs (NpcSpawnPoint *target, NpcSpawnPoint *destination, TerrainManager *terrainManager, CreatureManager *creatureManager)
void freeMissionNpc (NpcSpawnPoint *npc)
void despawnMissionNpc (NpcSpawnPoint *npc)
void deactivateMissions (CreatureObject *player)
operator const MissionManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< MissionManager * > _this
Static Public Attributes
static unsigned const int UNKNOWN_TARGET = 0xB911DA26
Protected Member Functions
virtual ~MissionManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference< ZoneServer * > server
MissionNpcSpawnMap missionNpcSpawnMap
Vector< String > craftingMissionItems
Vector< String > bhTargetZones
VectorMap< unsigned int,
Vector< String > * > bhTargetsAtMissionLevel
VectorMap< unsigned long long,
BountyTargetListElement * > playerBountyList
Mutex playerBountyListMutex
bool enableFactionalCraftingMissions
bool enableFactionalReconMissions
bool enableFactionalEntertainerMissions
Private Member Functions
void generateRandomFactionalDestroyMissionDescription (CreatureObject *player, MissionObject *mission, const String &faction)
Private Attributes
ManagedReference
< ZoneProcessServer * > processor
Friends
class MissionManager
Detailed Description
Definition at line 320 of file MissionManager.h.
Constructor & Destructor Documentation
MissionManagerImplementation::MissionManagerImplementation (ZoneServer * srv, ZoneProcessServer * impl)
Definition at line 1171 of file MissionManager.cpp.
References _initializeImplementation(), enableFactionalCraftingMissions, enableFactionalEntertainerMissions, enableFactionalReconMissions, loadLuaSettings(), missionNpcSpawnMap, playerBountyList, processor, and server.
MissionManagerImplementation::MissionManagerImplementation (DummyConstructorParameter * param)
Definition at line 949 of file MissionManager.cpp.
References _initializeImplementation().
MissionManagerImplementation::~MissionManagerImplementation () protected virtual
Definition at line 954 of file MissionManager.cpp.
Member Function Documentation
DistributedObjectStub * MissionManagerImplementation::_getStub ()
Definition at line 974 of file MissionManager.cpp.
References _this.
void MissionManagerImplementation::_initializeImplementation () protected
Definition at line 961 of file MissionManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by MissionManagerImplementation().
void MissionManagerImplementation::_serializationHelperMethod () protected
Definition at line 1010 of file MissionManager.cpp.
Referenced by _initializeImplementation().
void MissionManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 969 of file MissionManager.cpp.
References _this.
Referenced by server::zone::managers::mission::MissionManager::MissionManager().
void MissionManagerImplementation::addBountyHunterToPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
Definition at line 1661 of file MissionManagerImplementation.cpp.
References playerBountyList, and playerBountyListMutex.
Referenced by server::zone::managers::mission::MissionManager::addBountyHunterToPlayerBounty().
void MissionManagerImplementation::addPlayerToBountyList (unsigned long long targetId, int reward)
Definition at line 1629 of file MissionManagerImplementation.cpp.
References playerBountyList, and playerBountyListMutex.
Referenced by server::zone::managers::mission::MissionManager::addPlayerToBountyList().
void MissionManagerImplementation::allocateMissionNpcs (NpcSpawnPoint * target, NpcSpawnPoint * destination, TerrainManager * terrainManager, CreatureManager * creatureManager)
Definition at line 1755 of file MissionManagerImplementation.cpp.
References server::zone::managers::mission::spawnmaps::NpcSpawnPoint::allocateNpc(), and missionNpcSpawnMap.
Referenced by server::zone::managers::mission::MissionManager::allocateMissionNpcs().
void MissionManagerImplementation::completePlayerBounty (unsigned long long targetId, unsigned long long bountyHunter)
Definition at line 1716 of file MissionManagerImplementation.cpp.
References failPlayerBountyMission(), BountyTargetListElement::getActiveBountyHunters(), playerBountyList, and playerBountyListMutex.
Referenced by server::zone::managers::mission::MissionManager::completePlayerBounty().
void MissionManagerImplementation::createBountyMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 324 of file MissionManagerImplementation.cpp.
References server::zone::objects::mission::MissionObject::setMissionObjective().
Referenced by server::zone::managers::mission::MissionManager::createBountyMissionObjectives(), and createMissionObjectives().
void MissionManagerImplementation::createCraftingMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 236 of file MissionManagerImplementation.cpp.
References craftingMissionItems, enableFactionalCraftingMissions, server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::mission::MissionObject::getFaction(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::mission::MissionObject::getTemplateString1(), server::zone::objects::mission::MissionObject::setMissionObjective(), server::zone::objects::mission::MissionObject::setTargetTemplate(), and server::zone::objects::mission::MissionObject::setTemplateStrings().
Referenced by server::zone::managers::mission::MissionManager::createCraftingMissionObjectives(), and createMissionObjectives().
void MissionManagerImplementation::createDeliverMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 227 of file MissionManagerImplementation.cpp.
References server::zone::objects::mission::MissionObject::setMissionObjective().
Referenced by server::zone::managers::mission::MissionManager::createDeliverMissionObjectives(), and createMissionObjectives().
void MissionManagerImplementation::createDestroyMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 216 of file MissionManagerImplementation.cpp.
References server::zone::objects::mission::MissionObject::getDifficultyLevel(), server::zone::objects::mission::MissionObject::getTargetOptionalTemplate(), and server::zone::objects::mission::MissionObject::setMissionObjective().
Referenced by server::zone::managers::mission::MissionManager::createDestroyMissionObjectives(), and createMissionObjectives().
void MissionManagerImplementation::createEntertainerMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 297 of file MissionManagerImplementation.cpp.
References server::zone::objects::mission::MissionObject::setMissionObjective().
Referenced by server::zone::managers::mission::MissionManager::createEntertainerMissionObjectives(), and createMissionObjectives().
void MissionManagerImplementation::createHuntingMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 306 of file MissionManagerImplementation.cpp.
References server::zone::objects::mission::MissionObject::setMissionObjective().
Referenced by server::zone::managers::mission::MissionManager::createHuntingMissionObjectives(), and createMissionObjectives().
void MissionManagerImplementation::createMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 333 of file MissionManagerImplementation.cpp.
References createBountyMissionObjectives(), createCraftingMissionObjectives(), createDeliverMissionObjectives(), createDestroyMissionObjectives(), createEntertainerMissionObjectives(), createHuntingMissionObjectives(), createReconMissionObjectives(), createSurveyMissionObjectives(), and server::zone::objects::mission::MissionObject::getTypeCRC().
Referenced by server::zone::managers::mission::MissionManager::createMissionObjectives(), and handleMissionAccept().
void MissionManagerImplementation::createReconMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 315 of file MissionManagerImplementation.cpp.
References server::zone::objects::mission::MissionObject::setMissionObjective().
Referenced by createMissionObjectives(), and server::zone::managers::mission::MissionManager::createReconMissionObjectives().
void MissionManagerImplementation::createSpawnPoint (CreatureObject * player, const String & spawnTypes)
Definition at line 1426 of file MissionManagerImplementation.cpp.
References server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::addSpawnPoint(), server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::findSpawnAt(), server::zone::objects::scene::SceneObject::getDirection(), server::zone::objects::scene::SceneObject::getParentID(), server::zone::objects::scene::SceneObject::getPlanetCRC(), server::zone::managers::mission::spawnmaps::NpcSpawnPoint::getPosition(), server::zone::managers::mission::spawnmaps::NpcSpawnPoint::getSpawnType(), missionNpcSpawnMap, server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::saveSpawnPoints(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::mission::MissionManager::createSpawnPoint().
void MissionManagerImplementation::createSurveyMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 283 of file MissionManagerImplementation.cpp.
References server::zone::objects::mission::MissionObject::getDifficultyLevel(), server::zone::objects::mission::MissionObject::getTargetName(), and server::zone::objects::mission::MissionObject::setMissionObjective().
Referenced by createMissionObjectives(), and server::zone::managers::mission::MissionManager::createSurveyMissionObjectives().
void MissionManagerImplementation::deactivateMissions (CreatureObject * player)
Definition at line 1778 of file MissionManagerImplementation.cpp.
References server::zone::objects::mission::MissionObjective::deactivate(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), and server::zone::objects::scene::SceneObject::getSlottedObject().
Referenced by server::zone::managers::mission::MissionManager::deactivateMissions().
void MissionManagerImplementation::despawnMissionNpc (NpcSpawnPoint * npc)
Definition at line 1769 of file MissionManagerImplementation.cpp.
References server::zone::managers::mission::spawnmaps::NpcSpawnPoint::despawnNpc(), and missionNpcSpawnMap.
Referenced by server::zone::managers::mission::MissionManager::despawnMissionNpc().
void MissionManagerImplementation::failPlayerBountyMission (unsigned long long bountyHunter)
Definition at line 1734 of file MissionManagerImplementation.cpp.
References getBountyHunterMission(), and server.
Referenced by completePlayerBounty(), and server::zone::managers::mission::MissionManager::failPlayerBountyMission().
void MissionManagerImplementation::finalize () protected
Definition at line 958 of file MissionManager.cpp.
void MissionManagerImplementation::freeMissionNpc (NpcSpawnPoint * npc)
Definition at line 1763 of file MissionManagerImplementation.cpp.
References _this, server::zone::managers::mission::spawnmaps::NpcSpawnPoint::freeNpc(), and missionNpcSpawnMap.
Referenced by server::zone::managers::mission::MissionManager::freeMissionNpc().
void MissionManagerImplementation::generateRandomFactionalDestroyMissionDescription (CreatureObject * player, MissionObject * mission, const String & faction) private
Definition at line 1389 of file MissionManagerImplementation.cpp.
References FactionStatus::COVERT, server::zone::objects::mission::MissionObject::getDifficultyLevel(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::creature::CreatureObject::getPlayerObject(), FactionStatus::OVERT, server::zone::objects::mission::MissionObject::setMissionDescription(), and server::zone::objects::mission::MissionObject::setMissionTitle().
Referenced by randomizeGenericDestroyMission().
Reference< MissionObject * > MissionManagerImplementation::getBountyHunterMission (CreatureObject * player)
Definition at line 1611 of file MissionManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getSlottedObject().
Referenced by failPlayerBountyMission(), and server::zone::managers::mission::MissionManager::getBountyHunterMission().
int MissionManagerImplementation::getDeliverMissionNumberOfMissions (const int faction)
Definition at line 912 of file MissionManagerImplementation.cpp.
Referenced by server::zone::managers::mission::MissionManager::getDeliverMissionNumberOfMissions(), and randomGenericDeliverMission().
int MissionManagerImplementation::getDeliverMissionSpawnType (const int faction)
Definition at line 923 of file MissionManagerImplementation.cpp.
Referenced by server::zone::managers::mission::MissionManager::getDeliverMissionSpawnType(), and randomGenericDeliverMission().
String MissionManagerImplementation::getDeliveryMissionFileName (const int faction)
Definition at line 901 of file MissionManagerImplementation.cpp.
Referenced by server::zone::managers::mission::MissionManager::getDeliveryMissionFileName(), and randomGenericDeliverMission().
Vector3 MissionManagerImplementation::getRandomBountyTargetPosition (CreatureObject * player)
Definition at line 1577 of file MissionManagerImplementation.cpp.
References server::zone::Zone::getMaxX(), server::zone::Zone::getMaxY(), server::zone::Zone::getMinX(), server::zone::Zone::getMinY(), server::zone::Zone::getPlanetManager(), server::zone::objects::scene::SceneObject::getWorldCoordinate(), server::zone::objects::scene::SceneObject::getZone(), server::zone::managers::planet::PlanetManager::isBuildingPermittedAt(), server::zone::managers::planet::PlanetManager::isInWater(), and server::zone::Zone::isWithinBoundaries().
Referenced by server::zone::managers::mission::MissionManager::getRandomBountyTargetPosition(), and randomizeGenericBountyMission().
NpcSpawnPoint * MissionManagerImplementation::getRandomFreeNpcSpawnPoint (unsigned const int planetCRC, const float x, const float y, const int spawnType)
Definition at line 1032 of file MissionManagerImplementation.cpp.
References server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::getRandomNpcSpawnPoint(), and missionNpcSpawnMap.
Referenced by server::zone::managers::mission::MissionManager::getRandomFreeNpcSpawnPoint().
LairSpawn * MissionManagerImplementation::getRandomLairSpawn (CreatureObject * player, const int faction, unsigned int type)
Definition at line 1464 of file MissionManagerImplementation.cpp.
References FactionStatus::COVERT, server::zone::Zone::getCreatureManager(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::managers::creature::CreatureManager::getFactionalImperialMissionSpawnAreas(), server::zone::managers::creature::CreatureManager::getFactionalNeutralMissionSpawnAreas(), server::zone::managers::creature::CreatureManager::getFactionalRebelMissionSpawnAreas(), server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::group::GroupObject::getGroupLevel(), server::zone::managers::creature::LairSpawnGroup::getLairList(), server::zone::managers::creature::LairSpawn::getMaxDifficulty(), server::zone::managers::creature::LairSpawn::getMinDifficulty(), server::zone::managers::creature::CreatureManager::getNonfactionalMissionSpawnAreas(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::area::LairSpawnArea::getSpawnGroup(), server::zone::managers::creature::CreatureManager::getWorldSpawnAreas(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isGrouped(), FactionStatus::OVERT, and server.
Referenced by server::zone::managers::mission::MissionManager::getRandomLairSpawn(), randomizeGenericDestroyMission(), and randomizeGenericHuntingMission().
BountyTargetListElement * MissionManagerImplementation::getRandomPlayerBounty (CreatureObject * player)
Definition at line 1684 of file MissionManagerImplementation.cpp.
References BountyTargetListElement::getCanHaveNewMissions(), server::zone::objects::scene::SceneObject::getObjectID(), BountyTargetListElement::getTargetId(), BountyTargetListElement::numberOfActiveMissions(), playerBountyList, and playerBountyListMutex.
Referenced by server::zone::managers::mission::MissionManager::getRandomPlayerBounty(), and randomizeGenericBountyMission().
void MissionManagerImplementation::handleMissionAbort (MissionObject * mission, CreatureObject * player)
Definition at line 383 of file MissionManagerImplementation.cpp.
References server::zone::objects::mission::MissionObject::abort(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::mission::MissionObject::getTypeCRC(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::creature::CreatureObject::isInCombat(), removeMission(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::mission::MissionManager::handleMissionAbort().
void MissionManagerImplementation::handleMissionAccept (MissionTerminal * missionTerminal, MissionObject * mission, CreatureObject * player)
Definition at line 153 of file MissionManagerImplementation.cpp.
References createMissionObjectives(), BountyTargetListElement::getCanHaveNewMissions(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::mission::MissionObject::getTargetObjectId(), server::zone::objects::mission::MissionObject::getTypeCRC(), server::zone::objects::scene::SceneObject::isMissionObject(), playerBountyList, playerBountyListMutex, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::SceneObject::transferObject(), and server::zone::objects::creature::CreatureObject::updateToDatabaseAllObjects().
Referenced by server::zone::managers::mission::MissionManager::handleMissionAccept().
void MissionManagerImplementation::handleMissionListRequest (MissionTerminal * missionTerminal, CreatureObject * player, int counter)
Definition at line 100 of file MissionManagerImplementation.cpp.
References enableFactionalCraftingMissions, enableFactionalEntertainerMissions, enableFactionalReconMissions, server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::tangible::terminal::mission::MissionTerminal::isBountyTerminal(), server::zone::objects::tangible::terminal::mission::MissionTerminal::isNewbieTerminal(), server::zone::objects::tangible::terminal::mission::MissionTerminal::isStatueTerminal(), populateMissionList(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server.
Referenced by server::zone::managers::mission::MissionManager::handleMissionListRequest().
void MissionManagerImplementation::loadLuaSettings ()
Definition at line 39 of file MissionManagerImplementation.cpp.
References bhTargetsAtMissionLevel, bhTargetZones, craftingMissionItems, enableFactionalCraftingMissions, enableFactionalEntertainerMissions, and enableFactionalReconMissions.
Referenced by server::zone::managers::mission::MissionManager::loadLuaSettings(), and MissionManagerImplementation().
void MissionManagerImplementation::lock (bool doLock = true) protected
Definition at line 982 of file MissionManager.cpp.
References _this.
void MissionManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 986 of file MissionManager.cpp.
References _this.
MissionManagerImplementation::operator const MissionManager * ()
Definition at line 978 of file MissionManager.cpp.
void MissionManagerImplementation::populateMissionList (MissionTerminal * missionTerminal, CreatureObject * player, int counter)
Definition at line 406 of file MissionManagerImplementation.cpp.
References enableFactionalCraftingMissions, enableFactionalEntertainerMissions, enableFactionalReconMissions, server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::tangible::terminal::mission::MissionTerminal::isArtisanTerminal(), server::zone::objects::tangible::terminal::mission::MissionTerminal::isBountyTerminal(), server::zone::objects::tangible::terminal::mission::MissionTerminal::isEntertainerTerminal(), server::zone::objects::tangible::terminal::mission::MissionTerminal::isGeneralTerminal(), server::zone::objects::tangible::terminal::mission::MissionTerminal::isImperialTerminal(), server::zone::objects::tangible::terminal::mission::MissionTerminal::isRebelTerminal(), server::zone::objects::tangible::terminal::mission::MissionTerminal::isScoutTerminal(), server::zone::objects::tangible::terminal::mission::MissionTerminal::isSlicer(), randomizeBountyMission(), randomizeCraftingMission(), randomizeDeliverMission(), randomizeDestroyMission(), randomizeGenericEntertainerMission(), randomizeHuntingMission(), randomizeImperialCraftingMission(), randomizeImperialDeliverMission(), randomizeImperialDestroyMission(), randomizeImperialReconMission(), randomizeRebelCraftingMission(), randomizeRebelDeliverMission(), randomizeRebelDestroyMission(), randomizeRebelReconMission(), randomizeReconMission(), randomizeSurveyMission(), server::zone::objects::tangible::terminal::mission::MissionTerminal::removeSlicer(), and server::zone::objects::mission::MissionObject::setTypeCRC().
Referenced by handleMissionListRequest(), and server::zone::managers::mission::MissionManager::populateMissionList().
bool MissionManagerImplementation::randomGenericDeliverMission (CreatureObject * player, MissionObject * mission, bool inTownMission, const int faction)
Definition at line 934 of file MissionManagerImplementation.cpp.
References getDeliverMissionNumberOfMissions(), getDeliverMissionSpawnType(), getDeliveryMissionFileName(), server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::getRandomCityCoordinates(), server::zone::managers::mission::spawnmaps::MissionNpcSpawnMap::getRandomNpcSpawnPoint(), server::zone::objects::scene::SceneObject::getWorldPosition(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::managers::name::NameManager::makeCreatureName(), missionNpcSpawnMap, processor, server::zone::objects::mission::MissionObject::setCreatorName(), server::zone::objects::mission::MissionObject::setEndPosition(), server::zone::objects::mission::MissionObject::setFaction(), server::zone::objects::mission::MissionObject::setMissionDescription(), server::zone::objects::mission::MissionObject::setMissionDifficulty(), server::zone::objects::mission::MissionObject::setMissionNumber(), server::zone::objects::mission::MissionObject::setMissionTarget(), server::zone::objects::mission::MissionObject::setMissionTargetDest(), server::zone::objects::mission::MissionObject::setMissionTargetName(), server::zone::objects::mission::MissionObject::setMissionTitle(), server::zone::objects::mission::MissionObject::setRewardCredits(), server::zone::objects::mission::MissionObject::setRewardFactionPointsImperial(), server::zone::objects::mission::MissionObject::setRewardFactionPointsRebel(), server::zone::objects::mission::MissionObject::setStartPlanet(), server::zone::objects::mission::MissionObject::setStartPosition(), server::zone::objects::mission::MissionObject::setTargetTemplate(), and server::zone::objects::mission::MissionObject::setTypeCRC().
Referenced by server::zone::managers::mission::MissionManager::randomGenericDeliverMission(), and randomizeGenericDeliverMission().
void MissionManagerImplementation::randomizeBountyMission (CreatureObject * player, MissionObject * mission)
Definition at line 753 of file MissionManagerImplementation.cpp.
References randomizeGenericBountyMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeBountyMission().
void MissionManagerImplementation::randomizeCraftingMission (CreatureObject * player, MissionObject * mission)
Definition at line 1053 of file MissionManagerImplementation.cpp.
References randomizeGenericCraftingMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeCraftingMission().
void MissionManagerImplementation::randomizeDeliverMission (CreatureObject * player, MissionObject * mission)
Definition at line 883 of file MissionManagerImplementation.cpp.
References randomizeGenericDeliverMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeDeliverMission().
void MissionManagerImplementation::randomizeDestroyMission (CreatureObject * player, MissionObject * mission)
Definition at line 535 of file MissionManagerImplementation.cpp.
References randomizeGenericDestroyMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeDestroyMission().
void MissionManagerImplementation::randomizeGenericBountyMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 757 of file MissionManagerImplementation.cpp.
References bhTargetsAtMissionLevel, bhTargetZones, server::zone::templates::mobile::CreatureTemplate::getLevel(), server::zone::ZoneServer::getObject(), getRandomBountyTargetPosition(), getRandomPlayerBounty(), BountyTargetListElement::getReward(), BountyTargetListElement::getTargetId(), server::zone::objects::mission::MissionObject::getTargetOptionalTemplate(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::managers::name::NameManager::makeCreatureName(), playerBountyList, processor, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::mission::MissionObject::setCreatorName(), server::zone::objects::mission::MissionObject::setEndPosition(), server::zone::objects::mission::MissionObject::setFaction(), server::zone::objects::mission::MissionObject::setMissionDescription(), server::zone::objects::mission::MissionObject::setMissionDifficulty(), server::zone::objects::mission::MissionObject::setMissionLevel(), server::zone::objects::mission::MissionObject::setMissionNumber(), server::zone::objects::mission::MissionObject::setMissionTargetName(), server::zone::objects::mission::MissionObject::setMissionTitle(), server::zone::objects::mission::MissionObject::setRewardCredits(), server::zone::objects::mission::MissionObject::setStartPlanet(), server::zone::objects::mission::MissionObject::setStartPosition(), server::zone::objects::mission::MissionObject::setTargetObjectId(), server::zone::objects::mission::MissionObject::setTargetOptionalTemplate(), server::zone::objects::mission::MissionObject::setTargetTemplate(), and server::zone::objects::mission::MissionObject::setTypeCRC().
Referenced by randomizeBountyMission(), and server::zone::managers::mission::MissionManager::randomizeGenericBountyMission().
void MissionManagerImplementation::randomizeGenericCraftingMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 1057 of file MissionManagerImplementation.cpp.
References server::zone::objects::mission::MissionObject::getTypeCRC(), randomizeGenericDeliverMission(), server::zone::objects::mission::MissionObject::setMissionDescription(), server::zone::objects::mission::MissionObject::setMissionTitle(), server::zone::objects::mission::MissionObject::setTargetTemplate(), and server::zone::objects::mission::MissionObject::setTypeCRC().
Referenced by randomizeCraftingMission(), server::zone::managers::mission::MissionManager::randomizeGenericCraftingMission(), randomizeImperialCraftingMission(), and randomizeRebelCraftingMission().
void MissionManagerImplementation::randomizeGenericDeliverMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 887 of file MissionManagerImplementation.cpp.
References randomGenericDeliverMission().
Referenced by randomizeDeliverMission(), randomizeGenericCraftingMission(), server::zone::managers::mission::MissionManager::randomizeGenericDeliverMission(), randomizeImperialDeliverMission(), and randomizeRebelDeliverMission().
void MissionManagerImplementation::randomizeGenericDestroyMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 539 of file MissionManagerImplementation.cpp.
References generateRandomFactionalDestroyMissionDescription(), server::zone::templates::mobile::LairTemplate::getBuilding(), server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::group::GroupObject::getGroupLevel(), server::zone::Zone::getHeight(), server::zone::Zone::getInRangeActiveAreas(), server::zone::managers::creature::LairSpawn::getLairTemplateName(), server::zone::managers::creature::LairSpawn::getMaxDifficulty(), server::zone::managers::creature::LairSpawn::getMinDifficulty(), server::zone::templates::mobile::LairTemplate::getName(), server::zone::Zone::getPlanetManager(), getRandomLairSpawn(), server::zone::managers::planet::PlanetManager::getTerrainManager(), TerrainManager::getWaterHeight(), server::zone::objects::scene::SceneObject::getWorldCoordinate(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::creature::CreatureObject::isGrouped(), server::zone::templates::SharedObjectTemplate::isSharedTangibleObjectTemplate(), server::zone::Zone::isWithinBoundaries(), server::zone::managers::name::NameManager::makeCreatureName(), processor, server, server::zone::objects::mission::MissionObject::setCreatorName(), server::zone::objects::mission::MissionObject::setFaction(), server::zone::objects::mission::MissionObject::setMissionDescription(), server::zone::objects::mission::MissionObject::setMissionDifficulty(), server::zone::objects::mission::MissionObject::setMissionNumber(), server::zone::objects::mission::MissionObject::setMissionTargetName(), server::zone::objects::mission::MissionObject::setMissionTitle(), server::zone::objects::mission::MissionObject::setRewardCredits(), server::zone::objects::mission::MissionObject::setRewardFactionPointsImperial(), server::zone::objects::mission::MissionObject::setRewardFactionPointsRebel(), server::zone::objects::mission::MissionObject::setStartPlanet(), server::zone::objects::mission::MissionObject::setStartPosition(), server::zone::objects::mission::MissionObject::setTargetOptionalTemplate(), server::zone::objects::mission::MissionObject::setTargetTemplate(), and server::zone::objects::mission::MissionObject::setTypeCRC().
Referenced by randomizeDestroyMission(), server::zone::managers::mission::MissionManager::randomizeGenericDestroyMission(), randomizeImperialDestroyMission(), and randomizeRebelDestroyMission().
void MissionManagerImplementation::randomizeGenericEntertainerMission (CreatureObject * player, MissionObject * mission, const int faction, const int missionType)
Definition at line 1094 of file MissionManagerImplementation.cpp.
References server::zone::managers::planet::PlanetManager::getPerformanceLocations(), server::zone::Zone::getPlanetManager(), MissionTargetMap::getRandomTarget(), server::zone::objects::scene::SceneObject::getWorldPosition(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::scene::SceneObject::isStructureObject(), server::zone::managers::name::NameManager::makeCreatureName(), processor, server::zone::objects::mission::MissionObject::setCreatorName(), server::zone::objects::mission::MissionObject::setFaction(), server::zone::objects::mission::MissionObject::setMissionDescription(), server::zone::objects::mission::MissionObject::setMissionDifficulty(), server::zone::objects::mission::MissionObject::setMissionNumber(), server::zone::objects::mission::MissionObject::setMissionTargetName(), server::zone::objects::mission::MissionObject::setMissionTitle(), server::zone::objects::mission::MissionObject::setRewardCredits(), server::zone::objects::mission::MissionObject::setRewardFactionPointsImperial(), server::zone::objects::mission::MissionObject::setRewardFactionPointsRebel(), server::zone::objects::mission::MissionObject::setStartPlanet(), server::zone::objects::mission::MissionObject::setStartPosition(), server::zone::objects::mission::MissionObject::setTargetTemplate(), server::zone::objects::mission::MissionObject::setTypeCRC(), and MissionTargetMap::size().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeGenericEntertainerMission().
void MissionManagerImplementation::randomizeGenericHuntingMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 1181 of file MissionManagerImplementation.cpp.
References server::zone::managers::creature::LairSpawn::getLairTemplateName(), server::zone::managers::creature::LairSpawn::getMinDifficulty(), server::zone::templates::mobile::LairTemplate::getMobiles(), server::zone::templates::mobile::CreatureTemplate::getObjectName(), getRandomLairSpawn(), server::zone::templates::mobile::CreatureTemplate::getTemplates(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::managers::name::NameManager::makeCreatureName(), processor, server::zone::objects::mission::MissionObject::setCreatorName(), server::zone::objects::mission::MissionObject::setFaction(), server::zone::objects::mission::MissionObject::setMissionDescription(), server::zone::objects::mission::MissionObject::setMissionDifficulty(), server::zone::objects::mission::MissionObject::setMissionNumber(), server::zone::objects::mission::MissionObject::setMissionTargetName(), server::zone::objects::mission::MissionObject::setMissionTitle(), server::zone::objects::mission::MissionObject::setRewardCredits(), server::zone::objects::mission::MissionObject::setStartPlanet(), server::zone::objects::mission::MissionObject::setStartPosition(), server::zone::objects::mission::MissionObject::setTargetTemplate(), server::zone::objects::mission::MissionObject::setTemplateStrings(), and server::zone::objects::mission::MissionObject::setTypeCRC().
Referenced by server::zone::managers::mission::MissionManager::randomizeGenericHuntingMission(), and randomizeHuntingMission().
void MissionManagerImplementation::randomizeGenericReconMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 1278 of file MissionManagerImplementation.cpp.
References server::zone::managers::planet::PlanetManager::getNearestPlanetTravelPoint(), server::zone::Zone::getPlanetManager(), server::zone::objects::scene::SceneObject::getWorldCoordinate(), server::zone::objects::scene::SceneObject::getWorldPosition(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::managers::planet::PlanetManager::isBuildingPermittedAt(), server::zone::Zone::isWithinBoundaries(), server::zone::managers::name::NameManager::makeCreatureName(), processor, server::zone::objects::mission::MissionObject::setCreatorName(), server::zone::objects::mission::MissionObject::setFaction(), server::zone::objects::mission::MissionObject::setMissionDescription(), server::zone::objects::mission::MissionObject::setMissionDifficulty(), server::zone::objects::mission::MissionObject::setMissionNumber(), server::zone::objects::mission::MissionObject::setMissionTargetName(), server::zone::objects::mission::MissionObject::setMissionTitle(), server::zone::objects::mission::MissionObject::setRewardCredits(), server::zone::objects::mission::MissionObject::setRewardFactionPointsImperial(), server::zone::objects::mission::MissionObject::setRewardFactionPointsRebel(), server::zone::objects::mission::MissionObject::setStartPlanet(), server::zone::objects::mission::MissionObject::setStartPosition(), server::zone::objects::mission::MissionObject::setTargetTemplate(), and server::zone::objects::mission::MissionObject::setTypeCRC().
Referenced by server::zone::managers::mission::MissionManager::randomizeGenericReconMission(), randomizeImperialReconMission(), randomizeRebelReconMission(), and randomizeReconMission().
void MissionManagerImplementation::randomizeGenericSurveyMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 678 of file MissionManagerImplementation.cpp.
References server::zone::managers::resource::ResourceManager::getResourceListByType(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::managers::name::NameManager::makeCreatureName(), processor, server, server::zone::objects::mission::MissionObject::setCreatorName(), server::zone::objects::mission::MissionObject::setFaction(), server::zone::objects::mission::MissionObject::setMissionDescription(), server::zone::objects::mission::MissionObject::setMissionDifficulty(), server::zone::objects::mission::MissionObject::setMissionTargetName(), server::zone::objects::mission::MissionObject::setMissionTitle(), server::zone::objects::mission::MissionObject::setRewardCredits(), server::zone::objects::mission::MissionObject::setStartPosition(), server::zone::objects::mission::MissionObject::setTargetTemplate(), and server::zone::objects::mission::MissionObject::setTypeCRC().
Referenced by server::zone::managers::mission::MissionManager::randomizeGenericSurveyMission(), and randomizeSurveyMission().
void MissionManagerImplementation::randomizeHuntingMission (CreatureObject * player, MissionObject * mission)
Definition at line 1177 of file MissionManagerImplementation.cpp.
References randomizeGenericHuntingMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeHuntingMission().
void MissionManagerImplementation::randomizeImperialCraftingMission (CreatureObject * player, MissionObject * mission)
Definition at line 1365 of file MissionManagerImplementation.cpp.
References randomizeGenericCraftingMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeImperialCraftingMission().
void MissionManagerImplementation::randomizeImperialDeliverMission (CreatureObject * player, MissionObject * mission)
Definition at line 1361 of file MissionManagerImplementation.cpp.
References randomizeGenericDeliverMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeImperialDeliverMission().
void MissionManagerImplementation::randomizeImperialDestroyMission (CreatureObject * player, MissionObject * mission)
Definition at line 1357 of file MissionManagerImplementation.cpp.
References randomizeGenericDestroyMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeImperialDestroyMission().
void MissionManagerImplementation::randomizeImperialReconMission (CreatureObject * player, MissionObject * mission)
Definition at line 1369 of file MissionManagerImplementation.cpp.
References randomizeGenericReconMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeImperialReconMission().
void MissionManagerImplementation::randomizeRebelCraftingMission (CreatureObject * player, MissionObject * mission)
Definition at line 1381 of file MissionManagerImplementation.cpp.
References randomizeGenericCraftingMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeRebelCraftingMission().
void MissionManagerImplementation::randomizeRebelDeliverMission (CreatureObject * player, MissionObject * mission)
Definition at line 1377 of file MissionManagerImplementation.cpp.
References randomizeGenericDeliverMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeRebelDeliverMission().
void MissionManagerImplementation::randomizeRebelDestroyMission (CreatureObject * player, MissionObject * mission)
Definition at line 1373 of file MissionManagerImplementation.cpp.
References randomizeGenericDestroyMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeRebelDestroyMission().
void MissionManagerImplementation::randomizeRebelReconMission (CreatureObject * player, MissionObject * mission)
Definition at line 1385 of file MissionManagerImplementation.cpp.
References randomizeGenericReconMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeRebelReconMission().
void MissionManagerImplementation::randomizeReconMission (CreatureObject * player, MissionObject * mission)
Definition at line 1353 of file MissionManagerImplementation.cpp.
References randomizeGenericReconMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeReconMission().
void MissionManagerImplementation::randomizeSurveyMission (CreatureObject * player, MissionObject * mission)
Definition at line 674 of file MissionManagerImplementation.cpp.
References randomizeGenericSurveyMission().
Referenced by populateMissionList(), and server::zone::managers::mission::MissionManager::randomizeSurveyMission().
void MissionManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 1017 of file MissionManager.cpp.
References readObjectMember().
bool MissionManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 1036 of file MissionManager.cpp.
References bhTargetsAtMissionLevel, bhTargetZones, craftingMissionItems, enableFactionalCraftingMissions, enableFactionalEntertainerMissions, enableFactionalReconMissions, missionNpcSpawnMap, playerBountyList, and server.
Referenced by readObject().
void MissionManagerImplementation::removeBountyHunterFromPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
Definition at line 1669 of file MissionManagerImplementation.cpp.
References playerBountyList, and playerBountyListMutex.
Referenced by server::zone::managers::mission::MissionManager::removeBountyHunterFromPlayerBounty().
void MissionManagerImplementation::removeMission (MissionObject * mission, CreatureObject * player)
Definition at line 367 of file MissionManagerImplementation.cpp.
References server::zone::objects::mission::MissionObject::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::sendDestroyTo(), and server::zone::objects::creature::CreatureObject::updateToDatabaseAllObjects().
Referenced by handleMissionAbort(), and server::zone::managers::mission::MissionManager::removeMission().
void MissionManagerImplementation::removePlayerFromBountyList (unsigned long long targetId)
Definition at line 1639 of file MissionManagerImplementation.cpp.
References playerBountyList, and playerBountyListMutex.
Referenced by server::zone::managers::mission::MissionManager::removePlayerFromBountyList().
void MissionManagerImplementation::rlock (bool doLock = true) protected
Definition at line 990 of file MissionManager.cpp.
References _this.
void MissionManagerImplementation::runlock (bool doLock = true) protected
Definition at line 1006 of file MissionManager.cpp.
References _this.
void MissionManagerImplementation::unlock (bool doLock = true) protected
Definition at line 1002 of file MissionManager.cpp.
References _this.
void MissionManagerImplementation::updatePlayerBountyReward (unsigned long long targetId, int reward)
Definition at line 1653 of file MissionManagerImplementation.cpp.
References playerBountyList, and playerBountyListMutex.
Referenced by server::zone::managers::mission::MissionManager::updatePlayerBountyReward().
void MissionManagerImplementation::wlock (bool doLock = true) protected
Definition at line 994 of file MissionManager.cpp.
References _this.
void MissionManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 998 of file MissionManager.cpp.
References _this.
void MissionManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 1082 of file MissionManager.cpp.
References writeObjectMembers().
int MissionManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 1089 of file MissionManager.cpp.
References bhTargetsAtMissionLevel, bhTargetZones, craftingMissionItems, enableFactionalCraftingMissions, enableFactionalEntertainerMissions, enableFactionalReconMissions, missionNpcSpawnMap, playerBountyList, and server.
Referenced by writeObject().
Friends And Related Function Documentation
friend class MissionManager friend
Definition at line 509 of file MissionManager.h.
Member Data Documentation
WeakReference<MissionManager*> server::zone::managers::mission::MissionManagerImplementation::_this
Definition at line 475 of file MissionManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), freeMissionNpc(), lock(), rlock(), runlock(), unlock(), and wlock().
VectorMap<unsigned int, Vector<String>*> server::zone::managers::mission::MissionManagerImplementation::bhTargetsAtMissionLevel protected
Definition at line 334 of file MissionManager.h.
Referenced by loadLuaSettings(), randomizeGenericBountyMission(), readObjectMember(), and writeObjectMembers().
Vector<String> server::zone::managers::mission::MissionManagerImplementation::bhTargetZones protected
Definition at line 332 of file MissionManager.h.
Referenced by loadLuaSettings(), randomizeGenericBountyMission(), readObjectMember(), and writeObjectMembers().
Vector<String> server::zone::managers::mission::MissionManagerImplementation::craftingMissionItems protected
Definition at line 330 of file MissionManager.h.
Referenced by createCraftingMissionObjectives(), loadLuaSettings(), readObjectMember(), and writeObjectMembers().
bool server::zone::managers::mission::MissionManagerImplementation::enableFactionalCraftingMissions protected
Definition at line 340 of file MissionManager.h.
Referenced by createCraftingMissionObjectives(), handleMissionListRequest(), loadLuaSettings(), MissionManagerImplementation(), populateMissionList(), readObjectMember(), and writeObjectMembers().
bool server::zone::managers::mission::MissionManagerImplementation::enableFactionalEntertainerMissions protected
Definition at line 344 of file MissionManager.h.
Referenced by handleMissionListRequest(), loadLuaSettings(), MissionManagerImplementation(), populateMissionList(), readObjectMember(), and writeObjectMembers().
bool server::zone::managers::mission::MissionManagerImplementation::enableFactionalReconMissions protected
Definition at line 342 of file MissionManager.h.
Referenced by handleMissionListRequest(), loadLuaSettings(), MissionManagerImplementation(), populateMissionList(), readObjectMember(), and writeObjectMembers().
MissionNpcSpawnMap server::zone::managers::mission::MissionManagerImplementation::missionNpcSpawnMap protected
Definition at line 328 of file MissionManager.h.
Referenced by allocateMissionNpcs(), createSpawnPoint(), despawnMissionNpc(), freeMissionNpc(), getRandomFreeNpcSpawnPoint(), MissionManagerImplementation(), randomGenericDeliverMission(), readObjectMember(), and writeObjectMembers().
VectorMap<unsigned long long, BountyTargetListElement*> server::zone::managers::mission::MissionManagerImplementation::playerBountyList protected
Definition at line 336 of file MissionManager.h.
Referenced by addBountyHunterToPlayerBounty(), addPlayerToBountyList(), completePlayerBounty(), getRandomPlayerBounty(), handleMissionAccept(), MissionManagerImplementation(), randomizeGenericBountyMission(), readObjectMember(), removeBountyHunterFromPlayerBounty(), removePlayerFromBountyList(), updatePlayerBountyReward(), and writeObjectMembers().
Mutex server::zone::managers::mission::MissionManagerImplementation::playerBountyListMutex protected
Definition at line 338 of file MissionManager.h.
Referenced by addBountyHunterToPlayerBounty(), addPlayerToBountyList(), completePlayerBounty(), getRandomPlayerBounty(), handleMissionAccept(), removeBountyHunterFromPlayerBounty(), removePlayerFromBountyList(), and updatePlayerBountyReward().
ManagedReference<ZoneProcessServer* > server::zone::managers::mission::MissionManagerImplementation::processor private
Definition at line 325 of file MissionManager.h.
Referenced by MissionManagerImplementation(), randomGenericDeliverMission(), randomizeGenericBountyMission(), randomizeGenericDestroyMission(), randomizeGenericEntertainerMission(), randomizeGenericHuntingMission(), randomizeGenericReconMission(), and randomizeGenericSurveyMission().
ManagedReference<ZoneServer* > server::zone::managers::mission::MissionManagerImplementation::server protected
Definition at line 322 of file MissionManager.h.
Referenced by failPlayerBountyMission(), getRandomLairSpawn(), handleMissionListRequest(), MissionManagerImplementation(), randomizeGenericDestroyMission(), randomizeGenericSurveyMission(), readObjectMember(), and writeObjectMembers().
unsigned const int server::zone::managers::mission::MissionManagerImplementation::UNKNOWN_TARGET = 0xB911DA26 static
Definition at line 347 of file MissionManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/mission/MissionManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/mission/MissionManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/mission/MissionManagerImplementation.cpp