Core3: server::zone::packets::object::ObjectMenuResponse Class Reference
server::zone::packets::object::ObjectMenuResponse Class Reference
#include <ObjectMenuResponse.h>
Public Member Functions
ObjectMenuResponse (SceneObject *player, uint64 target, uint8 counter)
~ObjectMenuResponse ()
RadialMenuItem * getRadialItem (int index)
RadialMenuItem * getRadialItemByRadialID (uint8 id)
void addRadialMenuItem (uint8 parentid, uint8 radialid, uint8 callback, const UnicodeString &text="")
void addRadialMenuItemToRadialID (uint8 parentRadialID, uint8 newRadialID, uint8 callback, const UnicodeString &text="")
void addRadialMenuItem (uint8 radialid, uint8 callback, const UnicodeString &text="")
void finish ()
void insertRadialItemToMessage (RadialMenuItem *item)
void setCounter (uint8 counter)
RadialMenuItem * getRootMenuItem ()
Public Member Functions inherited from ObjectControllerMessage
ObjectControllerMessage (uint64 objid, uint32 header1, uint32 header2, bool comp=true)
Private Member Functions
void addRadialOption (RadialMenuItem *item)
Private Attributes
int listSize
uint8 count
Reference< RadialMenuItem * > root
int indexCount
Detailed Description
Definition at line 61 of file ObjectMenuResponse.h.
Constructor & Destructor Documentation
server::zone::packets::object::ObjectMenuResponse::ObjectMenuResponse (SceneObject * player, uint64 target, uint8 counter) inline
Definition at line 93 of file ObjectMenuResponse.h.
References count, server::zone::objects::scene::SceneObject::getObjectID(), indexCount, listSize, and root.
server::zone::packets::object::ObjectMenuResponse::~ObjectMenuResponse () inline
Definition at line 119 of file ObjectMenuResponse.h.
Member Function Documentation
void server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem (uint8 parentid, uint8 radialid, uint8 callback, const UnicodeString & text = "") inline
Definition at line 136 of file ObjectMenuResponse.h.
References RadialMenuItem::addRadialMenuItem(), getRadialItem(), and indexCount.
Referenced by server::zone::packets::object::LuaObjectMenuResponse::addRadialMenuItem(), RadialClientItem::addToResponse(), CityManagementMenuComponent::fillObjectMenuResponse(), CityVotingMenuComponent::fillObjectMenuResponse(), InstallationObjectMenuComponent::fillObjectMenuResponse(), ElevatorDownMenuComponent::fillObjectMenuResponse(), ElevatorMenuComponent::fillObjectMenuResponse(), ElevatorUpMenuComponent::fillObjectMenuResponse(), FactoryObjectMenuComponent::fillObjectMenuResponse(), StructureTerminalMenuComponent::fillObjectMenuResponse(), PlayerObjectMenuComponent::fillObjectMenuResponse(), TrainerMenuComponent::fillObjectMenuResponse(), LootSchematicMenuComponent::fillObjectMenuResponse(), GogglesObjectMenuComponent::fillObjectMenuResponse(), LairMenuComponent::fillObjectMenuResponse(), LightsaberObjectMenuComponent::fillObjectMenuResponse(), TangibleObjectMenuComponent::fillObjectMenuResponse(), VendorMenuComponent::fillObjectMenuResponse(), WeaponObjectMenuComponent::fillObjectMenuResponse(), WearableObjectMenuComponent::fillObjectMenuResponse(), CampTerminalMenuComponent::fillObjectMenuResponse(), CityDecorationMenuComponent::fillObjectMenuResponse(), FireworkShowMenuComponent::fillObjectMenuResponse(), CreatureHabitatMenuComponent::fillObjectMenuResponse(), ArmorObjectMenuComponent::fillObjectMenuResponse(), DiceMenuComponent::fillObjectMenuResponse(), BountyHunterDroidMenuComponent::fillObjectMenuResponse(), PowerRegulatorMenuComponent::fillObjectMenuResponse(), TurretControlMenuComponent::fillObjectMenuResponse(), OverrideTerminalMenuComponent::fillObjectMenuResponse(), MinefieldMenuComponent::fillObjectMenuResponse(), SecurityTerminalMenuComponent::fillObjectMenuResponse(), UplinkTerminalMenuComponent::fillObjectMenuResponse(), HQMenuComponent::fillObjectMenuResponse(), ForceShrineMenuComponent::fillObjectMenuResponse(), ObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::intangible::ShipControlDeviceImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::deed::ResourceDeedImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::ContainerImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::deed::pet::PetDeedImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::fishing::FishObjectImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::tool::SurveyToolImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::fillObjectMenuResponse(), server::zone::objects::creature::CreatureImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::InstrumentImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::tool::recycle::RecycleToolImplementation::fillObjectMenuResponse(), server::zone::objects::creature::VehicleObjectImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::tool::CraftingToolImplementation::fillObjectMenuResponse(), and server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::fillObjectMenuResponse().
void server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem (uint8 radialid, uint8 callback, const UnicodeString & text = "") inline
Definition at line 161 of file ObjectMenuResponse.h.
References indexCount, and root.
void server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID (uint8 parentRadialID, uint8 newRadialID, uint8 callback, const UnicodeString & text = "") inline
Adds an object menu item to the specified parent radial id, not parent index with callback
Definition at line 150 of file ObjectMenuResponse.h.
References RadialMenuItem::addRadialMenuItem(), getRadialItemByRadialID(), and indexCount.
Referenced by server::zone::packets::object::LuaObjectMenuResponse::addRadialMenuItemToRadialID(), CityManagementMenuComponent::fillObjectMenuResponse(), CityVotingMenuComponent::fillObjectMenuResponse(), StructureTerminalMenuComponent::fillObjectMenuResponse(), InstallationObjectMenuComponent::fillObjectMenuResponse(), FactoryObjectMenuComponent::fillObjectMenuResponse(), VendorMenuComponent::fillObjectMenuResponse(), FireworkShowMenuComponent::fillObjectMenuResponse(), BountyHunterDroidMenuComponent::fillObjectMenuResponse(), DiceMenuComponent::fillObjectMenuResponse(), BankTerminalMenuComponent::fillObjectMenuResponse(), HQMenuComponent::fillObjectMenuResponse(), ObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::installation::GeneratorObjectImplementation::fillObjectMenuResponse(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::tool::SurveyToolImplementation::fillObjectMenuResponse(), server::zone::objects::creature::CreatureImplementation::fillObjectMenuResponse(), and server::zone::objects::tangible::tool::recycle::RecycleToolImplementation::fillObjectMenuResponse().
void server::zone::packets::object::ObjectMenuResponse::addRadialOption (RadialMenuItem * item) inline private
This method is used to write the radial objects to the packet.
Parameters
parentid The parentid of the radial option.
radialid The radial id to be handled by the client and radialmanager.
callback The callback type for the radial.
text The text to label the radial choice.
Definition at line 79 of file ObjectMenuResponse.h.
References RadialMenuItem::getCallback(), RadialMenuItem::getItemIndex(), RadialMenuItem::getParentIndex(), RadialMenuItem::getRadialID(), RadialMenuItem::getText(), and listSize.
Referenced by insertRadialItemToMessage().
void server::zone::packets::object::ObjectMenuResponse::finish () inline
Definition at line 165 of file ObjectMenuResponse.h.
References count, insertRadialItemToMessage(), listSize, and root.
Referenced by server::zone::managers::radial::RadialManagerImplementation::handleObjectMenuRequest().
RadialMenuItem* server::zone::packets::object::ObjectMenuResponse::getRadialItem (int index) inline
Definition at line 122 of file ObjectMenuResponse.h.
References root.
Referenced by addRadialMenuItem().
RadialMenuItem* server::zone::packets::object::ObjectMenuResponse::getRadialItemByRadialID (uint8 id) inline
Definition at line 129 of file ObjectMenuResponse.h.
References root.
Referenced by addRadialMenuItemToRadialID().
RadialMenuItem* server::zone::packets::object::ObjectMenuResponse::getRootMenuItem () inline
Definition at line 185 of file ObjectMenuResponse.h.
References root.
void server::zone::packets::object::ObjectMenuResponse::insertRadialItemToMessage (RadialMenuItem * item) inline
Definition at line 172 of file ObjectMenuResponse.h.
References addRadialOption(), RadialMenuItem::getChild(), and RadialMenuItem::getChildrenSize().
Referenced by finish().
void server::zone::packets::object::ObjectMenuResponse::setCounter (uint8 counter) inline
Definition at line 181 of file ObjectMenuResponse.h.
References count.
Member Data Documentation
uint8 server::zone::packets::object::ObjectMenuResponse::count private
Definition at line 63 of file ObjectMenuResponse.h.
Referenced by finish(), ObjectMenuResponse(), and setCounter().
int server::zone::packets::object::ObjectMenuResponse::indexCount private
Definition at line 71 of file ObjectMenuResponse.h.
Referenced by addRadialMenuItem(), addRadialMenuItemToRadialID(), and ObjectMenuResponse().
int server::zone::packets::object::ObjectMenuResponse::listSize private
Definition at line 62 of file ObjectMenuResponse.h.
Referenced by addRadialOption(), finish(), and ObjectMenuResponse().
Reference<RadialMenuItem*> server::zone::packets::object::ObjectMenuResponse::root private
Definition at line 65 of file ObjectMenuResponse.h.
Referenced by addRadialMenuItem(), finish(), getRadialItem(), getRadialItemByRadialID(), getRootMenuItem(), and ObjectMenuResponse().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/object/ObjectMenuResponse.h