Core3: server::zone::objects::auction::AuctionItem Class Reference
server::zone::objects::auction::AuctionItem Class Reference
#include <AuctionItem.h>
Public Member Functions
AuctionItem (unsigned long long objectid)
int compareTo (AuctionItem *obj)
void notifyLoadFromDatabase ()
void setVendorID (unsigned long long val)
void setItemName (const String &name)
void setItemDescription (const String &descr)
void setPrice (int newPrice)
void setProxy (int newProxy)
void setAuctionedItemObjectID (unsigned long long objectID)
void setItemType (int type)
void setOwnerID (unsigned long long ownerObjectID)
void setOfferToID (unsigned long long vendorOwnerID)
void setBidderName (const String &name)
void setOwnerName (const String &name)
void setAuction (bool isAuction)
void setAuctionPremium ()
void clearAuctionWithdraw ()
void setOnBazaar (bool val)
void setExpireTime (int time)
void setBuyerID (unsigned long long id)
void setStatus (int value)
bool isOnBazaar ()
bool isAuction ()
int getStatus ()
unsigned long long getVendorID ()
unsigned long long getAuctionedItemObjectID ()
unsigned long long getOwnerID ()
unsigned long long getOfferToID ()
void setVendorUID (const String &uid)
const String getVendorUID ()
String getOwnerName ()
String getItemName ()
int getExpireTime ()
int getPrice ()
int getProxy ()
int getItemType ()
unsigned long long getBuyerID ()
String getBidderName ()
String getItemDescription ()
int getAuctionOptions ()
bool isPremiumAuction ()
bool isOwner (CreatureObject *player)
bool isAuctionObject ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int OPTION_PREMIUM = 0x400
static const int OPTION_WITHDRAW = 0x800
static const int FORSALE = 1
static const int SOLD = 2
static const int EXPIRED = 4
static const int OFFERED = 5
static const int RETRIEVED = 6
Protected Member Functions
AuctionItem (DummyConstructorParameter *param)
virtual ~AuctionItem ()
Friends
class AuctionItemHelper
Detailed Description
Definition at line 55 of file AuctionItem.h.
Constructor & Destructor Documentation
AuctionItem::AuctionItem (unsigned long long objectid)
Definition at line 17 of file AuctionItem.cpp.
References server::zone::objects::auction::AuctionItemImplementation::_setStub().
AuctionItem::AuctionItem (DummyConstructorParameter * param) protected
Definition at line 24 of file AuctionItem.cpp.
AuctionItem::~AuctionItem () protected virtual
Definition at line 28 of file AuctionItem.cpp.
Member Function Documentation
DistributedObjectServant * AuctionItem::_getImplementation ()
Definition at line 608 of file AuctionItem.cpp.
Referenced by clearAuctionWithdraw(), notifyLoadFromDatabase(), setAuction(), setAuctionedItemObjectID(), setAuctionPremium(), setBidderName(), setBuyerID(), setExpireTime(), setItemDescription(), setItemName(), setItemType(), setOfferToID(), setOnBazaar(), setOwnerID(), setOwnerName(), setPrice(), setProxy(), setStatus(), setVendorID(), and setVendorUID().
DistributedObjectServant * AuctionItem::_getImplementationForRead ()
Definition at line 614 of file AuctionItem.cpp.
Referenced by compareTo(), getAuctionedItemObjectID(), getAuctionOptions(), getBidderName(), getBuyerID(), getExpireTime(), getItemDescription(), getItemName(), getItemType(), getOfferToID(), getOwnerID(), getOwnerName(), getPrice(), getProxy(), getStatus(), getVendorID(), getVendorUID(), isAuction(), isAuctionObject(), isOnBazaar(), isOwner(), and isPremiumAuction().
void AuctionItem::_setImplementation (DistributedObjectServant * servant)
Definition at line 618 of file AuctionItem.cpp.
void AuctionItem::clearAuctionWithdraw ()
Definition at line 241 of file AuctionItem.cpp.
References _getImplementation(), server::zone::objects::auction::AuctionItemImplementation::clearAuctionWithdraw(), and RPC_CLEARAUCTIONWITHDRAW__.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireBidAuction(), and server::zone::managers::auction::AuctionManagerImplementation::expireSale().
int AuctionItem::compareTo (AuctionItem * obj)
Compares object ids of this object with obj
Precondition
{ this object is locked, obj is not null }
Postcondition
{this object is locked }
Parameters
obj SceneObject that will be compared to
Returns
returns 1 if this < obj, -1 if this > obj and 0 if this == obj
Definition at line 33 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::compareTo(), and RPC_COMPARETO__AUCTIONITEM_.
unsigned long long AuctionItem::getAuctionedItemObjectID ()
Definition at line 362 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getAuctionedItemObjectID(), and RPC_GETAUCTIONEDITEMOBJECTID__.
Referenced by server::zone::managers::auction::AuctionsMapImplementation::addBazaarItem(), server::zone::managers::auction::AuctionsMapImplementation::addVendorItem(), server::zone::objects::auction::AuctionItemImplementation::compareTo(), server::zone::managers::auction::AuctionsMapImplementation::deleteItem(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), and AuctionQueryHeadersResponseMessage::dumpItemInfoList().
int AuctionItem::getAuctionOptions ()
Definition at line 555 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getAuctionOptions(), and RPC_GETAUCTIONOPTIONS__.
Referenced by AuctionQueryHeadersResponseMessage::dumpItemInfoList().
String AuctionItem::getBidderName ()
Definition at line 525 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getBidderName(), and RPC_GETBIDDERNAME__.
Referenced by AuctionQueryHeadersResponseMessage::addItemToList(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), AuctionQueryHeadersResponseMessage::dumpItemInfoList(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), and server::zone::managers::auction::AuctionManagerImplementation::refundAuction().
unsigned long long AuctionItem::getBuyerID ()
Definition at line 512 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getBuyerID(), and RPC_GETBUYERID__.
Referenced by AuctionQueryHeadersResponseMessage::dumpItemInfoList().
int AuctionItem::getExpireTime ()
Definition at line 460 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getExpireTime(), and RPC_GETEXPIRETIME__.
Referenced by AuctionQueryHeadersResponseMessage::dumpItemInfoList().
String AuctionItem::getItemDescription ()
Definition at line 540 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getItemDescription(), and RPC_GETITEMDESCRIPTION__.
String AuctionItem::getItemName ()
Definition at line 445 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getItemName(), and RPC_GETITEMNAME__.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::deleteExpiredSale(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), AuctionQueryHeadersResponseMessage::dumpItemNameList(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireBidAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireSale(), and server::zone::managers::auction::AuctionManagerImplementation::refundAuction().
int AuctionItem::getItemType ()
Definition at line 499 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getItemType(), and RPC_GETITEMTYPE__.
Referenced by AuctionQueryHeadersResponseMessage::dumpItemInfoList().
unsigned long long AuctionItem::getOfferToID ()
Definition at line 388 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getOfferToID(), and RPC_GETOFFERTOID__.
unsigned long long AuctionItem::getOwnerID ()
Definition at line 375 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getOwnerID(), and RPC_GETOWNERID__.
Referenced by server::zone::managers::auction::AuctionsMapImplementation::addToCommodityLimit(), AuctionQueryHeadersResponseMessage::dumpItemInfoList(), and server::zone::managers::auction::AuctionsMapImplementation::removeFromCommodityLimit().
String AuctionItem::getOwnerName ()
Definition at line 430 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getOwnerName(), and RPC_GETOWNERNAME__.
Referenced by AuctionQueryHeadersResponseMessage::addItemToList(), server::zone::managers::auction::AuctionManagerImplementation::deleteExpiredSale(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), AuctionQueryHeadersResponseMessage::dumpItemInfoList(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireBidAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireSale(), server::zone::managers::auction::AuctionManagerImplementation::refundAuction(), and server::zone::managers::auction::AuctionManagerImplementation::updateAuctionOwner().
int AuctionItem::getPrice ()
Definition at line 473 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getPrice(), and RPC_GETPRICE__.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), AuctionQueryHeadersResponseMessage::dumpItemInfoList(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), and server::zone::managers::auction::AuctionManagerImplementation::refundAuction().
int AuctionItem::getProxy ()
Definition at line 486 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getProxy(), and RPC_GETPROXY__.
Referenced by AuctionQueryHeadersResponseMessage::dumpItemInfoList().
int AuctionItem::getStatus ()
Definition at line 336 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getStatus(), and RPC_GETSTATUS__.
Referenced by AuctionQueryHeadersResponseMessage::addItemToList(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), AuctionQueryHeadersResponseMessage::dumpItemInfoList(), server::zone::managers::auction::AuctionManagerImplementation::expireSale(), and server::zone::managers::auction::AuctionManagerImplementation::updateAuctionOwner().
unsigned long long AuctionItem::getVendorID ()
Definition at line 349 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getVendorID(), and RPC_GETVENDORID__.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::deleteExpiredSale(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), AuctionQueryHeadersResponseMessage::dumpItemInfoList(), and server::zone::managers::auction::AuctionManagerImplementation::expireAuction().
const String AuctionItem::getVendorUID ()
Definition at line 415 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::getVendorUID(), and RPC_GETVENDORUID__.
Referenced by AuctionQueryHeadersResponseMessage::addItemToList(), and AuctionQueryHeadersResponseMessage::dumpItemInfoList().
bool AuctionItem::isAuction ()
Definition at line 323 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::isAuction(), and RPC_ISAUCTION__.
Referenced by AuctionQueryHeadersResponseMessage::addItemToList(), and AuctionQueryHeadersResponseMessage::dumpItemInfoList().
bool AuctionItem::isAuctionObject ()
Definition at line 595 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::isAuctionObject(), and RPC_ISAUCTIONOBJECT__.
bool AuctionItem::isOnBazaar ()
Definition at line 310 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::isOnBazaar(), and RPC_ISONBAZAAR__.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::checkBidAuction(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireBidAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireSale(), and server::zone::managers::auction::AuctionManagerImplementation::updateAuctionOwner().
bool AuctionItem::isOwner (CreatureObject * player)
Definition at line 581 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::isOwner(), and RPC_ISOWNER__CREATUREOBJECT_.
bool AuctionItem::isPremiumAuction ()
Definition at line 568 of file AuctionItem.cpp.
References _getImplementationForRead(), server::zone::objects::auction::AuctionItemImplementation::isPremiumAuction(), and RPC_ISPREMIUMAUCTION__.
void AuctionItem::notifyLoadFromDatabase ()
Definition at line 47 of file AuctionItem.cpp.
References _getImplementation(), server::zone::objects::auction::AuctionItemImplementation::notifyLoadFromDatabase(), and RPC_NOTIFYLOADFROMDATABASE__.
void AuctionItem::setAuction (bool isAuction)
Definition at line 214 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETAUCTION__BOOL_, and server::zone::objects::auction::AuctionItemImplementation::setAuction().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem().
void AuctionItem::setAuctionedItemObjectID (unsigned long long objectID)
Definition at line 130 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETAUCTIONEDITEMOBJECTID__LONG_, and server::zone::objects::auction::AuctionItemImplementation::setAuctionedItemObjectID().
void AuctionItem::setAuctionPremium ()
Definition at line 228 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETAUCTIONPREMIUM__, and server::zone::objects::auction::AuctionItemImplementation::setAuctionPremium().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem().
void AuctionItem::setBidderName (const String & name)
Definition at line 186 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETBIDDERNAME__STRING_, and server::zone::objects::auction::AuctionItemImplementation::setBidderName().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), and server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy().
void AuctionItem::setBuyerID (unsigned long long id)
Definition at line 282 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETBUYERID__LONG_, and server::zone::objects::auction::AuctionItemImplementation::setBuyerID().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), and server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy().
void AuctionItem::setExpireTime (int time)
Definition at line 268 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETEXPIRETIME__INT_, and server::zone::objects::auction::AuctionItemImplementation::setExpireTime().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireBidAuction(), and server::zone::managers::auction::AuctionManagerImplementation::expireSale().
void AuctionItem::setItemDescription (const String & descr)
Definition at line 88 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETITEMDESCRIPTION__STRING_, and server::zone::objects::auction::AuctionItemImplementation::setItemDescription().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem().
void AuctionItem::setItemName (const String & name)
Definition at line 74 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETITEMNAME__STRING_, and server::zone::objects::auction::AuctionItemImplementation::setItemName().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem().
void AuctionItem::setItemType (int type)
Definition at line 144 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETITEMTYPE__INT_, and server::zone::objects::auction::AuctionItemImplementation::setItemType().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem().
void AuctionItem::setOfferToID (unsigned long long vendorOwnerID)
Definition at line 172 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETOFFERTOID__LONG_, and server::zone::objects::auction::AuctionItemImplementation::setOfferToID().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem().
void AuctionItem::setOnBazaar (bool val)
Definition at line 254 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETONBAZAAR__BOOL_, and server::zone::objects::auction::AuctionItemImplementation::setOnBazaar().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem().
void AuctionItem::setOwnerID (unsigned long long ownerObjectID)
Definition at line 158 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETOWNERID__LONG_, and server::zone::objects::auction::AuctionItemImplementation::setOwnerID().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::updateAuctionOwner().
void AuctionItem::setOwnerName (const String & name)
Definition at line 200 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETOWNERNAME__STRING_, and server::zone::objects::auction::AuctionItemImplementation::setOwnerName().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::updateAuctionOwner().
void AuctionItem::setPrice (int newPrice)
Definition at line 102 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETPRICE__INT_, and server::zone::objects::auction::AuctionItemImplementation::setPrice().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), and server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid().
void AuctionItem::setProxy (int newProxy)
Definition at line 116 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETPROXY__INT_, and server::zone::objects::auction::AuctionItemImplementation::setProxy().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid().
void AuctionItem::setStatus (int value)
Definition at line 296 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETSTATUS__INT_, and server::zone::objects::auction::AuctionItemImplementation::setStatus().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireBidAuction(), and server::zone::managers::auction::AuctionManagerImplementation::expireSale().
void AuctionItem::setVendorID (unsigned long long val)
Definition at line 60 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETVENDORID__LONG_, and server::zone::objects::auction::AuctionItemImplementation::setVendorID().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem().
void AuctionItem::setVendorUID (const String & uid)
Definition at line 401 of file AuctionItem.cpp.
References _getImplementation(), RPC_SETVENDORUID__STRING_, and server::zone::objects::auction::AuctionItemImplementation::setVendorUID().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem().
Friends And Related Function Documentation
friend class AuctionItemHelper friend
Definition at line 174 of file AuctionItem.h.
Member Data Documentation
const int server::zone::objects::auction::AuctionItem::EXPIRED = 4 static
Definition at line 65 of file AuctionItem.h.
const int server::zone::objects::auction::AuctionItem::FORSALE = 1 static
Definition at line 61 of file AuctionItem.h.
const int server::zone::objects::auction::AuctionItem::OFFERED = 5 static
Definition at line 67 of file AuctionItem.h.
const int server::zone::objects::auction::AuctionItem::OPTION_PREMIUM = 0x400 static
Definition at line 57 of file AuctionItem.h.
const int server::zone::objects::auction::AuctionItem::OPTION_WITHDRAW = 0x800 static
Definition at line 59 of file AuctionItem.h.
const int server::zone::objects::auction::AuctionItem::RETRIEVED = 6 static
Definition at line 69 of file AuctionItem.h.
const int server::zone::objects::auction::AuctionItem::SOLD = 2 static
Definition at line 63 of file AuctionItem.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/auction/AuctionItem.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/auction/AuctionItem.cpp