Core3: server::zone::managers::minigames::FishingManagerImplementation Class Reference
server::zone::managers::minigames::FishingManagerImplementation Class Reference
#include <FishingManager.h>
Public Member Functions
FishingManagerImplementation ()
FishingManagerImplementation (DummyConstructorParameter *param)
void initializeBaitStatus ()
void initializeProperty ()
void initializeAction ()
void initializeState ()
void initializeFishType ()
void initializeFishLength ()
void initializeLoot ()
void initializeColor ()
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void checkFishingOnPositionUpdate (CreatureObject *player)
int notifyCloseContainer (CreatureObject *player, SceneObject *container)
int checkLocation (CreatureObject *player, int quality, float &x, float &y, float &z)
int startFishing (CreatureObject *player)
void stopFishing (CreatureObject *player, unsigned int boxID, bool rem)
void fishingStep (CreatureObject *player)
void success (CreatureObject *player, int fish, SceneObject *marker, unsigned int boxID)
String getTime ()
void sendReward (CreatureObject *player, SceneObject *marker, SceneObject *loot)
unsigned int createWindow (CreatureObject *player, unsigned int boxID)
void closeMenu (CreatureObject *player, unsigned int boxID)
int vegetation (SceneObject *marker)
int density (SceneObject *marker)
int getFish (CreatureObject *player)
int getNextAction (CreatureObject *player)
void setNextAction (CreatureObject *player, int next)
FishingPoleObject * getPole (CreatureObject *player)
FishingBaitObject * getBait (CreatureObject *player)
unsigned int getFishBoxID (CreatureObject *player)
void setFishBoxID (CreatureObject *player, unsigned int boxID)
int getFishingState (CreatureObject *player)
void setFishingState (CreatureObject *player, int state)
SceneObject * getFishMarker (CreatureObject *player)
void setFishMarker (CreatureObject *player, SceneObject *marker)
void freeBait (CreatureObject *player)
void fishingProceed (CreatureObject *player, int nextAction, SceneObject *marker, int fish, unsigned int boxID, int newstate, bool notifyClient, String &moodString)
void mishapEvent (const String &text, CreatureObject *player, unsigned int boxID, bool losebait, String &moodString)
bool loseBait (CreatureObject *player)
void animate (CreatureObject *player, int nextAction)
SceneObject * createMarker (float x, float y, float z, Zone *zone)
void createSplash (float x, float y, float z, Zone *zone, CreatureObject *player)
bool checkUpdateMarker (CreatureObject *player, float &x, float &y, float &z)
bool isPlaying (CreatureObject *player)
SceneObject * updateMarker (CreatureObject *player, SceneObject *marker, bool notifyPlayer)
void removeMarker (CreatureObject *player, SceneObject *container)
void removeSplash (SceneObject *splash)
void createFishingSplashEvent (CreatureObject *player, SceneObject *splash)
void createFishingSession (CreatureObject *player, FishingEvent *event, SceneObject *marker, int nextAction, int fish, unsigned int boxID, int fishingState, String &mood)
FishingEvent * createFishingEvent (CreatureObject *player, int state)
void stopFishingEvent (CreatureObject *player)
FishingEvent * getFishingEvent (CreatureObject *player)
operator const FishingManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< FishingManager * > _this
Static Public Attributes
static const int NOTFISHING = 0
static const int WAITING = 1
static const int SNAGGED = 2
static const int NIBBLE = 3
static const int BITE = 4
static const int CATCH = 5
static const int REELING = 6
static const int REELGAME = 7
static const int BLACKFISH = 0
static const int BLOWFISH = 1
static const int BLUEFISH = 2
static const int FAA = 3
static const int LAA = 4
static const int RAY = 5
static const int STRIPED = 6
static const int FRESH = 0
static const int SOGGY = 6
static const int MUSH = 10
static const int DONOTHING = 0
static const int TUGUP = 1
static const int TUGRIGHT = 2
static const int TUGLEFT = 3
static const int REEL = 4
static const int STOPFISHING = 5
static const int NOEVENT = 0
static const int PROCEED = 17
static const int MISHAP = 45
Protected Member Functions
virtual ~FishingManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
Vector< String > miscLoot
Vector< String > rareLoot
VectorMap< String, int > color
Vector< int > fishLength
Vector< String > fishType
Vector< String > state
Vector< String > action
Vector< String > property
Vector< String > baitStatus
Friends
class FishingManager
Detailed Description
Definition at line 725 of file FishingManager.h.
Constructor & Destructor Documentation
FishingManagerImplementation::FishingManagerImplementation ()
Definition at line 995 of file FishingManager.cpp.
References _initializeImplementation(), initializeAction(), initializeBaitStatus(), initializeColor(), initializeFishLength(), initializeFishType(), initializeLoot(), initializeProperty(), and initializeState().
FishingManagerImplementation::FishingManagerImplementation (DummyConstructorParameter * param)
Definition at line 773 of file FishingManager.cpp.
References _initializeImplementation().
FishingManagerImplementation::~FishingManagerImplementation () protected virtual
Definition at line 778 of file FishingManager.cpp.
Member Function Documentation
DistributedObjectStub * FishingManagerImplementation::_getStub ()
Definition at line 798 of file FishingManager.cpp.
References _this.
void FishingManagerImplementation::_initializeImplementation () protected
Definition at line 785 of file FishingManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by FishingManagerImplementation().
void FishingManagerImplementation::_serializationHelperMethod () protected
Definition at line 834 of file FishingManager.cpp.
Referenced by _initializeImplementation().
void FishingManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 793 of file FishingManager.cpp.
References _this.
Referenced by server::zone::managers::minigames::FishingManager::FishingManager().
void FishingManagerImplementation::animate (CreatureObject * player, int nextAction)
Does Player Animations for different fishing actions animate switches through nextAction and calls appropriate Animations
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to doAnimation()
nextAction index used to decide which animation to play
Definition at line 959 of file FishingManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::doAnimation(), REEL, TUGLEFT, TUGRIGHT, and TUGUP.
Referenced by server::zone::managers::minigames::FishingManager::animate(), and fishingStep().
void FishingManagerImplementation::checkFishingOnPositionUpdate (CreatureObject * player)
Checks for Player movement checkFishingOnPositionUpdate is called from notify(SceneObject) by the observer pattern The method locks the manager since it is a new entry point into the manager Based on the Fishing State and the position change, fishing might be stopped if the Player goes in too deep (starts swimming) or moves too far from the marker for the line or if the Player moves within 2.0 distance of the marker, attempts to reel in either succeeding or stopping fishing because no fish was caught yet.
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject to check movement for
Definition at line 1279 of file FishingManagerImplementation.cpp.
References SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), getFishingState(), server::zone::managers::minigames::FishingSession::getMarker(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::CreatureObject::isSwimming(), server::zone::managers::minigames::FishingManager::NOTFISHING, server::zone::managers::minigames::FishingManager::REELING, stopFishing(), and success().
Referenced by server::zone::managers::minigames::FishingManager::checkFishingOnPositionUpdate(), and notifyObserverEvent().
int FishingManagerImplementation::checkLocation (CreatureObject * player, int quality, float & x, float & y, float & z)
check location of Player and return the marker position checkLocation gets the PositionX/Y/Z from Player computing new coordinates based on quality of the fishing pole
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject used for coordinate calculation
quality Crafted Quality of the Fishing Pole
x x-Coordinate to be filled with marker position
y y-Coordinate to be filled with marker position
z z-Coordinate to be filled with marker position
Returns
{ 0: everything worked, 1: Exception case, 3: No Water, 4: Water under terrain } { once actually craftable the line range calculation probably needs to be adjusted to affect the outcome less }
Definition at line 31 of file FishingManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDirectionAngle(), server::zone::Zone::getHeight(), server::zone::Zone::getPlanetManager(), server::zone::managers::planet::PlanetManager::getTerrainManager(), TerrainManager::getWaterHeight(), and server::zone::objects::scene::SceneObject::getZone().
Referenced by server::zone::managers::minigames::FishingManager::checkLocation(), and startFishing().
bool FishingManagerImplementation::checkUpdateMarker (CreatureObject * player, float & x, float & y, float & z)
Checks whether the fish has beached checkUpdateMarker is called by updateMarker to see if the new position is in Water
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to check
x X-Coordinate of the splash
y Y-Coordinate of the splash
z Z-Coordinate of the splash
Returns
{ true if beached, false if water }
Definition at line 1017 of file FishingManagerImplementation.cpp.
References server::zone::Zone::getHeight(), server::zone::Zone::getPlanetManager(), server::zone::managers::planet::PlanetManager::getTerrainManager(), TerrainManager::getWaterHeight(), and server::zone::objects::scene::SceneObject::getZone().
Referenced by server::zone::managers::minigames::FishingManager::checkUpdateMarker(), and updateMarker().
void FishingManagerImplementation::closeMenu (CreatureObject * player, unsigned int boxID)
Closes the FishingMenu closeMenu checks for valid boxID and Player and sends the close message, removing the sui box from the player
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to close window
boxID Fishing window being closed
Definition at line 582 of file FishingManagerImplementation.cpp.
References SuiWindowType::FISHING, server::zone::objects::creature::CreatureObject::getPlayerObject(), and server::zone::objects::player::PlayerObject::removeSuiBoxType().
Referenced by server::zone::managers::minigames::FishingManager::closeMenu(), createWindow(), fishingStep(), and stopFishing().
FishingEvent * FishingManagerImplementation::createFishingEvent (CreatureObject * player, int state)
Creates a Fishing Event schedule 7000 createFishingEvent creates a new Fishing Event given the State
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to create Fishing Event
zoneServer ZoneServer used
state FishingState the player is in
Definition at line 1215 of file FishingManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::addPendingTask(), CATCH, and server::zone::objects::scene::SceneObject::removePendingTask().
Referenced by server::zone::managers::minigames::FishingManager::createFishingEvent(), fishingProceed(), mishapEvent(), and startFishing().
void FishingManagerImplementation::createFishingSession (CreatureObject * player, FishingEvent * event, SceneObject * marker, int nextAction, int fish, unsigned int boxID, int fishingState, String & mood)
Creates a FishingSession createFishingSession creates a new FishingSession given the player, event, nextAction, the marker, the FishType as sum, the fishing window, the State and the mood and puts it into VectorMap sessions
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to create FishingSession
event Current FishingEvent
nextAction Action to be executed
marker The fish marker being used
sum Integer indicating fish
boxID Fishing window to later close
state FishingState the player is in
moodString String taken from player before fishing to return to after fishing
Definition at line 1208 of file FishingManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::addActiveSession(), and SessionFacadeType::FISHING.
Referenced by server::zone::managers::minigames::FishingManager::createFishingSession(), and startFishing().
void FishingManagerImplementation::createFishingSplashEvent (CreatureObject * player, SceneObject * splash)
Creates a Splash Event schedule 1000 createFishingSplashEvent creates a new FishingSplashEvent for the given SceneObject and schedules it to 1000 so the Splash is removed after 1 second
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to create Splash Event
zoneServer ZoneServer used
splash SceneObject to remove later
Definition at line 1200 of file FishingManagerImplementation.cpp.
Referenced by server::zone::managers::minigames::FishingManager::createFishingSplashEvent(), and createSplash().
SceneObject * FishingManagerImplementation::createMarker (float x, float y, float z, Zone * zone)
Creates a marker object at the given coordinates createMarker creates a SceneObject for tango/fishing/shared_marker.iff and inserts it at given coordinates
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
x X-Coordinate of new marker
y Y-Coordinate of new marker
z Z-Coordinate of new marker
zone Zone used to create the marker in
Returns
{ SceneObject of new marker }
Definition at line 982 of file FishingManagerImplementation.cpp.
References _this, ObserverEventType::CLOSECONTAINER, server::zone::ZoneServer::createObject(), server::zone::Zone::getZoneServer(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::managers::minigames::FishingManager::createMarker(), startFishing(), and updateMarker().
void FishingManagerImplementation::createSplash (float x, float y, float z, Zone * zone, CreatureObject * player)
Creates a small Splash at the given coordinates createSplash creates a SceneObject for tango/fishing/shared_splash.iff and inserts it at given coordinates a FishingSplashEvent is created so that the splash is removed in due time
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
x X-Coordinate of the splash
y Y-Coordinate of the splash
z Z-Coordinate of the splash
zone Zone used to create the splash in
player CreatureObject for which to create fishing splash event
Definition at line 1002 of file FishingManagerImplementation.cpp.
References createFishingSplashEvent(), server::zone::ZoneServer::createObject(), server::zone::objects::scene::SceneObject::getZoneServer(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::managers::minigames::FishingManager::createSplash(), fishingProceed(), startFishing(), and stopFishing().
uint32 FishingManagerImplementation::createWindow (CreatureObject * player, unsigned int boxID)
Creates a Fishing Window createWindow closes the old menu and creates a new one based on vegetation, density, freshness etc
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to open a new window
boxID Old fishing window to close
Returns
{ -1: problem, otherwise uint32 boxID of new window }
Definition at line 520 of file FishingManagerImplementation.cpp.
References action, baitStatus, closeMenu(), density(), SuiWindowType::FISHING, getBait(), server::zone::objects::scene::SceneObject::getDistanceTo(), getFishingState(), getFishMarker(), getNextAction(), server::zone::objects::creature::CreatureObject::getPlayerObject(), MUSH, server::zone::objects::creature::CreatureObject::sendMessage(), SOGGY, state, and vegetation().
Referenced by server::zone::managers::minigames::FishingManager::createWindow(), fishingProceed(), mishapEvent(), and startFishing().
int FishingManagerImplementation::density (SceneObject * marker)
Calculates density based on current Position density returns a value 0-5 based on abs(PositionY/100) rounded up { Actually make density a property of a body of water }
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
marker Fishing marker to get coordinates of to calculate the fish density
Returns
{ 0-5 }
Definition at line 597 of file FishingManagerImplementation.cpp.
Referenced by createWindow(), server::zone::managers::minigames::FishingManager::density(), fishingStep(), and getFish().
void FishingManagerImplementation::finalize () protected
Definition at line 782 of file FishingManager.cpp.
void FishingManagerImplementation::fishingProceed (CreatureObject * player, int nextAction, SceneObject * marker, int fish, unsigned int boxID, int newstate, bool notifyClient, String & moodString)
fishingProceed notifies the Player and create the new Event fishingProceed is called from FishingStep unless fishing has ended It will notify the Player through fly text and system messages of what is going on
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to proceed fishing
nextAction action taken by player
marker Fish marker used to create splash at
fish Integer carried along to know what fish is currently biting
boxID window to close when creating new window
newstate The new state for the player to know from where and where to the transition is taking place
notifyClient If true the marker was updated and the player will be informed that the fish was brought closer
moodString String taken from player before fishing to return to after fishing
Definition at line 794 of file FishingManagerImplementation.cpp.
References BITE, CATCH, createFishingEvent(), createSplash(), createWindow(), DONOTHING, SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), getBait(), getFishingState(), server::zone::objects::scene::SceneObject::getZone(), NIBBLE, REEL, REELGAME, REELING, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::SceneObject::showFlyText(), and SNAGGED.
Referenced by server::zone::managers::minigames::FishingManager::fishingProceed(), and fishingStep().
void FishingManagerImplementation::fishingStep (CreatureObject * player)
fishingStep gets called from FishingEvent::run() fishingStep closes the menu, gets the current state and computes two random numbers If the player hasnt reached CATCH state yet and the bait is MUSH, it will be tossed and fishing ends
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject which is currently fishing
Definition at line 167 of file FishingManagerImplementation.cpp.
References animate(), BITE, CATCH, closeMenu(), density(), DONOTHING, SessionFacadeType::FISHING, fishingProceed(), server::zone::objects::scene::SceneObject::getActiveSession(), getBait(), getFish(), server::zone::managers::minigames::FishingSession::getNextAction(), getPole(), server::zone::objects::scene::SceneObject::isInRange(), MISHAP, mishapEvent(), NIBBLE, PROCEED, REEL, REELGAME, REELING, SNAGGED, SOGGY, state, success(), TUGLEFT, TUGUP, updateMarker(), vegetation(), and WAITING.
Referenced by server::zone::managers::minigames::FishingManager::fishingStep().
void FishingManagerImplementation::freeBait (CreatureObject * player)
Hands out free Bait freeBait is used for debugging: in case the Pole is empty, a bait will be created and added to the pole { Remove this and it's call at FishCommand when testing is complete }
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to put free bait into the fishing pole
Definition at line 780 of file FishingManagerImplementation.cpp.
References server::zone::ZoneServer::createObject(), getPole(), and server::zone::objects::scene::SceneObject::getZoneServer().
Referenced by server::zone::managers::minigames::FishingManager::freeBait().
FishingBaitObject * FishingManagerImplementation::getBait (CreatureObject * player)
Gets Bait from Pole getBait gets the pole from the Player, looks into the Container and if there's an object in it returns it
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get fishing bait
Returns
{ FishingBaitObject or NULL }
Definition at line 678 of file FishingManagerImplementation.cpp.
References _this, and getPole().
Referenced by createWindow(), fishingProceed(), fishingStep(), server::zone::managers::minigames::FishingManager::getBait(), getFish(), and startFishing().
int FishingManagerImplementation::getFish (CreatureObject * player)
Calculates Fish biting getFish calculates a random number 0-99 and, if it's a fish (<94) calculates what kind of fish based on pole quality, vegetation penalty, fish density bonus, bait status, and a random number
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to randomize fish
Returns
{ 0-6: Fish, 94-99: Misc Item }
Definition at line 605 of file FishingManagerImplementation.cpp.
References density(), getBait(), getPole(), and vegetation().
Referenced by fishingStep(), server::zone::managers::minigames::FishingManager::getFish(), and mishapEvent().
uint32 FishingManagerImplementation::getFishBoxID (CreatureObject * player)
Gets Fishing Window ID from Event getFishBoxID gets the Event linked to a player and returns the fishBoxID from it
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get fishing event's fishBoxID
Returns
{ boxID or -1 }
Definition at line 702 of file FishingManagerImplementation.cpp.
References SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), and server::zone::managers::minigames::FishingSession::getFishBoxID().
Referenced by server::zone::managers::minigames::FishingManager::getFishBoxID(), and stopFishing().
FishingEvent * FishingManagerImplementation::getFishingEvent (CreatureObject * player)
FishingEvent getter getFishingEvent is a readonly method that gets the FishingEvent from the events VectorMap and returns it
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to get fishing event
Definition at line 1253 of file FishingManagerImplementation.cpp.
References SessionFacadeType::FISHING, and server::zone::objects::scene::SceneObject::getActiveSession().
Referenced by server::zone::managers::minigames::FishingManager::getFishingEvent(), stopFishing(), and stopFishingEvent().
int FishingManagerImplementation::getFishingState (CreatureObject * player)
Gets fishing state from Event getFishingState gets the Event linked to the player and returns the FishingState, NOTFISHING if there is no event
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get the fishing event's fishing state
Returns
{ 0-6 }
Definition at line 726 of file FishingManagerImplementation.cpp.
References SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), NOTFISHING, REELGAME, and state.
Referenced by checkFishingOnPositionUpdate(), createWindow(), fishingProceed(), server::zone::managers::minigames::FishingManager::getFishingState(), and updateMarker().
SceneObject * FishingManagerImplementation::getFishMarker (CreatureObject * player)
Gets Fish Marker in Event getFishMarker gets the Event linked to the player and returns the Marker of the Event, even if it is NULL
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get the event's fish marker
Returns
{ NULL: player is NULL, player: no fishing event, FishMarker otherwise }
Definition at line 757 of file FishingManagerImplementation.cpp.
References SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), and server::zone::managers::minigames::FishingSession::getMarker().
Referenced by createWindow(), server::zone::managers::minigames::FishingManager::getFishMarker(), mishapEvent(), removeMarker(), and stopFishing().
int FishingManagerImplementation::getNextAction (CreatureObject * player)
Gets Next Action from Event getNextAction gets the Event linked to the Player and returns the next action, if the player or the event are NULL the value DONOTHING(=0) is returned
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get the fishing event's nextAction member
Returns
{ 0-5: Next Action }
Definition at line 633 of file FishingManagerImplementation.cpp.
References DONOTHING, SessionFacadeType::FISHING, and server::zone::objects::scene::SceneObject::getActiveSession().
Referenced by createWindow(), and server::zone::managers::minigames::FishingManager::getNextAction().
FishingPoleObject * FishingManagerImplementation::getPole (CreatureObject * player)
Gets Pole from Player getPole gets the SceneObject in the Players right hand and, unless it is NULL, checks whether it is a fishing pole and returns it
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to get fishing pole
Returns
{ FishingPoleObject or NULL }
Definition at line 660 of file FishingManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::scene::SceneObject::isFishingPoleObject().
Referenced by fishingStep(), freeBait(), getBait(), getFish(), server::zone::managers::minigames::FishingManager::getPole(), startFishing(), and success().
String FishingManagerImplementation::getTime ()
Returns timestamp as string Takes current time and returns formatted String
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
{ String of time }
Definition at line 370 of file FishingManagerImplementation.cpp.
Referenced by server::zone::managers::minigames::FishingManager::getTime(), and success().
void FishingManagerImplementation::initializeAction ()
Definition at line 1043 of file FishingManager.cpp.
References action.
Referenced by FishingManagerImplementation(), and server::zone::managers::minigames::FishingManager::initializeAction().
void FishingManagerImplementation::initializeBaitStatus ()
Definition at line 1019 of file FishingManager.cpp.
References baitStatus.
Referenced by FishingManagerImplementation(), and server::zone::managers::minigames::FishingManager::initializeBaitStatus().
void FishingManagerImplementation::initializeColor ()
Definition at line 1120 of file FishingManager.cpp.
References color.
Referenced by FishingManagerImplementation(), and server::zone::managers::minigames::FishingManager::initializeColor().
void FishingManagerImplementation::initializeFishLength ()
Definition at line 1092 of file FishingManager.cpp.
References fishLength.
Referenced by FishingManagerImplementation(), and server::zone::managers::minigames::FishingManager::initializeFishLength().
void FishingManagerImplementation::initializeFishType ()
Definition at line 1075 of file FishingManager.cpp.
References fishType.
Referenced by FishingManagerImplementation(), and server::zone::managers::minigames::FishingManager::initializeFishType().
void FishingManagerImplementation::initializeLoot ()
Definition at line 1109 of file FishingManager.cpp.
References miscLoot, and rareLoot.
Referenced by FishingManagerImplementation(), and server::zone::managers::minigames::FishingManager::initializeLoot().
void FishingManagerImplementation::initializeProperty ()
Definition at line 1028 of file FishingManager.cpp.
References property.
Referenced by FishingManagerImplementation(), and server::zone::managers::minigames::FishingManager::initializeProperty().
void FishingManagerImplementation::initializeState ()
Definition at line 1058 of file FishingManager.cpp.
References state.
Referenced by FishingManagerImplementation(), and server::zone::managers::minigames::FishingManager::initializeState().
bool FishingManagerImplementation::isPlaying (CreatureObject * player)
Definition at line 1267 of file FishingManagerImplementation.cpp.
References SessionFacadeType::FISHING, and server::zone::objects::scene::SceneObject::getActiveSession().
Referenced by server::zone::managers::minigames::FishingManager::isPlaying().
void FishingManagerImplementation::lock (bool doLock = true) protected
Definition at line 806 of file FishingManager.cpp.
References _this.
void FishingManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 810 of file FishingManager.cpp.
References _this.
bool FishingManagerImplementation::loseBait (CreatureObject * player)
Lose the Bait in the Container loseBait gets the pole and removes the object from that container { For stacks (more than 1 of the bait) remove just one of it }
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to remove bait from pole
Returns
{ true if bait was removed }
Definition at line 925 of file FishingManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getSlottedObject().
Referenced by server::zone::managers::minigames::FishingManager::loseBait(), and mishapEvent().
void FishingManagerImplementation::mishapEvent (const String & text, CreatureObject * player, unsigned int boxID, bool losebait, String & moodString)
mishapEvent stops Fishing out of bad luck, possibly losing bait in the process mishapEvent uses the argument string and sends it to the Player, stops Fishing and if losebait is true, calls loseBait
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
text String to send to Player
player CreatureObject to which send message
boxID fishing window to close when calling stopFishing()
losebait If true the bait in the pole will be removed as an outcome of what happened
moodString String taken from player before fishing to return to after fishing
Definition at line 901 of file FishingManagerImplementation.cpp.
References createFishingEvent(), createWindow(), DONOTHING, SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), getFish(), getFishMarker(), loseBait(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), stopFishing(), and WAITING.
Referenced by fishingStep(), and server::zone::managers::minigames::FishingManager::mishapEvent().
int FishingManagerImplementation::notifyCloseContainer (CreatureObject * player, SceneObject * container)
Removes the Marker notifyCloseContainer is called when the registered Marker is closed.
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject to remove Marker from
Definition at line 1271 of file FishingManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::dropActiveSession(), SessionFacadeType::FISHING, and removeMarker().
Referenced by server::zone::managers::minigames::FishingManager::notifyCloseContainer(), and notifyObserverEvent().
int FishingManagerImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 1143 of file FishingManager.cpp.
References checkFishingOnPositionUpdate(), ObserverEventType::CLOSECONTAINER, notifyCloseContainer(), and ObserverEventType::POSITIONCHANGED.
Referenced by server::zone::managers::minigames::FishingManager::notifyObserverEvent().
FishingManagerImplementation::operator const FishingManager * ()
Definition at line 802 of file FishingManager.cpp.
void FishingManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 841 of file FishingManager.cpp.
References readObjectMember().
bool FishingManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 860 of file FishingManager.cpp.
References action, baitStatus, color, fishLength, fishType, miscLoot, property, rareLoot, and state.
Referenced by readObject().
void FishingManagerImplementation::removeMarker (CreatureObject * player, SceneObject * container)
Removes the fishing marker removeMarker sets the Marker in the Event to NULL and removes the marker from Zone it is only called where it is set to a new marker, or the event is stopped, so the NULL won't cause problems
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject to get Event to remove marker from
container Container to remove
Definition at line 1147 of file FishingManagerImplementation.cpp.
References getFishMarker(), and setFishMarker().
Referenced by notifyCloseContainer(), server::zone::managers::minigames::FishingManager::removeMarker(), stopFishing(), and updateMarker().
void FishingManagerImplementation::removeSplash (SceneObject * splash)
Removes the Splash removeSplash is called from FishingSplashEvent, the splash is simply removed from zone
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
splash SceneObject to remove from Zone
Definition at line 1188 of file FishingManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), and server::zone::objects::scene::SceneObject::isPlayerCreature().
Referenced by server::zone::managers::minigames::FishingManager::removeSplash().
void FishingManagerImplementation::rlock (bool doLock = true) protected
Definition at line 814 of file FishingManager.cpp.
References _this.
void FishingManagerImplementation::runlock (bool doLock = true) protected
Definition at line 830 of file FishingManager.cpp.
References _this.
void FishingManagerImplementation::sendReward (CreatureObject * player, SceneObject * marker, SceneObject * loot)
Sends loot to Player sendReward receives Player, the Marker and the created Object, adds the object to the marker, opens the Container to the Player and sends appropriate SystemMessage
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject receiving item
marker Container for item
loot Item to send to Player
Definition at line 498 of file FishingManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getContainerPermissions(), server::zone::objects::scene::variables::StringId::getFullPath(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getObjectName(), server::zone::objects::scene::SceneObject::openContainerTo(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::SceneObject::sendTo(), server::zone::objects::scene::variables::ContainerPermissions::setOwner(), server::chat::StringIdChatParameter::setTT(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::managers::minigames::FishingManager::sendReward(), and success().
void FishingManagerImplementation::setFishBoxID (CreatureObject * player, unsigned int boxID)
Sets Window BoxID in Event setFishBoxID gets the event linked to the player and sets the fishBoxID to the argument given boxID
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to modify the fishing event
boxID fishing window to point to
Definition at line 715 of file FishingManagerImplementation.cpp.
References SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), and server::zone::managers::minigames::FishingSession::setFishBoxID().
Referenced by server::zone::managers::minigames::FishingManager::setFishBoxID().
void FishingManagerImplementation::setFishingState (CreatureObject * player, int state)
Sets fishing state in Event setFishingState gets the Event linked to the player and sets the FishingState to the argument-given state unless it's NULL
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to set the fishing event's fishing state
state Integer value sent to event
Definition at line 743 of file FishingManagerImplementation.cpp.
References SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), NOTFISHING, REELGAME, and server::zone::managers::minigames::FishingSession::setFishingState().
Referenced by server::zone::managers::minigames::FishingManager::setFishingState(), and stopFishing().
void FishingManagerImplementation::setFishMarker (CreatureObject * player, SceneObject * marker)
Sets Fish Marker in Event setFishMarker gets the Event linked to the player and sets it's marker to the argument-given marker there is an intended call that sets the marker in the event to NULL
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to set the event's fish marker
marker Marker sent to event
Definition at line 770 of file FishingManagerImplementation.cpp.
References SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), and server::zone::managers::minigames::FishingSession::setMarker().
Referenced by removeMarker(), server::zone::managers::minigames::FishingManager::setFishMarker(), and updateMarker().
void FishingManagerImplementation::setNextAction (CreatureObject * player, int next)
Sets Next Action on Fishing Event setNextAction gets the Fishing Event linked to the Player and sets it's Action to the argument unless it is out of acceptable bounds
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject for which to modify the fishing event
next Integer index of Action selected by Player
Definition at line 645 of file FishingManagerImplementation.cpp.
References DONOTHING, SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::managers::minigames::FishingSession::setNextAction(), and STOPFISHING.
Referenced by server::zone::managers::minigames::FishingManager::setNextAction().
int FishingManagerImplementation::startFishing (CreatureObject * player)
Starts Fishing Game startFishing checks for Fishing Pole, Fishing Bait and Water at the position of the bobber, creates the bobber and opens the window for Fishing.
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject which wants to start fishing
Returns
{ 0: everything worked, 1: No Pole, 2: No Bait, 3: No Water, 4: Water under terrain, 5: Player Swimming, 6: Exception case }
Definition at line 57 of file FishingManagerImplementation.cpp.
References _this, checkLocation(), createFishingEvent(), createFishingSession(), createMarker(), createSplash(), createWindow(), server::zone::objects::creature::CreatureObject::doAnimation(), DONOTHING, SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), getBait(), server::zone::objects::creature::CreatureObject::getMoodString(), getPole(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isSwimming(), ObserverEventType::POSITIONCHANGED, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::managers::minigames::FishingSession::setFishBoxID(), server::zone::objects::creature::CreatureObject::setMoodString(), and WAITING.
Referenced by server::zone::managers::minigames::FishingManager::startFishing().
void FishingManagerImplementation::stopFishing (CreatureObject * player, unsigned int boxID, bool rem)
Stops Fishing Game stopFishing sets fishing state to NOTFISHING, creates a new splash (marker disappearing), closes the menu, removes the marker and stops the event
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject which wants to stop fishing
boxID Fishing window to close
rem if true removes Marker, false when called by successful catch so the container won't disappear
Definition at line 122 of file FishingManagerImplementation.cpp.
References _this, closeMenu(), createSplash(), server::zone::objects::creature::CreatureObject::doAnimation(), server::zone::objects::scene::SceneObject::dropActiveSession(), SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), getFishBoxID(), getFishingEvent(), getFishMarker(), server::zone::managers::minigames::FishingSession::getMoodString(), server::zone::objects::scene::SceneObject::getZone(), NOTFISHING, ObserverEventType::POSITIONCHANGED, removeMarker(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), setFishingState(), server::zone::objects::creature::CreatureObject::setMoodString(), and stopFishingEvent().
Referenced by checkFishingOnPositionUpdate(), mishapEvent(), server::zone::managers::minigames::FishingManager::stopFishing(), success(), and updateMarker().
void FishingManagerImplementation::stopFishingEvent (CreatureObject * player)
Stops Fishing Event stopFishingEvent gets the FishingEvent for a player, drops it from the VectorMap and cancels it
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to stop the fishing event
Definition at line 1233 of file FishingManagerImplementation.cpp.
References SessionFacadeType::FISHING, server::zone::objects::scene::SceneObject::getActiveSession(), getFishingEvent(), server::zone::objects::scene::SceneObject::removePendingTask(), and server::zone::managers::minigames::FishingSession::setEvent().
Referenced by stopFishing(), and server::zone::managers::minigames::FishingManager::stopFishingEvent().
void FishingManagerImplementation::success (CreatureObject * player, int fish, SceneObject * marker, unsigned int boxID)
success is called to give the Player his reward success uses the given fish to decide whether the player receives a misc item or a fish The values for chances (>93 for item, >94 on another roll for rare item) are based on a SWG Dev comment: "As for the drop rates of Fish Tank Items/Treasure maps/Junk Loot (not including collection fish) when fishing, each time you catch something, there is a 6% chance it will be one of the above mentioned items." -Millbarge - SWG Developer So there is a 6% chance of an item, and another 5% change for a rare item => 0.3% chance for a rare item Also, if you are unlucky (5% chance) the fish was too small and it is being tossed
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
player CreatureObject that receives the reward
marker Fishing Marker that is used as Container
boxID Fishing window being closed
Definition at line 378 of file FishingManagerImplementation.cpp.
References color, server::zone::ZoneServer::createObject(), fishLength, fishType, server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getLastName(), server::zone::ZoneServer::getPlayerManager(), getPole(), server::zone::ZoneServer::getResourceManager(), getTime(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::Zone::getZoneServer(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::hasSkill(), miscLoot, rareLoot, sendReward(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and stopFishing().
Referenced by checkFishingOnPositionUpdate(), fishingStep(), and server::zone::managers::minigames::FishingManager::success().
void FishingManagerImplementation::unlock (bool doLock = true) protected
Definition at line 826 of file FishingManager.cpp.
References _this.
SceneObject * FishingManagerImplementation::updateMarker (CreatureObject * player, SceneObject * marker, bool notifyPlayer)
Updates the fishing Marker updateMarker takes the player position and the marker position and halfes that distance creating a new marker at that position and returning the marker
Precondition
{ object is locked }
Postcondition
{ object is locked }
Parameters
player CreatureObject for which to update the fishing event's marker
marker Object sent to event as new marker
Returns
{ SceneObject of new Marker }
Definition at line 1035 of file FishingManagerImplementation.cpp.
References checkUpdateMarker(), createMarker(), getFishingState(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isInRange(), REELING, removeMarker(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), setFishMarker(), and stopFishing().
Referenced by fishingStep(), and server::zone::managers::minigames::FishingManager::updateMarker().
int FishingManagerImplementation::vegetation (SceneObject * marker)
Calculates vegetation based on current Position vegetation returns a value 0-5 based on abs(PositionX/100) rounded up { Actually make vegetation a property of a body of water }
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
marker Fishing marker to get coordinates of to calculate the vegetation
Returns
{ 0-5 }
Definition at line 590 of file FishingManagerImplementation.cpp.
Referenced by createWindow(), fishingStep(), getFish(), and server::zone::managers::minigames::FishingManager::vegetation().
void FishingManagerImplementation::wlock (bool doLock = true) protected
Definition at line 818 of file FishingManager.cpp.
References _this.
void FishingManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 822 of file FishingManager.cpp.
References _this.
void FishingManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 906 of file FishingManager.cpp.
References writeObjectMembers().
int FishingManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 913 of file FishingManager.cpp.
References action, baitStatus, color, fishLength, fishType, miscLoot, property, rareLoot, and state.
Referenced by writeObject().
Friends And Related Function Documentation
friend class FishingManager friend
Definition at line 1321 of file FishingManager.h.
Member Data Documentation
WeakReference<FishingManager*> server::zone::managers::minigames::FishingManagerImplementation::_this
Definition at line 1287 of file FishingManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), createMarker(), getBait(), lock(), rlock(), runlock(), startFishing(), stopFishing(), unlock(), and wlock().
Vector<String> server::zone::managers::minigames::FishingManagerImplementation::action protected
Definition at line 739 of file FishingManager.h.
Referenced by createWindow(), initializeAction(), readObjectMember(), and writeObjectMembers().
Vector<String> server::zone::managers::minigames::FishingManagerImplementation::baitStatus protected
Definition at line 743 of file FishingManager.h.
Referenced by createWindow(), initializeBaitStatus(), readObjectMember(), and writeObjectMembers().
const int server::zone::managers::minigames::FishingManagerImplementation::BITE = 4 static
Definition at line 754 of file FishingManager.h.
Referenced by fishingProceed(), and fishingStep().
const int server::zone::managers::minigames::FishingManagerImplementation::BLACKFISH = 0 static
Definition at line 762 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManagerImplementation::BLOWFISH = 1 static
Definition at line 764 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManagerImplementation::BLUEFISH = 2 static
Definition at line 766 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManagerImplementation::CATCH = 5 static
Definition at line 756 of file FishingManager.h.
Referenced by createFishingEvent(), fishingProceed(), and fishingStep().
VectorMap<String, int> server::zone::managers::minigames::FishingManagerImplementation::color protected
Definition at line 731 of file FishingManager.h.
Referenced by initializeColor(), readObjectMember(), success(), and writeObjectMembers().
const int server::zone::managers::minigames::FishingManagerImplementation::DONOTHING = 0 static
Definition at line 782 of file FishingManager.h.
Referenced by fishingProceed(), fishingStep(), getNextAction(), mishapEvent(), setNextAction(), and startFishing().
const int server::zone::managers::minigames::FishingManagerImplementation::FAA = 3 static
Definition at line 768 of file FishingManager.h.
Vector<int> server::zone::managers::minigames::FishingManagerImplementation::fishLength protected
Definition at line 733 of file FishingManager.h.
Referenced by initializeFishLength(), readObjectMember(), success(), and writeObjectMembers().
Vector<String> server::zone::managers::minigames::FishingManagerImplementation::fishType protected
Definition at line 735 of file FishingManager.h.
Referenced by initializeFishType(), readObjectMember(), success(), and writeObjectMembers().
const int server::zone::managers::minigames::FishingManagerImplementation::FRESH = 0 static
Definition at line 776 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManagerImplementation::LAA = 4 static
Definition at line 770 of file FishingManager.h.
Vector<String> server::zone::managers::minigames::FishingManagerImplementation::miscLoot protected
Definition at line 727 of file FishingManager.h.
Referenced by initializeLoot(), readObjectMember(), success(), and writeObjectMembers().
const int server::zone::managers::minigames::FishingManagerImplementation::MISHAP = 45 static
Definition at line 798 of file FishingManager.h.
Referenced by fishingStep().
const int server::zone::managers::minigames::FishingManagerImplementation::MUSH = 10 static
Definition at line 780 of file FishingManager.h.
Referenced by createWindow().
const int server::zone::managers::minigames::FishingManagerImplementation::NIBBLE = 3 static
Definition at line 752 of file FishingManager.h.
Referenced by fishingProceed(), and fishingStep().
const int server::zone::managers::minigames::FishingManagerImplementation::NOEVENT = 0 static
Definition at line 794 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManagerImplementation::NOTFISHING = 0 static
Definition at line 746 of file FishingManager.h.
Referenced by getFishingState(), server::zone::managers::minigames::events::FishingEvent::run(), setFishingState(), and stopFishing().
const int server::zone::managers::minigames::FishingManagerImplementation::PROCEED = 17 static
Definition at line 796 of file FishingManager.h.
Referenced by fishingStep().
Vector<String> server::zone::managers::minigames::FishingManagerImplementation::property protected
Definition at line 741 of file FishingManager.h.
Referenced by initializeProperty(), readObjectMember(), and writeObjectMembers().
Vector<String> server::zone::managers::minigames::FishingManagerImplementation::rareLoot protected
Definition at line 729 of file FishingManager.h.
Referenced by initializeLoot(), readObjectMember(), success(), and writeObjectMembers().
const int server::zone::managers::minigames::FishingManagerImplementation::RAY = 5 static
Definition at line 772 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManagerImplementation::REEL = 4 static
Definition at line 790 of file FishingManager.h.
Referenced by animate(), fishingProceed(), and fishingStep().
const int server::zone::managers::minigames::FishingManagerImplementation::REELGAME = 7 static
Definition at line 760 of file FishingManager.h.
Referenced by fishingProceed(), fishingStep(), getFishingState(), and setFishingState().
const int server::zone::managers::minigames::FishingManagerImplementation::REELING = 6 static
Definition at line 758 of file FishingManager.h.
Referenced by fishingProceed(), fishingStep(), and updateMarker().
const int server::zone::managers::minigames::FishingManagerImplementation::SNAGGED = 2 static
Definition at line 750 of file FishingManager.h.
Referenced by fishingProceed(), and fishingStep().
const int server::zone::managers::minigames::FishingManagerImplementation::SOGGY = 6 static
Definition at line 778 of file FishingManager.h.
Referenced by createWindow(), and fishingStep().
Vector<String> server::zone::managers::minigames::FishingManagerImplementation::state protected
Definition at line 737 of file FishingManager.h.
Referenced by createWindow(), fishingStep(), getFishingState(), initializeState(), readObjectMember(), and writeObjectMembers().
const int server::zone::managers::minigames::FishingManagerImplementation::STOPFISHING = 5 static
Definition at line 792 of file FishingManager.h.
Referenced by setNextAction().
const int server::zone::managers::minigames::FishingManagerImplementation::STRIPED = 6 static
Definition at line 774 of file FishingManager.h.
const int server::zone::managers::minigames::FishingManagerImplementation::TUGLEFT = 3 static
Definition at line 788 of file FishingManager.h.
Referenced by animate(), and fishingStep().
const int server::zone::managers::minigames::FishingManagerImplementation::TUGRIGHT = 2 static
Definition at line 786 of file FishingManager.h.
Referenced by animate().
const int server::zone::managers::minigames::FishingManagerImplementation::TUGUP = 1 static
Definition at line 784 of file FishingManager.h.
Referenced by animate(), and fishingStep().
const int server::zone::managers::minigames::FishingManagerImplementation::WAITING = 1 static
Definition at line 748 of file FishingManager.h.
Referenced by fishingStep(), mishapEvent(), and startFishing().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingManagerImplementation.cpp