Core3: FactionStandingList Class Reference
FactionStandingList Class Reference
#include <FactionStandingList.h>
Public Member Functions
FactionStandingList ()
FactionStandingList (const FactionStandingList &f)
FactionStandingList & operator= (const FactionStandingList &f)
void addSerializableVariables ()
float get (const String &faction)
int size ()
void put (const String &faction, float amount)
float getFactionStanding (const String &faction)
bool contains (const String &faction)
bool isPvpFaction (const String &faction)
String & getFactionRank ()
void setRebelPoints (int amount)
void setImperialPoints (int amount)
void increaseRebelPoints (int amount)
void decreaseRebelPoints (int amount)
void increaseImperialPoints (int amount)
void decreaseImperialPoints (int amount)
void setFactionRank (const String &rank)
int getImperialPoints ()
int getRebelPoints ()
int getHuttPoints ()
void insertToMessage (BaseMessage *message)
Private Attributes
String factionRank
int rebelPoints
int imperialPoints
VectorMap< String, float > factions
Detailed Description
Definition at line 13 of file FactionStandingList.h.
Constructor & Destructor Documentation
FactionStandingList::FactionStandingList () inline
Definition at line 21 of file FactionStandingList.h.
References addSerializableVariables(), factions, imperialPoints, and rebelPoints.
FactionStandingList::FactionStandingList (const FactionStandingList & f) inline
Definition at line 31 of file FactionStandingList.h.
References addSerializableVariables(), factionRank, factions, imperialPoints, and rebelPoints.
Member Function Documentation
void FactionStandingList::addSerializableVariables () inline
Definition at line 55 of file FactionStandingList.h.
References factionRank, factions, imperialPoints, and rebelPoints.
Referenced by FactionStandingList().
bool FactionStandingList::contains (const String & faction) inline
Definition at line 88 of file FactionStandingList.h.
References factions.
void FactionStandingList::decreaseImperialPoints (int amount) inline
Definition at line 123 of file FactionStandingList.h.
References imperialPoints.
void FactionStandingList::decreaseRebelPoints (int amount) inline
Definition at line 115 of file FactionStandingList.h.
References rebelPoints.
float FactionStandingList::get (const String & faction) inline
Definition at line 62 of file FactionStandingList.h.
References getFactionStanding().
Referenced by server::zone::objects::player::PlayerObjectImplementation::decreaseFactionStanding().
String& FactionStandingList::getFactionRank () inline
Definition at line 99 of file FactionStandingList.h.
References factionRank.
float FactionStandingList::getFactionStanding (const String & faction) inline
Definition at line 79 of file FactionStandingList.h.
References factions, getImperialPoints(), and getRebelPoints().
Referenced by get(), server::zone::objects::player::PlayerObjectImplementation::getFactionStanding(), and server::zone::objects::player::PlayerObjectImplementation::increaseFactionStanding().
int FactionStandingList::getHuttPoints () inline
Definition at line 139 of file FactionStandingList.h.
int FactionStandingList::getImperialPoints () inline
Definition at line 131 of file FactionStandingList.h.
References imperialPoints.
Referenced by getFactionStanding().
int FactionStandingList::getRebelPoints () inline
Definition at line 135 of file FactionStandingList.h.
References rebelPoints.
Referenced by getFactionStanding().
void FactionStandingList::increaseImperialPoints (int amount) inline
Definition at line 119 of file FactionStandingList.h.
References imperialPoints.
void FactionStandingList::increaseRebelPoints (int amount) inline
Definition at line 111 of file FactionStandingList.h.
References rebelPoints.
void FactionStandingList::insertToMessage (BaseMessage * message) inline
Definition at line 143 of file FactionStandingList.h.
References factionRank, factions, imperialPoints, and rebelPoints.
Referenced by FactionResponseMessage::FactionResponseMessage().
bool FactionStandingList::isPvpFaction (const String & faction) inline
Definition at line 95 of file FactionStandingList.h.
Referenced by server::zone::objects::player::PlayerObjectImplementation::increaseFactionStanding().
FactionStandingList& FactionStandingList::operator= (const FactionStandingList & f) inline
Definition at line 43 of file FactionStandingList.h.
References factionRank, factions, imperialPoints, and rebelPoints.
void FactionStandingList::put (const String & faction, float amount) inline
Definition at line 70 of file FactionStandingList.h.
References factions, setImperialPoints(), and setRebelPoints().
Referenced by server::zone::objects::player::PlayerObjectImplementation::decreaseFactionStanding(), and server::zone::objects::player::PlayerObjectImplementation::increaseFactionStanding().
void FactionStandingList::setFactionRank (const String & rank) inline
Definition at line 127 of file FactionStandingList.h.
References factionRank.
void FactionStandingList::setImperialPoints (int amount) inline
Definition at line 107 of file FactionStandingList.h.
References imperialPoints.
Referenced by put().
void FactionStandingList::setRebelPoints (int amount) inline
Definition at line 103 of file FactionStandingList.h.
References rebelPoints.
Referenced by put().
int FactionStandingList::size () inline
Definition at line 66 of file FactionStandingList.h.
References factions.
Member Data Documentation
String FactionStandingList::factionRank private
Definition at line 14 of file FactionStandingList.h.
Referenced by addSerializableVariables(), FactionStandingList(), getFactionRank(), insertToMessage(), operator=(), and setFactionRank().
VectorMap<String, float> FactionStandingList::factions private
Definition at line 17 of file FactionStandingList.h.
Referenced by addSerializableVariables(), contains(), FactionStandingList(), getFactionStanding(), insertToMessage(), operator=(), put(), and size().
int FactionStandingList::imperialPoints private
Definition at line 16 of file FactionStandingList.h.
Referenced by addSerializableVariables(), decreaseImperialPoints(), FactionStandingList(), getImperialPoints(), increaseImperialPoints(), insertToMessage(), operator=(), and setImperialPoints().
int FactionStandingList::rebelPoints private
Definition at line 15 of file FactionStandingList.h.
Referenced by addSerializableVariables(), decreaseRebelPoints(), FactionStandingList(), getRebelPoints(), increaseRebelPoints(), insertToMessage(), operator=(), and setRebelPoints().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/variables/FactionStandingList.h