Core3: TerrainGenerator Class Reference
TerrainGenerator Class Reference
#include <TerrainGenerator.h>
Public Member Functions
TerrainGenerator (ProceduralTerrainAppearance *ptat)
void processLayers ()
void processLayer (Layer *layer)
void parseFromIffStream (engine::util::IffStream *iffStream)
void parseFromIffStream (engine::util::IffStream *iffStream, Version<'0000'>)
void addLayer (Layer *layer)
void removeLayer (Layer *layer)
MapGroup * getMapGroup ()
LayersGroup * getLayersGroup ()
BitmapGroup * getBitmapGroup ()
MapFractal * getMfrc (int idx)
Public Member Functions inherited from TemplateVariable<'TGEN'>
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Private Attributes
ProceduralTerrainAppearance * terrain
ShadersGroup shaderGroup
RadialGroup radialGroup
FloraGroup floraGroup
EnvironmentGroup environmentGroup
MapGroup mapGroup
BitmapGroup bitmapGroup
LayersGroup layers
Detailed Description
Definition at line 23 of file TerrainGenerator.h.
Constructor & Destructor Documentation
TerrainGenerator::TerrainGenerator (ProceduralTerrainAppearance * ptat) inline
Definition at line 35 of file TerrainGenerator.h.
References terrain.
Member Function Documentation
void TerrainGenerator::addLayer (Layer * layer)
Definition at line 75 of file TerrainGenerator.cpp.
References LayersGroup::getLayers(), and layers.
BitmapGroup* TerrainGenerator::getBitmapGroup () inline
Definition at line 56 of file TerrainGenerator.h.
References bitmapGroup.
Referenced by FilterBitmap::process().
LayersGroup* TerrainGenerator::getLayersGroup () inline
Definition at line 52 of file TerrainGenerator.h.
References layers.
Referenced by ProceduralTerrainAppearance::addTerrainModification(), ProceduralTerrainAppearance::getEnvironmentID(), ProceduralTerrainAppearance::getHeight(), and ProceduralTerrainAppearance::getLayer().
MapGroup* TerrainGenerator::getMapGroup () inline
Definition at line 48 of file TerrainGenerator.h.
References mapGroup.
MapFractal* TerrainGenerator::getMfrc (int idx) inline
Definition at line 60 of file TerrainGenerator.h.
References MapGroup::getMfrc(), and mapGroup.
Referenced by AffectorHeightFractal::process(), and FilterFractal::process().
void TerrainGenerator::parseFromIffStream (engine::util::IffStream * iffStream) virtual
Reimplemented from TemplateVariable<'TGEN'>.
Definition at line 33 of file TerrainGenerator.cpp.
Referenced by ProceduralTerrainAppearance::addTerrainModification().
void TerrainGenerator::parseFromIffStream (engine::util::IffStream * iffStream, Version<'0000'>)
Definition at line 50 of file TerrainGenerator.cpp.
References bitmapGroup, environmentGroup, floraGroup, LayersGroup::getLayers(), layers, mapGroup, radialGroup, TemplateVariable< formType >::readObject(), and shaderGroup.
void TerrainGenerator::processLayer (Layer * layer)
Definition at line 20 of file TerrainGenerator.cpp.
References Layer::getBoundaries(), Layer::getChildren(), and terrain.
Referenced by processLayers().
void TerrainGenerator::processLayers ()
Definition at line 12 of file TerrainGenerator.cpp.
References LayersGroup::getLayers(), layers, and processLayer().
Referenced by ProceduralTerrainAppearance::load().
void TerrainGenerator::removeLayer (Layer * layer)
Definition at line 79 of file TerrainGenerator.cpp.
References LayersGroup::getLayers(), and layers.
Member Data Documentation
BitmapGroup TerrainGenerator::bitmapGroup private
Definition at line 31 of file TerrainGenerator.h.
Referenced by getBitmapGroup(), and parseFromIffStream().
EnvironmentGroup TerrainGenerator::environmentGroup private
Definition at line 29 of file TerrainGenerator.h.
Referenced by parseFromIffStream().
FloraGroup TerrainGenerator::floraGroup private
Definition at line 28 of file TerrainGenerator.h.
Referenced by parseFromIffStream().
LayersGroup TerrainGenerator::layers private
Definition at line 32 of file TerrainGenerator.h.
Referenced by addLayer(), getLayersGroup(), parseFromIffStream(), processLayers(), and removeLayer().
MapGroup TerrainGenerator::mapGroup private
Definition at line 30 of file TerrainGenerator.h.
Referenced by getMapGroup(), getMfrc(), and parseFromIffStream().
RadialGroup TerrainGenerator::radialGroup private
Definition at line 27 of file TerrainGenerator.h.
Referenced by parseFromIffStream().
ShadersGroup TerrainGenerator::shaderGroup private
Definition at line 26 of file TerrainGenerator.h.
Referenced by parseFromIffStream().
ProceduralTerrainAppearance* TerrainGenerator::terrain private
Definition at line 24 of file TerrainGenerator.h.
Referenced by processLayer(), and TerrainGenerator().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/TerrainGenerator.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/TerrainGenerator.cpp