Core3: WorldCoordinates Class Reference
WorldCoordinates Class Reference
#include <WorldCoordinates.h>
Public Member Functions
WorldCoordinates ()
WorldCoordinates (const WorldCoordinates &c)
WorldCoordinates (SceneObject *obj)
WorldCoordinates (const Vector3 &position, SceneObject *cell)
WorldCoordinates & operator= (const WorldCoordinates &c)
bool operator== (const WorldCoordinates &c)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
bool isInRange (const WorldCoordinates &obj, float range) const
Vector3 getWorldPosition () const
void setCell (SceneObject *obj)
void setCoordinates (const Vector3 &pos)
void setX (float x)
void setY (float y)
void setZ (float z)
Vector3 getPoint () const
SceneObject * getCell () const
float getX () const
float getY () const
float getZ () const
Protected Attributes
Vector3 point
ManagedReference< SceneObject * > cell
Detailed Description
Definition at line 25 of file WorldCoordinates.h.
Constructor & Destructor Documentation
WorldCoordinates::WorldCoordinates ()
Definition at line 11 of file WorldCoordinates.cpp.
WorldCoordinates::WorldCoordinates (const WorldCoordinates & c)
Definition at line 15 of file WorldCoordinates.cpp.
References cell, and point.
WorldCoordinates::WorldCoordinates (SceneObject * obj)
Definition at line 30 of file WorldCoordinates.cpp.
References cell, server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::isCellObject(), and point.
WorldCoordinates::WorldCoordinates (const Vector3 & position, SceneObject * cell)
Definition at line 39 of file WorldCoordinates.cpp.
References cell, server::zone::objects::scene::SceneObject::isCellObject(), and point.
Member Function Documentation
SceneObject* WorldCoordinates::getCell () const inline
Definition at line 74 of file WorldCoordinates.h.
Referenced by AiStateComponent::doMovement(), server::zone::objects::creature::AiAgentImplementation::doMovement(), FindObjectCommand::doQueueCommand(), DragIncapacitatedPlayerCommand::drag(), PathFinderManager::filterPastPoints(), AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), PathFinderManager::findPath(), PathFinderManager::findPathFromCellToCell(), PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), PathFinderManager::findPathFromWorldToCell(), and PatrolPoint::getCell().
Vector3 WorldCoordinates::getPoint () const inline
Definition at line 70 of file WorldCoordinates.h.
Referenced by AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), PathFinderManager::findPathFromCellToCell(), PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), and PathFinderManager::findPathFromWorldToCell().
Vector3 WorldCoordinates::getWorldPosition () const
Definition at line 61 of file WorldCoordinates.cpp.
References cell, and point.
Referenced by FindObjectCommand::doQueueCommand(), PathFinderManager::filterPastPoints(), AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), PatrolPoint::getWorldPosition(), and isInRange().
float WorldCoordinates::getX () const inline
Definition at line 78 of file WorldCoordinates.h.
Referenced by AiStateComponent::doMovement(), server::zone::objects::creature::AiAgentImplementation::doMovement(), DragIncapacitatedPlayerCommand::drag(), AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), PathFinderManager::findPath(), DragIncapacitatedPlayerCommand::getCoordinate(), PatrolPoint::getPositionX(), and WanderingStateComponent::onEnter().
float WorldCoordinates::getY () const inline
Definition at line 82 of file WorldCoordinates.h.
Referenced by AiStateComponent::doMovement(), server::zone::objects::creature::AiAgentImplementation::doMovement(), DragIncapacitatedPlayerCommand::drag(), AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), PathFinderManager::findPath(), DragIncapacitatedPlayerCommand::getCoordinate(), PatrolPoint::getPositionY(), and WanderingStateComponent::onEnter().
float WorldCoordinates::getZ () const inline
Definition at line 86 of file WorldCoordinates.h.
Referenced by AiStateComponent::doMovement(), server::zone::objects::creature::AiAgentImplementation::doMovement(), DragIncapacitatedPlayerCommand::drag(), AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), PathFinderManager::findPath(), PatrolPoint::getPositionZ(), and WanderingStateComponent::onEnter().
bool WorldCoordinates::isInRange (const WorldCoordinates & obj, float range) const
Definition at line 83 of file WorldCoordinates.cpp.
References getWorldPosition().
WorldCoordinates & WorldCoordinates::operator= (const WorldCoordinates & c)
Definition at line 20 of file WorldCoordinates.cpp.
References cell, and point.
bool WorldCoordinates::operator== (const WorldCoordinates & c) inline
Definition at line 39 of file WorldCoordinates.h.
References cell, and point.
bool WorldCoordinates::parseFromBinaryStream (ObjectInputStream * stream)
Definition at line 54 of file WorldCoordinates.cpp.
References cell, and point.
void WorldCoordinates::setCell (SceneObject * obj) inline
Definition at line 50 of file WorldCoordinates.h.
Referenced by AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), DragIncapacitatedPlayerCommand::getCoordinate(), and PatrolPoint::setCell().
void WorldCoordinates::setCoordinates (const Vector3 & pos) inline
Definition at line 54 of file WorldCoordinates.h.
Referenced by DragIncapacitatedPlayerCommand::getCoordinate(), and PatrolPoint::setPosition().
void WorldCoordinates::setX (float x) inline
Definition at line 58 of file WorldCoordinates.h.
Referenced by AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), DragIncapacitatedPlayerCommand::getCoordinate(), and PatrolPoint::setPositionX().
void WorldCoordinates::setY (float y) inline
Definition at line 62 of file WorldCoordinates.h.
Referenced by AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), DragIncapacitatedPlayerCommand::getCoordinate(), and PatrolPoint::setPositionY().
void WorldCoordinates::setZ (float z) inline
Definition at line 66 of file WorldCoordinates.h.
Referenced by AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), DragIncapacitatedPlayerCommand::getCoordinate(), and PatrolPoint::setPositionZ().
bool WorldCoordinates::toBinaryStream (ObjectOutputStream * stream)
Definition at line 47 of file WorldCoordinates.cpp.
References cell, and point.
Member Data Documentation
ManagedReference<SceneObject*> WorldCoordinates::cell protected
Definition at line 29 of file WorldCoordinates.h.
Referenced by getWorldPosition(), operator=(), operator==(), parseFromBinaryStream(), toBinaryStream(), and WorldCoordinates().
Vector3 WorldCoordinates::point protected
Definition at line 27 of file WorldCoordinates.h.
Referenced by getWorldPosition(), operator=(), operator==(), parseFromBinaryStream(), toBinaryStream(), and WorldCoordinates().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/WorldCoordinates.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/WorldCoordinates.cpp