Core3: LootGroupMap Class Reference
LootGroupMap Class Reference
#include <LootGroupMap.h>
Public Types
enum LUA_ERROR_CODE { NO_ERROR = 0, GENERAL_ERROR }
Public Member Functions
LootGroupMap ()
virtual ~LootGroupMap ()
int initialize ()
void putLootItemTemplate (const String &name, LootItemTemplate *item)
void putLootGroupTemplate (const String &name, LootGroupTemplate *group)
LootGroupTemplate * getLootGroupTemplate (const String &name)
LootItemTemplate * getLootItemTemplate (const String &name)
int countLootItemTemplates ()
int countLootGroupTemplates ()
Public Attributes
HashTable< String, Reference
< LootItemTemplate * > > itemTemplates
HashTable< String, Reference
< LootGroupTemplate * > > groupTemplates
Static Public Attributes
static Lua * lua = NULL
static int ERROR_CODE = NO_ERROR
Private Member Functions
void registerFunctions ()
void registerGlobals ()
Static Private Member Functions
static int includeFile (lua_State *L)
static int addLootGroupTemplate (lua_State *L)
static int addLootItemTemplate (lua_State *L)
Detailed Description
Definition at line 17 of file LootGroupMap.h.
Member Enumeration Documentation
enum LootGroupMap::LUA_ERROR_CODE
Enumerator
NO_ERROR
GENERAL_ERROR
Definition at line 20 of file LootGroupMap.h.
Constructor & Destructor Documentation
LootGroupMap::LootGroupMap ()
Definition at line 16 of file LootGroupMap.cpp.
References groupTemplates, itemTemplates, and lua.
LootGroupMap::~LootGroupMap () virtual
Definition at line 23 of file LootGroupMap.cpp.
References lua.
Member Function Documentation
int LootGroupMap::addLootGroupTemplate (lua_State * L) static private
Definition at line 67 of file LootGroupMap.cpp.
Referenced by registerFunctions().
int LootGroupMap::addLootItemTemplate (lua_State * L) static private
Definition at line 80 of file LootGroupMap.cpp.
Referenced by registerFunctions().
int LootGroupMap::countLootGroupTemplates () inline
Definition at line 52 of file LootGroupMap.h.
References groupTemplates.
int LootGroupMap::countLootItemTemplates () inline
Definition at line 48 of file LootGroupMap.h.
References itemTemplates.
LootGroupTemplate* LootGroupMap::getLootGroupTemplate (const String & name) inline
Definition at line 40 of file LootGroupMap.h.
References groupTemplates.
Referenced by TEST_F().
LootItemTemplate* LootGroupMap::getLootItemTemplate (const String & name) inline
Definition at line 44 of file LootGroupMap.h.
References itemTemplates.
Referenced by TEST_F().
int LootGroupMap::includeFile (lua_State * L) static private
Definition at line 56 of file LootGroupMap.cpp.
References ERROR_CODE, and GENERAL_ERROR.
Referenced by registerFunctions().
int LootGroupMap::initialize ()
Definition at line 28 of file LootGroupMap.cpp.
References ERROR_CODE, GENERAL_ERROR, lua, registerFunctions(), and registerGlobals().
Referenced by TEST_F().
void LootGroupMap::putLootGroupTemplate (const String & name, LootGroupTemplate * group) inline
Definition at line 36 of file LootGroupMap.h.
References groupTemplates.
void LootGroupMap::putLootItemTemplate (const String & name, LootItemTemplate * item) inline
Definition at line 32 of file LootGroupMap.h.
References itemTemplates.
void LootGroupMap::registerFunctions () private
Definition at line 47 of file LootGroupMap.cpp.
References addLootGroupTemplate(), addLootItemTemplate(), includeFile(), and lua.
Referenced by initialize().
void LootGroupMap::registerGlobals () private
Definition at line 53 of file LootGroupMap.cpp.
Referenced by initialize().
Member Data Documentation
int LootGroupMap::ERROR_CODE = NO_ERROR static
Definition at line 21 of file LootGroupMap.h.
Referenced by includeFile(), and initialize().
HashTable<String, Reference<LootGroupTemplate*> > LootGroupMap::groupTemplates
Definition at line 24 of file LootGroupMap.h.
Referenced by countLootGroupTemplates(), getLootGroupTemplate(), LootGroupMap(), putLootGroupTemplate(), and TEST_F().
HashTable<String, Reference<LootItemTemplate*> > LootGroupMap::itemTemplates
Definition at line 23 of file LootGroupMap.h.
Referenced by countLootItemTemplates(), getLootItemTemplate(), LootGroupMap(), and putLootItemTemplate().
Lua * LootGroupMap::lua = NULL static
Definition at line 19 of file LootGroupMap.h.
Referenced by initialize(), LootGroupMap(), registerFunctions(), and ~LootGroupMap().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/LootGroupMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/LootGroupMap.cpp