Core3: server::zone::objects::creature::buffs::DelayedBuffImplementation Class Reference
server::zone::objects::creature::buffs::DelayedBuffImplementation Class Reference
#include <DelayedBuff.h>
Public Member Functions
DelayedBuffImplementation (CreatureObject *creo, unsigned int buffcrc, int effectCount)
DelayedBuffImplementation (DummyConstructorParameter *param)
void init (Vector< int > *events)
void activate ()
void deactivate ()
void useCharge ()
void setUsesRemaining (int uses)
operator const DelayedBuff * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
BuffImplementation (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype)
BuffImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
virtual void sendTo (CreatureObject *player)
virtual void sendDestroyTo (CreatureObject *player)
virtual void activate (bool applyModifiers)
virtual void deactivate (bool removeModifiers)
VectorMap< String, int > * getSkillModifiers ()
virtual void applyAttributeModifiers ()
virtual void applySkillModifiers ()
virtual void applyStates ()
virtual void removeAttributeModifiers ()
virtual void removeSkillModifiers ()
virtual void removeStates ()
virtual void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
virtual void parseAttributeModifierString (const String &modifierstring)
virtual void parseSkillModifierString (const String &modifierstring)
virtual String getAttributeModifierString ()
virtual String getSkillModifierString ()
virtual float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
VectorMap< byte, int > * getAttributeModifiers ()
virtual int getAttributeModifierValue (byte attribute)
virtual int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartMessage (StringIdChatParameter &start)
void setEndMessage (StringIdChatParameter &end)
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
operator const Buff * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< DelayedBuff * > _this
Public Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
WeakReference< Buff * > _this
Protected Member Functions
virtual ~DelayedBuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
virtual ~BuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
int usesRemaining
ManagedReference
< CreatureObject * > player
ManagedReference
< DelayedBuffObserver * > observer
Vector< int > eventTypes
Protected Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
ManagedWeakReference
< CreatureObject * > creature
Reference< BuffDurationEvent * > buffEvent
VectorMap< byte, int > attributeModifiers
VectorMap< String, int > skillModifiers
Vector< unsigned long long > states
String buffName
float buffDuration
unsigned int buffCRC
int buffType
bool fillAttributesOnBuff
StringIdChatParameter startMessage
StringIdChatParameter endMessage
String startFlyFile
String startFlyAux
byte startFlyRed
byte startFlyGreen
byte startFlyBlue
String endFlyFile
String endFlyAux
byte endFlyRed
byte endFlyGreen
byte endFlyBlue
Time nextExecutionTime
Private Member Functions
void addObservers ()
void dropObservers ()
Friends
class DelayedBuff
Detailed Description
Definition at line 139 of file DelayedBuff.h.
Constructor & Destructor Documentation
DelayedBuffImplementation::DelayedBuffImplementation (CreatureObject * creo, unsigned int buffcrc, int effectCount)
Definition at line 279 of file DelayedBuff.cpp.
References _initializeImplementation(), player, and usesRemaining.
DelayedBuffImplementation::DelayedBuffImplementation (DummyConstructorParameter * param)
Definition at line 117 of file DelayedBuff.cpp.
References _initializeImplementation().
DelayedBuffImplementation::~DelayedBuffImplementation () protected virtual
Definition at line 122 of file DelayedBuff.cpp.
Member Function Documentation
DistributedObjectStub * DelayedBuffImplementation::_getStub ()
Definition at line 142 of file DelayedBuff.cpp.
References _this.
void DelayedBuffImplementation::_initializeImplementation () protected
Definition at line 129 of file DelayedBuff.cpp.
References _serializationHelperMethod(), and _this.
Referenced by DelayedBuffImplementation().
void DelayedBuffImplementation::_serializationHelperMethod () protected
Definition at line 178 of file DelayedBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void DelayedBuffImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 137 of file DelayedBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::buffs::DelayedBuff::DelayedBuff().
void DelayedBuffImplementation::activate () virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 303 of file DelayedBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::activate(), and addObservers().
Referenced by server::zone::objects::creature::buffs::DelayedBuff::activate().
void DelayedBuffImplementation::addObservers () private
Definition at line 341 of file DelayedBuff.cpp.
References eventTypes, observer, and player.
Referenced by activate().
void DelayedBuffImplementation::deactivate () virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 310 of file DelayedBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::deactivate(), and dropObservers().
Referenced by server::zone::objects::creature::buffs::DelayedBuff::deactivate().
void DelayedBuffImplementation::dropObservers () private
Definition at line 352 of file DelayedBuff.cpp.
References eventTypes, observer, and player.
Referenced by deactivate().
void DelayedBuffImplementation::finalize () protected
Definition at line 126 of file DelayedBuff.cpp.
void DelayedBuffImplementation::init (Vector< int > * events)
Definition at line 287 of file DelayedBuff.cpp.
References _this, eventTypes, and observer.
Referenced by server::zone::objects::creature::buffs::DelayedBuff::init().
void DelayedBuffImplementation::lock (bool doLock = true) protected
Definition at line 150 of file DelayedBuff.cpp.
References _this.
void DelayedBuffImplementation::lock (ManagedObject * obj) protected
Definition at line 154 of file DelayedBuff.cpp.
References _this.
DelayedBuffImplementation::operator const DelayedBuff * ()
Definition at line 146 of file DelayedBuff.cpp.
void DelayedBuffImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 185 of file DelayedBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::initializeTransientMembers(), and readObjectMember().
bool DelayedBuffImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 204 of file DelayedBuff.cpp.
References eventTypes, observer, player, server::zone::objects::creature::buffs::BuffImplementation::readObjectMember(), and usesRemaining.
Referenced by readObject().
void DelayedBuffImplementation::rlock (bool doLock = true) protected
Definition at line 158 of file DelayedBuff.cpp.
References _this.
void DelayedBuffImplementation::runlock (bool doLock = true) protected
Definition at line 174 of file DelayedBuff.cpp.
References _this.
void DelayedBuffImplementation::setUsesRemaining (int uses)
Definition at line 329 of file DelayedBuff.cpp.
References _this, player, and usesRemaining.
Referenced by server::zone::objects::creature::buffs::DelayedBuff::setUsesRemaining().
void DelayedBuffImplementation::unlock (bool doLock = true) protected
Definition at line 170 of file DelayedBuff.cpp.
References _this.
void DelayedBuffImplementation::useCharge ()
Definition at line 317 of file DelayedBuff.cpp.
References _this, player, and usesRemaining.
Referenced by server::zone::objects::creature::buffs::DelayedBuff::useCharge().
void DelayedBuffImplementation::wlock (bool doLock = true) protected
Definition at line 162 of file DelayedBuff.cpp.
References _this.
void DelayedBuffImplementation::wlock (ManagedObject * obj) protected
Definition at line 166 of file DelayedBuff.cpp.
References _this.
void DelayedBuffImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 230 of file DelayedBuff.cpp.
References writeObjectMembers().
int DelayedBuffImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 237 of file DelayedBuff.cpp.
References eventTypes, observer, player, usesRemaining, and server::zone::objects::creature::buffs::BuffImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class DelayedBuff friend
Definition at line 204 of file DelayedBuff.h.
Member Data Documentation
WeakReference<DelayedBuff*> server::zone::objects::creature::buffs::DelayedBuffImplementation::_this
Definition at line 170 of file DelayedBuff.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), init(), lock(), rlock(), runlock(), setUsesRemaining(), unlock(), useCharge(), and wlock().
Vector<int> server::zone::objects::creature::buffs::DelayedBuffImplementation::eventTypes protected
Definition at line 147 of file DelayedBuff.h.
Referenced by addObservers(), dropObservers(), init(), readObjectMember(), and writeObjectMembers().
ManagedReference<DelayedBuffObserver* > server::zone::objects::creature::buffs::DelayedBuffImplementation::observer protected
Definition at line 145 of file DelayedBuff.h.
Referenced by addObservers(), dropObservers(), init(), readObjectMember(), and writeObjectMembers().
ManagedReference<CreatureObject* > server::zone::objects::creature::buffs::DelayedBuffImplementation::player protected
Definition at line 143 of file DelayedBuff.h.
Referenced by addObservers(), DelayedBuffImplementation(), dropObservers(), readObjectMember(), setUsesRemaining(), useCharge(), and writeObjectMembers().
int server::zone::objects::creature::buffs::DelayedBuffImplementation::usesRemaining protected
Definition at line 141 of file DelayedBuff.h.
Referenced by DelayedBuffImplementation(), readObjectMember(), setUsesRemaining(), useCharge(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/DelayedBuff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/DelayedBuff.cpp