Core3: server::zone::objects::area::areashapes::RectangularAreaShape Class Reference
server::zone::objects::area::areashapes::RectangularAreaShape Class Reference
#include <RectangularAreaShape.h>
Public Member Functions
RectangularAreaShape ()
void setDimensions (float h, float w)
float getHeight ()
float getWidth ()
bool containsPoint (float x, float y)
bool containsPoint (const Vector3 &point)
Vector3 getRandomPosition ()
Vector3 getRandomPosition (const Vector3 &origin, float minDistance, float maxDistance)
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::area::areashapes::AreaShape
AreaShape ()
void setAreaCenter (float x, float y)
Vector3 getAreaCenter ()
bool containsPoint (float x, float y)
float getRadius ()
Vector3 getRandomPosition ()
Vector3 getRandomPosition (const Vector3 &origin, float minDistance, float maxDistance)
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
RectangularAreaShape (DummyConstructorParameter *param)
virtual ~RectangularAreaShape ()
Protected Member Functions inherited from server::zone::objects::area::areashapes::AreaShape
AreaShape (DummyConstructorParameter *param)
virtual ~AreaShape ()
Friends
class RectangularAreaShapeHelper
Detailed Description
Definition at line 38 of file RectangularAreaShape.h.
Constructor & Destructor Documentation
RectangularAreaShape::RectangularAreaShape ()
Constructor
Definition at line 15 of file RectangularAreaShape.cpp.
References server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::_setStub().
RectangularAreaShape::RectangularAreaShape (DummyConstructorParameter * param) protected
Definition at line 22 of file RectangularAreaShape.cpp.
RectangularAreaShape::~RectangularAreaShape () protected virtual
Definition at line 26 of file RectangularAreaShape.cpp.
Member Function Documentation
DistributedObjectServant * RectangularAreaShape::_getImplementation ()
Definition at line 180 of file RectangularAreaShape.cpp.
Referenced by containsPoint(), getArea(), getHeight(), getRandomPosition(), getWidth(), intersectsWith(), isCircularAreaShape(), isRectangularAreaShape(), isRingAreaShape(), and setDimensions().
DistributedObjectServant * RectangularAreaShape::_getImplementationForRead ()
Definition at line 186 of file RectangularAreaShape.cpp.
void RectangularAreaShape::_setImplementation (DistributedObjectServant * servant)
Definition at line 190 of file RectangularAreaShape.cpp.
bool RectangularAreaShape::containsPoint (float x, float y)
Check if the coordinate is within the area shape.
Parameters
x the x coordinate.
y the y coordinate.
Returns
true if the coordinate is within the area shape.
Definition at line 72 of file RectangularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::containsPoint(), and RPC_CONTAINSPOINT__FLOAT_FLOAT_.
bool RectangularAreaShape::containsPoint (const Vector3 & point) virtual
Check if the coordinate is within the area shape.
Parameters
point the point to check if it is within the area shape.
Returns
true if the coordinate is within the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShape.
Definition at line 87 of file RectangularAreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::containsPoint().
float RectangularAreaShape::getArea ()
Get the area of the areaShape.
Returns
the area of the area shape.
Definition at line 167 of file RectangularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::getArea(), and RPC_GETAREA__.
float RectangularAreaShape::getHeight ()
Get the height of the rectangle.
Returns
height of the rectangle.
Definition at line 46 of file RectangularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::getHeight(), and RPC_GETHEIGHT__.
Vector3 RectangularAreaShape::getRandomPosition ()
Generate a random position within the area.
Returns
a random position within the area.
Definition at line 96 of file RectangularAreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::getRandomPosition().
Vector3 RectangularAreaShape::getRandomPosition (const Vector3 & origin, float minDistance, float maxDistance)
Generate a random position within the area with the supplied origin and radius as limits.
Parameters
origin the origin coordinate to generate the random position from.
minDistance the minimum distance from the origin.
maxDistance the maximum distance from the origin.
Returns
a random position within the area.
Definition at line 105 of file RectangularAreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::getRandomPosition().
float RectangularAreaShape::getWidth ()
Get the width of the rectangle.
Returns
width of the rectangle.
Definition at line 59 of file RectangularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::getWidth(), and RPC_GETWIDTH__.
bool RectangularAreaShape::intersectsWith (AreaShape * areaShape)
Check if this area shape intersects with the supplied area shape.
Parameters
areaShape the area shape to check for intersections with.s
Returns
true if the area shapes intersects each other.
Definition at line 153 of file RectangularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::intersectsWith(), and RPC_INTERSECTSWITH__AREASHAPE_.
bool RectangularAreaShape::isCircularAreaShape ()
Check if this is a circular area shape.
Returns
true if it is a circular area shape.
Definition at line 114 of file RectangularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::isCircularAreaShape(), and RPC_ISCIRCULARAREASHAPE__.
bool RectangularAreaShape::isRectangularAreaShape ()
Check if this is a rectangular area shape.
Returns
true if it is a rectangular area shape.
Definition at line 127 of file RectangularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::isRectangularAreaShape(), and RPC_ISRECTANGULARAREASHAPE__.
bool RectangularAreaShape::isRingAreaShape ()
Check if this is a ring area shape.
Returns
true if it is a ring area shape.
Definition at line 140 of file RectangularAreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::isRingAreaShape(), and RPC_ISRINGAREASHAPE__.
void RectangularAreaShape::setDimensions (float h, float w)
Set the dimensions of the rectangle.
Parameters
h the height of the rectangle.
w the width of the rectangle.
Definition at line 31 of file RectangularAreaShape.cpp.
References _getImplementation(), RPC_SETDIMENSIONS__FLOAT_FLOAT_, and server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::setDimensions().
Friends And Related Function Documentation
friend class RectangularAreaShapeHelper friend
Definition at line 133 of file RectangularAreaShape.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RectangularAreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RectangularAreaShape.cpp