Core3: server::zone::objects::mission::SurveyMissionObjective Class Reference
server::zone::objects::mission::SurveyMissionObjective Class Reference
#include <SurveyMissionObjective.h>
Public Member Functions
SurveyMissionObjective (MissionObject *mission)
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void setSpawnFamily (String &spf)
void setEfficiency (unsigned int eff)
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (MissionObject *parent)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
SurveyMissionObjective (DummyConstructorParameter *param)
virtual ~SurveyMissionObjective ()
Protected Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (DummyConstructorParameter *param)
virtual ~MissionObjective ()
Friends
class SurveyMissionObjectiveHelper
Detailed Description
Definition at line 85 of file SurveyMissionObjective.h.
Constructor & Destructor Documentation
SurveyMissionObjective::SurveyMissionObjective (MissionObject * mission)
Definition at line 21 of file SurveyMissionObjective.cpp.
References server::zone::objects::mission::SurveyMissionObjectiveImplementation::_setStub().
SurveyMissionObjective::SurveyMissionObjective (DummyConstructorParameter * param) protected
Definition at line 28 of file SurveyMissionObjective.cpp.
SurveyMissionObjective::~SurveyMissionObjective () protected virtual
Definition at line 32 of file SurveyMissionObjective.cpp.
Member Function Documentation
DistributedObjectServant * SurveyMissionObjective::_getImplementation ()
Definition at line 144 of file SurveyMissionObjective.cpp.
Referenced by abort(), activate(), complete(), getEndPosition(), initializeTransientMembers(), notifyObserverEvent(), setEfficiency(), and setSpawnFamily().
DistributedObjectServant * SurveyMissionObjective::_getImplementationForRead ()
Definition at line 150 of file SurveyMissionObjective.cpp.
void SurveyMissionObjective::_setImplementation (DistributedObjectServant * servant)
Definition at line 154 of file SurveyMissionObjective.cpp.
void SurveyMissionObjective::abort ()
Definition at line 63 of file SurveyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::abort(), and RPC_ABORT__.
void SurveyMissionObjective::activate ()
Definition at line 50 of file SurveyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::activate(), and RPC_ACTIVATE__.
void SurveyMissionObjective::complete ()
Definition at line 76 of file SurveyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::complete(), and RPC_COMPLETE__.
Vector3 SurveyMissionObjective::getEndPosition ()
Definition at line 135 of file SurveyMissionObjective.cpp.
References _getImplementation(), and server::zone::objects::mission::SurveyMissionObjectiveImplementation::getEndPosition().
void SurveyMissionObjective::initializeTransientMembers ()
Definition at line 37 of file SurveyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
int SurveyMissionObjective::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 89 of file SurveyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
void SurveyMissionObjective::setEfficiency (unsigned int eff)
Definition at line 121 of file SurveyMissionObjective.cpp.
References _getImplementation(), RPC_SETEFFICIENCY__INT_, and server::zone::objects::mission::SurveyMissionObjectiveImplementation::setEfficiency().
void SurveyMissionObjective::setSpawnFamily (String & spf)
Definition at line 107 of file SurveyMissionObjective.cpp.
References _getImplementation(), RPC_SETSPAWNFAMILY__STRING_, and server::zone::objects::mission::SurveyMissionObjectiveImplementation::setSpawnFamily().
Friends And Related Function Documentation
friend class SurveyMissionObjectiveHelper friend
Definition at line 115 of file SurveyMissionObjective.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/SurveyMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/SurveyMissionObjective.cpp