Core3: PlaceDecorationComponent Class Reference
PlaceDecorationComponent Class Reference
#include <PlaceDecorationComponent.h>
Public Member Functions
int placeStructure (StructureDeed *deed, CreatureObject *creature, float x, float y, int angle)
Public Member Functions inherited from PlaceStructureComponent
virtual int notifyStructurePlaced (StructureDeed *deed, CreatureObject *creature, StructureObject *structure)
Detailed Description
Definition at line 13 of file PlaceDecorationComponent.h.
Member Function Documentation
int PlaceDecorationComponent::placeStructure (StructureDeed * deed, CreatureObject * creature, float x, float y, int angle) virtual
Reimplemented from PlaceStructureComponent.
Definition at line 17 of file PlaceDecorationComponent.cpp.
References server::zone::managers::city::CityManager::canSupportMoreDecorations(), server::zone::ZoneServer::getCityManager(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getZoneServer(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/deed/components/PlaceDecorationComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/deed/components/PlaceDecorationComponent.cpp