Core3: SpawnStateComponent Class Reference
SpawnStateComponent Class Reference
#include <SpawnStateComponent.h>
Public Member Functions
uint16 onEnter (AiActor *actor)
uint16 doRecovery (AiActor *actor)
uint16 doMovement (AiActor *actor)
Public Member Functions inherited from AiStateComponent
virtual void notifyPositionUpdate (Observable *obs, QuadTreeEntry *entry)
void notifyDespawn (AiActor *actor, Zone *zone)
virtual void doAwarenessCheck (Observable *obs, Coordinate &start, uint64 time, CreatureObject *target)
virtual void onExit (AiActor *actor)
virtual uint16 tryRetreat (AiActor *actor)
virtual uint16 doAttack (AiActor *actor)
bool findNextPosition (Observable *obs, float maxDistance, float speed, PatrolPointsVector *patrolPoints, WorldCoordinates *nextPosition)
virtual float getMaxDistance (CreatureObject *host)
virtual float getSpeed (CreatureObject *host)
void setNextPosition (AiActor *actor, float x, float z, float y, SceneObject *cell=NULL)
void updateCurrentPosition (CreatureObject *host, PatrolPoint *pos)
void broadcastNextPositionUpdate (CreatureObject *host, PatrolPoint *point)
void checkNewAngle (AiActor *actor)
void sendConversationStartTo (CreatureObject *host, SceneObject *player)
void selectWeapon (AiActor *actor)
bool validateStateAttack (CreatureObject *target, String &args)
virtual bool isScared (CreatureObject *host, SceneObject *followObject)
Detailed Description
Definition at line 17 of file SpawnStateComponent.h.
Member Function Documentation
uint16 SpawnStateComponent::doMovement (AiActor * actor) inline virtual
Reimplemented from AiStateComponent.
Definition at line 60 of file SpawnStateComponent.h.
References onEnter().
uint16 SpawnStateComponent::doRecovery (AiActor * actor) inline virtual
Reimplemented from AiStateComponent.
Definition at line 56 of file SpawnStateComponent.h.
References onEnter().
uint16 SpawnStateComponent::onEnter (AiActor * actor) inline virtual
Reimplemented from AiStateComponent.
Definition at line 19 of file SpawnStateComponent.h.
References server::zone::objects::creature::ai::AiActor::activateRecovery(), server::zone::managers::creature::CreatureManager::createCreature(), PatrolPoint::getCell(), server::zone::Zone::getCreatureManager(), server::zone::objects::creature::ai::AiActor::getHomeLocation(), server::zone::objects::creature::ai::AiActor::getHost(), server::zone::objects::creature::ai::AiActor::getNpcTemplate(), server::zone::objects::scene::SceneObject::getObjectID(), PatrolPoint::getPositionX(), PatrolPoint::getPositionY(), PatrolPoint::getPositionZ(), server::zone::templates::mobile::CreatureTemplate::getTemplateName(), server::zone::managers::creature::CreatureManager::getTemplateToSpawn(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::ai::AiActor::loadTemplateData(), server::zone::managers::creature::CreatureManager::placeCreature(), and server::zone::objects::creature::ai::AiActor::setHost().
Referenced by doMovement(), and doRecovery().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/components/SpawnStateComponent.h