Core3: server::zone::managers::director::PersistentEventImplementation Class Reference
server::zone::managers::director::PersistentEventImplementation Class Reference
#include <PersistentEvent.h>
Public Member Functions
PersistentEventImplementation ()
PersistentEventImplementation (DummyConstructorParameter *param)
int getTimeStamp ()
const String getKey ()
const String getScreenplay ()
SceneObject * getObject ()
int getCurTime ()
void setCurTime (int time)
void setTimeStamp (int stamp)
void setKey (const String &k)
void setScreenplay (const String &sp)
void setObject (SceneObject *o)
void notifyLoadFromDatabase ()
operator const PersistentEvent * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< PersistentEvent * > _this
Protected Member Functions
virtual ~PersistentEventImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
int timeStamp
int curTime
String key
String play
ManagedReference< SceneObject * > obj
Friends
class PersistentEvent
Detailed Description
Definition at line 78 of file PersistentEvent.h.
Constructor & Destructor Documentation
PersistentEventImplementation::PersistentEventImplementation ()
Definition at line 373 of file PersistentEvent.cpp.
References _initializeImplementation(), and play.
PersistentEventImplementation::PersistentEventImplementation (DummyConstructorParameter * param)
Definition at line 199 of file PersistentEvent.cpp.
References _initializeImplementation().
PersistentEventImplementation::~PersistentEventImplementation () protected virtual
Definition at line 204 of file PersistentEvent.cpp.
Member Function Documentation
DistributedObjectStub * PersistentEventImplementation::_getStub ()
Definition at line 224 of file PersistentEvent.cpp.
References _this.
void PersistentEventImplementation::_initializeImplementation () protected
Definition at line 211 of file PersistentEvent.cpp.
References _serializationHelperMethod(), and _this.
Referenced by PersistentEventImplementation().
void PersistentEventImplementation::_serializationHelperMethod () protected
Definition at line 260 of file PersistentEvent.cpp.
Referenced by _initializeImplementation().
void PersistentEventImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 219 of file PersistentEvent.cpp.
References _this.
Referenced by server::zone::managers::director::PersistentEvent::PersistentEvent().
void PersistentEventImplementation::finalize () protected
Definition at line 208 of file PersistentEvent.cpp.
int PersistentEventImplementation::getCurTime ()
Definition at line 399 of file PersistentEvent.cpp.
References curTime.
Referenced by server::zone::managers::director::PersistentEvent::getCurTime().
const String PersistentEventImplementation::getKey ()
Definition at line 384 of file PersistentEvent.cpp.
References key.
Referenced by server::zone::managers::director::PersistentEvent::getKey().
SceneObject * PersistentEventImplementation::getObject ()
Definition at line 394 of file PersistentEvent.cpp.
References obj.
Referenced by server::zone::managers::director::PersistentEvent::getObject().
const String PersistentEventImplementation::getScreenplay ()
Definition at line 389 of file PersistentEvent.cpp.
References play.
Referenced by server::zone::managers::director::PersistentEvent::getScreenplay().
int PersistentEventImplementation::getTimeStamp ()
Definition at line 379 of file PersistentEvent.cpp.
References timeStamp.
Referenced by server::zone::managers::director::PersistentEvent::getTimeStamp().
void PersistentEventImplementation::lock (bool doLock = true) protected
Definition at line 232 of file PersistentEvent.cpp.
References _this.
void PersistentEventImplementation::lock (ManagedObject * obj) protected
Definition at line 236 of file PersistentEvent.cpp.
References _this.
void PersistentEventImplementation::notifyLoadFromDatabase ()
Definition at line 49 of file PersistentEventImplementation.cpp.
References curTime, key, obj, play, and timeStamp.
Referenced by server::zone::managers::director::PersistentEvent::notifyLoadFromDatabase().
PersistentEventImplementation::operator const PersistentEvent * ()
Definition at line 228 of file PersistentEvent.cpp.
void PersistentEventImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 267 of file PersistentEvent.cpp.
References readObjectMember().
bool PersistentEventImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 286 of file PersistentEvent.cpp.
References curTime, key, obj, play, and timeStamp.
Referenced by readObject().
void PersistentEventImplementation::rlock (bool doLock = true) protected
Definition at line 240 of file PersistentEvent.cpp.
References _this.
void PersistentEventImplementation::runlock (bool doLock = true) protected
Definition at line 256 of file PersistentEvent.cpp.
References _this.
void PersistentEventImplementation::setCurTime (int time)
Definition at line 404 of file PersistentEvent.cpp.
References curTime.
Referenced by server::zone::managers::director::PersistentEvent::setCurTime().
void PersistentEventImplementation::setKey (const String & k)
Definition at line 414 of file PersistentEvent.cpp.
References key.
Referenced by server::zone::managers::director::PersistentEvent::setKey().
void PersistentEventImplementation::setObject (SceneObject * o)
Definition at line 424 of file PersistentEvent.cpp.
References obj.
Referenced by server::zone::managers::director::PersistentEvent::setObject().
void PersistentEventImplementation::setScreenplay (const String & sp)
Definition at line 419 of file PersistentEvent.cpp.
References play.
Referenced by server::zone::managers::director::PersistentEvent::setScreenplay().
void PersistentEventImplementation::setTimeStamp (int stamp)
Definition at line 409 of file PersistentEvent.cpp.
References timeStamp.
Referenced by server::zone::managers::director::PersistentEvent::setTimeStamp().
void PersistentEventImplementation::unlock (bool doLock = true) protected
Definition at line 252 of file PersistentEvent.cpp.
References _this.
void PersistentEventImplementation::wlock (bool doLock = true) protected
Definition at line 244 of file PersistentEvent.cpp.
References _this.
void PersistentEventImplementation::wlock (ManagedObject * obj) protected
Definition at line 248 of file PersistentEvent.cpp.
References _this.
void PersistentEventImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 316 of file PersistentEvent.cpp.
References writeObjectMembers().
int PersistentEventImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 323 of file PersistentEvent.cpp.
References curTime, key, obj, play, and timeStamp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class PersistentEvent friend
Definition at line 151 of file PersistentEvent.h.
Member Data Documentation
WeakReference<PersistentEvent*> server::zone::managers::director::PersistentEventImplementation::_this
Definition at line 117 of file PersistentEvent.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
int server::zone::managers::director::PersistentEventImplementation::curTime protected
Definition at line 82 of file PersistentEvent.h.
Referenced by getCurTime(), notifyLoadFromDatabase(), readObjectMember(), setCurTime(), and writeObjectMembers().
String server::zone::managers::director::PersistentEventImplementation::key protected
Definition at line 84 of file PersistentEvent.h.
Referenced by getKey(), notifyLoadFromDatabase(), readObjectMember(), setKey(), and writeObjectMembers().
ManagedReference<SceneObject* > server::zone::managers::director::PersistentEventImplementation::obj protected
Definition at line 88 of file PersistentEvent.h.
Referenced by getObject(), notifyLoadFromDatabase(), readObjectMember(), setObject(), and writeObjectMembers().
String server::zone::managers::director::PersistentEventImplementation::play protected
Definition at line 86 of file PersistentEvent.h.
Referenced by getScreenplay(), notifyLoadFromDatabase(), PersistentEventImplementation(), readObjectMember(), setScreenplay(), and writeObjectMembers().
int server::zone::managers::director::PersistentEventImplementation::timeStamp protected
Definition at line 80 of file PersistentEvent.h.
Referenced by getTimeStamp(), notifyLoadFromDatabase(), readObjectMember(), setTimeStamp(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/PersistentEvent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/PersistentEvent.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/PersistentEventImplementation.cpp