Core3: server::zone::managers::gcw::GCWManagerImplementation Class Reference
server::zone::managers::gcw::GCWManagerImplementation Class Reference
#include <GCWManager.h>
Public Member Functions
GCWManagerImplementation (Zone *zne)
GCWManagerImplementation (DummyConstructorParameter *param)
void loadLuaConfig ()
void initialize ()
void start ()
void registerGCWBase (BuildingObject *building, bool initializeBase)
void unregisterGCWBase (BuildingObject *building)
void performGCWTasks ()
void startVulnerability (BuildingObject *building)
void endVulnerability (BuildingObject *building)
bool isBaseVulnerable (BuildingObject *building)
bool isBandIdentified (BuildingObject *building)
bool isUplinkJammed (BuildingObject *building)
bool isShutdownSequenceStarted (BuildingObject *building)
bool isSecurityTermSliced (BuildingObject *building)
bool isPowerOverloaded (BuildingObject *building)
void resetVulnerability (CreatureObject *creature, BuildingObject *building)
void sendBaseDefenseStatus (CreatureObject *creature, BuildingObject *building)
void doBaseDestruction (StructureObject *structure)
void doBaseDestruction (BuildingObject *building)
void sendResetVerification (CreatureObject *creature, BuildingObject *building)
void sendJamUplinkMenu (CreatureObject *creature, BuildingObject *building, TangibleObject *uplinkTerminal)
void verifyUplinkBand (CreatureObject *creature, BuildingObject *building, int band)
bool canStartSlice (CreatureObject *creature, TangibleObject *terminal)
void sendDNASampleMenu (CreatureObject *creature, BuildingObject *building, TangibleObject *overrideTerminal)
void completeSecuritySlice (CreatureObject *creature, TangibleObject *securityTerminal)
void failSecuritySlice (TangibleObject *securityTerminal)
bool isTerminalDamaged (TangibleObject *securityTerminal)
bool isDNASampled (BuildingObject *building)
void repairTerminal (CreatureObject *creature, TangibleObject *securityTerminal)
void abortShutdownSequence (BuildingObject *building, CreatureObject *creature)
void processDNASample (CreatureObject *creature, TangibleObject *overrideTerminal, const String &sampleChain, int indx)
void handlePowerRegulatorSwitch (CreatureObject *creature, TangibleObject *powerRegulator, int indx)
void sendPowerRegulatorControls (CreatureObject *creature, BuildingObject *building, TangibleObject *powerRegulator)
String getDNAHash (const String &usersample)
bool isPlanetCapped ()
void scheduleBaseDestruction (BuildingObject *building, CreatureObject *creature)
void initializeNewVulnerability (BuildingObject *building)
void notifyInstallationDestruction (InstallationObject *installation)
void notifyTurretDestruction (BuildingObject *building, InstallationObject *turret)
void notifyMinefieldDestruction (BuildingObject *building, InstallationObject *turret)
void sendSelectDeedToDonate (BuildingObject *building, CreatureObject *creature, int turretIndex)
void sendRemoveDefenseConfirmation (BuildingObject *building, CreatureObject *creature, unsigned long long deedOID)
void performDefenseDontation (BuildingObject *building, CreatureObject *creature, unsigned long long deedOID, int turretIndex)
void sendStatus (BuildingObject *building, CreatureObject *creature)
void addMinefield (BuildingObject *building, SceneObject *minefield)
void addTurret (BuildingObject *building, SceneObject *turret)
void addScanner (BuildingObject *building, SceneObject *scanner)
void removeDefense (BuildingObject *building, CreatureObject *creature, unsigned long long deedOID)
bool canUseTerminals (CreatureObject *creature, BuildingObject *building, SceneObject *terminal)
void sendTurretAttackListTo (CreatureObject *creature, SceneObject *turretControlTerminal)
bool canPlaceMoreBases (CreatureObject *creature)
int getImperialBaseCount ()
int getRebelBaseCount ()
int getRebelScore ()
int getImperialScore ()
void setRebelScore (int val)
void setImperialScore (int val)
unsigned int getWinningFaction ()
float getGCWDiscount (CreatureObject *creature)
int getGCWXPBonus ()
void broadcastBuilding (BuildingObject *building, StringIdChatParameter &params)
int getPointValue (const String &templateString)
void addPointValue (const String &templateString, int val)
void addRacialPenalty (int race, float val)
float getRacialPenalty (int race)
bool isRacialPenaltyEnabled ()
bool shouldSpawnDefenses ()
int getInitialVulnerabilityDelay ()
void awardSlicingXP (CreatureObject *creature, const String &xpType, int value)
operator const GCWManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< GCWManager * > _this
Static Public Attributes
static const int IMPERIALHASH = 3679112276
static const int REBELHASH = 370444368
static const int NOTAFACTIONBASE = 0
static const int PLAYERFACTIONBASE = 1
static const int STATICFACTIONBASE = 2
static int gcwCheckTimer = 3600
static int vulnerabilityDuration = 7200
static int vulnerabilityFrequency = 172800
static int resetTimer = 604800
static int sliceCooldown = 120
static int totalDNASamples = 10
static int dnaMatchesRequired = 28
static int destructionTimer = 600
static int maxBases = -1
static int overtCooldown = 300
static int reactvationTimer = 300
static int turretAutoFireTimeout = 120
static int maxBasesPerPlayer = 3
static int bonusXP = 15
static int bonusDiscount = 30
static bool spawnDefenses = true
static int initialVulnerabilityDelay = 0
static bool racialPenaltyEnabled = true
Protected Member Functions
void addDNAHash (const String &usersample, const String &systemsample)
bool hasBase (BuildingObject *building)
bool dropBase (BuildingObject *building)
void addBase (BuildingObject *building)
BuildingObject * getBase (int indx)
bool hasStartTask (unsigned long long id)
bool addStartTask (unsigned long long id, Reference< Task * > newTask)
Reference< Task * > getStartTask (unsigned long long id)
bool dropStartTask (unsigned long long id)
bool hasEndTask (unsigned long long id)
bool addEndTask (unsigned long long id, Reference< Task * > newTask)
Reference< Task * > getEndTask (unsigned long long id)
bool dropEndTask (unsigned long long id)
bool hasDestroyTask (unsigned long long id)
bool addDestroyTask (unsigned long long id, Reference< Task * > newTask)
Reference< Task * > getDestroyTask (unsigned long long id)
bool dropDestroyTask (unsigned long long id)
virtual ~GCWManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
SortedVector< ManagedReference
< BuildingObject * > > gcwBaseList
VectorMap< unsigned long long,
Reference< Task * > > gcwStartTasks
VectorMap< unsigned long long,
Reference< Task * > > gcwEndTasks
VectorMap< String, String > dnaHash
VectorMap< unsigned long long,
Reference< Task * > > gcwDestroyTasks
Static Protected Attributes
static Mutex baseMutex
static VectorMap< String, int > baseValue
static HashTable< int, float > racialPenaltyMap
Private Member Functions
DestructibleBuildingDataComponent * getDestructibleBuildingData (BuildingObject *building)
void checkVulnerabilityData (BuildingObject *building)
void scheduleVulnerabilityStart (BuildingObject *building)
void scheduleVulnerabilityEnd (BuildingObject *building)
void initializeBaseTimers (BuildingObject *building)
void renewUplinkBand (BuildingObject *building)
void refreshExpiredVulnerability (BuildingObject *building)
void initializeNewVulnerability (DestructibleBuildingDataComponent *data)
String refreshDNA (DestructibleBuildingDataComponent *data, int chainLength)
void destroyStandaloneTurret (InstallationObject *turret)
void performDonateMine (BuildingObject *building, CreatureObject *creature, SceneObject *sceneObject)
void performDonateMinefield (BuildingObject *building, CreatureObject *creature, Deed *deed)
void performDonateTurret (BuildingObject *building, CreatureObject *creature, Deed *deed)
unsigned long long addChildInstallationFromDeed (BuildingObject *building, ChildObject *child, CreatureObject *creature, Deed *deed)
void verifyTurrets (BuildingObject *building)
TurretControlTerminalDataComponent * getTurretControlDataComponent (SceneObject *terminal)
TurretDataComponent * getTurretDataComponent (SceneObject *turret)
void generateTurretControlBoxTo (CreatureObject *creature, TangibleObject *turret, SceneObject *terminal)
bool canUseTurret (TurretDataComponent *turretData, TurretControlTerminalDataComponent *controlData, CreatureObject *creature)
void setRebelBaseCount (int val)
void setImperialBaseCount (int val)
Private Attributes
ManagedReference< Zone * > zone
int rebelBases
int rebelScore
int imperialBases
int imperialScore
Friends
class GCWManager
Detailed Description
Definition at line 344 of file GCWManager.h.
Constructor & Destructor Documentation
GCWManagerImplementation::GCWManagerImplementation (Zone * zne)
Definition at line 1110 of file GCWManager.cpp.
References _initializeImplementation(), baseValue, gcwBaseList, gcwDestroyTasks, gcwEndTasks, gcwStartTasks, server::zone::Zone::getZoneName(), imperialBases, imperialScore, rebelBases, rebelScore, and zone.
GCWManagerImplementation::GCWManagerImplementation (DummyConstructorParameter * param)
Definition at line 984 of file GCWManager.cpp.
References _initializeImplementation().
GCWManagerImplementation::~GCWManagerImplementation () protected virtual
Definition at line 989 of file GCWManager.cpp.
Member Function Documentation
DistributedObjectStub * GCWManagerImplementation::_getStub ()
Definition at line 1009 of file GCWManager.cpp.
References _this.
void GCWManagerImplementation::_initializeImplementation () protected
Definition at line 996 of file GCWManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by GCWManagerImplementation().
void GCWManagerImplementation::_serializationHelperMethod () protected
Definition at line 1045 of file GCWManager.cpp.
Referenced by _initializeImplementation().
void GCWManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 1004 of file GCWManager.cpp.
References _this.
Referenced by server::zone::managers::gcw::GCWManager::GCWManager().
void GCWManagerImplementation::abortShutdownSequence (BuildingObject * building, CreatureObject * creature)
Definition at line 481 of file GCWManagerImplementation.cpp.
References broadcastBuilding(), server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), dropDestroyTask(), getDestroyTask(), getDestructibleBuildingData(), server::zone::objects::scene::SceneObject::getObjectID(), hasDestroyTask(), isBaseVulnerable(), DestructibleBuildingDataComponent::OVERLOADED, overtCooldown, reactvationTimer, server::zone::objects::creature::CreatureObject::sendSystemMessage(), DestructibleBuildingDataComponent::setRebootFinishTime(), DestructibleBuildingDataComponent::setState(), server::zone::objects::scene::variables::StringId::setStringId(), and server::chat::StringIdChatParameter::setTO().
Referenced by server::zone::managers::gcw::GCWManager::abortShutdownSequence().
void GCWManagerImplementation::addBase (BuildingObject * building) protected
Definition at line 1168 of file GCWManager.cpp.
References _this, and gcwBaseList.
Referenced by registerGCWBase().
uint64 GCWManagerImplementation::addChildInstallationFromDeed (BuildingObject * building, ChildObject * child, CreatureObject * creature, Deed * deed) private
Definition at line 2361 of file GCWManagerImplementation.cpp.
References server::zone::objects::installation::InstallationObject::createChildObjects(), server::zone::objects::scene::SceneObject::getChildObjects(), ChildObject::getDirection(), server::zone::objects::scene::SceneObject::getDirection(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::tangible::deed::Deed::getGeneratedObjectTemplate(), server::zone::objects::scene::SceneObject::getObjectID(), ChildObject::getPosition(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), server::zone::objects::scene::SceneObject::isInstallationObject(), server::zone::objects::scene::SceneObject::isTurret(), server::zone::objects::scene::SceneObject::setDetailedDescription(), server::zone::objects::tangible::TangibleObject::setFaction(), server::zone::objects::structure::StructureObject::setOwnerObjectID(), server::zone::objects::tangible::TangibleObject::setPvpStatusBitmask(), and zone.
Referenced by performDonateMinefield(), and performDonateTurret().
bool GCWManagerImplementation::addDestroyTask (unsigned long long id, Reference< Task * > newTask) protected
Definition at line 1244 of file GCWManager.cpp.
References _this, and gcwDestroyTasks.
Referenced by scheduleBaseDestruction().
void GCWManagerImplementation::addDNAHash (const String & usersample, const String & systemsample) protected
Definition at line 1150 of file GCWManager.cpp.
References _this, and dnaHash.
Referenced by initialize().
bool GCWManagerImplementation::addEndTask (unsigned long long id, Reference< Task * > newTask) protected
Definition at line 1215 of file GCWManager.cpp.
References _this, and gcwEndTasks.
Referenced by scheduleVulnerabilityEnd().
void GCWManagerImplementation::addMinefield (BuildingObject * building, SceneObject * minefield)
Definition at line 2409 of file GCWManagerImplementation.cpp.
References DestructibleBuildingDataComponent::addMinefield(), getDestructibleBuildingData(), server::zone::objects::scene::SceneObject::getObjectID(), and DestructibleBuildingDataComponent::getTotalMinefieldCount().
Referenced by server::zone::managers::gcw::GCWManager::addMinefield().
void GCWManagerImplementation::addPointValue (const String & templateString, int val)
Definition at line 1340 of file GCWManager.cpp.
References baseMutex, and baseValue.
Referenced by server::zone::managers::gcw::GCWManager::addPointValue(), and loadLuaConfig().
void GCWManagerImplementation::addRacialPenalty (int race, float val)
Definition at line 1349 of file GCWManager.cpp.
References baseMutex, and racialPenaltyMap.
Referenced by server::zone::managers::gcw::GCWManager::addRacialPenalty(), and loadLuaConfig().
void GCWManagerImplementation::addScanner (BuildingObject * building, SceneObject * scanner)
Definition at line 2427 of file GCWManagerImplementation.cpp.
References DestructibleBuildingDataComponent::addScanner(), getDestructibleBuildingData(), server::zone::objects::scene::SceneObject::getObjectID(), and DestructibleBuildingDataComponent::getTotalScannerCount().
Referenced by server::zone::managers::gcw::GCWManager::addScanner().
bool GCWManagerImplementation::addStartTask (unsigned long long id, Reference< Task * > newTask) protected
Definition at line 1186 of file GCWManager.cpp.
References _this, and gcwStartTasks.
Referenced by registerGCWBase(), and scheduleVulnerabilityStart().
void GCWManagerImplementation::addTurret (BuildingObject * building, SceneObject * turret)
Definition at line 2445 of file GCWManagerImplementation.cpp.
References DestructibleBuildingDataComponent::addTurret(), getDestructibleBuildingData(), server::zone::objects::scene::SceneObject::getObjectID(), DestructibleBuildingDataComponent::getTotalTurretCount(), and verifyTurrets().
Referenced by server::zone::managers::gcw::GCWManager::addTurret().
void GCWManagerImplementation::awardSlicingXP (CreatureObject * creature, const String & xpType, int value)
Definition at line 2580 of file GCWManagerImplementation.cpp.
References server::zone::managers::player::PlayerManager::awardExperience(), server::zone::ZoneServer::getPlayerManager(), and server::zone::objects::scene::SceneObject::getZoneServer().
Referenced by server::zone::managers::gcw::GCWManager::awardSlicingXP(), handlePowerRegulatorSwitch(), processDNASample(), and verifyUplinkBand().
void GCWManagerImplementation::broadcastBuilding (BuildingObject * building, StringIdChatParameter & params)
Definition at line 2552 of file GCWManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zone.
Referenced by abortShutdownSequence(), server::zone::managers::gcw::GCWManager::broadcastBuilding(), doBaseDestruction(), handlePowerRegulatorSwitch(), and scheduleBaseDestruction().
bool GCWManagerImplementation::canPlaceMoreBases (CreatureObject * creature)
Definition at line 2484 of file GCWManagerImplementation.cpp.
References server::zone::ZoneServer::getObject(), server::zone::objects::player::PlayerObject::getOwnedStructure(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::player::PlayerObject::getTotalOwnedStructureCount(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), maxBasesPerPlayer, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zone.
Referenced by server::zone::managers::gcw::GCWManager::canPlaceMoreBases().
bool GCWManagerImplementation::canStartSlice (CreatureObject * creature, TangibleObject * terminal)
Definition at line 1439 of file GCWManagerImplementation.cpp.
References canUseTerminals(), SceneObjectType::FACTIONBUILDING, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::creature::CreatureObject::getPlayerObject(), isBaseVulnerable(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), isSecurityTermSliced(), isTerminalDamaged(), isUplinkJammed(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::gcw::GCWManager::canStartSlice().
bool GCWManagerImplementation::canUseTerminals (CreatureObject * creature, BuildingObject * building, SceneObject * terminal)
Definition at line 2512 of file GCWManagerImplementation.cpp.
References FactionStatus::COVERT, server::zone::objects::tangible::TangibleObject::getFaction(), ValidatedPosition::getParent(), server::zone::objects::scene::SceneObject::getParentID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), FactionStatus::OVERT, CreatureFlag::OVERT, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by canStartSlice(), and server::zone::managers::gcw::GCWManager::canUseTerminals().
bool GCWManagerImplementation::canUseTurret (TurretDataComponent * turretData, TurretControlTerminalDataComponent * controlData, CreatureObject * creature) private
Definition at line 1140 of file GCWManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::closeSuiWindowType(), TurretDataComponent::getController(), server::zone::objects::creature::CreatureObject::getPlayerObject(), TurretControlTerminalDataComponent::getSuiBoxID(), TurretDataComponent::getTarget(), server::zone::objects::player::PlayerObject::hasSuiBox(), and SuiWindowType::HQ_TURRET_TERMINAL.
Referenced by sendTurretAttackListTo().
void GCWManagerImplementation::checkVulnerabilityData (BuildingObject * building) private
Definition at line 768 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), DestructibleBuildingDataComponent::getNextVulnerableTime(), server::zone::objects::scene::SceneObject::getObjectID(), DestructibleBuildingDataComponent::getState(), DestructibleBuildingDataComponent::getVulnerabilityEndTime(), refreshExpiredVulnerability(), scheduleBaseDestruction(), scheduleVulnerabilityStart(), DestructibleBuildingDataComponent::SHUTDOWNSEQUENCE, startVulnerability(), and zone.
Referenced by registerGCWBase().
void GCWManagerImplementation::completeSecuritySlice (CreatureObject * creature, TangibleObject * securityTerminal)
Definition at line 1482 of file GCWManagerImplementation.cpp.
References SceneObjectType::FACTIONBUILDING, getDestructibleBuildingData(), server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), DestructibleBuildingDataComponent::setState(), and DestructibleBuildingDataComponent::SLICED.
Referenced by server::zone::managers::gcw::GCWManager::completeSecuritySlice().
void server::zone::managers::gcw::GCWManagerImplementation::destroyStandaloneTurret (InstallationObject * turret) private
void GCWManagerImplementation::doBaseDestruction (StructureObject * structure)
Definition at line 519 of file GCWManagerImplementation.cpp.
Referenced by server::zone::managers::gcw::GCWManager::doBaseDestruction().
void GCWManagerImplementation::doBaseDestruction (BuildingObject * building)
Definition at line 529 of file GCWManagerImplementation.cpp.
References _this, broadcastBuilding(), ObserverEventType::FACTIONBASEFLIPPED, BaseDestructionTask::getCountdown(), getDestroyTask(), getDestructibleBuildingData(), server::zone::objects::building::BuildingObject::getFactionBaseType(), server::zone::objects::scene::SceneObject::getObjectID(), PLAYERFACTIONBASE, server::chat::StringIdChatParameter::setDI(), STATICFACTIONBASE, and unregisterGCWBase().
bool GCWManagerImplementation::dropBase (BuildingObject * building) protected
Definition at line 1162 of file GCWManager.cpp.
References _this, and gcwBaseList.
Referenced by unregisterGCWBase().
bool GCWManagerImplementation::dropDestroyTask (unsigned long long id) protected
Definition at line 1261 of file GCWManager.cpp.
References _this, and gcwDestroyTasks.
Referenced by abortShutdownSequence(), and unregisterGCWBase().
bool GCWManagerImplementation::dropEndTask (unsigned long long id) protected
Definition at line 1232 of file GCWManager.cpp.
References _this, and gcwEndTasks.
Referenced by endVulnerability(), and unregisterGCWBase().
bool GCWManagerImplementation::dropStartTask (unsigned long long id) protected
Definition at line 1203 of file GCWManager.cpp.
References _this, and gcwStartTasks.
Referenced by resetVulnerability(), startVulnerability(), and unregisterGCWBase().
void GCWManagerImplementation::endVulnerability (BuildingObject * building)
Definition at line 264 of file GCWManagerImplementation.cpp.
References server::zone::objects::building::BuildingObject::broadcastCellPermissions(), DestructibleBuildingDataComponent::clearDNAProfiles(), dropEndTask(), getDestructibleBuildingData(), DestructibleBuildingDataComponent::getLastVulnerableTime(), DestructibleBuildingDataComponent::getNextVulnerableTime(), server::zone::objects::scene::SceneObject::getObjectID(), DestructibleBuildingDataComponent::INVULNERABLE, scheduleVulnerabilityStart(), DestructibleBuildingDataComponent::setLastVulnerableTime(), DestructibleBuildingDataComponent::setNextVulnerableTime(), DestructibleBuildingDataComponent::setState(), DestructibleBuildingDataComponent::setVulnerabilityEndTime(), vulnerabilityDuration, and vulnerabilityFrequency.
Referenced by server::zone::managers::gcw::GCWManager::endVulnerability().
void GCWManagerImplementation::failSecuritySlice (TangibleObject * securityTerminal)
Definition at line 1572 of file GCWManagerImplementation.cpp.
References SceneObjectType::FACTIONBUILDING, getDestructibleBuildingData(), server::zone::objects::scene::SceneObject::getParentRecursively(), DestructibleBuildingDataComponent::getVulnerabilityEndTime(), isBaseVulnerable(), DestructibleBuildingDataComponent::setSliceRepairTime(), DestructibleBuildingDataComponent::setTerminalBeingRepaired(), and DestructibleBuildingDataComponent::setTerminalDamaged().
Referenced by server::zone::managers::gcw::GCWManager::failSecuritySlice().
void GCWManagerImplementation::finalize () protected
Definition at line 993 of file GCWManager.cpp.
void GCWManagerImplementation::generateTurretControlBoxTo (CreatureObject * creature, TangibleObject * turret, SceneObject * terminal) private
Definition at line 1056 of file GCWManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), CollisionManager::checkLineOfSight(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getObjectNameStringIdName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getSlottedObject(), TurretDataComponent::getTarget(), getTurretControlDataComponent(), getTurretDataComponent(), SuiWindowType::HQ_TURRET_TERMINAL, server::zone::objects::creature::CreatureObject::isAttackableBy(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), TurretDataComponent::setController(), server::zone::objects::scene::variables::StringId::setStringId(), TurretControlTerminalDataComponent::setSuiBoxID(), and zone.
Referenced by sendTurretAttackListTo().
BuildingObject * GCWManagerImplementation::getBase (int indx) protected
Definition at line 1174 of file GCWManager.cpp.
References _this, and gcwBaseList.
Referenced by performGCWTasks().
Reference< Task * > GCWManagerImplementation::getDestroyTask (unsigned long long id) protected
Definition at line 1255 of file GCWManager.cpp.
References _this, and gcwDestroyTasks.
Referenced by abortShutdownSequence(), doBaseDestruction(), and unregisterGCWBase().
DestructibleBuildingDataComponent * GCWManagerImplementation::getDestructibleBuildingData (BuildingObject * building) private
Definition at line 900 of file GCWManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDataObjectComponent(), and server::zone::objects::scene::SceneObject::isGCWBase().
Referenced by abortShutdownSequence(), addMinefield(), addScanner(), addTurret(), checkVulnerabilityData(), completeSecuritySlice(), doBaseDestruction(), endVulnerability(), failSecuritySlice(), handlePowerRegulatorSwitch(), initializeBaseTimers(), initializeNewVulnerability(), isBandIdentified(), isBaseVulnerable(), isDNASampled(), isPowerOverloaded(), isSecurityTermSliced(), isShutdownSequenceStarted(), isTerminalDamaged(), isUplinkJammed(), notifyInstallationDestruction(), notifyMinefieldDestruction(), notifyTurretDestruction(), performDonateMinefield(), performDonateTurret(), processDNASample(), refreshExpiredVulnerability(), registerGCWBase(), renewUplinkBand(), repairTerminal(), resetVulnerability(), scheduleBaseDestruction(), scheduleVulnerabilityEnd(), scheduleVulnerabilityStart(), sendBaseDefenseStatus(), sendDNASampleMenu(), sendJamUplinkMenu(), sendPowerRegulatorControls(), sendRemoveDefenseConfirmation(), sendResetVerification(), sendSelectDeedToDonate(), sendStatus(), sendTurretAttackListTo(), startVulnerability(), verifyTurrets(), and verifyUplinkBand().
String GCWManagerImplementation::getDNAHash (const String & usersample)
Definition at line 1144 of file GCWManager.cpp.
References _this, and dnaHash.
Referenced by server::zone::managers::gcw::GCWManager::getDNAHash(), and processDNASample().
Reference< Task * > GCWManagerImplementation::getEndTask (unsigned long long id) protected
Definition at line 1226 of file GCWManager.cpp.
References _this, and gcwEndTasks.
Referenced by unregisterGCWBase().
float GCWManagerImplementation::getGCWDiscount (CreatureObject * creature)
Definition at line 2595 of file GCWManagerImplementation.cpp.
References bonusDiscount, server::zone::objects::tangible::TangibleObject::getFaction(), getRacialPenalty(), server::zone::objects::creature::CreatureObject::getSpecies(), getWinningFaction(), IMPERIALHASH, and racialPenaltyEnabled.
Referenced by server::zone::managers::gcw::GCWManager::getGCWDiscount().
int GCWManagerImplementation::getGCWXPBonus ()
Definition at line 1326 of file GCWManager.cpp.
References bonusXP.
Referenced by server::zone::managers::gcw::GCWManager::getGCWXPBonus().
int GCWManagerImplementation::getImperialBaseCount ()
Definition at line 1273 of file GCWManager.cpp.
References imperialBases.
Referenced by server::zone::managers::gcw::GCWManager::getImperialBaseCount().
int GCWManagerImplementation::getImperialScore ()
Definition at line 1288 of file GCWManager.cpp.
References imperialScore.
Referenced by server::zone::managers::gcw::GCWManager::getImperialScore(), getWinningFaction(), registerGCWBase(), and unregisterGCWBase().
int GCWManagerImplementation::getInitialVulnerabilityDelay ()
Definition at line 1377 of file GCWManager.cpp.
References initialVulnerabilityDelay.
Referenced by server::zone::managers::gcw::GCWManager::getInitialVulnerabilityDelay(), initializeBaseTimers(), and registerGCWBase().
int GCWManagerImplementation::getPointValue (const String & templateString)
Definition at line 1331 of file GCWManager.cpp.
References baseMutex, and baseValue.
Referenced by server::zone::managers::gcw::GCWManager::getPointValue(), registerGCWBase(), and unregisterGCWBase().
float GCWManagerImplementation::getRacialPenalty (int race)
Definition at line 1358 of file GCWManager.cpp.
References baseMutex, and racialPenaltyMap.
Referenced by getGCWDiscount(), and server::zone::managers::gcw::GCWManager::getRacialPenalty().
int GCWManagerImplementation::getRebelBaseCount ()
Definition at line 1278 of file GCWManager.cpp.
References rebelBases.
Referenced by server::zone::managers::gcw::GCWManager::getRebelBaseCount().
int GCWManagerImplementation::getRebelScore ()
Definition at line 1283 of file GCWManager.cpp.
References rebelScore.
Referenced by server::zone::managers::gcw::GCWManager::getRebelScore(), getWinningFaction(), registerGCWBase(), and unregisterGCWBase().
Reference< Task * > GCWManagerImplementation::getStartTask (unsigned long long id) protected
Definition at line 1197 of file GCWManager.cpp.
References _this, and gcwStartTasks.
Referenced by resetVulnerability(), and unregisterGCWBase().
TurretControlTerminalDataComponent * GCWManagerImplementation::getTurretControlDataComponent (SceneObject * terminal) private
Definition at line 1047 of file GCWManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDataObjectComponent().
Referenced by generateTurretControlBoxTo(), and sendTurretAttackListTo().
TurretDataComponent * GCWManagerImplementation::getTurretDataComponent (SceneObject * turret) private
Definition at line 1038 of file GCWManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getDataObjectComponent().
Referenced by generateTurretControlBoxTo(), and sendTurretAttackListTo().
unsigned int GCWManagerImplementation::getWinningFaction ()
Definition at line 1313 of file GCWManager.cpp.
References getImperialScore(), getRebelScore(), IMPERIALHASH, and REBELHASH.
Referenced by getGCWDiscount(), and server::zone::managers::gcw::GCWManager::getWinningFaction().
void GCWManagerImplementation::handlePowerRegulatorSwitch (CreatureObject * creature, TangibleObject * powerRegulator, int indx)
Definition at line 1815 of file GCWManagerImplementation.cpp.
References awardSlicingXP(), broadcastBuilding(), SceneObjectType::FACTIONBUILDING, getDestructibleBuildingData(), DestructibleBuildingDataComponent::getOnSwitchCount(), server::zone::objects::scene::SceneObject::getParentRecursively(), DestructibleBuildingDataComponent::getPowerPosition(), isBaseVulnerable(), DestructibleBuildingDataComponent::OVERLOADED, sendPowerRegulatorControls(), DestructibleBuildingDataComponent::setState(), DestructibleBuildingDataComponent::turnSwitchOff(), and DestructibleBuildingDataComponent::turnSwitchOn().
Referenced by server::zone::managers::gcw::GCWManager::handlePowerRegulatorSwitch().
bool GCWManagerImplementation::hasBase (BuildingObject * building) protected
Definition at line 1156 of file GCWManager.cpp.
References _this, and gcwBaseList.
Referenced by registerGCWBase(), scheduleVulnerabilityEnd(), scheduleVulnerabilityStart(), and unregisterGCWBase().
bool GCWManagerImplementation::hasDestroyTask (unsigned long long id) protected
Definition at line 1238 of file GCWManager.cpp.
References _this, and gcwDestroyTasks.
Referenced by abortShutdownSequence(), performGCWTasks(), and scheduleBaseDestruction().
bool GCWManagerImplementation::hasEndTask (unsigned long long id) protected
Definition at line 1209 of file GCWManager.cpp.
References _this, and gcwEndTasks.
Referenced by performGCWTasks().
bool GCWManagerImplementation::hasStartTask (unsigned long long id) protected
Definition at line 1180 of file GCWManager.cpp.
References _this, and gcwStartTasks.
Referenced by performGCWTasks().
void GCWManagerImplementation::initialize ()
Definition at line 81 of file GCWManagerImplementation.cpp.
References addDNAHash().
Referenced by server::zone::managers::gcw::GCWManager::initialize(), and start().
void GCWManagerImplementation::initializeBaseTimers (BuildingObject * building) private
Definition at line 835 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), getInitialVulnerabilityDelay(), DestructibleBuildingDataComponent::getPlacmenetTime(), DestructibleBuildingDataComponent::setLastResetTime(), DestructibleBuildingDataComponent::setLastVulnerableTime(), DestructibleBuildingDataComponent::setNextVulnerableTime(), DestructibleBuildingDataComponent::setPlacementTime(), DestructibleBuildingDataComponent::setSliceRepairTime(), DestructibleBuildingDataComponent::setTerminalDamaged(), DestructibleBuildingDataComponent::setVulnerabilityEndTime(), vulnerabilityDuration, and vulnerabilityFrequency.
Referenced by registerGCWBase().
void GCWManagerImplementation::initializeNewVulnerability (BuildingObject * building)
Definition at line 208 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData().
Referenced by server::zone::managers::gcw::GCWManager::initializeNewVulnerability(), refreshExpiredVulnerability(), and registerGCWBase().
void GCWManagerImplementation::initializeNewVulnerability (DestructibleBuildingDataComponent * data) private
Definition at line 219 of file GCWManagerImplementation.cpp.
References DestructibleBuildingDataComponent::setRebootFinishTime(), DestructibleBuildingDataComponent::setSampleMatches(), DestructibleBuildingDataComponent::setSliceRepairTime(), DestructibleBuildingDataComponent::setState(), DestructibleBuildingDataComponent::setSystemDNAString(), DestructibleBuildingDataComponent::setTerminalDamaged(), DestructibleBuildingDataComponent::turnAllSwitchesOn(), and DestructibleBuildingDataComponent::VULNERABLE.
bool GCWManagerImplementation::isBandIdentified (BuildingObject * building)
Definition at line 1371 of file GCWManagerImplementation.cpp.
References DestructibleBuildingDataComponent::BAND, getDestructibleBuildingData(), and DestructibleBuildingDataComponent::getState().
Referenced by server::zone::managers::gcw::GCWManager::isBandIdentified(), sendJamUplinkMenu(), and verifyUplinkBand().
bool GCWManagerImplementation::isBaseVulnerable (BuildingObject * building)
Definition at line 1360 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), DestructibleBuildingDataComponent::getState(), DestructibleBuildingDataComponent::INVULNERABLE, and CreatureFlag::OVERT.
Referenced by abortShutdownSequence(), canStartSlice(), failSecuritySlice(), handlePowerRegulatorSwitch(), server::zone::managers::gcw::GCWManager::isBaseVulnerable(), processDNASample(), repairTerminal(), resetVulnerability(), scheduleBaseDestruction(), sendDNASampleMenu(), sendJamUplinkMenu(), sendPowerRegulatorControls(), sendResetVerification(), sendSelectDeedToDonate(), and sendStatus().
bool GCWManagerImplementation::isDNASampled (BuildingObject * building)
Definition at line 1404 of file GCWManagerImplementation.cpp.
References DestructibleBuildingDataComponent::DNA, getDestructibleBuildingData(), and DestructibleBuildingDataComponent::getState().
Referenced by server::zone::managers::gcw::GCWManager::isDNASampled().
bool GCWManagerImplementation::isPlanetCapped ()
Definition at line 1267 of file GCWManager.cpp.
References _this, gcwBaseList, and maxBases.
Referenced by server::zone::managers::gcw::GCWManager::isPlanetCapped().
bool GCWManagerImplementation::isPowerOverloaded (BuildingObject * building)
Definition at line 1416 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), DestructibleBuildingDataComponent::getState(), and DestructibleBuildingDataComponent::OVERLOADED.
Referenced by server::zone::managers::gcw::GCWManager::isPowerOverloaded().
bool GCWManagerImplementation::isRacialPenaltyEnabled ()
Definition at line 1367 of file GCWManager.cpp.
References racialPenaltyEnabled.
Referenced by server::zone::managers::gcw::GCWManager::isRacialPenaltyEnabled().
bool GCWManagerImplementation::isSecurityTermSliced (BuildingObject * building)
Definition at line 1392 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), DestructibleBuildingDataComponent::getState(), and DestructibleBuildingDataComponent::SLICED.
Referenced by canStartSlice(), and server::zone::managers::gcw::GCWManager::isSecurityTermSliced().
bool GCWManagerImplementation::isShutdownSequenceStarted (BuildingObject * building)
Definition at line 1427 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), DestructibleBuildingDataComponent::getState(), and DestructibleBuildingDataComponent::SHUTDOWNSEQUENCE.
Referenced by server::zone::managers::gcw::GCWManager::isShutdownSequenceStarted().
bool GCWManagerImplementation::isTerminalDamaged (TangibleObject * securityTerminal)
Definition at line 1502 of file GCWManagerImplementation.cpp.
References SceneObjectType::FACTIONBUILDING, getDestructibleBuildingData(), server::zone::objects::scene::SceneObject::getParentRecursively(), DestructibleBuildingDataComponent::getSliceRepairTime(), DestructibleBuildingDataComponent::isTerminalDamanged(), DestructibleBuildingDataComponent::setTerminalBeingRepaired(), DestructibleBuildingDataComponent::setTerminalDamaged(), and sliceCooldown.
Referenced by canStartSlice(), and server::zone::managers::gcw::GCWManager::isTerminalDamaged().
bool GCWManagerImplementation::isUplinkJammed (BuildingObject * building)
Definition at line 1381 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), DestructibleBuildingDataComponent::getState(), and DestructibleBuildingDataComponent::JAMMED.
Referenced by canStartSlice(), server::zone::managers::gcw::GCWManager::isUplinkJammed(), and verifyUplinkBand().
void GCWManagerImplementation::loadLuaConfig ()
Definition at line 102 of file GCWManagerImplementation.cpp.
References addPointValue(), addRacialPenalty(), baseValue, bonusDiscount, bonusXP, destructionTimer, dnaMatchesRequired, gcwCheckTimer, initialVulnerabilityDelay, maxBases, maxBasesPerPlayer, overtCooldown, racialPenaltyEnabled, reactvationTimer, resetTimer, sliceCooldown, spawnDefenses, totalDNASamples, turretAutoFireTimeout, vulnerabilityDuration, and vulnerabilityFrequency.
Referenced by server::zone::managers::gcw::GCWManager::loadLuaConfig(), and start().
void GCWManagerImplementation::lock (bool doLock = true) protected
Definition at line 1017 of file GCWManager.cpp.
References _this.
void GCWManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 1021 of file GCWManager.cpp.
References _this.
void GCWManagerImplementation::notifyInstallationDestruction (InstallationObject * installation)
Definition at line 1861 of file GCWManagerImplementation.cpp.
References server::zone::objects::installation::InstallationObject::broadcastMessage(), server::zone::objects::scene::SceneObject::containsChildObject(), server::zone::objects::installation::InstallationObject::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::getChildObjects(), getDestructibleBuildingData(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::structure::StructureObject::getOwnerObjectID(), DestructibleBuildingDataComponent::hasMinefield(), DestructibleBuildingDataComponent::hasTurret(), server::zone::objects::scene::SceneObject::isMinefield(), server::zone::objects::scene::SceneObject::isTurret(), notifyMinefieldDestruction(), notifyTurretDestruction(), and zone.
Referenced by server::zone::managers::gcw::GCWManager::notifyInstallationDestruction(), and removeDefense().
void GCWManagerImplementation::notifyMinefieldDestruction (BuildingObject * building, InstallationObject * turret)
Definition at line 1981 of file GCWManagerImplementation.cpp.
References server::zone::objects::installation::InstallationObject::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), getDestructibleBuildingData(), DestructibleBuildingDataComponent::getIndexOfMinefield(), DestructibleBuildingDataComponent::getMinefieldOID(), server::zone::objects::scene::SceneObject::getObjectID(), DestructibleBuildingDataComponent::getTotalMinefieldCount(), and DestructibleBuildingDataComponent::setMinefieldID().
Referenced by notifyInstallationDestruction(), and server::zone::managers::gcw::GCWManager::notifyMinefieldDestruction().
void GCWManagerImplementation::notifyTurretDestruction (BuildingObject * building, InstallationObject * turret)
Definition at line 1943 of file GCWManagerImplementation.cpp.
References server::zone::objects::building::BuildingObject::broadcastCellPermissions(), server::zone::objects::installation::InstallationObject::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), getDestructibleBuildingData(), DestructibleBuildingDataComponent::getIndexOfTurret(), server::zone::objects::scene::SceneObject::getObjectID(), DestructibleBuildingDataComponent::getTotalTurretCount(), DestructibleBuildingDataComponent::getTurretID(), DestructibleBuildingDataComponent::setDefense(), DestructibleBuildingDataComponent::setTurretID(), and verifyTurrets().
Referenced by notifyInstallationDestruction(), and server::zone::managers::gcw::GCWManager::notifyTurretDestruction().
GCWManagerImplementation::operator const GCWManager * ()
Definition at line 1013 of file GCWManager.cpp.
void GCWManagerImplementation::performDefenseDontation (BuildingObject * building, CreatureObject * creature, unsigned long long deedOID, int turretIndex)
Definition at line 2125 of file GCWManagerImplementation.cpp.
References server::zone::ZoneServer::getObject(), SceneObjectType::MINE, SceneObjectType::MINEFIELD, performDonateMine(), performDonateMinefield(), performDonateTurret(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setTO(), SceneObjectType::TURRET, and zone.
Referenced by server::zone::managers::gcw::GCWManager::performDefenseDontation().
void GCWManagerImplementation::performDonateMine (BuildingObject * building, CreatureObject * creature, SceneObject * sceneObject) private
Definition at line 2171 of file GCWManagerImplementation.cpp.
References CreatureFlag::ATTACKABLE, server::zone::objects::scene::SceneObject::getChildObjects(), server::zone::objects::scene::SceneObject::getObjectNameStringIdFile(), server::zone::objects::scene::SceneObject::getObjectNameStringIdName(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::tangible::TangibleObject::setPvpStatusBitmask(), and server::chat::StringIdChatParameter::setTO().
Referenced by performDefenseDontation().
void GCWManagerImplementation::performDonateMinefield (BuildingObject * building, CreatureObject * creature, Deed * deed) private
Definition at line 2213 of file GCWManagerImplementation.cpp.
References addChildInstallationFromDeed(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), getDestructibleBuildingData(), server::zone::objects::tangible::deed::Deed::getGeneratedObjectTemplate(), DestructibleBuildingDataComponent::getMinefieldOID(), server::zone::objects::scene::SceneObject::getObjectNameStringIdFile(), server::zone::objects::scene::SceneObject::getObjectNameStringIdName(), server::zone::objects::scene::SceneObject::getObjectTemplate(), ChildObject::getTemplateFile(), DestructibleBuildingDataComponent::getTotalMinefieldCount(), DestructibleBuildingDataComponent::getTotalTurretCount(), SceneObjectType::MINEFIELD, server::zone::objects::creature::CreatureObject::sendSystemMessage(), DestructibleBuildingDataComponent::setMinefieldID(), server::zone::objects::scene::variables::StringId::setStringId(), and server::chat::StringIdChatParameter::setTO().
Referenced by performDefenseDontation().
void GCWManagerImplementation::performDonateTurret (BuildingObject * building, CreatureObject * creature, Deed * deed) private
Definition at line 2290 of file GCWManagerImplementation.cpp.
References addChildInstallationFromDeed(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), getDestructibleBuildingData(), server::zone::objects::tangible::deed::Deed::getGeneratedObjectTemplate(), server::zone::objects::scene::SceneObject::getObjectNameStringIdFile(), server::zone::objects::scene::SceneObject::getObjectNameStringIdName(), server::zone::objects::scene::SceneObject::getObjectTemplate(), ChildObject::getTemplateFile(), DestructibleBuildingDataComponent::getTotalTurretCount(), DestructibleBuildingDataComponent::getTurretID(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTO(), DestructibleBuildingDataComponent::setTurretID(), SceneObjectType::TURRET, and verifyTurrets().
Referenced by performDefenseDontation().
void GCWManagerImplementation::performGCWTasks ()
Definition at line 631 of file GCWManagerImplementation.cpp.
References _this, gcwBaseList, gcwCheckTimer, gcwDestroyTasks, gcwEndTasks, gcwStartTasks, getBase(), server::zone::objects::scene::SceneObject::getObjectID(), hasDestroyTask(), hasEndTask(), hasStartTask(), IMPERIALHASH, REBELHASH, setImperialBaseCount(), setRebelBaseCount(), and zone.
Referenced by server::zone::managers::gcw::GCWManager::performGCWTasks().
void GCWManagerImplementation::processDNASample (CreatureObject * creature, TangibleObject * overrideTerminal, const String & sampleChain, int indx)
Definition at line 1701 of file GCWManagerImplementation.cpp.
References awardSlicingXP(), DestructibleBuildingDataComponent::DNA, dnaMatchesRequired, SceneObjectType::FACTIONBUILDING, getDestructibleBuildingData(), getDNAHash(), DestructibleBuildingDataComponent::getDNAProfile(), server::zone::objects::scene::SceneObject::getParentRecursively(), DestructibleBuildingDataComponent::getSampleMatches(), DestructibleBuildingDataComponent::incrementSampleMatches(), isBaseVulnerable(), DestructibleBuildingDataComponent::modifySampleAt(), sendDNASampleMenu(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and DestructibleBuildingDataComponent::setState().
Referenced by server::zone::managers::gcw::GCWManager::processDNASample().
void GCWManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 1052 of file GCWManager.cpp.
References readObjectMember().
bool GCWManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 1071 of file GCWManager.cpp.
References zone.
Referenced by readObject().
String GCWManagerImplementation::refreshDNA (DestructibleBuildingDataComponent * data, int chainLength) private
Definition at line 1767 of file GCWManagerImplementation.cpp.
References DestructibleBuildingDataComponent::setSystemDNAString().
Referenced by sendDNASampleMenu().
void GCWManagerImplementation::refreshExpiredVulnerability (BuildingObject * building) private
Definition at line 314 of file GCWManagerImplementation.cpp.
References gcwStartTasks, getDestructibleBuildingData(), DestructibleBuildingDataComponent::getLastVulnerableTime(), server::zone::objects::scene::SceneObject::getObjectID(), DestructibleBuildingDataComponent::getVulnerabilityEndTime(), initializeNewVulnerability(), DestructibleBuildingDataComponent::INVULNERABLE, renewUplinkBand(), scheduleVulnerabilityEnd(), scheduleVulnerabilityStart(), DestructibleBuildingDataComponent::setLastVulnerableTime(), DestructibleBuildingDataComponent::setNextVulnerableTime(), DestructibleBuildingDataComponent::setState(), DestructibleBuildingDataComponent::setVulnerabilityEndTime(), vulnerabilityDuration, and vulnerabilityFrequency.
Referenced by checkVulnerabilityData().
void GCWManagerImplementation::registerGCWBase (BuildingObject * building, bool initializeBase)
Definition at line 690 of file GCWManagerImplementation.cpp.
References _this, addBase(), addStartTask(), checkVulnerabilityData(), getDestructibleBuildingData(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::templates::SharedObjectTemplate::getFullTemplateString(), getImperialScore(), getInitialVulnerabilityDelay(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::structure::StructureObject::getOwnerCreatureObject(), getPointValue(), getRebelScore(), hasBase(), imperialBases, IMPERIALHASH, initializeBaseTimers(), initializeNewVulnerability(), rebelBases, REBELHASH, setImperialScore(), setRebelScore(), and startVulnerability().
Referenced by server::zone::managers::gcw::GCWManager::registerGCWBase().
void GCWManagerImplementation::removeDefense (BuildingObject * building, CreatureObject * creature, unsigned long long deedOID)
Definition at line 2102 of file GCWManagerImplementation.cpp.
References server::zone::ZoneServer::getObject(), notifyInstallationDestruction(), and zone.
Referenced by server::zone::managers::gcw::GCWManager::removeDefense(), and sendRemoveDefenseConfirmation().
void GCWManagerImplementation::renewUplinkBand (BuildingObject * building) private
Definition at line 814 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), and DestructibleBuildingDataComponent::setUplinkBand().
Referenced by refreshExpiredVulnerability(), startVulnerability(), and verifyUplinkBand().
void GCWManagerImplementation::repairTerminal (CreatureObject * creature, TangibleObject * securityTerminal)
Definition at line 1533 of file GCWManagerImplementation.cpp.
References SceneObjectType::FACTIONBUILDING, getDestructibleBuildingData(), server::zone::objects::scene::SceneObject::getParentRecursively(), DestructibleBuildingDataComponent::getSliceRepairTime(), isBaseVulnerable(), DestructibleBuildingDataComponent::isTerminalBeingRepaired(), DestructibleBuildingDataComponent::isTerminalDamanged(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), DestructibleBuildingDataComponent::setSliceRepairTime(), DestructibleBuildingDataComponent::setTerminalBeingRepaired(), and sliceCooldown.
Referenced by server::zone::managers::gcw::GCWManager::repairTerminal().
void GCWManagerImplementation::resetVulnerability (CreatureObject * creature, BuildingObject * building)
Definition at line 917 of file GCWManagerImplementation.cpp.
References _this, dropStartTask(), getDestructibleBuildingData(), DestructibleBuildingDataComponent::getLastResetTime(), server::zone::objects::scene::SceneObject::getObjectID(), getStartTask(), isBaseVulnerable(), resetTimer, scheduleVulnerabilityStart(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), DestructibleBuildingDataComponent::setLastResetTime(), DestructibleBuildingDataComponent::setLastVulnerableTime(), DestructibleBuildingDataComponent::setNextVulnerableTime(), DestructibleBuildingDataComponent::setVulnerabilityEndTime(), vulnerabilityDuration, and vulnerabilityFrequency.
Referenced by server::zone::managers::gcw::GCWManager::resetVulnerability().
void GCWManagerImplementation::rlock (bool doLock = true) protected
Definition at line 1025 of file GCWManager.cpp.
References _this.
void GCWManagerImplementation::runlock (bool doLock = true) protected
Definition at line 1041 of file GCWManager.cpp.
References _this.
void GCWManagerImplementation::scheduleBaseDestruction (BuildingObject * building, CreatureObject * creature)
Definition at line 449 of file GCWManagerImplementation.cpp.
References _this, addDestroyTask(), broadcastBuilding(), destructionTimer, getDestructibleBuildingData(), server::zone::objects::scene::SceneObject::getObjectID(), DestructibleBuildingDataComponent::getRebootFinishTime(), hasDestroyTask(), isBaseVulnerable(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), DestructibleBuildingDataComponent::setState(), and DestructibleBuildingDataComponent::SHUTDOWNSEQUENCE.
Referenced by checkVulnerabilityData(), and server::zone::managers::gcw::GCWManager::scheduleBaseDestruction().
void GCWManagerImplementation::scheduleVulnerabilityEnd (BuildingObject * building) private
Definition at line 413 of file GCWManagerImplementation.cpp.
References _this, addEndTask(), getDestructibleBuildingData(), server::zone::objects::scene::SceneObject::getObjectID(), DestructibleBuildingDataComponent::getVulnerabilityEndTime(), and hasBase().
Referenced by refreshExpiredVulnerability(), and startVulnerability().
void GCWManagerImplementation::scheduleVulnerabilityStart (BuildingObject * building) private
Definition at line 230 of file GCWManagerImplementation.cpp.
References _this, addStartTask(), getDestructibleBuildingData(), DestructibleBuildingDataComponent::getNextVulnerableTime(), server::zone::objects::scene::SceneObject::getObjectID(), and hasBase().
Referenced by checkVulnerabilityData(), endVulnerability(), refreshExpiredVulnerability(), and resetVulnerability().
void GCWManagerImplementation::sendBaseDefenseStatus (CreatureObject * creature, BuildingObject * building)
Definition at line 1202 of file GCWManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getChildObjects(), getDestructibleBuildingData(), server::zone::ZoneServer::getObject(), server::zone::objects::structure::StructureObject::getOwnerCreatureObject(), server::zone::objects::creature::CreatureObject::getPlayerObject(), DestructibleBuildingDataComponent::getTotalTurretCount(), DestructibleBuildingDataComponent::getTurretID(), SuiWindowType::HQ_TERMINAL, server::zone::objects::creature::CreatureObject::sendMessage(), and zone.
Referenced by server::zone::managers::gcw::GCWManager::sendBaseDefenseStatus().
void GCWManagerImplementation::sendDNASampleMenu (CreatureObject * creature, BuildingObject * building, TangibleObject * overrideTerminal)
Definition at line 1600 of file GCWManagerImplementation.cpp.
References DestructibleBuildingDataComponent::addDNAProfile(), getDestructibleBuildingData(), DestructibleBuildingDataComponent::getDNAProfile(), server::zone::objects::creature::CreatureObject::getPlayerObject(), DestructibleBuildingDataComponent::getSampleMatches(), server::zone::objects::creature::CreatureObject::hasSkill(), SuiWindowType::HQ_TERMINAL, isBaseVulnerable(), DestructibleBuildingDataComponent::isDNAInitialized(), refreshDNA(), server::zone::objects::creature::CreatureObject::sendMessage(), totalDNASamples, and zone.
Referenced by processDNASample(), and server::zone::managers::gcw::GCWManager::sendDNASampleMenu().
void GCWManagerImplementation::sendJamUplinkMenu (CreatureObject * creature, BuildingObject * building, TangibleObject * uplinkTerminal)
Definition at line 1243 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::HQ_TERMINAL, isBandIdentified(), isBaseVulnerable(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zone.
Referenced by server::zone::managers::gcw::GCWManager::sendJamUplinkMenu().
void GCWManagerImplementation::sendPowerRegulatorControls (CreatureObject * creature, BuildingObject * building, TangibleObject * powerRegulator)
Definition at line 1778 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), server::zone::objects::creature::CreatureObject::getPlayerObject(), DestructibleBuildingDataComponent::getPowerPosition(), SuiWindowType::HQ_TERMINAL, isBaseVulnerable(), server::zone::objects::creature::CreatureObject::sendMessage(), and zone.
Referenced by handlePowerRegulatorSwitch(), and server::zone::managers::gcw::GCWManager::sendPowerRegulatorControls().
void GCWManagerImplementation::sendRemoveDefenseConfirmation (BuildingObject * building, CreatureObject * creature, unsigned long long deedOID)
Definition at line 2076 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::HQ_TERMINAL, removeDefense(), server::zone::objects::creature::CreatureObject::sendMessage(), and zone.
Referenced by server::zone::managers::gcw::GCWManager::sendRemoveDefenseConfirmation().
void GCWManagerImplementation::sendResetVerification (CreatureObject * creature, BuildingObject * building)
Definition at line 1333 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::HQ_TERMINAL, isBaseVulnerable(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zone.
Referenced by server::zone::managers::gcw::GCWManager::sendResetVerification().
void GCWManagerImplementation::sendSelectDeedToDonate (BuildingObject * building, CreatureObject * creature, int turretIndex)
Definition at line 2014 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getSlottedObject(), SuiWindowType::HQ_TERMINAL, isBaseVulnerable(), SceneObjectType::MINE, SceneObjectType::MINEFIELD, server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), SceneObjectType::TURRET, and zone.
Referenced by server::zone::managers::gcw::GCWManager::sendSelectDeedToDonate().
void GCWManagerImplementation::sendStatus (BuildingObject * building, CreatureObject * creature)
Definition at line 1170 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), DestructibleBuildingDataComponent::getNextVulnerableTime(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), DestructibleBuildingDataComponent::getVulnerabilityEndTime(), isBaseVulnerable(), CreatureFlag::OVERT, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::gcw::GCWManager::sendStatus().
void GCWManagerImplementation::sendTurretAttackListTo (CreatureObject * creature, SceneObject * turretControlTerminal)
Definition at line 973 of file GCWManagerImplementation.cpp.
References canUseTurret(), server::zone::objects::player::PlayerObject::closeSuiWindowType(), SceneObjectType::FACTIONBUILDING, generateTurretControlBoxTo(), getDestructibleBuildingData(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::creature::CreatureObject::getPlayerObject(), getTurretControlDataComponent(), getTurretDataComponent(), DestructibleBuildingDataComponent::getTurretID(), TurretControlTerminalDataComponent::getTurrteIndex(), server::zone::objects::player::PlayerObject::hasSuiBoxWindowType(), SuiWindowType::HQ_TURRET_TERMINAL, server::zone::objects::creature::CreatureObject::isInCombat(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and zone.
Referenced by server::zone::managers::gcw::GCWManager::sendTurretAttackListTo().
void GCWManagerImplementation::setImperialBaseCount (int val) private
Definition at line 1308 of file GCWManager.cpp.
References imperialBases.
Referenced by performGCWTasks().
void GCWManagerImplementation::setImperialScore (int val)
Definition at line 1298 of file GCWManager.cpp.
References imperialScore.
Referenced by registerGCWBase(), server::zone::managers::gcw::GCWManager::setImperialScore(), and unregisterGCWBase().
void GCWManagerImplementation::setRebelBaseCount (int val) private
Definition at line 1303 of file GCWManager.cpp.
References rebelBases.
Referenced by performGCWTasks().
void GCWManagerImplementation::setRebelScore (int val)
Definition at line 1293 of file GCWManager.cpp.
References rebelScore.
Referenced by registerGCWBase(), server::zone::managers::gcw::GCWManager::setRebelScore(), and unregisterGCWBase().
bool GCWManagerImplementation::shouldSpawnDefenses ()
Definition at line 1372 of file GCWManager.cpp.
References spawnDefenses.
Referenced by server::zone::managers::gcw::GCWManager::shouldSpawnDefenses().
void GCWManagerImplementation::start ()
Definition at line 94 of file GCWManagerImplementation.cpp.
References _this, gcwCheckTimer, initialize(), and loadLuaConfig().
Referenced by server::zone::managers::gcw::GCWManager::start().
void GCWManagerImplementation::startVulnerability (BuildingObject * building)
Definition at line 172 of file GCWManagerImplementation.cpp.
References server::zone::objects::building::BuildingObject::broadcastCellPermissions(), dropStartTask(), getDestructibleBuildingData(), DestructibleBuildingDataComponent::getNextVulnerableTime(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getZone(), renewUplinkBand(), scheduleVulnerabilityEnd(), and DestructibleBuildingDataComponent::setLastVulnerableTime().
Referenced by checkVulnerabilityData(), registerGCWBase(), and server::zone::managers::gcw::GCWManager::startVulnerability().
void GCWManagerImplementation::unlock (bool doLock = true) protected
Definition at line 1037 of file GCWManager.cpp.
References _this.
void GCWManagerImplementation::unregisterGCWBase (BuildingObject * building)
Definition at line 573 of file GCWManagerImplementation.cpp.
References dropBase(), dropDestroyTask(), dropEndTask(), dropStartTask(), getDestroyTask(), getEndTask(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::templates::SharedObjectTemplate::getFullTemplateString(), getImperialScore(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getObjectTemplate(), getPointValue(), getRebelScore(), getStartTask(), hasBase(), imperialBases, IMPERIALHASH, rebelBases, REBELHASH, setImperialScore(), and setRebelScore().
Referenced by doBaseDestruction(), and server::zone::managers::gcw::GCWManager::unregisterGCWBase().
void GCWManagerImplementation::verifyTurrets (BuildingObject * building) private
Definition at line 2465 of file GCWManagerImplementation.cpp.
References getDestructibleBuildingData(), DestructibleBuildingDataComponent::getTotalTurretCount(), DestructibleBuildingDataComponent::getTurretID(), and DestructibleBuildingDataComponent::setDefense().
Referenced by addTurret(), notifyTurretDestruction(), and performDonateTurret().
void GCWManagerImplementation::verifyUplinkBand (CreatureObject * creature, BuildingObject * building, int band)
Definition at line 1293 of file GCWManagerImplementation.cpp.
References awardSlicingXP(), DestructibleBuildingDataComponent::BAND, getDestructibleBuildingData(), server::zone::objects::creature::CreatureObject::getPlayerObject(), DestructibleBuildingDataComponent::getUplinkBand(), isBandIdentified(), isUplinkJammed(), DestructibleBuildingDataComponent::JAMMED, renewUplinkBand(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and DestructibleBuildingDataComponent::setState().
Referenced by server::zone::managers::gcw::GCWManager::verifyUplinkBand().
void GCWManagerImplementation::wlock (bool doLock = true) protected
Definition at line 1029 of file GCWManager.cpp.
References _this.
void GCWManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 1033 of file GCWManager.cpp.
References _this.
void GCWManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 1085 of file GCWManager.cpp.
References writeObjectMembers().
int GCWManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 1092 of file GCWManager.cpp.
References zone.
Referenced by writeObject().
Friends And Related Function Documentation
friend class GCWManager friend
Definition at line 690 of file GCWManager.h.
Member Data Documentation
WeakReference<GCWManager*> server::zone::managers::gcw::GCWManagerImplementation::_this
Definition at line 656 of file GCWManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addBase(), addDestroyTask(), addDNAHash(), addEndTask(), addStartTask(), doBaseDestruction(), dropBase(), dropDestroyTask(), dropEndTask(), dropStartTask(), getBase(), getDestroyTask(), getDNAHash(), getEndTask(), getStartTask(), hasBase(), hasDestroyTask(), hasEndTask(), hasStartTask(), isPlanetCapped(), lock(), performGCWTasks(), registerGCWBase(), resetVulnerability(), rlock(), runlock(), scheduleBaseDestruction(), scheduleVulnerabilityEnd(), scheduleVulnerabilityStart(), start(), unlock(), and wlock().
Mutex GCWManagerImplementation::baseMutex static protected
Definition at line 370 of file GCWManager.h.
Referenced by addPointValue(), addRacialPenalty(), getPointValue(), and getRacialPenalty().
VectorMap< String, int > GCWManagerImplementation::baseValue static protected
Definition at line 372 of file GCWManager.h.
Referenced by addPointValue(), GCWManagerImplementation(), getPointValue(), and loadLuaConfig().
int GCWManagerImplementation::bonusDiscount = 30 static
Definition at line 414 of file GCWManager.h.
Referenced by getGCWDiscount(), and loadLuaConfig().
int GCWManagerImplementation::bonusXP = 15 static
Definition at line 412 of file GCWManager.h.
Referenced by getGCWXPBonus(), and loadLuaConfig().
int GCWManagerImplementation::destructionTimer = 600 static
Definition at line 400 of file GCWManager.h.
Referenced by loadLuaConfig(), and scheduleBaseDestruction().
VectorMap<String, String> server::zone::managers::gcw::GCWManagerImplementation::dnaHash protected
Definition at line 366 of file GCWManager.h.
Referenced by addDNAHash(), and getDNAHash().
int GCWManagerImplementation::dnaMatchesRequired = 28 static
Definition at line 398 of file GCWManager.h.
Referenced by loadLuaConfig(), and processDNASample().
SortedVector<ManagedReference<BuildingObject* > > server::zone::managers::gcw::GCWManagerImplementation::gcwBaseList protected
Definition at line 360 of file GCWManager.h.
Referenced by addBase(), dropBase(), GCWManagerImplementation(), getBase(), hasBase(), isPlanetCapped(), and performGCWTasks().
int GCWManagerImplementation::gcwCheckTimer = 3600 static
Definition at line 386 of file GCWManager.h.
Referenced by loadLuaConfig(), performGCWTasks(), and start().
VectorMap<unsigned long long, Reference<Task*> > server::zone::managers::gcw::GCWManagerImplementation::gcwDestroyTasks protected
Definition at line 368 of file GCWManager.h.
Referenced by addDestroyTask(), dropDestroyTask(), GCWManagerImplementation(), getDestroyTask(), hasDestroyTask(), and performGCWTasks().
VectorMap<unsigned long long, Reference<Task*> > server::zone::managers::gcw::GCWManagerImplementation::gcwEndTasks protected
Definition at line 364 of file GCWManager.h.
Referenced by addEndTask(), dropEndTask(), GCWManagerImplementation(), getEndTask(), hasEndTask(), and performGCWTasks().
VectorMap<unsigned long long, Reference<Task*> > server::zone::managers::gcw::GCWManagerImplementation::gcwStartTasks protected
Definition at line 362 of file GCWManager.h.
Referenced by addStartTask(), dropStartTask(), GCWManagerImplementation(), getStartTask(), hasStartTask(), performGCWTasks(), and refreshExpiredVulnerability().
int server::zone::managers::gcw::GCWManagerImplementation::imperialBases private
Definition at line 381 of file GCWManager.h.
Referenced by GCWManagerImplementation(), getImperialBaseCount(), registerGCWBase(), setImperialBaseCount(), and unregisterGCWBase().
const int server::zone::managers::gcw::GCWManagerImplementation::IMPERIALHASH = 3679112276 static
Definition at line 346 of file GCWManager.h.
Referenced by getGCWDiscount(), getWinningFaction(), performGCWTasks(), registerGCWBase(), and unregisterGCWBase().
int server::zone::managers::gcw::GCWManagerImplementation::imperialScore private
Definition at line 383 of file GCWManager.h.
Referenced by GCWManagerImplementation(), getImperialScore(), and setImperialScore().
int GCWManagerImplementation::initialVulnerabilityDelay = 0 static
Definition at line 418 of file GCWManager.h.
Referenced by getInitialVulnerabilityDelay(), and loadLuaConfig().
int GCWManagerImplementation::maxBases = -1 static
Definition at line 402 of file GCWManager.h.
Referenced by isPlanetCapped(), and loadLuaConfig().
int GCWManagerImplementation::maxBasesPerPlayer = 3 static
Definition at line 410 of file GCWManager.h.
Referenced by canPlaceMoreBases(), and loadLuaConfig().
const int server::zone::managers::gcw::GCWManagerImplementation::NOTAFACTIONBASE = 0 static
Definition at line 350 of file GCWManager.h.
int GCWManagerImplementation::overtCooldown = 300 static
Definition at line 404 of file GCWManager.h.
Referenced by abortShutdownSequence(), and loadLuaConfig().
const int server::zone::managers::gcw::GCWManagerImplementation::PLAYERFACTIONBASE = 1 static
Definition at line 352 of file GCWManager.h.
Referenced by doBaseDestruction().
bool GCWManagerImplementation::racialPenaltyEnabled = true static
Definition at line 420 of file GCWManager.h.
Referenced by getGCWDiscount(), isRacialPenaltyEnabled(), and loadLuaConfig().
HashTable< int, float > GCWManagerImplementation::racialPenaltyMap static protected
Definition at line 374 of file GCWManager.h.
Referenced by addRacialPenalty(), and getRacialPenalty().
int GCWManagerImplementation::reactvationTimer = 300 static
Definition at line 406 of file GCWManager.h.
Referenced by abortShutdownSequence(), and loadLuaConfig().
int server::zone::managers::gcw::GCWManagerImplementation::rebelBases private
Definition at line 377 of file GCWManager.h.
Referenced by GCWManagerImplementation(), getRebelBaseCount(), registerGCWBase(), setRebelBaseCount(), and unregisterGCWBase().
const int server::zone::managers::gcw::GCWManagerImplementation::REBELHASH = 370444368 static
Definition at line 348 of file GCWManager.h.
Referenced by getWinningFaction(), performGCWTasks(), registerGCWBase(), and unregisterGCWBase().
int server::zone::managers::gcw::GCWManagerImplementation::rebelScore private
Definition at line 379 of file GCWManager.h.
Referenced by GCWManagerImplementation(), getRebelScore(), and setRebelScore().
int GCWManagerImplementation::resetTimer = 604800 static
Definition at line 392 of file GCWManager.h.
Referenced by loadLuaConfig(), and resetVulnerability().
int GCWManagerImplementation::sliceCooldown = 120 static
Definition at line 394 of file GCWManager.h.
Referenced by isTerminalDamaged(), loadLuaConfig(), and repairTerminal().
bool GCWManagerImplementation::spawnDefenses = true static
Definition at line 416 of file GCWManager.h.
Referenced by loadLuaConfig(), and shouldSpawnDefenses().
const int server::zone::managers::gcw::GCWManagerImplementation::STATICFACTIONBASE = 2 static
Definition at line 354 of file GCWManager.h.
Referenced by doBaseDestruction().
int GCWManagerImplementation::totalDNASamples = 10 static
Definition at line 396 of file GCWManager.h.
Referenced by loadLuaConfig(), and sendDNASampleMenu().
int GCWManagerImplementation::turretAutoFireTimeout = 120 static
Definition at line 408 of file GCWManager.h.
Referenced by loadLuaConfig().
int GCWManagerImplementation::vulnerabilityDuration = 7200 static
Definition at line 388 of file GCWManager.h.
Referenced by endVulnerability(), initializeBaseTimers(), loadLuaConfig(), refreshExpiredVulnerability(), and resetVulnerability().
int GCWManagerImplementation::vulnerabilityFrequency = 172800 static
Definition at line 390 of file GCWManager.h.
Referenced by endVulnerability(), initializeBaseTimers(), loadLuaConfig(), refreshExpiredVulnerability(), and resetVulnerability().
ManagedReference<Zone* > server::zone::managers::gcw::GCWManagerImplementation::zone private
Definition at line 357 of file GCWManager.h.
Referenced by addChildInstallationFromDeed(), broadcastBuilding(), canPlaceMoreBases(), checkVulnerabilityData(), GCWManagerImplementation(), generateTurretControlBoxTo(), notifyInstallationDestruction(), performDefenseDontation(), performGCWTasks(), readObjectMember(), removeDefense(), sendBaseDefenseStatus(), sendDNASampleMenu(), sendJamUplinkMenu(), sendPowerRegulatorControls(), sendRemoveDefenseConfirmation(), sendResetVerification(), sendSelectDeedToDonate(), sendTurretAttackListTo(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/gcw/GCWManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/gcw/GCWManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/gcw/GCWManagerImplementation.cpp