Core3: VendorDataComponent Class Reference
VendorDataComponent Class Reference
#include <VendorDataComponent.h>
Public Member Functions
VendorDataComponent ()
virtual ~VendorDataComponent ()
void initializeTransientMembers ()
void notifyObjectDestroyingFromDatabase ()
void sendVendorUpdateMail (bool isEmpty)
void sendVendorDestroyMail ()
void runVendorUpdate ()
void setOwnerId (uint64 id)
uint64 getOwnerId ()
bool isVendorData ()
void setInitialized (bool val)
void setVendorSearchEnabled (bool enabled)
void setDisabled (bool isDisabled)
void setRegistered (bool reg)
int getOwnershipRightsOf (CreatureObject *player)
bool isVendorOwner (CreatureObject *player)
bool isInitialized ()
bool isVendorSearchEnabled ()
bool isDisabled ()
bool isRegistered ()
void awardUseXP ()
bool isAdBarkingEnabled ()
void setAdBarking (bool value)
bool isEmpty ()
void setEmpty ()
int getMaint ()
bool isOnStrike ()
void setAdPhrase (const String &message)
void setAdMood (const String &mood)
void setAdAnimation (const String &animation)
bool hasBarkTarget (SceneObject *target)
void addBarkTarget (SceneObject *target)
bool canBark ()
void clearVendorBark (SceneObject *target)
float getMaintenanceRate ()
void payMaintanence ()
void withdrawMaintanence ()
void handlePayMaintanence (int value)
void handleWithdrawMaintanence (int value)
void performVendorBark (SceneObject *target)
Public Member Functions inherited from AuctionTerminalDataComponent
AuctionTerminalDataComponent ()
virtual ~AuctionTerminalDataComponent ()
void updateUID ()
String getUID ()
bool isAuctionTerminalData ()
Public Member Functions inherited from DataObjectComponent
DataObjectComponent ()
~DataObjectComponent ()
void setParent (SceneObject *object)
SceneObject * getParent ()
virtual bool isDiceData ()
virtual bool isCreatureHabitatData ()
virtual bool isBuildingData ()
virtual bool isDestructibleBuildingData ()
virtual bool isTurretData ()
virtual bool isDetectorData ()
virtual bool isGCWBaseData ()
virtual bool isSecurityTerminalData ()
virtual bool isMinefieldData ()
virtual bool isTurretControlTerminalData ()
virtual bool isDecoration ()
Static Public Attributes
static const int USEXPINTERVAL = 5
5 minutes
static const int VENDORCHECKINTERVAL = 60
static const int VENDORCHECKDELAY = 20
static const int FIRSTWARNING = 60 * 60 * 24 * 25
static const int SECONDWARNING = 60 * 60 * 24 * 50
static const int EMPTYDELETE = 60 * 60 * 24 * 14
static const int DELETEWARNING = 60 * 60 * 24 * 100
static const int BARKRANGE = 15
static const int BARKINTERVAL = 60 * 2
Protected Attributes
uint64 ownerId
Reference< Task * > vendorCheckTask
bool initialized
bool vendorSearchEnabled
bool disabled
bool registered
Time lastSuccessfulUpdate
int maintAmount
Time lastXpAward
int awardUsageXP
bool adBarking
Time emptyTimer
Time inactiveTimer
bool mail1Sent
bool mail2Sent
Vector< uint64 > vendorBarks
uint64 lastBark
String barkMessage
String barkMood
String barkAnimation
float originalDirection
Protected Attributes inherited from AuctionTerminalDataComponent
ManagedReference
< AuctionManager * > auctionManager
String uid
Protected Attributes inherited from DataObjectComponent
ManagedWeakReference
< SceneObject * > parent
Private Member Functions
void addSerializableVariables ()
Detailed Description
Definition at line 18 of file VendorDataComponent.h.
Constructor & Destructor Documentation
VendorDataComponent::VendorDataComponent ()
Definition at line 22 of file VendorDataComponent.cpp.
References adBarking, addSerializableVariables(), AuctionTerminalDataComponent::auctionManager, awardUsageXP, barkMessage, disabled, initialized, mail1Sent, mail2Sent, maintAmount, originalDirection, ownerId, registered, and vendorSearchEnabled.
virtual VendorDataComponent::~VendorDataComponent () inline virtual
Definition at line 72 of file VendorDataComponent.h.
References vendorCheckTask.
Member Function Documentation
void VendorDataComponent::addBarkTarget (SceneObject * target) inline
Definition at line 214 of file VendorDataComponent.h.
References server::zone::objects::scene::SceneObject::getObjectID(), and vendorBarks.
Referenced by VendorZoneComponent::notifyPositionUpdate(), and performVendorBark().
void VendorDataComponent::addSerializableVariables () private
Definition at line 39 of file VendorDataComponent.cpp.
References adBarking, awardUsageXP, barkAnimation, barkMessage, barkMood, disabled, emptyTimer, initialized, lastSuccessfulUpdate, lastXpAward, mail1Sent, mail2Sent, maintAmount, originalDirection, ownerId, registered, and vendorSearchEnabled.
Referenced by VendorDataComponent().
void VendorDataComponent::awardUseXP () inline
Definition at line 153 of file VendorDataComponent.h.
References awardUsageXP, lastXpAward, and USEXPINTERVAL.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::getData().
bool VendorDataComponent::canBark () inline
Definition at line 218 of file VendorDataComponent.h.
References BARKINTERVAL, and lastBark.
Referenced by VendorZoneComponent::notifyPositionUpdate().
void VendorDataComponent::clearVendorBark (SceneObject * target) inline
Definition at line 222 of file VendorDataComponent.h.
References server::zone::objects::scene::SceneObject::getObjectID(), and vendorBarks.
int VendorDataComponent::getMaint () inline
Definition at line 190 of file VendorDataComponent.h.
References maintAmount.
Referenced by server::zone::managers::vendor::VendorManager::handleDisplayStatus().
float VendorDataComponent::getMaintenanceRate ()
Definition at line 191 of file VendorDataComponent.cpp.
References getOwnerId(), DataObjectComponent::parent, and registered.
Referenced by server::zone::managers::vendor::VendorManager::handleDisplayStatus(), and runVendorUpdate().
uint64 VendorDataComponent::getOwnerId () inline
Definition at line 91 of file VendorDataComponent.h.
References ownerId.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), VendorContainerComponent::checkContainerPermission(), server::zone::managers::auction::AuctionManagerImplementation::checkSaleItem(), server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), GiveItemCommand::doQueueCommand(), VendorMenuComponent::fillObjectMenuResponse(), getMaintenanceRate(), VendorMenuComponent::handleObjectMenuSelect(), handlePayMaintanence(), handleWithdrawMaintanence(), payMaintanence(), server::zone::managers::vendor::VendorManager::promptDestroyVendor(), runVendorUpdate(), server::zone::managers::auction::AuctionsMapImplementation::sendVendorUpdateMail(), and withdrawMaintanence().
int VendorDataComponent::getOwnershipRightsOf (CreatureObject * player) inline
Definition at line 121 of file VendorDataComponent.h.
References server::zone::objects::scene::SceneObject::getObjectID(), initialized, and ownerId.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), and IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage().
void VendorDataComponent::handlePayMaintanence (int value)
Definition at line 230 of file VendorDataComponent.cpp.
References getOwnerId(), maintAmount, DataObjectComponent::parent, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::chat::StringIdChatParameter::setDI().
Referenced by VendorMaintSuiCallback::run().
void VendorDataComponent::handleWithdrawMaintanence (int value)
Definition at line 283 of file VendorDataComponent.cpp.
References getOwnerId(), maintAmount, DataObjectComponent::parent, and server::chat::StringIdChatParameter::setDI().
Referenced by VendorMaintSuiCallback::run().
bool VendorDataComponent::hasBarkTarget (SceneObject * target) inline
Definition at line 210 of file VendorDataComponent.h.
References server::zone::objects::scene::SceneObject::getObjectID(), and vendorBarks.
Referenced by VendorZoneComponent::notifyPositionUpdate().
void VendorDataComponent::initializeTransientMembers () virtual
Schedule initial task
Reimplemented from AuctionTerminalDataComponent.
Definition at line 59 of file VendorDataComponent.cpp.
References AuctionTerminalDataComponent::initializeTransientMembers(), isInitialized(), isRegistered(), lastBark, originalDirection, DataObjectComponent::parent, VENDORCHECKDELAY, VENDORCHECKINTERVAL, and vendorCheckTask.
bool VendorDataComponent::isAdBarkingEnabled () inline
Definition at line 160 of file VendorDataComponent.h.
References adBarking.
Referenced by VendorMenuComponent::fillObjectMenuResponse(), VendorMenuComponent::handleObjectMenuSelect(), and VendorZoneComponent::notifyPositionUpdate().
bool VendorDataComponent::isDisabled () inline
Definition at line 145 of file VendorDataComponent.h.
References disabled.
Referenced by setDisabled().
bool VendorDataComponent::isEmpty () inline
Definition at line 169 of file VendorDataComponent.h.
References AuctionTerminalDataComponent::auctionManager, and DataObjectComponent::parent.
Referenced by runVendorUpdate().
bool VendorDataComponent::isInitialized () inline
Definition at line 137 of file VendorDataComponent.h.
References initialized.
Referenced by VendorContainerComponent::checkContainerPermission(), VendorMenuComponent::fillObjectMenuResponse(), VendorMenuComponent::handleObjectMenuSelect(), and initializeTransientMembers().
bool VendorDataComponent::isOnStrike () inline
Definition at line 194 of file VendorDataComponent.h.
References maintAmount.
Referenced by IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage(), performVendorBark(), and runVendorUpdate().
bool VendorDataComponent::isRegistered () inline
Definition at line 149 of file VendorDataComponent.h.
References registered.
Referenced by server::zone::managers::vendor::VendorManager::destroyVendor(), VendorMenuComponent::fillObjectMenuResponse(), VendorMenuComponent::handleObjectMenuSelect(), server::zone::managers::vendor::VendorManager::handleRenameVendor(), and initializeTransientMembers().
bool VendorDataComponent::isVendorData () inline virtual
Reimplemented from DataObjectComponent.
Definition at line 95 of file VendorDataComponent.h.
bool VendorDataComponent::isVendorOwner (CreatureObject * player) inline
Definition at line 133 of file VendorDataComponent.h.
References server::zone::objects::scene::SceneObject::getObjectID(), and ownerId.
bool VendorDataComponent::isVendorSearchEnabled () inline
Definition at line 141 of file VendorDataComponent.h.
References vendorSearchEnabled.
Referenced by server::zone::managers::auction::AuctionsMapImplementation::addVendorItem(), VendorMenuComponent::fillObjectMenuResponse(), server::zone::managers::vendor::VendorManager::handleDisplayStatus(), and VendorMenuComponent::handleObjectMenuSelect().
void VendorDataComponent::notifyObjectDestroyingFromDatabase () virtual
Reimplemented from DataObjectComponent.
Definition at line 82 of file VendorDataComponent.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), ownerId, and DataObjectComponent::parent.
void VendorDataComponent::payMaintanence ()
Definition at line 212 of file VendorDataComponent.cpp.
References getOwnerId(), DataObjectComponent::parent, and SuiWindowType::STRUCTURE_VENDOR_PAY.
Referenced by VendorMenuComponent::handleObjectMenuSelect().
void VendorDataComponent::performVendorBark (SceneObject * target)
Definition at line 318 of file VendorDataComponent.cpp.
References addBarkTarget(), barkAnimation, barkMessage, barkMood, Races::getMoodID(), server::zone::objects::scene::SceneObject::getObjectID(), isOnStrike(), server::zone::objects::scene::SceneObject::isPlayerCreature(), lastBark, originalDirection, DataObjectComponent::parent, server::zone::objects::scene::variables::StringId::setStringId(), and server::chat::StringIdChatParameter::setTT().
Referenced by VendorZoneComponent::notifyPositionUpdate().
void VendorDataComponent::runVendorUpdate ()
parent salaries
Award hourly XP
Definition at line 94 of file VendorDataComponent.cpp.
References awardUsageXP, DELETEWARNING, EMPTYDELETE, emptyTimer, FIRSTWARNING, getMaintenanceRate(), getOwnerId(), inactiveTimer, isEmpty(), isOnStrike(), lastSuccessfulUpdate, mail1Sent, mail2Sent, maintAmount, DataObjectComponent::parent, SECONDWARNING, server::chat::StringIdChatParameter::setTO(), vendorBarks, VENDORCHECKINTERVAL, and vendorCheckTask.
Referenced by VendorMenuComponent::handleObjectMenuSelect(), and server::zone::objects::auction::events::UpdateVendorTask::run().
void VendorDataComponent::sendVendorDestroyMail ()
void VendorDataComponent::sendVendorUpdateMail (bool isEmpty)
void VendorDataComponent::setAdAnimation (const String & animation) inline
Definition at line 206 of file VendorDataComponent.h.
References barkAnimation.
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::completeSession().
void VendorDataComponent::setAdBarking (bool value) inline
Definition at line 164 of file VendorDataComponent.h.
References adBarking, and vendorBarks.
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::completeSession(), and VendorMenuComponent::handleObjectMenuSelect().
void VendorDataComponent::setAdMood (const String & mood) inline
Definition at line 202 of file VendorDataComponent.h.
References barkMood.
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::completeSession().
void VendorDataComponent::setAdPhrase (const String & message) inline
Definition at line 198 of file VendorDataComponent.h.
References barkMessage.
Referenced by server::zone::objects::player::sessions::vendor::VendorAdBarkingSessionImplementation::completeSession().
void VendorDataComponent::setDisabled (bool isDisabled) inline
Definition at line 107 of file VendorDataComponent.h.
References disabled, and isDisabled().
void VendorDataComponent::setEmpty () inline
Definition at line 183 of file VendorDataComponent.h.
References emptyTimer, mail1Sent, and mail2Sent.
Referenced by VendorMenuComponent::handleObjectMenuSelect(), and server::zone::managers::auction::AuctionsMapImplementation::sendVendorUpdateMail().
void VendorDataComponent::setInitialized (bool val) inline
Definition at line 99 of file VendorDataComponent.h.
References initialized, originalDirection, DataObjectComponent::parent, and AuctionTerminalDataComponent::updateUID().
Referenced by VendorMenuComponent::handleObjectMenuSelect().
void VendorDataComponent::setOwnerId (uint64 id) inline
Definition at line 87 of file VendorDataComponent.h.
References ownerId.
Referenced by server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::createVendor().
void VendorDataComponent::setRegistered (bool reg) inline
This is just a precaution in case somehow items get lost and this would link up a missing auction list unless it was totally gone
Definition at line 111 of file VendorDataComponent.h.
References registered, and AuctionTerminalDataComponent::updateUID().
Referenced by server::zone::managers::vendor::VendorManager::handleRegisterVendorCallback(), server::zone::managers::vendor::VendorManager::handleRenameVendor(), and server::zone::managers::vendor::VendorManager::handleUnregisterVendor().
void VendorDataComponent::setVendorSearchEnabled (bool enabled)
Definition at line 308 of file VendorDataComponent.cpp.
References AuctionTerminalDataComponent::auctionManager, DataObjectComponent::parent, and vendorSearchEnabled.
Referenced by VendorMenuComponent::handleObjectMenuSelect().
void VendorDataComponent::withdrawMaintanence ()
Definition at line 265 of file VendorDataComponent.cpp.
References getOwnerId(), DataObjectComponent::parent, and SuiWindowType::STRUCTURE_VENDOR_WITHDRAW.
Referenced by VendorMenuComponent::handleObjectMenuSelect().
Member Data Documentation
bool VendorDataComponent::adBarking protected
Definition at line 36 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), isAdBarkingEnabled(), setAdBarking(), and VendorDataComponent().
int VendorDataComponent::awardUsageXP protected
Definition at line 34 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), awardUseXP(), runVendorUpdate(), and VendorDataComponent().
String VendorDataComponent::barkAnimation protected
Definition at line 48 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), performVendorBark(), and setAdAnimation().
const int VendorDataComponent::BARKINTERVAL = 60 * 2 static
Definition at line 67 of file VendorDataComponent.h.
Referenced by canBark().
String VendorDataComponent::barkMessage protected
Definition at line 46 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), performVendorBark(), setAdPhrase(), and VendorDataComponent().
String VendorDataComponent::barkMood protected
Definition at line 47 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), performVendorBark(), and setAdMood().
const int VendorDataComponent::BARKRANGE = 15 static
Definition at line 66 of file VendorDataComponent.h.
Referenced by VendorZoneComponent::notifyPositionUpdate().
const int VendorDataComponent::DELETEWARNING = 60 * 60 * 24 * 100 static
Definition at line 64 of file VendorDataComponent.h.
Referenced by runVendorUpdate().
bool VendorDataComponent::disabled protected
Definition at line 26 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), isDisabled(), setDisabled(), and VendorDataComponent().
const int VendorDataComponent::EMPTYDELETE = 60 * 60 * 24 * 14 static
Definition at line 62 of file VendorDataComponent.h.
Referenced by runVendorUpdate().
Time VendorDataComponent::emptyTimer protected
Definition at line 38 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), runVendorUpdate(), and setEmpty().
const int VendorDataComponent::FIRSTWARNING = 60 * 60 * 24 * 25 static
Definition at line 60 of file VendorDataComponent.h.
Referenced by runVendorUpdate().
Time VendorDataComponent::inactiveTimer protected
Definition at line 39 of file VendorDataComponent.h.
Referenced by runVendorUpdate().
bool VendorDataComponent::initialized protected
Definition at line 24 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), getOwnershipRightsOf(), isInitialized(), setInitialized(), and VendorDataComponent().
uint64 VendorDataComponent::lastBark protected
Definition at line 45 of file VendorDataComponent.h.
Referenced by canBark(), initializeTransientMembers(), and performVendorBark().
Time VendorDataComponent::lastSuccessfulUpdate protected
Definition at line 29 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), and runVendorUpdate().
Time VendorDataComponent::lastXpAward protected
Definition at line 33 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), and awardUseXP().
bool VendorDataComponent::mail1Sent protected
Definition at line 41 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), runVendorUpdate(), setEmpty(), and VendorDataComponent().
bool VendorDataComponent::mail2Sent protected
Definition at line 42 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), runVendorUpdate(), setEmpty(), and VendorDataComponent().
int VendorDataComponent::maintAmount protected
Definition at line 31 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), getMaint(), handlePayMaintanence(), handleWithdrawMaintanence(), isOnStrike(), runVendorUpdate(), and VendorDataComponent().
float VendorDataComponent::originalDirection protected
Definition at line 50 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), initializeTransientMembers(), performVendorBark(), setInitialized(), and VendorDataComponent().
uint64 VendorDataComponent::ownerId protected
Definition at line 20 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), getOwnerId(), getOwnershipRightsOf(), isVendorOwner(), notifyObjectDestroyingFromDatabase(), setOwnerId(), and VendorDataComponent().
bool VendorDataComponent::registered protected
Definition at line 27 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), getMaintenanceRate(), isRegistered(), setRegistered(), and VendorDataComponent().
const int VendorDataComponent::SECONDWARNING = 60 * 60 * 24 * 50 static
Definition at line 61 of file VendorDataComponent.h.
Referenced by runVendorUpdate().
const int VendorDataComponent::USEXPINTERVAL = 5 static
5 minutes
Definition at line 54 of file VendorDataComponent.h.
Referenced by awardUseXP().
Vector<uint64> VendorDataComponent::vendorBarks protected
Definition at line 44 of file VendorDataComponent.h.
Referenced by addBarkTarget(), clearVendorBark(), hasBarkTarget(), runVendorUpdate(), and setAdBarking().
const int VendorDataComponent::VENDORCHECKDELAY = 20 static
Definition at line 58 of file VendorDataComponent.h.
Referenced by initializeTransientMembers().
const int VendorDataComponent::VENDORCHECKINTERVAL = 60 static
Definition at line 57 of file VendorDataComponent.h.
Referenced by initializeTransientMembers(), and runVendorUpdate().
Reference<Task*> VendorDataComponent::vendorCheckTask protected
Definition at line 22 of file VendorDataComponent.h.
Referenced by initializeTransientMembers(), runVendorUpdate(), and ~VendorDataComponent().
bool VendorDataComponent::vendorSearchEnabled protected
Definition at line 25 of file VendorDataComponent.h.
Referenced by addSerializableVariables(), isVendorSearchEnabled(), setVendorSearchEnabled(), and VendorDataComponent().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/vendor/VendorDataComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/vendor/VendorDataComponent.cpp