Core3: DataTransformCallback Class Reference
DataTransformCallback Class Reference
#include <DataTransform.h>
Public Member Functions
DataTransformCallback (ObjectControllerMessageCallback *objectControllerCallback)
void parse (Message *message)
void bounceBack (SceneObject *object, ValidatedPosition &pos)
void run ()
void updatePosition (CreatureObject *object)
Public Member Functions inherited from server::zone::packets::MessageCallback
MessageCallback (ZoneClientSession *client, ZoneProcessServer *server)
virtual ~MessageCallback ()
int getTaskQueue ()
bool parseMessage (Message *packet)
ZoneClientSession * getClient ()
ZoneProcessServer * getServer ()
Private Attributes
uint32 movementStamp
uint32 movementCounter
float directionX
float directionY
float directionZ
float directionW
float positionX
float positionZ
float positionY
float parsedSpeed
ObjectControllerMessageCallback * objectControllerMain
Additional Inherited Members
Protected Attributes inherited from server::zone::packets::MessageCallback
Reference< ZoneClientSession * > client
ManagedReference
< ZoneProcessServer * > server
int taskqueue
Detailed Description
Definition at line 79 of file DataTransform.h.
Constructor & Destructor Documentation
DataTransformCallback::DataTransformCallback (ObjectControllerMessageCallback * objectControllerCallback) inline
Definition at line 91 of file DataTransform.h.
References server::zone::packets::MessageCallback::client, server::zone::objects::scene::SceneObject::getLocalZone(), server::zone::Zone::getZoneName(), objectControllerMain, and server::zone::packets::MessageCallback::taskqueue.
Member Function Documentation
void DataTransformCallback::bounceBack (SceneObject * object, ValidatedPosition & pos) inline
Definition at line 136 of file DataTransform.h.
References ValidatedPosition::getParent(), and ValidatedPosition::getPosition().
Referenced by updatePosition().
void DataTransformCallback::parse (Message * message) inline virtual
Implements server::zone::packets::MessageCallback.
Definition at line 116 of file DataTransform.h.
References directionW, directionX, directionY, directionZ, movementCounter, movementStamp, parsedSpeed, positionX, positionY, and positionZ.
void DataTransformCallback::run () inline
Definition at line 143 of file DataTransform.h.
References server::zone::packets::MessageCallback::client, CreaturePosture::DRIVINGVEHICLE, CreaturePosture::PRONE, CreaturePosture::RIDINGCREATURE, CreaturePosture::SKILLANIMATING, updatePosition(), and CreaturePosture::UPRIGHT.
void DataTransformCallback::updatePosition (CreatureObject * object) inline
Definition at line 168 of file DataTransform.h.
References bounceBack(), directionW, directionX, directionY, directionZ, server::zone::objects::scene::SceneObject::error(), server::zone::objects::scene::SceneObject::getContainerVolumeLimit(), server::zone::objects::scene::SceneObject::getCountableObjectsRecursive(), ObjectControllerMessageCallback::getPriority(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::creature::CreatureObject::getSwimHeight(), CollisionManager::getWorldFloorCollisions(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isFrozen(), server::zone::objects::player::PlayerObject::isPrivileged(), server::zone::objects::player::PlayerObject::isTeleporting(), movementCounter, movementStamp, objectControllerMain, parsedSpeed, positionX, positionY, positionZ, server::zone::packets::MessageCallback::server, server::zone::objects::player::PlayerObject::setClientLastMovementStamp(), ValidatedPosition::update(), and server::zone::objects::scene::SceneObject::updateZone().
Referenced by run().
Member Data Documentation
float DataTransformCallback::directionW private
Definition at line 83 of file DataTransform.h.
Referenced by parse(), and updatePosition().
float DataTransformCallback::directionX private
Definition at line 83 of file DataTransform.h.
Referenced by parse(), and updatePosition().
float DataTransformCallback::directionY private
Definition at line 83 of file DataTransform.h.
Referenced by parse(), and updatePosition().
float DataTransformCallback::directionZ private
Definition at line 83 of file DataTransform.h.
Referenced by parse(), and updatePosition().
uint32 DataTransformCallback::movementCounter private
Definition at line 81 of file DataTransform.h.
Referenced by parse(), and updatePosition().
uint32 DataTransformCallback::movementStamp private
Definition at line 80 of file DataTransform.h.
Referenced by parse(), and updatePosition().
ObjectControllerMessageCallback* DataTransformCallback::objectControllerMain private
Definition at line 87 of file DataTransform.h.
Referenced by DataTransformCallback(), and updatePosition().
float DataTransformCallback::parsedSpeed private
Definition at line 85 of file DataTransform.h.
Referenced by parse(), and updatePosition().
float DataTransformCallback::positionX private
Definition at line 84 of file DataTransform.h.
Referenced by parse(), and updatePosition().
float DataTransformCallback::positionY private
Definition at line 84 of file DataTransform.h.
Referenced by parse(), and updatePosition().
float DataTransformCallback::positionZ private
Definition at line 84 of file DataTransform.h.
Referenced by parse(), and updatePosition().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/object/DataTransform.h