Core3: ManufactureSchematicObjectDeltaMessage7 Class Reference
ManufactureSchematicObjectDeltaMessage7 Class Reference
#include <ManufactureSchematicObjectDeltaMessage7.h>
Public Member Functions
ManufactureSchematicObjectDeltaMessage7 (SceneObject *schematic)
void updateForAssembly (ManufactureSchematic *manufactureSchematic, float failureRate)
void updateCustomizationOptions (VectorMap< String, Reference< CustomizationVariable * > > *vars, int custpoints)
void initialAssemblyUpdate (ManufactureSchematic *manufactureSchematic)
void update9 (ManufactureSchematic *manufactureSchematic, bool initial)
void update0A (ManufactureSchematic *manufactureSchematic)
void update0B (ManufactureSchematic *manufactureSchematic)
void update0C (ManufactureSchematic *manufactureSchematic)
void update0D (VectorMap< String, Reference< CustomizationVariable * > > *vars)
void update0E (VectorMap< String, Reference< CustomizationVariable * > > *vars)
void update0F (VectorMap< String, Reference< CustomizationVariable * > > *vars)
void update10 (VectorMap< String, Reference< CustomizationVariable * > > *vars, int custpoints)
void update11 ()
void update12 (float failureRate)
void update13 (ManufactureSchematic *manufactureSchematic)
void update14 ()
Public Member Functions inherited from DeltaMessage
DeltaMessage (uint64 oid, uint32 name, uint8 type)
uint32 generateRandomObjectCRC ()
void startUpdate (uint16 type)
void addByteUpdate (uint16 type, uint8 value)
void addShortUpdate (uint16 type, uint16 value)
void addIntUpdate (uint16 type, uint32 value)
void addLongUpdate (uint16 type, uint64 value)
void addFloatUpdate (uint16 type, float value)
void addAsciiUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const UnicodeString &val)
void startList (uint32 cnt, uint32 updcnt)
void addListIntElement (uint16 index, uint32 value)
void addListFloatElement (uint16 index, float value)
void addListLongElement (uint16 index, uint64 value)
void addListAsciiElement (const String &value)
void removeListIntElement (uint16 index, uint32 value)
void removeListFloatElement (uint16 index, float value)
void removeListLongElement (uint16 index, uint64 value)
void removeListLongElement (uint16 index)
void removeListAsciiElement (const String &value)
void close ()
Detailed Description
Definition at line 51 of file ManufactureSchematicObjectDeltaMessage7.h.
Constructor & Destructor Documentation
ManufactureSchematicObjectDeltaMessage7::ManufactureSchematicObjectDeltaMessage7 (SceneObject * schematic) inline
Definition at line 53 of file ManufactureSchematicObjectDeltaMessage7.h.
Member Function Documentation
void ManufactureSchematicObjectDeltaMessage7::initialAssemblyUpdate (ManufactureSchematic * manufactureSchematic) inline
Definition at line 78 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::addListFloatElement(), DeltaMessage::startList(), and DeltaMessage::startUpdate().
Referenced by updateForAssembly().
void ManufactureSchematicObjectDeltaMessage7::update0A (ManufactureSchematic * manufactureSchematic) inline
Definition at line 175 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::removeListFloatElement(), DeltaMessage::startList(), and DeltaMessage::startUpdate().
void ManufactureSchematicObjectDeltaMessage7::update0B (ManufactureSchematic * manufactureSchematic) inline
Definition at line 190 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::removeListFloatElement(), DeltaMessage::startList(), and DeltaMessage::startUpdate().
Referenced by updateForAssembly().
void ManufactureSchematicObjectDeltaMessage7::update0C (ManufactureSchematic * manufactureSchematic) inline
Definition at line 205 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::removeListFloatElement(), DeltaMessage::startList(), and DeltaMessage::startUpdate().
Referenced by updateForAssembly().
void ManufactureSchematicObjectDeltaMessage7::update0D (VectorMap< String, Reference< CustomizationVariable * > > * vars) inline
Definition at line 226 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::startList(), and DeltaMessage::startUpdate().
Referenced by updateCustomizationOptions().
void ManufactureSchematicObjectDeltaMessage7::update0E (VectorMap< String, Reference< CustomizationVariable * > > * vars) inline
Definition at line 245 of file ManufactureSchematicObjectDeltaMessage7.h.
References RangedIntCustomizationVariable::getDefaultValue(), DeltaMessage::startList(), and DeltaMessage::startUpdate().
Referenced by updateCustomizationOptions().
void ManufactureSchematicObjectDeltaMessage7::update0F (VectorMap< String, Reference< CustomizationVariable * > > * vars) inline
Definition at line 263 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::startList(), and DeltaMessage::startUpdate().
Referenced by updateCustomizationOptions().
void ManufactureSchematicObjectDeltaMessage7::update10 (VectorMap< String, Reference< CustomizationVariable * > > * vars, int custpoints) inline
Definition at line 277 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::startList(), and DeltaMessage::startUpdate().
Referenced by updateCustomizationOptions().
void ManufactureSchematicObjectDeltaMessage7::update11 () inline
Definition at line 290 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::startUpdate().
Referenced by updateCustomizationOptions().
void ManufactureSchematicObjectDeltaMessage7::update12 (float failureRate) inline
Definition at line 296 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::startUpdate().
Referenced by updateForAssembly().
void ManufactureSchematicObjectDeltaMessage7::update13 (ManufactureSchematic * manufactureSchematic) inline
Template List
The first template is the
Definition at line 301 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::startList(), and DeltaMessage::startUpdate().
Referenced by updateForAssembly().
void ManufactureSchematicObjectDeltaMessage7::update14 () inline
Definition at line 322 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::startUpdate().
void ManufactureSchematicObjectDeltaMessage7::update9 (ManufactureSchematic * manufactureSchematic, bool initial) inline
Definition at line 140 of file ManufactureSchematicObjectDeltaMessage7.h.
References DeltaMessage::removeListFloatElement(), DeltaMessage::startList(), and DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::experiment(), and updateForAssembly().
void ManufactureSchematicObjectDeltaMessage7::updateCustomizationOptions (VectorMap< String, Reference< CustomizationVariable * > > * vars, int custpoints) inline
Definition at line 68 of file ManufactureSchematicObjectDeltaMessage7.h.
References update0D(), update0E(), update0F(), update10(), and update11().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::initialAssembly().
void ManufactureSchematicObjectDeltaMessage7::updateForAssembly (ManufactureSchematic * manufactureSchematic, float failureRate) inline
Definition at line 58 of file ManufactureSchematicObjectDeltaMessage7.h.
References initialAssemblyUpdate(), update0B(), update0C(), update12(), update13(), and update9().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::initialAssembly().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/manufactureschematic/ManufactureSchematicObjectDeltaMessage7.h