Core3: server::zone::objects::scene::variables::StringId Class Reference
server::zone::objects::scene::variables::StringId Class Reference
#include <StringId.h>
Public Member Functions
StringId ()
StringId (const StringId &id)
StringId (const char *cstr)
StringId (const String &fullPath)
StringId (const String &fil, const String &stringId)
StringId & operator= (const StringId &id)
bool operator== (const StringId &id) const
int compareTo (const StringId &id) const
void clear ()
void getFullPath (String &str) const
String getFullPath () const
String & getFile ()
String & getStringID ()
uint32 size () const
bool isEmpty () const
void setStringId (const String &fullPath)
void setStringId (const String &file, const String &id)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
Protected Attributes
String file
int filler
String stringID
Detailed Description
Definition at line 57 of file StringId.h.
Constructor & Destructor Documentation
StringId::StringId ()
Definition at line 47 of file StringId.cpp.
References file, filler, and stringID.
StringId::StringId (const StringId & id)
Definition at line 53 of file StringId.cpp.
References file, filler, and stringID.
StringId::StringId (const char * cstr)
Definition at line 64 of file StringId.cpp.
References filler, and setStringId().
StringId::StringId (const String & fullPath)
Definition at line 59 of file StringId.cpp.
References filler, and setStringId().
StringId::StringId (const String & fil, const String & stringId)
Definition at line 69 of file StringId.cpp.
References file, filler, and stringID.
Member Function Documentation
void StringId::clear ()
Definition at line 76 of file StringId.cpp.
References file, filler, and stringID.
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsorshipRequest().
int server::zone::objects::scene::variables::StringId::compareTo (const StringId & id) const inline
Definition at line 92 of file StringId.h.
References getFullPath().
String& server::zone::objects::scene::variables::StringId::getFile () inline
Definition at line 106 of file StringId.h.
References file.
Referenced by BaseLineMessage::insertStringId(), DraftSlot::insertToMessage(), MissionObjectMessage3::MissionObjectMessage3(), MissionObjectDeltaMessage3::updateDescriptionStf(), and MissionObjectDeltaMessage3::updateTitleStf().
void server::zone::objects::scene::variables::StringId::getFullPath (String & str) const inline
Definition at line 98 of file StringId.h.
References file, and stringID.
Referenced by server::zone::managers::minigames::GamblingManagerImplementation::bet(), server::zone::managers::creature::DnaManager::generateSample(), server::zone::templates::mobile::ConversationOption::getDisplayedName(), server::zone::objects::scene::SceneObjectImplementation::getDisplayedName(), server::zone::objects::region::CityRegionImplementation::getRegionName(), and server::zone::managers::minigames::FishingManagerImplementation::sendReward().
String server::zone::objects::scene::variables::StringId::getFullPath () const inline
Definition at line 102 of file StringId.h.
References file, and stringID.
Referenced by compareTo().
String& server::zone::objects::scene::variables::StringId::getStringID () inline
Definition at line 110 of file StringId.h.
References stringID.
Referenced by BaseLineMessage::insertStringId(), DraftSlot::insertToMessage(), MissionObjectMessage3::MissionObjectMessage3(), MissionObjectDeltaMessage3::updateDescriptionStf(), and MissionObjectDeltaMessage3::updateTitleStf().
bool server::zone::objects::scene::variables::StringId::isEmpty () const inline
Definition at line 118 of file StringId.h.
References file.
Referenced by server::zone::objects::creature::buffs::BuffImplementation::activate(), and server::zone::objects::creature::buffs::BuffImplementation::deactivate().
StringId& server::zone::objects::scene::variables::StringId::operator= (const StringId & id) inline
Definition at line 70 of file StringId.h.
References file, filler, and stringID.
Referenced by server::chat::StringIdChatParameter::operator=().
bool server::zone::objects::scene::variables::StringId::operator== (const StringId & id) const inline
Definition at line 81 of file StringId.h.
References file, and stringID.
bool server::zone::objects::scene::variables::StringId::parseFromBinaryStream (ObjectInputStream * stream) inline
Definition at line 139 of file StringId.h.
References file, filler, and stringID.
void StringId::setStringId (const String & fullPath)
Definition at line 82 of file StringId.cpp.
References file, and stringID.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::abortShutdownSequence(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsorshipRequest(), server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer(), server::zone::objects::player::sessions::FindSessionImplementation::addWaypoint(), server::zone::managers::player::PlayerManagerImplementation::awardBadge(), server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::createSellJunkLootSelection(), server::zone::objects::player::PlayerObjectImplementation::decreaseFactionStanding(), BandFlourishCommand::doBandFlourish(), InsureCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), TransferstructureCommand::doTransferStructure(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceDamage(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceEffectiveness(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceEncumbrance(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceSpeed(), server::zone::objects::player::PlayerObjectImplementation::increaseFactionStanding(), GroupManager::inviteToGroup(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), server::zone::managers::player::PlayerManagerImplementation::killPlayer(), server::zone::managers::guild::GuildManagerImplementation::leaveGuild(), server::zone::objects::scene::SceneObjectImplementation::loadTemplateData(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield(), server::zone::managers::gcw::GCWManagerImplementation::performDonateTurret(), VendorDataComponent::performVendorBark(), CityDecorationTask::placeDecoration(), server::zone::templates::mobile::ConversationScreen::readObject(), GuildSponsorVerifySuiCallback::run(), InsuranceAllConfirmSuiCallback::run(), InsuranceMenuSuiCallback::run(), CloningStoreSuiCallback::run(), JunkDealerSellListSuiCallback::run(), InsertPowerSuiCallback::run(), InstallMissionTerminalSuiCallback::run(), RecruitSkillTrainerSuiCallback::run(), TurretControlSuiCallback::run(), TaxPayMailTask::run(), MeditateTask::run(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationStartTo(), server::zone::templates::mobile::ConversationScreen::setDialogText(), server::zone::managers::guild::GuildManagerImplementation::setMemberTitle(), server::zone::objects::mission::MissionObjectImplementation::setMissionDescription(), server::zone::objects::mission::MissionObjectImplementation::setMissionTitle(), DraftSlot::setStringId(), server::zone::managers::guild::GuildManagerImplementation::sponsorPlayer(), server::zone::objects::installation::factory::FactoryObjectImplementation::stopFactory(), StringId(), server::zone::managers::city::CityManagerImplementation::updateCityVoting(), and server::zone::objects::mission::DeliverMissionObjectiveImplementation::updateMissionStatus().
void server::zone::objects::scene::variables::StringId::setStringId (const String & file, const String & id) inline
Definition at line 128 of file StringId.h.
References file, and stringID.
uint32 server::zone::objects::scene::variables::StringId::size () const inline
Definition at line 114 of file StringId.h.
References file, and stringID.
bool server::zone::objects::scene::variables::StringId::toBinaryStream (ObjectOutputStream * stream) inline
Definition at line 133 of file StringId.h.
References file, filler, and stringID.
Member Data Documentation
String server::zone::objects::scene::variables::StringId::file protected
Definition at line 59 of file StringId.h.
Referenced by server::chat::StringIdChatParameter::addToPacketStream(), clear(), getFile(), getFullPath(), isEmpty(), operator=(), operator==(), parseFromBinaryStream(), setStringId(), size(), StringId(), and toBinaryStream().
int server::zone::objects::scene::variables::StringId::filler protected
Definition at line 60 of file StringId.h.
Referenced by clear(), operator=(), parseFromBinaryStream(), StringId(), and toBinaryStream().
String server::zone::objects::scene::variables::StringId::stringID protected
Definition at line 61 of file StringId.h.
Referenced by server::chat::StringIdChatParameter::addToPacketStream(), clear(), getFullPath(), getStringID(), operator=(), operator==(), parseFromBinaryStream(), setStringId(), size(), StringId(), and toBinaryStream().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/StringId.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/StringId.cpp