Core3: ResourceSlot Class Reference
ResourceSlot Class Reference
#include <ResourceSlot.h>
Public Member Functions
ResourceSlot ()
ResourceSlot (const ResourceSlot &slot)
~ResourceSlot ()
Object * clone ()
bool add (CreatureObject *player, SceneObject *satchel, ManagedReference< TangibleObject * > tano)
bool returnToParents (CreatureObject *player)
int getSlotQuantity ()
bool isFull ()
bool isEmpty ()
bool isResourceSlot ()
ResourceSpawn * getCurrentSpawn ()
SceneObject * getFactoryIngredient ()
Vector< uint64 > getOIDVector ()
Vector< int > getQuantityVector ()
Public Member Functions inherited from IngredientSlot
IngredientSlot ()
IngredientSlot (const IngredientSlot &slot)
~IngredientSlot ()
Object * clone ()
Object * clone (void *object)
int getClientSlotType ()
void setOptional (bool value)
bool isOptional ()
void setIdentical (bool value)
bool requiresIdentical ()
void setContentType (const String &value)
void setQuantityNeeded (int value)
int getQuantityNeeded ()
bool removeAll (CreatureObject *player)
void setSlotName (const String &name)
const String & getSlotName ()
virtual int size ()
virtual void print ()
virtual bool isComponentSlot ()
Private Attributes
int quantity
VectorMap< ManagedReference
< SceneObject * >, int > parents
ManagedReference< ResourceSpawn * > currentSpawn
Additional Inherited Members
Static Public Attributes inherited from IngredientSlot
static const int RESOURCESLOT = 0
static const int IDENTICALSLOT = 1
static const int MIXEDSLOT = 2
static const int OPTIONALIDENTICALSLOT = 3
static const int OPTIONALMIXEDSLOT = 4
static const short OK = 0x00
static const short NOSERVER = 0x01
static const short NOTASSEMBLYSTAGE = 0x02
static const short NOTCUSTOMIZATIONSTAGE = 0x03
static const short NOSCHEMATIC = 0x04
static const short NOTOOL = 0x05
static const short NOMANUFACTURE = 0x06
static const short INVALID = 0x07
static const short INVALIDOPTION = 0x08
static const short INVALIDINGREDIENTSIZE = 0x09
static const short FULL = 0x0A
static const short INVALIDINGREDIENT = 0x0B
static const short INGREDIENTNOTININVENTORY = 0x0C
static const short BADCRATE = 0x0D
static const short BADRESOURCEFOR = 0x0E
static const short COMPONENTDAMAGED = 0x0F
static const short NOCOMPONENTTRANSFER = 0x10
static const short BADCOMPONENT = 0x11
static const short NOINVENTORY = 0x12
static const short BADSTATIONHOPPER = 0x13
static const short BADTARGETCONTAINER = 0x14
static const short EMPTYISEMPTY = 0x15
static const short FAILEDRESOURCECREATE = 0x16
static const short EMPTYASSEMBLE = 0x17
static const short PARTIALASSEMBLE = 0x18
static const short PROTOTYPENOTFOUND = 0x19
static const short BADNAME = 0x1A
static const short MYSTERY = 0x1B
static const short FAILEDTOTRANSFER = 0x1C
static const short WEIRDFAILEDMESSAGE = 0x1D
Protected Attributes inherited from IngredientSlot
String slotName
String contentType
int requiredQuantity
bool identical
bool optional
short clientSlotType
Detailed Description
Definition at line 53 of file ResourceSlot.h.
Constructor & Destructor Documentation
ResourceSlot::ResourceSlot () inline
Definition at line 60 of file ResourceSlot.h.
References IngredientSlot::clientSlotType, parents, and quantity.
Referenced by clone().
ResourceSlot::ResourceSlot (const ResourceSlot & slot) inline
Definition at line 67 of file ResourceSlot.h.
References parents, and quantity.
ResourceSlot::~ResourceSlot () inline
Definition at line 73 of file ResourceSlot.h.
Member Function Documentation
bool ResourceSlot::add (CreatureObject * player, SceneObject * satchel, ManagedReference< TangibleObject * > tano) inline virtual
Must be a resource container to proceed, and
Get spawn object
Verify the resource is the right type
Reimplemented from IngredientSlot.
Definition at line 81 of file ResourceSlot.h.
References IngredientSlot::contentType, currentSpawn, server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::resource::ResourceContainer::getQuantity(), server::zone::objects::resource::ResourceContainer::getSpawnObject(), server::zone::objects::resource::ResourceSpawn::isType(), parents, quantity, IngredientSlot::requiredQuantity, and server::zone::objects::resource::ResourceContainer::setQuantity().
Object* ResourceSlot::clone () inline
Definition at line 77 of file ResourceSlot.h.
References ResourceSlot().
ResourceSpawn* ResourceSlot::getCurrentSpawn () inline
Definition at line 201 of file ResourceSlot.h.
References currentSpawn.
Referenced by getFactoryIngredient(), and server::zone::managers::crafting::labratories::SharedLabratory::getWeightedValue().
SceneObject* ResourceSlot::getFactoryIngredient () inline virtual
Reimplemented from IngredientSlot.
Definition at line 205 of file ResourceSlot.h.
References getCurrentSpawn().
Vector<uint64> ResourceSlot::getOIDVector () inline virtual
Reimplemented from IngredientSlot.
Definition at line 209 of file ResourceSlot.h.
References currentSpawn.
Vector<int> ResourceSlot::getQuantityVector () inline virtual
Reimplemented from IngredientSlot.
Definition at line 216 of file ResourceSlot.h.
References quantity.
int ResourceSlot::getSlotQuantity () inline virtual
Reimplemented from IngredientSlot.
Definition at line 185 of file ResourceSlot.h.
References quantity.
bool ResourceSlot::isEmpty () inline virtual
Reimplemented from IngredientSlot.
Definition at line 193 of file ResourceSlot.h.
References quantity.
bool ResourceSlot::isFull () inline virtual
Reimplemented from IngredientSlot.
Definition at line 189 of file ResourceSlot.h.
References quantity, and IngredientSlot::requiredQuantity.
bool ResourceSlot::isResourceSlot () inline virtual
Reimplemented from IngredientSlot.
Definition at line 197 of file ResourceSlot.h.
bool ResourceSlot::returnToParents (CreatureObject * player) inline virtual
Reimplemented from IngredientSlot.
Definition at line 131 of file ResourceSlot.h.
References server::zone::objects::scene::SceneObject::broadcastObject(), currentSpawn, server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), parents, quantity, and server::zone::objects::scene::SceneObject::transferObject().
Member Data Documentation
ManagedReference<ResourceSpawn*> ResourceSlot::currentSpawn private
Definition at line 57 of file ResourceSlot.h.
Referenced by add(), getCurrentSpawn(), getOIDVector(), and returnToParents().
VectorMap<ManagedReference<SceneObject*>, int> ResourceSlot::parents private
Definition at line 56 of file ResourceSlot.h.
Referenced by add(), ResourceSlot(), and returnToParents().
int ResourceSlot::quantity private
Definition at line 55 of file ResourceSlot.h.
Referenced by add(), getQuantityVector(), getSlotQuantity(), isEmpty(), isFull(), ResourceSlot(), and returnToParents().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/ingredientslots/ResourceSlot.h