Core3: server::login::LoginServer Class Reference
server::login::LoginServer Class Reference
#include <LoginServer.h>
Public Member Functions
LoginServer (ConfigManager *config)
void initializeTransientMembers ()
LoginClient * createConnection (Socket *sock, SocketAddress &addr)
void initialize ()
void shutdown ()
void startManagers ()
void stopManagers ()
void start (int p, int mconn=10)
void stop ()
void handleMessage (LoginClient *client, Packet *message)
void processMessage (Message *message)
bool handleError (ServiceClient *client, Exception &e)
void printInfo ()
void populateGalaxyList ()
AccountManager * getAccountManager ()
Account * getAccount (unsigned int accountID)
LoginClient * getLoginClient (ServiceClient *session)
LoginEnumCluster * getLoginEnumClusterMessage ()
LoginClusterStatus * getLoginClusterStatusMessage ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
LoginServer (DummyConstructorParameter *param)
virtual ~LoginServer ()
Friends
class LoginServerHelper
Detailed Description
Definition at line 129 of file LoginServer.h.
Constructor & Destructor Documentation
LoginServer::LoginServer (ConfigManager * config)
Definition at line 29 of file LoginServer.cpp.
References server::login::LoginServerImplementation::_setStub().
LoginServer::LoginServer (DummyConstructorParameter * param) protected
Definition at line 36 of file LoginServer.cpp.
LoginServer::~LoginServer () protected virtual
Definition at line 40 of file LoginServer.cpp.
Member Function Documentation
DistributedObjectServant * LoginServer::_getImplementation ()
Definition at line 258 of file LoginServer.cpp.
Referenced by createConnection(), getAccount(), getAccountManager(), getLoginClient(), getLoginClusterStatusMessage(), getLoginEnumClusterMessage(), handleError(), handleMessage(), initialize(), initializeTransientMembers(), populateGalaxyList(), printInfo(), processMessage(), shutdown(), start(), startManagers(), stop(), and stopManagers().
DistributedObjectServant * LoginServer::_getImplementationForRead ()
Definition at line 264 of file LoginServer.cpp.
void LoginServer::_setImplementation (DistributedObjectServant * servant)
Definition at line 268 of file LoginServer.cpp.
LoginClient * LoginServer::createConnection (Socket * sock, SocketAddress & addr)
Definition at line 58 of file LoginServer.cpp.
References _getImplementation(), and server::login::LoginServerImplementation::createConnection().
Referenced by server::login::LoginHandler::createConnection().
Account * LoginServer::getAccount (unsigned int accountID)
Definition at line 209 of file LoginServer.cpp.
References _getImplementation(), server::login::LoginServerImplementation::getAccount(), and RPC_GETACCOUNT__INT_.
AccountManager * LoginServer::getAccountManager ()
Definition at line 200 of file LoginServer.cpp.
References _getImplementation(), and server::login::LoginServerImplementation::getAccountManager().
LoginClient * LoginServer::getLoginClient (ServiceClient * session)
Definition at line 223 of file LoginServer.cpp.
References _getImplementation(), and server::login::LoginServerImplementation::getLoginClient().
LoginClusterStatus * LoginServer::getLoginClusterStatusMessage ()
Definition at line 245 of file LoginServer.cpp.
References _getImplementation(), server::login::LoginServerImplementation::getLoginClusterStatusMessage(), and RPC_GETLOGINCLUSTERSTATUSMESSAGE__.
LoginEnumCluster * LoginServer::getLoginEnumClusterMessage ()
Definition at line 232 of file LoginServer.cpp.
References _getImplementation(), server::login::LoginServerImplementation::getLoginEnumClusterMessage(), and RPC_GETLOGINENUMCLUSTERMESSAGE__.
bool LoginServer::handleError (ServiceClient * client, Exception & e)
Definition at line 165 of file LoginServer.cpp.
References _getImplementation(), and server::login::LoginServerImplementation::handleError().
Referenced by server::login::LoginHandler::handleError().
void LoginServer::handleMessage (LoginClient * client, Packet * message)
Definition at line 147 of file LoginServer.cpp.
References _getImplementation(), and server::login::LoginServerImplementation::handleMessage().
Referenced by server::login::LoginHandler::handleMessage().
void LoginServer::initialize ()
Definition at line 67 of file LoginServer.cpp.
References _getImplementation(), server::login::LoginServerImplementation::initialize(), and RPC_INITIALIZE__.
Referenced by server::login::LoginHandler::initialize().
void LoginServer::initializeTransientMembers ()
Definition at line 45 of file LoginServer.cpp.
References _getImplementation(), server::login::LoginServerImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
void LoginServer::populateGalaxyList ()
Definition at line 187 of file LoginServer.cpp.
References _getImplementation(), server::login::LoginServerImplementation::populateGalaxyList(), and RPC_POPULATEGALAXYLIST__.
void LoginServer::printInfo ()
Definition at line 174 of file LoginServer.cpp.
References _getImplementation(), server::login::LoginServerImplementation::printInfo(), and RPC_PRINTINFO__.
void LoginServer::processMessage (Message * message)
Definition at line 156 of file LoginServer.cpp.
References _getImplementation(), and server::login::LoginServerImplementation::processMessage().
Referenced by server::login::LoginHandler::processMessage().
void LoginServer::shutdown ()
Definition at line 80 of file LoginServer.cpp.
References _getImplementation(), RPC_SHUTDOWN__, and server::login::LoginServerImplementation::shutdown().
void LoginServer::start (int p, int mconn = 10)
Definition at line 119 of file LoginServer.cpp.
References _getImplementation(), RPC_START__INT_INT_, and server::login::LoginServerImplementation::start().
void LoginServer::startManagers ()
Definition at line 93 of file LoginServer.cpp.
References _getImplementation(), RPC_STARTMANAGERS__, and server::login::LoginServerImplementation::startManagers().
void LoginServer::stop ()
Definition at line 134 of file LoginServer.cpp.
References _getImplementation(), RPC_STOP__, and server::login::LoginServerImplementation::stop().
void LoginServer::stopManagers ()
Definition at line 106 of file LoginServer.cpp.
References _getImplementation(), RPC_STOPMANAGERS__, and server::login::LoginServerImplementation::stopManagers().
Friends And Related Function Documentation
friend class LoginServerHelper friend
Definition at line 179 of file LoginServer.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginServer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginServer.cpp