Core3: WaypointList Class Reference
WaypointList Class Reference
#include <WaypointList.h>
Public Member Functions
int set (uint64 key, WaypointObject *value, DeltaMessage *message=NULL, int updates=1)
bool drop (const uint64 &key, DeltaMessage *message=NULL, int updates=1)
void insertToMessage (BaseMessage *msg)
uint64 find (const String &name)
uint64 getWaypointBySpecialType (const uint8 specialTypeID)
Public Member Functions inherited from DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >
DeltaVectorMap ()
DeltaVectorMap (int initsize, int incr)
DeltaVectorMap (const DeltaVectorMap &ds)
void addSerializableVariables ()
virtual int set (const uint64 &key, const ManagedReference< WaypointObject * > &value, DeltaMessage *message=NULL, int updates=1)
ManagedReference
< WaypointObject * > & getValueAt (int index)
uint64 & getKeyAt (int index)
ManagedReference
< WaypointObject * > & get (const uint64 &key)
bool contains (const uint64 &key)
int size ()
uint32 getUpdateCounter ()
void setNullValue (const ManagedReference< WaypointObject * > &val)
Additional Inherited Members
Protected Attributes inherited from DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >
VectorMap< uint64,
ManagedReference
< WaypointObject * > > vectorMap
uint32 updateCounter
Detailed Description
Definition at line 52 of file WaypointList.h.
Member Function Documentation
bool WaypointList::drop (const uint64 & key, DeltaMessage * message = NULL, int updates = 1) inline virtual
Reimplemented from DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >.
Definition at line 71 of file WaypointList.h.
References DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::updateCounter, and DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::vectorMap.
Referenced by server::zone::objects::player::PlayerObjectImplementation::removeWaypoint().
uint64 WaypointList::find (const String & name) inline
Definition at line 106 of file WaypointList.h.
References DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::getKeyAt(), DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::getValueAt(), and DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::size().
Referenced by server::zone::objects::player::PlayerObjectImplementation::addWaypoint().
uint64 WaypointList::getWaypointBySpecialType (const uint8 specialTypeID) inline
Definition at line 121 of file WaypointList.h.
References DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::vectorMap.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addWaypoint(), server::zone::objects::player::sessions::FindSessionImplementation::clearWaypoint(), FindCommand::doQueueCommand(), and server::zone::objects::player::PlayerObjectImplementation::getSurveyWaypoint().
void WaypointList::insertToMessage (BaseMessage * msg) inline virtual
Reimplemented from DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >.
Definition at line 92 of file WaypointList.h.
References DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::getKeyAt(), DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::getUpdateCounter(), DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::getValueAt(), and DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::size().
Referenced by PlayerObjectMessage8::PlayerObjectMessage8().
int WaypointList::set (uint64 key, WaypointObject * value, DeltaMessage * message = NULL, int updates = 1) inline
Definition at line 55 of file WaypointList.h.
References DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::updateCounter, and DeltaVectorMap< uint64, ManagedReference< WaypointObject * > >::vectorMap.
Referenced by server::zone::objects::player::PlayerObjectImplementation::setWaypoint().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/variables/WaypointList.h