Core3: ResourceContainerTransferCommand Class Reference
ResourceContainerTransferCommand Class Reference
#include <ResourceContainerTransferCommand.h>
Public Member Functions
ResourceContainerTransferCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Detailed Description
Definition at line 51 of file ResourceContainerTransferCommand.h.
Constructor & Destructor Documentation
ResourceContainerTransferCommand::ResourceContainerTransferCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 54 of file ResourceContainerTransferCommand.h.
Member Function Documentation
int ResourceContainerTransferCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 59 of file ResourceContainerTransferCommand.h.
References server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/ResourceContainerTransferCommand.h