Core3: server::chat::StringIdChatParameter Class Reference
server::chat::StringIdChatParameter Class Reference
#include <StringIdChatParameter.h>
Public Member Functions
StringIdChatParameter ()
StringIdChatParameter (const StringId &id)
StringIdChatParameter (const char *cstr)
StringIdChatParameter (const String &fullPath)
StringIdChatParameter (const String &fil, const String &stringId)
StringIdChatParameter (const StringIdChatParameter &custom)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
StringIdChatParameter & operator= (const StringIdChatParameter &id)
void parse (Message *message)
template<class T >
void setTT (const T &obj)
void setTT (const String &file, const String &stringid)
template<class T >
void setTU (const T &obj)
void setTU (const String &file, const String &stringid)
template<class T >
void setTO (const T &obj)
void setTO (const String &file, const String &stringid)
void setDI (uint32 i)
void setDF (float f)
void setUnknownByte (uint16 val)
StringIdParameter * getTT ()
StringIdParameter * getTU ()
StringIdParameter * getTO ()
Public Member Functions inherited from server::chat::ChatParameter
ChatParameter ()
ChatParameter (const ChatParameter &id)
ChatParameter & operator= (const ChatParameter &id)
void insertToMessage (Message *message)
bool isStringIdParameter ()
bool isWaypointParameter ()
Public Member Functions inherited from server::zone::objects::scene::variables::StringId
StringId ()
StringId (const StringId &id)
StringId (const char *cstr)
StringId (const String &fullPath)
StringId (const String &fil, const String &stringId)
StringId & operator= (const StringId &id)
bool operator== (const StringId &id) const
int compareTo (const StringId &id) const
void clear ()
void getFullPath (String &str) const
String getFullPath () const
String & getFile ()
String & getStringID ()
uint32 size () const
bool isEmpty () const
void setStringId (const String &fullPath)
void setStringId (const String &file, const String &id)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
Protected Member Functions
void addToPacketStream (Message *packet)
Protected Member Functions inherited from server::chat::ChatParameter
virtual void insertHeaderToMessage (Message *message)
Protected Attributes
StringIdParameter TT
StringIdParameter TU
StringIdParameter TO
uint32 DI
float DF
byte unknownByte
Protected Attributes inherited from server::zone::objects::scene::variables::StringId
String file
int filler
String stringID
Additional Inherited Members
Static Public Attributes inherited from server::chat::ChatParameter
static const byte TYPE_STRINGID = 1
static const byte TYPE_WAYPOINT = 4
static const int STRINGID = 0xFFFFFFFF
static const int WAYPOINT = 0xFFFFFFFD
Detailed Description
Definition at line 71 of file StringIdChatParameter.h.
Constructor & Destructor Documentation
StringIdChatParameter::StringIdChatParameter ()
Definition at line 47 of file StringIdChatParameter.cpp.
References DF, DI, and unknownByte.
StringIdChatParameter::StringIdChatParameter (const StringId & id)
Definition at line 53 of file StringIdChatParameter.cpp.
References DF, DI, and unknownByte.
StringIdChatParameter::StringIdChatParameter (const char * cstr)
Definition at line 59 of file StringIdChatParameter.cpp.
References DF, DI, and unknownByte.
StringIdChatParameter::StringIdChatParameter (const String & fullPath)
Definition at line 65 of file StringIdChatParameter.cpp.
References DF, DI, and unknownByte.
StringIdChatParameter::StringIdChatParameter (const String & fil, const String & stringId)
Definition at line 71 of file StringIdChatParameter.cpp.
References DF, DI, and unknownByte.
StringIdChatParameter::StringIdChatParameter (const StringIdChatParameter & custom)
Definition at line 77 of file StringIdChatParameter.cpp.
References DF, DI, TO, TT, TU, and unknownByte.
Member Function Documentation
void StringIdChatParameter::addToPacketStream (Message * packet) protected virtual
Inserts stf string identifier and variables into a packet
Precondition
{ packet is a valid Message }
Postcondition
{ data is inserted into packet }
Parameters
packet Message that data is to be inserted into
Implements server::chat::ChatParameter.
Definition at line 89 of file StringIdChatParameter.cpp.
References DF, DI, server::zone::objects::scene::variables::StringId::file, server::zone::objects::scene::variables::StringIdParameter::getFileParameter(), server::zone::objects::scene::variables::StringIdParameter::getPointerParameter(), server::zone::objects::scene::variables::StringIdParameter::getStringIDParameter(), server::zone::objects::scene::variables::StringIdParameter::getUnicodeParameter(), server::zone::objects::scene::variables::StringId::stringID, TO, TT, TU, and unknownByte.
StringIdParameter* server::chat::StringIdChatParameter::getTO () inline
Definition at line 229 of file StringIdChatParameter.h.
Referenced by LuaConversationScreen::setDialogTextTO().
StringIdParameter* server::chat::StringIdChatParameter::getTT () inline
Definition at line 221 of file StringIdChatParameter.h.
Referenced by LuaConversationScreen::setDialogTextTT().
StringIdParameter* server::chat::StringIdChatParameter::getTU () inline
Definition at line 225 of file StringIdChatParameter.h.
Referenced by LuaConversationScreen::setDialogTextTU().
StringIdChatParameter& server::chat::StringIdChatParameter::operator= (const StringIdChatParameter & id) inline
Definition at line 101 of file StringIdChatParameter.h.
References server::zone::objects::scene::variables::StringId::operator=(), and TT.
void StringIdChatParameter::parse (Message * message) virtual
Implements server::chat::ChatParameter.
Definition at line 117 of file StringIdChatParameter.cpp.
Referenced by ChatPersistentMessageToServerCallback::parse().
bool StringIdChatParameter::parseFromBinaryStream (ObjectInputStream * stream)
Definition at line 132 of file StringIdChatParameter.cpp.
References DF, DI, TO, TT, and TU.
void server::chat::StringIdChatParameter::setDF (float f) inline
Sets the DF variable
Precondition
{ }
Postcondition
{ DF variable is set }
Parameters
f value for DF
Definition at line 213 of file StringIdChatParameter.h.
Referenced by server::zone::objects::mission::SurveyMissionObjectiveImplementation::notifyObserverEvent(), server::zone::templates::mobile::ConversationScreen::setDialogTextDF(), and server::zone::managers::director::DirectorManager::setParameterDF().
void server::chat::StringIdChatParameter::setDI (uint32 i) inline
Sets the DI variable
Precondition
{ }
Postcondition
{ DI variable is set }
Parameters
i value for DI
Definition at line 203 of file StringIdChatParameter.h.
Referenced by server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer(), server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::zone::managers::player::PlayerManagerImplementation::awardExperience(), server::zone::objects::mission::MissionObjectiveImplementation::awardReward(), server::zone::managers::minigames::GamblingManagerImplementation::bet(), server::zone::managers::minigames::GamblingManagerImplementation::calculateOutcome(), server::zone::objects::player::sessions::PlaceStructureSessionImplementation::completeSession(), server::zone::objects::player::PlayerObjectImplementation::decreaseFactionStanding(), server::zone::managers::city::CityManagerImplementation::depositToCityTreasury(), server::zone::managers::gcw::GCWManagerImplementation::doBaseDestruction(), DelegateFactionPointsCommand::doDelegate(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), AddPowerCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), TipCommand::doQueueCommand(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), server::zone::objects::tangible::fishing::FishObjectImplementation::filet(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::findAndTrackSuccess(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), StructureTerminalMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), VendorDataComponent::handlePayMaintanence(), server::zone::objects::creature::conversation::screenhandlers::TrainerCanLearnSkillScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainSkillScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughCreditsScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughSkillPointsScreenHandler::handleScreen(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceDamage(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceEffectiveness(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceEncumbrance(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceSpeed(), VendorDataComponent::handleWithdrawMaintanence(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), server::zone::objects::player::PlayerObjectImplementation::increaseFactionStanding(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::objects::mission::SurveyMissionObjectiveImplementation::notifyObserverEvent(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::notifyObserverEvent(), StructureManager::payMaintenance(), TipCommand::performBankTip(), TipCommand::performTip(), CityDecorationTask::placeDecoration(), StructureManager::placeStructureFromDeed(), JunkDealerSellListSuiCallback::run(), InsertPowerSuiCallback::run(), InstallMissionTerminalSuiCallback::run(), CloningStoreSuiCallback::run(), RecruitSkillTrainerSuiCallback::run(), RepairVehicleSuiCallback::run(), TipCommandSuiCallback::run(), TaxPayMailTask::run(), MeditateTask::run(), server::zone::managers::gcw::GCWManagerImplementation::scheduleBaseDestruction(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailCondemned(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailDecay(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceDecayEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceEmail(), ResourceSpawner::sendSampleResults(), server::zone::objects::creature::LuaCreatureObject::sendSystemMessageWithDI(), server::zone::templates::mobile::ConversationScreen::setDialogTextDI(), server::zone::objects::creature::CreatureObjectImplementation::setNextAttackDelay(), server::zone::managers::director::DirectorManager::setParameterDI(), server::zone::managers::city::CityManagerImplementation::setTax(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::statusUpdate(), server::zone::objects::installation::factory::FactoryObjectImplementation::stopFactory(), and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
template<class T > void server::chat::StringIdChatParameter::setTO (const T & obj) inline
Sets the TO variable of a stf string
Precondition
{ obj is one of the following: String, UnicodeString, pointer to SceneObject that is in the client's memory, objectid of SceneObject that is in the client's memory, StringId, pointer to StringId }
Postcondition
{ TO variable is set }
Parameters
obj Data that the TO variable is to be set as
Definition at line 182 of file StringIdChatParameter.h.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::abortShutdownSequence(), server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer(), server::zone::objects::player::sessions::FindSessionImplementation::addWaypoint(), server::zone::managers::player::PlayerManagerImplementation::awardBadge(), server::zone::managers::player::PlayerManagerImplementation::awardExperience(), server::zone::managers::minigames::GamblingManagerImplementation::calculateOutcome(), server::zone::managers::auction::AuctionManagerImplementation::cancelItem(), server::zone::managers::city::CityManagerImplementation::castMayoralVote(), server::zone::managers::city::CityManagerImplementation::changeCitySpecialization(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::checkJoin(), server::zone::objects::player::sessions::PlaceStructureSessionImplementation::completeSession(), ConsentCommand::consent(), StructureManager::declareResidence(), server::zone::objects::player::PlayerObjectImplementation::decreaseFactionStanding(), server::zone::managers::auction::AuctionManagerImplementation::deleteExpiredSale(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), DelegateFactionPointsCommand::doDelegate(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), FindPlayerCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), TipCommand::doQueueCommand(), TransferstructureCommand::doTransferStructure(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireBidAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireSale(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::findAndTrackSuccess(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), LootSchematicMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::conversation::screenhandlers::TrainerCanLearnSkillScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainSkillScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughCreditsScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughSkillPointsScreenHandler::handleScreen(), server::zone::managers::sui::SuiManager::handleSetObjectName(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), server::zone::objects::player::PlayerObjectImplementation::increaseFactionStanding(), server::zone::objects::area::CampSiteActiveAreaImplementation::notifyEnter(), server::zone::objects::area::CampSiteActiveAreaImplementation::notifyExit(), LootContainerComponent::notifyObjectRemoved(), server::zone::objects::mission::HuntingMissionObjectiveImplementation::notifyObserverEvent(), server::zone::managers::player::PlayerManagerImplementation::offerTeaching(), server::zone::managers::gcw::GCWManagerImplementation::performDefenseDontation(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMine(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield(), server::zone::managers::gcw::GCWManagerImplementation::performDonateTurret(), CityDecorationTask::placeDecoration(), StructureManager::placeStructureFromDeed(), server::zone::managers::city::CityManagerImplementation::promptCitySpecialization(), server::zone::managers::auction::AuctionManagerImplementation::refundAuction(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), RevokeConsentSuiCallback::run(), TipCommandSuiCallback::run(), TurretControlSuiCallback::run(), TaxPayMailTask::run(), MeditateTask::run(), VendorDataComponent::runVendorUpdate(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailCondemned(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailDecay(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailMaintenanceWithdrawnFromBank(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceDecayEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceDestroyEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceRepairEmail(), ResourceSpawner::sendSampleResults(), ResourceSpawner::sendSurvey(), server::zone::objects::creature::LuaCreatureObject::sendSystemMessageWithTO(), server::zone::managers::guild::GuildManagerImplementation::sendTransferAckTo(), server::zone::managers::auction::AuctionsMapImplementation::sendVendorUpdateMail(), server::zone::templates::mobile::ConversationScreen::setDialogTextTO(), server::zone::templates::mobile::ConversationScreen::setDialogTextTU(), server::zone::managers::director::DirectorManager::setParameterTO(), server::zone::objects::player::sessions::survey::SurveySessionImplementation::startSample(), server::zone::objects::player::sessions::survey::SurveySessionImplementation::startSurvey(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::statusUpdate(), server::zone::objects::installation::factory::FactoryObjectImplementation::stopFactory(), UnconsentCommand::unconscent(), server::zone::managers::city::CityManagerImplementation::updateCityVoting(), server::zone::managers::city::CityManagerImplementation::validateCityInRange(), server::zone::managers::planet::PlanetManagerImplementation::validateClientCityInRange(), and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
void server::chat::StringIdChatParameter::setTO (const String & file, const String & stringid) inline
Sets the TO variable of this stf string to another stf string
Precondition
{ }
Postcondition
{ TO variable is set }
Parameters
file stf file name that contains the stf string
stringid stringid of stf string
Definition at line 193 of file StringIdChatParameter.h.
template<class T > void server::chat::StringIdChatParameter::setTT (const T & obj) inline
Sets the TT variable
Precondition
{ obj is one of the following: String, UnicodeString, pointer to SceneObject that is in the client's memory, objectid of SceneObject that is in the client's memory, StringId, pointer to StringId }
Postcondition
{ TT variable is set }
Parameters
obj Data that the TT variable is to be set as
Definition at line 132 of file StringIdChatParameter.h.
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsorshipRequest(), server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer(), server::zone::objects::player::PlayerObjectImplementation::addFriend(), server::zone::objects::player::PlayerObjectImplementation::addIgnore(), server::zone::managers::minigames::GamblingManagerImplementation::bet(), ForceCureDiseaseCommand::canPerformSkill(), ForceCurePoisonCommand::canPerformSkill(), StopBleedingCommand::canPerformSkill(), HealStatesOtherCommand::canPerformSkill(), HealDamageCommand::canPerformSkill(), CurePackCommand::canPerformSkill(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::checkJoin(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::createSellJunkLootSelection(), CombatManager::declineDuel(), DotPackCommand::doAreaMedicActionTarget(), BandFlourishCommand::doBandFlourish(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), InsureCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), TransferstructureCommand::doTransferStructure(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), CombatManager::freeDuelList(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleInsertFactorySchem(), WeaponObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleRemoveFactorySchem(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainedMasterScreenHandler::handleScreen(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), GroupManager::inviteToGroup(), GroupManager::joinGroup(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), SampleDnaTask::killCreature(), server::zone::managers::player::PlayerManagerImplementation::killPlayer(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), LootContainerComponent::notifyObjectRemoved(), server::zone::managers::player::PlayerManagerImplementation::offerTeaching(), StructureManager::payMaintenance(), TipCommand::performBankTip(), TipCommand::performTip(), VendorDataComponent::performVendorBark(), server::zone::managers::player::PlayerManagerImplementation::promptTeachableSkills(), server::zone::managers::auction::AuctionManagerImplementation::refundAuction(), server::zone::objects::player::PlayerObjectImplementation::removeFriend(), server::zone::objects::player::PlayerObjectImplementation::removeIgnore(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), CombatManager::requestDuel(), CombatManager::requestEndDuel(), InsuranceAllConfirmSuiCallback::run(), PlayerTeachConfirmSuiCallback::run(), InsuranceMenuSuiCallback::run(), JunkDealerSellListSuiCallback::run(), CloningStoreSuiCallback::run(), TipCommandSuiCallback::run(), CamoTask::run(), TotalHealOtherCommand::sendHealMessage(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailCondemned(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailDecay(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailMaintenanceWithdrawnFromBank(), ChatPersistentMessageToServerCallback::sendMailToPlayer(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceDecayEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceDestroyEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceRepairEmail(), server::zone::managers::minigames::FishingManagerImplementation::sendReward(), server::zone::templates::mobile::ConversationScreen::setDialogTextTT(), server::zone::managers::guild::GuildManagerImplementation::setMemberTitle(), server::zone::managers::director::DirectorManager::setParameterTT(), server::zone::managers::guild::GuildManagerImplementation::sponsorPlayer(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::statusUpdate(), server::zone::objects::installation::factory::FactoryObjectImplementation::stopFactory(), server::zone::managers::city::CityManagerImplementation::updateCityVoting(), and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
void server::chat::StringIdChatParameter::setTT (const String & file, const String & stringid) inline
Sets the TT variable of this stf string to another stf string
Precondition
{ }
Postcondition
{ TT variable is set }
Parameters
file stf file name that contains the stf string
stringid stringid of stf string
Definition at line 143 of file StringIdChatParameter.h.
template<class T > void server::chat::StringIdChatParameter::setTU (const T & obj) inline
Sets the TU variable of a stf string
Precondition
{ obj is one of the following: String, UnicodeString, pointer to SceneObject that is in the client's memory, objectid of SceneObject that is in the client's memory, StringId, pointer to StringId }
Postcondition
{ TU variable is set }
Parameters
obj Data that the TU variable is to be set as
Definition at line 157 of file StringIdChatParameter.h.
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsorshipRequest(), server::zone::managers::skill::SkillManager::awardSkill(), DotPackCommand::doAreaMedicActionTarget(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), GuildstatusCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), DiceMenuComponent::doRoll(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), GroupManager::joinGroup(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), server::zone::managers::guild::GuildManagerImplementation::leaveGuild(), LootContainerComponent::notifyObjectRemoved(), GuildSponsorVerifySuiCallback::run(), ItemDropTradeCallback::run(), server::zone::templates::mobile::ConversationScreen::setDialogTextTU(), server::zone::managers::guild::GuildManagerImplementation::setMemberTitle(), server::zone::managers::director::DirectorManager::setParameterTU(), server::zone::managers::guild::GuildManagerImplementation::sponsorPlayer(), server::zone::managers::player::PlayerManagerImplementation::stopListen(), and server::zone::managers::player::PlayerManagerImplementation::stopWatch().
void server::chat::StringIdChatParameter::setTU (const String & file, const String & stringid) inline
Sets the TU variable of this stf string to another stf string
Precondition
{ }
Postcondition
{ TU variable is set }
Parameters
file stf file name that contains the stf string
stringid stringid of stf string
Definition at line 168 of file StringIdChatParameter.h.
void server::chat::StringIdChatParameter::setUnknownByte (uint16 val) inline
Definition at line 217 of file StringIdChatParameter.h.
bool StringIdChatParameter::toBinaryStream (ObjectOutputStream * stream)
Definition at line 121 of file StringIdChatParameter.cpp.
References DF, DI, TO, TT, and TU.
Member Data Documentation
float server::chat::StringIdChatParameter::DF protected
Definition at line 78 of file StringIdChatParameter.h.
Referenced by addToPacketStream(), parseFromBinaryStream(), StringIdChatParameter(), and toBinaryStream().
uint32 server::chat::StringIdChatParameter::DI protected
Definition at line 77 of file StringIdChatParameter.h.
Referenced by addToPacketStream(), parseFromBinaryStream(), StringIdChatParameter(), and toBinaryStream().
StringIdParameter server::chat::StringIdChatParameter::TO protected
Definition at line 75 of file StringIdChatParameter.h.
Referenced by addToPacketStream(), parseFromBinaryStream(), StringIdChatParameter(), and toBinaryStream().
StringIdParameter server::chat::StringIdChatParameter::TT protected
Definition at line 73 of file StringIdChatParameter.h.
Referenced by addToPacketStream(), operator=(), parseFromBinaryStream(), StringIdChatParameter(), and toBinaryStream().
StringIdParameter server::chat::StringIdChatParameter::TU protected
Definition at line 74 of file StringIdChatParameter.h.
Referenced by addToPacketStream(), parseFromBinaryStream(), StringIdChatParameter(), and toBinaryStream().
byte server::chat::StringIdChatParameter::unknownByte protected
Definition at line 80 of file StringIdChatParameter.h.
Referenced by addToPacketStream(), and StringIdChatParameter().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/StringIdChatParameter.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/StringIdChatParameter.cpp