Core3: server::zone::managers::minigames::GamblingManagerImplementation Class Reference
server::zone::managers::minigames::GamblingManagerImplementation Class Reference
#include <GamblingManager.h>
Public Member Functions
GamblingManagerImplementation ()
GamblingManagerImplementation (DummyConstructorParameter *param)
Vector< String > * getRoulette ()
void initializeSlotTimer ()
void initializeRouletteTimer ()
void initializeSlots ()
void initializeRouletteRed ()
void initializeRoulette ()
int notify (SceneObject *sceneObject)
bool isHigh (int value)
bool isLow (int value)
bool isEven (int value)
bool isOdd (int value)
bool isBlack (int value)
bool isRed (int value)
void handleSlot (CreatureObject *player, bool cancel, bool other)
void bet (CreatureObject *player, int amount, int target, int machineType)
void bet (GamblingTerminal *terminal, CreatureObject *player, int amount, int target)
void startGame (CreatureObject *player, int machineType)
void startGame (GamblingTerminal *terminal)
void leaveTerminal (CreatureObject *player, int machineType)
void registerPlayer (GamblingTerminal *terminal, CreatureObject *player)
void refreshRouletteMenu (CreatureObject *player)
void continueGame (GamblingTerminal *terminal)
void stopGame (GamblingTerminal *terminal, bool cancel)
void calculateOutcome (GamblingTerminal *terminal)
unsigned int createWindow (GamblingTerminal *terminal, CreatureObject *player)
unsigned int createPayoutWindow (CreatureObject *player)
unsigned int createSlotWindow (CreatureObject *player, unsigned int payoutBoxID)
unsigned int createRouletteWindow (CreatureObject *player)
void createEvent (GamblingTerminal *terminal, int time)
bool isPlaying (CreatureObject *player)
operator const GamblingManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< GamblingManager * > _this
Protected Member Functions
void refreshSlotMenu (CreatureObject *player, GamblingTerminal *terminal)
virtual ~GamblingManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
VectorMap< ManagedReference
< CreatureObject * >
, ManagedReference
< GamblingTerminal * > > slotGames
VectorMap< ManagedReference
< CreatureObject * >
, ManagedReference
< GamblingTerminal * > > rouletteGames
Vector< String > roulette
Vector< String > red
Vector< int > slot
Vector< int > slotTimer
Vector< int > rouletteTimer
Friends
class GamblingManager
Detailed Description
Definition at line 332 of file GamblingManager.h.
Constructor & Destructor Documentation
GamblingManagerImplementation::GamblingManagerImplementation ()
Definition at line 682 of file GamblingManager.cpp.
References _initializeImplementation(), initializeRoulette(), initializeRouletteRed(), initializeRouletteTimer(), initializeSlots(), and initializeSlotTimer().
GamblingManagerImplementation::GamblingManagerImplementation (DummyConstructorParameter * param)
Definition at line 484 of file GamblingManager.cpp.
References _initializeImplementation().
GamblingManagerImplementation::~GamblingManagerImplementation () protected virtual
Definition at line 489 of file GamblingManager.cpp.
Member Function Documentation
DistributedObjectStub * GamblingManagerImplementation::_getStub ()
Definition at line 509 of file GamblingManager.cpp.
References _this.
void GamblingManagerImplementation::_initializeImplementation () protected
Definition at line 496 of file GamblingManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by GamblingManagerImplementation().
void GamblingManagerImplementation::_serializationHelperMethod () protected
Definition at line 545 of file GamblingManager.cpp.
Referenced by _initializeImplementation().
void GamblingManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 504 of file GamblingManager.cpp.
References _this.
Referenced by server::zone::managers::minigames::GamblingManager::GamblingManager().
void GamblingManagerImplementation::bet (CreatureObject * player, int amount, int target, int machineType)
Accept bet from /bet command This method receives the player who wants to bet, the amount he wants to bet, and the target he's betting on and calls bet(terminal, player, amount, target)
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject betting money
amount Amount of Credits to bet
target Target field (remains empty for slotMachine)
Definition at line 262 of file GamblingManagerImplementation.cpp.
References rouletteGames, and slotGames.
Referenced by server::zone::managers::minigames::GamblingManager::bet(), calculateOutcome(), and handleSlot().
void GamblingManagerImplementation::bet (GamblingTerminal * terminal, CreatureObject * player, int amount, int target)
Accept bet from /bet command or startGame This method receives the player who wants to bet, the amount he wants to bet, and the target he's betting on The method creates a bet and adds it to the GamblingTerminal's bets VectorMap
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
terminal GamblingTerminal for which to add bet
player CreatureObject betting money
amount Amount of Credits to bet
target Target field (remains empty for slotMachine)
Definition at line 273 of file GamblingManagerImplementation.cpp.
References server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getBets(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::scene::variables::StringId::getFullPath(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getMachineType(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getMaxBet(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getMinBet(), server::zone::objects::scene::SceneObject::getObjectName(), server::zone::objects::scene::SceneObject::isInRange(), refreshSlotMenu(), roulette, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setCashCredits(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTT(), and startGame().
void GamblingManagerImplementation::calculateOutcome (GamblingTerminal * terminal)
Calculates the results of each players' bets This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 531 of file GamblingManagerImplementation.cpp.
References bet(), server::zone::managers::minigames::GamblingBet::getAmount(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getBets(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getFirst(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getMachineType(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getPlayersWindows(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getSecond(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getThird(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getWinnings(), isBlack(), isEven(), isHigh(), isLow(), isOdd(), isRed(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::notifyOthers(), roulette, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setCashCredits(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), and slot.
Referenced by server::zone::managers::minigames::GamblingManager::calculateOutcome(), and stopGame().
void GamblingManagerImplementation::continueGame (GamblingTerminal * terminal)
Continues the Game This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 420 of file GamblingManagerImplementation.cpp.
References createEvent(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getMachineType(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getPlayersWindows(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getState(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::joinTerminal(), rouletteTimer, server::zone::objects::tangible::terminal::gambling::GamblingTerminal::setState(), slotTimer, server::zone::objects::tangible::terminal::gambling::GamblingTerminal::statusUpdate(), and stopGame().
Referenced by server::zone::managers::minigames::GamblingManager::continueGame().
void GamblingManagerImplementation::createEvent (GamblingTerminal * terminal, int time)
Creates Events This method receives a Terminal and a time, creates a GamblingEvent, stores it in the Terminal and schedules it to time
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
terminal GamblingTerminal for which to create event
time Time in ms to schedule the Task
Definition at line 412 of file GamblingManagerImplementation.cpp.
References server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getEvent(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getGameCount(), and server::zone::objects::tangible::terminal::gambling::GamblingTerminal::setEvent().
Referenced by continueGame(), server::zone::managers::minigames::GamblingManager::createEvent(), startGame(), and stopGame().
uint32 GamblingManagerImplementation::createPayoutWindow (CreatureObject * player)
Creates the SlotPayoutWindow This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 184 of file GamblingManagerImplementation.cpp.
References SuiWindowType::GAMBLING_SLOT_PAYOUT, server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::managers::minigames::GamblingManager::createPayoutWindow(), and createWindow().
uint32 GamblingManagerImplementation::createRouletteWindow (CreatureObject * player)
Creates the RouletteWindow This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 127 of file GamblingManagerImplementation.cpp.
References SuiWindowType::GAMBLING_ROULETTE, server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), rouletteGames, and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::zone::managers::minigames::GamblingManager::createRouletteWindow(), createWindow(), and refreshRouletteMenu().
uint32 GamblingManagerImplementation::createSlotWindow (CreatureObject * player, unsigned int payoutBoxID)
Creates the SlotWindow This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
payoutBoxID boxID of the payout menu so it can be closed later
Definition at line 73 of file GamblingManagerImplementation.cpp.
References SuiWindowType::GAMBLING_SLOT, server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::sendMessage(), and slotGames.
Referenced by server::zone::managers::minigames::GamblingManager::createSlotWindow(), createWindow(), and refreshSlotMenu().
uint32 GamblingManagerImplementation::createWindow (GamblingTerminal * terminal, CreatureObject * player)
Creates the Windows This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 48 of file GamblingManagerImplementation.cpp.
References createPayoutWindow(), createRouletteWindow(), createSlotWindow(), and server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getMachineType().
Referenced by server::zone::managers::minigames::GamblingManager::createWindow().
void GamblingManagerImplementation::finalize () protected
Definition at line 493 of file GamblingManager.cpp.
Vector< String > * GamblingManagerImplementation::getRoulette ()
Definition at line 700 of file GamblingManager.cpp.
References roulette.
Referenced by server::zone::managers::minigames::GamblingManager::getRoulette().
void GamblingManagerImplementation::handleSlot (CreatureObject * player, bool cancel, bool other)
Definition at line 239 of file GamblingManagerImplementation.cpp.
References bet(), leaveTerminal(), slotGames, and startGame().
Referenced by server::zone::managers::minigames::GamblingManager::handleSlot().
void GamblingManagerImplementation::initializeRoulette ()
Definition at line 805 of file GamblingManager.cpp.
References roulette.
Referenced by GamblingManagerImplementation(), and server::zone::managers::minigames::GamblingManager::initializeRoulette().
void GamblingManagerImplementation::initializeRouletteRed ()
Definition at line 766 of file GamblingManager.cpp.
References red.
Referenced by GamblingManagerImplementation(), and server::zone::managers::minigames::GamblingManager::initializeRouletteRed().
void GamblingManagerImplementation::initializeRouletteTimer ()
Definition at line 720 of file GamblingManager.cpp.
References rouletteTimer.
Referenced by GamblingManagerImplementation(), and server::zone::managers::minigames::GamblingManager::initializeRouletteTimer().
void GamblingManagerImplementation::initializeSlots ()
Definition at line 747 of file GamblingManager.cpp.
References slot.
Referenced by GamblingManagerImplementation(), and server::zone::managers::minigames::GamblingManager::initializeSlots().
void GamblingManagerImplementation::initializeSlotTimer ()
Definition at line 705 of file GamblingManager.cpp.
References slotTimer.
Referenced by GamblingManagerImplementation(), and server::zone::managers::minigames::GamblingManager::initializeSlotTimer().
bool GamblingManagerImplementation::isBlack (int value)
Definition at line 942 of file GamblingManager.cpp.
References isRed(), and roulette.
Referenced by calculateOutcome(), and server::zone::managers::minigames::GamblingManager::isBlack().
bool GamblingManagerImplementation::isEven (int value)
Definition at line 920 of file GamblingManager.cpp.
Referenced by calculateOutcome(), and server::zone::managers::minigames::GamblingManager::isEven().
bool GamblingManagerImplementation::isHigh (int value)
Definition at line 904 of file GamblingManager.cpp.
Referenced by calculateOutcome(), and server::zone::managers::minigames::GamblingManager::isHigh().
bool GamblingManagerImplementation::isLow (int value)
Definition at line 912 of file GamblingManager.cpp.
Referenced by calculateOutcome(), and server::zone::managers::minigames::GamblingManager::isLow().
bool GamblingManagerImplementation::isOdd (int value)
Definition at line 931 of file GamblingManager.cpp.
Referenced by calculateOutcome(), and server::zone::managers::minigames::GamblingManager::isOdd().
bool GamblingManagerImplementation::isPlaying (CreatureObject * player)
Definition at line 972 of file GamblingManager.cpp.
References rouletteGames, and slotGames.
Referenced by server::zone::managers::minigames::GamblingManager::isPlaying().
bool GamblingManagerImplementation::isRed (int value)
Definition at line 953 of file GamblingManager.cpp.
References red, and roulette.
Referenced by calculateOutcome(), isBlack(), and server::zone::managers::minigames::GamblingManager::isRed().
void GamblingManagerImplementation::leaveTerminal (CreatureObject * player, int machineType)
LeaveTerminal called by SuiManager This method receives a CreatureObject, looks it up in the machineType's corresponding VectorMap and then calls Terminal::leaveTerminal(player)
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject who wants to leave the Terminal
machineType machine type of the Terminal, set in the SuiManager
Definition at line 743 of file GamblingManagerImplementation.cpp.
References rouletteGames, and slotGames.
Referenced by handleSlot(), and server::zone::managers::minigames::GamblingManager::leaveTerminal().
void GamblingManagerImplementation::lock (bool doLock = true) protected
Definition at line 517 of file GamblingManager.cpp.
References _this.
void GamblingManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 521 of file GamblingManager.cpp.
References _this.
int GamblingManagerImplementation::notify (SceneObject * sceneObject)
Definition at line 896 of file GamblingManager.cpp.
References server::zone::objects::scene::SceneObject::isCreatureObject().
Referenced by server::zone::managers::minigames::GamblingManager::notify().
GamblingManagerImplementation::operator const GamblingManager * ()
Definition at line 513 of file GamblingManager.cpp.
void GamblingManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 552 of file GamblingManager.cpp.
References readObjectMember().
bool GamblingManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 571 of file GamblingManager.cpp.
References red, roulette, rouletteGames, rouletteTimer, slot, slotGames, and slotTimer.
Referenced by readObject().
void GamblingManagerImplementation::refreshRouletteMenu (CreatureObject * player)
Refreshes the menu This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 217 of file GamblingManagerImplementation.cpp.
References createRouletteWindow(), and rouletteGames.
Referenced by server::zone::managers::minigames::GamblingManager::refreshRouletteMenu().
void GamblingManagerImplementation::refreshSlotMenu (CreatureObject * player, GamblingTerminal * terminal) protected
Definition at line 229 of file GamblingManagerImplementation.cpp.
References server::zone::objects::tangible::terminal::gambling::GamblingTerminal::closeMenu(), createSlotWindow(), and server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getPlayersWindows().
Referenced by bet().
void GamblingManagerImplementation::registerPlayer (GamblingTerminal * terminal, CreatureObject * player)
Adds player to VectorMap This method switches machineTypes adding the Player and GamblingTerminal to the machineType's corresponding VectorMap
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
terminal GamblingTerminal to register
player CreatureObject to register
Definition at line 31 of file GamblingManagerImplementation.cpp.
References _this, server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getMachineType(), rouletteGames, and slotGames.
Referenced by server::zone::managers::minigames::GamblingManager::registerPlayer().
void GamblingManagerImplementation::rlock (bool doLock = true) protected
Definition at line 525 of file GamblingManager.cpp.
References _this.
void GamblingManagerImplementation::runlock (bool doLock = true) protected
Definition at line 541 of file GamblingManager.cpp.
References _this.
void GamblingManagerImplementation::startGame (CreatureObject * player, int machineType)
StartGame called by SuiManager This method receives a CreatureObject, looks it up in the machineType's corresponding VectorMap and then calls startGame(Terminal)
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to start the Game
machineType machine type of the Terminal, set in the SuiManager
Definition at line 365 of file GamblingManagerImplementation.cpp.
References rouletteGames, and slotGames.
Referenced by bet(), handleSlot(), and server::zone::managers::minigames::GamblingManager::startGame().
void GamblingManagerImplementation::startGame (GamblingTerminal * terminal)
Starts Game This method receives a GamblingTerminal, starting the Event cycle of the Game
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
terminal GamblingTerminal for which to start the game
Definition at line 381 of file GamblingManagerImplementation.cpp.
References createEvent(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getMachineType(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getState(), rouletteTimer, server::zone::objects::tangible::terminal::gambling::GamblingTerminal::setState(), slotTimer, and server::zone::objects::tangible::terminal::gambling::GamblingTerminal::statusUpdate().
void GamblingManagerImplementation::stopGame (GamblingTerminal * terminal, bool cancel)
Ends the Game This method receives a CreatureObject, looks it up in the Roulette VectorMap and then closes the Roulette Menu, reopening it
Precondition
{ this object is not locked }
Postcondition
{ this object is not locked }
Parameters
player CreatureObject for which to refresh menu
Definition at line 474 of file GamblingManagerImplementation.cpp.
References calculateOutcome(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::closeAllMenus(), createEvent(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getBets(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getEvent(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getMachineType(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::getState(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::reset(), server::zone::objects::tangible::terminal::gambling::GamblingTerminal::setState(), slotTimer, and server::zone::objects::tangible::terminal::gambling::GamblingTerminal::statusUpdate().
Referenced by continueGame(), and server::zone::managers::minigames::GamblingManager::stopGame().
void GamblingManagerImplementation::unlock (bool doLock = true) protected
Definition at line 537 of file GamblingManager.cpp.
References _this.
void GamblingManagerImplementation::wlock (bool doLock = true) protected
Definition at line 529 of file GamblingManager.cpp.
References _this.
void GamblingManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 533 of file GamblingManager.cpp.
References _this.
void GamblingManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 609 of file GamblingManager.cpp.
References writeObjectMembers().
int GamblingManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 616 of file GamblingManager.cpp.
References red, roulette, rouletteGames, rouletteTimer, slot, slotGames, and slotTimer.
Referenced by writeObject().
Friends And Related Function Documentation
friend class GamblingManager friend
Definition at line 579 of file GamblingManager.h.
Member Data Documentation
WeakReference<GamblingManager*> server::zone::managers::minigames::GamblingManagerImplementation::_this
Definition at line 545 of file GamblingManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), registerPlayer(), rlock(), runlock(), unlock(), and wlock().
Vector<String> server::zone::managers::minigames::GamblingManagerImplementation::red protected
Definition at line 340 of file GamblingManager.h.
Referenced by initializeRouletteRed(), isRed(), readObjectMember(), and writeObjectMembers().
Vector<String> server::zone::managers::minigames::GamblingManagerImplementation::roulette protected
Definition at line 338 of file GamblingManager.h.
Referenced by bet(), calculateOutcome(), getRoulette(), initializeRoulette(), isBlack(), isRed(), readObjectMember(), and writeObjectMembers().
VectorMap<ManagedReference<CreatureObject* >, ManagedReference<GamblingTerminal* > > server::zone::managers::minigames::GamblingManagerImplementation::rouletteGames protected
Definition at line 336 of file GamblingManager.h.
Referenced by bet(), createRouletteWindow(), isPlaying(), leaveTerminal(), readObjectMember(), refreshRouletteMenu(), registerPlayer(), startGame(), and writeObjectMembers().
Vector<int> server::zone::managers::minigames::GamblingManagerImplementation::rouletteTimer protected
Definition at line 346 of file GamblingManager.h.
Referenced by continueGame(), initializeRouletteTimer(), readObjectMember(), startGame(), and writeObjectMembers().
Vector<int> server::zone::managers::minigames::GamblingManagerImplementation::slot protected
Definition at line 342 of file GamblingManager.h.
Referenced by calculateOutcome(), initializeSlots(), readObjectMember(), and writeObjectMembers().
VectorMap<ManagedReference<CreatureObject* >, ManagedReference<GamblingTerminal* > > server::zone::managers::minigames::GamblingManagerImplementation::slotGames protected
Definition at line 334 of file GamblingManager.h.
Referenced by bet(), createSlotWindow(), handleSlot(), isPlaying(), leaveTerminal(), readObjectMember(), registerPlayer(), startGame(), and writeObjectMembers().
Vector<int> server::zone::managers::minigames::GamblingManagerImplementation::slotTimer protected
Definition at line 344 of file GamblingManager.h.
Referenced by continueGame(), initializeSlotTimer(), readObjectMember(), startGame(), stopGame(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/GamblingManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/GamblingManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/GamblingManagerImplementation.cpp