Core3: server::zone::objects::mission::ReconMissionObjective Class Reference
server::zone::objects::mission::ReconMissionObjective Class Reference
#include <ReconMissionObjective.h>
Public Member Functions
ReconMissionObjective (MissionObject *mission)
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (MissionObject *parent)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ReconMissionObjective (DummyConstructorParameter *param)
virtual ~ReconMissionObjective ()
Protected Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (DummyConstructorParameter *param)
virtual ~MissionObjective ()
Friends
class ReconMissionObjectiveHelper
Detailed Description
Definition at line 95 of file ReconMissionObjective.h.
Constructor & Destructor Documentation
ReconMissionObjective::ReconMissionObjective (MissionObject * mission)
Definition at line 23 of file ReconMissionObjective.cpp.
References server::zone::objects::mission::ReconMissionObjectiveImplementation::_setStub().
ReconMissionObjective::ReconMissionObjective (DummyConstructorParameter * param) protected
Definition at line 30 of file ReconMissionObjective.cpp.
ReconMissionObjective::~ReconMissionObjective () protected virtual
Definition at line 34 of file ReconMissionObjective.cpp.
Member Function Documentation
DistributedObjectServant * ReconMissionObjective::_getImplementation ()
Definition at line 100 of file ReconMissionObjective.cpp.
Referenced by abort(), activate(), complete(), getEndPosition(), and initializeTransientMembers().
DistributedObjectServant * ReconMissionObjective::_getImplementationForRead ()
Definition at line 106 of file ReconMissionObjective.cpp.
void ReconMissionObjective::_setImplementation (DistributedObjectServant * servant)
Definition at line 110 of file ReconMissionObjective.cpp.
void ReconMissionObjective::abort ()
Definition at line 65 of file ReconMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::ReconMissionObjectiveImplementation::abort(), and RPC_ABORT__.
void ReconMissionObjective::activate ()
Definition at line 52 of file ReconMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::ReconMissionObjectiveImplementation::activate(), and RPC_ACTIVATE__.
void ReconMissionObjective::complete ()
Definition at line 78 of file ReconMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::ReconMissionObjectiveImplementation::complete(), and RPC_COMPLETE__.
Vector3 ReconMissionObjective::getEndPosition ()
Definition at line 91 of file ReconMissionObjective.cpp.
References _getImplementation(), and server::zone::objects::mission::ReconMissionObjectiveImplementation::getEndPosition().
void ReconMissionObjective::initializeTransientMembers ()
Definition at line 39 of file ReconMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::ReconMissionObjectiveImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
Friends And Related Function Documentation
friend class ReconMissionObjectiveHelper friend
Definition at line 119 of file ReconMissionObjective.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/ReconMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/ReconMissionObjective.cpp