Core3: server::zone::objects::creature::buffs::Buff Class Reference
server::zone::objects::creature::buffs::Buff Class Reference
#include <Buff.h>
Public Member Functions
Buff (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
void sendTo (CreatureObject *player)
void sendDestroyTo (CreatureObject *player)
void activate (bool applyModifiers)
void deactivate (bool removeModifiers)
void activate ()
void deactivate ()
VectorMap< String, int > * getSkillModifiers ()
void applyAttributeModifiers ()
void applySkillModifiers ()
void applyStates ()
void removeAttributeModifiers ()
void removeSkillModifiers ()
void removeStates ()
void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
void parseAttributeModifierString (const String &modifierstring)
void parseSkillModifierString (const String &modifierstring)
String getAttributeModifierString ()
String getSkillModifierString ()
float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
VectorMap< byte, int > * getAttributeModifiers ()
int getAttributeModifierValue (byte attribute)
int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartMessage (StringIdChatParameter &start)
void setEndMessage (StringIdChatParameter &end)
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
Buff (DummyConstructorParameter *param)
virtual ~Buff ()
Friends
class BuffHelper
Detailed Description
Definition at line 80 of file Buff.h.
Constructor & Destructor Documentation
Buff::Buff (CreatureObject * creo, unsigned int buffcrc, float duration, int bufftype)
Definition at line 19 of file Buff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_setStub().
Buff::Buff (DummyConstructorParameter * param) protected
Definition at line 26 of file Buff.cpp.
Buff::~Buff () protected virtual
Definition at line 30 of file Buff.cpp.
Member Function Documentation
DistributedObjectServant * Buff::_getImplementation ()
Definition at line 637 of file Buff.cpp.
Referenced by activate(), addState(), applyAttributeModifiers(), applySkillModifiers(), applyStates(), clearBuffEvent(), deactivate(), getAttributeModifiers(), getAttributeModifierString(), getAttributeModifierValue(), getBuffCRC(), getBuffDuration(), getBuffName(), getBuffType(), getSkillModifiers(), getSkillModifierString(), getSkillModifierValue(), getTimeLeft(), init(), initializeTransientMembers(), isActive(), isAttributeBuff(), isSpiceBuff(), loadBuffDurationEvent(), notifyLoadFromDatabase(), parseAttributeModifierString(), parseSkillModifierString(), removeAttributeModifiers(), removeSkillModifiers(), removeStates(), scheduleBuffEvent(), sendDestroyTo(), sendTo(), setAccelerationMultiplierMod(), setAttributeModifier(), setBuffEventNull(), setEndFlyText(), setEndMessage(), setFillAttributesOnBuff(), setSkillModifier(), setSpeedMultiplierMod(), setStartFlyText(), and setStartMessage().
DistributedObjectServant * Buff::_getImplementationForRead ()
Definition at line 643 of file Buff.cpp.
void Buff::_setImplementation (DistributedObjectServant * servant)
Definition at line 647 of file Buff.cpp.
void Buff::activate (bool applyModifiers)
Definition at line 116 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::activate(), and RPC_ACTIVATE__BOOL_.
Referenced by BuffList::addBuff().
void Buff::activate ()
Definition at line 144 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::activate(), and RPC_ACTIVATE__.
void Buff::addState (unsigned long long option)
Definition at line 397 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::addState(), and RPC_ADDSTATE__LONG_.
Referenced by ThrowTrapCommand::doQueueCommand().
void Buff::applyAttributeModifiers ()
Definition at line 179 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::applyAttributeModifiers(), and RPC_APPLYATTRIBUTEMODIFIERS__.
void Buff::applySkillModifiers ()
Definition at line 192 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::applySkillModifiers(), and RPC_APPLYSKILLMODIFIERS__.
void Buff::applyStates ()
Definition at line 205 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::applyStates(), and RPC_APPLYSTATES__.
void Buff::clearBuffEvent ()
Definition at line 257 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::clearBuffEvent(), and RPC_CLEARBUFFEVENT__.
Referenced by BuffList::removeBuff().
void Buff::deactivate (bool removeModifiers)
Definition at line 130 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::deactivate(), and RPC_DEACTIVATE__BOOL_.
Referenced by BuffList::removeBuff().
void Buff::deactivate ()
Definition at line 157 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::deactivate(), and RPC_DEACTIVATE__.
VectorMap< byte, int > * Buff::getAttributeModifiers ()
Definition at line 507 of file Buff.cpp.
References _getImplementation(), and server::zone::objects::creature::buffs::BuffImplementation::getAttributeModifiers().
Referenced by server::zone::managers::player::PlayerManagerImplementation::fixHAM().
String Buff::getAttributeModifierString ()
Definition at line 324 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::getAttributeModifierString(), and RPC_GETATTRIBUTEMODIFIERSTRING__.
int Buff::getAttributeModifierValue (byte attribute)
Definition at line 516 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::getAttributeModifierValue(), and RPC_GETATTRIBUTEMODIFIERVALUE__BYTE_.
Referenced by HealEnhanceCommand::doQueueCommand(), and server::zone::managers::player::PlayerManagerImplementation::healEnhance().
int Buff::getBuffCRC ()
Definition at line 468 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::getBuffCRC(), and RPC_GETBUFFCRC__.
Referenced by BuffList::addBuff(), server::zone::objects::creature::CreatureObjectImplementation::addBuff(), BuffList::removeBuff(), and server::zone::objects::creature::CreatureObjectImplementation::removeBuff().
float Buff::getBuffDuration ()
Definition at line 481 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::getBuffDuration(), and RPC_GETBUFFDURATION__.
String Buff::getBuffName ()
Definition at line 453 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::getBuffName(), and RPC_GETBUFFNAME__.
int Buff::getBuffType ()
Definition at line 494 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::getBuffType(), and RPC_GETBUFFTYPE__.
Referenced by BuffList::addBuff().
VectorMap< String, int > * Buff::getSkillModifiers ()
Definition at line 170 of file Buff.cpp.
References _getImplementation(), and server::zone::objects::creature::buffs::BuffImplementation::getSkillModifiers().
Referenced by server::zone::managers::skill::SkillModManager::verifyBuffSkillMods().
String Buff::getSkillModifierString ()
Definition at line 339 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::getSkillModifierString(), and RPC_GETSKILLMODIFIERSTRING__.
int Buff::getSkillModifierValue (const String & modname)
Definition at line 530 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::getSkillModifierValue(), and RPC_GETSKILLMODIFIERVALUE__STRING_.
Referenced by server::zone::managers::crafting::CraftingManagerImplementation::calculateAssemblySuccess(), server::zone::managers::crafting::CraftingManagerImplementation::calculateExperimentationSuccess(), CurePackCommand::deactivateConditionTreatment(), HealDamageCommand::deactivateInjuryTreatment(), HealStateCommand::deactivateStateTreatment(), HealEnhanceCommand::deactivateWoundTreatment(), HealWoundCommand::deactivateWoundTreatment(), DotPackCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), BuffList::getModifierByName(), and server::zone::managers::player::PlayerManagerImplementation::healEnhance().
float Buff::getTimeLeft ()
Definition at line 354 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::getTimeLeft(), and RPC_GETTIMELEFT__.
void Buff::init ()
Definition at line 75 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::init(), and RPC_INIT__.
void Buff::initializeTransientMembers ()
Definition at line 35 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
bool Buff::isActive ()
Definition at line 544 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::isActive(), and RPC_ISACTIVE__.
Referenced by BuffList::addBuff(), and BuffList::removeBuff().
bool Buff::isAttributeBuff ()
Definition at line 570 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::isAttributeBuff(), and RPC_ISATTRIBUTEBUFF__.
Referenced by BuffList::addBuff().
bool Buff::isSpiceBuff ()
Definition at line 557 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::isSpiceBuff(), and RPC_ISSPICEBUFF__.
Referenced by BuffList::addBuff(), and BuffList::removeBuff().
void Buff::loadBuffDurationEvent (CreatureObject * creo)
Definition at line 61 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::loadBuffDurationEvent(), and RPC_LOADBUFFDURATIONEVENT__CREATUREOBJECT_.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase().
void Buff::notifyLoadFromDatabase ()
Gets called when this objects is loaded from database
Precondition
{ this locked }
Postcondition
{ this locked }
Definition at line 48 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::notifyLoadFromDatabase(), and RPC_NOTIFYLOADFROMDATABASE__.
void Buff::parseAttributeModifierString (const String & modifierstring)
Definition at line 296 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::parseAttributeModifierString(), and RPC_PARSEATTRIBUTEMODIFIERSTRING__STRING_.
void Buff::parseSkillModifierString (const String & modifierstring)
Definition at line 310 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::parseSkillModifierString(), and RPC_PARSESKILLMODIFIERSTRING__STRING_.
void Buff::removeAttributeModifiers ()
Definition at line 218 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::removeAttributeModifiers(), and RPC_REMOVEATTRIBUTEMODIFIERS__.
void Buff::removeSkillModifiers ()
Definition at line 231 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::removeSkillModifiers(), and RPC_REMOVESKILLMODIFIERS__.
void Buff::removeStates ()
Definition at line 244 of file Buff.cpp.
References _getImplementation(), server::zone::objects::creature::buffs::BuffImplementation::removeStates(), and RPC_REMOVESTATES__.
void Buff::scheduleBuffEvent ()
Definition at line 283 of file Buff.cpp.
References _getImplementation(), RPC_SCHEDULEBUFFEVENT__, and server::zone::objects::creature::buffs::BuffImplementation::scheduleBuffEvent().
void Buff::sendDestroyTo (CreatureObject * player)
Definition at line 102 of file Buff.cpp.
References _getImplementation(), RPC_SENDDESTROYTO__CREATUREOBJECT_, and server::zone::objects::creature::buffs::BuffImplementation::sendDestroyTo().
Referenced by BuffList::sendDestroyTo().
void Buff::sendTo (CreatureObject * player)
Definition at line 88 of file Buff.cpp.
References _getImplementation(), RPC_SENDTO__CREATUREOBJECT_, and server::zone::objects::creature::buffs::BuffImplementation::sendTo().
Referenced by BuffList::sendTo().
void Buff::setAccelerationMultiplierMod (float multiplier)
Definition at line 425 of file Buff.cpp.
References _getImplementation(), RPC_SETACCELERATIONMULTIPLIERMOD__FLOAT_, and server::zone::objects::creature::buffs::BuffImplementation::setAccelerationMultiplierMod().
void Buff::setAttributeModifier (byte attribute, int value)
Definition at line 367 of file Buff.cpp.
References _getImplementation(), RPC_SETATTRIBUTEMODIFIER__BYTE_INT_, and server::zone::objects::creature::buffs::BuffImplementation::setAttributeModifier().
Referenced by CombatQueueCommand::applyEffect(), ForceOfWillCommand::doDowner(), server::zone::objects::creature::buffs::SpiceBuffImplementation::setDownerAttributes(), and server::zone::objects::tangible::consumable::ConsumableImplementation::setModifiers().
void Buff::setBuffEventNull ()
Definition at line 270 of file Buff.cpp.
References _getImplementation(), RPC_SETBUFFEVENTNULL__, and server::zone::objects::creature::buffs::BuffImplementation::setBuffEventNull().
void Buff::setEndFlyText (const String & file, const String & aux, byte red, byte green, byte blue)
Definition at line 619 of file Buff.cpp.
References _getImplementation(), RPC_SETENDFLYTEXT__STRING_STRING_BYTE_BYTE_BYTE_, and server::zone::objects::creature::buffs::BuffImplementation::setEndFlyText().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::setIntimidatedState().
void Buff::setEndMessage (StringIdChatParameter & end)
Definition at line 592 of file Buff.cpp.
References _getImplementation(), and server::zone::objects::creature::buffs::BuffImplementation::setEndMessage().
void Buff::setFillAttributesOnBuff (bool val)
Definition at line 439 of file Buff.cpp.
References _getImplementation(), RPC_SETFILLATTRIBUTESONBUFF__BOOL_, and server::zone::objects::creature::buffs::BuffImplementation::setFillAttributesOnBuff().
void Buff::setSkillModifier (const String & modname, int value)
Definition at line 382 of file Buff.cpp.
References _getImplementation(), RPC_SETSKILLMODIFIER__STRING_INT_, and server::zone::objects::creature::buffs::BuffImplementation::setSkillModifier().
Referenced by server::zone::objects::group::GroupObjectImplementation::addGroupModifiers(), server::zone::managers::player::PlayerManagerImplementation::healEnhance(), server::zone::objects::creature::CreatureObjectImplementation::setAimingState(), server::zone::objects::creature::CreatureObjectImplementation::setIntimidatedState(), and server::zone::objects::tangible::consumable::ConsumableImplementation::setModifiers().
void Buff::setSpeedMultiplierMod (float multiplier)
Definition at line 411 of file Buff.cpp.
References _getImplementation(), RPC_SETSPEEDMULTIPLIERMOD__FLOAT_, and server::zone::objects::creature::buffs::BuffImplementation::setSpeedMultiplierMod().
void Buff::setStartFlyText (const String & file, const String & aux, byte red, byte green, byte blue)
Definition at line 601 of file Buff.cpp.
References _getImplementation(), RPC_SETSTARTFLYTEXT__STRING_STRING_BYTE_BYTE_BYTE_, and server::zone::objects::creature::buffs::BuffImplementation::setStartFlyText().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::setBerserkedState(), server::zone::objects::creature::CreatureObjectImplementation::setBlindedState(), server::zone::objects::creature::CreatureObjectImplementation::setCoverState(), server::zone::objects::creature::CreatureObjectImplementation::setDizziedState(), server::zone::objects::creature::CreatureObjectImplementation::setIntimidatedState(), server::zone::objects::creature::CreatureObjectImplementation::setRalliedState(), server::zone::objects::creature::CreatureObjectImplementation::setRootedState(), server::zone::objects::creature::CreatureObjectImplementation::setSnaredState(), and server::zone::objects::creature::CreatureObjectImplementation::setStunnedState().
void Buff::setStartMessage (StringIdChatParameter & start)
Definition at line 583 of file Buff.cpp.
References _getImplementation(), and server::zone::objects::creature::buffs::BuffImplementation::setStartMessage().
Friends And Related Function Documentation
friend class BuffHelper friend
Definition at line 189 of file Buff.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/Buff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/Buff.cpp