Core3: server::zone::managers::city::CityManager Class Reference
server::zone::managers::city::CityManager Class Reference
#include <CityManager.h>
Public Member Functions
CityManager (ZoneServer *zserv)
void loadLuaConfig ()
void loadCityRegions ()
bool validateCityName (const String &name)
bool isCityInRange (Zone *zone, float x, float y)
CityRegion * createCity (CreatureObject *mayor, const String &cityName, float x, float y)
void processCityUpdate (CityRegion *city)
void processIncomeTax (CityRegion *city)
void updateCityVoting (CityRegion *city, bool override=false)
void deductCityMaintenance (CityRegion *city)
int collectNonStructureMaintenance (SceneObject *object, CityRegion *city, int maintenanceDue)
int collectCivicStructureMaintenance (StructureObject *structure, CityRegion *city, int maintenanceDue)
void sendMaintenanceEmail (CityRegion *city, int maintenancePaid)
void sendMaintenanceDecayEmail (CityRegion *city, StructureObject *structure, int maintenanceDue)
void sendMaintenanceDestroyEmail (CityRegion *city, StructureObject *structure)
void sendMaintenanceRepairEmail (CityRegion *city, StructureObject *structure)
void contractCity (CityRegion *city)
void expandCity (CityRegion *city)
void destroyCity (CityRegion *city)
void sendStatusReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void promptCitySpecialization (CityRegion *city, CreatureObject *mayor, SceneObject *terminal=NULL)
void changeCitySpecialization (CityRegion *city, CreatureObject *mayor, const String &spec)
void promptWithdrawCityTreasury (CityRegion *city, CreatureObject *mayor, SceneObject *terminal=NULL)
void promptDepositCityTreasury (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void withdrawFromCityTreasury (CityRegion *city, CreatureObject *mayor, int value, const String &reason, SceneObject *terminal=NULL)
void depositToCityTreasury (CityRegion *city, CreatureObject *creature, int value)
void sendTreasuryReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void sendCitizenshipReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void registerCitizen (CityRegion *city, CreatureObject *creature)
void unregisterCitizen (CityRegion *city, CreatureObject *creature, bool inactive=false)
void sendManageMilitia (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void promptAddMilitiaMember (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void addMilitiaMember (CityRegion *city, CreatureObject *mayor, const String &playerName)
void removeMilitiaMember (CityRegion *city, CreatureObject *mayor, unsigned long long militiaid)
void sendCityAdvancement (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void promptRegisterCity (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void promptUnregisterCity (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void registerCity (CityRegion *city, CreatureObject *mayor)
void unregisterCity (CityRegion *city, CreatureObject *mayor)
void promptAdjustTaxes (CityRegion *city, CreatureObject *mayor, SceneObject *terminal=NULL)
void promptSetTax (CityRegion *city, CreatureObject *mayor, int selectedTax, SceneObject *terminal=NULL)
void setTax (CityRegion *city, CreatureObject *mayor, int selectedTax, int value)
void sendMaintenanceReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void sendMail (CityRegion *city, const String &sender, const UnicodeString &subject, StringIdChatParameter &params, WaypointObject *waypoint)
bool containsCityName (const String &name)
bool isCityRankCapped (const String &planetName, byte cityRank)
void sendCityReport (CreatureObject *creature, const String &planetName, byte rank)
bool validateCityInRange (CreatureObject *creature, Zone *zone, float x, float y)
void toggleZoningEnabled (CityRegion *city, CreatureObject *mayor)
int getTotalCities ()
bool renameCity (CityRegion *city, const String &newName)
void sendMayoralStandings (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void promptMayoralVote (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void registerForMayoralRace (CityRegion *city, CreatureObject *creature)
void castMayoralVote (CityRegion *city, CreatureObject *creature, unsigned long long oid)
void sendStructureReport (CityRegion *city, CreatureObject *creature, SceneObject *terminal=NULL)
void fixMayor (CityRegion *city, CreatureObject *mayor)
bool canSupportMoreDecorations (CityRegion *city)
CitySpecialization * getCitySpecialization (const String &cityspec)
CityTax * getCityTax (int idx)
void sendChangeCityName (CityRegion *city, CreatureObject *mayor)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const byte CLIENT = 0
static const byte OUTPOST = 1
static const byte VILLAGE = 2
static const byte TOWNSHIP = 3
static const byte CITY = 4
static const byte METROPOLIS = 5
Protected Member Functions
CityManager (DummyConstructorParameter *param)
virtual ~CityManager ()
Friends
class CityManagerHelper
Detailed Description
Definition at line 143 of file CityManager.h.
Constructor & Destructor Documentation
CityManager::CityManager (ZoneServer * zserv)
Definition at line 29 of file CityManager.cpp.
References server::zone::managers::city::CityManagerImplementation::_setStub().
CityManager::CityManager (DummyConstructorParameter * param) protected
Definition at line 36 of file CityManager.cpp.
CityManager::~CityManager () protected virtual
Definition at line 40 of file CityManager.cpp.
Member Function Documentation
DistributedObjectServant * CityManager::_getImplementation ()
Definition at line 950 of file CityManager.cpp.
Referenced by addMilitiaMember(), canSupportMoreDecorations(), castMayoralVote(), changeCitySpecialization(), collectCivicStructureMaintenance(), collectNonStructureMaintenance(), containsCityName(), contractCity(), createCity(), deductCityMaintenance(), depositToCityTreasury(), destroyCity(), expandCity(), fixMayor(), getCitySpecialization(), getCityTax(), getTotalCities(), isCityInRange(), isCityRankCapped(), loadCityRegions(), loadLuaConfig(), processCityUpdate(), processIncomeTax(), promptAddMilitiaMember(), promptAdjustTaxes(), promptCitySpecialization(), promptDepositCityTreasury(), promptMayoralVote(), promptRegisterCity(), promptSetTax(), promptUnregisterCity(), promptWithdrawCityTreasury(), registerCitizen(), registerCity(), registerForMayoralRace(), removeMilitiaMember(), renameCity(), sendChangeCityName(), sendCitizenshipReport(), sendCityAdvancement(), sendCityReport(), sendMail(), sendMaintenanceDecayEmail(), sendMaintenanceDestroyEmail(), sendMaintenanceEmail(), sendMaintenanceRepairEmail(), sendMaintenanceReport(), sendManageMilitia(), sendMayoralStandings(), sendStatusReport(), sendStructureReport(), sendTreasuryReport(), setTax(), toggleZoningEnabled(), unregisterCitizen(), unregisterCity(), updateCityVoting(), validateCityInRange(), validateCityName(), and withdrawFromCityTreasury().
DistributedObjectServant * CityManager::_getImplementationForRead ()
Definition at line 956 of file CityManager.cpp.
void CityManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 960 of file CityManager.cpp.
void CityManager::addMilitiaMember (CityRegion * city, CreatureObject * mayor, const String & playerName)
Definition at line 519 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::addMilitiaMember(), and RPC_ADDMILITIAMEMBER__CITYREGION_CREATUREOBJECT_STRING_.
Referenced by CityAddMilitiaMemberSuiCallback::run().
bool CityManager::canSupportMoreDecorations (CityRegion * city)
Definition at line 903 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::canSupportMoreDecorations(), and RPC_CANSUPPORTMOREDECORATIONS__CITYREGION_.
Referenced by CityDecorationTask::placeDecoration(), and PlaceDecorationComponent::placeStructure().
void CityManager::castMayoralVote (CityRegion * city, CreatureObject * creature, unsigned long long oid)
Definition at line 856 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::castMayoralVote(), and RPC_CASTMAYORALVOTE__CITYREGION_CREATUREOBJECT_LONG_.
Referenced by CityMayoralVoteSuiCallback::run().
void CityManager::changeCitySpecialization (CityRegion * city, CreatureObject * mayor, const String & spec)
Definition at line 342 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::changeCitySpecialization(), and RPC_CHANGECITYSPECIALIZATION__CITYREGION_CREATUREOBJECT_STRING_.
Referenced by server::zone::objects::player::sessions::CitySpecializationSessionImplementation::acceptChoice().
int CityManager::collectCivicStructureMaintenance (StructureObject * structure, CityRegion * city, int maintenanceDue)
Definition at line 191 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::collectCivicStructureMaintenance(), and RPC_COLLECTCIVICSTRUCTUREMAINTENANCE__STRUCTUREOBJECT_CITYREGION_INT_.
int CityManager::collectNonStructureMaintenance (SceneObject * object, CityRegion * city, int maintenanceDue)
Definition at line 175 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::collectNonStructureMaintenance(), and RPC_COLLECTNONSTRUCTUREMAINTENANCE__SCENEOBJECT_CITYREGION_INT_.
bool CityManager::containsCityName (const String & name)
Definition at line 704 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::containsCityName(), and RPC_CONTAINSCITYNAME__STRING_.
void CityManager::contractCity (CityRegion * city)
Definition at line 268 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::contractCity(), and RPC_CONTRACTCITY__CITYREGION_.
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
CityRegion * CityManager::createCity (CreatureObject * mayor, const String & cityName, float x, float y)
Definition at line 101 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::createCity(), and RPC_CREATECITY__CREATUREOBJECT_STRING_FLOAT_FLOAT_.
Referenced by PlaceCityHallSuiCallback::run().
void CityManager::deductCityMaintenance (CityRegion * city)
Definition at line 161 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), and RPC_DEDUCTCITYMAINTENANCE__CITYREGION_.
void CityManager::depositToCityTreasury (CityRegion * city, CreatureObject * creature, int value)
Definition at line 408 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::depositToCityTreasury(), and RPC_DEPOSITTOCITYTREASURY__CITYREGION_CREATUREOBJECT_INT_.
Referenced by CityTreasuryDepositSuiCallback::run().
void CityManager::destroyCity (CityRegion * city)
Definition at line 296 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::destroyCity(), and RPC_DESTROYCITY__CITYREGION_.
Referenced by CityHallZoneComponent::destroyObjectFromWorld().
void CityManager::expandCity (CityRegion * city)
Definition at line 282 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::expandCity(), and RPC_EXPANDCITY__CITYREGION_.
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::fixMayor (CityRegion * city, CreatureObject * mayor)
Definition at line 888 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::fixMayor(), and RPC_FIXMAYOR__CITYREGION_CREATUREOBJECT_.
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
CitySpecialization * CityManager::getCitySpecialization (const String & cityspec)
Definition at line 917 of file CityManager.cpp.
References _getImplementation(), and server::zone::managers::city::CityManagerImplementation::getCitySpecialization().
Referenced by server::zone::objects::region::CityRegionImplementation::applySpecializationModifiers().
CityTax * CityManager::getCityTax (int idx)
Definition at line 926 of file CityManager.cpp.
References _getImplementation(), and server::zone::managers::city::CityManagerImplementation::getCityTax().
int CityManager::getTotalCities ()
Definition at line 781 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::getTotalCities(), and RPC_GETTOTALCITIES__.
bool CityManager::isCityInRange (Zone * zone, float x, float y)
Definition at line 85 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::isCityInRange(), and RPC_ISCITYINRANGE__ZONE_FLOAT_FLOAT_.
bool CityManager::isCityRankCapped (const String & planetName, byte cityRank)
Definition at line 718 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::isCityRankCapped(), and RPC_ISCITYRANKCAPPED__STRING_BYTE_.
Referenced by PlaceCityHallComponent::placeStructure().
void CityManager::loadCityRegions ()
Definition at line 58 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::loadCityRegions(), and RPC_LOADCITYREGIONS__.
void CityManager::loadLuaConfig ()
Loads configuration settings for cities from the lua for the city manager.
Definition at line 45 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::loadLuaConfig(), and RPC_LOADLUACONFIG__.
void CityManager::processCityUpdate (CityRegion * city)
Definition at line 118 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::processCityUpdate(), and RPC_PROCESSCITYUPDATE__CITYREGION_.
Referenced by CityManagementMenuComponent::handleObjectMenuSelect(), and server::zone::objects::region::events::CityUpdateEvent::run().
void CityManager::processIncomeTax (CityRegion * city)
Processes income tax from all citizens
Precondition
city locked
Postcondition
city locked
Definition at line 132 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::processIncomeTax(), and RPC_PROCESSINCOMETAX__CITYREGION_.
void CityManager::promptAddMilitiaMember (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 503 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::promptAddMilitiaMember(), and RPC_PROMPTADDMILITIAMEMBER__CITYREGION_CREATUREOBJECT_SCENEOBJECT_.
Referenced by CityManageMilitiaSuiCallback::run().
void CityManager::promptAdjustTaxes (CityRegion * city, CreatureObject * mayor, SceneObject * terminal = NULL)
Definition at line 629 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::promptAdjustTaxes(), and RPC_PROMPTADJUSTTAXES__CITYREGION_CREATUREOBJECT_SCENEOBJECT_.
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::promptCitySpecialization (CityRegion * city, CreatureObject * mayor, SceneObject * terminal = NULL)
Definition at line 326 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::promptCitySpecialization(), and RPC_PROMPTCITYSPECIALIZATION__CITYREGION_CREATUREOBJECT_SCENEOBJECT_.
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::promptDepositCityTreasury (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 374 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::promptDepositCityTreasury(), and RPC_PROMPTDEPOSITCITYTREASURY__CITYREGION_CREATUREOBJECT_SCENEOBJECT_.
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::promptMayoralVote (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Precondition
city locked, creature locked, sceneObject locked
Postcondition
city locked, creature locked, sceneObject locked
Definition at line 825 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::promptMayoralVote(), and RPC_PROMPTMAYORALVOTE__CITYREGION_CREATUREOBJECT_SCENEOBJECT_.
Referenced by CityVotingMenuComponent::handleObjectMenuSelect().
void CityManager::promptRegisterCity (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 567 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::promptRegisterCity(), and RPC_PROMPTREGISTERCITY__CITYREGION_CREATUREOBJECT_SCENEOBJECT_.
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::promptSetTax (CityRegion * city, CreatureObject * mayor, int selectedTax, SceneObject * terminal = NULL)
Definition at line 645 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::promptSetTax(), and RPC_PROMPTSETTAX__CITYREGION_CREATUREOBJECT_INT_SCENEOBJECT_.
Referenced by CityAdjustTaxSuiCallback::run().
void CityManager::promptUnregisterCity (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 583 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::promptUnregisterCity(), and RPC_PROMPTUNREGISTERCITY__CITYREGION_CREATUREOBJECT_SCENEOBJECT_.
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::promptWithdrawCityTreasury (CityRegion * city, CreatureObject * mayor, SceneObject * terminal = NULL)
Definition at line 358 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::promptWithdrawCityTreasury(), and RPC_PROMPTWITHDRAWCITYTREASURY__CITYREGION_CREATUREOBJECT_SCENEOBJECT_.
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::registerCitizen (CityRegion * city, CreatureObject * creature)
Definition at line 456 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::registerCitizen(), and RPC_REGISTERCITIZEN__CITYREGION_CREATUREOBJECT_.
Referenced by StructureManager::declareResidence().
void CityManager::registerCity (CityRegion * city, CreatureObject * mayor)
Definition at line 599 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::registerCity(), and RPC_REGISTERCITY__CITYREGION_CREATUREOBJECT_.
Referenced by RenameCitySuiCallback::run(), and CityRegisterSuiCallback::run().
void CityManager::registerForMayoralRace (CityRegion * city, CreatureObject * creature)
Precondition
city locked, creature locked
Postcondition
city locked, creature locked
Definition at line 841 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), and RPC_REGISTERFORMAYORALRACE__CITYREGION_CREATUREOBJECT_.
Referenced by CityVotingMenuComponent::handleObjectMenuSelect().
void CityManager::removeMilitiaMember (CityRegion * city, CreatureObject * mayor, unsigned long long militiaid)
Definition at line 535 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::removeMilitiaMember(), and RPC_REMOVEMILITIAMEMBER__CITYREGION_CREATUREOBJECT_LONG_.
Referenced by CityRemoveMilitiaMemberSuiCallback::run().
bool CityManager::renameCity (CityRegion * city, const String & newName)
Definition at line 794 of file CityManager.cpp.
References _getImplementation(), server::zone::managers::city::CityManagerImplementation::renameCity(), and RPC_RENAMECITY__CITYREGION_STRING_.
Referenced by RenameCitySuiCallback::run().
void CityManager::sendChangeCityName (CityRegion * city, CreatureObject * mayor)
Definition at line 935 of file CityManager.cpp.
References _getImplementation(), RPC_SENDCHANGECITYNAME__CITYREGION_CREATUREOBJECT_, and server::zone::managers::city::CityManagerImplementation::sendChangeCityName().
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::sendCitizenshipReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 440 of file CityManager.cpp.
References _getImplementation(), RPC_SENDCITIZENSHIPREPORT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::city::CityManagerImplementation::sendCitizenshipReport().
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::sendCityAdvancement (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 551 of file CityManager.cpp.
References _getImplementation(), RPC_SENDCITYADVANCEMENT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::city::CityManagerImplementation::sendCityAdvancement().
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::sendCityReport (CreatureObject * creature, const String & planetName, byte rank)
Definition at line 733 of file CityManager.cpp.
References _getImplementation(), RPC_SENDCITYREPORT__CREATUREOBJECT_STRING_BYTE_, and server::zone::managers::city::CityManagerImplementation::sendCityReport().
Referenced by CityReportCommand::executeCommand().
void CityManager::sendMail (CityRegion * city, const String & sender, const UnicodeString & subject, StringIdChatParameter & params, WaypointObject * waypoint)
Definition at line 695 of file CityManager.cpp.
References _getImplementation(), and server::zone::managers::city::CityManagerImplementation::sendMail().
void CityManager::sendMaintenanceDecayEmail (CityRegion * city, StructureObject * structure, int maintenanceDue)
Definition at line 222 of file CityManager.cpp.
References _getImplementation(), RPC_SENDMAINTENANCEDECAYEMAIL__CITYREGION_STRUCTUREOBJECT_INT_, and server::zone::managers::city::CityManagerImplementation::sendMaintenanceDecayEmail().
void CityManager::sendMaintenanceDestroyEmail (CityRegion * city, StructureObject * structure)
Definition at line 238 of file CityManager.cpp.
References _getImplementation(), RPC_SENDMAINTENANCEDESTROYEMAIL__CITYREGION_STRUCTUREOBJECT_, and server::zone::managers::city::CityManagerImplementation::sendMaintenanceDestroyEmail().
void CityManager::sendMaintenanceEmail (CityRegion * city, int maintenancePaid)
Definition at line 207 of file CityManager.cpp.
References _getImplementation(), RPC_SENDMAINTENANCEEMAIL__CITYREGION_INT_, and server::zone::managers::city::CityManagerImplementation::sendMaintenanceEmail().
void CityManager::sendMaintenanceRepairEmail (CityRegion * city, StructureObject * structure)
Definition at line 253 of file CityManager.cpp.
References _getImplementation(), RPC_SENDMAINTENANCEREPAIREMAIL__CITYREGION_STRUCTUREOBJECT_, and server::zone::managers::city::CityManagerImplementation::sendMaintenanceRepairEmail().
void CityManager::sendMaintenanceReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 679 of file CityManager.cpp.
References _getImplementation(), RPC_SENDMAINTENANCEREPORT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport().
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::sendManageMilitia (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 487 of file CityManager.cpp.
References _getImplementation(), RPC_SENDMANAGEMILITIA__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::city::CityManagerImplementation::sendManageMilitia().
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::sendMayoralStandings (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Precondition
city locked, creature locked, sceneObject locked
Postcondition
city locked, creature locked, sceneObject locked
Definition at line 809 of file CityManager.cpp.
References _getImplementation(), RPC_SENDMAYORALSTANDINGS__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::city::CityManagerImplementation::sendMayoralStandings().
Referenced by CityVotingMenuComponent::handleObjectMenuSelect().
void CityManager::sendStatusReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 310 of file CityManager.cpp.
References _getImplementation(), RPC_SENDSTATUSREPORT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::city::CityManagerImplementation::sendStatusReport().
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::sendStructureReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 872 of file CityManager.cpp.
References _getImplementation(), RPC_SENDSTRUCTUREREPORT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::city::CityManagerImplementation::sendStructureReport().
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::sendTreasuryReport (CityRegion * city, CreatureObject * creature, SceneObject * terminal = NULL)
Definition at line 424 of file CityManager.cpp.
References _getImplementation(), RPC_SENDTREASURYREPORT__CITYREGION_CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::city::CityManagerImplementation::sendTreasuryReport().
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::setTax (CityRegion * city, CreatureObject * mayor, int selectedTax, int value)
Definition at line 662 of file CityManager.cpp.
References _getImplementation(), RPC_SETTAX__CITYREGION_CREATUREOBJECT_INT_INT_, and server::zone::managers::city::CityManagerImplementation::setTax().
Referenced by CitySetTaxSuiCallback::run().
void CityManager::toggleZoningEnabled (CityRegion * city, CreatureObject * mayor)
Definition at line 766 of file CityManager.cpp.
References _getImplementation(), RPC_TOGGLEZONINGENABLED__CITYREGION_CREATUREOBJECT_, and server::zone::managers::city::CityManagerImplementation::toggleZoningEnabled().
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
void CityManager::unregisterCitizen (CityRegion * city, CreatureObject * creature, bool inactive = false)
Definition at line 471 of file CityManager.cpp.
References _getImplementation(), RPC_UNREGISTERCITIZEN__CITYREGION_CREATUREOBJECT_BOOL_, and server::zone::managers::city::CityManagerImplementation::unregisterCitizen().
Referenced by StructureManager::declareResidence().
void CityManager::unregisterCity (CityRegion * city, CreatureObject * mayor)
Definition at line 614 of file CityManager.cpp.
References _getImplementation(), RPC_UNREGISTERCITY__CITYREGION_CREATUREOBJECT_, and server::zone::managers::city::CityManagerImplementation::unregisterCity().
Referenced by RenameCitySuiCallback::run(), and CityRegisterSuiCallback::run().
void CityManager::updateCityVoting (CityRegion * city, bool override = false)
Handles the voting of the city, tallys votes, see's who won. Resets the voting process.
Precondition
city locked
Postcondition
city locked
Definition at line 146 of file CityManager.cpp.
References _getImplementation(), RPC_UPDATECITYVOTING__CITYREGION_BOOL_, and server::zone::managers::city::CityManagerImplementation::updateCityVoting().
Referenced by CityManagementMenuComponent::handleObjectMenuSelect().
bool CityManager::validateCityInRange (CreatureObject * creature, Zone * zone, float x, float y)
Definition at line 749 of file CityManager.cpp.
References _getImplementation(), RPC_VALIDATECITYINRANGE__CREATUREOBJECT_ZONE_FLOAT_FLOAT_, and server::zone::managers::city::CityManagerImplementation::validateCityInRange().
Referenced by PlaceCityHallSuiCallback::run().
bool CityManager::validateCityName (const String & name)
Definition at line 71 of file CityManager.cpp.
References _getImplementation(), RPC_VALIDATECITYNAME__STRING_, and server::zone::managers::city::CityManagerImplementation::validateCityName().
Referenced by PlaceCityHallSuiCallback::run().
void CityManager::withdrawFromCityTreasury (CityRegion * city, CreatureObject * mayor, int value, const String & reason, SceneObject * terminal = NULL)
Definition at line 390 of file CityManager.cpp.
References _getImplementation(), RPC_WITHDRAWFROMCITYTREASURY__CITYREGION_CREATUREOBJECT_INT_STRING_SCENEOBJECT_, and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
Referenced by server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::withdrawCredits().
Friends And Related Function Documentation
friend class CityManagerHelper friend
Definition at line 314 of file CityManager.h.
Member Data Documentation
const byte server::zone::managers::city::CityManager::CITY = 4 static
Definition at line 153 of file CityManager.h.
const byte server::zone::managers::city::CityManager::CLIENT = 0 static
Definition at line 145 of file CityManager.h.
const byte server::zone::managers::city::CityManager::METROPOLIS = 5 static
Definition at line 155 of file CityManager.h.
const byte server::zone::managers::city::CityManager::OUTPOST = 1 static
Definition at line 147 of file CityManager.h.
const byte server::zone::managers::city::CityManager::TOWNSHIP = 3 static
Definition at line 151 of file CityManager.h.
const byte server::zone::managers::city::CityManager::VILLAGE = 2 static
Definition at line 149 of file CityManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/city/CityManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/city/CityManager.cpp