Core3: server::zone::ZoneClientSession Class Reference
server::zone::ZoneClientSession Class Reference
#include <ZoneClientSession.h>
Public Member Functions
ZoneClientSession (BaseClientProxy *session)
void disconnect ()
void disconnect (bool doLock)
void sendMessage (BasePacket *msg)
void balancePacketCheckupTime ()
void resetPacketCheckupTime ()
void closeConnection (bool lockPlayer, bool doLock=true)
void info (const String &msg, bool force=false)
void error (const String &msg)
String getAddress ()
void setPlayer (SceneObject *playerCreature)
void setSessionID (unsigned int id)
void setAccountID (unsigned int acc)
int getCommandCount ()
void increaseCommandCount ()
void resetCommandCount ()
Time * getCommandSpamCooldown ()
BaseClientProxy * getSession ()
ManagedWeakReference
< SceneObject * > getPlayer ()
unsigned int getSessionID ()
unsigned int getAccountID ()
bool hasCharacter (unsigned long long cid, unsigned int galaxyId)
void addCharacter (unsigned long long cid, unsigned int galaxyId)
void addBannedCharacter (unsigned long long cid, unsigned int galaxyId)
int getCharacterCount ()
int getCharacterCount (int galaxyId)
void resetCharacters ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ZoneClientSession (DummyConstructorParameter *param)
virtual ~ZoneClientSession ()
Friends
class ZoneClientSessionHelper
Detailed Description
Definition at line 71 of file ZoneClientSession.h.
Constructor & Destructor Documentation
ZoneClientSession::ZoneClientSession (BaseClientProxy * session)
Definition at line 17 of file ZoneClientSession.cpp.
References server::zone::ZoneClientSessionImplementation::_setStub().
ZoneClientSession::ZoneClientSession (DummyConstructorParameter * param) protected
Definition at line 24 of file ZoneClientSession.cpp.
ZoneClientSession::~ZoneClientSession () protected virtual
Definition at line 28 of file ZoneClientSession.cpp.
Member Function Documentation
DistributedObjectServant * ZoneClientSession::_getImplementation ()
Definition at line 382 of file ZoneClientSession.cpp.
Referenced by addBannedCharacter(), addCharacter(), balancePacketCheckupTime(), closeConnection(), disconnect(), error(), getAccountID(), getAddress(), getCharacterCount(), getCommandCount(), getCommandSpamCooldown(), getPlayer(), getSession(), getSessionID(), hasCharacter(), increaseCommandCount(), info(), resetCharacters(), resetCommandCount(), resetPacketCheckupTime(), sendMessage(), setAccountID(), setPlayer(), and setSessionID().
DistributedObjectServant * ZoneClientSession::_getImplementationForRead ()
Definition at line 388 of file ZoneClientSession.cpp.
void ZoneClientSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 392 of file ZoneClientSession.cpp.
void ZoneClientSession::addBannedCharacter (unsigned long long cid, unsigned int galaxyId)
Definition at line 327 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::addBannedCharacter(), and RPC_ADDBANNEDCHARACTER__LONG_INT_.
void ZoneClientSession::addCharacter (unsigned long long cid, unsigned int galaxyId)
Definition at line 312 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::addCharacter(), and RPC_ADDCHARACTER__LONG_INT_.
void ZoneClientSession::balancePacketCheckupTime ()
Definition at line 74 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::balancePacketCheckupTime(), and RPC_BALANCEPACKETCHECKUPTIME__.
void ZoneClientSession::closeConnection (bool lockPlayer, bool doLock = true)
Definition at line 100 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::closeConnection(), and RPC_CLOSECONNECTION__BOOL_BOOL_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::disconnect(), and server::zone::objects::player::PlayerObjectImplementation::doRecovery().
void ZoneClientSession::disconnect ()
Definition at line 33 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::disconnect(), and RPC_DISCONNECT__.
Referenced by server::zone::ZoneHandler::deleteConnection(), server::zone::ZoneServerImplementation::handleError(), server::zone::objects::player::PlayerObjectImplementation::reload(), and SelectCharacterCallback::run().
void ZoneClientSession::disconnect (bool doLock)
Definition at line 46 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::disconnect(), and RPC_DISCONNECT__BOOL_.
void ZoneClientSession::error (const String & msg)
Definition at line 130 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::error(), and RPC_ERROR__STRING_.
unsigned int ZoneClientSession::getAccountID ()
Definition at line 284 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::getAccountID(), and RPC_GETACCOUNTID__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::decreaseOnlineCharCount(), server::zone::managers::holocron::HolocronManager::getReporterId(), and server::zone::managers::player::PlayerManagerImplementation::increaseOnlineCharCountIfPossible().
String ZoneClientSession::getAddress ()
Definition at line 144 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::getAddress(), and RPC_GETADDRESS__.
int ZoneClientSession::getCharacterCount ()
Definition at line 342 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::getCharacterCount(), and RPC_GETCHARACTERCOUNT__.
int ZoneClientSession::getCharacterCount (int galaxyId)
Definition at line 355 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::getCharacterCount(), and RPC_GETCHARACTERCOUNT__INT_.
int ZoneClientSession::getCommandCount ()
Definition at line 201 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::getCommandCount(), and RPC_GETCOMMANDCOUNT__.
Time * ZoneClientSession::getCommandSpamCooldown ()
Definition at line 240 of file ZoneClientSession.cpp.
References _getImplementation(), and server::zone::ZoneClientSessionImplementation::getCommandSpamCooldown().
ManagedWeakReference< SceneObject * > ZoneClientSession::getPlayer ()
Definition at line 258 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::getPlayer(), and RPC_GETPLAYER__.
Referenced by server::chat::ChatManagerImplementation::handleChatInstantMessageToCharacter(), and server::zone::managers::player::PlayerManagerImplementation::increaseOnlineCharCountIfPossible().
BaseClientProxy * ZoneClientSession::getSession ()
Definition at line 249 of file ZoneClientSession.cpp.
References _getImplementation(), and server::zone::ZoneClientSessionImplementation::getSession().
Referenced by server::zone::ZoneSessionMap::add(), server::zone::ZoneHandler::createConnection(), server::zone::managers::player::PlayerManagerImplementation::decreaseOnlineCharCount(), server::zone::ZoneServerImplementation::handleError(), server::zone::ZoneServerImplementation::handleMessage(), and server::zone::managers::player::PlayerManagerImplementation::increaseOnlineCharCountIfPossible().
unsigned int ZoneClientSession::getSessionID ()
Definition at line 271 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::getSessionID(), and RPC_GETSESSIONID__.
bool ZoneClientSession::hasCharacter (unsigned long long cid, unsigned int galaxyId)
Definition at line 297 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::hasCharacter(), and RPC_HASCHARACTER__LONG_INT_.
void ZoneClientSession::increaseCommandCount ()
Definition at line 214 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::increaseCommandCount(), and RPC_INCREASECOMMANDCOUNT__.
void ZoneClientSession::info (const String & msg, bool force = false)
Definition at line 115 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::info(), and RPC_INFO__STRING_BOOL_.
void ZoneClientSession::resetCharacters ()
Definition at line 369 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::resetCharacters(), and RPC_RESETCHARACTERS__.
void ZoneClientSession::resetCommandCount ()
Definition at line 227 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::resetCommandCount(), and RPC_RESETCOMMANDCOUNT__.
void ZoneClientSession::resetPacketCheckupTime ()
Definition at line 87 of file ZoneClientSession.cpp.
References _getImplementation(), server::zone::ZoneClientSessionImplementation::resetPacketCheckupTime(), and RPC_RESETPACKETCHECKUPTIME__.
void ZoneClientSession::sendMessage (BasePacket * msg)
Definition at line 60 of file ZoneClientSession.cpp.
References _getImplementation(), RPC_SENDMESSAGE__BASEPACKET_, and server::zone::ZoneClientSessionImplementation::sendMessage().
Referenced by server::zone::objects::scene::SceneObjectImplementation::broadcastMessagePrivate(), server::zone::objects::group::GroupObjectImplementation::sendBaselinesTo(), and server::zone::managers::holocron::HolocronManager::sendRequestCategoriesResponseTo().
void ZoneClientSession::setAccountID (unsigned int acc)
Definition at line 187 of file ZoneClientSession.cpp.
References _getImplementation(), RPC_SETACCOUNTID__INT_, and server::zone::ZoneClientSessionImplementation::setAccountID().
void ZoneClientSession::setPlayer (SceneObject * playerCreature)
Definition at line 159 of file ZoneClientSession.cpp.
References _getImplementation(), RPC_SETPLAYER__SCENEOBJECT_, and server::zone::ZoneClientSessionImplementation::setPlayer().
void ZoneClientSession::setSessionID (unsigned int id)
Definition at line 173 of file ZoneClientSession.cpp.
References _getImplementation(), RPC_SETSESSIONID__INT_, and server::zone::ZoneClientSessionImplementation::setSessionID().
Friends And Related Function Documentation
friend class ZoneClientSessionHelper friend
Definition at line 137 of file ZoneClientSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneClientSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/ZoneClientSession.cpp