Core3: ComponentSlot Class Reference
ComponentSlot Class Reference
#include <ComponentSlot.h>
Public Member Functions
ComponentSlot ()
ComponentSlot (const ComponentSlot &slot)
~ComponentSlot ()
Object * clone ()
bool add (CreatureObject *player, SceneObject *satchel, ManagedReference< TangibleObject * > incomingTano)
bool returnToParents (CreatureObject *player)
int getSlotQuantity ()
bool isFull ()
bool isEmpty ()
TangibleObject * getPrototype ()
SceneObject * getFactoryIngredient ()
bool isComponentSlot ()
Vector< uint64 > getOIDVector ()
Vector< int > getQuantityVector ()
Public Member Functions inherited from IngredientSlot
IngredientSlot ()
IngredientSlot (const IngredientSlot &slot)
~IngredientSlot ()
Object * clone ()
Object * clone (void *object)
int getClientSlotType ()
void setOptional (bool value)
bool isOptional ()
void setIdentical (bool value)
bool requiresIdentical ()
void setContentType (const String &value)
void setQuantityNeeded (int value)
int getQuantityNeeded ()
bool removeAll (CreatureObject *player)
void setSlotName (const String &name)
const String & getSlotName ()
virtual int size ()
virtual void print ()
virtual bool isResourceSlot ()
Private Attributes
VectorMap< ManagedReference
< TangibleObject * >
, ManagedReference
< SceneObject * > > contents
Indexed by <object, parent>
Additional Inherited Members
Static Public Attributes inherited from IngredientSlot
static const int RESOURCESLOT = 0
static const int IDENTICALSLOT = 1
static const int MIXEDSLOT = 2
static const int OPTIONALIDENTICALSLOT = 3
static const int OPTIONALMIXEDSLOT = 4
static const short OK = 0x00
static const short NOSERVER = 0x01
static const short NOTASSEMBLYSTAGE = 0x02
static const short NOTCUSTOMIZATIONSTAGE = 0x03
static const short NOSCHEMATIC = 0x04
static const short NOTOOL = 0x05
static const short NOMANUFACTURE = 0x06
static const short INVALID = 0x07
static const short INVALIDOPTION = 0x08
static const short INVALIDINGREDIENTSIZE = 0x09
static const short FULL = 0x0A
static const short INVALIDINGREDIENT = 0x0B
static const short INGREDIENTNOTININVENTORY = 0x0C
static const short BADCRATE = 0x0D
static const short BADRESOURCEFOR = 0x0E
static const short COMPONENTDAMAGED = 0x0F
static const short NOCOMPONENTTRANSFER = 0x10
static const short BADCOMPONENT = 0x11
static const short NOINVENTORY = 0x12
static const short BADSTATIONHOPPER = 0x13
static const short BADTARGETCONTAINER = 0x14
static const short EMPTYISEMPTY = 0x15
static const short FAILEDRESOURCECREATE = 0x16
static const short EMPTYASSEMBLE = 0x17
static const short PARTIALASSEMBLE = 0x18
static const short PROTOTYPENOTFOUND = 0x19
static const short BADNAME = 0x1A
static const short MYSTERY = 0x1B
static const short FAILEDTOTRANSFER = 0x1C
static const short WEIRDFAILEDMESSAGE = 0x1D
Protected Attributes inherited from IngredientSlot
String slotName
String contentType
int requiredQuantity
bool identical
bool optional
short clientSlotType
Detailed Description
Definition at line 53 of file ComponentSlot.h.
Constructor & Destructor Documentation
ComponentSlot::ComponentSlot () inline
Definition at line 60 of file ComponentSlot.h.
References IngredientSlot::clientSlotType.
Referenced by clone().
ComponentSlot::ComponentSlot (const ComponentSlot & slot) inline
Definition at line 65 of file ComponentSlot.h.
References contents.
ComponentSlot::~ComponentSlot () inline
Definition at line 72 of file ComponentSlot.h.
Member Function Documentation
bool ComponentSlot::add (CreatureObject * player, SceneObject * satchel, ManagedReference< TangibleObject * > incomingTano) inline virtual
If Full, don't add
Get template
Get prototype's template for check
Check if prototype is correct type
Check types
How much do we need
Get parent
Extract tano from crate and set it to the incoming object
Reimplemented from IngredientSlot.
Definition at line 80 of file ComponentSlot.h.
References server::zone::managers::object::ObjectManager::cloneObject(), contents, IngredientSlot::contentType, server::zone::objects::factorycrate::FactoryCrate::extractObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::factorycrate::FactoryCrate::getPrototype(), server::zone::objects::tangible::TangibleObject::getSerialNumber(), getSlotQuantity(), server::zone::objects::tangible::TangibleObject::getUseCount(), IngredientSlot::requiredQuantity, IngredientSlot::requiresIdentical(), and server::zone::objects::scene::SceneObject::transferObject().
Object* ComponentSlot::clone () inline
Definition at line 76 of file ComponentSlot.h.
References ComponentSlot().
SceneObject* ComponentSlot::getFactoryIngredient () inline virtual
Reimplemented from IngredientSlot.
Definition at line 256 of file ComponentSlot.h.
References getPrototype().
Vector<uint64> ComponentSlot::getOIDVector () inline virtual
Reimplemented from IngredientSlot.
Definition at line 264 of file ComponentSlot.h.
References getPrototype(), and getSlotQuantity().
TangibleObject* ComponentSlot::getPrototype () inline
Definition at line 248 of file ComponentSlot.h.
References contents.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), getFactoryIngredient(), getOIDVector(), and server::zone::managers::crafting::labratories::GeneticLabratory::setInitialCraftingValues().
Vector<int> ComponentSlot::getQuantityVector () inline virtual
Reimplemented from IngredientSlot.
Definition at line 275 of file ComponentSlot.h.
References getSlotQuantity().
int ComponentSlot::getSlotQuantity () inline virtual
Reimplemented from IngredientSlot.
Definition at line 230 of file ComponentSlot.h.
References contents, and server::zone::objects::tangible::TangibleObject::getUseCount().
Referenced by add(), getOIDVector(), getQuantityVector(), isEmpty(), and isFull().
bool ComponentSlot::isComponentSlot () inline virtual
Reimplemented from IngredientSlot.
Definition at line 260 of file ComponentSlot.h.
bool ComponentSlot::isEmpty () inline virtual
Reimplemented from IngredientSlot.
Definition at line 244 of file ComponentSlot.h.
References getSlotQuantity().
bool ComponentSlot::isFull () inline virtual
Reimplemented from IngredientSlot.
Definition at line 240 of file ComponentSlot.h.
References getSlotQuantity(), and IngredientSlot::requiredQuantity.
bool ComponentSlot::returnToParents (CreatureObject * player) inline virtual
Reimplemented from IngredientSlot.
Definition at line 204 of file ComponentSlot.h.
References server::zone::objects::scene::SceneObject::broadcastObject(), contents, and server::zone::objects::scene::SceneObject::transferObject().
Member Data Documentation
VectorMap<ManagedReference<TangibleObject*>, ManagedReference<SceneObject*> > ComponentSlot::contents private
Indexed by <object, parent>
Definition at line 56 of file ComponentSlot.h.
Referenced by add(), ComponentSlot(), getPrototype(), getSlotQuantity(), and returnToParents().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/ingredientslots/ComponentSlot.h