Core3: server::zone::managers::skill::SkillModManager Class Reference
server::zone::managers::skill::SkillModManager Class Reference
#include <SkillModManager.h>
Public Member Functions
SkillModManager ()
~SkillModManager ()
void verifyWearableSkillMods (CreatureObject *creature)
void verifyStructureSkillMods (TangibleObject *tano)
void verifySkillBoxSkillMods (CreatureObject *creature)
void verifyBuffSkillMods (CreatureObject *creature)
int getMinSkill (const uint32 modType)
int getMaxSkill (const uint32 modType)
Static Public Attributes
static const int PERMANENTMOD = 0x100
Permanent Mods.
static const int TEMPLATE = 0x101
static const int SKILLBOX = 0x103
From LUA templates.
static const int BONUSMOD = 0x1000
From Skills learned.
static const int WEARABLE = 0x1001
static const int STRUCTURE = 0x1002
From Wearable items.
static const int CITY = 0x1003
From Structures creature is in.
static const int TEMPORARYMOD = 0x10000
static const int BUFF = 0x10001
static const int ABILITYBONUS = 0x10002
From temporary buffs.
Private Member Functions
void init ()
void setDefaults ()
bool compareMods (VectorMap< String, int > mods, CreatureObject *creature, uint32 type)
Private Attributes
VectorMap< uint32, int > skillModMax
From CombatQueueCommands.
VectorMap< uint32, int > skillModMin
Detailed Description
Definition at line 90 of file SkillModManager.h.
Constructor & Destructor Documentation
SkillModManager::SkillModManager ()
Definition at line 54 of file SkillModManager.cpp.
References init(), skillModMax, and skillModMin.
SkillModManager::~SkillModManager ()
Definition at line 61 of file SkillModManager.cpp.
Member Function Documentation
bool SkillModManager::compareMods (VectorMap< String, int > mods, CreatureObject * creature, uint32 type) private
Definition at line 298 of file SkillModManager.cpp.
References server::zone::objects::creature::CreatureObject::addSkillMod(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), SkillModList::getSkillModGroup(), server::zone::objects::creature::CreatureObject::getSkillModList(), server::zone::objects::creature::CreatureObject::getSkillModMutex(), server::zone::objects::creature::CreatureObject::removeSkillMod(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by verifyBuffSkillMods(), verifySkillBoxSkillMods(), verifyStructureSkillMods(), and verifyWearableSkillMods().
int server::zone::managers::skill::SkillModManager::getMaxSkill (const uint32 modType) inline
Definition at line 138 of file SkillModManager.h.
int server::zone::managers::skill::SkillModManager::getMinSkill (const uint32 modType) inline
Definition at line 134 of file SkillModManager.h.
void SkillModManager::init () private
Definition at line 65 of file SkillModManager.cpp.
References setDefaults(), skillModMax, and skillModMin.
Referenced by SkillModManager().
void SkillModManager::setDefaults () private
Definition at line 104 of file SkillModManager.cpp.
References ABILITYBONUS, BUFF, skillModMax, skillModMin, STRUCTURE, and WEARABLE.
Referenced by init().
void SkillModManager::verifyBuffSkillMods (CreatureObject * creature)
Definition at line 270 of file SkillModManager.cpp.
References BUFF, compareMods(), BuffList::getBuffByIndex(), server::zone::objects::creature::CreatureObject::getBuffList(), BuffList::getBuffListSize(), server::zone::objects::creature::CreatureObject::getFirstName(), and server::zone::objects::creature::buffs::Buff::getSkillModifiers().
void SkillModManager::verifySkillBoxSkillMods (CreatureObject * creature)
Definition at line 242 of file SkillModManager.cpp.
References compareMods(), server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getSkillList(), server::zone::objects::scene::variables::DeltaVector< E >::size(), and SKILLBOX.
void SkillModManager::verifyStructureSkillMods (TangibleObject * tano)
Definition at line 195 of file SkillModManager.cpp.
References compareMods(), server::zone::objects::area::CampSiteActiveArea::getCamp(), server::zone::objects::creature::CreatureObject::getCurrentCamp(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getRootParent(), server::zone::objects::tangible::TangibleObject::getTemplateSkillMods(), server::zone::objects::scene::SceneObject::isCreatureObject(), and STRUCTURE.
void SkillModManager::verifyWearableSkillMods (CreatureObject * creature)
Definition at line 119 of file SkillModManager.cpp.
References compareMods(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getSlottedObjectsSize(), server::zone::objects::tangible::wearables::WearableContainerObject::getWearableSkillMods(), server::zone::objects::tangible::wearables::WearableObject::getWearableSkillMods(), server::zone::objects::tangible::weapon::WeaponObject::getWearableSkillMods(), and WEARABLE.
Member Data Documentation
const int server::zone::managers::skill::SkillModManager::ABILITYBONUS = 0x10002 static
From temporary buffs.
Definition at line 107 of file SkillModManager.h.
Referenced by setDefaults().
const int server::zone::managers::skill::SkillModManager::BONUSMOD = 0x1000 static
From Skills learned.
Bonus Mods
Definition at line 99 of file SkillModManager.h.
const int server::zone::managers::skill::SkillModManager::BUFF = 0x10001 static
Definition at line 106 of file SkillModManager.h.
Referenced by setDefaults(), and verifyBuffSkillMods().
const int server::zone::managers::skill::SkillModManager::CITY = 0x1003 static
From Structures creature is in.
Definition at line 102 of file SkillModManager.h.
const int server::zone::managers::skill::SkillModManager::PERMANENTMOD = 0x100 static
Permanent Mods.
Definition at line 94 of file SkillModManager.h.
const int server::zone::managers::skill::SkillModManager::SKILLBOX = 0x103 static
From LUA templates.
Definition at line 96 of file SkillModManager.h.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::skill::SkillManager::surrenderAllSkills(), server::zone::managers::skill::SkillManager::surrenderSkill(), and verifySkillBoxSkillMods().
VectorMap<uint32, int> server::zone::managers::skill::SkillModManager::skillModMax private
From CombatQueueCommands.
Definition at line 110 of file SkillModManager.h.
Referenced by init(), setDefaults(), and SkillModManager().
VectorMap<uint32, int> server::zone::managers::skill::SkillModManager::skillModMin private
Definition at line 111 of file SkillModManager.h.
Referenced by init(), setDefaults(), and SkillModManager().
const int server::zone::managers::skill::SkillModManager::STRUCTURE = 0x1002 static
From Wearable items.
Definition at line 101 of file SkillModManager.h.
Referenced by setDefaults(), and verifyStructureSkillMods().
const int server::zone::managers::skill::SkillModManager::TEMPLATE = 0x101 static
Definition at line 95 of file SkillModManager.h.
const int server::zone::managers::skill::SkillModManager::TEMPORARYMOD = 0x10000 static
Definition at line 105 of file SkillModManager.h.
const int server::zone::managers::skill::SkillModManager::WEARABLE = 0x1001 static
Definition at line 100 of file SkillModManager.h.
Referenced by setDefaults(), and verifyWearableSkillMods().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/skill/SkillModManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/skill/SkillModManager.cpp