Core3: PlaceCityHallComponent Class Reference
PlaceCityHallComponent Class Reference
#include <PlaceCityHallComponent.h>
Public Member Functions
int placeStructure (StructureDeed *deed, CreatureObject *creature, float x, float y, int angle)
int notifyStructurePlaced (StructureDeed *deed, CreatureObject *creature, StructureObject *structure)
Detailed Description
Definition at line 13 of file PlaceCityHallComponent.h.
Member Function Documentation
int PlaceCityHallComponent::notifyStructurePlaced (StructureDeed * deed, CreatureObject * creature, StructureObject * structure) virtual
Reimplemented from PlaceStructureComponent.
Definition at line 64 of file PlaceCityHallComponent.cpp.
References server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::isBuildingObject(), and PlaceStructureComponent::notifyStructurePlaced().
int PlaceCityHallComponent::placeStructure (StructureDeed * deed, CreatureObject * creature, float x, float y, int angle) virtual
Reimplemented from PlaceStructureComponent.
Definition at line 20 of file PlaceCityHallComponent.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), SuiWindowType::CITY_CREATE, server::zone::ZoneServer::getCityManager(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::player::PlayerObject::getDeclaredResidence(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::Zone::getZoneServer(), server::zone::managers::city::CityManager::isCityRankCapped(), server::zone::objects::creature::CreatureObject::sendMessage(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/deed/components/PlaceCityHallComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/deed/components/PlaceCityHallComponent.cpp