Core3: server::zone::objects::creature::conversation::DeliverMissionConversationObserverImplementation Class Reference
server::zone::objects::creature::conversation::DeliverMissionConversationObserverImplementation Class Reference
#include <DeliverMissionConversationObserver.h>
Public Member Functions
DeliverMissionConversationObserverImplementation (ConversationTemplate *conversationTemplate)
DeliverMissionConversationObserverImplementation (DummyConstructorParameter *param)
operator const DeliverMissionConversationObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
ConversationObserverImplementation (ConversationTemplate *conversationTemplate)
ConversationObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
virtual ConversationScreen * getNextConversationScreen (CreatureObject *conversingPlayer, int selectedOption, CreatureObject *conversingNPC)
virtual ConversationScreen * runScreenHandlers (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
operator const ConversationObserver * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< DeliverMissionConversationObserver * > _this
Public Attributes inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
WeakReference
< ConversationObserver * > _this
Protected Member Functions
virtual ~DeliverMissionConversationObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
virtual void createConversationSession (CreatureObject *conversingPlayer, CreatureObject *npc)
void registerScreenHandler (const String &screenId, ScreenHandler *screenHandler)
void removeScreenHandler (const String &screenId)
void createPositionObserver (CreatureObject *player)
virtual ~ConversationObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
DeliverMissionScreenHandler deliverMissionScreenHandler
Friends
class DeliverMissionConversationObserver
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::conversation::ConversationObserverImplementation
Reference< ConversationTemplate * > conversationTemplate
Detailed Description
Definition at line 61 of file DeliverMissionConversationObserver.h.
Constructor & Destructor Documentation
DeliverMissionConversationObserverImplementation::DeliverMissionConversationObserverImplementation (ConversationTemplate * conversationTemplate)
Definition at line 47 of file DeliverMissionConversationObserverImplementation.cpp.
References deliverMissionScreenHandler, and server::zone::objects::creature::conversation::ConversationObserverImplementation::registerScreenHandler().
DeliverMissionConversationObserverImplementation::DeliverMissionConversationObserverImplementation (DummyConstructorParameter * param)
Definition at line 45 of file DeliverMissionConversationObserver.cpp.
References _initializeImplementation().
DeliverMissionConversationObserverImplementation::~DeliverMissionConversationObserverImplementation () protected virtual
Definition at line 50 of file DeliverMissionConversationObserver.cpp.
Member Function Documentation
DistributedObjectStub * DeliverMissionConversationObserverImplementation::_getStub ()
Definition at line 70 of file DeliverMissionConversationObserver.cpp.
References _this.
void DeliverMissionConversationObserverImplementation::_initializeImplementation () protected
Definition at line 57 of file DeliverMissionConversationObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by DeliverMissionConversationObserverImplementation().
void DeliverMissionConversationObserverImplementation::_serializationHelperMethod () protected
Definition at line 106 of file DeliverMissionConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void DeliverMissionConversationObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 65 of file DeliverMissionConversationObserver.cpp.
References server::zone::objects::creature::conversation::ConversationObserverImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::conversation::DeliverMissionConversationObserver::DeliverMissionConversationObserver().
void DeliverMissionConversationObserverImplementation::finalize () protected
Definition at line 54 of file DeliverMissionConversationObserver.cpp.
void DeliverMissionConversationObserverImplementation::lock (bool doLock = true) protected
Definition at line 78 of file DeliverMissionConversationObserver.cpp.
References _this.
void DeliverMissionConversationObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 82 of file DeliverMissionConversationObserver.cpp.
References _this.
DeliverMissionConversationObserverImplementation::operator const DeliverMissionConversationObserver * ()
Definition at line 74 of file DeliverMissionConversationObserver.cpp.
void DeliverMissionConversationObserverImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::conversation::ConversationObserverImplementation.
Definition at line 113 of file DeliverMissionConversationObserver.cpp.
References readObjectMember().
bool DeliverMissionConversationObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 132 of file DeliverMissionConversationObserver.cpp.
References deliverMissionScreenHandler, and server::zone::objects::creature::conversation::ConversationObserverImplementation::readObjectMember().
Referenced by readObject().
void DeliverMissionConversationObserverImplementation::rlock (bool doLock = true) protected
Definition at line 86 of file DeliverMissionConversationObserver.cpp.
References _this.
void DeliverMissionConversationObserverImplementation::runlock (bool doLock = true) protected
Definition at line 102 of file DeliverMissionConversationObserver.cpp.
References _this.
void DeliverMissionConversationObserverImplementation::unlock (bool doLock = true) protected
Definition at line 98 of file DeliverMissionConversationObserver.cpp.
References _this.
void DeliverMissionConversationObserverImplementation::wlock (bool doLock = true) protected
Definition at line 90 of file DeliverMissionConversationObserver.cpp.
References _this.
void DeliverMissionConversationObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 94 of file DeliverMissionConversationObserver.cpp.
References _this.
void DeliverMissionConversationObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::conversation::ConversationObserverImplementation.
Definition at line 146 of file DeliverMissionConversationObserver.cpp.
References writeObjectMembers().
int DeliverMissionConversationObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 153 of file DeliverMissionConversationObserver.cpp.
References deliverMissionScreenHandler, and server::zone::objects::creature::conversation::ConversationObserverImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class DeliverMissionConversationObserver friend
Definition at line 103 of file DeliverMissionConversationObserver.h.
Member Data Documentation
WeakReference<DeliverMissionConversationObserver*> server::zone::objects::creature::conversation::DeliverMissionConversationObserverImplementation::_this
Definition at line 69 of file DeliverMissionConversationObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
DeliverMissionScreenHandler server::zone::objects::creature::conversation::DeliverMissionConversationObserverImplementation::deliverMissionScreenHandler private
Definition at line 62 of file DeliverMissionConversationObserver.h.
Referenced by DeliverMissionConversationObserverImplementation(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/DeliverMissionConversationObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/DeliverMissionConversationObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/DeliverMissionConversationObserverImplementation.cpp