Core3: AdBarkingPhraseSuiCallback Class Reference
AdBarkingPhraseSuiCallback Class Reference
#include <AdBarkingPhraseSuiCallback.h>
Public Member Functions
AdBarkingPhraseSuiCallback (ZoneServer *serv)
void run (CreatureObject *creature, SuiBox *sui, bool cancelPressed, Vector< UnicodeString > *args)
void handleSelectPhrase (VendorAdBarkingSession *session, CreatureObject *creature, SuiBox *sui, bool cancelPressed, Vector< UnicodeString > *args)
void handleCustomMessage (VendorAdBarkingSession *session, CreatureObject *creature, SuiBox *sui, bool cancelPressed, Vector< UnicodeString > *args)
void handleSelectMood (VendorAdBarkingSession *session, CreatureObject *creature, SuiBox *sui, bool cancelPressed, Vector< UnicodeString > *args)
void handleSelectAnimation (VendorAdBarkingSession *session, CreatureObject *creature, SuiBox *sui, bool cancelPressed, Vector< UnicodeString > *args)
Public Member Functions inherited from server::zone::objects::player::sui::SuiCallback
SuiCallback (ZoneServer *serv)
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::player::sui::SuiCallback
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 14 of file AdBarkingPhraseSuiCallback.h.
Constructor & Destructor Documentation
AdBarkingPhraseSuiCallback::AdBarkingPhraseSuiCallback (ZoneServer * serv) inline
Definition at line 18 of file AdBarkingPhraseSuiCallback.h.
Member Function Documentation
void AdBarkingPhraseSuiCallback::handleCustomMessage (VendorAdBarkingSession * session, CreatureObject * creature, SuiBox * sui, bool cancelPressed, Vector< UnicodeString > * args) inline
Definition at line 62 of file AdBarkingPhraseSuiCallback.h.
References server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::sendPhraseOptions(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::setMessage().
Referenced by run().
void AdBarkingPhraseSuiCallback::handleSelectAnimation (VendorAdBarkingSession * session, CreatureObject * creature, SuiBox * sui, bool cancelPressed, Vector< UnicodeString > * args) inline
Definition at line 95 of file AdBarkingPhraseSuiCallback.h.
References server::zone::objects::player::sui::listbox::SuiListBox::getMenuItemName(), server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::sendPhraseOptions(), and server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::setAnimation().
Referenced by run().
void AdBarkingPhraseSuiCallback::handleSelectMood (VendorAdBarkingSession * session, CreatureObject * creature, SuiBox * sui, bool cancelPressed, Vector< UnicodeString > * args) inline
Definition at line 81 of file AdBarkingPhraseSuiCallback.h.
References server::zone::objects::player::sui::listbox::SuiListBox::getMenuItemName(), server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::sendPhraseOptions(), and server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::setMood().
Referenced by run().
void AdBarkingPhraseSuiCallback::handleSelectPhrase (VendorAdBarkingSession * session, CreatureObject * creature, SuiBox * sui, bool cancelPressed, Vector< UnicodeString > * args) inline
Definition at line 41 of file AdBarkingPhraseSuiCallback.h.
References server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::cancelSession(), server::zone::objects::player::sui::listbox::SuiListBox::getMenuItemName(), server::zone::objects::player::sui::listbox::SuiListBox::getMenuObjectID(), server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::sendCustomMessageInput(), and server::zone::objects::player::sessions::vendor::VendorAdBarkingSession::setMessage().
Referenced by run().
void AdBarkingPhraseSuiCallback::run (CreatureObject * player, SuiBox * suiBox, bool cancelPressed, Vector< UnicodeString > * args) inline virtual
Parameters
player The player that this suibox is assigned to.
suiBox The actual SuiBox object.
cancelPressed Was the cancel button pressed, or was the sui box closed via a similar method. (this might actually be more of a dialogResult type variable)
args A vector of UnicodeStrings containing the arguments passed to the sui box from the client.
Implements server::zone::objects::player::sui::SuiCallback.
Definition at line 22 of file AdBarkingPhraseSuiCallback.h.
References server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::player::sui::SuiBox::getWindowType(), handleCustomMessage(), handleSelectAnimation(), handleSelectMood(), handleSelectPhrase(), SuiWindowType::VENDOR_ANIMATION, SuiWindowType::VENDOR_CUSTOM_PHRASE, SuiWindowType::VENDOR_MOODS, SuiWindowType::VENDOR_PHRASES, and SessionFacadeType::VENDORADBARKING.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/callbacks/AdBarkingPhraseSuiCallback.h