Core3: server::zone::objects::player::sessions::CityTreasuryWithdrawalSession Class Reference
server::zone::objects::player::sessions::CityTreasuryWithdrawalSession Class Reference
#include <CityTreasuryWithdrawalSession.h>
Public Member Functions
CityTreasuryWithdrawalSession (CreatureObject *creature, CityRegion *city, SceneObject *terminal=NULL)
void setReason (const String &r)
int initializeSession ()
int sendTransferBox (const String &reason)
int withdrawCredits (int value)
int cancelSession ()
int clearSession ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
CityTreasuryWithdrawalSession (DummyConstructorParameter *param)
virtual ~CityTreasuryWithdrawalSession ()
Friends
class CityTreasuryWithdrawalSessionHelper
Detailed Description
Definition at line 80 of file CityTreasuryWithdrawalSession.h.
Constructor & Destructor Documentation
CityTreasuryWithdrawalSession::CityTreasuryWithdrawalSession (CreatureObject * creature, CityRegion * city, SceneObject * terminal = NULL)
Definition at line 21 of file CityTreasuryWithdrawalSession.cpp.
References server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::_setStub().
CityTreasuryWithdrawalSession::CityTreasuryWithdrawalSession (DummyConstructorParameter * param) protected
Definition at line 28 of file CityTreasuryWithdrawalSession.cpp.
CityTreasuryWithdrawalSession::~CityTreasuryWithdrawalSession () protected virtual
Definition at line 32 of file CityTreasuryWithdrawalSession.cpp.
Member Function Documentation
DistributedObjectServant * CityTreasuryWithdrawalSession::_getImplementation ()
Definition at line 118 of file CityTreasuryWithdrawalSession.cpp.
Referenced by cancelSession(), clearSession(), initializeSession(), sendTransferBox(), setReason(), and withdrawCredits().
DistributedObjectServant * CityTreasuryWithdrawalSession::_getImplementationForRead ()
Definition at line 124 of file CityTreasuryWithdrawalSession.cpp.
void CityTreasuryWithdrawalSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 128 of file CityTreasuryWithdrawalSession.cpp.
int CityTreasuryWithdrawalSession::cancelSession ()
Definition at line 92 of file CityTreasuryWithdrawalSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
Referenced by CityTreasuryWithdrawalReasonSuiCallback::run(), and CityTreasuryWithdrawalSuiCallback::run().
int CityTreasuryWithdrawalSession::clearSession ()
Definition at line 105 of file CityTreasuryWithdrawalSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
int CityTreasuryWithdrawalSession::initializeSession ()
Definition at line 51 of file CityTreasuryWithdrawalSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
int CityTreasuryWithdrawalSession::sendTransferBox (const String & reason)
Definition at line 64 of file CityTreasuryWithdrawalSession.cpp.
References _getImplementation(), RPC_SENDTRANSFERBOX__STRING_, and server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::sendTransferBox().
void CityTreasuryWithdrawalSession::setReason (const String & r)
Definition at line 37 of file CityTreasuryWithdrawalSession.cpp.
References _getImplementation(), RPC_SETREASON__STRING_, and server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::setReason().
int CityTreasuryWithdrawalSession::withdrawCredits (int value)
Definition at line 78 of file CityTreasuryWithdrawalSession.cpp.
References _getImplementation(), RPC_WITHDRAWCREDITS__INT_, and server::zone::objects::player::sessions::CityTreasuryWithdrawalSessionImplementation::withdrawCredits().
Friends And Related Function Documentation
friend class CityTreasuryWithdrawalSessionHelper friend
Definition at line 106 of file CityTreasuryWithdrawalSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityTreasuryWithdrawalSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CityTreasuryWithdrawalSession.cpp