Core3: server::zone::objects::area::CampSiteObserver Class Reference
server::zone::objects::area::CampSiteObserver Class Reference
#include <CampSiteObserver.h>
Public Member Functions
CampSiteObserver (CampSiteActiveArea *area)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
CampSiteObserver (DummyConstructorParameter *param)
virtual ~CampSiteObserver ()
Friends
class CampSiteObserverHelper
Detailed Description
Definition at line 27 of file CampSiteObserver.h.
Constructor & Destructor Documentation
CampSiteObserver::CampSiteObserver (CampSiteActiveArea * area)
Definition at line 13 of file CampSiteObserver.cpp.
References server::zone::objects::area::CampSiteObserverImplementation::_setStub().
CampSiteObserver::CampSiteObserver (DummyConstructorParameter * param) protected
Definition at line 20 of file CampSiteObserver.cpp.
CampSiteObserver::~CampSiteObserver () protected virtual
Definition at line 24 of file CampSiteObserver.cpp.
Member Function Documentation
DistributedObjectServant * CampSiteObserver::_getImplementation ()
Definition at line 46 of file CampSiteObserver.cpp.
Referenced by notifyObserverEvent().
DistributedObjectServant * CampSiteObserver::_getImplementationForRead ()
Definition at line 52 of file CampSiteObserver.cpp.
void CampSiteObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 56 of file CampSiteObserver.cpp.
int CampSiteObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 29 of file CampSiteObserver.cpp.
References _getImplementation(), server::zone::objects::area::CampSiteObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class CampSiteObserverHelper friend
Definition at line 43 of file CampSiteObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/CampSiteObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/CampSiteObserver.cpp