Core3: StructureTerminalMenuComponent Class Reference
StructureTerminalMenuComponent Class Reference
#include <StructureTerminalMenuComponent.h>
Public Member Functions
void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *creature)
int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *creature, byte selectedID)
Detailed Description
Definition at line 14 of file StructureTerminalMenuComponent.h.
Member Function Documentation
void StructureTerminalMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from ObjectMenuComponent.
Definition at line 20 of file StructureTerminalMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID(), server::zone::objects::building::BuildingObject::hasAccessFee(), server::zone::objects::creature::CreatureObject::hasSkill(), and server::zone::objects::scene::SceneObject::isTerminal().
int StructureTerminalMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from ObjectMenuComponent.
Definition at line 96 of file StructureTerminalMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::addActiveSession(), server::zone::objects::building::BuildingObject::canChangeAccessFee(), server::zone::objects::creature::CreatureObject::executeObjectControllerAction(), server::zone::objects::building::BuildingObject::getAccessFeeDelay(), server::zone::objects::building::BuildingObject::hasAccessFee(), server::zone::objects::creature::CreatureObject::hasSkill(), StructureManager::promptDeleteAllItems(), StructureManager::promptFindLostItems(), StructureManager::promptNameStructure(), server::zone::objects::building::BuildingObject::removeAccessFee(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), and SessionFacadeType::SETSTRUCTUREACCESSFEE.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/terminal/components/StructureTerminalMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/terminal/components/StructureTerminalMenuComponent.cpp