Core3: PlaceCityHallSuiCallback Class Reference
PlaceCityHallSuiCallback Class Reference
#include <PlaceCityHallSuiCallback.h>
Public Member Functions
PlaceCityHallSuiCallback (Zone *zone, StructureDeed *deed, float x, float y, int angle)
void run (CreatureObject *creature, SuiBox *sui, bool cancelPressed, Vector< UnicodeString > *args)
Public Member Functions inherited from server::zone::objects::player::sui::SuiCallback
SuiCallback (ZoneServer *serv)
Private Attributes
ManagedWeakReference< Zone * > zone
ManagedWeakReference
< StructureDeed * > deed
float x
float y
int angle
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::player::sui::SuiCallback
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 21 of file PlaceCityHallSuiCallback.h.
Constructor & Destructor Documentation
PlaceCityHallSuiCallback::PlaceCityHallSuiCallback (Zone * zone, StructureDeed * deed, float x, float y, int angle) inline
Definition at line 30 of file PlaceCityHallSuiCallback.h.
References angle, deed, x, y, and zone.
Member Function Documentation
void PlaceCityHallSuiCallback::run (CreatureObject * player, SuiBox * suiBox, bool cancelPressed, Vector< UnicodeString > * args) inline virtual
Parameters
player The player that this suibox is assigned to.
suiBox The actual SuiBox object.
cancelPressed Was the cancel button pressed, or was the sui box closed via a similar method. (this might actually be more of a dialogResult type variable)
args A vector of UnicodeStrings containing the arguments passed to the sui box from the client.
Implements server::zone::objects::player::sui::SuiCallback.
Definition at line 40 of file PlaceCityHallSuiCallback.h.
References angle, server::zone::managers::city::CityManager::createCity(), deed, server::zone::objects::player::sui::SuiBox::isInputBox(), server::zone::managers::name::NameManager::isProfane(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::player::sui::SuiCallback::server, server::zone::managers::city::CityManager::validateCityInRange(), server::zone::managers::city::CityManager::validateCityName(), server::zone::managers::planet::PlanetManager::validateClientCityInRange(), server::zone::managers::planet::PlanetManager::validateRegionName(), x, y, and zone.
Member Data Documentation
int PlaceCityHallSuiCallback::angle private
Definition at line 27 of file PlaceCityHallSuiCallback.h.
Referenced by PlaceCityHallSuiCallback(), and run().
ManagedWeakReference<StructureDeed*> PlaceCityHallSuiCallback::deed private
Definition at line 23 of file PlaceCityHallSuiCallback.h.
Referenced by PlaceCityHallSuiCallback(), and run().
float PlaceCityHallSuiCallback::x private
Definition at line 25 of file PlaceCityHallSuiCallback.h.
Referenced by PlaceCityHallSuiCallback(), and run().
float PlaceCityHallSuiCallback::y private
Definition at line 26 of file PlaceCityHallSuiCallback.h.
Referenced by PlaceCityHallSuiCallback(), and run().
ManagedWeakReference<Zone*> PlaceCityHallSuiCallback::zone private
Definition at line 22 of file PlaceCityHallSuiCallback.h.
Referenced by PlaceCityHallSuiCallback(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/callbacks/PlaceCityHallSuiCallback.h