Core3: server::zone::objects::tangible::weapon::WeaponObject Class Reference
server::zone::objects::tangible::weapon::WeaponObject Class Reference
#include <WeaponObject.h>
Public Member Functions
WeaponObject ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void sendBaselinesTo (SceneObject *player)
void sendContainerTo (CreatureObject *player)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void updateCraftingValues (CraftingValues *values, bool firstUpdate)
void createChildObjects ()
bool isCertifiedFor (CreatureObject *object)
Vector< String > * getDamageModifiers ()
Vector< String > * getSpeedModifiers ()
Vector< String > * getCreatureAccuracyModifiers ()
Vector< String > * getCreatureAimModifiers ()
Vector< String > * getDefenderDefenseModifiers ()
Vector< String > * getDefenderSecondaryDefenseModifiers ()
Vector< String > * getDefenderToughnessModifiers ()
void setCertified (bool cert)
int getAttackType ()
void setAttackType (int a)
bool isCertified ()
int getPointBlankAccuracy (bool withPup=true)
void setPointBlankAccuracy (int value)
int getPointBlankRange (bool withPup=true)
int getIdealRange (bool withPup=true)
void setIdealRange (int value)
int getMaxRange (bool withPup=true)
void setMaxRange (int value)
int getIdealAccuracy (bool withPup=true)
void setIdealAccuracy (int value)
int getArmorPiercing ()
int getMaxRangeAccuracy (bool withPup=true)
void setMaxRangeAccuracy (int value)
float getAttackSpeed (bool withPup=true)
void setAttackSpeed (float value)
float getMaxDamage (bool withPup=true)
void setMaxDamage (float value)
float getMinDamage (bool withPup=true)
void setMinDamage (float value)
float getWoundsRatio (bool withPup=true)
void setWoundsRatio (float value)
float getDamageRadius (bool withPup=true)
void setDamageRadius (float value)
int getHealthAttackCost (bool withPup=true)
void setHealthAttackCost (int value)
int getActionAttackCost (bool withPup=true)
void setActionAttackCost (int value)
int getMindAttackCost (bool withPup=true)
void setMindAttackCost (int value)
int getForceCost ()
void setForceCost (int value)
int getBladeColor ()
void setBladeColor (int value)
int getDamageType ()
String getXpType ()
int getNumberOfDots ()
int getDotType (int index)
int getDotAttribute (int index)
int getDotStrength (int index)
int getDotDuration (int index)
int getDotPotency (int index)
int getDotUses (int index)
void addDotType (int t)
void addDotAttribute (int a)
void addDotStrength (int s)
void addDotDuration (int du)
void addDotPotency (int po)
void addDotUses (int u)
void setDotUses (int u, int index)
String getWeaponType ()
bool isUnarmedWeapon ()
bool isMeleeWeapon ()
bool isRangedWeapon ()
bool isRifleWeapon ()
bool isThrownWeapon ()
bool isHeavyWeapon ()
bool isSpecialHeavyWeapon ()
bool isLightningRifle ()
bool isFlameThrower ()
bool isHeavyAcidRifle ()
bool isCarbineWeapon ()
bool isPistolWeapon ()
bool isOneHandMeleeWeapon ()
bool isPolearmWeaponObject ()
bool isTwoHandMeleeWeapon ()
bool isMineWeapon ()
bool isJediWeapon ()
bool isJediOneHandedWeapon ()
bool isJediTwoHandedWeapon ()
bool isJediPolearmWeapon ()
bool isWeaponObject ()
bool hasPowerup ()
void applyPowerup (CreatureObject *player, PowerupObject *pup)
PowerupObject * removePowerup ()
void decreasePowerupUses (CreatureObject *player)
String repairAttempt (int repairChance)
void decay (CreatureObject *user, float damage)
void setDamageSlice (float value)
void setSpeedSlice (float value)
void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
void removeSkillModsFrom (CreatureObject *creature)
void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
VectorMap< String, int > * getWearableSkillMods ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::tangible::TangibleObject
TangibleObject ()
void initializeMembers ()
void addTemplateSkillMods (TangibleObject *targetObject)
void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
void removeSkillModsFrom (CreatureObject *creature)
void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
void removeAllSkillModsOfType (const int skillType, bool notifyClient=true)
void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void sendBaselinesTo (SceneObject *player)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
void removeDefenders ()
void setCombatState ()
void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void clearCombatState (bool clearDefenders=true)
bool hasDefender (SceneObject *defender)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
bool isHealableBy (CreatureObject *object)
void sendPvpStatusTo (CreatureObject *player)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
void updateCraftingValues (CraftingValues *values, bool firstUpdate)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
bool isKiller ()
bool isTicketCollector ()
bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
int getUseCount ()
int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
int getJunkDealerNeeded ()
void setJunkValue (int jValue)
int getJunkValue ()
void setSerialNumber (const String &serial)
void setLevel (int lev)
String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
String repairAttempt (int repairChance)
bool isBroken ()
float getHitChance ()
void broadcastPvpStatusBitmask ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject ()
void initializePrivateData ()
void loadTemplateData (SharedObjectTemplate *templateData)
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendAttributeListTo (CreatureObject *object)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
void openContainerTo (CreatureObject *player)
byte checkContainerPermission (CreatureObject *player, unsigned short permission)
void closeContainerTo (CreatureObject *player, bool notify=true)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets=true)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
String getDetailedDescription ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int NONE = 0
static const int LIGHT = 1
static const int MEDIUM = 2
static const int HEAVY = 3
static const int KINETIC = 1
static const int ENERGY = 2
static const int BLAST = 4
static const int STUN = 8
static const int LIGHTSABER = 16
static const int HEAT = 32
static const int COLD = 64
static const int ACID = 128
static const int ELECTRICITY = 256
static const int FORCE = 512
static const int MELEEATTACK = 0
static const int RANGEDATTACK = 1
static const int FORCEATTACK = 2
static const int TRAPATTACK = 3
static const int GRENADEATTACK = 4
static const int HEAVYACIDBEAMATTACK = 14
static const int HEAVYLIGHTNINGBEAMATTACK = 15
static const int HEAVYPARTICLEBEAMATTACK = 17
static const int HEAVYROCKETLAUNCHERATTACK = 18
static const int HEAVYLAUNCHERATTACK = 19
Protected Member Functions
WeaponObject (DummyConstructorParameter *param)
virtual ~WeaponObject ()
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObject
TangibleObject (DummyConstructorParameter *param)
virtual ~TangibleObject ()
Protected Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject (DummyConstructorParameter *param)
virtual ~SceneObject ()
Friends
class WeaponObjectHelper
Detailed Description
Definition at line 130 of file WeaponObject.h.
Constructor & Destructor Documentation
WeaponObject::WeaponObject ()
Definition at line 27 of file WeaponObject.cpp.
References server::zone::objects::tangible::weapon::WeaponObjectImplementation::_setStub().
WeaponObject::WeaponObject (DummyConstructorParameter * param) protected
Definition at line 34 of file WeaponObject.cpp.
WeaponObject::~WeaponObject () protected virtual
Definition at line 38 of file WeaponObject.cpp.
Member Function Documentation
DistributedObjectServant * WeaponObject::_getImplementation ()
Definition at line 1381 of file WeaponObject.cpp.
Referenced by addDotAttribute(), addDotDuration(), addDotPotency(), addDotStrength(), addDotType(), addDotUses(), addSkillMod(), applyPowerup(), applySkillModsTo(), createChildObjects(), decay(), decreasePowerupUses(), fillAttributeList(), getActionAttackCost(), getArmorPiercing(), getAttackSpeed(), getAttackType(), getBladeColor(), getCreatureAccuracyModifiers(), getCreatureAimModifiers(), getDamageModifiers(), getDamageRadius(), getDamageType(), getDefenderDefenseModifiers(), getDefenderSecondaryDefenseModifiers(), getDefenderToughnessModifiers(), getDotAttribute(), getDotDuration(), getDotPotency(), getDotStrength(), getDotType(), getDotUses(), getForceCost(), getHealthAttackCost(), getIdealAccuracy(), getIdealRange(), getMaxDamage(), getMaxRange(), getMaxRangeAccuracy(), getMinDamage(), getMindAttackCost(), getNumberOfDots(), getPointBlankAccuracy(), getPointBlankRange(), getSpeedModifiers(), getWeaponType(), getWearableSkillMods(), getWoundsRatio(), getXpType(), hasPowerup(), initializeTransientMembers(), isCarbineWeapon(), isCertified(), isCertifiedFor(), isFlameThrower(), isHeavyAcidRifle(), isHeavyWeapon(), isJediOneHandedWeapon(), isJediPolearmWeapon(), isJediTwoHandedWeapon(), isJediWeapon(), isLightningRifle(), isMeleeWeapon(), isMineWeapon(), isOneHandMeleeWeapon(), isPistolWeapon(), isPolearmWeaponObject(), isRangedWeapon(), isRifleWeapon(), isSpecialHeavyWeapon(), isThrownWeapon(), isTwoHandMeleeWeapon(), isUnarmedWeapon(), isWeaponObject(), loadTemplateData(), removePowerup(), removeSkillModsFrom(), repairAttempt(), sendBaselinesTo(), sendContainerTo(), setActionAttackCost(), setAttackSpeed(), setAttackType(), setBladeColor(), setCertified(), setDamageRadius(), setDamageSlice(), setDotUses(), setForceCost(), setHealthAttackCost(), setIdealAccuracy(), setIdealRange(), setMaxDamage(), setMaxRange(), setMaxRangeAccuracy(), setMinDamage(), setMindAttackCost(), setPointBlankAccuracy(), setSpeedSlice(), setWoundsRatio(), and updateCraftingValues().
DistributedObjectServant * WeaponObject::_getImplementationForRead ()
Definition at line 1387 of file WeaponObject.cpp.
void WeaponObject::_setImplementation (DistributedObjectServant * servant)
Definition at line 1391 of file WeaponObject.cpp.
void WeaponObject::addDotAttribute (int a)
Definition at line 839 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::addDotAttribute(), and RPC_ADDDOTATTRIBUTE__INT_.
void WeaponObject::addDotDuration (int du)
Definition at line 867 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::addDotDuration(), and RPC_ADDDOTDURATION__INT_.
void WeaponObject::addDotPotency (int po)
Definition at line 881 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::addDotPotency(), and RPC_ADDDOTPOTENCY__INT_.
void WeaponObject::addDotStrength (int s)
Definition at line 853 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::addDotStrength(), and RPC_ADDDOTSTRENGTH__INT_.
void WeaponObject::addDotType (int t)
Definition at line 825 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::addDotType(), and RPC_ADDDOTTYPE__INT_.
void WeaponObject::addDotUses (int u)
Definition at line 895 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::addDotUses(), and RPC_ADDDOTUSES__INT_.
void WeaponObject::addSkillMod (const int skillType, const String & skillMod, int value, bool notifyClient = true)
Definition at line 1355 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::addSkillMod(), and RPC_ADDSKILLMOD__INT_STRING_INT_BOOL_.
void WeaponObject::applyPowerup (CreatureObject * player, PowerupObject * pup)
Definition at line 1225 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::applyPowerup(), and RPC_APPLYPOWERUP__CREATUREOBJECT_POWERUPOBJECT_.
Referenced by ApplyPowerupCommand::doQueueCommand().
void WeaponObject::applySkillModsTo (CreatureObject * creature, bool doCheck = true)
Definition at line 1326 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::applySkillModsTo(), and RPC_APPLYSKILLMODSTO__CREATUREOBJECT_BOOL_.
void WeaponObject::createChildObjects ()
Handles creating the Saber inventory.
Definition at line 111 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), and RPC_CREATECHILDOBJECTS__.
void WeaponObject::decay (CreatureObject * user, float damage)
Definition at line 1283 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::decay(), and RPC_DECAY__CREATUREOBJECT_FLOAT_.
Referenced by CombatManager::applySpecialAttackCost(), and CombatManager::calculateDamage().
void WeaponObject::decreasePowerupUses (CreatureObject * player)
Definition at line 1253 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::decreasePowerupUses(), and RPC_DECREASEPOWERUPUSES__CREATUREOBJECT_.
Referenced by CombatManager::applyDamage(), and CombatManager::doAreaCombatAction().
void WeaponObject::fillAttributeList (AttributeListMessage * msg, CreatureObject * object)
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Definition at line 93 of file WeaponObject.cpp.
References _getImplementation(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::fillAttributeList().
int WeaponObject::getActionAttackCost (bool withPup = true)
Definition at line 590 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getActionAttackCost(), and RPC_GETACTIONATTACKCOST__BOOL_.
Referenced by CombatManager::applySpecialAttackCost(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat().
int WeaponObject::getArmorPiercing ()
Definition at line 381 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getArmorPiercing(), and RPC_GETARMORPIERCING__.
Referenced by CombatManager::getArmorPiercing().
float WeaponObject::getAttackSpeed (bool withPup = true)
Definition at line 422 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getAttackSpeed(), and RPC_GETATTACKSPEED__BOOL_.
Referenced by CombatManager::calculateWeaponAttackSpeed(), TurretFireTask::doAutoFire(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat(), TurretFireTask::handleManualFire(), TurretDataComponent::initializeTransientMembers(), and TurretDataComponent::setWeapon().
int WeaponObject::getAttackType ()
Definition at line 215 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getAttackType(), and RPC_GETATTACKTYPE__.
Referenced by CombatManager::calculateDamage(), CombatManager::calculateDamageRange(), CombatManager::calculatePostureModifier(), CombatManager::getAttackerAccuracyBonus(), CombatManager::getDamageModifier(), CombatManager::getHitChance(), and CombatManager::getSpeedModifier().
int WeaponObject::getBladeColor ()
Definition at line 673 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getBladeColor(), and RPC_GETBLADECOLOR__.
Vector< String > * WeaponObject::getCreatureAccuracyModifiers ()
Definition at line 156 of file WeaponObject.cpp.
References _getImplementation(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::getCreatureAccuracyModifiers().
Referenced by CombatManager::getAttackerAccuracyModifier().
Vector< String > * WeaponObject::getCreatureAimModifiers ()
Definition at line 165 of file WeaponObject.cpp.
References _getImplementation(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::getCreatureAimModifiers().
Vector< String > * WeaponObject::getDamageModifiers ()
Definition at line 138 of file WeaponObject.cpp.
References _getImplementation(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDamageModifiers().
Referenced by CombatManager::getDamageModifier().
float WeaponObject::getDamageRadius (bool withPup = true)
Definition at line 534 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDamageRadius(), and RPC_GETDAMAGERADIUS__BOOL_.
Referenced by server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat().
int WeaponObject::getDamageType ()
Definition at line 700 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDamageType(), and RPC_GETDAMAGETYPE__.
Referenced by CombatManager::calculateDamage(), CombatManager::getArmorNpcReduction(), CombatManager::getArmorObjectReduction(), CombatManager::getArmorReduction(), and CombatManager::getArmorTurretReduction().
Vector< String > * WeaponObject::getDefenderDefenseModifiers ()
Definition at line 174 of file WeaponObject.cpp.
References _getImplementation(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDefenderDefenseModifiers().
Referenced by CombatManager::getDefenderDefenseModifier().
Vector< String > * WeaponObject::getDefenderSecondaryDefenseModifiers ()
Definition at line 183 of file WeaponObject.cpp.
References _getImplementation(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDefenderSecondaryDefenseModifiers().
Vector< String > * WeaponObject::getDefenderToughnessModifiers ()
Definition at line 192 of file WeaponObject.cpp.
References _getImplementation(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDefenderToughnessModifiers().
int WeaponObject::getDotAttribute (int index)
Definition at line 755 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDotAttribute(), and RPC_GETDOTATTRIBUTE__INT_.
int WeaponObject::getDotDuration (int index)
Definition at line 783 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDotDuration(), and RPC_GETDOTDURATION__INT_.
int WeaponObject::getDotPotency (int index)
Definition at line 797 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDotPotency(), and RPC_GETDOTPOTENCY__INT_.
int WeaponObject::getDotStrength (int index)
Definition at line 769 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDotStrength(), and RPC_GETDOTSTRENGTH__INT_.
int WeaponObject::getDotType (int index)
Definition at line 741 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDotType(), and RPC_GETDOTTYPE__INT_.
int WeaponObject::getDotUses (int index)
Definition at line 811 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getDotUses(), and RPC_GETDOTUSES__INT_.
int WeaponObject::getForceCost ()
Definition at line 646 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getForceCost(), and RPC_GETFORCECOST__.
Referenced by CombatManager::applySpecialAttackCost().
int WeaponObject::getHealthAttackCost (bool withPup = true)
Definition at line 562 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getHealthAttackCost(), and RPC_GETHEALTHATTACKCOST__BOOL_.
Referenced by CombatManager::applySpecialAttackCost(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat().
int WeaponObject::getIdealAccuracy (bool withPup = true)
Definition at line 353 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getIdealAccuracy(), and RPC_GETIDEALACCURACY__BOOL_.
Referenced by CombatManager::getWeaponRangeModifier(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat(), and WeaponRanges::WeaponRanges().
int WeaponObject::getIdealRange (bool withPup = true)
Definition at line 297 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getIdealRange(), and RPC_GETIDEALRANGE__BOOL_.
Referenced by CombatManager::getWeaponRangeModifier(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat(), AiStateComponent::selectWeapon(), server::zone::objects::creature::AiAgentImplementation::selectWeapon(), and WeaponRanges::WeaponRanges().
float WeaponObject::getMaxDamage (bool withPup = true)
Definition at line 450 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getMaxDamage(), and RPC_GETMAXDAMAGE__BOOL_.
Referenced by CombatManager::calculateDamage(), CombatManager::calculateDamageRange(), CombatManager::doTargetCombatAction(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat().
int WeaponObject::getMaxRange (bool withPup = true)
Definition at line 325 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getMaxRange(), and RPC_GETMAXRANGE__BOOL_.
Referenced by CombatManager::doAreaCombatAction(), CombatManager::getWeaponRangeModifier(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat(), TurretDataComponent::initializeTransientMembers(), TurretDataComponent::setWeapon(), and WeaponRanges::WeaponRanges().
int WeaponObject::getMaxRangeAccuracy (bool withPup = true)
Definition at line 394 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getMaxRangeAccuracy(), and RPC_GETMAXRANGEACCURACY__BOOL_.
Referenced by CombatManager::getWeaponRangeModifier(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat(), and WeaponRanges::WeaponRanges().
float WeaponObject::getMinDamage (bool withPup = true)
Definition at line 478 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getMinDamage(), and RPC_GETMINDAMAGE__BOOL_.
Referenced by CombatManager::calculateDamage(), CombatManager::calculateDamageRange(), CombatManager::doTargetCombatAction(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat().
int WeaponObject::getMindAttackCost (bool withPup = true)
Definition at line 618 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getMindAttackCost(), and RPC_GETMINDATTACKCOST__BOOL_.
Referenced by CombatManager::applySpecialAttackCost(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat().
int WeaponObject::getNumberOfDots ()
Definition at line 728 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getNumberOfDots(), and RPC_GETNUMBEROFDOTS__.
int WeaponObject::getPointBlankAccuracy (bool withPup = true)
Definition at line 255 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getPointBlankAccuracy(), and RPC_GETPOINTBLANKACCURACY__BOOL_.
Referenced by CombatManager::getWeaponRangeModifier(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat(), and WeaponRanges::WeaponRanges().
int WeaponObject::getPointBlankRange (bool withPup = true)
Definition at line 283 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getPointBlankRange(), and RPC_GETPOINTBLANKRANGE__BOOL_.
Referenced by CombatManager::getWeaponRangeModifier(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat().
Vector< String > * WeaponObject::getSpeedModifiers ()
Definition at line 147 of file WeaponObject.cpp.
References _getImplementation(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::getSpeedModifiers().
Referenced by CombatManager::getSpeedModifier().
String WeaponObject::getWeaponType ()
Definition at line 924 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getWeaponType(), and RPC_GETWEAPONTYPE__.
VectorMap< String, int > * WeaponObject::getWearableSkillMods ()
Definition at line 1372 of file WeaponObject.cpp.
References _getImplementation(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::getWearableSkillMods().
Referenced by server::zone::managers::skill::SkillModManager::verifyWearableSkillMods().
float WeaponObject::getWoundsRatio (bool withPup = true)
Definition at line 506 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getWoundsRatio(), and RPC_GETWOUNDSRATIO__BOOL_.
Referenced by CombatManager::applyDamage(), and server::zone::objects::tangible::powerup::PowerupObjectImplementation::getWeaponStat().
String WeaponObject::getXpType ()
Definition at line 713 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::getXpType(), and RPC_GETXPTYPE__.
Referenced by server::zone::objects::tangible::threat::ThreatMapEntry::addDamage(), server::zone::objects::tangible::threat::ThreatMap::addDamage(), and CombatManager::applyDamage().
bool WeaponObject::hasPowerup ()
Definition at line 1212 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::hasPowerup(), and RPC_HASPOWERUP__.
void WeaponObject::initializeTransientMembers ()
Definition at line 52 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
bool WeaponObject::isCarbineWeapon ()
Definition at line 1069 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isCarbineWeapon(), and RPC_ISCARBINEWEAPON__.
bool WeaponObject::isCertified ()
Definition at line 242 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isCertified(), and RPC_ISCERTIFIED__.
bool WeaponObject::isCertifiedFor (CreatureObject * object)
Returns true if the player has the required certifications for this weapon
Precondition
{ }
Postcondition
{ }
Parameters
object player object to check against
Definition at line 124 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isCertifiedFor(), and RPC_ISCERTIFIEDFOR__CREATUREOBJECT_.
Referenced by CombatManager::calculateDamage(), and TransferItemWeaponCommand::doQueueCommand().
bool WeaponObject::isFlameThrower ()
Definition at line 1043 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isFlameThrower(), and RPC_ISFLAMETHROWER__.
bool WeaponObject::isHeavyAcidRifle ()
Definition at line 1056 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isHeavyAcidRifle(), and RPC_ISHEAVYACIDRIFLE__.
bool WeaponObject::isHeavyWeapon ()
Definition at line 1004 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isHeavyWeapon(), and RPC_ISHEAVYWEAPON__.
Referenced by CombatManager::doAreaCombatAction().
bool WeaponObject::isJediOneHandedWeapon ()
Definition at line 1160 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isJediOneHandedWeapon(), and RPC_ISJEDIONEHANDEDWEAPON__.
bool WeaponObject::isJediPolearmWeapon ()
Definition at line 1186 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isJediPolearmWeapon(), and RPC_ISJEDIPOLEARMWEAPON__.
bool WeaponObject::isJediTwoHandedWeapon ()
Definition at line 1173 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isJediTwoHandedWeapon(), and RPC_ISJEDITWOHANDEDWEAPON__.
bool WeaponObject::isJediWeapon ()
Definition at line 1147 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isJediWeapon(), and RPC_ISJEDIWEAPON__.
bool WeaponObject::isLightningRifle ()
Definition at line 1030 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isLightningRifle(), and RPC_ISLIGHTNINGRIFLE__.
bool WeaponObject::isMeleeWeapon ()
Definition at line 952 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isMeleeWeapon(), and RPC_ISMELEEWEAPON__.
Referenced by CombatManager::calculateTargetPostureModifier(), and server::zone::objects::creature::AiAgentImplementation::selectWeapon().
bool WeaponObject::isMineWeapon ()
Definition at line 1134 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isMineWeapon(), and RPC_ISMINEWEAPON__.
bool WeaponObject::isOneHandMeleeWeapon ()
Definition at line 1095 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isOneHandMeleeWeapon(), and RPC_ISONEHANDMELEEWEAPON__.
bool WeaponObject::isPistolWeapon ()
Definition at line 1082 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isPistolWeapon(), and RPC_ISPISTOLWEAPON__.
bool WeaponObject::isPolearmWeaponObject ()
Definition at line 1108 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isPolearmWeaponObject(), and RPC_ISPOLEARMWEAPONOBJECT__.
bool WeaponObject::isRangedWeapon ()
Definition at line 965 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isRangedWeapon(), and RPC_ISRANGEDWEAPON__.
Referenced by CombatManager::getDefaultAttackAnimation(), and server::zone::objects::creature::AiAgentImplementation::selectWeapon().
bool WeaponObject::isRifleWeapon ()
Definition at line 978 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isRifleWeapon(), and RPC_ISRIFLEWEAPON__.
bool WeaponObject::isSpecialHeavyWeapon ()
Definition at line 1017 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isSpecialHeavyWeapon(), and RPC_ISSPECIALHEAVYWEAPON__.
bool WeaponObject::isThrownWeapon ()
Definition at line 991 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isThrownWeapon(), and RPC_ISTHROWNWEAPON__.
Referenced by CombatManager::doAreaCombatAction().
bool WeaponObject::isTwoHandMeleeWeapon ()
Definition at line 1121 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isTwoHandMeleeWeapon(), and RPC_ISTWOHANDMELEEWEAPON__.
bool WeaponObject::isUnarmedWeapon ()
Definition at line 939 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isUnarmedWeapon(), and RPC_ISUNARMEDWEAPON__.
bool WeaponObject::isWeaponObject ()
Definition at line 1199 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::isWeaponObject(), and RPC_ISWEAPONOBJECT__.
void WeaponObject::loadTemplateData (SharedObjectTemplate * templateData)
Definition at line 43 of file WeaponObject.cpp.
References _getImplementation(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::loadTemplateData().
PowerupObject * WeaponObject::removePowerup ()
Definition at line 1240 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::removePowerup(), and RPC_REMOVEPOWERUP__.
void WeaponObject::removeSkillModsFrom (CreatureObject * creature)
Definition at line 1341 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::removeSkillModsFrom(), and RPC_REMOVESKILLMODSFROM__CREATUREOBJECT_.
String WeaponObject::repairAttempt (int repairChance)
Definition at line 1267 of file WeaponObject.cpp.
References _getImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::repairAttempt(), and RPC_REPAIRATTEMPT__INT_.
void WeaponObject::sendBaselinesTo (SceneObject * player)
Definition at line 65 of file WeaponObject.cpp.
References _getImplementation(), RPC_SENDBASELINESTO__SCENEOBJECT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::sendBaselinesTo().
void WeaponObject::sendContainerTo (CreatureObject * player)
Definition at line 79 of file WeaponObject.cpp.
References _getImplementation(), RPC_SENDCONTAINERTO__CREATUREOBJECT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::sendContainerTo().
void WeaponObject::setActionAttackCost (int value)
Definition at line 604 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETACTIONATTACKCOST__INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setActionAttackCost().
void WeaponObject::setAttackSpeed (float value)
Definition at line 436 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETATTACKSPEED__FLOAT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setAttackSpeed().
Referenced by server::zone::objects::creature::ai::AiActorImplementation::setLevel(), and server::zone::objects::creature::AiAgentImplementation::setLevel().
void WeaponObject::setAttackType (int a)
Definition at line 228 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETATTACKTYPE__INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setAttackType().
void WeaponObject::setBladeColor (int value)
Definition at line 686 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETBLADECOLOR__INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setBladeColor().
void WeaponObject::setCertified (bool cert)
Definition at line 201 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETCERTIFIED__BOOL_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setCertified().
Referenced by TransferItemWeaponCommand::doQueueCommand().
void WeaponObject::setDamageRadius (float value)
Definition at line 548 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETDAMAGERADIUS__FLOAT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setDamageRadius().
void WeaponObject::setDamageSlice (float value)
Definition at line 1298 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETDAMAGESLICE__FLOAT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setDamageSlice().
Referenced by server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceDamage().
void WeaponObject::setDotUses (int u, int index)
Definition at line 909 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETDOTUSES__INT_INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setDotUses().
void WeaponObject::setForceCost (int value)
Definition at line 659 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETFORCECOST__INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setForceCost().
void WeaponObject::setHealthAttackCost (int value)
Definition at line 576 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETHEALTHATTACKCOST__INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setHealthAttackCost().
void WeaponObject::setIdealAccuracy (int value)
Definition at line 367 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETIDEALACCURACY__INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setIdealAccuracy().
void WeaponObject::setIdealRange (int value)
Definition at line 311 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETIDEALRANGE__INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setIdealRange().
void WeaponObject::setMaxDamage (float value)
Definition at line 464 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETMAXDAMAGE__FLOAT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setMaxDamage().
Referenced by server::zone::objects::creature::ai::AiActorImplementation::setLevel(), and server::zone::objects::creature::AiAgentImplementation::setLevel().
void WeaponObject::setMaxRange (int value)
Definition at line 339 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETMAXRANGE__INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setMaxRange().
void WeaponObject::setMaxRangeAccuracy (int value)
Definition at line 408 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETMAXRANGEACCURACY__INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setMaxRangeAccuracy().
void WeaponObject::setMinDamage (float value)
Definition at line 492 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETMINDAMAGE__FLOAT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setMinDamage().
Referenced by server::zone::objects::creature::ai::AiActorImplementation::setLevel(), and server::zone::objects::creature::AiAgentImplementation::setLevel().
void WeaponObject::setMindAttackCost (int value)
Definition at line 632 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETMINDATTACKCOST__INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setMindAttackCost().
void WeaponObject::setPointBlankAccuracy (int value)
Definition at line 269 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETPOINTBLANKACCURACY__INT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setPointBlankAccuracy().
void WeaponObject::setSpeedSlice (float value)
Definition at line 1312 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETSPEEDSLICE__FLOAT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setSpeedSlice().
Referenced by server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceSpeed().
void WeaponObject::setWoundsRatio (float value)
Definition at line 520 of file WeaponObject.cpp.
References _getImplementation(), RPC_SETWOUNDSRATIO__FLOAT_, and server::zone::objects::tangible::weapon::WeaponObjectImplementation::setWoundsRatio().
void WeaponObject::updateCraftingValues (CraftingValues * values, bool firstUpdate)
Definition at line 102 of file WeaponObject.cpp.
References _getImplementation(), and server::zone::objects::tangible::weapon::WeaponObjectImplementation::updateCraftingValues().
Friends And Related Function Documentation
friend class WeaponObjectHelper friend
Definition at line 410 of file WeaponObject.h.
Member Data Documentation
const int server::zone::objects::tangible::weapon::WeaponObject::ACID = 128 static
Definition at line 154 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::BLAST = 4 static
Definition at line 144 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::COLD = 64 static
Definition at line 152 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::ELECTRICITY = 256 static
Definition at line 156 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::ENERGY = 2 static
Definition at line 142 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::FORCE = 512 static
Definition at line 158 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::FORCEATTACK = 2 static
Definition at line 164 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::GRENADEATTACK = 4 static
Definition at line 168 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::HEAT = 32 static
Definition at line 150 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::HEAVY = 3 static
Definition at line 138 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::HEAVYACIDBEAMATTACK = 14 static
Definition at line 170 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::HEAVYLAUNCHERATTACK = 19 static
Definition at line 178 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::HEAVYLIGHTNINGBEAMATTACK = 15 static
Definition at line 172 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::HEAVYPARTICLEBEAMATTACK = 17 static
Definition at line 174 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::HEAVYROCKETLAUNCHERATTACK = 18 static
Definition at line 176 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::KINETIC = 1 static
Definition at line 140 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::LIGHT = 1 static
Definition at line 134 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::LIGHTSABER = 16 static
Definition at line 148 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::MEDIUM = 2 static
Definition at line 136 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::MELEEATTACK = 0 static
Definition at line 160 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::NONE = 0 static
Definition at line 132 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::RANGEDATTACK = 1 static
Definition at line 162 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::STUN = 8 static
Definition at line 146 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObject::TRAPATTACK = 3 static
Definition at line 166 of file WeaponObject.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/weapon/WeaponObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/weapon/WeaponObject.cpp