Core3: PingServer Class Reference
PingServer Class Reference
#include <PingServer.h>
Public Member Functions
PingServer ()
~PingServer ()
void initialize ()
void run ()
void shutdown ()
PingClient * createConnection (Socket *sock, SocketAddress &addr)
void handleMessage (ServiceClient *client, Packet *message)
void processMessage (Message *message)
bool handleError (ServiceClient *client, Exception &e)
void printInfo ()
Detailed Description
Definition at line 52 of file PingServer.h.
Constructor & Destructor Documentation
PingServer::PingServer ()
Definition at line 48 of file PingServer.cpp.
PingServer::~PingServer ()
Definition at line 56 of file PingServer.cpp.
Member Function Documentation
PingClient * PingServer::createConnection (Socket * sock, SocketAddress & addr)
Definition at line 73 of file PingServer.cpp.
bool PingServer::handleError (ServiceClient * client, Exception & e)
Definition at line 103 of file PingServer.cpp.
References PingClient::disconnect().
void PingServer::handleMessage (ServiceClient * client, Packet * message)
Definition at line 81 of file PingServer.cpp.
void PingServer::initialize ()
Definition at line 59 of file PingServer.cpp.
void PingServer::printInfo ()
Definition at line 116 of file PingServer.cpp.
Referenced by ServerCore::handleCommands().
void PingServer::processMessage (Message * message)
Definition at line 112 of file PingServer.cpp.
void PingServer::run ()
Definition at line 62 of file PingServer.cpp.
References shutdown().
void PingServer::shutdown ()
Definition at line 69 of file PingServer.cpp.
Referenced by run().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/ping/PingServer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/ping/PingServer.cpp