Core3: server::zone::objects::creature::conversation::screenhandlers::TrainerTrainedMasterScreenHandler Class Reference
server::zone::objects::creature::conversation::screenhandlers::TrainerTrainedMasterScreenHandler Class Reference
#include <TrainerScreenHandlers.h>
Public Member Functions
TrainerTrainedMasterScreenHandler ()
ConversationScreen * handleScreen (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
Public Member Functions inherited from server::zone::objects::creature::conversation::screenhandlers::ScreenHandler
ScreenHandler ()
~ScreenHandler ()
String getNextScreenId ()
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::conversation::screenhandlers::ScreenHandler
String nextScreenId
Detailed Description
Definition at line 115 of file TrainerScreenHandlers.h.
Constructor & Destructor Documentation
server::zone::objects::creature::conversation::screenhandlers::TrainerTrainedMasterScreenHandler::TrainerTrainedMasterScreenHandler () inline
Definition at line 117 of file TrainerScreenHandlers.h.
Member Function Documentation
ConversationScreen * TrainerTrainedMasterScreenHandler::handleScreen (CreatureObject * conversingPlayer, CreatureObject * conversingNPC, int selectedOption, ConversationScreen * conversationScreen) virtual
Implements server::zone::objects::creature::conversation::screenhandlers::ScreenHandler.
Definition at line 436 of file TrainerScreenHandlers.cpp.
References server::zone::templates::mobile::ConversationScreen::getDialogText(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getLastName(), and server::chat::StringIdChatParameter::setTT().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/screenhandlers/TrainerScreenHandlers.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/screenhandlers/TrainerScreenHandlers.cpp