Core3: TurretZoneComponent Class Reference
TurretZoneComponent Class Reference
#include <TurretZoneComponent.h>
Public Member Functions
void notifyPositionUpdate (SceneObject *sceneObject, QuadTreeEntry *entry)
void notifyInsertToZone (SceneObject *sceneObject, Zone *zne)
Public Member Functions inherited from ZoneComponent
virtual void switchZone (SceneObject *sceneObject, const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, uint64 parentID=0)
virtual void teleport (SceneObject *sceneObject, float newPositionX, float newPositionZ, float newPositionY, uint64 parentID=0)
virtual void notifyRemoveFromZone (SceneObject *sceneObject)
virtual void updateZone (SceneObject *sceneObject, bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *sceneObject, SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
virtual void notifySelfPositionUpdate (SceneObject *sceneObject)
virtual void notifyInsert (SceneObject *sceneObject, QuadTreeEntry *entry)
virtual void notifyDissapear (SceneObject *sceneObject, QuadTreeEntry *entry)
void updateInRangeObjectsOnMount (SceneObject *sceneObject)
virtual void destroyObjectFromWorld (SceneObject *sceneObject, bool sendSelfDestroy)
Additional Inherited Members
Protected Member Functions inherited from ZoneComponent
void insertChildObjectsToZone (SceneObject *sceneObject, Zone *zone)
Detailed Description
Definition at line 19 of file TurretZoneComponent.h.
Member Function Documentation
void TurretZoneComponent::notifyInsertToZone (SceneObject * sceneObject, Zone * zone) virtual
Inserts this object into zone
Precondition
{ this object is locked }
Postcondition
{ this object is locked and inserted into zone }
Parameters
zone Zone object where this object will be inserted
Reimplemented from ZoneComponent.
Definition at line 67 of file TurretZoneComponent.cpp.
References server::zone::ZoneServer::getObject(), server::zone::Zone::getZoneServer(), and ObserverEventType::OBJECTDESTRUCTION.
void TurretZoneComponent::notifyPositionUpdate (SceneObject * sceneObject, QuadTreeEntry * entry) virtual
Reimplemented from ZoneComponent.
Definition at line 29 of file TurretZoneComponent.cpp.
References TurretDataComponent::canAutoFire(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::scene::SceneObject::isTangibleObject(), and server::zone::objects::scene::SceneObject::isTurret().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/TurretZoneComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/TurretZoneComponent.cpp