Core3: VectorParam< Data > Class Template Reference
VectorParam< Data > Class Template Reference
#include <VectorParam.h>
Public Member Functions
VectorParam ()
~VectorParam ()
Vector< Data > get () const
Data & get (int i)
void add (Data data)
String toString ()
bool parse (Chunk *data)
Public Member Functions inherited from Param
Param ()
virtual ~Param ()
virtual bool parse (engine::util::Chunk *source)=0
uint32 getType ()
void setType (uint32 tp)
bool isBool ()
bool isFloat ()
bool isInteger ()
bool isString ()
bool isStringId ()
Private Attributes
Vector< Data > vectorData
Additional Inherited Members
Static Public Attributes inherited from Param
static const uint32 BOOL = 0x01
static const uint32 FLOAT = 0x02
static const uint32 INTEGER = 0x04
static const uint32 STRING = 0x08
static const uint32 STRINGID = 0x10
static const uint32 VECTOR = 0x12
static const uint32 DYNAMICVARIABLE = 0x014
static const uint32 TRIGGERVOLUME = 0x16
static const uint32 PALETTECOLORCUSTOMIZATION = 0x18
static const uint32 RANGEDINTCUSTOMIZATIONVARIABLE = 0x20
static const uint32 CUSTOMIZATIONVARIABLEMAP = 0x22
Detailed Description
template<class Data>
class VectorParam< Data >
Definition at line 33 of file VectorParam.h.
Constructor & Destructor Documentation
template<class Data> VectorParam< Data >::VectorParam () inline
Definition at line 37 of file VectorParam.h.
template<class Data> VectorParam< Data >::~VectorParam () inline
Definition at line 40 of file VectorParam.h.
Member Function Documentation
template<class Data> void VectorParam< Data >::add (Data data) inline
Definition at line 51 of file VectorParam.h.
Referenced by SharedCreatureObjectTemplate::parseVariableData().
template<class Data> Vector<Data> VectorParam< Data >::get () const inline
Definition at line 43 of file VectorParam.h.
Referenced by SharedCreatureObjectTemplate::getAcceleration(), SharedCreatureObjectTemplate::getPostureAlignToTerrain(), SharedCreatureObjectTemplate::getSpeed(), and SharedCreatureObjectTemplate::getTurnRate().
template<class Data> Data& VectorParam< Data >::get (int i) inline
Definition at line 47 of file VectorParam.h.
template<class Data> bool VectorParam< Data >::parse (Chunk * data) inline
Definition at line 72 of file VectorParam.h.
Referenced by SharedCreatureObjectTemplate::parseVariableData().
template<class Data> String VectorParam< Data >::toString () inline virtual
Implements Param.
Definition at line 55 of file VectorParam.h.
Member Data Documentation
template<class Data> Vector<Data> VectorParam< Data >::vectorData private
Definition at line 34 of file VectorParam.h.
Referenced by VectorParam< FloatParam >::add(), VectorParam< FloatParam >::get(), VectorParam< FloatParam >::parse(), and VectorParam< FloatParam >::toString().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/params/VectorParam.h