Core3: server::zone::objects::creature::commands::QueueCommand Class Reference
server::zone::objects::creature::commands::QueueCommand Class Reference
#include <QueueCommand.h>
Public Member Functions
QueueCommand (const String &skillname, ZoneProcessServer *serv)
virtual ~QueueCommand ()
bool checkInvalidLocomotions (CreatureObject *creature)
void onStateFail (CreatureObject *creature, uint32 actioncntr)
void onLocomotionFail (CreatureObject *creature, uint32 actioncntr)
virtual String getSyntax () const
virtual void onFail (uint32 actioncntr, CreatureObject *creature, uint32 errorNumber)
virtual void onComplete (uint32 actioncntr, CreatureObject *creature, float commandDuration)
void setInvalidLocomotions (const String &lStr)
void addInvalidLocomotion (int l)
virtual int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
bool checkStateMask (CreatureObject *creature)
virtual float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
void setStateMask (uint64 mask)
void setDefaultTime (float time)
void setTargetType (int num)
void setDisabled (bool state)
void setDisabled (int state)
void setAddToCombatQueue (bool state)
void setAddToCombatQueue (int state)
void setCommandGroup (int val)
void setMaxRange (float r)
void setCharacterAbility (const String &ability)
void setDefaultPriority (const String &priority)
void setDefaultPriority (const int priority)
uint64 getStateMask ()
bool requiresAdmin ()
int getTargetType ()
uint32 getNameCRC ()
float getMaxRange ()
String & getQueueCommandName ()
String & getCharacterAbility ()
float getDefaultTime ()
int getDefaultPriority ()
bool isDisabled ()
bool addToCombatQueue ()
virtual bool isCombatCommand ()
int getSkillModSize ()
int getSkillMod (int index, String &skillMod)
int getCommandGroup ()
void addSkillMod (const String &skillMod, const int value)
bool isWearingArmor (CreatureObject *creo)
virtual void handleBuff (SceneObject *creature, ManagedObject *object, int64 param)
Static Public Attributes
static const int IMMEDIATE = 0
static const int FRONT = 1
static const int NORMAL = 2
static const int SUCCESS = 0
static const int GENERALERROR = 1
static const int INVALIDLOCOMOTION = 2
static const int INVALIDSTATE = 3
static const int INVALIDTARGET = 4
static const int INVALIDWEAPON = 5
static const int TOOFAR = 6
static const int INSUFFICIENTHAM = 7
static const int INVALIDPARAMETERS = 8
static const int NOPRONE = 9
static const int NOKNEELING = 10
static const int INSUFFICIENTPERMISSION = 11
static const int NOJEDIARMOR = 12
static const int INVALIDSYNTAX = 13
Protected Attributes
ZoneProcessServer * server
String name
uint32 nameCRC
uint64 stateMask
Vector< int > invalidLocomotion
int targetType
int maxRangeToTarget
bool disabled
bool addToQueue
bool admin
uint32 cooldown
float defaultTime
String characterAbility
int defaultPriority
VectorMap< String, int > skillMods
int commandGroup
Detailed Description
Definition at line 67 of file QueueCommand.h.
Constructor & Destructor Documentation
QueueCommand::QueueCommand (const String & skillname, ZoneProcessServer * serv)
Definition at line 12 of file QueueCommand.cpp.
References addToQueue, admin, commandGroup, cooldown, defaultPriority, defaultTime, disabled, maxRangeToTarget, name, nameCRC, NORMAL, server, stateMask, and targetType.
virtual server::zone::objects::creature::commands::QueueCommand::~QueueCommand () inline virtual
Definition at line 119 of file QueueCommand.h.
Member Function Documentation
void server::zone::objects::creature::commands::QueueCommand::addInvalidLocomotion (int l) inline
Definition at line 156 of file QueueCommand.h.
References invalidLocomotion.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData().
void server::zone::objects::creature::commands::QueueCommand::addSkillMod (const String & skillMod, const int value) inline
Definition at line 333 of file QueueCommand.h.
References skillMods.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
bool server::zone::objects::creature::commands::QueueCommand::addToCombatQueue () inline
Definition at line 312 of file QueueCommand.h.
References addToQueue.
bool QueueCommand::checkInvalidLocomotions (CreatureObject * creature)
Definition at line 60 of file QueueCommand.cpp.
References server::zone::objects::creature::CreatureObject::getLocomotion(), and invalidLocomotion.
Referenced by CreatureRangedAttackCommand::doQueueCommand(), DefaultDroidAttackCommand::doQueueCommand(), MediumDiseaseCommand::doQueueCommand(), MediumPoisonCommand::doQueueCommand(), StrongDiseaseCommand::doQueueCommand(), StrongPoisonCommand::doQueueCommand(), MildDiseaseCommand::doQueueCommand(), MildPoisonCommand::doQueueCommand(), TurretFireCommand::doQueueCommand(), TurretFireManualCommand::doQueueCommand(), MinefieldAttackCommand::doQueueCommand(), SquadLeaderCommand::doQueueCommand(), DefaultAttackCommand::doQueueCommand(), DizzyAttackCommand::doQueueCommand(), PostureDownAttackCommand::doQueueCommand(), PostureUpAttackCommand::doQueueCommand(), IntimidationAttackCommand::doQueueCommand(), KnockdownAttackCommand::doQueueCommand(), BlindAttackCommand::doQueueCommand(), StunAttackCommand::doQueueCommand(), SurpriseShotCommand::doQueueCommand(), CreatureAreaBleedingCommand::doQueueCommand(), FireHeavyWeaponCommand::doQueueCommand(), CreatureAreaComboCommand::doQueueCommand(), CreatureAreaDiseaseCommand::doQueueCommand(), CreatureAreaKnockdownCommand::doQueueCommand(), CreatureAreaPoisonCommand::doQueueCommand(), CreatureAreaAttackCommand::doQueueCommand(), MultiTargetShotCommand::doQueueCommand(), ActionShot1Command::doQueueCommand(), UnarmedDizzy1Command::doQueueCommand(), BleedingShotCommand::doQueueCommand(), BurstShot1Command::doQueueCommand(), FormupCommand::doQueueCommand(), OverChargeShot1Command::doQueueCommand(), OverChargeShot2Command::doQueueCommand(), FullAutoArea1Command::doQueueCommand(), PanicShotCommand::doQueueCommand(), FullAutoArea2Command::doQueueCommand(), FullAutoSingle1Command::doQueueCommand(), FullAutoSingle2Command::doQueueCommand(), PistolMeleeDefense1Command::doQueueCommand(), PistolMeleeDefense2Command::doQueueCommand(), PointBlankArea1Command::doQueueCommand(), PointBlankSingle1Command::doQueueCommand(), PointBlankSingle2Command::doQueueCommand(), BurstShot2Command::doQueueCommand(), DisarmingShot1Command::doQueueCommand(), PolearmLunge1Command::doQueueCommand(), DisarmingShot2Command::doQueueCommand(), BodyShot1Command::doQueueCommand(), ThrowGrenadeCommand::doQueueCommand(), HeadShot1Command::doQueueCommand(), ChargeShot1Command::doQueueCommand(), ChargeShot2Command::doQueueCommand(), HeadShot3Command::doQueueCommand(), RallyCommand::doQueueCommand(), DoubleTapCommand::doQueueCommand(), RollShotCommand::doQueueCommand(), BodyShot2Command::doQueueCommand(), HealthShot1Command::doQueueCommand(), HealthShot2Command::doQueueCommand(), BodyShot3Command::doQueueCommand(), ConcealShotCommand::doQueueCommand(), EyeShotCommand::doQueueCommand(), FanShotCommand::doQueueCommand(), FastBlastCommand::doQueueCommand(), StoppingShotCommand::doQueueCommand(), ScatterShot1Command::doQueueCommand(), ScatterShot2Command::doQueueCommand(), KipUpShotCommand::doQueueCommand(), SetBoostmoraleCommand::doQueueCommand(), SetFormupCommand::doQueueCommand(), ConfusionShotCommand::doQueueCommand(), StartleShot1Command::doQueueCommand(), SetRetreatCommand::doQueueCommand(), SetSteadyaimCommand::doQueueCommand(), SniperShotCommand::doQueueCommand(), FireAcidCone1Command::doQueueCommand(), KnockdownFireCommand::doQueueCommand(), SprayShotCommand::doQueueCommand(), LastDitchCommand::doQueueCommand(), FireAcidCone2Command::doQueueCommand(), StartleShot2Command::doQueueCommand(), SteadyaimCommand::doQueueCommand(), FireAcidSingle1Command::doQueueCommand(), LegShot1Command::doQueueCommand(), UnarmedHit1Command::doQueueCommand(), FireAcidSingle2Command::doQueueCommand(), StrafeShot1Command::doQueueCommand(), StrafeShot2Command::doQueueCommand(), LegShot2Command::doQueueCommand(), LegShot3Command::doQueueCommand(), SuppressionFire1Command::doQueueCommand(), SuppressionFire2Command::doQueueCommand(), FireLightningCone1Command::doQueueCommand(), TauntCommand::doQueueCommand(), FireLightningCone2Command::doQueueCommand(), ThreatenShotCommand::doQueueCommand(), LowBlowCommand::doQueueCommand(), FireLightningSingle1Command::doQueueCommand(), TorsoShotCommand::doQueueCommand(), FireLightningSingle2Command::doQueueCommand(), FlameCone1Command::doQueueCommand(), UnarmedBlind1Command::doQueueCommand(), AimCommand::doQueueCommand(), FlameCone2Command::doQueueCommand(), UnarmedBodyHit1Command::doQueueCommand(), UnarmedCombo1Command::doQueueCommand(), UnarmedCombo2Command::doQueueCommand(), FlameSingle1Command::doQueueCommand(), UnarmedHeadHit1Command::doQueueCommand(), UnarmedHit2Command::doQueueCommand(), FlameSingle2Command::doQueueCommand(), UnarmedKnockdown1Command::doQueueCommand(), UnarmedKnockdown2Command::doQueueCommand(), UnarmedLegHit1Command::doQueueCommand(), FlurryShot1Command::doQueueCommand(), UnarmedSpinAttack1Command::doQueueCommand(), UnarmedSpinAttack2Command::doQueueCommand(), FlurryShot2Command::doQueueCommand(), UnderHandShotCommand::doQueueCommand(), FlushingShot1Command::doQueueCommand(), VolleyFireAttackCommand::doQueueCommand(), ActionShot2Command::doQueueCommand(), FlushingShot2Command::doQueueCommand(), WarningShotCommand::doQueueCommand(), WildShot1Command::doQueueCommand(), WildShot2Command::doQueueCommand(), Melee2hLunge1Command::doQueueCommand(), CripplingShotCommand::doQueueCommand(), UnarmedHit3Command::doQueueCommand(), MindShot2Command::doQueueCommand(), MindShot1Command::doQueueCommand(), MultiTargetPistolShotCommand::doQueueCommand(), Melee2hArea1Command::doQueueCommand(), OpenWingsCommand::doQueueCommand(), ForceWeaken2Command::doQueueCommand(), Melee1hBodyHit3Command::doQueueCommand(), AborthyperspaceCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), PilotShipCommand::doQueueCommand(), PointBlankArea2Command::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), ToggleDisplayingFactionRankCommand::doQueueCommand(), DestroyTargetCommand::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), DisableTargetCommand::doQueueCommand(), GmCreateClassResourceCommand::doQueueCommand(), GmCreateSpecificResourceCommand::doQueueCommand(), ChannelForceCommand::doQueueCommand(), PolearmLunge2Command::doQueueCommand(), UnpilotShipCommand::doQueueCommand(), DiveShotCommand::doQueueCommand(), Ptrap1Command::doQueueCommand(), Ptrap2Command::doQueueCommand(), PumpreactorCommand::doQueueCommand(), LootCommand::doQueueCommand(), HeadShot2Command::doQueueCommand(), DockCommand::doQueueCommand(), RequestBiographyCommand::doQueueCommand(), CheckForceStatusCommand::doQueueCommand(), RequestDraftSlotsBatchCommand::doQueueCommand(), RequestResourceWeightsBatchCommand::doQueueCommand(), RequestSpaceTrainerCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), DroidCommand::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), Saber1hComboHit2Command::doQueueCommand(), Melee1hHit1Command::doQueueCommand(), ForageCommand::doQueueCommand(), Epulse1Command::doQueueCommand(), Saber1hFlurryCommand::doQueueCommand(), Saber1hHeadHit1Command::doQueueCommand(), Saber1hHeadHit2Command::doQueueCommand(), AddPowerCommand::doQueueCommand(), Epulse2Command::doQueueCommand(), ClearVeteranRewardCommand::doQueueCommand(), Epulse3Command::doQueueCommand(), HyperspaceCommand::doQueueCommand(), EscapePodCommand::doQueueCommand(), IffscrambleCommand::doQueueCommand(), LfgCommand::doQueueCommand(), CloseWingsCommand::doQueueCommand(), EshieldsCommand::doQueueCommand(), InspacereloadCommand::doQueueCommand(), InspacerepairCommand::doQueueCommand(), EthrustCommand::doQueueCommand(), InspacerrCommand::doQueueCommand(), InspectCommand::doQueueCommand(), CreateMissionElementCommand::doQueueCommand(), EweaponsCommand::doQueueCommand(), InsureCommand::doQueueCommand(), Intimidate1Command::doQueueCommand(), LightEngineScrambleCommand::doQueueCommand(), NewbiehelperCommand::doQueueCommand(), Intimidate2Command::doQueueCommand(), ActivateQuestCommand::doQueueCommand(), Warcry1Command::doQueueCommand(), SaberThrow1Command::doQueueCommand(), SaberThrow2Command::doQueueCommand(), InvulnerableCommand::doQueueCommand(), SaberThrow3Command::doQueueCommand(), BoosterOffCommand::doQueueCommand(), Jstart1Command::doQueueCommand(), MindBlast2Command::doQueueCommand(), Jstart2Command::doQueueCommand(), ForceLightningCone2Command::doQueueCommand(), KillCommand::doQueueCommand(), Melee2hSweep2Command::doQueueCommand(), Melee2hSweep1Command::doQueueCommand(), ServerAsteroidDataListenCommand::doQueueCommand(), ServerAsteroidDataStopListeningCommand::doQueueCommand(), Melee2hMindHit2Command::doQueueCommand(), Jstart3Command::doQueueCommand(), KillPlayerCommand::doQueueCommand(), BoosterOnCommand::doQueueCommand(), Melee2hHit3Command::doQueueCommand(), LaunchCountermeasureCommand::doQueueCommand(), LaunchMissileCommand::doQueueCommand(), LeaveStationCommand::doQueueCommand(), SaberPolearmSpinAttack1Command::doQueueCommand(), SendFormObjectDataCommand::doQueueCommand(), VrepairCommand::doQueueCommand(), AddAllowedPlayerCommand::doQueueCommand(), Saber1hHit3Command::doQueueCommand(), Warcry2Command::doQueueCommand(), LootAllCommand::doQueueCommand(), SaberSlash2Command::doQueueCommand(), ToggleAwayFromKeyBoardCommand::doQueueCommand(), MedicalForageCommand::doQueueCommand(), UndockCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), SaberPolearmSpinAttack3Command::doQueueCommand(), UnarmedStun1Command::doQueueCommand(), Melee1hBlindHit1Command::doQueueCommand(), SaberSlash1Command::doQueueCommand(), SaberPolearmHit3Command::doQueueCommand(), SaberPolearmLegHit1Command::doQueueCommand(), Melee1hBlindHit2Command::doQueueCommand(), Melee1hBodyHit1Command::doQueueCommand(), SaberPolearmHit1Command::doQueueCommand(), SaberPolearmLegHit2Command::doQueueCommand(), UnarmedLunge1Command::doQueueCommand(), SaberPolearmLegHit3Command::doQueueCommand(), SaberPolearmHit2Command::doQueueCommand(), SaberPolearmDervishCommand::doQueueCommand(), Saber1hHeadHit3Command::doQueueCommand(), UnarmedLunge2Command::doQueueCommand(), Melee1hLunge1Command::doQueueCommand(), VolleyFireCommand::doQueueCommand(), Saber1hHit1Command::doQueueCommand(), VrepairotherCommand::doQueueCommand(), Saber1hHit2Command::doQueueCommand(), AttackCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), Melee2hHit1Command::doQueueCommand(), ForceIntimidate1Command::doQueueCommand(), Melee2hHit2Command::doQueueCommand(), Bstrike1Command::doQueueCommand(), ForceIntimidate2Command::doQueueCommand(), Melee2hLunge2Command::doQueueCommand(), ForceKnockdown1Command::doQueueCommand(), AnonCommand::doQueueCommand(), ForceKnockdown2Command::doQueueCommand(), ForceKnockdown3Command::doQueueCommand(), Saber1hComboHit1Command::doQueueCommand(), Saber1hComboHit3Command::doQueueCommand(), Bstrike2Command::doQueueCommand(), ForceLightningCone1Command::doQueueCommand(), MindBlast1Command::doQueueCommand(), ForceLightningSingle1Command::doQueueCommand(), Melee1hSpinAttack1Command::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), Bstrike3Command::doQueueCommand(), ForceThrow1Command::doQueueCommand(), ForceThrow2Command::doQueueCommand(), NblastCommand::doQueueCommand(), ForceWeaken1Command::doQueueCommand(), Melee1hDizzyHit1Command::doQueueCommand(), Melee1hBodyHit2Command::doQueueCommand(), PeaceCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), PolearmActionHit1Command::doQueueCommand(), PolearmActionHit2Command::doQueueCommand(), ActivateCloneCommand::doQueueCommand(), PolearmArea1Command::doQueueCommand(), PolearmStun1Command::doQueueCommand(), PolearmHit1Command::doQueueCommand(), PolearmHit2Command::doQueueCommand(), PolearmHit3Command::doQueueCommand(), PolearmLegHit2Command::doQueueCommand(), PolearmLegHit3Command::doQueueCommand(), PolearmSpinAttack1Command::doQueueCommand(), PolearmSpinAttack2Command::doQueueCommand(), HarvesterDeactivateCommand::doQueueCommand(), Melee1hLunge2Command::doQueueCommand(), PolearmSweep1Command::doQueueCommand(), PolearmSweep2Command::doQueueCommand(), Melee1hScatterHit1Command::doQueueCommand(), TakeCoverCommand::doQueueCommand(), DismountCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), RequestCharacterSheetInfoCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), TeleportToCommand::doQueueCommand(), PolearmStun2Command::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), PolearmArea2Command::doQueueCommand(), PolearmLegHit1Command::doQueueCommand(), Saber1hFlurry2Command::doQueueCommand(), Saber2hBodyHit1Command::doQueueCommand(), CloseContainerCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), Melee2hSpinAttack2Command::doQueueCommand(), MountCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), StoplisteningCommand::doQueueCommand(), DeclareresidenceCommand::doQueueCommand(), ForceLightningSingle2Command::doQueueCommand(), DeathBlowCommand::doQueueCommand(), Melee1hScatterHit2Command::doQueueCommand(), Melee2hSpinAttack1Command::doQueueCommand(), FindPlayerCommand::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), Melee1hDizzyHit2Command::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), Melee2hMindHit1Command::doQueueCommand(), Saber2hSweep3Command::doQueueCommand(), Melee2hArea3Command::doQueueCommand(), Melee2hHeadHit2Command::doQueueCommand(), Melee1hHit3Command::doQueueCommand(), RolePlayCommand::doQueueCommand(), Melee1hHit2Command::doQueueCommand(), AiIgnoreCommand::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), Melee1hHealthHit2Command::doQueueCommand(), Saber2hPhantomCommand::doQueueCommand(), Saber2hHit3Command::doQueueCommand(), SaberPolearmDervish2Command::doQueueCommand(), Saber2hBodyHit2Command::doQueueCommand(), Melee2hArea2Command::doQueueCommand(), Melee1hSpinAttack2Command::doQueueCommand(), Saber2hSweep2Command::doQueueCommand(), Saber2hFrenzyCommand::doQueueCommand(), Saber2hSweep1Command::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), Saber2hBodyHit3Command::doQueueCommand(), Saber2hHit2Command::doQueueCommand(), Saber2hHit1Command::doQueueCommand(), MeditateCommand::doQueueCommand(), SaberPolearmSpinAttack2Command::doQueueCommand(), KneelCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), ForceChokeCommand::doQueueCommand(), Melee2hHeadHit1Command::doQueueCommand(), Melee2hHeadHit3Command::doQueueCommand(), StandCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), StopwatchingCommand::doQueueCommand(), WatchCommand::doQueueCommand(), Melee1hHealthHit1Command::doQueueCommand(), ObjectCommand::doQueueCommand(), ListenCommand::doQueueCommand(), CreateVendorCommand::doQueueCommand(), GcwStatusCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), RequestStatMigrationDataCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), RequestStatMigrationStartCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), HarvesterDiscardHopperCommand::doQueueCommand(), HarvesterActivateCommand::doQueueCommand(), StopDanceCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), SetFactionCommand::doQueueCommand(), ServerDestroyObjectCommand::doQueueCommand(), StopMusicCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), FishCommand::doQueueCommand(), CreateCreatureCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), MakeLeaderCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), InviteCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), GiveItemCommand::doQueueCommand(), ScriptCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), BetCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), FindCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), RequestSurveyCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), ServerCommand::doQueueCommand(), RetreatCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), TipCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), and onLocomotionFail().
bool server::zone::objects::creature::commands::QueueCommand::checkStateMask (CreatureObject * creature) inline
Definition at line 170 of file QueueCommand.h.
References server::zone::objects::creature::CreatureObject::getStateBitmask(), and stateMask.
Referenced by CreatureRangedAttackCommand::doQueueCommand(), DefaultDroidAttackCommand::doQueueCommand(), MediumDiseaseCommand::doQueueCommand(), MediumPoisonCommand::doQueueCommand(), StrongDiseaseCommand::doQueueCommand(), StrongPoisonCommand::doQueueCommand(), MildDiseaseCommand::doQueueCommand(), MildPoisonCommand::doQueueCommand(), TurretFireCommand::doQueueCommand(), TurretFireManualCommand::doQueueCommand(), MinefieldAttackCommand::doQueueCommand(), SquadLeaderCommand::doQueueCommand(), DefaultAttackCommand::doQueueCommand(), DizzyAttackCommand::doQueueCommand(), PostureDownAttackCommand::doQueueCommand(), PostureUpAttackCommand::doQueueCommand(), IntimidationAttackCommand::doQueueCommand(), KnockdownAttackCommand::doQueueCommand(), BlindAttackCommand::doQueueCommand(), StunAttackCommand::doQueueCommand(), SurpriseShotCommand::doQueueCommand(), CreatureAreaBleedingCommand::doQueueCommand(), FireHeavyWeaponCommand::doQueueCommand(), CreatureAreaComboCommand::doQueueCommand(), CreatureAreaDiseaseCommand::doQueueCommand(), CreatureAreaKnockdownCommand::doQueueCommand(), CreatureAreaPoisonCommand::doQueueCommand(), CreatureAreaAttackCommand::doQueueCommand(), MultiTargetShotCommand::doQueueCommand(), ActionShot1Command::doQueueCommand(), UnarmedDizzy1Command::doQueueCommand(), BleedingShotCommand::doQueueCommand(), BurstShot1Command::doQueueCommand(), FormupCommand::doQueueCommand(), OverChargeShot1Command::doQueueCommand(), OverChargeShot2Command::doQueueCommand(), FullAutoArea1Command::doQueueCommand(), PanicShotCommand::doQueueCommand(), FullAutoArea2Command::doQueueCommand(), FullAutoSingle1Command::doQueueCommand(), FullAutoSingle2Command::doQueueCommand(), PistolMeleeDefense1Command::doQueueCommand(), PistolMeleeDefense2Command::doQueueCommand(), PointBlankArea1Command::doQueueCommand(), PointBlankSingle1Command::doQueueCommand(), PointBlankSingle2Command::doQueueCommand(), BurstShot2Command::doQueueCommand(), DisarmingShot1Command::doQueueCommand(), PolearmLunge1Command::doQueueCommand(), DisarmingShot2Command::doQueueCommand(), BodyShot1Command::doQueueCommand(), ThrowGrenadeCommand::doQueueCommand(), HeadShot1Command::doQueueCommand(), ChargeShot1Command::doQueueCommand(), ChargeShot2Command::doQueueCommand(), HeadShot3Command::doQueueCommand(), RallyCommand::doQueueCommand(), DoubleTapCommand::doQueueCommand(), RollShotCommand::doQueueCommand(), BodyShot2Command::doQueueCommand(), HealthShot1Command::doQueueCommand(), HealthShot2Command::doQueueCommand(), BodyShot3Command::doQueueCommand(), ConcealShotCommand::doQueueCommand(), EyeShotCommand::doQueueCommand(), FanShotCommand::doQueueCommand(), FastBlastCommand::doQueueCommand(), StoppingShotCommand::doQueueCommand(), ScatterShot1Command::doQueueCommand(), ScatterShot2Command::doQueueCommand(), KipUpShotCommand::doQueueCommand(), SetBoostmoraleCommand::doQueueCommand(), SetFormupCommand::doQueueCommand(), ConfusionShotCommand::doQueueCommand(), StartleShot1Command::doQueueCommand(), SetRetreatCommand::doQueueCommand(), SetSteadyaimCommand::doQueueCommand(), SniperShotCommand::doQueueCommand(), FireAcidCone1Command::doQueueCommand(), KnockdownFireCommand::doQueueCommand(), SprayShotCommand::doQueueCommand(), LastDitchCommand::doQueueCommand(), FireAcidCone2Command::doQueueCommand(), StartleShot2Command::doQueueCommand(), SteadyaimCommand::doQueueCommand(), FireAcidSingle1Command::doQueueCommand(), LegShot1Command::doQueueCommand(), UnarmedHit1Command::doQueueCommand(), FireAcidSingle2Command::doQueueCommand(), StrafeShot1Command::doQueueCommand(), StrafeShot2Command::doQueueCommand(), LegShot2Command::doQueueCommand(), LegShot3Command::doQueueCommand(), SuppressionFire1Command::doQueueCommand(), SuppressionFire2Command::doQueueCommand(), FireLightningCone1Command::doQueueCommand(), TauntCommand::doQueueCommand(), FireLightningCone2Command::doQueueCommand(), ThreatenShotCommand::doQueueCommand(), LowBlowCommand::doQueueCommand(), FireLightningSingle1Command::doQueueCommand(), TorsoShotCommand::doQueueCommand(), FireLightningSingle2Command::doQueueCommand(), FlameCone1Command::doQueueCommand(), UnarmedBlind1Command::doQueueCommand(), AimCommand::doQueueCommand(), FlameCone2Command::doQueueCommand(), UnarmedBodyHit1Command::doQueueCommand(), UnarmedCombo1Command::doQueueCommand(), UnarmedCombo2Command::doQueueCommand(), FlameSingle1Command::doQueueCommand(), UnarmedHeadHit1Command::doQueueCommand(), UnarmedHit2Command::doQueueCommand(), FlameSingle2Command::doQueueCommand(), UnarmedKnockdown1Command::doQueueCommand(), UnarmedKnockdown2Command::doQueueCommand(), UnarmedLegHit1Command::doQueueCommand(), FlurryShot1Command::doQueueCommand(), UnarmedSpinAttack1Command::doQueueCommand(), UnarmedSpinAttack2Command::doQueueCommand(), FlurryShot2Command::doQueueCommand(), UnderHandShotCommand::doQueueCommand(), FlushingShot1Command::doQueueCommand(), VolleyFireAttackCommand::doQueueCommand(), ActionShot2Command::doQueueCommand(), FlushingShot2Command::doQueueCommand(), WarningShotCommand::doQueueCommand(), WildShot1Command::doQueueCommand(), WildShot2Command::doQueueCommand(), Melee2hLunge1Command::doQueueCommand(), CripplingShotCommand::doQueueCommand(), UnarmedHit3Command::doQueueCommand(), MindShot2Command::doQueueCommand(), MindShot1Command::doQueueCommand(), MultiTargetPistolShotCommand::doQueueCommand(), Melee2hArea1Command::doQueueCommand(), OpenWingsCommand::doQueueCommand(), ForceWeaken2Command::doQueueCommand(), Melee1hBodyHit3Command::doQueueCommand(), AborthyperspaceCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), PilotShipCommand::doQueueCommand(), PointBlankArea2Command::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), ToggleDisplayingFactionRankCommand::doQueueCommand(), DestroyTargetCommand::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), DisableTargetCommand::doQueueCommand(), GmCreateClassResourceCommand::doQueueCommand(), GmCreateSpecificResourceCommand::doQueueCommand(), ChannelForceCommand::doQueueCommand(), PolearmLunge2Command::doQueueCommand(), UnpilotShipCommand::doQueueCommand(), DiveShotCommand::doQueueCommand(), Ptrap1Command::doQueueCommand(), Ptrap2Command::doQueueCommand(), PumpreactorCommand::doQueueCommand(), LootCommand::doQueueCommand(), HeadShot2Command::doQueueCommand(), DockCommand::doQueueCommand(), RequestBiographyCommand::doQueueCommand(), CheckForceStatusCommand::doQueueCommand(), RequestDraftSlotsBatchCommand::doQueueCommand(), RequestResourceWeightsBatchCommand::doQueueCommand(), RequestSpaceTrainerCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), DroidCommand::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), Saber1hComboHit2Command::doQueueCommand(), Melee1hHit1Command::doQueueCommand(), ForageCommand::doQueueCommand(), Epulse1Command::doQueueCommand(), Saber1hFlurryCommand::doQueueCommand(), Saber1hHeadHit1Command::doQueueCommand(), Saber1hHeadHit2Command::doQueueCommand(), AddPowerCommand::doQueueCommand(), Epulse2Command::doQueueCommand(), ClearVeteranRewardCommand::doQueueCommand(), Epulse3Command::doQueueCommand(), HyperspaceCommand::doQueueCommand(), EscapePodCommand::doQueueCommand(), IffscrambleCommand::doQueueCommand(), LfgCommand::doQueueCommand(), CloseWingsCommand::doQueueCommand(), EshieldsCommand::doQueueCommand(), InspacereloadCommand::doQueueCommand(), InspacerepairCommand::doQueueCommand(), EthrustCommand::doQueueCommand(), InspacerrCommand::doQueueCommand(), InspectCommand::doQueueCommand(), CreateMissionElementCommand::doQueueCommand(), EweaponsCommand::doQueueCommand(), InsureCommand::doQueueCommand(), Intimidate1Command::doQueueCommand(), LightEngineScrambleCommand::doQueueCommand(), NewbiehelperCommand::doQueueCommand(), Intimidate2Command::doQueueCommand(), ActivateQuestCommand::doQueueCommand(), Warcry1Command::doQueueCommand(), SaberThrow1Command::doQueueCommand(), SaberThrow2Command::doQueueCommand(), InvulnerableCommand::doQueueCommand(), SaberThrow3Command::doQueueCommand(), BoosterOffCommand::doQueueCommand(), Jstart1Command::doQueueCommand(), MindBlast2Command::doQueueCommand(), Jstart2Command::doQueueCommand(), ForceLightningCone2Command::doQueueCommand(), KillCommand::doQueueCommand(), Melee2hSweep2Command::doQueueCommand(), Melee2hSweep1Command::doQueueCommand(), ServerAsteroidDataListenCommand::doQueueCommand(), ServerAsteroidDataStopListeningCommand::doQueueCommand(), Melee2hMindHit2Command::doQueueCommand(), Jstart3Command::doQueueCommand(), KillPlayerCommand::doQueueCommand(), BoosterOnCommand::doQueueCommand(), Melee2hHit3Command::doQueueCommand(), LaunchCountermeasureCommand::doQueueCommand(), LaunchMissileCommand::doQueueCommand(), LeaveStationCommand::doQueueCommand(), SaberPolearmSpinAttack1Command::doQueueCommand(), SendFormObjectDataCommand::doQueueCommand(), VrepairCommand::doQueueCommand(), AddAllowedPlayerCommand::doQueueCommand(), Saber1hHit3Command::doQueueCommand(), Warcry2Command::doQueueCommand(), LootAllCommand::doQueueCommand(), SaberSlash2Command::doQueueCommand(), ToggleAwayFromKeyBoardCommand::doQueueCommand(), MedicalForageCommand::doQueueCommand(), UndockCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), SaberPolearmSpinAttack3Command::doQueueCommand(), UnarmedStun1Command::doQueueCommand(), Melee1hBlindHit1Command::doQueueCommand(), SaberSlash1Command::doQueueCommand(), SaberPolearmHit3Command::doQueueCommand(), SaberPolearmLegHit1Command::doQueueCommand(), Melee1hBlindHit2Command::doQueueCommand(), Melee1hBodyHit1Command::doQueueCommand(), SaberPolearmHit1Command::doQueueCommand(), SaberPolearmLegHit2Command::doQueueCommand(), UnarmedLunge1Command::doQueueCommand(), SaberPolearmLegHit3Command::doQueueCommand(), SaberPolearmHit2Command::doQueueCommand(), SaberPolearmDervishCommand::doQueueCommand(), Saber1hHeadHit3Command::doQueueCommand(), UnarmedLunge2Command::doQueueCommand(), Melee1hLunge1Command::doQueueCommand(), VolleyFireCommand::doQueueCommand(), Saber1hHit1Command::doQueueCommand(), VrepairotherCommand::doQueueCommand(), Saber1hHit2Command::doQueueCommand(), AttackCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), Melee2hHit1Command::doQueueCommand(), ForceIntimidate1Command::doQueueCommand(), Melee2hHit2Command::doQueueCommand(), Bstrike1Command::doQueueCommand(), ForceIntimidate2Command::doQueueCommand(), Melee2hLunge2Command::doQueueCommand(), ForceKnockdown1Command::doQueueCommand(), AnonCommand::doQueueCommand(), ForceKnockdown2Command::doQueueCommand(), ForceKnockdown3Command::doQueueCommand(), Saber1hComboHit1Command::doQueueCommand(), Saber1hComboHit3Command::doQueueCommand(), Bstrike2Command::doQueueCommand(), ForceLightningCone1Command::doQueueCommand(), MindBlast1Command::doQueueCommand(), ForceLightningSingle1Command::doQueueCommand(), Melee1hSpinAttack1Command::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), Bstrike3Command::doQueueCommand(), ForceThrow1Command::doQueueCommand(), ForceThrow2Command::doQueueCommand(), NblastCommand::doQueueCommand(), ForceWeaken1Command::doQueueCommand(), Melee1hDizzyHit1Command::doQueueCommand(), Melee1hBodyHit2Command::doQueueCommand(), PeaceCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), PolearmActionHit1Command::doQueueCommand(), PolearmActionHit2Command::doQueueCommand(), ActivateCloneCommand::doQueueCommand(), PolearmArea1Command::doQueueCommand(), PolearmStun1Command::doQueueCommand(), PolearmHit1Command::doQueueCommand(), PolearmHit2Command::doQueueCommand(), PolearmHit3Command::doQueueCommand(), PolearmLegHit2Command::doQueueCommand(), PolearmLegHit3Command::doQueueCommand(), PolearmSpinAttack1Command::doQueueCommand(), PolearmSpinAttack2Command::doQueueCommand(), HarvesterDeactivateCommand::doQueueCommand(), Melee1hLunge2Command::doQueueCommand(), PolearmSweep1Command::doQueueCommand(), PolearmSweep2Command::doQueueCommand(), Melee1hScatterHit1Command::doQueueCommand(), DismountCommand::doQueueCommand(), TakeCoverCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), RequestCharacterSheetInfoCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), TeleportToCommand::doQueueCommand(), PolearmStun2Command::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), PolearmArea2Command::doQueueCommand(), PolearmLegHit1Command::doQueueCommand(), Saber1hFlurry2Command::doQueueCommand(), Saber2hBodyHit1Command::doQueueCommand(), CloseContainerCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), Melee2hSpinAttack2Command::doQueueCommand(), MountCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), StoplisteningCommand::doQueueCommand(), DeclareresidenceCommand::doQueueCommand(), ForceLightningSingle2Command::doQueueCommand(), DeathBlowCommand::doQueueCommand(), Melee1hScatterHit2Command::doQueueCommand(), Melee2hSpinAttack1Command::doQueueCommand(), FindPlayerCommand::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), Melee1hDizzyHit2Command::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), Melee2hMindHit1Command::doQueueCommand(), Saber2hSweep3Command::doQueueCommand(), Melee2hArea3Command::doQueueCommand(), Melee2hHeadHit2Command::doQueueCommand(), Melee1hHit3Command::doQueueCommand(), RolePlayCommand::doQueueCommand(), Melee1hHit2Command::doQueueCommand(), AiIgnoreCommand::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), Melee1hHealthHit2Command::doQueueCommand(), Saber2hPhantomCommand::doQueueCommand(), Saber2hHit3Command::doQueueCommand(), SaberPolearmDervish2Command::doQueueCommand(), Saber2hBodyHit2Command::doQueueCommand(), Melee2hArea2Command::doQueueCommand(), Melee1hSpinAttack2Command::doQueueCommand(), Saber2hSweep2Command::doQueueCommand(), Saber2hFrenzyCommand::doQueueCommand(), Saber2hSweep1Command::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), Saber2hBodyHit3Command::doQueueCommand(), Saber2hHit2Command::doQueueCommand(), Saber2hHit1Command::doQueueCommand(), MeditateCommand::doQueueCommand(), SaberPolearmSpinAttack2Command::doQueueCommand(), KneelCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), ForceChokeCommand::doQueueCommand(), Melee2hHeadHit1Command::doQueueCommand(), Melee2hHeadHit3Command::doQueueCommand(), StandCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), StopwatchingCommand::doQueueCommand(), WatchCommand::doQueueCommand(), Melee1hHealthHit1Command::doQueueCommand(), ObjectCommand::doQueueCommand(), ListenCommand::doQueueCommand(), CreateVendorCommand::doQueueCommand(), GcwStatusCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), RequestStatMigrationDataCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), RequestStatMigrationStartCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), HarvesterDiscardHopperCommand::doQueueCommand(), HarvesterActivateCommand::doQueueCommand(), StopDanceCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), SetFactionCommand::doQueueCommand(), ServerDestroyObjectCommand::doQueueCommand(), StopMusicCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), FishCommand::doQueueCommand(), CreateCreatureCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), MakeLeaderCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), InviteCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), GiveItemCommand::doQueueCommand(), ScriptCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), BetCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), FindCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), RequestSurveyCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), ServerCommand::doQueueCommand(), RetreatCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), TipCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), and HealDamageCommand::doQueueCommand().
virtual int server::zone::objects::creature::commands::QueueCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline virtual
Reimplemented in HealDamageCommand, CurePackCommand, TotalHealOtherCommand, HealEnhanceCommand, HealWoundCommand, HealStateCommand, DotPackCommand, RevivePlayerCommand, TotalHealSelfCommand, HealActionWoundOther1Command, HealActionWoundOther2Command, HealHealthWoundOther1Command, HealHealthWoundOther2Command, HealMindWoundOther1Command, HealMindWoundOther2Command, HealAllOther1Command, HealAllOther2Command, TendCommand, HealStatesOtherCommand, TipCommand, ForceCureDiseaseCommand, ForceCurePoisonCommand, StopBleedingCommand, QuickHealCommand, DelegateFactionPointsCommand, BurstRunCommand, RetreatCommand, ServerCommand, BoardShuttleCommand, RequestSetStatMigrationDataCommand, UnconsentCommand, MoveFurnitureCommand, ConsentCommand, RequestSurveyCommand, CreateSpawningElementCommand, RequestCoreSampleCommand, BetCommand, FindCommand, FindFriendCommand, PlaceStructureModeCommand, WaypointCommand, GiveItemCommand, PurchaseTicketCommand, ScriptCommand, GenerateCraftedItemCommand, InviteCommand, RequestCraftingSessionCommand, TransferItemMiscCommand, AddIgnoreCommand, MakeLeaderCommand, PermissionListModifyCommand, TransferItemWeaponCommand, TransferstructureCommand, UninviteCommand, AddFriendCommand, BroadcastGalaxyCommand, CreateCreatureCommand, CreateVendorCommand, DeclineCommand, FishCommand, GcwStatusCommand, GetAccountInfoCommand, HarvestCorpseCommand, HarvesterActivateCommand, HarvesterDiscardHopperCommand, HarvesterSelectResourceCommand, ListenCommand, ObjectCommand, PowerBoostCommand, RegainConsciousnessCommand, RequestStatMigrationDataCommand, RequestStatMigrationStartCommand, ServerDestroyObjectCommand, SetExperienceCommand, SetFactionCommand, SetGodModeCommand, StopDanceCommand, StopMusicCommand, ThrowTrapCommand, TransferItemArmorCommand, TumbleToKneelingCommand, ActivateCloneCommand, AddBannedPlayerCommand, AiIgnoreCommand, BoostmoraleCommand, CloseContainerCommand, CreateManfSchematicCommand, CreatePrototypeCommand, DeathBlowCommand, DeclareresidenceCommand, DestroystructureCommand, DismountCommand, FindPlayerCommand, ForceChokeCommand, ForceLightningSingle2Command, HarvesterDeactivateCommand, HarvesterGetResourceDataCommand, ImagedesignCommand, KneelCommand, MeditateCommand, Melee1hBodyHit2Command, Melee1hDizzyHit1Command, Melee1hDizzyHit2Command, Melee1hHealthHit1Command, Melee1hHealthHit2Command, Melee1hHit2Command, Melee1hHit3Command, Melee1hLunge2Command, Melee1hScatterHit1Command, Melee1hScatterHit2Command, Melee1hSpinAttack2Command, Melee2hArea2Command, Melee2hArea3Command, Melee2hHeadHit1Command, Melee2hHeadHit2Command, Melee2hHeadHit3Command, Melee2hMindHit1Command, Melee2hSpinAttack1Command, Melee2hSpinAttack2Command, MountCommand, NameStructureCommand, NewbieSelectStartingLocationCommand, NextCraftingStageCommand, PeaceCommand, PlaceStructureCommand, PolearmActionHit1Command, PolearmActionHit2Command, PolearmArea1Command, PolearmArea2Command, PolearmHit1Command, PolearmHit2Command, PolearmHit3Command, PolearmLegHit1Command, PolearmLegHit2Command, PolearmLegHit3Command, PolearmSpinAttack1Command, PolearmSpinAttack2Command, PolearmStun1Command, PolearmStun2Command, PolearmSweep1Command, PolearmSweep2Command, RecruitSkillTrainerCommand, RequestCharacterSheetInfoCommand, RolePlayCommand, Saber1hFlurry2Command, Saber2hBodyHit1Command, Saber2hBodyHit2Command, Saber2hBodyHit3Command, Saber2hFrenzyCommand, Saber2hHit1Command, Saber2hHit2Command, Saber2hHit3Command, Saber2hPhantomCommand, Saber2hSweep1Command, Saber2hSweep2Command, Saber2hSweep3Command, SaberPolearmDervish2Command, SaberPolearmSpinAttack2Command, SelectDraftSchematicCommand, StandCommand, StoplisteningCommand, StopwatchingCommand, TakeCoverCommand, TeleportTargetCommand, TeleportToCommand, TumbleToStandingCommand, WatchCommand, WookieeRoarCommand, AborthyperspaceCommand, ActivateQuestCommand, AddAllowedPlayerCommand, AddPowerCommand, AnonCommand, AttackCommand, BoosterOffCommand, BoosterOnCommand, BroadcastAreaCommand, BroadcastCommand, BroadcastPlanetCommand, Bstrike1Command, Bstrike2Command, Bstrike3Command, ChannelForceCommand, CheckForceStatusCommand, ClearCompletedQuestCommand, ClearVeteranRewardCommand, CloseWingsCommand, CreateMissionElementCommand, DestroyTargetCommand, DisableTargetCommand, DiveShotCommand, DockCommand, DrainForceCommand, DroidCommand, Epulse1Command, Epulse2Command, Epulse3Command, EscapePodCommand, EshieldsCommand, EthrustCommand, EweaponsCommand, ForageCommand, ForceIntimidate1Command, ForceIntimidate2Command, ForceKnockdown1Command, ForceKnockdown2Command, ForceKnockdown3Command, ForceLightningCone1Command, ForceLightningCone2Command, ForceLightningSingle1Command, ForceMeditateCommand, ForceThrow1Command, ForceThrow2Command, ForceWeaken1Command, ForceWeaken2Command, GetPlayerIdCommand, GmCreateClassResourceCommand, GmCreateSpecificResourceCommand, HeadShot2Command, HyperspaceCommand, IffscrambleCommand, InspacereloadCommand, InspacerepairCommand, InspacerrCommand, InspectCommand, InsureCommand, Intimidate1Command, Intimidate2Command, InvulnerableCommand, Jstart1Command, Jstart2Command, Jstart3Command, KillCommand, KillPlayerCommand, LaunchCountermeasureCommand, LaunchMissileCommand, LeaveStationCommand, LfgCommand, LightEngineScrambleCommand, LootAllCommand, LootCommand, MedicalForageCommand, Melee1hBlindHit1Command, Melee1hBlindHit2Command, Melee1hBodyHit1Command, Melee1hBodyHit3Command, Melee1hHit1Command, Melee1hLunge1Command, Melee1hSpinAttack1Command, Melee2hArea1Command, Melee2hHit1Command, Melee2hHit2Command, Melee2hHit3Command, Melee2hLunge2Command, Melee2hMindHit2Command, Melee2hSweep1Command, Melee2hSweep2Command, MindBlast1Command, MindBlast2Command, NblastCommand, NewbiehelperCommand, OpenWingsCommand, PilotShipCommand, PointBlankArea2Command, PolearmLunge2Command, Ptrap1Command, Ptrap2Command, PumpreactorCommand, RequestBiographyCommand, RequestDraftSlotsBatchCommand, RequestResourceWeightsBatchCommand, RequestSpaceTrainerCommand, RotateFurnitureCommand, Saber1hComboHit1Command, Saber1hComboHit2Command, Saber1hComboHit3Command, Saber1hFlurryCommand, Saber1hHeadHit1Command, Saber1hHeadHit2Command, Saber1hHeadHit3Command, Saber1hHit1Command, Saber1hHit2Command, Saber1hHit3Command, SaberPolearmDervishCommand, SaberPolearmHit1Command, SaberPolearmHit2Command, SaberPolearmHit3Command, SaberPolearmLegHit1Command, SaberPolearmLegHit2Command, SaberPolearmLegHit3Command, SaberPolearmSpinAttack1Command, SaberPolearmSpinAttack3Command, SaberSlash1Command, SaberSlash2Command, SaberThrow1Command, SaberThrow2Command, SaberThrow3Command, SendFormObjectDataCommand, ServerAsteroidDataListenCommand, ServerAsteroidDataStopListeningCommand, ToggleAwayFromKeyBoardCommand, ToggleDisplayingFactionRankCommand, TumbleToProneCommand, UnarmedLunge1Command, UnarmedLunge2Command, UnarmedStun1Command, UndockCommand, UnpilotShipCommand, VolleyFireCommand, VrepairCommand, VrepairotherCommand, Warcry1Command, Warcry2Command, ActionShot1Command, ActionShot2Command, AimCommand, BleedingShotCommand, BodyShot1Command, BodyShot2Command, BodyShot3Command, BurstShot1Command, BurstShot2Command, ChargeShot1Command, ChargeShot2Command, ConcealShotCommand, ConfusionShotCommand, CripplingShotCommand, DisarmingShot1Command, DisarmingShot2Command, DoubleTapCommand, EyeShotCommand, FanShotCommand, FastBlastCommand, FireAcidCone1Command, FireAcidCone2Command, FireAcidSingle1Command, FireAcidSingle2Command, FireLightningCone1Command, FireLightningCone2Command, FireLightningSingle1Command, FireLightningSingle2Command, FlameCone1Command, FlameCone2Command, FlameSingle1Command, FlameSingle2Command, FlurryShot1Command, FlurryShot2Command, FlushingShot1Command, FlushingShot2Command, FormupCommand, FullAutoArea1Command, FullAutoArea2Command, FullAutoSingle1Command, FullAutoSingle2Command, HeadShot1Command, HeadShot3Command, HealthShot1Command, HealthShot2Command, KipUpShotCommand, KnockdownFireCommand, LastDitchCommand, LegShot1Command, LegShot2Command, LegShot3Command, LowBlowCommand, Melee2hLunge1Command, MindShot1Command, MindShot2Command, MultiTargetPistolShotCommand, OverChargeShot1Command, OverChargeShot2Command, PanicShotCommand, PistolMeleeDefense1Command, PistolMeleeDefense2Command, PointBlankArea1Command, PointBlankSingle1Command, PointBlankSingle2Command, PolearmLunge1Command, RallyCommand, RollShotCommand, ScatterShot1Command, ScatterShot2Command, SetBoostmoraleCommand, SetFormupCommand, SetRetreatCommand, SetSteadyaimCommand, SniperShotCommand, SprayShotCommand, StartleShot1Command, StartleShot2Command, SteadyaimCommand, StoppingShotCommand, StrafeShot1Command, StrafeShot2Command, SuppressionFire1Command, SuppressionFire2Command, TauntCommand, ThreatenShotCommand, ThrowGrenadeCommand, TorsoShotCommand, UnarmedBlind1Command, UnarmedBodyHit1Command, UnarmedCombo1Command, UnarmedCombo2Command, UnarmedDizzy1Command, UnarmedHeadHit1Command, UnarmedHit1Command, UnarmedHit2Command, UnarmedHit3Command, UnarmedKnockdown1Command, UnarmedKnockdown2Command, UnarmedLegHit1Command, UnarmedSpinAttack1Command, UnarmedSpinAttack2Command, UnderHandShotCommand, VolleyFireAttackCommand, WarningShotCommand, WildShot1Command, WildShot2Command, BlindAttackCommand, CreatureAreaAttackCommand, CreatureAreaBleedingCommand, CreatureAreaComboCommand, CreatureAreaDiseaseCommand, CreatureAreaKnockdownCommand, CreatureAreaPoisonCommand, DefaultAttackCommand, DizzyAttackCommand, FireHeavyWeaponCommand, IntimidationAttackCommand, KnockdownAttackCommand, MultiTargetShotCommand, PostureDownAttackCommand, PostureUpAttackCommand, StunAttackCommand, SurpriseShotCommand, SquadLeaderCommand, MinefieldAttackCommand, TurretFireCommand, TurretFireManualCommand, MediumDiseaseCommand, MediumPoisonCommand, MildDiseaseCommand, MildPoisonCommand, StrongDiseaseCommand, StrongPoisonCommand, DefaultDroidAttackCommand, and CreatureRangedAttackCommand.
Definition at line 163 of file QueueCommand.h.
References SUCCESS.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand().
String& server::zone::objects::creature::commands::QueueCommand::getCharacterAbility () inline
Definition at line 290 of file QueueCommand.h.
References characterAbility.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand().
virtual float server::zone::objects::creature::commands::QueueCommand::getCommandDuration (CreatureObject * object, const UnicodeString & arguments) inline virtual
Returns duration of the command
Reimplemented in CombatQueueCommand, ChannelForceCommand, ThrowGrenadeCommand, FireHeavyWeaponCommand, DrainForceCommand, ForcePowersQueueCommand, and HeavyWeaponQueueCommand.
Definition at line 178 of file QueueCommand.h.
References defaultTime.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand().
int server::zone::objects::creature::commands::QueueCommand::getCommandGroup () inline
Definition at line 329 of file QueueCommand.h.
References commandGroup.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand().
int server::zone::objects::creature::commands::QueueCommand::getDefaultPriority () inline
Definition at line 298 of file QueueCommand.h.
References defaultPriority.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand(), and server::zone::objects::creature::CreatureObjectImplementation::enqueueCommand().
float server::zone::objects::creature::commands::QueueCommand::getDefaultTime () inline
Definition at line 294 of file QueueCommand.h.
References defaultTime.
float server::zone::objects::creature::commands::QueueCommand::getMaxRange () inline
Definition at line 282 of file QueueCommand.h.
References maxRangeToTarget.
uint32 server::zone::objects::creature::commands::QueueCommand::getNameCRC () inline
Definition at line 278 of file QueueCommand.h.
References nameCRC.
Referenced by CombatManager::applyDots(), ForceWeaken2Command::doQueueCommand(), ForceWeaken1Command::doQueueCommand(), CreatureAttackData::getCommandCRC(), and server::zone::managers::objectcontroller::command::CommandList::put().
String& server::zone::objects::creature::commands::QueueCommand::getQueueCommandName () inline
Definition at line 286 of file QueueCommand.h.
References name.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand(), CreatureAttackData::getCommandName(), server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData(), and server::zone::managers::objectcontroller::command::CommandList::put().
int server::zone::objects::creature::commands::QueueCommand::getSkillMod (int index, String & skillMod) inline
Definition at line 324 of file QueueCommand.h.
References skillMods.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand().
int server::zone::objects::creature::commands::QueueCommand::getSkillModSize () inline
Definition at line 320 of file QueueCommand.h.
References skillMods.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand().
uint64 server::zone::objects::creature::commands::QueueCommand::getStateMask () inline
Definition at line 262 of file QueueCommand.h.
References stateMask.
virtual String server::zone::objects::creature::commands::QueueCommand::getSyntax () const inline virtual
Gets a string describing this commands syntax usage.
Definition at line 133 of file QueueCommand.h.
Referenced by onFail().
int server::zone::objects::creature::commands::QueueCommand::getTargetType () inline
Definition at line 274 of file QueueCommand.h.
References targetType.
virtual void server::zone::objects::creature::commands::QueueCommand::handleBuff (SceneObject * creature, ManagedObject * object, int64 param) inline virtual
Definition at line 347 of file QueueCommand.h.
Referenced by server::zone::objects::creature::buffs::SingleUseBuffObserverImplementation::notifyObserverEvent().
virtual bool server::zone::objects::creature::commands::QueueCommand::isCombatCommand () inline virtual
Reimplemented in CombatQueueCommand.
Definition at line 316 of file QueueCommand.h.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
bool server::zone::objects::creature::commands::QueueCommand::isDisabled () inline
Definition at line 305 of file QueueCommand.h.
References disabled.
bool server::zone::objects::creature::commands::QueueCommand::isWearingArmor (CreatureObject * creo) inline
Definition at line 337 of file QueueCommand.h.
References server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getSlottedObjectsSize(), and server::zone::objects::scene::SceneObject::isArmorObject().
Referenced by ChannelForceCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), ForceKnockdown1Command::doQueueCommand(), ForceThrow1Command::doQueueCommand(), SaberThrow3Command::doQueueCommand(), SaberThrow2Command::doQueueCommand(), Saber1hComboHit1Command::doQueueCommand(), SaberPolearmSpinAttack3Command::doQueueCommand(), SaberSlash2Command::doQueueCommand(), Saber1hComboHit2Command::doQueueCommand(), SaberThrow1Command::doQueueCommand(), SaberPolearmLegHit3Command::doQueueCommand(), SaberPolearmLegHit2Command::doQueueCommand(), SaberPolearmLegHit1Command::doQueueCommand(), ForceThrow2Command::doQueueCommand(), SaberPolearmHit2Command::doQueueCommand(), Saber1hComboHit3Command::doQueueCommand(), ForceKnockdown2Command::doQueueCommand(), ForceWeaken1Command::doQueueCommand(), Saber1hFlurryCommand::doQueueCommand(), Saber1hHeadHit1Command::doQueueCommand(), ForceWeaken2Command::doQueueCommand(), Saber1hHeadHit2Command::doQueueCommand(), Saber1hHeadHit3Command::doQueueCommand(), ForceKnockdown3Command::doQueueCommand(), Saber1hHit1Command::doQueueCommand(), Saber1hHit2Command::doQueueCommand(), Saber1hHit3Command::doQueueCommand(), ForceLightningCone1Command::doQueueCommand(), ForceIntimidate1Command::doQueueCommand(), ForceLightningCone2Command::doQueueCommand(), ForceLightningSingle1Command::doQueueCommand(), SaberPolearmDervishCommand::doQueueCommand(), ForceIntimidate2Command::doQueueCommand(), MindBlast1Command::doQueueCommand(), SaberPolearmHit1Command::doQueueCommand(), SaberPolearmHit3Command::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), MindBlast2Command::doQueueCommand(), SaberPolearmSpinAttack1Command::doQueueCommand(), SaberPolearmSpinAttack2Command::doQueueCommand(), Saber1hFlurry2Command::doQueueCommand(), Saber2hSweep1Command::doQueueCommand(), SaberPolearmDervish2Command::doQueueCommand(), Saber2hSweep3Command::doQueueCommand(), Saber2hHit1Command::doQueueCommand(), Saber2hHit3Command::doQueueCommand(), Saber2hBodyHit1Command::doQueueCommand(), Saber2hBodyHit2Command::doQueueCommand(), Saber2hBodyHit3Command::doQueueCommand(), Saber2hFrenzyCommand::doQueueCommand(), ForceChokeCommand::doQueueCommand(), Saber2hHit2Command::doQueueCommand(), Saber2hPhantomCommand::doQueueCommand(), Saber2hSweep2Command::doQueueCommand(), ForceLightningSingle2Command::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), and TotalHealOtherCommand::doQueueCommand().
void QueueCommand::onComplete (uint32 actioncntr, CreatureObject * creature, float commandDuration) virtual
Definition at line 172 of file QueueCommand.cpp.
References addToQueue, server::zone::objects::creature::CreatureObject::clearQueueAction(), and server::zone::objects::creature::CreatureObject::isPlayerCreature().
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand().
void QueueCommand::onFail (uint32 actioncntr, CreatureObject * creature, uint32 errorNumber) virtual
Definition at line 101 of file QueueCommand.cpp.
References addToQueue, server::zone::objects::creature::CreatureObject::clearQueueAction(), getSyntax(), server::zone::objects::creature::CreatureObject::getWeapon(), INSUFFICIENTPERMISSION, INVALIDLOCOMOTION, INVALIDSTATE, INVALIDSYNTAX, INVALIDTARGET, INVALIDWEAPON, NOJEDIARMOR, NOKNEELING, NOPRONE, onLocomotionFail(), onStateFail(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and TOOFAR.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand().
void QueueCommand::onLocomotionFail (CreatureObject * creature, uint32 actioncntr)
Definition at line 93 of file QueueCommand.cpp.
References checkInvalidLocomotions(), server::zone::objects::creature::CreatureObject::clearQueueAction(), and server::zone::objects::creature::CreatureObject::getLocomotion().
Referenced by onFail().
void QueueCommand::onStateFail (CreatureObject * creature, uint32 actioncntr)
Definition at line 69 of file QueueCommand.cpp.
References addToQueue, server::zone::objects::creature::CreatureObject::clearQueueAction(), server::zone::objects::creature::CreatureObject::getStateBitmask(), and stateMask.
Referenced by onFail().
bool server::zone::objects::creature::commands::QueueCommand::requiresAdmin () inline
Definition at line 266 of file QueueCommand.h.
References admin.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand().
void server::zone::objects::creature::commands::QueueCommand::setAddToCombatQueue (bool state) inline
Definition at line 217 of file QueueCommand.h.
References addToQueue.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), and server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void server::zone::objects::creature::commands::QueueCommand::setAddToCombatQueue (int state) inline
Definition at line 221 of file QueueCommand.h.
References addToQueue.
void server::zone::objects::creature::commands::QueueCommand::setCharacterAbility (const String & ability) inline
Definition at line 236 of file QueueCommand.h.
References admin, and characterAbility.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), and server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void server::zone::objects::creature::commands::QueueCommand::setCommandGroup (int val) inline
Definition at line 228 of file QueueCommand.h.
References commandGroup.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), and server::zone::managers::objectcontroller::command::CommandConfigManager::registerSpecialCommands().
void server::zone::objects::creature::commands::QueueCommand::setDefaultPriority (const String & priority) inline
Definition at line 243 of file QueueCommand.h.
References defaultPriority, FRONT, IMMEDIATE, and NORMAL.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), and server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void server::zone::objects::creature::commands::QueueCommand::setDefaultPriority (const int priority) inline
Definition at line 254 of file QueueCommand.h.
References defaultPriority.
void server::zone::objects::creature::commands::QueueCommand::setDefaultTime (float time) inline
Definition at line 198 of file QueueCommand.h.
References defaultTime.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), and server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void server::zone::objects::creature::commands::QueueCommand::setDisabled (bool state) inline
Definition at line 206 of file QueueCommand.h.
References disabled.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void server::zone::objects::creature::commands::QueueCommand::setDisabled (int state) inline
Definition at line 210 of file QueueCommand.h.
References disabled.
void QueueCommand::setInvalidLocomotions (const String & lStr)
Definition at line 43 of file QueueCommand.cpp.
References invalidLocomotion.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void server::zone::objects::creature::commands::QueueCommand::setMaxRange (float r) inline
Definition at line 232 of file QueueCommand.h.
References maxRangeToTarget.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), and server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void server::zone::objects::creature::commands::QueueCommand::setStateMask (uint64 mask) inline
Definition at line 188 of file QueueCommand.h.
References stateMask.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), and server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
void server::zone::objects::creature::commands::QueueCommand::setTargetType (int num) inline
Definition at line 202 of file QueueCommand.h.
References targetType.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), and server::zone::managers::objectcontroller::command::CommandConfigManager::parseVariableData().
Member Data Documentation
bool server::zone::objects::creature::commands::QueueCommand::addToQueue protected
Definition at line 81 of file QueueCommand.h.
Referenced by addToCombatQueue(), onComplete(), onFail(), onStateFail(), QueueCommand(), and setAddToCombatQueue().
bool server::zone::objects::creature::commands::QueueCommand::admin protected
Definition at line 82 of file QueueCommand.h.
Referenced by GetPlayerIdCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), QueueCommand(), requiresAdmin(), and setCharacterAbility().
String server::zone::objects::creature::commands::QueueCommand::characterAbility protected
Definition at line 88 of file QueueCommand.h.
Referenced by getCharacterAbility(), and setCharacterAbility().
int server::zone::objects::creature::commands::QueueCommand::commandGroup protected
Definition at line 94 of file QueueCommand.h.
Referenced by getCommandGroup(), QueueCommand(), and setCommandGroup().
uint32 server::zone::objects::creature::commands::QueueCommand::cooldown protected
Definition at line 84 of file QueueCommand.h.
Referenced by ThrowTrapCommand::doQueueCommand(), and QueueCommand().
int server::zone::objects::creature::commands::QueueCommand::defaultPriority protected
Definition at line 90 of file QueueCommand.h.
Referenced by getDefaultPriority(), QueueCommand(), and setDefaultPriority().
float server::zone::objects::creature::commands::QueueCommand::defaultTime protected
Definition at line 86 of file QueueCommand.h.
Referenced by HeavyWeaponQueueCommand::getCommandDuration(), ForcePowersQueueCommand::getCommandDuration(), DrainForceCommand::getCommandDuration(), FireHeavyWeaponCommand::getCommandDuration(), ChannelForceCommand::getCommandDuration(), ThrowGrenadeCommand::getCommandDuration(), getCommandDuration(), getDefaultTime(), QueueCommand(), and setDefaultTime().
bool server::zone::objects::creature::commands::QueueCommand::disabled protected
Definition at line 80 of file QueueCommand.h.
Referenced by isDisabled(), QueueCommand(), and setDisabled().
const int server::zone::objects::creature::commands::QueueCommand::FRONT = 1 static
Definition at line 100 of file QueueCommand.h.
Referenced by setDefaultPriority().
const int server::zone::objects::creature::commands::QueueCommand::GENERALERROR = 1 static
Definition at line 104 of file QueueCommand.h.
Referenced by HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), DelegateFactionPointsCommand::doDelegate(), StrongDiseaseCommand::doQueueCommand(), StrongPoisonCommand::doQueueCommand(), MediumDiseaseCommand::doQueueCommand(), MediumPoisonCommand::doQueueCommand(), MildDiseaseCommand::doQueueCommand(), MildPoisonCommand::doQueueCommand(), DefaultAttackCommand::doQueueCommand(), BlindAttackCommand::doQueueCommand(), StunAttackCommand::doQueueCommand(), DizzyAttackCommand::doQueueCommand(), IntimidationAttackCommand::doQueueCommand(), KnockdownAttackCommand::doQueueCommand(), FireHeavyWeaponCommand::doQueueCommand(), CreatureAreaAttackCommand::doQueueCommand(), CreatureAreaBleedingCommand::doQueueCommand(), CreatureAreaComboCommand::doQueueCommand(), PostureDownAttackCommand::doQueueCommand(), CreatureAreaDiseaseCommand::doQueueCommand(), PostureUpAttackCommand::doQueueCommand(), CreatureAreaKnockdownCommand::doQueueCommand(), CreatureAreaPoisonCommand::doQueueCommand(), SetBoostmoraleCommand::doQueueCommand(), SetFormupCommand::doQueueCommand(), SetRetreatCommand::doQueueCommand(), SetSteadyaimCommand::doQueueCommand(), SteadyaimCommand::doQueueCommand(), SniperShotCommand::doQueueCommand(), ThrowGrenadeCommand::doQueueCommand(), FormupCommand::doQueueCommand(), RallyCommand::doQueueCommand(), Warcry2Command::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), ToggleAwayFromKeyBoardCommand::doQueueCommand(), ToggleDisplayingFactionRankCommand::doQueueCommand(), InsureCommand::doQueueCommand(), Intimidate1Command::doQueueCommand(), DrainForceCommand::doQueueCommand(), Intimidate2Command::doQueueCommand(), InvulnerableCommand::doQueueCommand(), VolleyFireCommand::doQueueCommand(), Warcry1Command::doQueueCommand(), KillPlayerCommand::doQueueCommand(), KillCommand::doQueueCommand(), LfgCommand::doQueueCommand(), LootCommand::doQueueCommand(), MedicalForageCommand::doQueueCommand(), ForageCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), AnonCommand::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), NewbiehelperCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), RequestBiographyCommand::doQueueCommand(), ChannelForceCommand::doQueueCommand(), RequestDraftSlotsBatchCommand::doQueueCommand(), RequestResourceWeightsBatchCommand::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), CloseContainerCommand::doQueueCommand(), StoplisteningCommand::doQueueCommand(), StopwatchingCommand::doQueueCommand(), DismountCommand::doQueueCommand(), TakeCoverCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), WatchCommand::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), ActivateCloneCommand::doQueueCommand(), MeditateCommand::doQueueCommand(), ForceChokeCommand::doQueueCommand(), MountCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), RequestCharacterSheetInfoCommand::doQueueCommand(), HarvesterDeactivateCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), RolePlayCommand::doQueueCommand(), ServerDestroyObjectCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), StopDanceCommand::doQueueCommand(), StopMusicCommand::doQueueCommand(), CreateCreatureCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), ListenCommand::doQueueCommand(), FishCommand::doQueueCommand(), CreateVendorCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), GcwStatusCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), HarvesterActivateCommand::doQueueCommand(), HarvesterDiscardHopperCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), MakeLeaderCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), InviteCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), GiveItemCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), BetCommand::doQueueCommand(), FindCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), RequestSurveyCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), ServerCommand::doQueueCommand(), RetreatCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), TipCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), TransferstructureCommand::doTransferStructure(), TipCommand::performBankTip(), and TipCommand::performTip().
const int server::zone::objects::creature::commands::QueueCommand::IMMEDIATE = 0 static
Definition at line 99 of file QueueCommand.h.
Referenced by setDefaultPriority().
const int server::zone::objects::creature::commands::QueueCommand::INSUFFICIENTHAM = 7 static
Definition at line 110 of file QueueCommand.h.
Referenced by CombatQueueCommand::doCombatAction(), TumbleToProneCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), and DotPackCommand::doQueueCommand().
const int server::zone::objects::creature::commands::QueueCommand::INSUFFICIENTPERMISSION = 11 static
Definition at line 114 of file QueueCommand.h.
Referenced by ActivateQuestCommand::doQueueCommand(), AddAllowedPlayerCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), ClearVeteranRewardCommand::doQueueCommand(), KillCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), AiIgnoreCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), and onFail().
Vector<int> server::zone::objects::creature::commands::QueueCommand::invalidLocomotion protected
Definition at line 75 of file QueueCommand.h.
Referenced by addInvalidLocomotion(), checkInvalidLocomotions(), and setInvalidLocomotions().
const int server::zone::objects::creature::commands::QueueCommand::INVALIDLOCOMOTION = 2 static
Definition at line 105 of file QueueCommand.h.
Referenced by CombatQueueCommand::doCombatAction(), CreatureRangedAttackCommand::doQueueCommand(), DefaultDroidAttackCommand::doQueueCommand(), MediumDiseaseCommand::doQueueCommand(), MediumPoisonCommand::doQueueCommand(), StrongDiseaseCommand::doQueueCommand(), StrongPoisonCommand::doQueueCommand(), MildDiseaseCommand::doQueueCommand(), MildPoisonCommand::doQueueCommand(), TurretFireCommand::doQueueCommand(), TurretFireManualCommand::doQueueCommand(), MinefieldAttackCommand::doQueueCommand(), SquadLeaderCommand::doQueueCommand(), BlindAttackCommand::doQueueCommand(), DefaultAttackCommand::doQueueCommand(), DizzyAttackCommand::doQueueCommand(), PostureDownAttackCommand::doQueueCommand(), PostureUpAttackCommand::doQueueCommand(), IntimidationAttackCommand::doQueueCommand(), KnockdownAttackCommand::doQueueCommand(), StunAttackCommand::doQueueCommand(), SurpriseShotCommand::doQueueCommand(), CreatureAreaBleedingCommand::doQueueCommand(), FireHeavyWeaponCommand::doQueueCommand(), CreatureAreaComboCommand::doQueueCommand(), CreatureAreaDiseaseCommand::doQueueCommand(), CreatureAreaKnockdownCommand::doQueueCommand(), CreatureAreaPoisonCommand::doQueueCommand(), CreatureAreaAttackCommand::doQueueCommand(), MultiTargetShotCommand::doQueueCommand(), UnarmedSpinAttack2Command::doQueueCommand(), UnarmedCombo2Command::doQueueCommand(), BleedingShotCommand::doQueueCommand(), FormupCommand::doQueueCommand(), OverChargeShot1Command::doQueueCommand(), FullAutoArea1Command::doQueueCommand(), OverChargeShot2Command::doQueueCommand(), PanicShotCommand::doQueueCommand(), BurstShot1Command::doQueueCommand(), FullAutoArea2Command::doQueueCommand(), PistolMeleeDefense1Command::doQueueCommand(), FullAutoSingle1Command::doQueueCommand(), PistolMeleeDefense2Command::doQueueCommand(), FullAutoSingle2Command::doQueueCommand(), PointBlankArea1Command::doQueueCommand(), PointBlankSingle1Command::doQueueCommand(), BurstShot2Command::doQueueCommand(), PointBlankSingle2Command::doQueueCommand(), DisarmingShot1Command::doQueueCommand(), PolearmLunge1Command::doQueueCommand(), DisarmingShot2Command::doQueueCommand(), ThrowGrenadeCommand::doQueueCommand(), BodyShot1Command::doQueueCommand(), ChargeShot1Command::doQueueCommand(), HeadShot1Command::doQueueCommand(), RallyCommand::doQueueCommand(), ChargeShot2Command::doQueueCommand(), HeadShot3Command::doQueueCommand(), DoubleTapCommand::doQueueCommand(), SuppressionFire2Command::doQueueCommand(), RollShotCommand::doQueueCommand(), BodyShot2Command::doQueueCommand(), HealthShot1Command::doQueueCommand(), HealthShot2Command::doQueueCommand(), BodyShot3Command::doQueueCommand(), ConcealShotCommand::doQueueCommand(), ConfusionShotCommand::doQueueCommand(), EyeShotCommand::doQueueCommand(), FanShotCommand::doQueueCommand(), ScatterShot1Command::doQueueCommand(), ScatterShot2Command::doQueueCommand(), FastBlastCommand::doQueueCommand(), SetBoostmoraleCommand::doQueueCommand(), StartleShot2Command::doQueueCommand(), ActionShot1Command::doQueueCommand(), SetFormupCommand::doQueueCommand(), SetRetreatCommand::doQueueCommand(), SetSteadyaimCommand::doQueueCommand(), FireAcidCone1Command::doQueueCommand(), SniperShotCommand::doQueueCommand(), SprayShotCommand::doQueueCommand(), KipUpShotCommand::doQueueCommand(), KnockdownFireCommand::doQueueCommand(), FireAcidCone2Command::doQueueCommand(), LastDitchCommand::doQueueCommand(), StartleShot1Command::doQueueCommand(), SteadyaimCommand::doQueueCommand(), StoppingShotCommand::doQueueCommand(), UnarmedLegHit1Command::doQueueCommand(), LegShot1Command::doQueueCommand(), StrafeShot1Command::doQueueCommand(), LegShot2Command::doQueueCommand(), StrafeShot2Command::doQueueCommand(), FireAcidSingle1Command::doQueueCommand(), LegShot3Command::doQueueCommand(), SuppressionFire1Command::doQueueCommand(), FireAcidSingle2Command::doQueueCommand(), TauntCommand::doQueueCommand(), FireLightningCone1Command::doQueueCommand(), ThreatenShotCommand::doQueueCommand(), FireLightningSingle1Command::doQueueCommand(), LowBlowCommand::doQueueCommand(), TorsoShotCommand::doQueueCommand(), FireLightningCone2Command::doQueueCommand(), FireLightningSingle2Command::doQueueCommand(), FlameCone1Command::doQueueCommand(), FlameCone2Command::doQueueCommand(), UnarmedBlind1Command::doQueueCommand(), UnarmedBodyHit1Command::doQueueCommand(), UnarmedCombo1Command::doQueueCommand(), UnarmedDizzy1Command::doQueueCommand(), UnarmedHeadHit1Command::doQueueCommand(), UnarmedHit1Command::doQueueCommand(), FlameSingle1Command::doQueueCommand(), UnarmedHit3Command::doQueueCommand(), UnarmedKnockdown1Command::doQueueCommand(), UnarmedKnockdown2Command::doQueueCommand(), FlameSingle2Command::doQueueCommand(), UnarmedSpinAttack1Command::doQueueCommand(), ActionShot2Command::doQueueCommand(), FlurryShot1Command::doQueueCommand(), UnderHandShotCommand::doQueueCommand(), FlurryShot2Command::doQueueCommand(), VolleyFireAttackCommand::doQueueCommand(), AimCommand::doQueueCommand(), FlushingShot1Command::doQueueCommand(), FlushingShot2Command::doQueueCommand(), WarningShotCommand::doQueueCommand(), WildShot1Command::doQueueCommand(), WildShot2Command::doQueueCommand(), Melee2hLunge1Command::doQueueCommand(), UnarmedHit2Command::doQueueCommand(), CripplingShotCommand::doQueueCommand(), MindShot1Command::doQueueCommand(), MindShot2Command::doQueueCommand(), MultiTargetPistolShotCommand::doQueueCommand(), ToggleDisplayingFactionRankCommand::doQueueCommand(), ForceWeaken1Command::doQueueCommand(), OpenWingsCommand::doQueueCommand(), ForceWeaken2Command::doQueueCommand(), Melee1hBodyHit3Command::doQueueCommand(), AborthyperspaceCommand::doQueueCommand(), PilotShipCommand::doQueueCommand(), Melee1hBlindHit1Command::doQueueCommand(), PointBlankArea2Command::doQueueCommand(), MedicalForageCommand::doQueueCommand(), DestroyTargetCommand::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), GmCreateClassResourceCommand::doQueueCommand(), DisableTargetCommand::doQueueCommand(), GmCreateSpecificResourceCommand::doQueueCommand(), ChannelForceCommand::doQueueCommand(), PolearmLunge2Command::doQueueCommand(), UndockCommand::doQueueCommand(), UnpilotShipCommand::doQueueCommand(), Ptrap1Command::doQueueCommand(), Ptrap2Command::doQueueCommand(), PumpreactorCommand::doQueueCommand(), DiveShotCommand::doQueueCommand(), HeadShot2Command::doQueueCommand(), LootCommand::doQueueCommand(), RequestBiographyCommand::doQueueCommand(), DockCommand::doQueueCommand(), RequestDraftSlotsBatchCommand::doQueueCommand(), RequestResourceWeightsBatchCommand::doQueueCommand(), RequestSpaceTrainerCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), CheckForceStatusCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), Saber1hComboHit1Command::doQueueCommand(), CreateMissionElementCommand::doQueueCommand(), LfgCommand::doQueueCommand(), AddPowerCommand::doQueueCommand(), DroidCommand::doQueueCommand(), Saber1hComboHit3Command::doQueueCommand(), Saber1hFlurryCommand::doQueueCommand(), ClearVeteranRewardCommand::doQueueCommand(), Saber1hHeadHit2Command::doQueueCommand(), Epulse1Command::doQueueCommand(), Epulse2Command::doQueueCommand(), Saber1hHit3Command::doQueueCommand(), Epulse3Command::doQueueCommand(), HyperspaceCommand::doQueueCommand(), IffscrambleCommand::doQueueCommand(), CloseWingsCommand::doQueueCommand(), EscapePodCommand::doQueueCommand(), InspacereloadCommand::doQueueCommand(), EshieldsCommand::doQueueCommand(), InspacerepairCommand::doQueueCommand(), InspacerrCommand::doQueueCommand(), ActivateQuestCommand::doQueueCommand(), EthrustCommand::doQueueCommand(), InspectCommand::doQueueCommand(), InsureCommand::doQueueCommand(), EweaponsCommand::doQueueCommand(), Intimidate1Command::doQueueCommand(), NewbiehelperCommand::doQueueCommand(), Intimidate2Command::doQueueCommand(), SaberSlash2Command::doQueueCommand(), SaberThrow1Command::doQueueCommand(), SaberThrow2Command::doQueueCommand(), SaberThrow3Command::doQueueCommand(), AddAllowedPlayerCommand::doQueueCommand(), Melee1hSpinAttack1Command::doQueueCommand(), InvulnerableCommand::doQueueCommand(), Jstart1Command::doQueueCommand(), BoosterOffCommand::doQueueCommand(), MindBlast1Command::doQueueCommand(), ForceLightningCone1Command::doQueueCommand(), Melee2hSweep2Command::doQueueCommand(), Jstart2Command::doQueueCommand(), Melee2hSweep1Command::doQueueCommand(), SendFormObjectDataCommand::doQueueCommand(), Jstart3Command::doQueueCommand(), LeaveStationCommand::doQueueCommand(), KillCommand::doQueueCommand(), Melee2hLunge2Command::doQueueCommand(), KillPlayerCommand::doQueueCommand(), LaunchCountermeasureCommand::doQueueCommand(), Melee2hHit2Command::doQueueCommand(), LaunchMissileCommand::doQueueCommand(), BoosterOnCommand::doQueueCommand(), Saber1hHeadHit1Command::doQueueCommand(), SaberPolearmSpinAttack1Command::doQueueCommand(), AnonCommand::doQueueCommand(), UnarmedLunge2Command::doQueueCommand(), ServerAsteroidDataStopListeningCommand::doQueueCommand(), ServerAsteroidDataListenCommand::doQueueCommand(), LightEngineScrambleCommand::doQueueCommand(), Warcry1Command::doQueueCommand(), LootAllCommand::doQueueCommand(), VrepairotherCommand::doQueueCommand(), Melee1hHit1Command::doQueueCommand(), ToggleAwayFromKeyBoardCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), SaberPolearmSpinAttack3Command::doQueueCommand(), SaberSlash1Command::doQueueCommand(), VolleyFireCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), SaberPolearmHit3Command::doQueueCommand(), SaberPolearmLegHit1Command::doQueueCommand(), Melee1hBlindHit2Command::doQueueCommand(), SaberPolearmHit1Command::doQueueCommand(), SaberPolearmLegHit2Command::doQueueCommand(), Melee1hBodyHit1Command::doQueueCommand(), SaberPolearmLegHit3Command::doQueueCommand(), SaberPolearmHit2Command::doQueueCommand(), SaberPolearmDervishCommand::doQueueCommand(), UnarmedLunge1Command::doQueueCommand(), Saber1hHeadHit3Command::doQueueCommand(), UnarmedStun1Command::doQueueCommand(), Melee1hLunge1Command::doQueueCommand(), Saber1hHit1Command::doQueueCommand(), VrepairCommand::doQueueCommand(), Saber1hHit2Command::doQueueCommand(), BroadcastCommand::doQueueCommand(), AttackCommand::doQueueCommand(), ForageCommand::doQueueCommand(), Melee2hArea1Command::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), Melee2hHit1Command::doQueueCommand(), Bstrike1Command::doQueueCommand(), Melee2hHit3Command::doQueueCommand(), ForceIntimidate1Command::doQueueCommand(), ForceIntimidate2Command::doQueueCommand(), ForceKnockdown1Command::doQueueCommand(), Melee2hMindHit2Command::doQueueCommand(), ForceKnockdown2Command::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), Saber1hComboHit2Command::doQueueCommand(), Warcry2Command::doQueueCommand(), ForceKnockdown3Command::doQueueCommand(), Bstrike2Command::doQueueCommand(), ForceLightningCone2Command::doQueueCommand(), MindBlast2Command::doQueueCommand(), ForceLightningSingle1Command::doQueueCommand(), Bstrike3Command::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), ForceThrow1Command::doQueueCommand(), NblastCommand::doQueueCommand(), ForceThrow2Command::doQueueCommand(), Melee2hHeadHit3Command::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), Melee1hLunge2Command::doQueueCommand(), Melee1hHealthHit2Command::doQueueCommand(), Melee1hBodyHit2Command::doQueueCommand(), Melee1hHit3Command::doQueueCommand(), PeaceCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), PolearmActionHit1Command::doQueueCommand(), PolearmActionHit2Command::doQueueCommand(), PolearmArea1Command::doQueueCommand(), ActivateCloneCommand::doQueueCommand(), PolearmArea2Command::doQueueCommand(), PolearmHit2Command::doQueueCommand(), PolearmLegHit1Command::doQueueCommand(), PolearmLegHit2Command::doQueueCommand(), PolearmLegHit3Command::doQueueCommand(), RequestCharacterSheetInfoCommand::doQueueCommand(), PolearmSpinAttack1Command::doQueueCommand(), TakeCoverCommand::doQueueCommand(), DismountCommand::doQueueCommand(), PolearmSpinAttack2Command::doQueueCommand(), TeleportToCommand::doQueueCommand(), PolearmStun2Command::doQueueCommand(), PolearmSweep1Command::doQueueCommand(), HarvesterDeactivateCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), PolearmSweep2Command::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), RolePlayCommand::doQueueCommand(), PolearmStun1Command::doQueueCommand(), Saber1hFlurry2Command::doQueueCommand(), PolearmHit1Command::doQueueCommand(), PolearmHit3Command::doQueueCommand(), CloseContainerCommand::doQueueCommand(), Saber2hBodyHit2Command::doQueueCommand(), ImagedesignCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), Melee1hHealthHit1Command::doQueueCommand(), Melee2hSpinAttack1Command::doQueueCommand(), DeathBlowCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), StopwatchingCommand::doQueueCommand(), Melee1hDizzyHit2Command::doQueueCommand(), Melee2hSpinAttack2Command::doQueueCommand(), MountCommand::doQueueCommand(), Melee1hDizzyHit1Command::doQueueCommand(), FindPlayerCommand::doQueueCommand(), KneelCommand::doQueueCommand(), StandCommand::doQueueCommand(), Melee2hMindHit1Command::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), Melee1hScatterHit1Command::doQueueCommand(), SaberPolearmDervish2Command::doQueueCommand(), Melee2hHeadHit1Command::doQueueCommand(), Melee1hSpinAttack2Command::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), Saber2hBodyHit3Command::doQueueCommand(), Saber2hHit2Command::doQueueCommand(), Saber2hPhantomCommand::doQueueCommand(), Melee1hScatterHit2Command::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), Melee1hHit2Command::doQueueCommand(), Saber2hFrenzyCommand::doQueueCommand(), Saber2hSweep1Command::doQueueCommand(), SaberPolearmSpinAttack2Command::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), Saber2hBodyHit1Command::doQueueCommand(), Saber2hSweep2Command::doQueueCommand(), Saber2hHit1Command::doQueueCommand(), Saber2hHit3Command::doQueueCommand(), Saber2hSweep3Command::doQueueCommand(), WatchCommand::doQueueCommand(), Melee2hArea3Command::doQueueCommand(), MeditateCommand::doQueueCommand(), AiIgnoreCommand::doQueueCommand(), Melee2hArea2Command::doQueueCommand(), ForceChokeCommand::doQueueCommand(), Melee2hHeadHit2Command::doQueueCommand(), DeclareresidenceCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), StoplisteningCommand::doQueueCommand(), ForceLightningSingle2Command::doQueueCommand(), ObjectCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), HarvesterDiscardHopperCommand::doQueueCommand(), RequestStatMigrationStartCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), HarvesterActivateCommand::doQueueCommand(), RequestStatMigrationDataCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), ListenCommand::doQueueCommand(), FishCommand::doQueueCommand(), GcwStatusCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), CreateVendorCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), StopMusicCommand::doQueueCommand(), ServerDestroyObjectCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), CreateCreatureCommand::doQueueCommand(), SetFactionCommand::doQueueCommand(), StopDanceCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), MakeLeaderCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), InviteCommand::doQueueCommand(), GiveItemCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), ScriptCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), BetCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), FindCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), RequestSurveyCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), ServerCommand::doQueueCommand(), RetreatCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), TipCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), and onFail().
const int server::zone::objects::creature::commands::QueueCommand::INVALIDPARAMETERS = 8 static
Definition at line 111 of file QueueCommand.h.
Referenced by FireHeavyWeaponCommand::doQueueCommand(), ThrowGrenadeCommand::doQueueCommand(), AddPowerCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), KillCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), GmCreateClassResourceCommand::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), GmCreateSpecificResourceCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), DeclareresidenceCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), TeleportToCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), SetFactionCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), and TipCommand::doQueueCommand().
const int server::zone::objects::creature::commands::QueueCommand::INVALIDSTATE = 3 static
Definition at line 106 of file QueueCommand.h.
Referenced by CreatureRangedAttackCommand::doQueueCommand(), DefaultDroidAttackCommand::doQueueCommand(), MediumDiseaseCommand::doQueueCommand(), MediumPoisonCommand::doQueueCommand(), StrongDiseaseCommand::doQueueCommand(), StrongPoisonCommand::doQueueCommand(), MildDiseaseCommand::doQueueCommand(), MildPoisonCommand::doQueueCommand(), TurretFireCommand::doQueueCommand(), TurretFireManualCommand::doQueueCommand(), MinefieldAttackCommand::doQueueCommand(), SquadLeaderCommand::doQueueCommand(), DefaultAttackCommand::doQueueCommand(), DizzyAttackCommand::doQueueCommand(), PostureDownAttackCommand::doQueueCommand(), PostureUpAttackCommand::doQueueCommand(), IntimidationAttackCommand::doQueueCommand(), KnockdownAttackCommand::doQueueCommand(), BlindAttackCommand::doQueueCommand(), StunAttackCommand::doQueueCommand(), SurpriseShotCommand::doQueueCommand(), CreatureAreaBleedingCommand::doQueueCommand(), FireHeavyWeaponCommand::doQueueCommand(), CreatureAreaComboCommand::doQueueCommand(), CreatureAreaDiseaseCommand::doQueueCommand(), CreatureAreaKnockdownCommand::doQueueCommand(), CreatureAreaPoisonCommand::doQueueCommand(), CreatureAreaAttackCommand::doQueueCommand(), MultiTargetShotCommand::doQueueCommand(), UnarmedHeadHit1Command::doQueueCommand(), ActionShot1Command::doQueueCommand(), UnarmedCombo2Command::doQueueCommand(), BleedingShotCommand::doQueueCommand(), BurstShot1Command::doQueueCommand(), FormupCommand::doQueueCommand(), OverChargeShot1Command::doQueueCommand(), OverChargeShot2Command::doQueueCommand(), FullAutoArea1Command::doQueueCommand(), PanicShotCommand::doQueueCommand(), FullAutoArea2Command::doQueueCommand(), FullAutoSingle1Command::doQueueCommand(), FullAutoSingle2Command::doQueueCommand(), PistolMeleeDefense1Command::doQueueCommand(), PistolMeleeDefense2Command::doQueueCommand(), PointBlankArea1Command::doQueueCommand(), PointBlankSingle1Command::doQueueCommand(), PointBlankSingle2Command::doQueueCommand(), BurstShot2Command::doQueueCommand(), DisarmingShot1Command::doQueueCommand(), PolearmLunge1Command::doQueueCommand(), DisarmingShot2Command::doQueueCommand(), ThrowGrenadeCommand::doQueueCommand(), ThreatenShotCommand::doQueueCommand(), BodyShot1Command::doQueueCommand(), HeadShot1Command::doQueueCommand(), ChargeShot1Command::doQueueCommand(), ChargeShot2Command::doQueueCommand(), HeadShot3Command::doQueueCommand(), RallyCommand::doQueueCommand(), SuppressionFire2Command::doQueueCommand(), DoubleTapCommand::doQueueCommand(), RollShotCommand::doQueueCommand(), BodyShot2Command::doQueueCommand(), HealthShot1Command::doQueueCommand(), HealthShot2Command::doQueueCommand(), BodyShot3Command::doQueueCommand(), ConcealShotCommand::doQueueCommand(), StoppingShotCommand::doQueueCommand(), EyeShotCommand::doQueueCommand(), FanShotCommand::doQueueCommand(), FastBlastCommand::doQueueCommand(), ScatterShot1Command::doQueueCommand(), ScatterShot2Command::doQueueCommand(), KipUpShotCommand::doQueueCommand(), SetBoostmoraleCommand::doQueueCommand(), ConfusionShotCommand::doQueueCommand(), LastDitchCommand::doQueueCommand(), SetFormupCommand::doQueueCommand(), SetRetreatCommand::doQueueCommand(), SetSteadyaimCommand::doQueueCommand(), FireAcidCone1Command::doQueueCommand(), SniperShotCommand::doQueueCommand(), SprayShotCommand::doQueueCommand(), KnockdownFireCommand::doQueueCommand(), FireAcidCone2Command::doQueueCommand(), StartleShot1Command::doQueueCommand(), StartleShot2Command::doQueueCommand(), SteadyaimCommand::doQueueCommand(), FireAcidSingle1Command::doQueueCommand(), LegShot1Command::doQueueCommand(), UnarmedLegHit1Command::doQueueCommand(), LegShot2Command::doQueueCommand(), StrafeShot1Command::doQueueCommand(), LegShot3Command::doQueueCommand(), StrafeShot2Command::doQueueCommand(), FireAcidSingle2Command::doQueueCommand(), SuppressionFire1Command::doQueueCommand(), FireLightningCone1Command::doQueueCommand(), TauntCommand::doQueueCommand(), FireLightningCone2Command::doQueueCommand(), LowBlowCommand::doQueueCommand(), UnarmedSpinAttack2Command::doQueueCommand(), FireLightningSingle1Command::doQueueCommand(), FireLightningSingle2Command::doQueueCommand(), TorsoShotCommand::doQueueCommand(), FlameCone1Command::doQueueCommand(), AimCommand::doQueueCommand(), FlameCone2Command::doQueueCommand(), UnarmedBlind1Command::doQueueCommand(), UnarmedBodyHit1Command::doQueueCommand(), UnarmedCombo1Command::doQueueCommand(), FlameSingle1Command::doQueueCommand(), UnarmedDizzy1Command::doQueueCommand(), UnarmedHit1Command::doQueueCommand(), FlameSingle2Command::doQueueCommand(), UnarmedHit3Command::doQueueCommand(), UnarmedKnockdown1Command::doQueueCommand(), UnarmedKnockdown2Command::doQueueCommand(), FlurryShot1Command::doQueueCommand(), UnarmedSpinAttack1Command::doQueueCommand(), FlurryShot2Command::doQueueCommand(), UnderHandShotCommand::doQueueCommand(), FlushingShot1Command::doQueueCommand(), VolleyFireAttackCommand::doQueueCommand(), ActionShot2Command::doQueueCommand(), FlushingShot2Command::doQueueCommand(), WarningShotCommand::doQueueCommand(), WildShot1Command::doQueueCommand(), UnarmedHit2Command::doQueueCommand(), WildShot2Command::doQueueCommand(), Melee2hLunge1Command::doQueueCommand(), CripplingShotCommand::doQueueCommand(), MindShot2Command::doQueueCommand(), MindShot1Command::doQueueCommand(), MultiTargetPistolShotCommand::doQueueCommand(), LightEngineScrambleCommand::doQueueCommand(), Melee1hBlindHit2Command::doQueueCommand(), OpenWingsCommand::doQueueCommand(), ForceWeaken2Command::doQueueCommand(), Melee1hBodyHit3Command::doQueueCommand(), AborthyperspaceCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), PilotShipCommand::doQueueCommand(), Melee1hBodyHit1Command::doQueueCommand(), PointBlankArea2Command::doQueueCommand(), ToggleDisplayingFactionRankCommand::doQueueCommand(), DestroyTargetCommand::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), DisableTargetCommand::doQueueCommand(), GmCreateClassResourceCommand::doQueueCommand(), GmCreateSpecificResourceCommand::doQueueCommand(), ChannelForceCommand::doQueueCommand(), PolearmLunge2Command::doQueueCommand(), VolleyFireCommand::doQueueCommand(), DiveShotCommand::doQueueCommand(), Ptrap1Command::doQueueCommand(), Ptrap2Command::doQueueCommand(), PumpreactorCommand::doQueueCommand(), HeadShot2Command::doQueueCommand(), DockCommand::doQueueCommand(), RequestBiographyCommand::doQueueCommand(), CheckForceStatusCommand::doQueueCommand(), RequestDraftSlotsBatchCommand::doQueueCommand(), RequestResourceWeightsBatchCommand::doQueueCommand(), RequestSpaceTrainerCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), DroidCommand::doQueueCommand(), Saber1hComboHit1Command::doQueueCommand(), CreateMissionElementCommand::doQueueCommand(), Epulse1Command::doQueueCommand(), Saber1hComboHit3Command::doQueueCommand(), Saber1hFlurryCommand::doQueueCommand(), Saber1hHeadHit1Command::doQueueCommand(), AddPowerCommand::doQueueCommand(), Epulse2Command::doQueueCommand(), ClearVeteranRewardCommand::doQueueCommand(), Epulse3Command::doQueueCommand(), HyperspaceCommand::doQueueCommand(), Saber1hHit3Command::doQueueCommand(), EscapePodCommand::doQueueCommand(), IffscrambleCommand::doQueueCommand(), CloseWingsCommand::doQueueCommand(), EshieldsCommand::doQueueCommand(), InspacereloadCommand::doQueueCommand(), InspacerepairCommand::doQueueCommand(), EthrustCommand::doQueueCommand(), InspacerrCommand::doQueueCommand(), InspectCommand::doQueueCommand(), EweaponsCommand::doQueueCommand(), InsureCommand::doQueueCommand(), SaberPolearmHit3Command::doQueueCommand(), Intimidate1Command::doQueueCommand(), Intimidate2Command::doQueueCommand(), SaberPolearmSpinAttack1Command::doQueueCommand(), ActivateQuestCommand::doQueueCommand(), InvulnerableCommand::doQueueCommand(), NewbiehelperCommand::doQueueCommand(), SaberSlash2Command::doQueueCommand(), SaberThrow1Command::doQueueCommand(), ForceThrow1Command::doQueueCommand(), SaberThrow2Command::doQueueCommand(), SaberThrow3Command::doQueueCommand(), UndockCommand::doQueueCommand(), Jstart1Command::doQueueCommand(), Jstart2Command::doQueueCommand(), KillCommand::doQueueCommand(), MindBlast2Command::doQueueCommand(), SendFormObjectDataCommand::doQueueCommand(), ServerAsteroidDataListenCommand::doQueueCommand(), ServerAsteroidDataStopListeningCommand::doQueueCommand(), Melee2hSweep2Command::doQueueCommand(), Melee2hSweep1Command::doQueueCommand(), Jstart3Command::doQueueCommand(), KillPlayerCommand::doQueueCommand(), Melee2hMindHit2Command::doQueueCommand(), LaunchCountermeasureCommand::doQueueCommand(), Melee2hLunge2Command::doQueueCommand(), BoosterOnCommand::doQueueCommand(), Melee2hHit3Command::doQueueCommand(), Melee2hHit2Command::doQueueCommand(), LaunchMissileCommand::doQueueCommand(), LeaveStationCommand::doQueueCommand(), Saber1hHeadHit2Command::doQueueCommand(), SaberPolearmLegHit3Command::doQueueCommand(), Warcry2Command::doQueueCommand(), AddAllowedPlayerCommand::doQueueCommand(), LfgCommand::doQueueCommand(), BoosterOffCommand::doQueueCommand(), Melee1hSpinAttack1Command::doQueueCommand(), LootAllCommand::doQueueCommand(), Warcry1Command::doQueueCommand(), LootCommand::doQueueCommand(), Melee1hLunge1Command::doQueueCommand(), SaberPolearmSpinAttack3Command::doQueueCommand(), MedicalForageCommand::doQueueCommand(), ToggleAwayFromKeyBoardCommand::doQueueCommand(), SaberSlash1Command::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), SaberPolearmHit2Command::doQueueCommand(), Melee1hBlindHit1Command::doQueueCommand(), SaberPolearmLegHit2Command::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), Melee2hArea1Command::doQueueCommand(), Saber1hHeadHit3Command::doQueueCommand(), SaberPolearmDervishCommand::doQueueCommand(), SaberPolearmLegHit1Command::doQueueCommand(), UnarmedLunge1Command::doQueueCommand(), SaberPolearmHit1Command::doQueueCommand(), Melee1hHit1Command::doQueueCommand(), Saber1hHit1Command::doQueueCommand(), UnarmedLunge2Command::doQueueCommand(), UnarmedStun1Command::doQueueCommand(), UnpilotShipCommand::doQueueCommand(), Saber1hHit2Command::doQueueCommand(), VrepairCommand::doQueueCommand(), ForageCommand::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), AttackCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), Melee2hHit1Command::doQueueCommand(), ForceIntimidate1Command::doQueueCommand(), VrepairotherCommand::doQueueCommand(), Bstrike1Command::doQueueCommand(), ForceIntimidate2Command::doQueueCommand(), ForceKnockdown1Command::doQueueCommand(), ForceKnockdown2Command::doQueueCommand(), ForceKnockdown3Command::doQueueCommand(), Bstrike2Command::doQueueCommand(), ForceLightningCone1Command::doQueueCommand(), ForceLightningCone2Command::doQueueCommand(), MindBlast1Command::doQueueCommand(), ForceLightningSingle1Command::doQueueCommand(), Saber1hComboHit2Command::doQueueCommand(), AnonCommand::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), Bstrike3Command::doQueueCommand(), ForceThrow2Command::doQueueCommand(), NblastCommand::doQueueCommand(), ForceWeaken1Command::doQueueCommand(), Melee1hDizzyHit1Command::doQueueCommand(), Melee1hBodyHit2Command::doQueueCommand(), PeaceCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), PolearmActionHit1Command::doQueueCommand(), PolearmActionHit2Command::doQueueCommand(), ActivateCloneCommand::doQueueCommand(), PolearmArea1Command::doQueueCommand(), PolearmHit1Command::doQueueCommand(), PolearmHit2Command::doQueueCommand(), PolearmHit3Command::doQueueCommand(), RolePlayCommand::doQueueCommand(), RequestCharacterSheetInfoCommand::doQueueCommand(), PolearmLegHit2Command::doQueueCommand(), PolearmLegHit3Command::doQueueCommand(), MeditateCommand::doQueueCommand(), PolearmSpinAttack1Command::doQueueCommand(), PolearmSpinAttack2Command::doQueueCommand(), HarvesterDeactivateCommand::doQueueCommand(), Melee1hLunge2Command::doQueueCommand(), PolearmSweep1Command::doQueueCommand(), PolearmSweep2Command::doQueueCommand(), Melee1hScatterHit1Command::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), DismountCommand::doQueueCommand(), TeleportToCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), TakeCoverCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), PolearmStun1Command::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), PolearmStun2Command::doQueueCommand(), Melee2hHeadHit3Command::doQueueCommand(), Melee1hHit3Command::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), PolearmLegHit1Command::doQueueCommand(), CloseContainerCommand::doQueueCommand(), PolearmArea2Command::doQueueCommand(), Melee1hHit2Command::doQueueCommand(), DeclareresidenceCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), ForceLightningSingle2Command::doQueueCommand(), Melee1hSpinAttack2Command::doQueueCommand(), StoplisteningCommand::doQueueCommand(), Melee2hMindHit1Command::doQueueCommand(), Melee2hSpinAttack2Command::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), Melee2hSpinAttack1Command::doQueueCommand(), FindPlayerCommand::doQueueCommand(), KneelCommand::doQueueCommand(), Melee1hScatterHit2Command::doQueueCommand(), Melee2hHeadHit2Command::doQueueCommand(), Melee1hDizzyHit2Command::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), Saber2hBodyHit1Command::doQueueCommand(), Melee2hArea3Command::doQueueCommand(), ForceChokeCommand::doQueueCommand(), SaberPolearmDervish2Command::doQueueCommand(), Saber2hHit3Command::doQueueCommand(), Saber2hBodyHit3Command::doQueueCommand(), Saber2hSweep1Command::doQueueCommand(), Saber2hBodyHit2Command::doQueueCommand(), Saber2hFrenzyCommand::doQueueCommand(), Saber2hSweep3Command::doQueueCommand(), SaberPolearmSpinAttack2Command::doQueueCommand(), Saber2hPhantomCommand::doQueueCommand(), AiIgnoreCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), Saber2hHit2Command::doQueueCommand(), Saber2hSweep2Command::doQueueCommand(), Melee2hArea2Command::doQueueCommand(), Saber2hHit1Command::doQueueCommand(), StopwatchingCommand::doQueueCommand(), Melee1hHealthHit2Command::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), Melee2hHeadHit1Command::doQueueCommand(), Saber1hFlurry2Command::doQueueCommand(), StandCommand::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), MountCommand::doQueueCommand(), WatchCommand::doQueueCommand(), Melee1hHealthHit1Command::doQueueCommand(), SetFactionCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), StopDanceCommand::doQueueCommand(), CreateVendorCommand::doQueueCommand(), RequestStatMigrationStartCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), HarvesterActivateCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), ListenCommand::doQueueCommand(), HarvesterDiscardHopperCommand::doQueueCommand(), RequestStatMigrationDataCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), GcwStatusCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), StopMusicCommand::doQueueCommand(), CreateCreatureCommand::doQueueCommand(), ServerDestroyObjectCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), FishCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), MakeLeaderCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), InviteCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), GiveItemCommand::doQueueCommand(), ScriptCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), FindCommand::doQueueCommand(), BetCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), RequestSurveyCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), ServerCommand::doQueueCommand(), RetreatCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), TipCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), and onFail().
const int server::zone::objects::creature::commands::QueueCommand::INVALIDSYNTAX = 13 static
Definition at line 116 of file QueueCommand.h.
Referenced by onFail().
const int server::zone::objects::creature::commands::QueueCommand::INVALIDTARGET = 4 static
Definition at line 107 of file QueueCommand.h.
Referenced by HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), TauntCommand::doQueueCommand(), AddPowerCommand::doQueueCommand(), Intimidate1Command::doQueueCommand(), Warcry1Command::doQueueCommand(), Intimidate2Command::doQueueCommand(), KillCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), LootCommand::doQueueCommand(), Warcry2Command::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), TeleportToCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), MountCommand::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), SetFactionCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), and onFail().
const int server::zone::objects::creature::commands::QueueCommand::INVALIDWEAPON = 5 static
Definition at line 108 of file QueueCommand.h.
Referenced by CreatureRangedAttackCommand::doQueueCommand(), WildShot2Command::doQueueCommand(), WildShot1Command::doQueueCommand(), WarningShotCommand::doQueueCommand(), UnderHandShotCommand::doQueueCommand(), ActionShot2Command::doQueueCommand(), UnarmedSpinAttack2Command::doQueueCommand(), UnarmedSpinAttack1Command::doQueueCommand(), BleedingShotCommand::doQueueCommand(), BurstShot1Command::doQueueCommand(), UnarmedLegHit1Command::doQueueCommand(), UnarmedKnockdown2Command::doQueueCommand(), UnarmedKnockdown1Command::doQueueCommand(), UnarmedHit3Command::doQueueCommand(), UnarmedHit2Command::doQueueCommand(), DisarmingShot1Command::doQueueCommand(), FlameCone2Command::doQueueCommand(), FlameSingle1Command::doQueueCommand(), UnarmedCombo2Command::doQueueCommand(), DisarmingShot2Command::doQueueCommand(), UnarmedBodyHit1Command::doQueueCommand(), FlameSingle2Command::doQueueCommand(), FlurryShot1Command::doQueueCommand(), BurstShot2Command::doQueueCommand(), SuppressionFire2Command::doQueueCommand(), FlurryShot2Command::doQueueCommand(), StrafeShot2Command::doQueueCommand(), FlushingShot1Command::doQueueCommand(), StoppingShotCommand::doQueueCommand(), StartleShot2Command::doQueueCommand(), StartleShot1Command::doQueueCommand(), DoubleTapCommand::doQueueCommand(), SniperShotCommand::doQueueCommand(), FlushingShot2Command::doQueueCommand(), FullAutoArea1Command::doQueueCommand(), ScatterShot1Command::doQueueCommand(), BodyShot1Command::doQueueCommand(), ChargeShot1Command::doQueueCommand(), EyeShotCommand::doQueueCommand(), FullAutoArea2Command::doQueueCommand(), ScatterShot2Command::doQueueCommand(), SprayShotCommand::doQueueCommand(), FullAutoSingle1Command::doQueueCommand(), Melee2hLunge1Command::doQueueCommand(), StrafeShot1Command::doQueueCommand(), FanShotCommand::doQueueCommand(), FullAutoSingle2Command::doQueueCommand(), SuppressionFire1Command::doQueueCommand(), TorsoShotCommand::doQueueCommand(), HeadShot1Command::doQueueCommand(), UnarmedBlind1Command::doQueueCommand(), UnarmedCombo1Command::doQueueCommand(), ChargeShot2Command::doQueueCommand(), FastBlastCommand::doQueueCommand(), UnarmedDizzy1Command::doQueueCommand(), UnarmedHeadHit1Command::doQueueCommand(), UnarmedHit1Command::doQueueCommand(), HeadShot3Command::doQueueCommand(), MindShot1Command::doQueueCommand(), MindShot2Command::doQueueCommand(), FireAcidCone1Command::doQueueCommand(), HealthShot1Command::doQueueCommand(), MultiTargetPistolShotCommand::doQueueCommand(), OverChargeShot1Command::doQueueCommand(), HealthShot2Command::doQueueCommand(), OverChargeShot2Command::doQueueCommand(), PanicShotCommand::doQueueCommand(), ActionShot1Command::doQueueCommand(), BodyShot2Command::doQueueCommand(), ConcealShotCommand::doQueueCommand(), FireAcidCone2Command::doQueueCommand(), KipUpShotCommand::doQueueCommand(), PistolMeleeDefense1Command::doQueueCommand(), PistolMeleeDefense2Command::doQueueCommand(), KnockdownFireCommand::doQueueCommand(), PointBlankArea1Command::doQueueCommand(), FireAcidSingle1Command::doQueueCommand(), LastDitchCommand::doQueueCommand(), PointBlankSingle1Command::doQueueCommand(), PointBlankSingle2Command::doQueueCommand(), LegShot1Command::doQueueCommand(), ConfusionShotCommand::doQueueCommand(), FireAcidSingle2Command::doQueueCommand(), LegShot2Command::doQueueCommand(), LegShot3Command::doQueueCommand(), FireLightningCone1Command::doQueueCommand(), LowBlowCommand::doQueueCommand(), AimCommand::doQueueCommand(), BodyShot3Command::doQueueCommand(), FireLightningCone2Command::doQueueCommand(), PolearmLunge1Command::doQueueCommand(), FireLightningSingle1Command::doQueueCommand(), CripplingShotCommand::doQueueCommand(), FireLightningSingle2Command::doQueueCommand(), RollShotCommand::doQueueCommand(), FlameCone1Command::doQueueCommand(), Saber1hHeadHit1Command::doQueueCommand(), Melee2hHit1Command::doQueueCommand(), UnarmedLunge1Command::doQueueCommand(), UnarmedStun1Command::doQueueCommand(), Melee1hHit1Command::doQueueCommand(), Saber1hHeadHit2Command::doQueueCommand(), Saber1hHit1Command::doQueueCommand(), UnarmedLunge2Command::doQueueCommand(), Saber1hHit3Command::doQueueCommand(), Melee1hLunge1Command::doQueueCommand(), SaberPolearmHit2Command::doQueueCommand(), Melee2hSweep1Command::doQueueCommand(), Melee2hSweep2Command::doQueueCommand(), HeadShot2Command::doQueueCommand(), Melee1hSpinAttack1Command::doQueueCommand(), Melee2hHit2Command::doQueueCommand(), Melee2hMindHit2Command::doQueueCommand(), DiveShotCommand::doQueueCommand(), SaberThrow3Command::doQueueCommand(), SaberThrow1Command::doQueueCommand(), SaberPolearmSpinAttack3Command::doQueueCommand(), SaberPolearmDervishCommand::doQueueCommand(), Melee2hArea1Command::doQueueCommand(), SaberPolearmHit3Command::doQueueCommand(), SaberPolearmLegHit1Command::doQueueCommand(), SaberPolearmLegHit2Command::doQueueCommand(), Melee2hHit3Command::doQueueCommand(), SaberPolearmSpinAttack1Command::doQueueCommand(), Melee2hLunge2Command::doQueueCommand(), SaberThrow2Command::doQueueCommand(), SaberSlash2Command::doQueueCommand(), SaberPolearmLegHit3Command::doQueueCommand(), SaberPolearmHit1Command::doQueueCommand(), Saber1hHeadHit3Command::doQueueCommand(), Saber1hFlurryCommand::doQueueCommand(), Saber1hHit2Command::doQueueCommand(), Saber1hComboHit2Command::doQueueCommand(), PointBlankArea2Command::doQueueCommand(), Melee1hBlindHit2Command::doQueueCommand(), PolearmLunge2Command::doQueueCommand(), Melee1hBlindHit1Command::doQueueCommand(), Melee1hBodyHit1Command::doQueueCommand(), Melee1hBodyHit3Command::doQueueCommand(), Saber1hComboHit1Command::doQueueCommand(), Saber1hComboHit3Command::doQueueCommand(), PolearmSpinAttack1Command::doQueueCommand(), PolearmStun2Command::doQueueCommand(), PolearmSweep1Command::doQueueCommand(), PolearmSpinAttack2Command::doQueueCommand(), Melee1hHealthHit1Command::doQueueCommand(), Melee1hHit2Command::doQueueCommand(), Saber2hBodyHit2Command::doQueueCommand(), Saber2hHit2Command::doQueueCommand(), Saber2hSweep1Command::doQueueCommand(), Melee1hScatterHit1Command::doQueueCommand(), Melee1hSpinAttack2Command::doQueueCommand(), SaberPolearmDervish2Command::doQueueCommand(), Melee2hHeadHit1Command::doQueueCommand(), Melee2hHeadHit2Command::doQueueCommand(), Melee2hHeadHit3Command::doQueueCommand(), TakeCoverCommand::doQueueCommand(), SaberPolearmSpinAttack2Command::doQueueCommand(), Saber2hSweep3Command::doQueueCommand(), Saber2hPhantomCommand::doQueueCommand(), Saber2hFrenzyCommand::doQueueCommand(), Melee1hHit3Command::doQueueCommand(), PolearmHit2Command::doQueueCommand(), PolearmActionHit2Command::doQueueCommand(), Melee1hDizzyHit1Command::doQueueCommand(), PolearmSweep2Command::doQueueCommand(), PolearmLegHit3Command::doQueueCommand(), PolearmActionHit1Command::doQueueCommand(), PolearmStun1Command::doQueueCommand(), PolearmHit3Command::doQueueCommand(), Saber2hBodyHit1Command::doQueueCommand(), Saber2hHit1Command::doQueueCommand(), Melee1hLunge2Command::doQueueCommand(), Melee2hSpinAttack2Command::doQueueCommand(), Melee2hSpinAttack1Command::doQueueCommand(), Melee2hMindHit1Command::doQueueCommand(), Melee2hArea2Command::doQueueCommand(), Melee1hScatterHit2Command::doQueueCommand(), PolearmLegHit2Command::doQueueCommand(), PolearmArea1Command::doQueueCommand(), PolearmArea2Command::doQueueCommand(), Melee1hDizzyHit2Command::doQueueCommand(), Melee1hHealthHit2Command::doQueueCommand(), Saber2hBodyHit3Command::doQueueCommand(), Saber2hSweep2Command::doQueueCommand(), Melee2hArea3Command::doQueueCommand(), PolearmHit1Command::doQueueCommand(), Melee1hBodyHit2Command::doQueueCommand(), Saber1hFlurry2Command::doQueueCommand(), Saber2hHit3Command::doQueueCommand(), PolearmLegHit1Command::doQueueCommand(), and onFail().
int server::zone::objects::creature::commands::QueueCommand::maxRangeToTarget protected
Definition at line 78 of file QueueCommand.h.
Referenced by getMaxRange(), QueueCommand(), and setMaxRange().
String server::zone::objects::creature::commands::QueueCommand::name protected
Definition at line 71 of file QueueCommand.h.
Referenced by NameStructureCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), getQueueCommandName(), and QueueCommand().
uint32 server::zone::objects::creature::commands::QueueCommand::nameCRC protected
Definition at line 72 of file QueueCommand.h.
Referenced by getNameCRC(), and QueueCommand().
const int server::zone::objects::creature::commands::QueueCommand::NOJEDIARMOR = 12 static
Definition at line 115 of file QueueCommand.h.
Referenced by ChannelForceCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), ForceKnockdown1Command::doQueueCommand(), ForceThrow1Command::doQueueCommand(), SaberThrow3Command::doQueueCommand(), SaberThrow2Command::doQueueCommand(), Saber1hComboHit1Command::doQueueCommand(), SaberPolearmSpinAttack3Command::doQueueCommand(), SaberSlash2Command::doQueueCommand(), SaberThrow1Command::doQueueCommand(), SaberPolearmSpinAttack1Command::doQueueCommand(), ForceThrow2Command::doQueueCommand(), SaberPolearmLegHit2Command::doQueueCommand(), SaberPolearmLegHit1Command::doQueueCommand(), SaberPolearmHit3Command::doQueueCommand(), Saber1hComboHit2Command::doQueueCommand(), SaberPolearmHit1Command::doQueueCommand(), Saber1hComboHit3Command::doQueueCommand(), ForceKnockdown2Command::doQueueCommand(), ForceWeaken1Command::doQueueCommand(), Saber1hFlurryCommand::doQueueCommand(), ForceWeaken2Command::doQueueCommand(), Saber1hHeadHit1Command::doQueueCommand(), Saber1hHeadHit2Command::doQueueCommand(), ForceKnockdown3Command::doQueueCommand(), Saber1hHeadHit3Command::doQueueCommand(), Saber1hHit1Command::doQueueCommand(), Saber1hHit2Command::doQueueCommand(), Saber1hHit3Command::doQueueCommand(), ForceLightningCone1Command::doQueueCommand(), ForceIntimidate1Command::doQueueCommand(), ForceLightningCone2Command::doQueueCommand(), ForceLightningSingle1Command::doQueueCommand(), ForceIntimidate2Command::doQueueCommand(), MindBlast1Command::doQueueCommand(), SaberPolearmDervishCommand::doQueueCommand(), SaberPolearmHit2Command::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), MindBlast2Command::doQueueCommand(), SaberPolearmLegHit3Command::doQueueCommand(), Saber2hPhantomCommand::doQueueCommand(), SaberPolearmSpinAttack2Command::doQueueCommand(), Saber1hFlurry2Command::doQueueCommand(), ForceLightningSingle2Command::doQueueCommand(), Saber2hSweep2Command::doQueueCommand(), Saber2hFrenzyCommand::doQueueCommand(), Saber2hSweep3Command::doQueueCommand(), Saber2hHit2Command::doQueueCommand(), Saber2hBodyHit1Command::doQueueCommand(), Saber2hBodyHit2Command::doQueueCommand(), Saber2hBodyHit3Command::doQueueCommand(), ForceChokeCommand::doQueueCommand(), Saber2hHit1Command::doQueueCommand(), Saber2hHit3Command::doQueueCommand(), Saber2hSweep1Command::doQueueCommand(), SaberPolearmDervish2Command::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), and onFail().
const int server::zone::objects::creature::commands::QueueCommand::NOKNEELING = 10 static
Definition at line 113 of file QueueCommand.h.
Referenced by CombatQueueCommand::doCombatAction(), and onFail().
const int server::zone::objects::creature::commands::QueueCommand::NOPRONE = 9 static
Definition at line 112 of file QueueCommand.h.
Referenced by HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), and onFail().
const int server::zone::objects::creature::commands::QueueCommand::NORMAL = 2 static
Definition at line 101 of file QueueCommand.h.
Referenced by QueueCommand(), and setDefaultPriority().
ZoneProcessServer* server::zone::objects::creature::commands::QueueCommand::server protected
Definition at line 69 of file QueueCommand.h.
Referenced by DotPackCommand::awardXp(), HealStateCommand::awardXp(), HealWoundCommand::awardXp(), TendCommand::awardXp(), CurePackCommand::awardXp(), RevivePlayerCommand::awardXp(), HealEnhanceCommand::awardXp(), HealDamageCommand::awardXp(), StopBleedingCommand::canPerformSkill(), ForceCureDiseaseCommand::canPerformSkill(), ForceCurePoisonCommand::canPerformSkill(), HealStatesOtherCommand::canPerformSkill(), HealAllOther2Command::canPerformSkill(), HealAllOther1Command::canPerformSkill(), HealActionWoundOther2Command::canPerformSkill(), HealHealthWoundOther1Command::canPerformSkill(), HealHealthWoundOther2Command::canPerformSkill(), HealMindWoundOther1Command::canPerformSkill(), HealMindWoundOther2Command::canPerformSkill(), HealActionWoundOther1Command::canPerformSkill(), CurePackCommand::canPerformSkill(), TotalHealOtherCommand::canPerformSkill(), DotPackCommand::checkTarget(), StopBleedingCommand::checkTarget(), ForceCureDiseaseCommand::checkTarget(), ForceCurePoisonCommand::checkTarget(), HealStatesOtherCommand::checkTarget(), HealAllOther1Command::checkTarget(), HealAllOther2Command::checkTarget(), HealActionWoundOther2Command::checkTarget(), HealHealthWoundOther1Command::checkTarget(), HealHealthWoundOther2Command::checkTarget(), HealMindWoundOther1Command::checkTarget(), HealMindWoundOther2Command::checkTarget(), HealActionWoundOther1Command::checkTarget(), TotalHealOtherCommand::checkTarget(), CurePackCommand::checkTarget(), HealDamageCommand::checkTarget(), HealDamageCommand::doAreaMedicActionTarget(), HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), FireHeavyWeaponCommand::doQueueCommand(), SniperShotCommand::doQueueCommand(), ThrowGrenadeCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), ForageCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), Warcry1Command::doQueueCommand(), Warcry2Command::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), ForceWeaken2Command::doQueueCommand(), ForceWeaken1Command::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), Intimidate1Command::doQueueCommand(), Intimidate2Command::doQueueCommand(), KillCommand::doQueueCommand(), GmCreateClassResourceCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), LootCommand::doQueueCommand(), GmCreateSpecificResourceCommand::doQueueCommand(), MedicalForageCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), AddPowerCommand::doQueueCommand(), RequestBiographyCommand::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), ActivateCloneCommand::doQueueCommand(), StoplisteningCommand::doQueueCommand(), StopwatchingCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), ForceChokeCommand::doQueueCommand(), TeleportToCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), WatchCommand::doQueueCommand(), MeditateCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), MountCommand::doQueueCommand(), HarvesterDeactivateCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), DismountCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), CloseContainerCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), ServerDestroyObjectCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), HarvesterActivateCommand::doQueueCommand(), FishCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), HarvesterDiscardHopperCommand::doQueueCommand(), SetFactionCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), ListenCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), MakeLeaderCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), InviteCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), GiveItemCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), BetCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), TipCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), FireHeavyWeaponCommand::getCommandDuration(), ThrowGrenadeCommand::getCommandDuration(), TipCommand::performBankTip(), QueueCommand(), BoardShuttleCommand::sendTicketSelectionBoxTo(), and SquadLeaderCommand::shoutCommand().
VectorMap<String, int> server::zone::objects::creature::commands::QueueCommand::skillMods protected
Definition at line 92 of file QueueCommand.h.
Referenced by addSkillMod(), ThrowTrapCommand::doQueueCommand(), getSkillMod(), and getSkillModSize().
uint64 server::zone::objects::creature::commands::QueueCommand::stateMask protected
Definition at line 74 of file QueueCommand.h.
Referenced by checkStateMask(), getStateMask(), onStateFail(), QueueCommand(), and setStateMask().
const int server::zone::objects::creature::commands::QueueCommand::SUCCESS = 0 static
Definition at line 103 of file QueueCommand.h.
Referenced by VolleyFireCommand::attemptVolleyFire(), HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), DelegateFactionPointsCommand::doDelegate(), SquadLeaderCommand::doQueueCommand(), SurpriseShotCommand::doQueueCommand(), FireHeavyWeaponCommand::doQueueCommand(), MultiTargetShotCommand::doQueueCommand(), SetBoostmoraleCommand::doQueueCommand(), SetFormupCommand::doQueueCommand(), SetRetreatCommand::doQueueCommand(), SetSteadyaimCommand::doQueueCommand(), SteadyaimCommand::doQueueCommand(), RollShotCommand::doQueueCommand(), TauntCommand::doQueueCommand(), ThreatenShotCommand::doQueueCommand(), ThrowGrenadeCommand::doQueueCommand(), KipUpShotCommand::doQueueCommand(), AimCommand::doQueueCommand(), FormupCommand::doQueueCommand(), RallyCommand::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), SaberSlash1Command::doQueueCommand(), ActivateQuestCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), ChannelForceCommand::doQueueCommand(), CheckForceStatusCommand::doQueueCommand(), ToggleAwayFromKeyBoardCommand::doQueueCommand(), DiveShotCommand::doQueueCommand(), ToggleDisplayingFactionRankCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), InsureCommand::doQueueCommand(), InvulnerableCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), KillCommand::doQueueCommand(), AnonCommand::doQueueCommand(), ClearVeteranRewardCommand::doQueueCommand(), VolleyFireCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), LfgCommand::doQueueCommand(), ForageCommand::doQueueCommand(), LootAllCommand::doQueueCommand(), LootCommand::doQueueCommand(), MedicalForageCommand::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), NewbiehelperCommand::doQueueCommand(), ForceWeaken1Command::doQueueCommand(), AddAllowedPlayerCommand::doQueueCommand(), ForceWeaken2Command::doQueueCommand(), AddPowerCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), CreateMissionElementCommand::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), RequestBiographyCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), GmCreateClassResourceCommand::doQueueCommand(), RequestDraftSlotsBatchCommand::doQueueCommand(), RequestResourceWeightsBatchCommand::doQueueCommand(), GmCreateSpecificResourceCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), ActivateCloneCommand::doQueueCommand(), RolePlayCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), HarvesterDeactivateCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), AiIgnoreCommand::doQueueCommand(), DeclareresidenceCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), StandCommand::doQueueCommand(), StoplisteningCommand::doQueueCommand(), StopwatchingCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), TakeCoverCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), TeleportToCommand::doQueueCommand(), DismountCommand::doQueueCommand(), WatchCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), KneelCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), CloseContainerCommand::doQueueCommand(), ForceChokeCommand::doQueueCommand(), MeditateCommand::doQueueCommand(), MountCommand::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), PeaceCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), RequestCharacterSheetInfoCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), HarvesterDiscardHopperCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), ServerDestroyObjectCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), StopDanceCommand::doQueueCommand(), StopMusicCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), CreateCreatureCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), SetFactionCommand::doQueueCommand(), ListenCommand::doQueueCommand(), FishCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), CreateVendorCommand::doQueueCommand(), GcwStatusCommand::doQueueCommand(), HarvesterActivateCommand::doQueueCommand(), RequestStatMigrationStartCommand::doQueueCommand(), RequestStatMigrationDataCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), MakeLeaderCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), InviteCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), ScriptCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), GiveItemCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), BetCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), FindCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), RequestSurveyCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), ServerCommand::doQueueCommand(), RetreatCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), TransferstructureCommand::doTransferStructure(), TipCommand::performBankTip(), and TipCommand::performTip().
int server::zone::objects::creature::commands::QueueCommand::targetType protected
Definition at line 77 of file QueueCommand.h.
Referenced by getTargetType(), QueueCommand(), and setTargetType().
const int server::zone::objects::creature::commands::QueueCommand::TOOFAR = 6 static
Definition at line 109 of file QueueCommand.h.
Referenced by HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), SniperShotCommand::doQueueCommand(), Warcry1Command::doQueueCommand(), Warcry2Command::doQueueCommand(), Intimidate1Command::doQueueCommand(), Intimidate2Command::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), TransferstructureCommand::doTransferStructure(), and onFail().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/QueueCommand.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/QueueCommand.cpp