Core3: NewbieTutorialResponseCallback Class Reference
NewbieTutorialResponseCallback Class Reference
#include <NewbieTutorialRequest.h>
Public Member Functions
NewbieTutorialResponseCallback (ZoneClientSession *client, ZoneProcessServer *server)
void parse (Message *message)
void run ()
Public Member Functions inherited from server::zone::packets::MessageCallback
MessageCallback (ZoneClientSession *client, ZoneProcessServer *server)
virtual ~MessageCallback ()
int getTaskQueue ()
bool parseMessage (Message *packet)
ZoneClientSession * getClient ()
ZoneProcessServer * getServer ()
Private Attributes
String response
Additional Inherited Members
Protected Attributes inherited from server::zone::packets::MessageCallback
Reference< ZoneClientSession * > client
ManagedReference
< ZoneProcessServer * > server
int taskqueue
Detailed Description
Sends clientReady on zone. Echos string sent by NewbieTutorialRequest, when action is triggered.
Definition at line 60 of file NewbieTutorialRequest.h.
Constructor & Destructor Documentation
NewbieTutorialResponseCallback::NewbieTutorialResponseCallback (ZoneClientSession * client, ZoneProcessServer * server) inline
Definition at line 63 of file NewbieTutorialRequest.h.
Member Function Documentation
void NewbieTutorialResponseCallback::parse (Message * message) inline virtual
Implements server::zone::packets::MessageCallback.
Definition at line 68 of file NewbieTutorialRequest.h.
References response.
void NewbieTutorialResponseCallback::run () inline
Definition at line 72 of file NewbieTutorialRequest.h.
References ObserverEventType::CHAT, server::zone::packets::MessageCallback::client, server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), ObserverEventType::NEWBIECLOSEINVENTORY, ObserverEventType::NEWBIEOPENINVENTORY, ObserverEventType::NEWBIETUTORIALHOLOCRON, ObserverEventType::NEWBIETUTORIALZOOMCAMERA, and response.
Member Data Documentation
String NewbieTutorialResponseCallback::response private
Definition at line 61 of file NewbieTutorialRequest.h.
Referenced by parse(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/player/NewbieTutorialRequest.h