Core3: CampTerminalMenuComponent Class Reference
CampTerminalMenuComponent Class Reference
#include <CampTerminalMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
void disbandCamp (SceneObject *sceneObject, CreatureObject *player)
void assumeCampOwnership (SceneObject *sceneObject, CreatureObject *player)
void showCampStatus (SceneObject *sceneObject, CreatureObject *player)
void awardCampExperience (PlayerObject *ghost, CampSiteActiveArea *campArea)
Detailed Description
Definition at line 14 of file CampTerminalMenuComponent.h.
Member Function Documentation
void CampTerminalMenuComponent::assumeCampOwnership (SceneObject * sceneObject, CreatureObject * player)
Definition at line 151 of file CampTerminalMenuComponent.cpp.
References server::zone::objects::area::CampSiteActiveArea::assumeOwnership(), server::zone::objects::scene::SceneObject::getActiveAreas(), server::zone::objects::tangible::terminal::Terminal::getControlledObject(), and server::zone::objects::area::CampSiteActiveArea::isAbandoned().
Referenced by handleObjectMenuSelect().
void CampTerminalMenuComponent::awardCampExperience (PlayerObject * ghost, CampSiteActiveArea * campArea)
Definition at line 262 of file CampTerminalMenuComponent.cpp.
void CampTerminalMenuComponent::disbandCamp (SceneObject * sceneObject, CreatureObject * player)
Definition at line 106 of file CampTerminalMenuComponent.cpp.
References server::zone::objects::area::CampSiteActiveArea::despawnCamp(), server::zone::objects::scene::SceneObject::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::getActiveAreas(), server::zone::objects::tangible::terminal::Terminal::getControlledObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isSitting(), server::zone::objects::creature::CreatureObject::setPosture(), and CreaturePosture::UPRIGHT.
Referenced by handleObjectMenuSelect().
void CampTerminalMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Get Ghost
Make sure player doesn't already have a camp setup somewhere else
Reimplemented from TangibleObjectMenuComponent.
Definition at line 21 of file CampTerminalMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), TangibleObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::scene::SceneObject::getActiveAreas(), server::zone::objects::tangible::terminal::Terminal::getControlledObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::scene::SceneObject::isTerminal().
int CampTerminalMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Disband
Reimplemented from TangibleObjectMenuComponent.
Definition at line 78 of file CampTerminalMenuComponent.cpp.
References assumeCampOwnership(), disbandCamp(), TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::isTangibleObject(), and showCampStatus().
void CampTerminalMenuComponent::showCampStatus (SceneObject * sceneObject, CreatureObject * player)
Get Ghost
Definition at line 189 of file CampTerminalMenuComponent.cpp.
References SuiWindowType::CAMP_STATUS, server::zone::objects::scene::SceneObject::getActiveAreas(), server::zone::objects::tangible::terminal::Terminal::getControlledObject(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getLastName(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::area::CampSiteActiveArea::getOwner(), server::zone::objects::structure::StructureObject::getOwnerCreatureObject(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::area::CampSiteActiveArea::getUptime(), server::zone::objects::area::CampSiteActiveArea::getVisitorCount(), server::zone::objects::creature::CreatureObject::sendMessage(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by handleObjectMenuSelect().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/CampTerminalMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/CampTerminalMenuComponent.cpp