Core3: server::zone::objects::player::sessions::PlaceStructureSessionAdapter Class Reference
server::zone::objects::player::sessions::PlaceStructureSessionAdapter Class Reference
#include <PlaceStructureSession.h>
Public Member Functions
PlaceStructureSessionAdapter (PlaceStructureSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int initializeSession ()
void removeTemporaryNoBuildZone ()
int constructStructure (float x, float y, int angle)
int completeSession ()
int cancelSession ()
int clearSession ()
Detailed Description
Definition at line 229 of file PlaceStructureSession.h.
Constructor & Destructor Documentation
PlaceStructureSessionAdapter::PlaceStructureSessionAdapter (PlaceStructureSession * impl)
Definition at line 408 of file PlaceStructureSession.cpp.
Member Function Documentation
int PlaceStructureSessionAdapter::cancelSession ()
Definition at line 466 of file PlaceStructureSession.cpp.
Referenced by invokeMethod().
int PlaceStructureSessionAdapter::clearSession ()
Definition at line 470 of file PlaceStructureSession.cpp.
Referenced by invokeMethod().
int PlaceStructureSessionAdapter::completeSession ()
Definition at line 462 of file PlaceStructureSession.cpp.
Referenced by invokeMethod().
int PlaceStructureSessionAdapter::constructStructure (float x, float y, int angle)
Definition at line 458 of file PlaceStructureSession.cpp.
Referenced by invokeMethod().
int PlaceStructureSessionAdapter::initializeSession ()
Definition at line 450 of file PlaceStructureSession.cpp.
Referenced by invokeMethod().
void PlaceStructureSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 411 of file PlaceStructureSession.cpp.
References cancelSession(), clearSession(), completeSession(), constructStructure(), initializeSession(), removeTemporaryNoBuildZone(), RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_COMPLETESESSION__, RPC_CONSTRUCTSTRUCTURE__FLOAT_FLOAT_INT_, RPC_INITIALIZESESSION__, and RPC_REMOVETEMPORARYNOBUILDZONE__.
void PlaceStructureSessionAdapter::removeTemporaryNoBuildZone ()
Definition at line 454 of file PlaceStructureSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/PlaceStructureSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/PlaceStructureSession.cpp