Core3: BaseLineMessage Class Reference
BaseLineMessage Class Reference
#include <BaseLineMessage.h>
Public Member Functions
BaseLineMessage (uint64 oid, uint32 name, uint8 type, uint16 opcnt)
uint32 generateRandomObjectCRC ()
void setSize ()
void insertStringId (StringId *id)
void insertCustomName (const UnicodeString &name)
Detailed Description
Definition at line 53 of file BaseLineMessage.h.
Constructor & Destructor Documentation
BaseLineMessage::BaseLineMessage (uint64 oid, uint32 name, uint8 type, uint16 opcnt) inline
Definition at line 55 of file BaseLineMessage.h.
Member Function Documentation
uint32 BaseLineMessage::generateRandomObjectCRC () inline
Definition at line 69 of file BaseLineMessage.h.
void BaseLineMessage::insertCustomName (const UnicodeString & name) inline
Definition at line 94 of file BaseLineMessage.h.
Referenced by FactoryCrateObjectMessage3::FactoryCrateObjectMessage3(), IntangibleObjectMessage3::IntangibleObjectMessage3(), IntangibleObjectMessage6::IntangibleObjectMessage6(), MissionObjectMessage3::MissionObjectMessage3(), and StaticObjectMessage3::StaticObjectMessage3().
void BaseLineMessage::insertStringId (StringId * id) inline
Definition at line 88 of file BaseLineMessage.h.
References server::zone::objects::scene::variables::StringId::getFile(), and server::zone::objects::scene::variables::StringId::getStringID().
Referenced by FactoryCrateObjectMessage3::FactoryCrateObjectMessage3(), IntangibleObjectMessage3::IntangibleObjectMessage3(), IntangibleObjectMessage6::IntangibleObjectMessage6(), MissionObjectMessage3::MissionObjectMessage3(), StaticObjectMessage3::StaticObjectMessage3(), and TangibleObjectMessage3::TangibleObjectMessage3().
void BaseLineMessage::setSize () inline
Definition at line 84 of file BaseLineMessage.h.
Referenced by BuildingObjectMessage3::BuildingObjectMessage3(), BuildingObjectMessage6::BuildingObjectMessage6(), CellObjectMessage3::CellObjectMessage3(), CellObjectMessage6::CellObjectMessage6(), CreatureObjectMessage1::CreatureObjectMessage1(), CreatureObjectMessage3::CreatureObjectMessage3(), CreatureObjectMessage4::CreatureObjectMessage4(), CreatureObjectMessage6::CreatureObjectMessage6(), FactoryCrateObjectMessage3::FactoryCrateObjectMessage3(), FactoryCrateObjectMessage6::FactoryCrateObjectMessage6(), GroupObjectMessage3::GroupObjectMessage3(), GroupObjectMessage6::GroupObjectMessage6(), GuildObjectMessage3::GuildObjectMessage3(), GuildObjectMessage6::GuildObjectMessage6(), HarvesterObjectMessage3::HarvesterObjectMessage3(), HarvesterObjectMessage6::HarvesterObjectMessage6(), HarvesterObjectMessage7::HarvesterObjectMessage7(), InstallationObjectMessage3::InstallationObjectMessage3(), InstallationObjectMessage6::InstallationObjectMessage6(), InstallationObjectMessage7::InstallationObjectMessage7(), IntangibleObjectMessage3::IntangibleObjectMessage3(), IntangibleObjectMessage6::IntangibleObjectMessage6(), LairObjectMessage3::LairObjectMessage3(), LairObjectMessage6::LairObjectMessage6(), ManufactureSchematicObjectMessage3::ManufactureSchematicObjectMessage3(), ManufactureSchematicObjectMessage6::ManufactureSchematicObjectMessage6(), ManufactureSchematicObjectMessage8::ManufactureSchematicObjectMessage8(), ManufactureSchematicObjectMessage9::ManufactureSchematicObjectMessage9(), MissionObjectMessage3::MissionObjectMessage3(), MissionObjectMessage6::MissionObjectMessage6(), PlayerObjectMessage3::PlayerObjectMessage3(), PlayerObjectMessage6::PlayerObjectMessage6(), PlayerObjectMessage8::PlayerObjectMessage8(), PlayerObjectMessage9::PlayerObjectMessage9(), ResourceContainerObjectMessage3::ResourceContainerObjectMessage3(), ResourceContainerObjectMessage6::ResourceContainerObjectMessage6(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendMsco7(), ShipObjectMessage1::ShipObjectMessage1(), ShipObjectMessage3::ShipObjectMessage3(), ShipObjectMessage4::ShipObjectMessage4(), ShipObjectMessage6::ShipObjectMessage6(), StaticObjectMessage3::StaticObjectMessage3(), StaticObjectMessage6::StaticObjectMessage6(), TangibleObjectMessage3::TangibleObjectMessage3(), TangibleObjectMessage6::TangibleObjectMessage6(), TangibleObjectMessage7::TangibleObjectMessage7(), TangibleObjectMessage8::TangibleObjectMessage8(), TangibleObjectMessage9::TangibleObjectMessage9(), WeaponObjectMessage3::WeaponObjectMessage3(), and WeaponObjectMessage6::WeaponObjectMessage6().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/BaseLineMessage.h