Core3: server::zone::objects::creature::CreatureObject Class Reference
server::zone::objects::creature::CreatureObject Class Reference
#include <CreatureObject.h>
Public Member Functions
CreatureObject ()
void initializeMembers ()
void createChildObjects ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void clearQueueAction (unsigned int actioncntr, float timer=0, unsigned int tab1=0, unsigned int tab2=0)
void sendBaselinesTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendTo (SceneObject *player, bool doClose)
void sendSystemMessage (const String &message)
void playMusicMessage (const String &file)
void sendNewbieTutorialRequest (const String &request)
void sendNewbieTutorialEnableHudElement (const String &ui, bool enable=true)
void sendOpenHolocronToPageMessage ()
void sendSystemMessage (UnicodeString &message)
void sendSystemMessage (StringIdChatParameter &stringid)
void sendSlottedObjectsTo (SceneObject *player)
void setCombatState ()
void clearCombatState (bool clearDefenders=true)
void setPosture (int newPosture, bool notifyClient=true)
float calculateSpeed ()
void updateLocomotion ()
void setHeight (float heigh, bool notifyClient=true)
void setAccelerationMultiplierBase (float newMultiplierBase, bool notifyClient=true)
void setAccelerationMultiplierMod (float newMultiplierMod, bool notifyClient=true)
void setSpeedMultiplierBase (float newMultiplierBase, bool notifyClient=true)
void setSpeedMultiplierMod (float newMultiplierMod, bool notifyClient=true)
void setTurnScale (float newMultiplierMod, bool notifyClient=true)
void setRunSpeed (float newSpeed, bool notifyClient=true)
void setCurrentSpeed (float newSpeed)
void setHAM (int type, int value, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
bool hasDamage (int attribute)
int healDamage (TangibleObject *healer, int damageType, int damage, bool notifyClient=true, bool notifyObservers=true)
int healWound (TangibleObject *healer, int damageType, int damage, bool notifyClient=true, bool notifyObservers=true)
void setBaseHAM (int type, int value, bool notifyClient=true)
void setWounds (int type, int value, bool notifyClient=true)
int addWounds (int type, int value, bool notifyClient=true)
void setMaxHAM (int type, int value, bool notifyClient=true)
void addMaxHAM (int type, int value, bool notifyClient=true)
void setEncumbrance (int type, int value, bool notifyClient=true)
void addEncumbrance (int type, int value, bool notifyClient=true)
void setWeapon (WeaponObject *weao, bool notifyClient=false)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void setInstrumentID (int instrumentid, bool notifyClient=true)
void setListenToID (unsigned long long id, bool notifyClient=true)
void setPerformanceCounter (int counter, bool notifyClient=true)
void setPerformanceAnimation (const String &animation, bool notifyClient=true)
void setShockWounds (int newShock, bool notifyClient=true)
void addShockWounds (int shockToAdd, bool notiyClient=true)
void setTargetID (unsigned long long targetID, bool notifyClient=true)
void setBankCredits (int credits, bool notifyClient=true)
void addBuff (Buff *buff)
bool removeBuff (unsigned int buffcrc)
void removeBuff (Buff *buff)
bool removeStateBuff (unsigned long long state)
void clearBuffs (bool updateclient)
void addWearableObject (TangibleObject *object, bool notifyClient=true)
void removeWearableObject (TangibleObject *object, bool notifyClient=true)
WearablesDeltaVector * getWearablesDeltaVector ()
void sendBuffsTo (CreatureObject *creature)
BuffList * getBuffList ()
Buff * getBuff (unsigned int buffcrc)
long long getSkillModFromBuffs (const String &skillMod)
int addDotState (unsigned long long dotType, unsigned long long objectID, unsigned int strength, byte type, unsigned int duration, float potency, unsigned int defense, int secondaryStrength=0)
bool healDot (unsigned long long dotType, int reduction)
void clearDots ()
DamageOverTimeList * getDamageOverTimeList ()
bool hasBuff (unsigned int buffcrc)
void notifySelfPositionUpdate ()
void notifyPostureChange (int newPosture)
void setLevel (int level)
void updateToDatabaseAllObjects (bool startTask)
bool isResuscitable ()
void addBankCredits (int credits, bool notifyClient=true)
void addCashCredits (int credits, bool notifyClient=true)
void subtractBankCredits (int credits)
void subtractCashCredits (int credits)
bool verifyCashCredits (int credits)
bool verifyBankCredits (int credits)
bool isDancing ()
bool isPlayingMusic ()
void stopEntertaining ()
bool isEntertaining ()
void setCashCredits (int credits, bool notifyClient=true)
void setTerrainNegotiation (float value, bool notifyClient=true)
void addSkill (Skill *skill, bool notifyClient=true)
void addSkill (const String &skill, bool notifyClient=true)
void removeSkill (Skill *skill, bool notifyClient=true)
void removeSkill (const String &skill, bool notifyClient=true)
void addSkillMod (const int modType, const String &skillMod, int value, bool notifyClient=true)
void removeSkillMod (const int modType, const String &skillMod, int value, bool notifyClient=true)
void removeAllSkillModsOfType (const int modType, bool notifyClient=true)
void updateGroupInviterID (unsigned long long id, bool notifyClient=true)
void updateGroup (GroupObject *group, bool notifyClient=true)
void enqueueCommand (unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString &arguments, int priority=-1)
void setMood (byte moodID, bool notifyClient=true)
void setMoodString (const String &animation, bool notifyClient=true)
void deleteQueueAction (unsigned int actionCount)
bool setState (unsigned long long state, bool notifyClient=true)
bool clearState (unsigned long long state, bool notifyClient=true)
void setControlDevice (ControlDevice *device)
void setCreatureLink (CreatureObject *object, bool notifyClient=true)
void executeObjectControllerAction (unsigned int actionCRC)
void executeObjectControllerAction (unsigned int actionCRC, unsigned long long targetID, const UnicodeString &args)
bool isAttackableBy (CreatureObject *object)
bool isAttackableBy (TangibleObject *attacker)
bool isHealableBy (CreatureObject *object)
bool isInBountyMission (CreatureObject *bountyHunter, CreatureObject *target)
void sendConversationStartTo (SceneObject *player)
void selectConversationOption (int option, SceneObject *obj)
void sendMessage (BasePacket *msg)
void sendExecuteConsoleCommand (const String &command)
bool isAggressiveTo (CreatureObject *object)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
int notifyObjectKillObservers (TangibleObject *killer)
void notifyLoadFromDatabase ()
void setFactionRank (int rank, bool notifyClient=true)
String getFirstName ()
String getLastName ()
bool isOnline ()
bool canTreatInjuries ()
bool canTreatStates ()
bool canTreatWounds ()
bool canTreatConditions ()
Reference< PlayerObject * > getPlayerObject ()
AiActor * getActorObject ()
bool isListening ()
bool isWatching ()
void setClient (ZoneClientSession *cli)
void dismount ()
float calculateBFRatio ()
void setDizziedState (int durationSeconds=5)
void setRalliedState (int durationSeconds=5)
void setAimingState (int durationSeconds=5)
void setCoverState (int durationSeconds=40)
void setBerserkedState (unsigned int duration)
void setStunnedState (int durationSeconds=5)
void setBlindedState (int durationSeconds=5)
void setIntimidatedState (unsigned int mod, int durationSeconds=15)
void setSnaredState (int durationSeconds=20)
void setRootedState (int durationSeconds=20)
bool setNextAttackDelay (unsigned int mod, int del)
void setMeditateState ()
void activateHAMRegeneration ()
void activatePassiveWoundRegeneration ()
void activateStateRecovery ()
void updateTimeOfDeath ()
bool hasAttackDelay ()
void removeAttackDelay ()
CooldownTimerMap * getCooldownTimerMap ()
bool hasSpice ()
void updateLastSuccessfulCombatAction ()
void updateKnockdownRecovery ()
void queueDizzyFallEvent ()
void updateLastKnockdown ()
bool checkKnockdownRecovery ()
bool checkLastKnockdown ()
void updatePostureDownRecovery ()
void updatePostureUpRecovery ()
bool checkPostureDownRecovery ()
unsigned long long getScreenPlayState (const String &screenPlay)
void setScreenPlayState (const String &screenPlay, unsigned long long state)
bool checkPostureUpRecovery ()
void updateCooldownTimer (const String &coooldownTimer, unsigned int miliSecondsToAdd=0)
bool checkCooldownRecovery (const String &cooldown)
Time * getCooldownTime (const String &cooldown)
void addCooldown (const String &name, unsigned int miliseconds)
void doAnimation (const String &animation)
void doCombatAnimation (CreatureObject *defender, unsigned int animationCRC, byte hit, byte trails)
void playEffect (const String &file, const String &aux)
void playEffect (const String &file)
void activateQueueAction ()
void activateImmediateAction ()
UnicodeString getCreatureName ()
bool isGrouped ()
int getBankCredits ()
int getCashCredits ()
int getBaseHAM (int idx)
int getWounds (int idx)
DeltaVector< int > * getWounds ()
int getHAM (int idx)
DeltaVector< int > * getHAM ()
int getMaxHAM (int idx)
DeltaVector< int > * getMaxHAM ()
int getEncumbrance (int idx)
DeltaVector< int > * getEncumbrances ()
byte getPosture ()
byte getLocomotion ()
byte getFactionRank ()
ManagedWeakReference
< CreatureObject * > getLinkedCreature ()
unsigned long long getCreatureLinkID ()
float getShockWounds ()
unsigned long long getWatchToID ()
unsigned long long getStateBitmask ()
bool hasState (unsigned long long state)
bool hasStates ()
unsigned long long getListenID ()
float getAccelerationMultiplierBase ()
float getAccelerationMultiplierMod ()
float getSpeedMultiplierBase ()
float getSpeedMultiplierMod ()
float getCurrentSpeed ()
SpeedMultiplierModChanges * getSpeedMultiplierModChanges ()
CommandQueueActionVector * getCommandQueue ()
float getRunSpeed ()
float getWalkSpeed ()
float getTurnScale ()
float getTerrainNegotiation ()
float getRunAcceleration ()
float getWalkAcceleration ()
String getPerformanceAnimation ()
String getMoodString ()
unsigned long long getWeaponID ()
Reference< WeaponObject * > getWeapon ()
Reference< GuildObject * > getGuildObject ()
int getGuildID ()
bool isInGuild ()
void setGuildObject (GuildObject *guildobj)
unsigned long long getGroupID ()
unsigned long long getGroupInviterID ()
GroupObject * getGroup ()
unsigned long long getGroupInviteCounter ()
unsigned long long getTargetID ()
byte getMoodID ()
float getSlopeModPercent ()
int getPerformanceCounter ()
int getInstrumentID ()
byte getFrozen ()
float getHeight ()
int getSpecies ()
String getSpeciesName ()
int getGender ()
DeltaVector< int > * getBaseHAM ()
SkillList * getSkillList ()
int getSkillMod (const String &skillmod)
bool hasSkill (const String &skill)
SkillModList * getSkillModList ()
void setWatchToID (unsigned long long id)
bool isCreatureObject ()
bool isNextActionPast ()
bool isTrainerCreature ()
bool isSwimming ()
ZoneClientSession * getClient ()
bool isRidingMount ()
ManagedWeakReference
< ControlDevice * > getControlDevice ()
float getSwimHeight ()
bool isIncapacitated ()
bool isDead ()
bool isKnockedDown ()
bool isKneeling ()
bool isProne ()
bool isStanding ()
bool isSitting ()
bool isSkillAnimating ()
bool isRallied ()
bool isInCombat ()
bool isDizzied ()
bool isBerserked ()
bool isStunned ()
bool isBlinded ()
bool isIntimidated ()
bool isSnared ()
bool isImmobilized ()
bool isRooted ()
bool isFrozen ()
bool isDiseased ()
bool isPoisoned ()
bool isBleeding ()
bool isOnFire ()
bool isMounted ()
bool isRidingCreature ()
bool isPeaced ()
bool isMeditating ()
bool isAiming ()
bool isInCover ()
bool isRunning ()
bool isNonPlayerCreatureObject ()
bool isCreature ()
bool isPlayerCreature ()
bool isAiActor ()
bool isInformantCreature ()
CampSiteActiveArea * getCurrentCamp ()
byte getCurrentWeather ()
void setCurrentWeather (byte value)
byte getCurrentWind ()
void setCurrentWind (byte value)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void destroyObjectFromWorld (bool sendSelfDestroy)
bool isInvisible ()
void setInvisible (bool invis)
Mutex * getSkillModMutex ()
float calculateCostAdjustment (byte stat, float baseCost)
void updateSpeedAndAccelerationMods ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::tangible::TangibleObject
TangibleObject ()
void initializeMembers ()
void addTemplateSkillMods (TangibleObject *targetObject)
void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
void removeSkillModsFrom (CreatureObject *creature)
void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
void removeAllSkillModsOfType (const int skillType, bool notifyClient=true)
void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void sendBaselinesTo (SceneObject *player)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
void removeDefenders ()
void setCombatState ()
void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void clearCombatState (bool clearDefenders=true)
bool hasDefender (SceneObject *defender)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
bool isHealableBy (CreatureObject *object)
void sendPvpStatusTo (CreatureObject *player)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
void updateCraftingValues (CraftingValues *values, bool firstUpdate)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
bool isKiller ()
bool isTicketCollector ()
bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
int getUseCount ()
int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
int getJunkDealerNeeded ()
void setJunkValue (int jValue)
int getJunkValue ()
void setSerialNumber (const String &serial)
void setLevel (int lev)
String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
String repairAttempt (int repairChance)
bool isBroken ()
float getHitChance ()
void broadcastPvpStatusBitmask ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject ()
void initializePrivateData ()
void loadTemplateData (SharedObjectTemplate *templateData)
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendAttributeListTo (CreatureObject *object)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
void openContainerTo (CreatureObject *player)
byte checkContainerPermission (CreatureObject *player, unsigned short permission)
void closeContainerTo (CreatureObject *player, bool notify=true)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets=true)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
String getDetailedDescription ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int HUMAN = 0
static const int RODIAN = 1
static const int TRANDOSHAN = 2
static const int MONCAL = 3
static const int WOOKIE = 4
static const int BOTHAN = 5
static const int TWILEK = 6
static const int ZABRAK = 7
static const int ITHORIAN = 0x21
static const int SULLUSTAN = 0x31
static const int MALE = 0
static const int FEMALE = 1
static unsigned const long long DEAD_TOO_LONG = 1800000
Protected Member Functions
CreatureObject (DummyConstructorParameter *param)
virtual ~CreatureObject ()
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObject
TangibleObject (DummyConstructorParameter *param)
virtual ~TangibleObject ()
Protected Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject (DummyConstructorParameter *param)
virtual ~SceneObject ()
Friends
class CreatureObjectHelper
Detailed Description
Definition at line 317 of file CreatureObject.h.
Constructor & Destructor Documentation
CreatureObject::CreatureObject ()
CreatureObject constructor, used to initialized the object
Precondition
{ templateData is a valid SharedCreatureObjectTemplate LuaObject that contains the necessary values to initialize CreatureObject }
Postcondition
{ CreatureObject is initialized }
Parameters
templateData templateData points to the SharedCreatureObjectTemplate LuaObject that is used to initialize CreatureObject members
Definition at line 49 of file CreatureObject.cpp.
References server::zone::objects::creature::CreatureObjectImplementation::_setStub().
CreatureObject::CreatureObject (DummyConstructorParameter * param) protected
Definition at line 56 of file CreatureObject.cpp.
CreatureObject::~CreatureObject () protected virtual
Definition at line 60 of file CreatureObject.cpp.
Member Function Documentation
DistributedObjectServant * CreatureObject::_getImplementation ()
Definition at line 4091 of file CreatureObject.cpp.
Referenced by activateHAMRegeneration(), activateImmediateAction(), activatePassiveWoundRegeneration(), activateQueueAction(), activateStateRecovery(), addBankCredits(), addBuff(), addCashCredits(), addCooldown(), addDotState(), addEncumbrance(), addMaxHAM(), addShockWounds(), addSkill(), addSkillMod(), addWearableObject(), addWounds(), calculateBFRatio(), calculateCostAdjustment(), calculateSpeed(), canTreatConditions(), canTreatInjuries(), canTreatStates(), canTreatWounds(), checkCooldownRecovery(), checkKnockdownRecovery(), checkLastKnockdown(), checkPostureDownRecovery(), checkPostureUpRecovery(), clearBuffs(), clearCombatState(), clearDots(), clearQueueAction(), clearState(), createChildObjects(), deleteQueueAction(), destroyObjectFromWorld(), dismount(), doAnimation(), doCombatAnimation(), enqueueCommand(), executeObjectControllerAction(), fillAttributeList(), getAccelerationMultiplierBase(), getAccelerationMultiplierMod(), getActorObject(), getBankCredits(), getBaseHAM(), getBuff(), getBuffList(), getCashCredits(), getClient(), getCommandQueue(), getControlDevice(), getCooldownTime(), getCooldownTimerMap(), getCreatureLinkID(), getCreatureName(), getCurrentCamp(), getCurrentSpeed(), getCurrentWeather(), getCurrentWind(), getDamageOverTimeList(), getEncumbrance(), getEncumbrances(), getFactionRank(), getFirstName(), getFrozen(), getGender(), getGroup(), getGroupID(), getGroupInviteCounter(), getGroupInviterID(), getGuildID(), getGuildObject(), getHAM(), getHeight(), getInstrumentID(), getLastName(), getLinkedCreature(), getListenID(), getLocomotion(), getMaxHAM(), getMoodID(), getMoodString(), getPerformanceAnimation(), getPerformanceCounter(), getPlayerObject(), getPosture(), getRunAcceleration(), getRunSpeed(), getScreenPlayState(), getShockWounds(), getSkillList(), getSkillMod(), getSkillModFromBuffs(), getSkillModList(), getSkillModMutex(), getSlopeModPercent(), getSpecies(), getSpeciesName(), getSpeedMultiplierBase(), getSpeedMultiplierMod(), getSpeedMultiplierModChanges(), getStateBitmask(), getSwimHeight(), getTargetID(), getTerrainNegotiation(), getTurnScale(), getWalkAcceleration(), getWalkSpeed(), getWatchToID(), getWeapon(), getWeaponID(), getWearablesDeltaVector(), getWounds(), handleObjectMenuSelect(), hasAttackDelay(), hasBuff(), hasDamage(), hasSkill(), hasSpice(), hasState(), hasStates(), healDamage(), healDot(), healWound(), inflictDamage(), initializeMembers(), initializeTransientMembers(), isAggressiveTo(), isAiming(), isAttackableBy(), isBerserked(), isBleeding(), isBlinded(), isCreature(), isCreatureObject(), isDancing(), isDead(), isDiseased(), isDizzied(), isEntertaining(), isFrozen(), isGrouped(), isHealableBy(), isImmobilized(), isInBountyMission(), isIncapacitated(), isInCombat(), isInCover(), isInformantCreature(), isInGuild(), isIntimidated(), isInvisible(), isKneeling(), isKnockedDown(), isListening(), isMeditating(), isMounted(), isNextActionPast(), isNonPlayerCreatureObject(), isOnFire(), isOnline(), isPeaced(), isPlayingMusic(), isPoisoned(), isProne(), isRallied(), isResuscitable(), isRidingCreature(), isRidingMount(), isRooted(), isRunning(), isSitting(), isSkillAnimating(), isSnared(), isStanding(), isStunned(), isSwimming(), isTrainerCreature(), isWatching(), loadTemplateData(), notifyLoadFromDatabase(), notifyObjectDestructionObservers(), notifyObjectInserted(), notifyObjectKillObservers(), notifyObjectRemoved(), notifyPostureChange(), notifySelfPositionUpdate(), playEffect(), playMusicMessage(), queueDizzyFallEvent(), removeAllSkillModsOfType(), removeAttackDelay(), removeBuff(), removeSkill(), removeSkillMod(), removeStateBuff(), removeWearableObject(), selectConversationOption(), sendBaselinesTo(), sendBuffsTo(), sendConversationStartTo(), sendExecuteConsoleCommand(), sendMessage(), sendNewbieTutorialEnableHudElement(), sendNewbieTutorialRequest(), sendOpenHolocronToPageMessage(), sendSlottedObjectsTo(), sendSystemMessage(), sendToOwner(), setAccelerationMultiplierBase(), setAccelerationMultiplierMod(), setAimingState(), setBankCredits(), setBaseHAM(), setBerserkedState(), setBlindedState(), setCashCredits(), setClient(), setCombatState(), setControlDevice(), setCoverState(), setCreatureLink(), setCurrentSpeed(), setCurrentWeather(), setCurrentWind(), setDizziedState(), setEncumbrance(), setFactionRank(), setGuildObject(), setHAM(), setHeight(), setInstrumentID(), setIntimidatedState(), setInvisible(), setLevel(), setListenToID(), setMaxHAM(), setMeditateState(), setMood(), setMoodString(), setNextAttackDelay(), setPerformanceAnimation(), setPerformanceCounter(), setPosture(), setRalliedState(), setRootedState(), setRunSpeed(), setScreenPlayState(), setShockWounds(), setSnaredState(), setSpeedMultiplierBase(), setSpeedMultiplierMod(), setState(), setStunnedState(), setTargetID(), setTerrainNegotiation(), setTurnScale(), setWatchToID(), setWeapon(), setWounds(), stopEntertaining(), subtractBankCredits(), subtractCashCredits(), updateCooldownTimer(), updateGroup(), updateGroupInviterID(), updateKnockdownRecovery(), updateLastKnockdown(), updateLastSuccessfulCombatAction(), updateLocomotion(), updatePostureDownRecovery(), updatePostureUpRecovery(), updateSpeedAndAccelerationMods(), updateTimeOfDeath(), updateToDatabaseAllObjects(), verifyBankCredits(), and verifyCashCredits().
DistributedObjectServant * CreatureObject::_getImplementationForRead ()
Definition at line 4097 of file CreatureObject.cpp.
Referenced by isAiActor(), isPlayerCreature(), and sendTo().
void CreatureObject::_setImplementation (DistributedObjectServant * servant)
Definition at line 4101 of file CreatureObject.cpp.
void CreatureObject::activateHAMRegeneration ()
Definition at line 2132 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::activateHAMRegeneration(), and RPC_ACTIVATEHAMREGENERATION__.
Referenced by FleeStateComponent::doRecovery(), AttackStateComponent::doRecovery(), StandingStateComponent::doRecovery(), AlertStateComponent::doRecovery(), RetreatStateComponent::doRecovery(), WanderingStateComponent::doRecovery(), and server::zone::objects::player::PlayerObjectImplementation::doRecovery().
void CreatureObject::activateImmediateAction ()
Definition at line 2517 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::activateImmediateAction(), and RPC_ACTIVATEIMMEDIATEACTION__.
void CreatureObject::activatePassiveWoundRegeneration ()
Definition at line 2145 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::activatePassiveWoundRegeneration(), and RPC_ACTIVATEPASSIVEWOUNDREGENERATION__.
void CreatureObject::activateQueueAction ()
Definition at line 2504 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::activateQueueAction(), and RPC_ACTIVATEQUEUEACTION__.
void CreatureObject::activateStateRecovery ()
Definition at line 2158 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::activateStateRecovery(), and RPC_ACTIVATESTATERECOVERY__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::doRecovery().
void CreatureObject::addBankCredits (int credits, bool notifyClient = true)
Definition at line 1145 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addBankCredits(), and RPC_ADDBANKCREDITS__INT_BOOL_.
Referenced by BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::building::BuildingObjectImplementation::payAccessFee(), and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
void CreatureObject::addBuff (Buff * buff)
Adds the buff to the creature, activating it and sending packets if it is a player. Buffs should never be added to the list without sending of packets.
Parameters
buff The Buff object to add the creature.
Definition at line 845 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addBuff(), and RPC_ADDBUFF__BUFF_.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::activateEntertainerBuff(), server::zone::objects::group::GroupObjectImplementation::addGroupModifiers(), CombatQueueCommand::applyEffect(), ForceOfWillCommand::doDowner(), server::zone::managers::player::PlayerManagerImplementation::doEnhanceCharacter(), ForceResistPoisonCommand::doQueueCommand(), ForceResistStatesCommand::doQueueCommand(), VitalizeCommand::doQueueCommand(), MaskscentCommand::doQueueCommand(), AvoidIncapacitationCommand::doQueueCommand(), RegenerationCommand::doQueueCommand(), ForceResistBleedingCommand::doQueueCommand(), SetSpeedCommand::doQueueCommand(), ForceResistDiseaseCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), ForceSpeed1Command::doQueueCommand(), ForceShield2Command::doQueueCommand(), ForceShield1Command::doQueueCommand(), ForceAbsorb2Command::doQueueCommand(), ForceArmor1Command::doQueueCommand(), ForceRun1Command::doQueueCommand(), ForceRun2Command::doQueueCommand(), ForceArmor2Command::doQueueCommand(), ForceRun3Command::doQueueCommand(), ForceFeedback1Command::doQueueCommand(), ForceFeedback2Command::doQueueCommand(), ForceAbsorb1Command::doQueueCommand(), ForceSpeed2Command::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), CenterOfBeingCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), RetreatCommand::doRetreat(), SkillBuffObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), and server::zone::managers::player::PlayerManagerImplementation::healEnhance().
void CreatureObject::addCashCredits (int credits, bool notifyClient = true)
Definition at line 1160 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addCashCredits(), and RPC_ADDCASHCREDITS__INT_BOOL_.
Referenced by server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::managers::player::PlayerManagerImplementation::handleVerifyTradeMessage(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), TipCommand::performTip(), and JunkDealerSellListSuiCallback::run().
void CreatureObject::addCooldown (const String & name, unsigned int miliseconds)
Definition at line 2429 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addCooldown(), and RPC_ADDCOOLDOWN__STRING_INT_.
Referenced by server::zone::managers::city::CityManagerImplementation::changeCitySpecialization(), StructureManager::declareResidence(), RegenerationCommand::doQueueCommand(), VitalizeCommand::doQueueCommand(), EquilibriumCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), ForceOfWillCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), server::zone::objects::player::PlayerObjectImplementation::resetFirstIncapacitationTime(), RenameCitySuiCallback::run(), server::zone::objects::player::PlayerObjectImplementation::setFactionStatus(), and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
int CreatureObject::addDotState (unsigned long long dotType, unsigned long long objectID, unsigned int strength, byte type, unsigned int duration, float potency, unsigned int defense, int secondaryStrength = 0)
Definition at line 1005 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addDotState(), and RPC_ADDDOTSTATE__LONG_LONG_INT_BYTE_INT_FLOAT_INT_INT_.
Referenced by CombatManager::applyDots(), CombatManager::applyWeaponDots(), DotPackCommand::doAreaMedicActionTarget(), DotPackCommand::doQueueCommand(), and server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem().
void CreatureObject::addEncumbrance (int type, int value, bool notifyClient = true)
Definition at line 666 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addEncumbrance(), and RPC_ADDENCUMBRANCE__INT_INT_BOOL_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::applyEncumbrancies(), and server::zone::managers::player::PlayerManagerImplementation::removeEncumbrancies().
void CreatureObject::addMaxHAM (int type, int value, bool notifyClient = true)
Definition at line 634 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addMaxHAM(), and RPC_ADDMAXHAM__INT_INT_BOOL_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::applyEncumbrancies(), and server::zone::managers::player::PlayerManagerImplementation::removeEncumbrancies().
void CreatureObject::addShockWounds (int shockToAdd, bool notiyClient = true)
Definition at line 800 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addShockWounds(), and RPC_ADDSHOCKWOUNDS__INT_BOOL_.
Referenced by CombatManager::applyDamage(), DamageOverTime::doDiseaseTick(), DamageOverTime::doFireTick(), ForceOfWillCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), HealBattleFatigueSelf2Command::healBattleFatigue(), HealBattleFatigueSelf1Command::healBattleFatigue(), server::zone::objects::player::sessions::EntertainingSessionImplementation::healWounds(), and server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner().
void CreatureObject::addSkill (Skill * skill, bool notifyClient = true)
Adds the specified skillbox to this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified skillbox in the delta vector
Parameters
skillbox skillbox to add
notifyClient if set true the client will be updated with the changes
Definition at line 1313 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::addSkill().
Referenced by server::zone::managers::skill::SkillManager::awardSkill().
void CreatureObject::addSkill (const String & skill, bool notifyClient = true)
Adds the specified skillbox to this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified skillbox in the delta vector
Parameters
skillbox skillbox name to add
notifyClient if set true the client will be updated with the changes
Definition at line 1322 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addSkill(), and RPC_ADDSKILL__STRING_BOOL_.
void CreatureObject::addSkillMod (const int modType, const String & skillMod, int value, bool notifyClient = true)
Adds new value to the specified skillmod (add a negative number to subtract)
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
skillMod skill mod to change
value value to add/subtract
notifyClient if set true the client will be updated with the changes
Definition at line 1361 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addSkillMod(), and RPC_ADDSKILLMOD__INT_STRING_INT_BOOL_.
Referenced by server::zone::objects::tangible::wearables::WearableContainerObjectImplementation::applySkillModsTo(), server::zone::objects::tangible::wearables::WearableObjectImplementation::applySkillModsTo(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::applySkillModsTo(), server::zone::objects::region::CityRegionImplementation::applySpecializationModifiers(), VolleyFireCommand::attemptVolleyFire(), server::zone::managers::skill::SkillManager::awardSkill(), and server::zone::managers::skill::SkillModManager::compareMods().
void CreatureObject::addWearableObject (TangibleObject * object, bool notifyClient = true)
Definition at line 915 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addWearableObject(), and RPC_ADDWEARABLEOBJECT__TANGIBLEOBJECT_BOOL_.
Referenced by PlayerContainerComponent::notifyObjectInserted().
int CreatureObject::addWounds (int type, int value, bool notifyClient = true)
Returns
returns wounds added
Definition at line 602 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::addWounds(), and RPC_ADDWOUNDS__INT_INT_BOOL_.
Referenced by CombatManager::applyDamage(), BoostmoraleCommand::distributeWounds(), DamageOverTime::doDiseaseTick(), DamageOverTime::doFireTick(), ForceOfWillCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), server::zone::objects::player::sessions::EntertainingSessionImplementation::healWounds(), server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner(), and ResourceSpawner::sendSampleResults().
float CreatureObject::calculateBFRatio ()
Definition at line 1950 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::calculateBFRatio(), and RPC_CALCULATEBFRATIO__.
Referenced by CombatManager::applyStates(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::calculatePower(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::calculatePower(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::calculatePower(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::calculatePower(), HealMindCommand::doQueueCommand(), TendCommand::doQueueCommand(), and HealEnhanceCommand::doQueueCommand().
float CreatureObject::calculateCostAdjustment (byte stat, float baseCost)
Definition at line 4063 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::calculateCostAdjustment(), and RPC_CALCULATECOSTADJUSTMENT__BYTE_FLOAT_.
Referenced by Berserk2Command::doQueueCommand(), DazzleCommand::doQueueCommand(), VentriloquismCommand::doQueueCommand(), DistractCommand::doQueueCommand(), SteadyaimCommand::doQueueCommand(), FirejetCommand::doQueueCommand(), FormupCommand::doQueueCommand(), ColorlightsCommand::doQueueCommand(), RallyCommand::doQueueCommand(), SmokebombCommand::doQueueCommand(), SpotlightCommand::doQueueCommand(), VolleyFireCommand::doQueueCommand(), Berserk1Command::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), TakeCoverCommand::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), RetreatCommand::doQueueCommand(), ResourceSpawner::sendSample(), ResourceSpawner::sendSurvey(), and server::zone::managers::minigames::ForageManagerImplementation::startForaging().
float CreatureObject::calculateSpeed ()
checks locomotion and sets a new one if appropriate
Precondition
{ this object is locked }
Postcondition
{this object is locked, this object has the new locomotion set, if appropriate }
Definition at line 322 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::calculateSpeed(), and RPC_CALCULATESPEED__.
Referenced by CombatManager::calculatePostureModifier().
bool CreatureObject::canTreatConditions ()
Definition at line 1858 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::canTreatConditions(), and RPC_CANTREATCONDITIONS__.
Referenced by CurePackCommand::canPerformSkill().
bool CreatureObject::canTreatInjuries ()
Definition at line 1819 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::canTreatInjuries(), and RPC_CANTREATINJURIES__.
Referenced by HealDamageCommand::canPerformSkill().
bool CreatureObject::canTreatStates ()
Definition at line 1832 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::canTreatStates(), and RPC_CANTREATSTATES__.
Referenced by HealStateCommand::canPerformSkill().
bool CreatureObject::canTreatWounds ()
Definition at line 1845 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::canTreatWounds(), and RPC_CANTREATWOUNDS__.
Referenced by HealEnhanceCommand::canPerformSkill(), and HealWoundCommand::canPerformSkill().
bool CreatureObject::checkCooldownRecovery (const String & cooldown)
Definition at line 2406 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::checkCooldownRecovery(), and RPC_CHECKCOOLDOWNRECOVERY__STRING_.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::abortShutdownSequence(), CombatManager::applyStates(), BurstRunCommand::checkBurstRun(), MaskscentCommand::checkMaskScent(), RetreatCommand::checkRetreat(), StructureManager::declareResidence(), RegenerationCommand::doQueueCommand(), VitalizeCommand::doQueueCommand(), EquilibriumCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), DismountCommand::doQueueCommand(), MountCommand::doQueueCommand(), ForceOfWillCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::handleObjectMenuSelect(), server::zone::objects::player::PlayerObjectImplementation::isFirstIncapacitationExpired(), server::zone::managers::city::CityManagerImplementation::promptCitySpecialization(), server::zone::managers::city::CityManagerImplementation::promptWithdrawCityTreasury(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), server::zone::managers::city::CityManagerImplementation::sendChangeCityName(), server::zone::objects::intangible::VehicleControlDeviceImplementation::storeObject(), and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
bool CreatureObject::checkKnockdownRecovery ()
Definition at line 2284 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::checkKnockdownRecovery(), and RPC_CHECKKNOCKDOWNRECOVERY__.
Referenced by CombatManager::doCombatAction().
bool CreatureObject::checkLastKnockdown ()
Definition at line 2297 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::checkLastKnockdown(), and RPC_CHECKLASTKNOCKDOWN__.
bool CreatureObject::checkPostureDownRecovery ()
Definition at line 2336 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::checkPostureDownRecovery(), and RPC_CHECKPOSTUREDOWNRECOVERY__.
bool CreatureObject::checkPostureUpRecovery ()
Definition at line 2378 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::checkPostureUpRecovery(), and RPC_CHECKPOSTUREUPRECOVERY__.
void CreatureObject::clearBuffs (bool updateclient)
Removes all buffs from the creature, deactivating any currently active buffs.
Parameters
updateclient Should packets be sent to the player?
Definition at line 901 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::clearBuffs(), and RPC_CLEARBUFFS__BOOL_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::killPlayer().
void CreatureObject::clearCombatState (bool clearDefenders = true)
Cleares the combat state
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object is not in a combat state }
Parameters
clearDefenders if true the defender vector willl be emptied
Definition at line 293 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::clearCombatState(), and RPC_CLEARCOMBATSTATE__BOOL_.
Referenced by CombatManager::attemptPeace(), and CombatManager::forcePeace().
void CreatureObject::clearDots ()
Definition at line 1041 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::clearDots(), and RPC_CLEARDOTS__.
Referenced by server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), and server::zone::managers::player::PlayerManagerImplementation::notifyDestruction().
void CreatureObject::clearQueueAction (unsigned int actioncntr, float timer = 0, unsigned int tab1 = 0, unsigned int tab2 = 0)
Sends a CommandQueueRemove ObjectControllerMessage to the owner client of this object
Precondition
{ }
Postcondition
{ client received the CommandQueueRemove message }
Parameters
actioncntr action id that will be cleared from clients queue
timer how many seconds will the action take to execute
tab1 message 1
tab2 message 2
Definition at line 113 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::clearQueueAction(), and RPC_CLEARQUEUEACTION__INT_FLOAT_INT_INT_.
Referenced by server::zone::objects::creature::commands::QueueCommand::onComplete(), server::zone::objects::creature::commands::QueueCommand::onFail(), server::zone::objects::creature::commands::QueueCommand::onLocomotionFail(), and server::zone::objects::creature::commands::QueueCommand::onStateFail().
bool CreatureObject::clearState (unsigned long long state, bool notifyClient = true)
Cleares a state from the state bitmask
Precondition
{ this object is locked }
Postcondition
{ this object is locked, stateBitmask doesnt have the specified state }
Parameters
state state to clear
Definition at line 1517 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::clearState(), and RPC_CLEARSTATE__LONG_BOOL_.
Referenced by DamageOverTimeList::activateDots(), DamageOverTimeList::clear(), SetPlayerStateCommand::doQueueCommand(), DismountCommand::doQueueCommand(), MountCommand::doQueueCommand(), DamageOverTimeList::healState(), server::zone::managers::player::PlayerManagerImplementation::notifyObserverEvent(), server::zone::objects::player::PlayerObjectImplementation::reload(), server::zone::objects::intangible::ShipControlDeviceImplementation::storeObject(), and server::zone::managers::player::PlayerManagerImplementation::updateSwimmingState().
void CreatureObject::createChildObjects ()
Definition at line 78 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), and RPC_CREATECHILDOBJECTS__.
void CreatureObject::deleteQueueAction (unsigned int actionCount)
Removes a command from queue
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
actionCount the action count to remove
Definition at line 1488 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::deleteQueueAction(), and RPC_DELETEQUEUEACTION__INT_.
void CreatureObject::destroyObjectFromWorld (bool sendSelfDestroy)
Definition at line 4013 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::destroyObjectFromWorld(), and RPC_DESTROYOBJECTFROMWORLD__BOOL_.
Referenced by server::zone::objects::mission::bountyhunter::events::FindTargetTask::droidSent().
void CreatureObject::dismount ()
Definition at line 1937 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::dismount(), and RPC_DISMOUNT__.
Referenced by CombatQueueCommand::applyEffect(), and server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage().
void CreatureObject::doAnimation (const String & animation)
Definition at line 2444 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::doAnimation(), and RPC_DOANIMATION__STRING_.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), server::zone::managers::minigames::FishingManagerImplementation::animate(), server::zone::objects::tangible::firework::FireworkObjectImplementation::completeLaunch(), CurePackCommand::doAnimations(), FirstAidCommand::doAnimations(), TendCommand::doAnimations(), HealMindCommand::doAnimations(), QuickHealCommand::doAnimations(), HealWoundCommand::doAnimations(), HealDamageCommand::doAnimations(), HealStateCommand::doAnimations(), RevivePlayerCommand::doAnimations(), HealEnhanceCommand::doAnimations(), server::zone::managers::minigames::FishingManagerImplementation::startFishing(), server::zone::managers::minigames::ForageManagerImplementation::startForaging(), and server::zone::managers::minigames::FishingManagerImplementation::stopFishing().
void CreatureObject::doCombatAnimation (CreatureObject * defender, unsigned int animationCRC, byte hit, byte trails)
Definition at line 2458 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::doCombatAnimation(), and RPC_DOCOMBATANIMATION__CREATUREOBJECT_INT_BYTE_BYTE_.
Referenced by ForceCureDiseaseCommand::doAnimations(), ForceCurePoisonCommand::doAnimations(), HealStatesOtherCommand::doAnimations(), StopBleedingCommand::doAnimations(), HealAllOther1Command::doAnimations(), HealAllOther2Command::doAnimations(), HealActionWoundOther2Command::doAnimations(), HealHealthWoundOther2Command::doAnimations(), HealMindWoundOther1Command::doAnimations(), HealMindWoundOther2Command::doAnimations(), HealActionWoundOther1Command::doAnimations(), HealHealthWoundOther1Command::doAnimations(), TotalHealOtherCommand::doAnimations(), TransferForceCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), and TumbleToKneelingCommand::doQueueCommand().
void CreatureObject::enqueueCommand (unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString & arguments, int priority = -1)
Enqueues a command action
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
actionCRC queue command crc
actionCount command count
targetID target
arguments arguments
priority command priority
Definition at line 1440 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::enqueueCommand(), and RPC_ENQUEUECOMMAND__INT_INT_LONG_UNICODESTRING_INT_.
void CreatureObject::executeObjectControllerAction (unsigned int actionCRC)
Executes an object controller command
Definition at line 1561 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::executeObjectControllerAction(), and RPC_EXECUTEOBJECTCONTROLLERACTION__INT_.
Referenced by server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::doFishing(), ItemmovebackCommand::doQueueCommand(), ItemmovedownCommand::doQueueCommand(), ItemmoveforwardCommand::doQueueCommand(), ItemmoveupCommand::doQueueCommand(), InnateCommand::doQueueCommand(), ItemrotateleftCommand::doQueueCommand(), ItemrotaterightCommand::doQueueCommand(), SetpermissionCommand::doQueueCommand(), InstallationObjectMenuComponent::handleObjectMenuSelect(), StructureTerminalMenuComponent::handleObjectMenuSelect(), PlayerObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::ticketcollector::TicketCollectorImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::deed::structure::StructureDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::ticket::TicketObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::InstrumentImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::objects::creature::AiAgentImplementation::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObjectImplementation::handleObjectMenuSelect(), server::zone::managers::sui::SuiManager::handleStartDancing(), server::zone::managers::sui::SuiManager::handleStartMusic(), server::zone::managers::player::PlayerManagerImplementation::killPlayer(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), TicketSelectionSuiCallback::run(), NameStructureSuiCallback::run(), server::zone::objects::tangible::InstrumentImplementation::spawnInAdminCell(), server::zone::objects::intangible::VehicleControlDeviceImplementation::spawnObject(), server::zone::objects::intangible::VehicleControlDeviceImplementation::storeObject(), PlayerZoneComponent::switchZone(), and PlayerZoneComponent::teleport().
void CreatureObject::executeObjectControllerAction (unsigned int actionCRC, unsigned long long targetID, const UnicodeString & args)
Definition at line 1575 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::executeObjectControllerAction(), and RPC_EXECUTEOBJECTCONTROLLERACTION__INT_LONG_UNICODESTRING_.
void CreatureObject::fillAttributeList (AttributeListMessage * msg, CreatureObject * object)
Definition at line 3998 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::fillAttributeList(), and RPC_FILLATTRIBUTELIST__ATTRIBUTELISTMESSAGE_CREATUREOBJECT_.
float CreatureObject::getAccelerationMultiplierBase ()
Definition at line 2834 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getAccelerationMultiplierBase(), and RPC_GETACCELERATIONMULTIPLIERBASE__.
Referenced by CreatureObjectMessage4::CreatureObjectMessage4().
float CreatureObject::getAccelerationMultiplierMod ()
Definition at line 2847 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getAccelerationMultiplierMod(), and RPC_GETACCELERATIONMULTIPLIERMOD__.
Referenced by CreatureObjectMessage4::CreatureObjectMessage4().
AiActor * CreatureObject::getActorObject ()
Definition at line 1884 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getActorObject(), and RPC_GETACTOROBJECT__.
int CreatureObject::getBankCredits ()
Definition at line 2558 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getBankCredits(), and RPC_GETBANKCREDITS__.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::checkBidAuction(), server::zone::managers::auction::AuctionManagerImplementation::checkSaleItem(), server::zone::managers::minigames::GamblingManagerImplementation::createRouletteWindow(), server::zone::managers::minigames::GamblingManagerImplementation::createSlotWindow(), CreatureObjectMessage1::CreatureObjectMessage1(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), PurchaseTicketCommand::doQueueCommand(), server::zone::managers::sui::SuiManager::handleBankTransfer(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainSkillScreenHandler::handleScreen(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), server::zone::objects::structure::StructureObjectImplementation::payMaintenance(), TipCommand::performBankTip(), PlayerMoneyResponseMessage::PlayerMoneyResponseMessage(), StructureManager::promptPayUncondemnMaintenance(), InsuranceAllConfirmSuiCallback::run(), InsuranceMenuSuiCallback::run(), CloningStoreSuiCallback::run(), RepairVehicleSuiCallback::run(), TaxPayMailTask::run(), StructurePayUncondemnMaintenanceSuiCallback::run(), server::zone::objects::creature::VehicleObjectImplementation::sendRepairConfirmTo(), and server::zone::managers::player::PlayerManagerImplementation::shouldRescheduleCorpseDestruction().
int CreatureObject::getBaseHAM (int idx)
Definition at line 2584 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getBaseHAM(), and RPC_GETBASEHAM__INT_.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addRacialMods(), CreatureObjectMessage1::CreatureObjectMessage1(), RequestStatMigrationDataCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), and server::zone::managers::player::PlayerManagerImplementation::fixHAM().
DeltaVector< int > * CreatureObject::getBaseHAM ()
Definition at line 3288 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getBaseHAM().
Buff * CreatureObject::getBuff (unsigned int buffcrc)
Definition at line 977 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getBuff(), and RPC_GETBUFF__INT_.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::activateEntertainerBuff(), server::zone::managers::crafting::CraftingManagerImplementation::calculateAssemblySuccess(), server::zone::managers::crafting::CraftingManagerImplementation::calculateExperimentationSuccess(), CurePackCommand::deactivateConditionTreatment(), HealDamageCommand::deactivateInjuryTreatment(), HealStateCommand::deactivateStateTreatment(), HealWoundCommand::deactivateWoundTreatment(), HealEnhanceCommand::deactivateWoundTreatment(), DotPackCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), and server::zone::managers::player::PlayerManagerImplementation::healEnhance().
BuffList * CreatureObject::getBuffList ()
Definition at line 968 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getBuffList().
Referenced by server::zone::managers::player::PlayerManagerImplementation::fixHAM(), and server::zone::managers::skill::SkillModManager::verifyBuffSkillMods().
int CreatureObject::getCashCredits ()
Definition at line 2571 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getCashCredits(), and RPC_GETCASHCREDITS__.
Referenced by server::zone::managers::minigames::GamblingManagerImplementation::bet(), server::zone::managers::minigames::GamblingManagerImplementation::calculateOutcome(), server::zone::managers::player::PlayerManagerImplementation::checkTradeItems(), server::zone::managers::minigames::GamblingManagerImplementation::createRouletteWindow(), server::zone::managers::minigames::GamblingManagerImplementation::createSlotWindow(), CreatureObjectMessage1::CreatureObjectMessage1(), server::zone::managers::city::CityManagerImplementation::depositToCityTreasury(), PaymaintenanceCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), server::zone::managers::sui::SuiManager::handleBankTransfer(), server::zone::managers::player::PlayerManagerImplementation::handleGiveMoneyMessage(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainSkillScreenHandler::handleScreen(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::objects::building::BuildingObjectImplementation::payAccessFee(), StructureManager::payMaintenance(), server::zone::objects::structure::StructureObjectImplementation::payMaintenance(), TipCommand::performTip(), PlayerMoneyResponseMessage::PlayerMoneyResponseMessage(), server::zone::managers::city::CityManagerImplementation::promptDepositCityTreasury(), StructureManager::promptPayMaintenance(), StructureManager::promptPayUncondemnMaintenance(), InsuranceAllConfirmSuiCallback::run(), InsuranceMenuSuiCallback::run(), CloningStoreSuiCallback::run(), StructurePayUncondemnMaintenanceSuiCallback::run(), server::zone::managers::player::PlayerManagerImplementation::sendActivateCloneRequest(), and server::zone::managers::player::PlayerManagerImplementation::shouldRescheduleCorpseDestruction().
ZoneClientSession * CreatureObject::getClient ()
Definition at line 3409 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getClient(), and RPC_GETCLIENT__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::doRecovery(), server::zone::objects::player::PlayerObjectImplementation::reload(), and SelectCharacterCallback::run().
CommandQueueActionVector * CreatureObject::getCommandQueue ()
Definition at line 2908 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getCommandQueue().
Referenced by server::zone::objects::player::PlayerObjectImplementation::doRecovery().
ManagedWeakReference< ControlDevice * > CreatureObject::getControlDevice ()
Definition at line 3435 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getControlDevice(), and RPC_GETCONTROLDEVICE__.
Referenced by DismountCommand::doQueueCommand().
Time * CreatureObject::getCooldownTime (const String & cooldown)
Definition at line 2420 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getCooldownTime().
Referenced by MaskscentCommand::checkMaskScent(), StructureManager::declareResidence(), VitalizeCommand::doQueueCommand(), RegenerationCommand::doQueueCommand(), EquilibriumCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), and server::zone::managers::city::CityManagerImplementation::promptCitySpecialization().
CooldownTimerMap * CreatureObject::getCooldownTimerMap ()
Definition at line 2210 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getCooldownTimerMap().
Referenced by AreatrackCommand::doQueueCommand(), and server::zone::objects::player::PlayerObjectImplementation::doRecovery().
unsigned long long CreatureObject::getCreatureLinkID ()
Definition at line 2742 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getCreatureLinkID(), and RPC_GETCREATURELINKID__.
Referenced by CreatureObjectMessage3::CreatureObjectMessage3(), MountCommand::doQueueCommand(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), and CreatureObjectDeltaMessage3::updateCreatureLinkID().
UnicodeString CreatureObject::getCreatureName ()
Definition at line 2530 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getCreatureName(), and RPC_GETCREATURENAME__.
Referenced by GroupManager::inviteToGroup(), TipCommand::performBankTip(), and TipCommand::performTip().
CampSiteActiveArea * CreatureObject::getCurrentCamp ()
Definition at line 3916 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getCurrentCamp(), and RPC_GETCURRENTCAMP__.
Referenced by server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), CampKitMenuComponent::handleObjectMenuSelect(), and server::zone::managers::skill::SkillModManager::verifyStructureSkillMods().
float CreatureObject::getCurrentSpeed ()
Definition at line 2886 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getCurrentSpeed(), and RPC_GETCURRENTSPEED__.
Referenced by AiStateComponent::doMovement(), and AiStateComponent::getSpeed().
byte CreatureObject::getCurrentWeather ()
Definition at line 3929 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getCurrentWeather(), and RPC_GETCURRENTWEATHER__.
Referenced by server::zone::managers::weather::WeatherManagerImplementation::sendWeatherTo().
byte CreatureObject::getCurrentWind ()
Definition at line 3956 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getCurrentWind(), and RPC_GETCURRENTWIND__.
Referenced by server::zone::managers::weather::WeatherManagerImplementation::sendWeatherTo().
DamageOverTimeList * CreatureObject::getDamageOverTimeList ()
Definition at line 1054 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getDamageOverTimeList().
Referenced by server::zone::objects::player::PlayerObjectImplementation::doRecovery().
int CreatureObject::getEncumbrance (int idx)
Definition at line 2667 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getEncumbrance(), and RPC_GETENCUMBRANCE__INT_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::fixHAM().
DeltaVector< int > * CreatureObject::getEncumbrances ()
Definition at line 2681 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getEncumbrances().
Referenced by CreatureObjectMessage4::CreatureObjectMessage4().
byte CreatureObject::getFactionRank ()
Definition at line 2716 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getFactionRank(), and RPC_GETFACTIONRANK__.
Referenced by CreatureObjectMessage3::CreatureObjectMessage3(), DelegateFactionPointsCommand::doDelegate(), DelegateFactionPointsCommand::doQueueCommand(), HQMenuComponent::handleObjectMenuSelect(), server::zone::objects::player::PlayerObjectImplementation::increaseFactionStanding(), and CreatureObjectDeltaMessage3::updateFactionRank().
String CreatureObject::getFirstName ()
Definition at line 1776 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getFirstName(), and RPC_GETFIRSTNAME__.
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::chat::room::ChatRoomImplementation::addPlayer(), server::chat::ChatManagerImplementation::addPlayer(), server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::chat::ChatManagerImplementation::broadcastGalaxy(), server::zone::managers::minigames::GamblingManagerImplementation::calculateOutcome(), RevivePlayerCommand::canPerformSkill(), ChatOnLeaveRoom::ChatOnLeaveRoom(), server::zone::managers::auction::AuctionManagerImplementation::checkRetrieve(), server::zone::managers::skill::SkillModManager::compareMods(), server::zone::managers::city::CityManagerImplementation::contractCity(), server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), server::zone::managers::city::CityManagerImplementation::destroyCity(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), BandFlourishCommand::doBandFlourish(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), SetNameCommand::doQueueCommand(), CompleteQuestCommand::doQueueCommand(), DumpTargetInformationCommand::doQueueCommand(), UnfreezePlayerCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), FreezePlayerCommand::doQueueCommand(), GrantSkillCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), SetFactionStandingCommand::doQueueCommand(), DumpZoneInformationCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), TendCommand::doQueueCommand(), DiceMenuComponent::doRoll(), TransferstructureCommand::doTransferStructure(), DragIncapacitatedPlayerCommand::drag(), server::zone::managers::city::CityManagerImplementation::expandCity(), server::zone::managers::auction::AuctionManagerImplementation::fillAuctionQueryHeadersResponseMessage(), server::zone::managers::minigames::ForageManagerImplementation::finishForaging(), ForageAreaCollection::ForageAreaCollection(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), server::zone::objects::tangible::threat::ThreatMatrix::getLargestThreat(), TurretFireTask::getTargetName(), server::chat::ChatManagerImplementation::handleChatRoomMessage(), server::chat::ChatManagerImplementation::handleGroupChat(), server::chat::ChatManagerImplementation::handleGuildChat(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetKilled(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetReceivesDamage(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleOperateToggle(), server::chat::ChatManagerImplementation::handlePlanetChat(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainedMasterScreenHandler::handleScreen(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), server::chat::room::ChatRoomImplementation::hasPlayer(), server::zone::objects::structure::StructureObjectImplementation::isOnAdminList(), server::zone::objects::structure::StructureObjectImplementation::isOnBanList(), server::zone::objects::structure::StructureObjectImplementation::isOnEntryList(), server::zone::objects::structure::StructureObjectImplementation::isOnHopperList(), server::zone::objects::structure::StructureObjectImplementation::isOnPermissionList(), GroupManager::makeLeader(), server::zone::objects::player::PlayerObjectImplementation::notifyOnline(), StructureManager::placeStructure(), server::zone::managers::city::CityManagerImplementation::processIncomeTax(), CharacterNameMap::put(), server::zone::managers::city::CityManagerImplementation::registerCitizen(), server::chat::room::ChatRoomImplementation::removePlayer(), StructureManager::reportStructureStatus(), GmReviveCommand::revivePlayer(), TaxPayMailTask::run(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendBaselinesTo(), server::zone::managers::player::PlayerManagerImplementation::sendBattleFatigueMessage(), ForceCurePoisonCommand::sendCureMessage(), StopBleedingCommand::sendCureMessage(), ForceCureDiseaseCommand::sendCureMessage(), FirstAidCommand::sendCureMessage(), CurePackCommand::sendCureMessage(), HealEnhanceCommand::sendEnhanceMessage(), server::zone::managers::guild::GuildManagerImplementation::sendGuildMail(), HealMindCommand::sendHealMessage(), TendCommand::sendHealMessage(), QuickHealCommand::sendHealMessage(), HealAllOther1Command::sendHealMessage(), HealAllOther2Command::sendHealMessage(), HealDamageCommand::sendHealMessage(), TotalHealOtherCommand::sendHealMessage(), ChatPersistentMessageToServerCallback::sendMail(), server::zone::managers::city::CityManagerImplementation::sendMail(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailCondemned(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailDecay(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailMaintenanceWithdrawnFromBank(), HealStatesOtherCommand::sendStateMessage(), HealStateCommand::sendStateMessage(), server::zone::managers::guild::GuildManagerImplementation::sendTransferAckTo(), TendCommand::sendWoundMessage(), HealWoundCommand::sendWoundMessage(), HealActionWoundOther2Command::sendWoundMessage(), HealActionWoundOther1Command::sendWoundMessage(), HealMindWoundOther1Command::sendWoundMessage(), HealMindWoundOther2Command::sendWoundMessage(), HealHealthWoundOther1Command::sendWoundMessage(), HealHealthWoundOther2Command::sendWoundMessage(), TotalHealOtherCommand::sendWoundMessage(), MapLocationEntry::setObject(), CampTerminalMenuComponent::showCampStatus(), server::zone::objects::resource::ResourceContainerImplementation::split(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::statusUpdate(), server::zone::managers::player::PlayerManagerImplementation::stopListen(), server::zone::managers::player::PlayerManagerImplementation::stopWatch(), server::zone::managers::minigames::FishingManagerImplementation::success(), server::zone::managers::city::CityManagerImplementation::unregisterCitizen(), server::zone::managers::auction::AuctionManagerImplementation::updateAuctionOwner(), server::zone::managers::city::CityManagerImplementation::updateCityVoting(), server::zone::managers::skill::SkillModManager::verifyBuffSkillMods(), server::zone::managers::skill::SkillModManager::verifySkillBoxSkillMods(), server::zone::managers::skill::SkillModManager::verifyStructureSkillMods(), and server::zone::managers::skill::SkillModManager::verifyWearableSkillMods().
byte CreatureObject::getFrozen ()
Definition at line 3221 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getFrozen(), and RPC_GETFROZEN__.
Referenced by CreatureObjectMessage6::CreatureObjectMessage6().
int CreatureObject::getGender ()
Definition at line 3275 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getGender(), and RPC_GETGENDER__.
Referenced by ImageDesignManager::getSpeciesGenderString(), and server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect().
GroupObject * CreatureObject::getGroup ()
Definition at line 3130 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getGroup(), and RPC_GETGROUP__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer(), server::zone::objects::player::sessions::EntertainingSessionImplementation::awardEntertainerExperience(), server::zone::managers::player::PlayerManagerImplementation::canGroupMemberHarvestCorpse(), RevivePlayerCommand::canPerformSkill(), server::zone::managers::player::PlayerManagerImplementation::disseminateExperience(), BandFlourishCommand::doBandFlourish(), ServerSysGroupCommand::doQueueCommand(), StartBandCommand::doQueueCommand(), StopBandCommand::doQueueCommand(), VolleyFireCommand::doQueueCommand(), DismissGroupMemberCommand::doQueueCommand(), LeaveGroupCommand::doQueueCommand(), RescueCommand::doQueueCommand(), ChangeMusicCommand::doQueueCommand(), DisbandCommand::doQueueCommand(), MakeLeaderCommand::doQueueCommand(), RetreatCommand::doQueueCommand(), ChangeBandMusicCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), DragIncapacitatedPlayerCommand::drag(), PlayerObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::tangible::threat::ThreatMap::getHighestDamageGroupLeader(), server::zone::managers::mission::MissionManagerImplementation::getRandomLairSpawn(), server::chat::ChatManagerImplementation::handleGroupChat(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), GroupManager::inviteToGroup(), GroupManager::joinGroup(), LootContainerComponent::notifyObjectRemoved(), server::zone::managers::player::PlayerManagerImplementation::promptTeachableSkills(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), and server::zone::managers::director::DirectorManager::updateCellPermissionGroup().
unsigned long long CreatureObject::getGroupID ()
Definition at line 3104 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getGroupID(), and RPC_GETGROUPID__.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::activateEntertainerBuff(), server::zone::objects::creature::CreatureImplementation::canHarvestMe(), LootContainerComponent::checkContainerPermission(), CreatureObjectMessage6::CreatureObjectMessage6(), LootCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), server::zone::objects::tangible::threat::ThreatMap::getHighestDamageGroupLeader(), server::zone::objects::player::sessions::EntertainingSessionImplementation::increaseEntertainerBuff(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction(), and CreatureObjectDeltaMessage6::updateGroupID().
unsigned long long CreatureObject::getGroupInviteCounter ()
Definition at line 3143 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getGroupInviteCounter(), and RPC_GETGROUPINVITECOUNTER__.
Referenced by CreatureObjectMessage6::CreatureObjectMessage6(), and CreatureObjectDeltaMessage6::updateInviterId().
unsigned long long CreatureObject::getGroupInviterID ()
Definition at line 3117 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getGroupInviterID(), and RPC_GETGROUPINVITERID__.
Referenced by GroupManager::createGroup(), CreatureObjectMessage6::CreatureObjectMessage6(), DeclineCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), GroupManager::inviteToGroup(), GroupManager::joinGroup(), and CreatureObjectDeltaMessage6::updateInviterId().
int CreatureObject::getGuildID ()
Definition at line 3064 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getGuildID(), and RPC_GETGUILDID__.
Referenced by CreatureObjectMessage6::CreatureObjectMessage6(), and CreatureObjectDeltaMessage6::updateGuildID().
Reference< GuildObject * > CreatureObject::getGuildObject ()
Definition at line 3051 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getGuildObject(), and RPC_GETGUILDOBJECT__.
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsorshipRequest(), GuildremoveCommand::doQueueCommand(), GuildstatusCommand::doQueueCommand(), server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation::fillObjectMenuResponse(), GuildResponseMessage::GuildResponseMessage(), server::chat::ChatManagerImplementation::handleGuildChat(), server::zone::objects::guild::GuildObjectImplementation::isInWaringGuild(), server::zone::objects::structure::StructureObjectImplementation::isOnAdminList(), server::zone::objects::structure::StructureObjectImplementation::isOnBanList(), server::zone::objects::structure::StructureObjectImplementation::isOnEntryList(), server::zone::objects::structure::StructureObjectImplementation::isOnHopperList(), server::zone::objects::structure::StructureObjectImplementation::isOnPermissionList(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), GuildTransferLeaderAckSuiCallback::run(), GuildSponsorVerifySuiCallback::run(), GuildMemberListSuiCallback::run(), server::zone::managers::guild::GuildManagerImplementation::sendBaselinesTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSetTitleTo(), server::zone::managers::guild::GuildManagerImplementation::sendMemberPermissionsTo(), server::zone::managers::guild::GuildManagerImplementation::sendTransferAckTo(), server::zone::managers::guild::GuildManagerImplementation::setMemberTitle(), and server::zone::managers::guild::GuildManagerImplementation::transferLeadership().
int CreatureObject::getHAM (int idx)
Definition at line 2621 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getHAM(), and RPC_GETHAM__INT_.
Referenced by CombatManager::applySpecialAttackCost(), RevivePlayerCommand::canPerformSkill(), HealEnhanceCommand::canPerformSkill(), HealStateCommand::canPerformSkill(), HealWoundCommand::canPerformSkill(), HealDamageCommand::canPerformSkill(), CurePackCommand::canPerformSkill(), server::zone::managers::player::PlayerManagerImplementation::checkEncumbrancies(), CreatureObjectMessage6::CreatureObjectMessage6(), DamageOverTime::doBleedingTick(), DamageOverTime::doFireTick(), DamageOverTime::doPoisonTick(), VentriloquismCommand::doQueueCommand(), ColorlightsCommand::doQueueCommand(), DazzleCommand::doQueueCommand(), DistractCommand::doQueueCommand(), Berserk2Command::doQueueCommand(), SmokebombCommand::doQueueCommand(), SpotlightCommand::doQueueCommand(), EquilibriumCommand::doQueueCommand(), FirejetCommand::doQueueCommand(), Berserk1Command::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), TakeCoverCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), server::zone::managers::player::PlayerManagerImplementation::fixHAM(), DotPackCommand::hasCost(), SquadLeaderCommand::inflictHAM(), and server::zone::managers::minigames::ForageManagerImplementation::startForaging().
DeltaVector< int > * CreatureObject::getHAM ()
Definition at line 2635 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getHAM().
float CreatureObject::getHeight ()
Definition at line 3234 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getHeight(), and RPC_GETHEIGHT__.
Referenced by CreatureObjectMessage3::CreatureObjectMessage3(), EjectCommand::doQueueCommand(), CollisionManager::getRayOriginPoint(), and CreatureObjectDeltaMessage3::updateHeight().
int CreatureObject::getInstrumentID ()
Definition at line 3208 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getInstrumentID(), and RPC_GETINSTRUMENTID__.
Referenced by CreatureObjectMessage6::CreatureObjectMessage6().
String CreatureObject::getLastName ()
Definition at line 1791 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getLastName(), and RPC_GETLASTNAME__.
Referenced by SetNameCommand::doQueueCommand(), CampKitMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainedMasterScreenHandler::handleScreen(), MapLocationEntry::setObject(), CampTerminalMenuComponent::showCampStatus(), and server::zone::managers::minigames::FishingManagerImplementation::success().
ManagedWeakReference< CreatureObject * > CreatureObject::getLinkedCreature ()
Definition at line 2729 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getLinkedCreature(), and RPC_GETLINKEDCREATURE__.
unsigned long long CreatureObject::getListenID ()
Definition at line 2821 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getListenID(), and RPC_GETLISTENID__.
Referenced by CreatureObjectMessage4::CreatureObjectMessage4(), server::zone::managers::player::PlayerManagerImplementation::startListen(), and server::zone::managers::player::PlayerManagerImplementation::stopListen().
byte CreatureObject::getLocomotion ()
Definition at line 2703 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getLocomotion(), and RPC_GETLOCOMOTION__.
Referenced by CombatManager::calculatePostureModifier(), server::zone::objects::creature::commands::QueueCommand::checkInvalidLocomotions(), and server::zone::objects::creature::commands::QueueCommand::onLocomotionFail().
int CreatureObject::getMaxHAM (int idx)
Definition at line 2644 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getMaxHAM(), and RPC_GETMAXHAM__INT_.
Referenced by CreatureObjectMessage6::CreatureObjectMessage6(), ChannelForceCommand::doQueueCommand(), server::zone::managers::player::PlayerManagerImplementation::fixHAM(), and server::zone::objects::creature::buffs::SpiceBuffImplementation::setDownerAttributes().
DeltaVector< int > * CreatureObject::getMaxHAM ()
Definition at line 2658 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getMaxHAM().
byte CreatureObject::getMoodID ()
Definition at line 3169 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getMoodID(), and RPC_GETMOODID__.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), CreatureObjectMessage6::CreatureObjectMessage6(), GiveItemCommand::doQueueCommand(), server::zone::managers::player::PlayerManagerImplementation::notifyObserverEvent(), server::zone::managers::player::PlayerManagerImplementation::stopListen(), server::zone::managers::player::PlayerManagerImplementation::stopWatch(), and CreatureObjectDeltaMessage6::updateMoodID().
String CreatureObject::getMoodString ()
Definition at line 3010 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getMoodString(), and RPC_GETMOODSTRING__.
Referenced by CreatureObjectMessage6::CreatureObjectMessage6(), ForceMeditateCommand::doQueueCommand(), MeditateCommand::doQueueCommand(), server::zone::managers::minigames::FishingManagerImplementation::startFishing(), server::zone::managers::player::PlayerManagerImplementation::stopListen(), server::zone::managers::player::PlayerManagerImplementation::stopWatch(), and CreatureObjectDeltaMessage6::updateMoodStr().
String CreatureObject::getPerformanceAnimation ()
Definition at line 2995 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getPerformanceAnimation(), and RPC_GETPERFORMANCEANIMATION__.
Referenced by CreatureObjectMessage6::CreatureObjectMessage6().
int CreatureObject::getPerformanceCounter ()
Definition at line 3195 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getPerformanceCounter(), and RPC_GETPERFORMANCECOUNTER__.
Referenced by CreatureObjectMessage6::CreatureObjectMessage6().
Reference< PlayerObject * > CreatureObject::getPlayerObject ()
Definition at line 1871 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getPlayerObject(), and RPC_GETPLAYEROBJECT__.
Referenced by PlayersNearYouMessage::addFoundPlayer(), server::chat::room::ChatRoomImplementation::addPlayer(), server::zone::managers::player::creation::PlayerCreationManager::addStartingItemsInto(), server::zone::managers::player::creation::PlayerCreationManager::addStartingWeaponsInto(), server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage(), CombatManager::applySpecialAttackCost(), server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership(), server::zone::managers::player::PlayerManagerImplementation::awardExperience(), FactionManager::awardFactionStanding(), FactionManager::awardPvpFactionPoints(), server::zone::managers::skill::SkillManager::awardSkill(), Biography::Biography(), CombatManager::calculateDamageRange(), server::zone::objects::creature::VehicleObjectImplementation::calculateRepairCost(), PlayerContainerComponent::canAddObject(), server::zone::managers::skill::SkillManager::canLearnSkill(), ForceCureDiseaseCommand::canPerformSkill(), ForceCurePoisonCommand::canPerformSkill(), StopBleedingCommand::canPerformSkill(), HealStatesOtherCommand::canPerformSkill(), server::zone::managers::gcw::GCWManagerImplementation::canPlaceMoreBases(), ChangeBandMusicCommand::canPlaySong(), server::zone::managers::gcw::GCWManagerImplementation::canStartSlice(), server::zone::managers::gcw::GCWManagerImplementation::canUseTerminals(), server::zone::managers::gcw::GCWManagerImplementation::canUseTurret(), CharacterSheetResponseMessage::CharacterSheetResponseMessage(), MinefieldContainerComponent::checkContainerPermission(), ContainerComponent::checkContainerPermission(), GCWBaseContainerComponent::checkPVEPermission(), GCWBaseContainerComponent::checkPVPPermission(), server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackSecondTest(), server::zone::managers::player::PlayerManagerImplementation::checkTradeItems(), TurretFireTask::checkTurretController(), TurretFireTask::closeControls(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::closeMenu(), server::zone::managers::minigames::FishingManagerImplementation::closeMenu(), server::zone::managers::skill::SkillModManager::compareMods(), ConsentCommand::consent(), server::zone::managers::minigames::GamblingManagerImplementation::createPayoutWindow(), server::zone::managers::minigames::GamblingManagerImplementation::createRouletteWindow(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::createSellJunkLootSelection(), server::zone::managers::player::PlayerManagerImplementation::createSkippedTutorialBuilding(), server::zone::managers::minigames::GamblingManagerImplementation::createSlotWindow(), server::zone::managers::player::PlayerManagerImplementation::createTutorialBuilding(), server::zone::managers::minigames::FishingManagerImplementation::createWindow(), StructureManager::declareResidence(), CombatManager::declineDuel(), server::chat::ChatManagerImplementation::deletePersistentMessage(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), DelegateFactionPointsCommand::doDelegate(), AdjustLotCountCommand::doQueueCommand(), TransferForceCommand::doQueueCommand(), AvoidIncapacitationCommand::doQueueCommand(), CompleteQuestCommand::doQueueCommand(), FindMyTrainerCommand::doQueueCommand(), ForceResistBleedingCommand::doQueueCommand(), ForceResistDiseaseCommand::doQueueCommand(), ForceResistPoisonCommand::doQueueCommand(), ForceResistStatesCommand::doQueueCommand(), GmJediStateCommand::doQueueCommand(), GrantPadawanTrialsEligibilityCommand::doQueueCommand(), InnateCommand::doQueueCommand(), NpcConversationSelectCommand::doQueueCommand(), NpcConversationStartCommand::doQueueCommand(), NpcConversationStopCommand::doQueueCommand(), RemoveBannedPlayerCommand::doQueueCommand(), ResendLoginMessageToAllCommand::doQueueCommand(), ResetJediCommand::doQueueCommand(), SampleDNACommand::doQueueCommand(), SetBiographyCommand::doQueueCommand(), SetCurrentSkillTitleCommand::doQueueCommand(), SetLoginMessageCommand::doQueueCommand(), SetNameCommand::doQueueCommand(), SetSpeedCommand::doQueueCommand(), SetWaypointNameCommand::doQueueCommand(), SnoopCommand::doQueueCommand(), AddAllowedPlayerCommand::doQueueCommand(), ActivateQuestCommand::doQueueCommand(), AreatrackCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), ChangeDanceCommand::doQueueCommand(), ChannelForceCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), ClearVeteranRewardCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), ForceAbsorb1Command::doQueueCommand(), ForceAbsorb2Command::doQueueCommand(), ForceArmor1Command::doQueueCommand(), ForceArmor2Command::doQueueCommand(), ForceFeedback2Command::doQueueCommand(), ForceFeedback1Command::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), ForceRun1Command::doQueueCommand(), ForceRun2Command::doQueueCommand(), ForceRun3Command::doQueueCommand(), ForceShield1Command::doQueueCommand(), ForceShield2Command::doQueueCommand(), ForceSpeed1Command::doQueueCommand(), ForceSpeed2Command::doQueueCommand(), GrantSkillCommand::doQueueCommand(), InsureCommand::doQueueCommand(), KillCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), ProneCommand::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), SetPerformanceBuffTargetCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), AiIgnoreCommand::doQueueCommand(), ChangeMusicCommand::doQueueCommand(), CitybanCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), HaveconsentCommand::doQueueCommand(), InstallMissionTerminalCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), DiagnoseCommand::doQueueCommand(), GcwStatusCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), CenterOfBeingCommand::doQueueCommand(), SetFactionStandingCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), FindCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), HealActionSelf1Command::doQueueCommand(), HealActionSelf2Command::doQueueCommand(), HealActionWoundSelf1Command::doQueueCommand(), HealActionWoundSelf2Command::doQueueCommand(), HealAllSelf1Command::doQueueCommand(), HealAllSelf2Command::doQueueCommand(), HealHealthSelf1Command::doQueueCommand(), HealHealthSelf2Command::doQueueCommand(), HealHealthWoundSelf2Command::doQueueCommand(), HealMindWoundSelf1Command::doQueueCommand(), HealMindWoundSelf2Command::doQueueCommand(), HealHealthWoundSelf1Command::doQueueCommand(), HealStatesSelfCommand::doQueueCommand(), HealMindSelf1Command::doQueueCommand(), HealMindSelf2Command::doQueueCommand(), ConsentCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), HealBattleFatigueSelf1Command::doQueueCommand(), HealBattleFatigueSelf2Command::doQueueCommand(), ChangeBandMusicCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), TransferstructureCommand::doTransferStructure(), DragIncapacitatedPlayerCommand::drag(), server::zone::objects::building::BuildingObjectImplementation::ejectObject(), ServerInfoCommand::executeCommand(), ServerStatisticsCommand::executeCommand(), CityReportCommand::executeCommand(), PlayerInfoCommand::executeCommand(), CityManagementMenuComponent::fillObjectMenuResponse(), TangibleObjectMenuComponent::fillObjectMenuResponse(), TurretControlMenuComponent::fillObjectMenuResponse(), BankTerminalMenuComponent::fillObjectMenuResponse(), server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation::fillObjectMenuResponse(), server::zone::objects::creature::VehicleObjectImplementation::fillObjectMenuResponse(), server::zone::managers::player::PlayerManagerImplementation::finishHologrind(), server::zone::managers::city::CityManagerImplementation::fixMayor(), CombatManager::freeDuelList(), server::zone::managers::skill::SkillManager::fullfillsSkillPrerequisitesAndXp(), server::zone::objects::intangible::ShipControlDeviceImplementation::generateObject(), server::zone::managers::mission::MissionManagerImplementation::generateRandomFactionalDestroyMissionDescription(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), CombatManager::getArmorReduction(), server::zone::managers::player::PlayerManagerImplementation::getInRangeOwnedStructure(), server::zone::managers::mission::MissionManagerImplementation::getRandomLairSpawn(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), server::zone::managers::vendor::VendorManager::handleDisplayStatus(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAbort(), PlayerObjectMenuComponent::handleObjectMenuSelect(), CloningTerminalMenuComponent::handleObjectMenuSelect(), GogglesObjectMenuComponent::handleObjectMenuSelect(), InsuranceTerminalMenuComponent::handleObjectMenuSelect(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), TangibleObjectMenuComponent::handleObjectMenuSelect(), ArmorObjectMenuComponent::handleObjectMenuSelect(), TurretControlMenuComponent::handleObjectMenuSelect(), ForceShrineMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::ContainerImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::SurveyToolImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::recycle::RecycleToolImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::CraftingToolImplementation::handleObjectMenuSelect(), server::chat::ChatManagerImplementation::handleRequestPersistentMsg(), server::zone::objects::creature::conversation::screenhandlers::TrainerInfoScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainSkillScreenHandler::handleScreen(), server::zone::objects::installation::InstallationObjectImplementation::handleStructureAddEnergy(), server::zone::managers::sui::SuiManager::handleSuiEventNotification(), server::zone::objects::player::sessions::DestroyStructureSessionImplementation::initializeSession(), server::zone::objects::creature::ai::AiActorImplementation::isAggressiveTo(), server::zone::objects::creature::AiAgentImplementation::isAggressiveTo(), server::zone::objects::structure::StructureObjectImplementation::isOnAdminList(), server::zone::objects::structure::StructureObjectImplementation::isOnBanList(), server::zone::objects::structure::StructureObjectImplementation::isOnEntryList(), server::zone::objects::structure::StructureObjectImplementation::isOnHopperList(), server::zone::objects::structure::StructureObjectImplementation::isOnPermissionList(), server::zone::managers::player::PlayerManagerImplementation::killPlayer(), server::chat::ChatManagerImplementation::loadMail(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), VendorDataComponent::notifyObjectDestroyingFromDatabase(), PlayerContainerComponent::notifyObjectInserted(), PlayerContainerComponent::notifyObjectRemoved(), PlaceCityHallComponent::notifyStructurePlaced(), server::zone::managers::player::PlayerManagerImplementation::offerTeaching(), server::zone::objects::building::BuildingObjectImplementation::payAccessFee(), StructureManager::payMaintenance(), TipCommand::performBankTip(), PlaceGCWBaseComponent::placeStructure(), PlaceCityHallComponent::placeStructure(), StructureManager::placeStructureFromDeed(), server::zone::managers::city::CityManagerImplementation::promptAddMilitiaMember(), server::zone::managers::guild::GuildManagerImplementation::promptAddNewEnemy(), server::zone::managers::city::CityManagerImplementation::promptAdjustTaxes(), StructureManager::promptDeleteAllItems(), server::zone::managers::city::CityManagerImplementation::promptDepositCityTreasury(), server::zone::managers::vendor::VendorManager::promptDestroyVendor(), StructureManager::promptFindLostItems(), server::zone::managers::city::CityManagerImplementation::promptMayoralVote(), StructureManager::promptNameStructure(), server::zone::objects::building::BuildingObjectImplementation::promptPayAccessFee(), StructureManager::promptPayMaintenance(), StructureManager::promptPayUncondemnMaintenance(), server::zone::managers::city::CityManagerImplementation::promptRegisterCity(), server::zone::managers::vendor::VendorManager::promptRenameVendorTo(), server::zone::managers::city::CityManagerImplementation::promptSetTax(), server::zone::managers::player::PlayerManagerImplementation::promptTeachableSkills(), server::zone::managers::city::CityManagerImplementation::promptUnregisterCity(), server::zone::managers::city::CityManagerImplementation::promptWithdrawCityTreasury(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), server::chat::room::ChatRoomImplementation::removePlayer(), server::zone::objects::creature::VehicleObjectImplementation::repairVehicle(), StructureManager::reportStructureStatus(), CombatManager::requestDuel(), CombatManager::requestEndDuel(), DeleteAllItemsSuiCallback::run(), GuildCreateAbbrevResponseSuiCallback::run(), GuildCreateNameResponseSuiCallback::run(), InsuranceMenuSuiCallback::run(), CloningStoreSuiCallback::run(), JunkDealerSellListSuiCallback::run(), InstallMissionTerminalSuiCallback::run(), RecruitSkillTrainerSuiCallback::run(), CustomVehicleSuiCallback::run(), ItemDropTradeCallback::run(), SelectCharacterCallback::run(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::selectConversationOption(), server::zone::managers::guild::GuildManagerImplementation::sendAcceptLotsTo(), server::zone::managers::player::PlayerManagerImplementation::sendActivateCloneRequest(), server::zone::managers::gcw::GCWManagerImplementation::sendBaseDefenseStatus(), server::zone::managers::city::CityManagerImplementation::sendChangeCityName(), server::zone::managers::city::CityManagerImplementation::sendCitizenshipReport(), server::zone::managers::sui::SuiManager::sendConfirmSui(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationStartTo(), server::zone::objects::player::sessions::DestroyStructureSessionImplementation::sendDestroyCode(), server::zone::managers::gcw::GCWManagerImplementation::sendDNASampleMenu(), server::zone::managers::guild::GuildManagerImplementation::sendGuildCreateAbbrevTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildCreateNameTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildDisbandConfirmTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildKickPromptTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildListTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberListTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberOptionsTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSetTitleTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredListTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredOptionsTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsorTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsorVerifyTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildTransferTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildWarStatusTo(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendIngredientsNeededSui(), server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation::sendInitialChoices(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendInitialChoices(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendInitialMessage(), server::zone::managers::sui::SuiManager::sendInputBox(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendInsertManuSui(), server::zone::managers::gcw::GCWManagerImplementation::sendJamUplinkMenu(), server::zone::managers::sui::SuiManager::sendKeypadSui(), server::zone::managers::sui::SuiManager::sendListBox(), server::chat::ChatManagerImplementation::sendMail(), ChatPersistentMessageToServerCallback::sendMailToPlayer(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport(), server::zone::managers::city::CityManagerImplementation::sendManageMilitia(), server::zone::managers::city::CityManagerImplementation::sendMayoralStandings(), server::zone::managers::guild::GuildManagerImplementation::sendMemberPermissionsTo(), server::zone::managers::sui::SuiManager::sendMessageBox(), server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner(), server::zone::managers::gcw::GCWManagerImplementation::sendPowerRegulatorControls(), server::zone::objects::tangible::tool::SurveyToolImplementation::sendRadioactiveWarning(), server::zone::objects::tangible::tool::SurveyToolImplementation::sendRangeSui(), server::zone::managers::vendor::VendorManager::sendRegisterVendorTo(), server::zone::managers::gcw::GCWManagerImplementation::sendRemoveDefenseConfirmation(), server::zone::objects::creature::VehicleObjectImplementation::sendRepairConfirmTo(), server::zone::managers::gcw::GCWManagerImplementation::sendResetVerification(), ResourceSpawner::sendSample(), ResourceSpawner::sendSampleResults(), server::zone::managers::gcw::GCWManagerImplementation::sendSelectDeedToDonate(), server::zone::managers::city::CityManagerImplementation::sendStructureReport(), ResourceSpawner::sendSurvey(), BoardShuttleCommand::sendTicketSelectionBoxTo(), server::zone::managers::gcw::GCWManagerImplementation::sendTurretAttackListTo(), SquadLeaderCommand::shoutCommand(), CombatManager::startCombat(), server::zone::managers::skill::SkillManager::surrenderAllSkills(), server::zone::managers::skill::SkillManager::surrenderSkill(), PlayerZoneComponent::switchZone(), PlayerZoneComponent::teleport(), UnconsentCommand::unconscent(), server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus(), TangibleObjectDeltaMessage3::updateName(), server::zone::managers::player::PlayerManagerImplementation::updatePermissionLevel(), server::zone::managers::player::PlayerManagerImplementation::updatePermissionName(), PlayerZoneComponent::updateZone(), PlayerZoneComponent::updateZoneWithParent(), server::zone::objects::tangible::deed::ResourceDeedImplementation::useObject(), server::zone::managers::gcw::GCWManagerImplementation::verifyUplinkBand(), and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
byte CreatureObject::getPosture ()
Definition at line 2690 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getPosture(), and RPC_GETPOSTURE__.
Referenced by CombatQueueCommand::applyEffect(), CombatManager::calculatePostureModifier(), CreatureObjectMessage3::CreatureObjectMessage3(), ForceShrineMenuComponent::handleObjectMenuSelect(), SurveyGMinigameSuiCallback::run(), SurveyCMinigameSuiCallback::run(), and CreatureObjectDeltaMessage3::updatePosture().
float CreatureObject::getRunAcceleration ()
Definition at line 2969 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getRunAcceleration(), and RPC_GETRUNACCELERATION__.
float CreatureObject::getRunSpeed ()
Definition at line 2917 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getRunSpeed(), and RPC_GETRUNSPEED__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackFirstTest(), CreatureObjectMessage4::CreatureObjectMessage4(), MountCommand::doQueueCommand(), FleeStateComponent::getSpeed(), RetreatStateComponent::getSpeed(), and AttackStateComponent::getSpeed().
unsigned long long CreatureObject::getScreenPlayState (const String & screenPlay)
Definition at line 2349 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getScreenPlayState(), and RPC_GETSCREENPLAYSTATE__STRING_.
Referenced by CompleteQuestCommand::doQueueCommand(), and ClearCompletedQuestCommand::doQueueCommand().
float CreatureObject::getShockWounds ()
Definition at line 2755 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getShockWounds(), and RPC_GETSHOCKWOUNDS__.
Referenced by HealBattleFatigueSelf1Command::canPerformSkill(), HealBattleFatigueSelf2Command::canPerformSkill(), CreatureObjectMessage3::CreatureObjectMessage3(), DamageOverTime::doDiseaseTick(), DamageOverTime::doFireTick(), DiagnoseCommand::doQueueCommand(), HealBattleFatigueSelf2Command::healBattleFatigue(), HealBattleFatigueSelf1Command::healBattleFatigue(), server::zone::objects::player::sessions::EntertainingSessionImplementation::healWounds(), DamageOverTime::initDot(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), server::zone::managers::player::PlayerManagerImplementation::sendBattleFatigueMessage(), and CreatureObjectDeltaMessage3::updateShockWounds().
SkillList * CreatureObject::getSkillList ()
Definition at line 3297 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getSkillList().
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), CreatureObjectMessage1::CreatureObjectMessage1(), ResetJediCommand::doQueueCommand(), server::zone::managers::player::PlayerManagerImplementation::getTeachableSkills(), server::zone::managers::skill::SkillManager::surrenderAllSkills(), server::zone::managers::skill::SkillManager::surrenderSkill(), and server::zone::managers::skill::SkillModManager::verifySkillBoxSkillMods().
int CreatureObject::getSkillMod (const String & skillmod)
Definition at line 3306 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getSkillMod(), and RPC_GETSKILLMOD__STRING_.
Referenced by CombatManager::applyDots(), CombatManager::applyStates(), CombatManager::applyWeaponDots(), server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership(), server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::crafting::CraftingManagerImplementation::calculateAssemblySuccess(), CombatManager::calculateDamage(), CombatManager::calculateDamageRange(), server::zone::managers::crafting::CraftingManagerImplementation::calculateExperimentationFailureRate(), server::zone::managers::crafting::CraftingManagerImplementation::calculateExperimentationSuccess(), server::zone::managers::player::PlayerManagerImplementation::calculatePlayerLevel(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::calculatePower(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::calculatePower(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::calculatePower(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::calculatePower(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::calculatePower(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::calculatePower(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::calculateTime(), CombatManager::calculateWeaponAttackSpeed(), server::zone::objects::creature::CreatureImplementation::canCollectDna(), server::zone::objects::creature::CreatureImplementation::canHarvestMe(), HealEnhanceCommand::canPerformSkill(), HealWoundCommand::canPerformSkill(), HealDamageCommand::canPerformSkill(), MaskscentCommand::checkMaskScent(), server::zone::managers::auction::AuctionManagerImplementation::checkSaleItem(), ImageDesignManager::createHairObject(), CurePackCommand::deactivateConditionTreatment(), HealDamageCommand::deactivateInjuryTreatment(), HealStateCommand::deactivateStateTreatment(), HealEnhanceCommand::deactivateWoundTreatment(), HealWoundCommand::deactivateWoundTreatment(), DotPackCommand::doAreaMedicActionTarget(), RegenerationCommand::doQueueCommand(), SteadyaimCommand::doQueueCommand(), TauntCommand::doQueueCommand(), MaskscentCommand::doQueueCommand(), VolleyFireCommand::doQueueCommand(), ConcealCommand::doQueueCommand(), ForceRun2Command::doQueueCommand(), ForceRun3Command::doQueueCommand(), RescueCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), CenterOfBeingCommand::doQueueCommand(), ForceOfWillCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), TendCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), RetreatCommand::doRetreat(), CombatManager::doTargetCombatAction(), server::zone::objects::creature::CreatureImplementation::fillAttributeList(), CurePackCommand::findCurePack(), HealEnhanceCommand::findEnhancePack(), RevivePlayerCommand::findRevivePack(), HealStateCommand::findStatePack(), HealDamageCommand::findStimPack(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::FindTargetTask(), HealWoundCommand::findWoundPack(), server::zone::managers::minigames::ForageManagerImplementation::finishForaging(), CombatManager::getArmorReduction(), CombatManager::getAttackerAccuracyBonus(), CombatManager::getAttackerAccuracyModifier(), CombatManager::getDamageModifier(), CombatManager::getDefenderDefenseModifier(), CombatManager::getDefenderSecondaryDefenseModifier(), CombatManager::getDefenderToughnessModifier(), CombatManager::getHitChance(), server::zone::objects::tangible::tool::SurveyToolImplementation::getRange(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::getRange(), CombatManager::getSpeedModifier(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::getSuccess(), CampKitMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::handleObjectMenuSelect(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), server::zone::objects::creature::CreatureImplementation::hasSkillToHarvestMe(), server::zone::objects::creature::CreatureImplementation::hasSkillToSampleMe(), server::zone::objects::creature::ai::AiActorImplementation::isConcealed(), server::zone::objects::creature::AiAgentImplementation::isConcealed(), server::zone::objects::creature::ai::AiActorImplementation::isScentMasked(), server::zone::objects::creature::AiAgentImplementation::isScentMasked(), server::zone::managers::mission::MissionManagerImplementation::populateMissionList(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), server::zone::objects::tangible::tool::SurveyToolImplementation::sendRangeSui(), ResourceSpawner::sendSampleResults(), server::zone::managers::skill::SkillManager::surrenderAllSkills(), server::zone::managers::skill::SkillManager::surrenderSkill(), ImageDesignManager::updateColorCustomization(), and ImageDesignManager::updateCustomization().
long long CreatureObject::getSkillModFromBuffs (const String & skillMod)
Definition at line 991 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getSkillModFromBuffs(), and RPC_GETSKILLMODFROMBUFFS__STRING_.
Referenced by server::zone::objects::mission::bountyhunter::events::FindTargetTask::calculateTime(), and server::zone::objects::mission::bountyhunter::events::FindTargetTask::getSuccess().
SkillModList * CreatureObject::getSkillModList ()
Definition at line 3334 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getSkillModList().
Referenced by server::zone::managers::skill::SkillModManager::compareMods(), and CreatureObjectMessage4::CreatureObjectMessage4().
Mutex * CreatureObject::getSkillModMutex ()
Definition at line 4054 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getSkillModMutex().
Referenced by server::zone::managers::skill::SkillModManager::compareMods().
float CreatureObject::getSlopeModPercent ()
Definition at line 3182 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getSlopeModPercent(), and RPC_GETSLOPEMODPERCENT__.
Referenced by CreatureObjectMessage4::CreatureObjectMessage4().
int CreatureObject::getSpecies ()
Definition at line 3247 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getSpecies(), and RPC_GETSPECIES__.
Referenced by EquilibriumCommand::doQueueCommand(), RegenerationCommand::doQueueCommand(), VitalizeCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), server::zone::managers::gcw::GCWManagerImplementation::getGCWDiscount(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), and server::zone::managers::name::NameManager::validateName().
String CreatureObject::getSpeciesName ()
Definition at line 3260 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getSpeciesName(), and RPC_GETSPECIESNAME__.
Referenced by server::zone::managers::skill::SkillManager::fullfillsSkillPrerequisites(), RequestSetStatMigrationDataCommand::getMaxAttribute(), RequestSetStatMigrationDataCommand::getMinAttribute(), ImageDesignManager::getSpeciesGenderString(), RequestSetStatMigrationDataCommand::getTotalAttribPoints(), and server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect().
float CreatureObject::getSpeedMultiplierBase ()
Definition at line 2860 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getSpeedMultiplierBase(), and RPC_GETSPEEDMULTIPLIERBASE__.
Referenced by CreatureObjectMessage4::CreatureObjectMessage4().
float CreatureObject::getSpeedMultiplierMod ()
Definition at line 2873 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getSpeedMultiplierMod(), and RPC_GETSPEEDMULTIPLIERMOD__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackFirstTest(), CreatureObjectMessage4::CreatureObjectMessage4(), and DismountCommand::doQueueCommand().
SpeedMultiplierModChanges * CreatureObject::getSpeedMultiplierModChanges ()
Definition at line 2899 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getSpeedMultiplierModChanges().
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackFirstTest(), MountCommand::doQueueCommand(), and DismountCommand::doQueueCommand().
unsigned long long CreatureObject::getStateBitmask ()
Definition at line 2781 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getStateBitmask(), and RPC_GETSTATEBITMASK__.
Referenced by server::zone::objects::creature::commands::QueueCommand::checkStateMask(), CreatureObjectMessage3::CreatureObjectMessage3(), server::zone::objects::creature::commands::QueueCommand::onStateFail(), and CreatureObjectDeltaMessage3::updateState().
float CreatureObject::getSwimHeight ()
Definition at line 3448 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getSwimHeight(), and RPC_GETSWIMHEIGHT__.
Referenced by DismountCommand::doQueueCommand(), TerrainManager::notifyPositionUpdate(), DataTransformCallback::updatePosition(), and server::zone::managers::player::PlayerManagerImplementation::updateSwimmingState().
unsigned long long CreatureObject::getTargetID ()
Definition at line 3156 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getTargetID(), and RPC_GETTARGETID__.
Referenced by CommandQueueEnqueue::CommandQueueEnqueue(), CreatureObjectMessage6::CreatureObjectMessage6(), GmReviveCommand::doQueueCommand(), StartBandCommand::doQueueCommand(), SnoopCommand::doQueueCommand(), DumpTargetInformationCommand::doQueueCommand(), PaymaintenanceCommand::doQueueCommand(), VentriloquismCommand::doQueueCommand(), KillCommand::doQueueCommand(), StructurestatusCommand::doQueueCommand(), FindObjectCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), server::zone::objects::player::PlayerObjectImplementation::doRecovery(), PlayerInfoCommand::executeCommand(), server::zone::objects::player::sessions::EntertainingSessionImplementation::getInstrument(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::handleObjectMenuSelect(), server::zone::managers::sui::SuiManager::handleStartMusic(), and CreatureObjectDeltaMessage6::updateTarget().
float CreatureObject::getTerrainNegotiation ()
Definition at line 2956 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getTerrainNegotiation(), and RPC_GETTERRAINNEGOTIATION__.
Referenced by CreatureObjectMessage4::CreatureObjectMessage4().
float CreatureObject::getTurnScale ()
Definition at line 2943 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getTurnScale(), and RPC_GETTURNSCALE__.
Referenced by CreatureObjectMessage4::CreatureObjectMessage4().
float CreatureObject::getWalkAcceleration ()
Definition at line 2982 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getWalkAcceleration(), and RPC_GETWALKACCELERATION__.
float CreatureObject::getWalkSpeed ()
Definition at line 2930 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getWalkSpeed(), and RPC_GETWALKSPEED__.
Referenced by CreatureObjectMessage4::CreatureObjectMessage4(), AiCreatureComponent::doAwarenessCheck(), and WanderingStateComponent::getSpeed().
unsigned long long CreatureObject::getWatchToID ()
Definition at line 2768 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getWatchToID(), and RPC_GETWATCHTOID__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::startWatch(), and server::zone::managers::player::PlayerManagerImplementation::stopWatch().
Reference< WeaponObject * > CreatureObject::getWeapon ()
Definition at line 3038 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getWeapon(), and RPC_GETWEAPON__.
Referenced by server::zone::objects::tangible::threat::ThreatMap::addDamage(), VolleyFireCommand::attemptVolleyFire(), server::zone::managers::player::PlayerManagerImplementation::calculatePlayerLevel(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), CreatureRangedAttackCommand::doQueueCommand(), WildShot1Command::doQueueCommand(), AimCommand::doQueueCommand(), UnderHandShotCommand::doQueueCommand(), BurstShot1Command::doQueueCommand(), FanShotCommand::doQueueCommand(), LastDitchCommand::doQueueCommand(), LegShot1Command::doQueueCommand(), FastBlastCommand::doQueueCommand(), LegShot2Command::doQueueCommand(), LegShot3Command::doQueueCommand(), UnarmedKnockdown2Command::doQueueCommand(), RollShotCommand::doQueueCommand(), UnarmedHit3Command::doQueueCommand(), BurstShot2Command::doQueueCommand(), FireAcidCone1Command::doQueueCommand(), LowBlowCommand::doQueueCommand(), UnarmedDizzy1Command::doQueueCommand(), FireAcidCone2Command::doQueueCommand(), UnarmedCombo1Command::doQueueCommand(), ChargeShot1Command::doQueueCommand(), UnarmedBlind1Command::doQueueCommand(), FireAcidSingle1Command::doQueueCommand(), FireAcidSingle2Command::doQueueCommand(), FireLightningCone1Command::doQueueCommand(), SuppressionFire2Command::doQueueCommand(), FireLightningCone2Command::doQueueCommand(), StrafeShot2Command::doQueueCommand(), ActionShot2Command::doQueueCommand(), StoppingShotCommand::doQueueCommand(), Berserk2Command::doQueueCommand(), FireLightningSingle1Command::doQueueCommand(), FireLightningSingle2Command::doQueueCommand(), ChargeShot2Command::doQueueCommand(), FlameCone1Command::doQueueCommand(), FlameCone2Command::doQueueCommand(), ScatterShot1Command::doQueueCommand(), ScatterShot2Command::doQueueCommand(), SniperShotCommand::doQueueCommand(), ConcealShotCommand::doQueueCommand(), FlameSingle1Command::doQueueCommand(), SprayShotCommand::doQueueCommand(), StartleShot1Command::doQueueCommand(), StartleShot2Command::doQueueCommand(), FlameSingle2Command::doQueueCommand(), StrafeShot1Command::doQueueCommand(), SuppressionFire1Command::doQueueCommand(), FlurryShot1Command::doQueueCommand(), TauntCommand::doQueueCommand(), TorsoShotCommand::doQueueCommand(), FlurryShot2Command::doQueueCommand(), UnarmedBodyHit1Command::doQueueCommand(), UnarmedCombo2Command::doQueueCommand(), WarningShotCommand::doQueueCommand(), WildShot2Command::doQueueCommand(), FlushingShot1Command::doQueueCommand(), Melee2hLunge1Command::doQueueCommand(), UnarmedHeadHit1Command::doQueueCommand(), UnarmedHit1Command::doQueueCommand(), UnarmedHit2Command::doQueueCommand(), FlushingShot2Command::doQueueCommand(), UnarmedKnockdown1Command::doQueueCommand(), UnarmedLegHit1Command::doQueueCommand(), ActionShot1Command::doQueueCommand(), ConfusionShotCommand::doQueueCommand(), UnarmedSpinAttack1Command::doQueueCommand(), UnarmedSpinAttack2Command::doQueueCommand(), BleedingShotCommand::doQueueCommand(), FullAutoArea1Command::doQueueCommand(), MultiTargetPistolShotCommand::doQueueCommand(), BodyShot1Command::doQueueCommand(), FullAutoArea2Command::doQueueCommand(), MindShot1Command::doQueueCommand(), MindShot2Command::doQueueCommand(), CripplingShotCommand::doQueueCommand(), FullAutoSingle1Command::doQueueCommand(), OverChargeShot1Command::doQueueCommand(), DisarmingShot1Command::doQueueCommand(), FullAutoSingle2Command::doQueueCommand(), OverChargeShot2Command::doQueueCommand(), PanicShotCommand::doQueueCommand(), HeadShot1Command::doQueueCommand(), PolearmLunge1Command::doQueueCommand(), PistolMeleeDefense1Command::doQueueCommand(), PistolMeleeDefense2Command::doQueueCommand(), BodyShot2Command::doQueueCommand(), DisarmingShot2Command::doQueueCommand(), HeadShot3Command::doQueueCommand(), PointBlankArea1Command::doQueueCommand(), PointBlankSingle1Command::doQueueCommand(), PointBlankSingle2Command::doQueueCommand(), HealthShot1Command::doQueueCommand(), HealthShot2Command::doQueueCommand(), BodyShot3Command::doQueueCommand(), DoubleTapCommand::doQueueCommand(), EyeShotCommand::doQueueCommand(), KipUpShotCommand::doQueueCommand(), KnockdownFireCommand::doQueueCommand(), Warcry1Command::doQueueCommand(), Warcry2Command::doQueueCommand(), UnarmedLunge2Command::doQueueCommand(), Saber1hComboHit2Command::doQueueCommand(), Saber1hComboHit3Command::doQueueCommand(), Melee2hSweep1Command::doQueueCommand(), UnarmedStun1Command::doQueueCommand(), Melee2hLunge2Command::doQueueCommand(), Melee2hMindHit2Command::doQueueCommand(), UnarmedLunge1Command::doQueueCommand(), Melee1hBlindHit1Command::doQueueCommand(), Melee1hBlindHit2Command::doQueueCommand(), Saber1hFlurryCommand::doQueueCommand(), Melee1hBodyHit1Command::doQueueCommand(), Melee2hHit3Command::doQueueCommand(), Melee1hBodyHit3Command::doQueueCommand(), Saber1hHit1Command::doQueueCommand(), Saber1hHit2Command::doQueueCommand(), Saber1hHit3Command::doQueueCommand(), Melee2hHit1Command::doQueueCommand(), Melee2hHit2Command::doQueueCommand(), Melee1hHit1Command::doQueueCommand(), SaberPolearmDervishCommand::doQueueCommand(), Melee2hArea1Command::doQueueCommand(), Melee1hLunge1Command::doQueueCommand(), Melee1hSpinAttack1Command::doQueueCommand(), SaberPolearmHit1Command::doQueueCommand(), SaberPolearmHit2Command::doQueueCommand(), SaberPolearmHit3Command::doQueueCommand(), SaberPolearmLegHit2Command::doQueueCommand(), SaberPolearmLegHit3Command::doQueueCommand(), SaberPolearmSpinAttack1Command::doQueueCommand(), SaberPolearmSpinAttack3Command::doQueueCommand(), SaberSlash2Command::doQueueCommand(), SaberThrow3Command::doQueueCommand(), SaberThrow2Command::doQueueCommand(), SaberThrow1Command::doQueueCommand(), SaberPolearmLegHit1Command::doQueueCommand(), Berserk1Command::doQueueCommand(), Saber1hHeadHit2Command::doQueueCommand(), Saber1hHeadHit3Command::doQueueCommand(), Melee2hSweep2Command::doQueueCommand(), PolearmLunge2Command::doQueueCommand(), Saber1hHeadHit1Command::doQueueCommand(), Saber1hComboHit1Command::doQueueCommand(), PointBlankArea2Command::doQueueCommand(), HeadShot2Command::doQueueCommand(), DiveShotCommand::doQueueCommand(), Intimidate1Command::doQueueCommand(), Intimidate2Command::doQueueCommand(), Melee2hHeadHit2Command::doQueueCommand(), PolearmHit1Command::doQueueCommand(), PolearmArea2Command::doQueueCommand(), Saber2hHit1Command::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), PolearmSpinAttack2Command::doQueueCommand(), PolearmSweep2Command::doQueueCommand(), PolearmSpinAttack1Command::doQueueCommand(), Melee2hSpinAttack1Command::doQueueCommand(), PolearmLegHit3Command::doQueueCommand(), Melee1hBodyHit2Command::doQueueCommand(), Saber2hFrenzyCommand::doQueueCommand(), Saber2hHit3Command::doQueueCommand(), Melee1hHit3Command::doQueueCommand(), Saber2hHit2Command::doQueueCommand(), Melee1hScatterHit1Command::doQueueCommand(), SaberPolearmDervish2Command::doQueueCommand(), Melee2hHeadHit1Command::doQueueCommand(), Saber2hSweep3Command::doQueueCommand(), PolearmStun2Command::doQueueCommand(), Saber1hFlurry2Command::doQueueCommand(), Melee1hHit2Command::doQueueCommand(), Melee1hHealthHit1Command::doQueueCommand(), Melee1hDizzyHit1Command::doQueueCommand(), Saber2hPhantomCommand::doQueueCommand(), Melee2hMindHit1Command::doQueueCommand(), Saber2hBodyHit1Command::doQueueCommand(), Melee1hScatterHit2Command::doQueueCommand(), Saber2hSweep1Command::doQueueCommand(), PolearmHit3Command::doQueueCommand(), PolearmActionHit2Command::doQueueCommand(), TakeCoverCommand::doQueueCommand(), PolearmArea1Command::doQueueCommand(), PolearmSweep1Command::doQueueCommand(), SaberPolearmSpinAttack2Command::doQueueCommand(), PolearmStun1Command::doQueueCommand(), Saber2hBodyHit3Command::doQueueCommand(), Melee1hDizzyHit2Command::doQueueCommand(), Melee1hHealthHit2Command::doQueueCommand(), Melee1hLunge2Command::doQueueCommand(), Melee1hSpinAttack2Command::doQueueCommand(), Melee2hArea3Command::doQueueCommand(), Melee2hArea2Command::doQueueCommand(), Saber2hBodyHit2Command::doQueueCommand(), PolearmLegHit2Command::doQueueCommand(), PolearmLegHit1Command::doQueueCommand(), PolearmHit2Command::doQueueCommand(), Melee2hSpinAttack2Command::doQueueCommand(), Saber2hSweep2Command::doQueueCommand(), Melee2hHeadHit3Command::doQueueCommand(), PolearmActionHit1Command::doQueueCommand(), CenterOfBeingCommand::doQueueCommand(), CombatQueueCommand::getCommandDuration(), CombatManager::getDefaultAttackAnimation(), CombatManager::getDefenderSecondaryDefenseModifier(), CombatManager::getDefenderToughnessModifier(), CombatManager::getHitChance(), AttackStateComponent::getMaxDistance(), and server::zone::objects::creature::commands::QueueCommand::onFail().
unsigned long long CreatureObject::getWeaponID ()
Definition at line 3025 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getWeaponID(), and RPC_GETWEAPONID__.
Referenced by CreatureObjectMessage6::CreatureObjectMessage6(), and CreatureObjectDeltaMessage6::updateWeapon().
WearablesDeltaVector * CreatureObject::getWearablesDeltaVector ()
Definition at line 945 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getWearablesDeltaVector().
Referenced by CombatManager::getActionArmor(), CombatManager::getHealthArmor(), CombatManager::getMindArmor(), and CreatureObjectMessage6::insertEquipmentList().
int CreatureObject::getWounds (int idx)
Definition at line 2598 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::getWounds(), and RPC_GETWOUNDS__INT_.
Referenced by HealActionWoundSelf1Command::canPerformSkill(), HealActionWoundSelf2Command::canPerformSkill(), HealMindWoundSelf1Command::canPerformSkill(), HealMindWoundSelf2Command::canPerformSkill(), HealHealthWoundSelf1Command::canPerformSkill(), HealHealthWoundSelf2Command::canPerformSkill(), HealActionWoundOther1Command::canPerformSkill(), HealMindWoundOther1Command::canPerformSkill(), HealMindWoundOther2Command::canPerformSkill(), HealHealthWoundOther1Command::canPerformSkill(), HealHealthWoundOther2Command::canPerformSkill(), HealActionWoundOther2Command::canPerformSkill(), TotalHealOtherCommand::canPerformSkill(), HealMindWoundOther1Command::checkTarget(), HealMindWoundOther2Command::checkTarget(), HealActionWoundOther1Command::checkTarget(), HealHealthWoundOther1Command::checkTarget(), HealActionWoundOther2Command::checkTarget(), HealHealthWoundOther2Command::checkTarget(), TotalHealOtherCommand::checkTarget(), CreatureObjectMessage3::CreatureObjectMessage3(), DiagnoseCommand::doQueueCommand(), TendCommand::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), TendCommand::findAttribute(), HealWoundCommand::findAttribute(), BoostmoraleCommand::getWounds(), server::zone::objects::player::sessions::EntertainingSessionImplementation::healWounds(), and server::zone::objects::creature::buffs::SpiceBuffImplementation::setDownerAttributes().
DeltaVector< int > * CreatureObject::getWounds ()
Definition at line 2612 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::getWounds().
int CreatureObject::handleObjectMenuSelect (CreatureObject * player, byte selectedID)
Definition at line 3983 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::handleObjectMenuSelect(), and RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_.
bool CreatureObject::hasAttackDelay ()
Definition at line 2184 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::hasAttackDelay(), and RPC_HASATTACKDELAY__.
Referenced by DamageOverTime::doBleedingTick(), CombatManager::doCombatAction(), DamageOverTime::doDiseaseTick(), DamageOverTime::doFireTick(), DamageOverTime::doPoisonTick(), and CombatManager::doTargetCombatAction().
bool CreatureObject::hasBuff (unsigned int buffcrc)
Definition at line 1063 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::hasBuff(), and RPC_HASBUFF__INT_.
Referenced by server::zone::objects::group::GroupObjectImplementation::addGroupModifiers(), server::zone::managers::crafting::CraftingManagerImplementation::calculateAssemblySuccess(), server::zone::managers::crafting::CraftingManagerImplementation::calculateExperimentationSuccess(), BurstRunCommand::checkBurstRun(), RetreatCommand::checkRetreat(), CurePackCommand::deactivateConditionTreatment(), HealDamageCommand::deactivateInjuryTreatment(), HealStateCommand::deactivateStateTreatment(), HealWoundCommand::deactivateWoundTreatment(), HealEnhanceCommand::deactivateWoundTreatment(), server::zone::managers::player::PlayerManagerImplementation::doEnhanceCharacter(), MaskscentCommand::doQueueCommand(), ForceResistBleedingCommand::doQueueCommand(), ForceResistDiseaseCommand::doQueueCommand(), ForceResistPoisonCommand::doQueueCommand(), ForceResistStatesCommand::doQueueCommand(), AvoidIncapacitationCommand::doQueueCommand(), ForceSpeed2Command::doQueueCommand(), ForceArmor2Command::doQueueCommand(), ForceShield2Command::doQueueCommand(), ForceFeedback1Command::doQueueCommand(), ForceFeedback2Command::doQueueCommand(), ForceRun1Command::doQueueCommand(), ForceAbsorb1Command::doQueueCommand(), ForceRun2Command::doQueueCommand(), ForceRun3Command::doQueueCommand(), ForceShield1Command::doQueueCommand(), ForceAbsorb2Command::doQueueCommand(), ForceSpeed1Command::doQueueCommand(), ForceArmor1Command::doQueueCommand(), MountCommand::doQueueCommand(), DismountCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), CenterOfBeingCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), RetreatCommand::doRetreat(), SkillBuffObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::managers::player::PlayerManagerImplementation::healEnhance(), server::zone::objects::group::GroupObjectImplementation::removeGroupModifiers(), and server::zone::objects::creature::buffs::BuffImplementation::sendDestroyTo().
bool CreatureObject::hasDamage (int attribute)
Definition at line 520 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::hasDamage(), and RPC_HASDAMAGE__INT_.
Referenced by HealActionSelf1Command::canPerformSkill(), HealActionSelf2Command::canPerformSkill(), HealAllSelf2Command::canPerformSkill(), HealHealthSelf1Command::canPerformSkill(), HealAllSelf1Command::canPerformSkill(), HealHealthSelf2Command::canPerformSkill(), HealMindSelf1Command::canPerformSkill(), HealMindSelf2Command::canPerformSkill(), HealAllOther1Command::canPerformSkill(), HealAllOther2Command::canPerformSkill(), HealDamageCommand::canPerformSkill(), TotalHealOtherCommand::canPerformSkill(), HealAllOther2Command::checkTarget(), HealAllOther1Command::checkTarget(), TotalHealOtherCommand::checkTarget(), HealDamageCommand::checkTarget(), HealMindCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), and TotalHealSelfCommand::doQueueCommand().
bool CreatureObject::hasSkill (const String & skill)
Definition at line 3320 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::hasSkill(), and RPC_HASSKILL__STRING_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer(), server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::zone::managers::skill::SkillManager::awardSkill(), PlayerContainerComponent::canAddObject(), server::zone::objects::creature::CreatureImplementation::canCollectDna(), server::zone::objects::creature::CreatureImplementation::canHarvestMe(), server::zone::managers::skill::SkillManager::canLearnSkill(), server::zone::managers::player::PlayerManagerImplementation::disseminateExperience(), SetCurrentSkillTitleCommand::doQueueCommand(), AreatrackCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), InstallMissionTerminalCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), StructureTerminalMenuComponent::fillObjectMenuResponse(), LootSchematicMenuComponent::fillObjectMenuResponse(), LairMenuComponent::fillObjectMenuResponse(), TangibleObjectMenuComponent::fillObjectMenuResponse(), VendorMenuComponent::fillObjectMenuResponse(), server::zone::objects::tangible::ContainerImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::fillObjectMenuResponse(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveItems(), server::zone::managers::skill::SkillManager::fullfillsSkillPrerequisites(), server::zone::objects::group::GroupObjectImplementation::getGroupHarvestModifier(), server::zone::objects::creature::conversation::screenhandlers::TrainerNextSkillsScreenHandler::getNextSkillsList(), ImageDesignManager::getSkillLevel(), server::zone::objects::player::sessions::SlicingSessionImplementation::getSlicingSkill(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainableSkillsScreenHandler::getTrainableSkillsList(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), server::zone::managers::mission::MissionManagerImplementation::handleMissionListRequest(), StructureTerminalMenuComponent::handleObjectMenuSelect(), LootSchematicMenuComponent::handleObjectMenuSelect(), LairMenuComponent::handleObjectMenuSelect(), TangibleObjectMenuComponent::handleObjectMenuSelect(), VendorMenuComponent::handleObjectMenuSelect(), WeaponObjectMenuComponent::handleObjectMenuSelect(), PowerRegulatorMenuComponent::handleObjectMenuSelect(), OverrideTerminalMenuComponent::handleObjectMenuSelect(), SecurityTerminalMenuComponent::handleObjectMenuSelect(), UplinkTerminalMenuComponent::handleObjectMenuSelect(), ForceShrineMenuComponent::handleObjectMenuSelect(), HQMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::ContainerImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::handleObjectMenuSelect(), server::zone::objects::creature::conversation::screenhandlers::TrainerInfoScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::handleScreen(), server::zone::objects::creature::CreatureImplementation::hasSkillToHarvestMe(), server::zone::objects::creature::CreatureImplementation::hasSkillToSampleMe(), BountyHunterDroidMenuComponent::playerCanUseProbot(), BountyHunterDroidMenuComponent::playerCanUseSeeker(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationStartTo(), server::zone::managers::gcw::GCWManagerImplementation::sendDNASampleMenu(), server::zone::managers::minigames::FishingManagerImplementation::success(), server::zone::managers::skill::SkillManager::surrenderSkill(), and server::zone::managers::city::CityManagerImplementation::updateCityVoting().
bool CreatureObject::hasSpice ()
Definition at line 2219 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::hasSpice(), and RPC_HASSPICE__.
Referenced by server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect().
bool CreatureObject::hasState (unsigned long long state)
Definition at line 2794 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::hasState(), and RPC_HASSTATE__LONG_.
Referenced by CombatManager::attemptPeace(), server::zone::objects::creature::CreatureImplementation::canMilkMe(), HealStatesSelfCommand::canPerformSkill(), HealStatesOtherCommand::canPerformSkill(), TotalHealOtherCommand::canPerformSkill(), HealStatesOtherCommand::checkTarget(), TotalHealOtherCommand::checkTarget(), server::zone::objects::creature::AiAgentImplementation::doAttack(), SetPlayerStateCommand::doQueueCommand(), HealStatesSelfCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), AttackStateComponent::doRecovery(), server::zone::objects::creature::ai::AiActorImplementation::isConcealed(), server::zone::objects::creature::AiAgentImplementation::isConcealed(), server::zone::objects::creature::ai::AiActorImplementation::isScentMasked(), server::zone::objects::creature::AiAgentImplementation::isScentMasked(), server::zone::managers::player::PlayerManagerImplementation::notifyObserverEvent(), TerrainManager::notifyPositionUpdate(), AiStateComponent::validateStateAttack(), and server::zone::objects::creature::AiAgentImplementation::validateStateAttack().
bool CreatureObject::hasStates ()
Definition at line 2808 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::hasStates(), and RPC_HASSTATES__.
int CreatureObject::healDamage (TangibleObject * healer, int damageType, int damage, bool notifyClient = true, bool notifyObservers = true)
Heals damage
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
unused for now
Definition at line 534 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::healDamage(), and RPC_HEALDAMAGE__TANGIBLEOBJECT_INT_INT_BOOL_BOOL_.
Referenced by HealDamageCommand::doAreaMedicActionTarget(), EquilibriumCommand::doQueueCommand(), HealAllSelf1Command::doQueueCommand(), HealAllSelf2Command::doQueueCommand(), HealActionSelf1Command::doQueueCommand(), HealActionSelf2Command::doQueueCommand(), HealHealthSelf1Command::doQueueCommand(), HealHealthSelf2Command::doQueueCommand(), HealMindSelf2Command::doQueueCommand(), HealMindSelf1Command::doQueueCommand(), HealMindCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::managers::player::PlayerManagerImplementation::removeEncumbrancies(), and GmReviveCommand::revivePlayer().
bool CreatureObject::healDot (unsigned long long dotType, int reduction)
Definition at line 1026 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::healDot(), and RPC_HEALDOT__LONG_INT_.
Referenced by CurePackCommand::doAreaMedicActionTarget(), FirstAidCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), and TerrainManager::notifyPositionUpdate().
int CreatureObject::healWound (TangibleObject * healer, int damageType, int damage, bool notifyClient = true, bool notifyObservers = true)
Heals wound
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
unused for now
Definition at line 552 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::healWound(), and RPC_HEALWOUND__TANGIBLEOBJECT_INT_INT_BOOL_BOOL_.
Referenced by HealActionWoundSelf1Command::doQueueCommand(), HealActionWoundSelf2Command::doQueueCommand(), HealHealthWoundSelf2Command::doQueueCommand(), HealMindWoundSelf1Command::doQueueCommand(), HealHealthWoundSelf1Command::doQueueCommand(), HealMindWoundSelf2Command::doQueueCommand(), TendCommand::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), and TotalHealOtherCommand::doQueueCommand().
int CreatureObject::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, bool notifyClient = true)
Inflicts damage into the object
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
unused for now
Definition at line 483 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::inflictDamage(), and RPC_INFLICTDAMAGE__TANGIBLEOBJECT_INT_FLOAT_BOOL_BOOL_.
Referenced by DotPackCommand::applyCost(), CombatManager::applyDamage(), server::zone::managers::player::PlayerManagerImplementation::applyEncumbrancies(), server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage(), CombatManager::applySpecialAttackCost(), DamageOverTime::doBleedingTick(), DamageOverTime::doFireTick(), DamageOverTime::doPoisonTick(), DistractCommand::doQueueCommand(), EquilibriumCommand::doQueueCommand(), VentriloquismCommand::doQueueCommand(), Berserk2Command::doQueueCommand(), FirejetCommand::doQueueCommand(), ColorlightsCommand::doQueueCommand(), SmokebombCommand::doQueueCommand(), DazzleCommand::doQueueCommand(), SpotlightCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), Berserk1Command::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), TakeCoverCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), CombatManager::doTargetCombatAction(), CombatManager::getArmorReduction(), SquadLeaderCommand::inflictHAM(), ResourceSpawner::sendSample(), ResourceSpawner::sendSurvey(), and server::zone::managers::minigames::ForageManagerImplementation::startForaging().
int CreatureObject::inflictDamage (TangibleObject * attacker, int damageType, float damage, bool destroy, const String & xp, bool notifyClient = true)
Definition at line 501 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::inflictDamage(), and RPC_INFLICTDAMAGE__TANGIBLEOBJECT_INT_FLOAT_BOOL_STRING_BOOL_.
void CreatureObject::initializeMembers ()
Definition at line 65 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::initializeMembers(), and RPC_INITIALIZEMEMBERS__.
void CreatureObject::initializeTransientMembers ()
Initializes the transient members of SceneObject, must call the inherited object method first.
Precondition
{transient members are not initialized }
Postcondition
{ transient members are initialized }
Definition at line 100 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
bool CreatureObject::isAggressiveTo (CreatureObject * object)
Evaluates if this creature is aggresive to the object
Precondition
{ }
Postcondition
{ }
Returns
returns true if its aggressive
Definition at line 1705 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isAggressiveTo(), and RPC_ISAGGRESSIVETO__CREATUREOBJECT_.
bool CreatureObject::isAiActor ()
Definition at line 3890 of file CreatureObject.cpp.
References _getImplementationForRead(), server::zone::objects::creature::CreatureObjectImplementation::isAiActor(), and RPC_ISAIACTOR__.
Referenced by server::zone::objects::creature::ai::AiActorImplementation::isAttackableBy().
bool CreatureObject::isAiming ()
Definition at line 3812 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isAiming(), and RPC_ISAIMING__.
bool CreatureObject::isAttackableBy (CreatureObject * object)
Evaluates if this object can be attacket by the passed creature object
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns true if the creature object can attack this
Definition at line 1591 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy(), and RPC_ISATTACKABLEBY__CREATUREOBJECT_.
Referenced by DotPackCommand::checkTarget(), server::zone::objects::creature::AiAgentImplementation::doAttack(), SniperShotCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), AttackStateComponent::doRecovery(), CombatManager::doTargetCombatAction(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), server::zone::objects::tangible::threat::ThreatMap::getHighestThreatCreature(), DotPackCommand::handleArea(), CurePackCommand::handleArea(), and HealDamageCommand::handleArea().
bool CreatureObject::isAttackableBy (TangibleObject * attacker)
Definition at line 1605 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy(), and RPC_ISATTACKABLEBY__TANGIBLEOBJECT_.
bool CreatureObject::isBerserked ()
Definition at line 3604 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isBerserked(), and RPC_ISBERSERKED__.
Referenced by CombatManager::doCombatAction().
bool CreatureObject::isBleeding ()
Definition at line 3734 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isBleeding(), and RPC_ISBLEEDING__.
Referenced by FirstAidCommand::canPerformSkill(), StopBleedingCommand::canPerformSkill(), TotalHealOtherCommand::canPerformSkill(), StopBleedingCommand::checkTarget(), and TotalHealOtherCommand::checkTarget().
bool CreatureObject::isBlinded ()
Definition at line 3630 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isBlinded(), and RPC_ISBLINDED__.
bool CreatureObject::isCreature ()
Definition at line 3864 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isCreature(), and RPC_ISCREATURE__.
Referenced by CombatManager::broadcastCombatAction(), HarvestCorpseCommand::doQueueCommand(), CombatManager::getHitChance(), and server::zone::managers::player::PlayerManagerImplementation::shouldRescheduleCorpseDestruction().
bool CreatureObject::isCreatureObject ()
Definition at line 3357 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isCreatureObject(), and RPC_ISCREATUREOBJECT__.
Referenced by server::zone::managers::director::DirectorManager::updateCellPermission(), and server::zone::managers::director::DirectorManager::updateCellPermissionGroup().
bool CreatureObject::isDancing ()
Definition at line 1231 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isDancing(), and RPC_ISDANCING__.
Referenced by DistractCommand::doQueueCommand(), SmokebombCommand::doQueueCommand(), BandFlourishCommand::doQueueCommand(), PlayerObjectMenuComponent::fillObjectMenuResponse(), server::zone::managers::player::PlayerManagerImplementation::startListen(), and server::zone::managers::player::PlayerManagerImplementation::startWatch().
bool CreatureObject::isDead ()
Definition at line 3474 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isDead(), and RPC_ISDEAD__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::activateForceRegen(), CombatQueueCommand::applyEffect(), CombatManager::applyStates(), CombatManager::attemptPeace(), server::zone::objects::creature::CreatureImplementation::canCollectDna(), server::zone::objects::creature::CreatureImplementation::canHarvestMe(), server::zone::objects::creature::CreatureImplementation::canMilkMe(), RevivePlayerCommand::canPerformSkill(), HealEnhanceCommand::canPerformSkill(), HealDamageCommand::checkTarget(), server::zone::managers::creature::LairObserverImplementation::doAggro(), server::zone::objects::creature::AiAgentImplementation::doAttack(), AiCreatureComponent::doAwarenessCheck(), CombatQueueCommand::doCombatAction(), SampleDNACommand::doQueueCommand(), SniperShotCommand::doQueueCommand(), ConcealCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), ActivateCloneCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), AttackStateComponent::doRecovery(), server::zone::objects::player::PlayerObjectImplementation::doRecovery(), DragIncapacitatedPlayerCommand::drag(), PowerRegulatorMenuComponent::fillObjectMenuResponse(), TurretControlMenuComponent::fillObjectMenuResponse(), OverrideTerminalMenuComponent::fillObjectMenuResponse(), MinefieldMenuComponent::fillObjectMenuResponse(), SecurityTerminalMenuComponent::fillObjectMenuResponse(), UplinkTerminalMenuComponent::fillObjectMenuResponse(), HQMenuComponent::fillObjectMenuResponse(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), server::zone::objects::tangible::threat::ThreatMap::getHighestThreatCreature(), SkillBuffObjectMenuComponent::handleObjectMenuSelect(), PowerRegulatorMenuComponent::handleObjectMenuSelect(), OverrideTerminalMenuComponent::handleObjectMenuSelect(), UplinkTerminalMenuComponent::handleObjectMenuSelect(), SecurityTerminalMenuComponent::handleObjectMenuSelect(), HQMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::managers::creature::LairObserverImplementation::healLair(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::invalidPosture(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), AiNPCComponent::notifyPositionUpdate(), AiCreatureComponent::notifyPositionUpdate(), server::zone::managers::player::PlayerManagerImplementation::promptTeachableSkills(), JamUplinkSuiCallback::run(), OverrideTerminalSuiCallback::run(), PowerRegulatorSuiCallback::run(), and CloningRequestSuiCallback::run().
bool CreatureObject::isDiseased ()
Definition at line 3708 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isDiseased(), and RPC_ISDISEASED__.
Referenced by ForceCureDiseaseCommand::canPerformSkill(), CurePackCommand::canPerformSkill(), TotalHealOtherCommand::canPerformSkill(), ForceCureDiseaseCommand::checkTarget(), TotalHealOtherCommand::checkTarget(), and CurePackCommand::checkTarget().
bool CreatureObject::isDizzied ()
Definition at line 3591 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isDizzied(), and RPC_ISDIZZIED__.
Referenced by FormupCommand::doFormUp(), KipUpShotCommand::doQueueCommand(), RollShotCommand::doQueueCommand(), DiveShotCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), ProneCommand::doQueueCommand(), StandCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), KneelCommand::doQueueCommand(), and TumbleToKneelingCommand::doQueueCommand().
bool CreatureObject::isEntertaining ()
Definition at line 1270 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isEntertaining(), and RPC_ISENTERTAINING__.
Referenced by ColorlightsCommand::doQueueCommand(), DazzleCommand::doQueueCommand(), SpotlightCommand::doQueueCommand(), VentriloquismCommand::doQueueCommand(), SmokebombCommand::doQueueCommand(), DistractCommand::doQueueCommand(), FirejetCommand::doQueueCommand(), BandFlourishCommand::doQueueCommand(), CombatManager::doTargetCombatAction(), and PlayerContainerComponent::notifyObjectInserted().
bool CreatureObject::isFrozen ()
Definition at line 3695 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isFrozen(), and RPC_ISFROZEN__.
Referenced by DataTransformCallback::updatePosition(), and DataTransformWithParentCallback::updatePosition().
bool CreatureObject::isGrouped ()
Definition at line 2545 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isGrouped(), and RPC_ISGROUPED__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::canGroupMemberHarvestCorpse(), server::zone::objects::creature::CreatureImplementation::canHarvestMe(), RescueCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), server::zone::objects::tangible::threat::ThreatMap::getHighestDamageGroupLeader(), server::zone::managers::mission::MissionManagerImplementation::getRandomLairSpawn(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), GroupManager::inviteToGroup(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), and server::zone::managers::director::DirectorManager::updateCellPermissionGroup().
bool CreatureObject::isHealableBy (CreatureObject * object)
Definition at line 1619 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isHealableBy(), and RPC_ISHEALABLEBY__CREATUREOBJECT_.
Referenced by RevivePlayerCommand::canPerformSkill(), HealEnhanceCommand::canPerformSkill(), HealStateCommand::canPerformSkill(), HealWoundCommand::canPerformSkill(), HealDamageCommand::canPerformSkill(), CurePackCommand::canPerformSkill(), CurePackCommand::checkTarget(), TransferForceCommand::doQueueCommand(), DiagnoseCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), DragIncapacitatedPlayerCommand::doQueueCommand(), and TotalHealOtherCommand::doQueueCommand().
bool CreatureObject::isImmobilized ()
Definition at line 3669 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isImmobilized(), and RPC_ISIMMOBILIZED__.
bool CreatureObject::isInBountyMission (CreatureObject * bountyHunter, CreatureObject * target)
Evaluates if the bounty hunter has a mission with the target.
Parameters
bountyHunter the bounty hunter.
target the target.
Returns
true if bounty hunter has a mission with the target.
Definition at line 1633 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isInBountyMission(), and RPC_ISINBOUNTYMISSION__CREATUREOBJECT_CREATUREOBJECT_.
bool CreatureObject::isIncapacitated ()
Definition at line 3461 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isIncapacitated(), and RPC_ISINCAPACITATED__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::activateForceRegen(), CombatQueueCommand::applyEffect(), server::zone::objects::creature::CreatureImplementation::canCollectDna(), server::zone::objects::creature::CreatureImplementation::canHarvestMe(), server::zone::objects::creature::CreatureImplementation::canMilkMe(), server::zone::objects::creature::AiAgentImplementation::doAttack(), SniperShotCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), ForceOfWillCommand::doQueueCommand(), AttackStateComponent::doRecovery(), server::zone::objects::player::PlayerObjectImplementation::doRecovery(), DragIncapacitatedPlayerCommand::drag(), PowerRegulatorMenuComponent::fillObjectMenuResponse(), TurretControlMenuComponent::fillObjectMenuResponse(), OverrideTerminalMenuComponent::fillObjectMenuResponse(), MinefieldMenuComponent::fillObjectMenuResponse(), UplinkTerminalMenuComponent::fillObjectMenuResponse(), SecurityTerminalMenuComponent::fillObjectMenuResponse(), HQMenuComponent::fillObjectMenuResponse(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), server::zone::objects::tangible::threat::ThreatMap::getHighestThreatCreature(), CollisionManager::getRayOriginPoint(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAbort(), SkillBuffObjectMenuComponent::handleObjectMenuSelect(), PowerRegulatorMenuComponent::handleObjectMenuSelect(), OverrideTerminalMenuComponent::handleObjectMenuSelect(), SecurityTerminalMenuComponent::handleObjectMenuSelect(), UplinkTerminalMenuComponent::handleObjectMenuSelect(), HQMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::invalidPosture(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), JamUplinkSuiCallback::run(), PowerRegulatorSuiCallback::run(), and OverrideTerminalSuiCallback::run().
bool CreatureObject::isInCombat ()
Definition at line 3578 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isInCombat(), and RPC_ISINCOMBAT__.
Referenced by server::zone::objects::creature::CreatureImplementation::canCollectDna(), server::zone::objects::creature::CreatureImplementation::canHarvestMe(), server::zone::objects::creature::CreatureImplementation::canMilkMe(), HealEnhanceCommand::canPerformSkill(), HealWoundCommand::canPerformSkill(), MaskscentCommand::checkMaskScent(), Berserk2Command::doQueueCommand(), SampleCommand::doQueueCommand(), Berserk1Command::doQueueCommand(), TakeCoverCommand::doQueueCommand(), SitServerCommand::doQueueCommand(), LogoutServerCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), server::zone::objects::player::PlayerObjectImplementation::doRecovery(), server::zone::managers::minigames::ForageManagerImplementation::finishForaging(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAbort(), CampKitMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::deed::pet::PetDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::invalidPosture(), AiNPCComponent::notifyPositionUpdate(), AiCreatureComponent::notifyPositionUpdate(), and server::zone::managers::gcw::GCWManagerImplementation::sendTurretAttackListTo().
bool CreatureObject::isInCover ()
Definition at line 3825 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isInCover(), and RPC_ISINCOVER__.
bool CreatureObject::isInformantCreature ()
Definition at line 3903 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isInformantCreature(), and RPC_ISINFORMANTCREATURE__.
bool CreatureObject::isInGuild ()
Definition at line 3077 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isInGuild(), and RPC_ISINGUILD__.
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::managers::guild::GuildManagerImplementation::createGuild(), GuildremoveCommand::doQueueCommand(), GuildstatusCommand::doQueueCommand(), server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation::fillObjectMenuResponse(), GuildCreateAbbrevResponseSuiCallback::run(), GuildCreateNameResponseSuiCallback::run(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildCreateNameTo().
bool CreatureObject::isIntimidated ()
Definition at line 3643 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isIntimidated(), and RPC_ISINTIMIDATED__.
Referenced by CombatManager::applyStates(), and CombatManager::getDefenderSecondaryDefenseModifier().
bool CreatureObject::isInvisible ()
Definition at line 4027 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isInvisible(), and RPC_ISINVISIBLE__.
Referenced by PlayerZoneComponent::notifyInsert(), ZoneComponent::updateZone(), and ZoneComponent::updateZoneWithParent().
bool CreatureObject::isKneeling ()
Definition at line 3500 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isKneeling(), and RPC_ISKNEELING__.
Referenced by CombatManager::calculatePostureModifier(), CombatManager::calculateTargetPostureModifier(), CombatQueueCommand::doCombatAction(), and CollisionManager::getRayOriginPoint().
bool CreatureObject::isKnockedDown ()
Definition at line 3487 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isKnockedDown(), and RPC_ISKNOCKEDDOWN__.
Referenced by CombatQueueCommand::applyEffect(), server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage(), CombatManager::calculateDamage(), CollisionManager::getRayOriginPoint(), AiStateComponent::validateStateAttack(), and server::zone::objects::creature::AiAgentImplementation::validateStateAttack().
bool CreatureObject::isListening ()
Definition at line 1897 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isListening(), and RPC_ISLISTENING__.
Referenced by StoplisteningCommand::doQueueCommand(), ListenCommand::doQueueCommand(), PlayerObjectMenuComponent::fillObjectMenuResponse(), and server::zone::managers::player::PlayerManagerImplementation::startListen().
bool CreatureObject::isMeditating ()
Definition at line 3799 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isMeditating(), and RPC_ISMEDITATING__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::activateForceRegen(), RevivePlayerCommand::canPerformSkill(), HealEnhanceCommand::canPerformSkill(), HealStateCommand::canPerformSkill(), HealWoundCommand::canPerformSkill(), HealDamageCommand::canPerformSkill(), CurePackCommand::canPerformSkill(), ForceMeditateCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), and server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::invalidPosture().
bool CreatureObject::isMounted ()
Definition at line 3760 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isMounted(), and RPC_ISMOUNTED__.
Referenced by CombatQueueCommand::applyEffect(), server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage(), RevivePlayerCommand::canPerformSkill(), HealEnhanceCommand::canPerformSkill(), HealStateCommand::canPerformSkill(), HealWoundCommand::canPerformSkill(), HealDamageCommand::canPerformSkill(), CurePackCommand::canPerformSkill(), HealMindCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), FireworkMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::invalidPosture(), server::zone::managers::creature::CreatureManagerImplementation::milk(), and server::zone::managers::creature::CreatureManagerImplementation::sample().
bool CreatureObject::isNextActionPast ()
Definition at line 3370 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isNextActionPast(), and RPC_ISNEXTACTIONPAST__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::doRecovery().
bool CreatureObject::isNonPlayerCreatureObject ()
Definition at line 3851 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isNonPlayerCreatureObject(), and RPC_ISNONPLAYERCREATUREOBJECT__.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction(), server::zone::managers::creature::CreatureManagerImplementation::sample(), and server::zone::managers::player::PlayerManagerImplementation::shouldRescheduleCorpseDestruction().
bool CreatureObject::isOnFire ()
Definition at line 3747 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isOnFire(), and RPC_ISONFIRE__.
Referenced by CurePackCommand::canPerformSkill(), and CurePackCommand::checkTarget().
bool CreatureObject::isOnline ()
Definition at line 1806 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isOnline(), and RPC_ISONLINE__.
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), GroupManager::makeLeader(), server::zone::managers::guild::GuildManagerImplementation::setMemberTitle(), and server::zone::managers::player::PlayerManagerImplementation::updatePermissionName().
bool CreatureObject::isPeaced ()
Definition at line 3786 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isPeaced(), and RPC_ISPEACED__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::doRecovery().
bool CreatureObject::isPlayerCreature ()
Definition at line 3877 of file CreatureObject.cpp.
References _getImplementationForRead(), server::zone::objects::creature::CreatureObjectImplementation::isPlayerCreature(), and RPC_ISPLAYERCREATURE__.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand(), server::zone::objects::tangible::threat::ThreatMatrix::add(), server::zone::objects::group::GroupObjectImplementation::addGroupModifiers(), server::zone::managers::player::creation::PlayerCreationManager::addStartingItemsInto(), server::zone::managers::player::creation::PlayerCreationManager::addStartingWeaponsInto(), CombatManager::applyDamage(), server::zone::objects::player::sessions::EntertainingSessionImplementation::awardEntertainerExperience(), FactionManager::awardPvpFactionPoints(), DotPackCommand::awardXp(), HealStateCommand::awardXp(), HealWoundCommand::awardXp(), TendCommand::awardXp(), CurePackCommand::awardXp(), RevivePlayerCommand::awardXp(), HealEnhanceCommand::awardXp(), HealDamageCommand::awardXp(), CombatManager::calculateDamage(), CombatManager::calculatePostureModifier(), PlayerContainerComponent::canAddObject(), RevivePlayerCommand::canPerformSkill(), server::zone::managers::gcw::GCWManagerImplementation::canPlaceMoreBases(), server::zone::managers::gcw::GCWManagerImplementation::canStartSlice(), ForceCureDiseaseCommand::checkTarget(), ForceCurePoisonCommand::checkTarget(), StopBleedingCommand::checkTarget(), HealStatesOtherCommand::checkTarget(), HealAllOther1Command::checkTarget(), HealAllOther2Command::checkTarget(), HealActionWoundOther2Command::checkTarget(), HealActionWoundOther1Command::checkTarget(), HealHealthWoundOther1Command::checkTarget(), HealHealthWoundOther2Command::checkTarget(), HealMindWoundOther1Command::checkTarget(), HealMindWoundOther2Command::checkTarget(), TotalHealOtherCommand::checkTarget(), CurePackCommand::checkTarget(), server::zone::objects::group::GroupObjectImplementation::disband(), server::zone::managers::player::PlayerManagerImplementation::disseminateExperience(), HealDamageCommand::doAreaMedicActionTarget(), BandFlourishCommand::doBandFlourish(), CombatQueueCommand::doCombatAction(), DuelCommand::doQueueCommand(), DumpTargetInformationCommand::doQueueCommand(), EndDuelCommand::doQueueCommand(), EquilibriumCommand::doQueueCommand(), FactoryCrateSplitCommand::doQueueCommand(), NpcConversationSelectCommand::doQueueCommand(), NpcConversationStartCommand::doQueueCommand(), NpcConversationStopCommand::doQueueCommand(), FindMyTrainerCommand::doQueueCommand(), RallyCommand::doQueueCommand(), RegenerationCommand::doQueueCommand(), Berserk2Command::doQueueCommand(), RemoveFriendCommand::doQueueCommand(), RemoveIgnoreCommand::doQueueCommand(), RequestWaypointAtPositionCommand::doQueueCommand(), FormupCommand::doQueueCommand(), SampleCommand::doQueueCommand(), SampleDNACommand::doQueueCommand(), ServerSysGroupCommand::doQueueCommand(), SetSpeedCommand::doQueueCommand(), SetSpokenLanguageCommand::doQueueCommand(), SetWaypointNameCommand::doQueueCommand(), SniperShotCommand::doQueueCommand(), SpatialChatInternalCommand::doQueueCommand(), SetBiographyCommand::doQueueCommand(), SteadyaimCommand::doQueueCommand(), SynchronizedUiStopListeningCommand::doQueueCommand(), VentriloquismCommand::doQueueCommand(), VitalizeCommand::doQueueCommand(), DenyServiceCommand::doQueueCommand(), Intimidate1Command::doQueueCommand(), Intimidate2Command::doQueueCommand(), InvulnerableCommand::doQueueCommand(), LfgCommand::doQueueCommand(), ListGuildsCommand::doQueueCommand(), MedicalForageCommand::doQueueCommand(), NewbiehelperCommand::doQueueCommand(), AnonCommand::doQueueCommand(), AreatrackCommand::doQueueCommand(), OpenContainerCommand::doQueueCommand(), Berserk1Command::doQueueCommand(), ProneCommand::doQueueCommand(), ForageCommand::doQueueCommand(), RequestBiographyCommand::doQueueCommand(), RequestDraftSlotsBatchCommand::doQueueCommand(), RequestResourceWeightsBatchCommand::doQueueCommand(), ResourceContainerSplitCommand::doQueueCommand(), ResourceContainerTransferCommand::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), SynchronizedUiListenCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), FreezePlayerCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), GmCreateSpecificResourceCommand::doQueueCommand(), GetStationNameCommand::doQueueCommand(), SetPerformanceBuffTargetCommand::doQueueCommand(), GuildremoveCommand::doQueueCommand(), SurveyCommand::doQueueCommand(), ToggleAwayFromKeyBoardCommand::doQueueCommand(), ToggleDisplayingFactionRankCommand::doQueueCommand(), UnfreezePlayerCommand::doQueueCommand(), VolleyFireCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), RolePlayCommand::doQueueCommand(), MeditateCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), FindObjectCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), RequestCharacterSheetInfoCommand::doQueueCommand(), BoostmoraleCommand::doQueueCommand(), RescueCommand::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), GetAttributesBatchCommand::doQueueCommand(), CancelCraftingSessionCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), HaveconsentCommand::doQueueCommand(), TakeCoverCommand::doQueueCommand(), CloseContainerCommand::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), ActivateCloneCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), ServerDestroyObjectCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), FishCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), SetFactionCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), GuildstatusCommand::doQueueCommand(), CreateVendorCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), DumpZoneInformationCommand::doQueueCommand(), CenterOfBeingCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), FindCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), BetCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), RequestSurveyCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), ForceOfWillCommand::doQueueCommand(), RetreatCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), StartDanceCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DragIncapacitatedPlayerCommand::doQueueCommand(), BandFlourishCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), MarketCommand::executeCommand(), PlayerManagerCommand::executeCommand(), WeatherCommand::executeCommand(), CityReportCommand::executeCommand(), VendorInfoCommand::executeCommand(), server::zone::managers::city::CityManagerImplementation::fixMayor(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), CombatManager::getArmorReduction(), CombatManager::getDefenderDefenseModifier(), server::zone::objects::tangible::threat::ThreatMap::getHighestDamagePlayer(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetKilled(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetReceivesDamage(), ThrowGrenadeMenuComponent::handleObjectMenuSelect(), FireHeavyWeaponMenuComponent::handleObjectMenuSelect(), CloningTerminalMenuComponent::handleObjectMenuSelect(), FireworkMenuComponent::handleObjectMenuSelect(), InsuranceTerminalMenuComponent::handleObjectMenuSelect(), LairMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), ArtCrateMenuComponent::handleObjectMenuSelect(), LootSchematicMenuComponent::handleObjectMenuSelect(), CityDecorationMenuComponent::handleObjectMenuSelect(), CreatureHabitatMenuComponent::handleObjectMenuSelect(), CampTerminalMenuComponent::handleObjectMenuSelect(), FireworkShowMenuComponent::handleObjectMenuSelect(), DiceMenuComponent::handleObjectMenuSelect(), BountyHunterDroidMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::chat::ChatManagerImplementation::handleSocialInternalMessage(), DotPackCommand::hasCost(), server::zone::objects::installation::InstallationObjectImplementation::isAttackableBy(), server::zone::objects::tangible::TangibleObjectImplementation::isAttackableBy(), server::zone::objects::structure::StructureObjectImplementation::isOnAdminList(), server::zone::objects::structure::StructureObjectImplementation::isOnBanList(), server::zone::objects::structure::StructureObjectImplementation::isOnEntryList(), server::zone::objects::structure::StructureObjectImplementation::isOnHopperList(), server::zone::objects::structure::StructureObjectImplementation::isOnPermissionList(), GroupManager::joinGroup(), GroupManager::kickFromGroup(), GroupManager::leaveGroup(), GroupManager::makeLeader(), server::zone::objects::area::LairSpawnAreaImplementation::notifyPositionUpdate(), server::zone::objects::creature::commands::QueueCommand::onComplete(), server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation::onEnter(), server::zone::objects::building::BuildingObjectImplementation::onEnter(), server::zone::objects::building::tutorial::TutorialBuildingObjectImplementation::onExit(), server::zone::objects::building::BuildingObjectImplementation::promptPayAccessFee(), server::zone::managers::player::PlayerManagerImplementation::promptTeachableSkills(), server::zone::objects::group::GroupObjectImplementation::removeGroupModifiers(), CustomVehicleSuiCallback::run(), ForceCureDiseaseCommand::sendCureMessage(), ForceCurePoisonCommand::sendCureMessage(), StopBleedingCommand::sendCureMessage(), FirstAidCommand::sendCureMessage(), CurePackCommand::sendCureMessage(), DamageOverTimeList::sendDecreaseMessage(), HealEnhanceCommand::sendEnhanceMessage(), HealMindCommand::sendHealMessage(), TendCommand::sendHealMessage(), QuickHealCommand::sendHealMessage(), HealAllOther1Command::sendHealMessage(), HealAllOther2Command::sendHealMessage(), HealDamageCommand::sendHealMessage(), TotalHealOtherCommand::sendHealMessage(), DamageOverTimeList::sendIncreaseMessage(), DamageOverTimeList::sendStartMessage(), HealStatesOtherCommand::sendStateMessage(), HealStateCommand::sendStateMessage(), DamageOverTimeList::sendStopMessage(), BoardShuttleCommand::sendTicketSelectionBoxTo(), TendCommand::sendWoundMessage(), HealWoundCommand::sendWoundMessage(), HealHealthWoundOther2Command::sendWoundMessage(), HealHealthWoundOther1Command::sendWoundMessage(), HealMindWoundOther2Command::sendWoundMessage(), HealMindWoundOther1Command::sendWoundMessage(), HealActionWoundOther1Command::sendWoundMessage(), HealActionWoundOther2Command::sendWoundMessage(), TotalHealOtherCommand::sendWoundMessage(), SquadLeaderCommand::setCommandMessage(), CombatManager::startCombat(), server::zone::managers::player::PlayerManagerImplementation::stopListen(), and server::zone::managers::player::PlayerManagerImplementation::stopWatch().
bool CreatureObject::isPlayingMusic ()
Definition at line 1244 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isPlayingMusic(), and RPC_ISPLAYINGMUSIC__.
Referenced by GroupManager::createGroup(), BandFlourishCommand::doBandFlourish(), VentriloquismCommand::doQueueCommand(), FirejetCommand::doQueueCommand(), BandFlourishCommand::doQueueCommand(), PlayerObjectMenuComponent::fillObjectMenuResponse(), GroupManager::joinGroup(), PlayerContainerComponent::notifyObjectRemoved(), server::zone::managers::player::PlayerManagerImplementation::startListen(), and server::zone::managers::player::PlayerManagerImplementation::startWatch().
bool CreatureObject::isPoisoned ()
Definition at line 3721 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isPoisoned(), and RPC_ISPOISONED__.
Referenced by ForceCurePoisonCommand::canPerformSkill(), CurePackCommand::canPerformSkill(), TotalHealOtherCommand::canPerformSkill(), ForceCurePoisonCommand::checkTarget(), TotalHealOtherCommand::checkTarget(), and CurePackCommand::checkTarget().
bool CreatureObject::isProne ()
Definition at line 3513 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isProne(), and RPC_ISPRONE__.
Referenced by CombatQueueCommand::applyEffect(), server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage(), CombatManager::calculateDamage(), CombatManager::calculatePostureModifier(), CombatManager::calculateTargetPostureModifier(), RevivePlayerCommand::canPerformSkill(), HealStatesOtherCommand::canPerformSkill(), HealEnhanceCommand::canPerformSkill(), HealStateCommand::canPerformSkill(), HealWoundCommand::canPerformSkill(), HealAllOther2Command::canPerformSkill(), HealAllOther1Command::canPerformSkill(), HealHealthWoundOther1Command::canPerformSkill(), HealHealthWoundOther2Command::canPerformSkill(), HealMindWoundOther1Command::canPerformSkill(), HealActionWoundOther1Command::canPerformSkill(), HealMindWoundOther2Command::canPerformSkill(), HealActionWoundOther2Command::canPerformSkill(), HealDamageCommand::canPerformSkill(), CurePackCommand::canPerformSkill(), TotalHealOtherCommand::canPerformSkill(), HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), HealMindCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), CollisionManager::getRayOriginPoint(), AiStateComponent::validateStateAttack(), and server::zone::objects::creature::AiAgentImplementation::validateStateAttack().
bool CreatureObject::isRallied ()
Definition at line 3565 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isRallied(), and RPC_ISRALLIED__.
bool CreatureObject::isResuscitable ()
Definition at line 1132 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isResuscitable(), and RPC_ISRESUSCITABLE__.
Referenced by RevivePlayerCommand::canPerformSkill().
bool CreatureObject::isRidingCreature ()
Definition at line 3773 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isRidingCreature(), and RPC_ISRIDINGCREATURE__.
Referenced by server::zone::objects::mission::bountyhunter::BountyHunterDroid::callArakydDroid(), RevivePlayerCommand::canPerformSkill(), HealEnhanceCommand::canPerformSkill(), HealStateCommand::canPerformSkill(), HealWoundCommand::canPerformSkill(), HealDamageCommand::canPerformSkill(), CurePackCommand::canPerformSkill(), BurstRunCommand::checkBurstRun(), RetreatCommand::checkRetreat(), InvulnerableCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::findTarget(), and server::zone::objects::mission::bountyhunter::BountyHunterDroid::transmitBiologicalSignature().
bool CreatureObject::isRidingMount ()
Definition at line 3422 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isRidingMount(), and RPC_ISRIDINGMOUNT__.
Referenced by server::zone::objects::mission::bountyhunter::BountyHunterDroid::callArakydDroid(), InvulnerableCommand::doQueueCommand(), MountCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::findTarget(), server::zone::managers::player::PlayerManagerImplementation::killPlayer(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), server::zone::objects::player::PlayerObjectImplementation::reload(), CombatManager::startCombat(), server::zone::objects::intangible::VehicleControlDeviceImplementation::storeObject(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::transmitBiologicalSignature(), and DataTransformWithParentCallback::updatePosition().
bool CreatureObject::isRooted ()
Definition at line 3682 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isRooted(), and RPC_ISROOTED__.
bool CreatureObject::isRunning ()
Definition at line 3838 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isRunning(), and RPC_ISRUNNING__.
bool CreatureObject::isSitting ()
Definition at line 3539 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isSitting(), and RPC_ISSITTING__.
Referenced by CampTerminalMenuComponent::disbandCamp().
bool CreatureObject::isSkillAnimating ()
Definition at line 3552 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isSkillAnimating(), and RPC_ISSKILLANIMATING__.
bool CreatureObject::isSnared ()
Definition at line 3656 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isSnared(), and RPC_ISSNARED__.
bool CreatureObject::isStanding ()
Definition at line 3526 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isStanding(), and RPC_ISSTANDING__.
Referenced by CombatManager::getAttackerAccuracyModifier(), CampKitMenuComponent::handleObjectMenuSelect(), AiStateComponent::validateStateAttack(), and server::zone::objects::creature::AiAgentImplementation::validateStateAttack().
bool CreatureObject::isStunned ()
Definition at line 3617 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isStunned(), and RPC_ISSTUNNED__.
Referenced by FormupCommand::doFormUp().
bool CreatureObject::isSwimming ()
Definition at line 3396 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isSwimming(), and RPC_ISSWIMMING__.
Referenced by server::zone::managers::minigames::FishingManagerImplementation::checkFishingOnPositionUpdate(), CampKitMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::invalidPosture(), server::zone::managers::minigames::FishingManagerImplementation::startFishing(), and server::zone::managers::minigames::ForageManagerImplementation::startForaging().
bool CreatureObject::isTrainerCreature ()
Definition at line 3383 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isTrainerCreature(), and RPC_ISTRAINERCREATURE__.
bool CreatureObject::isWatching ()
Definition at line 1910 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::isWatching(), and RPC_ISWATCHING__.
Referenced by StopwatchingCommand::doQueueCommand(), WatchCommand::doQueueCommand(), PlayerObjectMenuComponent::fillObjectMenuResponse(), and server::zone::managers::player::PlayerManagerImplementation::startWatch().
void CreatureObject::loadTemplateData (SharedObjectTemplate * templateData)
Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
Precondition
{ templateData is a valid pointer }
Postcondition
{ TangibleObject members are initialized }
Parameters
templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
Definition at line 91 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::loadTemplateData().
void CreatureObject::notifyLoadFromDatabase ()
Gets called when this objects is loaded from database
Precondition
{ this locked }
Postcondition
{ this locked }
Definition at line 1748 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), and RPC_NOTIFYLOADFROMDATABASE__.
int CreatureObject::notifyObjectDestructionObservers (TangibleObject * attacker, int condition)
Is called when this object is destroyed
Precondition
{ this, attacker locked }
Postcondition
{ this, attacker locked }
Definition at line 1719 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::notifyObjectDestructionObservers(), and RPC_NOTIFYOBJECTDESTRUCTIONOBSERVERS__TANGIBLEOBJECT_INT_.
int CreatureObject::notifyObjectInserted (SceneObject * object)
Is called when this object has been inserted with an object
Parameters
object object that has been inserted
Definition at line 697 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::notifyObjectInserted(), and RPC_NOTIFYOBJECTINSERTED__SCENEOBJECT_.
int CreatureObject::notifyObjectKillObservers (TangibleObject * killer)
Is called when this object is killed
Precondition
{ this, killer locked }
Postcondition
{ this, killer locked }
Parameters
killer The killer.
Definition at line 1734 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::notifyObjectKillObservers(), and RPC_NOTIFYOBJECTKILLOBSERVERS__TANGIBLEOBJECT_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::killPlayer().
int CreatureObject::notifyObjectRemoved (SceneObject * object)
Is called when an object was removed
Parameters
object object that has been inserted
Definition at line 711 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::notifyObjectRemoved(), and RPC_NOTIFYOBJECTREMOVED__SCENEOBJECT_.
void CreatureObject::notifyPostureChange (int newPosture)
Definition at line 1090 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::notifyPostureChange(), and RPC_NOTIFYPOSTURECHANGE__INT_.
void CreatureObject::notifySelfPositionUpdate ()
Definition at line 1077 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::notifySelfPositionUpdate(), and RPC_NOTIFYSELFPOSITIONUPDATE__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::updateSwimmingState().
void CreatureObject::playEffect (const String & file, const String & aux)
Definition at line 2475 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::playEffect(), and RPC_PLAYEFFECT__STRING_STRING_.
Referenced by CombatManager::broadcastCombatAction(), CurePackCommand::doAnimations(), StopBleedingCommand::doAnimations(), ForceCureDiseaseCommand::doAnimations(), ForceCurePoisonCommand::doAnimations(), HealStatesOtherCommand::doAnimations(), FirstAidCommand::doAnimations(), TendCommand::doAnimations(), HealMindCommand::doAnimations(), HealAllOther1Command::doAnimations(), HealAllOther2Command::doAnimations(), QuickHealCommand::doAnimations(), HealActionWoundOther2Command::doAnimations(), HealHealthWoundOther1Command::doAnimations(), HealHealthWoundOther2Command::doAnimations(), HealMindWoundOther1Command::doAnimations(), HealMindWoundOther2Command::doAnimations(), HealActionWoundOther1Command::doAnimations(), HealWoundCommand::doAnimations(), HealDamageCommand::doAnimations(), TotalHealOtherCommand::doAnimations(), TotalHealSelfCommand::doAnimations(), HealStateCommand::doAnimations(), RevivePlayerCommand::doAnimations(), HealEnhanceCommand::doAnimations(), DamageOverTime::doBleedingTick(), DamageOverTime::doDiseaseTick(), DamageOverTime::doFireTick(), DamageOverTime::doPoisonTick(), SmokebombCommand::doQueueCommand(), SpotlightCommand::doQueueCommand(), AvoidIncapacitationCommand::doQueueCommand(), ForceResistDiseaseCommand::doQueueCommand(), ForceResistPoisonCommand::doQueueCommand(), DazzleCommand::doQueueCommand(), ForceResistStatesCommand::doQueueCommand(), ColorlightsCommand::doQueueCommand(), DistractCommand::doQueueCommand(), FirejetCommand::doQueueCommand(), ForceResistBleedingCommand::doQueueCommand(), InvulnerableCommand::doQueueCommand(), ForceAbsorb1Command::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), ForceFeedback1Command::doQueueCommand(), ForceAbsorb2Command::doQueueCommand(), ForceRun1Command::doQueueCommand(), ForceFeedback2Command::doQueueCommand(), ForceArmor1Command::doQueueCommand(), ForceRun2Command::doQueueCommand(), ForceArmor2Command::doQueueCommand(), ForceSpeed1Command::doQueueCommand(), ForceRun3Command::doQueueCommand(), ForceShield1Command::doQueueCommand(), ForceShield2Command::doQueueCommand(), ForceSpeed2Command::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), HealStatesSelfCommand::doQueueCommand(), HealHealthWoundSelf1Command::doQueueCommand(), HealActionWoundSelf1Command::doQueueCommand(), HealActionSelf2Command::doQueueCommand(), HealHealthWoundSelf2Command::doQueueCommand(), HealActionWoundSelf2Command::doQueueCommand(), HealMindWoundSelf2Command::doQueueCommand(), HealAllSelf1Command::doQueueCommand(), HealHealthSelf1Command::doQueueCommand(), HealActionSelf1Command::doQueueCommand(), HealAllSelf2Command::doQueueCommand(), HealHealthSelf2Command::doQueueCommand(), HealMindWoundSelf1Command::doQueueCommand(), HealMindSelf2Command::doQueueCommand(), HealMindSelf1Command::doQueueCommand(), HealBattleFatigueSelf2Command::doQueueCommand(), HealBattleFatigueSelf1Command::doQueueCommand(), ElevatorMenuComponent::handleObjectMenuSelect(), ForceShrineMenuComponent::handleObjectMenuSelect(), and server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect().
void CreatureObject::playEffect (const String & file)
Definition at line 2490 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::playEffect(), and RPC_PLAYEFFECT__STRING_.
void CreatureObject::playMusicMessage (const String & file)
Sends a PlayMusicMessage
Definition at line 187 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::playMusicMessage(), and RPC_PLAYMUSICMESSAGE__STRING_.
void CreatureObject::queueDizzyFallEvent ()
Definition at line 2258 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::queueDizzyFallEvent(), and RPC_QUEUEDIZZYFALLEVENT__.
Referenced by KipUpShotCommand::doQueueCommand(), RollShotCommand::doQueueCommand(), ProneCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), DiveShotCommand::doQueueCommand(), StandCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), KneelCommand::doQueueCommand(), and TumbleToKneelingCommand::doQueueCommand().
void CreatureObject::removeAllSkillModsOfType (const int modType, bool notifyClient = true)
Definition at line 1395 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::removeAllSkillModsOfType(), and RPC_REMOVEALLSKILLMODSOFTYPE__INT_BOOL_.
Referenced by server::zone::objects::region::CityRegionImplementation::applySpecializationModifiers(), and server::zone::objects::region::CityRegionImplementation::removeSpecializationModifiers().
void CreatureObject::removeAttackDelay ()
Definition at line 2197 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::removeAttackDelay(), and RPC_REMOVEATTACKDELAY__.
Referenced by DamageOverTime::doBleedingTick(), DamageOverTime::doDiseaseTick(), DamageOverTime::doFireTick(), DamageOverTime::doPoisonTick(), and CombatManager::doTargetCombatAction().
bool CreatureObject::removeBuff (unsigned int buffcrc)
Removes the buff from the creature, activating it and sending packets if it is a player. Buffs should never be removed from the list without sending of packets.
Parameters
buffcrc The buff crc to remove from the buff list.
Definition at line 859 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::removeBuff(), and RPC_REMOVEBUFF__INT_.
Referenced by server::zone::objects::group::GroupObjectImplementation::addGroupModifiers(), CombatQueueCommand::doCombatAction(), TransferItemWeaponCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), server::zone::managers::player::PlayerManagerImplementation::fixHAM(), and server::zone::objects::group::GroupObjectImplementation::removeGroupModifiers().
void CreatureObject::removeBuff (Buff * buff)
Removes the buff from the creature, activating it and sending packets if it is a player. Buffs should never be removed from the list without sending of packets.
Parameters
buffcrc The buff object to remove from the list.
Definition at line 873 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::removeBuff(), and RPC_REMOVEBUFF__BUFF_.
void CreatureObject::removeSkill (Skill * skill, bool notifyClient = true)
Removes the specified skillbox from this object
Precondition
{ this object is locked }
Postcondition
{ this obejct is locked, skillbox is removed }
Parameters
skillBox skillBox to remove
notifyClient if set true the client will be updated with the changes
Definition at line 1337 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::removeSkill().
Referenced by server::zone::managers::skill::SkillManager::surrenderAllSkills(), and server::zone::managers::skill::SkillManager::surrenderSkill().
void CreatureObject::removeSkill (const String & skill, bool notifyClient = true)
Removes the specified skillbox from this object
Precondition
{ this object is locked }
Postcondition
{ this obejct is locked, skillbox is removed }
Parameters
skillBox skillBox to remove
notifyClient if set true the client will be updated with the changes
Definition at line 1346 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::removeSkill(), and RPC_REMOVESKILL__STRING_BOOL_.
void CreatureObject::removeSkillMod (const int modType, const String & skillMod, int value, bool notifyClient = true)
Removes skill mod from the list (same as setting to 0)
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
skillMod skill mod to remove
notifyClient if set true the client will be updated with the changes
Definition at line 1378 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::removeSkillMod(), and RPC_REMOVESKILLMOD__INT_STRING_INT_BOOL_.
Referenced by server::zone::managers::skill::SkillModManager::compareMods(), server::zone::objects::tangible::wearables::WearableContainerObjectImplementation::removeSkillModsFrom(), server::zone::objects::tangible::wearables::WearableObjectImplementation::removeSkillModsFrom(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::removeSkillModsFrom(), server::zone::managers::skill::SkillManager::surrenderAllSkills(), and server::zone::managers::skill::SkillManager::surrenderSkill().
bool CreatureObject::removeStateBuff (unsigned long long state)
Definition at line 887 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::removeStateBuff(), and RPC_REMOVESTATEBUFF__LONG_.
Referenced by CombatQueueCommand::doCombatAction(), FormupCommand::doFormUp(), HealStatesSelfCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), and TotalHealOtherCommand::doQueueCommand().
void CreatureObject::removeWearableObject (TangibleObject * object, bool notifyClient = true)
Definition at line 930 of file CreatureObject.cpp.
References _getImplementation(), server::zone::objects::creature::CreatureObjectImplementation::removeWearableObject(), and RPC_REMOVEWEARABLEOBJECT__TANGIBLEOBJECT_BOOL_.
Referenced by PlayerContainerComponent::notifyObjectRemoved().
void CreatureObject::selectConversationOption (int option, SceneObject * obj)
sends the conversation list
Precondition
{this locked, player locked }
Postcondition
{ this locked, player locked }
Definition at line 1662 of file CreatureObject.cpp.
References _getImplementation(), RPC_SELECTCONVERSATIONOPTION__INT_SCENEOBJECT_, and server::zone::objects::creature::CreatureObjectImplementation::selectConversationOption().
void CreatureObject::sendBaselinesTo (SceneObject * player)
Sends the CREO baseline messages of this object to the specified player
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the baseline messages }
Parameters
player SceneObject that will receive the baselines
Definition at line 130 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDBASELINESTO__SCENEOBJECT_, and server::zone::objects::creature::CreatureObjectImplementation::sendBaselinesTo().
void CreatureObject::sendBuffsTo (CreatureObject * creature)
Definition at line 954 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDBUFFSTO__CREATUREOBJECT_, and server::zone::objects::creature::CreatureObjectImplementation::sendBuffsTo().
void CreatureObject::sendConversationStartTo (SceneObject * player)
sends the conversation list
Precondition
{this locked, player locked }
Postcondition
{ this locked, player locked }
Definition at line 1648 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDCONVERSATIONSTARTTO__SCENEOBJECT_, and server::zone::objects::creature::CreatureObjectImplementation::sendConversationStartTo().
Referenced by NpcConversationStartCommand::doQueueCommand().
void CreatureObject::sendExecuteConsoleCommand (const String & command)
Sends a ExecuteConsoleCommand to the client
Parameters
command example "/attack"
Definition at line 1691 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDEXECUTECONSOLECOMMAND__STRING_, and server::zone::objects::creature::CreatureObjectImplementation::sendExecuteConsoleCommand().
Referenced by server::zone::objects::player::PlayerObjectImplementation::doRecovery(), ThrowGrenadeMenuComponent::handleObjectMenuSelect(), FireHeavyWeaponMenuComponent::handleObjectMenuSelect(), TrapMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::handleObjectMenuSelect(), and server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::handleObjectMenuSelect().
void CreatureObject::sendMessage (BasePacket * msg)
Sends a message to client
Precondition
{ }
Postcondition
{ message is sent to client }
Parameters
msg BasePacket to send
Definition at line 1677 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDMESSAGE__BASEPACKET_, and server::zone::objects::creature::CreatureObjectImplementation::sendMessage().
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::addIngredientToSlot(), server::chat::room::ChatRoomImplementation::addPlayer(), server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::zone::managers::skill::SkillManager::awardSkill(), CombatManager::broadcastCombatSpam(), server::zone::objects::installation::InstallationObjectImplementation::broadcastMessage(), server::zone::objects::installation::InstallationObjectImplementation::broadcastToOperators(), server::zone::managers::auction::AuctionManagerImplementation::buyItem(), server::zone::objects::creature::conversation::ConversationObserverImplementation::cancelConversationSession(), server::zone::managers::auction::AuctionManagerImplementation::cancelItem(), server::zone::objects::scene::SceneObjectImplementation::closeContainerTo(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::closeMenu(), server::zone::managers::minigames::GamblingManagerImplementation::createPayoutWindow(), server::zone::managers::minigames::GamblingManagerImplementation::createRouletteWindow(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::createSellJunkLootSelection(), server::zone::managers::minigames::GamblingManagerImplementation::createSlotWindow(), server::zone::managers::minigames::FishingManagerImplementation::createWindow(), server::zone::managers::auction::AuctionManagerImplementation::displayInfo(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), AreatrackCommand::doQueueCommand(), InsureCommand::doQueueCommand(), RequestBiographyCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), GetAttributesBatchCommand::doQueueCommand(), InstallMissionTerminalCommand::doQueueCommand(), HaveconsentCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), RequestCharacterSheetInfoCommand::doQueueCommand(), DiagnoseCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), RequestStatMigrationDataCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), ServerInfoCommand::executeCommand(), PlayerInfoCommand::executeCommand(), server::zone::managers::player::PlayerManagerImplementation::finishHologrind(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), server::zone::managers::auction::AuctionManagerImplementation::getAuctionData(), server::zone::managers::auction::AuctionManagerImplementation::getItemAttributes(), server::zone::managers::player::PlayerManagerImplementation::handleAbortTradeMessage(), server::zone::managers::player::PlayerManagerImplementation::handleAcceptTransactionMessage(), server::zone::managers::player::PlayerManagerImplementation::handleAddItemToTradeWindow(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), server::zone::managers::vendor::VendorManager::handleDisplayStatus(), server::zone::managers::player::PlayerManagerImplementation::handleGiveMoneyMessage(), server::zone::managers::radial::RadialManagerImplementation::handleObjectMenuRequest(), CloningTerminalMenuComponent::handleObjectMenuSelect(), GogglesObjectMenuComponent::handleObjectMenuSelect(), InsuranceTerminalMenuComponent::handleObjectMenuSelect(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), ArmorObjectMenuComponent::handleObjectMenuSelect(), ForceShrineMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::installation::GeneratorObjectImplementation::handleObjectMenuSelect(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::ContainerImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::handleObjectMenuSelect(), server::chat::ChatManagerImplementation::handleSocialInternalMessage(), server::zone::objects::installation::InstallationObjectImplementation::handleStructureAddEnergy(), server::zone::managers::player::PlayerManagerImplementation::handleUnAcceptTransactionMessage(), server::zone::managers::player::PlayerManagerImplementation::handleVerifyTradeMessage(), server::zone::objects::player::sessions::DestroyStructureSessionImplementation::initializeSession(), server::zone::managers::player::PlayerManagerImplementation::offerTeaching(), server::zone::objects::scene::SceneObjectImplementation::openContainerTo(), TipCommand::performBankTip(), PlaceCityHallComponent::placeStructure(), server::zone::managers::city::CityManagerImplementation::promptAddMilitiaMember(), server::zone::managers::guild::GuildManagerImplementation::promptAddNewEnemy(), server::zone::managers::city::CityManagerImplementation::promptAdjustTaxes(), StructureManager::promptDeleteAllItems(), server::zone::managers::city::CityManagerImplementation::promptDepositCityTreasury(), server::zone::managers::vendor::VendorManager::promptDestroyVendor(), StructureManager::promptFindLostItems(), server::zone::managers::city::CityManagerImplementation::promptMayoralVote(), StructureManager::promptNameStructure(), server::zone::objects::building::BuildingObjectImplementation::promptPayAccessFee(), StructureManager::promptPayMaintenance(), StructureManager::promptPayUncondemnMaintenance(), server::zone::managers::city::CityManagerImplementation::promptRegisterCity(), server::zone::managers::vendor::VendorManager::promptRenameVendorTo(), server::zone::managers::city::CityManagerImplementation::promptSetTax(), server::zone::managers::player::PlayerManagerImplementation::promptTeachableSkills(), server::zone::managers::city::CityManagerImplementation::promptUnregisterCity(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::removeIngredientFromSlot(), server::chat::room::ChatRoomImplementation::removePlayer(), server::zone::managers::resource::ResourceManagerImplementation::removePowerFromPlayer(), StructureManager::reportStructureStatus(), CombatManager::requestDuel(), server::zone::managers::auction::AuctionManagerImplementation::retrieveItem(), DeleteAllItemsSuiCallback::run(), GuildCreateAbbrevResponseSuiCallback::run(), GuildCreateNameResponseSuiCallback::run(), InsuranceMenuSuiCallback::run(), JunkDealerSellListSuiCallback::run(), GamblingSlotPayoutSuiCallback::run(), CustomVehicleSuiCallback::run(), VerifyPlayerNameCallback::run(), ItemDropTradeCallback::run(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::selectConversationOption(), server::zone::managers::guild::GuildManagerImplementation::sendAcceptLotsTo(), server::zone::managers::player::PlayerManagerImplementation::sendActivateCloneRequest(), StartDanceCommand::sendAvailableDances(), StartMusicCommand::sendAvailableSongs(), server::zone::objects::player::PlayerObjectImplementation::sendBadgesResponseTo(), server::zone::managers::gcw::GCWManagerImplementation::sendBaseDefenseStatus(), server::zone::managers::guild::GuildManagerImplementation::sendBaselinesTo(), server::zone::managers::city::CityManagerImplementation::sendChangeCityName(), server::zone::managers::city::CityManagerImplementation::sendCitizenshipReport(), server::zone::managers::city::CityManagerImplementation::sendCityAdvancement(), server::zone::managers::sui::SuiManager::sendConfirmSui(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationContinue(), server::zone::objects::creature::conversation::ConversationObserverImplementation::sendConversationScreenToPlayer(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationStartTo(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationTerminate(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendDelta7(), server::zone::objects::player::sessions::DestroyStructureSessionImplementation::sendDestroyCode(), server::chat::room::ChatRoomImplementation::sendDestroyTo(), server::zone::objects::creature::buffs::BuffImplementation::sendDestroyTo(), server::zone::managers::gcw::GCWManagerImplementation::sendDNASampleMenu(), server::zone::objects::draftschematic::DraftSchematicImplementation::sendDraftSlotsTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildCreateAbbrevTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildCreateNameTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildDisbandConfirmTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildInformationTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildKickPromptTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildListTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberListTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberOptionsTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSetTitleTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredListTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredOptionsTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsorTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsorVerifyTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildTransferTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildWarStatusTo(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendIngredientsNeededSui(), server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation::sendInitialChoices(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendInitialChoices(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendInitialMessage(), server::zone::managers::sui::SuiManager::sendInputBox(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendInsertManuSui(), server::zone::managers::gcw::GCWManagerImplementation::sendJamUplinkMenu(), server::zone::managers::sui::SuiManager::sendKeypadSui(), server::zone::managers::sui::SuiManager::sendListBox(), server::zone::managers::player::PlayerManagerImplementation::sendLoginMessage(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport(), server::zone::managers::city::CityManagerImplementation::sendManageMilitia(), server::zone::managers::city::CityManagerImplementation::sendMayoralStandings(), server::zone::managers::guild::GuildManagerImplementation::sendMemberPermissionsTo(), server::zone::managers::sui::SuiManager::sendMessageBox(), server::zone::objects::cell::CellObjectImplementation::sendPermissionsTo(), server::zone::managers::planet::PlanetManagerImplementation::sendPlanetTravelPointListResponse(), server::zone::managers::gcw::GCWManagerImplementation::sendPowerRegulatorControls(), server::zone::objects::tangible::TangibleObjectImplementation::sendPvpStatusTo(), server::zone::objects::tangible::tool::SurveyToolImplementation::sendRadioactiveWarning(), server::zone::objects::tangible::tool::SurveyToolImplementation::sendRangeSui(), server::zone::managers::vendor::VendorManager::sendRegisterVendorTo(), server::zone::managers::gcw::GCWManagerImplementation::sendRemoveDefenseConfirmation(), server::zone::objects::creature::VehicleObjectImplementation::sendRepairConfirmTo(), server::zone::managers::gcw::GCWManagerImplementation::sendResetVerification(), ResourceSpawner::sendResourceListForSurvey(), server::zone::objects::draftschematic::DraftSchematicImplementation::sendResourceWeightsTo(), server::chat::ChatManagerImplementation::sendRoomList(), server::zone::managers::gcw::GCWManagerImplementation::sendSelectDeedToDonate(), server::zone::objects::tangible::sign::SignObjectImplementation::sendSignNameTo(), server::zone::managers::player::PlayerManagerImplementation::sendStartingLocationsTo(), server::zone::managers::city::CityManagerImplementation::sendStatusReport(), server::zone::managers::city::CityManagerImplementation::sendStructureReport(), ResourceSpawner::sendSurvey(), BoardShuttleCommand::sendTicketSelectionBoxTo(), StructurePermissionList::sendTo(), server::chat::PersistentMessageImplementation::sendTo(), server::zone::templates::mobile::ConversationScreen::sendTo(), server::chat::room::ChatRoomImplementation::sendTo(), server::zone::objects::creature::buffs::BuffImplementation::sendTo(), server::zone::objects::tangible::tool::CraftingToolImplementation::sendToolStartFailure(), server::zone::managers::city::CityManagerImplementation::sendTreasuryReport(), server::zone::managers::weather::WeatherManagerImplementation::sendWeatherTo(), CampTerminalMenuComponent::showCampStatus(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::startImageDesign(), server::zone::managers::skill::SkillManager::surrenderSkill(), server::zone::managers::director::DirectorManager::updateCellPermission(), server::zone::managers::director::DirectorManager::updateCellPermissionGroup(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::updateImageDesign(), and server::zone::objects::tangible::deed::ResourceDeedImplementation::useObject().
void CreatureObject::sendNewbieTutorialEnableHudElement (const String & ui, bool enable = true)
Sends NewbieTutorialEnableHud
Definition at line 215 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDNEWBIETUTORIALENABLEHUDELEMENT__STRING_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::sendNewbieTutorialEnableHudElement().
void CreatureObject::sendNewbieTutorialRequest (const String & request)
Sends a tutorial request
Definition at line 201 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDNEWBIETUTORIALREQUEST__STRING_, and server::zone::objects::creature::CreatureObjectImplementation::sendNewbieTutorialRequest().
void CreatureObject::sendOpenHolocronToPageMessage ()
Definition at line 230 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDOPENHOLOCRONTOPAGEMESSAGE__, and server::zone::objects::creature::CreatureObjectImplementation::sendOpenHolocronToPageMessage().
void CreatureObject::sendSlottedObjectsTo (SceneObject * player)
Sends the contained slotted objects to the specified player
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the slotted objects }
Parameters
player SceneObject that will receive the objects
Definition at line 266 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDSLOTTEDOBJECTSTO__SCENEOBJECT_, and server::zone::objects::creature::CreatureObjectImplementation::sendSlottedObjectsTo().
void CreatureObject::sendSystemMessage (const String & message)
Sends a system message to the client of this object
Precondition
{}
Postcondition
{ this object received the message }
Parameters
message string message to send
Definition at line 173 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDSYSTEMMESSAGE__STRING_, and server::zone::objects::creature::CreatureObjectImplementation::sendSystemMessage().
Referenced by server::zone::managers::gcw::GCWManagerImplementation::abortShutdownSequence(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsorshipRequest(), server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer(), server::zone::objects::player::sessions::EntertainingSessionImplementation::activateEntertainerBuff(), server::zone::managers::city::CityManagerImplementation::addMilitiaMember(), ResourceSpawner::addResourceToPlayerInventory(), server::zone::objects::player::PlayerObjectImplementation::addRewardedSchematic(), server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), CombatQueueCommand::applyEffect(), server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage(), CombatManager::applySpecialAttackCost(), CombatManager::applyStates(), server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership(), server::zone::managers::player::PlayerManagerImplementation::awardExperience(), server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::minigames::GamblingManagerImplementation::bet(), server::zone::managers::gcw::GCWManagerImplementation::broadcastBuilding(), server::zone::managers::minigames::GamblingManagerImplementation::calculateOutcome(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::callArakydDroid(), HealActionSelf1Command::canPerformSkill(), HealActionSelf2Command::canPerformSkill(), HealActionWoundSelf1Command::canPerformSkill(), HealActionWoundSelf2Command::canPerformSkill(), HealAllSelf1Command::canPerformSkill(), HealAllSelf2Command::canPerformSkill(), HealBattleFatigueSelf1Command::canPerformSkill(), HealBattleFatigueSelf2Command::canPerformSkill(), HealHealthSelf1Command::canPerformSkill(), HealHealthSelf2Command::canPerformSkill(), HealHealthWoundSelf1Command::canPerformSkill(), HealHealthWoundSelf2Command::canPerformSkill(), HealMindSelf1Command::canPerformSkill(), HealMindSelf2Command::canPerformSkill(), HealMindWoundSelf1Command::canPerformSkill(), HealMindWoundSelf2Command::canPerformSkill(), HealStatesSelfCommand::canPerformSkill(), RevivePlayerCommand::canPerformSkill(), FirstAidCommand::canPerformSkill(), StopBleedingCommand::canPerformSkill(), ForceCureDiseaseCommand::canPerformSkill(), ForceCurePoisonCommand::canPerformSkill(), HealStatesOtherCommand::canPerformSkill(), HealEnhanceCommand::canPerformSkill(), HealStateCommand::canPerformSkill(), HealWoundCommand::canPerformSkill(), HealAllOther1Command::canPerformSkill(), HealAllOther2Command::canPerformSkill(), HealActionWoundOther1Command::canPerformSkill(), HealActionWoundOther2Command::canPerformSkill(), HealHealthWoundOther1Command::canPerformSkill(), HealHealthWoundOther2Command::canPerformSkill(), HealMindWoundOther1Command::canPerformSkill(), HealMindWoundOther2Command::canPerformSkill(), HealDamageCommand::canPerformSkill(), CurePackCommand::canPerformSkill(), TotalHealOtherCommand::canPerformSkill(), server::zone::managers::gcw::GCWManagerImplementation::canPlaceMoreBases(), StartBandCommand::canPlayInstrument(), server::zone::managers::gcw::GCWManagerImplementation::canStartSlice(), server::zone::managers::gcw::GCWManagerImplementation::canUseTerminals(), server::zone::managers::city::CityManagerImplementation::castMayoralVote(), server::zone::managers::city::CityManagerImplementation::changeCitySpecialization(), BandFlourishCommand::changeStatus(), BurstRunCommand::checkBurstRun(), StructureContainerComponent::checkContainerPermission(), ContainerObjectComponent::checkContainerPermission(), VendorContainerComponent::checkContainerPermission(), SquadLeaderCommand::checkGroupLeader(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::checkJoin(), MaskscentCommand::checkMaskScent(), GCWBaseContainerComponent::checkPVEPermission(), GCWBaseContainerComponent::checkPVPPermission(), RetreatCommand::checkRetreat(), server::zone::managers::auction::AuctionManagerImplementation::checkRetrieve(), server::zone::managers::planet::PlanetManagerImplementation::checkShuttleStatus(), server::zone::managers::player::PlayerManagerImplementation::checkTradeItems(), server::zone::managers::skill::SkillModManager::compareMods(), server::zone::managers::gcw::GCWManagerImplementation::completeSecuritySlice(), ConsentCommand::consent(), server::zone::objects::tangible::tool::SurveyToolImplementation::consentRadioactiveSample(), GroupManager::createGroup(), server::zone::managers::guild::GuildManagerImplementation::createGuild(), server::zone::managers::resource::ResourceManagerImplementation::createResourceSpawn(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::createSellJunkLootSelection(), server::zone::managers::mission::MissionManagerImplementation::createSpawnPoint(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::decay(), StructureManager::declareResidence(), server::zone::managers::guild::GuildManagerImplementation::declareWarByName(), CombatManager::declineDuel(), server::zone::objects::player::PlayerObjectImplementation::decreaseFactionStanding(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::decreasePowerupUses(), server::zone::managers::city::CityManagerImplementation::depositToCityTreasury(), ResourceCommand::despawnResource(), server::zone::managers::weather::WeatherManagerImplementation::disableWeather(), GroupManager::disbandGroup(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), DotPackCommand::doAreaMedicActionTarget(), BandFlourishCommand::doBandFlourish(), HeavyWeaponQueueCommand::doCombatAction(), ForcePowersQueueCommand::doCombatAction(), CombatQueueCommand::doCombatAction(), DelegateFactionPointsCommand::doDelegate(), DatabaseCommand::doObjectDBQuery(), GmReviveCommand::doQueueCommand(), ForceResistPoisonCommand::doQueueCommand(), ForceResistStatesCommand::doQueueCommand(), GetObjVarsCommand::doQueueCommand(), GmJediStateCommand::doQueueCommand(), GrantBadgeCommand::doQueueCommand(), GrantPadawanTrialsEligibilityCommand::doQueueCommand(), GrantZoningRightsCommand::doQueueCommand(), AdjustLotCountCommand::doQueueCommand(), AvoidIncapacitationCommand::doQueueCommand(), InnateCommand::doQueueCommand(), KickCommand::doQueueCommand(), CitypardonCommand::doQueueCommand(), MaskscentCommand::doQueueCommand(), PaymaintenanceCommand::doQueueCommand(), ColorlightsCommand::doQueueCommand(), CompleteQuestCommand::doQueueCommand(), RegenerationCommand::doQueueCommand(), RemoveBannedPlayerCommand::doQueueCommand(), ResendLoginMessageToAllCommand::doQueueCommand(), ResetJediCommand::doQueueCommand(), CreditsCommand::doQueueCommand(), ResourceCommand::doQueueCommand(), DatabaseCommand::doQueueCommand(), SampleCommand::doQueueCommand(), SampleDNACommand::doQueueCommand(), ServerSysGroupCommand::doQueueCommand(), DazzleCommand::doQueueCommand(), DenyServiceCommand::doQueueCommand(), SetLoginMessageCommand::doQueueCommand(), SetpermissionCommand::doQueueCommand(), SetPlayerStateCommand::doQueueCommand(), SetprivacyCommand::doQueueCommand(), SetSpeedCommand::doQueueCommand(), SmokebombCommand::doQueueCommand(), SniperShotCommand::doQueueCommand(), DistractCommand::doQueueCommand(), SpotlightCommand::doQueueCommand(), StartBandCommand::doQueueCommand(), DumpTargetInformationCommand::doQueueCommand(), StopBandCommand::doQueueCommand(), EjectCommand::doQueueCommand(), TeleportCommand::doQueueCommand(), EquilibriumCommand::doQueueCommand(), FactoryCrateSplitCommand::doQueueCommand(), FindMyTrainerCommand::doQueueCommand(), FirejetCommand::doQueueCommand(), VentriloquismCommand::doQueueCommand(), VitalizeCommand::doQueueCommand(), ForceResistBleedingCommand::doQueueCommand(), ForceResistDiseaseCommand::doQueueCommand(), ForceRun1Command::doQueueCommand(), ForceRun2Command::doQueueCommand(), ForceRun3Command::doQueueCommand(), ForceShield1Command::doQueueCommand(), ForceShield2Command::doQueueCommand(), ForceSpeed1Command::doQueueCommand(), ForceSpeed2Command::doQueueCommand(), FreezePlayerCommand::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), GetStationNameCommand::doQueueCommand(), GrantSkillCommand::doQueueCommand(), GuildremoveCommand::doQueueCommand(), AddPowerCommand::doQueueCommand(), AreatrackCommand::doQueueCommand(), BroadcastCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), BroadcastPlanetCommand::doQueueCommand(), InsureCommand::doQueueCommand(), Intimidate1Command::doQueueCommand(), Intimidate2Command::doQueueCommand(), InvulnerableCommand::doQueueCommand(), KillCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), LootCommand::doQueueCommand(), ChangeDanceCommand::doQueueCommand(), ChannelForceCommand::doQueueCommand(), OpenContainerCommand::doQueueCommand(), ClearCompletedQuestCommand::doQueueCommand(), ConcealCommand::doQueueCommand(), ResourceContainerSplitCommand::doQueueCommand(), ResourceContainerTransferCommand::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), SetPerformanceBuffTargetCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), StructurestatusCommand::doQueueCommand(), SurveyCommand::doQueueCommand(), UnfreezePlayerCommand::doQueueCommand(), ForceAbsorb1Command::doQueueCommand(), Warcry1Command::doQueueCommand(), ForceArmor1Command::doQueueCommand(), Warcry2Command::doQueueCommand(), ForceArmor2Command::doQueueCommand(), ForceAbsorb2Command::doQueueCommand(), ForceFeedback1Command::doQueueCommand(), ForceFeedback2Command::doQueueCommand(), ForceMeditateCommand::doQueueCommand(), HarvesterDeactivateCommand::doQueueCommand(), HaveconsentCommand::doQueueCommand(), AddBannedPlayerCommand::doQueueCommand(), ApplyPowerupCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), ChangeMusicCommand::doQueueCommand(), CitybanCommand::doQueueCommand(), MeditateCommand::doQueueCommand(), MountCommand::doQueueCommand(), NameStructureCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), WookieeRoarCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), DestroystructureCommand::doQueueCommand(), FlourishCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), TeleportToCommand::doQueueCommand(), ExtractObjectCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), WipeItemsCommand::doQueueCommand(), GcwStatusCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), HarvesterActivateCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), HarvesterDiscardHopperCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), PowerBoostCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), CreateCreatureCommand::doQueueCommand(), DeclineCommand::doQueueCommand(), SetExperienceCommand::doQueueCommand(), SetFactionCommand::doQueueCommand(), SetGodModeCommand::doQueueCommand(), DiagnoseCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), FishCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), CenterOfBeingCommand::doQueueCommand(), SetFactionStandingCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), DumpZoneInformationCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), BetCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), FindCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), HealActionSelf1Command::doQueueCommand(), HealActionSelf2Command::doQueueCommand(), HealActionWoundSelf1Command::doQueueCommand(), HealActionWoundSelf2Command::doQueueCommand(), HealAllSelf1Command::doQueueCommand(), HealAllSelf2Command::doQueueCommand(), HealHealthSelf1Command::doQueueCommand(), HealHealthSelf2Command::doQueueCommand(), HealHealthWoundSelf1Command::doQueueCommand(), HealHealthWoundSelf2Command::doQueueCommand(), HealMindWoundSelf1Command::doQueueCommand(), HealMindWoundSelf2Command::doQueueCommand(), HealStatesSelfCommand::doQueueCommand(), LogoutServerCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), HealMindSelf1Command::doQueueCommand(), HealMindSelf2Command::doQueueCommand(), ConsentCommand::doQueueCommand(), RequestSurveyCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), HealBattleFatigueSelf1Command::doQueueCommand(), HealBattleFatigueSelf2Command::doQueueCommand(), ForceOfWillCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), ChangeBandMusicCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), DelegateFactionPointsCommand::doQueueCommand(), StartDanceCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), TipCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), TotalHealSelfCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DragIncapacitatedPlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), BandFlourishCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), RetreatCommand::doRetreat(), DiceMenuComponent::doRoll(), DatabaseCommand::doSQLQuery(), TransferstructureCommand::doTransferStructure(), DragIncapacitatedPlayerCommand::drag(), ResourceCommand::dumpResources(), server::zone::managers::weather::WeatherManagerImplementation::enableWeather(), server::zone::managers::player::PlayerManagerImplementation::enhanceCharacter(), MarketCommand::executeCommand(), PlayerManagerCommand::executeCommand(), WeatherCommand::executeCommand(), ServerInfoCommand::executeCommand(), ServerStatisticsCommand::executeCommand(), CityReportCommand::executeCommand(), TurretFireTask::executeCommand(), server::zone::objects::tangible::fishing::FishObjectImplementation::filet(), TurretControlMenuComponent::fillObjectMenuResponse(), SecurityTerminalMenuComponent::fillObjectMenuResponse(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::findAndTrackSuccess(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::findTarget(), server::zone::managers::minigames::ForageManagerImplementation::finishForaging(), server::zone::managers::minigames::FishingManagerImplementation::fishingProceed(), server::zone::managers::city::CityManagerImplementation::fixMayor(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveItems(), CombatManager::freeDuelList(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), server::zone::managers::creature::DnaManager::generateSample(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), PlayerManagementSessionSuiCallback::getPlayerGalaxyID(), server::zone::managers::resource::ResourceManagerImplementation::givePlayerResource(), server::zone::managers::player::PlayerManagerImplementation::handleAddItemToTradeWindow(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), AdBarkingPhraseSuiCallback::handleCustomMessage(), server::zone::managers::sui::SuiManager::handleFishingAction(), server::chat::ChatManagerImplementation::handleGroupChat(), server::chat::ChatManagerImplementation::handleGuildChat(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleInsertFactorySchem(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAbort(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAccept(), server::zone::managers::mission::MissionManagerImplementation::handleMissionListRequest(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetKilled(), ElevatorMenuComponent::handleObjectMenuSelect(), StructureTerminalMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), LightsaberObjectMenuComponent::handleObjectMenuSelect(), SkillBuffObjectMenuComponent::handleObjectMenuSelect(), WeaponObjectMenuComponent::handleObjectMenuSelect(), GogglesObjectMenuComponent::handleObjectMenuSelect(), TangibleObjectMenuComponent::handleObjectMenuSelect(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), VendorMenuComponent::handleObjectMenuSelect(), LootSchematicMenuComponent::handleObjectMenuSelect(), InsuranceTerminalMenuComponent::handleObjectMenuSelect(), ArmorObjectMenuComponent::handleObjectMenuSelect(), CreatureHabitatMenuComponent::handleObjectMenuSelect(), DiceMenuComponent::handleObjectMenuSelect(), PowerRegulatorMenuComponent::handleObjectMenuSelect(), MinefieldMenuComponent::handleObjectMenuSelect(), OverrideTerminalMenuComponent::handleObjectMenuSelect(), UplinkTerminalMenuComponent::handleObjectMenuSelect(), SecurityTerminalMenuComponent::handleObjectMenuSelect(), ForceShrineMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), HQMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::ContainerImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::deed::pet::PetDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::fishing::FishObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::SurveyToolImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::InstrumentImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::CraftingToolImplementation::handleObjectMenuSelect(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleOperateToggle(), VendorDataComponent::handlePayMaintanence(), server::chat::ChatManagerImplementation::handlePlanetChat(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handlePlayerKilled(), server::zone::managers::vendor::VendorManager::handleRegisterVendorCallback(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleRemoveFactorySchem(), server::zone::managers::vendor::VendorManager::handleRenameVendor(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainSkillScreenHandler::handleScreen(), server::zone::managers::sui::SuiManager::handleSetObjectName(), server::zone::managers::vendor::VendorManager::handleUnregisterVendor(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), ResourceSpawner::harvestResource(), ResourceCommand::healthCheck(), server::zone::objects::player::PlayerObjectImplementation::increaseFactionStanding(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::init(), GroupManager::inviteToGroup(), IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage(), GroupManager::joinGroup(), GroupManager::kickFromGroup(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), server::zone::managers::player::PlayerManagerImplementation::killPlayer(), GroupManager::leaveGroup(), server::zone::managers::guild::GuildManagerImplementation::leaveGuild(), ResourceCommand::listResourceInfo(), ResourceSpawner::listResourcesForPlanetOnScreen(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), GroupManager::makeLeader(), server::zone::managers::creature::CreatureManagerImplementation::milk(), server::zone::managers::minigames::FishingManagerImplementation::mishapEvent(), StructureManager::moveFirstItemTo(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), server::zone::objects::area::FsVillageAreaImplementation::notifyEnter(), server::zone::objects::area::CampSiteActiveAreaImplementation::notifyEnter(), server::zone::objects::region::CityRegionImplementation::notifyEnter(), server::zone::objects::area::CampSiteActiveAreaImplementation::notifyExit(), server::zone::objects::region::CityRegionImplementation::notifyExit(), LootContainerComponent::notifyObjectRemoved(), server::zone::managers::resource::ResourceManagerImplementation::notifyObserverEvent(), server::zone::managers::player::PlayerManagerImplementation::notifyObserverEvent(), server::zone::managers::player::PlayerManagerImplementation::offerTeaching(), server::zone::objects::building::BuildingObjectImplementation::onEnter(), server::zone::objects::creature::commands::QueueCommand::onFail(), BandFlourishCommand::parseOptions(), server::zone::objects::building::BuildingObjectImplementation::payAccessFee(), StructureManager::payMaintenance(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::performAction(), TipCommand::performBankTip(), server::zone::managers::gcw::GCWManagerImplementation::performDefenseDontation(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMine(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield(), server::zone::managers::gcw::GCWManagerImplementation::performDonateTurret(), BountyHunterDroidMenuComponent::performDroidAction(), server::zone::objects::mission::BountyMissionObjectiveImplementation::performDroidAction(), TipCommand::performTip(), PlaceGCWBaseComponent::placeStructure(), PlaceDecorationComponent::placeStructure(), PlaceCityHallComponent::placeStructure(), StructureManager::placeStructureFromDeed(), server::zone::managers::weather::WeatherManagerImplementation::printInfo(), BandFlourishCommand::printStatus(), server::zone::managers::gcw::GCWManagerImplementation::processDNASample(), server::zone::managers::guild::GuildManagerImplementation::promptAddNewEnemy(), server::zone::managers::city::CityManagerImplementation::promptAdjustTaxes(), server::zone::managers::city::CityManagerImplementation::promptCitySpecialization(), server::zone::managers::city::CityManagerImplementation::promptMayoralVote(), StructureManager::promptPayMaintenance(), server::zone::managers::city::CityManagerImplementation::promptRegisterCity(), server::zone::managers::city::CityManagerImplementation::promptSetTax(), server::zone::managers::player::PlayerManagerImplementation::promptTeachableSkills(), server::zone::managers::city::CityManagerImplementation::promptWithdrawCityTreasury(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), StructureManager::redeedStructure(), server::zone::managers::city::CityManagerImplementation::registerCity(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), server::zone::managers::city::CityManagerImplementation::removeMilitiaMember(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), server::zone::managers::gcw::GCWManagerImplementation::repairTerminal(), server::zone::objects::creature::VehicleObjectImplementation::repairVehicle(), CombatManager::requestDuel(), CombatManager::requestEndDuel(), server::zone::managers::gcw::GCWManagerImplementation::resetVulnerability(), GmReviveCommand::revivePlayer(), GuildTransferLeaderAckSuiCallback::run(), DestroyStructureCodeSuiCallback::run(), GuildSponsorVerifySuiCallback::run(), DeleteAllItemsConfirmSuiCallback::run(), InsuranceAllConfirmSuiCallback::run(), GuildSponsoredListSuiCallback::run(), GuildCreateAbbrevResponseSuiCallback::run(), GuildMemberListSuiCallback::run(), SurveyCMinigameSuiCallback::run(), SurveyGMinigameSuiCallback::run(), InsuranceMenuSuiCallback::run(), GuildCreateNameResponseSuiCallback::run(), JunkDealerSellListSuiCallback::run(), CloningStoreSuiCallback::run(), InstallMissionTerminalSuiCallback::run(), InsertPowerSuiCallback::run(), RepairVehicleSuiCallback::run(), RecruitSkillTrainerSuiCallback::run(), CustomVehicleSuiCallback::run(), TurretControlSuiCallback::run(), CloningRequestSuiCallback::run(), RenameCitySuiCallback::run(), ItemDropTradeCallback::run(), PlaceCityHallSuiCallback::run(), StructurePayUncondemnMaintenanceSuiCallback::run(), PlayerManagementSessionSuiCallback::runAccountInfo(), server::zone::managers::creature::CreatureManagerImplementation::sample(), server::zone::managers::gcw::GCWManagerImplementation::scheduleBaseDestruction(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::searching(), server::zone::managers::player::PlayerManagerImplementation::sendBattleFatigueMessage(), server::zone::managers::city::CityManagerImplementation::sendChangeCityName(), server::zone::managers::city::CityManagerImplementation::sendCityReport(), SquadLeaderCommand::sendCombatSpam(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationStartTo(), ForceCureDiseaseCommand::sendCureMessage(), StopBleedingCommand::sendCureMessage(), ForceCurePoisonCommand::sendCureMessage(), FirstAidCommand::sendCureMessage(), CurePackCommand::sendCureMessage(), DamageOverTimeList::sendDecreaseMessage(), HealEnhanceCommand::sendEnhanceMessage(), server::zone::managers::guild::GuildManagerImplementation::sendGuildCreateNameTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildDisbandConfirmTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildListTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSetTitleTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredOptionsTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsorTo(), TendCommand::sendHealMessage(), HealMindCommand::sendHealMessage(), QuickHealCommand::sendHealMessage(), HealAllOther1Command::sendHealMessage(), HealAllOther2Command::sendHealMessage(), TotalHealSelfCommand::sendHealMessage(), HealDamageCommand::sendHealMessage(), TotalHealOtherCommand::sendHealMessage(), DamageOverTimeList::sendIncreaseMessage(), server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation::sendInitialChoices(), SetFactionStandingCommand::sendInvalidParameterMessage(), server::zone::managers::gcw::GCWManagerImplementation::sendJamUplinkMenu(), server::zone::managers::city::CityManagerImplementation::sendManageMilitia(), server::zone::managers::guild::GuildManagerImplementation::sendMemberPermissionsTo(), server::zone::managers::director::DirectorManager::sendParameterMessage(), server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner(), server::zone::managers::gcw::GCWManagerImplementation::sendResetVerification(), ResourceSpawner::sendResourceListForSurvey(), server::zone::managers::minigames::FishingManagerImplementation::sendReward(), ResourceSpawner::sendSampleResults(), server::zone::managers::gcw::GCWManagerImplementation::sendSelectDeedToDonate(), DamageOverTimeList::sendStartMessage(), HealStatesOtherCommand::sendStateMessage(), HealStateCommand::sendStateMessage(), server::zone::managers::gcw::GCWManagerImplementation::sendStatus(), DamageOverTimeList::sendStopMessage(), ServerStatisticsCommand::sendSyntax(), MarketCommand::sendSyntax(), ServerInfoCommand::sendSyntax(), PlayerManagerCommand::sendSyntax(), CityReportCommand::sendSyntax(), WeatherCommand::sendSyntax(), server::zone::objects::group::GroupObjectImplementation::sendSystemMessage(), server::zone::objects::tangible::tool::CraftingToolImplementation::sendToolStartFailure(), server::zone::managers::guild::GuildManagerImplementation::sendTransferAckTo(), server::zone::managers::gcw::GCWManagerImplementation::sendTurretAttackListTo(), GetAccountInfoCommand::sendUsage(), server::zone::managers::weather::WeatherManagerImplementation::sendWeatherTo(), TendCommand::sendWoundMessage(), TotalHealSelfCommand::sendWoundMessage(), HealWoundCommand::sendWoundMessage(), HealActionWoundOther2Command::sendWoundMessage(), HealMindWoundOther2Command::sendWoundMessage(), HealHealthWoundOther1Command::sendWoundMessage(), HealHealthWoundOther2Command::sendWoundMessage(), HealActionWoundOther1Command::sendWoundMessage(), HealMindWoundOther1Command::sendWoundMessage(), TotalHealOtherCommand::sendWoundMessage(), server::zone::objects::player::PlayerObjectImplementation::setFactionStatus(), server::zone::managers::guild::GuildManagerImplementation::setMemberTitle(), server::zone::managers::city::CityManagerImplementation::setTax(), CampTerminalMenuComponent::showCampStatus(), server::zone::managers::guild::GuildManagerImplementation::sponsorPlayer(), server::zone::managers::minigames::FishingManagerImplementation::startFishing(), server::zone::managers::minigames::ForageManagerImplementation::startForaging(), server::zone::managers::player::PlayerManagerImplementation::startListen(), server::zone::managers::player::PlayerManagerImplementation::startWatch(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::statusUpdate(), server::zone::managers::minigames::FishingManagerImplementation::stopFishing(), server::zone::managers::player::PlayerManagerImplementation::stopListen(), server::zone::managers::player::PlayerManagerImplementation::stopWatch(), server::zone::managers::minigames::FishingManagerImplementation::success(), server::zone::managers::guild::GuildManagerImplementation::toggleGuildPermission(), server::zone::managers::guild::GuildManagerImplementation::toggleWarStatus(), server::zone::managers::city::CityManagerImplementation::toggleZoningEnabled(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::tracking(), server::zone::managers::guild::GuildManagerImplementation::transferGuildHall(), server::zone::managers::guild::GuildManagerImplementation::transferLeadership(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::transmitBiologicalSignature(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::tuneCrystal(), UnconsentCommand::unconscent(), server::zone::managers::city::CityManagerImplementation::unregisterCity(), server::zone::managers::minigames::FishingManagerImplementation::updateMarker(), server::zone::managers::player::PlayerManagerImplementation::updatePermissionLevel(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::useCharge(), server::zone::managers::city::CityManagerImplementation::validateCityInRange(), server::zone::managers::planet::PlanetManagerImplementation::validateClientCityInRange(), server::zone::managers::guild::GuildManagerImplementation::validateGuildAbbrev(), server::zone::managers::guild::GuildManagerImplementation::validateGuildName(), server::zone::managers::gcw::GCWManagerImplementation::verifyUplinkBand(), and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
void CreatureObject::sendSystemMessage (UnicodeString & message)
Sends a system message to the client of this object
Precondition
{}
Postcondition
{ this object received the message }
Parameters
message unicode message to send
Definition at line 243 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDSYSTEMMESSAGE__UNICODESTRING_, and server::zone::objects::creature::CreatureObjectImplementation::sendSystemMessage().
void CreatureObject::sendSystemMessage (StringIdChatParameter & stringid)
Sends a system message to the client of this object
Precondition
{}
Postcondition
{ this object received the message }
Parameters
message StringIdChatParameter message to send
Definition at line 257 of file CreatureObject.cpp.
References _getImplementation(), and server::zone::objects::creature::CreatureObjectImplementation::sendSystemMessage().
void CreatureObject::sendTo (SceneObject * player, bool doClose)
Sends the necessary messages to player in order to create this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received this object }
Parameters
player SceneObject that will receive the messages
doClose if true a SceneObjectCloseMessage is sent to finish the object
Definition at line 158 of file CreatureObject.cpp.
References _getImplementationForRead(), RPC_SENDTO__SCENEOBJECT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::sendTo().
void CreatureObject::sendToOwner (bool doClose = true)
Sends the necessary messages to owner client
Precondition
{ this object is locked }
Postcondition
{ this object is locked, owner received its own scene object }
Parameters
doClose if true a SceneObjectCloseMessage is sent to finish the object
Definition at line 144 of file CreatureObject.cpp.
References _getImplementation(), RPC_SENDTOOWNER__BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::sendToOwner().
Referenced by SelectCharacterCallback::run().
void CreatureObject::setAccelerationMultiplierBase (float newMultiplierBase, bool notifyClient = true)
Updates the acceleration speed multiplier base
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
newMultiplierBase new multiplier base to set
notifyClient if set true the client will be updated with the changes
Definition at line 363 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETACCELERATIONMULTIPLIERBASE__FLOAT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setAccelerationMultiplierBase().
void CreatureObject::setAccelerationMultiplierMod (float newMultiplierMod, bool notifyClient = true)
Updates the acceleration speed multiplier mod
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
newMultiplierMod new multiplier mod to set
notifyClient if set true the client will be updated with the changes
Definition at line 378 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETACCELERATIONMULTIPLIERMOD__FLOAT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setAccelerationMultiplierMod().
Referenced by DismountCommand::doQueueCommand(), and MountCommand::doQueueCommand().
void CreatureObject::setAimingState (int durationSeconds = 5)
Definition at line 1991 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETAIMINGSTATE__INT_, and server::zone::objects::creature::CreatureObjectImplementation::setAimingState().
Referenced by AimCommand::doQueueCommand().
void CreatureObject::setBankCredits (int credits, bool notifyClient = true)
Updates the bank credits of this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified bank credits }
Parameters
credits the new credits
notifyClient if set true the client will be updated with the changes
Definition at line 830 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETBANKCREDITS__INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setBankCredits().
Referenced by server::zone::managers::sui::SuiManager::handleBankTransfer(), and RepairVehicleSuiCallback::run().
void CreatureObject::setBaseHAM (int type, int value, bool notifyClient = true)
Updates a specific type of the Base HAM
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the Base HAM type updated to the new value }
Parameters
type specifies which Base HAM type to update
value the new value
notifyClient if set true the client will be updated with the changes
Definition at line 570 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETBASEHAM__INT_INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setBaseHAM().
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addProfessionStartingItems(), and server::zone::managers::player::creation::PlayerCreationManager::addRacialMods().
void CreatureObject::setBerserkedState (unsigned int duration)
Definition at line 2019 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETBERSERKEDSTATE__INT_, and server::zone::objects::creature::CreatureObjectImplementation::setBerserkedState().
Referenced by Berserk2Command::doQueueCommand(), and Berserk1Command::doQueueCommand().
void CreatureObject::setBlindedState (int durationSeconds = 5)
Definition at line 2047 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETBLINDEDSTATE__INT_, and server::zone::objects::creature::CreatureObjectImplementation::setBlindedState().
Referenced by CombatQueueCommand::applyEffect(), and server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage().
void CreatureObject::setCashCredits (int credits, bool notifyClient = true)
Update the cash credits of this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified cash credits }
Parameters
credits the new credits
notifyClient if set true the client will be updated with the changes
Definition at line 1283 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETCASHCREDITS__INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setCashCredits().
Referenced by server::zone::managers::minigames::GamblingManagerImplementation::bet(), server::zone::managers::minigames::GamblingManagerImplementation::calculateOutcome(), server::zone::managers::sui::SuiManager::handleBankTransfer(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), and server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction().
void CreatureObject::setClient (ZoneClientSession * cli)
Definition at line 1923 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETCLIENT__ZONECLIENTSESSION_, and server::zone::objects::creature::CreatureObjectImplementation::setClient().
Referenced by SelectCharacterCallback::run().
void CreatureObject::setCombatState ()
Sets the combat state
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object is in a combat state }
Definition at line 280 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETCOMBATSTATE__, and server::zone::objects::creature::CreatureObjectImplementation::setCombatState().
void CreatureObject::setControlDevice (ControlDevice * device)
Definition at line 1532 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETCONTROLDEVICE__CONTROLDEVICE_, and server::zone::objects::creature::CreatureObjectImplementation::setControlDevice().
void CreatureObject::setCoverState (int durationSeconds = 40)
Definition at line 2005 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETCOVERSTATE__INT_, and server::zone::objects::creature::CreatureObjectImplementation::setCoverState().
Referenced by TakeCoverCommand::doQueueCommand().
void CreatureObject::setCreatureLink (CreatureObject * object, bool notifyClient = true)
Updates creatureLinkID with specified object
Precondition
{ this is locked }
Postcondition
{ this is locked }
Definition at line 1546 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETCREATURELINK__CREATUREOBJECT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setCreatureLink().
void CreatureObject::setCurrentSpeed (float newSpeed)
Definition at line 453 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETCURRENTSPEED__FLOAT_, and server::zone::objects::creature::CreatureObjectImplementation::setCurrentSpeed().
Referenced by server::zone::managers::player::PlayerManagerImplementation::killPlayer(), and server::zone::managers::player::PlayerManagerImplementation::notifyDestruction().
void CreatureObject::setCurrentWeather (byte value)
Definition at line 3942 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETCURRENTWEATHER__BYTE_, and server::zone::objects::creature::CreatureObjectImplementation::setCurrentWeather().
Referenced by server::zone::managers::weather::WeatherManagerImplementation::sendWeatherTo().
void CreatureObject::setCurrentWind (byte value)
Definition at line 3969 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETCURRENTWIND__BYTE_, and server::zone::objects::creature::CreatureObjectImplementation::setCurrentWind().
void CreatureObject::setDizziedState (int durationSeconds = 5)
Definition at line 1963 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETDIZZIEDSTATE__INT_, and server::zone::objects::creature::CreatureObjectImplementation::setDizziedState().
Referenced by CombatQueueCommand::applyEffect().
void CreatureObject::setEncumbrance (int type, int value, bool notifyClient = true)
Updates a specific type of the Encumbrance
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the Encumbrance type updated to the new value }
Parameters
type specifies which Encumbrance type to update
value the new value
notifyClient if set true the client will be updated with the changes
Definition at line 650 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETENCUMBRANCE__INT_INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setEncumbrance().
void CreatureObject::setFactionRank (int rank, bool notifyClient = true)
Definition at line 1761 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETFACTIONRANK__INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setFactionRank().
void CreatureObject::setGuildObject (GuildObject * guildobj)
Definition at line 3090 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETGUILDOBJECT__GUILDOBJECT_, and server::zone::objects::creature::CreatureObjectImplementation::setGuildObject().
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::managers::guild::GuildManagerImplementation::createGuild(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), and server::zone::managers::guild::GuildManagerImplementation::leaveGuild().
void CreatureObject::setHAM (int type, int value, bool notifyClient = true)
Updates a specific type of the HAM
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the HAM type updated to the new value }
Parameters
type specifies which HAM type to update
value the new value
notifyClient if set true the client will be updated with the changes
Definition at line 467 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETHAM__INT_INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setHAM().
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addProfessionStartingItems(), server::zone::managers::player::creation::PlayerCreationManager::addRacialMods(), and server::zone::managers::player::PlayerManagerImplementation::fixHAM().
void CreatureObject::setHeight (float heigh, bool notifyClient = true)
Definition at line 348 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETHEIGHT__FLOAT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setHeight().
void CreatureObject::setInstrumentID (int instrumentid, bool notifyClient = true)
Updates the instrument id to the specified object id
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified weapon id }
Parameters
instrumentid the new instrument id
notifyClient if set true the client will be updated with the changes
Definition at line 725 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETINSTRUMENTID__INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setInstrumentID().
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainingUpdate().
void CreatureObject::setIntimidatedState (unsigned int mod, int durationSeconds = 15)
Definition at line 2061 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETINTIMIDATEDSTATE__INT_INT_, and server::zone::objects::creature::CreatureObjectImplementation::setIntimidatedState().
Referenced by CombatQueueCommand::applyEffect().
void CreatureObject::setInvisible (bool invis)
Definition at line 4040 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETINVISIBLE__BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setInvisible().
void CreatureObject::setLevel (int level)
Definition at line 1104 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETLEVEL__INT_, and server::zone::objects::creature::CreatureObjectImplementation::setLevel().
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), TransferItemWeaponCommand::doQueueCommand(), server::zone::managers::creature::CreatureManagerImplementation::spawnCreatureWithLevel(), and server::zone::managers::skill::SkillManager::surrenderSkill().
void CreatureObject::setListenToID (unsigned long long id, bool notifyClient = true)
Updates listen id
Definition at line 740 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETLISTENTOID__LONG_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setListenToID().
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainmentUpdate(), and server::zone::managers::player::PlayerManagerImplementation::startListen().
void CreatureObject::setMaxHAM (int type, int value, bool notifyClient = true)
Updates a specific type of the Max HAM
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the Max HAM type updated to the new value }
Parameters
type specifies which Max HAM type to update
value the new value
notifyClient if set true the client will be updated with the changes
Definition at line 618 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETMAXHAM__INT_INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setMaxHAM().
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addProfessionStartingItems(), server::zone::managers::player::creation::PlayerCreationManager::addRacialMods(), ChannelForceCommand::doQueueCommand(), and server::zone::managers::player::PlayerManagerImplementation::fixHAM().
void CreatureObject::setMeditateState ()
Definition at line 2119 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETMEDITATESTATE__, and server::zone::objects::creature::CreatureObjectImplementation::setMeditateState().
Referenced by ForceMeditateCommand::doQueueCommand(), and MeditateCommand::doQueueCommand().
void CreatureObject::setMood (byte moodID, bool notifyClient = true)
Sets characters mood
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
moodID mood to set
Definition at line 1458 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETMOOD__BYTE_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setMood().
Referenced by SetMoodInternalCommand::doQueueCommand(), server::zone::managers::player::PlayerManagerImplementation::notifyObserverEvent(), server::zone::managers::player::PlayerManagerImplementation::stopListen(), and server::zone::managers::player::PlayerManagerImplementation::stopWatch().
void CreatureObject::setMoodString (const String & animation, bool notifyClient = true)
Sets a new mood animation
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
mood mood animation string
Definition at line 1473 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETMOODSTRING__STRING_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setMoodString().
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainmentUpdate(), server::zone::managers::minigames::FishingManagerImplementation::startFishing(), and server::zone::managers::minigames::FishingManagerImplementation::stopFishing().
bool CreatureObject::setNextAttackDelay (unsigned int mod, int del)
Definition at line 2104 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETNEXTATTACKDELAY__INT_INT_, and server::zone::objects::creature::CreatureObjectImplementation::setNextAttackDelay().
Referenced by CombatQueueCommand::applyEffect().
void CreatureObject::setPerformanceAnimation (const String & animation, bool notifyClient = true)
Updates the preformance animation string
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the animation updated }
Parameters
animation new animation
notifyClient if set true the client will be updated with the changes
Definition at line 770 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETPERFORMANCEANIMATION__STRING_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setPerformanceAnimation().
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainingUpdate().
void CreatureObject::setPerformanceCounter (int counter, bool notifyClient = true)
Updates the preformance counter
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the counter updated }
Parameters
counter new performance counter
notifyClient if set true the client will be updated with the changes
Definition at line 755 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETPERFORMANCECOUNTER__INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setPerformanceCounter().
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainingUpdate().
void CreatureObject::setPosture (int newPosture, bool notifyClient = true)
Sets a new posture
Precondition
{ this object is locked }
Postcondition
{this object is locked, this object has the new posture set }
Parameters
newPosture posture to set
notifyClient if set true the client will be updated with the changes
Definition at line 307 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETPOSTURE__INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setPosture().
Referenced by ResourceSpawner::addResourceToPlayerInventory(), CombatQueueCommand::applyEffect(), server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage(), CombatManager::applyStates(), server::zone::objects::tangible::firework::FireworkObjectImplementation::completeLaunch(), CampTerminalMenuComponent::disbandCamp(), RollShotCommand::doQueueCommand(), KipUpShotCommand::doQueueCommand(), ProneCommand::doQueueCommand(), DiveShotCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), StandCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), KneelCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), SitServerCommand::doQueueCommand(), ForceOfWillCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), server::zone::managers::creature::DnaManager::generateSample(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::init(), server::zone::managers::player::PlayerManagerImplementation::killPlayer(), server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), GmReviveCommand::revivePlayer(), server::zone::managers::planet::PlanetManagerImplementation::scheduleShuttle(), and ResourceSpawner::sendSampleResults().
void CreatureObject::setRalliedState (int durationSeconds = 5)
Definition at line 1977 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETRALLIEDSTATE__INT_, and server::zone::objects::creature::CreatureObjectImplementation::setRalliedState().
void CreatureObject::setRootedState (int durationSeconds = 20)
Definition at line 2090 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETROOTEDSTATE__INT_, and server::zone::objects::creature::CreatureObjectImplementation::setRootedState().
void CreatureObject::setRunSpeed (float newSpeed, bool notifyClient = true)
Updates the run speed
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Definition at line 438 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETRUNSPEED__FLOAT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setRunSpeed().
void CreatureObject::setScreenPlayState (const String & screenPlay, unsigned long long state)
Definition at line 2363 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETSCREENPLAYSTATE__STRING_LONG_, and server::zone::objects::creature::CreatureObjectImplementation::setScreenPlayState().
Referenced by CompleteQuestCommand::doQueueCommand(), and ClearCompletedQuestCommand::doQueueCommand().
void CreatureObject::setShockWounds (int newShock, bool notifyClient = true)
Updates shock wounds
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified target id }
Parameters
shock new shock wounds
notifyClient if set true the client will be updated with the changes
Definition at line 785 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETSHOCKWOUNDS__INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setShockWounds().
Referenced by server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), and GmReviveCommand::revivePlayer().
void CreatureObject::setSnaredState (int durationSeconds = 20)
Definition at line 2076 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETSNAREDSTATE__INT_, and server::zone::objects::creature::CreatureObjectImplementation::setSnaredState().
void CreatureObject::setSpeedMultiplierBase (float newMultiplierBase, bool notifyClient = true)
Updates the speed multiplier base
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
newMultiplierBase new multiplier base to set
notifyClient if set true the client will be updated with the changes
Definition at line 393 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETSPEEDMULTIPLIERBASE__FLOAT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setSpeedMultiplierBase().
void CreatureObject::setSpeedMultiplierMod (float newMultiplierMod, bool notifyClient = true)
Updates the speed multiplier mod
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
newMultiplierMod new multiplier mod to set
notifyClient if set true the client will be updated with the changes
Definition at line 408 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETSPEEDMULTIPLIERMOD__FLOAT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setSpeedMultiplierMod().
Referenced by DismountCommand::doQueueCommand(), and MountCommand::doQueueCommand().
bool CreatureObject::setState (unsigned long long state, bool notifyClient = true)
Sets a new state to the statebitmask
Precondition
{ this object is locked }
Postcondition
{ this object is locked, stateBitmask has the new state }
Parameters
state state to add
Definition at line 1502 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETSTATE__LONG_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setState().
Referenced by DamageOverTimeList::addDot(), CombatManager::attemptPeace(), SetPlayerStateCommand::doQueueCommand(), MountCommand::doQueueCommand(), SitServerCommand::doQueueCommand(), CombatManager::forcePeace(), server::zone::objects::intangible::ShipControlDeviceImplementation::generateObject(), and server::zone::managers::player::PlayerManagerImplementation::updateSwimmingState().
void CreatureObject::setStunnedState (int durationSeconds = 5)
Definition at line 2033 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETSTUNNEDSTATE__INT_, and server::zone::objects::creature::CreatureObjectImplementation::setStunnedState().
Referenced by CombatQueueCommand::applyEffect().
void CreatureObject::setTargetID (unsigned long long targetID, bool notifyClient = true)
Updates the target id to the specified object id
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified target id }
Parameters
objectID the new target id
notifyClient if set true the client will be updated with the changes
Definition at line 815 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETTARGETID__LONG_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setTargetID().
void CreatureObject::setTerrainNegotiation (float value, bool notifyClient = true)
Updates the terrain negotiation variable?
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified terrain negotiation }
Parameters
terrain new terrain negotiation
notifyClient if set true the client will be updated with the changes
Definition at line 1298 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETTERRAINNEGOTIATION__FLOAT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setTerrainNegotiation().
void CreatureObject::setTurnScale (float newMultiplierMod, bool notifyClient = true)
Updates the turn scale mod
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
newMultiplierMod new multiplier mod to set
notifyClient if set true the client will be updated with the changes
Definition at line 423 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETTURNSCALE__FLOAT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setTurnScale().
void CreatureObject::setWatchToID (unsigned long long id)
Definition at line 3343 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETWATCHTOID__LONG_, and server::zone::objects::creature::CreatureObjectImplementation::setWatchToID().
Referenced by server::zone::managers::player::PlayerManagerImplementation::startWatch(), and server::zone::managers::player::PlayerManagerImplementation::stopWatch().
void CreatureObject::setWeapon (WeaponObject * weao, bool notifyClient = false)
Updates the weapon to the specified object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the specified weapon id }
Parameters
weao the new weapon
notifyClient if set true the client will be updated with the changes
Definition at line 682 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETWEAPON__WEAPONOBJECT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setWeapon().
Referenced by TransferItemWeaponCommand::doQueueCommand(), and TransferItemMiscCommand::doQueueCommand().
void CreatureObject::setWounds (int type, int value, bool notifyClient = true)
Updates a specific type of the Wounds
Precondition
{ this object is locked }
Postcondition
{ this object is locked, this object has the Wounds type updated to the new value }
Parameters
type specifies which Wounds type to update
value the new value
notifyClient if set true the client will be updated with the changes
Definition at line 586 of file CreatureObject.cpp.
References _getImplementation(), RPC_SETWOUNDS__INT_INT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::setWounds().
Referenced by BoostmoraleCommand::getWounds(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), and GmReviveCommand::revivePlayer().
void CreatureObject::stopEntertaining ()
Definition at line 1257 of file CreatureObject.cpp.
References _getImplementation(), RPC_STOPENTERTAINING__, and server::zone::objects::creature::CreatureObjectImplementation::stopEntertaining().
Referenced by CombatManager::doTargetCombatAction(), PlayerContainerComponent::notifyObjectInserted(), and PlayerContainerComponent::notifyObjectRemoved().
void CreatureObject::subtractBankCredits (int credits)
Definition at line 1175 of file CreatureObject.cpp.
References _getImplementation(), RPC_SUBTRACTBANKCREDITS__INT_, and server::zone::objects::creature::CreatureObjectImplementation::subtractBankCredits().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), PurchaseTicketCommand::doQueueCommand(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainSkillScreenHandler::handleScreen(), server::zone::objects::structure::StructureObjectImplementation::payMaintenance(), InsuranceAllConfirmSuiCallback::run(), InsuranceMenuSuiCallback::run(), CloningStoreSuiCallback::run(), and TaxPayMailTask::run().
void CreatureObject::subtractCashCredits (int credits)
Definition at line 1189 of file CreatureObject.cpp.
References _getImplementation(), RPC_SUBTRACTCASHCREDITS__INT_, and server::zone::objects::creature::CreatureObjectImplementation::subtractCashCredits().
Referenced by server::zone::managers::city::CityManagerImplementation::depositToCityTreasury(), PurchaseTicketCommand::doQueueCommand(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainSkillScreenHandler::handleScreen(), server::zone::managers::player::PlayerManagerImplementation::handleVerifyTradeMessage(), server::zone::objects::building::BuildingObjectImplementation::payAccessFee(), StructureManager::payMaintenance(), server::zone::objects::structure::StructureObjectImplementation::payMaintenance(), TipCommand::performTip(), InsuranceAllConfirmSuiCallback::run(), InsuranceMenuSuiCallback::run(), and CloningStoreSuiCallback::run().
void CreatureObject::updateCooldownTimer (const String & coooldownTimer, unsigned int miliSecondsToAdd = 0)
Definition at line 2391 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATECOOLDOWNTIMER__STRING_INT_, and server::zone::objects::creature::CreatureObjectImplementation::updateCooldownTimer().
Referenced by CombatQueueCommand::applyEffect(), MaskscentCommand::doQueueCommand(), MountCommand::doQueueCommand(), DismountCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), RetreatCommand::doRetreat(), and server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect().
void CreatureObject::updateGroup (GroupObject * group, bool notifyClient = true)
Sets the group of this object
Precondition
{ this object is locked }
Postcondition
{this object is locked }
Parameters
group GroupObject to update
notifyClient if set true the client will be updated with the changes
Definition at line 1425 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATEGROUP__GROUPOBJECT_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::updateGroup().
Referenced by GroupManager::createGroup(), server::zone::objects::group::GroupObjectImplementation::disband(), GroupManager::joinGroup(), GroupManager::kickFromGroup(), and GroupManager::leaveGroup().
void CreatureObject::updateGroupInviterID (unsigned long long id, bool notifyClient = true)
Sets a new group inviter id
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
id object id of the inviter
notifyClient if set true the client will be updated with the changes
Definition at line 1410 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATEGROUPINVITERID__LONG_BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::updateGroupInviterID().
Referenced by GroupManager::createGroup(), DeclineCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), GroupManager::inviteToGroup(), and GroupManager::joinGroup().
void CreatureObject::updateKnockdownRecovery ()
Definition at line 2245 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATEKNOCKDOWNRECOVERY__, and server::zone::objects::creature::CreatureObjectImplementation::updateKnockdownRecovery().
Referenced by CombatQueueCommand::applyEffect().
void CreatureObject::updateLastKnockdown ()
Definition at line 2271 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATELASTKNOCKDOWN__, and server::zone::objects::creature::CreatureObjectImplementation::updateLastKnockdown().
Referenced by CombatQueueCommand::applyEffect().
void CreatureObject::updateLastSuccessfulCombatAction ()
Definition at line 2232 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATELASTSUCCESSFULCOMBATACTION__, and server::zone::objects::creature::CreatureObjectImplementation::updateLastSuccessfulCombatAction().
Referenced by CombatManager::doCombatAction().
void CreatureObject::updateLocomotion ()
Definition at line 335 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATELOCOMOTION__, and server::zone::objects::creature::CreatureObjectImplementation::updateLocomotion().
Referenced by server::zone::managers::player::PlayerManagerImplementation::killPlayer(), and server::zone::managers::player::PlayerManagerImplementation::notifyDestruction().
void CreatureObject::updatePostureDownRecovery ()
Definition at line 2310 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATEPOSTUREDOWNRECOVERY__, and server::zone::objects::creature::CreatureObjectImplementation::updatePostureDownRecovery().
Referenced by CombatQueueCommand::applyEffect().
void CreatureObject::updatePostureUpRecovery ()
Definition at line 2323 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATEPOSTUREUPRECOVERY__, and server::zone::objects::creature::CreatureObjectImplementation::updatePostureUpRecovery().
Referenced by CombatQueueCommand::applyEffect().
void CreatureObject::updateSpeedAndAccelerationMods ()
Definition at line 4078 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATESPEEDANDACCELERATIONMODS__, and server::zone::objects::creature::CreatureObjectImplementation::updateSpeedAndAccelerationMods().
void CreatureObject::updateTimeOfDeath ()
Definition at line 2171 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATETIMEOFDEATH__, and server::zone::objects::creature::CreatureObjectImplementation::updateTimeOfDeath().
Referenced by server::zone::managers::player::PlayerManagerImplementation::killPlayer(), and server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction().
void CreatureObject::updateToDatabaseAllObjects (bool startTask)
Definition at line 1118 of file CreatureObject.cpp.
References _getImplementation(), RPC_UPDATETODATABASEALLOBJECTS__BOOL_, and server::zone::objects::creature::CreatureObjectImplementation::updateToDatabaseAllObjects().
Referenced by server::zone::managers::mission::MissionManagerImplementation::handleMissionAccept(), and server::zone::managers::mission::MissionManagerImplementation::removeMission().
bool CreatureObject::verifyBankCredits (int credits)
Definition at line 1217 of file CreatureObject.cpp.
References _getImplementation(), RPC_VERIFYBANKCREDITS__INT_, and server::zone::objects::creature::CreatureObjectImplementation::verifyBankCredits().
bool CreatureObject::verifyCashCredits (int credits)
Definition at line 1203 of file CreatureObject.cpp.
References _getImplementation(), RPC_VERIFYCASHCREDITS__INT_, and server::zone::objects::creature::CreatureObjectImplementation::verifyCashCredits().
Friends And Related Function Documentation
friend class CreatureObjectHelper friend
Definition at line 1404 of file CreatureObject.h.
Member Data Documentation
const int server::zone::objects::creature::CreatureObject::BOTHAN = 5 static
Definition at line 329 of file CreatureObject.h.
unsigned const long long server::zone::objects::creature::CreatureObject::DEAD_TOO_LONG = 1800000 static
Definition at line 343 of file CreatureObject.h.
const int server::zone::objects::creature::CreatureObject::FEMALE = 1 static
Definition at line 341 of file CreatureObject.h.
const int server::zone::objects::creature::CreatureObject::HUMAN = 0 static
Definition at line 319 of file CreatureObject.h.
const int server::zone::objects::creature::CreatureObject::ITHORIAN = 0x21 static
Definition at line 335 of file CreatureObject.h.
const int server::zone::objects::creature::CreatureObject::MALE = 0 static
Definition at line 339 of file CreatureObject.h.
const int server::zone::objects::creature::CreatureObject::MONCAL = 3 static
Definition at line 325 of file CreatureObject.h.
const int server::zone::objects::creature::CreatureObject::RODIAN = 1 static
Definition at line 321 of file CreatureObject.h.
const int server::zone::objects::creature::CreatureObject::SULLUSTAN = 0x31 static
Definition at line 337 of file CreatureObject.h.
const int server::zone::objects::creature::CreatureObject::TRANDOSHAN = 2 static
Definition at line 323 of file CreatureObject.h.
const int server::zone::objects::creature::CreatureObject::TWILEK = 6 static
Definition at line 331 of file CreatureObject.h.
const int server::zone::objects::creature::CreatureObject::WOOKIE = 4 static
Definition at line 327 of file CreatureObject.h.
const int server::zone::objects::creature::CreatureObject::ZABRAK = 7 static
Definition at line 333 of file CreatureObject.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/CreatureObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/CreatureObject.cpp