Core3: PathGraph Class Reference
PathGraph Class Reference
#include <PathGraph.h>
Public Member Functions
PathGraph (FloorMesh *floor)
~PathGraph ()
void readObject (IffStream *iffStream)
float calculateManhattanDistance (PathNode *node1, PathNode *node2)
PathNode * getNode (int globalNumberID)
PathNode * findNearestNode (float x, float z, float y)
PathNode * findNearestNode (const Vector3 &pointAlfa)
PathNode * findNearestGlobalNode (const Vector3 &pointAlfa)
PathNode * findGlobalNode (int globalNodeID)
void addPathNode (PathNode *pathNode)
Vector< PathNode * > * getPathNodes ()
Vector< PathNode * > getGlobalNodes ()
FloorMesh * getFloorMesh ()
Public Member Functions inherited from IffTemplate
virtual ~IffTemplate ()
Public Member Functions inherited from TemplateData
virtual ~TemplateData ()
Protected Member Functions
void connectNodes (Vector< PathEdge > &pathEdges)
Private Attributes
Vector< PathNode * > pathNodes
int unkownMetaInt
Vector< int > ecnt
Vector< int > estr
FloorMesh * floorMesh
Detailed Description
Definition at line 16 of file PathGraph.h.
Constructor & Destructor Documentation
PathGraph::PathGraph (FloorMesh * floor) inline
Definition at line 31 of file PathGraph.h.
References floorMesh, and unkownMetaInt.
PathGraph::~PathGraph () inline
Definition at line 36 of file PathGraph.h.
References pathNodes.
Member Function Documentation
void PathGraph::addPathNode (PathNode * pathNode) inline
Definition at line 60 of file PathGraph.h.
References pathNodes.
float PathGraph::calculateManhattanDistance (PathNode * node1, PathNode * node2) inline
Definition at line 43 of file PathGraph.h.
References PathNode::getPosition().
void PathGraph::connectNodes (Vector< PathEdge > & pathEdges) protected
Definition at line 147 of file PathGraph.cpp.
References PathNode::addChild(), PathEdge::getFromConnection(), PathEdge::getToConnection(), and pathNodes.
Referenced by readObject().
PathNode * PathGraph::findGlobalNode (int globalNodeID)
Definition at line 93 of file PathGraph.cpp.
References PathNode::getGlobalGraphNodeID(), and pathNodes.
Referenced by FloorMesh::getGlobalNode().
PathNode * PathGraph::findNearestGlobalNode (const Vector3 & pointAlfa)
Definition at line 104 of file PathGraph.cpp.
References PathNode::getGlobalGraphNodeID(), PathNode::getX(), PathNode::getY(), PathNode::getZ(), and pathNodes.
Referenced by PathFinderManager::findPathFromCellToWorld(), and FleeStateComponent::getFleeLocation().
PathNode* PathGraph::findNearestNode (float x, float z, float y) inline
Definition at line 52 of file PathGraph.h.
Referenced by PathFinderManager::findPathFromWorldToCell().
PathNode * PathGraph::findNearestNode (const Vector3 & pointAlfa)
Definition at line 127 of file PathGraph.cpp.
References PathNode::getX(), PathNode::getY(), PathNode::getZ(), and pathNodes.
FloorMesh* PathGraph::getFloorMesh () inline
Definition at line 79 of file PathGraph.h.
References floorMesh.
Referenced by PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), PathFinderManager::findPathFromWorldToCell(), and PathNode::getID().
Vector<PathNode*> PathGraph::getGlobalNodes () inline
Definition at line 68 of file PathGraph.h.
References pathNodes.
Referenced by PortalLayout::connectFloorMeshGraphs().
PathNode * PathGraph::getNode (int globalNumberID)
Definition at line 82 of file PathGraph.cpp.
References PathNode::getGlobalGraphNodeID(), and pathNodes.
Vector<PathNode*>* PathGraph::getPathNodes () inline
Definition at line 64 of file PathGraph.h.
References pathNodes.
Referenced by CollisionManager::findNearestPathNode(), and FleeStateComponent::getFleeLocation().
void PathGraph::readObject (IffStream * iffStream) virtual
Implements IffTemplate.
Definition at line 18 of file PathGraph.cpp.
References connectNodes(), ecnt, estr, pathNodes, PathNode::readObject(), PathEdge::readObject(), and unkownMetaInt.
Referenced by PortalLayout::parse(), and FloorMesh::parsePGRF().
Member Data Documentation
Vector<int> PathGraph::ecnt private
Definition at line 22 of file PathGraph.h.
Referenced by readObject().
Vector<int> PathGraph::estr private
Definition at line 23 of file PathGraph.h.
Referenced by readObject().
FloorMesh* PathGraph::floorMesh private
Definition at line 25 of file PathGraph.h.
Referenced by getFloorMesh(), and PathGraph().
Vector<PathNode*> PathGraph::pathNodes private
Definition at line 17 of file PathGraph.h.
Referenced by addPathNode(), connectNodes(), findGlobalNode(), findNearestGlobalNode(), findNearestNode(), getGlobalNodes(), getNode(), getPathNodes(), readObject(), and ~PathGraph().
int PathGraph::unkownMetaInt private
Definition at line 20 of file PathGraph.h.
Referenced by PathGraph(), and readObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/PathGraph.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/appearance/PathGraph.cpp