Core3: server::zone::managers::auction::AuctionManager Class Reference
server::zone::managers::auction::AuctionManager Class Reference
#include <AuctionManager.h>
Public Member Functions
AuctionManager (ZoneServer *server)
void initialize ()
void addSaleItem (CreatureObject *player, unsigned long long objectid, SceneObject *vendor, const UnicodeString &description, int price, unsigned int duration, bool auction, bool premium)
AuctionItem * createVendorItem (CreatureObject *player, SceneObject *objectToSell, SceneObject *vendor, const UnicodeString &description, int price, unsigned int duration, bool auction, bool premium)
int checkSaleItem (CreatureObject *player, SceneObject *object, SceneObject *vendor, int price, bool premium)
void getItemAttributes (CreatureObject *player, unsigned long long objectid)
void getData (CreatureObject *player, int extent, unsigned long long vendorObjectID, int screen, unsigned int category, int count, int offset)
void getAuctionData (CreatureObject *player, SceneObject *usedVendor, const String &planet, const String &region, SceneObject *vendor, int screen, unsigned int category, int count, int offset)
int checkRetrieve (CreatureObject *player, unsigned long long objectIdToRetrieve, SceneObject *vendor)
void retrieveItem (CreatureObject *player, unsigned long long objectid, unsigned long long vendorID)
void buyItem (CreatureObject *player, unsigned long long objectid, int price1, int price2)
void doAuctionBid (CreatureObject *player, AuctionItem *item, int price1, int price2)
void doInstantBuy (CreatureObject *player, AuctionItem *item)
int checkBidAuction (CreatureObject *player, AuctionItem *item, int price1, int price2)
void cancelItem (CreatureObject *player, unsigned long long objectID)
AuctionQueryHeadersResponseMessage * fillAuctionQueryHeadersResponseMessage (CreatureObject *player, SceneObject *vendor, TerminalListVector *terminalList, int screen, unsigned int category, int count, int offset)
AuctionsMap * getAuctionMap ()
void checkVendorItems ()
void checkAuctions ()
String getVendorUID (SceneObject *vendor)
void updateVendorUID (SceneObject *vendor, const String &oldUID, const String &newUID)
void updateVendorSearch (SceneObject *vendor, bool enabled)
void expireSale (AuctionItem *item)
void expireBidAuction (AuctionItem *item)
void expireAuction (AuctionItem *item)
void deleteExpiredSale (AuctionItem *item)
bool isMarketEnabled ()
void setMarketEnabled (bool value)
void displayInfo (CreatureObject *player)
void updateAuctionOwner (AuctionItem *item, CreatureObject *player)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int MAXBAZAARPRICE = 20000
static const int MAXSALES = 25
static const int SALESFEE = 20
static const int CHECKEVERY = 60
static const int MAXVENDORPRICE = 99999999
static const int ITEMSPERPAGE = 100
static const int VENDOREXPIREPERIOD = 2592000
static const int COMMODITYEXPIREPERIOD = 604800
Protected Member Functions
AuctionManager (DummyConstructorParameter *param)
virtual ~AuctionManager ()
Friends
class AuctionManagerHelper
Detailed Description
Definition at line 137 of file AuctionManager.h.
Constructor & Destructor Documentation
AuctionManager::AuctionManager (ZoneServer * server)
Definition at line 29 of file AuctionManager.cpp.
References server::zone::managers::auction::AuctionManagerImplementation::_setStub().
AuctionManager::AuctionManager (DummyConstructorParameter * param) protected
Definition at line 36 of file AuctionManager.cpp.
AuctionManager::~AuctionManager () protected virtual
Definition at line 40 of file AuctionManager.cpp.
Member Function Documentation
DistributedObjectServant * AuctionManager::_getImplementation ()
Definition at line 442 of file AuctionManager.cpp.
Referenced by addSaleItem(), buyItem(), cancelItem(), checkAuctions(), checkBidAuction(), checkRetrieve(), checkSaleItem(), checkVendorItems(), createVendorItem(), deleteExpiredSale(), displayInfo(), doAuctionBid(), doInstantBuy(), expireAuction(), expireBidAuction(), expireSale(), fillAuctionQueryHeadersResponseMessage(), getAuctionData(), getAuctionMap(), getData(), getItemAttributes(), getVendorUID(), initialize(), isMarketEnabled(), retrieveItem(), setMarketEnabled(), updateAuctionOwner(), updateVendorSearch(), and updateVendorUID().
DistributedObjectServant * AuctionManager::_getImplementationForRead ()
Definition at line 448 of file AuctionManager.cpp.
void AuctionManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 452 of file AuctionManager.cpp.
void AuctionManager::addSaleItem (CreatureObject * player, unsigned long long objectid, SceneObject * vendor, const UnicodeString & description, int price, unsigned int duration, bool auction, bool premium)
Definition at line 58 of file AuctionManager.cpp.
References _getImplementation(), and server::zone::managers::auction::AuctionManagerImplementation::addSaleItem().
Referenced by CreateImmediateAuctionMessageCallback::run(), and CreateAuctionMessageCallback::run().
void AuctionManager::buyItem (CreatureObject * player, unsigned long long objectid, int price1, int price2)
Definition at line 154 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::buyItem(), and RPC_BUYITEM__CREATUREOBJECT_LONG_INT_INT_.
Referenced by BidAuctionMessageCallback::run().
void AuctionManager::cancelItem (CreatureObject * player, unsigned long long objectID)
Definition at line 220 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::cancelItem(), and RPC_CANCELITEM__CREATUREOBJECT_LONG_.
Referenced by CancelLiveAuctionMessageCallback::run().
void AuctionManager::checkAuctions ()
Definition at line 270 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::checkAuctions(), and RPC_CHECKAUCTIONS__.
int AuctionManager::checkBidAuction (CreatureObject * player, AuctionItem * item, int price1, int price2)
Definition at line 203 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::checkBidAuction(), and RPC_CHECKBIDAUCTION__CREATUREOBJECT_AUCTIONITEM_INT_INT_.
int AuctionManager::checkRetrieve (CreatureObject * player, unsigned long long objectIdToRetrieve, SceneObject * vendor)
Definition at line 129 of file AuctionManager.cpp.
References _getImplementation(), and server::zone::managers::auction::AuctionManagerImplementation::checkRetrieve().
int AuctionManager::checkSaleItem (CreatureObject * player, SceneObject * object, SceneObject * vendor, int price, bool premium)
Definition at line 76 of file AuctionManager.cpp.
References _getImplementation(), and server::zone::managers::auction::AuctionManagerImplementation::checkSaleItem().
void AuctionManager::checkVendorItems ()
Definition at line 257 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::checkVendorItems(), and RPC_CHECKVENDORITEMS__.
AuctionItem * AuctionManager::createVendorItem (CreatureObject * player, SceneObject * objectToSell, SceneObject * vendor, const UnicodeString & description, int price, unsigned int duration, bool auction, bool premium)
Definition at line 67 of file AuctionManager.cpp.
References _getImplementation(), and server::zone::managers::auction::AuctionManagerImplementation::createVendorItem().
void AuctionManager::deleteExpiredSale (AuctionItem * item)
Definition at line 372 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::deleteExpiredSale(), and RPC_DELETEEXPIREDSALE__AUCTIONITEM_.
void AuctionManager::displayInfo (CreatureObject * player)
Definition at line 413 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::displayInfo(), and RPC_DISPLAYINFO__CREATUREOBJECT_.
void AuctionManager::doAuctionBid (CreatureObject * player, AuctionItem * item, int price1, int price2)
Definition at line 171 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), and RPC_DOAUCTIONBID__CREATUREOBJECT_AUCTIONITEM_INT_INT_.
void AuctionManager::doInstantBuy (CreatureObject * player, AuctionItem * item)
Definition at line 188 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), and RPC_DOINSTANTBUY__CREATUREOBJECT_AUCTIONITEM_.
void AuctionManager::expireAuction (AuctionItem * item)
Definition at line 358 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), and RPC_EXPIREAUCTION__AUCTIONITEM_.
void AuctionManager::expireBidAuction (AuctionItem * item)
Definition at line 344 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::expireBidAuction(), and RPC_EXPIREBIDAUCTION__AUCTIONITEM_.
void AuctionManager::expireSale (AuctionItem * item)
Definition at line 330 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::expireSale(), and RPC_EXPIRESALE__AUCTIONITEM_.
AuctionQueryHeadersResponseMessage * AuctionManager::fillAuctionQueryHeadersResponseMessage (CreatureObject * player, SceneObject * vendor, TerminalListVector * terminalList, int screen, unsigned int category, int count, int offset)
Definition at line 235 of file AuctionManager.cpp.
References _getImplementation(), and server::zone::managers::auction::AuctionManagerImplementation::fillAuctionQueryHeadersResponseMessage().
void AuctionManager::getAuctionData (CreatureObject * player, SceneObject * usedVendor, const String & planet, const String & region, SceneObject * vendor, int screen, unsigned int category, int count, int offset)
Definition at line 120 of file AuctionManager.cpp.
References _getImplementation(), and server::zone::managers::auction::AuctionManagerImplementation::getAuctionData().
AuctionsMap * AuctionManager::getAuctionMap ()
Definition at line 244 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::getAuctionMap(), and RPC_GETAUCTIONMAP__.
void AuctionManager::getData (CreatureObject * player, int extent, unsigned long long vendorObjectID, int screen, unsigned int category, int count, int offset)
Definition at line 100 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::getData(), and RPC_GETDATA__CREATUREOBJECT_INT_LONG_INT_INT_INT_INT_.
Referenced by AuctionQueryHeadersMessageCallback::run().
void AuctionManager::getItemAttributes (CreatureObject * player, unsigned long long objectid)
Definition at line 85 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::getItemAttributes(), and RPC_GETITEMATTRIBUTES__CREATUREOBJECT_LONG_.
Referenced by GetAuctionDetailsCallback::run().
String AuctionManager::getVendorUID (SceneObject * vendor)
Definition at line 283 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::getVendorUID(), and RPC_GETVENDORUID__SCENEOBJECT_.
void AuctionManager::initialize ()
Definition at line 45 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::initialize(), and RPC_INITIALIZE__.
bool AuctionManager::isMarketEnabled ()
Definition at line 386 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::isMarketEnabled(), and RPC_ISMARKETENABLED__.
Referenced by IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage().
void AuctionManager::retrieveItem (CreatureObject * player, unsigned long long objectid, unsigned long long vendorID)
Definition at line 138 of file AuctionManager.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionManagerImplementation::retrieveItem(), and RPC_RETRIEVEITEM__CREATUREOBJECT_LONG_LONG_.
Referenced by RetrieveAuctionItemMessageCallback::run().
void AuctionManager::setMarketEnabled (bool value)
Definition at line 399 of file AuctionManager.cpp.
References _getImplementation(), RPC_SETMARKETENABLED__BOOL_, and server::zone::managers::auction::AuctionManagerImplementation::setMarketEnabled().
void AuctionManager::updateAuctionOwner (AuctionItem * item, CreatureObject * player)
Definition at line 427 of file AuctionManager.cpp.
References _getImplementation(), RPC_UPDATEAUCTIONOWNER__AUCTIONITEM_CREATUREOBJECT_, and server::zone::managers::auction::AuctionManagerImplementation::updateAuctionOwner().
void AuctionManager::updateVendorSearch (SceneObject * vendor, bool enabled)
Definition at line 315 of file AuctionManager.cpp.
References _getImplementation(), RPC_UPDATEVENDORSEARCH__SCENEOBJECT_BOOL_, and server::zone::managers::auction::AuctionManagerImplementation::updateVendorSearch().
void AuctionManager::updateVendorUID (SceneObject * vendor, const String & oldUID, const String & newUID)
Definition at line 299 of file AuctionManager.cpp.
References _getImplementation(), RPC_UPDATEVENDORUID__SCENEOBJECT_STRING_STRING_, and server::zone::managers::auction::AuctionManagerImplementation::updateVendorUID().
Friends And Related Function Documentation
friend class AuctionManagerHelper friend
Definition at line 225 of file AuctionManager.h.
Member Data Documentation
const int server::zone::managers::auction::AuctionManager::CHECKEVERY = 60 static
Definition at line 145 of file AuctionManager.h.
const int server::zone::managers::auction::AuctionManager::COMMODITYEXPIREPERIOD = 604800 static
Definition at line 153 of file AuctionManager.h.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::cancelItem(), server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), server::zone::managers::auction::AuctionManagerImplementation::expireAuction(), server::zone::managers::auction::AuctionManagerImplementation::expireBidAuction(), and server::zone::managers::auction::AuctionManagerImplementation::expireSale().
const int server::zone::managers::auction::AuctionManager::ITEMSPERPAGE = 100 static
Definition at line 149 of file AuctionManager.h.
const int server::zone::managers::auction::AuctionManager::MAXBAZAARPRICE = 20000 static
Definition at line 139 of file AuctionManager.h.
const int server::zone::managers::auction::AuctionManager::MAXSALES = 25 static
Definition at line 141 of file AuctionManager.h.
const int server::zone::managers::auction::AuctionManager::MAXVENDORPRICE = 99999999 static
Definition at line 147 of file AuctionManager.h.
const int server::zone::managers::auction::AuctionManager::SALESFEE = 20 static
Definition at line 143 of file AuctionManager.h.
const int server::zone::managers::auction::AuctionManager::VENDOREXPIREPERIOD = 2592000 static
Definition at line 151 of file AuctionManager.h.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::cancelItem(), server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), server::zone::managers::auction::AuctionManagerImplementation::expireBidAuction(), and server::zone::managers::auction::AuctionManagerImplementation::expireSale().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionManager.cpp