Core3: server::zone::objects::player::sessions::CitySpecializationSessionImplementation Class Reference
server::zone::objects::player::sessions::CitySpecializationSessionImplementation Class Reference
#include <CitySpecializationSession.h>
Public Member Functions
CitySpecializationSessionImplementation (CreatureObject *creature, CityRegion *city, SceneObject *terminal=NULL)
CitySpecializationSessionImplementation (DummyConstructorParameter *param)
int initializeSession ()
int sendConfirmationBox (const String &choice)
int acceptChoice ()
int cancelSession ()
int clearSession ()
operator const CitySpecializationSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< CitySpecializationSession * > _this
Protected Member Functions
virtual ~CitySpecializationSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference
< CreatureObject * > creatureObject
ManagedReference< CityRegion * > cityRegion
ManagedReference< SceneObject * > terminalObject
String specialization
Friends
class CitySpecializationSession
Detailed Description
Definition at line 121 of file CitySpecializationSession.h.
Constructor & Destructor Documentation
CitySpecializationSessionImplementation::CitySpecializationSessionImplementation (CreatureObject * creature, CityRegion * city, SceneObject * terminal = NULL)
Definition at line 283 of file CitySpecializationSession.cpp.
References _initializeImplementation(), cityRegion, creatureObject, and terminalObject.
CitySpecializationSessionImplementation::CitySpecializationSessionImplementation (DummyConstructorParameter * param)
Definition at line 121 of file CitySpecializationSession.cpp.
References _initializeImplementation().
CitySpecializationSessionImplementation::~CitySpecializationSessionImplementation () protected virtual
Definition at line 126 of file CitySpecializationSession.cpp.
Member Function Documentation
DistributedObjectStub * CitySpecializationSessionImplementation::_getStub ()
Definition at line 146 of file CitySpecializationSession.cpp.
References _this.
void CitySpecializationSessionImplementation::_initializeImplementation () protected
Definition at line 133 of file CitySpecializationSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CitySpecializationSessionImplementation().
void CitySpecializationSessionImplementation::_serializationHelperMethod () protected
Definition at line 182 of file CitySpecializationSession.cpp.
Referenced by _initializeImplementation().
void CitySpecializationSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 141 of file CitySpecializationSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::CitySpecializationSession::CitySpecializationSession().
int CitySpecializationSessionImplementation::acceptChoice ()
Definition at line 82 of file CitySpecializationSessionImplementation.cpp.
References cancelSession(), server::zone::managers::city::CityManager::changeCitySpecialization(), cityRegion, creatureObject, and specialization.
Referenced by server::zone::objects::player::sessions::CitySpecializationSession::acceptChoice().
int CitySpecializationSessionImplementation::cancelSession ()
Definition at line 297 of file CitySpecializationSession.cpp.
References SessionFacadeType::CITYSPEC, and creatureObject.
Referenced by acceptChoice(), server::zone::objects::player::sessions::CitySpecializationSession::cancelSession(), initializeSession(), and sendConfirmationBox().
int CitySpecializationSessionImplementation::clearSession ()
Definition at line 304 of file CitySpecializationSession.cpp.
Referenced by server::zone::objects::player::sessions::CitySpecializationSession::clearSession().
void CitySpecializationSessionImplementation::finalize () protected
Definition at line 130 of file CitySpecializationSession.cpp.
int CitySpecializationSessionImplementation::initializeSession ()
Definition at line 22 of file CitySpecializationSessionImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), cancelSession(), SuiWindowType::CITY_SPEC, cityRegion, creatureObject, server::zone::objects::scene::variables::DeltaVector< E >::get(), server::zone::objects::player::PlayerObject::getAbilityList(), Ability::getAbilityName(), server::zone::objects::scene::variables::DeltaVector< E >::size(), and terminalObject.
Referenced by server::zone::objects::player::sessions::CitySpecializationSession::initializeSession().
void CitySpecializationSessionImplementation::lock (bool doLock = true) protected
Definition at line 154 of file CitySpecializationSession.cpp.
References _this.
void CitySpecializationSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 158 of file CitySpecializationSession.cpp.
References _this.
CitySpecializationSessionImplementation::operator const CitySpecializationSession * ()
Definition at line 150 of file CitySpecializationSession.cpp.
void CitySpecializationSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 189 of file CitySpecializationSession.cpp.
References readObjectMember().
bool CitySpecializationSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 208 of file CitySpecializationSession.cpp.
References cityRegion, creatureObject, specialization, and terminalObject.
Referenced by readObject().
void CitySpecializationSessionImplementation::rlock (bool doLock = true) protected
Definition at line 162 of file CitySpecializationSession.cpp.
References _this.
void CitySpecializationSessionImplementation::runlock (bool doLock = true) protected
Definition at line 178 of file CitySpecializationSession.cpp.
References _this.
int CitySpecializationSessionImplementation::sendConfirmationBox (const String & choice)
Definition at line 61 of file CitySpecializationSessionImplementation.cpp.
References server::zone::objects::player::PlayerObject::addSuiBox(), cancelSession(), SuiWindowType::CITY_SPEC_CONFIRM, creatureObject, server::zone::objects::player::sui::messagebox::SuiMessageBox::generateMessage(), server::zone::objects::player::sui::SuiBox::setCallback(), server::zone::objects::player::sui::SuiBox::setCancelButton(), server::zone::objects::player::sui::SuiBox::setOkButton(), server::zone::objects::player::sui::SuiBox::setPromptText(), server::zone::objects::player::sui::SuiBox::setPromptTitle(), and specialization.
Referenced by server::zone::objects::player::sessions::CitySpecializationSession::sendConfirmationBox().
void CitySpecializationSessionImplementation::unlock (bool doLock = true) protected
Definition at line 174 of file CitySpecializationSession.cpp.
References _this.
void CitySpecializationSessionImplementation::wlock (bool doLock = true) protected
Definition at line 166 of file CitySpecializationSession.cpp.
References _this.
void CitySpecializationSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 170 of file CitySpecializationSession.cpp.
References _this.
void CitySpecializationSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 234 of file CitySpecializationSession.cpp.
References writeObjectMembers().
int CitySpecializationSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 241 of file CitySpecializationSession.cpp.
References cityRegion, creatureObject, specialization, and terminalObject.
Referenced by writeObject().
Friends And Related Function Documentation
friend class CitySpecializationSession friend
Definition at line 180 of file CitySpecializationSession.h.
Member Data Documentation
WeakReference<CitySpecializationSession*> server::zone::objects::player::sessions::CitySpecializationSessionImplementation::_this
Definition at line 146 of file CitySpecializationSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedReference<CityRegion* > server::zone::objects::player::sessions::CitySpecializationSessionImplementation::cityRegion protected
Definition at line 125 of file CitySpecializationSession.h.
Referenced by acceptChoice(), CitySpecializationSessionImplementation(), initializeSession(), readObjectMember(), and writeObjectMembers().
ManagedReference<CreatureObject* > server::zone::objects::player::sessions::CitySpecializationSessionImplementation::creatureObject protected
Definition at line 123 of file CitySpecializationSession.h.
Referenced by acceptChoice(), cancelSession(), CitySpecializationSessionImplementation(), initializeSession(), readObjectMember(), sendConfirmationBox(), and writeObjectMembers().
String server::zone::objects::player::sessions::CitySpecializationSessionImplementation::specialization protected
Definition at line 129 of file CitySpecializationSession.h.
Referenced by acceptChoice(), readObjectMember(), sendConfirmationBox(), and writeObjectMembers().
ManagedReference<SceneObject* > server::zone::objects::player::sessions::CitySpecializationSessionImplementation::terminalObject protected
Definition at line 127 of file CitySpecializationSession.h.
Referenced by CitySpecializationSessionImplementation(), initializeSession(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CitySpecializationSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CitySpecializationSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CitySpecializationSessionImplementation.cpp