Core3: server::login::account::AccountAdapter Class Reference
server::login::account::AccountAdapter Class Reference
#include <Account.h>
Public Member Functions
AccountAdapter (Account *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void setActive (bool act)
void setAccountID (unsigned int accountid)
void setStationID (unsigned int stationid)
void setAdminLevel (unsigned int adminlvl)
void setUsername (const String &usern)
void setBanExpires (unsigned int expires)
void setBanReason (const String &reason)
void setSalt (const String &s)
void setBanAdmin (unsigned int value)
unsigned int getBanAdmin ()
void setTimeCreated (unsigned int seconds)
bool isActive ()
unsigned int getAccountID ()
unsigned int getStationID ()
unsigned int getAdminLevel ()
String getUsername ()
String getSalt ()
unsigned int getTimeCreated ()
void updateFromDatabase ()
void updateAccount ()
void updateCharacters ()
void updateGalaxyBans ()
unsigned int getBanExpires ()
String getBanReason ()
bool isBanned ()
Detailed Description
Definition at line 263 of file Account.h.
Constructor & Destructor Documentation
AccountAdapter::AccountAdapter (Account * impl)
Definition at line 641 of file Account.cpp.
Member Function Documentation
unsigned int AccountAdapter::getAccountID ()
Definition at line 829 of file Account.cpp.
Referenced by invokeMethod().
unsigned int AccountAdapter::getAdminLevel ()
Definition at line 837 of file Account.cpp.
Referenced by invokeMethod().
unsigned int AccountAdapter::getBanAdmin ()
Definition at line 817 of file Account.cpp.
Referenced by invokeMethod().
unsigned int AccountAdapter::getBanExpires ()
Definition at line 869 of file Account.cpp.
Referenced by invokeMethod().
String AccountAdapter::getBanReason ()
Definition at line 873 of file Account.cpp.
Referenced by invokeMethod().
String AccountAdapter::getSalt ()
Definition at line 845 of file Account.cpp.
Referenced by invokeMethod().
unsigned int AccountAdapter::getStationID ()
Definition at line 833 of file Account.cpp.
Referenced by invokeMethod().
unsigned int AccountAdapter::getTimeCreated ()
Definition at line 849 of file Account.cpp.
Referenced by invokeMethod().
String AccountAdapter::getUsername ()
Definition at line 841 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 644 of file Account.cpp.
References getAccountID(), getAdminLevel(), getBanAdmin(), getBanExpires(), getBanReason(), getSalt(), getStationID(), getTimeCreated(), getUsername(), isActive(), isBanned(), RPC_GETACCOUNTID__, RPC_GETADMINLEVEL__, RPC_GETBANADMIN__, RPC_GETBANEXPIRES__, RPC_GETBANREASON__, RPC_GETSALT__, RPC_GETSTATIONID__, RPC_GETTIMECREATED__, RPC_GETUSERNAME__, RPC_ISACTIVE__, RPC_ISBANNED__, RPC_SETACCOUNTID__INT_, RPC_SETACTIVE__BOOL_, RPC_SETADMINLEVEL__INT_, RPC_SETBANADMIN__INT_, RPC_SETBANEXPIRES__INT_, RPC_SETBANREASON__STRING_, RPC_SETSALT__STRING_, RPC_SETSTATIONID__INT_, RPC_SETTIMECREATED__INT_, RPC_SETUSERNAME__STRING_, RPC_UPDATEACCOUNT__, RPC_UPDATECHARACTERS__, RPC_UPDATEFROMDATABASE__, RPC_UPDATEGALAXYBANS__, setAccountID(), setActive(), setAdminLevel(), setBanAdmin(), setBanExpires(), setBanReason(), setSalt(), setStationID(), setTimeCreated(), setUsername(), updateAccount(), updateCharacters(), updateFromDatabase(), and updateGalaxyBans().
bool AccountAdapter::isActive ()
Definition at line 825 of file Account.cpp.
Referenced by invokeMethod().
bool AccountAdapter::isBanned ()
Definition at line 877 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::setAccountID (unsigned int accountid)
Definition at line 785 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::setActive (bool act)
Definition at line 781 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::setAdminLevel (unsigned int adminlvl)
Definition at line 793 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::setBanAdmin (unsigned int value)
Definition at line 813 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::setBanExpires (unsigned int expires)
Definition at line 801 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::setBanReason (const String & reason)
Definition at line 805 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::setSalt (const String & s)
Definition at line 809 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::setStationID (unsigned int stationid)
Definition at line 789 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::setTimeCreated (unsigned int seconds)
Definition at line 821 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::setUsername (const String & usern)
Definition at line 797 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::updateAccount ()
Definition at line 857 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::updateCharacters ()
Definition at line 861 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::updateFromDatabase ()
Definition at line 853 of file Account.cpp.
Referenced by invokeMethod().
void AccountAdapter::updateGalaxyBans ()
Definition at line 865 of file Account.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/account/Account.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/account/Account.cpp