Core3: SchematicMap Class Reference
SchematicMap Class Reference
#include <SchematicMap.h>
Public Member Functions
SchematicMap ()
~SchematicMap ()
void initialize (ZoneServer *server)
void loadDraftSchematicDatabase ()
bool addSchematics (PlayerObject *playerObject, Vector< String > schematicgroups, bool updateClient)
void removeSchematics (PlayerObject *playerObject, Vector< String > schematicgroups, bool updateClient)
void sendDraftSlotsTo (CreatureObject *player, uint32 schematicID)
void sendResourceWeightsTo (CreatureObject *player, uint32 schematicID)
DraftSchematic * get (uint32 schemid)
Private Member Functions
void loadSchematicGroups ()
void loadDraftSchematicFile ()
void buildSchematicGroups ()
Private Attributes
VectorMap< uint32,
ManagedReference
< DraftSchematic * > > schematicCrcMap
VectorMap< String,
DraftSchematicGroup * > groupMap
ManagedReference< ZoneServer * > zoneServer
ObjectManager * objectManager
VectorMap< uint32, String > iffGroupMap
Detailed Description
Definition at line 63 of file SchematicMap.h.
Constructor & Destructor Documentation
SchematicMap::SchematicMap ()
Definition at line 60 of file SchematicMap.cpp.
References groupMap, and iffGroupMap.
SchematicMap::~SchematicMap ()
Definition at line 70 of file SchematicMap.cpp.
References groupMap.
Member Function Documentation
bool SchematicMap::addSchematics (PlayerObject * playerObject, Vector< String > schematicgroups, bool updateClient)
Definition at line 221 of file SchematicMap.cpp.
References server::zone::objects::player::PlayerObject::addSchematics(), and groupMap.
void SchematicMap::buildSchematicGroups () private
Definition at line 196 of file SchematicMap.cpp.
References DraftSchematicGroup::contains(), groupMap, iffGroupMap, schematicCrcMap, and server::zone::objects::draftschematic::DraftSchematic::setGroupName().
Referenced by loadSchematicGroups().
DraftSchematic* SchematicMap::get (uint32 schemid) inline
Definition at line 89 of file SchematicMap.h.
References schematicCrcMap.
void SchematicMap::initialize (ZoneServer * server)
Definition at line 75 of file SchematicMap.cpp.
References loadDraftSchematicDatabase(), loadDraftSchematicFile(), loadSchematicGroups(), objectManager, and zoneServer.
void SchematicMap::loadDraftSchematicDatabase ()
Definition at line 113 of file SchematicMap.cpp.
References schematicCrcMap, and zoneServer.
Referenced by initialize().
void SchematicMap::loadDraftSchematicFile () private
Definition at line 141 of file SchematicMap.cpp.
References server::zone::managers::object::ObjectManager::createObject(), objectManager, and schematicCrcMap.
Referenced by initialize().
void SchematicMap::loadSchematicGroups () private
Definition at line 84 of file SchematicMap.cpp.
References buildSchematicGroups(), DataTableRow::getCell(), DataTableIff::getRow(), DataTableIff::getTotalRows(), DataTableCell::getValue(), iffGroupMap, TemplateManager::openIffFile(), and DataTableIff::readObject().
Referenced by initialize().
void SchematicMap::removeSchematics (PlayerObject * playerObject, Vector< String > schematicgroups, bool updateClient)
Definition at line 245 of file SchematicMap.cpp.
References groupMap, and server::zone::objects::player::PlayerObject::removeSchematics().
void SchematicMap::sendDraftSlotsTo (CreatureObject * player, uint32 schematicID)
The client doesn't display correctly all the time If these aren't sent twice..... no idea why
Definition at line 267 of file SchematicMap.cpp.
References schematicCrcMap.
void SchematicMap::sendResourceWeightsTo (CreatureObject * player, uint32 schematicID)
Definition at line 279 of file SchematicMap.cpp.
References schematicCrcMap.
Member Data Documentation
VectorMap<String, DraftSchematicGroup* > SchematicMap::groupMap private
Definition at line 66 of file SchematicMap.h.
Referenced by addSchematics(), buildSchematicGroups(), removeSchematics(), SchematicMap(), and ~SchematicMap().
VectorMap<uint32, String> SchematicMap::iffGroupMap private
Definition at line 70 of file SchematicMap.h.
Referenced by buildSchematicGroups(), loadSchematicGroups(), and SchematicMap().
ObjectManager* SchematicMap::objectManager private
Definition at line 68 of file SchematicMap.h.
Referenced by initialize(), and loadDraftSchematicFile().
VectorMap<uint32, ManagedReference<DraftSchematic* > > SchematicMap::schematicCrcMap private
Definition at line 65 of file SchematicMap.h.
Referenced by buildSchematicGroups(), get(), loadDraftSchematicDatabase(), loadDraftSchematicFile(), sendDraftSlotsTo(), and sendResourceWeightsTo().
ManagedReference<ZoneServer*> SchematicMap::zoneServer private
Definition at line 67 of file SchematicMap.h.
Referenced by initialize(), and loadDraftSchematicDatabase().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/schematicmap/SchematicMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/schematicmap/SchematicMap.cpp