Core3: DataTableIff Class Reference
DataTableIff Class Reference
#include <DataTableIff.h>
Public Member Functions
DataTableIff ()
~DataTableIff ()
void readObject (IffStream *iffStream)
void clearDataTable ()
Vector< DataTableRow * > getRowsByColumn (int columnIdx, const String &columnValue)
String getColumnNameByIndex (int idx) const
int getColumnIndexByName (const String &name)
DataTableRow * getRow (int idx)
int getTotalRows ()
int getTotalColumns ()
Public Member Functions inherited from IffTemplate
virtual ~IffTemplate ()
Public Member Functions inherited from TemplateData
virtual ~TemplateData ()
Private Attributes
Vector< String > columns
Vector< byte > columnTypes
Vector< DataTableRow * > rows
Detailed Description
Definition at line 16 of file DataTableIff.h.
Constructor & Destructor Documentation
DataTableIff::DataTableIff ()
Definition at line 12 of file DataTableIff.cpp.
DataTableIff::~DataTableIff ()
Definition at line 16 of file DataTableIff.cpp.
References clearDataTable().
Member Function Documentation
void DataTableIff::clearDataTable ()
Definition at line 20 of file DataTableIff.cpp.
References columns, columnTypes, and rows.
Referenced by ~DataTableIff().
int DataTableIff::getColumnIndexByName (const String & name) inline
Returns the index of the column with the header name passed.
Parameters
name The name of the column header to retrieve the index of.
Returns
The index of the column, or -1 if it wasn't found.
Definition at line 51 of file DataTableIff.h.
References columns.
String DataTableIff::getColumnNameByIndex (int idx) const inline
Returns the column header name based on the column index.
Parameters
idx The index of the column to retrieve the header name for.
Returns
Returns the header name as a String.
Definition at line 42 of file DataTableIff.h.
References columns.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadTravelFares().
DataTableRow* DataTableIff::getRow (int idx) inline
Definition at line 60 of file DataTableIff.h.
References rows.
Referenced by ResourceTree::buildTreeFromClient(), CustomizationIdManager::loadAllowBald(), server::zone::managers::player::PlayerManagerImplementation::loadBadgeMap(), server::zone::managers::skill::SkillManager::loadClientData(), server::zone::managers::planet::PlanetManagerImplementation::loadClientRegions(), server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), ImageDesignManager::loadCustomizationData(), CustomizationIdManager::loadHairAssetsSkillMods(), CreaturePosture::loadMovementData(), CustomizationIdManager::loadPaletteColumns(), PerformanceManager::loadPerformances(), TemplateManager::loadPlanetMapCategories(), server::zone::managers::player::creation::PlayerCreationManager::loadProfessionDefaultsInfo(), server::zone::managers::player::creation::PlayerCreationManager::loadRacialCreationData(), SchematicMap::loadSchematicGroups(), CreatureState::loadStateData(), server::zone::managers::planet::PlanetManagerImplementation::loadTravelFares(), server::zone::managers::skill::SkillManager::loadXpLimits(), StartingLocationList::parseFromIffStream(), FactionRanks::readObject(), and ClientPoiDataTable::readObject().
Vector< DataTableRow * > DataTableIff::getRowsByColumn (int columnIdx, const String & columnValue)
Returns a collection of rows whose column specified by the column index matches the specified column value.
Parameters
columnIdx Which column to lookup.
columnValue What value should be compared.
Returns
Returns a collection of DataTableRow objects.
Definition at line 116 of file DataTableIff.cpp.
References DataTableRow::getCell(), rows, and DataTableCell::toString().
Referenced by server::zone::managers::player::creation::PlayerCreationManager::loadRacialCreationData().
int DataTableIff::getTotalColumns () inline
Definition at line 68 of file DataTableIff.h.
References columns.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::loadTravelFares().
int DataTableIff::getTotalRows () inline
Definition at line 64 of file DataTableIff.h.
References rows.
Referenced by ResourceTree::buildTreeFromClient(), CustomizationIdManager::loadAllowBald(), server::zone::managers::player::PlayerManagerImplementation::loadBadgeMap(), server::zone::managers::skill::SkillManager::loadClientData(), server::zone::managers::planet::PlanetManagerImplementation::loadClientRegions(), server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), ImageDesignManager::loadCustomizationData(), CustomizationIdManager::loadHairAssetsSkillMods(), CreaturePosture::loadMovementData(), CustomizationIdManager::loadPaletteColumns(), PerformanceManager::loadPerformances(), TemplateManager::loadPlanetMapCategories(), server::zone::managers::player::creation::PlayerCreationManager::loadProfessionDefaultsInfo(), server::zone::managers::player::creation::PlayerCreationManager::loadRacialCreationData(), SchematicMap::loadSchematicGroups(), CreatureState::loadStateData(), server::zone::managers::planet::PlanetManagerImplementation::loadTravelFares(), server::zone::managers::skill::SkillManager::loadXpLimits(), StartingLocationList::parseFromIffStream(), FactionRanks::readObject(), and ClientPoiDataTable::readObject().
void DataTableIff::readObject (IffStream * iffStream) virtual
Implements IffTemplate.
Definition at line 32 of file DataTableIff.cpp.
References DataTableRow::addCell(), columns, columnTypes, DataTableCell::parse(), and rows.
Referenced by ResourceTree::buildTreeFromClient(), CustomizationIdManager::loadAllowBald(), server::zone::managers::player::PlayerManagerImplementation::loadBadgeMap(), server::zone::managers::skill::SkillManager::loadClientData(), server::zone::managers::planet::PlanetManagerImplementation::loadClientPoiData(), server::zone::managers::planet::PlanetManagerImplementation::loadClientRegions(), server::zone::managers::objectcontroller::command::CommandConfigManager::loadCommandData(), ImageDesignManager::loadCustomizationData(), FactionManager::loadFactionRanks(), CustomizationIdManager::loadHairAssetsSkillMods(), CreaturePosture::loadMovementData(), CustomizationIdManager::loadPaletteColumns(), PerformanceManager::loadPerformances(), TemplateManager::loadPlanetMapCategories(), server::zone::managers::player::creation::PlayerCreationManager::loadProfessionDefaultsInfo(), server::zone::managers::player::creation::PlayerCreationManager::loadRacialCreationData(), SchematicMap::loadSchematicGroups(), CreatureState::loadStateData(), server::zone::managers::planet::PlanetManagerImplementation::loadTravelFares(), server::zone::managers::skill::SkillManager::loadXpLimits(), and StartingLocationList::parseFromIffStream().
Member Data Documentation
Vector<String> DataTableIff::columns private
Definition at line 17 of file DataTableIff.h.
Referenced by clearDataTable(), getColumnIndexByName(), getColumnNameByIndex(), getTotalColumns(), and readObject().
Vector<byte> DataTableIff::columnTypes private
Definition at line 18 of file DataTableIff.h.
Referenced by clearDataTable(), and readObject().
Vector<DataTableRow*> DataTableIff::rows private
Definition at line 19 of file DataTableIff.h.
Referenced by clearDataTable(), getRow(), getRowsByColumn(), getTotalRows(), and readObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/datatables/DataTableIff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/datatables/DataTableIff.cpp