Core3: server::chat::ChatManager Class Reference
server::chat::ChatManager Class Reference
#include <ChatManager.h>
Public Member Functions
ChatManager (ZoneServer *serv, int initsize)
void initiateRooms ()
void initiatePlanetRooms ()
void destroyRooms ()
ChatRoom * createRoom (const String &roomName, ChatRoom *parent=NULL)
void addRoom (ChatRoom *channel)
void removeRoom (ChatRoom *channel)
void populateRoomListMessage (ChatRoom *channel, ChatRoomList *msg)
void sendRoomList (CreatureObject *player)
void addPlayer (CreatureObject *player)
CreatureObject * getPlayer (const String &name)
CreatureObject * removePlayer (const String &name)
void broadcastMessage (BaseMessage *message)
void broadcastMessage (CreatureObject *player, const UnicodeString &message, unsigned long long target=0, unsigned int moodid=0, unsigned int mood2=0)
void handleSpatialChatInternalMessage (CreatureObject *player, const UnicodeString &args)
void handleGroupChat (CreatureObject *player, const UnicodeString &message)
void handleGuildChat (CreatureObject *player, const UnicodeString &message)
void handlePlanetChat (CreatureObject *player, const UnicodeString &message)
ChatRoom * createRoomByFullPath (const String &path)
ChatRoom * getChatRoomByFullPath (const String &path)
ChatRoom * getChatRoomByGamePath (ChatRoom *game, const String &path)
void handleChatRoomMessage (CreatureObject *sender, const UnicodeString &message, unsigned int roomID, unsigned int counter)
void handleChatEnterRoomById (CreatureObject *player, unsigned int counter, unsigned int roomID)
void handleSocialInternalMessage (CreatureObject *sender, const UnicodeString &arguments)
void handleChatInstantMessageToCharacter (ChatInstantMessageToCharacter *message)
void destroyRoom (ChatRoom *room)
ChatRoom * createGroupRoom (unsigned long long groupID, CreatureObject *creator)
void loadMail (CreatureObject *player)
void sendMail (const String &sendername, const UnicodeString &header, const UnicodeString &body, const String &name)
int sendMail (const String &sendername, const UnicodeString &subject, StringIdChatParameter &body, const String &recipientName, WaypointObject *waypoint=NULL)
int sendMail (const String &sendername, const UnicodeString &subject, const UnicodeString &body, const String &recipientName, StringIdChatParameterVector *stringIdParameters, WaypointChatParameterVector *waypointParameters)
void handleRequestPersistentMsg (CreatureObject *player, unsigned int mailID)
void deletePersistentMessage (CreatureObject *player, unsigned int mailID)
void broadcastGalaxy (CreatureObject *player, const String &message)
void broadcastGalaxy (const String &message, const String &faction)
void setPlayerManager (PlayerManager *manager)
ChatRoom * getChatRoom (unsigned int id)
ChatRoom * getGameRoom (const String &game)
unsigned int getNextRoomID ()
int getPlayerCount ()
PlayerMap * getPlayerMap ()
ChatRoom * getGuildRoom ()
ChatRoom * getGroupRoom ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int IM_SUCCESS = 0x00
static const int IM_OFFLINE = 0x04
static const int IM_IGNORED = 0x09
static const int IM_TOOLONG = 0x10
static const int IM_MAXSIZE = 255
static const int PM_MAXSIZE = 4000
Protected Member Functions
ChatManager (DummyConstructorParameter *param)
virtual ~ChatManager ()
Friends
class ChatManagerHelper
Detailed Description
Definition at line 181 of file ChatManager.h.
Constructor & Destructor Documentation
ChatManager::ChatManager (ZoneServer * serv, int initsize)
Definition at line 35 of file ChatManager.cpp.
References server::chat::ChatManagerImplementation::_setStub().
ChatManager::ChatManager (DummyConstructorParameter * param) protected
Definition at line 42 of file ChatManager.cpp.
ChatManager::~ChatManager () protected virtual
Definition at line 46 of file ChatManager.cpp.
Member Function Documentation
DistributedObjectServant * ChatManager::_getImplementation ()
Definition at line 637 of file ChatManager.cpp.
Referenced by addPlayer(), addRoom(), broadcastGalaxy(), broadcastMessage(), createGroupRoom(), createRoom(), createRoomByFullPath(), deletePersistentMessage(), destroyRoom(), destroyRooms(), getChatRoom(), getChatRoomByFullPath(), getChatRoomByGamePath(), getGameRoom(), getGroupRoom(), getGuildRoom(), getNextRoomID(), getPlayer(), getPlayerCount(), getPlayerMap(), handleChatEnterRoomById(), handleChatInstantMessageToCharacter(), handleChatRoomMessage(), handleGroupChat(), handleGuildChat(), handlePlanetChat(), handleRequestPersistentMsg(), handleSocialInternalMessage(), handleSpatialChatInternalMessage(), initiatePlanetRooms(), initiateRooms(), loadMail(), populateRoomListMessage(), removePlayer(), removeRoom(), sendMail(), sendRoomList(), and setPlayerManager().
DistributedObjectServant * ChatManager::_getImplementationForRead ()
Definition at line 643 of file ChatManager.cpp.
void ChatManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 647 of file ChatManager.cpp.
void ChatManager::addPlayer (CreatureObject * player)
Definition at line 162 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::addPlayer(), and RPC_ADDPLAYER__CREATUREOBJECT_.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), and SelectCharacterCallback::run().
void ChatManager::addRoom (ChatRoom * channel)
Definition at line 105 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::addRoom(), and RPC_ADDROOM__CHATROOM_.
void ChatManager::broadcastGalaxy (CreatureObject * player, const String & message)
Definition at line 504 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::broadcastGalaxy(), and RPC_BROADCASTGALAXY__CREATUREOBJECT_STRING_.
Referenced by BroadcastCommand::doQueueCommand(), BroadcastGalaxyCommand::doQueueCommand(), ServerCore::handleCommands(), and server::zone::ZoneServerImplementation::timedShutdown().
void ChatManager::broadcastGalaxy (const String & message, const String & faction)
Definition at line 519 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::broadcastGalaxy(), and RPC_BROADCASTGALAXY__STRING_STRING_.
void ChatManager::broadcastMessage (BaseMessage * message)
Definition at line 204 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::broadcastMessage(), and RPC_BROADCASTMESSAGE__BASEMESSAGE_.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), GiveItemCommand::doQueueCommand(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetReceivesDamage(), server::zone::managers::player::PlayerManagerImplementation::resendLoginMessageToAll(), server::zone::managers::director::DirectorManager::spatialChat(), and server::zone::managers::director::DirectorManager::spatialMoodChat().
void ChatManager::broadcastMessage (CreatureObject * player, const UnicodeString & message, unsigned long long target = 0, unsigned int moodid = 0, unsigned int mood2 = 0)
Definition at line 218 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::broadcastMessage(), and RPC_BROADCASTMESSAGE__CREATUREOBJECT_UNICODESTRING_LONG_INT_INT_.
ChatRoom * ChatManager::createGroupRoom (unsigned long long groupID, CreatureObject * creator)
Definition at line 410 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::createGroupRoom(), and RPC_CREATEGROUPROOM__LONG_CREATUREOBJECT_.
ChatRoom * ChatManager::createRoom (const String & roomName, ChatRoom * parent = NULL)
Definition at line 90 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::createRoom(), and RPC_CREATEROOM__STRING_CHATROOM_.
ChatRoom * ChatManager::createRoomByFullPath (const String & path)
Definition at line 296 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::createRoomByFullPath(), and RPC_CREATEROOMBYFULLPATH__STRING_.
void ChatManager::deletePersistentMessage (CreatureObject * player, unsigned int mailID)
Definition at line 489 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::deletePersistentMessage(), and RPC_DELETEPERSISTENTMESSAGE__CREATUREOBJECT_INT_.
Referenced by ChatDeletePersistentMessageCallback::run().
void ChatManager::destroyRoom (ChatRoom * room)
Definition at line 396 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::destroyRoom(), and RPC_DESTROYROOM__CHATROOM_.
Referenced by server::zone::objects::group::GroupObjectImplementation::destroyChatRoom().
void ChatManager::destroyRooms ()
Definition at line 77 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::destroyRooms(), and RPC_DESTROYROOMS__.
ChatRoom * ChatManager::getChatRoom (unsigned int id)
Definition at line 548 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::getChatRoom(), and RPC_GETCHATROOM__INT_.
ChatRoom * ChatManager::getChatRoomByFullPath (const String & path)
Definition at line 310 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::getChatRoomByFullPath(), and RPC_GETCHATROOMBYFULLPATH__STRING_.
ChatRoom * ChatManager::getChatRoomByGamePath (ChatRoom * game, const String & path)
Definition at line 324 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::getChatRoomByGamePath(), and RPC_GETCHATROOMBYGAMEPATH__CHATROOM_STRING_.
ChatRoom * ChatManager::getGameRoom (const String & game)
Definition at line 562 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::getGameRoom(), and RPC_GETGAMEROOM__STRING_.
ChatRoom * ChatManager::getGroupRoom ()
Returns the parent room for group chat rooms.
Definition at line 624 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::getGroupRoom(), and RPC_GETGROUPROOM__.
ChatRoom * ChatManager::getGuildRoom ()
Returns the parent room for guild chat rooms.
Definition at line 611 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::getGuildRoom(), and RPC_GETGUILDROOM__.
unsigned int ChatManager::getNextRoomID ()
Definition at line 576 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::getNextRoomID(), and RPC_GETNEXTROOMID__.
CreatureObject * ChatManager::getPlayer (const String & name)
Definition at line 176 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::getPlayer(), and RPC_GETPLAYER__STRING_.
Referenced by FindFriendCommand::doQueueCommand().
int ChatManager::getPlayerCount ()
Definition at line 589 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::getPlayerCount(), and RPC_GETPLAYERCOUNT__.
PlayerMap * ChatManager::getPlayerMap ()
Definition at line 602 of file ChatManager.cpp.
References _getImplementation(), and server::chat::ChatManagerImplementation::getPlayerMap().
Referenced by BroadcastPlanetCommand::doQueueCommand().
void ChatManager::handleChatEnterRoomById (CreatureObject * player, unsigned int counter, unsigned int roomID)
Definition at line 356 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::handleChatEnterRoomById(), and RPC_HANDLECHATENTERROOMBYID__CREATUREOBJECT_INT_INT_.
Referenced by ChatEnterRoomByIdCallback::run().
void ChatManager::handleChatInstantMessageToCharacter (ChatInstantMessageToCharacter * message)
Definition at line 387 of file ChatManager.cpp.
References _getImplementation(), and server::chat::ChatManagerImplementation::handleChatInstantMessageToCharacter().
Referenced by server::zone::packets::chat::ChatInstantMessageToCharacter::run().
void ChatManager::handleChatRoomMessage (CreatureObject * sender, const UnicodeString & message, unsigned int roomID, unsigned int counter)
Definition at line 339 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::handleChatRoomMessage(), and RPC_HANDLECHATROOMMESSAGE__CREATUREOBJECT_UNICODESTRING_INT_INT_.
Referenced by ChatSendToRoomCallback::run().
void ChatManager::handleGroupChat (CreatureObject * player, const UnicodeString & message)
Definition at line 251 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::handleGroupChat(), and RPC_HANDLEGROUPCHAT__CREATUREOBJECT_UNICODESTRING_.
Referenced by GroupChatCommand::doQueueCommand().
void ChatManager::handleGuildChat (CreatureObject * player, const UnicodeString & message)
Definition at line 266 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::handleGuildChat(), and RPC_HANDLEGUILDCHAT__CREATUREOBJECT_UNICODESTRING_.
Referenced by GuildCommand::doQueueCommand().
void ChatManager::handlePlanetChat (CreatureObject * player, const UnicodeString & message)
Definition at line 281 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::handlePlanetChat(), and RPC_HANDLEPLANETCHAT__CREATUREOBJECT_UNICODESTRING_.
Referenced by PlanetsayCommand::doQueueCommand().
void ChatManager::handleRequestPersistentMsg (CreatureObject * player, unsigned int mailID)
Definition at line 474 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::handleRequestPersistentMsg(), and RPC_HANDLEREQUESTPERSISTENTMSG__CREATUREOBJECT_INT_.
Referenced by ChatRequestPersistentMessageCallback::run().
void ChatManager::handleSocialInternalMessage (CreatureObject * sender, const UnicodeString & arguments)
Definition at line 372 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::handleSocialInternalMessage(), and RPC_HANDLESOCIALINTERNALMESSAGE__CREATUREOBJECT_UNICODESTRING_.
void ChatManager::handleSpatialChatInternalMessage (CreatureObject * player, const UnicodeString & args)
Definition at line 236 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::handleSpatialChatInternalMessage(), and RPC_HANDLESPATIALCHATINTERNALMESSAGE__CREATUREOBJECT_UNICODESTRING_.
void ChatManager::initiatePlanetRooms ()
Definition at line 64 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::initiatePlanetRooms(), and RPC_INITIATEPLANETROOMS__.
void ChatManager::initiateRooms ()
Definition at line 51 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::initiateRooms(), and RPC_INITIATEROOMS__.
void ChatManager::loadMail (CreatureObject * player)
Definition at line 425 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::loadMail(), and RPC_LOADMAIL__CREATUREOBJECT_.
Referenced by SelectCharacterCallback::run().
void ChatManager::populateRoomListMessage (ChatRoom * channel, ChatRoomList * msg)
Definition at line 133 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::populateRoomListMessage(), and RPC_POPULATEROOMLISTMESSAGE__CHATROOM_CHATROOMLIST_.
CreatureObject * ChatManager::removePlayer (const String & name)
Definition at line 190 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::removePlayer(), and RPC_REMOVEPLAYER__STRING_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::unload().
void ChatManager::removeRoom (ChatRoom * channel)
Definition at line 119 of file ChatManager.cpp.
References _getImplementation(), server::chat::ChatManagerImplementation::removeRoom(), and RPC_REMOVEROOM__CHATROOM_.
void ChatManager::sendMail (const String & sendername, const UnicodeString & header, const UnicodeString & body, const String & name)
Definition at line 439 of file ChatManager.cpp.
References _getImplementation(), RPC_SENDMAIL__STRING_UNICODESTRING_UNICODESTRING_STRING_, and server::chat::ChatManagerImplementation::sendMail().
Referenced by server::zone::managers::city::CityManagerImplementation::contractCity(), server::zone::managers::city::CityManagerImplementation::destroyCity(), DumpZoneInformationCommand::doQueueCommand(), server::zone::managers::city::CityManagerImplementation::expandCity(), server::zone::managers::city::CityManagerImplementation::registerCitizen(), server::zone::managers::city::CityManagerImplementation::sendMail(), ChatPersistentMessageToServerCallback::sendMailToPlayer(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceDecayEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceDestroyEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceRepairEmail(), server::zone::managers::city::CityManagerImplementation::unregisterCitizen(), and server::zone::managers::city::CityManagerImplementation::updateCityVoting().
int ChatManager::sendMail (const String & sendername, const UnicodeString & subject, StringIdChatParameter & body, const String & recipientName, WaypointObject * waypoint = NULL)
Definition at line 456 of file ChatManager.cpp.
References _getImplementation(), and server::chat::ChatManagerImplementation::sendMail().
int ChatManager::sendMail (const String & sendername, const UnicodeString & subject, const UnicodeString & body, const String & recipientName, StringIdChatParameterVector * stringIdParameters, WaypointChatParameterVector * waypointParameters)
Definition at line 465 of file ChatManager.cpp.
References _getImplementation(), and server::chat::ChatManagerImplementation::sendMail().
void ChatManager::sendRoomList (CreatureObject * player)
Definition at line 148 of file ChatManager.cpp.
References _getImplementation(), RPC_SENDROOMLIST__CREATUREOBJECT_, and server::chat::ChatManagerImplementation::sendRoomList().
Referenced by server::zone::packets::chat::ChatRequestRoomListCallback::run().
void ChatManager::setPlayerManager (PlayerManager * manager)
Definition at line 534 of file ChatManager.cpp.
References _getImplementation(), RPC_SETPLAYERMANAGER__PLAYERMANAGER_, and server::chat::ChatManagerImplementation::setPlayerManager().
Friends And Related Function Documentation
friend class ChatManagerHelper friend
Definition at line 297 of file ChatManager.h.
Member Data Documentation
const int server::chat::ChatManager::IM_IGNORED = 0x09 static
Definition at line 187 of file ChatManager.h.
const int server::chat::ChatManager::IM_MAXSIZE = 255 static
Definition at line 191 of file ChatManager.h.
const int server::chat::ChatManager::IM_OFFLINE = 0x04 static
Definition at line 185 of file ChatManager.h.
const int server::chat::ChatManager::IM_SUCCESS = 0x00 static
Definition at line 183 of file ChatManager.h.
const int server::chat::ChatManager::IM_TOOLONG = 0x10 static
Definition at line 189 of file ChatManager.h.
const int server::chat::ChatManager::PM_MAXSIZE = 4000 static
Definition at line 193 of file ChatManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatManager.cpp