Core3: AiMap Class Reference
AiMap Class Reference
#include <AiMap.h>
Public Member Functions
AiMap ()
~AiMap ()
void initialize ()
int getSize ()
void put (String name, Reference< AiTemplate * > ait)
Reference< AiTemplate * > get (String name)
Public Attributes
HashTable< String, Reference
< AiTemplate * > > aiMap
Private Member Functions
void registerFunctions ()
void registerGlobals ()
Static Private Member Functions
static int includeFile (lua_State *L)
static int addAiTemplate (lua_State *L)
Detailed Description
Definition at line 16 of file AiMap.h.
Constructor & Destructor Documentation
AiMap::AiMap () inline
Definition at line 20 of file AiMap.h.
References aiMap.
AiMap::~AiMap () inline
Definition at line 24 of file AiMap.h.
Member Function Documentation
static int AiMap::addAiTemplate (lua_State * L) inline static private
Definition at line 75 of file AiMap.h.
Referenced by registerFunctions().
Reference<AiTemplate*> AiMap::get (String name) inline
Definition at line 45 of file AiMap.h.
References aiMap.
int AiMap::getSize () inline
Definition at line 37 of file AiMap.h.
References aiMap.
static int AiMap::includeFile (lua_State * L) inline static private
Definition at line 67 of file AiMap.h.
Referenced by registerFunctions().
void AiMap::initialize () inline
Definition at line 27 of file AiMap.h.
References registerFunctions(), and registerGlobals().
void AiMap::put (String name, Reference< AiTemplate * > ait) inline
Definition at line 41 of file AiMap.h.
References aiMap.
void AiMap::registerFunctions () inline private
Definition at line 50 of file AiMap.h.
References addAiTemplate(), and includeFile().
Referenced by initialize().
void AiMap::registerGlobals () inline private
Definition at line 55 of file AiMap.h.
Referenced by initialize().
Member Data Documentation
HashTable<String, Reference<AiTemplate*> > AiMap::aiMap
Definition at line 18 of file AiMap.h.
Referenced by AiMap(), get(), getSize(), and put().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/AiMap.h