Core3: LoginServlet Class Reference
LoginServlet Class Reference
#include <LoginServlet.h>
Public Member Functions
LoginServlet (String context)
virtual ~LoginServlet ()
void handleGet (HttpRequest *request, HttpResponse *response)
void handlePost (HttpRequest *request, HttpResponse *response)
Public Member Functions inherited from Servlet
Servlet (String context)
virtual ~Servlet ()
void handleRequest (struct mg_connection *conn, HttpRequest *request, HttpResponse *response)
void setZoneServer (ZoneServer *serv)
String getContext ()
Additional Inherited Members
Protected Attributes inherited from Servlet
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 13 of file LoginServlet.h.
Constructor & Destructor Documentation
LoginServlet::LoginServlet (String context)
Definition at line 11 of file LoginServlet.cpp.
LoginServlet::~LoginServlet () virtual
Definition at line 17 of file LoginServlet.cpp.
Member Function Documentation
void LoginServlet::handleGet (HttpRequest * request, HttpResponse * response) virtual
Implements Servlet.
Definition at line 21 of file LoginServlet.cpp.
References server::web::HttpRequest::getSession(), server::web::session::HttpSession::getSessionId(), and server::web::HttpResponse::println().
void LoginServlet::handlePost (HttpRequest * request, HttpResponse * response) virtual
Implements Servlet.
Definition at line 48 of file LoginServlet.cpp.
References server::web::HttpResponse::forwardTo(), server::web::HttpRequest::getParameter(), server::web::HttpRequest::getRemoteIp(), server::web::HttpRequest::getSession(), server::web::HttpResponse::println(), server::web::session::HttpSession::setPassword(), server::web::session::HttpSession::setSessionIp(), and server::web::session::HttpSession::setUserName().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/servlets/login/LoginServlet.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/servlets/login/LoginServlet.cpp