Core3: server::zone::objects::mission::EntertainerMissionObjectiveImplementation Class Reference
server::zone::objects::mission::EntertainerMissionObjectiveImplementation Class Reference
#include <EntertainerMissionObjective.h>
Public Member Functions
EntertainerMissionObjectiveImplementation (MissionObject *mission)
EntertainerMissionObjectiveImplementation (DummyConstructorParameter *param)
void finalize ()
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
void setIsEntertaining (bool value)
void clearLocationActiveAreaAndObservers ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void startCompleteTask ()
Vector3 getEndPosition ()
operator const EntertainerMissionObjective * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
MissionObjectiveImplementation (MissionObject *parent)
MissionObjectiveImplementation (DummyConstructorParameter *param)
virtual void destroyObjectFromDatabase ()
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
virtual void deactivate ()
virtual void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
operator const MissionObjective * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< EntertainerMissionObjective * > _this
Public Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
WeakReference< MissionObjective * > _this
Protected Member Functions
virtual ~EntertainerMissionObjectiveImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
virtual ~MissionObjectiveImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
bool inMissionArea
bool isEntertaining
ManagedReference< ActiveArea * > locationActiveArea
Reference
< CompleteMissionAfterCertainTimeTask * > completeTask
Protected Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
ManagedWeakReference
< MissionObject * > mission
unsigned int objectiveType
Time missionStartTime
Reference
< FailMissionAfterCertainTimeTask * > failTask
unsigned long long timeRemaining
bool activated
Friends
class EntertainerMissionObjective
Detailed Description
Definition at line 170 of file EntertainerMissionObjective.h.
Constructor & Destructor Documentation
EntertainerMissionObjectiveImplementation::EntertainerMissionObjectiveImplementation (MissionObject * mission)
Definition at line 340 of file EntertainerMissionObjective.cpp.
References _initializeImplementation(), completeTask, inMissionArea, isEntertaining, and locationActiveArea.
EntertainerMissionObjectiveImplementation::EntertainerMissionObjectiveImplementation (DummyConstructorParameter * param)
Definition at line 180 of file EntertainerMissionObjective.cpp.
References _initializeImplementation().
EntertainerMissionObjectiveImplementation::~EntertainerMissionObjectiveImplementation () protected virtual
Definition at line 185 of file EntertainerMissionObjective.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * EntertainerMissionObjectiveImplementation::_getStub ()
Definition at line 203 of file EntertainerMissionObjective.cpp.
References _this.
void EntertainerMissionObjectiveImplementation::_initializeImplementation () protected
Definition at line 190 of file EntertainerMissionObjective.cpp.
References _serializationHelperMethod(), and _this.
Referenced by EntertainerMissionObjectiveImplementation().
void EntertainerMissionObjectiveImplementation::_serializationHelperMethod () protected
Definition at line 239 of file EntertainerMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void EntertainerMissionObjectiveImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 198 of file EntertainerMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_setStub(), and _this.
Referenced by server::zone::objects::mission::EntertainerMissionObjective::EntertainerMissionObjective().
void EntertainerMissionObjectiveImplementation::abort () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 80 of file EntertainerMissionObjectiveImplementation.cpp.
References _this, server::zone::objects::mission::MissionObjectiveImplementation::abort(), and clearLocationActiveAreaAndObservers().
Referenced by server::zone::objects::mission::EntertainerMissionObjective::abort().
void EntertainerMissionObjectiveImplementation::activate () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 22 of file EntertainerMissionObjectiveImplementation.cpp.
References _this, server::zone::objects::mission::MissionObjectiveImplementation::activate(), server::zone::objects::mission::MissionObjectiveImplementation::addObserver(), ObserverEventType::ENTEREDAREA, ObserverEventType::EXITEDAREA, server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::mission::MissionObjectiveImplementation::hasObservers(), locationActiveArea, server::zone::objects::mission::MissionObjectiveImplementation::mission, server::zone::objects::waypoint::WaypointObject::setActive(), server::zone::objects::waypoint::WaypointObject::setPlanetCRC(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by server::zone::objects::mission::EntertainerMissionObjective::activate().
void EntertainerMissionObjectiveImplementation::clearLocationActiveAreaAndObservers ()
Definition at line 88 of file EntertainerMissionObjectiveImplementation.cpp.
References _this, ObserverEventType::ENTEREDAREA, ObserverEventType::EXITEDAREA, server::zone::objects::mission::MissionObjectiveImplementation::getObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getObserverCount(), locationActiveArea, and server::zone::objects::mission::MissionObjectiveImplementation::removeAllObservers().
Referenced by abort(), server::zone::objects::mission::EntertainerMissionObjective::clearLocationActiveAreaAndObservers(), and complete().
void EntertainerMissionObjectiveImplementation::complete () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 112 of file EntertainerMissionObjectiveImplementation.cpp.
References clearLocationActiveAreaAndObservers(), and server::zone::objects::mission::MissionObjectiveImplementation::complete().
Referenced by server::zone::objects::mission::EntertainerMissionObjective::complete().
void EntertainerMissionObjectiveImplementation::finalize ()
Definition at line 354 of file EntertainerMissionObjective.cpp.
Referenced by ~EntertainerMissionObjectiveImplementation().
Vector3 EntertainerMissionObjectiveImplementation::getEndPosition () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 182 of file EntertainerMissionObjectiveImplementation.cpp.
References TerrainManager::getHeight(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), and server::zone::objects::mission::MissionObjectiveImplementation::mission.
Referenced by server::zone::objects::mission::EntertainerMissionObjective::getEndPosition().
void EntertainerMissionObjectiveImplementation::initializeTransientMembers () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 357 of file EntertainerMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::initializeTransientMembers().
Referenced by server::zone::objects::mission::EntertainerMissionObjective::initializeTransientMembers(), and readObject().
void EntertainerMissionObjectiveImplementation::lock (bool doLock = true) protected
Definition at line 211 of file EntertainerMissionObjective.cpp.
References _this.
void EntertainerMissionObjectiveImplementation::lock (ManagedObject * obj) protected
Definition at line 215 of file EntertainerMissionObjective.cpp.
References _this.
int EntertainerMissionObjectiveImplementation::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 156 of file EntertainerMissionObjectiveImplementation.cpp.
References _this, ObserverEventType::ENTEREDAREA, ObserverEventType::EXITEDAREA, server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), inMissionArea, locationActiveArea, and startCompleteTask().
Referenced by server::zone::objects::mission::EntertainerMissionObjective::notifyObserverEvent().
EntertainerMissionObjectiveImplementation::operator const EntertainerMissionObjective * ()
Definition at line 207 of file EntertainerMissionObjective.cpp.
void EntertainerMissionObjectiveImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 246 of file EntertainerMissionObjective.cpp.
References initializeTransientMembers(), and readObjectMember().
bool EntertainerMissionObjectiveImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 265 of file EntertainerMissionObjective.cpp.
References completeTask, inMissionArea, isEntertaining, locationActiveArea, and server::zone::objects::mission::MissionObjectiveImplementation::readObjectMember().
Referenced by readObject().
void EntertainerMissionObjectiveImplementation::rlock (bool doLock = true) protected
Definition at line 219 of file EntertainerMissionObjective.cpp.
References _this.
void EntertainerMissionObjectiveImplementation::runlock (bool doLock = true) protected
Definition at line 235 of file EntertainerMissionObjective.cpp.
References _this.
void EntertainerMissionObjectiveImplementation::setIsEntertaining (bool value)
Definition at line 118 of file EntertainerMissionObjectiveImplementation.cpp.
References _this, isEntertaining, and startCompleteTask().
Referenced by server::zone::objects::mission::EntertainerMissionObjective::setIsEntertaining().
void EntertainerMissionObjectiveImplementation::startCompleteTask ()
Definition at line 130 of file EntertainerMissionObjectiveImplementation.cpp.
References _this, completeTask, server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), inMissionArea, and isEntertaining.
Referenced by notifyObserverEvent(), setIsEntertaining(), and server::zone::objects::mission::EntertainerMissionObjective::startCompleteTask().
void EntertainerMissionObjectiveImplementation::unlock (bool doLock = true) protected
Definition at line 231 of file EntertainerMissionObjective.cpp.
References _this.
void EntertainerMissionObjectiveImplementation::wlock (bool doLock = true) protected
Definition at line 223 of file EntertainerMissionObjective.cpp.
References _this.
void EntertainerMissionObjectiveImplementation::wlock (ManagedObject * obj) protected
Definition at line 227 of file EntertainerMissionObjective.cpp.
References _this.
void EntertainerMissionObjectiveImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 291 of file EntertainerMissionObjective.cpp.
References writeObjectMembers().
int EntertainerMissionObjectiveImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 298 of file EntertainerMissionObjective.cpp.
References completeTask, inMissionArea, isEntertaining, locationActiveArea, and server::zone::objects::mission::MissionObjectiveImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class EntertainerMissionObjective friend
Definition at line 237 of file EntertainerMissionObjective.h.
Member Data Documentation
WeakReference<EntertainerMissionObjective*> server::zone::objects::mission::EntertainerMissionObjectiveImplementation::_this
Definition at line 205 of file EntertainerMissionObjective.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), abort(), activate(), clearLocationActiveAreaAndObservers(), lock(), notifyObserverEvent(), rlock(), runlock(), setIsEntertaining(), startCompleteTask(), unlock(), and wlock().
Reference<CompleteMissionAfterCertainTimeTask* > server::zone::objects::mission::EntertainerMissionObjectiveImplementation::completeTask protected
Definition at line 178 of file EntertainerMissionObjective.h.
Referenced by EntertainerMissionObjectiveImplementation(), readObjectMember(), startCompleteTask(), and writeObjectMembers().
bool server::zone::objects::mission::EntertainerMissionObjectiveImplementation::inMissionArea protected
Definition at line 172 of file EntertainerMissionObjective.h.
Referenced by EntertainerMissionObjectiveImplementation(), notifyObserverEvent(), readObjectMember(), startCompleteTask(), and writeObjectMembers().
bool server::zone::objects::mission::EntertainerMissionObjectiveImplementation::isEntertaining protected
Definition at line 174 of file EntertainerMissionObjective.h.
Referenced by EntertainerMissionObjectiveImplementation(), readObjectMember(), setIsEntertaining(), startCompleteTask(), and writeObjectMembers().
ManagedReference<ActiveArea* > server::zone::objects::mission::EntertainerMissionObjectiveImplementation::locationActiveArea protected
Definition at line 176 of file EntertainerMissionObjective.h.
Referenced by activate(), clearLocationActiveAreaAndObservers(), EntertainerMissionObjectiveImplementation(), notifyObserverEvent(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/EntertainerMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/EntertainerMissionObjective.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/EntertainerMissionObjectiveImplementation.cpp