Core3: SkillModMap Class Reference
SkillModMap Class Reference
#include <SkillModMap.h>
Public Member Functions
SkillModMap ()
SkillModMap (const SkillModMap &smm)
SkillModMap & operator= (const SkillModMap &smm)
void add (SkillModMap *map)
void add (VectorMap< String, int64 > *map)
void subtract (SkillModMap *map)
void subtract (VectorMap< String, int64 > *map)
void addSerializableVariables ()
int size ()
bool contains (const String &mod)
int64 get (const String &mod)
int64 get (int idx)
void put (const String &mod, int64 value)
void overwrite (const String &mod, int64 value)
void add (const String &mod, int64 value)
void subtract (const String &mod, int64 value)
Private Attributes
VectorMap< String, int64 > skillMods
Detailed Description
Definition at line 13 of file SkillModMap.h.
Constructor & Destructor Documentation
SkillModMap::SkillModMap ()
Definition at line 10 of file SkillModMap.cpp.
References addSerializableVariables(), and skillMods.
SkillModMap::SkillModMap (const SkillModMap & smm)
Definition at line 17 of file SkillModMap.cpp.
References addSerializableVariables(), and skillMods.
Member Function Documentation
void SkillModMap::add (SkillModMap * map)
Definition at line 32 of file SkillModMap.cpp.
References size(), and skillMods.
void SkillModMap::add (VectorMap< String, int64 > * map)
Definition at line 40 of file SkillModMap.cpp.
References skillMods.
void SkillModMap::add (const String & mod, int64 value) inline
Adds the value to an existing mod, or puts into the map if not existing.
Definition at line 82 of file SkillModMap.h.
References skillMods.
void SkillModMap::addSerializableVariables () inline
Definition at line 28 of file SkillModMap.h.
References skillMods.
Referenced by SkillModMap().
bool SkillModMap::contains (const String & mod) inline
Returns true if the map contains a value for the mod.
Definition at line 42 of file SkillModMap.h.
References skillMods.
int64 SkillModMap::get (const String & mod) inline
If the key exists, returns the value, otherwise returns 0.
Definition at line 49 of file SkillModMap.h.
References skillMods.
int64 SkillModMap::get (int idx) inline
Definition at line 53 of file SkillModMap.h.
References skillMods.
SkillModMap & SkillModMap::operator= (const SkillModMap & smm)
Definition at line 23 of file SkillModMap.cpp.
References skillMods.
void SkillModMap::overwrite (const String & mod, int64 value) inline
If the key exists, it will overwrite it's value with this value.
Definition at line 67 of file SkillModMap.h.
References skillMods.
void SkillModMap::put (const String & mod, int64 value) inline
If the key does not exist, it will put this value. If the key does exist, it will be ignored.
Definition at line 60 of file SkillModMap.h.
References skillMods.
int SkillModMap::size () inline
Returns the number of mods in the map.
Definition at line 35 of file SkillModMap.h.
References skillMods.
Referenced by add().
void SkillModMap::subtract (SkillModMap * map)
Definition at line 48 of file SkillModMap.cpp.
References skillMods.
void SkillModMap::subtract (VectorMap< String, int64 > * map)
Definition at line 62 of file SkillModMap.cpp.
References skillMods.
void SkillModMap::subtract (const String & mod, int64 value) inline
Subtracts the value of an existing mod, and drops the mod if it is equal to 0.
Definition at line 93 of file SkillModMap.h.
References skillMods.
Member Data Documentation
VectorMap<String, int64> SkillModMap::skillMods private
Definition at line 14 of file SkillModMap.h.
Referenced by add(), addSerializableVariables(), contains(), get(), operator=(), overwrite(), put(), size(), SkillModMap(), and subtract().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/variables/SkillModMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/variables/SkillModMap.cpp