Core3: server::zone::managers::minigames::GamblingManagerAdapter Class Reference
server::zone::managers::minigames::GamblingManagerAdapter Class Reference
#include <GamblingManager.h>
Public Member Functions
GamblingManagerAdapter (GamblingManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeSlotTimer ()
void initializeRouletteTimer ()
void initializeSlots ()
void initializeRouletteRed ()
void initializeRoulette ()
int notify (SceneObject *sceneObject)
bool isHigh (int value)
bool isLow (int value)
bool isEven (int value)
bool isOdd (int value)
bool isBlack (int value)
bool isRed (int value)
void handleSlot (CreatureObject *player, bool cancel, bool other)
void bet (CreatureObject *player, int amount, int target, int machineType)
void bet (GamblingTerminal *terminal, CreatureObject *player, int amount, int target)
void startGame (CreatureObject *player, int machineType)
void startGame (GamblingTerminal *terminal)
void leaveTerminal (CreatureObject *player, int machineType)
void registerPlayer (GamblingTerminal *terminal, CreatureObject *player)
void refreshRouletteMenu (CreatureObject *player)
void continueGame (GamblingTerminal *terminal)
void stopGame (GamblingTerminal *terminal, bool cancel)
void calculateOutcome (GamblingTerminal *terminal)
unsigned int createWindow (GamblingTerminal *terminal, CreatureObject *player)
unsigned int createPayoutWindow (CreatureObject *player)
unsigned int createSlotWindow (CreatureObject *player, unsigned int payoutBoxID)
unsigned int createRouletteWindow (CreatureObject *player)
void createEvent (GamblingTerminal *terminal, int time)
bool isPlaying (CreatureObject *player)
Detailed Description
Definition at line 582 of file GamblingManager.h.
Constructor & Destructor Documentation
GamblingManagerAdapter::GamblingManagerAdapter (GamblingManager * impl)
Definition at line 985 of file GamblingManager.cpp.
Member Function Documentation
void GamblingManagerAdapter::bet (CreatureObject * player, int amount, int target, int machineType)
Definition at line 1194 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::bet (GamblingTerminal * terminal, CreatureObject * player, int amount, int target)
Definition at line 1198 of file GamblingManager.cpp.
void GamblingManagerAdapter::calculateOutcome (GamblingTerminal * terminal)
Definition at line 1230 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::continueGame (GamblingTerminal * terminal)
Definition at line 1222 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::createEvent (GamblingTerminal * terminal, int time)
Definition at line 1250 of file GamblingManager.cpp.
Referenced by invokeMethod().
unsigned int GamblingManagerAdapter::createPayoutWindow (CreatureObject * player)
Definition at line 1238 of file GamblingManager.cpp.
Referenced by invokeMethod().
unsigned int GamblingManagerAdapter::createRouletteWindow (CreatureObject * player)
Definition at line 1246 of file GamblingManager.cpp.
Referenced by invokeMethod().
unsigned int GamblingManagerAdapter::createSlotWindow (CreatureObject * player, unsigned int payoutBoxID)
Definition at line 1242 of file GamblingManager.cpp.
Referenced by invokeMethod().
unsigned int GamblingManagerAdapter::createWindow (GamblingTerminal * terminal, CreatureObject * player)
Definition at line 1234 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::handleSlot (CreatureObject * player, bool cancel, bool other)
Definition at line 1190 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::initializeRoulette ()
Definition at line 1158 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::initializeRouletteRed ()
Definition at line 1154 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::initializeRouletteTimer ()
Definition at line 1146 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::initializeSlots ()
Definition at line 1150 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::initializeSlotTimer ()
Definition at line 1142 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 988 of file GamblingManager.cpp.
References bet(), calculateOutcome(), continueGame(), createEvent(), createPayoutWindow(), createRouletteWindow(), createSlotWindow(), createWindow(), handleSlot(), initializeRoulette(), initializeRouletteRed(), initializeRouletteTimer(), initializeSlots(), initializeSlotTimer(), isBlack(), isEven(), isHigh(), isLow(), isOdd(), isPlaying(), isRed(), leaveTerminal(), notify(), refreshRouletteMenu(), registerPlayer(), RPC_BET__CREATUREOBJECT_INT_INT_INT_, RPC_BET__GAMBLINGTERMINAL_CREATUREOBJECT_INT_INT_, RPC_CALCULATEOUTCOME__GAMBLINGTERMINAL_, RPC_CONTINUEGAME__GAMBLINGTERMINAL_, RPC_CREATEEVENT__GAMBLINGTERMINAL_INT_, RPC_CREATEPAYOUTWINDOW__CREATUREOBJECT_, RPC_CREATEROULETTEWINDOW__CREATUREOBJECT_, RPC_CREATESLOTWINDOW__CREATUREOBJECT_INT_, RPC_CREATEWINDOW__GAMBLINGTERMINAL_CREATUREOBJECT_, RPC_HANDLESLOT__CREATUREOBJECT_BOOL_BOOL_, RPC_INITIALIZEROULETTE__, RPC_INITIALIZEROULETTERED__, RPC_INITIALIZEROULETTETIMER__, RPC_INITIALIZESLOTS__, RPC_INITIALIZESLOTTIMER__, RPC_ISBLACK__INT_, RPC_ISEVEN__INT_, RPC_ISHIGH__INT_, RPC_ISLOW__INT_, RPC_ISODD__INT_, RPC_ISPLAYING__CREATUREOBJECT_, RPC_ISRED__INT_, RPC_LEAVETERMINAL__CREATUREOBJECT_INT_, RPC_NOTIFY__SCENEOBJECT_, RPC_REFRESHROULETTEMENU__CREATUREOBJECT_, RPC_REGISTERPLAYER__GAMBLINGTERMINAL_CREATUREOBJECT_, RPC_STARTGAME__CREATUREOBJECT_INT_, RPC_STARTGAME__GAMBLINGTERMINAL_, RPC_STOPGAME__GAMBLINGTERMINAL_BOOL_, startGame(), and stopGame().
bool GamblingManagerAdapter::isBlack (int value)
Definition at line 1182 of file GamblingManager.cpp.
Referenced by invokeMethod().
bool GamblingManagerAdapter::isEven (int value)
Definition at line 1174 of file GamblingManager.cpp.
Referenced by invokeMethod().
bool GamblingManagerAdapter::isHigh (int value)
Definition at line 1166 of file GamblingManager.cpp.
Referenced by invokeMethod().
bool GamblingManagerAdapter::isLow (int value)
Definition at line 1170 of file GamblingManager.cpp.
Referenced by invokeMethod().
bool GamblingManagerAdapter::isOdd (int value)
Definition at line 1178 of file GamblingManager.cpp.
Referenced by invokeMethod().
bool GamblingManagerAdapter::isPlaying (CreatureObject * player)
Definition at line 1254 of file GamblingManager.cpp.
Referenced by invokeMethod().
bool GamblingManagerAdapter::isRed (int value)
Definition at line 1186 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::leaveTerminal (CreatureObject * player, int machineType)
Definition at line 1210 of file GamblingManager.cpp.
Referenced by invokeMethod().
int GamblingManagerAdapter::notify (SceneObject * sceneObject)
Definition at line 1162 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::refreshRouletteMenu (CreatureObject * player)
Definition at line 1218 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::registerPlayer (GamblingTerminal * terminal, CreatureObject * player)
Definition at line 1214 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::startGame (CreatureObject * player, int machineType)
Definition at line 1202 of file GamblingManager.cpp.
Referenced by invokeMethod().
void GamblingManagerAdapter::startGame (GamblingTerminal * terminal)
Definition at line 1206 of file GamblingManager.cpp.
void GamblingManagerAdapter::stopGame (GamblingTerminal * terminal, bool cancel)
Definition at line 1226 of file GamblingManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/GamblingManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/GamblingManager.cpp