Core3: server::zone::objects::mission::BountyMissionObjective Class Reference
server::zone::objects::mission::BountyMissionObjective Class Reference
#include <BountyMissionObjective.h>
Public Member Functions
BountyMissionObjective (MissionObject *mission)
void initializeTransientMembers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void spawnTarget (const String &zoneName)
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void setNpcTemplateToSpawn (SharedObjectTemplate *sp)
void updateMissionStatus (int informantLevel)
int getObjectiveStatus ()
SceneObject * getArakydDroid ()
void setArakydDroid (SceneObject *droid)
void performDroidAction (int action, SceneObject *sceneObject, CreatureObject *player)
bool playerHasMissionOfCorrectLevel (int action)
void updateWaypoint ()
Vector3 getTargetPosition ()
void cancelAllTasks ()
String getTargetZoneName ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (MissionObject *parent)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int INITSTATUS = 0
static const int HASBIOSIGNATURESTATUS = 1
static const int HASTALKED = 2
static const int TARGETELIMINATEDSTATUS = 3
Protected Member Functions
BountyMissionObjective (DummyConstructorParameter *param)
virtual ~BountyMissionObjective ()
Protected Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (DummyConstructorParameter *param)
virtual ~MissionObjective ()
Friends
class BountyMissionObjectiveHelper
Detailed Description
Definition at line 135 of file BountyMissionObjective.h.
Constructor & Destructor Documentation
BountyMissionObjective::BountyMissionObjective (MissionObject * mission)
Definition at line 27 of file BountyMissionObjective.cpp.
References server::zone::objects::mission::BountyMissionObjectiveImplementation::_setStub().
BountyMissionObjective::BountyMissionObjective (DummyConstructorParameter * param) protected
Definition at line 34 of file BountyMissionObjective.cpp.
BountyMissionObjective::~BountyMissionObjective () protected virtual
Definition at line 38 of file BountyMissionObjective.cpp.
Member Function Documentation
DistributedObjectServant * BountyMissionObjective::_getImplementation ()
Definition at line 292 of file BountyMissionObjective.cpp.
Referenced by abort(), activate(), cancelAllTasks(), complete(), deactivate(), getArakydDroid(), getEndPosition(), getObjectiveStatus(), getTargetPosition(), getTargetZoneName(), initializeTransientMembers(), notifyObserverEvent(), performDroidAction(), playerHasMissionOfCorrectLevel(), setArakydDroid(), setNpcTemplateToSpawn(), spawnTarget(), updateMissionStatus(), and updateWaypoint().
DistributedObjectServant * BountyMissionObjective::_getImplementationForRead ()
Definition at line 298 of file BountyMissionObjective.cpp.
void BountyMissionObjective::_setImplementation (DistributedObjectServant * servant)
Definition at line 302 of file BountyMissionObjective.cpp.
void BountyMissionObjective::abort ()
Definition at line 82 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::abort(), and RPC_ABORT__.
void BountyMissionObjective::activate ()
Definition at line 56 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::activate(), and RPC_ACTIVATE__.
void BountyMissionObjective::cancelAllTasks ()
Definition at line 255 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::cancelAllTasks(), and RPC_CANCELALLTASKS__.
void BountyMissionObjective::complete ()
Definition at line 95 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::complete(), and RPC_COMPLETE__.
void BountyMissionObjective::deactivate ()
Definition at line 69 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::deactivate(), and RPC_DEACTIVATE__.
SceneObject * BountyMissionObjective::getArakydDroid ()
Definition at line 176 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::getArakydDroid(), and RPC_GETARAKYDDROID__.
Vector3 BountyMissionObjective::getEndPosition ()
Definition at line 283 of file BountyMissionObjective.cpp.
References _getImplementation(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::getEndPosition().
int BountyMissionObjective::getObjectiveStatus ()
Definition at line 163 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::getObjectiveStatus(), and RPC_GETOBJECTIVESTATUS__.
Referenced by server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::handleScreen().
Vector3 BountyMissionObjective::getTargetPosition ()
Definition at line 246 of file BountyMissionObjective.cpp.
References _getImplementation(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::getTargetPosition().
Referenced by server::zone::objects::mission::bountyhunter::events::FindTargetTask::getDirectionToTarget(), and server::zone::objects::mission::bountyhunter::events::FindTargetTask::getDistanceToTarget().
String BountyMissionObjective::getTargetZoneName ()
Definition at line 268 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::getTargetZoneName(), and RPC_GETTARGETZONENAME__.
Referenced by server::zone::objects::mission::bountyhunter::events::FindTargetTask::findAndTrackSuccess().
void BountyMissionObjective::initializeTransientMembers ()
Definition at line 43 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
int BountyMissionObjective::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 122 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
void BountyMissionObjective::performDroidAction (int action, SceneObject * sceneObject, CreatureObject * player)
Definition at line 203 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::performDroidAction(), and RPC_PERFORMDROIDACTION__INT_SCENEOBJECT_CREATUREOBJECT_.
bool BountyMissionObjective::playerHasMissionOfCorrectLevel (int action)
Definition at line 219 of file BountyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::BountyMissionObjectiveImplementation::playerHasMissionOfCorrectLevel(), and RPC_PLAYERHASMISSIONOFCORRECTLEVEL__INT_.
void BountyMissionObjective::setArakydDroid (SceneObject * droid)
Definition at line 189 of file BountyMissionObjective.cpp.
References _getImplementation(), RPC_SETARAKYDDROID__SCENEOBJECT_, and server::zone::objects::mission::BountyMissionObjectiveImplementation::setArakydDroid().
Referenced by server::zone::objects::mission::bountyhunter::events::FindTargetTask::searching(), and server::zone::objects::mission::bountyhunter::events::FindTargetTask::tracking().
void BountyMissionObjective::setNpcTemplateToSpawn (SharedObjectTemplate * sp)
Definition at line 140 of file BountyMissionObjective.cpp.
References _getImplementation(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::setNpcTemplateToSpawn().
void BountyMissionObjective::spawnTarget (const String & zoneName)
Definition at line 108 of file BountyMissionObjective.cpp.
References _getImplementation(), RPC_SPAWNTARGET__STRING_, and server::zone::objects::mission::BountyMissionObjectiveImplementation::spawnTarget().
void BountyMissionObjective::updateMissionStatus (int informantLevel)
Definition at line 149 of file BountyMissionObjective.cpp.
References _getImplementation(), RPC_UPDATEMISSIONSTATUS__INT_, and server::zone::objects::mission::BountyMissionObjectiveImplementation::updateMissionStatus().
Referenced by server::zone::objects::mission::bountyhunter::events::FindTargetTask::findAndTrackSuccess(), and server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::handleScreen().
void BountyMissionObjective::updateWaypoint ()
Definition at line 233 of file BountyMissionObjective.cpp.
References _getImplementation(), RPC_UPDATEWAYPOINT__, and server::zone::objects::mission::BountyMissionObjectiveImplementation::updateWaypoint().
Friends And Related Function Documentation
friend class BountyMissionObjectiveHelper friend
Definition at line 195 of file BountyMissionObjective.h.
Member Data Documentation
const int server::zone::objects::mission::BountyMissionObjective::HASBIOSIGNATURESTATUS = 1 static
Definition at line 139 of file BountyMissionObjective.h.
const int server::zone::objects::mission::BountyMissionObjective::HASTALKED = 2 static
Definition at line 141 of file BountyMissionObjective.h.
const int server::zone::objects::mission::BountyMissionObjective::INITSTATUS = 0 static
Definition at line 137 of file BountyMissionObjective.h.
Referenced by server::zone::objects::mission::bountyhunter::BountyHunterDroid::callArakydDroid(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::findTarget(), and server::zone::objects::mission::bountyhunter::BountyHunterDroid::transmitBiologicalSignature().
const int server::zone::objects::mission::BountyMissionObjective::TARGETELIMINATEDSTATUS = 3 static
Definition at line 143 of file BountyMissionObjective.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/BountyMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/BountyMissionObjective.cpp