Core3: server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation Class Reference
server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation Class Reference
#include <SuiKeypadBox.h>
Public Member Functions
SuiKeypadBoxImplementation (CreatureObject *player, unsigned int windowType)
SuiKeypadBoxImplementation (DummyConstructorParameter *param)
BaseMessage * generateMessage ()
bool isKeypadBox ()
operator const SuiKeypadBox * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
SuiBoxImplementation (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
SuiBoxImplementation (DummyConstructorParameter *param)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
virtual bool isInputBox ()
virtual bool isListBox ()
virtual bool isMessageBox ()
virtual bool isTransferBox ()
virtual bool isBankTransferBox ()
virtual bool isSlicingBox ()
virtual bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
operator const SuiBox * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< SuiKeypadBox * > _this
Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
WeakReference< SuiBox * > _this
Protected Member Functions
virtual ~SuiKeypadBoxImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::player::sui::SuiBoxImplementation
virtual ~SuiBoxImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Friends
class SuiKeypadBox
Additional Inherited Members
Static Public Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Protected Attributes inherited from server::zone::objects::player::sui::SuiBoxImplementation
ManagedWeakReference
< CreatureObject * > player
Reference< SuiCallback * > suiCallback
unsigned int boxID
ManagedWeakReference
< SceneObject * > usingObject
String handlerStr
String cancelButtonText
bool cancelButton
String okButtonText
bool okButton
String otherButtonText
bool otherButton
String promptTitle
String promptText
int boxType
unsigned int windowType
float forceCloseDistance
Vector< String > headerSets
Vector< String > optionSets
int hdrOptCount
bool hasGenerated
Detailed Description
Definition at line 108 of file SuiKeypadBox.h.
Constructor & Destructor Documentation
SuiKeypadBoxImplementation::SuiKeypadBoxImplementation (CreatureObject * player, unsigned int windowType)
Definition at line 193 of file SuiKeypadBox.cpp.
References _initializeImplementation().
SuiKeypadBoxImplementation::SuiKeypadBoxImplementation (DummyConstructorParameter * param)
Definition at line 79 of file SuiKeypadBox.cpp.
References _initializeImplementation().
SuiKeypadBoxImplementation::~SuiKeypadBoxImplementation () protected virtual
Definition at line 84 of file SuiKeypadBox.cpp.
Member Function Documentation
DistributedObjectStub * SuiKeypadBoxImplementation::_getStub ()
Definition at line 104 of file SuiKeypadBox.cpp.
References _this.
void SuiKeypadBoxImplementation::_initializeImplementation () protected
Definition at line 91 of file SuiKeypadBox.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SuiKeypadBoxImplementation().
void SuiKeypadBoxImplementation::_serializationHelperMethod () protected
Definition at line 140 of file SuiKeypadBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void SuiKeypadBoxImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 99 of file SuiKeypadBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::_setStub(), and _this.
Referenced by server::zone::objects::player::sui::keypadbox::SuiKeypadBox::SuiKeypadBox().
void SuiKeypadBoxImplementation::finalize () protected
Definition at line 88 of file SuiKeypadBox.cpp.
BaseMessage * SuiKeypadBoxImplementation::generateMessage () virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 11 of file SuiKeypadBoxImplementation.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::boxID, server::zone::objects::player::sui::SuiBoxImplementation::forceCloseDistance, server::zone::objects::player::sui::SuiBoxImplementation::hasGenerated, and server::zone::objects::player::sui::SuiBoxImplementation::usingObject.
Referenced by server::zone::objects::player::sui::keypadbox::SuiKeypadBox::generateMessage().
bool SuiKeypadBoxImplementation::isKeypadBox ()
Definition at line 197 of file SuiKeypadBox.cpp.
Referenced by server::zone::objects::player::sui::keypadbox::SuiKeypadBox::isKeypadBox().
void SuiKeypadBoxImplementation::lock (bool doLock = true) protected
Definition at line 112 of file SuiKeypadBox.cpp.
References _this.
void SuiKeypadBoxImplementation::lock (ManagedObject * obj) protected
Definition at line 116 of file SuiKeypadBox.cpp.
References _this.
SuiKeypadBoxImplementation::operator const SuiKeypadBox * ()
Definition at line 108 of file SuiKeypadBox.cpp.
void SuiKeypadBoxImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 147 of file SuiKeypadBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::initializeTransientMembers(), and readObjectMember().
bool SuiKeypadBoxImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 166 of file SuiKeypadBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::readObjectMember().
Referenced by readObject().
void SuiKeypadBoxImplementation::rlock (bool doLock = true) protected
Definition at line 120 of file SuiKeypadBox.cpp.
References _this.
void SuiKeypadBoxImplementation::runlock (bool doLock = true) protected
Definition at line 136 of file SuiKeypadBox.cpp.
References _this.
void SuiKeypadBoxImplementation::unlock (bool doLock = true) protected
Definition at line 132 of file SuiKeypadBox.cpp.
References _this.
void SuiKeypadBoxImplementation::wlock (bool doLock = true) protected
Definition at line 124 of file SuiKeypadBox.cpp.
References _this.
void SuiKeypadBoxImplementation::wlock (ManagedObject * obj) protected
Definition at line 128 of file SuiKeypadBox.cpp.
References _this.
void SuiKeypadBoxImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::player::sui::SuiBoxImplementation.
Definition at line 176 of file SuiKeypadBox.cpp.
References writeObjectMembers().
int SuiKeypadBoxImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 183 of file SuiKeypadBox.cpp.
References server::zone::objects::player::sui::SuiBoxImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class SuiKeypadBox friend
Definition at line 153 of file SuiKeypadBox.h.
Member Data Documentation
WeakReference<SuiKeypadBox*> server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation::_this
Definition at line 119 of file SuiKeypadBox.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/keypadbox/SuiKeypadBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/keypadbox/SuiKeypadBox.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/keypadbox/SuiKeypadBoxImplementation.cpp