Core3: server::zone::objects::player::sui::listbox::SuiListBoxAdapter Class Reference
server::zone::objects::player::sui::listbox::SuiListBoxAdapter Class Reference
#include <SuiListBox.h>
Public Member Functions
SuiListBoxAdapter (SuiListBox *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void init ()
void addMenuItem (const String &name, unsigned long long objectID)
String getMenuItemName (int index)
void removeAllMenuItems ()
unsigned long long getMenuObjectID (unsigned int idx)
int getMenuSize ()
BaseMessage * generateMessage ()
void setNextBox (unsigned int boxID)
void setPreviousBox (unsigned int boxID)
unsigned long long getNextBox ()
unsigned long long getPreviousBox ()
bool isListBox ()
Public Member Functions inherited from server::zone::objects::player::sui::SuiBoxAdapter
SuiBoxAdapter (SuiBox *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type)
BaseMessage * generateMessage ()
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
bool isInputBox ()
bool isListBox ()
bool isMessageBox ()
bool isTransferBox ()
bool isBankTransferBox ()
bool isSlicingBox ()
bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
Detailed Description
Definition at line 237 of file SuiListBox.h.
Constructor & Destructor Documentation
SuiListBoxAdapter::SuiListBoxAdapter (SuiListBox * impl)
Definition at line 457 of file SuiListBox.cpp.
Member Function Documentation
void SuiListBoxAdapter::addMenuItem (const String & name, unsigned long long objectID)
Definition at line 534 of file SuiListBox.cpp.
Referenced by invokeMethod().
BaseMessage * SuiListBoxAdapter::generateMessage ()
Definition at line 554 of file SuiListBox.cpp.
Referenced by invokeMethod().
String SuiListBoxAdapter::getMenuItemName (int index)
Definition at line 538 of file SuiListBox.cpp.
Referenced by invokeMethod().
unsigned long long SuiListBoxAdapter::getMenuObjectID (unsigned int idx)
Definition at line 546 of file SuiListBox.cpp.
Referenced by invokeMethod().
int SuiListBoxAdapter::getMenuSize ()
Definition at line 550 of file SuiListBox.cpp.
Referenced by invokeMethod().
unsigned long long SuiListBoxAdapter::getNextBox ()
Definition at line 566 of file SuiListBox.cpp.
Referenced by invokeMethod().
unsigned long long SuiListBoxAdapter::getPreviousBox ()
Definition at line 570 of file SuiListBox.cpp.
Referenced by invokeMethod().
void SuiListBoxAdapter::init ()
Definition at line 530 of file SuiListBox.cpp.
Referenced by invokeMethod().
void SuiListBoxAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 460 of file SuiListBox.cpp.
References addMenuItem(), generateMessage(), getMenuItemName(), getMenuObjectID(), getMenuSize(), getNextBox(), getPreviousBox(), init(), isListBox(), removeAllMenuItems(), RPC_ADDMENUITEM__STRING_LONG_, RPC_GENERATEMESSAGE__, RPC_GETMENUITEMNAME__INT_, RPC_GETMENUOBJECTID__INT_, RPC_GETMENUSIZE__, RPC_GETNEXTBOX__, RPC_GETPREVIOUSBOX__, RPC_INIT__, RPC_ISLISTBOX__, RPC_REMOVEALLMENUITEMS__, RPC_SETNEXTBOX__INT_, RPC_SETPREVIOUSBOX__INT_, setNextBox(), and setPreviousBox().
bool SuiListBoxAdapter::isListBox ()
Definition at line 574 of file SuiListBox.cpp.
Referenced by invokeMethod().
void SuiListBoxAdapter::removeAllMenuItems ()
Definition at line 542 of file SuiListBox.cpp.
Referenced by invokeMethod().
void SuiListBoxAdapter::setNextBox (unsigned int boxID)
Definition at line 558 of file SuiListBox.cpp.
Referenced by invokeMethod().
void SuiListBoxAdapter::setPreviousBox (unsigned int boxID)
Definition at line 562 of file SuiListBox.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/listbox/SuiListBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/listbox/SuiListBox.cpp