Core3: server::zone::objects::tangible::threat::ThreatMapObserverImplementation Class Reference
server::zone::objects::tangible::threat::ThreatMapObserverImplementation Class Reference
#include <ThreatMapObserver.h>
Public Member Functions
ThreatMapObserverImplementation (TangibleObject *me)
ThreatMapObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const ThreatMapObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< ThreatMapObserver * > _this
Protected Member Functions
virtual ~ThreatMapObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< TangibleObject * > self
Friends
class ThreatMapObserver
Detailed Description
Definition at line 83 of file ThreatMapObserver.h.
Constructor & Destructor Documentation
ThreatMapObserverImplementation::ThreatMapObserverImplementation (TangibleObject * me)
Definition at line 192 of file ThreatMapObserver.cpp.
References _initializeImplementation().
ThreatMapObserverImplementation::ThreatMapObserverImplementation (DummyConstructorParameter * param)
Definition at line 66 of file ThreatMapObserver.cpp.
References _initializeImplementation().
ThreatMapObserverImplementation::~ThreatMapObserverImplementation () protected virtual
Definition at line 71 of file ThreatMapObserver.cpp.
Member Function Documentation
DistributedObjectStub * ThreatMapObserverImplementation::_getStub ()
Definition at line 91 of file ThreatMapObserver.cpp.
References _this.
void ThreatMapObserverImplementation::_initializeImplementation () protected
Definition at line 78 of file ThreatMapObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ThreatMapObserverImplementation().
void ThreatMapObserverImplementation::_serializationHelperMethod () protected
Definition at line 127 of file ThreatMapObserver.cpp.
Referenced by _initializeImplementation().
void ThreatMapObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 86 of file ThreatMapObserver.cpp.
References _this.
Referenced by server::zone::objects::tangible::threat::ThreatMapObserver::ThreatMapObserver().
void ThreatMapObserverImplementation::finalize () protected
Definition at line 75 of file ThreatMapObserver.cpp.
void ThreatMapObserverImplementation::lock (bool doLock = true) protected
Definition at line 99 of file ThreatMapObserver.cpp.
References _this.
void ThreatMapObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 103 of file ThreatMapObserver.cpp.
References _this.
int ThreatMapObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 14 of file ThreatMapObserverImplementation.cpp.
References server::zone::objects::tangible::threat::ThreatMap::addHeal(), and ObserverEventType::HEALINGPERFORMED.
Referenced by server::zone::objects::tangible::threat::ThreatMapObserver::notifyObserverEvent().
ThreatMapObserverImplementation::operator const ThreatMapObserver * ()
Definition at line 95 of file ThreatMapObserver.cpp.
void ThreatMapObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 134 of file ThreatMapObserver.cpp.
References readObjectMember().
bool ThreatMapObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 153 of file ThreatMapObserver.cpp.
Referenced by readObject().
void ThreatMapObserverImplementation::rlock (bool doLock = true) protected
Definition at line 107 of file ThreatMapObserver.cpp.
References _this.
void ThreatMapObserverImplementation::runlock (bool doLock = true) protected
Definition at line 123 of file ThreatMapObserver.cpp.
References _this.
void ThreatMapObserverImplementation::unlock (bool doLock = true) protected
Definition at line 119 of file ThreatMapObserver.cpp.
References _this.
void ThreatMapObserverImplementation::wlock (bool doLock = true) protected
Definition at line 111 of file ThreatMapObserver.cpp.
References _this.
void ThreatMapObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 115 of file ThreatMapObserver.cpp.
References _this.
void ThreatMapObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 167 of file ThreatMapObserver.cpp.
References writeObjectMembers().
int ThreatMapObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 174 of file ThreatMapObserver.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ThreatMapObserver friend
Definition at line 128 of file ThreatMapObserver.h.
Member Data Documentation
WeakReference<ThreatMapObserver*> server::zone::objects::tangible::threat::ThreatMapObserverImplementation::_this
Definition at line 94 of file ThreatMapObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<TangibleObject* > server::zone::objects::tangible::threat::ThreatMapObserverImplementation::self protected
Definition at line 85 of file ThreatMapObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/threat/ThreatMapObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/threat/ThreatMapObserver.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/threat/ThreatMapObserverImplementation.cpp