Core3: server::zone::objects::creature::buffs::SingleUseBuffAdapter Class Reference
server::zone::objects::creature::buffs::SingleUseBuffAdapter Class Reference
#include <SingleUseBuff.h>
Public Member Functions
SingleUseBuffAdapter (SingleUseBuff *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
unsigned int getCommandCRC ()
CreatureObject * getPlayer ()
void activate ()
void deactivate ()
Public Member Functions inherited from server::zone::objects::creature::buffs::BuffAdapter
BuffAdapter (Buff *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
void sendTo (CreatureObject *player)
void sendDestroyTo (CreatureObject *player)
void activate (bool applyModifiers)
void deactivate (bool removeModifiers)
void activate ()
void deactivate ()
void applyAttributeModifiers ()
void applySkillModifiers ()
void applyStates ()
void removeAttributeModifiers ()
void removeSkillModifiers ()
void removeStates ()
void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
void parseAttributeModifierString (const String &modifierstring)
void parseSkillModifierString (const String &modifierstring)
String getAttributeModifierString ()
String getSkillModifierString ()
float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
int getAttributeModifierValue (byte attribute)
int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
Detailed Description
Definition at line 189 of file SingleUseBuff.h.
Constructor & Destructor Documentation
SingleUseBuffAdapter::SingleUseBuffAdapter (SingleUseBuff * impl)
Definition at line 354 of file SingleUseBuff.cpp.
Member Function Documentation
void SingleUseBuffAdapter::activate ()
Definition at line 394 of file SingleUseBuff.cpp.
Referenced by invokeMethod().
void SingleUseBuffAdapter::deactivate ()
Definition at line 398 of file SingleUseBuff.cpp.
Referenced by invokeMethod().
unsigned int SingleUseBuffAdapter::getCommandCRC ()
Definition at line 386 of file SingleUseBuff.cpp.
Referenced by invokeMethod().
CreatureObject * SingleUseBuffAdapter::getPlayer ()
Definition at line 390 of file SingleUseBuff.cpp.
Referenced by invokeMethod().
void SingleUseBuffAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 357 of file SingleUseBuff.cpp.
References activate(), deactivate(), getCommandCRC(), getPlayer(), RPC_ACTIVATE__, RPC_DEACTIVATE__, RPC_GETCOMMANDCRC__, and RPC_GETPLAYER__.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SingleUseBuff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/SingleUseBuff.cpp