Core3: server::zone::objects::area::areashapes::AreaShape Class Reference
server::zone::objects::area::areashapes::AreaShape Class Reference
#include <AreaShape.h>
Public Member Functions
AreaShape ()
void setAreaCenter (float x, float y)
Vector3 getAreaCenter ()
bool containsPoint (float x, float y)
virtual bool containsPoint (const Vector3 &point)
float getRadius ()
Vector3 getRandomPosition ()
Vector3 getRandomPosition (const Vector3 &origin, float minDistance, float maxDistance)
bool isCircularAreaShape ()
bool isRectangularAreaShape ()
bool isRingAreaShape ()
bool intersectsWith (AreaShape *areaShape)
float getArea ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
AreaShape (DummyConstructorParameter *param)
virtual ~AreaShape ()
Friends
class AreaShapeHelper
Detailed Description
Definition at line 26 of file AreaShape.h.
Constructor & Destructor Documentation
AreaShape::AreaShape ()
Constructor
Definition at line 13 of file AreaShape.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::_setStub().
AreaShape::AreaShape (DummyConstructorParameter * param) protected
Definition at line 20 of file AreaShape.cpp.
AreaShape::~AreaShape () protected virtual
Definition at line 24 of file AreaShape.cpp.
Member Function Documentation
DistributedObjectServant * AreaShape::_getImplementation ()
Definition at line 174 of file AreaShape.cpp.
Referenced by containsPoint(), getArea(), getAreaCenter(), getRadius(), getRandomPosition(), intersectsWith(), isCircularAreaShape(), isRectangularAreaShape(), isRingAreaShape(), and setAreaCenter().
DistributedObjectServant * AreaShape::_getImplementationForRead ()
Definition at line 180 of file AreaShape.cpp.
void AreaShape::_setImplementation (DistributedObjectServant * servant)
Definition at line 184 of file AreaShape.cpp.
bool AreaShape::containsPoint (float x, float y)
Check if the coordinate is within the area shape.
Parameters
x the x coordinate.
y the y coordinate.
Returns
true if the coordinate is within the area shape.
Definition at line 53 of file AreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::AreaShapeImplementation::containsPoint(), and RPC_CONTAINSPOINT__FLOAT_FLOAT_.
Referenced by server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::intersectsWith().
bool AreaShape::containsPoint (const Vector3 & point) virtual
Check if the coordinate is within the area shape.
Parameters
point the point to check if it is within the area shape.
Returns
true if the coordinate is within the area shape.
Reimplemented in server::zone::objects::area::areashapes::RingAreaShape, server::zone::objects::area::areashapes::RectangularAreaShape, and server::zone::objects::area::areashapes::CircularAreaShape.
Definition at line 68 of file AreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::AreaShapeImplementation::containsPoint().
float AreaShape::getArea ()
Get the area of the areaShape.
Returns
the area of the area shape.
Definition at line 161 of file AreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::AreaShapeImplementation::getArea(), and RPC_GETAREA__.
Vector3 AreaShape::getAreaCenter ()
Get the area center.
Returns
the area center.
Definition at line 44 of file AreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::AreaShapeImplementation::getAreaCenter().
Referenced by server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::intersectsWith(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::intersectsWithCircle(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::intersectsWithCircle(), and server::zone::objects::area::areashapes::RingAreaShapeImplementation::intersectsWithRing().
float AreaShape::getRadius ()
Get the minimum radius of a circle bounding the area shape.
Returns
the minimum bonding radius.
Definition at line 77 of file AreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::AreaShapeImplementation::getRadius(), and RPC_GETRADIUS__.
Vector3 AreaShape::getRandomPosition ()
Generate a random position within the area.
Returns
a random position within the area.
Definition at line 90 of file AreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::AreaShapeImplementation::getRandomPosition().
Vector3 AreaShape::getRandomPosition (const Vector3 & origin, float minDistance, float maxDistance)
Generate a random position within the area with the supplied origin and radius as limits.
Parameters
origin the origin coordinate to generate the random position from.
minDistance the minimum distance from the origin.
maxDistance the maximum distance from the origin.
Returns
a random position within the area.
Definition at line 99 of file AreaShape.cpp.
References _getImplementation(), and server::zone::objects::area::areashapes::AreaShapeImplementation::getRandomPosition().
bool AreaShape::intersectsWith (AreaShape * areaShape)
Check if this area shape intersects with the supplied area shape.
Parameters
areaShape the area shape to check for intersections with.
Returns
true if the area shapes intersects each other.
Definition at line 147 of file AreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::AreaShapeImplementation::intersectsWith(), and RPC_INTERSECTSWITH__AREASHAPE_.
bool AreaShape::isCircularAreaShape ()
Check if this is a circular area shape.
Returns
true if it is a circular area shape.
Definition at line 108 of file AreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::AreaShapeImplementation::isCircularAreaShape(), and RPC_ISCIRCULARAREASHAPE__.
Referenced by server::zone::objects::area::areashapes::CircularAreaShapeImplementation::intersectsWith(), and server::zone::objects::area::areashapes::RingAreaShapeImplementation::intersectsWith().
bool AreaShape::isRectangularAreaShape ()
Check if this is a rectangular area shape.
Returns
true if it is a rectangular area shape.
Definition at line 121 of file AreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::AreaShapeImplementation::isRectangularAreaShape(), and RPC_ISRECTANGULARAREASHAPE__.
Referenced by server::zone::objects::area::areashapes::CircularAreaShapeImplementation::intersectsWith(), and server::zone::objects::area::areashapes::RingAreaShapeImplementation::intersectsWith().
bool AreaShape::isRingAreaShape ()
Check if this is a ring area shape.
Returns
true if it is a ring area shape.
Definition at line 134 of file AreaShape.cpp.
References _getImplementation(), server::zone::objects::area::areashapes::AreaShapeImplementation::isRingAreaShape(), and RPC_ISRINGAREASHAPE__.
Referenced by server::zone::objects::area::areashapes::CircularAreaShapeImplementation::intersectsWith(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::intersectsWith(), and server::zone::objects::area::areashapes::RingAreaShapeImplementation::intersectsWith().
void AreaShape::setAreaCenter (float x, float y)
Set the area center.
Parameters
x the x coordinate.
y the y coordinate.
Definition at line 29 of file AreaShape.cpp.
References _getImplementation(), RPC_SETAREACENTER__FLOAT_FLOAT_, and server::zone::objects::area::areashapes::AreaShapeImplementation::setAreaCenter().
Friends And Related Function Documentation
friend class AreaShapeHelper friend
Definition at line 121 of file AreaShape.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/AreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/AreaShape.cpp