Core3: server::zone::objects::mission::DestroyMissionObjectiveAdapter Class Reference
server::zone::objects::mission::DestroyMissionObjectiveAdapter Class Reference
#include <DestroyMissionObjective.h>
Public Member Functions
DestroyMissionObjectiveAdapter (DestroyMissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
void spawnLair ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void setDifficulty (int diff)
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveAdapter
MissionObjectiveAdapter (MissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Detailed Description
Definition at line 269 of file DestroyMissionObjective.h.
Constructor & Destructor Documentation
DestroyMissionObjectiveAdapter::DestroyMissionObjectiveAdapter (DestroyMissionObjective * impl)
Definition at line 391 of file DestroyMissionObjective.cpp.
Member Function Documentation
void DestroyMissionObjectiveAdapter::abort ()
Definition at line 460 of file DestroyMissionObjective.cpp.
Referenced by invokeMethod().
void DestroyMissionObjectiveAdapter::activate ()
Definition at line 456 of file DestroyMissionObjective.cpp.
Referenced by invokeMethod().
void DestroyMissionObjectiveAdapter::complete ()
Definition at line 464 of file DestroyMissionObjective.cpp.
Referenced by invokeMethod().
void DestroyMissionObjectiveAdapter::destroyObjectFromDatabase ()
Definition at line 472 of file DestroyMissionObjective.cpp.
Referenced by invokeMethod().
void DestroyMissionObjectiveAdapter::finalize ()
Definition at line 448 of file DestroyMissionObjective.cpp.
Referenced by invokeMethod().
void DestroyMissionObjectiveAdapter::initializeTransientMembers ()
Definition at line 452 of file DestroyMissionObjective.cpp.
Referenced by invokeMethod().
void DestroyMissionObjectiveAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 394 of file DestroyMissionObjective.cpp.
References abort(), activate(), complete(), destroyObjectFromDatabase(), finalize(), initializeTransientMembers(), notifyObserverEvent(), RPC_ABORT__, RPC_ACTIVATE__, RPC_COMPLETE__, RPC_DESTROYOBJECTFROMDATABASE__, RPC_FINALIZE__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_, RPC_SETDIFFICULTY__INT_, RPC_SPAWNLAIR__, setDifficulty(), and spawnLair().
int DestroyMissionObjectiveAdapter::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 476 of file DestroyMissionObjective.cpp.
Referenced by invokeMethod().
void DestroyMissionObjectiveAdapter::setDifficulty (int diff)
Definition at line 480 of file DestroyMissionObjective.cpp.
Referenced by invokeMethod().
void DestroyMissionObjectiveAdapter::spawnLair ()
Definition at line 468 of file DestroyMissionObjective.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DestroyMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DestroyMissionObjective.cpp