Core3: DataArchiveStore Class Reference
DataArchiveStore Class Reference
#include <DataArchiveStore.h>
Public Member Functions
DataArchiveStore ()
~DataArchiveStore ()
byte * getData (const String &path, int &size)
int loadTres (String &path, Vector< String > &treFilesToLoad)
IffStream * openIffFile (const String &fileName)
TreeArchive * getTreeArchive ()
Private Attributes
TreeArchive * treeDirectory
Detailed Description
Definition at line 20 of file DataArchiveStore.h.
Constructor & Destructor Documentation
DataArchiveStore::DataArchiveStore ()
Definition at line 11 of file DataArchiveStore.cpp.
References treeDirectory.
DataArchiveStore::~DataArchiveStore ()
Definition at line 15 of file DataArchiveStore.cpp.
References treeDirectory.
Member Function Documentation
byte * DataArchiveStore::getData (const String & path, int & size)
Definition at line 20 of file DataArchiveStore.cpp.
References TreeArchive::getBytes(), and treeDirectory.
Referenced by openIffFile().
TreeArchive* DataArchiveStore::getTreeArchive () inline
Definition at line 34 of file DataArchiveStore.h.
References treeDirectory.
int DataArchiveStore::loadTres (String & path, Vector< String > & treFilesToLoad)
Definition at line 62 of file DataArchiveStore.cpp.
References treeDirectory, and TreeArchive::unpackFile().
IffStream * DataArchiveStore::openIffFile (const String & fileName)
Definition at line 97 of file DataArchiveStore.cpp.
References getData().
Member Data Documentation
TreeArchive* DataArchiveStore::treeDirectory private
Definition at line 21 of file DataArchiveStore.h.
Referenced by DataArchiveStore(), getData(), getTreeArchive(), loadTres(), and ~DataArchiveStore().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/templates/DataArchiveStore.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/templates/DataArchiveStore.cpp