Core3: PlaceGCWBaseComponent Class Reference
PlaceGCWBaseComponent Class Reference
#include <PlaceGCWBaseComponent.h>
Public Member Functions
int placeStructure (StructureDeed *deed, CreatureObject *creature, float x, float y, int angle)
int notifyStructurePlaced (StructureDeed *deed, CreatureObject *creature, StructureObject *structure)
Detailed Description
Definition at line 13 of file PlaceGCWBaseComponent.h.
Member Function Documentation
int PlaceGCWBaseComponent::notifyStructurePlaced (StructureDeed * deed, CreatureObject * creature, StructureObject * structure) virtual
Reimplemented from PlaceStructureComponent.
Definition at line 43 of file PlaceGCWBaseComponent.cpp.
References server::zone::Zone::getGCWManager(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isGCWBase(), PlaceStructureComponent::notifyStructurePlaced(), and server::zone::managers::gcw::GCWManager::registerGCWBase().
int PlaceGCWBaseComponent::placeStructure (StructureDeed * deed, CreatureObject * creature, float x, float y, int angle) virtual
Reimplemented from PlaceStructureComponent.
Definition at line 17 of file PlaceGCWBaseComponent.cpp.
References server::zone::Zone::getGCWManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::managers::gcw::GCWManager::isPlanetCapped(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/deed/components/PlaceGCWBaseComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/deed/components/PlaceGCWBaseComponent.cpp