Core3: server::zone::managers::objectcontroller::ObjectController Class Reference
server::zone::managers::objectcontroller::ObjectController Class Reference
#include <ObjectController.h>
Public Member Functions
ObjectController (ZoneProcessServer *srv)
void loadCommands ()
bool transferObject (SceneObject *objectToTransfer, SceneObject *destinationObject, int containmentType, bool notifyClient=false)
float activateCommand (CreatureObject *object, unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString &arguments)
void addQueueCommand (QueueCommand *command)
QueueCommand * getQueueCommand (const String &name)
QueueCommand * getQueueCommand (unsigned int crc)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ObjectController (DummyConstructorParameter *param)
virtual ~ObjectController ()
Friends
class ObjectControllerHelper
Detailed Description
Definition at line 121 of file ObjectController.h.
Constructor & Destructor Documentation
ObjectController::ObjectController (ZoneProcessServer * srv)
Definition at line 27 of file ObjectController.cpp.
References server::zone::managers::objectcontroller::ObjectControllerImplementation::_setStub().
ObjectController::ObjectController (DummyConstructorParameter * param) protected
Definition at line 34 of file ObjectController.cpp.
ObjectController::~ObjectController () protected virtual
Definition at line 38 of file ObjectController.cpp.
Member Function Documentation
DistributedObjectServant * ObjectController::_getImplementation ()
Definition at line 118 of file ObjectController.cpp.
Referenced by activateCommand(), addQueueCommand(), getQueueCommand(), loadCommands(), and transferObject().
DistributedObjectServant * ObjectController::_getImplementationForRead ()
Definition at line 124 of file ObjectController.cpp.
void ObjectController::_setImplementation (DistributedObjectServant * servant)
Definition at line 128 of file ObjectController.cpp.
float ObjectController::activateCommand (CreatureObject * object, unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString & arguments)
Activates a queue command from a creature object
Parameters
object creature object that the command will be run on
actionCRC crc of the command to run
actionCount count of the command targetID target object id
arguments arguments of the command
Returns
time in seconds of command execution
Definition at line 73 of file ObjectController.cpp.
References _getImplementation(), server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand(), and RPC_ACTIVATECOMMAND__CREATUREOBJECT_INT_INT_LONG_UNICODESTRING_.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::activateImmediateAction(), server::zone::objects::creature::CreatureObjectImplementation::activateQueueAction(), MountCommand::doQueueCommand(), server::zone::objects::creature::CreatureObjectImplementation::executeObjectControllerAction(), and DataTransformWithParentCallback::updatePosition().
void ObjectController::addQueueCommand (QueueCommand * command)
Definition at line 91 of file ObjectController.cpp.
References _getImplementation(), and server::zone::managers::objectcontroller::ObjectControllerImplementation::addQueueCommand().
QueueCommand * ObjectController::getQueueCommand (const String & name)
Definition at line 100 of file ObjectController.cpp.
References _getImplementation(), and server::zone::managers::objectcontroller::ObjectControllerImplementation::getQueueCommand().
QueueCommand * ObjectController::getQueueCommand (unsigned int crc)
Definition at line 109 of file ObjectController.cpp.
References _getImplementation(), and server::zone::managers::objectcontroller::ObjectControllerImplementation::getQueueCommand().
void ObjectController::loadCommands ()
Definition at line 43 of file ObjectController.cpp.
References _getImplementation(), server::zone::managers::objectcontroller::ObjectControllerImplementation::loadCommands(), and RPC_LOADCOMMANDS__.
bool ObjectController::transferObject (SceneObject * objectToTransfer, SceneObject * destinationObject, int containmentType, bool notifyClient = false)
Definition at line 56 of file ObjectController.cpp.
References _getImplementation(), RPC_TRANSFEROBJECT__SCENEOBJECT_SCENEOBJECT_INT_BOOL_, and server::zone::managers::objectcontroller::ObjectControllerImplementation::transferObject().
Referenced by TransferItemArmorCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), and TransferItemMiscCommand::doQueueCommand().
Friends And Related Function Documentation
friend class ObjectControllerHelper friend
Definition at line 156 of file ObjectController.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/objectcontroller/ObjectController.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/objectcontroller/ObjectController.cpp