Core3: PerformanceManager Class Reference
PerformanceManager Class Reference
#include <PerformanceManager.h>
Public Member Functions
PerformanceManager ()
~PerformanceManager ()
Performance * getDance (const String &name)
Performance * getSong (const String &name, int instrumentType)
Vector< Performance * > getPerformanceListFromMod (const String &requiredSkillMod, int playerSkillModValue, int instrument)
int getInstrumentAnimation (int instrumentType, String &instrumentAnimation)
String getInstrument (int instrumentType)
String getDanceAnimation (const String &dance)
int getInstrumentId (const String &song)
bool hasInstrumentId (const String &song)
bool hasDanceAnimation (const String &dance)
Private Member Functions
void loadPerformances ()
Private Attributes
HashTable< String, String > danceMap
HashTable< String, int > instrumentIdMap
Vector< Performance * > * performances
int loadedCount
Detailed Description
Definition at line 54 of file PerformanceManager.h.
Constructor & Destructor Documentation
PerformanceManager::PerformanceManager ()
Definition at line 54 of file PerformanceManager.cpp.
References danceMap, instrumentIdMap, and loadPerformances().
PerformanceManager::~PerformanceManager ()
Definition at line 194 of file PerformanceManager.cpp.
References performances.
Member Function Documentation
Performance * PerformanceManager::getDance (const String & name)
Definition at line 264 of file PerformanceManager.cpp.
References Performance::getName(), Performance::isDance(), and performances.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::doEntertainerPatronEffects(), server::zone::objects::player::sessions::EntertainingSessionImplementation::doFlourish(), server::zone::objects::player::sessions::EntertainingSessionImplementation::doPerformanceAction(), and server::zone::objects::player::sessions::EntertainingSessionImplementation::increaseEntertainerBuff().
String PerformanceManager::getDanceAnimation (const String & dance) inline
Definition at line 78 of file PerformanceManager.h.
References danceMap.
Referenced by ChangeDanceCommand::doQueueCommand(), and StartDanceCommand::doQueueCommand().
String PerformanceManager::getInstrument (int instrumentType)
Definition at line 152 of file PerformanceManager.cpp.
Referenced by StartBandCommand::canPlayInstrument(), ChangeBandMusicCommand::canPlaySong(), ChangeMusicCommand::doQueueCommand(), ChangeBandMusicCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), and getPerformanceListFromMod().
int PerformanceManager::getInstrumentAnimation (int instrumentType, String & instrumentAnimation)
Definition at line 99 of file PerformanceManager.cpp.
Referenced by StartBandCommand::doQueueCommand(), ChangeMusicCommand::doQueueCommand(), ChangeBandMusicCommand::doQueueCommand(), and StartMusicCommand::doQueueCommand().
int PerformanceManager::getInstrumentId (const String & song) inline
Definition at line 82 of file PerformanceManager.h.
References instrumentIdMap.
Referenced by StartBandCommand::doQueueCommand(), ChangeMusicCommand::doQueueCommand(), ChangeBandMusicCommand::doQueueCommand(), and StartMusicCommand::doQueueCommand().
Vector< Performance * > PerformanceManager::getPerformanceListFromMod (const String & requiredSkillMod, int playerSkillModValue, int instrument)
Definition at line 233 of file PerformanceManager.cpp.
References getInstrument(), Performance::getRequiredInstrument(), Performance::getRequiredSkillMod(), Performance::getRequiredSkillModValue(), and performances.
Performance * PerformanceManager::getSong (const String & name, int instrumentType)
Definition at line 277 of file PerformanceManager.cpp.
References Performance::getInstrumentAudioId(), Performance::getName(), Performance::isMusic(), and performances.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::doEntertainerPatronEffects(), server::zone::objects::player::sessions::EntertainingSessionImplementation::doFlourish(), server::zone::objects::player::sessions::EntertainingSessionImplementation::doPerformanceAction(), and server::zone::objects::player::sessions::EntertainingSessionImplementation::increaseEntertainerBuff().
bool PerformanceManager::hasDanceAnimation (const String & dance) inline
Definition at line 90 of file PerformanceManager.h.
References danceMap.
Referenced by ChangeDanceCommand::doQueueCommand(), and StartDanceCommand::doQueueCommand().
bool PerformanceManager::hasInstrumentId (const String & song) inline
Definition at line 86 of file PerformanceManager.h.
References instrumentIdMap.
Referenced by StartBandCommand::doQueueCommand(), ChangeMusicCommand::doQueueCommand(), ChangeBandMusicCommand::doQueueCommand(), and StartMusicCommand::doQueueCommand().
void PerformanceManager::loadPerformances () private
Definition at line 205 of file PerformanceManager.cpp.
References DataTableIff::getRow(), DataTableIff::getTotalRows(), Performance::parseDataTableRow(), performances, and DataTableIff::readObject().
Referenced by PerformanceManager().
Member Data Documentation
HashTable<String, String> PerformanceManager::danceMap private
Definition at line 55 of file PerformanceManager.h.
Referenced by getDanceAnimation(), hasDanceAnimation(), and PerformanceManager().
HashTable<String, int> PerformanceManager::instrumentIdMap private
Definition at line 56 of file PerformanceManager.h.
Referenced by getInstrumentId(), hasInstrumentId(), and PerformanceManager().
int PerformanceManager::loadedCount private
Definition at line 59 of file PerformanceManager.h.
Vector<Performance*>* PerformanceManager::performances private
Definition at line 58 of file PerformanceManager.h.
Referenced by getDance(), getPerformanceListFromMod(), getSong(), loadPerformances(), and ~PerformanceManager().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/skill/PerformanceManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/skill/PerformanceManager.cpp