Core3: server::web::WebServer Class Reference
server::web::WebServer Class Reference
#include <WebServer.h>
Public Member Functions
WebServer ()
~WebServer ()
void start (ConfigManager *conf)
void stop ()
bool addContext (String context, Servlet *servlet)
bool authorize (HttpSession *session)
void dispatch (String location, HttpSession *session)
void forward (struct mg_connection *conn, String content, HttpRequest *request)
Static Public Member Functions
static void * uriHandler (enum mg_event event, struct mg_connection *conn, const struct mg_request_info *request_info)
Static Public Attributes
static int sessionTimeout
Private Member Functions
void init ()
void registerBaseContexts ()
void whitelistInit ()
void mongooseMgrInit ()
void * handleRequest (struct mg_connection *conn, const struct mg_request_info *request_info)
ManagedReference< Account * > validateAccountCredentials (LoginClient *client, const String &username, const String &password)
HttpSession * getSession (struct mg_connection *conn, const struct mg_request_info *request_info)
bool validateIPAccess (long remoteIp)
void displayUnauthorized (struct mg_connection *conn)
void displayNotFound (struct mg_connection *conn)
void displayUnauthorized (StringBuffer *out)
void displayLogin (StringBuffer *out)
bool isValidIp (String address)
bool isLocalHost (long address)
bool isLocalHost (String address)
uint32 ipStringToLong (String address)
String ipLongToString (long address)
Private Attributes
ManagedReference< ZoneServer * > zoneServer
ConfigManager * configManager
VectorMap< String, Servlet * > contexts
VectorMap< String,
WebCredentials * > authorizedUsers
VectorMap< uint64,
HttpSessionList * > activeSessions
Vector< String > authorizedIpAddresses
Static Private Attributes
static struct mg_context * ctx
Detailed Description
Definition at line 71 of file WebServer.h.
Constructor & Destructor Documentation
WebServer::WebServer ()
Definition at line 60 of file WebServer.cpp.
References configManager, sessionTimeout, and zoneServer.
WebServer::~WebServer ()
Definition at line 76 of file WebServer.cpp.
References activeSessions, authorizedUsers, and contexts.
Member Function Documentation
bool WebServer::addContext (String context, Servlet * servlet)
Definition at line 219 of file WebServer.cpp.
References contexts, Servlet::setZoneServer(), and zoneServer.
Referenced by registerBaseContexts().
bool WebServer::authorize (HttpSession * session)
Remove Password
Definition at line 452 of file WebServer.cpp.
References authorizedUsers, server::web::session::HttpSession::getPassword(), server::web::session::HttpSession::getUserName(), server::web::session::HttpSession::setAuthenticated(), server::web::session::HttpSession::setPassword(), and validateAccountCredentials().
void WebServer::dispatch (String location, HttpSession * session)
Definition at line 291 of file WebServer.cpp.
References contexts, server::web::session::HttpSession::getRequest(), server::web::session::HttpSession::getResponse(), and Servlet::handleGet().
void WebServer::displayLogin (StringBuffer * out) private
Definition at line 448 of file WebServer.cpp.
void WebServer::displayNotFound (struct mg_connection * conn) private
Definition at line 437 of file WebServer.cpp.
References mg_printf().
Referenced by handleRequest().
void WebServer::displayUnauthorized (struct mg_connection * conn) private
Definition at line 426 of file WebServer.cpp.
References mg_printf().
void server::web::WebServer::displayUnauthorized (StringBuffer * out) private
void WebServer::forward (struct mg_connection * conn, String content, HttpRequest * request)
Definition at line 301 of file WebServer.cpp.
References mg_printf().
Referenced by handleRequest().
HttpSession * WebServer::getSession (struct mg_connection * conn, const struct mg_request_info * request_info) private
Find existing session, or create new one if one doesn't exist or has timed out
Get Post Data
Ensure no stack corruption
Definition at line 322 of file WebServer.cpp.
References activeSessions, server::web::HttpRequest::getHeader(), server::web::session::HttpSession::getRequest(), server::web::session::HttpSession::getSessionId(), server::web::session::HttpSession::hasExpired(), mg_read(), mg_request_info::remote_ip, server::web::session::HttpSession::setSessionId(), server::web::session::HttpSession::setSessionIp(), server::web::session::HttpSession::update(), and server::web::HttpRequest::updatePostData().
Referenced by handleRequest().
void * WebServer::handleRequest (struct mg_connection * conn, const struct mg_request_info * request_info) private
First we validate the IP address to see if we should proceed
If it's a CSS request grant request
If the session isn't valid, only the login servlet is Accessable
Definition at line 237 of file WebServer.cpp.
References contexts, displayNotFound(), forward(), server::web::HttpRequest::getBaseContext(), Servlet::getContext(), server::web::session::HttpSession::getRequest(), server::web::session::HttpSession::getResponse(), getSession(), server::web::HttpRequest::getUri(), Servlet::handleRequest(), and server::web::session::HttpSession::isAuthenticated().
void WebServer::init () private
Definition at line 105 of file WebServer.cpp.
References mongooseMgrInit(), registerBaseContexts(), and whitelistInit().
Referenced by start().
String WebServer::ipLongToString (long address) private
Definition at line 572 of file WebServer.cpp.
uint32 WebServer::ipStringToLong (String address) private
Definition at line 535 of file WebServer.cpp.
Referenced by isValidIp(), and validateIPAccess().
bool WebServer::isLocalHost (long address) private
Definition at line 523 of file WebServer.cpp.
bool WebServer::isLocalHost (String address) private
Definition at line 519 of file WebServer.cpp.
bool WebServer::isValidIp (String address) private
Definition at line 527 of file WebServer.cpp.
References ipStringToLong().
Referenced by whitelistInit().
void WebServer::mongooseMgrInit () private
Definition at line 195 of file WebServer.cpp.
References configManager, ctx, server::conf::ConfigManager::getWebAccessLog(), server::conf::ConfigManager::getWebErrorLog(), server::conf::ConfigManager::getWebPorts(), server::conf::ConfigManager::getWebSessionTimeout(), mg_start(), sessionTimeout, and uriHandler().
Referenced by init().
void WebServer::registerBaseContexts () private
Definition at line 114 of file WebServer.cpp.
References addContext().
Referenced by init().
void WebServer::start (ConfigManager * conf)
Definition at line 92 of file WebServer.cpp.
References configManager, and init().
Referenced by ServerCore::initialize().
void WebServer::stop ()
Definition at line 101 of file WebServer.cpp.
References ctx, and mg_stop().
Referenced by ServerCore::shutdown().
void * WebServer::uriHandler (enum mg_event event, struct mg_connection * conn, const struct mg_request_info * request_info) static
Definition at line 229 of file WebServer.cpp.
Referenced by mongooseMgrInit().
ManagedReference< Account * > WebServer::validateAccountCredentials (LoginClient * client, const String & username, const String & password) private
Definition at line 486 of file WebServer.cpp.
References configManager, server::conf::ConfigManager::getDBSecret(), ServerDatabase::instance(), and zoneServer.
Referenced by authorize().
bool WebServer::validateIPAccess (long remoteIp) private
Check session IP against valid ip addresses to deny access
Definition at line 413 of file WebServer.cpp.
References authorizedIpAddresses, and ipStringToLong().
void WebServer::whitelistInit () private
Definition at line 124 of file WebServer.cpp.
References WebCredentials::addInetAddress(), authorizedIpAddresses, authorizedUsers, isValidIp(), and zoneServer.
Referenced by init().
Member Data Documentation
VectorMap<uint64, HttpSessionList*> server::web::WebServer::activeSessions private
Definition at line 81 of file WebServer.h.
Referenced by getSession(), and ~WebServer().
Vector<String> server::web::WebServer::authorizedIpAddresses private
Definition at line 82 of file WebServer.h.
Referenced by validateIPAccess(), and whitelistInit().
VectorMap<String, WebCredentials*> server::web::WebServer::authorizedUsers private
Definition at line 80 of file WebServer.h.
Referenced by authorize(), whitelistInit(), and ~WebServer().
ConfigManager* server::web::WebServer::configManager private
Definition at line 75 of file WebServer.h.
Referenced by mongooseMgrInit(), start(), validateAccountCredentials(), and WebServer().
VectorMap<String, Servlet*> server::web::WebServer::contexts private
Definition at line 79 of file WebServer.h.
Referenced by addContext(), dispatch(), handleRequest(), and ~WebServer().
mg_context * WebServer::ctx static private
Definition at line 77 of file WebServer.h.
Referenced by mongooseMgrInit(), and stop().
int WebServer::sessionTimeout static
Definition at line 85 of file WebServer.h.
Referenced by server::web::session::HttpSession::hasExpired(), mongooseMgrInit(), and WebServer().
ManagedReference<ZoneServer*> server::web::WebServer::zoneServer private
Definition at line 73 of file WebServer.h.
Referenced by addContext(), validateAccountCredentials(), WebServer(), and whitelistInit().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/WebServer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/WebServer.cpp