Core3: WearableObjectMenuComponent Class Reference
WearableObjectMenuComponent Class Reference
#include <WearableObjectMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file WearableObjectMenuComponent.h.
Member Function Documentation
void WearableObjectMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from TangibleObjectMenuComponent.
Reimplemented in ArmorObjectMenuComponent.
Definition at line 17 of file WearableObjectMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::objects::tangible::TangibleObject::canRepair(), TangibleObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::tangible::TangibleObject::getConditionDamage(), and server::zone::objects::scene::SceneObject::isTangibleObject().
Referenced by ArmorObjectMenuComponent::fillObjectMenuResponse().
int WearableObjectMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from TangibleObjectMenuComponent.
Reimplemented in ArmorObjectMenuComponent.
Definition at line 34 of file WearableObjectMenuComponent.cpp.
References TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::scene::SceneObject::isASubChildOf(), server::zone::objects::scene::SceneObject::isTangibleObject(), and server::zone::objects::tangible::TangibleObject::repair().
Referenced by ArmorObjectMenuComponent::handleObjectMenuSelect().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/WearableObjectMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/WearableObjectMenuComponent.cpp