Core3: server::zone::objects::mission::DeliverMissionObjective Class Reference
server::zone::objects::mission::DeliverMissionObjective Class Reference
#include <DeliverMissionObjective.h>
Public Member Functions
DeliverMissionObjective (MissionObject *mission)
void initializeTransientMembers ()
TangibleObject * getItem ()
int getObjectiveStatus ()
void activate ()
void deactivate ()
bool activateWithResult ()
void abort ()
void complete ()
void despawnNpcs ()
void updateMissionStatus (CreatureObject *player)
bool updateMissionTarget (CreatureObject *player)
NpcSpawnPoint * getTargetSpawnPoint ()
NpcSpawnPoint * getDestinationSpawnPoint ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (MissionObject *parent)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int INITSTATUS = 0
static const int PICKEDUPSTATUS = 1
static const int DELIVEREDSTATUS = 2
Protected Member Functions
DeliverMissionObjective (DummyConstructorParameter *param)
virtual ~DeliverMissionObjective ()
Protected Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (DummyConstructorParameter *param)
virtual ~MissionObjective ()
Friends
class DeliverMissionObjectiveHelper
Detailed Description
Definition at line 139 of file DeliverMissionObjective.h.
Constructor & Destructor Documentation
DeliverMissionObjective::DeliverMissionObjective (MissionObject * mission)
Definition at line 29 of file DeliverMissionObjective.cpp.
References server::zone::objects::mission::DeliverMissionObjectiveImplementation::_setStub().
DeliverMissionObjective::DeliverMissionObjective (DummyConstructorParameter * param) protected
Definition at line 36 of file DeliverMissionObjective.cpp.
DeliverMissionObjective::~DeliverMissionObjective () protected virtual
Definition at line 40 of file DeliverMissionObjective.cpp.
Member Function Documentation
DistributedObjectServant * DeliverMissionObjective::_getImplementation ()
Definition at line 216 of file DeliverMissionObjective.cpp.
Referenced by abort(), activate(), activateWithResult(), complete(), deactivate(), despawnNpcs(), getDestinationSpawnPoint(), getItem(), getObjectiveStatus(), getTargetSpawnPoint(), initializeTransientMembers(), updateMissionStatus(), and updateMissionTarget().
DistributedObjectServant * DeliverMissionObjective::_getImplementationForRead ()
Definition at line 222 of file DeliverMissionObjective.cpp.
void DeliverMissionObjective::_setImplementation (DistributedObjectServant * servant)
Definition at line 226 of file DeliverMissionObjective.cpp.
void DeliverMissionObjective::abort ()
Definition at line 123 of file DeliverMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::abort(), and RPC_ABORT__.
void DeliverMissionObjective::activate ()
Definition at line 84 of file DeliverMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::activate(), and RPC_ACTIVATE__.
bool DeliverMissionObjective::activateWithResult ()
Definition at line 110 of file DeliverMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::activateWithResult(), and RPC_ACTIVATEWITHRESULT__.
void DeliverMissionObjective::complete ()
Definition at line 136 of file DeliverMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::complete(), and RPC_COMPLETE__.
void DeliverMissionObjective::deactivate ()
Definition at line 97 of file DeliverMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::deactivate(), and RPC_DEACTIVATE__.
void DeliverMissionObjective::despawnNpcs ()
Definition at line 149 of file DeliverMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::despawnNpcs(), and RPC_DESPAWNNPCS__.
NpcSpawnPoint * DeliverMissionObjective::getDestinationSpawnPoint ()
Definition at line 203 of file DeliverMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::getDestinationSpawnPoint(), and RPC_GETDESTINATIONSPAWNPOINT__.
Referenced by server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::isDestinationNpc().
TangibleObject * DeliverMissionObjective::getItem ()
Definition at line 58 of file DeliverMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::getItem(), and RPC_GETITEM__.
int DeliverMissionObjective::getObjectiveStatus ()
Definition at line 71 of file DeliverMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::getObjectiveStatus(), and RPC_GETOBJECTIVESTATUS__.
Referenced by server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::handleScreen().
NpcSpawnPoint * DeliverMissionObjective::getTargetSpawnPoint ()
Definition at line 190 of file DeliverMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::getTargetSpawnPoint(), and RPC_GETTARGETSPAWNPOINT__.
Referenced by server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::isTargetNpc().
void DeliverMissionObjective::initializeTransientMembers ()
Definition at line 45 of file DeliverMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
void DeliverMissionObjective::updateMissionStatus (CreatureObject * player)
Definition at line 162 of file DeliverMissionObjective.cpp.
References _getImplementation(), RPC_UPDATEMISSIONSTATUS__CREATUREOBJECT_, and server::zone::objects::mission::DeliverMissionObjectiveImplementation::updateMissionStatus().
Referenced by server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::handleScreen().
bool DeliverMissionObjective::updateMissionTarget (CreatureObject * player)
Definition at line 176 of file DeliverMissionObjective.cpp.
References _getImplementation(), RPC_UPDATEMISSIONTARGET__CREATUREOBJECT_, and server::zone::objects::mission::DeliverMissionObjectiveImplementation::updateMissionTarget().
Friends And Related Function Documentation
friend class DeliverMissionObjectiveHelper friend
Definition at line 185 of file DeliverMissionObjective.h.
Member Data Documentation
const int server::zone::objects::mission::DeliverMissionObjective::DELIVEREDSTATUS = 2 static
Definition at line 145 of file DeliverMissionObjective.h.
const int server::zone::objects::mission::DeliverMissionObjective::INITSTATUS = 0 static
Definition at line 141 of file DeliverMissionObjective.h.
const int server::zone::objects::mission::DeliverMissionObjective::PICKEDUPSTATUS = 1 static
Definition at line 143 of file DeliverMissionObjective.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DeliverMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DeliverMissionObjective.cpp