Core3: server::zone::objects::manufactureschematic::ManufactureSchematicImplementation Class Reference
server::zone::objects::manufactureschematic::ManufactureSchematicImplementation Class Reference
#include <ManufactureSchematic.h>
Public Member Functions
ManufactureSchematicImplementation ()
ManufactureSchematicImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
virtual void sendTo (SceneObject *player, bool doClose)
void sendBaselinesTo (SceneObject *player)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
bool isManufactureSchematic ()
void setDraftSchematic (DraftSchematic *schematic)
int addIngredientToSlot (CreatureObject *player, SceneObject *satchel, TangibleObject *tano, int slot)
int removeIngredientFromSlot (CreatureObject *player, TangibleObject *tano, int slot)
void cleanupIngredientSlots (CreatureObject *player)
DraftSchematic * getDraftSchematic ()
void increaseComplexity ()
void decreaseComplexity ()
float getComplexity ()
bool isReadyForAssembly ()
void setAssembled ()
bool isAssembled ()
void setCompleted ()
bool isCompleted ()
int getSlotCount ()
IngredientSlot * getSlot (int i)
void setCrafter (CreatureObject *player)
CreatureObject * getCrafter ()
CraftingValues * getCraftingValues ()
void setExperimentingCounter (int value)
int getExperimentingCounter ()
int getExperimentingCounterPrevious ()
int getIngredientCounter ()
void setManufactureLimit (int limit)
int getManufactureLimit ()
void setPrototype (TangibleObject *tano)
TangibleObject * getPrototype ()
void canManufactureItem (String &type, String &displayedName)
void manufactureItem (FactoryObject *factory)
void createFactoryBlueprint ()
int getBlueprintSize ()
BlueprintEntry * getBlueprintEntry (int i)
bool allowFactoryRun ()
int getLabratory ()
operator const ManufactureSchematic * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::intangible::IntangibleObjectImplementation
IntangibleObjectImplementation ()
IntangibleObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializeTransientMembers ()
void loadTemplateData (SharedObjectTemplate *templateData)
bool isIntangibleObject ()
void updateStatus (int newStatus, bool notifyClient=true)
unsigned int getStatus ()
operator const IntangibleObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
virtual void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
virtual int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWeaponObject ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isTangibleObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
virtual void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< ManufactureSchematic * > _this
Public Attributes inherited from server::zone::objects::intangible::IntangibleObjectImplementation
WeakReference< IntangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Protected Member Functions
virtual ~ManufactureSchematicImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::intangible::IntangibleObjectImplementation
virtual ~IntangibleObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference
< DraftSchematic * > draftSchematic
ManagedReference
< TangibleObject * > prototype
float dataSize
int manufactureLimit
float complexity
ManagedReference
< CreatureObject * > crafter
FactoryBlueprint factoryBlueprint
Vector< Reference
< IngredientSlot * > > ingredientSlots
StringIdDeltaVector ingredientNames
DeltaVector< int > ingredientTypes
Uint64VectorDeltaVector slotOIDs
IntVectorDeltaVector slotQuantities
DeltaVector< float > slotQualities
DeltaVector< int > slotClean
DeltaVector< int > slotIndexes
bool assembled
bool completed
bool initialized
int ingredientCounter
int experimentingCounter
int experimentingCounterPrevious
bool possibleSyncIssue
Reference< CraftingValues * > craftingValues
Vector< byte > customizationOptions
Vector< byte > customizationDefaultValues
Protected Attributes inherited from server::zone::objects::intangible::IntangibleObjectImplementation
unsigned int status
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Private Member Functions
void sendMsco7 (SceneObject *player)
void initializeIngredientSlots ()
void sendDelta7 (IngredientSlot *ingredientSlot, int slot, CreatureObject *player)
void updateIngredientCounter ()
Friends
class ManufactureSchematic
Detailed Description
Definition at line 280 of file ManufactureSchematic.h.
Constructor & Destructor Documentation
ManufactureSchematicImplementation::ManufactureSchematicImplementation ()
Definition at line 808 of file ManufactureSchematic.cpp.
References _initializeImplementation(), assembled, server::zone::objects::scene::variables::ContainerPermissions::clearDefaultDenyPermission(), server::zone::objects::scene::variables::ContainerPermissions::clearDenyPermission(), completed, complexity, crafter, craftingValues, dataSize, draftSchematic, experimentingCounter, experimentingCounterPrevious, ingredientCounter, initialized, manufactureLimit, possibleSyncIssue, and prototype.
ManufactureSchematicImplementation::ManufactureSchematicImplementation (DummyConstructorParameter * param)
Definition at line 586 of file ManufactureSchematic.cpp.
References _initializeImplementation().
ManufactureSchematicImplementation::~ManufactureSchematicImplementation () protected virtual
Definition at line 591 of file ManufactureSchematic.cpp.
Member Function Documentation
DistributedObjectStub * ManufactureSchematicImplementation::_getStub ()
Definition at line 611 of file ManufactureSchematic.cpp.
References _this.
void ManufactureSchematicImplementation::_initializeImplementation () protected
Definition at line 598 of file ManufactureSchematic.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ManufactureSchematicImplementation().
void ManufactureSchematicImplementation::_serializationHelperMethod () protected
Definition at line 647 of file ManufactureSchematic.cpp.
Referenced by _initializeImplementation().
void ManufactureSchematicImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 606 of file ManufactureSchematic.cpp.
References _this.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::ManufactureSchematic().
int ManufactureSchematicImplementation::addIngredientToSlot (CreatureObject * player, SceneObject * satchel, TangibleObject * tano, int slot)
Delta 7
Definition at line 378 of file ManufactureSchematicImplementation.cpp.
References _this, DeltaMessage::close(), IngredientSlot::FULL, getComplexity(), increaseComplexity(), ingredientSlots, ManufactureSchematicObjectDeltaMessage6::insertToResourceSlot(), IngredientSlot::INVALID, IngredientSlot::INVALIDINGREDIENT, IngredientSlot::OK, possibleSyncIssue, sendDelta7(), server::zone::objects::creature::CreatureObject::sendMessage(), sendMsco7(), ManufactureSchematicObjectDeltaMessage3::updateComplexity(), and updateIngredientCounter().
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::addIngredientToSlot().
bool ManufactureSchematicImplementation::allowFactoryRun ()
Definition at line 633 of file ManufactureSchematicImplementation.cpp.
References draftSchematic.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::allowFactoryRun().
void ManufactureSchematicImplementation::canManufactureItem (String & type, String & displayedName)
Definition at line 964 of file ManufactureSchematic.cpp.
References factoryBlueprint.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::canManufactureItem().
void ManufactureSchematicImplementation::cleanupIngredientSlots (CreatureObject * player)
Definition at line 518 of file ManufactureSchematicImplementation.cpp.
References _this, assembled, and ingredientSlots.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::cleanupIngredientSlots().
void ManufactureSchematicImplementation::createFactoryBlueprint ()
Definition at line 610 of file ManufactureSchematicImplementation.cpp.
References FactoryBlueprint::addIngredient(), server::zone::objects::scene::SceneObjectImplementation::error(), factoryBlueprint, server::zone::objects::scene::SceneObjectImplementation::getDisplayedName(), and ingredientSlots.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::createFactoryBlueprint(), and setPrototype().
void ManufactureSchematicImplementation::decreaseComplexity ()
Definition at line 871 of file ManufactureSchematic.cpp.
References complexity.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::decreaseComplexity(), and removeIngredientFromSlot().
void ManufactureSchematicImplementation::fillAttributeList (AttributeListMessage * msg, CreatureObject * object) virtual
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 67 of file ManufactureSchematicImplementation.cpp.
References dataSize, server::zone::objects::scene::SceneObjectImplementation::error(), factoryBlueprint, FactoryBlueprint::getCompleteEntry(), FactoryBlueprint::getCompleteSize(), server::zone::packets::scene::AttributeListMessage::insertAttribute(), BlueprintEntry::insertSchematicAttribute(), manufactureLimit, and prototype.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::fillAttributeList().
void ManufactureSchematicImplementation::finalize () protected
Definition at line 595 of file ManufactureSchematic.cpp.
BlueprintEntry * ManufactureSchematicImplementation::getBlueprintEntry (int i)
Definition at line 981 of file ManufactureSchematic.cpp.
References factoryBlueprint.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getBlueprintEntry().
int ManufactureSchematicImplementation::getBlueprintSize ()
Definition at line 976 of file ManufactureSchematic.cpp.
References factoryBlueprint.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getBlueprintSize().
float ManufactureSchematicImplementation::getComplexity ()
Definition at line 877 of file ManufactureSchematic.cpp.
References complexity.
Referenced by addIngredientToSlot(), server::zone::objects::manufactureschematic::ManufactureSchematic::getComplexity(), and removeIngredientFromSlot().
CreatureObject * ManufactureSchematicImplementation::getCrafter ()
Definition at line 912 of file ManufactureSchematic.cpp.
References crafter.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getCrafter().
CraftingValues * ManufactureSchematicImplementation::getCraftingValues ()
Definition at line 917 of file ManufactureSchematic.cpp.
References craftingValues.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getCraftingValues().
DraftSchematic * ManufactureSchematicImplementation::getDraftSchematic ()
Definition at line 861 of file ManufactureSchematic.cpp.
References draftSchematic.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getDraftSchematic().
int ManufactureSchematicImplementation::getExperimentingCounter ()
Definition at line 929 of file ManufactureSchematic.cpp.
References experimentingCounter.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getExperimentingCounter().
int ManufactureSchematicImplementation::getExperimentingCounterPrevious ()
Definition at line 934 of file ManufactureSchematic.cpp.
References experimentingCounterPrevious.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getExperimentingCounterPrevious().
int ManufactureSchematicImplementation::getIngredientCounter ()
Definition at line 944 of file ManufactureSchematic.cpp.
References ingredientCounter.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getIngredientCounter(), and sendMsco7().
int ManufactureSchematicImplementation::getLabratory ()
Definition at line 638 of file ManufactureSchematicImplementation.cpp.
References draftSchematic.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getLabratory().
int ManufactureSchematicImplementation::getManufactureLimit ()
Definition at line 954 of file ManufactureSchematic.cpp.
References manufactureLimit.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getManufactureLimit(), and manufactureItem().
TangibleObject * ManufactureSchematicImplementation::getPrototype ()
Definition at line 959 of file ManufactureSchematic.cpp.
References prototype.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getPrototype().
IngredientSlot * ManufactureSchematicImplementation::getSlot (int i)
Definition at line 902 of file ManufactureSchematic.cpp.
References ingredientSlots.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getSlot().
int ManufactureSchematicImplementation::getSlotCount ()
Definition at line 897 of file ManufactureSchematic.cpp.
References ingredientSlots.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::getSlotCount().
void ManufactureSchematicImplementation::increaseComplexity ()
Definition at line 866 of file ManufactureSchematic.cpp.
References complexity.
Referenced by addIngredientToSlot(), and server::zone::objects::manufactureschematic::ManufactureSchematic::increaseComplexity().
void ManufactureSchematicImplementation::initializeIngredientSlots () private
Definition at line 302 of file ManufactureSchematicImplementation.cpp.
References _this, server::zone::objects::scene::variables::DeltaVector< E >::add(), assembled, completed, complexity, craftingValues, draftSchematic, server::zone::objects::scene::SceneObjectImplementation::error(), IngredientSlot::IDENTICALSLOT, ingredientCounter, ingredientNames, ingredientSlots, ingredientTypes, initialized, manufactureLimit, IngredientSlot::MIXEDSLOT, IngredientSlot::OPTIONALIDENTICALSLOT, IngredientSlot::OPTIONALMIXEDSLOT, server::zone::objects::scene::variables::DeltaVector< E >::removeAll(), IngredientSlot::RESOURCESLOT, slotClean, slotIndexes, slotOIDs, slotQualities, and slotQuantities.
Referenced by synchronizedUIListen().
void ManufactureSchematicImplementation::initializeTransientMembers ()
Definition at line 851 of file ManufactureSchematic.cpp.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::initializeTransientMembers(), and readObject().
bool ManufactureSchematicImplementation::isAssembled ()
Definition at line 882 of file ManufactureSchematic.cpp.
References assembled.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::isAssembled().
bool ManufactureSchematicImplementation::isCompleted ()
Definition at line 892 of file ManufactureSchematic.cpp.
References completed.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::isCompleted().
bool ManufactureSchematicImplementation::isManufactureSchematic () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 856 of file ManufactureSchematic.cpp.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::isManufactureSchematic().
bool ManufactureSchematicImplementation::isReadyForAssembly ()
Definition at line 535 of file ManufactureSchematicImplementation.cpp.
References ingredientSlots, and initialized.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::isReadyForAssembly().
void ManufactureSchematicImplementation::lock (bool doLock = true) protected
Definition at line 619 of file ManufactureSchematic.cpp.
References _this.
void ManufactureSchematicImplementation::lock (ManagedObject * obj) protected
Definition at line 623 of file ManufactureSchematic.cpp.
References _this.
void ManufactureSchematicImplementation::manufactureItem (FactoryObject * factory)
Definition at line 969 of file ManufactureSchematic.cpp.
References factoryBlueprint, getManufactureLimit(), and setManufactureLimit().
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::manufactureItem().
ManufactureSchematicImplementation::operator const ManufactureSchematic * ()
Definition at line 615 of file ManufactureSchematic.cpp.
void ManufactureSchematicImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::intangible::IntangibleObjectImplementation.
Definition at line 654 of file ManufactureSchematic.cpp.
References initializeTransientMembers(), and readObjectMember().
bool ManufactureSchematicImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 673 of file ManufactureSchematic.cpp.
References complexity, crafter, customizationDefaultValues, customizationOptions, dataSize, draftSchematic, factoryBlueprint, manufactureLimit, and prototype.
Referenced by readObject().
int ManufactureSchematicImplementation::removeIngredientFromSlot (CreatureObject * player, TangibleObject * tano, int slot)
Send delta 7
Definition at line 445 of file ManufactureSchematicImplementation.cpp.
References _this, IngredientSlot::BADTARGETCONTAINER, DeltaMessage::close(), decreaseComplexity(), getComplexity(), ingredientSlots, IngredientSlot::INVALID, IngredientSlot::OK, sendDelta7(), server::zone::objects::creature::CreatureObject::sendMessage(), ManufactureSchematicObjectDeltaMessage3::updateComplexity(), and updateIngredientCounter().
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::removeIngredientFromSlot().
void ManufactureSchematicImplementation::rlock (bool doLock = true) protected
Definition at line 627 of file ManufactureSchematic.cpp.
References _this.
void ManufactureSchematicImplementation::runlock (bool doLock = true) protected
Definition at line 643 of file ManufactureSchematic.cpp.
References _this.
void ManufactureSchematicImplementation::sendBaselinesTo (SceneObject * player) virtual
Sends the baseline messages of this object to the specified player\
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the baseline messages }
Parameters
player SceneObject that will receive the baselines
Reimplemented from server::zone::objects::intangible::IntangibleObjectImplementation.
Definition at line 121 of file ManufactureSchematicImplementation.cpp.
References _this, complexity, draftSchematic, server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObjectImplementation::getObjectID(), server::zone::objects::scene::SceneObject::isPlayerCreature(), prototype, and server::zone::objects::scene::SceneObject::sendMessage().
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::sendBaselinesTo(), and sendTo().
void ManufactureSchematicImplementation::sendDelta7 (IngredientSlot * ingredientSlot, int slot, CreatureObject * player) private
Update slot type
Update list of OID's
Update list of quantities
Update pointless clean slot
The Odd update
Definition at line 474 of file ManufactureSchematicImplementation.cpp.
References _this, DeltaMessage::close(), IngredientSlot::getClientSlotType(), IngredientSlot::getOIDVector(), IngredientSlot::getQuantityVector(), ingredientCounter, ingredientTypes, IngredientSlot::isEmpty(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::scene::variables::DeltaVector< E >::set(), slotClean, slotOIDs, slotQuantities, and DeltaMessage::startUpdate().
Referenced by addIngredientToSlot(), and removeIngredientFromSlot().
void ManufactureSchematicImplementation::sendMsco7 (SceneObject * player) private
Sends the baseline7 message of this object to the specified player\
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the baseline messages }
Parameters
player SceneObject that will receive the baselines
Slot names
Slot types
Slot OID's
Slot Quantities
Slot Quantities
Slot Clean
Slot Index
Ingredient Counter
Experimenting names
Experimenting values
Useless values - always 0 Experiment offset
always 1 Max experimentation value
Pallete List
Pallete Start Index
Pallete End index
Pallete List
Customization Counter
Risk Factor
Definition at line 181 of file ManufactureSchematicImplementation.cpp.
References _this, craftingValues, getIngredientCounter(), ingredientNames, ingredientTypes, server::zone::objects::scene::variables::DeltaVector< E >::insertToMessage(), server::zone::objects::scene::SceneObject::sendMessage(), BaseLineMessage::setSize(), slotClean, slotIndexes, slotOIDs, slotQualities, and slotQuantities.
Referenced by addIngredientToSlot(), and synchronizedUIListen().
void ManufactureSchematicImplementation::sendTo (SceneObject * player, bool doClose) virtual
Sends the necessary messages to player in order to create this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received this object }
Parameters
player SceneObject that will receive the messages
doClose if true a SceneObjectCloseMessage is sent to finish the object
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 93 of file ManufactureSchematicImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::getObjectID(), server::zone::objects::scene::SceneObjectImplementation::getParent(), server::zone::objects::scene::SceneObjectImplementation::isStaticObject(), server::zone::objects::scene::SceneObjectImplementation::link(), sendBaselinesTo(), server::zone::objects::scene::SceneObjectImplementation::sendContainerObjectsTo(), server::zone::objects::scene::SceneObject::sendMessage(), and server::zone::objects::scene::SceneObjectImplementation::sendSlottedObjectsTo().
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::sendTo().
void ManufactureSchematicImplementation::setAssembled ()
Definition at line 574 of file ManufactureSchematicImplementation.cpp.
References assembled, craftingValues, ingredientSlots, and initialized.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::setAssembled().
void ManufactureSchematicImplementation::setCompleted ()
Definition at line 887 of file ManufactureSchematic.cpp.
References completed.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::setCompleted().
void ManufactureSchematicImplementation::setCrafter (CreatureObject * player)
Definition at line 907 of file ManufactureSchematic.cpp.
References crafter.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::setCrafter().
void ManufactureSchematicImplementation::setDraftSchematic (DraftSchematic * schematic)
Definition at line 155 of file ManufactureSchematicImplementation.cpp.
References draftSchematic.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::setDraftSchematic().
void ManufactureSchematicImplementation::setExperimentingCounter (int value)
Definition at line 922 of file ManufactureSchematic.cpp.
References experimentingCounter, and experimentingCounterPrevious.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::setExperimentingCounter().
void ManufactureSchematicImplementation::setManufactureLimit (int limit)
Definition at line 949 of file ManufactureSchematic.cpp.
References manufactureLimit.
Referenced by manufactureItem(), and server::zone::objects::manufactureschematic::ManufactureSchematic::setManufactureLimit().
void ManufactureSchematicImplementation::setPrototype (TangibleObject * tano)
We clean up all the unnecessary objects here This is where the schematic gets sent to the datapad, so wee need To initialize all the values
Definition at line 594 of file ManufactureSchematicImplementation.cpp.
References _this, crafter, createFactoryBlueprint(), dataSize, draftSchematic, ingredientSlots, and prototype.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::setPrototype().
void ManufactureSchematicImplementation::synchronizedUIListen (SceneObject * player, int value) virtual
Calls the appropriate UI Listener Function
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
player CreatureObject using the item
value value from packet
Send session packets for UI listen
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 159 of file ManufactureSchematicImplementation.cpp.
References _this, SessionFacadeType::CRAFTING, draftSchematic, server::zone::objects::scene::SceneObject::getActiveSession(), initialized, initializeIngredientSlots(), server::zone::objects::scene::SceneObject::isPlayerCreature(), possibleSyncIssue, and sendMsco7().
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::synchronizedUIListen().
void ManufactureSchematicImplementation::synchronizedUIStopListen (SceneObject * player, int value) virtual
Calls the appropriate UI Stop Listener Function
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
player CreatureObject using the item
value value from packet
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 298 of file ManufactureSchematicImplementation.cpp.
Referenced by server::zone::objects::manufactureschematic::ManufactureSchematic::synchronizedUIStopListen().
void ManufactureSchematicImplementation::unlock (bool doLock = true) protected
Definition at line 639 of file ManufactureSchematic.cpp.
References _this.
void ManufactureSchematicImplementation::updateIngredientCounter () private
Definition at line 939 of file ManufactureSchematic.cpp.
References ingredientCounter.
Referenced by addIngredientToSlot(), and removeIngredientFromSlot().
void ManufactureSchematicImplementation::wlock (bool doLock = true) protected
Definition at line 631 of file ManufactureSchematic.cpp.
References _this.
void ManufactureSchematicImplementation::wlock (ManagedObject * obj) protected
Definition at line 635 of file ManufactureSchematic.cpp.
References _this.
void ManufactureSchematicImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::intangible::IntangibleObjectImplementation.
Definition at line 719 of file ManufactureSchematic.cpp.
References writeObjectMembers().
int ManufactureSchematicImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 726 of file ManufactureSchematic.cpp.
References complexity, crafter, customizationDefaultValues, customizationOptions, dataSize, draftSchematic, factoryBlueprint, manufactureLimit, and prototype.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ManufactureSchematic friend
Definition at line 507 of file ManufactureSchematic.h.
Member Data Documentation
WeakReference<ManufactureSchematic*> server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::_this
Definition at line 473 of file ManufactureSchematic.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addIngredientToSlot(), cleanupIngredientSlots(), initializeIngredientSlots(), lock(), removeIngredientFromSlot(), rlock(), runlock(), sendBaselinesTo(), sendDelta7(), sendMsco7(), sendTo(), setPrototype(), synchronizedUIListen(), unlock(), and wlock().
bool server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::assembled protected
Definition at line 312 of file ManufactureSchematic.h.
Referenced by cleanupIngredientSlots(), initializeIngredientSlots(), isAssembled(), ManufactureSchematicImplementation(), and setAssembled().
bool server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::completed protected
Definition at line 314 of file ManufactureSchematic.h.
Referenced by initializeIngredientSlots(), isCompleted(), ManufactureSchematicImplementation(), and setCompleted().
float server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::complexity protected
Definition at line 290 of file ManufactureSchematic.h.
Referenced by decreaseComplexity(), getComplexity(), increaseComplexity(), initializeIngredientSlots(), ManufactureSchematicImplementation(), readObjectMember(), sendBaselinesTo(), and writeObjectMembers().
ManagedReference<CreatureObject* > server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::crafter protected
Definition at line 292 of file ManufactureSchematic.h.
Referenced by getCrafter(), ManufactureSchematicImplementation(), readObjectMember(), setCrafter(), setPrototype(), and writeObjectMembers().
Reference<CraftingValues* > server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::craftingValues protected
Definition at line 326 of file ManufactureSchematic.h.
Referenced by getCraftingValues(), initializeIngredientSlots(), ManufactureSchematicImplementation(), sendMsco7(), and setAssembled().
Vector<byte> server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::customizationDefaultValues protected
Definition at line 330 of file ManufactureSchematic.h.
Referenced by readObjectMember(), and writeObjectMembers().
Vector<byte> server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::customizationOptions protected
Definition at line 328 of file ManufactureSchematic.h.
Referenced by readObjectMember(), and writeObjectMembers().
float server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::dataSize protected
Definition at line 286 of file ManufactureSchematic.h.
Referenced by fillAttributeList(), ManufactureSchematicImplementation(), readObjectMember(), setPrototype(), and writeObjectMembers().
ManagedReference<DraftSchematic* > server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::draftSchematic protected
Definition at line 282 of file ManufactureSchematic.h.
Referenced by allowFactoryRun(), getDraftSchematic(), getLabratory(), initializeIngredientSlots(), ManufactureSchematicImplementation(), readObjectMember(), sendBaselinesTo(), setDraftSchematic(), setPrototype(), synchronizedUIListen(), and writeObjectMembers().
int server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::experimentingCounter protected
Definition at line 320 of file ManufactureSchematic.h.
Referenced by getExperimentingCounter(), ManufactureSchematicImplementation(), and setExperimentingCounter().
int server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::experimentingCounterPrevious protected
Definition at line 322 of file ManufactureSchematic.h.
Referenced by getExperimentingCounterPrevious(), ManufactureSchematicImplementation(), and setExperimentingCounter().
FactoryBlueprint server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::factoryBlueprint protected
Definition at line 294 of file ManufactureSchematic.h.
Referenced by canManufactureItem(), createFactoryBlueprint(), fillAttributeList(), getBlueprintEntry(), getBlueprintSize(), manufactureItem(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::ingredientCounter protected
Definition at line 318 of file ManufactureSchematic.h.
Referenced by getIngredientCounter(), initializeIngredientSlots(), ManufactureSchematicImplementation(), sendDelta7(), and updateIngredientCounter().
StringIdDeltaVector server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::ingredientNames protected
Definition at line 298 of file ManufactureSchematic.h.
Referenced by initializeIngredientSlots(), and sendMsco7().
Vector<Reference<IngredientSlot*> > server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::ingredientSlots protected
Definition at line 296 of file ManufactureSchematic.h.
Referenced by addIngredientToSlot(), cleanupIngredientSlots(), createFactoryBlueprint(), getSlot(), getSlotCount(), initializeIngredientSlots(), isReadyForAssembly(), removeIngredientFromSlot(), setAssembled(), and setPrototype().
DeltaVector<int> server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::ingredientTypes protected
Definition at line 300 of file ManufactureSchematic.h.
Referenced by initializeIngredientSlots(), sendDelta7(), and sendMsco7().
bool server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::initialized protected
Definition at line 316 of file ManufactureSchematic.h.
Referenced by initializeIngredientSlots(), isReadyForAssembly(), ManufactureSchematicImplementation(), setAssembled(), and synchronizedUIListen().
int server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::manufactureLimit protected
Definition at line 288 of file ManufactureSchematic.h.
Referenced by fillAttributeList(), getManufactureLimit(), initializeIngredientSlots(), ManufactureSchematicImplementation(), readObjectMember(), setManufactureLimit(), and writeObjectMembers().
bool server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::possibleSyncIssue protected
Definition at line 324 of file ManufactureSchematic.h.
Referenced by addIngredientToSlot(), ManufactureSchematicImplementation(), and synchronizedUIListen().
ManagedReference<TangibleObject* > server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::prototype protected
Definition at line 284 of file ManufactureSchematic.h.
Referenced by fillAttributeList(), getPrototype(), ManufactureSchematicImplementation(), readObjectMember(), sendBaselinesTo(), setPrototype(), and writeObjectMembers().
DeltaVector<int> server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::slotClean protected
Definition at line 308 of file ManufactureSchematic.h.
Referenced by initializeIngredientSlots(), sendDelta7(), and sendMsco7().
DeltaVector<int> server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::slotIndexes protected
Definition at line 310 of file ManufactureSchematic.h.
Referenced by initializeIngredientSlots(), and sendMsco7().
Uint64VectorDeltaVector server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::slotOIDs protected
Definition at line 302 of file ManufactureSchematic.h.
Referenced by initializeIngredientSlots(), sendDelta7(), and sendMsco7().
DeltaVector<float> server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::slotQualities protected
Definition at line 306 of file ManufactureSchematic.h.
Referenced by initializeIngredientSlots(), and sendMsco7().
IntVectorDeltaVector server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::slotQuantities protected
Definition at line 304 of file ManufactureSchematic.h.
Referenced by initializeIngredientSlots(), sendDelta7(), and sendMsco7().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/ManufactureSchematic.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/ManufactureSchematic.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/ManufactureSchematicImplementation.cpp