Core3: server::zone::objects::player::sessions::FindSessionImplementation Class Reference
server::zone::objects::player::sessions::FindSessionImplementation Class Reference
#include <FindSession.h>
Public Member Functions
FindSessionImplementation (CreatureObject *pl)
FindSessionImplementation (DummyConstructorParameter *param)
int initializeSession ()
int cancelSession ()
int clearSession ()
void initalizeFindMenu ()
void addWaypoint (float x, float y, const String &name)
void findPlanetaryObject (String &maplocationtype)
void clearWaypoint ()
operator const FindSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< FindSession * > _this
Protected Member Functions
virtual ~FindSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > player
ManagedReference< SuiListBox * > findSuiBox
Friends
class FindSession
Detailed Description
Definition at line 95 of file FindSession.h.
Constructor & Destructor Documentation
FindSessionImplementation::FindSessionImplementation (CreatureObject * pl)
Definition at line 273 of file FindSession.cpp.
References _initializeImplementation(), initializeSession(), and player.
FindSessionImplementation::FindSessionImplementation (DummyConstructorParameter * param)
Definition at line 135 of file FindSession.cpp.
References _initializeImplementation().
FindSessionImplementation::~FindSessionImplementation () protected virtual
Definition at line 140 of file FindSession.cpp.
Member Function Documentation
DistributedObjectStub * FindSessionImplementation::_getStub ()
Definition at line 160 of file FindSession.cpp.
References _this.
void FindSessionImplementation::_initializeImplementation () protected
Definition at line 147 of file FindSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by FindSessionImplementation().
void FindSessionImplementation::_serializationHelperMethod () protected
Definition at line 196 of file FindSession.cpp.
Referenced by _initializeImplementation().
void FindSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 155 of file FindSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::FindSession::FindSession().
void FindSessionImplementation::addWaypoint (float x, float y, const String & name)
Definition at line 64 of file FindSessionImplementation.cpp.
References server::zone::objects::player::PlayerObject::addWaypoint(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), player, server::zone::objects::scene::variables::StringId::setStringId(), and server::chat::StringIdChatParameter::setTO().
Referenced by server::zone::objects::player::sessions::FindSession::addWaypoint(), and findPlanetaryObject().
int FindSessionImplementation::cancelSession ()
Definition at line 290 of file FindSession.cpp.
References clearSession(), SessionFacadeType::FIND, and player.
Referenced by server::zone::objects::player::sessions::FindSession::cancelSession(), and findPlanetaryObject().
int FindSessionImplementation::clearSession ()
Definition at line 300 of file FindSession.cpp.
References player.
Referenced by cancelSession(), and server::zone::objects::player::sessions::FindSession::clearSession().
void FindSessionImplementation::clearWaypoint ()
Definition at line 93 of file FindSessionImplementation.cpp.
References WaypointList::getWaypointBySpecialType(), server::zone::objects::player::PlayerObject::getWaypointList(), player, and server::zone::objects::player::PlayerObject::removeWaypoint().
Referenced by server::zone::objects::player::sessions::FindSession::clearWaypoint().
void FindSessionImplementation::finalize () protected
Definition at line 144 of file FindSession.cpp.
void FindSessionImplementation::findPlanetaryObject (String & maplocationtype)
Definition at line 111 of file FindSessionImplementation.cpp.
References addWaypoint(), cancelSession(), server::zone::Zone::getNearestPlanetaryObject(), server::zone::managers::stringid::StringIdManager::getStringId(), server::zone::objects::scene::SceneObject::getZone(), and player.
Referenced by server::zone::objects::player::sessions::FindSession::findPlanetaryObject().
void FindSessionImplementation::initalizeFindMenu ()
Definition at line 23 of file FindSessionImplementation.cpp.
References _this, SessionFacadeType::FIND, SuiWindowType::FINDSESSION, and player.
Referenced by server::zone::objects::player::sessions::FindSession::initalizeFindMenu().
int FindSessionImplementation::initializeSession ()
Definition at line 285 of file FindSession.cpp.
Referenced by FindSessionImplementation(), and server::zone::objects::player::sessions::FindSession::initializeSession().
void FindSessionImplementation::lock (bool doLock = true) protected
Definition at line 168 of file FindSession.cpp.
References _this.
void FindSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 172 of file FindSession.cpp.
References _this.
FindSessionImplementation::operator const FindSession * ()
Definition at line 164 of file FindSession.cpp.
void FindSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 203 of file FindSession.cpp.
References readObjectMember().
bool FindSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 222 of file FindSession.cpp.
References findSuiBox, and player.
Referenced by readObject().
void FindSessionImplementation::rlock (bool doLock = true) protected
Definition at line 176 of file FindSession.cpp.
References _this.
void FindSessionImplementation::runlock (bool doLock = true) protected
Definition at line 192 of file FindSession.cpp.
References _this.
void FindSessionImplementation::unlock (bool doLock = true) protected
Definition at line 188 of file FindSession.cpp.
References _this.
void FindSessionImplementation::wlock (bool doLock = true) protected
Definition at line 180 of file FindSession.cpp.
References _this.
void FindSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 184 of file FindSession.cpp.
References _this.
void FindSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 240 of file FindSession.cpp.
References writeObjectMembers().
int FindSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 247 of file FindSession.cpp.
References findSuiBox, and player.
Referenced by writeObject().
Friends And Related Function Documentation
friend class FindSession friend
Definition at line 154 of file FindSession.h.
Member Data Documentation
WeakReference<FindSession*> server::zone::objects::player::sessions::FindSessionImplementation::_this
Definition at line 120 of file FindSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), initalizeFindMenu(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedReference<SuiListBox* > server::zone::objects::player::sessions::FindSessionImplementation::findSuiBox protected
Definition at line 99 of file FindSession.h.
Referenced by readObjectMember(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sessions::FindSessionImplementation::player protected
Definition at line 97 of file FindSession.h.
Referenced by addWaypoint(), cancelSession(), clearSession(), clearWaypoint(), findPlanetaryObject(), FindSessionImplementation(), initalizeFindMenu(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/FindSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/FindSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/FindSessionImplementation.cpp