Core3: GCWBaseContainerComponent Class Reference
GCWBaseContainerComponent Class Reference
#include <GCWBaseContainerComponent.h>
Public Member Functions
bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
bool checkContainerPermission (BuildingObject *building, CreatureObject *creature, uint16 permission, bool sendMessage)
bool checkPVPPermission (BuildingObject *building, CreatureObject *creature, uint16 permission, bool sendMessage)
bool checkPVEPermission (BuildingObject *building, CreatureObject *creature, uint16 permission, bool sendMessage)
Public Member Functions inherited from StructureContainerComponent
bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
Public Member Functions inherited from ContainerComponent
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
virtual int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Detailed Description
Definition at line 19 of file GCWBaseContainerComponent.h.
Member Function Documentation
bool GCWBaseContainerComponent::checkContainerPermission (SceneObject * sceneObject, CreatureObject * creature, uint16 permission) virtual
Reimplemented from ContainerComponent.
Definition at line 9 of file GCWBaseContainerComponent.cpp.
bool GCWBaseContainerComponent::checkContainerPermission (BuildingObject * building, CreatureObject * creature, uint16 permission, bool sendMessage)
Definition at line 20 of file GCWBaseContainerComponent.cpp.
References StructureContainerComponent::checkContainerPermission(), checkPVEPermission(), checkPVPPermission(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), and CreatureFlag::OVERT.
bool GCWBaseContainerComponent::checkPVEPermission (BuildingObject * building, CreatureObject * creature, uint16 permission, bool sendMessage)
Definition at line 99 of file GCWBaseContainerComponent.cpp.
References FactionStatus::CHANGINGSTATUS, FactionStatus::COVERT, server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::player::PlayerObject::getFactionStatus(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), DestructibleBuildingDataComponent::hasDefense(), FactionStatus::OVERT, CreatureFlag::OVERT, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by checkContainerPermission().
bool GCWBaseContainerComponent::checkPVPPermission (BuildingObject * building, CreatureObject * creature, uint16 permission, bool sendMessage)
Definition at line 38 of file GCWBaseContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::tangible::TangibleObject::getPvpStatusBitmask(), DestructibleBuildingDataComponent::hasDefense(), DestructibleBuildingDataComponent::isVulnerable(), CreatureFlag::OVERT, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by checkContainerPermission().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/building/components/GCWBaseContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/building/components/GCWBaseContainerComponent.cpp