Core3: server::zone::templates::SharedObjectTemplate Class Reference
server::zone::templates::SharedObjectTemplate Class Reference
#include <SharedObjectTemplate.h>
Public Member Functions
SharedObjectTemplate ()
virtual ~SharedObjectTemplate ()
void readObject (LuaObject *templateData)
void readObject (IffStream *iffStream)
void parseVariableData (const String &varName, Chunk *data)
void parseVariableData (const String &varName, LuaObject *templateData)
void loadDerv (IffStream *iffStream)
void parseFileData (IffStream *iffStream)
bool isDerivedFrom (const String &iffPath, bool includeSelf=true)
String getAppearanceFilename () const
float getClearFloraRadius () const
String getClientDataFile () const
int getCollisionActionBlockFlags () const
int getCollisionActionFlags () const
int getCollisionActionPassFlags () const
int getCollisionMaterialBlockFlags () const
int getCollisionMaterialFlags () const
int getCollisionMaterialPassFlags () const
int getContainerType () const
int getContainerVolumeLimit () const
String getDetailedDescription ()
int getGameObjectType () const
int getClientGameObjectType () const
float getLocationReservationRadius () const
String getLookAtText () const
float getNoBuildRadius () const
String getObjectName () const
bool getOnlyVisibleInTools () const
String getPortalLayoutFilename () const
PortalLayout * getPortalLayout ()
AppearanceTemplate * getAppearanceTemplate ()
Vector< String > * getArrangementDescriptors ()
void addDerivedFile (const String &name)
float getMinScale ()
float getMaxScale ()
bool isNoTrade ()
float getScaleThresholdBeforeExtentTest () const
bool getSendToClient () const
Vector< String > * getSlotDescriptors ()
bool getSnapToTerrain () const
int getSurfaceType () const
String getTintPallete () const
int getTotalCellNumber () const
uint32 getClientObjectCRC () const
String getClientTemplateFileName ()
uint32 getServerObjectCRC ()
String getFullTemplateString ()
String getDataObjectComponent ()
String getTemplateFileName ()
SceneObjectComponent * getContainerComponent ()
String getZoneComponent ()
SceneObjectComponent * getObjectMenuComponent ()
String getAttributeListComponent ()
PlanetMapCategory * getPlanetMapCategory () const
PlanetMapCategory * getPlanetMapSubCategory () const
bool isAutoRegistering ()
int getChildObjectsSize ()
ChildObject * getChildObject (int idx)
bool hasInheritPermissionsFromParent ()
HashTable< uint32, uint32 > * getGroupPermissions ()
bool hasArrangementDescriptor (String s)
void setAppearanceFilename (String appearanceFilename)
void setClearFloraRadius (float clearFloraRadius)
void setClientDataFile (String clientDataFile)
void setCollisionActionBlockFlags (int collisionActionBlockFlags)
void setCollisionActionFlags (int collisionActionFlags)
void setCollisionActionPassFlags (int collisionActionPassFlags)
void setCollisionMaterialBlockFlags (int collisionMaterialBlockFlags)
void setCollisionMaterialFlags (int collisionMaterialFlags)
void setCollisionMaterialPassFlags (int collisionMaterialPassFlags)
void setContainerType (int containerType)
void setContainerVolumeLimit (int containerVolumeLimit)
void setDetailedDescription (String detailedDescription)
void setGameObjectType (int gameObjectType)
void setLocationReservationRadius (float locationReservationRadius)
void setLookAtText (String lookAtText)
void setNoBuildRadius (float noBuildRadius)
void setObjectName (String objectName)
void setOnlyVisibleInTools (bool onlyVisibleInTools)
void setPortalLayoutFilename (String portalLayoutFilename)
void setScale (float scale)
void setScaleThresholdBeforeExtentTest (float scaleThresholdBeforeExtentTest)
void setSendToClient (bool sendToClient)
void setSnapToTerrain (bool snapToTerrain)
void setSurfaceType (int surfaceType)
void setTintPallete (String tintPallete)
void setTotalCellNumber (int totalCellNumber)
void setFullTemplateString (const String &str)
void setTemplateFileName (const String &str)
virtual bool isArmorObjectTemplate ()
virtual bool isSharedTangibleObjectTemplate ()
virtual bool isSharedBuildingObjectTemplate ()
virtual bool isSharedInstallationObjectTemplate ()
virtual bool isMissionTerminalTemplate ()
virtual bool isGamblingTerminalTemplate ()
virtual bool isFireworkObjectTemplate ()
virtual bool isCloningBuildingObjectTemplate ()
virtual bool isHospitalBuildingObjectTemplate ()
virtual bool isRecreationBuildingObjectTemplate ()
virtual bool isNonPlayerCreatureObjectTemplate ()
virtual bool isStimPackTemplate ()
virtual bool isStatePackTemplate ()
virtual bool isRangedStimPackTemplate ()
virtual bool isEnhancePackTemplate ()
virtual bool isCurePackTemplate ()
virtual bool isDotPackTemplate ()
virtual bool isWoundPackTemplate ()
virtual bool isSkillBuffTemplate ()
virtual bool isLairObjectTemplate ()
virtual bool isElevatorTerminalTemplate ()
virtual bool isInstrumentObjectTemplate ()
virtual bool isCampKitTemplate ()
virtual bool isCamoKitTemplate ()
virtual bool isCampStructureTemplate ()
virtual bool isDiceTemplate ()
virtual bool isVendorCreatureTemplate ()
virtual bool isCreatureHabitatTemplate ()
virtual bool isRepairToolTemplate ()
virtual bool isRobeObjectTemplate ()
virtual bool isLightsaberCrystalTemplate ()
virtual bool isShipChassisTemplate ()
virtual bool isShipDeedTemplate ()
virtual bool isRecycleToolTemplate ()
virtual bool isVehicleCustomKitTemplate ()
virtual bool isDnaSampleTemplate ()
virtual bool isPetDeedTemplate ()
Public Member Functions inherited from LuaTemplate
virtual ~LuaTemplate ()
Public Member Functions inherited from TemplateData
virtual ~TemplateData ()
Public Member Functions inherited from IffTemplate
virtual ~IffTemplate ()
Static Public Member Functions
static String getType (int type)
Static Public Attributes
static const int SHOT = 'SHOT'
static const int STOT = 'STOT'
static const int SBMK = 'SBMK'
static const int SBOT = 'SBOT'
static const int STAT = 'STAT'
static const int SIOT = 'SIOT'
static const int CCLT = 'CCLT'
static const int SCOU = 'SCOU'
static const int SDSC = 'SDSC'
static const int SFOT = 'SFOT'
static const int SGRP = 'SGRP'
static const int SITN = 'SITN'
static const int SGLD = 'SGLD'
static const int SJED = 'SJED'
static const int SMSC = 'SMSC'
static const int SMSO = 'SMSO'
static const int SMSD = 'SMSD'
static const int SMLE = 'SMLE'
static const int SPLY = 'SPLY'
static const int RCCT = 'RCCT'
static const int SSHP = 'SSHP'
static const int SUNI = 'SUNI'
static const int SWAY = 'SWAY'
static const int STOK = 'STOK'
static const int SWOT = 'SWOT'
static const int SCNC = 'SCNC'
static const int SCOT = 'SCOT'
static const int CHARACTERBUILDERTERMINAL = 0x4000001
static const int SURVEYTOOL = 0x4000002
static const int RESOURCESPAWN = 0x4000003
static const int RESOURCECONTAINER = 0x4000004
static const int ARMOROBJECT = 0x4000005
static const int DEED = 0x4000006
static const int CRAFTINGTOOL = 0x4000007
static const int CRAFTINGSTATION = 0x4000008
static const int MISSIONTERMINAL = 0x4000009
static const int CLONINGBUILDING = 0x400000A
static const int DRAFTSCHEMATIC = 0x400000B
static const int NPCCREATURE = 0x400000C
static const int LAIRTEMPLATE = 0x400000D
static const int FACTORY = 0x400000E
static const int STIMPACK = 0x400000F
static const int RANGEDSTIMPACK = 0x4000010
static const int ENHANCEPACK = 0x4000011
static const int CUREPACK = 0x4000012
static const int DOTPACK = 0x4000013
static const int WOUNDPACK = 0x4000014
static const int STATEPACK = 0x4000015
static const int CONSUMABLE = 0x4000016
static const int ELEVATORTERMINAL = 0x4000017
static const int GAMBLINGTERMINAL = 0x4000018
static const int LOOTKIT = 0x4000019
static const int INSTRUMENT = 0x400001A
static const int FIREWORK = 0x400001B
static const int VEHICLEDEED = 0x400001C
static const int CAMPKIT = 0x400001D
static const int PLAYERCREATURE = 0x400001E
static const int SLICINGTOOL = 0x400001F
static const int CONTAINER = 0x4000020
static const int VENDORCREATURE = 0x4000021
static const int LOOTSCHEMATIC = 0x4000022
static const int CAMPSTRUCTURE = 0x4000023
static const int HOSPITALBUILDING = 0x4000024
static const int RECREATIONBUILDING = 0x4000025
static const int TRAP = 0x4000026
static const int STRUCTUREDEED = 0x4000027
static const int CAMOKIT = 0x4000028
static const int POWERUP = 0x4000029
static const int DICE = 0x4000030
static const int LIVESAMPLE = 0x4000031
static const int CREATUREHABITAT = 0x4000032
static const int REPAIRTOOL = 0x4000033
static const int ROBEOBJECT = 0x4000034
static const int LIGHTSABERCRYSTAL = 0x4000035
static const int SHIPCHASSIS = 0x4000036
static const int SHIPDEED = 0x4000037
static const int RECYCLETOOL = 0x4000038
static const int DNASAMPLE = 0x4000039
static const int PETDEED = 0x4000040
static const int VEHICLECUSTOMKIT = 0x4000041
static const int SKILLBUFF = 0x4000042
Protected Attributes
StringIdParam objectName
StringIdParam detailedDescription
StringIdParam lookAtText
BoolParam snapToTerrain
IntegerParam containerType
IntegerParam containerVolumeLimit
StringParam tintPallete
Reference
< ArrangementDescriptor * > arrangementDescriptors
Reference< SlotDescriptor * > slotDescriptors
StringParam appearanceFilename
StringParam portalLayoutFilename
int totalCellNumber
StringParam clientDataFile
IntegerParam collisionMaterialFlags
IntegerParam collisionMaterialPassFlags
FloatParam scale
IntegerParam collisionMaterialBlockFlags
IntegerParam collisionActionFlags
IntegerParam collisionActionPassFlags
IntegerParam collisionActionBlockFlags
IntegerParam gameObjectType
int clientGameObjectType
BoolParam sendToClient
FloatParam scaleThresholdBeforeExtentTest
FloatParam clearFloraRadius
IntegerParam surfaceType
FloatParam noBuildRadius
BoolParam onlyVisibleInTools
FloatParam locationReservationRadius
String clientTemplateFileName
Reference< PlanetMapCategory * > planetMapCategory
Reference< PlanetMapCategory * > planetMapSubCategory
bool autoRegisterWithPlanetMap
String fullTemplateString
String templateFileName
int templateType
Vector< ChildObject > childObjects
PortalLayout * portalLayout
AppearanceTemplate * appearanceTemplate
bool loadedPortalLayout
bool loadedAppearanceTemplate
String zoneComponent
String attributeListComponent
SceneObjectComponent * containerComponent
SceneObjectComponent * objectMenuComponent
String dataObjectComponent
bool inheritPermissionsFromParent
HashTable< uint32, uint32 > groupPermissions
SortedVector< String > loadedDerivedFiles
bool noTrade
Detailed Description
Definition at line 36 of file SharedObjectTemplate.h.
Constructor & Destructor Documentation
SharedObjectTemplate::SharedObjectTemplate ()
Definition at line 18 of file SharedObjectTemplate.cpp.
References appearanceTemplate, autoRegisterWithPlanetMap, clearFloraRadius, clientGameObjectType, collisionActionBlockFlags, collisionActionFlags, collisionActionPassFlags, collisionMaterialBlockFlags, collisionMaterialFlags, collisionMaterialPassFlags, containerComponent, containerType, containerVolumeLimit, gameObjectType, inheritPermissionsFromParent, loadedAppearanceTemplate, loadedPortalLayout, locationReservationRadius, noBuildRadius, noTrade, objectMenuComponent, onlyVisibleInTools, portalLayout, scaleThresholdBeforeExtentTest, sendToClient, snapToTerrain, surfaceType, templateType, and totalCellNumber.
virtual server::zone::templates::SharedObjectTemplate::~SharedObjectTemplate () inline virtual
Definition at line 188 of file SharedObjectTemplate.h.
Member Function Documentation
void server::zone::templates::SharedObjectTemplate::addDerivedFile (const String & name) inline
Definition at line 299 of file SharedObjectTemplate.h.
References loadedDerivedFiles.
Referenced by TemplateManager::addTemplate().
String server::zone::templates::SharedObjectTemplate::getAppearanceFilename () const inline
Definition at line 205 of file SharedObjectTemplate.h.
References appearanceFilename.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addHair(), server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), ImageDesignManager::createHairObject(), GogglesObjectMenuComponent::handleObjectMenuSelect(), ArmorObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::initialAssembly(), server::zone::objects::creature::VehicleObjectImplementation::notifyInsertToZone(), ImageDesignManager::updateColorVariable(), and ImageDesignManager::updateCustomization().
AppearanceTemplate * SharedObjectTemplate::getAppearanceTemplate ()
Definition at line 627 of file SharedObjectTemplate.cpp.
References appearanceFilename, appearanceTemplate, TemplateBase< V >::get(), and loadedAppearanceTemplate.
Referenced by CollisionManager::getAABBTree(), server::zone::objects::structure::StructureObjectImplementation::loadTemplateData(), and server::zone::objects::scene::SceneObjectImplementation::loadTemplateData().
Vector<String>* server::zone::templates::SharedObjectTemplate::getArrangementDescriptors () inline
Definition at line 288 of file SharedObjectTemplate.h.
References arrangementDescriptors.
String server::zone::templates::SharedObjectTemplate::getAttributeListComponent () inline
Definition at line 382 of file SharedObjectTemplate.h.
References attributeListComponent.
ChildObject* server::zone::templates::SharedObjectTemplate::getChildObject (int idx) inline
Definition at line 402 of file SharedObjectTemplate.h.
References childObjects.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects().
int server::zone::templates::SharedObjectTemplate::getChildObjectsSize () inline
Definition at line 398 of file SharedObjectTemplate.h.
References childObjects.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects().
float server::zone::templates::SharedObjectTemplate::getClearFloraRadius () const inline
Definition at line 209 of file SharedObjectTemplate.h.
References clearFloraRadius.
Referenced by StructureManager::placeStructure().
String server::zone::templates::SharedObjectTemplate::getClientDataFile () const inline
Definition at line 213 of file SharedObjectTemplate.h.
References clientDataFile.
int server::zone::templates::SharedObjectTemplate::getClientGameObjectType () const inline
Definition at line 257 of file SharedObjectTemplate.h.
References clientGameObjectType.
uint32 server::zone::templates::SharedObjectTemplate::getClientObjectCRC () const inline
Definition at line 346 of file SharedObjectTemplate.h.
References clientTemplateFileName.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), and server::zone::objects::scene::SceneObjectImplementation::loadTemplateData().
String server::zone::templates::SharedObjectTemplate::getClientTemplateFileName () inline
Definition at line 350 of file SharedObjectTemplate.h.
References clientTemplateFileName.
int server::zone::templates::SharedObjectTemplate::getCollisionActionBlockFlags () const inline
Definition at line 217 of file SharedObjectTemplate.h.
References collisionActionBlockFlags.
Referenced by CollisionManager::getAABBTree(), and server::zone::objects::scene::SceneObjectImplementation::loadTemplateData().
int server::zone::templates::SharedObjectTemplate::getCollisionActionFlags () const inline
Definition at line 221 of file SharedObjectTemplate.h.
References collisionActionFlags.
int server::zone::templates::SharedObjectTemplate::getCollisionActionPassFlags () const inline
Definition at line 225 of file SharedObjectTemplate.h.
References collisionActionPassFlags.
int server::zone::templates::SharedObjectTemplate::getCollisionMaterialBlockFlags () const inline
Definition at line 229 of file SharedObjectTemplate.h.
References collisionMaterialBlockFlags.
int server::zone::templates::SharedObjectTemplate::getCollisionMaterialFlags () const inline
Definition at line 233 of file SharedObjectTemplate.h.
References collisionMaterialFlags.
int server::zone::templates::SharedObjectTemplate::getCollisionMaterialPassFlags () const inline
Definition at line 237 of file SharedObjectTemplate.h.
References collisionMaterialPassFlags.
SceneObjectComponent* server::zone::templates::SharedObjectTemplate::getContainerComponent () inline
Definition at line 370 of file SharedObjectTemplate.h.
References containerComponent.
int server::zone::templates::SharedObjectTemplate::getContainerType () const inline
Definition at line 241 of file SharedObjectTemplate.h.
References containerType.
Referenced by server::zone::objects::scene::SceneObjectImplementation::loadTemplateData().
int server::zone::templates::SharedObjectTemplate::getContainerVolumeLimit () const inline
Definition at line 245 of file SharedObjectTemplate.h.
References containerVolumeLimit.
Referenced by server::zone::objects::scene::SceneObjectImplementation::loadTemplateData().
String server::zone::templates::SharedObjectTemplate::getDataObjectComponent () inline
Definition at line 362 of file SharedObjectTemplate.h.
References dataObjectComponent.
Referenced by server::zone::objects::scene::SceneObjectImplementation::loadTemplateData().
String server::zone::templates::SharedObjectTemplate::getDetailedDescription () inline
Definition at line 249 of file SharedObjectTemplate.h.
References detailedDescription, and StringIdParam::getFullString().
String server::zone::templates::SharedObjectTemplate::getFullTemplateString () inline
Definition at line 358 of file SharedObjectTemplate.h.
References fullTemplateString.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addHair(), server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), PlayerContainerComponent::canAddObject(), ImageDesignManager::createHairObject(), GetObjVarsCommand::doQueueCommand(), PathFinderManager::findPathFromWorldToCell(), TemplateManager::getTemplateFile(), parseVariableData(), server::zone::managers::gcw::GCWManagerImplementation::registerGCWBase(), server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner(), and server::zone::managers::gcw::GCWManagerImplementation::unregisterGCWBase().
int server::zone::templates::SharedObjectTemplate::getGameObjectType () const inline
Definition at line 253 of file SharedObjectTemplate.h.
References gameObjectType.
Referenced by server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::managers::object::ObjectManager::loadObjectFromTemplate(), server::zone::objects::scene::SceneObjectImplementation::loadTemplateData(), and StructureManager::placeStructure().
HashTable<uint32, uint32>* server::zone::templates::SharedObjectTemplate::getGroupPermissions () inline
Definition at line 410 of file SharedObjectTemplate.h.
References groupPermissions.
float server::zone::templates::SharedObjectTemplate::getLocationReservationRadius () const inline
Definition at line 261 of file SharedObjectTemplate.h.
References locationReservationRadius.
String server::zone::templates::SharedObjectTemplate::getLookAtText () const inline
Definition at line 265 of file SharedObjectTemplate.h.
References StringIdParam::getFullString(), and lookAtText.
float server::zone::templates::SharedObjectTemplate::getMaxScale () inline
Definition at line 307 of file SharedObjectTemplate.h.
References FloatParam::getMax(), and scale.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), ImageDesignManager::loadCustomizationData(), and server::zone::objects::creature::CreatureObjectImplementation::loadTemplateData().
float server::zone::templates::SharedObjectTemplate::getMinScale () inline
Definition at line 303 of file SharedObjectTemplate.h.
References FloatParam::getMin(), and scale.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), ImageDesignManager::loadCustomizationData(), and server::zone::objects::creature::CreatureObjectImplementation::loadTemplateData().
float server::zone::templates::SharedObjectTemplate::getNoBuildRadius () const inline
Definition at line 269 of file SharedObjectTemplate.h.
References noBuildRadius.
Referenced by CampKitMenuComponent::handleObjectMenuSelect(), server::zone::managers::planet::PlanetManagerImplementation::isInObjectsNoBuildZone(), and server::zone::objects::mission::bountyhunter::events::CallArakydTask::noInterferingObjects().
SceneObjectComponent* server::zone::templates::SharedObjectTemplate::getObjectMenuComponent () inline
Definition at line 378 of file SharedObjectTemplate.h.
References objectMenuComponent.
String server::zone::templates::SharedObjectTemplate::getObjectName () const inline
Definition at line 273 of file SharedObjectTemplate.h.
References StringIdParam::getFullString(), and objectName.
Referenced by server::zone::objects::scene::SceneObjectImplementation::loadTemplateData().
bool server::zone::templates::SharedObjectTemplate::getOnlyVisibleInTools () const inline
Definition at line 277 of file SharedObjectTemplate.h.
References onlyVisibleInTools.
PlanetMapCategory* server::zone::templates::SharedObjectTemplate::getPlanetMapCategory () const inline
Definition at line 386 of file SharedObjectTemplate.h.
References planetMapCategory.
Referenced by server::zone::objects::scene::SceneObjectImplementation::loadTemplateData().
PlanetMapCategory* server::zone::templates::SharedObjectTemplate::getPlanetMapSubCategory () const inline
Definition at line 390 of file SharedObjectTemplate.h.
References planetMapSubCategory.
Referenced by server::zone::objects::scene::SceneObjectImplementation::loadTemplateData().
PortalLayout * SharedObjectTemplate::getPortalLayout ()
Definition at line 609 of file SharedObjectTemplate.cpp.
References TemplateBase< V >::get(), loadedPortalLayout, portalLayout, and portalLayoutFilename.
Referenced by CollisionManager::checkLineOfSightInBuilding(), CollisionManager::checkLineOfSightWorldToCell(), PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), PathFinderManager::findPathFromWorldToCell(), CollisionManager::getAABBTree(), CollisionManager::getCellFloorCollision(), FleeStateComponent::getFleeLocation(), PathFinderManager::getFloorMesh(), CollisionManager::getWorldFloorCollision(), server::zone::objects::building::BuildingObjectImplementation::loadTemplateData(), server::zone::objects::structure::StructureObjectImplementation::loadTemplateData(), and server::zone::objects::scene::SceneObjectImplementation::loadTemplateData().
String server::zone::templates::SharedObjectTemplate::getPortalLayoutFilename () const inline
Definition at line 281 of file SharedObjectTemplate.h.
References portalLayoutFilename.
float server::zone::templates::SharedObjectTemplate::getScaleThresholdBeforeExtentTest () const inline
Definition at line 315 of file SharedObjectTemplate.h.
References scaleThresholdBeforeExtentTest.
bool server::zone::templates::SharedObjectTemplate::getSendToClient () const inline
Definition at line 319 of file SharedObjectTemplate.h.
References sendToClient.
uint32 server::zone::templates::SharedObjectTemplate::getServerObjectCRC () inline
Definition at line 354 of file SharedObjectTemplate.h.
References fullTemplateString.
Referenced by ConcealCommand::doQueueCommand(), and DumpZoneInformationCommand::doQueueCommand().
Vector<String>* server::zone::templates::SharedObjectTemplate::getSlotDescriptors () inline
Definition at line 323 of file SharedObjectTemplate.h.
References slotDescriptors.
bool server::zone::templates::SharedObjectTemplate::getSnapToTerrain () const inline
Definition at line 330 of file SharedObjectTemplate.h.
References snapToTerrain.
Referenced by StructureManager::placeStructure().
int server::zone::templates::SharedObjectTemplate::getSurfaceType () const inline
Definition at line 334 of file SharedObjectTemplate.h.
References surfaceType.
String server::zone::templates::SharedObjectTemplate::getTemplateFileName () inline
Definition at line 366 of file SharedObjectTemplate.h.
References templateFileName.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), BountyHunterDroidMenuComponent::fillObjectMenuResponse(), CampKitMenuComponent::handleObjectMenuSelect(), BountyHunterDroidMenuComponent::handleObjectMenuSelect(), BountyHunterDroidMenuComponent::isProbeDroid(), and BountyHunterDroidMenuComponent::isSeekerDroid().
String server::zone::templates::SharedObjectTemplate::getTintPallete () const inline
Definition at line 338 of file SharedObjectTemplate.h.
References tintPallete.
int server::zone::templates::SharedObjectTemplate::getTotalCellNumber () const inline
Definition at line 342 of file SharedObjectTemplate.h.
References totalCellNumber.
Referenced by server::zone::objects::building::BuildingObjectImplementation::loadTemplateData().
String SharedObjectTemplate::getType (int type) static
Definition at line 422 of file SharedObjectTemplate.cpp.
Referenced by readObject().
String server::zone::templates::SharedObjectTemplate::getZoneComponent () inline
Definition at line 374 of file SharedObjectTemplate.h.
References zoneComponent.
bool server::zone::templates::SharedObjectTemplate::hasArrangementDescriptor (String s) inline
Definition at line 414 of file SharedObjectTemplate.h.
References arrangementDescriptors.
bool server::zone::templates::SharedObjectTemplate::hasInheritPermissionsFromParent () inline
Definition at line 406 of file SharedObjectTemplate.h.
References inheritPermissionsFromParent.
virtual bool server::zone::templates::SharedObjectTemplate::isArmorObjectTemplate () inline virtual
Reimplemented in ArmorObjectTemplate.
Definition at line 540 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::wearables::ArmorObjectImplementation::loadTemplateData().
bool server::zone::templates::SharedObjectTemplate::isAutoRegistering () inline
Definition at line 394 of file SharedObjectTemplate.h.
References autoRegisterWithPlanetMap.
virtual bool server::zone::templates::SharedObjectTemplate::isCamoKitTemplate () inline virtual
Reimplemented in CamoKitTemplate.
Definition at line 632 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isCampKitTemplate () inline virtual
Reimplemented in CampKitTemplate.
Definition at line 628 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isCampStructureTemplate () inline virtual
Reimplemented in CampStructureTemplate.
Definition at line 636 of file SharedObjectTemplate.h.
Referenced by StructureManager::placeStructure().
virtual bool server::zone::templates::SharedObjectTemplate::isCloningBuildingObjectTemplate () inline virtual
Reimplemented in CloningBuildingObjectTemplate.
Definition at line 568 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isCreatureHabitatTemplate () inline virtual
Reimplemented in CreatureHabitatTemplate.
Definition at line 648 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isCurePackTemplate () inline virtual
Reimplemented in CurePackTemplate.
Definition at line 600 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::pharmaceutical::CurePackImplementation::loadTemplateData().
bool SharedObjectTemplate::isDerivedFrom (const String & iffPath, bool includeSelf = true)
Definition at line 645 of file SharedObjectTemplate.cpp.
References fullTemplateString, and loadedDerivedFiles.
virtual bool server::zone::templates::SharedObjectTemplate::isDiceTemplate () inline virtual
Reimplemented in DiceTemplate.
Definition at line 640 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isDnaSampleTemplate () inline virtual
Reimplemented in DnaSampleTemplate.
Definition at line 678 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isDotPackTemplate () inline virtual
Reimplemented in DotPackTemplate.
Definition at line 604 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::pharmaceutical::DotPackImplementation::loadTemplateData().
virtual bool server::zone::templates::SharedObjectTemplate::isElevatorTerminalTemplate () inline virtual
Definition at line 620 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isEnhancePackTemplate () inline virtual
Reimplemented in EnhancePackTemplate.
Definition at line 596 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::loadTemplateData().
virtual bool server::zone::templates::SharedObjectTemplate::isFireworkObjectTemplate () inline virtual
Reimplemented in FireworkObjectTemplate.
Definition at line 564 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::firework::FireworkObjectImplementation::loadTemplateData().
virtual bool server::zone::templates::SharedObjectTemplate::isGamblingTerminalTemplate () inline virtual
Reimplemented in GamblingTerminalTemplate.
Definition at line 560 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::loadTemplateData().
virtual bool server::zone::templates::SharedObjectTemplate::isHospitalBuildingObjectTemplate () inline virtual
Reimplemented in HospitalBuildingObjectTemplate.
Definition at line 572 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isInstrumentObjectTemplate () inline virtual
Reimplemented in InstrumentObjectTemplate.
Definition at line 624 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::InstrumentImplementation::loadTemplateData().
virtual bool server::zone::templates::SharedObjectTemplate::isLairObjectTemplate () inline virtual
Definition at line 616 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isLightsaberCrystalTemplate () inline virtual
Reimplemented in LightsaberCrystalObjectTemplate.
Definition at line 660 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isMissionTerminalTemplate () inline virtual
Reimplemented in MissionTerminalTemplate.
Definition at line 556 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::loadTemplateData().
virtual bool server::zone::templates::SharedObjectTemplate::isNonPlayerCreatureObjectTemplate () inline virtual
Reimplemented in NonPlayerCreatureObjectTemplate.
Definition at line 580 of file SharedObjectTemplate.h.
bool server::zone::templates::SharedObjectTemplate::isNoTrade () inline
Definition at line 311 of file SharedObjectTemplate.h.
References noTrade.
virtual bool server::zone::templates::SharedObjectTemplate::isPetDeedTemplate () inline virtual
Definition at line 681 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isRangedStimPackTemplate () inline virtual
Reimplemented in RangedStimPackTemplate.
Definition at line 592 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::loadTemplateData().
virtual bool server::zone::templates::SharedObjectTemplate::isRecreationBuildingObjectTemplate () inline virtual
Reimplemented in RecreationBuildingObjectTemplate.
Definition at line 576 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isRecycleToolTemplate () inline virtual
Reimplemented in RecycleToolTemplate.
Definition at line 672 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isRepairToolTemplate () inline virtual
Reimplemented in RepairToolTemplate.
Definition at line 652 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isRobeObjectTemplate () inline virtual
Reimplemented in RobeObjectTemplate.
Definition at line 656 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::wearables::RobeObjectImplementation::loadTemplateData().
virtual bool server::zone::templates::SharedObjectTemplate::isSharedBuildingObjectTemplate () inline virtual
Reimplemented in SharedBuildingObjectTemplate.
Definition at line 548 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isSharedInstallationObjectTemplate () inline virtual
Reimplemented in SharedInstallationObjectTemplate.
Definition at line 552 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isSharedTangibleObjectTemplate () inline virtual
Reimplemented in SharedTangibleObjectTemplate.
Definition at line 544 of file SharedObjectTemplate.h.
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission().
virtual bool server::zone::templates::SharedObjectTemplate::isShipChassisTemplate () inline virtual
Definition at line 664 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isShipDeedTemplate () inline virtual
Definition at line 668 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isSkillBuffTemplate () inline virtual
Reimplemented in SkillBuffTemplate.
Definition at line 612 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isStatePackTemplate () inline virtual
Reimplemented in StatePackTemplate.
Definition at line 588 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::pharmaceutical::StatePackImplementation::loadTemplateData().
virtual bool server::zone::templates::SharedObjectTemplate::isStimPackTemplate () inline virtual
Reimplemented in StimPackTemplate.
Definition at line 584 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::pharmaceutical::StimPackImplementation::loadTemplateData().
virtual bool server::zone::templates::SharedObjectTemplate::isVehicleCustomKitTemplate () inline virtual
Reimplemented in VehicleCustomKitTemplate.
Definition at line 675 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isVendorCreatureTemplate () inline virtual
Reimplemented in VendorCreatureTemplate.
Definition at line 644 of file SharedObjectTemplate.h.
virtual bool server::zone::templates::SharedObjectTemplate::isWoundPackTemplate () inline virtual
Reimplemented in WoundPackTemplate.
Definition at line 608 of file SharedObjectTemplate.h.
Referenced by server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::loadTemplateData().
void SharedObjectTemplate::loadDerv (IffStream * iffStream)
Definition at line 369 of file SharedObjectTemplate.cpp.
References loadedDerivedFiles, and readObject().
Referenced by SharedConstructionContractObjectTemplate::readObject(), SharedDraftSchematicObjectTemplate::readObject(), SharedMissionDataObjectTemplate::readObject(), SharedTokenObjectTemplate::readObject(), SharedWaypointObjectTemplate::readObject(), SharedMissionListEntryObjectTemplate::readObject(), SharedMissionObjectTemplate::readObject(), SharedGuildObjectTemplate::readObject(), SharedJediManagerTemplate::readObject(), SharedManufactureSchematicObjectTemplate::readObject(), SharedGroupObjectTemplate::readObject(), SharedPlayerObjectTemplate::readObject(), SharedUniverseObjectTemplate::readObject(), SharedCellObjectTemplate::readObject(), SharedShipObjectTemplate::readObject(), SharedBattlefieldMarkerObjectTemplate::readObject(), SharedCountingObjectTemplate::readObject(), SharedFactoryObjectTemplate::readObject(), SharedIntangibleObjectTemplate::readObject(), SharedResourceContainerObjectTemplate::readObject(), SharedStaticObjectTemplate::readObject(), SharedBuildingObjectTemplate::readObject(), SharedCreatureObjectTemplate::readObject(), SharedInstallationObjectTemplate::readObject(), SharedTangibleObjectTemplate::readObject(), SharedWeaponObjectTemplate::readObject(), and readObject().
void SharedObjectTemplate::parseFileData (IffStream * iffStream)
Definition at line 345 of file SharedObjectTemplate.cpp.
References parseVariableData().
Referenced by readObject().
void SharedObjectTemplate::parseVariableData (const String & varName, Chunk * data)
Definition at line 276 of file SharedObjectTemplate.cpp.
References appearanceFilename, arrangementDescriptors, clearFloraRadius, clientDataFile, clientGameObjectType, collisionActionBlockFlags, collisionActionFlags, collisionActionPassFlags, collisionMaterialBlockFlags, collisionMaterialFlags, collisionMaterialPassFlags, containerType, containerVolumeLimit, detailedDescription, gameObjectType, TemplateBase< V >::get(), TemplateManager::getArrangementDescriptor(), TemplateManager::getSlotDescriptor(), locationReservationRadius, lookAtText, noBuildRadius, objectName, onlyVisibleInTools, IntegerParam::parse(), StringParam::parse(), BoolParam::parse(), FloatParam::parse(), StringIdParam::parse(), portalLayoutFilename, scale, scaleThresholdBeforeExtentTest, sendToClient, slotDescriptors, snapToTerrain, surfaceType, and tintPallete.
Referenced by parseFileData(), and readObject().
void SharedObjectTemplate::parseVariableData (const String & varName, LuaObject * templateData)
Definition at line 56 of file SharedObjectTemplate.cpp.
References appearanceFilename, appearanceTemplate, arrangementDescriptors, attributeListComponent, autoRegisterWithPlanetMap, childObjects, clearFloraRadius, clientDataFile, clientGameObjectType, collisionActionBlockFlags, collisionActionFlags, collisionActionPassFlags, collisionMaterialBlockFlags, collisionMaterialFlags, collisionMaterialPassFlags, containerComponent, containerType, containerVolumeLimit, dataObjectComponent, detailedDescription, gameObjectType, TemplateManager::getArrangementDescriptor(), getFullTemplateString(), TemplateManager::getPlanetMapCategoryByName(), TemplateManager::getSlotDescriptor(), groupPermissions, inheritPermissionsFromParent, locationReservationRadius, lookAtText, noBuildRadius, noTrade, objectMenuComponent, objectName, onlyVisibleInTools, ChildObject::parseFromLua(), planetMapCategory, planetMapSubCategory, portalLayout, portalLayoutFilename, scale, scaleThresholdBeforeExtentTest, sendToClient, FloatParam::setMax(), FloatParam::setMin(), slotDescriptors, snapToTerrain, surfaceType, templateType, tintPallete, totalCellNumber, and zoneComponent.
void SharedObjectTemplate::readObject (LuaObject * templateData) virtual
Implements LuaTemplate.
Reimplemented in DnaSampleTemplate, SharedWeaponObjectTemplate, SharedTangibleObjectTemplate, PowerupTemplate, SharedCreatureObjectTemplate, TrapTemplate, PlayerCreatureTemplate, SharedInstallationObjectTemplate, ConsumableTemplate, ArmorObjectTemplate, DotPackTemplate, SharedStructureObjectTemplate, SharedBuildingObjectTemplate, DiceTemplate, CampStructureTemplate, CharacterBuilderTerminalTemplate, LootkitObjectTemplate, CurePackTemplate, LootSchematicTemplate, RepairToolTemplate, EnhancePackTemplate, RangedStimPackTemplate, ElevatorTerminalTemplate, SurveyToolTemplate, SharedStaticObjectTemplate, WoundPackTemplate, SkillBuffTemplate, CraftingStationTemplate, CraftingToolTemplate, LiveSampleTemplate, StatePackTemplate, StimPackTemplate, FireworkObjectTemplate, HospitalBuildingObjectTemplate, NonPlayerCreatureObjectTemplate, RecreationBuildingObjectTemplate, SlicingToolTemplate, VehicleDeedTemplate, VendorCreatureTemplate, CamoKitTemplate, ContainerTemplate, DeedTemplate, GamblingTerminalTemplate, LightsaberCrystalObjectTemplate, StructureDeedTemplate, CloningBuildingObjectTemplate, CreatureHabitatTemplate, PetDeedTemplate, SharedBattlefieldMarkerObjectTemplate, SharedCountingObjectTemplate, SharedFactoryObjectTemplate, SharedResourceContainerObjectTemplate, SharedShipObjectTemplate, VehicleCustomKitTemplate, MissionTerminalTemplate, RobeObjectTemplate, RecycleToolTemplate, InstrumentObjectTemplate, and CampKitTemplate.
Definition at line 471 of file SharedObjectTemplate.cpp.
References clientTemplateFileName, and parseVariableData().
Referenced by TemplateManager::addTemplate(), and loadDerv().
void SharedObjectTemplate::readObject (IffStream * iffStream) virtual
Implements IffTemplate.
Reimplemented in SharedWeaponObjectTemplate, SharedTangibleObjectTemplate, SharedInstallationObjectTemplate, SharedCreatureObjectTemplate, SharedBuildingObjectTemplate, SharedStaticObjectTemplate, SharedBattlefieldMarkerObjectTemplate, SharedCountingObjectTemplate, SharedFactoryObjectTemplate, SharedResourceContainerObjectTemplate, SharedShipObjectTemplate, SharedUniverseObjectTemplate, SharedGroupObjectTemplate, SharedGuildObjectTemplate, and SharedJediManagerTemplate.
Definition at line 432 of file SharedObjectTemplate.cpp.
References getType(), loadDerv(), and parseFileData().
void server::zone::templates::SharedObjectTemplate::setAppearanceFilename (String appearanceFilename) inline
Definition at line 419 of file SharedObjectTemplate.h.
References appearanceFilename.
void server::zone::templates::SharedObjectTemplate::setClearFloraRadius (float clearFloraRadius) inline
Definition at line 423 of file SharedObjectTemplate.h.
References clearFloraRadius.
void server::zone::templates::SharedObjectTemplate::setClientDataFile (String clientDataFile) inline
Definition at line 427 of file SharedObjectTemplate.h.
References clientDataFile.
void server::zone::templates::SharedObjectTemplate::setCollisionActionBlockFlags (int collisionActionBlockFlags) inline
Definition at line 431 of file SharedObjectTemplate.h.
References collisionActionBlockFlags.
void server::zone::templates::SharedObjectTemplate::setCollisionActionFlags (int collisionActionFlags) inline
Definition at line 435 of file SharedObjectTemplate.h.
References collisionActionFlags.
void server::zone::templates::SharedObjectTemplate::setCollisionActionPassFlags (int collisionActionPassFlags) inline
Definition at line 439 of file SharedObjectTemplate.h.
References collisionActionPassFlags.
void server::zone::templates::SharedObjectTemplate::setCollisionMaterialBlockFlags (int collisionMaterialBlockFlags) inline
Definition at line 443 of file SharedObjectTemplate.h.
References collisionMaterialBlockFlags.
void server::zone::templates::SharedObjectTemplate::setCollisionMaterialFlags (int collisionMaterialFlags) inline
Definition at line 447 of file SharedObjectTemplate.h.
References collisionMaterialFlags.
void server::zone::templates::SharedObjectTemplate::setCollisionMaterialPassFlags (int collisionMaterialPassFlags) inline
Definition at line 451 of file SharedObjectTemplate.h.
References collisionMaterialPassFlags.
void server::zone::templates::SharedObjectTemplate::setContainerType (int containerType) inline
Definition at line 455 of file SharedObjectTemplate.h.
References containerType.
void server::zone::templates::SharedObjectTemplate::setContainerVolumeLimit (int containerVolumeLimit) inline
Definition at line 459 of file SharedObjectTemplate.h.
References containerVolumeLimit.
void server::zone::templates::SharedObjectTemplate::setDetailedDescription (String detailedDescription) inline
Definition at line 463 of file SharedObjectTemplate.h.
References detailedDescription.
void server::zone::templates::SharedObjectTemplate::setFullTemplateString (const String & str) inline
Definition at line 531 of file SharedObjectTemplate.h.
References fullTemplateString.
Referenced by TemplateManager::addTemplate().
void server::zone::templates::SharedObjectTemplate::setGameObjectType (int gameObjectType) inline
Definition at line 467 of file SharedObjectTemplate.h.
References gameObjectType.
void server::zone::templates::SharedObjectTemplate::setLocationReservationRadius (float locationReservationRadius) inline
Definition at line 471 of file SharedObjectTemplate.h.
References locationReservationRadius.
void server::zone::templates::SharedObjectTemplate::setLookAtText (String lookAtText) inline
Definition at line 475 of file SharedObjectTemplate.h.
References lookAtText.
void server::zone::templates::SharedObjectTemplate::setNoBuildRadius (float noBuildRadius) inline
Definition at line 479 of file SharedObjectTemplate.h.
References noBuildRadius.
void server::zone::templates::SharedObjectTemplate::setObjectName (String objectName) inline
Definition at line 483 of file SharedObjectTemplate.h.
References objectName.
void server::zone::templates::SharedObjectTemplate::setOnlyVisibleInTools (bool onlyVisibleInTools) inline
Definition at line 487 of file SharedObjectTemplate.h.
References onlyVisibleInTools.
void server::zone::templates::SharedObjectTemplate::setPortalLayoutFilename (String portalLayoutFilename) inline
Definition at line 491 of file SharedObjectTemplate.h.
References portalLayoutFilename.
void server::zone::templates::SharedObjectTemplate::setScale (float scale) inline
Definition at line 499 of file SharedObjectTemplate.h.
References scale.
void server::zone::templates::SharedObjectTemplate::setScaleThresholdBeforeExtentTest (float scaleThresholdBeforeExtentTest) inline
Definition at line 503 of file SharedObjectTemplate.h.
References scaleThresholdBeforeExtentTest.
void server::zone::templates::SharedObjectTemplate::setSendToClient (bool sendToClient) inline
Definition at line 507 of file SharedObjectTemplate.h.
References sendToClient.
void server::zone::templates::SharedObjectTemplate::setSnapToTerrain (bool snapToTerrain) inline
Definition at line 515 of file SharedObjectTemplate.h.
References snapToTerrain.
void server::zone::templates::SharedObjectTemplate::setSurfaceType (int surfaceType) inline
Definition at line 519 of file SharedObjectTemplate.h.
References surfaceType.
void server::zone::templates::SharedObjectTemplate::setTemplateFileName (const String & str) inline
Definition at line 535 of file SharedObjectTemplate.h.
References templateFileName.
Referenced by TemplateManager::addTemplate().
void server::zone::templates::SharedObjectTemplate::setTintPallete (String tintPallete) inline
Definition at line 523 of file SharedObjectTemplate.h.
References tintPallete.
void server::zone::templates::SharedObjectTemplate::setTotalCellNumber (int totalCellNumber) inline
Definition at line 527 of file SharedObjectTemplate.h.
References totalCellNumber.
Member Data Documentation
StringParam server::zone::templates::SharedObjectTemplate::appearanceFilename protected
Definition at line 51 of file SharedObjectTemplate.h.
Referenced by getAppearanceFilename(), getAppearanceTemplate(), parseVariableData(), and setAppearanceFilename().
AppearanceTemplate* server::zone::templates::SharedObjectTemplate::appearanceTemplate protected
Definition at line 87 of file SharedObjectTemplate.h.
Referenced by getAppearanceTemplate(), parseVariableData(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::ARMOROBJECT = 0x4000005 static
Definition at line 134 of file SharedObjectTemplate.h.
Reference<ArrangementDescriptor*> server::zone::templates::SharedObjectTemplate::arrangementDescriptors protected
Definition at line 49 of file SharedObjectTemplate.h.
Referenced by getArrangementDescriptors(), hasArrangementDescriptor(), and parseVariableData().
String server::zone::templates::SharedObjectTemplate::attributeListComponent protected
Definition at line 89 of file SharedObjectTemplate.h.
Referenced by getAttributeListComponent(), and parseVariableData().
bool server::zone::templates::SharedObjectTemplate::autoRegisterWithPlanetMap protected
Definition at line 77 of file SharedObjectTemplate.h.
Referenced by isAutoRegistering(), parseVariableData(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::CAMOKIT = 0x4000028 static
Definition at line 169 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::CAMPKIT = 0x400001D static
Definition at line 158 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::CAMPSTRUCTURE = 0x4000023 static
Definition at line 164 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::CCLT = 'CCLT' static
Definition at line 109 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::CHARACTERBUILDERTERMINAL = 0x4000001 static
Definition at line 130 of file SharedObjectTemplate.h.
Vector<ChildObject> server::zone::templates::SharedObjectTemplate::childObjects protected
Definition at line 84 of file SharedObjectTemplate.h.
Referenced by getChildObject(), getChildObjectsSize(), and parseVariableData().
FloatParam server::zone::templates::SharedObjectTemplate::clearFloraRadius protected
Definition at line 67 of file SharedObjectTemplate.h.
Referenced by getClearFloraRadius(), parseVariableData(), setClearFloraRadius(), and SharedObjectTemplate().
StringParam server::zone::templates::SharedObjectTemplate::clientDataFile protected
Definition at line 54 of file SharedObjectTemplate.h.
Referenced by getClientDataFile(), parseVariableData(), and setClientDataFile().
int server::zone::templates::SharedObjectTemplate::clientGameObjectType protected
Definition at line 64 of file SharedObjectTemplate.h.
Referenced by getClientGameObjectType(), parseVariableData(), and SharedObjectTemplate().
String server::zone::templates::SharedObjectTemplate::clientTemplateFileName protected
Definition at line 73 of file SharedObjectTemplate.h.
Referenced by getClientObjectCRC(), getClientTemplateFileName(), and readObject().
const int server::zone::templates::SharedObjectTemplate::CLONINGBUILDING = 0x400000A static
Definition at line 139 of file SharedObjectTemplate.h.
IntegerParam server::zone::templates::SharedObjectTemplate::collisionActionBlockFlags protected
Definition at line 62 of file SharedObjectTemplate.h.
Referenced by getCollisionActionBlockFlags(), parseVariableData(), setCollisionActionBlockFlags(), and SharedObjectTemplate().
IntegerParam server::zone::templates::SharedObjectTemplate::collisionActionFlags protected
Definition at line 60 of file SharedObjectTemplate.h.
Referenced by getCollisionActionFlags(), parseVariableData(), setCollisionActionFlags(), and SharedObjectTemplate().
IntegerParam server::zone::templates::SharedObjectTemplate::collisionActionPassFlags protected
Definition at line 61 of file SharedObjectTemplate.h.
Referenced by getCollisionActionPassFlags(), parseVariableData(), setCollisionActionPassFlags(), and SharedObjectTemplate().
IntegerParam server::zone::templates::SharedObjectTemplate::collisionMaterialBlockFlags protected
Definition at line 59 of file SharedObjectTemplate.h.
Referenced by getCollisionMaterialBlockFlags(), parseVariableData(), setCollisionMaterialBlockFlags(), and SharedObjectTemplate().
IntegerParam server::zone::templates::SharedObjectTemplate::collisionMaterialFlags protected
Definition at line 56 of file SharedObjectTemplate.h.
Referenced by getCollisionMaterialFlags(), parseVariableData(), setCollisionMaterialFlags(), and SharedObjectTemplate().
IntegerParam server::zone::templates::SharedObjectTemplate::collisionMaterialPassFlags protected
Definition at line 57 of file SharedObjectTemplate.h.
Referenced by getCollisionMaterialPassFlags(), parseVariableData(), setCollisionMaterialPassFlags(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::CONSUMABLE = 0x4000016 static
Definition at line 151 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::CONTAINER = 0x4000020 static
Definition at line 161 of file SharedObjectTemplate.h.
SceneObjectComponent* server::zone::templates::SharedObjectTemplate::containerComponent protected
Definition at line 90 of file SharedObjectTemplate.h.
Referenced by getContainerComponent(), parseVariableData(), and SharedObjectTemplate().
IntegerParam server::zone::templates::SharedObjectTemplate::containerType protected
Definition at line 43 of file SharedObjectTemplate.h.
Referenced by getContainerType(), parseVariableData(), setContainerType(), and SharedObjectTemplate().
IntegerParam server::zone::templates::SharedObjectTemplate::containerVolumeLimit protected
Definition at line 44 of file SharedObjectTemplate.h.
Referenced by getContainerVolumeLimit(), parseVariableData(), setContainerVolumeLimit(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::CRAFTINGSTATION = 0x4000008 static
Definition at line 137 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::CRAFTINGTOOL = 0x4000007 static
Definition at line 136 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::CREATUREHABITAT = 0x4000032 static
Definition at line 173 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::CUREPACK = 0x4000012 static
Definition at line 147 of file SharedObjectTemplate.h.
String server::zone::templates::SharedObjectTemplate::dataObjectComponent protected
Definition at line 93 of file SharedObjectTemplate.h.
Referenced by getDataObjectComponent(), and parseVariableData().
const int server::zone::templates::SharedObjectTemplate::DEED = 0x4000006 static
Definition at line 135 of file SharedObjectTemplate.h.
StringIdParam server::zone::templates::SharedObjectTemplate::detailedDescription protected
Definition at line 39 of file SharedObjectTemplate.h.
Referenced by getDetailedDescription(), parseVariableData(), and setDetailedDescription().
const int server::zone::templates::SharedObjectTemplate::DICE = 0x4000030 static
Definition at line 171 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::DNASAMPLE = 0x4000039 static
Definition at line 180 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::DOTPACK = 0x4000013 static
Definition at line 148 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::DRAFTSCHEMATIC = 0x400000B static
Definition at line 140 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::ELEVATORTERMINAL = 0x4000017 static
Definition at line 152 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::ENHANCEPACK = 0x4000011 static
Definition at line 146 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::FACTORY = 0x400000E static
Definition at line 143 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::FIREWORK = 0x400001B static
Definition at line 156 of file SharedObjectTemplate.h.
String server::zone::templates::SharedObjectTemplate::fullTemplateString protected
Definition at line 79 of file SharedObjectTemplate.h.
Referenced by getFullTemplateString(), getServerObjectCRC(), isDerivedFrom(), and setFullTemplateString().
const int server::zone::templates::SharedObjectTemplate::GAMBLINGTERMINAL = 0x4000018 static
Definition at line 153 of file SharedObjectTemplate.h.
IntegerParam server::zone::templates::SharedObjectTemplate::gameObjectType protected
Definition at line 63 of file SharedObjectTemplate.h.
Referenced by getGameObjectType(), parseVariableData(), setGameObjectType(), and SharedObjectTemplate().
HashTable<uint32, uint32> server::zone::templates::SharedObjectTemplate::groupPermissions protected
Definition at line 96 of file SharedObjectTemplate.h.
Referenced by getGroupPermissions(), and parseVariableData().
const int server::zone::templates::SharedObjectTemplate::HOSPITALBUILDING = 0x4000024 static
Definition at line 165 of file SharedObjectTemplate.h.
bool server::zone::templates::SharedObjectTemplate::inheritPermissionsFromParent protected
Definition at line 95 of file SharedObjectTemplate.h.
Referenced by hasInheritPermissionsFromParent(), parseVariableData(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::INSTRUMENT = 0x400001A static
Definition at line 155 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::LAIRTEMPLATE = 0x400000D static
Definition at line 142 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::LIGHTSABERCRYSTAL = 0x4000035 static
Definition at line 176 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::LIVESAMPLE = 0x4000031 static
Definition at line 172 of file SharedObjectTemplate.h.
bool server::zone::templates::SharedObjectTemplate::loadedAppearanceTemplate protected
Definition at line 88 of file SharedObjectTemplate.h.
Referenced by getAppearanceTemplate(), and SharedObjectTemplate().
SortedVector<String> server::zone::templates::SharedObjectTemplate::loadedDerivedFiles protected
Definition at line 98 of file SharedObjectTemplate.h.
Referenced by addDerivedFile(), isDerivedFrom(), and loadDerv().
bool server::zone::templates::SharedObjectTemplate::loadedPortalLayout protected
Definition at line 88 of file SharedObjectTemplate.h.
Referenced by getPortalLayout(), and SharedObjectTemplate().
FloatParam server::zone::templates::SharedObjectTemplate::locationReservationRadius protected
Definition at line 71 of file SharedObjectTemplate.h.
Referenced by getLocationReservationRadius(), parseVariableData(), setLocationReservationRadius(), and SharedObjectTemplate().
StringIdParam server::zone::templates::SharedObjectTemplate::lookAtText protected
Definition at line 40 of file SharedObjectTemplate.h.
Referenced by getLookAtText(), parseVariableData(), and setLookAtText().
const int server::zone::templates::SharedObjectTemplate::LOOTKIT = 0x4000019 static
Definition at line 154 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::LOOTSCHEMATIC = 0x4000022 static
Definition at line 163 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::MISSIONTERMINAL = 0x4000009 static
Definition at line 138 of file SharedObjectTemplate.h.
FloatParam server::zone::templates::SharedObjectTemplate::noBuildRadius protected
Definition at line 69 of file SharedObjectTemplate.h.
Referenced by getNoBuildRadius(), parseVariableData(), setNoBuildRadius(), and SharedObjectTemplate().
bool server::zone::templates::SharedObjectTemplate::noTrade protected
Definition at line 100 of file SharedObjectTemplate.h.
Referenced by isNoTrade(), parseVariableData(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::NPCCREATURE = 0x400000C static
Definition at line 141 of file SharedObjectTemplate.h.
SceneObjectComponent* server::zone::templates::SharedObjectTemplate::objectMenuComponent protected
Definition at line 91 of file SharedObjectTemplate.h.
Referenced by getObjectMenuComponent(), parseVariableData(), and SharedObjectTemplate().
StringIdParam server::zone::templates::SharedObjectTemplate::objectName protected
Definition at line 38 of file SharedObjectTemplate.h.
Referenced by getObjectName(), parseVariableData(), and setObjectName().
BoolParam server::zone::templates::SharedObjectTemplate::onlyVisibleInTools protected
Definition at line 70 of file SharedObjectTemplate.h.
Referenced by getOnlyVisibleInTools(), parseVariableData(), setOnlyVisibleInTools(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::PETDEED = 0x4000040 static
Definition at line 181 of file SharedObjectTemplate.h.
Reference<PlanetMapCategory*> server::zone::templates::SharedObjectTemplate::planetMapCategory protected
Definition at line 75 of file SharedObjectTemplate.h.
Referenced by getPlanetMapCategory(), and parseVariableData().
Reference<PlanetMapCategory*> server::zone::templates::SharedObjectTemplate::planetMapSubCategory protected
Definition at line 76 of file SharedObjectTemplate.h.
Referenced by getPlanetMapSubCategory(), and parseVariableData().
const int server::zone::templates::SharedObjectTemplate::PLAYERCREATURE = 0x400001E static
Definition at line 159 of file SharedObjectTemplate.h.
PortalLayout* server::zone::templates::SharedObjectTemplate::portalLayout protected
Definition at line 86 of file SharedObjectTemplate.h.
Referenced by getPortalLayout(), parseVariableData(), and SharedObjectTemplate().
StringParam server::zone::templates::SharedObjectTemplate::portalLayoutFilename protected
Definition at line 52 of file SharedObjectTemplate.h.
Referenced by getPortalLayout(), getPortalLayoutFilename(), parseVariableData(), and setPortalLayoutFilename().
const int server::zone::templates::SharedObjectTemplate::POWERUP = 0x4000029 static
Definition at line 170 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::RANGEDSTIMPACK = 0x4000010 static
Definition at line 145 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::RCCT = 'RCCT' static
Definition at line 122 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::RECREATIONBUILDING = 0x4000025 static
Definition at line 166 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::RECYCLETOOL = 0x4000038 static
Definition at line 179 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::REPAIRTOOL = 0x4000033 static
Definition at line 174 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::RESOURCECONTAINER = 0x4000004 static
Definition at line 133 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::RESOURCESPAWN = 0x4000003 static
Definition at line 132 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::ROBEOBJECT = 0x4000034 static
Definition at line 175 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SBMK = 'SBMK' static
Definition at line 105 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SBOT = 'SBOT' static
Definition at line 106 of file SharedObjectTemplate.h.
FloatParam server::zone::templates::SharedObjectTemplate::scale protected
Definition at line 58 of file SharedObjectTemplate.h.
Referenced by getMaxScale(), getMinScale(), parseVariableData(), and setScale().
FloatParam server::zone::templates::SharedObjectTemplate::scaleThresholdBeforeExtentTest protected
Definition at line 66 of file SharedObjectTemplate.h.
Referenced by getScaleThresholdBeforeExtentTest(), parseVariableData(), setScaleThresholdBeforeExtentTest(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::SCNC = 'SCNC' static
Definition at line 128 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SCOT = 'SCOT' static
Definition at line 129 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SCOU = 'SCOU' static
Definition at line 110 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SDSC = 'SDSC' static
Definition at line 111 of file SharedObjectTemplate.h.
BoolParam server::zone::templates::SharedObjectTemplate::sendToClient protected
Definition at line 65 of file SharedObjectTemplate.h.
Referenced by getSendToClient(), parseVariableData(), setSendToClient(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::SFOT = 'SFOT' static
Definition at line 112 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SGLD = 'SGLD' static
Definition at line 115 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SGRP = 'SGRP' static
Definition at line 113 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SHIPCHASSIS = 0x4000036 static
Definition at line 177 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SHIPDEED = 0x4000037 static
Definition at line 178 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SHOT = 'SHOT' static
Definition at line 103 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SIOT = 'SIOT' static
Definition at line 108 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SITN = 'SITN' static
Definition at line 114 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SJED = 'SJED' static
Definition at line 116 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SKILLBUFF = 0x4000042 static
Definition at line 183 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SLICINGTOOL = 0x400001F static
Definition at line 160 of file SharedObjectTemplate.h.
Reference<SlotDescriptor*> server::zone::templates::SharedObjectTemplate::slotDescriptors protected
Definition at line 50 of file SharedObjectTemplate.h.
Referenced by getSlotDescriptors(), and parseVariableData().
const int server::zone::templates::SharedObjectTemplate::SMLE = 'SMLE' static
Definition at line 120 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SMSC = 'SMSC' static
Definition at line 117 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SMSD = 'SMSD' static
Definition at line 119 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SMSO = 'SMSO' static
Definition at line 118 of file SharedObjectTemplate.h.
BoolParam server::zone::templates::SharedObjectTemplate::snapToTerrain protected
Definition at line 42 of file SharedObjectTemplate.h.
Referenced by getSnapToTerrain(), parseVariableData(), setSnapToTerrain(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::SPLY = 'SPLY' static
Definition at line 121 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SSHP = 'SSHP' static
Definition at line 123 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::STAT = 'STAT' static
Definition at line 107 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::STATEPACK = 0x4000015 static
Definition at line 150 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::STIMPACK = 0x400000F static
Definition at line 144 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::STOK = 'STOK' static
Definition at line 126 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::STOT = 'STOT' static
Definition at line 104 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::STRUCTUREDEED = 0x4000027 static
Definition at line 168 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SUNI = 'SUNI' static
Definition at line 124 of file SharedObjectTemplate.h.
IntegerParam server::zone::templates::SharedObjectTemplate::surfaceType protected
Definition at line 68 of file SharedObjectTemplate.h.
Referenced by getSurfaceType(), parseVariableData(), setSurfaceType(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::SURVEYTOOL = 0x4000002 static
Definition at line 131 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SWAY = 'SWAY' static
Definition at line 125 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::SWOT = 'SWOT' static
Definition at line 127 of file SharedObjectTemplate.h.
String server::zone::templates::SharedObjectTemplate::templateFileName protected
Definition at line 80 of file SharedObjectTemplate.h.
Referenced by getTemplateFileName(), and setTemplateFileName().
int server::zone::templates::SharedObjectTemplate::templateType protected
Definition at line 82 of file SharedObjectTemplate.h.
Referenced by parseVariableData(), and SharedObjectTemplate().
StringParam server::zone::templates::SharedObjectTemplate::tintPallete protected
Definition at line 46 of file SharedObjectTemplate.h.
Referenced by getTintPallete(), parseVariableData(), and setTintPallete().
int server::zone::templates::SharedObjectTemplate::totalCellNumber protected
Definition at line 53 of file SharedObjectTemplate.h.
Referenced by getTotalCellNumber(), parseVariableData(), setTotalCellNumber(), and SharedObjectTemplate().
const int server::zone::templates::SharedObjectTemplate::TRAP = 0x4000026 static
Definition at line 167 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::VEHICLECUSTOMKIT = 0x4000041 static
Definition at line 182 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::VEHICLEDEED = 0x400001C static
Definition at line 157 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::VENDORCREATURE = 0x4000021 static
Definition at line 162 of file SharedObjectTemplate.h.
const int server::zone::templates::SharedObjectTemplate::WOUNDPACK = 0x4000014 static
Definition at line 149 of file SharedObjectTemplate.h.
String server::zone::templates::SharedObjectTemplate::zoneComponent protected
Definition at line 89 of file SharedObjectTemplate.h.
Referenced by getZoneComponent(), and parseVariableData().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/SharedObjectTemplate.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/SharedObjectTemplate.cpp