Core3: server::zone::objects::creature::aigroup::AiGroupObserver Class Reference
server::zone::objects::creature::aigroup::AiGroupObserver Class Reference
#include <AiGroupObserver.h>
Public Member Functions
AiGroupObserver (AiGroup *group)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
AiGroupObserver (DummyConstructorParameter *param)
virtual ~AiGroupObserver ()
Friends
class AiGroupObserverHelper
Detailed Description
Definition at line 54 of file AiGroupObserver.h.
Constructor & Destructor Documentation
AiGroupObserver::AiGroupObserver (AiGroup * group)
Definition at line 17 of file AiGroupObserver.cpp.
References server::zone::objects::creature::aigroup::AiGroupObserverImplementation::_setStub().
AiGroupObserver::AiGroupObserver (DummyConstructorParameter * param) protected
Definition at line 24 of file AiGroupObserver.cpp.
AiGroupObserver::~AiGroupObserver () protected virtual
Definition at line 28 of file AiGroupObserver.cpp.
Member Function Documentation
DistributedObjectServant * AiGroupObserver::_getImplementation ()
Definition at line 50 of file AiGroupObserver.cpp.
Referenced by notifyObserverEvent().
DistributedObjectServant * AiGroupObserver::_getImplementationForRead ()
Definition at line 56 of file AiGroupObserver.cpp.
void AiGroupObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 60 of file AiGroupObserver.cpp.
int AiGroupObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 33 of file AiGroupObserver.cpp.
References _getImplementation(), server::zone::objects::creature::aigroup::AiGroupObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class AiGroupObserverHelper friend
Definition at line 70 of file AiGroupObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/aigroup/AiGroupObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/aigroup/AiGroupObserver.cpp