Core3: server::zone::objects::creature::buffs::PerformanceBuffImplementation Class Reference
server::zone::objects::creature::buffs::PerformanceBuffImplementation Class Reference
#include <PerformanceBuff.h>
Public Member Functions
PerformanceBuffImplementation (CreatureObject *creo, unsigned int buffCRC, float value, int duration, int typeOfBuff)
PerformanceBuffImplementation (DummyConstructorParameter *param)
void activate (bool applyModifiers)
float getBuffStrength ()
void deactivate (bool removeModifiers)
operator const PerformanceBuff * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
BuffImplementation (CreatureObject *creo, unsigned int buffcrc, float duration, int bufftype)
BuffImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void loadBuffDurationEvent (CreatureObject *creo)
void init ()
virtual void sendTo (CreatureObject *player)
virtual void sendDestroyTo (CreatureObject *player)
virtual void activate ()
virtual void deactivate ()
VectorMap< String, int > * getSkillModifiers ()
virtual void applyAttributeModifiers ()
virtual void applySkillModifiers ()
virtual void applyStates ()
virtual void removeAttributeModifiers ()
virtual void removeSkillModifiers ()
virtual void removeStates ()
virtual void clearBuffEvent ()
void setBuffEventNull ()
void scheduleBuffEvent ()
virtual void parseAttributeModifierString (const String &modifierstring)
virtual void parseSkillModifierString (const String &modifierstring)
virtual String getAttributeModifierString ()
virtual String getSkillModifierString ()
virtual float getTimeLeft ()
void setAttributeModifier (byte attribute, int value)
void setSkillModifier (const String &modname, int value)
void addState (unsigned long long option)
void setSpeedMultiplierMod (float multiplier)
void setAccelerationMultiplierMod (float multiplier)
void setFillAttributesOnBuff (bool val)
String getBuffName ()
int getBuffCRC ()
float getBuffDuration ()
int getBuffType ()
VectorMap< byte, int > * getAttributeModifiers ()
virtual int getAttributeModifierValue (byte attribute)
virtual int getSkillModifierValue (const String &modname)
bool isActive ()
bool isSpiceBuff ()
bool isAttributeBuff ()
void setStartMessage (StringIdChatParameter &start)
void setEndMessage (StringIdChatParameter &end)
void setStartFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
void setEndFlyText (const String &file, const String &aux, byte red, byte green, byte blue)
operator const Buff * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< PerformanceBuff * > _this
Public Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
WeakReference< Buff * > _this
Protected Member Functions
virtual ~PerformanceBuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::creature::buffs::BuffImplementation
virtual ~BuffImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
float strength
int type
Protected Attributes inherited from server::zone::objects::creature::buffs::BuffImplementation
ManagedWeakReference
< CreatureObject * > creature
Reference< BuffDurationEvent * > buffEvent
VectorMap< byte, int > attributeModifiers
VectorMap< String, int > skillModifiers
Vector< unsigned long long > states
String buffName
float buffDuration
unsigned int buffCRC
int buffType
bool fillAttributesOnBuff
StringIdChatParameter startMessage
StringIdChatParameter endMessage
String startFlyFile
String startFlyAux
byte startFlyRed
byte startFlyGreen
byte startFlyBlue
String endFlyFile
String endFlyAux
byte endFlyRed
byte endFlyGreen
byte endFlyBlue
Time nextExecutionTime
Friends
class PerformanceBuff
Detailed Description
Definition at line 121 of file PerformanceBuff.h.
Constructor & Destructor Documentation
PerformanceBuffImplementation::PerformanceBuffImplementation (CreatureObject * creo, unsigned int buffCRC, float value, int duration, int typeOfBuff)
Definition at line 232 of file PerformanceBuff.cpp.
References _initializeImplementation(), strength, and type.
PerformanceBuffImplementation::PerformanceBuffImplementation (DummyConstructorParameter * param)
Definition at line 94 of file PerformanceBuff.cpp.
References _initializeImplementation().
PerformanceBuffImplementation::~PerformanceBuffImplementation () protected virtual
Definition at line 99 of file PerformanceBuff.cpp.
Member Function Documentation
DistributedObjectStub * PerformanceBuffImplementation::_getStub ()
Definition at line 119 of file PerformanceBuff.cpp.
References _this.
void PerformanceBuffImplementation::_initializeImplementation () protected
Definition at line 106 of file PerformanceBuff.cpp.
References _serializationHelperMethod(), and _this.
Referenced by PerformanceBuffImplementation().
void PerformanceBuffImplementation::_serializationHelperMethod () protected
Definition at line 155 of file PerformanceBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void PerformanceBuffImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 114 of file PerformanceBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::_setStub(), and _this.
Referenced by server::zone::objects::creature::buffs::PerformanceBuff::PerformanceBuff().
void PerformanceBuffImplementation::activate (bool applyModifiers) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 14 of file PerformanceBuffImplementation.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::activate(), server::zone::objects::creature::buffs::BuffImplementation::creature, PerformanceBuffType::DANCE_MIND, CreatureAttribute::FOCUS, CreatureAttribute::MIND, PerformanceBuffType::MUSIC_FOCUS, PerformanceBuffType::MUSIC_WILLPOWER, server::zone::objects::creature::buffs::BuffImplementation::setAttributeModifier(), strength, type, and CreatureAttribute::WILLPOWER.
Referenced by server::zone::objects::creature::buffs::PerformanceBuff::activate().
void PerformanceBuffImplementation::deactivate (bool removeModifiers) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 38 of file PerformanceBuffImplementation.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::deactivate().
Referenced by server::zone::objects::creature::buffs::PerformanceBuff::deactivate().
void PerformanceBuffImplementation::finalize () protected
Definition at line 103 of file PerformanceBuff.cpp.
float PerformanceBuffImplementation::getBuffStrength ()
Definition at line 240 of file PerformanceBuff.cpp.
References strength.
Referenced by server::zone::objects::creature::buffs::PerformanceBuff::getBuffStrength().
void PerformanceBuffImplementation::lock (bool doLock = true) protected
Definition at line 127 of file PerformanceBuff.cpp.
References _this.
void PerformanceBuffImplementation::lock (ManagedObject * obj) protected
Definition at line 131 of file PerformanceBuff.cpp.
References _this.
PerformanceBuffImplementation::operator const PerformanceBuff * ()
Definition at line 123 of file PerformanceBuff.cpp.
void PerformanceBuffImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 162 of file PerformanceBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::initializeTransientMembers(), and readObjectMember().
bool PerformanceBuffImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 181 of file PerformanceBuff.cpp.
References server::zone::objects::creature::buffs::BuffImplementation::readObjectMember(), strength, and type.
Referenced by readObject().
void PerformanceBuffImplementation::rlock (bool doLock = true) protected
Definition at line 135 of file PerformanceBuff.cpp.
References _this.
void PerformanceBuffImplementation::runlock (bool doLock = true) protected
Definition at line 151 of file PerformanceBuff.cpp.
References _this.
void PerformanceBuffImplementation::unlock (bool doLock = true) protected
Definition at line 147 of file PerformanceBuff.cpp.
References _this.
void PerformanceBuffImplementation::wlock (bool doLock = true) protected
Definition at line 139 of file PerformanceBuff.cpp.
References _this.
void PerformanceBuffImplementation::wlock (ManagedObject * obj) protected
Definition at line 143 of file PerformanceBuff.cpp.
References _this.
void PerformanceBuffImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::creature::buffs::BuffImplementation.
Definition at line 199 of file PerformanceBuff.cpp.
References writeObjectMembers().
int PerformanceBuffImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 206 of file PerformanceBuff.cpp.
References strength, type, and server::zone::objects::creature::buffs::BuffImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class PerformanceBuff friend
Definition at line 172 of file PerformanceBuff.h.
Member Data Documentation
WeakReference<PerformanceBuff*> server::zone::objects::creature::buffs::PerformanceBuffImplementation::_this
Definition at line 138 of file PerformanceBuff.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
float server::zone::objects::creature::buffs::PerformanceBuffImplementation::strength protected
Definition at line 123 of file PerformanceBuff.h.
Referenced by activate(), getBuffStrength(), PerformanceBuffImplementation(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::creature::buffs::PerformanceBuffImplementation::type protected
Definition at line 125 of file PerformanceBuff.h.
Referenced by activate(), PerformanceBuffImplementation(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/PerformanceBuff.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/PerformanceBuff.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/buffs/PerformanceBuffImplementation.cpp