Core3: server::chat::ChatMessageImplementation Class Reference
server::chat::ChatMessageImplementation Class Reference
#include <ChatMessage.h>
Public Member Functions
ChatMessageImplementation ()
ChatMessageImplementation (DummyConstructorParameter *param)
void setString (const String &msg)
String toString ()
operator const ChatMessage * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< ChatMessage * > _this
Protected Member Functions
virtual ~ChatMessageImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
String message
Friends
class ChatMessage
Detailed Description
Definition at line 76 of file ChatMessage.h.
Constructor & Destructor Documentation
ChatMessageImplementation::ChatMessageImplementation ()
Definition at line 204 of file ChatMessage.cpp.
References _initializeImplementation(), and message.
ChatMessageImplementation::ChatMessageImplementation (DummyConstructorParameter * param)
Definition at line 78 of file ChatMessage.cpp.
References _initializeImplementation().
ChatMessageImplementation::~ChatMessageImplementation () protected virtual
Definition at line 83 of file ChatMessage.cpp.
Member Function Documentation
DistributedObjectStub * ChatMessageImplementation::_getStub ()
Definition at line 103 of file ChatMessage.cpp.
References _this.
void ChatMessageImplementation::_initializeImplementation () protected
Definition at line 90 of file ChatMessage.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ChatMessageImplementation().
void ChatMessageImplementation::_serializationHelperMethod () protected
Definition at line 139 of file ChatMessage.cpp.
Referenced by _initializeImplementation().
void ChatMessageImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 98 of file ChatMessage.cpp.
References _this.
Referenced by server::chat::ChatMessage::ChatMessage().
void ChatMessageImplementation::finalize () protected
Definition at line 87 of file ChatMessage.cpp.
void ChatMessageImplementation::lock (bool doLock = true) protected
Definition at line 111 of file ChatMessage.cpp.
References _this.
void ChatMessageImplementation::lock (ManagedObject * obj) protected
Definition at line 115 of file ChatMessage.cpp.
References _this.
ChatMessageImplementation::operator const ChatMessage * ()
Definition at line 107 of file ChatMessage.cpp.
void ChatMessageImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 146 of file ChatMessage.cpp.
References readObjectMember().
bool ChatMessageImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 165 of file ChatMessage.cpp.
References message.
Referenced by readObject().
void ChatMessageImplementation::rlock (bool doLock = true) protected
Definition at line 119 of file ChatMessage.cpp.
References _this.
void ChatMessageImplementation::runlock (bool doLock = true) protected
Definition at line 135 of file ChatMessage.cpp.
References _this.
void ChatMessageImplementation::setString (const String & msg)
Definition at line 210 of file ChatMessage.cpp.
References message.
Referenced by server::chat::ChatMessage::setString().
String ChatMessageImplementation::toString ()
Definition at line 215 of file ChatMessage.cpp.
References message.
Referenced by server::chat::ChatMessage::toString().
void ChatMessageImplementation::unlock (bool doLock = true) protected
Definition at line 131 of file ChatMessage.cpp.
References _this.
void ChatMessageImplementation::wlock (bool doLock = true) protected
Definition at line 123 of file ChatMessage.cpp.
References _this.
void ChatMessageImplementation::wlock (ManagedObject * obj) protected
Definition at line 127 of file ChatMessage.cpp.
References _this.
void ChatMessageImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 179 of file ChatMessage.cpp.
References writeObjectMembers().
int ChatMessageImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 186 of file ChatMessage.cpp.
References message.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ChatMessage friend
Definition at line 123 of file ChatMessage.h.
Member Data Documentation
WeakReference<ChatMessage*> server::chat::ChatMessageImplementation::_this
Definition at line 89 of file ChatMessage.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
String server::chat::ChatMessageImplementation::message protected
Definition at line 78 of file ChatMessage.h.
Referenced by ChatMessageImplementation(), readObjectMember(), setString(), toString(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatMessage.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatMessage.cpp