Core3: server::zone::objects::mission::CraftingMissionObjectiveAdapter Class Reference
server::zone::objects::mission::CraftingMissionObjectiveAdapter Class Reference
#include <CraftingMissionObjective.h>
Public Member Functions
CraftingMissionObjectiveAdapter (CraftingMissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializeTransientMembers ()
void updateMissionStatus (CreatureObject *player)
void abort ()
Public Member Functions inherited from server::zone::objects::mission::DeliverMissionObjectiveAdapter
DeliverMissionObjectiveAdapter (DeliverMissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializeTransientMembers ()
TangibleObject * getItem ()
int getObjectiveStatus ()
void activate ()
void deactivate ()
bool activateWithResult ()
void abort ()
void complete ()
void despawnNpcs ()
void updateMissionStatus (CreatureObject *player)
bool updateMissionTarget (CreatureObject *player)
NpcSpawnPoint * getTargetSpawnPoint ()
NpcSpawnPoint * getDestinationSpawnPoint ()
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveAdapter
MissionObjectiveAdapter (MissionObjective *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Detailed Description
Definition at line 134 of file CraftingMissionObjective.h.
Constructor & Destructor Documentation
CraftingMissionObjectiveAdapter::CraftingMissionObjectiveAdapter (CraftingMissionObjective * impl)
Definition at line 227 of file CraftingMissionObjective.cpp.
Member Function Documentation
void CraftingMissionObjectiveAdapter::abort ()
Definition at line 271 of file CraftingMissionObjective.cpp.
Referenced by invokeMethod().
void CraftingMissionObjectiveAdapter::finalize ()
Definition at line 259 of file CraftingMissionObjective.cpp.
Referenced by invokeMethod().
void CraftingMissionObjectiveAdapter::initializeTransientMembers ()
Definition at line 263 of file CraftingMissionObjective.cpp.
Referenced by invokeMethod().
void CraftingMissionObjectiveAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 230 of file CraftingMissionObjective.cpp.
References abort(), finalize(), initializeTransientMembers(), RPC_ABORT__, RPC_FINALIZE__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_UPDATEMISSIONSTATUS__CREATUREOBJECT_, and updateMissionStatus().
void CraftingMissionObjectiveAdapter::updateMissionStatus (CreatureObject * player)
Definition at line 267 of file CraftingMissionObjective.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/CraftingMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/CraftingMissionObjective.cpp