Core3: server::zone::objects::scene::SceneObject Class Reference
server::zone::objects::scene::SceneObject Class Reference
#include <SceneObject.h>
Public Member Functions
SceneObject ()
void initializePrivateData ()
void loadTemplateData (SharedObjectTemplate *templateData)
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendAttributeListTo (CreatureObject *object)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
void openContainerTo (CreatureObject *player)
byte checkContainerPermission (CreatureObject *player, unsigned short permission)
void closeContainerTo (CreatureObject *player, bool notify=true)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets=true)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
String getDetailedDescription ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
SceneObject (DummyConstructorParameter *param)
virtual ~SceneObject ()
Friends
class SceneObjectHelper
Detailed Description
Definition at line 267 of file SceneObject.h.
Constructor & Destructor Documentation
SceneObject::SceneObject ()
SceneObject constructor, used to initialize the object.
Precondition
{ templateData is a valid SharedObjectTemplate LuaObject that contains the necessary values to initialize SceneObject }
Postcondition
{ SceneObject is initialized }
Parameters
templateData templateData points to the SharedObjectTemplate LuaObject that is used to initialize SceneObejct members
Definition at line 39 of file SceneObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::_setStub().
SceneObject::SceneObject (DummyConstructorParameter * param) protected
Definition at line 46 of file SceneObject.cpp.
SceneObject::~SceneObject () protected virtual
Definition at line 50 of file SceneObject.cpp.
Member Function Documentation
DistributedObjectServant * SceneObject::_getImplementation ()
Definition at line 3755 of file SceneObject.cpp.
Referenced by addActiveArea(), addActiveSession(), addPendingTask(), canBeDestroyed(), checkContainerPermission(), clearContainerDefaultAllowPermission(), clearContainerDefaultDenyPermission(), closeContainerTo(), createChildObjects(), createComponents(), createContainerComponent(), destroyObjectFromDatabase(), destroyObjectFromWorld(), destroyPlayerCreatureFromDatabase(), doSendToClient(), dropActiveArea(), dropActiveSession(), dropSlottedObject(), error(), faceObject(), fillAttributeList(), getChildObjects(), getClient(), getContainedObjectsRecursive(), getContainerLock(), getContainerObjects(), getContainerPermissions(), getCoordinate(), getCountableObjectsRecursive(), getDisplayedName(), getObjectID(), getObservers(), getPendingTasks(), getSlottedObjects(), getTransformForCollisionMatrix(), getWorldCoordinate(), getZoneProcessServer(), handleObjectMenuSelect(), incrementMovementCounter(), info(), initializeChildObject(), initializePrivateData(), initializeTransientMembers(), inRangeObjects(), isActiveArea(), isActorObject(), isAiAgent(), isArmorObject(), isAttachment(), isAuctionObject(), isBuildingDeed(), isBuildingObject(), isCamoKit(), isCampStructure(), isCellObject(), isCityTerminal(), isCityVoteTerminal(), isCloningBuildingObject(), isComponent(), isContainerObject(), isControlDevice(), isCraftingStation(), isCraftingTool(), isCreatureHabitat(), isCreatureObject(), isDecoration(), isDeedObject(), isDiceObject(), isFactory(), isFactoryCrate(), isFireworkObject(), isGeneratorObject(), isGroupObject(), isGuildObject(), isHarvesterObject(), isInstallationDeed(), isInstallationObject(), isIntangibleObject(), isInWater(), isJunkDealer(), isLightsaberCrystalObject(), isManufactureSchematic(), isMissionObject(), isMissionTerminal(), isNoTrade(), isPlayerCreature(), isPsgArmorObject(), isRegion(), isResourceContainer(), isResourceSpawn(), isRobeObject(), isShipObject(), isSignObject(), isStructureObject(), isTangibleObject(), isTerminal(), isVehicleDeedObject(), isVehicleObject(), isWeaponObject(), isWearableContainerObject(), isWearableObject(), link(), loadTemplateData(), notifyCloseContainer(), notifyDissapear(), notifyInsert(), notifyInsertToZone(), notifyLoadFromDatabase(), notifyObjectInserted(), notifyObjectInsertedToChild(), notifyObjectRemoved(), notifyObjectRemovedFromChild(), notifyPositionUpdate(), notifyRemoveFromZone(), notifySelfPositionUpdate(), openContainerTo(), putInContainer(), removeAllContainerObjects(), removeFromContainerObjects(), removeObject(), removePendingTask(), removeSlottedObject(), rotate(), sendBaselinesTo(), sendContainerObjectsTo(), sendDestroyTo(), sendMessage(), sendSlottedObjectsTo(), sendToOwner(), setCityRegion(), setClientObject(), setClientObjectCRC(), setContainerAllowPermission(), setContainerComponent(), setContainerDefaultAllowPermission(), setContainerDefaultDenyPermission(), setContainerDenyPermission(), setContainerInheritPermissionsFromParent(), setContainerOwnerID(), setContainerType(), setContainerVolumeLimit(), setContainmentType(), setCustomObjectName(), setDetailedDescription(), setDirection(), setGameObjectType(), setLoggingName(), setMovementCounter(), setObjectMenuComponent(), setObjectName(), setParent(), setPlanetMapCategory(), setPlanetMapSubCategory(), setSendToClient(), setServerObjectCRC(), setTransformForCollisionMatrixIfNull(), setZone(), setZoneComponent(), setZoneProcessServer(), showFlyText(), switchZone(), synchronizedUIListen(), synchronizedUIStopListen(), teleport(), transferObject(), updateDirection(), updateToDatabase(), updateToDatabaseAllObjects(), updateToDatabaseWithoutChildren(), updateVehiclePosition(), updateZone(), and updateZoneWithParent().
DistributedObjectServant * SceneObject::_getImplementationForRead ()
Definition at line 3761 of file SceneObject.cpp.
Referenced by broadcastDestroy(), broadcastDestroyPrivate(), broadcastMessage(), broadcastMessagePrivate(), broadcastMessages(), broadcastMessagesPrivate(), broadcastObject(), broadcastObjectPrivate(), canAddObject(), compareTo(), containsActiveSession(), containsChildObject(), containsPendingTask(), fillObjectMenuResponse(), getActiveAreas(), getActiveAreasSize(), getActiveRegion(), getActiveSession(), getActiveSessionsCount(), getArrangementDescriptor(), getArrangementDescriptorSize(), getCityRegion(), getClientGameObjectType(), getClientObjectCRC(), getContainerObject(), getContainerObjectRecursive(), getContainerObjects(), getContainerObjectsSize(), getContainerType(), getContainerVolumeLimit(), getContainmentType(), getCustomObjectName(), getDataObjectComponent(), getDetailedDescription(), getDirection(), getDirectionAngle(), getDirectionW(), getDirectionX(), getDirectionY(), getDirectionZ(), getDistanceTo(), getGameObjectType(), getLocalZone(), getLoggingName(), getMovementCounter(), getObjectActiveSessions(), getObjectMenuComponent(), getObjectName(), getObjectNameStringIdFile(), getObjectNameStringIdName(), getObjectTemplate(), getParent(), getParentID(), getParentRecursively(), getPendingTask(), getPlanetCRC(), getPlanetMapCategory(), getPlanetMapCategoryCRC(), getPlanetMapSubCategory(), getPlanetMapSubCategoryCRC(), getRootParent(), getServerObjectCRC(), getSlotDescriptor(), getSlotDescriptorSize(), getSlottedObject(), getSlottedObjects(), getSlottedObjectsSize(), getSpecialDirectionAngle(), getWorldPosition(), getWorldPositionX(), getWorldPositionY(), getWorldPositionZ(), getZone(), getZoneComponent(), getZoneServer(), hasActiveArea(), hasArrangementDescriptor(), hasFullContainerObjects(), hasObjectInContainer(), hasObjectInSlottedContainer(), hasSlotDescriptor(), isASubChildOf(), isBazaarTerminal(), isCampKit(), isContainerFull(), isDetector(), isFishingBait(), isFishingPoleObject(), isGarage(), isGCWBase(), isInRange(), isInstrument(), isLiveSample(), isMinefield(), isPlayerObject(), isRecycleToolObject(), isRepairTool(), isSecurityTerminal(), isShuttleInstallation(), isStaticObject(), isTrapObject(), isTurret(), isTurretControlTerminal(), isVendor(), isWaypointObject(), sendAttributeListTo(), sendTo(), sendWithoutContainerObjectsTo(), and sendWithoutParentTo().
void SceneObject::_setImplementation (DistributedObjectServant * servant)
Definition at line 3765 of file SceneObject.cpp.
void SceneObject::addActiveArea (ActiveArea * area)
Definition at line 1171 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::addActiveArea(), and RPC_ADDACTIVEAREA__ACTIVEAREA_.
Referenced by CampKitMenuComponent::handleObjectMenuSelect(), and server::zone::ZoneImplementation::updateActiveAreas().
void SceneObject::addActiveSession (unsigned int type, Facade * session)
Definition at line 1026 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::addActiveSession(), and RPC_ADDACTIVESESSION__INT_FACADE_.
Referenced by server::zone::objects::creature::conversation::TrainerConversationObserverImplementation::createConversationSession(), server::zone::objects::creature::conversation::ConversationObserverImplementation::createConversationSession(), server::zone::managers::minigames::FishingManagerImplementation::createFishingSession(), GetAccountInfoCommand::doQueueCommand(), RequestStatMigrationDataCommand::doQueueCommand(), StructureTerminalMenuComponent::handleObjectMenuSelect(), StructureManager::placeStructureFromDeed(), server::zone::managers::city::CityManagerImplementation::promptCitySpecialization(), server::zone::managers::city::CityManagerImplementation::promptWithdrawCityTreasury(), CityManageMilitiaSuiCallback::run(), StartDanceCommand::startDance(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::startImageDesign(), and StartMusicCommand::startMusic().
void SceneObject::addPendingTask (const String & name, Task * task, int miliseconds)
Adds a pending task of this SceneObject
Precondition
{ this locked }
Postcondition
{ this locked}
Parameters
name Name of the task
task Task to add
Definition at line 918 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::addPendingTask().
Referenced by server::zone::managers::minigames::FishingManagerImplementation::createFishingEvent(), CurePackCommand::deactivateConditionTreatment(), HealDamageCommand::deactivateInjuryTreatment(), HealStateCommand::deactivateStateTreatment(), HealEnhanceCommand::deactivateWoundTreatment(), HealWoundCommand::deactivateWoundTreatment(), ForceMeditateCommand::doQueueCommand(), InvulnerableCommand::doQueueCommand(), ChannelForceCommand::doQueueCommand(), MeditateCommand::doQueueCommand(), RegainConsciousnessCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), LogoutServerCommand::doQueueCommand(), BurstRunCommand::doQueueCommand(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), server::zone::managers::creature::CreatureManagerImplementation::sample(), and server::zone::managers::minigames::ForageManagerImplementation::startForaging().
void SceneObject::broadcastDestroy (SceneObject * object, bool sendSelf)
Broadcasts an object to the in range objects
Precondition
{this object is locked, object is not null }
Postcondition
{this object is locked, in range objects received the object }
Parameters
object SceneObject that will be sent to the in range objects
sendSelf if true the owner of this object receives the object too
Definition at line 811 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::broadcastDestroy(), and RPC_BROADCASTDESTROY__SCENEOBJECT_BOOL_.
Referenced by ZoneComponent::destroyObjectFromWorld().
void SceneObject::broadcastDestroyPrivate (SceneObject * object, SceneObject * selfObject)
Definition at line 826 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::broadcastDestroyPrivate(), and RPC_BROADCASTDESTROYPRIVATE__SCENEOBJECT_SCENEOBJECT_.
void SceneObject::broadcastMessage (BasePacket * message, bool sendSelf, bool lockZone = true)
Broadcasts the message to the in range objects
Precondition
{this object is locked, message is not null }
Postcondition
{this object is locked, in range objects received a copy of the message, message is deleted }
Parameters
sendSelf if true the owner if this object receives the message too
Definition at line 749 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessage(), and RPC_BROADCASTMESSAGE__BASEPACKET_BOOL_BOOL_.
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), CombatManager::broadcastCombatAction(), AiStateComponent::broadcastNextPositionUpdate(), server::zone::managers::guild::GuildManagerImplementation::createGuild(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), DotPackCommand::doAnimationsRange(), HealDamageCommand::doAnimationsRange(), KipUpShotCommand::doQueueCommand(), RollShotCommand::doQueueCommand(), InvulnerableCommand::doQueueCommand(), TumbleToProneCommand::doQueueCommand(), DiveShotCommand::doQueueCommand(), RescueCommand::doQueueCommand(), TumbleToStandingCommand::doQueueCommand(), TumbleToKneelingCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), DiceMenuComponent::doRoll(), CombatManager::doTargetCombatAction(), CreatureHabitatMenuComponent::handleObjectMenuSelect(), server::zone::managers::creature::LairObserverImplementation::healLair(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), server::zone::managers::guild::GuildManagerImplementation::leaveGuild(), server::zone::managers::creature::LairObserverImplementation::notifyDestruction(), ContainerComponent::removeObject(), server::zone::objects::player::sessions::EntertainingSessionImplementation::sendEntertainingUpdate(), ResourceSpawner::sendSample(), ZoneComponent::teleport(), ContainerComponent::transferObject(), server::zone::managers::player::PlayerManagerImplementation::updatePermissionName(), ZoneComponent::updateZone(), and ZoneComponent::updateZoneWithParent().
void SceneObject::broadcastMessagePrivate (BasePacket * message, SceneObject * selfObject, bool lockZone)
Definition at line 765 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessagePrivate(), and RPC_BROADCASTMESSAGEPRIVATE__BASEPACKET_SCENEOBJECT_BOOL_.
void SceneObject::broadcastMessages (Vector< BasePacket * > * messages, bool sendSelf)
Broadcasts a vector of messages to the in range objects
Precondition
{this object is locked }
Postcondition
{ this object is locked, in range objects received the messages, messages are deleted and removed from the vector }
Parameters
messages a vector containing the messages to be sent, it will be emptied when messages get sent
sendSelf if true the owner of this object receives the messages too
Definition at line 841 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::broadcastMessages().
void SceneObject::broadcastMessagesPrivate (Vector< BasePacket * > * messages, SceneObject * selfObject)
Definition at line 850 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::broadcastMessagesPrivate().
void SceneObject::broadcastObject (SceneObject * object, bool sendSelf)
Broadcasts an object to the in range objects
Precondition
{this object is locked, object is not null }
Postcondition
{this object is locked, in range objects received the object }
Parameters
object SceneObject that will be sent to the in range objects
sendSelf if true the owner of this object receives the object too
Definition at line 781 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::broadcastObject(), and RPC_BROADCASTOBJECT__SCENEOBJECT_BOOL_.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), server::zone::managers::loot::LootManagerImplementation::createLoot(), server::zone::managers::resource::ResourceManagerImplementation::givePlayerResource(), ResourceSlot::returnToParents(), ComponentSlot::returnToParents(), EmptyHopperCallback::run(), ContainerComponent::transferObject(), and ImageDesignManager::updateHairObject().
void SceneObject::broadcastObjectPrivate (SceneObject * object, SceneObject * selfObject)
Definition at line 796 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::broadcastObjectPrivate(), and RPC_BROADCASTOBJECTPRIVATE__SCENEOBJECT_SCENEOBJECT_.
int SceneObject::canAddObject (SceneObject * object, int containmentType, String & errorDescription)
Evaluates if this object has the necessary free slots to be able to add the specified SceneObject
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be checked
error error string that the player will receive on error
Returns
returns 0 on success, or error code
Definition at line 235 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::canAddObject(), and RPC_CANADDOBJECT__SCENEOBJECT_INT_STRING_.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addProfessionStartingItems(), server::zone::managers::player::creation::PlayerCreationManager::addStartingItems(), and server::zone::managers::player::PlayerManagerImplementation::checkTradeItems().
int SceneObject::canBeDestroyed (CreatureObject * player)
Checks if the object can be destroyed
Precondition
{ player is locked }
Postcondition
{ player is locked }
Parameters
player Player that attempts to destroy this object
Returns
0 on succes, != 0 on error
Definition at line 380 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::canBeDestroyed(), and RPC_CANBEDESTROYED__CREATUREOBJECT_.
byte SceneObject::checkContainerPermission (CreatureObject * player, unsigned short permission)
Definition at line 583 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::checkContainerPermission().
Referenced by server::zone::objects::building::BuildingObjectImplementation::sendTo().
void SceneObject::clearContainerDefaultAllowPermission (unsigned short perm)
Definition at line 3130 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::clearContainerDefaultAllowPermission(), and RPC_CLEARCONTAINERDEFAULTALLOWPERMISSION__SHORT_.
void SceneObject::clearContainerDefaultDenyPermission (unsigned short perm)
Definition at line 3158 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::clearContainerDefaultDenyPermission(), and RPC_CLEARCONTAINERDEFAULTDENYPERMISSION__SHORT_.
void SceneObject::closeContainerTo (CreatureObject * player, bool notify = true)
Closes the container of a player
Definition at line 592 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::closeContainerTo(), and RPC_CLOSECONTAINERTO__CREATUREOBJECT_BOOL_.
int SceneObject::compareTo (SceneObject * obj)
Compares object ids of this object with obj
Precondition
{ this object is locked, obj is not null }
Postcondition
{this object is locked }
Parameters
obj SceneObject that will be compared to
Returns
returns 1 if this < obj, -1 if this > obj and 0 if this == obj
Definition at line 873 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::compareTo(), and RPC_COMPARETO__SCENEOBJECT_.
bool SceneObject::containsActiveSession (unsigned int type)
Definition at line 1041 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::containsActiveSession(), and RPC_CONTAINSACTIVESESSION__INT_.
Referenced by DestroystructureCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), TangibleObjectMenuComponent::handleObjectMenuSelect(), VendorMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::handleObjectMenuSelect(), and StructureManager::placeStructureFromDeed().
bool SceneObject::containsChildObject (SceneObject * obj)
Definition at line 3623 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::containsChildObject(), and RPC_CONTAINSCHILDOBJECT__SCENEOBJECT_.
Referenced by RotateFurnitureCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), and server::zone::managers::gcw::GCWManagerImplementation::notifyInstallationDestruction().
bool SceneObject::containsPendingTask (const String & name)
Definition at line 954 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::containsPendingTask(), and RPC_CONTAINSPENDINGTASK__STRING_.
void SceneObject::createChildObjects ()
Definition at line 3655 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::createChildObjects(), and RPC_CREATECHILDOBJECTS__.
void SceneObject::createComponents ()
Definition at line 77 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::createComponents(), and RPC_CREATECOMPONENTS__.
Referenced by server::zone::managers::object::ObjectManager::cloneObject().
void SceneObject::createContainerComponent ()
Definition at line 90 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::createContainerComponent(), and RPC_CREATECONTAINERCOMPONENT__.
void SceneObject::destroyObjectFromDatabase (bool destroyContainedObjects = false)
Destroys this object from database
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
destroyContainedObjects if true, will destroy from database all its contained objects
Definition at line 366 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::destroyObjectFromDatabase(), and RPC_DESTROYOBJECTFROMDATABASE__BOOL_.
Referenced by server::zone::objects::tangible::loot::LootkitObjectImplementation::addToKit(), server::zone::objects::region::CityRegionImplementation::cleanupDecorations(), server::zone::managers::vendor::VendorManager::destroyVendor(), CampTerminalMenuComponent::disbandCamp(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), TrainerMenuComponent::handleObjectMenuSelect(), and server::zone::managers::minigames::FishingManagerImplementation::removeSplash().
void SceneObject::destroyObjectFromWorld (bool sendSelfDestroy)
Destroys the object from the world
Definition at line 221 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::destroyObjectFromWorld(), and RPC_DESTROYOBJECTFROMWORLD__BOOL_.
Referenced by server::zone::objects::tangible::wearables::WearableObjectImplementation::applyAttachment(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::applyPowerup(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::callArakydDroid(), server::zone::objects::region::CityRegionImplementation::cleanupDecorations(), server::zone::objects::resource::ResourceContainerImplementation::combine(), server::zone::managers::vendor::VendorManager::destroyVendor(), CampTerminalMenuComponent::disbandCamp(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::findTarget(), TrainerMenuComponent::handleObjectMenuSelect(), ArtCrateMenuComponent::handleObjectMenuSelect(), ZoneContainerComponent::insertActiveArea(), AiStateComponent::notifyDespawn(), server::zone::managers::creature::LairObserverImplementation::notifyDestruction(), server::zone::managers::gcw::GCWManagerImplementation::notifyInstallationDestruction(), server::zone::managers::gcw::GCWManagerImplementation::notifyMinefieldDestruction(), server::zone::managers::gcw::GCWManagerImplementation::notifyTurretDestruction(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield(), server::zone::managers::gcw::GCWManagerImplementation::performDonateTurret(), StructureManager::placeStructureFromDeed(), server::zone::managers::mission::MissionManagerImplementation::removeMission(), server::zone::managers::resource::ResourceManagerImplementation::removePowerFromPlayer(), server::zone::managers::minigames::FishingManagerImplementation::removeSplash(), server::zone::objects::creature::events::DespawnCreatureOnPlayerDissappear::run(), AiStateComponent::selectWeapon(), server::zone::objects::creature::AiAgentImplementation::selectWeapon(), ZoneComponent::switchZone(), ImageDesignManager::updateHairObject(), and server::zone::objects::player::sessions::SlicingSessionImplementation::useClampFromInventory().
void SceneObject::destroyPlayerCreatureFromDatabase (bool destroyContainedObjects = false)
Destroys a PlayerCreature from the database. If this object is not a PlayerCreature then the method will return without doing anything.
Precondition
{ this is locked }
Postcondition
{ this is locked }
Parameters
destroyContainedObjects if true, will destroy from database all its contained objects
Definition at line 352 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::destroyPlayerCreatureFromDatabase(), and RPC_DESTROYPLAYERCREATUREFROMDATABASE__BOOL_.
bool SceneObject::doSendToClient ()
Definition at line 3728 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::doSendToClient(), and RPC_DOSENDTOCLIENT__.
void SceneObject::dropActiveArea (ActiveArea * area)
Definition at line 1185 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::dropActiveArea(), and RPC_DROPACTIVEAREA__ACTIVEAREA_.
Referenced by ZoneContainerComponent::removeActiveArea(), and server::zone::ZoneImplementation::updateActiveAreas().
bool SceneObject::dropActiveSession (unsigned int type)
Definition at line 1055 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::dropActiveSession(), and RPC_DROPACTIVESESSION__INT_.
Referenced by server::zone::objects::creature::conversation::ConversationObserverImplementation::cancelConversationSession(), GetAccountInfoCommand::doQueueCommand(), server::zone::managers::player::PlayerManagerImplementation::handleAbortTradeMessage(), server::zone::managers::player::PlayerManagerImplementation::handleVerifyTradeMessage(), server::zone::managers::minigames::FishingManagerImplementation::notifyCloseContainer(), server::zone::managers::minigames::FishingManagerImplementation::stopFishing(), and server::zone::objects::player::sessions::ImageDesignSessionImplementation::updateImageDesign().
void SceneObject::dropSlottedObject (const String & arrengementDescriptor)
Definition at line 1684 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::dropSlottedObject(), and RPC_DROPSLOTTEDOBJECT__STRING_.
void SceneObject::error (const String & msg)
Logs an error message
Precondition
{}
Postcondition
{error message has been printed to console and file }
Parameters
msg error message to print
Definition at line 144 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::error(), and RPC_ERROR__STRING_.
Referenced by server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::player::PlayerManagerImplementation::calculatePlayerLevel(), ContainerComponent::canAddObject(), CollisionManager::checkShipCollision(), CollisionManager::checkSphereCollision(), server::zone::managers::director::DirectorManager::clearScreenPlayData(), NpcConversationStartCommand::doQueueCommand(), MountCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), LogoutServerCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), ServerInfoCommand::executeCommand(), CityManagementMenuComponent::fillObjectMenuResponse(), PlayerManagementSessionSuiCallback::getPlayerGalaxyID(), ZoneContainerComponent::insertActiveArea(), server::zone::managers::director::DirectorManager::readScreenPlayData(), ContainerComponent::removeObject(), DestroyStructureTask::run(), EmptyHopperCallback::run(), ShipUpdateTransformCallback::run(), PlayerManagementSessionSuiCallback::runAccountInfo(), server::zone::managers::director::DirectorManager::spawnMobile(), server::zone::managers::director::DirectorManager::spawnMobileRandom(), server::zone::managers::skill::SkillManager::surrenderSkill(), ZoneComponent::switchZone(), ContainerComponent::transferObject(), DataTransformCallback::updatePosition(), ZoneComponent::updateZone(), ZoneComponent::updateZoneWithParent(), and server::zone::managers::director::DirectorManager::writeScreenPlayData().
void SceneObject::faceObject (SceneObject * obj)
Sets this objects direction so that the object is facing the specified object.
Parameters
obj The object to face.
Definition at line 2004 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::faceObject(), and RPC_FACEOBJECT__SCENEOBJECT_.
Referenced by AiStateComponent::checkNewAngle(), and AiStateComponent::sendConversationStartTo().
void SceneObject::fillAttributeList (AttributeListMessage * msg, CreatureObject * object)
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Definition at line 536 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::fillAttributeList().
void SceneObject::fillObjectMenuResponse (ObjectMenuResponse * menuResponse, CreatureObject * player)
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Definition at line 560 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::fillObjectMenuResponse().
Vector< ManagedReference< ActiveArea * > > * SceneObject::getActiveAreas ()
Definition at line 1227 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getActiveAreas().
Referenced by CampTerminalMenuComponent::assumeCampOwnership(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::callArakydDroid(), ZoneComponent::destroyObjectFromWorld(), CampTerminalMenuComponent::disbandCamp(), CampTerminalMenuComponent::fillObjectMenuResponse(), and CampTerminalMenuComponent::showCampStatus().
int SceneObject::getActiveAreasSize ()
Definition at line 1236 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getActiveAreasSize(), and RPC_GETACTIVEAREASSIZE__.
Referenced by DumpZoneInformationCommand::doQueueCommand().
Reference< ActiveArea * > SceneObject::getActiveRegion ()
Definition at line 1249 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getActiveRegion(), and RPC_GETACTIVEREGION__.
Reference< Facade * > SceneObject::getActiveSession (unsigned int type)
Returns a Facade session
Definition at line 1012 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getActiveSession(), and RPC_GETACTIVESESSION__INT_.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::zone::objects::creature::conversation::ConversationObserverImplementation::cancelConversationSession(), ChangeBandMusicCommand::canPlaySong(), BandFlourishCommand::changeStatus(), server::zone::managers::minigames::FishingManagerImplementation::checkFishingOnPositionUpdate(), server::zone::managers::player::PlayerManagerImplementation::checkTradeItems(), GroupManager::createGroup(), BandFlourishCommand::doBandFlourish(), StopBandCommand::doQueueCommand(), DenyServiceCommand::doQueueCommand(), SampleCommand::doQueueCommand(), StartBandCommand::doQueueCommand(), SurveyCommand::doQueueCommand(), ChangeDanceCommand::doQueueCommand(), CancelCraftingSessionCommand::doQueueCommand(), CreateManfSchematicCommand::doQueueCommand(), ChangeMusicCommand::doQueueCommand(), CreatePrototypeCommand::doQueueCommand(), FlourishCommand::doQueueCommand(), ImagedesignCommand::doQueueCommand(), NextCraftingStageCommand::doQueueCommand(), SelectDraftSchematicCommand::doQueueCommand(), StopDanceCommand::doQueueCommand(), StopMusicCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), RequestStatMigrationDataCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), FindCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), RequestSurveyCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), ChangeBandMusicCommand::doQueueCommand(), StartDanceCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), server::zone::managers::minigames::FishingManagerImplementation::fishingProceed(), server::zone::managers::minigames::FishingManagerImplementation::fishingStep(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), server::zone::managers::minigames::FishingManagerImplementation::getFishBoxID(), server::zone::managers::minigames::FishingManagerImplementation::getFishingEvent(), server::zone::managers::minigames::FishingManagerImplementation::getFishingState(), server::zone::managers::minigames::FishingManagerImplementation::getFishMarker(), server::zone::managers::minigames::FishingManagerImplementation::getNextAction(), server::zone::objects::creature::conversation::ConversationObserverImplementation::getNextConversationScreen(), server::zone::managers::player::PlayerManagerImplementation::handleAbortTradeMessage(), server::zone::managers::player::PlayerManagerImplementation::handleAcceptTransactionMessage(), server::zone::managers::player::PlayerManagerImplementation::handleAddItemToTradeWindow(), server::zone::managers::player::PlayerManagerImplementation::handleGiveMoneyMessage(), WeaponObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::ContainerImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::SurveyToolImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::handleObjectMenuSelect(), server::zone::objects::creature::conversation::screenhandlers::TrainerInfoScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainableSkillsScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerNextSkillsScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerSkillInfoScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerCanLearnSkillScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainSkillScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughCreditsScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughSkillPointsScreenHandler::handleScreen(), server::zone::managers::player::PlayerManagerImplementation::handleUnAcceptTransactionMessage(), server::zone::managers::player::PlayerManagerImplementation::handleVerifyTradeMessage(), server::zone::managers::minigames::FishingManagerImplementation::isPlaying(), GroupManager::joinGroup(), server::zone::managers::minigames::FishingManagerImplementation::mishapEvent(), server::zone::objects::creature::conversation::ConversationObserverImplementation::notifyObserverEvent(), BandFlourishCommand::printStatus(), StructureManager::redeedStructure(), DestroyStructureRequestSuiCallback::run(), FindSessionSuiCallback::run(), SlicingSessionSuiCallback::run(), DestroyStructureCodeSuiCallback::run(), CityTreasuryWithdrawalReasonSuiCallback::run(), CitySpecializationConfirmSuiCallback::run(), CitySpecializationSuiCallback::run(), CityTreasuryWithdrawalSuiCallback::run(), CreateVendorSuiCallback::run(), NameVendorSuiCallback::run(), SurveyCMinigameSuiCallback::run(), SurveyGMinigameSuiCallback::run(), AdBarkingPhraseSuiCallback::run(), ItemDropTradeCallback::run(), CityRemoveMilitiaMemberSuiCallback::run(), ImageDesignRejectMessageCallback::run(), ImageDesignChangeMessageCallback::run(), CraftingExperimentCallback::run(), CraftingCustomizationCallback::run(), PlayerManagementSessionSuiCallback::runAccountInfo(), PlayerManagementSessionSuiCallback::runDurationCallback(), PlayerManagementSessionSuiCallback::runReasonCallback(), PlayerManagementSessionSuiCallback::runSummaryCallback(), PlayerManagementSessionSuiCallback::runUnbanSummaryCallback(), server::zone::objects::creature::conversation::ConversationObserverImplementation::sendConversationScreenToPlayer(), ResourceSpawner::sendSample(), ResourceSpawner::sendSampleResults(), ResourceSpawner::sendSurvey(), server::zone::templates::mobile::ConversationScreen::sendTo(), server::zone::managers::minigames::FishingManagerImplementation::setFishBoxID(), server::zone::managers::minigames::FishingManagerImplementation::setFishingState(), server::zone::managers::minigames::FishingManagerImplementation::setFishMarker(), server::zone::managers::minigames::FishingManagerImplementation::setNextAction(), server::zone::objects::intangible::VehicleControlDeviceImplementation::spawnObject(), StartDanceCommand::startDance(), server::zone::managers::minigames::FishingManagerImplementation::startFishing(), server::zone::managers::player::PlayerManagerImplementation::startListen(), StartMusicCommand::startMusic(), server::zone::managers::player::PlayerManagerImplementation::startWatch(), server::zone::managers::minigames::FishingManagerImplementation::stopFishing(), server::zone::managers::minigames::FishingManagerImplementation::stopFishingEvent(), server::zone::managers::player::PlayerManagerImplementation::stopListen(), server::zone::managers::player::PlayerManagerImplementation::stopWatch(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::synchronizedUIListen(), and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
int SceneObject::getActiveSessionsCount ()
Definition at line 1069 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getActiveSessionsCount(), and RPC_GETACTIVESESSIONSCOUNT__.
String SceneObject::getArrangementDescriptor (int idx)
Definition at line 1560 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getArrangementDescriptor(), and RPC_GETARRANGEMENTDESCRIPTOR__INT_.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), server::zone::objects::scene::SceneObjectImplementation::hasObjectInSlottedContainer(), ContainerComponent::removeObject(), and ContainerComponent::transferObject().
int SceneObject::getArrangementDescriptorSize ()
Definition at line 1547 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getArrangementDescriptorSize(), and RPC_GETARRANGEMENTDESCRIPTORSIZE__.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::addWearableItem().
SortedVector< ManagedReference< SceneObject * > > * SceneObject::getChildObjects ()
Definition at line 3614 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::getChildObjects().
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addChildInstallationFromDeed(), ShuttleInstallationZoneComponent::destroyObjectFromWorld(), CampKitMenuComponent::handleObjectMenuSelect(), ZoneComponent::insertChildObjectsToZone(), server::zone::managers::gcw::GCWManagerImplementation::notifyInstallationDestruction(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMine(), and server::zone::managers::gcw::GCWManagerImplementation::sendBaseDefenseStatus().
ManagedWeakReference< CityRegion * > SceneObject::getCityRegion ()
Definition at line 1262 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getCityRegion().
Referenced by server::zone::managers::auction::AuctionsMapImplementation::addItem(), server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::zone::managers::auction::AuctionManagerImplementation::checkRetrieve(), server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), StructureManager::declareResidence(), ShuttleInstallationZoneComponent::destroyObjectFromWorld(), CityHallZoneComponent::destroyObjectFromWorld(), CitypardonCommand::doQueueCommand(), GrantZoningRightsCommand::doQueueCommand(), CitybanCommand::doQueueCommand(), InstallMissionTerminalCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), DumpZoneInformationCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), TransferstructureCommand::doTransferStructure(), CityManagementMenuComponent::fillObjectMenuResponse(), CityVotingMenuComponent::fillObjectMenuResponse(), TrainerMenuComponent::fillObjectMenuResponse(), CityDecorationMenuComponent::fillObjectMenuResponse(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::fillObjectMenuResponse(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), server::zone::managers::auction::AuctionManagerImplementation::getData(), server::zone::managers::vendor::VendorManager::handleDisplayStatus(), server::zone::managers::mission::MissionManagerImplementation::handleMissionListRequest(), CityManagementMenuComponent::handleObjectMenuSelect(), CityVotingMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), TrainerMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::handleObjectMenuSelect(), server::zone::objects::area::LairSpawnAreaImplementation::notifyEnter(), server::zone::objects::region::CityRegionImplementation::notifyEnter(), ShuttleZoneComponent::notifyInsertToZone(), PlaceCityHallComponent::notifyStructurePlaced(), PlaceCityHallComponent::placeStructure(), PlaceDecorationComponent::placeStructure(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), StructureManager::reportStructureStatus(), InstallMissionTerminalSuiCallback::run(), RecruitSkillTrainerSuiCallback::run(), RepairVehicleSuiCallback::run(), server::zone::managers::player::PlayerManagerImplementation::sendActivateCloneRequest(), and server::zone::managers::auction::AuctionsMapImplementation::updateUID().
ZoneClientSession * SceneObject::getClient ()
Definition at line 1912 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::getClient(), and RPC_GETCLIENT__.
Referenced by server::zone::objects::scene::SceneObjectImplementation::broadcastDestroyPrivate(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessagePrivate(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessagesPrivate(), server::zone::objects::scene::SceneObjectImplementation::broadcastObjectPrivate(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), server::zone::objects::group::GroupObjectImplementation::sendBaselinesTo(), and server::zone::objects::scene::SceneObjectImplementation::sendTo().
unsigned int SceneObject::getClientGameObjectType ()
Definition at line 1938 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getClientGameObjectType(), and RPC_GETCLIENTGAMEOBJECTTYPE__.
Referenced by server::zone::managers::auction::AuctionManagerImplementation::createVendorItem().
unsigned int SceneObject::getClientObjectCRC ()
Definition at line 1446 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getClientObjectCRC(), and RPC_GETCLIENTOBJECTCRC__.
Referenced by SchematicList::add(), CmdStartScene::CmdStartScene(), SchematicList::contains(), DraftSchematicGroup::contains(), WearablesDeltaVector::insertItemToMessage(), SchematicList::insertToMessage(), SceneObjectCreateMessage::SceneObjectCreateMessage(), and server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::startSession().
int SceneObject::getContainedObjectsRecursive ()
Definition at line 986 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::getContainedObjectsRecursive(), and RPC_GETCONTAINEDOBJECTSRECURSIVE__.
ReadWriteLock * SceneObject::getContainerLock ()
Definition at line 2153 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::getContainerLock().
Referenced by ContainerComponent::canAddObject(), ZoneComponent::destroyObjectFromWorld(), server::zone::objects::building::BuildingObjectImplementation::notifyRemoveFromZone(), ZoneContainerComponent::removeObject(), ContainerComponent::removeObject(), ContainerComponent::transferObject(), and server::zone::ZoneImplementation::updateActiveAreas().
Reference< SceneObject * > SceneObject::getContainerObject (int idx)
Definition at line 1764 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getContainerObject(), and RPC_GETCONTAINEROBJECT__INT_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::activateMissions(), server::zone::managers::player::PlayerManagerImplementation::addInsurableItemsRecursive(), SaberInventoryContainerComponent::canAddObject(), server::zone::objects::tangible::TangibleObjectImplementation::canRepair(), server::zone::objects::installation::factory::FactoryObjectImplementation::collectMatchesInInputHopper(), server::zone::managers::mission::MissionManagerImplementation::createCraftingMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::deactivateMissions(), server::zone::objects::building::BuildingObjectImplementation::destroyObjectFromDatabase(), WipeItemsCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), TangibleObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::tangible::tool::CraftingStationImplementation::findCraftingTool(), CurePackCommand::findCurePack(), HealEnhanceCommand::findEnhancePack(), RevivePlayerCommand::findRevivePack(), HealStateCommand::findStatePack(), HealDamageCommand::findStimPack(), HealWoundCommand::findWoundPack(), server::zone::managers::resource::ResourceManagerImplementation::getAvailablePowerFromPlayer(), server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::getBountyMissionObject(), server::zone::managers::director::DirectorManager::getContainerObjectByTemplate(), server::zone::ZoneImplementation::getInRangeObjects(), server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::getRelevantMissionObject(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAccept(), TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::objects::building::BuildingObjectImplementation::notifyDissapear(), server::zone::objects::building::BuildingObjectImplementation::notifyInsert(), server::zone::objects::building::BuildingObjectImplementation::notifyInsertToZone(), server::zone::objects::building::BuildingObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), server::zone::objects::building::BuildingObjectImplementation::notifyRemoveFromZone(), server::zone::managers::mission::MissionManagerImplementation::populateMissionList(), server::zone::managers::resource::ResourceManagerImplementation::removePowerFromPlayer(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), ResourceSlot::returnToParents(), server::zone::objects::building::BuildingObjectImplementation::sendTo(), server::zone::objects::player::PlayerObjectImplementation::unloadSpawnedChildren(), and server::zone::objects::player::sessions::EntertainingSessionImplementation::updateEntertainerMissionStatus().
Reference< SceneObject * > SceneObject::getContainerObject (unsigned long long objectID)
Definition at line 1815 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getContainerObject(), and RPC_GETCONTAINEROBJECT__LONG_.
Reference< SceneObject * > SceneObject::getContainerObjectRecursive (unsigned long long oid)
Definition at line 1670 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getContainerObjectRecursive(), and RPC_GETCONTAINEROBJECTRECURSIVE__LONG_.
void SceneObject::getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > & objects)
Definition at line 896 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getContainerObjects().
Referenced by SaberInventoryContainerComponent::canAddObject(), ContainerComponent::canAddObject(), server::zone::objects::building::BuildingObjectImplementation::notifyRemoveFromZone(), ContainerComponent::removeObject(), and ContainerComponent::transferObject().
VectorMap< unsigned long long, ManagedReference< SceneObject * > > * SceneObject::getContainerObjects ()
Definition at line 1778 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::getContainerObjects().
int SceneObject::getContainerObjectsSize ()
Definition at line 1712 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getContainerObjectsSize(), and RPC_GETCONTAINEROBJECTSSIZE__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::activateMissions(), ComponentSlot::add(), server::zone::managers::player::PlayerManagerImplementation::addInsurableItemsRecursive(), PlaceableLootContainerComponent::canAddObject(), LootContainerComponent::canAddObject(), MinefieldContainerComponent::canAddObject(), FireworkShowContainerComponent::canAddObject(), server::zone::objects::tangible::ContainerImplementation::canAddObject(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::canInventoryItemBeSoldAsJunk(), server::zone::objects::tangible::TangibleObjectImplementation::canRepair(), server::zone::managers::player::PlayerManagerImplementation::checkTradeItems(), server::zone::objects::installation::factory::FactoryObjectImplementation::collectMatchesInInputHopper(), server::zone::managers::mission::MissionManagerImplementation::createCraftingMissionObjectives(), server::zone::managers::mission::MissionManagerImplementation::deactivateMissions(), server::zone::objects::building::BuildingObjectImplementation::destroyObjectFromDatabase(), WipeItemsCommand::doQueueCommand(), FactoryObjectMenuComponent::fillObjectMenuResponse(), TangibleObjectMenuComponent::fillObjectMenuResponse(), CurePackCommand::findCurePack(), HealEnhanceCommand::findEnhancePack(), RevivePlayerCommand::findRevivePack(), HealStateCommand::findStatePack(), HealDamageCommand::findStimPack(), HealWoundCommand::findWoundPack(), server::zone::managers::resource::ResourceManagerImplementation::getAvailablePowerFromPlayer(), server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::getBountyMissionObject(), server::zone::managers::director::DirectorManager::getContainerObjectByTemplate(), server::zone::ZoneImplementation::getInRangeObjects(), server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::getRelevantMissionObject(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAccept(), TangibleObjectMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::AiAgentImplementation::hasLoot(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::objects::building::BuildingObjectImplementation::notifyDissapear(), server::zone::objects::building::BuildingObjectImplementation::notifyInsert(), server::zone::objects::building::BuildingObjectImplementation::notifyInsertToZone(), server::zone::objects::building::BuildingObjectImplementation::notifyLoadFromDatabase(), MinefieldZoneComponent::notifyPositionUpdate(), server::zone::objects::building::BuildingObjectImplementation::notifyRemoveFromZone(), server::zone::managers::mission::MissionManagerImplementation::populateMissionList(), server::zone::managers::resource::ResourceManagerImplementation::removePowerFromPlayer(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), ResourceSlot::returnToParents(), server::zone::objects::building::BuildingObjectImplementation::sendTo(), FireworkShowContainerComponent::transferObject(), and server::zone::objects::player::sessions::EntertainingSessionImplementation::updateEntertainerMissionStatus().
ContainerPermissions * SceneObject::getContainerPermissions ()
Definition at line 3107 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::getContainerPermissions().
Referenced by server::zone::objects::tangible::ContainerImplementation::canAddObject(), server::zone::objects::creature::CreatureImplementation::canHarvestMe(), PlaceableLootContainerComponent::checkContainerPermission(), LootContainerComponent::checkContainerPermission(), ContainerComponent::checkContainerPermission(), LootCommand::doQueueCommand(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::managers::minigames::FishingManagerImplementation::sendReward(), and server::zone::objects::building::BuildingObjectImplementation::sendTo().
unsigned int SceneObject::getContainerType ()
Definition at line 1899 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getContainerType(), and RPC_GETCONTAINERTYPE__.
unsigned int SceneObject::getContainerVolumeLimit ()
Definition at line 1751 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getContainerVolumeLimit(), and RPC_GETCONTAINERVOLUMELIMIT__.
Referenced by SaberInventoryContainerComponent::canAddObject(), ContainerComponent::canAddObject(), server::zone::objects::tangible::ContainerImplementation::canAddObject(), server::zone::managers::player::PlayerManagerImplementation::checkTradeItems(), ContainerComponent::transferObject(), DataTransformCallback::updatePosition(), and DataTransformWithParentCallback::updatePosition().
unsigned int SceneObject::getContainmentType ()
Definition at line 1951 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getContainmentType(), and RPC_GETCONTAINMENTTYPE__.
Referenced by WearablesDeltaVector::insertItemToMessage(), and server::zone::managers::objectcontroller::ObjectControllerImplementation::transferObject().
Vector3 SceneObject::getCoordinate (float distance, float angleDegrees)
Definition at line 1319 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::getCoordinate().
int SceneObject::getCountableObjectsRecursive ()
Definition at line 999 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::getCountableObjectsRecursive(), and RPC_GETCOUNTABLEOBJECTSRECURSIVE__.
Referenced by server::zone::objects::cell::CellObjectImplementation::canAddObject(), server::zone::objects::tangible::ContainerImplementation::canAddObject(), DataTransformCallback::updatePosition(), and DataTransformWithParentCallback::updatePosition().
UnicodeString SceneObject::getCustomObjectName ()
Definition at line 2162 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getCustomObjectName(), and RPC_GETCUSTOMOBJECTNAME__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::addWaypoint(), KickCommand::doQueueCommand(), StopBandCommand::doQueueCommand(), FactoryCrateObjectMessage3::FactoryCrateObjectMessage3(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleInsertFactorySchem(), IntangibleObjectMessage3::IntangibleObjectMessage3(), MissionObjectMessage3::MissionObjectMessage3(), server::chat::WaypointChatParameter::set(), server::zone::managers::player::PlayerManagerImplementation::startListen(), server::zone::managers::player::PlayerManagerImplementation::startWatch(), StaticObjectMessage3::StaticObjectMessage3(), TangibleObjectMessage3::TangibleObjectMessage3(), and server::zone::managers::name::NameManager::validateName().
DataObjectComponentReference * SceneObject::getDataObjectComponent ()
Definition at line 2286 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getDataObjectComponent().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::zone::managers::auction::AuctionsMapImplementation::addVendorItem(), VendorContainerComponent::checkContainerPermission(), GCWBaseContainerComponent::checkPVEPermission(), GCWBaseContainerComponent::checkPVPPermission(), server::zone::managers::auction::AuctionManagerImplementation::checkSaleItem(), server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), server::zone::managers::vendor::VendorManager::destroyVendor(), VendorMenuComponent::fillObjectMenuResponse(), CombatManager::getArmorPiercing(), CombatManager::getArmorTurretReduction(), server::zone::managers::gcw::GCWManagerImplementation::getDestructibleBuildingData(), server::zone::managers::gcw::GCWManagerImplementation::getTurretControlDataComponent(), server::zone::managers::gcw::GCWManagerImplementation::getTurretDataComponent(), server::zone::managers::auction::AuctionManagerImplementation::getVendorUID(), server::zone::managers::vendor::VendorManager::handleDisplayStatus(), VendorMenuComponent::handleObjectMenuSelect(), DiceMenuComponent::handleObjectMenuSelect(), server::zone::managers::vendor::VendorManager::handleRegisterVendorCallback(), server::zone::managers::vendor::VendorManager::handleRenameVendor(), server::zone::managers::vendor::VendorManager::handleUnregisterVendor(), IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage(), MinefieldZoneComponent::notifyPositionUpdate(), DetectorZoneComponent::notifyPositionUpdate(), TurretZoneComponent::notifyPositionUpdate(), VendorZoneComponent::notifyPositionUpdate(), server::zone::managers::vendor::VendorManager::promptDestroyVendor(), and server::zone::managers::auction::AuctionsMapImplementation::sendVendorUpdateMail().
String SceneObject::getDetailedDescription ()
Definition at line 1524 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getDetailedDescription().
Referenced by IntangibleObjectMessage6::IntangibleObjectMessage6().
Quaternion * SceneObject::getDirection ()
Definition at line 1437 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getDirection().
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addChildInstallationFromDeed(), server::zone::managers::mission::MissionManagerImplementation::createSpawnPoint(), FindPlayerCommand::doQueueCommand(), DumpZoneInformationCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), CollisionManager::getTransformMatrix(), server::zone::managers::mission::spawnmaps::NpcSpawnPoint::NpcSpawnPoint(), and PathFinderManager::transformToModelSpace().
float SceneObject::getDirectionAngle ()
Definition at line 1964 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getDirectionAngle(), and RPC_GETDIRECTIONANGLE__.
Referenced by server::zone::managers::minigames::FishingManagerImplementation::checkLocation(), server::zone::objects::tangible::firework::FireworkObjectImplementation::completeLaunch(), MoveFurnitureCommand::doQueueCommand(), CampKitMenuComponent::handleObjectMenuSelect(), StructureManager::isInStructureFootprint(), StructureManager::placeStructureFromDeed(), InstallMissionTerminalSuiCallback::run(), and RecruitSkillTrainerSuiCallback::run().
float SceneObject::getDirectionW ()
Definition at line 1424 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getDirectionW(), and RPC_GETDIRECTIONW__.
Referenced by DataTransform::DataTransform(), DataTransformWithParent::DataTransformWithParent(), ProneCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), SceneObjectCreateMessage::SceneObjectCreateMessage(), and ShipUpdateTransformCollisionMessage::ShipUpdateTransformCollisionMessage().
float SceneObject::getDirectionX ()
Definition at line 1385 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getDirectionX(), and RPC_GETDIRECTIONX__.
Referenced by DataTransform::DataTransform(), DataTransformWithParent::DataTransformWithParent(), ProneCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), SceneObjectCreateMessage::SceneObjectCreateMessage(), and ShipUpdateTransformCollisionMessage::ShipUpdateTransformCollisionMessage().
float SceneObject::getDirectionY ()
Definition at line 1411 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getDirectionY(), and RPC_GETDIRECTIONY__.
Referenced by DataTransform::DataTransform(), DataTransformWithParent::DataTransformWithParent(), ProneCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), SceneObjectCreateMessage::SceneObjectCreateMessage(), and ShipUpdateTransformCollisionMessage::ShipUpdateTransformCollisionMessage().
float SceneObject::getDirectionZ ()
Definition at line 1398 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getDirectionZ(), and RPC_GETDIRECTIONZ__.
Referenced by DataTransform::DataTransform(), DataTransformWithParent::DataTransformWithParent(), ProneCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), SceneObjectCreateMessage::SceneObjectCreateMessage(), and ShipUpdateTransformCollisionMessage::ShipUpdateTransformCollisionMessage().
String SceneObject::getDisplayedName ()
Definition at line 3713 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::getDisplayedName(), and RPC_GETDISPLAYEDNAME__.
Referenced by server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsorshipRequest(), server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer(), server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand(), PlayersNearYouMessage::addFoundPlayer(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::addIngredient(), server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), SetPlayerStateCommand::doQueueCommand(), CitypardonCommand::doQueueCommand(), DenyServiceCommand::doQueueCommand(), GrantZoningRightsCommand::doQueueCommand(), SetPerformanceBuffTargetCommand::doQueueCommand(), InsureCommand::doQueueCommand(), CitybanCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), DiagnoseCommand::doQueueCommand(), GuildstatusCommand::doQueueCommand(), InsuranceTerminalMenuComponent::handleObjectMenuSelect(), GroupManager::inviteToGroup(), GroupManager::joinGroup(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), server::zone::managers::guild::GuildManagerImplementation::leaveGuild(), LootContainerComponent::notifyObjectRemoved(), server::zone::managers::player::PlayerManagerImplementation::offerTeaching(), StructureManager::payMaintenance(), server::zone::managers::player::PlayerManagerImplementation::promptTeachableSkills(), server::zone::managers::city::CityManagerImplementation::registerCitizen(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::removeIngredient(), StructureManager::reportStructureStatus(), TaxPayMailTask::run(), server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberListTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredListTo(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport(), server::zone::managers::auction::AuctionsMapImplementation::sendVendorUpdateMail(), server::zone::managers::guild::GuildManagerImplementation::setMemberTitle(), CampTerminalMenuComponent::showCampStatus(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::tuneCrystal(), server::zone::managers::city::CityManagerImplementation::unregisterCitizen(), and server::zone::managers::player::PlayerManagerImplementation::updatePermissionName().
float SceneObject::getDistanceTo (SceneObject * object)
Definition at line 1106 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getDistanceTo(), and RPC_GETDISTANCETO__SCENEOBJECT_.
Referenced by StartBandCommand::canPlayInstrument(), server::zone::managers::player::PlayerManagerImplementation::checkTradeItems(), server::zone::managers::minigames::FishingManagerImplementation::createWindow(), server::zone::objects::creature::AiAgentImplementation::doAttack(), AiNPCComponent::doAwarenessCheck(), AiCreatureComponent::doAwarenessCheck(), EjectCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), LairMenuComponent::fillObjectMenuResponse(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), CombatManager::getHitChance(), server::zone::managers::player::PlayerManagerImplementation::getInRangeStructureWithAdminRights(), server::zone::ZoneImplementation::getNearestPlanetaryObject(), MissionTargetMap::getRandomTarget(), CampKitMenuComponent::handleObjectMenuSelect(), LairMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::InstrumentImplementation::handleObjectMenuSelect(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::objects::creature::conversation::ConversationObserverImplementation::notifyObserverEvent(), server::zone::objects::tangible::InstrumentObserverImplementation::notifyObserverEvent(), AiStateComponent::selectWeapon(), and ResourceSpawner::sendSampleResults().
float SceneObject::getDistanceTo (Coordinate * coordinate)
Definition at line 1120 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getDistanceTo().
unsigned int SceneObject::getGameObjectType ()
Definition at line 1925 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getGameObjectType(), and RPC_GETGAMEOBJECTTYPE__.
Referenced by CombatManager::broadcastCombatAction(), MinefieldContainerComponent::canAddObject(), server::zone::objects::tangible::ContainerImplementation::canAddObject(), InsureCommand::doQueueCommand(), LootSchematicMenuComponent::fillObjectMenuResponse(), TangibleObjectMenuComponent::fillObjectMenuResponse(), server::zone::managers::object::ObjectManager::loadPersistentObject(), server::zone::managers::director::DirectorManager::setAuthorizationState(), server::zone::managers::loot::LootManagerImplementation::setSkillMods(), and server::zone::objects::player::sessions::SlicingSessionImplementation::useClampFromInventory().
Zone * SceneObject::getLocalZone ()
Definition at line 1293 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getLocalZone(), and RPC_GETLOCALZONE__.
Referenced by DataTransformCallback::DataTransformCallback(), DataTransformWithParentCallback::DataTransformWithParentCallback(), ZoneComponent::destroyObjectFromWorld(), server::zone::objects::scene::SceneObjectAdapter::getLocalZone(), and ZoneComponent::updateZone().
String SceneObject::getLoggingName ()
Definition at line 2177 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getLoggingName(), and RPC_GETLOGGINGNAME__.
Referenced by server::zone::managers::object::ObjectManager::loadPersistentObject().
unsigned int SceneObject::getMovementCounter ()
Definition at line 2059 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getMovementCounter(), and RPC_GETMOVEMENTCOUNTER__.
Referenced by DataTransform::DataTransform(), DataTransformWithParent::DataTransformWithParent(), LightUpdateTransformMessage::LightUpdateTransformMessage(), LightUpdateTransformWithParentMessage::LightUpdateTransformWithParentMessage(), ShipUpdateTransformCollisionMessage::ShipUpdateTransformCollisionMessage(), ShipUpdateTransformMessage::ShipUpdateTransformMessage(), UpdateTransformMessage::UpdateTransformMessage(), and UpdateTransformWithParentMessage::UpdateTransformWithParentMessage().
VectorMap< unsigned int, ManagedReference< Facade * > > * SceneObject::getObjectActiveSessions ()
Definition at line 1082 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getObjectActiveSessions().
unsigned long long SceneObject::getObjectID ()
Definition at line 1306 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::getObjectID(), and RPC_GETOBJECTID__.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::abortShutdownSequence(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsorshipRequest(), server::zone::objects::player::sessions::EntertainingSessionImplementation::activateEntertainerBuff(), server::zone::objects::creature::CreatureImplementation::addAlreadyHarvested(), VendorDataComponent::addBarkTarget(), server::zone::objects::region::CityRegionImplementation::addBazaar(), server::zone::managers::auction::AuctionsMapImplementation::addBazaarItem(), server::zone::objects::building::BuildingObjectImplementation::addCell(), server::zone::managers::gcw::GCWManagerImplementation::addChildInstallationFromDeed(), server::zone::managers::city::CityManagerImplementation::addMilitiaMember(), server::zone::managers::gcw::GCWManagerImplementation::addMinefield(), server::zone::objects::player::PlayerObjectImplementation::addOwnedStructure(), server::zone::managers::visibility::VisibilityManager::addPlayerToBountyList(), server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::zone::managers::gcw::GCWManagerImplementation::addScanner(), server::zone::ZoneImplementation::addSceneObject(), server::zone::objects::tangible::loot::LootkitObjectImplementation::addToKit(), server::zone::managers::gcw::GCWManagerImplementation::addTurret(), server::zone::objects::player::PlayerObjectImplementation::addVendor(), server::zone::managers::auction::AuctionsMapImplementation::addVendorItem(), server::zone::objects::player::PlayerObjectImplementation::addWaypoint(), server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership(), server::zone::packets::scene::AttributeListMessage::AttributeListMessage(), BadgesResponseMessage::BadgesResponseMessage(), Biography::Biography(), CombatManager::broadcastCombatAction(), AiStateComponent::broadcastNextPositionUpdate(), server::zone::objects::creature::AiAgentImplementation::broadcastNextPositionUpdate(), server::zone::managers::auction::AuctionManagerImplementation::buyItem(), server::zone::objects::creature::conversation::ConversationObserverImplementation::cancelConversationSession(), server::zone::managers::auction::AuctionManagerImplementation::cancelItem(), server::zone::managers::player::PlayerManagerImplementation::canGroupMemberHarvestCorpse(), server::zone::objects::creature::CreatureImplementation::canHarvestMe(), FirstAidCommand::canPerformSkill(), ForceCureDiseaseCommand::canPerformSkill(), ForceCurePoisonCommand::canPerformSkill(), StopBleedingCommand::canPerformSkill(), HealStatesOtherCommand::canPerformSkill(), HealDamageCommand::canPerformSkill(), CurePackCommand::canPerformSkill(), server::zone::managers::city::CityManagerImplementation::castMayoralVote(), VendorContainerComponent::checkContainerPermission(), LootContainerComponent::checkContainerPermission(), ContainerComponent::checkContainerPermission(), server::zone::managers::auction::AuctionManagerImplementation::checkRetrieve(), server::zone::managers::auction::AuctionManagerImplementation::checkSaleItem(), server::zone::managers::planet::PlanetManagerImplementation::checkShuttleStatus(), server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackSecondTest(), server::zone::managers::player::PlayerManagerImplementation::checkTradeItems(), server::zone::managers::gcw::GCWManagerImplementation::checkVulnerabilityData(), server::zone::objects::tangible::threat::ThreatMap::clearThreatState(), VendorDataComponent::clearVendorBark(), ClientOpenContainerMessage::ClientOpenContainerMessage(), server::zone::managers::object::ObjectManager::cloneObject(), CmdStartScene::CmdStartScene(), CombatSpam::CombatSpam(), server::zone::objects::scene::SceneObjectImplementation::compareTo(), server::zone::managers::city::CityManagerImplementation::createCity(), server::zone::managers::guild::GuildManagerImplementation::createGuild(), server::zone::managers::player::PlayerManagerImplementation::createSkippedTutorialBuilding(), AuctionTerminalMap::createTerminalListing(), server::zone::managers::player::PlayerManagerImplementation::createTutorialBuilding(), server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), StructureManager::declareResidence(), server::zone::managers::guild::GuildManagerImplementation::declareWarByName(), CombatManager::declineDuel(), server::zone::managers::auction::AuctionsMapImplementation::deleteTerminalItems(), server::zone::objects::building::BuildingObjectImplementation::destroyObjectFromDatabase(), ZoneComponent::destroyObjectFromWorld(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), DotPackCommand::doAreaMedicActionTarget(), server::zone::objects::creature::AiAgentImplementation::doAttack(), server::zone::managers::auction::AuctionManagerImplementation::doAuctionBid(), server::zone::managers::gcw::GCWManagerImplementation::doBaseDestruction(), server::zone::managers::auction::AuctionManagerImplementation::doInstantBuy(), CitypardonCommand::doQueueCommand(), GrantZoningRightsCommand::doQueueCommand(), SetNameCommand::doQueueCommand(), InsureCommand::doQueueCommand(), LootCommand::doQueueCommand(), CitybanCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), InstallMissionTerminalCommand::doQueueCommand(), MountCommand::doQueueCommand(), RecruitSkillTrainerCommand::doQueueCommand(), RescueCommand::doQueueCommand(), GuildstatusCommand::doQueueCommand(), PermissionListModifyCommand::doQueueCommand(), UninviteCommand::doQueueCommand(), GiveItemCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), ConsentCommand::doQueueCommand(), UnconsentCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), TendCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), AttackStateComponent::doRecovery(), TransferstructureCommand::doTransferStructure(), DragIncapacitatedPlayerCommand::drag(), server::zone::ZoneImplementation::dropSceneObject(), AuctionTerminalMap::dropTerminalListing(), server::zone::managers::gcw::GCWManagerImplementation::endVulnerability(), server::zone::managers::auction::AuctionManagerImplementation::fillAuctionQueryHeadersResponseMessage(), CityManagementMenuComponent::fillObjectMenuResponse(), CityVotingMenuComponent::fillObjectMenuResponse(), TrainerMenuComponent::fillObjectMenuResponse(), VendorMenuComponent::fillObjectMenuResponse(), CampTerminalMenuComponent::fillObjectMenuResponse(), CityDecorationMenuComponent::fillObjectMenuResponse(), server::zone::objects::tangible::terminal::guild::GuildTerminalImplementation::fillObjectMenuResponse(), server::zone::objects::tangible::terminal::mission::MissionTerminalImplementation::fillObjectMenuResponse(), server::zone::managers::city::CityManagerImplementation::fixMayor(), CombatManager::freeDuelList(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), server::zone::managers::auction::AuctionsMapImplementation::getCommodityCount(), server::zone::objects::tangible::threat::ThreatMap::getHighestDamageGroupLeader(), server::zone::managers::player::PlayerManagerImplementation::getNearbyCraftingStation(), VendorDataComponent::getOwnershipRightsOf(), server::zone::managers::mission::MissionManagerImplementation::getRandomPlayerBounty(), AuctionTerminalMap::getTerminalData(), server::zone::managers::auction::AuctionsMapImplementation::getVendorItemCount(), AuctionTerminalMap::getVendorRegion(), server::zone::managers::auction::AuctionManagerImplementation::getVendorUID(), GuildResponseMessage::GuildResponseMessage(), server::zone::managers::player::PlayerManagerImplementation::handleAbortTradeMessage(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleDefenderAdded(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleDefenderDropped(), server::zone::managers::mission::MissionManagerImplementation::handleMissionListRequest(), CityManagementMenuComponent::handleObjectMenuSelect(), CityVotingMenuComponent::handleObjectMenuSelect(), InstallationObjectMenuComponent::handleObjectMenuSelect(), ThrowGrenadeMenuComponent::handleObjectMenuSelect(), FireHeavyWeaponMenuComponent::handleObjectMenuSelect(), VendorMenuComponent::handleObjectMenuSelect(), PlayerObjectMenuComponent::handleObjectMenuSelect(), InsuranceTerminalMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), TrapMenuComponent::handleObjectMenuSelect(), BountyHunterDroidMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handlePlayerKilled(), VendorDataComponent::hasBarkTarget(), server::zone::objects::creature::CreatureImplementation::hasSkillToHarvestMe(), server::zone::objects::player::sessions::EntertainingSessionImplementation::increaseEntertainerBuff(), WearablesDeltaVector::insertItemToMessage(), HopperList::insertToMessage(), GroupManager::inviteToGroup(), server::zone::objects::creature::CreatureObjectImplementation::isAggressiveTo(), server::zone::objects::building::BuildingObjectImplementation::isAllowedEntry(), server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy(), server::zone::objects::building::BuildingObjectImplementation::isCityBanned(), server::zone::objects::guild::GuildObjectImplementation::isGuildLeader(), server::zone::objects::creature::CreatureObjectImplementation::isInBountyMission(), server::zone::objects::player::PlayerObjectImplementation::isOwnedStructure(), server::zone::objects::auction::AuctionItemImplementation::isOwner(), server::zone::objects::structure::StructureObjectImplementation::isOwnerOf(), VendorDataComponent::isVendorOwner(), IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), server::zone::managers::player::PlayerManagerImplementation::killPlayer(), server::zone::managers::guild::GuildManagerImplementation::leaveGuild(), LightUpdateTransformMessage::LightUpdateTransformMessage(), LightUpdateTransformWithParentMessage::LightUpdateTransformWithParentMessage(), server::zone::managers::visibility::VisibilityManager::login(), server::zone::managers::visibility::VisibilityManager::logout(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), server::zone::objects::area::CampSiteActiveAreaImplementation::notifyEnter(), server::zone::objects::region::CityRegionImplementation::notifyEnter(), server::zone::objects::region::CityRegionImplementation::notifyExit(), ShuttleZoneComponent::notifyInsertToZone(), server::zone::managers::gcw::GCWManagerImplementation::notifyInstallationDestruction(), server::zone::objects::cell::CellObjectImplementation::notifyLoadFromDatabase(), server::zone::managers::gcw::GCWManagerImplementation::notifyMinefieldDestruction(), server::zone::objects::area::LairSpawnAreaImplementation::notifyObserverEvent(), PlaceCityHallComponent::notifyStructurePlaced(), server::zone::managers::gcw::GCWManagerImplementation::notifyTurretDestruction(), server::zone::packets::object::ObjectMenuResponse::ObjectMenuResponse(), SpawnStateComponent::onEnter(), server::zone::objects::building::BuildingObjectImplementation::onEnter(), server::zone::objects::building::BuildingObjectImplementation::payAccessFee(), server::zone::managers::gcw::GCWManagerImplementation::performGCWTasks(), VendorDataComponent::performVendorBark(), PlaceCityHallComponent::placeStructure(), StructureManager::placeStructure(), StructureManager::placeStructureFromDeed(), PlayClientEffectObjectMessage::PlayClientEffectObjectMessage(), PlayClientEventObjectMessage::PlayClientEventObjectMessage(), BountyHunterDroidMenuComponent::playerOwnsTheDroid(), server::zone::managers::guild::GuildManagerImplementation::promptAddNewEnemy(), server::zone::managers::vendor::VendorManager::promptDestroyVendor(), server::zone::managers::city::CityManagerImplementation::promptMayoralVote(), server::zone::managers::city::CityManagerImplementation::promptRegisterCity(), server::zone::managers::city::CityManagerImplementation::promptUnregisterCity(), server::zone::managers::city::CityManagerImplementation::promptWithdrawCityTreasury(), CharacterNameMap::put(), server::zone::managers::gcw::GCWManagerImplementation::refreshExpiredVulnerability(), server::zone::managers::city::CityManagerImplementation::registerCitizen(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), server::zone::managers::gcw::GCWManagerImplementation::registerGCWBase(), server::zone::managers::auction::AuctionsMapImplementation::removeBazaarItem(), server::zone::managers::city::CityManagerImplementation::removeMilitiaMember(), ZoneContainerComponent::removeObject(), ContainerComponent::removeObject(), server::zone::objects::player::PlayerObjectImplementation::removeOwnedStructure(), server::zone::managers::visibility::VisibilityManager::removePlayerFromBountyList(), server::zone::managers::planet::PlanetManagerImplementation::removeShuttle(), server::zone::objects::player::PlayerObjectImplementation::removeVendor(), server::zone::managers::auction::AuctionsMapImplementation::removeVendorItem(), server::zone::objects::creature::VehicleObjectImplementation::repairVehicle(), CombatManager::requestDuel(), CombatManager::requestEndDuel(), server::zone::managers::gcw::GCWManagerImplementation::resetVulnerability(), GuildSponsorVerifySuiCallback::run(), GuildSponsoredListSuiCallback::run(), GuildCreateAbbrevResponseSuiCallback::run(), GuildCreateNameResponseSuiCallback::run(), RenameCitySuiCallback::run(), ItemDropTradeCallback::run(), MissionAbortCallback::run(), MissionAcceptCallback::run(), SceneObjectCloseMessage::SceneObjectCloseMessage(), SceneObjectCreateMessage::SceneObjectCreateMessage(), SceneObjectDestroyMessage::SceneObjectDestroyMessage(), server::zone::managers::gcw::GCWManagerImplementation::scheduleBaseDestruction(), server::zone::managers::planet::PlanetManagerImplementation::scheduleShuttle(), server::zone::managers::gcw::GCWManagerImplementation::scheduleVulnerabilityEnd(), server::zone::managers::gcw::GCWManagerImplementation::scheduleVulnerabilityStart(), server::zone::managers::player::PlayerManagerImplementation::sendActivateCloneRequest(), server::zone::objects::creature::conversation::ConversationObserverImplementation::sendConversationScreenToPlayer(), AiStateComponent::sendConversationStartTo(), server::zone::objects::draftschematic::DraftSchematicImplementation::sendDraftSlotsTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildDisbandConfirmTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberOptionsTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSetTitleTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredOptionsTo(), server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsorTo(), server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner(), ResourceSpawner::sendResourceListForSurvey(), server::zone::objects::draftschematic::DraftSchematicImplementation::sendResourceWeightsTo(), server::zone::managers::minigames::FishingManagerImplementation::sendReward(), server::zone::templates::mobile::ConversationScreen::sendTo(), server::zone::objects::building::BuildingObjectImplementation::sendTo(), server::zone::objects::tangible::tool::CraftingToolImplementation::sendToolStartFailure(), server::chat::WaypointChatParameter::set(), server::zone::objects::scene::variables::StringIdParameter::set(), server::zone::objects::player::PlayerObjectImplementation::setCloningFacility(), server::zone::objects::player::PlayerObjectImplementation::setConversatingCreature(), server::zone::objects::player::PlayerObjectImplementation::setDeclaredResidence(), server::zone::managers::guild::GuildManagerImplementation::setMemberTitle(), server::zone::objects::area::CampSiteActiveAreaImplementation::setOwner(), server::zone::objects::tangible::threat::ThreatMap::setThreatState(), server::zone::objects::player::PlayerObjectImplementation::setWaypoint(), ShipUpdateTransformCollisionMessage::ShipUpdateTransformCollisionMessage(), CampTerminalMenuComponent::showCampStatus(), server::zone::packets::object::ShowFlyText::ShowFlyText(), server::zone::managers::guild::GuildManagerImplementation::sponsorPlayer(), server::zone::managers::player::PlayerManagerImplementation::startListen(), server::zone::managers::gcw::GCWManagerImplementation::startVulnerability(), server::zone::managers::player::PlayerManagerImplementation::startWatch(), server::zone::managers::guild::GuildManagerImplementation::toggleGuildPermission(), server::zone::managers::guild::GuildManagerImplementation::toggleWarStatus(), server::zone::managers::city::CityManagerImplementation::toggleZoningEnabled(), server::zone::managers::guild::GuildManagerImplementation::transferLeadership(), ContainerComponent::transferObject(), server::zone::managers::city::CityManagerImplementation::unregisterCitizen(), server::zone::managers::gcw::GCWManagerImplementation::unregisterGCWBase(), server::zone::managers::auction::AuctionManagerImplementation::updateAuctionOwner(), server::zone::managers::director::DirectorManager::updateCellPermission(), server::zone::managers::director::DirectorManager::updateCellPermissionGroup(), UpdateContainmentMessage::UpdateContainmentMessage(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::updateImageDesign(), UpdatePVPStatusMessage::UpdatePVPStatusMessage(), AuctionTerminalMap::updateTerminalSearch(), AuctionTerminalMap::updateTerminalUID(), UpdateTransformMessage::UpdateTransformMessage(), UpdateTransformWithParentMessage::UpdateTransformWithParentMessage(), and WeaponRanges::WeaponRanges().
ObjectMenuComponent * SceneObject::getObjectMenuComponent ()
Definition at line 2277 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getObjectMenuComponent().
StringId * SceneObject::getObjectName ()
Definition at line 1485 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getObjectName().
Referenced by server::zone::managers::minigames::GamblingManagerImplementation::bet(), FactoryCrateObjectMessage3::FactoryCrateObjectMessage3(), server::zone::managers::creature::DnaManager::generateSample(), IntangibleObjectMessage3::IntangibleObjectMessage3(), NoBuildAreaMap::isNoBuildArea(), MissionObjectMessage3::MissionObjectMessage3(), InsuranceAllConfirmSuiCallback::run(), InsuranceMenuSuiCallback::run(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailCondemned(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailDecay(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailMaintenanceWithdrawnFromBank(), server::zone::managers::minigames::FishingManagerImplementation::sendReward(), StaticObjectMessage3::StaticObjectMessage3(), TangibleObjectMessage3::TangibleObjectMessage3(), and server::zone::managers::name::NameManager::validateName().
String SceneObject::getObjectNameStringIdFile ()
Definition at line 1494 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getObjectNameStringIdFile(), and RPC_GETOBJECTNAMESTRINGIDFILE__.
Referenced by server::zone::objects::factorycrate::FactoryCrateImplementation::fillAttributeList(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleInsertFactorySchem(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMine(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield(), and server::zone::managers::gcw::GCWManagerImplementation::performDonateTurret().
String SceneObject::getObjectNameStringIdName ()
Definition at line 1509 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getObjectNameStringIdName(), and RPC_GETOBJECTNAMESTRINGIDNAME__.
Referenced by server::zone::objects::factorycrate::FactoryCrateImplementation::fillAttributeList(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), TurretFireTask::getTargetName(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleInsertFactorySchem(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMine(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield(), server::zone::managers::gcw::GCWManagerImplementation::performDonateTurret(), and server::zone::managers::city::CityManagerImplementation::sendMaintenanceDestroyEmail().
SharedObjectTemplate * SceneObject::getObjectTemplate ()
Definition at line 3637 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getObjectTemplate().
Referenced by ComponentSlot::add(), server::zone::managers::player::creation::PlayerCreationManager::addHair(), server::zone::managers::player::creation::PlayerCreationManager::addStartingItemsInto(), server::zone::managers::player::creation::PlayerCreationManager::addStartingWeaponsInto(), server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), PlayerContainerComponent::canAddObject(), CollisionManager::checkLineOfSightInBuilding(), ImageDesignManager::createHairObject(), server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), ZoneComponent::destroyObjectFromWorld(), GetObjVarsCommand::doQueueCommand(), SetprivacyCommand::doQueueCommand(), LootSchematicMenuComponent::fillObjectMenuResponse(), DiceMenuComponent::fillObjectMenuResponse(), BountyHunterDroidMenuComponent::fillObjectMenuResponse(), CollisionManager::getAABBTree(), CollisionManager::getWorldFloorCollision(), CampKitMenuComponent::handleObjectMenuSelect(), GogglesObjectMenuComponent::handleObjectMenuSelect(), SkillBuffObjectMenuComponent::handleObjectMenuSelect(), LootSchematicMenuComponent::handleObjectMenuSelect(), ArmorObjectMenuComponent::handleObjectMenuSelect(), BountyHunterDroidMenuComponent::handleObjectMenuSelect(), DiceMenuComponent::handleObjectMenuSelect(), MinefieldDataComponent::initializeTransientMembers(), TurretDataComponent::initializeTransientMembers(), server::zone::managers::planet::PlanetManagerImplementation::isInObjectsNoBuildZone(), StructureManager::isInStructureFootprint(), BountyHunterDroidMenuComponent::isProbeDroid(), BountyHunterDroidMenuComponent::isSeekerDroid(), server::zone::objects::mission::bountyhunter::events::CallArakydTask::noInterferingObjects(), server::zone::managers::gcw::GCWManagerImplementation::performDonateMinefield(), server::zone::managers::gcw::GCWManagerImplementation::performDonateTurret(), StructureManager::placeStructureFromDeed(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::randomizeVendorLooks(), server::zone::managers::gcw::GCWManagerImplementation::registerGCWBase(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport(), server::zone::managers::loot::LootManagerImplementation::setInitialObjectStats(), server::zone::managers::gcw::GCWManagerImplementation::unregisterGCWBase(), ImageDesignManager::updateColorVariable(), and ImageDesignManager::updateCustomization().
SortedVector< ManagedReference< Observer * > > SceneObject::getObservers (unsigned int eventType)
The returning value points directly to the internal vector, do not delete it or store it
Definition at line 3646 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::getObservers().
Referenced by CombatManager::calculateDamage(), LairMenuComponent::fillObjectMenuResponse(), CampKitMenuComponent::handleObjectMenuSelect(), and server::zone::objects::tangible::InstrumentImplementation::handleObjectMenuSelect().
ManagedWeakReference< SceneObject * > SceneObject::getParent ()
Definition at line 2072 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getParent(), and RPC_GETPARENT__.
Referenced by ResourceSlot::add(), server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::applyPowerup(), server::zone::managers::player::PlayerManagerImplementation::awardBadge(), AiStateComponent::broadcastNextPositionUpdate(), server::zone::objects::tangible::ContainerImplementation::canAddObject(), StartBandCommand::canPlayInstrument(), ContainerComponent::checkContainerPermission(), CollisionManager::checkLineOfSight(), CollisionManager::checkLineOfSightWorldToCell(), server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackFirstTest(), server::zone::objects::resource::ResourceContainerImplementation::combine(), ZoneComponent::destroyObjectFromWorld(), AttackStateComponent::doMovement(), EjectCommand::doQueueCommand(), ResourceContainerTransferCommand::doQueueCommand(), ProneCommand::doQueueCommand(), AreatrackCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), MountCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), DismountCommand::doQueueCommand(), DumpZoneInformationCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), PlaceStructureModeCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), BountyHunterDroidMenuComponent::droidIsInPlayerInventory(), server::zone::managers::player::PlayerManagerImplementation::ejectPlayerFromBuilding(), TangibleObjectMenuComponent::fillObjectMenuResponse(), ArmorObjectMenuComponent::fillObjectMenuResponse(), CityDecorationMenuComponent::fillObjectMenuResponse(), ObjectMenuComponent::fillObjectMenuResponse(), AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), PathFinderManager::findPathFromCellToCell(), PathFinderManager::findPathFromCellToDifferentCell(), PathFinderManager::findPathFromCellToWorld(), PathFinderManager::findPathFromWorldToCell(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), DragIncapacitatedPlayerCommand::getCoordinate(), FleeStateComponent::getFleeLocation(), PathFinderManager::getFloorMesh(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAccept(), ElevatorMenuComponent::handleObjectMenuSelect(), GogglesObjectMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), ArmorObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::intangible::ShipControlDeviceImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::InstrumentImplementation::handleObjectMenuSelect(), StructureManager::moveFirstItemTo(), PlayerZoneComponent::notifyInsert(), server::zone::objects::building::BuildingObjectImplementation::notifyInsert(), SaberInventoryContainerComponent::notifyObjectInserted(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), LootContainerComponent::notifyObjectRemoved(), SaberInventoryContainerComponent::notifyObjectRemoved(), AiNPCComponent::notifyPositionUpdate(), AiCreatureComponent::notifyPositionUpdate(), TerrainManager::notifyPositionUpdate(), server::zone::objects::area::LairSpawnAreaImplementation::notifyPositionUpdate(), server::zone::objects::player::PlayerObjectImplementation::reload(), server::zone::managers::mission::MissionManagerImplementation::removeMission(), ContainerComponent::removeObject(), InstallMissionTerminalSuiCallback::run(), RecruitSkillTrainerSuiCallback::run(), SelectCharacterCallback::run(), NewbieTutorialResponseCallback::run(), server::zone::objects::ship::ShipObjectImplementation::sendBaselinesTo(), AiStateComponent::sendConversationStartTo(), server::zone::objects::creature::CreatureObjectImplementation::setState(), server::zone::objects::tangible::InstrumentImplementation::spawnInAdminCell(), server::zone::objects::tangible::InstrumentImplementation::spawnInForeignCell(), server::zone::objects::intangible::VehicleControlDeviceImplementation::storeObject(), PlayerZoneComponent::switchZone(), PlayerZoneComponent::teleport(), ZoneContainerComponent::transferObject(), ContainerComponent::transferObject(), server::zone::managers::objectcontroller::ObjectControllerImplementation::transferObject(), AiStateComponent::updateCurrentPosition(), DataTransformWithParentCallback::updatePosition(), server::zone::managers::player::PlayerManagerImplementation::updateSwimmingState(), ZoneComponent::updateZone(), PlayerZoneComponent::updateZoneWithParent(), ZoneComponent::updateZoneWithParent(), and WorldCoordinates::WorldCoordinates().
unsigned long long SceneObject::getParentID ()
Returns the object id of the parent of this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns 0 if this object doesnt have a parent, otherwise returns its object id
Definition at line 905 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getParentID(), and RPC_GETPARENTID__.
Referenced by server::zone::managers::weather::WeatherManagerImplementation::applySandstormDamage(), server::zone::managers::gcw::GCWManagerImplementation::canUseTerminals(), server::zone::managers::mission::MissionManagerImplementation::createSpawnPoint(), DataTransformWithParent::DataTransformWithParent(), ZoneComponent::destroyObjectFromWorld(), NpcConversationStartCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), CreateCreatureCommand::doQueueCommand(), SitServerCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), BountyHunterDroidMenuComponent::droidIsInZone(), FriendsListMessage::FriendsListMessage(), ElevatorMenuComponent::handleObjectMenuSelect(), BlueprintEntry::hasEnoughResources(), IgnoreListMessage::IgnoreListMessage(), LightUpdateTransformWithParentMessage::LightUpdateTransformWithParentMessage(), StructureManager::moveFirstItemTo(), server::zone::objects::area::ActiveAreaImplementation::notifyEnter(), server::zone::objects::area::ActiveAreaImplementation::notifyExit(), ZoneComponent::notifyInsertToZone(), server::chat::WaypointChatParameter::set(), server::zone::objects::tangible::InstrumentImplementation::spawnInForeignCell(), server::zone::objects::tangible::InstrumentImplementation::spawnOutside(), server::zone::managers::minigames::ForageManagerImplementation::startForaging(), UpdateTransformWithParentMessage::UpdateTransformWithParentMessage(), and PlayerZoneComponent::updateZoneWithParent().
ManagedWeakReference< SceneObject * > SceneObject::getParentRecursively (unsigned int gameObjectType)
Returns the parent of object type in the tree
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
Returns the parent of object type in the tree
Definition at line 2125 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getParentRecursively(), and RPC_GETPARENTRECURSIVELY__INT_.
Referenced by RecycleToolContainerComponent::canAddObject(), server::zone::managers::gcw::GCWManagerImplementation::canStartSlice(), server::zone::managers::gcw::GCWManagerImplementation::completeSecuritySlice(), DeclareresidenceCommand::doQueueCommand(), server::zone::managers::gcw::GCWManagerImplementation::failSecuritySlice(), PowerRegulatorMenuComponent::fillObjectMenuResponse(), TurretControlMenuComponent::fillObjectMenuResponse(), OverrideTerminalMenuComponent::fillObjectMenuResponse(), SecurityTerminalMenuComponent::fillObjectMenuResponse(), UplinkTerminalMenuComponent::fillObjectMenuResponse(), HQMenuComponent::fillObjectMenuResponse(), PowerRegulatorMenuComponent::handleObjectMenuSelect(), TurretControlMenuComponent::handleObjectMenuSelect(), OverrideTerminalMenuComponent::handleObjectMenuSelect(), SecurityTerminalMenuComponent::handleObjectMenuSelect(), UplinkTerminalMenuComponent::handleObjectMenuSelect(), HQMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::deed::pet::PetDeedImplementation::handleObjectMenuSelect(), server::zone::managers::gcw::GCWManagerImplementation::handlePowerRegulatorSwitch(), server::zone::managers::gcw::GCWManagerImplementation::isTerminalDamaged(), server::zone::objects::player::sessions::ImageDesignPositionObserverImplementation::notifyObserverEvent(), server::zone::managers::gcw::GCWManagerImplementation::processDNASample(), server::zone::managers::gcw::GCWManagerImplementation::repairTerminal(), server::zone::managers::gcw::GCWManagerImplementation::sendTurretAttackListTo(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::startImageDesign(), server::zone::managers::guild::GuildManagerImplementation::transferGuildHall(), and server::zone::managers::skill::SkillManager::updateXpLimits().
Reference< Task * > SceneObject::getPendingTask (const String & name)
Looks up a specific pending tasks by the name
Precondition
{ this locked }
Postcondition
{ this locked }
Parameters
name Name of the task to lookup
Definition at line 945 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getPendingTask().
Referenced by server::zone::objects::intangible::VehicleControlDeviceImplementation::cancelSpawnObject(), InvulnerableCommand::doQueueCommand(), MeditateCommand::doQueueCommand(), ThrowTrapCommand::doQueueCommand(), LogoutServerCommand::doQueueCommand(), RequestCoreSampleCommand::doQueueCommand(), RequestSurveyCommand::doQueueCommand(), ForceOfWillCommand::doQueueCommand(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), server::zone::objects::tangible::consumable::ConsumableImplementation::handleObjectMenuSelect(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), server::zone::managers::resource::ResourceManagerImplementation::notifyObserverEvent(), server::zone::managers::player::PlayerManagerImplementation::notifyObserverEvent(), server::zone::managers::player::PlayerManagerImplementation::rescheduleCorpseDestruction(), server::zone::managers::creature::CreatureManagerImplementation::sample(), and server::zone::managers::minigames::ForageManagerImplementation::startForaging().
PendingTasksMap * SceneObject::getPendingTasks ()
Definition at line 936 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::getPendingTasks().
unsigned int SceneObject::getPlanetCRC ()
Definition at line 3422 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getPlanetCRC(), and RPC_GETPLANETCRC__.
Referenced by server::zone::managers::mission::MissionManagerImplementation::createSpawnPoint(), and BroadcastPlanetCommand::doQueueCommand().
PlanetMapCategory * SceneObject::getPlanetMapCategory ()
Definition at line 3596 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getPlanetMapCategory().
int SceneObject::getPlanetMapCategoryCRC ()
Definition at line 3552 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getPlanetMapCategoryCRC(), and RPC_GETPLANETMAPCATEGORYCRC__.
PlanetMapCategory * SceneObject::getPlanetMapSubCategory ()
Definition at line 3605 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getPlanetMapSubCategory().
int SceneObject::getPlanetMapSubCategoryCRC ()
Definition at line 3565 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getPlanetMapSubCategoryCRC(), and RPC_GETPLANETMAPSUBCATEGORYCRC__.
ManagedWeakReference< SceneObject * > SceneObject::getRootParent ()
Returns the parent of all children in the object tree
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns the parent of all children in the object tree
Definition at line 2112 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getRootParent(), and RPC_GETROOTPARENT__.
Referenced by CollisionManager::checkLineOfSight(), server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackSecondTest(), SetprivacyCommand::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), MoveFurnitureCommand::doQueueCommand(), CollisionManager::getCellFloorCollision(), server::zone::managers::auction::AuctionManagerImplementation::getData(), server::zone::managers::player::PlayerManagerImplementation::getInRangeStructureWithAdminRights(), VendorMenuComponent::handleObjectMenuSelect(), server::zone::managers::radial::RadialManagerImplementation::handleObjectMenuSelect(), server::zone::objects::player::sessions::EntertainingSessionImplementation::isInEntertainingBuilding(), server::zone::objects::area::GarageAreaImplementation::notifyEnter(), server::zone::objects::building::BuildingObjectImplementation::notifyInsert(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToZone(), StructureManager::payMaintenance(), ContainerComponent::removeObject(), SelectCharacterCallback::run(), server::zone::objects::building::BuildingObjectImplementation::updateCellPermissionsTo(), ZoneComponent::updateInRangeObjectsOnMount(), ZoneComponent::updateZone(), ZoneComponent::updateZoneWithParent(), and server::zone::managers::skill::SkillModManager::verifyStructureSkillMods().
unsigned int SceneObject::getServerObjectCRC ()
Definition at line 1459 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getServerObjectCRC(), and RPC_GETSERVEROBJECTCRC__.
Referenced by server::zone::objects::tangible::loot::LootkitObjectImplementation::canAddObject(), server::zone::objects::installation::factory::FactoryObjectImplementation::collectMatchesInInputHopper(), DotPackCommand::doAreaMedicActionTarget(), DismountCommand::doQueueCommand(), SkillBuffObjectAttributeListComponent::fillAttributeList(), LootSchematicMenuComponent::fillObjectMenuResponse(), DiceMenuComponent::fillObjectMenuResponse(), server::zone::managers::director::DirectorManager::getContainerObjectByTemplate(), SkillBuffObjectMenuComponent::handleObjectMenuSelect(), LootSchematicMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), and DiceMenuComponent::handleObjectMenuSelect().
String SceneObject::getSlotDescriptor (int idx)
Definition at line 1576 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getSlotDescriptor(), and RPC_GETSLOTDESCRIPTOR__INT_.
int SceneObject::getSlotDescriptorSize ()
Definition at line 1643 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getSlotDescriptorSize(), and RPC_GETSLOTDESCRIPTORSIZE__.
Reference< SceneObject * > SceneObject::getSlottedObject (const String & slot)
Definition at line 1629 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getSlottedObject(), and RPC_GETSLOTTEDOBJECT__STRING_.
Referenced by server::zone::objects::player::PlayerObjectImplementation::activateMissions(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::addIngredient(), server::zone::managers::player::creation::PlayerCreationManager::addProfessionStartingItems(), server::zone::managers::player::creation::PlayerCreationManager::addRacialMods(), ResourceSpawner::addResourceToPlayerInventory(), server::zone::managers::player::creation::PlayerCreationManager::addStartingItems(), server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), server::zone::objects::building::BuildingObjectImplementation::broadcastCellPermissions(), server::zone::managers::weather::WeatherManagerImplementation::calculateSandstormProtection(), server::zone::objects::tangible::ContainerImplementation::canAddObject(), StartBandCommand::canPlayInstrument(), server::zone::objects::tangible::TangibleObjectImplementation::canRepair(), server::zone::managers::auction::AuctionManagerImplementation::checkRetrieve(), server::zone::managers::player::PlayerManagerImplementation::checkTradeItems(), server::zone::managers::director::DirectorManager::clearScreenPlayData(), server::zone::managers::visibility::VisibilityManager::clearVisibility(), server::zone::managers::mission::MissionManagerImplementation::createCraftingMissionObjectives(), GroupManager::createGroup(), ImageDesignManager::createHairObject(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::createSellJunkLootSelection(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::createVendor(), server::zone::managers::mission::MissionManagerImplementation::deactivateMissions(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::decay(), server::zone::managers::visibility::VisibilityManager::decreaseVisibility(), RemoveFriendCommand::doQueueCommand(), RemoveIgnoreCommand::doQueueCommand(), RequestBadgesCommand::doQueueCommand(), RequestWaypointAtPositionCommand::doQueueCommand(), SnoopCommand::doQueueCommand(), SetSpokenLanguageCommand::doQueueCommand(), StartBandCommand::doQueueCommand(), GetPlayerIdCommand::doQueueCommand(), GetStationNameCommand::doQueueCommand(), LfgCommand::doQueueCommand(), LootCommand::doQueueCommand(), NewbiehelperCommand::doQueueCommand(), ToggleAwayFromKeyBoardCommand::doQueueCommand(), ToggleDisplayingFactionRankCommand::doQueueCommand(), AnonCommand::doQueueCommand(), ConcealCommand::doQueueCommand(), RolePlayCommand::doQueueCommand(), WipeItemsCommand::doQueueCommand(), FindObjectCommand::doQueueCommand(), FlourishCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), ServerDestroyObjectCommand::doQueueCommand(), AddFriendCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), AddIgnoreCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), StartDanceCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), BountyHunterDroidMenuComponent::droidIsInPlayerInventory(), server::zone::objects::tangible::fishing::FishObjectImplementation::filet(), TangibleObjectMenuComponent::fillObjectMenuResponse(), CreatureHabitatMenuComponent::fillObjectMenuResponse(), CampTerminalMenuComponent::fillObjectMenuResponse(), server::zone::objects::tangible::tool::CraftingStationImplementation::findCraftingTool(), CurePackCommand::findCurePack(), HealEnhanceCommand::findEnhancePack(), RevivePlayerCommand::findRevivePack(), HealStateCommand::findStatePack(), HealDamageCommand::findStimPack(), BoardShuttleCommand::findTicketsInInventory(), HealWoundCommand::findWoundPack(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveItems(), server::zone::objects::intangible::VehicleControlDeviceImplementation::generateObject(), server::zone::managers::creature::DnaManager::generateSample(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), server::zone::managers::resource::ResourceManagerImplementation::getAvailablePowerFromPlayer(), server::zone::managers::mission::MissionManagerImplementation::getBountyHunterMission(), server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::getBountyMissionObject(), server::zone::ZoneImplementation::getInRangeObjects(), server::zone::objects::player::sessions::EntertainingSessionImplementation::getInstrument(), server::zone::managers::player::PlayerManagerImplementation::getInsurableItems(), server::zone::managers::minigames::FishingManagerImplementation::getPole(), CombatManager::getPSGArmor(), server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::getRelevantMissionObject(), server::zone::managers::resource::ResourceManagerImplementation::givePlayerResource(), server::zone::managers::player::PlayerManagerImplementation::handleAddItemToTradeWindow(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAccept(), server::zone::managers::mission::MissionManagerImplementation::handleMissionListRequest(), LootSchematicMenuComponent::handleObjectMenuSelect(), ArtCrateMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), WeaponObjectMenuComponent::handleObjectMenuSelect(), TangibleObjectMenuComponent::handleObjectMenuSelect(), CreatureHabitatMenuComponent::handleObjectMenuSelect(), ForceShrineMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::deed::pet::PetDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::InstrumentImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::tool::CraftingToolImplementation::handleObjectMenuSelect(), server::zone::objects::installation::factory::FactoryObjectImplementation::handleRemoveFactorySchem(), server::chat::ChatManagerImplementation::handleSocialInternalMessage(), server::zone::managers::player::PlayerManagerImplementation::handleVerifyTradeMessage(), server::zone::managers::visibility::VisibilityManager::increaseVisibility(), server::zone::objects::player::sessions::SlicingSessionImplementation::initalizeSlicingMenu(), TurretDataComponent::initializeTransientMembers(), server::zone::objects::creature::commands::QueueCommand::isWearingArmor(), GroupManager::joinGroup(), JtlShipListResponse::JtlShipListResponse(), server::zone::managers::player::PlayerManagerImplementation::kickUser(), server::zone::managers::visibility::VisibilityManager::login(), server::zone::managers::player::PlayerManagerImplementation::lootAll(), server::zone::managers::minigames::FishingManagerImplementation::loseBait(), server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction(), TurretZoneComponent::notifyPositionUpdate(), server::zone::managers::mission::MissionManagerImplementation::populateMissionList(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::randomizeVendorLooks(), server::zone::managers::director::DirectorManager::readScreenPlayData(), StructureManager::redeedStructure(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::removeIngredient(), server::zone::managers::mission::MissionManagerImplementation::removeMission(), server::zone::managers::resource::ResourceManagerImplementation::removePowerFromPlayer(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), server::zone::managers::auction::AuctionManagerImplementation::retrieveItem(), JunkDealerSellListSuiCallback::run(), EmptyHopperCallback::run(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::selectConversationOption(), AiStateComponent::selectWeapon(), server::zone::objects::installation::factory::FactoryObjectImplementation::sendInsertManuSui(), server::zone::managers::gcw::GCWManagerImplementation::sendSelectDeedToDonate(), CampTerminalMenuComponent::showCampStatus(), server::zone::objects::resource::ResourceContainerImplementation::split(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::startImageDesign(), server::zone::managers::city::CityManagerImplementation::updateCityVoting(), server::zone::objects::player::sessions::EntertainingSessionImplementation::updateEntertainerMissionStatus(), ImageDesignManager::updateHairObject(), server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::updateMissionStatus(), DataTransformCallback::updatePosition(), DataTransformWithParentCallback::updatePosition(), server::zone::managers::skill::SkillModManager::verifyWearableSkillMods(), and server::zone::managers::director::DirectorManager::writeScreenPlayData().
Reference< SceneObject * > SceneObject::getSlottedObject (int idx)
Definition at line 1656 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getSlottedObject(), and RPC_GETSLOTTEDOBJECT__INT_.
void SceneObject::getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > & objects)
Fills the specified vector with the containment objects of this object
Precondition
{ this obejct is locked }
Postcondition
{ this object is locked, objects is a vector map with the contained objects and their occupied slots }
Parameters
objects the vector map that will contain the objects and their occupied slots
Definition at line 887 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getSlottedObjects().
Referenced by ContainerComponent::canAddObject(), ContainerComponent::removeObject(), and ContainerComponent::transferObject().
VectorMap< String, ManagedReference< SceneObject * > > * SceneObject::getSlottedObjects ()
Definition at line 1620 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::getSlottedObjects().
int SceneObject::getSlottedObjectsSize ()
Definition at line 1725 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getSlottedObjectsSize(), and RPC_GETSLOTTEDOBJECTSSIZE__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::getInsurableItems(), server::zone::objects::creature::commands::QueueCommand::isWearingArmor(), and server::zone::managers::skill::SkillModManager::verifyWearableSkillMods().
float SceneObject::getSpecialDirectionAngle ()
Definition at line 1977 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getSpecialDirectionAngle(), and RPC_GETSPECIALDIRECTIONANGLE__.
Referenced by LightUpdateTransformMessage::LightUpdateTransformMessage(), LightUpdateTransformWithParentMessage::LightUpdateTransformWithParentMessage(), UpdateTransformMessage::UpdateTransformMessage(), and UpdateTransformWithParentMessage::UpdateTransformWithParentMessage().
Matrix4 * SceneObject::getTransformForCollisionMatrix ()
Definition at line 3668 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::getTransformForCollisionMatrix().
Referenced by CollisionManager::getTransformMatrix().
Vector3 SceneObject::getWorldCoordinate (float distance, float angleDegrees)
Definition at line 1328 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::getWorldCoordinate().
Referenced by server::zone::objects::mission::bountyhunter::events::CallArakydTask::getLandingCoordinates(), server::zone::managers::mission::MissionManagerImplementation::getRandomBountyTargetPosition(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission().
Vector3 SceneObject::getWorldPosition () virtual
Definition at line 1376 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getWorldPosition().
Referenced by CollisionManager::checkLineOfSight(), CollisionManager::checkMovementCollision(), CollisionManager::checkShipCollision(), server::zone::managers::player::PlayerManagerImplementation::disseminateExperience(), NpcConversationStartCommand::doQueueCommand(), FindPlayerCommand::doQueueCommand(), DragIncapacitatedPlayerCommand::drag(), DragIncapacitatedPlayerCommand::getCoordinate(), FleeStateComponent::getFleeLocation(), server::zone::managers::planet::PlanetManagerImplementation::getNearestPlanetTravelPoint(), server::zone::objects::area::SpawnAreaImplementation::getRandomPosition(), server::zone::objects::mission::BountyMissionObjectiveImplementation::getTargetPosition(), ZoneContainerComponent::insertActiveArea(), server::zone::managers::planet::PlanetManagerImplementation::isInObjectsNoBuildZone(), PatrolPoint::isInRange(), server::zone::objects::mission::bountyhunter::events::CallArakydTask::noInterferingObjects(), server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::run(), and PlanetTravelPoint::setShuttle().
float SceneObject::getWorldPositionX () virtual
Definition at line 1337 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getWorldPositionX(), and RPC_GETWORLDPOSITIONX__.
Referenced by CombatManager::broadcastCombatSpam(), server::zone::managers::visibility::VisibilityManager::calculateVisibilityIncrease(), server::zone::managers::player::PlayerManagerImplementation::disseminateExperience(), CombatManager::doAreaCombatAction(), server::zone::objects::scene::SceneObjectImplementation::getDistanceTo(), server::zone::objects::creature::conversation::screenhandlers::TrainerInfoScreenHandler::handleScreen(), server::chat::ChatManagerImplementation::handleSocialInternalMessage(), IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage(), ShuttleZoneComponent::notifyInsertToZone(), InstallMissionTerminalSuiCallback::run(), RecruitSkillTrainerSuiCallback::run(), and ZoneContainerComponent::transferObject().
float SceneObject::getWorldPositionY () virtual
Definition at line 1350 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getWorldPositionY(), and RPC_GETWORLDPOSITIONY__.
Referenced by CombatManager::broadcastCombatSpam(), server::zone::managers::visibility::VisibilityManager::calculateVisibilityIncrease(), server::zone::managers::player::PlayerManagerImplementation::disseminateExperience(), CombatManager::doAreaCombatAction(), server::zone::objects::scene::SceneObjectImplementation::getDistanceTo(), server::zone::objects::creature::conversation::screenhandlers::TrainerInfoScreenHandler::handleScreen(), IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage(), ShuttleZoneComponent::notifyInsertToZone(), InstallMissionTerminalSuiCallback::run(), and RecruitSkillTrainerSuiCallback::run().
float SceneObject::getWorldPositionZ () virtual
Definition at line 1363 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getWorldPositionZ(), and RPC_GETWORLDPOSITIONZ__.
Referenced by DragIncapacitatedPlayerCommand::getCoordinate(), ShuttleZoneComponent::notifyInsertToZone(), InstallMissionTerminalSuiCallback::run(), and RecruitSkillTrainerSuiCallback::run().
Zone * SceneObject::getZone ()
Definition at line 1280 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getZone(), and RPC_GETZONE__.
Referenced by server::zone::objects::mission::ReconMissionObjectiveImplementation::activate(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::activate(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::activateWithResult(), PlayersNearYouMessage::addFoundPlayer(), server::zone::managers::auction::AuctionsMapImplementation::addItem(), server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::zone::objects::player::sessions::FindSessionImplementation::addWaypoint(), CombatManager::broadcastCombatSpam(), server::zone::managers::visibility::VisibilityManager::calculateVisibilityIncrease(), server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::canSpawnTargetAt(), BurstRunCommand::checkBurstRun(), server::zone::managers::creature::LairObserverImplementation::checkForNewSpawns(), CollisionManager::checkLineOfSight(), server::zone::managers::minigames::FishingManagerImplementation::checkLocation(), MaskscentCommand::checkMaskScent(), RetreatCommand::checkRetreat(), server::zone::managers::auction::AuctionManagerImplementation::checkRetrieve(), CollisionManager::checkShipCollision(), server::zone::managers::minigames::FishingManagerImplementation::checkUpdateMarker(), CmdStartScene::CmdStartScene(), server::zone::objects::tangible::firework::FireworkObjectImplementation::completeLaunch(), server::zone::managers::city::CityManagerImplementation::createCity(), GroupManager::createGroup(), server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), ShuttleInstallationZoneComponent::destroyObjectFromWorld(), ZoneComponent::destroyObjectFromWorld(), server::zone::managers::vendor::VendorManager::destroyVendor(), CampTerminalMenuComponent::disbandCamp(), server::zone::managers::player::PlayerManagerImplementation::disseminateExperience(), server::zone::managers::creature::LairObserverImplementation::doAggro(), CombatManager::doAreaCombatAction(), FormupCommand::doFormUp(), GmReviveCommand::doQueueCommand(), EjectCommand::doQueueCommand(), TeleportCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), ConcealCommand::doQueueCommand(), KillCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), ProneCommand::doQueueCommand(), DismountCommand::doQueueCommand(), GetAttributesBatchCommand::doQueueCommand(), HarvesterGetResourceDataCommand::doQueueCommand(), PlaceStructureCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), TeleportTargetCommand::doQueueCommand(), CreateCreatureCommand::doQueueCommand(), GcwStatusCommand::doQueueCommand(), HarvestCorpseCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), GiveItemCommand::doQueueCommand(), PurchaseTicketCommand::doQueueCommand(), FindFriendCommand::doQueueCommand(), WaypointCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), RetreatCommand::doQueueCommand(), DragIncapacitatedPlayerCommand::doQueueCommand(), RallyCommand::doRally(), server::zone::objects::player::PlayerObjectImplementation::doRecovery(), SteadyaimCommand::doSteadyAim(), server::zone::managers::player::PlayerManagerImplementation::ejectPlayerFromBuilding(), PowerRegulatorMenuComponent::fillObjectMenuResponse(), TurretControlMenuComponent::fillObjectMenuResponse(), OverrideTerminalMenuComponent::fillObjectMenuResponse(), MinefieldMenuComponent::fillObjectMenuResponse(), SecurityTerminalMenuComponent::fillObjectMenuResponse(), UplinkTerminalMenuComponent::fillObjectMenuResponse(), BankTerminalMenuComponent::fillObjectMenuResponse(), HQMenuComponent::fillObjectMenuResponse(), AiStateComponent::findNextPosition(), server::zone::objects::player::sessions::FindSessionImplementation::findPlanetaryObject(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::findTarget(), server::zone::managers::minigames::ForageManagerImplementation::finishForaging(), server::zone::managers::minigames::FishingManagerImplementation::fishingProceed(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveResource(), server::zone::objects::intangible::ShipControlDeviceImplementation::generateObject(), DragIncapacitatedPlayerCommand::getCoordinate(), server::zone::managers::auction::AuctionManagerImplementation::getData(), FleeStateComponent::getFleeLocation(), server::zone::managers::director::DirectorManager::getGCWDiscount(), server::zone::managers::player::PlayerManagerImplementation::getInRangeOwnedStructure(), StructureManager::getInRangeParkingGarage(), server::zone::managers::player::PlayerManagerImplementation::getInRangeStructureWithAdminRights(), server::zone::objects::mission::bountyhunter::events::CallArakydTask::getLandingCoordinates(), server::zone::managers::player::PlayerManagerImplementation::getNearbyCraftingStation(), server::zone::managers::mission::MissionManagerImplementation::getRandomBountyTargetPosition(), server::zone::managers::mission::MissionManagerImplementation::getRandomLairSpawn(), MissionTargetMap::getRandomTarget(), server::zone::managers::director::DirectorManager::getSpawnPoint(), server::zone::objects::mission::BountyMissionObjectiveImplementation::getTargetZoneName(), server::zone::managers::director::DirectorManager::getTerrainHeight(), server::zone::managers::auction::AuctionManagerImplementation::getVendorUID(), server::zone::ZoneServerAdapter::getZone(), server::zone::objects::region::CityRegionAdapter::getZone(), server::zone::objects::scene::SceneObjectAdapter::getZone(), DotPackCommand::handleArea(), CurePackCommand::handleArea(), HealDamageCommand::handleArea(), server::zone::managers::vendor::VendorManager::handleDisplayStatus(), InstallationObjectMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), ArtCrateMenuComponent::handleObjectMenuSelect(), FireworkMenuComponent::handleObjectMenuSelect(), CreatureHabitatMenuComponent::handleObjectMenuSelect(), FireworkShowMenuComponent::handleObjectMenuSelect(), DiceMenuComponent::handleObjectMenuSelect(), PowerRegulatorMenuComponent::handleObjectMenuSelect(), TurretControlMenuComponent::handleObjectMenuSelect(), OverrideTerminalMenuComponent::handleObjectMenuSelect(), MinefieldMenuComponent::handleObjectMenuSelect(), SecurityTerminalMenuComponent::handleObjectMenuSelect(), UplinkTerminalMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), HQMenuComponent::handleObjectMenuSelect(), server::chat::ChatManagerImplementation::handlePlanetChat(), server::zone::managers::vendor::VendorManager::handleRegisterVendorCallback(), server::zone::managers::vendor::VendorManager::handleRenameVendor(), server::zone::objects::creature::conversation::screenhandlers::TrainerInfoScreenHandler::handleScreen(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSlice(), server::zone::objects::player::sessions::SlicingSessionImplementation::handleSliceFailed(), server::chat::ChatManagerImplementation::handleSocialInternalMessage(), server::zone::managers::vendor::VendorManager::handleUnregisterVendor(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), HarvesterObjectMessage7::HarvesterObjectMessage7(), ResourceSpawner::harvestResource(), server::zone::managers::creature::LairObserverImplementation::healLair(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::init(), ZoneContainerComponent::insertActiveArea(), InstallationObjectMessage7::InstallationObjectMessage7(), server::zone::objects::creature::VehicleObjectImplementation::isAttackableBy(), server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy(), GroupManager::joinGroup(), StructureManager::loadPlayerStructures(), server::zone::managers::creature::CreatureManagerImplementation::milk(), server::zone::managers::creature::LairObserverImplementation::notifyDestruction(), PlayerZoneComponent::notifySelfPositionUpdate(), PlaceGCWBaseComponent::notifyStructurePlaced(), SpawnStateComponent::onEnter(), PlaceCityHallComponent::placeStructure(), PlaceGCWBaseComponent::placeStructure(), PlaceStructureComponent::placeStructure(), StructureManager::placeStructure(), StructureManager::placeStructureFromDeed(), server::zone::objects::player::sessions::PlaceStructureSessionImplementation::PlaceStructureSessionImplementation(), server::zone::managers::mission::MissionManagerImplementation::randomGenericDeliverMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission(), server::zone::managers::city::CityManagerImplementation::registerCity(), server::zone::objects::player::PlayerObjectImplementation::reload(), FindLostItemsSuiCallback::run(), HQDefenseStatusSuiCallback::run(), StructurePayMaintenanceSuiCallback::run(), HQSendResetVerificationSuiCallback::run(), JamUplinkSuiCallback::run(), SelectTurretDonationSuiCallback::run(), InstallMissionTerminalSuiCallback::run(), RemoveDefenseSuiCallback::run(), RecruitSkillTrainerSuiCallback::run(), OverrideTerminalSuiCallback::run(), PowerRegulatorSuiCallback::run(), DonateDefenseSuiCallback::run(), TurretControlSuiCallback::run(), server::zone::objects::creature::events::DespawnCreatureOnPlayerDissappear::run(), IsVendorOwnerMessageCallback::run(), SelectCharacterCallback::run(), ShipUpdateTransformCallback::run(), NewbieTutorialResponseCallback::run(), server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::run(), server::zone::managers::creature::CreatureManagerImplementation::sample(), server::zone::managers::player::PlayerManagerImplementation::sendActivateCloneRequest(), server::zone::managers::city::CityManagerImplementation::sendChangeCityName(), server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner(), ResourceSpawner::sendResourceListForSurvey(), ResourceSpawner::sendSample(), ResourceSpawner::sendSampleResults(), ResourceSpawner::sendSurvey(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::spawnLair(), server::zone::objects::intangible::VehicleControlDeviceImplementation::spawnObject(), server::zone::objects::tangible::InstrumentImplementation::spawnOutside(), CombatManager::startCombat(), server::zone::managers::minigames::FishingManagerImplementation::startFishing(), server::zone::managers::minigames::ForageManagerImplementation::startForaging(), server::zone::managers::gcw::GCWManagerImplementation::startVulnerability(), server::zone::managers::minigames::FishingManagerImplementation::stopFishing(), server::zone::objects::intangible::ShipControlDeviceImplementation::storeObject(), server::zone::managers::minigames::FishingManagerImplementation::success(), ZoneComponent::switchZone(), ZoneComponent::teleport(), ZoneContainerComponent::transferObject(), server::zone::managers::city::CityManagerImplementation::unregisterCity(), AiStateComponent::updateCurrentPosition(), server::zone::managers::minigames::FishingManagerImplementation::updateMarker(), DataTransformCallback::updatePosition(), DataTransformWithParentCallback::updatePosition(), server::zone::managers::player::PlayerManagerImplementation::updateSwimmingState(), server::zone::managers::auction::AuctionsMapImplementation::updateUID(), ZoneComponent::updateZone(), and ZoneComponent::updateZoneWithParent().
ZoneComponent * SceneObject::getZoneComponent ()
Definition at line 2268 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::getZoneComponent().
ZoneProcessServer * SceneObject::getZoneProcessServer ()
Definition at line 3281 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::getZoneProcessServer().
Referenced by ForageAreaCollection::ForageAreaCollection(), LairMenuComponent::handleObjectMenuSelect(), ShellfishHarvesterMenuComponent::handleObjectMenuSelect(), GamblingSlotSuiCallback::run(), and GamblingRouletteSuiCallback::run().
ZoneServer * SceneObject::getZoneServer ()
Definition at line 2099 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::getZoneServer(), and RPC_GETZONESERVER__.
Referenced by server::zone::managers::visibility::VisibilityManager::addPlayerToBountyList(), server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership(), server::zone::managers::skill::SkillManager::awardSkill(), server::zone::managers::gcw::GCWManagerImplementation::awardSlicingXP(), server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::BountyHunterTargetTask(), PlayerContainerComponent::canAddObject(), CharacterSheetResponseMessage::CharacterSheetResponseMessage(), ImageDesignManager::createHairObject(), server::zone::managers::minigames::GamblingManagerImplementation::createPayoutWindow(), server::zone::managers::minigames::GamblingManagerImplementation::createRouletteWindow(), server::zone::managers::minigames::GamblingManagerImplementation::createSlotWindow(), server::zone::managers::minigames::FishingManagerImplementation::createSplash(), ResourceCommand::despawnResource(), CityHallZoneComponent::destroyObjectFromWorld(), SynchronizedUiStopListeningCommand::doQueueCommand(), TauntCommand::doQueueCommand(), AdjustLotCountCommand::doQueueCommand(), CitypardonCommand::doQueueCommand(), GrantZoningRightsCommand::doQueueCommand(), SynchronizedUiListenCommand::doQueueCommand(), UnfreezePlayerCommand::doQueueCommand(), CreateMissionElementCommand::doQueueCommand(), FreezePlayerCommand::doQueueCommand(), InsureCommand::doQueueCommand(), ListGuildsCommand::doQueueCommand(), RequestDraftSlotsBatchCommand::doQueueCommand(), RequestResourceWeightsBatchCommand::doQueueCommand(), ResourceContainerTransferCommand::doQueueCommand(), RotateFurnitureCommand::doQueueCommand(), ApplyPowerupCommand::doQueueCommand(), CitybanCommand::doQueueCommand(), HaveconsentCommand::doQueueCommand(), CreateCreatureCommand::doQueueCommand(), GetAccountInfoCommand::doQueueCommand(), ObjectCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), GenerateCraftedItemCommand::doQueueCommand(), RequestCraftingSessionCommand::doQueueCommand(), StartMusicCommand::doQueueCommand(), ResourceCommand::dumpResources(), server::zone::objects::tangible::terminal::characterbuilder::CharacterBuilderTerminalImplementation::enhanceCharacter(), MarketCommand::executeCommand(), ServerInfoCommand::executeCommand(), CityReportCommand::executeCommand(), PlayerInfoCommand::executeCommand(), MinefieldMenuComponent::fillObjectMenuResponse(), AiStateComponent::findNextPosition(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveItems(), server::zone::managers::minigames::ForageManagerImplementation::forageGiveResource(), server::zone::managers::minigames::FishingManagerImplementation::freeBait(), FriendsListMessage::FriendsListMessage(), server::zone::managers::creature::DnaManager::generateSample(), BountyHunterDroidMenuComponent::getBountyHunterMission(), server::zone::objects::player::sessions::EntertainingSessionImplementation::getInstrument(), server::zone::objects::mission::bountyhunter::events::FindTargetTask::getTargetLevel(), server::zone::managers::director::DirectorManager::giveControlDevice(), server::zone::managers::director::DirectorManager::giveItem(), server::zone::managers::sui::SuiManager::handleCharacterBuilderSelectItem(), server::zone::objects::mission::BountyMissionObjectiveImplementation::handleNpcTargetReceivesDamage(), CityManagementMenuComponent::handleObjectMenuSelect(), CityVotingMenuComponent::handleObjectMenuSelect(), ThrowGrenadeMenuComponent::handleObjectMenuSelect(), InsuranceTerminalMenuComponent::handleObjectMenuSelect(), TrapMenuComponent::handleObjectMenuSelect(), CloningTerminalMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), GogglesObjectMenuComponent::handleObjectMenuSelect(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), ArmorObjectMenuComponent::handleObjectMenuSelect(), BountyHunterDroidMenuComponent::handleObjectMenuSelect(), ForceShrineMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), server::zone::objects::tangible::tool::smuggler::PrecisionLaserKnifeImplementation::handleObjectMenuSelect(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::handleObjectMenuSelect(), HarvesterObjectMessage7::HarvesterObjectMessage7(), ResourceCommand::healthCheck(), server::zone::objects::creature::CreatureObjectImplementation::isInBountyMission(), IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage(), ResourceCommand::listResourceInfo(), ResourceCommand::listResources(), server::zone::managers::creature::LairObserverImplementation::notifyDestruction(), PlayerContainerComponent::notifyObjectInserted(), PlayerContainerComponent::notifyObjectRemoved(), PlaceDecorationComponent::placeStructure(), BountyHunterDroidMenuComponent::playerOwnsTheDroid(), server::zone::managers::vendor::VendorManager::promptDestroyVendor(), server::zone::managers::vendor::VendorManager::promptRenameVendorTo(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericBountyMission(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), server::zone::managers::visibility::VisibilityManager::removePlayerFromBountyList(), server::zone::objects::tangible::TangibleObjectImplementation::repair(), InsuranceAllConfirmSuiCallback::run(), InsuranceMenuSuiCallback::run(), InsertPowerSuiCallback::run(), JunkDealerSellListSuiCallback::run(), server::zone::managers::player::PlayerManagerImplementation::sendActivateCloneRequest(), server::zone::managers::sui::SuiManager::sendConfirmSui(), server::zone::objects::player::sessions::DestroyStructureSessionImplementation::sendDestroyCode(), server::zone::managers::sui::SuiManager::sendInputBox(), server::zone::managers::sui::SuiManager::sendKeypadSui(), server::zone::managers::sui::SuiManager::sendListBox(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailCondemned(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailDecay(), server::zone::objects::structure::events::StructureMaintenanceTask::sendMailMaintenanceWithdrawnFromBank(), server::zone::managers::sui::SuiManager::sendMessageBox(), server::zone::managers::vendor::VendorManager::sendRegisterVendorTo(), StructurePermissionList::sendTo(), server::zone::managers::auction::AuctionsMapImplementation::sendVendorUpdateMail(), server::zone::ZoneClientSessionImplementation::setPlayer(), server::zone::managers::minigames::ForageManagerImplementation::startForaging(), server::zone::managers::minigames::FishingManagerImplementation::success(), server::zone::managers::skill::SkillManager::surrenderSkill(), ZoneComponent::switchZone(), ZoneComponent::teleport(), server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus(), server::zone::objects::mission::DeliverMissionObjectiveImplementation::updateMissionStatus(), and server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::updatePosition().
int SceneObject::handleObjectMenuSelect (CreatureObject * player, byte selectedID)
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player CreatureObject that selected the option
selectedID selected menu id
Returns
0 if successfull
Definition at line 1091 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::handleObjectMenuSelect(), and RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_.
bool SceneObject::hasActiveArea (ActiveArea * area)
Definition at line 1199 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::hasActiveArea(), and RPC_HASACTIVEAREA__ACTIVEAREA_.
Referenced by ZoneContainerComponent::insertActiveArea(), ZoneContainerComponent::removeActiveArea(), and server::zone::ZoneImplementation::updateActiveAreas().
bool SceneObject::hasActiveArea (unsigned long long objectid)
Definition at line 1213 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::hasActiveArea(), and RPC_HASACTIVEAREA__LONG_.
bool SceneObject::hasArrangementDescriptor (const String & descr)
Definition at line 1606 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::hasArrangementDescriptor(), and RPC_HASARRANGEMENTDESCRIPTOR__STRING_.
bool SceneObject::hasFullContainerObjects ()
Definition at line 1738 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::hasFullContainerObjects(), and RPC_HASFULLCONTAINEROBJECTS__.
Referenced by EmptyHopperCallback::run().
bool SceneObject::hasObjectInContainer (unsigned long long objectID)
Definition at line 1787 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::hasObjectInContainer(), and RPC_HASOBJECTINCONTAINER__LONG_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkTradeItems(), and server::zone::objects::building::BuildingObjectImplementation::destroyObjectFromDatabase().
bool SceneObject::hasObjectInSlottedContainer (SceneObject * object)
Definition at line 1801 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::hasObjectInSlottedContainer(), and RPC_HASOBJECTINSLOTTEDCONTAINER__SCENEOBJECT_.
bool SceneObject::hasSlotDescriptor (const String & descr)
Definition at line 1592 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::hasSlotDescriptor(), and RPC_HASSLOTDESCRIPTOR__STRING_.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::createCreatureChildrenObjects().
void SceneObject::incrementMovementCounter ()
Definition at line 3367 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::incrementMovementCounter(), and RPC_INCREMENTMOVEMENTCOUNTER__.
Referenced by AiStateComponent::broadcastNextPositionUpdate(), and DragIncapacitatedPlayerCommand::drag().
void SceneObject::info (const String & msg, bool forced = false)
Logs an info message
Precondition
{}
Postcondition
{ message has been printed to console or file }
Parameters
msg message to print
forced if true, always prints the message to console
Definition at line 129 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::info(), and RPC_INFO__STRING_BOOL_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackFirstTest(), TransferItemCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), FindObjectCommand::doQueueCommand(), TransferItemArmorCommand::doQueueCommand(), TransferItemWeaponCommand::doQueueCommand(), TransferItemMiscCommand::doQueueCommand(), RequestSetStatMigrationDataCommand::doQueueCommand(), CombatManager::freeDuelList(), GroupManager::joinGroup(), GroupManager::kickFromGroup(), GroupManager::leaveGroup(), CombatManager::requestDuel(), CombatManager::requestEndDuel(), JunkDealerSellListSuiCallback::run(), server::zone::managers::player::PlayerManagerImplementation::startListen(), server::zone::managers::player::PlayerManagerImplementation::startWatch(), server::zone::managers::player::PlayerManagerImplementation::stopListen(), server::zone::managers::player::PlayerManagerImplementation::stopWatch(), server::zone::objects::area::LairSpawnAreaImplementation::trySpawnLair(), server::zone::managers::director::DirectorManager::updateCellPermission(), server::zone::managers::director::DirectorManager::updateCellPermissionGroup(), and server::zone::managers::player::PlayerManagerImplementation::updateSwimmingState().
void SceneObject::initializeChildObject (SceneObject * controllerObject)
This method initializes "this" object as if it were a "childObject" of the controller object that is passed as an argument to the method. NOTE: The controllerObject is not necessarily the "parent" of the child object. The childObject just happens to be specified in the controllerObject's childObjects vector.
Parameters
controllerObject The object that has this object specified as a "childObject".
Definition at line 3686 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::initializeChildObject(), and RPC_INITIALIZECHILDOBJECT__SCENEOBJECT_.
void SceneObject::initializePrivateData ()
Definition at line 55 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::initializePrivateData(), and RPC_INITIALIZEPRIVATEDATA__.
void SceneObject::initializeTransientMembers ()
Initializes the transient members of SceneObject, must call the inherited object method first.
Precondition
{transient members are not initialized }
Postcondition
{ transient members are initialized }
Definition at line 103 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
int SceneObject::inRangeObjects (unsigned int gameObjectType, float range)
Returns number of specified game objects in range
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
number of objects in range
Definition at line 158 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::inRangeObjects(), and RPC_INRANGEOBJECTS__INT_FLOAT_.
bool SceneObject::isActiveArea ()
Definition at line 2392 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isActiveArea(), and RPC_ISACTIVEAREA__.
Referenced by ZoneComponent::destroyObjectFromWorld(), ZoneContainerComponent::removeObject(), and ZoneContainerComponent::transferObject().
bool SceneObject::isActorObject ()
Definition at line 3539 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isActorObject(), and RPC_ISACTOROBJECT__.
bool SceneObject::isAiAgent ()
Definition at line 2431 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isAiAgent(), and RPC_ISAIAGENT__.
Referenced by server::zone::managers::objectcontroller::ObjectControllerImplementation::activateCommand(), CombatManager::applySpecialAttackCost(), CollisionManager::checkLineOfSight(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::decay(), server::zone::managers::creature::LairObserverImplementation::doAggro(), MediumDiseaseCommand::doQueueCommand(), MediumPoisonCommand::doQueueCommand(), MildDiseaseCommand::doQueueCommand(), MildPoisonCommand::doQueueCommand(), StrongPoisonCommand::doQueueCommand(), StrongDiseaseCommand::doQueueCommand(), CreatureAreaAttackCommand::doQueueCommand(), CreatureAreaBleedingCommand::doQueueCommand(), CreatureAreaComboCommand::doQueueCommand(), CreatureAreaDiseaseCommand::doQueueCommand(), CreatureAreaKnockdownCommand::doQueueCommand(), CreatureAreaPoisonCommand::doQueueCommand(), IntimidationAttackCommand::doQueueCommand(), KnockdownAttackCommand::doQueueCommand(), DefaultAttackCommand::doQueueCommand(), PostureDownAttackCommand::doQueueCommand(), PostureUpAttackCommand::doQueueCommand(), BlindAttackCommand::doQueueCommand(), DizzyAttackCommand::doQueueCommand(), StunAttackCommand::doQueueCommand(), TransferForceCommand::doQueueCommand(), DrainForceCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), HealAllOther2Command::doQueueCommand(), HealAllOther1Command::doQueueCommand(), HealHealthWoundOther1Command::doQueueCommand(), HealHealthWoundOther2Command::doQueueCommand(), HealMindWoundOther1Command::doQueueCommand(), HealMindWoundOther2Command::doQueueCommand(), HealActionWoundOther1Command::doQueueCommand(), HealActionWoundOther2Command::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), TotalHealOtherCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), CombatManager::getArmorPiercing(), CombatManager::getArmorReduction(), CombatManager::getAttackerAccuracyBonus(), server::zone::objects::creature::AiAgentImplementation::isAttackableBy(), server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy(), server::zone::managers::creature::LairObserverImplementation::notifyDestruction(), AiNPCComponent::notifyPositionUpdate(), AiCreatureComponent::notifyPositionUpdate(), server::zone::managers::creature::CreatureManagerImplementation::placeCreature(), server::zone::objects::building::BuildingObjectImplementation::spawnChildCreature(), server::zone::objects::building::BuildingObjectImplementation::spawnChildCreaturesFromTemplate(), server::zone::managers::director::DirectorManager::spawnMobile(), and server::zone::managers::director::DirectorManager::spawnMobileRandom().
bool SceneObject::isArmorObject ()
Definition at line 2561 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isArmorObject(), and RPC_ISARMOROBJECT__.
Referenced by server::zone::managers::loot::LootManagerImplementation::addConditionDamage(), server::zone::managers::player::PlayerManagerImplementation::addInsurableItemsRecursive(), server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), PlayerContainerComponent::canAddObject(), TangibleObjectMenuComponent::fillObjectMenuResponse(), CombatManager::getArmorPiercing(), server::zone::managers::player::PlayerManagerImplementation::getInsurableItems(), server::zone::objects::player::sessions::SlicingSessionImplementation::getPrefix(), server::zone::objects::creature::commands::QueueCommand::isWearingArmor(), PlayerContainerComponent::notifyObjectInserted(), PlayerContainerComponent::notifyObjectRemoved(), and InsuranceMenuSuiCallback::run().
bool SceneObject::isASubChildOf (SceneObject * object)
Evaluates if this object is a child of the specified SceneObject
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns true if this object is a child of object
Definition at line 2139 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isASubChildOf(), and RPC_ISASUBCHILDOF__SCENEOBJECT_.
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::addIngredient(), VendorMenuComponent::fillObjectMenuResponse(), ThrowGrenadeMenuComponent::handleObjectMenuSelect(), FireHeavyWeaponMenuComponent::handleObjectMenuSelect(), WearableObjectMenuComponent::handleObjectMenuSelect(), LootSchematicMenuComponent::handleObjectMenuSelect(), TrapMenuComponent::handleObjectMenuSelect(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), SkillBuffObjectMenuComponent::handleObjectMenuSelect(), LightsaberObjectMenuComponent::handleObjectMenuSelect(), ShellfishHarvesterMenuComponent::handleObjectMenuSelect(), GogglesObjectMenuComponent::handleObjectMenuSelect(), FireworkMenuComponent::handleObjectMenuSelect(), ArtCrateMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), FireworkShowMenuComponent::handleObjectMenuSelect(), DiceMenuComponent::handleObjectMenuSelect(), HolocronMenuComponent::handleObjectMenuSelect(), CityDecorationMenuComponent::isInInventory(), and StructureManager::placeStructureFromDeed().
bool SceneObject::isAttachment ()
Definition at line 3029 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isAttachment(), and RPC_ISATTACHMENT__.
bool SceneObject::isAuctionObject ()
Definition at line 2964 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isAuctionObject(), and RPC_ISAUCTIONOBJECT__.
bool SceneObject::isBazaarTerminal ()
Definition at line 2717 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isBazaarTerminal(), and RPC_ISBAZAARTERMINAL__.
Referenced by server::zone::managers::auction::AuctionsMapImplementation::addItem(), server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), server::zone::managers::auction::AuctionManagerImplementation::checkRetrieve(), server::zone::managers::auction::AuctionManagerImplementation::checkSaleItem(), server::zone::managers::auction::AuctionManagerImplementation::createVendorItem(), server::zone::managers::auction::AuctionsMapImplementation::deleteItem(), server::zone::managers::auction::AuctionsMapImplementation::deleteTerminalItems(), server::zone::managers::auction::AuctionManagerImplementation::fillAuctionQueryHeadersResponseMessage(), server::zone::managers::auction::AuctionManagerImplementation::getAuctionData(), IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage(), server::zone::objects::region::CityRegionImplementation::notifyEnter(), server::zone::objects::region::CityRegionImplementation::notifyExit(), AuctionTerminalMap::updateTerminalSearch(), and server::zone::managers::auction::AuctionsMapImplementation::updateUID().
bool SceneObject::isBuildingDeed ()
Definition at line 2873 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isBuildingDeed(), and RPC_ISBUILDINGDEED__.
bool SceneObject::isBuildingObject ()
Definition at line 2483 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isBuildingObject(), and RPC_ISBUILDINGOBJECT__.
Referenced by StructureContainerComponent::checkContainerPermission(), StructureManager::declareResidence(), PermissionListModifyCommand::doQueueCommand(), TransferstructureCommand::doQueueCommand(), TransferstructureCommand::doTransferStructure(), server::zone::objects::tangible::sign::SignObjectImplementation::initializeChildObject(), StructureManager::moveFirstItemTo(), server::zone::objects::region::CityRegionImplementation::notifyEnter(), server::zone::objects::region::CityRegionImplementation::notifyExit(), PlaceCityHallComponent::notifyStructurePlaced(), StructureManager::placeStructure(), StructureManager::reportStructureStatus(), StructurePayUncondemnMaintenanceSuiCallback::run(), and server::zone::objects::structure::events::StructureMaintenanceTask::sendMailDecay().
bool SceneObject::isCamoKit ()
Definition at line 3016 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isCamoKit(), and RPC_ISCAMOKIT__.
bool SceneObject::isCampKit ()
Definition at line 3068 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isCampKit(), and RPC_ISCAMPKIT__.
Referenced by CampKitMenuComponent::fillObjectMenuResponse().
bool SceneObject::isCampStructure ()
Definition at line 3081 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isCampStructure(), and RPC_ISCAMPSTRUCTURE__.
Referenced by CampKitMenuComponent::handleObjectMenuSelect().
bool SceneObject::isCellObject ()
Definition at line 2626 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isCellObject(), and RPC_ISCELLOBJECT__.
Referenced by server::zone::objects::creature::LuaCreatureObject::getInCellNumber(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), PatrolPoint::setCell(), server::zone::managers::director::DirectorManager::updateCellPermission(), server::zone::managers::director::DirectorManager::updateCellPermissionGroup(), and WorldCoordinates::WorldCoordinates().
bool SceneObject::isCityTerminal ()
Definition at line 2782 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isCityTerminal(), and RPC_ISCITYTERMINAL__.
bool SceneObject::isCityVoteTerminal ()
Definition at line 2795 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isCityVoteTerminal(), and RPC_ISCITYVOTETERMINAL__.
bool SceneObject::isCloningBuildingObject ()
Definition at line 2496 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isCloningBuildingObject(), and RPC_ISCLONINGBUILDINGOBJECT__.
bool SceneObject::isComponent ()
Definition at line 2678 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isComponent(), and RPC_ISCOMPONENT__.
Referenced by server::zone::managers::crafting::labratories::GeneticLabratory::setInitialCraftingValues().
bool SceneObject::isContainerFull ()
Definition at line 2353 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isContainerFull(), and RPC_ISCONTAINERFULL__.
bool SceneObject::isContainerObject ()
Definition at line 3448 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isContainerObject(), and RPC_ISCONTAINEROBJECT__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::addInsurableItemsRecursive(), server::zone::objects::cell::CellObjectImplementation::canAddObject(), server::zone::objects::tangible::ContainerImplementation::canAddObject(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::canInventoryItemBeSoldAsJunk(), PlaceableLootContainerComponent::checkContainerPermission(), TangibleObjectMenuComponent::fillObjectMenuResponse(), and server::zone::objects::player::sessions::SlicingSessionImplementation::getPrefix().
bool SceneObject::isControlDevice ()
Definition at line 3500 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isControlDevice(), and RPC_ISCONTROLDEVICE__.
bool SceneObject::isCraftingStation ()
Definition at line 2925 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isCraftingStation(), and RPC_ISCRAFTINGSTATION__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::getNearbyCraftingStation().
bool SceneObject::isCraftingTool ()
Definition at line 2912 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isCraftingTool(), and RPC_ISCRAFTINGTOOL__.
Referenced by server::zone::objects::tangible::tool::CraftingStationImplementation::findCraftingTool().
bool SceneObject::isCreatureHabitat ()
Definition at line 3055 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isCreatureHabitat(), and RPC_ISCREATUREHABITAT__.
Referenced by CreatureHabitatMenuComponent::fillObjectMenuResponse(), and CreatureHabitatMenuComponent::handleObjectMenuSelect().
bool SceneObject::isCreatureObject ()
Definition at line 2418 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isCreatureObject(), and RPC_ISCREATUREOBJECT__.
Referenced by CombatManager::attemptPeace(), CombatManager::broadcastCombatAction(), server::zone::objects::tangible::TangibleObjectImplementation::broadcastPvpStatusBitmask(), server::zone::objects::group::GroupObjectImplementation::calcGroupLevel(), server::zone::managers::visibility::VisibilityManager::calculateVisibilityIncrease(), CollisionManager::checkLineOfSight(), server::zone::managers::city::CityManagerImplementation::collectNonStructureMaintenance(), CombatManager::doAreaCombatAction(), server::zone::objects::creature::AiAgentImplementation::doAttack(), AiNPCComponent::doAwarenessCheck(), AiCreatureComponent::doAwarenessCheck(), ConcealCommand::doQueueCommand(), KillCommand::doQueueCommand(), AttackStateComponent::doRecovery(), CombatManager::doTargetCombatAction(), PlayerObjectMenuComponent::fillObjectMenuResponse(), VendorMenuComponent::fillObjectMenuResponse(), DotPackCommand::handleArea(), server::zone::objects::creature::CreatureObjectImplementation::isAttackableBy(), server::zone::objects::structure::StructureObjectImplementation::isOwnerOf(), AiStateComponent::isScared(), server::zone::managers::minigames::GamblingManagerImplementation::notify(), server::zone::objects::area::DynamicSpawnAreaImplementation::notifyEnter(), server::zone::objects::region::CityRegionImplementation::notifyEnter(), server::zone::objects::area::DynamicSpawnAreaImplementation::notifyExit(), server::zone::objects::region::CityRegionImplementation::notifyExit(), server::zone::objects::building::BuildingObjectImplementation::notifyInsert(), ShuttleZoneComponent::notifyInsertToZone(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToZone(), AiNPCComponent::notifyPositionUpdate(), AiCreatureComponent::notifyPositionUpdate(), server::zone::objects::creature::ai::AiActorImplementation::removeDefender(), server::zone::objects::creature::AiAgentImplementation::removeDefender(), server::zone::objects::cell::CellObjectImplementation::sendBaselinesTo(), server::zone::objects::installation::InstallationObjectImplementation::sendBaselinesTo(), server::zone::managers::sui::SuiManager::sendConfirmSui(), server::zone::managers::sui::SuiManager::sendInputBox(), server::zone::managers::sui::SuiManager::sendKeypadSui(), server::zone::managers::sui::SuiManager::sendListBox(), server::zone::managers::sui::SuiManager::sendMessageBox(), CombatManager::startCombat(), ZoneComponent::updateZone(), ZoneComponent::updateZoneWithParent(), and server::zone::managers::skill::SkillModManager::verifyStructureSkillMods().
bool SceneObject::isDecoration ()
Definition at line 2295 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isDecoration(), and RPC_ISDECORATION__.
Referenced by server::zone::managers::city::CityManagerImplementation::collectNonStructureMaintenance(), server::zone::objects::region::CityRegionImplementation::notifyEnter(), and server::zone::objects::region::CityRegionImplementation::notifyExit().
bool SceneObject::isDeedObject ()
Definition at line 2847 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isDeedObject(), and RPC_ISDEEDOBJECT__.
bool SceneObject::isDetector ()
Definition at line 2241 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::isDetector().
Referenced by DetectorZoneComponent::notifyPositionUpdate().
bool SceneObject::isDiceObject ()
Definition at line 3042 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isDiceObject(), and RPC_ISDICEOBJECT__.
Referenced by DiceMenuComponent::fillObjectMenuResponse(), and DiceMenuComponent::handleObjectMenuSelect().
bool SceneObject::isFactory ()
Definition at line 2808 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isFactory(), and RPC_ISFACTORY__.
Referenced by FactoryObjectMenuComponent::fillObjectMenuResponse(), and FactoryObjectMenuComponent::handleObjectMenuSelect().
bool SceneObject::isFactoryCrate ()
Definition at line 2821 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isFactoryCrate(), and RPC_ISFACTORYCRATE__.
bool SceneObject::isFireworkObject ()
Definition at line 2600 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isFireworkObject(), and RPC_ISFIREWORKOBJECT__.
Referenced by FireworkShowContainerComponent::canAddObject(), FireworkMenuComponent::fillObjectMenuResponse(), FireworkShowMenuComponent::fillObjectMenuResponse(), FireworkMenuComponent::handleObjectMenuSelect(), FireworkShowMenuComponent::handleObjectMenuSelect(), and FireworkShowContainerComponent::transferObject().
bool SceneObject::isFishingBait ()
Definition at line 2977 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isFishingBait(), and RPC_ISFISHINGBAIT__.
Referenced by server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::canAddObject().
bool SceneObject::isFishingPoleObject ()
Definition at line 2834 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isFishingPoleObject(), and RPC_ISFISHINGPOLEOBJECT__.
Referenced by server::zone::managers::minigames::FishingManagerImplementation::getPole().
bool SceneObject::isGarage ()
Definition at line 2509 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isGarage(), and RPC_ISGARAGE__.
Referenced by StructureManager::getInRangeParkingGarage().
bool SceneObject::isGCWBase ()
Definition at line 2214 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::isGCWBase().
Referenced by server::zone::managers::gcw::GCWManagerImplementation::getDestructibleBuildingData(), StructureZoneComponent::notifyInsertToZone(), and PlaceGCWBaseComponent::notifyStructurePlaced().
bool SceneObject::isGeneratorObject ()
Definition at line 2769 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isGeneratorObject(), and RPC_ISGENERATOROBJECT__.
Referenced by StructureManager::reportStructureStatus().
bool SceneObject::isGroupObject ()
Definition at line 3474 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isGroupObject(), and RPC_ISGROUPOBJECT__.
bool SceneObject::isGuildObject ()
Definition at line 3487 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isGuildObject(), and RPC_ISGUILDOBJECT__.
bool SceneObject::isHarvesterObject ()
Definition at line 2756 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isHarvesterObject(), and RPC_ISHARVESTEROBJECT__.
bool SceneObject::isInRange (SceneObject * obj, float range)
Evaluates if the object is in range
Precondition
{ this object is locked, obj is locked}
Postcondition
{ thisobject is locked, obj is locked }
Parameters
obj object that will be checked against
range range to check
Returns
returns true if this object is in range with obj
Definition at line 173 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isInRange(), and RPC_ISINRANGE__SCENEOBJECT_FLOAT_.
Referenced by server::zone::managers::player::PlayerManagerImplementation::acceptTeachingOffer(), CombatManager::attemptPeace(), server::zone::managers::minigames::GamblingManagerImplementation::bet(), server::zone::managers::gcw::GCWManagerImplementation::broadcastBuilding(), CombatManager::broadcastCombatSpam(), server::zone::objects::creature::CreatureImplementation::canCollectDna(), server::zone::managers::player::PlayerManagerImplementation::canGroupMemberHarvestCorpse(), server::zone::objects::creature::CreatureImplementation::canHarvestMe(), server::zone::objects::creature::CreatureImplementation::canMilkMe(), server::zone::managers::minigames::FishingManagerImplementation::checkFishingOnPositionUpdate(), server::zone::objects::tangible::terminal::gambling::GamblingTerminalImplementation::checkJoin(), server::zone::managers::auction::AuctionManagerImplementation::checkRetrieve(), CombatManager::doAreaCombatAction(), server::zone::objects::creature::AiAgentImplementation::doAttack(), GmReviveCommand::doQueueCommand(), SniperShotCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), InsureCommand::doQueueCommand(), KillCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), HarvesterDeactivateCommand::doQueueCommand(), MountCommand::doQueueCommand(), DeathBlowCommand::doQueueCommand(), HarvesterActivateCommand::doQueueCommand(), HarvesterDiscardHopperCommand::doQueueCommand(), HarvesterSelectResourceCommand::doQueueCommand(), DiagnoseCommand::doQueueCommand(), HealMindCommand::doQueueCommand(), FirstAidCommand::doQueueCommand(), QuickHealCommand::doQueueCommand(), ForceCureDiseaseCommand::doQueueCommand(), ForceCurePoisonCommand::doQueueCommand(), StopBleedingCommand::doQueueCommand(), HealStatesOtherCommand::doQueueCommand(), TendCommand::doQueueCommand(), RevivePlayerCommand::doQueueCommand(), DotPackCommand::doQueueCommand(), HealStateCommand::doQueueCommand(), HealWoundCommand::doQueueCommand(), HealEnhanceCommand::doQueueCommand(), CurePackCommand::doQueueCommand(), HealDamageCommand::doQueueCommand(), AttackStateComponent::doRecovery(), TransferstructureCommand::doTransferStructure(), DragIncapacitatedPlayerCommand::drag(), server::zone::managers::minigames::FishingManagerImplementation::fishingStep(), server::zone::objects::group::GroupObjectImplementation::getGroupHarvestModifier(), server::zone::objects::tangible::threat::ThreatMap::getHighestThreatCreature(), StructureManager::getInRangeParkingGarage(), server::zone::managers::player::PlayerManagerImplementation::getNearbyCraftingStation(), DotPackCommand::handleArea(), CurePackCommand::handleArea(), HealDamageCommand::handleArea(), server::zone::managers::sui::SuiManager::handleBankTransfer(), server::chat::ChatManagerImplementation::handleSocialInternalMessage(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), DetectorZoneComponent::notifyPositionUpdate(), MinefieldZoneComponent::notifyPositionUpdate(), TurretZoneComponent::notifyPositionUpdate(), AiNPCComponent::notifyPositionUpdate(), AiCreatureComponent::notifyPositionUpdate(), StructureManager::payMaintenance(), TipCommand::performTip(), server::zone::managers::player::PlayerManagerImplementation::promptTeachableSkills(), InsuranceAllConfirmSuiCallback::run(), InsuranceMenuSuiCallback::run(), CloningStoreSuiCallback::run(), UpdateWarStatusTask::run(), EmptyHopperCallback::run(), server::zone::managers::guild::GuildManagerImplementation::sendTransferAckTo(), server::zone::managers::guild::GuildManagerImplementation::sponsorPlayer(), and server::zone::managers::minigames::FishingManagerImplementation::updateMarker().
bool SceneObject::isInstallationDeed ()
Definition at line 2899 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isInstallationDeed(), and RPC_ISINSTALLATIONDEED__.
bool SceneObject::isInstallationObject ()
Definition at line 2743 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isInstallationObject(), and RPC_ISINSTALLATIONOBJECT__.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addChildInstallationFromDeed(), ShuttleInstallationZoneComponent::destroyObjectFromWorld(), InstallationObjectMenuComponent::fillObjectMenuResponse(), InstallationObjectMenuComponent::handleObjectMenuSelect(), PlaceStructureComponent::notifyStructurePlaced(), and StructureManager::reportStructureStatus().
bool SceneObject::isInstrument ()
Definition at line 2704 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isInstrument(), and RPC_ISINSTRUMENT__.
Referenced by PlayerContainerComponent::notifyObjectInserted(), and PlayerContainerComponent::notifyObjectRemoved().
bool SceneObject::isIntangibleObject ()
Definition at line 2691 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isIntangibleObject(), and RPC_ISINTANGIBLEOBJECT__.
Referenced by server::zone::objects::tangible::ContainerImplementation::canAddObject(), and server::zone::managers::auction::AuctionManagerImplementation::checkSaleItem().
bool SceneObject::isInWater ()
Definition at line 3700 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isInWater(), and RPC_ISINWATER__.
Referenced by CampKitMenuComponent::handleObjectMenuSelect(), and server::zone::managers::minigames::ForageManagerImplementation::startForaging().
bool SceneObject::isJunkDealer ()
Definition at line 2444 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isJunkDealer(), and RPC_ISJUNKDEALER__.
bool SceneObject::isLightsaberCrystalObject ()
Definition at line 2587 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isLightsaberCrystalObject(), and RPC_ISLIGHTSABERCRYSTALOBJECT__.
Referenced by SaberInventoryContainerComponent::canAddObject().
bool SceneObject::isLiveSample ()
Definition at line 2730 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isLiveSample(), and RPC_ISLIVESAMPLE__.
bool SceneObject::isManufactureSchematic ()
Definition at line 2938 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isManufactureSchematic(), and RPC_ISMANUFACTURESCHEMATIC__.
bool SceneObject::isMinefield ()
Definition at line 2232 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::isMinefield().
Referenced by MinefieldMenuComponent::fillObjectMenuResponse(), server::zone::managers::gcw::GCWManagerImplementation::notifyInstallationDestruction(), MinefieldZoneComponent::notifyPositionUpdate(), and StructureManager::placeStructure().
bool SceneObject::isMissionObject ()
Definition at line 3526 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isMissionObject(), and RPC_ISMISSIONOBJECT__.
Referenced by server::zone::managers::mission::MissionManagerImplementation::handleMissionAccept().
bool SceneObject::isMissionTerminal ()
Definition at line 3513 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isMissionTerminal(), and RPC_ISMISSIONTERMINAL__.
Referenced by server::zone::managers::city::CityManagerImplementation::collectNonStructureMaintenance(), TangibleObjectMenuComponent::fillObjectMenuResponse(), and server::zone::objects::player::sessions::SlicingSessionImplementation::getPrefix().
bool SceneObject::isNoTrade ()
Definition at line 2340 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isNoTrade(), and RPC_ISNOTRADE__.
Referenced by server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::canInventoryItemBeSoldAsJunk().
bool SceneObject::isPlayerCreature ()
Definition at line 2192 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isPlayerCreature(), and RPC_ISPLAYERCREATURE__.
Referenced by server::zone::objects::group::GroupObjectImplementation::addMember(), server::zone::objects::structure::StructureObjectImplementation::addTemplateSkillMods(), CombatManager::applyDamage(), server::zone::objects::area::CampSiteActiveAreaImplementation::assumeOwnership(), FactionManager::awardPvpFactionPoints(), server::zone::managers::gcw::GCWManagerImplementation::broadcastBuilding(), CombatManager::broadcastCombatSpam(), server::zone::managers::director::DirectorManager::clearScreenPlayData(), server::zone::objects::building::BuildingObjectImplementation::destroyObjectFromDatabase(), GmReviveCommand::doQueueCommand(), ServerSysGroupCommand::doQueueCommand(), BroadcastAreaCommand::doQueueCommand(), KillPlayerCommand::doQueueCommand(), KillCommand::doQueueCommand(), ObjectMenuComponent::fillObjectMenuResponse(), TurretFireTask::getTargetName(), CurePackCommand::handleArea(), HealDamageCommand::handleArea(), server::chat::ChatManagerImplementation::handleSocialInternalMessage(), server::zone::objects::tangible::TangibleObjectImplementation::inflictDamage(), server::zone::objects::creature::AiAgentImplementation::inflictDamage(), server::zone::objects::creature::CreatureObjectImplementation::inflictDamage(), server::zone::managers::player::PlayerManagerImplementation::killPlayer(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), server::zone::objects::creature::ai::AiActorImplementation::notifyDissapear(), server::zone::objects::creature::AiAgentImplementation::notifyDissapear(), server::zone::objects::area::GarageAreaImplementation::notifyEnter(), server::zone::objects::area::FsVillageAreaImplementation::notifyEnter(), server::zone::objects::area::BadgeActiveAreaImplementation::notifyEnter(), server::zone::objects::area::MissionSpawnActiveAreaImplementation::notifyEnter(), server::zone::objects::area::MissionReconActiveAreaImplementation::notifyEnter(), server::zone::objects::area::LairSpawnAreaImplementation::notifyEnter(), server::zone::objects::area::CampSiteActiveAreaImplementation::notifyEnter(), server::zone::objects::area::MissionReconActiveAreaImplementation::notifyExit(), server::zone::objects::area::CampSiteActiveAreaImplementation::notifyExit(), server::zone::objects::region::CityRegionImplementation::notifyExit(), PlayerZoneComponent::notifyInsert(), server::zone::objects::creature::ai::AiActorImplementation::notifyInsert(), server::zone::objects::creature::AiAgentImplementation::notifyInsert(), PlayerZoneComponent::notifyInsertToZone(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), VendorDataComponent::performVendorBark(), server::zone::managers::player::PlayerManagerImplementation::promptTeachableSkills(), server::zone::managers::director::DirectorManager::readScreenPlayData(), server::zone::objects::group::GroupObjectImplementation::removeMember(), server::zone::managers::minigames::FishingManagerImplementation::removeSplash(), server::zone::objects::structure::StructureObjectImplementation::removeTemplateSkillMods(), InvisibleDelayEvent::run(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::selectConversationOption(), server::zone::objects::group::GroupObjectImplementation::sendBaselinesTo(), server::zone::objects::draftschematic::DraftSchematicImplementation::sendBaselinesTo(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendBaselinesTo(), server::zone::objects::tangible::TangibleObjectImplementation::sendBaselinesTo(), server::zone::objects::creature::CreatureObjectImplementation::sendBaselinesTo(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationStartTo(), server::zone::objects::creature::ai::AiActorImplementation::sendConversationStartTo(), server::zone::objects::creature::AiAgentImplementation::sendConversationStartTo(), server::zone::objects::creature::CreatureObjectImplementation::sendToOwner(), PlayerZoneComponent::switchZone(), server::zone::objects::installation::GeneratorObjectImplementation::synchronizedUIListen(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::synchronizedUIListen(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::synchronizedUIListen(), server::zone::objects::installation::GeneratorObjectImplementation::synchronizedUIStopListen(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::synchronizedUIStopListen(), TangibleObjectMessage3::TangibleObjectMessage3(), PlayerZoneComponent::teleport(), TangibleObjectDeltaMessage3::updateName(), PlayerZoneComponent::updateZone(), PlayerZoneComponent::updateZoneWithParent(), and server::zone::managers::director::DirectorManager::writeScreenPlayData().
bool SceneObject::isPlayerObject ()
Definition at line 2379 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isPlayerObject(), and RPC_ISPLAYEROBJECT__.
Referenced by SchematicList::addRewardedSchematics(), and server::zone::managers::skill::SkillManager::updateXpLimits().
bool SceneObject::isPsgArmorObject ()
Definition at line 2613 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isPsgArmorObject(), and RPC_ISPSGARMOROBJECT__.
Referenced by CombatManager::getPSGArmor().
bool SceneObject::isRecycleToolObject ()
Definition at line 3094 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isRecycleToolObject(), and RPC_ISRECYCLETOOLOBJECT__.
bool SceneObject::isRegion ()
Definition at line 2405 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isRegion(), and RPC_ISREGION__.
bool SceneObject::isRepairTool ()
Definition at line 3003 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isRepairTool(), and RPC_ISREPAIRTOOL__.
bool SceneObject::isResourceContainer ()
Definition at line 2652 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isResourceContainer(), and RPC_ISRESOURCECONTAINER__.
Referenced by BlueprintEntry::removeResources().
bool SceneObject::isResourceSpawn ()
Definition at line 2665 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isResourceSpawn(), and RPC_ISRESOURCESPAWN__.
Referenced by FactoryBlueprint::addIngredient().
bool SceneObject::isRobeObject ()
Definition at line 2574 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isRobeObject(), and RPC_ISROBEOBJECT__.
Referenced by PlayerContainerComponent::canAddObject(), PlayerContainerComponent::notifyObjectInserted(), and PlayerContainerComponent::notifyObjectRemoved().
bool SceneObject::isSecurityTerminal ()
Definition at line 2250 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::isSecurityTerminal().
bool SceneObject::isShipObject ()
Definition at line 2457 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isShipObject(), and RPC_ISSHIPOBJECT__.
bool SceneObject::isShuttleInstallation ()
Definition at line 2366 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isShuttleInstallation(), and RPC_ISSHUTTLEINSTALLATION__.
bool SceneObject::isSignObject ()
Definition at line 2886 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isSignObject(), and RPC_ISSIGNOBJECT__.
bool SceneObject::isStaticObject ()
Definition at line 3435 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isStaticObject(), and RPC_ISSTATICOBJECT__.
Referenced by StructureContainerComponent::checkContainerPermission(), and ContainerComponent::checkContainerPermission().
bool SceneObject::isStructureObject ()
Definition at line 2951 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isStructureObject(), and RPC_ISSTRUCTUREOBJECT__.
Referenced by server::zone::ZoneImplementation::addSceneObject(), server::zone::objects::region::CityRegionImplementation::cleanupDecorations(), ShuttleInstallationZoneComponent::destroyObjectFromWorld(), CampKitMenuComponent::handleObjectMenuSelect(), server::zone::objects::region::CityRegionImplementation::notifyEnter(), server::zone::objects::region::CityRegionImplementation::notifyExit(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission().
bool SceneObject::isTangibleObject ()
Definition at line 2639 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isTangibleObject(), and RPC_ISTANGIBLEOBJECT__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::addInsurableItemsRecursive(), PlayerContainerComponent::canAddObject(), MinefieldContainerComponent::checkContainerPermission(), SkillBuffObjectAttributeListComponent::fillAttributeList(), ThrowGrenadeMenuComponent::fillObjectMenuResponse(), LightsaberObjectMenuComponent::fillObjectMenuResponse(), LairMenuComponent::fillObjectMenuResponse(), SkillBuffObjectMenuComponent::fillObjectMenuResponse(), TangibleObjectMenuComponent::fillObjectMenuResponse(), TrapMenuComponent::fillObjectMenuResponse(), VehicleCustomKitObjectMenuComponent::fillObjectMenuResponse(), WeaponObjectMenuComponent::fillObjectMenuResponse(), LootSchematicMenuComponent::fillObjectMenuResponse(), WearableObjectMenuComponent::fillObjectMenuResponse(), ShellfishHarvesterMenuComponent::fillObjectMenuResponse(), GogglesObjectMenuComponent::fillObjectMenuResponse(), BountyHunterDroidMenuComponent::fillObjectMenuResponse(), CurePackCommand::findCurePack(), HealEnhanceCommand::findEnhancePack(), RevivePlayerCommand::findRevivePack(), HealStateCommand::findStatePack(), HealDamageCommand::findStimPack(), HealWoundCommand::findWoundPack(), server::zone::managers::player::PlayerManagerImplementation::getInsurableItems(), ThrowGrenadeMenuComponent::handleObjectMenuSelect(), InsuranceTerminalMenuComponent::handleObjectMenuSelect(), LairMenuComponent::handleObjectMenuSelect(), LightsaberObjectMenuComponent::handleObjectMenuSelect(), WearableObjectMenuComponent::handleObjectMenuSelect(), CampKitMenuComponent::handleObjectMenuSelect(), TrapMenuComponent::handleObjectMenuSelect(), SkillBuffObjectMenuComponent::handleObjectMenuSelect(), VehicleCustomKitObjectMenuComponent::handleObjectMenuSelect(), CloningTerminalMenuComponent::handleObjectMenuSelect(), WeaponObjectMenuComponent::handleObjectMenuSelect(), ArtCrateMenuComponent::handleObjectMenuSelect(), LootSchematicMenuComponent::handleObjectMenuSelect(), TangibleObjectMenuComponent::handleObjectMenuSelect(), ShellfishHarvesterMenuComponent::handleObjectMenuSelect(), GogglesObjectMenuComponent::handleObjectMenuSelect(), CityDecorationMenuComponent::handleObjectMenuSelect(), CampTerminalMenuComponent::handleObjectMenuSelect(), BountyHunterDroidMenuComponent::handleObjectMenuSelect(), TurretControlMenuComponent::handleObjectMenuSelect(), SecurityTerminalMenuComponent::handleObjectMenuSelect(), UplinkTerminalMenuComponent::handleObjectMenuSelect(), BankTerminalMenuComponent::handleObjectMenuSelect(), PlayerContainerComponent::notifyObjectInserted(), PlayerContainerComponent::notifyObjectRemoved(), DetectorZoneComponent::notifyPositionUpdate(), TurretZoneComponent::notifyPositionUpdate(), InsuranceAllConfirmSuiCallback::run(), ClearDefenderListsTask::run(), and server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner().
bool SceneObject::isTerminal ()
Definition at line 3461 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isTerminal(), and RPC_ISTERMINAL__.
Referenced by StructureTerminalMenuComponent::fillObjectMenuResponse(), CampTerminalMenuComponent::fillObjectMenuResponse(), and server::zone::managers::guild::GuildManagerImplementation::transferGuildHall().
bool SceneObject::isTrapObject ()
Definition at line 2990 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isTrapObject(), and RPC_ISTRAPOBJECT__.
bool SceneObject::isTurret ()
Definition at line 2223 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::isTurret().
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addChildInstallationFromDeed(), CombatManager::applyDamage(), CombatManager::getArmorTurretReduction(), CombatManager::getHitChance(), server::zone::managers::gcw::GCWManagerImplementation::notifyInstallationDestruction(), TurretZoneComponent::notifyPositionUpdate(), and StructureManager::placeStructure().
bool SceneObject::isTurretControlTerminal ()
Definition at line 2259 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::isTurretControlTerminal().
bool SceneObject::isVehicleDeedObject ()
Definition at line 2860 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isVehicleDeedObject(), and RPC_ISVEHICLEDEEDOBJECT__.
bool SceneObject::isVehicleObject ()
Definition at line 2470 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isVehicleObject(), and RPC_ISVEHICLEOBJECT__.
Referenced by server::zone::objects::scene::SceneObjectImplementation::broadcastDestroyPrivate(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessagesPrivate(), server::zone::objects::scene::SceneObjectImplementation::broadcastObjectPrivate(), and server::zone::ZoneImplementation::getInRangeObjects().
bool SceneObject::isVendor ()
Definition at line 2205 of file SceneObject.cpp.
References _getImplementationForRead(), and server::zone::objects::scene::SceneObjectImplementation::isVendor().
Referenced by server::zone::managers::auction::AuctionManagerImplementation::addSaleItem(), VendorContainerComponent::checkContainerPermission(), server::zone::managers::auction::AuctionManagerImplementation::checkRetrieve(), server::zone::managers::auction::AuctionManagerImplementation::checkSaleItem(), server::zone::managers::auction::AuctionManagerImplementation::fillAuctionQueryHeadersResponseMessage(), VendorMenuComponent::fillObjectMenuResponse(), VendorMenuComponent::handleObjectMenuSelect(), IsVendorOwnerResponseMessage::IsVendorOwnerResponseMessage(), server::zone::managers::auction::AuctionsMapImplementation::sendVendorUpdateMail(), and server::zone::managers::auction::AuctionsMapImplementation::updateUID().
bool SceneObject::isWaypointObject ()
Definition at line 1472 of file SceneObject.cpp.
References _getImplementationForRead(), server::zone::objects::scene::SceneObjectImplementation::isWaypointObject(), and RPC_ISWAYPOINTOBJECT__.
bool SceneObject::isWeaponObject ()
Definition at line 2522 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isWeaponObject(), and RPC_ISWEAPONOBJECT__.
Referenced by server::zone::managers::loot::LootManagerImplementation::addConditionDamage(), server::zone::managers::player::PlayerManagerImplementation::addInsurableItemsRecursive(), server::zone::managers::loot::LootManagerImplementation::addRandomDots(), server::zone::managers::player::creation::PlayerCreationManager::addStartingItemsInto(), server::zone::managers::player::creation::PlayerCreationManager::addStartingWeaponsInto(), server::zone::managers::loot::LootManagerImplementation::addStaticDots(), server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), PlayerContainerComponent::canAddObject(), FireHeavyWeaponMenuComponent::fillObjectMenuResponse(), TangibleObjectMenuComponent::fillObjectMenuResponse(), server::zone::managers::player::PlayerManagerImplementation::getInsurableItems(), server::zone::objects::player::sessions::SlicingSessionImplementation::getPrefix(), FireHeavyWeaponMenuComponent::handleObjectMenuSelect(), PlayerContainerComponent::notifyObjectInserted(), server::zone::objects::creature::CreatureObjectImplementation::notifyObjectInserted(), PlayerContainerComponent::notifyObjectRemoved(), server::zone::objects::creature::CreatureObjectImplementation::notifyObjectRemoved(), InsuranceMenuSuiCallback::run(), and server::zone::managers::loot::LootManagerImplementation::setSkillMods().
bool SceneObject::isWearableContainerObject ()
Definition at line 2548 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isWearableContainerObject(), and RPC_ISWEARABLECONTAINEROBJECT__.
bool SceneObject::isWearableObject ()
Definition at line 2535 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::isWearableObject(), and RPC_ISWEARABLEOBJECT__.
Referenced by server::zone::managers::player::PlayerManagerImplementation::addInsurableItemsRecursive(), server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), ArmorObjectMenuComponent::fillObjectMenuResponse(), server::zone::managers::player::PlayerManagerImplementation::getInsurableItems(), InsuranceMenuSuiCallback::run(), server::zone::managers::loot::LootManagerImplementation::setSkillMods(), and server::zone::managers::loot::LootManagerImplementation::setSockets().
BaseMessage * SceneObject::link (unsigned long long objectID, unsigned int containmentType = 4)
Creates a new UpdateContainmentMessage that adds/links this object to the specified objectID
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
objectID object id of object to link
containmentType arrangement type?
Returns
returns a new valid UpdateContainmentMessage
Definition at line 394 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::link(), and RPC_LINK__LONG_INT_.
Referenced by server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), ContainerComponent::removeObject(), and ContainerComponent::transferObject().
void SceneObject::loadTemplateData (SharedObjectTemplate * templateData)
Reads and sets the template data from a SharedObjectTemplate LuaObject
Precondition
{ templateData is a valid pointer }
Postcondition
{ SceneObject members are initialized }
Parameters
templateData templateData points to the LuaObject that is used to initialize SceneObejct members
Definition at line 68 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::loadTemplateData().
void SceneObject::notifyCloseContainer (CreatureObject * player)
Parameters
player player that closed the container
Definition at line 2045 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::notifyCloseContainer(), and RPC_NOTIFYCLOSECONTAINER__CREATUREOBJECT_.
void SceneObject::notifyDissapear (QuadTreeEntry * entry)
Definition at line 696 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::notifyDissapear().
Referenced by InvisibleDelayEvent::run(), and server::zone::objects::creature::CreatureObjectImplementation::sendToOwner().
void SceneObject::notifyInsert (QuadTreeEntry * entry)
Definition at line 687 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::notifyInsert().
Referenced by server::zone::objects::building::BuildingObjectImplementation::notifyInsert(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToZone(), and InvisibleDelayEvent::run().
void SceneObject::notifyInsertToZone (Zone * zone)
Inserts this object into zone
Precondition
{ this object is locked }
Postcondition
{ this object is locked and inserted into zone }
Parameters
zone Zone object where this object will be inserted
Definition at line 607 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::notifyInsertToZone(), and RPC_NOTIFYINSERTTOZONE__ZONE_.
Referenced by ZoneContainerComponent::insertActiveArea().
void SceneObject::notifyLoadFromDatabase ()
Gets called when this objects is loaded from database
Precondition
{ this locked }
Postcondition
{ this locked }
Definition at line 116 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::notifyLoadFromDatabase(), and RPC_NOTIFYLOADFROMDATABASE__.
int SceneObject::notifyObjectInserted (SceneObject * object)
Is called when this object has been inserted with an object
Parameters
object object that has been inserted
Definition at line 1143 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::notifyObjectInserted(), and RPC_NOTIFYOBJECTINSERTED__SCENEOBJECT_.
Referenced by SaberInventoryContainerComponent::notifyObjectInserted(), FireworkShowContainerComponent::notifyObjectInserted(), and ContainerComponent::notifyObjectInserted().
int SceneObject::notifyObjectInsertedToChild (SceneObject * object, SceneObject * child, SceneObject * oldParent)
Definition at line 251 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::notifyObjectInsertedToChild(), and RPC_NOTIFYOBJECTINSERTEDTOCHILD__SCENEOBJECT_SCENEOBJECT_SCENEOBJECT_.
int SceneObject::notifyObjectRemoved (SceneObject * object)
Is called when an object was removed
Parameters
object object that has been inserted
Definition at line 1157 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::notifyObjectRemoved(), and RPC_NOTIFYOBJECTREMOVED__SCENEOBJECT_.
Referenced by SaberInventoryContainerComponent::notifyObjectRemoved(), FireworkShowContainerComponent::notifyObjectRemoved(), and ContainerComponent::notifyObjectRemoved().
int SceneObject::notifyObjectRemovedFromChild (SceneObject * object, SceneObject * child)
Definition at line 267 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::notifyObjectRemovedFromChild(), and RPC_NOTIFYOBJECTREMOVEDFROMCHILD__SCENEOBJECT_SCENEOBJECT_.
Referenced by ContainerComponent::removeObject().
void SceneObject::notifyPositionUpdate (QuadTreeEntry * entry)
Definition at line 2031 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::notifyPositionUpdate(), and RPC_NOTIFYPOSITIONUPDATE__QUADTREEENTRY_.
Referenced by server::zone::ZoneImplementation::updateActiveAreas(), and ZoneComponent::updateZoneWithParent().
void SceneObject::notifyRemoveFromZone ()
Definition at line 705 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::notifyRemoveFromZone(), and RPC_NOTIFYREMOVEFROMZONE__.
Referenced by ZoneContainerComponent::removeActiveArea().
void SceneObject::notifySelfPositionUpdate ()
Definition at line 2018 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::notifySelfPositionUpdate(), and RPC_NOTIFYSELFPOSITIONUPDATE__.
Referenced by ZoneComponent::notifySelfPositionUpdate().
void SceneObject::openContainerTo (CreatureObject * player)
Opens container contents to player
Precondition
{ }
Postcondition
{ }
Parameters
player CreatureObject to open the container to
Definition at line 569 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::openContainerTo(), and RPC_OPENCONTAINERTO__CREATUREOBJECT_.
Referenced by SnoopCommand::doQueueCommand(), LootCommand::doQueueCommand(), TangibleObjectMenuComponent::handleObjectMenuSelect(), and server::zone::managers::minigames::FishingManagerImplementation::sendReward().
void SceneObject::putInContainer (SceneObject * obj, unsigned long long key)
Definition at line 1842 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::putInContainer(), and RPC_PUTINCONTAINER__SCENEOBJECT_LONG_.
void SceneObject::removeAllContainerObjects ()
Definition at line 1829 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::removeAllContainerObjects(), and RPC_REMOVEALLCONTAINEROBJECTS__.
Referenced by CreatureHabitatMenuComponent::handleObjectMenuSelect().
void SceneObject::removeFromContainerObjects (int index)
Definition at line 1857 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::removeFromContainerObjects(), and RPC_REMOVEFROMCONTAINEROBJECTS__INT_.
bool SceneObject::removeObject (SceneObject * object, SceneObject * destination, bool notifyClient = false)
Tries to remove/unlink object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be removed from the current object
destination SceneObject that will be the new destination of the object.
notifyClient not used currently
Returns
returns true if the object has been successfully removed
Definition at line 205 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::removeObject(), and RPC_REMOVEOBJECT__SCENEOBJECT_SCENEOBJECT_BOOL_.
Referenced by server::zone::objects::intangible::VehicleControlDeviceImplementation::destroyObjectFromDatabase(), server::zone::objects::building::BuildingObjectImplementation::destroyObjectFromDatabase(), and ZoneComponent::destroyObjectFromWorld().
void SceneObject::removePendingTask (const String & name)
Removes a pending task from this SceneObject
Precondition
{ this locked }
Postcondition
{ this locked }
Parameters
name Name of the task to drop
Definition at line 927 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::removePendingTask().
Referenced by server::zone::objects::intangible::VehicleControlDeviceImplementation::cancelSpawnObject(), server::zone::managers::minigames::FishingManagerImplementation::createFishingEvent(), ForceOfWillCommand::doQueueCommand(), server::zone::managers::minigames::ForageManagerImplementation::finishForaging(), server::zone::managers::player::PlayerManagerImplementation::notifyDestruction(), server::zone::managers::resource::ResourceManagerImplementation::notifyObserverEvent(), server::zone::managers::player::PlayerManagerImplementation::notifyObserverEvent(), and server::zone::managers::minigames::FishingManagerImplementation::stopFishingEvent().
void SceneObject::removeSlottedObject (int index)
Definition at line 1698 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::removeSlottedObject(), and RPC_REMOVESLOTTEDOBJECT__INT_.
void SceneObject::rotate (int degrees)
Rotates an object by a specified number of degrees.
Parameters
degrees How many degrees to rotate the object with 0 being North. TODO:
notifyClient
Definition at line 1990 of file SceneObject.cpp.
References _getImplementation(), server::zone::objects::scene::SceneObjectImplementation::rotate(), and RPC_ROTATE__INT_.
Referenced by StructureManager::placeStructure(), and RecruitSkillTrainerSuiCallback::run().
void SceneObject::sendAttributeListTo (CreatureObject * object)
Sends an AttributeListMessage to specified object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, object received the attribute list message }
Parameters
object SceneObject that will receive the message
Definition at line 522 of file SceneObject.cpp.
References _getImplementationForRead(), RPC_SENDATTRIBUTELISTTO__CREATUREOBJECT_, and server::zone::objects::scene::SceneObjectImplementation::sendAttributeListTo().
void SceneObject::sendBaselinesTo (SceneObject * player)
Sends the baseline messages of this object to the specified player, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the baseline messages }
Parameters
player SceneObject that will receive the baselines
Definition at line 466 of file SceneObject.cpp.
References _getImplementation(), RPC_SENDBASELINESTO__SCENEOBJECT_, and server::zone::objects::scene::SceneObjectImplementation::sendBaselinesTo().
void SceneObject::sendContainerObjectsTo (SceneObject * player)
Sends the contained non slotted objects to the specified player
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the container objects }
Parameters
player SceneObject that will receive the objects
Definition at line 480 of file SceneObject.cpp.
References _getImplementation(), RPC_SENDCONTAINEROBJECTSTO__SCENEOBJECT_, and server::zone::objects::scene::SceneObjectImplementation::sendContainerObjectsTo().
void SceneObject::sendDestroyTo (SceneObject * player)
Sends a SceneObjectDestroyMessage of this object to client
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the destroy message }
Parameters
plaer SceneObject that will receive the message
Definition at line 452 of file SceneObject.cpp.
References _getImplementation(), RPC_SENDDESTROYTO__SCENEOBJECT_, and server::zone::objects::scene::SceneObjectImplementation::sendDestroyTo().
Referenced by server::zone::objects::group::GroupObjectImplementation::disband(), BankTerminalMenuComponent::handleObjectMenuSelect(), GroupManager::kickFromGroup(), GroupManager::leaveGroup(), PlayerZoneComponent::notifyDissapear(), and server::zone::managers::mission::MissionManagerImplementation::removeMission().
void SceneObject::sendMessage (BasePacket * msg)
Sends BasePacket msg to the owner of this object, needs to be overriden
Precondition
{ }
Postcondition
{owner of this object received message, message is deleted }
Parameters
msg BasePacket to be sent
Definition at line 859 of file SceneObject.cpp.
References _getImplementation(), RPC_SENDMESSAGE__BASEPACKET_, and server::zone::objects::scene::SceneObjectImplementation::sendMessage().
Referenced by server::zone::objects::group::GroupObjectImplementation::broadcastMessage(), server::zone::objects::scene::SceneObjectImplementation::broadcastMessagesPrivate(), server::zone::objects::scene::SceneObjectImplementation::close(), server::zone::objects::ship::ShipObjectImplementation::sendBaselinesTo(), server::zone::objects::staticobject::StaticObjectImplementation::sendBaselinesTo(), server::zone::objects::intangible::IntangibleObjectImplementation::sendBaselinesTo(), server::zone::objects::resource::ResourceContainerImplementation::sendBaselinesTo(), server::zone::objects::cell::CellObjectImplementation::sendBaselinesTo(), server::zone::objects::factorycrate::FactoryCrateImplementation::sendBaselinesTo(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendBaselinesTo(), server::zone::objects::mission::MissionObjectImplementation::sendBaselinesTo(), server::zone::objects::installation::InstallationObjectImplementation::sendBaselinesTo(), server::zone::objects::building::BuildingObjectImplementation::sendBaselinesTo(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::sendBaselinesTo(), server::zone::objects::tangible::TangibleObjectImplementation::sendBaselinesTo(), server::zone::objects::player::PlayerObjectImplementation::sendBaselinesTo(), server::zone::objects::creature::CreatureObjectImplementation::sendBaselinesTo(), AiStateComponent::sendConversationStartTo(), server::zone::objects::creature::AiAgentImplementation::sendConversationStartTo(), server::zone::objects::scene::SceneObjectImplementation::sendDestroyTo(), server::zone::ZoneImplementation::sendMapLocationsTo(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendMsco7(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendTo(), server::zone::objects::building::BuildingObjectImplementation::sendTo(), server::zone::objects::scene::SceneObjectImplementation::sendTo(), server::zone::objects::scene::SceneObjectImplementation::sendWithoutContainerObjectsTo(), server::zone::objects::scene::SceneObjectImplementation::sendWithoutParentTo(), ZoneComponent::switchZone(), server::zone::objects::installation::GeneratorObjectImplementation::synchronizedUIListen(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::synchronizedUIListen(), and server::zone::objects::tangible::TangibleObjectImplementation::synchronizedUIListen().
void SceneObject::sendSlottedObjectsTo (SceneObject * player)
Sends the contained slotted objects to the specified player
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the slotted objects }
Parameters
player SceneObject that will receive the objects
Definition at line 494 of file SceneObject.cpp.
References _getImplementation(), RPC_SENDSLOTTEDOBJECTSTO__SCENEOBJECT_, and server::zone::objects::scene::SceneObjectImplementation::sendSlottedObjectsTo().
void SceneObject::sendTo (SceneObject * player, bool doClose)
Sends the necessary messages to player in order to create this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received this object }
Parameters
player SceneObject that will receive the messages
doClose if true a SceneObjectCloseMessage is sent to finish the object
Definition at line 409 of file SceneObject.cpp.
References _getImplementationForRead(), RPC_SENDTO__SCENEOBJECT_BOOL_, and server::zone::objects::scene::SceneObjectImplementation::sendTo().
Referenced by server::zone::objects::player::sessions::SlicingSessionImplementation::handleContainerSlice(), BankTerminalMenuComponent::handleObjectMenuSelect(), PlayerZoneComponent::notifyInsert(), server::zone::objects::building::BuildingObjectImplementation::notifyInsert(), server::zone::objects::building::BuildingObjectImplementation::notifyObjectInsertedToChild(), server::zone::objects::building::BuildingObjectImplementation::sendContainerObjectsTo(), server::zone::objects::scene::SceneObjectImplementation::sendContainerObjectsTo(), server::zone::managers::minigames::FishingManagerImplementation::sendReward(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::synchronizedUIListen(), and server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus().
void SceneObject::sendToOwner (bool doClose = true)
Sends the necessary messages to owner client, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, owner received its own scene object }
Parameters
doClose if true a SceneObjectCloseMessage is sent to finish the object
Definition at line 508 of file SceneObject.cpp.
References _getImplementation(), RPC_SENDTOOWNER__BOOL_, and server::zone::objects::scene::SceneObjectImplementation::sendToOwner().
Referenced by ZoneComponent::switchZone().
void SceneObject::sendWithoutContainerObjectsTo (SceneObject * player)
Definition at line 438 of file SceneObject.cpp.
References _getImplementationForRead(), RPC_SENDWITHOUTCONTAINEROBJECTSTO__SCENEOBJECT_, and server::zone::objects::scene::SceneObjectImplementation::sendWithoutContainerObjectsTo().
Referenced by server::zone::managers::player::PlayerManagerImplementation::handleAddItemToTradeWindow(), and TangibleObjectMenuComponent::handleObjectMenuSelect().
void SceneObject::sendWithoutParentTo (SceneObject * player)
Sends the object without linking to its actual parent and without sending its children (f.e trade)
Definition at line 424 of file SceneObject.cpp.
References _getImplementationForRead(), RPC_SENDWITHOUTPARENTTO__SCENEOBJECT_, and server::zone::objects::scene::SceneObjectImplementation::sendWithoutParentTo().
Referenced by SnoopCommand::doQueueCommand().
void SceneObject::setCityRegion (CityRegion * region)
Definition at line 1271 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::setCityRegion().
void SceneObject::setClientObject (bool val)
Definition at line 3408 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCLIENTOBJECT__BOOL_, and server::zone::objects::scene::SceneObjectImplementation::setClientObject().
void SceneObject::setClientObjectCRC (unsigned int objCRC)
Definition at line 3244 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCLIENTOBJECTCRC__INT_, and server::zone::objects::scene::SceneObjectImplementation::setClientObjectCRC().
void SceneObject::setContainerAllowPermission (const String & group, unsigned short perm)
Definition at line 3200 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCONTAINERALLOWPERMISSION__STRING_SHORT_, and server::zone::objects::scene::SceneObjectImplementation::setContainerAllowPermission().
void SceneObject::setContainerComponent (const String & name)
Definition at line 2317 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::setContainerComponent().
void SceneObject::setContainerDefaultAllowPermission (unsigned short perm)
Definition at line 3116 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCONTAINERDEFAULTALLOWPERMISSION__SHORT_, and server::zone::objects::scene::SceneObjectImplementation::setContainerDefaultAllowPermission().
void SceneObject::setContainerDefaultDenyPermission (unsigned short perm)
Definition at line 3144 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCONTAINERDEFAULTDENYPERMISSION__SHORT_, and server::zone::objects::scene::SceneObjectImplementation::setContainerDefaultDenyPermission().
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addHair(), and ImageDesignManager::createHairObject().
void SceneObject::setContainerDenyPermission (const String & group, unsigned short perm)
Definition at line 3215 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCONTAINERDENYPERMISSION__STRING_SHORT_, and server::zone::objects::scene::SceneObjectImplementation::setContainerDenyPermission().
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addHair(), and ImageDesignManager::createHairObject().
void SceneObject::setContainerInheritPermissionsFromParent (bool val)
Definition at line 3172 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCONTAINERINHERITPERMISSIONSFROMPARENT__BOOL_, and server::zone::objects::scene::SceneObjectImplementation::setContainerInheritPermissionsFromParent().
void SceneObject::setContainerOwnerID (unsigned long long id)
Definition at line 3186 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCONTAINEROWNERID__LONG_, and server::zone::objects::scene::SceneObjectImplementation::setContainerOwnerID().
Referenced by server::zone::objects::creature::AiAgentImplementation::notifyDespawn(), and server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction().
void SceneObject::setContainerType (int type)
Definition at line 1885 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCONTAINERTYPE__INT_, and server::zone::objects::scene::SceneObjectImplementation::setContainerType().
void SceneObject::setContainerVolumeLimit (int lim)
Definition at line 1871 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCONTAINERVOLUMELIMIT__INT_, and server::zone::objects::scene::SceneObjectImplementation::setContainerVolumeLimit().
void SceneObject::setContainmentType (unsigned int type)
Definition at line 3380 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCONTAINMENTTYPE__INT_, and server::zone::objects::scene::SceneObjectImplementation::setContainmentType().
void SceneObject::setCustomObjectName (const UnicodeString & name, bool notifyClient)
Updates the custom name of the object
Precondition
{ this locked }
Postcondition
{ this locked }
Definition at line 545 of file SceneObject.cpp.
References _getImplementation(), RPC_SETCUSTOMOBJECTNAME__UNICODESTRING_BOOL_, and server::zone::objects::scene::SceneObjectImplementation::setCustomObjectName().
void SceneObject::setDetailedDescription (const String & detail)
Definition at line 1533 of file SceneObject.cpp.
References _getImplementation(), RPC_SETDETAILEDDESCRIPTION__STRING_, and server::zone::objects::scene::SceneObjectImplementation::setDetailedDescription().
Referenced by server::zone::managers::gcw::GCWManagerImplementation::addChildInstallationFromDeed(), and server::zone::objects::building::BuildingObjectImplementation::createChildObjects().
void SceneObject::setDirection (float fw, float fx, float fy, float fz)
Definition at line 3313 of file SceneObject.cpp.
References _getImplementation(), RPC_SETDIRECTION__FLOAT_FLOAT_FLOAT_FLOAT_, and server::zone::objects::scene::SceneObjectImplementation::setDirection().
Referenced by AlertStateComponent::doMovement(), TeleportCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), DragIncapacitatedPlayerCommand::drag(), SpawnAreaMap::loadStaticSpawns(), and server::zone::objects::creature::aigroup::AiGroupImplementation::setup().
void SceneObject::setDirection (float headingAngleRadians)
Definition at line 3330 of file SceneObject.cpp.
References _getImplementation(), RPC_SETDIRECTION__FLOAT_, and server::zone::objects::scene::SceneObjectImplementation::setDirection().
void SceneObject::setDirection (const Quaternion & dir)
Definition at line 3344 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::setDirection().
void SceneObject::setGameObjectType (unsigned int type)
Definition at line 3230 of file SceneObject.cpp.
References _getImplementation(), RPC_SETGAMEOBJECTTYPE__INT_, and server::zone::objects::scene::SceneObjectImplementation::setGameObjectType().
Referenced by server::zone::managers::object::ObjectManager::loadPersistentObject().
void SceneObject::setLoggingName (const String & name)
Definition at line 3394 of file SceneObject.cpp.
References _getImplementation(), RPC_SETLOGGINGNAME__STRING_, and server::zone::objects::scene::SceneObjectImplementation::setLoggingName().
Referenced by server::zone::managers::object::ObjectManager::loadPersistentObject().
void SceneObject::setMovementCounter (unsigned int count)
Definition at line 3353 of file SceneObject.cpp.
References _getImplementation(), RPC_SETMOVEMENTCOUNTER__INT_, and server::zone::objects::scene::SceneObjectImplementation::setMovementCounter().
Referenced by server::zone::objects::player::PlayerObjectImplementation::reload(), SelectCharacterCallback::run(), PlayerZoneComponent::switchZone(), and PlayerZoneComponent::teleport().
void SceneObject::setObjectMenuComponent (const String & name)
Definition at line 2308 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::setObjectMenuComponent().
void SceneObject::setObjectName (StringId & stringID)
Definition at line 3304 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::setObjectName().
void SceneObject::setParent (QuadTreeEntry * entry)
Definition at line 2085 of file SceneObject.cpp.
References _getImplementation(), RPC_SETPARENT__QUADTREEENTRY_, and server::zone::objects::scene::SceneObjectImplementation::setParent().
Referenced by server::zone::managers::object::ObjectManager::cloneObject().
void SceneObject::setPlanetMapCategory (PlanetMapCategory * pmc)
Definition at line 3578 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::setPlanetMapCategory().
Referenced by server::zone::managers::vendor::VendorManager::handleRegisterVendorCallback(), and server::zone::managers::city::CityManagerImplementation::registerCity().
void SceneObject::setPlanetMapSubCategory (PlanetMapCategory * pmc)
Definition at line 3587 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::setPlanetMapSubCategory().
Referenced by server::zone::managers::vendor::VendorManager::handleRegisterVendorCallback().
void SceneObject::setSendToClient (bool val)
Definition at line 3741 of file SceneObject.cpp.
References _getImplementation(), RPC_SETSENDTOCLIENT__BOOL_, and server::zone::objects::scene::SceneObjectImplementation::setSendToClient().
void SceneObject::setServerObjectCRC (unsigned int objCRC)
Definition at line 3258 of file SceneObject.cpp.
References _getImplementation(), RPC_SETSERVEROBJECTCRC__INT_, and server::zone::objects::scene::SceneObjectImplementation::setServerObjectCRC().
bool SceneObject::setTransformForCollisionMatrixIfNull (Matrix4 * mat)
Definition at line 3677 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::setTransformForCollisionMatrixIfNull().
Referenced by CollisionManager::getTransformMatrix().
void SceneObject::setZone (Zone * zone)
Definition at line 3290 of file SceneObject.cpp.
References _getImplementation(), RPC_SETZONE__ZONE_, and server::zone::objects::scene::SceneObjectImplementation::setZone().
Referenced by ZoneContainerComponent::insertActiveArea(), ZoneContainerComponent::removeActiveArea(), and ZoneContainerComponent::transferObject().
void SceneObject::setZoneComponent (const String & name)
Definition at line 2326 of file SceneObject.cpp.
References _getImplementation(), RPC_SETZONECOMPONENT__STRING_, and server::zone::objects::scene::SceneObjectImplementation::setZoneComponent().
void SceneObject::setZoneProcessServer (ZoneProcessServer * srv)
Definition at line 3272 of file SceneObject.cpp.
References _getImplementation(), and server::zone::objects::scene::SceneObjectImplementation::setZoneProcessServer().
void SceneObject::showFlyText (const String & file, const String & uax, byte red, byte green, byte blue)
Definition at line 968 of file SceneObject.cpp.
References _getImplementation(), RPC_SHOWFLYTEXT__STRING_STRING_BYTE_BYTE_BYTE_, and server::zone::objects::scene::SceneObjectImplementation::showFlyText().
Referenced by CombatManager::doBlock(), CombatManager::doCounterAttack(), CombatManager::doDodge(), CombatManager::doMiss(), EquilibriumCommand::doQueueCommand(), RegenerationCommand::doQueueCommand(), VitalizeCommand::doQueueCommand(), DragIncapacitatedPlayerCommand::drag(), server::zone::managers::minigames::FishingManagerImplementation::fishingProceed(), and AlertStateComponent::onEnter().
void SceneObject::switchZone (const String & newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID = 0)
Switches zone and position of this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, is in the new zone and in the new position }
Parameters
newTerrainName Name of the new terrain where the player will be inserted.
newPositionX new position X
newPositionZ new position Z
newPositionY new position Y
Definition at line 621 of file SceneObject.cpp.
References _getImplementation(), RPC_SWITCHZONE__STRING_FLOAT_FLOAT_FLOAT_LONG_, and server::zone::objects::scene::SceneObjectImplementation::switchZone().
Referenced by TeleportCommand::doQueueCommand(), NewbieSelectStartingLocationCommand::doQueueCommand(), TeleportToCommand::doQueueCommand(), BoardShuttleCommand::doQueueCommand(), server::zone::managers::player::PlayerManagerImplementation::ejectPlayerFromBuilding(), and server::zone::managers::player::PlayerManagerImplementation::sendPlayerToCloner().
void SceneObject::synchronizedUIListen (SceneObject * player, int value)
Calls the appropriate UI Listener Function
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
player CreatureObject using the item
value value from packet
Definition at line 282 of file SceneObject.cpp.
References _getImplementation(), RPC_SYNCHRONIZEDUILISTEN__SCENEOBJECT_INT_, and server::zone::objects::scene::SceneObjectImplementation::synchronizedUIListen().
void SceneObject::synchronizedUIStopListen (SceneObject * player, int value)
Calls the appropriate UI Stop Listener Function
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
player CreatureObject using the item
value value from packet
Definition at line 297 of file SceneObject.cpp.
References _getImplementation(), RPC_SYNCHRONIZEDUISTOPLISTEN__SCENEOBJECT_INT_, and server::zone::objects::scene::SceneObjectImplementation::synchronizedUIStopListen().
void SceneObject::teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID = 0)
Definition at line 639 of file SceneObject.cpp.
References _getImplementation(), RPC_TELEPORT__FLOAT_FLOAT_FLOAT_LONG_, and server::zone::objects::scene::SceneObjectImplementation::teleport().
Referenced by server::zone::managers::player::PlayerManagerImplementation::checkSpeedHackFirstTest(), server::zone::objects::building::BuildingObjectImplementation::destroyObjectFromDatabase(), DismountCommand::doQueueCommand(), SitServerCommand::doQueueCommand(), DragIncapacitatedPlayerCommand::drag(), ElevatorMenuComponent::handleObjectMenuSelect(), server::zone::objects::area::FsVillageAreaImplementation::notifyEnter(), ZoneComponent::notifyInsertToZone(), and DestroyStructureTask::run().
bool SceneObject::transferObject (SceneObject * object, int containmentType, bool notifyClient = false, bool allowOverflow = false)
Tries to add/link object
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be added to the current object
containmentType arrangement type that will be used to add the object
notifyClient if true in range objects will be updated with the change
Returns
returns true if the object has been successfully added
Definition at line 188 of file SceneObject.cpp.
References _getImplementation(), RPC_TRANSFEROBJECT__SCENEOBJECT_INT_BOOL_BOOL_, and server::zone::objects::scene::SceneObjectImplementation::transferObject().
Referenced by server::zone::objects::mission::ReconMissionObjectiveImplementation::activate(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::activate(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::activate(), ComponentSlot::add(), server::zone::managers::player::creation::PlayerCreationManager::addHair(), server::zone::managers::player::creation::PlayerCreationManager::addProfessionStartingItems(), server::zone::managers::player::creation::PlayerCreationManager::addRacialMods(), server::zone::managers::player::creation::PlayerCreationManager::addStartingItems(), server::zone::managers::player::creation::PlayerCreationManager::addStartingItemsInto(), server::zone::managers::player::creation::PlayerCreationManager::addStartingWeaponsInto(), server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), server::zone::objects::tangible::firework::FireworkObjectImplementation::completeLaunch(), server::zone::objects::installation::garage::GarageInstallationImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::scene::SceneObjectImplementation::createChildObjects(), server::zone::managers::creature::CreatureManagerImplementation::createCreatureChildrenObjects(), server::zone::managers::loot::LootManagerImplementation::createLoot(), server::zone::managers::minigames::FishingManagerImplementation::createMarker(), server::zone::managers::player::PlayerManagerImplementation::createSkippedTutorialBuilding(), server::zone::managers::minigames::FishingManagerImplementation::createSplash(), server::zone::managers::player::PlayerManagerImplementation::createTutorialBuilding(), server::zone::objects::intangible::VehicleControlDeviceImplementation::destroyObjectFromDatabase(), ProneCommand::doQueueCommand(), DismountCommand::doQueueCommand(), MountCommand::doQueueCommand(), CreateSpawningElementCommand::doQueueCommand(), AiStateComponent::findNextPosition(), server::zone::objects::creature::AiAgentImplementation::findNextPosition(), server::zone::objects::intangible::ShipControlDeviceImplementation::generateObject(), server::zone::managers::director::DirectorManager::giveControlDevice(), server::zone::managers::director::DirectorManager::giveItem(), server::zone::managers::mission::MissionManagerImplementation::handleMissionAccept(), ZoneComponent::insertChildObjectsToZone(), server::zone::managers::creature::CreatureManagerImplementation::placeCreature(), CityDecorationTask::placeDecoration(), server::zone::objects::player::sessions::vendor::CreateVendorSessionImplementation::randomizeVendorLooks(), server::zone::objects::player::PlayerObjectImplementation::reload(), server::zone::objects::creature::ai::AiActorImplementation::respawn(), server::zone::objects::creature::AiAgentImplementation::respawn(), ResourceSlot::returnToParents(), ComponentSlot::returnToParents(), InstallMissionTerminalSuiCallback::run(), SelectCharacterCallback::run(), EmptyHopperCallback::run(), server::zone::managers::minigames::FishingManagerImplementation::sendReward(), server::zone::objects::building::BuildingObjectImplementation::spawnChildSceneObject(), server::zone::objects::area::DynamicSpawnAreaImplementation::spawnCreature(), server::zone::objects::area::StaticSpawnAreaImplementation::spawnCreatures(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::spawnLair(), server::zone::objects::intangible::VehicleControlDeviceImplementation::spawnObject(), server::zone::objects::tangible::InstrumentImplementation::spawnOutside(), server::zone::managers::director::DirectorManager::spawnSceneObject(), server::zone::objects::intangible::ShipControlDeviceImplementation::storeObject(), ZoneComponent::switchZone(), server::zone::managers::objectcontroller::ObjectControllerImplementation::transferObject(), ImageDesignManager::updateHairObject(), ZoneComponent::updateZone(), and ZoneComponent::updateZoneWithParent().
void SceneObject::updateDirection (float fw, float fx, float fy, float fz)
Updates the direction of this object, and braodcasts DataTransform with the update
Definition at line 656 of file SceneObject.cpp.
References _getImplementation(), RPC_UPDATEDIRECTION__FLOAT_FLOAT_FLOAT_FLOAT_, and server::zone::objects::scene::SceneObjectImplementation::updateDirection().
Referenced by server::zone::objects::building::BuildingObjectImplementation::spawnChildCreature(), server::zone::objects::building::BuildingObjectImplementation::spawnChildCreaturesFromTemplate(), server::zone::managers::director::DirectorManager::spawnMobile(), and server::zone::managers::director::DirectorManager::spawnMobileRandom().
void SceneObject::updateDirection (float angleHeadingRadians)
Definition at line 673 of file SceneObject.cpp.
References _getImplementation(), RPC_UPDATEDIRECTION__FLOAT_, and server::zone::objects::scene::SceneObjectImplementation::updateDirection().
void SceneObject::updateToDatabase ()
Updates this object to database (calls updatesToDatabaseAllObjects())
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
startTask if true, queues a new update task
Definition at line 312 of file SceneObject.cpp.
References _getImplementation(), RPC_UPDATETODATABASE__, and server::zone::objects::scene::SceneObjectImplementation::updateToDatabase().
Referenced by server::zone::objects::player::PlayerObjectImplementation::addFriend(), DismountCommand::doQueueCommand(), MountCommand::doQueueCommand(), server::zone::objects::player::PlayerObjectImplementation::removeFriend(), ContainerComponent::removeObject(), InsertPowerSuiCallback::run(), and ContainerComponent::transferObject().
void SceneObject::updateToDatabaseAllObjects (bool startTask)
Updates this object and childre objects to database
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Parameters
startTask if true, queues a new update task
Definition at line 338 of file SceneObject.cpp.
References _getImplementation(), RPC_UPDATETODATABASEALLOBJECTS__BOOL_, and server::zone::objects::scene::SceneObjectImplementation::updateToDatabaseAllObjects().
void SceneObject::updateToDatabaseWithoutChildren ()
Updates only this object to database without updating children WARNING use only when necessary
Definition at line 325 of file SceneObject.cpp.
References _getImplementation(), RPC_UPDATETODATABASEWITHOUTCHILDREN__, and server::zone::objects::scene::SceneObjectImplementation::updateToDatabaseWithoutChildren().
void SceneObject::updateVehiclePosition (bool sendPackets)
Definition at line 1129 of file SceneObject.cpp.
References _getImplementation(), RPC_UPDATEVEHICLEPOSITION__BOOL_, and server::zone::objects::scene::SceneObjectImplementation::updateVehiclePosition().
Referenced by ZoneComponent::updateZone().
void SceneObject::updateZone (bool lightUpdate, bool sendPackets = true)
Updates position of this object to the rest of in range objects
Precondition
{ this object is locked}
Postcondition
{ this object is locked, in range objects are updated with the new position }
Parameters
lightUpdate if true a standalone message is sent to the in range objects
Definition at line 718 of file SceneObject.cpp.
References _getImplementation(), RPC_UPDATEZONE__BOOL_BOOL_, and server::zone::objects::scene::SceneObjectImplementation::updateZone().
Referenced by DragIncapacitatedPlayerCommand::drag(), ZoneComponent::teleport(), AiStateComponent::updateCurrentPosition(), and DataTransformCallback::updatePosition().
void SceneObject::updateZoneWithParent (SceneObject * newParent, bool lightUpdate, bool sendPackets = true)
Updates position and/or parent of this object and to the rest of in range objects
Precondition
{ this object is locked, newParent is a CellObject }
Postcondition
{this object is locked, in range objects are updated of the new position and parent }
Parameters
newParent cellObject where this object is
lightUpdate if true a standalone message is sent to the in range objects
Definition at line 733 of file SceneObject.cpp.
References _getImplementation(), RPC_UPDATEZONEWITHPARENT__SCENEOBJECT_BOOL_BOOL_, and server::zone::objects::scene::SceneObjectImplementation::updateZoneWithParent().
Referenced by DragIncapacitatedPlayerCommand::drag(), ZoneComponent::teleport(), AiStateComponent::updateCurrentPosition(), and DataTransformWithParentCallback::updatePosition().
Friends And Related Function Documentation
friend class SceneObjectHelper friend
Definition at line 1229 of file SceneObject.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/SceneObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/SceneObject.cpp