Core3: CombatAction Class Reference
CombatAction Class Reference
#include <CombatAction.h>
Public Member Functions
CombatAction (CreatureObject *attacker, CreatureObject *defender, uint32 animcrc, uint8 hit, uint8 trails, long weaponID=0)
CombatAction (CreatureObject *attacker, TangibleObject *defender, uint32 animcrc, uint8 hit, uint8 trails, long weaponID=0)
CombatAction (CreatureObject *attacker, uint32 animcrc)
CombatAction (CreatureObject *attacker, uint32 animcrc, long weaponID)
CombatAction (TangibleObject *attacker, CreatureObject *defender, uint32 animcrc, uint8 hit, long wpnID=0)
CombatAction (CreatureObject *attacker, CreatureObject *defender, uint32 animcrc, uint8 hit, long wpnID)
void updateDefenderSize ()
void addDefender (CreatureObject *defender, uint8 hit)
Public Member Functions inherited from ObjectControllerMessage
ObjectControllerMessage (uint64 objid, uint32 header1, uint32 header2, bool comp=true)
Private Attributes
int defenderSize
Detailed Description
Definition at line 50 of file CombatAction.h.
Constructor & Destructor Documentation
CombatAction::CombatAction (CreatureObject * attacker, CreatureObject * defender, uint32 animcrc, uint8 hit, uint8 trails, long weaponID = 0) inline
Definition at line 56 of file CombatAction.h.
References defenderSize, and SceneObject::getObjectID().
CombatAction::CombatAction (CreatureObject * attacker, TangibleObject * defender, uint32 animcrc, uint8 hit, uint8 trails, long weaponID = 0) inline
Definition at line 80 of file CombatAction.h.
References defenderSize, and SceneObject::getObjectID().
CombatAction::CombatAction (CreatureObject * attacker, uint32 animcrc) inline
Definition at line 104 of file CombatAction.h.
References defenderSize, and SceneObject::getObjectID().
CombatAction::CombatAction (CreatureObject * attacker, uint32 animcrc, long weaponID) inline
Definition at line 119 of file CombatAction.h.
References defenderSize, and SceneObject::getObjectID().
CombatAction::CombatAction (TangibleObject * attacker, CreatureObject * defender, uint32 animcrc, uint8 hit, long wpnID = 0) inline
Definition at line 135 of file CombatAction.h.
References defenderSize, and SceneObject::getObjectID().
CombatAction::CombatAction (CreatureObject * attacker, CreatureObject * defender, uint32 animcrc, uint8 hit, long wpnID) inline
Definition at line 156 of file CombatAction.h.
References defenderSize, and SceneObject::getObjectID().
Member Function Documentation
void CombatAction::addDefender (CreatureObject * defender, uint8 hit) inline
Definition at line 181 of file CombatAction.h.
References SceneObject::getObjectID(), and updateDefenderSize().
void CombatAction::updateDefenderSize () inline
Definition at line 177 of file CombatAction.h.
References defenderSize.
Referenced by addDefender().
Member Data Documentation
int CombatAction::defenderSize private
Definition at line 51 of file CombatAction.h.
Referenced by CombatAction(), and updateDefenderSize().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/object/CombatAction.h