Core3: server::zone::packets::chat::ChatRoomList Class Reference
server::zone::packets::chat::ChatRoomList Class Reference
#include <ChatRoomList.h>
Public Member Functions
ChatRoomList ()
void addChannel (ChatRoom *channel)
void insertChannelListCount ()
void addToUnknownListA (ChatRoom *room)
void addToUnknownListB ()
Private Attributes
int channelCounter
Detailed Description
Definition at line 63 of file ChatRoomList.h.
Constructor & Destructor Documentation
server::zone::packets::chat::ChatRoomList::ChatRoomList () inline
Definition at line 67 of file ChatRoomList.h.
References channelCounter.
Member Function Documentation
void server::zone::packets::chat::ChatRoomList::addChannel (ChatRoom * channel) inline
Definition at line 78 of file ChatRoomList.h.
References addToUnknownListA(), addToUnknownListB(), channelCounter, server::chat::room::ChatRoom::getCreator(), server::chat::room::ChatRoom::getFullPath(), server::chat::room::ChatRoom::getGalaxyName(), server::chat::room::ChatRoom::getOwner(), server::chat::room::ChatRoom::getRoomID(), and server::chat::room::ChatRoom::getTitle().
Referenced by server::chat::ChatManagerImplementation::populateRoomListMessage(), and server::chat::room::ChatRoomImplementation::sendTo().
void server::zone::packets::chat::ChatRoomList::addToUnknownListA (ChatRoom * room) inline
Definition at line 106 of file ChatRoomList.h.
Referenced by addChannel().
void server::zone::packets::chat::ChatRoomList::addToUnknownListB () inline
Definition at line 124 of file ChatRoomList.h.
Referenced by addChannel().
void server::zone::packets::chat::ChatRoomList::insertChannelListCount () inline
Definition at line 102 of file ChatRoomList.h.
References channelCounter.
Referenced by server::chat::ChatManagerImplementation::sendRoomList(), and server::chat::room::ChatRoomImplementation::sendTo().
Member Data Documentation
int server::zone::packets::chat::ChatRoomList::channelCounter private
Definition at line 64 of file ChatRoomList.h.
Referenced by addChannel(), ChatRoomList(), and insertChannelListCount().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/chat/ChatRoomList.h