Core3: server::zone::objects::scene::variables::ContainerPermissions Class Reference
server::zone::objects::scene::variables::ContainerPermissions Class Reference
#include <ContainerPermissions.h>
Public Member Functions
ContainerPermissions ()
bool hasPermission (const String &group, uint16 permission)
uint16 getAllowPermissions (const String &group)
uint16 getDenyPermissions (const String &group)
void setAllowPermission (const String &group, uint16 permission)
void setDenyPermission (const String &group, uint16 permission)
void clearAllowPermission (const String &group, uint16 permission)
void clearDenyPermission (const String &group, uint16 permission)
bool hasPermission (uint32 group, uint16 permission)
bool hasOwnerPermission (uint16 permission)
void setAllowPermission (uint32 group, uint16 permission)
void setDenyPermission (uint32 group, uint16 permission)
void clearAllowPermission (uint32 group, uint16 permission)
void clearDenyPermission (uint32 group, uint16 permission)
void setDefaultAllowPermission (uint16 permission)
void clearDefaultAllowPermission (uint16 permission)
void setDefaultDenyPermission (uint16 permission)
void clearDefaultDenyPermission (uint16 permission)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
uint64 getOwnerID ()
bool hasInheritPermissionsFromParent ()
uint16 getAllowPermissions (uint32 group)
uint16 getDenyPermissions (uint32 group)
uint32 getFullPermissions (uint32 group)
uint32 getFullPermissions (const String &group)
void setOwner (uint64 id)
void setInheritPermissionsFromParent (bool val)
Static Public Attributes
static const uint16 OPEN = 1
static const uint16 MOVEIN = 1 << 1
static const uint16 MOVEOUT = 1 << 2
static const uint16 MOVECONTAINER = 1 << 3
static const uint16 WALKIN = 1 << 4
static const uint16 MOVEVENDOR = 1 << 8
Vendors have special checks.
Private Attributes
HashTable< uint32, uint32 > groupPermissions
uint64 ownerID
bool inheritPermissionsFromParent
Detailed Description
Definition at line 22 of file ContainerPermissions.h.
Constructor & Destructor Documentation
ContainerPermissions::ContainerPermissions ()
Definition at line 10 of file ContainerPermissions.cpp.
References groupPermissions, and MOVECONTAINER.
Member Function Documentation
void ContainerPermissions::clearAllowPermission (const String & group, uint16 permission)
Definition at line 79 of file ContainerPermissions.cpp.
void ContainerPermissions::clearAllowPermission (uint32 group, uint16 permission)
Definition at line 121 of file ContainerPermissions.cpp.
References groupPermissions.
void ContainerPermissions::clearDefaultAllowPermission (uint16 permission)
Definition at line 28 of file ContainerPermissions.cpp.
References groupPermissions.
void ContainerPermissions::clearDefaultDenyPermission (uint16 permission)
Definition at line 49 of file ContainerPermissions.cpp.
References groupPermissions.
Referenced by server::zone::objects::intangible::ControlDeviceImplementation::ControlDeviceImplementation(), and server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::ManufactureSchematicImplementation().
void ContainerPermissions::clearDenyPermission (const String & group, uint16 permission)
Definition at line 83 of file ContainerPermissions.cpp.
Referenced by server::zone::objects::intangible::ControlDeviceImplementation::ControlDeviceImplementation(), and server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::ManufactureSchematicImplementation().
void ContainerPermissions::clearDenyPermission (uint32 group, uint16 permission)
Definition at line 132 of file ContainerPermissions.cpp.
References groupPermissions.
uint16 ContainerPermissions::getAllowPermissions (const String & group)
Definition at line 63 of file ContainerPermissions.cpp.
Referenced by ContainerComponent::checkContainerPermission().
uint16 server::zone::objects::scene::variables::ContainerPermissions::getAllowPermissions (uint32 group) inline
Definition at line 74 of file ContainerPermissions.h.
References groupPermissions.
uint16 ContainerPermissions::getDenyPermissions (const String & group)
Definition at line 67 of file ContainerPermissions.cpp.
Referenced by ContainerComponent::checkContainerPermission().
uint16 server::zone::objects::scene::variables::ContainerPermissions::getDenyPermissions (uint32 group) inline
Definition at line 78 of file ContainerPermissions.h.
References groupPermissions.
uint32 server::zone::objects::scene::variables::ContainerPermissions::getFullPermissions (uint32 group) inline
Definition at line 82 of file ContainerPermissions.h.
References groupPermissions.
uint32 server::zone::objects::scene::variables::ContainerPermissions::getFullPermissions (const String & group) inline
Definition at line 86 of file ContainerPermissions.h.
References groupPermissions.
uint64 server::zone::objects::scene::variables::ContainerPermissions::getOwnerID () inline
Definition at line 66 of file ContainerPermissions.h.
References ownerID.
Referenced by server::zone::objects::tangible::ContainerImplementation::canAddObject(), server::zone::objects::creature::CreatureImplementation::canHarvestMe(), LootContainerComponent::checkContainerPermission(), ContainerComponent::checkContainerPermission(), LootCommand::doQueueCommand(), and server::zone::managers::player::PlayerManagerImplementation::lootAll().
bool server::zone::objects::scene::variables::ContainerPermissions::hasInheritPermissionsFromParent () inline
Definition at line 70 of file ContainerPermissions.h.
References inheritPermissionsFromParent.
Referenced by ContainerComponent::checkContainerPermission(), server::zone::objects::cell::CellObjectImplementation::sendPermissionsTo(), server::zone::objects::building::BuildingObjectImplementation::sendTo(), and DataTransformWithParentCallback::updatePosition().
bool ContainerPermissions::hasOwnerPermission (uint16 permission)
Definition at line 96 of file ContainerPermissions.cpp.
References hasPermission().
Referenced by ContainerComponent::checkContainerPermission().
bool ContainerPermissions::hasPermission (const String & group, uint16 permission)
Definition at line 59 of file ContainerPermissions.cpp.
Referenced by hasOwnerPermission().
bool ContainerPermissions::hasPermission (uint32 group, uint16 permission)
Definition at line 87 of file ContainerPermissions.cpp.
References groupPermissions.
bool ContainerPermissions::parseFromBinaryStream (ObjectInputStream * stream)
Definition at line 150 of file ContainerPermissions.cpp.
References groupPermissions, inheritPermissionsFromParent, and ownerID.
void ContainerPermissions::setAllowPermission (const String & group, uint16 permission)
Definition at line 71 of file ContainerPermissions.cpp.
void ContainerPermissions::setAllowPermission (uint32 group, uint16 permission)
Definition at line 100 of file ContainerPermissions.cpp.
References groupPermissions.
void ContainerPermissions::setDefaultAllowPermission (uint16 permission)
Definition at line 17 of file ContainerPermissions.cpp.
References groupPermissions.
void ContainerPermissions::setDefaultDenyPermission (uint16 permission)
Definition at line 39 of file ContainerPermissions.cpp.
References groupPermissions.
Referenced by server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), and server::zone::objects::scene::SceneObjectImplementation::createChildObjects().
void ContainerPermissions::setDenyPermission (const String & group, uint16 permission)
Definition at line 75 of file ContainerPermissions.cpp.
Referenced by server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), and server::zone::objects::scene::SceneObjectImplementation::createChildObjects().
void ContainerPermissions::setDenyPermission (uint32 group, uint16 permission)
Definition at line 111 of file ContainerPermissions.cpp.
References groupPermissions.
void server::zone::objects::scene::variables::ContainerPermissions::setInheritPermissionsFromParent (bool val) inline
Definition at line 94 of file ContainerPermissions.h.
References inheritPermissionsFromParent.
Referenced by server::zone::objects::intangible::ControlDeviceImplementation::ControlDeviceImplementation(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), and server::zone::objects::scene::SceneObjectImplementation::createChildObjects().
void server::zone::objects::scene::variables::ContainerPermissions::setOwner (uint64 id) inline
Definition at line 90 of file ContainerPermissions.h.
References ownerID.
Referenced by server::zone::objects::tangible::weapon::WeaponObjectImplementation::createChildObjects(), server::zone::objects::building::BuildingObjectImplementation::createChildObjects(), server::zone::objects::creature::CreatureObjectImplementation::createChildObjects(), server::zone::objects::scene::SceneObjectImplementation::createChildObjects(), and server::zone::managers::minigames::FishingManagerImplementation::sendReward().
bool ContainerPermissions::toBinaryStream (ObjectOutputStream * stream)
Definition at line 142 of file ContainerPermissions.cpp.
References groupPermissions, inheritPermissionsFromParent, and ownerID.
Member Data Documentation
HashTable<uint32, uint32> server::zone::objects::scene::variables::ContainerPermissions::groupPermissions private
Definition at line 23 of file ContainerPermissions.h.
Referenced by clearAllowPermission(), clearDefaultAllowPermission(), clearDefaultDenyPermission(), clearDenyPermission(), ContainerPermissions(), getAllowPermissions(), getDenyPermissions(), getFullPermissions(), hasPermission(), parseFromBinaryStream(), setAllowPermission(), setDefaultAllowPermission(), setDefaultDenyPermission(), setDenyPermission(), and toBinaryStream().
bool server::zone::objects::scene::variables::ContainerPermissions::inheritPermissionsFromParent private
Definition at line 25 of file ContainerPermissions.h.
Referenced by hasInheritPermissionsFromParent(), parseFromBinaryStream(), setInheritPermissionsFromParent(), and toBinaryStream().
const uint16 server::zone::objects::scene::variables::ContainerPermissions::MOVECONTAINER = 1 << 3 static
Definition at line 31 of file ContainerPermissions.h.
Referenced by ContainerPermissions().
const uint16 server::zone::objects::scene::variables::ContainerPermissions::MOVEIN = 1 << 1 static
Definition at line 29 of file ContainerPermissions.h.
const uint16 server::zone::objects::scene::variables::ContainerPermissions::MOVEOUT = 1 << 2 static
Definition at line 30 of file ContainerPermissions.h.
const uint16 server::zone::objects::scene::variables::ContainerPermissions::MOVEVENDOR = 1 << 8 static
Vendors have special checks.
Definition at line 35 of file ContainerPermissions.h.
const uint16 server::zone::objects::scene::variables::ContainerPermissions::OPEN = 1 static
Definition at line 28 of file ContainerPermissions.h.
uint64 server::zone::objects::scene::variables::ContainerPermissions::ownerID private
Definition at line 24 of file ContainerPermissions.h.
Referenced by getOwnerID(), parseFromBinaryStream(), setOwner(), and toBinaryStream().
const uint16 server::zone::objects::scene::variables::ContainerPermissions::WALKIN = 1 << 4 static
Definition at line 32 of file ContainerPermissions.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/ContainerPermissions.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/ContainerPermissions.cpp