Core3: PaletteColorCustomizationVariable Class Reference
PaletteColorCustomizationVariable Class Reference
#include <PaletteColorCustomizationVariable.h>
Public Member Functions
PaletteColorCustomizationVariable ()
PaletteColorCustomizationVariable (int defIndex, const String &fileName)
PaletteColorCustomizationVariable (const PaletteColorCustomizationVariable &p)
~PaletteColorCustomizationVariable ()
PaletteColorCustomizationVariable & operator= (const PaletteColorCustomizationVariable &p)
String toString ()
bool parse (Chunk *source)
String getPaletteFileName ()
String getVariableName ()
Public Member Functions inherited from RangedIntCustomizationVariable
RangedIntCustomizationVariable ()
RangedIntCustomizationVariable (const RangedIntCustomizationVariable &m)
~RangedIntCustomizationVariable ()
int getDefaultValue ()
String toString ()
bool parse (Chunk *source)
String getVariableName ()
Public Member Functions inherited from CustomizationVariable
CustomizationVariable ()
CustomizationVariable (const CustomizationVariable &o)
Public Member Functions inherited from Param
Param ()
virtual ~Param ()
virtual bool parse (engine::util::Chunk *source)=0
uint32 getType ()
void setType (uint32 tp)
bool isBool ()
bool isFloat ()
bool isInteger ()
bool isString ()
bool isStringId ()
Protected Attributes
StringParam variableName
StringParam palettePathName
Protected Attributes inherited from RangedIntCustomizationVariable
StringParam variableName
IntegerParam minValueInclusive
IntegerParam defaultValue
IntegerParam maxValueExclusive
Additional Inherited Members
Static Public Attributes inherited from Param
static const uint32 BOOL = 0x01
static const uint32 FLOAT = 0x02
static const uint32 INTEGER = 0x04
static const uint32 STRING = 0x08
static const uint32 STRINGID = 0x10
static const uint32 VECTOR = 0x12
static const uint32 DYNAMICVARIABLE = 0x014
static const uint32 TRIGGERVOLUME = 0x16
static const uint32 PALETTECOLORCUSTOMIZATION = 0x18
static const uint32 RANGEDINTCUSTOMIZATIONVARIABLE = 0x20
static const uint32 CUSTOMIZATIONVARIABLEMAP = 0x22
Detailed Description
Definition at line 18 of file PaletteColorCustomizationVariable.h.
Constructor & Destructor Documentation
PaletteColorCustomizationVariable::PaletteColorCustomizationVariable () inline
Definition at line 24 of file PaletteColorCustomizationVariable.h.
References Param::PALETTECOLORCUSTOMIZATION, and Param::setType().
PaletteColorCustomizationVariable::PaletteColorCustomizationVariable (int defIndex, const String & fileName) inline
Definition at line 28 of file PaletteColorCustomizationVariable.h.
References RangedIntCustomizationVariable::defaultValue, Param::PALETTECOLORCUSTOMIZATION, palettePathName, and Param::setType().
PaletteColorCustomizationVariable::PaletteColorCustomizationVariable (const PaletteColorCustomizationVariable & p) inline
Definition at line 34 of file PaletteColorCustomizationVariable.h.
References Param::PALETTECOLORCUSTOMIZATION, palettePathName, Param::setType(), and variableName.
PaletteColorCustomizationVariable::~PaletteColorCustomizationVariable () inline
Definition at line 41 of file PaletteColorCustomizationVariable.h.
Member Function Documentation
String PaletteColorCustomizationVariable::getPaletteFileName () inline
Definition at line 111 of file PaletteColorCustomizationVariable.h.
References TemplateBase< V >::get(), and palettePathName.
Referenced by ImageDesignManager::validatePalette().
String PaletteColorCustomizationVariable::getVariableName () inline
Definition at line 119 of file PaletteColorCustomizationVariable.h.
References TemplateBase< V >::get(), and variableName.
PaletteColorCustomizationVariable& PaletteColorCustomizationVariable::operator= (const PaletteColorCustomizationVariable & p) inline
Definition at line 45 of file PaletteColorCustomizationVariable.h.
References palettePathName, and variableName.
bool PaletteColorCustomizationVariable::parse (Chunk * source) inline
Definition at line 71 of file PaletteColorCustomizationVariable.h.
References RangedIntCustomizationVariable::defaultValue, palettePathName, IntegerParam::parse(), StringParam::parse(), and variableName.
Referenced by PaletteColorCustomizationVariables::parseType1().
String PaletteColorCustomizationVariable::toString () inline virtual
Implements Param.
Definition at line 55 of file PaletteColorCustomizationVariable.h.
References RangedIntCustomizationVariable::defaultValue, palettePathName, StringParam::toString(), IntegerParam::toString(), and variableName.
Member Data Documentation
StringParam PaletteColorCustomizationVariable::palettePathName protected
Definition at line 21 of file PaletteColorCustomizationVariable.h.
Referenced by getPaletteFileName(), operator=(), PaletteColorCustomizationVariable(), parse(), and toString().
StringParam PaletteColorCustomizationVariable::variableName protected
Definition at line 20 of file PaletteColorCustomizationVariable.h.
Referenced by getVariableName(), operator=(), PaletteColorCustomizationVariable(), parse(), and toString().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/params/PaletteColorCustomizationVariable.h