Core3: server::zone::objects::player::sessions::ImageDesignSessionImplementation Class Reference
server::zone::objects::player::sessions::ImageDesignSessionImplementation Class Reference
#include <ImageDesignSession.h>
Public Member Functions
ImageDesignSessionImplementation (CreatureObject *parent)
ImageDesignSessionImplementation (DummyConstructorParameter *param)
void initializeTransientMembers ()
void startImageDesign (CreatureObject *designer, CreatureObject *targetPlayer)
void updateImageDesign (CreatureObject *updater, unsigned long long designer, unsigned long long targetPlayer, unsigned long long tent, int type, const ImageDesignData &data)
void cancelImageDesign (unsigned long long designer, unsigned long long targetPlayer, unsigned long long tent, int type, const ImageDesignData &data)
int initializeSession ()
int doPayment ()
int cancelSession ()
int clearSession ()
void clearIdTimeoutEvent ()
void checkDequeueEvent (SceneObject *scene)
void queueIdTimeoutEvent ()
void dequeueIdTimeoutEvent ()
void sessionTimeout ()
operator const ImageDesignSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< ImageDesignSession * > _this
Protected Member Functions
virtual ~ImageDesignSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > designerCreature
ManagedWeakReference
< CreatureObject * > targetCreature
ImageDesignData imageDesignData
ManagedReference
< TangibleObject * > hairObject
ManagedReference
< ImageDesignPositionObserver * > positionObserver
Reference
< ImageDesignTimeoutEvent * > idTimeoutEvent
ReadWriteLock idTimeoutLock
Friends
class ImageDesignSession
Detailed Description
Definition at line 175 of file ImageDesignSession.h.
Constructor & Destructor Documentation
ImageDesignSessionImplementation::ImageDesignSessionImplementation (CreatureObject * parent)
Definition at line 387 of file ImageDesignSession.cpp.
References _initializeImplementation(), and initializeSession().
ImageDesignSessionImplementation::ImageDesignSessionImplementation (DummyConstructorParameter * param)
Definition at line 213 of file ImageDesignSession.cpp.
References _initializeImplementation().
ImageDesignSessionImplementation::~ImageDesignSessionImplementation () protected virtual
Definition at line 218 of file ImageDesignSession.cpp.
Member Function Documentation
DistributedObjectStub * ImageDesignSessionImplementation::_getStub ()
Definition at line 238 of file ImageDesignSession.cpp.
References _this.
void ImageDesignSessionImplementation::_initializeImplementation () protected
Definition at line 225 of file ImageDesignSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ImageDesignSessionImplementation().
void ImageDesignSessionImplementation::_serializationHelperMethod () protected
Definition at line 274 of file ImageDesignSession.cpp.
Referenced by _initializeImplementation().
void ImageDesignSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 233 of file ImageDesignSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::ImageDesignSession::ImageDesignSession().
void ImageDesignSessionImplementation::cancelImageDesign (unsigned long long designer, unsigned long long targetPlayer, unsigned long long tent, int type, const ImageDesignData & data)
Definition at line 309 of file ImageDesignSessionImplementation.cpp.
References cancelSession(), designerCreature, imageDesignData, ImageDesignData::insertToMessage(), and targetCreature.
Referenced by server::zone::objects::player::sessions::ImageDesignSession::cancelImageDesign(), and sessionTimeout().
int ImageDesignSessionImplementation::cancelSession ()
Definition at line 26 of file ImageDesignSessionImplementation.cpp.
References dequeueIdTimeoutEvent(), designerCreature, SessionFacadeType::IMAGEDESIGN, ObserverEventType::POSITIONCHANGED, positionObserver, and targetCreature.
Referenced by cancelImageDesign(), server::zone::objects::player::sessions::ImageDesignSession::cancelSession(), and doPayment().
void ImageDesignSessionImplementation::checkDequeueEvent (SceneObject * scene)
Definition at line 257 of file ImageDesignSessionImplementation.cpp.
References dequeueIdTimeoutEvent(), designerCreature, SceneObjectType::SALONBUILDING, and targetCreature.
Referenced by server::zone::objects::player::sessions::ImageDesignSession::checkDequeueEvent().
void ImageDesignSessionImplementation::clearIdTimeoutEvent ()
Definition at line 415 of file ImageDesignSession.cpp.
References idTimeoutEvent, and idTimeoutLock.
Referenced by server::zone::objects::player::sessions::ImageDesignSession::clearIdTimeoutEvent().
int ImageDesignSessionImplementation::clearSession ()
Definition at line 410 of file ImageDesignSession.cpp.
Referenced by server::zone::objects::player::sessions::ImageDesignSession::clearSession().
void ImageDesignSessionImplementation::dequeueIdTimeoutEvent ()
Definition at line 442 of file ImageDesignSession.cpp.
References idTimeoutEvent, and idTimeoutLock.
Referenced by cancelSession(), checkDequeueEvent(), server::zone::objects::player::sessions::ImageDesignSession::dequeueIdTimeoutEvent(), and updateImageDesign().
int ImageDesignSessionImplementation::doPayment ()
Definition at line 232 of file ImageDesignSessionImplementation.cpp.
References cancelSession(), designerCreature, ImageDesignData::getRequiredPayment(), imageDesignData, and targetCreature.
Referenced by server::zone::objects::player::sessions::ImageDesignSession::doPayment(), and updateImageDesign().
void ImageDesignSessionImplementation::finalize () protected
Definition at line 222 of file ImageDesignSession.cpp.
int ImageDesignSessionImplementation::initializeSession ()
Definition at line 397 of file ImageDesignSession.cpp.
References designerCreature, idTimeoutEvent, positionObserver, and targetCreature.
Referenced by ImageDesignSessionImplementation(), and server::zone::objects::player::sessions::ImageDesignSession::initializeSession().
void ImageDesignSessionImplementation::initializeTransientMembers ()
Definition at line 22 of file ImageDesignSessionImplementation.cpp.
Referenced by server::zone::objects::player::sessions::ImageDesignSession::initializeTransientMembers(), and readObject().
void ImageDesignSessionImplementation::lock (bool doLock = true) protected
Definition at line 246 of file ImageDesignSession.cpp.
References _this.
void ImageDesignSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 250 of file ImageDesignSession.cpp.
References _this.
ImageDesignSessionImplementation::operator const ImageDesignSession * ()
Definition at line 242 of file ImageDesignSession.cpp.
void ImageDesignSessionImplementation::queueIdTimeoutEvent ()
Definition at line 424 of file ImageDesignSession.cpp.
References _this, idTimeoutEvent, and idTimeoutLock.
Referenced by server::zone::objects::player::sessions::ImageDesignSession::queueIdTimeoutEvent().
void ImageDesignSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 281 of file ImageDesignSession.cpp.
References initializeTransientMembers(), and readObjectMember().
bool ImageDesignSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 300 of file ImageDesignSession.cpp.
References designerCreature, hairObject, imageDesignData, positionObserver, and targetCreature.
Referenced by readObject().
void ImageDesignSessionImplementation::rlock (bool doLock = true) protected
Definition at line 254 of file ImageDesignSession.cpp.
References _this.
void ImageDesignSessionImplementation::runlock (bool doLock = true) protected
Definition at line 270 of file ImageDesignSession.cpp.
References _this.
void ImageDesignSessionImplementation::sessionTimeout ()
Definition at line 279 of file ImageDesignSessionImplementation.cpp.
References cancelImageDesign(), designerCreature, imageDesignData, ImageDesignData::isAcceptedByDesigner(), SceneObjectType::SALONBUILDING, and targetCreature.
Referenced by server::zone::objects::player::sessions::ImageDesignSession::sessionTimeout().
void ImageDesignSessionImplementation::startImageDesign (CreatureObject * designer, CreatureObject * targetPlayer)
Starts an ImageDesign session between the designer and the target player.
Parameters
designer The image designer.
targetPlayer The recipient of the image designing.
type Unknown type specifier (needs more research)
Precondition
designer and targetPlayer are locked
Postcondition
designer and targetPlayer are locked
Definition at line 49 of file ImageDesignSessionImplementation.cpp.
References _this, server::zone::objects::scene::SceneObject::addActiveSession(), designerCreature, server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::scene::SceneObject::getSlottedObject(), idTimeoutEvent, SessionFacadeType::IMAGEDESIGN, ObserverEventType::POSITIONCHANGED, positionObserver, SceneObjectType::SALONBUILDING, server::zone::objects::creature::CreatureObject::sendMessage(), and targetCreature.
Referenced by server::zone::objects::player::sessions::ImageDesignSession::startImageDesign().
void ImageDesignSessionImplementation::unlock (bool doLock = true) protected
Definition at line 266 of file ImageDesignSession.cpp.
References _this.
void ImageDesignSessionImplementation::updateImageDesign (CreatureObject * updater, unsigned long long designer, unsigned long long targetPlayer, unsigned long long tent, int type, const ImageDesignData & data)
When a change is made by the designer, the target's window needs to be notified, and vice versa.
Parameters
designer The object id of the designer.
targetPlayer The target player's object id.
tent The object id of the salon tent being used.
type The type of something - unknown atm.
data The image design data associated with this update request.
Definition at line 101 of file ImageDesignSessionImplementation.cpp.
References _this, server::zone::managers::player::PlayerManager::awardExperience(), ImageDesignManager::createHairObject(), dequeueIdTimeoutEvent(), designerCreature, doPayment(), server::zone::objects::scene::SceneObject::dropActiveSession(), ImageDesignData::getBodyAttributesMap(), ImageDesignData::getColorAttributesMap(), ImageDesignData::getHairCustomizationString(), ImageDesignData::getHairTemplate(), server::zone::objects::scene::SceneObject::getObjectID(), hairObject, idTimeoutEvent, SessionFacadeType::IMAGEDESIGN, imageDesignData, ImageDesignData::insertToMessage(), ImageDesignData::isAcceptedByDesigner(), ImageDesignData::isAcceptedByTarget(), ImageDesignData::isStatMigrationRequested(), SessionFacadeType::MIGRATESTATS, server::zone::objects::player::sessions::MigrateStatsSession::migrateStats(), SceneObjectType::SALONBUILDING, server::zone::objects::creature::CreatureObject::sendMessage(), targetCreature, ImageDesignManager::updateColorCustomization(), ImageDesignManager::updateCustomization(), and ImageDesignManager::updateHairObject().
Referenced by server::zone::objects::player::sessions::ImageDesignSession::updateImageDesign().
void ImageDesignSessionImplementation::wlock (bool doLock = true) protected
Definition at line 258 of file ImageDesignSession.cpp.
References _this.
void ImageDesignSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 262 of file ImageDesignSession.cpp.
References _this.
void ImageDesignSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 330 of file ImageDesignSession.cpp.
References writeObjectMembers().
int ImageDesignSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 337 of file ImageDesignSession.cpp.
References designerCreature, hairObject, imageDesignData, positionObserver, and targetCreature.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ImageDesignSession friend
Definition at line 272 of file ImageDesignSession.h.
Member Data Documentation
WeakReference<ImageDesignSession*> server::zone::objects::player::sessions::ImageDesignSessionImplementation::_this
Definition at line 238 of file ImageDesignSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), queueIdTimeoutEvent(), rlock(), runlock(), startImageDesign(), unlock(), updateImageDesign(), and wlock().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sessions::ImageDesignSessionImplementation::designerCreature protected
Definition at line 177 of file ImageDesignSession.h.
Referenced by cancelImageDesign(), cancelSession(), checkDequeueEvent(), doPayment(), initializeSession(), readObjectMember(), sessionTimeout(), startImageDesign(), updateImageDesign(), and writeObjectMembers().
ManagedReference<TangibleObject* > server::zone::objects::player::sessions::ImageDesignSessionImplementation::hairObject protected
Definition at line 183 of file ImageDesignSession.h.
Referenced by readObjectMember(), updateImageDesign(), and writeObjectMembers().
Reference<ImageDesignTimeoutEvent* > server::zone::objects::player::sessions::ImageDesignSessionImplementation::idTimeoutEvent protected
Definition at line 187 of file ImageDesignSession.h.
Referenced by clearIdTimeoutEvent(), dequeueIdTimeoutEvent(), initializeSession(), queueIdTimeoutEvent(), startImageDesign(), and updateImageDesign().
ReadWriteLock server::zone::objects::player::sessions::ImageDesignSessionImplementation::idTimeoutLock protected
Definition at line 189 of file ImageDesignSession.h.
Referenced by clearIdTimeoutEvent(), dequeueIdTimeoutEvent(), and queueIdTimeoutEvent().
ImageDesignData server::zone::objects::player::sessions::ImageDesignSessionImplementation::imageDesignData protected
Definition at line 181 of file ImageDesignSession.h.
Referenced by cancelImageDesign(), doPayment(), readObjectMember(), sessionTimeout(), updateImageDesign(), and writeObjectMembers().
ManagedReference<ImageDesignPositionObserver* > server::zone::objects::player::sessions::ImageDesignSessionImplementation::positionObserver protected
Definition at line 185 of file ImageDesignSession.h.
Referenced by cancelSession(), initializeSession(), readObjectMember(), startImageDesign(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sessions::ImageDesignSessionImplementation::targetCreature protected
Definition at line 179 of file ImageDesignSession.h.
Referenced by cancelImageDesign(), cancelSession(), checkDequeueEvent(), doPayment(), initializeSession(), readObjectMember(), sessionTimeout(), startImageDesign(), updateImageDesign(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignSession.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignSessionImplementation.cpp