Core3: server::zone::managers::director::ScreenPlayObserverAdapter Class Reference
server::zone::managers::director::ScreenPlayObserverAdapter Class Reference
#include <ScreenPlayObserver.h>
Public Member Functions
ScreenPlayObserverAdapter (ScreenPlayObserver *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void setScreenPlay (const String &screen)
void setScreenKey (const String &screenKey)
String getScreenPlay ()
String getScreenKey ()
Detailed Description
Definition at line 122 of file ScreenPlayObserver.h.
Constructor & Destructor Documentation
ScreenPlayObserverAdapter::ScreenPlayObserverAdapter (ScreenPlayObserver * impl)
Definition at line 294 of file ScreenPlayObserver.cpp.
Member Function Documentation
String ScreenPlayObserverAdapter::getScreenKey ()
Definition at line 349 of file ScreenPlayObserver.cpp.
Referenced by invokeMethod().
String ScreenPlayObserverAdapter::getScreenPlay ()
Definition at line 345 of file ScreenPlayObserver.cpp.
Referenced by invokeMethod().
void ScreenPlayObserverAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 297 of file ScreenPlayObserver.cpp.
References getScreenKey(), getScreenPlay(), notifyObserverEvent(), RPC_GETSCREENKEY__, RPC_GETSCREENPLAY__, RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_, RPC_SETSCREENKEY__STRING_, RPC_SETSCREENPLAY__STRING_, setScreenKey(), and setScreenPlay().
int ScreenPlayObserverAdapter::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 333 of file ScreenPlayObserver.cpp.
Referenced by invokeMethod().
void ScreenPlayObserverAdapter::setScreenKey (const String & screenKey)
Definition at line 341 of file ScreenPlayObserver.cpp.
Referenced by invokeMethod().
void ScreenPlayObserverAdapter::setScreenPlay (const String & screen)
Definition at line 337 of file ScreenPlayObserver.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/ScreenPlayObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/ScreenPlayObserver.cpp