Core3: TaxPayMailTask Class Reference
TaxPayMailTask Class Reference
#include <TaxPayMailTask.h>
Public Member Functions
TaxPayMailTask (int tax, const String &mayor, ManagedReference< ChatManager * > chat, ManagedReference< CityRegion * > cityRegion)
void run ()
void addCitizen (CreatureObject *citizen)
Private Attributes
Vector< ManagedReference
< CreatureObject * > > citizens
String mayorName
ManagedReference< ChatManager * > chatManager
ManagedReference< CityRegion * > city
int incomeTax
Detailed Description
Definition at line 15 of file TaxPayMailTask.h.
Constructor & Destructor Documentation
TaxPayMailTask::TaxPayMailTask (int tax, const String & mayor, ManagedReference< ChatManager * > chat, ManagedReference< CityRegion * > cityRegion) inline
Definition at line 23 of file TaxPayMailTask.h.
References chatManager, city, incomeTax, and mayorName.
Member Function Documentation
void TaxPayMailTask::addCitizen (CreatureObject * citizen) inline
Definition at line 71 of file TaxPayMailTask.h.
References citizens.
void TaxPayMailTask::run () inline
Definition at line 30 of file TaxPayMailTask.h.
References chatManager, citizens, city, server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getFirstName(), incomeTax, mayorName, server::chat::StringIdChatParameter::setDI(), server::zone::objects::scene::variables::StringId::setStringId(), server::chat::StringIdChatParameter::setTO(), and server::zone::objects::creature::CreatureObject::subtractBankCredits().
Member Data Documentation
ManagedReference<ChatManager*> TaxPayMailTask::chatManager private
Definition at line 18 of file TaxPayMailTask.h.
Referenced by run(), and TaxPayMailTask().
Vector<ManagedReference<CreatureObject*> > TaxPayMailTask::citizens private
Definition at line 16 of file TaxPayMailTask.h.
Referenced by addCitizen(), and run().
ManagedReference<CityRegion*> TaxPayMailTask::city private
Definition at line 19 of file TaxPayMailTask.h.
Referenced by run(), and TaxPayMailTask().
int TaxPayMailTask::incomeTax private
Definition at line 21 of file TaxPayMailTask.h.
Referenced by run(), and TaxPayMailTask().
String TaxPayMailTask::mayorName private
Definition at line 17 of file TaxPayMailTask.h.
Referenced by run(), and TaxPayMailTask().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/city/TaxPayMailTask.h