Core3: server::zone::managers::creature::DnaManager Class Reference
server::zone::managers::creature::DnaManager Class Reference
#include <DnaManager.h>
Public Member Functions
DnaManager ()
virtual ~DnaManager ()
void loadSampleData ()
int generateXp (int creatureLevel)
int generateScoreFor (int stat, int cl, int quality)
void generateSample (Creature *creature, CreatureObject *player, int quality)
Static Public Member Functions
static int addRange (lua_State *L)
static int addQualityTemplate (lua_State *L)
Static Public Attributes
static const int FORTITUDE = 1
static const int ENDURANCE = 2
static const int CLEVERNESS = 3
static const int INTELLIGENCE = 4
static const int DEXTERITY = 5
static const int HARDINESS = 6
static const int DEPENDABILITY = 7
static const int COURAGE = 8
static const int POWER = 9
static const int FIERCENESS = 10
Protected Attributes
HashTable< uint32,
DnaSampleRange * > dexerity
HashTable< uint32,
DnaSampleRange * > fortitude
HashTable< uint32,
DnaSampleRange * > endurance
HashTable< uint32,
DnaSampleRange * > intelligence
HashTable< uint32,
DnaSampleRange * > hardiness
HashTable< uint32,
DnaSampleRange * > power
HashTable< uint32,
DnaSampleRange * > cleverness
HashTable< uint32,
DnaSampleRange * > courage
HashTable< uint32,
DnaSampleRange * > dependency
HashTable< uint32,
DnaSampleRange * > fierceness
HashTable< int, uint32 > qualityTemplates
Lua * lua
Static Protected Attributes
static AtomicInteger loadedDnaData
Detailed Description
Definition at line 21 of file DnaManager.h.
Constructor & Destructor Documentation
DnaManager::DnaManager ()
Definition at line 22 of file DnaManager.cpp.
References addQualityTemplate(), addRange(), CLEVERNESS, COURAGE, DEPENDABILITY, DEXTERITY, ENDURANCE, FIERCENESS, FORTITUDE, HARDINESS, INTELLIGENCE, lua, and POWER.
DnaManager::~DnaManager () virtual
Definition at line 39 of file DnaManager.cpp.
Member Function Documentation
int DnaManager::addQualityTemplate (lua_State * L) static
Definition at line 98 of file DnaManager.cpp.
Referenced by DnaManager().
int DnaManager::addRange (lua_State * L) static
Definition at line 105 of file DnaManager.cpp.
References CLEVERNESS, COURAGE, DEPENDABILITY, DEXTERITY, ENDURANCE, FIERCENESS, FORTITUDE, HARDINESS, INTELLIGENCE, loadedDnaData, and POWER.
Referenced by DnaManager().
void DnaManager::generateSample (Creature * creature, CreatureObject * player, int quality)
Definition at line 164 of file DnaManager.cpp.
References CLEVERNESS, COURAGE, server::zone::ZoneServer::createObject(), DEPENDABILITY, DEXTERITY, ENDURANCE, FIERCENESS, FORTITUDE, server::zone::managers::crafting::CraftingManager::generateSerial(), server::zone::templates::mobile::CreatureTemplate::getAcid(), server::zone::templates::mobile::CreatureTemplate::getArmor(), server::zone::templates::mobile::CreatureTemplate::getAttacks(), server::zone::templates::mobile::CreatureTemplate::getBlast(), server::zone::templates::mobile::CreatureTemplate::getCold(), CreatureAttackMap::getCommand(), server::zone::ZoneServer::getCraftingManager(), server::zone::objects::creature::AiAgent::getCreatureTemplate(), server::zone::templates::mobile::CreatureTemplate::getElectricity(), server::zone::templates::mobile::CreatureTemplate::getEnergy(), server::zone::templates::mobile::CreatureTemplate::getFerocity(), server::zone::objects::scene::variables::StringId::getFullPath(), server::zone::templates::mobile::CreatureTemplate::getHeat(), server::zone::templates::mobile::CreatureTemplate::getKinetic(), server::zone::objects::tangible::TangibleObject::getLevel(), server::zone::templates::mobile::CreatureTemplate::getLightSaber(), server::zone::objects::scene::SceneObject::getObjectName(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::templates::mobile::CreatureTemplate::getStun(), server::zone::templates::mobile::CreatureTemplate::getWeapons(), server::zone::objects::scene::SceneObject::getZoneServer(), HARDINESS, INTELLIGENCE, POWER, qualityTemplates, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::creature::CreatureObject::setPosture(), and CreaturePosture::UPRIGHT.
int DnaManager::generateScoreFor (int stat, int cl, int quality)
Definition at line 64 of file DnaManager.cpp.
References CLEVERNESS, COURAGE, DEPENDABILITY, DEXTERITY, ENDURANCE, FIERCENESS, FORTITUDE, HARDINESS, INTELLIGENCE, and POWER.
int DnaManager::generateXp (int creatureLevel)
Definition at line 56 of file DnaManager.cpp.
void DnaManager::loadSampleData ()
Definition at line 43 of file DnaManager.cpp.
References lua.
Member Data Documentation
HashTable<uint32, DnaSampleRange* > server::zone::managers::creature::DnaManager::cleverness protected
Definition at line 29 of file DnaManager.h.
const int server::zone::managers::creature::DnaManager::CLEVERNESS = 3 static
Definition at line 45 of file DnaManager.h.
Referenced by addRange(), DnaManager(), generateSample(), and generateScoreFor().
HashTable<uint32, DnaSampleRange* > server::zone::managers::creature::DnaManager::courage protected
Definition at line 30 of file DnaManager.h.
const int server::zone::managers::creature::DnaManager::COURAGE = 8 static
Definition at line 50 of file DnaManager.h.
Referenced by addRange(), DnaManager(), generateSample(), and generateScoreFor().
const int server::zone::managers::creature::DnaManager::DEPENDABILITY = 7 static
Definition at line 49 of file DnaManager.h.
Referenced by addRange(), DnaManager(), generateSample(), and generateScoreFor().
HashTable<uint32, DnaSampleRange* > server::zone::managers::creature::DnaManager::dependency protected
Definition at line 31 of file DnaManager.h.
HashTable<uint32, DnaSampleRange* > server::zone::managers::creature::DnaManager::dexerity protected
Definition at line 23 of file DnaManager.h.
const int server::zone::managers::creature::DnaManager::DEXTERITY = 5 static
Definition at line 47 of file DnaManager.h.
Referenced by addRange(), DnaManager(), generateSample(), and generateScoreFor().
HashTable<uint32, DnaSampleRange* > server::zone::managers::creature::DnaManager::endurance protected
Definition at line 25 of file DnaManager.h.
const int server::zone::managers::creature::DnaManager::ENDURANCE = 2 static
Definition at line 44 of file DnaManager.h.
Referenced by addRange(), DnaManager(), generateSample(), and generateScoreFor().
HashTable<uint32, DnaSampleRange* > server::zone::managers::creature::DnaManager::fierceness protected
Definition at line 32 of file DnaManager.h.
const int server::zone::managers::creature::DnaManager::FIERCENESS = 10 static
Definition at line 52 of file DnaManager.h.
Referenced by addRange(), DnaManager(), generateSample(), and generateScoreFor().
HashTable<uint32, DnaSampleRange* > server::zone::managers::creature::DnaManager::fortitude protected
Definition at line 24 of file DnaManager.h.
const int server::zone::managers::creature::DnaManager::FORTITUDE = 1 static
Definition at line 43 of file DnaManager.h.
Referenced by addRange(), DnaManager(), generateSample(), and generateScoreFor().
HashTable<uint32, DnaSampleRange* > server::zone::managers::creature::DnaManager::hardiness protected
Definition at line 27 of file DnaManager.h.
const int server::zone::managers::creature::DnaManager::HARDINESS = 6 static
Definition at line 48 of file DnaManager.h.
Referenced by addRange(), DnaManager(), generateSample(), and generateScoreFor().
HashTable<uint32, DnaSampleRange* > server::zone::managers::creature::DnaManager::intelligence protected
Definition at line 26 of file DnaManager.h.
const int server::zone::managers::creature::DnaManager::INTELLIGENCE = 4 static
Definition at line 46 of file DnaManager.h.
Referenced by addRange(), DnaManager(), generateSample(), and generateScoreFor().
AtomicInteger DnaManager::loadedDnaData static protected
Definition at line 35 of file DnaManager.h.
Referenced by addRange().
Lua* server::zone::managers::creature::DnaManager::lua protected
Definition at line 34 of file DnaManager.h.
Referenced by DnaManager(), and loadSampleData().
HashTable<uint32, DnaSampleRange* > server::zone::managers::creature::DnaManager::power protected
Definition at line 28 of file DnaManager.h.
const int server::zone::managers::creature::DnaManager::POWER = 9 static
Definition at line 51 of file DnaManager.h.
Referenced by addRange(), DnaManager(), generateSample(), and generateScoreFor().
HashTable<int,uint32> server::zone::managers::creature::DnaManager::qualityTemplates protected
Definition at line 33 of file DnaManager.h.
Referenced by generateSample().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/DnaManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/DnaManager.cpp