Core3: StringFile Class Reference
StringFile Class Reference
#include <StringFile.h>
Public Member Functions
StringFile ()
~StringFile ()
bool load (ObjectInputStream *inputFile)
HashTable< String,
UnicodeString > * getStringMap ()
UnicodeString getValue (const String &id)
Protected Member Functions
bool checkHeader (ObjectInputStream *inputFile)
Private Attributes
HashTable< String, UnicodeString > stringMap
Detailed Description
Definition at line 13 of file StringFile.h.
Constructor & Destructor Documentation
StringFile::StringFile ()
Definition at line 10 of file StringFile.cpp.
StringFile::~StringFile ()
Definition at line 14 of file StringFile.cpp.
Member Function Documentation
bool StringFile::checkHeader (ObjectInputStream * inputFile) protected
Definition at line 92 of file StringFile.cpp.
Referenced by load().
HashTable<String, UnicodeString>* StringFile::getStringMap () inline
Definition at line 22 of file StringFile.h.
References stringMap.
Referenced by server::zone::managers::stringid::StringIdManager::populateDatabase().
UnicodeString StringFile::getValue (const String & id) inline
Definition at line 26 of file StringFile.h.
References stringMap.
bool StringFile::load (ObjectInputStream * inputFile)
Definition at line 18 of file StringFile.cpp.
References checkHeader(), and stringMap.
Referenced by server::zone::managers::stringid::StringIdManager::populateDatabase().
Member Data Documentation
HashTable<String, UnicodeString> StringFile::stringMap private
Definition at line 14 of file StringFile.h.
Referenced by getStringMap(), getValue(), and load().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/string/StringFile.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/string/StringFile.cpp