Core3: TurretFireTask Class Reference
TurretFireTask Class Reference
#include <TurretFireTask.h>
Public Member Functions
TurretFireTask (TangibleObject *turret, SceneObject *victim, bool isManualFire=false)
void run ()
void executeCommand (TurretDataComponent *turretData, CombatQueueCommand *combatCommand)
void doAutoFire (TurretDataComponent *turretData, WeaponObject *weapon, SceneObject *defenderObject)
void handleManualFire (TurretDataComponent *turretData, WeaponObject *weapon, SceneObject *defenderObject)
void checkTurretController (TurretDataComponent *turretData)
String getTargetName (SceneObject *target)
void closeControls (CreatureObject *controllerCharacter, TurretDataComponent *turretData)
bool checkTarget (TurretDataComponent *turretData)
bool isManualFireTask ()
void setManualTask (bool val)
Private Attributes
ManagedReference
< TangibleObject * > sceneObject
ManagedReference< SceneObject * > target
bool isManual
Detailed Description
Definition at line 20 of file TurretFireTask.h.
Constructor & Destructor Documentation
TurretFireTask::TurretFireTask (TangibleObject * turret, SceneObject * victim, bool isManualFire = false) inline
Definition at line 27 of file TurretFireTask.h.
References isManual, sceneObject, and target.
Member Function Documentation
bool TurretFireTask::checkTarget (TurretDataComponent * turretData) inline
Definition at line 156 of file TurretFireTask.h.
References CollisionManager::checkLineOfSight(), closeControls(), TurretDataComponent::getController(), TurretDataComponent::getTarget(), sceneObject, and target.
Referenced by run().
void TurretFireTask::checkTurretController (TurretDataComponent * turretData) inline
Definition at line 118 of file TurretFireTask.h.
References server::zone::objects::player::PlayerObject::closeSuiWindowType(), TurretDataComponent::getController(), server::zone::objects::creature::CreatureObject::getPlayerObject(), and SuiWindowType::HQ_TERMINAL.
Referenced by run().
void TurretFireTask::closeControls (CreatureObject * controllerCharacter, TurretDataComponent * turretData) inline
Definition at line 145 of file TurretFireTask.h.
References server::zone::objects::player::PlayerObject::closeSuiWindowType(), server::zone::objects::creature::CreatureObject::getPlayerObject(), and SuiWindowType::HQ_TURRET_TERMINAL.
Referenced by checkTarget().
void TurretFireTask::doAutoFire (TurretDataComponent * turretData, WeaponObject * weapon, SceneObject * defenderObject) inline
Definition at line 104 of file TurretFireTask.h.
References server::zone::objects::tangible::weapon::WeaponObject::getAttackSpeed(), TurretDataComponent::rescheduleFireTask(), TurretDataComponent::setTarget(), TurretDataComponent::updateAutoCooldown(), and TurretDataComponent::updateManualCooldown().
Referenced by executeCommand().
void TurretFireTask::executeCommand (TurretDataComponent * turretData, CombatQueueCommand * combatCommand) inline
Definition at line 82 of file TurretFireTask.h.
References doAutoFire(), TurretDataComponent::getController(), getTargetName(), handleManualFire(), isManual, sceneObject, server::zone::objects::creature::CreatureObject::sendSystemMessage(), and target.
Referenced by run().
String TurretFireTask::getTargetName (SceneObject * target) inline
Definition at line 128 of file TurretFireTask.h.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getObjectNameStringIdName(), server::zone::objects::scene::SceneObject::isPlayerCreature(), and target.
Referenced by executeCommand().
void TurretFireTask::handleManualFire (TurretDataComponent * turretData, WeaponObject * weapon, SceneObject * defenderObject) inline
Definition at line 111 of file TurretFireTask.h.
References server::zone::objects::tangible::weapon::WeaponObject::getAttackSpeed(), TurretDataComponent::rescheduleFireTask(), TurretDataComponent::setTarget(), TurretDataComponent::updateAutoCooldown(), and TurretDataComponent::updateManualCooldown().
Referenced by executeCommand().
bool TurretFireTask::isManualFireTask () inline
Definition at line 189 of file TurretFireTask.h.
References isManual.
void TurretFireTask::run () inline
Definition at line 34 of file TurretFireTask.h.
References TurretDataComponent::canAutoFire(), checkTarget(), checkTurretController(), executeCommand(), TurretDataComponent::getTarget(), isManual, sceneObject, TurretDataComponent::setFireTask(), TurretDataComponent::setTarget(), and target.
void TurretFireTask::setManualTask (bool val) inline
Definition at line 193 of file TurretFireTask.h.
References isManual.
Member Data Documentation
bool TurretFireTask::isManual private
Definition at line 23 of file TurretFireTask.h.
Referenced by executeCommand(), isManualFireTask(), run(), setManualTask(), and TurretFireTask().
ManagedReference<TangibleObject*> TurretFireTask::sceneObject private
Definition at line 21 of file TurretFireTask.h.
Referenced by checkTarget(), executeCommand(), run(), and TurretFireTask().
ManagedReference<SceneObject*> TurretFireTask::target private
Definition at line 22 of file TurretFireTask.h.
Referenced by checkTarget(), executeCommand(), getTargetName(), run(), and TurretFireTask().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/TurretFireTask.h