Core3: PermissionLevelList Class Reference
PermissionLevelList Class Reference
#include <PermissionLevelList.h>
Public Member Functions
PermissionLevelList ()
~PermissionLevelList ()
void loadLevel (LuaObject *luaLevel)
UnicodeString getPermissionTag (uint32 permissionLevel)
Vector< String > * getPermissionSkills (uint32 permissionLevel)
int getLevelNumber (String name)
bool containsLevel (String name)
Static Public Member Functions
static void loadLevels ()
static int addLevel (lua_State *L)
static int includeFile (lua_State *L)
Protected Attributes
VectorMap< String, int > permissionNames
Static Protected Attributes
static Lua lua
Detailed Description
Definition at line 60 of file PermissionLevelList.h.
Constructor & Destructor Documentation
PermissionLevelList::PermissionLevelList () inline
Definition at line 67 of file PermissionLevelList.h.
PermissionLevelList::~PermissionLevelList () inline
Definition at line 70 of file PermissionLevelList.h.
Member Function Documentation
static int PermissionLevelList::addLevel (lua_State * L) inline static
Definition at line 80 of file PermissionLevelList.h.
Referenced by loadLevels().
bool PermissionLevelList::containsLevel (String name) inline
Definition at line 136 of file PermissionLevelList.h.
References permissionNames.
Referenced by SetGodModeCommand::doQueueCommand().
int PermissionLevelList::getLevelNumber (String name) inline
Definition at line 132 of file PermissionLevelList.h.
References permissionNames.
Referenced by SetGodModeCommand::doQueueCommand().
Vector<String>* PermissionLevelList::getPermissionSkills (uint32 permissionLevel) inline
Definition at line 125 of file PermissionLevelList.h.
UnicodeString PermissionLevelList::getPermissionTag (uint32 permissionLevel) inline
Definition at line 118 of file PermissionLevelList.h.
static int PermissionLevelList::includeFile (lua_State * L) inline static
Definition at line 88 of file PermissionLevelList.h.
References lua.
Referenced by loadLevels().
void PermissionLevelList::loadLevel (LuaObject * luaLevel) inline
Definition at line 95 of file PermissionLevelList.h.
References permissionNames.
static void PermissionLevelList::loadLevels () inline static
Definition at line 73 of file PermissionLevelList.h.
References addLevel(), includeFile(), and lua.
Member Data Documentation
Lua PermissionLevelList::lua static protected
Definition at line 62 of file PermissionLevelList.h.
Referenced by includeFile(), and loadLevels().
VectorMap<String, int> PermissionLevelList::permissionNames protected
Definition at line 63 of file PermissionLevelList.h.
Referenced by containsLevel(), getLevelNumber(), and loadLevel().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/PermissionLevelList.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/PermissionLevelList.cpp