Core3: server::zone::managers::minigames::FishingManagerAdapter Class Reference
server::zone::managers::minigames::FishingManagerAdapter Class Reference
#include <FishingManager.h>
Public Member Functions
FishingManagerAdapter (FishingManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeBaitStatus ()
void initializeProperty ()
void initializeAction ()
void initializeState ()
void initializeFishType ()
void initializeFishLength ()
void initializeLoot ()
void initializeColor ()
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void checkFishingOnPositionUpdate (CreatureObject *player)
int notifyCloseContainer (CreatureObject *player, SceneObject *container)
int startFishing (CreatureObject *player)
void stopFishing (CreatureObject *player, unsigned int boxID, bool rem)
void fishingStep (CreatureObject *player)
void success (CreatureObject *player, int fish, SceneObject *marker, unsigned int boxID)
String getTime ()
void sendReward (CreatureObject *player, SceneObject *marker, SceneObject *loot)
unsigned int createWindow (CreatureObject *player, unsigned int boxID)
void closeMenu (CreatureObject *player, unsigned int boxID)
int vegetation (SceneObject *marker)
int density (SceneObject *marker)
int getFish (CreatureObject *player)
int getNextAction (CreatureObject *player)
void setNextAction (CreatureObject *player, int next)
FishingPoleObject * getPole (CreatureObject *player)
FishingBaitObject * getBait (CreatureObject *player)
unsigned int getFishBoxID (CreatureObject *player)
void setFishBoxID (CreatureObject *player, unsigned int boxID)
int getFishingState (CreatureObject *player)
void setFishingState (CreatureObject *player, int state)
SceneObject * getFishMarker (CreatureObject *player)
void setFishMarker (CreatureObject *player, SceneObject *marker)
void freeBait (CreatureObject *player)
void fishingProceed (CreatureObject *player, int nextAction, SceneObject *marker, int fish, unsigned int boxID, int newstate, bool notifyClient, String &moodString)
void mishapEvent (const String &text, CreatureObject *player, unsigned int boxID, bool losebait, String &moodString)
bool loseBait (CreatureObject *player)
void animate (CreatureObject *player, int nextAction)
SceneObject * createMarker (float x, float y, float z, Zone *zone)
void createSplash (float x, float y, float z, Zone *zone, CreatureObject *player)
bool isPlaying (CreatureObject *player)
SceneObject * updateMarker (CreatureObject *player, SceneObject *marker, bool notifyPlayer)
void removeMarker (CreatureObject *player, SceneObject *container)
void removeSplash (SceneObject *splash)
void createFishingSplashEvent (CreatureObject *player, SceneObject *splash)
void stopFishingEvent (CreatureObject *player)
Detailed Description
Definition at line 1324 of file FishingManager.h.
Constructor & Destructor Documentation
FishingManagerAdapter::FishingManagerAdapter (FishingManager * impl)
Definition at line 1169 of file FishingManager.cpp.
Member Function Documentation
void FishingManagerAdapter::animate (CreatureObject * player, int nextAction)
Definition at line 1552 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::checkFishingOnPositionUpdate (CreatureObject * player)
Definition at line 1444 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::closeMenu (CreatureObject * player, unsigned int boxID)
Definition at line 1480 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::createFishingSplashEvent (CreatureObject * player, SceneObject * splash)
Definition at line 1580 of file FishingManager.cpp.
Referenced by invokeMethod().
SceneObject * FishingManagerAdapter::createMarker (float x, float y, float z, Zone * zone)
Definition at line 1556 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::createSplash (float x, float y, float z, Zone * zone, CreatureObject * player)
Definition at line 1560 of file FishingManager.cpp.
Referenced by invokeMethod().
unsigned int FishingManagerAdapter::createWindow (CreatureObject * player, unsigned int boxID)
Definition at line 1476 of file FishingManager.cpp.
Referenced by invokeMethod().
int FishingManagerAdapter::density (SceneObject * marker)
Definition at line 1488 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::fishingProceed (CreatureObject * player, int nextAction, SceneObject * marker, int fish, unsigned int boxID, int newstate, bool notifyClient, String & moodString)
Definition at line 1540 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::fishingStep (CreatureObject * player)
Definition at line 1460 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::freeBait (CreatureObject * player)
Definition at line 1536 of file FishingManager.cpp.
Referenced by invokeMethod().
FishingBaitObject * FishingManagerAdapter::getBait (CreatureObject * player)
Definition at line 1508 of file FishingManager.cpp.
Referenced by invokeMethod().
int FishingManagerAdapter::getFish (CreatureObject * player)
Definition at line 1492 of file FishingManager.cpp.
Referenced by invokeMethod().
unsigned int FishingManagerAdapter::getFishBoxID (CreatureObject * player)
Definition at line 1512 of file FishingManager.cpp.
Referenced by invokeMethod().
int FishingManagerAdapter::getFishingState (CreatureObject * player)
Definition at line 1520 of file FishingManager.cpp.
Referenced by invokeMethod().
SceneObject * FishingManagerAdapter::getFishMarker (CreatureObject * player)
Definition at line 1528 of file FishingManager.cpp.
Referenced by invokeMethod().
int FishingManagerAdapter::getNextAction (CreatureObject * player)
Definition at line 1496 of file FishingManager.cpp.
Referenced by invokeMethod().
FishingPoleObject * FishingManagerAdapter::getPole (CreatureObject * player)
Definition at line 1504 of file FishingManager.cpp.
Referenced by invokeMethod().
String FishingManagerAdapter::getTime ()
Definition at line 1468 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::initializeAction ()
Definition at line 1416 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::initializeBaitStatus ()
Definition at line 1408 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::initializeColor ()
Definition at line 1436 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::initializeFishLength ()
Definition at line 1428 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::initializeFishType ()
Definition at line 1424 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::initializeLoot ()
Definition at line 1432 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::initializeProperty ()
Definition at line 1412 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::initializeState ()
Definition at line 1420 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1172 of file FishingManager.cpp.
References animate(), checkFishingOnPositionUpdate(), closeMenu(), createFishingSplashEvent(), createMarker(), createSplash(), createWindow(), density(), fishingProceed(), fishingStep(), freeBait(), getBait(), getFish(), getFishBoxID(), getFishingState(), getFishMarker(), getNextAction(), getPole(), getTime(), initializeAction(), initializeBaitStatus(), initializeColor(), initializeFishLength(), initializeFishType(), initializeLoot(), initializeProperty(), initializeState(), isPlaying(), loseBait(), mishapEvent(), notifyCloseContainer(), notifyObserverEvent(), removeMarker(), removeSplash(), RPC_ANIMATE__CREATUREOBJECT_INT_, RPC_CHECKFISHINGONPOSITIONUPDATE__CREATUREOBJECT_, RPC_CLOSEMENU__CREATUREOBJECT_INT_, RPC_CREATEFISHINGSPLASHEVENT__CREATUREOBJECT_SCENEOBJECT_, RPC_CREATEMARKER__FLOAT_FLOAT_FLOAT_ZONE_, RPC_CREATESPLASH__FLOAT_FLOAT_FLOAT_ZONE_CREATUREOBJECT_, RPC_CREATEWINDOW__CREATUREOBJECT_INT_, RPC_DENSITY__SCENEOBJECT_, RPC_FISHINGPROCEED__CREATUREOBJECT_INT_SCENEOBJECT_INT_INT_INT_BOOL_STRING_, RPC_FISHINGSTEP__CREATUREOBJECT_, RPC_FREEBAIT__CREATUREOBJECT_, RPC_GETBAIT__CREATUREOBJECT_, RPC_GETFISH__CREATUREOBJECT_, RPC_GETFISHBOXID__CREATUREOBJECT_, RPC_GETFISHINGSTATE__CREATUREOBJECT_, RPC_GETFISHMARKER__CREATUREOBJECT_, RPC_GETNEXTACTION__CREATUREOBJECT_, RPC_GETPOLE__CREATUREOBJECT_, RPC_GETTIME__, RPC_INITIALIZEACTION__, RPC_INITIALIZEBAITSTATUS__, RPC_INITIALIZECOLOR__, RPC_INITIALIZEFISHLENGTH__, RPC_INITIALIZEFISHTYPE__, RPC_INITIALIZELOOT__, RPC_INITIALIZEPROPERTY__, RPC_INITIALIZESTATE__, RPC_ISPLAYING__CREATUREOBJECT_, RPC_LOSEBAIT__CREATUREOBJECT_, RPC_MISHAPEVENT__STRING_CREATUREOBJECT_INT_BOOL_STRING_, RPC_NOTIFYCLOSECONTAINER__CREATUREOBJECT_SCENEOBJECT_, RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_, RPC_REMOVEMARKER__CREATUREOBJECT_SCENEOBJECT_, RPC_REMOVESPLASH__SCENEOBJECT_, RPC_SENDREWARD__CREATUREOBJECT_SCENEOBJECT_SCENEOBJECT_, RPC_SETFISHBOXID__CREATUREOBJECT_INT_, RPC_SETFISHINGSTATE__CREATUREOBJECT_INT_, RPC_SETFISHMARKER__CREATUREOBJECT_SCENEOBJECT_, RPC_SETNEXTACTION__CREATUREOBJECT_INT_, RPC_STARTFISHING__CREATUREOBJECT_, RPC_STOPFISHING__CREATUREOBJECT_INT_BOOL_, RPC_STOPFISHINGEVENT__CREATUREOBJECT_, RPC_SUCCESS__CREATUREOBJECT_INT_SCENEOBJECT_INT_, RPC_UPDATEMARKER__CREATUREOBJECT_SCENEOBJECT_BOOL_, RPC_VEGETATION__SCENEOBJECT_, sendReward(), setFishBoxID(), setFishingState(), setFishMarker(), setNextAction(), startFishing(), stopFishing(), stopFishingEvent(), success(), updateMarker(), and vegetation().
bool FishingManagerAdapter::isPlaying (CreatureObject * player)
Definition at line 1564 of file FishingManager.cpp.
Referenced by invokeMethod().
bool FishingManagerAdapter::loseBait (CreatureObject * player)
Definition at line 1548 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::mishapEvent (const String & text, CreatureObject * player, unsigned int boxID, bool losebait, String & moodString)
Definition at line 1544 of file FishingManager.cpp.
Referenced by invokeMethod().
int FishingManagerAdapter::notifyCloseContainer (CreatureObject * player, SceneObject * container)
Definition at line 1448 of file FishingManager.cpp.
Referenced by invokeMethod().
int FishingManagerAdapter::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 1440 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::removeMarker (CreatureObject * player, SceneObject * container)
Definition at line 1572 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::removeSplash (SceneObject * splash)
Definition at line 1576 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::sendReward (CreatureObject * player, SceneObject * marker, SceneObject * loot)
Definition at line 1472 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::setFishBoxID (CreatureObject * player, unsigned int boxID)
Definition at line 1516 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::setFishingState (CreatureObject * player, int state)
Definition at line 1524 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::setFishMarker (CreatureObject * player, SceneObject * marker)
Definition at line 1532 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::setNextAction (CreatureObject * player, int next)
Definition at line 1500 of file FishingManager.cpp.
Referenced by invokeMethod().
int FishingManagerAdapter::startFishing (CreatureObject * player)
Definition at line 1452 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::stopFishing (CreatureObject * player, unsigned int boxID, bool rem)
Definition at line 1456 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::stopFishingEvent (CreatureObject * player)
Definition at line 1584 of file FishingManager.cpp.
Referenced by invokeMethod().
void FishingManagerAdapter::success (CreatureObject * player, int fish, SceneObject * marker, unsigned int boxID)
Definition at line 1464 of file FishingManager.cpp.
Referenced by invokeMethod().
SceneObject * FishingManagerAdapter::updateMarker (CreatureObject * player, SceneObject * marker, bool notifyPlayer)
Definition at line 1568 of file FishingManager.cpp.
Referenced by invokeMethod().
int FishingManagerAdapter::vegetation (SceneObject * marker)
Definition at line 1484 of file FishingManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/minigames/FishingManager.cpp