Core3: server::zone::managers::loot::LootManagerAdapter Class Reference
server::zone::managers::loot::LootManagerAdapter Class Reference
#include <LootManager.h>
Public Member Functions
LootManagerAdapter (LootManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initialize ()
int calculateLootCredits (int level)
bool createLoot (SceneObject *container, AiAgent *creature)
bool createLoot (SceneObject *container, const String &lootGroup, int level, bool maxCondition)
Detailed Description
Definition at line 317 of file LootManager.h.
Constructor & Destructor Documentation
LootManagerAdapter::LootManagerAdapter (LootManager * impl)
Definition at line 321 of file LootManager.cpp.
Member Function Documentation
int LootManagerAdapter::calculateLootCredits (int level)
Definition at line 358 of file LootManager.cpp.
Referenced by invokeMethod().
bool LootManagerAdapter::createLoot (SceneObject * container, AiAgent * creature)
Definition at line 362 of file LootManager.cpp.
Referenced by invokeMethod().
bool LootManagerAdapter::createLoot (SceneObject * container, const String & lootGroup, int level, bool maxCondition)
Definition at line 366 of file LootManager.cpp.
void LootManagerAdapter::initialize ()
Definition at line 354 of file LootManager.cpp.
Referenced by invokeMethod().
void LootManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 324 of file LootManager.cpp.
References calculateLootCredits(), createLoot(), initialize(), RPC_CALCULATELOOTCREDITS__INT_, RPC_CREATELOOT__SCENEOBJECT_AIAGENT_, RPC_CREATELOOT__SCENEOBJECT_STRING_INT_BOOL_, and RPC_INITIALIZE__.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/LootManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/LootManager.cpp