Core3: server::zone::objects::player::sessions::ImageDesignSessionAdapter Class Reference
server::zone::objects::player::sessions::ImageDesignSessionAdapter Class Reference
#include <ImageDesignSession.h>
Public Member Functions
ImageDesignSessionAdapter (ImageDesignSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
int initializeSession ()
int doPayment ()
int cancelSession ()
int clearSession ()
void clearIdTimeoutEvent ()
void checkDequeueEvent (SceneObject *scene)
void queueIdTimeoutEvent ()
void dequeueIdTimeoutEvent ()
void sessionTimeout ()
Detailed Description
Definition at line 275 of file ImageDesignSession.h.
Constructor & Destructor Documentation
ImageDesignSessionAdapter::ImageDesignSessionAdapter (ImageDesignSession * impl)
Definition at line 465 of file ImageDesignSession.cpp.
Member Function Documentation
int ImageDesignSessionAdapter::cancelSession ()
Definition at line 539 of file ImageDesignSession.cpp.
Referenced by invokeMethod().
void ImageDesignSessionAdapter::checkDequeueEvent (SceneObject * scene)
Definition at line 551 of file ImageDesignSession.cpp.
Referenced by invokeMethod().
void ImageDesignSessionAdapter::clearIdTimeoutEvent ()
Definition at line 547 of file ImageDesignSession.cpp.
Referenced by invokeMethod().
int ImageDesignSessionAdapter::clearSession ()
Definition at line 543 of file ImageDesignSession.cpp.
Referenced by invokeMethod().
void ImageDesignSessionAdapter::dequeueIdTimeoutEvent ()
Definition at line 559 of file ImageDesignSession.cpp.
Referenced by invokeMethod().
int ImageDesignSessionAdapter::doPayment ()
Definition at line 535 of file ImageDesignSession.cpp.
Referenced by invokeMethod().
int ImageDesignSessionAdapter::initializeSession ()
Definition at line 531 of file ImageDesignSession.cpp.
Referenced by invokeMethod().
void ImageDesignSessionAdapter::initializeTransientMembers ()
Definition at line 527 of file ImageDesignSession.cpp.
Referenced by invokeMethod().
void ImageDesignSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 468 of file ImageDesignSession.cpp.
References cancelSession(), checkDequeueEvent(), clearIdTimeoutEvent(), clearSession(), dequeueIdTimeoutEvent(), doPayment(), initializeSession(), initializeTransientMembers(), queueIdTimeoutEvent(), RPC_CANCELSESSION__, RPC_CHECKDEQUEUEEVENT__SCENEOBJECT_, RPC_CLEARIDTIMEOUTEVENT__, RPC_CLEARSESSION__, RPC_DEQUEUEIDTIMEOUTEVENT__, RPC_DOPAYMENT__, RPC_INITIALIZESESSION__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_QUEUEIDTIMEOUTEVENT__, RPC_SESSIONTIMEOUT__, and sessionTimeout().
void ImageDesignSessionAdapter::queueIdTimeoutEvent ()
Definition at line 555 of file ImageDesignSession.cpp.
Referenced by invokeMethod().
void ImageDesignSessionAdapter::sessionTimeout ()
Definition at line 563 of file ImageDesignSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignSession.cpp