Core3: ZoneComponent Class Reference
ZoneComponent Class Reference
#include <ZoneComponent.h>
Public Member Functions
virtual void notifyInsertToZone (SceneObject *sceneObject, Zone *zone)
virtual void switchZone (SceneObject *sceneObject, const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, uint64 parentID=0)
virtual void teleport (SceneObject *sceneObject, float newPositionX, float newPositionZ, float newPositionY, uint64 parentID=0)
virtual void notifyRemoveFromZone (SceneObject *sceneObject)
virtual void updateZone (SceneObject *sceneObject, bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *sceneObject, SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
virtual void notifyPositionUpdate (SceneObject *sceneObject, QuadTreeEntry *entry)
virtual void notifySelfPositionUpdate (SceneObject *sceneObject)
virtual void notifyInsert (SceneObject *sceneObject, QuadTreeEntry *entry)
virtual void notifyDissapear (SceneObject *sceneObject, QuadTreeEntry *entry)
void updateInRangeObjectsOnMount (SceneObject *sceneObject)
virtual void destroyObjectFromWorld (SceneObject *sceneObject, bool sendSelfDestroy)
Protected Member Functions
void insertChildObjectsToZone (SceneObject *sceneObject, Zone *zone)
Detailed Description
Definition at line 37 of file ZoneComponent.h.
Member Function Documentation
void ZoneComponent::destroyObjectFromWorld (SceneObject * sceneObject, bool sendSelfDestroy) virtual
Reimplemented in CityHallZoneComponent, and ShuttleInstallationZoneComponent.
Definition at line 388 of file ZoneComponent.cpp.
References server::zone::objects::scene::SceneObject::broadcastDestroy(), server::zone::objects::scene::SceneObject::getActiveAreas(), server::zone::objects::scene::SceneObject::getContainerLock(), server::zone::objects::scene::SceneObject::getLocalZone(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getParentID(), SharedBuildingObjectTemplate::getTerrainModificationFile(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isActiveArea(), ObserverEventType::OBJECTREMOVEDFROMZONE, and server::zone::objects::scene::SceneObject::removeObject().
Referenced by ShuttleInstallationZoneComponent::destroyObjectFromWorld(), and CityHallZoneComponent::destroyObjectFromWorld().
void ZoneComponent::insertChildObjectsToZone (SceneObject * sceneObject, Zone * zone) protected
Definition at line 75 of file ZoneComponent.cpp.
References server::zone::objects::scene::SceneObject::getChildObjects(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by notifyInsertToZone().
virtual void ZoneComponent::notifyDissapear (SceneObject * sceneObject, QuadTreeEntry * entry) inline virtual
Reimplemented in PlayerZoneComponent.
Definition at line 96 of file ZoneComponent.h.
virtual void ZoneComponent::notifyInsert (SceneObject * sceneObject, QuadTreeEntry * entry) inline virtual
Reimplemented in PlayerZoneComponent.
Definition at line 93 of file ZoneComponent.h.
void ZoneComponent::notifyInsertToZone (SceneObject * sceneObject, Zone * zone) virtual
Inserts this object into zone
Precondition
{ this object is locked }
Postcondition
{ this object is locked and inserted into zone }
Parameters
zone Zone object where this object will be inserted
Reimplemented in ShuttleZoneComponent, StructureZoneComponent, ShuttleInstallationZoneComponent, TurretZoneComponent, MinefieldZoneComponent, and PlayerZoneComponent.
Definition at line 62 of file ZoneComponent.cpp.
References server::zone::objects::scene::SceneObject::getParentID(), insertChildObjectsToZone(), and server::zone::objects::scene::SceneObject::teleport().
Referenced by PlayerZoneComponent::notifyInsertToZone(), StructureZoneComponent::notifyInsertToZone(), and ShuttleZoneComponent::notifyInsertToZone().
virtual void ZoneComponent::notifyPositionUpdate (SceneObject * sceneObject, QuadTreeEntry * entry) inline virtual
Reimplemented in VendorZoneComponent, TurretZoneComponent, DetectorZoneComponent, and MinefieldZoneComponent.
Definition at line 87 of file ZoneComponent.h.
void ZoneComponent::notifyRemoveFromZone (SceneObject * sceneObject) virtual
Removes object from zone
Precondition
{ this object is locked }
Postcondition
{ this object is locked and not in zone}
Reimplemented in ShuttleZoneComponent, StructureZoneComponent, and ShuttleInstallationZoneComponent.
Definition at line 381 of file ZoneComponent.cpp.
Referenced by ShuttleZoneComponent::notifyRemoveFromZone(), and StructureZoneComponent::notifyRemoveFromZone().
void ZoneComponent::notifySelfPositionUpdate (SceneObject * sceneObject) virtual
Reimplemented in PlayerZoneComponent.
Definition at line 491 of file ZoneComponent.cpp.
References server::zone::objects::scene::SceneObject::notifySelfPositionUpdate().
Referenced by PlayerZoneComponent::notifySelfPositionUpdate(), updateZone(), and updateZoneWithParent().
void ZoneComponent::switchZone (SceneObject * sceneObject, const String & newTerrainName, float newPostionX, float newPositionZ, float newPositionY, uint64 parentID = 0) virtual
Switches zone and position of this object
Precondition
{ this object is locked }
Postcondition
{ this object is locked, is in the new zone and in the new position }
Parameters
newZoneID new zone id where the object will be inserted
newPositionX new position X
newPositionZ new position Z
newPositionY new position Y
Reimplemented in PlayerZoneComponent.
Definition at line 337 of file ZoneComponent.cpp.
References server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::error(), server::zone::Zone::getHeight(), server::zone::ZoneServer::getObject(), server::zone::ZoneServer::getZone(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::sendMessage(), server::zone::objects::scene::SceneObject::sendToOwner(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by PlayerZoneComponent::switchZone().
void ZoneComponent::teleport (SceneObject * sceneObject, float newPositionX, float newPositionZ, float newPositionY, uint64 parentID = 0) virtual
Reimplemented in PlayerZoneComponent.
Definition at line 90 of file ZoneComponent.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::updateZone(), and server::zone::objects::scene::SceneObject::updateZoneWithParent().
Referenced by PlayerZoneComponent::teleport().
void ZoneComponent::updateInRangeObjectsOnMount (SceneObject * sceneObject)
Definition at line 127 of file ZoneComponent.cpp.
References server::zone::objects::scene::SceneObject::getRootParent().
Referenced by updateZone().
void ZoneComponent::updateZone (SceneObject * sceneObject, bool lightUpdate, bool sendPackets = true) virtual
Updates position of this object to the rest of in range objects
Precondition
{ this object is locked}
Postcondition
{ this object is locked, in range objects are updated with the new position }
Parameters
lightUpdate if true a standalone message is sent to the in range objects
Reimplemented in PlayerZoneComponent.
Definition at line 186 of file ZoneComponent.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), server::zone::objects::scene::SceneObject::error(), server::zone::objects::scene::SceneObject::getLocalZone(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getRootParent(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::inRange(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::creature::CreatureObject::isInvisible(), notifySelfPositionUpdate(), server::zone::objects::scene::SceneObject::transferObject(), server::zone::Zone::update(), server::zone::Zone::updateActiveAreas(), updateInRangeObjectsOnMount(), and server::zone::objects::scene::SceneObject::updateVehiclePosition().
Referenced by PlayerZoneComponent::updateZone().
void ZoneComponent::updateZoneWithParent (SceneObject * sceneObject, SceneObject * newParent, bool lightUpdate, bool sendPackets = true) virtual
Updates position and/or parent of this object and to the rest of in range objects
Precondition
{ this object is locked, newParent is a CellObject }
Postcondition
{this object is locked, in range objects are updated of the new position and parent }
Parameters
newParent cellObject where this object is
lightUpdate if true a standalone message is sent to the in range objects
Reimplemented in PlayerZoneComponent.
Definition at line 255 of file ZoneComponent.cpp.
References server::zone::objects::scene::SceneObject::broadcastMessage(), server::zone::objects::scene::SceneObject::error(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getRootParent(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::creature::CreatureObject::isInvisible(), server::zone::objects::scene::SceneObject::notifyPositionUpdate(), notifySelfPositionUpdate(), and server::zone::objects::scene::SceneObject::transferObject().
Referenced by PlayerZoneComponent::updateZoneWithParent().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/components/ZoneComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/components/ZoneComponent.cpp