Core3: MapLocationTable Class Reference
MapLocationTable Class Reference
#include <MapLocationTable.h>
Public Member Functions
MapLocationTable ()
MapLocationTable (const MapLocationTable &t)
Object * clone ()
Object * clone (void *object)
void transferObject (SceneObject *object)
void dropObject (SceneObject *object)
SortedVector< MapLocationEntry > & getLocation (const String &name)
SortedVector< MapLocationEntry > & get (int index)
int findLocation (const String &name)
int size ()
Private Attributes
VectorMap< String,
SortedVector< MapLocationEntry > > locations
Detailed Description
Definition at line 28 of file MapLocationTable.h.
Constructor & Destructor Documentation
MapLocationTable::MapLocationTable () inline
Definition at line 32 of file MapLocationTable.h.
MapLocationTable::MapLocationTable (const MapLocationTable & t) inline
Definition at line 36 of file MapLocationTable.h.
References locations.
Member Function Documentation
Object* MapLocationTable::clone () inline
Definition at line 40 of file MapLocationTable.h.
Object* MapLocationTable::clone (void * object) inline
Definition at line 44 of file MapLocationTable.h.
void MapLocationTable::dropObject (SceneObject * object)
Definition at line 39 of file MapLocationTable.cpp.
References PlanetMapCategory::getName(), and locations.
int MapLocationTable::findLocation (const String & name)
Definition at line 65 of file MapLocationTable.cpp.
References locations.
SortedVector<MapLocationEntry>& MapLocationTable::get (int index) inline
Definition at line 54 of file MapLocationTable.h.
Referenced by GetMapLocationsResponseMessage::GetMapLocationsResponseMessage().
SortedVector< MapLocationEntry > & MapLocationTable::getLocation (const String & name)
Definition at line 61 of file MapLocationTable.cpp.
References locations.
int MapLocationTable::size () inline
Definition at line 60 of file MapLocationTable.h.
Referenced by GetMapLocationsResponseMessage::GetMapLocationsResponseMessage().
void MapLocationTable::transferObject (SceneObject * object)
Definition at line 12 of file MapLocationTable.cpp.
References PlanetMapCategory::getName(), and locations.
Member Data Documentation
VectorMap<String, SortedVector<MapLocationEntry> > MapLocationTable::locations private
Definition at line 29 of file MapLocationTable.h.
Referenced by dropObject(), findLocation(), getLocation(), MapLocationTable(), and transferObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/MapLocationTable.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/MapLocationTable.cpp