Core3: ClientIDMessageCallback Class Reference
ClientIDMessageCallback Class Reference
#include <ClientIDMessageCallback.h>
Public Member Functions
ClientIDMessageCallback (ZoneClientSession *client, ZoneProcessServer *server)
void parse (Message *message)
void run ()
uint32 getDataLen ()
uint32 getSessionID ()
uint32 getAccountID ()
Public Member Functions inherited from server::zone::packets::MessageCallback
MessageCallback (ZoneClientSession *client, ZoneProcessServer *server)
virtual ~MessageCallback ()
int getTaskQueue ()
bool parseMessage (Message *packet)
ZoneClientSession * getClient ()
ZoneProcessServer * getServer ()
Private Attributes
uint32 dataLen
uint32 sessionID
uint32 accountID
Additional Inherited Members
Protected Attributes inherited from server::zone::packets::MessageCallback
Reference< ZoneClientSession * > client
ManagedReference
< ZoneProcessServer * > server
int taskqueue
Detailed Description
Definition at line 20 of file ClientIDMessageCallback.h.
Constructor & Destructor Documentation
ClientIDMessageCallback::ClientIDMessageCallback (ZoneClientSession * client, ZoneProcessServer * server) inline
Definition at line 26 of file ClientIDMessageCallback.h.
References server::zone::packets::MessageCallback::taskqueue.
Member Function Documentation
uint32 ClientIDMessageCallback::getAccountID () inline
Definition at line 140 of file ClientIDMessageCallback.h.
References accountID.
uint32 ClientIDMessageCallback::getDataLen () inline
Definition at line 132 of file ClientIDMessageCallback.h.
References dataLen.
uint32 ClientIDMessageCallback::getSessionID () inline
Definition at line 136 of file ClientIDMessageCallback.h.
References sessionID.
void ClientIDMessageCallback::parse (Message * message) inline virtual
Implements server::zone::packets::MessageCallback.
Definition at line 33 of file ClientIDMessageCallback.h.
References accountID, dataLen, and sessionID.
void ClientIDMessageCallback::run () inline
Definition at line 48 of file ClientIDMessageCallback.h.
References accountID, server::zone::packets::MessageCallback::client, GalaxyBanEntry::getBanReason(), CharacterListEntry::getGalaxyID(), CharacterListEntry::getObjectID(), ServerDatabase::instance(), CharacterListEntry::isBanned(), server::zone::packets::MessageCallback::server, and sessionID.
Member Data Documentation
uint32 ClientIDMessageCallback::accountID private
Definition at line 23 of file ClientIDMessageCallback.h.
Referenced by getAccountID(), parse(), and run().
uint32 ClientIDMessageCallback::dataLen private
Definition at line 21 of file ClientIDMessageCallback.h.
Referenced by getDataLen(), and parse().
uint32 ClientIDMessageCallback::sessionID private
Definition at line 22 of file ClientIDMessageCallback.h.
Referenced by getSessionID(), parse(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/zone/ClientIDMessageCallback.h