Core3: CustomizationIdManager Class Reference
CustomizationIdManager Class Reference
#include <CustomizationIdManager.h>
Public Member Functions
CustomizationIdManager ()
void loadPaletteColumns (IffStream *iffStream)
void loadHairAssetsSkillMods (IffStream *iffStream)
void loadAllowBald (IffStream *iffStream)
void readObject (IffStream *iffStream)
int getCustomizationId (const String &var)
String getCustomizationVariable (int id)
PaletteData * getPaletteData (const String &palette)
HairAssetData * getHairAssetData (const String &hairServerTemplate)
bool canBeBald (const String &speciesSubString)
Private Attributes
HashTable< String, int > customizationIds
HashTable< int, String > reverseIds
HashTable< String, Reference
< PaletteData * > > paletteColumns
HashTable< String, Reference
< HairAssetData * > > hairAssetSkillMods
HashTable< String, bool > allowBald
Detailed Description
Definition at line 16 of file CustomizationIdManager.h.
Constructor & Destructor Documentation
CustomizationIdManager::CustomizationIdManager ()
Definition at line 12 of file CustomizationIdManager.cpp.
Member Function Documentation
bool CustomizationIdManager::canBeBald (const String & speciesSubString) inline
Definition at line 47 of file CustomizationIdManager.h.
References allowBald.
int CustomizationIdManager::getCustomizationId (const String & var) inline
Definition at line 31 of file CustomizationIdManager.h.
References customizationIds.
String CustomizationIdManager::getCustomizationVariable (int id) inline
Definition at line 35 of file CustomizationIdManager.h.
References reverseIds.
HairAssetData* CustomizationIdManager::getHairAssetData (const String & hairServerTemplate) inline
Definition at line 43 of file CustomizationIdManager.h.
References hairAssetSkillMods.
PaletteData* CustomizationIdManager::getPaletteData (const String & palette) inline
Definition at line 39 of file CustomizationIdManager.h.
References paletteColumns.
void CustomizationIdManager::loadAllowBald (IffStream * iffStream)
Definition at line 32 of file CustomizationIdManager.cpp.
References allowBald, DataTableIff::getRow(), DataTableIff::getTotalRows(), DataTableRow::getValue(), and DataTableIff::readObject().
void CustomizationIdManager::loadHairAssetsSkillMods (IffStream * iffStream)
Definition at line 16 of file CustomizationIdManager.cpp.
References DataTableIff::getRow(), HairAssetData::getServerTemplate(), DataTableIff::getTotalRows(), hairAssetSkillMods, paletteColumns, DataTableIff::readObject(), and HairAssetData::readObject().
void CustomizationIdManager::loadPaletteColumns (IffStream * iffStream)
Definition at line 51 of file CustomizationIdManager.cpp.
References PaletteData::getName(), DataTableIff::getRow(), DataTableIff::getTotalRows(), paletteColumns, DataTableIff::readObject(), and PaletteData::readObject().
void CustomizationIdManager::readObject (IffStream * iffStream)
Definition at line 66 of file CustomizationIdManager.cpp.
References customizationIds, and reverseIds.
Member Data Documentation
HashTable<String, bool> CustomizationIdManager::allowBald private
Definition at line 21 of file CustomizationIdManager.h.
Referenced by canBeBald(), and loadAllowBald().
HashTable<String, int> CustomizationIdManager::customizationIds private
Definition at line 17 of file CustomizationIdManager.h.
Referenced by getCustomizationId(), and readObject().
HashTable<String, Reference<HairAssetData*> > CustomizationIdManager::hairAssetSkillMods private
Definition at line 20 of file CustomizationIdManager.h.
Referenced by getHairAssetData(), and loadHairAssetsSkillMods().
HashTable<String, Reference<PaletteData*> > CustomizationIdManager::paletteColumns private
Definition at line 19 of file CustomizationIdManager.h.
Referenced by getPaletteData(), loadHairAssetsSkillMods(), and loadPaletteColumns().
HashTable<int, String> CustomizationIdManager::reverseIds private
Definition at line 18 of file CustomizationIdManager.h.
Referenced by getCustomizationVariable(), and readObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/customization/CustomizationIdManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/customization/CustomizationIdManager.cpp