Core3: SharedTangibleObjectTemplate Class Reference
SharedTangibleObjectTemplate Class Reference
#include <SharedTangibleObjectTemplate.h>
Public Member Functions
SharedTangibleObjectTemplate ()
~SharedTangibleObjectTemplate ()
void readObject (LuaObject *templateData)
void readObject (IffStream *iffStream)
void parseFileData (IffStream *str)
void parseVariableData (const String &varName, Chunk *data)
void parseVariableData (const String &varName, LuaObject *data)
int getMaxCondition () const
uint32 getOptionsBitmask () const
uint32 getPvpStatusBitmask () const
void setMaxCondition (int maxCondition)
void setOptionsBitmask (uint32 optionsBitmask)
void setPvpStatusBitmask (uint32 pvpStatusBitmask)
Vector< String > getCertificationsRequired () const
int getLevel () const
int getUseCount () const
int getFactoryCrateSize () const
uint16 getPlayerUseMask () const
int getFaction () const
StructureFootprint * getStructureFootprint () const
bool getTargetable () const
void setCertificationsRequired (Vector< String > certificationsRequired)
void setPlayerUseMask (uint16 playerUseMask)
void setTargetable (bool targetable)
bool getSliceable () const
Vector< short > * getNumberExperimentalProperties ()
Vector< String > * getExperimentalProperties ()
Vector< short > * getExperimentalWeights ()
Vector< String > * getExperimentalGroupTitles ()
Vector< String > * getExperimentalSubGroupTitles ()
Vector< float > * getExperimentalMin ()
Vector< float > * getExperimentalMax ()
Vector< short > * getExperimentalPrecision ()
Vector< uint32 > * getPlayerRaces ()
Vector< Reference
< ResourceWeight * > > * getResourceWeights ()
VectorMap< String, int > * getSkillMods ()
int getSkillMod (const String &mod)
bool isSharedTangibleObjectTemplate ()
Public Member Functions inherited from server::zone::templates::SharedObjectTemplate
SharedObjectTemplate ()
virtual ~SharedObjectTemplate ()
void parseVariableData (const String &varName, Chunk *data)
void parseVariableData (const String &varName, LuaObject *templateData)
void loadDerv (IffStream *iffStream)
void parseFileData (IffStream *iffStream)
bool isDerivedFrom (const String &iffPath, bool includeSelf=true)
String getAppearanceFilename () const
float getClearFloraRadius () const
String getClientDataFile () const
int getCollisionActionBlockFlags () const
int getCollisionActionFlags () const
int getCollisionActionPassFlags () const
int getCollisionMaterialBlockFlags () const
int getCollisionMaterialFlags () const
int getCollisionMaterialPassFlags () const
int getContainerType () const
int getContainerVolumeLimit () const
String getDetailedDescription ()
int getGameObjectType () const
int getClientGameObjectType () const
float getLocationReservationRadius () const
String getLookAtText () const
float getNoBuildRadius () const
String getObjectName () const
bool getOnlyVisibleInTools () const
String getPortalLayoutFilename () const
PortalLayout * getPortalLayout ()
AppearanceTemplate * getAppearanceTemplate ()
Vector< String > * getArrangementDescriptors ()
void addDerivedFile (const String &name)
float getMinScale ()
float getMaxScale ()
bool isNoTrade ()
float getScaleThresholdBeforeExtentTest () const
bool getSendToClient () const
Vector< String > * getSlotDescriptors ()
bool getSnapToTerrain () const
int getSurfaceType () const
String getTintPallete () const
int getTotalCellNumber () const
uint32 getClientObjectCRC () const
String getClientTemplateFileName ()
uint32 getServerObjectCRC ()
String getFullTemplateString ()
String getDataObjectComponent ()
String getTemplateFileName ()
SceneObjectComponent * getContainerComponent ()
String getZoneComponent ()
SceneObjectComponent * getObjectMenuComponent ()
String getAttributeListComponent ()
PlanetMapCategory * getPlanetMapCategory () const
PlanetMapCategory * getPlanetMapSubCategory () const
bool isAutoRegistering ()
int getChildObjectsSize ()
ChildObject * getChildObject (int idx)
bool hasInheritPermissionsFromParent ()
HashTable< uint32, uint32 > * getGroupPermissions ()
bool hasArrangementDescriptor (String s)
void setAppearanceFilename (String appearanceFilename)
void setClearFloraRadius (float clearFloraRadius)
void setClientDataFile (String clientDataFile)
void setCollisionActionBlockFlags (int collisionActionBlockFlags)
void setCollisionActionFlags (int collisionActionFlags)
void setCollisionActionPassFlags (int collisionActionPassFlags)
void setCollisionMaterialBlockFlags (int collisionMaterialBlockFlags)
void setCollisionMaterialFlags (int collisionMaterialFlags)
void setCollisionMaterialPassFlags (int collisionMaterialPassFlags)
void setContainerType (int containerType)
void setContainerVolumeLimit (int containerVolumeLimit)
void setDetailedDescription (String detailedDescription)
void setGameObjectType (int gameObjectType)
void setLocationReservationRadius (float locationReservationRadius)
void setLookAtText (String lookAtText)
void setNoBuildRadius (float noBuildRadius)
void setObjectName (String objectName)
void setOnlyVisibleInTools (bool onlyVisibleInTools)
void setPortalLayoutFilename (String portalLayoutFilename)
void setScale (float scale)
void setScaleThresholdBeforeExtentTest (float scaleThresholdBeforeExtentTest)
void setSendToClient (bool sendToClient)
void setSnapToTerrain (bool snapToTerrain)
void setSurfaceType (int surfaceType)
void setTintPallete (String tintPallete)
void setTotalCellNumber (int totalCellNumber)
void setFullTemplateString (const String &str)
void setTemplateFileName (const String &str)
virtual bool isArmorObjectTemplate ()
virtual bool isSharedBuildingObjectTemplate ()
virtual bool isSharedInstallationObjectTemplate ()
virtual bool isMissionTerminalTemplate ()
virtual bool isGamblingTerminalTemplate ()
virtual bool isFireworkObjectTemplate ()
virtual bool isCloningBuildingObjectTemplate ()
virtual bool isHospitalBuildingObjectTemplate ()
virtual bool isRecreationBuildingObjectTemplate ()
virtual bool isNonPlayerCreatureObjectTemplate ()
virtual bool isStimPackTemplate ()
virtual bool isStatePackTemplate ()
virtual bool isRangedStimPackTemplate ()
virtual bool isEnhancePackTemplate ()
virtual bool isCurePackTemplate ()
virtual bool isDotPackTemplate ()
virtual bool isWoundPackTemplate ()
virtual bool isSkillBuffTemplate ()
virtual bool isLairObjectTemplate ()
virtual bool isElevatorTerminalTemplate ()
virtual bool isInstrumentObjectTemplate ()
virtual bool isCampKitTemplate ()
virtual bool isCamoKitTemplate ()
virtual bool isCampStructureTemplate ()
virtual bool isDiceTemplate ()
virtual bool isVendorCreatureTemplate ()
virtual bool isCreatureHabitatTemplate ()
virtual bool isRepairToolTemplate ()
virtual bool isRobeObjectTemplate ()
virtual bool isLightsaberCrystalTemplate ()
virtual bool isShipChassisTemplate ()
virtual bool isShipDeedTemplate ()
virtual bool isRecycleToolTemplate ()
virtual bool isVehicleCustomKitTemplate ()
virtual bool isDnaSampleTemplate ()
virtual bool isPetDeedTemplate ()
Public Member Functions inherited from LuaTemplate
virtual ~LuaTemplate ()
Public Member Functions inherited from TemplateData
virtual ~TemplateData ()
Public Member Functions inherited from IffTemplate
virtual ~IffTemplate ()
Protected Attributes
Reference< StructureFootprint * > structureFootprint
BoolParam targetable
uint16 playerUseMask
int level
Vector< String > certificationsRequired
int maxCondition
uint32 optionsBitmask
uint32 pvpStatusBitmask
int useCount
int factoryCrateSize
bool sliceable
int faction
VectorMap< String, int > skillMods
Vector< short > * numberExperimentalProperties
Vector< String > * experimentalProperties
Vector< short > * experimentalWeights
Vector< String > * experimentalGroupTitles
Vector< String > * experimentalSubGroupTitles
Vector< float > * experimentalMin
Vector< float > * experimentalMax
Vector< short > * experimentalPrecision
Vector< short > * experimentalCombineType
Vector< uint32 > * playerRaces
Vector< Reference
< ResourceWeight * > > * resourceWeights
Protected Attributes inherited from server::zone::templates::SharedObjectTemplate
StringIdParam objectName
StringIdParam detailedDescription
StringIdParam lookAtText
BoolParam snapToTerrain
IntegerParam containerType
IntegerParam containerVolumeLimit
StringParam tintPallete
Reference
< ArrangementDescriptor * > arrangementDescriptors
Reference< SlotDescriptor * > slotDescriptors
StringParam appearanceFilename
StringParam portalLayoutFilename
int totalCellNumber
StringParam clientDataFile
IntegerParam collisionMaterialFlags
IntegerParam collisionMaterialPassFlags
FloatParam scale
IntegerParam collisionMaterialBlockFlags
IntegerParam collisionActionFlags
IntegerParam collisionActionPassFlags
IntegerParam collisionActionBlockFlags
IntegerParam gameObjectType
int clientGameObjectType
BoolParam sendToClient
FloatParam scaleThresholdBeforeExtentTest
FloatParam clearFloraRadius
IntegerParam surfaceType
FloatParam noBuildRadius
BoolParam onlyVisibleInTools
FloatParam locationReservationRadius
String clientTemplateFileName
Reference< PlanetMapCategory * > planetMapCategory
Reference< PlanetMapCategory * > planetMapSubCategory
bool autoRegisterWithPlanetMap
String fullTemplateString
String templateFileName
int templateType
Vector< ChildObject > childObjects
PortalLayout * portalLayout
AppearanceTemplate * appearanceTemplate
bool loadedPortalLayout
bool loadedAppearanceTemplate
String zoneComponent
String attributeListComponent
SceneObjectComponent * containerComponent
SceneObjectComponent * objectMenuComponent
String dataObjectComponent
bool inheritPermissionsFromParent
HashTable< uint32, uint32 > groupPermissions
SortedVector< String > loadedDerivedFiles
bool noTrade
Additional Inherited Members
Static Public Member Functions inherited from server::zone::templates::SharedObjectTemplate
static String getType (int type)
Static Public Attributes inherited from server::zone::templates::SharedObjectTemplate
static const int SHOT = 'SHOT'
static const int STOT = 'STOT'
static const int SBMK = 'SBMK'
static const int SBOT = 'SBOT'
static const int STAT = 'STAT'
static const int SIOT = 'SIOT'
static const int CCLT = 'CCLT'
static const int SCOU = 'SCOU'
static const int SDSC = 'SDSC'
static const int SFOT = 'SFOT'
static const int SGRP = 'SGRP'
static const int SITN = 'SITN'
static const int SGLD = 'SGLD'
static const int SJED = 'SJED'
static const int SMSC = 'SMSC'
static const int SMSO = 'SMSO'
static const int SMSD = 'SMSD'
static const int SMLE = 'SMLE'
static const int SPLY = 'SPLY'
static const int RCCT = 'RCCT'
static const int SSHP = 'SSHP'
static const int SUNI = 'SUNI'
static const int SWAY = 'SWAY'
static const int STOK = 'STOK'
static const int SWOT = 'SWOT'
static const int SCNC = 'SCNC'
static const int SCOT = 'SCOT'
static const int CHARACTERBUILDERTERMINAL = 0x4000001
static const int SURVEYTOOL = 0x4000002
static const int RESOURCESPAWN = 0x4000003
static const int RESOURCECONTAINER = 0x4000004
static const int ARMOROBJECT = 0x4000005
static const int DEED = 0x4000006
static const int CRAFTINGTOOL = 0x4000007
static const int CRAFTINGSTATION = 0x4000008
static const int MISSIONTERMINAL = 0x4000009
static const int CLONINGBUILDING = 0x400000A
static const int DRAFTSCHEMATIC = 0x400000B
static const int NPCCREATURE = 0x400000C
static const int LAIRTEMPLATE = 0x400000D
static const int FACTORY = 0x400000E
static const int STIMPACK = 0x400000F
static const int RANGEDSTIMPACK = 0x4000010
static const int ENHANCEPACK = 0x4000011
static const int CUREPACK = 0x4000012
static const int DOTPACK = 0x4000013
static const int WOUNDPACK = 0x4000014
static const int STATEPACK = 0x4000015
static const int CONSUMABLE = 0x4000016
static const int ELEVATORTERMINAL = 0x4000017
static const int GAMBLINGTERMINAL = 0x4000018
static const int LOOTKIT = 0x4000019
static const int INSTRUMENT = 0x400001A
static const int FIREWORK = 0x400001B
static const int VEHICLEDEED = 0x400001C
static const int CAMPKIT = 0x400001D
static const int PLAYERCREATURE = 0x400001E
static const int SLICINGTOOL = 0x400001F
static const int CONTAINER = 0x4000020
static const int VENDORCREATURE = 0x4000021
static const int LOOTSCHEMATIC = 0x4000022
static const int CAMPSTRUCTURE = 0x4000023
static const int HOSPITALBUILDING = 0x4000024
static const int RECREATIONBUILDING = 0x4000025
static const int TRAP = 0x4000026
static const int STRUCTUREDEED = 0x4000027
static const int CAMOKIT = 0x4000028
static const int POWERUP = 0x4000029
static const int DICE = 0x4000030
static const int LIVESAMPLE = 0x4000031
static const int CREATUREHABITAT = 0x4000032
static const int REPAIRTOOL = 0x4000033
static const int ROBEOBJECT = 0x4000034
static const int LIGHTSABERCRYSTAL = 0x4000035
static const int SHIPCHASSIS = 0x4000036
static const int SHIPDEED = 0x4000037
static const int RECYCLETOOL = 0x4000038
static const int DNASAMPLE = 0x4000039
static const int PETDEED = 0x4000040
static const int VEHICLECUSTOMKIT = 0x4000041
static const int SKILLBUFF = 0x4000042
Detailed Description
Definition at line 17 of file SharedTangibleObjectTemplate.h.
Constructor & Destructor Documentation
SharedTangibleObjectTemplate::SharedTangibleObjectTemplate ()
Definition at line 14 of file SharedTangibleObjectTemplate.cpp.
References experimentalCombineType, experimentalGroupTitles, experimentalMax, experimentalMin, experimentalPrecision, experimentalProperties, experimentalSubGroupTitles, experimentalWeights, faction, factoryCrateSize, numberExperimentalProperties, playerRaces, resourceWeights, and skillMods.
SharedTangibleObjectTemplate::~SharedTangibleObjectTemplate ()
Definition at line 35 of file SharedTangibleObjectTemplate.cpp.
References experimentalCombineType, experimentalGroupTitles, experimentalMax, experimentalMin, experimentalPrecision, experimentalProperties, experimentalSubGroupTitles, experimentalWeights, numberExperimentalProperties, playerRaces, and resourceWeights.
Member Function Documentation
Vector<String> SharedTangibleObjectTemplate::getCertificationsRequired () const inline
Definition at line 100 of file SharedTangibleObjectTemplate.h.
References certificationsRequired.
Vector<String>* SharedTangibleObjectTemplate::getExperimentalGroupTitles () inline
Definition at line 160 of file SharedTangibleObjectTemplate.h.
References experimentalGroupTitles.
Referenced by server::zone::managers::loot::LootManagerImplementation::setInitialObjectStats().
Vector<float>* SharedTangibleObjectTemplate::getExperimentalMax () inline
Definition at line 172 of file SharedTangibleObjectTemplate.h.
References experimentalMax.
Referenced by server::zone::managers::loot::LootManagerImplementation::setInitialObjectStats().
Vector<float>* SharedTangibleObjectTemplate::getExperimentalMin () inline
Definition at line 168 of file SharedTangibleObjectTemplate.h.
References experimentalMin.
Referenced by server::zone::managers::loot::LootManagerImplementation::setInitialObjectStats().
Vector<short >* SharedTangibleObjectTemplate::getExperimentalPrecision () inline
Definition at line 176 of file SharedTangibleObjectTemplate.h.
References experimentalPrecision.
Referenced by server::zone::managers::loot::LootManagerImplementation::setInitialObjectStats().
Vector<String>* SharedTangibleObjectTemplate::getExperimentalProperties () inline
Definition at line 152 of file SharedTangibleObjectTemplate.h.
References experimentalProperties.
Vector<String>* SharedTangibleObjectTemplate::getExperimentalSubGroupTitles () inline
Definition at line 164 of file SharedTangibleObjectTemplate.h.
References experimentalSubGroupTitles.
Referenced by server::zone::managers::loot::LootManagerImplementation::setInitialObjectStats().
Vector<short >* SharedTangibleObjectTemplate::getExperimentalWeights () inline
Definition at line 156 of file SharedTangibleObjectTemplate.h.
References experimentalWeights.
int SharedTangibleObjectTemplate::getFaction () const inline
Definition at line 120 of file SharedTangibleObjectTemplate.h.
References faction.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::loadTemplateData().
int SharedTangibleObjectTemplate::getFactoryCrateSize () const inline
Definition at line 112 of file SharedTangibleObjectTemplate.h.
References factoryCrateSize.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::createFactoryCrate().
int SharedTangibleObjectTemplate::getLevel () const inline
Definition at line 104 of file SharedTangibleObjectTemplate.h.
References level.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::loadTemplateData().
int SharedTangibleObjectTemplate::getMaxCondition () const inline
Definition at line 76 of file SharedTangibleObjectTemplate.h.
References maxCondition.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::loadTemplateData().
Vector<short >* SharedTangibleObjectTemplate::getNumberExperimentalProperties () inline
Definition at line 148 of file SharedTangibleObjectTemplate.h.
References numberExperimentalProperties.
uint32 SharedTangibleObjectTemplate::getOptionsBitmask () const inline
Definition at line 80 of file SharedTangibleObjectTemplate.h.
References optionsBitmask.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::loadTemplateData().
Vector<uint32>* SharedTangibleObjectTemplate::getPlayerRaces () inline
Definition at line 180 of file SharedTangibleObjectTemplate.h.
References playerRaces.
Referenced by server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), and PlayerContainerComponent::canAddObject().
uint16 SharedTangibleObjectTemplate::getPlayerUseMask () const inline
Definition at line 116 of file SharedTangibleObjectTemplate.h.
References playerUseMask.
uint32 SharedTangibleObjectTemplate::getPvpStatusBitmask () const inline
Definition at line 84 of file SharedTangibleObjectTemplate.h.
References pvpStatusBitmask.
Referenced by server::zone::objects::building::BuildingObjectImplementation::initializeTransientMembers(), and server::zone::objects::tangible::TangibleObjectImplementation::loadTemplateData().
Vector<Reference<ResourceWeight* > >* SharedTangibleObjectTemplate::getResourceWeights () inline
Definition at line 184 of file SharedTangibleObjectTemplate.h.
References resourceWeights.
Referenced by DraftSchematicObjectTemplate::getResourceWeights().
int SharedTangibleObjectTemplate::getSkillMod (const String & mod) inline
Definition at line 192 of file SharedTangibleObjectTemplate.h.
References skillMods.
VectorMap<String, int>* SharedTangibleObjectTemplate::getSkillMods () inline
Definition at line 188 of file SharedTangibleObjectTemplate.h.
References skillMods.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::addTemplateSkillMods(), server::zone::objects::structure::StructureObjectImplementation::addTemplateSkillMods(), ThrowTrapCommand::doQueueCommand(), server::zone::objects::tangible::TangibleObjectImplementation::getTemplateSkillMods(), server::zone::objects::structure::StructureObjectImplementation::removeTemplateSkillMods(), and server::zone::objects::tangible::TangibleObjectImplementation::removeTemplateSkillMods().
bool SharedTangibleObjectTemplate::getSliceable () const inline
Definition at line 144 of file SharedTangibleObjectTemplate.h.
References sliceable.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::loadTemplateData().
StructureFootprint* SharedTangibleObjectTemplate::getStructureFootprint () const inline
Definition at line 124 of file SharedTangibleObjectTemplate.h.
References structureFootprint.
Referenced by StructureManager::getStructureFootprint(), StructureManager::isInStructureFootprint(), StructureManager::placeStructure(), and server::zone::objects::player::sessions::PlaceStructureSessionImplementation::placeTemporaryNoBuildZone().
bool SharedTangibleObjectTemplate::getTargetable () const inline
Definition at line 128 of file SharedTangibleObjectTemplate.h.
References targetable.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::loadTemplateData().
int SharedTangibleObjectTemplate::getUseCount () const inline
Definition at line 108 of file SharedTangibleObjectTemplate.h.
References useCount.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::loadTemplateData().
bool SharedTangibleObjectTemplate::isSharedTangibleObjectTemplate () inline virtual
Reimplemented from server::zone::templates::SharedObjectTemplate.
Definition at line 196 of file SharedTangibleObjectTemplate.h.
void SharedTangibleObjectTemplate::parseFileData (IffStream * str)
Definition at line 49 of file SharedTangibleObjectTemplate.cpp.
References parseVariableData().
Referenced by readObject().
void SharedTangibleObjectTemplate::parseVariableData (const String & varName, Chunk * data)
Definition at line 221 of file SharedTangibleObjectTemplate.cpp.
References TemplateBase< V >::get(), TemplateManager::loadStructureFootprint(), StringParam::parse(), RangedIntCustomizationVariables::parse(), BoolParam::parse(), PaletteColorCustomizationVariables::parse(), structureFootprint, and targetable.
Referenced by parseFileData(), and readObject().
void SharedTangibleObjectTemplate::parseVariableData (const String & varName, LuaObject * data)
Definition at line 75 of file SharedTangibleObjectTemplate.cpp.
References certificationsRequired, experimentalCombineType, experimentalGroupTitles, experimentalMax, experimentalMin, experimentalPrecision, experimentalProperties, experimentalSubGroupTitles, experimentalWeights, faction, factoryCrateSize, level, TemplateManager::loadStructureFootprint(), maxCondition, numberExperimentalProperties, optionsBitmask, playerRaces, playerUseMask, pvpStatusBitmask, skillMods, sliceable, structureFootprint, targetable, and useCount.
void SharedTangibleObjectTemplate::readObject (LuaObject * templateData) virtual
Reimplemented from server::zone::templates::SharedObjectTemplate.
Reimplemented in DnaSampleTemplate, SharedWeaponObjectTemplate, PowerupTemplate, SharedCreatureObjectTemplate, TrapTemplate, PlayerCreatureTemplate, SharedInstallationObjectTemplate, ConsumableTemplate, ArmorObjectTemplate, DotPackTemplate, SharedStructureObjectTemplate, SharedBuildingObjectTemplate, DiceTemplate, CampStructureTemplate, CharacterBuilderTerminalTemplate, LootkitObjectTemplate, CurePackTemplate, LootSchematicTemplate, RepairToolTemplate, EnhancePackTemplate, RangedStimPackTemplate, ElevatorTerminalTemplate, SurveyToolTemplate, WoundPackTemplate, SkillBuffTemplate, CraftingStationTemplate, CraftingToolTemplate, LiveSampleTemplate, StatePackTemplate, StimPackTemplate, FireworkObjectTemplate, HospitalBuildingObjectTemplate, NonPlayerCreatureObjectTemplate, RecreationBuildingObjectTemplate, SlicingToolTemplate, VehicleDeedTemplate, VendorCreatureTemplate, CamoKitTemplate, ContainerTemplate, DeedTemplate, GamblingTerminalTemplate, LightsaberCrystalObjectTemplate, StructureDeedTemplate, CloningBuildingObjectTemplate, CreatureHabitatTemplate, PetDeedTemplate, SharedBattlefieldMarkerObjectTemplate, SharedCountingObjectTemplate, SharedFactoryObjectTemplate, SharedResourceContainerObjectTemplate, SharedShipObjectTemplate, VehicleCustomKitTemplate, MissionTerminalTemplate, RobeObjectTemplate, RecycleToolTemplate, InstrumentObjectTemplate, and CampKitTemplate.
Definition at line 310 of file SharedTangibleObjectTemplate.cpp.
References ResourceWeight::addProperties(), ResourceWeight::addWeight(), experimentalCombineType, experimentalGroupTitles, experimentalMax, experimentalMin, experimentalPrecision, experimentalProperties, experimentalSubGroupTitles, experimentalWeights, numberExperimentalProperties, parseVariableData(), and resourceWeights.
Referenced by CampKitTemplate::readObject(), InstrumentObjectTemplate::readObject(), MissionTerminalTemplate::readObject(), RobeObjectTemplate::readObject(), CreatureHabitatTemplate::readObject(), SharedResourceContainerObjectTemplate::readObject(), SharedShipObjectTemplate::readObject(), VehicleCustomKitTemplate::readObject(), SharedBattlefieldMarkerObjectTemplate::readObject(), SharedCountingObjectTemplate::readObject(), SharedFactoryObjectTemplate::readObject(), GamblingTerminalTemplate::readObject(), CamoKitTemplate::readObject(), LightsaberCrystalObjectTemplate::readObject(), DeedTemplate::readObject(), ContainerTemplate::readObject(), FireworkObjectTemplate::readObject(), SlicingToolTemplate::readObject(), StatePackTemplate::readObject(), StimPackTemplate::readObject(), LiveSampleTemplate::readObject(), CraftingToolTemplate::readObject(), SkillBuffTemplate::readObject(), CraftingStationTemplate::readObject(), WoundPackTemplate::readObject(), SurveyToolTemplate::readObject(), ElevatorTerminalTemplate::readObject(), EnhancePackTemplate::readObject(), CurePackTemplate::readObject(), LootSchematicTemplate::readObject(), RepairToolTemplate::readObject(), LootkitObjectTemplate::readObject(), CharacterBuilderTerminalTemplate::readObject(), DiceTemplate::readObject(), SharedBuildingObjectTemplate::readObject(), SharedStructureObjectTemplate::readObject(), DotPackTemplate::readObject(), ArmorObjectTemplate::readObject(), ConsumableTemplate::readObject(), TrapTemplate::readObject(), PowerupTemplate::readObject(), SharedCreatureObjectTemplate::readObject(), SharedInstallationObjectTemplate::readObject(), readObject(), SharedWeaponObjectTemplate::readObject(), and DnaSampleTemplate::readObject().
void SharedTangibleObjectTemplate::readObject (IffStream * iffStream) virtual
Reimplemented from server::zone::templates::SharedObjectTemplate.
Reimplemented in SharedWeaponObjectTemplate, SharedInstallationObjectTemplate, SharedCreatureObjectTemplate, SharedBuildingObjectTemplate, SharedBattlefieldMarkerObjectTemplate, SharedCountingObjectTemplate, SharedFactoryObjectTemplate, SharedResourceContainerObjectTemplate, and SharedShipObjectTemplate.
Definition at line 264 of file SharedTangibleObjectTemplate.cpp.
References server::zone::templates::SharedObjectTemplate::loadDerv(), parseFileData(), and readObject().
void SharedTangibleObjectTemplate::setCertificationsRequired (Vector< String > certificationsRequired) inline
Definition at line 132 of file SharedTangibleObjectTemplate.h.
References certificationsRequired.
void SharedTangibleObjectTemplate::setMaxCondition (int maxCondition) inline
Definition at line 88 of file SharedTangibleObjectTemplate.h.
References maxCondition.
void SharedTangibleObjectTemplate::setOptionsBitmask (uint32 optionsBitmask) inline
Definition at line 92 of file SharedTangibleObjectTemplate.h.
References optionsBitmask.
void SharedTangibleObjectTemplate::setPlayerUseMask (uint16 playerUseMask) inline
Definition at line 136 of file SharedTangibleObjectTemplate.h.
References playerUseMask.
void SharedTangibleObjectTemplate::setPvpStatusBitmask (uint32 pvpStatusBitmask) inline
Definition at line 96 of file SharedTangibleObjectTemplate.h.
References pvpStatusBitmask.
void SharedTangibleObjectTemplate::setTargetable (bool targetable) inline
Definition at line 140 of file SharedTangibleObjectTemplate.h.
References targetable.
Member Data Documentation
Vector<String> SharedTangibleObjectTemplate::certificationsRequired protected
Definition at line 32 of file SharedTangibleObjectTemplate.h.
Referenced by getCertificationsRequired(), parseVariableData(), and setCertificationsRequired().
Vector<short>* SharedTangibleObjectTemplate::experimentalCombineType protected
Definition at line 57 of file SharedTangibleObjectTemplate.h.
Referenced by parseVariableData(), readObject(), SharedTangibleObjectTemplate(), and ~SharedTangibleObjectTemplate().
Vector<String>* SharedTangibleObjectTemplate::experimentalGroupTitles protected
Definition at line 52 of file SharedTangibleObjectTemplate.h.
Referenced by getExperimentalGroupTitles(), parseVariableData(), readObject(), SharedTangibleObjectTemplate(), and ~SharedTangibleObjectTemplate().
Vector<float>* SharedTangibleObjectTemplate::experimentalMax protected
Definition at line 55 of file SharedTangibleObjectTemplate.h.
Referenced by getExperimentalMax(), parseVariableData(), readObject(), SharedTangibleObjectTemplate(), and ~SharedTangibleObjectTemplate().
Vector<float>* SharedTangibleObjectTemplate::experimentalMin protected
Definition at line 54 of file SharedTangibleObjectTemplate.h.
Referenced by getExperimentalMin(), parseVariableData(), readObject(), SharedTangibleObjectTemplate(), and ~SharedTangibleObjectTemplate().
Vector<short>* SharedTangibleObjectTemplate::experimentalPrecision protected
Definition at line 56 of file SharedTangibleObjectTemplate.h.
Referenced by getExperimentalPrecision(), parseVariableData(), readObject(), SharedTangibleObjectTemplate(), and ~SharedTangibleObjectTemplate().
Vector<String>* SharedTangibleObjectTemplate::experimentalProperties protected
Definition at line 50 of file SharedTangibleObjectTemplate.h.
Referenced by getExperimentalProperties(), parseVariableData(), readObject(), SharedTangibleObjectTemplate(), and ~SharedTangibleObjectTemplate().
Vector<String>* SharedTangibleObjectTemplate::experimentalSubGroupTitles protected
Definition at line 53 of file SharedTangibleObjectTemplate.h.
Referenced by getExperimentalSubGroupTitles(), parseVariableData(), readObject(), SharedTangibleObjectTemplate(), and ~SharedTangibleObjectTemplate().
Vector<short>* SharedTangibleObjectTemplate::experimentalWeights protected
Definition at line 51 of file SharedTangibleObjectTemplate.h.
Referenced by getExperimentalWeights(), parseVariableData(), readObject(), SharedTangibleObjectTemplate(), and ~SharedTangibleObjectTemplate().
int SharedTangibleObjectTemplate::faction protected
Definition at line 45 of file SharedTangibleObjectTemplate.h.
Referenced by getFaction(), parseVariableData(), and SharedTangibleObjectTemplate().
int SharedTangibleObjectTemplate::factoryCrateSize protected
Definition at line 41 of file SharedTangibleObjectTemplate.h.
Referenced by getFactoryCrateSize(), parseVariableData(), and SharedTangibleObjectTemplate().
int SharedTangibleObjectTemplate::level protected
Definition at line 30 of file SharedTangibleObjectTemplate.h.
Referenced by getLevel(), and parseVariableData().
int SharedTangibleObjectTemplate::maxCondition protected
Definition at line 34 of file SharedTangibleObjectTemplate.h.
Referenced by getMaxCondition(), parseVariableData(), and setMaxCondition().
Vector<short>* SharedTangibleObjectTemplate::numberExperimentalProperties protected
Definition at line 49 of file SharedTangibleObjectTemplate.h.
Referenced by getNumberExperimentalProperties(), parseVariableData(), readObject(), SharedTangibleObjectTemplate(), and ~SharedTangibleObjectTemplate().
uint32 SharedTangibleObjectTemplate::optionsBitmask protected
Definition at line 36 of file SharedTangibleObjectTemplate.h.
Referenced by getOptionsBitmask(), parseVariableData(), and setOptionsBitmask().
Vector<uint32>* SharedTangibleObjectTemplate::playerRaces protected
Definition at line 58 of file SharedTangibleObjectTemplate.h.
Referenced by getPlayerRaces(), parseVariableData(), SharedTangibleObjectTemplate(), and ~SharedTangibleObjectTemplate().
uint16 SharedTangibleObjectTemplate::playerUseMask protected
Definition at line 28 of file SharedTangibleObjectTemplate.h.
Referenced by getPlayerUseMask(), parseVariableData(), and setPlayerUseMask().
uint32 SharedTangibleObjectTemplate::pvpStatusBitmask protected
Definition at line 37 of file SharedTangibleObjectTemplate.h.
Referenced by getPvpStatusBitmask(), parseVariableData(), and setPvpStatusBitmask().
Vector<Reference<ResourceWeight* > >* SharedTangibleObjectTemplate::resourceWeights protected
Definition at line 60 of file SharedTangibleObjectTemplate.h.
Referenced by getResourceWeights(), readObject(), SharedTangibleObjectTemplate(), and ~SharedTangibleObjectTemplate().
VectorMap<String, int> SharedTangibleObjectTemplate::skillMods protected
Definition at line 47 of file SharedTangibleObjectTemplate.h.
Referenced by getSkillMod(), getSkillMods(), parseVariableData(), and SharedTangibleObjectTemplate().
bool SharedTangibleObjectTemplate::sliceable protected
Definition at line 43 of file SharedTangibleObjectTemplate.h.
Referenced by getSliceable(), and parseVariableData().
Reference<StructureFootprint*> SharedTangibleObjectTemplate::structureFootprint protected
Definition at line 24 of file SharedTangibleObjectTemplate.h.
Referenced by getStructureFootprint(), and parseVariableData().
BoolParam SharedTangibleObjectTemplate::targetable protected
Definition at line 26 of file SharedTangibleObjectTemplate.h.
Referenced by getTargetable(), parseVariableData(), and setTargetable().
int SharedTangibleObjectTemplate::useCount protected
Definition at line 39 of file SharedTangibleObjectTemplate.h.
Referenced by getUseCount(), and parseVariableData().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/SharedTangibleObjectTemplate.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/SharedTangibleObjectTemplate.cpp