Core3: server::zone::objects::intangible::VehicleControlObserver Class Reference
server::zone::objects::intangible::VehicleControlObserver Class Reference
#include <VehicleControlObserver.h>
Public Member Functions
VehicleControlObserver (VehicleControlDevice *device)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
VehicleControlObserver (DummyConstructorParameter *param)
virtual ~VehicleControlObserver ()
Friends
class VehicleControlObserverHelper
Detailed Description
Definition at line 63 of file VehicleControlObserver.h.
Constructor & Destructor Documentation
VehicleControlObserver::VehicleControlObserver (VehicleControlDevice * device)
Definition at line 17 of file VehicleControlObserver.cpp.
References server::zone::objects::intangible::VehicleControlObserverImplementation::_setStub().
VehicleControlObserver::VehicleControlObserver (DummyConstructorParameter * param) protected
Definition at line 24 of file VehicleControlObserver.cpp.
VehicleControlObserver::~VehicleControlObserver () protected virtual
Definition at line 28 of file VehicleControlObserver.cpp.
Member Function Documentation
DistributedObjectServant * VehicleControlObserver::_getImplementation ()
Definition at line 50 of file VehicleControlObserver.cpp.
Referenced by notifyObserverEvent().
DistributedObjectServant * VehicleControlObserver::_getImplementationForRead ()
Definition at line 56 of file VehicleControlObserver.cpp.
void VehicleControlObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 60 of file VehicleControlObserver.cpp.
int VehicleControlObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 33 of file VehicleControlObserver.cpp.
References _getImplementation(), server::zone::objects::intangible::VehicleControlObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class VehicleControlObserverHelper friend
Definition at line 79 of file VehicleControlObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/intangible/VehicleControlObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/intangible/VehicleControlObserver.cpp