Core3: server::zone::objects::tangible::pharmaceutical::RangedStimPackAdapter Class Reference
server::zone::objects::tangible::pharmaceutical::RangedStimPackAdapter Class Reference
#include <RangedStimPack.h>
Public Member Functions
RangedStimPackAdapter (RangedStimPack *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
unsigned int calculatePower (CreatureObject *healer, CreatureObject *patient, bool applyBattleFatigue)
float getRange (CreatureObject *creature)
float getEffectiveness ()
float getArea ()
bool isArea ()
float getRangeMod ()
bool isRangedStimPack ()
Public Member Functions inherited from server::zone::objects::tangible::pharmaceutical::StimPackAdapter
StimPackAdapter (StimPack *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
unsigned int calculatePower (CreatureObject *healer, CreatureObject *patient, bool applyBattleFatigue)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getEffectiveness ()
bool isStimPack ()
Public Member Functions inherited from server::zone::objects::tangible::pharmaceutical::PharmaceuticalObjectAdapter
PharmaceuticalObjectAdapter (PharmaceuticalObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int getMedicineUseRequired ()
float getRange (CreatureObject *creature)
bool isArea ()
float getArea ()
bool isPharmaceuticalObject ()
bool isStimPack ()
bool isRangedStimPack ()
bool isEnhancePack ()
bool isWoundPack ()
bool isCurePack ()
bool isStatePack ()
bool isRevivePack ()
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectAdapter
TangibleObjectAdapter (TangibleObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeMembers ()
void applySkillModsTo (CreatureObject *creature, bool doCheck)
void removeSkillModsFrom (CreatureObject *creature)
void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient)
void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient)
void removeAllSkillModsOfType (const int skillType, bool notifyClient)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void sendBaselinesTo (SceneObject *player)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
void removeDefenders ()
void setCombatState ()
void setUseCount (unsigned int newUseCount, bool notifyClient)
void setCountdownTimer (unsigned int newCount, bool notifyClient)
void decreaseUseCount ()
void clearCombatState (bool clearDefenders)
bool hasDefender (SceneObject *defender)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
bool isHealableBy (CreatureObject *object)
void sendPvpStatusTo (CreatureObject *player)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient)
int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient)
void setConditionDamage (float condDamage, bool notifyClient)
void setCustomizationVariable (byte type, short value, bool notifyClient)
void setCustomizationVariable (const String &type, short value, bool notifyClient)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
bool isKiller ()
bool isTicketCollector ()
bool isTicketObject ()
int getUseCount ()
int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient)
void setCraftersName (String &name)
String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
int getJunkDealerNeeded ()
void setJunkValue (int jValue)
int getJunkValue ()
void setSerialNumber (const String &serial)
void setLevel (int lev)
String getSerialNumber ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
String repairAttempt (int repairChance)
bool isBroken ()
float getHitChance ()
void broadcastPvpStatusBitmask ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectAdapter
SceneObjectAdapter (SceneObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializePrivateData ()
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient, bool allowOverflow)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects)
void destroyObjectFromDatabase (bool destroyContainedObjects)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose)
void sendAttributeListTo (CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void openContainerTo (CreatureObject *player)
void closeContainerTo (CreatureObject *player, bool notify)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
unsigned long long getParentID ()
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
float getWorldPositionX ()
float getWorldPositionY ()
float getWorldPositionZ ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isDecoration ()
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZone (Zone *zone)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
bool containsChildObject (SceneObject *obj)
void createChildObjects ()
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
Detailed Description
Definition at line 313 of file RangedStimPack.h.
Constructor & Destructor Documentation
RangedStimPackAdapter::RangedStimPackAdapter (RangedStimPack * impl)
Definition at line 509 of file RangedStimPack.cpp.
Member Function Documentation
unsigned int RangedStimPackAdapter::calculatePower (CreatureObject * healer, CreatureObject * patient, bool applyBattleFatigue)
Definition at line 565 of file RangedStimPack.cpp.
Referenced by invokeMethod().
float RangedStimPackAdapter::getArea ()
Definition at line 577 of file RangedStimPack.cpp.
Referenced by invokeMethod().
float RangedStimPackAdapter::getEffectiveness ()
Definition at line 573 of file RangedStimPack.cpp.
Referenced by invokeMethod().
float RangedStimPackAdapter::getRange (CreatureObject * creature)
Definition at line 569 of file RangedStimPack.cpp.
Referenced by invokeMethod().
float RangedStimPackAdapter::getRangeMod ()
Definition at line 585 of file RangedStimPack.cpp.
Referenced by invokeMethod().
int RangedStimPackAdapter::handleObjectMenuSelect (CreatureObject * player, byte selectedID)
Definition at line 561 of file RangedStimPack.cpp.
Referenced by invokeMethod().
void RangedStimPackAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 512 of file RangedStimPack.cpp.
References calculatePower(), getArea(), getEffectiveness(), getRange(), getRangeMod(), handleObjectMenuSelect(), isArea(), isRangedStimPack(), RPC_CALCULATEPOWER__CREATUREOBJECT_CREATUREOBJECT_BOOL_, RPC_GETAREA__, RPC_GETEFFECTIVENESS__, RPC_GETRANGE__CREATUREOBJECT_, RPC_GETRANGEMOD__, RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_, RPC_ISAREA__, and RPC_ISRANGEDSTIMPACK__.
bool RangedStimPackAdapter::isArea ()
Definition at line 581 of file RangedStimPack.cpp.
Referenced by invokeMethod().
bool RangedStimPackAdapter::isRangedStimPack ()
Definition at line 589 of file RangedStimPack.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/pharmaceutical/RangedStimPack.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/pharmaceutical/RangedStimPack.cpp