Core3: CloneSpawnPoint Class Reference
CloneSpawnPoint Class Reference
#include <CloneSpawnPoint.h>
Public Member Functions
CloneSpawnPoint ()
CloneSpawnPoint (const CloneSpawnPoint &p)
void parseFromLua (LuaObject *luaObject)
float getPositionX () const
float getPositionY () const
float getPositionZ () const
Coordinate * getCoordinate ()
Quaternion * getDirection ()
int getCellID ()
Private Attributes
Coordinate coordinate
Quaternion direction
int cellid
Detailed Description
Definition at line 13 of file CloneSpawnPoint.h.
Constructor & Destructor Documentation
CloneSpawnPoint::CloneSpawnPoint () inline
Definition at line 18 of file CloneSpawnPoint.h.
CloneSpawnPoint::CloneSpawnPoint (const CloneSpawnPoint & p) inline
Definition at line 21 of file CloneSpawnPoint.h.
References cellid, coordinate, direction, getPositionX(), getPositionY(), and getPositionZ().
Member Function Documentation
int CloneSpawnPoint::getCellID () inline
Definition at line 60 of file CloneSpawnPoint.h.
References cellid.
Coordinate* CloneSpawnPoint::getCoordinate () inline
Definition at line 52 of file CloneSpawnPoint.h.
References coordinate.
Quaternion* CloneSpawnPoint::getDirection () inline
Definition at line 56 of file CloneSpawnPoint.h.
References direction.
float CloneSpawnPoint::getPositionX () const inline
Definition at line 40 of file CloneSpawnPoint.h.
References coordinate.
Referenced by CloneSpawnPoint().
float CloneSpawnPoint::getPositionY () const inline
Definition at line 44 of file CloneSpawnPoint.h.
References coordinate.
Referenced by CloneSpawnPoint().
float CloneSpawnPoint::getPositionZ () const inline
Definition at line 48 of file CloneSpawnPoint.h.
References coordinate.
Referenced by CloneSpawnPoint().
void CloneSpawnPoint::parseFromLua (LuaObject * luaObject) inline
Definition at line 30 of file CloneSpawnPoint.h.
References cellid, coordinate, and direction.
Referenced by CloningBuildingObjectTemplate::readObject().
Member Data Documentation
int CloneSpawnPoint::cellid private
Definition at line 16 of file CloneSpawnPoint.h.
Referenced by CloneSpawnPoint(), getCellID(), and parseFromLua().
Coordinate CloneSpawnPoint::coordinate private
Definition at line 14 of file CloneSpawnPoint.h.
Referenced by CloneSpawnPoint(), getCoordinate(), getPositionX(), getPositionY(), getPositionZ(), and parseFromLua().
Quaternion CloneSpawnPoint::direction private
Definition at line 15 of file CloneSpawnPoint.h.
Referenced by CloneSpawnPoint(), getDirection(), and parseFromLua().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/building/cloning/CloneSpawnPoint.h