Core3: server::zone::objects::area::areashapes::RectangularAreaShapeImplementation Class Reference
server::zone::objects::area::areashapes::RectangularAreaShapeImplementation Class Reference
#include <RectangularAreaShape.h>
Public Member Functions
RectangularAreaShapeImplementation ()
RectangularAreaShapeImplementation (DummyConstructorParameter *param)
void setDimensions (float h, float w)
virtual float getHeight ()
virtual float getWidth ()
virtual bool containsPoint (float x, float y)
virtual bool containsPoint (const Vector3 &point)
virtual Vector3 getRandomPosition ()
virtual Vector3 getRandomPosition (const Vector3 &origin, float minDistance, float maxDistance)
virtual bool isCircularAreaShape ()
virtual bool isRectangularAreaShape ()
virtual bool isRingAreaShape ()
virtual bool intersectsWith (AreaShape *areaShape)
virtual float getArea ()
operator const RectangularAreaShape * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
AreaShapeImplementation ()
AreaShapeImplementation (DummyConstructorParameter *param)
void setAreaCenter (float x, float y)
Vector3 getAreaCenter ()
virtual float getRadius ()
operator const AreaShape * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< RectangularAreaShape * > _this
Public Attributes inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
WeakReference< AreaShape * > _this
Protected Member Functions
virtual ~RectangularAreaShapeImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
virtual ~AreaShapeImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
float height
float width
Protected Attributes inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
Vector3 areaCenter
Private Member Functions
Vector3 getClosestPoint (const Vector3 &position)
Vector3 getFarthestPoint (const Vector3 &position)
Friends
class RectangularAreaShape
Detailed Description
Definition at line 150 of file RectangularAreaShape.h.
Constructor & Destructor Documentation
RectangularAreaShapeImplementation::RectangularAreaShapeImplementation ()
Definition at line 336 of file RectangularAreaShape.cpp.
References _initializeImplementation(), height, and width.
RectangularAreaShapeImplementation::RectangularAreaShapeImplementation (DummyConstructorParameter * param)
Definition at line 198 of file RectangularAreaShape.cpp.
References _initializeImplementation().
RectangularAreaShapeImplementation::~RectangularAreaShapeImplementation () protected virtual
Definition at line 203 of file RectangularAreaShape.cpp.
Member Function Documentation
DistributedObjectStub * RectangularAreaShapeImplementation::_getStub ()
Definition at line 223 of file RectangularAreaShape.cpp.
References _this.
void RectangularAreaShapeImplementation::_initializeImplementation () protected
Definition at line 210 of file RectangularAreaShape.cpp.
References _serializationHelperMethod(), and _this.
Referenced by RectangularAreaShapeImplementation().
void RectangularAreaShapeImplementation::_serializationHelperMethod () protected
Definition at line 259 of file RectangularAreaShape.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void RectangularAreaShapeImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 218 of file RectangularAreaShape.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::_setStub(), and _this.
Referenced by server::zone::objects::area::areashapes::RectangularAreaShape::RectangularAreaShape().
bool RectangularAreaShapeImplementation::containsPoint (float x, float y) virtual
Check if the coordinate is within the area shape.
Parameters
x the x coordinate.
y the y coordinate.
Returns
true if the coordinate is within the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 12 of file RectangularAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, height, and width.
Referenced by server::zone::objects::area::areashapes::RectangularAreaShape::containsPoint(), containsPoint(), and getRandomPosition().
bool RectangularAreaShapeImplementation::containsPoint (const Vector3 & point) virtual
Check if the coordinate is within the area shape.
Parameters
point the point to check if it is within the area shape.
Returns
true if the coordinate is within the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 21 of file RectangularAreaShapeImplementation.cpp.
References containsPoint().
void RectangularAreaShapeImplementation::finalize () protected
Definition at line 207 of file RectangularAreaShape.cpp.
float RectangularAreaShapeImplementation::getArea () virtual
Get the area of the areaShape.
Returns
the area of the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 376 of file RectangularAreaShape.cpp.
References height, and width.
Referenced by server::zone::objects::area::areashapes::RectangularAreaShape::getArea().
Vector3 RectangularAreaShapeImplementation::getClosestPoint (const Vector3 & position) private
Calculates the point in the area that has the shortest distance to the supplied position.
Parameters
position the position to find the closest point towards.
Returns
the closest point inside the area.
Definition at line 65 of file RectangularAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, height, and width.
Referenced by intersectsWith().
Vector3 RectangularAreaShapeImplementation::getFarthestPoint (const Vector3 & position) private
Calculates the point in the area that has the longest distance to the supplied position.
Parameters
position the position to find the closest point towards.
Returns
the farthest point inside the area.
Definition at line 100 of file RectangularAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, height, and width.
Referenced by intersectsWith().
float RectangularAreaShapeImplementation::getHeight () virtual
Get the height of the rectangle.
Returns
height of the rectangle.
Definition at line 351 of file RectangularAreaShape.cpp.
References height.
Referenced by server::zone::objects::area::areashapes::RectangularAreaShape::getHeight().
Vector3 RectangularAreaShapeImplementation::getRandomPosition () virtual
Generate a random position within the area.
Returns
a random position within the area.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 25 of file RectangularAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, height, and width.
Referenced by server::zone::objects::area::areashapes::RectangularAreaShape::getRandomPosition().
Vector3 RectangularAreaShapeImplementation::getRandomPosition (const Vector3 & origin, float minDistance, float maxDistance) virtual
Generate a random position within the area with the supplied origin and radius as limits.
Parameters
origin the origin coordinate to generate the random position from.
minDistance the minimum distance from the origin.
maxDistance the maximum distance from the origin.
Returns
a random position within the area.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 35 of file RectangularAreaShapeImplementation.cpp.
References containsPoint().
float RectangularAreaShapeImplementation::getWidth () virtual
Get the width of the rectangle.
Returns
width of the rectangle.
Definition at line 356 of file RectangularAreaShape.cpp.
References width.
Referenced by server::zone::objects::area::areashapes::RectangularAreaShape::getWidth().
bool RectangularAreaShapeImplementation::intersectsWith (AreaShape * areaShape) virtual
Check if this area shape intersects with the supplied area shape.
Parameters
areaShape the area shape to check for intersections with.s
Returns
true if the area shapes intersects each other.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 50 of file RectangularAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShape::containsPoint(), server::zone::objects::area::areashapes::AreaShape::getAreaCenter(), getClosestPoint(), getFarthestPoint(), and server::zone::objects::area::areashapes::AreaShape::isRingAreaShape().
Referenced by server::zone::objects::area::areashapes::RectangularAreaShape::intersectsWith().
bool RectangularAreaShapeImplementation::isCircularAreaShape () virtual
Check if this is a circular area shape.
Returns
true if it is a circular area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 361 of file RectangularAreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::RectangularAreaShape::isCircularAreaShape().
bool RectangularAreaShapeImplementation::isRectangularAreaShape () virtual
Check if this is a rectangular area shape.
Returns
true if it is a rectangular area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 366 of file RectangularAreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::RectangularAreaShape::isRectangularAreaShape().
bool RectangularAreaShapeImplementation::isRingAreaShape () virtual
Check if this is a ring area shape.
Returns
true if it is a ring area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 371 of file RectangularAreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::RectangularAreaShape::isRingAreaShape().
void RectangularAreaShapeImplementation::lock (bool doLock = true) protected
Definition at line 231 of file RectangularAreaShape.cpp.
References _this.
void RectangularAreaShapeImplementation::lock (ManagedObject * obj) protected
Definition at line 235 of file RectangularAreaShape.cpp.
References _this.
RectangularAreaShapeImplementation::operator const RectangularAreaShape * ()
Definition at line 227 of file RectangularAreaShape.cpp.
void RectangularAreaShapeImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 266 of file RectangularAreaShape.cpp.
References readObjectMember().
bool RectangularAreaShapeImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 285 of file RectangularAreaShape.cpp.
References height, server::zone::objects::area::areashapes::AreaShapeImplementation::readObjectMember(), and width.
Referenced by readObject().
void RectangularAreaShapeImplementation::rlock (bool doLock = true) protected
Definition at line 239 of file RectangularAreaShape.cpp.
References _this.
void RectangularAreaShapeImplementation::runlock (bool doLock = true) protected
Definition at line 255 of file RectangularAreaShape.cpp.
References _this.
void RectangularAreaShapeImplementation::setDimensions (float h, float w)
Set the dimensions of the rectangle.
Parameters
h the height of the rectangle.
w the width of the rectangle.
Definition at line 344 of file RectangularAreaShape.cpp.
References height, and width.
Referenced by server::zone::objects::area::areashapes::RectangularAreaShape::setDimensions().
void RectangularAreaShapeImplementation::unlock (bool doLock = true) protected
Definition at line 251 of file RectangularAreaShape.cpp.
References _this.
void RectangularAreaShapeImplementation::wlock (bool doLock = true) protected
Definition at line 243 of file RectangularAreaShape.cpp.
References _this.
void RectangularAreaShapeImplementation::wlock (ManagedObject * obj) protected
Definition at line 247 of file RectangularAreaShape.cpp.
References _this.
void RectangularAreaShapeImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 303 of file RectangularAreaShape.cpp.
References writeObjectMembers().
int RectangularAreaShapeImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 310 of file RectangularAreaShape.cpp.
References height, width, and server::zone::objects::area::areashapes::AreaShapeImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class RectangularAreaShape friend
Definition at line 293 of file RectangularAreaShape.h.
Member Data Documentation
WeakReference<RectangularAreaShape*> server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::_this
Definition at line 259 of file RectangularAreaShape.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
float server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::height protected
Definition at line 152 of file RectangularAreaShape.h.
Referenced by containsPoint(), getArea(), getClosestPoint(), getFarthestPoint(), getHeight(), getRandomPosition(), readObjectMember(), RectangularAreaShapeImplementation(), setDimensions(), and writeObjectMembers().
float server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::width protected
Definition at line 154 of file RectangularAreaShape.h.
Referenced by containsPoint(), getArea(), getClosestPoint(), getFarthestPoint(), getRandomPosition(), getWidth(), readObjectMember(), RectangularAreaShapeImplementation(), setDimensions(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RectangularAreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RectangularAreaShape.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RectangularAreaShapeImplementation.cpp