Core3: PermissionsServlet Class Reference
PermissionsServlet Class Reference
#include <PermissionsServlet.h>
Public Member Functions
PermissionsServlet (String context)
virtual ~PermissionsServlet ()
void handleGet (HttpRequest *request, HttpResponse *response)
void handlePost (HttpRequest *request, HttpResponse *response)
Public Member Functions inherited from Servlet
Servlet (String context)
virtual ~Servlet ()
void handleRequest (struct mg_connection *conn, HttpRequest *request, HttpResponse *response)
void setZoneServer (ZoneServer *serv)
String getContext ()
Additional Inherited Members
Protected Attributes inherited from Servlet
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 13 of file PermissionsServlet.h.
Constructor & Destructor Documentation
PermissionsServlet::PermissionsServlet (String context)
Definition at line 14 of file PermissionsServlet.cpp.
PermissionsServlet::~PermissionsServlet () virtual
Definition at line 20 of file PermissionsServlet.cpp.
Member Function Documentation
void PermissionsServlet::handleGet (HttpRequest * request, HttpResponse * response) virtual
Implements Servlet.
Definition at line 24 of file PermissionsServlet.cpp.
References server::web::HttpResponse::println().
void PermissionsServlet::handlePost (HttpRequest * request, HttpResponse * response) virtual
Implements Servlet.
Definition at line 54 of file PermissionsServlet.cpp.
References server::zone::managers::player::PlayerManager::getAccount(), CharacterListEntry::getFirstName(), server::web::HttpRequest::getParameter(), server::zone::managers::player::PlayerManager::getPlayer(), server::web::HttpResponse::println(), Servlet::server, and server::zone::managers::player::PlayerManager::updatePermissionLevel().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/servlets/permissions/PermissionsServlet.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/servlets/permissions/PermissionsServlet.cpp