Core3: FilterBitmap Class Reference
FilterBitmap Class Reference
#include <FilterBitmap.h>
Public Member Functions
FilterBitmap ()
void parseFromIffStream (engine::util::IffStream *iffStream)
void parseFromIffStream (engine::util::IffStream *iffStream, Version<'0000'>)
float process (float x, float y, float transformValue, float &baseValue, TerrainGenerator *terrainGenerator, FilterRectangle *rect)
bool isEnabled ()
Public Member Functions inherited from ProceduralRule<'FBIT'>
ProceduralRule ()
bool isEnabled ()
Public Member Functions inherited from TemplateVariable< formType >
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Public Member Functions inherited from FilterProceduralRule
FilterProceduralRule (int type)
virtual ~FilterProceduralRule ()
int getFeatheringType ()
int getFilterType ()
int getInternalType ()
bool isType (int type)
Private Attributes
int bitmapId
float min
float max
TargaBitmap * map
Additional Inherited Members
Static Public Attributes inherited from FilterProceduralRule
static const int HEIGHTTYPE = 0x100
static const int ENVIRONMENT = 0x200
static const int HEIGHT = 0
static const int FRACTAL = 1
static const int SLOPE = 2
static const int DIRECTION = 3
static const int SHADER = 4
static const int BITMAP = 5
Protected Attributes inherited from ProceduralRule<'FBIT'>
InformationHeader informationHeader
Protected Attributes inherited from FilterProceduralRule
int featheringType
float featheringAmount
int filterType
int internalType
Detailed Description
Definition at line 18 of file FilterBitmap.h.
Constructor & Destructor Documentation
FilterBitmap::FilterBitmap () inline
Definition at line 28 of file FilterBitmap.h.
References map.
Member Function Documentation
bool FilterBitmap::isEnabled () inline virtual
Reimplemented from FilterProceduralRule.
Definition at line 70 of file FilterBitmap.h.
References ProceduralRule<'FBIT'>::informationHeader, and InformationHeader::isEnabled().
void FilterBitmap::parseFromIffStream (engine::util::IffStream * iffStream) inline virtual
Reimplemented from TemplateVariable< formType >.
Definition at line 32 of file FilterBitmap.h.
void FilterBitmap::parseFromIffStream (engine::util::IffStream * iffStream, Version<'0000'>) inline
Definition at line 49 of file FilterBitmap.h.
References bitmapId, FilterProceduralRule::featheringAmount, FilterProceduralRule::featheringType, ProceduralRule<'FBIT'>::informationHeader, max, min, and TemplateVariable< formType >::readObject().
float FilterBitmap::process (float x, float y, float transformValue, float & baseValue, TerrainGenerator * terrainGenerator, FilterRectangle * rect) virtual
Reimplemented from FilterProceduralRule.
Definition at line 14 of file FilterBitmap.cpp.
References bitmapId, FilterProceduralRule::featheringAmount, BitmapGroup::getBitmap(), TerrainGenerator::getBitmapGroup(), TargaBitmap::getData(), InformationHeader::getDescription(), TargaBitmap::getHeight(), TargaBitmap::getWidth(), ProceduralRule<'FBIT'>::informationHeader, map, max, FilterRectangle::maxX, FilterRectangle::maxY, min, FilterRectangle::minX, and FilterRectangle::minY.
Member Data Documentation
int FilterBitmap::bitmapId private
Definition at line 19 of file FilterBitmap.h.
Referenced by parseFromIffStream(), and process().
TargaBitmap* FilterBitmap::map private
Definition at line 25 of file FilterBitmap.h.
Referenced by FilterBitmap(), and process().
float FilterBitmap::max private
Definition at line 23 of file FilterBitmap.h.
Referenced by parseFromIffStream(), and process().
float FilterBitmap::min private
Definition at line 22 of file FilterBitmap.h.
Referenced by parseFromIffStream(), and process().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/layer/filters/FilterBitmap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/layer/filters/FilterBitmap.cpp