Core3: CustomizationVariables Class Reference
CustomizationVariables Class Reference
#include <CustomizationVariables.h>
Public Member Functions
CustomizationVariables ()
~CustomizationVariables ()
CustomizationVariables (const CustomizationVariables &cv)
CustomizationVariables & operator= (const CustomizationVariables &var)
CustomizationVariables & operator= (const String &custString)
void setVariable (uint8 type, int16 value)
void setVariable (const String &type, int16 value)
int16 getVariable (uint8 type)
int16 getVariable (int idx)
void getVariable (int idx, uint8 &type, int16 &value)
int getSize ()
void parseFromClientString (const String &custString)
void getData (String &ascii)
bool toString (String &ascii)
bool parseFromString (const String &str, int version=0)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
Private Attributes
uint8 unknown
Vector< uint8 > keyIndex
Detailed Description
Definition at line 50 of file CustomizationVariables.h.
Constructor & Destructor Documentation
CustomizationVariables::CustomizationVariables ()
Definition at line 51 of file CustomizationVariables.cpp.
References keyIndex, and unknown.
CustomizationVariables::~CustomizationVariables ()
Definition at line 62 of file CustomizationVariables.cpp.
CustomizationVariables::CustomizationVariables (const CustomizationVariables & cv)
Definition at line 66 of file CustomizationVariables.cpp.
References keyIndex, and unknown.
Member Function Documentation
void CustomizationVariables::getData (String & ascii)
Definition at line 114 of file CustomizationVariables.cpp.
References keyIndex, and unknown.
Referenced by ImageDesignData::getHairCustomizationString(), ImageDesignData::insertToMessage(), toBinaryStream(), and toString().
int CustomizationVariables::getSize () inline
Definition at line 79 of file CustomizationVariables.h.
int16 CustomizationVariables::getVariable (uint8 type) inline
Definition at line 69 of file CustomizationVariables.h.
int16 CustomizationVariables::getVariable (int idx) inline
Definition at line 73 of file CustomizationVariables.h.
void CustomizationVariables::getVariable (int idx, uint8 & type, int16 & value)
Definition at line 107 of file CustomizationVariables.cpp.
CustomizationVariables & CustomizationVariables::operator= (const CustomizationVariables & var)
Definition at line 78 of file CustomizationVariables.cpp.
References keyIndex, and unknown.
CustomizationVariables & CustomizationVariables::operator= (const String & custString)
Definition at line 72 of file CustomizationVariables.cpp.
References parseFromClientString().
bool CustomizationVariables::parseFromBinaryStream (ObjectInputStream * stream)
Definition at line 291 of file CustomizationVariables.cpp.
void CustomizationVariables::parseFromClientString (const String & custString)
Definition at line 157 of file CustomizationVariables.cpp.
References keyIndex, setVariable(), and unknown.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addCustomization(), server::zone::managers::player::creation::PlayerCreationManager::addHair(), ImageDesignManager::createHairObject(), operator=(), and ImageDesignData::parse().
bool CustomizationVariables::parseFromString (const String & str, int version = 0)
Definition at line 270 of file CustomizationVariables.cpp.
void CustomizationVariables::setVariable (uint8 type, int16 value)
Definition at line 91 of file CustomizationVariables.cpp.
References keyIndex.
Referenced by parseFromClientString(), ImageDesignData::setHairAttribute(), and setVariable().
void CustomizationVariables::setVariable (const String & type, int16 value)
Definition at line 101 of file CustomizationVariables.cpp.
References setVariable().
bool CustomizationVariables::toBinaryStream (ObjectOutputStream * stream)
Definition at line 282 of file CustomizationVariables.cpp.
References getData().
bool CustomizationVariables::toString (String & ascii)
Definition at line 259 of file CustomizationVariables.cpp.
References getData().
Member Data Documentation
Vector<uint8> CustomizationVariables::keyIndex private
Definition at line 53 of file CustomizationVariables.h.
Referenced by CustomizationVariables(), getData(), operator=(), parseFromClientString(), and setVariable().
uint8 CustomizationVariables::unknown private
Definition at line 51 of file CustomizationVariables.h.
Referenced by CustomizationVariables(), getData(), operator=(), and parseFromClientString().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/CustomizationVariables.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/CustomizationVariables.cpp