Core3: server::zone::managers::visibility::VisibilityManager Class Reference
server::zone::managers::visibility::VisibilityManager Class Reference
#include <VisibilityManager.h>
Public Member Functions
VisibilityManager ()
void login (CreatureObject *creature)
void logout (CreatureObject *creature)
void increaseVisibility (CreatureObject *creature)
void clearVisibility (CreatureObject *creature)
void performVisiblityDecay ()
Private Member Functions
void addPlayerToBountyList (CreatureObject *creature, int reward)
void removePlayerFromBountyList (CreatureObject *creature)
int calculateReward (float visibility)
float calculateVisibilityIncrease (CreatureObject *creature)
void decreaseVisibility (CreatureObject *creature)
Private Attributes
VectorMap< uint64,
ManagedReference
< CreatureObject * > > visibilityList
Mutex visibilityListLock
Static Private Attributes
static const int TERMINALVISIBILITYLIMIT = 24
static const String factionStringRebel = "rebel"
static const String factionStringImperial = "imperial"
static const unsigned int factionRebel = factionStringRebel.hashCode()
static const unsigned int factionImperial = factionStringImperial.hashCode()
Detailed Description
Visibility manager that handles visibility and listing on bounty hunter terminals.
Definition at line 59 of file VisibilityManager.h.
Constructor & Destructor Documentation
VisibilityManager::VisibilityManager ()
Constructor.
Definition at line 127 of file VisibilityManager.cpp.
Member Function Documentation
void VisibilityManager::addPlayerToBountyList (CreatureObject * creature, int reward) private
Add the player to the bounty list.
Parameters
creature the player to add.
reward the reward for the player bounty.
Definition at line 56 of file VisibilityManager.cpp.
References server::zone::managers::mission::MissionManager::addPlayerToBountyList(), server::zone::ZoneServer::getMissionManager(), server::zone::objects::scene::SceneObject::getObjectID(), and server::zone::objects::scene::SceneObject::getZoneServer().
Referenced by login().
int VisibilityManager::calculateReward (float visibility) private
Calculate/generate a reward for the player bounty.
Parameters
visibility the visibility of the player.
Returns
calculated/generated reward.
Definition at line 68 of file VisibilityManager.cpp.
Referenced by login().
float VisibilityManager::calculateVisibilityIncrease (CreatureObject * creature) private
Calculates the visibility increase for the player depending on the number of players and NPC's within 32 m.
Parameters
creature the player.
visibilityIncrease base increase for the action.
Definition at line 74 of file VisibilityManager.cpp.
References factionImperial, factionRebel, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::Zone::getInRangeObjects(), server::zone::objects::scene::SceneObject::getWorldPositionX(), server::zone::objects::scene::SceneObject::getWorldPositionY(), server::zone::objects::scene::SceneObject::getZone(), and server::zone::objects::scene::SceneObject::isCreatureObject().
Referenced by increaseVisibility().
void VisibilityManager::clearVisibility (CreatureObject * creature)
Clear the visibility for a player and remove him/her from the visibility list. Should be used when a player is killed from a bounty hunter with a mission for the player.
Parameters
creature the player to clear the visibility for.
Definition at line 181 of file VisibilityManager.cpp.
References server::zone::objects::scene::SceneObject::getSlottedObject(), and logout().
Referenced by decreaseVisibility().
void VisibilityManager::decreaseVisibility (CreatureObject * creature) private
Decrease visibility for a player. The player is removed from the visibility list if visibility goes beneath the listing level.
Parameters
creature the player to decrease the visibility for.
Definition at line 106 of file VisibilityManager.cpp.
References clearVisibility(), server::zone::objects::scene::SceneObject::getSlottedObject(), removePlayerFromBountyList(), and TERMINALVISIBILITYLIMIT.
Referenced by increaseVisibility(), login(), and performVisiblityDecay().
void VisibilityManager::increaseVisibility (CreatureObject * creature)
Increase visibility for a player. The player is added to the visibility list if not already in the list.
Parameters
creature the player to increase the visibility for.
Definition at line 166 of file VisibilityManager.cpp.
References calculateVisibilityIncrease(), decreaseVisibility(), server::zone::objects::scene::SceneObject::getSlottedObject(), and login().
void VisibilityManager::login (CreatureObject * creature)
Login a player and add it to the visibility list if he/she still has visibility.
Parameters
creature the player to login.
Definition at line 132 of file VisibilityManager.cpp.
References addPlayerToBountyList(), calculateReward(), decreaseVisibility(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getSlottedObject(), TERMINALVISIBILITYLIMIT, visibilityList, and visibilityListLock.
Referenced by increaseVisibility().
void VisibilityManager::logout (CreatureObject * creature)
Logout a player and remove him/her from the visibility list.
Parameters
creature the player to logout.
Definition at line 154 of file VisibilityManager.cpp.
References server::zone::objects::scene::SceneObject::getObjectID(), removePlayerFromBountyList(), visibilityList, and visibilityListLock.
Referenced by clearVisibility().
void VisibilityManager::performVisiblityDecay ()
Iterates through all currently online players and decays their visibility.
Definition at line 195 of file VisibilityManager.cpp.
References decreaseVisibility(), visibilityList, and visibilityListLock.
void VisibilityManager::removePlayerFromBountyList (CreatureObject * creature) private
Remove the player to the bounty list.
Parameters
creature the player to remove.
Definition at line 62 of file VisibilityManager.cpp.
References server::zone::ZoneServer::getMissionManager(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getZoneServer(), and server::zone::managers::mission::MissionManager::removePlayerFromBountyList().
Referenced by decreaseVisibility(), and logout().
Member Data Documentation
const unsigned int VisibilityManager::factionImperial = factionStringImperial.hashCode() static private
Imperial faction value.
Definition at line 85 of file VisibilityManager.h.
Referenced by calculateVisibilityIncrease().
const unsigned int VisibilityManager::factionRebel = factionStringRebel.hashCode() static private
Rebel faction value.
Definition at line 80 of file VisibilityManager.h.
Referenced by calculateVisibilityIncrease().
const String VisibilityManager::factionStringImperial = "imperial" static private
Imperial faction string.
Definition at line 75 of file VisibilityManager.h.
const String VisibilityManager::factionStringRebel = "rebel" static private
Rebel faction string.
Definition at line 70 of file VisibilityManager.h.
const int server::zone::managers::visibility::VisibilityManager::TERMINALVISIBILITYLIMIT = 24 static private
Any player with a visibility greater than or equal to this amount will be available on the bounty hunter mission terminal as a player bounty.
Definition at line 65 of file VisibilityManager.h.
Referenced by decreaseVisibility(), and login().
VectorMap<uint64, ManagedReference<CreatureObject*> > server::zone::managers::visibility::VisibilityManager::visibilityList private
Visibility list that contains all currently online players with visibility.
Definition at line 90 of file VisibilityManager.h.
Referenced by login(), logout(), and performVisiblityDecay().
Mutex server::zone::managers::visibility::VisibilityManager::visibilityListLock private
Mutex for the visibilityList.
Definition at line 95 of file VisibilityManager.h.
Referenced by login(), logout(), and performVisiblityDecay().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/visibility/VisibilityManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/visibility/VisibilityManager.cpp