Core3: server::zone::objects::mission::MissionObserver Class Reference
server::zone::objects::mission::MissionObserver Class Reference
#include <MissionObserver.h>
Public Member Functions
MissionObserver (MissionObjective *objective)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void destroyObjectFromDatabase ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
MissionObserver (DummyConstructorParameter *param)
virtual ~MissionObserver ()
Friends
class MissionObserverHelper
Detailed Description
Definition at line 67 of file MissionObserver.h.
Constructor & Destructor Documentation
MissionObserver::MissionObserver (MissionObjective * objective)
Definition at line 19 of file MissionObserver.cpp.
References server::zone::objects::mission::MissionObserverImplementation::_setStub().
MissionObserver::MissionObserver (DummyConstructorParameter * param) protected
Definition at line 26 of file MissionObserver.cpp.
MissionObserver::~MissionObserver () protected virtual
Definition at line 30 of file MissionObserver.cpp.
Member Function Documentation
DistributedObjectServant * MissionObserver::_getImplementation ()
Definition at line 65 of file MissionObserver.cpp.
Referenced by destroyObjectFromDatabase(), and notifyObserverEvent().
DistributedObjectServant * MissionObserver::_getImplementationForRead ()
Definition at line 71 of file MissionObserver.cpp.
void MissionObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 75 of file MissionObserver.cpp.
void MissionObserver::destroyObjectFromDatabase ()
Destroys this object from database
Precondition
{ this is locked }
Postcondition
{ this is locked }
Definition at line 52 of file MissionObserver.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObserverImplementation::destroyObjectFromDatabase(), and RPC_DESTROYOBJECTFROMDATABASE__.
Referenced by server::zone::objects::mission::MissionObjectiveImplementation::destroyObjectFromDatabase(), and server::zone::objects::mission::MissionObjectiveImplementation::dropObserver().
int MissionObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 35 of file MissionObserver.cpp.
References _getImplementation(), server::zone::objects::mission::MissionObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class MissionObserverHelper friend
Definition at line 90 of file MissionObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObserver.cpp