Core3: server::zone::managers::crafting::CraftingManagerImplementation Class Reference
server::zone::managers::crafting::CraftingManagerImplementation Class Reference
#include <CraftingManager.h>
Public Member Functions
CraftingManagerImplementation ()
CraftingManagerImplementation (DummyConstructorParameter *param)
void initialize ()
void awardSchematicGroup (PlayerObject *playerObject, Vector< String > &schematicgroups, bool updateClient=false)
void removeSchematicGroup (PlayerObject *playerObject, Vector< String > &schematicgroups, bool updateClient=false)
DraftSchematic * getSchematic (unsigned int schematicID)
void sendDraftSlotsTo (CreatureObject *player, unsigned int schematicID)
void sendResourceWeightsTo (CreatureObject *player, unsigned int schematicID)
int calculateAssemblySuccess (CreatureObject *player, DraftSchematic *draftSchematic, float effectiveness)
void experimentRow (ManufactureSchematic *schematic, CraftingValues *craftingValues, int rowEffected, int pointsAttempted, float failure, int experimentationResult)
int calculateExperimentationFailureRate (CreatureObject *player, ManufactureSchematic *manufactureSchematic, int pointsUsed)
int calculateExperimentationSuccess (CreatureObject *player, DraftSchematic *draftSchematic, float effectiveness)
String generateSerial ()
String checkBioSkillMods (const String &property)
void setInitialCraftingValues (TangibleObject *prototype, ManufactureSchematic *manufactureSchematic, int assemblySuccess)
bool allowManufactureSchematic (ManufactureSchematic *manufactureSchematic)
operator const CraftingManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::manager::ZoneManagerImplementation
ZoneManagerImplementation (const String &name)
ZoneManagerImplementation (DummyConstructorParameter *param)
void setZoneProcessor (ZoneProcessServer *server)
operator const ZoneManager * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< CraftingManager * > _this
Public Attributes inherited from server::zone::manager::ZoneManagerImplementation
WeakReference< ZoneManager * > _this
Static Public Attributes
static const short RESOURCECOMBINE = 0x00
static const short LINEARCOMBINE = 0x01
static const short PERCENTAGECOMBINE = 0x02
static const short BITSETCOMBINE = 0x03
static const short OVERRIDECOMBINE = 0x04
static const short CR = 1
static const short CD = 2
static const short DR = 3
static const short HR = 4
static const short FL = 5
static const short MA = 6
static const short PE = 7
static const short OQ = 8
static const short SR = 9
static const short UT = 10
static const short AMAZINGSUCCESS = 0
static const short GREATSUCCESS = 1
static const short GOODSUCCESS = 2
static const short MODERATESUCCESS = 3
static const short SUCCESS = 4
static const short MARGINALSUCCESS = 5
static const short OK = 6
static const short BARELYSUCCESSFUL = 7
static const short CRITICALFAILURE = 8
static const int RESOURCE_LAB = 0x00
static const int GENETIC_LAB = 0x01
Protected Member Functions
virtual ~CraftingManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::manager::ZoneManagerImplementation
virtual ~ZoneManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Member Functions
bool loadBioSkillMods ()
void configureLabratories ()
Private Attributes
Reference< SchematicMap * > schematicMap
SortedVector< String > bioMods
HashTable< int, Reference
< SharedLabratory * > > labs
Friends
class CraftingManager
Additional Inherited Members
Protected Attributes inherited from server::zone::manager::ZoneManagerImplementation
ManagedReference< ZoneServer * > zoneServer
ManagedReference
< ZoneProcessServer * > zoneProcessor
Reference< ObjectManager * > objectManager
Detailed Description
Definition at line 226 of file CraftingManager.h.
Constructor & Destructor Documentation
CraftingManagerImplementation::CraftingManagerImplementation ()
Definition at line 362 of file CraftingManager.cpp.
References _initializeImplementation().
CraftingManagerImplementation::CraftingManagerImplementation (DummyConstructorParameter * param)
Definition at line 248 of file CraftingManager.cpp.
References _initializeImplementation().
CraftingManagerImplementation::~CraftingManagerImplementation () protected virtual
Definition at line 253 of file CraftingManager.cpp.
Member Function Documentation
DistributedObjectStub * CraftingManagerImplementation::_getStub ()
Definition at line 273 of file CraftingManager.cpp.
References _this.
void CraftingManagerImplementation::_initializeImplementation () protected
Definition at line 260 of file CraftingManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by CraftingManagerImplementation().
void CraftingManagerImplementation::_serializationHelperMethod () protected
Definition at line 309 of file CraftingManager.cpp.
Referenced by _initializeImplementation().
void CraftingManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 268 of file CraftingManager.cpp.
References _this.
Referenced by server::zone::managers::crafting::CraftingManager::CraftingManager().
bool CraftingManagerImplementation::allowManufactureSchematic (ManufactureSchematic * manufactureSchematic)
Definition at line 157 of file CraftingManagerImplementation.cpp.
References server::zone::managers::crafting::labratories::SharedLabratory::allowFactoryRun(), server::zone::objects::manufactureschematic::ManufactureSchematic::getLabratory(), and labs.
Referenced by server::zone::managers::crafting::CraftingManager::allowManufactureSchematic().
void CraftingManagerImplementation::awardSchematicGroup (PlayerObject * playerObject, Vector< String > & schematicgroups, bool updateClient = false)
Definition at line 59 of file CraftingManagerImplementation.cpp.
References schematicMap.
Referenced by server::zone::managers::crafting::CraftingManager::awardSchematicGroup().
int CraftingManagerImplementation::calculateAssemblySuccess (CreatureObject * player, DraftSchematic * draftSchematic, float effectiveness)
City bonus should be 10
Definition at line 75 of file CraftingManagerImplementation.cpp.
References AMAZINGSUCCESS, BARELYSUCCESSFUL, BuffCRC::FOOD_CRAFT_BONUS, server::zone::objects::draftschematic::DraftSchematic::getAssemblySkill(), server::zone::objects::creature::CreatureObject::getBuff(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::buffs::Buff::getSkillModifierValue(), GOODSUCCESS, GREATSUCCESS, server::zone::objects::creature::CreatureObject::hasBuff(), MARGINALSUCCESS, MODERATESUCCESS, OK, and SUCCESS.
Referenced by server::zone::managers::crafting::CraftingManager::calculateAssemblySuccess().
int CraftingManagerImplementation::calculateExperimentationFailureRate (CreatureObject * player, ManufactureSchematic * manufactureSchematic, int pointsUsed)
Definition at line 142 of file CraftingManagerImplementation.cpp.
References server::zone::objects::manufactureschematic::ManufactureSchematic::getDraftSchematic(), server::zone::objects::draftschematic::DraftSchematic::getExperimentationSkill(), server::zone::objects::manufactureschematic::ManufactureSchematic::getLabratory(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::managers::crafting::labratories::SharedLabratory::getWeightedValue(), labs, and MA.
Referenced by server::zone::managers::crafting::CraftingManager::calculateExperimentationFailureRate().
int CraftingManagerImplementation::calculateExperimentationSuccess (CreatureObject * player, DraftSchematic * draftSchematic, float effectiveness)
Range 0-100
Definition at line 162 of file CraftingManagerImplementation.cpp.
References AMAZINGSUCCESS, BARELYSUCCESSFUL, BuffCRC::FOOD_EXPERIMENT_BONUS, server::zone::objects::draftschematic::DraftSchematic::getAssemblySkill(), server::zone::objects::creature::CreatureObject::getBuff(), server::zone::objects::draftschematic::DraftSchematic::getExperimentationSkill(), server::zone::objects::creature::CreatureObject::getSkillMod(), server::zone::objects::creature::buffs::Buff::getSkillModifierValue(), GOODSUCCESS, GREATSUCCESS, server::zone::objects::creature::CreatureObject::hasBuff(), MARGINALSUCCESS, MODERATESUCCESS, OK, and SUCCESS.
Referenced by server::zone::managers::crafting::CraftingManager::calculateExperimentationSuccess().
String CraftingManagerImplementation::checkBioSkillMods (const String & property)
Definition at line 286 of file CraftingManagerImplementation.cpp.
References bioMods.
Referenced by server::zone::managers::crafting::CraftingManager::checkBioSkillMods().
void CraftingManagerImplementation::configureLabratories () private
Definition at line 301 of file CraftingManagerImplementation.cpp.
References GENETIC_LAB, server::zone::managers::crafting::labratories::ResourceLabratory::initialize(), server::zone::managers::crafting::labratories::GeneticLabratory::initialize(), labs, RESOURCE_LAB, and server::zone::manager::ZoneManagerImplementation::zoneServer.
Referenced by initialize().
void CraftingManagerImplementation::experimentRow (ManufactureSchematic * schematic, CraftingValues * craftingValues, int rowEffected, int pointsAttempted, float failure, int experimentationResult)
Definition at line 255 of file CraftingManagerImplementation.cpp.
References server::zone::managers::crafting::labratories::SharedLabratory::experimentRow(), server::zone::objects::manufactureschematic::ManufactureSchematic::getLabratory(), and labs.
Referenced by server::zone::managers::crafting::CraftingManager::experimentRow().
void CraftingManagerImplementation::finalize () protected
Definition at line 257 of file CraftingManager.cpp.
String CraftingManagerImplementation::generateSerial ()
Definition at line 229 of file CraftingManagerImplementation.cpp.
Referenced by server::zone::managers::crafting::CraftingManager::generateSerial().
DraftSchematic * CraftingManagerImplementation::getSchematic (unsigned int schematicID)
Definition at line 366 of file CraftingManager.cpp.
References schematicMap.
Referenced by server::zone::managers::crafting::CraftingManager::getSchematic().
void CraftingManagerImplementation::initialize ()
Definition at line 52 of file CraftingManagerImplementation.cpp.
References configureLabratories(), loadBioSkillMods(), schematicMap, and server::zone::manager::ZoneManagerImplementation::zoneServer.
Referenced by server::zone::managers::crafting::CraftingManager::initialize().
bool CraftingManagerImplementation::loadBioSkillMods () private
Definition at line 262 of file CraftingManagerImplementation.cpp.
References bioMods.
Referenced by initialize().
void CraftingManagerImplementation::lock (bool doLock = true) protected
Definition at line 281 of file CraftingManager.cpp.
References _this.
void CraftingManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 285 of file CraftingManager.cpp.
References _this.
CraftingManagerImplementation::operator const CraftingManager * ()
Definition at line 277 of file CraftingManager.cpp.
void CraftingManagerImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::manager::ZoneManagerImplementation.
Definition at line 316 of file CraftingManager.cpp.
References readObjectMember().
bool CraftingManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 335 of file CraftingManager.cpp.
Referenced by readObject().
void CraftingManagerImplementation::removeSchematicGroup (PlayerObject * playerObject, Vector< String > & schematicgroups, bool updateClient = false)
Definition at line 63 of file CraftingManagerImplementation.cpp.
References schematicMap.
Referenced by server::zone::managers::crafting::CraftingManager::removeSchematicGroup().
void CraftingManagerImplementation::rlock (bool doLock = true) protected
Definition at line 289 of file CraftingManager.cpp.
References _this.
void CraftingManagerImplementation::runlock (bool doLock = true) protected
Definition at line 305 of file CraftingManager.cpp.
References _this.
void CraftingManagerImplementation::sendDraftSlotsTo (CreatureObject * player, unsigned int schematicID)
Definition at line 67 of file CraftingManagerImplementation.cpp.
References schematicMap.
Referenced by server::zone::managers::crafting::CraftingManager::sendDraftSlotsTo().
void CraftingManagerImplementation::sendResourceWeightsTo (CreatureObject * player, unsigned int schematicID)
Definition at line 71 of file CraftingManagerImplementation.cpp.
References schematicMap.
Referenced by server::zone::managers::crafting::CraftingManager::sendResourceWeightsTo().
void CraftingManagerImplementation::setInitialCraftingValues (TangibleObject * prototype, ManufactureSchematic * manufactureSchematic, int assemblySuccess)
Definition at line 310 of file CraftingManagerImplementation.cpp.
References server::zone::objects::manufactureschematic::ManufactureSchematic::getDraftSchematic(), server::zone::objects::manufactureschematic::ManufactureSchematic::getLabratory(), labs, and server::zone::managers::crafting::labratories::SharedLabratory::setInitialCraftingValues().
Referenced by server::zone::managers::crafting::CraftingManager::setInitialCraftingValues().
void CraftingManagerImplementation::unlock (bool doLock = true) protected
Definition at line 301 of file CraftingManager.cpp.
References _this.
void CraftingManagerImplementation::wlock (bool doLock = true) protected
Definition at line 293 of file CraftingManager.cpp.
References _this.
void CraftingManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 297 of file CraftingManager.cpp.
References _this.
void CraftingManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::manager::ZoneManagerImplementation.
Definition at line 345 of file CraftingManager.cpp.
References writeObjectMembers().
int CraftingManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 352 of file CraftingManager.cpp.
Referenced by writeObject().
Friends And Related Function Documentation
friend class CraftingManager friend
Definition at line 362 of file CraftingManager.h.
Member Data Documentation
WeakReference<CraftingManager*> server::zone::managers::crafting::CraftingManagerImplementation::_this
Definition at line 328 of file CraftingManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
const short server::zone::managers::crafting::CraftingManagerImplementation::AMAZINGSUCCESS = 0 static
Definition at line 260 of file CraftingManager.h.
Referenced by calculateAssemblySuccess(), and calculateExperimentationSuccess().
const short server::zone::managers::crafting::CraftingManagerImplementation::BARELYSUCCESSFUL = 7 static
Definition at line 274 of file CraftingManager.h.
Referenced by calculateAssemblySuccess(), and calculateExperimentationSuccess().
SortedVector<String> server::zone::managers::crafting::CraftingManagerImplementation::bioMods private
Definition at line 283 of file CraftingManager.h.
Referenced by checkBioSkillMods(), and loadBioSkillMods().
const short server::zone::managers::crafting::CraftingManagerImplementation::BITSETCOMBINE = 0x03 static
Definition at line 236 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManagerImplementation::CD = 2 static
Definition at line 242 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManagerImplementation::CR = 1 static
Definition at line 240 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManagerImplementation::CRITICALFAILURE = 8 static
Definition at line 276 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManagerImplementation::DR = 3 static
Definition at line 244 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManagerImplementation::FL = 5 static
Definition at line 248 of file CraftingManager.h.
const int server::zone::managers::crafting::CraftingManagerImplementation::GENETIC_LAB = 0x01 static
Definition at line 280 of file CraftingManager.h.
Referenced by configureLabratories().
const short server::zone::managers::crafting::CraftingManagerImplementation::GOODSUCCESS = 2 static
Definition at line 264 of file CraftingManager.h.
Referenced by calculateAssemblySuccess(), and calculateExperimentationSuccess().
const short server::zone::managers::crafting::CraftingManagerImplementation::GREATSUCCESS = 1 static
Definition at line 262 of file CraftingManager.h.
Referenced by calculateAssemblySuccess(), and calculateExperimentationSuccess().
const short server::zone::managers::crafting::CraftingManagerImplementation::HR = 4 static
Definition at line 246 of file CraftingManager.h.
HashTable<int, Reference<SharedLabratory*> > server::zone::managers::crafting::CraftingManagerImplementation::labs private
Definition at line 285 of file CraftingManager.h.
Referenced by allowManufactureSchematic(), calculateExperimentationFailureRate(), configureLabratories(), experimentRow(), and setInitialCraftingValues().
const short server::zone::managers::crafting::CraftingManagerImplementation::LINEARCOMBINE = 0x01 static
Definition at line 232 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManagerImplementation::MA = 6 static
Definition at line 250 of file CraftingManager.h.
Referenced by calculateExperimentationFailureRate().
const short server::zone::managers::crafting::CraftingManagerImplementation::MARGINALSUCCESS = 5 static
Definition at line 270 of file CraftingManager.h.
Referenced by calculateAssemblySuccess(), and calculateExperimentationSuccess().
const short server::zone::managers::crafting::CraftingManagerImplementation::MODERATESUCCESS = 3 static
Definition at line 266 of file CraftingManager.h.
Referenced by calculateAssemblySuccess(), and calculateExperimentationSuccess().
const short server::zone::managers::crafting::CraftingManagerImplementation::OK = 6 static
Definition at line 272 of file CraftingManager.h.
Referenced by calculateAssemblySuccess(), and calculateExperimentationSuccess().
const short server::zone::managers::crafting::CraftingManagerImplementation::OQ = 8 static
Definition at line 254 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManagerImplementation::OVERRIDECOMBINE = 0x04 static
Definition at line 238 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManagerImplementation::PE = 7 static
Definition at line 252 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManagerImplementation::PERCENTAGECOMBINE = 0x02 static
Definition at line 234 of file CraftingManager.h.
const int server::zone::managers::crafting::CraftingManagerImplementation::RESOURCE_LAB = 0x00 static
Definition at line 278 of file CraftingManager.h.
Referenced by configureLabratories().
const short server::zone::managers::crafting::CraftingManagerImplementation::RESOURCECOMBINE = 0x00 static
Definition at line 230 of file CraftingManager.h.
Reference<SchematicMap* > server::zone::managers::crafting::CraftingManagerImplementation::schematicMap private
Definition at line 227 of file CraftingManager.h.
Referenced by awardSchematicGroup(), getSchematic(), initialize(), removeSchematicGroup(), sendDraftSlotsTo(), and sendResourceWeightsTo().
const short server::zone::managers::crafting::CraftingManagerImplementation::SR = 9 static
Definition at line 256 of file CraftingManager.h.
const short server::zone::managers::crafting::CraftingManagerImplementation::SUCCESS = 4 static
Definition at line 268 of file CraftingManager.h.
Referenced by calculateAssemblySuccess(), and calculateExperimentationSuccess().
const short server::zone::managers::crafting::CraftingManagerImplementation::UT = 10 static
Definition at line 258 of file CraftingManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/CraftingManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/CraftingManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/CraftingManagerImplementation.cpp