Core3: server::login::LoginServerAdapter Class Reference
server::login::LoginServerAdapter Class Reference
#include <LoginServer.h>
Public Member Functions
LoginServerAdapter (LoginServer *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void initialize ()
void shutdown ()
void startManagers ()
void stopManagers ()
void start (int p, int mconn)
void stop ()
void printInfo ()
void populateGalaxyList ()
Account * getAccount (unsigned int accountID)
LoginEnumCluster * getLoginEnumClusterMessage ()
LoginClusterStatus * getLoginClusterStatusMessage ()
Detailed Description
Definition at line 285 of file LoginServer.h.
Constructor & Destructor Documentation
LoginServerAdapter::LoginServerAdapter (LoginServer * impl)
Definition at line 413 of file LoginServer.cpp.
Member Function Documentation
Account * LoginServerAdapter::getAccount (unsigned int accountID)
Definition at line 521 of file LoginServer.cpp.
Referenced by invokeMethod().
LoginClusterStatus * LoginServerAdapter::getLoginClusterStatusMessage ()
Definition at line 529 of file LoginServer.cpp.
Referenced by invokeMethod().
LoginEnumCluster * LoginServerAdapter::getLoginEnumClusterMessage ()
Definition at line 525 of file LoginServer.cpp.
Referenced by invokeMethod().
void LoginServerAdapter::initialize ()
Definition at line 489 of file LoginServer.cpp.
Referenced by invokeMethod().
void LoginServerAdapter::initializeTransientMembers ()
Definition at line 485 of file LoginServer.cpp.
Referenced by invokeMethod().
void LoginServerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 416 of file LoginServer.cpp.
References getAccount(), getLoginClusterStatusMessage(), getLoginEnumClusterMessage(), initialize(), initializeTransientMembers(), populateGalaxyList(), printInfo(), RPC_GETACCOUNT__INT_, RPC_GETLOGINCLUSTERSTATUSMESSAGE__, RPC_GETLOGINENUMCLUSTERMESSAGE__, RPC_INITIALIZE__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_POPULATEGALAXYLIST__, RPC_PRINTINFO__, RPC_SHUTDOWN__, RPC_START__INT_INT_, RPC_STARTMANAGERS__, RPC_STOP__, RPC_STOPMANAGERS__, shutdown(), start(), startManagers(), stop(), and stopManagers().
void LoginServerAdapter::populateGalaxyList ()
Definition at line 517 of file LoginServer.cpp.
Referenced by invokeMethod().
void LoginServerAdapter::printInfo ()
Definition at line 513 of file LoginServer.cpp.
Referenced by invokeMethod().
void LoginServerAdapter::shutdown ()
Definition at line 493 of file LoginServer.cpp.
Referenced by invokeMethod().
void LoginServerAdapter::start (int p, int mconn)
Definition at line 505 of file LoginServer.cpp.
Referenced by invokeMethod().
void LoginServerAdapter::startManagers ()
Definition at line 497 of file LoginServer.cpp.
Referenced by invokeMethod().
void LoginServerAdapter::stop ()
Definition at line 509 of file LoginServer.cpp.
Referenced by invokeMethod().
void LoginServerAdapter::stopManagers ()
Definition at line 501 of file LoginServer.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginServer.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginServer.cpp