Core3: CooldownTimerMap Class Reference
CooldownTimerMap Class Reference
#include <CooldownTimerMap.h>
Public Member Functions
CooldownTimerMap ()
CooldownTimerMap (const CooldownTimerMap &map)
~CooldownTimerMap ()
CooldownTimerMap & operator= (const CooldownTimerMap &map)
bool isPast (const String &cooldownName)
void updateToCurrentAndAddMili (const String &cooldownName, uint64 mili)
Time * updateToCurrentTime (const String &cooldownName)
void addMiliTime (const String &cooldownName, uint64 mili)
Time * getTime (const String &cooldownName)
Object * clone ()
Object * clone (void *object)
Private Attributes
HashTable< String, CooldownTimer > timers
Detailed Description
Definition at line 100 of file CooldownTimerMap.h.
Constructor & Destructor Documentation
CooldownTimerMap::CooldownTimerMap () inline
Definition at line 104 of file CooldownTimerMap.h.
CooldownTimerMap::CooldownTimerMap (const CooldownTimerMap & map) inline
Definition at line 107 of file CooldownTimerMap.h.
References timers.
CooldownTimerMap::~CooldownTimerMap () inline
Definition at line 111 of file CooldownTimerMap.h.
Member Function Documentation
void CooldownTimerMap::addMiliTime (const String & cooldownName, uint64 mili) inline
Definition at line 147 of file CooldownTimerMap.h.
References timers.
Object* CooldownTimerMap::clone () inline
Definition at line 165 of file CooldownTimerMap.h.
Object* CooldownTimerMap::clone (void * object) inline
Definition at line 169 of file CooldownTimerMap.h.
Time* CooldownTimerMap::getTime (const String & cooldownName) inline
Definition at line 156 of file CooldownTimerMap.h.
References timers.
bool CooldownTimerMap::isPast (const String & cooldownName) inline
Definition at line 123 of file CooldownTimerMap.h.
References timers.
Referenced by AreatrackCommand::doQueueCommand(), server::zone::objects::player::PlayerObjectImplementation::doRecovery(), server::zone::objects::tangible::threat::ThreatMap::getHighestThreatCreature(), and server::zone::objects::tangible::threat::ThreatMap::setThreatState().
CooldownTimerMap& CooldownTimerMap::operator= (const CooldownTimerMap & map) inline
Definition at line 114 of file CooldownTimerMap.h.
References timers.
void CooldownTimerMap::updateToCurrentAndAddMili (const String & cooldownName, uint64 mili) inline
Definition at line 130 of file CooldownTimerMap.h.
References updateToCurrentTime().
Referenced by server::zone::objects::player::PlayerObjectImplementation::doRecovery(), server::zone::objects::tangible::threat::ThreatMap::getHighestThreatCreature(), and server::zone::objects::tangible::threat::ThreatMap::setThreatState().
Time* CooldownTimerMap::updateToCurrentTime (const String & cooldownName) inline
Definition at line 136 of file CooldownTimerMap.h.
References timers.
Referenced by server::zone::objects::tangible::threat::ThreatMap::setThreatState(), and updateToCurrentAndAddMili().
Member Data Documentation
HashTable<String, CooldownTimer> CooldownTimerMap::timers private
Definition at line 101 of file CooldownTimerMap.h.
Referenced by addMiliTime(), CooldownTimerMap(), getTime(), isPast(), operator=(), and updateToCurrentTime().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/variables/CooldownTimerMap.h