Core3: ItemDropTradeCallback Class Reference
ItemDropTradeCallback Class Reference
#include <ItemDropTradeCallback.h>
Public Member Functions
ItemDropTradeCallback (ObjectControllerMessageCallback *objectControllerCallback)
void parse (Message *message)
void run ()
Public Member Functions inherited from server::zone::packets::MessageCallback
MessageCallback (ZoneClientSession *client, ZoneProcessServer *server)
virtual ~MessageCallback ()
int getTaskQueue ()
bool parseMessage (Message *packet)
ZoneClientSession * getClient ()
ZoneProcessServer * getServer ()
Private Attributes
uint64 targetToTrade
ObjectControllerMessageCallback * objectControllerMain
Additional Inherited Members
Protected Attributes inherited from server::zone::packets::MessageCallback
Reference< ZoneClientSession * > client
ManagedReference
< ZoneProcessServer * > server
int taskqueue
Detailed Description
Definition at line 16 of file ItemDropTradeCallback.h.
Constructor & Destructor Documentation
ItemDropTradeCallback::ItemDropTradeCallback (ObjectControllerMessageCallback * objectControllerCallback) inline
Definition at line 21 of file ItemDropTradeCallback.h.
References objectControllerMain.
Member Function Documentation
void ItemDropTradeCallback::parse (Message * message) inline virtual
Implements server::zone::packets::MessageCallback.
Definition at line 27 of file ItemDropTradeCallback.h.
References targetToTrade.
void ItemDropTradeCallback::run () inline
Definition at line 33 of file ItemDropTradeCallback.h.
References server::zone::packets::MessageCallback::client, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::packets::MessageCallback::server, server::chat::StringIdChatParameter::setTU(), targetToTrade, and SessionFacadeType::TRADE.
Member Data Documentation
ObjectControllerMessageCallback* ItemDropTradeCallback::objectControllerMain private
Definition at line 19 of file ItemDropTradeCallback.h.
Referenced by ItemDropTradeCallback().
uint64 ItemDropTradeCallback::targetToTrade private
Definition at line 17 of file ItemDropTradeCallback.h.
Referenced by parse(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/object/ItemDropTradeCallback.h