Core3: SpotlightCommand Class Reference
SpotlightCommand Class Reference
#include <SpotlightCommand.h>
Public Member Functions
SpotlightCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file SpotlightCommand.h.
Constructor & Destructor Documentation
SpotlightCommand::SpotlightCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file SpotlightCommand.h.
Member Function Documentation
int SpotlightCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 58 of file SpotlightCommand.h.
References CreatureAttribute::ACTION, server::zone::objects::creature::CreatureObject::calculateCostAdjustment(), server::zone::objects::creature::CreatureObject::getHAM(), server::zone::objects::creature::CreatureObject::inflictDamage(), server::zone::objects::creature::CreatureObject::isEntertaining(), server::zone::objects::creature::CreatureObject::playEffect(), CreatureAttribute::QUICKNESS, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/SpotlightCommand.h