Core3: StartBandCommand Class Reference
StartBandCommand Class Reference
#include <StartBandCommand.h>
Public Member Functions
StartBandCommand (const String &name, ZoneProcessServer *server)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
bool canPlayInstrument (CreatureObject *creature, const uint64 &target)
Detailed Description
Definition at line 50 of file StartBandCommand.h.
Constructor & Destructor Documentation
StartBandCommand::StartBandCommand (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file StartBandCommand.h.
Member Function Documentation
bool StartBandCommand::canPlayInstrument (CreatureObject * creature, const uint64 & target) inline
Definition at line 237 of file StartBandCommand.h.
References server::zone::objects::scene::SceneObject::getDistanceTo(), PerformanceManager::getInstrument(), server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
int StartBandCommand::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 58 of file StartBandCommand.h.
References SuiWindowType::BAND_START, canPlayInstrument(), SessionFacadeType::ENTERTAINING, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::creature::CreatureObject::getGroup(), PerformanceManager::getInstrumentAnimation(), PerformanceManager::getInstrumentId(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::creature::CreatureObject::getTargetID(), PerformanceManager::hasInstrumentId(), StartMusicCommand::sendAvailableSongs(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and StartMusicCommand::startMusic().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/StartBandCommand.h