Core3: LoginPacketHandler Class Reference
LoginPacketHandler Class Reference
#include <LoginPacketHandler.h>
Public Member Functions
LoginPacketHandler (LoginSession *session)
~LoginPacketHandler ()
void handleMessage (Message *pack)
void handleEnumerateCharacterId (Message *pack)
void handleLoginClientToken (Message *pack)
void handleErrorMessage (Message *pack)
Private Attributes
Reference< LoginSession * > loginSession
Detailed Description
Definition at line 15 of file LoginPacketHandler.h.
Constructor & Destructor Documentation
LoginPacketHandler::LoginPacketHandler (LoginSession * session) inline
Definition at line 19 of file LoginPacketHandler.h.
References loginSession.
LoginPacketHandler::~LoginPacketHandler () inline
Definition at line 23 of file LoginPacketHandler.h.
Member Function Documentation
void LoginPacketHandler::handleEnumerateCharacterId (Message * pack)
Definition at line 75 of file LoginPacketHandler.cpp.
References loginSession.
Referenced by handleMessage().
void LoginPacketHandler::handleErrorMessage (Message * pack)
Definition at line 49 of file LoginPacketHandler.cpp.
Referenced by handleMessage().
void LoginPacketHandler::handleLoginClientToken (Message * pack)
Definition at line 63 of file LoginPacketHandler.cpp.
References loginSession.
Referenced by handleMessage().
void LoginPacketHandler::handleMessage (Message * pack)
Definition at line 13 of file LoginPacketHandler.cpp.
References handleEnumerateCharacterId(), handleErrorMessage(), and handleLoginClientToken().
Referenced by LoginMessageProcessorTask::run().
Member Data Documentation
Reference<LoginSession*> LoginPacketHandler::loginSession private
Definition at line 16 of file LoginPacketHandler.h.
Referenced by handleEnumerateCharacterId(), handleLoginClientToken(), and LoginPacketHandler().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/login/LoginPacketHandler.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/login/LoginPacketHandler.cpp