Core3: LairMenuComponent Class Reference
LairMenuComponent Class Reference
#include <LairMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file LairMenuComponent.h.
Member Function Documentation
void LairMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from TangibleObjectMenuComponent.
Definition at line 17 of file LairMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), TangibleObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::objects::scene::SceneObject::getObservers(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::scene::SceneObject::isTangibleObject(), and ObserverEventType::OBJECTDESTRUCTION.
int LairMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from TangibleObjectMenuComponent.
Definition at line 44 of file LairMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::getDistanceTo(), server::zone::ZoneProcessServer::getForageManager(), server::zone::objects::scene::SceneObject::getZoneProcessServer(), TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), server::zone::objects::scene::SceneObject::isTangibleObject(), and server::zone::managers::minigames::ForageManager::startForaging().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/LairMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/LairMenuComponent.cpp