Core3: server::zone::objects::mission::MissionObserverAdapter Class Reference
server::zone::objects::mission::MissionObserverAdapter Class Reference
#include <MissionObserver.h>
Public Member Functions
MissionObserverAdapter (MissionObserver *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void destroyObjectFromDatabase ()
Detailed Description
Definition at line 160 of file MissionObserver.h.
Constructor & Destructor Documentation
MissionObserverAdapter::MissionObserverAdapter (MissionObserver * impl)
Definition at line 225 of file MissionObserver.cpp.
Member Function Documentation
void MissionObserverAdapter::destroyObjectFromDatabase ()
Definition at line 251 of file MissionObserver.cpp.
Referenced by invokeMethod().
void MissionObserverAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 228 of file MissionObserver.cpp.
References destroyObjectFromDatabase(), notifyObserverEvent(), RPC_DESTROYOBJECTFROMDATABASE__, and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
int MissionObserverAdapter::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 247 of file MissionObserver.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/MissionObserver.cpp