Core3: AffectorHeightFractal Class Reference
AffectorHeightFractal Class Reference
#include <AffectorHeightFractal.h>
Public Member Functions
AffectorHeightFractal ()
void process (float x, float y, float transformValue, float &baseValue, TerrainGenerator *terrainGenerator)
void parseFromIffStream (engine::util::IffStream *iffStream)
void parseFromIffStream (engine::util::IffStream *iffStream, Version<'0003'>)
int getFractalId ()
float getHeight ()
bool isEnabled ()
Public Member Functions inherited from ProceduralRule<'AHFR'>
ProceduralRule ()
bool isEnabled ()
Public Member Functions inherited from TemplateVariable< formType >
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Public Member Functions inherited from AffectorProceduralRule
AffectorProceduralRule ()
virtual ~AffectorProceduralRule ()
bool isHeightTypeAffector ()
bool isEnvoronmentTypeAffector ()
int getAffectorType ()
Private Attributes
int fractalId
int operationType
float height
MapFractal * mfrc
Additional Inherited Members
Static Public Attributes inherited from AffectorProceduralRule
static const int HEIGHTTYPE = 0x100
static const int HEIGHTFRACTAL = 0x101
static const int HEIGHTTERRACE = 0x102
static const int HEIGHTCONSTANT = 0x103
static const int ENVIRONMENT = 0x200
Protected Attributes inherited from ProceduralRule<'AHFR'>
InformationHeader informationHeader
Protected Attributes inherited from AffectorProceduralRule
int affectorType
Detailed Description
Definition at line 16 of file AffectorHeightFractal.h.
Constructor & Destructor Documentation
AffectorHeightFractal::AffectorHeightFractal () inline
Definition at line 23 of file AffectorHeightFractal.h.
References AffectorProceduralRule::affectorType, AffectorProceduralRule::HEIGHTFRACTAL, and mfrc.
Member Function Documentation
int AffectorHeightFractal::getFractalId () inline
Definition at line 33 of file AffectorHeightFractal.h.
References fractalId.
float AffectorHeightFractal::getHeight () inline
Definition at line 37 of file AffectorHeightFractal.h.
References height.
bool AffectorHeightFractal::isEnabled () inline virtual
Reimplemented from AffectorProceduralRule.
Definition at line 41 of file AffectorHeightFractal.h.
References ProceduralRule<'AHFR'>::informationHeader, and InformationHeader::isEnabled().
void AffectorHeightFractal::parseFromIffStream (engine::util::IffStream * iffStream) virtual
Reimplemented from TemplateVariable< formType >.
Definition at line 52 of file AffectorHeightFractal.cpp.
void AffectorHeightFractal::parseFromIffStream (engine::util::IffStream * iffStream, Version<'0003'>)
Definition at line 69 of file AffectorHeightFractal.cpp.
References fractalId, height, ProceduralRule<'AHFR'>::informationHeader, operationType, and TemplateVariable< formType >::readObject().
void AffectorHeightFractal::process (float x, float y, float transformValue, float & baseValue, TerrainGenerator * terrainGenerator) virtual
Reimplemented from AffectorProceduralRule.
Definition at line 11 of file AffectorHeightFractal.cpp.
References fractalId, InformationHeader::getDescription(), TerrainGenerator::getMfrc(), MapFractal::getNoise(), height, ProceduralRule<'AHFR'>::informationHeader, mfrc, and operationType.
Member Data Documentation
int AffectorHeightFractal::fractalId private
Definition at line 17 of file AffectorHeightFractal.h.
Referenced by getFractalId(), parseFromIffStream(), and process().
float AffectorHeightFractal::height private
Definition at line 19 of file AffectorHeightFractal.h.
Referenced by getHeight(), parseFromIffStream(), and process().
MapFractal* AffectorHeightFractal::mfrc private
Definition at line 20 of file AffectorHeightFractal.h.
Referenced by AffectorHeightFractal(), and process().
int AffectorHeightFractal::operationType private
Definition at line 18 of file AffectorHeightFractal.h.
Referenced by parseFromIffStream(), and process().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/layer/affectors/AffectorHeightFractal.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/layer/affectors/AffectorHeightFractal.cpp