Core3: ObjectManager Class Reference
ObjectManager Class Reference
#include <ObjectManager.h>
Public Member Functions
ObjectManager ()
virtual ~ObjectManager ()
SceneObject * createObject (uint32 objectCRC, uint64 objectID)
void destroyObject (uint64 objectID)
SceneObject * getObject (uint64 objectID)
SceneObject * getObject (const UnicodeString &customName)
void setZone (Zone *zn)
uint32 getObjectMapSize ()
void registerFunctions ()
Static Public Member Functions
static int includeFile (lua_State *L)
static int crcString (lua_State *L)
static int addTemplateCRC (lua_State *L)
Private Member Functions
void registerObjectTypes ()
Private Attributes
ObjectMap * objectMap
Zone * zone
Static Private Attributes
static ObjectFactory
< SceneObject *(LuaObject
*), uint32 > objectFactory
static Lua * luaInstance = NULL
static Mutex luaMutex
Detailed Description
Definition at line 17 of file ObjectManager.h.
Constructor & Destructor Documentation
ObjectManager::ObjectManager ()
Definition at line 23 of file ObjectManager.cpp.
References luaInstance, luaMutex, objectMap, registerFunctions(), registerObjectTypes(), and zone.
ObjectManager::~ObjectManager () virtual
Definition at line 44 of file ObjectManager.cpp.
References objectMap.
Member Function Documentation
int ObjectManager::addTemplateCRC (lua_State * L) static
Definition at line 235 of file ObjectManager.cpp.
Referenced by registerFunctions().
int ObjectManager::crcString (lua_State * L) static
Definition at line 225 of file ObjectManager.cpp.
Referenced by registerFunctions().
SceneObject * ObjectManager::createObject (uint32 objectCRC, uint64 objectID)
Definition at line 104 of file ObjectManager.cpp.
References luaInstance, luaMutex, objectFactory, objectMap, ObjectMap::put(), SceneObject::setObjectID(), and zone.
Referenced by ZonePacketHandler::handleSceneObjectCreateMessage().
void ObjectManager::destroyObject (uint64 objectID)
Definition at line 175 of file ObjectManager.cpp.
References SceneObject::getSlottedObject(), objectMap, ObjectMap::remove(), and SceneObject::removeObject().
Referenced by ZonePacketHandler::handleSceneObejctDestroyMessage().
SceneObject * ObjectManager::getObject (uint64 objectID)
Definition at line 151 of file ObjectManager.cpp.
References objectMap.
Referenced by Zone::follow(), Zone::getObject(), and Zone::getSelfPlayer().
SceneObject * ObjectManager::getObject (const UnicodeString & customName)
Definition at line 157 of file ObjectManager.cpp.
References StringId::getCustomString(), and objectMap.
uint32 ObjectManager::getObjectMapSize ()
Definition at line 203 of file ObjectManager.cpp.
References objectMap.
int ObjectManager::includeFile (lua_State * L) static
Definition at line 217 of file ObjectManager.cpp.
Referenced by registerFunctions().
void ObjectManager::registerFunctions ()
Definition at line 210 of file ObjectManager.cpp.
References addTemplateCRC(), crcString(), includeFile(), and luaInstance.
Referenced by ObjectManager().
void ObjectManager::registerObjectTypes () private
Definition at line 52 of file ObjectManager.cpp.
References SceneObject::ARMOR, SceneObject::BODYARMOR, SceneObject::CONTAINER, SceneObject::CREATURE, SceneObject::DROIDCREATURE, SceneObject::GENERICITEM, SceneObject::NPCCREATURE, objectFactory, SceneObject::PLAYERCREATURE, SceneObject::PLAYEROBJECT, SceneObject::PROBOTCREATURE, and SceneObject::WEARABLECONTAINER.
Referenced by ObjectManager().
void ObjectManager::setZone (Zone * zn) inline
Definition at line 39 of file ObjectManager.h.
References zone.
Referenced by Zone::Zone().
Member Data Documentation
Lua * ObjectManager::luaInstance = NULL static private
Definition at line 21 of file ObjectManager.h.
Referenced by createObject(), ObjectManager(), and registerFunctions().
Mutex ObjectManager::luaMutex static private
Definition at line 22 of file ObjectManager.h.
Referenced by createObject(), and ObjectManager().
ObjectFactory< SceneObject *(LuaObject *), uint32 > ObjectManager::objectFactory static private
Definition at line 20 of file ObjectManager.h.
Referenced by createObject(), and registerObjectTypes().
ObjectMap* ObjectManager::objectMap private
Definition at line 18 of file ObjectManager.h.
Referenced by createObject(), destroyObject(), getObject(), getObjectMapSize(), ObjectManager(), and ~ObjectManager().
Zone* ObjectManager::zone private
Definition at line 24 of file ObjectManager.h.
Referenced by createObject(), ObjectManager(), and setZone().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/zone/managers/object/ObjectManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/zone/managers/object/ObjectManager.cpp