Core3: server::zone::objects::creature::conversation::screenhandlers::TrainerTrainableSkillsScreenHandler Class Reference
server::zone::objects::creature::conversation::screenhandlers::TrainerTrainableSkillsScreenHandler Class Reference
#include <TrainerScreenHandlers.h>
Public Member Functions
TrainerTrainableSkillsScreenHandler ()
ConversationScreen * handleScreen (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
Public Member Functions inherited from server::zone::objects::creature::conversation::screenhandlers::ScreenHandler
ScreenHandler ()
~ScreenHandler ()
String getNextScreenId ()
Private Member Functions
void getTrainableSkillsList (CreatureObject *conversingPlayer, Vector< String > *trainableSkillList, Skill *skill)
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::conversation::screenhandlers::ScreenHandler
String nextScreenId
Detailed Description
Definition at line 64 of file TrainerScreenHandlers.h.
Constructor & Destructor Documentation
server::zone::objects::creature::conversation::screenhandlers::TrainerTrainableSkillsScreenHandler::TrainerTrainableSkillsScreenHandler () inline
Definition at line 67 of file TrainerScreenHandlers.h.
Member Function Documentation
void TrainerTrainableSkillsScreenHandler::getTrainableSkillsList (CreatureObject * conversingPlayer, Vector< String > * trainableSkillList, Skill * skill) private
Definition at line 158 of file TrainerScreenHandlers.cpp.
References Skill::getSkillName(), Skill::getSkillsRequired(), and server::zone::objects::creature::CreatureObject::hasSkill().
Referenced by handleScreen().
ConversationScreen * TrainerTrainableSkillsScreenHandler::handleScreen (CreatureObject * conversingPlayer, CreatureObject * conversingNPC, int selectedOption, ConversationScreen * conversationScreen) virtual
Implements server::zone::objects::creature::conversation::screenhandlers::ScreenHandler.
Definition at line 109 of file TrainerScreenHandlers.cpp.
References server::zone::templates::mobile::ConversationScreen::addOption(), server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::CANLEARNSKILLSCREENHANDLERID, SessionFacadeType::CONVERSATION, server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::ERRORSCREENHANDLERID, server::zone::objects::scene::SceneObject::getActiveSession(), getTrainableSkillsList(), server::zone::objects::creature::conversation::screenhandlers::ScreenHandler::nextScreenId, server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::NOTENOUGHXPSCREENHANDLERID, server::zone::templates::mobile::ConversationScreen::removeOption(), and server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::STARTSCREENHANDLERID.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/screenhandlers/TrainerScreenHandlers.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/screenhandlers/TrainerScreenHandlers.cpp