Core3: server::zone::objects::player::sessions::MigrateStatsSessionImplementation Class Reference
server::zone::objects::player::sessions::MigrateStatsSessionImplementation Class Reference
#include <MigrateStatsSession.h>
Public Member Functions
MigrateStatsSessionImplementation (CreatureObject *parent)
MigrateStatsSessionImplementation (DummyConstructorParameter *param)
int initializeSession ()
int cancelSession ()
int clearSession ()
int getAttributeToModifyCount ()
void setAttributeToModify (int attribute, int value)
int getAttribtueToModify (int attribute)
void migrateStats ()
operator const MigrateStatsSession * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< MigrateStatsSession * > _this
Protected Member Functions
virtual ~MigrateStatsSessionImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > creature
Vector< int > attributesToModify
Friends
class MigrateStatsSession
Detailed Description
Definition at line 109 of file MigrateStatsSession.h.
Constructor & Destructor Documentation
MigrateStatsSessionImplementation::MigrateStatsSessionImplementation (CreatureObject * parent)
Definition at line 283 of file MigrateStatsSession.cpp.
References _initializeImplementation(), attributesToModify, and creature.
MigrateStatsSessionImplementation::MigrateStatsSessionImplementation (DummyConstructorParameter * param)
Definition at line 145 of file MigrateStatsSession.cpp.
References _initializeImplementation().
MigrateStatsSessionImplementation::~MigrateStatsSessionImplementation () protected virtual
Definition at line 150 of file MigrateStatsSession.cpp.
Member Function Documentation
DistributedObjectStub * MigrateStatsSessionImplementation::_getStub ()
Definition at line 170 of file MigrateStatsSession.cpp.
References _this.
void MigrateStatsSessionImplementation::_initializeImplementation () protected
Definition at line 157 of file MigrateStatsSession.cpp.
References _serializationHelperMethod(), and _this.
Referenced by MigrateStatsSessionImplementation().
void MigrateStatsSessionImplementation::_serializationHelperMethod () protected
Definition at line 206 of file MigrateStatsSession.cpp.
Referenced by _initializeImplementation().
void MigrateStatsSessionImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 165 of file MigrateStatsSession.cpp.
References _this.
Referenced by server::zone::objects::player::sessions::MigrateStatsSession::MigrateStatsSession().
int MigrateStatsSessionImplementation::cancelSession ()
Definition at line 306 of file MigrateStatsSession.cpp.
References creature, and SessionFacadeType::MIGRATESTATS.
Referenced by server::zone::objects::player::sessions::MigrateStatsSession::cancelSession(), and migrateStats().
int MigrateStatsSessionImplementation::clearSession ()
Definition at line 321 of file MigrateStatsSession.cpp.
References attributesToModify.
Referenced by server::zone::objects::player::sessions::MigrateStatsSession::clearSession().
void MigrateStatsSessionImplementation::finalize () protected
Definition at line 154 of file MigrateStatsSession.cpp.
int MigrateStatsSessionImplementation::getAttribtueToModify (int attribute)
Definition at line 338 of file MigrateStatsSession.cpp.
References attributesToModify.
Referenced by server::zone::objects::player::sessions::MigrateStatsSession::getAttribtueToModify().
int MigrateStatsSessionImplementation::getAttributeToModifyCount ()
Definition at line 328 of file MigrateStatsSession.cpp.
References attributesToModify.
Referenced by server::zone::objects::player::sessions::MigrateStatsSession::getAttributeToModifyCount().
int MigrateStatsSessionImplementation::initializeSession ()
Definition at line 301 of file MigrateStatsSession.cpp.
Referenced by server::zone::objects::player::sessions::MigrateStatsSession::initializeSession().
void MigrateStatsSessionImplementation::lock (bool doLock = true) protected
Definition at line 178 of file MigrateStatsSession.cpp.
References _this.
void MigrateStatsSessionImplementation::lock (ManagedObject * obj) protected
Definition at line 182 of file MigrateStatsSession.cpp.
References _this.
void MigrateStatsSessionImplementation::migrateStats ()
Definition at line 343 of file MigrateStatsSession.cpp.
References attributesToModify, cancelSession(), and creature.
Referenced by server::zone::objects::player::sessions::MigrateStatsSession::migrateStats().
MigrateStatsSessionImplementation::operator const MigrateStatsSession * ()
Definition at line 174 of file MigrateStatsSession.cpp.
void MigrateStatsSessionImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 213 of file MigrateStatsSession.cpp.
References readObjectMember().
bool MigrateStatsSessionImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 232 of file MigrateStatsSession.cpp.
References attributesToModify, and creature.
Referenced by readObject().
void MigrateStatsSessionImplementation::rlock (bool doLock = true) protected
Definition at line 186 of file MigrateStatsSession.cpp.
References _this.
void MigrateStatsSessionImplementation::runlock (bool doLock = true) protected
Definition at line 202 of file MigrateStatsSession.cpp.
References _this.
void MigrateStatsSessionImplementation::setAttributeToModify (int attribute, int value)
Definition at line 333 of file MigrateStatsSession.cpp.
References attributesToModify.
Referenced by server::zone::objects::player::sessions::MigrateStatsSession::setAttributeToModify().
void MigrateStatsSessionImplementation::unlock (bool doLock = true) protected
Definition at line 198 of file MigrateStatsSession.cpp.
References _this.
void MigrateStatsSessionImplementation::wlock (bool doLock = true) protected
Definition at line 190 of file MigrateStatsSession.cpp.
References _this.
void MigrateStatsSessionImplementation::wlock (ManagedObject * obj) protected
Definition at line 194 of file MigrateStatsSession.cpp.
References _this.
void MigrateStatsSessionImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 250 of file MigrateStatsSession.cpp.
References writeObjectMembers().
int MigrateStatsSessionImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 257 of file MigrateStatsSession.cpp.
References attributesToModify, and creature.
Referenced by writeObject().
Friends And Related Function Documentation
friend class MigrateStatsSession friend
Definition at line 168 of file MigrateStatsSession.h.
Member Data Documentation
WeakReference<MigrateStatsSession*> server::zone::objects::player::sessions::MigrateStatsSessionImplementation::_this
Definition at line 134 of file MigrateStatsSession.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
Vector<int> server::zone::objects::player::sessions::MigrateStatsSessionImplementation::attributesToModify protected
Definition at line 113 of file MigrateStatsSession.h.
Referenced by clearSession(), getAttribtueToModify(), getAttributeToModifyCount(), migrateStats(), MigrateStatsSessionImplementation(), readObjectMember(), setAttributeToModify(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sessions::MigrateStatsSessionImplementation::creature protected
Definition at line 111 of file MigrateStatsSession.h.
Referenced by cancelSession(), migrateStats(), MigrateStatsSessionImplementation(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/MigrateStatsSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/MigrateStatsSession.cpp