Core3: PlanetTravelPoint Class Reference
PlanetTravelPoint Class Reference
#include <PlanetTravelPoint.h>
Public Member Functions
PlanetTravelPoint (const String &zoneName)
PlanetTravelPoint (const String &zoneName, const String &cityName, Vector3 arrVector, Vector3 departVector, CreatureObject *shuttle)
PlanetTravelPoint (const PlanetTravelPoint &ptp)
PlanetTravelPoint & operator= (const PlanetTravelPoint &ptp)
void readLuaObject (LuaObject *luaObject)
void setShuttle (CreatureObject *shuttle)
void setPointName (const String &name)
String & getPointZone ()
String & getPointName ()
float getArrivalPositionX () const
float getArrivalPositionY () const
float getArrivalPositionZ () const
Vector3 getArrivalPosition () const
float getDeparturePositionX () const
float getDeparturePositionY () const
float getDeparturePositionZ () const
Vector3 getDeparturePosition () const
bool isPoint (const String &zoneName, const String &name)
bool isInterplanetary ()
bool isIncomingAllowed ()
bool canTravelTo (PlanetTravelPoint *arrivalPoint)
ManagedReference
< CreatureObject * > getShuttle ()
String toString ()
Private Attributes
ManagedWeakReference
< CreatureObject * > shuttleObject
String pointZone
String pointName
Vector3 arrivalVector
Vector3 departureVector
bool interplanetaryTravelAllowed
bool incomingTravelAllowed
Detailed Description
Definition at line 18 of file PlanetTravelPoint.h.
Constructor & Destructor Documentation
PlanetTravelPoint::PlanetTravelPoint (const String & zoneName) inline
Definition at line 29 of file PlanetTravelPoint.h.
PlanetTravelPoint::PlanetTravelPoint (const String & zoneName, const String & cityName, Vector3 arrVector, Vector3 departVector, CreatureObject * shuttle) inline
Definition at line 37 of file PlanetTravelPoint.h.
PlanetTravelPoint::PlanetTravelPoint (const PlanetTravelPoint & ptp) inline
Definition at line 47 of file PlanetTravelPoint.h.
References arrivalVector, departureVector, incomingTravelAllowed, interplanetaryTravelAllowed, pointName, pointZone, and shuttleObject.
Member Function Documentation
bool PlanetTravelPoint::canTravelTo (PlanetTravelPoint * arrivalPoint) inline
Returns true if travel between this point and the passed in point is permitted.
Parameters
arrivalPoint The destination point.
Definition at line 162 of file PlanetTravelPoint.h.
References getPointZone(), and isIncomingAllowed().
Vector3 PlanetTravelPoint::getArrivalPosition () const inline
Definition at line 117 of file PlanetTravelPoint.h.
float PlanetTravelPoint::getArrivalPositionX () const inline
Definition at line 105 of file PlanetTravelPoint.h.
float PlanetTravelPoint::getArrivalPositionY () const inline
Definition at line 109 of file PlanetTravelPoint.h.
float PlanetTravelPoint::getArrivalPositionZ () const inline
Definition at line 113 of file PlanetTravelPoint.h.
Vector3 PlanetTravelPoint::getDeparturePosition () const inline
Definition at line 133 of file PlanetTravelPoint.h.
float PlanetTravelPoint::getDeparturePositionX () const inline
Definition at line 121 of file PlanetTravelPoint.h.
float PlanetTravelPoint::getDeparturePositionY () const inline
Definition at line 125 of file PlanetTravelPoint.h.
float PlanetTravelPoint::getDeparturePositionZ () const inline
Definition at line 129 of file PlanetTravelPoint.h.
String& PlanetTravelPoint::getPointName () inline
Definition at line 101 of file PlanetTravelPoint.h.
Referenced by PlanetTravelPointList::addPlayerCityTravelPoint(), EnterTicketPurchaseModeMessage::EnterTicketPurchaseModeMessage(), and MapLocationEntry::setObject().
String& PlanetTravelPoint::getPointZone () inline
Definition at line 97 of file PlanetTravelPoint.h.
Referenced by canTravelTo(), and EnterTicketPurchaseModeMessage::EnterTicketPurchaseModeMessage().
ManagedReference<CreatureObject*> PlanetTravelPoint::getShuttle () inline
Definition at line 169 of file PlanetTravelPoint.h.
bool PlanetTravelPoint::isIncomingAllowed () inline
Returns true if this location allows incoming travel
Definition at line 154 of file PlanetTravelPoint.h.
Referenced by canTravelTo(), and server::zone::managers::planet::PlanetManagerImplementation::isIncomingTravelAllowed().
bool PlanetTravelPoint::isInterplanetary () inline
Returns true if this location allows interplanetary travel
Definition at line 147 of file PlanetTravelPoint.h.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::isInterplanetaryTravelAllowed().
bool PlanetTravelPoint::isPoint (const String & zoneName, const String & name) inline
Returns true if this point is has the same zone and name that is passed in.
Definition at line 140 of file PlanetTravelPoint.h.
Referenced by BoardShuttleCommand::findTicketsInInventory().
PlanetTravelPoint& PlanetTravelPoint::operator= (const PlanetTravelPoint & ptp) inline
Definition at line 57 of file PlanetTravelPoint.h.
References arrivalVector, departureVector, incomingTravelAllowed, interplanetaryTravelAllowed, pointName, pointZone, and shuttleObject.
void PlanetTravelPoint::readLuaObject (LuaObject * luaObject) inline
Definition at line 72 of file PlanetTravelPoint.h.
void PlanetTravelPoint::setPointName (const String & name) inline
Definition at line 93 of file PlanetTravelPoint.h.
void PlanetTravelPoint::setShuttle (CreatureObject * shuttle) inline
Definition at line 86 of file PlanetTravelPoint.h.
References server::zone::objects::scene::SceneObject::getWorldPosition().
Referenced by ShuttleZoneComponent::notifyInsertToZone().
String PlanetTravelPoint::toString () inline
Definition at line 173 of file PlanetTravelPoint.h.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::getNearestPlanetTravelPoint().
Member Data Documentation
Vector3 PlanetTravelPoint::arrivalVector private
Definition at line 23 of file PlanetTravelPoint.h.
Referenced by operator=(), and PlanetTravelPoint().
Vector3 PlanetTravelPoint::departureVector private
Definition at line 24 of file PlanetTravelPoint.h.
Referenced by operator=(), and PlanetTravelPoint().
bool PlanetTravelPoint::incomingTravelAllowed private
Definition at line 26 of file PlanetTravelPoint.h.
Referenced by operator=(), and PlanetTravelPoint().
bool PlanetTravelPoint::interplanetaryTravelAllowed private
Definition at line 25 of file PlanetTravelPoint.h.
Referenced by operator=(), and PlanetTravelPoint().
String PlanetTravelPoint::pointName private
Definition at line 22 of file PlanetTravelPoint.h.
Referenced by operator=(), and PlanetTravelPoint().
String PlanetTravelPoint::pointZone private
Definition at line 21 of file PlanetTravelPoint.h.
Referenced by operator=(), and PlanetTravelPoint().
ManagedWeakReference<CreatureObject*> PlanetTravelPoint::shuttleObject private
Definition at line 19 of file PlanetTravelPoint.h.
Referenced by operator=(), and PlanetTravelPoint().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/PlanetTravelPoint.h