Core3: server::zone::managers::resource::ResourceManager Class Reference
server::zone::managers::resource::ResourceManager Class Reference
#include <ResourceManager.h>
Public Member Functions
ResourceManager (ZoneServer *server, ZoneProcessServer *impl, ObjectManager *objectMan)
void stop ()
void initialize ()
void shiftResources ()
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
int getResourceRecycleType (ResourceSpawn *resource)
void sendResourceListForSurvey (CreatureObject *playerCreature, const int toolType, const String &surveyType)
void sendSurvey (CreatureObject *playerCreature, const String &resname)
void sendSample (CreatureObject *playerCreature, const String &resname, const String &sampleAnimation)
ResourceContainer * harvestResource (CreatureObject *player, const String &type, const int quantity)
void harvestResourceToPlayer (CreatureObject *player, ResourceSpawn *resourceSpawn, const int quantity)
unsigned int getAvailablePowerFromPlayer (CreatureObject *player)
void removePowerFromPlayer (CreatureObject *player, unsigned int power)
void getResourceListByType (Vector< ManagedReference< ResourceSpawn * > > &list, int type, const String &zoneName)
void createResourceSpawn (CreatureObject *playerCreature, const String &restype)
void givePlayerResource (CreatureObject *playerCreature, const String &restype, const int quantity)
ResourceSpawn * getCurrentSpawn (const String &restype, const String &zoneName)
ResourceSpawn * getResourceSpawn (const String &spawnName)
bool isRecycledResource (ResourceSpawn *resource)
ResourceSpawn * getRecycledVersion (ResourceSpawn *resource)
void addNodeToListBox (SuiListBox *sui, const String &nodeName)
String addParentNodeToListBox (SuiListBox *sui, const String &currentNode)
void listResourcesForPlanetOnScreen (CreatureObject *creature, const String &planet)
String healthCheck ()
String dumpResources ()
String despawnResource (String &resourceName)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int RESOURCE_DEED_QUANTITY = 100000
Protected Member Functions
ResourceManager (DummyConstructorParameter *param)
virtual ~ResourceManager ()
Friends
class ResourceManagerHelper
Detailed Description
Definition at line 143 of file ResourceManager.h.
Constructor & Destructor Documentation
ResourceManager::ResourceManager (ZoneServer * server, ZoneProcessServer * impl, ObjectManager * objectMan)
The resource manager handles all aspects of in game resources within the Core3 environment
Definition at line 29 of file ResourceManager.cpp.
References server::zone::managers::resource::ResourceManagerImplementation::_setStub().
ResourceManager::ResourceManager (DummyConstructorParameter * param) protected
Definition at line 36 of file ResourceManager.cpp.
ResourceManager::~ResourceManager () protected virtual
Definition at line 40 of file ResourceManager.cpp.
Member Function Documentation
DistributedObjectServant * ResourceManager::_getImplementation ()
Definition at line 413 of file ResourceManager.cpp.
Referenced by addNodeToListBox(), addParentNodeToListBox(), createResourceSpawn(), despawnResource(), dumpResources(), getAvailablePowerFromPlayer(), getCurrentSpawn(), getRecycledVersion(), getResourceListByType(), getResourceRecycleType(), getResourceSpawn(), givePlayerResource(), harvestResource(), harvestResourceToPlayer(), healthCheck(), initialize(), isRecycledResource(), listResourcesForPlanetOnScreen(), notifyObserverEvent(), removePowerFromPlayer(), sendResourceListForSurvey(), sendSample(), sendSurvey(), shiftResources(), and stop().
DistributedObjectServant * ResourceManager::_getImplementationForRead ()
Definition at line 419 of file ResourceManager.cpp.
void ResourceManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 423 of file ResourceManager.cpp.
void ResourceManager::addNodeToListBox (SuiListBox * sui, const String & nodeName)
Definition at line 320 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::addNodeToListBox(), and RPC_ADDNODETOLISTBOX__SUILISTBOX_STRING_.
String ResourceManager::addParentNodeToListBox (SuiListBox * sui, const String & currentNode)
Definition at line 335 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::addParentNodeToListBox(), and RPC_ADDPARENTNODETOLISTBOX__SUILISTBOX_STRING_.
void ResourceManager::createResourceSpawn (CreatureObject * playerCreature, const String & restype)
Definition at line 232 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::createResourceSpawn(), and RPC_CREATERESOURCESPAWN__CREATUREOBJECT_STRING_.
Referenced by GmCreateClassResourceCommand::doQueueCommand(), and GmCreateSpecificResourceCommand::doQueueCommand().
String ResourceManager::despawnResource (String & resourceName)
Definition at line 397 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::despawnResource(), and RPC_DESPAWNRESOURCE__STRING_.
String ResourceManager::dumpResources ()
Definition at line 382 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::dumpResources(), and RPC_DUMPRESOURCES__.
unsigned int ResourceManager::getAvailablePowerFromPlayer (CreatureObject * player)
Definition at line 194 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::getAvailablePowerFromPlayer(), and RPC_GETAVAILABLEPOWERFROMPLAYER__CREATUREOBJECT_.
Referenced by AddPowerCommand::doQueueCommand(), and server::zone::objects::installation::InstallationObjectImplementation::handleStructureAddEnergy().
ResourceSpawn * ResourceManager::getCurrentSpawn (const String & restype, const String & zoneName)
Definition at line 263 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::getCurrentSpawn(), and RPC_GETCURRENTSPAWN__STRING_STRING_.
ResourceSpawn * ResourceManager::getRecycledVersion (ResourceSpawn * resource)
Definition at line 306 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::getRecycledVersion(), and RPC_GETRECYCLEDVERSION__RESOURCESPAWN_.
Referenced by RecycleResourceTask::run().
void ResourceManager::getResourceListByType (Vector< ManagedReference< ResourceSpawn * > > & list, int type, const String & zoneName)
Definition at line 223 of file ResourceManager.cpp.
References _getImplementation(), and server::zone::managers::resource::ResourceManagerImplementation::getResourceListByType().
Referenced by server::zone::managers::minigames::ForageManagerImplementation::forageGiveResource(), HarvesterObjectMessage7::HarvesterObjectMessage7(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericSurveyMission().
int ResourceManager::getResourceRecycleType (ResourceSpawn * resource)
Definition at line 101 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::getResourceRecycleType(), and RPC_GETRESOURCERECYCLETYPE__RESOURCESPAWN_.
Referenced by RecycleResourceTask::run().
ResourceSpawn * ResourceManager::getResourceSpawn (const String & spawnName)
Definition at line 278 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::getResourceSpawn(), and RPC_GETRESOURCESPAWN__STRING_.
void ResourceManager::givePlayerResource (CreatureObject * playerCreature, const String & restype, const int quantity)
Definition at line 247 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::givePlayerResource(), and RPC_GIVEPLAYERRESOURCE__CREATUREOBJECT_STRING_INT_.
Referenced by ObjectCommand::doQueueCommand().
ResourceContainer * ResourceManager::harvestResource (CreatureObject * player, const String & type, const int quantity)
Definition at line 162 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::harvestResource(), and RPC_HARVESTRESOURCE__CREATUREOBJECT_STRING_INT_.
void ResourceManager::harvestResourceToPlayer (CreatureObject * player, ResourceSpawn * resourceSpawn, const int quantity)
Definition at line 178 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::harvestResourceToPlayer(), and RPC_HARVESTRESOURCETOPLAYER__CREATUREOBJECT_RESOURCESPAWN_INT_.
Referenced by RecycleResourceTask::run().
String ResourceManager::healthCheck ()
Definition at line 367 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::healthCheck(), and RPC_HEALTHCHECK__.
void ResourceManager::initialize ()
Definition at line 58 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::initialize(), and RPC_INITIALIZE__.
bool ResourceManager::isRecycledResource (ResourceSpawn * resource)
Definition at line 292 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::isRecycledResource(), and RPC_ISRECYCLEDRESOURCE__RESOURCESPAWN_.
Referenced by RecycleResourceTask::run().
void ResourceManager::listResourcesForPlanetOnScreen (CreatureObject * creature, const String & planet)
Definition at line 352 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::listResourcesForPlanetOnScreen(), and RPC_LISTRESOURCESFORPLANETONSCREEN__CREATUREOBJECT_STRING_.
int ResourceManager::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 84 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
void ResourceManager::removePowerFromPlayer (CreatureObject * player, unsigned int power)
Definition at line 208 of file ResourceManager.cpp.
References _getImplementation(), server::zone::managers::resource::ResourceManagerImplementation::removePowerFromPlayer(), and RPC_REMOVEPOWERFROMPLAYER__CREATUREOBJECT_INT_.
Referenced by AddPowerCommand::doQueueCommand().
void ResourceManager::sendResourceListForSurvey (CreatureObject * playerCreature, const int toolType, const String & surveyType)
Definition at line 115 of file ResourceManager.cpp.
References _getImplementation(), RPC_SENDRESOURCELISTFORSURVEY__CREATUREOBJECT_INT_STRING_, and server::zone::managers::resource::ResourceManagerImplementation::sendResourceListForSurvey().
void ResourceManager::sendSample (CreatureObject * playerCreature, const String & resname, const String & sampleAnimation)
Definition at line 146 of file ResourceManager.cpp.
References _getImplementation(), RPC_SENDSAMPLE__CREATUREOBJECT_STRING_STRING_, and server::zone::managers::resource::ResourceManagerImplementation::sendSample().
void ResourceManager::sendSurvey (CreatureObject * playerCreature, const String & resname)
Definition at line 131 of file ResourceManager.cpp.
References _getImplementation(), RPC_SENDSURVEY__CREATUREOBJECT_STRING_, and server::zone::managers::resource::ResourceManagerImplementation::sendSurvey().
void ResourceManager::shiftResources ()
Definition at line 71 of file ResourceManager.cpp.
References _getImplementation(), RPC_SHIFTRESOURCES__, and server::zone::managers::resource::ResourceManagerImplementation::shiftResources().
void ResourceManager::stop ()
Definition at line 45 of file ResourceManager.cpp.
References _getImplementation(), RPC_STOP__, and server::zone::managers::resource::ResourceManagerImplementation::stop().
Friends And Related Function Documentation
friend class ResourceManagerHelper friend
Definition at line 213 of file ResourceManager.h.
Member Data Documentation
const int server::zone::managers::resource::ResourceManager::RESOURCE_DEED_QUANTITY = 100000 static
Definition at line 145 of file ResourceManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/ResourceManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/ResourceManager.cpp