Core3: HealBattleFatigueSelf2Command Class Reference
HealBattleFatigueSelf2Command Class Reference
#include <HealBattleFatigueSelf2Command.h>
Public Member Functions
HealBattleFatigueSelf2Command (const String &name, ZoneProcessServer *server)
bool canPerformSkill (CreatureObject *creature)
int healBattleFatigue (CreatureObject *creature, int damage)
int doQueueCommand (CreatureObject *creature, const uint64 &target, const UnicodeString &arguments)
float getCommandDuration (CreatureObject *object, const UnicodeString &arguments)
Detailed Description
Definition at line 50 of file HealBattleFatigueSelf2Command.h.
Constructor & Destructor Documentation
HealBattleFatigueSelf2Command::HealBattleFatigueSelf2Command (const String & name, ZoneProcessServer * server) inline
Definition at line 53 of file HealBattleFatigueSelf2Command.h.
Member Function Documentation
bool HealBattleFatigueSelf2Command::canPerformSkill (CreatureObject * creature) inline
Definition at line 58 of file HealBattleFatigueSelf2Command.h.
References server::zone::objects::creature::CreatureObject::getShockWounds(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by doQueueCommand().
int HealBattleFatigueSelf2Command::doQueueCommand (CreatureObject * creature, const uint64 & target, const UnicodeString & arguments) inline
Definition at line 80 of file HealBattleFatigueSelf2Command.h.
References canPerformSkill(), server::zone::objects::creature::CreatureObject::getPlayerObject(), healBattleFatigue(), server::zone::objects::creature::CreatureObject::playEffect(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
float HealBattleFatigueSelf2Command::getCommandDuration (CreatureObject * object, const UnicodeString & arguments) inline
Definition at line 138 of file HealBattleFatigueSelf2Command.h.
int HealBattleFatigueSelf2Command::healBattleFatigue (CreatureObject * creature, int damage) inline
Definition at line 68 of file HealBattleFatigueSelf2Command.h.
References server::zone::objects::creature::CreatureObject::addShockWounds(), and server::zone::objects::creature::CreatureObject::getShockWounds().
Referenced by doQueueCommand().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/commands/HealBattleFatigueSelf2Command.h