Core3: ProceduralTerrainAppearance Class Reference
ProceduralTerrainAppearance Class Reference
#include <ProceduralTerrainAppearance.h>
Public Member Functions
ProceduralTerrainAppearance ()
~ProceduralTerrainAppearance ()
bool load (engine::util::IffStream *iffStream)
void parseFromIffStream (engine::util::IffStream *iffStream)
void parseFromIffStream (engine::util::IffStream *iffStream, Version<'0014'>)
void insertWaterBoundary (Boundary *boundary)
float getSize ()
bool getWater (float x, float y, float &waterHeight)
float getHeight (float x, float y)
int getEnvironmentID (float x, float y)
TerrainGenerator * addTerrainModification (engine::util::IffStream *terrainGeneratorIffStream, float x, float y, uint64 objectid)
void removeTerrainModification (uint64 objectid)
Public Member Functions inherited from TemplateVariable<'PTAT'>
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Protected Member Functions
float calculateFeathering (float value, int featheringType)
float processTerrain (Layer *layer, float x, float y, float &baseValue, float affectorTransformValue, int affectorType)
Layer * getLayerRecursive (float x, float y, Layer *rootParent)
Layer * getLayer (float x, float y)
void translateBoundaries (Layer *layer, float x, float y)
void setHeight (Layer *layer, float height)
Private Attributes
TerrainGenerator * terrainGenerator
Vector< Boundary * > waterBoundaries
TerrainMaps * terrainMaps
String terrainFile
float size
float chunkSize
uint32 tilesPerChunk
uint32 useGlobalWaterTable
float globalWaterTableHeight
float globalWaterTableShaderSize
String globalWaterTableShader
float timeCycle
uint32 floraCollidableMinDistance
float floraCollidableMaxDistance
float floraCollidableTileSize
float floraCollidableTileBorder
float floraCollidableSeed
uint32 floraNonCollidableMinDistance
float floraNonCollidableMaxDistance
float floraNonCollidableTileSize
float floraNonCollidableTileBorder
float floraNonCollidableSeed
uint32 radialNearMinDistance
float radialNearMaxDistance
float radialNearTileSize
float radialNearTileBorder
float radialNearSeed
float radialFarMinDistance
float radialFarMaxDistance
float radialFarTileSize
float radialFarTileBorder
float radialFarSeed
ReadWriteLock guard
HashTable< uint64,
TerrainGenerator * > terrainModifications
Vector< TerrainGenerator * > customTerrain
Detailed Description
Definition at line 21 of file ProceduralTerrainAppearance.h.
Constructor & Destructor Documentation
ProceduralTerrainAppearance::ProceduralTerrainAppearance ()
Definition at line 15 of file ProceduralTerrainAppearance.cpp.
References terrainGenerator, terrainMaps, and useGlobalWaterTable.
ProceduralTerrainAppearance::~ProceduralTerrainAppearance ()
Definition at line 22 of file ProceduralTerrainAppearance.cpp.
References terrainGenerator, and terrainMaps.
Member Function Documentation
TerrainGenerator * ProceduralTerrainAppearance::addTerrainModification (engine::util::IffStream * terrainGeneratorIffStream, float x, float y, uint64 objectid)
Definition at line 422 of file ProceduralTerrainAppearance.cpp.
References customTerrain, getHeight(), LayersGroup::getLayers(), TerrainGenerator::getLayersGroup(), guard, Layer::isEnabled(), TerrainGenerator::parseFromIffStream(), setHeight(), terrainModifications, and translateBoundaries().
Referenced by TerrainManager::addTerrainModification().
float ProceduralTerrainAppearance::calculateFeathering (float value, int featheringType) protected
Definition at line 181 of file ProceduralTerrainAppearance.cpp.
Referenced by processTerrain().
int ProceduralTerrainAppearance::getEnvironmentID (float x, float y)
Definition at line 320 of file ProceduralTerrainAppearance.cpp.
References customTerrain, AffectorProceduralRule::ENVIRONMENT, LayersGroup::getLayers(), TerrainGenerator::getLayersGroup(), guard, Layer::isEnabled(), processTerrain(), and terrainGenerator.
float ProceduralTerrainAppearance::getHeight (float x, float y)
Definition at line 349 of file ProceduralTerrainAppearance.cpp.
References customTerrain, LayersGroup::getLayers(), TerrainGenerator::getLayersGroup(), guard, AffectorProceduralRule::HEIGHTTYPE, Layer::isEnabled(), processTerrain(), and terrainGenerator.
Referenced by addTerrainModification(), and TEST_F().
Layer * ProceduralTerrainAppearance::getLayer (float x, float y) protected
Definition at line 158 of file ProceduralTerrainAppearance.cpp.
References getLayerRecursive(), LayersGroup::getLayers(), TerrainGenerator::getLayersGroup(), Layer::isEnabled(), and terrainGenerator.
Layer * ProceduralTerrainAppearance::getLayerRecursive (float x, float y, Layer * rootParent) protected
Definition at line 132 of file ProceduralTerrainAppearance.cpp.
References Layer::getBoundaries(), and Layer::getChildren().
Referenced by getLayer().
float ProceduralTerrainAppearance::getSize () inline
Returns the size of the terrain.
Returns
float The size of the terrain.
Definition at line 98 of file ProceduralTerrainAppearance.h.
References size.
bool ProceduralTerrainAppearance::getWater (float x, float y, float & waterHeight)
Definition at line 112 of file ProceduralTerrainAppearance.cpp.
References Boundary::containsPoint(), Boundary::getLocalWaterTableHeight(), globalWaterTableHeight, guard, useGlobalWaterTable, and waterBoundaries.
void ProceduralTerrainAppearance::insertWaterBoundary (Boundary * boundary) inline
Definition at line 90 of file ProceduralTerrainAppearance.h.
References waterBoundaries.
Referenced by BoundaryPolygon::executeRule(), and BoundaryRectangle::executeRule().
bool ProceduralTerrainAppearance::load (engine::util::IffStream * iffStream)
Definition at line 30 of file ProceduralTerrainAppearance.cpp.
References TerrainGenerator::processLayers(), TemplateVariable<'PTAT'>::readObject(), terrainGenerator, terrainMaps, and waterBoundaries.
Referenced by TerrainManager::initialize().
void ProceduralTerrainAppearance::parseFromIffStream (engine::util::IffStream * iffStream) virtual
Reimplemented from TemplateVariable<'PTAT'>.
Definition at line 46 of file ProceduralTerrainAppearance.cpp.
void ProceduralTerrainAppearance::parseFromIffStream (engine::util::IffStream * iffStream, Version<'0014'>)
Definition at line 63 of file ProceduralTerrainAppearance.cpp.
References chunkSize, floraCollidableMaxDistance, floraCollidableMinDistance, floraCollidableSeed, floraCollidableTileBorder, floraCollidableTileSize, floraNonCollidableMaxDistance, floraNonCollidableMinDistance, floraNonCollidableSeed, floraNonCollidableTileBorder, floraNonCollidableTileSize, globalWaterTableHeight, globalWaterTableShader, globalWaterTableShaderSize, radialFarMaxDistance, radialFarMinDistance, radialFarSeed, radialFarTileBorder, radialFarTileSize, radialNearMaxDistance, radialNearMinDistance, radialNearSeed, radialNearTileBorder, radialNearTileSize, TemplateVariable< formType >::readObject(), size, terrainFile, terrainGenerator, terrainMaps, tilesPerChunk, timeCycle, and useGlobalWaterTable.
float ProceduralTerrainAppearance::processTerrain (Layer * layer, float x, float y, float & baseValue, float affectorTransformValue, int affectorType) protected
Definition at line 211 of file ProceduralTerrainAppearance.cpp.
References calculateFeathering(), Layer::getAffectors(), AffectorProceduralRule::getAffectorType(), Layer::getBoundaries(), Layer::getChildren(), Boundary::getFeatheringType(), FilterProceduralRule::getFeatheringType(), Layer::getFilters(), Boundary::getMaxX(), Boundary::getMaxY(), Boundary::getMinX(), Boundary::getMinY(), Layer::invertBoundaries(), Layer::invertFilters(), Boundary::isEnabled(), AffectorProceduralRule::isEnabled(), FilterProceduralRule::isEnabled(), Layer::isEnabled(), FilterRectangle::maxX, FilterRectangle::maxY, FilterRectangle::minX, FilterRectangle::minY, AffectorProceduralRule::process(), Boundary::process(), FilterProceduralRule::process(), and terrainGenerator.
Referenced by getEnvironmentID(), and getHeight().
void ProceduralTerrainAppearance::removeTerrainModification (uint64 objectid)
Definition at line 461 of file ProceduralTerrainAppearance.cpp.
References customTerrain, guard, and terrainModifications.
Referenced by TerrainManager::removeTerrainModification().
void ProceduralTerrainAppearance::setHeight (Layer * layer, float height) protected
Definition at line 398 of file ProceduralTerrainAppearance.cpp.
References Layer::getAffectors(), Layer::getChildren(), AffectorHeightConstant::getHeight(), AffectorHeightConstant::getOperationType(), Layer::isEnabled(), and AffectorHeightConstant::setHeight().
Referenced by addTerrainModification().
void ProceduralTerrainAppearance::translateBoundaries (Layer * layer, float x, float y) protected
Definition at line 378 of file ProceduralTerrainAppearance.cpp.
References Layer::getBoundaries(), Layer::getChildren(), Layer::isEnabled(), and Boundary::translateBoundary().
Referenced by addTerrainModification().
Member Data Documentation
float ProceduralTerrainAppearance::chunkSize private
Definition at line 32 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
Vector<TerrainGenerator*> ProceduralTerrainAppearance::customTerrain private
Definition at line 70 of file ProceduralTerrainAppearance.h.
Referenced by addTerrainModification(), getEnvironmentID(), getHeight(), and removeTerrainModification().
float ProceduralTerrainAppearance::floraCollidableMaxDistance private
Definition at line 43 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
uint32 ProceduralTerrainAppearance::floraCollidableMinDistance private
Definition at line 42 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::floraCollidableSeed private
Definition at line 46 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::floraCollidableTileBorder private
Definition at line 45 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::floraCollidableTileSize private
Definition at line 44 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::floraNonCollidableMaxDistance private
Definition at line 49 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
uint32 ProceduralTerrainAppearance::floraNonCollidableMinDistance private
Definition at line 48 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::floraNonCollidableSeed private
Definition at line 52 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::floraNonCollidableTileBorder private
Definition at line 51 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::floraNonCollidableTileSize private
Definition at line 50 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::globalWaterTableHeight private
Definition at line 36 of file ProceduralTerrainAppearance.h.
Referenced by getWater(), and parseFromIffStream().
String ProceduralTerrainAppearance::globalWaterTableShader private
Definition at line 38 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::globalWaterTableShaderSize private
Definition at line 37 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
ReadWriteLock ProceduralTerrainAppearance::guard private
Definition at line 66 of file ProceduralTerrainAppearance.h.
Referenced by addTerrainModification(), getEnvironmentID(), getHeight(), getWater(), and removeTerrainModification().
float ProceduralTerrainAppearance::radialFarMaxDistance private
Definition at line 61 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::radialFarMinDistance private
Definition at line 60 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::radialFarSeed private
Definition at line 64 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::radialFarTileBorder private
Definition at line 63 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::radialFarTileSize private
Definition at line 62 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::radialNearMaxDistance private
Definition at line 55 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
uint32 ProceduralTerrainAppearance::radialNearMinDistance private
Definition at line 54 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::radialNearSeed private
Definition at line 58 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::radialNearTileBorder private
Definition at line 57 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::radialNearTileSize private
Definition at line 56 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::size private
Definition at line 31 of file ProceduralTerrainAppearance.h.
Referenced by getSize(), and parseFromIffStream().
String ProceduralTerrainAppearance::terrainFile private
Definition at line 30 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
TerrainGenerator* ProceduralTerrainAppearance::terrainGenerator private
Definition at line 22 of file ProceduralTerrainAppearance.h.
Referenced by getEnvironmentID(), getHeight(), getLayer(), load(), parseFromIffStream(), ProceduralTerrainAppearance(), processTerrain(), and ~ProceduralTerrainAppearance().
TerrainMaps* ProceduralTerrainAppearance::terrainMaps private
Definition at line 26 of file ProceduralTerrainAppearance.h.
Referenced by load(), parseFromIffStream(), ProceduralTerrainAppearance(), and ~ProceduralTerrainAppearance().
HashTable<uint64, TerrainGenerator*> ProceduralTerrainAppearance::terrainModifications private
Definition at line 68 of file ProceduralTerrainAppearance.h.
Referenced by addTerrainModification(), and removeTerrainModification().
uint32 ProceduralTerrainAppearance::tilesPerChunk private
Definition at line 33 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
float ProceduralTerrainAppearance::timeCycle private
Definition at line 40 of file ProceduralTerrainAppearance.h.
Referenced by parseFromIffStream().
uint32 ProceduralTerrainAppearance::useGlobalWaterTable private
Definition at line 35 of file ProceduralTerrainAppearance.h.
Referenced by getWater(), parseFromIffStream(), and ProceduralTerrainAppearance().
Vector<Boundary*> ProceduralTerrainAppearance::waterBoundaries private
Definition at line 24 of file ProceduralTerrainAppearance.h.
Referenced by getWater(), insertWaterBoundary(), and load().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/ProceduralTerrainAppearance.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/ProceduralTerrainAppearance.cpp