Core3: LogsServlet Class Reference
LogsServlet Class Reference
#include <LogsServlet.h>
Public Member Functions
LogsServlet (String context)
virtual ~LogsServlet ()
void handleGet (HttpRequest *request, HttpResponse *response)
void handlePost (HttpRequest *request, HttpResponse *response)
Public Member Functions inherited from Servlet
Servlet (String context)
virtual ~Servlet ()
void handleRequest (struct mg_connection *conn, HttpRequest *request, HttpResponse *response)
void setZoneServer (ZoneServer *serv)
String getContext ()
Additional Inherited Members
Protected Attributes inherited from Servlet
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 13 of file LogsServlet.h.
Constructor & Destructor Documentation
LogsServlet::LogsServlet (String context)
Definition at line 11 of file LogsServlet.cpp.
LogsServlet::~LogsServlet () virtual
Definition at line 17 of file LogsServlet.cpp.
Member Function Documentation
void LogsServlet::handleGet (HttpRequest * request, HttpResponse * response) virtual
Implements Servlet.
Definition at line 21 of file LogsServlet.cpp.
References server::web::HttpResponse::println().
Referenced by handlePost().
void LogsServlet::handlePost (HttpRequest * request, HttpResponse * response) virtual
Implements Servlet.
Definition at line 36 of file LogsServlet.cpp.
References handleGet().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/servlets/logs/LogsServlet.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/servlets/logs/LogsServlet.cpp