Core3: server::zone::objects::creature::ai::AiActor Class Reference
server::zone::objects::creature::ai::AiActor Class Reference
#include <AiActor.h>
Public Member Functions
AiActor ()
void setHost (CreatureObject *creo)
CreatureObject * getHost ()
void initializeTransientMembers ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void notifyPositionUpdate (QuadTreeEntry *entry)
void setCurrentMessage (unsigned short msg)
void next (unsigned short msg)
void next ()
void destroyActor ()
void doAwarenessCheck (Coordinate &start, unsigned long long time, CreatureObject *target)
void addTransition (const String &stateName, unsigned short msg, const String &resultState)
void loadTemplateData (CreatureTemplate *templateData)
CreatureTemplateReference * getNpcTemplate ()
void setLevel (int lvl)
int calculateAttackMinDamage (int level)
int calculateAttackMaxDamage (int level)
float calculateAttackSpeed (int level)
bool isCamouflaged (CreatureObject *target)
bool isScentMasked (CreatureObject *target)
bool isConcealed (CreatureObject *target)
void activateRecovery ()
void activateMovementEvent ()
void activateAwarenessEvent (CreatureObject *target)
void activatePostureRecovery ()
void queueDizzyFallEvent ()
void setNextPosition (PatrolPoint &point)
void setNextStepPosition (float x, float z, float y, SceneObject *cell=NULL)
PatrolPoint * getNextStepPosition ()
void setShowNextPosition (bool val)
bool isShowNextPosition ()
Vector< ManagedReference
< SceneObject * > > * getMovementMarkers ()
int getMovementMarkersSize ()
SceneObject * getMovementMarker (int i)
void dropMovementMarker (SceneObject *marker)
void dropAllMovemementMarkers ()
void addMovementMarker (SceneObject *marker)
void clearPatrolPoints ()
PatrolPointsVector * getPatrolPoints ()
void addPatrolPoint (PatrolPoint &point)
void setHomeLocation (float x, float z, float y, SceneObject *cell=NULL)
PatrolPoint * getHomeLocation ()
void setDespawnOnNoPlayerInRange (bool val)
void notifyDespawn (Zone *zone)
void scheduleDespawn (int timeToDespawn)
void respawn (Zone *zone, int level)
void scheduleDespawn ()
void clearDespawnEvent ()
void setRespawnTimer (float resp)
float getRespawnTimer ()
bool getDespawnOnNoPlayerInRange ()
int getNumberOfPlayersInRange ()
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
int notifyConverseObservers (CreatureObject *converser)
SceneObject * getFollowObject ()
void setFollowObject (SceneObject *targ)
void setTargetObject (SceneObject *obj)
void setOblivious ()
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
void updateLastDamageReceived ()
void sendConversationStartTo (SceneObject *player)
float getKinetic ()
float getEnergy ()
float getElectricity ()
float getStun ()
float getBlast ()
float getHeat ()
float getCold ()
float getAcid ()
float getLightSaber ()
bool isStalker ()
bool isKiller ()
unsigned int getFerocity ()
unsigned int getArmor ()
String getFactionString ()
String getSocialGroup ()
float getChanceHit ()
int getDamageMin ()
int getDamageMax ()
int getBaseXp ()
unsigned int getDiet ()
CreatureAttackMap * getAttackMap ()
LootGroupCollection * getLootGroups ()
CreatureTemplate * getCreatureTemplate ()
Vector< ManagedReference
< WeaponObject * > > getWeapons ()
Time getLastDamageReceived ()
bool isActorObject ()
int getBehaviorStatus (Behavior *b)
void setBehaviorStatus (Behavior *b, int status)
void addBehaviorToTree (BehaviorTree *tree, Behavior *b)
Behavior * getNextBehaviorFromTree (BehaviorTree *tree)
void resetBehaviorList (BehaviorTree *tree)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject ()
void initializePrivateData ()
void loadTemplateData (SharedObjectTemplate *templateData)
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
void destroyObjectFromDatabase (bool destroyContainedObjects=false)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose=true)
void sendAttributeListTo (CreatureObject *object)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
void openContainerTo (CreatureObject *player)
byte checkContainerPermission (CreatureObject *player, unsigned short permission)
void closeContainerTo (CreatureObject *player, bool notify=true)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets=true)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
String getDetailedDescription ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
void createChildObjects ()
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static unsigned const short FINISHED = 0
static unsigned const short UNFINISHED = 1
static unsigned const short ATTACKED = 2
static unsigned const short INTERESTED = 3
static unsigned const short DEAD = 4
static unsigned const short ALMOSTDEAD = 5
static unsigned const short SCARED = 6
static unsigned const short FORGOT = 7
static unsigned const short NONE = 0xFFFF
static const int UPDATEMOVEMENTINTERVAL = 500
Protected Member Functions
AiActor (DummyConstructorParameter *param)
virtual ~AiActor ()
Protected Member Functions inherited from server::zone::objects::scene::SceneObject
SceneObject (DummyConstructorParameter *param)
virtual ~SceneObject ()
Friends
class AiActorHelper
Detailed Description
Definition at line 240 of file AiActor.h.
Constructor & Destructor Documentation
AiActor::AiActor ()
Definition at line 37 of file AiActor.cpp.
References server::zone::objects::creature::ai::AiActorImplementation::_setStub().
AiActor::AiActor (DummyConstructorParameter * param) protected
Definition at line 44 of file AiActor.cpp.
AiActor::~AiActor () protected virtual
Definition at line 48 of file AiActor.cpp.
Member Function Documentation
DistributedObjectServant * AiActor::_getImplementation ()
Definition at line 1275 of file AiActor.cpp.
Referenced by activateAwarenessEvent(), activateMovementEvent(), activatePostureRecovery(), activateRecovery(), addBehaviorToTree(), addDefender(), addMovementMarker(), addPatrolPoint(), addTransition(), calculateAttackMaxDamage(), calculateAttackMinDamage(), calculateAttackSpeed(), clearDespawnEvent(), clearPatrolPoints(), destroyActor(), doAwarenessCheck(), dropAllMovemementMarkers(), dropMovementMarker(), fillAttributeList(), getAcid(), getArmor(), getAttackMap(), getBaseXp(), getBehaviorStatus(), getBlast(), getChanceHit(), getCold(), getCreatureTemplate(), getDamageMax(), getDamageMin(), getDespawnOnNoPlayerInRange(), getDiet(), getElectricity(), getEnergy(), getFactionString(), getFerocity(), getFollowObject(), getHeat(), getHomeLocation(), getHost(), getKinetic(), getLastDamageReceived(), getLightSaber(), getLootGroups(), getMovementMarker(), getMovementMarkers(), getMovementMarkersSize(), getNextBehaviorFromTree(), getNextStepPosition(), getNumberOfPlayersInRange(), getPatrolPoints(), getRespawnTimer(), getSocialGroup(), getStun(), getWeapons(), initializeTransientMembers(), isActorObject(), isAggressiveTo(), isAttackableBy(), isCamouflaged(), isConcealed(), isKiller(), isScentMasked(), isShowNextPosition(), isStalker(), loadTemplateData(), next(), notifyConverseObservers(), notifyDespawn(), notifyDissapear(), notifyInsert(), notifyPositionUpdate(), queueDizzyFallEvent(), removeDefender(), resetBehaviorList(), respawn(), scheduleDespawn(), sendConversationStartTo(), setBehaviorStatus(), setCurrentMessage(), setDefender(), setDespawnOnNoPlayerInRange(), setFollowObject(), setHomeLocation(), setHost(), setLevel(), setNextPosition(), setNextStepPosition(), setOblivious(), setRespawnTimer(), setShowNextPosition(), setTargetObject(), and updateLastDamageReceived().
DistributedObjectServant * AiActor::_getImplementationForRead ()
Definition at line 1281 of file AiActor.cpp.
Referenced by getNpcTemplate().
void AiActor::_setImplementation (DistributedObjectServant * servant)
Definition at line 1285 of file AiActor.cpp.
void AiActor::activateAwarenessEvent (CreatureObject * target)
Definition at line 343 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::activateAwarenessEvent(), and RPC_ACTIVATEAWARENESSEVENT__CREATUREOBJECT_.
void AiActor::activateMovementEvent ()
Definition at line 330 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::activateMovementEvent(), and RPC_ACTIVATEMOVEMENTEVENT__.
Referenced by AlertStateComponent::doMovement(), AiStateComponent::doMovement(), RetreatStateComponent::onEnter(), AlertStateComponent::onEnter(), WanderingStateComponent::onEnter(), AttackStateComponent::onEnter(), and AiStateComponent::onEnter().
void AiActor::activatePostureRecovery ()
Definition at line 357 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::activatePostureRecovery(), and RPC_ACTIVATEPOSTURERECOVERY__.
Referenced by FleeStateComponent::doRecovery(), AttackStateComponent::doRecovery(), StandingStateComponent::doRecovery(), AlertStateComponent::doRecovery(), RetreatStateComponent::doRecovery(), and WanderingStateComponent::doRecovery().
void AiActor::activateRecovery ()
Definition at line 317 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::activateRecovery(), and RPC_ACTIVATERECOVERY__.
Referenced by FleeStateComponent::doRecovery(), AlertStateComponent::doRecovery(), RetreatStateComponent::doRecovery(), RetreatStateComponent::onEnter(), StandingStateComponent::onEnter(), AlertStateComponent::onEnter(), AttackStateComponent::onEnter(), WanderingStateComponent::onEnter(), SpawnStateComponent::onEnter(), and AiStateComponent::onEnter().
void AiActor::addBehaviorToTree (BehaviorTree * tree, Behavior * b)
Definition at line 1248 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::addBehaviorToTree().
void AiActor::addDefender (SceneObject * defender)
Definition at line 825 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::addDefender(), and RPC_ADDDEFENDER__SCENEOBJECT_.
void AiActor::addMovementMarker (SceneObject * marker)
Definition at line 508 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::addMovementMarker(), and RPC_ADDMOVEMENTMARKER__SCENEOBJECT_.
void AiActor::addPatrolPoint (PatrolPoint & point)
Definition at line 544 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::addPatrolPoint().
void AiActor::addTransition (const String & stateName, unsigned short msg, const String & resultState)
Definition at line 185 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::addTransition(), and RPC_ADDTRANSITION__STRING_SHORT_STRING_.
int AiActor::calculateAttackMaxDamage (int level)
Definition at line 247 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::calculateAttackMaxDamage(), and RPC_CALCULATEATTACKMAXDAMAGE__INT_.
int AiActor::calculateAttackMinDamage (int level)
Definition at line 233 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::calculateAttackMinDamage(), and RPC_CALCULATEATTACKMINDAMAGE__INT_.
float AiActor::calculateAttackSpeed (int level)
Definition at line 261 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::calculateAttackSpeed(), and RPC_CALCULATEATTACKSPEED__INT_.
void AiActor::clearDespawnEvent ()
Definition at line 649 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::clearDespawnEvent(), and RPC_CLEARDESPAWNEVENT__.
void AiActor::clearPatrolPoints ()
Definition at line 522 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::clearPatrolPoints(), and RPC_CLEARPATROLPOINTS__.
void AiActor::destroyActor ()
Definition at line 163 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::destroyActor(), and RPC_DESTROYACTOR__.
void AiActor::doAwarenessCheck (Coordinate & start, unsigned long long time, CreatureObject * target)
Definition at line 176 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::doAwarenessCheck().
void AiActor::dropAllMovemementMarkers ()
Definition at line 495 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::dropAllMovemementMarkers(), and RPC_DROPALLMOVEMEMENTMARKERS__.
void AiActor::dropMovementMarker (SceneObject * marker)
Definition at line 481 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::dropMovementMarker(), and RPC_DROPMOVEMENTMARKER__SCENEOBJECT_.
void AiActor::fillAttributeList (AttributeListMessage * msg, CreatureObject * object)
Definition at line 93 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::fillAttributeList(), and RPC_FILLATTRIBUTELIST__ATTRIBUTELISTMESSAGE_CREATUREOBJECT_.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::fillAttributeList().
float AiActor::getAcid ()
Definition at line 999 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getAcid(), and RPC_GETACID__.
unsigned int AiActor::getArmor ()
Definition at line 1064 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getArmor(), and RPC_GETARMOR__.
CreatureAttackMap * AiActor::getAttackMap ()
Definition at line 1172 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::getAttackMap().
int AiActor::getBaseXp ()
Definition at line 1146 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getBaseXp(), and RPC_GETBASEXP__.
int AiActor::getBehaviorStatus (Behavior * b)
Definition at line 1230 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::getBehaviorStatus().
float AiActor::getBlast ()
Definition at line 960 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getBlast(), and RPC_GETBLAST__.
float AiActor::getChanceHit ()
Definition at line 1107 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getChanceHit(), and RPC_GETCHANCEHIT__.
float AiActor::getCold ()
Definition at line 986 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getCold(), and RPC_GETCOLD__.
CreatureTemplate * AiActor::getCreatureTemplate ()
Definition at line 1190 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::getCreatureTemplate().
Referenced by AttackStateComponent::doRecovery(), and AiStateComponent::notifyDespawn().
int AiActor::getDamageMax ()
Definition at line 1133 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getDamageMax(), and RPC_GETDAMAGEMAX__.
int AiActor::getDamageMin ()
Definition at line 1120 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getDamageMin(), and RPC_GETDAMAGEMIN__.
bool AiActor::getDespawnOnNoPlayerInRange ()
Definition at line 689 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getDespawnOnNoPlayerInRange(), and RPC_GETDESPAWNONNOPLAYERINRANGE__.
unsigned int AiActor::getDiet ()
Definition at line 1159 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getDiet(), and RPC_GETDIET__.
float AiActor::getElectricity ()
Definition at line 934 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getElectricity(), and RPC_GETELECTRICITY__.
float AiActor::getEnergy ()
Definition at line 921 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getEnergy(), and RPC_GETENERGY__.
String AiActor::getFactionString ()
Definition at line 1077 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getFactionString(), and RPC_GETFACTIONSTRING__.
unsigned int AiActor::getFerocity ()
Definition at line 1051 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getFerocity(), and RPC_GETFEROCITY__.
SceneObject * AiActor::getFollowObject ()
Definition at line 757 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getFollowObject(), and RPC_GETFOLLOWOBJECT__.
Referenced by AiStateComponent::checkNewAngle(), FleeStateComponent::doMovement(), RetreatStateComponent::doMovement(), AlertStateComponent::doMovement(), AttackStateComponent::doMovement(), FleeStateComponent::doRecovery(), AttackStateComponent::doRecovery(), AlertStateComponent::doRecovery(), and AiStateComponent::selectWeapon().
float AiActor::getHeat ()
Definition at line 973 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getHeat(), and RPC_GETHEAT__.
PatrolPoint * AiActor::getHomeLocation ()
Definition at line 570 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::getHomeLocation().
Referenced by RetreatStateComponent::onEnter(), WanderingStateComponent::onEnter(), and SpawnStateComponent::onEnter().
CreatureObject * AiActor::getHost ()
Definition at line 67 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getHost(), and RPC_GETHOST__.
Referenced by AiStateComponent::checkNewAngle(), FleeStateComponent::doMovement(), RetreatStateComponent::doMovement(), AlertStateComponent::doMovement(), AiStateComponent::doMovement(), FleeStateComponent::doRecovery(), AttackStateComponent::doRecovery(), StandingStateComponent::doRecovery(), AlertStateComponent::doRecovery(), RetreatStateComponent::doRecovery(), WanderingStateComponent::doRecovery(), AiStateComponent::notifyDespawn(), RetreatStateComponent::onEnter(), StandingStateComponent::onEnter(), AlertStateComponent::onEnter(), DeathStateComponent::onEnter(), AttackStateComponent::onEnter(), SpawnStateComponent::onEnter(), WanderingStateComponent::onEnter(), AiStateComponent::onEnter(), AiStateComponent::selectWeapon(), and server::zone::managers::creature::CreatureManagerImplementation::spawnCreatureWithAi().
float AiActor::getKinetic ()
Definition at line 908 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getKinetic(), and RPC_GETKINETIC__.
Time AiActor::getLastDamageReceived ()
Definition at line 1208 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::getLastDamageReceived().
Referenced by AttackStateComponent::doRecovery().
float AiActor::getLightSaber ()
Definition at line 1012 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getLightSaber(), and RPC_GETLIGHTSABER__.
LootGroupCollection * AiActor::getLootGroups ()
Definition at line 1181 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::getLootGroups().
SceneObject * AiActor::getMovementMarker (int i)
Definition at line 467 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getMovementMarker(), and RPC_GETMOVEMENTMARKER__INT_.
Referenced by AiStateComponent::notifyDespawn().
Vector< ManagedReference< SceneObject * > > * AiActor::getMovementMarkers ()
Definition at line 445 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::getMovementMarkers().
int AiActor::getMovementMarkersSize ()
Definition at line 454 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getMovementMarkersSize(), and RPC_GETMOVEMENTMARKERSSIZE__.
Referenced by AiStateComponent::notifyDespawn().
Behavior * AiActor::getNextBehaviorFromTree (BehaviorTree * tree)
Definition at line 1257 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::getNextBehaviorFromTree().
PatrolPoint * AiActor::getNextStepPosition ()
Definition at line 409 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::getNextStepPosition().
Referenced by AiStateComponent::checkNewAngle(), and AiStateComponent::doMovement().
CreatureTemplateReference * AiActor::getNpcTemplate ()
Definition at line 210 of file AiActor.cpp.
References _getImplementationForRead(), and server::zone::objects::creature::ai::AiActorImplementation::getNpcTemplate().
Referenced by SpawnStateComponent::onEnter().
int AiActor::getNumberOfPlayersInRange ()
Definition at line 702 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getNumberOfPlayersInRange(), and RPC_GETNUMBEROFPLAYERSINRANGE__.
PatrolPointsVector * AiActor::getPatrolPoints ()
Definition at line 535 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::getPatrolPoints().
Referenced by FleeStateComponent::doMovement(), AiStateComponent::doMovement(), AttackStateComponent::doMovement(), RetreatStateComponent::onEnter(), StandingStateComponent::onEnter(), and WanderingStateComponent::onEnter().
float AiActor::getRespawnTimer ()
Definition at line 676 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getRespawnTimer(), and RPC_GETRESPAWNTIMER__.
Referenced by AiStateComponent::notifyDespawn(), and DeathStateComponent::onEnter().
String AiActor::getSocialGroup ()
Definition at line 1092 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getSocialGroup(), and RPC_GETSOCIALGROUP__.
float AiActor::getStun ()
Definition at line 947 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::getStun(), and RPC_GETSTUN__.
Vector< ManagedReference< WeaponObject * > > AiActor::getWeapons ()
Definition at line 1199 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::getWeapons().
Referenced by AiStateComponent::selectWeapon().
void AiActor::initializeTransientMembers ()
Initializes the transient members of ManagedObject, must call the inherited object method first.
Precondition
{ transient members are not initialized }
Postcondition
{ transient members are initialized }
Definition at line 80 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
bool AiActor::isActorObject ()
Definition at line 1217 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::isActorObject(), and RPC_ISACTOROBJECT__.
bool AiActor::isAggressiveTo (CreatureObject * object)
Evaluates if this creature is aggresive to the object
Precondition
{ }
Postcondition
{ }
Returns
returns true if its aggressive
Definition at line 867 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::isAggressiveTo(), and RPC_ISAGGRESSIVETO__CREATUREOBJECT_.
bool AiActor::isAttackableBy (CreatureObject * object)
Evaluates if this object can be attacket by the passed creature object
Precondition
{ this object is locked }
Postcondition
{ this object is locked }
Returns
returns true if the creature object can attack this
Definition at line 853 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::isAttackableBy(), and RPC_ISATTACKABLEBY__CREATUREOBJECT_.
bool AiActor::isCamouflaged (CreatureObject * target)
Definition at line 275 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::isCamouflaged(), and RPC_ISCAMOUFLAGED__CREATUREOBJECT_.
bool AiActor::isConcealed (CreatureObject * target)
Definition at line 303 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::isConcealed(), and RPC_ISCONCEALED__CREATUREOBJECT_.
bool AiActor::isKiller ()
Definition at line 1038 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::isKiller(), and RPC_ISKILLER__.
bool AiActor::isScentMasked (CreatureObject * target)
Definition at line 289 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::isScentMasked(), and RPC_ISSCENTMASKED__CREATUREOBJECT_.
bool AiActor::isShowNextPosition ()
Definition at line 432 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::isShowNextPosition(), and RPC_ISSHOWNEXTPOSITION__.
bool AiActor::isStalker ()
Definition at line 1025 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::isStalker(), and RPC_ISSTALKER__.
void AiActor::loadTemplateData (CreatureTemplate * templateData)
Definition at line 201 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData().
Referenced by AiStateComponent::notifyDespawn(), SpawnStateComponent::onEnter(), and server::zone::managers::creature::CreatureManagerImplementation::spawnCreatureWithAi().
void AiActor::next (unsigned short msg)
calculate next state based on initial state and message
Definition at line 136 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::next(), and RPC_NEXT__SHORT_.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::clearCombatState().
void AiActor::next ()
Definition at line 150 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::next(), and RPC_NEXT__.
int AiActor::notifyConverseObservers (CreatureObject * converser)
Definition at line 743 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::notifyConverseObservers(), and RPC_NOTIFYCONVERSEOBSERVERS__CREATUREOBJECT_.
void AiActor::notifyDespawn (Zone * zone)
Definition at line 593 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::notifyDespawn(), and RPC_NOTIFYDESPAWN__ZONE_.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::destroyObjectFromWorld().
void AiActor::notifyDissapear (QuadTreeEntry * entry)
Definition at line 729 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::notifyDissapear(), and RPC_NOTIFYDISSAPEAR__QUADTREEENTRY_.
void AiActor::notifyInsert (QuadTreeEntry * entry)
Definition at line 715 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::notifyInsert(), and RPC_NOTIFYINSERT__QUADTREEENTRY_.
void AiActor::notifyPositionUpdate (QuadTreeEntry * entry)
Uses position updates to perform a think
Definition at line 108 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::notifyPositionUpdate(), and RPC_NOTIFYPOSITIONUPDATE__QUADTREEENTRY_.
void AiActor::queueDizzyFallEvent ()
Definition at line 370 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::queueDizzyFallEvent(), and RPC_QUEUEDIZZYFALLEVENT__.
void AiActor::removeDefender (SceneObject * defender)
Definition at line 839 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::removeDefender(), and RPC_REMOVEDEFENDER__SCENEOBJECT_.
void AiActor::resetBehaviorList (BehaviorTree * tree)
Definition at line 1266 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::resetBehaviorList().
void AiActor::respawn (Zone * zone, int level)
Definition at line 621 of file AiActor.cpp.
References _getImplementation(), server::zone::objects::creature::ai::AiActorImplementation::respawn(), and RPC_RESPAWN__ZONE_INT_.
void AiActor::scheduleDespawn (int timeToDespawn)
Definition at line 607 of file AiActor.cpp.
References _getImplementation(), RPC_SCHEDULEDESPAWN__INT_, and server::zone::objects::creature::ai::AiActorImplementation::scheduleDespawn().
void AiActor::scheduleDespawn ()
Definition at line 636 of file AiActor.cpp.
References _getImplementation(), RPC_SCHEDULEDESPAWN__, and server::zone::objects::creature::ai::AiActorImplementation::scheduleDespawn().
void AiActor::sendConversationStartTo (SceneObject * player)
Definition at line 894 of file AiActor.cpp.
References _getImplementation(), RPC_SENDCONVERSATIONSTARTTO__SCENEOBJECT_, and server::zone::objects::creature::ai::AiActorImplementation::sendConversationStartTo().
Referenced by server::zone::objects::creature::CreatureObjectImplementation::sendConversationStartTo().
void AiActor::setBehaviorStatus (Behavior * b, int status)
Definition at line 1239 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::setBehaviorStatus().
void AiActor::setCurrentMessage (unsigned short msg)
Definition at line 122 of file AiActor.cpp.
References _getImplementation(), RPC_SETCURRENTMESSAGE__SHORT_, and server::zone::objects::creature::ai::AiActorImplementation::setCurrentMessage().
void AiActor::setDefender (SceneObject * defender)
Definition at line 811 of file AiActor.cpp.
References _getImplementation(), RPC_SETDEFENDER__SCENEOBJECT_, and server::zone::objects::creature::ai::AiActorImplementation::setDefender().
void AiActor::setDespawnOnNoPlayerInRange (bool val)
Definition at line 579 of file AiActor.cpp.
References _getImplementation(), RPC_SETDESPAWNONNOPLAYERINRANGE__BOOL_, and server::zone::objects::creature::ai::AiActorImplementation::setDespawnOnNoPlayerInRange().
void AiActor::setFollowObject (SceneObject * targ)
Definition at line 770 of file AiActor.cpp.
References _getImplementation(), RPC_SETFOLLOWOBJECT__SCENEOBJECT_, and server::zone::objects::creature::ai::AiActorImplementation::setFollowObject().
Referenced by AttackStateComponent::doRecovery(), and AiStateComponent::notifyDespawn().
void AiActor::setHomeLocation (float x, float z, float y, SceneObject * cell = NULL)
Definition at line 553 of file AiActor.cpp.
References _getImplementation(), RPC_SETHOMELOCATION__FLOAT_FLOAT_FLOAT_SCENEOBJECT_, and server::zone::objects::creature::ai::AiActorImplementation::setHomeLocation().
Referenced by server::zone::managers::creature::CreatureManagerImplementation::spawnCreatureWithAi().
void AiActor::setHost (CreatureObject * creo)
Definition at line 53 of file AiActor.cpp.
References _getImplementation(), RPC_SETHOST__CREATUREOBJECT_, and server::zone::objects::creature::ai::AiActorImplementation::setHost().
Referenced by SpawnStateComponent::onEnter().
void AiActor::setLevel (int lvl)
Definition at line 219 of file AiActor.cpp.
References _getImplementation(), RPC_SETLEVEL__INT_, and server::zone::objects::creature::ai::AiActorImplementation::setLevel().
Referenced by AiStateComponent::notifyDespawn().
void AiActor::setNextPosition (PatrolPoint & point)
Definition at line 383 of file AiActor.cpp.
References _getImplementation(), and server::zone::objects::creature::ai::AiActorImplementation::setNextPosition().
Referenced by AiStateComponent::setNextPosition().
void AiActor::setNextStepPosition (float x, float z, float y, SceneObject * cell = NULL)
Definition at line 392 of file AiActor.cpp.
References _getImplementation(), RPC_SETNEXTSTEPPOSITION__FLOAT_FLOAT_FLOAT_SCENEOBJECT_, and server::zone::objects::creature::ai::AiActorImplementation::setNextStepPosition().
void AiActor::setOblivious ()
Definition at line 798 of file AiActor.cpp.
References _getImplementation(), RPC_SETOBLIVIOUS__, and server::zone::objects::creature::ai::AiActorImplementation::setOblivious().
void AiActor::setRespawnTimer (float resp)
Definition at line 662 of file AiActor.cpp.
References _getImplementation(), RPC_SETRESPAWNTIMER__FLOAT_, and server::zone::objects::creature::ai::AiActorImplementation::setRespawnTimer().
void AiActor::setShowNextPosition (bool val)
Definition at line 418 of file AiActor.cpp.
References _getImplementation(), RPC_SETSHOWNEXTPOSITION__BOOL_, and server::zone::objects::creature::ai::AiActorImplementation::setShowNextPosition().
void AiActor::setTargetObject (SceneObject * obj)
Definition at line 784 of file AiActor.cpp.
References _getImplementation(), RPC_SETTARGETOBJECT__SCENEOBJECT_, and server::zone::objects::creature::ai::AiActorImplementation::setTargetObject().
Referenced by AiStateComponent::notifyDespawn().
void AiActor::updateLastDamageReceived ()
Definition at line 881 of file AiActor.cpp.
References _getImplementation(), RPC_UPDATELASTDAMAGERECEIVED__, and server::zone::objects::creature::ai::AiActorImplementation::updateLastDamageReceived().
Friends And Related Function Documentation
friend class AiActorHelper friend
Definition at line 489 of file AiActor.h.
Member Data Documentation
unsigned const short server::zone::objects::creature::ai::AiActor::ALMOSTDEAD = 5 static
Definition at line 252 of file AiActor.h.
unsigned const short server::zone::objects::creature::ai::AiActor::ATTACKED = 2 static
Definition at line 246 of file AiActor.h.
Referenced by server::zone::objects::creature::ai::AiActorImplementation::addDefender(), and server::zone::objects::creature::ai::AiActorImplementation::setDefender().
unsigned const short server::zone::objects::creature::ai::AiActor::DEAD = 4 static
Definition at line 250 of file AiActor.h.
unsigned const short server::zone::objects::creature::ai::AiActor::FINISHED = 0 static
Definition at line 242 of file AiActor.h.
unsigned const short server::zone::objects::creature::ai::AiActor::FORGOT = 7 static
Definition at line 256 of file AiActor.h.
Referenced by server::zone::objects::creature::ai::AiActorImplementation::removeDefender().
unsigned const short server::zone::objects::creature::ai::AiActor::INTERESTED = 3 static
Definition at line 248 of file AiActor.h.
unsigned const short server::zone::objects::creature::ai::AiActor::NONE = 0xFFFF static
Definition at line 258 of file AiActor.h.
unsigned const short server::zone::objects::creature::ai::AiActor::SCARED = 6 static
Definition at line 254 of file AiActor.h.
unsigned const short server::zone::objects::creature::ai::AiActor::UNFINISHED = 1 static
Definition at line 244 of file AiActor.h.
Referenced by server::zone::objects::creature::ai::AiActorImplementation::initializeTransientMembers().
const int server::zone::objects::creature::ai::AiActor::UPDATEMOVEMENTINTERVAL = 500 static
Definition at line 260 of file AiActor.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/AiActor.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/ai/AiActor.cpp