Core3: server::login::LoginClient Class Reference
server::login::LoginClient Class Reference
#include <LoginClient.h>
Public Member Functions
LoginClient (BaseClientProxy *session)
virtual ~LoginClient ()
void disconnect (bool doLock=true)
void sendMessage (Message *msg)
void sendErrorMessage (const String &title, const String &text, bool fatal=false)
void info (const String &msg, bool doLog=true)
ServiceClient * getSession ()
uint32 getAccountID ()
void setAccountID (uint32 account)
bool hasAccount ()
Private Attributes
Reference< BaseClientProxy * > session
uint32 accountID
Detailed Description
Definition at line 55 of file LoginClient.h.
Constructor & Destructor Documentation
server::login::LoginClient::LoginClient (BaseClientProxy * session) inline
Definition at line 60 of file LoginClient.h.
References accountID, and session.
virtual server::login::LoginClient::~LoginClient () inline virtual
Definition at line 65 of file LoginClient.h.
Member Function Documentation
void server::login::LoginClient::disconnect (bool doLock = true) inline
Definition at line 68 of file LoginClient.h.
References accountID, and session.
uint32 server::login::LoginClient::getAccountID () inline
Definition at line 104 of file LoginClient.h.
References accountID.
Referenced by server::login::LoginPacketHandler::handleDeleteCharacterMessage().
ServiceClient* server::login::LoginClient::getSession () inline
Definition at line 100 of file LoginClient.h.
References session.
Referenced by server::login::LoginSessionMap::add(), server::login::LoginHandler::createConnection(), server::login::LoginServerImplementation::handleMessage(), and server::login::account::AccountManager::loginAccount().
bool server::login::LoginClient::hasAccount () inline
Definition at line 112 of file LoginClient.h.
References accountID.
Referenced by server::login::LoginPacketHandler::handleDeleteCharacterMessage().
void server::login::LoginClient::info (const String & msg, bool doLog = true) inline
Definition at line 96 of file LoginClient.h.
References session.
Referenced by server::login::account::AccountManager::loginAccount().
void server::login::LoginClient::sendErrorMessage (const String & title, const String & text, bool fatal = false) inline
Definition at line 90 of file LoginClient.h.
References sendMessage().
Referenced by server::login::account::AccountManager::loginAccount(), and server::login::account::AccountManager::validateAccountCredentials().
void server::login::LoginClient::sendMessage (Message * msg) inline
Definition at line 86 of file LoginClient.h.
References session.
Referenced by server::login::LoginPacketHandler::handleDeleteCharacterMessage(), server::login::account::AccountManager::loginAccount(), and sendErrorMessage().
void server::login::LoginClient::setAccountID (uint32 account) inline
Definition at line 108 of file LoginClient.h.
References accountID.
Referenced by server::login::account::AccountManager::loginAccount().
Member Data Documentation
uint32 server::login::LoginClient::accountID private
Definition at line 57 of file LoginClient.h.
Referenced by disconnect(), getAccountID(), hasAccount(), LoginClient(), and setAccountID().
Reference<BaseClientProxy*> server::login::LoginClient::session private
Definition at line 56 of file LoginClient.h.
Referenced by disconnect(), getSession(), info(), LoginClient(), and sendMessage().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/LoginClient.h