Core3: server::zone::objects::mission::SurveyMissionObjectiveImplementation Class Reference
server::zone::objects::mission::SurveyMissionObjectiveImplementation Class Reference
#include <SurveyMissionObjective.h>
Public Member Functions
SurveyMissionObjectiveImplementation (MissionObject *mission)
SurveyMissionObjectiveImplementation (DummyConstructorParameter *param)
void finalize ()
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void setSpawnFamily (String &spf)
void setEfficiency (unsigned int eff)
Vector3 getEndPosition ()
operator const SurveyMissionObjective * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
MissionObjectiveImplementation (MissionObject *parent)
MissionObjectiveImplementation (DummyConstructorParameter *param)
virtual void destroyObjectFromDatabase ()
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
virtual void deactivate ()
virtual void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
operator const MissionObjective * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< SurveyMissionObjective * > _this
Public Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
WeakReference< MissionObjective * > _this
Protected Member Functions
virtual ~SurveyMissionObjectiveImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
virtual ~MissionObjectiveImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
String spawnFamily
unsigned int efficiency
Protected Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
ManagedWeakReference
< MissionObject * > mission
unsigned int objectiveType
Time missionStartTime
Reference
< FailMissionAfterCertainTimeTask * > failTask
unsigned long long timeRemaining
bool activated
Friends
class SurveyMissionObjective
Detailed Description
Definition at line 130 of file SurveyMissionObjective.h.
Constructor & Destructor Documentation
SurveyMissionObjectiveImplementation::SurveyMissionObjectiveImplementation (MissionObject * mission)
Definition at line 298 of file SurveyMissionObjective.cpp.
References _initializeImplementation(), and efficiency.
SurveyMissionObjectiveImplementation::SurveyMissionObjectiveImplementation (DummyConstructorParameter * param)
Definition at line 162 of file SurveyMissionObjective.cpp.
References _initializeImplementation().
SurveyMissionObjectiveImplementation::~SurveyMissionObjectiveImplementation () protected virtual
Definition at line 167 of file SurveyMissionObjective.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * SurveyMissionObjectiveImplementation::_getStub ()
Definition at line 185 of file SurveyMissionObjective.cpp.
References _this.
void SurveyMissionObjectiveImplementation::_initializeImplementation () protected
Definition at line 172 of file SurveyMissionObjective.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SurveyMissionObjectiveImplementation().
void SurveyMissionObjectiveImplementation::_serializationHelperMethod () protected
Definition at line 221 of file SurveyMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void SurveyMissionObjectiveImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 180 of file SurveyMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_setStub(), and _this.
Referenced by server::zone::objects::mission::SurveyMissionObjective::SurveyMissionObjective().
void SurveyMissionObjectiveImplementation::abort () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 34 of file SurveyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::abort(), server::zone::objects::mission::MissionObjectiveImplementation::dropObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::hasObservers(), and ObserverEventType::SURVEY.
Referenced by server::zone::objects::mission::SurveyMissionObjective::abort().
void SurveyMissionObjectiveImplementation::activate () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 18 of file SurveyMissionObjectiveImplementation.cpp.
References _this, server::zone::objects::mission::MissionObjectiveImplementation::activate(), server::zone::objects::mission::MissionObjectiveImplementation::addObserver(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::mission::MissionObjectiveImplementation::hasObservers(), and ObserverEventType::SURVEY.
Referenced by server::zone::objects::mission::SurveyMissionObjective::activate().
void SurveyMissionObjectiveImplementation::complete () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 50 of file SurveyMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::complete().
Referenced by server::zone::objects::mission::SurveyMissionObjective::complete(), and notifyObserverEvent().
void SurveyMissionObjectiveImplementation::finalize ()
Definition at line 306 of file SurveyMissionObjective.cpp.
Referenced by ~SurveyMissionObjectiveImplementation().
Vector3 SurveyMissionObjectiveImplementation::getEndPosition () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 326 of file SurveyMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner().
Referenced by server::zone::objects::mission::SurveyMissionObjective::getEndPosition().
void SurveyMissionObjectiveImplementation::initializeTransientMembers () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 309 of file SurveyMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::initializeTransientMembers().
Referenced by server::zone::objects::mission::SurveyMissionObjective::initializeTransientMembers(), and readObject().
void SurveyMissionObjectiveImplementation::lock (bool doLock = true) protected
Definition at line 193 of file SurveyMissionObjective.cpp.
References _this.
void SurveyMissionObjectiveImplementation::lock (ManagedObject * obj) protected
Definition at line 197 of file SurveyMissionObjective.cpp.
References _this.
int SurveyMissionObjectiveImplementation::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 54 of file SurveyMissionObjectiveImplementation.cpp.
References complete(), server::zone::objects::mission::MissionObjectiveImplementation::dropObserver(), efficiency, server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::objects::resource::ResourceSpawn::getSurveyMissionSpawnFamilyName(), server::zone::objects::mission::MissionObjectiveImplementation::mission, server::chat::StringIdChatParameter::setDF(), server::chat::StringIdChatParameter::setDI(), spawnFamily, and ObserverEventType::SURVEY.
Referenced by server::zone::objects::mission::SurveyMissionObjective::notifyObserverEvent().
SurveyMissionObjectiveImplementation::operator const SurveyMissionObjective * ()
Definition at line 189 of file SurveyMissionObjective.cpp.
void SurveyMissionObjectiveImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 228 of file SurveyMissionObjective.cpp.
References initializeTransientMembers(), and readObjectMember().
bool SurveyMissionObjectiveImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 247 of file SurveyMissionObjective.cpp.
References efficiency, server::zone::objects::mission::MissionObjectiveImplementation::readObjectMember(), and spawnFamily.
Referenced by readObject().
void SurveyMissionObjectiveImplementation::rlock (bool doLock = true) protected
Definition at line 201 of file SurveyMissionObjective.cpp.
References _this.
void SurveyMissionObjectiveImplementation::runlock (bool doLock = true) protected
Definition at line 217 of file SurveyMissionObjective.cpp.
References _this.
void SurveyMissionObjectiveImplementation::setEfficiency (unsigned int eff)
Definition at line 321 of file SurveyMissionObjective.cpp.
References efficiency.
Referenced by server::zone::objects::mission::SurveyMissionObjective::setEfficiency().
void SurveyMissionObjectiveImplementation::setSpawnFamily (String & spf)
Definition at line 316 of file SurveyMissionObjective.cpp.
References spawnFamily.
Referenced by server::zone::objects::mission::SurveyMissionObjective::setSpawnFamily().
void SurveyMissionObjectiveImplementation::unlock (bool doLock = true) protected
Definition at line 213 of file SurveyMissionObjective.cpp.
References _this.
void SurveyMissionObjectiveImplementation::wlock (bool doLock = true) protected
Definition at line 205 of file SurveyMissionObjective.cpp.
References _this.
void SurveyMissionObjectiveImplementation::wlock (ManagedObject * obj) protected
Definition at line 209 of file SurveyMissionObjective.cpp.
References _this.
void SurveyMissionObjectiveImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 265 of file SurveyMissionObjective.cpp.
References writeObjectMembers().
int SurveyMissionObjectiveImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 272 of file SurveyMissionObjective.cpp.
References efficiency, spawnFamily, and server::zone::objects::mission::MissionObjectiveImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class SurveyMissionObjective friend
Definition at line 191 of file SurveyMissionObjective.h.
Member Data Documentation
WeakReference<SurveyMissionObjective*> server::zone::objects::mission::SurveyMissionObjectiveImplementation::_this
Definition at line 159 of file SurveyMissionObjective.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), activate(), lock(), rlock(), runlock(), unlock(), and wlock().
unsigned int server::zone::objects::mission::SurveyMissionObjectiveImplementation::efficiency protected
Definition at line 134 of file SurveyMissionObjective.h.
Referenced by notifyObserverEvent(), readObjectMember(), setEfficiency(), SurveyMissionObjectiveImplementation(), and writeObjectMembers().
String server::zone::objects::mission::SurveyMissionObjectiveImplementation::spawnFamily protected
Definition at line 132 of file SurveyMissionObjective.h.
Referenced by notifyObserverEvent(), readObjectMember(), setSpawnFamily(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/SurveyMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/SurveyMissionObjective.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/SurveyMissionObjectiveImplementation.cpp