Core3: server::zone::objects::creature::CreatureAdapter Class Reference
server::zone::objects::creature::CreatureAdapter Class Reference
#include <Creature.h>
Public Member Functions
CreatureAdapter (Creature *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
bool isCreature ()
short getDnaState ()
short getDnaSampleCount ()
void incDnaSampleCount ()
bool isCamouflaged (CreatureObject *target)
void runAway (CreatureObject *target)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void scheduleDespawn ()
bool hasOrganics ()
bool hasMilk ()
bool hasDNA ()
bool canHarvestMe (CreatureObject *player)
bool hasSkillToHarvestMe (CreatureObject *player)
bool canMilkMe (CreatureObject *player)
bool canCollectDna (CreatureObject *player)
bool hasSkillToSampleMe (CreatureObject *player)
void addAlreadyHarvested (CreatureObject *player)
void setMilkState (short milkState)
void setDnaState (short dnaState)
void notifyDespawn (Zone *zone)
bool isBaby ()
float getTame ()
String getMeatType ()
String getBoneType ()
String getHideType ()
String getMilkType ()
float getMilk ()
float getHideMax ()
float getBoneMax ()
float getMeatMax ()
Public Member Functions inherited from server::zone::objects::creature::AiAgentAdapter
AiAgentAdapter (AiAgent *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeTransientMembers ()
void finalize ()
void activateRecovery ()
void activateMovementEvent ()
void activateWaitEvent ()
void activateAwarenessEvent (CreatureObject *target)
bool tryRetreat ()
void doRecovery ()
void doAttack ()
void doMovement ()
void setLevel (int lvl)
void sendBaselinesTo (SceneObject *player)
int calculateAttackMinDamage (int level)
int calculateAttackMaxDamage (int level)
float calculateAttackSpeed (int level)
bool isCamouflaged (CreatureObject *target)
bool isScentMasked (CreatureObject *target)
bool isConcealed (CreatureObject *target)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
void checkNewAngle ()
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void setNextPosition (float x, float z, float y, SceneObject *cell)
void notifyPositionUpdate (QuadTreeEntry *entry)
void clearPatrolPoints ()
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient)
void sendConversationStartTo (SceneObject *player)
void sendDefaultConversationTo (SceneObject *player)
void selectConversationOption (int option, SceneObject *obj)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
int notifyConverseObservers (CreatureObject *converser)
int notifyAttack (Observable *observable)
int notifyCallForHelp (Observable *observable, ManagedObject *arg1)
void destroyObjectFromWorld (bool sendSelfDestroy)
void activatePostureRecovery ()
void queueDizzyFallEvent ()
void clearCombatState (bool clearDefenders)
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
void setDespawnOnNoPlayerInRange (bool val)
void notifyDespawn (Zone *zone)
void scheduleDespawn ()
void scheduleDespawn (int timeToDespawn)
void respawn (Zone *zone, int level)
void setHomeLocation (float x, float z, float y, SceneObject *cell)
void setRespawnTimer (float resp)
void setRandomRespawn (bool resp)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
void setOblivious ()
void setWatchObject (SceneObject *obj)
void setStalkObject (SceneObject *obj)
void setFollowObject (SceneObject *obj)
void setTargetObject (SceneObject *obj)
SceneObject * getFollowObject ()
void selectWeapon ()
bool validateStateAttack (CreatureObject *target, String &args)
bool isRetreating ()
bool isFleeing ()
void clearDespawnEvent ()
float getKinetic ()
float getEnergy ()
float getElectricity ()
float getStun ()
float getBlast ()
float getHeat ()
float getCold ()
float getAcid ()
float getLightSaber ()
bool isStalker ()
bool isKiller ()
unsigned int getFerocity ()
unsigned int getArmor ()
bool getDespawnOnNoPlayerInRange ()
int getNumberOfPlayersInRange ()
String getFactionString ()
String getSocialGroup ()
float getChanceHit ()
int getDamageMin ()
int getDamageMax ()
int getBaseXp ()
unsigned int getDiet ()
float getRespawnTimer ()
bool getRandomRespawn ()
bool isAiAgent ()
bool hasLoot ()
void setShowNextPosition (bool val)
bool isEventMob ()
String getPvPFaction ()
Public Member Functions inherited from server::zone::objects::creature::CreatureObjectAdapter
CreatureObjectAdapter (CreatureObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeMembers ()
void finalize ()
void createChildObjects ()
void initializeTransientMembers ()
void clearQueueAction (unsigned int actioncntr, float timer, unsigned int tab1, unsigned int tab2)
void sendBaselinesTo (SceneObject *player)
void sendToOwner (bool doClose)
void sendTo (SceneObject *player, bool doClose)
void sendSystemMessage (const String &message)
void playMusicMessage (const String &file)
void sendNewbieTutorialRequest (const String &request)
void sendNewbieTutorialEnableHudElement (const String &ui, bool enable)
void sendOpenHolocronToPageMessage ()
void sendSystemMessage (UnicodeString &message)
void sendSlottedObjectsTo (SceneObject *player)
void setCombatState ()
void clearCombatState (bool clearDefenders)
void setPosture (int newPosture, bool notifyClient)
float calculateSpeed ()
void updateLocomotion ()
void setHeight (float heigh, bool notifyClient)
void setAccelerationMultiplierBase (float newMultiplierBase, bool notifyClient)
void setAccelerationMultiplierMod (float newMultiplierMod, bool notifyClient)
void setSpeedMultiplierBase (float newMultiplierBase, bool notifyClient)
void setSpeedMultiplierMod (float newMultiplierMod, bool notifyClient)
void setTurnScale (float newMultiplierMod, bool notifyClient)
void setRunSpeed (float newSpeed, bool notifyClient)
void setCurrentSpeed (float newSpeed)
void setHAM (int type, int value, bool notifyClient)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient)
bool hasDamage (int attribute)
int healDamage (TangibleObject *healer, int damageType, int damage, bool notifyClient, bool notifyObservers)
int healWound (TangibleObject *healer, int damageType, int damage, bool notifyClient, bool notifyObservers)
void setBaseHAM (int type, int value, bool notifyClient)
void setWounds (int type, int value, bool notifyClient)
int addWounds (int type, int value, bool notifyClient)
void setMaxHAM (int type, int value, bool notifyClient)
void addMaxHAM (int type, int value, bool notifyClient)
void setEncumbrance (int type, int value, bool notifyClient)
void addEncumbrance (int type, int value, bool notifyClient)
void setWeapon (WeaponObject *weao, bool notifyClient)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void setInstrumentID (int instrumentid, bool notifyClient)
void setListenToID (unsigned long long id, bool notifyClient)
void setPerformanceCounter (int counter, bool notifyClient)
void setPerformanceAnimation (const String &animation, bool notifyClient)
void setShockWounds (int newShock, bool notifyClient)
void addShockWounds (int shockToAdd, bool notiyClient)
void setTargetID (unsigned long long targetID, bool notifyClient)
void setBankCredits (int credits, bool notifyClient)
void addBuff (Buff *buff)
bool removeBuff (unsigned int buffcrc)
void removeBuff (Buff *buff)
bool removeStateBuff (unsigned long long state)
void clearBuffs (bool updateclient)
void addWearableObject (TangibleObject *object, bool notifyClient)
void removeWearableObject (TangibleObject *object, bool notifyClient)
void sendBuffsTo (CreatureObject *creature)
Buff * getBuff (unsigned int buffcrc)
long long getSkillModFromBuffs (const String &skillMod)
int addDotState (unsigned long long dotType, unsigned long long objectID, unsigned int strength, byte type, unsigned int duration, float potency, unsigned int defense, int secondaryStrength)
bool healDot (unsigned long long dotType, int reduction)
void clearDots ()
bool hasBuff (unsigned int buffcrc)
void notifySelfPositionUpdate ()
void notifyPostureChange (int newPosture)
void setLevel (int level)
void updateToDatabaseAllObjects (bool startTask)
bool isResuscitable ()
void addBankCredits (int credits, bool notifyClient)
void addCashCredits (int credits, bool notifyClient)
void subtractBankCredits (int credits)
void subtractCashCredits (int credits)
bool verifyCashCredits (int credits)
bool verifyBankCredits (int credits)
bool isDancing ()
bool isPlayingMusic ()
void stopEntertaining ()
bool isEntertaining ()
void setCashCredits (int credits, bool notifyClient)
void setTerrainNegotiation (float value, bool notifyClient)
void addSkill (const String &skill, bool notifyClient)
void removeSkill (const String &skill, bool notifyClient)
void addSkillMod (const int modType, const String &skillMod, int value, bool notifyClient)
void removeSkillMod (const int modType, const String &skillMod, int value, bool notifyClient)
void removeAllSkillModsOfType (const int modType, bool notifyClient)
void updateGroupInviterID (unsigned long long id, bool notifyClient)
void updateGroup (GroupObject *group, bool notifyClient)
void enqueueCommand (unsigned int actionCRC, unsigned int actionCount, unsigned long long targetID, const UnicodeString &arguments, int priority)
void setMood (byte moodID, bool notifyClient)
void setMoodString (const String &animation, bool notifyClient)
void deleteQueueAction (unsigned int actionCount)
bool setState (unsigned long long state, bool notifyClient)
bool clearState (unsigned long long state, bool notifyClient)
void setControlDevice (ControlDevice *device)
void setCreatureLink (CreatureObject *object, bool notifyClient)
void executeObjectControllerAction (unsigned int actionCRC)
void executeObjectControllerAction (unsigned int actionCRC, unsigned long long targetID, const UnicodeString &args)
bool isAttackableBy (CreatureObject *object)
bool isAttackableBy (TangibleObject *attacker)
bool isHealableBy (CreatureObject *object)
bool isInBountyMission (CreatureObject *bountyHunter, CreatureObject *target)
void sendConversationStartTo (SceneObject *player)
void selectConversationOption (int option, SceneObject *obj)
void sendMessage (BasePacket *msg)
void sendExecuteConsoleCommand (const String &command)
bool isAggressiveTo (CreatureObject *object)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
int notifyObjectKillObservers (TangibleObject *killer)
void notifyLoadFromDatabase ()
void setFactionRank (int rank, bool notifyClient)
String getFirstName ()
String getLastName ()
bool isOnline ()
bool canTreatInjuries ()
bool canTreatStates ()
bool canTreatWounds ()
bool canTreatConditions ()
Reference< PlayerObject * > getPlayerObject ()
AiActor * getActorObject ()
bool isListening ()
bool isWatching ()
void setClient (ZoneClientSession *cli)
void dismount ()
float calculateBFRatio ()
void setDizziedState (int durationSeconds)
void setRalliedState (int durationSeconds)
void setAimingState (int durationSeconds)
void setCoverState (int durationSeconds)
void setBerserkedState (unsigned int duration)
void setStunnedState (int durationSeconds)
void setBlindedState (int durationSeconds)
void setIntimidatedState (unsigned int mod, int durationSeconds)
void setSnaredState (int durationSeconds)
void setRootedState (int durationSeconds)
bool setNextAttackDelay (unsigned int mod, int del)
void setMeditateState ()
void activateHAMRegeneration ()
void activatePassiveWoundRegeneration ()
void activateStateRecovery ()
void updateTimeOfDeath ()
bool hasAttackDelay ()
void removeAttackDelay ()
bool hasSpice ()
void updateLastSuccessfulCombatAction ()
void updateKnockdownRecovery ()
void queueDizzyFallEvent ()
void updateLastKnockdown ()
bool checkKnockdownRecovery ()
bool checkLastKnockdown ()
void updatePostureDownRecovery ()
void updatePostureUpRecovery ()
bool checkPostureDownRecovery ()
unsigned long long getScreenPlayState (const String &screenPlay)
void setScreenPlayState (const String &screenPlay, unsigned long long state)
bool checkPostureUpRecovery ()
void updateCooldownTimer (const String &coooldownTimer, unsigned int miliSecondsToAdd)
bool checkCooldownRecovery (const String &cooldown)
void addCooldown (const String &name, unsigned int miliseconds)
void doAnimation (const String &animation)
void doCombatAnimation (CreatureObject *defender, unsigned int animationCRC, byte hit, byte trails)
void playEffect (const String &file, const String &aux)
void playEffect (const String &file)
void activateQueueAction ()
void activateImmediateAction ()
UnicodeString getCreatureName ()
bool isGrouped ()
int getBankCredits ()
int getCashCredits ()
int getBaseHAM (int idx)
int getWounds (int idx)
int getHAM (int idx)
int getMaxHAM (int idx)
int getEncumbrance (int idx)
byte getPosture ()
byte getLocomotion ()
byte getFactionRank ()
ManagedWeakReference
< CreatureObject * > getLinkedCreature ()
unsigned long long getCreatureLinkID ()
float getShockWounds ()
unsigned long long getWatchToID ()
unsigned long long getStateBitmask ()
bool hasState (unsigned long long state)
bool hasStates ()
unsigned long long getListenID ()
float getAccelerationMultiplierBase ()
float getAccelerationMultiplierMod ()
float getSpeedMultiplierBase ()
float getSpeedMultiplierMod ()
float getCurrentSpeed ()
float getRunSpeed ()
float getWalkSpeed ()
float getTurnScale ()
float getTerrainNegotiation ()
float getRunAcceleration ()
float getWalkAcceleration ()
String getPerformanceAnimation ()
String getMoodString ()
unsigned long long getWeaponID ()
Reference< WeaponObject * > getWeapon ()
Reference< GuildObject * > getGuildObject ()
int getGuildID ()
bool isInGuild ()
void setGuildObject (GuildObject *guildobj)
unsigned long long getGroupID ()
unsigned long long getGroupInviterID ()
GroupObject * getGroup ()
unsigned long long getGroupInviteCounter ()
unsigned long long getTargetID ()
byte getMoodID ()
float getSlopeModPercent ()
int getPerformanceCounter ()
int getInstrumentID ()
byte getFrozen ()
float getHeight ()
int getSpecies ()
String getSpeciesName ()
int getGender ()
int getSkillMod (const String &skillmod)
bool hasSkill (const String &skill)
void setWatchToID (unsigned long long id)
bool isCreatureObject ()
bool isNextActionPast ()
bool isTrainerCreature ()
bool isSwimming ()
ZoneClientSession * getClient ()
bool isRidingMount ()
ManagedWeakReference
< ControlDevice * > getControlDevice ()
float getSwimHeight ()
bool isIncapacitated ()
bool isDead ()
bool isKnockedDown ()
bool isKneeling ()
bool isProne ()
bool isStanding ()
bool isSitting ()
bool isSkillAnimating ()
bool isRallied ()
bool isInCombat ()
bool isDizzied ()
bool isBerserked ()
bool isStunned ()
bool isBlinded ()
bool isIntimidated ()
bool isSnared ()
bool isImmobilized ()
bool isRooted ()
bool isFrozen ()
bool isDiseased ()
bool isPoisoned ()
bool isBleeding ()
bool isOnFire ()
bool isMounted ()
bool isRidingCreature ()
bool isPeaced ()
bool isMeditating ()
bool isAiming ()
bool isInCover ()
bool isRunning ()
bool isNonPlayerCreatureObject ()
bool isCreature ()
bool isPlayerCreature ()
bool isAiActor ()
bool isInformantCreature ()
CampSiteActiveArea * getCurrentCamp ()
byte getCurrentWeather ()
void setCurrentWeather (byte value)
byte getCurrentWind ()
void setCurrentWind (byte value)
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void destroyObjectFromWorld (bool sendSelfDestroy)
bool isInvisible ()
void setInvisible (bool invis)
float calculateCostAdjustment (byte stat, float baseCost)
void updateSpeedAndAccelerationMods ()
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectAdapter
TangibleObjectAdapter (TangibleObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void initializeMembers ()
void applySkillModsTo (CreatureObject *creature, bool doCheck)
void removeSkillModsFrom (CreatureObject *creature)
void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient)
void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient)
void removeAllSkillModsOfType (const int skillType, bool notifyClient)
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void sendBaselinesTo (SceneObject *player)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void setDefender (SceneObject *defender)
void addDefender (SceneObject *defender)
void removeDefender (SceneObject *defender)
void removeDefenders ()
void setCombatState ()
void setUseCount (unsigned int newUseCount, bool notifyClient)
void setCountdownTimer (unsigned int newCount, bool notifyClient)
void decreaseUseCount ()
void clearCombatState (bool clearDefenders)
bool hasDefender (SceneObject *defender)
bool isAttackableBy (CreatureObject *object)
bool isAggressiveTo (CreatureObject *object)
bool isHealableBy (CreatureObject *object)
void sendPvpStatusTo (CreatureObject *player)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient)
int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient)
int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient)
void setConditionDamage (float condDamage, bool notifyClient)
void setCustomizationVariable (byte type, short value, bool notifyClient)
void setCustomizationVariable (const String &type, short value, bool notifyClient)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient)
int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
bool isKiller ()
bool isTicketCollector ()
bool isTicketObject ()
int getUseCount ()
int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient)
void setCraftersName (String &name)
String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
int getJunkDealerNeeded ()
void setJunkValue (int jValue)
int getJunkValue ()
void setSerialNumber (const String &serial)
void setLevel (int lev)
String getSerialNumber ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
String repairAttempt (int repairChance)
bool isBroken ()
float getHitChance ()
void broadcastPvpStatusBitmask ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectAdapter
SceneObjectAdapter (SceneObject *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void finalize ()
void initializePrivateData ()
void createComponents ()
void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
bool transferObject (SceneObject *object, int containmentType, bool notifyClient, bool allowOverflow)
bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient)
void destroyObjectFromWorld (bool sendSelfDestroy)
int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void synchronizedUIListen (SceneObject *player, int value)
void synchronizedUIStopListen (SceneObject *player, int value)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects)
void destroyObjectFromDatabase (bool destroyContainedObjects)
int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType)
void sendTo (SceneObject *player, bool doClose)
void sendWithoutParentTo (SceneObject *player)
void sendWithoutContainerObjectsTo (SceneObject *player)
void sendDestroyTo (SceneObject *player)
void sendBaselinesTo (SceneObject *player)
void sendContainerObjectsTo (SceneObject *player)
void sendSlottedObjectsTo (SceneObject *player)
void sendToOwner (bool doClose)
void sendAttributeListTo (CreatureObject *object)
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
void openContainerTo (CreatureObject *player)
void closeContainerTo (CreatureObject *player, bool notify)
void notifyInsertToZone (Zone *zone)
void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyRemoveFromZone ()
void updateZone (bool lightUpdate, bool sendPackets)
void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
unsigned long long getParentID ()
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
void updateVehiclePosition (bool sendPackets)
int notifyObjectInserted (SceneObject *object)
int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
float getWorldPositionX ()
float getWorldPositionY ()
float getWorldPositionZ ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
UnicodeString getCustomObjectName ()
String getLoggingName ()
bool isPlayerCreature ()
bool isDecoration ()
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
bool isActiveArea ()
bool isRegion ()
bool isCreatureObject ()
bool isAiAgent ()
bool isJunkDealer ()
bool isShipObject ()
bool isVehicleObject ()
bool isBuildingObject ()
bool isCloningBuildingObject ()
bool isGarage ()
bool isWeaponObject ()
bool isWearableObject ()
bool isWearableContainerObject ()
bool isArmorObject ()
bool isRobeObject ()
bool isLightsaberCrystalObject ()
bool isFireworkObject ()
bool isPsgArmorObject ()
bool isCellObject ()
bool isTangibleObject ()
bool isResourceContainer ()
bool isResourceSpawn ()
bool isComponent ()
bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
bool isInstallationObject ()
bool isHarvesterObject ()
bool isGeneratorObject ()
bool isCityTerminal ()
bool isCityVoteTerminal ()
bool isFactory ()
bool isFactoryCrate ()
bool isFishingPoleObject ()
bool isDeedObject ()
bool isVehicleDeedObject ()
bool isBuildingDeed ()
bool isSignObject ()
bool isInstallationDeed ()
bool isCraftingTool ()
bool isCraftingStation ()
bool isManufactureSchematic ()
bool isStructureObject ()
bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
bool isCampStructure ()
bool isRecycleToolObject ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZone (Zone *zone)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
unsigned int getPlanetCRC ()
bool isStaticObject ()
bool isContainerObject ()
bool isTerminal ()
bool isGroupObject ()
bool isGuildObject ()
bool isControlDevice ()
bool isMissionTerminal ()
bool isMissionObject ()
bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
bool containsChildObject (SceneObject *obj)
void createChildObjects ()
void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
Detailed Description
Definition at line 345 of file Creature.h.
Constructor & Destructor Documentation
CreatureAdapter::CreatureAdapter (Creature * impl)
Definition at line 777 of file Creature.cpp.
Member Function Documentation
void CreatureAdapter::addAlreadyHarvested (CreatureObject * player)
Definition at line 1021 of file Creature.cpp.
Referenced by invokeMethod().
bool CreatureAdapter::canCollectDna (CreatureObject * player)
Definition at line 1013 of file Creature.cpp.
Referenced by invokeMethod().
bool CreatureAdapter::canHarvestMe (CreatureObject * player)
Definition at line 1001 of file Creature.cpp.
Referenced by invokeMethod().
bool CreatureAdapter::canMilkMe (CreatureObject * player)
Definition at line 1009 of file Creature.cpp.
Referenced by invokeMethod().
void CreatureAdapter::fillAttributeList (AttributeListMessage * msg, CreatureObject * object)
Definition at line 981 of file Creature.cpp.
Referenced by invokeMethod().
float CreatureAdapter::getBoneMax ()
Definition at line 1069 of file Creature.cpp.
Referenced by invokeMethod().
String CreatureAdapter::getBoneType ()
Definition at line 1049 of file Creature.cpp.
Referenced by invokeMethod().
short CreatureAdapter::getDnaSampleCount ()
Definition at line 961 of file Creature.cpp.
Referenced by invokeMethod().
short CreatureAdapter::getDnaState ()
Definition at line 957 of file Creature.cpp.
Referenced by invokeMethod().
float CreatureAdapter::getHideMax ()
Definition at line 1065 of file Creature.cpp.
Referenced by invokeMethod().
String CreatureAdapter::getHideType ()
Definition at line 1053 of file Creature.cpp.
Referenced by invokeMethod().
float CreatureAdapter::getMeatMax ()
Definition at line 1073 of file Creature.cpp.
Referenced by invokeMethod().
String CreatureAdapter::getMeatType ()
Definition at line 1045 of file Creature.cpp.
Referenced by invokeMethod().
float CreatureAdapter::getMilk ()
Definition at line 1061 of file Creature.cpp.
Referenced by invokeMethod().
String CreatureAdapter::getMilkType ()
Definition at line 1057 of file Creature.cpp.
Referenced by invokeMethod().
float CreatureAdapter::getTame ()
Definition at line 1041 of file Creature.cpp.
Referenced by invokeMethod().
int CreatureAdapter::handleObjectMenuSelect (CreatureObject * player, byte selectedID)
Definition at line 977 of file Creature.cpp.
Referenced by invokeMethod().
bool CreatureAdapter::hasDNA ()
Definition at line 997 of file Creature.cpp.
Referenced by invokeMethod().
bool CreatureAdapter::hasMilk ()
Definition at line 993 of file Creature.cpp.
Referenced by invokeMethod().
bool CreatureAdapter::hasOrganics ()
Definition at line 989 of file Creature.cpp.
Referenced by invokeMethod().
bool CreatureAdapter::hasSkillToHarvestMe (CreatureObject * player)
Definition at line 1005 of file Creature.cpp.
Referenced by invokeMethod().
bool CreatureAdapter::hasSkillToSampleMe (CreatureObject * player)
Definition at line 1017 of file Creature.cpp.
Referenced by invokeMethod().
void CreatureAdapter::incDnaSampleCount ()
Definition at line 965 of file Creature.cpp.
Referenced by invokeMethod().
void CreatureAdapter::initializeTransientMembers ()
Definition at line 949 of file Creature.cpp.
Referenced by invokeMethod().
void CreatureAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 780 of file Creature.cpp.
References addAlreadyHarvested(), canCollectDna(), canHarvestMe(), canMilkMe(), fillAttributeList(), getBoneMax(), getBoneType(), getDnaSampleCount(), getDnaState(), getHideMax(), getHideType(), getMeatMax(), getMeatType(), getMilk(), getMilkType(), getTame(), handleObjectMenuSelect(), hasDNA(), hasMilk(), hasOrganics(), hasSkillToHarvestMe(), hasSkillToSampleMe(), incDnaSampleCount(), initializeTransientMembers(), isBaby(), isCamouflaged(), isCreature(), notifyDespawn(), RPC_ADDALREADYHARVESTED__CREATUREOBJECT_, RPC_CANCOLLECTDNA__CREATUREOBJECT_, RPC_CANHARVESTME__CREATUREOBJECT_, RPC_CANMILKME__CREATUREOBJECT_, RPC_FILLATTRIBUTELIST__ATTRIBUTELISTMESSAGE_CREATUREOBJECT_, RPC_GETBONEMAX__, RPC_GETBONETYPE__, RPC_GETDNASAMPLECOUNT__, RPC_GETDNASTATE__, RPC_GETHIDEMAX__, RPC_GETHIDETYPE__, RPC_GETMEATMAX__, RPC_GETMEATTYPE__, RPC_GETMILK__, RPC_GETMILKTYPE__, RPC_GETTAME__, RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_, RPC_HASDNA__, RPC_HASMILK__, RPC_HASORGANICS__, RPC_HASSKILLTOHARVESTME__CREATUREOBJECT_, RPC_HASSKILLTOSAMPLEME__CREATUREOBJECT_, RPC_INCDNASAMPLECOUNT__, RPC_INITIALIZETRANSIENTMEMBERS__, RPC_ISBABY__, RPC_ISCAMOUFLAGED__CREATUREOBJECT_, RPC_ISCREATURE__, RPC_NOTIFYDESPAWN__ZONE_, RPC_RUNAWAY__CREATUREOBJECT_, RPC_SCHEDULEDESPAWN__, RPC_SETDNASTATE__SHORT_, RPC_SETMILKSTATE__SHORT_, runAway(), scheduleDespawn(), setDnaState(), and setMilkState().
bool CreatureAdapter::isBaby ()
Definition at line 1037 of file Creature.cpp.
Referenced by invokeMethod().
bool CreatureAdapter::isCamouflaged (CreatureObject * target)
Definition at line 969 of file Creature.cpp.
Referenced by invokeMethod().
bool CreatureAdapter::isCreature ()
Definition at line 953 of file Creature.cpp.
Referenced by invokeMethod().
void CreatureAdapter::notifyDespawn (Zone * zone)
Definition at line 1033 of file Creature.cpp.
Referenced by invokeMethod().
void CreatureAdapter::runAway (CreatureObject * target)
Definition at line 973 of file Creature.cpp.
Referenced by invokeMethod().
void CreatureAdapter::scheduleDespawn ()
Definition at line 985 of file Creature.cpp.
Referenced by invokeMethod().
void CreatureAdapter::setDnaState (short dnaState)
Definition at line 1029 of file Creature.cpp.
Referenced by invokeMethod().
void CreatureAdapter::setMilkState (short milkState)
Definition at line 1025 of file Creature.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/Creature.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/Creature.cpp