Core3: server::chat::room::ChatRoom Class Reference
server::chat::room::ChatRoom Class Reference
#include <ChatRoom.h>
Public Member Functions
ChatRoom ()
void init (ZoneServer *serv, ChatRoom *par, const String &roomName, unsigned int channelID)
void sendTo (CreatureObject *player)
void sendDestroyTo (CreatureObject *player)
void addSubRoom (ChatRoom *channel)
void removeSubRoom (ChatRoom *channel)
ChatRoom * getSubRoom (int i)
ChatRoom * getSubRoom (const String &name)
void addPlayer (CreatureObject *player, bool doLock=true)
void removePlayer (CreatureObject *player, bool doLock=true)
void removePlayer (const String &player)
void broadcastMessage (BaseMessage *msg)
void broadcastMessages (Vector< BaseMessage * > *messages)
bool hasPlayer (CreatureObject *player)
bool hasPlayer (const String &name)
void removeAllPlayers ()
void setPrivate ()
void setPublic ()
bool isPublic ()
bool isPrivate ()
bool isModerated ()
void setModerated (bool moderate)
CreatureObject * getPlayer (int idx)
int getPlayerSize ()
void setName (const String &Name)
String getName ()
String getFullPath ()
String getOwner ()
String getCreator ()
UnicodeString getTitle ()
String getGalaxyName ()
void setOwner (const String &Owner)
void setCreator (const String &Creator)
void setTitle (const String &Title)
void setRoomID (int id)
unsigned int getRoomID ()
int getSubRoomsSize ()
ChatRoom * getParent ()
int compareTo (ChatRoom *obj)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ChatRoom (DummyConstructorParameter *param)
virtual ~ChatRoom ()
Friends
class ChatRoomHelper
Detailed Description
Definition at line 78 of file ChatRoom.h.
Constructor & Destructor Documentation
ChatRoom::ChatRoom ()
Definition at line 21 of file ChatRoom.cpp.
References server::chat::room::ChatRoomImplementation::_setStub().
ChatRoom::ChatRoom (DummyConstructorParameter * param) protected
Definition at line 28 of file ChatRoom.cpp.
ChatRoom::~ChatRoom () protected virtual
Definition at line 32 of file ChatRoom.cpp.
Member Function Documentation
DistributedObjectServant * ChatRoom::_getImplementation ()
Definition at line 565 of file ChatRoom.cpp.
Referenced by addPlayer(), addSubRoom(), broadcastMessage(), broadcastMessages(), compareTo(), getCreator(), getFullPath(), getGalaxyName(), getName(), getOwner(), getParent(), getPlayer(), getPlayerSize(), getRoomID(), getSubRoom(), getSubRoomsSize(), getTitle(), hasPlayer(), init(), isModerated(), isPrivate(), isPublic(), removeAllPlayers(), removePlayer(), removeSubRoom(), sendDestroyTo(), sendTo(), setCreator(), setModerated(), setName(), setOwner(), setPrivate(), setPublic(), setRoomID(), and setTitle().
DistributedObjectServant * ChatRoom::_getImplementationForRead ()
Definition at line 571 of file ChatRoom.cpp.
void ChatRoom::_setImplementation (DistributedObjectServant * servant)
Definition at line 575 of file ChatRoom.cpp.
void ChatRoom::addPlayer (CreatureObject * player, bool doLock = true)
Definition at line 138 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::addPlayer(), and RPC_ADDPLAYER__CREATUREOBJECT_BOOL_.
void ChatRoom::addSubRoom (ChatRoom * channel)
Definition at line 82 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::addSubRoom(), and RPC_ADDSUBROOM__CHATROOM_.
Referenced by server::chat::ChatManagerImplementation::createGroupRoom(), server::chat::ChatManagerImplementation::createRoomByFullPath(), server::chat::ChatManagerImplementation::initiatePlanetRooms(), and server::chat::ChatManagerImplementation::initiateRooms().
void ChatRoom::broadcastMessage (BaseMessage * msg)
Definition at line 182 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::broadcastMessage(), and RPC_BROADCASTMESSAGE__BASEMESSAGE_.
Referenced by server::chat::ChatManagerImplementation::destroyRoom(), and server::chat::ChatManagerImplementation::handleChatRoomMessage().
void ChatRoom::broadcastMessages (Vector< BaseMessage * > * messages)
Definition at line 196 of file ChatRoom.cpp.
References _getImplementation(), and server::chat::room::ChatRoomImplementation::broadcastMessages().
int ChatRoom::compareTo (ChatRoom * obj)
Definition at line 551 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::compareTo(), and RPC_COMPARETO__CHATROOM_.
String ChatRoom::getCreator ()
Definition at line 411 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getCreator(), and RPC_GETCREATOR__.
Referenced by server::zone::packets::chat::ChatRoomList::addChannel(), and ChatOnCreateRoom::ChatOnCreateRoom().
String ChatRoom::getFullPath ()
Definition at line 381 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getFullPath(), and RPC_GETFULLPATH__.
Referenced by server::zone::packets::chat::ChatRoomList::addChannel(), ChatOnCreateRoom::ChatOnCreateRoom(), and server::chat::room::ChatRoomImplementation::init().
String ChatRoom::getGalaxyName ()
Definition at line 441 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getGalaxyName(), and RPC_GETGALAXYNAME__.
Referenced by server::zone::packets::chat::ChatRoomList::addChannel(), ChatOnCreateRoom::ChatOnCreateRoom(), and ChatOnLeaveRoom::ChatOnLeaveRoom().
String ChatRoom::getName ()
Definition at line 366 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getName(), and RPC_GETNAME__.
Referenced by server::chat::room::ChatRoomImplementation::addSubRoom(), and server::chat::room::ChatRoomImplementation::removeSubRoom().
String ChatRoom::getOwner ()
Definition at line 396 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getOwner(), and RPC_GETOWNER__.
Referenced by server::zone::packets::chat::ChatRoomList::addChannel().
ChatRoom * ChatRoom::getParent ()
Definition at line 538 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getParent(), and RPC_GETPARENT__.
Referenced by server::chat::ChatManagerImplementation::destroyRoom(), server::zone::objects::group::GroupObjectImplementation::disband(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), server::chat::room::ChatRoomAdapter::getParent(), and GroupManager::leaveGroup().
CreatureObject * ChatRoom::getPlayer (int idx)
Definition at line 325 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getPlayer(), and RPC_GETPLAYER__INT_.
int ChatRoom::getPlayerSize ()
Definition at line 339 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getPlayerSize(), and RPC_GETPLAYERSIZE__.
unsigned int ChatRoom::getRoomID ()
Definition at line 512 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getRoomID(), and RPC_GETROOMID__.
Referenced by server::zone::packets::chat::ChatRoomList::addChannel(), server::chat::ChatManagerImplementation::addRoom(), ChatOnCreateRoom::ChatOnCreateRoom(), ChatOnLeaveRoom::ChatOnLeaveRoom(), server::chat::room::ChatRoomImplementation::compareTo(), server::chat::ChatManagerImplementation::destroyRoom(), and server::chat::ChatManagerImplementation::removeRoom().
ChatRoom * ChatRoom::getSubRoom (int i)
Definition at line 110 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getSubRoom(), and RPC_GETSUBROOM__INT_.
Referenced by server::chat::ChatManagerImplementation::createRoomByFullPath(), server::chat::ChatManagerImplementation::getChatRoomByGamePath(), server::chat::room::ChatRoomAdapter::getSubRoom(), and server::chat::ChatManagerImplementation::populateRoomListMessage().
ChatRoom * ChatRoom::getSubRoom (const String & name)
Definition at line 124 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getSubRoom(), and RPC_GETSUBROOM__STRING_.
int ChatRoom::getSubRoomsSize ()
Definition at line 525 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getSubRoomsSize(), and RPC_GETSUBROOMSSIZE__.
Referenced by server::chat::ChatManagerImplementation::populateRoomListMessage().
UnicodeString ChatRoom::getTitle ()
Definition at line 426 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::getTitle(), and RPC_GETTITLE__.
Referenced by server::zone::packets::chat::ChatRoomList::addChannel(), and ChatOnCreateRoom::ChatOnCreateRoom().
bool ChatRoom::hasPlayer (CreatureObject * player)
Definition at line 205 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::hasPlayer(), and RPC_HASPLAYER__CREATUREOBJECT_.
Referenced by server::chat::ChatManagerImplementation::handleChatRoomMessage().
bool ChatRoom::hasPlayer (const String & name)
Definition at line 219 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::hasPlayer(), and RPC_HASPLAYER__STRING_.
void ChatRoom::init (ZoneServer * serv, ChatRoom * par, const String & roomName, unsigned int channelID)
Definition at line 37 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::init(), and RPC_INIT__ZONESERVER_CHATROOM_STRING_INT_.
Referenced by server::chat::ChatManagerImplementation::createRoom().
bool ChatRoom::isModerated ()
Definition at line 298 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::isModerated(), and RPC_ISMODERATED__.
bool ChatRoom::isPrivate ()
Definition at line 285 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::isPrivate(), and RPC_ISPRIVATE__.
Referenced by server::chat::ChatManagerImplementation::createRoomByFullPath().
bool ChatRoom::isPublic ()
Definition at line 272 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::isPublic(), and RPC_ISPUBLIC__.
Referenced by server::chat::ChatManagerImplementation::populateRoomListMessage().
void ChatRoom::removeAllPlayers ()
Definition at line 233 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::removeAllPlayers(), and RPC_REMOVEALLPLAYERS__.
Referenced by server::chat::ChatManagerImplementation::destroyRoom().
void ChatRoom::removePlayer (CreatureObject * player, bool doLock = true)
Definition at line 153 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::removePlayer(), and RPC_REMOVEPLAYER__CREATUREOBJECT_BOOL_.
Referenced by GroupManager::leaveGroup(), server::zone::managers::guild::GuildManagerImplementation::leaveGuild(), server::zone::objects::player::PlayerObjectImplementation::notifySceneReady(), and server::zone::objects::player::PlayerObjectImplementation::unload().
void ChatRoom::removePlayer (const String & player)
Definition at line 168 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::removePlayer(), and RPC_REMOVEPLAYER__STRING_.
void ChatRoom::removeSubRoom (ChatRoom * channel)
Definition at line 96 of file ChatRoom.cpp.
References _getImplementation(), server::chat::room::ChatRoomImplementation::removeSubRoom(), and RPC_REMOVESUBROOM__CHATROOM_.
Referenced by server::chat::ChatManagerImplementation::destroyRoom().
void ChatRoom::sendDestroyTo (CreatureObject * player)
Definition at line 68 of file ChatRoom.cpp.
References _getImplementation(), RPC_SENDDESTROYTO__CREATUREOBJECT_, and server::chat::room::ChatRoomImplementation::sendDestroyTo().
Referenced by server::zone::objects::group::GroupObjectImplementation::disband(), and GroupManager::leaveGroup().
void ChatRoom::sendTo (CreatureObject * player)
Definition at line 54 of file ChatRoom.cpp.
References _getImplementation(), RPC_SENDTO__CREATUREOBJECT_, and server::chat::room::ChatRoomImplementation::sendTo().
Referenced by server::zone::objects::player::PlayerObjectImplementation::notifySceneReady().
void ChatRoom::setCreator (const String & Creator)
Definition at line 470 of file ChatRoom.cpp.
References _getImplementation(), RPC_SETCREATOR__STRING_, and server::chat::room::ChatRoomImplementation::setCreator().
void ChatRoom::setModerated (bool moderate)
Definition at line 311 of file ChatRoom.cpp.
References _getImplementation(), RPC_SETMODERATED__BOOL_, and server::chat::room::ChatRoomImplementation::setModerated().
void ChatRoom::setName (const String & Name)
Definition at line 352 of file ChatRoom.cpp.
References _getImplementation(), RPC_SETNAME__STRING_, and server::chat::room::ChatRoomImplementation::setName().
void ChatRoom::setOwner (const String & Owner)
Definition at line 456 of file ChatRoom.cpp.
References _getImplementation(), RPC_SETOWNER__STRING_, and server::chat::room::ChatRoomImplementation::setOwner().
void ChatRoom::setPrivate ()
Definition at line 246 of file ChatRoom.cpp.
References _getImplementation(), RPC_SETPRIVATE__, and server::chat::room::ChatRoomImplementation::setPrivate().
Referenced by server::chat::ChatManagerImplementation::createGroupRoom(), and server::chat::ChatManagerImplementation::initiateRooms().
void ChatRoom::setPublic ()
Definition at line 259 of file ChatRoom.cpp.
References _getImplementation(), RPC_SETPUBLIC__, and server::chat::room::ChatRoomImplementation::setPublic().
void ChatRoom::setRoomID (int id)
Definition at line 498 of file ChatRoom.cpp.
References _getImplementation(), RPC_SETROOMID__INT_, and server::chat::room::ChatRoomImplementation::setRoomID().
void ChatRoom::setTitle (const String & Title)
Definition at line 484 of file ChatRoom.cpp.
References _getImplementation(), RPC_SETTITLE__STRING_, and server::chat::room::ChatRoomImplementation::setTitle().
Friends And Related Function Documentation
friend class ChatRoomHelper friend
Definition at line 168 of file ChatRoom.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/room/ChatRoom.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/room/ChatRoom.cpp