Core3: BoolParam Class Reference
BoolParam Class Reference
#include <BoolParam.h>
Public Member Functions
BoolParam ()
BoolParam (bool b)
BoolParam & operator= (bool val)
String toString ()
virtual bool parse (engine::util::Chunk *source)
Public Member Functions inherited from TemplateBase< bool >
TemplateBase (const bool &defaultValue)
TemplateBase (const TemplateBase &t)
virtual ~TemplateBase ()
void create (const bool &val)
virtual int compareTo (const bool &val) const
virtual bool operator== (const bool &val) const
virtual bool operator< (const bool &val) const
virtual bool operator> (const bool &val) const
virtual bool operator!= (const bool &val) const
operator bool () const
virtual bool getValue () const
virtual bool get () const
virtual void setValue (const bool &val)
Public Member Functions inherited from Param
Param ()
virtual ~Param ()
uint32 getType ()
void setType (uint32 tp)
bool isBool ()
bool isFloat ()
bool isInteger ()
bool isString ()
bool isStringId ()
Static Public Member Functions
static bool toBinaryStream (ObjectOutputStream *stream)
static bool parseFromBinaryStream (ObjectInputStream *stream)
Additional Inherited Members
Static Public Attributes inherited from Param
static const uint32 BOOL = 0x01
static const uint32 FLOAT = 0x02
static const uint32 INTEGER = 0x04
static const uint32 STRING = 0x08
static const uint32 STRINGID = 0x10
static const uint32 VECTOR = 0x12
static const uint32 DYNAMICVARIABLE = 0x014
static const uint32 TRIGGERVOLUME = 0x16
static const uint32 PALETTECOLORCUSTOMIZATION = 0x18
static const uint32 RANGEDINTCUSTOMIZATIONVARIABLE = 0x20
static const uint32 CUSTOMIZATIONVARIABLEMAP = 0x22
Protected Attributes inherited from TemplateBase< bool >
bool value
Detailed Description
Definition at line 13 of file BoolParam.h.
Constructor & Destructor Documentation
BoolParam::BoolParam () inline
Definition at line 15 of file BoolParam.h.
References Param::BOOL, and Param::setType().
BoolParam::BoolParam (bool b) inline
Definition at line 19 of file BoolParam.h.
References Param::BOOL, and Param::setType().
Member Function Documentation
BoolParam& BoolParam::operator= (bool val) inline
Definition at line 23 of file BoolParam.h.
References TemplateBase< bool >::create().
virtual bool BoolParam::parse (engine::util::Chunk * source) inline virtual
Implements Param.
Definition at line 45 of file BoolParam.h.
References TemplateBase< bool >::create().
Referenced by SharedTangibleObjectTemplate::parseVariableData(), and server::zone::templates::SharedObjectTemplate::parseVariableData().
static bool BoolParam::parseFromBinaryStream (ObjectInputStream * stream) inline static
Definition at line 41 of file BoolParam.h.
static bool BoolParam::toBinaryStream (ObjectOutputStream * stream) inline static
Definition at line 33 of file BoolParam.h.
String BoolParam::toString () inline virtual
Implements Param.
Definition at line 29 of file BoolParam.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/params/primitives/BoolParam.h