Core3: server::zone::objects::scene::variables::DeltaVector< E > Class Template Reference
server::zone::objects::scene::variables::DeltaVector< E > Class Template Reference
#include <DeltaVector.h>
Public Member Functions
DeltaVector ()
DeltaVector (int initsize, int incr)
DeltaVector (const DeltaVector &v)
~DeltaVector ()
DeltaVector & operator= (const DeltaVector &v)
void addSerializableVariables ()
virtual E set (int idx, const E &newValue, DeltaMessage *message=NULL, int updates=1)
virtual bool add (const E &element, DeltaMessage *message=NULL, int updates=1)
E & get (int index) const
E & getSafe (int index)
E remove (int index, DeltaMessage *message=NULL, int updates=1)
void removeAll (DeltaMessage *message=NULL)
virtual void insertToMessage (BaseMessage *msg)
virtual void insertItemToMessage (E *item, BaseMessage *msg)
virtual bool contains (const E &element)
int find (const E &element)
uint32 getUpdateCounter ()
uint32 getNewUpdateCounter (int increment)
void setUpdateCounter (int count)
void resetUpdateCounter ()
int size ()
ReadWriteLock * getLock ()
Protected Attributes
Vector< E > vector
uint32 updateCounter
ReadWriteLock * mutex
Detailed Description
template<class E>
class server::zone::objects::scene::variables::DeltaVector< E >
Definition at line 20 of file DeltaVector.h.
Constructor & Destructor Documentation
template<class E> server::zone::objects::scene::variables::DeltaVector< E >::DeltaVector () inline
Definition at line 28 of file DeltaVector.h.
template<class E> server::zone::objects::scene::variables::DeltaVector< E >::DeltaVector (int initsize, int incr) inline
Definition at line 36 of file DeltaVector.h.
template<class E> server::zone::objects::scene::variables::DeltaVector< E >::DeltaVector (const DeltaVector< E > & v) inline
Definition at line 44 of file DeltaVector.h.
template<class E> server::zone::objects::scene::variables::DeltaVector< E >::~DeltaVector () inline
Definition at line 53 of file DeltaVector.h.
Member Function Documentation
template<class E> virtual bool server::zone::objects::scene::variables::DeltaVector< E >::add (const E & element, DeltaMessage * message = NULL, int updates = 1) inline virtual
Definition at line 94 of file DeltaVector.h.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::addDefender(), server::zone::objects::group::GroupObjectImplementation::addMember(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::initializeIngredientSlots(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), and server::zone::objects::creature::CreatureObjectImplementation::loadTemplateData().
template<class E> void server::zone::objects::scene::variables::DeltaVector< E >::addSerializableVariables () inline
Definition at line 70 of file DeltaVector.h.
Referenced by server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::DeltaVector().
template<class E> virtual bool server::zone::objects::scene::variables::DeltaVector< E >::contains (const E & element) inline virtual
Definition at line 166 of file DeltaVector.h.
Referenced by server::zone::objects::installation::InstallationObjectImplementation::addResourceToHopper(), server::zone::objects::creature::CreatureObjectImplementation::addSkill(), server::zone::objects::creature::CreatureObjectImplementation::addWearableObject(), server::zone::objects::creature::AiAgentImplementation::doAttack(), AttackStateComponent::doRecovery(), and server::zone::objects::creature::CreatureObjectImplementation::removeSkill().
template<class E> int server::zone::objects::scene::variables::DeltaVector< E >::find (const E & element) inline
Definition at line 170 of file DeltaVector.h.
Referenced by server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::contains(), server::zone::objects::player::PlayerObjectImplementation::removeAbilities(), server::zone::objects::player::PlayerObjectImplementation::removeAbility(), and server::zone::objects::creature::CreatureObjectImplementation::removeWearableObject().
template<class E> E& server::zone::objects::scene::variables::DeltaVector< E >::get (int index) const inline
Definition at line 113 of file DeltaVector.h.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::addDefender(), server::zone::objects::creature::CreatureObjectImplementation::addEncumbrance(), server::zone::objects::group::GroupObjectImplementation::addGroupModifiers(), server::zone::objects::creature::CreatureObjectImplementation::addMaxHAM(), server::zone::objects::creature::CreatureObjectImplementation::addWounds(), CombatManager::attemptPeace(), server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::group::GroupObjectImplementation::broadcastMessage(), server::zone::objects::installation::InstallationObjectImplementation::clearResourceHopper(), server::zone::objects::installation::InstallationObjectImplementation::destroyObjectFromDatabase(), server::zone::objects::group::GroupObjectImplementation::disband(), server::zone::objects::creature::AiAgentImplementation::doAttack(), ResetJediCommand::doQueueCommand(), RequestStatMigrationDataCommand::doQueueCommand(), AttackStateComponent::doRecovery(), PlayerInfoCommand::executeCommand(), CombatManager::forcePeace(), FriendsListMessage::FriendsListMessage(), server::zone::objects::creature::CreatureObjectImplementation::getBaseHAM(), server::zone::objects::installation::InstallationObjectImplementation::getContainerFromHopper(), server::zone::objects::group::GroupObjectImplementation::getGroupHarvestModifier(), server::zone::objects::creature::CreatureObjectImplementation::getHAM(), server::zone::objects::installation::InstallationObjectImplementation::getHopperItemQuantity(), server::zone::objects::installation::InstallationObjectImplementation::getHopperSize(), server::zone::objects::creature::CreatureObjectImplementation::getMaxHAM(), server::zone::managers::player::PlayerManagerImplementation::getTeachableSkills(), server::zone::objects::creature::CreatureObjectImplementation::getWounds(), server::zone::objects::group::GroupObjectImplementation::hasMember(), server::zone::objects::creature::CreatureObjectImplementation::healDamage(), server::zone::objects::creature::CreatureObjectImplementation::healWound(), server::zone::objects::creature::CreatureObjectImplementation::inflictDamage(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::initializeSession(), HarvesterObjectMessage7::insertHopperSpawnObjects(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), server::zone::objects::creature::CreatureObjectImplementation::loadTemplateData(), server::zone::objects::group::GroupObjectImplementation::makeLeader(), server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefender(), server::zone::objects::creature::AiAgentImplementation::removeDefender(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefenders(), server::zone::objects::group::GroupObjectImplementation::removeGroupModifiers(), server::zone::objects::group::GroupObjectImplementation::removeMember(), server::zone::objects::player::PlayerObjectImplementation::removeSchematics(), ClearDefenderListsTask::run(), StartDanceCommand::sendAvailableDances(), StartMusicCommand::sendAvailableSongs(), server::zone::objects::group::GroupObjectImplementation::sendSystemMessage(), server::zone::objects::installation::InstallationObjectImplementation::setActiveResource(), server::zone::objects::creature::CreatureObjectImplementation::setBaseHAM(), server::zone::objects::tangible::TangibleObjectImplementation::setDefender(), server::zone::objects::creature::CreatureObjectImplementation::setEncumbrance(), server::zone::objects::creature::CreatureObjectImplementation::setHAM(), server::zone::objects::creature::AiAgentImplementation::setLevel(), server::zone::objects::creature::CreatureObjectImplementation::setMaxHAM(), server::zone::objects::creature::CreatureObjectImplementation::setWounds(), server::zone::objects::group::GroupObjectImplementation::startChatRoom(), server::zone::managers::skill::SkillManager::surrenderAllSkills(), server::zone::managers::skill::SkillManager::surrenderSkill(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::synchronizedUIListen(), server::zone::objects::installation::InstallationObjectImplementation::updateHopper(), server::zone::objects::installation::InstallationObjectImplementation::updateResourceContainerQuantity(), server::zone::managers::skill::SkillManager::updateXpLimits(), and server::zone::managers::skill::SkillModManager::verifySkillBoxSkillMods().
template<class E> ReadWriteLock* server::zone::objects::scene::variables::DeltaVector< E >::getLock () inline
Definition at line 199 of file DeltaVector.h.
Referenced by server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::add(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::getSafe(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::insertToMessage(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::remove(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::removeAll(), and server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::set().
template<class E> uint32 server::zone::objects::scene::variables::DeltaVector< E >::getNewUpdateCounter (int increment) inline
Definition at line 183 of file DeltaVector.h.
template<class E> E& server::zone::objects::scene::variables::DeltaVector< E >::getSafe (int index) inline
Definition at line 117 of file DeltaVector.h.
template<class E> uint32 server::zone::objects::scene::variables::DeltaVector< E >::getUpdateCounter () inline
Definition at line 179 of file DeltaVector.h.
template<class E> virtual void server::zone::objects::scene::variables::DeltaVector< E >::insertItemToMessage (E * item, BaseMessage * msg) inline virtual
Definition at line 162 of file DeltaVector.h.
Referenced by server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::add(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::insertToMessage(), and server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::set().
template<class E> virtual void server::zone::objects::scene::variables::DeltaVector< E >::insertToMessage (BaseMessage * msg) inline virtual
Reimplemented in SkillList, HopperList, SchematicList, and AbilityList.
Definition at line 150 of file DeltaVector.h.
Referenced by CreatureObjectMessage4::CreatureObjectMessage4(), CreatureObjectMessage6::CreatureObjectMessage6(), GroupObjectMessage6::groupLists(), TangibleObjectMessage6::insertDefenders(), CreatureObjectMessage6::insertEquipmentList(), PlayerObjectMessage9::PlayerObjectMessage9(), and server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendMsco7().
template<class E> DeltaVector& server::zone::objects::scene::variables::DeltaVector< E >::operator= (const DeltaVector< E > & v) inline
Definition at line 60 of file DeltaVector.h.
template<class E> E server::zone::objects::scene::variables::DeltaVector< E >::remove (int index, DeltaMessage * message = NULL, int updates = 1) inline
Definition at line 123 of file DeltaVector.h.
Referenced by server::zone::objects::player::PlayerObjectImplementation::removeAbilities(), server::zone::objects::player::PlayerObjectImplementation::removeAbility(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefender(), server::zone::objects::group::GroupObjectImplementation::removeMember(), server::zone::objects::installation::InstallationObjectImplementation::setActiveResource(), and server::zone::objects::installation::InstallationObjectImplementation::updateResourceContainerQuantity().
template<class E> void server::zone::objects::scene::variables::DeltaVector< E >::removeAll (DeltaMessage * message = NULL) inline
Definition at line 139 of file DeltaVector.h.
Referenced by server::zone::objects::installation::InstallationObjectImplementation::clearResourceHopper(), server::zone::objects::group::GroupObjectImplementation::disband(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::initializeIngredientSlots(), server::zone::objects::creature::AiAgentImplementation::loadTemplateData(), server::zone::objects::creature::CreatureObjectImplementation::loadTemplateData(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefender(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefenders(), and server::zone::objects::player::PlayerObjectImplementation::removeSchematics().
template<class E> void server::zone::objects::scene::variables::DeltaVector< E >::resetUpdateCounter () inline
Definition at line 191 of file DeltaVector.h.
template<class E> virtual E server::zone::objects::scene::variables::DeltaVector< E >::set (int idx, const E & newValue, DeltaMessage * message = NULL, int updates = 1) inline virtual
Definition at line 75 of file DeltaVector.h.
Referenced by server::zone::objects::group::GroupObjectImplementation::makeLeader(), server::zone::objects::manufactureschematic::ManufactureSchematicImplementation::sendDelta7(), server::zone::objects::creature::CreatureObjectImplementation::setBaseHAM(), server::zone::objects::tangible::TangibleObjectImplementation::setDefender(), server::zone::objects::creature::CreatureObjectImplementation::setEncumbrance(), server::zone::objects::creature::CreatureObjectImplementation::setHAM(), server::zone::objects::creature::CreatureObjectImplementation::setMaxHAM(), and server::zone::objects::creature::CreatureObjectImplementation::setWounds().
template<class E> void server::zone::objects::scene::variables::DeltaVector< E >::setUpdateCounter (int count) inline
Definition at line 187 of file DeltaVector.h.
template<class E> int server::zone::objects::scene::variables::DeltaVector< E >::size () inline
Definition at line 195 of file DeltaVector.h.
Referenced by server::zone::objects::tangible::TangibleObjectImplementation::addDefender(), server::zone::objects::creature::AiAgentImplementation::addDefender(), server::zone::objects::creature::CreatureObjectImplementation::addEncumbrance(), server::zone::objects::group::GroupObjectImplementation::addGroupModifiers(), server::zone::objects::creature::CreatureObjectImplementation::addMaxHAM(), server::zone::objects::creature::CreatureObjectImplementation::addWounds(), CombatManager::attemptPeace(), server::zone::managers::skill::SkillManager::awardSkill(), server::zone::objects::group::GroupObjectImplementation::broadcastMessage(), server::zone::objects::installation::InstallationObjectImplementation::clearResourceHopper(), server::zone::objects::installation::InstallationObjectImplementation::destroyObjectFromDatabase(), server::zone::objects::group::GroupObjectImplementation::disband(), server::zone::objects::creature::AiAgentImplementation::doAttack(), ResetJediCommand::doQueueCommand(), AttackStateComponent::doRecovery(), server::zone::objects::tangible::TangibleObjectImplementation::dropFromDefenderLists(), PlayerInfoCommand::executeCommand(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::find(), CombatManager::forcePeace(), FriendsListMessage::FriendsListMessage(), server::zone::objects::installation::InstallationObjectImplementation::getActualRate(), server::zone::objects::installation::InstallationObjectImplementation::getContainerFromHopper(), server::zone::objects::group::GroupObjectImplementation::getGroupHarvestModifier(), server::zone::objects::installation::InstallationObjectImplementation::getHopperItemQuantity(), server::zone::objects::installation::InstallationObjectImplementation::getHopperSize(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::getRedeedMessage(), server::zone::managers::player::PlayerManagerImplementation::getTeachableSkills(), server::zone::objects::group::GroupObjectImplementation::hasMember(), server::zone::objects::creature::CreatureObjectImplementation::healDamage(), server::zone::objects::creature::CreatureObjectImplementation::healWound(), server::zone::objects::creature::CreatureObjectImplementation::inflictDamage(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::initializeSession(), HarvesterObjectMessage7::insertHopperItems(), HarvesterObjectMessage7::insertHopperSpawnObjects(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::insertToMessage(), server::zone::objects::group::GroupObjectImplementation::makeLeader(), server::zone::objects::creature::CreatureObjectImplementation::notifyLoadFromDatabase(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefender(), server::zone::objects::creature::AiAgentImplementation::removeDefender(), server::zone::objects::tangible::TangibleObjectImplementation::removeDefenders(), server::zone::objects::group::GroupObjectImplementation::removeGroupModifiers(), server::zone::objects::group::GroupObjectImplementation::removeMember(), server::zone::objects::player::PlayerObjectImplementation::removeSchematics(), ClearDefenderListsTask::run(), StartDanceCommand::sendAvailableDances(), StartMusicCommand::sendAvailableSongs(), server::zone::objects::group::GroupObjectImplementation::sendSystemMessage(), server::zone::objects::installation::InstallationObjectImplementation::setActiveResource(), server::zone::objects::tangible::TangibleObjectImplementation::setDefender(), server::zone::managers::skill::SkillManager::surrenderAllSkills(), server::zone::managers::skill::SkillManager::surrenderSkill(), server::zone::objects::installation::harvester::HarvesterObjectImplementation::synchronizedUIListen(), server::zone::objects::installation::InstallationObjectImplementation::updateHopper(), server::zone::objects::installation::InstallationObjectImplementation::updateResourceContainerQuantity(), server::zone::managers::skill::SkillManager::updateXpLimits(), and server::zone::managers::skill::SkillModManager::verifySkillBoxSkillMods().
Member Data Documentation
template<class E> ReadWriteLock* server::zone::objects::scene::variables::DeltaVector< E >::mutex protected
Definition at line 25 of file DeltaVector.h.
Referenced by server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::DeltaVector(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::getLock(), and server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::~DeltaVector().
template<class E> uint32 server::zone::objects::scene::variables::DeltaVector< E >::updateCounter protected
Definition at line 23 of file DeltaVector.h.
Referenced by server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::add(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::addSerializableVariables(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::DeltaVector(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::getNewUpdateCounter(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::getUpdateCounter(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::insertToMessage(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::operator=(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::remove(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::removeAll(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::resetUpdateCounter(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::set(), and server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::setUpdateCounter().
template<class E> Vector<E> server::zone::objects::scene::variables::DeltaVector< E >::vector protected
Definition at line 22 of file DeltaVector.h.
Referenced by server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::add(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::addSerializableVariables(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::DeltaVector(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::get(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::getSafe(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::operator=(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::remove(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::removeAll(), server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::set(), and server::zone::objects::scene::variables::DeltaVector< ManagedReference< DraftSchematic * > >::size().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/DeltaVector.h