Core3: server::zone::objects::mission::EntertainerMissionObjective Class Reference
server::zone::objects::mission::EntertainerMissionObjective Class Reference
#include <EntertainerMissionObjective.h>
Public Member Functions
EntertainerMissionObjective (MissionObject *mission)
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
void setIsEntertaining (bool value)
void clearLocationActiveAreaAndObservers ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void startCompleteTask ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (MissionObject *parent)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
EntertainerMissionObjective (DummyConstructorParameter *param)
virtual ~EntertainerMissionObjective ()
Protected Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (DummyConstructorParameter *param)
virtual ~MissionObjective ()
Friends
class EntertainerMissionObjectiveHelper
Detailed Description
Definition at line 123 of file EntertainerMissionObjective.h.
Constructor & Destructor Documentation
EntertainerMissionObjective::EntertainerMissionObjective (MissionObject * mission)
Definition at line 27 of file EntertainerMissionObjective.cpp.
References server::zone::objects::mission::EntertainerMissionObjectiveImplementation::_setStub().
EntertainerMissionObjective::EntertainerMissionObjective (DummyConstructorParameter * param) protected
Definition at line 34 of file EntertainerMissionObjective.cpp.
EntertainerMissionObjective::~EntertainerMissionObjective () protected virtual
Definition at line 38 of file EntertainerMissionObjective.cpp.
Member Function Documentation
DistributedObjectServant * EntertainerMissionObjective::_getImplementation ()
Definition at line 162 of file EntertainerMissionObjective.cpp.
Referenced by abort(), activate(), clearLocationActiveAreaAndObservers(), complete(), getEndPosition(), initializeTransientMembers(), notifyObserverEvent(), setIsEntertaining(), and startCompleteTask().
DistributedObjectServant * EntertainerMissionObjective::_getImplementationForRead ()
Definition at line 168 of file EntertainerMissionObjective.cpp.
void EntertainerMissionObjective::_setImplementation (DistributedObjectServant * servant)
Definition at line 172 of file EntertainerMissionObjective.cpp.
void EntertainerMissionObjective::abort ()
Definition at line 69 of file EntertainerMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::abort(), and RPC_ABORT__.
void EntertainerMissionObjective::activate ()
Definition at line 56 of file EntertainerMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::activate(), and RPC_ACTIVATE__.
void EntertainerMissionObjective::clearLocationActiveAreaAndObservers ()
Definition at line 109 of file EntertainerMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::clearLocationActiveAreaAndObservers(), and RPC_CLEARLOCATIONACTIVEAREAANDOBSERVERS__.
void EntertainerMissionObjective::complete ()
Definition at line 82 of file EntertainerMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::complete(), and RPC_COMPLETE__.
Vector3 EntertainerMissionObjective::getEndPosition ()
Definition at line 153 of file EntertainerMissionObjective.cpp.
References _getImplementation(), and server::zone::objects::mission::EntertainerMissionObjectiveImplementation::getEndPosition().
void EntertainerMissionObjective::initializeTransientMembers ()
Definition at line 43 of file EntertainerMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
int EntertainerMissionObjective::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 122 of file EntertainerMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::EntertainerMissionObjectiveImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
void EntertainerMissionObjective::setIsEntertaining (bool value)
Definition at line 95 of file EntertainerMissionObjective.cpp.
References _getImplementation(), RPC_SETISENTERTAINING__BOOL_, and server::zone::objects::mission::EntertainerMissionObjectiveImplementation::setIsEntertaining().
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::updateEntertainerMissionStatus().
void EntertainerMissionObjective::startCompleteTask ()
Definition at line 140 of file EntertainerMissionObjective.cpp.
References _getImplementation(), RPC_STARTCOMPLETETASK__, and server::zone::objects::mission::EntertainerMissionObjectiveImplementation::startCompleteTask().
Friends And Related Function Documentation
friend class EntertainerMissionObjectiveHelper friend
Definition at line 155 of file EntertainerMissionObjective.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/EntertainerMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/EntertainerMissionObjective.cpp