Core3: TurretDataComponent Class Reference
TurretDataComponent Class Reference
#include <TurretDataComponent.h>
Public Member Functions
TurretDataComponent ()
~TurretDataComponent ()
void initializeTransientMembers ()
bool canAutoFire ()
bool canManualFire ()
void refreshControlTimer (int seconds)
bool hasControlTimedOut ()
void updateAutoCooldown (float secondsToAdd)
void updateManualCooldown (float secondsToAdd)
bool isTurretData ()
void setController (CreatureObject *creature)
CreatureObject * getController ()
void setTarget (CreatureObject *creature)
CreatureObject * getTarget ()
void setFireTask (Task *newTask)
Task * getFireTask ()
void rescheduleManualFireTask (float secondsToWait)
void rescheduleFireTask (float secondsToWait, bool manual)
void setWeapon (WeaponObject *weapon)
unsigned int getArmorRating ()
float getKinetic ()
float getEnergy ()
float getElectricity ()
float getStun ()
float getBlast ()
float getHeat ()
float getCold ()
float getAcid ()
float getLightSaber ()
float getChanceHit ()
String getWeaponString ()
void fillAttributeList (AttributeListMessage *alm)
Public Member Functions inherited from DataObjectComponent
DataObjectComponent ()
~DataObjectComponent ()
virtual void notifyObjectDestroyingFromDatabase ()
void setParent (SceneObject *object)
SceneObject * getParent ()
virtual bool isDiceData ()
virtual bool isVendorData ()
virtual bool isAuctionTerminalData ()
virtual bool isCreatureHabitatData ()
virtual bool isBuildingData ()
virtual bool isDestructibleBuildingData ()
virtual bool isDetectorData ()
virtual bool isGCWBaseData ()
virtual bool isSecurityTerminalData ()
virtual bool isMinefieldData ()
virtual bool isTurretControlTerminalData ()
virtual bool isDecoration ()
Protected Attributes
int maxrange
Time nextFireTime
Time nextManualFireTime
Time controlTimeout
int attackSpeed
SharedInstallationObjectTemplate * templateData
ManagedReference
< CreatureObject * > controller
ManagedReference
< CreatureObject * > target
Reference< Task * > turretFireTask
Protected Attributes inherited from DataObjectComponent
ManagedWeakReference
< SceneObject * > parent
Private Member Functions
void addSerializableVariables ()
Detailed Description
Definition at line 17 of file TurretDataComponent.h.
Constructor & Destructor Documentation
TurretDataComponent::TurretDataComponent () inline
Definition at line 31 of file TurretDataComponent.h.
References attackSpeed, controller, controlTimeout, maxrange, nextFireTime, nextManualFireTime, target, templateData, and turretFireTask.
TurretDataComponent::~TurretDataComponent () inline
Definition at line 43 of file TurretDataComponent.h.
Member Function Documentation
void TurretDataComponent::addSerializableVariables () inline private
Definition at line 119 of file TurretDataComponent.h.
bool TurretDataComponent::canAutoFire () inline
Definition at line 49 of file TurretDataComponent.h.
References attackSpeed, and nextFireTime.
Referenced by TurretZoneComponent::notifyPositionUpdate(), and TurretFireTask::run().
bool TurretDataComponent::canManualFire () inline
Definition at line 53 of file TurretDataComponent.h.
References attackSpeed, and nextManualFireTime.
void TurretDataComponent::fillAttributeList (AttributeListMessage * alm)
Definition at line 62 of file TurretDataComponent.cpp.
References getAcid(), getArmorRating(), getBlast(), getCold(), getElectricity(), getEnergy(), getHeat(), getKinetic(), getLightSaber(), DataObjectComponent::getParent(), getStun(), and server::zone::packets::scene::AttributeListMessage::insertAttribute().
Referenced by server::zone::objects::installation::InstallationObjectImplementation::fillAttributeList().
float TurretDataComponent::getAcid ()
Definition at line 285 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getAcid(), and templateData.
Referenced by fillAttributeList(), and CombatManager::getArmorTurretReduction().
unsigned int TurretDataComponent::getArmorRating ()
Definition at line 229 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getArmorRating(), and templateData.
Referenced by fillAttributeList(), and CombatManager::getArmorPiercing().
float TurretDataComponent::getBlast ()
Definition at line 264 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getBlast(), and templateData.
Referenced by fillAttributeList(), and CombatManager::getArmorTurretReduction().
float TurretDataComponent::getChanceHit ()
Definition at line 299 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getChanceHit(), and templateData.
float TurretDataComponent::getCold ()
Definition at line 278 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getCold(), and templateData.
Referenced by fillAttributeList(), and CombatManager::getArmorTurretReduction().
CreatureObject* TurretDataComponent::getController () inline
Definition at line 78 of file TurretDataComponent.h.
References controller.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::canUseTurret(), TurretFireTask::checkTarget(), TurretFireTask::checkTurretController(), TurretFireTask::executeCommand(), rescheduleFireTask(), and TurretControlSuiCallback::run().
float TurretDataComponent::getElectricity ()
Definition at line 250 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getElectricity(), and templateData.
Referenced by fillAttributeList(), and CombatManager::getArmorTurretReduction().
float TurretDataComponent::getEnergy ()
Definition at line 243 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getEnergy(), and templateData.
Referenced by fillAttributeList(), and CombatManager::getArmorTurretReduction().
Task* TurretDataComponent::getFireTask () inline
Definition at line 94 of file TurretDataComponent.h.
References turretFireTask.
Referenced by rescheduleFireTask(), and TurretControlSuiCallback::run().
float TurretDataComponent::getHeat ()
Definition at line 271 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getHeat(), and templateData.
Referenced by fillAttributeList(), and CombatManager::getArmorTurretReduction().
float TurretDataComponent::getKinetic ()
Definition at line 236 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getKinetic(), and templateData.
Referenced by fillAttributeList(), and CombatManager::getArmorTurretReduction().
float TurretDataComponent::getLightSaber ()
Definition at line 292 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getLightSaber(), and templateData.
Referenced by fillAttributeList(), and CombatManager::getArmorTurretReduction().
float TurretDataComponent::getStun ()
Definition at line 257 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getStun(), and templateData.
Referenced by fillAttributeList(), and CombatManager::getArmorTurretReduction().
CreatureObject* TurretDataComponent::getTarget () inline
Definition at line 86 of file TurretDataComponent.h.
References target.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::canUseTurret(), TurretFireTask::checkTarget(), server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), rescheduleFireTask(), TurretControlSuiCallback::run(), and TurretFireTask::run().
String TurretDataComponent::getWeaponString ()
Definition at line 306 of file TurretDataComponent.cpp.
References SharedInstallationObjectTemplate::getWeapon(), and templateData.
bool TurretDataComponent::hasControlTimedOut () inline
Definition at line 62 of file TurretDataComponent.h.
References controlTimeout.
void TurretDataComponent::initializeTransientMembers () virtual
Reimplemented from DataObjectComponent.
Definition at line 13 of file TurretDataComponent.cpp.
References attackSpeed, server::zone::objects::tangible::weapon::WeaponObject::getAttackSpeed(), server::zone::objects::tangible::weapon::WeaponObject::getMaxRange(), server::zone::objects::scene::SceneObject::getObjectTemplate(), DataObjectComponent::getParent(), server::zone::objects::scene::SceneObject::getSlottedObject(), maxrange, and templateData.
bool TurretDataComponent::isTurretData () inline virtual
Reimplemented from DataObjectComponent.
Definition at line 69 of file TurretDataComponent.h.
void TurretDataComponent::refreshControlTimer (int seconds) inline
Definition at line 57 of file TurretDataComponent.h.
References controlTimeout.
void TurretDataComponent::rescheduleFireTask (float secondsToWait, bool manual)
Definition at line 32 of file TurretDataComponent.cpp.
References getController(), getFireTask(), DataObjectComponent::getParent(), getTarget(), setController(), setFireTask(), setTarget(), and target.
Referenced by TurretFireTask::doAutoFire(), and TurretFireTask::handleManualFire().
void TurretDataComponent::rescheduleManualFireTask (float secondsToWait)
void TurretDataComponent::setController (CreatureObject * creature) inline
Definition at line 74 of file TurretDataComponent.h.
References controller.
Referenced by server::zone::managers::gcw::GCWManagerImplementation::generateTurretControlBoxTo(), and rescheduleFireTask().
void TurretDataComponent::setFireTask (Task * newTask) inline
Definition at line 90 of file TurretDataComponent.h.
References turretFireTask.
Referenced by rescheduleFireTask(), TurretControlSuiCallback::run(), and TurretFireTask::run().
void TurretDataComponent::setTarget (CreatureObject * creature) inline
Definition at line 82 of file TurretDataComponent.h.
References target.
Referenced by TurretFireTask::doAutoFire(), TurretFireTask::handleManualFire(), rescheduleFireTask(), TurretControlSuiCallback::run(), and TurretFireTask::run().
void TurretDataComponent::setWeapon (WeaponObject * weapon)
Definition at line 55 of file TurretDataComponent.cpp.
References attackSpeed, server::zone::objects::tangible::weapon::WeaponObject::getAttackSpeed(), server::zone::objects::tangible::weapon::WeaponObject::getMaxRange(), and maxrange.
Referenced by server::zone::objects::installation::InstallationObjectImplementation::createChildObjects().
void TurretDataComponent::updateAutoCooldown (float secondsToAdd)
Definition at line 217 of file TurretDataComponent.cpp.
References nextFireTime.
Referenced by TurretFireTask::doAutoFire(), and TurretFireTask::handleManualFire().
void TurretDataComponent::updateManualCooldown (float secondsToAdd)
Definition at line 223 of file TurretDataComponent.cpp.
References nextManualFireTime.
Referenced by TurretFireTask::doAutoFire(), and TurretFireTask::handleManualFire().
Member Data Documentation
int TurretDataComponent::attackSpeed protected
Definition at line 24 of file TurretDataComponent.h.
Referenced by canAutoFire(), canManualFire(), initializeTransientMembers(), setWeapon(), and TurretDataComponent().
ManagedReference<CreatureObject*> TurretDataComponent::controller protected
Definition at line 26 of file TurretDataComponent.h.
Referenced by getController(), setController(), and TurretDataComponent().
Time TurretDataComponent::controlTimeout protected
Definition at line 23 of file TurretDataComponent.h.
Referenced by hasControlTimedOut(), refreshControlTimer(), and TurretDataComponent().
int TurretDataComponent::maxrange protected
Definition at line 20 of file TurretDataComponent.h.
Referenced by initializeTransientMembers(), setWeapon(), and TurretDataComponent().
Time TurretDataComponent::nextFireTime protected
Definition at line 21 of file TurretDataComponent.h.
Referenced by canAutoFire(), TurretDataComponent(), and updateAutoCooldown().
Time TurretDataComponent::nextManualFireTime protected
Definition at line 22 of file TurretDataComponent.h.
Referenced by canManualFire(), TurretDataComponent(), and updateManualCooldown().
ManagedReference<CreatureObject*> TurretDataComponent::target protected
Definition at line 27 of file TurretDataComponent.h.
Referenced by getTarget(), rescheduleFireTask(), setTarget(), and TurretDataComponent().
SharedInstallationObjectTemplate* TurretDataComponent::templateData protected
Definition at line 25 of file TurretDataComponent.h.
Referenced by getAcid(), getArmorRating(), getBlast(), getChanceHit(), getCold(), getElectricity(), getEnergy(), getHeat(), getKinetic(), getLightSaber(), getStun(), getWeaponString(), initializeTransientMembers(), and TurretDataComponent().
Reference<Task*> TurretDataComponent::turretFireTask protected
Definition at line 28 of file TurretDataComponent.h.
Referenced by getFireTask(), setFireTask(), and TurretDataComponent().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/TurretDataComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/TurretDataComponent.cpp