Core3: server::zone::objects::player::sessions::DestroyStructureSessionAdapter Class Reference
server::zone::objects::player::sessions::DestroyStructureSessionAdapter Class Reference
#include <DestroyStructureSession.h>
Public Member Functions
DestroyStructureSessionAdapter (DestroyStructureSession *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
bool isDestroyCode (unsigned int code)
int initializeSession ()
int sendDestroyCode ()
int destroyStructure ()
int cancelSession ()
int clearSession ()
StructureObject * getStructureObject ()
Detailed Description
Definition at line 175 of file DestroyStructureSession.h.
Constructor & Destructor Documentation
DestroyStructureSessionAdapter::DestroyStructureSessionAdapter (DestroyStructureSession * impl)
Definition at line 339 of file DestroyStructureSession.cpp.
Member Function Documentation
int DestroyStructureSessionAdapter::cancelSession ()
Definition at line 402 of file DestroyStructureSession.cpp.
Referenced by invokeMethod().
int DestroyStructureSessionAdapter::clearSession ()
Definition at line 406 of file DestroyStructureSession.cpp.
Referenced by invokeMethod().
int DestroyStructureSessionAdapter::destroyStructure ()
Definition at line 398 of file DestroyStructureSession.cpp.
Referenced by invokeMethod().
StructureObject * DestroyStructureSessionAdapter::getStructureObject ()
Definition at line 410 of file DestroyStructureSession.cpp.
Referenced by invokeMethod().
int DestroyStructureSessionAdapter::initializeSession ()
Definition at line 390 of file DestroyStructureSession.cpp.
Referenced by invokeMethod().
void DestroyStructureSessionAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 342 of file DestroyStructureSession.cpp.
References cancelSession(), clearSession(), destroyStructure(), getStructureObject(), initializeSession(), isDestroyCode(), RPC_CANCELSESSION__, RPC_CLEARSESSION__, RPC_DESTROYSTRUCTURE__, RPC_GETSTRUCTUREOBJECT__, RPC_INITIALIZESESSION__, RPC_ISDESTROYCODE__INT_, RPC_SENDDESTROYCODE__, and sendDestroyCode().
bool DestroyStructureSessionAdapter::isDestroyCode (unsigned int code)
Definition at line 386 of file DestroyStructureSession.cpp.
Referenced by invokeMethod().
int DestroyStructureSessionAdapter::sendDestroyCode ()
Definition at line 394 of file DestroyStructureSession.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/DestroyStructureSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/DestroyStructureSession.cpp