Core3: server::zone::managers::creature::SpawnCoordinate Class Reference
server::zone::managers::creature::SpawnCoordinate Class Reference
#include <StaticSpawnGroup.h>
Public Member Functions
SpawnCoordinate ()
SpawnCoordinate (const SpawnCoordinate &cr)
virtual ~SpawnCoordinate ()
SpawnCoordinate & operator= (const SpawnCoordinate &cr)
Coordinate * getCoordinate ()
Quaternion * getDirection ()
void set (float a, float b, float c, float d)
void setPosition (float x, float z, float y)
String getTemplateName () const
void setTemplateName (String templateName)
Protected Attributes
String templateName
Coordinate coordinate
Quaternion quaternion
Detailed Description
Definition at line 18 of file StaticSpawnGroup.h.
Constructor & Destructor Documentation
server::zone::managers::creature::SpawnCoordinate::SpawnCoordinate () inline
Definition at line 25 of file StaticSpawnGroup.h.
server::zone::managers::creature::SpawnCoordinate::SpawnCoordinate (const SpawnCoordinate & cr) inline
Definition at line 27 of file StaticSpawnGroup.h.
References coordinate, quaternion, and templateName.
virtual server::zone::managers::creature::SpawnCoordinate::~SpawnCoordinate () inline virtual
Definition at line 33 of file StaticSpawnGroup.h.
Member Function Documentation
Coordinate* server::zone::managers::creature::SpawnCoordinate::getCoordinate () inline
Definition at line 46 of file StaticSpawnGroup.h.
References coordinate.
Referenced by server::zone::objects::creature::aigroup::AiGroupImplementation::setup().
Quaternion* server::zone::managers::creature::SpawnCoordinate::getDirection () inline
Definition at line 50 of file StaticSpawnGroup.h.
References quaternion.
Referenced by server::zone::objects::creature::aigroup::AiGroupImplementation::setup().
String server::zone::managers::creature::SpawnCoordinate::getTemplateName () const inline
Definition at line 62 of file StaticSpawnGroup.h.
References templateName.
Referenced by server::zone::objects::creature::aigroup::AiGroupImplementation::setup().
SpawnCoordinate& server::zone::managers::creature::SpawnCoordinate::operator= (const SpawnCoordinate & cr) inline
Definition at line 35 of file StaticSpawnGroup.h.
References coordinate, quaternion, and templateName.
void server::zone::managers::creature::SpawnCoordinate::set (float a, float b, float c, float d) inline
Definition at line 54 of file StaticSpawnGroup.h.
References quaternion.
Referenced by server::zone::managers::creature::StaticSpawnGroup::StaticSpawnGroup().
void server::zone::managers::creature::SpawnCoordinate::setPosition (float x, float z, float y) inline
Definition at line 58 of file StaticSpawnGroup.h.
References coordinate.
Referenced by server::zone::managers::creature::StaticSpawnGroup::StaticSpawnGroup().
void server::zone::managers::creature::SpawnCoordinate::setTemplateName (String templateName) inline
Definition at line 66 of file StaticSpawnGroup.h.
References templateName.
Referenced by server::zone::managers::creature::StaticSpawnGroup::StaticSpawnGroup().
Member Data Documentation
Coordinate server::zone::managers::creature::SpawnCoordinate::coordinate protected
Definition at line 21 of file StaticSpawnGroup.h.
Referenced by getCoordinate(), operator=(), setPosition(), and SpawnCoordinate().
Quaternion server::zone::managers::creature::SpawnCoordinate::quaternion protected
Definition at line 22 of file StaticSpawnGroup.h.
Referenced by getDirection(), operator=(), set(), and SpawnCoordinate().
String server::zone::managers::creature::SpawnCoordinate::templateName protected
Definition at line 20 of file StaticSpawnGroup.h.
Referenced by getTemplateName(), operator=(), setTemplateName(), and SpawnCoordinate().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/StaticSpawnGroup.h