Core3: server::zone::managers::mission::MissionManagerAdapter Class Reference
server::zone::managers::mission::MissionManagerAdapter Class Reference
#include <MissionManager.h>
Public Member Functions
MissionManagerAdapter (MissionManager *impl)
void invokeMethod (sys::uint32 methid, DistributedMethod *method)
void loadLuaSettings ()
void handleMissionListRequest (MissionTerminal *missionTerminal, CreatureObject *player, int counter)
void handleMissionAccept (MissionTerminal *missionTerminal, MissionObject *mission, CreatureObject *player)
void handleMissionAbort (MissionObject *mission, CreatureObject *player)
void removeMission (MissionObject *mission, CreatureObject *player)
void populateMissionList (MissionTerminal *missionTerminal, CreatureObject *player, int counter)
bool randomGenericDeliverMission (CreatureObject *player, MissionObject *mission, bool inTownMission, const int faction)
void randomizeGenericBountyMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericCraftingMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericDeliverMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericDestroyMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericEntertainerMission (CreatureObject *player, MissionObject *mission, const int faction, const int missionType)
void randomizeGenericHuntingMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericReconMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeGenericSurveyMission (CreatureObject *player, MissionObject *mission, const int faction)
void randomizeSurveyMission (CreatureObject *player, MissionObject *mission)
void randomizeDestroyMission (CreatureObject *player, MissionObject *mission)
void randomizeBountyMission (CreatureObject *player, MissionObject *mission)
void randomizeDeliverMission (CreatureObject *player, MissionObject *mission)
void randomizeCraftingMission (CreatureObject *player, MissionObject *mission)
void randomizeHuntingMission (CreatureObject *player, MissionObject *mission)
void randomizeReconMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialDestroyMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialDeliverMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialCraftingMission (CreatureObject *player, MissionObject *mission)
void randomizeImperialReconMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelDestroyMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelDeliverMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelCraftingMission (CreatureObject *player, MissionObject *mission)
void randomizeRebelReconMission (CreatureObject *player, MissionObject *mission)
void createMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createSurveyMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createDestroyMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createDeliverMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createEntertainerMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createHuntingMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createReconMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createBountyMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
void createCraftingMissionObjectives (MissionObject *mission, MissionTerminal *missionTerminal, CreatureObject *player)
NpcSpawnPoint * getRandomFreeNpcSpawnPoint (unsigned const int planetCRC, const float x, const float y, const int spawnType)
void createSpawnPoint (CreatureObject *player, const String &spawnTypes)
Reference< MissionObject * > getBountyHunterMission (CreatureObject *player)
String getDeliveryMissionFileName (const int faction)
int getDeliverMissionNumberOfMissions (const int faction)
int getDeliverMissionSpawnType (const int faction)
void addPlayerToBountyList (unsigned long long targetId, int reward)
void removePlayerFromBountyList (unsigned long long targetId)
void updatePlayerBountyReward (unsigned long long targetId, int reward)
void addBountyHunterToPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
void removeBountyHunterFromPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
BountyTargetListElement * getRandomPlayerBounty (CreatureObject *player)
void completePlayerBounty (unsigned long long targetId, unsigned long long bountyHunter)
void failPlayerBountyMission (unsigned long long bountyHunter)
void freeMissionNpc (NpcSpawnPoint *npc)
void despawnMissionNpc (NpcSpawnPoint *npc)
void deactivateMissions (CreatureObject *player)
Detailed Description
Definition at line 512 of file MissionManager.h.
Constructor & Destructor Documentation
MissionManagerAdapter::MissionManagerAdapter (MissionManager * impl)
Definition at line 1201 of file MissionManager.cpp.
Member Function Documentation
void MissionManagerAdapter::addBountyHunterToPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
Definition at line 1686 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::addPlayerToBountyList (unsigned long long targetId, int reward)
Definition at line 1674 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::completePlayerBounty (unsigned long long targetId, unsigned long long bountyHunter)
Definition at line 1698 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::createBountyMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 1642 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::createCraftingMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 1646 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::createDeliverMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 1626 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::createDestroyMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 1622 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::createEntertainerMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 1630 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::createHuntingMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 1634 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::createMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 1614 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::createReconMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 1638 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::createSpawnPoint (CreatureObject * player, const String & spawnTypes)
Definition at line 1654 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::createSurveyMissionObjectives (MissionObject * mission, MissionTerminal * missionTerminal, CreatureObject * player)
Definition at line 1618 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::deactivateMissions (CreatureObject * player)
Definition at line 1714 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::despawnMissionNpc (NpcSpawnPoint * npc)
Definition at line 1710 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::failPlayerBountyMission (unsigned long long bountyHunter)
Definition at line 1702 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::freeMissionNpc (NpcSpawnPoint * npc)
Definition at line 1706 of file MissionManager.cpp.
Referenced by invokeMethod().
Reference< MissionObject * > MissionManagerAdapter::getBountyHunterMission (CreatureObject * player)
Definition at line 1658 of file MissionManager.cpp.
Referenced by invokeMethod().
int MissionManagerAdapter::getDeliverMissionNumberOfMissions (const int faction)
Definition at line 1666 of file MissionManager.cpp.
Referenced by invokeMethod().
int MissionManagerAdapter::getDeliverMissionSpawnType (const int faction)
Definition at line 1670 of file MissionManager.cpp.
Referenced by invokeMethod().
String MissionManagerAdapter::getDeliveryMissionFileName (const int faction)
Definition at line 1662 of file MissionManager.cpp.
Referenced by invokeMethod().
NpcSpawnPoint * MissionManagerAdapter::getRandomFreeNpcSpawnPoint (unsigned const int planetCRC, const float x, const float y, const int spawnType)
Definition at line 1650 of file MissionManager.cpp.
Referenced by invokeMethod().
BountyTargetListElement * MissionManagerAdapter::getRandomPlayerBounty (CreatureObject * player)
Definition at line 1694 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::handleMissionAbort (MissionObject * mission, CreatureObject * player)
Definition at line 1506 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::handleMissionAccept (MissionTerminal * missionTerminal, MissionObject * mission, CreatureObject * player)
Definition at line 1502 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::handleMissionListRequest (MissionTerminal * missionTerminal, CreatureObject * player, int counter)
Definition at line 1498 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::invokeMethod (sys::uint32 methid, DistributedMethod * method)
Definition at line 1204 of file MissionManager.cpp.
References addBountyHunterToPlayerBounty(), addPlayerToBountyList(), completePlayerBounty(), createBountyMissionObjectives(), createCraftingMissionObjectives(), createDeliverMissionObjectives(), createDestroyMissionObjectives(), createEntertainerMissionObjectives(), createHuntingMissionObjectives(), createMissionObjectives(), createReconMissionObjectives(), createSpawnPoint(), createSurveyMissionObjectives(), deactivateMissions(), despawnMissionNpc(), failPlayerBountyMission(), freeMissionNpc(), getBountyHunterMission(), getDeliverMissionNumberOfMissions(), getDeliverMissionSpawnType(), getDeliveryMissionFileName(), getRandomFreeNpcSpawnPoint(), getRandomPlayerBounty(), handleMissionAbort(), handleMissionAccept(), handleMissionListRequest(), loadLuaSettings(), populateMissionList(), randomGenericDeliverMission(), randomizeBountyMission(), randomizeCraftingMission(), randomizeDeliverMission(), randomizeDestroyMission(), randomizeGenericBountyMission(), randomizeGenericCraftingMission(), randomizeGenericDeliverMission(), randomizeGenericDestroyMission(), randomizeGenericEntertainerMission(), randomizeGenericHuntingMission(), randomizeGenericReconMission(), randomizeGenericSurveyMission(), randomizeHuntingMission(), randomizeImperialCraftingMission(), randomizeImperialDeliverMission(), randomizeImperialDestroyMission(), randomizeImperialReconMission(), randomizeRebelCraftingMission(), randomizeRebelDeliverMission(), randomizeRebelDestroyMission(), randomizeRebelReconMission(), randomizeReconMission(), randomizeSurveyMission(), removeBountyHunterFromPlayerBounty(), removeMission(), removePlayerFromBountyList(), RPC_ADDBOUNTYHUNTERTOPLAYERBOUNTY__LONG_LONG_, RPC_ADDPLAYERTOBOUNTYLIST__LONG_INT_, RPC_COMPLETEPLAYERBOUNTY__LONG_LONG_, RPC_CREATEBOUNTYMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_, RPC_CREATECRAFTINGMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_, RPC_CREATEDELIVERMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_, RPC_CREATEDESTROYMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_, RPC_CREATEENTERTAINERMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_, RPC_CREATEHUNTINGMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_, RPC_CREATEMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_, RPC_CREATERECONMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_, RPC_CREATESPAWNPOINT__CREATUREOBJECT_STRING_, RPC_CREATESURVEYMISSIONOBJECTIVES__MISSIONOBJECT_MISSIONTERMINAL_CREATUREOBJECT_, RPC_DEACTIVATEMISSIONS__CREATUREOBJECT_, RPC_DESPAWNMISSIONNPC__NPCSPAWNPOINT_, RPC_FAILPLAYERBOUNTYMISSION__LONG_, RPC_FREEMISSIONNPC__NPCSPAWNPOINT_, RPC_GETBOUNTYHUNTERMISSION__CREATUREOBJECT_, RPC_GETDELIVERMISSIONNUMBEROFMISSIONS__INT_, RPC_GETDELIVERMISSIONSPAWNTYPE__INT_, RPC_GETDELIVERYMISSIONFILENAME__INT_, RPC_GETRANDOMFREENPCSPAWNPOINT__INT_FLOAT_FLOAT_INT_, RPC_GETRANDOMPLAYERBOUNTY__CREATUREOBJECT_, RPC_HANDLEMISSIONABORT__MISSIONOBJECT_CREATUREOBJECT_, RPC_HANDLEMISSIONACCEPT__MISSIONTERMINAL_MISSIONOBJECT_CREATUREOBJECT_, RPC_HANDLEMISSIONLISTREQUEST__MISSIONTERMINAL_CREATUREOBJECT_INT_, RPC_LOADLUASETTINGS__, RPC_POPULATEMISSIONLIST__MISSIONTERMINAL_CREATUREOBJECT_INT_, RPC_RANDOMGENERICDELIVERMISSION__CREATUREOBJECT_MISSIONOBJECT_BOOL_INT_, RPC_RANDOMIZEBOUNTYMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZECRAFTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZEDELIVERMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZEDESTROYMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZEGENERICBOUNTYMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_, RPC_RANDOMIZEGENERICCRAFTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_, RPC_RANDOMIZEGENERICDELIVERMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_, RPC_RANDOMIZEGENERICDESTROYMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_, RPC_RANDOMIZEGENERICENTERTAINERMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_INT_, RPC_RANDOMIZEGENERICHUNTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_, RPC_RANDOMIZEGENERICRECONMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_, RPC_RANDOMIZEGENERICSURVEYMISSION__CREATUREOBJECT_MISSIONOBJECT_INT_, RPC_RANDOMIZEHUNTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZEIMPERIALCRAFTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZEIMPERIALDELIVERMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZEIMPERIALDESTROYMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZEIMPERIALRECONMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZEREBELCRAFTINGMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZEREBELDELIVERMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZEREBELDESTROYMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZEREBELRECONMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZERECONMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_RANDOMIZESURVEYMISSION__CREATUREOBJECT_MISSIONOBJECT_, RPC_REMOVEBOUNTYHUNTERFROMPLAYERBOUNTY__LONG_LONG_, RPC_REMOVEMISSION__MISSIONOBJECT_CREATUREOBJECT_, RPC_REMOVEPLAYERFROMBOUNTYLIST__LONG_, RPC_UPDATEPLAYERBOUNTYREWARD__LONG_INT_, and updatePlayerBountyReward().
void MissionManagerAdapter::loadLuaSettings ()
Definition at line 1494 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::populateMissionList (MissionTerminal * missionTerminal, CreatureObject * player, int counter)
Definition at line 1514 of file MissionManager.cpp.
Referenced by invokeMethod().
bool MissionManagerAdapter::randomGenericDeliverMission (CreatureObject * player, MissionObject * mission, bool inTownMission, const int faction)
Definition at line 1518 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeBountyMission (CreatureObject * player, MissionObject * mission)
Definition at line 1562 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeCraftingMission (CreatureObject * player, MissionObject * mission)
Definition at line 1570 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeDeliverMission (CreatureObject * player, MissionObject * mission)
Definition at line 1566 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeDestroyMission (CreatureObject * player, MissionObject * mission)
Definition at line 1558 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeGenericBountyMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 1522 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeGenericCraftingMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 1526 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeGenericDeliverMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 1530 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeGenericDestroyMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 1534 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeGenericEntertainerMission (CreatureObject * player, MissionObject * mission, const int faction, const int missionType)
Definition at line 1538 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeGenericHuntingMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 1542 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeGenericReconMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 1546 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeGenericSurveyMission (CreatureObject * player, MissionObject * mission, const int faction)
Definition at line 1550 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeHuntingMission (CreatureObject * player, MissionObject * mission)
Definition at line 1574 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeImperialCraftingMission (CreatureObject * player, MissionObject * mission)
Definition at line 1590 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeImperialDeliverMission (CreatureObject * player, MissionObject * mission)
Definition at line 1586 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeImperialDestroyMission (CreatureObject * player, MissionObject * mission)
Definition at line 1582 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeImperialReconMission (CreatureObject * player, MissionObject * mission)
Definition at line 1594 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeRebelCraftingMission (CreatureObject * player, MissionObject * mission)
Definition at line 1606 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeRebelDeliverMission (CreatureObject * player, MissionObject * mission)
Definition at line 1602 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeRebelDestroyMission (CreatureObject * player, MissionObject * mission)
Definition at line 1598 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeRebelReconMission (CreatureObject * player, MissionObject * mission)
Definition at line 1610 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeReconMission (CreatureObject * player, MissionObject * mission)
Definition at line 1578 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::randomizeSurveyMission (CreatureObject * player, MissionObject * mission)
Definition at line 1554 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::removeBountyHunterFromPlayerBounty (unsigned long long targetId, unsigned long long bountyHunterId)
Definition at line 1690 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::removeMission (MissionObject * mission, CreatureObject * player)
Definition at line 1510 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::removePlayerFromBountyList (unsigned long long targetId)
Definition at line 1678 of file MissionManager.cpp.
Referenced by invokeMethod().
void MissionManagerAdapter::updatePlayerBountyReward (unsigned long long targetId, int reward)
Definition at line 1682 of file MissionManager.cpp.
Referenced by invokeMethod().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/mission/MissionManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/mission/MissionManager.cpp