Core3: server::zone::managers::creature::CreatureTemplateManager Class Reference
server::zone::managers::creature::CreatureTemplateManager Class Reference
#include <CreatureTemplateManager.h>
Public Types
enum LUA_ERROR_CODE { NO_ERROR = 0, GENERAL_ERROR, DUPLICATE_MOBILE, INCORRECT_ARGUMENTS }
Public Member Functions
CreatureTemplateManager ()
virtual ~CreatureTemplateManager ()
int loadTemplates ()
int size ()
HashTableIterator< uint32,
Reference< CreatureTemplate * > > iterator ()
CreatureTemplate * getTemplate (uint32 crc)
PatrolPathTemplate * getPatrolPathTemplate (const String &name)
CreatureTemplate * getTemplate (const String &ascii)
MobileOutfitGroup * getMobileOutfitGroup (const String &name)
ConversationTemplate * getConversationTemplate (const String &name)
ConversationTemplate * getConversationTemplate (uint32 crc)
Vector< String > getWeapons (uint32 crc)
Vector< String > getWeapons (String ascii)
DynamicSpawnGroup * getDynamicGroup (uint32 crc)
DynamicSpawnGroup * getDynamicGroup (String ascii)
StaticSpawnGroup * getStaticGroup (uint32 crc)
LairSpawnGroup * getLairGroup (uint32 crc)
StaticSpawnGroup * getStaticGroup (String ascii)
LairTemplate * getLairTemplate (uint32 crc)
Static Public Member Functions
static int includeFile (lua_State *L)
static int addTemplate (lua_State *L)
static int addWeapon (lua_State *L)
static int addDynamicGroup (lua_State *L)
static int addStaticGroup (lua_State *L)
static int addConversationTemplate (lua_State *L)
static int addLairTemplate (lua_State *L)
static int addLairGroup (lua_State *L)
static int addPatrolPathTemplate (lua_State *L)
static int addOutfitGroup (lua_State *L)
static int checkArgumentCount (lua_State *L, int args)
Static Public Attributes
static int DEBUG_MODE = 0
static int ERROR_CODE = NO_ERROR
Protected Attributes
VectorMap< uint32, Vector
< String > > weaponMap
VectorMap< uint32, Reference
< DynamicSpawnGroup * > > dynamicGroupMap
VectorMap< uint32, Reference
< StaticSpawnGroup * > > staticGroupMap
Reference< Lua * > lua
HashTable< uint32, Reference
< CreatureTemplate * > > hashTable
HashTable< uint32, Reference
< ConversationTemplate * > > conversations
HashTable< uint32, Reference
< LairTemplate * > > lairTemplates
HashTable< uint32, Reference
< LairSpawnGroup * > > lairSpawnGroupMap
HashTable< String, Reference
< PatrolPathTemplate * > > patrolPaths
HashTable< String, Reference
< MobileOutfitGroup * > > outfits
Static Protected Attributes
static AtomicInteger loadedMobileTemplates
Detailed Description
Definition at line 27 of file CreatureTemplateManager.h.
Member Enumeration Documentation
enum server::zone::managers::creature::CreatureTemplateManager::LUA_ERROR_CODE
Enumerator
NO_ERROR
GENERAL_ERROR
DUPLICATE_MOBILE
INCORRECT_ARGUMENTS
Definition at line 45 of file CreatureTemplateManager.h.
Constructor & Destructor Documentation
CreatureTemplateManager::CreatureTemplateManager ()
Definition at line 17 of file CreatureTemplateManager.cpp.
References addConversationTemplate(), addDynamicGroup(), addLairGroup(), addLairTemplate(), addOutfitGroup(), addPatrolPathTemplate(), addStaticGroup(), addTemplate(), addWeapon(), CreatureFlag::AGGRESSIVE, CreatureFlag::ATTACKABLE, CreatureFlag::BABY, CreatureFlag::BLINK_GREEN, CreatureFlag::CARNIVORE, CreatureFlag::CHANGEFACTIONSTATUS, DEBUG_MODE, CreatureFlag::ENEMY, hashTable, CreatureFlag::HEALER, CreatureFlag::HERBIVORE, CreatureFlag::HERD, includeFile(), CreatureFlag::KILLER, CreatureFlag::LAIR, lua, CreatureFlag::NONE, CreatureFlag::OVERT, CreatureFlag::PACK, CreatureFlag::PLAYER, CreatureFlag::STALKER, and CreatureFlag::TEF.
CreatureTemplateManager::~CreatureTemplateManager () virtual
Definition at line 65 of file CreatureTemplateManager.cpp.
Member Function Documentation
int CreatureTemplateManager::addConversationTemplate (lua_State * L) static
Definition at line 168 of file CreatureTemplateManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by CreatureTemplateManager().
int CreatureTemplateManager::addDynamicGroup (lua_State * L) static
Definition at line 209 of file CreatureTemplateManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by CreatureTemplateManager().
int CreatureTemplateManager::addLairGroup (lua_State * L) static
Definition at line 241 of file CreatureTemplateManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by CreatureTemplateManager().
int CreatureTemplateManager::addLairTemplate (lua_State * L) static
Definition at line 257 of file CreatureTemplateManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by CreatureTemplateManager().
int CreatureTemplateManager::addOutfitGroup (lua_State * L) static
Definition at line 296 of file CreatureTemplateManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by CreatureTemplateManager().
int CreatureTemplateManager::addPatrolPathTemplate (lua_State * L) static
Definition at line 277 of file CreatureTemplateManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by CreatureTemplateManager().
int CreatureTemplateManager::addStaticGroup (lua_State * L) static
Definition at line 225 of file CreatureTemplateManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by CreatureTemplateManager().
int CreatureTemplateManager::addTemplate (lua_State * L) static
Definition at line 132 of file CreatureTemplateManager.cpp.
References checkArgumentCount(), DEBUG_MODE, DUPLICATE_MOBILE, ERROR_CODE, hashTable, INCORRECT_ARGUMENTS, loadedMobileTemplates, server::zone::templates::mobile::CreatureTemplate::readObject(), and server::zone::templates::mobile::CreatureTemplate::setTemplateName().
Referenced by CreatureTemplateManager().
int CreatureTemplateManager::addWeapon (lua_State * L) static
Definition at line 187 of file CreatureTemplateManager.cpp.
References checkArgumentCount(), ERROR_CODE, and INCORRECT_ARGUMENTS.
Referenced by CreatureTemplateManager().
int CreatureTemplateManager::checkArgumentCount (lua_State * L, int args) static
Definition at line 95 of file CreatureTemplateManager.cpp.
Referenced by addConversationTemplate(), addDynamicGroup(), addLairGroup(), addLairTemplate(), addOutfitGroup(), addPatrolPathTemplate(), addStaticGroup(), addTemplate(), addWeapon(), and includeFile().
ConversationTemplate* server::zone::managers::creature::CreatureTemplateManager::getConversationTemplate (const String & name) inline
Definition at line 90 of file CreatureTemplateManager.h.
References conversations.
ConversationTemplate* server::zone::managers::creature::CreatureTemplateManager::getConversationTemplate (uint32 crc) inline
Definition at line 94 of file CreatureTemplateManager.h.
References conversations.
DynamicSpawnGroup* server::zone::managers::creature::CreatureTemplateManager::getDynamicGroup (uint32 crc) inline
Definition at line 106 of file CreatureTemplateManager.h.
References dynamicGroupMap.
DynamicSpawnGroup* server::zone::managers::creature::CreatureTemplateManager::getDynamicGroup (String ascii) inline
Definition at line 110 of file CreatureTemplateManager.h.
References dynamicGroupMap.
LairSpawnGroup* server::zone::managers::creature::CreatureTemplateManager::getLairGroup (uint32 crc) inline
Definition at line 118 of file CreatureTemplateManager.h.
References lairSpawnGroupMap.
LairTemplate* server::zone::managers::creature::CreatureTemplateManager::getLairTemplate (uint32 crc) inline
Definition at line 126 of file CreatureTemplateManager.h.
References lairTemplates.
MobileOutfitGroup* server::zone::managers::creature::CreatureTemplateManager::getMobileOutfitGroup (const String & name) inline
Definition at line 86 of file CreatureTemplateManager.h.
References outfits.
PatrolPathTemplate* server::zone::managers::creature::CreatureTemplateManager::getPatrolPathTemplate (const String & name) inline
Definition at line 78 of file CreatureTemplateManager.h.
References patrolPaths.
StaticSpawnGroup* server::zone::managers::creature::CreatureTemplateManager::getStaticGroup (uint32 crc) inline
Definition at line 114 of file CreatureTemplateManager.h.
References staticGroupMap.
StaticSpawnGroup* server::zone::managers::creature::CreatureTemplateManager::getStaticGroup (String ascii) inline
Definition at line 122 of file CreatureTemplateManager.h.
References staticGroupMap.
CreatureTemplate* server::zone::managers::creature::CreatureTemplateManager::getTemplate (uint32 crc) inline
Definition at line 74 of file CreatureTemplateManager.h.
References hashTable.
CreatureTemplate* server::zone::managers::creature::CreatureTemplateManager::getTemplate (const String & ascii) inline
Definition at line 82 of file CreatureTemplateManager.h.
References hashTable.
Vector<String> server::zone::managers::creature::CreatureTemplateManager::getWeapons (uint32 crc) inline
Definition at line 98 of file CreatureTemplateManager.h.
References weaponMap.
Vector<String> server::zone::managers::creature::CreatureTemplateManager::getWeapons (String ascii) inline
Definition at line 102 of file CreatureTemplateManager.h.
References weaponMap.
int CreatureTemplateManager::includeFile (lua_State * L) static
Definition at line 106 of file CreatureTemplateManager.cpp.
References checkArgumentCount(), ERROR_CODE, GENERAL_ERROR, and INCORRECT_ARGUMENTS.
Referenced by CreatureTemplateManager().
HashTableIterator<uint32, Reference<CreatureTemplate*> > server::zone::managers::creature::CreatureTemplateManager::iterator () inline
Definition at line 70 of file CreatureTemplateManager.h.
References hashTable.
int CreatureTemplateManager::loadTemplates ()
Definition at line 68 of file CreatureTemplateManager.cpp.
References DEBUG_MODE, ERROR_CODE, GENERAL_ERROR, and lua.
int server::zone::managers::creature::CreatureTemplateManager::size () inline
Definition at line 66 of file CreatureTemplateManager.h.
References hashTable.
Member Data Documentation
HashTable<uint32, Reference<ConversationTemplate*> > server::zone::managers::creature::CreatureTemplateManager::conversations protected
Definition at line 35 of file CreatureTemplateManager.h.
Referenced by getConversationTemplate().
int CreatureTemplateManager::DEBUG_MODE = 0 static
Definition at line 44 of file CreatureTemplateManager.h.
Referenced by addTemplate(), CreatureTemplateManager(), and loadTemplates().
VectorMap<uint32, Reference<DynamicSpawnGroup*> > server::zone::managers::creature::CreatureTemplateManager::dynamicGroupMap protected
Definition at line 30 of file CreatureTemplateManager.h.
Referenced by getDynamicGroup().
int CreatureTemplateManager::ERROR_CODE = NO_ERROR static
Definition at line 46 of file CreatureTemplateManager.h.
Referenced by addConversationTemplate(), addDynamicGroup(), addLairGroup(), addLairTemplate(), addOutfitGroup(), addPatrolPathTemplate(), addStaticGroup(), addTemplate(), addWeapon(), includeFile(), and loadTemplates().
HashTable<uint32, Reference<CreatureTemplate*> > server::zone::managers::creature::CreatureTemplateManager::hashTable protected
Definition at line 33 of file CreatureTemplateManager.h.
Referenced by addTemplate(), CreatureTemplateManager(), getTemplate(), iterator(), and size().
HashTable<uint32, Reference<LairSpawnGroup*> > server::zone::managers::creature::CreatureTemplateManager::lairSpawnGroupMap protected
Definition at line 38 of file CreatureTemplateManager.h.
Referenced by getLairGroup().
HashTable<uint32, Reference<LairTemplate*> > server::zone::managers::creature::CreatureTemplateManager::lairTemplates protected
Definition at line 37 of file CreatureTemplateManager.h.
Referenced by getLairTemplate().
AtomicInteger CreatureTemplateManager::loadedMobileTemplates static protected
Definition at line 41 of file CreatureTemplateManager.h.
Referenced by addTemplate().
Reference<Lua*> server::zone::managers::creature::CreatureTemplateManager::lua protected
Definition at line 32 of file CreatureTemplateManager.h.
Referenced by CreatureTemplateManager(), and loadTemplates().
HashTable<String, Reference<MobileOutfitGroup*> > server::zone::managers::creature::CreatureTemplateManager::outfits protected
Definition at line 40 of file CreatureTemplateManager.h.
Referenced by getMobileOutfitGroup().
HashTable<String, Reference<PatrolPathTemplate*> > server::zone::managers::creature::CreatureTemplateManager::patrolPaths protected
Definition at line 39 of file CreatureTemplateManager.h.
Referenced by getPatrolPathTemplate().
VectorMap<uint32, Reference<StaticSpawnGroup*> > server::zone::managers::creature::CreatureTemplateManager::staticGroupMap protected
Definition at line 31 of file CreatureTemplateManager.h.
Referenced by getStaticGroup().
VectorMap<uint32, Vector<String> > server::zone::managers::creature::CreatureTemplateManager::weaponMap protected
Definition at line 29 of file CreatureTemplateManager.h.
Referenced by getWeapons().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/CreatureTemplateManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/CreatureTemplateManager.cpp