Core3: server::zone::objects::manufactureschematic::craftingvalues::CraftingValues Class Reference
server::zone::objects::manufactureschematic::craftingvalues::CraftingValues Class Reference
#include <CraftingValues.h>
Public Member Functions
CraftingValues ()
CraftingValues (const CraftingValues &values)
~CraftingValues ()
void setManufactureSchematic (ManufactureSchematic *manu)
ManufactureSchematic * getManufactureSchematic ()
void setPlayer (CreatureObject *play)
CreatureObject * getPlayer ()
void addExperimentalProperty (const String &title, const String &subtitle, const float min, const float max, const int precision, const bool filler, const int combine)
String & getExperimentalPropertyTitle (const String &subtitle)
String & getExperimentalPropertyTitle (const int i)
String & getVisibleExperimentalPropertyTitle (const int i)
String & getExperimentalPropertySubtitlesTitle (const int i)
String & getExperimentalPropertySubtitle (const int i)
String & getExperimentalPropertySubtitle (const String title, const int i)
int getExperimentalPropertySubtitleSize ()
int getExperimentalPropertySubtitleSize (const String title)
bool hasProperty (const String &attribute)
bool isHidden (const String &attribute)
void setHidden (const String &attribute)
void unsetHidden (const String &attribute)
short getCombineType (const String &attribute)
void setCurrentValue (const String &attribute, const float value)
void setCurrentValue (const String &attribute, const float value, const float min, const float max)
float getCurrentValue (const String &attribute)
float getCurrentValue (const int i)
void unlockValue (const String &attribute)
void lockValue (const String &attribute)
void resetValue (const String &attribute)
void setCurrentPercentage (const String &subtitle, const float value)
void setCurrentPercentage (const String &subtitle, const float value, const float min, const float max)
float getCurrentPercentage (const String &attribute)
float getCurrentPercentage (const int i)
float getCurrentVisiblePercentage (const String title)
void setMaxPercentage (const String &attribute, const float value)
float getMaxPercentage (const String &attribute)
float getMaxPercentage (const int i)
float getMaxVisiblePercentage (const int i)
float getMinValue (const String &attribute)
float getMaxValue (const String &attribute)
void setMinValue (const String &attribute, const float value)
void setMaxValue (const String &attribute, const float value)
int getPrecision (const String &attribute)
void setPrecision (const String &attribute, const int precision)
void recalculateValues (bool initial)
String toString ()
int getExperimentalPropertyTitleSize ()
void setSlot (const String &value, bool filled)
void clearSlots ()
bool hasSlotFilled (const String &name)
int getVisibleExperimentalPropertyTitleSize ()
int getSubtitleCount ()
int getValuesToSendSize ()
int getTitleLine (String &title)
String & getValuesToSend (const int i)
float getAttributeAndValue (String &attribute, const int i)
void clear ()
void clearAll ()
Static Public Attributes
static float VALUENOTFOUND = -999999
static const int NORMAL = 1
static const int HIDDEN = 2
Private Attributes
VectorMap< String, Reference
< Subclasses * > > experimentalValuesMap
Vector< String > valuesToSend
String EMPTY
bool doHide
ManagedReference
< ManufactureSchematic * > schematic
ManagedReference
< CreatureObject * > player
VectorMap< String, bool > slots
Detailed Description
Definition at line 86 of file CraftingValues.h.
Constructor & Destructor Documentation
CraftingValues::CraftingValues ()
Definition at line 50 of file CraftingValues.cpp.
References doHide, EMPTY, and experimentalValuesMap.
CraftingValues::CraftingValues (const CraftingValues & values)
Definition at line 59 of file CraftingValues.cpp.
References doHide, EMPTY, experimentalValuesMap, Subclasses::getValue(), and valuesToSend.
CraftingValues::~CraftingValues ()
Definition at line 79 of file CraftingValues.cpp.
Member Function Documentation
void CraftingValues::addExperimentalProperty (const String & title, const String & subtitle, const float min, const float max, const int precision, const bool filler, const int combine)
Definition at line 100 of file CraftingValues.cpp.
References Subclasses::addSubtitle(), and experimentalValuesMap.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), server::zone::managers::loot::LootManagerImplementation::createLootObject(), LootItemTemplate::readObject(), server::zone::managers::crafting::labratories::ResourceLabratory::setInitialCraftingValues(), server::zone::managers::crafting::labratories::GeneticLabratory::setInitialCraftingValues(), and server::zone::managers::loot::LootManagerImplementation::setInitialObjectStats().
void server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::clear () inline
Definition at line 268 of file CraftingValues.h.
void CraftingValues::clearAll ()
Definition at line 866 of file CraftingValues.cpp.
References clearSlots(), doHide, experimentalValuesMap, player, schematic, and valuesToSend.
void server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::clearSlots () inline
Definition at line 191 of file CraftingValues.h.
Referenced by clearAll().
float server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getAttributeAndValue (String & attribute, const int i) inline
Definition at line 259 of file CraftingValues.h.
short CraftingValues::getCombineType (const String & attribute)
Definition at line 802 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getCombineType(), Values::getName(), Subclasses::size(), and VALUENOTFOUND.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats().
float CraftingValues::getCurrentPercentage (const String & attribute)
Definition at line 525 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::getPercentage(), Subclasses::size(), and VALUENOTFOUND.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::experimentRow(), server::zone::managers::crafting::labratories::GeneticLabratory::experimentRow(), recalculateValues(), and server::zone::objects::tangible::consumable::ConsumableImplementation::updateCraftingValues().
float CraftingValues::getCurrentPercentage (const int i)
Definition at line 547 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getPercentage(), Subclasses::size(), and VALUENOTFOUND.
float CraftingValues::getCurrentValue (const String & attribute)
Definition at line 367 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::getValue(), Subclasses::size(), and VALUENOTFOUND.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), server::zone::objects::tangible::component::armor::ArmorComponentImplementation::calculateSpecialProtection(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::calculateSpecialProtection(), server::zone::managers::loot::LootManagerImplementation::createLootObject(), recalculateValues(), server::zone::managers::loot::LootManagerImplementation::setSockets(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::updateCraftingValues(), server::zone::objects::tangible::component::armor::ArmorComponentImplementation::updateCraftingValues(), server::zone::objects::tangible::deed::structure::StructureDeedImplementation::updateCraftingValues(), server::zone::objects::tangible::wearables::WearableObjectImplementation::updateCraftingValues(), server::zone::objects::tangible::tool::repair::RepairToolImplementation::updateCraftingValues(), server::zone::objects::tangible::firework::FireworkObjectImplementation::updateCraftingValues(), server::zone::objects::tangible::deed::vehicle::VehicleDeedImplementation::updateCraftingValues(), server::zone::objects::tangible::fishing::FishingPoleObjectImplementation::updateCraftingValues(), server::zone::objects::tangible::component::ComponentImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::updateCraftingValues(), server::zone::objects::tangible::tool::CraftingStationImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::StimPackImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::updateCraftingValues(), server::zone::objects::tangible::tool::smuggler::SlicingToolImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::WoundPackImplementation::updateCraftingValues(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::DotPackImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::EnhancePackImplementation::updateCraftingValues(), server::zone::objects::tangible::component::genetic::GeneticComponentImplementation::updateCraftingValues(), server::zone::objects::tangible::wearables::ArmorObjectImplementation::updateCraftingValues(), server::zone::objects::tangible::consumable::ConsumableImplementation::updateCraftingValues(), server::zone::objects::tangible::tool::CraftingToolImplementation::updateCraftingValues(), server::zone::objects::tangible::weapon::WeaponObjectImplementation::updateCraftingValues(), and server::zone::objects::tangible::TangibleObjectImplementation::updateCraftingValues().
float CraftingValues::getCurrentValue (const int i)
Definition at line 389 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getValue(), Subclasses::size(), and VALUENOTFOUND.
float CraftingValues::getCurrentVisiblePercentage (const String title)
Definition at line 568 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getMaxPercentage(), Values::getMaxValue(), Values::getMinValue(), Values::getPercentage(), Values::isFiller(), and Subclasses::size().
String & CraftingValues::getExperimentalPropertySubtitle (const int i)
Definition at line 187 of file CraftingValues.cpp.
References EMPTY, experimentalValuesMap, Subclasses::get(), Values::getName(), and Subclasses::size().
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootObject(), server::zone::managers::crafting::labratories::ResourceLabratory::experimentRow(), server::zone::managers::crafting::labratories::GeneticLabratory::experimentRow(), recalculateValues(), and server::zone::objects::tangible::component::ComponentImplementation::updateCraftingValues().
String & CraftingValues::getExperimentalPropertySubtitle (const String title, const int i)
Definition at line 208 of file CraftingValues.cpp.
References EMPTY, experimentalValuesMap, Subclasses::get(), and Values::getName().
int CraftingValues::getExperimentalPropertySubtitleSize ()
Definition at line 219 of file CraftingValues.cpp.
References experimentalValuesMap, and Subclasses::size().
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootObject(), server::zone::managers::crafting::labratories::ResourceLabratory::experimentRow(), server::zone::managers::crafting::labratories::GeneticLabratory::experimentRow(), and server::zone::objects::tangible::component::ComponentImplementation::updateCraftingValues().
int CraftingValues::getExperimentalPropertySubtitleSize (const String title)
Definition at line 232 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::size(), and VALUENOTFOUND.
String & CraftingValues::getExperimentalPropertySubtitlesTitle (const int i)
Definition at line 170 of file CraftingValues.cpp.
References EMPTY, experimentalValuesMap, Subclasses::getClassTitle(), and Subclasses::size().
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::experimentRow(), and server::zone::managers::crafting::labratories::GeneticLabratory::experimentRow().
String & CraftingValues::getExperimentalPropertyTitle (const String & subtitle)
Definition at line 115 of file CraftingValues.cpp.
References EMPTY, experimentalValuesMap, Subclasses::get(), Subclasses::getClassTitle(), Values::getName(), and Subclasses::size().
Referenced by recalculateValues(), and server::zone::objects::tangible::component::ComponentImplementation::updateCraftingValues().
String & CraftingValues::getExperimentalPropertyTitle (const int i)
Definition at line 136 of file CraftingValues.cpp.
References EMPTY, experimentalValuesMap, and Subclasses::getClassTitle().
int server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertyTitleSize () inline
Definition at line 183 of file CraftingValues.h.
ManufactureSchematic * CraftingValues::getManufactureSchematic ()
Definition at line 88 of file CraftingValues.cpp.
References schematic.
Referenced by server::zone::objects::tangible::wearables::WearableObjectImplementation::generateSockets().
float CraftingValues::getMaxPercentage (const String & attribute)
Definition at line 619 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getMaxPercentage(), Values::getName(), Subclasses::size(), and VALUENOTFOUND.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::experimentRow(), and server::zone::managers::crafting::labratories::GeneticLabratory::experimentRow().
float CraftingValues::getMaxPercentage (const int i)
Definition at line 641 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getMaxPercentage(), Subclasses::size(), and VALUENOTFOUND.
float CraftingValues::getMaxValue (const String & attribute)
Definition at line 688 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getMaxValue(), Values::getName(), Subclasses::size(), and VALUENOTFOUND.
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), server::zone::managers::loot::LootManagerImplementation::createLootObject(), server::zone::managers::crafting::labratories::GeneticLabratory::experimentRow(), recalculateValues(), server::zone::objects::tangible::powerup::PowerupObjectImplementation::updateCraftingValues(), server::zone::objects::tangible::attachement::AttachmentImplementation::updateCraftingValues(), server::zone::objects::tangible::component::lightsaber::LightsaberCrystalComponentImplementation::updateCraftingValues(), and server::zone::objects::tangible::wearables::ArmorObjectImplementation::updateCraftingValues().
float CraftingValues::getMaxVisiblePercentage (const int i)
Definition at line 662 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getMaxPercentage(), Values::getMaxValue(), Values::getMinValue(), getVisibleExperimentalPropertyTitle(), Values::isFiller(), and Subclasses::size().
float CraftingValues::getMinValue (const String & attribute)
Definition at line 708 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getMinValue(), Values::getName(), Subclasses::size(), and VALUENOTFOUND.
Referenced by server::zone::managers::loot::LootManagerImplementation::addConditionDamage(), server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), server::zone::managers::loot::LootManagerImplementation::createLootObject(), recalculateValues(), and server::zone::objects::tangible::wearables::ArmorObjectImplementation::updateCraftingValues().
CreatureObject * CraftingValues::getPlayer ()
Definition at line 96 of file CraftingValues.cpp.
References player.
int CraftingValues::getPrecision (const String & attribute)
Definition at line 764 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::getPrecision(), Subclasses::size(), and VALUENOTFOUND.
Referenced by server::zone::objects::tangible::component::ComponentImplementation::updateCraftingValues().
int server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getSubtitleCount () inline
Definition at line 215 of file CraftingValues.h.
References Subclasses::get(), and Subclasses::size().
Referenced by recalculateValues().
int server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getTitleLine (String & title) inline
Definition at line 232 of file CraftingValues.h.
References Subclasses::get(), Subclasses::getClassTitle(), and Subclasses::isClassHidden().
String& server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getValuesToSend (const int i) inline
Definition at line 255 of file CraftingValues.h.
int server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getValuesToSendSize () inline
Definition at line 228 of file CraftingValues.h.
String & CraftingValues::getVisibleExperimentalPropertyTitle (const int i)
Definition at line 150 of file CraftingValues.cpp.
References EMPTY, experimentalValuesMap, Subclasses::getClassTitle(), and Subclasses::hasAllHiddenItems().
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::experimentRow(), server::zone::managers::crafting::labratories::GeneticLabratory::experimentRow(), and getMaxVisiblePercentage().
int server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getVisibleExperimentalPropertyTitleSize () inline
Definition at line 202 of file CraftingValues.h.
References Subclasses::get(), and Subclasses::hasAllHiddenItems().
bool CraftingValues::hasProperty (const String & attribute)
Definition at line 243 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), and Subclasses::size().
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), server::zone::managers::loot::LootManagerImplementation::createLootObject(), server::zone::managers::loot::LootManagerImplementation::setInitialObjectStats(), server::zone::managers::loot::LootManagerImplementation::setSockets(), server::zone::objects::tangible::wearables::WearableObjectImplementation::updateCraftingValues(), server::zone::objects::tangible::firework::FireworkObjectImplementation::updateCraftingValues(), server::zone::objects::tangible::component::ComponentImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::CurePackImplementation::updateCraftingValues(), server::zone::objects::tangible::pharmaceutical::RangedStimPackImplementation::updateCraftingValues(), server::zone::objects::tangible::consumable::ConsumableImplementation::updateCraftingValues(), and server::zone::objects::tangible::TangibleObjectImplementation::updateCraftingValues().
bool server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::hasSlotFilled (const String & name) inline
Definition at line 195 of file CraftingValues.h.
bool CraftingValues::isHidden (const String & attribute)
Definition at line 263 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::isFiller(), and Subclasses::size().
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), recalculateValues(), and server::zone::objects::tangible::component::ComponentImplementation::updateCraftingValues().
void CraftingValues::lockValue (const String & attribute)
Definition at line 410 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::lockValue(), and Subclasses::size().
void CraftingValues::recalculateValues (bool initial)
Definition at line 822 of file CraftingValues.cpp.
References getCurrentPercentage(), getCurrentValue(), getExperimentalPropertySubtitle(), getExperimentalPropertyTitle(), getMaxValue(), getMinValue(), getSubtitleCount(), isHidden(), setCurrentValue(), and valuesToSend.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootObject(), server::zone::managers::crafting::labratories::ResourceLabratory::setInitialCraftingValues(), and server::zone::managers::crafting::labratories::GeneticLabratory::setInitialCraftingValues().
void CraftingValues::resetValue (const String & attribute)
Definition at line 448 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::resetValue(), and Subclasses::size().
void CraftingValues::setCurrentPercentage (const String & subtitle, const float value)
Definition at line 467 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getMaxPercentage(), Values::getName(), Values::setPercentage(), and Subclasses::size().
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), server::zone::managers::loot::LootManagerImplementation::createLootObject(), server::zone::managers::crafting::labratories::ResourceLabratory::experimentRow(), server::zone::managers::crafting::labratories::GeneticLabratory::experimentRow(), server::zone::objects::tangible::component::genetic::GeneticComponentImplementation::resetResists(), server::zone::managers::crafting::labratories::ResourceLabratory::setInitialCraftingValues(), and server::zone::managers::crafting::labratories::GeneticLabratory::setInitialCraftingValues().
void CraftingValues::setCurrentPercentage (const String & subtitle, const float value, const float min, const float max)
Definition at line 496 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::setMaxValue(), Values::setMinValue(), Values::setPercentage(), and Subclasses::size().
void CraftingValues::setCurrentValue (const String & attribute, const float value)
Definition at line 321 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::setValue(), and Subclasses::size().
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), server::zone::managers::loot::LootManagerImplementation::createLootObject(), recalculateValues(), and server::zone::objects::tangible::component::genetic::GeneticComponentImplementation::resetResists().
void CraftingValues::setCurrentValue (const String & attribute, const float value, const float min, const float max)
Definition at line 342 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::setMaxValue(), Values::setMinValue(), Values::setValue(), and Subclasses::size().
void CraftingValues::setHidden (const String & attribute)
Definition at line 283 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::setFiller(), and Subclasses::size().
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootObject(), server::zone::managers::loot::LootManagerImplementation::setInitialObjectStats(), server::zone::objects::tangible::pharmaceutical::StatePackImplementation::updateCraftingValues(), and server::zone::objects::tangible::pharmaceutical::RevivePackImplementation::updateCraftingValues().
void CraftingValues::setManufactureSchematic (ManufactureSchematic * manu)
Definition at line 84 of file CraftingValues.cpp.
References schematic.
void CraftingValues::setMaxPercentage (const String & attribute, const float value)
Definition at line 596 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::setMaxPercentage(), and Subclasses::size().
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), LootItemTemplate::readObject(), server::zone::managers::crafting::labratories::ResourceLabratory::setInitialCraftingValues(), and server::zone::managers::crafting::labratories::GeneticLabratory::setInitialCraftingValues().
void CraftingValues::setMaxValue (const String & attribute, const float value)
Definition at line 746 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::setMaxValue(), and Subclasses::size().
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), and server::zone::managers::loot::LootManagerImplementation::createLootObject().
void CraftingValues::setMinValue (const String & attribute, const float value)
Definition at line 728 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::setMinValue(), and Subclasses::size().
Referenced by server::zone::managers::crafting::labratories::ResourceLabratory::applyComponentStats(), and server::zone::managers::loot::LootManagerImplementation::createLootObject().
void CraftingValues::setPlayer (CreatureObject * play)
Definition at line 92 of file CraftingValues.cpp.
References player.
void CraftingValues::setPrecision (const String & attribute, const int precision)
Definition at line 784 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::setPrecision(), and Subclasses::size().
void server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setSlot (const String & value, bool filled) inline
Definition at line 187 of file CraftingValues.h.
String CraftingValues::toString ()
Definition at line 875 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::getClassTitle(), and Subclasses::toString().
void CraftingValues::unlockValue (const String & attribute)
Definition at line 429 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Subclasses::size(), and Values::unlockValue().
void CraftingValues::unsetHidden (const String & attribute)
Definition at line 302 of file CraftingValues.cpp.
References experimentalValuesMap, Subclasses::get(), Values::getName(), Values::setFiller(), and Subclasses::size().
Member Data Documentation
bool server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::doHide private
Definition at line 93 of file CraftingValues.h.
Referenced by clearAll(), and CraftingValues().
String server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::EMPTY private
Definition at line 91 of file CraftingValues.h.
Referenced by CraftingValues(), getExperimentalPropertySubtitle(), getExperimentalPropertySubtitlesTitle(), getExperimentalPropertyTitle(), and getVisibleExperimentalPropertyTitle().
VectorMap<String, Reference<Subclasses*> > server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::experimentalValuesMap private
Definition at line 87 of file CraftingValues.h.
Referenced by addExperimentalProperty(), clearAll(), CraftingValues(), getCombineType(), getCurrentPercentage(), getCurrentValue(), getCurrentVisiblePercentage(), getExperimentalPropertySubtitle(), getExperimentalPropertySubtitleSize(), getExperimentalPropertySubtitlesTitle(), getExperimentalPropertyTitle(), getMaxPercentage(), getMaxValue(), getMaxVisiblePercentage(), getMinValue(), getPrecision(), getVisibleExperimentalPropertyTitle(), hasProperty(), isHidden(), lockValue(), resetValue(), setCurrentPercentage(), setCurrentValue(), setHidden(), setMaxPercentage(), setMaxValue(), setMinValue(), setPrecision(), toString(), unlockValue(), and unsetHidden().
const int server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::HIDDEN = 2 static
Definition at line 104 of file CraftingValues.h.
const int server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::NORMAL = 1 static
Definition at line 103 of file CraftingValues.h.
ManagedReference<CreatureObject*> server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::player private
Definition at line 96 of file CraftingValues.h.
Referenced by clearAll(), getPlayer(), and setPlayer().
ManagedReference<ManufactureSchematic*> server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::schematic private
Definition at line 95 of file CraftingValues.h.
Referenced by clearAll(), getManufactureSchematic(), and setManufactureSchematic().
VectorMap<String, bool> server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::slots private
Definition at line 97 of file CraftingValues.h.
float CraftingValues::VALUENOTFOUND = -999999 static
Definition at line 101 of file CraftingValues.h.
Referenced by getCombineType(), getCurrentPercentage(), getCurrentValue(), getExperimentalPropertySubtitleSize(), getMaxPercentage(), getMaxValue(), getMinValue(), and getPrecision().
Vector<String> server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::valuesToSend private
Definition at line 89 of file CraftingValues.h.
Referenced by clearAll(), CraftingValues(), and recalculateValues().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/craftingvalues/CraftingValues.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/manufactureschematic/craftingvalues/CraftingValues.cpp