Core3: server::zone::objects::creature::conversation::screenhandlers::TrainerCanLearnSkillScreenHandler Class Reference
server::zone::objects::creature::conversation::screenhandlers::TrainerCanLearnSkillScreenHandler Class Reference
#include <TrainerScreenHandlers.h>
Public Member Functions
TrainerCanLearnSkillScreenHandler ()
ConversationScreen * handleScreen (CreatureObject *conversingPlayer, CreatureObject *conversingNPC, int selectedOption, ConversationScreen *conversationScreen)
Public Member Functions inherited from server::zone::objects::creature::conversation::screenhandlers::ScreenHandler
ScreenHandler ()
~ScreenHandler ()
String getNextScreenId ()
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::creature::conversation::screenhandlers::ScreenHandler
String nextScreenId
Detailed Description
Definition at line 87 of file TrainerScreenHandlers.h.
Constructor & Destructor Documentation
server::zone::objects::creature::conversation::screenhandlers::TrainerCanLearnSkillScreenHandler::TrainerCanLearnSkillScreenHandler () inline
Definition at line 89 of file TrainerScreenHandlers.h.
Member Function Documentation
ConversationScreen * TrainerCanLearnSkillScreenHandler::handleScreen (CreatureObject * conversingPlayer, CreatureObject * conversingNPC, int selectedOption, ConversationScreen * conversationScreen) virtual
Implements server::zone::objects::creature::conversation::screenhandlers::ScreenHandler.
Definition at line 276 of file TrainerScreenHandlers.cpp.
References SessionFacadeType::CONVERSATION, server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::ERRORSCREENHANDLERID, server::zone::objects::scene::SceneObject::getActiveSession(), Skill::getMoneyRequired(), Skill::getSkillName(), server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::INFOSCREENHANDLERID, server::zone::objects::creature::conversation::screenhandlers::ScreenHandler::nextScreenId, server::zone::objects::creature::conversation::screenhandlers::TrainerScreenHandlers::NONEXISTINGSCREENHANDLERID, server::chat::StringIdChatParameter::setDI(), server::zone::templates::mobile::ConversationScreen::setDialogText(), and server::chat::StringIdChatParameter::setTO().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/screenhandlers/TrainerScreenHandlers.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/conversation/screenhandlers/TrainerScreenHandlers.cpp