Core3: Boundary Class Reference
Boundary Class Reference abstract
#include <Boundary.h>
Public Member Functions
virtual ~Boundary ()
virtual void executeRule (ProceduralTerrainAppearance *generator)
virtual bool containsPoint (float x, float y)
virtual float getLocalWaterTableHeight ()
virtual float process (float x, float y)
int getFeatheringType ()
virtual bool isEnabled ()
virtual float getMinX ()=0
virtual float getMaxX ()=0
virtual float getMinY ()=0
virtual float getMaxY ()=0
virtual void translateBoundary (float x, float y)=0
Protected Attributes
int featheringType
float featheringAmount
Detailed Description
Definition at line 13 of file Boundary.h.
Constructor & Destructor Documentation
virtual Boundary::~Boundary () inline virtual
Definition at line 19 of file Boundary.h.
References featheringType.
Member Function Documentation
virtual bool Boundary::containsPoint (float x, float y) inline virtual
Reimplemented in BoundaryPolygon, and BoundaryRectangle.
Definition at line 27 of file Boundary.h.
Referenced by ProceduralTerrainAppearance::getWater().
virtual void Boundary::executeRule (ProceduralTerrainAppearance * generator) inline virtual
Reimplemented in BoundaryRectangle, and BoundaryPolygon.
Definition at line 23 of file Boundary.h.
int Boundary::getFeatheringType () inline
Definition at line 39 of file Boundary.h.
References featheringType.
Referenced by ProceduralTerrainAppearance::processTerrain().
virtual float Boundary::getLocalWaterTableHeight () inline virtual
Reimplemented in BoundaryPolygon, and BoundaryRectangle.
Definition at line 31 of file Boundary.h.
Referenced by ProceduralTerrainAppearance::getWater().
virtual float Boundary::getMaxX () pure virtual
Implemented in BoundaryPolygon, BoundaryRectangle, BoundaryPolyline, and BoundaryCircle.
Referenced by ProceduralTerrainAppearance::processTerrain().
virtual float Boundary::getMaxY () pure virtual
Implemented in BoundaryPolygon, BoundaryRectangle, BoundaryPolyline, and BoundaryCircle.
Referenced by ProceduralTerrainAppearance::processTerrain().
virtual float Boundary::getMinX () pure virtual
Implemented in BoundaryPolygon, BoundaryRectangle, BoundaryPolyline, and BoundaryCircle.
Referenced by ProceduralTerrainAppearance::processTerrain().
virtual float Boundary::getMinY () pure virtual
Implemented in BoundaryPolygon, BoundaryRectangle, BoundaryPolyline, and BoundaryCircle.
Referenced by ProceduralTerrainAppearance::processTerrain().
virtual bool Boundary::isEnabled () inline virtual
Reimplemented in BoundaryPolygon, BoundaryRectangle, BoundaryPolyline, and BoundaryCircle.
Definition at line 43 of file Boundary.h.
Referenced by ProceduralTerrainAppearance::processTerrain().
virtual float Boundary::process (float x, float y) inline virtual
Reimplemented in BoundaryRectangle, BoundaryPolyline, BoundaryPolygon, and BoundaryCircle.
Definition at line 35 of file Boundary.h.
Referenced by ProceduralTerrainAppearance::processTerrain().
virtual void Boundary::translateBoundary (float x, float y) pure virtual
Implemented in BoundaryRectangle, BoundaryCircle, BoundaryPolyline, and BoundaryPolygon.
Referenced by ProceduralTerrainAppearance::translateBoundaries().
Member Data Documentation
float Boundary::featheringAmount protected
Definition at line 16 of file Boundary.h.
Referenced by BoundaryRectangle::initialize(), BoundaryCircle::parseFromIffStream(), BoundaryPolyline::parseFromIffStream(), BoundaryRectangle::parseFromIffStream(), BoundaryPolygon::parseFromIffStream(), BoundaryCircle::process(), BoundaryPolygon::process(), BoundaryPolyline::process(), and BoundaryRectangle::process().
int Boundary::featheringType protected
Definition at line 15 of file Boundary.h.
Referenced by getFeatheringType(), BoundaryCircle::parseFromIffStream(), BoundaryPolyline::parseFromIffStream(), BoundaryRectangle::parseFromIffStream(), BoundaryPolygon::parseFromIffStream(), and ~Boundary().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/layer/boundaries/Boundary.h