Core3: server::zone::objects::area::SpawnObserver Class Reference
server::zone::objects::area::SpawnObserver Class Reference
#include <SpawnObserver.h>
Public Member Functions
SpawnObserver (SpawnArea *area)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
SpawnObserver (DummyConstructorParameter *param)
virtual ~SpawnObserver ()
Friends
class SpawnObserverHelper
Detailed Description
Definition at line 41 of file SpawnObserver.h.
Constructor & Destructor Documentation
SpawnObserver::SpawnObserver (SpawnArea * area)
Definition at line 15 of file SpawnObserver.cpp.
References server::zone::objects::area::SpawnObserverImplementation::_setStub().
SpawnObserver::SpawnObserver (DummyConstructorParameter * param) protected
Definition at line 22 of file SpawnObserver.cpp.
SpawnObserver::~SpawnObserver () protected virtual
Definition at line 26 of file SpawnObserver.cpp.
Member Function Documentation
DistributedObjectServant * SpawnObserver::_getImplementation ()
Definition at line 48 of file SpawnObserver.cpp.
Referenced by notifyObserverEvent().
DistributedObjectServant * SpawnObserver::_getImplementationForRead ()
Definition at line 54 of file SpawnObserver.cpp.
void SpawnObserver::_setImplementation (DistributedObjectServant * servant)
Definition at line 58 of file SpawnObserver.cpp.
int SpawnObserver::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 31 of file SpawnObserver.cpp.
References _getImplementation(), server::zone::objects::area::SpawnObserverImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
Friends And Related Function Documentation
friend class SpawnObserverHelper friend
Definition at line 57 of file SpawnObserver.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/SpawnObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/SpawnObserver.cpp