Core3: SkillList Class Reference
SkillList Class Reference
#include <SkillList.h>
Public Member Functions
bool add (Skill *skill, DeltaMessage *message=NULL)
void remove (Skill *skill, DeltaMessage *message=NULL)
bool containsSkill (const String &skill)
bool toBinaryStream (ObjectOutputStream *stream)
bool parseFromBinaryStream (ObjectInputStream *stream)
void getStringList (Vector< String > &skills)
void loadFromNames (Vector< String > &skills)
void insertToMessage (BaseMessage *msg)
Public Member Functions inherited from server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >
DeltaVector ()
DeltaVector (int initsize, int incr)
DeltaVector (const DeltaVector &v)
~DeltaVector ()
DeltaVector & operator= (const DeltaVector &v)
void addSerializableVariables ()
virtual Reference< Skill * > set (int idx, const Reference< Skill * > &newValue, DeltaMessage *message=NULL, int updates=1)
virtual bool add (const Reference< Skill * > &element, DeltaMessage *message=NULL, int updates=1)
Reference< Skill * > & get (int index) const
Reference< Skill * > & getSafe (int index)
Reference< Skill * > remove (int index, DeltaMessage *message=NULL, int updates=1)
void removeAll (DeltaMessage *message=NULL)
virtual void insertItemToMessage (Reference< Skill * > *item, BaseMessage *msg)
virtual bool contains (const Reference< Skill * > &element)
int find (const Reference< Skill * > &element)
uint32 getUpdateCounter ()
uint32 getNewUpdateCounter (int increment)
void setUpdateCounter (int count)
void resetUpdateCounter ()
int size ()
ReadWriteLock * getLock ()
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >
Vector< Reference< Skill * > > vector
uint32 updateCounter
ReadWriteLock * mutex
Detailed Description
Definition at line 53 of file SkillList.h.
Member Function Documentation
bool SkillList::add (Skill * skill, DeltaMessage * message = NULL)
Definition at line 84 of file SkillList.cpp.
References Skill::getSkillName(), DeltaMessage::startList(), server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::updateCounter, and server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::vector.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::addSkill().
bool SkillList::containsSkill (const String & skill)
Definition at line 16 of file SkillList.cpp.
References server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::find(), server::zone::managers::skill::SkillManager::getSkill(), and server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::vector.
void SkillList::getStringList (Vector< String > & skills)
Definition at line 39 of file SkillList.cpp.
References server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::vector.
Referenced by toBinaryStream().
void SkillList::insertToMessage (BaseMessage * msg) virtual
Reimplemented from server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >.
Definition at line 113 of file SkillList.cpp.
References server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::updateCounter, and server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::vector.
Referenced by CreatureObjectMessage1::CreatureObjectMessage1().
void SkillList::loadFromNames (Vector< String > & skills)
Definition at line 70 of file SkillList.cpp.
References server::zone::managers::skill::SkillManager::getSkill(), and server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::vector.
Referenced by parseFromBinaryStream().
bool SkillList::parseFromBinaryStream (ObjectInputStream * stream)
Definition at line 59 of file SkillList.cpp.
References loadFromNames(), and server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::updateCounter.
void SkillList::remove (Skill * skill, DeltaMessage * message = NULL)
Definition at line 99 of file SkillList.cpp.
References server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::find(), DeltaMessage::startList(), server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::updateCounter, and server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::vector.
Referenced by server::zone::objects::creature::CreatureObjectImplementation::removeSkill().
bool SkillList::toBinaryStream (ObjectOutputStream * stream)
Definition at line 49 of file SkillList.cpp.
References getStringList(), and server::zone::objects::scene::variables::DeltaVector< Reference< Skill * > >::updateCounter.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/variables/SkillList.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/creature/variables/SkillList.cpp