Core3: server::zone::managers::resource::ResourceManagerImplementation Class Reference
server::zone::managers::resource::ResourceManagerImplementation Class Reference
#include <ResourceManager.h>
Public Member Functions
ResourceManagerImplementation (ZoneServer *server, ZoneProcessServer *impl, ObjectManager *objectMan)
ResourceManagerImplementation (DummyConstructorParameter *param)
void stop ()
void initialize ()
void shiftResources ()
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
int getResourceRecycleType (ResourceSpawn *resource)
void sendResourceListForSurvey (CreatureObject *playerCreature, const int toolType, const String &surveyType)
void sendSurvey (CreatureObject *playerCreature, const String &resname)
void sendSample (CreatureObject *playerCreature, const String &resname, const String &sampleAnimation)
ResourceContainer * harvestResource (CreatureObject *player, const String &type, const int quantity)
void harvestResourceToPlayer (CreatureObject *player, ResourceSpawn *resourceSpawn, const int quantity)
unsigned int getAvailablePowerFromPlayer (CreatureObject *player)
void removePowerFromPlayer (CreatureObject *player, unsigned int power)
void getResourceListByType (Vector< ManagedReference< ResourceSpawn * > > &list, int type, const String &zoneName)
void createResourceSpawn (CreatureObject *playerCreature, const String &restype)
void givePlayerResource (CreatureObject *playerCreature, const String &restype, const int quantity)
ResourceSpawn * getCurrentSpawn (const String &restype, const String &zoneName)
ResourceSpawn * getResourceSpawn (const String &spawnName)
bool isRecycledResource (ResourceSpawn *resource)
ResourceSpawn * getRecycledVersion (ResourceSpawn *resource)
void addNodeToListBox (SuiListBox *sui, const String &nodeName)
Resource Deed Methods.
String addParentNodeToListBox (SuiListBox *sui, const String &currentNode)
void listResourcesForPlanetOnScreen (CreatureObject *creature, const String &planet)
String healthCheck ()
String dumpResources ()
String despawnResource (String &resourceName)
operator const ResourceManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< ResourceManager * > _this
Static Public Attributes
static const int RESOURCE_DEED_QUANTITY = 100000
Protected Member Functions
virtual ~ResourceManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Member Functions
bool loadConfigFile ()
bool loadConfigData ()
void loadDefaultConfig ()
void startResourceSpawner ()
Private Attributes
ManagedReference
< ZoneProcessServer * > processor
ManagedWeakReference
< ZoneServer * > zoneServer
Reference< ResourceSpawner * > resourceSpawner
Reference< ObjectManager * > objectManager
int shiftInterval
Reference< Lua * > lua
Friends
class ResourceManager
Detailed Description
Definition at line 228 of file ResourceManager.h.
Constructor & Destructor Documentation
ResourceManagerImplementation::ResourceManagerImplementation (ZoneServer * server, ZoneProcessServer * impl, ObjectManager * objectMan)
Definition at line 557 of file ResourceManager.cpp.
References _initializeImplementation(), objectManager, processor, resourceSpawner, and zoneServer.
ResourceManagerImplementation::ResourceManagerImplementation (DummyConstructorParameter * param)
Definition at line 431 of file ResourceManager.cpp.
References _initializeImplementation().
ResourceManagerImplementation::~ResourceManagerImplementation () protected virtual
Definition at line 436 of file ResourceManager.cpp.
Member Function Documentation
DistributedObjectStub * ResourceManagerImplementation::_getStub ()
Definition at line 456 of file ResourceManager.cpp.
References _this.
void ResourceManagerImplementation::_initializeImplementation () protected
Definition at line 443 of file ResourceManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ResourceManagerImplementation().
void ResourceManagerImplementation::_serializationHelperMethod () protected
Definition at line 492 of file ResourceManager.cpp.
Referenced by _initializeImplementation().
void ResourceManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 451 of file ResourceManager.cpp.
References _this.
Referenced by server::zone::managers::resource::ResourceManager::ResourceManager().
void ResourceManagerImplementation::addNodeToListBox (SuiListBox * sui, const String & nodeName)
Resource Deed Methods.
Definition at line 425 of file ResourceManagerImplementation.cpp.
References resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::addNodeToListBox().
String ResourceManagerImplementation::addParentNodeToListBox (SuiListBox * sui, const String & currentNode)
Definition at line 429 of file ResourceManagerImplementation.cpp.
References resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::addParentNodeToListBox().
void ResourceManagerImplementation::createResourceSpawn (CreatureObject * playerCreature, const String & restype)
Definition at line 243 of file ResourceManagerImplementation.cpp.
References _this, resourceSpawner, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::resource::ResourceManager::createResourceSpawn().
String ResourceManagerImplementation::despawnResource (String & resourceName)
Definition at line 446 of file ResourceManagerImplementation.cpp.
References getResourceSpawn(), and resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::despawnResource().
String ResourceManagerImplementation::dumpResources ()
Definition at line 441 of file ResourceManagerImplementation.cpp.
References _this, and resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::dumpResources().
void ResourceManagerImplementation::finalize () protected
Definition at line 440 of file ResourceManager.cpp.
uint32 ResourceManagerImplementation::getAvailablePowerFromPlayer (CreatureObject * player)
Definition at line 323 of file ResourceManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::resource::ResourceContainer::getQuantity(), server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::resource::ResourceContainer::getSpawnObject().
Referenced by server::zone::managers::resource::ResourceManager::getAvailablePowerFromPlayer().
ResourceSpawn * ResourceManagerImplementation::getCurrentSpawn (const String & restype, const String & zoneName)
Definition at line 279 of file ResourceManagerImplementation.cpp.
References resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::getCurrentSpawn().
ResourceSpawn * ResourceManagerImplementation::getRecycledVersion (ResourceSpawn * resource)
Definition at line 420 of file ResourceManagerImplementation.cpp.
References resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::getRecycledVersion().
void ResourceManagerImplementation::getResourceListByType (Vector< ManagedReference< ResourceSpawn * > > & list, int type, const String & zoneName)
Definition at line 283 of file ResourceManagerImplementation.cpp.
References ResourceMap::getZoneResourceList(), resourceSpawner, rlock(), and runlock().
Referenced by server::zone::managers::resource::ResourceManager::getResourceListByType().
int ResourceManagerImplementation::getResourceRecycleType (ResourceSpawn * resource)
Definition at line 208 of file ResourceManagerImplementation.cpp.
References resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::getResourceRecycleType().
ResourceSpawn * ResourceManagerImplementation::getResourceSpawn (const String & spawnName)
Definition at line 259 of file ResourceManagerImplementation.cpp.
References resourceSpawner, rlock(), and runlock().
Referenced by despawnResource(), server::zone::managers::resource::ResourceManager::getResourceSpawn(), and givePlayerResource().
void ResourceManagerImplementation::givePlayerResource (CreatureObject * playerCreature, const String & restype, const int quantity)
Definition at line 394 of file ResourceManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::broadcastObject(), getResourceSpawn(), server::zone::objects::scene::SceneObject::getSlottedObject(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::resource::ResourceManager::givePlayerResource().
ResourceContainer * ResourceManagerImplementation::harvestResource (CreatureObject * player, const String & type, const int quantity)
Definition at line 226 of file ResourceManagerImplementation.cpp.
References resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::harvestResource().
void ResourceManagerImplementation::harvestResourceToPlayer (CreatureObject * player, ResourceSpawn * resourceSpawn, const int quantity)
Definition at line 229 of file ResourceManagerImplementation.cpp.
References resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::harvestResourceToPlayer().
String ResourceManagerImplementation::healthCheck ()
Definition at line 437 of file ResourceManagerImplementation.cpp.
References resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::healthCheck().
void ResourceManagerImplementation::initialize ()
Definition at line 55 of file ResourceManagerImplementation.cpp.
References loadConfigData(), loadDefaultConfig(), lua, resourceSpawner, and startResourceSpawner().
Referenced by server::zone::managers::resource::ResourceManager::initialize().
bool ResourceManagerImplementation::isRecycledResource (ResourceSpawn * resource)
Definition at line 416 of file ResourceManagerImplementation.cpp.
References resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::isRecycledResource().
void ResourceManagerImplementation::listResourcesForPlanetOnScreen (CreatureObject * creature, const String & planet)
Definition at line 433 of file ResourceManagerImplementation.cpp.
References resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::listResourcesForPlanetOnScreen().
bool ResourceManagerImplementation::loadConfigData () private
Definition at line 99 of file ResourceManagerImplementation.cpp.
References loadConfigFile(), lua, resourceSpawner, and shiftInterval.
Referenced by initialize().
bool ResourceManagerImplementation::loadConfigFile () private
Definition at line 71 of file ResourceManagerImplementation.cpp.
References lua.
Referenced by loadConfigData().
void ResourceManagerImplementation::loadDefaultConfig () private
Definition at line 168 of file ResourceManagerImplementation.cpp.
References resourceSpawner, and shiftInterval.
Referenced by initialize().
void ResourceManagerImplementation::lock (bool doLock = true) protected
Definition at line 464 of file ResourceManager.cpp.
References _this.
void ResourceManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 468 of file ResourceManager.cpp.
References _this.
int ResourceManagerImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 75 of file ResourceManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getPendingTask(), ObserverEventType::POSTURECHANGED, server::zone::objects::scene::SceneObject::removePendingTask(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::managers::resource::ResourceManager::notifyObserverEvent().
ResourceManagerImplementation::operator const ResourceManager * ()
Definition at line 460 of file ResourceManager.cpp.
void ResourceManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 499 of file ResourceManager.cpp.
References readObjectMember().
bool ResourceManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 518 of file ResourceManager.cpp.
References zoneServer.
Referenced by readObject().
void ResourceManagerImplementation::removePowerFromPlayer (CreatureObject * player, unsigned int power)
Definition at line 350 of file ResourceManagerImplementation.cpp.
References DeltaMessage::close(), server::zone::objects::resource::ResourceContainer::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::getContainerObject(), server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::resource::ResourceContainer::getQuantity(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::resource::ResourceContainer::getSpawnObject(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::resource::ResourceContainer::setQuantity(), and ResourceContainerObjectDeltaMessage3::updateQuantity().
Referenced by server::zone::managers::resource::ResourceManager::removePowerFromPlayer().
void ResourceManagerImplementation::rlock (bool doLock = true) protected
Definition at line 472 of file ResourceManager.cpp.
References _this.
Referenced by getResourceListByType(), getResourceSpawn(), and sendResourceListForSurvey().
void ResourceManagerImplementation::runlock (bool doLock = true) protected
Definition at line 488 of file ResourceManager.cpp.
References _this.
Referenced by getResourceListByType(), getResourceSpawn(), and sendResourceListForSurvey().
void ResourceManagerImplementation::sendResourceListForSurvey (CreatureObject * playerCreature, const int toolType, const String & surveyType)
Definition at line 212 of file ResourceManagerImplementation.cpp.
References resourceSpawner, rlock(), and runlock().
Referenced by server::zone::managers::resource::ResourceManager::sendResourceListForSurvey().
void ResourceManagerImplementation::sendSample (CreatureObject * playerCreature, const String & resname, const String & sampleAnimation)
Definition at line 237 of file ResourceManagerImplementation.cpp.
References _this, ObserverEventType::POSTURECHANGED, and resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::sendSample().
void ResourceManagerImplementation::sendSurvey (CreatureObject * playerCreature, const String & resname)
Definition at line 233 of file ResourceManagerImplementation.cpp.
References resourceSpawner.
Referenced by server::zone::managers::resource::ResourceManager::sendSurvey().
void ResourceManagerImplementation::shiftResources ()
Definition at line 199 of file ResourceManagerImplementation.cpp.
References _this, resourceSpawner, and shiftInterval.
Referenced by server::zone::managers::resource::ResourceManager::shiftResources().
void ResourceManagerImplementation::startResourceSpawner () private
Definition at line 190 of file ResourceManagerImplementation.cpp.
References _this, resourceSpawner, and shiftInterval.
Referenced by initialize().
void ResourceManagerImplementation::stop ()
Definition at line 185 of file ResourceManagerImplementation.cpp.
Referenced by server::zone::managers::resource::ResourceManager::stop().
void ResourceManagerImplementation::unlock (bool doLock = true) protected
Definition at line 484 of file ResourceManager.cpp.
References _this.
void ResourceManagerImplementation::wlock (bool doLock = true) protected
Definition at line 476 of file ResourceManager.cpp.
References _this.
void ResourceManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 480 of file ResourceManager.cpp.
References _this.
void ResourceManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 532 of file ResourceManager.cpp.
References writeObjectMembers().
int ResourceManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 539 of file ResourceManager.cpp.
References zoneServer.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ResourceManager friend
Definition at line 342 of file ResourceManager.h.
Member Data Documentation
WeakReference<ResourceManager*> server::zone::managers::resource::ResourceManagerImplementation::_this
Definition at line 308 of file ResourceManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), createResourceSpawn(), dumpResources(), lock(), rlock(), runlock(), sendSample(), shiftResources(), startResourceSpawner(), unlock(), and wlock().
Reference<Lua* > server::zone::managers::resource::ResourceManagerImplementation::lua private
Definition at line 239 of file ResourceManager.h.
Referenced by initialize(), loadConfigData(), and loadConfigFile().
Reference<ObjectManager* > server::zone::managers::resource::ResourceManagerImplementation::objectManager private
Definition at line 235 of file ResourceManager.h.
Referenced by ResourceManagerImplementation().
ManagedReference<ZoneProcessServer* > server::zone::managers::resource::ResourceManagerImplementation::processor private
Definition at line 229 of file ResourceManager.h.
Referenced by ResourceManagerImplementation().
const int server::zone::managers::resource::ResourceManagerImplementation::RESOURCE_DEED_QUANTITY = 100000 static
Definition at line 242 of file ResourceManager.h.
Reference<ResourceSpawner* > server::zone::managers::resource::ResourceManagerImplementation::resourceSpawner private
Definition at line 233 of file ResourceManager.h.
Referenced by addNodeToListBox(), addParentNodeToListBox(), createResourceSpawn(), despawnResource(), dumpResources(), getCurrentSpawn(), getRecycledVersion(), getResourceListByType(), getResourceRecycleType(), getResourceSpawn(), harvestResource(), harvestResourceToPlayer(), healthCheck(), initialize(), isRecycledResource(), listResourcesForPlanetOnScreen(), loadConfigData(), loadDefaultConfig(), ResourceManagerImplementation(), sendResourceListForSurvey(), sendSample(), sendSurvey(), shiftResources(), and startResourceSpawner().
int server::zone::managers::resource::ResourceManagerImplementation::shiftInterval private
Definition at line 237 of file ResourceManager.h.
Referenced by loadConfigData(), loadDefaultConfig(), shiftResources(), and startResourceSpawner().
ManagedWeakReference<ZoneServer* > server::zone::managers::resource::ResourceManagerImplementation::zoneServer private
Definition at line 231 of file ResourceManager.h.
Referenced by readObjectMember(), ResourceManagerImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/ResourceManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/ResourceManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/resource/ResourceManagerImplementation.cpp