Core3: server::zone::objects::installation::factory::FactoryHopperObserverImplementation Class Reference
server::zone::objects::installation::factory::FactoryHopperObserverImplementation Class Reference
#include <FactoryHopperObserver.h>
Public Member Functions
FactoryHopperObserverImplementation (FactoryObject *fact)
FactoryHopperObserverImplementation (DummyConstructorParameter *param)
int notifyObserverEvent (unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
operator const FactoryHopperObserver * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference
< FactoryHopperObserver * > _this
Protected Member Functions
virtual ~FactoryHopperObserverImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< FactoryObject * > factory
Friends
class FactoryHopperObserver
Detailed Description
Definition at line 87 of file FactoryHopperObserver.h.
Constructor & Destructor Documentation
FactoryHopperObserverImplementation::FactoryHopperObserverImplementation (FactoryObject * fact)
Definition at line 192 of file FactoryHopperObserver.cpp.
References _initializeImplementation(), and factory.
FactoryHopperObserverImplementation::FactoryHopperObserverImplementation (DummyConstructorParameter * param)
Definition at line 66 of file FactoryHopperObserver.cpp.
References _initializeImplementation().
FactoryHopperObserverImplementation::~FactoryHopperObserverImplementation () protected virtual
Definition at line 71 of file FactoryHopperObserver.cpp.
Member Function Documentation
DistributedObjectStub * FactoryHopperObserverImplementation::_getStub ()
Definition at line 91 of file FactoryHopperObserver.cpp.
References _this.
void FactoryHopperObserverImplementation::_initializeImplementation () protected
Definition at line 78 of file FactoryHopperObserver.cpp.
References _serializationHelperMethod(), and _this.
Referenced by FactoryHopperObserverImplementation().
void FactoryHopperObserverImplementation::_serializationHelperMethod () protected
Definition at line 127 of file FactoryHopperObserver.cpp.
Referenced by _initializeImplementation().
void FactoryHopperObserverImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 86 of file FactoryHopperObserver.cpp.
References _this.
Referenced by server::zone::objects::installation::factory::FactoryHopperObserver::FactoryHopperObserver().
void FactoryHopperObserverImplementation::finalize () protected
Definition at line 75 of file FactoryHopperObserver.cpp.
void FactoryHopperObserverImplementation::lock (bool doLock = true) protected
Definition at line 99 of file FactoryHopperObserver.cpp.
References _this.
void FactoryHopperObserverImplementation::lock (ManagedObject * obj) protected
Definition at line 103 of file FactoryHopperObserver.cpp.
References _this.
int FactoryHopperObserverImplementation::notifyObserverEvent (unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 198 of file FactoryHopperObserver.cpp.
References ObserverEventType::CLOSECONTAINER, factory, and ObserverEventType::OPENCONTAINER.
Referenced by server::zone::objects::installation::factory::FactoryHopperObserver::notifyObserverEvent().
FactoryHopperObserverImplementation::operator const FactoryHopperObserver * ()
Definition at line 95 of file FactoryHopperObserver.cpp.
void FactoryHopperObserverImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 134 of file FactoryHopperObserver.cpp.
References readObjectMember().
bool FactoryHopperObserverImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 153 of file FactoryHopperObserver.cpp.
References factory.
Referenced by readObject().
void FactoryHopperObserverImplementation::rlock (bool doLock = true) protected
Definition at line 107 of file FactoryHopperObserver.cpp.
References _this.
void FactoryHopperObserverImplementation::runlock (bool doLock = true) protected
Definition at line 123 of file FactoryHopperObserver.cpp.
References _this.
void FactoryHopperObserverImplementation::unlock (bool doLock = true) protected
Definition at line 119 of file FactoryHopperObserver.cpp.
References _this.
void FactoryHopperObserverImplementation::wlock (bool doLock = true) protected
Definition at line 111 of file FactoryHopperObserver.cpp.
References _this.
void FactoryHopperObserverImplementation::wlock (ManagedObject * obj) protected
Definition at line 115 of file FactoryHopperObserver.cpp.
References _this.
void FactoryHopperObserverImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 167 of file FactoryHopperObserver.cpp.
References writeObjectMembers().
int FactoryHopperObserverImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 174 of file FactoryHopperObserver.cpp.
References factory.
Referenced by writeObject().
Friends And Related Function Documentation
friend class FactoryHopperObserver friend
Definition at line 132 of file FactoryHopperObserver.h.
Member Data Documentation
WeakReference<FactoryHopperObserver*> server::zone::objects::installation::factory::FactoryHopperObserverImplementation::_this
Definition at line 98 of file FactoryHopperObserver.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedWeakReference<FactoryObject* > server::zone::objects::installation::factory::FactoryHopperObserverImplementation::factory protected
Definition at line 89 of file FactoryHopperObserver.h.
Referenced by FactoryHopperObserverImplementation(), notifyObserverEvent(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/factory/FactoryHopperObserver.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/factory/FactoryHopperObserver.cpp