Core3: BountyHunterDroidMenuComponent Class Reference
BountyHunterDroidMenuComponent Class Reference
#include <BountyHunterDroidMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *droidObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *droidObject, CreatureObject *player, byte selectedID)
Private Member Functions
bool playerCanUseProbot (CreatureObject *player)
bool playerCanUseSeeker (CreatureObject *player)
bool isProbeDroid (SceneObject *droidObject)
bool isSeekerDroid (SceneObject *droidObject)
bool droidIsInPlayerInventory (SceneObject *droidObject, CreatureObject *player)
bool droidIsInZone (SceneObject *droidObject)
bool playerOwnsTheDroid (SceneObject *droidObject, CreatureObject *player)
void performDroidAction (int action, SceneObject *droidObject, CreatureObject *player)
MissionObject * getBountyHunterMission (CreatureObject *player)
Detailed Description
Definition at line 15 of file BountyHunterDroidMenuComponent.h.
Member Function Documentation
bool BountyHunterDroidMenuComponent::droidIsInPlayerInventory (SceneObject * droidObject, CreatureObject * player) private
Checks if the scene object is in the inventory of the player.
Parameters
droidObject the object to check.
player the player creature to check in.
Returns
true if the object is found in the inventory of the player.
Definition at line 91 of file BountyHunterDroidMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::getParent(), and server::zone::objects::scene::SceneObject::getSlottedObject().
Referenced by fillObjectMenuResponse(), and handleObjectMenuSelect().
bool BountyHunterDroidMenuComponent::droidIsInZone (SceneObject * droidObject) private
Checks if the object is in a zone.
Parameters
droidObject the object to check.
Returns
true if it is in the Zone.
Definition at line 97 of file BountyHunterDroidMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::getParentID().
Referenced by fillObjectMenuResponse(), and handleObjectMenuSelect().
void BountyHunterDroidMenuComponent::fillObjectMenuResponse (SceneObject * droidObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from TangibleObjectMenuComponent.
Definition at line 16 of file BountyHunterDroidMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::packets::object::ObjectMenuResponse::addRadialMenuItemToRadialID(), droidIsInPlayerInventory(), droidIsInZone(), TangibleObjectMenuComponent::fillObjectMenuResponse(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::templates::SharedObjectTemplate::getTemplateFileName(), isProbeDroid(), isSeekerDroid(), server::zone::objects::scene::SceneObject::isTangibleObject(), and playerOwnsTheDroid().
MissionObject * BountyHunterDroidMenuComponent::getBountyHunterMission (CreatureObject * player) private
Returns a bounty hunter mission object if the player has one.
Parameters
player the player.
Returns
bounty hunter mission object if the player has one otherwise NULL.
Definition at line 148 of file BountyHunterDroidMenuComponent.cpp.
References server::zone::managers::mission::MissionManager::getBountyHunterMission(), server::zone::ZoneServer::getMissionManager(), and server::zone::objects::scene::SceneObject::getZoneServer().
Referenced by performDroidAction().
int BountyHunterDroidMenuComponent::handleObjectMenuSelect (SceneObject * droidObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from TangibleObjectMenuComponent.
Definition at line 41 of file BountyHunterDroidMenuComponent.cpp.
References server::zone::managers::mission::MissionManager::addPlayerToBountyList(), droidIsInPlayerInventory(), droidIsInZone(), server::zone::ZoneServer::getMissionManager(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::templates::SharedObjectTemplate::getTemplateFileName(), server::zone::objects::scene::SceneObject::getZoneServer(), TangibleObjectMenuComponent::handleObjectMenuSelect(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), isProbeDroid(), isSeekerDroid(), server::zone::objects::scene::SceneObject::isTangibleObject(), performDroidAction(), and playerOwnsTheDroid().
bool BountyHunterDroidMenuComponent::isProbeDroid (SceneObject * droidObject) private
Checks if the object is a probe droid.
Parameters
droidObject the object to check.
Returns
true if it is a probe droid.
Definition at line 81 of file BountyHunterDroidMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::getObjectTemplate(), and server::zone::templates::SharedObjectTemplate::getTemplateFileName().
Referenced by fillObjectMenuResponse(), and handleObjectMenuSelect().
bool BountyHunterDroidMenuComponent::isSeekerDroid (SceneObject * droidObject) private
Checks if the object is a seeker droid.
Parameters
droidObject the object to check.
Returns
true if it is a seeker droid.
Definition at line 87 of file BountyHunterDroidMenuComponent.cpp.
References server::zone::objects::scene::SceneObject::getObjectTemplate(), and server::zone::templates::SharedObjectTemplate::getTemplateFileName().
Referenced by fillObjectMenuResponse(), and handleObjectMenuSelect().
void BountyHunterDroidMenuComponent::performDroidAction (int action, SceneObject * droidObject, CreatureObject * player) private
Perform the droid action selected in the radial menu.
Parameters
action the action to perform.
droidObject the droid.
player the player that performs the action on the droid.
Definition at line 117 of file BountyHunterDroidMenuComponent.cpp.
References getBountyHunterMission(), playerCanUseProbot(), playerCanUseSeeker(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by handleObjectMenuSelect().
bool BountyHunterDroidMenuComponent::playerCanUseProbot (CreatureObject * player) private
Checks if the player has the skill to use a probot.
Parameters
player the player to check.
Returns
true if the player got the required skill.
Definition at line 73 of file BountyHunterDroidMenuComponent.cpp.
References server::zone::objects::creature::CreatureObject::hasSkill().
Referenced by performDroidAction().
bool BountyHunterDroidMenuComponent::playerCanUseSeeker (CreatureObject * player) private
Checks if the player has the skill to use a seeker.
Parameters
player the player to check.
Returns
true if the player got the required skill.
Definition at line 77 of file BountyHunterDroidMenuComponent.cpp.
References server::zone::objects::creature::CreatureObject::hasSkill().
Referenced by performDroidAction().
bool BountyHunterDroidMenuComponent::playerOwnsTheDroid (SceneObject * droidObject, CreatureObject * player) private
Checks if the player owns the droid.
Parameters
droidObject the droid.
player the player.
Returns
true if the player owns the droid.
Definition at line 101 of file BountyHunterDroidMenuComponent.cpp.
References server::zone::managers::mission::MissionManager::getBountyHunterMission(), server::zone::ZoneServer::getMissionManager(), server::zone::objects::scene::SceneObject::getObjectID(), and server::zone::objects::scene::SceneObject::getZoneServer().
Referenced by fillObjectMenuResponse(), and handleObjectMenuSelect().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/BountyHunterDroidMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/components/BountyHunterDroidMenuComponent.cpp