Core3: SecurityTerminalMenuComponent Class Reference
SecurityTerminalMenuComponent Class Reference
#include <SecurityTerminalMenuComponent.h>
Public Member Functions
void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 15 of file SecurityTerminalMenuComponent.h.
Member Function Documentation
void SecurityTerminalMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from ObjectMenuComponent.
Definition at line 22 of file SecurityTerminalMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::managers::gcw::GCWManager::canUseTerminals(), SceneObjectType::FACTIONBUILDING, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::Zone::getGCWManager(), server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::managers::gcw::GCWManager::isSecurityTermSliced(), server::zone::managers::gcw::GCWManager::isTerminalDamaged(), server::zone::managers::gcw::GCWManager::isUplinkJammed(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
int SecurityTerminalMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from ObjectMenuComponent.
Definition at line 51 of file SecurityTerminalMenuComponent.cpp.
References SceneObjectType::FACTIONBUILDING, server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::Zone::getGCWManager(), server::zone::objects::scene::SceneObject::getParentRecursively(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::hasSkill(), server::zone::objects::creature::CreatureObject::isDead(), server::zone::objects::creature::CreatureObject::isIncapacitated(), server::zone::objects::scene::SceneObject::isTangibleObject(), server::zone::managers::gcw::GCWManager::repairTerminal(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/terminal/components/SecurityTerminalMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/terminal/components/SecurityTerminalMenuComponent.cpp