Core3: server::zone::managers::player::creation::ProfessionDefaultsInfo Class Reference
server::zone::managers::player::creation::ProfessionDefaultsInfo Class Reference
#include <ProfessionDefaultsInfo.h>
Public Member Functions
ProfessionDefaultsInfo ()
void readObject (IffStream *iffStream)
void setAttributeMod (uint8 idx, int value)
SortedVector< String > * getProfessionItems (const String &clientTemplate)
Skill * getSkill ()
int getAttributeMod (uint8 idx)
Vector< String > * getStartingItems ()
Private Attributes
Reference< Skill * > skill
VectorMap< String,
SortedVector< String > > professionItems
VectorMap< uint8, int > professionMods
Vector< String > startingItems
Detailed Description
Definition at line 21 of file ProfessionDefaultsInfo.h.
Constructor & Destructor Documentation
server::zone::managers::player::creation::ProfessionDefaultsInfo::ProfessionDefaultsInfo () inline
Definition at line 28 of file ProfessionDefaultsInfo.h.
References professionItems, professionMods, and skill.
Member Function Documentation
int server::zone::managers::player::creation::ProfessionDefaultsInfo::getAttributeMod (uint8 idx) inline
Definition at line 99 of file ProfessionDefaultsInfo.h.
References professionMods.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addProfessionStartingItems().
SortedVector<String>* server::zone::managers::player::creation::ProfessionDefaultsInfo::getProfessionItems (const String & clientTemplate) inline
Definition at line 88 of file ProfessionDefaultsInfo.h.
References professionItems.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addProfessionStartingItems().
Skill* server::zone::managers::player::creation::ProfessionDefaultsInfo::getSkill () inline
Definition at line 95 of file ProfessionDefaultsInfo.h.
References skill.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addProfessionStartingItems().
Vector<String>* server::zone::managers::player::creation::ProfessionDefaultsInfo::getStartingItems () inline
Definition at line 103 of file ProfessionDefaultsInfo.h.
References startingItems.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::addProfessionStartingItems(), server::zone::managers::player::creation::PlayerCreationManager::addStartingItemsInto(), and server::zone::managers::player::creation::PlayerCreationManager::addStartingWeaponsInto().
void server::zone::managers::player::creation::ProfessionDefaultsInfo::readObject (IffStream * iffStream) inline
Definition at line 35 of file ProfessionDefaultsInfo.h.
References server::zone::managers::skill::SkillManager::getSkill(), professionItems, and skill.
void server::zone::managers::player::creation::ProfessionDefaultsInfo::setAttributeMod (uint8 idx, int value) inline
Definition at line 84 of file ProfessionDefaultsInfo.h.
References professionMods.
Member Data Documentation
VectorMap<String, SortedVector<String> > server::zone::managers::player::creation::ProfessionDefaultsInfo::professionItems private
Definition at line 23 of file ProfessionDefaultsInfo.h.
Referenced by getProfessionItems(), ProfessionDefaultsInfo(), and readObject().
VectorMap<uint8, int> server::zone::managers::player::creation::ProfessionDefaultsInfo::professionMods private
Definition at line 24 of file ProfessionDefaultsInfo.h.
Referenced by getAttributeMod(), ProfessionDefaultsInfo(), and setAttributeMod().
Reference<Skill*> server::zone::managers::player::creation::ProfessionDefaultsInfo::skill private
Definition at line 22 of file ProfessionDefaultsInfo.h.
Referenced by getSkill(), ProfessionDefaultsInfo(), and readObject().
Vector<String> server::zone::managers::player::creation::ProfessionDefaultsInfo::startingItems private
Definition at line 25 of file ProfessionDefaultsInfo.h.
Referenced by getStartingItems().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/player/creation/ProfessionDefaultsInfo.h