Core3: server::zone::managers::radial::RadialManagerImplementation Class Reference
server::zone::managers::radial::RadialManagerImplementation Class Reference
#include <RadialManager.h>
Public Member Functions
RadialManagerImplementation (ZoneServer *server)
RadialManagerImplementation (DummyConstructorParameter *param)
void handleObjectMenuSelect (CreatureObject *player, byte selectID, unsigned long long objectID)
void handleObjectMenuRequest (CreatureObject *player, ObjectMenuResponse *defaultMenuResponse, unsigned long long objectID)
operator const RadialManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< RadialManager * > _this
Protected Member Functions
virtual ~RadialManagerImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
ManagedReference< ZoneServer * > zoneServer
Friends
class RadialManager
Detailed Description
Definition at line 108 of file RadialManager.h.
Constructor & Destructor Documentation
RadialManagerImplementation::RadialManagerImplementation (ZoneServer * server)
Definition at line 14 of file RadialManagerImplementation.cpp.
References zoneServer.
RadialManagerImplementation::RadialManagerImplementation (DummyConstructorParameter * param)
Definition at line 87 of file RadialManager.cpp.
References _initializeImplementation().
RadialManagerImplementation::~RadialManagerImplementation () protected virtual
Definition at line 92 of file RadialManager.cpp.
Member Function Documentation
DistributedObjectStub * RadialManagerImplementation::_getStub ()
Definition at line 112 of file RadialManager.cpp.
References _this.
void RadialManagerImplementation::_initializeImplementation () protected
Definition at line 99 of file RadialManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by RadialManagerImplementation().
void RadialManagerImplementation::_serializationHelperMethod () protected
Definition at line 148 of file RadialManager.cpp.
Referenced by _initializeImplementation().
void RadialManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 107 of file RadialManager.cpp.
References _this.
Referenced by server::zone::managers::radial::RadialManager::RadialManager().
void RadialManagerImplementation::finalize () protected
Definition at line 96 of file RadialManager.cpp.
void RadialManagerImplementation::handleObjectMenuRequest (CreatureObject * player, ObjectMenuResponse * defaultMenuResponse, unsigned long long objectID)
Definition at line 23 of file RadialManagerImplementation.cpp.
References server::zone::packets::object::ObjectMenuResponse::finish(), ObserverEventType::OBJECTRADIALOPENED, server::zone::objects::creature::CreatureObject::sendMessage(), and zoneServer.
Referenced by server::zone::managers::radial::RadialManager::handleObjectMenuRequest().
void RadialManagerImplementation::handleObjectMenuSelect (CreatureObject * player, byte selectID, unsigned long long objectID)
Definition at line 47 of file RadialManagerImplementation.cpp.
References server::zone::objects::scene::SceneObject::getRootParent(), ObserverEventType::OBJECTRADIALUSED, and zoneServer.
Referenced by server::zone::managers::radial::RadialManager::handleObjectMenuSelect().
void RadialManagerImplementation::lock (bool doLock = true) protected
Definition at line 120 of file RadialManager.cpp.
References _this.
void RadialManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 124 of file RadialManager.cpp.
References _this.
RadialManagerImplementation::operator const RadialManager * ()
Definition at line 116 of file RadialManager.cpp.
void RadialManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 155 of file RadialManager.cpp.
References readObjectMember().
bool RadialManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 174 of file RadialManager.cpp.
References zoneServer.
Referenced by readObject().
void RadialManagerImplementation::rlock (bool doLock = true) protected
Definition at line 128 of file RadialManager.cpp.
References _this.
void RadialManagerImplementation::runlock (bool doLock = true) protected
Definition at line 144 of file RadialManager.cpp.
References _this.
void RadialManagerImplementation::unlock (bool doLock = true) protected
Definition at line 140 of file RadialManager.cpp.
References _this.
void RadialManagerImplementation::wlock (bool doLock = true) protected
Definition at line 132 of file RadialManager.cpp.
References _this.
void RadialManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 136 of file RadialManager.cpp.
References _this.
void RadialManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 188 of file RadialManager.cpp.
References writeObjectMembers().
int RadialManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 195 of file RadialManager.cpp.
References zoneServer.
Referenced by writeObject().
Friends And Related Function Documentation
friend class RadialManager friend
Definition at line 154 of file RadialManager.h.
Member Data Documentation
WeakReference<RadialManager*> server::zone::managers::radial::RadialManagerImplementation::_this
Definition at line 120 of file RadialManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
ManagedReference<ZoneServer* > server::zone::managers::radial::RadialManagerImplementation::zoneServer private
Definition at line 109 of file RadialManager.h.
Referenced by handleObjectMenuRequest(), handleObjectMenuSelect(), RadialManagerImplementation(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/radial/RadialManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/radial/RadialManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/radial/RadialManagerImplementation.cpp