Core3: server::zone::managers::objectcontroller::command::CommandList Class Reference
server::zone::managers::objectcontroller::command::CommandList Class Reference
#include <CommandList.h>
Public Member Functions
CommandList ()
void put (QueueCommand *value)
void put (const String &name, QueueCommand *value)
QueueCommand * getSlashCommand (const String &aname)
QueueCommand * getSlashCommand (uint32 crc)
HashTableIterator< uint32,
Reference< QueueCommand * > > iterator ()
int size ()
Private Attributes
HashTable< uint32, Reference
< QueueCommand * > > commands
Detailed Description
Definition at line 59 of file CommandList.h.
Constructor & Destructor Documentation
server::zone::managers::objectcontroller::command::CommandList::CommandList () inline
Definition at line 63 of file CommandList.h.
Member Function Documentation
QueueCommand* server::zone::managers::objectcontroller::command::CommandList::getSlashCommand (const String & aname) inline
Definition at line 90 of file CommandList.h.
References commands.
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::addCommand().
QueueCommand* server::zone::managers::objectcontroller::command::CommandList::getSlashCommand (uint32 crc) inline
Definition at line 96 of file CommandList.h.
References commands.
HashTableIterator<uint32, Reference<QueueCommand*> > server::zone::managers::objectcontroller::command::CommandList::iterator () inline
Definition at line 100 of file CommandList.h.
References commands.
void server::zone::managers::objectcontroller::command::CommandList::put (QueueCommand * value) inline
Definition at line 70 of file CommandList.h.
References commands, server::zone::objects::creature::commands::QueueCommand::getNameCRC(), and server::zone::objects::creature::commands::QueueCommand::getQueueCommandName().
Referenced by server::zone::managers::objectcontroller::command::CommandConfigManager::createCommand(), server::zone::managers::objectcontroller::command::CommandConfigManager::parseAlternativeNames(), and server::zone::managers::objectcontroller::command::CommandConfigManager::registerSpecialCommands().
void server::zone::managers::objectcontroller::command::CommandList::put (const String & name, QueueCommand * value) inline
Definition at line 80 of file CommandList.h.
References commands.
int server::zone::managers::objectcontroller::command::CommandList::size () inline
Definition at line 104 of file CommandList.h.
References commands.
Member Data Documentation
HashTable<uint32, Reference<QueueCommand*> > server::zone::managers::objectcontroller::command::CommandList::commands private
Definition at line 60 of file CommandList.h.
Referenced by getSlashCommand(), iterator(), put(), and size().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/objectcontroller/command/CommandList.h