Core3: LoginClientThread Class Reference
LoginClientThread Class Reference
#include <LoginClientThread.h>
Public Member Functions
LoginClientThread (LoginClient *client)
~LoginClientThread ()
void run ()
void stop ()
Private Attributes
Reference< BaseClient * > client
Detailed Description
Definition at line 15 of file LoginClientThread.h.
Constructor & Destructor Documentation
LoginClientThread::LoginClientThread (LoginClient * client) inline
Definition at line 19 of file LoginClientThread.h.
References client, and LoginClient::getClient().
LoginClientThread::~LoginClientThread () inline
Definition at line 25 of file LoginClientThread.h.
References client.
Member Function Documentation
void LoginClientThread::run () inline
Definition at line 33 of file LoginClientThread.h.
References client.
Referenced by server::zone::managers::object::ObjectManager::updateObjectVersion().
void LoginClientThread::stop () inline
Definition at line 37 of file LoginClientThread.h.
References client.
Referenced by LoginSession::~LoginSession().
Member Data Documentation
Reference<BaseClient*> LoginClientThread::client private
Definition at line 16 of file LoginClientThread.h.
Referenced by LoginClientThread(), run(), stop(), and ~LoginClientThread().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/login/LoginClientThread.h