Core3: ZonePacketHandler Class Reference
ZonePacketHandler Class Reference
#include <ZonePacketHandler.h>
Public Member Functions
ZonePacketHandler (const String &s, Zone *z)
~ZonePacketHandler ()
void handleMessage (Message *pack)
void handleSceneObjectCreateMessage (Message *pack)
void handleCharacterCreateSucessMessage (Message *pack)
void handleUpdateTransformMessage (Message *pack)
void handleCharacterCreateFailureMessage (Message *pack)
void handleCmdStartScene (Message *pack)
void handleBaselineMessage (Message *pack)
void handleChatInstantMessageToClient (Message *pack)
void handleChatSystemMessage (Message *pack)
void handleObjectControllerMessage (Message *pack)
void handleUpdateContainmentMessage (Message *pack)
void handleSceneObejctDestroyMessage (Message *pack)
void handleClientPermissionsMessage (Message *pack)
Private Attributes
Zone * zone
Detailed Description
Definition at line 52 of file ZonePacketHandler.h.
Constructor & Destructor Documentation
ZonePacketHandler::ZonePacketHandler (const String & s, Zone * z)
Definition at line 13 of file ZonePacketHandler.cpp.
References zone.
ZonePacketHandler::~ZonePacketHandler () inline
Definition at line 58 of file ZonePacketHandler.h.
Member Function Documentation
void ZonePacketHandler::handleBaselineMessage (Message * pack)
Definition at line 200 of file ZonePacketHandler.cpp.
References Zone::getObject(), and zone.
Referenced by handleMessage().
void ZonePacketHandler::handleCharacterCreateFailureMessage (Message * pack)
Definition at line 277 of file ZonePacketHandler.cpp.
Referenced by handleMessage().
void ZonePacketHandler::handleCharacterCreateSucessMessage (Message * pack)
Definition at line 232 of file ZonePacketHandler.cpp.
References Zone::setCharacterID(), and zone.
Referenced by handleMessage().
void ZonePacketHandler::handleChatInstantMessageToClient (Message * pack)
Definition at line 291 of file ZonePacketHandler.cpp.
Referenced by handleMessage().
void ZonePacketHandler::handleChatSystemMessage (Message * pack)
Definition at line 307 of file ZonePacketHandler.cpp.
Referenced by handleMessage().
void ZonePacketHandler::handleClientPermissionsMessage (Message * pack)
Definition at line 103 of file ZonePacketHandler.cpp.
References Zone::getCharacterID(), and zone.
Referenced by handleMessage().
void ZonePacketHandler::handleCmdStartScene (Message * pack)
Definition at line 135 of file ZonePacketHandler.cpp.
References Zone::sceneStarted(), Zone::setCharacterID(), and zone.
Referenced by handleMessage().
void ZonePacketHandler::handleMessage (Message * pack)
Definition at line 20 of file ZonePacketHandler.cpp.
References handleBaselineMessage(), handleCharacterCreateFailureMessage(), handleCharacterCreateSucessMessage(), handleChatInstantMessageToClient(), handleChatSystemMessage(), handleClientPermissionsMessage(), handleCmdStartScene(), handleObjectControllerMessage(), handleSceneObejctDestroyMessage(), handleSceneObjectCreateMessage(), handleUpdateContainmentMessage(), and handleUpdateTransformMessage().
Referenced by ZoneMessageProcessorTask::run().
void ZonePacketHandler::handleObjectControllerMessage (Message * pack)
Definition at line 324 of file ZonePacketHandler.cpp.
References Zone::getObject(), Zone::getObjectController(), ObjectController::handleObjectController(), and zone.
Referenced by handleMessage().
void ZonePacketHandler::handleSceneObejctDestroyMessage (Message * pack)
Definition at line 193 of file ZonePacketHandler.cpp.
References ObjectManager::destroyObject(), Zone::getObjectManager(), and zone.
Referenced by handleMessage().
void ZonePacketHandler::handleSceneObjectCreateMessage (Message * pack)
Definition at line 162 of file ZonePacketHandler.cpp.
References ObjectManager::createObject(), Zone::getObjectManager(), Zone::getZoneClient(), Zone::isSelfPlayer(), SceneObject::setClient(), and zone.
Referenced by handleMessage().
void ZonePacketHandler::handleUpdateContainmentMessage (Message * pack)
Definition at line 338 of file ZonePacketHandler.cpp.
References Zone::getObject(), SceneObject::getParent(), SceneObject::removeObject(), SceneObject::transferObject(), and zone.
Referenced by handleMessage().
void ZonePacketHandler::handleUpdateTransformMessage (Message * pack)
Definition at line 247 of file ZonePacketHandler.cpp.
References PlayerCreature::getFollowObject(), Zone::getObject(), Zone::getSelfPlayer(), PlayerCreature::updatePosition(), and zone.
Referenced by handleMessage().
Member Data Documentation
Zone* ZonePacketHandler::zone private
Definition at line 53 of file ZonePacketHandler.h.
Referenced by handleBaselineMessage(), handleCharacterCreateSucessMessage(), handleClientPermissionsMessage(), handleCmdStartScene(), handleObjectControllerMessage(), handleSceneObejctDestroyMessage(), handleSceneObjectCreateMessage(), handleUpdateContainmentMessage(), handleUpdateTransformMessage(), and ZonePacketHandler().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/zone/ZonePacketHandler.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/zone/ZonePacketHandler.cpp