Core3: server::zone::objects::mission::DeliverMissionObjectiveImplementation Class Reference
server::zone::objects::mission::DeliverMissionObjectiveImplementation Class Reference
#include <DeliverMissionObjective.h>
Public Member Functions
DeliverMissionObjectiveImplementation (MissionObject *mission)
DeliverMissionObjectiveImplementation (DummyConstructorParameter *param)
void finalize ()
void initializeTransientMembers ()
TangibleObject * getItem ()
int getObjectiveStatus ()
virtual void activate ()
virtual void deactivate ()
bool activateWithResult ()
virtual void abort ()
virtual void complete ()
void despawnNpcs ()
virtual void updateMissionStatus (CreatureObject *player)
virtual bool updateMissionTarget (CreatureObject *player)
NpcSpawnPoint * getTargetSpawnPoint ()
NpcSpawnPoint * getDestinationSpawnPoint ()
operator const DeliverMissionObjective * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
MissionObjectiveImplementation (MissionObject *parent)
MissionObjectiveImplementation (DummyConstructorParameter *param)
virtual void destroyObjectFromDatabase ()
virtual int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
virtual void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
virtual Vector3 getEndPosition ()
operator const MissionObjective * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference
< DeliverMissionObjective * > _this
Public Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
WeakReference< MissionObjective * > _this
Static Public Attributes
static const int INITSTATUS = 0
static const int PICKEDUPSTATUS = 1
static const int DELIVEREDSTATUS = 2
Protected Member Functions
virtual ~DeliverMissionObjectiveImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::mission::MissionObjectiveImplementation
virtual ~MissionObjectiveImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedReference
< TangibleObject * > item
Reference< NpcSpawnPoint * > targetSpawnPoint
Reference< NpcSpawnPoint * > destinationSpawnPoint
int objectiveStatus
Protected Attributes inherited from server::zone::objects::mission::MissionObjectiveImplementation
ManagedWeakReference
< MissionObject * > mission
unsigned int objectiveType
Time missionStartTime
Reference
< FailMissionAfterCertainTimeTask * > failTask
unsigned long long timeRemaining
bool activated
Friends
class DeliverMissionObjective
Detailed Description
Definition at line 200 of file DeliverMissionObjective.h.
Constructor & Destructor Documentation
DeliverMissionObjectiveImplementation::DeliverMissionObjectiveImplementation (MissionObject * mission)
Definition at line 394 of file DeliverMissionObjective.cpp.
References _initializeImplementation(), INITSTATUS, and objectiveStatus.
DeliverMissionObjectiveImplementation::DeliverMissionObjectiveImplementation (DummyConstructorParameter * param)
Definition at line 234 of file DeliverMissionObjective.cpp.
References _initializeImplementation().
DeliverMissionObjectiveImplementation::~DeliverMissionObjectiveImplementation () protected virtual
Definition at line 239 of file DeliverMissionObjective.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * DeliverMissionObjectiveImplementation::_getStub ()
Definition at line 257 of file DeliverMissionObjective.cpp.
References _this.
void DeliverMissionObjectiveImplementation::_initializeImplementation () protected
Definition at line 244 of file DeliverMissionObjective.cpp.
References _serializationHelperMethod(), and _this.
Referenced by DeliverMissionObjectiveImplementation().
void DeliverMissionObjectiveImplementation::_serializationHelperMethod () protected
Definition at line 293 of file DeliverMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation(), and server::zone::objects::mission::CraftingMissionObjectiveImplementation::_serializationHelperMethod().
void DeliverMissionObjectiveImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 252 of file DeliverMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::_setStub(), and _this.
Referenced by server::zone::objects::mission::CraftingMissionObjectiveImplementation::_setStub(), and server::zone::objects::mission::DeliverMissionObjective::DeliverMissionObjective().
void DeliverMissionObjectiveImplementation::abort () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Reimplemented in server::zone::objects::mission::CraftingMissionObjectiveImplementation.
Definition at line 152 of file DeliverMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::abort(), and despawnNpcs().
Referenced by server::zone::objects::mission::CraftingMissionObjectiveImplementation::abort(), and server::zone::objects::mission::DeliverMissionObjective::abort().
void DeliverMissionObjectiveImplementation::activate () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 28 of file DeliverMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::activate(), server::zone::objects::mission::MissionObjectiveImplementation::activated, activateWithResult(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), and server::zone::objects::mission::MissionObjectiveImplementation::removeMissionFromPlayer().
Referenced by server::zone::objects::mission::DeliverMissionObjective::activate().
bool DeliverMissionObjectiveImplementation::activateWithResult ()
Definition at line 58 of file DeliverMissionObjectiveImplementation.cpp.
References server::zone::managers::mission::MissionManager::allocateMissionNpcs(), destinationSpawnPoint, server::zone::objects::mission::MissionObject::FACTIONIMPERIAL, server::zone::objects::mission::MissionObject::FACTIONREBEL, server::zone::Zone::getCreatureManager(), server::zone::ZoneServer::getMissionManager(), server::zone::Zone::getPlanetManager(), server::zone::objects::mission::MissionObjectiveImplementation::getPlayerOwner(), server::zone::managers::mission::MissionManager::getRandomFreeNpcSpawnPoint(), server::zone::managers::planet::PlanetManager::getTerrainManager(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::mission::MissionObjectiveImplementation::mission, objectiveStatus, server::zone::objects::waypoint::WaypointObject::setActive(), server::zone::objects::waypoint::WaypointObject::setPlanetCRC(), targetSpawnPoint, and updateMissionTarget().
Referenced by activate(), and server::zone::objects::mission::DeliverMissionObjective::activateWithResult().
void DeliverMissionObjectiveImplementation::complete () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 158 of file DeliverMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::complete(), and despawnNpcs().
Referenced by server::zone::objects::mission::DeliverMissionObjective::complete(), server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus(), and updateMissionStatus().
void DeliverMissionObjectiveImplementation::deactivate () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 51 of file DeliverMissionObjectiveImplementation.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::activated, server::zone::objects::mission::MissionObjectiveImplementation::deactivate(), and despawnNpcs().
Referenced by server::zone::objects::mission::DeliverMissionObjective::deactivate().
void DeliverMissionObjectiveImplementation::despawnNpcs ()
Definition at line 164 of file DeliverMissionObjectiveImplementation.cpp.
References destinationSpawnPoint, server::zone::managers::mission::MissionManager::freeMissionNpc(), server::zone::ZoneServer::getMissionManager(), ServerCore::getZoneServer(), and targetSpawnPoint.
Referenced by abort(), complete(), deactivate(), and server::zone::objects::mission::DeliverMissionObjective::despawnNpcs().
void DeliverMissionObjectiveImplementation::finalize ()
Definition at line 402 of file DeliverMissionObjective.cpp.
Referenced by ~DeliverMissionObjectiveImplementation().
NpcSpawnPoint * DeliverMissionObjectiveImplementation::getDestinationSpawnPoint ()
Definition at line 427 of file DeliverMissionObjective.cpp.
References destinationSpawnPoint.
Referenced by server::zone::objects::mission::DeliverMissionObjective::getDestinationSpawnPoint().
TangibleObject * DeliverMissionObjectiveImplementation::getItem ()
Definition at line 412 of file DeliverMissionObjective.cpp.
References item.
Referenced by server::zone::objects::mission::DeliverMissionObjective::getItem().
int DeliverMissionObjectiveImplementation::getObjectiveStatus ()
Definition at line 417 of file DeliverMissionObjective.cpp.
References objectiveStatus.
Referenced by server::zone::objects::mission::DeliverMissionObjective::getObjectiveStatus().
NpcSpawnPoint * DeliverMissionObjectiveImplementation::getTargetSpawnPoint ()
Definition at line 422 of file DeliverMissionObjective.cpp.
References targetSpawnPoint.
Referenced by server::zone::objects::mission::DeliverMissionObjective::getTargetSpawnPoint().
void DeliverMissionObjectiveImplementation::initializeTransientMembers () virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Definition at line 405 of file DeliverMissionObjective.cpp.
References server::zone::objects::mission::MissionObjectiveImplementation::initializeTransientMembers().
Referenced by server::zone::objects::mission::CraftingMissionObjectiveImplementation::initializeTransientMembers(), server::zone::objects::mission::DeliverMissionObjective::initializeTransientMembers(), and readObject().
void DeliverMissionObjectiveImplementation::lock (bool doLock = true) protected
Definition at line 265 of file DeliverMissionObjective.cpp.
References _this.
Referenced by updateMissionStatus().
void DeliverMissionObjectiveImplementation::lock (ManagedObject * obj) protected
Definition at line 269 of file DeliverMissionObjective.cpp.
References _this.
DeliverMissionObjectiveImplementation::operator const DeliverMissionObjective * ()
Definition at line 261 of file DeliverMissionObjective.cpp.
void DeliverMissionObjectiveImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Reimplemented in server::zone::objects::mission::CraftingMissionObjectiveImplementation.
Definition at line 300 of file DeliverMissionObjective.cpp.
References initializeTransientMembers(), and readObjectMember().
bool DeliverMissionObjectiveImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 319 of file DeliverMissionObjective.cpp.
References destinationSpawnPoint, item, objectiveStatus, server::zone::objects::mission::MissionObjectiveImplementation::readObjectMember(), and targetSpawnPoint.
Referenced by readObject(), and server::zone::objects::mission::CraftingMissionObjectiveImplementation::readObjectMember().
void DeliverMissionObjectiveImplementation::rlock (bool doLock = true) protected
Definition at line 273 of file DeliverMissionObjective.cpp.
References _this.
void DeliverMissionObjectiveImplementation::runlock (bool doLock = true) protected
Definition at line 289 of file DeliverMissionObjective.cpp.
References _this.
void DeliverMissionObjectiveImplementation::unlock (bool doLock = true) protected
Definition at line 285 of file DeliverMissionObjective.cpp.
References _this.
void DeliverMissionObjectiveImplementation::updateMissionStatus (CreatureObject * player) virtual
Reimplemented in server::zone::objects::mission::CraftingMissionObjectiveImplementation.
Definition at line 175 of file DeliverMissionObjectiveImplementation.cpp.
References complete(), server::zone::ZoneServer::createObject(), DELIVEREDSTATUS, server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getZoneServer(), item, lock(), server::zone::objects::mission::MissionObjectiveImplementation::mission, objectiveStatus, PICKEDUPSTATUS, server::zone::objects::scene::variables::StringId::setStringId(), and updateMissionTarget().
Referenced by server::zone::objects::mission::DeliverMissionObjective::updateMissionStatus().
bool DeliverMissionObjectiveImplementation::updateMissionTarget (CreatureObject * player) virtual
Definition at line 224 of file DeliverMissionObjectiveImplementation.cpp.
References destinationSpawnPoint, server::zone::objects::mission::MissionObjectiveImplementation::mission, server::zone::objects::waypoint::WaypointObject::setActive(), and server::zone::objects::waypoint::WaypointObject::setPlanetCRC().
Referenced by activateWithResult(), server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus(), updateMissionStatus(), and server::zone::objects::mission::DeliverMissionObjective::updateMissionTarget().
void DeliverMissionObjectiveImplementation::wlock (bool doLock = true) protected
Definition at line 277 of file DeliverMissionObjective.cpp.
References _this.
void DeliverMissionObjectiveImplementation::wlock (ManagedObject * obj) protected
Definition at line 281 of file DeliverMissionObjective.cpp.
References _this.
void DeliverMissionObjectiveImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::mission::MissionObjectiveImplementation.
Reimplemented in server::zone::objects::mission::CraftingMissionObjectiveImplementation.
Definition at line 345 of file DeliverMissionObjective.cpp.
References writeObjectMembers().
int DeliverMissionObjectiveImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 352 of file DeliverMissionObjective.cpp.
References destinationSpawnPoint, item, objectiveStatus, targetSpawnPoint, and server::zone::objects::mission::MissionObjectiveImplementation::writeObjectMembers().
Referenced by writeObject(), and server::zone::objects::mission::CraftingMissionObjectiveImplementation::writeObjectMembers().
Friends And Related Function Documentation
friend class DeliverMissionObjective friend
Definition at line 281 of file DeliverMissionObjective.h.
Member Data Documentation
WeakReference<DeliverMissionObjective*> server::zone::objects::mission::DeliverMissionObjectiveImplementation::_this
Definition at line 249 of file DeliverMissionObjective.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
const int server::zone::objects::mission::DeliverMissionObjectiveImplementation::DELIVEREDSTATUS = 2 static
Definition at line 215 of file DeliverMissionObjective.h.
Referenced by server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus(), and updateMissionStatus().
Reference<NpcSpawnPoint* > server::zone::objects::mission::DeliverMissionObjectiveImplementation::destinationSpawnPoint protected
Definition at line 206 of file DeliverMissionObjective.h.
Referenced by activateWithResult(), despawnNpcs(), getDestinationSpawnPoint(), readObjectMember(), updateMissionTarget(), and writeObjectMembers().
const int server::zone::objects::mission::DeliverMissionObjectiveImplementation::INITSTATUS = 0 static
Definition at line 211 of file DeliverMissionObjective.h.
Referenced by DeliverMissionObjectiveImplementation().
ManagedReference<TangibleObject* > server::zone::objects::mission::DeliverMissionObjectiveImplementation::item protected
Definition at line 202 of file DeliverMissionObjective.h.
Referenced by getItem(), readObjectMember(), server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus(), updateMissionStatus(), and writeObjectMembers().
int server::zone::objects::mission::DeliverMissionObjectiveImplementation::objectiveStatus protected
Definition at line 208 of file DeliverMissionObjective.h.
Referenced by activateWithResult(), DeliverMissionObjectiveImplementation(), getObjectiveStatus(), readObjectMember(), server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus(), updateMissionStatus(), and writeObjectMembers().
const int server::zone::objects::mission::DeliverMissionObjectiveImplementation::PICKEDUPSTATUS = 1 static
Definition at line 213 of file DeliverMissionObjective.h.
Referenced by server::zone::objects::mission::CraftingMissionObjectiveImplementation::updateMissionStatus(), and updateMissionStatus().
Reference<NpcSpawnPoint* > server::zone::objects::mission::DeliverMissionObjectiveImplementation::targetSpawnPoint protected
Definition at line 204 of file DeliverMissionObjective.h.
Referenced by activateWithResult(), despawnNpcs(), getTargetSpawnPoint(), readObjectMember(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DeliverMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DeliverMissionObjective.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DeliverMissionObjectiveImplementation.cpp