Core3: server::zone::managers::vendor::VendorManager Class Reference
server::zone::managers::vendor::VendorManager Class Reference
#include <VendorManager.h>
Public Member Functions
VendorManager ()
~VendorManager ()
void initialize (ZoneProcessServer *zserv)
void loadLuaVendors ()
void loadVendorOutfits ()
bool isValidVendorName (const String &name)
void handleDisplayStatus (CreatureObject *player, TangibleObject *vendor)
String getTimeString (uint32 timestamp)
void promptDestroyVendor (CreatureObject *player, TangibleObject *vendor)
void promptRenameVendorTo (CreatureObject *player, TangibleObject *vendor)
void handleDestroyCallback (CreatureObject *player, TangibleObject *vendor)
void destroyVendor (SceneObject *vendor)
void sendRegisterVendorTo (CreatureObject *player, TangibleObject *vendor)
void handleRegisterVendorCallback (CreatureObject *player, TangibleObject *vendor, const String &planetMapCategoryName)
void handleUnregisterVendor (CreatureObject *player, TangibleObject *vendor)
void handleRenameVendor (CreatureObject *player, TangibleObject *vendor, String &name)
void randomizeCustomization (TangibleObject *vendor)
VendorSelectionNode * getRootNode ()
Protected Attributes
Reference< VendorSelectionNode * > rootNode
ManagedReference
< ZoneProcessServer * > server
Reference< NameManager * > nameManager
Detailed Description
Definition at line 22 of file VendorManager.h.
Constructor & Destructor Documentation
VendorManager::VendorManager ()
Definition at line 21 of file VendorManager.cpp.
References nameManager, and server.
server::zone::managers::vendor::VendorManager::~VendorManager () inline
Definition at line 33 of file VendorManager.h.
Member Function Documentation
void VendorManager::destroyVendor (SceneObject * vendor)
Definition at line 231 of file VendorManager.cpp.
References server::zone::objects::scene::SceneObject::destroyObjectFromDatabase(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getZone(), VendorDataComponent::isRegistered(), server, and server::zone::Zone::unregisterObjectWithPlanetaryMap().
Referenced by handleDestroyCallback().
VendorSelectionNode* server::zone::managers::vendor::VendorManager::getRootNode () inline
Definition at line 69 of file VendorManager.h.
References rootNode.
String VendorManager::getTimeString (uint32 timestamp)
Definition at line 156 of file VendorManager.cpp.
Referenced by handleDisplayStatus().
void VendorManager::handleDestroyCallback (CreatureObject * player, TangibleObject * vendor)
Definition at line 227 of file VendorManager.cpp.
References destroyVendor().
void VendorManager::handleDisplayStatus (CreatureObject * player, TangibleObject * vendor)
Definition at line 65 of file VendorManager.cpp.
References server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::tangible::TangibleObject::getConditionDamage(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), VendorDataComponent::getMaint(), VendorDataComponent::getMaintenanceRate(), server::zone::objects::tangible::TangibleObject::getMaxCondition(), server::zone::objects::creature::CreatureObject::getPlayerObject(), getTimeString(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), VendorDataComponent::isVendorSearchEnabled(), server::zone::objects::creature::CreatureObject::sendMessage(), server, and SuiWindowType::STRUCTURE_VENDOR_STATUS.
void VendorManager::handleRegisterVendorCallback (CreatureObject * player, TangibleObject * vendor, const String & planetMapCategoryName)
Definition at line 293 of file VendorManager.cpp.
References server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::registerObjectWithPlanetaryMap(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::scene::SceneObject::setPlanetMapCategory(), server::zone::objects::scene::SceneObject::setPlanetMapSubCategory(), and VendorDataComponent::setRegistered().
void VendorManager::handleRenameVendor (CreatureObject * player, TangibleObject * vendor, String & name)
Definition at line 358 of file VendorManager.cpp.
References server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getZone(), VendorDataComponent::isRegistered(), isValidVendorName(), promptRenameVendorTo(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::tangible::TangibleObject::setCustomObjectName(), VendorDataComponent::setRegistered(), and server::zone::Zone::unregisterObjectWithPlanetaryMap().
void VendorManager::handleUnregisterVendor (CreatureObject * player, TangibleObject * vendor)
Definition at line 330 of file VendorManager.cpp.
References server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), VendorDataComponent::setRegistered(), and server::zone::Zone::unregisterObjectWithPlanetaryMap().
void VendorManager::initialize (ZoneProcessServer * zserv)
Definition at line 27 of file VendorManager.cpp.
References loadLuaVendors(), loadVendorOutfits(), and server.
bool VendorManager::isValidVendorName (const String & name)
Definition at line 52 of file VendorManager.cpp.
References nameManager, and server.
Referenced by handleRenameVendor().
void VendorManager::loadLuaVendors ()
Definition at line 34 of file VendorManager.cpp.
References rootNode.
Referenced by initialize().
void server::zone::managers::vendor::VendorManager::loadVendorOutfits () inline
Definition at line 41 of file VendorManager.h.
Referenced by initialize().
void VendorManager::promptDestroyVendor (CreatureObject * player, TangibleObject * vendor)
Definition at line 185 of file VendorManager.cpp.
References server::zone::objects::player::sui::messagebox::SuiMessageBox::generateMessage(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getObjectID(), VendorDataComponent::getOwnerId(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::player::sui::SuiBox::setCallback(), server::zone::objects::player::sui::SuiBox::setCancelButton(), server::zone::objects::player::sui::SuiBox::setOkButton(), server::zone::objects::player::sui::SuiBox::setPromptText(), server::zone::objects::player::sui::SuiBox::setPromptTitle(), server::zone::objects::player::sui::SuiBox::setUsingObject(), and SuiWindowType::STRUCTURE_DESTROY_VENDOR_CONFIRM.
void VendorManager::promptRenameVendorTo (CreatureObject * player, TangibleObject * vendor)
Definition at line 215 of file VendorManager.cpp.
References server::zone::objects::player::sui::messagebox::SuiInputBox::generateMessage(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::player::sui::SuiBox::setCallback(), server::zone::objects::player::sui::SuiBox::setCancelButton(), server::zone::objects::player::sui::SuiBox::setPromptText(), server::zone::objects::player::sui::SuiBox::setPromptTitle(), server::zone::objects::player::sui::SuiBox::setUsingObject(), and SuiWindowType::STRUCTURE_NAME_VENDOR.
Referenced by handleRenameVendor().
void VendorManager::randomizeCustomization (TangibleObject * vendor)
Definition at line 401 of file VendorManager.cpp.
void VendorManager::sendRegisterVendorTo (CreatureObject * player, TangibleObject * vendor)
Definition at line 265 of file VendorManager.cpp.
References server::zone::objects::player::sui::listbox::SuiListBox::addMenuItem(), server::zone::objects::player::sui::listbox::SuiListBox::generateMessage(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::player::sui::SuiBox::setCallback(), server::zone::objects::player::sui::SuiBox::setCancelButton(), server::zone::objects::player::sui::SuiBox::setPromptText(), server::zone::objects::player::sui::SuiBox::setPromptTitle(), server::zone::objects::player::sui::SuiBox::setUsingObject(), and SuiWindowType::STRUCTURE_VENDOR_REGISTER.
Member Data Documentation
Reference<NameManager*> server::zone::managers::vendor::VendorManager::nameManager protected
Definition at line 27 of file VendorManager.h.
Referenced by isValidVendorName(), and VendorManager().
Reference<VendorSelectionNode*> server::zone::managers::vendor::VendorManager::rootNode protected
Definition at line 24 of file VendorManager.h.
Referenced by getRootNode(), and loadLuaVendors().
ManagedReference<ZoneProcessServer*> server::zone::managers::vendor::VendorManager::server protected
Definition at line 26 of file VendorManager.h.
Referenced by destroyVendor(), handleDisplayStatus(), initialize(), isValidVendorName(), and VendorManager().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/vendor/VendorManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/vendor/VendorManager.cpp