Core3: HeightMap Class Reference
HeightMap Class Reference
#include <HeightMap.h>
Public Member Functions
HeightMap ()
~HeightMap ()
void load (const String &path)
float getHeight (float x, float y)
bool isLoaded ()
Static Public Member Functions
static float getHeightFrom (FileInputStream *file, float x, float y)
static void convert (const String &path)
static void readPlaneForConversion (FileInputStream *file, float *buffer, int planeX, int planeY)
Protected Member Functions
HeightMapPlane * streamPlaneAt (float x, float y)
int getPlanePosition (float x, float y)
Private Attributes
FileInputStream * reader
File * file
HeightMapPlane ** planes
ArrayQueue< HeightMapPlane * > planeQueue
Static Private Attributes
static const int PLANESSIZE = 64
static const int PLANEWIDTH = 256
static const int PLANELIMIT = 300
static const int HEIGHTSIZE = sizeof(float)
static const int ORIGOSHIFT = PLANESSIZE * PLANEWIDTH / 2
Detailed Description
Definition at line 8 of file HeightMap.h.
Constructor & Destructor Documentation
HeightMap::HeightMap ()
Definition at line 3 of file HeightMap.cpp.
References file, planes, PLANESSIZE, and reader.
HeightMap::~HeightMap ()
Definition at line 18 of file HeightMap.cpp.
References file, planes, PLANESSIZE, and reader.
Member Function Documentation
void HeightMap::convert (const String & path) static
Definition at line 169 of file HeightMap.cpp.
References HEIGHTSIZE, PLANEWIDTH, reader, and readPlaneForConversion().
float HeightMap::getHeight (float x, float y)
Definition at line 64 of file HeightMap.cpp.
References HeightMapPlane::getHeight(), getPlanePosition(), ORIGOSHIFT, planes, PLANEWIDTH, reader, and streamPlaneAt().
float HeightMap::getHeightFrom (FileInputStream * file, float x, float y) static
Definition at line 105 of file HeightMap.cpp.
Referenced by readPlaneForConversion().
int HeightMap::getPlanePosition (float x, float y) protected
Definition at line 153 of file HeightMap.cpp.
References ORIGOSHIFT, PLANESSIZE, and PLANEWIDTH.
Referenced by getHeight(), and streamPlaneAt().
bool HeightMap::isLoaded () inline
Definition at line 35 of file HeightMap.h.
References reader.
void HeightMap::load (const String & path)
Definition at line 39 of file HeightMap.cpp.
References file, and reader.
void HeightMap::readPlaneForConversion (FileInputStream * file, float * buffer, int planeX, int planeY) static
Definition at line 239 of file HeightMap.cpp.
References getHeightFrom(), and PLANEWIDTH.
Referenced by convert().
HeightMapPlane * HeightMap::streamPlaneAt (float x, float y) protected
Definition at line 121 of file HeightMap.cpp.
References HeightMapPlane::getBuffer(), HeightMapPlane::getIndex(), getPlanePosition(), HEIGHTSIZE, PLANELIMIT, planeQueue, planes, PLANEWIDTH, reader, and HeightMapPlane::setIndex().
Referenced by getHeight().
Member Data Documentation
File* HeightMap::file private
Definition at line 10 of file HeightMap.h.
Referenced by HeightMap(), load(), and ~HeightMap().
const int HeightMap::HEIGHTSIZE = sizeof(float) static private
Definition at line 22 of file HeightMap.h.
Referenced by convert(), and streamPlaneAt().
const int HeightMap::ORIGOSHIFT = PLANESSIZE * PLANEWIDTH / 2 static private
Definition at line 24 of file HeightMap.h.
Referenced by getHeight(), and getPlanePosition().
const int HeightMap::PLANELIMIT = 300 static private
Definition at line 20 of file HeightMap.h.
Referenced by streamPlaneAt().
ArrayQueue<HeightMapPlane*> HeightMap::planeQueue private
Definition at line 14 of file HeightMap.h.
Referenced by streamPlaneAt().
HeightMapPlane** HeightMap::planes private
Definition at line 12 of file HeightMap.h.
Referenced by getHeight(), HeightMap(), streamPlaneAt(), and ~HeightMap().
const int HeightMap::PLANESSIZE = 64 static private
Definition at line 16 of file HeightMap.h.
Referenced by getPlanePosition(), HeightMap(), and ~HeightMap().
const int HeightMap::PLANEWIDTH = 256 static private
Definition at line 18 of file HeightMap.h.
Referenced by convert(), getHeight(), getPlanePosition(), readPlaneForConversion(), and streamPlaneAt().
FileInputStream* HeightMap::reader private
Definition at line 9 of file HeightMap.h.
Referenced by convert(), getHeight(), HeightMap(), isLoaded(), load(), streamPlaneAt(), and ~HeightMap().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/HeightMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/HeightMap.cpp