Core3: server::zone::templates::mobile::LairTemplate Class Reference
server::zone::templates::mobile::LairTemplate Class Reference
#include <LairTemplate.h>
Public Types
enum LairType { CREATURE, NPC }
enum {
VERYEASY = 0, EASY, MEDIUM, HARD,
VERYHARD
}
Public Member Functions
LairTemplate (const String &templateName)
virtual ~LairTemplate ()
String getBuilding (int level)
void readObject (LuaObject *templateData)
int getSpawnLimit ()
VectorMap< String, int > * getMobiles ()
bool isLairTemplate ()
String & getName ()
unsigned int getFaction ()
LairType getLairType ()
Protected Attributes
VectorMap< String, int > mobiles
int spawnLimit
VectorMap< uint32, Reference
< Vector< String > * > > buildings
String name
unsigned int faction
LairType lairType
Detailed Description
Definition at line 19 of file LairTemplate.h.
Member Enumeration Documentation
anonymous enum
Enumerator
VERYEASY
EASY
MEDIUM
HARD
VERYHARD
Definition at line 36 of file LairTemplate.h.
enum server::zone::templates::mobile::LairTemplate::LairType
Enumerator
CREATURE
NPC
Definition at line 21 of file LairTemplate.h.
Constructor & Destructor Documentation
server::zone::templates::mobile::LairTemplate::LairTemplate (const String & templateName) inline
Definition at line 40 of file LairTemplate.h.
References buildings, and name.
virtual server::zone::templates::mobile::LairTemplate::~LairTemplate () inline virtual
Definition at line 47 of file LairTemplate.h.
Member Function Documentation
String server::zone::templates::mobile::LairTemplate::getBuilding (int level) inline
Definition at line 50 of file LairTemplate.h.
References buildings, EASY, HARD, MEDIUM, VERYEASY, and VERYHARD.
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), and server::zone::managers::creature::CreatureManagerImplementation::spawnLair().
unsigned int server::zone::templates::mobile::LairTemplate::getFaction () inline
Definition at line 212 of file LairTemplate.h.
References faction.
Referenced by CreateSpawningElementCommand::doQueueCommand(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::spawnLair(), and server::zone::objects::area::LairSpawnAreaImplementation::trySpawnLair().
LairType server::zone::templates::mobile::LairTemplate::getLairType () inline
Definition at line 216 of file LairTemplate.h.
References lairType.
VectorMap<String, int>* server::zone::templates::mobile::LairTemplate::getMobiles () inline
Definition at line 200 of file LairTemplate.h.
References mobiles.
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomizeGenericHuntingMission(), and server::zone::managers::creature::CreatureManagerImplementation::spawnLair().
String& server::zone::templates::mobile::LairTemplate::getName () inline
Definition at line 208 of file LairTemplate.h.
References name.
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission().
int server::zone::templates::mobile::LairTemplate::getSpawnLimit () inline
Definition at line 196 of file LairTemplate.h.
References spawnLimit.
bool server::zone::templates::mobile::LairTemplate::isLairTemplate () inline
Definition at line 204 of file LairTemplate.h.
void server::zone::templates::mobile::LairTemplate::readObject (LuaObject * templateData) inline
Definition at line 77 of file LairTemplate.h.
References buildings, CREATURE, EASY, faction, HARD, lairType, MEDIUM, mobiles, NPC, spawnLimit, VERYEASY, and VERYHARD.
Member Data Documentation
VectorMap<uint32, Reference<Vector<String>*> > server::zone::templates::mobile::LairTemplate::buildings protected
Definition at line 27 of file LairTemplate.h.
Referenced by getBuilding(), LairTemplate(), and readObject().
unsigned int server::zone::templates::mobile::LairTemplate::faction protected
Definition at line 31 of file LairTemplate.h.
Referenced by getFaction(), and readObject().
LairType server::zone::templates::mobile::LairTemplate::lairType protected
Definition at line 33 of file LairTemplate.h.
Referenced by getLairType(), and readObject().
VectorMap<String, int> server::zone::templates::mobile::LairTemplate::mobiles protected
Definition at line 24 of file LairTemplate.h.
Referenced by getMobiles(), and readObject().
String server::zone::templates::mobile::LairTemplate::name protected
Definition at line 29 of file LairTemplate.h.
Referenced by getName(), and LairTemplate().
int server::zone::templates::mobile::LairTemplate::spawnLimit protected
Definition at line 25 of file LairTemplate.h.
Referenced by getSpawnLimit(), and readObject().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/mobile/LairTemplate.h