Core3: EntertainingData Class Reference
EntertainingData Class Reference
#include <EntertainingData.h>
Public Member Functions
EntertainingData ()
EntertainingData (const EntertainingData &d)
EntertainingData & operator= (const EntertainingData &d)
void addSerializableVariables ()
int getDuration ()
int getStrength ()
int getTimeStarted ()
void setStrength (int str)
void incrementStrength (int incr)
void setDuration (int dur)
void incrementDuration (int incr)
Private Attributes
int duration
int strength
int timeStarted
Detailed Description
Definition at line 13 of file EntertainingData.h.
Constructor & Destructor Documentation
EntertainingData::EntertainingData () inline
Definition at line 18 of file EntertainingData.h.
References addSerializableVariables(), duration, strength, and timeStarted.
EntertainingData::EntertainingData (const EntertainingData & d) inline
Definition at line 25 of file EntertainingData.h.
References addSerializableVariables(), duration, and strength.
Member Function Documentation
void EntertainingData::addSerializableVariables () inline
Definition at line 42 of file EntertainingData.h.
References duration, and strength.
Referenced by EntertainingData().
int EntertainingData::getDuration () inline
Definition at line 47 of file EntertainingData.h.
References duration.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::getEntertainerBuffDuration().
int EntertainingData::getStrength () inline
Definition at line 51 of file EntertainingData.h.
References strength.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::getEntertainerBuffStrength().
int EntertainingData::getTimeStarted () inline
Definition at line 54 of file EntertainingData.h.
References timeStarted.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::getEntertainerBuffStartTime().
void EntertainingData::incrementDuration (int incr) inline
Definition at line 69 of file EntertainingData.h.
References duration.
void EntertainingData::incrementStrength (int incr) inline
Definition at line 61 of file EntertainingData.h.
References strength.
EntertainingData& EntertainingData::operator= (const EntertainingData & d) inline
Definition at line 32 of file EntertainingData.h.
References duration, and strength.
void EntertainingData::setDuration (int dur) inline
Definition at line 65 of file EntertainingData.h.
References duration.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::setEntertainerBuffDuration().
void EntertainingData::setStrength (int str) inline
Definition at line 57 of file EntertainingData.h.
References strength.
Referenced by server::zone::objects::player::sessions::EntertainingSessionImplementation::setEntertainerBuffStrength().
Member Data Documentation
int EntertainingData::duration private
Definition at line 14 of file EntertainingData.h.
Referenced by addSerializableVariables(), EntertainingData(), getDuration(), incrementDuration(), operator=(), and setDuration().
int EntertainingData::strength private
Definition at line 15 of file EntertainingData.h.
Referenced by addSerializableVariables(), EntertainingData(), getStrength(), incrementStrength(), operator=(), and setStrength().
int EntertainingData::timeStarted private
Definition at line 16 of file EntertainingData.h.
Referenced by EntertainingData(), and getTimeStarted().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/EntertainingData.h