Core3: LootGroupEntry Class Reference
LootGroupEntry Class Reference
#include <LootGroupEntry.h>
Public Member Functions
LootGroupEntry ()
LootGroupEntry (const String &name, int chance)
void readObject (LuaObject *lua)
int compareTo (const LootGroupEntry &lge) const
LootGroupEntry & operator= (const LootGroupEntry &lge)
String & getLootGroupName ()
int getLootChance ()
Private Attributes
String templateName
int lootChance
Detailed Description
Definition at line 13 of file LootGroupEntry.h.
Constructor & Destructor Documentation
LootGroupEntry::LootGroupEntry () inline
Definition at line 18 of file LootGroupEntry.h.
References lootChance.
LootGroupEntry::LootGroupEntry (const String & name, int chance) inline
Definition at line 22 of file LootGroupEntry.h.
References lootChance, and templateName.
Member Function Documentation
int LootGroupEntry::compareTo (const LootGroupEntry & lge) const inline
Loot Group Entries are sorted by their weights, in descending order. Thus, the greatest weight will be first.
Parameters
lge The loot group entry to compare.
Definition at line 36 of file LootGroupEntry.h.
References lootChance.
int LootGroupEntry::getLootChance () inline
Definition at line 60 of file LootGroupEntry.h.
References lootChance.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootFromCollection(), and TEST_F().
String& LootGroupEntry::getLootGroupName () inline
Definition at line 56 of file LootGroupEntry.h.
References templateName.
Referenced by server::zone::managers::loot::LootManagerImplementation::createLootFromCollection(), and TEST_F().
LootGroupEntry& LootGroupEntry::operator= (const LootGroupEntry & lge) inline
Definition at line 45 of file LootGroupEntry.h.
References lootChance, and templateName.
void LootGroupEntry::readObject (LuaObject * lua) inline
Definition at line 27 of file LootGroupEntry.h.
References lootChance, and templateName.
Referenced by LootGroups::readObject().
Member Data Documentation
int LootGroupEntry::lootChance private
Definition at line 15 of file LootGroupEntry.h.
Referenced by compareTo(), getLootChance(), LootGroupEntry(), operator=(), and readObject().
String LootGroupEntry::templateName private
Definition at line 14 of file LootGroupEntry.h.
Referenced by getLootGroupName(), LootGroupEntry(), operator=(), and readObject().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/loot/lootgroup/LootGroupEntry.h