Core3: AssetCustomizationManagerTemplate Class Reference
AssetCustomizationManagerTemplate Class Reference
#include <AssetCustomizationManagerTemplate.h>
Public Member Functions
AssetCustomizationManagerTemplate ()
~AssetCustomizationManagerTemplate ()
void readObject (IffStream *iffStream)
void getCustomizationVariables (uint32 appearanceFileCRC, VectorMap< String, Reference< CustomizationVariable * > > &variables, bool skipShared=false)
Public Member Functions inherited from IffTemplate
virtual ~IffTemplate ()
Public Member Functions inherited from TemplateData
virtual ~TemplateData ()
Private Member Functions
void parseCidxTable (IffStream *iffStream)
void parseLidxTable (IffStream *iffStream)
void parseLlstTable (IffStream *iffStream)
void parseUidxTable (IffStream *iffStream)
void parseUlstTable (IffStream *iffStream)
void parseUcmpTable (IffStream *iffStream)
void parseRtypTable (IffStream *iffStream)
void parseIrngTable (IffStream *iffStream)
void parseNameTable (IffStream *iffStream)
void parsePnofTable (IffStream *iffStream)
void parseVnofTable (IffStream *iffStream)
void parseDefvTable (IffStream *iffStream)
uint16 searchCidx (uint32 appearenceFileCRC)
void * searchLidx (uint16 cidxKey)
void * searchUidx (uint16 cidxKey)
void * getUCMPValue (uint16 index)
int getDEFVValue (byte index)
String getCustomizationVariableName (byte index)
String getStringFromNAME (uint16 index)
String getPaletteFileName (uint16 pnofIndex)
void getRTYP (byte a1, bool &pallete, uint16 &resultIndex)
void * getCustomizationVariablesFromMap (uint16 key, uint64 a2, bool skipSharedOwner, VectorMap< String, Reference< CustomizationVariable * > > &result)
Static Private Member Functions
static int cidxCompareFunction (const void *key, const void *value)
static int lidxCompareFunction (const void *key, const void *value)
Private Attributes
byte * ulstTable
int ulstTableCount
byte * ucmpTable
int ucmpTableCount
byte * vnofTable
int vnofTableCount
byte * pnofTable
int pnofTableCount
byte * defvTable
int defvTableCount
byte * irngTable
int irngTableCount
byte * nameTable
int nameTableCount
byte * rtypTable
int rtypTableCount
byte * uidxTable
int uidxTableCount
byte * llstTable
int llstTableCount
byte * lidxTable
int lidxTableCount
byte * cidxTable
int cidxTableCount
Detailed Description
Definition at line 16 of file AssetCustomizationManagerTemplate.h.
Constructor & Destructor Documentation
AssetCustomizationManagerTemplate::AssetCustomizationManagerTemplate ()
Definition at line 12 of file AssetCustomizationManagerTemplate.cpp.
References cidxTable, defvTable, irngTable, lidxTable, llstTable, nameTable, pnofTable, rtypTable, ucmpTable, uidxTable, ulstTable, and vnofTable.
AssetCustomizationManagerTemplate::~AssetCustomizationManagerTemplate ()
Definition at line 27 of file AssetCustomizationManagerTemplate.cpp.
References cidxTable, defvTable, irngTable, lidxTable, llstTable, nameTable, pnofTable, rtypTable, ucmpTable, uidxTable, ulstTable, and vnofTable.
Member Function Documentation
int AssetCustomizationManagerTemplate::cidxCompareFunction (const void * key, const void * value) static private
Definition at line 120 of file AssetCustomizationManagerTemplate.cpp.
Referenced by searchCidx().
String AssetCustomizationManagerTemplate::getCustomizationVariableName (byte index) private
Definition at line 168 of file AssetCustomizationManagerTemplate.cpp.
References getStringFromNAME(), and vnofTable.
Referenced by getCustomizationVariablesFromMap().
void AssetCustomizationManagerTemplate::getCustomizationVariables (uint32 appearanceFileCRC, VectorMap< String, Reference< CustomizationVariable * > > & variables, bool skipShared = false)
Definition at line 111 of file AssetCustomizationManagerTemplate.cpp.
References getCustomizationVariablesFromMap(), and searchCidx().
void * AssetCustomizationManagerTemplate::getCustomizationVariablesFromMap (uint16 key, uint64 a2, bool skipSharedOwner, VectorMap< String, Reference< CustomizationVariable * > > & result) private
Definition at line 42 of file AssetCustomizationManagerTemplate.cpp.
References defaultValue, getCustomizationVariableName(), getDEFVValue(), getPaletteFileName(), getRTYP(), getUCMPValue(), irngTable, llstTable, searchLidx(), searchUidx(), and ulstTable.
Referenced by getCustomizationVariables().
int AssetCustomizationManagerTemplate::getDEFVValue (byte index) private
Definition at line 176 of file AssetCustomizationManagerTemplate.cpp.
References defvTable.
Referenced by getCustomizationVariablesFromMap().
String AssetCustomizationManagerTemplate::getPaletteFileName (uint16 pnofIndex) private
Definition at line 142 of file AssetCustomizationManagerTemplate.cpp.
References getStringFromNAME(), and pnofTable.
Referenced by getCustomizationVariablesFromMap().
void AssetCustomizationManagerTemplate::getRTYP (byte a1, bool & pallete, uint16 & resultIndex) private
Definition at line 135 of file AssetCustomizationManagerTemplate.cpp.
References rtypTable.
Referenced by getCustomizationVariablesFromMap().
String AssetCustomizationManagerTemplate::getStringFromNAME (uint16 index) private
Definition at line 172 of file AssetCustomizationManagerTemplate.cpp.
References nameTable.
Referenced by getCustomizationVariableName(), and getPaletteFileName().
void * AssetCustomizationManagerTemplate::getUCMPValue (uint16 index) private
Definition at line 164 of file AssetCustomizationManagerTemplate.cpp.
References ucmpTable.
Referenced by getCustomizationVariablesFromMap().
int AssetCustomizationManagerTemplate::lidxCompareFunction (const void * key, const void * value) static private
Definition at line 131 of file AssetCustomizationManagerTemplate.cpp.
Referenced by searchLidx(), and searchUidx().
void AssetCustomizationManagerTemplate::parseCidxTable (IffStream * iffStream) private
Definition at line 202 of file AssetCustomizationManagerTemplate.cpp.
References cidxTable, and cidxTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::parseDefvTable (IffStream * iffStream) private
Definition at line 317 of file AssetCustomizationManagerTemplate.cpp.
References defvTable, and defvTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::parseIrngTable (IffStream * iffStream) private
Definition at line 273 of file AssetCustomizationManagerTemplate.cpp.
References irngTable, and irngTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::parseLidxTable (IffStream * iffStream) private
Definition at line 212 of file AssetCustomizationManagerTemplate.cpp.
References lidxTable, and lidxTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::parseLlstTable (IffStream * iffStream) private
Definition at line 222 of file AssetCustomizationManagerTemplate.cpp.
References llstTable, and llstTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::parseNameTable (IffStream * iffStream) private
Definition at line 284 of file AssetCustomizationManagerTemplate.cpp.
References nameTable, and nameTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::parsePnofTable (IffStream * iffStream) private
Definition at line 295 of file AssetCustomizationManagerTemplate.cpp.
References pnofTable, and pnofTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::parseRtypTable (IffStream * iffStream) private
Definition at line 262 of file AssetCustomizationManagerTemplate.cpp.
References rtypTable, and rtypTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::parseUcmpTable (IffStream * iffStream) private
Definition at line 252 of file AssetCustomizationManagerTemplate.cpp.
References ucmpTable, and ucmpTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::parseUidxTable (IffStream * iffStream) private
Definition at line 232 of file AssetCustomizationManagerTemplate.cpp.
References uidxTable, and uidxTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::parseUlstTable (IffStream * iffStream) private
Definition at line 242 of file AssetCustomizationManagerTemplate.cpp.
References ulstTable, and ulstTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::parseVnofTable (IffStream * iffStream) private
Definition at line 306 of file AssetCustomizationManagerTemplate.cpp.
References vnofTable, and vnofTableCount.
Referenced by readObject().
void AssetCustomizationManagerTemplate::readObject (IffStream * iffStream) virtual
Implements IffTemplate.
Definition at line 181 of file AssetCustomizationManagerTemplate.cpp.
References parseCidxTable(), parseDefvTable(), parseIrngTable(), parseLidxTable(), parseLlstTable(), parseNameTable(), parsePnofTable(), parseRtypTable(), parseUcmpTable(), parseUidxTable(), parseUlstTable(), and parseVnofTable().
uint16 AssetCustomizationManagerTemplate::searchCidx (uint32 appearenceFileCRC) private
Definition at line 146 of file AssetCustomizationManagerTemplate.cpp.
References cidxCompareFunction(), cidxTable, and cidxTableCount.
Referenced by getCustomizationVariables().
void * AssetCustomizationManagerTemplate::searchLidx (uint16 cidxKey) private
Definition at line 327 of file AssetCustomizationManagerTemplate.cpp.
References lidxCompareFunction(), lidxTable, and lidxTableCount.
Referenced by getCustomizationVariablesFromMap().
void * AssetCustomizationManagerTemplate::searchUidx (uint16 cidxKey) private
Definition at line 331 of file AssetCustomizationManagerTemplate.cpp.
References lidxCompareFunction(), uidxTable, and uidxTableCount.
Referenced by getCustomizationVariablesFromMap().
Member Data Documentation
byte* AssetCustomizationManagerTemplate::cidxTable private
Definition at line 50 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), parseCidxTable(), searchCidx(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::cidxTableCount private
Definition at line 51 of file AssetCustomizationManagerTemplate.h.
Referenced by parseCidxTable(), and searchCidx().
byte* AssetCustomizationManagerTemplate::defvTable private
Definition at line 29 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), getDEFVValue(), parseDefvTable(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::defvTableCount private
Definition at line 30 of file AssetCustomizationManagerTemplate.h.
Referenced by parseDefvTable().
byte* AssetCustomizationManagerTemplate::irngTable private
Definition at line 32 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), getCustomizationVariablesFromMap(), parseIrngTable(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::irngTableCount private
Definition at line 33 of file AssetCustomizationManagerTemplate.h.
Referenced by parseIrngTable().
byte* AssetCustomizationManagerTemplate::lidxTable private
Definition at line 47 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), parseLidxTable(), searchLidx(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::lidxTableCount private
Definition at line 48 of file AssetCustomizationManagerTemplate.h.
Referenced by parseLidxTable(), and searchLidx().
byte* AssetCustomizationManagerTemplate::llstTable private
Definition at line 44 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), getCustomizationVariablesFromMap(), parseLlstTable(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::llstTableCount private
Definition at line 45 of file AssetCustomizationManagerTemplate.h.
Referenced by parseLlstTable().
byte* AssetCustomizationManagerTemplate::nameTable private
Definition at line 35 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), getStringFromNAME(), parseNameTable(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::nameTableCount private
Definition at line 36 of file AssetCustomizationManagerTemplate.h.
Referenced by parseNameTable().
byte* AssetCustomizationManagerTemplate::pnofTable private
Definition at line 26 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), getPaletteFileName(), parsePnofTable(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::pnofTableCount private
Definition at line 27 of file AssetCustomizationManagerTemplate.h.
Referenced by parsePnofTable().
byte* AssetCustomizationManagerTemplate::rtypTable private
Definition at line 38 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), getRTYP(), parseRtypTable(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::rtypTableCount private
Definition at line 39 of file AssetCustomizationManagerTemplate.h.
Referenced by parseRtypTable().
byte* AssetCustomizationManagerTemplate::ucmpTable private
Definition at line 20 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), getUCMPValue(), parseUcmpTable(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::ucmpTableCount private
Definition at line 21 of file AssetCustomizationManagerTemplate.h.
Referenced by parseUcmpTable().
byte* AssetCustomizationManagerTemplate::uidxTable private
Definition at line 41 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), parseUidxTable(), searchUidx(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::uidxTableCount private
Definition at line 42 of file AssetCustomizationManagerTemplate.h.
Referenced by parseUidxTable(), and searchUidx().
byte* AssetCustomizationManagerTemplate::ulstTable private
Definition at line 17 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), getCustomizationVariablesFromMap(), parseUlstTable(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::ulstTableCount private
Definition at line 18 of file AssetCustomizationManagerTemplate.h.
Referenced by parseUlstTable().
byte* AssetCustomizationManagerTemplate::vnofTable private
Definition at line 23 of file AssetCustomizationManagerTemplate.h.
Referenced by AssetCustomizationManagerTemplate(), getCustomizationVariableName(), parseVnofTable(), and ~AssetCustomizationManagerTemplate().
int AssetCustomizationManagerTemplate::vnofTableCount private
Definition at line 24 of file AssetCustomizationManagerTemplate.h.
Referenced by parseVnofTable().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/customization/AssetCustomizationManagerTemplate.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/customization/AssetCustomizationManagerTemplate.cpp