Core3: server::chat::ChatManagerImplementation Class Reference
server::chat::ChatManagerImplementation Class Reference
#include <ChatManager.h>
Public Member Functions
ChatManagerImplementation (ZoneServer *serv, int initsize)
ChatManagerImplementation (DummyConstructorParameter *param)
void finalize ()
void initiateRooms ()
void initiatePlanetRooms ()
void destroyRooms ()
ChatRoom * createRoom (const String &roomName, ChatRoom *parent=NULL)
void addRoom (ChatRoom *channel)
void removeRoom (ChatRoom *channel)
void populateRoomListMessage (ChatRoom *channel, ChatRoomList *msg)
void sendRoomList (CreatureObject *player)
void addPlayer (CreatureObject *player)
CreatureObject * getPlayer (const String &name)
CreatureObject * removePlayer (const String &name)
void broadcastMessage (BaseMessage *message)
void broadcastMessage (CreatureObject *player, const UnicodeString &message, unsigned long long target=0, unsigned int moodid=0, unsigned int mood2=0)
void handleSpatialChatInternalMessage (CreatureObject *player, const UnicodeString &args)
void handleGroupChat (CreatureObject *player, const UnicodeString &message)
void handleGuildChat (CreatureObject *player, const UnicodeString &message)
void handlePlanetChat (CreatureObject *player, const UnicodeString &message)
ChatRoom * createRoomByFullPath (const String &path)
ChatRoom * getChatRoomByFullPath (const String &path)
ChatRoom * getChatRoomByGamePath (ChatRoom *game, const String &path)
void handleChatRoomMessage (CreatureObject *sender, const UnicodeString &message, unsigned int roomID, unsigned int counter)
void handleChatEnterRoomById (CreatureObject *player, unsigned int counter, unsigned int roomID)
void handleSocialInternalMessage (CreatureObject *sender, const UnicodeString &arguments)
void handleChatInstantMessageToCharacter (ChatInstantMessageToCharacter *message)
void destroyRoom (ChatRoom *room)
ChatRoom * createGroupRoom (unsigned long long groupID, CreatureObject *creator)
void loadMail (CreatureObject *player)
void sendMail (const String &sendername, const UnicodeString &header, const UnicodeString &body, const String &name)
int sendMail (const String &sendername, const UnicodeString &subject, StringIdChatParameter &body, const String &recipientName, WaypointObject *waypoint=NULL)
int sendMail (const String &sendername, const UnicodeString &subject, const UnicodeString &body, const String &recipientName, StringIdChatParameterVector *stringIdParameters, WaypointChatParameterVector *waypointParameters)
void handleRequestPersistentMsg (CreatureObject *player, unsigned int mailID)
void deletePersistentMessage (CreatureObject *player, unsigned int mailID)
void broadcastGalaxy (CreatureObject *player, const String &message)
void broadcastGalaxy (const String &message, const String &faction)
void setPlayerManager (PlayerManager *manager)
ChatRoom * getChatRoom (unsigned int id)
ChatRoom * getGameRoom (const String &game)
unsigned int getNextRoomID ()
int getPlayerCount ()
PlayerMap * getPlayerMap ()
ChatRoom * getGuildRoom ()
ChatRoom * getGroupRoom ()
operator const ChatManager * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< ChatManager * > _this
Static Public Attributes
static const int IM_SUCCESS = 0x00
static const int IM_OFFLINE = 0x04
static const int IM_IGNORED = 0x09
static const int IM_TOOLONG = 0x10
static const int IM_MAXSIZE = 255
static const int PM_MAXSIZE = 4000
Protected Member Functions
virtual ~ChatManagerImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Private Attributes
ManagedReference< ZoneServer * > server
ManagedReference< PlayerManager * > playerManager
Reference< PlayerMap * > playerMap
VectorMap< String,
ManagedReference< ChatRoom * > > gameRooms
ManagedReference< ChatRoom * > groupRoom
ManagedReference< ChatRoom * > guildRoom
ManagedReference< ChatRoom * > core3Room
Reference< ChatRoomMap * > roomMap
unsigned int roomID
bool mute
Friends
class ChatManager
Detailed Description
Definition at line 308 of file ChatManager.h.
Constructor & Destructor Documentation
ChatManagerImplementation::ChatManagerImplementation (ZoneServer * serv, int initsize)
Definition at line 36 of file ChatManagerImplementation.cpp.
References mute, playerManager, playerMap, roomID, roomMap, and server.
ChatManagerImplementation::ChatManagerImplementation (DummyConstructorParameter * param)
Definition at line 655 of file ChatManager.cpp.
References _initializeImplementation().
ChatManagerImplementation::~ChatManagerImplementation () protected virtual
Definition at line 660 of file ChatManager.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * ChatManagerImplementation::_getStub ()
Definition at line 678 of file ChatManager.cpp.
References _this.
void ChatManagerImplementation::_initializeImplementation () protected
Definition at line 665 of file ChatManager.cpp.
References _serializationHelperMethod(), and _this.
Referenced by ChatManagerImplementation().
void ChatManagerImplementation::_serializationHelperMethod () protected
Definition at line 714 of file ChatManager.cpp.
Referenced by _initializeImplementation().
void ChatManagerImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 673 of file ChatManager.cpp.
References _this.
Referenced by server::chat::ChatManager::ChatManager().
void ChatManagerImplementation::addPlayer (CreatureObject * player)
Definition at line 337 of file ChatManagerImplementation.cpp.
References _this, server::zone::objects::creature::CreatureObject::getFirstName(), and playerMap.
Referenced by server::chat::ChatManager::addPlayer().
void ChatManagerImplementation::addRoom (ChatRoom * channel)
Definition at line 863 of file ChatManager.cpp.
References _this, server::chat::room::ChatRoom::getRoomID(), and roomMap.
Referenced by server::chat::ChatManager::addRoom(), and createRoom().
void ChatManagerImplementation::broadcastGalaxy (CreatureObject * player, const String & message)
Definition at line 386 of file ChatManagerImplementation.cpp.
References _this, server::zone::objects::creature::CreatureObject::getFirstName(), and playerMap.
Referenced by server::chat::ChatManager::broadcastGalaxy().
void ChatManagerImplementation::broadcastGalaxy (const String & message, const String & faction)
Definition at line 371 of file ChatManagerImplementation.cpp.
References _this, and playerMap.
void ChatManagerImplementation::broadcastMessage (BaseMessage * message)
Definition at line 407 of file ChatManagerImplementation.cpp.
References _this, and playerMap.
Referenced by server::chat::ChatManager::broadcastMessage(), and handleSpatialChatInternalMessage().
void server::chat::ChatManagerImplementation::broadcastMessage (CreatureObject * player, const UnicodeString & message, unsigned long long target = 0, unsigned int moodid = 0, unsigned int mood2 = 0)
ChatRoom * ChatManagerImplementation::createGroupRoom (unsigned long long groupID, CreatureObject * creator)
Definition at line 603 of file ChatManagerImplementation.cpp.
References server::chat::room::ChatRoom::addSubRoom(), createRoom(), groupRoom, and server::chat::room::ChatRoom::setPrivate().
Referenced by server::chat::ChatManager::createGroupRoom().
ChatRoom * ChatManagerImplementation::createRoom (const String & roomName, ChatRoom * parent = NULL)
Definition at line 67 of file ChatManagerImplementation.cpp.
References addRoom(), getNextRoomID(), server::chat::room::ChatRoom::init(), and server.
Referenced by createGroupRoom(), server::chat::ChatManager::createRoom(), createRoomByFullPath(), initiatePlanetRooms(), and initiateRooms().
ChatRoom * ChatManagerImplementation::createRoomByFullPath (const String & path)
Definition at line 121 of file ChatManagerImplementation.cpp.
References server::chat::room::ChatRoom::addSubRoom(), createRoom(), getGameRoom(), server::chat::room::ChatRoom::getSubRoom(), and server::chat::room::ChatRoom::isPrivate().
Referenced by server::chat::ChatManager::createRoomByFullPath().
void ChatManagerImplementation::deletePersistentMessage (CreatureObject * player, unsigned int mailID)
Definition at line 950 of file ChatManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::getPersistentMessages(), and server::zone::objects::creature::CreatureObject::getPlayerObject().
Referenced by server::chat::ChatManager::deletePersistentMessage().
void ChatManagerImplementation::destroyRoom (ChatRoom * room)
Definition at line 629 of file ChatManagerImplementation.cpp.
References _this, server::chat::room::ChatRoom::broadcastMessage(), server::chat::room::ChatRoom::getParent(), server::chat::room::ChatRoom::getRoomID(), server::chat::room::ChatRoom::removeAllPlayers(), server::chat::room::ChatRoom::removeSubRoom(), roomMap, and server.
Referenced by server::chat::ChatManager::destroyRoom().
void ChatManagerImplementation::destroyRooms ()
Definition at line 200 of file ChatManagerImplementation.cpp.
References _this, gameRooms, and roomMap.
Referenced by server::chat::ChatManager::destroyRooms().
void ChatManagerImplementation::finalize ()
Definition at line 64 of file ChatManagerImplementation.cpp.
Referenced by ~ChatManagerImplementation().
ChatRoom * ChatManagerImplementation::getChatRoom (unsigned int id)
Definition at line 880 of file ChatManager.cpp.
References _this, and roomMap.
Referenced by server::chat::ChatManager::getChatRoom(), handleChatEnterRoomById(), and handleChatRoomMessage().
ChatRoom * ChatManagerImplementation::getChatRoomByFullPath (const String & path)
Definition at line 178 of file ChatManagerImplementation.cpp.
References getChatRoomByGamePath(), and getGameRoom().
Referenced by server::chat::ChatManager::getChatRoomByFullPath().
ChatRoom * ChatManagerImplementation::getChatRoomByGamePath (ChatRoom * game, const String & path)
Definition at line 157 of file ChatManagerImplementation.cpp.
References server::chat::room::ChatRoom::getSubRoom().
Referenced by getChatRoomByFullPath(), and server::chat::ChatManager::getChatRoomByGamePath().
ChatRoom * ChatManagerImplementation::getGameRoom (const String & game)
Definition at line 886 of file ChatManager.cpp.
References _this, and gameRooms.
Referenced by createRoomByFullPath(), getChatRoomByFullPath(), and server::chat::ChatManager::getGameRoom().
ChatRoom * ChatManagerImplementation::getGroupRoom ()
Returns the parent room for group chat rooms.
Definition at line 913 of file ChatManager.cpp.
References groupRoom.
Referenced by server::chat::ChatManager::getGroupRoom().
ChatRoom * ChatManagerImplementation::getGuildRoom ()
Returns the parent room for guild chat rooms.
Definition at line 908 of file ChatManager.cpp.
References guildRoom.
Referenced by server::chat::ChatManager::getGuildRoom().
unsigned int ChatManagerImplementation::getNextRoomID ()
Definition at line 892 of file ChatManager.cpp.
References _this, and roomID.
Referenced by createRoom(), and server::chat::ChatManager::getNextRoomID().
CreatureObject * ChatManagerImplementation::getPlayer (const String & name)
Definition at line 344 of file ChatManagerImplementation.cpp.
References _this, and playerMap.
Referenced by server::chat::ChatManager::getPlayer(), and handleChatInstantMessageToCharacter().
int ChatManagerImplementation::getPlayerCount ()
Definition at line 898 of file ChatManager.cpp.
References playerMap.
Referenced by server::chat::ChatManager::getPlayerCount().
PlayerMap * ChatManagerImplementation::getPlayerMap ()
Definition at line 903 of file ChatManager.cpp.
References playerMap.
Referenced by server::chat::ChatManager::getPlayerMap().
void ChatManagerImplementation::handleChatEnterRoomById (CreatureObject * player, unsigned int counter, unsigned int roomID)
Definition at line 255 of file ChatManagerImplementation.cpp.
References getChatRoom().
Referenced by server::chat::ChatManager::handleChatEnterRoomById().
void ChatManagerImplementation::handleChatInstantMessageToCharacter (ChatInstantMessageToCharacter * message)
Definition at line 563 of file ChatManagerImplementation.cpp.
References server::zone::packets::MessageCallback::getClient(), server::zone::packets::chat::ChatInstantMessageToCharacter::getMessage(), server::zone::packets::chat::ChatInstantMessageToCharacter::getName(), server::zone::ZoneClientSession::getPlayer(), getPlayer(), server::zone::packets::chat::ChatInstantMessageToCharacter::getSequence(), IM_IGNORED, IM_MAXSIZE, IM_OFFLINE, IM_SUCCESS, and IM_TOOLONG.
Referenced by server::chat::ChatManager::handleChatInstantMessageToCharacter().
void ChatManagerImplementation::handleChatRoomMessage (CreatureObject * sender, const UnicodeString & message, unsigned int roomID, unsigned int counter)
Definition at line 226 of file ChatManagerImplementation.cpp.
References server::chat::room::ChatRoom::broadcastMessage(), getChatRoom(), server::zone::objects::creature::CreatureObject::getFirstName(), and server::chat::room::ChatRoom::hasPlayer().
Referenced by server::chat::ChatManager::handleChatRoomMessage().
void ChatManagerImplementation::handleGroupChat (CreatureObject * player, const UnicodeString & message)
Definition at line 645 of file ChatManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getGroup(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::chat::ChatManager::handleGroupChat().
void ChatManagerImplementation::handleGuildChat (CreatureObject * player, const UnicodeString & message)
Definition at line 687 of file ChatManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::creature::CreatureObject::getGuildObject(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::chat::ChatManager::handleGuildChat().
void ChatManagerImplementation::handlePlanetChat (CreatureObject * player, const UnicodeString & message)
Definition at line 715 of file ChatManagerImplementation.cpp.
References server::zone::Zone::getChatRoom(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::scene::SceneObject::getZone(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::chat::ChatManager::handlePlanetChat().
void ChatManagerImplementation::handleRequestPersistentMsg (CreatureObject * player, unsigned int mailID)
Definition at line 916 of file ChatManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::getPersistentMessages(), server::zone::objects::creature::CreatureObject::getPlayerObject(), and server::chat::PersistentMessage::setStatus().
Referenced by server::chat::ChatManager::handleRequestPersistentMsg().
void ChatManagerImplementation::handleSocialInternalMessage (CreatureObject * sender, const UnicodeString & arguments)
Definition at line 264 of file ChatManagerImplementation.cpp.
References server::zone::Zone::getInRangeObjects(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::scene::SceneObject::getWorldPositionX(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::scene::SceneObject::isPlayerCreature(), server::zone::objects::creature::CreatureObject::isPlayerCreature(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::chat::ChatManager::handleSocialInternalMessage().
void ChatManagerImplementation::handleSpatialChatInternalMessage (CreatureObject * player, const UnicodeString & args)
Definition at line 521 of file ChatManagerImplementation.cpp.
References broadcastMessage(), and ObserverEventType::CHAT.
Referenced by server::chat::ChatManager::handleSpatialChatInternalMessage().
void ChatManagerImplementation::initiatePlanetRooms ()
Definition at line 101 of file ChatManagerImplementation.cpp.
References server::chat::room::ChatRoom::addSubRoom(), core3Room, createRoom(), and server.
Referenced by server::chat::ChatManager::initiatePlanetRooms().
void ChatManagerImplementation::initiateRooms ()
Definition at line 76 of file ChatManagerImplementation.cpp.
References server::chat::room::ChatRoom::addSubRoom(), core3Room, createRoom(), gameRooms, groupRoom, guildRoom, server, and server::chat::room::ChatRoom::setPrivate().
Referenced by server::chat::ChatManager::initiateRooms().
void ChatManagerImplementation::loadMail (CreatureObject * player)
Definition at line 895 of file ChatManagerImplementation.cpp.
References server::zone::objects::player::PlayerObject::getPersistentMessages(), server::zone::objects::creature::CreatureObject::getPlayerObject(), and server::chat::PersistentMessage::sendTo().
Referenced by server::chat::ChatManager::loadMail().
void ChatManagerImplementation::lock (bool doLock = true) protected
Definition at line 686 of file ChatManager.cpp.
References _this.
void ChatManagerImplementation::lock (ManagedObject * obj) protected
Definition at line 690 of file ChatManager.cpp.
References _this.
ChatManagerImplementation::operator const ChatManager * ()
Definition at line 682 of file ChatManager.cpp.
void ChatManagerImplementation::populateRoomListMessage (ChatRoom * channel, ChatRoomList * msg)
Definition at line 215 of file ChatManagerImplementation.cpp.
References server::zone::packets::chat::ChatRoomList::addChannel(), server::chat::room::ChatRoom::getSubRoom(), server::chat::room::ChatRoom::getSubRoomsSize(), and server::chat::room::ChatRoom::isPublic().
Referenced by server::chat::ChatManager::populateRoomListMessage(), and sendRoomList().
void ChatManagerImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 721 of file ChatManager.cpp.
References readObjectMember().
bool ChatManagerImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 740 of file ChatManager.cpp.
References core3Room, gameRooms, groupRoom, guildRoom, mute, playerManager, roomID, and server.
Referenced by readObject().
CreatureObject * ChatManagerImplementation::removePlayer (const String & name)
Definition at line 361 of file ChatManagerImplementation.cpp.
References _this, and playerMap.
Referenced by server::chat::ChatManager::removePlayer().
void ChatManagerImplementation::removeRoom (ChatRoom * channel)
Definition at line 869 of file ChatManager.cpp.
References _this, server::chat::room::ChatRoom::getRoomID(), and roomMap.
Referenced by server::chat::ChatManager::removeRoom().
void ChatManagerImplementation::rlock (bool doLock = true) protected
Definition at line 694 of file ChatManager.cpp.
References _this.
void ChatManagerImplementation::runlock (bool doLock = true) protected
Definition at line 710 of file ChatManager.cpp.
References _this.
void ChatManagerImplementation::sendMail (const String & sendername, const UnicodeString & header, const UnicodeString & body, const String & name)
Definition at line 742 of file ChatManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), playerManager, and server.
Referenced by server::chat::ChatManager::sendMail().
int ChatManagerImplementation::sendMail (const String & sendername, const UnicodeString & subject, StringIdChatParameter & body, const String & recipientName, WaypointObject * waypoint = NULL)
Definition at line 853 of file ChatManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), IM_IGNORED, IM_OFFLINE, IM_SUCCESS, playerManager, and server.
int ChatManagerImplementation::sendMail (const String & sendername, const UnicodeString & subject, const UnicodeString & body, const String & recipientName, StringIdChatParameterVector * stringIdParameters, WaypointChatParameterVector * waypointParameters)
Definition at line 795 of file ChatManagerImplementation.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), IM_IGNORED, IM_OFFLINE, IM_SUCCESS, IM_TOOLONG, playerManager, PM_MAXSIZE, and server.
void ChatManagerImplementation::sendRoomList (CreatureObject * player)
Definition at line 327 of file ChatManagerImplementation.cpp.
References gameRooms, server::zone::packets::chat::ChatRoomList::insertChannelListCount(), populateRoomListMessage(), and server::zone::objects::creature::CreatureObject::sendMessage().
Referenced by server::chat::ChatManager::sendRoomList().
void ChatManagerImplementation::setPlayerManager (PlayerManager * manager)
Definition at line 875 of file ChatManager.cpp.
References playerManager.
Referenced by server::chat::ChatManager::setPlayerManager().
void ChatManagerImplementation::unlock (bool doLock = true) protected
Definition at line 706 of file ChatManager.cpp.
References _this.
void ChatManagerImplementation::wlock (bool doLock = true) protected
Definition at line 698 of file ChatManager.cpp.
References _this.
void ChatManagerImplementation::wlock (ManagedObject * obj) protected
Definition at line 702 of file ChatManager.cpp.
References _this.
void ChatManagerImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 782 of file ChatManager.cpp.
References writeObjectMembers().
int ChatManagerImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 789 of file ChatManager.cpp.
References core3Room, gameRooms, groupRoom, guildRoom, mute, playerManager, roomID, and server.
Referenced by writeObject().
Friends And Related Function Documentation
friend class ChatManager friend
Definition at line 470 of file ChatManager.h.
Member Data Documentation
WeakReference<ChatManager*> server::chat::ChatManagerImplementation::_this
Definition at line 438 of file ChatManager.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addPlayer(), addRoom(), broadcastGalaxy(), broadcastMessage(), destroyRoom(), destroyRooms(), getChatRoom(), getGameRoom(), getNextRoomID(), getPlayer(), lock(), removePlayer(), removeRoom(), rlock(), runlock(), unlock(), and wlock().
ManagedReference<ChatRoom* > server::chat::ChatManagerImplementation::core3Room private
Definition at line 321 of file ChatManager.h.
Referenced by initiatePlanetRooms(), initiateRooms(), readObjectMember(), and writeObjectMembers().
VectorMap<String, ManagedReference<ChatRoom* > > server::chat::ChatManagerImplementation::gameRooms private
Definition at line 315 of file ChatManager.h.
Referenced by destroyRooms(), getGameRoom(), initiateRooms(), readObjectMember(), sendRoomList(), and writeObjectMembers().
ManagedReference<ChatRoom* > server::chat::ChatManagerImplementation::groupRoom private
Definition at line 317 of file ChatManager.h.
Referenced by createGroupRoom(), getGroupRoom(), initiateRooms(), readObjectMember(), and writeObjectMembers().
ManagedReference<ChatRoom* > server::chat::ChatManagerImplementation::guildRoom private
Definition at line 319 of file ChatManager.h.
Referenced by getGuildRoom(), initiateRooms(), readObjectMember(), and writeObjectMembers().
const int server::chat::ChatManagerImplementation::IM_IGNORED = 0x09 static
Definition at line 334 of file ChatManager.h.
Referenced by handleChatInstantMessageToCharacter(), and sendMail().
const int server::chat::ChatManagerImplementation::IM_MAXSIZE = 255 static
Definition at line 338 of file ChatManager.h.
Referenced by handleChatInstantMessageToCharacter().
const int server::chat::ChatManagerImplementation::IM_OFFLINE = 0x04 static
Definition at line 332 of file ChatManager.h.
Referenced by handleChatInstantMessageToCharacter(), and sendMail().
const int server::chat::ChatManagerImplementation::IM_SUCCESS = 0x00 static
Definition at line 330 of file ChatManager.h.
Referenced by handleChatInstantMessageToCharacter(), and sendMail().
const int server::chat::ChatManagerImplementation::IM_TOOLONG = 0x10 static
Definition at line 336 of file ChatManager.h.
Referenced by handleChatInstantMessageToCharacter(), and sendMail().
bool server::chat::ChatManagerImplementation::mute private
Definition at line 327 of file ChatManager.h.
Referenced by ChatManagerImplementation(), readObjectMember(), and writeObjectMembers().
ManagedReference<PlayerManager* > server::chat::ChatManagerImplementation::playerManager private
Definition at line 311 of file ChatManager.h.
Referenced by ChatManagerImplementation(), readObjectMember(), sendMail(), setPlayerManager(), and writeObjectMembers().
Reference<PlayerMap* > server::chat::ChatManagerImplementation::playerMap private
Definition at line 313 of file ChatManager.h.
Referenced by addPlayer(), broadcastGalaxy(), broadcastMessage(), ChatManagerImplementation(), getPlayer(), getPlayerCount(), getPlayerMap(), and removePlayer().
const int server::chat::ChatManagerImplementation::PM_MAXSIZE = 4000 static
Definition at line 340 of file ChatManager.h.
Referenced by sendMail().
unsigned int server::chat::ChatManagerImplementation::roomID private
Definition at line 325 of file ChatManager.h.
Referenced by ChatManagerImplementation(), getNextRoomID(), readObjectMember(), and writeObjectMembers().
Reference<ChatRoomMap* > server::chat::ChatManagerImplementation::roomMap private
Definition at line 323 of file ChatManager.h.
Referenced by addRoom(), ChatManagerImplementation(), destroyRoom(), destroyRooms(), getChatRoom(), and removeRoom().
ManagedReference<ZoneServer* > server::chat::ChatManagerImplementation::server private
Definition at line 309 of file ChatManager.h.
Referenced by ChatManagerImplementation(), createRoom(), destroyRoom(), initiatePlanetRooms(), initiateRooms(), readObjectMember(), sendMail(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatManager.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/chat/ChatManagerImplementation.cpp