Core3: server::zone::managers::guild::GuildManager Class Reference
server::zone::managers::guild::GuildManager Class Reference
#include <GuildManager.h>
Public Member Functions
GuildManager (ZoneServer *serv, ZoneProcessServer *proc)
void setChatManager (ChatManager *chatmanager)
void sendGuildListTo (CreatureObject *player, const String &guildFilter)
void addPendingGuild (unsigned long long playerID, const String &guildName)
void removePendingGuild (unsigned long long playerID)
String getPendingGuildName (unsigned long long playerID)
void addSponsoredPlayer (unsigned long long playerID, GuildObject *guild)
void removeSponsoredPlayer (unsigned long long playerID)
bool isCreatingGuild (unsigned long long playerID)
bool isSponsoredPlayer (unsigned long long playerID)
GuildObject * getSponsoredGuild (unsigned long long playerID)
void sendBaselinesTo (CreatureObject *player)
void loadGuilds ()
void sendGuildCreateNameTo (CreatureObject *player, GuildTerminal *guildTerminal)
void sendGuildCreateAbbrevTo (CreatureObject *player, GuildTerminal *guildTerminal)
void sendGuildInformationTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildMemberListTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildMemberOptionsTo (CreatureObject *player, GuildObject *guild, unsigned long long memberID, GuildTerminal *guildTerminal)
void sendGuildDisbandConfirmTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildSponsoredListTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildSponsoredOptionsTo (CreatureObject *player, GuildObject *guild, unsigned long long playerID, GuildTerminal *guildTerminal)
void sendGuildSponsorTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void sendGuildSponsorVerifyTo (CreatureObject *player, CreatureObject *target)
void sendGuildKickPromptTo (CreatureObject *player, CreatureObject *target)
void sendGuildSetTitleTo (CreatureObject *player, CreatureObject *target)
void sendGuildWarStatusTo (CreatureObject *player, GuildObject *guild, GuildTerminal *guildTerminal)
void promptAddNewEnemy (CreatureObject *player, GuildObject *guild, SceneObject *terminal)
void toggleWarStatus (CreatureObject *player, GuildObject *guild, unsigned long long guildoid)
void declareWarByName (CreatureObject *player, GuildObject *guild, const String &search)
void updateWarStatusToWaringGuild (GuildObject *guild, GuildObject *waringGuild)
void sendMemberPermissionsTo (CreatureObject *player, unsigned long long targetID, GuildTerminal *guildTerminal)
bool validateGuildName (CreatureObject *player, const String &guildName)
bool validateGuildAbbrev (CreatureObject *player, const String &guildAbbrev)
bool guildNameExists (const String &guildName)
bool guildAbbrevExists (const String &guildAbbrev)
GuildObject * createGuild (CreatureObject *player, GuildTerminal *guildTerminal, const String &guildName, const String &guildAbbrev)
bool disbandGuild (CreatureObject *player, GuildObject *guild)
void sponsorPlayer (CreatureObject *player, GuildTerminal *guildTerminal, const String &playerName)
void acceptSponsorshipRequest (CreatureObject *player, CreatureObject *target)
void acceptSponsoredPlayer (CreatureObject *player, unsigned long long targetID)
void kickMember (CreatureObject *player, CreatureObject *target)
void leaveGuild (CreatureObject *player, GuildObject *guild)
void setMemberTitle (CreatureObject *player, CreatureObject *target, const String &title)
void setAllegianceTo (CreatureObject *player, unsigned long long targetID, GuildTerminal *guildTerminal)
void toggleGuildPermission (CreatureObject *player, unsigned long long targetID, int permissionIndex, GuildTerminal *guildTerminal)
ChatRoom * createGuildChannels (GuildObject *guild)
void sendGuildTransferTo (CreatureObject *player, GuildTerminal *guildTerminal)
void sendTransferAckTo (CreatureObject *player, const String &newOwnerName, SceneObject *guildTerminal)
void transferLeadership (CreatureObject *newOwner, CreatureObject *oldOwner, SceneObject *guildTerminal)
void sendAcceptLotsTo (CreatureObject *newOwner, GuildTerminal *guildTerminal)
void transferGuildHall (CreatureObject *newOwner, SceneObject *guildTerminal)
void sendGuildMail (const String &subject, StringIdChatParameter &body, GuildObject *guild)
GuildObject * getGuildFromAbbrev (const String &guildAbbrev)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
GuildManager (DummyConstructorParameter *param)
virtual ~GuildManager ()
Friends
class GuildManagerHelper
Detailed Description
Definition at line 117 of file GuildManager.h.
Constructor & Destructor Documentation
GuildManager::GuildManager (ZoneServer * serv, ZoneProcessServer * proc)
Definition at line 27 of file GuildManager.cpp.
References server::zone::managers::guild::GuildManagerImplementation::_setStub().
GuildManager::GuildManager (DummyConstructorParameter * param) protected
Definition at line 34 of file GuildManager.cpp.
GuildManager::~GuildManager () protected virtual
Definition at line 38 of file GuildManager.cpp.
Member Function Documentation
DistributedObjectServant * GuildManager::_getImplementation ()
Definition at line 828 of file GuildManager.cpp.
Referenced by acceptSponsoredPlayer(), acceptSponsorshipRequest(), addPendingGuild(), addSponsoredPlayer(), createGuild(), createGuildChannels(), declareWarByName(), disbandGuild(), getGuildFromAbbrev(), getPendingGuildName(), getSponsoredGuild(), guildAbbrevExists(), guildNameExists(), isCreatingGuild(), isSponsoredPlayer(), kickMember(), leaveGuild(), loadGuilds(), promptAddNewEnemy(), removePendingGuild(), removeSponsoredPlayer(), sendAcceptLotsTo(), sendBaselinesTo(), sendGuildCreateAbbrevTo(), sendGuildCreateNameTo(), sendGuildDisbandConfirmTo(), sendGuildInformationTo(), sendGuildKickPromptTo(), sendGuildListTo(), sendGuildMail(), sendGuildMemberListTo(), sendGuildMemberOptionsTo(), sendGuildSetTitleTo(), sendGuildSponsoredListTo(), sendGuildSponsoredOptionsTo(), sendGuildSponsorTo(), sendGuildSponsorVerifyTo(), sendGuildTransferTo(), sendGuildWarStatusTo(), sendMemberPermissionsTo(), sendTransferAckTo(), setAllegianceTo(), setChatManager(), setMemberTitle(), sponsorPlayer(), toggleGuildPermission(), toggleWarStatus(), transferGuildHall(), transferLeadership(), updateWarStatusToWaringGuild(), validateGuildAbbrev(), and validateGuildName().
DistributedObjectServant * GuildManager::_getImplementationForRead ()
Definition at line 834 of file GuildManager.cpp.
void GuildManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 838 of file GuildManager.cpp.
void GuildManager::acceptSponsoredPlayer (CreatureObject * player, unsigned long long targetID)
Definition at line 620 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsoredPlayer(), and RPC_ACCEPTSPONSOREDPLAYER__CREATUREOBJECT_LONG_.
void GuildManager::acceptSponsorshipRequest (CreatureObject * player, CreatureObject * target)
Definition at line 605 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::acceptSponsorshipRequest(), and RPC_ACCEPTSPONSORSHIPREQUEST__CREATUREOBJECT_CREATUREOBJECT_.
void GuildManager::addPendingGuild (unsigned long long playerID, const String & guildName)
Definition at line 72 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::addPendingGuild(), and RPC_ADDPENDINGGUILD__LONG_STRING_.
void GuildManager::addSponsoredPlayer (unsigned long long playerID, GuildObject * guild)
Definition at line 117 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::addSponsoredPlayer(), and RPC_ADDSPONSOREDPLAYER__LONG_GUILDOBJECT_.
GuildObject * GuildManager::createGuild (CreatureObject * player, GuildTerminal * guildTerminal, const String & guildName, const String & guildAbbrev)
Definition at line 557 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::createGuild(), and RPC_CREATEGUILD__CREATUREOBJECT_GUILDTERMINAL_STRING_STRING_.
ChatRoom * GuildManager::createGuildChannels (GuildObject * guild)
Definition at line 714 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::createGuildChannels(), and RPC_CREATEGUILDCHANNELS__GUILDOBJECT_.
void GuildManager::declareWarByName (CreatureObject * player, GuildObject * guild, const String & search)
Definition at line 452 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::declareWarByName(), and RPC_DECLAREWARBYNAME__CREATUREOBJECT_GUILDOBJECT_STRING_.
bool GuildManager::disbandGuild (CreatureObject * player, GuildObject * guild)
Definition at line 574 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::disbandGuild(), and RPC_DISBANDGUILD__CREATUREOBJECT_GUILDOBJECT_.
GuildObject * GuildManager::getGuildFromAbbrev (const String & guildAbbrev)
Definition at line 814 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::getGuildFromAbbrev(), and RPC_GETGUILDFROMABBREV__STRING_.
String GuildManager::getPendingGuildName (unsigned long long playerID)
Definition at line 101 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::getPendingGuildName(), and RPC_GETPENDINGGUILDNAME__LONG_.
GuildObject * GuildManager::getSponsoredGuild (unsigned long long playerID)
Definition at line 174 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::getSponsoredGuild(), and RPC_GETSPONSOREDGUILD__LONG_.
bool GuildManager::guildAbbrevExists (const String & guildAbbrev)
Definition at line 543 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::guildAbbrevExists(), and RPC_GUILDABBREVEXISTS__STRING_.
bool GuildManager::guildNameExists (const String & guildName)
Definition at line 529 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::guildNameExists(), and RPC_GUILDNAMEEXISTS__STRING_.
bool GuildManager::isCreatingGuild (unsigned long long playerID)
Definition at line 146 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::isCreatingGuild(), and RPC_ISCREATINGGUILD__LONG_.
bool GuildManager::isSponsoredPlayer (unsigned long long playerID)
Definition at line 160 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::isSponsoredPlayer(), and RPC_ISSPONSOREDPLAYER__LONG_.
void GuildManager::kickMember (CreatureObject * player, CreatureObject * target)
Definition at line 635 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::kickMember(), and RPC_KICKMEMBER__CREATUREOBJECT_CREATUREOBJECT_.
void GuildManager::leaveGuild (CreatureObject * player, GuildObject * guild)
Definition at line 650 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::leaveGuild(), and RPC_LEAVEGUILD__CREATUREOBJECT_GUILDOBJECT_.
void GuildManager::loadGuilds ()
Definition at line 202 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::loadGuilds(), and RPC_LOADGUILDS__.
void GuildManager::promptAddNewEnemy (CreatureObject * player, GuildObject * guild, SceneObject * terminal)
Definition at line 420 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::promptAddNewEnemy(), and RPC_PROMPTADDNEWENEMY__CREATUREOBJECT_GUILDOBJECT_SCENEOBJECT_.
void GuildManager::removePendingGuild (unsigned long long playerID)
Definition at line 87 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::removePendingGuild(), and RPC_REMOVEPENDINGGUILD__LONG_.
void GuildManager::removeSponsoredPlayer (unsigned long long playerID)
Definition at line 132 of file GuildManager.cpp.
References _getImplementation(), server::zone::managers::guild::GuildManagerImplementation::removeSponsoredPlayer(), and RPC_REMOVESPONSOREDPLAYER__LONG_.
void GuildManager::sendAcceptLotsTo (CreatureObject * newOwner, GuildTerminal * guildTerminal)
Definition at line 775 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDACCEPTLOTSTO__CREATUREOBJECT_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendAcceptLotsTo().
void GuildManager::sendBaselinesTo (CreatureObject * player)
Definition at line 188 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDBASELINESTO__CREATUREOBJECT_, and server::zone::managers::guild::GuildManagerImplementation::sendBaselinesTo().
void GuildManager::sendGuildCreateAbbrevTo (CreatureObject * player, GuildTerminal * guildTerminal)
Definition at line 230 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDCREATEABBREVTO__CREATUREOBJECT_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildCreateAbbrevTo().
void GuildManager::sendGuildCreateNameTo (CreatureObject * player, GuildTerminal * guildTerminal)
Definition at line 215 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDCREATENAMETO__CREATUREOBJECT_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildCreateNameTo().
void GuildManager::sendGuildDisbandConfirmTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 294 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDDISBANDCONFIRMTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildDisbandConfirmTo().
void GuildManager::sendGuildInformationTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 245 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDINFORMATIONTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildInformationTo().
void GuildManager::sendGuildKickPromptTo (CreatureObject * player, CreatureObject * target)
Definition at line 374 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDKICKPROMPTTO__CREATUREOBJECT_CREATUREOBJECT_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildKickPromptTo().
void GuildManager::sendGuildListTo (CreatureObject * player, const String & guildFilter)
Definition at line 57 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDLISTTO__CREATUREOBJECT_STRING_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildListTo().
Referenced by ListGuildsCommand::doQueueCommand().
void GuildManager::sendGuildMail (const String & subject, StringIdChatParameter & body, GuildObject * guild)
Definition at line 805 of file GuildManager.cpp.
References _getImplementation(), and server::zone::managers::guild::GuildManagerImplementation::sendGuildMail().
void GuildManager::sendGuildMemberListTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 261 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDMEMBERLISTTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberListTo().
void GuildManager::sendGuildMemberOptionsTo (CreatureObject * player, GuildObject * guild, unsigned long long memberID, GuildTerminal * guildTerminal)
Definition at line 277 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDMEMBEROPTIONSTO__CREATUREOBJECT_GUILDOBJECT_LONG_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildMemberOptionsTo().
void GuildManager::sendGuildSetTitleTo (CreatureObject * player, CreatureObject * target)
Definition at line 389 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDSETTITLETO__CREATUREOBJECT_CREATUREOBJECT_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildSetTitleTo().
void GuildManager::sendGuildSponsoredListTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 310 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDSPONSOREDLISTTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredListTo().
void GuildManager::sendGuildSponsoredOptionsTo (CreatureObject * player, GuildObject * guild, unsigned long long playerID, GuildTerminal * guildTerminal)
Definition at line 326 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDSPONSOREDOPTIONSTO__CREATUREOBJECT_GUILDOBJECT_LONG_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsoredOptionsTo().
void GuildManager::sendGuildSponsorTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 343 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDSPONSORTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsorTo().
void GuildManager::sendGuildSponsorVerifyTo (CreatureObject * player, CreatureObject * target)
Definition at line 359 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDSPONSORVERIFYTO__CREATUREOBJECT_CREATUREOBJECT_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildSponsorVerifyTo().
void GuildManager::sendGuildTransferTo (CreatureObject * player, GuildTerminal * guildTerminal)
Definition at line 728 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDTRANSFERTO__CREATUREOBJECT_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildTransferTo().
void GuildManager::sendGuildWarStatusTo (CreatureObject * player, GuildObject * guild, GuildTerminal * guildTerminal)
Definition at line 404 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDGUILDWARSTATUSTO__CREATUREOBJECT_GUILDOBJECT_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendGuildWarStatusTo().
void GuildManager::sendMemberPermissionsTo (CreatureObject * player, unsigned long long targetID, GuildTerminal * guildTerminal)
Definition at line 483 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDMEMBERPERMISSIONSTO__CREATUREOBJECT_LONG_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::sendMemberPermissionsTo().
void GuildManager::sendTransferAckTo (CreatureObject * player, const String & newOwnerName, SceneObject * guildTerminal)
Definition at line 743 of file GuildManager.cpp.
References _getImplementation(), RPC_SENDTRANSFERACKTO__CREATUREOBJECT_STRING_SCENEOBJECT_, and server::zone::managers::guild::GuildManagerImplementation::sendTransferAckTo().
void GuildManager::setAllegianceTo (CreatureObject * player, unsigned long long targetID, GuildTerminal * guildTerminal)
Definition at line 681 of file GuildManager.cpp.
References _getImplementation(), RPC_SETALLEGIANCETO__CREATUREOBJECT_LONG_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::setAllegianceTo().
void GuildManager::setChatManager (ChatManager * chatmanager)
Definition at line 43 of file GuildManager.cpp.
References _getImplementation(), RPC_SETCHATMANAGER__CHATMANAGER_, and server::zone::managers::guild::GuildManagerImplementation::setChatManager().
void GuildManager::setMemberTitle (CreatureObject * player, CreatureObject * target, const String & title)
Definition at line 665 of file GuildManager.cpp.
References _getImplementation(), RPC_SETMEMBERTITLE__CREATUREOBJECT_CREATUREOBJECT_STRING_, and server::zone::managers::guild::GuildManagerImplementation::setMemberTitle().
void GuildManager::sponsorPlayer (CreatureObject * player, GuildTerminal * guildTerminal, const String & playerName)
Definition at line 589 of file GuildManager.cpp.
References _getImplementation(), RPC_SPONSORPLAYER__CREATUREOBJECT_GUILDTERMINAL_STRING_, and server::zone::managers::guild::GuildManagerImplementation::sponsorPlayer().
void GuildManager::toggleGuildPermission (CreatureObject * player, unsigned long long targetID, int permissionIndex, GuildTerminal * guildTerminal)
Definition at line 697 of file GuildManager.cpp.
References _getImplementation(), RPC_TOGGLEGUILDPERMISSION__CREATUREOBJECT_LONG_INT_GUILDTERMINAL_, and server::zone::managers::guild::GuildManagerImplementation::toggleGuildPermission().
void GuildManager::toggleWarStatus (CreatureObject * player, GuildObject * guild, unsigned long long guildoid)
Definition at line 436 of file GuildManager.cpp.
References _getImplementation(), RPC_TOGGLEWARSTATUS__CREATUREOBJECT_GUILDOBJECT_LONG_, and server::zone::managers::guild::GuildManagerImplementation::toggleWarStatus().
void GuildManager::transferGuildHall (CreatureObject * newOwner, SceneObject * guildTerminal)
Definition at line 790 of file GuildManager.cpp.
References _getImplementation(), RPC_TRANSFERGUILDHALL__CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::guild::GuildManagerImplementation::transferGuildHall().
void GuildManager::transferLeadership (CreatureObject * newOwner, CreatureObject * oldOwner, SceneObject * guildTerminal)
Definition at line 759 of file GuildManager.cpp.
References _getImplementation(), RPC_TRANSFERLEADERSHIP__CREATUREOBJECT_CREATUREOBJECT_SCENEOBJECT_, and server::zone::managers::guild::GuildManagerImplementation::transferLeadership().
void GuildManager::updateWarStatusToWaringGuild (GuildObject * guild, GuildObject * waringGuild)
Definition at line 468 of file GuildManager.cpp.
References _getImplementation(), RPC_UPDATEWARSTATUSTOWARINGGUILD__GUILDOBJECT_GUILDOBJECT_, and server::zone::managers::guild::GuildManagerImplementation::updateWarStatusToWaringGuild().
bool GuildManager::validateGuildAbbrev (CreatureObject * player, const String & guildAbbrev)
Definition at line 514 of file GuildManager.cpp.
References _getImplementation(), RPC_VALIDATEGUILDABBREV__CREATUREOBJECT_STRING_, and server::zone::managers::guild::GuildManagerImplementation::validateGuildAbbrev().
bool GuildManager::validateGuildName (CreatureObject * player, const String & guildName)
Definition at line 499 of file GuildManager.cpp.
References _getImplementation(), RPC_VALIDATEGUILDNAME__CREATUREOBJECT_STRING_, and server::zone::managers::guild::GuildManagerImplementation::validateGuildName().
Friends And Related Function Documentation
friend class GuildManagerHelper friend
Definition at line 235 of file GuildManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/guild/GuildManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/guild/GuildManager.cpp