Core3: StructureManager Class Reference
StructureManager Class Reference
#include <StructureManager.h>
Public Member Functions
StructureManager ()
void setZoneServer (ZoneServer *zoneServer)
void loadPlayerStructures (const String &zoneName)
int placeStructureFromDeed (CreatureObject *creature, StructureDeed *deed, float x, float y, int angle)
StructureObject * placeStructure (CreatureObject *creature, const String &structureTemplatePath, float x, float y, int angle)
int destroyStructure (StructureObject *structureObject)
int redeedStructure (CreatureObject *creature)
int declareResidence (CreatureObject *player, StructureObject *structureObject)
String getTimeString (uint32 timestamp)
SceneObject * getInRangeParkingGarage (SceneObject *obj, int range=64)
void reportStructureStatus (CreatureObject *creature, StructureObject *structure)
void promptNameStructure (CreatureObject *creature, StructureObject *structure, TangibleObject *object)
void promptDeleteAllItems (CreatureObject *creature, StructureObject *structure)
void promptFindLostItems (CreatureObject *creature, StructureObject *structure)
void moveFirstItemTo (CreatureObject *creature, StructureObject *structure)
void promptPayUncondemnMaintenance (CreatureObject *creature, StructureObject *structure)
void promptPayMaintenance (StructureObject *structure, CreatureObject *creature, SceneObject *terminal=NULL)
void payMaintenance (StructureObject *structure, CreatureObject *creature, int amount)
int getStructureFootprint (SharedObjectTemplate *objectTemplate, int angle, float &l0, float &w0, float &l1, float &w1)
bool isInStructureFootprint (StructureObject *structure, float positionX, float positionY, int extraFootprintMargin)
Private Attributes
ZoneServer * server
TemplateManager * templateManager
Detailed Description
Definition at line 83 of file StructureManager.h.
Constructor & Destructor Documentation
StructureManager::StructureManager () inline
Definition at line 88 of file StructureManager.h.
Member Function Documentation
int StructureManager::declareResidence (CreatureObject * player, StructureObject * structureObject)
Definition at line 594 of file StructureManager.cpp.
References server::zone::objects::creature::CreatureObject::addCooldown(), server::zone::objects::creature::CreatureObject::checkCooldownRecovery(), server::zone::ZoneServer::getCityManager(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::creature::CreatureObject::getCooldownTime(), server::zone::objects::player::PlayerObject::getDeclaredResidence(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::isBuildingObject(), server::zone::objects::player::PlayerObject::isPrivileged(), server::zone::managers::city::CityManager::registerCitizen(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, server::zone::objects::player::PlayerObject::setDeclaredResidence(), server::chat::StringIdChatParameter::setTO(), and server::zone::managers::city::CityManager::unregisterCitizen().
int StructureManager::destroyStructure (StructureObject * structureObject)
Destroys the structure after the confirmation of the player. All items still in the structure will be deleted from the database. If the maintenance requirements are met, it is to be redeeded. pre: structure locked post: structure deleted*
Parameters
structure The structure that is being destroyed.
Definition at line 503 of file StructureManager.cpp.
Referenced by server::zone::objects::region::CityRegionImplementation::cleanupDecorations(), server::zone::objects::region::CityRegionImplementation::destroyAllStructuresForRank(), redeedStructure(), server::zone::objects::region::CityRegionImplementation::removeDecorationsOutsideCity(), and server::zone::objects::region::CityRegionImplementation::removeStructuresOutsideCity().
SceneObject * StructureManager::getInRangeParkingGarage (SceneObject * obj, int range = 64)
Returns the closest parking garage to the obj, or NULL if one can't be found within the required radius.
Precondition
{ obj locked, zone unlocked }
Postcondition
{ obj locked, zone unlocked }
Parameters
obj The object to use as reference for searching for the nearest parking garage.
Returns
Returns a SceneObject representing the nearest parking garage, or NULL if one was not found in the required range.
Definition at line 688 of file StructureManager.cpp.
References server::zone::Zone::getInRangeObjects(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isGarage(), and server::zone::objects::scene::SceneObject::isInRange().
int StructureManager::getStructureFootprint (SharedObjectTemplate * objectTemplate, int angle, float & l0, float & w0, float & l1, float & w1)
Definition at line 119 of file StructureManager.cpp.
References StructureFootprint::getCenterX(), StructureFootprint::getCenterY(), StructureFootprint::getColSize(), StructureFootprint::getRowSize(), and SharedTangibleObjectTemplate::getStructureFootprint().
Referenced by placeStructure(), and placeStructureFromDeed().
String StructureManager::getTimeString (uint32 timestamp)
Converts seconds remaining into days, hours, minutes timestamp
Definition at line 565 of file StructureManager.cpp.
Referenced by reportStructureStatus().
bool StructureManager::isInStructureFootprint (StructureObject * structure, float positionX, float positionY, int extraFootprintMargin)
Definition at line 1115 of file StructureManager.cpp.
References BoundaryRectangle::containsPoint(), server::zone::objects::scene::SceneObject::getDirectionAngle(), server::zone::objects::scene::SceneObject::getObjectTemplate(), and SharedTangibleObjectTemplate::getStructureFootprint().
void StructureManager::loadPlayerStructures (const String & zoneName)
Definition at line 41 of file StructureManager.cpp.
References server::zone::Zone::getGCWManager(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getZone(), server::zone::managers::gcw::GCWManager::registerGCWBase(), and server.
void StructureManager::moveFirstItemTo (CreatureObject * creature, StructureObject * structure)
Moves the first object in the building to the creature's feet.
Parameters
creature The creature to whom's feet the item will be moved.
structure The structure containing the item.
Definition at line 798 of file StructureManager.cpp.
References server::zone::objects::scene::SceneObject::getParent(), server::zone::objects::scene::SceneObject::getParentID(), server::zone::objects::scene::SceneObject::isBuildingObject(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
void StructureManager::payMaintenance (StructureObject * structure, CreatureObject * creature, int amount)
Attempts to pay the requested amount to the structure, and notifies the creature.
Parameters
structure The structure being paid maintenance.
creature The creature attempting to pay maintenance.
amount The amount to pay maintenance.
Definition at line 1082 of file StructureManager.cpp.
References server::zone::objects::structure::StructureObject::addMaintenance(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::scene::SceneObject::getRootParent(), server::zone::objects::player::PlayerObject::hasAbility(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), server::zone::objects::structure::StructureObject::setMaintenanceReduced(), server::chat::StringIdChatParameter::setTT(), and server::zone::objects::creature::CreatureObject::subtractCashCredits().
Referenced by PaymaintenanceCommand::doQueueCommand().
StructureObject * StructureManager::placeStructure (CreatureObject * creature, const String & structureTemplatePath, float x, float y, int angle)
Simply creates and places a structure at the provided coordinates.
Definition at line 405 of file StructureManager.cpp.
References server::zone::objects::building::BuildingObject::createCellObjects(), server::zone::objects::structure::StructureObject::createChildObjects(), SceneObjectType::FACTIONBUILDING, server::zone::templates::SharedObjectTemplate::getClearFloraRadius(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::templates::SharedObjectTemplate::getGameObjectType(), TerrainManager::getHighestHeight(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::templates::SharedObjectTemplate::getSnapToTerrain(), SharedTangibleObjectTemplate::getStructureFootprint(), getStructureFootprint(), TemplateManager::getTemplate(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::structure::StructureObject::grantPermission(), server::zone::objects::scene::SceneObject::isBuildingObject(), server::zone::templates::SharedObjectTemplate::isCampStructureTemplate(), server::zone::objects::scene::SceneObject::isMinefield(), SharedStructureObjectTemplate::isPublicStructure(), server::zone::objects::scene::SceneObject::isTurret(), server::zone::objects::structure::StructureObject::notifyStructurePlaced(), server::zone::objects::scene::SceneObject::rotate(), server::zone::objects::tangible::TangibleObject::setFaction(), server::zone::objects::structure::StructureObject::setOwnerName(), server::zone::objects::structure::StructureObject::setOwnerObjectID(), server::zone::objects::structure::StructureObject::setPublicStructure(), templateManager, and SceneObjectType::TURRET.
Referenced by server::zone::objects::player::sessions::PlaceStructureSessionImplementation::completeSession().
int StructureManager::placeStructureFromDeed (CreatureObject * creature, StructureDeed * deed, float x, float y, int angle)
Definition at line 189 of file StructureManager.cpp.
References server::zone::objects::scene::SceneObject::addActiveSession(), server::zone::managers::gcw::GCWManager::canPlaceMoreBases(), server::zone::objects::scene::SceneObject::containsActiveSession(), BoundaryRectangle::containsPoint(), server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::getDirectionAngle(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::Zone::getGCWManager(), server::zone::objects::tangible::deed::Deed::getGeneratedObjectTemplate(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::getObjectTemplate(), server::zone::Zone::getPlanetManager(), server::zone::objects::creature::CreatureObject::getPlayerObject(), getStructureFootprint(), TemplateManager::getTemplate(), server::zone::objects::scene::SceneObject::getZone(), server::zone::objects::scene::SceneObject::isASubChildOf(), server::zone::objects::area::ActiveArea::isRegion(), SessionFacadeType::PLACESTRUCTURE, server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::chat::StringIdChatParameter::setDI(), server::chat::StringIdChatParameter::setTO(), and templateManager.
void StructureManager::promptDeleteAllItems (CreatureObject * creature, StructureObject * structure)
Sends a Sui prompt to the player asking if they wish to delete all the items in their house.
Parameters
creature The player receiving the prompt.
building The building that will have all items deleted.
Definition at line 765 of file StructureManager.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by StructureTerminalMenuComponent::handleObjectMenuSelect().
void StructureManager::promptFindLostItems (CreatureObject * creature, StructureObject * structure)
Sends a Sui prompt to the player asking if they want to move the first item in the house to their feet.
Parameters
creature The creature who the item will be moved to.
structure The structure which holds the items.
Definition at line 782 of file StructureManager.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by StructureTerminalMenuComponent::handleObjectMenuSelect().
void StructureManager::promptNameStructure (CreatureObject * creature, StructureObject * structure, TangibleObject * object)
Sends a Sui prompt to the player asking them to enter a name for the structure.
Parameters
creature The player receiving the prompt.
structure The structure that will be named.
object Optional terminal to be used for sui
Definition at line 959 of file StructureManager.cpp.
References server::zone::objects::creature::CreatureObject::getPlayerObject(), SuiWindowType::OBJECT_NAME, server::zone::objects::creature::CreatureObject::sendMessage(), and server.
Referenced by InstallationObjectMenuComponent::handleObjectMenuSelect(), and StructureTerminalMenuComponent::handleObjectMenuSelect().
void StructureManager::promptPayMaintenance (StructureObject * structure, CreatureObject * creature, SceneObject * terminal = NULL)
Sends the transfer box prompting for maintenance to be paid.
Parameters
structure The structure being paid maintenance too.
creature The creature attempting to pay maintenance.
terminal The terminal used in the process. Defaults to null.
Definition at line 1045 of file StructureManager.cpp.
References server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::structure::StructureObject::getSurplusMaintenance(), server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server, SuiWindowType::STRUCTURE_MANAGE_MAINTENANCE, and server::zone::objects::structure::StructureObject::updateStructureStatus().
Referenced by PaymaintenanceCommand::doQueueCommand().
void StructureManager::promptPayUncondemnMaintenance (CreatureObject * creature, StructureObject * structure)
Sends a Sui prompt to the player asking if they want to pay the required maintenance and fee to un-condemn the structure.
Parameters
creature The creature who owns the structure.
structure The condemned structure.
Definition at line 983 of file StructureManager.cpp.
References server::zone::objects::creature::CreatureObject::getBankCredits(), server::zone::objects::creature::CreatureObject::getCashCredits(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::structure::StructureObject::getSurplusMaintenance(), SuiWindowType::NONE, server::zone::objects::creature::CreatureObject::sendMessage(), server, and SuiWindowType::STRUCTURE_UNCONDEMN_CONFIRM.
int StructureManager::redeedStructure (CreatureObject * creature)
Redeeds the structure, returning it to the player in deed form with any surplus maintenance and power attached. This should occur after a destroy confirm, but before the structure has been completely destroyed. pre: player locked, building locked post: player locked, building locked
Parameters
creature The creatureObject who is redeeding the structure.
destroy Should the structure be destroyed after the deed is retrieved?
Definition at line 713 of file StructureManager.cpp.
References SessionFacadeType::DESTROYSTRUCTURE, destroyStructure(), server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::ZoneServer::getObject(), server::zone::objects::scene::SceneObject::getSlottedObject(), server::zone::objects::player::sessions::DestroyStructureSession::getStructureObject(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), and server.
void StructureManager::reportStructureStatus (CreatureObject * creature, StructureObject * structure)
Sends a sui list box containing information about the structure.
Parameters
creature The creature receiving the report.
structure The structure the report is about.
Definition at line 840 of file StructureManager.cpp.
References server::zone::objects::structure::StructureObject::getBasePowerRate(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::building::BuildingObject::getCurrentNumberOfPlayerItems(), server::zone::objects::structure::StructureObject::getDecayPercentage(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::objects::creature::CreatureObject::getFirstName(), server::zone::objects::structure::StructureObject::getMaintenanceMods(), server::zone::objects::structure::StructureObject::getMaintenanceRate(), server::zone::ZoneServer::getObject(), server::zone::objects::structure::StructureObject::getOwnerObjectID(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::structure::StructureObject::getSurplusMaintenance(), server::zone::objects::structure::StructureObject::getSurplusPower(), getTimeString(), server::zone::objects::scene::SceneObject::isBuildingObject(), server::zone::objects::structure::StructureObject::isCivicStructure(), server::zone::objects::scene::SceneObject::isGeneratorObject(), server::zone::objects::scene::SceneObject::isInstallationObject(), server::zone::objects::structure::StructureObject::isPrivateStructure(), server::zone::objects::creature::CreatureObject::sendMessage(), server, and SuiWindowType::STRUCTURE_STATUS.
void StructureManager::setZoneServer (ZoneServer * zoneServer) inline
Definition at line 96 of file StructureManager.h.
Referenced by server::zone::ZoneServerImplementation::startZones().
Member Data Documentation
ZoneServer* StructureManager::server private
Definition at line 84 of file StructureManager.h.
Referenced by declareResidence(), loadPlayerStructures(), promptDeleteAllItems(), promptFindLostItems(), promptNameStructure(), promptPayMaintenance(), promptPayUncondemnMaintenance(), redeedStructure(), and reportStructureStatus().
TemplateManager* StructureManager::templateManager private
Definition at line 85 of file StructureManager.h.
Referenced by placeStructure(), and placeStructureFromDeed().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/structure/StructureManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/structure/StructureManager.cpp