Core3: GalaxyList Class Reference
GalaxyList Class Reference
#include <GalaxyList.h>
Public Member Functions
GalaxyList ()
~GalaxyList ()
bool next ()
uint32 getGalaxyID ()
void getGalaxyName (String &name)
void getGalaxyAddress (String &address)
uint16 getGalaxyPort ()
uint16 getGalaxyPingPort ()
uint32 getGalaxyPopulation ()
int size ()
Private Attributes
ResultSet * galaxies
Detailed Description
Definition at line 50 of file GalaxyList.h.
Constructor & Destructor Documentation
GalaxyList::GalaxyList () inline
Definition at line 54 of file GalaxyList.h.
References galaxies, and ServerDatabase::instance().
GalaxyList::~GalaxyList () inline
Definition at line 61 of file GalaxyList.h.
References galaxies.
Member Function Documentation
void GalaxyList::getGalaxyAddress (String & address) inline
Definition at line 78 of file GalaxyList.h.
References galaxies.
Referenced by server::login::LoginServerImplementation::populateGalaxyList().
uint32 GalaxyList::getGalaxyID () inline
Definition at line 70 of file GalaxyList.h.
References galaxies.
Referenced by server::login::LoginServerImplementation::populateGalaxyList().
void GalaxyList::getGalaxyName (String & name) inline
Definition at line 74 of file GalaxyList.h.
References galaxies.
Referenced by server::login::LoginServerImplementation::populateGalaxyList().
uint16 GalaxyList::getGalaxyPingPort () inline
Definition at line 86 of file GalaxyList.h.
References galaxies.
Referenced by server::login::LoginServerImplementation::populateGalaxyList().
uint32 GalaxyList::getGalaxyPopulation () inline
Definition at line 90 of file GalaxyList.h.
References galaxies.
uint16 GalaxyList::getGalaxyPort () inline
Definition at line 82 of file GalaxyList.h.
References galaxies.
Referenced by server::login::LoginServerImplementation::populateGalaxyList().
bool GalaxyList::next () inline
Definition at line 66 of file GalaxyList.h.
References galaxies.
Referenced by server::login::LoginServerImplementation::populateGalaxyList().
int GalaxyList::size () inline
Definition at line 94 of file GalaxyList.h.
References galaxies.
Referenced by server::login::LoginServerImplementation::populateGalaxyList().
Member Data Documentation
ResultSet* GalaxyList::galaxies private
Definition at line 51 of file GalaxyList.h.
Referenced by GalaxyList(), getGalaxyAddress(), getGalaxyID(), getGalaxyName(), getGalaxyPingPort(), getGalaxyPopulation(), getGalaxyPort(), next(), size(), and ~GalaxyList().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/objects/GalaxyList.h