Core3: StringList Class Reference
StringList Class Reference
#include <StringList.h>
Public Member Functions
StringList (CreatureObject *creo)
void insertOption (const String &file, const String &str)
void insertOption (const String &option)
void insertOption (const UnicodeString &option)
void updateOptionCount ()
int getOptionCount ()
Public Member Functions inherited from ObjectControllerMessage
ObjectControllerMessage (uint64 objid, uint32 header1, uint32 header2, bool comp=true)
Private Attributes
uint8 optionCount
Detailed Description
Definition at line 51 of file StringList.h.
Constructor & Destructor Documentation
StringList::StringList (CreatureObject * creo) inline
Definition at line 56 of file StringList.h.
References optionCount.
Member Function Documentation
int StringList::getOptionCount () inline
Definition at line 80 of file StringList.h.
References optionCount.
void StringList::insertOption (const String & file, const String & str) inline
Definition at line 61 of file StringList.h.
References updateOptionCount().
Referenced by server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::selectConversationOption(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendConversationContinue(), server::zone::objects::creature::junkdealer::JunkdealerCreatureImplementation::sendInitialChoices(), and server::zone::templates::mobile::ConversationScreen::sendTo().
void StringList::insertOption (const String & option) inline
Definition at line 66 of file StringList.h.
References updateOptionCount().
void StringList::insertOption (const UnicodeString & option) inline
Definition at line 71 of file StringList.h.
References updateOptionCount().
void StringList::updateOptionCount () inline
Definition at line 76 of file StringList.h.
References optionCount.
Referenced by insertOption().
Member Data Documentation
uint8 StringList::optionCount private
Definition at line 52 of file StringList.h.
Referenced by getOptionCount(), StringList(), and updateOptionCount().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/object/StringList.h