Core3: StringIdParam Class Reference
StringIdParam Class Reference
#include <StringIdParam.h>
Public Member Functions
StringIdParam (const String &str)
StringIdParam ()
~StringIdParam ()
String toString ()
virtual bool parse (Chunk *source)
StringIdParam & operator= (const String &str)
StringIdParam & operator= (const StringIdParamData &custom)
String getFullString () const
Public Member Functions inherited from TemplateBase< StringIdParamData >
TemplateBase (const StringIdParamData &defaultValue)
TemplateBase (const TemplateBase &t)
virtual ~TemplateBase ()
void create (const StringIdParamData &val)
virtual int compareTo (const StringIdParamData &val) const
virtual bool operator== (const StringIdParamData &val) const
virtual bool operator< (const StringIdParamData &val) const
virtual bool operator> (const StringIdParamData &val) const
virtual bool operator!= (const StringIdParamData &val) const
operator StringIdParamData () const
virtual StringIdParamData getValue () const
virtual StringIdParamData get () const
virtual void setValue (const StringIdParamData &val)
Public Member Functions inherited from Param
Param ()
virtual ~Param ()
virtual bool parse (engine::util::Chunk *source)=0
uint32 getType ()
void setType (uint32 tp)
bool isBool ()
bool isFloat ()
bool isInteger ()
bool isString ()
bool isStringId ()
Additional Inherited Members
Static Public Attributes inherited from Param
static const uint32 BOOL = 0x01
static const uint32 FLOAT = 0x02
static const uint32 INTEGER = 0x04
static const uint32 STRING = 0x08
static const uint32 STRINGID = 0x10
static const uint32 VECTOR = 0x12
static const uint32 DYNAMICVARIABLE = 0x014
static const uint32 TRIGGERVOLUME = 0x16
static const uint32 PALETTECOLORCUSTOMIZATION = 0x18
static const uint32 RANGEDINTCUSTOMIZATIONVARIABLE = 0x20
static const uint32 CUSTOMIZATIONVARIABLEMAP = 0x22
Protected Attributes inherited from TemplateBase< StringIdParamData >
StringIdParamData value
Detailed Description
Definition at line 67 of file StringIdParam.h.
Constructor & Destructor Documentation
StringIdParam::StringIdParam (const String & str) inline
Definition at line 70 of file StringIdParam.h.
References Param::setType(), and Param::STRINGID.
StringIdParam::StringIdParam () inline
Definition at line 74 of file StringIdParam.h.
References Param::setType(), and Param::STRINGID.
StringIdParam::~StringIdParam () inline
Definition at line 78 of file StringIdParam.h.
Member Function Documentation
String StringIdParam::getFullString () const inline
Definition at line 129 of file StringIdParam.h.
Referenced by server::zone::templates::SharedObjectTemplate::getDetailedDescription(), server::zone::templates::SharedObjectTemplate::getLookAtText(), server::zone::templates::SharedObjectTemplate::getObjectName(), and toString().
StringIdParam& StringIdParam::operator= (const String & str) inline
Definition at line 104 of file StringIdParam.h.
References TemplateBase< StringIdParamData >::create().
StringIdParam& StringIdParam::operator= (const StringIdParamData & custom) inline
Definition at line 123 of file StringIdParam.h.
References TemplateBase< StringIdParamData >::create().
virtual bool StringIdParam::parse (Chunk * source) inline virtual
Definition at line 85 of file StringIdParam.h.
References TemplateBase< StringIdParamData >::create(), and StringParam::parse().
Referenced by server::zone::templates::SharedObjectTemplate::parseVariableData().
String StringIdParam::toString () inline virtual
Implements Param.
Definition at line 81 of file StringIdParam.h.
References getFullString().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/params/StringIdParam.h