Core3: server::zone::managers::crafting::labratories::GeneticLabratory Class Reference
server::zone::managers::crafting::labratories::GeneticLabratory Class Reference
#include <GeneticLabratory.h>
Public Member Functions
GeneticLabratory ()
virtual ~GeneticLabratory ()
void setInitialCraftingValues (TangibleObject *prototype, ManufactureSchematic *manufactureSchematic, int assemblySuccess)
void experimentRow (CraftingValues *craftingValues, int rowEffected, int pointsAttempted, float failure, int experimentationResult)
void initialize (ZoneServer *server)
bool allowFactoryRun (ManufactureSchematic *manufactureSchematic)
Public Member Functions inherited from server::zone::managers::crafting::labratories::SharedLabratory
SharedLabratory ()
virtual ~SharedLabratory ()
virtual float getWeightedValue (ManufactureSchematic *manufactureSchematic, int type)
Protected Member Functions
uint32 calcMin (float input)
float calcResistMin (float input, float mod)
float calcMaxPercentage (uint32 value)
Protected Member Functions inherited from server::zone::managers::crafting::labratories::SharedLabratory
float calculateExperimentationValueModifier (int experimentationResult, int pointsAttempted)
float calculateAssemblyValueModifier (int assemblyResult)
float getAssemblyPercentage (float value)
Private Member Functions
float applyFormula (float a, float b, float c, float d, float e, int formula)
String pickSpecialAttack (String a, String b, String c, String d, String e, int odds)
Static Private Attributes
static const short PHYSIQUE = 0
static const short PROWESS = 1
static const short MENTAL = 2
static const short AGRESSION = 3
static const short PHYSCHOLOGICAL = 4
Additional Inherited Members
Protected Attributes inherited from server::zone::managers::crafting::labratories::SharedLabratory
ManagedReference< ZoneServer * > zoneServer
Detailed Description
Definition at line 20 of file GeneticLabratory.h.
Constructor & Destructor Documentation
GeneticLabratory::GeneticLabratory ()
Definition at line 12 of file GeneticLabratory.cpp.
GeneticLabratory::~GeneticLabratory () virtual
Definition at line 15 of file GeneticLabratory.cpp.
Member Function Documentation
bool GeneticLabratory::allowFactoryRun (ManufactureSchematic * manufactureSchematic) virtual
Reimplemented from server::zone::managers::crafting::labratories::SharedLabratory.
Definition at line 297 of file GeneticLabratory.cpp.
float GeneticLabratory::applyFormula (float a, float b, float c, float d, float e, int formula) private
Definition at line 18 of file GeneticLabratory.cpp.
References AGRESSION, MENTAL, PHYSCHOLOGICAL, PHYSIQUE, and PROWESS.
Referenced by setInitialCraftingValues().
float server::zone::managers::crafting::labratories::GeneticLabratory::calcMaxPercentage (uint32 value) inline protected
Definition at line 45 of file GeneticLabratory.h.
Referenced by setInitialCraftingValues().
uint32 server::zone::managers::crafting::labratories::GeneticLabratory::calcMin (float input) inline protected
Definition at line 37 of file GeneticLabratory.h.
Referenced by setInitialCraftingValues().
float server::zone::managers::crafting::labratories::GeneticLabratory::calcResistMin (float input, float mod) inline protected
Definition at line 40 of file GeneticLabratory.h.
Referenced by setInitialCraftingValues().
void GeneticLabratory::experimentRow (CraftingValues * craftingValues, int rowEffected, int pointsAttempted, float failure, int experimentationResult) virtual
Implements server::zone::managers::crafting::labratories::SharedLabratory.
Definition at line 301 of file GeneticLabratory.cpp.
References server::zone::managers::crafting::labratories::SharedLabratory::calculateExperimentationValueModifier(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitleSize(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getExperimentalPropertySubtitlesTitle(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getMaxValue(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getVisibleExperimentalPropertyTitle(), and server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage().
void GeneticLabratory::initialize (ZoneServer * server) virtual
Reimplemented from server::zone::managers::crafting::labratories::SharedLabratory.
Definition at line 292 of file GeneticLabratory.cpp.
References server::zone::managers::crafting::labratories::SharedLabratory::initialize().
Referenced by server::zone::managers::crafting::CraftingManagerImplementation::configureLabratories().
String GeneticLabratory::pickSpecialAttack (String a, String b, String c, String d, String e, int odds) private
Definition at line 56 of file GeneticLabratory.cpp.
Referenced by setInitialCraftingValues().
void GeneticLabratory::setInitialCraftingValues (TangibleObject * prototype, ManufactureSchematic * manufactureSchematic, int assemblySuccess) virtual
Implements server::zone::managers::crafting::labratories::SharedLabratory.
Definition at line 93 of file GeneticLabratory.cpp.
References server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::addExperimentalProperty(), AGRESSION, applyFormula(), calcMaxPercentage(), calcMin(), calcResistMin(), server::zone::managers::crafting::labratories::SharedLabratory::calculateAssemblyValueModifier(), server::zone::objects::tangible::component::dna::DnaComponent::getAcid(), server::zone::managers::crafting::labratories::SharedLabratory::getAssemblyPercentage(), server::zone::objects::tangible::component::dna::DnaComponent::getBlast(), server::zone::objects::tangible::component::dna::DnaComponent::getCleverness(), server::zone::objects::tangible::component::dna::DnaComponent::getCold(), server::zone::objects::manufactureschematic::ManufactureSchematic::getComplexity(), server::zone::objects::tangible::component::dna::DnaComponent::getCourage(), server::zone::objects::manufactureschematic::ManufactureSchematic::getCraftingValues(), server::zone::objects::tangible::component::dna::DnaComponent::getDependency(), server::zone::objects::tangible::component::dna::DnaComponent::getDexterity(), server::zone::objects::manufactureschematic::ManufactureSchematic::getDraftSchematic(), server::zone::objects::tangible::component::dna::DnaComponent::getElectric(), server::zone::objects::tangible::component::dna::DnaComponent::getEndurance(), server::zone::objects::tangible::component::dna::DnaComponent::getEnergy(), server::zone::objects::tangible::component::dna::DnaComponent::getFierceness(), server::zone::objects::tangible::component::dna::DnaComponent::getForititude(), server::zone::objects::tangible::component::dna::DnaComponent::getHardiness(), server::zone::objects::tangible::component::dna::DnaComponent::getHeat(), server::zone::objects::tangible::component::dna::DnaComponent::getIntellect(), server::zone::objects::tangible::component::dna::DnaComponent::getKinetic(), server::zone::objects::tangible::component::dna::DnaComponent::getPower(), ComponentSlot::getPrototype(), server::zone::objects::tangible::component::dna::DnaComponent::getQuality(), server::zone::objects::tangible::component::dna::DnaComponent::getSaber(), server::zone::objects::manufactureschematic::ManufactureSchematic::getSlot(), server::zone::objects::manufactureschematic::ManufactureSchematic::getSlotCount(), IngredientSlot::getSlotName(), server::zone::objects::tangible::component::dna::DnaComponent::getSpecialAttackOne(), server::zone::objects::tangible::component::dna::DnaComponent::getSpecialAttackTwo(), server::zone::objects::tangible::component::dna::DnaComponent::getStun(), server::zone::objects::scene::SceneObject::isComponent(), server::zone::objects::tangible::component::dna::DnaComponent::isRanged(), server::zone::managers::crafting::CraftingManager::LINEARCOMBINE, MENTAL, server::zone::managers::crafting::CraftingManager::OVERRIDECOMBINE, PHYSCHOLOGICAL, PHYSIQUE, pickSpecialAttack(), PROWESS, server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::recalculateValues(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setCurrentPercentage(), server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::setMaxPercentage(), server::zone::objects::tangible::component::genetic::GeneticComponent::setQuality(), server::zone::objects::tangible::component::genetic::GeneticComponent::setRanged(), server::zone::objects::tangible::component::genetic::GeneticComponent::setSpecialAttackOne(), and server::zone::objects::tangible::component::genetic::GeneticComponent::setSpecialAttackTwo().
Member Data Documentation
const short server::zone::managers::crafting::labratories::GeneticLabratory::AGRESSION = 3 static private
Definition at line 25 of file GeneticLabratory.h.
Referenced by applyFormula(), and setInitialCraftingValues().
const short server::zone::managers::crafting::labratories::GeneticLabratory::MENTAL = 2 static private
Definition at line 24 of file GeneticLabratory.h.
Referenced by applyFormula(), and setInitialCraftingValues().
const short server::zone::managers::crafting::labratories::GeneticLabratory::PHYSCHOLOGICAL = 4 static private
Definition at line 26 of file GeneticLabratory.h.
Referenced by applyFormula(), and setInitialCraftingValues().
const short server::zone::managers::crafting::labratories::GeneticLabratory::PHYSIQUE = 0 static private
Definition at line 22 of file GeneticLabratory.h.
Referenced by applyFormula(), and setInitialCraftingValues().
const short server::zone::managers::crafting::labratories::GeneticLabratory::PROWESS = 1 static private
Definition at line 23 of file GeneticLabratory.h.
Referenced by applyFormula(), and setInitialCraftingValues().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/labratories/GeneticLabratory.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/crafting/labratories/GeneticLabratory.cpp