Core3: server::zone::objects::area::areashapes::RingAreaShapeImplementation Class Reference
server::zone::objects::area::areashapes::RingAreaShapeImplementation Class Reference
#include <RingAreaShape.h>
Public Member Functions
RingAreaShapeImplementation ()
RingAreaShapeImplementation (DummyConstructorParameter *param)
void setInnerRadius (float r)
void setOuterRadius (float r)
virtual float getInnerRadius ()
float getInnerRadius2 ()
virtual float getOuterRadius ()
float getOuterRadius2 ()
virtual bool containsPoint (float x, float y)
virtual bool containsPoint (const Vector3 &point)
virtual Vector3 getRandomPosition ()
virtual Vector3 getRandomPosition (const Vector3 &origin, float minDistance, float maxDistance)
virtual bool isRingAreaShape ()
virtual bool isCircularAreaShape ()
virtual bool isRectangularAreaShape ()
virtual bool intersectsWith (AreaShape *areaShape)
virtual float getArea ()
operator const RingAreaShape * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
AreaShapeImplementation ()
AreaShapeImplementation (DummyConstructorParameter *param)
void setAreaCenter (float x, float y)
Vector3 getAreaCenter ()
virtual float getRadius ()
operator const AreaShape * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< RingAreaShape * > _this
Public Attributes inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
WeakReference< AreaShape * > _this
Protected Member Functions
virtual ~RingAreaShapeImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
virtual ~AreaShapeImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
float innerRadius
float outerRadius
float innerRadius2
float outerRadius2
Protected Attributes inherited from server::zone::objects::area::areashapes::AreaShapeImplementation
Vector3 areaCenter
Private Member Functions
bool intersectsWithCircle (CircularAreaShape *circle)
bool intersectsWithRing (RingAreaShape *ring)
Friends
class RingAreaShape
Detailed Description
Definition at line 167 of file RingAreaShape.h.
Constructor & Destructor Documentation
RingAreaShapeImplementation::RingAreaShapeImplementation ()
Definition at line 399 of file RingAreaShape.cpp.
References _initializeImplementation(), innerRadius, innerRadius2, outerRadius, and outerRadius2.
RingAreaShapeImplementation::RingAreaShapeImplementation (DummyConstructorParameter * param)
Definition at line 237 of file RingAreaShape.cpp.
References _initializeImplementation().
RingAreaShapeImplementation::~RingAreaShapeImplementation () protected virtual
Definition at line 242 of file RingAreaShape.cpp.
Member Function Documentation
DistributedObjectStub * RingAreaShapeImplementation::_getStub ()
Definition at line 262 of file RingAreaShape.cpp.
References _this.
void RingAreaShapeImplementation::_initializeImplementation () protected
Definition at line 249 of file RingAreaShape.cpp.
References _serializationHelperMethod(), and _this.
Referenced by RingAreaShapeImplementation().
void RingAreaShapeImplementation::_serializationHelperMethod () protected
Definition at line 298 of file RingAreaShape.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void RingAreaShapeImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 257 of file RingAreaShape.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::_setStub(), and _this.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::RingAreaShape().
bool RingAreaShapeImplementation::containsPoint (float x, float y) virtual
Check if the coordinate is within the area shape.
Parameters
x the x coordinate.
y the y coordinate.
Returns
true if the coordinate is within the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 6 of file RingAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, innerRadius2, and outerRadius2.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::containsPoint().
bool RingAreaShapeImplementation::containsPoint (const Vector3 & point) virtual
Check if the coordinate is within the area shape.
Parameters
point the point to check if it is within the area shape.
Returns
true if the coordinate is within the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 13 of file RingAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, innerRadius2, and outerRadius2.
void RingAreaShapeImplementation::finalize () protected
Definition at line 246 of file RingAreaShape.cpp.
float RingAreaShapeImplementation::getArea () virtual
Get the area of the areaShape.
Returns
the area of the area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 88 of file RingAreaShapeImplementation.cpp.
References innerRadius2, and outerRadius2.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::getArea().
float RingAreaShapeImplementation::getInnerRadius () virtual
Get the inner radius of the ring.
Returns
inner radius of the ring
Definition at line 425 of file RingAreaShape.cpp.
References innerRadius.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::getInnerRadius().
float RingAreaShapeImplementation::getInnerRadius2 ()
Get the inner squared radius of the ring.
Returns
inner squared radius of the ring
Definition at line 430 of file RingAreaShape.cpp.
References innerRadius2.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::getInnerRadius2().
float RingAreaShapeImplementation::getOuterRadius () virtual
Get the outer radius of the ring.
Returns
outer radius of the ring
Definition at line 435 of file RingAreaShape.cpp.
References outerRadius.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::getOuterRadius().
float RingAreaShapeImplementation::getOuterRadius2 ()
Get the outer squared radius of the ring.
Returns
outer squared radius of the ring
Definition at line 440 of file RingAreaShape.cpp.
References outerRadius2.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::getOuterRadius2().
Vector3 RingAreaShapeImplementation::getRandomPosition () virtual
Generate a random position within the area.
Returns
a random position within the area.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 17 of file RingAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, innerRadius, and outerRadius.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::getRandomPosition().
Vector3 RingAreaShapeImplementation::getRandomPosition (const Vector3 & origin, float minDistance, float maxDistance) virtual
Generate a random position within the area with the supplied origin and radius as limits.
Parameters
origin the origin coordinate to generate the random position from.
minDistance the minimum distance from the origin.
maxDistance the maximum distance from the origin.
Returns
a random position within the area.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 27 of file RingAreaShapeImplementation.cpp.
bool RingAreaShapeImplementation::intersectsWith (AreaShape * areaShape) virtual
Check if this area shape intersects with the supplied area shape.
Parameters
areaShape the area shape to check for intersections with.s
Returns
true if the area shapes intersects each other.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 37 of file RingAreaShapeImplementation.cpp.
References _this, intersectsWithCircle(), intersectsWithRing(), server::zone::objects::area::areashapes::AreaShape::isCircularAreaShape(), server::zone::objects::area::areashapes::AreaShape::isRectangularAreaShape(), and server::zone::objects::area::areashapes::AreaShape::isRingAreaShape().
Referenced by server::zone::objects::area::areashapes::RingAreaShape::intersectsWith().
bool RingAreaShapeImplementation::intersectsWithCircle (CircularAreaShape * circle) private
Check if this area shape intersects with the supplied circular area shape.
Parameters
circle the circular area shape to check for intersections with.
Returns
true if the area shapes intersects each other.
Definition at line 56 of file RingAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, server::zone::objects::area::areashapes::AreaShape::getAreaCenter(), server::zone::objects::area::areashapes::CircularAreaShape::getRadius2(), innerRadius2, and outerRadius2.
Referenced by intersectsWith().
bool RingAreaShapeImplementation::intersectsWithRing (RingAreaShape * ring) private
Check if this area shape intersects with the supplied ring area shape.
Parameters
ring the ring area shape to check for intersections with.
Returns
true if the rings intersect with each other.
Definition at line 70 of file RingAreaShapeImplementation.cpp.
References server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter, server::zone::objects::area::areashapes::AreaShape::getAreaCenter(), server::zone::objects::area::areashapes::RingAreaShape::getInnerRadius2(), server::zone::objects::area::areashapes::RingAreaShape::getOuterRadius2(), innerRadius2, and outerRadius2.
Referenced by intersectsWith().
bool RingAreaShapeImplementation::isCircularAreaShape () virtual
Check if this is a circular area shape.
Returns
true if it is a circular area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 450 of file RingAreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::isCircularAreaShape().
bool RingAreaShapeImplementation::isRectangularAreaShape () virtual
Check if this is a rectangular area shape.
Returns
true if it is a rectangular area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 455 of file RingAreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::isRectangularAreaShape().
bool RingAreaShapeImplementation::isRingAreaShape () virtual
Check if this is a ring area shape.
Returns
true if it is a ring area shape.
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 445 of file RingAreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::isRingAreaShape().
void RingAreaShapeImplementation::lock (bool doLock = true) protected
Definition at line 270 of file RingAreaShape.cpp.
References _this.
void RingAreaShapeImplementation::lock (ManagedObject * obj) protected
Definition at line 274 of file RingAreaShape.cpp.
References _this.
RingAreaShapeImplementation::operator const RingAreaShape * ()
Definition at line 266 of file RingAreaShape.cpp.
void RingAreaShapeImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 305 of file RingAreaShape.cpp.
References readObjectMember().
bool RingAreaShapeImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 324 of file RingAreaShape.cpp.
References innerRadius, innerRadius2, outerRadius, outerRadius2, and server::zone::objects::area::areashapes::AreaShapeImplementation::readObjectMember().
Referenced by readObject().
void RingAreaShapeImplementation::rlock (bool doLock = true) protected
Definition at line 278 of file RingAreaShape.cpp.
References _this.
void RingAreaShapeImplementation::runlock (bool doLock = true) protected
Definition at line 294 of file RingAreaShape.cpp.
References _this.
void RingAreaShapeImplementation::setInnerRadius (float r)
Set the inner radius of the ring.
Parameters
r the new inner radius of the ring.
Definition at line 411 of file RingAreaShape.cpp.
References innerRadius, and innerRadius2.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::setInnerRadius().
void RingAreaShapeImplementation::setOuterRadius (float r)
Set the outer radius of the ring.
Parameters
r the new outer radius of the ring.
Definition at line 418 of file RingAreaShape.cpp.
References outerRadius, and outerRadius2.
Referenced by server::zone::objects::area::areashapes::RingAreaShape::setOuterRadius().
void RingAreaShapeImplementation::unlock (bool doLock = true) protected
Definition at line 290 of file RingAreaShape.cpp.
References _this.
void RingAreaShapeImplementation::wlock (bool doLock = true) protected
Definition at line 282 of file RingAreaShape.cpp.
References _this.
void RingAreaShapeImplementation::wlock (ManagedObject * obj) protected
Definition at line 286 of file RingAreaShape.cpp.
References _this.
void RingAreaShapeImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::area::areashapes::AreaShapeImplementation.
Definition at line 350 of file RingAreaShape.cpp.
References writeObjectMembers().
int RingAreaShapeImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 357 of file RingAreaShape.cpp.
References innerRadius, innerRadius2, outerRadius, outerRadius2, and server::zone::objects::area::areashapes::AreaShapeImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class RingAreaShape friend
Definition at line 329 of file RingAreaShape.h.
Member Data Documentation
WeakReference<RingAreaShape*> server::zone::objects::area::areashapes::RingAreaShapeImplementation::_this
Definition at line 295 of file RingAreaShape.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), intersectsWith(), lock(), rlock(), runlock(), unlock(), and wlock().
float server::zone::objects::area::areashapes::RingAreaShapeImplementation::innerRadius protected
Definition at line 169 of file RingAreaShape.h.
Referenced by getInnerRadius(), getRandomPosition(), readObjectMember(), RingAreaShapeImplementation(), setInnerRadius(), and writeObjectMembers().
float server::zone::objects::area::areashapes::RingAreaShapeImplementation::innerRadius2 protected
Definition at line 173 of file RingAreaShape.h.
Referenced by containsPoint(), getArea(), getInnerRadius2(), intersectsWithCircle(), intersectsWithRing(), readObjectMember(), RingAreaShapeImplementation(), setInnerRadius(), and writeObjectMembers().
float server::zone::objects::area::areashapes::RingAreaShapeImplementation::outerRadius protected
Definition at line 171 of file RingAreaShape.h.
Referenced by getOuterRadius(), getRandomPosition(), readObjectMember(), RingAreaShapeImplementation(), setOuterRadius(), and writeObjectMembers().
float server::zone::objects::area::areashapes::RingAreaShapeImplementation::outerRadius2 protected
Definition at line 175 of file RingAreaShape.h.
Referenced by containsPoint(), getArea(), getOuterRadius2(), intersectsWithCircle(), intersectsWithRing(), readObjectMember(), RingAreaShapeImplementation(), setOuterRadius(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RingAreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RingAreaShape.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/RingAreaShapeImplementation.cpp