Core3: StringId Class Reference
StringId Class Reference
#include <StringId.h>
Public Member Functions
StringId ()
StringId (const StringId &id)
StringId (const String &fullPath)
StringId (const String &fil, const String &stringId)
StringId (const UnicodeString &custom)
void getFullPath (String &str)
String & getFile ()
String & getStringID ()
UnicodeString & getCustomString ()
void setCustomString (const UnicodeString &custom)
void setStringId (const String &fullPath)
void parse (Message *message)
Private Member Functions
void addSerializableVariables ()
Private Attributes
String file
String stringID
UnicodeString customName
Detailed Description
Definition at line 50 of file StringId.h.
Constructor & Destructor Documentation
StringId::StringId ()
Definition at line 47 of file StringId.cpp.
References addSerializableVariables().
StringId::StringId (const StringId & id)
Definition at line 51 of file StringId.cpp.
References addSerializableVariables(), customName, file, and stringID.
StringId::StringId (const String & fullPath)
Definition at line 60 of file StringId.cpp.
References addSerializableVariables(), and setStringId().
StringId::StringId (const String & fil, const String & stringId)
Definition at line 66 of file StringId.cpp.
References addSerializableVariables(), file, and stringID.
StringId::StringId (const UnicodeString & custom)
Definition at line 73 of file StringId.cpp.
References addSerializableVariables(), and customName.
Member Function Documentation
void StringId::addSerializableVariables () inline private
Definition at line 79 of file StringId.cpp.
References customName, file, and stringID.
Referenced by StringId().
UnicodeString& StringId::getCustomString () inline
Definition at line 78 of file StringId.h.
References customName.
Referenced by ObjectManager::getObject(), and TangibleObject::parseBaseline3().
String& StringId::getFile () inline
Definition at line 70 of file StringId.h.
References file.
void StringId::getFullPath (String & str) inline
Definition at line 66 of file StringId.h.
References file, and stringID.
Referenced by TangibleObject::parseBaseline3(), and SceneObject::SceneObject().
String& StringId::getStringID () inline
Definition at line 74 of file StringId.h.
References stringID.
void StringId::parse (Message * message) inline
Definition at line 99 of file StringId.h.
References customName, file, and stringID.
Referenced by TangibleObject::parseBaseline3().
void StringId::setCustomString (const UnicodeString & custom) inline
Definition at line 82 of file StringId.h.
References customName.
void StringId::setStringId (const String & fullPath) inline
Definition at line 86 of file StringId.h.
References file, and stringID.
Referenced by SceneObject::SceneObject(), and StringId().
Member Data Documentation
UnicodeString StringId::customName private
Definition at line 54 of file StringId.h.
Referenced by addSerializableVariables(), getCustomString(), parse(), setCustomString(), and StringId().
String StringId::file private
Definition at line 51 of file StringId.h.
Referenced by addSerializableVariables(), getFile(), getFullPath(), parse(), setStringId(), and StringId().
String StringId::stringID private
Definition at line 52 of file StringId.h.
Referenced by addSerializableVariables(), getFullPath(), getStringID(), parse(), setStringId(), and StringId().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/zone/objects/scene/variables/StringId.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/client/zone/objects/scene/variables/StringId.cpp