Core3: server::zone::objects::player::sessions::ImageDesignSession Class Reference
server::zone::objects::player::sessions::ImageDesignSession Class Reference
#include <ImageDesignSession.h>
Public Member Functions
ImageDesignSession (CreatureObject *parent)
void initializeTransientMembers ()
void startImageDesign (CreatureObject *designer, CreatureObject *targetPlayer)
void updateImageDesign (CreatureObject *updater, unsigned long long designer, unsigned long long targetPlayer, unsigned long long tent, int type, const ImageDesignData &data)
void cancelImageDesign (unsigned long long designer, unsigned long long targetPlayer, unsigned long long tent, int type, const ImageDesignData &data)
int initializeSession ()
int doPayment ()
int cancelSession ()
int clearSession ()
void clearIdTimeoutEvent ()
void checkDequeueEvent (SceneObject *scene)
void queueIdTimeoutEvent ()
void dequeueIdTimeoutEvent ()
void sessionTimeout ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
ImageDesignSession (DummyConstructorParameter *param)
virtual ~ImageDesignSession ()
Friends
class ImageDesignSessionHelper
Detailed Description
Definition at line 102 of file ImageDesignSession.h.
Constructor & Destructor Documentation
ImageDesignSession::ImageDesignSession (CreatureObject * parent)
Definition at line 21 of file ImageDesignSession.cpp.
References server::zone::objects::player::sessions::ImageDesignSessionImplementation::_setStub().
ImageDesignSession::ImageDesignSession (DummyConstructorParameter * param) protected
Definition at line 28 of file ImageDesignSession.cpp.
ImageDesignSession::~ImageDesignSession () protected virtual
Definition at line 32 of file ImageDesignSession.cpp.
Member Function Documentation
DistributedObjectServant * ImageDesignSession::_getImplementation ()
Definition at line 195 of file ImageDesignSession.cpp.
Referenced by cancelImageDesign(), cancelSession(), checkDequeueEvent(), clearIdTimeoutEvent(), clearSession(), dequeueIdTimeoutEvent(), doPayment(), initializeSession(), initializeTransientMembers(), queueIdTimeoutEvent(), sessionTimeout(), startImageDesign(), and updateImageDesign().
DistributedObjectServant * ImageDesignSession::_getImplementationForRead ()
Definition at line 201 of file ImageDesignSession.cpp.
void ImageDesignSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 205 of file ImageDesignSession.cpp.
void ImageDesignSession::cancelImageDesign (unsigned long long designer, unsigned long long targetPlayer, unsigned long long tent, int type, const ImageDesignData & data)
Definition at line 68 of file ImageDesignSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::ImageDesignSessionImplementation::cancelImageDesign().
Referenced by ImageDesignRejectMessageCallback::run().
int ImageDesignSession::cancelSession ()
Definition at line 103 of file ImageDesignSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
void ImageDesignSession::checkDequeueEvent (SceneObject * scene)
Definition at line 142 of file ImageDesignSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::checkDequeueEvent(), and RPC_CHECKDEQUEUEEVENT__SCENEOBJECT_.
void ImageDesignSession::clearIdTimeoutEvent ()
Definition at line 129 of file ImageDesignSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::clearIdTimeoutEvent(), and RPC_CLEARIDTIMEOUTEVENT__.
int ImageDesignSession::clearSession ()
Definition at line 116 of file ImageDesignSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
void ImageDesignSession::dequeueIdTimeoutEvent ()
Definition at line 169 of file ImageDesignSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::dequeueIdTimeoutEvent(), and RPC_DEQUEUEIDTIMEOUTEVENT__.
int ImageDesignSession::doPayment ()
Definition at line 90 of file ImageDesignSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::doPayment(), and RPC_DOPAYMENT__.
int ImageDesignSession::initializeSession ()
Definition at line 77 of file ImageDesignSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
void ImageDesignSession::initializeTransientMembers ()
Definition at line 37 of file ImageDesignSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
void ImageDesignSession::queueIdTimeoutEvent ()
Definition at line 156 of file ImageDesignSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::ImageDesignSessionImplementation::queueIdTimeoutEvent(), and RPC_QUEUEIDTIMEOUTEVENT__.
void ImageDesignSession::sessionTimeout ()
Definition at line 182 of file ImageDesignSession.cpp.
References _getImplementation(), RPC_SESSIONTIMEOUT__, and server::zone::objects::player::sessions::ImageDesignSessionImplementation::sessionTimeout().
void ImageDesignSession::startImageDesign (CreatureObject * designer, CreatureObject * targetPlayer)
Starts an ImageDesign session between the designer and the target player.
Parameters
designer The image designer.
targetPlayer The recipient of the image designing.
type Unknown type specifier (needs more research)
Precondition
designer and targetPlayer are locked
Postcondition
designer and targetPlayer are locked
Definition at line 50 of file ImageDesignSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::ImageDesignSessionImplementation::startImageDesign().
void ImageDesignSession::updateImageDesign (CreatureObject * updater, unsigned long long designer, unsigned long long targetPlayer, unsigned long long tent, int type, const ImageDesignData & data)
When a change is made by the designer, the target's window needs to be notified, and vice versa.
Parameters
designer The object id of the designer.
targetPlayer The target player's object id.
tent The object id of the salon tent being used.
type The type of something - unknown atm.
data The image design data associated with this update request.
Definition at line 59 of file ImageDesignSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::ImageDesignSessionImplementation::updateImageDesign().
Referenced by ImageDesignChangeMessageCallback::run().
Friends And Related Function Documentation
friend class ImageDesignSessionHelper friend
Definition at line 158 of file ImageDesignSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/ImageDesignSession.cpp