Core3: EmptyHopperCallback Class Reference
EmptyHopperCallback Class Reference
#include <EmptyHopperCallback.h>
Public Member Functions
EmptyHopperCallback (ObjectControllerMessageCallback *objectControllerCallback)
void parse (Message *message)
void run ()
Public Member Functions inherited from server::zone::packets::MessageCallback
MessageCallback (ZoneClientSession *client, ZoneProcessServer *server)
virtual ~MessageCallback ()
int getTaskQueue ()
bool parseMessage (Message *packet)
ZoneClientSession * getClient ()
ZoneProcessServer * getServer ()
Private Attributes
uint64 harvesterId
uint64 resourceId
uint32 quantity
uint8 byte1
uint8 byte2
ObjectControllerMessageCallback * objectControllerMain
Additional Inherited Members
Protected Attributes inherited from server::zone::packets::MessageCallback
Reference< ZoneClientSession * > client
ManagedReference
< ZoneProcessServer * > server
int taskqueue
Detailed Description
Definition at line 17 of file EmptyHopperCallback.h.
Constructor & Destructor Documentation
EmptyHopperCallback::EmptyHopperCallback (ObjectControllerMessageCallback * objectControllerCallback) inline
Definition at line 26 of file EmptyHopperCallback.h.
References objectControllerMain.
Member Function Documentation
void EmptyHopperCallback::parse (Message * message) inline virtual
Implements server::zone::packets::MessageCallback.
Definition at line 32 of file EmptyHopperCallback.h.
References byte1, byte2, harvesterId, quantity, and resourceId.
void EmptyHopperCallback::run () inline
Definition at line 42 of file EmptyHopperCallback.h.
References server::zone::objects::scene::SceneObject::broadcastObject(), server::zone::objects::installation::InstallationObject::broadcastToOperators(), byte1, byte2, server::zone::packets::MessageCallback::client, server::zone::objects::scene::SceneObject::error(), server::zone::objects::installation::InstallationObject::getContainerFromHopper(), server::zone::objects::scene::SceneObject::getSlottedObject(), harvesterId, server::zone::objects::scene::SceneObject::hasFullContainerObjects(), server::zone::objects::scene::SceneObject::isInRange(), server::zone::objects::structure::StructureObject::isOnAdminList(), quantity, resourceId, server::zone::packets::MessageCallback::server, server::zone::objects::scene::SceneObject::transferObject(), and server::zone::objects::installation::InstallationObject::updateResourceContainerQuantity().
Member Data Documentation
uint8 EmptyHopperCallback::byte1 private
Definition at line 21 of file EmptyHopperCallback.h.
Referenced by parse(), and run().
uint8 EmptyHopperCallback::byte2 private
Definition at line 22 of file EmptyHopperCallback.h.
Referenced by parse(), and run().
uint64 EmptyHopperCallback::harvesterId private
Definition at line 18 of file EmptyHopperCallback.h.
Referenced by parse(), and run().
ObjectControllerMessageCallback* EmptyHopperCallback::objectControllerMain private
Definition at line 24 of file EmptyHopperCallback.h.
Referenced by EmptyHopperCallback().
uint32 EmptyHopperCallback::quantity private
Definition at line 20 of file EmptyHopperCallback.h.
Referenced by parse(), and run().
uint64 EmptyHopperCallback::resourceId private
Definition at line 19 of file EmptyHopperCallback.h.
Referenced by parse(), and run().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/object/EmptyHopperCallback.h