Core3: server::zone::objects::mission::DestroyMissionObjective Class Reference
server::zone::objects::mission::DestroyMissionObjective Class Reference
#include <DestroyMissionObjective.h>
Public Member Functions
DestroyMissionObjective (MissionObject *mission)
void initializeTransientMembers ()
void activate ()
void abort ()
void complete ()
void spawnLair ()
void destroyObjectFromDatabase ()
Vector3 findValidSpawnPosition (Zone *zone)
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void setLairTemplateToSpawn (const String &sp)
void setDifficulty (int diff)
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (MissionObject *parent)
void initializeTransientMembers ()
void destroyObjectFromDatabase ()
int notifyObserverEvent (MissionObserver *observer, unsigned int eventType, Observable *observable, ManagedObject *arg1, long long arg2)
void addObserver (MissionObserver *observer, bool makePersistent)
void dropObserver (MissionObserver *observer, bool removeFromDatabase)
int getObserverCount ()
void removeAllObservers ()
MissionObserver * getObserver (int index)
bool hasObservers ()
void activate ()
void deactivate ()
void abort ()
void complete ()
void fail ()
ManagedWeakReference
< MissionObject * > getMissionObject ()
unsigned int getObjectiveType ()
ManagedWeakReference
< CreatureObject * > getPlayerOwner ()
void awardFactionPoints ()
void removeMissionFromPlayer ()
void awardReward ()
Vector3 getEndPosition ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
DestroyMissionObjective (DummyConstructorParameter *param)
virtual ~DestroyMissionObjective ()
Protected Member Functions inherited from server::zone::objects::mission::MissionObjective
MissionObjective (DummyConstructorParameter *param)
virtual ~MissionObjective ()
Friends
class DestroyMissionObjectiveHelper
Detailed Description
Definition at line 133 of file DestroyMissionObjective.h.
Constructor & Destructor Documentation
DestroyMissionObjective::DestroyMissionObjective (MissionObject * mission)
Definition at line 29 of file DestroyMissionObjective.cpp.
References server::zone::objects::mission::DestroyMissionObjectiveImplementation::_setStub().
DestroyMissionObjective::DestroyMissionObjective (DummyConstructorParameter * param) protected
Definition at line 36 of file DestroyMissionObjective.cpp.
DestroyMissionObjective::~DestroyMissionObjective () protected virtual
Definition at line 40 of file DestroyMissionObjective.cpp.
Member Function Documentation
DistributedObjectServant * DestroyMissionObjective::_getImplementation ()
Definition at line 182 of file DestroyMissionObjective.cpp.
Referenced by abort(), activate(), complete(), destroyObjectFromDatabase(), findValidSpawnPosition(), getEndPosition(), initializeTransientMembers(), notifyObserverEvent(), setDifficulty(), setLairTemplateToSpawn(), and spawnLair().
DistributedObjectServant * DestroyMissionObjective::_getImplementationForRead ()
Definition at line 188 of file DestroyMissionObjective.cpp.
void DestroyMissionObjective::_setImplementation (DistributedObjectServant * servant)
Definition at line 192 of file DestroyMissionObjective.cpp.
void DestroyMissionObjective::abort ()
Definition at line 71 of file DestroyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::abort(), and RPC_ABORT__.
void DestroyMissionObjective::activate ()
Definition at line 58 of file DestroyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::activate(), and RPC_ACTIVATE__.
void DestroyMissionObjective::complete ()
Definition at line 84 of file DestroyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::complete(), and RPC_COMPLETE__.
void DestroyMissionObjective::destroyObjectFromDatabase ()
Destroys this object from database
Precondition
{ this is locked }
Postcondition
{ this is locked }
Definition at line 110 of file DestroyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::destroyObjectFromDatabase(), and RPC_DESTROYOBJECTFROMDATABASE__.
Vector3 DestroyMissionObjective::findValidSpawnPosition (Zone * zone)
Definition at line 123 of file DestroyMissionObjective.cpp.
References _getImplementation(), and server::zone::objects::mission::DestroyMissionObjectiveImplementation::findValidSpawnPosition().
Vector3 DestroyMissionObjective::getEndPosition ()
Definition at line 173 of file DestroyMissionObjective.cpp.
References _getImplementation(), and server::zone::objects::mission::DestroyMissionObjectiveImplementation::getEndPosition().
void DestroyMissionObjective::initializeTransientMembers ()
Definition at line 45 of file DestroyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
int DestroyMissionObjective::notifyObserverEvent (MissionObserver * observer, unsigned int eventType, Observable * observable, ManagedObject * arg1, long long arg2)
Definition at line 132 of file DestroyMissionObjective.cpp.
References _getImplementation(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::notifyObserverEvent(), and RPC_NOTIFYOBSERVEREVENT__MISSIONOBSERVER_INT_OBSERVABLE_MANAGEDOBJECT_LONG_.
void DestroyMissionObjective::setDifficulty (int diff)
Definition at line 159 of file DestroyMissionObjective.cpp.
References _getImplementation(), RPC_SETDIFFICULTY__INT_, and server::zone::objects::mission::DestroyMissionObjectiveImplementation::setDifficulty().
void DestroyMissionObjective::setLairTemplateToSpawn (const String & sp)
Definition at line 150 of file DestroyMissionObjective.cpp.
References _getImplementation(), and server::zone::objects::mission::DestroyMissionObjectiveImplementation::setLairTemplateToSpawn().
void DestroyMissionObjective::spawnLair ()
Definition at line 97 of file DestroyMissionObjective.cpp.
References _getImplementation(), RPC_SPAWNLAIR__, and server::zone::objects::mission::DestroyMissionObjectiveImplementation::spawnLair().
Friends And Related Function Documentation
friend class DestroyMissionObjectiveHelper friend
Definition at line 174 of file DestroyMissionObjective.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DestroyMissionObjective.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/mission/DestroyMissionObjective.cpp