Core3: server::zone::objects::player::sessions::SlicingSession Class Reference
server::zone::objects::player::sessions::SlicingSession Class Reference
#include <SlicingSession.h>
Public Member Functions
SlicingSession (CreatureObject *parent)
void initalizeSlicingMenu (CreatureObject *pl, TangibleObject *obj)
void handleMenuSelect (CreatureObject *pl, byte menuID, SuiListBox *suiBox)
int initializeSession ()
int cancelSession ()
int clearSession ()
void endSlicing ()
bool isBaseSlice ()
void setBaseSlice (bool val)
int getSlicingSkill (CreatureObject *slicer)
bool hasPrecisionLaserKnife (bool removeItem=true)
bool hasWeaponUpgradeKit ()
bool hasArmorUpgradeKit ()
void useClampFromInventory (SlicingTool *clamp)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
SlicingSession (DummyConstructorParameter *param)
virtual ~SlicingSession ()
Friends
class SlicingSessionHelper
Detailed Description
Definition at line 68 of file SlicingSession.h.
Constructor & Destructor Documentation
SlicingSession::SlicingSession (CreatureObject * parent)
Definition at line 17 of file SlicingSession.cpp.
References server::zone::objects::player::sessions::SlicingSessionImplementation::_setStub().
SlicingSession::SlicingSession (DummyConstructorParameter * param) protected
Definition at line 24 of file SlicingSession.cpp.
SlicingSession::~SlicingSession () protected virtual
Definition at line 28 of file SlicingSession.cpp.
Member Function Documentation
DistributedObjectServant * SlicingSession::_getImplementation ()
Definition at line 198 of file SlicingSession.cpp.
Referenced by cancelSession(), clearSession(), endSlicing(), getSlicingSkill(), handleMenuSelect(), hasArmorUpgradeKit(), hasPrecisionLaserKnife(), hasWeaponUpgradeKit(), initalizeSlicingMenu(), initializeSession(), isBaseSlice(), setBaseSlice(), and useClampFromInventory().
DistributedObjectServant * SlicingSession::_getImplementationForRead ()
Definition at line 204 of file SlicingSession.cpp.
void SlicingSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 208 of file SlicingSession.cpp.
int SlicingSession::cancelSession ()
Definition at line 64 of file SlicingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::SlicingSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
Referenced by SlicingSessionSuiCallback::run().
int SlicingSession::clearSession ()
Definition at line 77 of file SlicingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::SlicingSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
void SlicingSession::endSlicing ()
Definition at line 90 of file SlicingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::SlicingSessionImplementation::endSlicing(), and RPC_ENDSLICING__.
int SlicingSession::getSlicingSkill (CreatureObject * slicer)
Definition at line 130 of file SlicingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::SlicingSessionImplementation::getSlicingSkill(), and RPC_GETSLICINGSKILL__CREATUREOBJECT_.
void SlicingSession::handleMenuSelect (CreatureObject * pl, byte menuID, SuiListBox * suiBox)
Definition at line 42 of file SlicingSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::SlicingSessionImplementation::handleMenuSelect().
bool SlicingSession::hasArmorUpgradeKit ()
Definition at line 171 of file SlicingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::SlicingSessionImplementation::hasArmorUpgradeKit(), and RPC_HASARMORUPGRADEKIT__.
bool SlicingSession::hasPrecisionLaserKnife (bool removeItem = true)
Definition at line 144 of file SlicingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::SlicingSessionImplementation::hasPrecisionLaserKnife(), and RPC_HASPRECISIONLASERKNIFE__BOOL_.
bool SlicingSession::hasWeaponUpgradeKit ()
Definition at line 158 of file SlicingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::SlicingSessionImplementation::hasWeaponUpgradeKit(), and RPC_HASWEAPONUPGRADEKIT__.
void SlicingSession::initalizeSlicingMenu (CreatureObject * pl, TangibleObject * obj)
Definition at line 33 of file SlicingSession.cpp.
References _getImplementation(), and server::zone::objects::player::sessions::SlicingSessionImplementation::initalizeSlicingMenu().
int SlicingSession::initializeSession ()
Definition at line 51 of file SlicingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::SlicingSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
bool SlicingSession::isBaseSlice ()
Definition at line 103 of file SlicingSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::SlicingSessionImplementation::isBaseSlice(), and RPC_ISBASESLICE__.
void SlicingSession::setBaseSlice (bool val)
Definition at line 116 of file SlicingSession.cpp.
References _getImplementation(), RPC_SETBASESLICE__BOOL_, and server::zone::objects::player::sessions::SlicingSessionImplementation::setBaseSlice().
void SlicingSession::useClampFromInventory (SlicingTool * clamp)
Definition at line 184 of file SlicingSession.cpp.
References _getImplementation(), RPC_USECLAMPFROMINVENTORY__SLICINGTOOL_, and server::zone::objects::player::sessions::SlicingSessionImplementation::useClampFromInventory().
Friends And Related Function Documentation
friend class SlicingSessionHelper friend
Definition at line 108 of file SlicingSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/SlicingSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/SlicingSession.cpp