Core3: server::zone::objects::area::areashapes::AreaShapeImplementation Class Reference
server::zone::objects::area::areashapes::AreaShapeImplementation Class Reference
#include <AreaShape.h>
Public Member Functions
AreaShapeImplementation ()
AreaShapeImplementation (DummyConstructorParameter *param)
void setAreaCenter (float x, float y)
Vector3 getAreaCenter ()
virtual bool containsPoint (float x, float y)
virtual bool containsPoint (const Vector3 &point)
virtual float getRadius ()
virtual Vector3 getRandomPosition ()
virtual Vector3 getRandomPosition (const Vector3 &origin, float minDistance, float maxDistance)
virtual bool isCircularAreaShape ()
virtual bool isRectangularAreaShape ()
virtual bool isRingAreaShape ()
virtual bool intersectsWith (AreaShape *areaShape)
virtual float getArea ()
operator const AreaShape * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< AreaShape * > _this
Protected Member Functions
virtual ~AreaShapeImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
Vector3 areaCenter
Friends
class AreaShape
Detailed Description
Definition at line 138 of file AreaShape.h.
Constructor & Destructor Documentation
AreaShapeImplementation::AreaShapeImplementation ()
Definition at line 318 of file AreaShape.cpp.
References _initializeImplementation(), and areaCenter.
AreaShapeImplementation::AreaShapeImplementation (DummyConstructorParameter * param)
Definition at line 192 of file AreaShape.cpp.
References _initializeImplementation().
AreaShapeImplementation::~AreaShapeImplementation () protected virtual
Definition at line 197 of file AreaShape.cpp.
Member Function Documentation
DistributedObjectStub * AreaShapeImplementation::_getStub ()
Definition at line 217 of file AreaShape.cpp.
References _this.
void AreaShapeImplementation::_initializeImplementation () protected
Definition at line 204 of file AreaShape.cpp.
References _serializationHelperMethod(), and _this.
Referenced by AreaShapeImplementation().
void AreaShapeImplementation::_serializationHelperMethod () protected
Definition at line 253 of file AreaShape.cpp.
Referenced by _initializeImplementation(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::_serializationHelperMethod(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::_serializationHelperMethod(), and server::zone::objects::area::areashapes::RingAreaShapeImplementation::_serializationHelperMethod().
void AreaShapeImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 212 of file AreaShape.cpp.
References _this.
Referenced by server::zone::objects::area::areashapes::CircularAreaShapeImplementation::_setStub(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::_setStub(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::_setStub(), and server::zone::objects::area::areashapes::AreaShape::AreaShape().
bool AreaShapeImplementation::containsPoint (float x, float y) virtual
Check if the coordinate is within the area shape.
Parameters
x the x coordinate.
y the y coordinate.
Returns
true if the coordinate is within the area shape.
Reimplemented in server::zone::objects::area::areashapes::RingAreaShapeImplementation, server::zone::objects::area::areashapes::RectangularAreaShapeImplementation, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 329 of file AreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::AreaShape::containsPoint(), and getRandomPosition().
bool AreaShapeImplementation::containsPoint (const Vector3 & point) virtual
Check if the coordinate is within the area shape.
Parameters
point the point to check if it is within the area shape.
Returns
true if the coordinate is within the area shape.
Reimplemented in server::zone::objects::area::areashapes::RingAreaShapeImplementation, server::zone::objects::area::areashapes::RectangularAreaShapeImplementation, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 334 of file AreaShape.cpp.
void AreaShapeImplementation::finalize () protected
Definition at line 201 of file AreaShape.cpp.
float AreaShapeImplementation::getArea () virtual
Get the area of the areaShape.
Returns
the area of the area shape.
Reimplemented in server::zone::objects::area::areashapes::RingAreaShapeImplementation, server::zone::objects::area::areashapes::RectangularAreaShapeImplementation, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 364 of file AreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::AreaShape::getArea().
Vector3 AreaShapeImplementation::getAreaCenter ()
Get the area center.
Returns
the area center.
Definition at line 24 of file AreaShapeImplementation.cpp.
References areaCenter.
Referenced by server::zone::objects::area::areashapes::AreaShape::getAreaCenter().
float AreaShapeImplementation::getRadius () virtual
Get the minimum radius of a circle bounding the area shape.
Returns
the minimum bonding radius.
Reimplemented in server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 339 of file AreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::AreaShape::getRadius().
Vector3 AreaShapeImplementation::getRandomPosition () virtual
Generate a random position within the area.
Returns
a random position within the area.
Reimplemented in server::zone::objects::area::areashapes::RingAreaShapeImplementation, server::zone::objects::area::areashapes::RectangularAreaShapeImplementation, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 10 of file AreaShapeImplementation.cpp.
Referenced by server::zone::objects::area::areashapes::AreaShape::getRandomPosition().
Vector3 AreaShapeImplementation::getRandomPosition (const Vector3 & origin, float minDistance, float maxDistance) virtual
Generate a random position within the area with the supplied origin and radius as limits.
Parameters
origin the origin coordinate to generate the random position from.
minDistance the minimum distance from the origin.
maxDistance the maximum distance from the origin.
Returns
a random position within the area.
Reimplemented in server::zone::objects::area::areashapes::RingAreaShapeImplementation, server::zone::objects::area::areashapes::RectangularAreaShapeImplementation, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 15 of file AreaShapeImplementation.cpp.
References containsPoint().
bool AreaShapeImplementation::intersectsWith (AreaShape * areaShape) virtual
Check if this area shape intersects with the supplied area shape.
Parameters
areaShape the area shape to check for intersections with.
Returns
true if the area shapes intersects each other.
Reimplemented in server::zone::objects::area::areashapes::RingAreaShapeImplementation, server::zone::objects::area::areashapes::RectangularAreaShapeImplementation, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 359 of file AreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::AreaShape::intersectsWith().
bool AreaShapeImplementation::isCircularAreaShape () virtual
Check if this is a circular area shape.
Returns
true if it is a circular area shape.
Reimplemented in server::zone::objects::area::areashapes::RingAreaShapeImplementation, server::zone::objects::area::areashapes::RectangularAreaShapeImplementation, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 344 of file AreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::AreaShape::isCircularAreaShape().
bool AreaShapeImplementation::isRectangularAreaShape () virtual
Check if this is a rectangular area shape.
Returns
true if it is a rectangular area shape.
Reimplemented in server::zone::objects::area::areashapes::RingAreaShapeImplementation, server::zone::objects::area::areashapes::RectangularAreaShapeImplementation, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 349 of file AreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::AreaShape::isRectangularAreaShape().
bool AreaShapeImplementation::isRingAreaShape () virtual
Check if this is a ring area shape.
Returns
true if it is a ring area shape.
Reimplemented in server::zone::objects::area::areashapes::RingAreaShapeImplementation, server::zone::objects::area::areashapes::RectangularAreaShapeImplementation, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 354 of file AreaShape.cpp.
Referenced by server::zone::objects::area::areashapes::AreaShape::isRingAreaShape().
void AreaShapeImplementation::lock (bool doLock = true) protected
Definition at line 225 of file AreaShape.cpp.
References _this.
void AreaShapeImplementation::lock (ManagedObject * obj) protected
Definition at line 229 of file AreaShape.cpp.
References _this.
AreaShapeImplementation::operator const AreaShape * ()
Definition at line 221 of file AreaShape.cpp.
void AreaShapeImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented in server::zone::objects::area::areashapes::RingAreaShapeImplementation, server::zone::objects::area::areashapes::RectangularAreaShapeImplementation, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 260 of file AreaShape.cpp.
References readObjectMember().
bool AreaShapeImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 279 of file AreaShape.cpp.
References areaCenter.
Referenced by readObject(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::readObjectMember(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::readObjectMember(), and server::zone::objects::area::areashapes::RingAreaShapeImplementation::readObjectMember().
void AreaShapeImplementation::rlock (bool doLock = true) protected
Definition at line 233 of file AreaShape.cpp.
References _this.
void AreaShapeImplementation::runlock (bool doLock = true) protected
Definition at line 249 of file AreaShape.cpp.
References _this.
void AreaShapeImplementation::setAreaCenter (float x, float y)
Set the area center.
Parameters
x the x coordinate.
y the y coordinate.
Definition at line 324 of file AreaShape.cpp.
References areaCenter.
Referenced by server::zone::objects::area::areashapes::AreaShape::setAreaCenter().
void AreaShapeImplementation::unlock (bool doLock = true) protected
Definition at line 245 of file AreaShape.cpp.
References _this.
void AreaShapeImplementation::wlock (bool doLock = true) protected
Definition at line 237 of file AreaShape.cpp.
References _this.
void AreaShapeImplementation::wlock (ManagedObject * obj) protected
Definition at line 241 of file AreaShape.cpp.
References _this.
void AreaShapeImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented in server::zone::objects::area::areashapes::RingAreaShapeImplementation, server::zone::objects::area::areashapes::RectangularAreaShapeImplementation, and server::zone::objects::area::areashapes::CircularAreaShapeImplementation.
Definition at line 293 of file AreaShape.cpp.
References writeObjectMembers().
int AreaShapeImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 300 of file AreaShape.cpp.
References areaCenter.
Referenced by writeObject(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::writeObjectMembers(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::writeObjectMembers(), and server::zone::objects::area::areashapes::RingAreaShapeImplementation::writeObjectMembers().
Friends And Related Function Documentation
friend class AreaShape friend
Definition at line 261 of file AreaShape.h.
Member Data Documentation
WeakReference<AreaShape*> server::zone::objects::area::areashapes::AreaShapeImplementation::_this
Definition at line 227 of file AreaShape.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
Vector3 server::zone::objects::area::areashapes::AreaShapeImplementation::areaCenter protected
Definition at line 140 of file AreaShape.h.
Referenced by AreaShapeImplementation(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::containsPoint(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::containsPoint(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::containsPoint(), getAreaCenter(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::getClosestPoint(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::getFarthestPoint(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::getRandomPosition(), server::zone::objects::area::areashapes::RectangularAreaShapeImplementation::getRandomPosition(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::getRandomPosition(), server::zone::objects::area::areashapes::CircularAreaShapeImplementation::intersectsWithCircle(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::intersectsWithCircle(), server::zone::objects::area::areashapes::RingAreaShapeImplementation::intersectsWithRing(), readObjectMember(), setAreaCenter(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/AreaShape.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/AreaShape.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/area/areashapes/AreaShapeImplementation.cpp