Core3: server::zone::managers::planet::PlanetManager Class Reference
server::zone::managers::planet::PlanetManager Class Reference
#include <PlanetManager.h>
Public Member Functions
PlanetManager (Zone *planet, ZoneProcessServer *srv)
void initializeTransientMembers ()
void initialize ()
void loadClientRegions ()
void loadClientPoiData ()
void loadBadgeAreas ()
void loadPerformanceLocations ()
PlanetTravelPoint * getNearestPlanetTravelPoint (SceneObject *object, float range=16000.0)
PlanetTravelPoint * getNearestPlanetTravelPoint (const Vector3 &position, float range=16000.0)
bool isBuildingPermittedAt (float x, float y, SceneObject *objectTryingToBuild=NULL)
bool isCampingPermittedAt (float x, float y, float margin)
Reference< SceneObject * > findObjectTooCloseToDecoration (float x, float y, float margin)
bool isInRangeWithPoi (float x, float y, float range)
bool isInObjectsNoBuildZone (float x, float y, float extraMargin)
int getTravelFare (const String &departurePlanet, const String &arrivalPlanet)
void sendPlanetTravelPointListResponse (CreatureObject *player)
Reference< SceneObject * > createTicket (const String &departurePoint, const String &arrivalPlanet, const String &arrivalPoint)
bool validateRegionName (const String &name)
bool validateClientCityInRange (CreatureObject *creatureObject, float x, float y)
WeatherManager * getWeatherManager ()
TerrainManager * getTerrainManager ()
int getRegionCount ()
int getNumberOfCities ()
void increaseNumberOfCities ()
CityRegion * getRegion (int index)
CityRegion * getRegion (const String &region)
CityRegion * getRegionAt (float x, float y)
void addRegion (CityRegion *region)
void dropRegion (const String &region)
bool hasRegion (const String &name)
void addPerformanceLocation (SceneObject *obj)
MissionTargetMap * getPerformanceLocations ()
bool isExistingPlanetTravelPoint (const String &pointName)
bool isInterplanetaryTravelAllowed (const String &pointName)
bool isIncomingTravelAllowed (const String &pointName)
PlanetTravelPoint * getPlanetTravelPoint (const String &pointName)
bool isTravelToLocationPermitted (const String &destinationPoint, const String &arrivalPlanet, const String &arrivalPoint)
void scheduleShuttle (CreatureObject *shuttle, int shuttleType)
void removeShuttle (CreatureObject *shuttle)
bool checkShuttleStatus (CreatureObject *creature, CreatureObject *shuttle)
bool isInWater (float x, float y)
float findClosestWorldFloor (float x, float y, float z, float swimHeight, IntersectionResults *intersections=NULL, CloseObjectsVector *closeObjects=NULL)
void addPlayerCityTravelPoint (PlanetTravelPoint *ptp)
void removePlayerCityTravelPoint (const String &cityName)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const int SHUTTLEPORT = 0
static const int STARPORT = 1
Protected Member Functions
PlanetManager (DummyConstructorParameter *param)
virtual ~PlanetManager ()
Friends
class PlanetManagerHelper
Detailed Description
Definition at line 199 of file PlanetManager.h.
Constructor & Destructor Documentation
PlanetManager::PlanetManager (Zone * planet, ZoneProcessServer * srv)
Definition at line 33 of file PlanetManager.cpp.
References server::zone::managers::planet::PlanetManagerImplementation::_setStub().
PlanetManager::PlanetManager (DummyConstructorParameter * param) protected
Definition at line 40 of file PlanetManager.cpp.
PlanetManager::~PlanetManager () protected virtual
Definition at line 44 of file PlanetManager.cpp.
Member Function Documentation
DistributedObjectServant * PlanetManager::_getImplementation ()
Definition at line 627 of file PlanetManager.cpp.
Referenced by addPerformanceLocation(), addPlayerCityTravelPoint(), addRegion(), checkShuttleStatus(), createTicket(), dropRegion(), findClosestWorldFloor(), findObjectTooCloseToDecoration(), getNearestPlanetTravelPoint(), getNumberOfCities(), getPerformanceLocations(), getPlanetTravelPoint(), getRegion(), getRegionAt(), getRegionCount(), getTerrainManager(), getTravelFare(), getWeatherManager(), hasRegion(), increaseNumberOfCities(), initialize(), initializeTransientMembers(), isBuildingPermittedAt(), isCampingPermittedAt(), isExistingPlanetTravelPoint(), isIncomingTravelAllowed(), isInObjectsNoBuildZone(), isInRangeWithPoi(), isInterplanetaryTravelAllowed(), isInWater(), isTravelToLocationPermitted(), loadBadgeAreas(), loadClientPoiData(), loadClientRegions(), loadPerformanceLocations(), removePlayerCityTravelPoint(), removeShuttle(), scheduleShuttle(), sendPlanetTravelPointListResponse(), validateClientCityInRange(), and validateRegionName().
DistributedObjectServant * PlanetManager::_getImplementationForRead ()
Definition at line 633 of file PlanetManager.cpp.
void PlanetManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 637 of file PlanetManager.cpp.
void PlanetManager::addPerformanceLocation (SceneObject * obj)
Definition at line 446 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::addPerformanceLocation(), and RPC_ADDPERFORMANCELOCATION__SCENEOBJECT_.
void PlanetManager::addPlayerCityTravelPoint (PlanetTravelPoint * ptp)
Definition at line 604 of file PlanetManager.cpp.
References _getImplementation(), and server::zone::managers::planet::PlanetManagerImplementation::addPlayerCityTravelPoint().
Referenced by ShuttleZoneComponent::notifyInsertToZone(), and server::zone::objects::region::CityRegionImplementation::notifyLoadFromDatabase().
void PlanetManager::addRegion (CityRegion * region)
Definition at line 404 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::addRegion(), and RPC_ADDREGION__CITYREGION_.
Referenced by server::zone::objects::region::CityRegionImplementation::notifyLoadFromDatabase().
bool PlanetManager::checkShuttleStatus (CreatureObject * creature, CreatureObject * shuttle)
Definition at line 565 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::checkShuttleStatus(), and RPC_CHECKSHUTTLESTATUS__CREATUREOBJECT_CREATUREOBJECT_.
Reference< SceneObject * > PlanetManager::createTicket (const String & departurePoint, const String & arrivalPlanet, const String & arrivalPoint)
Creates a travel ticket from the departure point on this planet to the arrival point on the arrival planet.
Parameters
departurePoint The point on this planet from which the ticket is set to depart.
arrivalPlanet The planet to which the ticket is set to arrive.
departurePoint The point on the arrival planet to which the ticket is set to arrive.
Returns
Returns a travel ticket for the route specified, or NULL if it could not be created.
Definition at line 254 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::createTicket(), and RPC_CREATETICKET__STRING_STRING_STRING_.
void PlanetManager::dropRegion (const String & region)
Definition at line 418 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::dropRegion(), and RPC_DROPREGION__STRING_.
Referenced by server::zone::managers::city::CityManagerImplementation::unregisterCity().
float PlanetManager::findClosestWorldFloor (float x, float y, float z, float swimHeight, IntersectionResults * intersections = NULL, CloseObjectsVector * closeObjects = NULL)
Definition at line 595 of file PlanetManager.cpp.
References _getImplementation(), and server::zone::managers::planet::PlanetManagerImplementation::findClosestWorldFloor().
Referenced by server::zone::objects::creature::AiAgentImplementation::findNextPosition().
Reference< SceneObject * > PlanetManager::findObjectTooCloseToDecoration (float x, float y, float margin)
Definition at line 177 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::findObjectTooCloseToDecoration(), and RPC_FINDOBJECTTOOCLOSETODECORATION__FLOAT_FLOAT_FLOAT_.
Referenced by CityDecorationTask::placeDecoration().
PlanetTravelPoint * PlanetManager::getNearestPlanetTravelPoint (SceneObject * object, float range = 16000.0)
Returns the closest PlanetTravelPoint within the given range.
Parameters
object The object to use as reference.
range The maximum range to search within.
Returns
Returns a PlanetTravelPoint or NULL if not found in range
Definition at line 127 of file PlanetManager.cpp.
References _getImplementation(), and server::zone::managers::planet::PlanetManagerImplementation::getNearestPlanetTravelPoint().
Referenced by server::zone::objects::tangible::terminal::travel::TravelTerminalImplementation::getPlanetTravelPoint(), ShuttleZoneComponent::notifyInsertToZone(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission().
PlanetTravelPoint * PlanetManager::getNearestPlanetTravelPoint (const Vector3 & position, float range = 16000.0)
Returns the closest PlanetTravelPoint within the given range.
Parameters
position The position to use as reference.
range The maximum range to search within.
Returns
Returns a PlanetTravelPoint or NULL if not found in range
Definition at line 136 of file PlanetManager.cpp.
References _getImplementation(), and server::zone::managers::planet::PlanetManagerImplementation::getNearestPlanetTravelPoint().
int PlanetManager::getNumberOfCities ()
Definition at line 335 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::getNumberOfCities(), and RPC_GETNUMBEROFCITIES__.
MissionTargetMap * PlanetManager::getPerformanceLocations ()
Definition at line 460 of file PlanetManager.cpp.
References _getImplementation(), and server::zone::managers::planet::PlanetManagerImplementation::getPerformanceLocations().
Referenced by server::zone::managers::mission::MissionManagerImplementation::randomizeGenericEntertainerMission().
PlanetTravelPoint * PlanetManager::getPlanetTravelPoint (const String & pointName)
Gets the PlanetTravelPoint that corresponds to the point name. If the point doesn't exist then it will return NULL.
Parameters
pointName The planet travel point's name.
Returns
PlanetTravelPoint for the given point name.
Definition at line 511 of file PlanetManager.cpp.
References _getImplementation(), and server::zone::managers::planet::PlanetManagerImplementation::getPlanetTravelPoint().
CityRegion * PlanetManager::getRegion (int index)
Definition at line 361 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::getRegion(), and RPC_GETREGION__INT_.
CityRegion * PlanetManager::getRegion (const String & region)
Definition at line 375 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::getRegion(), and RPC_GETREGION__STRING_.
CityRegion * PlanetManager::getRegionAt (float x, float y)
Definition at line 389 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::getRegionAt(), and RPC_GETREGIONAT__FLOAT_FLOAT_.
int PlanetManager::getRegionCount ()
Definition at line 322 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::getRegionCount(), and RPC_GETREGIONCOUNT__.
TerrainManager * PlanetManager::getTerrainManager ()
Definition at line 313 of file PlanetManager.cpp.
References _getImplementation(), and server::zone::managers::planet::PlanetManagerImplementation::getTerrainManager().
Referenced by server::zone::objects::mission::DeliverMissionObjectiveImplementation::activateWithResult(), server::zone::managers::minigames::FishingManagerImplementation::checkLocation(), CollisionManager::checkShipCollision(), server::zone::managers::minigames::FishingManagerImplementation::checkUpdateMarker(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::findValidSpawnPosition(), server::zone::objects::mission::ReconMissionObjectiveImplementation::getEndPosition(), CollisionManager::getWorldFloorCollision(), CollisionManager::getWorldFloorCollisions(), server::zone::managers::mission::MissionManagerImplementation::randomizeGenericDestroyMission(), ZoneContainerComponent::removeObject(), and ZoneContainerComponent::transferObject().
int PlanetManager::getTravelFare (const String & departurePlanet, const String & arrivalPlanet)
Gets the cost to travel via shuttleport/starport to the destination planet. If the value is 0, then travel to the planet from this planet is disabled.
Parameters
destinationPlanet The planet that to which is being travelled. Can be the same planet.
Returns
The cost to travel to the destination planet.
Definition at line 225 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::getTravelFare(), and RPC_GETTRAVELFARE__STRING_STRING_.
WeatherManager * PlanetManager::getWeatherManager ()
Definition at line 300 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::getWeatherManager(), and RPC_GETWEATHERMANAGER__.
Referenced by server::zone::objects::player::PlayerObjectImplementation::doRecovery().
bool PlanetManager::hasRegion (const String & name)
Definition at line 432 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::hasRegion(), and RPC_HASREGION__STRING_.
void PlanetManager::increaseNumberOfCities ()
Definition at line 348 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::increaseNumberOfCities(), and RPC_INCREASENUMBEROFCITIES__.
void PlanetManager::initialize ()
Definition at line 62 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::initialize(), and RPC_INITIALIZE__.
void PlanetManager::initializeTransientMembers ()
Definition at line 49 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
bool PlanetManager::isBuildingPermittedAt (float x, float y, SceneObject * objectTryingToBuild = NULL)
Definition at line 145 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::isBuildingPermittedAt(), and RPC_ISBUILDINGPERMITTEDAT__FLOAT_FLOAT_SCENEOBJECT_.
Referenced by server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::canSpawnTargetAt(), server::zone::managers::mission::MissionManagerImplementation::getRandomBountyTargetPosition(), server::zone::managers::director::DirectorManager::getSpawnPoint(), and server::zone::managers::mission::MissionManagerImplementation::randomizeGenericReconMission().
bool PlanetManager::isCampingPermittedAt (float x, float y, float margin)
Definition at line 161 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::isCampingPermittedAt(), and RPC_ISCAMPINGPERMITTEDAT__FLOAT_FLOAT_FLOAT_.
bool PlanetManager::isExistingPlanetTravelPoint (const String & pointName)
Checks to see if the point is an existing planet travel point.
Parameters
pointName The name of the point to check for.
Returns
Returns true if the point exists.
Definition at line 469 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::isExistingPlanetTravelPoint(), and RPC_ISEXISTINGPLANETTRAVELPOINT__STRING_.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::isTravelToLocationPermitted().
bool PlanetManager::isIncomingTravelAllowed (const String & pointName)
Checks to see if incoming travel is allowed to the specified point.
Parameters
pointName The point name representing a travel point belonging to this planet.
Returns
Returns true if incoming travel is allowed.
Definition at line 497 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::isIncomingTravelAllowed(), and RPC_ISINCOMINGTRAVELALLOWED__STRING_.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::isTravelToLocationPermitted().
bool PlanetManager::isInObjectsNoBuildZone (float x, float y, float extraMargin)
Definition at line 209 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::isInObjectsNoBuildZone(), and RPC_ISINOBJECTSNOBUILDZONE__FLOAT_FLOAT_FLOAT_.
Referenced by server::zone::objects::mission::DestroyMissionObjectiveImplementation::findValidSpawnPosition(), and server::zone::managers::director::DirectorManager::getSpawnPoint().
bool PlanetManager::isInRangeWithPoi (float x, float y, float range)
Definition at line 193 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::isInRangeWithPoi(), and RPC_ISINRANGEWITHPOI__FLOAT_FLOAT_FLOAT_.
bool PlanetManager::isInterplanetaryTravelAllowed (const String & pointName)
Checks to see if interplanetary travel is allowed to the specified point.
Parameters
pointName The point name representing a travel point belonging to this planet.
Returns
Returns true if interplanetary travel is allowed.
Definition at line 483 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::isInterplanetaryTravelAllowed(), and RPC_ISINTERPLANETARYTRAVELALLOWED__STRING_.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::isTravelToLocationPermitted().
bool PlanetManager::isInWater (float x, float y)
Definition at line 580 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::isInWater(), and RPC_ISINWATER__FLOAT_FLOAT_.
Referenced by server::zone::objects::mission::bountyhunter::events::BountyHunterTargetTask::canSpawnTargetAt(), and server::zone::managers::mission::MissionManagerImplementation::getRandomBountyTargetPosition().
bool PlanetManager::isTravelToLocationPermitted (const String & destinationPoint, const String & arrivalPlanet, const String & arrivalPoint)
Checks to see the travel between the points is allowed based on their settings.
Parameters
destinationPoint The point from which is being traveled.
arrivalPlanet The planet to which is being traveled.
arrivalPoint The point to which is being traveled.
Returns
Returns true if travel is permitted between the two points.
Definition at line 520 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::isTravelToLocationPermitted(), and RPC_ISTRAVELTOLOCATIONPERMITTED__STRING_STRING_STRING_.
void PlanetManager::loadBadgeAreas ()
Definition at line 101 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::loadBadgeAreas(), and RPC_LOADBADGEAREAS__.
void PlanetManager::loadClientPoiData ()
Definition at line 88 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::loadClientPoiData(), and RPC_LOADCLIENTPOIDATA__.
void PlanetManager::loadClientRegions ()
Definition at line 75 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::loadClientRegions(), and RPC_LOADCLIENTREGIONS__.
void PlanetManager::loadPerformanceLocations ()
Definition at line 114 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::loadPerformanceLocations(), and RPC_LOADPERFORMANCELOCATIONS__.
void PlanetManager::removePlayerCityTravelPoint (const String & cityName)
Definition at line 613 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::removePlayerCityTravelPoint(), and RPC_REMOVEPLAYERCITYTRAVELPOINT__STRING_.
void PlanetManager::removeShuttle (CreatureObject * shuttle)
Definition at line 551 of file PlanetManager.cpp.
References _getImplementation(), server::zone::managers::planet::PlanetManagerImplementation::removeShuttle(), and RPC_REMOVESHUTTLE__CREATUREOBJECT_.
void PlanetManager::scheduleShuttle (CreatureObject * shuttle, int shuttleType)
Definition at line 536 of file PlanetManager.cpp.
References _getImplementation(), RPC_SCHEDULESHUTTLE__CREATUREOBJECT_INT_, and server::zone::managers::planet::PlanetManagerImplementation::scheduleShuttle().
Referenced by ShuttleZoneComponent::notifyInsertToZone(), and server::zone::objects::region::CityRegionImplementation::notifyLoadFromDatabase().
void PlanetManager::sendPlanetTravelPointListResponse (CreatureObject * player)
Definition at line 240 of file PlanetManager.cpp.
References _getImplementation(), RPC_SENDPLANETTRAVELPOINTLISTRESPONSE__CREATUREOBJECT_, and server::zone::managers::planet::PlanetManagerImplementation::sendPlanetTravelPointListResponse().
Referenced by PlanetTravelPointListRequestCallback::run().
bool PlanetManager::validateClientCityInRange (CreatureObject * creatureObject, float x, float y)
Definition at line 284 of file PlanetManager.cpp.
References _getImplementation(), RPC_VALIDATECLIENTCITYINRANGE__CREATUREOBJECT_FLOAT_FLOAT_, and server::zone::managers::planet::PlanetManagerImplementation::validateClientCityInRange().
Referenced by PlaceCityHallSuiCallback::run().
bool PlanetManager::validateRegionName (const String & name)
Definition at line 270 of file PlanetManager.cpp.
References _getImplementation(), RPC_VALIDATEREGIONNAME__STRING_, and server::zone::managers::planet::PlanetManagerImplementation::validateRegionName().
Referenced by PlaceCityHallSuiCallback::run().
Friends And Related Function Documentation
friend class PlanetManagerHelper friend
Definition at line 356 of file PlanetManager.h.
Member Data Documentation
const int server::zone::managers::planet::PlanetManager::SHUTTLEPORT = 0 static
Definition at line 201 of file PlanetManager.h.
const int server::zone::managers::planet::PlanetManager::STARPORT = 1 static
Definition at line 203 of file PlanetManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/PlanetManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/planet/PlanetManager.cpp