Core3: server::zone::managers::auction::AuctionsMap Class Reference
server::zone::managers::auction::AuctionsMap Class Reference
#include <AuctionsMap.h>
Public Member Functions
AuctionsMap ()
int addItem (CreatureObject *player, SceneObject *vendor, AuctionItem *item)
void deleteItem (SceneObject *vendor, AuctionItem *item)
AuctionItem * getItem (unsigned long long id)
bool containsItem (unsigned long long id)
TerminalListVector getVendorTerminalData (const String &planet, const String &region, SceneObject *vendor)
TerminalListVector getBazaarTerminalData (const String &planet, const String &region, SceneObject *vendor)
int getVendorItemCount (SceneObject *vendor)
void deleteTerminalItems (SceneObject *vendor)
int getCommodityCount (CreatureObject *player)
void updateUID (SceneObject *vendor, const String &oldUID, const String &newUID)
void updateVendorSearch (SceneObject *vendor, bool enabled)
void addToCommodityLimit (AuctionItem *item)
void removeFromCommodityLimit (AuctionItem *item)
int getBazaarCount ()
int getVendorCount ()
int getTotalItemCount ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
AuctionsMap (DummyConstructorParameter *param)
virtual ~AuctionsMap ()
Friends
class AuctionsMapHelper
Detailed Description
Definition at line 63 of file AuctionsMap.h.
Constructor & Destructor Documentation
AuctionsMap::AuctionsMap ()
Definition at line 17 of file AuctionsMap.cpp.
References server::zone::managers::auction::AuctionsMapImplementation::_setStub().
AuctionsMap::AuctionsMap (DummyConstructorParameter * param) protected
Definition at line 24 of file AuctionsMap.cpp.
AuctionsMap::~AuctionsMap () protected virtual
Definition at line 28 of file AuctionsMap.cpp.
Member Function Documentation
DistributedObjectServant * AuctionsMap::_getImplementation ()
Definition at line 250 of file AuctionsMap.cpp.
Referenced by addItem(), addToCommodityLimit(), containsItem(), deleteItem(), deleteTerminalItems(), getBazaarCount(), getBazaarTerminalData(), getCommodityCount(), getItem(), getTotalItemCount(), getVendorCount(), getVendorItemCount(), getVendorTerminalData(), removeFromCommodityLimit(), updateUID(), and updateVendorSearch().
DistributedObjectServant * AuctionsMap::_getImplementationForRead ()
Definition at line 256 of file AuctionsMap.cpp.
void AuctionsMap::_setImplementation (DistributedObjectServant * servant)
Definition at line 260 of file AuctionsMap.cpp.
int AuctionsMap::addItem (CreatureObject * player, SceneObject * vendor, AuctionItem * item)
Definition at line 33 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::addItem(), and RPC_ADDITEM__CREATUREOBJECT_SCENEOBJECT_AUCTIONITEM_.
void AuctionsMap::addToCommodityLimit (AuctionItem * item)
Definition at line 183 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::addToCommodityLimit(), and RPC_ADDTOCOMMODITYLIMIT__AUCTIONITEM_.
bool AuctionsMap::containsItem (unsigned long long id)
Definition at line 78 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::containsItem(), and RPC_CONTAINSITEM__LONG_.
void AuctionsMap::deleteItem (SceneObject * vendor, AuctionItem * item)
Definition at line 49 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::deleteItem(), and RPC_DELETEITEM__SCENEOBJECT_AUCTIONITEM_.
void AuctionsMap::deleteTerminalItems (SceneObject * vendor)
Definition at line 124 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::deleteTerminalItems(), and RPC_DELETETERMINALITEMS__SCENEOBJECT_.
int AuctionsMap::getBazaarCount ()
Definition at line 211 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::getBazaarCount(), and RPC_GETBAZAARCOUNT__.
TerminalListVector AuctionsMap::getBazaarTerminalData (const String & planet, const String & region, SceneObject * vendor)
Definition at line 101 of file AuctionsMap.cpp.
References _getImplementation(), and server::zone::managers::auction::AuctionsMapImplementation::getBazaarTerminalData().
int AuctionsMap::getCommodityCount (CreatureObject * player)
Definition at line 138 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::getCommodityCount(), and RPC_GETCOMMODITYCOUNT__CREATUREOBJECT_.
AuctionItem * AuctionsMap::getItem (unsigned long long id)
Definition at line 64 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::getItem(), and RPC_GETITEM__LONG_.
int AuctionsMap::getTotalItemCount ()
Definition at line 237 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::getTotalItemCount(), and RPC_GETTOTALITEMCOUNT__.
int AuctionsMap::getVendorCount ()
Definition at line 224 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::getVendorCount(), and RPC_GETVENDORCOUNT__.
int AuctionsMap::getVendorItemCount (SceneObject * vendor)
Definition at line 110 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::getVendorItemCount(), and RPC_GETVENDORITEMCOUNT__SCENEOBJECT_.
TerminalListVector AuctionsMap::getVendorTerminalData (const String & planet, const String & region, SceneObject * vendor)
Definition at line 92 of file AuctionsMap.cpp.
References _getImplementation(), and server::zone::managers::auction::AuctionsMapImplementation::getVendorTerminalData().
void AuctionsMap::removeFromCommodityLimit (AuctionItem * item)
Definition at line 197 of file AuctionsMap.cpp.
References _getImplementation(), server::zone::managers::auction::AuctionsMapImplementation::removeFromCommodityLimit(), and RPC_REMOVEFROMCOMMODITYLIMIT__AUCTIONITEM_.
void AuctionsMap::updateUID (SceneObject * vendor, const String & oldUID, const String & newUID)
Definition at line 152 of file AuctionsMap.cpp.
References _getImplementation(), RPC_UPDATEUID__SCENEOBJECT_STRING_STRING_, and server::zone::managers::auction::AuctionsMapImplementation::updateUID().
void AuctionsMap::updateVendorSearch (SceneObject * vendor, bool enabled)
Definition at line 168 of file AuctionsMap.cpp.
References _getImplementation(), RPC_UPDATEVENDORSEARCH__SCENEOBJECT_BOOL_, and server::zone::managers::auction::AuctionsMapImplementation::updateVendorSearch().
Friends And Related Function Documentation
friend class AuctionsMapHelper friend
Definition at line 109 of file AuctionsMap.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionsMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionsMap.cpp