Core3: server::zone::objects::scene::variables::StringIdParameter Class Reference
server::zone::objects::scene::variables::StringIdParameter Class Reference
#include <StringIdParameter.h>
Public Member Functions
StringIdParameter (const StringIdParameter &par)
StringIdParameter & operator= (const StringIdParameter &par)
void set (SceneObject *obj)
void set (StringId *sid)
void set (StringId &sid)
void clear ()
void set (uint64 oid)
void set (const String &file, const String &id)
void set (const UnicodeString &us)
void set (const String &cs)
void set (const char *cstr)
uint32 size () const
uint64 getPointerParameter () const
UnicodeString & getUnicodeParameter ()
String getDisplayedName ()
String & getFileParameter ()
String & getStringIDParameter ()
Protected Member Functions
StringIdParameter ()
Protected Attributes
uint64 pointerParameter
StringId stringID
UnicodeString customName
Private Member Functions
void addSerializableVariables ()
Friends
class server::chat::StringIdChatParameter
Detailed Description
Definition at line 69 of file StringIdParameter.h.
Constructor & Destructor Documentation
server::zone::objects::scene::variables::StringIdParameter::StringIdParameter () inline protected
Definition at line 75 of file StringIdParameter.h.
StringIdParameter::StringIdParameter (const StringIdParameter & par)
Definition at line 50 of file StringIdParameter.cpp.
References addSerializableVariables(), customName, pointerParameter, and stringID.
Member Function Documentation
void server::zone::objects::scene::variables::StringIdParameter::addSerializableVariables () inline private
Definition at line 80 of file StringIdParameter.h.
Referenced by StringIdParameter().
void server::zone::objects::scene::variables::StringIdParameter::clear () inline
Definition at line 104 of file StringIdParameter.h.
Referenced by set().
String server::zone::objects::scene::variables::StringIdParameter::getDisplayedName () inline
Definition at line 151 of file StringIdParameter.h.
String& server::zone::objects::scene::variables::StringIdParameter::getFileParameter () inline
Definition at line 159 of file StringIdParameter.h.
Referenced by server::chat::StringIdChatParameter::addToPacketStream().
uint64 server::zone::objects::scene::variables::StringIdParameter::getPointerParameter () const inline
Definition at line 143 of file StringIdParameter.h.
Referenced by server::chat::StringIdChatParameter::addToPacketStream().
String& server::zone::objects::scene::variables::StringIdParameter::getStringIDParameter () inline
Definition at line 163 of file StringIdParameter.h.
Referenced by server::chat::StringIdChatParameter::addToPacketStream().
UnicodeString& server::zone::objects::scene::variables::StringIdParameter::getUnicodeParameter () inline
Definition at line 147 of file StringIdParameter.h.
Referenced by server::chat::StringIdChatParameter::addToPacketStream().
StringIdParameter& server::zone::objects::scene::variables::StringIdParameter::operator= (const StringIdParameter & par) inline
Definition at line 89 of file StringIdParameter.h.
References customName, pointerParameter, and stringID.
void StringIdParameter::set (SceneObject * obj)
Definition at line 58 of file StringIdParameter.cpp.
References clear(), server::zone::objects::scene::SceneObject::getObjectID(), and pointerParameter.
Referenced by LuaConversationScreen::setDialogText().
void StringIdParameter::set (StringId * sid)
Definition at line 64 of file StringIdParameter.cpp.
void StringIdParameter::set (StringId & sid)
Definition at line 68 of file StringIdParameter.cpp.
References clear(), and stringID.
void server::zone::objects::scene::variables::StringIdParameter::set (uint64 oid) inline
Definition at line 109 of file StringIdParameter.h.
void server::zone::objects::scene::variables::StringIdParameter::set (const String & file, const String & id) inline
Definition at line 115 of file StringIdParameter.h.
void server::zone::objects::scene::variables::StringIdParameter::set (const UnicodeString & us) inline
Definition at line 121 of file StringIdParameter.h.
void server::zone::objects::scene::variables::StringIdParameter::set (const String & cs) inline
Definition at line 127 of file StringIdParameter.h.
void server::zone::objects::scene::variables::StringIdParameter::set (const char * cstr) inline
Definition at line 133 of file StringIdParameter.h.
uint32 server::zone::objects::scene::variables::StringIdParameter::size () const inline
Definition at line 139 of file StringIdParameter.h.
Friends And Related Function Documentation
friend class server::chat::StringIdChatParameter friend
Definition at line 167 of file StringIdParameter.h.
Member Data Documentation
UnicodeString server::zone::objects::scene::variables::StringIdParameter::customName protected
Definition at line 73 of file StringIdParameter.h.
Referenced by operator=(), and StringIdParameter().
uint64 server::zone::objects::scene::variables::StringIdParameter::pointerParameter protected
Definition at line 71 of file StringIdParameter.h.
Referenced by operator=(), set(), and StringIdParameter().
StringId server::zone::objects::scene::variables::StringIdParameter::stringID protected
Definition at line 72 of file StringIdParameter.h.
Referenced by operator=(), set(), and StringIdParameter().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/StringIdParameter.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/scene/variables/StringIdParameter.cpp