Core3: MapFamily Class Reference
MapFamily Class Reference
#include <MapFamily.h>
Public Member Functions
void parseFromIffStream (engine::util::IffStream *iffStream)
MapFractal * getMfrc ()
int getVar1 ()
String & getName ()
Public Member Functions inherited from TemplateVariable<'MFAM'>
virtual ~TemplateVariable ()
void readObject (engine::util::IffStream *iffStream)
Public Member Functions inherited from IffTemplateVariable
virtual ~IffTemplateVariable ()
Private Attributes
int var1
String var2
MapFractal mfrc
Detailed Description
Definition at line 15 of file MapFamily.h.
Member Function Documentation
MapFractal* MapFamily::getMfrc () inline
Definition at line 31 of file MapFamily.h.
References mfrc.
Referenced by MapGroup::parseFromIffStream().
String& MapFamily::getName () inline
Definition at line 39 of file MapFamily.h.
References var2.
int MapFamily::getVar1 () inline
Definition at line 35 of file MapFamily.h.
References var1.
Referenced by MapGroup::parseFromIffStream().
void MapFamily::parseFromIffStream (engine::util::IffStream * iffStream) inline virtual
Reimplemented from TemplateVariable<'MFAM'>.
Definition at line 20 of file MapFamily.h.
References mfrc, TemplateVariable< formType >::readObject(), var1, and var2.
Member Data Documentation
MapFractal MapFamily::mfrc private
Definition at line 18 of file MapFamily.h.
Referenced by getMfrc(), and parseFromIffStream().
int MapFamily::var1 private
Definition at line 16 of file MapFamily.h.
Referenced by getVar1(), and parseFromIffStream().
String MapFamily::var2 private
Definition at line 17 of file MapFamily.h.
Referenced by getName(), and parseFromIffStream().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/terrain/MapFamily.h