Core3: server::zone::objects::tangible::weapon::WeaponObjectImplementation Class Reference
server::zone::objects::tangible::weapon::WeaponObjectImplementation Class Reference
#include <WeaponObject.h>
Public Member Functions
WeaponObjectImplementation ()
WeaponObjectImplementation (DummyConstructorParameter *param)
void loadTemplateData (SharedObjectTemplate *templateData)
void initializeTransientMembers ()
void sendBaselinesTo (SceneObject *player)
void sendContainerTo (CreatureObject *player)
void fillAttributeList (AttributeListMessage *msg, CreatureObject *object)
void updateCraftingValues (CraftingValues *values, bool firstUpdate)
void createChildObjects ()
bool isCertifiedFor (CreatureObject *object)
Vector< String > * getDamageModifiers ()
Vector< String > * getSpeedModifiers ()
Vector< String > * getCreatureAccuracyModifiers ()
Vector< String > * getCreatureAimModifiers ()
Vector< String > * getDefenderDefenseModifiers ()
Vector< String > * getDefenderSecondaryDefenseModifiers ()
Vector< String > * getDefenderToughnessModifiers ()
void setCertified (bool cert)
int getAttackType ()
void setAttackType (int a)
bool isCertified ()
int getPointBlankAccuracy (bool withPup=true)
void setPointBlankAccuracy (int value)
int getPointBlankRange (bool withPup=true)
int getIdealRange (bool withPup=true)
void setIdealRange (int value)
int getMaxRange (bool withPup=true)
void setMaxRange (int value)
int getIdealAccuracy (bool withPup=true)
void setIdealAccuracy (int value)
int getArmorPiercing ()
int getMaxRangeAccuracy (bool withPup=true)
void setMaxRangeAccuracy (int value)
float getAttackSpeed (bool withPup=true)
void setAttackSpeed (float value)
float getMaxDamage (bool withPup=true)
void setMaxDamage (float value)
float getMinDamage (bool withPup=true)
void setMinDamage (float value)
float getWoundsRatio (bool withPup=true)
void setWoundsRatio (float value)
float getDamageRadius (bool withPup=true)
void setDamageRadius (float value)
int getHealthAttackCost (bool withPup=true)
void setHealthAttackCost (int value)
int getActionAttackCost (bool withPup=true)
void setActionAttackCost (int value)
int getMindAttackCost (bool withPup=true)
void setMindAttackCost (int value)
int getForceCost ()
void setForceCost (int value)
int getBladeColor ()
void setBladeColor (int value)
int getDamageType ()
String getXpType ()
int getNumberOfDots ()
int getDotType (int index)
int getDotAttribute (int index)
int getDotStrength (int index)
int getDotDuration (int index)
int getDotPotency (int index)
int getDotUses (int index)
void addDotType (int t)
void addDotAttribute (int a)
void addDotStrength (int s)
void addDotDuration (int du)
void addDotPotency (int po)
void addDotUses (int u)
void setDotUses (int u, int index)
String getWeaponType ()
bool isUnarmedWeapon ()
bool isMeleeWeapon ()
bool isRangedWeapon ()
bool isRifleWeapon ()
bool isThrownWeapon ()
bool isHeavyWeapon ()
bool isSpecialHeavyWeapon ()
bool isLightningRifle ()
bool isFlameThrower ()
bool isHeavyAcidRifle ()
bool isCarbineWeapon ()
bool isPistolWeapon ()
bool isOneHandMeleeWeapon ()
bool isPolearmWeaponObject ()
bool isTwoHandMeleeWeapon ()
bool isMineWeapon ()
bool isJediWeapon ()
bool isJediOneHandedWeapon ()
bool isJediTwoHandedWeapon ()
bool isJediPolearmWeapon ()
bool isWeaponObject ()
bool hasPowerup ()
void applyPowerup (CreatureObject *player, PowerupObject *pup)
PowerupObject * removePowerup ()
void decreasePowerupUses (CreatureObject *player)
String repairAttempt (int repairChance)
void decay (CreatureObject *user, float damage)
void setDamageSlice (float value)
void setSpeedSlice (float value)
virtual void applySkillModsTo (CreatureObject *creature, bool doCheck=true)
virtual void removeSkillModsFrom (CreatureObject *creature)
virtual void addSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
VectorMap< String, int > * getWearableSkillMods ()
operator const WeaponObject * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
TangibleObjectImplementation ()
TangibleObjectImplementation (DummyConstructorParameter *param)
void initializeMembers ()
virtual void addTemplateSkillMods (TangibleObject *targetObject)
virtual void removeSkillMod (const int skillType, const String &skillMod, int value, bool notifyClient=true)
virtual void removeAllSkillModsOfType (const int skillType, bool notifyClient=true)
virtual void removeTemplateSkillMods (TangibleObject *tangibleObject)
VectorMap< String, int > * getTemplateSkillMods ()
void initializeTransientMembers ()
void setCustomObjectName (const UnicodeString &name, bool notifyClient)
virtual void synchronizedUIListen (SceneObject *player, int value)
virtual void synchronizedUIStopListen (SceneObject *player, int value)
virtual void setDefender (SceneObject *defender)
virtual void addDefender (SceneObject *defender)
virtual void removeDefender (SceneObject *defender)
virtual void removeDefenders ()
virtual void setCombatState ()
virtual void setUseCount (unsigned int newUseCount, bool notifyClient=true)
void setCountdownTimer (unsigned int newCount, bool notifyClient=true)
void decreaseUseCount ()
virtual void clearCombatState (bool clearDefenders=true)
bool hasDefender (SceneObject *defender)
virtual bool isAttackableBy (CreatureObject *object)
virtual bool isAggressiveTo (CreatureObject *object)
virtual bool isHealableBy (CreatureObject *object)
virtual void sendPvpStatusTo (CreatureObject *player)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, bool notifyClient=true)
virtual int inflictDamage (TangibleObject *attacker, int damageType, float damage, bool destroy, const String &xp, bool notifyClient=true)
virtual int healDamage (TangibleObject *healer, int damageType, float damageToHeal, bool notifyClient=true)
void setConditionDamage (float condDamage, bool notifyClient=true)
void setCustomizationVariable (byte type, short value, bool notifyClient=true)
void setCustomizationVariable (const String &type, short value, bool notifyClient=true)
void setOptionsBitmask (unsigned int bitmask, bool notifyClient=true)
virtual int notifyObjectDestructionObservers (TangibleObject *attacker, int condition)
void dropFromDefenderLists (TangibleObject *destructor)
byte getUnknownByte ()
virtual bool isKiller ()
virtual bool isTicketCollector ()
virtual bool isTicketObject ()
CustomizationVariables * getCustomizationVariables ()
virtual int getUseCount ()
virtual int getDisplayedUseCount ()
int getMaxCondition ()
void setMaxCondition (int maxCond, bool notifyClient=true)
int getConditionDamage ()
int getVolume ()
void setComplexity (float value)
float getComplexity ()
unsigned int getOptionsBitmask ()
int getLevel ()
unsigned int getPvpStatusBitmask ()
bool isTangibleObject ()
void getCustomizationString (String &variables)
DeltaVector< ManagedReference
< SceneObject * > > * getDefenderList ()
SceneObject * getMainDefender ()
bool isDestroyed ()
void setFaction (unsigned int crc)
unsigned int getFaction ()
bool isRebel ()
bool isImperial ()
bool isNeutral ()
bool isSliceable ()
bool isSliced ()
void setSliceable (bool val)
void setSliced (bool slice)
virtual bool isPharmaceuticalObject ()
void setCustomizationString (const String &vars)
void setPvpStatusBitmask (int bitmask, bool notifyClient=true)
void setCraftersName (String &name)
virtual String getCraftersName ()
void setJunkDealerNeeded (int jdNeeded)
virtual int getJunkDealerNeeded ()
void setJunkValue (int jValue)
virtual int getJunkValue ()
void setSerialNumber (const String &serial)
virtual void setLevel (int lev)
virtual String getSerialNumber ()
ThreatMap * getThreatMap ()
Reference< FactoryCrate * > createFactoryCrate (bool insertSelf=false)
bool canRepair (CreatureObject *player)
void repair (CreatureObject *player)
bool isBroken ()
virtual float getHitChance ()
void broadcastPvpStatusBitmask ()
operator const TangibleObject * ()
DistributedObjectStub * _getStub ()
Public Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
SceneObjectImplementation ()
SceneObjectImplementation (DummyConstructorParameter *param)
void finalize ()
void initializePrivateData ()
virtual void createComponents ()
virtual void createContainerComponent ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void info (const String &msg, bool forced=false)
void error (const String &msg)
int inRangeObjects (unsigned int gameObjectType, float range)
bool isInRange (SceneObject *obj, float range)
virtual bool transferObject (SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *object, SceneObject *destination, bool notifyClient=false)
virtual void destroyObjectFromWorld (bool sendSelfDestroy)
virtual int canAddObject (SceneObject *object, int containmentType, String &errorDescription)
virtual int notifyObjectInsertedToChild (SceneObject *object, SceneObject *child, SceneObject *oldParent)
virtual int notifyObjectRemovedFromChild (SceneObject *object, SceneObject *child)
void updateToDatabase ()
void updateToDatabaseWithoutChildren ()
void updateToDatabaseAllObjects (bool startTask)
virtual void destroyPlayerCreatureFromDatabase (bool destroyContainedObjects=false)
virtual void destroyObjectFromDatabase (bool destroyContainedObjects=false)
virtual int canBeDestroyed (CreatureObject *player)
BaseMessage * link (unsigned long long objectID, unsigned int containmentType=4)
virtual void sendTo (SceneObject *player, bool doClose)
virtual void sendWithoutParentTo (SceneObject *player)
virtual void sendWithoutContainerObjectsTo (SceneObject *player)
virtual void sendDestroyTo (SceneObject *player)
virtual void sendContainerObjectsTo (SceneObject *player)
virtual void sendSlottedObjectsTo (SceneObject *player)
virtual void sendToOwner (bool doClose=true)
virtual void sendAttributeListTo (CreatureObject *object)
virtual void fillObjectMenuResponse (ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual void openContainerTo (CreatureObject *player)
virtual byte checkContainerPermission (CreatureObject *player, unsigned short permission)
virtual void closeContainerTo (CreatureObject *player, bool notify=true)
virtual void notifyInsertToZone (Zone *zone)
virtual void switchZone (const String &newTerrainName, float newPostionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
virtual void teleport (float newPositionX, float newPositionZ, float newPositionY, unsigned long long parentID=0)
void updateDirection (float fw, float fx, float fy, float fz)
void updateDirection (float angleHeadingRadians)
void notifyInsert (QuadTreeEntry *entry)
void notifyDissapear (QuadTreeEntry *entry)
virtual void notifyRemoveFromZone ()
virtual void updateZone (bool lightUpdate, bool sendPackets=true)
virtual void updateZoneWithParent (SceneObject *newParent, bool lightUpdate, bool sendPackets=true)
void broadcastMessage (BasePacket *message, bool sendSelf, bool lockZone=true)
void broadcastMessagePrivate (BasePacket *message, SceneObject *selfObject, bool lockZone)
void broadcastObject (SceneObject *object, bool sendSelf)
void broadcastObjectPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastDestroy (SceneObject *object, bool sendSelf)
void broadcastDestroyPrivate (SceneObject *object, SceneObject *selfObject)
void broadcastMessages (Vector< BasePacket * > *messages, bool sendSelf)
void broadcastMessagesPrivate (Vector< BasePacket * > *messages, SceneObject *selfObject)
virtual void sendMessage (BasePacket *msg)
int compareTo (SceneObject *obj)
void getSlottedObjects (VectorMap< String, ManagedReference< SceneObject * > > &objects)
void getContainerObjects (VectorMap< unsigned long long, ManagedReference< SceneObject * > > &objects)
unsigned long long getParentID ()
void addPendingTask (const String &name, Task *task, int miliseconds)
void removePendingTask (const String &name)
PendingTasksMap * getPendingTasks ()
Reference< Task * > getPendingTask (const String &name)
bool containsPendingTask (const String &name)
void showFlyText (const String &file, const String &uax, byte red, byte green, byte blue)
int getContainedObjectsRecursive ()
virtual int getCountableObjectsRecursive ()
Reference< Facade * > getActiveSession (unsigned int type)
void addActiveSession (unsigned int type, Facade *session)
bool containsActiveSession (unsigned int type)
bool dropActiveSession (unsigned int type)
int getActiveSessionsCount ()
VectorMap< unsigned int,
ManagedReference< Facade * > > * getObjectActiveSessions ()
virtual int handleObjectMenuSelect (CreatureObject *player, byte selectedID)
float getDistanceTo (SceneObject *object)
float getDistanceTo (Coordinate *coordinate)
void updateVehiclePosition (bool sendPackets)
virtual int notifyObjectInserted (SceneObject *object)
virtual int notifyObjectRemoved (SceneObject *object)
void addActiveArea (ActiveArea *area)
void dropActiveArea (ActiveArea *area)
bool hasActiveArea (ActiveArea *area)
bool hasActiveArea (unsigned long long objectid)
Vector< ManagedReference
< ActiveArea * > > * getActiveAreas ()
int getActiveAreasSize ()
Reference< ActiveArea * > getActiveRegion ()
virtual ManagedWeakReference
< CityRegion * > getCityRegion ()
void setCityRegion (CityRegion *region)
Zone * getZone ()
Zone * getLocalZone ()
unsigned long long getObjectID ()
Vector3 getCoordinate (float distance, float angleDegrees)
Vector3 getWorldCoordinate (float distance, float angleDegrees)
virtual float getWorldPositionX ()
virtual float getWorldPositionY ()
virtual float getWorldPositionZ ()
virtual Vector3 getWorldPosition ()
float getDirectionX ()
float getDirectionZ ()
float getDirectionY ()
float getDirectionW ()
Quaternion * getDirection ()
unsigned int getClientObjectCRC ()
unsigned int getServerObjectCRC ()
bool isWaypointObject ()
StringId * getObjectName ()
String getObjectNameStringIdFile ()
String getObjectNameStringIdName ()
virtual String getDetailedDescription ()
virtual void setDetailedDescription (const String &detail)
int getArrangementDescriptorSize ()
String getArrangementDescriptor (int idx)
String getSlotDescriptor (int idx)
bool hasSlotDescriptor (const String &descr)
bool hasArrangementDescriptor (const String &descr)
VectorMap< String,
ManagedReference< SceneObject * > > * getSlottedObjects ()
Reference< SceneObject * > getSlottedObject (const String &slot)
int getSlotDescriptorSize ()
Reference< SceneObject * > getSlottedObject (int idx)
Reference< SceneObject * > getContainerObjectRecursive (unsigned long long oid)
void dropSlottedObject (const String &arrengementDescriptor)
void removeSlottedObject (int index)
int getContainerObjectsSize ()
int getSlottedObjectsSize ()
bool hasFullContainerObjects ()
unsigned int getContainerVolumeLimit ()
Reference< SceneObject * > getContainerObject (int idx)
VectorMap< unsigned long long,
ManagedReference< SceneObject * > > * getContainerObjects ()
bool hasObjectInContainer (unsigned long long objectID)
bool hasObjectInSlottedContainer (SceneObject *object)
Reference< SceneObject * > getContainerObject (unsigned long long objectID)
void removeAllContainerObjects ()
void putInContainer (SceneObject *obj, unsigned long long key)
void removeFromContainerObjects (int index)
void setContainerVolumeLimit (int lim)
void setContainerType (int type)
unsigned int getContainerType ()
virtual ZoneClientSession * getClient ()
unsigned int getGameObjectType ()
unsigned int getClientGameObjectType ()
unsigned int getContainmentType ()
float getDirectionAngle ()
float getSpecialDirectionAngle ()
void rotate (int degrees)
void faceObject (SceneObject *obj)
virtual void notifySelfPositionUpdate ()
void notifyPositionUpdate (QuadTreeEntry *entry)
virtual void notifyCloseContainer (CreatureObject *player)
unsigned int getMovementCounter ()
ManagedWeakReference
< SceneObject * > getParent ()
void setParent (QuadTreeEntry *entry)
ZoneServer * getZoneServer ()
ManagedWeakReference
< SceneObject * > getRootParent ()
ManagedWeakReference
< SceneObject * > getParentRecursively (unsigned int gameObjectType)
bool isASubChildOf (SceneObject *object)
ReadWriteLock * getContainerLock ()
UnicodeString getCustomObjectName ()
String getLoggingName ()
virtual bool isPlayerCreature ()
bool isVendor ()
bool isGCWBase ()
bool isTurret ()
bool isMinefield ()
bool isDetector ()
bool isSecurityTerminal ()
bool isTurretControlTerminal ()
ZoneComponent * getZoneComponent ()
ObjectMenuComponent * getObjectMenuComponent ()
DataObjectComponentReference * getDataObjectComponent ()
bool isDecoration ()
void setObjectMenuComponent (const String &name)
void setContainerComponent (const String &name)
void setZoneComponent (const String &name)
bool isNoTrade ()
bool isContainerFull ()
bool isShuttleInstallation ()
bool isPlayerObject ()
virtual bool isActiveArea ()
virtual bool isRegion ()
virtual bool isCreatureObject ()
virtual bool isAiAgent ()
virtual bool isJunkDealer ()
virtual bool isShipObject ()
virtual bool isVehicleObject ()
virtual bool isBuildingObject ()
virtual bool isCloningBuildingObject ()
bool isGarage ()
virtual bool isWearableObject ()
virtual bool isWearableContainerObject ()
virtual bool isArmorObject ()
virtual bool isRobeObject ()
virtual bool isLightsaberCrystalObject ()
virtual bool isFireworkObject ()
bool isPsgArmorObject ()
virtual bool isCellObject ()
virtual bool isResourceContainer ()
virtual bool isResourceSpawn ()
virtual bool isComponent ()
virtual bool isIntangibleObject ()
bool isInstrument ()
bool isBazaarTerminal ()
bool isLiveSample ()
virtual bool isInstallationObject ()
virtual bool isHarvesterObject ()
virtual bool isGeneratorObject ()
virtual bool isCityTerminal ()
virtual bool isCityVoteTerminal ()
virtual bool isFactory ()
virtual bool isFactoryCrate ()
bool isFishingPoleObject ()
virtual bool isDeedObject ()
virtual bool isVehicleDeedObject ()
virtual bool isBuildingDeed ()
virtual bool isSignObject ()
virtual bool isInstallationDeed ()
virtual bool isCraftingTool ()
virtual bool isCraftingStation ()
virtual bool isManufactureSchematic ()
virtual bool isStructureObject ()
virtual bool isAuctionObject ()
bool isFishingBait ()
bool isTrapObject ()
bool isRepairTool ()
bool isCamoKit ()
virtual bool isAttachment ()
bool isDiceObject ()
bool isCreatureHabitat ()
bool isCampKit ()
virtual bool isCampStructure ()
virtual bool isRecycleToolObject ()
ContainerPermissions * getContainerPermissions ()
void setContainerDefaultAllowPermission (unsigned short perm)
void clearContainerDefaultAllowPermission (unsigned short perm)
void setContainerDefaultDenyPermission (unsigned short perm)
void clearContainerDefaultDenyPermission (unsigned short perm)
void setContainerInheritPermissionsFromParent (bool val)
void setContainerOwnerID (unsigned long long id)
void setContainerAllowPermission (const String &group, unsigned short perm)
void setContainerDenyPermission (const String &group, unsigned short perm)
void setGameObjectType (unsigned int type)
void setClientObjectCRC (unsigned int objCRC)
void setServerObjectCRC (unsigned int objCRC)
void setZoneProcessServer (ZoneProcessServer *srv)
ZoneProcessServer * getZoneProcessServer ()
void setZone (Zone *zone)
void setObjectName (StringId &stringID)
void setDirection (float fw, float fx, float fy, float fz)
void setDirection (float headingAngleRadians)
void setDirection (const Quaternion &dir)
void setMovementCounter (unsigned int count)
void incrementMovementCounter ()
void setContainmentType (unsigned int type)
void setLoggingName (const String &name)
void setClientObject (bool val)
virtual unsigned int getPlanetCRC ()
bool isStaticObject ()
virtual bool isContainerObject ()
virtual bool isTerminal ()
virtual bool isGroupObject ()
virtual bool isGuildObject ()
virtual bool isControlDevice ()
virtual bool isMissionTerminal ()
virtual bool isMissionObject ()
virtual bool isActorObject ()
int getPlanetMapCategoryCRC ()
int getPlanetMapSubCategoryCRC ()
void setPlanetMapCategory (PlanetMapCategory *pmc)
void setPlanetMapSubCategory (PlanetMapCategory *pmc)
PlanetMapCategory * getPlanetMapCategory ()
PlanetMapCategory * getPlanetMapSubCategory ()
SortedVector< ManagedReference
< SceneObject * > > * getChildObjects ()
bool containsChildObject (SceneObject *obj)
SharedObjectTemplate * getObjectTemplate ()
SortedVector< ManagedReference
< Observer * > > getObservers (unsigned int eventType)
Matrix4 * getTransformForCollisionMatrix ()
bool setTransformForCollisionMatrixIfNull (Matrix4 *mat)
virtual void initializeChildObject (SceneObject *controllerObject)
bool isInWater ()
String getDisplayedName ()
bool doSendToClient ()
void setSendToClient (bool val)
operator const SceneObject * ()
DistributedObjectStub * _getStub ()
Public Attributes
WeakReference< WeaponObject * > _this
Public Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
WeakReference< TangibleObject * > _this
Public Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
WeakReference< SceneObject * > _this
Static Public Attributes
static const int NONE = 0
static const int LIGHT = 1
static const int MEDIUM = 2
static const int HEAVY = 3
static const int KINETIC = 1
static const int ENERGY = 2
static const int BLAST = 4
static const int STUN = 8
static const int LIGHTSABER = 16
static const int HEAT = 32
static const int COLD = 64
static const int ACID = 128
static const int ELECTRICITY = 256
static const int FORCE = 512
static const int MELEEATTACK = 0
static const int RANGEDATTACK = 1
static const int FORCEATTACK = 2
static const int TRAPATTACK = 3
static const int GRENADEATTACK = 4
static const int HEAVYACIDBEAMATTACK = 14
static const int HEAVYLIGHTNINGBEAMATTACK = 15
static const int HEAVYPARTICLEBEAMATTACK = 17
static const int HEAVYROCKETLAUNCHERATTACK = 18
static const int HEAVYLAUNCHERATTACK = 19
Protected Member Functions
virtual ~WeaponObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::tangible::TangibleObjectImplementation
float getConditionReduction (float value)
virtual ~TangibleObjectImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Member Functions inherited from server::zone::objects::scene::SceneObjectImplementation
void close (SceneObject *client)
void link (SceneObject *client, unsigned int containmentType=4)
virtual ~SceneObjectImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
int attackType
String weaponEffect
int weaponEffectIndex
bool certified
int armorPiercing
int pointBlankAccuracy
int pointBlankRange
int idealRange
int idealAccuracy
int maxRange
int maxRangeAccuracy
int damageType
float attackSpeed
float minDamage
float maxDamage
float damageRadius
float woundsRatio
int healthAttackCost
int actionAttackCost
int mindAttackCost
int forceCost
int bladeColor
ManagedReference< PowerupObject * > powerupObject
float damageSlice
float speedSlice
Vector< int > dotType
Vector< int > dotAttribute
Vector< int > dotStrength
Vector< int > dotDuration
Vector< int > dotPotency
Vector< int > dotUses
Reference
< SharedWeaponObjectTemplate * > weaponTemplate
VectorMap< String, int > wearableSkillMods
Protected Attributes inherited from server::zone::objects::tangible::TangibleObjectImplementation
bool targetable
float complexity
int volume
unsigned int faction
CustomizationVariables customizationVariables
float conditionDamage
int maxCondition
int useCount
short level
unsigned int optionsBitmask
unsigned int pvpStatusBitmask
byte unknownByte
String craftersName
int junkDealerNeeded
int junkValue
String objectSerial
Reference< ThreatMap * > threatMap
DeltaVector< ManagedReference
< SceneObject * > > defenderList
bool sliceable
bool sliced
Protected Attributes inherited from server::zone::objects::scene::SceneObjectImplementation
ManagedReference
< ZoneProcessServer * > server
Reference< ZoneComponent * > zoneComponent
Reference< ObjectMenuComponent * > objectMenuComponent
Reference
< AttributeListComponent * > attributeListComponent
Reference< ContainerComponent * > containerComponent
Reference< SharedObjectTemplate * > templateObject
bool sendToClient
ZoneReference zone
DataObjectComponentReference dataObjectComponent
Reference< Matrix4 * > transformForCollisionMatrix
unsigned int containerType
unsigned int containerVolumeLimit
ContainerPermissions containerPermissions
unsigned int serverObjectCRC
unsigned int clientObjectCRC
Quaternion direction
unsigned int movementCounter
StringId objectName
Reference< PendingTasksMap * > pendingTasks
bool staticObject
VectorMap< unsigned int,
ManagedReference< Facade * > > objectActiveSessions
unsigned int gameObjectType
unsigned int containmentType
int planetMapCategory
int planetMapSubCategory
UnicodeString customName
ManagedWeakReference
< CityRegion * > cityRegion
SortedVector< ManagedReference
< ActiveArea * > > activeAreas
SortedVector< ManagedReference
< SceneObject * > > childObjects
VectorMap< String,
ManagedReference< SceneObject * > > slottedObjects
ReadWriteLock containerLock
Mutex parentLock
ContainerObjectsMap containerObjects
Friends
class WeaponObject
Detailed Description
Definition at line 427 of file WeaponObject.h.
Constructor & Destructor Documentation
WeaponObjectImplementation::WeaponObjectImplementation ()
Definition at line 1897 of file WeaponObject.cpp.
References _initializeImplementation(), actionAttackCost, armorPiercing, attackSpeed, certified, damageRadius, damageSlice, damageType, forceCost, healthAttackCost, idealAccuracy, idealRange, maxDamage, maxRange, maxRangeAccuracy, minDamage, mindAttackCost, pointBlankAccuracy, pointBlankRange, speedSlice, weaponTemplate, wearableSkillMods, and woundsRatio.
WeaponObjectImplementation::WeaponObjectImplementation (DummyConstructorParameter * param)
Definition at line 1399 of file WeaponObject.cpp.
References _initializeImplementation().
WeaponObjectImplementation::~WeaponObjectImplementation () protected virtual
Definition at line 1404 of file WeaponObject.cpp.
Member Function Documentation
DistributedObjectStub * WeaponObjectImplementation::_getStub ()
Definition at line 1424 of file WeaponObject.cpp.
References _this.
void WeaponObjectImplementation::_initializeImplementation () protected
Definition at line 1411 of file WeaponObject.cpp.
References _serializationHelperMethod(), and _this.
Referenced by WeaponObjectImplementation().
void WeaponObjectImplementation::_serializationHelperMethod () protected
Definition at line 1460 of file WeaponObject.cpp.
References server::zone::objects::tangible::TangibleObjectImplementation::_serializationHelperMethod().
Referenced by _initializeImplementation().
void WeaponObjectImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 1419 of file WeaponObject.cpp.
References server::zone::objects::tangible::TangibleObjectImplementation::_setStub(), and _this.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::WeaponObject().
void WeaponObjectImplementation::addDotAttribute (int a)
Definition at line 2142 of file WeaponObject.cpp.
References dotAttribute.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::addDotAttribute().
void WeaponObjectImplementation::addDotDuration (int du)
Definition at line 2152 of file WeaponObject.cpp.
References dotDuration.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::addDotDuration().
void WeaponObjectImplementation::addDotPotency (int po)
Definition at line 2157 of file WeaponObject.cpp.
References dotPotency.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::addDotPotency().
void WeaponObjectImplementation::addDotStrength (int s)
Definition at line 2147 of file WeaponObject.cpp.
References dotStrength.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::addDotStrength().
void WeaponObjectImplementation::addDotType (int t)
Definition at line 2137 of file WeaponObject.cpp.
References dotType.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::addDotType().
void WeaponObjectImplementation::addDotUses (int u)
Definition at line 2162 of file WeaponObject.cpp.
References dotUses.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::addDotUses().
void WeaponObjectImplementation::addSkillMod (const int skillType, const String & skillMod, int value, bool notifyClient = true) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 2325 of file WeaponObject.cpp.
References wearableSkillMods.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::addSkillMod().
void WeaponObjectImplementation::applyPowerup (CreatureObject * player, PowerupObject * pup)
Definition at line 2282 of file WeaponObject.cpp.
References server::zone::objects::scene::SceneObject::destroyObjectFromWorld(), server::zone::objects::scene::SceneObject::getParent(), hasPowerup(), powerupObject, and server::zone::objects::scene::SceneObjectImplementation::sendAttributeListTo().
Referenced by server::zone::objects::tangible::weapon::WeaponObject::applyPowerup().
void WeaponObjectImplementation::applySkillModsTo (CreatureObject * creature, bool doCheck = true) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 725 of file WeaponObjectImplementation.cpp.
References server::zone::objects::creature::CreatureObject::addSkillMod(), and wearableSkillMods.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::applySkillModsTo().
void WeaponObjectImplementation::createChildObjects () virtual
Handles creating the Saber inventory.
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 106 of file WeaponObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::childObjects, server::zone::ZoneServer::createObject(), ChildObject::getContainmentType(), server::zone::objects::scene::SceneObjectImplementation::getObjectID(), ChildObject::getTemplateFile(), server::zone::objects::scene::SceneObjectImplementation::server, server::zone::objects::scene::variables::ContainerPermissions::setDefaultDenyPermission(), server::zone::objects::scene::variables::ContainerPermissions::setDenyPermission(), server::zone::objects::scene::variables::ContainerPermissions::setInheritPermissionsFromParent(), server::zone::objects::scene::variables::ContainerPermissions::setOwner(), server::zone::objects::scene::SceneObjectImplementation::templateObject, and server::zone::objects::scene::SceneObjectImplementation::transferObject().
Referenced by server::zone::objects::tangible::weapon::WeaponObject::createChildObjects().
void WeaponObjectImplementation::decay (CreatureObject * user, float damage)
Definition at line 711 of file WeaponObjectImplementation.cpp.
References _this, server::zone::objects::tangible::TangibleObjectImplementation::conditionDamage, server::zone::objects::scene::SceneObject::getSlottedObject(), hasPowerup(), server::zone::objects::tangible::TangibleObjectImplementation::inflictDamage(), server::zone::objects::scene::SceneObject::isAiAgent(), server::zone::objects::tangible::TangibleObjectImplementation::isSliced(), server::zone::objects::tangible::TangibleObjectImplementation::maxCondition, and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::objects::tangible::weapon::WeaponObject::decay().
void WeaponObjectImplementation::decreasePowerupUses (CreatureObject * player)
Definition at line 670 of file WeaponObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::getDisplayedName(), hasPowerup(), powerupObject, server::zone::objects::scene::SceneObjectImplementation::sendAttributeListTo(), and server::zone::objects::creature::CreatureObject::sendSystemMessage().
Referenced by server::zone::objects::tangible::weapon::WeaponObject::decreasePowerupUses().
void WeaponObjectImplementation::fillAttributeList (AttributeListMessage * msg, CreatureObject * object) virtual
Fills the attribute list message options that are sent to player creature
Precondition
{ }
Postcondition
{ }
Parameters
msg attribute list message with the attributes
object player creature to which the message is sent
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 196 of file WeaponObjectImplementation.cpp.
References _this, ACID, armorPiercing, BLAST, COLD, damageType, ELECTRICITY, ENERGY, server::zone::objects::tangible::TangibleObjectImplementation::fillAttributeList(), getActionAttackCost(), getAttackSpeed(), getBladeColor(), getDamageRadius(), getDotAttribute(), getDotDuration(), getDotPotency(), getDotStrength(), getDotType(), getDotUses(), getForceCost(), getHealthAttackCost(), getIdealAccuracy(), getIdealRange(), getMaxDamage(), getMaxRange(), getMaxRangeAccuracy(), getMinDamage(), getMindAttackCost(), getNumberOfDots(), getPointBlankAccuracy(), getPointBlankRange(), getWoundsRatio(), hasPowerup(), HEAT, HEAVY, server::zone::packets::scene::AttributeListMessage::insertAttribute(), isCertifiedFor(), isJediWeapon(), KINETIC, LIGHT, LIGHTSABER, MEDIUM, NONE, powerupObject, server::zone::objects::tangible::TangibleObjectImplementation::sliced, STUN, and wearableSkillMods.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::fillAttributeList().
void WeaponObjectImplementation::finalize () protected
Definition at line 1408 of file WeaponObject.cpp.
int WeaponObjectImplementation::getActionAttackCost (bool withPup = true)
Definition at line 563 of file WeaponObjectImplementation.cpp.
References actionAttackCost, and powerupObject.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getActionAttackCost().
int WeaponObjectImplementation::getArmorPiercing ()
Definition at line 2022 of file WeaponObject.cpp.
References armorPiercing.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getArmorPiercing().
float WeaponObjectImplementation::getAttackSpeed (bool withPup = true)
Definition at line 487 of file WeaponObjectImplementation.cpp.
References attackSpeed, server::zone::objects::tangible::TangibleObjectImplementation::getConditionReduction(), powerupObject, server::zone::objects::tangible::TangibleObjectImplementation::sliced, and speedSlice.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getAttackSpeed().
int WeaponObjectImplementation::getAttackType ()
Definition at line 1987 of file WeaponObject.cpp.
References attackType.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getAttackType().
int WeaponObjectImplementation::getBladeColor ()
Definition at line 2082 of file WeaponObject.cpp.
References bladeColor.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getBladeColor().
Vector< String > * WeaponObjectImplementation::getCreatureAccuracyModifiers ()
Definition at line 1957 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getCreatureAccuracyModifiers().
Vector< String > * WeaponObjectImplementation::getCreatureAimModifiers ()
Definition at line 1962 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getCreatureAimModifiers().
Vector< String > * WeaponObjectImplementation::getDamageModifiers ()
Definition at line 1947 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getDamageModifiers().
float WeaponObjectImplementation::getDamageRadius (bool withPup = true)
Definition at line 546 of file WeaponObjectImplementation.cpp.
References damageRadius, and powerupObject.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getDamageRadius().
int WeaponObjectImplementation::getDamageType ()
Definition at line 2092 of file WeaponObject.cpp.
References damageType.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getDamageType().
Vector< String > * WeaponObjectImplementation::getDefenderDefenseModifiers ()
Definition at line 1967 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getDefenderDefenseModifiers().
Vector< String > * WeaponObjectImplementation::getDefenderSecondaryDefenseModifiers ()
Definition at line 1972 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getDefenderSecondaryDefenseModifiers().
Vector< String > * WeaponObjectImplementation::getDefenderToughnessModifiers ()
Definition at line 1977 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getDefenderToughnessModifiers().
int WeaponObjectImplementation::getDotAttribute (int index)
Definition at line 2112 of file WeaponObject.cpp.
References dotAttribute.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getDotAttribute().
int WeaponObjectImplementation::getDotDuration (int index)
Definition at line 2122 of file WeaponObject.cpp.
References dotDuration.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getDotDuration().
int WeaponObjectImplementation::getDotPotency (int index)
Definition at line 2127 of file WeaponObject.cpp.
References dotPotency.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getDotPotency().
int WeaponObjectImplementation::getDotStrength (int index)
Definition at line 2117 of file WeaponObject.cpp.
References dotStrength.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getDotStrength().
int WeaponObjectImplementation::getDotType (int index)
Definition at line 2107 of file WeaponObject.cpp.
References dotType.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getDotType().
int WeaponObjectImplementation::getDotUses (int index)
Definition at line 2132 of file WeaponObject.cpp.
References dotUses.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getDotUses().
int WeaponObjectImplementation::getForceCost ()
Definition at line 2072 of file WeaponObject.cpp.
References forceCost.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getForceCost().
int WeaponObjectImplementation::getHealthAttackCost (bool withPup = true)
Definition at line 555 of file WeaponObjectImplementation.cpp.
References healthAttackCost, and powerupObject.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getHealthAttackCost().
int WeaponObjectImplementation::getIdealAccuracy (bool withPup = true)
Definition at line 470 of file WeaponObjectImplementation.cpp.
References idealAccuracy, and powerupObject.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getIdealAccuracy().
int WeaponObjectImplementation::getIdealRange (bool withPup = true)
Definition at line 454 of file WeaponObjectImplementation.cpp.
References idealRange, and powerupObject.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getIdealRange().
float WeaponObjectImplementation::getMaxDamage (bool withPup = true)
Definition at line 508 of file WeaponObjectImplementation.cpp.
References damageSlice, server::zone::objects::tangible::TangibleObjectImplementation::getConditionReduction(), maxDamage, powerupObject, and server::zone::objects::tangible::TangibleObjectImplementation::sliced.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getMaxDamage().
int WeaponObjectImplementation::getMaxRange (bool withPup = true)
Definition at line 462 of file WeaponObjectImplementation.cpp.
References maxRange, and powerupObject.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getMaxRange().
int WeaponObjectImplementation::getMaxRangeAccuracy (bool withPup = true)
Definition at line 479 of file WeaponObjectImplementation.cpp.
References maxRangeAccuracy, and powerupObject.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getMaxRangeAccuracy().
float WeaponObjectImplementation::getMinDamage (bool withPup = true)
Definition at line 523 of file WeaponObjectImplementation.cpp.
References damageSlice, server::zone::objects::tangible::TangibleObjectImplementation::getConditionReduction(), minDamage, powerupObject, and server::zone::objects::tangible::TangibleObjectImplementation::sliced.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getMinDamage().
int WeaponObjectImplementation::getMindAttackCost (bool withPup = true)
Definition at line 571 of file WeaponObjectImplementation.cpp.
References mindAttackCost, and powerupObject.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getMindAttackCost().
int WeaponObjectImplementation::getNumberOfDots ()
Definition at line 2102 of file WeaponObject.cpp.
References dotType.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getNumberOfDots().
int WeaponObjectImplementation::getPointBlankAccuracy (bool withPup = true)
Definition at line 438 of file WeaponObjectImplementation.cpp.
References pointBlankAccuracy, and powerupObject.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getPointBlankAccuracy().
int WeaponObjectImplementation::getPointBlankRange (bool withPup = true)
Definition at line 446 of file WeaponObjectImplementation.cpp.
References pointBlankRange, and powerupObject.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getPointBlankRange().
Vector< String > * WeaponObjectImplementation::getSpeedModifiers ()
Definition at line 1952 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getSpeedModifiers().
String WeaponObjectImplementation::getWeaponType ()
Definition at line 148 of file WeaponObjectImplementation.cpp.
References SceneObjectType::CARBINE, server::zone::objects::scene::SceneObjectImplementation::getGameObjectType(), SceneObjectType::HEAVYWEAPON, isJediOneHandedWeapon(), isJediPolearmWeapon(), isJediTwoHandedWeapon(), SceneObjectType::MELEEWEAPON, SceneObjectType::MINE, SceneObjectType::ONEHANDMELEEWEAPON, SceneObjectType::PISTOL, SceneObjectType::POLEARM, SceneObjectType::RIFLE, SceneObjectType::SPECIALHEAVYWEAPON, SceneObjectType::THROWNWEAPON, SceneObjectType::TWOHANDMELEEWEAPON, and SceneObjectType::WEAPON.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getWeaponType().
VectorMap< String, int > * WeaponObjectImplementation::getWearableSkillMods ()
Definition at line 2330 of file WeaponObject.cpp.
References wearableSkillMods.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getWearableSkillMods().
float WeaponObjectImplementation::getWoundsRatio (bool withPup = true)
Definition at line 538 of file WeaponObjectImplementation.cpp.
References powerupObject, and woundsRatio.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::getWoundsRatio().
String WeaponObjectImplementation::getXpType ()
Definition at line 2097 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::getXpType().
bool WeaponObjectImplementation::hasPowerup ()
Definition at line 2277 of file WeaponObject.cpp.
References powerupObject.
Referenced by applyPowerup(), decay(), decreasePowerupUses(), fillAttributeList(), server::zone::objects::tangible::weapon::WeaponObject::hasPowerup(), and removePowerup().
void WeaponObjectImplementation::initializeTransientMembers ()
Definition at line 25 of file WeaponObjectImplementation.cpp.
References damageSlice, server::zone::objects::tangible::TangibleObjectImplementation::initializeTransientMembers(), server::zone::objects::scene::SceneObjectImplementation::serverObjectCRC, server::zone::objects::scene::SceneObjectImplementation::setLoggingName(), speedSlice, and weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::initializeTransientMembers(), and readObject().
bool WeaponObjectImplementation::isCarbineWeapon ()
Definition at line 2222 of file WeaponObject.cpp.
References SceneObjectType::CARBINE, and server::zone::objects::scene::SceneObjectImplementation::gameObjectType.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isCarbineWeapon().
bool WeaponObjectImplementation::isCertified ()
Definition at line 1997 of file WeaponObject.cpp.
References certified.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isCertified().
bool WeaponObjectImplementation::isCertifiedFor (CreatureObject * object)
Returns true if the player has the required certifications for this weapon
Precondition
{ }
Postcondition
{ }
Parameters
object player object to check against
Definition at line 651 of file WeaponObjectImplementation.cpp.
References weaponTemplate.
Referenced by fillAttributeList(), and server::zone::objects::tangible::weapon::WeaponObject::isCertifiedFor().
bool WeaponObjectImplementation::isFlameThrower ()
Definition at line 2212 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isFlameThrower().
bool WeaponObjectImplementation::isHeavyAcidRifle ()
Definition at line 2217 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isHeavyAcidRifle().
bool WeaponObjectImplementation::isHeavyWeapon ()
Definition at line 2197 of file WeaponObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::gameObjectType, and SceneObjectType::HEAVYWEAPON.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isHeavyWeapon().
bool WeaponObjectImplementation::isJediOneHandedWeapon ()
Definition at line 2257 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by getWeaponType(), server::zone::objects::tangible::weapon::WeaponObject::isJediOneHandedWeapon(), and isJediWeapon().
bool WeaponObjectImplementation::isJediPolearmWeapon ()
Definition at line 2267 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by getWeaponType(), server::zone::objects::tangible::weapon::WeaponObject::isJediPolearmWeapon(), and isJediWeapon().
bool WeaponObjectImplementation::isJediTwoHandedWeapon ()
Definition at line 2262 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by getWeaponType(), server::zone::objects::tangible::weapon::WeaponObject::isJediTwoHandedWeapon(), and isJediWeapon().
bool WeaponObjectImplementation::isJediWeapon ()
Definition at line 2252 of file WeaponObject.cpp.
References isJediOneHandedWeapon(), isJediPolearmWeapon(), and isJediTwoHandedWeapon().
Referenced by fillAttributeList(), server::zone::objects::tangible::weapon::WeaponObject::isJediWeapon(), sendContainerTo(), and updateCraftingValues().
bool WeaponObjectImplementation::isLightningRifle ()
Definition at line 2207 of file WeaponObject.cpp.
References weaponTemplate.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isLightningRifle().
bool WeaponObjectImplementation::isMeleeWeapon ()
Definition at line 2177 of file WeaponObject.cpp.
References attackType, and MELEEATTACK.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isMeleeWeapon().
bool WeaponObjectImplementation::isMineWeapon ()
Definition at line 2247 of file WeaponObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::gameObjectType, and SceneObjectType::MINE.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isMineWeapon().
bool WeaponObjectImplementation::isOneHandMeleeWeapon ()
Definition at line 2232 of file WeaponObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::gameObjectType, and SceneObjectType::ONEHANDMELEEWEAPON.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isOneHandMeleeWeapon().
bool WeaponObjectImplementation::isPistolWeapon ()
Definition at line 2227 of file WeaponObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::gameObjectType, and SceneObjectType::PISTOL.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isPistolWeapon().
bool WeaponObjectImplementation::isPolearmWeaponObject ()
Definition at line 2237 of file WeaponObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::gameObjectType, and SceneObjectType::POLEARM.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isPolearmWeaponObject().
bool WeaponObjectImplementation::isRangedWeapon ()
Definition at line 2182 of file WeaponObject.cpp.
References attackType, and RANGEDATTACK.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isRangedWeapon().
bool WeaponObjectImplementation::isRifleWeapon ()
Definition at line 2187 of file WeaponObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::gameObjectType, and SceneObjectType::RIFLE.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isRifleWeapon().
bool WeaponObjectImplementation::isSpecialHeavyWeapon ()
Definition at line 2202 of file WeaponObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::gameObjectType, and SceneObjectType::SPECIALHEAVYWEAPON.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isSpecialHeavyWeapon().
bool WeaponObjectImplementation::isThrownWeapon ()
Definition at line 2192 of file WeaponObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::gameObjectType, and SceneObjectType::THROWNWEAPON.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isThrownWeapon().
bool WeaponObjectImplementation::isTwoHandMeleeWeapon ()
Definition at line 2242 of file WeaponObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::gameObjectType, and SceneObjectType::TWOHANDMELEEWEAPON.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isTwoHandMeleeWeapon().
bool WeaponObjectImplementation::isUnarmedWeapon ()
Definition at line 2172 of file WeaponObject.cpp.
References server::zone::objects::scene::SceneObjectImplementation::gameObjectType, SceneObjectType::MELEEWEAPON, and SceneObjectType::WEAPON.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isUnarmedWeapon().
bool WeaponObjectImplementation::isWeaponObject () virtual
Reimplemented from server::zone::objects::scene::SceneObjectImplementation.
Definition at line 2272 of file WeaponObject.cpp.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::isWeaponObject().
void WeaponObjectImplementation::loadTemplateData (SharedObjectTemplate * templateData) virtual
Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
Precondition
{ templateData is a valid pointer }
Postcondition
{ TangibleObject members are initialized }
Parameters
templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 41 of file WeaponObjectImplementation.cpp.
References actionAttackCost, armorPiercing, attackSpeed, attackType, certified, damageRadius, damageType, forceCost, healthAttackCost, idealAccuracy, idealRange, server::zone::objects::tangible::TangibleObjectImplementation::loadTemplateData(), maxDamage, maxRange, maxRangeAccuracy, minDamage, mindAttackCost, pointBlankAccuracy, pointBlankRange, server::zone::objects::tangible::TangibleObjectImplementation::setSliceable(), weaponEffect, weaponEffectIndex, weaponTemplate, and woundsRatio.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::loadTemplateData().
void WeaponObjectImplementation::lock (bool doLock = true) protected
Definition at line 1432 of file WeaponObject.cpp.
References _this.
void WeaponObjectImplementation::lock (ManagedObject * obj) protected
Definition at line 1436 of file WeaponObject.cpp.
References _this.
WeaponObjectImplementation::operator const WeaponObject * ()
Definition at line 1428 of file WeaponObject.cpp.
void WeaponObjectImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 1467 of file WeaponObject.cpp.
References initializeTransientMembers(), and readObjectMember().
bool WeaponObjectImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 1486 of file WeaponObject.cpp.
References actionAttackCost, armorPiercing, attackSpeed, attackType, bladeColor, certified, damageRadius, damageSlice, damageType, dotAttribute, dotDuration, dotPotency, dotStrength, dotType, dotUses, forceCost, healthAttackCost, idealAccuracy, idealRange, maxDamage, maxRange, maxRangeAccuracy, minDamage, mindAttackCost, pointBlankAccuracy, pointBlankRange, powerupObject, server::zone::objects::tangible::TangibleObjectImplementation::readObjectMember(), speedSlice, weaponEffect, weaponEffectIndex, wearableSkillMods, and woundsRatio.
Referenced by readObject().
PowerupObject * WeaponObjectImplementation::removePowerup ()
Definition at line 2295 of file WeaponObject.cpp.
References hasPowerup(), and powerupObject.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::removePowerup().
void WeaponObjectImplementation::removeSkillModsFrom (CreatureObject * creature) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 741 of file WeaponObjectImplementation.cpp.
References server::zone::objects::creature::CreatureObject::removeSkillMod(), and wearableSkillMods.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::removeSkillModsFrom().
String WeaponObjectImplementation::repairAttempt (int repairChance) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 686 of file WeaponObjectImplementation.cpp.
References server::zone::objects::tangible::TangibleObjectImplementation::getMaxCondition(), server::zone::objects::tangible::TangibleObjectImplementation::setConditionDamage(), and server::zone::objects::tangible::TangibleObjectImplementation::setMaxCondition().
Referenced by server::zone::objects::tangible::weapon::WeaponObject::repairAttempt().
void WeaponObjectImplementation::rlock (bool doLock = true) protected
Definition at line 1440 of file WeaponObject.cpp.
References _this.
void WeaponObjectImplementation::runlock (bool doLock = true) protected
Definition at line 1456 of file WeaponObject.cpp.
References _this.
void WeaponObjectImplementation::sendBaselinesTo (SceneObject * player) virtual
Sends the TANO baseline messages of this object to the specified player
Precondition
{ this object is locked }
Postcondition
{ this object is locked, player received the baseline messages }
Parameters
player SceneObject that will receive the baselines
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 138 of file WeaponObjectImplementation.cpp.
References _this, server::zone::objects::scene::SceneObjectImplementation::info(), and server::zone::objects::scene::SceneObject::sendMessage().
Referenced by server::zone::objects::tangible::weapon::WeaponObject::sendBaselinesTo().
void WeaponObjectImplementation::sendContainerTo (CreatureObject * player)
Definition at line 89 of file WeaponObjectImplementation.cpp.
References server::zone::objects::scene::SceneObjectImplementation::getSlottedObject(), and isJediWeapon().
Referenced by server::zone::objects::tangible::weapon::WeaponObject::sendContainerTo().
void WeaponObjectImplementation::setActionAttackCost (int value)
Definition at line 2062 of file WeaponObject.cpp.
References actionAttackCost.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setActionAttackCost(), and updateCraftingValues().
void WeaponObjectImplementation::setAttackSpeed (float value)
Definition at line 2032 of file WeaponObject.cpp.
References attackSpeed.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setAttackSpeed(), and updateCraftingValues().
void WeaponObjectImplementation::setAttackType (int a)
Definition at line 1992 of file WeaponObject.cpp.
References attackType.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setAttackType().
void WeaponObjectImplementation::setBladeColor (int value)
Definition at line 2087 of file WeaponObject.cpp.
References bladeColor.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setBladeColor(), and updateCraftingValues().
void WeaponObjectImplementation::setCertified (bool cert)
Definition at line 1982 of file WeaponObject.cpp.
References certified.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setCertified().
void WeaponObjectImplementation::setDamageRadius (float value)
Definition at line 2052 of file WeaponObject.cpp.
References damageRadius.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setDamageRadius().
void WeaponObjectImplementation::setDamageSlice (float value)
Definition at line 2309 of file WeaponObject.cpp.
References damageSlice.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setDamageSlice().
void WeaponObjectImplementation::setDotUses (int u, int index)
Definition at line 2167 of file WeaponObject.cpp.
References dotUses.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setDotUses().
void WeaponObjectImplementation::setForceCost (int value)
Definition at line 2077 of file WeaponObject.cpp.
References forceCost.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setForceCost(), and updateCraftingValues().
void WeaponObjectImplementation::setHealthAttackCost (int value)
Definition at line 2057 of file WeaponObject.cpp.
References healthAttackCost.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setHealthAttackCost(), and updateCraftingValues().
void WeaponObjectImplementation::setIdealAccuracy (int value)
Definition at line 2017 of file WeaponObject.cpp.
References idealAccuracy.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setIdealAccuracy(), and updateCraftingValues().
void WeaponObjectImplementation::setIdealRange (int value)
Definition at line 2007 of file WeaponObject.cpp.
References idealRange.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setIdealRange(), and updateCraftingValues().
void WeaponObjectImplementation::setMaxDamage (float value)
Definition at line 2037 of file WeaponObject.cpp.
References maxDamage.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setMaxDamage(), and updateCraftingValues().
void WeaponObjectImplementation::setMaxRange (int value)
Definition at line 2012 of file WeaponObject.cpp.
References maxRange.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setMaxRange(), and updateCraftingValues().
void WeaponObjectImplementation::setMaxRangeAccuracy (int value)
Definition at line 2027 of file WeaponObject.cpp.
References maxRangeAccuracy.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setMaxRangeAccuracy(), and updateCraftingValues().
void WeaponObjectImplementation::setMinDamage (float value)
Definition at line 2042 of file WeaponObject.cpp.
References minDamage.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setMinDamage(), and updateCraftingValues().
void WeaponObjectImplementation::setMindAttackCost (int value)
Definition at line 2067 of file WeaponObject.cpp.
References mindAttackCost.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setMindAttackCost(), and updateCraftingValues().
void WeaponObjectImplementation::setPointBlankAccuracy (int value)
Definition at line 2002 of file WeaponObject.cpp.
References pointBlankAccuracy.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setPointBlankAccuracy(), and updateCraftingValues().
void WeaponObjectImplementation::setSpeedSlice (float value)
Definition at line 2317 of file WeaponObject.cpp.
References speedSlice.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setSpeedSlice().
void WeaponObjectImplementation::setWoundsRatio (float value)
Definition at line 2047 of file WeaponObject.cpp.
References woundsRatio.
Referenced by server::zone::objects::tangible::weapon::WeaponObject::setWoundsRatio(), and updateCraftingValues().
void WeaponObjectImplementation::unlock (bool doLock = true) protected
Definition at line 1452 of file WeaponObject.cpp.
References _this.
void WeaponObjectImplementation::updateCraftingValues (CraftingValues * values, bool firstUpdate) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 579 of file WeaponObjectImplementation.cpp.
References server::zone::objects::manufactureschematic::craftingvalues::CraftingValues::getCurrentValue(), isJediWeapon(), setActionAttackCost(), setAttackSpeed(), setBladeColor(), server::zone::objects::tangible::TangibleObjectImplementation::setConditionDamage(), setForceCost(), setHealthAttackCost(), setIdealAccuracy(), setIdealRange(), server::zone::objects::tangible::TangibleObjectImplementation::setMaxCondition(), setMaxDamage(), setMaxRange(), setMaxRangeAccuracy(), setMinDamage(), setMindAttackCost(), setPointBlankAccuracy(), and setWoundsRatio().
Referenced by server::zone::objects::tangible::weapon::WeaponObject::updateCraftingValues().
void WeaponObjectImplementation::wlock (bool doLock = true) protected
Definition at line 1444 of file WeaponObject.cpp.
References _this.
void WeaponObjectImplementation::wlock (ManagedObject * obj) protected
Definition at line 1448 of file WeaponObject.cpp.
References _this.
void WeaponObjectImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented from server::zone::objects::tangible::TangibleObjectImplementation.
Definition at line 1624 of file WeaponObject.cpp.
References writeObjectMembers().
int WeaponObjectImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 1631 of file WeaponObject.cpp.
References actionAttackCost, armorPiercing, attackSpeed, attackType, bladeColor, certified, damageRadius, damageSlice, damageType, dotAttribute, dotDuration, dotPotency, dotStrength, dotType, dotUses, forceCost, healthAttackCost, idealAccuracy, idealRange, maxDamage, maxRange, maxRangeAccuracy, minDamage, mindAttackCost, pointBlankAccuracy, pointBlankRange, powerupObject, speedSlice, weaponEffect, weaponEffectIndex, wearableSkillMods, woundsRatio, and server::zone::objects::tangible::TangibleObjectImplementation::writeObjectMembers().
Referenced by writeObject().
Friends And Related Function Documentation
friend class WeaponObject friend
Definition at line 800 of file WeaponObject.h.
Member Data Documentation
WeakReference<WeaponObject*> server::zone::objects::tangible::weapon::WeaponObjectImplementation::_this
Definition at line 766 of file WeaponObject.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), createChildObjects(), decay(), decreasePowerupUses(), fillAttributeList(), lock(), rlock(), runlock(), sendBaselinesTo(), unlock(), and wlock().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::ACID = 128 static
Definition at line 518 of file WeaponObject.h.
Referenced by fillAttributeList().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::actionAttackCost protected
Definition at line 465 of file WeaponObject.h.
Referenced by getActionAttackCost(), loadTemplateData(), readObjectMember(), setActionAttackCost(), WeaponObjectImplementation(), and writeObjectMembers().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::armorPiercing protected
Definition at line 437 of file WeaponObject.h.
Referenced by fillAttributeList(), getArmorPiercing(), loadTemplateData(), readObjectMember(), WeaponObjectImplementation(), and writeObjectMembers().
float server::zone::objects::tangible::weapon::WeaponObjectImplementation::attackSpeed protected
Definition at line 453 of file WeaponObject.h.
Referenced by getAttackSpeed(), loadTemplateData(), readObjectMember(), setAttackSpeed(), WeaponObjectImplementation(), and writeObjectMembers().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::attackType protected
Definition at line 429 of file WeaponObject.h.
Referenced by getAttackType(), isMeleeWeapon(), isRangedWeapon(), loadTemplateData(), readObjectMember(), setAttackType(), and writeObjectMembers().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::bladeColor protected
Definition at line 471 of file WeaponObject.h.
Referenced by getBladeColor(), readObjectMember(), setBladeColor(), and writeObjectMembers().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::BLAST = 4 static
Definition at line 508 of file WeaponObject.h.
Referenced by fillAttributeList().
bool server::zone::objects::tangible::weapon::WeaponObjectImplementation::certified protected
Definition at line 435 of file WeaponObject.h.
Referenced by isCertified(), loadTemplateData(), readObjectMember(), setCertified(), WeaponObjectImplementation(), and writeObjectMembers().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::COLD = 64 static
Definition at line 516 of file WeaponObject.h.
Referenced by fillAttributeList().
float server::zone::objects::tangible::weapon::WeaponObjectImplementation::damageRadius protected
Definition at line 459 of file WeaponObject.h.
Referenced by getDamageRadius(), loadTemplateData(), readObjectMember(), setDamageRadius(), WeaponObjectImplementation(), and writeObjectMembers().
float server::zone::objects::tangible::weapon::WeaponObjectImplementation::damageSlice protected
Definition at line 475 of file WeaponObject.h.
Referenced by getMaxDamage(), getMinDamage(), initializeTransientMembers(), readObjectMember(), setDamageSlice(), WeaponObjectImplementation(), and writeObjectMembers().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::damageType protected
Definition at line 451 of file WeaponObject.h.
Referenced by fillAttributeList(), getDamageType(), loadTemplateData(), readObjectMember(), WeaponObjectImplementation(), and writeObjectMembers().
Vector<int> server::zone::objects::tangible::weapon::WeaponObjectImplementation::dotAttribute protected
Definition at line 481 of file WeaponObject.h.
Referenced by addDotAttribute(), getDotAttribute(), readObjectMember(), and writeObjectMembers().
Vector<int> server::zone::objects::tangible::weapon::WeaponObjectImplementation::dotDuration protected
Definition at line 485 of file WeaponObject.h.
Referenced by addDotDuration(), getDotDuration(), readObjectMember(), and writeObjectMembers().
Vector<int> server::zone::objects::tangible::weapon::WeaponObjectImplementation::dotPotency protected
Definition at line 487 of file WeaponObject.h.
Referenced by addDotPotency(), getDotPotency(), readObjectMember(), and writeObjectMembers().
Vector<int> server::zone::objects::tangible::weapon::WeaponObjectImplementation::dotStrength protected
Definition at line 483 of file WeaponObject.h.
Referenced by addDotStrength(), getDotStrength(), readObjectMember(), and writeObjectMembers().
Vector<int> server::zone::objects::tangible::weapon::WeaponObjectImplementation::dotType protected
Definition at line 479 of file WeaponObject.h.
Referenced by addDotType(), getDotType(), getNumberOfDots(), readObjectMember(), and writeObjectMembers().
Vector<int> server::zone::objects::tangible::weapon::WeaponObjectImplementation::dotUses protected
Definition at line 489 of file WeaponObject.h.
Referenced by addDotUses(), getDotUses(), readObjectMember(), setDotUses(), and writeObjectMembers().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::ELECTRICITY = 256 static
Definition at line 520 of file WeaponObject.h.
Referenced by fillAttributeList().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::ENERGY = 2 static
Definition at line 506 of file WeaponObject.h.
Referenced by fillAttributeList().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::FORCE = 512 static
Definition at line 522 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::FORCEATTACK = 2 static
Definition at line 528 of file WeaponObject.h.
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::forceCost protected
Definition at line 469 of file WeaponObject.h.
Referenced by getForceCost(), loadTemplateData(), readObjectMember(), setForceCost(), WeaponObjectImplementation(), and writeObjectMembers().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::GRENADEATTACK = 4 static
Definition at line 532 of file WeaponObject.h.
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::healthAttackCost protected
Definition at line 463 of file WeaponObject.h.
Referenced by getHealthAttackCost(), loadTemplateData(), readObjectMember(), setHealthAttackCost(), WeaponObjectImplementation(), and writeObjectMembers().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::HEAT = 32 static
Definition at line 514 of file WeaponObject.h.
Referenced by fillAttributeList().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::HEAVY = 3 static
Definition at line 502 of file WeaponObject.h.
Referenced by fillAttributeList().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::HEAVYACIDBEAMATTACK = 14 static
Definition at line 534 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::HEAVYLAUNCHERATTACK = 19 static
Definition at line 542 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::HEAVYLIGHTNINGBEAMATTACK = 15 static
Definition at line 536 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::HEAVYPARTICLEBEAMATTACK = 17 static
Definition at line 538 of file WeaponObject.h.
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::HEAVYROCKETLAUNCHERATTACK = 18 static
Definition at line 540 of file WeaponObject.h.
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::idealAccuracy protected
Definition at line 445 of file WeaponObject.h.
Referenced by getIdealAccuracy(), loadTemplateData(), readObjectMember(), setIdealAccuracy(), WeaponObjectImplementation(), and writeObjectMembers().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::idealRange protected
Definition at line 443 of file WeaponObject.h.
Referenced by getIdealRange(), loadTemplateData(), readObjectMember(), setIdealRange(), WeaponObjectImplementation(), and writeObjectMembers().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::KINETIC = 1 static
Definition at line 504 of file WeaponObject.h.
Referenced by fillAttributeList().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::LIGHT = 1 static
Definition at line 498 of file WeaponObject.h.
Referenced by fillAttributeList().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::LIGHTSABER = 16 static
Definition at line 512 of file WeaponObject.h.
Referenced by fillAttributeList().
float server::zone::objects::tangible::weapon::WeaponObjectImplementation::maxDamage protected
Definition at line 457 of file WeaponObject.h.
Referenced by getMaxDamage(), loadTemplateData(), readObjectMember(), setMaxDamage(), WeaponObjectImplementation(), and writeObjectMembers().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::maxRange protected
Definition at line 447 of file WeaponObject.h.
Referenced by getMaxRange(), loadTemplateData(), readObjectMember(), setMaxRange(), WeaponObjectImplementation(), and writeObjectMembers().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::maxRangeAccuracy protected
Definition at line 449 of file WeaponObject.h.
Referenced by getMaxRangeAccuracy(), loadTemplateData(), readObjectMember(), setMaxRangeAccuracy(), WeaponObjectImplementation(), and writeObjectMembers().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::MEDIUM = 2 static
Definition at line 500 of file WeaponObject.h.
Referenced by fillAttributeList().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::MELEEATTACK = 0 static
Definition at line 524 of file WeaponObject.h.
Referenced by isMeleeWeapon().
float server::zone::objects::tangible::weapon::WeaponObjectImplementation::minDamage protected
Definition at line 455 of file WeaponObject.h.
Referenced by getMinDamage(), loadTemplateData(), readObjectMember(), setMinDamage(), WeaponObjectImplementation(), and writeObjectMembers().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::mindAttackCost protected
Definition at line 467 of file WeaponObject.h.
Referenced by getMindAttackCost(), loadTemplateData(), readObjectMember(), setMindAttackCost(), WeaponObjectImplementation(), and writeObjectMembers().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::NONE = 0 static
Definition at line 496 of file WeaponObject.h.
Referenced by fillAttributeList().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::pointBlankAccuracy protected
Definition at line 439 of file WeaponObject.h.
Referenced by getPointBlankAccuracy(), loadTemplateData(), readObjectMember(), setPointBlankAccuracy(), WeaponObjectImplementation(), and writeObjectMembers().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::pointBlankRange protected
Definition at line 441 of file WeaponObject.h.
Referenced by getPointBlankRange(), loadTemplateData(), readObjectMember(), WeaponObjectImplementation(), and writeObjectMembers().
ManagedReference<PowerupObject* > server::zone::objects::tangible::weapon::WeaponObjectImplementation::powerupObject protected
Definition at line 473 of file WeaponObject.h.
Referenced by applyPowerup(), decreasePowerupUses(), fillAttributeList(), getActionAttackCost(), getAttackSpeed(), getDamageRadius(), getHealthAttackCost(), getIdealAccuracy(), getIdealRange(), getMaxDamage(), getMaxRange(), getMaxRangeAccuracy(), getMinDamage(), getMindAttackCost(), getPointBlankAccuracy(), getPointBlankRange(), getWoundsRatio(), hasPowerup(), readObjectMember(), removePowerup(), and writeObjectMembers().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::RANGEDATTACK = 1 static
Definition at line 526 of file WeaponObject.h.
Referenced by isRangedWeapon().
float server::zone::objects::tangible::weapon::WeaponObjectImplementation::speedSlice protected
Definition at line 477 of file WeaponObject.h.
Referenced by getAttackSpeed(), initializeTransientMembers(), readObjectMember(), setSpeedSlice(), WeaponObjectImplementation(), and writeObjectMembers().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::STUN = 8 static
Definition at line 510 of file WeaponObject.h.
Referenced by fillAttributeList().
const int server::zone::objects::tangible::weapon::WeaponObjectImplementation::TRAPATTACK = 3 static
Definition at line 530 of file WeaponObject.h.
String server::zone::objects::tangible::weapon::WeaponObjectImplementation::weaponEffect protected
Definition at line 431 of file WeaponObject.h.
Referenced by loadTemplateData(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::tangible::weapon::WeaponObjectImplementation::weaponEffectIndex protected
Definition at line 433 of file WeaponObject.h.
Referenced by loadTemplateData(), readObjectMember(), and writeObjectMembers().
Reference<SharedWeaponObjectTemplate* > server::zone::objects::tangible::weapon::WeaponObjectImplementation::weaponTemplate protected
Definition at line 491 of file WeaponObject.h.
Referenced by getCreatureAccuracyModifiers(), getCreatureAimModifiers(), getDamageModifiers(), getDefenderDefenseModifiers(), getDefenderSecondaryDefenseModifiers(), getDefenderToughnessModifiers(), getSpeedModifiers(), getXpType(), initializeTransientMembers(), isCertifiedFor(), isFlameThrower(), isHeavyAcidRifle(), isJediOneHandedWeapon(), isJediPolearmWeapon(), isJediTwoHandedWeapon(), isLightningRifle(), loadTemplateData(), and WeaponObjectImplementation().
VectorMap<String, int> server::zone::objects::tangible::weapon::WeaponObjectImplementation::wearableSkillMods protected
Definition at line 493 of file WeaponObject.h.
Referenced by addSkillMod(), applySkillModsTo(), fillAttributeList(), getWearableSkillMods(), readObjectMember(), removeSkillModsFrom(), WeaponObjectImplementation(), and writeObjectMembers().
float server::zone::objects::tangible::weapon::WeaponObjectImplementation::woundsRatio protected
Definition at line 461 of file WeaponObject.h.
Referenced by getWoundsRatio(), loadTemplateData(), readObjectMember(), setWoundsRatio(), WeaponObjectImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/weapon/WeaponObject.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/weapon/WeaponObject.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/tangible/weapon/WeaponObjectImplementation.cpp