Core3: server::zone::managers::director::PersistentEvent Class Reference
server::zone::managers::director::PersistentEvent Class Reference
#include <PersistentEvent.h>
Public Member Functions
PersistentEvent ()
int getTimeStamp ()
const String getKey ()
const String getScreenplay ()
SceneObject * getObject ()
int getCurTime ()
void setCurTime (int time)
void setTimeStamp (int stamp)
void setKey (const String &k)
void setScreenplay (const String &sp)
void setObject (SceneObject *o)
void notifyLoadFromDatabase ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
PersistentEvent (DummyConstructorParameter *param)
virtual ~PersistentEvent ()
Friends
class PersistentEventHelper
Detailed Description
Definition at line 27 of file PersistentEvent.h.
Constructor & Destructor Documentation
PersistentEvent::PersistentEvent ()
Definition at line 13 of file PersistentEvent.cpp.
References server::zone::managers::director::PersistentEventImplementation::_setStub().
PersistentEvent::PersistentEvent (DummyConstructorParameter * param) protected
Definition at line 20 of file PersistentEvent.cpp.
PersistentEvent::~PersistentEvent () protected virtual
Definition at line 24 of file PersistentEvent.cpp.
Member Function Documentation
DistributedObjectServant * PersistentEvent::_getImplementation ()
Definition at line 181 of file PersistentEvent.cpp.
Referenced by getCurTime(), getKey(), getObject(), getScreenplay(), getTimeStamp(), notifyLoadFromDatabase(), setCurTime(), setKey(), setObject(), setScreenplay(), and setTimeStamp().
DistributedObjectServant * PersistentEvent::_getImplementationForRead ()
Definition at line 187 of file PersistentEvent.cpp.
void PersistentEvent::_setImplementation (DistributedObjectServant * servant)
Definition at line 191 of file PersistentEvent.cpp.
int PersistentEvent::getCurTime ()
Definition at line 85 of file PersistentEvent.cpp.
References _getImplementation(), server::zone::managers::director::PersistentEventImplementation::getCurTime(), and RPC_GETCURTIME__.
const String PersistentEvent::getKey ()
Definition at line 42 of file PersistentEvent.cpp.
References _getImplementation(), server::zone::managers::director::PersistentEventImplementation::getKey(), and RPC_GETKEY__.
SceneObject * PersistentEvent::getObject ()
Definition at line 72 of file PersistentEvent.cpp.
References _getImplementation(), server::zone::managers::director::PersistentEventImplementation::getObject(), and RPC_GETOBJECT__.
const String PersistentEvent::getScreenplay ()
Definition at line 57 of file PersistentEvent.cpp.
References _getImplementation(), server::zone::managers::director::PersistentEventImplementation::getScreenplay(), and RPC_GETSCREENPLAY__.
int PersistentEvent::getTimeStamp ()
Definition at line 29 of file PersistentEvent.cpp.
References _getImplementation(), server::zone::managers::director::PersistentEventImplementation::getTimeStamp(), and RPC_GETTIMESTAMP__.
void PersistentEvent::notifyLoadFromDatabase ()
Definition at line 168 of file PersistentEvent.cpp.
References _getImplementation(), server::zone::managers::director::PersistentEventImplementation::notifyLoadFromDatabase(), and RPC_NOTIFYLOADFROMDATABASE__.
void PersistentEvent::setCurTime (int time)
Definition at line 98 of file PersistentEvent.cpp.
References _getImplementation(), RPC_SETCURTIME__INT_, and server::zone::managers::director::PersistentEventImplementation::setCurTime().
void PersistentEvent::setKey (const String & k)
Definition at line 126 of file PersistentEvent.cpp.
References _getImplementation(), RPC_SETKEY__STRING_, and server::zone::managers::director::PersistentEventImplementation::setKey().
void PersistentEvent::setObject (SceneObject * o)
Definition at line 154 of file PersistentEvent.cpp.
References _getImplementation(), RPC_SETOBJECT__SCENEOBJECT_, and server::zone::managers::director::PersistentEventImplementation::setObject().
void PersistentEvent::setScreenplay (const String & sp)
Definition at line 140 of file PersistentEvent.cpp.
References _getImplementation(), RPC_SETSCREENPLAY__STRING_, and server::zone::managers::director::PersistentEventImplementation::setScreenplay().
void PersistentEvent::setTimeStamp (int stamp)
Definition at line 112 of file PersistentEvent.cpp.
References _getImplementation(), RPC_SETTIMESTAMP__INT_, and server::zone::managers::director::PersistentEventImplementation::setTimeStamp().
Friends And Related Function Documentation
friend class PersistentEventHelper friend
Definition at line 63 of file PersistentEvent.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/PersistentEvent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/director/PersistentEvent.cpp