Core3: EnumerateCharacterID Class Reference
EnumerateCharacterID Class Reference
#include <EnumerateCharacterId.h>
Public Member Functions
EnumerateCharacterID (Account *account)
Static Public Member Functions
static void parse (Packet *pack)
Detailed Description
Definition at line 52 of file EnumerateCharacterId.h.
Constructor & Destructor Documentation
EnumerateCharacterID::EnumerateCharacterID (Account * account) inline
Definition at line 54 of file EnumerateCharacterId.h.
References server::login::account::Account::getCharacterList(), CharacterListEntry::getFullName(), server::login::account::Account::getGalaxyBan(), CharacterListEntry::getGalaxyID(), CharacterListEntry::getObjectID(), CharacterListEntry::getRace(), and CharacterListEntry::isBanned().
Member Function Documentation
static void EnumerateCharacterID::parse (Packet * pack) inline static
Definition at line 79 of file EnumerateCharacterId.h.
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/login/packets/EnumerateCharacterId.h