Core3: TemplateManager Class Reference
TemplateManager Class Reference
#include <TemplateManager.h>
Public Types
enum TEMPLATE_ERROR_CODE {
NO_ERROR = 0, GENERAL_ERROR, NO_TRE_PATH, NO_TRE_FILES,
LOAD_TRES_ERROR, SLOT_DEFINITION_FILE_NOT_FOUND, ASSETCUSTOMIZATIONMANAGER_FILE_NOT_FOUND, CUSTOMIZATION_ID_MANAGER_FILE_NOT_FOUND,
PALLETE_COLUMNS_FILE_NOT_FOUND, HAIR_ASSETS_FILE_NOT_FOUND, PLANET_CAT_FILE_NOT_FOUND, LOAD_LUA_TEMPLATE_ERROR
}
Public Member Functions
TemplateManager ()
~TemplateManager ()
void registerTemplateObjects ()
void loadLuaTemplates ()
Reference< SlotDescriptor * > getSlotDescriptor (const String &filename)
Reference
< ArrangementDescriptor * > getArrangementDescriptor (const String &filename)
StructureFootprint * loadStructureFootprint (const String &filePath)
void addTemplate (uint32 key, const String &fullName, LuaObject *templateData)
String getTemplateFile (uint32 key)
SharedObjectTemplate * getTemplate (uint32 key)
IffStream * openIffFile (const String &fileName)
ObjectInputStream * openTreFile (const String &filePath)
bool containsTemplateType (uint32 type)
FloorMesh * getFloorMesh (const String &fileName)
PortalLayout * getPortalLayout (const String &fileName)
AppearanceTemplate * getAppearanceTemplate (const String &fileName)
AppearanceTemplate * instantiateAppearanceTemplate (IffStream *iffStream)
PaletteTemplate * getPaletteTemplate (const String &fileName)
bool existsTemplate (uint32 key)
void registerFunctions ()
void registerGlobals ()
PlanetMapCategory * getPlanetMapCategoryByName (const String &name)
PlanetMapCategory * getPlanetMapCategoryByCrc (int crc)
PlanetMapCategory * getPlanetMapCategoryById (int index)
StructureFootprint * getStructureFootprint (const String &filePath)
bool structureFootprintExists (const String &filePath)
SlotId * getSlotId (const String &slotName)
Static Public Member Functions
static int includeFile (lua_State *L)
static int crcString (lua_State *L)
static int addTemplateCRC (lua_State *L)
static int addClientTemplate (lua_State *L)
Static Public Attributes
static Lua * luaTemplatesInstance = NULL
static AtomicInteger loadedTemplatesCount
static int ERROR_CODE = NO_ERROR
Protected Member Functions
LuaObject * getLuaObject (const String &iffTemplateName)
Private Member Functions
void loadTreArchive ()
void loadSlotDefinitions ()
void loadPlanetMapCategories ()
void loadAssetCustomizationManager ()
Private Attributes
TemplateCRCMap * templateCRCMap
ObjectFactory
< SharedObjectTemplate
*(), uint32 > templateFactory
ClientTemplateCRCMap * clientTemplateCRCMap
PortalLayoutMap * portalLayoutMap
FloorMeshMap * floorMeshMap
AppearanceMap * appearanceMap
PlanetMapCategoryList planetMapCategoryList
VectorMap< String, Reference
< StructureFootprint * > > structureFootprints
VectorMap< String, Reference
< SlotId * > > slotDefinitions
VectorMap< String, Reference
< SlotDescriptor * > > slotDescriptors
VectorMap< String, Reference
< ArrangementDescriptor * > > arrangementDescriptors
ReadWriteLock appearanceMapLock
Friends
class server::zone::templates::SharedObjectTemplate
Detailed Description
Definition at line 38 of file TemplateManager.h.
Member Enumeration Documentation
enum TemplateManager::TEMPLATE_ERROR_CODE
Enumerator
NO_ERROR
GENERAL_ERROR
NO_TRE_PATH
NO_TRE_FILES
LOAD_TRES_ERROR
SLOT_DEFINITION_FILE_NOT_FOUND
ASSETCUSTOMIZATIONMANAGER_FILE_NOT_FOUND
CUSTOMIZATION_ID_MANAGER_FILE_NOT_FOUND
PALLETE_COLUMNS_FILE_NOT_FOUND
HAIR_ASSETS_FILE_NOT_FOUND
PLANET_CAT_FILE_NOT_FOUND
LOAD_LUA_TEMPLATE_ERROR
Definition at line 66 of file TemplateManager.h.
Constructor & Destructor Documentation
TemplateManager::TemplateManager ()
Definition at line 126 of file TemplateManager.cpp.
References appearanceMap, clientTemplateCRCMap, floorMeshMap, loadAssetCustomizationManager(), loadPlanetMapCategories(), loadSlotDefinitions(), loadTreArchive(), luaTemplatesInstance, portalLayoutMap, registerFunctions(), registerGlobals(), registerTemplateObjects(), and templateCRCMap.
TemplateManager::~TemplateManager ()
Definition at line 155 of file TemplateManager.cpp.
References appearanceMap, clientTemplateCRCMap, floorMeshMap, luaTemplatesInstance, portalLayoutMap, and templateCRCMap.
Member Function Documentation
int TemplateManager::addClientTemplate (lua_State * L) static
Definition at line 984 of file TemplateManager.cpp.
Referenced by registerFunctions().
void TemplateManager::addTemplate (uint32 key, const String & fullName, LuaObject * templateData)
Definition at line 448 of file TemplateManager.cpp.
References server::zone::templates::SharedObjectTemplate::addDerivedFile(), openIffFile(), server::zone::templates::SharedObjectTemplate::readObject(), server::zone::templates::SharedObjectTemplate::setFullTemplateString(), server::zone::templates::SharedObjectTemplate::setTemplateFileName(), templateCRCMap, and templateFactory.
int TemplateManager::addTemplateCRC (lua_State * L) static
Definition at line 961 of file TemplateManager.cpp.
References loadedTemplatesCount.
Referenced by registerFunctions().
bool TemplateManager::containsTemplateType (uint32 type) inline
Definition at line 110 of file TemplateManager.h.
References templateFactory.
int TemplateManager::crcString (lua_State * L) static
Definition at line 951 of file TemplateManager.cpp.
Referenced by registerFunctions().
bool TemplateManager::existsTemplate (uint32 key)
Definition at line 909 of file TemplateManager.cpp.
References templateCRCMap.
AppearanceTemplate * TemplateManager::getAppearanceTemplate (const String & fileName)
Definition at line 803 of file TemplateManager.cpp.
References appearanceMap, appearanceMapLock, instantiateAppearanceTemplate(), and openIffFile().
Referenced by instantiateAppearanceTemplate().
Reference< ArrangementDescriptor * > TemplateManager::getArrangementDescriptor (const String & filename)
Definition at line 333 of file TemplateManager.cpp.
References arrangementDescriptors, and openIffFile().
Referenced by server::zone::templates::SharedObjectTemplate::parseVariableData().
FloorMesh * TemplateManager::getFloorMesh (const String & fileName)
Definition at line 770 of file TemplateManager.cpp.
References floorMeshMap, openIffFile(), and FloorMesh::readObject().
LuaObject * TemplateManager::getLuaObject (const String & iffTemplateName) protected
Definition at line 924 of file TemplateManager.cpp.
References luaTemplatesInstance, and templateCRCMap.
PaletteTemplate * TemplateManager::getPaletteTemplate (const String & fileName)
Definition at line 308 of file TemplateManager.cpp.
References openTreFile(), and PaletteTemplate::readObject().
PlanetMapCategory* TemplateManager::getPlanetMapCategoryByCrc (int crc) inline
Definition at line 134 of file TemplateManager.h.
References PlanetMapCategoryList::get(), and planetMapCategoryList.
Referenced by server::zone::objects::scene::SceneObjectImplementation::getPlanetMapCategory(), and server::zone::objects::scene::SceneObjectImplementation::getPlanetMapSubCategory().
PlanetMapCategory* TemplateManager::getPlanetMapCategoryById (int index) inline
Definition at line 138 of file TemplateManager.h.
References planetMapCategoryList.
PlanetMapCategory* TemplateManager::getPlanetMapCategoryByName (const String & name) inline
Definition at line 130 of file TemplateManager.h.
References PlanetMapCategoryList::get(), and planetMapCategoryList.
Referenced by server::zone::templates::SharedObjectTemplate::parseVariableData().
PortalLayout * TemplateManager::getPortalLayout (const String & fileName)
Definition at line 872 of file TemplateManager.cpp.
References appearanceMapLock, openIffFile(), portalLayoutMap, and PortalLayout::readObject().
Reference< SlotDescriptor * > TemplateManager::getSlotDescriptor (const String & filename)
Attempts to get the slot descriptor. If the slot descriptor isn't loaded, attempt to load it.
Definition at line 289 of file TemplateManager.cpp.
References openIffFile(), and slotDescriptors.
Referenced by server::zone::templates::SharedObjectTemplate::parseVariableData().
SlotId* TemplateManager::getSlotId (const String & slotName) inline
Definition at line 166 of file TemplateManager.h.
References slotDefinitions.
StructureFootprint* TemplateManager::getStructureFootprint (const String & filePath) inline
This method should only be called after Templates have been loaded. It attempts to return the StructureFootprint that resides at the specified filepath, but requires that it has been loaded previously.
Parameters
filePath The TRE path of the desired Structure Footprint file.
Returns
Returns the StructureFootprint object, or NULL if it does not exist.
Definition at line 158 of file TemplateManager.h.
References structureFootprints.
SharedObjectTemplate * TemplateManager::getTemplate (uint32 key)
Definition at line 905 of file TemplateManager.cpp.
References templateCRCMap.
Referenced by server::zone::objects::player::sessions::PlaceStructureSessionImplementation::constructStructure(), server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), server::zone::objects::tangible::deed::structure::StructureDeedImplementation::fillAttributeList(), ImageDesignManager::getCustomizationData(), ImageDesignManager::loadCustomizationData(), server::zone::managers::object::ObjectManager::loadObjectFromTemplate(), StructureManager::placeStructure(), and StructureManager::placeStructureFromDeed().
String TemplateManager::getTemplateFile (uint32 key)
Definition at line 730 of file TemplateManager.cpp.
References clientTemplateCRCMap, server::zone::templates::SharedObjectTemplate::getFullTemplateString(), and templateCRCMap.
Referenced by server::zone::managers::player::creation::PlayerCreationManager::createCharacter(), and server::zone::managers::object::ObjectManager::createObject().
int TemplateManager::includeFile (lua_State * L) static
Definition at line 913 of file TemplateManager.cpp.
References ERROR_CODE, and LOAD_LUA_TEMPLATE_ERROR.
Referenced by registerFunctions().
AppearanceTemplate * TemplateManager::instantiateAppearanceTemplate (IffStream * iffStream)
Definition at line 830 of file TemplateManager.cpp.
References getAppearanceTemplate(), AppearanceRedirect::getRedirectFile(), AppearanceTemplate::readObject(), and AppearanceRedirect::readObject().
Referenced by getAppearanceTemplate().
void TemplateManager::loadAssetCustomizationManager () private
Definition at line 214 of file TemplateManager.cpp.
References ASSETCUSTOMIZATIONMANAGER_FILE_NOT_FOUND, CUSTOMIZATION_ID_MANAGER_FILE_NOT_FOUND, ERROR_CODE, HAIR_ASSETS_FILE_NOT_FOUND, openIffFile(), and PALLETE_COLUMNS_FILE_NOT_FOUND.
Referenced by TemplateManager().
void TemplateManager::loadLuaTemplates ()
Definition at line 378 of file TemplateManager.cpp.
References ERROR_CODE, floorMeshMap, LOAD_LUA_TEMPLATE_ERROR, luaTemplatesInstance, portalLayoutMap, and structureFootprints.
Referenced by server::zone::managers::object::ObjectManager::ObjectManager().
void TemplateManager::loadPlanetMapCategories () private
Definition at line 352 of file TemplateManager.cpp.
References ERROR_CODE, DataTableIff::getRow(), DataTableIff::getTotalRows(), openIffFile(), PLANET_CAT_FILE_NOT_FOUND, planetMapCategoryList, PlanetMapCategoryList::put(), and DataTableIff::readObject().
Referenced by TemplateManager().
void TemplateManager::loadSlotDefinitions () private
Definition at line 181 of file TemplateManager.cpp.
References ERROR_CODE, openIffFile(), SLOT_DEFINITION_FILE_NOT_FOUND, and slotDefinitions.
Referenced by TemplateManager().
StructureFootprint * TemplateManager::loadStructureFootprint (const String & filePath)
Attempts to load a Structure Footprint file from the TRE, and places it in the map. If the structure footprint already exists in the map, then it is simply returned. If the structure footprint cannot be found, then a warning is displayed, and NULL is returned
Parameters
filePath The TRE path to the Structure Footprint file from the root directory.
Returns
Returns NULL if not found, else returns the StructureFootprint.
Definition at line 993 of file TemplateManager.cpp.
References openIffFile(), and structureFootprints.
Referenced by SharedTangibleObjectTemplate::parseVariableData().
void TemplateManager::loadTreArchive () private
Definition at line 406 of file TemplateManager.cpp.
References ERROR_CODE, LOAD_TRES_ERROR, NO_TRE_FILES, and NO_TRE_PATH.
Referenced by TemplateManager().
IffStream * TemplateManager::openIffFile (const String & fileName)
Definition at line 766 of file TemplateManager.cpp.
Referenced by addTemplate(), ResourceTree::buildTreeFromClient(), getAppearanceTemplate(), getArrangementDescriptor(), getFloorMesh(), getPortalLayout(), getSlotDescriptor(), loadAssetCustomizationManager(), server::zone::managers::planet::PlanetManagerImplementation::loadClientRegions(), ImageDesignManager::loadCustomizationData(), loadPlanetMapCategories(), server::zone::managers::player::creation::PlayerCreationManager::loadProfessionDefaultsInfo(), server::zone::managers::player::creation::PlayerCreationManager::loadRacialCreationData(), SchematicMap::loadSchematicGroups(), loadSlotDefinitions(), server::zone::managers::planet::PlanetManagerImplementation::loadSnapshotObjects(), loadStructureFootprint(), and server::zone::managers::planet::PlanetManagerImplementation::loadTravelFares().
ObjectInputStream * TemplateManager::openTreFile (const String & filePath)
Definition at line 745 of file TemplateManager.cpp.
Referenced by getPaletteTemplate().
void TemplateManager::registerFunctions ()
Definition at line 569 of file TemplateManager.cpp.
References addClientTemplate(), addTemplateCRC(), crcString(), includeFile(), and luaTemplatesInstance.
Referenced by TemplateManager().
void TemplateManager::registerGlobals ()
Definition at line 577 of file TemplateManager.cpp.
References CreatureAttribute::ACTION, CreatureFlag::AGGRESSIVE, CombatManager::ARMS, CreatureFlag::ATTACKABLE, CreatureState::BLINDED, CreatureFlag::BLINK_GREEN, CreatureFlag::CHANGEFACTIONSTATUS, CombatManager::CHEST, ObserverEventType::CRAFTINGASSEMBLY, ObserverEventType::CRAFTINGEXPERIMENTATION, ObserverEventType::DAMAGERECEIVED, CreatureState::DISEASED, CreatureState::DIZZY, CreatureFlag::ENEMY, ObserverEventType::ENHANCINGPERFORMED, CreatureState::FROZEN, CombatManager::HEAD, ObserverEventType::HEALINGPERFORMED, CreatureAttribute::HEALTH, CreatureState::IMMOBILIZED, CreatureState::INTIMIDATED, CombatManager::LEGS, luaTemplatesInstance, ObserverEventType::MEDPACKUSED, CreatureAttribute::MIND, CombatManager::NOLOCATION, ObserverEventType::OBJECTDESTRUCTION, CreatureState::ONFIRE, CreatureFlag::OVERT, CreatureFlag::PLAYER, ObserverEventType::PLAYERCLONED, ObserverEventType::PLAYERKILLED, CreatureState::POISONED, ObserverEventType::SPICEDOWNERACTIVATED, CreatureState::STUNNED, CreatureFlag::TEF, ObserverEventType::WOUNDHEALINGPERFORMED, and ObserverEventType::XPAWARDED.
Referenced by TemplateManager().
void TemplateManager::registerTemplateObjects ()
Definition at line 489 of file TemplateManager.cpp.
References templateFactory.
Referenced by TemplateManager().
bool TemplateManager::structureFootprintExists (const String & filePath) inline
Definition at line 162 of file TemplateManager.h.
References structureFootprints.
Friends And Related Function Documentation
friend class server::zone::templates::SharedObjectTemplate friend
Definition at line 170 of file TemplateManager.h.
Member Data Documentation
AppearanceMap* TemplateManager::appearanceMap private
Definition at line 45 of file TemplateManager.h.
Referenced by getAppearanceTemplate(), TemplateManager(), and ~TemplateManager().
ReadWriteLock TemplateManager::appearanceMapLock private
Definition at line 55 of file TemplateManager.h.
Referenced by getAppearanceTemplate(), and getPortalLayout().
VectorMap<String, Reference<ArrangementDescriptor*> > TemplateManager::arrangementDescriptors private
Definition at line 53 of file TemplateManager.h.
Referenced by getArrangementDescriptor().
ClientTemplateCRCMap* TemplateManager::clientTemplateCRCMap private
Definition at line 42 of file TemplateManager.h.
Referenced by getTemplateFile(), TemplateManager(), and ~TemplateManager().
int TemplateManager::ERROR_CODE = NO_ERROR static
Definition at line 65 of file TemplateManager.h.
Referenced by includeFile(), loadAssetCustomizationManager(), loadLuaTemplates(), loadPlanetMapCategories(), loadSlotDefinitions(), loadTreArchive(), and TEST_F().
FloorMeshMap* TemplateManager::floorMeshMap private
Definition at line 44 of file TemplateManager.h.
Referenced by getFloorMesh(), loadLuaTemplates(), TemplateManager(), and ~TemplateManager().
AtomicInteger TemplateManager::loadedTemplatesCount static
Definition at line 64 of file TemplateManager.h.
Referenced by addTemplateCRC().
Lua * TemplateManager::luaTemplatesInstance = NULL static
Definition at line 63 of file TemplateManager.h.
Referenced by getLuaObject(), loadLuaTemplates(), registerFunctions(), registerGlobals(), TemplateManager(), and ~TemplateManager().
PlanetMapCategoryList TemplateManager::planetMapCategoryList private
Definition at line 47 of file TemplateManager.h.
Referenced by getPlanetMapCategoryByCrc(), getPlanetMapCategoryById(), getPlanetMapCategoryByName(), and loadPlanetMapCategories().
PortalLayoutMap* TemplateManager::portalLayoutMap private
Definition at line 43 of file TemplateManager.h.
Referenced by getPortalLayout(), loadLuaTemplates(), TemplateManager(), and ~TemplateManager().
VectorMap<String, Reference<SlotId*> > TemplateManager::slotDefinitions private
Definition at line 51 of file TemplateManager.h.
Referenced by getSlotId(), and loadSlotDefinitions().
VectorMap<String, Reference<SlotDescriptor*> > TemplateManager::slotDescriptors private
Definition at line 52 of file TemplateManager.h.
Referenced by getSlotDescriptor().
VectorMap<String, Reference<StructureFootprint*> > TemplateManager::structureFootprints private
Definition at line 49 of file TemplateManager.h.
Referenced by getStructureFootprint(), loadLuaTemplates(), loadStructureFootprint(), and structureFootprintExists().
TemplateCRCMap* TemplateManager::templateCRCMap private
Definition at line 39 of file TemplateManager.h.
Referenced by addTemplate(), existsTemplate(), getLuaObject(), getTemplate(), getTemplateFile(), TemplateManager(), and ~TemplateManager().
ObjectFactory<SharedObjectTemplate* (), uint32> TemplateManager::templateFactory private
Definition at line 41 of file TemplateManager.h.
Referenced by addTemplate(), containsTemplateType(), and registerTemplateObjects().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/templates/TemplateManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/templates/TemplateManager.cpp