Core3: server::zone::managers::creature::CreatureManager Class Reference
server::zone::managers::creature::CreatureManager Class Reference
#include <CreatureManager.h>
Public Member Functions
CreatureManager (Zone *planet)
void initialize ()
TangibleObject * spawnLair (unsigned int lairTemplate, int difficulty, float x, float z, float y, unsigned int faction)
CreatureObject * spawnCreatureWithAi (unsigned int templateCRC, float x, float z, float y, SceneObject *cell, bool persistent=false)
CreatureObject * spawnCreatureWithLevel (unsigned int mobileTemplateCRC, int level, float x, float z, float y, unsigned long long parentID=0)
CreatureObject * spawnCreature (unsigned int templateCRC, float x, float z, float y, unsigned long long parentID=0)
CreatureObject * spawnCreature (unsigned int templateCRC, unsigned int objectCRC, float x, float z, float y, unsigned long long parentID=0, bool persistent=false)
CreatureObject * createCreature (unsigned int templateCRC, bool persistent=false, unsigned int mobileTemplate=0)
void placeCreature (CreatureObject *creature, float x, float z, float y, unsigned long long parentID)
String getTemplateToSpawn (unsigned int templateCRC)
int notifyDestruction (TangibleObject *destructor, AiAgent *destructedObject, int condition)
void loadSpawnAreas ()
void loadAiTemplates ()
void loadSingleSpawns ()
void loadTrainers ()
void loadMissionSpawns ()
void loadInformants ()
void spawnRandomCreaturesAround (SceneObject *creature)
void spawnRandomCreature (int number, float x, float z, float y, unsigned long long parentID=0)
void harvest (Creature *creature, CreatureObject *player, int selectedID)
void milk (Creature *creature, CreatureObject *player)
void sample (Creature *creature, CreatureObject *player)
void addToReservePool (AiAgent *agent)
int getSpawnedRandomCreatures ()
Vector3 getRandomJediTrainer ()
Vector< ManagedReference
< SpawnArea * > > * getWorldSpawnAreas ()
Vector< ManagedReference
< SpawnArea * > > * getFactionalNeutralMissionSpawnAreas ()
Vector< ManagedReference
< SpawnArea * > > * getFactionalRebelMissionSpawnAreas ()
Vector< ManagedReference
< SpawnArea * > > * getFactionalImperialMissionSpawnAreas ()
Vector< ManagedReference
< SpawnArea * > > * getNonfactionalMissionSpawnAreas ()
SpawnArea * getSpawnArea (const String &areaname)
bool addWearableItem (CreatureObject *creature, TangibleObject *clothing)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Public Member Functions inherited from server::zone::manager::ZoneManager
ZoneManager (const String &name)
void setZoneProcessor (ZoneProcessServer *server)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const short NOTMILKED = 0x00
static const short BEINGMILKED = 0x01
static const short ALREADYMILKED = 0x02
static const short HASDNA = 0x00
static const short DNASAMPLED = 0x01
static const short DNADEATH = 0x03
Protected Member Functions
CreatureManager (DummyConstructorParameter *param)
virtual ~CreatureManager ()
Protected Member Functions inherited from server::zone::manager::ZoneManager
ZoneManager (DummyConstructorParameter *param)
virtual ~ZoneManager ()
Friends
class CreatureManagerHelper
Detailed Description
Definition at line 197 of file CreatureManager.h.
Constructor & Destructor Documentation
CreatureManager::CreatureManager (Zone * planet)
Definition at line 37 of file CreatureManager.cpp.
References server::zone::managers::creature::CreatureManagerImplementation::_setStub().
CreatureManager::CreatureManager (DummyConstructorParameter * param) protected
Definition at line 44 of file CreatureManager.cpp.
CreatureManager::~CreatureManager () protected virtual
Definition at line 48 of file CreatureManager.cpp.
Member Function Documentation
DistributedObjectServant * CreatureManager::_getImplementation ()
Definition at line 486 of file CreatureManager.cpp.
Referenced by addToReservePool(), addWearableItem(), createCreature(), getFactionalImperialMissionSpawnAreas(), getFactionalNeutralMissionSpawnAreas(), getFactionalRebelMissionSpawnAreas(), getNonfactionalMissionSpawnAreas(), getRandomJediTrainer(), getSpawnArea(), getSpawnedRandomCreatures(), getTemplateToSpawn(), getWorldSpawnAreas(), harvest(), initialize(), loadAiTemplates(), loadInformants(), loadMissionSpawns(), loadSingleSpawns(), loadSpawnAreas(), loadTrainers(), milk(), notifyDestruction(), placeCreature(), sample(), spawnCreature(), spawnCreatureWithAi(), spawnCreatureWithLevel(), spawnLair(), spawnRandomCreature(), and spawnRandomCreaturesAround().
DistributedObjectServant * CreatureManager::_getImplementationForRead ()
Definition at line 492 of file CreatureManager.cpp.
void CreatureManager::_setImplementation (DistributedObjectServant * servant)
Definition at line 496 of file CreatureManager.cpp.
void CreatureManager::addToReservePool (AiAgent * agent)
Definition at line 376 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::addToReservePool(), and RPC_ADDTORESERVEPOOL__AIAGENT_.
bool CreatureManager::addWearableItem (CreatureObject * creature, TangibleObject * clothing)
Definition at line 471 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::addWearableItem(), and RPC_ADDWEARABLEITEM__CREATUREOBJECT_TANGIBLEOBJECT_.
Referenced by GiveItemCommand::doQueueCommand().
CreatureObject * CreatureManager::createCreature (unsigned int templateCRC, bool persistent = false, unsigned int mobileTemplate = 0)
Definition at line 161 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::createCreature(), and RPC_CREATECREATURE__INT_BOOL_INT_.
Referenced by SpawnStateComponent::onEnter().
Vector< ManagedReference< SpawnArea * > > * CreatureManager::getFactionalImperialMissionSpawnAreas ()
Definition at line 439 of file CreatureManager.cpp.
References _getImplementation(), and server::zone::managers::creature::CreatureManagerImplementation::getFactionalImperialMissionSpawnAreas().
Referenced by server::zone::managers::mission::MissionManagerImplementation::getRandomLairSpawn().
Vector< ManagedReference< SpawnArea * > > * CreatureManager::getFactionalNeutralMissionSpawnAreas ()
Definition at line 421 of file CreatureManager.cpp.
References _getImplementation(), and server::zone::managers::creature::CreatureManagerImplementation::getFactionalNeutralMissionSpawnAreas().
Referenced by server::zone::managers::mission::MissionManagerImplementation::getRandomLairSpawn().
Vector< ManagedReference< SpawnArea * > > * CreatureManager::getFactionalRebelMissionSpawnAreas ()
Definition at line 430 of file CreatureManager.cpp.
References _getImplementation(), and server::zone::managers::creature::CreatureManagerImplementation::getFactionalRebelMissionSpawnAreas().
Referenced by server::zone::managers::mission::MissionManagerImplementation::getRandomLairSpawn().
Vector< ManagedReference< SpawnArea * > > * CreatureManager::getNonfactionalMissionSpawnAreas ()
Definition at line 448 of file CreatureManager.cpp.
References _getImplementation(), and server::zone::managers::creature::CreatureManagerImplementation::getNonfactionalMissionSpawnAreas().
Referenced by server::zone::managers::mission::MissionManagerImplementation::getRandomLairSpawn().
Vector3 CreatureManager::getRandomJediTrainer ()
Definition at line 403 of file CreatureManager.cpp.
References _getImplementation(), and server::zone::managers::creature::CreatureManagerImplementation::getRandomJediTrainer().
Referenced by ForceShrineMenuComponent::handleObjectMenuSelect().
SpawnArea * CreatureManager::getSpawnArea (const String & areaname)
Definition at line 457 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::getSpawnArea(), and RPC_GETSPAWNAREA__STRING_.
Referenced by server::zone::managers::director::DirectorManager::getRegion().
int CreatureManager::getSpawnedRandomCreatures ()
Definition at line 390 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::getSpawnedRandomCreatures(), and RPC_GETSPAWNEDRANDOMCREATURES__.
Referenced by server::zone::ZoneServerImplementation::getInfo(), and server::zone::ZoneServerImplementation::printInfo().
String CreatureManager::getTemplateToSpawn (unsigned int templateCRC)
Definition at line 195 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::getTemplateToSpawn(), and RPC_GETTEMPLATETOSPAWN__INT_.
Referenced by SpawnStateComponent::onEnter().
Vector< ManagedReference< SpawnArea * > > * CreatureManager::getWorldSpawnAreas ()
Definition at line 412 of file CreatureManager.cpp.
References _getImplementation(), and server::zone::managers::creature::CreatureManagerImplementation::getWorldSpawnAreas().
Referenced by server::zone::managers::mission::MissionManagerImplementation::getRandomLairSpawn().
void CreatureManager::harvest (Creature * creature, CreatureObject * player, int selectedID)
Definition at line 330 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::harvest(), and RPC_HARVEST__CREATURE_CREATUREOBJECT_INT_.
Referenced by HarvestCorpseCommand::doQueueCommand(), and server::zone::objects::creature::CreatureImplementation::handleObjectMenuSelect().
void CreatureManager::initialize ()
Definition at line 53 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::initialize(), and RPC_INITIALIZE__.
void CreatureManager::loadAiTemplates ()
Definition at line 233 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::loadAiTemplates(), and RPC_LOADAITEMPLATES__.
void CreatureManager::loadInformants ()
Definition at line 285 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::loadInformants(), and RPC_LOADINFORMANTS__.
void CreatureManager::loadMissionSpawns ()
Definition at line 272 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::loadMissionSpawns(), and RPC_LOADMISSIONSPAWNS__.
void CreatureManager::loadSingleSpawns ()
Definition at line 246 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::loadSingleSpawns(), and RPC_LOADSINGLESPAWNS__.
void CreatureManager::loadSpawnAreas ()
Definition at line 220 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::loadSpawnAreas(), and RPC_LOADSPAWNAREAS__.
void CreatureManager::loadTrainers ()
Definition at line 259 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::loadTrainers(), and RPC_LOADTRAINERS__.
void CreatureManager::milk (Creature * creature, CreatureObject * player)
Definition at line 346 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::milk(), and RPC_MILK__CREATURE_CREATUREOBJECT_.
Referenced by server::zone::objects::creature::CreatureImplementation::handleObjectMenuSelect().
int CreatureManager::notifyDestruction (TangibleObject * destructor, AiAgent * destructedObject, int condition)
Precondition
{ destructor and destructedObject locked }
Postcondition
{ destructor and destructedObject locked }
Definition at line 211 of file CreatureManager.cpp.
References _getImplementation(), and server::zone::managers::creature::CreatureManagerImplementation::notifyDestruction().
Referenced by server::zone::objects::creature::AiAgentImplementation::notifyObjectDestructionObservers().
void CreatureManager::placeCreature (CreatureObject * creature, float x, float z, float y, unsigned long long parentID)
Definition at line 177 of file CreatureManager.cpp.
References _getImplementation(), server::zone::managers::creature::CreatureManagerImplementation::placeCreature(), and RPC_PLACECREATURE__CREATUREOBJECT_FLOAT_FLOAT_FLOAT_LONG_.
Referenced by SpawnStateComponent::onEnter().
void CreatureManager::sample (Creature * creature, CreatureObject * player)
Gather a DNA sample from the given creature
Definition at line 361 of file CreatureManager.cpp.
References _getImplementation(), RPC_SAMPLE__CREATURE_CREATUREOBJECT_, and server::zone::managers::creature::CreatureManagerImplementation::sample().
CreatureObject * CreatureManager::spawnCreature (unsigned int templateCRC, float x, float z, float y, unsigned long long parentID = 0)
Definition at line 123 of file CreatureManager.cpp.
References _getImplementation(), RPC_SPAWNCREATURE__INT_FLOAT_FLOAT_FLOAT_LONG_, and server::zone::managers::creature::CreatureManagerImplementation::spawnCreature().
Referenced by server::zone::managers::mission::spawnmaps::NpcSpawnPoint::allocateNpc(), CreateCreatureCommand::doQueueCommand(), server::zone::objects::mission::bountyhunter::BountyHunterDroid::findTarget(), SpawnAreaMap::loadStaticSpawns(), RecruitSkillTrainerSuiCallback::run(), server::zone::objects::creature::aigroup::AiGroupImplementation::setup(), server::zone::objects::building::BuildingObjectImplementation::spawnChildCreature(), server::zone::objects::building::BuildingObjectImplementation::spawnChildCreaturesFromTemplate(), server::zone::managers::director::DirectorManager::spawnMobile(), server::zone::managers::director::DirectorManager::spawnMobileRandom(), and server::zone::objects::mission::BountyMissionObjectiveImplementation::spawnTarget().
CreatureObject * CreatureManager::spawnCreature (unsigned int templateCRC, unsigned int objectCRC, float x, float z, float y, unsigned long long parentID = 0, bool persistent = false)
Definition at line 141 of file CreatureManager.cpp.
References _getImplementation(), RPC_SPAWNCREATURE__INT_INT_FLOAT_FLOAT_FLOAT_LONG_BOOL_, and server::zone::managers::creature::CreatureManagerImplementation::spawnCreature().
CreatureObject * CreatureManager::spawnCreatureWithAi (unsigned int templateCRC, float x, float z, float y, SceneObject * cell, bool persistent = false)
Spawns the specified creature into zone
Precondition
{ this unlocked }
Postcondition
{ creature is in zone }
Parameters
templateCRC template string crc of the creature to spawn
x position x
y position y
parentID cell object id (optional)
Returns
returns creature object that has been spawned, NULL on error
Definition at line 85 of file CreatureManager.cpp.
References _getImplementation(), RPC_SPAWNCREATUREWITHAI__INT_FLOAT_FLOAT_FLOAT_SCENEOBJECT_BOOL_, and server::zone::managers::creature::CreatureManagerImplementation::spawnCreatureWithAi().
CreatureObject * CreatureManager::spawnCreatureWithLevel (unsigned int mobileTemplateCRC, int level, float x, float z, float y, unsigned long long parentID = 0)
Definition at line 104 of file CreatureManager.cpp.
References _getImplementation(), RPC_SPAWNCREATUREWITHLEVEL__INT_INT_FLOAT_FLOAT_FLOAT_LONG_, and server::zone::managers::creature::CreatureManagerImplementation::spawnCreatureWithLevel().
Referenced by server::zone::managers::creature::LairObserverImplementation::checkForNewSpawns().
TangibleObject * CreatureManager::spawnLair (unsigned int lairTemplate, int difficulty, float x, float z, float y, unsigned int faction)
Definition at line 66 of file CreatureManager.cpp.
References _getImplementation(), RPC_SPAWNLAIR__INT_INT_FLOAT_FLOAT_FLOAT_INT_, and server::zone::managers::creature::CreatureManagerImplementation::spawnLair().
Referenced by CreateSpawningElementCommand::doQueueCommand(), server::zone::objects::mission::DestroyMissionObjectiveImplementation::spawnLair(), and server::zone::objects::area::LairSpawnAreaImplementation::trySpawnLair().
void CreatureManager::spawnRandomCreature (int number, float x, float z, float y, unsigned long long parentID = 0)
Definition at line 312 of file CreatureManager.cpp.
References _getImplementation(), RPC_SPAWNRANDOMCREATURE__INT_FLOAT_FLOAT_FLOAT_LONG_, and server::zone::managers::creature::CreatureManagerImplementation::spawnRandomCreature().
void CreatureManager::spawnRandomCreaturesAround (SceneObject * creature)
Definition at line 298 of file CreatureManager.cpp.
References _getImplementation(), RPC_SPAWNRANDOMCREATURESAROUND__SCENEOBJECT_, and server::zone::managers::creature::CreatureManagerImplementation::spawnRandomCreaturesAround().
Friends And Related Function Documentation
friend class CreatureManagerHelper friend
Definition at line 300 of file CreatureManager.h.
Member Data Documentation
const short server::zone::managers::creature::CreatureManager::ALREADYMILKED = 0x02 static
Definition at line 203 of file CreatureManager.h.
const short server::zone::managers::creature::CreatureManager::BEINGMILKED = 0x01 static
Definition at line 201 of file CreatureManager.h.
const short server::zone::managers::creature::CreatureManager::DNADEATH = 0x03 static
Definition at line 209 of file CreatureManager.h.
const short server::zone::managers::creature::CreatureManager::DNASAMPLED = 0x01 static
Definition at line 207 of file CreatureManager.h.
const short server::zone::managers::creature::CreatureManager::HASDNA = 0x00 static
Definition at line 205 of file CreatureManager.h.
const short server::zone::managers::creature::CreatureManager::NOTMILKED = 0x00 static
Definition at line 199 of file CreatureManager.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/CreatureManager.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/creature/CreatureManager.cpp