Core3: server::zone::templates::mobile::ConversationScreen Class Reference
server::zone::templates::mobile::ConversationScreen Class Reference
#include <ConversationScreen.h>
Public Member Functions
ConversationScreen ()
ConversationScreen (const ConversationScreen &objectToCopy)
ConversationScreen * cloneScreen ()
void addOption (const String &optionText, const String &linkedScreenID)
void removeOption (int idx)
void removeAllOptions ()
ConversationOption * getOption (int idx)
String getOptionText (int idx) const
String getOptionLink (int idx) const
int getOptionCount ()
void sendTo (CreatureObject *player, CreatureObject *npc)
String & getScreenID ()
void readObject (LuaObject *luaObject)
template<class T >
void setDialogTextTT (const T &obj)
void setDialogTextTT (const String &file, const String &id)
template<class T >
void setDialogTextTO (const T &obj)
void setDialogTextTO (const String &file, const String &id)
template<class T >
void setDialogTextTU (const T &obj)
void setDialogTextTU (const String &file, const String &id)
void setDialogTextDI (uint32 val)
void setDialogTextDF (float val)
void setDialogText (const String &fullPath)
void setCustomDialogText (const UnicodeString &custom)
void setDialogText (const StringIdChatParameter &param)
void setStopConversation (bool stopConversation)
StringIdChatParameter * getDialogText ()
Private Attributes
String screenID
StringIdChatParameter dialogText
UnicodeString customText
Vector< Reference
< ConversationOption * > > options
bool stopConversation
bool readOnly
Detailed Description
Definition at line 106 of file ConversationScreen.h.
Constructor & Destructor Documentation
server::zone::templates::mobile::ConversationScreen::ConversationScreen () inline
Definition at line 119 of file ConversationScreen.h.
References readOnly, and stopConversation.
Referenced by cloneScreen().
server::zone::templates::mobile::ConversationScreen::ConversationScreen (const ConversationScreen & objectToCopy) inline
Copy constructor.
Definition at line 127 of file ConversationScreen.h.
References dialogText, options, readOnly, screenID, and stopConversation.
Member Function Documentation
void server::zone::templates::mobile::ConversationScreen::addOption (const String & optionText, const String & linkedScreenID) inline
Adds an option to this conversation screen.
Parameters
optionText The text to be displayed for the option.
linkedScreenID The ID of the screen this option is linked.
Definition at line 147 of file ConversationScreen.h.
References options, and readOnly.
Referenced by LuaConversationScreen::addOption(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainableSkillsScreenHandler::handleScreen(), and server::zone::objects::creature::conversation::screenhandlers::TrainerNextSkillsScreenHandler::handleScreen().
ConversationScreen* server::zone::templates::mobile::ConversationScreen::cloneScreen () inline
Definition at line 135 of file ConversationScreen.h.
References ConversationScreen(), and readOnly.
Referenced by LuaConversationScreen::cloneScreen(), and server::zone::objects::creature::conversation::ConversationObserverImplementation::runScreenHandlers().
StringIdChatParameter* server::zone::templates::mobile::ConversationScreen::getDialogText () inline
Definition at line 372 of file ConversationScreen.h.
References dialogText.
Referenced by server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughCreditsScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughSkillPointsScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerTrainedMasterScreenHandler::handleScreen(), LuaConversationScreen::setDialogTextTO(), LuaConversationScreen::setDialogTextTT(), and LuaConversationScreen::setDialogTextTU().
ConversationOption* server::zone::templates::mobile::ConversationScreen::getOption (int idx) inline
Definition at line 171 of file ConversationScreen.h.
References options.
int server::zone::templates::mobile::ConversationScreen::getOptionCount () inline
Definition at line 197 of file ConversationScreen.h.
References options.
Referenced by LuaConversationScreen::getOptionCount().
String server::zone::templates::mobile::ConversationScreen::getOptionLink (int idx) const inline
Definition at line 186 of file ConversationScreen.h.
References options.
Referenced by LuaConversationScreen::getOptionLink(), server::zone::objects::creature::conversation::screenhandlers::TrainerInfoScreenHandler::handleScreen(), and server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::handleScreen().
String server::zone::templates::mobile::ConversationScreen::getOptionText (int idx) const inline
Definition at line 175 of file ConversationScreen.h.
References options.
Referenced by LuaConversationScreen::getOptionText().
String& server::zone::templates::mobile::ConversationScreen::getScreenID () inline
Definition at line 243 of file ConversationScreen.h.
References screenID.
Referenced by LuaConversationScreen::getScreenID(), and server::zone::objects::creature::conversation::ConversationObserverImplementation::runScreenHandlers().
void server::zone::templates::mobile::ConversationScreen::readObject (LuaObject * luaObject) inline
Definition at line 247 of file ConversationScreen.h.
References customText, dialogText, options, readOnly, screenID, server::zone::objects::scene::variables::StringId::setStringId(), and stopConversation.
void server::zone::templates::mobile::ConversationScreen::removeAllOptions () inline
Definition at line 164 of file ConversationScreen.h.
References options, and readOnly.
Referenced by LuaConversationScreen::removeAllOptions().
void server::zone::templates::mobile::ConversationScreen::removeOption (int idx) inline
Definition at line 157 of file ConversationScreen.h.
References options, and readOnly.
Referenced by server::zone::objects::creature::conversation::screenhandlers::TrainerTrainableSkillsScreenHandler::handleScreen(), and server::zone::objects::creature::conversation::screenhandlers::TrainerNextSkillsScreenHandler::handleScreen().
void server::zone::templates::mobile::ConversationScreen::sendTo (CreatureObject * player, CreatureObject * npc) inline
Sends this ConversationScreen to the creature passed in.
Parameters
player The player receiving the message.
npc The npc the player is talking to.
Definition at line 206 of file ConversationScreen.h.
References SessionFacadeType::CONVERSATION, customText, dialogText, server::zone::objects::scene::SceneObject::getActiveSession(), server::zone::objects::scene::SceneObject::getObjectID(), StringList::insertOption(), options, server::zone::objects::creature::CreatureObject::sendMessage(), server::zone::objects::player::sessions::ConversationSession::setLastConversationScreen(), and stopConversation.
Referenced by server::zone::objects::creature::conversation::ConversationObserverImplementation::sendConversationScreenToPlayer(), and LuaConversationScreen::sendTo().
void server::zone::templates::mobile::ConversationScreen::setCustomDialogText (const UnicodeString & custom) inline
Definition at line 351 of file ConversationScreen.h.
References customText, and readOnly.
Referenced by LuaConversationScreen::setCustomDialogText().
void server::zone::templates::mobile::ConversationScreen::setDialogText (const String & fullPath) inline
Definition at line 344 of file ConversationScreen.h.
References dialogText, readOnly, and server::zone::objects::scene::variables::StringId::setStringId().
Referenced by server::zone::objects::creature::conversation::screenhandlers::InformantMissionScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerSkillInfoScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerCanLearnSkillScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::TrainerNotEnoughSkillPointsScreenHandler::handleScreen(), server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::performDeliverConversation(), server::zone::objects::creature::conversation::screenhandlers::DeliverMissionScreenHandler::performPickupConversation(), and LuaConversationScreen::setDialogTextStringId().
void server::zone::templates::mobile::ConversationScreen::setDialogText (const StringIdChatParameter & param) inline
Definition at line 358 of file ConversationScreen.h.
References dialogText, and readOnly.
void server::zone::templates::mobile::ConversationScreen::setDialogTextDF (float val) inline
Definition at line 337 of file ConversationScreen.h.
References dialogText, readOnly, and server::chat::StringIdChatParameter::setDF().
Referenced by LuaConversationScreen::setDialogTextDF().
void server::zone::templates::mobile::ConversationScreen::setDialogTextDI (uint32 val) inline
Definition at line 330 of file ConversationScreen.h.
References dialogText, readOnly, and server::chat::StringIdChatParameter::setDI().
Referenced by LuaConversationScreen::setDialogTextDI().
template<class T > void server::zone::templates::mobile::ConversationScreen::setDialogTextTO (const T & obj) inline
Definition at line 301 of file ConversationScreen.h.
References dialogText, readOnly, and server::chat::StringIdChatParameter::setTO().
void server::zone::templates::mobile::ConversationScreen::setDialogTextTO (const String & file, const String & id) inline
Definition at line 308 of file ConversationScreen.h.
References dialogText, readOnly, and server::chat::StringIdChatParameter::setTO().
template<class T > void server::zone::templates::mobile::ConversationScreen::setDialogTextTT (const T & obj) inline
Definition at line 286 of file ConversationScreen.h.
References dialogText, readOnly, and server::chat::StringIdChatParameter::setTT().
void server::zone::templates::mobile::ConversationScreen::setDialogTextTT (const String & file, const String & id) inline
Definition at line 293 of file ConversationScreen.h.
References dialogText, readOnly, and server::chat::StringIdChatParameter::setTT().
template<class T > void server::zone::templates::mobile::ConversationScreen::setDialogTextTU (const T & obj) inline
Definition at line 316 of file ConversationScreen.h.
References dialogText, readOnly, and server::chat::StringIdChatParameter::setTO().
void server::zone::templates::mobile::ConversationScreen::setDialogTextTU (const String & file, const String & id) inline
Definition at line 323 of file ConversationScreen.h.
References dialogText, readOnly, and server::chat::StringIdChatParameter::setTU().
void server::zone::templates::mobile::ConversationScreen::setStopConversation (bool stopConversation) inline
Definition at line 365 of file ConversationScreen.h.
References readOnly, and stopConversation.
Member Data Documentation
UnicodeString server::zone::templates::mobile::ConversationScreen::customText private
Definition at line 112 of file ConversationScreen.h.
Referenced by readObject(), sendTo(), and setCustomDialogText().
StringIdChatParameter server::zone::templates::mobile::ConversationScreen::dialogText private
Definition at line 110 of file ConversationScreen.h.
Referenced by ConversationScreen(), getDialogText(), readObject(), sendTo(), setDialogText(), setDialogTextDF(), setDialogTextDI(), setDialogTextTO(), setDialogTextTT(), and setDialogTextTU().
Vector<Reference<ConversationOption*> > server::zone::templates::mobile::ConversationScreen::options private
Definition at line 114 of file ConversationScreen.h.
Referenced by addOption(), ConversationScreen(), getOption(), getOptionCount(), getOptionLink(), getOptionText(), readObject(), removeAllOptions(), removeOption(), and sendTo().
bool server::zone::templates::mobile::ConversationScreen::readOnly private
Definition at line 116 of file ConversationScreen.h.
Referenced by addOption(), cloneScreen(), ConversationScreen(), readObject(), removeAllOptions(), removeOption(), setCustomDialogText(), setDialogText(), setDialogTextDF(), setDialogTextDI(), setDialogTextTO(), setDialogTextTT(), setDialogTextTU(), and setStopConversation().
String server::zone::templates::mobile::ConversationScreen::screenID private
Definition at line 107 of file ConversationScreen.h.
Referenced by ConversationScreen(), getScreenID(), and readObject().
bool server::zone::templates::mobile::ConversationScreen::stopConversation private
Definition at line 116 of file ConversationScreen.h.
Referenced by ConversationScreen(), readObject(), sendTo(), and setStopConversation().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/mobile/ConversationScreen.h