Core3: server::zone::objects::player::sessions::CitySpecializationSession Class Reference
server::zone::objects::player::sessions::CitySpecializationSession Class Reference
#include <CitySpecializationSession.h>
Public Member Functions
CitySpecializationSession (CreatureObject *creature, CityRegion *city, SceneObject *terminal=NULL)
int initializeSession ()
int sendConfirmationBox (const String &choice)
int acceptChoice ()
int cancelSession ()
int clearSession ()
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Protected Member Functions
CitySpecializationSession (DummyConstructorParameter *param)
virtual ~CitySpecializationSession ()
Friends
class CitySpecializationSessionHelper
Detailed Description
Definition at line 80 of file CitySpecializationSession.h.
Constructor & Destructor Documentation
CitySpecializationSession::CitySpecializationSession (CreatureObject * creature, CityRegion * city, SceneObject * terminal = NULL)
Definition at line 21 of file CitySpecializationSession.cpp.
References server::zone::objects::player::sessions::CitySpecializationSessionImplementation::_setStub().
CitySpecializationSession::CitySpecializationSession (DummyConstructorParameter * param) protected
Definition at line 28 of file CitySpecializationSession.cpp.
CitySpecializationSession::~CitySpecializationSession () protected virtual
Definition at line 32 of file CitySpecializationSession.cpp.
Member Function Documentation
DistributedObjectServant * CitySpecializationSession::_getImplementation ()
Definition at line 103 of file CitySpecializationSession.cpp.
Referenced by acceptChoice(), cancelSession(), clearSession(), initializeSession(), and sendConfirmationBox().
DistributedObjectServant * CitySpecializationSession::_getImplementationForRead ()
Definition at line 109 of file CitySpecializationSession.cpp.
void CitySpecializationSession::_setImplementation (DistributedObjectServant * servant)
Definition at line 113 of file CitySpecializationSession.cpp.
int CitySpecializationSession::acceptChoice ()
Definition at line 64 of file CitySpecializationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::acceptChoice(), and RPC_ACCEPTCHOICE__.
int CitySpecializationSession::cancelSession ()
Definition at line 77 of file CitySpecializationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::cancelSession(), and RPC_CANCELSESSION__.
Referenced by CitySpecializationConfirmSuiCallback::run(), and CitySpecializationSuiCallback::run().
int CitySpecializationSession::clearSession ()
Definition at line 90 of file CitySpecializationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::clearSession(), and RPC_CLEARSESSION__.
int CitySpecializationSession::initializeSession ()
Definition at line 37 of file CitySpecializationSession.cpp.
References _getImplementation(), server::zone::objects::player::sessions::CitySpecializationSessionImplementation::initializeSession(), and RPC_INITIALIZESESSION__.
int CitySpecializationSession::sendConfirmationBox (const String & choice)
Definition at line 50 of file CitySpecializationSession.cpp.
References _getImplementation(), RPC_SENDCONFIRMATIONBOX__STRING_, and server::zone::objects::player::sessions::CitySpecializationSessionImplementation::sendConfirmationBox().
Friends And Related Function Documentation
friend class CitySpecializationSessionHelper friend
Definition at line 104 of file CitySpecializationSession.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CitySpecializationSession.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sessions/CitySpecializationSession.cpp