Core3: server::zone::objects::region::CityRegion Class Reference
server::zone::objects::region::CityRegion Class Reference
#include <CityRegion.h>
Public Member Functions
CityRegion ()
void initialize ()
void initializeTransientMembers ()
void notifyLoadFromDatabase ()
void notifyEnter (SceneObject *object)
void notifyExit (SceneObject *object)
Region * addRegion (float x, float y, float radius, bool persistent)
void rescheduleUpdateEvent (unsigned int seconds)
void destroyActiveAreas ()
void addMilitiaMember (unsigned long long objectid)
void removeMilitiaMember (unsigned long long objectid)
bool isMilitiaMember (unsigned long long objectid)
void addZoningRights (unsigned long long objectid, unsigned int duration=86400)
void removeZoningRights (unsigned long long objectid)
bool hasZoningRights (unsigned long long objectid)
bool containsPoint (float x, float y)
void cleanupCitizens ()
Time * getNextUpdateTime ()
int getCurrentPlayerCount ()
void addCitizen (unsigned long long citizenID)
void removeCitizen (unsigned long long citizenID)
void addBannedPlayer (unsigned long long playerid)
void removeBannedPlayer (unsigned long long playerid)
bool isCitizen (unsigned long long citizenID)
int getTimeToUpdate ()
int getCitizenCount ()
byte getCityRank ()
bool isBanned (unsigned long long playerID)
CitizenList * getCitizenList ()
CitizenList * getMilitiaMembers ()
CitizenList * getBannedPlayers ()
bool isRegistered ()
Zone * getZone ()
String getRegionName ()
unsigned long long getMayorID ()
float getPositionX ()
float getPositionY ()
float getRadius ()
Region * getRegion (int idx)
int getRegionsCount ()
int getStructuresCount ()
int getCommercialStructuresCount ()
int getAllStructuresCount ()
String getCitySpecialization ()
float getCityTreasury ()
bool isMayor (unsigned long long objectid)
bool isZoningEnabled ()
bool isClientRegion ()
StructureObject * getCityHall ()
void setZone (Zone *zne)
void setCustomRegionName (const String &name)
void setCitySpecialization (const String &spec)
void setRegionName (const String &fullPath)
void setCityTreasury (float val)
float addToCityTreasury (float val)
float subtractFromCityTreasury (float val)
int getMaxWithdrawal ()
Vector< ManagedReference
< TangibleObject * > > * getVendorsInCity ()
void setRegionName (const StringId &name)
void setCityRank (byte rank)
void setMayorID (unsigned long long id)
void setRegistered (bool val)
void setZoningEnabled (bool val)
void setRadius (float rad)
void setCityHall (StructureObject *building)
void removeShuttleInstallation ()
bool hasShuttleInstallation ()
void setShuttleID (unsigned long long id)
int getMissionTerminalCount ()
int getDecorationCount ()
int getSkillTrainerCount ()
void addMissionTerminal (SceneObject *mt)
void addDecoration (SceneObject *deco)
void addSkillTrainer (SceneObject *trainer)
void removeMissionTerminal (SceneObject *mt)
void removeDecoration (SceneObject *deco)
void removeSkillTrainers (SceneObject *trainer)
void addBazaar (TangibleObject *ter)
TangibleObject * getBazaar (int idx)
int getBazaarCount ()
void removeAllSkillTrainers ()
void removeAllTerminals ()
void removeAllDecorations ()
void updateMilitia ()
void addStructure (StructureObject *structure)
void addCommercialStructure (StructureObject *structure)
void removeStructure (StructureObject *structure)
void removeCommercialStructure (StructureObject *structure)
bool hasUniqueStructure (unsigned int crc)
void destroyAllStructuresForRank (byte rank)
void addCandidate (unsigned long long candidateoid)
void setMayoralVote (unsigned long long voteroid, unsigned long long candidateoid)
int getCandidateVotes (unsigned long long candidateoid)
VectorMap< unsigned long long,
int > * getCandidates ()
VectorMap< unsigned long long,
unsigned long long > * getMayoralVotes ()
void resetCandidates ()
void resetMayoralVotes ()
void removeCandidate (unsigned long long candidateoid)
bool isCandidate (unsigned long long candidateoid)
bool isVotingPeriodOver ()
bool isVotingPeriod ()
bool isVotingLocked ()
void resetVotingPeriod ()
bool isLoaded ()
void setLoaded ()
void applySpecializationModifiers (CreatureObject *creature)
void removeSpecializationModifiers (CreatureObject *creature)
int getPropertyTax ()
int getIncomeTax ()
int getSalesTax ()
int getTravelTax ()
int getGarageTax ()
int getTax (int tax)
void setTax (int tax, int value)
StructureObject * getCivicStructure (int indx)
StructureObject * getCommercialStructure (int indx)
SceneObject * getCityDecoration (int indx)
SceneObject * getCityMissionTerminal (int indx)
SceneObject * getCitySkillTrainer (int indx)
void transferCivicStructuresToMayor ()
void cleanupDuplicateCityStructures ()
void removeDecorationsOutsideCity (int newRadius)
void removeTrainersOutsideCity (int newRadius)
void removeTerminalsOutsideCity (int newRadius)
void removeStructuresOutsideCity (int newRadius)
bool isInsideRadius (SceneObject *obj, int radiusToUse)
void removeAmenitiesOutsideCity (int newRadius)
void cleanupDecorations (int decorationLimit)
DistributedObjectServant * _getImplementation ()
DistributedObjectServant * _getImplementationForRead ()
void _setImplementation (DistributedObjectServant *servant)
Static Public Attributes
static const byte RANK_CLIENT = 0
static const byte RANK_OUTPOST = 1
static const byte RANK_VILLAGE = 2
static const byte RANK_TOWNSHIP = 3
static const byte RANK_CITY = 4
static const byte RANK_METROPOLIS = 5
static const byte TAX_PROPERTY = 0
static const byte TAX_INCOME = 1
static const byte TAX_SALES = 2
static const byte TAX_TRAVEL = 3
static const byte TAX_GARAGE = 4
Protected Member Functions
CityRegion (DummyConstructorParameter *param)
virtual ~CityRegion ()
Friends
class CityRegionHelper
Detailed Description
Definition at line 133 of file CityRegion.h.
Constructor & Destructor Documentation
CityRegion::CityRegion ()
Definition at line 27 of file CityRegion.cpp.
References server::zone::objects::region::CityRegionImplementation::_setStub().
CityRegion::CityRegion (DummyConstructorParameter * param) protected
Definition at line 34 of file CityRegion.cpp.
CityRegion::~CityRegion () protected virtual
Definition at line 38 of file CityRegion.cpp.
Member Function Documentation
DistributedObjectServant * CityRegion::_getImplementation ()
Definition at line 1717 of file CityRegion.cpp.
Referenced by addBannedPlayer(), addBazaar(), addCandidate(), addCitizen(), addCommercialStructure(), addDecoration(), addMilitiaMember(), addMissionTerminal(), addRegion(), addSkillTrainer(), addStructure(), addToCityTreasury(), addZoningRights(), applySpecializationModifiers(), cleanupCitizens(), cleanupDecorations(), cleanupDuplicateCityStructures(), containsPoint(), destroyActiveAreas(), destroyAllStructuresForRank(), getAllStructuresCount(), getBannedPlayers(), getBazaar(), getBazaarCount(), getCandidates(), getCandidateVotes(), getCitizenCount(), getCitizenList(), getCityDecoration(), getCityHall(), getCityMissionTerminal(), getCityRank(), getCitySkillTrainer(), getCitySpecialization(), getCityTreasury(), getCivicStructure(), getCommercialStructure(), getCommercialStructuresCount(), getCurrentPlayerCount(), getDecorationCount(), getGarageTax(), getIncomeTax(), getMaxWithdrawal(), getMayoralVotes(), getMayorID(), getMilitiaMembers(), getMissionTerminalCount(), getNextUpdateTime(), getPositionX(), getPositionY(), getPropertyTax(), getRadius(), getRegion(), getRegionName(), getRegionsCount(), getSalesTax(), getSkillTrainerCount(), getStructuresCount(), getTax(), getTimeToUpdate(), getTravelTax(), getVendorsInCity(), getZone(), hasShuttleInstallation(), hasUniqueStructure(), hasZoningRights(), initialize(), initializeTransientMembers(), isBanned(), isCandidate(), isCitizen(), isClientRegion(), isInsideRadius(), isLoaded(), isMayor(), isMilitiaMember(), isRegistered(), isVotingLocked(), isVotingPeriod(), isVotingPeriodOver(), isZoningEnabled(), notifyEnter(), notifyExit(), notifyLoadFromDatabase(), removeAllDecorations(), removeAllSkillTrainers(), removeAllTerminals(), removeAmenitiesOutsideCity(), removeBannedPlayer(), removeCandidate(), removeCitizen(), removeCommercialStructure(), removeDecoration(), removeDecorationsOutsideCity(), removeMilitiaMember(), removeMissionTerminal(), removeShuttleInstallation(), removeSkillTrainers(), removeSpecializationModifiers(), removeStructure(), removeStructuresOutsideCity(), removeTerminalsOutsideCity(), removeTrainersOutsideCity(), removeZoningRights(), rescheduleUpdateEvent(), resetCandidates(), resetMayoralVotes(), resetVotingPeriod(), setCityHall(), setCityRank(), setCitySpecialization(), setCityTreasury(), setCustomRegionName(), setLoaded(), setMayoralVote(), setMayorID(), setRadius(), setRegionName(), setRegistered(), setShuttleID(), setTax(), setZone(), setZoningEnabled(), subtractFromCityTreasury(), transferCivicStructuresToMayor(), and updateMilitia().
DistributedObjectServant * CityRegion::_getImplementationForRead ()
Definition at line 1723 of file CityRegion.cpp.
void CityRegion::_setImplementation (DistributedObjectServant * servant)
Definition at line 1727 of file CityRegion.cpp.
void CityRegion::addBannedPlayer (unsigned long long playerid)
Definition at line 317 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addBannedPlayer(), and RPC_ADDBANNEDPLAYER__LONG_.
void CityRegion::addBazaar (TangibleObject * ter)
Definition at line 1055 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addBazaar(), and RPC_ADDBAZAAR__TANGIBLEOBJECT_.
void CityRegion::addCandidate (unsigned long long candidateoid)
Adds a candidate to the ballot.
Definition at line 1232 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addCandidate(), and RPC_ADDCANDIDATE__LONG_.
Referenced by server::zone::managers::city::CityManagerImplementation::registerForMayoralRace().
void CityRegion::addCitizen (unsigned long long citizenID)
Definition at line 289 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addCitizen(), and RPC_ADDCITIZEN__LONG_.
Referenced by server::zone::managers::city::CityManagerImplementation::registerCitizen().
void CityRegion::addCommercialStructure (StructureObject * structure)
Definition at line 1162 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addCommercialStructure(), and RPC_ADDCOMMERCIALSTRUCTURE__STRUCTUREOBJECT_.
void CityRegion::addDecoration (SceneObject * deco)
Definition at line 985 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addDecoration(), and RPC_ADDDECORATION__SCENEOBJECT_.
void CityRegion::addMilitiaMember (unsigned long long objectid)
Definition at line 154 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addMilitiaMember(), and RPC_ADDMILITIAMEMBER__LONG_.
Referenced by server::zone::managers::city::CityManagerImplementation::addMilitiaMember(), server::zone::managers::city::CityManagerImplementation::changeCitySpecialization(), server::zone::managers::city::CityManagerImplementation::contractCity(), and server::zone::managers::city::CityManagerImplementation::expandCity().
void CityRegion::addMissionTerminal (SceneObject * mt)
Definition at line 971 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addMissionTerminal(), and RPC_ADDMISSIONTERMINAL__SCENEOBJECT_.
Region * CityRegion::addRegion (float x, float y, float radius, bool persistent)
Definition at line 110 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addRegion(), and RPC_ADDREGION__FLOAT_FLOAT_FLOAT_BOOL_.
void CityRegion::addSkillTrainer (SceneObject * trainer)
Definition at line 999 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addSkillTrainer(), and RPC_ADDSKILLTRAINER__SCENEOBJECT_.
void CityRegion::addStructure (StructureObject * structure)
Definition at line 1148 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addStructure(), and RPC_ADDSTRUCTURE__STRUCTUREOBJECT_.
float CityRegion::addToCityTreasury (float val)
Definition at line 749 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addToCityTreasury(), and RPC_ADDTOCITYTREASURY__FLOAT_.
Referenced by server::zone::managers::city::CityManagerImplementation::depositToCityTreasury().
void CityRegion::addZoningRights (unsigned long long objectid, unsigned int duration = 86400)
Definition at line 196 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::addZoningRights(), and RPC_ADDZONINGRIGHTS__LONG_INT_.
void CityRegion::applySpecializationModifiers (CreatureObject * creature)
Definition at line 1425 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::applySpecializationModifiers(), and RPC_APPLYSPECIALIZATIONMODIFIERS__CREATUREOBJECT_.
void CityRegion::cleanupCitizens ()
Definition at line 254 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::cleanupCitizens(), and RPC_CLEANUPCITIZENS__.
Referenced by server::zone::managers::city::CityManagerImplementation::contractCity(), server::zone::managers::city::CityManagerImplementation::processCityUpdate(), and server::zone::ZoneImplementation::updateCityRegions().
void CityRegion::cleanupDecorations (int decorationLimit)
Definition at line 1703 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::cleanupDecorations(), and RPC_CLEANUPDECORATIONS__INT_.
Referenced by server::zone::managers::city::CityManagerImplementation::processCityUpdate().
void CityRegion::cleanupDuplicateCityStructures ()
Definition at line 1605 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::cleanupDuplicateCityStructures(), and RPC_CLEANUPDUPLICATECITYSTRUCTURES__.
Referenced by server::zone::managers::city::CityManagerImplementation::processCityUpdate().
bool CityRegion::containsPoint (float x, float y)
Definition at line 239 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::containsPoint(), and RPC_CONTAINSPOINT__FLOAT_FLOAT_.
Referenced by RegionMap::getRegionAt().
void CityRegion::destroyActiveAreas ()
Definition at line 141 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::destroyActiveAreas(), and RPC_DESTROYACTIVEAREAS__.
Referenced by server::zone::managers::city::CityManagerImplementation::destroyCity().
void CityRegion::destroyAllStructuresForRank (byte rank)
Definition at line 1218 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::destroyAllStructuresForRank(), and RPC_DESTROYALLSTRUCTURESFORRANK__BYTE_.
Referenced by server::zone::managers::city::CityManagerImplementation::contractCity().
int CityRegion::getAllStructuresCount ()
Definition at line 585 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getAllStructuresCount(), and RPC_GETALLSTRUCTURESCOUNT__.
Referenced by server::zone::managers::city::CityManagerImplementation::sendCityReport(), and server::zone::managers::city::CityManagerImplementation::sendStatusReport().
CitizenList * CityRegion::getBannedPlayers ()
Definition at line 430 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getBannedPlayers().
TangibleObject * CityRegion::getBazaar (int idx)
Definition at line 1069 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getBazaar(), and RPC_GETBAZAAR__INT_.
int CityRegion::getBazaarCount ()
Definition at line 1083 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getBazaarCount(), and RPC_GETBAZAARCOUNT__.
VectorMap< unsigned long long, int > * CityRegion::getCandidates ()
Definition at line 1275 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getCandidates().
Referenced by server::zone::managers::city::CityManagerImplementation::promptMayoralVote(), server::zone::managers::city::CityManagerImplementation::sendMayoralStandings(), and server::zone::managers::city::CityManagerImplementation::updateCityVoting().
int CityRegion::getCandidateVotes (unsigned long long candidateoid)
Definition at line 1261 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getCandidateVotes(), and RPC_GETCANDIDATEVOTES__LONG_.
int CityRegion::getCitizenCount ()
Definition at line 372 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getCitizenCount(), and RPC_GETCITIZENCOUNT__.
Referenced by server::zone::managers::city::CityManagerImplementation::processCityUpdate(), server::zone::managers::city::CityManagerImplementation::sendCityAdvancement(), server::zone::managers::city::CityManagerImplementation::sendCityReport(), and server::zone::managers::city::CityManagerImplementation::sendStatusReport().
CitizenList * CityRegion::getCitizenList ()
Definition at line 412 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getCitizenList().
Referenced by server::zone::managers::city::CityManagerImplementation::processIncomeTax(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), server::zone::managers::city::CityManagerImplementation::sendCitizenshipReport(), and server::zone::managers::city::CityManagerImplementation::sendMail().
SceneObject * CityRegion::getCityDecoration (int indx)
Definition at line 1565 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getCityDecoration().
Referenced by server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport(), and server::zone::managers::city::CityManagerImplementation::sendStructureReport().
StructureObject * CityRegion::getCityHall ()
Definition at line 666 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getCityHall(), and RPC_GETCITYHALL__.
Referenced by server::zone::managers::city::CityManagerImplementation::contractCity(), server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), and server::zone::managers::city::CityManagerImplementation::destroyCity().
SceneObject * CityRegion::getCityMissionTerminal (int indx)
Definition at line 1574 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getCityMissionTerminal().
Referenced by server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), and server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport().
byte CityRegion::getCityRank ()
Definition at line 385 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getCityRank(), and RPC_GETCITYRANK__.
Referenced by server::zone::managers::city::CityManagerImplementation::canSupportMoreDecorations(), server::zone::managers::city::CityManagerImplementation::contractCity(), server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), server::zone::managers::city::CityManagerImplementation::expandCity(), server::zone::managers::city::CityManagerImplementation::isCityRankCapped(), server::zone::managers::city::CityManagerImplementation::processCityUpdate(), server::zone::managers::city::CityManagerImplementation::promptRegisterCity(), server::zone::managers::city::CityManagerImplementation::sendCityAdvancement(), server::zone::managers::city::CityManagerImplementation::sendCityReport(), and server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport().
SceneObject * CityRegion::getCitySkillTrainer (int indx)
Definition at line 1583 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getCitySkillTrainer().
Referenced by server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), and server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport().
String CityRegion::getCitySpecialization ()
Definition at line 598 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getCitySpecialization(), and RPC_GETCITYSPECIALIZATION__.
Referenced by server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport(), and server::zone::managers::city::CityManagerImplementation::sendStatusReport().
float CityRegion::getCityTreasury ()
Definition at line 613 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getCityTreasury(), and RPC_GETCITYTREASURY__.
Referenced by server::zone::managers::city::CityManagerImplementation::collectCivicStructureMaintenance(), server::zone::managers::city::CityManagerImplementation::collectNonStructureMaintenance(), server::zone::managers::city::CityManagerImplementation::sendCityReport(), server::zone::managers::city::CityManagerImplementation::sendTreasuryReport(), and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
StructureObject * CityRegion::getCivicStructure (int indx)
Definition at line 1547 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getCivicStructure().
Referenced by server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), server::zone::managers::city::CityManagerImplementation::registerCity(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport(), server::zone::managers::city::CityManagerImplementation::sendStructureReport(), server::zone::managers::city::CityManagerImplementation::unregisterCity(), and server::zone::ZoneImplementation::updateCityRegions().
StructureObject * CityRegion::getCommercialStructure (int indx)
Definition at line 1556 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getCommercialStructure().
Referenced by server::zone::managers::city::CityManagerImplementation::registerCity(), server::zone::managers::city::CityManagerImplementation::unregisterCity(), and server::zone::ZoneImplementation::updateCityRegions().
int CityRegion::getCommercialStructuresCount ()
Definition at line 572 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getCommercialStructuresCount(), and RPC_GETCOMMERCIALSTRUCTURESCOUNT__.
Referenced by server::zone::managers::city::CityManagerImplementation::registerCity(), server::zone::managers::city::CityManagerImplementation::unregisterCity(), and server::zone::ZoneImplementation::updateCityRegions().
int CityRegion::getCurrentPlayerCount ()
Definition at line 276 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getCurrentPlayerCount(), and RPC_GETCURRENTPLAYERCOUNT__.
int CityRegion::getDecorationCount ()
Definition at line 945 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getDecorationCount(), and RPC_GETDECORATIONCOUNT__.
Referenced by server::zone::managers::city::CityManagerImplementation::canSupportMoreDecorations(), server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), server::zone::managers::city::CityManagerImplementation::processCityUpdate(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport(), server::zone::managers::city::CityManagerImplementation::sendStatusReport(), and server::zone::managers::city::CityManagerImplementation::sendStructureReport().
int CityRegion::getGarageTax ()
Definition at line 1505 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getGarageTax(), and RPC_GETGARAGETAX__.
int CityRegion::getIncomeTax ()
Definition at line 1466 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getIncomeTax(), and RPC_GETINCOMETAX__.
Referenced by server::zone::managers::city::CityManagerImplementation::processIncomeTax().
int CityRegion::getMaxWithdrawal ()
Definition at line 777 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getMaxWithdrawal(), and RPC_GETMAXWITHDRAWAL__.
Referenced by server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
VectorMap< unsigned long long, unsigned long long > * CityRegion::getMayoralVotes ()
Definition at line 1284 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getMayoralVotes().
unsigned long long CityRegion::getMayorID ()
Definition at line 480 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getMayorID(), and RPC_GETMAYORID__.
Referenced by server::zone::managers::city::CityManagerImplementation::contractCity(), server::zone::managers::city::CityManagerImplementation::destroyCity(), server::zone::managers::city::CityManagerImplementation::expandCity(), server::zone::managers::city::CityManagerImplementation::processCityUpdate(), server::zone::managers::city::CityManagerImplementation::processIncomeTax(), server::zone::managers::city::CityManagerImplementation::promptMayoralVote(), server::zone::managers::city::CityManagerImplementation::registerCitizen(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceDecayEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceDestroyEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceEmail(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceRepairEmail(), server::zone::managers::city::CityManagerImplementation::sendMayoralStandings(), server::zone::managers::city::CityManagerImplementation::sendStatusReport(), server::zone::managers::city::CityManagerImplementation::unregisterCitizen(), and server::zone::managers::city::CityManagerImplementation::updateCityVoting().
CitizenList * CityRegion::getMilitiaMembers ()
Definition at line 421 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getMilitiaMembers().
Referenced by server::zone::managers::city::CityManagerImplementation::changeCitySpecialization(), server::zone::managers::city::CityManagerImplementation::contractCity(), server::zone::managers::city::CityManagerImplementation::expandCity(), and server::zone::managers::city::CityManagerImplementation::sendManageMilitia().
int CityRegion::getMissionTerminalCount ()
Definition at line 932 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getMissionTerminalCount(), and RPC_GETMISSIONTERMINALCOUNT__.
Referenced by server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), and server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport().
Time * CityRegion::getNextUpdateTime ()
Definition at line 267 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getNextUpdateTime().
Referenced by server::zone::managers::city::CityManagerImplementation::sendCityReport(), and server::zone::ZoneImplementation::updateCityRegions().
float CityRegion::getPositionX ()
Definition at line 493 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getPositionX(), and RPC_GETPOSITIONX__.
Referenced by server::zone::managers::city::CityManagerImplementation::sendCityReport(), server::zone::managers::city::CityManagerImplementation::sendStatusReport(), and server::zone::managers::city::CityManagerImplementation::validateCityInRange().
float CityRegion::getPositionY ()
Definition at line 506 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getPositionY(), and RPC_GETPOSITIONY__.
Referenced by server::zone::managers::city::CityManagerImplementation::sendCityReport(), server::zone::managers::city::CityManagerImplementation::sendStatusReport(), and server::zone::managers::city::CityManagerImplementation::validateCityInRange().
int CityRegion::getPropertyTax ()
Definition at line 1453 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getPropertyTax(), and RPC_GETPROPERTYTAX__.
float CityRegion::getRadius ()
Definition at line 519 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getRadius(), and RPC_GETRADIUS__.
Referenced by server::zone::managers::city::CityManagerImplementation::changeCitySpecialization(), server::zone::managers::city::CityManagerImplementation::processCityUpdate(), and server::zone::managers::city::CityManagerImplementation::sendStatusReport().
Region * CityRegion::getRegion (int idx)
Definition at line 532 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getRegion(), and RPC_GETREGION__INT_.
Referenced by server::zone::managers::planet::PlanetManagerImplementation::getRegion(), server::zone::managers::planet::PlanetManagerAdapter::getRegion(), server::zone::managers::city::CityManagerImplementation::registerCity(), server::zone::managers::city::CityManagerImplementation::unregisterCity(), server::zone::ZoneImplementation::updateCityRegions(), and server::zone::managers::planet::PlanetManagerImplementation::validateClientCityInRange().
String CityRegion::getRegionName ()
Definition at line 465 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getRegionName(), and RPC_GETREGIONNAME__.
Referenced by RegionMap::addRegion(), server::zone::managers::city::CityManagerImplementation::contractCity(), server::zone::managers::city::CityManagerImplementation::destroyCity(), server::zone::managers::city::CityManagerImplementation::expandCity(), server::zone::managers::city::CityManagerImplementation::processCityUpdate(), server::zone::managers::city::CityManagerImplementation::processIncomeTax(), server::zone::managers::city::CityManagerImplementation::registerCitizen(), server::zone::managers::city::CityManagerImplementation::renameCity(), server::zone::managers::city::CityManagerImplementation::sendCityReport(), server::zone::managers::city::CityManagerImplementation::sendStatusReport(), server::zone::managers::city::CityManagerImplementation::setTax(), server::zone::managers::city::CityManagerImplementation::unregisterCity(), server::zone::managers::city::CityManagerImplementation::updateCityVoting(), server::zone::managers::city::CityManagerImplementation::validateCityInRange(), server::zone::managers::planet::PlanetManagerImplementation::validateClientCityInRange(), and server::zone::managers::planet::PlanetManagerImplementation::validateRegionName().
int CityRegion::getRegionsCount ()
Definition at line 546 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getRegionsCount(), and RPC_GETREGIONSCOUNT__.
Referenced by server::zone::managers::city::CityManagerImplementation::unregisterCity(), server::zone::ZoneImplementation::updateCityRegions(), and server::zone::managers::planet::PlanetManagerImplementation::validateClientCityInRange().
int CityRegion::getSalesTax ()
Definition at line 1479 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getSalesTax(), and RPC_GETSALESTAX__.
int CityRegion::getSkillTrainerCount ()
Definition at line 958 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getSkillTrainerCount(), and RPC_GETSKILLTRAINERCOUNT__.
Referenced by server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), and server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport().
int CityRegion::getStructuresCount ()
Definition at line 559 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getStructuresCount(), and RPC_GETSTRUCTURESCOUNT__.
Referenced by server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), server::zone::managers::city::CityManagerImplementation::registerCity(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport(), server::zone::managers::city::CityManagerImplementation::sendStatusReport(), server::zone::managers::city::CityManagerImplementation::sendStructureReport(), server::zone::managers::city::CityManagerImplementation::unregisterCity(), and server::zone::ZoneImplementation::updateCityRegions().
int CityRegion::getTax (int tax)
Definition at line 1518 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getTax(), and RPC_GETTAX__INT_.
Referenced by server::zone::managers::city::CityManagerImplementation::sendStatusReport().
int CityRegion::getTimeToUpdate ()
Definition at line 359 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getTimeToUpdate(), and RPC_GETTIMETOUPDATE__.
Referenced by server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport().
int CityRegion::getTravelTax ()
Definition at line 1492 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getTravelTax(), and RPC_GETTRAVELTAX__.
Vector< ManagedReference< TangibleObject * > > * CityRegion::getVendorsInCity ()
Definition at line 790 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::getVendorsInCity().
Zone * CityRegion::getZone ()
Definition at line 452 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::getZone(), and RPC_GETZONE__.
Referenced by server::zone::managers::city::CityManagerImplementation::destroyCity(), server::zone::managers::city::CityManagerImplementation::expandCity(), server::zone::managers::city::CityManagerImplementation::isCityRankCapped(), server::zone::managers::city::CityManagerImplementation::sendCityReport(), and server::zone::managers::city::CityManagerImplementation::validateCityInRange().
bool CityRegion::hasShuttleInstallation ()
Definition at line 905 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::hasShuttleInstallation(), and RPC_HASSHUTTLEINSTALLATION__.
bool CityRegion::hasUniqueStructure (unsigned int crc)
Checks if the city has a structure in it's structures list of a particular template type.
Parameters
crc The crc of the template of the structure to search for.
Returns
True if the city has a structure of this type.
Definition at line 1204 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::hasUniqueStructure(), and RPC_HASUNIQUESTRUCTURE__INT_.
bool CityRegion::hasZoningRights (unsigned long long objectid)
Definition at line 225 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::hasZoningRights(), and RPC_HASZONINGRIGHTS__LONG_.
void CityRegion::initialize ()
Definition at line 43 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::initialize(), and RPC_INITIALIZE__.
void CityRegion::initializeTransientMembers ()
Definition at line 56 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::initializeTransientMembers(), and RPC_INITIALIZETRANSIENTMEMBERS__.
bool CityRegion::isBanned (unsigned long long playerID)
Definition at line 398 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isBanned(), and RPC_ISBANNED__LONG_.
bool CityRegion::isCandidate (unsigned long long candidateoid)
Definition at line 1333 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isCandidate(), and RPC_ISCANDIDATE__LONG_.
Referenced by server::zone::managers::city::CityManagerImplementation::castMayoralVote(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), and server::zone::managers::city::CityManagerImplementation::updateCityVoting().
bool CityRegion::isCitizen (unsigned long long citizenID)
Definition at line 345 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isCitizen(), and RPC_ISCITIZEN__LONG_.
Referenced by server::zone::managers::city::CityManagerImplementation::addMilitiaMember(), server::zone::managers::city::CityManagerImplementation::castMayoralVote(), server::zone::managers::city::CityManagerImplementation::fixMayor(), server::zone::managers::city::CityManagerImplementation::promptMayoralVote(), server::zone::managers::city::CityManagerImplementation::registerForMayoralRace(), and server::zone::managers::city::CityManagerImplementation::updateCityVoting().
bool CityRegion::isClientRegion ()
Definition at line 653 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isClientRegion(), and RPC_ISCLIENTREGION__.
bool CityRegion::isInsideRadius (SceneObject * obj, int radiusToUse)
Definition at line 1674 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isInsideRadius(), and RPC_ISINSIDERADIUS__SCENEOBJECT_INT_.
bool CityRegion::isLoaded ()
Definition at line 1399 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isLoaded(), and RPC_ISLOADED__.
bool CityRegion::isMayor (unsigned long long objectid)
Definition at line 626 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isMayor(), and RPC_ISMAYOR__LONG_.
Referenced by server::zone::managers::city::CityManagerImplementation::addMilitiaMember(), server::zone::managers::city::CityManagerImplementation::castMayoralVote(), server::zone::managers::city::CityManagerImplementation::fixMayor(), server::zone::managers::city::CityManagerImplementation::promptRegisterCity(), server::zone::managers::city::CityManagerImplementation::promptUnregisterCity(), server::zone::managers::city::CityManagerImplementation::promptWithdrawCityTreasury(), server::zone::managers::city::CityManagerImplementation::removeMilitiaMember(), and server::zone::managers::city::CityManagerImplementation::toggleZoningEnabled().
bool CityRegion::isMilitiaMember (unsigned long long objectid)
Definition at line 182 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isMilitiaMember(), and RPC_ISMILITIAMEMBER__LONG_.
Referenced by server::zone::managers::city::CityManagerImplementation::sendCitizenshipReport().
bool CityRegion::isRegistered ()
Definition at line 439 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isRegistered(), and RPC_ISREGISTERED__.
Referenced by server::zone::managers::city::CityManagerImplementation::deductCityMaintenance(), server::zone::managers::city::CityManagerImplementation::sendMaintenanceReport(), and server::zone::ZoneImplementation::updateCityRegions().
bool CityRegion::isVotingLocked ()
Definition at line 1373 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isVotingLocked(), and RPC_ISVOTINGLOCKED__.
Referenced by server::zone::managers::city::CityManagerImplementation::registerForMayoralRace().
bool CityRegion::isVotingPeriod ()
Definition at line 1360 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isVotingPeriod(), and RPC_ISVOTINGPERIOD__.
bool CityRegion::isVotingPeriodOver ()
Definition at line 1347 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isVotingPeriodOver(), and RPC_ISVOTINGPERIODOVER__.
Referenced by server::zone::managers::city::CityManagerImplementation::updateCityVoting().
bool CityRegion::isZoningEnabled ()
Definition at line 640 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::isZoningEnabled(), and RPC_ISZONINGENABLED__.
Referenced by server::zone::managers::city::CityManagerImplementation::toggleZoningEnabled().
void CityRegion::notifyEnter (SceneObject * object)
Definition at line 82 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::notifyEnter(), and RPC_NOTIFYENTER__SCENEOBJECT_.
void CityRegion::notifyExit (SceneObject * object)
Definition at line 96 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::notifyExit(), and RPC_NOTIFYEXIT__SCENEOBJECT_.
void CityRegion::notifyLoadFromDatabase ()
Gets called when this objects is loaded from database
Precondition
{ this locked }
Postcondition
{ this locked }
Definition at line 69 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::notifyLoadFromDatabase(), and RPC_NOTIFYLOADFROMDATABASE__.
void CityRegion::removeAllDecorations ()
Definition at line 1122 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeAllDecorations(), and RPC_REMOVEALLDECORATIONS__.
void CityRegion::removeAllSkillTrainers ()
Definition at line 1096 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeAllSkillTrainers(), and RPC_REMOVEALLSKILLTRAINERS__.
void CityRegion::removeAllTerminals ()
Definition at line 1109 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeAllTerminals(), and RPC_REMOVEALLTERMINALS__.
void CityRegion::removeAmenitiesOutsideCity (int newRadius)
Definition at line 1689 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeAmenitiesOutsideCity(), and RPC_REMOVEAMENITIESOUTSIDECITY__INT_.
Referenced by server::zone::managers::city::CityManagerImplementation::contractCity().
void CityRegion::removeBannedPlayer (unsigned long long playerid)
Definition at line 331 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeBannedPlayer(), and RPC_REMOVEBANNEDPLAYER__LONG_.
void CityRegion::removeCandidate (unsigned long long candidateoid)
Definition at line 1319 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeCandidate(), and RPC_REMOVECANDIDATE__LONG_.
Referenced by server::zone::managers::city::CityManagerImplementation::registerForMayoralRace().
void CityRegion::removeCitizen (unsigned long long citizenID)
Definition at line 303 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeCitizen(), and RPC_REMOVECITIZEN__LONG_.
Referenced by server::zone::managers::city::CityManagerImplementation::unregisterCitizen().
void CityRegion::removeCommercialStructure (StructureObject * structure)
Definition at line 1190 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeCommercialStructure(), and RPC_REMOVECOMMERCIALSTRUCTURE__STRUCTUREOBJECT_.
void CityRegion::removeDecoration (SceneObject * deco)
Definition at line 1027 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeDecoration(), and RPC_REMOVEDECORATION__SCENEOBJECT_.
Referenced by server::zone::managers::city::CityManagerImplementation::collectNonStructureMaintenance().
void CityRegion::removeDecorationsOutsideCity (int newRadius)
Definition at line 1618 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeDecorationsOutsideCity(), and RPC_REMOVEDECORATIONSOUTSIDECITY__INT_.
void CityRegion::removeMilitiaMember (unsigned long long objectid)
Definition at line 168 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeMilitiaMember(), and RPC_REMOVEMILITIAMEMBER__LONG_.
Referenced by server::zone::managers::city::CityManagerImplementation::removeMilitiaMember().
void CityRegion::removeMissionTerminal (SceneObject * mt)
Definition at line 1013 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeMissionTerminal(), and RPC_REMOVEMISSIONTERMINAL__SCENEOBJECT_.
Referenced by server::zone::managers::city::CityManagerImplementation::collectNonStructureMaintenance().
void CityRegion::removeShuttleInstallation ()
Definition at line 892 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeShuttleInstallation(), and RPC_REMOVESHUTTLEINSTALLATION__.
void CityRegion::removeSkillTrainers (SceneObject * trainer)
Definition at line 1041 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeSkillTrainers(), and RPC_REMOVESKILLTRAINERS__SCENEOBJECT_.
Referenced by server::zone::managers::city::CityManagerImplementation::collectNonStructureMaintenance().
void CityRegion::removeSpecializationModifiers (CreatureObject * creature)
Definition at line 1439 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeSpecializationModifiers(), and RPC_REMOVESPECIALIZATIONMODIFIERS__CREATUREOBJECT_.
void CityRegion::removeStructure (StructureObject * structure)
Definition at line 1176 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeStructure(), and RPC_REMOVESTRUCTURE__STRUCTUREOBJECT_.
void CityRegion::removeStructuresOutsideCity (int newRadius)
Definition at line 1660 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeStructuresOutsideCity(), and RPC_REMOVESTRUCTURESOUTSIDECITY__INT_.
void CityRegion::removeTerminalsOutsideCity (int newRadius)
Definition at line 1646 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeTerminalsOutsideCity(), and RPC_REMOVETERMINALSOUTSIDECITY__INT_.
void CityRegion::removeTrainersOutsideCity (int newRadius)
Definition at line 1632 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeTrainersOutsideCity(), and RPC_REMOVETRAINERSOUTSIDECITY__INT_.
void CityRegion::removeZoningRights (unsigned long long objectid)
Definition at line 211 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::removeZoningRights(), and RPC_REMOVEZONINGRIGHTS__LONG_.
void CityRegion::rescheduleUpdateEvent (unsigned int seconds)
Definition at line 127 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::rescheduleUpdateEvent(), and RPC_RESCHEDULEUPDATEEVENT__INT_.
Referenced by server::zone::managers::city::CityManagerImplementation::processCityUpdate(), and server::zone::ZoneImplementation::updateCityRegions().
void CityRegion::resetCandidates ()
At the end of a voting term, all candidates are removed from the ballot.
Definition at line 1293 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::resetCandidates(), and RPC_RESETCANDIDATES__.
Referenced by server::zone::managers::city::CityManagerImplementation::updateCityVoting().
void CityRegion::resetMayoralVotes ()
All votes are removed from the ballot.
Definition at line 1306 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::resetMayoralVotes(), and RPC_RESETMAYORALVOTES__.
Referenced by server::zone::managers::city::CityManagerImplementation::updateCityVoting().
void CityRegion::resetVotingPeriod ()
Definition at line 1386 of file CityRegion.cpp.
References _getImplementation(), server::zone::objects::region::CityRegionImplementation::resetVotingPeriod(), and RPC_RESETVOTINGPERIOD__.
Referenced by server::zone::managers::city::CityManagerImplementation::updateCityVoting().
void CityRegion::setCityHall (StructureObject * building)
Definition at line 878 of file CityRegion.cpp.
References _getImplementation(), RPC_SETCITYHALL__STRUCTUREOBJECT_, and server::zone::objects::region::CityRegionImplementation::setCityHall().
Referenced by server::zone::managers::city::CityManagerImplementation::destroyCity().
void CityRegion::setCityRank (byte rank)
Definition at line 808 of file CityRegion.cpp.
References _getImplementation(), RPC_SETCITYRANK__BYTE_, and server::zone::objects::region::CityRegionImplementation::setCityRank().
Referenced by server::zone::managers::city::CityManagerImplementation::contractCity(), and server::zone::managers::city::CityManagerImplementation::expandCity().
void CityRegion::setCitySpecialization (const String & spec)
Definition at line 707 of file CityRegion.cpp.
References _getImplementation(), RPC_SETCITYSPECIALIZATION__STRING_, and server::zone::objects::region::CityRegionImplementation::setCitySpecialization().
Referenced by server::zone::managers::city::CityManagerImplementation::changeCitySpecialization().
void CityRegion::setCityTreasury (float val)
Definition at line 735 of file CityRegion.cpp.
References _getImplementation(), RPC_SETCITYTREASURY__FLOAT_, and server::zone::objects::region::CityRegionImplementation::setCityTreasury().
void CityRegion::setCustomRegionName (const String & name)
Definition at line 693 of file CityRegion.cpp.
References _getImplementation(), RPC_SETCUSTOMREGIONNAME__STRING_, and server::zone::objects::region::CityRegionImplementation::setCustomRegionName().
void CityRegion::setLoaded ()
Definition at line 1412 of file CityRegion.cpp.
References _getImplementation(), RPC_SETLOADED__, and server::zone::objects::region::CityRegionImplementation::setLoaded().
Referenced by server::zone::ZoneImplementation::updateCityRegions().
void CityRegion::setMayoralVote (unsigned long long voteroid, unsigned long long candidateoid)
This method does not check to see if they have previously voted. That logic should be contained in the Manager. This is just a data container.
Definition at line 1246 of file CityRegion.cpp.
References _getImplementation(), RPC_SETMAYORALVOTE__LONG_LONG_, and server::zone::objects::region::CityRegionImplementation::setMayoralVote().
Referenced by server::zone::managers::city::CityManagerImplementation::castMayoralVote().
void CityRegion::setMayorID (unsigned long long id)
Definition at line 822 of file CityRegion.cpp.
References _getImplementation(), RPC_SETMAYORID__LONG_, and server::zone::objects::region::CityRegionImplementation::setMayorID().
Referenced by server::zone::managers::city::CityManagerImplementation::updateCityVoting().
void CityRegion::setRadius (float rad)
Definition at line 864 of file CityRegion.cpp.
References _getImplementation(), RPC_SETRADIUS__FLOAT_, and server::zone::objects::region::CityRegionImplementation::setRadius().
Referenced by server::zone::managers::city::CityManagerImplementation::changeCitySpecialization(), server::zone::managers::city::CityManagerImplementation::contractCity(), and server::zone::managers::city::CityManagerImplementation::expandCity().
void CityRegion::setRegionName (const String & fullPath)
Definition at line 721 of file CityRegion.cpp.
References _getImplementation(), RPC_SETREGIONNAME__STRING_, and server::zone::objects::region::CityRegionImplementation::setRegionName().
void CityRegion::setRegionName (const StringId & name)
Definition at line 799 of file CityRegion.cpp.
References _getImplementation(), and server::zone::objects::region::CityRegionImplementation::setRegionName().
void CityRegion::setRegistered (bool val)
Definition at line 836 of file CityRegion.cpp.
References _getImplementation(), RPC_SETREGISTERED__BOOL_, and server::zone::objects::region::CityRegionImplementation::setRegistered().
Referenced by server::zone::managers::city::CityManagerImplementation::registerCity(), and server::zone::managers::city::CityManagerImplementation::unregisterCity().
void CityRegion::setShuttleID (unsigned long long id)
Definition at line 918 of file CityRegion.cpp.
References _getImplementation(), RPC_SETSHUTTLEID__LONG_, and server::zone::objects::region::CityRegionImplementation::setShuttleID().
void CityRegion::setTax (int tax, int value)
Definition at line 1532 of file CityRegion.cpp.
References _getImplementation(), RPC_SETTAX__INT_INT_, and server::zone::objects::region::CityRegionImplementation::setTax().
Referenced by server::zone::managers::city::CityManagerImplementation::setTax().
void CityRegion::setZone (Zone * zne)
Definition at line 679 of file CityRegion.cpp.
References _getImplementation(), RPC_SETZONE__ZONE_, and server::zone::objects::region::CityRegionImplementation::setZone().
Referenced by server::zone::managers::city::CityManagerImplementation::destroyCity().
void CityRegion::setZoningEnabled (bool val)
Definition at line 850 of file CityRegion.cpp.
References _getImplementation(), RPC_SETZONINGENABLED__BOOL_, and server::zone::objects::region::CityRegionImplementation::setZoningEnabled().
Referenced by server::zone::managers::city::CityManagerImplementation::toggleZoningEnabled().
float CityRegion::subtractFromCityTreasury (float val)
Definition at line 763 of file CityRegion.cpp.
References _getImplementation(), RPC_SUBTRACTFROMCITYTREASURY__FLOAT_, and server::zone::objects::region::CityRegionImplementation::subtractFromCityTreasury().
Referenced by server::zone::managers::city::CityManagerImplementation::collectCivicStructureMaintenance(), server::zone::managers::city::CityManagerImplementation::collectNonStructureMaintenance(), and server::zone::managers::city::CityManagerImplementation::withdrawFromCityTreasury().
void CityRegion::transferCivicStructuresToMayor ()
Definition at line 1592 of file CityRegion.cpp.
References _getImplementation(), RPC_TRANSFERCIVICSTRUCTURESTOMAYOR__, and server::zone::objects::region::CityRegionImplementation::transferCivicStructuresToMayor().
Referenced by server::zone::managers::city::CityManagerImplementation::updateCityVoting().
void CityRegion::updateMilitia ()
Definition at line 1135 of file CityRegion.cpp.
References _getImplementation(), RPC_UPDATEMILITIA__, and server::zone::objects::region::CityRegionImplementation::updateMilitia().
Friends And Related Function Documentation
friend class CityRegionHelper friend
Definition at line 446 of file CityRegion.h.
Member Data Documentation
const byte server::zone::objects::region::CityRegion::RANK_CITY = 4 static
Definition at line 143 of file CityRegion.h.
const byte server::zone::objects::region::CityRegion::RANK_CLIENT = 0 static
Definition at line 135 of file CityRegion.h.
const byte server::zone::objects::region::CityRegion::RANK_METROPOLIS = 5 static
Definition at line 145 of file CityRegion.h.
const byte server::zone::objects::region::CityRegion::RANK_OUTPOST = 1 static
Definition at line 137 of file CityRegion.h.
const byte server::zone::objects::region::CityRegion::RANK_TOWNSHIP = 3 static
Definition at line 141 of file CityRegion.h.
const byte server::zone::objects::region::CityRegion::RANK_VILLAGE = 2 static
Definition at line 139 of file CityRegion.h.
const byte server::zone::objects::region::CityRegion::TAX_GARAGE = 4 static
Definition at line 155 of file CityRegion.h.
const byte server::zone::objects::region::CityRegion::TAX_INCOME = 1 static
Definition at line 149 of file CityRegion.h.
const byte server::zone::objects::region::CityRegion::TAX_PROPERTY = 0 static
Definition at line 147 of file CityRegion.h.
const byte server::zone::objects::region::CityRegion::TAX_SALES = 2 static
Definition at line 151 of file CityRegion.h.
const byte server::zone::objects::region::CityRegion::TAX_TRAVEL = 3 static
Definition at line 153 of file CityRegion.h.
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/region/CityRegion.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/region/CityRegion.cpp