Core3: OutfitTangibleObject Class Reference
OutfitTangibleObject Class Reference
#include <MobileOutfit.h>
Public Member Functions
OutfitTangibleObject ()
OutfitTangibleObject (const OutfitTangibleObject &o)
OutfitTangibleObject & operator= (const OutfitTangibleObject &o)
void readObject (LuaObject *luaObject)
String getObjectTemplate ()
VectorMap< String, uint8 > * getCustomizationVariables ()
Private Attributes
String objectTemplate
VectorMap< String, uint8 > customizationVariables
Detailed Description
Definition at line 13 of file MobileOutfit.h.
Constructor & Destructor Documentation
OutfitTangibleObject::OutfitTangibleObject () inline
Definition at line 17 of file MobileOutfit.h.
OutfitTangibleObject::OutfitTangibleObject (const OutfitTangibleObject & o) inline
Definition at line 21 of file MobileOutfit.h.
References customizationVariables, and objectTemplate.
Member Function Documentation
VectorMap<String, uint8>* OutfitTangibleObject::getCustomizationVariables () inline
Definition at line 59 of file MobileOutfit.h.
References customizationVariables.
Referenced by server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData(), and server::zone::objects::creature::AiAgentImplementation::loadTemplateData().
String OutfitTangibleObject::getObjectTemplate () inline
Definition at line 55 of file MobileOutfit.h.
References objectTemplate.
Referenced by server::zone::objects::creature::ai::AiActorImplementation::loadTemplateData(), and server::zone::objects::creature::AiAgentImplementation::loadTemplateData().
OutfitTangibleObject& OutfitTangibleObject::operator= (const OutfitTangibleObject & o) inline
Definition at line 26 of file MobileOutfit.h.
References customizationVariables, and objectTemplate.
void OutfitTangibleObject::readObject (LuaObject * luaObject) inline
Definition at line 36 of file MobileOutfit.h.
References customizationVariables, and objectTemplate.
Referenced by MobileOutfit::readObject().
Member Data Documentation
VectorMap<String, uint8> OutfitTangibleObject::customizationVariables private
Definition at line 15 of file MobileOutfit.h.
Referenced by getCustomizationVariables(), operator=(), OutfitTangibleObject(), and readObject().
String OutfitTangibleObject::objectTemplate private
Definition at line 14 of file MobileOutfit.h.
Referenced by getObjectTemplate(), operator=(), OutfitTangibleObject(), and readObject().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/templates/mobile/MobileOutfit.h