Core3: PlayerObjectDeltaMessage9 Class Reference
PlayerObjectDeltaMessage9 Class Reference
#include <PlayerObjectDeltaMessage9.h>
Public Member Functions
PlayerObjectDeltaMessage9 (PlayerObject *pl)
void updateStomachFilling ()
void updateFoodFilling (int newVal)
void updateDrinkFilling (int newVal)
void setLanguageID (uint8 lid)
void setExperimentationEnabled (bool experimenting)
void setExperimentationPoints (int points)
void setCraftingState (int state)
void setClosestCraftingStation (uint64 oid)
void setJediState (int state)
Public Member Functions inherited from DeltaMessage
DeltaMessage (uint64 oid, uint32 name, uint8 type)
uint32 generateRandomObjectCRC ()
void startUpdate (uint16 type)
void addByteUpdate (uint16 type, uint8 value)
void addShortUpdate (uint16 type, uint16 value)
void addIntUpdate (uint16 type, uint32 value)
void addLongUpdate (uint16 type, uint64 value)
void addFloatUpdate (uint16 type, float value)
void addAsciiUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const String &val)
void addUnicodeUpdate (uint16 type, const UnicodeString &val)
void startList (uint32 cnt, uint32 updcnt)
void addListIntElement (uint16 index, uint32 value)
void addListFloatElement (uint16 index, float value)
void addListLongElement (uint16 index, uint64 value)
void addListAsciiElement (const String &value)
void removeListIntElement (uint16 index, uint32 value)
void removeListFloatElement (uint16 index, float value)
void removeListLongElement (uint16 index, uint64 value)
void removeListLongElement (uint16 index)
void removeListAsciiElement (const String &value)
void close ()
Private Attributes
PlayerObject * play
Detailed Description
Definition at line 51 of file PlayerObjectDeltaMessage9.h.
Constructor & Destructor Documentation
PlayerObjectDeltaMessage9::PlayerObjectDeltaMessage9 (PlayerObject * pl) inline
Definition at line 55 of file PlayerObjectDeltaMessage9.h.
References play.
Member Function Documentation
void PlayerObjectDeltaMessage9::setClosestCraftingStation (uint64 oid) inline
Definition at line 100 of file PlayerObjectDeltaMessage9.h.
References DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::startSession().
void PlayerObjectDeltaMessage9::setCraftingState (int state) inline
Definition at line 95 of file PlayerObjectDeltaMessage9.h.
References DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::cancelSession(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::finishAssembly(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::finishStage1(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::finishStage2(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::initialAssembly(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::selectDraftSchematic(), and server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::startSession().
void PlayerObjectDeltaMessage9::setExperimentationEnabled (bool experimenting) inline
Definition at line 80 of file PlayerObjectDeltaMessage9.h.
References DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::startSession().
void PlayerObjectDeltaMessage9::setExperimentationPoints (int points) inline
Definition at line 90 of file PlayerObjectDeltaMessage9.h.
References DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::experiment(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::initialAssembly(), server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::selectDraftSchematic(), and server::zone::objects::player::sessions::crafting::CraftingSessionImplementation::startSession().
void PlayerObjectDeltaMessage9::setJediState (int state) inline
Definition at line 105 of file PlayerObjectDeltaMessage9.h.
References DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::PlayerObjectImplementation::setJediState().
void PlayerObjectDeltaMessage9::setLanguageID (uint8 lid) inline
Definition at line 75 of file PlayerObjectDeltaMessage9.h.
References DeltaMessage::startUpdate().
Referenced by server::zone::objects::player::PlayerObjectImplementation::setLanguageID().
void PlayerObjectDeltaMessage9::updateDrinkFilling (int newVal) inline
Definition at line 71 of file PlayerObjectDeltaMessage9.h.
References DeltaMessage::addIntUpdate().
Referenced by server::zone::objects::player::PlayerObjectImplementation::setDrinkFilling().
void PlayerObjectDeltaMessage9::updateFoodFilling (int newVal) inline
Definition at line 67 of file PlayerObjectDeltaMessage9.h.
References DeltaMessage::addIntUpdate().
Referenced by server::zone::objects::player::PlayerObjectImplementation::setFoodFilling().
void PlayerObjectDeltaMessage9::updateStomachFilling () inline
Definition at line 60 of file PlayerObjectDeltaMessage9.h.
References DeltaMessage::addIntUpdate(), server::zone::objects::player::PlayerObject::getDrinkFilling(), server::zone::objects::player::PlayerObject::getDrinkFillingMax(), server::zone::objects::player::PlayerObject::getFoodFilling(), server::zone::objects::player::PlayerObject::getFoodFillingMax(), and play.
Member Data Documentation
PlayerObject* PlayerObjectDeltaMessage9::play private
Definition at line 52 of file PlayerObjectDeltaMessage9.h.
Referenced by PlayerObjectDeltaMessage9(), and updateStomachFilling().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/packets/player/PlayerObjectDeltaMessage9.h