Core3: server::zone::objects::player::sui::SuiBoxImplementation Class Reference
server::zone::objects::player::sui::SuiBoxImplementation Class Reference
#include <SuiBox.h>
Public Member Functions
SuiBoxImplementation (CreatureObject *play, unsigned int windowtype, unsigned int boxtype)
SuiBoxImplementation (DummyConstructorParameter *param)
void initialize ()
void finalize ()
void initializeTransientMembers ()
void generateHeader (SuiCreatePageMessage *message)
void generateBody (SuiCreatePageMessage *message)
void generateFooter (SuiCreatePageMessage *message, int type=0)
virtual BaseMessage * generateMessage ()
BaseMessage * generateCloseMessage ()
void addSetting (const String &optType, const String &variable, const String &setting, const String &value)
void addHeader (const String &variable, const String &type)
void clearOptions ()
int compareTo (SuiBox *obj)
bool hasGeneratedMessage ()
void setPromptTitle (const String &name)
void setPromptText (const String &name)
String getPromptTitle ()
void setHandlerText (const String &text)
void setWindowType (unsigned int type)
void setBoxType (int type)
virtual bool isInputBox ()
virtual bool isListBox ()
virtual bool isMessageBox ()
virtual bool isTransferBox ()
virtual bool isBankTransferBox ()
virtual bool isSlicingBox ()
virtual bool isCharacterBuilderBox ()
bool isColorPicker ()
void setCancelButton (bool value, const String &cancelText)
void setOtherButton (bool value, const String &backText)
void setOkButton (bool value, const String &okText)
void setForceCloseDistance (float dist)
void setForceCloseDisabled ()
ManagedWeakReference
< CreatureObject * > getPlayer ()
unsigned int getBoxID ()
int getWindowType ()
ManagedWeakReference
< SceneObject * > getUsingObject ()
void setUsingObject (SceneObject *object)
void setCallback (SuiCallback *callback)
SuiCallback * getCallback ()
operator const SuiBox * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< SuiBox * > _this
Static Public Attributes
static const int INPUTBOX = 0
static const int LISTBOX = 1
static const int MESSAGEBOX = 2
static const int TRANSFERBOX = 3
static const int COLORPICKER = 4
static const int BANKTRANSFERBOX = 5
static const int BANKTIPCONFIRMBOX = 10
static const int SLICINGBOX = 20
static const int KEYPAD = 21
Protected Member Functions
virtual ~SuiBoxImplementation ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
ManagedWeakReference
< CreatureObject * > player
Reference< SuiCallback * > suiCallback
unsigned int boxID
ManagedWeakReference
< SceneObject * > usingObject
String handlerStr
String cancelButtonText
bool cancelButton
String okButtonText
bool okButton
String otherButtonText
bool otherButton
String promptTitle
String promptText
int boxType
unsigned int windowType
float forceCloseDistance
Vector< String > headerSets
Vector< String > optionSets
int hdrOptCount
bool hasGenerated
Friends
class SuiBox
Detailed Description
Definition at line 254 of file SuiBox.h.
Constructor & Destructor Documentation
SuiBoxImplementation::SuiBoxImplementation (CreatureObject * play, unsigned int windowtype, unsigned int boxtype)
Definition at line 919 of file SuiBox.cpp.
References _initializeImplementation(), boxType, forceCloseDistance, initialize(), player, and windowType.
SuiBoxImplementation::SuiBoxImplementation (DummyConstructorParameter * param)
Definition at line 567 of file SuiBox.cpp.
References _initializeImplementation().
SuiBoxImplementation::~SuiBoxImplementation () protected virtual
Definition at line 572 of file SuiBox.cpp.
References finalize().
Member Function Documentation
DistributedObjectStub * SuiBoxImplementation::_getStub ()
Definition at line 590 of file SuiBox.cpp.
References _this.
void SuiBoxImplementation::_initializeImplementation () protected
Definition at line 577 of file SuiBox.cpp.
References _serializationHelperMethod(), and _this.
Referenced by SuiBoxImplementation().
void SuiBoxImplementation::_serializationHelperMethod () protected
Definition at line 626 of file SuiBox.cpp.
Referenced by _initializeImplementation(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::_serializationHelperMethod(), server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation::_serializationHelperMethod(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::_serializationHelperMethod(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::_serializationHelperMethod(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::_serializationHelperMethod(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::_serializationHelperMethod(), and server::zone::objects::player::sui::listbox::SuiListBoxImplementation::_serializationHelperMethod().
void SuiBoxImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 585 of file SuiBox.cpp.
References _this.
Referenced by server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::_setStub(), server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation::_setStub(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::_setStub(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::_setStub(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::_setStub(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::_setStub(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::_setStub(), and server::zone::objects::player::sui::SuiBox::SuiBox().
void SuiBoxImplementation::addHeader (const String & variable, const String & type)
Use to add a UI-Header that will eventually be included in the UI generation. See trac documentation of SuiCreatePageMessage for when to use Variables are concated into a string and placed in a vector (headerSets) of all the header settings for the SuiBoxImplementation object. Each string separates variables with a tilde (~) character.
Parameters
variable UI Variable to declare header for
type Data type of the UI variable being declared
Definition at line 101 of file SuiBoxImplementation.cpp.
References hdrOptCount, and headerSets.
Referenced by server::zone::objects::player::sui::SuiBox::addHeader(), server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::generateMessage(), and server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage().
void SuiBoxImplementation::addSetting (const String & optType, const String & variable, const String & setting, const String & value)
Use to add a UI-body option that will be included in UI generation See trac documentation of SuiCreatePageMessage for when to use Variables are concated into a string and placed in a vector (optionSets) of all the body settings for the SuiBoxImplementation object. Each string separates variables with a tilde (~) character.
Parameters
optType Type of setting to add. See packet docs for info
variable UI Classpath in the script to access
setting SWG UI setting to modify
value The value of the setting being modified
Definition at line 72 of file SuiBoxImplementation.cpp.
References optionSets.
Referenced by server::zone::objects::player::sui::SuiBox::addSetting(), server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::generateMessage(), and server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage().
void SuiBoxImplementation::clearOptions ()
Definition at line 975 of file SuiBox.cpp.
References hdrOptCount, headerSets, and optionSets.
Referenced by server::zone::objects::player::sui::SuiBox::clearOptions(), and generateCloseMessage().
int SuiBoxImplementation::compareTo (SuiBox * obj)
Definition at line 984 of file SuiBox.cpp.
References boxID, and server::zone::objects::player::sui::SuiBox::getBoxID().
Referenced by server::zone::objects::player::sui::SuiBox::compareTo().
void SuiBoxImplementation::finalize ()
Definition at line 962 of file SuiBox.cpp.
Referenced by ~SuiBoxImplementation().
void SuiBoxImplementation::generateBody (SuiCreatePageMessage * message)
Call after all Body Settings have been added with addSetting() and the header has been generated Generates the UI-Body of the packet, SuiCreatePageMessage, based on the optionSets vector. If you are reusing the SuiBox and rebuilding with different variables, make sure you reset the object with clearOptions()
See Also
addSetting(), clearOptions()
Definition at line 39 of file SuiBoxImplementation.cpp.
References SuiCreatePageMessage::insertOption(), and optionSets.
Referenced by server::zone::objects::player::sui::SuiBox::generateBody(), server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::generateMessage(), and server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage().
BaseMessage * SuiBoxImplementation::generateCloseMessage ()
Use to close the UI object on the client. Sends the SuiForceClosePage packet to the client.
Definition at line 66 of file SuiBoxImplementation.cpp.
References boxID, and clearOptions().
Referenced by server::zone::objects::player::sui::SuiBox::generateCloseMessage().
void SuiBoxImplementation::generateFooter (SuiCreatePageMessage * message, int type = 0)
Call after generating both the header and body. Footer of SuiCreatePageMessage is largely unknown. Subject to change based on research. See trac
Parameters
type Type of footer to place into packet
Definition at line 114 of file SuiBoxImplementation.cpp.
References forceCloseDistance, SuiCreatePageMessage::insertFooter(), and usingObject.
Referenced by server::zone::objects::player::sui::SuiBox::generateFooter(), server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::generateMessage(), and server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage().
void SuiBoxImplementation::generateHeader (SuiCreatePageMessage * message)
Call after all Header settings have been added with addHeader() Generates the UI-Header of the packet, SuiCreatePageMessage, based on the headerSets vector. If you are reusing the SuiBox and rebuilding with different variables, make sure you reset the object with clearOptions()
See Also
addHeader(), clearOptions()
Definition at line 13 of file SuiBoxImplementation.cpp.
References handlerStr, hdrOptCount, headerSets, and SuiCreatePageMessage::insertHeaderOption().
Referenced by server::zone::objects::player::sui::SuiBox::generateHeader(), server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::generateMessage(), and server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage().
BaseMessage * SuiBoxImplementation::generateMessage () virtual
Reimplemented in server::zone::objects::player::sui::listbox::SuiListBoxImplementation, server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation, server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation, server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation, server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation, server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation, server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation, and server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation.
Definition at line 970 of file SuiBox.cpp.
Referenced by server::zone::objects::player::sui::SuiBox::generateMessage().
unsigned int SuiBoxImplementation::getBoxID ()
Definition at line 1079 of file SuiBox.cpp.
References boxID.
Referenced by server::zone::objects::player::sui::SuiBox::getBoxID().
SuiCallback * SuiBoxImplementation::getCallback ()
Definition at line 1104 of file SuiBox.cpp.
References suiCallback.
Referenced by server::zone::objects::player::sui::SuiBox::getCallback().
ManagedWeakReference< CreatureObject * > SuiBoxImplementation::getPlayer ()
Definition at line 1074 of file SuiBox.cpp.
References player.
Referenced by server::zone::objects::player::sui::SuiBox::getPlayer().
String SuiBoxImplementation::getPromptTitle ()
Definition at line 1014 of file SuiBox.cpp.
References promptTitle.
Referenced by server::zone::objects::player::sui::SuiBox::getPromptTitle().
ManagedWeakReference< SceneObject * > SuiBoxImplementation::getUsingObject ()
Definition at line 1089 of file SuiBox.cpp.
References usingObject.
Referenced by server::zone::objects::player::sui::SuiBox::getUsingObject().
int SuiBoxImplementation::getWindowType ()
Definition at line 1084 of file SuiBox.cpp.
References windowType.
Referenced by server::zone::objects::player::sui::SuiBox::getWindowType().
bool SuiBoxImplementation::hasGeneratedMessage ()
Definition at line 999 of file SuiBox.cpp.
References hasGenerated.
Referenced by server::zone::objects::player::sui::SuiBox::hasGeneratedMessage().
void SuiBoxImplementation::initialize ()
Definition at line 933 of file SuiBox.cpp.
References boxID, cancelButton, cancelButtonText, handlerStr, hasGenerated, hdrOptCount, okButton, okButtonText, otherButton, otherButtonText, player, suiCallback, and windowType.
Referenced by server::zone::objects::player::sui::SuiBox::initialize(), and SuiBoxImplementation().
void SuiBoxImplementation::initializeTransientMembers ()
Definition at line 965 of file SuiBox.cpp.
Referenced by server::zone::objects::player::sui::SuiBox::initializeTransientMembers(), server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::readObject(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::readObject(), server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation::readObject(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::readObject(), server::zone::objects::player::sui::slotmachinebox::SuiSlotMachineBoxImplementation::readObject(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::readObject(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::readObject(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::readObject(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::readObject(), and readObject().
bool SuiBoxImplementation::isBankTransferBox () virtual
Reimplemented in server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation.
Definition at line 1054 of file SuiBox.cpp.
Referenced by server::zone::objects::player::sui::SuiBox::isBankTransferBox().
bool SuiBoxImplementation::isCharacterBuilderBox () virtual
Reimplemented in server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation.
Definition at line 1064 of file SuiBox.cpp.
Referenced by server::zone::objects::player::sui::SuiBox::isCharacterBuilderBox().
bool SuiBoxImplementation::isColorPicker ()
Definition at line 1069 of file SuiBox.cpp.
Referenced by server::zone::objects::player::sui::SuiBox::isColorPicker().
bool SuiBoxImplementation::isInputBox () virtual
Reimplemented in server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation.
Definition at line 1034 of file SuiBox.cpp.
Referenced by server::zone::objects::player::sui::SuiBox::isInputBox().
bool SuiBoxImplementation::isListBox () virtual
Reimplemented in server::zone::objects::player::sui::listbox::SuiListBoxImplementation.
Definition at line 1039 of file SuiBox.cpp.
Referenced by server::zone::objects::player::sui::SuiBox::isListBox().
bool SuiBoxImplementation::isMessageBox () virtual
Reimplemented in server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation.
Definition at line 1044 of file SuiBox.cpp.
Referenced by server::zone::objects::player::sui::SuiBox::isMessageBox().
bool SuiBoxImplementation::isSlicingBox () virtual
Definition at line 1059 of file SuiBox.cpp.
Referenced by server::zone::objects::player::sui::SuiBox::isSlicingBox().
bool SuiBoxImplementation::isTransferBox () virtual
Reimplemented in server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation.
Definition at line 1049 of file SuiBox.cpp.
Referenced by server::zone::objects::player::sui::SuiBox::isTransferBox().
void SuiBoxImplementation::lock (bool doLock = true) protected
Definition at line 598 of file SuiBox.cpp.
References _this.
void SuiBoxImplementation::lock (ManagedObject * obj) protected
Definition at line 602 of file SuiBox.cpp.
References _this.
SuiBoxImplementation::operator const SuiBox * ()
Definition at line 594 of file SuiBox.cpp.
void SuiBoxImplementation::readObject (ObjectInputStream * stream) virtual
Reimplemented in server::zone::objects::player::sui::listbox::SuiListBoxImplementation, server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation, server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation, server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation, server::zone::objects::player::sui::slotmachinebox::SuiSlotMachineBoxImplementation, server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation, server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation, server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation, and server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation.
Definition at line 633 of file SuiBox.cpp.
References initializeTransientMembers(), and readObjectMember().
bool SuiBoxImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 652 of file SuiBox.cpp.
References boxID, boxType, cancelButton, cancelButtonText, forceCloseDistance, handlerStr, hasGenerated, hdrOptCount, headerSets, okButton, okButtonText, optionSets, otherButton, otherButtonText, player, promptText, promptTitle, suiCallback, usingObject, and windowType.
Referenced by readObject(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::readObjectMember(), server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation::readObjectMember(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::readObjectMember(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::readObjectMember(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::readObjectMember(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::readObjectMember(), and server::zone::objects::player::sui::listbox::SuiListBoxImplementation::readObjectMember().
void SuiBoxImplementation::rlock (bool doLock = true) protected
Definition at line 606 of file SuiBox.cpp.
References _this.
void SuiBoxImplementation::runlock (bool doLock = true) protected
Definition at line 622 of file SuiBox.cpp.
References _this.
void SuiBoxImplementation::setBoxType (int type)
Definition at line 1029 of file SuiBox.cpp.
References boxType.
Referenced by server::zone::objects::player::sui::SuiBox::setBoxType().
void SuiBoxImplementation::setCallback (SuiCallback * callback)
Definition at line 1099 of file SuiBox.cpp.
References suiCallback.
Referenced by server::zone::objects::player::sui::SuiBox::setCallback().
void SuiBoxImplementation::setCancelButton (bool value, const String & cancelText)
Definition at line 122 of file SuiBoxImplementation.cpp.
References cancelButton, and cancelButtonText.
Referenced by server::zone::objects::player::sui::SuiBox::setCancelButton().
void SuiBoxImplementation::setForceCloseDisabled ()
Definition at line 147 of file SuiBoxImplementation.cpp.
References forceCloseDistance.
Referenced by server::zone::objects::player::sui::SuiBox::setForceCloseDisabled().
void SuiBoxImplementation::setForceCloseDistance (float dist)
Definition at line 143 of file SuiBoxImplementation.cpp.
References forceCloseDistance.
Referenced by server::zone::objects::player::sui::SuiBox::setForceCloseDistance().
void SuiBoxImplementation::setHandlerText (const String & text)
Definition at line 1019 of file SuiBox.cpp.
References handlerStr.
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::generateMessage(), and server::zone::objects::player::sui::SuiBox::setHandlerText().
void SuiBoxImplementation::setOkButton (bool value, const String & okText)
Definition at line 136 of file SuiBoxImplementation.cpp.
References okButton, and okButtonText.
Referenced by server::zone::objects::player::sui::SuiBox::setOkButton().
void SuiBoxImplementation::setOtherButton (bool value, const String & backText)
Definition at line 129 of file SuiBoxImplementation.cpp.
References otherButton, and otherButtonText.
Referenced by server::zone::objects::player::sui::SuiBox::setOtherButton().
void SuiBoxImplementation::setPromptText (const String & name)
Definition at line 1009 of file SuiBox.cpp.
References promptText.
Referenced by server::zone::objects::player::sui::SuiBox::setPromptText(), and server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::SuiCharacterBuilderBoxImplementation().
void SuiBoxImplementation::setPromptTitle (const String & name)
Definition at line 1004 of file SuiBox.cpp.
References promptTitle.
Referenced by server::zone::objects::player::sui::SuiBox::setPromptTitle(), and server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::SuiCharacterBuilderBoxImplementation().
void SuiBoxImplementation::setUsingObject (SceneObject * object)
Definition at line 1094 of file SuiBox.cpp.
References usingObject.
Referenced by server::zone::objects::player::sui::SuiBox::setUsingObject().
void SuiBoxImplementation::setWindowType (unsigned int type)
Definition at line 1024 of file SuiBox.cpp.
References windowType.
Referenced by server::zone::objects::player::sui::SuiBox::setWindowType().
void SuiBoxImplementation::unlock (bool doLock = true) protected
Definition at line 618 of file SuiBox.cpp.
References _this.
void SuiBoxImplementation::wlock (bool doLock = true) protected
Definition at line 610 of file SuiBox.cpp.
References _this.
void SuiBoxImplementation::wlock (ManagedObject * obj) protected
Definition at line 614 of file SuiBox.cpp.
References _this.
void SuiBoxImplementation::writeObject (ObjectOutputStream * stream) virtual
Reimplemented in server::zone::objects::player::sui::listbox::SuiListBoxImplementation, server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation, server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation, server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation, server::zone::objects::player::sui::slotmachinebox::SuiSlotMachineBoxImplementation, server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation, server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation, server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation, and server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation.
Definition at line 742 of file SuiBox.cpp.
References writeObjectMembers().
int SuiBoxImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 749 of file SuiBox.cpp.
References boxID, boxType, cancelButton, cancelButtonText, forceCloseDistance, handlerStr, hasGenerated, hdrOptCount, headerSets, okButton, okButtonText, optionSets, otherButton, otherButtonText, player, promptText, promptTitle, suiCallback, usingObject, and windowType.
Referenced by writeObject(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::writeObjectMembers(), server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation::writeObjectMembers(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::writeObjectMembers(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::writeObjectMembers(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::writeObjectMembers(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::writeObjectMembers(), and server::zone::objects::player::sui::listbox::SuiListBoxImplementation::writeObjectMembers().
Friends And Related Function Documentation
friend class SuiBox friend
Definition at line 470 of file SuiBox.h.
Member Data Documentation
WeakReference<SuiBox*> server::zone::objects::player::sui::SuiBoxImplementation::_this
Definition at line 438 of file SuiBox.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), lock(), rlock(), runlock(), unlock(), and wlock().
const int server::zone::objects::player::sui::SuiBoxImplementation::BANKTIPCONFIRMBOX = 10 static
Definition at line 309 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBoxImplementation::BANKTRANSFERBOX = 5 static
Definition at line 307 of file SuiBox.h.
unsigned int server::zone::objects::player::sui::SuiBoxImplementation::boxID protected
Definition at line 260 of file SuiBox.h.
Referenced by compareTo(), generateCloseMessage(), server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::generateMessage(), server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::generateMessage(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage(), getBoxID(), initialize(), readObjectMember(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::setNextBox(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::setPreviousBox(), and writeObjectMembers().
int server::zone::objects::player::sui::SuiBoxImplementation::boxType protected
Definition at line 282 of file SuiBox.h.
Referenced by readObjectMember(), setBoxType(), SuiBoxImplementation(), and writeObjectMembers().
bool server::zone::objects::player::sui::SuiBoxImplementation::cancelButton protected
Definition at line 268 of file SuiBox.h.
Referenced by server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::generateMessage(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage(), initialize(), readObjectMember(), setCancelButton(), and writeObjectMembers().
String server::zone::objects::player::sui::SuiBoxImplementation::cancelButtonText protected
Definition at line 266 of file SuiBox.h.
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage(), initialize(), readObjectMember(), setCancelButton(), and writeObjectMembers().
const int server::zone::objects::player::sui::SuiBoxImplementation::COLORPICKER = 4 static
Definition at line 305 of file SuiBox.h.
float server::zone::objects::player::sui::SuiBoxImplementation::forceCloseDistance protected
Definition at line 286 of file SuiBox.h.
Referenced by generateFooter(), server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation::generateMessage(), readObjectMember(), setForceCloseDisabled(), setForceCloseDistance(), SuiBoxImplementation(), and writeObjectMembers().
String server::zone::objects::player::sui::SuiBoxImplementation::handlerStr protected
Definition at line 264 of file SuiBox.h.
Referenced by generateHeader(), initialize(), readObjectMember(), setHandlerText(), and writeObjectMembers().
bool server::zone::objects::player::sui::SuiBoxImplementation::hasGenerated protected
Definition at line 294 of file SuiBox.h.
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::generateMessage(), server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage(), hasGeneratedMessage(), initialize(), readObjectMember(), and writeObjectMembers().
int server::zone::objects::player::sui::SuiBoxImplementation::hdrOptCount protected
Definition at line 292 of file SuiBox.h.
Referenced by addHeader(), clearOptions(), generateHeader(), initialize(), readObjectMember(), and writeObjectMembers().
Vector<String> server::zone::objects::player::sui::SuiBoxImplementation::headerSets protected
Definition at line 288 of file SuiBox.h.
Referenced by addHeader(), clearOptions(), generateHeader(), readObjectMember(), and writeObjectMembers().
const int server::zone::objects::player::sui::SuiBoxImplementation::INPUTBOX = 0 static
Definition at line 297 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBoxImplementation::KEYPAD = 21 static
Definition at line 313 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBoxImplementation::LISTBOX = 1 static
Definition at line 299 of file SuiBox.h.
const int server::zone::objects::player::sui::SuiBoxImplementation::MESSAGEBOX = 2 static
Definition at line 301 of file SuiBox.h.
bool server::zone::objects::player::sui::SuiBoxImplementation::okButton protected
Definition at line 272 of file SuiBox.h.
Referenced by server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage(), initialize(), readObjectMember(), setOkButton(), and writeObjectMembers().
String server::zone::objects::player::sui::SuiBoxImplementation::okButtonText protected
Definition at line 270 of file SuiBox.h.
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage(), initialize(), readObjectMember(), setOkButton(), and writeObjectMembers().
Vector<String> server::zone::objects::player::sui::SuiBoxImplementation::optionSets protected
Definition at line 290 of file SuiBox.h.
Referenced by addSetting(), clearOptions(), generateBody(), readObjectMember(), and writeObjectMembers().
bool server::zone::objects::player::sui::SuiBoxImplementation::otherButton protected
Definition at line 276 of file SuiBox.h.
Referenced by server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage(), initialize(), readObjectMember(), setOtherButton(), and writeObjectMembers().
String server::zone::objects::player::sui::SuiBoxImplementation::otherButtonText protected
Definition at line 274 of file SuiBox.h.
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage(), initialize(), readObjectMember(), setOtherButton(), and writeObjectMembers().
ManagedWeakReference<CreatureObject* > server::zone::objects::player::sui::SuiBoxImplementation::player protected
Definition at line 256 of file SuiBox.h.
Referenced by getPlayer(), initialize(), readObjectMember(), SuiBoxImplementation(), and writeObjectMembers().
String server::zone::objects::player::sui::SuiBoxImplementation::promptText protected
Definition at line 280 of file SuiBox.h.
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::generateMessage(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage(), readObjectMember(), setPromptText(), and writeObjectMembers().
String server::zone::objects::player::sui::SuiBoxImplementation::promptTitle protected
Definition at line 278 of file SuiBox.h.
Referenced by server::zone::objects::player::sui::characterbuilderbox::SuiCharacterBuilderBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiMessageBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::messagebox::SuiInputBoxImplementation::generateMessage(), server::zone::objects::player::sui::banktransferbox::SuiBankTransferBoxImplementation::generateMessage(), server::zone::objects::player::sui::listbox::SuiListBoxImplementation::generateMessage(), getPromptTitle(), readObjectMember(), setPromptTitle(), and writeObjectMembers().
const int server::zone::objects::player::sui::SuiBoxImplementation::SLICINGBOX = 20 static
Definition at line 311 of file SuiBox.h.
Reference<SuiCallback* > server::zone::objects::player::sui::SuiBoxImplementation::suiCallback protected
Definition at line 258 of file SuiBox.h.
Referenced by getCallback(), initialize(), readObjectMember(), setCallback(), and writeObjectMembers().
const int server::zone::objects::player::sui::SuiBoxImplementation::TRANSFERBOX = 3 static
Definition at line 303 of file SuiBox.h.
ManagedWeakReference<SceneObject* > server::zone::objects::player::sui::SuiBoxImplementation::usingObject protected
Definition at line 262 of file SuiBox.h.
Referenced by generateFooter(), server::zone::objects::player::sui::colorbox::SuiColorBoxImplementation::generateMessage(), server::zone::objects::player::sui::keypadbox::SuiKeypadBoxImplementation::generateMessage(), getUsingObject(), readObjectMember(), setUsingObject(), and writeObjectMembers().
unsigned int server::zone::objects::player::sui::SuiBoxImplementation::windowType protected
Definition at line 284 of file SuiBox.h.
Referenced by getWindowType(), initialize(), readObjectMember(), setWindowType(), SuiBoxImplementation(), and writeObjectMembers().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/SuiBox.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/SuiBox.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/sui/SuiBoxImplementation.cpp