Core3: PlayerObjectMenuComponent Class Reference
PlayerObjectMenuComponent Class Reference
#include <PlayerObjectMenuComponent.h>
Public Member Functions
virtual void fillObjectMenuResponse (SceneObject *sceneObject, ObjectMenuResponse *menuResponse, CreatureObject *player)
virtual int handleObjectMenuSelect (SceneObject *sceneObject, CreatureObject *player, byte selectedID)
Detailed Description
Definition at line 13 of file PlayerObjectMenuComponent.h.
Member Function Documentation
void PlayerObjectMenuComponent::fillObjectMenuResponse (SceneObject * sceneObject, ObjectMenuResponse * menuResponse, CreatureObject * player) virtual
Fills the radial options, needs to be overriden
Precondition
{ this object is locked }
Postcondition
{ this object is locked, menuResponse is complete}
Parameters
menuResponse ObjectMenuResponse that will be sent to the client
Reimplemented from ObjectMenuComponent.
Definition at line 53 of file PlayerObjectMenuComponent.cpp.
References server::zone::packets::object::ObjectMenuResponse::addRadialMenuItem(), server::zone::objects::creature::CreatureObject::getGroup(), server::zone::objects::scene::SceneObject::isCreatureObject(), server::zone::objects::creature::CreatureObject::isDancing(), server::zone::objects::creature::CreatureObject::isListening(), server::zone::objects::creature::CreatureObject::isPlayingMusic(), and server::zone::objects::creature::CreatureObject::isWatching().
int PlayerObjectMenuComponent::handleObjectMenuSelect (SceneObject * sceneObject, CreatureObject * player, byte selectedID) virtual
Handles the radial selection sent by the client, must be overriden by inherited objects
Precondition
{ this object is locked, player is locked }
Postcondition
{ this object is locked, player is locked }
Parameters
player PlayerCreature that selected the option
selectedID selected menu id
Returns
0 if successfull
Reimplemented from ObjectMenuComponent.
Definition at line 86 of file PlayerObjectMenuComponent.cpp.
References server::zone::objects::creature::CreatureObject::executeObjectControllerAction(), server::zone::objects::scene::SceneObject::getObjectID(), and server::zone::objects::creature::CreatureObject::getPlayerObject().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/components/PlayerObjectMenuComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/player/components/PlayerObjectMenuComponent.cpp