Core3: MinefieldContainerComponent Class Reference
MinefieldContainerComponent Class Reference
#include <MinefieldContainerComponent.h>
Public Member Functions
bool checkContainerPermission (SceneObject *sceneObject, CreatureObject *creature, uint16 permission)
int canAddObject (SceneObject *sceneObject, SceneObject *object, int containmentType, String &errorDescription)
int notifyObjectInserted (SceneObject *sceneObject, SceneObject *object)
int notifyObjectRemoved (SceneObject *sceneObject, SceneObject *object, SceneObject *destination)
Public Member Functions inherited from ContainerComponent
virtual bool transferObject (SceneObject *sceneObject, SceneObject *object, int containmentType, bool notifyClient=false, bool allowOverflow=false)
virtual bool removeObject (SceneObject *sceneObject, SceneObject *object, SceneObject *destination, bool notifyClient)
Detailed Description
Definition at line 13 of file MinefieldContainerComponent.h.
Member Function Documentation
int MinefieldContainerComponent::canAddObject (SceneObject * sceneObject, SceneObject * object, int containmentType, String & errorDescription) virtual
Evaluates if this object has the necessary free slots to be able to add the specified SceneObject
Precondition
{ this object is locked, object is locked }
Postcondition
{this object is locked, object is locked }
Parameters
object SceneObject that will be checked
error error string that the player will receive on error
Returns
returns 0 on success, or error code
Reimplemented from ContainerComponent.
Definition at line 42 of file MinefieldContainerComponent.cpp.
References server::zone::objects::scene::SceneObject::getContainerObjectsSize(), server::zone::objects::scene::SceneObject::getGameObjectType(), and SceneObjectType::MINE.
bool MinefieldContainerComponent::checkContainerPermission (SceneObject * sceneObject, CreatureObject * creature, uint16 permission) virtual
Reimplemented from ContainerComponent.
Definition at line 11 of file MinefieldContainerComponent.cpp.
References ContainerComponent::checkContainerPermission(), server::zone::objects::tangible::TangibleObject::getFaction(), server::zone::objects::player::PlayerObject::getFactionStatus(), server::zone::objects::creature::CreatureObject::getPlayerObject(), server::zone::objects::structure::StructureObject::isOnAdminList(), server::zone::objects::scene::SceneObject::isTangibleObject(), and FactionStatus::ONLEAVE.
int MinefieldContainerComponent::notifyObjectInserted (SceneObject * sceneObject, SceneObject * object) virtual
Is called when this object has been inserted with an object
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 62 of file MinefieldContainerComponent.cpp.
References CreatureFlag::ATTACKABLE, and ContainerComponent::notifyObjectInserted().
int MinefieldContainerComponent::notifyObjectRemoved (SceneObject * sceneObject, SceneObject * object, SceneObject * destination) virtual
Is called when an object was removed
Parameters
object object that has been inserted
Reimplemented from ContainerComponent.
Definition at line 79 of file MinefieldContainerComponent.cpp.
References CreatureFlag::ATTACKABLE, and ContainerComponent::notifyObjectRemoved().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/MinefieldContainerComponent.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/installation/components/MinefieldContainerComponent.cpp