Core3: GuildSponsorVerifySuiCallback Class Reference
GuildSponsorVerifySuiCallback Class Reference
#include <GuildSponsorVerifySuiCallback.h>
Public Member Functions
GuildSponsorVerifySuiCallback (ZoneServer *server)
void run (CreatureObject *player, SuiBox *suiBox, bool cancelPressed, Vector< UnicodeString > *args)
Public Member Functions inherited from server::zone::objects::player::sui::SuiCallback
SuiCallback (ZoneServer *serv)
Additional Inherited Members
Protected Attributes inherited from server::zone::objects::player::sui::SuiCallback
ManagedReference< ZoneServer * > server
Detailed Description
Definition at line 15 of file GuildSponsorVerifySuiCallback.h.
Constructor & Destructor Documentation
GuildSponsorVerifySuiCallback::GuildSponsorVerifySuiCallback (ZoneServer * server) inline
Definition at line 17 of file GuildSponsorVerifySuiCallback.h.
Member Function Documentation
void GuildSponsorVerifySuiCallback::run (CreatureObject * player, SuiBox * suiBox, bool cancelPressed, Vector< UnicodeString > * args) inline virtual
Parameters
player The player that this suibox is assigned to.
suiBox The actual SuiBox object.
cancelPressed Was the cancel button pressed, or was the sui box closed via a similar method. (this might actually be more of a dialogResult type variable)
args A vector of UnicodeStrings containing the arguments passed to the sui box from the client.
Implements server::zone::objects::player::sui::SuiCallback.
Definition at line 21 of file GuildSponsorVerifySuiCallback.h.
References server::zone::objects::creature::CreatureObject::getGuildObject(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::player::sui::SuiBox::getUsingObject(), server::zone::objects::player::sui::SuiBox::isMessageBox(), server::zone::objects::creature::CreatureObject::sendSystemMessage(), server::zone::objects::player::sui::SuiCallback::server, server::zone::objects::scene::variables::StringId::setStringId(), and server::chat::StringIdChatParameter::setTU().
The documentation for this class was generated from the following file:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/objects/guild/sui/GuildSponsorVerifySuiCallback.h