Core3: server::zone::managers::auction::AuctionsMapImplementation Class Reference
server::zone::managers::auction::AuctionsMapImplementation Class Reference
#include <AuctionsMap.h>
Public Member Functions
AuctionsMapImplementation ()
AuctionsMapImplementation (DummyConstructorParameter *param)
int addItem (CreatureObject *player, SceneObject *vendor, AuctionItem *item)
void deleteItem (SceneObject *vendor, AuctionItem *item)
AuctionItem * getItem (unsigned long long id)
bool containsItem (unsigned long long id)
TerminalListVector getVendorTerminalData (const String &planet, const String &region, SceneObject *vendor)
TerminalListVector getBazaarTerminalData (const String &planet, const String &region, SceneObject *vendor)
int getVendorItemCount (SceneObject *vendor)
void deleteTerminalItems (SceneObject *vendor)
int getCommodityCount (CreatureObject *player)
void updateUID (SceneObject *vendor, const String &oldUID, const String &newUID)
void updateVendorSearch (SceneObject *vendor, bool enabled)
void addToCommodityLimit (AuctionItem *item)
void removeFromCommodityLimit (AuctionItem *item)
int getBazaarCount ()
int getVendorCount ()
int getTotalItemCount ()
operator const AuctionsMap * ()
DistributedObjectStub * _getStub ()
virtual void readObject (ObjectInputStream *stream)
virtual void writeObject (ObjectOutputStream *stream)
Public Attributes
WeakReference< AuctionsMap * > _this
Protected Member Functions
virtual ~AuctionsMapImplementation ()
void finalize ()
void _initializeImplementation ()
void _setStub (DistributedObjectStub *stub)
void lock (bool doLock=true)
void lock (ManagedObject *obj)
void rlock (bool doLock=true)
void wlock (bool doLock=true)
void wlock (ManagedObject *obj)
void unlock (bool doLock=true)
void runlock (bool doLock=true)
void _serializationHelperMethod ()
bool readObjectMember (ObjectInputStream *stream, const uint32 &nameHashCode)
int writeObjectMembers (ObjectOutputStream *stream)
Protected Attributes
AuctionTerminalMap vendorItemsForSale
AuctionTerminalMap bazaarItemsForSale
VectorMap< unsigned long long,
ManagedReference< AuctionItem * > > allItems
Logger logger
Private Member Functions
int addVendorItem (CreatureObject *player, const String &planet, const String &region, SceneObject *vendor, AuctionItem *item)
int addBazaarItem (CreatureObject *player, const String &planet, const String &region, SceneObject *vendor, AuctionItem *item)
void removeVendorItem (SceneObject *vendor, AuctionItem *item)
void removeBazaarItem (SceneObject *vendor, AuctionItem *item)
void sendVendorUpdateMail (SceneObject *vendor, bool isEmpty)
Private Attributes
CommoditiesLimit commoditiesLimit
Friends
class AuctionsMap
Detailed Description
Definition at line 124 of file AuctionsMap.h.
Constructor & Destructor Documentation
AuctionsMapImplementation::AuctionsMapImplementation ()
Definition at line 394 of file AuctionsMap.cpp.
References _initializeImplementation(), allItems, commoditiesLimit, and logger.
AuctionsMapImplementation::AuctionsMapImplementation (DummyConstructorParameter * param)
Definition at line 268 of file AuctionsMap.cpp.
References _initializeImplementation().
AuctionsMapImplementation::~AuctionsMapImplementation () protected virtual
Definition at line 273 of file AuctionsMap.cpp.
Member Function Documentation
DistributedObjectStub * AuctionsMapImplementation::_getStub ()
Definition at line 293 of file AuctionsMap.cpp.
References _this.
void AuctionsMapImplementation::_initializeImplementation () protected
Definition at line 280 of file AuctionsMap.cpp.
References _serializationHelperMethod(), and _this.
Referenced by AuctionsMapImplementation().
void AuctionsMapImplementation::_serializationHelperMethod () protected
Definition at line 329 of file AuctionsMap.cpp.
Referenced by _initializeImplementation().
void AuctionsMapImplementation::_setStub (DistributedObjectStub * stub) protected
Definition at line 288 of file AuctionsMap.cpp.
References _this.
Referenced by server::zone::managers::auction::AuctionsMap::AuctionsMap().
int AuctionsMapImplementation::addBazaarItem (CreatureObject * player, const String & planet, const String & region, SceneObject * vendor, AuctionItem * item) private
Definition at line 79 of file AuctionsMapImplementation.cpp.
References _this, allItems, ItemSoldMessage::ALREADYFORSALE, bazaarItemsForSale, AuctionTerminalMap::createTerminalListing(), server::zone::objects::auction::AuctionItem::getAuctionedItemObjectID(), server::zone::objects::scene::SceneObject::getObjectID(), ItemSoldMessage::INVALIDAUCTIONER, ItemSoldMessage::SUCCESS, ItemSoldMessage::UNKNOWNERROR, and ItemSoldMessage::VENDORNOTWORKING.
Referenced by addItem().
int AuctionsMapImplementation::addItem (CreatureObject * player, SceneObject * vendor, AuctionItem * item)
Definition at line 21 of file AuctionsMapImplementation.cpp.
References addBazaarItem(), addVendorItem(), server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::scene::SceneObject::isBazaarTerminal(), and ItemSoldMessage::VENDORNOTWORKING.
Referenced by server::zone::managers::auction::AuctionsMap::addItem().
void AuctionsMapImplementation::addToCommodityLimit (AuctionItem * item)
Definition at line 299 of file AuctionsMapImplementation.cpp.
References commoditiesLimit, and server::zone::objects::auction::AuctionItem::getOwnerID().
Referenced by server::zone::managers::auction::AuctionsMap::addToCommodityLimit().
int AuctionsMapImplementation::addVendorItem (CreatureObject * player, const String & planet, const String & region, SceneObject * vendor, AuctionItem * item) private
Definition at line 38 of file AuctionsMapImplementation.cpp.
References _this, allItems, ItemSoldMessage::ALREADYFORSALE, AuctionTerminalMap::createTerminalListing(), server::zone::objects::auction::AuctionItem::getAuctionedItemObjectID(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getObjectID(), ItemSoldMessage::INVALIDAUCTIONER, VendorDataComponent::isVendorSearchEnabled(), sendVendorUpdateMail(), ItemSoldMessage::SUCCESS, ItemSoldMessage::UNKNOWNERROR, vendorItemsForSale, and ItemSoldMessage::VENDORNOTWORKING.
Referenced by addItem().
bool AuctionsMapImplementation::containsItem (unsigned long long id)
Definition at line 418 of file AuctionsMap.cpp.
References _this, and allItems.
Referenced by server::zone::managers::auction::AuctionsMap::containsItem().
void AuctionsMapImplementation::deleteItem (SceneObject * vendor, AuctionItem * item)
Definition at line 103 of file AuctionsMapImplementation.cpp.
References _this, allItems, server::zone::objects::auction::AuctionItem::getAuctionedItemObjectID(), server::zone::objects::scene::SceneObject::isBazaarTerminal(), removeBazaarItem(), and removeVendorItem().
Referenced by server::zone::managers::auction::AuctionsMap::deleteItem().
void AuctionsMapImplementation::deleteTerminalItems (SceneObject * vendor)
Definition at line 188 of file AuctionsMapImplementation.cpp.
References _this, allItems, AuctionTerminalMap::dropTerminalListing(), server::zone::objects::scene::SceneObject::getObjectID(), server::zone::objects::scene::SceneObject::isBazaarTerminal(), and vendorItemsForSale.
Referenced by server::zone::managers::auction::AuctionsMap::deleteTerminalItems().
void AuctionsMapImplementation::finalize () protected
Definition at line 277 of file AuctionsMap.cpp.
int AuctionsMapImplementation::getBazaarCount ()
Definition at line 424 of file AuctionsMap.cpp.
References _this, and bazaarItemsForSale.
Referenced by server::zone::managers::auction::AuctionsMap::getBazaarCount().
TerminalListVector AuctionsMapImplementation::getBazaarTerminalData (const String & planet, const String & region, SceneObject * vendor)
Definition at line 166 of file AuctionsMapImplementation.cpp.
References _this, bazaarItemsForSale, and AuctionTerminalMap::getTerminalData().
Referenced by server::zone::managers::auction::AuctionsMap::getBazaarTerminalData().
int AuctionsMapImplementation::getCommodityCount (CreatureObject * player)
Definition at line 279 of file AuctionsMapImplementation.cpp.
References commoditiesLimit, and server::zone::objects::scene::SceneObject::getObjectID().
Referenced by server::zone::managers::auction::AuctionsMap::getCommodityCount().
AuctionItem * AuctionsMapImplementation::getItem (unsigned long long id)
Definition at line 412 of file AuctionsMap.cpp.
References _this, and allItems.
Referenced by server::zone::managers::auction::AuctionsMap::getItem().
int AuctionsMapImplementation::getTotalItemCount ()
Definition at line 435 of file AuctionsMap.cpp.
References allItems.
Referenced by server::zone::managers::auction::AuctionsMap::getTotalItemCount().
int AuctionsMapImplementation::getVendorCount ()
Definition at line 430 of file AuctionsMap.cpp.
References vendorItemsForSale.
Referenced by server::zone::managers::auction::AuctionsMap::getVendorCount().
int AuctionsMapImplementation::getVendorItemCount (SceneObject * vendor)
Definition at line 172 of file AuctionsMapImplementation.cpp.
References _this, server::zone::objects::scene::SceneObject::getObjectID(), logger, and vendorItemsForSale.
Referenced by server::zone::managers::auction::AuctionsMap::getVendorItemCount().
TerminalListVector AuctionsMapImplementation::getVendorTerminalData (const String & planet, const String & region, SceneObject * vendor)
Definition at line 160 of file AuctionsMapImplementation.cpp.
References _this, AuctionTerminalMap::getTerminalData(), and vendorItemsForSale.
Referenced by server::zone::managers::auction::AuctionsMap::getVendorTerminalData().
void AuctionsMapImplementation::lock (bool doLock = true) protected
Definition at line 301 of file AuctionsMap.cpp.
References _this.
void AuctionsMapImplementation::lock (ManagedObject * obj) protected
Definition at line 305 of file AuctionsMap.cpp.
References _this.
AuctionsMapImplementation::operator const AuctionsMap * ()
Definition at line 297 of file AuctionsMap.cpp.
void AuctionsMapImplementation::readObject (ObjectInputStream * stream) virtual
Definition at line 336 of file AuctionsMap.cpp.
References readObjectMember().
bool AuctionsMapImplementation::readObjectMember (ObjectInputStream * stream, const uint32 & nameHashCode) protected
Definition at line 355 of file AuctionsMap.cpp.
References commoditiesLimit.
Referenced by readObject().
void AuctionsMapImplementation::removeBazaarItem (SceneObject * vendor, AuctionItem * item) private
Definition at line 142 of file AuctionsMapImplementation.cpp.
References _this, bazaarItemsForSale, server::zone::objects::scene::SceneObject::getObjectID(), and logger.
Referenced by deleteItem().
void AuctionsMapImplementation::removeFromCommodityLimit (AuctionItem * item)
Definition at line 314 of file AuctionsMapImplementation.cpp.
References commoditiesLimit, and server::zone::objects::auction::AuctionItem::getOwnerID().
Referenced by server::zone::managers::auction::AuctionsMap::removeFromCommodityLimit().
void AuctionsMapImplementation::removeVendorItem (SceneObject * vendor, AuctionItem * item) private
Definition at line 118 of file AuctionsMapImplementation.cpp.
References _this, server::zone::objects::scene::SceneObject::getObjectID(), logger, sendVendorUpdateMail(), and vendorItemsForSale.
Referenced by deleteItem().
void AuctionsMapImplementation::rlock (bool doLock = true) protected
Definition at line 309 of file AuctionsMap.cpp.
References _this.
void AuctionsMapImplementation::runlock (bool doLock = true) protected
Definition at line 325 of file AuctionsMap.cpp.
References _this.
void AuctionsMapImplementation::sendVendorUpdateMail (SceneObject * vendor, bool isEmpty) private
Definition at line 208 of file AuctionsMapImplementation.cpp.
References server::zone::ZoneServer::getChatManager(), server::zone::objects::scene::SceneObject::getDataObjectComponent(), server::zone::objects::scene::SceneObject::getDisplayedName(), server::zone::ZoneServer::getObject(), VendorDataComponent::getOwnerId(), server::zone::objects::scene::SceneObject::getZoneServer(), server::zone::objects::scene::SceneObject::isVendor(), VendorDataComponent::setEmpty(), and server::chat::StringIdChatParameter::setTO().
Referenced by addVendorItem(), and removeVendorItem().
void AuctionsMapImplementation::unlock (bool doLock = true) protected
Definition at line 321 of file AuctionsMap.cpp.
References _this.
void AuctionsMapImplementation::updateUID (SceneObject * vendor, const String & oldUID, const String & newUID)
Definition at line 244 of file AuctionsMapImplementation.cpp.
References _this, bazaarItemsForSale, server::zone::objects::scene::SceneObject::getCityRegion(), server::zone::objects::scene::SceneObject::getZone(), server::zone::Zone::getZoneName(), server::zone::objects::scene::SceneObject::isBazaarTerminal(), server::zone::objects::scene::SceneObject::isVendor(), logger, AuctionTerminalMap::updateTerminalUID(), and vendorItemsForSale.
Referenced by server::zone::managers::auction::AuctionsMap::updateUID().
void AuctionsMapImplementation::updateVendorSearch (SceneObject * vendor, bool enabled)
Definition at line 270 of file AuctionsMapImplementation.cpp.
References _this, AuctionTerminalMap::updateTerminalSearch(), and vendorItemsForSale.
Referenced by server::zone::managers::auction::AuctionsMap::updateVendorSearch().
void AuctionsMapImplementation::wlock (bool doLock = true) protected
Definition at line 313 of file AuctionsMap.cpp.
References _this.
void AuctionsMapImplementation::wlock (ManagedObject * obj) protected
Definition at line 317 of file AuctionsMap.cpp.
References _this.
void AuctionsMapImplementation::writeObject (ObjectOutputStream * stream) virtual
Definition at line 369 of file AuctionsMap.cpp.
References writeObjectMembers().
int AuctionsMapImplementation::writeObjectMembers (ObjectOutputStream * stream) protected
Definition at line 376 of file AuctionsMap.cpp.
References commoditiesLimit.
Referenced by writeObject().
Friends And Related Function Documentation
friend class AuctionsMap friend
Definition at line 225 of file AuctionsMap.h.
Member Data Documentation
WeakReference<AuctionsMap*> server::zone::managers::auction::AuctionsMapImplementation::_this
Definition at line 191 of file AuctionsMap.h.
Referenced by _getStub(), _initializeImplementation(), _setStub(), addBazaarItem(), addVendorItem(), containsItem(), deleteItem(), deleteTerminalItems(), getBazaarCount(), getBazaarTerminalData(), getItem(), getVendorItemCount(), getVendorTerminalData(), lock(), removeBazaarItem(), removeVendorItem(), rlock(), runlock(), unlock(), updateUID(), updateVendorSearch(), and wlock().
VectorMap<unsigned long long, ManagedReference<AuctionItem* > > server::zone::managers::auction::AuctionsMapImplementation::allItems protected
Definition at line 130 of file AuctionsMap.h.
Referenced by addBazaarItem(), addVendorItem(), AuctionsMapImplementation(), containsItem(), deleteItem(), deleteTerminalItems(), getItem(), and getTotalItemCount().
AuctionTerminalMap server::zone::managers::auction::AuctionsMapImplementation::bazaarItemsForSale protected
Definition at line 128 of file AuctionsMap.h.
Referenced by addBazaarItem(), getBazaarCount(), getBazaarTerminalData(), removeBazaarItem(), and updateUID().
CommoditiesLimit server::zone::managers::auction::AuctionsMapImplementation::commoditiesLimit private
Definition at line 133 of file AuctionsMap.h.
Referenced by addToCommodityLimit(), AuctionsMapImplementation(), getCommodityCount(), readObjectMember(), removeFromCommodityLimit(), and writeObjectMembers().
Logger server::zone::managers::auction::AuctionsMapImplementation::logger protected
Definition at line 136 of file AuctionsMap.h.
Referenced by AuctionsMapImplementation(), getVendorItemCount(), removeBazaarItem(), removeVendorItem(), and updateUID().
AuctionTerminalMap server::zone::managers::auction::AuctionsMapImplementation::vendorItemsForSale protected
Definition at line 126 of file AuctionsMap.h.
Referenced by addVendorItem(), deleteTerminalItems(), getVendorCount(), getVendorItemCount(), getVendorTerminalData(), removeVendorItem(), updateUID(), and updateVendorSearch().
The documentation for this class was generated from the following files:
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionsMap.h
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionsMap.cpp
/Users/victor/git/Core3Mda/MMOCoreORB/src/server/zone/managers/auction/AuctionsMapImplementation.cpp