Core3: /Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/mongoose/mongoose.c File Reference
mongoose.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <signal.h>
#include <fcntl.h>
#include <time.h>
#include <stdlib.h>
#include <stdarg.h>
#include <assert.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>
#include <stddef.h>
#include <stdio.h>
#include <sys/wait.h>
#include <sys/socket.h>
#include <sys/select.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include <stdint.h>
#include <inttypes.h>
#include <netdb.h>
#include <pwd.h>
#include <unistd.h>
#include <dirent.h>
#include <dlfcn.h>
#include <pthread.h>
#include "mongoose.h"
Classes
struct ssl_func
struct usa
struct vec
struct mgstat
struct socket
struct mg_context
struct mg_connection
struct MD5Context
struct ah
struct de
struct cgi_env_block
Macros
#define _XOPEN_SOURCE 600
#define _LARGEFILE_SOURCE
#define __STDC_FORMAT_MACROS
#define SSL_LIB "libssl.so"
#define CRYPTO_LIB "libcrypto.so"
#define DIRSEP '/'
#define IS_DIRSEP_CHAR(c) ((c) == '/')
#define O_BINARY 0
#define closesocket(a) close(a)
#define mg_fopen(x, y) fopen(x, y)
#define mg_mkdir(x, y) mkdir(x, y)
#define mg_remove(x) remove(x)
#define mg_rename(x, y) rename(x, y)
#define ERRNO errno
#define INVALID_SOCKET (-1)
#define INT64_FMT PRId64
#define WINCDECL
#define MONGOOSE_VERSION "3.0"
#define PASSWORDS_FILE_NAME ".htpasswd"
#define CGI_ENVIRONMENT_SIZE 4096
#define MAX_CGI_ENVIR_VARS 64
#define ARRAY_SIZE(array) (sizeof(array) / sizeof(array[0]))
#define DEBUG_TRACE(x)
#define SSL_ERROR_WANT_READ 2
#define SSL_ERROR_WANT_WRITE 3
#define SSL_FILETYPE_PEM 1
#define CRYPTO_LOCK 1
#define SSL_free (* (void (*)(SSL *)) ssl_sw[0].ptr)
#define SSL_accept (* (int (*)(SSL *)) ssl_sw[1].ptr)
#define SSL_connect (* (int (*)(SSL *)) ssl_sw[2].ptr)
#define SSL_read (* (int (*)(SSL *, void *, int)) ssl_sw[3].ptr)
#define SSL_write (* (int (*)(SSL *, const void *,int)) ssl_sw[4].ptr)
#define SSL_get_error (* (int (*)(SSL *, int)) ssl_sw[5].ptr)
#define SSL_set_fd (* (int (*)(SSL *, SOCKET)) ssl_sw[6].ptr)
#define SSL_new (* (SSL * (*)(SSL_CTX *)) ssl_sw[7].ptr)
#define SSL_CTX_new (* (SSL_CTX * (*)(SSL_METHOD *)) ssl_sw[8].ptr)
#define SSLv23_server_method (* (SSL_METHOD * (*)(void)) ssl_sw[9].ptr)
#define SSL_library_init (* (int (*)(void)) ssl_sw[10].ptr)
#define SSL_CTX_use_PrivateKey_file
#define SSL_CTX_use_certificate_file
#define SSL_CTX_set_default_passwd_cb (* (void (*)(SSL_CTX *, mg_callback_t)) ssl_sw[13].ptr)
#define SSL_CTX_free (* (void (*)(SSL_CTX *)) ssl_sw[14].ptr)
#define SSL_load_error_strings (* (void (*)(void)) ssl_sw[15].ptr)
#define SSL_CTX_use_certificate_chain_file (* (int (*)(SSL_CTX *, const char *)) ssl_sw[16].ptr)
#define CRYPTO_num_locks (* (int (*)(void)) crypto_sw[0].ptr)
#define CRYPTO_set_locking_callback (* (void (*)(void (*)(int, int, const char *, int))) crypto_sw[1].ptr)
#define CRYPTO_set_id_callback (* (void (*)(unsigned long (*)(void))) crypto_sw[2].ptr)
#define ERR_get_error (* (unsigned long (*)(void)) crypto_sw[3].ptr)
#define ERR_error_string (* (char * (*)(unsigned long,char *)) crypto_sw[4].ptr)
#define ENTRIES_PER_CONFIG_OPTION 3
#define HEXTOI(x) (isdigit(x) ? x - '0' : x - 'W')
#define F1(x, y, z) (z ^ (x & (y ^ z)))
#define F2(x, y, z) F1(z, x, y)
#define F3(x, y, z) (x ^ y ^ z)
#define F4(x, y, z) (y ^ (x | ~z))
#define MD5STEP(f, w, x, y, z, data, s) (w += f(x, y, z) + data, w = w<<s | w>>(32-s), w += x)
Typedefs
typedef int SOCKET
typedef void *(* mg_thread_func_t)(void *)
typedef struct ssl_st SSL
typedef struct ssl_method_st SSL_METHOD
typedef struct ssl_ctx_st SSL_CTX
typedef struct MD5Context MD5_CTX
Enumerations
enum {
CGI_EXTENSIONS, CGI_ENVIRONMENT, PUT_DELETE_PASSWORDS_FILE, CGI_INTERPRETER,
PROTECT_URI, AUTHENTICATION_DOMAIN, SSI_EXTENSIONS, ACCESS_LOG_FILE,
SSL_CHAIN_FILE, ENABLE_DIRECTORY_LISTING, ERROR_LOG_FILE, GLOBAL_PASSWORDS_FILE,
INDEX_FILES, ENABLE_KEEP_ALIVE, ACCESS_CONTROL_LIST, MAX_REQUEST_SIZE,
EXTRA_MIME_TYPES, LISTENING_PORTS, DOCUMENT_ROOT, SSL_CERTIFICATE,
NUM_THREADS, RUN_AS_USER, NUM_OPTIONS
}
Functions
const char ** mg_get_valid_option_names (void)
const char * mg_get_option (const struct mg_context *ctx, const char *name)
const char * mg_version (void)
const char * mg_get_header (const struct mg_connection *conn, const char *name)
int mg_read (struct mg_connection *conn, void *buf, size_t len)
int mg_write (struct mg_connection *conn, const void *buf, size_t len)
int mg_printf (struct mg_connection *conn, const char *fmt,...)
int mg_get_var (const char *buf, size_t buf_len, const char *name, char *dst, size_t dst_len)
int mg_get_cookie (const struct mg_connection *conn, const char *cookie_name, char *dst, size_t dst_size)
void mg_md5 (char *buf,...)
int mg_modify_passwords_file (const char *fname, const char *domain, const char *user, const char *pass)
void mg_stop (struct mg_context *ctx)
struct mg_context * mg_start (mg_callback_t user_callback, void *user_data, const char **options)
Macro Definition Documentation
#define __STDC_FORMAT_MACROS
Definition at line 28 of file mongoose.c.
#define _LARGEFILE_SOURCE
Definition at line 27 of file mongoose.c.
#define _XOPEN_SOURCE 600
Definition at line 26 of file mongoose.c.
#define ARRAY_SIZE (array) (sizeof(array) / sizeof(array[0]))
Definition at line 224 of file mongoose.c.
#define CGI_ENVIRONMENT_SIZE 4096
Definition at line 222 of file mongoose.c.
#define closesocket (a) close(a)
Definition at line 205 of file mongoose.c.
#define CRYPTO_LIB "libcrypto.so"
Definition at line 197 of file mongoose.c.
#define CRYPTO_LOCK 1
Definition at line 260 of file mongoose.c.
#define CRYPTO_num_locks (* (int (*)(void)) crypto_sw[0].ptr)
Definition at line 314 of file mongoose.c.
#define CRYPTO_set_id_callback (* (void (*)(unsigned long (*)(void))) crypto_sw[2].ptr)
Definition at line 317 of file mongoose.c.
#define CRYPTO_set_locking_callback (* (void (*)(void (*)(int, int, const char *, int))) crypto_sw[1].ptr)
Definition at line 315 of file mongoose.c.
#define DEBUG_TRACE (x)
Definition at line 238 of file mongoose.c.
Referenced by mg_read(), and mg_start().
#define DIRSEP '/'
Definition at line 200 of file mongoose.c.
#define ENTRIES_PER_CONFIG_OPTION 3
Definition at line 433 of file mongoose.c.
Referenced by mg_start().
#define ERR_error_string (* (char * (*)(unsigned long,char *)) crypto_sw[4].ptr)
Definition at line 320 of file mongoose.c.
#define ERR_get_error (* (unsigned long (*)(void)) crypto_sw[3].ptr)
Definition at line 319 of file mongoose.c.
#define ERRNO errno
Definition at line 210 of file mongoose.c.
Referenced by mg_start().
#define F1 (x, y, z) (z ^ (x & (y ^ z)))
Definition at line 1828 of file mongoose.c.
#define F2 (x, y, z) F1(z, x, y)
Definition at line 1829 of file mongoose.c.
Referenced by SimplexNoise::noise().
#define F3 (x, y, z) (x ^ y ^ z)
Definition at line 1830 of file mongoose.c.
Referenced by SimplexNoise::noise().
#define F4 (x, y, z) (y ^ (x | ~z))
Definition at line 1831 of file mongoose.c.
Referenced by SimplexNoise::noise().
#define HEXTOI (x) (isdigit(x) ? x - '0' : x - 'W')
#define INT64_FMT PRId64
Definition at line 212 of file mongoose.c.
#define INVALID_SOCKET (-1)
Definition at line 211 of file mongoose.c.
#define IS_DIRSEP_CHAR (c) ((c) == '/')
Definition at line 201 of file mongoose.c.
#define MAX_CGI_ENVIR_VARS 64
Definition at line 223 of file mongoose.c.
#define MD5STEP (f, w, x, y, z, data, s) (w += f(x, y, z) + data, w = w<<s | w>>(32-s), w += x)
Definition at line 1833 of file mongoose.c.
#define mg_fopen (x, y) fopen(x, y)
Definition at line 206 of file mongoose.c.
Referenced by mg_modify_passwords_file().
#define mg_mkdir (x, y) mkdir(x, y)
Definition at line 207 of file mongoose.c.
#define mg_remove (x) remove(x)
Definition at line 208 of file mongoose.c.
Referenced by mg_modify_passwords_file().
#define mg_rename (x, y) rename(x, y)
Definition at line 209 of file mongoose.c.
Referenced by mg_modify_passwords_file().
#define MONGOOSE_VERSION "3.0"
Definition at line 220 of file mongoose.c.
Referenced by mg_version().
#define O_BINARY 0
Definition at line 203 of file mongoose.c.
#define PASSWORDS_FILE_NAME ".htpasswd"
Definition at line 221 of file mongoose.c.
#define SSL_accept (* (int (*)(SSL *)) ssl_sw[1].ptr)
Definition at line 293 of file mongoose.c.
#define SSL_connect (* (int (*)(SSL *)) ssl_sw[2].ptr)
Definition at line 294 of file mongoose.c.
#define SSL_CTX_free (* (void (*)(SSL_CTX *)) ssl_sw[14].ptr)
Definition at line 309 of file mongoose.c.
#define SSL_CTX_new (* (SSL_CTX * (*)(SSL_METHOD *)) ssl_sw[8].ptr)
Definition at line 300 of file mongoose.c.
#define SSL_CTX_set_default_passwd_cb (* (void (*)(SSL_CTX *, mg_callback_t)) ssl_sw[13].ptr)
Definition at line 307 of file mongoose.c.
#define SSL_CTX_use_certificate_chain_file (* (int (*)(SSL_CTX *, const char *)) ssl_sw[16].ptr)
Definition at line 311 of file mongoose.c.
#define SSL_CTX_use_certificate_file
Value:
(* (int (*)(SSL_CTX *, \
        const char *, int)) ssl_sw[12].ptr)
Definition at line 305 of file mongoose.c.
#define SSL_CTX_use_PrivateKey_file
Value:
(* (int (*)(SSL_CTX *, \
        const char *, int)) ssl_sw[11].ptr)
Definition at line 303 of file mongoose.c.
#define SSL_ERROR_WANT_READ 2
Definition at line 257 of file mongoose.c.
#define SSL_ERROR_WANT_WRITE 3
Definition at line 258 of file mongoose.c.
#define SSL_FILETYPE_PEM 1
Definition at line 259 of file mongoose.c.
#define SSL_free (* (void (*)(SSL *)) ssl_sw[0].ptr)
Definition at line 292 of file mongoose.c.
#define SSL_get_error (* (int (*)(SSL *, int)) ssl_sw[5].ptr)
Definition at line 297 of file mongoose.c.
#define SSL_LIB "libssl.so"
Definition at line 194 of file mongoose.c.
#define SSL_library_init (* (int (*)(void)) ssl_sw[10].ptr)
Definition at line 302 of file mongoose.c.
#define SSL_load_error_strings (* (void (*)(void)) ssl_sw[15].ptr)
Definition at line 310 of file mongoose.c.
#define SSL_new (* (SSL * (*)(SSL_CTX *)) ssl_sw[7].ptr)
Definition at line 299 of file mongoose.c.
#define SSL_read (* (int (*)(SSL *, void *, int)) ssl_sw[3].ptr)
Definition at line 295 of file mongoose.c.
#define SSL_set_fd (* (int (*)(SSL *, SOCKET)) ssl_sw[6].ptr)
Definition at line 298 of file mongoose.c.
#define SSL_write (* (int (*)(SSL *, const void *,int)) ssl_sw[4].ptr)
Definition at line 296 of file mongoose.c.
#define SSLv23_server_method (* (SSL_METHOD * (*)(void)) ssl_sw[9].ptr)
Definition at line 301 of file mongoose.c.
#define WINCDECL
Definition at line 214 of file mongoose.c.
Typedef Documentation
typedef struct MD5Context MD5_CTX
typedef void*(* mg_thread_func_t)(void *)
Definition at line 246 of file mongoose.c.
typedef int SOCKET
Definition at line 213 of file mongoose.c.
typedef struct ssl_st SSL
Definition at line 253 of file mongoose.c.
typedef struct ssl_ctx_st SSL_CTX
Definition at line 255 of file mongoose.c.
typedef struct ssl_method_st SSL_METHOD
Definition at line 254 of file mongoose.c.
Enumeration Type Documentation
anonymous enum
Enumerator
CGI_EXTENSIONS
CGI_ENVIRONMENT
PUT_DELETE_PASSWORDS_FILE
CGI_INTERPRETER
PROTECT_URI
AUTHENTICATION_DOMAIN
SSI_EXTENSIONS
ACCESS_LOG_FILE
SSL_CHAIN_FILE
ENABLE_DIRECTORY_LISTING
ERROR_LOG_FILE
GLOBAL_PASSWORDS_FILE
INDEX_FILES
ENABLE_KEEP_ALIVE
ACCESS_CONTROL_LIST
MAX_REQUEST_SIZE
EXTRA_MIME_TYPES
LISTENING_PORTS
DOCUMENT_ROOT
SSL_CERTIFICATE
NUM_THREADS
RUN_AS_USER
NUM_OPTIONS
Definition at line 397 of file mongoose.c.
Function Documentation
int mg_get_cookie (const struct mg_connection * conn, const char * cookie_name, char * dst, size_t dst_size)
Definition at line 1507 of file mongoose.c.
References mg_get_header().
const char* mg_get_header (const struct mg_connection * conn, const char * name)
Definition at line 716 of file mongoose.c.
References mg_connection::request_info.
Referenced by mg_get_cookie().
const char* mg_get_option (const struct mg_context * ctx, const char * name)
Definition at line 493 of file mongoose.c.
References mg_context::config.
const char** mg_get_valid_option_names (void)
Definition at line 471 of file mongoose.c.
int mg_get_var (const char * buf, size_t buf_len, const char * name, char * dst, size_t dst_len)
Definition at line 1471 of file mongoose.c.
void mg_md5 (char * buf, ...)
Definition at line 2008 of file mongoose.c.
Referenced by mg_modify_passwords_file().
int mg_modify_passwords_file (const char * fname, const char * domain, const char * user, const char * pass)
Definition at line 2241 of file mongoose.c.
References mg_fopen, mg_md5(), mg_remove, and mg_rename.
int mg_printf (struct mg_connection * conn, const char * fmt, ...)
Definition at line 1424 of file mongoose.c.
References mg_write().
Referenced by server::web::WebServer::displayNotFound(), server::web::WebServer::displayUnauthorized(), server::web::WebServer::forward(), and Servlet::outputResponse().
int mg_read (struct mg_connection * conn, void * buf, size_t len)
Definition at line 1369 of file mongoose.c.
References mg_connection::buf, mg_connection::client, mg_connection::consumed_content, mg_connection::content_len, mg_connection::data_len, DEBUG_TRACE, mg_connection::request_len, socket::sock, and mg_connection::ssl.
Referenced by server::web::WebServer::getSession().
struct mg_context* mg_start (mg_callback_t user_callback, void * user_data, const char ** options) read
Definition at line 4057 of file mongoose.c.
References mg_context::cond, mg_context::config, DEBUG_TRACE, ENTRIES_PER_CONFIG_OPTION, ERRNO, mg_context::mutex, NUM_THREADS, mg_context::num_threads, mg_context::sq_empty, mg_context::sq_full, mg_context::user_callback, and mg_context::user_data.
Referenced by server::web::WebServer::mongooseMgrInit().
void mg_stop (struct mg_context * ctx)
Definition at line 4043 of file mongoose.c.
References mg_context::stop_flag.
Referenced by server::web::WebServer::stop().
const char* mg_version (void)
Definition at line 564 of file mongoose.c.
References MONGOOSE_VERSION.
int mg_write (struct mg_connection * conn, const void * buf, size_t len)
Definition at line 1419 of file mongoose.c.
References mg_connection::client, socket::sock, and mg_connection::ssl.
Referenced by mg_printf().
Variable Documentation
size_t ext_len
Definition at line 1724 of file mongoose.c.
const char* extension
Definition at line 1723 of file mongoose.c.
const char* mime_type
Definition at line 1725 of file mongoose.c.
size_t mime_type_len
Definition at line 1726 of file mongoose.c.