Core3: /Users/victor/git/Core3Mda/MMOCoreORB/src/server/web/mongoose/mongoose.h File Reference
mongoose.h File Reference
Classes
struct mg_request_info
struct mg_request_info::mg_header
Typedefs
typedef void *(* mg_callback_t)(enum mg_event event, struct mg_connection *conn, const struct mg_request_info *request_info)
Enumerations
enum mg_event { MG_NEW_REQUEST, MG_HTTP_ERROR, MG_EVENT_LOG, MG_INIT_SSL }
Functions
struct mg_context * mg_start (mg_callback_t callback, void *user_data, const char **options)
void mg_stop (struct mg_context *)
const char * mg_get_option (const struct mg_context *ctx, const char *name)
const char ** mg_get_valid_option_names (void)
int mg_modify_passwords_file (const char *passwords_file_name, const char *domain, const char *user, const char *password)
int mg_write (struct mg_connection *, const void *buf, size_t len)
int mg_printf (struct mg_connection *, const char *fmt,...)
int mg_read (struct mg_connection *, void *buf, size_t len)
const char * mg_get_header (const struct mg_connection *, const char *name)
int mg_get_var (const char *data, size_t data_len, const char *var_name, char *buf, size_t buf_len)
int mg_get_cookie (const struct mg_connection *, const char *cookie_name, char *buf, size_t buf_len)
const char * mg_version (void)
void mg_md5 (char *buf,...)
Typedef Documentation
typedef void*(* mg_callback_t)(enum mg_event event, struct mg_connection *conn, const struct mg_request_info *request_info)
Definition at line 77 of file mongoose.h.
Enumeration Type Documentation
enum mg_event
Enumerator
MG_NEW_REQUEST
MG_HTTP_ERROR
MG_EVENT_LOG
MG_INIT_SSL
Definition at line 53 of file mongoose.h.
Function Documentation
int mg_get_cookie (const struct mg_connection * , const char * cookie_name, char * buf, size_t buf_len)
Definition at line 1507 of file mongoose.c.
References mg_get_header().
const char* mg_get_header (const struct mg_connection * , const char * name)
Definition at line 716 of file mongoose.c.
References mg_connection::request_info.
Referenced by mg_get_cookie().
const char* mg_get_option (const struct mg_context * ctx, const char * name)
Definition at line 493 of file mongoose.c.
References mg_context::config.
const char** mg_get_valid_option_names (void)
Definition at line 471 of file mongoose.c.
int mg_get_var (const char * data, size_t data_len, const char * var_name, char * buf, size_t buf_len)
Definition at line 1471 of file mongoose.c.
void mg_md5 (char * buf, ...)
Definition at line 2008 of file mongoose.c.
Referenced by mg_modify_passwords_file().
int mg_modify_passwords_file (const char * passwords_file_name, const char * domain, const char * user, const char * password)
Definition at line 2241 of file mongoose.c.
References mg_fopen, mg_md5(), mg_remove, and mg_rename.
int mg_printf (struct mg_connection * , const char * fmt, ...)
Definition at line 1424 of file mongoose.c.
References mg_write().
Referenced by server::web::WebServer::displayNotFound(), server::web::WebServer::displayUnauthorized(), server::web::WebServer::forward(), and Servlet::outputResponse().
int mg_read (struct mg_connection * , void * buf, size_t len)
Definition at line 1369 of file mongoose.c.
References mg_connection::buf, mg_connection::client, mg_connection::consumed_content, mg_connection::content_len, mg_connection::data_len, DEBUG_TRACE, mg_connection::request_len, socket::sock, and mg_connection::ssl.
Referenced by server::web::WebServer::getSession().
struct mg_context* mg_start (mg_callback_t callback, void * user_data, const char ** options) read
Definition at line 4057 of file mongoose.c.
References mg_context::cond, mg_context::config, DEBUG_TRACE, ENTRIES_PER_CONFIG_OPTION, ERRNO, mg_context::mutex, NUM_THREADS, mg_context::num_threads, mg_context::sq_empty, mg_context::sq_full, mg_context::user_callback, and mg_context::user_data.
Referenced by server::web::WebServer::mongooseMgrInit().
void mg_stop (struct mg_context *)
Definition at line 4043 of file mongoose.c.
References mg_context::stop_flag.
Referenced by server::web::WebServer::stop().
const char* mg_version (void)
Definition at line 564 of file mongoose.c.
References MONGOOSE_VERSION.
int mg_write (struct mg_connection * , const void * buf, size_t len)
Definition at line 1419 of file mongoose.c.
References mg_connection::client, socket::sock, and mg_connection::ssl.
Referenced by mg_printf().