Core3: server::zone::objects::creature::ai::bt::test Namespace Reference
server::zone::objects::creature::ai::bt::test Namespace Reference
Classes
class BehaviorTest
Functions
TEST_F (BehaviorTest, testInitialize)
TEST_F (BehaviorTest, testUpdate)
TEST_F (BehaviorTest, testTerminate)
TEST_F (BehaviorTest, testAbort)
TEST_F (BehaviorTest, testSingleNodeTreePassAndFail)
TEST_F (BehaviorTest, testTwoNodesWithFailingBehavior)
TEST_F (BehaviorTest, testTwoNodeWithRunningBehavior)
Function Documentation
server::zone::objects::creature::ai::bt::test::TEST_F (BehaviorTest , testInitialize)
Definition at line 50 of file BehaviorTest.cpp.
References server::zone::objects::creature::ai::bt::Behavior::RUNNING, server::zone::objects::creature::ai::bt::BehaviorTree::start(), and server::zone::objects::creature::ai::bt::BehaviorTree::tick().
server::zone::objects::creature::ai::bt::test::TEST_F (BehaviorTest , testUpdate)
Definition at line 61 of file BehaviorTest.cpp.
References server::zone::objects::creature::ai::bt::Behavior::RUNNING, server::zone::objects::creature::ai::bt::BehaviorTree::start(), and server::zone::objects::creature::ai::bt::BehaviorTree::tick().
server::zone::objects::creature::ai::bt::test::TEST_F (BehaviorTest , testTerminate)
Definition at line 73 of file BehaviorTest.cpp.
References server::zone::objects::creature::ai::bt::Behavior::RUNNING, server::zone::objects::creature::ai::bt::BehaviorTree::start(), server::zone::objects::creature::ai::bt::Behavior::SUCCESS, and server::zone::objects::creature::ai::bt::BehaviorTree::tick().
server::zone::objects::creature::ai::bt::test::TEST_F (BehaviorTest , testAbort)
Definition at line 85 of file BehaviorTest.cpp.
References server::zone::objects::creature::ai::bt::BehaviorTree::start(), and server::zone::objects::creature::ai::bt::BehaviorTree::tick().
server::zone::objects::creature::ai::bt::test::TEST_F (BehaviorTest , testSingleNodeTreePassAndFail)
Definition at line 96 of file BehaviorTest.cpp.
References server::zone::objects::creature::ai::bt::Behavior::FAILURE, server::zone::objects::creature::ai::bt::Behavior::RUNNING, server::zone::objects::creature::ai::bt::BehaviorTree::start(), server::zone::objects::creature::ai::bt::Behavior::SUCCESS, and server::zone::objects::creature::ai::bt::BehaviorTree::tick().
server::zone::objects::creature::ai::bt::test::TEST_F (BehaviorTest , testTwoNodesWithFailingBehavior)
Definition at line 115 of file BehaviorTest.cpp.
References server::zone::objects::creature::ai::bt::Behavior::FAILURE, server::zone::objects::creature::ai::bt::Behavior::RUNNING, server::zone::objects::creature::ai::bt::BehaviorTree::start(), and server::zone::objects::creature::ai::bt::BehaviorTree::tick().
server::zone::objects::creature::ai::bt::test::TEST_F (BehaviorTest , testTwoNodeWithRunningBehavior)
Definition at line 129 of file BehaviorTest.cpp.
References server::zone::objects::creature::ai::bt::Behavior::RUNNING, server::zone::objects::creature::ai::bt::BehaviorTree::start(), and server::zone::objects::creature::ai::bt::BehaviorTree::tick().