import "../../scene/SceneObject";

import "../../creature/CreatureObject";

import "../../player/Player";

import "../TangibleObject";

import "Pharmaceutical";

interface CurePack implements Pharmaceutical {

	CurePack(unsigned long oid, unsigned int tempCRC, const UnicodeString n, const String tempn) {
		super(oid, tempCRC, n, tempn, int mptype);
	}

	CurePack(CreatureObject creature, unsigned int tempCRC, const UnicodeString n, const String tempn) {
		super(creature, tempCRC, n, tempn, int mptype);
	}

	void generateAttributes(SceneObject obj);

	void setEffectiveness(float eff);
	void setState(unsigned long condition);

	float getEffectiveness();
	unsigned long getState();
}
