import "../../scene/SceneObject";

import "../../creature/CreatureObject";

import "../../player/Player";

import "../TangibleObject";

import "Pharmaceutical";

interface RevivePack implements Pharmaceutical {
	
	RevivePack(unsigned long oid, unsigned int tempCRC, const unicode n, const string tempn) {
		super(oid, tempCRC, n, tempn, int mptype);
	}
	
	RevivePack(CreatureObject creature, unsigned int tempCRC, const unicode n, const string tempn) {
		super(creature, tempCRC, n, tempn, int mptype);
	}
	
	void generateAttributes(SceneObject obj);
	
	void setHealthWoundHealed(float eff);
	void setHealthHealed(float eff);
	void setActionWoundHealed(float eff);
	void setActionHealed(float eff);
	void setMindWoundHealed(float eff);
	void setMindHealed(float eff);
	
	float getHealthWoundHealed();
	float getHealthHealed();
	float getActionWoundHealed();
	float getActionHealed();
	float getMindWoundHealed();
	float getMindHealed();
}
