import "../../scene/SceneObject";

import "../../creature/CreatureObject";

import "../../player/Player";

import "../TangibleObject";

import "Pharmaceutical";

interface StatePack implements Pharmaceutical {
	
	StatePack(unsigned long oid, unsigned int tempCRC, const unicode n, const string tempn) {
		super(oid, tempCRC, n, tempn, int mptype);
	}
	
	StatePack(CreatureObject creature, unsigned int tempCRC, const unicode n, const string tempn) {
		super(creature, tempCRC, n, tempn, int mptype);
	}
	
	void generateAttributes(SceneObject obj);
	
	void setState(unsigned long value);
	
	unsigned long getState();
}
