/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.managers.city;

import engine.core.ManagedService;
import engine.log.Logger;
import server.zone.ZoneServer;
import server.zone.Zone;
import server.zone.objects.creature.CreatureObject;
import system.util.VectorMap;
import system.util.Vector;
import server.zone.objects.scene.SceneObject;
import server.zone.objects.waypoint.WaypointObject;
import server.zone.objects.structure.StructureObject;
include server.zone.objects.region.NewCityRegion;
include server.zone.objects.region.CityRegion;
include server.chat.StringIdChatParameter;
include server.zone.managers.city.CitiesAllowed;
include server.zone.managers.city.CitySpecialization;
include server.zone.managers.city.CitySpecializationMap;
include server.zone.managers.city.CityTax;
include server.zone.managers.city.CityTaxMap;

@dirty
class CityManager extends ManagedService implements Logger {
	private transient ZoneServer zoneServer;

	@dereferenced
	public static transient Vector<unsigned short> radiusPerRank;

	@dereferenced
	public static transient Vector<byte> citizensPerRank;

	@dereferenced
	private transient static CitiesAllowed citiesAllowedPerRank;

	@dereferenced
	private transient static CitySpecializationMap citySpecializations;

	@dereferenced
	private transient static CityTaxMap cityTaxes;

	public transient static int cityUpdateInterval;
	public transient static int newCityGracePeriod;
	public transient static int oldCityGracePeriod;
	public transient static unsigned long citySpecializationCooldown;
	public transient static int cityVotingDuration;
	public transient static unsigned long treasuryWithdrawalCooldown;
	public transient static byte cityVotingCycles;
	public transient static byte cityVotingCyclesUntilLocked;
	public transient static int decorationsPerRank;
	public transient static int trainersPerRank;
	public transient static int missionTerminalsPerRank;
	public transient static float maintenanceDiscount;

	@dereferenced
	private transient VectorMap<string, NewCityRegion> cities;

	//City Ranks
	public static final byte CLIENT = 0;
	public static final byte OUTPOST = 1;
	public static final byte VILLAGE = 2;
	public static final byte TOWNSHIP = 3;
	public static final byte CITY = 4;
	public static final byte METROPOLIS = 5;

	public CityManager(ZoneServer zserv) {
		Logger.setLoggingName("CityManager");
		Logger.setLogging(false);
		Logger.setGlobalLogging(true);

		zoneServer = zserv;

		cities.setNoDuplicateInsertPlan();
		cities.setNullValue(null);
	}

	/**
	 * Loads configuration settings for cities from the lua for the city manager.
	 */
	public native void loadLuaConfig();

	public native void loadCityRegions();

	public native void stop();

	@preLocked
	public native void convertCity(CityRegion city);

	public native boolean validateCityName(final string name);

	public native boolean isCityInRange(Zone zone, float x, float y);

	@preLocked
	@arg1preLocked
	public native NewCityRegion createCity(CreatureObject mayor, final string cityName, float x, float y);

	public native void assessCitizens(NewCityRegion city);

	public native void processCityUpdate(NewCityRegion city);

	/**
	 * Processes income tax from all citizens
	 * @pre city locked
	 * @post city locked
	 */
	public native void processIncomeTax(NewCityRegion city);
 
	/**
	 * Handles the voting of the city, tallys votes, see's who won. Resets the voting process.
	 * @pre city locked
	 * @post city locked
	 */
	public native void updateCityVoting(NewCityRegion city, boolean override = false);

	public native void deductCityMaintenance(NewCityRegion city);

	public native int collectNonStructureMaintenance(SceneObject object, NewCityRegion city, int maintenanceDue);

	public native int collectCivicStructureMaintenance(StructureObject structure, NewCityRegion city, int maintenanceDue);

	public native void sendMaintenanceEmail(NewCityRegion city, int maintenancePaid);

	public native void sendMaintenanceDecayEmail(NewCityRegion city, StructureObject structure, int maintenanceDue);

	public native void sendMaintenanceDestroyEmail(NewCityRegion city, SceneObject object);

	public native void sendMaintenanceRepairEmail(NewCityRegion city, StructureObject structure);

	public native void contractCity(NewCityRegion city);

	public native void expandCity(NewCityRegion city);

	public native void destroyCity(NewCityRegion city);

	public native void sendStatusReport(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	public native void promptCitySpecialization(NewCityRegion city, CreatureObject mayor, SceneObject terminal = null);

	public native void changeCitySpecialization(NewCityRegion city, CreatureObject mayor, final string spec);

	public native void promptWithdrawCityTreasury(NewCityRegion city, CreatureObject mayor, SceneObject terminal = null);

	public native void promptDepositCityTreasury(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	public native void withdrawFromCityTreasury(NewCityRegion city, CreatureObject mayor, int value, final string reason, SceneObject terminal = null);

	public native void depositToCityTreasury(NewCityRegion city, CreatureObject creature, int value);

	public native void sendTreasuryReport(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	public native void sendCitizenshipReport(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	public native void registerCitizen(NewCityRegion city, CreatureObject creature);

	public native void unregisterCitizen(NewCityRegion city, CreatureObject creature);

	public native void sendManageMilitia(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	public native void promptAddMilitiaMember(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	public native void addMilitiaMember(NewCityRegion city, CreatureObject mayor, final string playerName);

	public native void removeMilitiaMember(NewCityRegion city, CreatureObject mayor, unsigned long militiaid);

	public native void sendCityAdvancement(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	public native string getNextUpdateTimeString(NewCityRegion city);

	public native void promptRegisterCity(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	public native void promptUnregisterCity(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	public native void registerCity(NewCityRegion city, CreatureObject mayor);

	public native void unregisterCity(NewCityRegion city, CreatureObject mayor);

	public native void promptAdjustTaxes(NewCityRegion city, CreatureObject mayor, SceneObject terminal = null);

	public native void promptSetTax(NewCityRegion city, CreatureObject mayor, int selectedTax, SceneObject terminal = null);

	public native void setTax(NewCityRegion city, CreatureObject mayor, int selectedTax, int value);

	public native void sendMaintenanceReport(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	@local
	public native void sendMail(NewCityRegion city, final string sender, final unicode subject, @dereferenced StringIdChatParameter params, WaypointObject waypoint);

	public synchronized boolean containsCityName(final string name) {
		return cities.contains(name);
	}

	public native boolean isCityRankCapped(final string planetName, byte cityRank);

	public native void sendCityReport(CreatureObject creature, final string planetName, byte rank);

	public native boolean validateCityInRange(CreatureObject creature, Zone zone, float x, float y);

	public native void promptToggleZoningEnabled(NewCityRegion city, CreatureObject mayor);

	public void toggleZoningEnabled(NewCityRegion city, CreatureObject mayor) {
		boolean val = city.isZoningEnabled();
		city.setZoningEnabled(!val);

		if (!val) {
			mayor.sendSystemMessage("@city/city:zoning_enabled"); //Your city now has zoning enabled.
		} else {
			mayor.sendSystemMessage("@city/city:zoning_disabled"); //Your city now has zoning disabled.
		}
	}

	public int getTotalCities() {
		return cities.size();
	}

	public boolean renameCity(NewCityRegion city, final string newName) {
		if(cities.contains(city.getCityRegionName())){
			cities.drop(city.getCityRegionName());
			cities.put(newName, city);
			return true;
		}

		return false;

	}

	/**
	 * @pre city locked, creature locked, sceneObject locked
	 * @post city locked, creature locked, sceneObject locked
	 */
	public native void sendMayoralStandings(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	/**
	 * @pre city locked, creature locked, sceneObject locked
	 * @post city locked, creature locked, sceneObject locked
	 */
	public native void promptMayoralVote(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	/**
	 * @pre city locked, creature locked
	 * @post city locked, creature locked
	 */
	public native void registerForMayoralRace(NewCityRegion city, CreatureObject creature);
	public native void unregisterFromMayoralRace(NewCityRegion city, CreatureObject creature, boolean force);

	public native void castMayoralVote(NewCityRegion city, CreatureObject creature, unsigned long oid);

	public native void sendStructureReport(NewCityRegion city, CreatureObject creature, SceneObject terminal = null);

	public native boolean canSupportMoreDecorations(NewCityRegion city);
	public native boolean canSupportMoreTrainers(NewCityRegion city);
	public native boolean canSupportMoreMissionTerminals(NewCityRegion city);

	@local
	public native final CitySpecialization getCitySpecialization(final string cityspec);

	@local
	public native final CityTax getCityTax(int idx);

	public native void sendChangeCityName(NewCityRegion city, CreatureObject mayor);

	public native void sendAddStructureMails(NewCityRegion city, StructureObject structure);

	public native void promptForceRank(NewCityRegion city, CreatureObject player, boolean rankUp);

	public native void promptForceUpdate(NewCityRegion city, CreatureObject player);

	public native void alignAmenity(NewCityRegion city, CreatureObject player, SceneObject amenity, int direction);
}
