/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.tangible.component.droid;

import server.zone.objects.tangible.component.Component;
include server.zone.objects.manufactureschematic.craftingvalues.CraftingValues;
import server.zone.packets.scene.AttributeListMessage;
import server.zone.objects.creature.CreatureObject;

@json
class DroidComponent extends Component {
	protected float quality;
	protected float durability;

	// Droid module floats for more precise crafting results
	protected float autoRepairPower;
	protected float combatRating;
	protected float detonationRating;
	protected float harvestBonus;
	protected float stimpackSpeed;
	protected float trapBonus;

	protected boolean surveyDroid;
	protected boolean autoRepairDroid;
	protected boolean combatDroid;
	protected boolean detonationDroid;
	protected boolean harvestDroid;
	protected boolean stimpackDroid;
	protected boolean trapDroid;

	public DroidComponent() {
		Logger.setLoggingName("DroidComponent");
		quality = 0;
		durability = 0;
		surveyDroid = false;
		autoRepairDroid = false;
		combatDroid = false;
		detonationDroid = false;
		harvestDroid = false;
		stimpackDroid = false;
		trapDroid = false;
	}

	/**
	 * Initializes the transient members of SceneObject, must call the inherited object method first.
	 * @pre {transient members are not initialized }
	 * @post { transient members are initialized }
	 */
	public native void initializeTransientMembers();

	@local
	public native void updateCraftingValues(CraftingValues values, boolean firstUpdate);

	@local
	@dirty
	public native void fillAttributeList(AttributeListMessage msg, CreatureObject object);

	@local
	public native boolean isSocketCluster();


}
