/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.region.space;

import engine.util.Observer;
import engine.util.Observable;

include server.zone.objects.region.space.SpaceSpawnArea;
include engine.log.Logger;
import engine.core.ManagedObject;

@json
class SpaceSpawnAreaObserver extends Observer implements Logger {
	@weakReference
	protected SpaceSpawnArea spaceSpawnArea;

	public SpaceSpawnAreaObserver(SpaceSpawnArea area) {
		spaceSpawnArea = area;

		Logger.setLoggingName("SpaceSpawnAreaObserver");
	}

	@dirty
	public abstract int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2) {
		SpaceSpawnArea area = spaceSpawnArea;

		if (!area)
			return 1;
		else
			return area.notifyObserverEvent(eventType, observable, arg1, arg2);
	}
}
