import "../../../scene/SceneObject";

import "../../../creature/CreatureObject";

import "../../../player/Player";

import "../../TangibleObject";

import "../Consumable";

interface Drink implements Consumable {

	Drink(unsigned long oid, unsigned int tempCRC, const UnicodeString n, const String tempn) {
		super(oid, tempCRC, n, tempn, int type);
	}

	Drink(CreatureObject creature, unsigned long oid, unsigned int tempCRC, const UnicodeString n, const String tempn) {
		super(creature, oid, tempCRC, n, tempn, int type);
	}	

	int useObject(Player player);
	
	void generateAttributes(SceneObject obj);
	
	void setNutrition(int n);
	void setFlavor(int f);
	void setQuantity(int q);
	void setFilling(int f);
	
	int getNutrition();
	int getFlavor();
	int getQuantity();
	int getFilling();

}
