import "../DeedObject";
import "../../TangibleObject";
import "../../../../packets";
import "../../../player/Player";
import "../../../creature/CreatureObject";

import "../../../../packets/object/ObjectMenuResponse";

interface ResourceDeed implements DeedObject {
	ResourceDeed(CreatureObject creature, int tempCRC, const UnicodeString n, const String tempn) {
		super(creature, tempCRC, n, tempn, int tp);
	}
	ResourceDeed(unsigned long oid, int tempCRC, const UnicodeString n, const String tempn) {
		super(oid, tempCRC, n, tempn, int tp);
	}

	int useObject(Player player);
	
	void sendRadialResponseTo(Player player, ObjectMenuResponse omr);
	
	void destroyDeed(Player player);
}

