/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.staticobject;

import server.zone.objects.staticobject.StaticObject;

@json
class SpaceObject extends StaticObject {
	public SpaceObject() {
	}

	@dirty
	public native abstract float getOutOfRangeDistance(unsigned long specialRangeObjectID = 0);
}