/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.staticobject;

import server.zone.objects.scene.SceneObject;
include templates.SharedObjectTemplate;

class StaticObject extends SceneObject {
	public StaticObject() {
		Logger.setLoggingName("StaticObject");
		Logger.setLogging(false);
		Logger.setGlobalLogging(true);
	}
	
	/**
	 * Reads and sets the template data from a SharedObjectTemplate LuaObject
	 * @pre { templateData is a valid pointer }
	 * @post { SceneObject members are initialized }
	 * @param templateData templateData points to the LuaObject that is used to initialize SceneObejct members
	 */
	@local
	public void loadTemplateData(SharedObjectTemplate templateData) {
		super.loadTemplateData(templateData);
	}

	@dirty
	public native void sendBaselinesTo(SceneObject player);

    @dirty
    @local
    public native abstract StaticObject asStaticObject();

	@dirty
	public boolean isStaticObjectClass() {
		return true;
	}
}
