/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.region;

import server.zone.objects.area.ActiveArea;
import server.zone.objects.region.CityRegion;
import server.zone.objects.scene.SceneObject;

@json
class Region extends ActiveArea {
	@weakReference
	protected CityRegion cityRegion;

	public Region() {
		super();
	}

	public native void notifyLoadFromDatabase();

	public void enqueueEnterEvent(SceneObject obj) {
		notifyEnter(obj);
	}

	public void enqueueExitEvent(SceneObject obj) {
		notifyExit(obj);
	}

	@dirty
	public boolean isRegion() {
		return true;
	}

	public boolean isSpawnAreaObject() {
		return false;
	}
}
