

package server.zone.objects.tangible.sign;

import engine.core.ManagedObject;
import engine.log.Logger;
import engine.util.Observer;
import engine.util.Observable;
import server.zone.objects.player.PlayerCreature;
import server.zone.objects.scene.SceneObject;
import server.zone.objects.area.ActiveArea;
import server.zone.Zone;
import server.zone.ZoneProcessServer;
import server.zone.objects.tangible.sign.SignObject;

include server.zone.objects.scene.ObserverEventType;

class SignObserver extends Observer {
	@weakReference
	protected SignObject signObject;
	
	public SignObserver(SignObject sign) {
		signObject = sign;
	}
	
	public int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2) {
		switch (eventType) {
		case ObserverEventType.OBJECTNAMECHANGED:
			notifyObjectNameChanged((SceneObject) arg1);
			break;
		}
		
		return 0;
	}
	
	public native void notifyObjectNameChanged(SceneObject object);
}