/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.tangible.sign;

import server.zone.objects.scene.SceneObject;
import server.zone.objects.tangible.TangibleObject;
import server.zone.objects.creature.CreatureObject;

class SignObject extends TangibleObject {
	@weakReference
	public SceneObject attachedObject;
	
	public SignObject() {		
		Logger.setLoggingName("SignObject");
	}

	public native int handleObjectMenuSelect(CreatureObject player, byte selectedID);
	
	@dirty
	public native void sendSignNameTo(CreatureObject player);
	
	@dirty
	public boolean isSignObject() {
		return true;
	}

	public native void initializeChildObject(SceneObject controllerObject);
}
