/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.managers.radial;

import engine.core.ManagedObject;
import engine.log.Logger;
import server.zone.ZoneServer;

import server.zone.objects.creature.CreatureObject;
import server.zone.packets.object.ObjectMenuResponse;
import server.zone.objects.scene.SceneObject;

class RadialManager extends ManagedObject implements Logger {
	ZoneServer zoneServer;
	
	public native RadialManager(ZoneServer server);
	
	public native void handleObjectMenuSelect(CreatureObject player, byte selectID, unsigned long objectID);
	public native void handleObjectMenuRequest(CreatureObject player, ObjectMenuResponse defaultMenuResponse, unsigned long objectID);
	
}