/*
 *	server/zone/objects/tangible/Instrument.cpp generated by engine3 IDL compiler 0.60
 */

#include "Instrument.h"

#include "server/zone/objects/scene/SceneObject.h"

/*
 *	InstrumentStub
 */

Instrument::Instrument() : TangibleObject(DummyConstructorParameter::instance()) {
	_impl = new InstrumentImplementation();
	_impl->_setStub(this);
}

Instrument::Instrument(DummyConstructorParameter* param) : TangibleObject(param) {
}

Instrument::~Instrument() {
}


void Instrument::initializeTransientMembers() {
	if (_impl == NULL) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, 6);

		method.executeWithVoidReturn();
	} else
		((InstrumentImplementation*) _impl)->initializeTransientMembers();
}

/*
 *	InstrumentImplementation
 */

InstrumentImplementation::InstrumentImplementation(DummyConstructorParameter* param) : TangibleObjectImplementation(param) {
	_initializeImplementation();
}

InstrumentImplementation::~InstrumentImplementation() {
}


void InstrumentImplementation::finalize() {
}

void InstrumentImplementation::_initializeImplementation() {
	_setClassHelper(InstrumentHelper::instance());

	_serializationHelperMethod();
}

void InstrumentImplementation::_setStub(DistributedObjectStub* stub) {
	_this = (Instrument*) stub;
	TangibleObjectImplementation::_setStub(stub);
}

DistributedObjectStub* InstrumentImplementation::_getStub() {
	return _this;
}

InstrumentImplementation::operator const Instrument*() {
	return _this;
}

void InstrumentImplementation::lock(bool doLock) {
	_this->lock(doLock);
}

void InstrumentImplementation::lock(ManagedObject* obj) {
	_this->lock(obj);
}

void InstrumentImplementation::rlock(bool doLock) {
	_this->rlock(doLock);
}

void InstrumentImplementation::wlock(bool doLock) {
	_this->wlock(doLock);
}

void InstrumentImplementation::wlock(ManagedObject* obj) {
	_this->wlock(obj);
}

void InstrumentImplementation::unlock(bool doLock) {
	_this->unlock(doLock);
}

void InstrumentImplementation::runlock(bool doLock) {
	_this->runlock(doLock);
}

void InstrumentImplementation::_serializationHelperMethod() {
	TangibleObjectImplementation::_serializationHelperMethod();

	_setClassName("Instrument");

}

InstrumentImplementation::InstrumentImplementation() {
	_initializeImplementation();
	// server/zone/objects/tangible/Instrument.idl(53):  		Logger.setLoggingName("Instrument");
	Logger::setLoggingName("Instrument");
}

void InstrumentImplementation::initializeTransientMembers() {
	// server/zone/objects/tangible/Instrument.idl(57):  		super.initializeTransientMembers();
	TangibleObjectImplementation::initializeTransientMembers();
	// server/zone/objects/tangible/Instrument.idl(59):  		Logger.setLoggingName("Instrument");
	Logger::setLoggingName("Instrument");
}

/*
 *	InstrumentAdapter
 */

InstrumentAdapter::InstrumentAdapter(InstrumentImplementation* obj) : TangibleObjectAdapter(obj) {
}

Packet* InstrumentAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	Packet* resp = new MethodReturnMessage(0);

	switch (methid) {
	case 6:
		initializeTransientMembers();
		break;
	default:
		return NULL;
	}

	return resp;
}

void InstrumentAdapter::initializeTransientMembers() {
	((InstrumentImplementation*) impl)->initializeTransientMembers();
}

/*
 *	InstrumentHelper
 */

InstrumentHelper* InstrumentHelper::staticInitializer = InstrumentHelper::instance();

InstrumentHelper::InstrumentHelper() {
	className = "Instrument";

	DistributedObjectBroker::instance()->registerClass(className, this);
}

void InstrumentHelper::finalizeHelper() {
	InstrumentHelper::finalize();
}

DistributedObject* InstrumentHelper::instantiateObject() {
	return new Instrument(DummyConstructorParameter::instance());
}

DistributedObjectServant* InstrumentHelper::instantiateServant() {
	return new InstrumentImplementation(DummyConstructorParameter::instance());
}

DistributedObjectAdapter* InstrumentHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new InstrumentAdapter((InstrumentImplementation*) obj->_getImplementation());

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

