/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions. */

package server.zone.objects.tangible;

include engine.core.ManagedObject;
import engine.util.Observer;
import engine.util.Observable;
import server.zone.objects.tangible.Instrument;

class InstrumentObserver extends Observer {
	@weakReference
	protected Instrument instrument;

	public InstrumentObserver(Instrument instr) {
		instrument = instr;
	}

	@dirty
	public native int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);

	@weakReference
	@read
	public Instrument getInstrument() {
		return instrument;
	}
}
