import "../DeedObject";
import "../../TangibleObject";
import "../../../../packets";
import "../../../player/Player";
import "../../../creature/CreatureObject";

import "../../../../packets/object/ObjectMenuResponse";

interface VehicleDeed implements DeedObject {
	VehicleDeed(CreatureObject creature, int tempCRC, const unicode n, const string tempn) {
		super(creature, tempCRC, n, tempn, int tp);
	}
	VehicleDeed(unsigned long oid, int tempCRC, const unicode n, const string tempn) {
		super(oid, tempCRC, n, tempn, int tp);
	}

	int useObject(Player player);
	
	void sendRadialResponseTo(Player player, ObjectMenuResponse omr);
}

