/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

package server.zone.objects.tangible.component.lightsaber;

import server.zone.objects.tangible.component.Component;
import engine.lua.LuaObject;
import server.zone.packets.scene.AttributeListMessage;
import server.zone.Zone;
import server.zone.packets.object.ObjectMenuResponse;
import server.zone.objects.manufactureschematic.ManufactureSchematic;
import server.zone.templates.SharedObjectTemplate;
include server.zone.templates.tangible.LightsaberCrystalObjectTemplate;

class LightsaberCrystalComponent extends Component {
	protected int color;
	protected int quality;
	protected string owner;
	protected int attackSpeed;
	protected int minimumDamage;	
	protected int maximumDamage;
	protected int forceCost;
	protected int sacHealth;
	protected int sacAction;
	protected int sacMind;
	protected float woundChance;
	protected string crystalType;


	protected transient LightsaberCrystalObjectTemplate lightsaberCrystalObjectTemplate;

	public LightsaberCrystalComponent() {

		crystalType = "";
		color = 0;
		quality = 0;
		attackSpeed = 0;
		minimumDamage = 0;	
		maximumDamage = 0;
		forceCost = 0;
		sacHealth = 0;
		sacAction = 0;
		sacMind = 0;
		woundChance = 0.0;
		
		Logger.setLoggingName("LightsaberCrystal");
	}
	
	@local
	public native void loadTemplateData(SharedObjectTemplate templateData);
	
	public native void initializeTransientMembers();
	
	@local
	public native void updateCraftingValues(CraftingValues values, boolean firstUpdate);
	
	/**
	 * Fills the attribute list message options that are sent to player creature
	 * @pre { }
	 * @post { }
	 * @param msg attribute list message with the attributes
	 * @param object player creature to which the message is sent
	 */
	@local
	public native void fillAttributeList(AttributeListMessage msg, CreatureObject object);
	
	public native void fillObjectMenuResponse(ObjectMenuResponse menuResponse, CreatureObject player);

	public native int handleObjectMenuSelect(CreatureObject player, byte selectedID);

	public native void tuneCrystal(CreatureObject player);

	public native void updateCrystal(int value);
	
	public int getColor() {
		return color;
	}
	
	public int getQuality() {
		return quality;
	}

	public int getMinimumDamage() {
		return minimumDamage;
	}

	public int getMaximumDamage() {
		return maximumDamage;
	}

	public int getForceCost() {
		return forceCost;
	}

	public int getSacHealth() {
		return sacHealth;
	}

	public int getAttackSpeed() {
		return attackSpeed;
	}

	
	public int getSacAction() {
		return sacAction;
	}

	
	public int getSacMind() {
		return sacMind;
	}

	
	public float getWoundChance() {
		return woundChance;
	}
	
	public string getCrystalType() {
		return crystalType;
	}

	public string getOwner() {
		return owner;
	}

	public void setCrystalType(string value) {
		crystalType = value;
	}

	public void setOwner(string value) {
		owner = value;
	}

	public void setColor(int value) {
		color = value;
	}
	
	public void setQuality(int value) {
		quality = value;
	}

	public void setMinimumDamage(int value) {
		minimumDamage = value;
	}

	public void setMaximumDamage(int value) {
		maximumDamage = value;
	}

	public void setForceCost(int value) {
		forceCost = value;
	}

	public void setSacHealth(int value) {
		sacHealth = value;
	}

	public void setSacAction(int value) {
		sacAction = value;
	}

	public void setSacMind(int value) {
		sacMind = value;
	}

	public void setAttackSpeed(int value) {
		attackSpeed = value;
	}

	public void setWoundChance(float value) {
		woundChance = value;
	}
	
	
	public boolean isLightsaberCrystalObject() {
		return true; 
	}
}

