import "../TangibleObject";
import "../../creature/CreatureObject";
import "../../player/Player";
 
//import "../../../Zone";
 
include "engine/service/Message";
 
interface Attachment implements TangibleObject {
 
	Attachment(unsigned int oid, int type);
	
	void remove(Player player);

	void setSkillMod0Type(int type);
	void setSkillMod1Type(int type);
	void setSkillMod2Type(int type);

	void setSkillMod0Value(int value);
	void setSkillMod1Value(int value);
	void setSkillMod2Value(int value);

	void setSkillModValue(int index, int value);
	void setSkillModType(int index, int type);
	
	void setSkillMods(int modifier);
	
	int getSkillMod0Type();
	int getSkillMod1Type();
	int getSkillMod2Type();

	int getSkillMod0Value();
	int getSkillMod1Value();
	int getSkillMod2Value();

	int getSkillModType(int index);
	int getSkillModValue(int index);
	int getBestSkillMod();
}
