/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

include "engine/service/Message";

import "../../creature/CreatureObject";

import "../../player/Player";

import "../TangibleObject";
import "../../scene/SceneObject";
import "../Container";
import "../../../packets";
import "../../player/Player";
import "../../draftschematic/DraftSchematic";

import "CraftingStation";

interface CraftingTool implements TangibleObject {
	CraftingTool(unsigned long oid, unsigned int tempCRC, const UnicodeString n, const String tempn) {
		super(oid, tempCRC, n, tempn, int type);
	}

	CraftingTool(CreatureObject creature, unsigned int tempCRC, const UnicodeString n, const String tempn) {
		super(creature, tempCRC, n, tempn, int type);
	}

	void sendTo(Player player, boolean doClose = true);
	void generateAttributes(SceneObject obj);

	void resetSlots();
	void retriveHopperItem(Player  player);

 	void cleanUp(Player player);

	int useObject(Player player);

	void sendToolStart(Player player);

	//setters
	void setToolEffectiveness(float eff);
	void setCraftingState(int s);
	void setWorkingTano(TangibleObject tano);
	void setWorkingDraftSchematic(DraftSchematic draftSchematic);
	void setInsertCount(int count);
	void setStatusReady();
	void setStatusWorking();
	void setStatusFinished();
	void setAssemblyResults(int results);
	void setRecoverResources(boolean in);
	void setToolType(int in);

	void increaseInsertCount();
	boolean addIngredientToSlot(int slot, TangibleObject tano);
	void clearIngredientInSlot(int slot);
	void addTempIngredient(TangibleObject tano);

	//getters
	float getToolEffectiveness();
	int getCraftingState();
	TangibleObject getWorkingTano();
	DraftSchematic getWorkingDraftSchematic();
	int getInsertCount();
	TangibleObject getIngredientInSlot(int slot);
	int getIngredientInSlotQuantity(int slot);
	int getSlotCount();
	Container getHopper(Player player);
	int getAssemblyResults();
	float getCraftingToolModifier();
	int getToolType();
	DraftSchematic getCurrentDraftSchematic(int slot);


	boolean isExperimenting();
	boolean isReady();
	boolean isFinished();
	boolean isWorking();
}
