/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.
*/

package server.zone.objects.tangible.consumable;

import engine.core.ManagedObject;
import engine.util.Observer;
import engine.util.Observable;
import server.zone.objects.creature.buffs.DelayedBuff;
include engine.log.Logger;

class DelayedBuffObserver extends Observer implements Logger {

	@weakReference
	protected DelayedBuff buff;

	public DelayedBuffObserver(DelayedBuff b) {
		super();
		
		Logger.setLoggingName("DelayedBuffObserver");
		
		buff = b;
	}
	
	public native int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);
	
}
