/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.tangible.consumable;

import server.zone.objects.tangible.consumable.Consumable;
import server.zone.objects.scene.SceneObject;
import engine.lua.LuaObject;
import server.zone.Zone;

class Food extends Consumable {
	public Food() {		
		Logger.setLoggingName("Food");
		
		initializePrivateData();
	}
	
	public void initializeTransientMembers() {
		super.initializeTransientMembers();
		
		Logger.setLoggingName("Food");
	}
	
	public void initializePrivateData() {
		super.consumableType = super.FOOD;
	}
}
