/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.tangible.terminal.ticketcollector;

import server.zone.objects.tangible.terminal.Terminal;
import server.zone.objects.scene.SceneObject;
import engine.lua.LuaObject;
import server.zone.objects.creature.CreatureObject;
import server.zone.Zone;
import server.zone.objects.tangible.ticket.TicketObject;

class TicketCollector extends Terminal {
	public TicketCollector() {		
		Logger.setLoggingName("TicketCollector");
	}
	
	public void initializeTransientMembers() {
		super.initializeTransientMembers();
		
		Logger.setLoggingName("TicketCollector");
	}
	
	
	/**
	 * Handles the radial selection sent by the client
	 * @pre { this object is locked, player is locked }
	 * @post { this object is locked, player is locked }
	 * @returns 0 if successfull
	 */
	public native int handleObjectMenuSelect(CreatureObject player, byte selectedID);
	
	@dirty
	public native void useTicket(CreatureObject player, TicketObject ticket);
	
	@dirty
	public boolean isTicketCollector() {
		return true;
	}
}