-- Update Instrument Objects to match instrumentAudioID in the TRE
UPDATE `character_items` set attributes = 'instrumentType=1:' where template_name = 'obj_traz';
UPDATE `character_items` set attributes = 'instrumentType=2:' where template_name = 'obj_slitherhorn';
UPDATE `character_items` set attributes = 'instrumentType=3:' where template_name = 'obj_fanfar';
UPDATE `character_items` set attributes = 'instrumentType=4:' where template_name = 'obj_growdi_flute';
UPDATE `character_items` set attributes = 'instrumentType=5:' where template_name = 'obj_kloo_horn';
UPDATE `character_items` set attributes = 'instrumentType=6:' where template_name = 'obj_fizzz';
UPDATE `character_items` set attributes = 'instrumentType=7:' where template_name = 'obj_bandfill';
UPDATE `character_items` set attributes = 'instrumentType=8' where template_name = 'obj_ommni_box';
UPDATE `character_items` set attributes = 'instrumentType=9:' where template_name = 'obj_nalargon';
UPDATE `character_items` set attributes = 'instrumentType=10:' where template_name = 'obj_mandoviol';
