DROP TABLE IF EXISTS `draft_schematics`;
CREATE TABLE `draft_schematics` (
  `draftschematic_id` bigint(20) unsigned NOT NULL,
  `name` text character set ucs2 NOT NULL,
  `object_crc` int(10) unsigned NOT NULL,
  `group_name` tinytext NOT NULL,
  `complexity` int(10) unsigned NOT NULL,
  `schematic_size` int(10) unsigned NOT NULL,
  `ingredient_template_names` text character set ucs2 NOT NULL,
  `ingredient_title_names` text NOT NULL,
  `ingredient_optional` text NOT NULL,
  `resource_types` text NOT NULL,
  `resource_quantities` text NOT NULL,
  `number_experimental_property` text NOT NULL,
  `experimental_property` text NOT NULL,
  `experimental_weights` text NOT NULL,
  `experimental_group_title` text NOT NULL,
    PRIMARY KEY  USING BTREE (`draftschematic_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

INSERT INTO `draft_schematics` VALUES(1, 'Bofa Treat', 2207249955, 'craftArtisanNewbieGroupA', 3, 1, 'craft_food_ingredients_n, craft_food_ingredients_n, craft_food_ingredients_n', 'dried_fruit, crust, additive', '0, 0, 1', 'organic, cereal, object/tangible/food/crafted/additive/shared_additive_light.iff', '3, 8, 1', '1, 1, 1, 2, 2, 2, 2', 'XX, XX, XX, OQ, PE, FL, OQ, DR, PE, DR, OQ', '0, 0, 0, 1, 2, 2, 1, 1, 3, 3, 1', 'exp_filling, exp_flavor, exp_nutrition, exp_quantity');
INSERT INTO `draft_schematics` VALUES(2, 'Advanced Chitin Armor Segment', 892546099, 'craftArtisanEngineeringGroupA', 15, 4, 'craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n', 'armor_segment_chitin, armor_segment_tab_mounts, segment_enhancement', '0, 0, 1', 'bone_mammal_dantooine, iron_doonium, object/tangible/component/armor/shared_armor_segment_chitin_advanced.iff', '25, 8, 1', '1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2', 'XX, XX, XX, OQ, SR, OQ, UT, MA, OQ, MA, OQ, MA, OQ, XX, XX, OQ, SR, OQ, SR', '0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1', '');
INSERT INTO `draft_schematics` VALUES(3, 'Food and Chemical Crafting Station', 697822739, 'craftArtisanNewbieGroupA', 20, 5, 'craft_item_ingredients_n, craft_item_ingredients_n, craft_item_ingredients_n, craft_item_ingredients_n, craft_item_ingredients_n', 'assembly_enclosure, thermal_shielding, electronic_control_unit, micro_sensor_suite, storage_compartment', '0, 0, 1, 1, 1', 'metal, mineral, object/tangible/component/item/shared_electronic_control_unit.iff, object/tangible/component/item/shared_micro_sensor_suite.iff, object/tangible/component/droid/shared_droid_storage_compartment.iff', '400, 50, 2, 2, 5', '1, 1, 1, 1', 'XX, XX, XX, CD', '0, 0, 0, 1', '');
INSERT INTO `draft_schematics` VALUES(4, 'Ambient Solar Energy Surveying Tool', 2148903380, 'craftArtisanNewbieGroupA', 5, 1, 'craft_item_ingredients_n, craft_item_ingredients_n, craft_item_ingredients_n', 'assembly_enclosure, controller_mechanism, scanner_assembly', '0, 0, 0', 'metal, metal, metal', '8, 5, 3', '1, 1, 1, 1', 'XX, XX, XX, CD', '0, 0, 0, 1', '');
INSERT INTO `draft_schematics` VALUES(5, 'Biological Effect Controller', 2661748357, 'craftMedicineComponentGroupA', 10, 2, 'craft_chemical_ingredients_n, craft_chemical_ingredients_n', 'organic_element, inorganic_element', '0, 0', 'organic, inorganic', '6, 6', '1, 1, 2, 2', 'XX, XX, OQ, UT, OQ, PE', '1, 1, 2, 1, 2, 1', '');
INSERT INTO `draft_schematics` VALUES(6, 'Simple Shirt', 2693939929, 'craftArtisanNewbieGroupB', 4, 3, 'craft_clothing_ingredients_n, craft_clothing_ingredients_n', 'body, bindings_and_binding_hardware', '0, 0', 'fiberplast, metal', '16, 4', '', '', '', '');
INSERT INTO `draft_schematics` VALUES(7, 'Hurrton', 221814880, 'craftDomesticCreatureGroupA', 18, 1, 'craft_creature_ingredients_n, craft_creature_ingredients_n, craft_creature_ingredients_n', 'dna_template, protein_base, organic_nutrition_materials', '0, 0, 0', 'object/tangible/component/base/shared_base_dna_sample.iff, creature_food, flora_food', '1, 45, 25', '', '', '', '');
INSERT INTO `draft_schematics` VALUES(8, 'Level 1 Droid Medical Module', 2910848469, 'craftdroidgenmodGroupA', 15, 2, 'craft_droid_ingredients_n, craft_droid_ingredients_n, craft_droid_ingredients_n', 'unknown, unknown, unknown', '0, 0, 0', 'nonferrous_metal, metal, inert_gas', '15, 5, 2', '1, 1, 2, 2, 2, 2', 'XX, XX, CD, OQ, XX, XX, CD, OQ, CD, OQ', '1, 1, 1, 1, 1, 1, 1, 1, 1, 1', '');
INSERT INTO `draft_schematics` VALUES(9, 'Travel Biscuits', 854764144, 'craftArtisanNewbieGroupA', 3, 1, 'craft_food_ingredients_n, craft_food_ingredients_n, craft_food_ingredients_n', 'dried_bread, preservative_wrap, additive', '0, 0, 1', 'cereal, hide, object/tangible/food/crafted/additive/shared_additive_light.iff', '3, 8, 1', '1, 1, 1, 2, 2, 2, 2', 'XX, XX, XX, OQ, PE, FL, OQ, DR, OQ, DR, SR', '0, 0, 0, 1, 2, 2, 1, 3, 1, 1, 3', '');
INSERT INTO `draft_schematics` VALUES(10, 'Couch', 503627770, 'craftFurnitureGroupAA', 18, 2, 'craft_furniture_ingredients_n, craft_furniture_ingredients_n', 'unknown, unknown', '0, 0', 'metal, hide', '90, 80', '1, 1, 1, 2', 'XX, XX, XX, DR, OQ', '0, 0, 0, 1, 1', '');
INSERT INTO `draft_schematics` VALUES(11, 'Generic Crafting Tool', 2914524854, 'craftArtisanNewbieGroupA', 10, 2, 'craft_item_ingredients_n, craft_item_ingredients_n, craft_item_ingredients_n', 'assembly_enclosure, thermal_shielding, electronic_control_unit', '0, 0, 0', 'metal, mineral, chemical', '12, 4, 4', '1, 1, 1, 1', 'XX, XX, XX, CD', '0, 0, 0, 1', '');
INSERT INTO `draft_schematics` VALUES(12, 'Metal Necklace', 2061721546, 'craftClothingFormalGroupA', 17, 2, 'craft_jewelry_ingredients_n, craft_jewelry_ingredients_n, craft_jewelry_ingredients_n', 'clasp, band, jewelry_setting', '0, 0, 0', 'steel, steel, crystalline_gemstone', '5, 15, 5', '', '', '', '');
INSERT INTO `draft_schematics` VALUES(13, 'C12 Fragmentation Grenade', 11395638, 'craftMunitionsGroupA', 20, 2, 'craft_munition_ingredients_n, craft_munition_ingredients_n, craft_munition_ingredients_n, craft_munition_ingredients_n, craft_munition_ingredients_n, craft_munition_ingredients_n', 'unknown, unknown, unknown, unknown, unknown, unknown', '0, 0, 0, 0, 0, 0', 'metal, metal, steel, steel, object/tangible/component/munition/shared_warhead_light.iff, object/tangible/component/munition/shared_warhead_fusing_mechanism.iff', '8, 4, 3, 2, 1, 1', '1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2', 'XX, XX, OQ, SR, OQ, SR, OQ, SR, OQ, SR, OQ, SR, OQ, SR, OQ, SR, OQ, SR, OQ, SR, OQ, SR, OQ, SR, OQ, SR, OQ, SR', '0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1', '');
INSERT INTO `draft_schematics` VALUES(14, 'Z-95 Chassis', 2357203295, 'craftShipwrightNoviceGroupA', 23, 1, 'craft_spaceship_ingredients_n, craft_spaceship_ingredients_n, craft_spaceship_ingredients_n, craft_spaceship_ingredients_n', 'unknown, unknown, unknown, unknown', '0, 0, 0, 0', 'steel, inert_petrochemcial, low_grade_ore, aluminum', '2000, 1000, 1000, 1000', '1, 1, 1, 1', 'XX, XX, SR, CD', '0, 0, 1, 1', '');
INSERT INTO `draft_schematics` VALUES(15, 'Deed for: Small Naboo House', 202905090, 'craftStructureGroupAA', 13, 10, 'craft_structure_ingredients_n, craft_structure_ingredients_n, craft_structure_ingredients_n, craft_structure_ingredients_n, craft_structure_ingredients_n, craft_structure_ingredients_n', 'load_bearing_structure_and_shell, insulation_and_covering, foundation, wall_sections, power_supply_unit, storage_space', '0, 0, 0, 0, 0, 0', 'metal, low_grade_ore, low_grade_ore, object/tangible/component/structure/shared_structural_module.iff, object/tangible/component/structure/shared_light_power_core_unit.iff, object/tangible/component/structure/shared_structure_small_storage_section.iff', '100, 200, 200, 10, 1, 1', '1, 1, 1', 'XX, XX, DR', '0, 0, 1', '');
INSERT INTO `draft_schematics` VALUES(16, 'Constrictor Cloth', 1070501512, 'craftBasicTissueGroup', 18, 1, 'craft_tissue_ingredients_n, craft_tissue_ingredients_n, craft_tissue_ingredients_n', 'protein_base, hormone_reactive_solution, psychoactive_solution', '0, 0, 0', 'creature_food, herbivore_meat, fungi', '20, 20, 10', '1, 1, 3, 1, 1, 3', 'XX, XX, FL, OQ, PE, XX, XX, FL, OQ, PE', '0, 0, 2, 5, 3, 0, 0, 2, 5, 3', '');
INSERT INTO `draft_schematics` VALUES(17, 'Swoop', 4231876597, 'craftArtisanVehicle', 20, 1, 'craft_vehicle_ingredients_n, craft_vehicle_ingredients_n', 'vehicle_body, structural_frame', '0, 0', 'nonferrous_metal, ferrous_metal', '1600, 6400', '1, 1, 1', 'XX, XX, SR', '0, 0, 1', '');
INSERT INTO `draft_schematics` VALUES(18, 'Stun Baton', 366533914, 'craftWeaponMeleeGroupE', 36, 3, 'craft_weapon_ingredients_n, craft_weapon_ingredients_n, craft_weapon_ingredients_n, craft_weapon_ingredients_n, craft_weapon_ingredients_n, craft_weapon_ingredients_n', 'unknown, unknown, unknown, unknown, unknown, unknown', '0, 0, 0, 0, 0, 1', 'polysteel_copper, steel, metal, byrothsis_crystalline_gemstone, object/tangible/component/item/shared_electronic_power_conditioner.iff, object/tangible/component/weapon/shared_reinforcement_core.iff', '18, 18, 10, 6, 2, 1', '1, 1, 1, 1, 1, 1, 1, 1', 'XX, XX, SR, SR, SR, SR, SR, SR', '0, 0, 1, 1, 1, 1, 1, 1', '');
INSERT INTO `draft_schematics` VALUES(19, 'Composite Armor Chestplate', 506032706, 'craftArmorPersonalGroupF', 15, 3, 'craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n', 'appearance_fragments, armor_core_frame, armor_core, load_bearing_harness, reinforcement, bio_enhancement_cartridge, appearance_enhancement, appearance_enhancement, unknown', '0, 0, 0, 0, 0, 0, 0, 0, 1', 'petrochem_fuel_solid_known, ore_intrusive, aluminum, fiberplast_naboo, copper_beyrllius, hide_wooly, object/tangible/component/clothing/shared_synthetic_cloth.iff, object/tangible/component/clothing/shared_reinforced_fiber_panels.iff, object/tangible/component/armor/shared_armor_segment_composite_advanced.iff', '100, 100, 60, 50, 50, 40, 1, 1, 4', '1, 1, 1, 1, 2, 2, 2, 2, 2', 'XX, XX, XX, XX, OQ, UT, OQ, UT, OQ, SR, OQ, UT, OQ, SR', '0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1', '');
INSERT INTO `draft_schematics` VALUES(20, 'Tantel Armor Chestplate', 1482977914, 'craftArmorPersonalGroupC', 30, 3, 'craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n, craft_armor_ingredients_n', 'unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown', '0, 0, 0, 0, 0, 0, 0, 0, 0', 'bone_avian, hide, hide_bristley, polymer, aluminum, hide_bristley, object/tangible/component/clothing/shared_synthetic_cloth.iff, object/tangible/component/clothing/shared_reinforced_fiber_panels.iff, object/tangible/component/armor/shared_armor_segment_zam.iff', '40, 40, 40, 25, 25, 25, 1, 1, 4', '1, 1, 1, 1, 2, 2, 2, 2, 2', 'XX, XX, XX, XX, OQ, UT, OQ, UT, OQ, SR, OQ, UT, OQ, SR', '0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1', '');
