ALTER TABLE `swgemu`.`characters` 
 ADD COLUMN `Health` MEDIUMINT UNSIGNED NOT NULL DEFAULT 900 AFTER `itemShift`,
 ADD COLUMN `Strength` MEDIUMINT UNSIGNED NOT NULL DEFAULT 450 AFTER `Health`,
 ADD COLUMN `Constitution` MEDIUMINT UNSIGNED NOT NULL DEFAULT 450 AFTER `Strength`,
 ADD COLUMN `Action` MEDIUMINT UNSIGNED NOT NULL DEFAULT 900 AFTER `Constitution`,
 ADD COLUMN `Quickness` MEDIUMINT UNSIGNED NOT NULL DEFAULT 450 AFTER `Action`,
 ADD COLUMN `Stamina` MEDIUMINT UNSIGNED NOT NULL DEFAULT 450 AFTER `Quickness`,
 ADD COLUMN `Mind` MEDIUMINT UNSIGNED NOT NULL DEFAULT 900 AFTER `Stamina`,
 ADD COLUMN `Focus` MEDIUMINT UNSIGNED NOT NULL DEFAULT 450 AFTER `Mind`,
 ADD COLUMN `Willpower` MEDIUMINT UNSIGNED NOT NULL DEFAULT 450 AFTER `Focus`,
 ADD COLUMN `HealthWounds` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0 AFTER `Willpower`,
 ADD COLUMN `ActionWounds` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0 AFTER `HealthWounds`,
 ADD COLUMN `MindWounds` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0 AFTER `ActionWounds`,
 ADD COLUMN `BattleFatigue` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0 AFTER `MindWounds`;
