/*
Copyright (C) 2007 <SWGEmu>
 
This File is part of Core3.
 
This program is free software; you can redistribute 
it and/or modify it under the terms of the GNU Lesser 
General Public License as published by the Free Software
Foundation; either version 2 of the License, 
or (at your option) any later version.
 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
See the GNU Lesser General Public License for
more details.
 
You should have received a copy of the GNU Lesser General 
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 
Linking Engine3 statically or dynamically with other modules 
is making a combined work based on Engine3. 
Thus, the terms and conditions of the GNU Lesser General Public License 
cover the whole combination.
 
In addition, as a special exception, the copyright holders of Engine3 
give you permission to combine Engine3 program with free software 
programs or libraries that are released under the GNU LGPL and with 
code included in the standard release of Core3 under the GNU LGPL 
license (or modified versions of such code, with unchanged license). 
You may copy and distribute such a system following the terms of the 
GNU LGPL for Engine3 and the licenses of the other code concerned, 
provided that you include the source code of that other code when 
and as the GNU LGPL requires distribution of source code.
 
Note that people who make modified versions of Engine3 are not obligated 
to grant this special exception for their modified versions; 
it is their choice whether to do so. The GNU Lesser General Public License 
gives permission to release a modified version without this exception; 
this exception also makes it possible to release a modified version 
which carries forward this exception.
*/

import "ResourceSpawn";
import "SpawnLocation";
import "../../objects/scene/SceneObject";

interface ResourceSpawn : implements SceneObject {
	ResourceSpawn(String& inType) {
		super();
	}
	
	void addSpawnLocation(SpawnLocation location);
	SpawnLocation removeSpawnLocation(unsigned int oid);
	SpawnLocation getSpawnLocation(int i);
	int getSpawnLocationSize();
	
	void setName(const String& inString);

	void setClass1(const String& inString);
	void setClass2(const String& inString);
	void setClass3(const String& inString);
	void setClass4(const String& inString);
	void setClass5(const String& inString);
	void setClass6(const String& inString);
	void setClass7(const String& inString);
	
	void setAtt1(const String& inString);
	void setAtt2(const String& inString);
	void setAtt3(const String& inString);
	void setAtt4(const String& inString);
	void setAtt5(const String& inString);
	void setAtt6(const String& inString);
	void setAtt7(const String& inString);
	void setAtt8(const String& inString);
	void setAtt9(const String& inString);
	void setAtt10(const String& inString);
	void setAtt11(const String& inString);

	void setAtt1Stat(int inInt);
	void setAtt2Stat(int inInt);
	void setAtt3Stat(int inInt);
	void setAtt4Stat(int inInt);
	void setAtt5Stat(int inInt);
	void setAtt6Stat(int inInt);
	void setAtt7Stat(int inInt);
	void setAtt8Stat(int inInt);
	void setAtt9Stat(int inInt);
	void setAtt10Stat(int inInt);
	void setAtt11Stat(int inInt);

	void setMaxType(int inInt);

	void setMinType(int inInt);

	void setMaxPool(int inInt);

	void setMinPool(int inInt);

	void setContainerName(const String& inString);

	// getters
	String& getName();

	String& getType();

	String& getClass1();
	String& getClass2();
	String& getClass3();
	String& getClass4();
	String& getClass5();
	String& getClass6();
	String& getClass7();
	
	String& getAtt1();
	String& getAtt2();
	String& getAtt3();
	String& getAtt4();
	String& getAtt5();
	String& getAtt6();
	String& getAtt7();
	String& getAtt8();
	String& getAtt9();
	String& getAtt10();
	String& getAtt11();
	
	int getAtt1Stat();
	int getAtt2Stat();
	int getAtt3Stat();
	int getAtt4Stat();
	int getAtt5Stat();
	int getAtt6Stat();
	int getAtt7Stat();
	int getAtt8Stat();
	int getAtt9Stat();
	int getAtt10Stat();
	int getAtt11Stat();
	
	int getMaxType();

	int getMinType();

	int getMaxPool();

	int getMinPool();

	String& getContainerName();

	void toString();
	
}
	