/*
				Copyright <SWGEmu>
		See file COPYING for copying conditions.*/

package server.zone.objects.installation.garage;

import server.zone.objects.installation.InstallationObject;
import server.zone.objects.area.ActiveArea;

class GarageInstallation extends InstallationObject {

	public GarageInstallation() {
		setLoggingName("GarageInstallation");
	}

	@preLocked
	public native void createChildObjects();
}
