/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

package server.zone;

import engine.core.ManagedService;

import server.zone.ZoneServer;
import server.zone.ZonePacketHandler;

import server.chat.ChatManager;
import server.zone.managers.objectcontroller.ObjectController;
import server.zone.managers.name.NameManager;
import server.zone.managers.holocron.HolocronManager;
import server.zone.managers.sui.SuiManager;
import server.zone.managers.player.PlayerManager;
import server.zone.managers.professions.ProfessionManager;
import server.zone.managers.object.ObjectManager;
import server.zone.managers.vendor.VendorManager;

class ZoneProcessServer extends ManagedService {
	@weak
	transient protected ZoneServer zoneServer;

	@local
	transient protected ZonePacketHandler zonePacketHandler;

	//Static Managers
	transient protected NameManager nameManager;
	
	transient protected HolocronManager holocronManager;

	transient protected SuiManager suiManager;
	
	transient protected ProfessionManager professionManager;

	transient protected VendorManager vendorManager;

	@weak
	transient protected ObjectController objectController;
	
	/*CombatManager combatManager;
	SkillManager skillManager;
	RadialManager radialManager;
	GroupManager groupManager;
	LootManager lootManager;
	*/
	
	public native ZoneProcessServer(ZoneServer server);

	public native void initialize();

	public native void finalize();

	// setters and getters
	@local
	public VendorManager getVendorManager() {
		return vendorManager;
	}

	public ZoneServer getZoneServer() {
		return zoneServer;
	}

	@local
	public ZonePacketHandler getPacketHandler() {
		return zonePacketHandler;
	}
	
	@local
	public ProfessionManager getProfessionManager() {
		return professionManager;
	}

	@local
	public ObjectController getObjectController() {
		return objectController;
	}

	public PlayerManager getPlayerManager() {
		return zoneServer.getPlayerManager();
	}

	@local
	public NameManager getNameManager() {
		return nameManager;
	}
	
	@local
	public HolocronManager getHolocronManager() {
		return holocronManager;
	}

	public ChatManager getChatManager() {
		return zoneServer.getChatManager();
	}

	@local
	public SuiManager getSuiManager() {
		return suiManager;
	}

	/*UserManager getUserManager() {
		return server.getUserManager();
	}

	CraftingManager getCraftingManager() {
		return server.getCraftingManager();
	}

	ItemManager getItemManager() {
		return server.getItemManager();
	}

	GuildManager getGuildManager() {
		return server.getGuildManager();
	}

	BankManager getBankManager() {
		return server.getBankManager();
	}

	MissionManager getMissionManager() {
		return server.getMissionManager();
	}

	CombatManager getCombatManager() {
		return combatManager;
	}

	SkillManager getSkillManager() {
		return skillManager;
	}

	RadialManager getRadialManager() {
		return radialManager;
	}

	GroupManager getGroupManager() {
		return groupManager;
	}

	LootManager getLootManager() {
		return lootManager;
	}*/
}
