/*
Copyright (C) 2007 <SWGEmu>
 
This File is part of Core3.
 
This program is free software; you can redistribute 
it and/or modify it under the terms of the GNU Lesser 
General Public License as published by the Free Software
Foundation; either version 2 of the License, 
or (at your option) any later version.
 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
See the GNU Lesser General Public License for
more details.
 
You should have received a copy of the GNU Lesser General 
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 
Linking Engine3 statically or dynamically with other modules 
is making a combined work based on Engine3. 
Thus, the terms and conditions of the GNU Lesser General Public License 
cover the whole combination.
 
In addition, as a special exception, the copyright holders of Engine3 
give you permission to combine Engine3 program with free software 
programs or libraries that are released under the GNU LGPL and with 
code included in the standard release of Core3 under the GNU LGPL 
license (or modified versions of such code, with unchanged license). 
You may copy and distribute such a system following the terms of the 
GNU LGPL for Engine3 and the licenses of the other code concerned, 
provided that you include the source code of that other code when 
and as the GNU LGPL requires distribution of source code.
 
Note that people who make modified versions of Engine3 are not obligated 
to grant this special exception for their modified versions; 
it is their choice whether to do so. The GNU Lesser General Public License 
gives permission to release a modified version without this exception; 
this exception also makes it possible to release a modified version 
which carries forward this exception.
*/

package server.zone;

import engine.service.proto.BasePacketHandler;
import engine.service.DatagramServiceThread;
import system.net.Socket;
import system.net.SocketAddress;
import system.net.Packet;
import engine.service.ServiceClient;
import engine.core.ManagedObject;
import engine.core.TaskManager;
import system.lang.Exception;
import system.util.Vector;

import server.zone.ZoneProcessServerImplementation;
import server.zone.managers.object.ObjectManager;
import server.zone.managers.player.PlayerManager;
import server.zone.Zone;
import server.chat.ChatManager;
import server.zone.managers.objectcontroller.ObjectController;
import server.zone.managers.radial.RadialManager;

import server.zone.objects.scene.SceneObject;

class ZoneServer extends ManagedObject implements DatagramServiceThread {
	BasePacketHandler phandler;
	
	ZoneProcessServerImplementation processor;

	int procThreadCount;
	
	native TaskManager taskManager;
	
	Vector<Zone> zones;
	
	ObjectManager objectManager;
	PlayerManager playerManager;
	ChatManager chatManager;
	ObjectController objectController;
	RadialManager radialManager;

	int totalSentPackets;
	
	int totalResentPackets;

	int currentPlayers;
	int maximumPlayers;
	int totalPlayers;
	int totalDeletedPlayers;
	
	int serverState;

	string name;
	string messageoftheDay;

	int galaxyID;
	
	public static final int OFFLINE = 0;
	public static final int LOADING = 1;
	public static final int ONLINE = 2;
	public static final int LOCKED = 3;
	
	public native ZoneServer(int processingThreads, int galaxyid = 2);
	
	public local native ServiceClient createConnection(Socket sock, dereferenced SocketAddress addr);
	
	public native void init();

	public native void run();

	public native void shutdown();

	public native void startManagers();

	public native void stopManagers();
	
	public native void start(int p, int mconn = 10);
	
	public native void stop();

	public local native void handleMessage(ServiceClient client, Packet message);

	public local native boolean handleError(ServiceClient client, dereferenced Exception e);
	
	public native void addTotalSentPacket(int count);
	public native void addTotalResentPacket(int count);
	
	public native void printInfo(boolean forcedLog = true);
	public native void printEvents();
	
	public native SceneObject getObject(unsigned long objectID, boolean doLock = true);
	public native SceneObject createObject(unsigned int templateCRC, unsigned long objectID = 0);
	public native void destroyObject(unsigned long objectID);

	public void fixScheduler() {
		//scheduler.fixQueue();
	}
	
	public native void changeUserCap(int amount = 50);

	public native int getConnectionCount();
	
	public void increaseOnlinePlayers() {
		lock();

		if (++currentPlayers > maximumPlayers)
			maximumPlayers = currentPlayers;

		++totalPlayers;

		unlock();
	}
	
	public void decreaseOnlinePlayers() {
		lock();
		
		currentPlayers = currentPlayers - 1; // for some reason it doesnt like --currentPlayers;
		
		unlock();
	}

	public void increaseTotalDeletedPlayers() {
		this.lock();

		++totalDeletedPlayers;

		this.unlock();
	}

	public native void lock(boolean doLock = true);
	
	public native void unlock(boolean doLock = true);

	public int getGalaxyID() {
		return galaxyID;
	}
	
	public native string getServerName();
	
	public boolean isServerLocked() {
		return serverState == LOCKED;
	}

	public boolean isServerOnline() {
		return serverState == ONLINE;
	}

	public boolean isServerOffline() {
		return serverState == OFFLINE;
	}

	public boolean isServerLoading() {
		return serverState == LOADING;
	}

	public int getServerState() {
		return serverState;
	}

	public Zone getZone(int index) {
		return zones.get(index);
	}

	public int getMaxPlayers() {
		return maximumPlayers;
	}

	public int getTotalPlayers() {
		return totalPlayers;
	}

	public int getDeletedPlayers() {
		return totalDeletedPlayers;
	}
	
	public PlayerManager getPlayerManager() {
		return playerManager;
	}
	
	public ChatManager getChatManager() {
		return chatManager;
	}
	
	public ObjectController getObjectController() {
		return objectController;
	}
	
	public RadialManager getRadialManager() {
		return radialManager;
	}

	/*public time_t getStartTimestamp() {
		return startTimestamp;
	}*/
	
	public native void setServerName(final string servername);

	public void setGalaxyID(int galaxyid) {
		galaxyID = galaxyid;
	}

	public void setServerState(int state) {
		lock();

		serverState = state;

		unlock();
	}
	
	public native void setServerStateLocked();

	public native void setServerStateOnline();
	
	public native void loadMessageoftheDay();

	public native void changeMessageoftheDay(final string newMOTD);
	public native string getMessageoftheDay();
}
