/*
Copyright (C) 2007 <SWGEmu>

This File is part of Core3.

This program is free software; you can redistribute
it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software
Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General
Public License along with this program; if not, write to
the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Linking Engine3 statically or dynamically with other modules
is making a combined work based on Engine3.
Thus, the terms and conditions of the GNU Lesser General Public License
cover the whole combination.

In addition, as a special exception, the copyright holders of Engine3
give you permission to combine Engine3 program with free software
programs or libraries that are released under the GNU LGPL and with
code included in the standard release of Core3 under the GNU LGPL
license (or modified versions of such code, with unchanged license).
You may copy and distribute such a system following the terms of the
GNU LGPL for Engine3 and the licenses of the other code concerned,
provided that you include the source code of that other code when
and as the GNU LGPL requires distribution of source code.

Note that people who make modified versions of Engine3 are not obligated
to grant this special exception for their modified versions;
it is their choice whether to do so. The GNU Lesser General Public License
gives permission to release a modified version without this exception;
this exception also makes it possible to release a modified version
which carries forward this exception.
*/

package server.zone.objects.creature;

import engine.lua.LuaObject;
import system.util.Vector;
import system.lang.Time;
import server.zone.Zone;
import system.util.SortedVector;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.creature.events.AiThinkEvent;
import server.zone.objects.creature.events.AiMoveEvent;
import server.zone.objects.creature.events.AiWaitEvent;
import server.zone.objects.creature.events.AiAwarenessEvent;
import system.lang.ref.Reference;
import server.zone.packets.scene.AttributeListMessage;
import server.zone.objects.creature.CreatureObject;
import server.zone.objects.tangible.weapon.WeaponObject;
include server.zone.objects.creature.PatrolPointsVector;
include server.zone.objects.creature.PatrolPoint;
include server.zone.objects.scene.WorldCoordinates;
import engine.core.ManagedObject;
import server.zone.objects.tangible.TangibleObject;
import server.zone.objects.tangible.weapon.WeaponObject;
import server.zone.templates.SharedObjectTemplate;
import server.zone.templates.mobile.CreatureTemplate;
import server.zone.objects.creature.events.DespawnCreatureOnPlayerDissappear;
include server.zone.objects.creature.variables.CreatureAttackMap;
import engine.util.u3d.Coordinate;
import server.zone.objects.creature.commands.QueueCommand;
import engine.util.Observable;
import server.zone.objects.creature.AiObserver;

class AiAgent extends CreatureObject {
	protected transient AiThinkEvent thinkEvent;
	
	protected transient AiMoveEvent moveEvent;
	
	protected transient AiWaitEvent waitEvent;
	
	protected transient AiAwarenessEvent awarenessEvent;
	
	@dereferenced
	protected Vector<string> skillCommands;
	
	@dereferenced
	protected PatrolPointsVector patrolPoints;
	
	@dereferenced
	protected PatrolPoint homeLocation;
	
	@dereferenced
	protected PatrolPoint nextStepPosition;
	
	@dereferenced
	protected SortedVector<AiObserver> aiObserverMap;
	
	@dereferenced
	protected Vector<WeaponObject> weapons;
	
	protected transient CreatureTemplate npcTemplate;
	protected transient SharedObjectTemplate objectTemplate;
	
	protected transient CreatureObject lootOwner;
	
	protected boolean baby;
	
	protected boolean despawnOnNoPlayerInRange;
	
	//@weakReference
	protected SceneObject followObject;
	protected unsigned int followState;
	
	protected boolean fleeing;
	
	protected float respawnTimer;
	protected int numberOfPlayersInRange;
	
	protected transient DespawnCreatureOnPlayerDissappear despawnEvent;
	
	public static final int UPDATEMOVEMENTINTERVAL = 1000; // msec
	
	public static final unsigned int OBLIVIOUS = 0;
	public static final unsigned int WATCHING = 1;
	public static final unsigned int STALKING = 2;
	public static final unsigned int FOLLOWING = 3;
	
	public AiAgent() {
		baby = false;
		
		followState = OBLIVIOUS;

		respawnTimer = 0;
		
		despawnOnNoPlayerInRange = true;
		numberOfPlayersInRange = 0;

		objectTemplate = null;
		npcTemplate = null;
		lootOwner = null;
		
		Logger.setLoggingName("AiAgent");
		Logger.setLogging(false);
		Logger.setGlobalLogging(true);
	}
	
	/**
	 * Initializes the transient members of SceneObject, must call the inherited object method first.
	 * @pre {transient members are not initialized }
	 * @post { transient members are initialized }
	 */
	public native void initializeTransientMembers();
	
	public void finalize() {
		Logger.info("deleting from ram", true);
	}
	
	public abstract native void activateRecovery();
	
	public abstract native void activateMovementEvent();
	
	public abstract native void activateWaitEvent();
	
	public native void activateAwarenessEvent(CreatureObject target);
	
	public native boolean tryRetreat();
	
	public native void doRecovery();
	
	public native void doMovement();
	
	protected native boolean findNextPosition(float maxDistance, WorldCoordinates nextPosition);
	
	@local
	public abstract void doAwarenessCheck(@dereferenced Coordinate start, unsigned long time, CreatureObject target) {
		
	}
		
	public native void checkNewAngle();
	
	public native void fillAttributeList(AttributeListMessage msg, CreatureObject object);
	
	public native void setNextPosition(float x, float z, float y, SceneObject cell = null);
	
	@local
	public native void updateCurrentPosition(PatrolPoint point);
	
	@local
	public native void broadcastNextPositionUpdate(PatrolPoint point);
	
	public void clearPatrolPoints() {
		patrolPoints.removeAll();
	}
	
	@local
	public native void notifyInsert(QuadTreeEntry entry);
	
	@local
	public native void notifyDissapear(QuadTreeEntry entry);
	
	/**
	 * Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
	 * @pre { templateData is a valid pointer }
	 * @post { TangibleObject members are initialized }
	 * @param templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
	 */
	@local
	public native void loadTemplateData(SharedObjectTemplate templateData);
	
	@local
	public native void loadTemplateData(CreatureTemplate templateData);
	
	/**
	 * Inflicts damage into the object
	 * @pre { this object is locked }
	 * @post { this object is locked }
	 * @return unused for now
	 */
	public native int inflictDamage(TangibleObject attacker, int damageType, int damage, boolean destroy, boolean notifyClient = true);
	
	/**
	 * sends the conversation notification 
	 * @pre {this locked, player locked }
	 * @post { this locked, player locked }
	 */
	public native void sendConversationStartTo(SceneObject player);
	
	/**
	 * sends the default conversation list
	 * @pre {this locked, player locked }
	 * @post {this locked, player locked }
	 */
	public native void sendDefaultConversationTo(SceneObject player);
	
	/**
	 * sends the conversation list 
	 * @pre {this locked, player locked }
	 * @post { this locked, player locked }
	 */
	public native void selectConversationOption(int option, SceneObject obj);
	
	/**
	 * Is called when this object is destroyed
	 * @pre { this, attacker locked }
	 * @post { this, attacker locked }
	 */
	public native int notifyObjectDestructionObservers(TangibleObject attacker, int condition);
	
	/**
	 * Is called when an object is talked to
	 * @pre { this, converser locked }
	 * @post {this, converser locked }
	 */
	public native int notifyConverseObservers(CreatureObject converser);

	public native int notifyAttack(Observable observable);
	public native int notifyCallForHelp(Observable observable, ManagedObject arg1);
	
	public native void activatePostureRecovery();
	
	/**
	 * Cleares the combat state
	 * @pre { this object is locked }
	 * @post { this object is locked, this object is not in a combat state }
	 * @param clearDefenders if true the defender vector willl be emptied
	 */
	public native void clearCombatState(boolean clearDefenders = true);
	
	/**
	 * Sets the active defender
	 * @pre { this object is locked }
	 * @post { this object is locked, defender is active }
	 * @param defender SceneObject to set as the active defender
	 */
	public native void setDefender(SceneObject defender);
	
	/**
	 * Adds a SceneObject to the defender vector
	 * @pre { this object is locked }
	 * @post { this object is locked, defender is in the defender vector }
	 * @param defender SceneObject to add to the defender vector
	 */
	public native void addDefender(SceneObject defender);
	
	/**
	 * Removes the specified defender from the defender vector
	 * @pre { this object is locked }
	 * @post { this object is locked, defender is not in the defender vector }
	 * @param defender SceneObject to remove from the defender vector
	 */
	public native void removeDefender(SceneObject defender);
	
	public native void setDespawnOnNoPlayerInRange(boolean val);
	
	/**
	 * Gets called when the creature was despawned
	 */
	public native void notifyDespawn(Zone zone);
	
	public abstract native void scheduleDespawn(); 
	
	/**
	 * Respawns creature to specified zone with home location position
	 */
	public native void respawn(Zone zone, int level);
	
	@local
	public void addPatrolPoint(@dereferenced PatrolPoint point) {
		patrolPoints.add(point);
	}
	
	public void setHomeLocation(float x, float z, float y, SceneObject cell = null) {
		homeLocation.setPosition(x, z, y);
		homeLocation.setCell(cell);
		homeLocation.setReached(true);
	}
	
	public void setRespawnTimer(float resp) {
		respawnTimer = resp;
	}
	
	/**
	 * Evaluates if this object can be attacket by the passed creature object
	 * @pre { this object is locked }
	 * @post { this object is locked }
	 * @return returns true if the creature object can attack this 
	 */
	public boolean isAttackableBy(CreatureObject object) {
		if (object == this)
			return false;
		
		if (super.pvpStatusBitmask == 0)
			return false;
		
		if (this.isRetreating())
			return false;
		
		if (this.isDead())
			return false;
		
		return true;
	}
	
	/**
	 * Evaluates if this creature is aggresive to the object
	 * @pre { }
	 * @post { }
	 * @return returns true if its aggressive
	 */
	public boolean isAggressiveTo(CreatureObject object) {
		if (!isAttackableBy(object))
			return false;
		
		if (super.pvpStatusBitmask & CreatureFlag.AGGRESSIVE)
			return true;
		
		return false;
	}
	
	public void setOblivious() {
		followState = OBLIVIOUS;
		setTargetObject(null);
		activateMovementEvent();
	}
	
	public void setWatchObject(SceneObject obj) {
		if (this.isRetreating())
			return;
		
		followState = WATCHING;
		
		setTargetObject(obj);
		activateMovementEvent();
	}
	
	public void setStalkObject(SceneObject obj) {
		if (this.isRetreating())
			return;
		
		followState = STALKING;
		
		setTargetObject(obj);
		activateMovementEvent();
	}
	
	public void setFollowObject(SceneObject obj) {
		if (this.isRetreating())
			return;
		
		followState = FOLLOWING;
		
		setTargetObject(obj);
		activateMovementEvent();
	}
	
	public void setTargetObject(SceneObject obj) {
		if (followObject != obj) {
			clearPatrolPoints();

			followObject = obj;
		}
	}
	
	public native void selectWeapon();
	public native boolean validateStateAttack(CreatureObject target, string args);
	
	public boolean isRetreating() {
		return !homeLocation.isReached();
	}
	
	public boolean isFleeing() {
		return fleeing;
	}
	
	public native void clearDespawnEvent();
	
	public float getKinetic() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getKinetic();
	}
	
	public float getEnergy() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getEnergy();
	}
	
	public float getElectricity() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getElectricity();
	}
	
	public float getStun() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getStun();
	}
	
	public float getBlast() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getBlast();
	}
	
	public float getHeat() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getHeat();
	}
	
	public float getCold() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getCold();
	}
	
	public float getAcid() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getAcid();
	}
	
	public float getLightSaber() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getLightSaber();
	}
	
	public boolean isStalker() {
		if (npcTemplate == null)
			return false;
		
		return npcTemplate.isStalker();
	}
	
	public boolean isKiller() {
		if (npcTemplate == null)
			return false;
		
		return npcTemplate.isKiller();
	}
	
	public unsigned int getFerocity() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getFerocity();
	}
	
	public unsigned int getArmor() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getArmor();
	}
	
	public boolean getDespawnOnNoPlayerInRange() {
		return despawnOnNoPlayerInRange;
	}
	
	public int getNumberOfPlayersInRange() {
		return numberOfPlayersInRange;
	}
	
	public string getFactionString() {
		if (npcTemplate == null)
			return "";
		
		return npcTemplate.getFaction();
	}
	
	public string getSocialGroup() {
		if (npcTemplate == null)
			return "";
		
		return npcTemplate.getSocialGroup();
	}
	
	public float getChanceHit() {
		if (npcTemplate == null)
			return false;
		
		return npcTemplate.getChanceHit();
	}
	
	public int getDamageMin() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getDamageMin();
	}
	
	public int getDamageMax() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getDamageMax();
	}
	
	public int getBaseXp() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getBaseXp();
	}
	
	public unsigned int getDiet() {
		if (npcTemplate == null)
			return 0;
		
		return npcTemplate.getDiet();
	}
	
	@local
	public CreatureAttackMap getAttackMap() {
		if (npcTemplate == null)
			return null;
		
		return npcTemplate.getAttacks();
	}
	
	public float getRespawnTimer() {
		return respawnTimer;
	}
	
	@local
	public PatrolPoint getHomeLocation() {
		return homeLocation;
	}
	
	public boolean isAiAgent() {
		return true;
	}
	
	public void setLootOwner(CreatureObject owner) {
		lootOwner = owner;
	}
	
	public CreatureObject getLootOwner() {
		return lootOwner;
	}
	
	/*
	 * Place holder for when loot is implemented
	 */
	public boolean hasLoot() {
		return false;
	}
}
